### ISSUE TITLE
True/False are not suggested as trigger/procedure arguments

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#100]
When you call a trigger with a boolean parameter, IntelliSense doesn't suggest True/False as possible arguments:

![image](https://cloud.githubusercontent.com/assets/1166791/23261573/207ce622-f9d7-11e6-9ca7-4db3dcf767c8.png)

The same goes for procedures that have boolean parameters:

![image](https://cloud.githubusercontent.com/assets/1166791/23261624/6e1c63d0-f9d7-11e6-9dfa-1a4844a7cbf6.png)

**Comment by StanislawStempin** [comment]
We have added your suggestion to the long term backlog.
