### ISSUE TITLE
Task scheduler

### ISSUE THREAD

**Issue by rslovak** [Microsoft/AL#1001]
Task scheduler doesn't work. I tried to change the parameter in CustomSettings.config but it didn't help.

<add key="EnableTaskScheduler" value="true" />

The Job queue is also not working.

Roman

**Comment by StanislawStempin** [comment]
Hi Roman, as this issue is not related to AL or development environment I would recommend that you contact regular support. To my knowledge task scheduler should work as before and is just a matter of proper configuration.
