### ISSUE TITLE
Page conversion into new syntax: Same name for fields, groups, actions leads to errors

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#1002]
After the export of pages with new syntax, it seems to me, that the group, action, field names are taken from the caption property. If an action has the same caption as a field on the page, the compiler complains about that. "A member with Name '...' already exists.
It would be nice if you could solve this. Otherwise I have to correct several pages each time I export the objects with new Syntax.
![captiondoublecall1](https://user-images.githubusercontent.com/34025722/33320703-6576af64-d443-11e7-9784-47d8bc6f95ee.png)
![captiondoublecall2](https://user-images.githubusercontent.com/34025722/33320704-65c0fe3e-d443-11e7-95b5-8fa6c04b43b9.png)

**Comment by esbenk** [comment]
If you give the control and action different names in C/SIDE then those will be used. That will solve you problem with the current bits.

**Comment by MaKnauer** [comment]
Ok fine. then I have to do some work. :)
