### ISSUE TITLE
Nav 2017 development with VS Code AL

### ISSUE THREAD

**Issue by PhilDOakley** [Microsoft/AL#1005]
I seem to be banging my head against the wall here and beginning to think this is not possible so I thought I would ask. I want to use VS Code to develop extensions in Nav 2017. I have a Nav 2017 installation on a server and I have VS Code installed on my PC. I have previously written an extension and worked with a local copy of Tenerife so I know basically what is required. 
My issue is that using the remote Nav 2017 I am unable to download symbols from the remote server no matter what I try. I have searched the internet and did not find any pointer for this so beginning to wonder if this is possible. When I try to download the symbols from the remote server I get a Microsoft Office login pop up. The remote server is on-premise. My launch.json has the details of the remote on-premise server and the port, service tier specified. Anyone have some help on this?
"type": "al",
            "request": "publish",
            "projectRoot": "${workspaceRoot}",
            "packageFileName": "${command:resolvePackageFileName}",
            "name": "2017Demo",
            "server": "nav2017demo.oakleyintegrate.co.uk",
            "serverInstance": "pdweb",
            "tenant": "default",
            "windowsAuthentication": false,
            "startupObjectId": 22,
            "port": 9049

**Comment by johndcollins** [comment]
It's not possible to do Extensions V2 on 2017. Only 2018 and forward.

**Comment by PhilDOakley** [comment]
Thanks
