### ISSUE TITLE
Variant casting request

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1006]
At this time we use a number of dotnet objects in C/AL that are replaced with new classes in AL. Some of these work on a global scope. 

To be compatible with NAV and extensions we would like to use variants at the global scope, and cast them to NAV and extension versions in the local scope. At this time we know we would need: 

XmlDocument
XmlElement
XmlNamespaceManager

**Comment by esbenk** [comment]
Just to clarify, you want

Variant := XmlDocument;
XmlDocument := Variant

I'm not sure I understand the compatibility part of the question. Can you be more specific?

**Comment by strophanthus** [comment]
Yes, that would help. 

I have a codeunit that builds xml documents since we have some syntax requirements that XMLPorts do not handle. 

This codeunit has a global document and element that are used for building the xml document, as well as the namespacemanager to assist with part of the unique syntax requirements. 

Using vars at the global scope will allow much simpler code and less duplication of code, since they can be used as variants in most of the cases. Where they can't they would be assigned to a local variable of the type required. Automating variable replacement is simpler in the local scope. 

Having these classes available in CSIDE would help somewhat but we still need our products to be compatible with NAV versions prior to 2018.

**Comment by esbenk** [comment]
Your plan is to do primary development in C/SIDE and forward migrate into AL whenever you make changes? And using variants will make the migration easier?
Just want to understand the underlying problem.

**Comment by strophanthus** [comment]
Yes, that is the case due to our existing products being used by a number of NAV only clients.
