### ISSUE TITLE
OData V4 Bound Actions for pages in AL

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#1009]
I'm using latest November-development-preview (with AL Language Extension 0.11.14434) and I'm trying to create a new page that will be published as OData V4 service with bound actions as part of Extension 2.0. 

I'm receiving a couple of errors here for this function:
````
  [ServiceEnabled]
  [Scope('Personalization')]
  procedure Post(var ActionContext : DotNet "'Microsoft.Dynamics.Nav.Ncl, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.Microsoft.Dynamics.Nav.Runtime.WebServiceActionContext");
  var
    SalesHeader : Record "Sales Header";
    SalesInvoiceHeader : Record "Sales Invoice Header";
  begin
    GetDraftInvoice(SalesHeader);
    PostInvoice(SalesHeader,SalesInvoiceHeader);
    SetActionResponse(ActionContext,SalesInvoiceHeader.Id);
  end; 
````
First, AL compiler does not recognize the attribute:
````
[AL] ServiceEnabled is not a valid attribute
ServiceEnabled()
````
Also, Bound Actions **accepts a parameter of .NET type**, so there is no way to add that in AL.  

Does that mean that we won't be able to add our custom Bound Actions through extensions 2.0?

**Comment by StanislawStempin** [comment]
This is currently not possible. We will prioritize this scenario

**Comment by ivandjordjevic** [comment]
Thanks!

**Comment by tfenster** [comment]
@StanislawStempin Any feedback on this? This still seems not to be possible. Any workarounds for this?

**Comment by slavakos** [comment]
@StanislawStempin Any progress on this? As I understand, currently there's no possibility to call a function via REST/OData, and the only way to do that is to use SOAP just for this purpose...

**Comment by StanislawStempin** [comment]
This feature will be shipping in July preview later this week.
