### ISSUE TITLE
Adding OData V4 NavigationProperty on Custom List page that's publsihed as Web Service

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#1010]
I'm using latest November-development-preview (with AL Language Extension 0.11.14434) and I'm trying to create a **new list page that will be published as OData V4 service with additional NavigationProperty** as part of Extension 2.0. 

The goal would be to have similar behavior as in native SalesInvoices entity that allows you to add '$expand=SalesInvoicessalesInvoiceLines' in OData url to retrive SalesInvoices with lines. Example would be: 
````
.../ODataV4/Company(<CompanyName>)/SalesInvoices?$expand=SalesInvoicessalesInvoiceLines
````
However when I try to create my own List page through extensions 2.0 with subform for document lines I receive the error: 
````
[AL] A control of type 'Part' is not allowed in a parent control of type 'Repeater'
````
This would make sense in old NAV, but now we need ability to add our own additional navigational data for our custom OData services in AL.

**Comment by StanislawStempin** [comment]
We blocked this construct because on normal pages it was causing the client to crash. It makes sense to allow this on web service pages.

Are you using PageType = API for your pages? We are considering enabling it only in that case.

**Comment by ivandjordjevic** [comment]
I was using regular List Page type.  Can we use API pages within our extensions on D365? I understood that API is still not extensible so we should use OData services in extensions.

**Comment by atoader** [comment]
Hi @ivandjordjevic ! Sorry for taking so long to come back to you. Have you found a solution to your problem?

**Comment by StanislawStempin** [comment]
We will allow this pattern in the compiler
