### ISSUE TITLE
Codeunit 7000 Sales Price Calc. Mgt.: set functions as GLOBAL

### ISSUE THREAD

**Issue by LKostiuk** [Microsoft/AL#1012]
Codeunit 7000 - Function CalcBestUnitPrice - set as GLOBAL
Codeunit 7000 - Function CalcBestLineDisc- set as GLOBAL
Thank you!

**Comment by shalu712** [comment]
Hi Team, I need same in NAV 2018 NA CU3 . Please let me know how to get it.
