### ISSUE TITLE
Expressions are not supported for page properties

### ISSUE THREAD

**Issue by sd484** [Microsoft/AL#1014]
I C/AL you are able to define expressions for properties that are evaluated into a Boolean (e.g. page 346, Item Picture, property Visible of action TakePicture). You can also use expressions in AL. The extension can be built and published, but as soon as you open the page in the WebClient / RTC an error message appears.

**Comment by esbenk** [comment]
Is it only when using a page property that the client crashes.

**Comment by sd484** [comment]
Maybe this belongs to issue #828. I've tried following expression: Visible=SomeBoolean AND (AnotherBoolean = false)
false is unknown.

**Comment by DominikDitoIvosevic** [comment]
The issue exists in CSIDE as well. True and false do not exist. Use

Visible = SomeBoolean and (Not AnotherBoolean) for now, we may add later

**Comment by esbenk** [comment]
I think that the expression evaluator which is used client-side requires uppercase TRUE/FALSE.

**Comment by DominikDitoIvosevic** [comment]
@esbenk is correct. You need to capitalize the boolean values like TRUE and FALSE for now like in CSIDE
