### ISSUE TITLE
Default value for ValidateTableRelation property

### ISSUE THREAD

**Issue by sd484** [Microsoft/AL#1015]
In C/AL, the default value for the ValidateTableRelation property is Yes and does not need to be explicitly defined. In AL, you must define the property explicitly so that the table relation is validated when you enter values into a field.

Also when converting C/AL objects to AL objects, the property is not added. You have to revise all converted objects.

It would be good if AL behaves in the same way as C/AL.

**Comment by MikeGlue** [comment]
I completely agree. To me, validating the table relationship is what I would want 98% of the time. The exception I think would be to disable that. Having to enable it on almost every field seems unnecessary.

**Comment by epernst** [comment]
That kind of explain a few issues I had, so to say. I would certainly expect that they would default to the same value. Or at least the default value was always visible from intellisense.

**Comment by kalberes** [comment]
This has been fixed and will be available on the next release. Unfortunately it did not make it to the Nav 2018 release though,

**Comment by epernst** [comment]
Great - and a holiday update? 
So there will both be a december update, a holiday update and a january update? 👍
