### ISSUE TITLE
How to work with dependencies and tableextensions?

### ISSUE THREAD

**Issue by sd484** [Microsoft/AL#1018]
I have tried to manage my solution into several extensions and run into an issue. I don't know whether or not it is a bug.

I have defined a table in a extension (A). In another extension (B) I tried to extend the table from extension A. The extension B built without any error, but when publishing extension B an internal error occurs:
The request for path /NAV/dev/apps failed with code 422. Reason: Extension compilation failed
error AL0999: Internal error: 'Object reference not set to an instance of an object.', Stack trace=unknown

Extension A has been published before publishing extension B. 
The same error occurs when using page extensions, too.

I can imagine that table extensions are not (currently) supported for tables from other extensions. In this case, the build process should fail. 

If I assume that MS will provide the localizations as extensions in the future, for example, what is the procedure for ISVs if additional fields are needed in the localization tables?

**Comment by DominikDitoIvosevic** [comment]
One known bug which has been fixed but is pending release is that there are issues when depending on an extension which has a label global variable. Then we get an exception when building the depending extension.

Could you try creating a small repro for us? (also not just a picture but something copy pasteable)

**Comment by StanislawStempin** [comment]
Table extensions for tables originating from other extensions is possible and your scenario should work. You are most likely running into the issue describe by Dominik above.

**Comment by jimmymcp** [comment]
I think I might have run into the same thing. Attempting to publish an extension that is dependent upon another that is already published.

"The request for path /ExtensionTesting/dev/apps failed with code 422. Reason: Extension compilation failed
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown"

Can't find anything else to go on in event viewer. I am using Labels in the underlying extension.

**Comment by DominikDitoIvosevic** [comment]
could you try commenting out the labels in the dependant extension and retry building this extension?
it's a know issue which has been fixed and is pending release
