### ISSUE TITLE
Integrating AL into TFS Code Search

### ISSUE THREAD

**Issue by kine** [microsoft/AL#102]
Not an issue, but question/request:
Do you expect that the AL code will be searchable by TFS Code Search functionality? I do not mean by text search, but by the context search, where you can search for method, property, caller, parameter etc. Will be great...

**Comment by StanislawStempin** [comment]
This is a good suggestion. It is currently not in our plans to implement this integration. 
It requires more investigation into Code Search itself, most important being if there is even an extensibility model for adding more languages other than C#, C, C++, VB.NET and Java.

**Comment by pborring** [comment]
I am going to close this rather old feedback item, and propose opening an idea on http://aka.ms/bcideas to track this instead if still relevant.
