### ISSUE TITLE
error AL0296: The type or method 'Media Resources' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by gudrunleos** [Microsoft/AL#1020]
This was not a problem in the november release.
We need this to get our wizards to look the best ;)
image: navdocker.azurecr.io/dynamics-nav:11.0.19494.0-finus
app.json - "target": "Extension"

**Comment by dennisfrostlander** [comment]
Media Resources table contains cross-tenant data, therefore direct access cannot be provided in the cloud environment (where multiple tenants share the same database).
Could you please let us know which information you need from this table? Perhaps there already exist base app codeunits for finding the necessary data.

**Comment by gudrunleos** [comment]
We are using this to display the header ribbon in a wizard:
![image](https://user-images.githubusercontent.com/24827406/33489271-4f2ebdd6-d6ab-11e7-8318-a0bbbd9315f5.png)

**Comment by dennisfrostlander** [comment]
Thanks, we are looking at the alternative way to expose this information. Will keep you posted.

**Comment by dennisfrostlander** [comment]
After further discussion, Media Resources have been unblocked for extension development. You should use the new system symbols Microsoft_System_11.0.1292**7**.0.app from the next docker image.

**Comment by dennisfrostlander** [comment]
Expected in build >= 11.0.19614.0

**Comment by KristofKlein** [comment]
> After further discussion, Media Resources have been unblocked for extension development. You should use the new system symbols Microsoft_System_11.0.12927.0.app from the next docker image.

What do you mean with this? How do I do this? Sync-NAVApp ? Copy it around?

**Comment by dennisfrostlander** [comment]
If you would like to apply symbols to the existing database (from an earlier release), you need to unpublish the old package and publish the new one:
```PowerShell
Unpublish-NAVApp -ServerInstance MyServer -Name System
Publish-NAVApp -ServerInstance MyServer -Path '.\Microsoft_System_11.0.12927.0.app' -PackageType SymbolsOnly
```
If you use the database from the new build (as specified), it should come with the updated System symbols already.

After the symbols are updated in the database, you need to clean up the `.alpackages` folder in the VSCode project and run `F1 -> AL: Download symbols` command again.

**Comment by gudrunleos** [comment]
Just updated to Build 19590 (navdocker.azurecr.io/dynamics-nav:11.0.19590.0-finus) getting 
Microsoft_System_11.0.12926.0.app  - no sign of Microsoft_System_11.0.129270.app anywhere

Am I missing something?

**Comment by dennisfrostlander** [comment]
19590 seems still older than needed. You'd need >= 19614.

**Comment by gudrunleos** [comment]
Is that one available?

**Comment by gudrunleos** [comment]
closing the issue - solved in Build 19829 :)
