### ISSUE TITLE
Please refactor the new Event OnAfterAssignFieldsForNo(...) in Table 39

### ISSUE THREAD

**Issue by navlarste** [Microsoft/AL#1022]
One more parameter has to be Property=AsVar in
TAB39 OnAfterAssignFieldsForNo(...)

Problem:
•	Parameter “xRec” with the field Quantity is used to set Rec. Quantity on the Purchase Line
Quantity := xRec.Quantity;
It is the only way  to reach the Quantity on the Purchase Line.

Solution:
•	Parameter “xRec” must be changed to Property=AsVar

Delta file built on CTP17 W1:
[TAB39.zip](https://github.com/Microsoft/AL/files/1517970/TAB39.zip)

**Comment by thpeder** [comment]
Rec, the first parameter, is VAR and you can access the Quentity field there.

**Comment by navlarste** [comment]
It is not possible to change the Quantity by Rec, it must be done by the xRec
The reason to this is the line marked on the screen dump
Quantity := xRec.Quantity;

![2017-12-11_14h04_58](https://user-images.githubusercontent.com/32996357/33832631-26b2aa32-de7d-11e7-8ab4-ac6bc291a136.png)


It is not like that on Table 37, there it works fine with Rec.
