### ISSUE TITLE
Cue Setup table isn't ISV suffix friendly

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#1028]
In order to use the Cue Setup table from an ISV solution, a Cue Setup table ID must be stored in the native Cue Setup table. However, the table relation on Cue Setup is:
AllObjWithCaption."Object ID" WHERE (Object Type=CONST(Table),Object Name=FILTER(*Cue))

That means that if the ISV has standardized on using object name suffixes, the ISV's table ID will not be able to be validated into Cue Setup (as its name will not end in "Cue").

**Comment by bachii1010** [comment]
Hi 

According to microsoft you can either use suffix or prefix so instead of suffix you can use prefix then it will end with "Cue".
