### ISSUE TITLE
Error publishing extension from VS Code after changing service user

### ISSUE THREAD

**Issue by rrrezende** [Microsoft/AL#1031]
Hello,

I just installed the newly released NAV 2018 and VS Code publishing was working, except when opening the web client using debug-context (I had to remove the parameter from the URL).

I was using a regular user to run the service and then changed it to NETWORK SERVICE and enabled debugging.

Now publishing doesn't work anymore, and the error message is incomplete:

> [2017-12-01 11:19:58.92] Sending request to http://localhost:7049/DynamicsNAV110/dev/apps
> [2017-12-01 11:20:03.07] The request for path /DynamicsNAV110/dev/apps failed with code InternalServerError. Reason: 

I checked the event log and don't see anything relevant to this.

Is there anything else I can do to diagnose this?

**Comment by rrrezende** [comment]
Strangely enough, the error stopped after I restored a new demo database from the installation folder, but debuggingcontext still doesn't work:

![image](https://user-images.githubusercontent.com/24936737/33493039-16025b94-d6a6-11e7-933f-1962d5651297.png)

On event log:

> 
> Server instance: DynamicsNAV110
> Tenant ID: 
> <ii>User: REZENDE\rafael
> Type: System.NullReferenceException
> Message: <ii>Object reference not set to an instance of an object.</ii>
> StackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntime.EnsureDetachedFromConnection(NavSession session)
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.ShutdownDebuggingEnvironment(NavBaseException& firstCaughtException)
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.InnerDispose()
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.<DisposeAsync>d__127.MoveNext()
> Source: Microsoft.Dynamics.Nav.Ncl
> HResult: -2147467261
> </ii>

Then

> 
> Server instance: DynamicsNAV110
> Tenant ID: 
> <ii>User: REZENDE\rafael
> Type: System.NullReferenceException
> Message: <ii>Object reference not set to an instance of an object.</ii>
> StackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntime.EnsureDetachedFromConnection(NavSession session)
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.ShutdownDebuggingEnvironment(NavBaseException& firstCaughtException)
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.InnerDispose()
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.<DisposeAsync>d__127.MoveNext()
> Source: Microsoft.Dynamics.Nav.Ncl
> HResult: -2147467261
> </ii>

Then

> 
> Server instance: DynamicsNAV110
> Tenant ID: 
> <ii>User: REZENDE\rafael
> Type: System.InvalidOperationException
> Message: <ii>Dynamic operations can only be performed in homogenous AppDomain.</ii>
> StackTrace:
>      at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
>      at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>      at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.DebuggerHub.OnDebuggeeConnected(Object sender, DebugSessionStartEventArgs eventArgs)
>      at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.OnDebuggingSessionStarted(DebugSessionStartEventArgs e)
>      at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.CreateRuntime(String debuggingContext, NavSession session, Boolean waitForDebugAdapterConfiguration)
>      at Microsoft.Dynamics.Nav.Runtime.NavSession.StartDebuggingSession(String debuggingContext, Boolean waitForDebugAdapterConfiguration)
>      at Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(ConnectionRequest connectionRequest)
>      at SyncInvokeOpenConnection(Object , Object[] , Object[] )
>      at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
>      at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
> Source: System.Core
> HResult: -2146233079
> </ii>

**Comment by kalberes** [comment]
I know no one reads the documentation but here it is what you have to do:
https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-debugging

"To enable debugging the NetFx40_LegacySecurityPolicy setting in the Microsoft.Dynamics.Nav.Server.exe.config file must be set to false. This requires a server restart."

The reason is that the CAS setting makes it impossible to use dynamic operation which the debugger relies on. This setting should be disabled for developer scenarios but enabled for production scenarios since otherwise some reports may render very slow.

**Comment by rrrezende** [comment]
Thanks! Sorry, I had't come across that article yet. Worked fine now.
