### ISSUE TITLE
Start object name instead of ID

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#1036]
Since I don't want to use the finsql anymore and ID's are a bit annoying, it would be nice if you could specify the object name in the launch.json instead of the ID :)

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We already have a similar one, see #82

**Comment by Gallimathias** [comment]
All right, I could have found it myself. :/
It is sufficient if an issue is open, so we can close this.
