### ISSUE TITLE
Referencing Global var in TableExtension OnValidate crashing client

### ISSUE THREAD

**Issue by eknraw** [Microsoft/AL#104]
Crashes with Record/Codeunits, not sure if it's more object types.  Locally scoped variable works correctly.  

See attached for a code example. 

[SalesHeaderTableExtension.1.zip](https://github.com/Microsoft/AL/files/805879/SalesHeaderTableExtension.1.zip)

**Comment by StanislawStempin** [comment]
Was it crushing at runtime or at compile time? 
I cannot reproduce the problem on the latest build.

**Comment by eknraw** [comment]
Runtime in the Windows client.  You're right about not reproducing, I could only get the example with the codeunit to do that after it crashed with the example I'm attaching.  I  just created a new VM and deployed the extension (attached the entire project this time) and was able to get the client to crash. 

1. Publish CrashTest
2. Compile table 36, page 42
3. Open a sales order and pick a new "Additional Ship-to Address Code."

![crash](https://cloud.githubusercontent.com/assets/5561726/23514796/fed0ea08-ff2d-11e6-9569-73749c632812.gif)

[CrashTest.zip](https://github.com/Microsoft/AL/files/814287/CrashTest.zip)

[EventLog.txt.txt](https://github.com/Microsoft/AL/files/814188/EventLog.txt.txt)
