### ISSUE TITLE
Codeunit 50001 Already Exists in NAV 2018

### ISSUE THREAD

**Issue by bwdeleeuw** [Microsoft/AL#1044]
When I create a new codeunit 50001 against NAV 2018, I get the following message:

severity: 'Error'
message: 'An application object of type 'Codeunit' with ID '50001' is already declared'
at: '1,10'
source: 'AL'
code: 'AL0264'

This mystery codeunit seems to contain the following procedures:
![image](https://user-images.githubusercontent.com/7257240/33638903-d98db0d0-d9e5-11e7-92ad-7adf2f7e9f15.png)

**Comment by bwdeleeuw** [comment]
There is no sign of this object being used in any Extension according to the NAV App Object Metadata, so I'm assuming it's an internal thing.

**Comment by StanislawStempin** [comment]
Do you see this codeunit in C/SIDE?

**Comment by bwdeleeuw** [comment]
No

**Comment by StanislawStempin** [comment]
Could you please retry this scenario on NAV 2018 CU1 and let us know if you're still hitting the same issue?

**Comment by bwdeleeuw** [comment]
Will do, once CU1 is released, I'll give it a retry.

**Comment by bwdeleeuw** [comment]
I'm still hitting the same issue in CU1

**Comment by lvanvugt** [comment]
We're sitting here in a workshop on VSCode and everyone is hitting the same. 50000 en 50002 are OK to create but 50001 not.

**Comment by NKarolak** [comment]
@StanislawStempin Are you still following this topic? This bug needs to tagged and fixed.

**Comment by StanislawStempin** [comment]
This must have been an issue with how the Docker image for NAV 2018 was prepared. Following these steps I cannot reproduce the issue anymore:
```
install-module navcontainerhelper -force
New-NavContainer -accept_eula -containerName "NAV2018" -imageName "microsoft/dynamics-nav" -includeCSide -doNotExportObjectsToText
```

**Comment by bwdeleeuw** [comment]
Agreed, this seems to be fixed in CU4.
