### ISSUE TITLE
JS Builder has problems with comments on End of File

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#1045]
I am currently creating with the released version 0.12.15355 some extensions with addins.

I received the following error after a while:

Uncaught SyntaxError: Unexpected end of input

Uncaught Reference Error: _controlAddInInitialize is not defined

![unexpected_end_of_input](https://user-images.githubusercontent.com/16351673/33649619-e10ac716-da5e-11e7-83e0-511c36456d97.JPG)

The cause of this is the problem that the Builder for the StartupScript does not terminate the comments at the end of a JS file with a closing parenthesis. This means that the function for initialization is not closed correctly.

![scope_problem](https://user-images.githubusercontent.com/16351673/33649780-82bd71e4-da5f-11e7-99c8-9ca79fae7428.PNG)

The problem can be easily reproduced. Just add a comment at the end of the startup script ^^.

**Comment by StanislawStempin** [comment]
Thanks for reporting.
