### ISSUE TITLE
How to Publish and test Extension Development in NAV 2018

### ISSUE THREAD

**Issue by StHillmann** [Microsoft/AL#1046]
We`ve got a id range from you for developing an extension.
Is there any way to test the resulting app in NAV 2018?
Trying to publish the App in NAV 2018 results in a license error. Likewise, it is not possible to develop the extension using NAV2018!?! Publishing the app inside VS Code results in "Your program license does not allow you to publish '<App Name>'.
Any hints?

Kind regards
Stefan

**Comment by larshaedersdal** [comment]
If you have recieved a custom object range from Microsoft I think you need to check if it is added in your devloper license.

[http://www.dynamics.is/?p=2613](http://www.dynamics.is/?p=2613)

**Comment by DominikDitoIvosevic** [comment]
Hi @orange-gobbler . Have you had success in publishing your extension?

**Comment by fvet** [comment]
If you would develop your extension in the D365 (70000000) range but would like to implement it on a NAV 2018 on-premise database, running on a customer license, would you need to include the 70000000 range in the customer license as well?

In addition, what about the 70000000 objects received when submitting an app idea, are these for free - no strings attached (both for partner and/or customer)? What are the differences with obtaining a cfmd range of objects?

**Comment by fvet** [comment]
Any feedback on the above? We're currently working on a set of features that we would like to offer to our customers, avoiding the use of custom object ranges (50.000 - 99.999)

Option 1 would be to go through the CfmD certification process. Goiing through the validation tests would be somewhat though, but not unevitable. Major drawback is the 10 recent customer references and the high cost of the objects if not achieved.

Option 2 would be to publish the features as apps / extension. For app submission on AppSource, we received a set of objects in the 70000000 range. Once the app is accepted, can we use the app on NAV 2018 on-premise implementations as well (and probably adding new objects to a branch of the app that would not necessarily make it into the AppSource app?) Will these 70000000  objects be available for free (both for partner / customer), without the need to have customer references / risk for penalties / ...?

**Comment by StanislawStempin** [comment]
Closing based on the NAV 2018 support case that resolved this topic.
In short - 70M range cannot be used On-Premise but we opened up for using 1M-60M range in the Cloud.
