### ISSUE TITLE
Txt2AL Convertor issues

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1047]
When converting the delta files of an app with the txt2Al.exe into AL files, the following errors occur when compiling the AL files with VS code:

1. The order of fieldproperties is important.
for flowfields in a table(extension): the fieldclass isn't put before the calcformula.
`        field(50018;"Completely Shipped";Boolean)`
     `  {`
           ` CalcFormula = Min("Sales Line"."Completely Shipped" WHERE (Document Type=CONST(Order),
                                                                       Document No.=FIELD(Document No.),
                                                                       Type=FILTER(<>' '),
                                                                       Quantity=FILTER(<>0)));`
            `Editable = false;`
            `FieldClass = FlowField;`
`}`
So you have to manually move the fieldclass in front of the calcformula in order to solve the problem.

2. In tablerelations, when a field/variable/name contains non-alphanumeric characters, there aren't any " " (quotes) put around those names. Like in the above example `Document Type' isn't written as '"Document Type"'.

3. Booleans aren't converted to `true/false` in tablerelations.

Suggestion:
variables that refer to another object have that refrence written as a number:
`SalesHeader : Record "36";`
change it so the name of the object is written instead?
`SalesHeader : Record "Sales Header";`

**Comment by DominikDitoIvosevic** [comment]
Are you sure the order of field properties matters? How does this manifest? (what happens if fieldclass is belowe? does it not get applied?)

**Comment by SirBETE** [comment]
1. The property 'CalcFormula' can only be set if the property 'FieldClass' is set to 'FlowField'

**Comment by qutreson** [comment]
It tried to reproduce the issue 2, the issue 3 and the suggestion and it worked properly for me. Before running the converter, you need to compile the object in C/SIDE and then export it to new syntax. 

Concerning the issue 1, the order of the properties shouldn't matter. In your file, the CalcFormula has some missing quotes which trigger other diagnostics. If you manually add the missing quotes to have: 
```
CalcFormula = Min("Sales Line"."Completely Shipped" WHERE ("Document Type"=CONST(Order), "Document No."=FIELD("Document No."), Type=FILTER(<>' '), Quantity=FILTER(<>0)));           
```
then the error with the FieldClass disappears.

**Comment by SirBETE** [comment]
You are correct, qutreson!
Issue 1 is due to the missing quotes (issue 2).

> It tried to reproduce the issue 2, the issue 3 and the suggestion and it worked properly for me. Before running the converter, you need to compile the object in C/SIDE and then export it to new syntax.

How do you mean?
I created delta files between my application and a cronus DB on the same CU as my application.
Next I used txt2al from NAV 2018, to create AL files from my delta files.

Do I need to upgrade my application first to NAV2018 so it works in C/AL?
The AL files should be converted from the delta files between my now 2018 application and cronus 2018 DB?

**Comment by qutreson** [comment]
When you create your delta file, you need to make sure that both the original file and the modified file were exported to new syntax (and also compiled in C/SIDE before being exported). No need for an upgrade here.

**Comment by SirBETE** [comment]
The correct order to create my application as AL files is?
1. Open application in NAV2018
2. Compile all application objects in nav2018
3. Export application to txt files
4. Open cronus (same CU as application) in NAV2018
5. Compile all cronus objects (same CU as application) in NAV2018
6. Export cronus to txt files
7. Create deltas between the application txts and cronus txts
8. Do txt2al on deltas to create application AL files
9. Put AL files in VS Code folder

(if not, I am lost ...)

**Comment by HunterFeltman-MSFT** [comment]
To @qutreson's comment about the 'new' syntax' see the linked documentation in issue #1055.
Repeated here: [Txt2Al Conversion Tool](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool)

**Comment by SirBETE** [comment]
Let's continue talking about problem 1. in #1055.

What about problem 2. & 3.?
These are something the txt2AL function should recognize and fix, no?

**Comment by qutreson** [comment]
The flow here is correct (using the command ExportToNewSyntax for the steps 3 and 6)
