### ISSUE TITLE
Loading all AL files of an application in the VS Code folder makes the project uncompileable

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1048]
I have converted all delta files of our application to AL files (with txt2Al). When I put all the AL files in the VSCode project folder, the extra objects appear in VS Code.
When pressing F5, ctrl+F5 or F6, nothing happens. Even with ctrl+shift+b, the application isn't build. Because the application can't be build, no problems are detected.
No output is shown, nor anything happend in the event viewer why it failed to build.

However when I load only a small part of the objects into the folder (example: all tables), you can compile and problems occur.
Some of these problems are caused by missing objects (functions in codeunits or properties like lookuppageID). These problems wouldn't occur if the application AL files would be loaded into the project all at once (after multiple iterate compilations).

**Comment by HunterFeltman-MSFT** [comment]
Could you outline the folder structure you have a little more? In order for VSCode to recognize and compile AL sources into an Extension package a few additional things need to be set up.
You'll need:

1.  The converted sources (of course)
2.  An app.json file describing your extension (akin to the manifest.xml from V1 extensions)
3.  A .vscode folder containing a launch.json that tells VSCode to invoke the Al compiler to generate the package
4. Application & System symbols packages

The final folder structure might look something like this:
```
Root\
   app.json
   .vscode\
      launch.json
   .alpackages\
      <symbol packages>
   sources\
      <AL source files>
```

You can generate a template .vscode folder & app.json by using the AL:GO! command from the command palette in VSCode: `View -> Command Palette -> AL:GO!`

Make sure to adjust your launch.json file to point at your NAV server and NAV Server Instance, and to use the same authentication type as the Nav server.

Once you have your launch.json set up properly, you will then need to download symbols from the nav server using another VSCode command: `View -> Command Palette -> AL:Download Symbols`

If all is well so far, then you're 'almost' ready to go all that's left is to clean up your source. Unfortunately, the txt2al tool can not always produce 100% conversion and so there might be a few errors that you need to correct in your converted source before you can compile. (Notably .NET type references/usages)

I would also recommend the following documentation references/readings:
- [Development in AL](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-dev-overview)
- [Converting from V1 to V2](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-upgrade-v1-to-v2-overview)
- [NAV Development Preview Blog](https://blogs.msdn.microsoft.com/nav/2017/11/08/nav-development-preview-november-update/)

**Comment by SirBETE** [comment]
I went into the webclient, designed a page and moved a field.
Saved that extension and downloaded the source code.
This created pageextension 50101.al .
Next I opened VSCode on that folder (after unzipping it).
Now I have the correct settings for the app & launch.json files, I pasted my objectfolders with my AL objects in explorer into the VSCode project folder.

Project overview: [https://i.imgur.com/GmdQYhv.png](url)

There are 1218 AL files created by the txt2AL function.
When I load all these files into the VSCode project folder and want to compile them nothing happens.
However if I load only the table and tableextension into the project, I can compile and see all the problems for these files.
I hope this extra information helps for my question.

**Comment by Gallimathias** [comment]
@SirBETE Have you exported the complete database or just the customized and used area?

**Comment by SirBETE** [comment]
All
Because delta files between 2 identical objects (even if they are exported to a new syntax) doens't exist.

Going to rerun the entire export with all these new information. 
Will update when i got more info (and hopefully close all these problems cause I didn't do the exact correct procedure...).

**Comment by Gallimathias** [comment]
Okay, there's the problem. You can't just take the whole database and use it as a single extension.

Standard objects are not overwritten.

And it is also not the sense to build monster extensions ;)

Take some time and follow the instructions above.

I am curious to hear about your success message ;)

**Comment by SirBETE** [comment]
Did a good export, have now less 'stupid' errors :D
However Loading all AL files of an application in the VS Code folder makes the project uncompileable is still there. 
Only solution I see is manually adding certain objects to the project and solving the compile problems.
(exampe: first all setup tables & pages, next tableextensions, pageext ...)
