### ISSUE TITLE
[Event Request] Codeunit 5763- Whse.Post Shipment

### ISSUE THREAD

**Issue by Deepika303** [Microsoft/AL#1050]
The purpose is,we have customization in Post Job Whse. Shipment. So, we request for Event in GetSourceDocument function for adding Customized table as shown below
![cu5763_1](https://user-images.githubusercontent.com/33539268/33647383-ed1d1e34-da7a-11e7-9f11-18c0eef6e53e.jpg)
the parameter's in the function can have with **PassByReference/Var**
Same as for Function InitSourceDocumentHeader **OnAfterInitSourceDocumentHeader(WhseShptLine,RECORDREF);**
Also for function PostSourceDocument as **OnAfterPostSourceDocument(WhseShptLine,RECORDREF)**

**Comment by AlexanderYakunin** [comment]
What is RECORDREF here and how it should be used/passed between different places? Please explain how your extension will use it?

**Comment by Deepika303** [comment]
Hi,
we have asked the event with RECORDREF parameter because we want to set our custom tables in that event, as microsoft cannot give a parameter with custom table so we have asked for a parameter with recordref which can be used for several other tables. RECORDREF should be with VAR.

Thanks.

**Comment by AlexanderYakunin** [comment]
Our code does not use any RECORDREFhere, from my view you only need to know "Source Type" and use it as Table ID in your extension? So you event should be like OnAfterGetSourceDocument(WhseShptLine,"Source Type"). Or can you provide your COD5753.txt with required changes?
