### ISSUE TITLE
Event Request – CU232. OnBeforeGLregReportRun

### ISSUE THREAD

**Issue by navlarste** [Microsoft/AL#1052]
The Purpose is to use on other report in an Event  

Solution:
•	Parameter GLRegister must be set to Property=AsVar, it is holding filters
 
![2017-12-06_15h02_14](https://user-images.githubusercontent.com/32996357/33665268-a4cae5c8-da96-11e7-9c06-1729d2d74edc.png)

 
Delta file built on 2018 RTM W1:
[COD232.txt](https://github.com/Microsoft/AL/files/1535403/COD232.txt)

**Comment by AlexanderYakunin** [comment]
Can you simply update field GenJnlTemplate."Posting Report ID" with your posting report ID?

**Comment by navlarste** [comment]
Yes, that could be another way doing it.
You have than to make the parameter for GenJnlTemplate."Posting Report ID" Property=AsVar.

Be aware. I Have Request for an event in Codeunit 243 looks the same as this. 

[Issues 1053](https://github.com/Microsoft/AL/issues/1053)

**Comment by navlarste** [comment]
I really need this event so I can select different reports depending on who is printing.
