### ISSUE TITLE
Keywords for variables or functions are recognised as objecttypes

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1055]
If you define variables of the type page, codeunit ... the compiler expects a number, as if you are declaring a new object.
```
CustCommentPag : Page "124";
CustCommentRec : Record "97";
CalMgt : Codeunit "50100";
```
This creates the problem on the "124"  and "50100":
```
[AL] Syntax error, integer literal expected
[AL] The application object identifier '0' is not valid. It must be within the allowed range '50100' - '50149'.
[AL] An application object of type 'Page' with ID '0' is already declared
```

Likewise, if doing the following in C/SIDE
`PAGE.RUN(PAGE::"Item Journal", ItemJournalLine);`
You see the next problem:
```
[AL] The application object identifier '0' is not valid. It must be within the allowed range '50100' - '50149'.
[AL] An application object of type 'Page' with name '' is already declared
[AL] An application object of type 'Page' with ID '0' is already declared
```
on both `PAGE` keywords.

**Comment by HunterFeltman-MSFT** [comment]
Variable declarations for object references can be written in 2 forms : 
1. Object Id - `<var name> : <object type> <object id>`
```
var
   CustomerCardPag : Pag 21;
   CustomerRec : Record 18;
   ApplicationMgmtCod : Codeunit 1;
```
2. Object Name - `<var name> : <object type> {"<object name>" | <objectname>}`
```
var
   CustomerCardPag : Pag "Customer Card";
   CustomerRec : Record "Customer";
   ApplicationMgmtCod : Codeunit ApplicationManagement;
```

The differences being that if you want to use the Object Id form, you cannot include quotes "". Likewise, if you want to use the Object Name form, and the object has 'spaces' in its name, then you must include quotes.

Was this the result of a direct txt2al conversion? If so, you can of course fix them manually, but if you want to try convering again, make sure to follow this guide to export your C\SIDE objects in the 'new syntax' form: [Txt2Al Conversion Tool](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool)

**Comment by SirBETE** [comment]
Yes, this was the result of the txt2AL function.
Why can't the txt2AL function convert it to the correct syntax (either the number or the name (with quotes if needed))?

I am not going to eliminate the quotation marks around the numbers through my entire application where objectvariables are declared. That's an overload of extra work on something that I can't control ...
Isn't it the txt2AL function's job to convert it correctly?


About the steps from the Txt2Al conversion tool
1. clean Dynamics NAV database = NAV110 CU0 ? or same NAV version and CU as my application?
2. and compile it?
3. ok
4. = comparing AL files (since the objects are ExportedToNewSyntax)?
5. \Program Files(x86)\DynamicsNAV\100\RoleTailored Client , you mean DynamicsNAV\110 folder?
6. Run txt2AL on the ExportedToNewSyntax objects? But aren't they already in the new syntax?

Sorry, but it still isn't quite clear for me how you should create your application in AL ...

**Comment by qutreson** [comment]
The problem for me looks similar to [#1047](https://github.com/Microsoft/AL/issues/1047), I think the problem is not on the txt2al, but on the delta file that is used which might not have been created from two txt files that were both compiled and exported to new syntax. 

You can refer to the documentation from @HunterFeltman-MSFT, you should follow the steps [there](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool). However, before exporting the base objects (step 1 online), make sure you compile them. Same thing before you export your new created or modified objects (step 3 online). If they are not compiled, they might not be exported properly, then the delta files created won't be correct and errors will appear in the output of the txt2al converter.

**Comment by SirBETE** [comment]
Ahha, I think I understand.
The delta files aren't between the txt exports of the objects in C/AL code of cronus and the application.
They are between the NewSyntax exports of the object export of cronus and the application.

Going to try it out.
Hopefully this will solve all my problems :).

**Comment by qutreson** [comment]
Let us know if this fixed your problems :)

**Comment by SirBETE** [comment]
Code was converted wrong.
