### ISSUE TITLE
Adding field to standard NAV table causes warning and skips creating delta file

### ISSUE THREAD

**Issue by darench** [Microsoft/AL#1059]
Getting the following warning in PowerShell:
_WARNING: Table=14 Element Field does not support property Level or the value is non numeric_ 

I’m getting this warning for each base NAV table that I added fields when I create deltas using  this PowerShell command:
_Compare-NAVApplicationObject -OriginalPath Original -ModifiedPath Modified -DeltaPath Delta -ExportToNewSyntax_ 

Nothing special about the fields.
![powershellwarning](https://user-images.githubusercontent.com/33038024/33687707-2733a65e-da96-11e7-98db-758bba9034db.jpg)

Here's the powershell errors:
![powershellwarning2](https://user-images.githubusercontent.com/33038024/33687823-a92d3904-da96-11e7-9330-a4fd13e378ab.jpg)

Docker image: navdocker.azurecr.io/dynamics-nav:11.0.19494.0-finus

**Comment by DominikDitoIvosevic** [comment]
I have fixed the issue and it's pending review. The flag -exporttonewsyntax was intended to fix an issue with pages but now when using it it's asserting table fields have levels as well. The workaround until my fix is reviewed is to Compare-NavApplicationObject with the -ExportToNewSyntax flag for pages and **for tables do the delta generation separately without the flag**.

The fix to be able to use the flag for both is coming soon. (it's also the recommended that you use the flag when comparing all objects after this is fixed)
