### ISSUE TITLE
failed with code 422. Reason: Your program license does not allow you to publish

### ISSUE THREAD

**Issue by aalund** [Microsoft/AL#1060]
I have tried do make make my first Extension, but I ran in to this error message:
_[2017-12-06 23:59:38.02] Sending request to http://localhost:7049/DynamicsNAV110/dev/apps
[2017-12-06 23:59:40.07] The request for path /DynamicsNAV110/dev/apps failed with code 422. Reason: Your program license does not allow you to publish 'CustomerListExt'._

It's the Hello World project, with out any changes. I'm using my developer license, even that it's pageextension 50100.

**Comment by yuranshrestha** [comment]
Upload Developer License in Database, restart the NAV 2018 service instance and try publishing it again.

**Comment by aalund** [comment]
I have already done that, but the error persist.

**Comment by yuranshrestha** [comment]
What is the id you are using for CustomerListExt object?

**Comment by aalund** [comment]
CustomerListExt ID is 50100 - it's actually the Hello World project that is created as default. I just changed the NST servername and changed it to us Windows credentials.

**Comment by aalund** [comment]
Okay, really seems to be an Licens issue.
I generated a new licensfile from Partnersource and now it works.

**Comment by chavansachin20** [comment]
@aalund : I'm also facing same issue. can you help me here. 
I have license file (.flf) file with me. 
Please suggest where to place license file, so that VS code will allow me to use my ID range in app.json. 

Thanks in Advance !!!

Sachin Chavan.

**Comment by StanislawStempin** [comment]
License validation happens only on the server - when publishing an extension that compiled successfully in VS Code. Have you gotten to this point?

In app.json you simply set your range to what you want using the IdRange element. This is not validated against the license file and simply serves as a hint to the compiler to give you an early failure in case you're stepping outside the defined range.
