### ISSUE TITLE
PowerShell Command Feature request for Export-NAVApplicationObject

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#1061]
```
Export-NAVApplicationObject -BasedOnFile 'C:\TEMP\NAV_Object_File.txt'
```

It is impossible to export multiple objects with different types and ID-ranges.
Now we need to read the file and build our own filters array.
After that, we export the objects to different files and than we need to join the files.

**Comment by KristofKlein** [comment]
That would be really nice! I also workaround this (parse the Object.txt or even CU Changelog Files) to give me all involved Objects + Type and smash them all one by one into the Export-NavApplicationObject. 
No big thing, but it would make some parts in powershell easier :)

**Comment by StanislawStempin** [comment]
Thank you for the suggestion. We have decided that we will not invest in this direction considering that we are officially moving away from using TXT files in the near future (12-24 months).
