### ISSUE TITLE
not able to pull finnl,finat,findk in dec preview

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1064]
Hi,

i have tried to pull the docker image for the above versions as i see they are also released but not able to download them getting below error:

![image](https://user-images.githubusercontent.com/26792519/33707673-2d447d20-db5e-11e7-987a-06ab0f12bfc8.png)

Please suggest.

Thanks & Regards 
Varun Reddy

**Comment by freddydk** [comment]
They are not included in the developer preview.
Where did you find information that they are released?

**Comment by bachii1010** [comment]
Hi i have found that in this document
[Build_19590.txt](https://github.com/Microsoft/AL/files/1541948/Build_19590.txt)

Please suggest

**Comment by StanislawStempin** [comment]
These are not available yet but will be available in one of the next updates.
