### ISSUE TITLE
Retrieving Version of Current App

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#1065]
Is there a smart way to retrieve the current version (a.b.c.d) of the current app (by 'current' I mean the app which contains the codeunit that I am executing code in).

Preferably a way that is 'Extension' target safe, but I'd take an answer that only works for 'Internal' for the time being as well.

Thanks

**Comment by esbenk** [comment]
You are looking for 

    procedure Foo();
    var 
        m : ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(m);
    end;

The ModuleInfo will contain information about the current module..

**Comment by jimmymcp** [comment]
Thanks, I thought I'd heard/read about it somewhere but couldn't find it.
