### ISSUE TITLE
December update: Most of standard objects are not available

### ISSUE THREAD

**Issue by acyvas** [Microsoft/AL#1067]
In December update, most of standard objects cannot be referenced in extension.
For example, it is not possible to extend Customer table or Page, because they are not available in symbols.

**Comment by StanislawStempin** [comment]
This will happen if you're using the C/SIDE side by side feature and haven't run finsql command=generatesymbolreference. Is that your case?

**Comment by acyvas** [comment]
No. I am using **microsoft/dynamics-nav:devpreview-december** docker image and i get this situation out of the box.
I have tried **microsoft/dynamics-nav:devpreview-december-fingb** it works fine.  Is this intended behavior?

**Comment by kfuglsang** [comment]
I'm also unable to reference application objects - e.g. the Hello World generated by "Al! Go" does not compile.
I'm running the NAV2018 RTM DK version. Not using Docker.

I've ran the generatesymbolreference (takes about 5 minutes) twice, downloaded symbols, restarted visual studio code. Nothing seems to work for me.

I can reference system objects such as the Company table though.
The following is configured on the NST:
- Allowed Extension Target Level: Internal
- Enable Developer Service Endpoint
- Enable loading application symbol references at server startup

**Comment by kfuglsang** [comment]
Found solution to my problem on Twitter.
I had installed the latest AL Language extension from VS Code's extension manager.
Uninstalling that and then installing using the vsix file from the dvd solved my issue.

**Comment by Frgusto** [comment]
Thankyou Fuglsang! I had the same problem. Your solution is correct.
