### ISSUE TITLE
Calling a Soap URL from V2 issue

### ISSUE THREAD

**Issue by naveenpinnama** [Microsoft/AL#1078]
Does V2 supports calling soap based urls?  Currently we have our app listed in appsource under V1 and we need this to work for V2.
I am trying to call the soap webservices url but running issue when i add the content-type header.
Also how can i resolve the below issue? 
i get the error attached. 
![error](https://user-images.githubusercontent.com/34326092/33782095-24baacde-dc0c-11e7-9d71-0683ba47c672.PNG)
This is what i have
                        Content.GetHeaders(Headers);
                        Content.WriteFrom(XMLRequestString);
                        RequestMessage.SetRequestUri('http://testurl.com/service1.asmx');
                        RequestMessage.Method('POST');
                        RequestMessage.Content(Content);
                        Headers.Remove('Content-Type');
                        RequestMessage.GetHeaders(Headers);
                        Headers.Add('Content-Type','text/xml');
                         Headers.Add('SOAPAction','http://tempuri.org/InsertProduct');
                        Client.Send(RequestMessage, ResponseMessage);
                   
If anyone have a sample code on how to call a soap based webservices please post here.

**Comment by kvaldik** [comment]
Hi.

I had the same issue as you are having. I never figured out (or I don't remember) what the issue was. But I was able to use the Post method instead of the Send method on the HttpClient. Bellow is my code for invoking a soap web service.

```
// Setup the content of the web service call
HttpContentWS.WriteFrom(ContentText);
HttpContentWS.GetHeaders(HttpHeadersWS);
HttpHeadersWS.Add('SOAPAction','http://tempuri.org/GetLoginInformation');
HttpHeadersWS.Remove('Content-Type');
HttpHeadersWS.Add('Content-Type','text/xml');
    
// Invoke the web service
HttpClientWS.Post(GetWebServiceAddress,HttpContentWS,HttpResponseMessageWS);
```

**Comment by naveenpinnama** [comment]
Thanks Kvaldik.. This worked for me.
