### ISSUE TITLE
Event Request T_36 

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/AL#1081]
We need a Event in Table 36 at the CASE in the "UpdateSalesLines" function  with the "SalesLine" record.

![table_36_updatesaleslines](https://user-images.githubusercontent.com/34307263/33819557-66e2b0fc-de4b-11e7-96c5-600a6d104347.PNG)

**Comment by AlexanderYakunin** [comment]
We already have this event:
 
OnUpdateSalesLineByChangedFieldName(Rec,SalesLine,ChangedFieldName);
