### ISSUE TITLE
Can´t get AL working in VSCode following instructions

### ISSUE THREAD

**Issue by mcerdeira** [Microsoft/AL#112]
On my VM, following this: https://msdn.microsoft.com/en-us/dynamics-nav/newdev-get-started

I can't even do:
2) Type AL: Go (case-insensitive) and select a project folder. 

AL: Go does nothing.

EDIT: on other link I see this:

> – Getting started in VS Code has been streamlined. Once you’ve installed the **visx** file, just enter AL: Go! in the command palette (Ctrl+Shift+P) and you’ll be offered a new folder to build a solution in. The preset values are configured for your Azure Gallery instance and if you’re missing the symbols for the project, VS Code will offer to download them for you. Note, we’ve introduced a shortcut for this too – Alt+A, Alt+L. Enjoy!

Where can I get that visx file??

**Comment by StanislawStempin** [comment]
We have seen this a few times if the VM didn't initialize properly. I suggest that you recycle the VM and give it 10-15 minutes before you log in for the first time.

**Comment by mcerdeira** [comment]
Thanks @StanislawStempin, I did that and now it worked.
