### ISSUE TITLE
Download symbols stopped working

### ISSUE THREAD

**Issue by mcerdeira** [Microsoft/AL#113]
Suddendly, download symbols option from VSCode stopped working.
I tried rebooting the VM, but no luck. 

![capture](https://cloud.githubusercontent.com/assets/938346/23968879/4c919e98-09a3-11e7-8164-5af3509fb589.PNG)

This is VSCode log:
```
[2017-03-15 20:12:38.90] Using reference symbols cache path: c:\Users\admin_madeira\Documents\AL\ALProject2\packages
[2017-03-15 20:12:41.65] Error: An error occurred while sending the request.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 127.0.0.1:7049

[2017-03-15 20:12:43.85] Error: An error occurred while sending the request.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 127.0.0.1:7049

[2017-03-15 20:12:43.85] Could not download reference symbols
```

I think is related to the app.json generated:
```json
{
  "id": "7d1a5229-1b11-4dab-ade0-b30d3e28d4ef",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "10.0.0.0",
  "application": {
    "version": "10.0.0.0",
    "locale": "US"
  }
}
```

**Comment by StanislawStempin** [comment]
Please try the following commands from the NAV administration powershell:
Set-NavServerConfiguration -ServerInstance DynamicsNAV100 -KeyName DeveloperServicesEnabled -KeyValue true  
Set-NAVServerInstance DynamicsNAV100 -restart

Also make sure that in the launch.json file the server instance name is set to DynamicsNAV100 and windows authentication is set to true.

**Comment by mcerdeira** [comment]
Ok, I did that. I also needed to replace "DynamicsNAV100" with "NAV" because thats the name of the instance on this VM.

![capture](https://cloud.githubusercontent.com/assets/938346/23995829/f0a13846-0a29-11e7-899c-292bd3684197.PNG)

Also, I needed to put "NAV" in the launch.json and it worked.
Do you have any clue why the instance name have changed to NAV? From where is getting that instance name?

**Comment by StanislawStempin** [comment]
You should have both NAV and DynamicsNAV100 instances. NAV is the default instance configured with username/password authentication and DynamicsNAV100 is an instance configured with windows authentication. The instance names are embedded in the installation scripts.

**Comment by mcerdeira** [comment]
Ok, I don´t know what could happen then. I think I'm going to start over again.
Thanks.

**Comment by mcerdeira** [comment]
I reopened this because, I tried on a fresh VM and the same happened again.
This are the two instances I have (NAV comes with the VM and Navision_main is what the script creates):

![capture](https://cloud.githubusercontent.com/assets/938346/24056649/559d6180-0b23-11e7-80a2-84146741ec53.PNG)

But, the VSCode seems to point to DynamicsNAV100.
At least, this it seems inconsistent to me.

```json
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "publish",
			"projectRoot": "${workspaceRoot}",
			"packageFileName": "${command.resolvePackageFileName}",
			"name": "Publish",
			"server": "http://localhost",
			"serverInstance": "DynamicsNAV100",
			"tenant": "default",
			"windowsAuthentication": true,
			"startupObjectId": 22
		}
	]
}
```
What do you recommend? I rename the instance Navision_main to DynamicsNAV100 or I just change the serverInstance var in the json file?

**Comment by StanislawStempin** [comment]
To get unblocked change serverInstance in the launch.json to "Navision_main".

The DynamicsNav100 instance is only created if the VM is created through the http://aka.ms/navdeveloperpreview URL.

**Comment by mcerdeira** [comment]
I think we use that link, I'll check.
Thanks.

**Comment by RafaelKoch** [comment]
Just happened to me too, and the solution is so very simple. After some fruitless searching I went to check the Status of DeveloperServicesEnabled flag only to find the Service Tier was not running. Apparently on the VM this ST does not start on boot and that's it. Once started I could once again download symbols and publish my app.

@StanislawStempin : the error message could be more helpful. "Actively refused..." is not what happened. Should be something like "...not found or not running..."

**Comment by StanislawStempin** [comment]
Thanks for this information. We will see if we can detect this state and provide a better error message
