### ISSUE TITLE
Documentation about new data types?

### ISSUE THREAD

**Issue by srenders** [Microsoft/AL#114]
Hi,

In the AddressService example I noticed some new datatypes such as: JsonArray, JsonToken, HttpClient, HttpResponseMessage, ...
Is there any documentation available about these, how to use them in VSCode with AL, and other similar 'new stuff'? 

Thanks,
Steven

**Comment by stuartglasson** [comment]
The docs are still work in progress and you can see the work so far at: https://msdn.microsoft.com/en-us/dynamics-nav/newdev-reference-overview. There is a section for the new types, including the REST API which is in progress and will get more updates soon.

**Comment by DanielGoehler** [comment]
https://msdn.microsoft.com/en-us/dynamics-nav/newdev-reference-overview says 
> We're sorry, the page you requested cannot be found.

Is there a new URL?

**Comment by StanislawStempin** [comment]
Yes, here is the new URL:
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-reference-overview

**Comment by DanielGoehler** [comment]
Thanks
