### ISSUE TITLE
Event Request C_5988 OnAfterCheckCertificateOfSupplyStatus

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/AL#1147]
We need the "OnAfterCheckCertificateOfSupplyStatus" Event in Codeunit 5988 , in the "CheckCertificateOfSupplyStatus" function with the "CertificateOfSupply" record.

![c_5988_checkcertifi](https://user-images.githubusercontent.com/34307263/33834340-f078688e-de82-11e7-9bd5-fd7b59761e7d.PNG)

**Comment by AlexanderYakunin** [comment]
Please clarify and explain what this event should be able to do. You ask for OnAfter event but put in Before. CertificateOfSupply record is not initialized at this point.

**Comment by GlicPi** [comment]
Sorry this was a mistake, it should be at this Position with the "ServShptHeader" record,

![codeunit 5988](https://user-images.githubusercontent.com/34307263/34207800-3b402540-e58c-11e7-9126-5bb8d6630f28.PNG)

**Comment by AlexanderYakunin** [comment]
There is already event in CertificateOfSupply.InitFromService function in table 780. I think this is right place to add more info to CertificateOfSupply record, so new event is not needed. Agree?
