### ISSUE TITLE
Details of the standard objects (especially tables) in Visual Studio Code

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1148]
When you jump into a standard object with F12 in Visual Studio code, it has little detail. If you use the Customer table, for example, the fields do not display whether the fields are FlowField or FlowFilter. This can be a bit problematic because it's so easy to forget to call the CALCFIELDS function. Would it be possible to display the standard objects in more detail when navigating with F12? That would simplify the work considerably.

**Comment by kalberes** [comment]
Makes sense. I will add it to the backlog.

**Comment by dtkb** [comment]
Isn't this resolved now? F12 should load a `.dal` file with all page properties/code present.

**Comment by FSharpCSharp** [comment]
True, that is to be implemented with the latest version already. Can therefore be closed from my point of view, which is what I do with this.
