### ISSUE TITLE
[Question] Processing of existing event requests.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1150]
Almost a month ago I requested several events in an issue. This issue was also marked as "eventrequest" and "accepted" [921](https://github.com/Microsoft/AL/issues/921). Unfortunately, nothing has happened since then. Even after my question, no one has contacted me. So I'd like to know if event requests are currently in the background, or are they being processed slowly? Up to now, event requests have been the major problem for converting existing programming to the new development environment. I would very much like to hear an enlightening answer on how things are going to proceed here, because without these events the changeover is no longer possible.

**Comment by kalberes** [comment]
These events are processed and added as bugs to the appropriate teams.  They will be processed within the normal development processes on the appropriate teams.

**Comment by AlexanderYakunin** [comment]
We implement events on daily basis, this one is available from Dec 2. Check CTP18 or take any build after Dec 2.

**Comment by FSharpCSharp** [comment]
@kalberes @AlexanderYakunin 
First of all, thank you very much for the answers. But I have another follow-up question. Will these events be implemented in parallel in the NAV 2018 version or only in the Tenerife version? I have already seen older event requests in the version of 2018. Is the NAV 2018 version regularly updated with adaptations to the modern development environment?

**Comment by AlexanderYakunin** [comment]
The answer is no for released NAV 2018, but they will be in NAV 2018 R2 release.
