### ISSUE TITLE
Event Request C_7307 OnBeforeErrorText004

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/AL#1152]
We need the "OnBeforeErrorText004" Event in Codeunit 7307 , in the "CheckWhseItemTrkgLine" function with the "TempWhseActivLine" record.

![c73071](https://user-images.githubusercontent.com/34307263/33834798-8cc6d544-de84-11e7-96c0-fe8309e2cb44.PNG)

**Comment by kalberes** [comment]
You have added zillions of requests today. Are all these viable requests? Don't you have workarounds. What is your scenario here for example?

**Comment by GlicPi** [comment]
In some Industry sectors, there is the possibility of over or under delivery. In this case, we want to skip the Error message. If we can´t get the event at this place we have to look for a workaround.

**Comment by RafaelKoch** [comment]
How will you skip the error message? It will fire nonetheless.

**Comment by GlicPi** [comment]
You are right, it will fire all the time even with this event. I´m sorry, in this case, you can delete this request and we have to search for a workaround.
