### ISSUE TITLE
Event Publisher C_1290 SOAP Web Service Request Mgt. 

### ISSUE THREAD

**Issue by robertintergen** [Microsoft/AL#1156]
I would like to have this event in place so that other HTTPWebRequest values such as ContentType can be changed:
![onafterbuildwebrequest](https://user-images.githubusercontent.com/24398648/33863115-1c862b96-df4b-11e7-9a75-909da44715d7.jpg)

**Comment by kalberes** [comment]
can't you use instead the newly added HttpClient and co. AL types?

**Comment by robertintergen** [comment]
Good point, I should be able to in going forward, I am just working in an older environment at the moment.
