### ISSUE TITLE
Suggestion: Enable Name Reference to Table/Record in EventSubscriber

### ISSUE THREAD

**Issue by bwdeleeuw** [Microsoft/AL#1157]
When I subscribe to an event in a codeunit, I call reference the codeunit by name, eg. Codeunit:"Sales-Post". For table, I have to use the number. I have tried Record::Customer as well as Table::Customer, to no avail:

![image](https://user-images.githubusercontent.com/7257240/33865845-b59aeae2-deb0-11e7-9213-07e8e5b36696.png)

It would be very useful to be able to reference the Table by name as well.

**Comment by MikeGlue** [comment]
You can use 'database::'  to reference a table by name.

**Comment by bwdeleeuw** [comment]
@MikeGlue That did the trick! Closing the issue now.
