### ISSUE TITLE
Extension compilation failed error while creating package in DEC preview

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1158]
Hi,

I am getting the below error when we are trying to create a package and also the symbols are dowloaded correctly.

![image](https://user-images.githubusercontent.com/26792519/33870883-1853635a-df36-11e7-956b-c5295455a772.png)

can you please suggest why i am getting this error and i cannot see all standard objects in my extension.

Thanks & regards
Varun Reddy

**Comment by kalberes** [comment]
This looks a server compilation error of your extension on the server. Is this a SAAS deployment or NAv 2018?

**Comment by bachii1010** [comment]
hi

i am using dev preview of dec which i created from docker

**Comment by kalberes** [comment]
aah yes, I see now your decpreviewserver in the screenshot provided:) And I assume your server is connecting to a Nav database that has a Dimension table?

**Comment by bachii1010** [comment]
HI Kalberes,

Yes it is connected to standard cronus db

**Comment by bachii1010** [comment]
@kalberes  is there any update about this issue.

This is high priority for us.
As we are not able to access standard objects we are not able to continue.

**Comment by kalberes** [comment]
Hi, 
In my opinion this is something local to your own installation.Else others would also ask ferociously that they cannot compile with the Dec preview. Isn't it?
It is hard to tell what is wrong from the info you have provided. Can you check the event viewer? Maybe there are other hints of what has gone wrong on the server.

**Comment by bachii1010** [comment]
Hi,

I have checked the editor but nothing is recorded when the symbols are downloaded. It says they are downloaded also but still the standard objects are not recognized.

**Comment by kalberes** [comment]
If you compile with Ctrl Shift B do you get any errors? If not, it means that that the symbols you have downloaded work correctly. Else you have wrong symbols.
Follow task 18 here: https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data
If only F5 or Ctrl F5 fails with compiler errors it means that you are compiling against a server that is  connected to a database that does not have those symbols.

**Comment by bachii1010** [comment]
Hi,

Yes when i compile with Ctrl Shift B then i am getting errors even though it shows the symbols are dowloaded

**Comment by thpeder** [comment]
Hi @bachii1010,
Are you still having problems in any of the newer previews?

**Comment by bachii1010** [comment]
@thpeder  no now i am not getting this issue.

**Comment by thpeder** [comment]
Excellent, then I'll close this issue. If you run into the problem again then feel free to open a new issue.
