### ISSUE TITLE
How do one runs Towers Of Hanoi example?

### ISSUE THREAD

**Issue by mcerdeira** [Microsoft/AL#116]
I cannot find the ListPage in NAV.
![capture](https://cloud.githubusercontent.com/assets/938346/24408182/54243670-13a3-11e7-8c23-34c49fac96a7.PNG)

![capture1](https://cloud.githubusercontent.com/assets/938346/24408254/721a20b8-13a3-11e7-8996-7d7b2425967a.PNG)

What am I doing wrong?

**Comment by srenders** [comment]
You have to add:
startupObjectId": 70008000
to the launch.json

**Comment by mcerdeira** [comment]
Oh, I see... Thanks @srenders !!
