### ISSUE TITLE
Adding a Report fails

### ISSUE THREAD

**Issue by srenders** [Microsoft/AL#117]
[MyReportTest.zip](https://github.com/Microsoft/AL/files/875895/MyReportTest.zip)
This is my Report:
```
report 70000000 MyReport
{
    CaptionML=ENU='MyCustomerList';
    //RDLCLayout='C:\MyCodeTests\MyReportTest\ReportLayouts\MyReportRDLC.rdlc';
    WordLayout='C:\MyCodeTests\MyReportTest\ReportLayouts\MyReportWORD.docx';
    DefaultLayout=Word;

    dataset
    {
        dataitem(Customer; Customer)
        {
            column(Name; Name)
            {
                IncludeCaption=true;
            }
            column(City;City)
            {
                IncludeCaption=true;
            }
            column(Balance;"Balance (LCY)")
            {
                IncludeCaption=true;
            }
        }
    }

    /*requestpage
    {
        layout
        {
            area(content)
            {
                group(Options)
                {
                    field(Name;NameSource)
                    {
                        
                    }
                }
            }
        }
    
        actions
        {
            area(processing)
            {
                action(ActionName)
                {
                    trigger OnAction();
                    begin
                    end;
                }
            }
        }
    }*/
}
```
Building the solution works. Running it throws this error:
_[2017-03-28 13:42:49.15] Publishing package to http://localhost:7049/navision_main/dev/apps?tenant=default
[2017-03-28 13:42:49.76] Error: The request failed with code 422, reason: Extension compilation failed
(5,5): error AL0327: Missing layout file 'C:\MyCodeTests\MyReportTest\ReportLayouts\MyReportWORD.docx'._

If I change 
WordLayout='C:\MyCodeTests\MyReportTest\ReportLayouts\MyReportWORD.docx';
to
WordLayout=MyReportWORD.docx';
it wont compile, as it cant find the docx file anymore.

Am I doing something wrong?

**Comment by thpeder** [comment]
You found a bug, it shouldn't be allowed to develop locally using an absolute path to your layout files.

The property expects a relative path from the project path, so in your example if the folder you opened in VSCode is "MyReportTest" then the property should be 'ReportLayouts/MyReportWORD.docx'.

**Comment by srenders** [comment]
Thanks!
If I set it to:
WordLayout='ReportLayouts/MyReportWORD.docx';
then it works indeed.

**Comment by srenders** [comment]
Another related question. 
When I add an RDLC layout, it only works if the extension is .rdlc, and not if it is .rdl.
Is that normal or intended? I would prefer both of them are possible, since Report Builder auto recognizes .rdl files and not always auto-recognizes .rdlc files.

**Comment by thpeder** [comment]
The property should accept both extensions. I'll fix that.
