### ISSUE TITLE
Event Request C_7324 OnAfterDeleteAllTempWhseActivLine 

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/AL#1175]
We need the "OnAfterDeleteAllTempWhseActivLine " Event in Codeunit 7324, in the "Code" function with the "WhseActivLine" record.
![7324 2](https://user-images.githubusercontent.com/34307263/33878508-e3bfddd0-df2b-11e7-93fe-21c99d7fabab.PNG)

**Comment by AlexanderYakunin** [comment]
Please recheck name and position for this event. Should it go just after TempWhseActivLine.DELETEALL?

**Comment by GlicPi** [comment]
Rechecked it,the new Position and Event should be the "OnAfterDeleteModifyActivLine" with the "WhseActivLine" record. 


![codeunit 7324](https://user-images.githubusercontent.com/34307263/34207608-8357e026-e58b-11e7-8daa-599798995f3c.PNG)
