### ISSUE TITLE
download symbols stopped working in DEC Preview

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1180]
Hi,

i am getting the below error suddenly when i am downloading symbols
![image](https://user-images.githubusercontent.com/26792519/33884982-d1fb4990-df67-11e7-8f06-35ce588695b0.png)

can you please suggest on this.

Thanks & Regards
Varun Reddy

**Comment by kalberes** [comment]
Have you set the serverInstance, in the launch.config? I do not see that in the URL.

**Comment by bachii1010** [comment]
Hi,

Yes i have given the URL correctly see below:
![image](https://user-images.githubusercontent.com/26792519/33921840-89f17d38-dfec-11e7-9bd1-513b70369436.png)

**Comment by kalberes** [comment]
Is this the Cronus Database? Or your own converted one?
What happens if you run the following:
Get-NAVAppInfo -SymbolsOnly -ServerInstance <YOUS>

**Comment by bachii1010** [comment]
Hi 

it is a cronus db only 
but after restarting the service using the command  Set-NavServerInstance NAV -restart
this error is not coming but i want to know why this error is comming.

**Comment by StanislawStempin** [comment]
It is hard to say without more information. Do you have any errors logged in the event log that could help us narrow down this issue?

**Comment by bachii1010** [comment]
Hi

i don't have any issue logged in event viewer also it is occurring sometimes and not always so it is not easy to reproduce again and check.

Please suggest

**Comment by StanislawStempin** [comment]
Are you still encountering this issue using the latest Developer Preview version (0.15) ?
