### ISSUE TITLE
Dynamics Nav 11.0.19394.0 es-ES not found objects

### ISSUE THREAD

**Issue by nicojmb** [Microsoft/AL#1181]
Hi, I've downloaded the latest NAV version 11.0.19394.0 and latest VScodoe AL plugin.

But Page "Customer List" not found, my NAV version is es-ES

`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Desarrollo",
            "server": "http://desarrollo",
            "serverInstance": "Cronus_2018_19394",
            "authentication": "Windows",
            "startupObjectId": 22
        }
    ]
}`

![image](https://user-images.githubusercontent.com/5610392/33883269-7b62d098-df3b-11e7-8c6e-3ab951f5ad5e.png)

**Comment by kalberes** [comment]
If you do not have the symbols in your database you can generate them.
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side#get-started-generating-symbols-and-compiling-all-objects
For the NAv 2018 we have not released the application symbols with the Cronus db.

**Comment by nicojmb** [comment]
Hi, 

I execute command described in docs and add parameter to finsql.exe but not vscode not download symbols

![image](https://user-images.githubusercontent.com/5610392/33929955-9599c16e-dfeb-11e7-9e53-c96e13840fe9.png)

**Comment by kalberes** [comment]
Ok, can you please look in the event viewer and see what exceptions the server is throwing?

**Comment by nicojmb** [comment]
In Event Viewer tellme Licence problem, i've updated to NAV Develper Licence for 2018 and now Symbols download correctly and now error show in event viewer.

BUT, Page "Customer List" still does not recognize it :(

I executed "generatesymbolreference" command and start finsql.exe with generatesymbolreference=yes

In server i've checked that "Enable loading application symbol references" is enabled.


![image](https://user-images.githubusercontent.com/5610392/33935791-768786d2-dffd-11e7-9fe8-e7cb18b7667c.png)

**Comment by TheodorosKarropoulos** [comment]
Inside the NAV installation folder exists a file named ALLanguage.vsix. So try the following.
First uninstall the AL Language extension from VS Code. Then go to VS Code extensions and install the AL Language again but this time by selecting the More button (the 3 dots at the top right of the following image)
![image](https://user-images.githubusercontent.com/11943238/33936151-33c0cc14-e007-11e7-94e2-8f8a9659f5e0.png)
Then Select the Install from VSIX.. option and select the ALLanguage.vsix file usually located at "C:\Program Files (x86)\Microsoft Dynamics NAV\110\Modern Development Environment" directory.
Reload and done! It works for me and I hope it will work for you too.

**Comment by nicojmb** [comment]
The @TheodorosKarropoulos solution work!

Now "Customer List" not show error and work!
