### ISSUE TITLE
AL debugger: is break on error possible?

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1184]
I haven't been able to determine how to enable this, if it is even possible. 

Could this be added if it does not exist yet? It is very helpful to be able to see what is going on around the error.

**Comment by kalberes** [comment]
It is not possible yet.

**Comment by coffeecup007** [comment]
When will this be possible?  Or perhaps the better question is if there is another way of finding more information about an error when it occurs?  Occasionally we will see a nice stack trace in the event log, and we can guess what's happening from there, however more often than not we see no such stack trace.

**Comment by lvanvugt** [comment]
No answer to [coffeecup007](https://github.com/coffeecup007)?

**Comment by kalberes** [comment]
It is in our backlog, with high priority to add support on break on errors. I do not have a time line of when this will happen though.

**Comment by lvanvugt** [comment]
I guess this can closed due to: [Debugger enhancements ](https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/)?

**Comment by kalberes** [comment]
What do you mean by 'what AL extension to use'?
Any AL extension's launch.json if you want to set it to false. The breakOnError is by default true.
Dynamic update does not work as in the old RTC debugger.

**Comment by lvanvugt** [comment]
> The breakOnError is by default true.
OK, had wrongly read that. Nevertheless, using AL extension 0.16.19969 I seem not to be able to insert breakOnError in launch.json. It's not recognized.

**Comment by kalberes** [comment]
Well it should be available with the extension version released with the June update as your link has suggested.

**Comment by StanislawStempin** [comment]
This functionality is available as of Business Central Fall 2018.
