### ISSUE TITLE
[Ctrl+K Ctrl+F] Format Selection does not format **case** command correctly.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1185]
The following code:

        case CurrentPeriod of
            1 : Period1IsVisible := true;
            2 : Period2IsVisible := true;
            3 : Period3IsVisible := true;
            4 : Period4IsVisible := true;
            5 : Period5IsVisible := true;
            6 : Period6IsVisible := true;
            7 : Period7IsVisible := true;
            8 : Period8IsVisible := true;
            9 : Period9IsVisible := true;
            10 : Period10IsVisible := true;
            11 : Period11IsVisible := true;
            12 : Period12IsVisible := true;
        end;

Gets reformatted to:

        case CurrentPeriod of
            1 : Period1IsVisible := true;
2 : Period2IsVisible := true;
3 : Period3IsVisible := true;
4 : Period4IsVisible := true;
5 : Period5IsVisible := true;
6 : Period6IsVisible := true;
7 : Period7IsVisible := true;
8 : Period8IsVisible := true;
9 : Period9IsVisible := true;
10 : Period10IsVisible := true;
11 : Period11IsVisible := true;
12 : Period12IsVisible := true;
        end;

**Comment by qutreson** [comment]
The formatter has been fixed on case statements, when applied on your code, it will return
```
 case CurrentPeriod of
            1 :
                Period1IsVisible := true;
            2 :
                Period2IsVisible := true;

            [etc]
 end;
```

**Comment by DavidRoys** [comment]
When you say “has been fixed” do you mean in an upcoming release?

**Comment by qutreson** [comment]
The fix will be in the January update
