### ISSUE TITLE
How do I create RDLC reports from the Visual Studio Code Editor

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1187]
I have found the Microsoft.RdlcDesigner.vsix file from

https://marketplace.visualstudio.com/items?itemName=SqlReportingServices.MicrosoftRdlcReportDesignerforVisualStudio-18001

But is that it? 

There is no useable explaination on how to install it.

Anybody found a link about the subject?

/Peik

**Comment by srenders** [comment]
Hi Peik,
How I understand it, these are the steps you can follow:
[http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/](http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/)

/Steven

**Comment by peikba** [comment]
Perfect

Not pretty but it will do 😀

Sendt fra min iPad

**Comment by peikba** [comment]
Hi Steven 

 

Have you found the right syntax for this:

 

DataItemTableView = SORTING("No.")

                                ORDER(Ascending)

                                WHERE("Subscription Customer"=CONST(Yes));

 

I tried converting it from cal to al and this was the suggestion.

But it does not work.

 

Med venlig hilsen / Best Regards

Peik Bech-Andersen
Senior Consultant, Lead MCT
Mobile: +45 28 92 91 11

**Comment by thpeder** [comment]
Hi @peikba,

The syntax for DataItemTableView is correct, but we have changed the values of booleans from yes/no to true/false so if "Subscription Customer" is a boolean field then you need to change it to CONST(True).

The converter should have done that transformation as well, but it requires you to first compile the objects in C/SIDE before exporting them with the following argument: command=exporttonewsyntax

**Comment by DominikDitoIvosevic** [comment]
Hi @peikba . As @srenders says, for now we support the tedious process of doing rdlc and word development where you need to export from the app. 
Here's a teaser: we have an improved scenario for this coming up in January update which will only require vscode and word/rdl designer

**Comment by srenders** [comment]
I have seen this improved scenario, and I find it amazing!
![buildreports](https://user-images.githubusercontent.com/17511254/35731660-d7ead6c2-0816-11e8-88dc-653083e6a52d.gif)

**Comment by aidasberesinevicius** [comment]
Hi @srenders , can you tell me which build you used?
