### ISSUE TITLE
Event Request C_6620 Archive Fix

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/AL#1188]
All event publishers added in codeunit 6620 Copy Document Mgt. with parameters FromDocType/FromDocumentType and FromDocNo/FromDocumentNo are missing the parameters **FromDocOccurenceNo** and **FromDocVersioNo** for Archive documents.

When we subscribe to these, the missing parameters do not allow us to find out the Archive record the user is copying from.

**Comment by NKarolak** [comment]
@kalberes Are you sure to label this as application? It's a request to fix lately added event publishers.

**Comment by NKarolak** [comment]
@kalberes 
Happy New Year 
Is there any specific reason why my event requests get labelled but never processed any further, whereas later event requests from other users get considered for next releases?

**Comment by AlexanderYakunin** [comment]
The reason is that this ask was probably for DACH version of COD6620, as support for Archived documents was part of localization. We just completed consolidation of these changes into W1 and can start processing this request.
