### ISSUE TITLE
Are .NET addins going to be supported?

### ISSUE THREAD

**Issue by mcerdeira** [Microsoft/AL#119]
This is not an issue but a question:

I know that NAV extensions supports .NET addins but, are you planning to support them on the new development environment??

Thanks.

**Comment by StanislawStempin** [comment]
We are currently investigating a safe way to support them considering they would be executing in SaaS environment. We will provide more updates in the near future.

**Comment by mcerdeira** [comment]
Ok @StanislawStempin, thanks for the update. My concern is related with .NET functionality that is not available in C/AL, or that is much more easy to develop and mantain like consuming web services (SOAP, Rest, WCF)

**Comment by StanislawStempin** [comment]
We are gradually adding more native AL functionality that replaces the most common .NET usages. In February Update we added support for Http requests and Json. You can have a look at draft documentation here (go to section REST API):
https://msdn.microsoft.com/en-us/dynamics-nav/newdev-reference-overview
