### ISSUE TITLE
DECEMBER Preview

### ISSUE THREAD

**Issue by thenavguy** [Microsoft/AL#1193]
Hello Team,

I created a Azure VM with December preview, but cannot see any program to access NAV.

Is there any additional set of procedure to be followed to get NAV on the VM?

Please help, I am on early stage with Docker and doesn't know how to use it.

**Comment by epernst** [comment]
No additional steps, but did you give it enough time? From when you start the deployment, until you can fully use it may take 30 minutes. Check the status page on the Landing Page for your new server. Does the web client work?

**Comment by thenavguy** [comment]
Hi @epernst ,

After executing the powershell script, the landing page and NAV container helper appeared on the desktop.
