### ISSUE TITLE
Modifications to property Caption are not supported

### ISSUE THREAD

**Issue by stanuj** [Microsoft/AL#1194]
While publishing app to local environment, i'm getting below error:

[2017-12-14 11:46:35.32] Sending request to http://localhost:7049/dynamicsnav110/dev/apps?tenant=default
[2017-12-14 11:46:55.64] The request for path /dynamicsnav110/dev/apps?tenant=default failed with code InternalServerError. Reason: Modifications to property Caption are not supported.

Package is created successfully. I've also created .xlf file.

While using CaptionML and Caption proeprty getting below error:

Cannot specify CaptionML and Caption property at the same time

Please assist me to resolve this issue.

**Comment by NKarolak** [comment]
Those properties are obsolete soon anyway. Using CaptionML only should do the trick.

**Comment by DominikDitoIvosevic** [comment]
Hi @stanuj .
I have tried modifying a page action caption and translating it and had no issues.

        pageextension 50123 MyExtension extends "Customer List"
        {
            actions {
                modify(CustomerLedgerEntriesHistory) {
                    Caption='qwe';
                }
            }
        }

my xliff file:


    <?xml version="1.0" encoding="utf-8"?>
    <xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
      <file datatype="xml" source-language="en-US" target-language="de-DE" original="MyAlProject">
        <body>
          <group id="body">
            <trans-unit id="PageExtension 4142435239 - Change 880334091 - Property 2879900210" maxWidth="999" size-unit="char" translate="yes" xml:space="preserve">
              <source>qwe</source>
              <target state="needs-review-translation" state-qualifier="tm-translation">My Report qq</target>
              <note from="Developer" annotates="general" priority="2" />
              <note from="Xliff Generator" annotates="general" priority="3">PageExtension - Change</note>
            </trans-unit>
          </group>
        </body>
      </file>
    </xliff>

German:

![image](https://user-images.githubusercontent.com/6378638/33985252-5fb5ba9c-e0ba-11e7-9153-3c63ec00b05f.png)

English:

![image](https://user-images.githubusercontent.com/6378638/33985285-73dcd186-e0ba-11e7-80e8-787973a0f3a8.png)


Everything works as expected.

Could you @stanuj  please give us a specific repro so that I can investigate further?

Best,
Dominik

**Comment by epernst** [comment]
I get the same error, when using the DK build. But it works fine in W1. My guess it is because only one language in W1, which AL "translates" to the "new" Caption. Converting same objects in DK version will get us CaptionML.

But try the code below against a non-W1 build.

```
    tableextension 50000 Test extends Customer
    {
        Caption = 'My Customers';        
    }

```

**Comment by stanuj** [comment]
Yes Epernst, i'm using W1 only with one language. By using only CaptionML, it works fine now.

Thank you all for your suggestions.
