### ISSUE TITLE
Issue converting tablerelations from C/AL to AL

### ISSUE THREAD

**Issue by niku-live** [Microsoft/AL#1195]
It seems there are a problem converting table relations when FILTER operator is used. For example, this field (from page):
      { 3   ;2   ;Field     ;
                  Name=PASumJournalBatchName;
                  CaptionML=[ENU=Sum Journal Batch Name;
                             LTH=Sumu zrn. paketo pav.];
                  SourceExpr=PASumJournalBatch.Name;
                  TableRelation="PA Sum Journal Batch".Name WHERE ("Journal Template Name"=FILTER(SUM..SUMA)) }
will be converted to something like this:
                    field(PASumJournalBatchName;PASumJournalBatch.Name)
                    {
                        CaptionML = ENU='Sum Journal Batch Name',
                                    LTH='Sumu zrn. paketo pav.';
                        TableRelation = "PA Sum Journal Batch".Name WHERE ("Journal Template Name"=FILTER(SUM..SUMA));
                    }
If I try to compile this code, I get an error:
"error AL0186: Reference 'Journal Template Name' in application object 'PA Sum Journal Batch' does not exist"
If I modify converted code to something like this:
                    field(PASumJournalBatchName;PASumJournalBatch.Name)
                    {
                        CaptionML = ENU='Sum Journal Batch Name',
                                    LTH='Sumu zrn. paketo pav.';
                        TableRelation = "PA Sum Journal Batch".Name WHERE ("Journal Template Name"=FILTER('SUM..SUMA'));
                    }
then everything compiles. I think FILTER operator should always be interpreted as followed by textual filter, so the best solution would be to always put text after FILTER in quotes.

**Comment by kalberes** [comment]
Have you run finsql with the ExportToNewSyntax prior calling txt2al?
What is that you would have liked here. An "in between" or a "string equal" operator?
As you have refactored it, the code will look to something that matches the string 'SUM..SUMA' and not something that is between 'SUM' and 'SUMA'.
If you want an in between then use FILTER('SUM'..'SUMA')

**Comment by niku-live** [comment]
You are right, that text most probably should be FILTER('SUM'..'SUMA'), because yes, it should have been "in between", thanks for noticing. 

File was exported using ExportToNewSyntax, I am sure of that and even date format at the beginning of object ("Date=20141026D;") proves that. I attach a minimum file, that causes this issue (Microsoft (R) AL Compiler version 0.12.15355 is used)
[XML17024505.TXT](https://github.com/Microsoft/AL/files/1558854/XML17024505.TXT)

**Comment by kalberes** [comment]
Ok, this is a bug on our side. C/SIDE's Filters are contextual, thus what is exported is SUMA..SUMB, so the conversion was just applying that.
The server was then "understanding and inferring" this context based on the left hand side's type.

**Comment by DominikDitoIvosevic** [comment]
Hi @niku-live . After further investigation, unfortunately we do not have enough information at the moment of conversion to be able to know whether the two values are strings or options. 
That is why we can't know whether we should quote them or not. 
Since this sounds like something which doesn't happen often, we will have to ask you to fix these by hand. 
Could you tell us how many occurrences of this issue you have in your code? Is it in the range <10 or more?

**Comment by niku-live** [comment]
Hi @DominikDitoIvosevic, yes, right now we are fixing it by hand, as we have only about 15-20 places where this problem occurs. I just wanted to write about this issue, for it to be known for others. Of course my team is aiming for fully automated conversion (for the time being we want to support both C/AL and AL versions of our add-on), so we will need to update our scripts, but we can deal with it, it's not a big problem.

**Comment by DominikDitoIvosevic** [comment]
Thank you @niku-live for cooperation. The problem for us is that we would need a 100% solution for all cases like these and from investigating it seems we would need significant work to make this happen. If you could handle these few cases in your scripts that would allow us to focus on bigger things. 

Thanks!
