### ISSUE TITLE
Format Document: Forced new line after WITH x DO

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#1196]
Please remove the forced new line in a WITH x DO statement.

This code:

```
with Customer do begin
    Name := NewName;
    Address := NewAddress;
end;
```

is formatted to

```
with Customer do 
begin
    Name := NewName;
    Address := NewAddress;
end;
```

Please do not move the begin to the next line.

**Comment by kalberes** [comment]
These should governed by format options.

**Comment by markbrummel** [comment]
I agree with Erik. This does not improve readabilty. The begin should be on the first line.

**Comment by kalberes** [comment]
Well this is the endless discussion on where to start block statements. For my eyes for example it does improve readability. This is why if we have options people can choose.

**Comment by kalberes** [comment]
But we will leave it on the same line for now.
