### ISSUE TITLE
Wrong CALTestLibraries in finus

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1197]
In the finus build on Docker the CALTestLibraries are W1 instead of the US version. I had to deploy the NA version to get the US version of the CALTestLibraries.

navdocker.azurecr.io/dynamics-nav:11.0.19660.0-na - correct
navdocker.azurecr.io/dynamics-nav:11.0.19660.0-finus - incorrect

**Comment by freddydk** [comment]
I will look into this and if possible get correct test libraries on future versions.

**Comment by freddydk** [comment]
This is fixed with the release of Business Central.
Images on microsoft/bcsandbox:us contains test libraries for US.
