### ISSUE TITLE
Codeunit Extension

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#120]
Hi,

Similar to Table Extension & Page Extension.
How will we extend standard codeunits so that we can change the OnRun Trigger & Procedures in the codeunit.

Also how can we modify the procedures in Tables and Pages?

Thanks
Varun Reddy

**Comment by esbenk** [comment]
There is no support for that in the preview bits.

We are still investigating how we will add more extensibility to the existing app without compromising upgradability.

**Comment by bachii1010** [comment]
Hi,

Is there a possiblity that it will be done in future updates and do you have a precise time frame when it can be avaialable

**Comment by esbenk** [comment]
We don't have any time frame for this. We are still investigating the best way of extending the app.
