### ISSUE TITLE
InStream not persisting when passed as a var

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1201]
Sample project: 
```

page 50000 "Web Call"
{
  PageType = Card;
  UsageCategory = Administration;

  layout
  {
    area(content)
    {

    }
  }

  actions
  {
    area(processing)
    {
      action(Request)
      {
        trigger OnAction();
        var
          Stream : InStream;
          Output : Text;
          CU : Codeunit MyCodeunit;
        begin
          if CU.GetStream(Stream) then begin
            while not Stream.EOS do begin
              Stream.ReadText(Output);
              Message(Output);
            end;
          end;
        end;
      }
    }
  }
}

codeunit 50000 MyCodeunit
{
  trigger OnRun();
  begin
  end;

  procedure GetStream(var Stream : InStream) Result : Boolean;
  var
    Content : HttpContent;
    Client : HttpClient;
    Response : HttpResponseMessage;
    MyBlob : record TempBlob temporary;
  begin
    Result := Client.Post('https://www.google.ca', Content, Response);
    MyBlob.Init;
    MyBlob.Blob.CreateInStream(Stream);
    Response.Content.ReadAs(Stream);
  end;
}
```

Result: 

![image](https://user-images.githubusercontent.com/32313731/34011216-8759e93a-e0cc-11e7-95eb-ff3fe47962e8.png)

Now if you do everything in the same scope, it works out as you would expect. Sample: 
```
page 50000 "Web Call"
{
  PageType = Card;
  UsageCategory = Administration;

  layout
  {
    area(content)
    {

    }
  }

  actions
  {
    area(processing)
    {
      action(Request)
      {
        trigger OnAction();
        var
          Stream : InStream;
          Output : Text;
          CU : Codeunit MyCodeunit;
          Content : HttpContent;
          Client : HttpClient;
          Response : HttpResponseMessage;
          MyBlob : record TempBlob temporary;
        begin
          if Client.Post('https://www.google.ca', Content, Response) then begin
            MyBlob.Init;
            MyBlob.Blob.CreateInStream(Stream);
            Response.Content.ReadAs(Stream);
            while not Stream.EOS do begin
              Stream.ReadText(Output);
              Message(Output);
            end;
          end;
        end;
      }
    }
  }
}
```

Result: 
![image](https://user-images.githubusercontent.com/32313731/34011307-db5c73b8-e0cc-11e7-8db3-60ba4bd4a336.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @strophanthus .
This has been a missing feature in CSIDE as well for many years. The issue is that you are assigning a new underlying stream to the InStream in the Response.Content.ReadAs method and so that new stream has a shorter lifespan (only until the end of that method).

The solution for you is to pass a tempblob by var into the method and get the content in it and then in the containing procedure read it out

**Comment by strophanthus** [comment]
This has not been an issue for us until now. 

Our actual use is a bit different than the example. We would initialize the stream before passing it, and that was working in our NAV installations as well as the V1 extension.

**Comment by kalberes** [comment]
You mean that you have used before .net to read the content into your InsStream?

**Comment by strophanthus** [comment]
1. Call a function to init the instream using the blob approach (InStream passed as var)
2. Next call another function to get the web response (this was using CU 1297's GetResponse function, also has the stream passed as a var) 
3. And then a final function to read the stream in to text using the EOS and ReadText stream functions

This has always been working, and no longer is. (Of course step 2 is replaced with our own function using the new classes)

**Comment by strophanthus** [comment]
(and sounds like because of the ReadAs method from what Dominik explained)

**Comment by kalberes** [comment]
Yes I know what he means, I have investigated the issue with him a few hours before. From usage perspective yes it is the same, but this is still a complete new scenario.
In your 2 the GetResponseContent was using the ResponseBodyTempBlob to read its content into the stream. This is something different, but we will try to fix it.
