### ISSUE TITLE
ValidateTableRelation switches from default Yes in C/SIDE to missing in AL which flips behaviour after Txt2AL conversion.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1202]
Default behavior for a field that has a TableRelation in C/SIDE is ValidateTableRelation=\<Yes\>. I'm assuming that because this is the default setting, it does not get included in the text export and is therefore also missing in the result of the Txt2AL conversion.

Unfortunately the default behavior for AL for ValidateTableRelation is false which means that because the property is not specified, all places in my extension that previously had a table relation (and relied upon the default setting which was to validate the table relation), now no longer validate the relation, which is pretty bad. :0(

Any chance we can add default properties to exports so this doesn't happen in future? It would be nice if adding the TableRelation property to a field in AL automatically adds a line for the property to validate, but that's a real nice to have type thing (which might be tricky).

**Comment by NKarolak** [comment]
See #1015
https://github.com/Microsoft/AL/issues/1015

**Comment by DavidRoys** [comment]
Thanks!
