### ISSUE TITLE
XMLPort namespaces not working again

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1205]
Since I cannot reopen an issue and haven't gotten a response on [#246](https://github.com/Microsoft/AL/issues/246) I'm creating this issue. The problem is the same as in [#246](https://github.com/Microsoft/AL/issues/246), tested on navdocker.azurecr.io/dynamics-nav:11.0.19660.0-finus.

**Comment by kvaldik** [comment]
Any news on this? This is a v1-blocker for us.

**Comment by gudrunleos** [comment]
Any progress with this issue?

**Comment by DominikDitoIvosevic** [comment]
Yes. I'm working on it. I will have more info hopefully today

**Comment by DominikDitoIvosevic** [comment]
The source of the issue has been found and a fix is on the way

**Comment by gudrunleos** [comment]
This is still not working and we are running out of time :(
![image](https://user-images.githubusercontent.com/24827406/35270040-be6e3c8c-0025-11e8-8281-63d948901b74.png)

Please advice.

**Comment by DominikDitoIvosevic** [comment]
This looks like an unrelated issue to the bug for which this issue was opened for.
Is this in some code you are upgrading or some new code?
Could you please open a new issue with repro steps?
You didn't really give me much to work with...
This also looks like a platform limitation, not a language one, so I suppose this limitation was here for a while.

**Comment by kvaldik** [comment]
Actually this is the same code as before.

This is the error we get when we run `if XMLPort.Import then` (yes, there is an `if .. then` around it and still we get a run time error).

Should the namespace error be fixed in navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus ?

**Comment by DominikDitoIvosevic** [comment]
Yes. The fix for namespaces is in. This is an unrelated error.
Is this happening when you want to do XMLPort.Import for anything or just specific xmlport?
It looks like you are invoking the method in a write transaction. Has this code worked in cside?

**Comment by kvaldik** [comment]
Alright, there was some mix up here. The write transaction error was associated with the XML Namespace error by mistake. I've verified that the namespace error is fixed and that the transaction error was just the structure of our code. This code was never in CSide as it's replacing old DotNet usage.

**Comment by DominikDitoIvosevic** [comment]
Thank you very much for clearing this up @kvaldik .
I suppose that this can be closed then. If you have more issues please open a new issue
