### ISSUE TITLE
InternalServerError on Report: error CS0012 caused by AutoFormatExpression in table field

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1206]
After converting a Report from C/Side to AL I get an error, when I start the VS Code debugger:
```
The request for path /nav/dev/apps failed with code InternalServerError. Reason: 
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Groupedbc578c3b474dd4d9950d9dce784907_Report5172104.cs(257,21) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Groupedbc578c3b474dd4d9950d9dce784907_Report5172104.cs(257,145) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.Report5172104' does not contain a definition for 'GetFieldValueSafe' and no extension method 'GetFieldValueSafe' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.Report5172104' could be found (are you missing a using directive or an assembly reference?)
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Groupedbc578c3b474dd4d9950d9dce784907_Report5172104.cs(268,94) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.Report5172104' does not contain a definition for 'GetFieldValueSafe' and no extension method 'GetFieldValueSafe' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.Report5172104' could be found (are you missing a using directive or an assembly reference?)
```

Version & Build:
```
Microsoft (R) AL Compiler version 0.12.15355
Copyright (C) Microsoft Corporation. All rights reserved
Success: The package is created.
```

I have analysed the problem and found the reason for the error.

The report use a table with an **AutoFormatExpression** in the column the following constellation:
```
table 50000 "Test RDLC"
{
    fields
    {
        field(50;"Currency Code";Code[10])
        {
            CaptionML = DEU='Währungscode',
                        ENU='Currency Code';
            TableRelation = Currency;
        }
        field(81;"Commissionable Amount";Decimal)
        {
            // This AutoFormatExpression cause the trouble
[Test RDLC.zip](https://github.com/Microsoft/AL/files/1562437/Test.RDLC.zip)
[Test RDLC.zip](https://github.com/Microsoft/AL/files/1562438/Test.RDLC.zip)


            AutoFormatExpression = "Currency Code";
            AutoFormatType = 1;
            CaptionML = DEU='Provisionsfähiger Betrag',
                        ENU='Commissionable Amount';
        }
    }

    keys
    {
        key(Key1;"Currency Code")        {        }
    }

    fieldgroups    {    }
}
```

The report display this fields:
```
report 50000 "Test RDLC"
{
    DefaultLayout = RDLC;
    RDLCLayout = './Test RDLC.rdlc';

    dataset
    {
        dataitem("Test RDLC";"Test RDLC")
        {
            column(Curr;"Test RDLC"."Currency Code")  {  }

            // This field cause the trouble
            column(Comm;"Test RDLC"."Commissionable Amount")  {  }
        }
    }
    labels
    {
        label(TestText;DEU='Test',
                       ENU='test')
    }

    var  TextTest : Label 'TestText';
}
```

The report uses an RDLC-File (included in the ZIP) and display the 2 columns.

[Test RDLC.zip](https://github.com/Microsoft/AL/files/1562441/Test.RDLC.zip)

When I comment out the line **AutoFormatExpression = "Currency Code";** in the **table**, the Extension is deployed correct and the debugger starts.

**Comment by TimothyWatkins** [comment]
I believe I have the same issue though am unsure of why... My report is a simple report and has been compiled and runs in 2018, then converted to AL code. I receive the following error when Publishing in a container/docker environment. I have successfully published 2 other reports in the same manner.
-------------------------------------------------------------------------------------------------------------------
__The request for path /nav/dev/apps failed with code InternalServerError. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Group93aeb35ec7aa9687a6954ceb4d7ab578_Report54275.cs(143,21) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Group93aeb35ec7aa9687a6954ceb4d7ab578_Report54275.cs(143,145) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.Report54275' does not contain a definition for 'GetFieldValueSafe' and no extension method 'GetFieldValueSafe' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.Report54275' could be found (are you missing a using directive or an assembly reference?)
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Report\Group93aeb35ec7aa9687a6954ceb4d7ab578_Report54275.cs(156,94) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.Report54275' does not contain a definition for 'GetFieldValueSafe' and no extension method 'GetFieldValueSafe' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.Report54275' could be found (are you missing a using directive or an assembly reference?)_
-------------------------------------------------------------------------------------------------------------------

**Comment by megel** [comment]
Look at the fields referenced by the report columns. If at least one of this fields contains an AutoFormatExpression, try to comment the AutoFormatExpression out and start again.

**Comment by TimothyWatkins** [comment]
Yes, thank you.

field(8;Amount;Decimal)
        {
            //AutoFormatExpression = "Currency Code"; //Commented out and now publishes
