### ISSUE TITLE
Programming license doesn't allow me to publish objects in our product range

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1207]
```
Microsoft (R) AL Compiler version 0.12.15355
Copyright (C) Microsoft Corporation. All rights reserved

Success: The package is created.
---
[2017-12-14 16:24:47.92] Sending request to http://localhost:7049/Product/dev/apps
[2017-12-14 16:24:53.70] The request for path /Product/dev/apps failed with code 422. 
Reason: Your programming license doesn't allow you to publish Product Setup.
```
License is uploaded in classic dev (and saved in database) and the service is restarted
![image](https://user-images.githubusercontent.com/34303738/34038850-0455b524-e18e-11e7-8a87-5a87bf0bb54b.png)

App.json:
```
  "idRange": {
    "from": 50000,
    "to": 2049514
  }
```

Object
New file, created with ttableextension snippet and 1 new field added
```
table 2048883 "Product Setup"
{

    fields
    {
        field(1;MyField;Integer)
        {
        }
        field(100;"Volume Unit of Measure";Code[10])
        {
            CaptionML = ENU='Volume Unit of Measure',
                        FRB='Unité de Volume',
                        NLB='Volume Eenheidscode';
            TableRelation = "Unit of Measure".Code;
        }
    }

    keys
    {
        key(PK;MyField)
        {
            Clustered = true;
        }
    }
}
```

If I give the file a 50100 number, the app publishes.

This license allows us to create and use objects in the classic env in our object range.

**Comment by kalberes** [comment]
You need Insert rights from your license for the id 2048883.

**Comment by SirBETE** [comment]
Correct!
Our license didn't include the insert permissions for our object range.
The old license was created quickly after NAV2018 came out.
MS must have updated the license creation process in the past weeks.
Creating a new license solved this.
TYVM!
