### ISSUE TITLE
The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1208]
I am getting this error when downloading packages in VS Code. I have generated my own package. We have little over 7000 objects.

![2100 parameter](https://user-images.githubusercontent.com/7205122/34040600-5500f064-e149-11e7-9e12-eb3a92743b29.png)

**Comment by markbrummel** [comment]
I've generated my symbols manually using the Microsoft.Dynamics.Nav.SymbolReferenceGenerator.exe

This works fine. At least, it looks like that for now.

**Comment by kalberes** [comment]
That error is not issues when downloading but when you have generated the symbols.
How did you create your symbols? By starting finsql.exe with generatesymbolreference flag and in the UI you have compiled all objects? Then this issue will happen. That is a bug fixed for CU1.
But this step should not be needed. The command generatesymbolreference does it all for you.
Also SymbolReferenceGenerator eventhough it will generate symbols **it cannot** generate as good symbols as C/SIDE. You may expect scenarios where you will not be offered as good services(e.g intellisense, lookup for symbols etc) as symbols generated from C/SIDE. An example would be if anything in our compiler services that depends on the type of the sourecexpression of a control field

**Comment by markbrummel** [comment]
All objects compile. I've started the finsql.exe with the generatesymbolreference.

After that there is nothing in the [NAV App Resource] table (Except the system symbols)

This error happens when I run the download symbols from VSCode. I see this error in the windows event log.

If the error is fixed in CU1 then it is ok for me. I can continue now. I just succesfully published my first extension in my hybrid database. I am already spending way more hours getting this to work than I want.

Hope you understand.

**Comment by kalberes** [comment]
My suggestion is still just let the finsql.exe command=generatesymbolreference .... (The command line version, not the UI started with the flag called the same.)
That should create your symbols. I know that we have some issues right now that we have only published the System symbols and the Application symbols only with Cronus. 
We will also publish soon all these required symbols to a downloadable location that anyone can publish them for themselves in their own database. Then hopefully things will be easier.

**Comment by markbrummel** [comment]
I'm good for now. I'll test again on CU1

**Comment by StanislawStempin** [comment]
Closing the issue. Please let us know if this is still a problem after CU1
