### ISSUE TITLE
Txt/fob to AL converter

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#121]
Hi,

Are there plans to create a tx/fob to Al converter so that they can be easily converted to 7 million series al files.

or do you have an advice for that how can we do this?

Thanks
Varun Reddy

**Comment by StanislawStempin** [comment]
We do plan on releasing a txt -> Al conversion tool. In the initial release it will not support object id renumbering but focus only on syntax conversion.

**Comment by freddydk** [comment]
This tool https://blogs.msdn.microsoft.com/freddyk/2017/02/28/renumbering-nav-object-ids/ supports AL files as well as txt and delta files - might be able to help on the renumbering.

**Comment by bachii1010** [comment]
Hi,

Thanks for the answers this helps us
Also will the converter be able to convert from AL to .txt? (Both sides)

Thanks,
Varun Reddy

**Comment by DominikDitoIvosevic** [comment]
Hi,
The tool is only intended to do one way conversion from .txt to .al files. There is no plan to support the reverse since we are moving away from it. Why would you need to convert back?
