### ISSUE TITLE
Substitution for License Information

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#1210]
License Information is no longer valid for extension development. 

Are there any alternative to get to customer information for the installation in which the
solution is running?

**Comment by kalberes** [comment]
The License information is an application global virtual table and cannot be exposed in cloud based scenarios. But if you only use it for NAV 2018 then you can use it, if your extension is marked as internal(target:Internal in app.json) and the server's ExtensionAllowedTargetLevel is also set to internal.

**Comment by NicolaiEsbensen** [comment]
@kalberes or any other. What im looking for is at unique identifier for the installation, previously we would use information from the database table together with som information in the License. 

Does anyone know if there will be other unique customer/installation identifiers in perhaps new virtual tables?

**Comment by tfenster** [comment]
We use GetAadTenantId from Codeunit Identity Management which returns a unique ID. Or am I missing what you need?

**Comment by NicolaiEsbensen** [comment]
@tfenster seems like exactly what we need. Thank you :)
