### ISSUE TITLE
GetDecimalString Error

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1212]
Ok, to I managed to publish a bunch of page extensions in my hybrid database, but 3 pageextensions failed. All with the same error.

Is this a known issue to you? For now I've just removed the pageextensions from the package.

c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$2018TST\source\PageExtension\PageExtension50010.cs(108,197) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50010' does not contain a definition for 'GetDecimalString' and no extension method 'GetDecimalString' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50010' could be found (are you missing a using directive or an assembly reference?)

**Comment by DominikDitoIvosevic** [comment]
hmm which version are you on? I fixed a bug on that one a long time ago. Do you have to pass the page extension there or could you use a page instead as a workaround?

**Comment by markbrummel** [comment]
NAV2018 RTM.

**Comment by srinivasGangadhara** [comment]
Hi,

Am also facing same issue cloud you update on this issue?

Thanks!
Srinivas

**Comment by RonSkalski** [comment]
Hi,

I just ran into this same issue. I added a Boolean and a Decimal field to the end of the Item Record. I get the error when I try to add the Decimal field to the item card. I learned that if I change the Boolean to an integer I no longer get the error. Unfortunately, that won't work for my extension. BTW - these changes are all in the same extension
