### ISSUE TITLE
Delete existing Packages when downloading new ones

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1213]
Should the command to download packages delete the old ones?

I am now getting multiple packages when I try to connect older projects to a customer database.

True, I can delete them myself before downloading them. If this is how it should work, then please acknowledge and I can put that on my blog or something.

![symbols](https://user-images.githubusercontent.com/7205122/34043406-c7352e28-e155-11e7-9624-2ed1be98449e.png)

**Comment by kalberes** [comment]
We have not done anything to delete old packages, thus I would say "yes this is how it should work"

**Comment by markbrummel** [comment]
Ok, thanks.
