### ISSUE TITLE
-

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1214]
-

**Comment by markbrummel** [comment]
Any updates on this? It is very anoying that I need to switch licenses (from customer license to partner license) each time I publish my extension.

**Comment by esbenk** [comment]
Allowing you to publish without license check would allow anyone to publish into your license range and run it with a customer license. 

In C/SIDE you would also need the partner license to create those tables.

**Comment by markbrummel** [comment]
As a customer you can always import a FOB file you get from a partner, also if that FOB file contains tables outside your license. The situation now is that as a customer you can no longer import an extension with tables outside the license.

This is a bug, and a huge one, that needs to be resolved before this hits mainstream usage.

Extensions need to work the same way with the license as C/Side or better, not worse.

**Comment by esbenk** [comment]
We have introduced the concept of runtime packages to allow a partner to send an .app file to a customer. The runtime package .app file can be imported using the customer license similar to the FOB.

There is a description of runtime packages in the [blog](https://blogs.msdn.microsoft.com/nav/2017/11/08/nav-development-preview-november-update/ )

The runtime package is created running the Get-NavAppRuntimePackage cmdlet against the development server.

**Comment by markbrummel** [comment]
Esben, this is totally unacceptable. We need to be able to see our own code in the debugger. How can I escalate this? Or do I just need to wait until someone else hits this brick wall. Shipping customizations with temporary tables is totally normal, and when shit hits the fan on monday morning after go-live you need to be able to start the debugger on the session that is causing the problem. This is exactly why the debugger in the windows client is so amazing.

Why is Microsoft making licensing such a pain for customers who want to do some inhouse development. In C# I can make as many classes and pages as I want, in SQL server I can create as many tables as I want. But as soon as you wrap C# and SQL into NAV everything is limited.

I can work around this for now. Go ahead and close the case. I don't want to burn anymore energy into this topic.
