### ISSUE TITLE
Error when publishing app in 2018 and December Release

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#1215]
I get an error when publishing our extension. 

It creates an app file however only 1Kb big. So i think the issue occurs in the compilation.

I've attached the stacktrace. I can't point out where the issue is, however it should be reproducable
with our source which i can share in a less public location if one is provided.
[StackTrace.txt](https://github.com/Microsoft/AL/files/1562807/StackTrace.txt)

**Comment by thpeder** [comment]
We would appreciate it if you could have a second look at your code and hopefully find the problem and a small repro for it.

From the stacktrace it looks to be related to a flowfield on a table where a property (CalcFormula or TableRelation) has a filter with a const of an option value.

**Comment by NicolaiEsbensen** [comment]
@thpeder nicely spotted. I could not deduct that from that trace :) That was indeed the issue, however the syntax checker user to report this error in the oct/nov release, that's why i didn't remember to correct that when i converted our onprem solution.

**Comment by thpeder** [comment]
It helps a lot to have access to the source code :)

We shouldn't crash on anything so if you could write a small example of what the problem is so we can get it fixed.

**Comment by kalberes** [comment]
This is a bug. Do you maybe have a repro object? It is one of your TableRelation having an option reference in its condition?

**Comment by NicolaiEsbensen** [comment]
Hi @thpeder and @kalberes. We don't have our source in a public repo currently. However with your suggestions i was able to isolate the error. 

We have at table with a field type (no. 3)  with the option string members
OptionMembers = " ","G/L Account",Item,,"Fixed Asset","Charge (Item)";

And in the same table we have a field with a table relation dependent on that field
TableRelation = IF (Type=CONST(" ")) "Standard Text"
                            ELSE IF (Type=CONST("G/L Account")) "G/L Account"
                            ELSE IF (Type=CONST(Item)) Item
                            ELSE IF (Type=CONST(3)) Resource
                            ELSE IF (Type=CONST("Fixed Asset")) "Fixed Asset"
                            ELSE IF (Type=CONST("Charge (Item)")) "Item Charge";

So it's the Type=CONST(3) relation that causes the crash. I checked if you do ExportToNewSyntax and the
convert to CAL you will get an error stating that the value 3 is not defined, which makes sense. The line would then look like this.
ELSE IF (Type=CONST("3")) Resource

However it's been a valid thing to do for all previous versions, referencing an option value by it's number rather than is name (you could argue that we should just define a value, i don't know the history for this table why this is not done). I'll leave it up to you to decide what should be done, I'm just reporting how to reproduce the error which is to define at table with the two fields i mentioned (attached the full table source).

[Table 6085775 - Std. Amount Distribution Line.al.txt](https://github.com/Microsoft/AL/files/1567014/Table.6085775.-.Std.Amount.Distribution.Line.al.txt)

**Comment by kalberes** [comment]
It should still be valid to reference an option value by its ordinal.  The issue here is that the ordinal value 3(counting from 0) is ,, (null).

**Comment by NicolaiEsbensen** [comment]
@kalberes ok, yes is a null exception we get. string.Empty would probably be a more fitting value :)
