### ISSUE TITLE
finsql.exe generatesymbolreference=yes

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1216]
Is this command
`finsql.exe generatesymbolreference=yes`
supposed to open FINSQL?

It does not do that for me, but the [documentation ](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side) says:

> without the generatesymbolreference flag set to yes, no symbols will be generated when downloading symbols from Visual Studio Code.

What am I missing?

**Comment by kalberes** [comment]
Where do you try opening finsql.exe from? it should be your client location.

**Comment by GreatScott000** [comment]
I open a Command Prompt as Administrator, change to the C:\Program Files (x86)\Microsoft Dynamics NAV\110 folder then enter the command:
`finsql.exe generatesymbolreference=yes`

**Comment by GreatScott000** [comment]
FYI this is NAV2018 RTM

**Comment by kalberes** [comment]
Anything in the event viewer, like a missing assembly?

**Comment by kalberes** [comment]
Is this your "RoleTailored Client" install directory?

**Comment by GreatScott000** [comment]
Sorry forgot to include the RoleTailored Client in the path I typed.  I do NOT get an error about FINSQ being an external program that I would get if FINSQL was not in the current folder.  This is a default install of the RTC and ModernDev components.  The one thing is that the NAV Service Tier and SQL server are on another server (but I get the same results on that server too).

**Comment by GreatScott000** [comment]
There are no application event viewer messages.

**Comment by kalberes** [comment]
Ok extremely weird. C/SIDE does not open at all if you pass this flag? Doesn't even say unknown command. And without this flag it opens.
You must have a malformed installation, or else I have no clue.
Could you check whether you have the following assemblies in your RTC client install location.
Microsoft.Dynamics.Nav.SymbolReferenceGeneratorImpl.dll
Txt2AlConverter.dll

**Comment by GreatScott000** [comment]
Okay, I reinstalled and it worked.  The only weird about the install is I
updated the install with the Microsoft Outlook Addin after the original
install.  Well it is working now.
