### ISSUE TITLE
Expose function T36.ValidateShortcutDimCode 

### ISSUE THREAD

**Issue by jwikman** [Microsoft/AL#1221]
Please make the function ValidateShortcutDimCode  in table 36 Global and External

```
[External]
PROCEDURE ValidateShortcutDimCode@19(FieldNumber@1000 : Integer;VAR ShortcutDimCode@1001 : Code[20]);
```
![image](https://user-images.githubusercontent.com/23032645/34109241-4487b1d4-e403-11e7-8897-7cf982b72211.png)

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
