### ISSUE TITLE
.Net Interopability

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#124]
Hi,

When i was working in Extensions 2.0 with files and file Management codeunit i see the .net interopability is 
not supported.

can you tell me if this will be supported in future and can you also tell us the precise timing.

Also is there an alternative for now to work on this?

Thanks,
Varun Reddy

**Comment by StanislawStempin** [comment]
Running arbitrary .NET code in the cloud in a safe manner is a specialized task. We will be handing over this task to other services our recommendation being Azure Functions (https://azure.microsoft.com/en-us/services/functions/) 
At the same time we are adding more functionality to the AL language and core library to satisfy the most common .NET usages. So far we have added HTTP and JSON types to enable you to call out to other web services.
You can see draft documentation here under REST API section:
https://msdn.microsoft.com/en-us/dynamics-nav/newdev-reference-overview

You can also take a look at a sample usage in this GitHub repository:
https://github.com/Microsoft/AL/tree/master/samples/GetAddressService

Upcoming improvements to AL core library include XML handling support and enhanced String handling.

**Comment by bachii1010** [comment]
Hi,

So we cannot have the complete .net variables access as we have in NAV Dev environment in On premise in future also?

Thanks,
Varun Reddy

**Comment by IgorPcelnikov** [comment]
On TechDays2016 (check mibuso) guys told that they will get rid of .NET interop and will introduce more AL syntax to core (strings, collections and etc. management) that will cover basics. There are no TBD for these.
GUI add-ins looks like will be JS with .NET DLL manifest as it is now... - again not clear for how long and not sure if that will not change, I assume they will get rid of dotnet add-ins.
If you want to handle specific .NET code to do job for you - you can use Azure Functions (you can do .NET stuff there) and publish via WS and consume results from your extension. So in general - welcome to WS/Json world! :)

Would be very good MS would publish plan or roadmap on what we'll have at the end of the day.

Thanks,
  Igor Pcelnikov

**Comment by bachii1010** [comment]
Hi,

So One more Question
I have created a .net dll and want to use it in extensions 2.0 do you guys have a code example to use it?

Thanks
Varun Reddy

**Comment by esbenk** [comment]
There is currently no support for .net interop in extensions v2. We plan to make that available for on-prem development in the future, but not for SaaS.
