### ISSUE TITLE
Event Request C400.OnBeforeCreateMessage, OnBeforeAddRecipients, OnBeforeAddCC, OnBeforeAddBCC

### ISSUE THREAD

**Issue by jwikman** [Microsoft/AL#1240]
Please add the following 4 events to Codeunit 400:
```
[Integration]
LOCAL PROCEDURE OnBeforeCreateMessage@12044964(VAR SenderName@12044964 : Text;VAR SenderAddress@12044963 : Text;VAR Recipients@12044962 : Text;VAR Subject@12044961 : Text;VAR Body@12044960 : Text;HtmlFormatted@12044959 : Boolean);

[Integration]
LOCAL PROCEDURE OnBeforeAddRecipients@12044968(VAR Recipients@12044958 : Text);

[Integration]
LOCAL PROCEDURE OnBeforeAddCC@12044969(VAR Recipients@12044958 : Text);

[Integration]
LOCAL PROCEDURE OnBeforeAddBCC@12044970(VAR Recipients@12044958 : Text);
```
All parameters, except HtmlFormatted, needs to be VAR

Call the event OnBeforeCreateMessage from  CreateMessage:
```
PROCEDURE CreateMessage@1(SenderName@1008 : Text;SenderAddress@1000 : Text;Recipients@1001 : Text;Subject@1004 : Text;Body@1005 : Text;HtmlFormatted@1006 : Boolean);
BEGIN
  OnBeforeCreateMessage(SenderName,SenderAddress,Recipients,Subject,Body,HtmlFormatted);
  IF Recipients <> '' THEN
    CheckValidEmailAddresses(Recipients);
  CheckValidEmailAddresses(SenderAddress);
  SMTPMailSetup.GET;
```
![image](https://user-images.githubusercontent.com/23032645/34131430-d6933c22-e44b-11e7-94c8-e627ef594521.png)

Call the event OnBeforeAddRecipients from  AddRecipients:
```
PROCEDURE AddRecipients@4(Recipients@1000 : Text);
VAR
  Result@1001 : Text;
BEGIN
  OnBeforeAddRecipients(Recipients);
  CheckValidEmailAddresses(Recipients);
  Result := Mail.AddRecipients(Recipients);
  IF Result <> '' THEN
    ShowErrorNotification(STRSUBSTNO(RecipientErr,Recipients),Result);
```
![image](https://user-images.githubusercontent.com/23032645/34131435-df6e468e-e44b-11e7-9bff-dc778d6308ff.png)

Call the event OnBeforeAddCC from  AddCC:
```
PROCEDURE AddCC@5(Recipients@1000 : Text);
VAR
  Result@1001 : Text;
BEGIN
  OnBeforeAddCC(Recipients);
  CheckValidEmailAddresses(Recipients);
  Result := Mail.AddCC(Recipients);
  IF Result <> '' THEN
    ShowErrorNotification(STRSUBSTNO(RecipientErr,Recipients),Result);
```
![image](https://user-images.githubusercontent.com/23032645/34131445-e5ad7128-e44b-11e7-8087-a0225dc8d3a1.png)

Call the event OnBeforeAddBCC from  AddBCC:
```
PROCEDURE AddBCC@6(Recipients@1000 : Text);
VAR
  Result@1001 : Text;
BEGIN
  OnBeforeAddBCC(Recipients);
  CheckValidEmailAddresses(Recipients);
  Result := Mail.AddBCC(Recipients);
```
![image](https://user-images.githubusercontent.com/23032645/34131452-ebd72a30-e44b-11e7-8e7c-3d4f20e7f7eb.png)

**Comment by AlexanderYakunin** [comment]
Hi! All procedures in COD 400 already have External property, so you can simply call CreateMessage from your extension with needed parameters instead of using event. Same for other asks. Please confirm if you really need this.

**Comment by jwikman** [comment]
Hi Alexander!

We still need those events, because we've got a feature that modifies all e-mails sent under certains circumstances. If we don't have these events, we would need a LOT of events all over the application where CU400 is called. :)

**Comment by jwikman** [comment]
And of course all new events should be marked as [External], I just need to remember that from now on...
