### ISSUE TITLE
Event Request C5321.OnBeforeSendEmailMessageWithAttachment and OnBeforeSaveHTMLEmailToInbox

### ISSUE THREAD

**Issue by jwikman** [Microsoft/AL#1248]
Please add the following two events to Codeunit 5321:
```
[Integration]
LOCAL PROCEDURE OnBeforeSendEmailMessageWithAttachment@12044959(VAR Subject@12044962 : Text;VAR RecipientAddress@12044961 : Text;VAR BodyHTML@12044960 : Text;VAR AttachmentPath@12044959 : Text;VAR SenderAddress@12044958 : Text);

[Integration]
LOCAL PROCEDURE OnBeforeSaveHTMLEmailToInbox@12044960(VAR EmailSubject@12044962 : Text;VAR EmailBodyHTML@12044961 : Text;VAR SenderAddress@12044960 : Text;VAR SenderName@12044959 : Text;VAR RecipientAddress@12044958 : Text);
```
All parameters needs to be VAR

Call the event OnBeforeSendEmailMessageWithAttachment from  SendEmailMessageWithAttachment:
```
PROCEDURE SendEmailMessageWithAttachment@22(Subject@1000 : Text;RecipientAddress@1001 : Text;BodyHTML@1004 : Text;AttachmentPath@1002 : Text;SenderAddress@1003 : Text);
BEGIN
  OnBeforeSendEmailMessageWithAttachment(Subject,RecipientAddress,BodyHTML,AttachmentPath,SenderAddress);
  Service.SendMessageAndSaveToSentItems(Subject,RecipientAddress,BodyHTML,AttachmentPath,SenderAddress,'');
END;

```
![image](https://user-images.githubusercontent.com/23032645/34150368-77c73df8-e4a8-11e7-92d4-e4a15d4d5db0.png)

Call the event OnBeforeSaveHTMLEmailToInbox from  SaveHTMLEmailToInbox:
```
PROCEDURE SaveHTMLEmailToInbox@21(EmailSubject@1000 : Text;EmailBodyHTML@1001 : Text;SenderAddress@1002 : Text;SenderName@1003 : Text;RecipientAddress@1004 : Text);
BEGIN
  OnBeforeSaveHTMLEmailToInbox(EmailSubject,EmailBodyHTML,SenderAddress,SenderName,RecipientAddress);
  Service.SaveHtmlMessageToInbox(EmailSubject,EmailBodyHTML,SenderAddress,SenderName,RecipientAddress);
END;

```
![image](https://user-images.githubusercontent.com/23032645/34150372-7a1e98a8-e4a8-11e7-9779-3d58fa57fe2f.png)

**Comment by jwikman** [comment]
Of course all new events should be marked as [External], I need to get used to that.

**Comment by AlexanderYakunin** [comment]
Not possible to implement, we are not allowed to expose AttachmentPath via event due to security reasons.

**Comment by jwikman** [comment]
I see. I don't need the AttachmentPath, I just wanted the event to be more generic.

So I'm happy if you skip that parameter and implemented the rest.  👍🏻

**Comment by jwikman** [comment]
@AlexanderYakunin, will it be possible to implement the rest, omitting AttachmentPath?
