### ISSUE TITLE
C/AL Object/Text to Visual Studio Code

### ISSUE THREAD

**Issue by alanb999** [Microsoft/AL#125]
During the Dynamics NAV March webinar, a tool was demonstrated to convert existing NAV objects to VS Code.
Can you please identify where to find the Tool in the development preview.

**Comment by StanislawStempin** [comment]
The tool will be available in the April Update coming out later this month. More details about the tool will be available in the blog post announcing the release.

**Comment by alanb999** [comment]
Thanks for the update.

Can you make the existing C/AL objects for the NAV 2017 development preview available in VS Code, this would assist in testing especially with reports.

**Comment by StanislawStempin** [comment]
You can have a look at some samples under c:\demo\new develop experience\AL if I remember correctly. If you change the name and ID you can deploy most of these samples from VS Code.
With the April Update you will be able to convert all of the base object using the conversion tool

**Comment by ChaficSaade** [comment]
@alanb999 does the vscode supports the reports and the menuisuite?

**Comment by StanislawStempin** [comment]
Extensions V2 in VS Code do support reports, see the [docs](https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-report-object).

Menusuites are not available, see the [FAQ](https://github.com/Microsoft/AL/wiki/AL-Language-Wiki#menusuite-objects-are-not-yet-supported-what-do-i-do) for more details
