### ISSUE TITLE
Test Framework and Extensibility

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#1250]
We are investigating to leverage the test framework for our solution. We will face many scenarios where we will need to attach our own initialization logic to standard tests in order to get them to run properly.

Request: please add event publishers to all `Initialize()` functions in all test codeunits.

Request: please add event publishers to general actions in the test framework, i.e. when one gets all test codeunits and when one starts the tests and when all tests have finished.

**Comment by lvanvugt** [comment]
Hi Rafael, this what I have asking MS about a long time, and what I have been advocating on my NAV TechDays sessions. And I can tell MS has been listening and are investigating it. Keep tuned.
If you already want a solution I am glad to share my deltas containing the adlustment I did.

**Comment by RafaelKoch** [comment]
Hi Luc, this is a small world we live in. One reason why we want to pick this up (again) is just this last training of yours at TechDays where one of my colleagues participated. Also, maybe You remember, we chatted over lunch the very same day. So very nice to read from You now!

I would very much like to get a look at your adjustments! I struggle to see how You will pull off the extensibility without events, but one lives to learn. :-)

**Comment by lvanvugt** [comment]
Send me a mail so I can share: lvanvugt@fluxxus.nl

**Comment by AlexanderYakunin** [comment]
We currently use test libraries to customize application setup. Please check how Codeunit 131300 Library - ERM find/update/create Gen/VAT Posting Setup depending on available data and how Codeunit 131305 Library - ERM Country Data adopt country specific setups.

Investigation on how to make test automation extensible is in progress, options with events is also considered, but I don't have information about next steps in this area yet.

**Comment by lvanvugt** [comment]
@AlexanderYakunin indeed an example and the one I took to insert my hook into  Intialize function on almost all test codeunits. And I am happy this being picked up now by your team. Looking forward to test it.

**Comment by AlexanderYakunin** [comment]
Rafael, usually Initialize functions contains multiple calls of other functions, where do you want to have events? Can you give me some samples what kind of problems you are going to address with such events (i.e. what kind of data you want to add/adjust etc.)?

**Comment by RafaelKoch** [comment]
Sorry for the delay and also for the confusing issue ... I will try to explain in more detail what I am trying to achieve. And also why we can drop this request for now ;-)  

Assume we have extended the application with a new feature, something very general that does actually happen. It does not actually matter if it is an Extension or a traditional modification of the base app. Say we add a field to a customer and depending on that field we do stuff to each Sales Order created for that customer. Then when posting we transport some data to the posted tables. Now to the tricky part: It is prohibited to post without this data, we have put checks and assumptions into the routines that will result in a runtime error. So in a system with this Extension/modification no test will perform successfully without proividing for that feature.

Now what I would need to do is actually two things:
1. Make the Microsoft test work again - I still want to know if posting does work after all
1. Make a test for what I expect my modification to do

The second task is easy enough. I write my own test runner and my own test units, those can be well separated from Microsoft's and still work fine in the framework.

The first task is trickier, to make this work again I would in this example need to alter the way `Codeunit 130509 Library - Sales` works in function `CreateCustomer `and/or `CreateSalesHeader`. Now how do I? I Can either place my own code in those functions or - much preferred - try and extend this without touching.

So this is why I was asking for Publishers in such functions. Yet, after studying the testability framework I am not so sure if this can be easily done as a general request. Some funtions just create data, some also fire routines after creating data, ... so one would have to scrutinize every function where to place a  publisher. And even that could still not be enough because my extension could still break things between validations.   

So maybe not a brilliant idea after all :-) 

What I will probably try is to include codeunits into our own test routines to subscribe to given events, so in this example to validations when creating a customer. That should work just as well for anything where additional/altered data is required. And then I will see how far this gets us.

**Comment by lvanvugt** [comment]
@RafaelKoch very clear and a meaningful wish.

**Comment by pborring** [comment]
Closing this old entry, as it looks like Rafael took a different path. If still issues, then please go ahead and post this to our Ideas forum at https://aka.ms/bcideas, or vote up the idea if its already there, as this GitHub tracks bugs to AL Language and VSC VSIX.
Thanks

**Comment by RafaelKoch** [comment]
@pborring: Wow, You dug up an oldie here :-) Good riddance!
