### ISSUE TITLE
Application Enhancement Request "Deferral Code".AssistEdit

### ISSUE THREAD

**Issue by jwikman** [Microsoft/AL#1251]
Please add AssistEdit code on the "Deferral Code" field, so that the user can use that instead of a three click navigation in the actions menu.

In table 37, add the function DeferralCodeAssistEdit:
```
PROCEDURE DeferralCodeAssistEdit@12044960();
BEGIN
  SalesHeader.GET("Document Type","Document No.");
  ShowDeferrals(SalesHeader."Posting Date",SalesHeader."Currency Code");
END;
```

In table 39, add the function DeferralCodeAssistEdit:
```
PROCEDURE DeferralCodeAssistEdit@12044960();
BEGIN
  PurchHeader.GET("Document Type","Document No.");
  ShowDeferrals(PurchHeader."Posting Date",PurchHeader."Currency Code");
END;
```

Then add a call to the functions created above in the OnAssistEdit trigger for field "Deferral Code" in pages:
* 46, Sales Order Subform
* 47, Sales Invoice Subform
* 54, Purchase Order Subform
* 55, Purch. Invoice Subform
* 96, Sales Cr. Memo Subform
* 98, Purch. Cr. Memo Subform
(there are probably more pages, but those been requested by users)

```
Deferral Code - OnAssistEdit()
DeferralCodeAssistEdit;
```
![image](https://user-images.githubusercontent.com/23032645/34158134-85c6efcc-e4c4-11e7-9849-1e14a6f91ccd.png)

Also add the following code into OnAssistEdit trigger for field "Deferral Code" in page 39, General Journal
```
Deferral Code - OnAssistEdit()
IF "Account Type" = "Account Type"::"Fixed Asset" THEN
  ERROR(AccTypeNotSupportedErr);

ShowDeferrals("Posting Date","Currency Code");

```
![image](https://user-images.githubusercontent.com/23032645/34158141-8ba02738-e4c4-11e7-8775-152579946d29.png)

The code used for AssistEdit is copied from the action "Deferral Schedule", so a small refactoring by moving that code to a function used by both action and AssistEdit might be a bit better.

**Comment by GiorgosPa** [comment]
Hello @jwikman, is there a specific reason that you get the posting date from the header? Since the change you are proposing is per line it seems better to get the posting date from the line instead

**Comment by jwikman** [comment]
Hi @GiorgosPa, the reason is that that's the way it works if you use the action "Deferral Schedule". 
![image](https://user-images.githubusercontent.com/23032645/34682620-c00425b6-f49f-11e7-972d-fca60fcdb4b8.png)

Actually this is a bit of code cloning, so it would be even better if you refactored the code from the action into a new function and then call that function from both the action and the AssistEdit functions I requested.. My proposal did just a bit less changes to existing code,  but could of course be improved. :)

**Comment by GiorgosPa** [comment]
Oh I see, but still they both operate on a sales line.
