### ISSUE TITLE
"Edit in excel" action and "Configuration Package Creation" on Dynamics 365 Sandbox

### ISSUE THREAD

**Issue by stanuj** [Microsoft/AL#1255]
Hi,

I want to export customers in excel from Customer List page. When i try to export it by using action "Edit in Excel", it only exports column definitions except data. Is it a bug or normal functionality in Sandbox?

When i'm trying to create a new configuration package in sandbox,
1. I can create this only in a new company not in Cronus.
2. Once i create a new config. package, it disappears from configuration package list page.

After creation of new company, i create an another new company by copy company action. In new copied company, there is same issue as i can't create new config. package and edit copied config. package.

I mean to say, Edit config. package is standard config. package provided automatically in sandbox.

Please provide guidance to resolve these issue.

**Comment by StanislawStempin** [comment]
Hi @stanuj, this GitHub repository is only for AL development related issues. Please contact regular support channel for your issue.
