### ISSUE TITLE
Page Extension existing field triggers

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#126]
Hi,

Is there a way in extensions 2.0 to access the **onvalidate** and **onlookup** of the existing fields in pageextension.al file?

We can see that we can access this triggers when we add new field in the Page Extensions

Thanks,
Varun Reddy

**Comment by esbenk** [comment]
If by accessing them, you mean changing the original OnValidate/OnLookup code the answer is no. You can add both OnBeforeValidate and OnAfterValidate triggers to existing table-fields and page-fields.

The triggers that can be used in extensions corresponds to the events supported in 2017. You can see that list here

https://msdn.microsoft.com/en-us/library/mt299406(v=nav.90).aspx#PageEvents

The new trigger syntax in extensions is an easier way to subscribe to the existing triggers.
