### ISSUE TITLE
Tablerelation with condition not working on a page field.

### ISSUE THREAD

**Issue by gudrunleos** [Microsoft/AL#1260]
Prerequisites: None of the customers are marked "Combine shipments" in either case.

in V2:
![image](https://user-images.githubusercontent.com/24827406/34215633-e9fde566-e59d-11e7-9c5f-277eea697e41.png)

Results in:
![image](https://user-images.githubusercontent.com/24827406/34215702-236b0dd8-e59e-11e7-9645-21604697765e.png)

Same in V1:
![image](https://user-images.githubusercontent.com/24827406/34216187-763cc014-e59f-11e7-8259-af8d956ea248.png)

and the result:
![image](https://user-images.githubusercontent.com/24827406/34216249-9ee3d174-e59f-11e7-88b4-3e276c2f0749.png)

**Comment by atoader** [comment]
Thanks for reporting this, @gudrunleos ! We will investigate and get back to you as soon as possible.

**Comment by gudrunleos** [comment]
Fixed :)

**Comment by gudrunleos** [comment]
Is it possible that this is still at large in table fields?

**Comment by gudrunleos** [comment]
Tested with Build 20539 - Fixed there, reclosing this issue
