### ISSUE TITLE
[Question] Toggle the Enable Field for base nav keys.

### ISSUE THREAD

**Issue by iWorksJared** [Microsoft/AL#1262]
I have an application that requires certain keys to be enabled in a table. I just want to know if it is possible to enable these keys with extensions?

Thank you.

**Comment by thpeder** [comment]
Thank you for your question.
It is not supported to modify keys with table extensions.

**Comment by iWorksJared** [comment]
okay. can we just select the "enable" boolean in the Keys for a table? There are few keys that are disabled by default and we need to enable them. I am wondering if that counts as modifying the base product?

**Comment by thpeder** [comment]
It does count as modifying the base product.
The problem is that when running it in a multi tenant environment then changes like that will also affect other tenants.
