### ISSUE TITLE
error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '11.0.0.0' could not be loaded.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1263]
Questions at the end in bold.

After upgrading a NAV 2017 database to NAV 2018, I tried to deploy my extensionv2 app to the server following instructions on (https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-how-publish-and-install-an-extension-v2).
After issuing the Publish-NAVApp command from within the NAV 2018 Admin Shell I got the following error:

> Publish-NAVApp
> : Extension compilation failed 
> error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '11.0.0.0' could not be loaded.

It then went on to list all of the objects (standard objects that the extension references) that could not be found.
The publish works OK for the clean CRONUS install, so we knew it was something to do with the database we had upgraded.
I set the “Enable loading application symbol references at server startup” property to ticked on the server instance and ran the finsql.exe Command=generatesymbolreference
This seemed to remove all the errors relating to the standard application objects but it did not fix the problems with the system tables.
In the end, I solved my problem by taking these two files from the CRONUS database (by using VS Code to download the symbols) and then manually re-deployed the standard application app packages back to the upgraded DNE database using the following commands:

> Publish-NAVApp -ServerInstance MyServerInstance -SkipVerification -PackageType SymbolsOnly -Path "C:\NAVApps\Microsoft_Application_11.0.19394.0.app"
> Publish-NAVApp -ServerInstance MyServerInstance -SkipVerification -PackageType SymbolsOnly -Path "C:\NAVApps\Microsoft_System_11.0.12925.0.app"

This then allowed me to publish my app without errors.

**My questions are: Did I do something wrong in the database upgrade that resulted in these standard apps being missing? Is there a better way of getting these standard app symbols added to the database? Should this be added to the database conversion instructions?**

**Comment by thpeder** [comment]
It doesn't sound like you did something wrong.
What you are missing are the symbol files used when compiling Extension v2 apps.

You can read more about it here, and especial take a look at task 18 where you populate your database with the right symbols.
https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data

**Comment by DavidRoys** [comment]
Thanks, that makes sense.
