### ISSUE TITLE
Can I set the Caption attribute of my ActionGroupDefinition in my app.json file?

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1264]
When I set the UsageCategory property on a page or report, it becomes discoverable through the search option and in the Windows client, through the departments place.
When I build my app, a navigation.xml file is created inside my app package with each of my target objects listed inside an Actions node with a type attribute of ActionGroupDefinition.
One of the attributes on this ActionGroupDefinition type Actions node is Caption which seems to be used to set the Caption of a group that appears in my Departments Place (I haven't actually tried changing this before deployment to see if this really is the case). This gets set to Extension by default when the app is bulit. Is there any property in my app.json file I can set that will determine what this Caption attribute will get set to as I would like my extension to have a real name without needing to hack the contents of my built .app file?

**Comment by thpeder** [comment]
Thanks for reporting the issue. 
It is a known bug we are actively working on resolving at the moment.

**Comment by thpeder** [comment]
Hi @DavidRoys,
It is changed to use the extension name, meaning the name you specify in the app.json file.
