### ISSUE TITLE
Web Client doesn't show field on second column of card page.

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1267]
I have some weird behaviour on the webclient, which I tried to illustrate in the gif below.

- notice the content of the fields that disappears when I toggle view/edit mode.
- also, when I add content, while typing, nothing shows, but again switching to view mode, it shows that stuff I typed... 

![7eacd569-762d-4dad-9d3c-000a31b07240](https://user-images.githubusercontent.com/12088142/34246355-90bf3e82-e62e-11e7-8ea1-17c72ce658d1.

Don't know if this is an isolated issue.. I have it on the latest docker image (finus).

**Comment by Gallimathias** [comment]
@waldo1001 your image is broken

**Comment by ajkauffmann** [comment]
I have the same issue, but only in Chrome. Edge seems to be ok.

**Comment by waldo1001** [comment]
Confirmed!  Works in Edge.
So I guess it's a bug.
/Maximus ;-)

**Comment by thpeder** [comment]
@waldo1001 I get an error message: "Access Denied" for your gif.
Could you try upload it again, or maybe at some other place.

**Comment by waldo1001** [comment]
Nope, not an issue anymore!

but here is the gif again:
![7eacd569-762d-4dad-9d3c-000a31b07240](https://user-images.githubusercontent.com/12088142/38555654-370fd05a-3cc7-11e8-913b-638070ac4796.GIF)

**Comment by StanislawStempin** [comment]
Thanks. Closing the issue based on no repro on the latest builds.
