### ISSUE TITLE
AL Sample of a Wizard Page

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#127]
in the "AL" folder, you have exported some known objects to AL. 
Could you please also export a (simple) wizard page and make it part of the examples?

**Comment by StanislawStempin** [comment]
Good suggestion, more samples as well as the conversion tool will be available in April Update

**Comment by srenders** [comment]
Here's an example. 
I made it based upon the one I created for the HDI video: [How Do I: Design Wizards for HTML Clients in Microsoft Dynamics NAV 2017](https://youtu.be/ljBZmKdsyAc).
[ExamplePageWizard.zip](https://github.com/Microsoft/AL/files/925671/ExamplePageWizard.zip)

(It might not be the best example, but It's something I tried once)

**Comment by waldo1001** [comment]
Thanks, Steven!

**Comment by waldo1001** [comment]
Does this work, @srenders ?
Or does it suppose to work @StanislawStempin ?

Because when I create a wizard from scratch, I don't seem to be able to get the images working, always resulting in just text being shown on the page.

I also get it when I try out Steven's page.
