### ISSUE TITLE
Will Business Charts work in NAV2018?

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1270]
I noticed in the Anniversary release, we now can use the Business Charts.  Will this work in NAV2018?

**Comment by markbrummel** [comment]
Arend Jan said all of this stuff will be shipped with R2 and we only get bugfixes with CU's.

**Comment by waldo1001** [comment]
Well, it's one thing to be able to compile.  It's another thing to be able to run. 
Since the controls are already on the service tiers, I expect it to just run...

**Comment by DominikDitoIvosevic** [comment]
Hi @waldo1001 and @markbrummel . You can use Business Charts from CSIDE but AL support is a feature and we currently don't have a plan to backport it. If there is enough demand we might consider backporting it but as you know, it takes away our resources to deliver new features and adds additional overhead on supporting all these various versions.

You can read more about our general stance about backporting features to CUs here https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018

**Comment by waldo1001** [comment]
So we can't create business charts as part of our apps.
that's - in my opinion - not the best decision ...

**Comment by waldo1001** [comment]
Also, in the description of the Anniversery update here:
https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/

it explicitly mentions:

> A number of built-in control add-ins can now be used in AL extensions: Microsoft.Dynamics.Nav.Client.BusinessChart

On would assume it would work?  The only question I had that it would work in NAV2018 (the RTM version that is available).

Let's just state that the current support for business charts is still not clear to me.  

What can we do in ExtensionsV2 with it?

**Comment by StanislawStempin** [comment]
You can use charts in Extensions V2 if you're using Anniversary Update or later. Dominik was referring specifically to NAV 2018 support.

**Comment by waldo1001** [comment]
So if I would do so, I wouldn't be able to publish my app/Extension on a NAV2018 DB.
That's too bad..

I just assumed I needed the anniversary update to be able to compile the business chart - but I would be able to publish it on a NAV2018, because all the bits and bytes are there anyway...

**Comment by StanislawStempin** [comment]
That's right but publishing involves recompilation. It _might_ work with a runtime package but we haven't tested that.

**Comment by waldo1001** [comment]
Ah .. I didn't realise that.
Well, I personally wouldn't want to depen on a runtime package, so that's a "no go" for me.

I guess I'll have to wait for a new platform update for NAV2018 ;-)
