### ISSUE TITLE
Extensions and C/Side using the same object ID

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1272]
It looks like NAV (C/Side) does not check if an object ID is used in an extension.

I've created codeunit 50250 in an extension and published it. Works fine.

When I then create codeunit 50250 in C/Side NAV uses that one instead.

After deleting the codeunit in C/Side it deletes the metadata and you have to re-publish your extension.

The desired way would be that C/Side checks if an extension is using that ID and raises an error. This is how V1 behaved if I remember correctly.

Merry x-mas.

**Comment by kalberes** [comment]
I am not sure we are going to fix this one though.

**Comment by markbrummel** [comment]
Off course not. It's much more fun getting a support call from a customer who had a fob file that breaks there extension on monday morning in production. That would give NAV an amazing reputation and all the hard work we are doing to promote extensions.

Dude, it's a trigger on the object table checking the metadatatable. I can do this in SQL as a SQL trigger and slap it as a download on mibuso, but that would make Microsoft look bad I and I don't want that.

... no more comments

**Comment by markbrummel** [comment]
Here is a workaround. https://markbrummel.blog/2018/05/01/prevent-c-side-from-using-ids-used-by-extensions/
