### ISSUE TITLE
App Test Automation

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1278]
Hi 

When we are uploading our app to appsource we find a validation for app test automation but we know it is not mandatory it says in the note that we have to upload a .app nav package file.

because we need a test tool to run it, is there a .app file for test tool so that we can use it and add our codeunit in that and create our own .app for test automation.

Please suggest.

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
This is still work in progress. The App Source Validation team will communicate directly with all App authors once the process is ready.

**Comment by StanislawStempin** [comment]
This should have been addressed in the App Source process by now. Please let us know if that's not the case
