### ISSUE TITLE
Licensing model for new extension objects

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#128]
Is there already any information available on the way 'table extension' and 'page extension' objects will be handled by the license file (or on extension licensing in general)? Using these new object types requires additional objects id's / ranges, whereas in the current approach, deltas on standard objects are generated instead (not requiring new object id's).

Will these objects types be available for free? How will 'page extension' objects made through the in-client designer behave towards the license?

Are there any plans to review the licensing model for other object types as well?

**Comment by StanislawStempin** [comment]
This is still being defined, we expect to be able to share more information later this summer.

**Comment by Gallimathias** [comment]
I'd say let's kill the ID's. What is old is old, what is new is new. In addition, you could never really prevent that everyone remained only in the purchased area. Look at Mibuso, the people can SQL.
