### ISSUE TITLE
Decimal places limited to 2

### ISSUE THREAD

**Issue by TaylerPino** [Microsoft/AL#1282]
On the December build, any fields with a decimal places property set higher than 2 is limited to 2 decimal places. Here is the field definition and the result in the web client:

![image](https://user-images.githubusercontent.com/19294127/34265442-e6009fc0-e643-11e7-9ba6-65f7ac7f09ba.png)
![image](https://user-images.githubusercontent.com/19294127/34265547-26a712d4-e644-11e7-8169-bb31a774d51c.png)

**Comment by Kraver88** [comment]
i have the same issue, tried it on Page and Table.
![image](https://user-images.githubusercontent.com/24684493/34292335-d1ebf210-e700-11e7-857b-64c8ffe20122.png)
