### ISSUE TITLE
Request: Enable Keys in Item Ledger Entry Table

### ISSUE THREAD

**Issue by iWorksJared** [Microsoft/AL#1285]
Would it be possible to enable the "Serial No." and "Lot No." keys in the Item Ledger Entry Table please? Currently they are disabled by default and our product relies on them.

Thanks

**Comment by markbrummel** [comment]
IMHO keys should be an object type.

Wait, I suggested that in 2008.

**Comment by StanislawStempin** [comment]
Transferred to: https://github.com/Microsoft/ALAppExtensions/issues/278
