### ISSUE TITLE
There appears to be an issue with temporary Report DataItems

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1286]
Table: 
```
table 50000 TestTable
{

  fields
  {
    field(1;Field1;Integer)
    {
    }
  }

  keys
  {
    key(PK;Field1)
    {
      Clustered = true;
    }
  }

  trigger OnInsert();
  begin
  end;

  trigger OnModify();
  begin
  end;

  trigger OnDelete();
  begin
  end;

  trigger OnRename();
  begin
  end;
}
```

Report: 

```
report 50000 TestReport
{
  dataset
  {
    dataitem(TestDataItem; TestTable)
    {
      UseTemporary = true;
      column(ColumnName; Field1)
      {
      }
    }
  }

  trigger OnPreReport();
  var
    TestTable : Record TestTable;
  begin
      TestTable.Reset;
      if TestTable.FindSet then begin
        repeat
          TestDataItem.Init;
          TestDataItem := TestTable;
          TestDataItem.Insert;
        until TestTable.Next = 0;
      end;
  end;
}
```

Page: 

```
page 50000 TestPage
{
  PageType = Card;
  SourceTable = TestTable;
  UsageCategory = Administration;

  layout
  {
    area(content)
    {
      group(GroupName)
      {
        field(Name;Field1)
        {
          
        }
      }
    }
  }

  actions
  {
    area(processing)
    {
      action(ActionTest)
      {
        ApplicationArea = Suite,Basic,Enhancement;
        trigger OnAction();
        var
          TestTable : Record TestTable;
        begin
          TestTable.Init;
          TestTable.Field1 := 5;
          TestTable.Insert;
          Commit();
          Report.Run(Report::TestReport);
        end;
      }
    }
  }
}
```

Expected result: can write to the temporary table

Actual result: cannot write to the temporary table. Error: 
![image](https://user-images.githubusercontent.com/32313731/34278133-3b4266cc-e666-11e7-8ae2-131aaa648984.png)

Being able to use that dataitem as a temporary table is useful in times when you want to modify the data for the report but do not want to modify that actual underlying data.

**Comment by strophanthus** [comment]
Note: this was tested on today's release.

**Comment by atoader** [comment]
Thanks for reporting this @strophanthus ! We will investigate.

**Comment by JulianTillmann** [comment]
one question, Is this going to ship with a cumulative update for NAV2018? Or just with R2?

**Comment by StanislawStempin** [comment]
This is currently only fixed in the latest codebase. We can consider backporting to NAV 2018 if this is a blocking issue for you

**Comment by JulianTillmann** [comment]
We have another issue that is unfortunately not going to get backported and so this would only be half the battle. I just wanted to know what the policy is with Fixing stuff for AL, because that process is not that transparent  to me right now.

**Comment by StanislawStempin** [comment]
Here are more details about the overall process: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018

It is not really different than other areas of the product and no different from recent releases.

In general this GitHub repository is related to the latest preview releases whereas NAV 2018 is supported through regular support channels.

**Comment by JulianTillmann** [comment]
K, thanks
