### ISSUE TITLE
XLIFF file: trans-unit/maxwidth must be in lowercase

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#1288]
I have been working a bit with the XLIFF translation files in the order to find the best and easiest CAT tool to use.

Here I have been using https://www.maxprograms.com/products/xliffchecker.html to check if the files are valid.

In the file you are creating the maxwidth attribute is written as as **maxWidth** - which is wrong. Must be with a lowercase W.

As a by-question, why did you choose the old XLIFF 1.2 format, when the XLIFF 2.0 format has been official since 2014?

**Comment by DominikDitoIvosevic** [comment]
Hi Erik. Thanks for the heads up about max width. I have also received from our internal internationalization engineers that that is not valid so I'm working on a fix. We have went with 1.2 as it is not obsolete nor being dropped from support in various tools for translation. When deciding which one to go with, we went with one that had wider adoption. I have made the code ready for supporting 2.0 as well but there needs to be a better reason to support it apart from "it's a newer format". The actual usage in our case is quite simple and I didn't see a big reason to go with 2.0.

Do you know if there are some tools or scenarios which don't support or aren't supported for Nav in 1.2 but are in 2.0?
