### ISSUE TITLE
Restarts required when changes are made in AL code

### ISSUE THREAD

**Issue by weinand** [Microsoft/AL#1289]
_From @PhilDOakley on December 22, 2017 11:4_

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#40714_

**Comment by weinand** [comment]
What do you mean by AL code?

**Comment by weinand** [comment]
_From @PhilDOakley on December 22, 2017 11:56_

VS Code extension Microsoft AL for Dynamics Nav

**Comment by PhilDOakley** [comment]
As an example. If you add this to the code there is an error that the procedure add cannot have a body.
Close VSC and open it again and the error goes away!
procedure Add(a: Integer; b: Integer; c: Integer) : Integer;
    begin
        exit (a+b+c);
    end;

**Comment by DominikDitoIvosevic** [comment]
Hi @PhilDOakley 
I'm afraid the information you have given us is not enough for us to reproduce the issue.
Could you please make a small extension which can demonstrate your problem?
