### ISSUE TITLE
Suggestion : Shortcuts for Locals and Globals

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1293]
Even after working in VS Code in like "real life" for a week I still find myself hitting CRTL+L for Locals and CRTL+G for globals.

It is also not as productive as I thought it would be to have the variables in the text.

Maybe I am not using the system correct, but I feel having CTRL+L jumping to the locals would improve my speed.

**Comment by DominikDitoIvosevic** [comment]
I totally understand your complaint as you have been working for many years in one way and now we have switched to a new development model. While we consider our new development more modern and in line with all the other mainstream languages, some scenarios could potentially be faster in a more UI centered model. As I'm working (at work) in C# 96% of the time, 3% in TypeScript and 1% in AL I must admit this is not something I have ever considered a missing feature or felt the need for it.

I'm afraid that with our current direction we will not be adding this, if any, of the UI features which were present in CSIDE. Modern mainstream programming is less UI based and more code based. Our primary concern is development of the language server and then the language clients like Vscode or Atom can utilize it per the language server protocol contract. This allows us to have more focus on the language itself and removes the burden of maintaining an IDE. As you may have noticed, further progress with CSIDE was very hard as everything was very tightly coupled and changes were very costly. 

Of course, this does not mean that visual studio code extensions could not be made by the community which were utilizing the language server to provide these functionalities. It's all about modularization and separation of concerns. This is something which we currently don't have a framework for and would take a significant effort to implement for unknown value.

I also believe after some time you will lose the reflex to use the shortcuts and notice that your development speed has not decreased. 
Most of the software engineering time consists of designing, planning, debugging and testing and the actual writing of code is only a fraction of the time.

I apologize for the long post, I'm just hoping we could clarify our priorities and as always, nothing is set in stone.

Happy Holidays,
Dominik
