### ISSUE TITLE
Event Request: Publisher Event in Codeunit 802: Online Map Management

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/AL#1297]
I've also posted it in Yammer, but no reply. Natalie Karolak suggested to put it in here.

Reason for this request is simple: Currently only a predefined number of tables are supported for Online Map.
With these 2 event publishers, we can create our own subscribers to allow for any table.

Delta attached
[CU802.DELTA.TXT](https://github.com/Microsoft/AL/files/1583353/CU802.DELTA.TXT)

**Comment by atoader** [comment]
Thank you for the request! I have forwarded this to the appropriate application team.

**Comment by AlexanderYakunin** [comment]
This is already implemented based on Yammer ask.

**Comment by ptijsma** [comment]
Hi Alexander,

I've just checked the CU1 for NAV2018 and didn't find the requested events

Can you confirm if it will appear in CU2 then?

Thanks,

**Comment by StanislawStempin** [comment]
For backporting requests to NAV 2018 please see: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by ptijsma** [comment]
Hi @StanislawStempin 

I don't understand your statement about backporting?

I've requested the event before CU1 was released and now after checking CU3, it's still not in, eventhough @atoader mentioned it was already put in based on a Yammer request (which was also mine).

If it has been built in, shouldn't I be able to find it then? and if so, where?

Thanks,

**Comment by StanislawStempin** [comment]
This GitHub repository feeds into the latest pre-release version of Business Central and so the event request is implemented in our latest codebase. 
As mentioned in the FAQ entry that I linked to before: 
"However, to get the fix backported to NAV 2018 ... you need to open a regular support case. You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company."

Please also see https://github.com/Microsoft/AL/issues/1806#issuecomment-379191564 for more details

**Comment by ptijsma** [comment]
Hi Stanislaw,

I understand now. Just pulled build 21229 and verified that all is in.
No worries, we need it for the next version anyway.

Thanks for explaining.
