### ISSUE TITLE
IncludeSender property on Event publisher function declared in table extension uses table extension as the sender and not the table it is extending.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1299]
When I create an event publisher from within a table extension and set the include sender, the system tries to include an object of type table extension as the sender when , I believe, it should in fact be including a reference to my instance of the table that my table extension is extending. I can achieve what I need by having a "by reference" variable as a parameter to my event, but it would be nice if the include sender worked properly.

**Comment by atoader** [comment]
Thank you for opening the issue! We will look into this issue.

**Comment by thpeder** [comment]
Hi @DavidRoys,
It is working today in the february update.
