### ISSUE TITLE
New event in Item Attribute Value table

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#1300]
Hello,

Could you please add publisher in GetValueInCurrentLanguage function in table Item Attribute Value? And to do EXIT (Value) instead of EXIT(''):

![image](https://user-images.githubusercontent.com/34686682/34336597-bf3c17b2-e958-11e7-8f2c-05d07145eff4.png)

This change would allow us to have additional attribute types.

Thanks,
Radovan

**Comment by atoader** [comment]
Hi! I have forwarded the request to the application team. We will get back to you as soon as possible.

**Comment by ivandjordjevic** [comment]
@atoader Do you plan to support Dates for attribute types out of the box in future release?

**Comment by atoader** [comment]
What do you mean by supporting Dates for attribute types? Could you give me an example? As far as I know, this is not on the roadmap.

**Comment by ivandjordjevic** [comment]
Adding additional option in type field for 'date' when creating an Item attribute:

![image](https://user-images.githubusercontent.com/20359384/34415052-d6a2cf18-ebec-11e7-9618-780b88d37f1c.png)
