### ISSUE TITLE
Publisher request inside FullName function for Employee Table

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#1302]
It would be great to have the ability to override how Full Name is generated within table 5200 function FullName.

Adding these two lines at the end of the function would solve it:

**OnAfterGetFullName(FullName);
EXIT(FullName);**

````
[External] FullName() : Text[100]

IF "Middle Name" = '' THEN
  FullName := "First Name" + ' ' + "Last Name";
ELSE
 FullName := "First Name" + ' ' + "Middle Name" + ' ' + "Last Name";
OnAfterGetFullName(FullName);
EXIT(FullName);
````

**Comment by atoader** [comment]
Thank you for opening this issue! The application team will look into this.
