### ISSUE TITLE
CaptionClass Property for Existing Field in table Error

### ISSUE THREAD

**Issue by Tonygithub17** [Microsoft/AL#1304]
Is it Extension support modify CaptionClass for existing field in standard table ?
I tested, if i put the CaptionClass in standard field all the label become blank.
Below is my Sample Code:
tableextension 80311 "GLAccount Extension" extends "G/L Account"
{
    fields
    {
        modify("VAT Bus. Posting Group")
        {
            CaptionClass = 'TESTING';
        } 
    }
}

**Comment by DominikDitoIvosevic** [comment]
Hi @Tonygithub17 . Are you still experiencing this issue? Which version of AL extension are you running on?

**Comment by Tonygithub17** [comment]
Example 
tableextension 50000 "Customer Extension" extends "Customer"
{
fields
{
modify("Prices Including VAT")
{
CaptionClass = 'Prices Including ABC';
}
}
}

When i run table or page i need field display at "Price Including ABC" instead of "Prices Including VAT"
Now when using captionclass in field the column name will be disappear 

![capture](https://user-images.githubusercontent.com/34825577/39106005-88a3c196-46eb-11e8-9ee3-b92adbfb44da.PNG)
