### ISSUE TITLE
Dynamics 365- Financial - Inventory Setup

### ISSUE THREAD

**Issue by stanuj** [Microsoft/AL#1305]
HI,

Subject : Dynamics 365- Financial/Navision - Inventory Setup

I need to activate "Expected Cost Posting to G/L" As TRUE for my client. But unfortunately i am not able to show this field on "Inventory Setup" as Show Column feature is not available. How to do this field Value as "TRUE"? Please suggest.

#DYNDEV365

**Comment by AlexanderYakunin** [comment]
Expected cost is not available in D365FF yet, so we cannot enable it right now

**Comment by stanuj** [comment]
In D365FF,one day configuration package was editable, so we did this through config package.
There is an another option named "Personalize", which also worked for adding hidden fields only in list page.
Now, we can close this issue.
