### ISSUE TITLE
Provide methods from System.Math 

### ISSUE THREAD

**Issue by finstx** [microsoft/AL#1306]
Methods like sine, cosine, min, max and other elementary functions as well as fields like Pi should be available in AL.

**Comment by atoader** [comment]
Thank you for the suggestion! Do you have any scenarios in mind? We are interested in knowing about the use cases you have for these.

**Comment by finstx** [comment]
I'm trying to migrate a BingMaps solution to AL. 
One feature of the solution is to calculate the bounding box around a contact (by latitude/longitude) and show other contacts in this bounding box. For calculating the bounding box I need some of the trigonometric functions and constants (http://aboutsqlserver.com/2013/09/03/optimizing-sql-server-spatial-queries-with-bounding-box/ fig. 11).

**Comment by GaryFrostick** [comment]
I agree with this. I have come across the need for functions in the Maths library when trying to calculate material requirements for specific manufacturing processes.

**Comment by SirBETE** [comment]
Any update on this?
A NumberManagement Codeunit (like COD41 TextManagement) with mathematical functions would be very useful.
The first 2 functions can already be moved from COD5780 "Whse. Cross-Dock Management" Maximum and Minimum.

**Comment by ThomasBrodkorb** [comment]
Well, I would say MAX and MIN should be implemented as global functions rather than in a CU.
If implementing in a CU, I need to declare a variable of type codeunit to use it.

**Comment by kevindstanley1988** [comment]
I have a requirement for old functionality in our ISV I am bringing forward to allow user entered formulas be parsed and it allows a user to enter almost every function inside of the System.Math library.  We need these function exposed if possible Abs, Ceiling, Exp, Floor, IEEERemainder, Min, Max, Sqrt, Truncate, Pow. 

I think that this functionality would make most sense as a codeunit. Just like System.Math is a library, a codeunit is the AL equivalent. If we cannot get System.Math features we lose a core feature in our software.
