### ISSUE TITLE
MemoryStream wrapper - function visbility

### ISSUE THREAD

**Issue by mrabus** [Microsoft/AL#1308]
Hello Dev Team,

I was trying to migrate some code from C/AL to new AL language, but unfortunately my old code uses .NET class MemoryStream. 

So I tried to use the new wrapper codeunit 704. But when I try that, i have some issues:
![grafik](https://user-images.githubusercontent.com/2485163/34395273-3a815b3c-eb5f-11e7-85a0-97237c03cf59.png)

![grafik](https://user-images.githubusercontent.com/2485163/34395302-6c49657e-eb5f-11e7-943c-15bb98d9984a.png)

Well, I checked the codeunit and none of the functions have FunctionVisiblity = External. I am using the latest (german) developer preview. Is there a way around that or can you please make the functions accessible for extension development?

Thanks and keep on the good work, guys!

**Comment by DominikDitoIvosevic** [comment]
You can temporarily put in your app.json `target:internal` so that you can still use the method until we make the scenario available for extensions

**Comment by atoader** [comment]
Hi @mrabus ! Could you please reopen the issue on the https://github.com/Microsoft/cal-open-library . I think that is the best place to discuss this type of issues.

**Comment by mrabus** [comment]
Hi you two,

I moved the issue to the cal open library, so I will close this one. 

@DominikDitoIvosevic: thanks for the workaround, that helps me proceeding. Do you know a timeframe when these methods will be available for extension development? Is it sure they will be in the near future?
