### ISSUE TITLE
syntax for keys

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#131]
Can You please provide documentation and/or examples for the correct syntax for typical keys, including SumIndexFields and other options. Many thanks!

**Comment by esbenk** [comment]
Here is an example

```
table 71000018 MyTable 
{
    fields
    {
        field(1;Id;Code[10]) {}
        field(2;Amount;Decimal) {}
        field(3;"Amount (LCY)";Decimal) {}
    }
    Keys
    {
        Key(1;KeyName;Id,Amount){
            Clustered = true;
            SumIndexFields = Amount, "Amount (LCY)";
        }                    
    }               
} 
```

**Comment by RafaelKoch** [comment]
Thanks for helping!

**Comment by hgnamvn** [comment]
Please help me.
I'm a new developer for Extension 2.0.
Example: 1. Add more file Offset Type into Table 17 G/L Entry. -> It is OK.
               2. I need add more key:
 keys
{
    key(Key9;"Transaction No.","Document No.","Offset Type")
    {
    }
}
But It isn't OK.
So how to do it. OR this isn't supported.
From [the help link](https://msdn.microsoft.com/en-us/dynamics-nav/extension-packages-capability-support-matrix). "You can add table keys, but you cannot delete or modify existing keys".
