### ISSUE TITLE
Event request: on after install extension

### ISSUE THREAD

**Issue by kvaldik** [microsoft/AL#1310]
In V1 we used to subscribe to the 'OnAfterActionEvent', 'Install' on Page 2501 to post a message to the user to setup LS Express right after he has installed it. This is no longer possible in V2 since the NAV App table is blocked for extension development as discussed in other issues. We have tried adding messages to the install code but those do not get displayed. 

Are there any plans on exposing the NAV App table for extensions? Is it possible to have an event raised when an extension is install and have the parameters of that event contain the GUID of the app that was installed, instead of the NAV App record? That would allow us to display our message without relying on the NAV App table.

We consider this to be a must have since we don't wan't to leave users hanging once they have installed our app but instead guide them through setting up and using our app.

**Comment by atoader** [comment]
@HunterFeltman-MSFT @AlexanderYakunin is there any event that you know of that could be used in this scenario?

**Comment by HunterFeltman-MSFT** [comment]
There are no plans currently for exposing the NAV App table to extensions.
To my knowledge, there is no such event to produce equivalent behavior in the base application. 
This type of scenario is, however, a backlog item that we have to allow developers to hook into some UI elements immediately following installation.

Adding an event such as you've outlined in the base application might be a workable temporary solution.

**Comment by pborring** [comment]
Hi,

This is a rather old suggestion, and our GitHub only tracks bugs to AL Language and VSC VSIX.

If still a large need, then please go ahead and post this to our Ideas forum at https://aka.ms/bcideas, or vote up the idea if its already there. 

Thanks
