### ISSUE TITLE
How to disable FunctionVisibility consideration

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#1311]
I would like to be able to use all Functions from the BaseApp regardless of the Scope (internal/external).

Is there a setting to allow this?

**Comment by mrabus** [comment]
Yes, there is. In your app.json you can do the following:

![grafik](https://user-images.githubusercontent.com/2485163/34409889-fb50dd0c-ebcc-11e7-8954-0fef359b9d07.png)

The target can be set to Personalization, Extension, Solution and Internal.

**Comment by janhofmann24** [comment]
Thanks! :)
