### ISSUE TITLE
Problem Object Table

### ISSUE THREAD

**Issue by geraldbeaulieu877** [Microsoft/AL#1313]
I have an issue to assign the value of virtual Table 200000001 Object table Column "Version List", (should be a Text[248] length to a Text. 

the message look a mistake conversion;

Microsoft Dynamics NAV
---------------------------

The definition of the Version List field has changed; old type: Text, new type: OemText. Start your activity again.
---------------------------
OK
---------------------------

codeunit 50205 MyCodeunitTest
{
    trigger OnRun();
    begin
        if rObject.get(rObject.Type::Table, '', 27) then
            TxtValue := rObject."Version List";            
    end;    
    var
        rObject : Record Object;
        TxtValue : Text[248];
}

![nav error](https://user-images.githubusercontent.com/24991246/34414310-9b7a115c-ebb6-11e7-9992-15c6a412dde6.png)

**Comment by mortenbraemer** [comment]
Same problem with Company Name, Name, Version List and Locked By all of type OemText

![object](https://user-images.githubusercontent.com/688204/34556462-a74a42a6-f136-11e7-873f-f45dd703ff2b.PNG)

**Comment by atoader** [comment]
Thanks! I will try to fix it today.
