### ISSUE TITLE
Suggestion: Handle comments per function

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#132]
IntelliSense for functions could be more efficient if we had a way to insert comments for that function that are then shown directtly in the IntelliSense output. This is something from the .NET-world that is quite useful.

**Comment by esbenk** [comment]
This is something that we have in the plans for the future, but we are currently working on areas with higher priority. Just be patient:-)

**Comment by RafaelKoch** [comment]
Thanks, I will :-)

**Comment by tfenster** [comment]
It would also be nice to have something like the ObsoleteState and ObsoleteReason property introduced lately for table fields in C/AL also as maybe an annotation for any object, field or function in AL. That way we could find out if something in standard NAV or an extension we depend on is to be removed

**Comment by esbenk** [comment]
ObsoleteState and ObsoleteReason will be surfaced for tables, fields, and keys in AL soon. We are planning to expand this to cover more functionality in the future.

**Comment by anzwdev** [comment]
Are you going to use the same xml comments format that we can use with c#? I've managed to add partial support for xml comments and code snippets to the current Nav Development Environment, so I can imagine that we could use the same DocFX template for old C/AL and new AL in the future and use 2 different tools to generate metadata from source code. Both development environments are going to exists together for some period of time, so it would be nice if my extension uses the same xml comments format that you will implement in VS Code and it would also be nice if txt2al could remove these comment from the begining of procedure body and put them back at the top of procedure header. Obviously you have plenty of other, much more important tasks and issues to solve, so this one has very low priority, but AL code is going to be much more "closed" in the future, so it would be good if we start thinking about better documentation for developers. 
I am going to publish results of my experiments with DocFX templates and plugins on github, so anybody interested can take a look at it

![documentation](https://user-images.githubusercontent.com/24944969/31568563-f037a4aa-b06c-11e7-962b-8f31df750ae1.gif)

**Comment by naradae** [comment]
This will be an essential feature

**Comment by StefanMaron** [comment]
Are there any news on this topic by now?

**Comment by esbenk** [comment]
No. It is still in our plans but we don't have a timeline for it.

**Comment by JavierFuentes** [comment]
Hi @esbenk, 
particularly, I would prefer a documentation syntax that is much more modern and less verbose than that based on XML ... something like this:

![image](https://user-images.githubusercontent.com/5801847/51083324-87697480-1718-11e9-8e12-9bf94aba115d.png)

To be used here:

![image](https://user-images.githubusercontent.com/5801847/51083251-22614f00-1717-11e9-9353-6d60a663b1a1.png)

... and here, because is more useful info about the remote parameter than about the local variable we are using:

![image](https://user-images.githubusercontent.com/5801847/51083253-31e09800-1717-11e9-9600-78fbe5f601a4.png)

**Comment by esbenk** [comment]
It is something like this that we are planning to implement.

**Comment by dtkb** [comment]
This has landed already, right? So it can be closed I'd think.

BC17 Launch Event video, which starts on this at around 45 minutes in:
https://events1.social27.com/MSDyn365BCLaunchEvent/agenda/player/61355

example doc comments:
![image](https://user-images.githubusercontent.com/63455896/97015908-07ef1300-1544-11eb-917f-153c23f6500c.png)

example Intellisense result:
![image](https://user-images.githubusercontent.com/63455896/97016009-20f7c400-1544-11eb-95a1-03b31ef7d533.png)
