### ISSUE TITLE
EventRequest - OnBeforePrintReport

### ISSUE THREAD

**Issue by Rotsch58** [Microsoft/AL#1323]
It should be possible to replace any report with a customized on

**Comment by AlexanderYakunin** [comment]
Please be more specific and provide details.

**Comment by Rotsch58** [comment]
Ok, I'll try to explain. 
Example:
On Page 5050 is it possible to print the standard report 5055 (Contact - Cover Sheet). Some customers would to print their own report for example with number 50'000. 

Report 5055 is hard coded on page 5050 like this:
REPORT.RUN(REPORT::"Contact - Cover Sheet",TRUE,FALSE,Cont);

What i want is a possibility to exchange report 5055 with my own report 50'000. If I have an event 'OnBeforePrintReport' or some similar to that, I would be able to print any reports that I want instead the standard one.

**Comment by Gallimathias** [comment]
I think In this case it would be better to take out the hardcoded report and use table 77 by default. In order to get more beautiful code as well as the fact that the original code cannot be changed, hard wired calls of reports should be solved completely.

**Comment by Rotsch58** [comment]
OK, I agree with you. That's the better way if it's possible that this would be changed in NAV

**Comment by StanislawStempin** [comment]
I got this information from Alexander:
New event 
 
LOCAL [IntegrationEvent] OnBeforePrintContactCoverSheet
(VAR ContactCoverSheetReportID : Integer)

implemented in Contact Cover Sheet trigger like this
 
ContactCoverSheet - OnAction()
Cont := Rec;
Cont.SETRECFILTER;
ContactCoverSheetReportID := REPORT::"Contact Cover Sheet";
OnBeforePrintContactCoverSheet(ContactCoverSheetReportID);
REPORT.RUN
(ContactCoverSheetReportID,TRUE,FALSE,Cont);
