### ISSUE TITLE
Command=generatesymbolreference

### ISSUE THREAD

**Issue by mortenbraemer** [Microsoft/AL#1325]
Please add support of using filters when generating symbolreference with finsql.exe

finsql.exe Command=generatesymbolreference, **filter="Type=Codeunit;ID=50000"**

Sometimes developers forget to start finsql.exe with generatesymbolreference=yes 

Check if Symbol Reference HASVALUE:
![symbolref](https://user-images.githubusercontent.com/688204/34486677-2edd5332-efd1-11e7-95da-f356b8f90d34.PNG)

**Comment by DominikDitoIvosevic** [comment]
Hi @mortenbraemer . Could you please clarify why you need filtering for generating symbol reference?
Also, I did not understand what you meant with the "Check if Symbol Reference HASVALUE". What are you suggesting we use this for?

**Comment by mortenbraemer** [comment]
Normally it takes full compilation time to generate all symbols – ill just speed up the process. If I only were mission symbols for a specific range of objects, the filter feature would be nice to have.

Note after the Command=generatesymbolreference finsql.exe will run forever. You have to kill the process yourself.

More the Command Prompt have to be started in elevated mode else the symbols will not be generated?

With "Symbol Reference".HASVALUE I can check if the symbols are ready for the specific object.

**Comment by kalberes** [comment]
The command runs approximately a  full compilation time. Filter support seems to be broken. That is a bug.

**Comment by kalberes** [comment]
Actually filters do work but the filter sting is a bit different here since the table in charge is the object metadata. This works for example: Filter=Object Type=table;Object Id=18

**Comment by richardrobberse** [comment]
@mortenbraemer 
Filters indeed work but if you apply filters it will only generate symbols for those objects and when you download the symbols in VS Code you'll only get the symbols for the objects within your filter.
Ideally it would (re)generate the symbols for the objects within your filter and apply it to the complete package.

**Comment by mortenbraemer** [comment]
@richardrobberse 
Ill just wait for the full compile - the filter will destroy the project.
