### ISSUE TITLE
Access to "Page Table Field" table

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1329]
Could you allow access to "Page Table Field" table from extensions?

**Comment by StanislawStempin** [comment]
Page Table Field is an internal system table used by the In-Client Designer and not meant to be exposed in code.

**Comment by anzwdev** [comment]
We have a generic reporting solution that can be invoked from any page and instead of showing users empty page when they select "new report" we would like to suggest the same list of fields that is visible to them. "Page Table Field" seems to be perfect to implement that functionality. Is there any other way to get information which fields are visible to the user on a page?

**Comment by StanislawStempin** [comment]
Ok, we are aware of this scenario and looking into it as part of #912. Let's continue the discussion there.
