### ISSUE TITLE
Question: how do we manage visibility of controls on a page

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#133]
Probably just a question because we could not figure out the way to do it: how do we implement the visibility of controls on pages with a boolean variable? Can You please provide documentation and/or an example? Many thanks!

**Comment by atoader** [comment]
To control the visibility of controls on pages with a boolean variable you assign the variable to the Visibility property of the control.
In the example below, I have created the page VisibleControlTest with a single control whose visibility is controlled by setting the isVisible boolean variable. The MyExtension page extension was added as helper code to run the page.

```CSharp
pageextension 70654555 MyExtension extends "Customer List"
{

layout { }
 
actions
{
    addafter("&Customer"){
        action("Run My Tenant Page")
        {
        Promoted=true;
        PromotedCategory=New;
        
        trigger OnAction();
        begin
            Page.Run(70050001);
        end;
        }
    }
}
}

page 70050001 VisibleControlTest
{    
    layout
    {
        area(Content)
        {
            field(Hello;'HelloWorld')
            {
                Visible=isVisible;
            }
        }
    }

    trigger OnOpenPage();
    begin
        isVisible:=true;
    end;
var
    isVisible : Boolean;
}
```

**Comment by RafaelKoch** [comment]
Thanks for helping!

**Comment by atoader** [comment]
You're welcome! Do not forget to add the InDataSet attribute to the variable declaration. The behavior should be identical with C/SIDE.

**Comment by sanjeevasawale** [comment]
@atoader, Why InDataSet attribute is used while defining Variables?
