### ISSUE TITLE
Invoking default drill down and lookup pages on FieldRef from code

### ISSUE THREAD

**Issue by anzwdev** [microsoft/AL#1330]
You mentioned in issue [912](https://github.com/Microsoft/AL/issues/912) that you prefer to provide API for each scenario instead of giving us access to "Object Metadata" page. 
We are currently parsing table metadata xml from "Object Metadata" to get information about relations and flow field definitions to show drill down and lookup pages for recordref fields. 
Could you add ShowLookUp and ShowDrillDown functions to FieldRef?

**Comment by pborring** [comment]
This is a 5 1/2 yrs old suggestion for object metadata. If not already supported or worked around, consider adding an entry on https://aka.ms/bcideas, as this GitHub only tracks bugs in AL Language or VSC VSIX
