### ISSUE TITLE
Question: Caption vs CaptionML

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1335]
Could you explain to me what the use of the Caption property is in AL?

[Caption](https://docs.microsoft.com/en-us/dynamics-nav/caption-property) always has been a kind of virtual property displaying the CaptionML value for the active language. This was laso reflected in the .txt export of any object with captions: the CaptionML properties were only to be found and not the Caption properties.

So to me the Caption property in AL has become obsolete. But maybe I am wrong.

Thanx in advance for the elaboration.

BTW: today converting my C/AL code to AL I noticed that Caption property was set and not CaptionML in AL objects.

**Comment by lvanvugt** [comment]
OK, just now I stumbled over the issue https://github.com/Microsoft/AL/issues/1200 which actually explains it all.

**Comment by DominikDitoIvosevic** [comment]
Yep. Closing as duplicate of #1200
