### ISSUE TITLE
Group controls in pages force the name to be displayed

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1337]
Groups in pages are sometimes used for grouping where text is not required or wanted. 

In NAV this can be achieved by simply not naming the groups. 
```
OBJECT Page 50000 Test Page
{
  OBJECT-PROPERTIES
  {
    Date=01/03/18;
    Time=[ 1:21:03 PM];
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    OnInit=BEGIN
             TestText := 'Hello';
           END;

  }
  CONTROLS
  {
    { 1000000000;;Container;
                Name=Test Groups;
                ContainerType=ContentArea }

    { 1000000001;1;Group  ;
                GroupType=Group }

    { 1000000002;2;Field  ;
                Name=Display Text;
                SourceExpr=TestText }

  }
  CODE
  {
    VAR
      TestText@1000000000 : Text;

    BEGIN
    END.
  }
}
```

Results in the desired output

![image](https://user-images.githubusercontent.com/32313731/34539040-35bd16ae-f08c-11e7-9fdd-6ee6740ad428.png)

After running through exporttonewsyntax and the txt2al tool, you get 
```
page 50000 "Test Page"
{

    layout
    {
        area(content)
        {
            group(Control1000000001)
            {
                field("Display Text";TestText)
                {
                }
            }
        }
    }

    actions
    {
    }

    trigger OnInit();
    begin
        TestText := 'Hello';
    end;

    var
        TestText : Text;
}
```

which does not result in the desired output
![image](https://user-images.githubusercontent.com/32313731/34539102-78bbc914-f08c-11e7-93a2-3fa30083556a.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @strophanthus . We have fixed an issue with generating and converting delta files and now this scenario will work. You need to generate the page delta files with the flag -ExportToNewSyntax as well.
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-generating-delta-files

This has been backported for CU1 as well

**Comment by StanislawStempin** [comment]
Names for groups are mandatory in AL. Therefore we have introduced a new property ShowCaption=false to be used in cases like this one.

**Comment by strophanthus** [comment]
@DominikDitoIvosevic With our product range we are only exporting. Should we also be generating deltas for our product range? 875 seems to be a different issue. We're using a later build and have not had issues with positioning.  

@StanislawStempin is this new property going to be included in CSIDE, or applied during export/AL conversion? Or is this something that will require manual editing after conversion?

**Comment by DominikDitoIvosevic** [comment]
@strophanthus my bad, I misunderstood. I'm afraid we wont be backporting the property to CSIDE. I will look into the txt2al feature. 

Is it so that every time the group doesn't have a name that you don't want the caption shown or there are specific cases?

**Comment by strophanthus** [comment]
> Is it so that every time the group doesn't have a name that you don't want the caption shown

Yup, that's it exactly, although it is just the standard export that leaves them without a name. ExportToNewSyntax appears to have added the name before it gets to txt2al

```
{ 1000000012;1;Group  ;
                Name=Control1000000012 }
```
