### ISSUE TITLE
Event and Refactoring Request for codeunit 333 Req. Wksh.-Make Order

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/AL#1339]
In codeuint 333, we extend the "make order process" by considering custom fields today like this:

**Function Code**
![001](https://user-images.githubusercontent.com/34504100/34555033-a6955cce-f127-11e7-89de-7803c55ca787.JPG)

**Function InsertPurchOrderLine** (wich event and refactoring suggestion)
![001](https://user-images.githubusercontent.com/34504100/34555312-f490a540-f128-11e7-8c3c-8e61c2344a07.JPG)

**Function FinalizeOrderHeader**
```
[...] 
ReqLine2.SETRANGE("Purchasing Code",PrevPurchCode);
  ReqLine2.SETFILTER("Line No.",'..%1',ReqLine."Line No.");
  // >> INSERT
  ReqLine2.SETFILTER("My Custom FIeld",'%1|%2','', PurchOrderHeader."No.");
  // << INSERT

  IF ReqLine2.FIND('-') THEN BEGIN
[...]
```

**Function CheckInsertFinalizePurchaseOrderHeader**
```
[...]
    (PrevPurchCode <> "Purchasing Code") OR
    (PrevLocationCode <> "Location Code") OR
    // >> INSERT
    ((PurchOrderHeader."No." <> "My Custom Field") AND ("My Custom FIeld" <> '')) OR
    // << INSERT
    CheckAddressDetails("Sales Order No.","Sales Order Line No.",UpdateAddressDetails);
[...]
```

As you can see, all those places can technically be replaced with events, BUT in function **Code**, in case of multiple subscribers (fields), there must be a way to create a SETCURRENTKEY that combines ALL added fields.
Any other ideas how to solve that?

**Comment by AlexanderYakunin** [comment]
Do you need extra fields in SETCURRENTKEY for particular sorting? Or there is another reason for extending key?

**Comment by NKarolak** [comment]
Yes, we need to extend SETCURRENTKEY because the sorting must include our own field(s) at the end, else the additional check in CheckInsertFinalizePurchaseOrderHeader (called by Code --> CarryOutReqLineAction) would not return the correct boolean value. (We want to create additional new headers in case our custom field changes its value.)

**Comment by AlexanderYakunin** [comment]
I see no simple solution for altering current key (or changing sorting order). The only idea is to have temporary table which can store sorting order for records you would like to process but this is large redesign which is not realistically possible for W1 solution.  Please let me know if there are still need to implement events in this codeunit or close this one.

**Comment by NKarolak** [comment]
OK, if there is no other technical possibility, please add an event that enables us at least to set or rather replace SETCURRENTKEY. When different add-ons are provided by partner, we can solve that at least internally. Hopefully ;-)

I checked my colleagues' changes for codeunit 333. I found indeed more to add. This is only part 1, next will follow soon:

**Function CarryOutBatchAction**
```
ReqLine.COPY(ReqLine2);
ReqLine.SETRANGE("Accept Action Message",TRUE);
// >> INSERT
ReqLine.SETRANGE("Custom Field",CustomValue);
// << INSERT
Code(ReqLine);
ReqLine2 := ReqLine;
```

**Function Code (end)**
```
[...]
 ReqLine3.SETRANGE("Worksheet Template Name","Worksheet Template Name");
      ReqLine3.SETRANGE("Journal Batch Name","Journal Batch Name");
      IF NOT ReqLine3.FINDLAST THEN
        IF INCSTR("Journal Batch Name") <> '' THEN BEGIN
          ReqWkshName.GET("Worksheet Template Name","Journal Batch Name");
          // >> INSERT
          CreateNewName := TRUE;
          OnCheckNewNameNeccessary(ReqWkshName,VAR CreateNewName);
          IF CreateNewName THEN BEGIN
          // << INSERT
            ReqWkshName.DELETE;
            ReqWkshName.Name := INCSTR("Journal Batch Name");
            IF ReqWkshName.INSERT THEN;
            "Journal Batch Name" := ReqWkshName.Name;
          // >> INSERT
          END;
          // << INSERT
        END;
[...]
```

**Function CheckReqWkshLine**
```
[...]
    END ELSE
        IF "Replenishment System" = "Replenishment System"::Transfer THEN BEGIN
          TESTFIELD("Location Code");
          IF "Planning Line Origin" = "Planning Line Origin"::"Order Planning" THEN
            TESTFIELD("Supply From");
          TESTFIELD("Transfer-from Code");
        // >> INSERT
        END ELSE BEGIN
          OnCheckFurtherReplenishmentSystems(ReqLine2);
        // << INSERT
        END;
[...]
```
Better would to turn that section into a CASE statement and add the event there.

**Function CarryOutReqLineAction**
At the very beginning:
```
// >> INSERT
OnBeforeCarryOutReqLineAction(ReqLine,Failed); // GlobVarAccess = Yes!
IF Failed THEN BEGIN
  SetFailedReqLine(ReqLine);
  EXIT;
END;
// << INSERT
[...]
```
At the very end, change the existing publisher:
```
[...]
// >> UPDATE
OnAfterCarryOutReqLineAction(ReqLine,PurchOrderHeader,VAR OrderCounter);
// << UPDATE
```

**Comment by NKarolak** [comment]
Part 2 (last one):

**Function InsertPurchOrderLine**
```
[...]
// >> UPDATE
OnBeforePurchOrderLineInsert(PurchOrderHeader,PurchOrderLine,ReqLine2);
// << UPDATE

PurchOrderLine.INSERT;

// >> INSERT
OnAfterPurchOrderLineInsert(VAR PurchOrderLine,ReqLine2); // we need to call a custom function within PurchOrderLine
// << INSERT
[...]
```

**Function InsertHeader**
```
[...]
// >> INSERT
OnBeforeInsertPurchOrderHeader(VAR PurchOrderHeader);
// << INSERT

PurchOrderHeader.INSERT(TRUE);
[...]

```
