### ISSUE TITLE
Personalisation or dynamic visibility of parts on role centers

### ISSUE THREAD

**Issue by anzwdev** [microsoft/AL#1340]
We are adding multiple new parts to standard role centers, most of these parts is empty by default and we would like to keep them hidden until users decide what they want to display on them. We are using our own personalisation in V1 extension, but it is not possible to move it to AL. The best option would be to decide from code if these parts should be visible or hidden, but unfortunately it is not possible to have any triggers (i.e. OnOpenPage) on role centers. New web client personalisation is also not the best solution as it only allows users to hide UI parts and once they hide something it is no longer displayed and the only way to have It back is to reset whole personalisation.

**Comment by pborring** [comment]
This is a rather old suggestion, I assume a solution was found inbetween, but if not, consider adding or voting on an existing entry on https://aka.ms/bcideas, as this GitHub only tracks bugs in AL Language and VSIX and not new functionality. Thanks.
