### ISSUE TITLE
Full stream based zip file support

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1341]
We are using zip files to import multiple images and in our data migration imports and exports but there is no zip stream support in nav so we cannot move this functionality to AL. We need a codeunit that would allow us to:
- upload zip file to the server, 
- get list of files from zip 
- get instream of a selected file from zip to be able to extract it
- create new inmemory zip
- add new file to the zip and return OutStream of that file
- download zip from the server

**Comment by StanislawStempin** [comment]
Can you check if changes made as part of #829 are sufficient for your case?

**Comment by anzwdev** [comment]
Yes, I've checked it, it adds AddStreamToZipStream() function but we also need something like GetListOfFilesFromZipStream() and GetStreamFromZipStream()

**Comment by JesperSchulz** [comment]
At any time, you are more that welcome to add missing library functions to https://github.com/Microsoft/cal-open-library. By doing so, you ensure that the functions meet your exact requirements and that your issue is picked up as fast as possible.

**Comment by anzwdev** [comment]
Thank you @JesperSchulz, we will add our functions to cal-open-library.

**Comment by anzwdev** [comment]
I've created cal-open-library pull request here: https://github.com/Microsoft/cal-open-library/pull/53
