### ISSUE TITLE
Crash on CLEAR(Query)

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#1345]
I have a query that I want to use twice in a function which different filters to calculate different values. I'm using CLEAR(Query) to clear the state of the variable before using the second time. Executing this line seems to crash the client.

Query.SETRANGE(...);
Query.SETRANGE(...);
Query.OPEN;
if Query.READ then....

CLEAR(Query); // <-- crash

Query.SETRANGE(...)
Query.OPEN;
if Query.READ then...

I've worked around this for now by creating a second variable and using that for the second calculation.

**Comment by thpeder** [comment]
It is fixed together with #974
