### ISSUE TITLE
VS Code performance

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#135]
When we work on a Project for hours at a time it Looks like some aspects of VS Code have their Performance degraded: the checking of our Code lags minutes behind typing in the end. Once we restart VS Code and continue workin g on the same Project Performance is back to normal and then slowly starts to degrade again.

**Comment by esbenk** [comment]
We are happy to hear that you already work for hours with the new tooling:-). 
We will investigate this. Based on the symptoms it sounds like a memory leak. 

Can you check the memory consumption of Microsoft.Dynamics.Nav.EditorServices.Host.exe (the AL backend) and Code.exe (VsCode) if/when it happens again?

**Comment by RafaelKoch** [comment]
Will do - might take a while though. The guy who does the actual work will be on holiday next week :-). I will try to find the time myself but I cannot promise.

**Comment by esbenk** [comment]
No problem. It will also be a quiet next week in our team.

**Comment by RafaelKoch** [comment]
Just gave it a very quick test with one Project Folder. Scrolling the Code as well as switching back and forth between files increases memory consumption of **Microsoft.Dynamics.Nav.EditorServices.Host.exe **. I managed to grab some additional MB of memory in 1 Minute just by changing between 2 active the files numerous times.
Most of the memory seems to be freed up when I close these files again. But when I leave them open the memory used up remains unchanged - at least for like 10min now.
Next thing I will do: leave it untouched, see what it consumes after I grabbed a coffee.

**Comment by RafaelKoch** [comment]
No change as long as I do not touch anything. BUT writing a simple line of Code using some IntelliSense takes even more memory. Another 35MB gone for changing between two files, adding one line of setcurrentkey and deleting it.

**Comment by RafaelKoch** [comment]
Another thing to mention: there is occasionally a considerable delay when scrolling and sometimes even when typing. This makes the editor feel cumbersome and unresponsive. 
I checked for obvious stuff, but no Windows updates running, CPU <20% and at least 2GB memory unused at that time.

**Comment by RafaelKoch** [comment]
What sort of Input do You Need?

**Comment by StanislawStempin** [comment]
Sorry, wrong label - we are looking into this bug

**Comment by StanislawStempin** [comment]
We found and fixed what we believe to be root cause of this issue. The fix will be available in May Update.
