### ISSUE TITLE
[Event Request] More Events in Codeunit 12

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1352]
Additional events are required in CodeUnit 12. These should have the following form:

The line in front of the respective event contains the comment "Event".

Function PostCust

![event3](https://user-images.githubusercontent.com/22373356/35145007-8e5a9850-fd06-11e7-9d43-061aa7cae32d.GIF)

Function PostVend

![event4](https://user-images.githubusercontent.com/22373356/35145023-939a9eb4-fd06-11e7-9c11-49a16e04658e.GIF)

Function CalcPmtTolerance
The following two new events should be implemented here.

![event5](https://user-images.githubusercontent.com/22373356/34609532-7acbefa8-f21d-11e7-94d2-f06c6f94663f.GIF)
![event6](https://user-images.githubusercontent.com/22373356/34609540-7f606e72-f21d-11e7-9063-cccfd63bbbf7.GIF)

Function CalcPmtDisc

Attention, here are 4 events to add.
The events should offer the possibility to read and change the calculated values. This is required under certain conditions.

![event7](https://user-images.githubusercontent.com/22373356/34609736-2bd6ff04-f21e-11e7-8771-c2a4f546ae97.GIF)

![event8](https://user-images.githubusercontent.com/22373356/34609759-44bf8194-f21e-11e7-825c-b5ea208d3327.GIF)

Function CalcPmtDiscTolerance

![event9](https://user-images.githubusercontent.com/22373356/34609824-88060928-f21e-11e7-82b6-136153d14fab.GIF)

![event10](https://user-images.githubusercontent.com/22373356/34609868-c1bfd874-f21e-11e7-9072-7716acbe1052.GIF)

Function CalcApplication

![event11](https://user-images.githubusercontent.com/22373356/34610050-9e86a576-f21f-11e7-9fa3-e023694c6ff4.GIF)

![event12](https://user-images.githubusercontent.com/22373356/34610089-c0f3e0a6-f21f-11e7-8514-5eb4b18e4991.GIF)

Function PostApply

![event13](https://user-images.githubusercontent.com/22373356/34610189-49e98d5c-f220-11e7-89be-41737fc565c4.GIF)

Function UpdateCustLedgEntry

![event14](https://user-images.githubusercontent.com/22373356/34610279-babceb64-f220-11e7-91ea-d351420ca502.GIF)

Function UpdateVendLedgEntry

![event15](https://user-images.githubusercontent.com/22373356/34610361-1458ecd6-f221-11e7-9575-45632ac164d8.GIF)

![event16](https://user-images.githubusercontent.com/22373356/34610363-16ab3836-f221-11e7-827c-116909e21585.GIF)

**Comment by NKarolak** [comment]
IMHO, the first two mentioned events should be added in function InitCustLedgEntry and InitVendLedgEntry instead, as OnAfterInitCustLedgEntry and OnAfterInitCustLedgEntry .

**Comment by FSharpCSharp** [comment]
@NKarolak 
That is of course true. It should be important to note that the "Gen. Journal Line" table is accessible.

**Comment by FSharpCSharp** [comment]
What about this event request now? It's been standing here for a while now, and wasn't even marked as an "event request". Was it overlooked?
