### ISSUE TITLE
XML Wrappers incompatible with Codeunit 6224

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#1353]
We have a lot of Code utilizing the different functions in Codeunit 6224 - XML DOM Management.
Trying to put this Code into an Extension, we are facing the problem, that
- XML Wrappers do not work in C/AL
- XML dotnet does not work in AL
- XML Wrappers and XML dotnet are not compatible/interchangeable

Is there a chance that either the XML wrappers would be made castable into XML dotnet types or that the XML Wrappers would be also be available in C/AL and CU6224 changed accordingly?

What would otherwise be the best approach?
Have a base layer with an extension version of CU6224 using the wrappers?

**Comment by esbenk** [comment]
We don't plan to backport the wrappers into C/SIDE, but .net interop will soon be available for on-prem development with V2. 

I think the answer depends and what you are trying to achieve. Are you trying to share source-code between C/SIDE code for on-prem installations or are you just lacking CU6224 functionality for extension V2 development? Or a different scenario?

**Comment by janhofmann24** [comment]
I am not trying to achieve source-code sharing between C/SIDE and AL, but rather trying to transform existing Code to AL without having to re-develop the whole XML logic. 

From my point of view it seems like having an AL "XML DOM Management" Codeunit would be the easiest at the moment.

**Comment by esbenk** [comment]
If you can encapsulate your xml usage in a codeunit an leave it in C/SIDE (hybrid development) for now, it seems like the easiest solution. Then you can move that codeunit to AL later.
