### ISSUE TITLE
AL extension error on Mac OS High sierra 

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#1354]
When i install AL extension from VS Code marketplace on Mac OS High Sierra , and create new project AL:Go i see next error
Launching server using command /Users/dkatson/.vscode/extensions/ms-dynamics-smb.al-0.11.14434/bin/Microsoft.Dynamics.Nav.EditorServices.Host failed.

**Comment by dkatson** [comment]
![image](https://user-images.githubusercontent.com/29101017/34643213-717336b8-f331-11e7-9223-e116f703f4f8.png)

**Comment by esbenk** [comment]
We haven't released the Mac version yet. Currently it is Windows only. We still have some smaller issues with the MacOS version.

**Comment by andupopescu** [comment]
Any ETA for the MAC version?

**Comment by esbenk** [comment]
It is not forgotten. Hopefully soon.

We still have some minor issues on MacOS.
