### ISSUE TITLE
Question: XLIFF file: Lifecycle Services

### ISSUE THREAD

**Issue by Kraver88** [Microsoft/AL#1356]
I have tried the Lifecycle Services from Microsoft to translate my xlf files that are generated from Visual Studio Code.
I used the following guide: https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/use-translation-service#xliff-tm
However I can't seem to upload a valid file. I tried both Microsoft Dynamics 365 for Finance and Operations and Dynamics Nav 2017 (2018 not available in drop down).

Is this service not available yet for our developments? Will it be available in the future?

**Comment by StanislawStempin** [comment]
XLIFF for NAV is not supported in LCS yet but it will be in the near future. We don't have an exact timeline to share yet.

**Comment by StanislawStempin** [comment]
LCS now supports the XLIFF format for NAV translations:
https://blogs.msdn.microsoft.com/lcs/2018/01/30/lcs-january-2018-release-2-release-notes/
