### ISSUE TITLE
View/research Code

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#136]
This is a question that has maybe been asked before. 
When we develop using VS Code we feel that we will need a meaningful way to research the objects we are programming/building against. Right now we can fall back to the old development environment (at least for Standard Code) to review them. We do this to either find an idea where to attach to, what to subscribe to, etc. And of Course we copy&paste like crazy. 
How will this be handled eventually? Can You also please expand this question to Extensions that we might want to build on without having the source code?

**Comment by esbenk** [comment]
Discoverability of extensions point in the base-app is clearly an issue. In C/SIDE you could just open the object and look at the source code. Of course the truth is in the code, but it is still a steep learning curve to understand the base app even with the source available.

We are investigating different options to improve in this area. For now it is not "cheating" to look in C/SIDE, but it is still the best way to understand the app.

For extensions that wants to support extensibility they should add their own extension points. Today in the form of events.

**Comment by RafaelKoch** [comment]
Regarding extensions: I was already assuming the extension I want to extend has suitable events. I still do not know how it works though and will want to see the code.

**Comment by esbenk** [comment]
I will depend on whether the other extension developer will allow others to view the code. You may only have access to the symbolic information.
