### ISSUE TITLE
Reference to object Comment Sheet is ambiguous. Make sure you are not referencing packages containing objects with the same names

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1364]
What could be the reason of this error?
Can we use this page in our code?

![image](https://user-images.githubusercontent.com/23735402/34673664-040cb008-f4a9-11e7-89e7-6bd4f84ec966.png)

**Comment by pmohanakrishna** [comment]
same with ServLogManagement codeunit..

**Comment by esbenk** [comment]
Are you using any dependencies in your app.json? 
Have you reused any of the names in your extension?

**Comment by pmohanakrishna** [comment]
no dependencies..
![image](https://user-images.githubusercontent.com/23735402/34674782-32938574-f4ad-11e7-8e85-01f1bc788dd3.png)
we have 2 objects with different names but same Comment Sheet Caption. Is it the issue?

**Comment by esbenk** [comment]
It shouldn't be. I assume from the screenshot that you are generating your own symbols for the base app.

**Comment by pmohanakrishna** [comment]
I just downloaded symbols and creating app using our modification..

**Comment by esbenk** [comment]
I meant that you have added object using C/SIDE and is using the generatesymbolreference switch on the command line, right? Following the instructions [here](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)?

**Comment by pmohanakrishna** [comment]
No, I am not using C/SIDE and AL side by side.
I am using only AL

**Comment by esbenk** [comment]
Can try do remove objects from your solution to figure out if one of your new objects are causing problems

**Comment by pmohanakrishna** [comment]
I imported objects in database and trying to create app on same database. it seems that is the issue.
let me try it on new demo db.

**Comment by peikba** [comment]
Try my new tool, that would show all object ids and names made by extensions.

Download [here](http://ba-consult.dk/downloads/ExtensionDetails.zip).
Read about it [here](https://dynamicsuser.net/nav/b/peik/posts/developing-extensions-blindfolded-in-dynamics-nav):

**Comment by pmohanakrishna** [comment]
I deleted all our objects and imported standard objects back and compiled
still getting same error with comment sheet page and some other standard pages..

**Comment by esbenk** [comment]
You are importing objects into C/SIDE, but you are not using the "generatesymbolreference" switch? I.e. the application symbols should be the originally shipped symbols. You will not get symbolic information for imported objects without that.

What happens if you create a sample project with AL:GO? Do you get the same problem?

Could you provide a step-by-step repro? Something like

1. Spin up docker build xx.xx.xx / Use NAV2018 release
2. Import my own objects into database ... (maybe some indication of the objects imported types etc)
3. Create extension project ... with ... objects in it

**Comment by pmohanakrishna** [comment]
1. Created azure VM using https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/
2.  exported standard objects using finsql.exe Command=ExportToNewSyntax
3. Merged our solution to standard database and exported using finsql.exe Command=ExportToNewSyntax
4. created deltas using Compare-NAVApplicationObject with ExportToNewSyntax
5. Ran txt2al
6. opened AL folder in VS Code
7. Connected to above database (got these errors)
8. as per comments here, reimported all standard objects and deleted our objects from database and compiled.

still getting same errors. 
not using generatesymbolreference

**Comment by pmohanakrishna** [comment]
creating hello world project with AL:GO is working fine.
