### ISSUE TITLE
Build 19943, DecimalPlaces does not seem to work

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/AL#1368]
We have a decimal field that needs 5 places of decimal precision.
The table definition of the field in AL is:
field(57;"my field";Decimal)
        {
            DecimalPlaces = 0:5;
        }

In the page using this we have:
 field("my field";"my field")
                {
                    ApplicationArea = Basic,Suite;
                    BlankNumbers = BlankZero;
                    DecimalPlaces = 0:5;
                }

However, when we try and use anything beyond 2 decimal places we get "The field can have a maximum of 2 decimal places".

**Comment by NKarolak** [comment]
#1282

**Comment by StanislawStempin** [comment]
Closing as duplicate
