### ISSUE TITLE
An error occurred during deployment

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#137]
I have tried to deploy the current Azure template and get an error.

```
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Die Vorlagensprachausdrücke für Ressource \"/subscriptions/a95a59fe-c7c7-4792-93a9-1c2c630899ce/resourceGroups/NewNavExperience/providers/Microsoft.Compute/virtualMachines/navexperience/extensions/vmextension1\" in Zeile 1 und Spalte 17845 konnten nicht verarbeitet werden. \"Die Sprachausdruckseigenschaft \"templateLink\" ist nicht vorhanden, verfügbare Eigenschaften sind \"template, parameters, mode, debugSetting, provisioningState\".\""
  }
}
```

**Comment by freddydk** [comment]
Not sure what went wrong here, but typically the problem is, that the VM Name needs to be globally unique and cannot contain special characters nor be more than 15 characters long.
I typically use my initials followed by dev and some number - that typically works.

**Comment by Gallimathias** [comment]
I think this is not the problem. The error says the TemplateLink property does not exist in the deployment script.
Typ: Microsoft.Compute/virtualMachines/extensions
Reesource: navexperience/vmextension1
VMName: navexperience

**Comment by freddydk** [comment]
A VM Name of navexperience is probably not globally unique - try navexp followed by some number or your initials followed by dev and some number
