### ISSUE TITLE
Event request for Pages 46,47,54,55,516,518 Procedure GetSelectionFilter

### ISSUE THREAD

**Issue by Mahendarmyak** [Microsoft/AL#1370]
In codeunit **46-SelectionFilterManagement**, the procedure-**GetSelectionFilter** changed to external.to use that in pages  Need **GetSelectionFilter** in **Pages 46,47,54,55,516,518**, it would be great if it is added.

![image](https://user-images.githubusercontent.com/34544585/34653001-013aa416-f3e6-11e7-95df-0816deeb2f15.png)

**Comment by Rajiniadvaita** [comment]
yes it will be great and helpful if it is added

**Comment by bachii1010** [comment]
Hi,

It would be also great if it will added in more search pages which we use frequently like sales purchase warehouse production etc

**Comment by AnkithShah** [comment]
hi,

 Yes it will be very help full if the above request is added.

**Comment by krishnaGottuparthi** [comment]
Hi,
Yes it will be very helpful if the above request is added.

**Comment by jwikman** [comment]
This would be nice to have on all list pages, as a system function. But I realize that it's a bit more work than just adding the functions on the requested pages...

**Comment by AlexanderYakunin** [comment]
Hi, you ask for selection filter for sub pages based on document line tables (like Sales Line) with primary key Document Type, Document No., Line No. 
GetSelectionFilter can provide filter for single field only. Please describe in details what do you need and which field should be used for filter?

**Comment by AlexanderYakunin** [comment]
1. GetSelectionFilter is already external
2. I have no reply to questions regarding GetFilterSelection from Sales/Purchase Line records. Here primary key consist of 3 fields although GetFilterSelection was designed for master tables (like Item, Vendor etc.) with one field in primary key. So this part is rejected
