### ISSUE TITLE
" BLOBImport " Method not found

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1372]
Error : The type or method BLOBImport cannot be used for Extension development.

**Comment by esbenk** [comment]
Can you provide some details?

**Comment by srinivasdes** [comment]
Currently we are converting our add-on from CAL to AL. And with in our add-on we have been using BLOBimport Method Witch is not exist in AL extension. 

Error : The type or method BLOBImport cannot be used for Extension development.

Please provide us if any method exist which gives the similar output

Thanks.

**Comment by esbenk** [comment]
File API's are blocked for extension development. You can use them on-prem by changing the target setting in app.json to "internal".

Please read the [FAQ](Please read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)) for more information on this topic.

**Comment by ryanweigel** [comment]
https://github.com/Microsoft/AL/labels/v1-blocker
