### ISSUE TITLE
Deviating user names in the setting will lead to errors

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#138]
In the deployment I have tried to deviate from the specified users of the template.

But, as soon as I did that I could no longer access Navision. I do not know why the user had no rights. The template works with me only with the given users from the Template.

**Comment by freddydk** [comment]
I assume we are talking about the Azure Image.
Not totally sure what you tried to do, but when deploying you will have two NAV instances created: One with NAV Username/Password authentication (an admin user and the same password you specified when deploying) + one instance with WIndows Authentication and the Windows Auth. SID has been applied to the Admin user.
If you create new users in Windows, you will need to add them to NAV using the powershell CmdLets in the administration shell and assign permissions (SUPER), that should work just fine.

**Comment by Gallimathias** [comment]
I tried to use this link: http://aka.ms/navdeveloperpreview. If I try to change the user names used in the picture, I am missing in the vm the rights to do something in Navision. I can not even add new users.

Image upload does not work here, I submit later.

**Comment by freddydk** [comment]
I have deployed a machine with vmadm as vm administrator and navadm as nav administrator and everything works fine. both users are in NAV, both users have access, both are SUPER.
