### ISSUE TITLE
Extensions License checking issues for NAV 2018 multitenant

### ISSUE THREAD

**Issue by acyvas** [Microsoft/AL#1381]
I have ran into following issues, when publishing AL extension to NAV 2018 multi-tenant option:

1. It is not possible to publish the solution if only execute permissions are specified in the license. Insert permissions needed to properly publish the solution. 
This is a blocker for ISV solutions to be distributed as on-premise extensions.

2. Once solution is deployed on NAV server instance, it can be deployed to any Tenant, even if tenant license does not have extension object range in it. It would be good, if license was checked before installing extension to tenant, or in worse case, objects outside range of tenant license were not accessible to protect intellectual property.

**Comment by esbenk** [comment]
1. is addressed with the support of Runtime Packages. See the [blog](https://blogs.msdn.microsoft.com/nav/2017/11/08/nav-development-preview-november-update/). Runtime Packages can be deployed without a developer license.

2. We don't have any plan for this short term.

**Comment by acyvas** [comment]
Thank you for your response.
Basically, your suggested runtime package approach means that object access is not restricted by NAV license and ISV has to create other means to protect their IP.

I have tried the scenario suggested in the blog post. It works as you described. There is only one thing -
Get-NavAppRuntimePackage commandlet works only with SingleTenant NST. In multi tenant it requires tenant parameter, which is not possible to specify in commandlet.

**Comment by esbenk** [comment]
We are aware of the SingleTenant limitation. We are working on support for that and it will be in one of the next updates.

The workaround for now is to change to single-tenant.

**Comment by fvet** [comment]
Following point 2. I hope this will neither change on long-term too.

Let's say we have an internal (non cfmd) addon called 'NAV Finance enhancements' grouping several smaller features. Each of these features consists of various new table objects (60000..60200). Shipping the entire addon as a fob file did never pose any issues and allowed us debugging the code as well. Even if the customer only had part of the tables (60000..60010) licensed, limited to only the features really needed (and thus to cut costs on the custom objects).

In case we would create the above as one 'NAV Finance enhancements' extension, containing all table objects (60000..60200) and we would publish/install the extension using the customer license (only containing 10 tables) this should not block in my opinion. Only when actually using/accessing an unlicensed feature (if not restricted by AccessByPermission) an error might raise.


Will we actually be obliged using Runtime Packages? When not using Runtime Packages, publishing/installing the above extension gives me an error

> Your program license does not allow you to pubslish table 60011.

A workaround I've found is to publish/install the extension first with the developers license, and afterwards change back to the customer license. (probably providing more debugging support as well) Is this supported behavior?

**Comment by esbenk** [comment]
Installing with the developer license is supported behavior and yes it will provide better debugging experience. You are definitely not required to use runtime packages, it is option that can be used if you want a package without AL sources or that can be installed with a customer license.
