### ISSUE TITLE
Feature Request: Txt2AL should pull Application Area and Usage Category information from MenuSuite

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#1382]
It would be great if the Txt2AL tool would pull MenuSuite information and apply it to the generated Page and PageExtension AL files.

**Comment by coffeecup007** [comment]
We would like this too.   We ended up having to build our own tool that did exactly this, but we'd prefer that this 'just worked' as part of the txt2al process.

**Comment by hougaard** [comment]
Put it up on GitHub :)

**Comment by StanislawStempin** [comment]
@JesperSchulz - didn't you guys build a tool that does exactly that?

**Comment by JesperSchulz** [comment]
We've written a PowerShell cmdlet which transfers the meta data from the menusuite into the C/AL pages and reports, as that step anyway needs to happen for our new search. The script will ship together with the October release. The name of the cmdlet is Set-ObjectPropertiesfromMenusuite. You would have to run that script BEFORE running Txt2AL. Does that meet your needs?

**Comment by StanislawStempin** [comment]
We will rely on that tool for the txt2al conversion pipeline. Closing this issue.
