### ISSUE TITLE
Page Extensions Trigger OnAfterGetCurrRecord not fired, when the C/Side Trigger is empty

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1383]
I want to add a new fact box at the `"Location List"` by `page extension`:

```javascript
pageextension 50100 "Location List Ext" extends "Location List"
{
    layout
    {
        addfirst(FactBoxes)
        {
            part(MyPart; MyPart) { }
        }
    }

    trigger OnAfterGetRecord();
    begin
       // This trigger is fired correct
    end;
 
    trigger OnAfterGetCurrRecord();
    begin
       //  This trigger is never fired - becuase the C/Side trigger is empty    
       Message('Trigger fired on: %1', Code);    
    end;
}
```
Unfortunately the `OnAfterGetCurrRecord` is never fired. 

**The current fix** is, to add a comment at the C/Side trigger e.g.:
![grafik](https://user-images.githubusercontent.com/15800069/34729113-15ba7b24-f55c-11e7-9ef3-832fb890bc21.png)

...and the result - my `page extension` trigger is fired correct:
![grafik](https://user-images.githubusercontent.com/15800069/34729086-039135fa-f55c-11e7-93b1-62a2e07370d3.png)

My Version(s):
![grafik](https://user-images.githubusercontent.com/15800069/34729266-84b78364-f55c-11e7-9204-4f2e1dfc1f56.png)
![grafik](https://user-images.githubusercontent.com/15800069/34729301-9aef9fae-f55c-11e7-8858-7e1b29dbb88a.png)

**Comment by geraldbeaulieu877** [comment]
I have the same issue. I use the NAV 2018 cu3, AL Language 0.12.17720

**Comment by Twija** [comment]
i have same issues related service. please check all list and card pages.

thank you.
