### ISSUE TITLE
Duplicate Primary Key in Temporary Subform

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/AL#1388]
Using Navision 2018 CU1

When Populating a Temp Header Table and then populating a Temp Line Table that is a subform for the Temp Header Table this is producing the record twice in the subform.  When moving from Header Record to Header Record the Temporary subform should update with Temporary Line records.  This happens but it results in duplicates of the same Record.  This works perfectly in NAV2018 but will not work as an extension

![image](https://user-images.githubusercontent.com/32099690/34746181-510d5112-f550-11e7-8a55-835695dc510b.png)

This is the code for the subform 

![image](https://user-images.githubusercontent.com/32099690/34746284-af47cc26-f550-11e7-9ce5-497500a64cef.png)

[test.zip](https://github.com/Microsoft/AL/files/1616867/test.zip)

**Comment by esbenk** [comment]
Looks like a bug. Do you have the C/SIDE version of the objects? Speeds up the investigation

**Comment by MatthewMcCarthy7** [comment]
Here you go.  Let me know if you need anything else.  
[TestObjects.zip](https://github.com/Microsoft/AL/files/1624303/TestObjects.zip)

**Comment by esbenk** [comment]
Thanks. I will take a look tomorrow.
