### ISSUE TITLE
"Permissions" attribute in a codeunit don't appear to work.

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/AL#1389]
Problem: Having permissions specified with the 'permissions' attribute doesn't appear to work in a codeunit.

Occurs with build 20048

To reproduce:

1) Have a codeunit where it has permissions to a table defined using the "Permissions" attribute.
codeunit 70012345 "Demonstrate Problem"
{
    Permissions = TableData "MyTable"=rimd;
    trigger OnRun();
    begin
        DoStuff(false);
    end;

local procedure DoStuff(notImportant : Boolean);
    begin
        recExample.RESET;
        if not recExample.GET then begin 
          exit;
        end;
    end

    var
	recExample : Record "MyTable"

}

2) Have an example table:
table 70067890 "MyTable"
{
    fields
    {
        field(1;"Primary Key";Code[10])
        {
            Caption='Primary Key';
        }
}

3) 
Expected:   Since Codeunit 70012345 "Demonstrate Problem" has the "rimd" on table 70067890 "MyTable" I would expect that codeunit to have read, insert, modify, and delete permission.

What actually happens (unexpected): 
Stack trace:
Server instance: NAV
Tenant ID: default
<ii>Session type: Background
Session ID: 30
User:
Type: Microsoft.Dynamics.Nav.Types.NavPermissionException
Remappable: True
ErrorCode: 18023807
ErrorNumber: 1407
ModuleNumber: 19
SuppressMessage: False
DiagnosticsSuppress: True
SuppressExceptionCreatedEvent: False
FatalityScope: Call
Message: <ii>You do not have the following permissions on TableData 70067890: Read</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.PermissionSetBase.VerifyPermissions(NavApplicationObjectBase securableObject, PermissionMask permissionMask, LimitedUserPermissionChecker limitedUserPermissionChecker, Func`2 checkTableEmpty, PermissionMask additionalIndirectPermissions)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.VerifyPermissions(PermissionMask permissionMask, Boolean checkForEmptyTable)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordWithoutCheckingValues(DataError errorLevel, NavValue[] primaryKeyValues, FiltersAndMarks filtersAndMarks, Boolean useRecord, Boolean cacheOnly, Boolean calcAutoCalcFields)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.GetRecord(DataError errorLevel, NavValue[] values)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALGet(DataError errorLevel, NavValue[] values)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit70012345.DoStuff_Scope__1522140613.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit70012345.DoStuff(Boolean pbForce)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit70012345.OnRun(INavRecordHandle ?rec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.InvokeRun(Int32 objectId, Object[] args)
     at Microsoft.Dynamics.Nav.Runtime.ALSession.RunCodeunitAndDisposeSession(NavSession session, Int32 codeUnitId, NavRecord record)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088

**Comment by atoader** [comment]
Hi, @coffeecup007 ! I've tried running the following code:
```
page 50100 MyPage
{
    actions
    {
        area(processing)
        {
            action(ActionName)
            {
                trigger OnAction();
                var
                    c: Codeunit MyOtherCodenit;
                begin
                    c.Run();
                end;
            }
        }
    }

    var
        myInt: Integer;
}

codeunit 70012345 MyOtherCodenit
{
    Permissions = TableData MyOtherTable = RIMD;

    trigger OnRun();
    begin
        DoStuff(false);
    end;

    var
        recExample: Record MyOtherTable;

    LOCAL procedure DoStuff(notImportant: Boolean);
    begin
        recExample.RESET;
        MESSAGE('here');
        IF NOT recExample.GET THEN BEGIN
            MESSAGE('here2');
            EXIT;
        END;
    end;


}

table 70067890 MyOtherTable
{
    fields
    {
        field(1; PK; Code[10])
        {
            Caption = 'Primary Key';
        }
    }
}
```
It prints "here" and "here2". Is there something that I am missing in your example? How are you running the Codeunit?

**Comment by coffeecup007** [comment]
We're triggering it from a variety of event subscribers (in the real app).

LOCAL [EventSubscriber] HandleOnAfterGetDefaultRoleCenter(VAR DefaultRoleCenterID : Integer)
LOCAL [EventSubscriber] HandlePageSOProcessorActivitiesOnOpenPage(VAR Rec : Record "Sales Cue")
LOCAL [EventSubscriber] HandlePageO365ActivitiesOnOpenPage(VAR Rec : Record "Activities Cue")
LOCAL [EventSubscriber] HandleOnAfterLogInStart()

We're currently trying to figure out what the differences are to give more information.   We thought we'd comment just to let you know we're not ignoring your inquiry, we're just having difficulties narrowing it down more, it does appear that there is something else happening.

**Comment by kalberes** [comment]
I have also tried a repro with the demo license (adjusting the IDs) and have no repro. Please provide more input on how can we repro this otherwise blocking issue.

**Comment by coffeecup007** [comment]
@kalberes  I have emailed @ryanweigel  an attachment containing an example AL extension showing the issue.   I am suspecting (but don't know) that it's related to being in an event subscription.

**Comment by kalberes** [comment]
What permissionsets have you given to the non SUPER user?

**Comment by kalberes** [comment]
I have managed to repro it with a minimal permission set. 
That said the same is also reproducible from C/SIDE.  This issue does not look like an extension V2 problem. Maybe CSS has to be involved an RFH initiated.

**Comment by coffeecup007** [comment]
This did not seem to cause us issues in the v1 extension (or if it did fail it did not seem to have any visible symptoms), unless you are indicating that it just happens on the recent builds regardless of v2 extension or not.

Is there a potential workaround?  Why do the permissions seem to apply in some scenarios and not others?

**Comment by kalberes** [comment]
I do not think this is a recent build regression.  I guess Nav 2018 release build for example would also repro had you been doing all this in C/SIDE.
What permissionset have you applied for the non SUPER user?
I do not know of a workaround but have logged your issue to the team handling the permission system in the NAV server.

**Comment by coffeecup007** [comment]
The permission sets are: "d365 basic" + "local"

**Comment by StanislawStempin** [comment]
The indirect permissions work as designed. Nothing has changed as compared to Extensions V1 in this area.

The basic idea is that you need to grant user one "half" of the indirect permission and the codeunit grants itself the other "half". Only if the two halfs are present the actual permission is granted.
