### ISSUE TITLE
Need Access To BuildSalesHeaderTypeConditions in Workflow Setup Codeunit 1502

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1394]
Ideally, all global functions would be exposed as "External" in this codeunit, but as others also have written, it should be possible to create your own workflows in an extension setup and also then reference existing functionality to do so - Like the function above. Yes, I can develop it myself, but why shouldn't I be able to reuse it?

**Comment by ryanweigel** [comment]
[v1-blocker](https://github.com/Microsoft/AL/labels/v1-blocker)

**Comment by JesperSchulz** [comment]
Exposed all functions in CU1502. Change is being submitted today.
