### ISSUE TITLE
Contols to extend standard pages hard to understand

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1395]
When creating page extensions for pages like the Order Processor Rolecenter or Purchases and Payables Setup the existing controls are numbered instead of names.

Is this going to be changed? The problem is that if the answer is yes, you guys are going to break my extension...

![image](https://user-images.githubusercontent.com/7205122/34782121-90d840a4-f5dc-11e7-8b70-a217d678dcac.png)

**Comment by esbenk** [comment]
We are aware of this problem. Unfortunately C/SIDE never forced developers to put a name on their controls & actions. The poor naming is already a problem in C/SIDE when write page tests.

We don't have a plan on how to handle this yet. There is no imminent plan for renaming the base-app.

On one hand we would like to have meaningful names on controls/actions, but on the other hand we don't want to break anything. Not an easy one.

**Comment by markbrummel** [comment]
I vote changing it into more understandable names. We are just at the beginning of extensions. How are you going to explain this to someone new to nav?

**Comment by vytjak** [comment]
Definitely +1 for changing the names into something sensible. This will be MUCH more painful to change in the future, when there will be a lot of extensions out in the wild.

**Comment by Gallimathias** [comment]
as well as in other topic I am definitely for breaking hard with the old way. In general, it would be nice to leave numbers and ids out of development altogether. Numbers don't only look like crap, they can't be memorized and lead to problems in the future. See the conflict topic in the individual number range of objects.

**Comment by StanislawStempin** [comment]
This is tracked by #527, let's continue the discussion over there
