### ISSUE TITLE
New Cues not showing values

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1397]
When extending Cue tables the flowfields seem not to show the values.

![image](https://user-images.githubusercontent.com/7205122/34783283-0731dc58-f5e0-11e7-80c6-04013e38ed9f.png)

![image](https://user-images.githubusercontent.com/7205122/34783298-1010abce-f5e0-11e7-9acd-2a67522f9284.png)

**Comment by cmrudolph-msft** [comment]
Hi Mark,

Would it be possible to get a small repro attached to save us a bit of time and to make sure we are looking into this exact issue?

**Comment by markbrummel** [comment]
Its fairly straight forward. extend a cue table with a flowfield. add a new activities page and extend the role center with it.

if you can't repro it it's probably my mistake. i just noticed that in my case neither of the two flowfields worked.

**Comment by cmrudolph-msft** [comment]
Fair enough. I'll give it a try. Just wanted to make sure there wasn't any extra complexity lurking. Thanks.

**Comment by markbrummel** [comment]
let me know if it works on your end. i'll look a bit more into it tomorrow too.

**Comment by cmrudolph-msft** [comment]
Hi Mark,

I did a simple experiment and it worked:
1. [VS Code]: Extend the **Sales Order Cue** table to have a field called **Sales Orders - Open2**. I used the exact same calc formula as the original field
2. [VS Code]: Extend the **SO Processor Activities** page to show my new field

![image](https://user-images.githubusercontent.com/30469904/34798968-32acb89a-f61b-11e7-888b-cce8bd422c51.png)

Upon a closer reading the only difference I see between our scenarios is adding a new activities page versus extending the existing one. I can't see this making a difference but will try to be certain...

**Comment by cmrudolph-msft** [comment]
...and I also had success adding a completely new page and extending the role center.

Per your screenshot something does appear to be amiss, but it must go deeper than simply using a new flow field as the basis for a cue value.

**Comment by markbrummel** [comment]
I found the issue. The table "Activities Cue" was empty. This is strange because it is a demo database.

When I insert a blank record the flowfields work.

Thanks for helping me figure this out.

**Comment by cmrudolph-msft** [comment]
I'm glad to know it was a data issue and not a case we flat out missed. Thanks for double checking.
