### ISSUE TITLE
PromotedActionCategories in PageExtensions

### ISSUE THREAD

**Issue by JamesCrowter** [microsoft/AL#1398]
So when I set the PromotedActionCategories property in a page extension, because I want a new toolbar category for the action I'm adding, it doesn't seem to take effect?

Actually don't we need to rethink how this works? Should I be able to set the full list in my extensions and what will that do to other extensions for the same page that add a Action Category as well?

Would it not be better to have a 'ActionCategory()' which I can add captions to etc. following an addafter() so following the same pattern we have for fields and actions themselves?

**Comment by vytjak** [comment]
+1 on this, I've just worked on the same bit recently and was wondering how will this work with multiple extensions, that want to have their own promoted action categories. 
It seems like this needs some platform design improvement considerations.

**Comment by dtkb** [comment]
I just saw BC not bothering to apply the new caption added in `PromotedActionCategories`, and after testing found that the correct caption was shown when viewing in English (US) language, but it reverted to Category9 when changed to English (UK).
