### ISSUE TITLE
CurrPage.Caption('My Page Caption') does not work in extension.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1399]
I have some code that works when run from C/SIDE type development, but after converting the code to AL to run as Extension V2, the caption of my page does not get changed.

I have some other pages where dynamically setting the caption works and it appears to me that I'm doing the same thing, although there are some differences between the pages (such as using a temporary table as the source).

To provide more details of the code that does not work properly, I have an activities page that shows Cues that could represent different things depending on user configuration. When I click the drill down on the Cue, it sets the caption of the drill down page and the temporary table records to display and then runs the page.

```
**Cue1Count - OnDrillDown()**
CLEAR(MyDetails);
MyDetails.SetRecordsToShowAndCaption(TempCue1Records,Cue1CaptionText);
MyDetails.SetApproverControlIsVisible(TRUE);
MyDetails.SetOwnerControlIsVisible(TRUE);
MyDetails.RUN;
```

The MyDetails page type is List. SourceTableTemporary is true.

I have messaged the CurrPage.Caption property in the OnOpenPage and it is set to the correct value, it is just not displayed on the page.

As I said, the same code when written in C/SIDE works correctly but when written in AL and deployed as an extension it does not.

**Comment by DavidRoys** [comment]
You should know that I tried to replicate this in a "Clean" extension with minimal code so I could send it through to you but I cannot get this to go wrong even though it appears that most things are the same. I can get this to go wrong every time in my real project which I could share privately, however, it needs some setup in order to use. Any suggestions most appreciated.

**Comment by DavidRoys** [comment]
I have done some more investigation on this because it is really weird. I think I have found what causes this to go wrong by creating a simple test project. 

Having the CaptionML property of the page I am drilling down to (in my initial example this would be MyDetails) set will cause this to go wrong, but you need to restart the NAV Server in order to pick this up.

Then I cannot fix this behavior again (i.e. removing the captionml property and restarting the NAV server keeps the wrong behavior). The only way I can "Fix" this again is to renumber my PageExtension (which in my example is the code that adds the new Cue to the drilldown page. I can add a zipped up project that you can use to replicate this if you wish.

**Comment by DavidRoys** [comment]
[Objects.zip](https://github.com/Microsoft/AL/files/1624311/Objects.zip)

OK this attached folder includes a project that will show the error. Simply run the Accounting Manager Role Centre page and click the Cue with the caption "Click me to see drilldown" in the Payments group on the Activities part. You should see a message that the CurrPage.Caption is "Drilldown Caption". This is being displayed in the OnOpenPage trigger. When the page opens the actual cue being used is "NewCueField" which is the Name of the field control on the page extension.

The only way I seem to be able to fix it again is to remove the CaptionML on the TestTempPage page and redeploy with a new PageExtension ID for the MyNewActivities extension.

I think I may have the CaptionML property commented out in the zip file I attached so you will need to edit this before deploying it in order to see it go wrong.

**Comment by DominikDitoIvosevic** [comment]
Hi @DavidRoys . This should be fixed on the latest developer preview. If you would like this to be ported to On Prem please follow the traditional channels to request a hotfix.

**Comment by DominikDitoIvosevic** [comment]
@DavidRoys please tell us if you are still experiencing this issue. I'm closing it
