### ISSUE TITLE
IntelliSense and table keys

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#140]
Good Morning!
We are missing two important features:
- No. of references for table keys -> always says "-"
- IntelliSense for keys -> "setcurrentkey(" should give You a list of available keys; ideally the names of the keys followed by the fields they contain

**Comment by dennisfrostlander** [comment]
Good morning,
Do you have in mind any specific types of references you would like to see for table keys?
We will consider code completion for field keys in the future updates.

**Comment by RafaelKoch** [comment]
I would like to see any coded usage of keys as references. This includes the command setcurrentkey as well as any sorting property in pages, reports, e.g. 
Why? Because if I change  a key I would like to see what I am about to break or of course sometimes a key might exist that is not (intentionally) used at all and I might want to remove it. It has always been hard to investigate this in NAV so we used Object Manager Advanced to do it, but only after coding itself. Now with AL  90% of the job could be done while programming if we had those references :-)

**Comment by esbenk** [comment]
The suggestion is to use 

r.SetCurrentKey(MyKeyname)

rather than (or as an alternative)

r.SetCurrentKey(FieldA, FieldB)

?

**Comment by RafaelKoch** [comment]
Yes, that pretty much sums it up

**Comment by esbenk** [comment]
Thanks. It makes sense.

**Comment by cruz-victor** [comment]
fsd

**Comment by pborring** [comment]
This should now be supported with
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/show-list-keys-while-working-al-code

Thus closing this GitHub entry
