### ISSUE TITLE
issue: Extending NAV 2018 through VS code

### ISSUE THREAD

**Issue by Linty1995** [Microsoft/AL#1400]
Hi all,
I am new in  vs code. I want to extend NAV 2018 through VS code but there are some errors as follows:
( Take Page "Purchase Quote" for example )

1. I can not find all actions in VS code.
![2018-01-11 12_09_31-demo database nav 11-0 - microsoft dynamics nav development environment](https://user-images.githubusercontent.com/35321752/34808300-f36cb0c8-f6c8-11e7-8f46-f8e90ed4fcd3.png)
In  NAV 2018, there is an action named "Release" but I can not find it in vs code. Therefore, I can not modify the Release action. (The error message shows that the action is not found in the target.)
![2018-01-11 12_20_29- purchase quote page al - pqtest - visual studio code](https://user-images.githubusercontent.com/35321752/34808428-e47be3f8-f6c9-11e7-828a-36d7865f9504.png)
note: "Release" in the pic is not the "Action" Release but the "Group" Release 

2. Can I modify the OnAction trigger in an existing page? In modify(), I just see two options: OnBeforeAction() and OnAfterAction().

Hope someone can kindly help me to solve these issues. Thanks in advance. :)

**Comment by esbenk** [comment]
1. Looks like a bug. We will investigate. The Group is actually named "Action3".
2. You can't change the code in the original OnAction trigger. You can be only called before or after the original code. In the scenario we you wan't to completely change the behavior, the workaround is to hide the original Action and provide your own replacement.

**Comment by Linty1995** [comment]
Hi @esbenk, thanks for your reply. :)
I put 3 messages ("1", "2", and "3") on different occasions: OnBeforeAction(), OnAction(), and OnAfterAction().
However, these three messages popped up after I pressed the action button.
Is there any way to use OnAfterAction trigger to replace OnAction trigger in Visual Studio Code development environment? ( I don't want to modify my code in NAV development environment and use "vs code extension" to cover the original code.)

**Comment by esbenk** [comment]
The message() function shows messages when all the server-side work is done. If you want to block code execution you can use Confirm() instead.

You can't replace code. Only hide the original action and provide your own with the same Caption/Icon.
