### ISSUE TITLE
Adjusting the tab size of the formatter

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1401]
I've noticed that the tab size of the built in formatter is always 4. It would be nice if the formatter would pick this value up from the VS Code settings.

![image](https://user-images.githubusercontent.com/5981414/34812265-e22323a0-f69c-11e7-9f03-bf9ff94b9810.png)

**Comment by atoader** [comment]
Hi @kvaldik ! At the moment, you cannot customize this property.
We have debated whether we should have options for customizing this in the beginning and we decided there should be only one way of formatting AL, similar to how golang does it. We might want to relax this in the future, and when we do it, we will surely take your suggestion into consideration.

**Comment by gudrunleos** [comment]
@atoader - this creates discrepancies in indentation of the code since txt2AL uses the C/al 2 space indentation - right?

**Comment by kvaldik** [comment]
Hi @atoader, that makes sense and I can live with that. It's just a bit of a jump going from the traditional 2 spaces in C/AL  to the now hard coded 4 spaces in AL. A 100% increase, but it's nothing you can't get used to :)
