### ISSUE TITLE
Debugging OnPremise MultiTenant ServerInstance

### ISSUE THREAD

**Issue by Jan-Skrubbeltrang** [Microsoft/AL#1402]
Got a weird issue after trying to set up a sandbox server.

On default ServerInstance (DynamicsNAV110) i have no problem publist and debug from AL (Have set the netfx flag) 

When I try to publish with debugging (F5) to my MultiTenant NST i get the following error:

Debug Console (VS Code)
[2018-01-11 09:26:29.74] Sending request to http://XXXXXXXXXX:XXX9/Demo/dev/apps?tenant=JSK
[2018-01-11 09:26:32.51] Success: The package has been published to the server.
[2018-01-11 09:26:32.59] Error: An internal error has occurred

Server Event;
Server instance: Demo
Tenant ID: 
<ii>User: XXXXXXXXXX\jsk
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavTenantNotFoundException
SuppressMessage: False
DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message: <ii>A tenant was not specified, but is needed because the system has multiple tenants. Contact your system administrator.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.get_DefaultTenant()
     at Microsoft.Dynamics.Nav.Service.ServiceAuthenticationHelper.AuthenticateForServiceCallCore(Func`1 getNavTenant, Func`1 getRequestProperties, Func`1 getWindowsIdentity, Func`3 createException)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
</ii>

Seems like it fails to connect to the Tenant at some point! Publishing the extension without debugging (CTRL + F5) works fine

**Comment by kalberes** [comment]
Have you specified a tenant in the launch.json?

**Comment by Jan-Skrubbeltrang** [comment]
Yes, my launch.json looks like this:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Onepint Development",
            "server": "http://XXXXXXXXXX",
            "serverInstance": "Demo",
            "tenant": "JSK",
            "port": XXX9,
            "authentication": "Windows",
            "startupObjectId": 22
        }
    ]
}

And also, i have no problem publishing without debugging (CTRL+F5)
