### ISSUE TITLE
Event request for adding extra filters to filter Saleslines in function "SetFilterSalesLine" in Codeunit 7322 Create Inventory Pick/Movement

### ISSUE THREAD

**Issue by krishnaGottuparthi** [Microsoft/AL#1403]
Hi,
Please provide event for adding extra filters to Sales line in function  **SetFilterSalesLine** of **Codeunit 7322 Create Inventory Pick/Movement**.It would be great if added for customization. Sales Line parameter to be added. It should be VAR type.

![image](https://user-images.githubusercontent.com/35251581/34824193-812d654a-f6f3-11e7-9459-9d94d07be93d.png)

**Comment by Mahendarmyak** [comment]
Yes it will be very help full if the above request is added.
