### ISSUE TITLE
'(' and ')' characters in Control Add-In name

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1404]
We've registered '(nH)' suffix for our extension and it works fine with every object type except control add-ins. Extension compiles and we can install it, but we are getting this error message when we try to open a page with one of our controls:

> The filter "control name (nH)" is not valid for the Add-in Name field on the Add-in table. Did not expect '('.

**Comment by jcooper01** [comment]
Just to warn you, we tried using (CL) as our suffix and we encountered some issues. Namely, system factboxes like Notes and Links didn't work, as the Record ID it generated and tried to apply considered the parentheses to be part of a NAV filter. Then, we heard from a partner that restoring a database with parentheses in the table name was causing problems for an Azure bacpac SQL restore.

**Comment by StanislawStempin** [comment]
The use of parenthesis will no longer be allowed as part of the prefix. We will change the compiler to disallow parenthesis in control add-in names.
