### ISSUE TITLE
Can't change language in build 20048

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1405]
I have tried using both of these images to provision an azure VM: 

navdocker.azurecr.io/dynamics-nav:11.0.20048.0-finus
navdocker.azurecr.io/dynamics-nav:11.0.20048.0-finca

The language settings start at English (United States) for both. When I try to switch to English (Canada) or French(Canada) in either one, it reverts back to English (United States). This is preventing us from testing our translations with the new xliff format. 

Is there some way I should be changing the language settings other than in the web client?

**Comment by esbenk** [comment]
Is this a regression?

**Comment by strophanthus** [comment]
Not really. We hadn't tested the captionML version of the extension on this build. We only tested the version where we have switched to xliff. But yes, we are trying to make sure this change doesn't affect the UI for our extension. 

The language won't change in the web client in these builds even before the extension is installed, so it seems to be something related to this build or I'm unaware another way to change the language settings in the web client. 

It does work to change the language settings in the windows client.

**Comment by freddydk** [comment]
When you are running the financial builds, we are simulating D365 Financials, where the language settings are done in AAD.
There might not be a way of setting this in the WebClient.
If you try navdocker.azurecr.io/dynamics-nav:11.0.20048.0-na - then you should be able to change language,

**Comment by strophanthus** [comment]
okay, I will give that a try. thanks
