### ISSUE TITLE
StorageRestApiAuth in AL Code

### ISSUE THREAD

**Issue by TimothyWatkins** [Microsoft/AL#1406]
Trying to access Azure Storage http://myaccount.file.core.windows.net/?comp=list in AL using REST API. 
A nice .Net program is available here
git clone https://github.com/Azure-Samples/storage-dotnet-rest-api-with-auth.git
The conversion of this .Net program to C/AL using dotnet variables would be relatively simple. But without the dotnet variable components things get a little tricky.
To be specific I'm having issues with the following couple of lines and how best to convert to AL

            // Now turn it into a byte array.
            byte[] SignatureBytes = Encoding.UTF8.GetBytes(MessageSignature);
            // Create the HMACSHA256 version of the storage key.
            HMACSHA256 SHA256 = new HMACSHA256(Convert.FromBase64String(storageAccountKey));
            // Compute the hash of the SignatureBytes and convert it to a base64 string.
            string signature = Convert.ToBase64String(SHA256.ComputeHash(SignatureBytes));
            // This is the actual header that will be added to the list of request headers.
            // You can stop the code here and look at the value of 'authHV' before it is returned.
            AuthenticationHeaderValue authHV = new AuthenticationHeaderValue("SharedKey",
                storageAccountName + ":" + Convert.ToBase64String(SHA256.ComputeHash(SignatureBytes)));

Any help would be appreciated.

**Comment by esbenk** [comment]
It requires a recent change to the Encryption Management codeunit to compute the hash. It is not shipped yet.

I will soon publish some samples here, that shows how to calculate the SharedKey signature for use with both ServiceBus Queue and BlobStorage (the SharedKey signature are calculated slightly different)

The BlobStorage sample will require the change mentioned above. That change should be included in one of the next BC updates.
