### ISSUE TITLE
Error while executing command -c:\>docker run -e ACCEPT_EULA=Y microsoft/dynamics-nav:devpreview-finus 

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#1408]
Hello MS,

while running Docker command **Four** different results found for same command every-time we run this command.

**Result 1 :** 
C:\>docker run -e ACCEPT_EULA=Y microsoft/dynamics-nav:devpreview-finus
Initializing...
Starting Container
Hostname is f5d4e59233fc
PublicDnsName is f5d4e59233fc
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C1EFEA70A301E40CD7B1387A00EF4A525622B229
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
**Insufficient system resources exist to complete the requested service.**

**Result 2:**
C:\>docker run -e ACCEPT_EULA=Y microsoft/dynamics-nav:devpreview-finus
Initializing...
Starting Container
Hostname is 29d102d30f69
PublicDnsName is 29d102d30f69
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 8D02A5ED914340AED9FA50A5A8698439180EACA0
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
**Exception of type 'System.OutOfMemoryException' was thrown.**

**Result 3:**
C:\>docker run -e ACCEPT_EULA=Y microsoft/dynamics-nav:devpreview-finus
Initializing...
Starting Container
Hostname is 79cede674edb
PublicDnsName is 79cede674edb
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 93A1D1896054A70BD98792B81987BF56EC67D336
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
**Not enough storage is available to process this command.** 

**Result 4:** 
C:\>docker run -e ACCEPT_EULA=Y microsoft/dynamics-nav:devpreview-finus
Initializing...
Starting Container
Hostname is d517d7063809
PublicDnsName is d517d7063809
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FD07EB7BA4A4B2FE8E6BD4DD6FBD02C29E18B849
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
**Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The paging file is too small for this operation to complete. (Exception from HRESULT: 0x800705AF)**

Regards
Sachin Chavan

**Comment by hgnamvn** [comment]
Maybe you run the script on Window 10.
You get this error because Not enough resources is for container.
Please reference NAV Docker Image.docx file from the link: [nav-docker](https://github.com/Microsoft/nav-docker)

**Comment by chavansachin20** [comment]
Thanks [https://github.com/hgnamvn](https://github.com/hgnamvn)

Resolution : 
I have tried below command which didn't resolved the issue : `C:\>docker run -e ACCEPT_EULA=Y **--memory 4G** microsoft/dynamics-nav:devpreview-finus`

Then read article which says, Windows 10 machine memory allocation is issue. For which below is change from memory 4G to memory 3G
`C:\>docker run -e ACCEPT_EULA=Y **--memory 3G** microsoft/dynamics-nav:devpreview-finus`

Ref Link : 

- [nav-docker](https://github.com/Microsoft/nav-docker)
- [NAV Docker Image.docx](https://github.com/Microsoft/nav-docker/blob/master/NAV%20Docker%20Image.docx) 

Thanks 
Sachin Chavan
