### ISSUE TITLE
SqlTimestamp property doesn't work

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/AL#1409]
The SqlTimestamp property doesn't work, it doesn't matter if it's implemented in a table extension or a new table, the value remains 0.

Expected behavior:
When using the SqlTimestamp in a table extension I expect it won't only increase in case of a modification on a field in my table extension, but also when a field in the actual table gets modified.

I would like to know if this property is or will be supported for extension development and how it should behave.

**Comment by richardrobberse** [comment]
According to a support engineer at Microsoft it is reproduced and an RFH is filed to the development team.
Incident numer is 118011217453551

**Comment by UweBoehme** [comment]
No progress until now? Have a similar problem:

Adding a BigInteger Field with property SqlTimestamp = true; returns error on publish

Code:
```
tableextension 70700 ItemLedgerEntryWithRowVersion extends "Item Ledger Entry"
{
    fields
    {
        field(70700; RowVersion; BigInteger)
        {
            SqlTimestamp = true;
        }
    }
}
```

Debug console on synchronize:
`[2018-03-20 16:42:00.30] The request for path /DYNAMICSNAV110/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Specifying default value for timestamp column
`

Duplicate or other issue?

**Comment by kalberes** [comment]
Looks another issue in the synchronize context.

**Comment by StanislawStempin** [comment]
The use of SqlTimestamp property is not allowed in table extensions and has been blocked in the compiler.
