### ISSUE TITLE
Blockcomment

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#141]
A suggestion for block comments with solution

```
/ *This is
a Block
Comment */
```

[al.configuration.json](https://github.com/Gallimathias/AL/blob/feature/modified_extension/extension_mods/al.configuration.json)
[alsyntax.tmlanguage](https://github.com/Gallimathias/AL/blob/feature/modified_extension/extension_mods/alsyntax.tmlanguage)

from #139 

> @StanislawStempin "Thank you for the contribution. However, this is a change to the AL Language extension itself which is not part of this repository and not open sourced and therefore I can't merge it in. I would encourage you to open this as an issue and we will fix it in the next update."

**Comment by Gallimathias** [comment]
[Uploading al.configuration.json.txt…]()
[Uploading alsyntax.tmlanguage.txt…]()

**Comment by Gallimathias** [comment]
huups Clicked

**Comment by kalberes** [comment]
Hi Gallimathias,
Block commenting with /* */ is already supported (replacing the old { } C/SIDE based block commenting) .  Isn't it?

Thanks
Kalman

**Comment by Gallimathias** [comment]
In the attached files already, but this was inserted by myself. Since I assume that your "compiler" but swallows. Yes your compiler considers this or he simply ignores everything which is not al.

**Comment by kalberes** [comment]
I do not clearly understand your issue. In an *.al file one can block comment with /* */  without your change.
That is part of the AL lexer. Or, do you think there is an issue with it?

**Comment by Gallimathias** [comment]
No. I know my change is not immediately apparent if you do not see the original files.

The Lexer seems to get it otherwise it would not work, but the block comments were not highlighted. I'll try to make it visible right away

**Comment by Gallimathias** [comment]
Ok on this Commit you can see my changes Commit:  [745d030](https://github.com/Gallimathias/AL/commit/745d030e4f910ad2e14bb7375ef11195056b59cb)
Here you can now recognize my changes to the original files

**Comment by kalberes** [comment]
Aah ok, so we have an issue in the colorizer. Ok, thanks for spotting it out, we will try to apply your fix.

**Comment by kalberes** [comment]
One more question. Which version of the toolset are you using? The alsyntax.tmlanguage file should already contain these changes, since we have introduced block commenting with /**/
What I mean that you should not find anything like that 
<dict>  			
<key>begin</key>  
   <string>\{</string>
If your  alsyntax.tmlanguage contains lines like these than you are on some old(December) version of the toolset.

**Comment by kalberes** [comment]
Sorry the essence did not make it. These are the lines that have long been replaced in the alsyntax.tmlanguage . Actually with something similar you have.
<!-- We cannot support colorization for multiline comments since the '{' character is used in metadata definitions<dict> 
+		<dict> 
 			<key>begin</key> 
-			<string>\{</string>

**Comment by Gallimathias** [comment]
I would have to have the latest version, I had created the machine last week with the official template of you. There were a few problems with the application but the lies themselves from me.

**Comment by Gallimathias** [comment]
I'm on the road and I doubt that I can connect well to Azure. If I am afterwards in the Microsoft HQ in Munich I have wlan, then I tell you the current version number: D.

**Comment by StanislawStempin** [comment]
As Kalman mentioned this was already fixed but we will do some clean up in al.configuration.json since it's a publicly visible file.

**Comment by Gallimathias** [comment]
This is a very good plan :D @StanislawStempin 

There are not public files in the extension ???
