### ISSUE TITLE
Formatting around key words and parentheses 

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1411]
When we call a procedure with parameters there should be no space between the procedure name and parentheses. That is all good but the formatter seems to apply this to all parentheses so when constructing an if statement like this:

`if (true) and (false) or (true) then;`

It gets formatted to this:

`if (true) and(false) or(true) then;`

Which is not good to read and at least used to be marked as a warning when Code Analysis was enabled, doesn't seem to do that anymore :)

**Comment by thpeder** [comment]
It is fixed now, so you can expect to see it in a future update.

**Comment by kvaldik** [comment]
Vúhú, that is awesome. Thanks!
