### ISSUE TITLE
Change Request for Event C99000813 OnAfterInsertProdOrderLine

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/AL#1413]
In codeunit 99000813 Carry Out Action, please set publisher **OnAfterInsertProdOrderLine** to **GlobVarAccess**=Yes.
Our module has added an own global variable in that codeunit that needs to be included in the standard publisher.

**Comment by AlexanderYakunin** [comment]
We add events to create extensions of our code without custom changes. My understanding is that GlobVarAccess=Yes gives access to "our" global variables. Are you going to add "your" global var using Modern Dev? If this is possible this variable should be available got you without event change?

**Comment by NKarolak** [comment]
Yes, we added a new function to codeunit 99000813 that will set our own, new global variable. 

Once GlobVarAccess is Yes in OnAfterInsertProdOrderLine, multiple add-ons can extend codeunit 99000813 without the need to change OnAfterInsertProdOrderLine any further. We only extend our subscribers with the variables we need.
