### ISSUE TITLE
A secure channel could not be established for SSL / TLS

### ISSUE THREAD

**Issue by Bobby7878** [Microsoft/AL#1414]
Hi,
I'm getting an error everytime the function client.send() is called:
![httpclientsend](https://user-images.githubusercontent.com/34790794/34888040-eadb4a5e-f7c8-11e7-8f8a-d4af3a15ba02.PNG)
![sorrythatdidnt](https://user-images.githubusercontent.com/34790794/34888113-31fa200e-f7c9-11e7-86de-3f4edcddd17d.PNG)

The problem is, that the URL set in the HttpRequestMessage is a https. 

Type: System.Net.WebException
Status: SecureChannelFailure
Message: <ii>The request was aborted: Could not create SSL/TLS secure channel.</ii>
StackTrace:
     at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
     at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Source: System
HResult: -2146233079
</ii>

I have tried to obtain a self-signed certificate, but that did not help. 
Any suggestions? 

Thanks!

**Comment by kalberes** [comment]
The server has an Enable SSL setting in its configuration. Have you enabled it?

**Comment by Bobby7878** [comment]
When I try to enable SSL in server configuration I get this error
![ssl cannot](https://user-images.githubusercontent.com/34790794/34910172-bc2ea3b2-f8af-11e7-857f-da60074b0a0e.PNG)
When I do it through the CustomSettings.config file and restart the server I get this error in VS Code after restarting the server and publishing
![vscode ssl](https://user-images.githubusercontent.com/34790794/34910191-3314777c-f8b0-11e7-8a8a-3f45ffe26491.PNG)
I have created a self-signed certificate through the IIS.

**Comment by kalberes** [comment]
Do you have anything in the eventviewer that may help?

**Comment by Bobby7878** [comment]
No, the only thing present in the eventviewer is this 

Type: Microsoft.Dynamics.Nav.Management.Exceptions.NavCommandException
SuppressMessage: False
DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message: <ii>SSL cannot be enabled when the certificate is not present.</ii>
StackTrace:
     ved Microsoft.Dynamics.Nav.Management.ServerSettings.ConfigureUrlRegistrationCommand.RegisterOnEnableSsl(ServicesConfigurationSettings webServiceConfiguration)
     ved Microsoft.Dynamics.Nav.Management.ServerSettings.ConfigureUrlRegistrationCommand.OnWebServiceConfigurationChange(ServicesConfigurationSettings webServiceConfiguration, ConfigurationChangeType changeType, String newValue)
     ved Microsoft.Dynamics.Nav.Management.Cmdlets.SetNavServerConfiguration.InternalProcessRecord()
     ved Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Management
HResult: -2146233088

I have followed these instructions:
https://docs.microsoft.com/en-us/dynamics-nav/how-to--configure-ssl-to-secure-the-connection-to-microsoft-dynamics-nav-web-client

**Comment by kalberes** [comment]
It has been a while on this thread. Have you been able to solve your issue?
