### ISSUE TITLE
Changing authentification

### ISSUE THREAD

**Issue by Twija** [Microsoft/AL#1416]
Now I have been creating an app in UK version.
however I got an error message like this today.
[2018-01-13 23:34:57.44] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0 failed with code InternalServerError. Reason: The tenant 'msuk1-----------------' is not accessible.

how can I solve this? 
or how can I change the authentication to another tenant??

**Comment by qutreson** [comment]
Can you try clearing your credential from VS Code (Ctrl + Shift + P and then select "AL: Clear credentials cache") and then try again?

**Comment by sweikelt** [comment]
got the following launch.json:
            "name": "Your own server",
            "type": "al",
            "request": "launch",
            "server": "http://nav.XXXX.de",
            "serverInstance": "DynamicsNAV110",
            "authentication": "AAD",
            "startupObjectId": 22

where XXX is my Azure-Server hosting NAV 2018 with ACS-Authentication.
When i press F5 to download Symbols - it tries to connect to 
https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2018-01-18 13:49:27.93] 

why does it not try to connect to my srv?

**Comment by dennisfrostlander** [comment]
@sweikelt We don't yet support AAD authentication against custom servers. AAD is currently working for connecting to online sandbox tenants only.

**Comment by sweikelt** [comment]
@dennisfrostlander - the problem is, that my database and nst is hosted in my azure-environment - which is configured for SSO through my company's o365. 
now i want to dev on my local computer against the hosted db -> which is so no possible - maybe when i create a second nst with win-auth -> i'll try that und report it

**Comment by dennisfrostlander** [comment]
For Windows authentication to work I assume your dev machine needs to be in the same virtual network with the Azure machines running the NST. If this is not the case, you could also try UsernamePassword authentication.

**Comment by sweikelt** [comment]
@dennisfrostlander -> sorry - that was the plan (not win-auth -> usernamepassword) 👍
