### ISSUE TITLE
Codeunit1 OnDatabase

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/AL#1417]
This is for NAV2018 CU1.  When making a change to a Setup Table (General ledger Setup, Inventory setup, etc)  this does not trigger the function OnDatabaseInsert, OndatabaseModify, OnDatabaseDelete, and OnDatabaseRename in Codeunit 1.

**Comment by StanislawStempin** [comment]
Hi @MatthewMcCarthy7 
I have tried subscribing to OnDatabaseModify for General Ledger Setup and it seems to be working as expected. Could you please try the following code and see if it works for you:
```
codeunit 50100 SubscribeToModifyEvent
{
    
    [EventSubscriber(ObjectType::Codeunit, Codeunit::ApplicationManagement, 'OnAfterGetDatabaseTableTriggerSetup', '', false, false)]
    local procedure MyProcedure(TableId: Integer; var OnDatabaseModify: Boolean)
    begin
        if (TableId = 98) then
        begin
            OnDatabaseModify := true;        
        end;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::ApplicationManagement, 'OnAfterOnDatabaseModify', '', false, false)]
    local procedure Modified(RecRef: RecordRef)
    begin
        message(Format(RecRef.RecordId()));
    end;

}
```

**Comment by MatthewMcCarthy7** [comment]
So I'm using the trigger on Codeunit1 since I'm subscribing to all tables and ones that do not exist yet.  It seems to be any table that is a setup table also I noticed it on Purchase Line table.  

[Sub TEST.txt](https://github.com/Microsoft/AL/files/1976121/Sub.TEST.txt)

**Comment by StanislawStempin** [comment]
You need to subscribe to the 'OnAfterGetDatabaseTableTriggerSetup' trigger first to let the system know that it should expect event subscribers for a given table. See my example above.

**Comment by MatthewMcCarthy7** [comment]
Thank you! That worked, This ticket can be closed.
