### ISSUE TITLE
Get and set is confusing in use

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#1418]
To me and to other colleagues the following thing seems confused for quite some time now and I hope therefore an improvement in the sense of cleancode and in addition with #228.

````CSharp
RecordRef.GetTable(example);
RecordRef.SetTable(example);
````
According to my education and the other standards is the expectation that you get a table back with GetTable and set a table with SetTable. It has always been the case in C/AL, but the Get sets the table of RecordRef and RecordRef. SetTable returns the table. That's actually a little bit upside down. Don't you think so?

**Comment by esbenk** [comment]
I don't disagree. We are not changing anything around this methods (right now) to be backwards compatibility. With some language/runtime enhancements we could maybe do better in a future version.

At least with VsCode you can get inline help when using intellisense.
