### ISSUE TITLE
Table data loss after extension republishing.

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#1419]
Hi all.
1) I've create a setup table with page and publish it on database (F5).
2) I create a new record in it with some values
3) I made a change in table in vscode and publish the extension again (F5)
4) My table gone empty after that (record has been delete)

Is it a normal? If yes - is there any way to save data? I know about install codeunit, but in this case - no way to fill default values on install.
Thanks in advance!

**Comment by thpeder** [comment]
Hi,
We have introduced a feature which lets you keep your data between publishes from VS Code.
It will be available in the January update.

**Comment by ABaludin** [comment]
Tenerife only or it'll be 2018 CU2 ?

**Comment by thpeder** [comment]
It is also part of CU2.
