### ISSUE TITLE
Source expression on page crashes the client

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#142]
I have tried to reverse the sign on a page field:

`field("Quantity Available";-"Quantity Available") {}   `

It compiles as expected, but crashes the Client:

> Message: Index was outside the bounds of the array. Logical Control: Name=29000810; Caption=Quantity Available Format Column Binder: 70070000_Inventory Availability.Control29000810_Format RowEntry Type: NavRowEntry Column 1: bookmark Column 2: 0 Column 3: 1 Column 4: 2 Column 5: 3 Column 6: 11 Column 7: 303 Column 8: 4 Column 9: 5 Column 10: 6 Column 11: 7 Column 12: 8 Column 13: 9 Column 14: 10 Column 15: 12 Column 16: 13 Column 17: 15 Column 18: 100 Column 19: 201 Column 20: 300 Column 21: 301 Column 22: 302 Column 23: 304 Column 24: 305 Column 25: 306 Column 26: 307 Column 27: 308 Column 28: 309 Column 29: 310 Column 30: 311 Column 31: 312 Column 32: 400 Column 33: 1000 Column 34: Control29000808_Format Column 35: Control29000810

**Comment by RafaelKoch** [comment]
`field("Quantity Available";abs("Quantity Available")) {}  `
does not work as well

**Comment by atoader** [comment]
Could you please post the minimum complete object that crashes the client?

**Comment by atoader** [comment]
I tried to reproduce the crash with the snippets you posted but everything worked as expected.

**Comment by RafaelKoch** [comment]
One thing to mention: we are using a temporary table. Maybe this helps.
The Extension we are developing contains IP, I cannot post it entirely and dumbing it down takes up time I do not have just right now. If You can point me to another way I can send you the project folder.

**Comment by atoader** [comment]
Feel free to contact me at altoader@microsoft.com .
