### ISSUE TITLE
Export Media in ZIP

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1421]
Hi everybody,

for V2 migration I need to export a Media in a ZIP File.
When I do a single export everything is okay (see code: `DownloadFromStream(MediaInStream, '', '', '', FileName);`). When do a export in a ZIP archive I am not able to open the media (in my case I have a png-file in my media field) (see code: `DownloadFromStream(BlobInStream,'Export','','',ZIPFileName);`).

Here is my example code. My ZIP code is surrounded with "Test Start / Stop" comments.
Can anybody help here?

![2018-01-15 13_53_17-d365onixappv2 3 - 40 71 204 16_3389 - remotedesktopverbindung](https://user-images.githubusercontent.com/14943914/34943331-8a72a218-f9fb-11e7-853f-b5c13a1885fa.png)

**Comment by DavidBastide** [comment]
Hi, 

I could repro the issue and fix it. It is an encoding issue with the streams. The fix will be included in upcoming Docker releases. 

To unblock you in the meantime, you can modify Codeunit 419 File Management: 
![image](https://user-images.githubusercontent.com/34068969/35334090-6c272136-0111-11e8-953b-4661047cb2d4.png)

Here is the code for easy copy/paste (but no formatting!):
    `[External]
    PROCEDURE AddStreamToZipStream@71(ZipStream@1000 : OutStream;StreamToAdd@1001 : InStream;PathInArchive@1002 : Text);
    VAR
      ZipArchiveLocal@1004 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchive";
      ZipArchiveEntry@1003 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchiveEntry";
      StreamReader@1005 : DotNet "'mscorlib'.System.IO.StreamReader";
      StreamWriter@1006 : DotNet "'mscorlib'.System.IO.StreamWriter";
      Encoding@1007 : DotNet "'mscorlib'.System.Text.Encoding";
    BEGIN
      ZipArchiveLocal := ZipArchiveLocal.ZipArchive(ZipStream,ZipArchiveMode.Update,TRUE);
      ZipArchiveEntry := ZipArchiveLocal.CreateEntry(PathInArchive);
      StreamReader := StreamReader.StreamReader(StreamToAdd,Encoding.Default);
      StreamWriter := StreamWriter.StreamWriter(ZipArchiveEntry.Open,StreamReader.CurrentEncoding);
      StreamWriter.Write(StreamReader.ReadToEnd);
      StreamWriter.Close;
      StreamReader.Close;
    END;`

Let me know if this solves your issue!
