### ISSUE TITLE
New Event request in table 337

### ISSUE THREAD

**Issue by Nagaraju17** [Microsoft/AL#1428]
As part of eventing , we have some customization for function "TextCaption" in table 337. It would be good if we have onAfterTextCaption event trigger in table 337. please do the needful.
![image](https://user-images.githubusercontent.com/30176345/35035400-3e564810-fb97-11e7-8b99-d0f2ef31bc28.png)

**Comment by NKarolak** [comment]
Then it would make sense to add the same type of event to T337.SummEntryNo as well.
