### ISSUE TITLE
Customizing the Dropdown Fieldgroup

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#143]
We often do modifications on standard NAV tables to provide more information on the dropdown when selecting master data (adding "description 2" field for table Item, adding "Enterprise No.", "Search Name" field for table Customer, ...), using the 'DropDown' fieldgroup.

How can this be achieved using table extentions? 
Would it be possible to add the fields to the dropdown using the in-client designer as well?

**Comment by StanislawStempin** [comment]
This is currently not supported. We will add support for it over the next few updates. 
There are currently no plans to support field groups in the in-client designer but we will consider it.

**Comment by vanacore** [comment]
any news of this feature?

**Comment by mortenseifert** [comment]
Agree, this is a very common request. Must be more running into the same issue. Please up-vote.

**Comment by svwfr** [comment]
Yes, we also often modify this part of code. I sign up for vote.

**Comment by thomasbook** [comment]
This is a common change made is the any updated on this?

**Comment by sigurpallviggo** [comment]
Still waiting for this feature. 

For me this is a must-have in table extensions, if the developer could just simply re-create the dropdown fieldgroup for said table.

**Comment by BenjaminHochstetter** [comment]
Please add this feature! We realy need it!

**Comment by StanislawStempin** [comment]
We will be starting to work on this feature in the near future. 

We are currently discussing the scope of the feature. Is it sufficient that we allow adding additional fields to an existing field group? We will not allow removing any fields nor adding duplicate fields. Also, at least in the first iteration, not allow changing the order of the fields in the group.

**Comment by fvet** [comment]
Just some related thoughts.

When reviewing the dropdown feature, maybe also consider sorting on any column without the need for a key, like available in normal list pages. Please also provide a shortcut Edit next to New and Advanced that allows direct navigation to the card page, to get more details on the selected record. And provide the same Edit shortcut via rightclick on any field that has a table relation... this will ease the navigation process a lot.

Another issue we face a lot is that table relations are often not sufficient for a more complex lookup, so the Onlookup is coded. This is gives another experience to the user, another page open instead of the in-page dropdown...

**Comment by fvet** [comment]
Some additional thoughts (from various key users that are used to do _fast_ data entry)

Suppose you have 2 customers that are named 'Van Terp A' and 'Van Terp B'. When users enter the value 'Van Terp' in the 'Customer No.' field and immediately presses Enter / TAB to the next field, an error occurs ('Van Terp' is not a valid customer no.). They need to have _patience_ for the dropdown list to load first, then select the correct customer and enter / TAB. This takes approx. 1 - 2 secs to load, which is too long for power users. 

Can this be enhanced so the error is not shown, but the dropdown is at least shown in case multiple records apply to the search query?

**Comment by StanislawStempin** [comment]
Thanks for the feedback. I should clarify that at this point we are only looking at the programming/extensibility model for field groups. Not at the client behavior of them or optimizing UX.
I will pass on the feedback to the owning team but let's keep this thread focused around AL.

**Comment by svwfr** [comment]
I look forwarded for this new feature. I am following up Fvet input about sorting extended columns as also searching is important to do. I.e., our customer use field "Item No. 2" as old no., and need the ability to search for that number from the sales line look up. To provide that, I had to add "Item No. 2" as an index key.

**Comment by fvet** [comment]
@StanislawStempin What's the best place to post and follow up these UX / application improvement requests and get the same quick feedback and solution as we get via Github? 👍  

MS Collaborate (seems to be limited to bugs for [Ready!] and Dynamics NAV feedback channel is quit silent) or via Dynamics Experience?

**Comment by StanislawStempin** [comment]
Here's what I received from the Client team:

•	Got a great idea or suggestion for Microsoft to add to Business Central? Post it to https://aka.ms/businesscentralideas and get the community to vote it up!
•	Customer impacted by an issue you've encountered? If you are a credited partner, just file a Support Request to Microsoft Support. Or if you are a customer, please engage with your partner.
•	If you've got feedback on pre-release versions of Business Central, discuss on Yammer or report defects to the Collaborate engagement.

**Comment by StanislawStempin** [comment]
It is now possible to extend field groups. See this blog post for more details:
https://blogs.msdn.microsoft.com/nav/2018/08/31/developer-preview-august-2018/

**Comment by RedFoxUA** [comment]
> It is now possible to extend field groups. See this blog post for more details:

It is still not possible for Table Extension!
