### ISSUE TITLE
Request new event publisher "OnAfterCopyFromInteractionLogEntry" on Table 5077

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#1432]
Please add new event publisher on table 5077.

EventName: OnAfterCopyFromInteractionLogEntry
FunctionName: CopyFromInteractLogEntry

Event signature: OnAfterCopyFromInteractionLogEntry(VAR Rec: Record 5077, VAR InteractionLogEntry: Record 5065)

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
