### ISSUE TITLE
Event request. Codeunit 6620 "Copy Document Mgt.", function CopySalesInvLinesToDoc

### ISSUE THREAD

**Issue by Veseljko** [Microsoft/AL#1434]
Hi,

Please provide new event which should be raised after copying each sales line buffer to sales line

![image](https://user-images.githubusercontent.com/35526474/35041032-40fc044a-fb7b-11e7-9b36-f3f300392b86.png)

**Comment by NKarolak** [comment]
Alredy here: #1369
