### ISSUE TITLE
Unable access the table from Extension

### ISSUE THREAD

**Issue by yukonn** [Microsoft/AL#1435]
Can someone explain why not able to access this two table from Extension.

> The type or method 'License Information' cannot be use for 'Extension' development.
> The type or method 'Table Information' cannot be use for 'Extension' development.

Our v1 extension used above two table, now cannot convert to V2. Any idea.

**Comment by dNsl9r** [comment]
Prohibited. How do you use these system tables in your extension?

**Comment by yukonn** [comment]
We read the company name from license information to get company name. Table information is part of table filter.

**Comment by atoader** [comment]
It took a really long time to get a response on this, but it looks like we won't be able to upon up these tables for extensions.
