### ISSUE TITLE
OnBeforeCalcDateBOC in Codeunit 7600, this can helps to change the source codes,OrgDate,

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/AL#1436]
Hi Team,

if we have Publisher like below,
OnBeforeCalcDateBOC(FirstCalCode,SecondCalCode,FirstSourceType,FirstSourceCode,FirstAddCode,SecondSourceType,SecondSourceCode,SecondAddCode);

Based on our requirment we can able to change the above data also we need the Var with Yes.

Also If we have OnAfterCalcDateBOC then it will also help full. :) 
![7600](https://user-images.githubusercontent.com/29703512/35042136-59da8f18-fbad-11e7-8908-a7988db55d2d.png)

Thanks!

Regards
srinivas

**Comment by AlexanderYakunin** [comment]
We don't have FirstCalCode or SecondCalCode in this codeunit. Seems you have customized codeunit, please rewrite your request for W1 codeunit.

**Comment by srinivasGangadhara** [comment]
i can see in standard cronus 2018 database, that is not customized variables, 
Please check below screen shots.
![7600-2](https://user-images.githubusercontent.com/29703512/35150965-7830d9c2-fd42-11e7-800d-e66523dbd1f8.png)

![7600-1](https://user-images.githubusercontent.com/29703512/35150972-7f31c3e4-fd42-11e7-82bb-551aeab01a3a.png)

**Comment by AlexanderYakunin** [comment]
Well, in this case it makes no sense to pass FirstCalCode and SecondCalCode to event as they are blank at this point. Please confirm specification of event you need, from my view it should be like this:

OnBeforeCalcDateBOC(FirstSourceType,FirstSourceCode,FirstAddCode,SecondSourceType,SecondSourceCode,SecondAddCode);

OR (if you want to alter calculation of FirstCalCode and SecondCalcCode) they should be passed to event by VAR and used value from event instead for date calculation below, right?

**Comment by srinivasGangadhara** [comment]
Yes, I want Like this only. After standard calculation we want to update the our calculation. as below is correct. 

> OR (if you want to alter calculation of FirstCalCode and SecondCalcCode) they should be passed to event by VAR and used value from event instead for date calculation below, right?

**Comment by srinivasGangadhara** [comment]
Hi,

Here we are missing one parameter to handled standard code.
Please also add that parameter OnBeforeCalcDateBOC(FirstCalCode,SecondCalCode,FirstSourceType,FirstSourceCode,FirstAddCode,SecondSourceType,SecondSourceCode,SecondAddCode,**CalConvTimeFrame**);

thanks!
srinivas
