### ISSUE TITLE
Table Field Properties

### ISSUE THREAD

**Issue by TomFranzen** [Microsoft/AL#1437]
Hi,
when will it be possible to alter properties of existing fields in tables, e.g. CalcFormula of a FlowField, Editable, DecimalPlaces?

**Comment by qutreson** [comment]
For now, we are not planning on enabling the modification of these properties from extensions.

**Comment by SirBETE** [comment]
@qutreson Any idea how we can work around it, especially the editable property?
Cause we need to add some code to validate of a certain field, but the users can't fill in any values due to editable = no ...
Other fields aren't allowed to be changed manually, but now you can due to editable = yes ...

**Comment by StanislawStempin** [comment]
Can you give a concrete example? Since the field is not editable can you instead use a new field from a table extension?

**Comment by TomFranzen** [comment]
Hi,

here is my concrete example:

-      I want to change the FlowField-Formula because I added a new FlowFilter in the actual table and a new filter criteria in the table below.

-      I want to add an additional DocumentType in an existing table


There is no help in creating a new field from an extension

Von: Stanislaw Stempin <notifications@github.com>
Gesendet: Donnerstag, 5. April 2018 17:35
An: Microsoft/AL <AL@noreply.github.com>
Cc: Thomas Franzen <Thomas.Franzen@agiles.de>; Author <author@noreply.github.com>
Betreff: Re: [Microsoft/AL] Table Field Properties (#1437)


Can you give a concrete example? Since the field is not editable can you instead use a new field from a table extension?
