### ISSUE TITLE
Question: Where is the Xml Reader?

### ISSUE THREAD

**Issue by Kraver88** [Microsoft/AL#1438]
Does anyone know how you can read xml files in Extensions? I want to use the Xml Buffer table but all these functions (and related codeunits) are blocked (see https://github.com/Microsoft/AL/issues/1425). So I thought I would write those functions myself in an extension.

However there doesn't seem to be an Xml Reader var that we can declare. Am I missing something? How do you guys read xml files (without xml port ofcourse)?

**Comment by HunterFeltman-MSFT** [comment]
The AL language has new types for manipulating/dealing with Xml (as well as other formats).

See this reading: [XmlDocument Class](https://docs.microsoft.com/en-us/dynamics-nav/developer/api/xmldocument-clas)

**Comment by Kraver88** [comment]
Thanks for the reference I did not know about that documentation. However it is still not clear for me how you can easily read through xml files without a reader. Maybe it's because I am not a C# Developer.

**Comment by Kraver88** [comment]
Okay I discovered how to do it. Heres a simple hardcoded example:
Xml example:
![image](https://user-images.githubusercontent.com/24684493/35108240-51698214-fc73-11e7-92a9-9991250488c5.png)

Code Example;
// Create Instream & upload file into it               
filename := 'test.xml';
filepath := 'C:\temp\';
UploadIntoStream('Window Title',filepath,'',filename,L_InStream);

// Read stream into new xml document        
Xmldocument.ReadFrom(L_InStream, TargetXmlDoc);

TargetXmlDoc.GetRoot(L_XmlElement);
//Message(format(L_XmlElement)); //Shows Entire Xml

TargetXmlDoc.SelectSingleNode('Store',L_XmlNode); //Takes Store Node and initiates L_XmlNode
L_XmlNode.SelectNodes('Product',L_XmlNodeList); //Takes all product Nodes and puts them in a list
//Message(Format(L_XmlNodeList.Count)); //shows 4
i := 1;
repeat
    L_XmlNodeList.Get(i,L_SingleXmlNode); //Takes each Product
    i +=1;
    //Message(Format(L_SingleXmlNode)); //Shows Every Product with its nodes
    L_SingleXmlNode.SelectNodes('Product_name',L_XmlNodeList2);
    L_XmlNodeList2.Get(1,L_SingleXmlNode);
    L_XmlElement := L_SingleXmlNode.AsXmlElement;
    Message(format(L_XmlElement.Name)); //Shows Product_name
    Message(format(L_XmlElement.InnerText)); //Shows Product1, Product2 etc
    
until i = L_XmlNodeList.Count;
