### ISSUE TITLE
When does AL Extensions for Visual Studio Code go out of preview?

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#144]
Hi all,
We are going to start two projects in NAV after two weeks. We have been doing different customizations in Visual Studio code since December after the preview had been released for testing purpose.
I want to know when does Visual Studio Code go out of preview? So that we can carry out these projects in Visual Studio Code.
Thank you.

**Comment by Gallimathias** [comment]
So Visual studio code as a tool itself exists since 2016 as a productive system ;). (Https://code.visualstudio.com/). If you mean the AL extension for VSC then only Microsoft itself can give you an answer. I would not expect an release before the release of Navision 2018, but then hopefully with very much force.

**Comment by TinaMenezes** [comment]
Hi @Gallimathias,
Thank you. Yes, I meant AL extensions for Visual Studio Code.

**Comment by stuartglasson** [comment]
We haven't formally announced when we're going to go out of preview.  

What I can say is that we're unlikely to go out of preview until we're more done.  Right now we still don't have a solution for all the objects - queries are being added now and menusuites are missing.  Plus we're still building more types to allow safe use of functionality that you used before with the .NET Interop type.

But it's getting closer :)

Thanks for following along and don't hesitate to ask if your project needs something that we haven't implemented yet.  We want suggestions to ensure your work is successful.

Thanks,
Stuart

**Comment by TinaMenezes** [comment]
Thank you @stuartglasson.
