### ISSUE TITLE
'JsonObject' does not contain a definition for 'RemoveAll' in new build (20186)

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1440]
We have acquired the new .app files and vsix from the newest build (20186). 

When opening our project in VS Code we get this error. 

![image](https://user-images.githubusercontent.com/32313731/35064432-4bd7cb4a-fb87-11e7-99ad-7404cb1ab090.png)

**Comment by qutreson** [comment]
We figured out that the behavior of the underlying library was bogus when using the methods JsonArray.RemoveAll and JsonObject.RemoveAll and we have then removed them. We advise now to use System.Clear which is more reliable instead.

**Comment by strophanthus** [comment]
Alright I will switch that up, thanks.
