### ISSUE TITLE
Standard events in NavReport or all reports

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#1441]
It would be a cool feature if in the NavReport and therefore for all reports standard events would be available or created.

**For NavReport:**

OnBeforInitReport 
OnBeforPreReport 
OnBeforPostReport 
OnAfterPostReport 

In addition, for all reports per data item or generalized for **all DataItems**.

OnPreDataItem 
OnAfterGetRecord 
OnPostDataItem  

I prefer the events would be generalized.

**Comment by qutreson** [comment]
It looks like a good idea. We don't have plan in order to support it for now, but we will take this into consideration for future improvements.

**Comment by qutreson** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
