### ISSUE TITLE
AL0124: The property 'UsageCategory' cannot be used in this context

### ISSUE THREAD

**Issue by Twija** [Microsoft/AL#1442]
Hi all,
i tried to add my page to search and i created a page following sample.
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-al-menusuite-functionality

however i got an error
Source%20Codes/Pages/simpletest.AL(5,5): error AL0124: The property 'UsageCategory' cannot be used in this context
Source%20Codes/Pages/simpletest.AL(6,5): error AL0124: The property 'AccessByPermission' cannot be used in this context
Source%20Codes/Pages/simpletest.AL(7,5): error AL0124: The property 'ApplicationArea' cannot be used in this context

i copied and pasted it. that's all i do.

alpackages version's here.
Microsoft_Application_11.0.19573.0.app
Microsoft_System_11.0.12925.0.app

**Comment by kalberes** [comment]
What is the version of your AL extension? If it the one that you download from within VsCode extensions , then that does not have yet the support for it.
You either have to use a version that is in our docker images from post December update, or NAV 2018

**Comment by Twija** [comment]
kalberes,

i use AL language extension for Dynamics 365 for Finance and Operations, Business edition. and version 0.11.14434

you mean i could not add pages or reports in the D365 BE.
then how could i add the menu in the D365 BE?

thanks in advance.

**Comment by kalberes** [comment]
That version does not support it. You will have to wait until a newer version is published to VSCode.
For now only the docker images >= December or Nav 2018 versions support this property.

**Comment by Twija** [comment]
thank you kalberes

i need to find a different way.
