### ISSUE TITLE
How to autogenerate the RDLC/Word layout?

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1447]
hello

I'm following the guide at 
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-howto-rdl-report-layout
to create a CustomerList.
However when I try to build the extension with this code:
```
report 50123 CustList
{
    DefaultLayout = RDLC;
    RDLCLayout = 'CustList.rdl';

}
```
The extension won't build and it gives the error: `Missing file 'CustList.rdl'`.

Do I have to specify in my app.json that VS Code has to generate the (empty) rdlc file (like it is with translations (`"features": "TranslationFile"`))?

Doesn't the rdlc file need to have the .rdlc extension (and not .rdl)?

Kind regards
SirBETE

**Comment by NKarolak** [comment]
.rdl is really correct.
http://www.cloudfronts.com/creation-reports-using-al-extension-microsoft-dynamcis-nav-development-preview/

**Comment by srenders** [comment]
It would seem, by reading the docs, that the rdl would be generated, but it's not. 
This is how you can create the layouts: http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/

**Comment by SirBETE** [comment]
Steven to the rescue!
Ty, I will definitly try your method.

Microsoft hasn't created an easier procedure in the past 5 months?
If Steven's method is (for now) the only viable option, then Microsoft should a) change the wording and refer to your method or b) get working on making their method possible ...

**Comment by thpeder** [comment]
For the next update or if you have access to the latest docker image, you will see that we generate the files on build if they are not found.

**Comment by SirBETE** [comment]
> For the next update or if you have access to the latest docker image, you will see that we generate the files on build if they are not found.
Excellent! :)

**Comment by dtacconi** [comment]
Thanks SirBete to contact CSS to receive an answer for NAV 2018 VSIX.

NAV Modern Development Team triaged this request and archived as “Feature Request” hence this is not a bug-fix for NAV 2018 VSIX but a brand new implementation that is currently supported for Dynamics 365 Business Central (D365BC) development and, as per latest statement of directions, will be added in the upcoming On Premise release VSIX (Fall 2018).

See below statement from Modern Dev team
…
This is a feature request. Per the standard process we won't be backporting it to NAV 2018. 
…
If you remember, NAV 2018 VSIX has been cut roughly in November 2017 and this new feature has been introduced in the February 2018 Developer Preview. 
See below
https://blogs.msdn.microsoft.com/nav/2018/02/15/nav-development-preview-february-update  
…
Report RDL and Word layout development with AL
We have enabled the scenario to develop RDL Report Layouts and Word Report Layouts by using the AL Extension and the editor for the files. Now, when you specify the path to the layout in the report, such as:
 
The extension will generate the .rdl file in the specified path. The scenarios are the same for both RDL and Word development. You specify the file and it is created. You make changes to the file in Word or SQL Server Report Builder, or you change the dataset in AL code and the layout files stay in sync with the AL extension. You can use the already existing RDL and Word files which you export from your codebase and use with this new development scenario.
…
