### ISSUE TITLE
Cannot use the object table as a variable in code

### ISSUE THREAD

**Issue by StijnMattheus** [Microsoft/AL#1448]
When i want to use the object table as a variable like this:

 LRec_Object: record Object;

the compiler gives the following error:

error AL0296: The type or method 'Object' cannot be used for 'Extension' development.

**Comment by SirBETE** [comment]
You have to use AllObjWithCaption table.

**Comment by dennisfrostlander** [comment]
Hi @StijnMattheus, 

Certain system tables (like Object) are not allowed in extensions. The rationale is that these tables either expose cross-tenant data (which cannot happen in online multi-tenant environment) or they are for internal use.

You should try using AllObjWithCaption as @SirBETE suggests. If it does not work, you can change the "target" setting in app.json by setting it to "Internal". However, please note that this is generally discouraged and you will not be able to distribute your extension through AppSource.
