### ISSUE TITLE
HTML-Reports

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#145]
I would like to throw something as thoughts into the virtual space. Could it possibly be interesting to replace the old cumbersome RDLC reports with new nice HTML reports. Especially under the aspect that the tools in VSC for HTML are significantly more comfortable. Apart from that, there is no VSC tool for RDLC.

**Comment by pborring** [comment]
I am going to close this rather old feedback item, and propose opening an idea on http://aka.ms/bcideas to track this instead, as not related specifically to the developer tools, but the reporting story.

**Comment by Gallimathias** [comment]
@pborring I find it sad when my ideas are simply closed because some of them have been added to the project over time.

However, I do not have the muse to transfer this to this other platform as I have left the Navision world in the meantime.
