### ISSUE TITLE
Report extendibility

### ISSUE THREAD

**Issue by gudrunleos** [microsoft/AL#1452]
Hi.

As mentioned by @DanKinsella in issue #805 it would be very much appreciated to be able to extend some reports, especially the Sales Document reports (1302..1307).

The reason is simple: If we are extending the underlying tables (110..115) it is most likely that we need to add some information to the printouts. Since the layout of those reports have been separated from the report code, the only thing we need is to get our data into the reports dataset and from there being able to deploy a new layout for the report making sure that all runtime calculations are correct at any time and the same as in the standard reports.

**Comment by StanislawStempin** [comment]
Report extensibility is on our backlog. I will change this issue to a Suggestion for tracking purposes.

**Comment by logandersen** [comment]
Hi @StanislawStempin until we have report extensibility, is there a way to copy the al code for an existing out of the box report or do I need to guess what the dataset query looks like to create a copy?

**Comment by gudrunleos** [comment]
Any news on this issue?

**Comment by hendrik244** [comment]
Are there any news on this issue? @StanislawStempin

**Comment by LauraNicolas** [comment]
Hello @logandersen ,

Regarding your question:

> is there a way to copy the al code for an existing out of the box report

I use the **txt2al tool** to obtain an AL version of a C/AL report.

Salut!
Laura Nicolàs

**Comment by toonsevrin** [comment]
"Report extensibility is high on our priority list" - 1 year ago
Yeah, right...

**Comment by gudrunleos** [comment]
It's been a year and 9 months now, any news on this?

**Comment by pborring** [comment]
We are tracking report extensibility in below idea, and have continued implementing support for 2021 Wave 1 (we actually did start on this a year ago), so unless unforeseen issues arise this time, there should finally be support for extending report dataset and/or request page, as well as add layouts (but layouts are still "blobs" without granular extensibility).
https://experience.dynamics.com/ideas/idea/?ideaid=33aff58b-8fab-e811-b96f-0003ff68aa60

We are not done with the work yet, but you should already be able to play with the first iteration of the report extension object model (there is no runtime support yet) using the v18/2021W1 insider container/artifacts 
![image](https://user-images.githubusercontent.com/28434210/100234255-18235500-2f2b-11eb-8c69-76af109eb1cf.png)

Given above and idea tracking this, I will close this GitHub entry

**Comment by rstefanetti** [comment]
Great!

**Comment by gdrenteriag** [comment]
Muy útil
