### ISSUE TITLE
ControlAddIn does not start

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1454]
Hi everybody,

we use a ControlAddIn to show an html Editor (https://quilljs.com/).
I can open the Page with the ControlAddIn but the AddIn does not appear.

Can anyone help?

**ControllAddIn**
![2018-01-19 controladdin](https://user-images.githubusercontent.com/14943914/35150772-ee886256-fd1b-11e7-9024-a994e088e5c7.png)

**Page**
![2018-01-19 page](https://user-images.githubusercontent.com/14943914/35150812-180b7b2c-fd1c-11e7-8a60-3891828d702d.png)

**JS ControlAddIn**
![2018-01-19 controladdin js](https://user-images.githubusercontent.com/14943914/35150822-272a5222-fd1c-11e7-840a-2f56876a5cbc.png)

**Comment by jiwanovski87** [comment]
One Addition:
I already tried to make the ControlAddIn.js as StartupScript in ControlAddIn.

**Comment by DavideVD** [comment]
Hi jiwanovski87, I am not an expert, but in my small experience in the new environment,  I noticed the StartupScript is necessary (maybe i am wrong). Try to slipt the script above JS ControlAddIn in 2, putting the document.ready part in the new startupscript

**Comment by Gallimathias** [comment]
You must use the StartScript property in the Control Addin. If it still doesn't work then the error message from your browser is also interesting. Try it once with a simple hello world after the document has finished loading.

Then the following note may also be decisive:

document. onready = When the HTML document has finished loading without external scripts
window. onload = When everything has loaded incl. scripts

;)

**Comment by jiwanovski87** [comment]
Hi guys,

I tested different szenarios. 
My new controlAddin should just raise an event in NAV.

![controlstartup](https://user-images.githubusercontent.com/14943914/35196978-b8e104fe-fed9-11e7-9864-4413b1c9f0e9.png)

When I try to use one of the following function I receive this error message in browser inspect:
- document.load
- document.onload
- document.ready
- document onready

![2018-01-21 event documentonready](https://user-images.githubusercontent.com/14943914/35197000-06b7085e-feda-11e7-83b7-a91fa6440cbd.png)

When I try to use one of these functions with: $(document).ready then I receive this error message in browser inspect:
![2018-01-21 event documentready2](https://user-images.githubusercontent.com/14943914/35197006-2cf119d8-feda-11e7-95a7-2e2a4303d024.png)

When I add an simple Button and raise the event with button.onclick everything is okay and my event is raised.

For our ControlAddIn we need the document.onready / document.ready function....

**Comment by Gallimathias** [comment]
hups sorry I just see the document.onready seems to be no native js event. I didn't seem to be paying attention at my last answer.

You cannot use onready and $ because you don't have a jquery at this time. Either because it's not loaded or because you're not pulling it out of the net.

Your button uses its own event. Until now, however, everything is already there in the slow human abilities.

This example should work:

````JS
       document.load = function () {
		alert('Document.load');
	};
	window.onload = function () {
		alert('Window.Onload');
	};
````

**Comment by Gallimathias** [comment]
Or try this to check if jquery is loaded

````JS
window.onload = function() {
    if (window.jQuery) {  
        alert("jQuery is ready to use");
    } else {
        alert("jQuery is not exist");
    }
}
````

**Comment by thpeder** [comment]
Can you try adding ControlAddIn.Js to StartupScript and don't have any @(document).ready or window/document.onload, just call your function.

**Comment by jiwanovski87** [comment]
So I tested your suggestions.
When I try to use something like document.load / window.onload I don't receive any alert / message. 
In browser inspect I cannot see any error. I don't know what happens here.

When I just call my event in ConrtolStartup.js (`Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("ControlReady", []);`) my ControlAddIn starts.

What I ascertained is that it is very important to fill the ApplicationArea property for the usercontrol. If you do not have this the usercontroladdin will not start too. 

I would appreciate that this property should be checked by AL language compiler if this is a required property for usercontrol.

![2018-01-22 applicationarea](https://user-images.githubusercontent.com/14943914/35214838-c5361968-ff62-11e7-9a5d-aa9180fecb62.png)

Thank you for your help guys!

**Comment by jiwanovski87** [comment]
Hey guys,

I have another problem now. And it seems to depent on my ControlAddIn.
When I press F5 to start debugging everything is okay. After authentification VS code loses the connection to the browser (Chrome and IE) and the Debug Console in VS Code shows the Message "Error: Not an application method."

Anyone an idea?

**Comment by jiwanovski87** [comment]
Another strange behaviour: 
When I open the page of the ControlAddIn I am not able to close the page. Neither with the standard X nor with a seperate Close button. When I comment out the ControlAddIn Part I can close the page.

**Comment by Gallimathias** [comment]
Please create a new issue. This makes it easier for everyone to find the same mistake.

**Comment by StanislawStempin** [comment]
We consider the issue to be fixed. Please log new cases for other issues.
