### ISSUE TITLE
When clicking F7 in VSCode the wrong object is pulled

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1457]
When pressing F7 in VSCode after deploying my extension with F6 (and not changed anyhthing) the wrong data is pulled from the server.
I have a simple extension that extends the User Setup table and page. When pushing F7 it updates the page extension .al file with the table extension.

I have attached the two .al objects. And just for completeness also the app.json.

I am running this on NAV 2018 RTM.

[UserSetupExtension.zip](https://github.com/Microsoft/AL/files/1647229/UserSetupExtension.zip)

**Comment by qutreson** [comment]
When pulling the source code it incorrectly only checks if the name matches of the objects pulled compared to the ones you have in the editor.
This is obviously a bug but you can get around it for now by having different names for your objects.

**Comment by lvanvugt** [comment]
Thanx @qutreson. Clear, but shouldn't F7 only pull page(extension) object from the service tier anyway?

**Comment by thpeder** [comment]
F7 at the moment pulls down the extension and merges all the AL code into your project VSCode, but your expectations of only pulling down the page(extension/customization) objects is an optimization we will investigate some more.
Thanks.
