### ISSUE TITLE
Error while Publishing (F5) app

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1459]
Error: An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.

[2018-01-19 12:44:01.94] Error: An internal error has occurred

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond x.x.x.x:7049

what could be the reason?

**Comment by thpeder** [comment]
If you are using the docker image then you need to install the self-signed certificate, or you can disable the use of ssl with -e UseSSL=N.

**Comment by pmohanakrishna** [comment]
I am using devpreview via azure vm

**Comment by pmohanakrishna** [comment]
seems Service Instance was not running. after starting service working fine.
error message should be clear to understand.
