### ISSUE TITLE
Control AddIns

### ISSUE THREAD

**Issue by PeterSchade1306** [Microsoft/AL#146]
Hello,
is there a way to adding JavaScript control add-ins by VS Code?
In the properties of the page fields I can't find the property "ControlAddIn".

How is it possible to add JavaScript control add-ins?

Thanks!
Peter

**Comment by Gallimathias** [comment]
Here is a similar question with a valid answer: #124

**Comment by RafaelKoch** [comment]
Hi,
this question is not referring to the use of .NET. We know this will only be supported on-premise, thank You.

We want to implement cloud friendly JavaScript. Today this means You have to write a .NET DLL and only need this in the development environment to generate Interface triggers on i.e. a page. Then you can access the JS control add-in triggers and functions to communicate between NAV and the add-in.
This means you only need the .NET DLL for publishing the add-in interfaces in the development environment - but not at runtime.

Perhaps, somebody from Microsoft can help us?

**Comment by kalberes** [comment]
We do not yet support JavaScript client control add-ins. It is in our plans though, but we do not have an exact date for when it is going to be delivered. 

Thanks
Kalman
