### ISSUE TITLE
Strange behaviour because of Trigger OnQueryClosePage

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1460]
Hey guys,

After finishing issue 1454 I get another problem. It seems to depent on my ControlAddIn (see issue 1454). When I press F5 to start debugging everything is okay. After authentification, VS code loses the connection to the browser (Chrome and IE) and the Debug Console in VS Code shows the Message "Error: Not an application method."

Another strange behaviour:
When I open the page of the ControlAddIn I am not able to close the page. Neither with the standard X nor with a seperate Close button. When I comment out the ControlAddIn Part I can close the page

Anyone an idea?

**Comment by thpeder** [comment]
Related to the first problem: "Error: Not an application method." Could you check if you have any breakpoints in VSCode and if any of them is causing the error.

You should be able to change the page in the client when you have a control AddIn, but It is hard to know what the exact problem is, so if you could give us a repro of the problem.

**Comment by jiwanovski87** [comment]
Okay I know how you can reproduce this error.
You just need a page (PageType: NavigatePage; I am not sure if it is only this PageType) and integrate a trigger OnQueryClosePage. 

The page which hosts the ControlAddIn needs this trigger to ask the user if he wants to save an html Text.

When I comment out this trigger I still can close the Page with the X.
When the trigger OnQueryClosePage is in the page I cannot close the page.

**Comment by thpeder** [comment]
You might be seen the same bug as in #1155. The default value for the trigger OnQueryClosePage should have been true but we have a bug which have it as false.

Could you try explicitly exit with true and see if it is the same bug.

**Comment by jiwanovski87** [comment]
@thpeder When I add an `EXIT(true);` at the end of the trigger everything is okay.
See my change:

![2018-01-22 trigger onqueryclosepage](https://user-images.githubusercontent.com/14943914/35229711-5eda7b00-ff94-11e7-94dd-23e81401c2c0.png)

**Comment by thpeder** [comment]
Then it is most likely the same bug.
Thanks for verifying it for me.
