### ISSUE TITLE
Unsupported feature: Change Visible on xxx

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1463]
we modified visible property to false for some standard fields and actions in our app.
txt2all didnt convert them and added below text in every place.
//Unsupported feature: Change Visible on xx. Please convert manually.

Is it going to same or will you convert properly in future releases?

**Comment by qutreson** [comment]
Modifying the property Visible is allowed from extensions, the converter shouldn't give a warning comment here and should have converted the property. For now you can just remove the comments and write manually the property, but there is then a bug here that will be fixed in the future releases.
