### ISSUE TITLE
Unable to read data from the transport connection

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1465]
Package is created and able to publish app till few minutes back.
suddenly getting this error
what could be the reason?

[2018-01-22 15:40:58.65] Error: An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a send.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host

[2018-01-22 15:40:58.66] Error: An internal error has occurred

**Comment by thpeder** [comment]
Could you provide some more context.
What is your environment? Azure VM or Docker. What version are you using?
Which actions led to this error message?

**Comment by pmohanakrishna** [comment]
azure vm
anniversary update build
while publishing.

**Comment by thpeder** [comment]
If you could please give us some repro steps otherwise we have a very hard time narrowing down the problem you are facing.
