### ISSUE TITLE
docker 20258 CA build issue.

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/AL#1466]
Using navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finca

We're not able to get the latest docker build 20258 running.
The problem seems related to permissions with SQL.

From the docker scripts:

Initializing...
Starting Container
Hostname is navserver
PublicDnsName is ( _Note: have removed this )_
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint _( Note: have removed this )_
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user admin
Creating Host Windows user
Enabling SA
Creating NAV user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 1
at <ScriptBlock>, C:\Run\navstart.ps1: line 153
at <ScriptBlock>, C:\Run\start.ps1: line 98
at <ScriptBlock>, <No file>: line 1

TimeGenerated : 1/22/2018 7:21:26 PM
EntryType     : Error
Message       : Server instance: NAV
                <ii>Cannot establish a connection to the SQL Server/Database.
                
                This could be due to one of the following reasons:
                
                * SQL Server is not started.
                * The database does not exist.
                * Proper permissions have not been given to the NAV Server 
                Account.
                
                Try again later or contact your system administrator.</ii>

TimeGenerated : 1/22/2018 7:21:26 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
                Remappable: True
                ErrorCode: 22924076
                ErrorNumber: 52012
                ModuleNumber: 93
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>Cannot establish a connection to the SQL Server/Database.
                  
                  This could be due to one of the following reasons:
                  
                  * SQL Server is not started.
                  * The database does not exist.
                  * Proper permissions have not been given to the NAV Server 
                Account.
                  
                  Try again later or contact your system administrator.</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.OpenCon
                nectionIfNeeded()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope.Ac
                quireSqlConnectionFromPool(NavDatabase database, Boolean 
                requireExclusiveConnection, TransactionType transactionType, 
                NavSqlConnection lastUsedSqlConnection)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope..c
                tor(NavDatabase database, Boolean requireNewConnection, 
                TransactionType transactionType, Boolean tryReuseConnection, 
                NavSqlConnection lastUsedSqlConnection, Boolean 
                requireExclusiveConnection)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope.Cr
                eate(NavDatabase database, TransactionType transactionType)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlMetadataCommands.T
                ableExists(NavDatabase database, String tableName)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .ReadDatabaseVersionNo()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .CheckDatabaseVersion()
                     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnec
                tion(Int32 attemptCount)
                Source: Microsoft.Dynamics.Nav.Ncl
                HResult: -2146233088
                </ii>

TimeGenerated : 1/22/2018 7:21:26 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant: nav-systemapplication
                <ii>Tenant ID: nav-systemapplication
                The connection to SQL server could not be established
                Database server: LOCALHOST\SQLEXPRESS
                Database name: FinancialsCA.</ii>

TimeGenerated : 1/22/2018 7:21:37 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: System.IO.IOException
                Message:
                  <ii>There are no more files.
                  </ii>
                StackTrace:
                     at System.IO.__Error.WinIOError(Int32 errorCode, String 
                maybeFullPath)
                     at System.IO.Directory.DeleteHelper(String fullPath, 
                String userPath, Boolean recursive, Boolean 
                throwOnTopLevelDirectoryNotFound)
                     at System.IO.Directory.Delete(String fullPath, String 
                userPath, Boolean recursive, Boolean checkHost)
                     at Microsoft.Dynamics.Nav.Runtime.TempPathHelper.RemovePat
                h(String path)
                Source: mscorlib
                HResult: -2147024878
                </ii>

TimeGenerated : 1/22/2018 7:21:37 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: System.IO.IOException
                Message:
                  <ii>There are no more files.
                  </ii>
                StackTrace:
                     at System.IO.Directory.DeleteHelper(String fullPath, 
                String userPath, Boolean recursive, Boolean 
                throwOnTopLevelDirectoryNotFound)
                     at System.IO.Directory.Delete(String fullPath, String 
                userPath, Boolean recursive, Boolean checkHost)
                     at Microsoft.Dynamics.Nav.Runtime.TempPathHelper.RemovePat
                h(String path)
                Source: mscorlib
                HResult: -2147024878
                </ii>

**Comment by yukonn** [comment]
You can submit all related docker issue at https://github.com/Microsoft/nav-docker/issues

**Comment by coffeecup007** [comment]
Neat!   We didn't realize this existed.
Looks like several other people found the same issue and it's being worked on (https://github.com/Microsoft/nav-docker/issues/153)

**Comment by yukonn** [comment]
Yes! They are fixing the issue.
