### ISSUE TITLE
CU1001 Job Post-Line --> PostInvoiceContractLine() function

### ISSUE THREAD

**Issue by AdilNowsherwan** [Microsoft/AL#1467]
Need a Integration Event for this method

Business use case is to be able to update the funding amount (custom feature) after a job planning line is invoiced.

**Comment by AlexanderYakunin** [comment]
Please be specific and provide event place and definition

**Comment by AdilNowsherwan** [comment]
The event is needed at the end of the method. Below snippet shows the current custom code placement, tagged as M008.0.0

JobPlanningLine.UpdateQtyToInvoice;
JobPlanningLine.MODIFY;
_JobFundingMgr.UpdateFundingLimits(JobPlanningLine);            //M008.0.0
JobFundingMgr.RemoveTrackingLinesPosted(JobPlanningLine); //M008.0.0_

IF JobPlanningLine.Type <> JobPlanningLine.Type::Text THEN
  PostJobOnSalesLine(JobPlanningLine,SalesHeader,SalesLine,EntryType::Sale);
