### ISSUE TITLE
New Event request in CodeUnit 7302

### ISSUE THREAD

**Issue by Nagaraju17** [Microsoft/AL#1470]
As part of eventing , we have some customization for function "ShowSourceDocLine" in CodeUnit 7302. It would be good if we have "OnAfterShowSourceDocLine" event trigger in Code Unit 7302.

![image](https://user-images.githubusercontent.com/30176345/35269398-dca56fb4-0051-11e8-88b8-f07faf466b97.png)

Thanks in Advance
Nagaraju

**Comment by AlexanderYakunin** [comment]
I would suggest you simply create you own extension code to show source docs from your extra tables, it can be easier than using event here.
