### ISSUE TITLE
error AL0275: Reference to symbol 'Jobs' is ambiguous.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1472]
Modifying Job Project manager RC page as below and getting this error

error AL0275: Reference to symbol 'Jobs' is ambiguous.
Error: The package could not be created.

pageextension 50140 pageextensionJobPMRC extends "Job Project Manager RC" 
{

    actions
    {

        modify(Jobs)
        {
            Visible = false;
        }
    
    }

}

**Comment by qutreson** [comment]
I tried it and couldn't it reproduce the error. Do you have other files in your extension that also have errors? Was this file created using the txt2al converter?

**Comment by pmohanakrishna** [comment]
I tried it in hello world folder.
build 20258
no other files with errors

**Comment by qutreson** [comment]
I can actually reproduce it now, we will have a look into it.

**Comment by pmohanakrishna** [comment]
in which build can we expect solution for this?
