### ISSUE TITLE
Foreach on Unknown JSONObject

### ISSUE THREAD

**Issue by DennisReinecke** [Microsoft/AL#1473]
Hey,

at the moment it is not possible to dynamically access values stored in a JsonObject. 
I would like to loop through the Object in a for each and access the JSONToken/JSONValue. 
This would allow parsing JSON responses with varying structures, as they are often returned by 3rd party APIs. To be able to correctly handle the JsonObject, it would also be helpful to be able to access the Key of a certain JSONToken/JSONValue.

Best 
Dennis

`codeunit 50098 JSONTEST
{
    trigger OnRun();
    var 
        JObject: JsonObject;
    begin
        JObject.Add('foo', 'bar');
        HandleUnknownJson(JObject);
    end;
    procedure HandleUnknownJson(var JObject: JsonObject);
    var
        JToken: JsonToken;
        JValue: JsonValue;
    begin
        foreach JToken in JObject Do begin
            if JToken.IsValue then begin
                JValue := JToken.AsValue;
                Message('JSON Value %1:%2', JValue.Key, JValue.AsText); 
                // or
                Message('JSON Value %1:%2', JToken.Key, JValue.AsText); 
                // or
                Message('JSON Value %1:%2', FINDLASTVALUEOFPATH(JValue.Path), JValue.AsText); 
                //Do some Stuff with Key => Value
            end else if JToken.IsArray then begin
                //handle array...
            end else if JToken.IsObject then begin 
                //handle object recursive...
            end;
        end;
    end;
}`

**Comment by thpeder** [comment]
Hey, 
We have added the ability to get all the keys from a JsonObject which will be available in the next update.
I hope that will be sufficient for you to solve your problem.

**Comment by DennisReinecke** [comment]
Thanks. It's implemented in 11.0.20630.

I do not like the Intellisense
`JsonObject."Keys"()`
I think it would make more sense to rename it to "JsonObject.GetKeys()" if you don't want to use the reservered word 'Keys'

**Comment by StanislawStempin** [comment]
I logged a new issue based on your last comment. Closing this one since it was fixed and delivered.
