### ISSUE TITLE
OnBeforePostCommitSalesDoc integration event (COD80) needs a signature change

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1475]
Currently this integration event in codeunit 80 has the following signature

LOCAL [IntegrationEvent] OnBeforePostCommitSalesDoc(VAR SalesHeader : Record "Sales Header";VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line";PreviewMode : Boolean;ModifyHeader : Boolean)

The last parameter needs to be _by reference_ allowing us to set this variable and influence the standard flow and trigger the COMMIT in the following standard code snippet:

  IF NOT PreviewMode AND ModifyHeader THEN BEGIN
    MODIFY;
    COMMIT;
  END;

**Comment by lvanvugt** [comment]
@thpeder I would like to extend this request as we have issues when updating sales lines in OnBeforePostCommitSalesDoc. This due to the fact that COD80 makes use of the TempSalesLineGlobal and SalesLine variables to be able to update lines before posting and not update them in the database (yet).

To be able to change Sales Lines in OnBeforePostCommitSalesDoc **TempSalesLineGlobal** and **SalesLine** need to synced before my subscriber to OnBeforePostCommitSalesDoc  is ended. Therefor TempSalesLineGlobal needs to be added as a _by reference_ parameter

LOCAL [IntegrationEvent] OnBeforePostCommitSalesDoc(VAR SalesHeader : Record "Sales Header";VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line";PreviewMode : Boolean;VAR ModifyHeader : Boolean;**VAR TempSalesLineGlobal : TEMPORARY Record "Sales Line"**)

And with that I should be able to access the function _RefreshTempLines_ in COD80, which is now local so should become global.

Note that this specific issue has been discussed on Yammer. If you want I can share the link here (not sure if that's "allowed").

**Comment by thpeder** [comment]
@lvanvugt If you wouldn't mind, could you please a create a new Issue with your request.

**Comment by lvanvugt** [comment]
@thpeder sure, no problem. That was my initial thought, to be honest.
