### ISSUE TITLE
Event Request ignored or not processed?

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1476]
I submitted a few events some time ago, but they were neither marked as "eventrequest" nor edited in any way. Furthermore, I don't even get an answer as to how things stand. So I can't even make amendments because there is simply no response. It is about the following issues:

#1352 #1008 

Somebody ever care about that? I would like to have a feedback whether something is happening or not. But I find it very bad not to react at all. Other much younger event requests are already being implemented, and delivery for the January stand marked. I don't really think this is fair, because the old event requests are simply ignored.

**Comment by esbenk** [comment]
Not marking #1352 as an event-request is clear a miss from our side. It is now marked correctly.

I have posted a reply on #1008 which is a different type of request.

**Comment by FSharpCSharp** [comment]
Thank you for all the detailed answers. Of course, I am aware of the fact that, in view of the large number of enquiries, it can happen again and again that certain points come underneath the table. The point has now been marked as an event request, so everything should be clear. I have only opened this point out of pure desperation, as the processing of the inquiries has been carried out at a completely different pace so far. And it was at this very point that this was overlooked. But let's forget about all of this, it's been cleared up!
