### ISSUE TITLE
Auto formatted decimal fields still limited to 2 decimal places (build 20258)

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#1478]
I'm using build 20258 and there are still some fields that are limited to 2 decimal places. Seems to be that fields where I specifically use the DecimalPlaces property are ok, but fields where I just use the AutoFormatType are still an issue.

See below:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/5204734/35281892-0b432df0-0022-11e8-8253-4c3ea5dc41a1.png">

The Quantity field is ok, but the Unit Cost field still is limited to 2 decimal places. Field definitions are below:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/5204734/35281932-2e39bf72-0022-11e8-9d2c-aafb180081db.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/5204734/35281954-4298f4a6-0022-11e8-85b1-54ce5ea2b833.png">

**Comment by StanislawStempin** [comment]
We are looking into it.

**Comment by DominikDitoIvosevic** [comment]
Hi @MikeGlue . Are you sure you are expecting the right behaviour?
https://msdn.microsoft.com/en-us/library/dd338607.aspx 
The AutoFormatType is intended to be accompanied with the AutoFormatExpression property. The AutoFormatType property specifies the type of the formatting (values 0,1 or 2) and then the AutoFormatExpression should provide the formatting string.

Are you saying you expect specifying "2" for AutoFormatType should empose 2 decimal places?
Usually if you think there is a bug with v2, it's good to check with CSIDE that it does as you would expect

**Comment by MikeGlue** [comment]
Yes I am aware of the behaviour of these fields. This is code that was working in my v1 extension and stopped working when converted to v2. I'm using **AutoFormatType = 2** with an empty AutoFormatExpr, as per the documentation below.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/5204734/35683443-f21aaecc-0731-11e8-8911-86bcfac4e4ca.png">

In C/Side you can see a working example of this if you look at the **Unit Cost (LCY)** field in the Sales Line table.

**Comment by DominikDitoIvosevic** [comment]
Thank you for clearing this up for me. I've found the missing piece and I'll be working on getting it in.
