### ISSUE TITLE
Error building a sulution with notifications

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#148]
We are trying to build a solution that uses a notification but we cannot get it to compile. Are we doing it wrong or is it not supported yet?

![notificationerror](https://cloud.githubusercontent.com/assets/25029667/25135140/d3bf5a4a-2451-11e7-8142-cfe640fdd523.png)

**Comment by esbenk** [comment]
It is a bug. Remove the first line in the method 'CLEAR(InventoryAvailSetupNotification)'. That should fix the problem.

In this case the Clear call is redundant, since the variable is initially clear.
