### ISSUE TITLE
Text.Split - Cannot convert from 'char' to 'string'

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#1480]
Text datatype function split cannot handle char returned from a dependent object as separator.
_TextList := TextVar.Split(DependentObject.GetDataSeparator)_ fails with the following error message when publishing the extension. 

[2018-01-23 15:50:40.26] The request for path /DynamicsNav110/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$DynamicsNAV110\source\Codeunit\Group40390e0fa7f3acc7037d972e15969206_Codeunit50200.cs(86,109) : error CS0030: Cannot convert type 'string' to 'char'
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$DynamicsNAV110\source\Codeunit\Group40390e0fa7f3acc7037d972e15969206_Codeunit50200.cs(86,97) : error CS1502: The best overloaded method match for 'Microsoft.Dynamics.Nav.Runtime.NavText.NavText(string)' has some invalid arguments
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$DynamicsNAV110\source\Codeunit\Group40390e0fa7f3acc7037d972e15969206_Codeunit50200.cs(86,110) : error CS1503: Argument 1: cannot convert from 'char' to 'string'

**Comment by thpeder** [comment]
I can't reproduce the error, so we might have fixed it. What version are you running on?

My Code is
codeunit 50000 TestingCodeUnit
{
    procedure RunTest()
    var
        txt : Text;
        splitted : list of [Text];
        dp : codeunit DependentObject;
    begin
        txt := 'Alpha::Bravo::Charlie';
        splitted := txt.Split(dp.GetSeperator);
    end;
}
codeunit 50001 DependentObject
{
    procedure GetSeperator():Text
    begin
        exit('::');
    end;
}

**Comment by Joel-NAVDev** [comment]
AL Compiler version 0.14.16446

The GetSeparator() resides in the dependent extension, this is key and it returns a char.
