### ISSUE TITLE
Wrong results filtering "Field" table

### ISSUE THREAD

**Issue by AcererakTheLich** [Microsoft/AL#1481]
Hi,

I encounter wrong results while filtering table "Field" with Setrange or Setfilter, and I did not found existing issues about this. I am using local NAV 2018 W1 cu1 Cronus (11.0.19846) and VS Code 0.12.15898

Purpose was to filter "Field" table on "Type" field to show only "Option" or "Boolean" fields to select.
However, to reproduce easily I used only lines below (I also tried Setfilter and even an If equal  loop).
Developed in NAV environment (behind a button action trigger) result seems ok, at least I have a message about 2020 records:
Same code at same place published as an extension return 0 records.

Variable declaration : 
RecLTable	Record	Field	

Code :
RecLTable.SETRANGE(Type,RecLTable.Type::Option);
MESSAGE(FORMAT(RecLTable.COUNT));                    

Regards

**Comment by thpeder** [comment]
Hi @AcererakTheLich, you ran into the same problem as #1365. We are working on a solution to it.
There is a workaround, if you use the ordinal value of the option members instead. 
So for your example to need
35583: Option
34047: Boolean

**Comment by AcererakTheLich** [comment]
Thank you, workaround works fine except in Case statement.

case MyRec.Myfield of
  35583:
  ...
return a 'Constant value '35583' is outside of the valid ordinal range for this option type'
We needed to use a "case true of" with a "MyRec.Myfield = 35583" instead.
