### ISSUE TITLE
New 2 Events for codeunit 80

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/AL#1482]
1) 1)	With in function FillInvoicePostingBuffer Line number 1429 (Place where we have BSSISubSalesAmount)  - The reason why we need that trigger is because we need to modify Local variable - TotalAmount,TotalAmountACY which contains line amount. We need the trigger In that exact place because we let NAV get the sales line amount and modify it.

![event 1](https://user-images.githubusercontent.com/22604702/35290299-b7ff20aa-0061-11e8-85a6-dc81dcf69882.png)

2)	With in function FillInvoicePostingBuffer Line number 1463 (Place where we have BSSIUpdateDefferedAmt)  - The reason why we need that trigger is because we need to create new line in JE to update the deferred account & rounding account. We need the trigger In that exact place 

![event 2](https://user-images.githubusercontent.com/22604702/35290416-165e07ec-0062-11e8-8d8c-b8ff68b20ee5.png)

**Comment by AlexanderYakunin** [comment]
I have a questions about second ask. If you update deferral amounts, should your event be part of FillDeferralPostingBuffer call one line below?

**Comment by SergioKelly** [comment]
Hi Alexander,
Yes, we can move the event at the end of FillInvoicePostingBuffer

[cid:image002.jpg@01D39924.3632AF00]

Thx.

[http://binarystream.com/wp-content/uploads/2015/04/logotopleft.jpg]<http://www.binarystream.com/>

Sergio Kelly | Technical Product Manager (Dynamics NAV)
P. 604 522 6300 x. 105
F. 866 834 7622
W. BinaryStream.com<http://www.binarystream.com/>
sergio@binarystream.com<mailto:segio@binarystream.com>





[http://binarystream.com/wp-content/uploads/2015/04/logos.jpg]<http://www.binarystream.com/>

[http://binarystream.com/wp-content/uploads/2015/04/twitter.jpg]<https://twitter.com/binarystream>[http://binarystream.com/wp-content/uploads/2015/04/linked.jpg]<https://www.linkedin.com/company/binary-stream-software>[http://binarystream.com/wp-content/uploads/2015/04/fb.jpg]<https://www.facebook.com/BinaryStream>[http://binarystream.com/wp-content/uploads/2015/04/yt.jpg]<https://www.youtube.com/user/TheBinaryStream>

**Comment by SergioKelly** [comment]
![fillinvoicepostingbuffer](https://user-images.githubusercontent.com/22604702/35543033-d350f916-055a-11e8-8055-d600f029b397.png)

End of FillInvoicePostingBuffer.
