### ISSUE TITLE
Hide Activitybuttons in Role center page

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1483]
How to hide below activity buttons in Project manager role center?

seems missing some basic thing..

![image](https://user-images.githubusercontent.com/23735402/35291865-b5bad284-0094-11e8-9f63-e7943eb64d46.png)

**Comment by thpeder** [comment]
Hi @pmohanakrishna,
I'm closing this issue because you got the solution for it in #1472.

**Comment by pmohanakrishna** [comment]
both are different issues.
if 1472 will automatically solve this issue then it is fine..

**Comment by thpeder** [comment]
It should since you have the correct way of doing it in your sample code.

**Comment by pmohanakrishna** [comment]
this issue is not fixed with 1472..

**Comment by thpeder** [comment]
@pmohanakrishna I have just tried to hide some of these actions but the names are very cryptic.
Take a look at the 'Sections' area inside the role center, these are the groups you would be hiding.
![image](https://user-images.githubusercontent.com/24276180/36314523-6674b1c8-1335-11e8-8cb6-3797b748936e.png)
