### ISSUE TITLE
Promoted Actions - Subpages - Windows Client

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1488]
Hi, is it a known issue that actions in subpages (Sales Invoice Lines) are not displayed correctly when they are promoted in the windows client?

If so, will it be fixed?

If not, I can provide more info.

**Comment by markbrummel** [comment]
Any update on this?

**Comment by dennisfrostlander** [comment]
Can't pinpoint anything existing, could you please provide more info to make sure that we are on the same page?
