### ISSUE TITLE
Webservice parameter names - is null error

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#1489]
Just noticed traditionally the first letter of web service parameter names are converted to lowercase and it is still the case in 2018, objects/CSide extension. But this is no longer the case in ModernDev extension, is this intentional? 

This causes the parameter is null error calling the web service function, spotted the difference on the wsdl.

**Comment by kvaldik** [comment]
Any input from Microsoft on this? Can we assume that the parameter will maintain their uppercase value in V2 or should we expect it to go the way of CSide in the near future?

**Comment by DominikDitoIvosevic** [comment]
Hi. Could you please provide repro steps for this issue? Are you working on the Nav 2018 or the latest Developer Preview?

**Comment by kvaldik** [comment]
That's simple create a codeunit with a function like so:

```
  procedure WebServiceProcedure(var Data : XmlPort SomeXMLPort);
  begin
    Data.IMPORT;
  end;
```

Now expose said codeunit as a web service. In good old CSide the parameter name is converted to `data` but in V2 the parameter remains as `Data`.

I think this has been like this forever in V2 and tested it in `dynamics-nav:11.0.20977.0-finus`.

**Comment by DominikDitoIvosevic** [comment]
This should be fixed in the next update of Developer Preview

**Comment by kvaldik** [comment]
So the parameter will be converted to lowercase in V2?

I did notice that the parameter is lowercase in live D365. Will that always be the case or should I take caution if a version where it is uppercase is released to live D365?

**Comment by DominikDitoIvosevic** [comment]
It will be lowercase in all cases to match what CSIDE did. It will take some time until this fix propagates to live though so you are going to need a mitigation until then I'm afraid

**Comment by kvaldik** [comment]
Thanks for your response @DominikDitoIvosevic.
