### ISSUE TITLE
Issue with TableRelation=[Table].[Field]

### ISSUE THREAD

**Issue by ln1000000** [Microsoft/AL#1491]
An error occurs when referencing a field in a TableRelation property:

![image](https://user-images.githubusercontent.com/29798357/35345042-9259288c-00fc-11e8-826a-2d8f35419a68.png)
![image](https://user-images.githubusercontent.com/29798357/35345015-81a01ab4-00fc-11e8-9529-2da7b7a7d13e.png)
Is this by design?
Currently running January Development Environment
VSIX: 0.14.16285

**Comment by thpeder** [comment]
Hi @ln1000000,

Yes it is by design. The limitation is there for performance reasons.
