### ISSUE TITLE
New Event request for codeunit 13 OnAfterPostReversingLines

### ISSUE THREAD

**Issue by tomggithub** [Microsoft/AL#1492]
Require new event in codeunit 13 after line 88. We have old add-ons that adjust posted Gen. Journal Line dimension and put in same G/L Register after standard NAV postReversing Lines. And we would like to move to extension and upload to AppSource.

![image](https://user-images.githubusercontent.com/7251764/35350955-b2088790-00fc-11e8-9cde-607fa2c2e2f7.png)

**Comment by AlexanderYakunin** [comment]
Please provide required event definition

**Comment by tomggithub** [comment]
OnAfterPostReversingLines

Let me know if you need more information. Thanks

**Comment by tomggithub** [comment]
Hi Alexander,

We have an add-on to adjust dimension value from Gen Jnl Line global dimension 1 to pre-configured global dimension 1 value. This is mostly for education customers. When system posts GL batch, we will record all posted GenJnlLine, and after posted process complete, before creates G/L register, our process will post extra gen. journal lines to adjust dimension to pre-configured dimension and pre-configured Balancing accounts. And we would like those entries shows when in preview mode too and in same G/L Register No.

Let me know if you need more information.

The syntax:
LOCAL [External] [IntegrationEvent] OnAfterPostReversingLines(VAR GenJournalLine : Record "Gen. Journal Line";PreviewMode : Boolean;RefNo:Integer)
