### ISSUE TITLE
OnInstallAppPerCompany trigger runs before OnInstallAppPerDatabase

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1495]
We have a few tables shared betwen companies where we store our initial extension data and we use that information to initialize each company when extension is installed or when new company is created. As these tables are shared between companies, OnInstallAppPerDatabase seems to be the best place to import data using NavApp.LoadPackageData function and then use that shared information to initialize each company in OnInstallAppPerCompany trigger. Unfortunatelly it seems that OnInstallAppPerCompany runs before OnInstallAppPerDatabase trigger.

**Comment by dennisfrostlander** [comment]
Yes, OnInstallAppPerCompany does currently run before OnInstallAppPerDatabase.
@HunterFeltman-MSFT, @ShaylaG-MSFT, do you know of a reason for this specific order or have suggestions how to handle such scenario?

**Comment by HunterFeltman-MSFT** [comment]
This was implemented in this manner to follow the pattern of the base application upgrade when run in serial mode (normal is to run in parallel, where this must still be accounted for). 

As it is now, the only workarounds would be to encode this shared information inside of some codeunit functions or labels/constants.

**Comment by anzwdev** [comment]
Thank you for you answer @HunterFeltman-MSFT. Does it mean that OnInstallAppPerDatabase can run parallel with OnInstallAppPerCompany?

Nav can have some tables that can share data between companies so it means that records from all other, company specific tables can reference these shared tables, which also means that shared records should be there before we start processing company specific data and before we update references to shared information. That's why we need a separate trigger to initialize shared information before we start initializing companies. If OnInstallAppPerDatabase does not work this way, can we have another OnPreInstallAppPerCompany and maybe OnPostInstallAppPerCompany triggers (something like OnPreDataItem/OnPostDataItem or OnPreReport/OnPostReport on reports)? OnInstallAppPerCompany can be run parallel for each of companies in the database, but it should not start before OnPreInstallAppPerCompany finishes.

**Comment by HunterFeltman-MSFT** [comment]
No, extension-related install/upgrade flows are always run in serial, I meant to convey that we modeled the 'order or execution' on what the base application was doing when it is run in serial. 

As you your suggestion, it definitely something we will consider, although I suspect it will be more likely that we will reverse the order of the triggers so that your original scenario would be valid.
