### ISSUE TITLE
How to create a new NAV Development Preview?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#1500]
I try to create a new NAV Development Preview (http://aka.ms/navdeveloperpreview), but the Docker Image **microsoft/dynamics-nav:devpreview-finus** seams not be available anymore. Azure gives me an unspecific "Error". How should I create a new NAV Development Preview?

**Comment by thpeder** [comment]
Hi @DanielGoehler,
I have just had success in both getting the docker image and creating a Azure machine.

In Azure when you get a deployment error in the notification bar you should be able to click on it and get more information.

**Comment by DanielGoehler** [comment]
Hi @thpeder,

thanks for your effort. I guess the error is only occures on my Azure account. It is not clickable...
<img width="421" alt="error" src="https://user-images.githubusercontent.com/9556549/35469595-33ff6ea2-0338-11e8-8e1c-d72e993e78c2.png">
On https://preview.portal.azure.com/ everything worked fine...
