### ISSUE TITLE
New RoleCenter ActivityButtons

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1503]
Hi everyone,

we made a new role center for our solution and we would like to build some activity button.
I see there no option in AL. Couldn't we create ActivityButtions in V2?

**Comment by thpeder** [comment]
Hi @jiwanovski87,
You need to use Area(Sections) for your actions.
Here is an example of how to add new to an existing Role center [https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-adding-menus-to-navigation-pane](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-adding-menus-to-navigation-pane)

**Comment by jiwanovski87** [comment]
Okay, thanks!
