### ISSUE TITLE
Will it be possible to format all .al-Files after converting via txt2al?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#1508]
I didn't got an answer on #944, so I try again here: Will it be possible to format all .al-Files after converting via txt2al?

**Comment by atoader** [comment]
Hi @DanielGoehler ! What do you mean if it is possible to format .al files after converting via txt2al? Do you mean if it is possible to run the formatter as part of the conversion process?

**Comment by DanielGoehler** [comment]
No, in VScode.

**Comment by dennisfrostlander** [comment]
Hi @DanielGoehler, I assume you'd like to format ALL al files at once? And not one by one?
VSCode itself does not support such feature yet (you can vote for it [here](https://github.com/Microsoft/vscode/issues/29403)). Perhaps there are some other VSCode extensions which would provide auto-formatting for all documents, however, I did not find any with a basic quick search (only something for C#).

**Comment by DanielGoehler** [comment]
Yes. So there is no need txt2al does the formating right... Thanks for the Info that this rather missing in VSCode.

**Comment by lvanvugt** [comment]
Voted for. Would be great.
