### ISSUE TITLE
OnLookup Trigger parameter Text not working

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1510]
created below code in V1 which is working fine while selecting resource from lookup
![image](https://user-images.githubusercontent.com/23735402/35502985-c907e4de-0504-11e8-9e46-d5eeb0f16f92.png)

same code in AL is not working while selecting from Lookup
![image](https://user-images.githubusercontent.com/23735402/35503024-e71deb8a-0504-11e8-872d-6b2288aa23c3.png)

**Comment by qutreson** [comment]
Hi @pmohanakrishna, I think the AL code is missing here the "var" in the trigger signature. Can you try adding it and tell us if it fixed your issue? 

If your AL file was created using the txt2al converter, I guess the origin of the missing "var" is related to the issue [1450](https://github.com/Microsoft/AL/issues/1450).

**Comment by pmohanakrishna** [comment]
yes, var solved the issue.

it is generated using txt2al converter.
