### ISSUE TITLE
Label space

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1511]
if we have text constant with space at end
ex: Day space, week space etc
![image](https://user-images.githubusercontent.com/23735402/35517834-a1ec1a92-0535-11e8-9d4b-3d39e09b4ffa.png)

it is converted using txt2al like

        PeriodDescDaily: Label '"Day "';

can it be corrected as
       PeriodDescDaily: Label 'Day ';

without double quotes?

**Comment by qutreson** [comment]
The double quotes are actually a bug and should be removed. We actually already fixed this problem some time ago and it will be available in the next update.
