### ISSUE TITLE
upgrading a NAV 2017 environment with table C/AL customizations to a NAV2018 AL extension?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#1512]
I've been asked to upgrade a customer to NAV2018. It's very likely the client has some table customizations in their NAV environment done over the years (e.g. custom fields on base tables, new custom tables in the 50000 range, etc) and I'm currently weighing risks and benefits of moving their C/AL customizations to AL extensions.

How would I go about migrating the **data** in those legacy table C/AL customizations to an extension?  If I convert all their customizations into an extension, how can I migrate the data previously found in their table custimzations to the extended + new tables in the extension itself? 

e.g.

Example 1:
Legacy C/AL customization: Customer Table: Field 50000 "Foo"
to
NAV2018 AL Customer Table Extension : Field 50000 "Foo"

Example 2:
Legacy C/AL customization: Table 50000 "Foo"
to
NAV2018 AL Table 50000 "Foo"

Is it feasible to upgrade such an environment to the AL extensions model, or are they stuck indefinately on the older C/AL customization path?

**Comment by DanielGoehler** [comment]
On possible way would be to copy/move your Data into DataUpgrade-Tables. 

## Customer Field
Create a new Table 90000 **Customer UPG** with two fields, the Primary Key of Table Customer ( **"No."**) and Field 50000 **Foo**.

Your [Upgrade Codeunit](https://docs.microsoft.com/en-us/dynamics-nav/upgrade-codeunits#tablesyncsetup-functions) 90000 should have following entry to copy that data:
`DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Customer",DATABASE::"Customer UPG",TableSynchSetup.Mode::Copy);`

If you import the new **Customer** Table, where Field Foo was deleted, the **Customer UPG** Table and the **Upgrade Codeunit**, the _Table Synchronisation_ (Schema: Now) would copy every entry of the **Customer** Table with the value of **Foo** into the Upgrade Table **Customer UPG** before deleting the Field **Foo** from the **Customer** Table.

With a second Upgrade Codeunit 90002 and Upgrade Function (Subtype UpgradePerCompany) inside you AL extensions, you can move the Data back.
```
if CustomerUPG.FINDSET then begin
  repeat
    Customer.GET(CustomerUPG."No.");
    Customer.Foo := CustomerUPG.Foo;
    Customer.MODIFY;
  until CustomerUPG.NEXT = 0;
  CustomerUPG.DELETEALL;
end;
```

## Custom Table
Create new Table 90001 **Foo UPG** with the same Fields.

Your [Upgrade-Codeunit](https://docs.microsoft.com/en-us/dynamics-nav/upgrade-codeunits#tablesyncsetup-functions) 90000 would have following entry:
`DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Foo",DATABASE::"Foo UPG",TableSynchSetup.Mode::Move);`
After import the new **Foo UPG** Table and the Upgrade Codeunit, the _Table Synchronisation_ (Schema Now) for deleting Table **Foo** should move all the Data into **Foo UPG**.
 
Also in the second Upgrade Codeunit 90002 and additional Upgrade Function inside you AL extensions, you can move the Data back into the new Table **Foo**.
```
if FooUPG.FINDSET then begin
  repeat
    Foo.TRANSFERFIELDS(FooUPG);
    Foo.INSERT;
  until FooUPG.NEXT = 0;
  FooUPG.DELETEALL;
end;
```

**Comment by CanuckNav74** [comment]
Thank you @DanielGoehler ! I think that's exactly what I was looking for.
