### ISSUE TITLE
Message: <ii>Data at the root level is invalid. Line 1,position 1.</ii>

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1513]
when we preview report in web client, webclient is crashing
log shows

TimeGenerated : 1/29/2018 12:02:58 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: default
                <ii>Session type: WebClient
                Session ID: 1243
                User:
                Type: System.Xml.XmlException
                LineNumber: 1
                LinePosition: 1
                Message: <ii>Data at the root level is invalid. Line 1,
                position 1.</ii>
                StackTrace:
                     at System.Xml.XmlTextReaderImpl.Throw(Exception e)
                     at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
                     at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
                     at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader
                reader, Boolean preserveWhitespace)
                     at System.Xml.XmlDocument.Load(XmlReader reader)
                     at Microsoft.Dynamics.Nav.Types.Metadata.MetaReport.Create
                XmlDocumentFromRdlString(String rdl)
                     at Microsoft.Dynamics.Nav.Types.Metadata.MetaReport.CheckA
                ndPrepareRdlc(Int32 reportId, String rdl)
                     at System.Lazy`1.CreateValue()
                     at System.Lazy`1.LazyInitValue()
                     at Microsoft.Dynamics.Nav.Runtime.NavSession.<>c.<get_Loca
                lReportCache>b__154_0(MetaReport metaReport)
                     at Microsoft.Dynamics.Nav.Runtime.LocalReportCache.GetLoca
                lReport(MetaReport metaReport)
                     at Microsoft.Dynamics.Nav.Runtime.NavReport.EffectiveLocal
                ReportHandle()
                     at Microsoft.Dynamics.Nav.Service.NSService.GetReportRDLMe
                tadata(Guid reportHandle, Boolean& allowCaching, Boolean&
                enableExternalImages, Boolean& enableHyperlinks, Boolean&
                enableExternalAssemblies, Boolean& enableAppDomainIsolation)
                     at SyncInvokeGetReportRDLMetadata(Object , Object[] ,
                Object[] )
                     at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                RunInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                TransientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                ErrorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                Source: System.Xml
                HResult: -2146232000
                </ii>

**Comment by DominikDitoIvosevic** [comment]
Hi @pmohanakrishna .
We need more context to know what's the issue. Does this happen for all rdlc file or just a specific one?
Could you try and isolate the issue by providing us with an rdlc file which causes the issue?
Check the file and see if it's a valid xml file. You can use some online xml validator like https://www.xmlvalidation.com/

**Comment by pmohanakrishna** [comment]
this is happening only for our app reports
attached is rdlc file.
not errors found while validating in your link

[Sales Invoice (PGS).txt](https://github.com/Microsoft/AL/files/1694673/Sales.Invoice.PGS.txt)

**Comment by pzentner** [comment]
I can add to this, since it is an issue for me as well. It must happen for any RDLC report that is converted via txt2al, but I can't say that it's not happening for newly created layouts. 

But, for my converted reports, it is failing with the same error message when trying to execute the report. Attached is a zipped version of a RDLC file.

[NAVX Process Commission.zip](https://github.com/Microsoft/AL/files/1696732/NAVX.Process.Commission.zip)

**Comment by DominikDitoIvosevic** [comment]
The issue seems to be that the compiler made the rdl file encoded in UTF8 with BOM which then added an invalid character before the xml and caused parsing issues. A fix is on the way

**Comment by pmohanakrishna** [comment]
do we have to convert the reports again or is there anyway to fix them manually?

**Comment by DominikDitoIvosevic** [comment]
I'm afraid there is no workaround. You will have to wait 1 or 2 days for update of the compiler. I'm investigating why this started happening as it worked before

**Comment by DominikDitoIvosevic** [comment]
@pmohanakrishna could you verify if you are still experiencing these issues after build 20531?

**Comment by pmohanakrishna** [comment]
@DominikDitoIvosevic 
do we have to run txt2al again for reports or is it fixed while compiling and creating app?

I am getting below new error while trying to create app. (I didnt run txt2al)

Microsoft (R) AL Compiler version 0.14.16095
Copyright (C) Microsoft Corporation. All rights reserved

error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
Error: The package could not be created.

**Comment by pzentner** [comment]
I did not run txt2al again and it worked for me. I have no issues anymore with latest build. But @pmohanakrishna  you are not using the latest build - this is still an older compiler - so there you will still get the error.

**Comment by DominikDitoIvosevic** [comment]
The issue should be fixed just by running a newer version of the compiler. Please make sure you have a fresh version

**Comment by pmohanakrishna** [comment]
I am using docker build 20539. do I have to do anything more to update compiler also?

**Comment by pmohanakrishna** [comment]
@DominikDitoIvosevic @pzentner any suggestion on how to update compiler please?

**Comment by pzentner** [comment]
It shows you in the docker image (when you start it) the URL to the vsix of the compiler. Go to VS Code -> Extensions -> '...' -> Install from VSIX and paste the URL into the "open file" dialog.

It then will update the compiler and install it. This has to be done with any new build that comes out.

**Comment by pmohanakrishna** [comment]
Thank you @pzentner 
@DominikDitoIvosevic Thank you.. It is working in latest build.

**Comment by pmohanakrishna** [comment]
@DominikDitoIvosevic I am facing same error again with NAV2018
AL Compiler version 0.15.18771
NAV2018 CU6

**Comment by DominikDitoIvosevic** [comment]
@pmohanakrishna I don't think it's possible that is happening since this whole feature is not available in Nav2018. Are you sure this is the same bug? Could you please provide full repro steps?

**Comment by rknabben** [comment]
@DominikDitoIvosevic What do you mean the feature is not available in NAV2018CU6? All functionality seems to be there and (somewhat) works, apart from the XmlException (Using NAV 2018CU6 + VSCODE with AL 0.16.16948). If you create the same object without adding the RDLC to the package, everything seems to be in working order.  Some database hacking also reveals the RDLC is imported in the database, so it seems to be an issue in the XML Parser (or at least the data it's fed)

**Comment by artisb45** [comment]
I was facing the same problem. The solution I found to work was converting the rdlc file encoding from UTF-8 with BOM to UTF-8

**Comment by nanla** [comment]
Thank you. I will try what you suggested.


________________________________

**Comment by Deepakalle123** [comment]
@artisb45 yes the rdlc issue has been fixed by using utf 8 with bom.
