### ISSUE TITLE
New event publisher in COD 414, OnAfterUpdateSalesDocLines

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1515]
Before the ATOs are released (with the statement ReleaseATOs(SalesHeader), I want to be able to add code in a subscriber to this publisher to allow me to also update the lines of the sales document to be released.

syntax:

`LOCAL [External] [IntegrationEvent] OnAfterUpdateSalesDocLines(VAR SalesHeader : Record "Sales Header";VAR LinesWereModified : Boolean)`

**Comment by NKarolak** [comment]
Would the already existing publisher OnBeforeReleaseSalesDoc not be an option?

**Comment by lvanvugt** [comment]
Nope, have considered that, but that's to early. Don't want to change lines before all checks have been done.
