### ISSUE TITLE
AL Namespaces

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#1517]
Since names and ID's should be unique across all APPs it would make sense to introduce a namespace functionality. 

You should be able to assign a namespace for an app. for example, in the app.json like the ID range. Thus, all objects in the database would always receive the namespace as a prefix and it would lead to fewer conflicts between apps. 

My attitude towards number ranges is well known.

**Comment by esbenk** [comment]
We are planning something like that in the future. We don't have a final design yet, but we need a namespace like feature.

**Comment by cvale** [comment]
I would support this request because we are limited with 30 character names and we already have situation where we need to extend same object from different apps and we want to use meaningful names in our objects, so I would ask you guys to definitely push this one to top of your requirements. I have to say that number ranges does not help here. Namespaces would solve this issue efficently.

Thanks

**Comment by cvale** [comment]
Once again, prefix system is total mess. We have our own codeunit that extends Dimension Management functionality, and the object is called "XXX Dimension Management". Now I know we could call it differently, but we want to stay inline with naming conventions and we want names to be as self sufficient as possible.

Here's the catch: If you name all of your objects inside an app with prefix, logical thing would be to name your object variables starting with the prefix. Now that gives you a spectacular code mess...

And I want to remind you again how stupid object names are when you have only 26 characters left (30-3 for prefix - 1 for separator)...

This prefix solution is just a plain band aid, but it doesn't hold well. **Come on guys, introduce simple namespace to app config files that would be read when app is being loaded and simply added like prefix to existing object name. It can not be so hard to change internal nav service code to have object names with namespace longer then 30 characters?!**

**Comment by pborring** [comment]
I am closing this suggestion as ideas are tracked on http://aka.ms/bcideas. This topic already has an entry
https://experience.dynamics.com/ideas/idea/?ideaid=57b8d9d1-e28b-ea11-99e5-0003ff68f606
