### ISSUE TITLE
[Questions, Best Practices] Licensing system integrated in the application, including trial versions

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1519]
It is well known that for an app you should offer a customer the possibility to make it available as a trial version. Now there are already some approaches to modeling trial versions in the guidelines for monitarization presented by Microsoft. #666 Unfortunately, however, nothing seems to be made available within the application by the system to offer trial versions. This means that it looks as if every partner has to cook their own soup here again.

For this reason, I wanted to ask again whether the system itself provides some kind of solution to address the licensing problem for the monitarization globally. If someone is reading this and there are already some good ideas, please write in at any time. In my opinion, a solution as a community project would also be conceivable. All the partners could join forces and work together to find a solution for licensing and deploying trial versions. But of course, a fundamental solution to this problem on the part of Microsoft would be important. Nowadays, the days when each partner has to invent something new for the products should be over. Then there are various solutions, and the customer no longer sees through what he has licensed and where.

It is important that the functionalities provided by the system should be transparent and open, so that each partner can adapt it to its own needs. There would be a common basis for licensing and special cases could still be covered. I don't know, for example, that there is a procedure for buying in apps or something similar. Here, too, a decision has to be made by Microsoft on how to deal with this, because of course there is more to be done.

**Comment by MikeGlue** [comment]
@ajkauffmann has a nice solution that integrates to Stripe. You should definitely check that out if you've not seen it already.

**Comment by FSharpCSharp** [comment]
@MikeGlue  Sounds interesting. No, I haven't heard about it yet. In the blog of @ajkauffmann  I could not find anything about it. Could you please give me a concrete link to it? Many thanks in advance!

**Comment by jiwanovski87** [comment]
See fact 12 here 
https://community.dynamics.com/nav/b/navericwauters/archive/2017/10/22/microsoft-dynamics-nav-2018-dynamics-365-tenerife

Is there any other link?

**Comment by MikeGlue** [comment]
I cannot find a link to his latest solution that uses Stripe. the above link is to his first version that used an Azure web service. Hopefully @ajkauffmann picks this thread up and can give us a link :)

**Comment by FSharpCSharp** [comment]
@jiwanovski87 
Wow, that was super fast! I definitely wouldn't have looked for that in this blog. Thanks for the tip. But somehow I'm a little confused now. I always thought that the AppSource is a kind of App Store where you can buy all these extensions in the future. The blog is also from October last year. I would really be interested to hear a statement from Microsoft if there are any changes of plans here.

**Comment by pborring** [comment]
We now finally has the first iteration of AppSource transactability, with a per user licensing model, assignable in Microsoft Admin Center. Currently credit card based purchase in AppSource Marketplace is supported. See more at https://aka.ms/bcapptransact 

Soon there will also be CSP support to sell and share margin with CSP resellers.

Given above, I will close this Al GitHub issue. For additional support in AppSource transact, such as per site or custom metering, please vote or create new entries on https://aka.ms/bcideas
