### ISSUE TITLE
Wizard page - media not working

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#152]
Not sure if it's because of me, or a bug.

I'm trying to build my first Wizard page.  Based on information from this issue:
https://github.com/Microsoft/AL/issues/127

But I'm not getting my images to work (MediaStandard & MediaDone).  I just get the groupname and 5 as a value in the field.  Even when I try the example of steven in from the issue above, I'm getting that not as images, merely as value :-/.

Anyone has a clue?

**Comment by StanislawStempin** [comment]
Media should be working fine. Can you check issue #115 and see if provides any hints? 
Otherwise could you post the code that doesn't work for you? 
The example from #127 doesn't seem right because value of the field Image is blank and the top banner will not be displayed.

**Comment by srenders** [comment]
I also noticed the image is not showing. Even if I set the Boolean manually so the group is displayed, it does not display the image.
Also, when I try to run the following list:
```
page 71234567 MyMediaRep
{
    PageType = List;
    SourceTable = "Media Repository";
    Editable = false;
    layout
    {
        area(content)
        {
            repeater(General)
            {
                field("File Name";"File Name")
                {                  
                }
                field("Display Target";"Display Target")
                {                  
                }
                field(Image;Image)
                {
                    Visible = true;                  
                }
            }
        }
    }

    actions
    {
        area(processing)
        {
            action(ActionName)
            {
                trigger OnAction();
                begin
                end;
            }
        }
    }
}
```
it does not display the images.

**Comment by StanislawStempin** [comment]
The images in the Media Repository table shipped in demo data are null. You need to update the Image to some valid Media Id. For example:
```
 update dbo.[Media Repository] set Image = '375629E0-7F27-4878-9F83-0C393CEE24E3' where [File Name] like '%400px.png'
```

And then running your example produces:
![media](https://cloud.githubusercontent.com/assets/23653165/25392993/8cccf15e-29da-11e7-8a98-dd1b25eddfdc.png)

**Comment by srenders** [comment]
Thanks for the info.
By the way, in this example the images work fine:
[MyWizard.zip](https://github.com/Microsoft/AL/files/969934/MyWizard.zip)

**Comment by StanislawStempin** [comment]
Thanks, your code looks like the right way to do it. Closing the issue.
