### ISSUE TITLE
Accessing Profile table still gives error

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1521]
A good day.

When accessing the Profile table with a variable (Profile : Record Profile) I still getting an error: The type or method 'Profile' cannot be used for 'Extension' development.

I am using _still_ as https://github.com/Microsoft/AL/issues/500 suggests this has been solved.

Of course might be that I am doing something wrong. Any tips? Or still a bug.

BTW: running build 19394.

**Comment by pmohanakrishna** [comment]
Profile table is available from anniversary update Build 19756
https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/

I hope it will help you..

**Comment by dennisfrostlander** [comment]
@lvanvugt If it still does not work you in the proper build, feel free to re-open.
P.S. Please also make sure that you are using the latest System symbols from that build (Microsoft_System_11.0.12927.0.app) in your .alpackages folder.
