### ISSUE TITLE
Folder structure inside control add-ins zip files created by AL compiler 

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1525]
When control add-in zip is created by AL compiler it uses folder structure from AL project, but creates additional, root "resources" folder for js and css files and it is not doing that for files listed in images list. This causes problems, because we have to modify all relative paths to images and fonts inside css files and we don't want to do it for third party js/css libraries.

I.e. we are using third party library, that is located in ScriptLibraries\UILib folder inside our extension. There are js, css and fonts subfolders there, one of css files references fonts from fonts folder using relative paths ('../fonts/font.eot'), but AL compiler transforms this list of extension folders:

> ScriptLibraries\UILib\js
> ScriptLibraries\UILib\css
> ScriptLibraries\UILib\fonts

into this list of control add-in folders:

> resources\ScriptLibraries\UILib\js
> resources\ScriptLibraries\UILib\css
> ScriptLibraries\UILib\fonts

**Comment by dennisfrostlander** [comment]
Thanks for reporting, this is a problem indeed.
