### ISSUE TITLE
Warehouse receipt page lines tab is not showing properly in Anniversary update

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1526]
Hi,

See below the warehouse receipt page lines tab is not showing properly or completely as we cannot see a single line also correctly
![image](https://user-images.githubusercontent.com/26792519/35566668-35d5b788-05e8-11e8-98a6-c0fe26f529f3.png)

Can you please check this?

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
This issue is out of scope for this repository. Please contact the regular support channel.

**Comment by bachii1010** [comment]
@StanislawStempin  i have rechecked this in march update and this looks fine here see below:

![image](https://user-images.githubusercontent.com/26792519/38552761-d77f2a78-3cda-11e8-90f0-c728ff5eda2c.png)

**Comment by StanislawStempin** [comment]
Thanks. In that case closing this issue
