### ISSUE TITLE
Content of Application.app is not loaded

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#1529]
VSCode Version: 1.19.3
OS Version: Win 10 1709
AL Version: 0.11.14434
Docker Version: 17.12.0
NAV Docker Image: microsoft/dynamics-nav:2018-de

Description: 
My VSCode/Docker Enviroment somehow ignores the application.app Content. 

Steps to Reproduce:
1.) Use AL: Go!
2.) add var 'Test: Record "Company Information"; to pageextension 50100
3.) variable is underlined, it says "Company Infoprmation" is missing. IntelliSense doesn't know about the table.

I've tried creating multiple new Projects, delete the app package, uninstalling VSCode, re-setting docker, etc.

**Comment by Gallimathias** [comment]
First: you are using the wrong AL version. NAV 2018 uses the extension version 0.12.15355 and the preview version 0.13.15836.

Second: After creating a project you have to download the symbols once. The information is taken from the extension of your launch.json file. Frequent problem here is that the nav instance is not called nav but different e. g. DynamicsNav110

**Comment by Gallimathias** [comment]
Complementary: CU1 Nav2018 uses al version 0.12.15898

**Comment by JulianTillmann** [comment]
What do you mean, the wrong version? I'm using the AL Version I can download as an Extension in AL: ms-dynamics-smb.al

And the Symbols are downloaded and the packages. "Microsoft_Application_11.0.19846.0.app" and "Microsoft_System_11.0.12925.0.app" are placed in the ".alpackages"-folder. 

This whole combination used to work for about four weeks, then I crashed one of my AL-Projects so that the Build-process is not started anymore.

**Comment by Gallimathias** [comment]
I mean the version of the al extension. The marketplace version does not match the actual used version.
The published version in the VS Code marketplace is: 0.11.14434

but 

But MS Dynamics NAV 2018 is delivered with: 0.12.15355

The folder of the RTC contains a subfolder New Developer Experience. There you will find a vsix with the correct verion.

Marketplace:
![marketplace](https://user-images.githubusercontent.com/16351673/35609317-2013944a-065d-11e8-8c0b-cc0a982d59c9.jpg)

**Comment by JulianTillmann** [comment]
oh, okay. I downloaded the vsix from my docker Container and now it seems to work. Thanks a lot! :-)

But why is the official and working Extension not the one available in VSCode itself?

**Comment by esbenk** [comment]
The extension from the marketplace matches our online sandboxes.

The docker images (and right now also on-prem) are ahead of the online sandboxes and there uses a newer version.

On-prem and docker images is therefore shipped with a version that matches the platform. 

We plan to get better alignment on this in the future.

**Comment by JulianTillmann** [comment]
okay, right now my Problem is fixed. Thank you :)
