### ISSUE TITLE
base keyword

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#153]
I would recommend or want to implement the base keyword from C #. In my opinion, it is necessary to be able to control whether one wants to execute its own code before, after or without standard code of the basic application.

I assume since we have in the background C# code have the extension inherited the "normal" hirachie which we are accustomed from C#.  It seems to me therefore consistently pass the base functionality.

**Comment by StanislawStempin** [comment]
The prerequisite to having base keyword would be to have some sort of code override. This is currently not available in extensions therefore base keyword would have no usage. We are taking it into consideration for the overall extensibility model in the future.
See #120, I will close this issue.
