### ISSUE TITLE
The request for path.. failed with code 422. Reason:  The value "1473493" can't be evaluated into type Date.

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1533]
Hi,

I'm facing this issue while running the AL code.Package is created successfully but the above error is thrown.Any suggestion?

**Comment by esbenk** [comment]
We need some more information. Can you include more from the log? Are you using dates in your code?

**Comment by DanielGoehler** [comment]
Hi @esbenk,
I have the very same Problem: 
```
[2018-02-17 21:52:28.93] Sending request to https://navfeb.westeurope.cloudapp.azure.com:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
[2018-02-17 21:53:50.76] The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: 
The value "1471345" can't be evaluated into type Date.
```
I didn't find _1471345_ in the Code. Also this is an converted Solution. There should nothing in it which not worked in C/AL. With `Get-NavContainerEventLog` I didn't any details to this error. 

Could you be so kind to share with us how to get you more log?

**Comment by esbenk** [comment]
It is a conversion error during deployment. It could be related to a CalcFormula - I'm currently looking into a bug in that area. 

@DanielGoehler The 1471345 is the internal representation of 2014-03-15. Do you have that in any form in your code?

@Chris-Dsilva  1473493 = 2017-02-21.

Hope this will help tracking down the issue.

It would assume that there is a EventLog entry for this. I'm not aware that Get-NavContainerEventLog is doing any filtering. I will look into that.

**Comment by DanielGoehler** [comment]
Hi @esbenk,

thank you! The **InitValue** on a **Date Filter** Field causes at least my problem. If I remove that this error don't occurs anymore. The following AL-Table, causes the same problem. 
```
table 50000 "Test Table"
{  
    fields
    {
        field(1;Code; Code[10])
        {           
        }
        field(2;"Date Filter"; Date)
        {
            FieldClass = FlowFilter;
            InitValue = 20180101D;
        }
    }   
    keys
    {
        key(PK; Code)
        {
            Clustered = true;
        }
    }   
}
```

**Comment by esbenk** [comment]
Perfect - or at least now I know where to look.

Thanks.

**Comment by StanislawStempin** [comment]
#1622 is potentially the same issue.
