### ISSUE TITLE
Subscriber Events - Copying the parameters from the Publisher Event

### ISSUE THREAD

**Issue by KJBOLOE** [Microsoft/AL#1534]
Hi,

I use the version 0.12.15898

Is there a way to copy the parameters from the Publisher Event to the Subscriber Local procedure. Like the way it is in the Development Enviroment.

[EventSubscriber(ObjectType::Table, 27, 'OnAfterValidateEvent', 'Description', false, false)]
    local procedure OnAfterValidateDescription(**VAR Rec: Record Item; VAR xRec: Record Item; CurrFieldNo: Integer**);
    begin
        Message('Beskrivelse er blevet ændret.\\Beskrivelse før : ' + xRec.Description + '.\\Beskrivelse efter : ' + rec.Description + '.');
    end;

![image](https://user-images.githubusercontent.com/35993204/35615528-a9fd8642-0672-11e8-9dd8-51f616190c6c.png)

![image](https://user-images.githubusercontent.com/35993204/35615476-8906bf80-0672-11e8-8dcf-e6e3a573ad9d.png)

Best regards,
Kenneth

**Comment by thpeder** [comment]
Hi @KJBOLOE,

There is no command or something like that, that makes it as easy as in C/SIDE at the moment, but we are looking into improving it.

**Comment by qutreson** [comment]
Hi @KJBOLOE, we made some changes recently on Intellisense around event subscribers in order to suggest the parameters you can use for trigger events, but also business and integration events.

![image](https://user-images.githubusercontent.com/31541422/36974397-d36d7d34-2076-11e8-9d69-45034c45cafd.png)


See also #149

**Comment by KJBOLOE** [comment]
Hi 
Looking good, how can I see the change, I can't find an upgrade anywhere to the AL Extension.
Best regards,
Kenneth
