### ISSUE TITLE
Licensing of table extension and page extension objects

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#1539]
_Continuing issue #673_ 

In case the customer license contains a Starter pack, the object table range 50000..50009 is available. Does this imply that we will only be able to create a maximum of 10 **table extension** objects too? (Where in the past we could add fields to almost any table, without any license impact / additional cost for the customer.)

Stated otherwise, is the customer required to purchase 10 additional table objects (600 €) in case he would like to use 10 addition **table extension** objects (50010..50019)?

Or can table extension (and page extension) objects be obtained / included in the license for **free**? If so, how is the **range assigned** in the license file?

**Comment by markbrummel** [comment]
For what I have tested (and running now in a production environment) a customer license can run ANY table and page extension.

HOWEVER!

With a customer license you cannot publish an extension that has table or page extensions outside their table or page numbers. If you publish the extension with a partner license and then switch the service tier to the customer license everything is just fine.

My guess is that the publishing limitation is a bug and what I found is a workaround.
