### ISSUE TITLE
Autogenerate variable names for object based variables

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1541]
Since NAV 2015 we have this simple and great feature in C/SIDE that generates automatically the name of variables based on the NAV objects. It makes the work of a developer quicker and more consistent. The latter because we all will use the same naming of these kind of variables.

Based on feedback of an in-house workshop I am reporting this here.

It would be great if we could get a similar experience in VSCode.

**Comment by DominikDitoIvosevic** [comment]
We actually have had this feature for a while where we would add the same name as the source expression.
We may not have covered all the cases so if you find a case where you think it's missing please let us know.

![2018-02-02_09-35-34](https://user-images.githubusercontent.com/6378638/35724123-f429088c-07fc-11e8-9551-3f790e266471.gif)

**Comment by lvanvugt** [comment]
Hai Dominik,

Looking at your video this is not what I am pointing at. What I see that a page field (control) will get assigned a (variable) Name automatically, but as I wrote 

> automatically [generate] the name of variables based on the NAV objects

So in C/SIDE like this:

- I only enter the DataType (here Rec) and the Subtype:

![image](https://user-images.githubusercontent.com/18466198/35728373-aacf5f88-080b-11e8-91a3-6a867d189ba0.png)
- and when I leave the line NAV automatically populated the Name of the variable (here Customer):

![image](https://user-images.githubusercontent.com/18466198/35728555-386b050e-080c-11e8-91f7-4ec1f05a5dd1.png)

**Comment by dennisfrostlander** [comment]
One solution could be a relatively simple code snippet, which would set both variable name and table name to the same value.
One drawback though is that intellisense does not kick off when typing a table name, but this might be a VSCode editor issue.

```JavaScript
    "Snippet: Var": {
        "prefix": "trec",
        "body": [
            "${1:Variable} : Record ${1};$0"
        ],
        "description": "Snippet: Record variable"
    }
```

**Comment by TheDenSter** [comment]
Another aspect of that feature is that in C/SIDE it removes spaces and special characters. So when you select "Sales Header" as the record subtype, that would result in a variable called SalesHeader (without the "" and spaces); picking the "G/L Entry" table gives you the GLEntry variable. Would snippets have the capability to remove spaces and special characters from the table name?

**Comment by dennisfrostlander** [comment]
No,  I don't think it's possible with snippets. The best you do is just to quote variable names as well...

**Comment by DavidFeldhoff** [comment]
What about using the [AL Variable Helper Extension](https://marketplace.visualstudio.com/items?itemName=rasmus.al-var-helper)?

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
