### ISSUE TITLE
{ } instead of begin .. end

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1543]
I know there has been a discussion when conceiving AL regarding the use of begin end in the code parts. If I recall right it was decided not to change that to { } (curly brackets), to not make the differences with C/AL to big. The curly brackets would solely be used for bordering the various other section (objects, fields, actions, etc.).
I must admit I was in favor of that. Now working with VSCode for some time, I find it somewhat confusing to have both in the same object. And with me various attendees to my workshops. Especially those (and that's what, among others, the _modern development experience_ is aiming at) who do come from environments like Visual Studio. Not in the least the youngster our world is needing.

So the request is to get rid of the begin .. end construct.

**Comment by Gallimathias** [comment]
The discussion is not over, but MS has not yet made a final statement.
After my renewed statement in #645, the discussion was moved from Stanislaw to #63. But i waiting for an answer. 

To have everything in one place and to show the urgency of this change, I would also recommend moving your issue to #63 ^^. @lvanvugt

**Comment by lvanvugt** [comment]
Thanx, Marcus. Had been searching my *** off, but hadn't found a post. So great that you noticed mine. And I will add my comment to #63.
