### ISSUE TITLE
Add UsageCategory property Page snippets 

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1544]
Based on my own findings and the findings of the participants of an in-house workshop on VSCode I would like to suggests to add the UsageCategory property to the Page snippets, so Page will be getting a UsageCategory, making it searchable.

**Comment by qutreson** [comment]
#1540

**Comment by qutreson** [comment]
Hi @lvanvugt, thank you again for your suggestion, we added the usage category property to the page and report snippet some time ago, but we forgot to update this issue.

**Comment by lvanvugt** [comment]
Great @qutreson, but no milestone on when it is going to be shipped?

**Comment by qutreson** [comment]
We added it to our master in May, so I guess it should have been part of the [June 2018 Update](https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/). If you use the AL extension from the Marketplace, it has the UsageCategory property as part of the page and report snippet.
