### ISSUE TITLE
Hints for the ApplicationArea property on Pages

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1545]
I guess for all properties there are hints for the possible values, but not for the ApplicationArea property on Pages. Please expose them.

**Comment by qutreson** [comment]
We have changed the property description of ApplicationArea that you can see on hover in order to show some standard values that can be used: 

![image](https://user-images.githubusercontent.com/31541422/35737551-39434908-082c-11e8-9d4e-7ff35a3725ec.png)

**Comment by lvanvugt** [comment]
Nice. Not possible to have it in Intellisense?

**Comment by MikeGlue** [comment]
The tooltip is nice, but to Luc's point, every other property that contains a list of values to select from will show you that list via intellisense. This property does not, and even with the tooltip, a developer does not know all of the options that they have to choose from.

If everything's consistent than it just makes learning the new platform that much easier.

**Comment by qutreson** [comment]
Providing Intellisense in this case is a good suggestion. However, the property ApplicationArea is different from other properties since its values are taken at run time and the application areas are then not defined in a fixed enum like it is the case for properties like PageType. 
This is something we would like to have in the future, but we don't have any time estimation on when we will make it possible it for now.

**Comment by lvanvugt** [comment]
Thanx for the elaboration. I guess we're on  the same level regarding consistency, but point taken. Let's call this a useful workaround, for now.

**Comment by grobyns** [comment]
Hi all,

just a little more info: from the platforms point of view the application area tags can be anything and they do not even need to be defined anywhere. As this would be very difficult for us to manage, we (the application) define the possible values in Table 9178 Application Area Setup as boolean fields. 
If you'd like to know what values we have defined that you can use, you just need to take a look at the table definition. Of course you are also free to add your own application areas by adding boolean fields to the table. You can read more about how to add your own application area here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-extending-application-areas

Cheers,
Gert
