### ISSUE TITLE
Add item to context menu for report layout

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1546]
Opening a designer for a report layout (.rdl or .docx) is a somewhat cumbersome task. You need to first open the file folder (using _Reveal in Explorer_ ) to be able to open the layout file in its associated designer.

Increase our productivity and add a context menu item in VSCode to allow us to directly open the file in its designer.

**Comment by DominikDitoIvosevic** [comment]
This is a feature request for vscode. I have opened an issue there asking for the feature so you can upvote there if you want them to prioritize it.

https://github.com/Microsoft/vscode/issues/43641

**Comment by lvanvugt** [comment]
Thanx, Dominik. DONE.

**Comment by DominikDitoIvosevic** [comment]
I'll leave this one open so that we have something to track

**Comment by DominikDitoIvosevic** [comment]
I have added a way to introduce this feature through our extension. Now you will be able to use:

![image](https://user-images.githubusercontent.com/6378638/36978494-ea3118c4-2084-11e8-8854-309f5c1c203f.png)

**Comment by lvanvugt** [comment]
Indeed I saw it. Great and thanx.
