### ISSUE TITLE
The name 'CurrAmount_Autoformat' is reserved for internal usage by the compiler

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#1548]
I get these errors on following Columns in a Report (Developing for Extension)

The name 'CurrAmount_Autoformat' is reserved for internal usage by the compiler
The name 'CurrQty_Autoformat' is reserved for internal usage by the compiler

Is this a Bug or are they really now allowed

If not allowed, can we see a list over Field names that are reserved for internal usage by compiler

**Comment by dennisfrostlander** [comment]
The only related rule is that the column names cannot end with "format". This is due to certain report platform specifics.

**Comment by StanislawStempin** [comment]
Tagging it as a bug. We should provide a better error message in this case
