### ISSUE TITLE
Please make Method  IsStartNewGroup available for Extension Dev

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#1549]
The type or method 'IsStartNewGroup' cannot be used for 'Extension' development.

Please make Method available for Extension Dev

In Report 6521 Item Tracking Appendix method IsStartNewGroup

In FIN-US the Scope is Personalization but in FIN-DK the scope is Internal

**Comment by JesperSchulz** [comment]
You got it. Will ship with upcoming Docker image.
