### ISSUE TITLE
Report - Request Page & OnOpenPage Trigger

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#155]
Hello,

i am up to develop a Report for my first extension in nav. It is an "processing only" Report (Batch-Job). But i need some option fields on the request page. Even that is done. But now i want to preallocate These Option fields (Default values). The usual method to do this is to use the "OnOpenPage" trigger of the request page. My Code is like that:

...
    requestpage
    {
        

        layout
        {
            
            area(content)
            {
                group(Options)
                {
                    field("Location Code Filter";opt_LocationFilter)
                    {
                        TableRelation = Location;                        
                    }
                    field("Variant Code Filter";opt_VariantFilter)
                    {
                        TableRelation = "Item Variant";
                    }
                    field("Planning Date Filter";opt_MaxPlanningDate)
                    {
                        
                    }
                }
            }
        }
    
    
    }
...

Can you give an example how to add the "OnOpenPage" trigger here?

**Comment by thpeder** [comment]
You write it after the layout within the request page, like:
```
requestpage
{
    layout
    { /* Your layout */
    }

    trigger OnOpenPage();
    begin
    end;
}
```

**Comment by KaiSwitalla** [comment]
Yeah! it works thanks! You can Close this issue.
