### ISSUE TITLE
Deleting Exsisting Table Extension Field, SQL Table Empty

### ISSUE THREAD

**Issue by danielgeissbuehler** [Microsoft/AL#1550]
Starting Point: I have an Table Extension with 3 fields, wich is already in use. The new fields contains values.

If i now delete one field, wich i dont need anymore and publish the Extension, **all values of all Fields** are gone. (SQL Extension Table completely is empty) Without any warning or confirmation. 

Could you change this behaviour to the behaviour wich happens in the old C/AL Development? (You have to force your changes, and only the data of the deleted field is deleted in SQL!)

**Comment by dennisfrostlander** [comment]
This was the current behavior of publishing extensions - the entire schema was forcefully recreated.
We have recently completed a feature to support preserving data when re-publishing the extension.
See https://github.com/Microsoft/AL/issues/62, it should be available in the next monthly update.

**Comment by DominikDitoIvosevic** [comment]
This feature has been implemented and you can read more about it here: 
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-retaining-data-after-publishing

**Comment by StanislawStempin** [comment]
Short-term we don't have any plans for supporting data retention in case of breaking schema changes. The way to handle it would be to mark the field as Obsolete instead of deleting it, running upgrade code, or doing manual backup/restore of data using SQL.
