### ISSUE TITLE
How do I use the new XmlDocument and related classes?

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1553]
I am trying to use the new XmlDocument class (and related classes) to update the value of a single node in an XML document but I cannot figure out how to do it.

I have the XML Document as text (which is actually the ReportParameters from a report in NAV).

I can use these lines to create my XmlDocument variable from the settings string.

```
SettingsXmlReadOptions.PreserveWhitespace := true;
XmlDocument.ReadFrom(SettingsText, SettingsXmlReadOptions, SettingsXmlDoc);
```
I can find the node I'm interested in using: 
```
SettingsXmlDoc.SelectSingleNode('/ReportParameters/Options/Field[@name='''+FieldName+''']/text()',OptionsFieldNode)
```

to select the text node or if I want to select the element that contains the text node I can use:

```
SettingsXmlDoc.SelectSingleNode('/ReportParameters/Options/Field[@name='''+FieldName+''']',OptionsFieldNode)
```

This works OK and I can see I'm getting the correct node back, but how do I update the node to a new value and store it back into my variable? This is part 1 of my problem - I don't know how to set the value of my node. It would be nice if there was a InnerText property on my XML node so I could just set that. Can you please advise how I am supposed to do this without such a property?

Also, I am having a problem saving my XMLDocument back to a variable. If I try to use SettingsXmlDoc.WriteTo(MyTextVariable) I get a runtime error of:

Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException' was thrown.

Am I doing something wrong here? Or does this new class just not work properly yet?

**Comment by dennisfrostlander** [comment]
Hi @DavidRoys,

The XML nodes return from the document are immutable, so if you want to change a node you need to replace it with a new XML Element.
Here is an example, which finds and replaces a node:
```JavaScript
trigger OnOpenPage();
    var XmlString : Text;
        Doc : XmlDocument;
        Node : XmlNode;
        NewNode : XmlElement;
        Options : XmlReadOptions;
        Result : Text;
    begin
        Options.PreserveWhitespace := true;

        XmlString := '<Cars><Car Id="2">BMW</Car></Cars>';
        XmlDocument.ReadFrom(XmlString, Options, Doc);

        Doc.SelectSingleNode('//Car[@Id="2"]', Node);

        NewNode := XmlElement.Create('Car', '', 'Audi');
        NewNode.SetAttribute('Id', '3');
        Node.ReplaceWith(NewNode);

        Doc.WriteTo(Result);
        Message(Result);
    end;
```

Writing to a text variable is definitely a support scenario as well. Could you please see what errors you have in the Windows Event Viewer when you this exception?

**Comment by DavidRoys** [comment]
Thanks for the help of how to update the contents of a node.

I’ve found out what the problem is with the exception and it looks like it’s the processing instruction in my xml string.

The report parameters are in the following format:

```
<?xml version="1.0" standalone="yes"?>
<ReportParameters name="My Report" id="50000">
    <Options>
        <Field name="PostingDate">2019-01-24</Field>
        <Field name="NextDocNo" />
    </Options>
    <DataItems>
        <DataItem name="Vendor">VERSION(1) SORTING(Field1)</DataItem>
    </DataItems>
</ReportParameters>
```

If I try to load this as an XMLDocument it appears to work but if I try to use the WriteTo after loading it I get the following error:

```
Type: System.ArgumentNullException
Message:
  <ii>Value cannot be null.
  Parameter name: name</ii>
ParamName: name
StackTrace:
     at System.Globalization.EncodingTable.GetCodePageFromName(String name)
     at System.Text.Encoding.GetEncoding(String name)
     at Microsoft.Dynamics.Nav.Runtime.Xml.XmlNodeAdapters.NavXDocumentAdapter.<>c__DisplayClass2_0.<WriteTo>b__0()
     at Microsoft.Dynamics.Nav.Runtime.TrappableXmlOperationExecutor.<>c__DisplayClass0_0.<ExecuteXmlOperation>b__0()
     at Microsoft.Dynamics.Nav.Runtime.TrappableOperationExecutor.Execute(DataError errorLevel, Func`1 operation, Action`2 processNativeException)
Source: mscorlib
HResult: -2147467261
</ii>
```

If I use your examples of the car and add the processing instruction, I get the same error.

```
    trigger OnOpenPage();
    var XmlString : Text;
        Doc : XmlDocument;
        Node : XmlNode;
        NewNode : XmlElement;
        Options : XmlReadOptions;
        Result : Text;
    begin
        Options.PreserveWhitespace := true;

        XmlString := '<?xml version="1.0" standalone="yes"?><Cars><Car Id="2">BMW</Car></Cars>';
        XmlDocument.ReadFrom(XmlString, Options, Doc);

        Doc.SelectSingleNode('//Car[@Id="2"]', Node);

        NewNode := XmlElement.Create('Car', '', 'Audi');
        NewNode.SetAttribute('Id', '3');
        Node.ReplaceWith(NewNode);

        Doc.WriteTo(Result);
        Message(Result);
    end;
```

**Comment by dennisfrostlander** [comment]
Thanks for the repro. This is a bug caused by missing "encoding" attribute in the XML declaration.
