### ISSUE TITLE
Event trigger For Post Shipment action in Page 7335 not working

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1554]
Hi,

There is no Name for Post Shipment Action in Page 7335 as shown in the below screen:
![image](https://user-images.githubusercontent.com/26792519/35790333-ce080596-0a67-11e8-9d9e-12b3f286a27f.png)

When we use the same name as shown in the above screen we are getting an error as shown below:
  
![image](https://user-images.githubusercontent.com/26792519/35790358-eff73dde-0a67-11e8-938e-e214d75de51a.png)
![image](https://user-images.githubusercontent.com/26792519/35790375-05140030-0a68-11e8-8841-ed05de3c6143.png)

Please suggest us?

Thanks & Regards
Varun Reddy

**Comment by dennisfrostlander** [comment]
If name is not specified, it is defaulted to caption for actions. Try:
```
[EventSubscriber(ObjectType::Page, 7335, 'OnBeforeActionEvent', 'P&ost Shipment', true, false)]
```

**Comment by sandeepchapte** [comment]
Used the caption in the event, but still not working.

**Comment by dennisfrostlander** [comment]
This is a bug. If this action does not have a Name explicitly defined in C/SIDE, event subscribers are not working.
If you have permissions to change W1 code, the only possible workaround is to give Action 25 a name 'P&ost Shipment'.

**Comment by thpeder** [comment]
The fix is available in the latest developer preview.
