### ISSUE TITLE
Visual Studio Code : error AL0304: Length of the identifier cannot exceed 120 characters

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#1555]
I have successfully converted our App to AL code from text code with all steps. but while creating package facing error as below : 

![image](https://user-images.githubusercontent.com/5293496/35796857-e44067ce-0a83-11e8-97e9-41670aaeb7f9.png)
![image](https://user-images.githubusercontent.com/5293496/35796888-ff6b778c-0a83-11e8-9273-ef712a76465c.png)

I would like to add my DLL into project and then want to add reference to each method from DLL to my code. 

Please help me here to add DLL and use DLL's methods under my codebase.

Thanks in Advance!!!

**Comment by atoader** [comment]
Hi @chavansachin20 ! DotNet is not supported in extensions, as you can see in our FAQ https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions .
