### ISSUE TITLE
Using the Microsoft ControlAddIn "PingPong" in a separate page for a copy of "My report inbox".

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1557]
We are currently converting a development that uses Microsoft's ControlAddIn `"Microsoft.Dynamics.Nav.Client.PingPong;PublicKeyToken=31bf3856ad364e35"` in a page. We originally copied this page from the standard, and adapted it accordingly. Unfortunately we can't use this site anymore, because DotNet is no longer allowed. Is there a workaround for this, how can we avoid this problem?

```
    event PingPong();
    begin
    /*
    AddInReady := TRUE;
    PrevNumberOfRecords := COUNT;
    CurrPage.PingPong.Ping(10000);
    */
    end;

    event PingPong();
    var
        CurrNumberOfRecords: Integer;
        begin
        /*
        CurrNumberOfRecords := COUNT;
        IF PrevNumberOfRecords <> CurrNumberOfRecords THEN
          CurrPage.UPDATE(FALSE);
        PrevNumberOfRecords := CurrNumberOfRecords;
        CurrPage.PingPong.Ping(10000);
        */
        end;
```

**Comment by dennisfrostlander** [comment]
PingPong is a DotNet control add-in and is not yet available in the new development tools. We will investigate if this can be supported before .net is available.

**Comment by pzentner** [comment]
@dennisfrostlander any update here? It would really be nice to be able to use PingPong or, which might be more "compatible", implement a standard feature that raises an even on all pages after a certain time elapsed.

So, basically, implement a page property to turn on a timer, implement a page property for the interval, and then implement a new trigger that is raised when interval elapsed.

**Comment by pzentner** [comment]
Since we have not heard back yet, if we are getting the control back or another implementation, I have quickly put something together that should help out. 

You can find a replacement of PingPong [here](http://peterzentner.com/2018/07/19/dynamics-365-business-central-how-to-use-timers-in-al/).

I hope that helps a bit.

**Comment by atoader** [comment]
OnPrem it should be possible to use the .NET Control Add-In from AL https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dotnet-controladdins .

**Comment by fvet** [comment]
@atoader Any chance in getting a standard DontNet replacement for the PingPong from MS? In #5200 is was stated that PageBackgroundTasks should be used instead? Is this the way 'Report Inbox' and 'My Jobqueue' (monitor alike pages requiring a periodic autorefresh) need to be refactored?

Beside that, something about the comment _We will investigate if this can be supported before .net is available._ Will we eventually - in SaaS - have .net support again?!?

**Comment by nndobrev** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
