### ISSUE TITLE
Change function DimCaptionClassTranslate of codeunit 42 into Global [External]

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#1561]
We customized function "CaptionClassTranslate’" in codeunit 42. We were happy to see this function has a new integration event named: OnExtensionCaptionArea.
However when we moved our code to this event we found out we also using function "DimCaptionClassTranslate" which happens to be a local function.

Can this function be made global and external so we can further reduce our footprint.

**Comment by JesperSchulz** [comment]
I'm on it. Will ship with upcoming Docker image.

**Comment by RonKoppelaar** [comment]
What is the expected delivery date of the upcomming docker image?
What is the usual update frequency for the DevPreview in docker?

**Comment by JesperSchulz** [comment]
The very next Docker image does not yet contain this fix, as this fix first has to go through an approval and check-in process. Going forward, we will provide preview images through the collaborate tool. I’m afraid I don’t know the frequency yet.

**Comment by JesperSchulz** [comment]
I actually just received a little push back on the fix. A colleague of mine will reach out to you and talk to you about another solution, which might work for you.

**Comment by grobyns** [comment]
Hi Ron,
I have asked Jesper to park this request for now as I'd like to clarify some things first.
I understand you've customized Codeunit 42 CaptionManagement. There's no need to do so. We should also not have added an event here, that was a mistake I am trying to correct.

As I'm sure you know, the code in this codeunit is called by the platform when you fill in the CaptionClass property on a page control. In most cases there's just a hard coded string in the property where with some magic numbers we get out the correct caption. 
This property is however expression based which means that you can put a local function call in there as long as that returns a string. If you make it return '3,<SomeCaption>' the code in COD42 will return the first 80 characters of<SomeCaption> and that will be the caption of your control. If you make the function simply return <SomeCaption> directly COD42 will not do any parsing and just return the exact string.
Essentially, you control the caption through your own local function call and of course you can have the local function call out to your own management style codeunit where you can centralize your logic.

My suggestion is, move your customization out of COD42 into a separate codeunit of your own. Add a local function in the pages where you need this (i.e. MyCaptionClassTranslate(CaptionExpr : Text) ) and have this function now call your codeunit where you process the caption however you need.

If you feel this approach will not work for your case, please do let me know, I'd be happy to discuss this further.

Cheers,
Gert

**Comment by RonKoppelaar** [comment]
Gert,

We start investigating your proposal tomorrow and get back to you asap. My colleagues (Richard Robberse and Gerrit Peters) will work on this. I'm off work for 2 days.

**Comment by grobyns** [comment]
Super, I look forward to hearing the results :-).

**Comment by grobyns** [comment]
Any news on this issue?

**Comment by RonKoppelaar** [comment]
We refactored the code, and indeed we neither need the event subscriber nor the global function. Thanx for the provided alternate solution.
Item may be closed

**Comment by JesperSchulz** [comment]
Fantastic :-) Case closed then!
