### ISSUE TITLE
Send E-mails with out using codeunit 400 (SMTP MAIL)..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1563]
Hi 

we wanted send emails through our application with out using smtp mail codeunit to use our own smtp server details. (We don't want to use the details from SMTP Setup.)

With the our V1 we are using the following .net variable to hard code our credentials for smtp

Mail : DotNet "'Microsoft.Dynamics.Nav.SMTP, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.Microsoft.Dynamics.Nav.SMTP.SmtpMessage";

Dotnet variables are not supporting.

can someone help me to find an alternative to send emails with out using smtp setup

Thanks.

**Comment by dennisfrostlander** [comment]
If you think SMTP setup in W1 code could be modified/extended in a way that could benefit everyone, feel free to request a new event/procedure to be added.
Alternatively, you could move the SMTP handling logic to another service (such as Azure function) and then invoke it via HTTP using the HttpClient in AL.
