### ISSUE TITLE
AL Extension & Appsource 

### ISSUE THREAD

**Issue by OakleyLeon** [Microsoft/AL#1566]
Hi,

I have a few questions relating to AL extension (D365 for Financial & Operations) distribution to App Source. I’ve read through the article which explains the app submission guidelines. However, how does the trial process work within app source? What happens when its elapsed? Would I need to handle a trial period in my AL code extension?

Also, if payment was to be taken after a trial period how do we handle payments from app source. Is this done via payment from Microsoft? or do we need to provide a payment gateway integration via AL or a 3rd party.?

Any links or advice welcome.
Thanks.

**Comment by dennisfrostlander** [comment]
Related to #1519
