### ISSUE TITLE
Renaming dataitem in XMLPort renames the SourceTable instead of Name

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1569]
I created a simple XMLPort which imports No. and Name as textfields to the customer.

```
...
    schema
    {
        tableelement(Customer; Customer)
        {


            fieldelement(No; Customer."No.")
            {

            }
            fieldelement(Name; Customer.name)
            {

            }
...
```
When renaming Customer to Cust (with F2), the SourceTable in the tableelement is renamed instead of the Name.

As seen in:
![2018-02-07_13-29-06](https://user-images.githubusercontent.com/34303738/35916598-33b4a90e-0c0b-11e8-82aa-11e948aa931e.gif)

The given error is:
`[AL] None of the specified parent table elements has the name Cust.`

Changing the SourceTable of the tableelement back to Customer and renaming the Name part to Cust, solves the problem.

NAV2018 (CU0)

E:
Renaming the Name tableelement doesn't change the fields SourceField.

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the refreshed VSIX file with NAV 2018 CU 5 DVD (May 2018 CU)
