### ISSUE TITLE
Suggestion: adjust docu for txt2al

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#157]
If you try to run the txt export and txt2al tool in the Azure image like described in the docu, it fails. I think the reason is that the database and server names don't match with the default settings in the Azure image. It works if you run as follows (I also wouldn't use table 66668 as sample, as it is not available in the demo db)

finsql.exe  Command=ExportToNewSyntax, File=exportedObjects.txt, Database="Demo Database NAV (10-0)", ServerName=.\NAVDEMO ,Filter=Type=table;ID=225

I would also explicitly state that txt2al is in the RTC folder as I tried to use finsql from the Service folder and therefore the docu "The tool is located in the same folder as finsql.exe" also didn't work for me

**Comment by StanislawStempin** [comment]
Thank you for the suggestions, we will update the documentation.

**Comment by StanislawStempin** [comment]
The blog post has been updated
