### ISSUE TITLE
You must specify open and close parenthesis after 'Page' and other warnings

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1570]
I love the warnings and suggestions of making code better, but there are some that either don't make sense or are not working.

When you have something like this on a page:

CurrPage.SubPageControl.Page.FunctionInSubPage(Parameter);

You get the warning "you must specify open and close parenthesis after 'Page'. Ok, let's do that:

CurrPage.SubPageControl.Page().FunctionInSubPage(Parameter);

Now you get an error "The property 'Page' is used as a function". So, this means the warning just made me change my code to something that doesn't compile. This should be fixed in my eyes.

Also, it seems like a lot of the "built in functions" are declared as procedures instead of properties, so you always get a warning that you should specify an open and close parenthesis. For instance, "Record.IsEmpty" - "IsEmpty" should be a property and not a function - it holds the state of the record, it doesn't "make" the record empty. However, currently, you have to use "Record.IsEmpty()" to not get a warning.

So, my suggestion would be to fix the above warning with the "Page" issue and review existing functions and change the declaration or at least exclude those from the warnings or something similar.

**Comment by dennisfrostlander** [comment]
Warning and suggests (i.e. code analysis) is currently an experimental feature. Thanks for the report.

**Comment by qutreson** [comment]
I think this has been handled in: #1861.
