### ISSUE TITLE
Rename Field of a Table don't work, when the Field is used in a CalcFormula

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1571]
Rename of a table field, used in a CalcFormula don't work.

1) Rename the field:
![grafik](https://user-images.githubusercontent.com/15800069/35960623-b3296ec8-0caa-11e8-93b7-95c426724f91.png)

2) The result:
![grafik](https://user-images.githubusercontent.com/15800069/35960668-d7a01fcc-0caa-11e8-8c6d-07d895dfeeea.png)

I believe, the reference of the Field is not counted:
![grafik](https://user-images.githubusercontent.com/15800069/35960702-05db6194-0cab-11e8-901e-029293b67f45.png)

**Comment by megel** [comment]
I have found a new problem:

Rename of Field "Name" (the Cursor is between 'N' and 'm')
![grafik](https://user-images.githubusercontent.com/15800069/36206015-22cf47ee-1191-11e8-9e5c-eddcb7d74b58.png)

Here is the sample code:
```javascript
table 50100 "My Table with a long Name1"
{
    fields
    {
        field(1;Code;Code[20]) { }
        field(2;Name;Text[50]) { }
    }
    keys
    { key(PK; Code) { Clustered = true; } }
}

table 50101 "My Table 2"
{
    fields
    {
        field(1;ID;Integer) { }
        field(2; "Locale Code"; Code[10]) { }
        field(3; "Locale Name"; Text[5])
        {
            FieldClass  = FlowField;
            CalcFormula = lookup("My Table with a long Name1".Name where (Code = field("Locale Code")));
            Editable    = false;
        }
    }
    keys { key(PK; ID) { Clustered = true; } }    
}
```

When changing the `Name` to `"Name"` VS Code provide the correct field name.

**Comment by qutreson** [comment]
Hi @megel, thank you for logging your issues! 

I could reproduce both of them and as you guessed, the first one issue is a bug of the compiler that cannot find the reference of the field MyNo in the CalcFormula. We are working on a fix which would then fix CodeLens, renaming and hovering. 

Concerning the second issue, it seems to be a VS Code bug. The initial text shown inside of the rename text field is not correct, but if you remove the content and enter your new value, it works perfectly as you can see in the gif below:

![vscoderenamingissue](https://user-images.githubusercontent.com/31541422/38940613-dc72c7aa-432a-11e8-9095-cbfb81564033.gif)

I created an issue on their github.

**Comment by qutreson** [comment]
Re-labeling the bug as external as it is for now an external issue related to VS Code.
Here is the main thread to follow on their github: [#7340](https://github.com/Microsoft/vscode/issues/7340)

**Comment by JohanStenberg100** [comment]
@megel Thanks for reporting this issue. I can no longer reproduce your **2** first issues with AL extension version 2.0.48254 and VS code version 1.28.2.

For your third issue - the renaming issue, please follow this github issue: #498.

Thanks!
