### ISSUE TITLE
[Suggestion] Allow us to add UsageCategory to pageextensions

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#1573]
I created a pageextension on the 'FA Depreciation Books' page. This page isn't searchable in the client.

```
pageextension 50090 FADepreciationBookOverviewExt extends "FA Depreciation Books"
{
    usagecategory = Lists;
    layout
    {
        addafter("FA No.")
        {
            field(SerialNo; SerialNo)
            {

            }
        }
    }
}
```
This gives the following error:
`[AL] The property 'usagecategory' cannot be customized.`

So in order to have this page, I recreated it as a new page in my extension.

**Comment by RonSkalski** [comment]
I agree. I had to create a custom page that is a copy of a standard page for the same reason.

**Comment by Pieterheinevdm** [comment]
added an idea for this, please vote
https://experience.dynamics.com/ideas/idea/?ideaid=cdc99444-4b97-e911-80e7-0003ff68d318

**Comment by dtkb** [comment]
see also https://github.com/microsoft/AL/issues/4006

**Comment by dtkb** [comment]
Please upvote the Idea: https://experience.dynamics.com/ideas/idea/?ideaid=cdc99444-4b97-e911-80e7-0003ff68d318

**Comment by atoader** [comment]
Thanks @dktb! I'll close this. Let's focus the discussion on the BCIdea entry.

**Comment by SirBETE** [comment]
> Please upvote the Idea: https://experience.dynamics.com/ideas/idea/?ideaid=cdc99444-4b97-e911-80e7-0003ff68d318

Issue is nearly 3y old, yes it still isn't possible, but no need to repost the existing link. :s


> Thanks @DKTB! I'll close this. Let's focus the discussion on the BCIdea entry.

Ty for closing it.

**Comment by dtkb** [comment]
> Issue is nearly 3y old, yes it still isn't possible, but no need to repost the existing link. :s

I didn't see it was already posted, just found that Idea spearately and posted the link on a couple of related issues here. Sorry for trying to help!

**Comment by SirBETE** [comment]
> > Issue is nearly 3y old, yes it still isn't possible, but no need to repost the existing link. :s
> 
> I didn't see it was already posted, just found that Idea spearately and posted the link on a couple of related issues here. Sorry for trying to help!

Np, ty for doing it. :)
Your reaction brought this issue back under the attention of Microsoft, which is always good.
(although I would have rather seen it to be fixed instead of closed :( )

**Comment by atoader** [comment]
We are evaluating ideas from partners and developers received through GitHub and BCIdeas. On the last count, we are looking at about 1000 different suggestions just in the development area. I use any opportunity to remove duplicates :) . That being said, even if we remove all duplicates, we will still be left with well over 500 different features which will take between a few days and a few months to implement. It will take some time until we can address all of the great feedback we've received.
