### ISSUE TITLE
[Suggestion][Question] Add UsageCategory to XMLports

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#1574]
Allow the property UsageCategory for XMLports.
The webclient can't show the requestpage of XMLports (why?) (but the Windows client can).

Currently the only option to run XMLports is via an action with the OnAction code
 `xmlport.run(50000, false, true);`

**Comment by dtkb** [comment]
> The webclient can't show the requestpage of XMLports

Thankfully it does nowadays!

> This rule applies only to Business Central Spring 2019 and earlier versions. Request pages for XMLPorts are supported as of Business Central 2019 release wave 2.

- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0001-requestpageofxmlportscannotbedisplayed

**Comment by atoader** [comment]
We are working on consolidating feedback received across multiple channels to a single location so that we can better prioritize suggestions that involve multiple areas of the product

Would you mind closing this issue and posting it in our Ideas forum at https://aka.ms/BusinessCentralideas or vote up the idea if it is already there?

**Comment by SirBETE** [comment]
> > The webclient can't show the requestpage of XMLports
> 
> Thankfully it does nowadays!
> 
> > This rule applies only to Business Central Spring 2019 and earlier versions. Request pages for XMLPorts are supported as of Business Central 2019 release wave 2.
> 
> * https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0001-requestpageofxmlportscannotbedisplayed

This issue is nearly 3y old ...
I created it cause it wasn't possible in BC13 back then.



> We are working on consolidating feedback received across multiple channels to a single location so that we can better prioritize suggestions that involve multiple areas of the product
> 
> Would you mind closing this issue and posting it in our Ideas forum at https://aka.ms/BusinessCentralideas or vote up the idea if it is already there?

Check :)

**Comment by The-J-Bird** [comment]
I think this issue needs reopening.   The wording of the OP question was slightly wrong, but the principle is correct.

The Web Client doesnt allow you to add XML Ports to the main menu by updating the "UsageCategory".  This can be used to add items to the menu:
![image](https://user-images.githubusercontent.com/51637057/200373988-f970f967-f0b6-443b-b2f0-6e18782df0cf.png)

UsageCategory only works for Pages and Reports - https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-usagecategory-property

Unless there is another way to add XMLPorts and CodeUnits to the menu?  (Work around, would be to have a Report which users run, which in turn runs the XML Port / Codeunit?

**Comment by BertDeTemmerman** [comment]
> I think this issue needs reopening. The wording of the OP question was slightly wrong, but the principle is correct.
> 
> The Web Client doesnt allow you to add XML Ports to the main menu by updating the "UsageCategory". This can be used to add items to the menu: ![image](https://user-images.githubusercontent.com/51637057/200373988-f970f967-f0b6-443b-b2f0-6e18782df0cf.png)
> 
> UsageCategory only works for Pages and Reports - https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-usagecategory-property
> 
> Unless there is another way to add XMLPorts and CodeUnits to the menu? (Work around, would be to have a Report which users run, which in turn runs the XML Port / Codeunit?

I created it now 4y ago, cause the requestpage of xmlports wasnt supported to be shown.
I think it's better to create a new one, and refer to this issue.
Cause I doubt MS checks the closed issues ...
