### ISSUE TITLE
[Enhancement] Add lookuppageid (and drilldownpageid) to TAB365 Analysis View Entry

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1576]
For easier navigation in the client

**Comment by JesperSchulz** [comment]
I assume you would like Page 558 Analysis View Entries to be the lookup and drilldown page?

**Comment by SirBETE** [comment]
Yep :)

**Comment by JesperSchulz** [comment]
That is definitely possible. I'm on it. Thanks for the suggestion!

**Comment by SirBETE** [comment]
Thank you very much! :D
Have a nice day.

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
