### ISSUE TITLE
Expose Functions in NAVDACH-CU "Format Adress Comfort"

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#1577]
In the German Codeunit 5005397 "Format Adress Comfort" the functions are not exposed as External. Please Change that.

**Comment by JesperSchulz** [comment]
Consider it done.

**Comment by dtacconi** [comment]
Thanks JulianTillmann to file also a Support Request to back port to NAV 2018. 
The changes will also be included in the standard application since NAV 2018 CU 5 (May 2018).
