### ISSUE TITLE
Setup and Help Resources

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#158]
Hi,
ich have a question to Setup and Help Resources in NAV. What is the correct way to publish my own learning Video to my Extension? 

![setup and help resources](https://cloud.githubusercontent.com/assets/26924867/25274728/b7788c2a-2691-11e7-9dc1-69888698910b.png)

So, are there any Events to make an entry in table 1803? Can you give an example?

**Comment by StanislawStempin** [comment]
You can have a look here:
http://msdynamicsnav.guru/wp/gunnar/building-assisted-setup-for-dynamics-365-for-financials/0026044/
http://thinkaboutit.be/2016/12/webinar-new-al-functions-in-nav-2017/

The new AL syntax for subscribing to the events mentioned in these posts is:
```
[EventSubscriber(ObjectType::Table, 1808,'OnRegisterAssistedSetup', '', true, true)]
procedure Register(tempAggregatedAssistedSetup : record "Aggregated Assisted Setup" temporary);
begin
end;
```
