### ISSUE TITLE
Need new external method HtmlDecode in Codeunit 10 Type Helper

### ISSUE THREAD

**Issue by StHillmann** [Microsoft/AL#1587]
Hi,

while there is an existing method "HtmlEncode" in Codeunit 10 "Type Helper", we need an corresponding method "HtmlDecode".

Code like this:
```
[External] HtmlDecode(VAR Value : Text) : Text
Value := HttpUtility.HtmlDecode(Value);
EXIT(Value);
```
Due to connecting external web services, we need this to import an html encoded text.

Kind Regards

Stefan

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! I will pick this one up asap.
Going forward, could I refer you to the GitHub repo https://github.com/Microsoft/cal-open-library when you would like us to add library functions? Especially, if you should have requests, which are a little more complex than the 3 lines of code you would like us to add this time ;-)
I wish you a nice weekend. And thanks again. Every contribution is much appreciated.
