### ISSUE TITLE
OnUninstallAppPerCompany

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1588]
Thank you for the CU2 that preserves the new data in the extensions.
That is awesome and now we can start developing seriously.

However, what do I do if I actually want to delete the data on uninstalling an app.

Can I make a OnUninstallAppPerCompany procedure?

/Peik

**Comment by dennisfrostlander** [comment]
No, there is no such procedure, but you can use the [Sync-NavApp](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=dynamicsnav-ps-2018) commandlet and run it with Clean mode.

**Comment by peikba** [comment]
Ok Thank you,
I used the "schemaUpdateMode": "Recreate" in the launch.json instead.

/Peik
