### ISSUE TITLE
Properties to use with modify in extensions

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1589]
Hi,

Which properties can be altered by modify in extensions.
I have seen that Visible can be changed but that I cannot change OptionMembers.  
Is there a list of the properties that can be changed and 
would it be possible to alter the OptionMembers as well?

/Peik

**Comment by StanislawStempin** [comment]
Below you can find a fairly complete list of properties that can be modified. OptionMembers cannot be modified right now. It is a deeper platform change to allow extensible options/enums and is on our long-term backlog.

All elements
- Description
- Caption/CaptionML

Table
- DataCaptionFields

Table field/Page field
- CaptionClass
- OptionCaption/OptionCaptionML
-ClosingDates
-Width

Page
-InsuctionalText/InstructionalTextML
-DataCaptionExpression
-PromotedActionCategories/PromotedActionCategoriesML

Page field
- Style
- ApplicationArea
- Visible
- StyleExpr
- ToolTip/ToolTipML
- Enabled
- HideValue
- ShowCaption
- Importance
- QuickEntry
- ODataEDMType

Page field group 
- Visible
- Enabled
- InstructionalText/InstructionalTextML
- FreezeColumn

Page part
- Visible
- Enabled
- ToolTip/ToolTipML

Page action group
- ToolTip/ToolTipML
- Visible
- Enabled

Page action
- ToolTip/ToolTipML
- Visible
- Enabled
- ApplicationArea
- Promoted
- PromotedIsBig
- PromotedOnly
- PromotedCategory
- ShortcutKey
-InFooterBar

**Comment by peikba** [comment]
Thank you Stanislaw, that was very useful
