### ISSUE TITLE
Download symbols from Local server -> InternalServerError

### ISSUE THREAD

**Issue by tothszabolcs90** [Microsoft/AL#159]
Download symbol -> 
Local server -> 
Could not download symbols. Please see the Visual Studio Code output log for more details. ->

[2017-04-21 12:40:53.25] Using reference symbols cache path: c:\Users\tothsz\Documents\AL\ALProject3\packages
[2017-04-21 12:40:53.28] Downloading from http://localhost:7049/navision_main/dev/symbols/Microsoft/US/10.0.0.0 ... Error (InternalServerError)
[2017-04-21 12:40:53.28] Downloading from http://localhost:7049/navision_main/dev/symbols/Microsoft/System/10.0.0.0 ... Error (InternalServerError)
[2017-04-21 12:40:53.28] Could not download reference symbols

launch.json is in default state:

// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
{
	"version": "0.2.0",
	"configurations": [

		{
			"type": "al",
			"request": "publish",
			"projectRoot": "${workspaceRoot}",
			"packageFileName": "${command:resolvePackageFileName}",
			"name": "Cloud",
			"startupObjectId": 22
		},
		{
			"type": "al",
			"request": "publish",
			"projectRoot": "${workspaceRoot}",
			"packageFileName": "${command:resolvePackageFileName}",
			"name": "Local server",
			"server": "http://localhost",
			"serverInstance": "navision_main",
			"tenant": "default",
			"windowsAuthentication": true,
			"startupObjectId": 22
		}
	]
}

What is the solution for this issue?

Thank you.

**Comment by waldo1001** [comment]
I think you need to remove the "Cloud"-part, as it just doesn't make sense to have two configurations (in my opinion).

I removed it - and it worked.

**Comment by tfenster** [comment]
Did you change the user when creating the Azure machine? I did and after that got the same error. I had to enable access for my user in the NAV database, after that it worked for me

**Comment by tothszabolcs90** [comment]
Thank you guys, the user access was the issue:

The configuration says: "windowsAuthentication": true
In Users table I have found only one database user with the same name as my Windows user with empty Windows User Name. After I have added my windows user, VS Code successfully updated the reference symbols.

Sorry for the reported issue, it was my bad.
