### ISSUE TITLE
schemaUpdateMode

### ISSUE THREAD

**Issue by gnaaktgeboren** [Microsoft/AL#1591]
When using the schemaUpdateMode setting in launch.json the error "Property schemaUpdateMode is not allowed." is shown.

I'm using Nav version 11.0.19846.0 and AL language extension version 0.12.15355.

**Comment by sgiordy** [comment]
With CU2 (AL extension 0.12.16641) now it works
https://blogs.msdn.microsoft.com/nav/2018/02/06/cumulative-update-02-for-microsoft-dynamics-nav-2018-has-been-released/

**Comment by gnaaktgeboren** [comment]
Thanks, I've installed CU2 and that solved the issue.

**Comment by olisterrcf** [comment]
I'm using NAV 2018 CU2. I'm still not getting 'schemaUpdateMode' property in my launch.json Is there any function that should be used other than setting this property?

**Comment by gnaaktgeboren** [comment]
I had the same issue.
Try to remove the extension from VSCode and then reinstall it again.

**Comment by olisterrcf** [comment]
Hi,
I've updated the VSCode extension and even updated the Visual Studio Code. Still issue persist

**Comment by StanislawStempin** [comment]
You need to add this parameter to an existing launch.json. You should see it in IntelliSense if you're using the CU2 version of the AL Language extension.

**Comment by Linty1995** [comment]
Hi @olisterrcf , I had the same problem but it was solved by reinstalling ALLanguage.vsix,

**Comment by olisterrcf** [comment]
Hi, 
It worked. I had to manually install the VSIX file from "CU 02 NAV 2018 NA\NAV.11.0.20348.NA.DVD\ModernDev\program files\Microsoft Dynamics NAV\110\Modern Development Environment" path. Downloading from the Marketplace doesn't work.

**Comment by StanislawStempin** [comment]
That's correct. In the future we aim to handle all NAV versions with a single VSIX available from the Marketplace. However, for now there is strict matching of the VSIX and the corresponding NAV server, please see: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use
