### ISSUE TITLE
Sender in OnOpenPage

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#1593]
It would be practical if in all OnOpenPage events always the current page is transferred as a sender.

**Comment by JesperSchulz** [comment]
Thank you for your suggestion. I have added the work to our backlog to be assesed and prioritzed against other work loads in the future, as this is a bigger investment.

**Comment by qutreson** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
