### ISSUE TITLE
Constant Value xx is outside the range for a Date

### ISSUE THREAD

**Issue by DennisReinecke** [Microsoft/AL#1594]
Hey,

was trying to set a date constant. it doesn't matter which constant value i use (expect 0D)

'Constant value '112710D' is outside the range for a Date' at: '7,18' source: 'AL' code: 'AL0191'
example from https://docs.microsoft.com/en-us/dynamics-nav/date-data-type
codeunit 50010 test
{
    procedure test();
    var
        Date1: Date;
    begin
        Date1 := 112710D;
        MESSAGE(FORMAT(Date1));
        Date1 := 11271810D;
        MESSAGE(FORMAT(Date1));
    end;
}

Version W1CU02 ; AL 0.12.16641

Did I miss something?

**Comment by srenders** [comment]
Jip: Date is locale independent in vscode and supports only: yyyy-mm-ddD.
https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-differences
