### ISSUE TITLE
Intellisense is not providing possible values on const part of TableRelation and CalcFormula properties

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1596]
When creating a conditional _TableRelation_ or a _CalcFormula_ Intellisense is not providing possible values on **const** part of TableRelation and CalcFormula properties when the field involved is a Option field.

Intellisense always shows true and false as possible values. 

As setting up the TableRelation and CalcFormula properties is quite a challenge in VSCode this omission surely does not make it easier.

**BTW**: it would be really useful to have code snippets for both the TableRelation and CalcFormula properties to have an example to start from.

**Comment by StanislawStempin** [comment]
Thanks for reporting, Luc. This is a known gap and is on our long-term backlog

**Comment by BazookaMusic** [comment]
This is fixed in the latest release, so I will close it.
