### ISSUE TITLE
UPLOADINTOSTREAM for multiple files

### ISSUE THREAD

**Issue by hrolfurh** [microsoft/AL#1597]
Hi,

Is there any way we can upload multiple files using UPLOADINTOSTREAM?

Best regards,
Hrólfur

**Comment by StanislawStempin** [comment]
That is unfortunately not possible. A workaround I have seen used by some partners is to use a ZIP file and unpack it server-side. 
We will keep this question as a suggestion for improvement in the future.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
