### ISSUE TITLE
'DataClassification' property

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#1598]
I'm using build 20539 and noticed that when using the table snippet there's a new "DataClassification" property added to the table and field. What's the significance of this property?

![image](https://user-images.githubusercontent.com/5204734/36159698-5d41dac0-10ad-11e8-981f-a64764ca6da7.png)

**Comment by StanislawStempin** [comment]
This feature is not publicly released/disclosed yet and will be first available in production when D365 Tenerife is released. We will be providing documentation and more information within a few weeks. The feature will be used for classifying data in the context of GDPR.

**Comment by MikeGlue** [comment]
ok thanks for the reply @StanislawStempin

**Comment by NKarolak** [comment]
https://blogs.msdn.microsoft.com/nav/2018/03/08/classifying-data-in-dynamics-nav/
