### ISSUE TITLE
CaptionML in Page ContentArea

### ISSUE THREAD

**Issue by iWorksJared** [Microsoft/AL#1599]
In post #1589, it is said that CaptionML can be modified for all Elements. However, it is failing to compile here:

area(creation)
    {
      CaptionML = ENU='New',
ESM='Nuevo',
FRC='Nouveau',
ENC='New';
 action("action name"){}

This happens anywhere the "Area" element is used.

Is there a solution to this problem, or is CaptionML not supported for this section of a page?

**Comment by peikba** [comment]
My understanding is that CaptionML will be discontinued in later versions and that only the Caption property should be used.

The translation will be handled via xliff files:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-work-with-translation-files

**Comment by iWorksJared** [comment]
Thank you for the quick response. Much appreciated.
