### ISSUE TITLE
Txt2Al -> Acess is denied.

### ISSUE THREAD

**Issue by tothszabolcs90** [Microsoft/AL#160]
I have tried to convert the exported txt to an al file.

Error message: Access is denied.

Please give me an example with real data how can I use it. CMD running as Admin.

Thank you.

**Comment by tfenster** [comment]
I wrote about it with a bit more detail [here](http://navblog.infoma.de/index.php/2017/04/23/converting-traditional-cal-code-to-al-and-finally-having-where-used/). Maybe that helps?

**Comment by tothszabolcs90** [comment]
It helped, thank you!
