### ISSUE TITLE
Jan 2018 Update & Feb 2018 Update Release plan

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1600]
Hi,

Can you let us know when the Jan 2018 Update and Feb 2018 Update will be released?

Also let us know if these updates are released in any new way than the previous ones?

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
The next update that we are releasing will be Feb 2018 update. It will be released later this week. 
It will be released the same way as previous ones.

**Comment by bachii1010** [comment]
Hi Stanis,

Thanks for the update, so there will be no Jan 2018 Update

**Comment by StanislawStempin** [comment]
Correct, we have just released the February 2018 update.
