### ISSUE TITLE
NAV 2018 extensions error message multi languages

### ISSUE THREAD

**Issue by gnaaktgeboren** [Microsoft/AL#1602]
I've added "features": "TranslationFile" to my app.json file to enable translation of my extension in the future.

But I noticed that when i create an error message this text is not added to the translation file.
Where can I define this error message so it ends up in the translation file?

**Comment by DennisReinecke** [comment]
You have to define variables as labels.
https://docs.microsoft.com/de-de/dynamics-nav/developer/devenv-work-with-translation-files

**Comment by gnaaktgeboren** [comment]
Thank you. Solved my question
