### ISSUE TITLE
REP492 Copy Purchase Document - Always IncludeHeader

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1603]
In REP492 Copy Purchase Document, we want `IncludeHeader `to be enabled by default.
The "Last used options and filters" gets overruled by the code in the `OnOpenPage` trigger.

How can we solve this?
Can MS add an event to change those request page parameters?

Another idea would be to use `InitializeRequest`, but this function will also be overruled by "Last used options and filters" and the `OnOpenPage` trigger.

**Comment by JesperSchulz** [comment]
Closing issue, as the issue seems to have been addressed.
