### ISSUE TITLE
[Event Request] New Events in the function "FindAmtForAppln" in Codeunit 12

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1607]
In the function "FindAmtForAppln" various events are needed to be able to influence the "AppliedAmount". Otherwise, it is not yet possible to intervene effectively in the posting routines in order to determine the clearing successfully.

I copied the new function for this once, what it should look like from my point of view. The comment "Event"stands before each required event. Unfortunately, some new beginnings and endings are needed to make the conversion work.

As with all other events, the values should all be passed as VAR so that they can be changed. I'm just assuming so now.

```
LOCAL FindAmtForAppln(VAR NewCVLedgEntryBuf : Record "CV Ledger Entry Buffer";VAR OldCVLedgEntryBuf : Record "CV Ledger Entry Buffer";VAR OldCVLedgEntryBuf2 : Record "CV Ledger Entry Buffer";VAR AppliedAmount : Decimal;VAR AppliedAmountLCY : Decimal;V
OnBeforeFindAmtForAppln(
  NewCVLedgEntryBuf,OldCVLedgEntryBuf,OldCVLedgEntryBuf2,AppliedAmount,AppliedAmountLCY,OldAppliedAmount);

IF OldCVLedgEntryBuf2.GETFILTER(Positive) <> '' THEN BEGIN
  IF OldCVLedgEntryBuf2."Amount to Apply" <> 0 THEN BEGIN
    IF (PaymentToleranceMgt.CheckCalcPmtDisc(NewCVLedgEntryBuf,OldCVLedgEntryBuf2,ApplnRoundingPrecision,FALSE,FALSE) AND
        (ABS(OldCVLedgEntryBuf2."Amount to Apply") >=
         ABS(OldCVLedgEntryBuf2."Remaining Amount" - OldCVLedgEntryBuf2."Remaining Pmt. Disc. Possible")))
    THEN BEGIN

// Event
    OnBeforeFindPositiveAppliedAmountIfAmountToApplyGreaterThenZeroAndCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

      AppliedAmount := -OldCVLedgEntryBuf2."Remaining Amount"

// Event
      OnAfterFindPositiveAppliedAmountIfAmountToApplyGreaterThenZeroAndCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

    END ELSE BEGIN

  // Event
      OnBeforeFindPositiveAppliedAmountIfAmountToApplyZeroAndNotCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

      AppliedAmount := -OldCVLedgEntryBuf2."Amount to Apply"

  // Event
      OnAfterFindPositiveAppliedAmountIfAmountToApplyZeroAndNotCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

  END ELSE BEGIN

  // Event
    OnBeforeFindPositiveAppliedAmountIfAmountToApplyZero(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

    AppliedAmount := -OldCVLedgEntryBuf2."Remaining Amount";

  // Event
    OnAfterFindPositiveAppliedAmountIfAmountToApplyZero(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

  END;
END ELSE BEGIN
  IF OldCVLedgEntryBuf2."Amount to Apply" <> 0 THEN
    IF (PaymentToleranceMgt.CheckCalcPmtDisc(NewCVLedgEntryBuf,OldCVLedgEntryBuf2,ApplnRoundingPrecision,FALSE,FALSE) AND
        (ABS(OldCVLedgEntryBuf2."Amount to Apply") >=
         ABS(OldCVLedgEntryBuf2."Remaining Amount" - OldCVLedgEntryBuf2."Remaining Pmt. Disc. Possible")) AND
        (ABS(NewCVLedgEntryBuf."Remaining Amount") >=
         ABS(
           ABSMin(
             OldCVLedgEntryBuf2."Remaining Amount" - OldCVLedgEntryBuf2."Remaining Pmt. Disc. Possible",
             OldCVLedgEntryBuf2."Amount to Apply")))) OR
       OldCVLedgEntryBuf."Accepted Pmt. Disc. Tolerance"
    THEN BEGIN

// Event
      OnBeforeFindNotPositiveAppliedAmountIfAmountToApplyGreaterThenZeroAndCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

      AppliedAmount := -OldCVLedgEntryBuf2."Remaining Amount";
      OldCVLedgEntryBuf."Accepted Pmt. Disc. Tolerance" := FALSE;

// Event
      OnAfterFindNotPositiveAppliedAmountIfAmountToApplyGreaterThenZeroAndCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

    END ELSE BEGIN

  // Event
      OnBeforeFindNotPositiveAppliedAmountIfAmountToApplyZeroAndNotCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

      AppliedAmount := ABSMin(NewCVLedgEntryBuf."Remaining Amount",-OldCVLedgEntryBuf2."Amount to Apply")

  // Event
      OnAfterFindNotPositiveAppliedAmountIfAmountToApplyZeroAndNotCheckCalcPmtDisc(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

  END ELSE BEGIN

  // Event
    OnBeforeFindNotPositiveAppliedAmountIfAmountToApplyZero(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

    AppliedAmount := ABSMin(NewCVLedgEntryBuf."Remaining Amount",-OldCVLedgEntryBuf2."Remaining Amount");

  // Event
    OnAfterFindNotPositiveAppliedAmountIfAmountToApplyZero(AppliedAmount,OldCVLedgEntryBuf2,NewCVLedgEntryBuf);

  END;
END;
```

Warning, since the source code is very wide, it breaks beyond the edge of the code area. So not everything is visible here on GitHub, because the issue view is not wide enough. Please scroll the code part to the right, so that everything is visible!

**Comment by AlexanderYakunin** [comment]
Does it make sense to implement Handled pattern in OnBeforeFindAmtForAppln event and let you write you own logic for defining AppliedAmount and EXIT just after? Implementing so many events before/after each assignment looks too sophisticated from my point of view.

**Comment by FSharpCSharp** [comment]
@AlexanderYakunin 
And how is that possible? To do this I would need full access to all the variables of the code unit 12, and so many local variables are changed within this function, so it doesn't really make sense to implement it all over again.

**Comment by AlexanderYakunin** [comment]
Function use 6 parameters and no local variables. It also use calls to simple methods in codeunit PaymentToleranceMgt.CheckCalcPmtDisc and CurrExchRate.ExchangeAmount. That is all needed, so you don't need access to other global variables in COD12.

FindAmtForAppln(VAR NewCVLedgEntryBuf : Record "CV Ledger Entry Buffer";VAR OldCVLedgEntryBuf : Record "CV Ledger Entry Buffer";VAR OldCVLedgEntryBuf2 : Record "CV Ledger Entry Buffer";VAR AppliedAmount : Decimal;VAR AppliedAmountLCY : Decimal;VAR OldAppliedAmount : Decimal;ApplnRoundingPrecision : Decimal)

So you will be able to make you own function to find AppliedAmount using OnBefore event with added Handled parameter. 

OnBeforeFindAmtForAppln( NewCVLedgEntryBuf,OldCVLedgEntryBuf,OldCVLedgEntryBuf2,AppliedAmount,AppliedAmountLCY,OldAppliedAmount,Hanlded);
IF Handled THEN
  EXIT;

**Comment by FSharpCSharp** [comment]
@AlexanderYakunin 
Thank you for the quick answer. OK, but I asked in another topic ready for the Handled Event. It has been said that you are not sure if it is being used or not. Now that you're suggesting the Handled Event itself, it's a good idea that it can be implemented.

We are happy to do as you suggest!
