### ISSUE TITLE
New request for Codeunit 700

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1608]
I need to add Global function in codeunit 700. I've tried creating an Integration Event in C/AL and calling it in AL but it throws error. How to resolve these?
![git1](https://user-images.githubusercontent.com/24870777/36297406-a7ca1694-1318-11e8-9894-decd9879f1a4.png)

![git2](https://user-images.githubusercontent.com/24870777/36297413-b078a724-1318-11e8-98c5-6acbe507cbf4.png)

**Comment by StanislawStempin** [comment]
Have you regenerated the application symbols using C/SIDE as described here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side ?

**Comment by Chris-Dsilva** [comment]
Yes I've done that

**Comment by StanislawStempin** [comment]
Can you show the signature of the new global function that you added in codeunit 700? Is it an Integration Event?  Does it have parameter named RecordRef?

For the second error - you cannot have a return value for event subscribers. Delete the **: Integer;** part

**Comment by Chris-Dsilva** [comment]
I deleted the Integer part and it worked.
