### ISSUE TITLE
Wish: Add a task recorder for support cases

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1609]
There was a very interesting [blog entry](https://blogs.msdn.microsoft.com/axinthefield/integration-testing-using-the-systest-framework-and-task-recorder-in-dynamics-365-for-finance-and-operations-to-create-integration-tests/) about Dynamics 365 for Finance and Operations in the last few days. It describes how the user can record a way, so that errors can be easily corrected and the click distance can be determined automatically. I think it would be really cool if Dynamics NAV could provide a similar functionality to the user. This would make support much easier. Could you take this once and discuss it with the team? This would make it really easy for the user to record the way he takes within the application and then send it directly to support. Furthermore, the description would be much more precise than if you had to explain it manually.

**Comment by NKarolak** [comment]
I am not sure whether some additinal, integrated recorder is really necessary: did you ever try the integrated Windows app [Steps Recorder](url)?

**Comment by FSharpCSharp** [comment]
Yes, it has already been extensively used by our customers. But he has some problems, especially with the web client. The results are far from satisfactory. In addition, our customers don't necessarily want to transfer their complete screen, but only describe the resulting steps.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. This is something we are aware of and acknowledge as a valuable scenario. We will use this entry for tracking.

**Comment by kalberes** [comment]
It is in the not so far pipeline.
