### ISSUE TITLE
Help certifying a .navx file with cert

### ISSUE THREAD

**Issue by garfunko** [Microsoft/AL#161]
Hi,

I am very new to this.

I am trying to certify a .navx file using my company wildcard pfx certificate. 

I am using either of the following commands with no luck:

SignTool sign /f adnm.pfx /p password /t http://timestamp.verisign.com/scripts/timstamp.dll TAG365.navx
SignTool sign /f adnm.pfx /p password TAG365.navx

When I have the /debug on, It tells me error with after private key filter, 0 certs were left. I've gone through lots of google searches with no luck.

Anyone can give me a hand?

**Comment by StanislawStempin** [comment]
Hi, 
What are you trying to achieve? There is no signing procedure for Extensions V2 created using the new Dev Tools.
