### ISSUE TITLE
Report making results in error CS0012

### ISSUE THREAD

**Issue by Phfo** [Microsoft/AL#1611]
Make of report results in : 
error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by StanislawStempin** [comment]
Could you please provide more information about how you ran into this error? Is it when deploying a newly created report object?

**Comment by Phfo** [comment]
It was indeed a newly created report object.
I've just found a way of deploying it by commenting the autoformat expressions on a used table field.
 //AutoFormatExpression = "Currency Code";
//AutoFormatType = 1;            
Maybe this information can help ?

**Comment by StanislawStempin** [comment]
Thanks, this is helpful information.

**Comment by atoader** [comment]
HI @Phfo ! Can you reproduce on the latest developer preview? We believe this should be fixed.

**Comment by Phfo** [comment]
It's ok now. Thanks.
