### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by iWorksJared** [Microsoft/AL#1613]
Is there a way to resize images. In Item #115 it shows how to upload a picture, but i am wondering if there is a way to set the width and height before uploading it.

Thanks

**Comment by mrabus** [comment]
I guess there is no way to do that with NAV tools right now.

Vjeko showed a way to resize images in his presentation at NAV Techdays (Link: https://www.youtube.com/watch?v=f10lFZtUWGE). 

Hope this helps

**Comment by StanislawStempin** [comment]
While there is no standard NAV way to do it you can consider contributing a .NET wrapper to the https://github.com/Microsoft/cal-open-library/

**Comment by iWorksJared** [comment]
thank you for your responses. i will explore both of these options when i get an opportunity.
