### ISSUE TITLE
No Intellisense in exit parentheses

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#1615]
Same issue as #253 

I'm still having this issue in the Feb developer preview (AL Language 0.13.15836), no intellisense inside the exit parentheses.
![image](https://user-images.githubusercontent.com/23434319/36338721-b1666c9c-1373-11e8-89b4-bb9713d16a14.png)

I commented on the other one but then noticed Stan asked to log a new one.

**Comment by StanislawStempin** [comment]
You're right, this scenario still doesn't work. Thanks for reporting.

**Comment by StanislawStempin** [comment]
As a side note February Update is AL Language 0.14.17461, you're using an older version.

**Comment by TheDenSter** [comment]
oh really, I just created a new developer preview VM last Friday, I thought those picked up the latest build. Thanks for the note, I'll try again
