### ISSUE TITLE
IncludeCaption property in report does not work

### ISSUE THREAD

**Issue by aidasberesinevicius** [Microsoft/AL#1616]
I created new rdlc report. I set the property IncludeCaption to true, to get caption of certain field.
![image](https://user-images.githubusercontent.com/31065713/36344673-a6e5f61c-1426-11e8-8910-85f17c6a507e.png)

Build the application and the rdl file appeared.
![image](https://user-images.githubusercontent.com/31065713/36344689-d6546154-1426-11e8-998a-8de2c917347f.png)

After I opened it with rdl file I found that field, but cannot find the caption part.
![image](https://user-images.githubusercontent.com/31065713/36344708-147bff5a-1427-11e8-91e0-cb42a57284eb.png)

It worked in older versions, where I had to make .rdl file through the "Custom Report Layout" page.

**Comment by DominikDitoIvosevic** [comment]
Thank you for the clear and precise repro. We will fix this
