### ISSUE TITLE
Compiling copies RDLC-files in the root folder

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#1617]
I put the reports and corresponding RDLC-files in a **Report**-Folder. When I compile the solution they will copied to the root-Folder of the solution. I would be nice if this didn't happen.

**Comment by anzwdev** [comment]
Are you sure that rdlc file is copied? If compiler cannot find rldc file, it creates a new, default one. All paths to files specified in reports and control add-ins definitions are not relative to the location of the al file but are relative to the root of the project. If you moved both your report al and rdlc files to the Report folder, you have to update RDLCLayout property and include that folder in the path.

**Comment by DanielGoehler** [comment]
Hi @anzwdev,

you are right. This newly generated RDLC-Files only contained the Field-Definition. I changed from `RDLCLayout = './<filename>.rdlc';` to `RDLCLayout = './Reports/<filename>.rdlc';` in every Report and everything works as expected.
