### ISSUE TITLE
Access to preview - question

### ISSUE THREAD

**Issue by markomolan** [Microsoft/AL#162]
I have run out of Azure test period long time ago. Is there any other way to get acces to development preview..i have it on my cmputer but its december 2016 preview.  Thanks.

**Comment by StanislawStempin** [comment]
Currently the only way to access Dev Preview is to use an Azure subscription. Your options are:
- use some other trial subscription from someone in your organization
- spin up a paid subscription
- (not officially supported/endorsed) search online for how set up nav developer preview locally

Keep in mind that you can stop the VM and accrue costs only when you are actually using the dev environment.

**Comment by markomolan** [comment]
Ok, thanks for answer. Although i find it not so amusing, that you ask us to help you test, find bugs etc. and on the other side you charge us for this....when actually we should charge you ...

**Comment by StanislawStempin** [comment]
We appreciate all the help that we are getting and realize that Azure image is not optimal in all cases. We are looking at providing the development environment in different formats but for the near future this will be the only available option.
