### ISSUE TITLE
Header and Fields in codeunit 5054 out of sync

### ISSUE THREAD

**Issue by peterz84** [Microsoft/AL#1620]
As mentioned in the code example in #1057, the header and fields in codeunit 5054 are out of sync now.
in function 
`[External] CreateHeader(VAR WordMergefile : DotNet "Micr.......
  AddNewEntry(Text015,''); <------ this is the FaxEmailValue and is the last header field.`

but in function
`[External] AddFieldsToMergeSource(VAR WordMergefile 
AddField(FaxMailToValue); <------ this value must come last and isn't now!`

**Comment by peterz84** [comment]
I'm not sure this is an enhancement, it will fail in merging now.

**Comment by JesperSchulz** [comment]
Sounds more like a bug. We will look into it! Thanks for reporting.

**Comment by peterz84** [comment]
Thanks, hope it makes it to Tenerife release.

**Comment by peterz84** [comment]
This simple change didn't make it to the BC release. Please mark it as bug.
When I add a field now using the events, Word gives me an error it could not find the Address (I guess FaxEmailValue is expected):

![image](https://user-images.githubusercontent.com/25202313/47361708-e51a9180-d6d2-11e8-8684-63d53907f756.png)

**Comment by StanislawStempin** [comment]
Issue has been moved to ALAppExtensions repo.
