### ISSUE TITLE
Rename all <control> Name fields on pages to the corresponding caption

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1623]
How can I add a field after these fields/groups/controls if I don't know what they are?

![image](https://user-images.githubusercontent.com/34303738/36367184-d8a56832-1551-11e8-8d77-877a8d18025a.png)

**Comment by StanislawStempin** [comment]
For now, you would need to look these controls up in C/SIDE. 
We are aware of the overall control/action naming issue and track it as part of #527

**Comment by SirBETE** [comment]
As long as we can access the C/SIDE, this is a possible workaround.
Thanks for the info.
