### ISSUE TITLE
SQL Report Builder missing in developer preview

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1627]
Hi Guys,

Just tested the new report snippet in the developer preview, and that works perfectly.
Thank you for that.

However, SQL Report Builder and Visual Studio are both missing in the developers preview.
Can vi get that in there?

Secondly, is there an easier way to open the SQL Server Report Builder than right-clicking the .rdl file and then selecting **Reveal in Explorer** to use the **open with** function there?

/Peik

**Comment by StanislawStempin** [comment]
Please open a request on https://github.com/Microsoft/nav-docker.

Regarding opening the .rdl/.docs file directly from VS Code we are looking into a solution.
