### ISSUE TITLE
Page Extension: Feature Request: layout -> modify -> Support ShowMandatory Property

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/AL#1628]
Hi Team

Add support for the property **ShowMandatory** in modify() please

![image](https://user-images.githubusercontent.com/36630655/36380895-37cc8ba6-1584-11e8-98b8-c11bf78003ae.png)

Thank you.

**Comment by StanislawStempin** [comment]
We generally don't expose properties that would lead to conflicting/undefined behavior in case 2 or more extensions modify the same property.
In this case you could have another extension modifying it to False.
We will investigate what could be done in this case, perhaps we only allow to set it to True. I will use this issue for tracking.

**Comment by bleisibach** [comment]
I fully understand your point. Allow to set it to True would be a valuable solution. IMO, the potential conflict/undefined behavior in case 2 or more extensions is applicable for the majority of properties.

**Comment by RobynGee** [comment]
I would also like to request the ability to set ShowMandatory to true as a Page Extension.  Is this still under consideration?

**Comment by Phfo** [comment]
Indeed, allowing to set it to 'True' would be a valuable solution !

**Comment by MarkusWinBI** [comment]
> We generally don't expose properties that would lead to conflicting/undefined behavior in case 2 or more extensions modify the same property.

Hi Stanislaw,

isn't this the same for editable or visible? These are conflicting too in my opinion. So how did you solve the problem for editable and visible? What about "concatenation" with AND? 

Extension 1 says Yes
Extension 2 says No
=> Client says Yes. :-)

Regards
Markus

**Comment by Wiechardt** [comment]
Hi Stanislaw,

I would really like to be able to set the ShowMandatory property of a base field in a Page Extension, we built an extensive feature allowing clients to configure mandatory fields and this feature relies heavily on the ability to visually identify the mandatory fields.

Many thanks,
Wiechardt

**Comment by MarkusWinBI** [comment]
Hi Wiechardt,

I found an evil workaround. :-) Just "remove" the Field from the page and "create" a new one. That's the way I do it. Then you can set every property you want! ;-)

Regards
Markus

**Comment by Wiechardt** [comment]
Thanks Markus, ithe evil workaround did the trick. :-)

**Comment by stephanweidmann** [comment]
If the old field is removed with visible = false AND Enabled = false, it should not show up.

**Comment by Wiechardt** [comment]
Hi Stephan,

I added the code below to the Page Extension for General Ledger Entries page but the Job No. is still available when using "Choose Columns" on the page:

        modify("Job No.")
        {
            Visible = false;
            Enabled = false;            
        }

**Comment by stephanweidmann** [comment]
Maybe this could be solved by filling ApplicationArea with a nonexistant value, but this may not be supported for all time. ( #3091 )

**Comment by StanislawStempin** [comment]
We will implement support for modifying the ShowMandatory property and see what other properties we can enable for modification. 
The workaround proposed above works fine if only one extension does it but imagine many extensions doing the same trick to the same field - you will end up with N copies of the same field, potentially each shown in a different way with a slightly different name.

**Comment by Wiechardt** [comment]
Much appreciated.

**Comment by JohanStenberg100** [comment]
Hi, thanks for reporting this issue. This is now fixed in our master branch and will ship in a future update!
