### ISSUE TITLE
Request - CU 8 -  OnBeforeTestBalance new Param or New Event

### ISSUE THREAD

**Issue by sweikelt** [Microsoft/AL#1629]
Hi,

it would be great if we can get a new Param (GLEntry) in this Event or to have another EVENT like maybe "OnBeforeFindGLEntry" or "OnBeforeCalcGLEntry," so we can customize the filtering on GLEntries - to extend the analysis.

**Comment by d-larisch** [comment]
+ it would be great, if this can be added!
