### ISSUE TITLE
AL & Server Settings Variables

### ISSUE THREAD

**Issue by OakleyLeon** [Microsoft/AL#1630]
Hi,
Is there a way in AL (using VS Code) to return back the current version / build number of the connected server instance for nav 2018 (on premis) & D365.
Thanks.

**Comment by StanislawStempin** [comment]
You can look into functions available on Codeunit 1 - ApplicationVersion, ReleasedVersion etc. 
There is no way to get the compiler version right now.

**Comment by StanislawStempin** [comment]
I'm not sure I understand the question. It is a normal AL function like any other function that you would call from AL, i.e.
```
var
   ApplicationManagement : codeunit ApplicationManagement;
   version : Text;
begin
   version := ApplicationManagement.ApplicationVersion();
end;
```

**Comment by OakleyLeon** [comment]
thats exactly what i was looking for. 
thankyou.
