### ISSUE TITLE
Collapse ListParts

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1631]
Hi everybody,

in RTC Client it was usual to collapse any ListParts. In Webclient and in D365 I am not able to collapse any ListPart. To do so will make a better overview on a master page with one or more ListParts in it. 

Will Microsoft support this or what's the reason why we cannot collapse any ListPart on a Card Page?
I can create a group arrount my ListPage to collapse, but then I have two headline captions and this don't look good either.

**Comment by StanislawStempin** [comment]
Hi, Since this is not a topic directly related to AL development could you please contact the regular NAV support channels.

**Comment by jiwanovski87** [comment]
@StanislawStempin can you tell me what you mean with regular NAV support channel? 
This is a development topic (not direct AL, right).

**Comment by StanislawStempin** [comment]
From the FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-not-related-to-al-development-what-do-i-do
Similarly to the above question, an issue not related to AL development is beyond the scope of this GitHub repository. In these cases please open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
