### ISSUE TITLE
RAM Usage of Compiler and Service Tier

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#1632]
Is it normal that an ISV Solution as Extension with 242 Codeunits, 392 Page Extensions, 554 Pages, 72 Queries, 61 Reports, 203 Table Extensions, 329 Tables and 20 XMLports uses that much on RAM while publishing? 

Pre-Compiler in VScode: ~2.5 GB
Service Tier: ~3.7 GB

The NAV Service Tier for the same solution (as C/AL) consumes (with disabled Data Cache) ~950 MB RAM on a Production Environment with ~25 Users running since yesterday 20:23:08.

![ram usage](https://user-images.githubusercontent.com/9556549/36394420-893117ac-15b4-11e8-9c17-06ac0c2321d0.png)

**Comment by StanislawStempin** [comment]
It sounds about right that the compiler in VS Code takes 2.5GB for a project of this size.  However, the service tier should only temporarily reach this size and after the initial publishing the memory should be released. 
Do you have any other memory consuming tasks runnin on the service tier?

**Comment by StanislawStempin** [comment]
The requirements shouldn't be any different from running the same code in C/AL. If the memory consumption doesn't go down after publishing then we have a bug.

**Comment by StanislawStempin** [comment]
Hi Daniel, have you had a chance to look at the memory consumption in case of a successful publish?

**Comment by DanielGoehler** [comment]
Hi @StanislawStempin,
is there anything I can do to solve #1633? I currently cannot publish successfully.

**Comment by DanielGoehler** [comment]
Hi @StanislawStempin,

after restarting the Service Tier and waiting for compiling and loading the business objects the Service Tier uses ~1 GB on Current Build of BC. Publishing/Installing is petty smooth via PowerShell (Service Tier RAM usages went up from ~1 GB to ~2 GB). But increased RAM will not released at least no within 20 minutes after installing.

Using VScode since last time with the same solution showed the same improvement: Service Tier RAM usage ~2 GB

But the Pre-Compiler in VScode uses still ~2.5 GB although he is finished with packaging and deploys a 4 MB App on the Service Tier.

Also if you Package again right away the Microsoft.Dynamics.Nav.EditorServices.Host.exe or one of svchost.exe-Processes uses a lot of RAM.

**Comment by atoader** [comment]
@DanielGoehler please try the latest developer preview https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ . You should see a significant in the performance of the AL compiler.

**Comment by DanielGoehler** [comment]
Hi @atoader, I wrote this issue not because of performance, but because the Pre-Compiler and the Service Tier uses a lot RAM and the RAM will not be released. Please check https://github.com/microsoft/AL/issues/1632#issuecomment-366942433 where StanislawStempin said that this not supposed to be.

You could test this now with your very own Base App with 6014 Objects. When I open the Source Code of the Base App from 2019 wave 2 Preview 01 in Visual Studio Code with the corresponding AL Language Extension (4.0.170493), the Pre-Compiler (Microsoft.Dynamics.Nav.EditorServices.Host.exe) uses 2.3 GB of RAM for Packaging. With Code Analysis even more (~3 GB). This RAM will still not be released.

Currently the Base App Source Code doesn't compile, so I can't say anything about the Service Tier behavior. Due to the Breaking Changes in 2019 wave 2, my Solution is also not 2019 wave 2 ready, yet.

**Comment by DanielGoehler** [comment]
Hi @atoader, thanks to your help publishing the Base App works now. It takes a while, but for this size is understandable.
RAM Usage of Visual Studio Code (Microsoft.Dynamics.Nav.EditorServices.Host.exe) drop when Publishing started and Service Tier used ~ 4 GB RAM while publishing and also dropped when finished. Quite better now.
