### ISSUE TITLE
Select server only showed for few seconds on launch

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1634]
I'm working with a launch.json that has more than one configuration (e.g. one for local dev and one for central test server).

When I use F5 first time, after opening VS Code, the dropdown appears to select the server configuration. However, that dropdown disappears disappears in a second, before I can choose the server. Then only the package is created but not published.

The only solution is to temporarily remove servers configurations from the launch.json. Then the publish process works. After the first publish, the status bar shows the configuration in use. Then it is possible to add the other server configurations and select the server by clicking on the server in the status bar. The dropdown appears but now waiting for selection.

**Comment by ajkauffmann** [comment]
Another observation: the app file is not created when you click on 'Select and start debug configuration' in the status bar.

So... with multiple configurations in the launch.json, the behavior is:

- F5 builds the app file, shows the select server dropdown for just a few seconds, no debug session is started. The debug console shows status lines of previous successful debug session.
- The 'Select and start debug' from the status bar does not build the app, let you select the server, publishes the (yet outdated) app and starts a debugging session on the selected server.

**Comment by StanislawStempin** [comment]
Thanks for reporting, we will look into it.

**Comment by kine** [comment]
Have same behavior. It is hard to switch between the configurations (e.g. I have one with recreate and one with synchronize). When using command "AL: Publish" the list is displayed shortly and after that the last config is used.

**Comment by StanislawStempin** [comment]
I can no longer reproduce the dissapearing dropdown on VS Code 1.22.1 and AL Language 0.15. 
Can you confirm it works for you as well?
