### ISSUE TITLE
Field name "G/L Account" treated as comment

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1636]
When using a field like "G/L Account" it is treated to be comment after the /
Not only on the line itself, but also on all subsequent lines.

With / in the name:
![image](https://user-images.githubusercontent.com/19155831/36414552-f89b54c2-1622-11e8-938f-8e79349d526d.png)

Without / in the name:
![image](https://user-images.githubusercontent.com/19155831/36414575-12c5e632-1623-11e8-96b5-3eb40367a3cb.png)

As a side note: I know it's a legacy to allow characters like space, dots and slashes in names. I wouldn't mind to use only letters and numbers. Too much for now, I know, just saying...

**Comment by atoader** [comment]
It seems to work in the latest build. Do you have problems with the following snippet?

```
table 40002 MyTable
{
    fields
    {
        field(1000000; "G/L Account No."; Integer) { }
    }
}

xmlport 40001 MyXmlport
{
    schema
    {
        textelement(NodeName1)
        {
            tableelement(MyTable; MyTable)
            {
                fieldelement(NodeName3; MyTable."G/L Account No."){}
            }
        }
    }
}
```

**Comment by atoader** [comment]
Hi, @ajkauffmann ! Could you please provide input? This works on the latest build. It might be that some other extension you have installed is interfering.

**Comment by ajkauffmann** [comment]
What build number do you test with? I have 0.14.17461 as latest build (February preview).
Still having this issue. Can't find any extension which causes this.

![image](https://user-images.githubusercontent.com/19155831/36828826-6492c8b8-1d1c-11e8-8260-c6bd8f2d5634.png)

**Comment by kalberes** [comment]
I can't repro this either. But I do not see any compiler errors on your screenshot just colorizer issues.
Have you changed the TextMate file defining the colorization rules? (alsyntax.tmlanguage)

**Comment by ajkauffmann** [comment]
Did some more investigation. It appears I downloaded a them extension that did some syntax injection for al code. Apparently not in the correct way, because it did even change the coloring while the them was not active. Completely disabling the extension solved the issue.
Sorry for bothering you with this, thanks for looking at it.
