### ISSUE TITLE
Reference to object Unit of Measure Management is ambiguous.

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1637]
When I declare a variable of type codeunit with the objectname written out as "Unit of Measure Management", a problem occurs:
`[AL] Reference to object Unit of Measure Management is ambiguous. Make sure you are not referencing packages containing objects with the same names.`
```
    var        
        UOMMgtError : Codeunit "Unit of Measure Management";
        UOMMgtOK : Codeunit 5402;
```

However when I create a new variable referenced to the codeunit by its number, it's accepted.

My extension does not contain an object with the same name.

So are there 2 codeunits "Unit of Measure Management" in NAV?

In the DEV Env only 1 object with that name exists:
Type	ID	Name	Modified	Version List	Date	Time	Compiled	Locked	Locked By
5	5402	Unit of Measure Management	No	NAVW111.00	22/11/17	12:00:00	Yes	No	

Using
```
  ,"platform": "11.0.12925.0"
  ,"application": "11.0.20348.0"
And
Al Language compiler 0.12.16641
```

Checked #745 , no controladdin since the object is a table, not a page.

**Comment by StanislawStempin** [comment]
I cannot reproduce on the latest build. Could you please try using the February Update?

**Comment by SirBETE** [comment]
Since the February update doesn't exist in NAV2018, I can't ... 😞

**Comment by StanislawStempin** [comment]
Ok, please file a support case for NAV 2018. It looks like we fixed the issue in the meanwhile and need to backport to NAV 2018.

**Comment by SirBETE** [comment]
FYI:
Your request has been sent.
Your support request has been sent. The incident number is: 118022217688480 
The expected time in which you can expect initial response is no later than feb 22, 2018 at 14:12 GMT 0100.

**Comment by SirBETE** [comment]
I have retested it and everything works now (no problems, package is created and published successfully to the server).
UOMMgt : Codeunit "Unit of Measure Management";
Is accepted as the variable definition.

Must have been something before the line that gave the error.
Or it must have been solved by closing and opening VS Code again.

Strange…
Anyway: case closed.
Thank you!
