### ISSUE TITLE
Webclient gives error 'Sorry it didn't work' on Master Card Pages.

### ISSUE THREAD

**Issue by olisterrcf** [Microsoft/AL#1638]
Hi,
I get the above mentioned error on the WebClient in NAV 2018 when handling the Master Pages such as Customer Card Page or Item Card Page. The page is properly visible in WinClient. After running the WinClient the WebClient runs the pages properly. I'm not sure why this happens. Thanks

**Comment by StanislawStempin** [comment]
Hi, Since this topic is not directly related to AL Development please contact the regular support channel with your issue.
