### ISSUE TITLE
IntelliSense does not properly recognize with block context

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#164]
When a complex variable type, such as Record, is used with a with-do block, IntelliSense does not show functions/methods of such variable.

For example:

    procedure WithIntelliSense();
    var
        Cust: Record Customer;
    begin
        with Cust do begin
            // IntelliSense does not show functions for Cust variable here
        end;
    end;

So, if you try to type e.g. SetRange inside the with block, IntelliSense will not show it. It will show fields of the Customer record and also any global functions defined on Customer record, but not built-in AL functions (e.g. SetFilter, SetRange, ...)

I am using April build.

**Comment by StanislawStempin** [comment]
Thanks for reporting, that's a bug.
