### ISSUE TITLE
CurrPage.Close doesn't work

### ISSUE THREAD

**Issue by olisterrcf** [Microsoft/AL#1640]
Hi,
I've a page that is run through the code. And code is written OnQueryClose trigger. The code is executed but the Current Page doesn't get closed

**Comment by StanislawStempin** [comment]
Could you please provide a code sample for us to understand the problem better?

**Comment by thpeder** [comment]
@olisterrcf In the February update this should be fixed.

**Comment by olisterrcf** [comment]
I've a page i.e "page1" which calls another page's ie. "page2" global method a.k.a page2.function1() and then runs the page using page2.RUN.
OnQueryClosePage trigger of page2, I've called the global method of Page1 using a.k.a page1.function2().

The method page1.function2() is executed properly but, page 2 doesn't close.

**Comment by olisterrcf** [comment]
Hi,
I've also check calling the page without adding code in OnQueryClosePage trigger, the page closes.
If I add the trigger and put a message box the page doesn't close.

**Comment by StanislawStempin** [comment]
February Update refers to the latest Developer Preview release for Dynamics 365 "Tenerife". Please see this FAQ entry for more details on NAV 2018 issues: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues

**Comment by DominikDitoIvosevic** [comment]
Please use standard channels for support of Nav 2018 as said https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
