### ISSUE TITLE
License issue with tableextension and pageextension

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#1643]
We have licensing issue with a customer with NAV 2018.
During the Publish-NAVApp the following error appears:

    Your program license does not allow you to publish ' ... '

The customer has bought custom objects and we have assigned the number range through Partner Source. 

But the above error is relative to tableextension and pageextension! There should not be a license check with these type of objects. In fact, if we publish with partner license, all it's OK and next the customer can use the tableextension and pageextension with no problems. But it's a big issue to change every time the application server license because it needs a service restart.

Please fix asap.
Thank you

**Comment by StanislawStempin** [comment]
We are aware of this limitations and looking into how to improve the experience. For now, as an alternative to the workaround that you described, you can use so-called runtime packages. For more information see:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-creating-runtime-packages

**Comment by sgiordy** [comment]
Thank you @StanislawStempin for now the work around resolves the cases of upgrading app in live environments.
