### ISSUE TITLE
Windows cannot find (url) make sure you typed error when pressing F5

### ISSUE THREAD

**Issue by hougaard** [Microsoft/AL#1646]
After pressing F5 and the extension was successfully deployed VS Code gives this error;

![image](https://user-images.githubusercontent.com/3357237/36450253-245a3b72-1642-11e8-89cd-88c105229ece.png)

Th URL works file when entered manually in a browser or in the start menu (So HTTP is registered correctly with a browser.

**Comment by StanislawStempin** [comment]
Which version of the server, of AL Language and of VS Code are you using?

**Comment by hougaard** [comment]
I believe it was on NAV2018 CU2.

**Comment by StanislawStempin** [comment]
Ok, then I would ask you to go through PartnerSource if this is still a problem on CU4. We have not been able to repro locally on any recent builds.
