### ISSUE TITLE
Expose functions TestStatusOpen and CheckItemAvailable in TAB37 Sales Line

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1649]
Please? :)
And `UpdateUnitPrice `too please (thank you for the OnAfterUpdateUnitPrice event :D)

**Comment by JesperSchulz** [comment]
You got it :)

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
