### ISSUE TITLE
app.json withhout startupObjectId 

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#165]
When there is no startupObjectId in the app.json, it does not run the web client upon successful building and publishing of the extension. I am forced to put startupObjectId and set a value, even though I might want to run a default role center.

I am using April release.

(Maybe this is by design, in this case, please reconsider the possibility of omitting the startupObjectId to allow running directly into the role center).

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. This was originally by design but we have received enough feedback to reconsider. We will update this thread with the outcome
