### ISSUE TITLE
FILTERGROUP behavior?

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1653]
I am still trying to narrow down the behavior more, but it seems that FILTERGROUP has not function anymore really?

What I am doing in "OnOpenPage" is, based on some conditions, set additional filters that I don't want the user to be able to adjust. So, I used to use FILTERGROUP(2) or FILTERGROUP(4) to switch to one of the "protected" filtergroups and set the filter and then switch back to 0 and the user cannot remove the filter.

Doing this now leads to nothing other than the user being able to remove the filter just like any other filter that was set. So, is that intended behavior or is this a bug or am I "buggy" ;) ? If this is now the intended behavior, what am I supposed to do to get the desired functionality?

**Comment by StanislawStempin** [comment]
Hi, we will investigate it but in the meanwhile could I ask for a few more details:
Is this a regression in behavior either between AL vs C/AL,  NAV 2018 vs older versions  or web client vs win client?

**Comment by DominikDitoIvosevic** [comment]
@pzentner Could you please help me out with a code snippet showcasing this scenario?

**Comment by pzentner** [comment]
@DominikDitoIvosevic I tried to create a snippet right now and validated in current build that it is now working as expected. So, something must have changed for the better. This now can be closed, I would think.

**Comment by DominikDitoIvosevic** [comment]
Great news :)
I'll close the issue then and we can reopen in case it resurfaces. @pzentner could you please share with us the snippet you used for reference?
