### ISSUE TITLE
Error Publishing extension with translation files

### ISSUE THREAD

**Issue by iWorksJared** [Microsoft/AL#1656]
I am getting a error when using Publish-NAVApp on an extension that has multiple .xlf files in it.

I followed the instructions here:
https://docs.microsoft.com/de-de/dynamics-nav/developer/devenv-work-with-translation-files

I am attempting to make a Spanish translation (es-MX). These are the steps I am taking:
1.Create a copy of the autogenerated .xlf file 
2.change the name to <extension>.es-MX.xlf 
3.change the target-language to "es-MX"
4.add all the <target></target> tags

VS Code builds the project, but when I try publish it, i get this error: 

`Publish-NAVApp : Value cannot be null.
Parameter name: value`

when i delete the translations and remove "feature": ["TranslationFile"] from app.json it publishes successfully.

I am not sure if I am missing something or if this is a bug i don't know about.

Any help at all would be great.

I am using VSCode version 1.20.1.

**Comment by StanislawStempin** [comment]
Can I ask which version of the NAV server and AL Language extension are you using?  There has been a recent change in that "feature" element in app.json uses an array instead of a single string.

**Comment by iWorksJared** [comment]
Nav Version: 11.0.20348
AL Version: 0.14.17291

**Comment by iWorksJared** [comment]
method in app.json i was using was 
`"features": ["TranslationFile"]`

**Comment by DominikDitoIvosevic** [comment]
Hi @iWorksJared .
Could you please try and build the extension within vscode and tell us what you get? My guess would be that if there is an error a compiler should complain about something.

**Comment by iWorksJared** [comment]
`[2018-02-23 08:32:14.95] Sending request to http://dms1-dfbsst01.dynms.local:7149/TENERIFE_STAGING/dev/apps?SchemaUpdateMode=synchronize
[2018-02-23 08:32:17.19] Error: Could not connect to the server. Please verify that:
1. The server is started.
2. The development endpoint is enabled (DeveloperServicesEnabled server setting).
3. The service name matches the one specified in the URL.
4. The port number matches the one specified in the URL (DeveloperServicesPort server setting).
5. The protocol matches the one specified in the URL (DeveloperServicesSSLEnabled server setting), and that a trusted certificate is used in case of an SSL connection.
[2018-02-23 08:32:17.19] Error: An internal error has occurred
`

That's my output when I hit F5. i am not running on an azure VM and I am not using a web client.

I removed everything from the second .xliff until it was exactly the same as the original. I basically have to copies with different names.

**Comment by DominikDitoIvosevic** [comment]
Hi @iWorksJared . I have fixed some issues regarding compiling translation files, but it could be that you have some other issue. Please provide us a repro (best way is a zipped small extension) which demonstrates your issue so that I can test locally

**Comment by iWorksJared** [comment]
Here you go, thanks for investigating
[HelloWorld.zip](https://github.com/Microsoft/AL/files/1763612/HelloWorld.zip)

**Comment by DominikDitoIvosevic** [comment]
Hi @iWorksJared . I tried reproducing you issue on the latest version and I can't get it. The only problem you have is that you xliff file is out of date.

Your surce should be `english` as you specified it in AL.


        <trans-unit id="Page 1928153799 - Control 4105281732 - Property 2879900210" maxwidth="999" size-unit="char" translate="yes" xml:space="preserve">
          <source>Language</source>

As for the publishing issue, it seems unrelated. Maybe getting a new VM would be the fastest fix

**Comment by DominikDitoIvosevic** [comment]
@iWorksJared if you are still experiencing issues please ping us back. I will close this issue for now
