### ISSUE TITLE
Global variables not available in system events

### ISSUE THREAD

**Issue by damse60** [microsoft/AL#1661]
Trying to use the same model for the field "WorkDescription" on Page 42 (Sales Order) on another solution, I ran into the problem that Global Variables on a page (and other places) are not available in systemevents (Page event OnAfterGetRecord).
In this case it means that you cannot load the content of a Blob field into a multiline textfield (like the line WorkDescription := GetWorkDescription; on OnAfterGetRecord trigger in Page 42  - WorkDescription being a global variable on the page.
This may not be a completely specific AL problem but in my eyes has significant impact on usability.

**Comment by StanislawStempin** [comment]
Currently these scenarios need to be handled by exposing a property function that accesses the variable indirectly.

**Comment by damse60** [comment]
Thanks Stanislaw - this would work, but is perhaps not the most elegant and 100% extension based solution. Hope it will be resolved sometime soon :)

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
