### ISSUE TITLE
Records in Lists and Dictionaries (Generics)

### ISSUE THREAD

**Issue by joandrsn** [microsoft/AL#1663]
Currently it's allowed to do code like this:
```
var
   list: List of [Text]
```

I would like to be able to so code like this:
```
var
  list: List of [Record Customer]
```

The generics can currently only contain simple datatypes(`Code`, `Text` and so on) but I would like to have it be able to hold Record objects.
It could be used instead of creating temporary records and filling those temporary records up.
```
TempCustomer := Customer;
TempCustomer.INSERT;
```
instead it would be more readable to have it:
```
TempCustomerlist.Add(Customer);
```

The advantage is that it would be more readable and sometimes forgettings to pass as a `var` sometimes leads to temporary records being created. A list of customers should only be in memory. 

It could be useful for buffers where you have to generate some data and put it somewhere.

The `Contains` method on a list might have an issue (Does the primary key exist or is the entirerecord the same, or is it the memory address) 

This should also apply to dictionaries aswell.

**Comment by StanislawStempin** [comment]
This is a known limitation due to how complex types like Record are handled in our runtime. Long term we would like to provide support for them in the Lists and Dcitionaries. I will keep this item for tracking that work.
