### ISSUE TITLE
CurrPage.Editable change on open

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1664]
We have the ability to check, if a page is editable and you can also assign a value to this property:

```
if CurrPage.Editable then
  CurrPage.Editable(false);

```

However, if you actually try this anywhere - in OnInit, OnOpenPage, or even any of the other triggers or in an action, nothing happens. So, it seems that this - while available - is not working. And this is an issue for us - we are trying to allow certain users to change data based on a status and others not to (or all users not to change data after a certain status is achieved). So it is necessary to be able to change "Editable" of a page on runtime.

We technically can set all fields to Editable = false at runtime, but that doesn't prevent the ability of a user to click on "New" or "Delete". 

Ideally, CurrPage.Editable would be available at runtime or new properties should be introduced:

```
CurrPage.InsertAllowed
CurrPage.ModifyAllowed
CurrPage.DeleteAllowed

```
to be changed at runtime.

We would need some solution for this as this is currently an issue for one of our V1 to V2 conversions.

**Comment by esbenk** [comment]
Was this working in V1 or did you do something different? It seems like the code we generate is exactly the same.

**Comment by pzentner** [comment]
Hmm... that's a good point. LOL. It is/was working in the Windows client with V1, but apparently not with the web client. The reason this now came up is that one of Ryan's testers made a "mistake" - anything that any normal end user would/could do (Thanks for finding it btw). 

This, I guess then goes into a bigger discussion on what can be supported how. The issue is that we only have the web client (for D365) and we need to be able to make the customer's experience even more "fool proof" to reduce the amount of mistakes a user can make and the amount of support one gets. 

If I am thinking of other ISVs, I can think of a couple that would have a huge issue not being able to control the "editability" of a page on run time, since at least one of them needs to make it "easy [to change] security" (get my hint?). 

I guess, it's somewhat a limitation of the web client, but I would actually call it a bug in the web client, because if I can do it in the Windows client, I can develop the code, and the documentation does not explicitly state that it doesn't work in the web client, it should work. 

Here is the documentation: https://docs.microsoft.com/en-us/dynamics-nav/editable-property 

While it says that it is not recommended using this to prevent users from deleting data, it doesn't say that it doesn't work and since we don't have the ability to change permissions on an object "on the fly", this is also not an option.

However, I am not set on enabling this property to work, there are a lot of different ways of implementing a scenario like this and we would just need one.

**Comment by esbenk** [comment]
I can't even make it work in the WinClient. Adding

`CurrPage.EDITABLE(FALSE);
`

as the last statement in OnInit() on the Customer Card (all C/SIDE) and run the WinClient still gives me an editable page.

**Comment by pzentner** [comment]
If you do that in OnOpenPage, it works. OnInit is too early it seems.

**Comment by esbenk** [comment]
I have just tried on NAV2018 Win & Web. If you do it in the OnOpenPage trigger it works.

I have both tried it from C/SIDE and also by deploying the following pageextension

```
pageextension 50100 CustomerListExt extends "Customer Card"
{
    trigger OnOpenPage();
    begin
        CurrPage.EDITABLE(FALSE);
    end;
}
```

**Comment by pzentner** [comment]
That took me a bit, since I was having a different experience, but when trying what you did, it was the same working scenario. However, I found the exact steps to replicate:

First of:
- PageExtension for page type Card works
- Custom Page for page type Card works
- PageExtension for page type list does not work
- Custom Page for page type list does not work

Try this please:

```
pageextension 50100 "testme" extends "Countries/Regions"
{
  trigger OnOpenPage();
  begin
    CurrPage.Editable(false);
  end;
}
```

Before the extension is in place, you can add, delete, modify records and select the "Edit list". Now, when you add the extension, you would think that it won't work anymore, but there is no change in behavior - you can still edit, insert, modify...

**Comment by esbenk** [comment]
Just  to make sure - this is not about Win vs. Web client or C/AL vs. AL. 

It is only Card vs. List - the List page doesn't respect the editable setting. This have never worked for List pages, right?

**Comment by pzentner** [comment]
It does seem that card works correctly and list does not. NAV 2017 windows client works with list as well, NAV 2017 web client does not. I have not tried it with NAV 2018 and also not with AL and Windows client.

The reason I am even bringing up NAV is that the current extension also exists as a NAV product and it has been working there (since NAV customers mainly utilize the windows client) and now seeing the behavior differently during the conversion - we must have missed this during the initial V1 validation.

So - it is card vs list and list windows client vs list web client.

**Comment by esbenk** [comment]
If I add 
`
CurrPage.Editable(false); `

to the OnOpenPage() trigger using C/SIDE in NAV 2018 and run the page, it start in view mode, but I click the "Edit List" button it goes into edit mode.

Is that working differently on 2017?

I see that exact same behavior for the NAV 2018 WebClient.

**Comment by pzentner** [comment]
Yes. Windows client NAV 2017 does not allow the "click on Edit List". It starts in view mode, but there is no way to switch to edit mode.

**Comment by esbenk** [comment]
Tried a few other things, Page 10 with Editable(false) in OnPageOpen at get different result depending on how the page is opened.

Win client:

* If launched from C/SIDE it still allows me to go to edit list.
* If launched from code with Page.Run(10), Edit List is disabled.
* If launched from search it is not possible to go to edit.
* From Embed Page, blue dropdown upper left corner Page|Open In New Windows -> Edit is enabled

WebClient:
* If launched by adding ?page=10 in the Url, same launch using VsCode deploy -> Edit is enabled
* If launched from code with Page.Run(10), Edit List is disabled.
* If launched from search it is possible to go to edit.

I assume this is why their is a red caution box in the documentation.

**Comment by pzentner** [comment]
Testing in 2017:
If launching a list page via Object Run (action on another page), Edit List is disabled with Editable(false) in OnPageOpen in Windows client. Similar to Page.Run.

If doing the same in the web client, edit list is enabled.

It seems that mainly, the behavior is the same, except for starting from search and object run.

I guess, this is then less of an AL issue itself, but the implementation of this functionality in the web client.

**Comment by pzentner** [comment]
I am using now an ugly work around to basically replace any of the calls to the pages with code. So, for now, we can move forward, but I highly suggest that this is fixed in the future so that we actually can use this functionality "more consistently".

**Comment by pzentner** [comment]
Stan,

Thank you for the follow up. It does make sense to warn not using the editable property to prevent deletion, since I can still delete records when the page is not editable (in my eyes a bug, but that's a different story). 

Based on this scenario - how do I dynamically change the permissions of a user to prevent deletion? I know I can always use an error message in the delete trigger, but from a user experience point, it would be better to disable that function instead allowing it and throwing an error.

Now, in the original use case, I did not want to prevent deletion, but modification of data and that's what the editable property is for on the field level, so it would be inconsistent to say that you shouldn't use editable on the page to prevent modification. If the property is available, it should work or the property should be removed or made read only. But then again - how do we provide the proper user experience to prevent modification of records in certain scenarios? We cant make each field non editable since users can add their own fields. We cant dynamically change permissions, so again, the only way would be the error message in the modify trigger and that's not only bad user experience, but also it is not good coding practice to use triggers to raise errors IMO

Thanks Peter

**Comment by JohanStenberg100** [comment]
Hi @pzentner, this repository does no longer accept questions so I will close this issue. We do appreciate the constraints you are highlighting and I would recommend you to instead contact regular support:

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)

As I understand this, you can work around this issue. If you are not satisfied with this course of action, you can create a new issue and formulate it as a _suggestion_ or _enhancement._ We will then consider implementing it.

**Comment by fvet** [comment]
@pzentner Struggling with the same restrictions over here as well Did you find a work around for this? 

In the meanwhile, feel free to upvote the idea.
https://experience.dynamics.com/ideas/idea/?ideaid=4bd39e15-7566-e911-b047-0003ff68d109

**Comment by pzentner** [comment]
Basically, you have to use the enabled property instead of the editable property. Has some other negatives, but that's the best way I found. Haven't needed it in a while, so I was hoping that this was actually fixed already, but doesnt seem that way

**Comment by gwhuebner** [comment]
There is a smart workaround for this problem (at least in NAV 2018 Windows Client):
Define a boolean variable isEditable and set it dynamically in the OnAfterGetRecord Trigger of the card page.
Furthermore, assign this variable to the Editable property of all Groups within the Content Area of the page.
Now, the page will be editable or not editable, while stepping through the records according to the variable set.

**Comment by pzentner** [comment]
This works in all versions (currently), however, it is not really great - just like using the enabled property is not great. The issue is that you have to arrange fields in groups and then you can make the group editable or not. It should not have to be necessary to define various arbitrary groups to get this to work - especially, if you don't know how the future UI might display groups. But yes, it is certainly a cumbersome work around.
