### ISSUE TITLE
Job Queue throws an error

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1666]
I've created a job with Object type as codeunit and published it as extension in NAV 2018 CU 2
but while setting up the job in the RTC, error is thrown that field ID to run the Job Queue Entry cannot be found.

![job](https://user-images.githubusercontent.com/24870777/36586113-78370f48-18a6-11e8-98d7-a097e14e8c4c.JPG)

**Comment by Chris-Dsilva** [comment]
If I have customized a job queue i.e a codeunit from range 50000 and above, how will I schedule in the Job queue entries ?

**Comment by Chris-Dsilva** [comment]
@StanislawStempin any progress?

**Comment by StanislawStempin** [comment]
Could you please share the steps you used to trigger this error?

**Comment by DominikDitoIvosevic** [comment]
@Chris-Dsilva could you please share us the repro steps for this issue?

**Comment by DominikDitoIvosevic** [comment]
@Chris-Dsilva could you please share us the repro steps for this issue?

**Comment by DominikDitoIvosevic** [comment]
@Chris-Dsilva please use the standard channels to open an issue for Nav 2018 as described https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
