### ISSUE TITLE
Renaming of tables

### ISSUE THREAD

**Issue by AlexanderCegla** [Microsoft/AL#1669]
I created a table and some objects with a relation on this table. When I build the package and run it, it works. However, when I change the tables name afterwards and run with debugging, I get the error message:

`Table 50001 :: Unsupported table change. Table:Sales CommmentLine - 8D; Change:Name`

Is there any solution for this issue?

**Comment by StanislawStempin** [comment]
This error is due to the fact that the change you made is a schema breaking change and running with the default schemaUpdateMode = Synchronize. You need to publish with "schemaUpdateMode" : "recreate" in app.json.

**Comment by AlexanderCegla** [comment]
Thanks, that's it.
