### ISSUE TITLE
txt2al - File naming suggestion (type subfolder, strip spaces and object id)

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#167]
When exporting a page object (51002 - My Page Card) and using the txt2al converter, an .al file with name 'Page 51002 - My Page Card' is created. When building my project, errors are shown in the output console, with the possibility to 'Ctrl+Click to follow link'. However, since the file name contains spaces, the hyperlink does not seem to work

**s:\Documents\user\New Dev Environment\Samples\Project\Page** 51002 - My Page Card.al(342,39): error AL0196: .......

Would it be possible to delete spaces when building the file names?

Looking at the 'GetAddressService' sample, it might be even a better idea to use the 'Object Type' as subfolder (Codeunits, Pages, Tables, ...), save the object in the related subfolder, strip spaces from object name and no longer include the object ID...

So _s:\Documents\user\New Dev Environment\Samples\Project\Page 51002 - My Page Card.al_ could have been saved as _s:\Documents\user\New Dev Environment\Samples\Project\Pages\MyPageCard.al_

**Comment by StanislawStempin** [comment]
Spaces in the path not being correctly supported is a VS Code issue (Dennis linked it just above). We will consider the subfolders suggestion. Including Ids in the name was a previous user suggestion to be able to easily map between new and old files, we could consider making Id a command line option.

**Comment by lvanvugt** [comment]
> We will consider the subfolders suggestion.
Please, if you do make it an option as I would like to have to choice to have the files organized like that.
**Justification**
Using source code management for years already we keep all app objects in one folder and test and upgrade objects in other folders. No level deeper.
Now moving to AL we're no sure yet whether we continue that way or not. But I would like to have the freedom to chose still.

**Comment by DominikDitoIvosevic** [comment]
Hey everyone. The PR has been merged in the VS Code repo so you can see the fix working in the Insiders build of VS Code and then hopefully next month it will be in the stable release.

**Comment by DominikDitoIvosevic** [comment]
This fix is available on the latest stable version of Visual Studio Code
