### ISSUE TITLE
Workflow Subscriber does not allow to publish

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1673]
I've created a codeunit which subscribes to the Workflow Integration Events e.g OnApproveApprovalRequest,OnAddWorkflowEventsToLibrary,OnAddWorkflowTableRelationsToLibrary,OnRejectApprovalRequest, OnDelegateApprovalRequest.

This codeunit does not allow to publish the Extension. Its throws error A task was cancelled.

**Comment by StanislawStempin** [comment]
Could you please provide more details? A code sample + the exact error message and the actions that you took would be helpful
