### ISSUE TITLE
Getting an error in app.json after upgrading to build 20539

### ISSUE THREAD

**Issue by AMCJN** [Microsoft/AL#1676]
After I updated our docker to build 20539 and reinstalled VSIX from file,
I get an error in app.json when I try to build our app.

Error message is this :

_A package with publisher 'Microsoft', name 'Application', and a version compatible with '11.0.0.0' could not be found in the package cache folder 
'c:\Users\Jan\Documents\AL\AMCFinanacials365_1.0.20539.0\./.alpackages'_ 

My app.json look like this :

_{
	"id": "f749384f-6f77-4a86-a0fc-d3b78da6c462",
	"name": "AMC Banking 365 Financials",
	"publisher": "AMC Banking",
	"brief": "AMC Banking 365 Financials",
	"description": "This service automates the bank account reconciliation and payment processing as  you will be able to get bank statements directly into Microsoft Dynamics 365 Financials",
	"version": "1.0.20539.0",
	"privacyStatement": "https://amcbanking.com/privacy/",
	"EULA": "https://amcbanking.com/agreements/",
	"help": "https://amcbanking.com/landingdyn365fin/",
	"url": "https://amcbanking.com",
	"logo": "C:/Temp/AMC APP 365/amclogo.png",
	"capabilities": [],
	"dependencies": [],
	"screenshots": [],
	"platform": "11.0.0.0",
	"application":  "11.0.0.0",
	"idRange": {
		"from": 70093919,
		"to": 700939922
	},
	"showMyCode": false
}_

The contens of folder .alpackages is :
Microsoft_Application_11.0.20539.0.app
Microsoft_System_11.0.12927.0.app

Any idea why this happens ? IS my application version wrong ?

**Comment by StanislawStempin** [comment]
Your configuration looks correct. I would suggest deleting local .app packages, restarting the server and VS Code and trying from scratch. 
Was the Application.app generated using C/SIDE or is that the one shipped in the database?

**Comment by AMCJN** [comment]
I deleted our .app packages and created it again with Shift+Ctrl+B
and it solved the problem.
