### ISSUE TITLE
Add support for 'Go to definiton' on page parts (PagePartID)

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#168]
When creating page objects containing parts, following code can be added:

_part(SubpageName;70051003)_

Using the 'Go to Definition' shortcut on the '70051003' text (PagePartID) does not allow to navigate to the page. Similar behavior as on the DrillDownPageID, LookupPageID properties would be interesting.

**Comment by StanislawStempin** [comment]
Thanks, this is a known limitation that will be addressed in the future updates.
