### ISSUE TITLE
RunObject error 

### ISSUE THREAD

**Issue by XavierAnnabi** [Microsoft/AL#1680]
i get issues with RunObject when i try to run page .
RunObject = Page "page Name"; I get => Synstax error, integer literal expected
Some pages with error => application object of type 'Page' with name XXXXX is already declared.
Thanks,

**Comment by kalberes** [comment]
Looks like the page id is not unique within your package?

**Comment by StanislawStempin** [comment]
@XavierAnnabi  - could you please paste a more complete snippet of your code? You have syntax errors in your code, it's hard to say what's causing them without seeing the full object or file

**Comment by XavierAnnabi** [comment]
Hi,
from my snippet i have just one page with this name. with the same id i have table and report but is unique for pages. 
![image](https://user-images.githubusercontent.com/36770013/36673450-d5fceacc-1ad0-11e8-9f3c-0e23c23d9fd8.png)

**Comment by kalberes** [comment]
Are you using the latest February Docker image? 
What happens if you close VsCode and reopen. Do yo still get the duplicate page issue?

**Comment by XavierAnnabi** [comment]
yes my environment is updated but when I put comment on RunObject that call this page it works 
![image](https://user-images.githubusercontent.com/36770013/36691763-2efaa23a-1b04-11e8-9189-a991ed089f1e.png)

Thanks,

**Comment by XavierAnnabi** [comment]
Hi, 

Action or group with the same name as field  i get error. 
![image](https://user-images.githubusercontent.com/36770013/36736990-f53d343c-1ba7-11e8-9a4c-e18a92b358ac.png)

Thanks,
