### ISSUE TITLE
Question: Stand alone compiler for CI / CD available ?

### ISSUE THREAD

**Issue by tonioknuth** [microsoft/AL#1681]
We want to build a continuous delivery pipeline for our AL code extensions, but we are stuck at the "build" step at the moment. Is there a compiler for AL code available, other than the one built into the AL code extension in VS code ? Or are there plans to release something of the sort in the future ?
We really want to avoid taking apart the VS code extension :)

**Comment by tfenster** [comment]
Not strictly an answer to your question, but you might want to check [https://www.axians-infoma.de/navblog/optimize-ci-build-appveyor-multi-stage-image/](https://www.axians-infoma.de/navblog/optimize-ci-build-appveyor-multi-stage-image/) where I have an example about how to use a multi-stage build container to extract the compiler

**Comment by kalberes** [comment]
The only available one is the alc.exe released with the vsix package in the extensions folder. But that one acts as a standalone compiler. I am not aware of any plans to package it differently. But I mark this request as a suggestion.

**Comment by Gallimathias** [comment]
You can make your own. The AL extension is not really a real compiler it only packs the code into a zip file. Only on the server will AL code become real C# code. So you can either get the .exe from the al extension or create your own one. This is not complicated ;)

**Comment by tonioknuth** [comment]
Thanks everyone, that was very helpful! Especially @tfenster, your examples helped us alot. We have successfully used powershell and the alc.exe to bundle and deploy an extension. Once we have finalized the scripts we will spin up a repo and link it here :)

**Comment by EmilDamsbo** [comment]
This is available in AL-Go for GitHub:
https://github.com/microsoft/AL-Go
