### ISSUE TITLE
Event Request Page 344 Navigate

### ISSUE THREAD

**Issue by danielrodgers** [Microsoft/AL#1682]
On Page 344 it is possible to add additional entries to the Navigate page using events

```
LOCAL [IntegrationEvent] OnAfterNavigateFindRecords(VAR DocumentEntry : Record "Document Entry";DocNoFilter : Text;PostingDateFilter : Text)

LOCAL [IntegrationEvent] OnAfterNavigateShowRecords(TableID : Integer;DocNoFilter : Text;PostingDateFilter : Text;ItemTrackingSearch : Boolean)
```

However the OnAfterNavigateFindRecords does not apply when using Navigate via Item Tracking

The following event would be useful
`LOCAL [IntegrationEvent] OnAfterNavigateFindTrackingRecords(VAR DocumentEntry : Record "Document Entry";SerialNoFilter : Text;LotNoFilter : Text;ItemNoFilter : Text;VariantFilter : Text)`

Which would be called during the FindTrackingRecords() function

```
[ ... ]
    TempRecordBuffer.SETRANGE("Table No.");
  UNTIL TempRecordBuffer.NEXT = 0;

// +++++++
OnAfterNavigateFindTrackingRecords(Rec,SerialNoFilter, LotNoFilter, '','');
// -------

DocExists := FIND('-');

UpdateFormAfterFindRecords;
Window.CLOSE;

```

**Comment by gudrunleos** [comment]
Hi.
Regarding the event OnAfterNavigateShowRecords it would be smashing to get the PostingDateFilter there as well, we can then choose to use it or not on our data.

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
