### ISSUE TITLE
Page Extension Property : Visible

### ISSUE THREAD

**Issue by gakitikori** [Microsoft/AL#1683]
The Page Extension Property Visible = false does not remove the Action Button that is Promoted to Home TAB on the Ribbon.
It however removes/hides it from the TAB where the button is originally located.
How do we remove/hide the Action Button from Home TAB on the Ribbon?

(Dynamics NAV 2018 NA 11.0.20348.0)

**Comment by kalberes** [comment]
Are you also using some of the other promoted action properties in combination with Visible? Eg. PromotedOnly=True ?

**Comment by gakitikori** [comment]
When I used Visible = false only, the result is as follows:
      On Home TAB on the Ribbon
            Action Button Remains Visible (Failed)
      On original Action TAB on the Ribbon
            Action Button is Hidden (Passed)

When I used Visible = false along with Enabled = false, the result is as follows:
      On Home TAB on the Ribbon
            Action Button Remains Visible (Failed)
            Action Button is disabled (Passed)
      On original Action TAB on the Ribbon
            Action Button is Hidden (Passed)

**Comment by DominikDitoIvosevic** [comment]
Hi @gakitikori .
When I try to use code

```
pageextension 50123 MyPaex extends "Customer List"
{
    actions {
        modify("Customer - Balance to Date") {
            Visible=false;
        }
    }
}
```

I cannot see the action on either the promoted ribbon nor the reports ribbon.
Could you please provide us a specific scenario where you are experiencing this issue?
Are you running the latest developer preview or on prem?

**Comment by DominikDitoIvosevic** [comment]
Hi @gakitikori . This is a repo for the developer preview. Please provide us with a small extension which reproduces the issue and try on the latest developer preview. Otherwise, please use the regular support channel for on prem issues

**Comment by DominikDitoIvosevic** [comment]
Closing for lack of response and no viable repro for Developer Preview. If this is a Nav 2018 issue please open a support request as described https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by gakitikori** [comment]
I have updated my Insider version to 1.24.0-Insider.
The issue now seems fixed.
Thanks
