### ISSUE TITLE
We need events on CU 1521  Functions:

### ISSUE THREAD

**Issue by shalu712** [Microsoft/AL#1684]
Hi Team , We need events on CU 1521  Functions: OpenDocument, ReleaseDocument As we have added a new workflow template and we need to update the status at every stage for our table (in our case it is NonStock Item table). Function: InsertApprovalsTableRelations CU 1502 Reason : to Insert Table relation with table (for which we have written approval Process).

**Comment by Gallimathias** [comment]
@shalu712 Could you please insert your issue into the description field and not use everything as title. It is better to have a meaningful short title and then describe it in detail.

**Comment by shalu712** [comment]
@Gallimathias , done. My apologies for that.
