### ISSUE TITLE
Report.SAVEASPDF is not supported in NAV 2018 using Extension 

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1686]
What is the workaround for saving a report as .pdf as REPORT.SAVEASPDF is not supported for Extension Development?

**Comment by ajkauffmann** [comment]
What about saving to an OutStream:

`Report.SaveAs(ReportId, Parameters, ReportFormat::Pdf, OutStr, RecRef);`

See also: https://msdn.microsoft.com/en-us/library/dn762343(v=nav.90).aspx
