### ISSUE TITLE
Global page variable when using dependent apps 

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1688]
I've been experimenting with moving our tests to a new app that is dependent on our solution. In that process I encountered this "informative" error (and a large boring stack trace):
```
[Error - 14:26:13] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/previewDocument' failed with error: 'Object reference not set to an instance of an object.'
```
It happens because we had a global page variable in one of our tables (in the base solution). I was able to define the variable as local as a workaround.

To reproduce you can create two Al projects, base and sub. In the base app define a table like this:
```
table 50101 MyTable
{
    fields { field(1;MyField; Integer) { } }
    keys { key(PK; MyField) { Clustered = true; } }
    var
        myPage: Page 384;
}
```
Add the base app as a dependency in the sub app and download the symbols. Reference table 50101 in the sub app and then go to definition will not work for the table nor building the sub app.

Tested on 11.0.20539.0-finus and AL Compiler version 0.14.17291

**Comment by kalberes** [comment]
Are he two projects in a multiroot workspace in VsCode?

**Comment by kvaldik** [comment]
No, they are not multiroot, I haven't ventured into that yet.
