### ISSUE TITLE
Error if action or group with the same name as field.

### ISSUE THREAD

**Issue by XavierAnnabi** [Microsoft/AL#1695]
I get error if I create action or group with the same name as field.
![image](https://user-images.githubusercontent.com/36770013/36737234-97b49160-1ba8-11e8-9cf0-cf6a248ccc77.png)

Thanks,

**Comment by StanislawStempin** [comment]
Rename either the action/group or the field to fix the error. It's not allowed to have multiple members with the same name in AL (as opposed to C/AL where this was allowed)
