### ISSUE TITLE
C/SIDE Code Units are not supported in [AL] Extensions 2.0 ? 

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#1698]
![image](https://user-images.githubusercontent.com/36566794/36751861-6b22250a-1bcf-11e8-8ee1-74176a69c9f5.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/36751967-b43878a2-1bcf-11e8-9a2b-7cb4e3b01298.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/36752558-65a3bfc4-1bd1-11e8-8bf9-815bbce6196b.png)

**Comment by sgiordy** [comment]
You need to mark the function as EXTERNAL visibility.

![functionvis](https://user-images.githubusercontent.com/17341714/36754171-98ccf424-1c08-11e8-90e9-10843f6b6142.PNG)

**Comment by dennisaubrey** [comment]
How do we ask Microsoft in there next CU update for Dynamics 2018,  make all Code Units in [C/SIDE] External - so that the Microsoft Code Units can be called from within [AL] in VS CODE?

**Comment by StanislawStempin** [comment]
See: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#the-type-or-method-xyz-cannot-be-used-for-extension-development

Please log an issue for the functions that you need us to mark as External. Please note that in a NAV 2018 On-Premise installation you can either mark the functions as External yourself or you can set Target=Internal for your extension, giving you access to all functions. However, Target = Internal can only be used on-premise, it won't work in the cloud deployments.
