### ISSUE TITLE
In-Client Designer adds a record in the Extension Management

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#170]
It looks really bad, and I don't think this can be the idea.. .
What happens in a multitenant environment?  is the "Designer_..." available for all tenants?

**Comment by vjekob** [comment]
I agree that there should be a difference between in-client designer extensions and "normal" extensions.

Having them accessible from PowerShell, though, is a good thing, so if you decide to fix this, please don't remove them from PowerShell output of Get-NAVAppInfo cmdlets.

**Comment by StanislawStempin** [comment]
This area is under active development and in the future if you see the designer extension in the list it will not be named Designer_GUID but something that the user picked.

**Comment by StanislawStempin** [comment]
The Designer extension now requires providing name and publisher before it's made visible to other users.
