### ISSUE TITLE
Event Request for code unit 6500-Item Tracking Management

### ISSUE THREAD

**Issue by Rajiniadvaita** [Microsoft/AL#1700]
Hi Team,

we need **OnAfterReserveEntryFilter** Event in codeunit 6500 for function **RetrieveItemTrackingFromReservEntry.**

Reason :  need some extra filters upon standard filters for ReserveEntry , as shown below.

![image](https://user-images.githubusercontent.com/31922450/36787650-d4715ff8-1cb0-11e8-8ddd-86919d575b9d.png)

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
