### ISSUE TITLE
Dynamics 365 issue=> You do not have the following permissions on TableData NAV App: IndirectRead

### ISSUE THREAD

**Issue by XavierAnnabi** [Microsoft/AL#1701]
Hi,
am trying to create extension with D365  from localhost with AAD authetification i get the issue 
**You do not have the following permissions on TableData NAV App: IndirectRead**
In NAV user card, user Permission Sets panel  i have added D365 EXTENSION MGT permission  with empty company  but i still have the issue.

Thanks for you support.

**Comment by kalberes** [comment]
So you were tying to publish and extension using the Microsoft Cloud sandbox and that failed?

**Comment by XavierAnnabi** [comment]
Am testing extension with D365 , I have created new project the same as NAV2018 but from localhost  with AAD am unable to download Symbols i get permission error.

Thanks,

**Comment by dennisfrostlander** [comment]
This sounds exactly like incorrect permission setup issue.
Could you please double check that:
- You have granted the D365 EXTENSION MGT in the Cloud Sandbox environment (and not in the main environment)
- You are using correct launch.json settings to connect to the tenant (no server, server instance are specified)
- You are logged in as a correct user in VSCode. To ensure that, press F1, then choose `AL: Clear credentials cache` and try to publish the extension again.
