### ISSUE TITLE
hide / choose columns

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#1703]
I'm not sure if this is an AL issue, but it seems no longer possible to hide / choose columns. See screenshot, the left side was I think the December update, in which I can select columns. On the right is the February update, in which that is not an option. Am I missing a setting or something?

![image](https://user-images.githubusercontent.com/23434319/36817713-681b74bc-1c9f-11e8-955d-950358f058fa.png)

**Comment by TheDenSter** [comment]
Today I'm looking a bit more at this, and it looks like this is by design in favor of doing page personalizations as extensions. If that is the case, could you please reconsider and putting hide/choose columns back? Hide/choose is simply a way to turn visibility of fields on the page on/off, it doesn't have to be a full fledged page extension. I'll have to check but I'm afraid the generated app dependencies are going to create issues.

**Comment by kalberes** [comment]
The team in charge claimed that this is the intended behavior as you have also figured out.
Personalization will provide the same semantics as choose columns.

**Comment by mikebcMSFT** [comment]
What you are experiencing is the correct behaviour going forward.
Developers can use the Designer to adjust column visibility and ordering, which is saved to the extension under development.
End-users can enable Personalization and also adjust column visibility and ordering, which in their case is saved to the database as part of their roaming personalization store.

Does that make it easy enough for you to adjust your table columns?

best regards,
Mike Borg Cardona

**Comment by TheDenSter** [comment]
Ok I think I was getting things mixed up, I was talking about the in-client designer and calling it personalization. I thought that the in-client designer was supposed to be used as a replacement for hide/choose columns, which is a REALLY bad idea. I did not know about the actual 'personalization' option, so thanks for pointing that out :)
