### ISSUE TITLE
In-client designer creates unnecessary dependent app

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1704]
The in-client designer creates an app that is dependent on every single app that is installed at the moment the in-client designer is being used. Regardless of using nothing from these installed apps. That creates unnecessary dependencies on already installed apps.

**Comment by kalberes** [comment]
The reason why this is like this is because fields from any of the installed extensions could potentially be modified or be anchors to other modifications, so they all need to be added as dependencies.

**Comment by ajkauffmann** [comment]
I was afraid of that answer.

Imagine this scenario: an end customer first installs a number of apps, then creates a designer app and finally decides to remove one the previously installed apps. That will not be possible, even if those apps are totally unrelated. He will need to remove the designer app first, then remove the app he doesn't want anymore and then manually recreate the designer app.

And what about upgrading scenario's? If one of these apps needs to upgrade, there you need to uninstall the old version. But that will require to uninstall the designer app as well.

Maybe I'm wrong, but if this behavior is by design, then please reconsider it. I can understand that it is complex to determine if the designer app does something with an already installed app. But then again, now it is creating so much dependencies, I'm really afraid this is going to cause a lot of support issues and negative user experience.

**Comment by kalberes** [comment]
It is by design for now. But there are backlog work items to improve it. The timeline is the question.

**Comment by ajkauffmann** [comment]
Great that there are backlogs items to improve it. Of course it will take some time, I can see that. Lot of work to do.

One suggestion to make this work quite simple:
- Create the designer app with dependencies to all existing apps
- Remove the dependencies one by one, compile the designer app after removing each individual depency
- If the app doesn't compile anymore, add that dependency again and move on to the next one

It looks a little bit dirty, but it should work like a charm. It simplifies the process, because you don't have to track all individual changes and to see if there is any reference to an app instead of the base application.

Of course this is just a suggestion from someone who doesn't exactly know how the internal stuff works ;-)

**Comment by AncaSterian** [comment]
Dear @StanislawStempin ,

Do you have any information regarding the progress or the request above?

We are currently working for a localization extension and we had the situation described above during the testing phase. Our business consultants took advantage of this feature but the we realized the problems. 
Currently they don't use  anymore the designer mode, at least until the major testing process is finished. 
The question is how can we explain,  if we implement to one customer, not to use this functionality. 
This is one of the most appealing for the key users... 

The workaround to download all these extensions, unpublish them and the rebuild them again it is time consuming and to be honest a nightmare for developers, consultants and customers. 

Does Microsoft has in plan to solve this issue? 

Looking forward to your answer. 

Kindest regards,
 Anca

**Comment by qutreson** [comment]
This issue has been fixed some time ago. The fix was delivered as part of CU 2. If you already have some designer extensions, moving a field using the designer mode will fix their dependencies.
