### ISSUE TITLE
Download source code with in-client designer only possible once

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1705]
The option to download the source code from the in-client designer is only offered once.

Wouldn't it be an idea to include the source code in the app by default? That would open the possibility to download the source code afterwards, in case you changed your mind and want to adopt the changes in a VS Code workspace. And it would allow to open the app again in design mode so you don't have to create a new in-client designer app in case you do further modifications with the in-client designer.

**Comment by joergrau** [comment]
Not sure which scenario this applies to Arend-Jan, but when I open the designer from VS Code with F6, carry out changes, save with default name (which is the name of your extension), then go back to VS Code and press F7, it downloads the changes to my code. I can do this multiple times.
In another scenario, where you use the designer directly in the browser, save your changes (under a new name with dependency to your extension) then you can see the extension also in the Extension page and there is also a download option. Again, not sure if you refer to these scenarios or if I missed the point.
