### ISSUE TITLE
Expose function T38.ValidateShortcutDimCode

### ISSUE THREAD

**Issue by andreasvictorin** [Microsoft/AL#1706]
Please make the function ValidateShortcutDimCode in table 38 Global and External

```
[External]
PROCEDURE ValidateShortcutDimCode@19(FieldNumber@1000 : Integer;VAR ShortcutDimCode@1001 : Code[20]);
```

![image](https://user-images.githubusercontent.com/36952029/36837323-584baf50-1d3c-11e8-8ed4-e6bc626e3f3a.png)

**Comment by JesperSchulz** [comment]
I've addressed this together with request https://github.com/Microsoft/AL/issues/1221. The code has shipped a couple of days ago.

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)
