### ISSUE TITLE
Extensions not recognizing custom tables

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1708]
I am trying to make an extension that moves data from old custom tables into new tables created by extensions.
I am going to make an upgrade codeunit to do that.

However, I cannot declare a variable with reference to table 50.000 (The old custom table).

Are there any tricks to do so?

**Comment by bleisibach** [comment]
Have you tried this?
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side

**Comment by peikba** [comment]
Yes I did try that.
But maybe not in the right sequence.

It works now, thanks.
