### ISSUE TITLE
System Event OnBeforeValidateEvent on Pages: Some ElementNames missing in AL

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/AL#1711]
In AL, the ElementName **InvDiscountAmount** for EventSubscriber Page 160, OnBeforeValidateEvent is not recognized:

![image](https://user-images.githubusercontent.com/36630655/36858573-c3eef732-1d7b-11e8-840a-1bd8d6a89149.png)

In C/AL, the Subscriber to Page::Sales Statistics.OnBeforeValidateEvent.**InvDiscountAmount** works fine:

![image](https://user-images.githubusercontent.com/36630655/36858165-b7a71410-1d7a-11e8-8e9d-065a4f867a7b.png)

**Comment by thpeder** [comment]
Hi @bleisibach,
What version are you running?

**Comment by bleisibach** [comment]
I was running on Prem CU 02, sorry for not checking against latest preview. I will check against latest preview and if it still occurs, I will reopen the isse.
