### ISSUE TITLE
Suggestion: Action images in intellisense

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#1714]
As documentation property of vscode.CompletionItem can contain markup content, could you include all action images in the extension and display them with completion entries for action image property? It would be nice to have something like this:

![actionimages gif](https://user-images.githubusercontent.com/24944969/36874533-300bffdc-1da4-11e8-9793-60bb80319952.gif)

**Comment by kalberes** [comment]
Good idea.

**Comment by anzwdev** [comment]
It looks great, thank you.
