### ISSUE TITLE
Record "Event Subscription" cannot be used for extension development

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#1715]
I was in the process of writing a blog post explaining a nice extension to Discovery Event pattern, and I got far too enthusiastic so I started writing it in AL. In C/AL, my Discovery Event pattern extension works amazingly, but at the heart of it is being able to do this:

var DiscoveryState: Record "Event Subscription" temporary;

Apparently, this is not possible in AL, because "The type or method 'Event Subscription' cannot be used for extension development"

Is this something you plan on supporting but you didn't have time yet. Or is it something you explicitly decided not to support for some reason?

**Comment by kalberes** [comment]
For now you can only use it for non SAAS scenarios.
We will investigate it if this virtual table really does not pose any cross tenant information.

**Comment by vjekob** [comment]
I understand that cross-tenant is a consideration. However, since it's a virtual table, why not having either a "Tenant Event Subscription" table that shows event subscribers coming from current tenant, or simply have "Event Subscription" table show only the content for the current tenant?

Making it completely inaccessible is limiting us in what we can do with the product.

**Comment by qutreson** [comment]
Marking #428 for issue tracking

**Comment by StanislawStempin** [comment]
We will use #428 for tracking the implementation of this suggestion.
