### ISSUE TITLE
The request for path /v1.0/sandbox/dev/apps failed with code 422. Reason: The extension specifies a higher compilation target than allowed.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1717]
Hello,

Facing the following error while publishing the extension to the sandbox.

The request for path /v1.0/sandbox/dev/apps failed with code 422. Reason: The extension specifies a higher compilation target than allowed.

Can anyone help me to fix this issue..

Thanks

**Comment by srinivasdes** [comment]
Hi thpeder,

Thanks for your reply.

But if i changed the target value to extension following methods are not found with AL package.

TEMPORARYPATH
Report.SAVEASPDF
BLOBImport
BLOBExport
FileMgmt.UploadFile
ExcelBuf.OpenBook

Is there any chance to have the above methods to al extension package to ignore the compile error.

Thanks.

**Comment by thpeder** [comment]
I'll recommend you searching through issues here on Github.
For example TemporaryPath was discussed here: #479.

If your plans are to only run your code on-premise and never to publish it to AppSource then you can switch back to use `"target":"Internal"`.
To get started on that you can either create a machine on Azure from our template at [http://aka.ms/navdeveloperpreview](http://aka.ms/navdeveloperpreview)
or use the containers we make available which you can read more about here: [https://github.com/Microsoft/nav-docker](https://github.com/Microsoft/nav-docker)

**Comment by DominikDitoIvosevic** [comment]
It looks like this issue was resolved. If you have more issues please open a new issue
