### ISSUE TITLE
Incorrect GetUrl in D365

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#1719]
We have an extension running live in D365 and we are relying on the GetUrl function and are getting incorrect results in the web client and the [Fin and Ops](https://docs.microsoft.com/en-us/dynamics365/financials/install-mobile-app) app.

In the web client, GetUrl returns:
`https://mytenant.financials.dynamics.com/MS?tenant=mytenant.financials.dynamics.com`
But to work either the MS part has to be removed or /webclient added:
`https://mytenant.financials.dynamics.com/?tenant=mytenant.financials.dynamics.com`
or
`https://mytenant.financials.dynamics.com/MS/webclient?tenant=mytenant.financials.dynamics.com`

In the Fin and Ops app, GetUrl returns:
`ms-dynamicsnav://mytenant.financials.dynamics.com:443/MS?tenant=mytenant.financials.dynamics.com`
But the Fin and Ops does not register to that scheme (ms-dynamicsnav) and therefor does not start. I don't know if it responds to any other scheme but if it does then the GetUrl functionality needs to be updated. If it does not respond to any scheme it needs to be added and the GetUrl functionality updated as well.

**Comment by kvaldik** [comment]
I'm not sure if question is the correct label for this issue. From my viewpoint this is clearly a bug or a configuration issue.

**Comment by kalberes** [comment]
Agree.  Looks like a bug. It has not yet been yet acknowledged as one though.

**Comment by unnur** [comment]
Any news on when this will be fixed?

**Comment by kvaldik** [comment]
Hi @kalberes.

To the best of my knowledge this is not an issue in in Nav 2018. As I stated in my original post this is blocking our app (LS Express) which is already live on D365 Business Central!

Could you please contact the owning team and have them take a look at this issue as soon as possible?

**Comment by kvaldik** [comment]
hi @StanislawStempin .

Now we have a tenant in D365 BC and there this issue is fixed when browsing BC in the web client.

But if I'm in the [Business Central app](https://www.microsoft.com/store/productId/9NBLGGH4QL79) GetUrl still returns an URL to to Dynamics NAV app (ms-dynamicsnav).

This is not a live site issue but a bug, either in the GetURL function or a missing scheme registration in the BC app (or both) as I mention in the original issue.

**Comment by StanislawStempin** [comment]
Most likely your tenant has not been updated to the latest version yet. Please retry in a few weeks and open a new issue if the problem still persists.

**Comment by kvaldik** [comment]
Alright, that just might be the case. But could you confirm that we are waiting for a change in the GetUrl functionality? Cause in my mind there are two solutions to this problem:

1. The Business Central app already registers a scheme but the GetUrl isn't returning it. In that case we are waiting for the tenant to be updated. It would also be nice to get that scheme in order to confirm that it does in fact work.
2. The Business Central app isn't registered as `ms-dynamicsnav` but will be. In this case we are not waiting for the tenant but for the app to be updated.

I want to make sure that we are waiting for the correct solution cause we have been waiting for almost three months now.

**Comment by pborring** [comment]
GETURL AL function should now return (from update 15 on up):
•	https://businesscentral.dynamics.com/ as the base Url
•	Ms-businesscentral:// as the protocol for mobile apps

The protocol registered for the app was just tested to confirm it is registering the correct one in the OS.

If you see a different behavior, please report back, as this is unexpected.

**Comment by kvaldik** [comment]
Hi @pborring.

Thanks your response, it really helps to see what has been fixed. I've confirmed that the protocol ms-businesscentral works. Now we just wait for the GetUrl to update.
