### ISSUE TITLE
New procedure on TableExtension does not include "Rec" variable

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#172]
Consider this TableExtension, where I put an extra procedure on the Item table:
tableextension 70050001 ItemTableExtension extends Item
{
    fields
    {        
        field(70050000;"Item Classification Code";Code[10]){
            TableRelation = "Item Classification"."Code";
        }
    }

    procedure CalcItemClassification();
    var
        CalcItemClassification:Codeunit "CalcItemClassification Meth.";
    begin
        CalcItemClassification.CalcItemClassification(Rec);
    end;
}

this does not compile - I'm not able to use the "Rec" like that (which I might expect).

either it's a bug, or I'm doing something wrong :-)

**Comment by esbenk** [comment]
It is a bug.
