### ISSUE TITLE
The multilanguage syntax is being deprecated. Please update to the new syntax.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1720]
Hello,

Facing this warning with CaptionML property and TextConstants.

Warning : The multilanguage syntax is being deprecated. Please update to the new syntax.

Existing Syntax : 

CaptionML=ENU= 'Mail Templates',ESM='&Plantillas correo', FRC='&Modèles de courriel',
ENC='&Mail Templates';

Text001 : TextConst ENU='Item No %1 does not exists.';

Can anyone please help me to fix this.

Thanks.

**Comment by Gallimathias** [comment]
Translations are now stored in xliff files, so there are no ML properties anymore. Use Caption and Label and activate the xliff function in your app.json
Look at this example:
[GetAddressService](https://github.com/Microsoft/AL/tree/master/samples/GetAddressService)

**Comment by srinivasdes** [comment]
Hi Gallimathias,

Thanks for you r reply.

I didn't get the activate the Xliff function in our app.json

Can you explain bit more

Thanks

**Comment by Gallimathias** [comment]
After you have created a project, you have to add the following in your app. json in your workstation:
````json
"features": "TranslationFile",
````
After you build your app, a standard xliff file will be created automatically. It already contains all your standard translations as source.

For each language you now make a copy of this file in this automatically created folder. Name them after the language and insert your translation.

The final result should look like the example above.

**Comment by TheDenSter** [comment]
Here's a link about that: https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-work-with-translation-files

Use Label to replace text constants

**Comment by DominikDitoIvosevic** [comment]
Hi @srinivasdes .
This warning only appears if you have the compiler feature for translating turned on. By having it on you are signalling that you are moving to the label syntax so we warn you where you have used the deprecated syntax

![image](https://user-images.githubusercontent.com/6378638/36971273-909094c0-206b-11e8-8857-0d5b4a6c3ee0.png)

If you remove the value from app.json you will stop seeing the error but we encourage you to rather update your code

**Comment by DominikDitoIvosevic** [comment]
@srinivasdes I hope that we have resolved your issues. If you have more questions please open a new issue
