### ISSUE TITLE
DotNet availiability in your FAQ

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#1722]
In [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions) there is 

> DotNet types are not available in Extensions V2. What now?
> On-Premise:
> DotNet interop will be available at some point in the future but not in the NAV release this year.

Which year you mean? ;-) What is the reality today?

**Comment by SirBETE** [comment]
MS has been creating the [cal-open-library](https://github.com/Microsoft/cal-open-library).
This library contains modified objects which have added functions to replace dotnet functionality (like COD10 Type Helper has 2 extra functions 'ConvertValueFromBase64' and 'ConvertValueToBase64').

When working on-premise, you can load these objects into your object environment.
You can then recreate symbols in cmd and redownload them in VS Code ([procedure](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)).

Reason I'm responding with this info, is I also needed some replacement for dotnet usage.

**Comment by kine** [comment]
Just want to make it clear: I want to make the FAQ clear in what is stated there and to have some helping links there (e.g. adding link to cal-open-library) etc. for newcomers. Right now, when I read the FAQ, I do not know the current state of the DotNet interop.

**Comment by SirBETE** [comment]
Ahha, I understand and you are correct.
There's very few info on what's available, what's allowed of dotnet/replacements and how to use it.

**Comment by StanislawStempin** [comment]
There are links to all kinds of resources under the DotNet section in the FAQ. Maybe it's not entirely clear that they apply both to OnPrem and SaaS, I will try to change that.
Regarding DotNet support for OnPrem this is still work in progress, the FAQ comment regarding 'this year' was written in 2017 and is out of date.
