### ISSUE TITLE
How to attached a new report or a page in AL to a Menu or Callable from a Ribbon?

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#1723]
Hi,

How to attached a new report or a page in AL to a Menu? 

The Menu could already exist for example "Dept - Company" or run the report  from a  Ribbon Labeled "REPORT".
 
Could you please provide both solutions.

report 50107 "Populate Material Plan Lines"
{
.................

![image](https://user-images.githubusercontent.com/36566794/36920305-4fefdf1e-1e2e-11e8-9981-8823a08c77ed.png)

![image](https://user-images.githubusercontent.com/36566794/36920448-b1769ba6-1e2e-11e8-893e-794bb45028ce.png)

![image](https://user-images.githubusercontent.com/36566794/36921139-3bcb0088-1e31-11e8-9e91-9138cee73fac.png)

Thank you
Dennis Aubrey

**Comment by atoader** [comment]
Hi @dennisaubrey ! Please take a look at https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-adding-menus-to-navigation-pane . We will have a new article in the next days that provides more information. I will keep you posted.

**Comment by atoader** [comment]
This is the other article I was talking about: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane .
