### ISSUE TITLE
Groups and actions cannot have the same name

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1726]
Created an Action Group named Resources and then created an Action named Resources under that.
That is not possible:
![image](https://user-images.githubusercontent.com/33752561/36944590-3727fcd2-1fa0-11e8-8c5b-39184027638b.png)

**Comment by thpeder** [comment]
It is by design since you need to be able to reference them by name from a PageExtension.
For instance for this case:
```
AddAfter(Resources)
{
    action(newAction) {}
}
```

**Comment by peikba** [comment]
Ok Thank you.

Only problem is that the Txt2Al conversion does not know that :)
It also converts all separators without identifiers.
