### ISSUE TITLE
Generic Chart - not possible use queries from extension

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1727]
It is not possible to make a Generic Chart based on a query from an extension.

![image](https://user-images.githubusercontent.com/33752561/36944956-70f41012-1fa6-11e8-850b-93d28a76a896.png)

Here is the list of queries:
![image](https://user-images.githubusercontent.com/33752561/36944960-8dbce746-1fa6-11e8-8029-af6b5ebeadd5.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @peikba . Which version are you running on? Is this on prem or saas?

**Comment by peikba** [comment]
I'm running 0.14.17461 against NAV 2018 CU2

**Comment by DominikDitoIvosevic** [comment]
@peikba could you please provide us with code that reproduces this error? A zipped small extension would be great!

**Comment by peikba** [comment]
@DominikDitoIvosevic  Here it is
[Default publisher_Test Charts With Queries_1.0.0.0.zip](https://github.com/Microsoft/AL/files/1789182/Default.publisher_Test.Charts.With.Queries_1.0.0.0.zip)

Import the Extension.

Create a new Generic Chart
![image](https://user-images.githubusercontent.com/33752561/37093221-ecda3598-220e-11e8-81c8-cf63f8355132.png)
Select the Query from the  Extension (It is visible)
![image](https://user-images.githubusercontent.com/33752561/37093266-0f14874e-220f-11e8-8eb9-cfbffae4764d.png)

and I get the Error

**Comment by peikba** [comment]
@DominikDitoIvosevic 
It is still a problem in Dynamics NAV 2018 CU3

**Comment by StanislawStempin** [comment]
A few side notes:
Al Language 0.14 should not be used with NAV 2018. See the FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

This GitHub repo tracks issues only for the latest version of Dynamics 365. See this FAQ entry for more details about NAV 2018 process: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues

**Comment by DominikDitoIvosevic** [comment]
@peikba this issue is fixed in the latest developer preview and this issues page is for tracking issues for the Developer Preview. If you would like to have your bug backported please open a request through the NAV 2018 process: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues
