### ISSUE TITLE
Conversion should be possible with PowerShell

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#173]
A few suggestions:
- I'm not able to export the objects using the default Export-NAVApplicationObject .. please provide a parameter where I can control this "ExportToNewSyntax" command.. .  Or build a new functions that is part of the Model.Tools module.. .

- I'd like to be able to fully do the conversion out-of-the-box with PowerShell - as this makes much more sense then fumbling around with cmd.exe :(.  I have created a first draft here:

[Export-NAVALfromNAVApplicationObject.zip](https://github.com/Microsoft/AL/files/958365/Export-NAVALfromNAVApplicationObject.zip)

**Comment by StanislawStempin** [comment]
Good suggestion, we'll look into it.
