### ISSUE TITLE
Need to regenerate translation files

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#1734]
I've noticed this a few times now. When I create a new container, and then publish an existing AL workspace, it does not pick up the captions from the translation file. The only way I seem to be able to get the captions into the app is by deleting the translation file and rebuilding the app.

**Comment by TheDenSter** [comment]
Another way to repro is to change the publisher in app.json. Build again and it doesn't pick up the caption, you have to delete the translation file and rebuild to make captions appear. 

Is it by design to have to re-create the translation file in certain cases?

**Comment by DominikDitoIvosevic** [comment]
This is definitely not intended. Could you please tell us what version you are using? Are you using your own translation files or just have the one which is automatically generated?

**Comment by TheDenSter** [comment]
NAVContainer: 11.0.20723.0-finus
AL Language: 0.14.17461
I only have the translation file that is generated by VSCode.

I'm using a developer preview VM that I created over this past weekend, so I think I have the latest. I just did a Replace-NavServerContainer to reproduce it and it happened again. The captions did not show up with my existing workspace, and I rebuilt the package explicitly. After I deleted the translation file and rebuilt the solution, the captions showed up. Then I changed the publisher name, hit F5 and the captions were gone again. Deleted the translation file again, and it worked again.

What is interesting is that GIT does not see a change in the translation file during all this regeneration.

**Comment by DominikDitoIvosevic** [comment]
Hi @TheDenSter .
This issue sounds a lot like what https://github.com/Microsoft/AL/issues/1692 waldo and aj are experiencing.
We had a few fixes since 20723 so could you please try this on a later version?

**Comment by TheDenSter** [comment]
Hi @DominikDitoIvosevic 
The app has been submitted and the VM is deallocated at the moment, and I am swamped with some other things. I expect validation issues down the road and as soon as those come in I'll try a newer build. Looking at AJ's reply I trust that the issue has been fixed, so if you want you can close this issue. If I run into it again I'll come back and reply again in here. Thanks for looking into this.

**Comment by DominikDitoIvosevic** [comment]
I suppose that's all right. Could you please open a new issue and reference this one (if you need to) because it's harder for us to track already closed issues?
