### ISSUE TITLE
OnLookup doesn't fetch the data

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1736]
I've a field called Promotion in an Customized Page. In the OnLookup trigger I've written a code to fetch the seleted data from the page PromotionListPageFiltered but onLookup the PromotionListPageFiltered appears also it allows to select the data but it doesn't fetch it.

Below is the attached image

![promotion](https://user-images.githubusercontent.com/24870777/37017104-3eccb630-2135-11e8-92a7-609594da7adf.PNG)
![getselectionfilter](https://user-images.githubusercontent.com/24870777/37017233-d5f16e20-2135-11e8-9e35-e80c20d7be68.PNG)

![issue](https://user-images.githubusercontent.com/24870777/37017154-7a6f8618-2135-11e8-9e7a-3301d39d3003.PNG)

**Comment by pmohanakrishna** [comment]
1st paramenter should have VAR
https://github.com/Microsoft/AL/issues/1510

**Comment by DominikDitoIvosevic** [comment]
@pmohanakrishna thank you very much for linking! 
@Chris-Dsilva has setting var solved your issue?

**Comment by Chris-Dsilva** [comment]
Yes setting var worked for me. Thanks @pmohanakrishna
