### ISSUE TITLE
Error on building package for XMLports

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1737]
I'm getting the below error on building XMLports. This package was working fine and even published successfully before adding XMlports.

![xmlport](https://user-images.githubusercontent.com/24870777/37022680-b81072de-2149-11e8-9fab-95b9c16becbc.PNG)

**Comment by Chris-Dsilva** [comment]
Hi @DominikDitoIvosevic , I've disabled condeLens still the issue persist

**Comment by DominikDitoIvosevic** [comment]
@Chris-Dsilva could you please try to isolate which code is causing this issue? Right now we don't have enough to know what is causing the problem.

**Comment by Chris-Dsilva** [comment]
Hi @DominikDitoIvosevic ,
I tried isolating the xmlport and found the below xmlport is the cause of the issue
I'm using NAV 2018 CU 2 NA version.
[XMLport 50000 - CF_ADP Payroll Entries Import.zip](https://github.com/Microsoft/AL/files/1788419/XMLport.50000.-.CF_ADP.Payroll.Entries.Import.zip)

**Comment by DominikDitoIvosevic** [comment]
This should be fixed in the next update of Developer Preview

**Comment by DominikDitoIvosevic** [comment]
Hi @Chris-Dsilva . Is this some legacy code being converted from v1 or is this new code written from scratch in v2? My first guess was to try and recreate the code in cside but to me it seems that the xmlport nodes should not be visible on variables of type xmlport
