### ISSUE TITLE
Generic Charts cannot be added to Role Centers

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1738]
Converting a Role Center containing a Generic Chart the suggestion looks like this:

![image](https://user-images.githubusercontent.com/33752561/37025217-6845312c-212b-11e8-8d0b-75c5082f47f8.png)

However implementing it in a runnuing solution, I get an error:

![image](https://user-images.githubusercontent.com/33752561/37025355-cb0a82da-212b-11e8-84c2-5ebc9836f211.png)

Is there another way?

/Peik

**Comment by DominikDitoIvosevic** [comment]
Hey @peikba .
We have added support for chart parts.
This is the syntax:

```

pageextension 50101 CustomerListExt2 extends "Customer List"
{
    layout {
        addfirst(FactBoxes) {
            chartpart(mychartPart; "Q5400-01") {

            }
        }
    }
}
```

It should be available on the latest dev preview
