### ISSUE TITLE
Extension Version and Dependencies

### ISSUE THREAD

**Issue by janhofmann24** [microsoft/AL#1739]
Hi!

I tried to create an App A and an App B, which is dependent on App A.
This initially works well, but if I change the version of App A, I cannot deploy it without also changing the dependency in App B to the new Version of App A.

So I would have to 
- Change the app.json of App B
- unpublish App B
- unpublish App A
- publish the new version of App A
- publish the new version of App B

This each time an App with a dependendent App changes the Version. And the example above is pretty simple. There could be chains of dependencies.
Changing the last digit of the Version in my eyes would be a good practice for every check-in/build to be always be able to check in the Source Control system what really is currently installed. 

Is there a way to avoid this? Maybe the last one or two digits could be more relaxed and if an App really does a structural change (change on Event Publisher, global Function or Field), the first two digits could be used? Or maybe it could be possible to use Wildcards in the app.json for the dependency to allow everyone to define it themselves?

**Comment by DominikDitoIvosevic** [comment]
@janhofmann24 the wildcards approach really seems the most sensible, especially regarding the last digit which is for minimal changes. I'll use this issue for tracking

**Comment by kalberes** [comment]
If all projects exist in vscode then the existing dependency publishing subsystem should solve this with the help Publish Full dependency tree for the active project. 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-workspace-projects-references
Else it is a new ask:

Hi,
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
