### ISSUE TITLE
Error happens when a table has the same ID as a tableextension object

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#174]
If you create a table and a tableextension object with the same ID, accessing the page over the table that was extended results in the following runtime error:

"Invalid application object code was found. Recompile all objects."

Example code:

tableextension 71234567 Extension extends Customer
{
    fields
    {
        field(71234567;Test;Integer) {}
    }
}

table 71234567 DuplicateId
{
    fields
    {
        field(1;Code;Code[10]) {}
        field(2;Description;Text[50]) {}
    }
}

After deploying this, try accessing Customer List, or Customer Card pages, and you get the error: "Invalid application object code was found. Recompile all objects."

If a tableextension is a separate object type, then this should not be a problem.

**Comment by StanislawStempin** [comment]
This was a bug. The fix will be shipped in May Update.

**Comment by markbrummel** [comment]
Thanks Vjeko, I was chasing this message for the last few days.
