### ISSUE TITLE
Language priorities

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#1741]
Hello,

I have been testing with the XLIFF translations and have experienced an interesting behavior.

Imagine I have an extension with 3 texts, and I have translated some of them (not all), to different languages.
   en-US (English – United States): Text1, Text2, Text3
   fr-FR (French – France) : Text1, Text2 
   fr-BE (French – Belgium): Text1

In the UI, I select the French – Belgium language. I have noticed that for a any given text,
- If the fr-BE exists, it shows it
- **If not, if the fr-FR exists, it shows it**
- If not, it shows the en-US text

So, I end up with this result:
![image](https://user-images.githubusercontent.com/32334451/37031100-d30b91ce-213d-11e8-93a8-3403b773f751.png)

This is new. I don't know if it's NAV2018, or the XLIFF translations, but in the past the system only checked for texts in the UI language.

I haved checked the other way around, having the BE text, but not the FR text.
The BE UI picks the FR texts, but the FR UI does not pick any other french tranlation.

So I came with this (not complete) list:
- fr-FR Interface: priorities are fr-FR, en-US
- fr-BE Interface: priorities are fr-BE, fr-FR, en-US
- fr-CA Interface: priorities are fr-CA, fr-FR, en-US
and so on

Now, I have a few questions:
- Can anyone confirm if this is the way it works?
- What about the other languages like Spanish, Portuguese, or German?  For each of them, which language-code is the one having "priority"?
- If I want to publish on AppSource and have the extension available in Canada, is it requiered to have all texts translated to fr-CA , or can I publish it even if I have them only translated to fr-FR?

Many thanks,

Salut!
Laura Nicolàs

**Comment by DominikDitoIvosevic** [comment]
What the compiler does in the background with the xliff approach is imitate the CaptionML behavior so the exact same thing would happen as if you had the CaptionMLs with those values.

While I'm not familiar right now with what happens, my guess would be that the fallback is first to the same language of a different country if it exists and if not then to english US. 

You have to have all the labels for all the languages you want to support. If you want to support canada, you have to have fr-CA. The nice thing about xliffs is that that means you can simply copy the fr-FR file and change the target language to fr-CA.

**Comment by LauraNicolas** [comment]
Thanks @DominikDitoIvosevic,

I am checking at the System table **"Windows Language"**, and it has a "Primary Language ID" field.

I am guessing the system:
- Shows the UI language,
- If not, it shows the texts in the "Primary Language".
- If not, is show the ENU texts.

For all French languages, the primary language is set to French-France. For Spanish, the primary is Spanish-Spain, and so on.

It looks like this have been like this for a long time (I have just checked a NAV2009R2), but I guess most of us have never played with languages that deep, so we didn't know. At list I didn't. 

Many thanks

Salut!
Laura Nicolàs
