### ISSUE TITLE
Recursive Looping

### ISSUE THREAD

**Issue by OakleyLeon** [Microsoft/AL#1742]
Hi,
Im quite new to AL programming and was wondering if someone could share some sample code that allows me to loop through the report IDs within D365 on the document layouts page and for the moment just output those to a message.  ive tried a few diffrent ways but to no avail
Thanks,

**Comment by DominikDitoIvosevic** [comment]
Hi @OakleyLeon . This is a repo for handling Issues regarding AL compiler and language development. We do not provide tranining. If you have questions regarding how to do something in AL I suggest you go to stackoverflow.com and use tags `dynamics-nav` and `al`
