### ISSUE TITLE
Automatically sign app files

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#1744]
I'm new to signing app files, so forgive me for asking a silly question. Is it possible to get the app file signed automatically when you build the solution? It would be great if all you need to do is put the certificate somewhere in the workspace and it signs automatically.

**Comment by MikeGlue** [comment]
I ended up going another route and having VSTS do the signing during the automated build process, but initially I had thought of doing a custom VS Code build task to call a script that does the build using the alc and then does the signing....something similar to below.

![image](https://user-images.githubusercontent.com/5204734/37043661-36ae18d2-212f-11e8-9205-f8b7775454e8.png)

**Comment by StanislawStempin** [comment]
We encourage to use the approach outlined by MikeGlue above. I.e. to do this as part of the overall automated build process. We currently don't have plans of integrating signing with the AL Language extension
