### ISSUE TITLE
Can we deploy Extensions to D365 Tenerife without going through appsource?

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#1746]
It is my understanding that all Tenerife modifications must be extensions that are applied from AppSource. I am hoping that I have got this wrong, because without the ability to deploy customer-specific modifications directly to a D365 tenant, I cannot imagine any of my existing customers being able to take advantage of D365 Tenerife. I believe that if MS want to make annuity revenue from hosting many of the world's existing NAV systems, they must offer partners this capability.

I was speaking to our AX team and they tell me that in the AX world they can deploy any customer-specific extensions directly to their customer's system using Lifecycle Services portal. Are we going to be able to do the same sort of thing?

**Comment by StanislawStempin** [comment]
Hi @DavidRoys, the Tenerife product reveal happens next week. We will share more details about this and other topics at Directions ASIA. I encourage you to follow the news from conference, if you/your company is not attending.

After the public reveal I will be able to provide more details on this forum as well.

**Comment by DavidRoys** [comment]
Thanks for the answer. I was not able to attend the conference. I have read MS press releases, MVP blogs, and tweets, but cannot find any official answer on this. I realize there is a lot to process and if it is possible, you will need to share details around limitations and process, but a short “yes it will be possible” would really help. Thanks for all your hard work!

**Comment by DavidRoys** [comment]
Well I guess this pretty much answers the question officially. 

http://download.microsoft.com/download/1/C/0/1C0A4DB7-9CE8-4D25-AC7F-65579E713BA8/ReleaseNotes_Dynamics365_03192018.pdf#page122

**Comment by DavidRoys** [comment]
I will close this issue since the answer to my question is clearly “yes”. Thank you.
