### ISSUE TITLE
Unable to use Library CUs function in AL environment

### ISSUE THREAD

**Issue by shalu712** [Microsoft/AL#1747]
Hi Team, I am using NAV 2018 CU2 NA version . While I am creating Test Code unit by using available Libraries getting below
message: 'The type or method 'GenerateRandomCode' cannot be used for 'Extension' development.'
Please find below the functions which I am using via libraries but unable to do so because of errors:
LibraryUtility.GenerateRandomCode
-LibraryInventory.CreateItem
-LibraryInventory.CreateNonStock
-Assert.AreEqual
Please suggest how to proceed further in test case in AL environment.

Before logging a new issue please make sure to:
1) Read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)
2) Search if there is an existing issue for what you want to log. If it's closed you can reopen it and add your comments.
3) Use the latest Developer Preview release both the server part and the AL Language extension in VS Code (listed on the [repository home page](https://github.com/Microsoft/AL))
4) If you're not using the latest released version (or are using a private build drop that is newer) please provide the version number in the issue

To help us reproduce the issue and find the root please try to:
A) Attach a minimal set of AL code that causes the issue
B) If the error occurs on the server - copy/paste the server stack trace from the Event Viewer

**Comment by Gallimathias** [comment]
if I understood you correctly then you want to use dotNet variable? The Dotnet data type is not allowed in extension development. See the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#dotnet-types-are-not-available-in-extensions-v2-what-now)

**Comment by StanislawStempin** [comment]
That's right, you cannot use DotNet in the AL language on NAV 2018. 
If you're trying to use functions that do not contain DotNet as part of their parameter list then you can simply change them from Internal to External in C/SIDE, regenerate symbols according to these [Docs](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side) and then you can use them from AL.
