### ISSUE TITLE
format document vs code analysis

### ISSUE THREAD

**Issue by Kraver88** [Microsoft/AL#1749]
Example code:
![image](https://user-images.githubusercontent.com/24684493/37086029-d9edcf3e-21f6-11e8-8512-d02abfd5c941.png)
when using Format Document (alt+shift+f) the result is the following
![image](https://user-images.githubusercontent.com/24684493/37086098-089b9848-21f7-11e8-99f3-1c2dcea8ede3.png)
1) he removed the tabs inside my repeat
2) he removed the space between 'or' and '(i = 20);' which results in code analysis giving a warning:
![image](https://user-images.githubusercontent.com/24684493/37086225-567916b2-21f7-11e8-9f59-2b121af46645.png)

**Comment by DominikDitoIvosevic** [comment]
This is our bug. Which version of the platform and the AL extensions are you running?

**Comment by Kraver88** [comment]
0.12.16641 sorry forgot to mention

**Comment by thpeder** [comment]
This got fixed in February Update.

**Comment by Kraver88** [comment]
Confirmed. Thank you!
