### ISSUE TITLE
Azure Function URL is  varying while republish function from local to azure.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1755]
Hello,

We have created a new function and published to azure. But while modify the function and republish to azure the function url is varying like this.

Published at first time : 
https://sendd365email.azurewebsites.net/api/EmailAzurecode=qsHM3smTyWq3792PPgs2bvZD19PWAr0LwV3aOZ8nlKIzedHQr1cEMA

Published at second time : 

https://sendd365email.azurewebsites.net/api/EmailAzure?code=UqmXdB40KkNz2mk2ZWa/R2J1sZ8YMUImicyknMLlV3YToXPXtfrd2w

Because of this i was unable to have one standard url hard coded in al extension and send parameters to that.

Can any one please help me to find a way to have fixed url for the azure function.

Thanks

**Comment by atoader** [comment]
Hi @srinivasdes ! This is not related to the AL development environment. Please see https://social.msdn.microsoft.com/Forums/vstudio/en-US/400077e9-ee48-4c04-b2eb-bd0ab803c30d/azure-functions-url-endpoint-changes?forum=AzureFunctions for a discussion on this topic.
