### ISSUE TITLE
Unable to create a new data package.

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1756]
Hello,

We are unable to create a new data package with D365. Is it restricted for now and can we have this feature in future release.

Please suggest me if any alternatives are there

Thanks.

**Comment by JesperSchulz** [comment]
Could you eloborate on what you mean by "new data package"? In case you mean a RapidStart configuration package, then I have good news for you. RapidStart is going to be made available in our upcoming release.
