### ISSUE TITLE
Idea : Integrate RECORDID in FlowField and Link properties

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#1757]
We often create generic functionalities that are using RecordID to link data between records. On the record, fields are added to show the no. of linked records, ... On the pages, factboxes are added to show the linked records (see #1552).  The above is always coded, since there's no native support for the 'RecordID' integration inside the FlowField definition of the SubPageLink property. Adding support for the RECORDID function (or an alternative to it) in various properties would ease this integration.

**Comment by fvet** [comment]
The way BC deals with e.g. the 'attachment' factboxes use the 'SubpageLink', which is nice since it updates without the need for code and it also update when page filters are set that return no records / results. (However, the PK is badly designed since not portable to any kind of records, if the PK differs from the No / Document Type / Line No pattern)
![image](https://user-images.githubusercontent.com/25268332/56565318-64b8e880-65b0-11e9-97fc-85a6d489e0ee.png)

The way we used to deal with the factboxes was by coding the RECORDID. It would be nice though to integrate the RecordID in the 'SubpageLink' property.
![image](https://user-images.githubusercontent.com/25268332/56565303-579bf980-65b0-11e9-96aa-598d77f58046.png)

**Comment by fvet** [comment]
As a reference (Feel free to upvote)
https://experience.dynamics.com/ideas/idea/?ideaid=4bcb9af5-aa6a-e911-b047-0003ff689546

**Comment by atoader** [comment]
I will close this issue. Any future readers should vote on the idea so that it can be considered for a future release.
