### ISSUE TITLE
SubPage List Part Webclient cannot be closed like OnPrem

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/AL#1759]
AL: 0.14.17461
NAV CU2.
You cannot close SubPage Lines parts in the webclient while you can do this in the OnPrem Client. Workaround is putting the subpage part inside another group but then you have to set the caption of the part to empty or you see 2 Captions.
To demonstrate this, see below screenshot:
![image](https://user-images.githubusercontent.com/24684493/37152247-f6b88f2c-22d8-11e8-9199-656c8eac763f.png)
1) This has just the part, if you recreate this you will see that you cannot open or close this part
2) This example was put inside a group so that now we can open and close the part. The downside is that you see 2 captions for this one part..
3) Same as 2 but we forced the caption of the part to be empty. Looks fine at first sight until you see that by doing this the Action on top has also had his caption put to empty.
The code:
![image](https://user-images.githubusercontent.com/24684493/37152465-b217ba86-22d9-11e8-802a-b03dc929cdc5.png)

**Comment by DominikDitoIvosevic** [comment]
Thanks. Since you're on NAV 2018 and this potentially requires deeper investigation please log a support case for your problem: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues
