### ISSUE TITLE
Propertie ApplicationArea

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#176]
Hello,
can you give me an example how to use this propertie (Syntax)? I also Need a description to all valid Areas (#Jobs, #All, #Basic...). What is the meaning of "#Jobs".

**Comment by esbenk** [comment]
The documentation for the ApplicationArea property can be found [here](https://msdn.microsoft.com/en-us/dynamics-nav/applicationarea-property).

Currently the new compiler don't use the # prefix, but we may change this before release. E.g.

`ApplicationArea = All;
`

#Jobs refers to [Jobs module](https://msdn.microsoft.com/en-us/library/hh172378(v=nav.90).aspx) in Dynamics NAV.

**Comment by KaiSwitalla** [comment]
ok. But - which area is the right one for my Extension? What is the meaning of the area "#Suite" for example. In which case this control is shown in the client? Do you have a list - and explanation - for the supported areas?

**Comment by grobyns** [comment]
You should decide whether the scenarios you are including in the extension should be available when the experience tier is set to Basic. If so you can use #Basic. If your scenarios are related to more advanced functionality that is only available in the Suite experience tier then use #Suite. We are continuously adding more features to both experience tiers.

Alternatively, you can define your own application area by adding a Boolean field to Table 9178 "Application Area Setup". Set the value to True to make the controls tagged with this area visible. You should prefix your application area tag with an identifier unique to your ISV like: #MyISVNewApplicationArea (name the field “MyISV New Application Area”). Please also read this whitepaper for more details: https://mbspartner.microsoft.com/secure/whatsnew/NAV2017/EnhancingTheCoreApplicationAndPlatform/WhitePaper_Application_Areas.docx
