### ISSUE TITLE
Create multiple entries API - customerPayments

### ISSUE THREAD

**Issue by TimothyWatkins** [Microsoft/AL#1762]
Looking to send through a batch of customer payments but sending a json array doesn't seem to work. I'm trying the following.

POST
https://dynamicsinstance/api/beta/companies(cbc66cd3-c138-4bfb-81f8-c5142f303a15)/customerPaymentJournals(26ddf21d-f4f1-4357-9111-bbfab86fe049)/customerPayments

For a single payment the following works fine:
```
{
	"customerNumber": "10000",
	"amount": -100,
	"appliesToInvoiceNumber": "103032",
	"description": "API Payment"
}
```
For creating multiple entries I'm trying the following
```
{
    "value": [{
			"customerNumber": "10000",
			"amount": -100,
			"appliesToInvoiceNumber": "103032",
			"description": "API Payment"
		},{
			"customerNumber": "10000",
			"amount": -750,
			"appliesToInvoiceNumber": "103033",
			"description": "API Payment"
		}]
}
```
I receive the following reply from Dynamics
```
"error": {
        "code": "BadRequest",
        "message": "Invalid Request Body"
    }
```

**Comment by atoader** [comment]
Hi @TimothyWatkins ! We are investigating whether this is possible. I will come back with an answer ASAP.

**Comment by atoader** [comment]
@TimothyWatkins it looks like the best way to get help for this issue is to create a support request through Partner Source.
