### ISSUE TITLE
Json AsText does not Unescape double quote character

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#1764]
One short example:

>                 var
>                     JsonObj: JsonObject;
>                     JsonTok: JsonToken;
>                     Data: text;
>                 begin
>                     JsonObj.Add('Test','Version="1.1.0.1"');
>                     JsonObj.SelectToken('Test',JsonTok);
>                     Data:= JsonTok.AsValue.AsText;
>                     Message('%1',Data);
>                end;
> 
> 

If you run this code, the message will give you>
>Version=\\"1.1.0.1\\"

This is not correct for me. I will expect the original value. Charaters like \u003e and \u003c are unescaped correctly.

The "why" for me is, that as part of JSon I am transferring XML data, which I need to parse. I cannot load them because I am getting 

> The following exception was encountered when processing XML data: ''\' is an unexpected token. The expected token is '"' or '''

**Comment by atoader** [comment]
Hi @kine ! What do you mean by original value? How are you transferring the JSON to XML data?

**Comment by kine** [comment]
I think it is irrelevant, the XML example is just example I am working with. The data are incoming from external app through WebService in NAV (codeunit having Text as parameter) and I mentioned it just to illustrate the effect of the escaped double quote in the text when the text is read from JSon. If you look at the function I put to the first message, any text including double quote added into the Json will not be unescaped when read from the JSon. 

Connection between the bug I described and the XML usage I mentioned is just illustrative and may be it is misleading for you. Than just ignore the "Why" paragraph.

**Comment by atoader** [comment]
Ok. I understand now. I will look into it.
