### ISSUE TITLE
[Event-Request] New events "OnBeforePostItemJnlLine" in C80 / C90

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#1767]
Just as the title says. Two new events (one in C80, the other in C90) raised just before an item journal line is posted would come in handy.

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU)

**Comment by hemisphera** [comment]
I've seen that this has already shipped with the April CU batch. The current signature of these events is:

    OnBeforeItemJnlPostLine(ItemJnlLine, SalesLine)

but what I am dearly missing here is the SalesHeader. I really need to know the state of `Ship` and `Invoice` of the header in this event. I suggest modifying the signature like so:

    OnBeforeItemJnlPostLine(ItemJnlLine, SalesHeader, SalesLine)

**Comment by dtacconi** [comment]
@AlexanderYakunin any take on this?

**Comment by hemisphera** [comment]
Done. I've created issue #2051. If this issue here is already closed, please mark it as such.

**Comment by StanislawStempin** [comment]
It is marked correctly. Please read: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#what-do-all-the-labels-assigned-to-issues-mean

We track each issue separately, otherwise the tracking issue in our system would need to have multiple states for each separate comment on the issue.

**Comment by hemisphera** [comment]
Good. I got confused by the fact that some issues are effectively closed while others are not. Thanks for pointing this out.
