### ISSUE TITLE
Exporting NAV Data not supported with installed extensions

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1768]
How can I export the NAV Data from a DB with an extension?

![image](https://user-images.githubusercontent.com/34303738/37273344-c315994a-25d9-11e8-8316-217482e48629.png)

![image](https://user-images.githubusercontent.com/34303738/37273282-95e8078c-25d9-11e8-8755-f71da0de2856.png)

**Comment by HunterFeltman-MSFT** [comment]
Unfortunately, exporting data from the DB with V2 extensions installed has not be supported until very recently. You will see support for this functionality for the Tenerife Release. (NAV 12.0 OnPrem)

**Comment by SirBETE** [comment]
Oh pitty ...
Thank you for the information.
Any possible ideas for a work-around?
Can we export data via sql?
Would the export data work if we uninstalled the extension?

**Comment by HunterFeltman-MSFT** [comment]
I apologize for the massive delay and hope you were able to find workarounds for your issue.

To answer them now, the export of data should work if the extension is uninstalled from the tenant, however, be sure not to include application data in the export. Similarly importing data will also work so long as the same set of extensions on the 'old' services are on the 'new' one and application data is not included in the import.
Additionally, if using cmdlets, you must use the -ServerInstance parameter set and NOT the ones that use the -*Database parameters.

And again, the new 'NAV 12.0 OnPrem' release has support for export/import with V2 extensions installed so I would recommend using that if this is a hard requirement and you are capable of moving.

**Comment by SirBETE** [comment]
Rather have a late answer than no answer :)
Thank you for the solution. I will try it out.

NAV 12.0 OnPrem will become available in November/December? So that's still a long wait ...
