### ISSUE TITLE
How to use $count in oData URL for NAV web service

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#1769]
Hello,

Is there a way to get total number of records returned by NAV odata web service? I tried using oData $count but I get error each time with this parameter in URL. Example with:

/ODataV4/Company('CRONUS%20Canada%2C%20Inc.')/VendorLedgerEntries/**$Count**
/ODataV4/Company('CRONUS%20Canada%2C%20Inc.')/VendorLedgerEntries?**$Count**

Any tips or workarounds are welcome. We would need the total number of record returned by NAV oData service in order to implement correct paging in our third party app.

In NAV 2016 I also get this error, and we would need solution for both 2016 and 2018:
![image](https://user-images.githubusercontent.com/20359384/37277244-75a0fa3c-25e4-11e8-8cb0-d4ce6271766e.png)

**Comment by atoader** [comment]
Hi @ivandjordjevic ! Thank you for your question! Unfortunately, I do not think this is the best place to get an answer to this. This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools. Could you please open a Support Request to CSS through the Partner Source portal? They might be able to help you with this.

**Comment by ivandjordjevic** [comment]
Thanks @atoader for your reply. Based on what I found out so far, $Count is not supported in NAV OData V2, but is supported in NAV OData V4.
