### ISSUE TITLE
txt2al - New field in standard table

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#177]
Do we have to redesign new fields which are added in standard tables to new table extensions after conversion?

**Comment by StanislawStempin** [comment]
Yes, for now the new syntax is only available for extension development. Therefore all modifications to the base application need to be done through extension objects and events.

**Comment by pmohanakrishna** [comment]
Can't it be done via tool itself? if we have any new fields/code etc done in standard objects then the tool should identify and create extension object?

or it just converts txt objects to .al objects?

**Comment by mortenseifert** [comment]
Is this not covered by #173 and #125 ?

**Comment by StanislawStempin** [comment]
That's an interesting suggestion but it's beyond the scope of the tool right now. 
For table fields it might be straightforward to do this but as soon as you have any code modifications you need to switch to a the events programming paradigm. This is not something that a simple automated tool can do for you.

**Comment by pmohanakrishna** [comment]
yes, you are right for OnPrem version of modified objects.
Our solution is on extension which means we only have fields in standard tables and fields. no code in standard objects.
there should be a way for solutions which are on extension already?

**Comment by StanislawStempin** [comment]
Conversion of .delta files will be supported in May Update. Stay tuned.

**Comment by pmohanakrishna** [comment]
ok super. Thank you.
Does it create automatic table and page extensions?

**Comment by StanislawStempin** [comment]
Yes, it does

**Comment by waldo1001** [comment]
There are cases where we don't want to convert deltas.. 
Basically extension objects are able to add code on existing tables or pages.  No need to subscribe to - for example - an action to  a page.  
For example:
I would be able to simply add a function on the item table, and call that function on the Item List from a new action.  Simply by using a table extension and page extension - without having to subscribe to an event.. .

Don't think a conversion tool will take care of this.. .  But admitted - for creating fields, actions, ... it makes sense to convert deltas - just not for code, I guess..

**Comment by StanislawStempin** [comment]
To add a few more details about this - the conversion tool for .delta files will only support modifications that are actually possible to achieve using page and table extension objects. The remaining modifications will be flagged as errors and require a redesign before full conversion can be completed.
