### ISSUE TITLE
Error in translation file when label variables have the same name

### ISSUE THREAD

**Issue by hrolfurh** [Microsoft/AL#1770]
There seems to be a bug in the translation file when variables have the same name, even though they are in different actions. Below is a sample where I have a Label variable in three different actions. 

```
      action("Import Contracts")
      {
        [...]
        trigger OnAction();
        var
          DialogMsg : Label 'Import Contracts';
        begin
          [...]
        end;
      }
      action("Export Contracts")
      {
        [..]
        trigger OnAction();
        var
          DialogMsg : Label 'Export Contracts';
        begin
          [...]
        end;
      }
      action("Download Contract Template")
      {
        [...]
        trigger OnAction();
        var
          DialogMsg : Label 'Download Contracts Template';
        begin
          [...]
        end;
      }
```    

The XLIFF file that generates has three `<trans-unit>` nodes with the same ID. This causes error in translation tools and services and might have some other weird interactions. When I changed the variable names to be different in each action the problem was fixed.

**Comment by DominikDitoIvosevic** [comment]
@hrolfurh thank you for this nasty edge case!
Right now we identify a variable by it's name, it's parent name (this case trigger) and the application object.
Indeed we need to remember the action name as well.

**Comment by gudrunleos** [comment]
Is this solved in build 21229?
