### ISSUE TITLE
IsNull for Native XML types needed

### ISSUE THREAD

**Issue by kine** [microsoft/AL#1771]
Hi, in closed issue #554 is stated, that IsNull is not needed for Native XML Types. I disagree.

Situation:

procedure having parameter of type XmlNode, how can I inside the procedure decide if the XmlNode is empty (not initialized) or not? To keep in line with issue #554 I will need to add another parameter, which will tell me if XmlNode was returned in previous step or not. This is not good...

Interesting is, that in case of JsonValue there is property/method IsNull. 

In C/AL we were able to use IsClear for Automations, IsNull for DotNet and FORMAT(var)='' for native variables. I still see the need for IsNull for native AL types like XmlDocument, XmlNode etc.

**Comment by atoader** [comment]
In the case of JsonValue, IsNull, means that the value represents a JSON null, it does not mean the variable is not initialized.
Thank you for the input! We will take it into account for a future update.

**Comment by JSebastianN** [comment]
In any case, it should be a humble wishto have ISClear/IsNull etc. 
It will help CAL Developers move to AL and do our many upgrades (y)

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
