### ISSUE TITLE
Table 37 function GetLineAmountToHandle : event request Onbefore and Onafter

### ISSUE THREAD

**Issue by RudyJanssens** [Microsoft/AL#1772]
OnBeforeEvent and OnAfterEvent before the EXIT command.

**Comment by AlexanderYakunin** [comment]
Please describe in details

**Comment by RudyJanssens** [comment]
[External] GetLineAmountToHandle(QtyToHandle : Decimal) : Decimal
IF "Line Discount %" = 100 THEN
  EXIT(0);

GetSalesHeader;
LineAmount := ROUND(QtyToHandle * "Unit Price",Currency."Amount Rounding Precision");
LineDiscAmount :=
  ROUND(
    LineAmount * "Line Discount %" / 100,Currency."Amount Rounding Precision");
**OnAfterEvent(LineDiscAmount,Rec)**
EXIT(LineAmount - LineDiscAmount);

**Comment by RudyJanssens** [comment]
.... The issue is updated.


Met vriendelijke groet
Rudy Janssens

[sigpic]

Tel.: +32 9 340 66 76
www.sde.be<http://www.sde.be/> | Lichtelarestraat 45, Lochristi
BTW BE 0422 482 411 | RPR Gent
