### ISSUE TITLE
 D365 and CRM

### ISSUE THREAD

**Issue by MiltonLi51** [Microsoft/AL#1774]
I need integrate D365 and CRM, and created table:
table 50160 CRMAccount
{
    TableType = CRM;
    ExternalName = 'account';
.....

I got below error 
1,[AL] The type or method 'TableType' cannot be used for 'Extension' development.
2, error AL0124: The property 'ExternalAccess' cannot be used in this context

Thanks,

Milton

**Comment by qutreson** [comment]
Hi @MiltonLi51, which version of the AL extension are you using? 

Enabling the table type CRM with target "Extension" came with the February update (0.14.17461). If the version of your AL extension is lower than this one, then this property can only be used with the target "Internal".

**Comment by MiltonLi51** [comment]
Hi Qutreson,

Thanks for your answer. My version is (0.12.15359), I checked MAV 2018 (CU3), it has a version (1.12.17720). Could you tell me where I can download  (0.14.17461)? 

Thanks,

Milton

**Comment by qutreson** [comment]
Hi @MiltonLi51,
The version 0.14.17461 is available when using Sandboxes. When using docker images, the latest AL extension version is currently 0.12.17720, so it is not possible to use CRM tables with target "Extension" on docker yet. If you want this to be backported to NAV 2018 CU3, you need to open a support case for NAV 2018.

**Comment by MiltonLi51** [comment]
Thanks
