### ISSUE TITLE
Max Record Size

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1777]
Quick question.

Earlier there was a limitation to the record size of 8.060 bytes due to limitations in the SQL server.

Does that still apply? 

/Peik

**Comment by atoader** [comment]
Hi @peikba ! The limitation is still there. We have tried to keep the compiler as decoupled as possible from the runtime, so you will not see any errors regarding this. 
At some point in the future, we will create a code analyzer that will warn you if you go beyond the limitations of the runtime.

**Comment by fvet** [comment]
In issue #347 it was stated that companion tables did not count towards the max. record size. So a workaround might be using table extensions...

**Comment by mynavblog** [comment]
Hi @atoader can you confirm that in future there will no limitation for tableextension as it had been stated in issue #347 ?

**Comment by StanislawStempin** [comment]
#347 states that extension tables do not count towards the limit of the base table.
However each table extension is individually still subject to that limit
