### ISSUE TITLE
Startupobjectid does not opens

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#1780]
Hi all,

When I m going to publish the package on local server ,then package successfully published on the server.
But when it redirects me to the **startupobjectid** in browser window then its showing error.(An error has occurred).
Startupobjectid is 22.
I captured some event log errors. But It could not be understandable by me.
Is anyone faced the same problem ever?
Errors caught by event log.
**This license is not compatible with this version of Dynamics NAV**

**Type: System.NullReferenceException
Message: <ii>Object reference not set to an instance of an object.**

**Dynamic operations can only be performed in homogenous AppDomain**

**Fault bucket 1701542955204676060, type 5
Event Name: DynamicsNavServiceException
Response: Not available
Cab Id: 0**

Kind regards
![image](https://user-images.githubusercontent.com/33481576/37330015-b5246220-26c5-11e8-8ca0-b95aeb895dd3.png)

**Comment by atoader** [comment]
Hi @SUD-D365 ! Could you please provide more information about your environment?

**Comment by SUD-D365** [comment]
Hi atoader,
Thanks for your immediate response.

I have created a package in VS code , when I m going to publish it on the local server , it published successfully on the local server.
But when the command going to open the **Startupobjectid** page defined in **launch.json** in browser.
Then I am getting error(An error has occurred).
According to me it should be open page no. 22(Customer list) in browser.
Please let me know what should be the issue or correct me for any mistake done by me.

![image](https://user-images.githubusercontent.com/33481576/37338931-eb295466-26de-11e8-8b0a-889078f46bd6.png)

**Comment by atoader** [comment]
I think the main error is  "This license is not compatible with this version of Dynamics NAV". Could you navigate to the customer page manually? What version of the extension are you using? What version of the server?

**Comment by atoader** [comment]
I see that you are trying to debug. Is the debugger enabled?

**Comment by SUD-D365** [comment]
Yes,
I am able to navigate customer list page(22) manually.
![image](https://user-images.githubusercontent.com/33481576/37341293-e7d2229a-26e6-11e8-9b91-4b6f81937dbe.png)
And the al extension version is below in screenshot.
![image](https://user-images.githubusercontent.com/33481576/37341325-020b3f20-26e7-11e8-8652-a1721a72fd69.png)

And I also enabled debugger.
![image](https://user-images.githubusercontent.com/33481576/37341455-75d6d02c-26e7-11e8-8b30-fb87bb0b3b87.png)

**Comment by atoader** [comment]
That setting doesn't enable the debugger in the server, it is used to debug the AL Language extension. You should remove it from your settings.
To enable the debugger please follow these instructions https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-debugging

**Comment by SUD-D365** [comment]
Yes,
Great, issue is resolved.
Thanks
