### ISSUE TITLE
Unable to publish package with the new VSIX

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#1781]
Hello,

I've encountered an issue with the lastest VSIX update: al-0.14.17461

This is the situation:
I have a 'Core' package currently deployed on the NAV2018 CU3 server, in this package I have the following function (this is also the only function):

![image](https://user-images.githubusercontent.com/6583705/37333012-8031a91e-26a8-11e8-9c13-86b3127c98c8.png)

When I try to call this function from another extension (after I added the dependency and downloaded the symbols) the following error is displayed in the debug console:

The request for path /DynamicsNav110/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Object reference not set to an instance of an object.

When I modify the function in my library so it doesn't take any arguments, deploy this package, download symbols and call this function again. The package is successfully published.

![image](https://user-images.githubusercontent.com/6583705/37333222-0ec5e0d2-26a9-11e8-9bd0-dd27b17ef8b2.png)

I've tried the following situations but none of these worked:
Removing all the downloaded and cached .al packages.
Remove the newly build package before trying to rebuild.
Reinstall Navision 2018 CU 3 (and tested with the first release).

Event viewer doesn't hold any relevant information for this.
When I deployed both packages with an older VSIX (al-0.12.16641) they both successfully deployed.

Visual studio:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I'm not sure how else I can test this, but if you need any other information. Please let me know, I am happy to help.

**Comment by atoader** [comment]
Hi @Joriek ! You should use the extension that came with the CU3. 
Along the way, we had to do a breaking change to enrich the symbol information format. This change means that you cannot use a newer version of the extension with old symbols or with an old server.

**Comment by Joriek** [comment]
Hi @atoader, 
Thank you for the quick and clear response!

**Comment by atoader** [comment]
You're welcome! May I close this issue?

**Comment by Joriek** [comment]
Yes, I have enough information. Thanks
