### ISSUE TITLE
Publishing extension error

### ISSUE THREAD

**Issue by YashinaElena** [Microsoft/AL#1782]
Please, help ! Whats wrong ?
I cant publish extension.
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://DE02-NAVISION02",
            "serverInstance": "nav365",
            "port": 7149,
            "authentication": "Windows",
            "tenant": "default",
            "startupObjectId": 9006          
        }
    ]
}

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="MicrosoftDynamicsNavServer$nav365" /> 
  <EventID Qualifiers="0">216</EventID> 
  <Level>2</Level> 
  <Task>13</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-03-13T08:49:07.593942500Z" /> 
  <EventRecordID>20879</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>de02-navision02</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Server instance: nav365 Tenant ID: <ii>User: Type: System.ObjectDisposedException Message: <ii>Cannot access a disposed object. Object name: 'internalDictionary'.</ii> ObjectName: internalDictionary StackTrace: at Microsoft.Dynamics.Nav.Runtime.DisposedImmutableDictionary`2.get_Values() at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.<AllTenants>d__40.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at Microsoft.Dynamics.Nav.Runtime.WebServiceSetupMonitor.ResetSetup(String tenantId, Int32[] changedTables) at System.EventHandler`1.Invoke(Object sender, TEventArgs e) at Microsoft.Dynamics.Nav.Runtime.NavDatabase.RaiseTypeSpecificTrackingEvent(EventHandler`1 eventHandler, List`1 trackingObjects, ObjectTrackingChangeType changeType) at Microsoft.Dynamics.Nav.Runtime.NavDatabase.HandleTrackingEvent(List`1 trackingObjects) at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.HandleTrackingEvent() at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.TimerHandleTrackingEvent() Source: Microsoft.Dynamics.Nav.Ncl HResult: -2146232798 </ii></Data> 
  </EventData>
  </Event>

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-DynamicsNAV-Server" Guid="{85423FD1-C021-5A63-F214-C4819F8809F3}" /> 
  <EventID>216</EventID> 
  <Version>1</Version> 
  <Level>2</Level> 
  <Task>13</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000f00000000001</Keywords> 
  <TimeCreated SystemTime="2018-03-13T08:49:07.605978100Z" /> 
  <EventRecordID>11596</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="9512" ThreadID="8928" /> 
  <Channel>Microsoft-DynamicsNAV-Server/Admin</Channel> 
  <Computer>de02-navision02</Computer> 
  <Security UserID="S-1-5-21-253446912-1862989423-1837467894-6886" /> 
  </System>
- <EventData>
  <Data Name="serverInstanceName">nav365</Data> 
  <Data Name="tenantId" /> 
  <Data Name="message"><ii>User: Type: System.ObjectDisposedException Message: <ii>Cannot access a disposed object. Object name: 'internalDictionary'.</ii> ObjectName: internalDictionary StackTrace: at Microsoft.Dynamics.Nav.Runtime.DisposedImmutableDictionary`2.get_Values() at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.<AllTenants>d__40.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at Microsoft.Dynamics.Nav.Runtime.WebServiceSetupMonitor.ResetSetup(String tenantId, Int32[] changedTables) at System.EventHandler`1.Invoke(Object sender, TEventArgs e) at Microsoft.Dynamics.Nav.Runtime.NavDatabase.RaiseTypeSpecificTrackingEvent(EventHandler`1 eventHandler, List`1 trackingObjects, ObjectTrackingChangeType changeType) at Microsoft.Dynamics.Nav.Runtime.NavDatabase.HandleTrackingEvent(List`1 trackingObjects) at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.HandleTrackingEvent() at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.TimerHandleTrackingEvent() Source: Microsoft.Dynamics.Nav.Ncl HResult: -2146232798 </ii></Data> 
  </EventData>
  </Event>

**Comment by atoader** [comment]
Hi @YashinaElena ! Could you let us know what version of the AL Language extension you are using? What runtime version are you developing against?

**Comment by YashinaElena** [comment]
AL Extension 01.12.15355

VS Code
 Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

MS Dynamics Nav 11.3.19394


2018-03-13 14:08 GMT+03:00 Alexandru Toader <notifications@github.com>:

**Comment by atoader** [comment]
Hi @YashinaElena ! From the information you have provided, I cannot tell what is the cause of the error. Do you have a code sample that reproduces the error? Does it fail in the same way when publishing to a different server?

**Comment by YashinaElena** [comment]
I created a new server with multitenancy
"version": "0.2.0",
"configurations": [
{
"type": "al",
"request": "launch",
"name": "Your own server",
"server": "http://localhost",
"serverInstance": "test",
"port": 7249,
"authentication": "Windows",
"tenant": "test",
"startupObjectId": 9006
}

and after F5 on VS Code this error
Server instance: test Tenant ID: <ii>User: CORP\omegaplus Type:
Microsoft.Dynamics.Nav.Types.Exceptions.NavTenantNotFoundException
SuppressMessage: False DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False FatalityScope: None Message: <ii>A
tenant was not specified, but is needed because the system has multiple
tenants. Contact your system administrator.</ii> StackTrace: at
Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.get_DefaultTenant() at
Microsoft.Dynamics.Nav.Service.ServiceAuthenticationHelper.AuthenticateForServiceCallCore(Func`1
getNavTenant, Func`1 getRequestProperties, Func`1 getWindowsIdentity,
Func`3 createException) Source: Microsoft.Dynamics.Nav.Ncl HResult:
-2146233088 </ii>


2018-03-14 9:43 GMT+03:00 Alexandru Toader <notifications@github.com>:

**Comment by kalberes** [comment]
There was an issue like this back then and was fixed and backported to NAV 2018 I guess CU2.
see #1402

**Comment by YashinaElena** [comment]
All thanks for the help !
NAV2018 CU2 really helped.

2018-03-21 13:11 GMT+03:00 Kálmán Béres <notifications@github.com>:
