### ISSUE TITLE
Internal Target option in app.json

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1788]
Hi,

We have added Test.app as dependency in app.json and are accessing the respective methods where we are getting error saying this method cannot be used in extension development.

When i used internal as target in app.json it worked.

But if i use internal it will not work in D365, so please look into this and make it possible to get those functions available, for example "CreateVendor" function in codeunit 130512

Thanks & Regards
Varun Reddy

**Comment by atoader** [comment]
Hi @bachii1010 ! From what I can understand you want a set of functions to be exposed to extension development. Please give us a list of the format and I will forward it:

| Object        | Method           | (Optional) Reason  |
| ------------- |:-------------:| -----:|
| Codeunit 130512      | CreateVendor | - |
| | OtherMethodFromSameCodeunit | - |

**Comment by bachii1010** [comment]
Hi

Below is the list:


Object | Method
-- | --
Codeunit 130512 | CreateVendor
  | CreateVendorNo
Codeunit 132202 | CreateProductionBOMHeader
  | CreateProductionBOMLine
  | CreateRoutingHeader
  | CreateWorkCenter
  | CreateRoutingLineSetup
Codeunit 132201 | CreateItem
  | CreateItemManufacturing
  | SelectItemJournalTemplateName
  | SelectItemJournalBatchName
  | CreateItemJournalLine
  | PostItemJournalLine

Please check

Thanks & regards
Varun Reddy

**Comment by atoader** [comment]
Thanks! I have forwarded the request.

**Comment by JesperSchulz** [comment]
The entire test tool was made "external" back in December, meaning that it already is available for D365 in the latest previews. Remember that we don't automatically backport changes made to already released versions, such as NAV2018. I hope that addresses your request. If not, please reopen this issue. Thanks again for reporting! Much appreciated!
