### ISSUE TITLE
increment and decrement operator

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#1789]
It would be nice if incremental operators were possible.

````csharp
a++ //postfix increment
++a //prefix increment
a-- //postfix decrement
--a //prefix decrement
````

**Comment by atoader** [comment]
Hi @Gallimathias ! Thank you for your suggestion! IMO, this does not improve readability, but if the community decides this is worth it, we will certaintly consider it.

**Comment by vytjak** [comment]
I would be for adding these, but _only postfix_ versions.

**Comment by Gallimathias** [comment]
@vytjak the prefix operators are not to be underestimated, e. g. in loops very practical. 

@atoader Thanks for the quick answer, we'll see what others have to say. ^^

**Comment by atoader** [comment]
Are these scenarios where:
```
a +=1;
a -=1;
```
is not sufficient?

**Comment by atoader** [comment]
My problem with these operators is that not a lot of people know what happens exactly when:
++x is executed versus x++

**Comment by Gallimathias** [comment]
Actually, this type of operator developer should be basic knowledge. In germany, this is the first week in the first year of apprenticeship for developers.

the assignment operators are difficult to grind or use in literals.

````
do 

until GetMath(x++)

Message := "This Message use the next value: " + FORMAT(++x) + "!";

Message := "After this Message increment x, current value: " + FORMAT(x++) + "!";

or easyer for

for i := 0 to count with i++
for i := 10 to 0 with i--

var a := 12 + Sqrt(value) + x++;
var b := 15 + GetECM() + --b;

var d := GetNewValue(a++, c--);
````

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
