### ISSUE TITLE
MenuSuite in AL

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#179]
Does the conversion tool/AL do anything with MenuSuites already? Or am I doing something wrong?

**Comment by esbenk** [comment]
The is no support for MenuSuites in this version.

**Comment by mortenseifert** [comment]
But this will come, correct? If we are to add functionality by extensions that this must be part of the environment.

**Comment by StanislawStempin** [comment]
Yes, this will be available at some point but not necessarily in the exact same shape. The current suggested approach is to add new actions to the navigation page part as well as any relevant application pages that should lead the user to the new functionality added by the extension.
