### ISSUE TITLE
Bitwise Flag Options

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#1790]
It would be useful if there were options that could be used as bitwise flags.

````CSharp
optionA = 1 = 0000 0001
optionB = 2 = 0000 0010
optionC = 4 = 0000 0100

3 = optionB and OptionC = 0000 0011
5 = optionA and OptionC = 0000 0101
6 = optionB and optionC =  0000 0110
7 = optionA and optionB and optionC = 0000 0111

optionD = 8 = 0000 1000

and so on......
````

**Comment by yrest** [comment]
Curiously, what would you use those for?

**Comment by vytjak** [comment]
Before we have that, we would need a proper bitwise OR operator in AL.
Wouldn't it be nice, if we could write:
`SalesHeader.PostAction := SalesHeader.PostAction::Ship | SalesHeader.PostAction::Post`

**Comment by Gallimathias** [comment]
@yrest I'm building such flags mostly with byte. Doing this manually in code units or manipulating the database or objects is annoying. I use them quite often (as in C# or c++). For example, for Id's that have different meanings or to mark something with flags. It is also interesting for queries because you can compare bitwise.

@vytjak has the perfect example ^^

**Comment by yrest** [comment]
It would probably make sense to add support for other bit operations, not only OR, at the same time.

**Comment by Gallimathias** [comment]
@yrest I also see it this way: OR, XOR, AND, NOR plus negation and of course bitshifting would be nice << and >> for left and right shift.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
