### ISSUE TITLE
[Event request] - Notifications - Rep1320 OnAfterSetReportFieldPlaceholders / Tab1511

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#1791]
We've started using the 'Notification Entry' framework of NAV to inform users about  (error related) events. However, there are various places missing event publishers if you're using own tables / recordrefs.

For example, in Report 1320, no custom fields can be added to the report dataset / notification e-mail.
Please provide 'OnAfterSetReportFieldPlaceholders'

PS: Having extra types (besides 'New Record', ...) in Notification Entry and support in all processes to extend on these new types might even allow better use of the current notification frame.

**Comment by AlexanderYakunin** [comment]
Thanks for suggestion. Which new types do you have in mind? Something line UpdatedRecord, DeletedRecord? Or something else?

**Comment by fvet** [comment]
@AlexanderYakunin As far as the 'types' concern, I'm more looking into a way to distinguish the 'new record' notifications based on their origin / source table. Where notifications related to the creation of new customers, items, ... might be ok to show up in the rolecenter as notifications, others might have a higher priority where e-mail delivery might be a better alternative. (Example: when an 'Errror Log' record, job queue log record, ... is created, those should be mailed instead). Not sure if an extra type would solve this issue. Currently the 'new record' type has one fixed delivery type (based on the user preferences) for all kinds of records.

Having an extra identifier (similar to the 'My Notifications' identifiers?) to define the delivery type could provide support for more scenarios.
