### ISSUE TITLE
Creating an RDL layout report in NAV 2018

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1795]
Is it correct that the procedure described in 

https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-howto-rdl-report-layout

Does not work with NAV 2018?

I run AL Language 0.12.17720

/Peik

**Comment by DominikDitoIvosevic** [comment]
Hi @peikba . As you can see by the note on the top of the page, this feature is not available for Nav 2018, only for cloud releases and developer previews.
