### ISSUE TITLE
How do I add text to existing wizard step?

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#180]
I'm trying to recreate a very easy modification we made to the Data Migration Wizard page, where we added a small piece of text to one of the steps. See [here](https://navbitsbytes.files.wordpress.com/2017/05/migrationwizardtext.png) for example.

For the life of me I cannot figure out how to recreate this with a page extension. Any help?

**Comment by esbenk** [comment]
Try the following

```
pageextension 70404040 DataMigrationExt extends "Data Migration Wizard"
{
    layout
    {
        addafter(Description)
        {
            group(MyInstructions)
            {
                CaptionML = ENU=''; 
                InstructionalTextML = ENU='Note: To import data into a BuildFood extension...';
            }
        }
    }
}
```

The CaptionML must be set to empty to avoid a caption on the group. This may change to the simpler ShowCaption = false in the future.

**Comment by NavBitsAndBytes** [comment]
Thanks, so simple when you see the solution, but just couldn't get my head thinking about it that way. :)
