### ISSUE TITLE
Can procedure:GetSelectionFilter made global in codeunit46:SelectionFilterManagement 

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#1809]
based on: NAV2018CU3
Can procedure:GetSelectionFilter made global in codeunit46:SelectionFilterManagement?

so we can use this for example for other entities like Employee or Responsibility Center.
GetSelectionFilterForResponsibilityCenter
GetSelectionFilterForEmployee

etc

**Comment by JesperSchulz** [comment]
Thanks for your suggestion! GetSelectionFilter has already been made external in Business Central in the January update (refer to https://github.com/Microsoft/AL/issues/947). Please note, that we cannot backport issues to already released versions (e.g. NAV2018) based on issues created in this forum (https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018). If you would like to request the fix to be backported, please create a hotfix request.

**Comment by Pieterheinevdm** [comment]
backport isn`t necessary (workaround is copy this function), but when do we get this change in the on-premise version?

**Comment by JesperSchulz** [comment]
The change will ship with the next on-premise release, which according to the roadmap (https://community.dynamics.com/nav/b/dynamicsnavessentials/archive/2018/03/17/dynamics-365-business-central-roadmap) will ship in the fall this year.

**Comment by Pieterheinevdm** [comment]
ok
