### ISSUE TITLE
Product Walkthrough / Tour

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1811]
Are there any plans to provide the ability for us to create product walkthroughs or tours for users for our apps? There are a lot of different tools out there that could be used with Business Central, but I wanted to see, if there is anything that is planned around this scenario and part of the customer experience.

**Comment by FHietala** [comment]
Hi, we're looking into how our partners can extend and build product tours , like the tours we had in Dynamics 365 for Finance & Operations, Business edition. However it's not possible to do this in Dynamics 365 Business Central today.
