### ISSUE TITLE
Publishing External CRM table gives an error

### ISSUE THREAD

**Issue by FrankAuwers** [Microsoft/AL#1813]
error AL0124: The property 'ExternalName' cannot be used in this context
error AL0124: The property 'ExternalType' cannot be used in this context
error AL0124: The property 'ExternalAccess' cannot be used in this context

[T 50000 CRM Recurring Contract.zip](https://github.com/Microsoft/AL/files/1825783/T.50000.CRM.Recurring.Contract.zip)

**Comment by qutreson** [comment]
Hi @FrankAuwers, which version of the AL extension are you using? If the version of your AL extension is lower than 0.14.17461, then this property can only be used with the target "Internal" (See #1774).

**Comment by FrankAuwers** [comment]
I use version 0.15.18046

**Comment by qutreson** [comment]
The version 0.15.18046 should support using CRM related properties. Are you getting these errors in VS Code or when trying to publish to the server?

**Comment by FrankAuwers** [comment]
When I publish the code to the server.

**Comment by qutreson** [comment]
Which version of the server are you using?

**Comment by FrankAuwers** [comment]
Server version is: 11.0.20348

**Comment by qutreson** [comment]
From what I see, your server relies on an older version of the AL compiler (0.12.16641). This is why it reports an error when you are trying to publish (as extensions are re-compiled in the server before publishing). You have now an AL extension that is not in sync with your server, while the AL extension you use should always be matching the server

**Comment by StanislawStempin** [comment]
In other words you need to be using Business Central for this to work.
