### ISSUE TITLE
ApplicationArea Codeunits missing

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#1817]
Hello,

I am developing an extension and assigning my own ApplicationArea to controls. I am following this documentation:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-extending-application-areas

1. I have added a boolean field in the "Application Area Setup" table
2. I have created an Install codeunit (COD50101 in the documentation)
3. I have created a codeunit to enable my ApplicationAres (COD50100 in the documentation)

In the documentation COD50100 uses to following objects:
- ExperienceTierSetup: Record "Experience Tier Setup";
- ApplicationAreaMgmtFacade: Codeunit "Application Area Mgmt. Facade";
- Codeunit::"Application Area Mgmt."

I haven't been able to use those objects because they do not exist in the base application
- I have tried using symbols from the Sandox
- I have tried using symbols from NAV2018 CU3

Can you tell us where those objects can be found?

Salut!
Laura Nicolàs

**Comment by qutreson** [comment]
Hi @LauraNicolas, 
Extending application area is still under active development (we added a note in our [docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-application-areas)) and the code example shown might be changing. 

When using the current docker images, the codeunits needed are missing from the symbols and you need then to wait for an updated version. 

However, they should be available when using sandboxes. Which version of the application symbols do you have when downloading from the sandbox?

**Comment by LauraNicolas** [comment]
Thanks @qutreson ,

I downloaded the symbols again, but the objects are still missing.
![image](https://user-images.githubusercontent.com/32334451/37838797-1d94f626-2eb9-11e8-8447-33abf09a9145.png)

I will keep on checking the docs to be aware of the changes. Thanks.

Salut!
Laura Nicolàs
