### ISSUE TITLE
When debugging "webclient" missing from url so page does not open

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1819]
This is in NAV2018 RTM on-premise

When debugging (F5) my extension the URL produced does not work 
`http://localhost:8088/dynamicsnav110/?page=51100&debuggingcontext=f97983c8-e4cf-44f5-91bd-ff2192b867c7&sk=f97983c8-e4cf-44f5-91bd-ff2192b867c7`
so the browser says:
> Sorry, that didn't work
> 
> An error has occurred
> Restart
> 
This happens with the HelloWorld sample app as well.

Interestingly if I run the app without debugging (Ctrl+F5) then the URL is works.
`http://localhost:8088/dynamicsnav110/?bookmark=11%3bYgAAAAJ7&page=51100&company=CRONUS%20UK%20Ltd.&dc=0`
Other information:
Web Client Base URL: http://localhost:8088/DynamicsNAV110/WebClient
Launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "serverInstance": "DynamicsNAV110",
            "authentication": "Windows",
            "startupObjectId": 51100
        }
    ]
}

Any suggestions?
```

**Comment by kalberes** [comment]
Is <NetFx40_LegacySecurityPolicy enabled="false" /> in the *Nav.server.exe.config file?

**Comment by GreatScott000** [comment]
@kalberes, thanks

No it wasn't and, after setting it to false, now it works.  

The documentation seems a little vague on this setting to me.  I wasn't trying to debug anything (or intending to use the debugging features), so basically this is a required setting.

**Comment by kalberes** [comment]
Yes, it is required if you want to debug. F5 creates a debugging session with the server and that needs dynamic  operations to be performed. The CAS security  policy enforcement setting would not allow that.
If you just want to publish Ctrl F5 can do that and the setting can be as defaulted.
