### ISSUE TITLE
How to get base URI host value?

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#182]
Any idea how can I replace the DotNet usage in the following code?

```
  LOCAL PROCEDURE GetTenantId() : Text;
  var
    Url : Text;
    Uri : DotNet "'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Uri";
  begin
    Url := GETURL(CLIENTTYPE::Web);
    Uri := Uri.Uri(Url);
    EXIT(Uri.Host);
  end;
```

**Comment by esbenk** [comment]
Unfortunately, the only option currently is to write your own Uri parser. 

We are looking at the Uri class functionality as  something we eventually will add to the AL language in the future. We don't have any timeline at this point.
