### ISSUE TITLE
Duplicate lines in Problem pane

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1820]
This is for NAV 2018 RTM on premise.
Why for every "problem" in my code are there 2 entries in the Problem pane of VS Code?

![image](https://user-images.githubusercontent.com/4333956/37652572-dee64830-2c33-11e8-8cf9-051c86929251.png)

It is very annoying.

**Comment by qutreson** [comment]
Hi @GreatScott000, which version of the extension are you using? Is it possible that you have two versions of the extension currently installed in VS Code?

**Comment by GreatScott000** [comment]
It is possible.  Is there a way to tell?
I had some problems installing the VSIX and I may have run one from the wrong build.

**Comment by qutreson** [comment]
When using VS Code, you can see which extensions are installed by clicking on the 'Extensions' icon (the one highlighted in the image below):
![image](https://user-images.githubusercontent.com/31541422/37658693-6879867e-2c4e-11e8-8229-b628e0cbc4dd.png)

**Comment by GreatScott000** [comment]
That was it, thank you.
