### ISSUE TITLE
GlobalVarAccess: OnBeforeDoSending in codeunit 9520 "Mail Management"

### ISSUE THREAD

**Issue by wdet** [Microsoft/AL#1821]
Is it possible to enable the property GlobalVarAccess on the event OnBeforeDoSending in codeunit 9520 "Mail Management"?

**Comment by AlexanderYakunin** [comment]
Before going for this change I need to understand which global variables may be needed here. If you need TempEmailItem, we can simply add it to event. Does it work for you?

**Comment by wdet** [comment]
Hi Alexander,

No, that won't be sufficient.
I would need to have access to the following globals:
- TempEmailItem (VAR)
- OutlookSupported (VAR)
- SMTPSupported (VAR)
- DoEdit (VAR)
- HideMailDialog (VAR)

I was thinking about this approach, because we have done a lot of customizations to the mail dialog.
So I tried to show our own dialog instead of the standard one with this event, but for sending the mail I still use the standard logic.
