### ISSUE TITLE
Question - API / Webservice logging options

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#1823]
What would be the best option to have some (native) logging on API / Webservice (incoming) calls?
We often create a custom logging framework inside NAV to log the received WS calls. For codeunits exposed as webservices, this is fine, since database transactions are allowed inside the functions.

For pages exposed as webservices, we struggled finding the right triggers, since in the OnOpenPageEvent, the filters can not yet be read, so we miss the context of the WS call. Since not all page triggers support database triggers to create a log record, we created some workaround via the OnFindRecord / OnNextRecord (since these triggers know about the Filter / parameter context) to write a log into a SQL table (instead of passing via a NAV record), which would not be supported with extensions. I guess the same constraints would apply for API pages as well?

Using STARTSESSION might be not the best option for performance, using SENDTRACETAG does only provide limited information, using an central Azure function might cause overhead, ... Can we find a solution inside NAV to know which API calls have been received?

**Comment by StanislawStempin** [comment]
I reached out to the owning team and I will update this thread once I hear back.
