### ISSUE TITLE
[Question] File Handling

### ISSUE THREAD

**Issue by ln1000000** [Microsoft/AL#1825]
Hello,
Currently, file handling appears to be disabled in the recent version of the VSIX (0.15.18566).
File.Open and File.Import are deprecated.
![image](https://user-images.githubusercontent.com/29798357/37675612-0c61fad0-2c4c-11e8-8c4c-c5fad2205e9c.png)

Is this, or similar functionality returning to AL?

Related:
My issue is: I'm attempting to populate a list from code on install, and the list contains a picture field I'm trying to import.

**Comment by MikeGlue** [comment]
There is new stream capability for importing files, and more specifically for your scenario, pictures.
https://navbitsbytes.wordpress.com/2017/12/08/al-extensions-importing-and-exporting-media-sets/

**Comment by ln1000000** [comment]
This only mentions the manual process of picture import.
I'm trying to import pictures when I create and insert a series of import records.
I.e. Data migration from X system with 2500 customer pictures, I would love to have a way to automatically import and apply those photos without the manual import, one by one.
