### ISSUE TITLE
Support Code Coverage for AL

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/AL#1827]
Hi,

we have a below sample code in our Extension to get the list of functions in a object using codecoverage.
If we give the standard object id for example codeunit 1 it is showing the fucnctions but when we give an object id in our extension then it is not showing the functions.  see below:

![image](https://user-images.githubusercontent.com/29703512/37702085-6a98257c-2d17-11e8-8933-f693f7fac3e9.png)

Please suggest

Thanks & Regards
Srinivas

**Comment by srinivasGangadhara** [comment]
Hi,

if the enhancement is done,
Please share us how we can handle this?

thanks!

Regards
Srinivas

**Comment by srinivasGangadhara** [comment]
Hi @qutreson  this is urgent for our product, Please provide alternate solution.

thanks!
srinivas

**Comment by gregoral** [comment]
Are there any updates for this issue?
90% CodeCoverage is a requirement for app submission.
I have also opened a new issue #3775 related to code coverage.

**Comment by tejabalusu** [comment]
do we have any update on above issue?

**Comment by krishnaGottuparthi** [comment]
Hi,do we have any update on above issue.We still see that it is not present in BC17

**Comment by krishnaGottuparthi** [comment]
We can see the code coverage in BC18.
