### ISSUE TITLE
Docker issue related to out dated image

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#1828]
Since yesterday I'm facing weird issues related to docker connectivity, Also found the root cause as we were pointing to old docker image. 
* **Error** : You are trying to run a   container which is more than 90 days old.   Microsoft recommends that   you always run the latest version of our containers.   Set the environment variable   ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.

After same we have installed new container with setting below value. Everything is running now on docker side. 
* **Command** : docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e licensefile= _link_ --memory 3G --restart unless-stopped microsoft/dynamics-nav:devpreview-finus

Let’s know if we are pointing to wrong image for development activity.

Furthermore, As we have created a new container, which is as per above screen, after downloading symbol in VS code, we are facing below **issue** while compiling solution. 

* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004821 AVA Validate Call.al(514,90): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004821 AVA Validate Call.al(663,68): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\codeunit 70004822 AvaSalesExtendCU80.al(4,150): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\codeunit 70004822 AvaSalesExtendCU80.al(3,48): error AL0280: The event 'OnBeforeCalculateSalesTax' is not found in the target
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\codeunit 70004822 AvaSalesExtendCU80.al(23,48): error AL0280: The event 'OnBeforePostUpdateOrderLine' is not found in the target
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\codeunit 70004822 AvaSalesExtendCU80.al(40,48): error AL0280: The event 'OnFinalizeInvoicePostingSalesTax' is not found in the target
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(39,40): error AL0185: Page '10038' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(40,154): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(40,211): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(40,268): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(40,325): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(56,40): error AL0185: Page '10041' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(57,114): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(57,171): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(66,40): error AL0185: Page '10042' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(67,96): error AL0185: Table 'Sales Tax Amount Line' is missing
* c:\Users\sachin.chavan\Documents\AL\AvalaraExtension2.0_POC\Module Extension\Codeunit\Codeunit 70004850 SalesOrderActions.al(67,153): error AL0185: Table 'Sales Tax Amount Line' is missing
* Error: The package could not be created.

**Comment by fvet** [comment]
You might have a look at
https://github.com/Microsoft/nav-docker/issues/171

**Comment by chavansachin20** [comment]
restarted my docker and re-created my container with command -e ACCEPT_OUTDATED=Y 
this resolved my issue.
