### ISSUE TITLE
Events in table:295:"Reminder Header

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#1829]
regarding table:295:"Reminder Header"
is it posible to at the events below to the reminderheader table? So we can change/add the (text)reminder lines behavior?

OnBeforeInsertLines + OnAfterInsertLines
OnBeforeUpdateLines + OnAfterUpdateLines

or/and:
OnBeforeInsertLines + OnAfterInsertLines
OnBeforeInsertBeginTexts + OnAfterInsertBeginTexts
OnBeforeInsertEndTexts + OnAfterInsertEndTexts

**Comment by AlexanderYakunin** [comment]
This is possible if you will be more specific and describe events with parameters and their placement in existing code. Please provide this info.

**Comment by Pieterheinevdm** [comment]
[TAB295.DELTA.txt](https://github.com/Microsoft/AL/files/1871061/TAB295.DELTA.txt)

sorry for the late response, I have a nav delta file attached, this describes the new publisher functions and when they should be called/triggered. Or do you prefer a MS Word document?

**Comment by AlexanderYakunin** [comment]
Delta file is sufficient, work in progress
