### ISSUE TITLE
[Event-Request] REP5685 Copy Fixed Asset

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1830]
Can we have an OnOpenPageEvent on the requestpage with as parameters the requestpage variables so we can modify them?
```
OnOpenPage()
IF NumberofCopies < 1 THEN
  NumberofCopies := 1;
FANo := FANo2;
OnOpenPageEvent(FANo, NumberofCopies, FirstFANo, UseFANoSeries); //<<<<
```

**Comment by dtacconi** [comment]
Thanks to SirBete to file this request through Partner Source / CSS. This is now resolved and will be included in the application base with NAV 2018 CU 5 (May 2018 CU). No Event added but exposed as external InitializeRequest function.
