### ISSUE TITLE
CreateDim Function in Table 5900 (Service Header)

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1831]
Hi,

Can you please make the function CreatDim **_Global_** now it is local see below:

![image](https://user-images.githubusercontent.com/26792519/37711358-75c306aa-2d36-11e8-916a-9886848344be.png)

We need this function in our app as it is local we cannot access it.
Please let us know?

Thanks & Regards
Varun Reddy

**Comment by JesperSchulz** [comment]
I will make this one and other CreateDim functions public and global. Thanks for the suggestion.
