### ISSUE TITLE
Personalization

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1833]
in one of our page, we are not able to add fields.
do they have to be added in page (visible false) to use personalization or can we directly add fields from table without adding them to page?

or do we have to setup any properties to add fields?

**Comment by qutreson** [comment]
Hi @pmohanakrishna, the personalization only enables to act on existing page controls. If you add some new fields in a table, you also need to add them to the page in order to use them in personalization.

**Comment by pmohanakrishna** [comment]
can we stop showing those table fields in right side list? it is so confusing that fields are ready in right side pane and not able to drag them to page (which are not added in page in designer?)

**Comment by StanislawStempin** [comment]
Which version are you using and on which environment does this happen (Docker, Cloud Sandbox, On-Prem deployment)?  We cannot reproduce this behavior on Business Central

**Comment by pmohanakrishna** [comment]
Docker
build 20901

but as mentioned above those fields are not available in page level and only available in table level.
are we still showing them in personalization which we cannot add?

**Comment by atoader** [comment]
Hi @pmohanakrishna ! As far as I can see, we are not showing fields that are not already part of the page object. What we are doing wrong is that we show the page fields with the name of the table fields. If you believe this is not the issue, could you please provide a repro?
