### ISSUE TITLE
Option string doesn't containg value set error in al (but works in c\al)

### ISSUE THREAD

**Issue by GedasB** [Microsoft/AL#1834]
Extention 0.14.17461

Table has field type option with option string: 
Company,Customer,Vendor,Location,Shipping Agent,Service

in c\al code is like
CustomizedCalendarChange2.SETRANGE("Source Type", "Source Type"::"16"); 
and after findset it does:
CustomizedCalendarChange2."Source Type" := CustomizedCalendarChange2."Source Type"::"16";
even option "16" doesn't exist at all.
Everything is OK.

But al the same code shows error:
'"Source Type"' does not contain a definition for '16'

if i change filter to:
CustomizedCalendarChange2.SETRANGE("Source Type", 16);
then al compiles, but assigment like:
CustomizedCalendarChange2."Source Type" := 16; 
shows error:
Constant value '16' is outside of the valid ordinal range for this option type

**Comment by kalberes** [comment]
yes, this is by design. Option values are checked when assigned. 
You could argue that we could have checked the same in the SetRange and even in the SetFilter to validate the filter expression, but we have chosen to let these as runtime evaluations. 
That said, we may add these validations, they make sense.  We will discuss it.

**Comment by GedasB** [comment]
Hi
Actually me and my colleagues (developing NAV 20 years) disagree.
Business case: we are publishing add-on and trying do not modify any standard NAV table, but of course use it. In this case this is Table 780. We are creating new record but use option value 15 or 16. These records never mix with standard record as standard uses it own options values. We don't change option string in field description but making direct assigment:
CustomizedCalendarChange2."Source Type" := 16;
Option field really is integer, so this always works, except V2.
What workaround now we have:
1. Don't use this table anymore and use copy. Then next step is to add to our add-on copy of all standard NAV, because we need some of tables and functions.
2. Increase option string in field. Usually trying avoid any conflict with other add-on or new coming functionality we do: _Company,Customer,Vendor,Location,Shipping Agent,Service,,,,,,,,,MyValue1,MyValue2_. We adding commas because if there comes new option in standard it could destroy our values...

Do we have other solutions?

/Gedas

**Comment by kalberes** [comment]
We have a slice on extendable enums. That would possibly solve your problem. 
Yes, it has been ages ago, but my first project around was developing Hotcopy on the proprietary database :).

**Comment by kalberes** [comment]
But we could ease your pain by removing this check until we have that slice ready.

**Comment by GedasB** [comment]
Yep. It is good idea to remove check before new "slice" will come on stage.
I would say i need it only for assignment like:
Type := 16;
And we could leave check for 
Type := Type::"16";

And of course leave as it is now in filters:
Setfilter(Type, 16);
must to work.

Thanks
