### ISSUE TITLE
Blocked Functions Codeunit "Document-Print"

### ISSUE THREAD

**Issue by Abraxas82** [Microsoft/AL#1835]
Hi there,
just tried to use the "EmailSalesHeader" Function an got the Error "error AL0296: The type or method 'EmailSalesHeader' cannot be used for 'Extension' development."

I found this in your FAQ:
"The type or method 'XYZ' cannot be used for 'Extension' development.
We have blocked off a certain set of functions from being directly called from Extension code. The approach was based on a conservative static analysis resulting in some functions being blocked unnecessarily. If you require to use one or more of these functions please log an issue and provide a full list. We will analyze the request and unblock functions deemed safe."

So.. what about getting those functions rdy to use in extensions?
I just cant see how this function would get informations form other tennants.

**Comment by DuttaSoumya** [comment]
Hi @Abraxas82: as of now, we do not allow extensions to send emails. You could however use an alternative mailer service to send emails within the extension.
