### ISSUE TITLE
Codeunit 7000 Sales Price Calc. Mgt.: set functions as GLOBAL : 

### ISSUE THREAD

**Issue by shalu712** [Microsoft/AL#1839]
Hi All, this request is made by someone already, I need in NAV 2018 CU3 NA .
Manually I tried to expose the function but still not able to use from AL.
Functions are 
Codeunit 7000 - Function CalcBestUnitPrice - set as External
Codeunit 7000 - Function CalcBestLineDisc- set as External

Please let us know when you guys planning to release  ?

**Comment by StanislawStempin** [comment]
Please see https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

You can still mark them External yourself and then follow the steps described under Hybrid Develpment: https://github.com/Microsoft/AL/wiki/Useful-resources
