### ISSUE TITLE
Delete unpublished extensions from SQL

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1840]
Is there a possibility to completely delete unpublished extensions from the database?
Example: I installed 3 different test-extensions, each adding a field to the "Purchases & Payables Setup".
When I uninstall and unpublish all 3, the fields aren't included anymore in NAV (obvious).
However when I look in SQL, the tableextensions still exist.
![image](https://user-images.githubusercontent.com/34303738/37778718-ebc7d920-2dea-11e8-8778-13a6b0e9d3a2.png)
Shouldn't these be deleted when I unpublish the extension?

**Comment by HunterFeltman-MSFT** [comment]
See this 'similar' issue #1198  where I talk about the sync state of the database
Also this reading about the [Sync-NavApp cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=dynamicsnav-ps-2018). Specifically, the section about the 'Clean' mode.

**Comment by SirBETE** [comment]
Exactly the answer I was looking for! Thank you!
