### ISSUE TITLE
When will the documentation have examples of the object/type properties?

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1842]
Trying to write a table from scratch, I need a TableRelation property.  Look up the documentation at:
https://docs.microsoft.com/en-us/dynamics-nav/developer/properties/devenv-tablerelation-property

Describes what it is for, thank you but I have been doing NAV for 17 years so I already know.  What I need to know is the syntax for a dependent TableRelation (e.g. No. in Sales Line dependent on Type) in AL.  I shouldn't have hunt examples in GitHub or convert tables that have what I am looking for into AL just to find it.

Same thing with most of the documentation especially the new types (JSON, HTTPCLIENT, etc.).

When will the documentation be useful?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We're continuously working on improving the docs, and we know that code samples are missing in particular in the reference docs. This is on our backlog for a refresh of the docs. Thanks!
