### ISSUE TITLE
al.codeAnalyzers

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1845]
I noticed the new settings for code analysis:
![image](https://user-images.githubusercontent.com/12088142/37825580-a6830fd2-2e90-11e8-99ef-0f2d1741b727.png)

However, when I enable them, like the screenshot, it doesn't do anything.. .  I can't enable it like I used to (enableCodeAnalysis setting), so at this point, no code analysis?

**Comment by qutreson** [comment]
Is `"al.enableCodeAnalysis" : true` ? You need both settings for this to work. `enableCodeAnalysis` will enable analyzers, `al.codeAnalyzers` is used for choosing which ones to enable. You should not have all three of them at the same time because that might give you conflicting diagnostics.

**Comment by waldo1001** [comment]
Sorry, I didn't see that one ... you are right.  It works now!

**Comment by waldo1001** [comment]
Is there a (short) explanation for all three?

**Comment by qutreson** [comment]
We have some documentation on them in [Using the Code Analysis Tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)

**Comment by waldo1001** [comment]
I missed that as well .. 
Thanks!
I'll stop asking stupid questions now ;-)

**Comment by epernst** [comment]
Remember, there are no stupid questions. And I have a follow-up. What is the detailed difference between the three options:
 - CodeCop is an analyzer that enforces the official AL Coding Guidelines.
 -  PerTenantExtensionCop is an analyzer that enforces rules that must be respected by extensions meant to be installed for individual tenants.
 -  AppSourceCop is an analyzer that enforces rules that must be respected by extensions meant to be published to Microsoft AppSource.
Is there a list of which ruleset's are in each analyzer?

**Comment by waldo1001** [comment]
I have indeed the same question - in other words - is there a document that lists the rules/guilelines?

**Comment by waldo1001** [comment]
Just got this from @StanislawStempin ;
https://docs.microsoft.com/da-dk/dynamics-nav/compliance/apptest-overview

**Comment by StanislawStempin** [comment]
We do not have a document listing each rule yet but will provide it in the near future. In the meanwhile I saw that waldo might have a nice blog post to share on this topic:)

**Comment by waldo1001** [comment]
The blog:
http://www.waldo.be/2018/04/05/al-code-analysis-rules-diagnostic-descriptors/
The script:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/1a39e45a23f5f38cc6b873ea00823a5763b44151/PSModules/Cloud.Ready.Software.NAV/Al/Get-AlCodeCopInfo.ps1

:-)
