### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by yuliia-biloklokova** [Microsoft/AL#1848]
When I send Http Request from one function and try to process Response in the next function, I get an error:

---------------------------
Cannot access a disposed object.
Object name: 'System.Net.Http.StreamContent'.
---------------------------

Example:
```
procedure TestProcedure();
    var
        Response: HttpResponseMessage;
        ResponseText: Text;
        URL: Text;
        BodyText: Text;
    begin
        URL := 'https://postman-echo.com/post';
        BodyText := 'testtest';
        
        SendRequest(URL,BodyText,Response);
        Response.Content.ReadAs(ResponseText);
        Message(ResponseText);
    end;

    local procedure SendRequest(URL:Text;var BodyText: Text;var Response: HttpResponseMessage);
    var
        Client: HttpClient;       
        Content: HttpContent;
    begin
        Content.WriteFrom(BodyText);
        Client.Post(URL,Content,Response);
    end;
```
Looks like HttpResponseMessage is disposed automatically in the end of my 'SendRequest' function.
Is it possible to process Response only in the same function where request was sent?

**Comment by kalberes** [comment]
Which versions(extension version, server version) are you using?
