### ISSUE TITLE
Is the Azure image no longer updated?

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#1849]
Yea finally the new preview is now online :). I also updated my Azure Machine directly to update the ReadMe. But I only get the February AL expansion. Do I have to go through the get ready program and is the Docker image just out of date? Or is this a bug?

**Comment by StanislawStempin** [comment]
As mentioned in the blog post https://blogs.msdn.microsoft.com/nav/2018/03/23/developer-preview-march-update/ the latest build should have become publicly available as of April 2nd. If that's not the case then it's a big.

**Comment by Gallimathias** [comment]
Fixed with #1948
