### ISSUE TITLE
Stack error

### ISSUE THREAD

**Issue by GedasB** [microsoft/AL#1851]
Any ideas why error comes when i do package, and how to resolve it?
error:
Processing of message 'al/createPackage' failed with error: 'Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.'

Thanks

**Comment by kalberes** [comment]
Does the server event viewer has more?

**Comment by GedasB** [comment]
No. Event viewer has nothing but output in vs code shows as attached.
I thought i have too many objects and removed almost half, but still have error.

[Error.txt](https://github.com/Microsoft/AL/files/1848822/Error.txt)

**Comment by DominikDitoIvosevic** [comment]
Could you confirm us if you have somewhere over 50 if statements nested one within the other?

**Comment by GedasB** [comment]
Not "if" but more than 1000 lines "case" statement. 
And yes, i've commented it and now i can make package.
Code is as attached. 
Could issue be resolved on your side i compiler/package code or i need to split NAV code?
How max case statements can be in one loop?

[Case.txt](https://github.com/Microsoft/AL/files/1850728/Case.txt)

**Comment by kalberes** [comment]
I think the best is to refactor. On the how much case statements we allow, we do not(yet) have a threshold. We are just bound by the .net framework' default stack size allocation in the implementation of our generators.

**Comment by GedasB** [comment]
OK.
Redesigned by split "case" to 500 lines - it works.
So probably not so big issue.
Just would be nice to have "clear" error in compiler.

**Comment by EmilDamsbo** [comment]
We have addressed this issue and the fix will be available in an upcoming release.
