### ISSUE TITLE
Error. AL Page() Function. You must specify open and close parenthesis after page().

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#1861]
Error. This code used to work, then after the AL update, 

CurrPage.MaterialPlanningLines.page.GetLines(TempMPL,true);
![image](https://user-images.githubusercontent.com/36566794/37914270-d4df81e8-30e4-11e8-81bc-7eb1cc1146f6.png)

Thank you
Dennis Aubrey

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/37914475-4acaa446-30e5-11e8-80ec-e9209fc68570.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/37915154-d6976d96-30e6-11e8-9ff1-1e2edd0d2372.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/37915374-642fc054-30e7-11e8-88c8-cebd53e5d4a4.png)

**Comment by kalberes** [comment]
"This code used to work, then after the AL update,"
Which version is it not working?

**Comment by dennisaubrey** [comment]
Warning Message? 

![image](https://user-images.githubusercontent.com/36566794/37925720-5a622abe-3103-11e8-9a6f-e38e87b5851d.png)

**Comment by tfenster** [comment]
I can repro on AL Language extension 0.15.18771

**Comment by kalberes** [comment]
It is a bug, has been accepted, a fix is being worked on.
