### ISSUE TITLE
Error. TextConst variable must have a suffix from this list: Msg, Tok, Err, Qst, Lbl, Txt. 

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#1864]
Upgraded to new patch for AL and this errors was displayed. 

![image](https://user-images.githubusercontent.com/36566794/37916277-6d82a8b8-30e9-11e8-9ca9-bf4f43674797.png)

Thank you
Dennis Aubrey

**Comment by kalberes** [comment]
This is not an error, but a warning. This is coming fronm the CodeCop analyzer.
And its triggered by the codeanalyzers enabled in your settings file.
See here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool
