### ISSUE TITLE
FindPurchPrice in codeunit 7010 "Purch. Price Calc. Mgt.

### ISSUE THREAD

**Issue by wdet** [Microsoft/AL#1865]
Is it possible to make the function FindPurchPrice Global?

```
LOCAL PROCEDURE FindPurchPrice@16(VAR ToPurchPrice@1000 : Record 7012;VendorNo@1008 : Code[20];ItemNo@1007 : Code[20];VariantCode@1006 : Code[10];UOM@1005 : Code[10];CurrencyCode@1004 : Code[10];StartingDate@1003 : Date;ShowAll@1002 : Boolean);
```

**Comment by DuttaSoumya** [comment]
FindPurchPrice and FindPurchLineDisc are functions that cater to local needs of this codeunit. It is not clear from th request why would any extension require a new PurchPrice variable as it gets populated in this codeunit.

**Comment by DuttaSoumya** [comment]
You may duplicate the function in your own extensions code.
