### ISSUE TITLE
ConvertToPdf in codeunit 9651 "Document Report Mgt."

### ISSUE THREAD

**Issue by wdet** [Microsoft/AL#1866]
Is it possible to make the function ConvertToPdf Global?

```
LOCAL PROCEDURE ConvertToPdf@1(VAR TempBlob@1015 : Record 99008535);
```

**Comment by StanislawStempin** [comment]
I can see that instead of ConvertToPdf being made global a new function in COD10 has been introduced:
PROCEDURE TryConvertWordBlobToPdf@67(VAR TempBlob@1000 : Record 99008535);

Does that meet your needs?
