### ISSUE TITLE
Create You Own Package

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#187]
Let's say I want to go Hybrid. Meaning I will make some changes to the old Development Environment like adding events that don't exist and I want to do everything else with AL as an extension.

How do I create my own Package file and make the compiler understand that I want to work against my own base version?

**Comment by Gallimathias** [comment]
When I look at the architecture, the compiler gets the needed info about an interface of the service from the database. Possibly. He already understands the changes. Already tried?

**Comment by esbenk** [comment]
This is not possible right now. Currently the base packages are created with an internal tools (not productized yet) that uses the .txt source. We are aware of the hybrid scenario, but don't support it at this point in time.
