### ISSUE TITLE
How to install custom app (*.app) file on docker container

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#1870]
Hi all, 

after all conversion / debugging / development / dev testing, I'm **ready** to ship my custom app to QA.
**But**, I haven't found detailed steps to install my custom app to another machine (QA's - docker container). 

Please provide the steps to move forward.

Thanks in advance.

Regards
Sachin Chavan.

**Comment by kalberes** [comment]
You can publish/install your extension on the other machine.
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-how-publish-and-install-an-extension-v2

**Comment by chavansachin20** [comment]
Thanks @kalberes , but here I'm using Docker container, not my machine. And here I'm unable to connect my powershell to docker container.

I need to install my custom app from my VS code to Docker NAV server instance.

**Comment by tfenster** [comment]
You can just do ```docker exec -ti <containername> powershell``` and you have a PowerShell session in your Container. But probably easier: Check NavContainerHelper, especially [this part](https://github.com/Microsoft/navcontainerhelper/blob/master/NavContainerHelper.md#Extension)
