### ISSUE TITLE
Code analysis: Possible Overflow with Labels

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#1871]
The code analysis tool should take into consideration the **MaxLength** property for labels. Right now it is throwing a warning even though my MaxLength is set to match the field length (20 in my example below) that the label contents are populating.

![image](https://user-images.githubusercontent.com/5204734/37986499-9f082c2e-31c9-11e8-89de-53eb8d255d31.png)

**Comment by DominikDitoIvosevic** [comment]
Good catch. We'll fix

**Comment by Kraver88** [comment]
Did not know about the MaxLength property of Labels. Could you tell me what the Locked property does?

**Comment by DominikDitoIvosevic** [comment]
It specifies that the label will not be translated in the product. It can be included in the xliff file for reference but shouldn't be translated
