### ISSUE TITLE
Forcing ID range on Field in own tables

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#1878]
I am trying the latest version of the extension (0.15.18771) and it is giving me:

>  error PTE0002: Field 'ID' has an ID of [1]. It must be between 50000 and 50099
Even in my own tables. ???

I hope that this is a bug.

**Comment by kine** [comment]
May be yes, but there is no issue in having 50099 in the text, but that the field ID in own table is checked at all... which is different than checking object IDs.

**Comment by StanislawStempin** [comment]
This one is a bug and already fixed in the next update. Field ID checks should only be enforced on table extensions.
