### ISSUE TITLE
Error form Microsoft.Dynamics.Nav.Client.BusinessChart

### ISSUE THREAD

**Issue by NSilvergrund** [Microsoft/AL#1883]
Hi! 

Trying to develop an AL projekt with the Control Add-In for Charts. Get an error from the add-in. 
"Unexpected token C in JSON at position 0. Stopping the debug adapter."

The Debug Console window says: Error: "Not an application method".

Also did a test with the example Code from:
https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/

Same problem there. 

Trying to publish it on a docker, version: navinsider.azurecr.io/dynamics-nav:11.0.21063.0-finse

**Comment by kalberes** [comment]
You probably put a breakpoint in a user control trigger? Isn't it? And tried to hit it?
I that was the case the that is an issue in the debugger that has been recently fixed and will be released in a next version of the AL extension.
If you would like this to be back-ported to Nav 2018 you will have to open  an RFH ticket with CSS as it is described in the https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions

**Comment by NSilvergrund** [comment]
That was the issue, now I got the other to fix without a debugger... :-) Thanks
