### ISSUE TITLE
how to access the file in my package

### ISSUE THREAD

**Issue by Twija** [microsoft/AL#1884]
i want to import some images when the app is installed.
so i add some images on the package like below.
>Root
  >>.alpackages
  >>.vscode
  >>img
    >aaa.png
    >bbb.png
  >>src
    >Cod1111.InitApp.al
    >Tab1111.Setup.al
      >>image1:Media
      >>image2:Media

how can i import the images from the package into the table?

**Comment by thpeder** [comment]
Hi @Twija,
Currently there is no way of doing that, but we will add it to the backlog.

**Comment by kalberes** [comment]
You can't. But Media's do have their own AL API. ALso we have on our longer plan to support resources within an app package.
