### ISSUE TITLE
Main / Sub working differently in Business Central than before?

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#1887]
I create a minimal main / sub page sample: sub page contains two fields from cust. ledger entry, main page only includes the part for my sub page. When I deploy this to 2018 CU3 it works as I expect. When I deploy this to Business Central, I don't get any data. I am probably missing something obvious, but what do I need to change to make this work on Business Central?

code:
```
page 50100 main_test
{
    PageType = Document;
    
    layout
    {
        area(Content)
        {
            part(sub_test; sub_test) {}
        }
    }
}

page 50101 sub_test
{
    PageType = ListPart;
    SourceTable = "Cust. Ledger Entry";
    
    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("Entry No.";"Entry No.") { }
                field(Amount;"Amount") { }
            }
        }
    }
}
```

2018 CU3
![image](https://user-images.githubusercontent.com/15346084/38097968-113f20fa-3377-11e8-9e0c-6a37a0948e50.png)

Business Central
![image](https://user-images.githubusercontent.com/15346084/38098001-28030dba-3377-11e8-8118-04006cf2fe8f.png)

Obviously my real extension code is more complex but I think the root problem is the same

**Comment by AndriusAndrulevicius** [comment]
ApplicationArea?

**Comment by tfenster** [comment]
@AndriusAndrulevicius right, thanks!
