### ISSUE TITLE
Request: ability to run AL tests on command line

### ISSUE THREAD

**Issue by coffeecup007** [microsoft/AL#1889]
Feature request: We'd like to be able to run the AL tests on the command line (or via powershell).
The goal is to integrate into our automated build system.

Ideally it would report details on test failure.
Nice stretch goal would be to report on test coverage as part of this.

**Comment by DominikDitoIvosevic** [comment]
Hi @coffeecup007 . Thank you for the input. This is on our backlog

**Comment by luxferresum** [comment]
Whats the current status for this? Building a CI pipeline without this is kind of hard.

**Comment by BazookaMusic** [comment]
This is nowadays handled by our work on AL:Go and BCContainerHelper, with nice support for github actions and a bunch of other stuff.

I will close this.
