### ISSUE TITLE
Find references for table and codeunit triggers

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/AL#189]
Can we get code reference information on the following:

- Table triggers (insert, modify, delete, rename)
- Codeunit onRun

**Comment by NKarolak** [comment]
@atoader Any news on this topic?

**Comment by ti-jalopez** [comment]
Hi,

I propose a related enhacement in  "Go to reference" and "Find All References" commands of AL Language in VSCode: show trigger / method before the references found.

Example: first image shows current behaviour and the second image the new showing berfore the trigger or method:
![image](https://user-images.githubusercontent.com/68008246/124556745-f1ba8600-de38-11eb-8c5c-4b1f624b79e2.png)

Best regards,

**Comment by BazookaMusic** [comment]
Some parts of this were already implemented a few releases ago. Specifically, some events, triggers and built-in methods are searchable by find references.

We also have this idea planned for this issue: https://experience.dynamics.com/ideas/idea/?ideaid=56458708-fb7f-eb11-8ced-0003ff45d48e

Thus I will be closing this issue.
