### ISSUE TITLE
Azure Active Directory and Microsoft Dynamic 365 finance & operation authentication token issue

### ISSUE THREAD

**Issue by DivyaRigel** [Microsoft/AL#1890]
Before logging a new issue please make sure to:
1) Read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)
2) Search if there is an existing issue for what you want to log. If it's closed you can reopen it and add your comments.
3) Use the latest Developer Preview release both the server part and the AL Language extension in VS Code (listed on the [repository home page](https://github.com/Microsoft/AL))
4) If you're not using the latest released version (or are using a private build drop that is newer) please provide the version number in the issue

To help us reproduce the issue and find the root please try to:
A) Attach a minimal set of AL code that causes the issue
B) If the error occurs on the server - copy/paste the server stack trace from the Event Viewer

**Comment by thpeder** [comment]
Hi @DivyaRigel,
You need to give us some more information than just the title.

**Comment by DivyaRigel** [comment]
I want to use web API for the MicroSoft Dynamic 365 Finance and Operation, as per the their guide line I have created/registered app in the Azure Active Directory and try to generate Access Toke as per below using the Postman, but getting issue of scope :

Error: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope https://api.financials.dynamics.com/ is not valid. The scope format is invalid. Scope must be in a valid URI form https://example/scope or a valid Guid ..

**Postman get access token data

Auth URL : https://login.microsoftonline.com/coromed.onmicrosoft.com/oauth2/v2.0/authorize

Access Tocken URL : https://login.microsoftonline.com/coromed.onmicrosoft.com/oauth2/v2.0/token

Client id = [Our Client ID]

Client Secret = [hsdhjkfhsjkdhfjkwshdjkfhsjkdhfjsdjhfgwjdsgfwegew]

Scope = https%3A%2F%2Fapi.financials.dynamics.com%2F

Grant Type = Autorization Code**

Which parameter and its format have to use in scope field ?

**Comment by dennisfrostlander** [comment]
Hi @DivyaRigel, 
Could you please provide a link to the guide that you've been using?

**Comment by DivyaRigel** [comment]
Hi @dennisfrostlander ,
[](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/third-party-service-test)

**Comment by dennisfrostlander** [comment]
Thanks,
The guide you are referring to is for a different product - Microsoft Dynamics 365 for Finance and Operations (formerly known as Dynamics AX).

This repository is for issues related to Microsoft Dynamics 365 Business Central (formerly known as 
Microsoft Dynamics 365 for Financials, formerly known as Dynamics Nav).

https://api.financials.dynamics.com is API for Business Central, so it will definitely not work with Finance and Operations. For further help, please reach out to Finance and Operations support forums.
