### ISSUE TITLE
[Event-Request] OnBeforeFinalizePosting

### ISSUE THREAD

**Issue by fmoric** [Microsoft/AL#1891]
In codeunit 80 and 90 i think there should be OnBeforeFinalizePostingCommit or just OnBeforeFinalizePosting.

There is an event there OnAfterFinalizePosting, but it has a commit before it.
We have a situation in witch we need to throw error before commit so it all rolls back.
We send documents to Tax Authority and before we can completely finish invoice we need to get a hash from them, if we cannot then we need to throw error. 

But first we have to get all VAT calculation to create xml for sending.

**Comment by AlexanderYakunin** [comment]
Adding external interaction in the middle of transaction is not recommended, instead you can send it from posted documents. This is preferred design.

**Comment by fmoric** [comment]
But as i wrote, i must not let the document be posted if i cannot get that hash.

What about the RedeemCouponsForSalesDocument?
It has a web service request, and it even has a commit inside of it, which i think is a bug.
There are few other functions that handle after posting events. Why couldn't there be a business event? 
There is even FinalizePostATO that has a testfield inside of it, which means it could throw an error.

I just think that there sould be a way that you can do your own finalization before commit

**Comment by AlexanderYakunin** [comment]
OnBeforeFinalizePosting already implemented for another earlier request in both COD80 and COD90.
