### ISSUE TITLE
Array variables with reference..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1893]
Hello,

We published a codeunit with couple of functions as web services. When we are browsing web service url in browser we can not see the array parameters with reference under results element for function in codeunit. Please find the screen shot.

Here is procedure syntax in with al

 procedure GetCartPrices(ItemNumber: ARRAY[300] OF Code[20]; VariantCode: ARRAY[300] OF Code[20]; CustomerNumber: Code[20]; Quantity: ARRAY[300] OF Decimal; UOM: ARRAY[300] OF Code[20]; QuoteNo: Code[30]; CallFromCartPage: Boolean; var Price: array[300] OF Text[30]; var SalesPrice: ARRAY[300] OF Text[30]; var DiscountPercent: ARRAY[300] OF Text[30]; var LineTotal: ARRAY[300] OF Text[30]; var InvoiceDiscount: Text[30]; var TaxAmount: Text[30]; var ShippingAmount: Text[30]; var InvoiceAmount: Text[30]; ArraySize: Integer; var CouponCode: Code[20]; var Response: Text[200]); 

Begin
End;

in the screen shot price, salesprice,discountpercent & linetotal are array parameters and not available under results. _****So that when we are using the soap URL and call function from another solution can not see above 4 parameters as references.****_

![screen shot1](https://user-images.githubusercontent.com/35101458/38140168-31daf832-3450-11e8-97bb-ea6b56176446.jpg)

But we can able to see those array parameters under resultus element and use them references in another application with **V1 and Nav 2018** as below
![v1](https://user-images.githubusercontent.com/35101458/38161116-5d0062fe-34e6-11e8-9c2d-14c24573a2ab.jpg)
![2018](https://user-images.githubusercontent.com/35101458/38161117-60de5926-34e6-11e8-8621-e5eba38cd72e.jpg)

Can some one help me on that

**Comment by esbenk** [comment]
What version are you using? BC with V2 extensions?

**Comment by srinivasdes** [comment]
we are using Al Version 0.14.17461

**Comment by StanislawStempin** [comment]
We have reached out to the owning team and will update this thread once we receive a reply
