### ISSUE TITLE
ADCS future

### ISSUE THREAD

**Issue by Phfo** [Microsoft/AL#1896]
Will ADCS be replaced by something new ?
Suppose we make a copy of an existing miniform codeunit to AL for doing a specific modification for our customer…
Like described in https://msdn.microsoft.com/en-us/library/hh173071(v=nav.90).aspx & https://msdn.microsoft.com/en-us/library/hh165798(v=nav.90).aspx
We can copy an existing codeunit but those codeunits contains .net vars ? Is there a workaround ?

**Comment by StanislawStempin** [comment]
We have reached out to the owning team and awaiting a reply

**Comment by AndersLarsenMicrosoft** [comment]
Hi 
We do not have any plans of replacing the ADCS at this moment. After refreshing my memory of the “mini forms” I can see that there is a lot of .net reference in the existing code units. Could you let us know which of the procedures you are calling in your code?  Hen we might be able to help 

Thanks
Anders

**Comment by Phfo** [comment]
Hi Anders
We want to make a new codeunit for a specific inventory scanning (in AL)...normally we copy an existing codeunit and do the modifications. However there are functions which require .dotnet vars f.ex the function to initialize the miniform in the OnRun trigger.
(There are 3 used dotnet vars : ReturnedNode : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";
        DOMxmlin : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlDocument";
        RootNode : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";)
How can we proces new defined miniforms/cdu's in ADCS in AL without using .net ?

**Comment by AndersLarsenMicrosoft** [comment]
thanks i will take a look at it during next week

**Comment by AndersLarsenMicrosoft** [comment]
I looked into it and it looks like the only posible solution to make ADCS extensible is to do an uplift (convert is to an extension) of the this feature. a this moment it is not in our backlog to do this in a 1. party extension.
Thanks
Anders

**Comment by Phfo** [comment]
Hi Anders
Thanks for quick answer. Do you have a time frame for adjustment ?
Philip

**Comment by lbernhardson** [comment]
It has been confirmed that the plan moving forward to have ADCS extensible will be to create a PowerApps app.  Microsoft is currently working on identifying what team can complete this work effort.  There is no current timeline as to when it will be completed.  In the meantime, the functionality available for ADCS is how it functions today for NAV 2018 and Dynamics Business Central.

**Comment by CanuckNav74** [comment]
@lbernhardson that sounds like quite the bold departure from the current telnet-based implementation of ADCS.

The benefit of ADCS is that it runs on any device that can establish a terminal emulation connection. Every OS supports this. 

Our customers have a substantial investment in rugged data capture devices, almost all of which are WinCE or WM6.5 based and various form factors (handheld, wrist-mounted, etc). They are not cheap to buy (costing at least $1,000 per unit or more). Will those customers need to abandon their data capture hardware investment to adopt a powerapps approach that is better suited for iOS and Android hand-held devices? Is WinCE Pocket IE even capable of running browser-based PowerApps? I'm aware that there is a third party webkit browser out for legacy WinCE and WinMo platforms (see : "zetakey") but I haven't had favorable experiences with it in the past (slow + memory issues). 

Hardware challenges aside, it also sounds like those who previously customized ADCS will have to re-factor their ADCS customizations from scratch to adopt this powerapps model. Is that a correct assumption?

A short-term suggestion:

ADCS documentation is somewhat scattered, but the guides pertinent to adding/customizing miniform  codeunits is circa NAV 2016. ADCS documentation is either hard to find or unavailable for NAV 2018. Someone may unknowingly try to implement ADCS for Dynamics 265 Business Central (cloud-only) only to discover that ADCS is not extensible via AL. There should be documentation out there warning that **C/AL** customizations are needed to add/customize ADCS miniforms codeunits and thus, on-prem only. 

thoughts?

**Comment by henrikwh** [comment]
@CanuckNav74 docs has been updated to reflect that ADCS does not work for BC SaaS. We’re pursuing a strategy, where we expose additional Standard APIs enabling ADCS scenario, so clients/apps can be developed against those standard APIs in BC SaaS. PowerApps is a framework which allows for building apps supporting ADCS scenarios. We will aim to have good connector support, wrapping the APIs, for easy consumption by PowerApp & Flow. PowerApps is just an option.

**Comment by henrikwh** [comment]
Standard web API services needs to be enabled for on-prem, as they are not enabled by default. https://docs.microsoft.com/en-us/dynamics-nav/enabling-apis-for-dynamics-nav. APIs will work across SaaS and onprem.
