### ISSUE TITLE
GetHideValidationDialog should be global

### ISSUE THREAD

**Issue by muratkarabek** [Microsoft/AL#1898]
I think, GetHideValidationDialog function should be global on Sales Header table and a new function with the same name should be added to Purchase Header table. When subscribing OnBefore/OnAfterValidate events, it's needed to access HideValidationDialog variable from subscriber function.

**Comment by DuttaSoumya** [comment]
We have accepted the request. This function shall be soon made accessible through extensions.

**Comment by megel** [comment]
**GetHideValidationDialog** should be also global / external for **Sales Line**

![image](https://user-images.githubusercontent.com/15800069/40220094-44c2f96a-5a78-11e8-9407-1c71256b131b.png)
