### ISSUE TITLE
Ambiguous object reference - non system object

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#190]
The following code gives an error that the reference to the No. Series table is ambiguous. I had a similar issue with referencing system tables (see #184 ) so this may or may not be a result of the same issue.

```
PROCEDURE IngredientNoSeriesIsDefault() : Boolean;
  var
    NoSeries : Record "No. Series";
  begin
    IF NoSeries.GET(DetermineIngredientSeriesNo) THEN
      EXIT(NoSeries."Default Nos.");

    EXIT(FALSE);
  end;
```

**Comment by NavBitsAndBytes** [comment]
This issue seems to stem from the fact that I have defined a dependency to my library extension. As soon as I do that, every base object reference shows as ambiguous. If I remove the dependency the base object errors go away.

**Comment by StanislawStempin** [comment]
Thanks for the follow up. The root cause of this bug is the same as #184 and has been fixed for the May Update.
