### ISSUE TITLE
txt > txt is compiled but failure during publish

### ISSUE THREAD

**Issue by GedasB** [Microsoft/AL#1910]
We have code like:

if format(weekday) > '07' then error(..)

Where 'weekday' is weekday number from date. something like 01 for monday and etc.
So finally it must to be understood
if '01' > '07' then error(..)

This works in c/al; was converted to al, was compiled and packet. It fails only in publishing with C# error that text can't be used with '>'..

Probably this must be fixed in compiler.

**Comment by Gallimathias** [comment]
I don't see it as a mistake. After all, you're really comparing text here. Doesn't Weekday return an integer?

If this works in C/al I'd say c/al is rather broken and all works correctly.

The solution should look like this:

````csharp
if weekday > 7 then
    Error('bla blub');
````

or

````csharp
if 1 > 7 then
    Error('What the hell....');
````

**Comment by GedasB** [comment]
I used 'weekday' in sample.
really it was something like:

DateString := FORMAT(TODAY,10,'<Day,2>.<Month,2>.<Year4>');
 if COPYSTR(DateString,1,2) > '07' then
    exit(false);

Yes. Fix is obvious.
But I don't like:
1. It was working in c\al - doesn't matter if it is not correct according syntaxis.
2. This was converted to al without warnings or issues.
3. This was compiled without warnings or errors.
4. This was packaged to app without errors.
Only publish shows error. 
Why if it is incorrect and can't work, why error comes only in last step?????

**Comment by Gallimathias** [comment]
Ah, okay, I see. Yes, of course the question is what is right here. I would say it is correct that the operator "is larger than" not allowed for strings. At least not like this.

I'm with you that intellisens should mark it as an error as well as that the compiler should actually throw an error here.

**Comment by DominikDitoIvosevic** [comment]
This has been fixed on the latest developer preview. If you would like this to be backported to Nav 2018 please open a support ticket.

https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by GedasB** [comment]
No problems
Thanks
