### ISSUE TITLE
Question: VSIX and ALPackage Archive

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#1916]
While automating the AL Build Process it is always a pita to get the necessary vsix and alpackages in all the needed versions.
Does Microsoft plan to build a download repository where we can get all versions of vsix and alpackages?
Is there an more easy way to get them as downloading the nav iso (download 900mb for the needed 9MB) or creating a docker container?

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider it for our backlog.

**Comment by BazookaMusic** [comment]
You can download the extensions directly from the marketplace these days:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/13.0.903630/vspackage
