### ISSUE TITLE
Http Web Request hard-code

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1919]
In order to call web services from extensions, it is necessary to use codeunit  1297 Http Web Request Mgt.

The problem is that a lot of the parameters are hardcoded in the codeunit:
HttpWebRequest.Method := 'GET';
HttpWebRequest.KeepAlive := TRUE;
HttpWebRequest.AllowAutoRedirect := TRUE;
HttpWebRequest.UseDefaultCredentials := TRUE;
HttpWebRequest.Timeout := 60000;
HttpWebRequest.Accept('application/xml');
HttpWebRequest.ContentType('application/xml');

Will this be changed?

**Comment by ajkauffmann** [comment]
Why do you think it is necessary to use Codeunit 1297? I can perfectly live without it and do everything I want with web services from extensions.

**Comment by StanislawStempin** [comment]
Please see: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#dotnet-types-are-not-available-in-extensions-v2-what-now

And actually a great blog post from AJ if I may :)
http://www.kauffmann.nl/2017/06/24/al-support-for-rest-web-services/
