### ISSUE TITLE
References in the Code

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#192]
This is maybe just a question: 
Is there a way I can switch off (and back on) the calculation and displaying of references? In some cases code could be easier to read without them showing and also while writing code the appearance of reference Information makes the line appear to "jump" which is annoying.

**Comment by DominikDitoIvosevic** [comment]
This is a generic feature which is used for many languages which support it in Visual Studio Code.
You can turn it off by setting "editor.codelens": "false" in user settings.

For more information go to: https://code.visualstudio.com/Docs/editor/editingevolved#_reference-information

**Comment by RafaelKoch** [comment]
Thanks, found it. 
I also found an extension that allows for toggling with a simple command or even with a little setup bound to a Keyboard shortcut. Works like a charm. So I'm good.

**Comment by doivosev** [comment]
Could you please link the extension here so that other people can find it easily as well?

**Comment by RafaelKoch** [comment]
Sure:
[](https://marketplace.visualstudio.com/items?itemName=cmlewis89.vscode-togglecodelens)
