### ISSUE TITLE
Request for event in R952 Suggest Job Jnl. Lines

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1925]
I need the ability to transfer values from the Time Sheet Line (T951) to the the Job Journal Line (T210).  Might be best to have one for Time Sheet Detail (T952) to Job Journal Line (T210) as well.  

The Job Transfer Line (C1004) has functions for other tables to Job Journal Line.  This is what I am looking for.

**Comment by GreatScott000** [comment]
This is for NAV 2018 Build 20783 CU03

**Comment by AlexanderYakunin** [comment]
If you need events for NAV 2018, please go via technical support and create Request for hotfix.

**Comment by AlexanderYakunin** [comment]
We already have 2 events in report 952 for this purpose

LOCAL [IntegrationEvent] OnBeforeInsertTempTimeSheetLine(JobJournalLine : Record "Job Journal Line";TimeSheetHeader : Record "Time Sheet Header";VAR TempTimeSheetLine : TEMPORARY Record "Time Sheet Line";VAR SkipLine : Boolean)

LOCAL [IntegrationEvent] OnAfterTransferTimeSheetDetailToJobJnlLine(VAR JobJournalLine : Record "Job Journal Line";JobJournalTemplate : Record "Job Journal Template";VAR TempTimeSheetLine : TEMPORARY Record "Time Sheet Line";TimeSheetDetail : Record "

**Comment by GreatScott000** [comment]
In what build?  I don't seem them.

**Comment by GreatScott000** [comment]
Found them in the latest build.  Thanks.
