### ISSUE TITLE
Function exposure for Job Planning Line (T1003)

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1930]
The SetupNewLine function in Job Planning Line (T1003) is not exposed although it is not local.  Can it be exposed?

What is the criteria for exposing some and not all?  I assumed it would relate to .NET functionality.

**Comment by GreatScott000** [comment]
This is for NAV 2018 Build 20783 CU03

**Comment by DuttaSoumya** [comment]
One of the criteria as you rightly point out is the use of unsafe .NET. Other criteria could be use of unsafe AL functions as well as access to the file system etc.
