### ISSUE TITLE
Job Buffer (T1017) Function Exposure

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1932]
This is for NAV 2018 Build 20783 CU03

Can InsertWorkInProgress, GetJobBuffer, InitJobBuffer functions from Job Buffer (T1017) be exposed?

**Comment by DuttaSoumya** [comment]
Thanks @GreatScott000 we shall address this as soon as possible.

**Comment by GreatScott000** [comment]
Will these be exposed in BC as well?
