### ISSUE TITLE
CodeCop warnings disappear when opening object

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1936]
I was updating an app that was created a month ago to align with the CodeCop rules. A lot of 'problems' were listed, mostly because of not using () after functions (it seems to see almost everything as a function). 

But as soon as I open an object, the green lines disappear on all other issues after I correct one of them. Making it very difficult to follow up the warnings.

Update: after waiting a few seconds in the open object, the green lines come back. Still somewhat annoying that the green lines don't just stay there, but disappear for about 5 seconds after you corrected one of them.

**Comment by atoader** [comment]
Hi @ajkauffmann ! This is a known issue. Please see the discussion in this issue: https://github.com/Microsoft/AL/issues/732 . We are planning to add support for incremental diagnostics, which should fix the problem you are experiencing, but I cannot give you an exact ETA at this moment.
