### ISSUE TITLE
Add menu item "Generate Symbol Reference" to C/SIDE Development Environment

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/AL#1940]
While in a hybrid of "classic" and "modern" extensions, Generating Symbols is something that may have to be done quite regularly. Those unfamiliar with command line can find it cumbersome to use the generatesymbolreferences command.

While adding to VS Code (#1707) might be more complicated, can it be added as a menu item similar to "Build Server Application Objects"? That could even show progress, or allow you to build for just the highlighted objects....

![image](https://user-images.githubusercontent.com/446329/38401132-50ab114c-3997-11e8-8229-eecf0e7bfac6.png)

**Comment by StanislawStempin** [comment]
After the initial run of 
```
Finsql.exe command=generatesymbolreference
```
you can use the incremental symbol generation which is much faster and doesn't require any additional steps beyond compiling changed objects. To achieve it launch finsql with the flag generatesymbolreference=yes. 
Would that address your scenario?

**Comment by ShadowXVII** [comment]
I wasn't aware that it needed to be launched with that parameter for incremental. Explains why it wasn't working. 

It should be an option in the zup file/tools > options.

We'd always want it on; any consultants forgetting to turn it on would require a full rebuild?

**Comment by ShadowXVII** [comment]
It simplifies things for those familiar with classic development.

Tools > Options seems to be the most appropriate.

Does it rebuild the symbol on compile? Or save?

**Comment by martinhocosta88** [comment]
I know that's kinda out of context, but everytime the symbols are generated, where is the VSIX stored?

**Comment by ShadowXVII** [comment]
Closed as stale
