### ISSUE TITLE
Integration between the financials.dynamics.com and other endpoint

### ISSUE THREAD

**Issue by venkateshwarlu-bavandla** [Microsoft/AL#1943]
Integration between the financials.dynamics.com and other endpoint. I have created a app in azure, I made a authorization request to the server using below url: 

https://login.microsoftonline.com/common/oauth2/authorize?client_id=b101408e-6947-44f8-be24-295a1e10af78&response_type=code&redirect_uri=https://localhost:5000/ck&response_mode=query&resource=https://test.financials.dynamics.com/ 

I got an error: 

error=access_denied&error_description=AADSTS65005: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: b101408e-6947-44f8-be24-295a1e10af78. Resource value from request: https://test.financials.dynamics.com/. Resource app ID: 996def3d-b36c-4153-8607-a6fd3c01b89f. List of valid resources from app registration: 00000003-0000-0000-c000-000000000000, What should i do please help me in that

**Comment by kvaldik** [comment]
I just had this exact same issue. In my case I had to add Dynamics 365 as a required permission to my app registration.

![image](https://user-images.githubusercontent.com/5981414/38417005-365f109c-3986-11e8-9732-eec5c1ef358e.png)

Hope this helps, getting this authorization to work has been a hell of hassle for me.

**Comment by StanislawStempin** [comment]
I reached out to the owning team and will provide an update once I hear back from them.

**Comment by venkateshwarlu-bavandla** [comment]
Hi kvaldik,

I did not have API name "Dynamics 365 (Dynamics 365 for Financials)", For getting in the list should we do anything on Azure portal.

**Comment by venkateshwarlu-bavandla** [comment]
Hi Kvaldik, Am able to add the financials api access.
Am able to get the access token.

**Comment by venkateshwarlu-bavandla** [comment]
Now, am facing another problem. I got a access token for resource "https://test.financials.dynamics.com/" (My azure app is multi multi-tenanted). Using the above token if i access the "https://api.businesscentral.dynamics.com/v1.0/api/beta/companies", Am getting {"message":"Unauthorized"}. Is any body having any idea why its throwing unauthorized error

**Comment by venkateshwarlu-bavandla** [comment]
the above issue resolved using https://github.com/Microsoft/AL/issues/1982
