### ISSUE TITLE
error AL1024: A package with publisher 'NAVSkills', name 'MasterClassExercise1', and a version compatible with '1.0.0.0' could not be loaded.

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1944]
During my last workshop is was working with the group on dependent extensions. We build a base one with the following identifiers used as dependencies in the app.json of the second, dependent extension:

`       "appId": "b6d76c04-1fd3-438b-9d33-9423b18d0289",`
`       "publisher": "NAVSkills",`
`       "name": "MasterClassExercise1",`
`       "version": "1.0.0.0"`

When building the second extension and down loading the symbols it did download the standard symbols and the symbols of the base extension, but when deploying it (using Ctrl+F5) VSCode threw the error in the subject and the additional following lines:

`PageExtensions/PEX50001_ExampleSetupExt.al(9,42): error AL0118: The name 'Example Person Nos.' does not exist in the current context`
`TableExtensions/TEX50001_ExampleSetupExt.al(1,43): error AL0247: The target Table ExampleSetup for the extension object is not found`
`PageExtensions/PEX50001_ExampleSetupExt.al(10,43): error AL0118: The name 'Example Product Nos.' does not exist in the current context`
`Codeunits/COD51400_ExampleDocumentNoVisibility.al(8,20): error AL0185: Page 'ExampleSetup' is missing`
`PageExtensions/PEX50001_ExampleSetupExt.al(1,45): error AL0247: The target Page ExampleSetup for the extension object is not found`
`Codeunits/COD51400_ExampleDocumentNoVisibility.al(58,20): error AL0185: Table 'ExampleSetup' is missing`
`Codeunits/COD51400_ExampleDocumentNoVisibility.al(66,20): error AL0185: Table 'ExampleSetup' is missing`
`Tables/TAB50020_ExampleProduct.al(73,23): error AL0185: Table 'ExampleSetup' is missing`
`Tables/TAB50010_ExamplePerson.al(119,23): error AL0185: Table 'ExampleSetup' is missing`

As the lines says all these objects are expected in the base extension and they are. And the extension is installed in the database programmed against with the second extension. If not how could it have downloaded the symbols of the base extension?

So the question is: what is done wrong? And more important: how to fix this?

The funny things is: some of us did get it working straight away, some got the same error.

### Notes
- I checked and rechecked the settings in both app.json files and they're OK. Again here: if they were not OK how could the symbols of the base extension have been downloaded ?
- We were working on NAV 2018 CU3
- Read https://github.com/Microsoft/AL/issues/1263, as it has the same subject, but no solution there

**Comment by StanislawStempin** [comment]
Can you check if the version numbers match exactly? I recall we had a bug where parts of the codebase were doing an exact version match whereas VS Code did only "greater than".

**Comment by lvanvugt** [comment]
> Can you check if the version numbers match exactly?

Just to be sure: what do you mean with _version numbers_?
If you mean the appId: yes, as said "I checked and rechecked the settings in both app.json files" and they match:

- Base Extension: "id": "b6d76c04-1fd3-438b-9d33-9423b18d0289",
- Second extension: "appId": "b6d76c04-1fd3-438b-9d33-9423b18d0289",

**Comment by atoader** [comment]
Hi @lvanvugt ! That is the ID of the extension. It is necessary, but not sufficient. Can you also check the version number. For example:
Extension A:
```
  "id": "498b86f9-3ce2-4912-a5d8-83a2c64b410d",
  "name": "A",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.1.1.0",
```

Extension B:
```
  "dependencies": [{
    "appId": "498b86f9-3ce2-4912-a5d8-83a2c64b410d",
    "name": "A",
    "publisher": "Default publisher",
    "version": "1.1.1.0"
  }],
```

**Comment by atoader** [comment]
Hi @lvanvugt ! We do not have enough information to reproduce the problem. I will close this issue. Feel free to reopen it if you have new information.

**Comment by lvanvugt** [comment]
Just for completeness sake: with later version I did get it working.
