### ISSUE TITLE
Event Request in Page 6510 

### ISSUE THREAD

**Issue by shalu712** [Microsoft/AL#1945]
Hi Team,
I need to flow some custom fields value from Tracking Specification to reservation entry Please  provide events as per the below screenshot.
![image](https://user-images.githubusercontent.com/36455082/38408517-8b83dff2-399b-11e8-9ebf-772c7
![event in p6510](https://user-images.githubusercontent.com/36455082/38408557-b1cb8052-399b-11e8-8b2f-006736d55245.png)
ea4b5b4.png)

**Comment by pranav4186** [comment]
Hello Team,

It would be great if we can get both OldTrackingSpecification and NewTrackingSpecification as a parameter in this suggested event.

Thanks
![event suggession in page 6510](https://user-images.githubusercontent.com/35543761/38895548-34d70ece-4245-11e8-9602-09a290578426.png)

**Comment by StanislawStempin** [comment]
Please log a new request. This one is already marked as fixed in our systems
