### ISSUE TITLE
SourceTableView Using Field Added via TableExtension

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#195]
I have a tableextension which adds an option field to the Sales Header table. I have a new page which uses Sales Header as its SourceTable. I want to refer to my new field in the SourceTableView of the new page but get the following build error:

Reference '<field name>' in application object 'Sales Header' does not exist.

**Comment by esbenk** [comment]
Can you share the SourceTableView property and the type of the added field?. I haven't been able to reproduce the problem.

**Comment by jimmymcp** [comment]
This is the declaration of the field in a Sales Header table extension object:

field(70086925;"Credit Management Status";Option)
    {
      CaptionML=ENU='Credit Management Status',
                ENG='Credit Management Status';
      Editable=false;
      OptionCaptionML=ENU='" ","Credit Held","Credit Released"',
                      ENG='" ","Credit Held","Credit Released"';
      OptionMembers=" ","Credit Held","Credit Released";
    }
}

And this is the properties of the page:

page 70086919 "Credit Held List"
{
  // version CMA1.0

  CaptionML=ENU='Credit Held List',
            ENG='Credit Held List';
  Editable=false;
  PageType=List;
  SourceTable="Sales Header";
  SourceTableView=where("Credit Management Status"=const("Credit Held"))

Which results in the error "Reference 'Credit Held' in application object 'Sales Header' does not exist."

**Comment by StanislawStempin** [comment]
I could now reproduce the issue, we will look into it.
