### ISSUE TITLE
error AL0247: The target Page "Customer List" for the extension object is not found

### ISSUE THREAD

**Issue by joshbooker** [Microsoft/AL#1953]
On a new BC trial with sandbox enabled, I've authenticated and downloaded symbols in VSCode successfully but get the following error.

error AL0247: The target Page "Customer List" for the extension object is not found
Error: The package could not be created.

VSCode gallery flavor of AL Language Extension is up to date.  I tried uninstalling and reinstalling - no luck.

Does anyone have a post on troubleshooting steps for this?

**Comment by StanislawStempin** [comment]
Do you see the Application symbol file in the .alpackages subfolder in your project? 
What is the version number on the symbols and what is the version number in your app.json : application element?

**Comment by joshbooker** [comment]
app.json

`  "platform": "11.0.0.0",
  "application": "11.0.0.0",`

Symbols
Application 12..0.21229.0
System 12.0.12928.0

I tried setting app.json the same, but that didn't work.  Also tried connecting to another v11 sandbox and again, symbols loaded but same error on F5.

**Comment by megel** [comment]
Did you check the Version of the *AL Language Extension* for VS Code?

**Comment by joshbooker** [comment]
It the most recent VSCode Gallery version.  

'Business Central Spring Release'
AL Compiler version 0.11.14434

**Comment by StanislawStempin** [comment]
0.11 is an old version. The latest AL Language version in the gallery is 0.15. Please retry with that one

**Comment by joshbooker** [comment]
I had uninstalled and reinstalled AL extension twice but got ver 11 each time. Then vscode updated itself and I was able to install AL ver15. All is good now. Thanks.
