### ISSUE TITLE
Event triggers on functions

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1955]
In any VSCode workshop I am performing the question arises whether there will be enough events available to be able to do proper extension development. With this the next question comes up why we do not have _OnBefore_ and _OnAfter_ function event trigger?
I know that this wouldn't have helped us a lot on NAV 2016 with codeunits like codeunit 80 and 90 with these huge amount of code int the OnRun trigger. Or in other words, with all the badly structured NAV code in general.
But given the fact that we all tend to get our code better structured wouldn't it make sense to enable _OnBefore_ and _OnAfter_ event triggers on functions?

**Comment by StanislawStempin** [comment]
This is actually something we are exploring. I will use this issue for tracking.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by lvanvugt** [comment]
@thpeder, I guess I will, but in the light of @StanislawStempin answer this feels awkward. I mean, as it was soemthing you were exploring (long time ago) what has come out of that?
