### ISSUE TITLE
Activating docs.microsoft.com topics straight from VSCode

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1956]
At docs.microsoft.com we have a lot of information on the AL language. It would be great if you could get VSCode enabled to open a specific topic on docs.microsoft.com that relates to the selected code.

For example, when my cursors is on the AL function **Error** and I right click the context dropdown menu shows met the option Help and by selecting it, the topic on the Error function is opened in my web browser.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion, we are actually looking into this. VS Code only recently enabled markdown and links support in all the IntelliSense contexts and we would like to add help topic links to as many places as possible.

**Comment by EmilDamsbo** [comment]
Closing this ancient issue. We have been providing help links in the 'Problems' pane in VSCode and IntelliSense hover for properties, diagnostics etc. for a while now.
