### ISSUE TITLE
Intellisense: put most used options at top

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1959]
Sitting in front of a (partly) empty page you click Ctrl+<space> to activate Intellisense and get the drop down list with all possible option (related to the context your cursor is in. Alphabetically ordered.
It would be great if at he top of the list the most (recent?) used options are shown like in the command palette of VSCode. This would the live of a Al developer some much easier.

BTW: often on the Intellisense dropdown list the cursor is put somewhere down. Why? What is the logic behind?

**Comment by StanislawStempin** [comment]
That's a good suggestion. We will look into it.

Regarding the cursor being put somewhere down this is an unfortunate effect of VS Code changing the default value of the "editor.suggestSelection" parameter. To return to the desired behavior include the following value in your user configuration:
```
"editor.suggestSelection": "first"
```

**Comment by blrobl** [comment]
Hi, thank you for your suggestion! This seems to still not have been implemented, and we are not prioritizing this for the immediate future, so we recommend you submit this at aka.ms/BCIdeas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
