### ISSUE TITLE
FlowField Calculation Formula Using Field Added via TableExtension

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#196]
I have added a new option field to the Sales Header with a tableextension. In a new table object I want to define a flowfield which counts the number of Sales Header records where the new option field has a certain value.

Referring to the new field in CalcFormula property gives the following error:

Reference '<field name>' in application object 'Sales Header' does not exist.

**Comment by kalberes** [comment]
This should work. Can you please share your calc fomula?

**Comment by jimmymcp** [comment]
I've actually deleted this object now as I realised I don't need it (it was part of a Cue table for a Role Centre), but this is an example of the issue:

field(2;"No. of Orders";integer)
        {
            FieldClass=FlowField;
            CalcFormula=count("Sales Header" where("Credit Management Status"=const("Credit Held")));
        }

"Credit Management Status" is a new option value added to the Sales Header table by a table extension object.

The error is "Reference 'Credit Held' in application object 'Sales Header' does not exist."

**Comment by StanislawStempin** [comment]
It looks like the same root cause as #195, we will look into it.
