### ISSUE TITLE
Card Page in "view" mode has editable fields

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#1960]
When I create a new page and define "non table bound" fields on the page, they do not get the "Editable/View" state from the rest of the page. So, when I open the page and it's in edit mode, all fields are editable. When I click on "Edit" to change it to the view mode, all table bound fields become non editable, but the "variable fields" remain editable. this should not happen in my eyes.

Example page:

```
page 50100 test
{
    PageType = Card;
    SourceTable = Customer;
    UsageCategory = Administration;
    ApplicationArea = All;
    Caption = 'Editable Test';

    layout
    {
        area(Content)
        {
            field("No.";"No.")
            {
                ApplicationArea = All;
            }
            field(Name;Name)
            {
                ApplicationArea = All;
            }
            field(TField;TField)
            {
                Caption = 'This is a test field';
                ApplicationArea = All;
            }
        }
    }
    var
        TField : Text[50];
}
```

Go to search, look for "Editable Test" and then click on "Edit" to see the state change.

**Comment by StanislawStempin** [comment]
Is this different from a behavior of page created in C/SIDE?

**Comment by TKapitan** [comment]
It is the same behavior as in C/SIDE.

**Comment by pzentner** [comment]
It is the same behavior, but that doesn't mean it is the correct behavior. Was the question how it behaves in C/SIDE to determine, if this issue has to go to the "client team" or stay with AL or was it to determine, if anything is going to be done at all?

Just trying to see, if we have to validate the behavior in C/SIDE and if there is no difference not even bother submitting it or submit it differently or somewhere else or if we should still submit everything through here.

From my point of view, it is something wrong with the software, so it needs to be addressed, but I would like to submit it to the right team.

**Comment by StanislawStempin** [comment]
@pzentner - yes, this was to determine if the issue is related to Client team. 
@TKapitan - since it is not related to AL you need to file a support request through official channels.
