### ISSUE TITLE
Action Groups in menu on Role Center

### ISSUE THREAD

**Issue by vitaliizz** [Microsoft/AL#1961]
Is there any way to group menu actions similar to "Manual Setup"?

![image](https://user-images.githubusercontent.com/37546680/38458404-a1862a88-3aa6-11e8-9a08-033161a2ea68.jpg)

I expect to see "Sales Group" as an Action Group which I can expand/collapse to show/hide "Sales Orders Test" action when I write the code below. Right now "Sales Group" is simply ignored.
![image2](https://user-images.githubusercontent.com/37546680/38458432-089bbb98-3aa7-11e8-9b4d-9fbc752edf20.jpg)

Thanks

**Comment by StanislawStempin** [comment]
I reached out for input to the owning team

**Comment by StanislawStempin** [comment]
Here is the related documentation from MSDN.

https://docs.microsoft.com/en-us/dynamics-nav/setting-up-the-home-button-and-home-items

An item is automatically positioned as a child to another item according to the following conditions:
- The child item targets a list page that displays filtered data from a table.
- The parent item targets the same list page as the child item, except that list page data is not filtered.
- The parent item is defined by an action, not a Cue.
