### ISSUE TITLE
VSCode editor lookup use the wrong field names on existing CalcFormula in where(...)

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1965]
VSCode editor lookup use the wrong field names on existing CalcFormula in where(...). Expected are Target-Table FieldNames and not the SourcTable FieldNames:
![grafik](https://user-images.githubusercontent.com/15800069/38484843-259663e2-3bd8-11e8-9b24-0b600d4f0301.png)

My VS-Code & AL Version:
![grafik](https://user-images.githubusercontent.com/15800069/38484829-1ebedaea-3bd8-11e8-8ffe-d9c4a1f5d2ba.png)
![grafik](https://user-images.githubusercontent.com/15800069/38484837-220e5400-3bd8-11e8-9ef8-22eb9ad641ff.png)

The test project:
[Microsoft AL [Lookup CalcFormula].zip](https://github.com/Microsoft/AL/files/1888816/Microsoft.AL.Lookup.CalcFormula.zip)

**Comment by kalberes** [comment]
"Name" and "Code" are fields from your "My Table 1". A CalcFormula's where expression's left hand side are the fields from the "My Table 1".
<CalculationFormula> ::=  
    [-]Exist(<TableNo> [WHERE (<TableFilters>)]) |  
    Count(<TableNo> [WHERE (<TableFilters>)]) |  
    [-]Sum(<TableNo>.<FieldNo> [WHERE(<TableFilters>)])|  
    [-]Average(<TableNo>.<FieldNo> [WHERE (<TableFilters>)]) |  
    Min(<TableNo>.<FieldNo> [WHERE (<TableFilters>)]) |  
    Max(<TableNo>.<FieldNo> [WHERE (<TableFilters>)]) |  
    Lookup(<TableNo>.<FieldNo> [WHERE (<TableFilters>)])  
<TableFilters> ::=  
    [<TableFilter> {,<TableFilter>}]  
<TableFilter> ::=  
    <DstFieldNo>=CONST(<FieldConst>) |  
    <DstFieldNo>=FILTER(<Filter>) |  
    <DstFieldNo>=FIELD(<SrcFieldNo>) |  
    <DstFieldNo>=FIELD(UPPERLIMIT(<SrcFieldNo>)) |  
    <DstFieldNo>=FIELD(FILTER(<SrcFieldNo>)) |  
    <DstFieldNo>=FIELD(UPPERLIMIT(FILTER(<SrcFieldNo>)))

**Comment by megel** [comment]
Yes "My Table 1" is correct. 
Sorry, my fault - as I have tested it my VS Code was on a different Version.
