### ISSUE TITLE
Event Request for "SynchronizeWhseActivItemTrkg" function in CU_6500 - Item Tracking Management

### ISSUE THREAD

**Issue by krishnaGottuparthi** [Microsoft/AL#1966]
We have a customization which needs to fill fields in "TempReservEntry" record variable, so we request to have a event trigger with 2 parameters (WhseActivLine[with VAR] , TempReservEntry(With VAR)), as shown in below screen shot.

![image](https://user-images.githubusercontent.com/35251581/38493957-a97ef2b2-3c11-11e8-8d59-36d31e1ce939.png)

**Comment by StanislawStempin** [comment]
We already have this event:
 OnSyncActivItemTrkgOnBeforeInsertTempReservEntry(TempReservEntry,WhseActivLine);
