### ISSUE TITLE
Change field visible property dynamically in a PageExtension 

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1969]
I was sure I had seen this discussion somewhere before but I cannot find it.  So if this is an old topic I apologize and please provide the link to the discussion.

Is ir possible to dynamically change the visible property of a field that is added in a pageextension?  

I have a number of places where I want to reuse a visible property variable from the base page but those variables are not accessible in the PageExtension.  I can live with that but I can find no way to do this in a PageExtension as no event allows access to the variables of the base Page or the PageExtension.  

I can't be the only one that has run into this.  What have others done to do this?

**Comment by megel** [comment]
Hi @GreatScott000, 

yes you can switch the visibility of added fields in a `pageextension` (don't forget to wrap the fields in groups - see https://github.com/Microsoft/AL/issues/1752 )

If you want to Show/Hide an existing field, you have to move this field into a group, e.g.:
```javascript
pageextension 50100 "Item Card Ext" extends "Item Card"
{
    layout
    {
        addafter(item)
        {
            group(GrpItem)
            {
                Caption = 'Item Description';
                Visible = mIsSpecial;
                group(Marker) { }
            }
        }

        // move the existing field into the greated behind the marker :)
        moveafter(Marker; Description)
    }        
    var mIsSpecial: Boolean; 

    trigger OnAfterGetCurrRecord()
    begin
        mIsSpecial := true // or false;    
    end;
}
```

But I agree with you, in some cases the existing variables should at least be **read-only** e.g. readonly Properties in C#.

**Comment by ajkauffmann** [comment]
See also this issue: https://github.com/Microsoft/AL/issues/593

**Comment by StanislawStempin** [comment]
It is not possible to access properties on the base page right now. The suggestion linked by AJ is tracking the longer-term improvement of introducing 'protected' visibility.
