### ISSUE TITLE
Event Request: Codeunit 841 Cash Flow Management

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/AL#1970]
We would like to request 2 new Event Publishers in **Codeunit 841 Cash Flow Management**

1. Called from ShowSourceDocument(CFVariant : Variant)
    **_OnBeforeShowSource(CFVariant, TRUE, IsHandled);
    IF IsHandled THEN
      EXIT;_**

2. Called from ShowSource(CFVariant : Variant)
    **_OnBeforeShowSource(CFVariant, FALSE, IsHandled);
    IF IsHandled THEN
      EXIT;_**

Suggestion as Call to Event Publisher:

**_LOCAL [IntegrationEvent] OnBeforeShowSource(CFVariant : Variant;ShowDocument : Boolean;VAR IsHandled : Boolean)_**

This way we can include our ISV part to the Cash Flow functionality without changing standard code

Thanks,

**Comment by StanislawStempin** [comment]
From Alexander:
We already have such events here and they do the same:
 
ShowSourceDocument(CFVariant : Variant)
OnBeforeShowSourceDocument
(CFVariant,Handled);

IF
Handled THEN


EXIT;

 
ShowSource(CFVariant : Variant)
OnBeforeShowSource
(CFVariant,Handled);

IF
Handled THEN


EXIT;

**Comment by ptijsma** [comment]
Hi Stanislaw,

Can you tell me in which build this is in?
Just checked build 12.0.21229, but there it's not in.

Thanks,
/Peter

**Comment by ptijsma** [comment]
Just checked build 21617 and found it in there :-)

Thanks!
