### ISSUE TITLE
Business/Integration event signature change: triggering a compilation error at runtime

### ISSUE THREAD

**Issue by demiliani** [Microsoft/AL#1972]
Actually, if you modify in NAV a Business or Integration event signature (parameters), a subscriber to this event (that was not updated with the new event signature) is not triggered anymore and no compilation error is thrown.
More details here:
https://demiliani.com/2018/04/09/nav-events-the-strange-behaviour-that-i-hate/

This is dangerous for certain business process results and a frequent source of "hidden errors" when working with distributed developer teams.
Any chance to have compilation error when an event signature changes and there's a subscriber that has parameters mismatch? 
Checking the Event Subscription view is not enough.

**Comment by KristofKlein** [comment]
Yes! This became also here a joke(r) answer: "have you checked your event is still active!?". Which part of the Engine takes care to set the flag in the Svent Subscription list? or is it filled while opening? 
Anyhow a hint or list about linked events that potentially can be damaged would be a really nice help.

**Comment by StanislawStempin** [comment]
This is actually checked by the new compiler. We have no plans of fixing it in C/SIDE.

**Comment by demiliani** [comment]
Not a good news... this could cause problems in classic NAV.

Il 10 apr 2018, 19:42 +0200, Stanislaw Stempin <notifications@github.com>, ha scritto:
