### ISSUE TITLE
SID and SETUSERPASSWORD

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1973]
I have a client, for whom were are writing an extension, that has >100 users that need to be added to the system .  In the past I have used the SID and SETUSERPASSWORD functions to assist in create users from an XMLport and data file.  These functions are not currently supported in AL.

Will they be in the future?

**Comment by StanislawStempin** [comment]
It is not supported to create users in Business Central from extension code. All users must be created in Azure AD using the portal or the API here: https://graph.microsoft.io

**Comment by waldo1001** [comment]
Are there examples of this?  No clue where to begin ...

**Comment by SBalslev** [comment]
Look graph.microsoft.io. Lots of examples for maybe different tasks.
Here's how you create users: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_post_users
