### ISSUE TITLE
CodeCop Descriptor AA0139 doesn't take the MaxLength of a label in consideration

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1977]
Hi,

Descriptor AA0139 doesn't take the MaxLength into consideration, like you see on this screenshot:

![image](https://user-images.githubusercontent.com/12088142/38558039-36a5e778-3ccf-11e8-8547-39f1ce8d4c8c.png)

**Comment by waldo1001** [comment]
@DominikDitoIvosevic,

ok, sorry about that :-).  
I'm not sure I'm using the latest build now (just updated to docker image "bcinsider.azurecr.io/bcsandbox:be" with al extension version "al-0.15.19352.vsix").

Same problem though:
![image](https://user-images.githubusercontent.com/12088142/38563932-52ae2dae-3cde-11e8-872b-75210e5560fe.png)

**Comment by StanislawStempin** [comment]
This is not shipped yet. You would either need a daily Docker build from today or wait until May dev preview update.

**Comment by waldo1001** [comment]
I used the image from "bcinsider.azurecr.io/bcsandbox-master:be" (I was told that is the daily build).
that's al-0.15.19171.vsix (which seems to be newer than al-0.15.19352.vsix because it's the daily build :-/).

But I can't test that, because of this error:
![image](https://user-images.githubusercontent.com/12088142/38601106-cd63beb4-3d66-11e8-8cb6-80edc0b3f0a1.png)

I guess I'll wait for another build ;-)

**Comment by DominikDitoIvosevic** [comment]
@waldo1001 I can't repro this anymore on the latest master. Please ping us here if there are more issues but I would expect this to work for you on the latest build
