### ISSUE TITLE
RENAME trigger does not propagate to table extensions of extensions

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#1978]
Hello,

if you create a new table object (via extension) and then extend it with another dependent extension, the RENAME trigger is not propagated:

1) Change primary key value in the original table
2) "Rename record?" dialog appears
3) Confirm
4) The original table has the value changed but the dependent tables not
5) Now the DB is inconsistent and various errors appears, because inserting the old key value generates a duplicate key in dependent table

Please fix ASAP.
S.

**Comment by cmrudolph-msft** [comment]
Can you please provide a more detailed repro scenario (with a relevant code snippet)? I ask because I cannot find any problems with rename in the following circumstances:

1. Base table extended by an extension (the PK in both tables updates fine)
2. Extension table extended by another extension (same as above)

Keep in mind, I am referring here to the integrity of the system-managed "companion" tables that hold data for table extension fields. I suspect there is more to your scenario than this, like perhaps:

- Is trigger code being added anywhere (the subject suggests yes)?
- Are table relationships involved?

**Comment by sgiordy** [comment]
Hi @cmrudolph-msft 

Unfortunately there is no trigger or table relationships involved.
Here the screenshot sequence:

**Insert the first value**
![screen1](https://user-images.githubusercontent.com/17341714/38750709-15f9af62-3f56-11e8-88c5-16e5a9cc27c7.JPG)

**Rename and confirm**
![screen2](https://user-images.githubusercontent.com/17341714/38750712-1615f35c-3f56-11e8-9cce-345482c6a7a4.JPG)

**Note the strange warning in the page that informs that the record is out of filter, but no filter is applied**
![screen3](https://user-images.githubusercontent.com/17341714/38750713-16328792-3f56-11e8-90ae-50bbb7b17a6b.JPG)

**Database is inconsistent between table and its extension***
![screen4](https://user-images.githubusercontent.com/17341714/38750714-1651c382-3f56-11e8-948a-2c7512ebe995.JPG)

The tables are simply defined as:

```
table 83000 "EDI Profile"
{
    CaptionML = ENU='EDI Profile', 
                ITA='Profili EDI';
    DataPerCompany = true;

    fields
    {
        field(1; "Code"; Code[10])
        {
            CaptionML = ENU='Code', 
                        ITA='Codice';
        }
        field(4; "Description"; Text[30])
        {
            CaptionML = ENU='Description', 
                        ITA='Descrizione';
        }        
        field(5; "Codeunit ID"; Integer)
        {
            CaptionML = ENU='Codeunit ID', 
                        ITA='ID codeunit';
            TableRelation = AllObj."Object ID" where ("Object Type" = const(Codeunit));
            ValidateTableRelation = true;
        }
        field(6; "Setup Page ID"; Integer)
        {
            CaptionML = ENU='Setup Page ID', 
                        ITA='ID pagina setup';
            TableRelation = AllObj."Object ID" where ("Object Type" = const(Page));
            ValidateTableRelation = true;
        }
        field(42; "Inbound Folder"; Text[250])
        {
            CaptionML = ENU='Inbound Folder',
                        ITA='Cartella ingresso';
        }
        field(43; "Outbound Folder"; Text[250])
        {
            CaptionML = ENU='Outbound Folder',
                        ITA='Cartella usicta';
        }
    }

    keys
    {
        key(PK; "Code")
        {
            Clustered = true;
        }
    }
}
```

```
tableextension 83416 T83416 extends "EDI Profile"
{
  fields
  {
    field(83400; "Mapping XML"; Blob)
    {
      CaptionML = ENU='Mapping XML',
                  ITA='XML mappatura';
    }
  }
}
```

**Comment by cmrudolph-msft** [comment]
Thanks for the extra detail. The key factor in reproducing the problem was making sure the table extension ONLY adds fields of type BLOB. There is a low-level platform defect in the way this special scenario is handled. I have made the fix and will get it into the relevant releases.
