### ISSUE TITLE
Developer Preview initialization failed

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#1979]
Hi there!

I get an error on the Developer Preview Image (create this day for the W1 version).

`Error: "Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."`

How can I solve this issue?

![image](https://user-images.githubusercontent.com/28626283/38564795-204b65be-3ce0-11e8-907b-b8e493463265.png)

**Comment by StanislawStempin** [comment]
I moved your issue to NavDocker GitHub
