### ISSUE TITLE
TableRelation intellisense has the values backwards

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#1981]
When I'm creating a field and adding a table relation.

The first part of the where clause pulls up fields from _my_ table, but it should be pulling fields from the to table. (Item Journal Batch in this example)
Similarly the second part is flipped too.

eg, the values supplied by intellisense won't compile.

![image](https://user-images.githubusercontent.com/7827702/38571765-490f473e-3ca6-11e8-9c10-81100dcc0ae0.png)

**Comment by kalberes** [comment]
What do you mean by second part? The Right Hand Side of the where expression?

**Comment by reiniroosh** [comment]
Yes, that's right. Within the `field(...)` it pulls fields from the "other" table.

**Comment by linasostreika** [comment]
Hi Guys, is this bug fixed already? I have the same issue. #2267

**Comment by alvarotellez** [comment]
Hello @linasostreika  Ive the same problem. Do you know something about this bug?

Thank you

**Comment by kalberes** [comment]
As far as I know it has been backported and thus it should be available in the next CU of Nav 2018

**Comment by linasostreika** [comment]
hi @alvarotellez, i have no updates on this issues, i hope it will be fixed soon, cause it is very annoying. If you will learn anything about this, please, share with me, thanks in advance.
