### ISSUE TITLE
Availability of encryption functions directly native for streams and texts.

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1985]
I have a general question about encryption. NAV already supports encryption at some points, but this is only relevant for data and not for processing. There is already an Encryption Handler via the CAL Open Library, but this supports only the standard system encryption. What would be desirable here would be that texts and streams about all available encryption algorithms, which are standard in .NET, are made available here. It must be possible to read and write encrypted data. This must be possible both symmetrically and asymmetrically. Which is why I'm inserting the point here. In my opinion, it would be good if the system could make these options available natively. In this case, for example, a wrapper via the .NET CryptoTransformations. This could then be used to connect almost all encryptions. It would be very good if you could use this to map data security.

**Comment by Gallimathias** [comment]
I would more than support the request for a wrapper for the complete Crypto API from.NET.

**Comment by naradae** [comment]
We also need this. Couple of use cases so far where we have needed this:
- Calculating the HMAC-SHA256 for authorization to Azure storage services (because we are not able to use the .net azure services SDKs)
- Validating server-signed license keys to ensure customers are licensed to use our apps

**Comment by kalberes** [comment]
There is some support in the https://github.com/microsoft/BCApps/tree/8e28ce05e86decb29dd6e0645cc5ccdd64517077/src/System%20Application/App/Cryptography%20Management
Being an open source project new additions can be added
