### ISSUE TITLE
What is the Procedure to add own event and Subscribe in AL Environment?

### ISSUE THREAD

**Issue by shalu712** [Microsoft/AL#1987]
Hi Team ,
I have Published few events in FOB and raised request to same in GitHub, I am trying to subscribe my created events in AL environment getting below error.
![image](https://user-images.githubusercontent.com/36455082/38607789-3d8f4b6a-3d97-11e8-8a9d-dfe7285ef247.png)
Please note  below mandatory setup are also done .
![image](https://user-images.githubusercontent.com/36455082/38607857-69cfde38-3d97-11e8-8628-91b8db7e1c52.png)
Please suggest how to proceed ?

**Comment by thpeder** [comment]
Hi @shalu712,
It sounds like your symbols doesn't contain your new events.
Take a look at the links under "Hybrid development with C/SIDE and VS Code" in this wiki site: [Useful resources](https://github.com/Microsoft/AL/wiki/Useful-resources)
