### ISSUE TITLE
Txt2Al conversion error - RunPageLink filter on numeric value

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#199]
The Txt2Cal conversion incorrectly put quotation marks around my numeric filter value in the RunPageLink property of a sub-page.

What it gave me was this:
`RunPageLink="Recipe No."=FIELD("No."),"Recipe Line No."=CONST("0");`

There should be no quotes around the 0, like this:
`RunPageLink="Recipe No."=FIELD("No."),"Recipe Line No."=CONST(0);`

**Comment by atoader** [comment]
The issue should be fixed in the next release of the tool.

**Comment by atoader** [comment]
The issue should be fixed in the next release of the tool.
