### ISSUE TITLE
Overload compile error AL0155

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#1992]
I've created a few overloads. VS code doesn't complain about them and I can call them in code with the different parameters. But when I try to compile and push the extension to the NAV2018 CU3 service, it throws 'error AL0155: A member with name 'MyMethodName' is already defined'.

![image](https://user-images.githubusercontent.com/14080280/38617735-0f8e6844-3d98-11e8-8739-09fdcf476c21.png)

**Comment by DennisReinecke** [comment]
Was facing the same issue some time ago.
CU03 is only AL Language 0.12.17720 and method overloading is not supported.
also JSONObject.Keys() is missing.

**Comment by erikrijn** [comment]
That's quite tricky if you want to write an extension for NAV2018, but you need to specify that it's only compatible with CUx or higher. You'll always have to write against RTM compatibility to be safe and have it work in all customer installs instead.

**Comment by StanislawStempin** [comment]
Currently we don't support using only the latest AL Language against multiple server versions. You will run exactly into issues like you did. You need to match the AL Language version with the server version, see: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

The long term plan is to allow to use the latest AL Language from VS Code gallery to work against multiple server versions and adapt to the feature set supported by the given server.

**Comment by erikrijn** [comment]
I understand what is happening, and why. It would be nice if the AL version could be downloaded from the server together with the symbols. That way VS could warn about incompatibly before publishing.
