### ISSUE TITLE
Empty Page in Version 12.0.0.0

### ISSUE THREAD

**Issue by aproehl79** [Microsoft/AL#1996]
When using the Custom Page sample from https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-object with version "12.0.0.0",  an empty page is shown.
I have this behavior both at cloud sandbox and local container. When publishing to an 11.0.0.0 environment (local container) the page is shown as expected.

````javascript
page 50000 SimpleCustomerCard
{
    PageType = Card;
    SourceTable = Customer;

    layout
    {
        area(content)
        {
            group(General)
            {
                field("No.";"No.")
                {
                    CaptionML = ENU='Hello';

                    trigger OnValidate()
                    begin
                        if "No." < '20' then
                            Message('Number too small')
                    end;
                }

                field(Name;Name) {}
                field(Address;Address) {}
            }
        }
    }
    actions
    {
        area(Navigation)
        {
            action(NewAction)
            {
                RunObject = codeunit "Document Totals";
            }         
        }
    }
}
````
![screenshot](https://user-images.githubusercontent.com/16100797/38667089-d6784e5e-3e40-11e8-9845-d57c7965c5ca.png)

**Comment by thpeder** [comment]
Hi @aproehl79,
You are missing the application area. Insert ApplicationArea = All; in the controls and actions.

**Comment by aproehl79** [comment]
Hi @thpeder,

thank you for your fast support. This was the missing property. The sample on  https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-object should be updated too. Also the txt2al converter not setting this property. It seems that the ApplicationArea could be empty in older version.
