### ISSUE TITLE
TableExtension using field with AutoIncrement

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1997]
For NAV 2018 CU03 OnPrem

I am trying to add an integer field with `AutoIncrement = true;` to a base NAV table in a TableExtension.  This compiles fine but when I try to publish the app (F5/Ctrl+F5) the publish fails with the following messages:
```
[2018-04-12 10:15:50.93] Sending request to http://localhost:7049/al20783/dev/apps?SchemaUpdateMode=recreate
[2018-04-12 10:15:55.84] The request for path /al20783/dev/apps?SchemaUpdateMode=recreate failed with code InternalServerError. Reason: An error has occurred.

```
![image](https://user-images.githubusercontent.com/4333956/38667886-9483759c-3e3a-11e8-84d1-d0ee26797330.png)

There is nothing in the event log.  

Is this not supported?
Is this a bug?
Please advise.

**Comment by GreatScott000** [comment]
I must have missed this in the Event Viewer earlier.
` Cannot insert the value NULL into column 'ID', table 'Extx PDI Upg.dbo.Project Development  Int Ltd$Time Sheet Detail$29f9ab83-38dd-4e5d-82f9-d3b2eb95e1f0'; column does not allow nulls. INSERT fails.
`
Which I guess makes sense, HOWEVER, if I do this in C/SIDE then the field is added is automatically populated.  

Why would this be different in AL?

**Comment by atoader** [comment]
Hi @GreatScott000 ! In the latest release you will get an error saying: "Property 'AutoIncrement' is not allowed on a table extension". @HunterFeltman-MSFT can give a good explanation on why this is the case.

**Comment by HunterFeltman-MSFT** [comment]
The NAV platform cannot/does not at current support multiple 'AutoIncrement' fields on a given table. Since there could be multiple table extensions for a table, all installed at the same time on a tenant, and each of these could have added an AutoIncrement field, the decision was to block its use.

**Comment by GreatScott000** [comment]
Can you at least enhance the error checking to capture this issue?

**Comment by HunterFeltman-MSFT** [comment]
As indicated by @atoader, in the latest release of the AL compiler/VSCode this property is not allowed for modification and the compiler will spit out appropriate errors.

@atoader @StanislawStempin - I don't know which version of the compiler bits was deployed for NAV2018 CU3 OnPrem, is there an update in the works?

**Comment by StanislawStempin** [comment]
The compiler check is implemented as of CU5.
