### ISSUE TITLE
Make GetStatisticsStartDate in Table:Intrastat Jnl. Batch External

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#1999]
The function:GetStatisticsStartDate of Table:Intrastat Jnl. Batch is used in Report:594.
For our App we need to change this report. So made a copy :( of this report but using GetStatisticsStartDate isn`t allowed because it isn't external.

**Comment by JesperSchulz** [comment]
I will expost that function for you. Thanks for reporting!
