### ISSUE TITLE
Server File Mangement functions not supported in Extentions

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#200]
In **Extension 2.0** it is not possible to use several functions in the FileMangement (419) codeunit:

**The type or method 'ServerCreateDirectory' cannot be used for 'Extension' development**

Other functions we need:
- GetExtention
- DeleteServerFile
- ServerTempFileName

Maybe it's an idea to support **Azure Blob storage** to store tenant specific files?

Note that we talked already with **esbenk** (in Denmark) about this during the WoW Workshop.

**Comment by StanislawStempin** [comment]
We will look into unblocking some of the APIs or providing equivalent functionality. 
Tighter Azure Blob Storage integration is an interesting suggestion.

**Comment by pborring** [comment]
I am going to close this rather old feedback item, and propose opening separate ideas on http://aka.ms/bcideas to track this instead, as not related specifically to the developer tools, but runtime and integration.
