### ISSUE TITLE
Question: Extending third party add-ons

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#2000]
Situation: A NAV 2018 CU3 install that includes a third party certified add-on.
Wish: Extending the third party add-on with a few extra fields in their tables and pages.

When I download the symbols in VS Code, it won't let me extend (for example) table 11260662 while that table is available in the c/side environment and it's in the active license. Is this unsupported? And if so, are there plans to support this in the future?

**Comment by StanislawStempin** [comment]
By third party certified add-on do you mean Extension V1? 
Mixing Extensions V1 with Extensions V2 is not supported. You can only mix base application C/SIDE changes with Extensions V2.
