### ISSUE TITLE
Event request to skip sales lines in Sales Post codeunit

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2001]
we need an event to skip some sales lines which we are inserting in our extension in standard process.

something like 
OnBeforeProcessingSalesLines(SalesLines); where SalesLines parameter is passes as Reference

Onrun function
![image](https://user-images.githubusercontent.com/23735402/38673553-478d2c30-3e6f-11e8-869b-efe982f7d733.png)

CalcInvoice function
![image](https://user-images.githubusercontent.com/23735402/38674067-cf0ecd5c-3e70-11e8-8a29-a88ed3ba3eb3.png)

CalcInvDiscount function
![image](https://user-images.githubusercontent.com/23735402/38674130-0378e7e4-3e71-11e8-9238-5396459cafca.png)

UpdateAssosOrderPostingNos function
![image](https://user-images.githubusercontent.com/23735402/38674676-e60dbf2a-3e72-11e8-951d-d45d75a8950a.png)

SumSalesLines2 function
![image](https://user-images.githubusercontent.com/23735402/38674813-5aee17ae-3e73-11e8-9683-99d889e546ca.png)

FindNotShippedLines function
![image](https://user-images.githubusercontent.com/23735402/38674881-a68c43de-3e73-11e8-9cc5-3a3a821a4bc6.png)

CheckTrackingAndWarehouseForReceive function
![image](https://user-images.githubusercontent.com/23735402/38675096-510cf7fe-3e74-11e8-94b3-d9ed17cbfeaa.png)

**Comment by AlexanderYakunin** [comment]
Can you design your solution differently, probably you don't need to have this information in sales lines but can keep it in extra table related to sales lines?

**Comment by pmohanakrishna** [comment]
we are showing grouping lines in sales lines and showing underlying detail lines with an action.
off course, both are sales lines only.
we need to spend months to redesign this change.
