### ISSUE TITLE
Permission set not exported as XML as indicated in documentation. Fix and documentation update needed

### ISSUE THREAD

**Issue by Addice73** [Microsoft/AL#2005]
Exporting the permission sets as indicated [in checklist ](https://docs.microsoft.com/en-gb/dynamics-nav/how-to--import-export-permission-sets-permissions)
“To export the permission sets' XML file, run XMLport 9171 Import/Export Permission Sets ,”

a CSV file is created instead of the expected XML file

At compile time we get the error:

> Project\Permissions\permission-sets.xml, due to the following error: Rilevati dati non validi al livello radice. Riga 1, posizione 1.'.
> warning AL1026: An error occurred during XML validation: 'Cannot load the web service at the specified location, c:\Users\adiceglie\Desktop\Repo\Eos.NavExtension.HistoricalExchangeRates\Main Project\Permissions\permissions.xml, due to the following error: Rilevati dati non validi al livello radice. Riga 1, posizione 1.'.
> Success: The package is created.

Modifiyng the xmlPort 9171  to produce an XML at compile time we get the error:

```
warning AL1025: The file at location 'c:\Users\xxx\Desktop\Repo\Eos.NavExtension.HistoricalExchangeRates\Main Project\Permissions\permission-sets.xml' does not match any definition.
warning AL1025: The file at location 'c:\Users\xx\Desktop\Repo\Eos.NavExtension.HistoricalExchangeRates\Main Project\Permissions\permissions.xml' does not match any definition.
Success: The package is created.

```

**Comment by StanislawStempin** [comment]
Please try using the approach described here: 
https://docs.microsoft.com/en-us/dynamics-nav/how-to-export-data-for-an-extension
The information is still relevant for Extensions V2, we are working on updating the documentation.
