### ISSUE TITLE
Dynamics NAV 2017 - Extensions V1 issue when Uninstall-NavApp is used. 

### ISSUE THREAD

**Issue by robertintergen** [Microsoft/AL#2009]
Hello,

   Problem with printscreens below: 
   - When trying to uninstall a standard app Sales and Inventory Forecast v1.0.0.0 I get an error that "the following SQL Error was unexpected: Invalid Column Name 'Has Sales Forecast'" 
   Tried the following:
   - syncing object metatada from both dev client and PS with both force and without
   - uninstalling from PS with -DoNotSaveData, same error pops up
   - a few other tests and workarounds that didn't work.
   Other observations:
   - the field is not present on the Item table in SQL because it is an extension field.
   - the extension look like it is installed.
   - the same CU11 for NAV 2017 doesn't have this problem in the UAT database, only in Development

![image](https://user-images.githubusercontent.com/24398648/38712316-e5483bc2-3f1e-11e8-80e9-611842c477d5.png)
![image](https://user-images.githubusercontent.com/24398648/38712338-07b26cd2-3f1f-11e8-816d-d0f3acd9edd9.png)

Cheers,
Robert

**Comment by StanislawStempin** [comment]
Please open a regular support case through NAV 2017 channels. This is not related to AL Development Preview releases.
