### ISSUE TITLE
RecordRef 'The type or method 'Open' cannot be used for 'Extension' development.'

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#201]
At this moment it is not possible to use Record Reference in Extension 2.0.

`RecordRef.OPEN(TableNo)
`

Is it possible to support this?

**Comment by kalberes** [comment]
Not really for now. But we should probably consider having support for an Open method that could be tenant only specific. We need to investigate our options.

**Comment by bvbeek** [comment]
Why not really for now? It's the way to program generic stuff. We will need it.

**Comment by waldo1001** [comment]
If you don't enable this, any "decent" generic solution is going to be difficult (read: not possible).
In my opinion it is very necessary to have this (or something similar)

**Comment by StanislawStempin** [comment]
After further investigation we decided to re-enable this API.

**Comment by waldo1001** [comment]
Very good decision! ;-)

**Comment by bvbeek** [comment]
Awesome! Thank you Microsoft!

**Comment by bvbeek** [comment]
@StanislawStempin Can we expect this feature in the July update? We miss it in the June update.

**Comment by StanislawStempin** [comment]
Yes, it will be available in the July Update. 
You can see the milestone marked on individual issues or go to the milestone itself to get an overview of what will be delivered:
https://github.com/Microsoft/AL/milestone/7

**Comment by bvbeek** [comment]
Thanks for your quick response!

**Comment by ewaldventer** [comment]
Awesome! 
Would've been quite a headache if the restriction was left as is.
