### ISSUE TITLE
New function request: GETCALLSTACK

### ISSUE THREAD

**Issue by ptijsma** [microsoft/AL#2019]
I've posted it on Yammer on November 1st, 2017, but not sure if anyone seen it.
(see https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=974473209)

I would like to vote for a new function, accessible from AL called GETCALLSTACK.
The function should be similar to GETLASTERRORCALLSTACK, but then accessible whenever needed, without throwing an Error first.

When using events, it would be very benificial to find out from where the event was originated through the callstack.
My current solution (fully .Net based in C/AL) will of course not work anymore in AL.

![image](https://user-images.githubusercontent.com/18245218/38737417-6b82436c-3f2f-11e8-84bd-301d8c0f4a55.png)

And using a TryFunction with explicit Error and then GETLASTERRORCALLSTACK is not the right way to go from my opinion.

Even worse: It's not even allowed anymore to use TryFunctions in AL, so there's not even an alternate solution right now :-(

**Comment by redIT-LoPf** [comment]
We are looking too for a possibilty to get the callstack. A command like requested would be very helpful.

**Comment by ptijsma** [comment]
Any news on this issue?

**Comment by ernestasjuska** [comment]
Hi, I can also add that there is a platform function like that and it is used for GetLastErrorCallStack().

In assembly Microsoft.Dynamics.Nav.Ncl.dll there is an internal function NavSession.GetCurrentCallStack().
I used it through an add-in to log call stacks when logging record changes.

```c#
using Microsoft.Dynamics.Nav.Runtime; // need to reference Microsoft.Dynamics.Nav.Ncl.dll
using System;
using System.Reflection;

namespace NavCallStack
{
    public class NavCallStack
    {
        public string GetCurrentCallStack()
        {
            MethodInfo methodInfo =
                typeof(NavSession)
                .GetMethod(
                    "GetCurrentCallstack", BindingFlags.NonPublic | BindingFlags.Instance, null, new[] { typeof(Func<NavApplicationObjectBase, string>) }, null);
            if (methodInfo == null)
                throw new NullReferenceException("Could not find method NavSession.GetCurrentCallstack(Func<NavApplicationObjectBase, string>).");
            return (string)methodInfo.Invoke(NavCurrentThread.Session, new object[] { new Func<NavApplicationObjectBase, string>(a => a.ObjectName) });
        }
    }
}
```

Example output:
```text
"My Call Stack Demo"(CodeUnit 50100)."(Page Call Stack Demo) MyEvent" line 4 - CallStackDemo by Default publisher
"Call Stack Demo"(Page 50100).MyEvent(Event) line 2 - CallStackDemo by Default publisher
"Call Stack Demo"(Page 50100).OnOpenPage(Trigger) line 2 - CallStackDemo by Default publisher
```

**Comment by pborring** [comment]
Closing, tracked in idea
https://experience.dynamics.com/ideas/idea/?ideaid=84d8ed18-5a7f-ec11-b820-0003ff45920b

**Comment by navdotnetreqs** [comment]
Still relevant and should be simple enough to implement since it already exists, just not available..

**Comment by ViktorasDanielius** [comment]
It is now possible using command SessionInformation.Callstack
https://yzhums.com/63662/
