### ISSUE TITLE
We need access to the Field table (2000000041)

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#202]
In Extension 2.0 it is not possible to access the field table 2000000041

Now we get this error: `'The type or method 'Field' cannot be used for 'Extension' development.'
`

Please can you made this possible? 
Or is there an other way to access it?

**Comment by waldo1001** [comment]
I found this:
https://github.com/Microsoft/AL/issues/184

So may be next version..

**Comment by bvbeek** [comment]
Ok, nice!

Thanks!

**Comment by kalberes** [comment]
Well, #184 will just fix an issue in our reference loading logic. It is still discussed whether the Field virtual table should be allowed for extension.

**Comment by waldo1001** [comment]
Discussion?  It's quite necessary to build any generic solution ... (obviously together with RecRef/FieldRef)

**Comment by bvbeek** [comment]
I totally agreed with waldo, please add this a.s.a.p.

**Comment by StanislawStempin** [comment]
Field table will be available in May Update.

**Comment by bvbeek** [comment]
Thank you to make this possible!
