### ISSUE TITLE
Cookie Container

### ISSUE THREAD

**Issue by Kowa63** [microsoft/AL#2020]
I'm looking for a way to handle cookies in AL. In C/AL you can use the .NET CookieContainer 
https://msdn.microsoft.com/en-us/library/system.net.cookiecontainer(v=vs.110).aspx
`DotNet "'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Net.CookieContainer`
Is anything planned in that direction?

**Comment by StanislawStempin** [comment]
It is on our backlog but not the highest priority at the moment.

**Comment by ERPgruppenMW** [comment]
Any news on this issue - is it resolved?

**Comment by pborring** [comment]
It is not resolved, and currently not in scope for the upcoming spring release. Scope for fall release is not settled yet.

**Comment by NS-NN** [comment]
Hi,
Long time ago since this article has been updated.
Anything new?

**Comment by pborring** [comment]
Plans to add more HttpClient capabilites in fall release, but not groomed/settled yet. Proxy and better cookie support high on the list, but latter might not include container initially, 

See also related asks
https://github.com/Microsoft/AL/issues?utf8=%E2%9C%93&q=is:open+is:issue+label:http-client
Cookies - https://experience.dynamics.com/ideas/idea/?ideaid=6e80f42d-8b43-ea11-b698-0003ff68dcf8
Proxy - https://experience.dynamics.com/ideas/idea/?ideaid=9545da70-666f-eb11-8fed-0003ff459a70 and https://experience.dynamics.com/ideas/idea/?ideaid=a40b6cb7-d546-ea11-b698-0003ff68992e
MultiPartFormDataContent - https://experience.dynamics.com/ideas/idea/?ideaid=adec2f78-3297-e911-80e7-0003ff68f3db

**Comment by BazookaMusic** [comment]
A cookie type was added for version 14. I will close this
