### ISSUE TITLE
The request for path /NAV2018CU4/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The extension specifies a higher compilation target than allowed.

### ISSUE THREAD

**Issue by CnCollins** [Microsoft/AL#2021]
Hi

I have installed the NAV2018CU4 release on my laptop and installed the VSIX that came with it into Visual Studio Code.

I  am trying to do some Automated Testing on an extension I am writing and have set the app.json to have the following settings, so that the Test Objects are available:

    "platform": "11.0.0.0",
    "application": "11.0.0.0",
    "test": "11.0.19846.0",

However when I try to run the code, I get the following error:

The request for path /NAV2018CU4/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The extension specifies a higher compilation target than allowed.

The only help I've found on the web regarding code 422 is about a date format issue, but that has a different message.

Can anyone help?

Thanks

Chris

**Comment by CnCollins** [comment]
I had both at Extension and it didn't work.  I changed both to Internal and I seem to get a little further but still have issues.

Firstly, if this is to go on AppStore, should the target not be Extension?
Secondly, when running from AL as Web Client, NAV freezes on the Blue pre login screen (functionality works fine when run via RDC)..
Thirdly, when running the Automated Tests via the RDP, the First Error is Object of Type CodeUnit with ID 132204 could not be found.  This id I believe is one of the testing library codeunits which I am using in my test routine.  I believe these should be included in the extension due to the "Test" setting in the app.json file?

Cheers

Chris

**Comment by StanislawStempin** [comment]
Yes, to go to AppSource your extensions needs to have target = Extension. However, the error message that you're getting would indicate that your server was set to MaximumAllowedExtensionLevel = Extension while your app.json had target : Internal or target : Solution.  
Try setting the server to Solution and your extension to Extension.

Regarding the second problem you are most likely missing the actual TestToolkit objects in the database. Please check if they are visible from C/SIDE and if not import them from the DVD or Docker image.

**Comment by CnCollins** [comment]
I've tried all different combinations, including the one you've suggested, of Allowed Extension Target Level in the Developer tab and the Target property on the app.json file.  The only combination that I have found that works is when both are set to Internal.  Every other option seems to error with either 

[2018-04-17 08:46:48.34] Sending request to http://localhost:7049/NAV2018CU4/dev/apps?SchemaUpdateMode=synchronize
[2018-04-17 08:46:52.59] The request for path /NAV2018CU4/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The extension specifies a higher compilation target than allowed.

or

c:\Visual Studio\Outbound Stock Selector\Automated Test Codeunits\SYN OSS Auto Test.al(37,21): error AL0296: The type or method 'CreateLocation' cannot be used for 'Extension' development. (Where CreateLocation is from the Test Library Codeunit for Warehouse.

You say that the TestToolkit objects are missing in the database.  That is correct.  I have not put them in the database but my (probably faulty) understanding was that by populating the Test property in the app.json file, I would not have to have them in the local database?  I cannot guarantee that everyone that uses this extension will have the testtoolkit installed and I thought what I had done would be enough.  It does create a Microsoft_Test_11.0.21441.0.app file in the .alpackages folder

**Comment by StanislawStempin** [comment]
Ok, so that's the real problem. You need to use target = Extension in app.json. If you get errors about some methods not being available you need to file a request for exposing a given function. Could you please file it as a new request for exposing a function?

Regarding the Test Toolkit you should assume that it is not present on Business Central servers. For On-Premise you should instruct your customers to make sure they install it. However, in general, why would you take dependency on Test objects outside of your development/test systems?

**Comment by CnCollins** [comment]
Ok so I've moved the testing code into a different extension (my fault as I missed the bit in the instructions to keep them separate).

The original extension works fine with both app.json and server instance set to Extension.

The test extension only compiles when both settings are set to Internal.  When running the Test Tool, I get the error:  Object of type CodeUnit with ID 132204 could not be found.  This codeunit was found in the al code as I added it as a variable and called functions on it.  If I import the codeunits from the TestToolKit section of the DVD into my On Premise NAV Visual Studio will then complain about the ambiguity of having two CodeUnit 132204 (the one from the downloaded server symbols and the other that's included due to the Test property on the app.json.

How do I run functions from the testing libraries in extensions, so that I can put on the automated testing required for AppSource?

Thanks 

Chris

**Comment by StanislawStempin** [comment]
You either need to make sure that you don't recompile the test objects with symbol generation flag or remove the Test package reference from your test project.

Otherwise, like you say, the test objects will be present in both packages causing ambiguity.

@kalberes  - could you share the filter that we're using internally not to recompile Test objects?
