### ISSUE TITLE
Unable to Launch Debugger: NAV CU02 2018 Local Client - Dynamic operations can only be performed in homogenous  AppDomain.

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#2022]
Server instance: DynamicsNAV110 Tenant ID: <ii>User:  DESKTOP-F5NR80A\dennis Type: System.InvalidOperationException Message:  <ii>Dynamic operations can only be performed in homogenous  AppDomain.</ii> StackTrace: at  System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site,  Object[] args) at  System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0  arg0, T1 arg1) at  Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.DebuggerHub.OnDebuggeeConnected(Object  sender, DebugSessionStartEventArgs eventArgs) at  Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.OnDebuggingSessionStarted(DebugSessionStartEventArgs  e) at  Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.CreateRuntime(String  debuggingContext, NavSession session, Boolean waitForDebugAdapterConfiguration)  at Microsoft.Dynamics.Nav.Runtime.NavSession.StartDebuggingSession(String  debuggingContext, Boolean waitForDebugAdapterConfiguration) at  Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(ConnectionRequest  connectionRequest) at SyncInvokeOpenConnection(Object , Object[] , Object[] ) at  System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance,  Object[] inputs, Object[]& outputs) at  Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation  innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[]  inputs, Object[]& outputs) Source: System.Core HResult: -2146233079  </ii>
--

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38748983-0243b220-3f1e-11e8-9f79-28b745104c3a.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38749769-d58ed69e-3f20-11e8-9724-b9edcad57db1.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38749810-efa1ea26-3f20-11e8-9925-e9f13d0ce009.png)

**Comment by dennisaubrey** [comment]
Can you run AL on CU2 for NAV 2018? - Local Client - 
![image](https://user-images.githubusercontent.com/36566794/38750770-fb8a3296-3f23-11e8-840c-ae37e28d7b26.png)

**Comment by StanislawStempin** [comment]
Please see: https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-debugging
![image](https://user-images.githubusercontent.com/23653165/38751552-c0e1a2e8-3f58-11e8-9a46-6fc4733c2843.png)

Also, you need to use VSIX that came on the NAV 2018 CU3 (0.12) instead of using the AL Language for Business Central (0.15)

For further help please contact support since NAV 2018 is not supported through this forum.
