### ISSUE TITLE
Request for various events in CU 12172, 12173 (IT)

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#2023]
OnBeforeCode
OnAfterCode
OnBeforeGenJnlPostLine

### **Please note that localized objects are completely lack of events and never raise the trigger when inserting, modifying and deleting tables**

Thank you
S.

**Comment by AlexanderYakunin** [comment]
You can ask what you need for any supported country, and requests with detailed description will be processed faster. Pls. be aware what due to legacy code in some objects they may require significant refactoring before event implementation, so final implementation may differ from you initial ask.
