### ISSUE TITLE
Function visibility - interaction attachments

### ISSUE THREAD

**Issue by TKapitan** [Microsoft/AL#2024]
We need the functions from T5103 to be visible in AL:

CreateAttachment()
OpenAttachment()
CopyFromAttachment()
ImportAttachment()
RemoveAttachment(Prompt : Boolean)

**Comment by GiorgosPa** [comment]
These functions are not safe for AL development, since they manipulate files on disk. We cannot process your request at the moment as it requires refactoring of the application and needs to be prioritized.

**Comment by JesperSchulz** [comment]
Closing issue based on comment.
