### ISSUE TITLE
Documentation headline in D365BC go to old url

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2026]
In Business Central there is Documentation headline part (p1440-p1448).
It has const url https://go.microsoft.com/fwlink/?linkid=867580 which redirects to https://docs.microsoft.com/en-us/dynamics365/financials/?branch=master
and should redirect to https://docs.microsoft.com/en-us/dynamics365/business-central/index

**Comment by StanislawStempin** [comment]
Thanks. I passed on the issue to the owning team but please keep in mind that AL GitHub is only for AL Development related issues and not for all product bugs.
