### ISSUE TITLE
Question: Open Bugs - Priority for Fixing

### ISSUE THREAD

**Issue by alanb999** [Microsoft/AL#2027]
There are currently 78 logged issues that have been accepted as bugs for the Modern Development environment.  43 of which are marked as 'ships-in-future-release' which is May 2018 (no April release).
Can you estimate a release date in May (first, second, third, forth or fifth week)?
Very glad to see that the backlog of bugs are being addressed!!!

Of the remaining bugs...would it be possible that the bugs be assigned priorities (1-3), and provide an indication when these issues will be addressed (targeted future release).  There are accepted issues as bugs dating back to Oct 2017.

**Comment by StanislawStempin** [comment]
We are currently working our way through the bug backlog, including the old bugs.  We cannot provide more details about the exact release date at this point. We intend to fix all issues currently marked as bugs. 
One thing to note though is that the fixes will only be available in the Developer Preview releases and ultimately in Fall 2018 in the next major Business Central release. If you require hot fixes for your live tenants then these requests need to go through the support team.

**Comment by alanb999** [comment]
Well its very unfortunate that bugs fixed for the Modern Development environment will not be available until the next major release of Dynamics NAV for on-premise.
We had expected to get an update for the Modern Development environment with NAV 2018 R2 but that release was cancelled.
The decision not release for the Modern Development environment bug fixes as part of the NAV 2018 cumulative update will delay the adoption of for the Modern Development environment by NAV partners.

**Comment by StanislawStempin** [comment]
Fixes for critical issues will be ported back to NAV 2018 if raised through the regular support channel.

**Comment by SirBETE** [comment]
@alanb999 If you create a regular support case, with the request to include this fix (link), they will copy it.
Just like Stanislaw is saying.
If you request it now, chances are high it will become available in CU5.
(Yes it is stupid you need to request to copy each event-request/function-expose/bug-fix/... to NAV2018 if it will be included in NAV2019/BC on prem, but that's another discussion.)
