### ISSUE TITLE
Company Indicator

### ISSUE THREAD

**Issue by KristofKlein** [Microsoft/AL#2028]
Hi,

it would be really nice if the Company Indicator Setup is also taken into account on the Web Front-end. Including the Naming but also the Coloring...

Apart from that: We had quite some clients asking for "Branding" the Web Client...Since they have clever people they start customizing the CSS on their own. But that never feels right.

**Comment by StanislawStempin** [comment]
I will pass on the feedback to the Client team and I know branding is on the long-term backlog. Since this topic is not directly related to AL Development I'm closing this issue.
