### ISSUE TITLE
Insight from last week - Infobox

### ISSUE THREAD

**Issue by KristofKlein** [Microsoft/AL#2029]
I have found a small glitch on the "Insight from last week" box: Running the Role Center for "Business Manager" it says: "Your top customer was Klubben, bought for £11,772" while clicking on it to see more: the column says: 11,772 $. so £ vs $ but same amount. 
(It would also be very nice to access the Customer "Klubben" via that subpage).

**Comment by StanislawStempin** [comment]
Thanks for taking the time to log the issue. Since it is not directly related to AL Development I would ask you to report it through regular support channels.
