### ISSUE TITLE
GETLASTERRORTEXT is not supported

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#203]
In **Extension 2.0** it is not possible to call these functions: 

```
GETLASTERRORTEXT
GETLASTERRORCALLSTACK
```

Please can you support this?

**Comment by StanislawStempin** [comment]
We will investigate if it's safe to re-enable these APIs or how to provide equivalent functionality.

**Comment by bvbeek** [comment]
Thanks for your update!
