### ISSUE TITLE
Translation Service Issue

### ISSUE THREAD

**Issue by Nagaraju17** [Microsoft/AL#2031]
We have generated translation file from AL environment. And we are trying to request caption by using Translation service, But when we upload the file and complete the process, it is showing the status with "Completed with error".  There is no proper information about the error and what it is.
Can any one give suggestion on this.

![image](https://user-images.githubusercontent.com/30176345/38807345-e30c9da8-4199-11e8-905f-b3b873c96a2b.png)

**Comment by StanislawStempin** [comment]
Translation Service is a separate product not support through this forum and not maintained by the NAV/Business Central team. Please try to reach out to the relevant support channel.
