### ISSUE TITLE
Handler function is not called in test codeunit.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#2034]
Hi all!

I implement a test package project for my app.
I create a simple test case. When I run my test CodeUnit (use Test Tool page), it run with fail result.
[COD50202.PurchaseTest.txt](https://github.com/Microsoft/AL/files/1918967/COD50202.PurchaseTest.txt)

Whe I debug it then i recognizes the the HandlerFunctions is not called.
![image](https://user-images.githubusercontent.com/24407031/38860246-f4b8a446-4259-11e8-8d71-86ac8d8daa4a.png)

![image](https://user-images.githubusercontent.com/24407031/38860286-1172f7da-425a-11e8-8dd5-a7603ddcd982.png)

Please check my case!
**_Check Version: W1 12.0 (21229)_**

**Comment by StanislawStempin** [comment]
After further investigation it turns out that the handler functions cannot be local. 
We will consider how to improve this experience, most likely by adding a compiler check that will prevent having local handler functions.

**Comment by hgnamvn** [comment]
Thank StanislawStempin!

Thank for finding out the root cause!
Now, i will change all handler functions to global for my project.
I also wait for an update of compiler.

**Comment by StanislawStempin** [comment]
We have implemented a compiler check enforcing that functions using any of the Handler* attributes cannot be local.
