### ISSUE TITLE
Upload Extension in Dynamics 365 Business Central

### ISSUE THREAD

**Issue by stanuj** [Microsoft/AL#2035]
Hi,

I'm trying to upload .app extension in business central from my local disk.

While deploying, it is showing me an error:

![image](https://user-images.githubusercontent.com/32701699/38863535-90afac32-4255-11e8-9db6-0ddaba3293e3.png)

Please provide your guidance, if anyone is aware of this.

**Comment by StanislawStempin** [comment]
Are you uploading to a live Business Central tenant? 
This functionality has been accidentally exposed on Container Sandboxes but it will not work locally.

**Comment by stanuj** [comment]
No, it's not live tenant, it's trial tenant.

**Comment by stanuj** [comment]
Is there any update on this part?

**Comment by stanuj** [comment]
Thanks, it is being uploaded now.

But why it showing me error as given below, if my app extension is not published on MS App Source?

![error message](https://user-images.githubusercontent.com/32701699/38932018-a6debf74-4332-11e8-9b48-73637f690d48.png)

Please share your experience.

**Comment by StanislawStempin** [comment]
Can you share more details about what you're trying to upload? Is it a Hello World app? It currently looks like your app id conflicts with an app id from AppSource.

**Comment by HunterFeltman-MSFT** [comment]
Could you relay your trial tenant's name? This will assist in the tracking down of this specific upload request. 

As it happens, my 'best guess' for this request would indicate you are trying to upload an extension that was written by the publisher 'Netsmartz LLC', which is indeed an extension that we have as coming from AppSource.

**Comment by stanuj** [comment]
@StanislawStempin : This is not the Hello World app. I've created an app extension with some customization to publish on MS App Source.

@HunterFeltman-MSFT : "https://netsmartz25.financials.dynamics.com/?aid=FIN&signInRedirected=1"

This is the tenant URL. Yes you are right, this extension is written by Netsmartz LLC.

Basically, i want to upload my app extension into D365 Business Central and to check the limitations as per my extension.

This is required, because I've to take screen shots of Business Central for publishing my app extension on MS App Source.

**Comment by HunterFeltman-MSFT** [comment]
The process coming from the AppSource submission team indicates that a Docker VM should be setup using the variety of builds/images for BC that have been made available to do what you are asking.
