### ISSUE TITLE
Http client GET failed

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#2037]
Hello!

I'm executing next code:

`API := 'SomeAPIUri';`
` Client.DefaultRequestHeaders.Add('Authorization', 'Basic TOKEN');`
        `if not Client.Get(API, Response) then`
           ` Error(StrSubstNo('Upload Failed, Status %1, Reason %2', Format(Response.HttpStatusCode), Response.ReasonPhrase));`

If response quite big (35Mb) - i get an error 'Upload Failed, Status 200, Reason OK'

I've set Max Upload Size = 256 on NAV instance, but it has no impact.

**Comment by StanislawStempin** [comment]
Try setting NavHttpClientMaxResponseContentSize setting to a larger value as well.
