### ISSUE TITLE
Excel document read failed on web client

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#2038]
Hello! 
I'm using NAV2018 CU03 with Excel Buffer table from Business Central.

I have an action on page which opens Excel document and read it. Everything is ok on RTC client, but on Web client it fails on  ExcelBuffer.SelectSheetsName with next error:

> A call to Microsoft.Dynamics.Nav.OpenXml.Spreadsheet.WorkbookReader.Open failed with this message: File1.xlsx

Executing code is next:

         `UploadIntoStream(
            'Select File to upload:', '', '',
            ClientFileName, InStr);

        IF ClientFileName <> '' THEN
            SheetName := ExcelBuffer.SelectSheetsName(ClientFileName)
        Else 
            Exit;

        ExcelBuffer.RESET;
        ExcelBuffer.DELETEALL;
        ExcelBuffer.OpenBookStream(InStr, SheetName);
        ExcelBuffer.ReadSheet;`

**Comment by StanislawStempin** [comment]
You are trying to read a file that doesn't exist on disk. Assuming this is On-Premise you should use Upload instead of UploadIntoStream or do not use SelectSheetsName which works based on server file.  

For futher assistance pleas contact Support team.

**Comment by JesperSchulz** [comment]
We recommend to use streams for extension development, your call to use UploadIntoStream is hence the right one. The function SelectSheetsName, however, works on files and should hence not be used. Instead, the stream equivalent SelectSheetsNameStream should be used, which was made available in Business Central. I hope that helps resolving your issue.
