### ISSUE TITLE
TableSynchSetup signature issue

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#204]
In Extension 2.0 we get this error:

'The signature of procedure 'TableSynchSetup' does not match the signature required by attribute 'TableSyncSetup': parameter 1 is expected to be of type 'var Table' but found type 'var Record "Table Synch. Setup"''

The code looks like this:
```
 [TableSyncSetup]
  procedure TableSynchSetup(var TableSynchSetup : Record 2000000135);
  var
    DataUpgradeMgt : Codeunit 9900;
  begin
    DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Customer",0,TableSynchSetup.Mode::Sync);
  end;
```

**Comment by waldo1001** [comment]
Can you explain the scenario?  

This looks like a data-upgrade scenario ... and as far as I understand:
(1) it's not being done this way in extensions (but by the OnNavAppUpgradePerDatabase/Company - https://msdn.microsoft.com/en-us/library/mt703361(v=nav.90).aspx ).  
And (2) it isn't supported yet in the latest (April) build.. .

**Comment by bvbeek** [comment]
That's right, it goes about the upgrade scenario.

I know that the upgrade procedure will be changed in the meantime, but I think the code should compile anyway.

**Comment by StanislawStempin** [comment]
This upgrade approach is not applicable to Extensions 2.0. Most likely the attribute should be removed for now to avoid confusion. 
What would be the reason to have this code successfully compile if it would not work at runtime anyway. That way we would just hide the problem.
