### ISSUE TITLE
Yet another expose request

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#2040]
Hi Again.

I've come across yet another few functions that are not available for extension development. 
Here they are.

FlowServiceManagement : Codeunit "Flow Service Management"
- FlowTemplateSelector.SetSearchText(FlowServiceManagement.GetPurchasingTemplateFilter)

PurchaseHeader : Record "Purchase Header"
- OnAfterValidateBuyFromVendorNo

ApplicationAreaSetup : Record "Application Area Setup";
- IsLocationEnabled
- IsAllDisabled

OfficeMgt : Codeunit "Office Management";
- OCRAvailable
- IsOutlookMobileApp

LanguageManagement : Codeunit LanguageManagement;
- SetGlobalLanguageByCode
- RestoreGlobalLanguage

ConfigValidateMgt : Codeunit "Config. Validate Management";
- IsKeyField

**Comment by grobyns** [comment]
Please note that the functions from Record 9178 Application Area Setup have been moved to Codeunit 9179 Application Area Mgmt. Facade. You should find all relevant functions there and they should all be marked as External.

br/Gert
