### ISSUE TITLE
Codeunit 5906 - OnBeforeServItemEventDescription event

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#2042]
Hi,
we are upgrading our solution to NAV 2018 (preparing for BC) and I have modification in function ServItemEventDescription in COD 5906. I want to use events, and there is event OnBeforeServItemEventDescription, but there is no way how to return value back to the function to return it as result. It means the event is "dead end". It is called, but there is no way how to use it somehow usefully.  I will expect to implement Handled pattern here to be able to return some text for the event no. and return this text as result of the function, when handled.

I will rather expect something like:

```
...
  18:
    EXIT(Text032);
  ELSE BEGIN
    OnServItemEventDescription(EventNo,Handled,Description);
    if Handled then
      Exit(Description);
    EXIT(Text014);
  END; 
```

**Comment by dtacconi** [comment]
Thanks to kine that creates a Support Request for back port, this is now also shipped in the application for NAV 2018 CU 5 (May 2018)
