### ISSUE TITLE
AL:Download Symbols - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TonyHemy** [Microsoft/AL#2043]
Create a new container using
 -containerName BCSANDBOXCA -imageName microsoft/bcsandbox:ca

Which worked successfully. 

Now trying to create a AL project based on the database in that container.
I have my launch.json as below (userpassword was not working)

"configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://BCSANDBOXCA",
            "serverInstance": "NAV",
            "authentication": "Windows",
            "startupObjectId": 22
        }

Symbols pull but I get the following error

[2018-04-17 16:46:55.30] Using reference symbols cache path: c:\Users\vmadmin\Documents\AL\ALProject1\.alpackages
[2018-04-17 16:46:55.30] Sending request to http://bcsandboxca:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2018-04-17 16:46:55.30] Sending request to http://bcsandboxca:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2018-04-17 16:46:58.22] All reference symbols have been downloaded.
[Error - 4:47:45 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Object reference not set to an instance of an object.
StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsAsync(Document document, Int32 position, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 25
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by TonyHemy** [comment]
My laptop is acting up - coming back to update issue after a restart.

**Comment by TonyHemy** [comment]
It looks like this may be related to the AL and RDLC files I have in the project too.

If I get symbols without the AL or RDLC file in the project then the above error does not occur.

If I add the files in i get the error.

To get the AL and RDLC files I created a new report object in the BCSANDBOXCA database and use the containerhelper Convert-ModfifedObjectToAL to create the AL and RDLC files and then pull them into the VS Code Project.

**Comment by StanislawStempin** [comment]
Could you attach the converted AL file in this issue?  Looking at the stack trace the issue doesn't look related to downloading symbol but to CodeLens. 
You can try switching off CodeLens in user settings and see if you can proceed with the project:
```
"[al]": {        
        "editor.codeLens": false
    }
```

**Comment by TonyHemy** [comment]
[Report 50101 - Check - Encore.zip](https://github.com/Microsoft/AL/files/1921577/Report.50101.-.Check.-.Encore.zip)

**Comment by TonyHemy** [comment]
If I set codeLens to false the original error goes away but when I publish I get the following error 

Microsoft (R) AL Compiler version 0.12.17720
Copyright (C) Microsoft Corporation. All rights reserved

error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
Error: The package could not be created.

**Comment by qutreson** [comment]
Hi @TonyHemy, I tried to use your code, but it seems that it takes dependency on some other objects that were not included. When moving these files to a new AL project, I have then diagnostic errors due to missing references and it does not reproduce your error. After when commenting out the missing references, I am also not unable to reproduce the issue.

Can you actually reproduce it by using only the code you sent here?
If no, can you try to cut down your main project again in order to provide us with something that we could use to reproduce the issue?

**Comment by TonyHemy** [comment]
Hey @qutreson,

Are you sure you have symbols pulled from the right base image? Would need to be the Canadian BC Sandbox.

Project is simply a copy of report 1401 with an existing MSFT field added to it; so strange that you would have missing dependencies as everything is base MSFT nothing added.

t

**Comment by TonyHemy** [comment]
@StanislawStempin any update?

Cheers

t

**Comment by qutreson** [comment]
Hi @TonyHemy, after downloading the symbols from the right container, I don't have any dependency problem anymore. 

Concerning the code lens issue, I cannot reproduce it when using the latest containers where the AL extension version is 0.15.1877, I can only reproduce it when using an older extension version like 0.12.17720. 

Can you try updating to a container which contains an updated version of the AL extension and tell me if this solves your problem?

**Comment by TonyHemy** [comment]
Hey @qutreson 

Thanks for the info.

I am not using containers for my VS Code but I think what you are saying here helped me figure out the issue. My azure machine with VS Code pre-installed has come from @freddydk  aka azure templates and is only a week old so it seemed odd to me that the extension would be out of date so soon.

From doing some more research it appears the AL extensions has ([or at least used to](https://www.kauffmann.nl/2017/12/15/the-different-al-extensions-versions-for-visual-studio-code/)) have 2 flavors - one for D365 BC and one for NAV. 

When I disabled the NAV one and installed the D365 BC extension it worked - same as you were seeing - however it was not an update from what I can tell but a different extension altogether.

Will test a little more before confirming.

t

**Comment by aconcato** [comment]
I had the same error message and I figured out running VS Code as administrator.. It used to work fine before the last update of VS Code.

**Comment by qutreson** [comment]
@TonyHemy, can you confirm your problem got fixed?

@aconcato, can you open a new issue with the code that produces the issue for you so that I can look into it? Even if you get the same error message here, the null reference object might not be the same one. We improved our stack traces so that in the future we will get more information about where the null object reference comes from.

**Comment by TonyHemy** [comment]
Hey @qutreson from the digging I have done no official confirmation of two different AL Extensions for Visual Studio Code perhaps @StanislawStempin could confirm?

t

**Comment by TonyHemy** [comment]
@qutreson Confirmed that there are 2 extensions for Visual Studio Code AL one for D365Bc and one for NAV and that is what was causing the issue,
