### ISSUE TITLE
Event Request OnBeforeCheckItemTrackingInfo in Codeunit 22

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/AL#2044]
Hello Team,
We have requirement to create the Lot No./Serial No. information record if it does not exist and if Lot No. info/Serial No. info is required. It would be helpful if you add event in CheckItemTrackingInfo Function in Codeunit 22 for that.
Thanks.
![event suggession in codeunit 22](https://user-images.githubusercontent.com/35543761/38903989-8c5069fe-425c-11e8-8faf-82f1acef132c.png)

**Comment by StanislawStempin** [comment]
This event already exists. Please check on the latest bcsandbox-master Docker image.
