### ISSUE TITLE
Translate native objects with XLF files 

### ISSUE THREAD

**Issue by NickLin1017** [Microsoft/AL#2045]
Hi all,

I meet some problems when I translate native objects.
I do not know how to generated “trans-unit id” associated with native objects.
Is there any way to translate native objects?Thanks.

Now We just can use XLF files to translate our custom objects.
1. command (Ctrl+Shift+B) –Create .xlf file.
Only automatically generated “trans-unit id” associated with our custom fields.

**Comment by StanislawStempin** [comment]
To translate native objects you need to use the same .txt translation files as you would have used in the past and just include them somewhere in the project folder. They will be automatically picked up by the compiler. We have just published a new  documentation topic here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-data-for-extension

**Comment by NickLin1017** [comment]
@StanislawStempin 
Thank you for your answer.
I put translation.txt files into my project and publish to my server but it still no use.
Is there anything else I should know ?

**Comment by NickLin1017** [comment]
Hi @StanislawStempin 
It's work.
The reason is the encoding problem.
But how can we switch language to our target language in D365 BC?
Or is there anything else we should do or pack in to extension besides translation file?

**Comment by DominikDitoIvosevic** [comment]
Why is encoding a problem?
Are you talking about translating your current extension or the base app?

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
#2100
At first I failed  because I use notepad to re-save translate file.
