### ISSUE TITLE
[event-request] OnAfterJobQueueScheduleTask

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2049]
In the latest CU batches a new event appeared on Codeunit 453: `OnBeforeJobQueueScheduleTask`. It would also be quite handy to have an `OnAfterJobQueueScheduleTask` that has a signature as follows:

    OnAfterJobQueueScheduleTask(JobQueueEntry, SystemTaskId)

**Comment by StanislawStempin** [comment]
OnAfterEnqueueJobQueueEntry(JobQueueEntry) event has been added.
SystemTaskId is already a field on JobQueueEntry so a separate parameter should not be needed.
