### ISSUE TITLE
[Event Request] Codeunit 6620 OnAfterInsertToSalesLine(ToSalesLine,FromSalesLine)

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/AL#2050]
In Codeunit 6620 the existing Eventtriggers are
in CopyPurchline the call to
OnAfterInsertToPurchLine(ToPurchLine,FromPurchLine)
but in CopySalesLine the call with
OnAfterInsertToSalesLine(ToSalesLine)

It should be the same Syntax in CopySalesLine(ToSalesLine,FromSalesLine) so that individual programming can use the source record Content and line number to copy individual data to Destination record and data.

**Comment by NKarolak** [comment]
This is already handled in #1344

**Comment by GuntherGebauer** [comment]
sorry, although searching I did not find that
when is it shipped  - which release or CU or ???
