### ISSUE TITLE
[Event Request] Codeunit 1305 OnAfterInsertSalesInvoiceLine

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/AL#2052]
In Codeunit 86  "Sales-Quote to Order" the Event Trigger 
- OnAfterInsertSalesOrderLine
- OnAfterInsertAllSalesOrderLines

are submitted.

Codeunit 1305 "Sales-Quote to Invoice" is the similar function on sales quotes to create invoices instead of orders both fnctions called from Page 41 and 9300.

To use the same Trigger structure those Triggers from codeunit 86 should be added to codeunit 1305 as well. Maybe all Triggers in both codeunits 86 and 1305 should be exaclty of the same strcucture which is Logical and conform to the two very similar page functions.

**Comment by marknitek** [comment]
While we are at it, Codeunit 5923 Service-Quote to Order does not expose these events too. There should be the same Events as in the Codeunit 86.

And only Codeunit 86 has Event Publisher  "OnAfterOnRun". I think all Codeunits (86,87,96,97,5923) should have the same set of Events:

- OnBeforeInsertOrderHeader
- OnAfterInsertOrderLine
- OnAfterInsertAllOrderLines
- OnAfterOnRun
- OnBeforeInsertOrderLine
