### ISSUE TITLE
NAV2018DK CU04: Bug in FIK Extension Cod13656 DataMigration

### ISSUE THREAD

**Issue by Hornhq** [Microsoft/AL#2054]
The Migrate functions are testing if the UPG table is in the database with the following line of code:
if Obj.GET(obj.Type::Table,104038) then
But the Object table the Primary key are "Type", "Company Name", "ID" So the correct code should be 
if Obj.GET(obj.Type::Table, '',  104038) then

The MigrateCompanyInformationFields function are pointing to the wrong table ID:
if Obj.GET(obj.Type::Table,104041) then
The object installed from upgrade toolkit has Id 104079!

So no data are migrated!

/Claus

**Comment by WaelAbuSeada** [comment]
Thanks for reporting the bug, we are fixing it.
