### ISSUE TITLE
Event Type OnAfterCreateDimTableIDs  for Purchase Line (T 39)

### ISSUE THREAD

**Issue by raduku2018** [Microsoft/AL#2055]
Hello,

For T 36| 37| 38 the EventType OnAfterCreateDimTableIDs exists.
Could you please added for T 39?

Thank you.

**Comment by AncaSterian** [comment]
Dear @thpeder ,

Can you please tell us in which cumulative this update will be included?
 We are currently working to a localization package and we need this functionality for a mandatory development.
 It's possible to have it on the CU7 which will be launched in July 2018 ?
We checked in the CU6 and this is not available yet. 
Thank you very much in advance.

Kindest regards,
 Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

New events will be implemented to Dynamics 365 Business Central only. No new events will be implemented to NAV 2018 CU’s based on GitHub requests, please contact customer support to create a hotfix request for critical events.
