### ISSUE TITLE
Unable to add hidden factboxes to a page with the web client

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/AL#2057]
not all fact boxes are default visible (for example page50:Purchase Order). How can a web client user add hidden fact boxes?

Dynamics 365 Business Central Sandbox Environment
12.0.21229.0 (march, finUS)

**Comment by StanislawStempin** [comment]
I assume you mean the Personalization feature in the web client?
It is not possible to add controls that are originally hidden, it is only possible to "in-hide" controls hidden as part of previous personalization.

**Comment by Pieterheinevdm** [comment]
:( there are a lot of factboxes default hidden in standard nav but also in addon`s and customizations. It would be unpleasant to ask everyone to make these factboxes default visible only because the webclient doesn't support a feature to unhide a factbox. so could you add a request for this feature?

**Comment by StanislawStempin** [comment]
I will pass it on to the Client team and track as a suggestion.

**Comment by richardrobberse** [comment]
Is there any news on this one? Currently facing the same thing and making all the factboxes visible by default is not really an option.

**Comment by Pieterheinevdm** [comment]
procedure ExampleUseFilterPageBuilder() Result:Text
    var
        TableMetadata: Record "Table Metadata";
        FilterPageBuilder: FilterPageBuilder;
    begin
        TableMetadata.GET(27);
        FilterPageBuilder.ADDTABLE(TableMetadata.Caption,TableMetadata.ID);
        if FilterPageBuilder.RUNMODAL then
          Result := FilterPageBuilder.GETVIEW(TableMetadata.Caption,true);
    end;

**Comment by TRASERDanielGorski** [comment]
Have still the same issue here... do you have any news?

**Comment by RosenLimbu** [comment]
"The difference with the Microsoft Dynamics NAV Web client is that you cannot perform customization tasks directly from the Microsoft Dynamics NAV Web client. Instead, you perform the customization tasks in the Microsoft Dynamics NAV Windows client, which means that any customization that is performed applies to both the Microsoft Dynamics NAV Windows client and Microsoft Dynamics NAV Web client."

What if you don't have a Windows Client?? I'm running into the same issue as you guys

**Comment by DRWEST90** [comment]
I'm struggling to believe this, even when you go into design mode on a Sandbox environment, it seems to offer the option to +Part etc but its un-editable. 
all the more complicated is the fact that in the training you are directed to add/remove fact boxes to show users how to do it, little does the trainer know that this is removing fact boxes for the remainder of the implementation........

**Comment by MajorBarf** [comment]
You can't even make them visible with an extension. I wanted to make the existing record links factbox visible on the standard posted sales shipment & posted purchase receipt pages. I know you can do it by switching on the "Record Links" applicatioen area but I dont need them showing everywhere else too. The factbox is there and the property says visible = false. But you cannot use a page extension to modify this property beause the control cannot be referenced. You end up having to duplicate it by having an extension something like this:
    layout
    {
        addlast(FactBoxes)
        {
            systempart(MyDuplicateRecordLinks; Links)
            {
                ApplicationArea = All;
            }
        }
    }
It seems silly that we have to do this. Is there a plausible explanation why we can't just modify the property of the existing control instead of adding a new one?

**Comment by Pieterheinevdm** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=913c8010-647d-e911-80e7-0003ff689ebe

**Comment by qutreson** [comment]
Closing this Github issue as it was moved to a BC Idea that was completed since. Hidden fact boxes are now showing as Ghosted when using in-client designer allowing you to show them, or move them. Thank you for your inputs on this.
