### ISSUE TITLE
Database collation setting - app install

### ISSUE THREAD

**Issue by Phfo** [Microsoft/AL#2058]
When creating an app for BC of NAV2018 - do we have to use the same collation settings as the demo cronus db ? We've made a local db Latin1_General_100_CI_AS in stead of Latin1_General_100_CS_AS (like cronus). Everything works fine except when installing Image Analyzer app we have error  : 
The following SQL error was unexpected:
Cannot resolve the collation conflict between "Latin1_General_100_CI_AS" and "Latin1_General_100_CS_AS" in the equal to operation.

**Comment by HunterFeltman-MSFT** [comment]
There is some large up coming work around Collation in general in the platform and so the decision at this point is to completely block collation changes when any extensions are synchronized to a database until those changes are finalized.
