### ISSUE TITLE
Scheduled tasks aren't executed

### ISSUE THREAD

**Issue by claudio1981** [Microsoft/AL#2059]
When a new task is created using _TASKSCHEDULER.CREATETASK_, the task is created in table 2000000175 "Scheduled Task" and then deleted by the scheduler after the "Not Before" condition is fullfilled, but the scheduled codeunit isn't really run.

The codeunit that was scheduled run without issues if executed manually.

I'm using the last available sandbox environment for Dynamics 365 Business Central.

**Comment by freddydk** [comment]
This is probably related to Windows authentication.
Try to run your sandbox environment using NavUserPassword auth. - then they should run.

**Comment by claudio1981** [comment]
I can confirm that using NavUserPassword auth the task scheduler works, thanks.
Is this a bug that will be fixed in a future release?

**Comment by jensmpmsft** [comment]
This seems identical to the issue we fixed in May, where starting a container with Windows Authentication caused failures. Builds larger than 21966 should contain the fix.
