### ISSUE TITLE
SQL Query in AL code

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#206]
It would be nice if we can execute custom SQL queries via AL Code.

**Comment by esbenk** [comment]
TSQL will never be allowed for SaaS. The reason for this is security and resource governance.

For OnPrem this can technically be done through .net interop (when we support that in the new tools).

**Comment by atoader** [comment]
We have been supporting .NET interop for a while now. It should be possible to achieve this scenario using functionality available in Business Central Fall 2018 and later.
