### ISSUE TITLE
How move a new action into specific (and new) Category on the Ribbon

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2061]
Trying to make a profile that matches one done in the RTC.

I have added a new action to a group on a page (Job Project Manager RC).  I want it to be PromotedOnly and in a new Category on the page.  How do I do this?
I have this in the Action section of my PageExtension
```
        addafter("Manager Time Sheet by Job")
        {
            action("Manager Time Sheet Lines")
            {
                Caption = 'Manager Time Sheet Lines';
                RunObject = Page "IMS PM TimeSheet";
                Image = JobTimeSheet;
                Promoted = true;
                PromotedIsBig = true;
                PromotedOnly = true;
                PromotedCategory = Category6;
                Visible = true;
            }
        }
```
Then in my PageCustomization, in the Action section I have
`        movebefore(NewGroup;"Manager Time Sheet Lines")`
This puts the new action in a Category called "General".  However, how do I change the name of the Category?  I have
`PromotedActionCategories = 'New,Process,Report,Manage,History,Time';`
Where does "General" come from?  How do I change it?
Any possibility of a tool convert Profile XML info to AL?

**Comment by qutreson** [comment]
Hi @GreatScott000, the concept of promoted actions does not really apply for RoleCenter pages as they don't have a `Home` ribbon in which promoted actions can be placed. Your new action is then only added to the `Actions` ribbon after `"Manager Time Sheet by Job"`. We will think about some way to prevent using promotion related properties for actions in role centers in the compiler or in the analysers.

In your customization, when moving your new action `"Manager Time Sheet Lines"` before `NewGroup`, you are doing the same than `movefirst(Processing; "Manager Time Sheet Lines")`. When adding an action in the Processing area, it gets added by default under the category name `General` in the `Actions` ribbon. 

If you want to change it, you can:
1. In the page extension, create an empty group first in Processing with the caption set as the name that you want to be displayed as category.
2. In the page extension, add your new action at the place you want it (as you did).
3. From the page customization, move your new action into the empty group you created.

Here is the code I tried:
```
pageextension 50100 JobProjectExt extends "Job Project Manager RC"
{    
    actions
    {
        addfirst(Processing)
        {
            group(EmptyGroup)
            {
                // Empty group aiming at receiving the actions moved in 
                // order for them to be displayed with a category different
                // than general.
                Caption = 'Promoted actions';
            }
        }

        addafter("Manager Time Sheet by Job")
        {
            action(MyNewAction)
            {
                Caption = 'My New Action';
                Image = Calculator;

                ApplicationArea = All;                
                Visible = true;

                RunObject = Page "Customer List";
            }
        }
    }
}

pagecustomization JobProjectCust customizes "Job Project Manager RC"
{
    actions
    {
        movefirst(EmptyGroup; MyNewAction) 
    }
}

profile JobProjectProfile 
{
    Description = 'My Job Project Profile';
    RoleCenter = "Job Project Manager RC";
    Customizations = JobProjectCust;
}
```

It renders this way:
![image](https://user-images.githubusercontent.com/31541422/39747121-acea3c3e-52ac-11e8-92a5-025687060f78.png)

**Comment by GreatScott000** [comment]
Thank you.
