### ISSUE TITLE
The property 'DataClassification' cannot be used in this context

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#2062]
The table snippet adds a DataClassification property by default.
This compiles, but when I try to publish to the database it errors:

```
[2018-04-19 14:49:59.68] The request for path /DynamicsNAV110/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed
HelloWorld.al(20,5): error AL0124: The property 'DataClassification' cannot be used in this context
HelloWorld.al(27,13): error AL0124: The property 'DataClassification' cannot be used in this context
```

Build 11.0.20348.0
vsix: 0.15.18771

Sample code:
```
table 50141 Test
{
    DataClassification = CustomerContent;
    
    fields
    {
        field(1;MyField; Integer)
        {
            
            DataClassification = CustomerContent;
        }
    }
    
    keys
    {
        key(PK0; MyField)
        {
            Clustered = true;
        }
    }
}
```

**Comment by reiniroosh** [comment]
Just wanted to point out that I'm using the newer vsix with the older platform, which I guessing is causing the issue. Haven't had time to try and figured I'd at least report it.

**Comment by StanislawStempin** [comment]
You are using wrong vsix version. Please make sure to use the vsix that comes bundled on the product DVD:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

We will soon implemented automated version checks to inform early about vsix -> server mismatch.
