### ISSUE TITLE
SQL Error - 22922070 - 28000 -Download Symbols - finsql.exe - Unable to Connect 

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/AL#2063]
[22922070] The following SQL Server error or errors occurred:

18456,"28000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'DESKTOP-F5NR80A\dennis'.
4060,"42000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot open database "'Demo Database NAV (11-0)'" requested by the login. The login failed.

cd "C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client"
finsql.exe Command=generatesymbolreference, Database='Demo Database NAV (11-0)', ServerName=DESKTOP-F5NR80A\NAVDEMO  

:start
if exist "C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\navcommandresult.txt" goto end

goto start
:end
rem dir navcommandresult.txt

dir *.txt

notepad.exe naverrorlog.txt
pause

**Comment by dennisaubrey** [comment]
Version - NAV 2018  CU04

**Comment by dennisaubrey** [comment]
I am able to connect and run NAV 2018 and Debug in AL. It all works.

**Comment by dennisaubrey** [comment]
I have been running this same command for a couple of months.

**Comment by dennisaubrey** [comment]
Un-Installed - NAV 2018 CU02 and SQL Sever - Deleted the folders. Installed NAV 2018 CU04. Everything is working.

finsql.exe - Unable to Connect to SQL database. 

Windows security.

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/39052095-d2aee326-4478-11e8-8db8-1227b347affa.png)

**Comment by dennisaubrey** [comment]
cd "C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client"
finsql.exe Command=generatesymbolreference, Database="Demo Database NAV (11-0)", ServerName=DESKTOP-F5NR80A\NAVDEMO  

rem finsql.exe Command=generatesymbolreference, Database="Demo Database NAV (11-0)", ServerName=.\NAVDEMO

:start
if exist "C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\navcommandresult.txt" goto end

goto start
:end
rem dir navcommandresult.txt

dir *.txt

notepad.exe naverrorlog.txt
pause

**Comment by dennisaubrey** [comment]
New Batch Program.
Works.

![image](https://user-images.githubusercontent.com/36566794/39057884-6787e164-4488-11e8-9ba7-487bd3643613.png)

**Comment by StanislawStempin** [comment]
This looks like a configuration/setup problem. Since it relates to NAV 2018 please contact the regular support channel. 
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
