### ISSUE TITLE
Expose function FindAttributeValue from table "Item Attribute Value Selection" as External

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#2065]
Hi all,

Could you please expose FindAttributeValue as External, table 7504 - "Item Attribute Value Selection"?

Thanks,
Radovan

**Comment by GreatScott000** [comment]
I am using the Docker image with NAV Build 22932, microsoft/bcsandbox:gb downloaded yesterday.  This function is not marked as External.  What build was this released in?
![image](https://user-images.githubusercontent.com/4333956/42574944-88fb0f5e-8517-11e8-8d1d-67c42e1152d9.png)
