### ISSUE TITLE
Documentation on Addxxx/Movexxx anchors

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2066]
What are the Embedding and Sections anchors for the Addxxx and Movexxx tags?

**Comment by qutreson** [comment]
Hi @GreatScott000, if you want to add a new actions into the `Embedding` or `Sections` action areas of a role center page, you need to use `addfirst` or ` addlast` with the action area as anchor. If these action areas have some actions defined in the base page, you can also insert the new ones relatively to one of these actions by using ` addbefore` or `addafter`.

When adding to the `Embedding` or `Sections` , the anchor is the action area itself as in the following example. It is similar for moving actions.
```
pageextension 50100 CustomerListExt extends "Accountant Role Center"
{
    actions
    {
        addfirst(Embedding)
        {
            action(MyNewAction)
            {
                // Some code
            }
        }
        movefirst(Embedding; "&Account Schedule")
    }
}
```

We recently fixed a bug where it was not possible to use the `Embedding` and `Sections` areas as anchors if these areas didn't have any actions declared in the base page. This might be the issue you are currently facing if the page you want to extend has these two areas empty. The fix will be available with the next update.

**Comment by StanislawStempin** [comment]
Here is also the documentation link for reference: https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview

**Comment by GreatScott000** [comment]
Thank you both for the information but I still don't know what the Embedding and Sections anchors represent.  What actions typically go in them?  Is there a page you can point at the using them?

**Comment by qutreson** [comment]
You can find more details about how to use them here: https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/devenv-actions-overview

The area `Embedding` corresponds to the `Home Items` type of actions and the area `Sections` corresponds to the `Activity Buttons` type of actions.
