### ISSUE TITLE
New event in Codeunit 419 - File Managemt

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#2067]
Hi all,

Could you please add one publisher in function GetToFilterText, in Codeunit 419, like on picture below:
![image](https://user-images.githubusercontent.com/34686682/39047286-a4c3779e-4499-11e8-8b29-d21b89d476f7.png)

That publisher would support any additional extensions.

Thanks,
Radovan

**Comment by NKarolak** [comment]
Then I'd suggest to put the new publisher into a new ELSE part of the previous CASE statement. Events should fire only when necessary..
