### ISSUE TITLE
External functions request

### ISSUE THREAD

**Issue by TimothyWatkins** [Microsoft/AL#2069]
Hi there,

A request for a couple of functions to be made external. Please see below.

Codeunit "Config. Validate Management" – EvaluateValueWithValidate
Codeunit "Approvals Mgmt." – IsIncomingDocApprovalsWorkflowEnabled
Codeunit "Document Totals" – PurchaseCalculateTotalsWithInvoiceRounding

Also, is the [TryFunction] available yet? It currently does not work with versions 11.0.21395 and VSIX 0.15.19171.

**Comment by StanislawStempin** [comment]
TryFunction is not available yet. It will be available in the Business Central Fall release.
