### ISSUE TITLE
Hooks between two extensions

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#207]
Hi,

If we have two extensions made and if they make use of same object and has a link between these two extenions.

Then how is it possible in extensions 2.0.

Can you suggest us regarding this.

Thanks
Varun Reddy

**Comment by waldo1001** [comment]
How do you mean?

you can create "dependent" extensions - don't know if you mean that?

**Comment by markbrummel** [comment]
Last time I checked you had to put the NAVx file of the dependency extensions in your packages folder and then it lets you code against it.

**Comment by bvbeek** [comment]
You can define the dependencies in the app.json file here:

![image](https://cloud.githubusercontent.com/assets/28626283/25995415/723efbd0-3712-11e7-9057-6707f9233969.png)

If you install the main app, it will install the extensions that are defined here.

**Comment by waldo1001** [comment]
yes indeed: change the app.json, put the navx in the packages folder, and off you go!

an example of what you would put in the "dependencies":
`
"dependencies": [
  {
    "appId": "af3ad7a7-bd49-4897-be18-4ed63589323d",
    "name": "NameOfTheAppYouMakeADependencyOn",
    "publisher": “waldo",
    "version": "1.0.0.0"
  }
]
`

**Comment by bachii1010** [comment]
Hi all,

Thanks for the answers let me try to implement this and check
