### ISSUE TITLE
javascript builder breaks file extensions

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#2072]
The Javascript builder adds.css to scss files, but it should not do this, otherwise the files will not be found.

__In the addIn.al file:__

![screen1](https://user-images.githubusercontent.com/16351673/39122823-4c6c2370-46f6-11e8-9e0f-7536674891bb.jpg)

__In the html source in chrome:__

![screen2](https://user-images.githubusercontent.com/16351673/39122831-527dd704-46f6-11e8-9f6b-0dbfcba4637b.jpg)

**Comment by qutreson** [comment]
Hi @Gallimathias, 

 just tried to reproduce the issue you are describing and it seems that all the files are that are not .css files are getting renamed with the file extension `.css`. However, even if they are renamed they are still found as you can see in the example below:

**MyPageWithControlAddins.al**
```
controladdin ScssAddIn
{
    StartupScript = 'js/startup.js';
    StyleSheets = 'css/scssContainingOnlyCss.scss';
    RequestedHeight = 500;
    MinimumHeight = 500;
    VerticalShrink = false;
    HorizontalStretch = true;
}

controladdin AddIn
{
    StartupScript = 'js/startup.js';
    StyleSheets = 'css/cssFileWithoutExtension';
    RequestedHeight = 500;
    MinimumHeight = 500;
    VerticalShrink = false;
    HorizontalStretch = true;
}

page 50300 PageWithAddIn
{
    layout
    {
        area(Content)
        {
            usercontrol(ControlName; ScssAddIn)
            {
                ApplicationArea = All;
            }

            usercontrol(ControlName2; AddIn)
            {
                ApplicationArea = All;
            }
        }
    }
}
```

**startup.js**
```
var container = document.querySelectorAll("#controlAddIn")[0];

function addDiv(cls){
    var div = document.createElement("div");
    div.className = cls;
    container.appendChild(div);
    return div;
}

addDiv("bg");
```

**cssFileWithoutExtension**
```
.bg {
    background: blue;
    height: 30px;
}
```
**scssFileContainingOnlyCss.scss**
```
.bg {
    background: blue;
    height: 30px;
}
```

which gets rendered in the client as follows:
![image](https://user-images.githubusercontent.com/31541422/39813187-bdda973a-538f-11e8-971c-c75de4256020.png)

The problem you are facing here is that only .css files are currently supported and the style sheets you are putting in your control add ins are then interpreted as .css files whatever their extension is. 
So if your .scss file contains some scss features that are not available in .css files (like using variables for instance), then the style won't be rendered at all. 

A workaround for you is then to compile the .scss file and include it as a .css file in your AL project.
