### ISSUE TITLE
Support for XML Request Pages in the web client

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#2075]
I tried to tricked the file handling (_which does not work with extensions yet, but we urgently need it_) with xml ports. When opening the XML port crashd NAV with the message that the request page would not exist.

__Error from XML Port__

![xmlporterror](https://user-images.githubusercontent.com/16351673/39172303-a57fffee-47a1-11e8-96d2-a2e9c0b0c4f9.jpg)

XML Port
````JavaScript
xmlport 50206 Exporter
{
    schema
    {
        textelement(NodeName1)
        {
            tableelement(FileContent; FileContent)
            {
                trigger OnAfterGetRecord()
                var
                    writer: InStream;
                begin
                    FileContent.CalcFields(Data);
                    FileContent.Data.CreateInStream(writer);
                    currXMLport.SetSource(writer);
                    currXMLport.Quit();
                end;
            }
        }
    }

    requestpage
    {
        layout
        {
            area(content)
            {
                group(GroupName)
                {
                    field(Name; FileContent.Id)
                    {
                        ApplicationArea = All;
                    }
                }
            }
        }
    
        actions
        {
            area(processing)
            {
                // action(ActionName)
                // {
                    
                // }
            }
        }
    }
}
````

**Comment by DominikDitoIvosevic** [comment]
Hi @Gallimathias . We do not support xmlports in the web client yet

**Comment by SirBETE** [comment]
Requestpages of XML ports aren't supported in the webclient ... (windowsclient works but that isn't available in BC).

**Comment by DominikDitoIvosevic** [comment]
He was correctly correcting me that only the request pages are not supported.
https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client#Objects

**Comment by SirBETE** [comment]
The requestpage of xmlports is suppported in windows clients. But the windows client doesn't exist in BC.
Thank you for the link Dominik, wanted to post it too, but couldn't found it ... :)

**Comment by StanislawStempin** [comment]
Since this is a web client feature request we will not track it in this repository. Instead it should be tracked through the Ideas site: https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1
