### ISSUE TITLE
Txt2al - Quote table fields as part of the conversion process

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#208]
In this case, the field Code are highlighted:

`Record.Code := 'ABC'`

**Comment by waldo1001** [comment]
I noticed it as well - obviously because "code" is a datatype .. :-/

As a suggestion (to Microsoft), why not place all fields between double quotes by default?  I don't know it's possible - but it would be very consistent - and who can argue consitency? ;-)

**Comment by kaspermoerch** [comment]
This issue is related to the way syntax highlighting is handled by VS Code as explained in #101

**Comment by bvbeek** [comment]
@kaspermoerch a little bit, in your post it goes about the **Modify** and **Testfield** names.

It would be nice to solve this problem, because **Code** is not a reserved word in AL Code.

I like the suggestion of @waldo1001

**Comment by doivosev** [comment]
Couldn't you also just enforce the quoting to yourselves by having it as a coding guideline while we leave the same choice to others?

**Comment by bvbeek** [comment]
Yes, that could be an option, but when I generate the AL code using the tool Txt2Al.exe, I have to modify all the references to Code fields. That's a lot of work. So it would be nice if fieldnames has double quotes by default.

**Comment by StanislawStempin** [comment]
We cannot do much about syntax highlighting for now. I will change the title and use this issue to track proposal for quoting all table fields as part of the txt2al conversion process.

**Comment by StanislawStempin** [comment]
After further consideration we will not implement this suggestion. We will instead rely on semantic syntax highlighting once it is available from VS Code.
