### ISSUE TITLE
GroupBy On list or allow list as parameter on Dictionary

### ISSUE THREAD

**Issue by eaathan** [microsoft/AL#2082]
Using AL Compiler version 0.15.18771.

We would very  much like a "group by" function on the list. In C# this is done by Linq so don't know how hard it is to implement for you guys.

**Comment by DominikDitoIvosevic** [comment]
Hi @eaathan . While it sounds nice, it's a big feature. We cannot just add "group by", we would have to add all linq methods then. Definitely we should do this at some point in the future, but there are more pressing matters at hand

**Comment by Gallimathias** [comment]
Introducing all Linq methods sounds very good ^^.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
