### ISSUE TITLE
txt2al.exe problem with PageType=CardPart

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#2085]
txt2al.exe doesn`t handle added control actions and page actions on pages of PageType=CardPart. Or I think the problem is the PageType=CardPart.

steps-to-reproduce:
Problem1: added one control action to the page:9025 and try to run txt2al.exe for the delta file 
Problem2: added one page action to the page:9025 and try to run txt2al.exe for the delta file 

attached the example data files:
[PAG9025 example with added one control action.DELTA.txt](https://github.com/Microsoft/AL/files/1946251/PAG9025.example.with.added.one.control.action.DELTA.txt)
[PAG9025 example with added one page action.DELTA.txt](https://github.com/Microsoft/AL/files/1946252/PAG9025.example.with.added.one.page.action.DELTA.txt)

**Comment by Pieterheinevdm** [comment]
some back-ground info: for an app I have to modify the report:"Aged Accounts Receivable". So I have copied this report and applied the code changes. Next steps is to set visible property to false for all page actions calling the original nav report. Then added a page actions which will call my copy report.

**Comment by DominikDitoIvosevic** [comment]
Hi @Pieterheinevdm . Your delta files seem to be missing a key part, namely something like "InsertAfter=AddAfter:MyAction(Action 133);"

Which version of the platform are you using? Are you generating the delta file using -ExportToNewSyntax ?

**Comment by Pieterheinevdm** [comment]
ps. sorry for the late response, I have been on vacation.
the InsertAfter is available in the first delta file. 
In the second deltafile the InsertAfter doesn't exists because in the original object there are no actions

The delta files has been generated by 2018cu4
The txt2al.exe version I have used is the one in the folder of 12.0.21229.0

**Comment by DominikDitoIvosevic** [comment]
@Pieterheinevdm could you please describe what you mean by "doesn't handle"? Are you saying they aren't showing up in the client? Did you add the proper application areas?

**Comment by Pieterheinevdm** [comment]
there are 2 problems:
the first problem is basically no support for extending control actions of a page, this is being handled by in issue #2087

**Comment by Pieterheinevdm** [comment]
the second problem:
I have added one page action in CAL to a page of type CardPart and this page didn't have any actions yet.
when processing the delta file of this change with the txt2al.exe tool I get the error:
----ERROR----
Error converting file:c:\merge\MFSL_2018W1CU4_AL\Create-NAVDelta\AppFiles\PAG9025.DELTA
De objectverwijzing is niet op een exemplaar van een object ingesteld.

Total Time: 0:00:01,0064415
Errors: 1
The delta files has been generated by 2018cu4
The txt2al.exe version I have used is the one in the folder of 12.0.21812.0

**Comment by Pieterheinevdm** [comment]
[PAG9025.DELTA.txt](https://github.com/Microsoft/AL/files/2005583/PAG9025.DELTA.txt)
