### ISSUE TITLE
Error after publishing table/page extension: The connection to the server was suspended

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#2086]
Add a table extension:

```
tableextension 50000 "BRU Item Extension" extends Item
{
    fields
    {
        field(50000; "MFI Min Value"; Decimal)
        {
            DataClassification = CustomerContent;
        }

        field(50001; "MFI Max Value"; Decimal)
        {
            DataClassification = CustomerContent;
        }
    }
}
```

Add a page extension:

```
pageextension 50000 "Item Card Extension" extends "Item Card"
{
    layout
    {
        addafter(Item)
        {
            group(Attributes)
            {

            }
        }

        addfirst(Attributes)
        {
            field("MFI Min Value"; "MFI Min Value")
            {

            }

            field("MFI Max Value"; "MFI Max Value")
            {

            }
        }
    }
}
```

Create a new NAV2018-nl container. Info:
> Using image microsoft/dynamics-nav:2018-nl
> Using license file C:\temp\lic.flf
> NAV Version: 11.0.21441.0-nl

Publish the extension to the new container and open the item list. Nothing happens. Click any other menu item and the error 'The connection to the server was suspended' appears.

![image](https://user-images.githubusercontent.com/14080280/39237662-669318b2-487c-11e8-8e04-68651013a389.png)

I've created multiple new container just to be sure the problem isn't in the particular container but the same thing happens every time. If I remove just the page extension, it works fine.

**EDIT:
To narrow it down even more; rename the "MFI Max Value" to "MFI M-Value" and now it works just fine.
Seems like I cannot use "MFI Min Value" and "MFI Max Value" together in the same page extension.**

**EDIT2:
"MFI Min. Value" and "MFI Max. Value" also works fine. This is one creative little platform bug I've stumbled accross.**

**Comment by thpeder** [comment]
Hi @erikrijn,

Thanks for reporting the bug.

The issue you are facing there is that we generate a hash for each page control and you have a collision with the base app, namely for your "MFI Max Value".
You have to rename the control to something else, like you did with adding the period.
I'm working on introducing more checks into the compiler so you will see an error for your extension.

Thanks,
Thomas
