### ISSUE TITLE
Code comment with brackets are not highlighted as comment

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#209]
```
{
<Code Line>
<Code Line>
}
```

**Comment by waldo1001** [comment]
https://github.com/Microsoft/AL/issues/141
:-)

**Comment by bvbeek** [comment]
;-) that's nice, next time I will search before I post :)

**Comment by kalberes** [comment]
We have been only supporting /* */ for multiline comments, since the last few updates. 
Using {} will lead to compiler errors.
