### ISSUE TITLE
Make PublicWebBaseUrl available through get request on the Dev endpoint

### ISSUE THREAD

**Issue by tfenster** [microsoft/AL#2090]
Not sure if this is the right place to ask for it as it is more about the NAV Server development service, but as the background is a VS Code extension, I'd like to give it a try. Please let me know if I should open this somewhere else.

I have a small VS Code extension which allows to run the currently opened object without publishing it (a bit like "Run" in C/SIDE). This works by getting configuration settings from launch.json and creating the matching URL like <server>/<instance>/?page=<id>. However if the user configured a port other than 80 for the WebClient, this will fail. I could add some configuration setting for that, but I noticed that the standard AL extensions gets the PublicWebBaseUrl as response after publishing an app. However I don't want to necessarily publish before running and also don't want to re-implement publishing. Would it be possible to make the PublicWebBaseUrl available through a GET request at the developer service?

**Comment by StanislawStempin** [comment]
This is definitely possible. We will add it to the backlog since we have plans for "run without publish" feature.

**Comment by tfenster** [comment]
@StanislawStempin Were you able to make any progress on this or have an idea when progress might happen?
