### ISSUE TITLE
Object of type CodeUnit with ID 132201 could not be found error while running test tool

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#2094]
Hi

I am getting the below error as shown while running Test tool in business central latest update.

![image](https://user-images.githubusercontent.com/26792519/39300489-800cb0a8-4969-11e8-9ee9-a99064b0f2a8.png)

Please suggest?

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
You seem to be missing codeunit 132201 on your server. Please import the test toolkit before trying to run tests. 
It is not possible to run automated tests on Cloud Sandboxes right now. Only on Container Sandboxes.

**Comment by bachii1010** [comment]
@StanislawStempin  i have created a container with docker image and i am running the test tool from there   so it should work there.

also can you please let us know how can we import the test tool kit as i am using AL for this and added tag **_test_** in app.json.

Please suggest

**Comment by bachii1010** [comment]
@StanislawStempin  i used the below command and this worked me for solving the above error in container sandbox BC.

> `Import-TestToolkitToNavContainer -containerName navserver`

also can you tell me when it will be available in cloud?

**Comment by StanislawStempin** [comment]
Currently testing needs to happen in the container sandboxes. 
Adding support for cloud sandboxes in on a longer-term backlog.
