### ISSUE TITLE
[ExternalReq] ChangeStatusOnProdOrder CU5407

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#2098]
Hi

Please mark as external function "ChangeStatusOnProdOrder" CU5407

Maybe add a new type of "target" in app.json that allows to use any functions will save you from tons of this requests 😆 

Thank you
S.

**Comment by thpeder** [comment]
It will be available in the coming developer preview.

If you are only targeting on-prem then you can change the target to "Internal", but the whole point about the target is to not allow every procedure in the Cloud version.

**Comment by anuj-inecta** [comment]
Hi Team, 
Could you please confirm if function "ChangeStatusOnProdOrder" CU5407 is going to be marked as 'external' in future releases.

Thanks!
