### ISSUE TITLE
Keys now have names?

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#210]
Is there a specific reason why you've decided to give keys name? Not complaining, just curious. Can you reference to a key with the name?

Like

SETCURRENTKEY("ItemTrackingByLot");

Instead

SETCURRENTKEY("Lot No.", "Item No.", etc...);

That would make the key into an object you can more easily read and replace

**Comment by esbenk** [comment]
That is the plan in an upcoming version.

**Comment by StanislawStempin** [comment]
This is tracked by #140.  I will close this issue
