### ISSUE TITLE
Translate native objects still not working

### ISSUE THREAD

**Issue by NickLin1017** [Microsoft/AL#2100]
Related to this one:#2064

I need to translate native objects. But I do not know how to do better.

According to #2064's answer:
To translate native objects you need to use the same .txt translation files as you would have used the past and just include them somewhere in the project folder.They will be automatically picked up by the compiler.

I put translation.txt files into my project and publish to my server but it still no working.
Is there anything else I should know ?

**Comment by thpeder** [comment]
Hi @NickLin1017,
I'm not sure what you mean by native objects, but have you had a look at the documentation?
[Working with Translation Files](https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)

**Comment by dennisfrostlander** [comment]
Hi @NickLin1017,

If you are having the issues with translating base objects using the old txt format, would you be able to narrow it down to a simple case that you could share with us?

For example:
I have a base code unit which has a TextConst with a value "Good evening"
```
OBJECT Codeunit 50105 50105
{
  OBJECT-PROPERTIES
  {
    Date=18-05-01;
    Time=12:02:47;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    OnRun=BEGIN
            MESSAGE(MyConst);
          END;

  }
  CODE
  {
    VAR
      MyConst@1000 : TextConst 'ENU=Good evening';

    BEGIN
    END.
  }
}
```

Then I add an extension which has the following translation file translations.txt anywhere in the project:
```
C50105-P2818-L30:50105
C50105-Q1000-P2818-L128:MyConst
C50105-Q1000-P26171-A1033-L999:Good night
```

When I run the codeunit, I get the modified value of `Good night`
```JavaScript
pageextension 50106 TranslationExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Codeunit.Run(50105);
    end;
}
```

![image](https://user-images.githubusercontent.com/16953692/39469544-1769f712-4d39-11e8-9696-136183dab0c5.png)

**Comment by NickLin1017** [comment]
@thpeder 
Thank you for your response
Yes,I have already seen that file.
It seems that only custom Fields can be translated.

@dennisfrostlander 
Thank you for your response.
I mean to translate a native page.
For Example:
I want to translate words marked in yellow.
![image](https://user-images.githubusercontent.com/34726930/39682221-3b324ce2-51e1-11e8-808f-c011a7351aa4.png)

Then I add an extension which has the following translation file translations.txt anywhere in the project:
![image](https://user-images.githubusercontent.com/34726930/39682401-33bfb2dc-51e2-11e8-8117-c14b6f981ae0.png)

When I run the Customer Card, I can not get the modified value.

**Comment by DominikDitoIvosevic** [comment]
@NickLin1017 could you please tell us which version of the AL extension and platform are you using? Did you generate the .txt file using CSIDE as described here https://docs.microsoft.com/da-dk/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files ?

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
I use AL Language 0.15.18771 and Publish on Nav 2018.
Yes,I generate the .txt file using CSIDE.

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
I re-generate Translate.txt file.
I succeed! Thank you very much.

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
Just beginning there is a correct display of the translation.
But I use notepad to re-save translate file,then the translation will fail to display.

**Comment by DominikDitoIvosevic** [comment]
@NickLin1017 the problem could be because you are using notepad which you shouldn't. Could you please try not opening with notepad but with Visual Studio Code instead? I think what might be happening is that when you save with notepad the encoding of the file changes and then the file gets broken somehow.

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
Thanks,
I have no problem with Visual Studio Code.
But how can we switch language to our target language in D365 BC?
Or is there anything else we should do or pack in to extension besides translation file?

**Comment by DominikDitoIvosevic** [comment]
@NickLin1017 are you talking about .xliff or .txt translation files?

**Comment by NickLin1017** [comment]
@DominikDitoIvosevic 
I talking about translation files.
I have no other language options,so I can't see my Translate Extension result in other languages.
![image](https://user-images.githubusercontent.com/34726930/39802419-926cfa6e-53a0-11e8-89aa-53f10bb17bd1.png)

**Comment by thpeder** [comment]
Not to keep the same discussion in two different places, since your question has also been asked here #2162 I'll close this Issue.
