### ISSUE TITLE
Please include ZXing or similar DLL for barcode generation

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#2104]
I'm aware that we could create an Azure service and call it from NAV (https://github.com/Microsoft/AL/issues/744), but including barcodes/QRs in reports is something that many customers request, and it seems odd to require an external service + associated costs just to do it, specially when Microsoft could solve it by including ZXing (https://github.com/micjahn/ZXing.Net) and creating a wrapper codeunit so that we could invoke it.

(And, let's be fair, some customers are still a bit reluctant to move to the cloud. Anything that's harder to implement in BC than on premise, it's just another excuse for them to stay on premise)

We've actually done something similar ourselves in the past, and an AL function with this signature:

     Encode(Value: Code[1024], Format: 'AZTEC,CODBAR,CODE39...', Height: Integer, Width: Integer, VAR TempBlob: TEMPORARY Record TempBlob)

Would allow us (partners) to include barcodes in reports, without external costs, and without the need for every partner to reimplement the same code.

I can understand the security implications of adding extra DLLs to Business Central, and that for Microsoft this is not so simple as just including a DLL and call it a day, but I also think that this would greatly help developers, cover a use case that many customers require, and give an edge to BC over other ERPs that don't include this functionality as standard (or compete with others that *do* include it).

**Comment by erikrijn** [comment]
You could just create a rest service that returns a base64 encoded barcode image. If you can wait a few days, I'd be happy to provide you with a code sample to set up an app service or azure function.

**Comment by salgiza** [comment]
@erikrijn Thanks a lot for offering an example on how to create such a service, but this ticket is precisely about being able to do it without calling/deploying an external service!

**Comment by erikrijn** [comment]
Well Microsoft has been clear from the beginning that additions like this will have to be done using API's. Sure you might find this addition super important, but along comes the next person who needs something else which he/she considers core functionality. And so on, and so on.

**Comment by dennisfrostlander** [comment]
Thanks for the suggestion. We will have another discussion between the teams on this topic. As it was correctly mentioned, it's not a straightforward process to host a 3rd party DLL on Business Central servers.

**Comment by ShadowXVII** [comment]
We'd like to see some sort of native Barcode encoding mechanism too. We could use an Azure function, but there'll be a latency involved which would be tricky to work around. E.g. generating unique labels for hundreds of items on an order would take forever to generate the barcodes and bring them back into the system.

**Comment by EasyStep2Lean** [comment]
Agree, Use either Zxing of any other Encoding library, is core functionality in the current ERP world where tracebility is an ever increasing demand, and using barcoding for this is eminent. Latency is also my worry using the Azure functions. Simple wrapper function being able to create barcodes please. You can get our function for free microsoft but I think building one yourself would take your guys max 4 days

**Comment by fvet** [comment]
> You could just create a rest service that returns a base64 encoded barcode image. If you can wait a few days, I'd be happy to provide you with a code sample to set up an app service or azure function.

@erikrijn As every ISV, we're looking into moving our Barcode bitmap creator (using xzing) towards an Azure function. We're facing some issues right now, since System.Drawing seems not supported in the Azure function. Any hints on how to move forward? (without having to wait for the nth release where MS will eventually come up with a standard solution)

**Comment by daansaveyn** [comment]
> return image.ToBase64String(ImageFormats.Png);

Thank you:)

**Comment by pborring** [comment]
As we have 1D and 2D barcode fonts support in BC SaaS now, along with Barcode module in System, I am closing this entry
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes

For any further support or requests, please log an idea on http://aka.ms/bcideas.
