### ISSUE TITLE
Codeunit 9651 - OnBeforeMergeWordLayout event

### ISSUE THREAD

**Issue by Chielve** [Microsoft/AL#2107]
Hi,

We are upgrading our connector to an extension and have modified the MergeWordLayout function in codeunit 9651. 

We need an event there that uses the Handled design pattern.

![onbeforemergewordlayout event](https://user-images.githubusercontent.com/13106808/39425398-8b713116-4c7b-11e8-888b-d7bab7d338c6.PNG)

**Comment by rvanbekkum** [comment]
+1 This would really help us out as well for customizing the report layout implementation. There are currently no events like this for customizations in this area, so this would be a good addition.
