### ISSUE TITLE
Error while publishing App from VScode: A task was canceled

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#2108]
I found out on issue #1633 that my App can successfully been published via PowerShell, but VScode gives me errors.

On Current Build of BC I get the error message `A task was canceled`, although the app was successfully published.
```
[2018-04-28 16:29:04.78] Publishing package to tenant 'default'
[2018-04-28 16:29:04.79] Sending request to https://bcsandbox-dago.westeurope.cloudapp.azure.com:7049/NAV/dev/apps?tenant=default&SchemaUpdateMode=recreate
[2018-04-28 16:34:04.85] Error: A task was canceled.
```

**Comment by DanielGoehler** [comment]
@DominikDitoIvosevic follow up to #1633 regarding VScode Flow

**Comment by dennisfrostlander** [comment]
You are hitting a 5 minute timeout when publishing from VSCode.

When you publish and install the extension from PowerShell, does it take more than 5 minutes to complete both operations?

**Comment by StanislawStempin** [comment]
We have extended the timeout as the direct mitigation for your problem. We are also looking at other performance improvements for the Fall release.
