### ISSUE TITLE
Compiler checks for Empty RDLC files, Unsupported Subscriber Names and Modifying OptionCaptionML

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#2109]
In issue #1633 I learned from @cmrudolph-msft that there are at least a few issues in my App that are producing errors on the compiler inside the Service Tier, but did shown as error in VScode (Pre-Compiler).

- Empty RDLC-Files
- Unsupported Event Subscriber Procedure Names (OnBeforeInsert, OnAfterInsert, OnBeforeModify, …)
- Modifying OptionCaptionML of existing Pages (at least with more OptionCaptionML-Values than Option-Values)

**Comment by StanislawStempin** [comment]
There is no such thing as pre-compiler vs compiler. It is the exact same compiler running in VSCode as the one running on the server.

The issues you mention are new features required in the compiler to capture invalid state that are currently only exposed in the server runtime. I will use this issue for tracking these improvements.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

This issue contains multiple new suggestions for compiler validations. If they are still making development unpleasant, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.

We are constantly monitoring top ideas and will consider them for a future release.
