### ISSUE TITLE
Need access to importing RapidStart files via code

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#211]
We've been working with the ICAP team and out of that we've created functionality by which a new user can download some evaluation data into their system so they have some configured data based on a questionnaire wizard that we provide to them.

This is done by hosting various RapidStart package files on Azure Blob Storage and then downloading and installing them.

All of this works within the extensions v1 platform, and on the v2 platform I've converted over the HTTP calls to use the new variable types, however there are still functions that we need that are not supported on the v2 platform:

(the following are used to create the physical RapidStart file from the downloaded binary stream)
- File Mgmt --> ServerTempFileName
- File.CREATE
- File.CREATEOUTSTREAM
- File.CLOSE

(the following are used to import and apply the physical RapidStart file)
- Config Package Import --> ImportRapidStartPackage
- Config. Setup --> ApplyPackages

Can we please get these supported? The functions we use above are essentially the exact same ones that are used in the base product to load the evaluation data into a company when a new company is created, so perhaps a "safe" api can be created for us to use?

**Comment by StanislawStempin** [comment]
We will look into providing a set of safe APIs to enable this scenario.

**Comment by StanislawStempin** [comment]
This area has been refactored to work without reliance on files. A new set of functions have been introduced:
COD8620:
ImportRapidStartPackageStream
ImportAndApplyRapidStartPackageStream
