### ISSUE TITLE
Suggestion txt2al: Procedures of Table Extension should be transfered

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2111]
Similar to #1509, could the procedures for a Table Extension be transferred?  Everything else is, even the global variables used by the procedures but not the procedures themselves.

**Comment by qutreson** [comment]
Hi @GreatScott000, the txt2al should be converting the procedures from table extensions either directly into AL code (when inserting a new procedure) or into commented code (when an existing procedure is modified). If we are missing one case and you have a repro for it, can you share your repro here?

**Comment by GreatScott000** [comment]
I was using the February build.  The 12.0.21229.0 build appears to work fine.  Sorry for the confusion.

**Comment by qutreson** [comment]
According to #1509, the fix was part of the February update (version 0.14.1746). Closing the issue as exporting procedures in table extensions is now working on the latest versions of the extension.
