### ISSUE TITLE
How to declare an Option variable/parameter?

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2112]
I can't seem to find documentation or an example of how to declare an option as a variable or as a parameter.

Can someone point me to documentation or provide an example for this?

**Comment by dennisfrostlander** [comment]
```JavaScript
codeunit 50101 TestCodeunit
{
    procedure HelloWithOptions(OptionParameter : Option A, B)
    var OptionVariable : Option C, "or D";
    begin
    end;
}
```

**Comment by GreatScott000** [comment]
Thanks, I tried everything but that.
