### ISSUE TITLE
Table Record Size Limit and Table Extensions

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2113]
I am in the process of converting a custom to an extension and was upgrading the custom to NAV 2018 and then on to BC.  Prior to making it an extension when I encountered a problem and it led me to wonder if there is any concern related table extensions.

The issue is that we have added a number of fields to a table and now that table record size (due to new base fields) exceeds the 8000 byte limit.  While moving the new fields to a table extension eliminates this issue, is there any limit on the _combined_ table record size?  I know the table extension data is maintained in a separate SQL table but might there be a limit related to how the _joined_ table is handled internally (as I have no idea how this is handled)?

With the possibility of multiple extensions extending the same table, this could be a real problem if there is a limit.

**Comment by fvet** [comment]
Check #1777

**Comment by GreatScott000** [comment]
Sorry, missed this.  Thanks for the information.
