### ISSUE TITLE
Suggestion: conditional operators

### ISSUE THREAD

**Issue by erikrijn** [microsoft/AL#2115]
I would like to suggest adding conditional operators (like we have in c#) to AL for some cleaner code.

Without:
```
if Attribute."Comparable on Storefront" then
    JsonHelper.AddValue(M2Attribute, 'is_comparable', '1')
else
    JsonHelper.AddValue(M2Attribute, 'is_comparable', '0');
```

With:
`JsonHelper.AddValue(M2Attribute, 'is_comparable', Attribute."Comparable on Storefront" ? '1' : '0');`

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
