### ISSUE TITLE
[Question] Azure AD authentication for BC WebServices

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#2116]
Hi,

Is there any documentation available regarding the authentication to the NAV WebServices with Azure AD?

I found [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps) and managed to access using the Web Service Access Key, however the Azure AD/OAuth2 authentication gives some trouble. What would be the correct Resource, Client ID, Client Secret and so on? 

Thanks

**Comment by dennisfrostlander** [comment]
@SBalslev @SusanneWindfeldPedersen 
Do you know if there are any additional documentation/walkthrough on how to properly configure AAD Oauth2 authentication?

**Comment by kvaldik** [comment]
I had an issue with the invalid resource as well. See [#1943](https://github.com/Microsoft/AL/issues/1943) for what resolved my issue.

It took me quite some time to get this working properly so a good walk through would be nice to have.
