### ISSUE TITLE
Expose list of functions

### ISSUE THREAD

**Issue by zhaohowie** [Microsoft/AL#2117]
Could you please expose those functions for the extensions (V2),

SetDoNotFillQtytoHandle in the Report "Get Source Documents"
GetLastReceiptHeader in the Report "Get Source Documents"
SetOneCreatedShptHeader in the Report "Get Source Documents"
SetOneCreatedReceiptHeader in the Report "Get Source Documents"
SetSkipBlocked in the Report "Get Source Documents"
SetHideValidationDialog in the Codeunit "TransferOrder-Post Receipt"
Calculate in the Codeunit "Calculate Prod. Order"
SaveFileDialog in the Codeunit "File Management"
ServerTempFileName in the Codeunit "File Management"
DownloadToFile in the Codeunit "File Management"
DOWNLOAD in the File
TEXTMODE in the File
CREATE in the File
CREATEOUTSTREAM in the File
Open in the File
Close in the File

Thanks,

**Comment by dennisfrostlander** [comment]
Please note that for security reasons when running in the cloud, much of the File management functionality cannot be exposed. For the other requested methods, sending a request to the owning team.

**Comment by DuttaSoumya** [comment]
Hi @zhaohowie, We are going to expose much of what you asked for, except the File handling part.
