### ISSUE TITLE
Cdu 80 - OnAfterPostSalesDoc

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#2118]
I am looking at the event signature for this event and am comparing this between the US and the DE version, I have not looked into other versions yet (using the current release).

I am noticing differences in the signatures:

US:
`
VAR SalesHeader : Record "Sales Header";VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line";SalesShptHdrNo : Code[20];RetRcpHdrNo : Code[20];SalesInvHdrNo : Code[20];SalesCrMemoHdrNo : Code[20];VAR SalesInvHdr : Record "Sales Invoice Header";VAR SalesCrMemoHdr : Record "Sales Cr.Memo Header";CommitIsSuppressed : Boolean

`
DE:
`
VAR SalesHeader : Record "Sales Header";VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line";SalesShptHdrNo : Code[20];RetRcpHdrNo : Code[20];SalesInvHdrNo : Code[20];SalesCrMemoHdrNo : Code[20];CommitIsSuppressed : Boolean
`

This makes it impossible to create an app that can be deployed in the US and Germany at the same time, if it uses this event. Can I get some insight as to why there are differences and if there is a valid reason for this? I was under the impression that event signatures wouldn't change between localizations - or at least they shouldn't change, if you want us to provide apps in multiple countries.

And while this is not necessarily an AL issue and also not a "function expose", I am requesting a "function fix".

**Comment by ajkauffmann** [comment]
Same counts for the GB version. Got an app declined because of this same issue, while the app was accepted in the US version.
