### ISSUE TITLE
Warning: Field 'xx' is not part of the keys...

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#212]
We "borrowed" the concept of Item Attributes and used them in our extension for another entity. This involved copying a few objects so that we could redirect them to our tables. In any case, when I try and convert some of the pages to the v2, platform, I am getting some errors on a few of the page fields.

This is the warning I am getting:

![img_20170512_094542](https://cloud.githubusercontent.com/assets/5204734/26001141/5a40da58-36f9-11e7-86a8-2253ca338f83.jpg)

This structure that I've used is identical to the base object Page 7504 (Item Attribute Value List) so it should work fine. The warning message needs to be corrected as I am using a field that is in an index, just not the primary key one.

**Comment by NavBitsAndBytes** [comment]
Further information.........these are the keys in the table that is referenced in the error. Again, this follows the exact structure as seen in the base Table 7500 (Item Attribute).

![screenpic1](https://cloud.githubusercontent.com/assets/5204734/26001360/16cb775a-36fa-11e7-9002-e0ef6ba3e1c4.png)

**Comment by kalberes** [comment]
This is just a warning. Isn't it? I know you cannot suppress it right now, but probably we will support that one to one day.
The message is misleading on the other hand, it should not emphasize the PK, but part of any key with a SQL index backing it. That we will change.

**Comment by NavBitsAndBytes** [comment]
Yes you are correct, it's just a warning not an error as I had stated. I updated the issue accordingly.

**Comment by dennisfrostlander** [comment]
After some consideration, we will remove this warning from the compiler. It is not a trivial task to predict the optimal execution plan in the underlying database based on table relation. Especially, when it comes to more complex expressions with WHERE statements and so on.
