### ISSUE TITLE
How to "generate" "NAV App xxx" table content

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2120]
I have recently tried to deploy an extension to a (NAV2018 CU4) database created from scratch using the "New Database" option of finsql.exe. Then I imported the base application via import and created a company. But now I find myself with the [NAV App xxx] tables all empty and therefore deploying an extension to this database does not work. The error I get is that the symbols for "Microsoft.System" and "Application" cannot be found.

I have then tried to generate symbol references by running `finsql.exe` with `command=generatesymbolreference` and it exited without error, stating that the command completed sucessfully after 227 seconds. But the records in theese tables did not appear. I don't even know if they are supposed to?

Anyway: how am I supposed to generate those records when NOT starting from a CRONUS database?

**Comment by dennisfrostlander** [comment]
Hi @hemisphera,
In general, the [Nav App] tables are populated when you publish the extensions using Publish-NavApp cmdlet (or when you publish from VSCode).

The _System_ and _Test_ symbol package can be found in program files as described [here](https://blogs.msdn.microsoft.com/nav/2018/02/02/import-symbols-in-new-or-upgrade-databases-with-microsoft-dynamics-nav-2018/).

Now, the _Application_ symbols you have generated yourself using finsql.exe command=generatesymbolreference. In this case, the Application symbols are not persisted in the [Nav App] table, but they are available at runtime on the server (physically individual symbols are stored in [Object Metadata].[Symbol Reference] column). 
So if you enable the setting EnableSymbolLoadingAtServerStartup as described [here](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side#dynamics-nav-server-setting), you should be able to publish extensions.

**Comment by StanislawStempin** [comment]
Please have a look at the upgrade checklist, Task 18:
https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data
