### ISSUE TITLE
Obsolete property for functions / event publishers

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#2121]
We could really use an obsolete property / attribute on functions and event publishers. Right now we are adding lots of event publishers to the application to allow us isolating our code, while at the same time posting requests here and / or find that others have already done so because they have the same requirements.

Now, while waiting for the publisher to become available in the base application, we still use the one we have created in the meantime. But once the "official" publisher becomes available, I'd like to mark mine as obsolete and require others to use the official one, as opposed to deleting it, which would be breaking stuff.

Another scenario is: I have created a publisher but I need to change signature for whatever reason. I decide to add a second one because I cannot delete the original one (for portability reasons) and therefore wold like to mark the old one as obsolete.

**Comment by atoader** [comment]
@hemisphera this functionality is available starting with the wave 2 2019 release. Please try it out and let us know what you think.
