### ISSUE TITLE
[event-request]: 'OnAfterInvPostBufferPrepareXXX' on Table 49

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2122]
Would be nice to have `OnAfterInvPostBufferPrepareSales`, `OnAfterInvPostBufferPreparePurchase`, and `OnAfterInvPostBufferPrepareService` that is called at the end of each of the respective functions in Table 49.

**Comment by StanislawStempin** [comment]
These events already existed. Please try bcsandbox-master Docker image
