### ISSUE TITLE
[Suggestion] Trigger Events on Reports

### ISSUE THREAD

**Issue by bleisibach** [microsoft/AL#2125]
As per my understanding, extending existing standard reports is limited to modify the layout. From a technical perspective, I can understand this very well.

The way to override the execution of a standard report is to catch the event e.g. OnBeforeActionEvent on the page the report is started and run the modified report instead. This works well, but it might be cumbersome to find all the events where reports are started. An in times of continues integration, reports can be added on new pages….

Trigger Events for e.g. **OnInitReport, OnPreReport, OnPostReport, OnOpenPage** could help us to implement such functionality on a better place. Even when we are just firing a notification that instead of this report we suggest to use an alternative functionality….

Remains the question of what values can be passed within the signature of the trigger events. E.g. the record of the first data item, gettableview...? The settings of RunModal or RunRequestpage?

Sure, this opens the door for abusive customization, but this is the risk of event driven systems anyway. 

Are there any plans to extend the report object with techniques that would help us here?

Thank you!

**Comment by thpeder** [comment]
Hi, Please have a look if ReportExtensions solves your problem, otherwise please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
