### ISSUE TITLE
New functions must be local by Default

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#213]
![image](https://cloud.githubusercontent.com/assets/28626283/26002973/a91ae154-3731-11e7-8418-3e4be1b06d8d.png)
![image](https://cloud.githubusercontent.com/assets/28626283/26002980/b0cb41e6-3731-11e7-8d11-22cde40d815b.png)

**Comment by waldo1001** [comment]
Yes, indeed, totally agree.

two options: 
- change the "tprocedure" snippet
- create a "tprocedure_local" snippet

I would prefer the first ;-).

Wat would be able to change the "snippet" ourselves here:
https://github.com/Microsoft/AL/tree/master/snippets

**Comment by bvbeek** [comment]
Or tlocalprocedure and tglobalprocedure.

I know we can create our own snippets, but less is more ☺

**Comment by StanislawStempin** [comment]
Good suggestion. I'm leaning towards modifying the tprocedure snippet
