### ISSUE TITLE
Enable GetClientDirectoryFilesList function from File Management for extension development

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2132]
Can you make GetClientDirectoryFilesList from codeunit File Management external? 

We could then use NameValueBuffer values to mass import files using stream.

**Comment by DuttaSoumya** [comment]
Hi @ivandjordjevic , as of now we are unable to make this function exposed for extensions as it poses a security risk.

**Comment by ivandjordjevic** [comment]
Thanks @DuttaSoumya for reply. Is there any workaround you would suggest for mass uploading files from single directory into stream?

**Comment by ivandjordjevic** [comment]
@DuttaSoumya I looked at Zip Stream Wrapper - that will work. Thanks!
