### ISSUE TITLE
Cannot use the Permission property on an object

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#214]
It seems as though we cannot use the Permissions property on an object. Is this going to be supported?

**Comment by StanislawStempin** [comment]
We are looking into how to re-enable this property in a secure way.

**Comment by StanislawStempin** [comment]
The property will be enabled in the July Update. To start with you will only be able to use the property with application objects from your own module. Later on the property will be extended to base application objects for which full permissions are granted in the license.
