### ISSUE TITLE
AL List type needs a RemoveAll method

### ISSUE THREAD

**Issue by quadfin** [Microsoft/AL#2141]
The AL List type (e.g., ListOfText : List of [Text]) does not have a method to clear its contents.
You are forced to use this ugliness -- ListOfText.RemoveRange(1, ListOfText.Count);
It needs a RemoveAll method.

**Comment by atoader** [comment]
Hi @quadfin ! Please use the CLEAR method. That is the AL way of resetting variables.

**Comment by Gallimathias** [comment]
@atoader But does CLEAR internally set the list to null?  So the variable must then be reinitialized and the Garbadge Collector runs unnecessarily.

Remove all references from list and set a list to null are two diffrent things or not?

**Comment by quadfin** [comment]
Understood, just logging this low priority stuff into the queue.
CLEAR() works but does not seem 'modern development'-ish (to me).
CLEAR() is C/AL legacy whereas List of [Type] is a new language feature so I kind of expected it to behave like a modern Collection -- similar to JsonArray (which has a RemoveAll)...

If you're also a .NET, Java, or other OO-language developer and you're in the process of banging out code in AL you just naturally assume such things -- when the language doesn't comply you have to momentarily refocus your thought on the issue -- oh yeah, C/AL, CLEAR(), note: applies to List, huh -- then get on with it.  Me thinks AL should strive not to bend that universe if possible.  My two cents.
