### ISSUE TITLE
Function expose : Table 130 HyperlinkToDocument

### ISSUE THREAD

**Issue by chris-amco** [Microsoft/AL#2143]
Is it possible to expose HyperlinkToDocument in T130? Or is there an alternative way to link to a document?

Thanks.

**Comment by DuttaSoumya** [comment]
HyperLinkToDocument creates a file on the server which is considered as a security risk as of now. We are therefore unable to expose this function to extensions for the time being.

**Comment by DuttaSoumya** [comment]
The workaround is to call HYPERLINK(GetURL) in your code.

**Comment by chris-amco** [comment]
I'll give it a try. Thank you for your help.
