### ISSUE TITLE
[Question] How to set a value for an invisible field on a testpage for Test Codeunit

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#2144]
As the title.

When I create a test codeunit, I get a problem.
I can set a value for a field which has visible=FALSE but I get an error when I run test codeunit (use Test Tool page).

_Error_: **The field with ID = 41 is not found on the page.**

For NAV 2018, I can open the page, show the field and run test case again. But for D365 BC, I need do that by AL Code.
So, please show me: when i using testpage, how to set an invisible field to a visible field so that i can set a value for that field.

**_Note:_** Checked Version is W1 12.0 (21229)

**Comment by dennisfrostlander** [comment]
Hi @hgnamvn,

Could you clarify how exactly you used to _show the field_ in NAV 2018? In general, this seems like a rather complicated scenario to manually make UI changes prior to running the tests. Is there possibly another way to compose the test and avoid setting values of invisible fields?

**Comment by NKarolak** [comment]
As a workaround, create and use a profile configuration where where requested field is shown (provided it is possible to add it by a simple personalization).

**Comment by hgnamvn** [comment]
Hi @dennisfrostlander,

_Show the field_ in NAV 2018, I mean that I right-click on any field caption and click _Choose Columns_ to show field on page.

Thank @NKarolak,

I am building a test project to send to MS when we submit package for bring extension to AppSource.
So i don't know whether I can do your suggest. Let me check it.

**Comment by hgnamvn** [comment]
Thank @NKarolak,

But I need a solution without import any external file. It should only be in AL.
If you can, please suggest me another solution.

**Comment by hgnamvn** [comment]
Hi!

I found out solution for this case. It is very simple. I will use page extension to show need field with the test package.

So, I close this case.
