### ISSUE TITLE
Publish Test Codeunit error when it include PREV method.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#2145]
Hi!

I build a test project.
When I build and publish my app, I get an error as bellow:

_The request for path /nav/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\120\Server\MicrosoftDynamicsNavServer$NAV\source\Codeunit\Group961b4a9b9c80f44c4c5f6f67c855cf64_Codeunit50201.cs(2969,21) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\120\Server\MicrosoftDynamicsNavServer$NAV\source\Codeunit\Group961b4a9b9c80f44c4c5f6f67c855cf64_Codeunit50201.cs(2969,68) : error CS1061: 'Microsoft.Dynamics.Nav.Runtime.NavTestPart' does not contain a definition for 'ALPrev' and no extension method 'ALPrev' accepting a first argument of type 'Microsoft.Dynamics.Nav.Runtime.NavTestPart' could be found (are you missing a using directive or an assembly reference?)_

I find out root cause.
The root cause is I call Prev method of testpage.

![error](https://user-images.githubusercontent.com/24407031/39619674-e7b14e9a-4fb2-11e8-8487-0ea71c6dc125.png)

If I comment this statement. I can build and publish my app well.

**_Note:_** checked version W1 12.0 (21229)

**Comment by DominikDitoIvosevic** [comment]
Hi @hgnamvn . We are aware of the issue, it's fixed in Developer Preview and we are backporting it to Nav 2018

**Comment by hgnamvn** [comment]
Hi !

I tested this issue on Dynamics 365 Business Central (W1 12.0 (21229)). I hope it is fixed for next release of D 365 BC.

**Comment by hgnamvn** [comment]
Thank DominikDitoIvosevic!
