### ISSUE TITLE
JsonObject needs an iterator

### ISSUE THREAD

**Issue by quadfin** [microsoft/AL#2154]
When interacting with external REST services there are many times when the response is unknown a priori.  One then needs to decode the response to make sense of it -- which involves iterating over the properties of JSON objects.

The AL JsonObject type does not support that behavior since it has no property iterator.

Also, it is difficult to determine if a JsonObject is empty (has no properties) since there is no Count() method.  (I.e., "{}" is valid JSON but if parsed into a JsonObject it is difficult to know that it is an empty object) (this interface is less important if there was an iterator)

**Comment by DennisReinecke** [comment]
This is already solved by:
https://github.com/Microsoft/AL/issues/1473

You can do a ForEach to JsonObject.Keys

**Comment by thpeder** [comment]
Hi, This seems to have been fixed. If you have other ideas for improves please go ahead and post them to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up other ideas. We're constantly monitoring top Ideas and will consider them for a future release.
