### ISSUE TITLE
Page 8614 Config. Package Card Actions do not trigger in Event Subscriber functions

### ISSUE THREAD

**Issue by ClintonSaunders** [Microsoft/AL#2156]
When creating an event subscriber function to any of the Actions on Page 8614 - Config. Package Card, they do not trigger. I think the reason is that the Action Names property has not been changed from the default (where Action[xxx]) is assigned to the Action. I have found that the event subscriber functions only fire when the Action Name property is changed from the default:
![image](https://user-images.githubusercontent.com/30843336/39686352-d33029ba-51c8-11e8-857d-6f3b1d03e681.png)

If one looks at the actions in the subform page (8625), these actions names have been changed from the defaults, and the OnAction triggers all fire successfully from event subscribers based on these actions:
![image](https://user-images.githubusercontent.com/30843336/39686427-338c834e-51c9-11e8-8990-251dc28d9aef.png)

I hope this information is sufficient.

**Comment by thpeder** [comment]
Hi @ClintonSaunders,
We have made some changes to how event subscribers work with actions a few months back.
What versions are you running?

**Comment by ClintonSaunders** [comment]
Hi there,

Sorry, I am guilty of basing my issue on the version of AL that is running with the latest hotfix of NAV 2018. I will log the issue with the NAV 2018 team if it has already been fixed in the dev preview.

I will setup a Sandbox with the latest dev preview software and test my issues there first in future before logging them on the Github issue list.

Thanks for the prompt feedback..

Clinton

**Comment by thpeder** [comment]
Since you haven't written back in some time, I'll close the issue. if you are still having an issue then feel free to open a new one.
