### ISSUE TITLE
Handling keys in NAV, and in SQL Server - Something doesn't match here, and leads to strange phenomena.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#2159]
As you know, NAV allows up to 20 fields for sorting tables. This applies not only to the secondary keys (SK), to which the missing fields of the primary key are indirectly appended, but even more so to the actual primary key (PK).

If the PK of a NAV table has more than 16 fields, the error message "Record already exists" may occur even though the NAV logic of the PK is unique.

Example: the 17th field of the primary key is an integer field (e.g. Entry No.) that is filled via the SQL server (or also by the programming itself). If the first 16 fields are identical, this strange error message appears.

This is because the SQL server (at least SQL Server 2014) converts each key of a table into an index. But on the SQL Server itself such an index may have a maximum of 16 columns (= fields). This simply truncates the subsequent fields of the primary key (in the above case the integer field) and no longer belongs to the unique key on the SQL side, which ultimately leads to the above error.

This means that primary keys must already be unique in the first 16 fields. In the above example, the integer field should therefore be created as a 16th field at the latest. To what extent it still makes sense, the 17th, 18th, etc. field in the primary key is optional.

**Comment by dennisfrostlander** [comment]
In the latest version of the AL extension, you can no longer define a key with more than 16 fields.
The compilation error is raised:
`The key 'SK' on table 'MyTable' contains too many fields.`
