### ISSUE TITLE
Txt2Al formatting - InDataSet property

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#216]
When page variables are set with the "InDataSet", when the conversion tool converts them, it puts the property on one line, and the variable on another. This seems a bit confusing and it might be better to put it all on a single line. 

This is what we get now:
```
[InDataSet]
MyPageVariable : Integer;
```
It seems cleaner if we got this instead:
`[InDataSet] MyPageVariable : Integer;`

**Comment by StanislawStempin** [comment]
We will most likely not invest in formatting improvements as part of txt2al but rather rely on the auto-formatting framework that VS Code provides. We plan to implement support for it later this year and will consider this particular case.

**Comment by atoader** [comment]
Hi @MikeGlue ! Thank you very much for your suggestion! We've thought it over and we think that having the attributes on separate lines is more future proof. As we enrich the language, we will add more attributes, and having a variable with 3 or 4 attributes on the same line might impair redability. 
We will add a rule in the formatter to add a new line before the attribute list.

**Comment by MikeGlue** [comment]
Thanks @atoader . That makes sense.
