### ISSUE TITLE
How to add new available language?

### ISSUE THREAD

**Issue by NickLin1017** [Microsoft/AL#2162]
I want to use other languages,but it only show English in my Sandbox.
How to add available language options in my sandbox?Thanks.
![image](https://user-images.githubusercontent.com/34726930/39736607-6d0e17d2-52b3-11e8-8e76-ee2af1de8388.png)

**Comment by NKarolak** [comment]
I have read the following answer from Microsoft on Yammer:

> We have enabled multi languages for the countries where is required e.g. Switzerland has Italian, French, German and English. For all non-English country versions we have added English as an option. For the Fall release we are also enabling the capability of being able to load additional languages through an extension.

**Comment by NickLin1017** [comment]
Yes, we are developing language pack through an extension now. 
But does anyone know how can we switch language to our target language in D365 BC?
Or is there anything else we should do or pack in to extension besides translation file?

Thanks,

**Comment by DominikDitoIvosevic** [comment]
Are you talking about the .txt or the .xliff translation file?

**Comment by StanislawStempin** [comment]
It is currently not possible to enable a new language in BC. We are working on a solution that will ship together with W1 being made available.
