### ISSUE TITLE
TAB77 OnBeforeSetReportLayout include function parameters in event

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#2163]
Could it be possible to add the parameters of PrintDocumentsWithCheckGUIYesNoCommon to the event OnBeforeSetReportLayout ?

```
LOCAL PrintDocumentsWithCheckGUIYesNoCommon(ReportUsage : Integer;RecordVariant : Variant;IsGUI : Boolean;AccountNoFieldNo : Integer;WithCheck : Boolean;TableNo : Integer)
OnBeforeSetReportLayout(RecordVariant);
```
using NAV2018CU3.
(If it's already implemented in BC, I will close this issue and use it as a reference for the regular NAV support).

**Comment by AlexanderYakunin** [comment]
This is already implemented in BC.

**Comment by SirBETE** [comment]
Ty! :)
