### ISSUE TITLE
AL0129 at field value assignment in dependent extension

### ISSUE THREAD

**Issue by chris-amco** [Microsoft/AL#2164]
Apologies if this has been covered before - it seems quite a basic issue but I couldn't find anything on it.

I am trying to convert a localisation feature using a base extension and a dependent extension. I created the base extension and published to the NAV server (ctrl+F5), then created the dependent extension and tried to publish it. I hit the error described in [#1018](https://github.com/Microsoft/AL/issues/1018).
Next, I tried to isolate the error by simpifying the dependent extension. This time, I got the following error:

error AL0129: The left-hand side of an assignment must be a variable or field

The error affects lines that assign a value to fields on table extensions in the base extension.

I reproduced the error with a couple of simple test extensions.
- Base extension :
  - Table extension that defined 1 additional field
```
tableextension 50000 BaseTest_TEX18 extends "Customer"
{
    fields
    {
        field(60000; TestField1; Text[100]) {} 
    }
}
```
  - Codeunit that assigns a value to the additional field
```
codeunit 50000 TestDependency
{
    trigger OnRun()
    var
        tblCustomer: Record Customer;
    begin
        if tblCustomer.FindFirst() then begin
            tblCustomer.Name := 'Standard field'; // OK - base and dependent extensions.
            tblCustomer.TestField1 := 'Extension field'; // AL0129 in dependent extension, OK in base extension
        end;
    end;
}
```
- Dependent extension :
  - Codeunit, same as codeunit in Base extension (apart from ID and name).

The codeunit compiles fine when it's in the base extension, but fails to compile when it's in the dependent extension (error AL0129). VSCode real-time compilation and intellisense in the dependent extension do not indicate any errors, so I assume that I have set up the dependency correctly.

What have I missed? Thanks in advance for any assistance.

Target server: NAV2018 (11.0.21441.0)
AL Language extension: 0.15.18771

**Comment by qutreson** [comment]
Hi @chris-amco, I just tried the code you added and I could not reproduce the error you are describing. 

Do you have other members or extensions on the `Customer` table with the name `TestField1`? 

I can only reproduce you error when having the following code:

- Base extension :
```
tableextension 50100 BaseTest_TEX18 extends "Customer"
{
    fields
    {
        field(60000; TestField1; Text[100]) {} 
    }
}
```
- Dependent extension:
```
tableextension 50107 BaseTest_TEX182 extends "Customer"
{
    procedure TestField1() 
    begin
    end;
}

codeunit 50100 TestDependency
{
    trigger OnRun()
    var
        tblCustomer: Record Customer;
    begin
        tblCustomer.Name := 'Standard field'; // OK - base and dependent extensions.
        tblCustomer.TestField1 := 'Extension field'; // AL0129 in dependent extension, OK in base extension
    end;
}
```

In that case, I get: `error AL0129: The left-hand side of an assignment must be a variable or field.` because the compiler tries then to assign `'Extension field'` to the procedure TestField1 and not to the field.

**Comment by chris-amco** [comment]
Hello qutreson. I don't have any other members with the same name. I have attached the source of both extensions (minus the .app files) in case it helps shed any light on it.

I wonder if it could be an issue with my setup? I am also getting errors that I don't understand when attempting to deploy to the server.  (e.g. I tried the workaround for 'Object reference not set...' suggested in #1018, but it didn't work for me.) I will give it a try with a D365BC sandbox instead of NAV2018 to see whether the result is different.

[Using Base fields in Dependent Ext.zip](https://github.com/Microsoft/AL/files/1990367/Using.Base.fields.in.Dependent.Ext.zip)

**Comment by chris-amco** [comment]
Update... I tried the advice in #1816, to use the AL extension that comes with NAV2018 (0.12.177720) rather than the latest one, and was able to compile and deploy the test extension without issue.

(After changing the AL extension, it initially showed the base extension field with a red underline, but when I keyed offending line again, the compilation problems disappeared).

**Comment by chris-amco** [comment]
Thank you qutreson. Perhaps I missed it, but I wasn't aware of this until I came across #1816. It would be good if MS documentation could mention this more often. For example a note could be added to the the AL language extension page on marketplace.visualstudio.com. Issue closed.
