### ISSUE TITLE
Expose/Add RegularExpressions.Regex.Replace

### ISSUE THREAD

**Issue by zhaohowie** [Microsoft/AL#2167]
Hello,

I saw there is method called IsMatch in the Codeunit 10. 

Can you also expose or add in Replace method in Codeunt 10?

The method will be,
Replace(string input, string pattern, string replacement) : Text  // Ignore case sensitive by default

Thanks,

**Comment by JesperSchulz** [comment]
We've already exposed two functions in COD10:
RegexReplace@55(Input@1000 : Text;Pattern@1001 : Text;Replacement@1002 : Text) : Text;
RegexReplaceIgnoreCase@52(Input@1000 : Text;Pattern@1001 : Text;Replacement@1002 : Text) : Text;
Those should meet your needs :) If not, please reopen issue.
