### ISSUE TITLE
Field Changes with "schemaUpdateMode":"Synchronize".

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#2168]
Hello,

We are facing the error when we delete filed from table and republish the extension to the sandbox with "schemaUpdateMode":"Synchronize".

FYI, We can able to publish the extension to the sandbox with "schemaUpdateMode":recreate. And loosing the history data 

How can we ignore this error and restore  the data to the remaining fields while re publishing the extension to the sandbox.

Thanks

**Comment by thpeder** [comment]
Hi @srinivasdes,
It is not possible. Take a look at [#1499](https://github.com/Microsoft/AL/issues/1499#issuecomment-360838258)
