### ISSUE TITLE
Why can't we use these functions in table "Currency Exchange Rate" (330)?

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#217]
In Extension 2.0 it is not allowed to call these functions:

```
ExchangeAmtLCYToFCY
ExchangeAmtFCYToLCY
ExchangeRate
ExchangeAmtFCYToLCYAdjmt
ExchangeRateAdjmt
ExchangeAmount
FindCurrency
ExchangeAmtFCYToFCY
ApplnExchangeAmtFCYToFCY
```
Error example: 'The type or method 'ExchangeRate' cannot be used for 'Extension' development.'

**Comment by StanislawStempin** [comment]
We will look into enabling these functions.

**Comment by StanislawStempin** [comment]
These functions will be enabled in the next update.

**Comment by bvbeek** [comment]
@StanislawStempin thank you! you are quite busy with it ;)
