### ISSUE TITLE
How can we make it possible to select a codeunit in a list?

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#218]
In the code example below we get this error: 'The type or method 'Object' cannot be used for 'Extension' development.'

```
local procedure SelectCodeunit();
  var
    "Object" : Record 2000000001;
    "Objects" : Page 358;
  begin
    Object.SETRANGE(Type,Object.Type::Codeunit);
    Objects.SETTABLEVIEW(Object);
    Objects.LOOKUPMODE(TRUE);
    IF Objects.RUNMODAL = ACTION::LookupOK THEN BEGIN
      Objects.GETRECORD(Object);
    END;
  end

```

AllObj and AllObjWithCaption is also not working.

**Comment by StanislawStempin** [comment]
AllObj and AllObjWithCaption will be enabled for Extensions development in May Update, will that be sufficient for your case? The Object table will remain locked.

**Comment by bvbeek** [comment]
@StanislawStempin, thank you for enable these two tables, maybe it's not needed to enable the Object table, but than I got a question:

How can we handle Object versions in AL code (the Version List column)?
Or should I create a new issue for this?
