### ISSUE TITLE
Field type 'TableFilter' issues

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#219]
This code results in an error and a warning:

**Error**: 'Syntax error, string literal expected'
I don't understand the error, the "Table No." is a field in the same table.

**Warning**; 'Property 'TableIDExpr' is obsolete and will be removed in a future version.'
Maybe it's needed to add a property TableNameExpr?

```
field(12;"Table No.";Integer)
{
  CaptionML=ENU='Table ID';
}
field(13;"Table Filter";TableFilter)
{
  CaptionML=ENU='Table Filter';
  TableIDExpr="Table No.";
}
```
![image](https://cloud.githubusercontent.com/assets/28626283/26052085/9bfef58e-3964-11e7-8846-51a036e704a7.png)

**Comment by dennisfrostlander** [comment]
Hi @bvbeek, 
We are now considering to drop support for the TableIDExpr property. 
Could you share more details about your use case? 
How does the TableIDExpr property help you solve the problem? 
Are there any other ways to solve the problem?

**Comment by bvbeek** [comment]
Hi Dennis,

I check this in our solution, and I can confirm that we can create a workarround for this.

You can close this for now!
