### ISSUE TITLE
events request - C12 -  PostDtldCustLedgEntries; PostDtldVendLedgEntries;UnapplyCustLedgEntry;UnapplyVendLedgEntry

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2190]
LOCAL   PostDtldCustLedgEntries
--
 
REPEAT
InsertDtldCustLedgEntry(GenJnlLine,DtldCVLedgEntryBuf,DtldCustLedgEntry,DtldCustLedgEntryNoOffset);
// request to add with   reference parameter UpdateAmount
**// begin
OnBeforeUpdateTotalAmount(UpdateAmount);
IF UpdateAmount then
// end**
UpdateTotalAmounts(
 
LOCAL PostDtldVendLedgEntries
REPEAT
InsertDtldVendLedgEntry(GenJnlLine,DtldCVLedgEntryBuf,DtldVendLedgEntry,DtldVendLedgEntryNoOffset);
// request to add with   reference parameter UpdateAmount
**// begin
OnBeforeUpdateTotalAmount(UpdateAmount);
IF UpdateAmount then
// end**
UpdateTotalAmounts(
 
[External]   UnapplyCustLedgEntry
….
// request to add with   reference parameter UpdateAmount
**// begin
OnBeforeUpdateTotalAmount(UpdateAmount);
IF UpdateAmount then
// end**
UpdateTotalAmounts(
TempInvPostBuf,GenJnlLine."Dimension   Set ID",DtldCVLedgEntryBuf."Amount (LCY)",
DtldCVLedgEntryBuf."Additional-Currency Amount");
 
[External]   UnapplyVendLedgEntry
….
// request to add with   reference parameter UpdateAmount
**// begin
OnBeforeUpdateTotalAmount(UpdateAmount);
IF UpdateAmount then
// end**
UpdateTotalAmounts(
TempInvPostBuf,GenJnlLine."Dimension   Set ID",DtldCVLedgEntryBuf."Amount (LCY)",
DtldCVLedgEntryBuf."Additional-Currency Amount");

===========================
LOCAL [IntegrationEvent] OnBeforeUpdateTotalAmount(VAR UpdateAmount : Boolean)
properties:
Property	Value
IncludeSender	Yes
GlobalVarAccess 	Yes

**Comment by AlexanderYakunin** [comment]
Please update each event description using parameters
