### ISSUE TITLE
event request C13 Function Code; Function UpdateAndDeleteLines

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2192]
LOCAL   Code(VAR GenJnlLine : Record "Gen. Journal Line")
--
WITH GenJnlLine DO BEGIN
SETRANGE("Journal Template   Name","Journal Template Name");
SETRANGE("Journal Batch   Name","Journal Batch Name");
………
// request to add with   reference parameter AutoIncr
**// begin
OnBeforeAutoIncre(AutoIncr);
if AutoIncr then
// end**
IF STRLEN(INCSTR(GenJnlBatch.Name)) >   MAXSTRLEN(GenJnlBatch.Name) THEN
 
 
LOCAL UpdateAndDeleteLines
…..
IF NOT GenJnlLine3.FINDLAST THEN
// request to add with   reference parameter AutoIncr
**// begin
OnbeforeAutoIncre(AutoIncr);
if AutoIncr then
// end**
IF INCSTR(GenJnlLine."Journal   Batch Name") <> '' THEN BEGIN

**Comment by AlexanderYakunin** [comment]
Please explain why you need such events here.
