### ISSUE TITLE
event request - C80 Function PostItemJnlLine

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2196]
LOCAL   PostItemJnlLine(SalesHeader : Record "Sales Header";SalesLine :   Record "Sales Line";QtyToBeShipped : Decimal;QtyToBeShippedBase :   Decimal;QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase :   Decimal;ItemLedgShptEntryNo : Integer;ItemChargeNo : Code[2
--
IF NOT ItemJnlRollRndg THEN   BEGIN
RemAmt := 0;
RemDiscAmt := 0;
END;
 
// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnBeforePostItemJnlLine;

**Comment by AlexanderYakunin** [comment]
Please update event description using parameters
