### ISSUE TITLE
event request C80 Function GetCountryCode(

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2197]
LOCAL   GetCountryCode(SalesLine : Record "Sales Line";SalesHeader : Record   "Sales Header") : Code[10]
--

EXIT(
GetCountryRegionCode(
SalesLine."Sell-to Customer   No.",
SalesHeader."Ship-to Code",
SalesHeader."Sell-to Country/Region   Code"));
**//request to add with  IncludeSender = Yes & GlobalVarAccess = Yes
OnAfterGetCountryCode;**

**Comment by AlexanderYakunin** [comment]
This event does not make sense after EXIT statement. It will never be reached. Please explain what you need to achieve here.

**Comment by Halilovast** [comment]
Yes, you're right.

our code is:
LOCAL PostItemJnlLine(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line";QtyToBeShipped : Decimal;QtyToBeShippedBase : Decimal;QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase : Decimal;ItemLedgShptEntryNo : Integer;ItemChargeNo : Code[2
.................

WITH ItemJnlLine DO BEGIN
  INIT;
  CopyFromSalesHeader(SalesHeader);
  CopyFromSalesLine(SalesLine);
  "Country/Region Code" := GetCountryCode(SalesLine,SalesHeader);
  // BG11.000
  "Country/Region Code" := SalesHeader."VAT Country/Region Code";
================================================================

maybe we need a new event here, like:
**LOCAL [IntegrationEvent] OnAfterGetCountryCode(VAR ItemJnlLine : Record "Item Journal Line";SalesHeader : Record "Sales Header")**

LOCAL PostItemJnlLine(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line";QtyToBeShipped : Decimal;QtyToBeShippedBase : Decimal;QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase : Decimal;ItemLedgShptEntryNo : Integer;ItemChargeNo : Code[2
..........
WITH ItemJnlLine DO BEGIN
  INIT;
  CopyFromSalesHeader(SalesHeader);
  CopyFromSalesLine(SalesLine);
  "Country/Region Code" := GetCountryCode(SalesLine,SalesHeader);
  **// BG11.000
  OnAfterGetCountryCode(ItemJnlLine,SalesHeader);**

**Comment by StanislawStempin** [comment]
Fixed in build 13.0.24110.0
