### ISSUE TITLE
event request C80 Function PostItemChargePerOrder

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2198]
LOCAL   PostItemChargePerOrder(SalesHeader : Record "Sales   Header";SalesLine : Record "Sales Line";ItemJnlLine2 : Record   "Item Journal Line";ItemChargeSalesLine : Record "Sales   Line")
--
WITH TempItemChargeAssgntSales   DO BEGIN
**// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnBeforePostItemChargePerOrder;**
SalesLine.TESTFIELD("Job   No.",'');

**Comment by AlexanderYakunin** [comment]
Please update event to include proper parameters. We should not use GlobalVarAccess here.

**Comment by Halilovast** [comment]
@thpeder  
Hello,
 is it Ok without specific parameters? I hope event is with IncludeSender = Yes & GlobalVarAccess = Yes.

**Comment by thpeder** [comment]
Hi @Halilovast,
As @AlexanderYakunin says the event will not be created with ```GlobalVarAccess = true``` since it is bad practice and could be a security problem.
The event was created without includeSender too and the invocation for it looks like so: ```OnBeforePostItemChargePerOrder(SalesHeader,SalesLine,ItemJnlLine2,ItemChargeSalesLine);```.

**Comment by VMashevBG** [comment]
Hi everyone, is it possible to add TempItemChargeAssgntSales in this event? 
I have additional fields in this table that I want to transfer to journal before post.
