### ISSUE TITLE
How can we call a function like: OpenFileDialog

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#220]
Call to Codeunit 419:
`FileManagement.OpenFileDialog`

Now I get the error: 'The type or method 'OpenFileDialog' cannot be used for 'Extension' development.'

**Comment by StanislawStempin** [comment]
What is the scenario that you need to support? Can you use File.UploadIntoStream instead?

**Comment by bvbeek** [comment]
Ok, I think we can handle this with your suggestion: UPLOADINTOSTREAM

You can close this for now.
