### ISSUE TITLE
event request C395 Function InitGenJnlLine

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2200]
LOCAL   InitGenJnlLine(AccType : Integer;AccNo : Code[20];SystemCreatedEntry :   Boolean)
--
….
GenJnlLine."Salespers./Purch.   Code" := '';
**// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnAfterInitGenJnlLine;**
END;

**Comment by AlexanderYakunin** [comment]
This event will be implemented:
OnAfterInitGenJnlLine(VAR GenJnlLine : Record "Gen. Journal Line";FinChargeMemoHeader : Record "Finance Charge Memo Header")

**Comment by Halilovast** [comment]
Thanks!
