### ISSUE TITLE
event request C5802 Function InitInvtPostBuf

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2202]
InitInvtPostBuf(ValueEntry   : Record "Value Entry";AccType : Option;BalAccType :   Option;CostToPost : Decimal;CostToPostACY : Decimal;InterimAccount : Boolean)
--
PostBufDimNo := PostBufDimNo +   1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,AccType,BalAccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],CostToPost,CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Dimension   Set ID" := ValueEntry."Dimension Set ID";
**// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnAfterInitTempInvtPostBuf;**
 
PostBufDimNo := PostBufDimNo +   1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,BalAccType,AccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],-CostToPost,-CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Dimension   Set ID" := ValueEntry."Dimension Set ID";
**// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnAfterInitTempInvtPostBuf;**

**Comment by AlexanderYakunin** [comment]
Please update event description using parameters

**Comment by raduku2018** [comment]
Hello,

Also for this function please add, the OnBeforeInitInvtPostBuf and  OnAfterInitInvtPostBuf subscribers.

LOCAL InitInvtPostBuf(ValueEntry : Record "Value Entry";AccType : Option;BalAccType : Option;CostToPost : Decimal;CostToPostACY : Decimal;InterimAccount : Boolean)

**OnBeforeInitInvtPostBuf(VAR ValueEntry : Record "Value Entry");**

PostBufDimNo := PostBufDimNo + 1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,AccType,BalAccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],CostToPost,CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Job No." := ValueEntry."Job No.";
TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";

PostBufDimNo := PostBufDimNo + 1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,BalAccType,AccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],-CostToPost,-CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Job No." := ValueEntry."Job No.";
TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";

**OnAfterInitInvtPostBuf(VAR ValueEntry : Record "Value Entry");**



Thank you!

**Comment by Halilovast** [comment]
Sorry for the late replay.

I change request for event with specific parameters: 

LOCAL [IntegrationEvent] OnAfterInitTempInvtPostBuf(VAR TempInvtPostBuf : Record "Invt. Posting Buffer";AccType : Option)

==========

InitInvtPostBuf(ValueEntry : Record "Value Entry";AccType : Option;BalAccType : Option;CostToPost : Decimal;CostToPostACY : Decimal;InterimAccount : Boolean)
PostBufDimNo := PostBufDimNo + 1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,AccType,BalAccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],CostToPost,CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";
**// begin
OnAfterInitTempInvtPostBuf(TempInvtPostBuf[PostBufDimNo],AccType);
// end**

PostBufDimNo := PostBufDimNo + 1;
SetAccNo(TempInvtPostBuf[PostBufDimNo],ValueEntry,BalAccType,AccType);
SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo],-CostToPost,-CostToPostACY,InterimAccount);
TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";
**// Begin
OnAfterInitTempInvtPostBuf(TempInvtPostBuf[PostBufDimNo],AccType);
// end**

**Comment by AncaSterian** [comment]
Dear   @thpeder , 

Can you please tell us in which cumulative this update  will be included? 
We are currently working to a localization package and we need this functionality for a mandatory development. 
It's possible to have it on the CU7 which will be launched in July ? 

Thank you very much in advance. 

Kindest regards, 
Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

New events will be implemented to Dynamics 365 Business Central only. No new events will be implemented to NAV 2018 CU’s based on GitHub requests, please contact customer support to create a hotfix request for critical events.
