### ISSUE TITLE
event request C5802  Function PostInvtPostBuf

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2203]
LOCAL   PostInvtPostBuf(VAR ValueEntry : Record "Value Entry";DocNo :   Code[20];ExternalDocNo : Code[35];Desc : Text[50];PostPerPostGrp : Boolean)
--
WITH GlobalInvtPostBuf DO   BEGIN
RESET;
**// request to add with IncludeSender = Yes & GlobalVarAccess = Yes
OnBeforePostInvtPostBuf;**
 
IF NOT FINDSET THEN
EXIT;

**Comment by AlexanderYakunin** [comment]
We already have event OnBeforePostInvtPostBuf(GenJnlLine,GlobalInvtPostBuf,ValueEntry) just before call to GenJnlPostLine.RunWithCheck(GenJnlLine).

**Comment by Halilovast** [comment]
I have made a mistake with the name of event. We need event after RESET and before repeat for change the key of table GlobalInvtPostBuf.

LOCAL [IntegrationEvent] OnBeforeFillGenJnlLinePostInvtPostBuffer(VAR GlobalInvtPostBuf : Record "Invt. Posting Buffer")

==================================

LOCAL PostInvtPostBuf(VAR ValueEntry : Record "Value Entry";DocNo : Code[20];ExternalDocNo : Code[35];Desc : Text[50];PostPerPostGrp : Boolean)
WITH GlobalInvtPostBuf DO BEGIN
  RESET;
  **// begin
  OnBeforeFillGenJnlLinePostInvtPostBuffer(GlobalInvtPostBuf);
  // end** 
  IF NOT FINDSET THEN
    EXIT;

  GenJnlLine.INIT;
  GenJnlLine."Document No." := DocNo;
  GenJnlLine."External Document No." := ExternalDocNo;
  GenJnlLine.Description := Desc;
  GetSourceCodeSetup;
  GenJnlLine."Source Code" := SourceCodeSetup."Inventory Post Cost";
  GenJnlLine."System-Created Entry" := TRUE;
  GenJnlLine."Job No." := ValueEntry."Job No.";
  GenJnlLine."Reason Code" := ValueEntry."Reason Code";
  REPEAT

**Comment by StanislawStempin** [comment]
Fixed in build 24004
