### ISSUE TITLE
change code C6224  Function IsValidXMLNameStartCharacter

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2204]
IsValidXMLNameStartCharacter(InputChar   : Char) : Boolean
--
IF   IsXMLRestrictedCharacter(InputChar) THEN
EXIT(FALSE);
 
// NameStartChar ::=   ":" \| [A-Z] \| "_" \| [a-z] \| [#xC0-#xD6] \| [#xD8-#xF6] \|   [#xF8-#x2FF] \| [#x370-#x37D] \| [#x37F-#x1FFF] \| [#x200C-#x200D] \|   [#x2070-#x218F] \| [#x2C00-#x2FEF] \| [#x3001-#xD7FF] \| [#xF900-#xFDCF] \|   [#xFDF0-#xFFFD] \| [#x10000-#xEFFF
**// begin
//IF InputChar IN   [':','_','A'..'Z','a'..'z'] THEN
IF InputChar IN   [':','_','A'..'Z','a'..'z','А'..'Я','а'..'я'] THEN
// end**
EXIT(TRUE);

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! I wonder if there is a .NET equivalent we can use for this function, instead of implementing our own flavor. I will investigate.

**Comment by JesperSchulz** [comment]
Turns out we could not find a suitable .NET equivalent and hence decided to go with your solution. For now, we've only made the changes to the Russian version. Does that suffice, or do you need the change in W1 or other country versions as well?

**Comment by JesperSchulz** [comment]
You got it!
