### ISSUE TITLE
C6620 - Change code -  Function CopyPurchLine

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#2207]
could you change:

old:
ToPurchLine.VALIDATE("Job No.",FromPurchLine."Job No.");
ToPurchLine.VALIDATE("Job Task No.",FromPurchLine."Job Task No.");
ToPurchLine.VALIDATE("Job Line Type",FromPurchLine."Job Line Type");

new:
**IF FromPurchLine."Job No." <> '' THEN BEGIN**
      ToPurchLine.VALIDATE("Job No.",FromPurchLine."Job No.");
      ToPurchLine.VALIDATE("Job Task No.",FromPurchLine."Job Task No.");
      ToPurchLine.VALIDATE("Job Line Type",FromPurchLine."Job Line Type");
**END;**

**Comment by JesperSchulz** [comment]
That does sound reasonable, yes. Consider it done.
