### ISSUE TITLE
Duplicate object: compile issues

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#221]
If there is a duplicate object, the compiler should stop compile the rest of the duplicated object.

Now you get invalid compile errors.
The first error is ok, but the second one not.

![image](https://cloud.githubusercontent.com/assets/28626283/26054421/ce0c9ec0-396c-11e7-9c7a-294f9d2227d2.png)

**Comment by StanislawStempin** [comment]
This is a bug, we will investigate it.
