### ISSUE TITLE
event request PAG11309 Function SetIncludeEntryFilter

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2210]
PROCEDURE SetIncludeEntryFilter@1010010();
    BEGIN
      SETCURRENTKEY("G/L Account No.","Posting Date","Entry No.",Open);
      case IncludeEntryFilter of
        IncludeEntryFilter::All:
          SETRANGE(Open);
        IncludeEntryFilter::Open:
          SETRANGE(Open,true);
        IncludeEntryFilter::Closed:
          SETRANGE(Open,false);
      end;

      OnAfterSetIncludeEntryFilter; //needed event
    END;

We need this event because we have added code in the standard function after the standard code for setting extra filters:
IF EntriesIncluded = EntriesIncluded::Open THEN
  IF IncludeEntryFilter <> IncludeEntryFilter::Open THEN
    SetExtraFilter;

Thanks !

**Comment by WaelAbuSeada** [comment]
Hi, sorry for the late answer. I assume this is the function in page 11309? if so, there is 2 reference of this function that you could add code using triggers found in page extension.

For example, 1st reference: at the end of open Page, and you could just use onOpenPage trigger to add your code there.

the 2nd is on validating field IncludeEntryFilter where you could also use onbefore validating trigger and add your code there.

Could you check if you could use that without the need to introduce an event?
