### ISSUE TITLE
Unexpected value TestAction of type Microsoft.Dynamics.Nav.CodeAnalysis.SymbolKind

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/AL#2212]
When referring to a page action on a testpage within a with do begin block the following error is generated:
[Error - 09:19:38] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Unexpected value 'TestAction' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.SymbolKind''

Using AL Language extension version 0.15.18771
Docker Image microsoft/bcsandbox:12.0.21229.0-nl

Removing the with do begin block can be used as a workaround.
I've attached the AL project containing the reproduction scenario.
[UnexpectedValueTestAction.zip](https://github.com/Microsoft/AL/files/1994346/UnexpectedValueTestAction.zip)

**Comment by qutreson** [comment]
Hi @richardrobberse, thank you for reporting this issue. I can reproduce it when using the extension from the marketplace (0.15.18771), but I cannot reproduce it in our current code base. The fix should then be available with the next update.

**Comment by richardrobberse** [comment]
@qutreson Thanks for letting me know :)

**Comment by srinivasbanny** [comment]
When can we expect the new version to download or any process to download the new version .Please suggest because even i am getting the same issue
