### ISSUE TITLE
New event request for FA Reclass. Transfer codeunits

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2213]
Can you add following publishers:

1. Added new publisher **OnBeforeInsertGenJnlLine** called from **InsertGenJnlLine** in **codeunit 5642** **FA Reclass. Transfer Line**.

**Publisher**:

``
LOCAL [IntegrationEvent] OnBeforeInsertGenJnlLine(VAR FAReclassJnlLine : Record "FA Reclass. Journal Line";VAR GenJnlLine : Record "Gen. Journal Line")
``

**Call in InsertGenJnlLine**:

![image](https://user-images.githubusercontent.com/20359384/39914646-edd2af14-5505-11e8-9d43-20e6064024ab.png)

2. Added new publisher **OnBeforeFAReclassJnlLineInsert** called from **Code** in **codeunit 5643 FA Reclass. Transfer Batch.**

**Publisher**:

``
LOCAL [IntegrationEvent] OnBeforeFAReclassJnlLineInsert(VAR FAReclassJnlLine : Record "FA Reclass. Journal Line";VAR LastFAReclassJnlLine : Record "FA Reclass. Journal Line";VAR NewFAReclassJnlLine : Record "FA Reclass. Journal Line")
``

**Call in Code**:

![image](https://user-images.githubusercontent.com/20359384/39914758-446e6a84-5506-11e8-8b47-26bcfd116451.png)

3. Added new publisher **OnBeforeCode** called from **Code** in **codeunit 5644 FA Reclass. Jnl.-Transfer**

**Publisher**:

``
LOCAL [IntegrationEvent] OnBeforeCode(VAR FAReclassJnlLine : Record "FA Reclass. Journal Line")
``

**Call in Code**:

![image](https://user-images.githubusercontent.com/20359384/39914849-8a39557e-5506-11e8-9245-e9d7b5798965.png)

**Comment by PooyaKharamesh** [comment]
Hi, 

Please consider the following suggestions/questions. 

1. Couldnt you use the OnInsert event on GenJnlLine in the first issue?
2. If we change the code to trigger the OnInsert event, Could you use the OnInsert event on the FAReclassonJnlLine for resolving the second issue?
3. On the 3rd one, function Code is called from OnRun and there is no logic before calling it. I suggest to apply your logic before running the code unit. does it help to solve the issue?

Thank you 
Pooya
