### ISSUE TITLE
New event request for OnAfterSetFAPostingDate called from SetFAPostingDate in Codeunit 5606 FA Check Consistency

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2214]
Can you add new publisher **OnAfterSetFAPostingDate** called from **SetFAPostingDate** in **Codeunit 5606 FA Check Consistency**?

**Publisher**:

``
[IntegrationEvent] OnAfterSetFAPostingDate(VAR FALedgEntry : Record "FA Ledger Entry";VAR FADeprBook : Record "FA Depreciation Book";MaxDate : Date;MinDate : Date;GLDate : Date)
``

**Called from SetFAPostingDate**:

![image](https://user-images.githubusercontent.com/20359384/39915118-6280fb80-5507-11e8-9a64-9445394c9190.png)

**Comment by MarcHansenMicrosoft** [comment]
You should be able to use the OnBeforeModifyEvent on the FADeprBook table.
