### ISSUE TITLE
Page 6510 in Function SetSourceSpecOnBeforeSetSourceSpec(TrackingSpecification,ReservEntry);

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/AL#2218]
Hi,

Please add publisher in Page 6510 in Function SetSourceSpec to add filters for Tracking and reservationentry.

OnBeforeSetSourceSpec(TrackingSpecification,ReservEntry);

with VAR.

![2018-05-11 18_04_20-172 17 0 1 - remote desktop connection](https://user-images.githubusercontent.com/29703512/39924655-4ee577ec-5546-11e8-9f8b-53e53f1c1f3e.png)

thanks!

regards,
srinivas

**Comment by AlexanderYakunin** [comment]
ReservEntry is empty at this point and filters will be reset later. So what this event is supposed to do?

**Comment by srinivasGangadhara** [comment]
ReservEntry is empty Custom filters will be applied, But the ReservEntry not RESET later.


![gs19](https://user-images.githubusercontent.com/29703512/40096855-890bebc4-58f0-11e8-8e5d-a3707e0b93bc.png)

we need to filter reservEntry, if we have event in AddReservEntriesToTempRecSet is also good for us.

Like below

![gs19-01](https://user-images.githubusercontent.com/29703512/40096984-3a045182-58f1-11e8-8f84-2bebc687dc2f.png)

**Comment by StanislawStempin** [comment]
This should have been implemented as part of #2260
