### ISSUE TITLE
Txt2Al- Function-call in a Page field

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#222]
Maybe it's an idea to use different names in the **Name** and **Source** of the field when it calls a function. Or use the caption?

![image](https://cloud.githubusercontent.com/assets/28626283/26060328/f5b7b74e-3984-11e7-8f71-656eb9428fb7.png)

**Comment by StanislawStempin** [comment]
You can already have a different Name and Source for a page field. Or do you mean that it should be allowed to have a page field named the same as other code members?

**Comment by bvbeek** [comment]
Thanks for your feedback.

Not really, what I mean is that I get this C/AL input:
![image](https://cloud.githubusercontent.com/assets/28626283/26063060/15d15a64-398d-11e7-985e-79161a381e90.png)

and I get this AL output:
![image](https://cloud.githubusercontent.com/assets/28626283/26063367/221ff1bc-398e-11e7-8680-e1592474e46e.png)

Now I got a compile issue, I will suggest to name the field according the ENU caption of the field.
So you will get this:
![image](https://cloud.githubusercontent.com/assets/28626283/26063262/c96798c2-398d-11e7-8ab6-f1f4b8a6efde.png)

**Comment by StanislawStempin** [comment]
Ok, got it. The current logic uses the following order:
1. Name
2. Source expression
3. ENU caption.

If I understand correctly you're suggesting flipping 2 and 3. That could indeed reduce the number of resulting conflicts.

**Comment by bvbeek** [comment]
Top, yes I think so, it's just a suggestion.;)
