### ISSUE TITLE
Daily Build with DotNET Variables

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#2228]
I've noticed that the daily build from docker for the FALL release does not give an error (anymore?) on DotNet variables.

Does this also mean it works now? Is this on the roadmap for VNext?

![image](https://user-images.githubusercontent.com/7205122/39971102-00872b70-56f6-11e8-9227-d037bce8096a.png)

**Comment by StanislawStempin** [comment]
It does not work yet but the work is progressing. It is on the roadmap for the Fall release.

**Comment by markbrummel** [comment]
That is wonderful news. Looking forward to yet another best release of Navision ever! Thanks.

**Comment by NoOneLt** [comment]
Hey guys, what is image name for fall release? Is it devpreview-finus ? Thanks

**Comment by StanislawStempin** [comment]
That's correct. However please keep in mind that it's not a public program and moreover the bits are shared under an NDA. I have a feeling it's sometimes forgotten.

Regarding DotNet support for Fall - it will be On-Prem only.
In the cloud the replacement for in-process DotNet interop is Azure Functions. With the ability to host Azure Functions locally we recommend it as the long-term approach both for On-Prem and cloud. We are enabling DotNet only to accelerate the conversion of existing V1 code to V2 code but long-term the move away from DotNet into the new native AL types and Azure Functions will still need to happen.
