### ISSUE TITLE
Labels a reserved word?

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#2229]
I am getting errors on variables called Labels.

Is this a new reserved word that we did not have in C/AL?

This error is removed when I rename the boolean to Label.

![image](https://user-images.githubusercontent.com/7205122/39971121-764cff06-56f6-11e8-8463-3e54f2c9deda.png)

**Comment by DominikDitoIvosevic** [comment]
Yes, we have "labels" as a keyword so we have to allow it as identifier as well. Expect a fix soon on dev preview.

**Comment by markbrummel** [comment]
Thanks. I appreciate the feedback.

**Comment by markbrummel** [comment]
I have it here too. We are a shipping company and "Labels" is something we us a lot as caption/field/function etc.

![image](https://user-images.githubusercontent.com/7205122/40140183-80af7ed4-5952-11e8-91a5-956a3409113b.png)
