### ISSUE TITLE
Package Deployment fails for AppSource App

### ISSUE THREAD

**Issue by sbuescher** [Microsoft/AL#2230]
I've tried to deploy an App from AppSource. It fails with "PackageDeployFailed". Is there a general Support for that? Who can help?

**Comment by HunterFeltman-MSFT** [comment]
Hello @sbuescher,

Could you specify which extension you are trying to deploy? 
And what country/region your Business Central tenant is located in? (US, CA, UK, etc...)

Not all extensions are supported in all regions, but unfortunately AppSource does not allow for any type of filtering so we end up showing 'everything'. 

Additionally, in the coming update we have continued work in the UI around the new extension deployment process so the actionable errors are visible in the details view for the deployment (so you'll be able to see 'why' it fails in the future).

**Comment by HunterFeltman-MSFT** [comment]
Closing this as issue is being tracked elsewhere with your conversations with the AppSource Validation team. (aka Ryan)
