### ISSUE TITLE
[BC Deployement] Problem deploying in specific range

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#2232]
Hi,

I've a problem when I deploy my extension into Business Central in my specific range (8052510 - 8052519).
I've this message when I publish: 
`The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Your license does not allow you to publish "extension"`

I'm able to publish it, with my specific range, in a docker container **ONLY** if I use the the -licensefile parameter.
I also can publish if I use the 50100 - 50149 range.

If this is really a license problem, could someone explain me how Microsoft checks the license without .flf ?

Thanks !

**Comment by thpeder** [comment]
Hi @JulienDecottignies,

You should be able to use that range in the sandbox.
If you could please provide your tenant id and region then we will investigate the issue.

**Comment by StanislawStempin** [comment]
This problem should have been solved by now. Please try again and if you still run into the same problem please log a new issue.
