### ISSUE TITLE
PageNotifier: DotNet variable and length issue

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#225]
#124 "There is currently no support for .net interop in extensions v2. We plan to make that available for on-prem development in the future, but not for SaaS."

But... is it possible to support the DotNet variables that's supported by Microsoft?

Please, take a look at OBJECT Page 1310 O365 Activities:
![image](https://cloud.githubusercontent.com/assets/28626283/26103227/c53a7692-3a38-11e7-890d-4a3fa4e5ea9b.png)

Here you are using a default Dynamics NAV Client DotNet variable, please can you make this available for extensions?

See also that the name is to long for AL code:
![image](https://cloud.githubusercontent.com/assets/28626283/26103361/4e2f1b7e-3a39-11e7-8b76-d48a302f85d6.png)

**Comment by esbenk** [comment]
The compiler support for DotNet doesn't exist yet. The identifier length error will of course be solved when we support the DotNet type (for OnPrem).

Client-side extensibility (like the listed types) is also something that we haven't finalized yet.

**Comment by bvbeek** [comment]
> Client-side extensibility (like the listed types) is also something that we haven't finalized yet.

Ok, can we expect that these DotNet variables will be supported for Saas in the near feature?

**Comment by esbenk** [comment]
We don't have a timeline for it yet.
