### ISSUE TITLE
Issue when using a tableextension-field in a Report Data-Item

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#226]
Similar to #223

But I don't know if this is same issue:

1. Create a tableextension
2. Use the field on the OnAfterGetRecord
3. Also tried names, but without success

![image](https://cloud.githubusercontent.com/assets/28626283/26105223/6cdd59a2-3a41-11e7-9a14-fb00950daf15.png)

**The extension**
```
tableextension 70095673 "Customer(Table 18)" extends Customer 
{
  // version NAVW110.0

  fields
  {
    field(70012200;"Invoice Period Code";Code[10])
    {
      CaptionML=ENU='Invoice Period Code';
      TableRelation="WMS Invoice Period";
    }
  }
  keys
  {
  }
}
```

**The report**
```
report 70012277 "WMS Create Sales Invoice"
{
  dataset
  {
      // dataitem(Customer;70095673)
      // dataitem(Customer;18)
      dataitem(Customer;Customer)
      {
        trigger OnAfterGetRecord();
        var
          InvoicePeriod : Record 70012256;
        begin         
          InvoicePeriod.GET("Invoice Period Code");
        end;
    }
  }
}

```

**Comment by bvbeek** [comment]
Sure, we can. But I think it's a bug. The compiler should know that it's on the Customer-Data-Item.

And, this is not consistent like other objects.

**Comment by esbenk** [comment]
You are right. I can see that the base fields are in scope. This is a bug.
