### ISSUE TITLE
Expose SetDrillDownIndexes function, table "Business Chart Buffer"

### ISSUE THREAD

**Issue by djole1391** [Microsoft/AL#2264]
Hello,

Can we have function SetDrillDownIndexes exposed, table "Business Chart Buffer"?

And how is this function going to work in extensions, since it receives Point: DotNet as parameter in C/Side, and event DataPointClicked also, but in extensions trigger DataPointClicked has point: JsonObject? 
C/Side:
![image](https://user-images.githubusercontent.com/12559226/40113134-a8330c2c-5908-11e8-8d1e-da0e0136883f.png)
VS Code:
![image](https://user-images.githubusercontent.com/12559226/40113162-c6f24c0e-5908-11e8-99dc-fedc492860ca.png)

I was looking at this article for example of DataPointClicked trigger: 
https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/

Thanks

**Comment by djole1391** [comment]
and also function SetValue.

Thanks

**Comment by dennisfrostlander** [comment]
Hi @djole1391,

For `SetDrillDownIndexes`, we added an overload procedure `SetDrillDownIndexesByCoordinate` on Business Chart Buffer. This procedure accepts native arguments (Text, Integer, etc) which you can extract from the JsonObject point.

The `SetValue` procedure has been already made external in the latest sources. If you need it to be backported, you can reach out to customer support.
