### ISSUE TITLE
txt2al should properly convert ValuesAllowed property for text/code fields

### ISSUE THREAD

**Issue by dennisfrostlander** [microsoft/AL#2266]
See #2123 for the initial discussion.

If the field type is code or text, the ValuesAllowed property is not correctly converted by txt2al.
In C/SIDE, the values are stored as [ABC;DEF] and this is converted as `ValuesAllowed = ABC, DEF`. However, the new AL syntax requires code/text constants to be single-quoted - `ValuesAllowed = 'ABC', 'DEF'`

**Comment by qutreson** [comment]
This issue has been fixed and the fix is available in version/14.x. Associated build number is 35439.
