### ISSUE TITLE
[PageExtension] Page level Properties modification

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2269]
Hello,

We are currently converting modifications in standard pages to page extensions and we have issues because in many cases we modified Properties at page level.

Some examples:
//Unsupported feature: Property Modification (PromotedActionCategoriesML). Please convert manually.
//Unsupported feature: Property Insertion (DeleteAllowed). Please convert manually. 
//Unsupported feature: Property Insertion (Editable). Please convert manually. 
//Unsupported feature: Property Insertion (SourceTableView). Please convert manually. 
Delayed Insert: Old Value: No; New Value: Yes

etc.

Which would be the best way to deal with this ? (besides creating custom page- in most of cases we only modified 1 property per page and it does not make too much sense to create a new page only for 1 property). 

It would be great if we could modify these properties from the extension.

Thanks,

**Comment by thpeder** [comment]
Hi @andreilungu,

PromotedActionCategoriesML should be available in page extensions, but we might have a but in the converter.

If you can't provide the same functionality from code then yes you should create a new page.

**Comment by andreilungu** [comment]
Hi @thpeder ,

Will all below properties be available in the June 2018 release ?
- DeleteAllowed
- InsertAllowed
- ModifyAllowed
- SourceTableView
- DelayedInsert
- Editable
etc.

Thanks

**Comment by thpeder** [comment]
No, there will be no changes to the compiler, but the converter now also handles properties on TableExtensions and PageExtensions objects. Before it would only convert Field, Control, etc. properties

**Comment by andreilungu** [comment]
It is not clear for me. So, will we be able to use page properties from a page extension ?
Ex: 
- Original page has DelayedInsert = No and we want to change it to DelayedInsert = Yes,
- Original page has SourceTableView empty and we want to change it and add a filter,
etc

**Comment by thpeder** [comment]
It is only a limited set of properties from a page that can be changed from a PageExtension, and none of the ones you listed can be changed.
Have a look at the docs: [Page and Page Extension Properties Overview](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)

**Comment by andreilungu** [comment]
So our only chance if we need to change these properties is to create a new page ? Or is there any other workaround.

Because we have pages where for example we changed only 1 property and besides this the page is standard.. And it does not seem to good to create an entirely new page only because we cannot change that property...

**Comment by thpeder** [comment]
We are aware of the limitation and if you can't mimic the same behavior from code then you do need to create a new page.

**Comment by andreilungu** [comment]
Yes, some of them can be done from code but not all. (ex: delayed insert).

Thanks, it is clear now
