### ISSUE TITLE
Suggestion: Use BLOB Field as String

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#227]
There is a **limit** on 250 Characters on _Text_ Fields on the Platform. In Order to handle longer Texts like URLs and longer Texts, my suggestion is to extent the handling of **BLOB** like a normal _Text_ Fields. Currently you have to STEAM the **BLOB** Value back and forth to a _Text_-Variable.

E.g. the Table **TempBLOB** has nowadays functions to handle this conversion.

```
WriteAsText(Content : Text;Encoding : TextEncoding)
CLEAR(Blob);
IF Content = '' THEN
  EXIT;
Blob.CREATEOUTSTREAM(OutStr,Encoding);
OutStr.WRITETEXT(Content);
```
```
ReadAsText(LineSeparator : Text;Encoding : TextEncoding) Content : Text
Blob.CREATEINSTREAM(InStream,Encoding);

InStream.READTEXT(Content);
WHILE NOT InStream.EOS DO BEGIN
  InStream.READTEXT(ContentLine);
  Content += LineSeparator + ContentLine;
END;
```

I think direct access would be much more developer friendly. In addition, it would be a blast to set a BLOB Field as a Page Field without handling it with _Code Behind_ (Multiline=Yes and No).

E.g. Code Behind Handling of the Work Description in Page 41 **Sales Quote**:
```
OnAfterGetRecord()
[..]
WorkDescription := GetWorkDescription;
```
```
WorkDescription - OnValidate()
SetWorkDescription(WorkDescription);
```
This would be also a good decision for the In-App Designer, so customer and consultants could add these fields without any additional help of a developer.

**Comment by StanislawStempin** [comment]
Interesting suggestion, we will consider it as part of our longer term backlog.

**Comment by Gallimathias** [comment]
@StanislawStempin @DanielGoehler:

I believe BLOB to use for these purposes is not the right way. The 250 character limit is silly, I believe we are all agreed.

For me, a blob is a compressed byte array and not a text variable.

My alternative would be to use a nvarchar(max) in the background if the length property of the text variable is not set.

A) could be parsed in the background text instead of in NavText in string
B) string has a limit of 2Gb and nvarchar(max) has a limit of 2GB
C) The adjustment effort is worthwhile

**Comment by ThomasBrodkorb** [comment]
@Gallimathias :
In the assumption that no conversion between ByteArray and Base64 is done, you might be right.
Returning an image with a BAse64 encoding currently requires at least twenty lines of code to copy it over to the tempblob table and extract from there as Base64.
I would rather consider making the functions in the TempBlob table methods of the Blob type.

**Comment by rsgilbert** [comment]
The problem is how to get the new line character when converting from tempblob to text
