### ISSUE TITLE
XmlElement.GetAttribute

### ISSUE THREAD

**Issue by JoelJame5** [Microsoft/AL#2272]
Can GetAttribute procedure be added to the XmlElement datatype? How can I get an attribute by name from an xml element? Iterate through the attribute collection?

**Comment by thpeder** [comment]
Hi @Joel-NAVDev,
The attributeCollection has a overload for getting the attribute by name, either with or without a namespace.
![image](https://user-images.githubusercontent.com/24276180/40167137-85984c3c-59c0-11e8-99bc-0682680f025b.png)

**Comment by Joel-NAVDev** [comment]
Thanks @thpeder, GetAttributeValue function would be helpful. I will use this to create my own function for now.
