### ISSUE TITLE
Can we have a new Option object type?

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#2275]
I'm not sure if this is the right place to log this, but I would like to propose a change to the AL language (I know you've probably got your hands full, but at least you can consider the suggestion).

I am proposing we create a new top level object type similar to Codeunit, Table, Page, etc. called Option.

I think the current syntax for defining options in AL is a little weird. Here's an example of adding a new option type field to a table:

```
field(3; "Account Type"; Option)
{
            OptionMembers = "'G/L Account","Customer","Vendor","Bank Account","Fixed Asset","IC Partner","Employee"; 
}

```
I am proposing we create a new top level object type similar to Codeunit, Table, Page, etc. called Option.

This will be defined in a similar way to a table object but with Members instead of Fields.

Then when I want to use an option as a variable I use syntax similar to the following:

```
MyOption: Option "Account Type";
```
We could add a new OptionType property on a table field for compatibility with C/SIDE, but the new AL syntax would be nice if it was consistent with declaring a variable like this:
```
field(3; "Account Type"; Option: "Account Type") { }
```
There are a few areas where this starts to get really powerful. For example, we could then have Option Extension type objects where we can add our own options to standard objects. We can pass variables of type option without needing a copy of the members duplicated in fragments of code (which is a source of bugs). We could even have a trigger that allows us to write our own assignment logic which will map one option type to another.

If we think about the extension model and all the places in standard code where an option is handled through a case statement, how could we make this extensible? Maybe change the standard code to have an else that will raise an event and if is not handled, can throw an error. For example we used to have a modification that allowed Resources to be purchased. This meant changing the standard field definition in lots of tables and changing the standard posting code to not throw an error for a resource but to handle it instead. Currently we cannot do this as an extension, but with the new Option object it might be possible.

Need more convincing this is a good idea? Think about the Report Selections handling in NAV. The option field for standard reports is a total nightmare to manage and maintain. Imagine how easy this would be if you had an Option object and new report types could be added as extensions for both localizations and as partner extensions.

**Comment by Gallimathias** [comment]
We're already having this discussion in #590 . So I think that belongs together.

**Comment by StanislawStempin** [comment]
This has been implemented as a new Enum and EnumExtension types. More details can be found here:
https://blogs.msdn.microsoft.com/nav/2018/07/30/developer-preview-july-2018-update/
