### ISSUE TITLE
Complex return types

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#228]
It would be nice if in AL complex data types could be defined as a return type. e.g. Records, Codeunits etc.

**Comment by esbenk** [comment]
The runtime (Dynamics Nav Server) doesn't support that at this point in time, but it is an area we would like to improve in the future.

**Comment by Gallimathias** [comment]
So it was thought :D.

**Comment by erikrijn** [comment]
I would really like this. It's still strange to me that I cant return a record.

**Comment by pri-kise** [comment]
I guess this issue can be closed with BC 18
https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave1/smb/dynamics365-business-central/returning-complex-types

**Comment by Gallimathias** [comment]
Cool that another idea of mine made it into the implementation after four years. :D
