### ISSUE TITLE
Event Request Codeunit 12

### ISSUE THREAD

**Issue by raduku2018** [Microsoft/AL#2280]
Hello,

Please add the subscribers OnBeforeInsertVAT and OnAfterInsertVAT, in function:

_LOCAL InsertVAT(GenJnlLine : Record "Gen. Journal Line";VATPostingSetup : Record "VAT Posting Setup";GLEntryAmount : Decimal;GLEntryVATAmount : Decimal;GLEntryBaseAmount : Decimal;SrcCurrCode : Code[10];SrcCurrGLEntryAmt : Decimal;SrcCurrGLEntryVATAmt : Decimal)_

**OnBeforeInsertVAT(VAR  GenJnlLine : Record "Gen. Journal Line"; VAR VATEntry : Record "VAT Entry"; VAR UnrealizedVAT : Boolean; VAR AddCurrencyCode : Code[10]);**

WITH GenJnlLine DO BEGIN
  // Post VAT
  // VAT for VAT entry
  VATEntry.INIT;
......

**OnAfterInsertVAT(VAR  GenJnlLine : Record "Gen. Journal Line"; VAR VATEntry : Record "VAT Entry"; VAR UnrealizedVAT : Boolean; VAR AddCurrencyCode : Code[10]);**

Thank you!

**Comment by Deepakalle123** [comment]
Can you please ship this into NAV2018
