### ISSUE TITLE
External functions CU 12: InitGLEntryVAT, InitGLEntryVATCopy and PostUnrealVATEntry

### ISSUE THREAD

**Issue by raduku2018** [Microsoft/AL#2281]
Hello,

The local functions **InitGLEntryVAT**, **InitGLEntryVATCopy** and **PostUnrealVATEntry** from Codeunit 12, please make them external.

Thank you!

**Comment by PooyaKharamesh** [comment]
Hi,

These functions are sort of local initialization functions and are tailored to the context of the CU. Would you provide an explanation of why you need these functions to be global? 

/Pooya

**Comment by Pooya-Kharamesh** [comment]
I closed the thread since as no response for last week.

/Pooya

**Comment by PooyaKharamesh** [comment]
I will close the thread due to no communication for a week.

Pooya

**Comment by raduku2018** [comment]
Hello,

Starting with the 1st of January 2013, the legal requirements demand implementing and using postponed VAT. To comply with these demands, a certain working procedure must be followed. It implies using standard and modified functionalities.
If those functions cannot be global, could be implemented subscribers?

1.) InitGLEntryVAT
_LOCAL InitGLEntryVAT(GenJnlLine : Record "Gen. Journal Line";AccNo : Code[20];BalAccNo : Code[20];Amount : Decimal;AmountAddCurr : Decimal;UseAmtAddCurr : Boolean)_
**OnBeforeInitGLEntryVAT(GenJnlLine : Record "Gen. Journal Line";VAR GLEntry : Record "G/L Entry"; SystemCreatedEntry : Boolean);**
xxxxxx
**OnAfterInitGLEntryVAT(GenJnlLine : Record "Gen. Journal Line";VAR GLEntry : Record "G/L Entry"; SystemCreatedEntry : Boolean);**
SummarizeVAT(GLSetup."Summarize G/L Entries",GLEntry);

2.) InitGLEntryVATCopy
_LOCAL InitGLEntryVATCopy(GenJnlLine : Record "Gen. Journal Line";AccNo : Code[20];BalAccNo : Code[20];Amount : Decimal;AmountAddCurr : Decimal;VATEntry : Record "VAT Entry") : Integer_
**OnBeforeInitGLEntryVATCopy(GenJnlLine : Record "Gen. Journal Line";VAR GLEntry : Record "G/L Entry"; SystemCreatedEntry : Boolean);**
xxxxxxxxxx
**OnAfterInitGLEntryVATCopy(GenJnlLine : Record "Gen. Journal Line";VAR GLEntry : Record "G/L Entry"; SystemCreatedEntry : Boolean);**
SummarizeVAT(GLSetup."Summarize G/L Entries",GLEntry);

3.) PostUnrealVATEntry
_LOCAL PostUnrealVATEntry(GenJnlLine : Record "Gen. Journal Line";VAR VATEntry2 : Record "VAT Entry";VATAmount : Decimal;VATBase : Decimal;VATAmountAddCurr : Decimal;VATBaseAddCurr : Decimal;GLEntryNo : Integer)_
VATEntry.LOCKTABLE;
VATEntry := VATEntry2;
**OnBeforePostUnrealVATEntry(GenJnlLine : Record "Gen. Journal Line";VAR VATEntry : Record "VAT Entry");**
xxxxxxxxxxxxx
**OnAfterPostUnrealVATEntry(GenJnlLine : Record "Gen. Journal Line";VAR VATEntry2 : Record "VAT Entry");**

->For 3) is no mistake for naming variables. OnBeforePostUnreaVATEntry is used VATEntry record, OnAfterPostUnrealVATCopy is used VATEntry2 record.


Thank you very much for your time!

**Comment by AncaSterian** [comment]
Dear @thpeder ,

Can you please tell us in which cumulative this update will be included?
 We are currently working to a localization package and we need this functionality for a mandatory development.
 It's possible to have it on the CU7 which will be launched in July 2018 ?

Thank you very much in advance.

Kindest regards,
 Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

New events will be implemented to Dynamics 365 Business Central only. No new events will be implemented to NAV 2018 CU’s based on GitHub requests, please contact customer support to create a hotfix request for critical events.
