### ISSUE TITLE
Reading zip files into a stream

### ISSUE THREAD

**Issue by jaadkins81** [Microsoft/AL#2283]
Hi.
Trying to use CU 706, ZipStreamWrapper, to read the zip archive entries from a zip archive of json files into separate instream objects that I could then read into separate Json Objects.  The zip archive entries are not exposed to work directly with them.   I could write an entry to an outstream object but I need to create separate instream objects for each zip archive entry.   

Unless there is a better way to do this.  The end goal is to read each json file in the zip archive into a a separate json object, respectively.

 "target": "Extension" in my app.json.

**Comment by grobyns** [comment]
Hi,

What would be your proposal for making this easier for you?
You can open the zip, get the entries, get an outstream for each entry, save it to a blob, create an instream from the blob and use that to create a json object. 

It seems to me you have all you need.

br/Gert

**Comment by grobyns** [comment]
I'm closing the issue for now.

br/Gert

**Comment by jaadkins81** [comment]
Thanks Gert.  The methods to get the zip archive entries were changed to external after I submitted this issue, which made this possible.
