### ISSUE TITLE
ERROR AL0296: The type or method 'SetCurrencyCode' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2289]
Today we have made a new report similar to 206, standard report. This report, call the function "Set Currency Code" from the table VAT Amount Line (ID: 290). This function isnt external. Do you know how to change this function to external?
![funcion-estandar](https://user-images.githubusercontent.com/22259440/40233418-3190fac4-5aa3-11e8-975d-b23f1f4a2b4f.png)

**Comment by JesperSchulz** [comment]
Thanks for you suggestion. I do have a few follow up questions though, before we can process:
1) I assume you mean Table 290 - "VAT Amount Line", not Table 206.
2) I can't seem to find the SetCurrencyCode function. The two below are there, but not the one you request to be exposed. Which version of NAV are you using? Did you maybe add the function yourself?

Thanks for clarifying!

**Comment by alvarotellez** [comment]
Hello JesperSchulz,
  1. You think correct. The Table is 290 - "VAT Amount Line".
  2. The function SetCurrencyCode is standard and Im using NAV 2018 with CU-01.

**Comment by JesperSchulz** [comment]
I've now looked through the latest versions and no version has the SetCurrentyCode function. NAV2017 had a SetCurrency function, but that was local. Also, I doubt that we would call the global variable CurrencyCod (without e), just like CurrCode isn't a widely used parameter name in the BaseApp. I'm afraid I cannot help you, as that function is nowhere to be found and it most certainly does not exist in the upcoming Business Central release. I hope you can find another way to work around your problem.

**Comment by mtarruella** [comment]
Hello, I'm the same situation as @alvarotellez, I'm creating a report based on report 206 and my code requires function SetCurrencyCode (from table 290, VAT Amount Line) to be External. The actual message shown in Visual Studio Code is the following: 

> [AL] The type or method 'SetCurrencyCode' cannot be used for 'Extension' development

Function _SetCurrencyCode()_ is located in line 460 of table _VAT Amount Line_ (T290) and it's called from trigger _SalesInvoiceLine - OnAfterGetRecord()_, line 150 of report _Sales - invoice_ (R206).

Info:
- AL Extension Version: 0.12.17091
- Server Version: 11.0.22292 (NAV 2018 CU6)

![image](https://user-images.githubusercontent.com/15626853/41777423-904fe324-762b-11e8-8b87-77a348c26d08.png)

![image](https://user-images.githubusercontent.com/15626853/41777875-278e2c68-762d-11e8-9225-f6fa70a6c058.png)

**Comment by JesperSchulz** [comment]
Found it! The function only exists in the Spanish version! I will expose the function.
