### ISSUE TITLE
Captions, Texts, Tooltips, ...

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#229]
I know it is some time to christmas yet... But I would like to suggest to decouple everything that is not actually code but metadata from the source code. 

I would like to see every text to be held in i.e. one json file per extension or multiple json files per extension. 
In the source code you could (automatically!) give any text an ID and then in the json file insert the text (including ML) for those IDs. CodeLens should still provide references to investigate where a text is used and in the code there should be an easy way to navigate to the appropriate text or better still: have it shown per Tooltip/Mouseover/IntelliSense/whatever.
This would allow a much easier and cleaner way to insert and modify and translate those texts.

Also, to make this even nicer I would like to have the opportunity to edit texts and translations in the in-client-designer which could then save those inputs directly back to such a json file which I could then include in my extension. This way I could start coding with those IDs only, put in any text and translation I need  directly where I Need it and be done.

**Comment by StanislawStempin** [comment]
You are spot on :) The first part about decoupling resource strings from source code is on our backlog.
The second part is interesting as well, we will look into it.

**Comment by Gallimathias** [comment]
Language files in the JSON format as @RafaelKoch has suggested is, in my opinion, the right way into the light
