### ISSUE TITLE
AL Code Analyzer Possible Overflow assigning text

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2291]
We have the following code:
trigger OnAction()
 var
  Textvariable: Text[30];
  Textvariable2: Text[3];
  begin
    Textvariable := 'Long text Long text Long text';
    Textvariable2 := CopyStr(Textvariable,1,MaxStrLen(Textvariable2));
end;

The AL code analyzer gives a warning: Possible overflow assigning 'text' to 'text[3]'

This is wrong as I am using CopyStr and MaxStrLen function to copy only maximum 3 characters in 'Textvariable2'

![possible overflow al analyzer](https://user-images.githubusercontent.com/29372522/40241416-4524f6ae-5abb-11e8-8f99-93416958c167.jpg)

**Comment by kalberes** [comment]
Duplicate for #1462 . But this is a bug IMO.
