### ISSUE TITLE
"Publish-NAVApp : Value cannot be null." Issue regarding translation files.

### ISSUE THREAD

**Issue by AcererakTheLich** [Microsoft/AL#2292]
Hi,

We encounter an issue working with translation files while developing on the two platforms. We are using the same source code and same package for our extension to publish to NAV 2018 and Business Central.

All works fine, same package publication on each Platform, until we try to use translation files.
Activating "TranslationFile" feature in app.json generate xxxxx.g.xlf global language file and still works fine.
As soon as we create a first translated file, it still works fine on business central but Trying to publish same package on NAV 2018 results in this error message : "Publish-NAVApp : Value cannot be null." 
Same behavior from F5 publish within VS Code or PowerShell Publish-NavApp.

We are using 0.16.14305 AL Language version and symbols from BC are System_12.0.12928.0, Application_12.1.22069.0 and for NAV 2018 (FR) System_11.0.12925.0 and Application_11.0.21836.0.

I tried several things, recreate files, and try to package with older AL version but without any success.
If I try to package using NAV 2018 corresponding AL language (al-0.12.17720.vsix), it then works with NAV 2018 but xxxx.g.xlf global language file is then recreated with totally different items ID's and we have to maintain twice same translations in two different branches.

Is there any way to maintain only one source code and one package and be compliant with the two Platform (of course using only common compatibles functionalities)?
It works fine except regarding translations.
Thank you for your help.

**Comment by DominikDitoIvosevic** [comment]
I believe I have identified the issue. We have fixed a bug with generating translation files where we were missing some information but changing the id generation would break backwards compatibility with already generated translation files for Nav 2018.

I will add support for consuming translation files on Nav 2018 which have been generated in Business Central.

@AcererakTheLich could you please provide us with AL code which was used to generate problematic translation files? Otherwise I wont be sure I guessed what your issue is.

**Comment by IvoMol** [comment]
Maybe will be useful this scenario, leading to the same error:
-	Switch on app.json "features": ["TranslationFile"]
-	Run build task (package)
-	Translation file xxxxx.g.xlf is generated
-	Publish app -> failed with “Value cannot be null.”
-	Translate file to xxxxxxx.cs-CZ.xlf
-	Publish app -> failed with “Value cannot be null.”
-	Switch off app.json "features": []
-	Publish app -> failed with “Value cannot be null.”
-	**Delete file xxxxx.g.xlf**
-	Publish app -> OK
-	Continue with work, change any object
-	Publish app -> OK
-	Publish app -> OK
Does not matter build, version, environment, debugger.
Problem is only with generated global translation file.
Tis file should be deleted or ignored when publish.

**Comment by DominikDitoIvosevic** [comment]
@IvoMol I don't think this is the same scenario. As I understand, you are having an issue that the same compiler which generated the xlf file cannot later package it in the extension.

Could you please try and isolate which AL code is causing the incorrect XLF file to be generated? Right now I do not know what is the exact issue. Can you build the extension using ctrl+shift+B with success?
Are you using the AL extension which came with your platform (don't use Business Central AL extension for Nav2018 development)?


@AcererakTheLich I'm afraid supporting XLF files generated by Business Central to work with Nav 2018 is going to require a bit more work. I don't have an ETA right now

**Comment by IvoMol** [comment]
**Using AL compiler 0.15.18771:**



**Using AL compiler 0.12.17091:**
you are not able use "features": ["TranslationFile"]

**Comment by IvoMol** [comment]
**Using AL compiler 0.15.18771:**
Problem is generated using any Label variable:
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        AppPublishedMsg: Label 'App published: Hello world';
    begin
        Message(AppPublishedMsg);
    end;
}
Translation file is created OK, I can build app many times repeatedly, but not publish (until remove XXXXXX.g.xlf).

**Using AL compiler 0.12.17091:**
Cannot use "features": ["TranslationFile"] at all.

**Comment by DominikDitoIvosevic** [comment]
@IvoMol  when using the 0.15.18771 version of the compiler, which version of the platform are you using?
What is the version number and is it Business Central or Nav2018?

**Comment by IvoMol** [comment]
Platform is NAV 2018 (on-premises), build 11.0.22292.
It is probably not an offically supported cobination, but if I want work with XLF translations outside AL files (and not with multilanguage inside AL files), I have no choice.
All works absolutely fine, but only before publishing I must manually delete XXXXXX.g.xlf file. If I forget about it, error "Value cannot be null" occurs during publishing. Delete or ignore this file during publishing and all will be perfect :-)

**Comment by StanislawStempin** [comment]
@IvoMol  -  you should use AL compiler 0.12.XXX with NAV 2018. You can still use the TranslationFile feature, it's just that the app.json syntax is slightly different. Please try:
"features" : "TranslationFile"

**Comment by IvoMol** [comment]
Solved for me: AL compiler 0.12.17091, platform NAV 2018 (11.0.22292), "features": "Translation File". 
Translation file generated, translated to cs-CZ, builded repeatedly, published repeatedly. 
Error "Value cannot be null" does not occur.
Thank you Stanislaw!
