### ISSUE TITLE
Debugger timeout

### ISSUE THREAD

**Issue by jaadkins81** [Microsoft/AL#2293]
The web client times out way to quick when launched by the debugger.  I've seen this in the last two builds I've used.  My current build is 12.0.21812.0.  

In the past, I've increased all the timeout settings in the nav server config file and that solved it.  Doing so now doesn't affect it, even bumping up the timeout in the web client config file. 

Consistently running the debugger in AL for 2-3 mins leads to a "Could not connect to the server" error in the Web client.

**Comment by GreatScott000** [comment]
I wonder if this is related to #1888

**Comment by kalberes** [comment]
Even though it is the client, but  do you have any errors/warnings for the nav server in the event viewer?

**Comment by jaadkins81** [comment]
nothing.

**Comment by kalberes** [comment]
And without debugging, just using the web client do you have the same timeouts?

**Comment by thpeder** [comment]
A fix is on its way.
