### ISSUE TITLE
Adding field to Standard primary key

### ISSUE THREAD

**Issue by jesuscristobal3** [Microsoft/AL#2295]
How could we add a field to the standard primary key into a standard tablet from an AL extension v2 Microsoft Dynamics Nav ?

**Comment by TKapitan** [comment]
It is not possible to modify keys.

**Comment by alvarotellez** [comment]
Hello, If you read the official documentation of Nav 2018, you mustnt modify any standard code. One alternative is replicate this standard table and modify it with ID 50XXX.

**Comment by jesuscristobal3** [comment]
Thank you very much !
