### ISSUE TITLE
Business Central sandbox is not provisioning after 5 hours for version 12.0.22067.0

### ISSUE THREAD

**Issue by robertosb** [Microsoft/AL#2297]
![image](https://user-images.githubusercontent.com/39469150/40301810-54a75b20-5d41-11e8-9980-ad9aab072a72.png)

**Comment by robertosb** [comment]
Hi Freddy,

  This is only when I try it from the BC interface, searching for Sandbox (Container) and clicking on the In Azure button.
   I realise I should have raised it in nav-docker issues, do let me know if you want me to recreate it there.

Cheers,
Robert

**Comment by StanislawStempin** [comment]
I moved your issue to the right GitHub forum.
