### ISSUE TITLE
More Intellisense

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#230]
When we use snippets to create fields we can see what to put in but when you just do it manually there is not really something that hints you what "field" expects.

Is this something we can expect in the future?

![helptowriteal](https://cloud.githubusercontent.com/assets/7205122/26155891/f710b71c-3b14-11e7-8781-e7f7af0290a5.png)

**Comment by bvbeek** [comment]
Good one!

Also needed on a pageextension, it's hard to find out what is expected for adding Actions

Like addbefore, addafter etc.

![image](https://cloud.githubusercontent.com/assets/28626283/26157525/b87ed93e-3b19-11e7-8d4b-1ce352bb7373.png)

**Comment by StanislawStempin** [comment]
@bvbeek - The correct keywords should already be suggested in all contexts. Try pressing Ctrl + space in the place that you highlighted.

On top of that we are working on adding signature help to structural syntax elements like action, field, key etc. Once that is completed you will which parameters and which types are required to declare a correct action, field, group etc.

**Comment by bvbeek** [comment]
@StanislawStempin, right, then I get the this, maybe add expand the snippets onafter, onbefore etc.

before
![image](https://cloud.githubusercontent.com/assets/28626283/26157970/d7eb529c-3b1a-11e7-89c6-b4732361e012.png)

after
![image](https://cloud.githubusercontent.com/assets/28626283/26157989/e144909c-3b1a-11e7-9ffc-d3482e8d10a2.png)

What to do now?

**Comment by StanislawStempin** [comment]
This is where the upcoming enhancement will help you.  Once you select 'addafter' from keyword list and type '(' you will get signature help saying something along the lines 'addafter( **target :  Identifier**)' - ' target - Identifier of the Area, Group or Field to add new content after'.

**Comment by bvbeek** [comment]
Ok, I will wait on it.
