### ISSUE TITLE
Event in Codeunit # 6501 - OnBeforeInsertAddSelectedTrackingToDataSet

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/AL#2300]
Hello Team,

Would you please add below event in AddSelectedTrackingToDataSetFunction of Codeunit 6501?

![image](https://user-images.githubusercontent.com/35543761/40323978-ec0b388e-5ceb-11e8-8e49-84e2921c8c0b.png)

Thanks

**Comment by AlexanderYakunin** [comment]
Which event and where?

**Comment by pranav4186** [comment]
OnBeforeInsertAddSelectedTrackingToDataSet Event just before TempTrackingSpecification.INSERT.
