### ISSUE TITLE
Function Request for adding "SetSelection" in Document Pages and ListPart pages

### ISSUE THREAD

**Issue by krishnaGottuparthi** [Microsoft/AL#2301]
In list Pages Function **SetSelection** is provided for masters.
![image](https://user-images.githubusercontent.com/35251581/40306347-f9da7ce2-5d1b-11e8-8655-593e9ece0ca5.png)

We have customizations wherein which the **selected records** by the user in the pages should be available for doing some further operations.
 
We need similar function in **Document pages** such as Sales Orders,Sales Quotes etc and in **ListPart** pages such as Sales Order sub form,Sales Quote sub form etc.

**Comment by Surya-mst** [comment]
yes, this would be great if SetSelection filter is available in all related pages

**Comment by grobyns** [comment]
Hi,
you can add your own SetSelectionFilter in a page extension (on an action for example). Why do you need a global external function to be added to document and lines pages?

br/Gert

**Comment by krishnaGottuparthi** [comment]
Hi Grobyns,
We tried your suggestions and it worked fine.Thank you.

**Comment by grobyns** [comment]
nice to hear :-)
