### ISSUE TITLE
OptionMember property tableextension #SOLVED

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2303]
Hello Ive just created a new field of type option. Ive 15 options, this options have multiple words with some spaces. Is it possible to have OptionMembers with spaces?

**Comment by thpeder** [comment]
Hi @alvarotellez,
Yes, you write them with quotes ```Option: "Option with ", "spaces and ", "Other symbols"```

**Comment by alvarotellez** [comment]
Thank you @thpeder !
