### ISSUE TITLE
AL Code Analyzer: PerTenantExtensionCop. Error on 50K range for field in 50K range table 

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2306]
Hi, I have created a new table in the 50K range. 
Then I've added new fields with Id's 1,2...

If I activate PerTenentExtensionCop, then I have an error that my fields should have 50K range.
Why? Is it a bug, or feature?

![image](https://user-images.githubusercontent.com/29101017/40352672-19a0b7ca-5db8-11e8-8fcb-f5d98326e602.png)

**Comment by thpeder** [comment]
Hi @dkatson,
It is a feature, when you are developing a Per Tenant Extensions then all your objects and table fields need to be withing the range.

**Comment by epernst** [comment]
WHAT???? Have that been communicated earlier? That's completely against any former best practices for development.

**Comment by RobAnderson42** [comment]
This was a bug that has been fixed. The fix has already been applied to the per tenant extension upload process (so it won't block uploads) and will be part of the next developer preview release. The ID range restriction should only be applied to fields added in table extensions, not tables.

**Comment by epernst** [comment]
I almost got a heart attack there! :)

**Comment by dkatson** [comment]
Uff... don’t joke like that
