### ISSUE TITLE
How to define a new parameter type Option? #SOLVED

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2307]
Hello, Ive seen the official documentation of Devlopment in AL already but I dont found how to solve/do this. Ive created a new procedure with a one parameter type integer and other one with type option. How can I say to the procedure's parameter which options it has?

Example:
```
procedure IsEntryIntracommunity(EntryNo : Integer; DocSource : Option):Boolean
    var
        
    begin
        case DocSource of
            DocSource::"Customer Ledger":
                
            
                
        end;    
    end;
```

Thanks!

**Comment by alvarotellez** [comment]
Ive just found how to implement this. To define option as parameter:

`procedure IsEntryIntracommunity(EntryNo : Integer; DocSource : Option "Customer Ledger","Vendor Ledger" ):Boolean`

**Comment by qutreson** [comment]
See also example in #2112
