### ISSUE TITLE
Running Tables

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#231]
In C/Side we can run a table from the Object Designer for quick data analysis/correction or testing.

How is that scenario handled in VS Code?

**Comment by StanislawStempin** [comment]
This is currently not possible due to web client limitations (VS Code is designed to only integrate with the web client). 
There is a similar issue for this topic #82, I will close this one.

**Comment by markbrummel** [comment]
I understand but it works just fine with the windows client which is what 99,5% of your customers use.
