### ISSUE TITLE
Error AL0445: The file 'f.docx' is opened in another application.

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#2311]
Issue #1351 is marked as closed & shipped. 
I'm running build 22070, and here I am still getting error AL0445, if I have a report with dataitems without any columns. Adding a column removes the error.
If this is by design, then please at least make the error message give the real reason. 👍

**Comment by DominikDitoIvosevic** [comment]
@epernst I can see that you are running on dev preview so your issue should be fixed. Could you please provide us with code which would reproduce this issue?

**Comment by epernst** [comment]
Just tested your file and it works without the error. 👍 
I'm sure that the reason I got the error is that I had a wrong path to the file name when I first tested. Putting a path that doesn't exists provokes the error again. So it should throw an error, just with a different message.
