### ISSUE TITLE
Call funtion causes error with unusual function id

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#2314]
Hello all,

i created a function in al that is impossible to call. Every time i call it the Extension causes an error (take a look at attachments).

i tried to 
- create a new function with same Name or different Name.
- call the function from a different Position in my Code.
It causes the error every time. What is this error about and how Can i make the function run?

Setup:
- latest release used.

![functionid 2](https://user-images.githubusercontent.com/26924867/40415561-af2bb04e-5e6a-11e8-811a-a4ea1fe56024.jpg)
![functionid 1](https://user-images.githubusercontent.com/26924867/40415563-af6ad04e-5e6a-11e8-900b-73eb79c64523.jpg)

**Comment by thpeder** [comment]
Hi @KaiSwitalla,
It looks like your symbol files doesn't reflect what is in your database. If you are doing Hybrid development could you try open CSide with ```finsql.exe generatesymbolreference=yes```, compile the objects and in VSCode download symbols again.

If that is not the case then could you please tell what version you are running and include a small extension that reproduces the issue.

**Comment by KaiSwitalla** [comment]
Hi,
i am not doing hybrid development. i only uses al language and visual Studio Code. My Version is:

![functionid 3](https://user-images.githubusercontent.com/26924867/40426454-a6374e1a-5e8a-11e8-9229-fd1aa0790ad0.jpg)

I do not have a small Extension for now. But i will try to extract a Little Code next days. But i have a nother Information that might by helpfull. I converted the Code using your code converting tool (C/AL -> AL). 

As far es i Can see now there are two functions (..found another one today) that have this Problem. The other one is an Integration Event:

![functionid 4](https://user-images.githubusercontent.com/26924867/40426732-56f34d4e-5e8b-11e8-9838-b99917f01834.jpg)
   
This one Looks fine for me too. I will try to send you an complete example.

**Comment by StanislawStempin** [comment]
Please make sure that you are using AL Language version 0.12.XXX. Otherwise the compiler on the server uses a different method id generation algorithm than the compiler in AL Language.

**Comment by thpeder** [comment]
I'm closing the issue since we haven't heard from you for some time and are therefor assuming the issue is resolved. If you are still experiencing the problem then just add a comment or open a new issue.
