### ISSUE TITLE
Modify optionMembers on an Options Field

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2317]
Hello,

I'm trying to add options to a Standard field.
By instict I wrote:

`        modify("Amount Type")
        {
            OptionMembers = "Net Amount","Debit Amount","Credit Amount","Debit Balance","Credit Balance";
        }`

But it seems it's a property that I can't modify:
      "The property 'OptionMembers' cannot be customized
       Error: The package could not be created."

What's the correct the way to do that?

**Comment by epernst** [comment]
This is in my mind one of the biggest challenges with Extensions, there is currently no way to add/modify/extend existing option fields. At least not without doing some funny code stuff and a shadows field, not beautiful.

**Comment by hougaard** [comment]
Yes, but just adding options is not enough. In many cases the table relation on other fields are controlled by an option (Type on Journal lines), so we also need to be able to add table relations based on the options fields.

**Comment by Gallimathias** [comment]
We're already having this discussion in #590 and in #2275 . So I think that belongs together.
