### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnAfterAutofillQtyToHandle

### ISSUE THREAD

**Issue by NAVRockClimber** [Microsoft/AL#2325]
Can you please add the following event to Table "Warehouse Activity Line" - Function "AutofillQtyToHandle"

```
[External] AutofillQtyToHandle(VAR WhseActivLine : Record "Warehouse Activity Line")
...
...
  IF NotEnough THEN
    MESSAGE(Text008);
  // ---New Code Begin---
  OnAfterAutofillQtyToHandle(WhseActivLine);
  // ---New Code End---
END;
```

Publisher Definition:

```
[IntegrationEvent] OnAfterAutofillQtyToHandle(VAR WhseActivLine : Record "Warehouse Activity Line")
```
Thank you very much.

**Comment by StanislawStempin** [comment]
The event already exists. Please always use a recent bcsandbox-master image before logging new event requests.

**Comment by NAVRockClimber** [comment]
@StanislawStempin: I used the most current Sandbox.
I am requesting a the event after you actually handled all lines.
