### ISSUE TITLE
Local Variables Don't show If they are used

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#233]
If you don't use a local variable it does not show that it is unused.

![localvariables](https://cloud.githubusercontent.com/assets/7205122/26191400/05248128-3bae-11e7-8974-4653e7b58c97.png)

**Comment by esbenk** [comment]
We have chosen not to use CodeLens references counting for locals to save CPU cycles and not to take up too much screen real-estate. We would like to provide that type of information in the future, but we don't have any timeline for that.

**Comment by markbrummel** [comment]
Thanks.
