### ISSUE TITLE
Object Type in NAV App Object Metadata Table for Table Extensions 

### ISSUE THREAD

**Issue by araratnalbantoglu** [Microsoft/AL#2334]
Hi all, 

Whenever I create a new table extension object in VS Code and publish it, I see their Object Type in NAV App Object Metadata table are created as '15' since there is no Table Extension type in Object Type field. However, PageExtension type is also 15 but has a string of its own as PageExtension. 

Kindly advise if this is regarded as a bug or done intentionally to gather extensions (table/page) in one option string and accept my apologies if this is issued before.

On a side note, I am using NAV 2018 Version (11.0.20783) and VSCode Version 1.23.1

Thanks,
Ararat

**Comment by qutreson** [comment]
Hi @araratnalbantoglu, I tried to reproduce it on our latest version of the server and of the extension and page extensions get created as 14 and table extensions as 15. 

We will add the related option members in the object type system table in AL.

**Comment by araratnalbantoglu** [comment]
Hello @qutreson, thank you for your attention, much appreciated.
