### ISSUE TITLE
Exporting data for Extensions

### ISSUE THREAD

**Issue by IvoMol** [Microsoft/AL#2335]
Trying add some data into APP.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-data-for-extension

Prepare data files OK, build package OK:
![vystrizek 0 12](https://user-images.githubusercontent.com/17826638/40485855-2b6cd8ce-5f4f-11e8-91bc-7181d517d97d.JPG)
Inspection: all four files are included inside in app file.

But after publishing APP, none of them can be seen.
- permissions are in table 2000000165+2000000166, but not visible in page 9802
- web service is in table 2000000168, but not visible on http://MyComp:7047/DynamicsNAV110/WS/Services
- report layout is not in table 9650
- table data are not imported into target table

Using AL Language extension 0.12.14734 or/and 0.15.18771 and NAV Platform Build 21836 (on-premises).

**Comment by IvoMol** [comment]
Using NAV Platform Build 22292 (on-premises):
permissions works OK, web service works OK, report layout works OK.

Table data (TAB78) still not visible in table. What exactly can data be published?

**Comment by waldo1001** [comment]
I have the same problem.  Is there any progress/data/solution?

**Comment by cmrudolph-msft** [comment]
This works for me. However, I suspect the confusion is the incompleteness of the docs (I'll talk to the right people internally).

This feature works the same way as it did in V1 extensions, meaning **a call to NavApp.LoadPackageData(ID) is required** (during install or upgrade code).

**Comment by thpeder** [comment]
The docs has been updated to reflect the necessary steps.
