### ISSUE TITLE
[Event Request] Codeunit 99000774 Calculate Routing Line, OnBeforeScheduleRoutingLine

### ISSUE THREAD

**Issue by IngoStender** [Microsoft/AL#2348]
Please add the following event to codeunit 99000774 Calculate Routing Line, function CalculateRoutingLine(). 

```
CalcExpectedCost(ProdOrderRoutingLine,TotalQtyPerOperation,TotalCapacityPerOperation);

// >> New
OnBeforeScheduleRoutingLine(ProdOrderRoutingLine);
// << New

IF ProdOrderRoutingLine."Schedule Manually" THEN
  CalculateRoutingLineFixed
ELSE BEGIN
  IF Direction = Direction::Backward THEN
    CalcRoutingLineBack(CalcStartEndDate)
  ELSE
    CalcRoutingLineForward(CalcStartEndDate);
END;

OnAfterCalculateRoutingLine(ProdOrderRoutingLine);

ProdOrderRoutingLine2 := ProdOrderRoutingLine;

```

Publisher Definition:

`[IntegrationEvent] OnBeforeScheduleRoutingLine(VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line")
`

Thank you very much.

**Comment by StanislawStempin** [comment]
The event already exists. Please make sure to always use a recent bcsandbox-master Docker image before filing new requests.

**Comment by IngoStender** [comment]
Just pulled Business Central docker image with build 23590 and publisher does not exist. Do I use the wrong Business Central version?
