### ISSUE TITLE
In-client designer fails to add fields #2

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#235]
Just like Tobias Fenster reported on https://github.com/Microsoft/AL/issues/122 the issue is happening to me today having created a fully new Azure machine for the Development Tool Preview only yesterday.

**Comment by doivosev** [comment]
Could you please provide us with a repro?

**Comment by lvanvugt** [comment]
It's the exact same repro as mentioned in https://github.com/Microsoft/AL/issues/122, that's why I did not repeat it here.

**Comment by markbrummel** [comment]
It's a know issue and been there for a while. I even noticed that Steward did not do it during his demos so I think the team is aware of it.

I'm still a little bit in the dark about the value proposition of the tool and my current thinking it is more of a nice toy for customers than something partners would use.

**Comment by lvanvugt** [comment]
:-) But on https://github.com/Microsoft/AL/issues/122 it was however reported as fixed.

**Comment by StanislawStempin** [comment]
I can reproduce the issue by following steps from #122 with the exception that there is no field called "Line Discount %" but instead "Payment Discount %".
We will look into it.
