### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post, OnAfterPostCustomerEntry

### ISSUE THREAD

**Issue by IngoStender** [Microsoft/AL#2351]
Please add the following event to codeunit 80 Sales-Post, function PostCustomerEntry(). I need to process some code when the customer ledger entry is inserted. The corresponding function PostBalancingEntry() already contains the OnBefore and OnAfter publisher around GenJnlPostLine.RunWithCheck().

Issue #1523 has a similar requirement, but based on the conversation I can't figure out if it's about the same publisher.

```
  Amount := -TotalSalesLine2."Amount Including VAT";
  "Source Currency Amount" := -TotalSalesLine2."Amount Including VAT";
  "Amount (LCY)" := -TotalSalesLineLCY2."Amount Including VAT";
  "Sales/Purch. (LCY)" := -TotalSalesLineLCY2.Amount;
  "Profit (LCY)" := -(TotalSalesLineLCY2.Amount - TotalSalesLineLCY2."Unit Cost (LCY)");
  "Inv. Discount (LCY)" := -TotalSalesLineLCY2."Inv. Discount Amount";

  OnBeforePostCustomerEntry(GenJnlLine,SalesHeader,TotalSalesLine2,TotalSalesLineLCY2,SuppressCommit);
  GenJnlPostLine.RunWithCheck(GenJnlLine);

  // >> New
  OnAfterPostCustomerEntry(GenJnlLine,SalesHeader,TotalSalesLine2,TotalSalesLineLCY2,SuppressCommit);
  // << New

END;

```

Publisher Definition:

`[IntegrationEvent] OnAfterPostCustomerEntry(VAR GenJnlLine : Record "Gen. Journal Line";SalesHeader : Record "Sales Header";VAR TotalSalesLine : Record "Sales Line";VAR TotalSalesLineLCY : Record "Sales Line";CommitIsSuppressed : Boolean)
`

Thank you very much.

**Comment by StanislawStempin** [comment]
The event already exists. Please make sure to always use a recent bcsandbox-master Docker image before filing new requests.
