### ISSUE TITLE
Getting license version warnings on Business Central environment with NAV 2018 license

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2354]
Hi,

What version of DEV license should we use for Business Central app development?
 
I am using bcinsider.azurecr.io/bcsandbox-master image and NAV 2018 dev license from partner source (Product Version 2018; Product Line: Microsoft Dynamics NAV Perpetual) and I'm getting this warning when creating new containers and publishing apps from VS Code:

``
WARNING: This license is not compatible with this version of Dynamics NAV.
``

**Comment by StanislawStempin** [comment]
Business Central from master branch is at version 13.0. I believe NAV 2018 license are at version 11.0. 
You would need to request an updated license.

**Comment by ivandjordjevic** [comment]
This is the latest one available for configuration on partner source. Where could I request updated version?

**Comment by Kowa63** [comment]
Same issue here. We downloaded the latest one available today (for NAV 2018) and still get the same warning from NAV Version: 13.0.22490.0-DE. Which strings have to be pulled to eliminate this?

**Comment by srenders** [comment]
I'm having the same issue, with a license I generated 10 minutes ago on Partnersource.

**Comment by Kowa63** [comment]
With current build 13.0.23255.0 an updated error message is shown, but the actual problem still persists. 
`WARNING: This license is not compatible with this version of Business Central`

**Comment by StanislawStempin** [comment]
The team responsible for licenses is looking into it. Since this results only in a warning I don't think any further action/tracking of this issue is needed so closing here.
