### ISSUE TITLE
Event Request: OnBeforePost in post & confirm codeunits

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2355]
One thing that I am currently missing in the posting routines are events that fire right before posting, but only when initiated by the user.

We have `OnBeforePost` in Codeunit 80 & Codeunit 90 (and similar). But those obviously fire also when posting automatically without user interaction. We also have the `OnBeforeConfirmSalesPost`, but somebody might still hook in there and change the way the sales header is posted (`Invoice` & `Ship`) afterwards (undeterministic events).

What would be handy: an event that fires only when the user is interactively initiating posting. **Before** it is posted and **after** the `Invoice`, `Ship` a.s.o. are set. Something like `OnBeforePost` that gets called in CU81, CU82, CU89 right before invoking CU80. Also for purchases. And don't forget service management.

**Comment by hemisphera** [comment]
PS: also include the Whse. Post Ship / Receive Yes / No.

Also it might help to explain myself: there are certain scenarios where I need to open a Page modally before the user posts a document, showing some summary data, errors / warnings, whatever. Therefore I need to hook into it ONLY when the user is interactivly posting. And also I require no transactions to be open.

**Comment by hemisphera** [comment]
For the sake of completeness, I'll list the events I have created in our solution DB so far ...

**Codeunit 5761 & 5762**
`OnAfterConfirmPost(WhseRcptHeader : Record 7316);`

**Codeunit 5764 & 5765**
`OnAfterConfirmPost(WhseShptHeader : Record 7320;Invoice : Boolean);`
     
**Codeunit 5981 & 5982**
`OnAfterConfirmPost(ServHeader : Record 5900;Ship : Boolean;Consume : Boolean;Invoice : Boolean);`

**Codeunit 81, 82 & 89**
`OnAfterConfirmPost(SalesHeader : Record 36);`

**Codeunit 91, 92 & 98**
`OnAfterConfirmPost(SalesHeader : Record 36);`

Please note that I have declared the document parameters **without** VAR, as to somewhat imply that "this event should not write, only read". And: also note the additional Boolean parameters for warehouse and service events.

**Comment by AlexanderYakunin** [comment]
Sorry, I cannot accept ideas as event request, we need each event specification and sample of code BEFORE/AFTER event.

**Comment by hemisphera** [comment]
OK. So here's one example for CU81.

```
LOCAL Code(VAR SalesHeader : Record "Sales Header")
OnBeforeConfirmSalesPost(SalesHeader,HideDialog);
IF NOT HideDialog THEN
  IF NOT ConfirmPost(SalesHeader) THEN
    EXIT;
```

**`OnAfterConfirmPost(SalesHeader);`**

```
SalesSetup.GET;
IF SalesSetup."Post with Job Queue" THEN
  SalesPostViaJobQueue.EnqueueSalesDoc(SalesHeader)
ELSE
  CODEUNIT.RUN(CODEUNIT::"Sales-Post",SalesHeader);
```
