### ISSUE TITLE
[Feature Request] OnAfterInput- Trigger

### ISSUE THREAD

**Issue by hhfiddelke** [microsoft/AL#2357]
In good old NAV- Forms we had the OnAfterInput- Trigger. This allowed us to implement searching.- routines where they are needed: in the input- field of a Customer-, Item- or Vendor- Number, and not in a description- field (we can't explain it to the users, that they have to search via description, if they want to enter a Customer- Card- No., or Item- Barcode)
Searching for anything is much more difficult, than Micrasoft currently Implements it. 
Items may be identified by a Barcode (using somtimes a Barcode- Scanner for input), or any other reference. Sometimes you need to refine the search (opening a Modal- Page should be possible, to show al list and enter more search options)
Customers also may be identified also by a Customer- Card in what ever Format in Input- Device.
And Customers are not as simple to find by using a simle drilldown. We have in Germany many names as Meyer, Meier, Maier, Mayer. They are all pronounced the same, so a phonetic search may be usefull and could be easily implemented.

The Trigger should be called after leaving the input- field. The parameter should be the raw text the User entered without any checks done before. The trigger itsself should have all rights to access the database- tables, to call Objects like Pages in Modal- Mode and to do validates in other fields. The returnvalue should be the resolved fieldvalue as Parameter.
Example:
```
PROCEDURE OnAfterInput(VAR pText:Text)
BEGIN
   if Search.SearchForAnythingByAnything(pText) then 
     Search.GetResolvedVal(pText)
   else
    pText :='';
END;
```

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
