### ISSUE TITLE
How to handle external donet libarys

### ISSUE THREAD

**Issue by hklemp** [Microsoft/AL#2359]
I know dotnet is a sensitive topic.
In some projects / modules I used external dotnet libraries like
- https://itextpdf.com/
- https://www.cryptosys.net/pki/

I know that I can not use their own dotent code.
But what was a valid solutions or workaround, if I have to use external dotnet libraries?

**Comment by erikrijn** [comment]
Hi Hendrik, the way you can still use .net libraries is to wrap them in your own (REST) service layer. And then use the AL HttpClient to consume them. Using the JsonObject and JsonArray functionality. If you need some help with real life application scenarios, I'd be happy to you on your way.

**Comment by Gallimathias** [comment]
There are three possibilities here:
1. use OnPremise, dotnet is possible there, unfortunately not in the cloud.
2. use as microservice a provider e.g. Azure Functions
3. or write your own microservice e.g. with C#

**Comment by hklemp** [comment]
Hi erikrijn,
hi Gallimathias,
Thank you for your suggestions. These are also the options that I have considered so far.
