### ISSUE TITLE
Testability Framework

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#236]
I get this error when publishing an extension with the testability framework. Is it supported or not ready yet?

![testframework](https://cloud.githubusercontent.com/assets/7205122/26274462/d976ea7c-3d4a-11e7-847e-514fd0f5fcd7.png)

**Comment by esbenk** [comment]
Not ready yet. A lot of the testability framework works just because the AL machinery works, but we haven't targeted it specifically. We know that it testability is important and it has high priority for us to finish that as well.
