### ISSUE TITLE
Codeunit 90 TempPurchLineGlobal Does Get Cleared

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#2362]
Codeunit 90 now uses a global temporary record variable to store a copy of purchase lines (TempPurchLineGlobal).

 This Global variable does not have its contents deleted at the start of the routine and CLEARALL does not delete the contents of the temporary table. This means that if a program uses a variable of Type Codeunit, Subtype 90 and executes the RUN function without clearing the Codeunit first, the TempPurchLineGlobal variable will contain the previous values and the posting routine will fail to work as expected.

Solution is to put a TempPurchLineGlobal.DELETEALL command at the start of the OnRun trigger of Codeunit 90.

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! We will change the code as per your recommandation. Actually, we will clear the state of all temporary, global records. Thanks again!
