### ISSUE TITLE
Delete My Notification setup when Unpublishing app

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2363]
Hi, When I unpublish App, record in My Notification setup is still there.
Should I delete that somehow? 
Or this should be handled automatically?

**Comment by StanislawStempin** [comment]
There is in general no automatic data cleanup happening as part of extension unpublish. So this and any other records need to be cleaned up manually.

**Comment by dkatson** [comment]
Ок, we have OnInstall app trigger where we can control what is happening during installation. Can we have (or we have?) onUninstall trigger to handle such situations?

Dmitry

**Comment by StanislawStempin** [comment]
Yes, we plan to add uninstall event in the future.
