### ISSUE TITLE
Suggestion: More Error Details, when installing an App within Business Central

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#2368]
In the May Update, when you try to install a publish App which cause an error you just see some unspecific error message:

![image](https://user-images.githubusercontent.com/9556549/40583763-fd1af526-6194-11e8-866c-943a450ede45.png)

Would be nice, if we would get something more to work with like in the Event Log of the Service Tier:
```
[..]
Message Unexpected event subscriber failure -- SubscriberType:CodeUnit; SubscriberId:20; TargetType:Table; TargetId:17; SubscriberCLRMethod:OnInsertGLEntry; SubscriberALName:OnInsertGLEntry; TargetMethod:OnAfterInsertEvent; Error:Value cannot be null.
Parameter name: element
[..]
```
Dynamics CRM has that Show Protocol Button on every error message. Something similar would be an improvement in my opinion.

**Comment by StanislawStempin** [comment]
The particular error that you have seen was a server bug. In normal failure scenarios you will see meaningful error messages.
