### ISSUE TITLE
Suggestion for txt2al: Show the related Line No. of that error

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#2371]
It would be nice if I could see the related Line No. in the Delta-File of a **txt2al** error (see #2369 and #2370). So I could at least see were the problem is coming from.

**Comment by qutreson** [comment]
Hi @DanielGoehler, the txt2al returns warnings when facing unsupported features. The two issues you mention seem to be bugs from the converter that we have to fix, so I am not sure how knowing the lines would help you here.

**Comment by DanielGoehler** [comment]
@qutreson I just want to report at problem as generic example and not the hole Delta-File(, which contains parts of our IP.)
