### ISSUE TITLE
Translating Package Name

### ISSUE THREAD

**Issue by lkazaz** [microsoft/AL#2374]
I am trying to find a place to set the translation of the extension package name but simply can't find any references in comments or guides. Is there a place I am missing or is this not possible at the moment?
It is important because the name is displayed in the RTC.

**Comment by thpeder** [comment]
Hi @lkazaz,
It is not possible at the moment.

**Comment by maze93** [comment]
Hi, we are experiencing problems with this as well.
This is quite urgent since the name is displayed in the menusuite when using UsageCategory for the published pages.

Will this be implemented soon?

Thanks, regards from Mattias

**Comment by cherabomb** [comment]
I agree - this is an extremely urgent issue. I am not aware of a workaround and this issue renders portions of the user interface unusable for non-English speakers. 

The extension name used for managing the extensions installed on the server should not be displayed to an end user at all; this approach to menu integration was from my perspective not well thought through. The name required to administer the package on the server is naturally different from the name displayed to an end user in his native language. Better than providing an opportunity to translate the technical package name for the end user would be to provide a method to specify the department title for the end user in all languages, completely separate to the package title.

**Comment by maze93** [comment]
Hi again all,

We resorted to the old solution by creating a partner menu, since it seems this will not be solved in quite some time. 

Rgds from Mattias

**Comment by cherabomb** [comment]
Hi Mattias,
Thanks for the tip. That is a Windows client solution, right? So you removed UsageCategory designations and manually linked the pages on a Windows client menu? Thanks.

**Comment by maze93** [comment]
Hi, correct. We manually created the partner menu in object designer like "the old days" and placed everything we needed there (however we let the UsageCategory remain in case of a fix from Microsoft. We aren't going live until September so hopefully it will be solved until then. However if it isn't, we needed to make a solution available so it will work anyway). I think this solution works for the web client also but I am not sure (our customer is only using the windows client).

**Comment by cherabomb** [comment]
Can confirm it works in web client as well. And it solves the problem with auto-generated menus disappearing that I reported here: 
https://github.com/Microsoft/AL/issues/2961

**Comment by Pieterheinevdm** [comment]
This issue isn't correct labeled, it`s a bug in my opinion that the Package/app name cannot be translated and not a suggestion.

**Comment by GuntherGebauer** [comment]
we support also the request to have a translated package name, description and Brief description

**Comment by pjllaneras** [comment]
We support this request too. It's really annoying/frustrating to have all extension translated, and in "Departments" appears the extension name as defined in app.json with no option to translate it.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
