### ISSUE TITLE
XML import treated as modal

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#2379]
In my code I'm streaming a response from a web service into an XML port and then importing it through the XML port.

The import part of the XML port is treated as modal, so if I want to use my code in a write transaction I need to add a commit before calling `XMLPort.Import()`. I have never seen a page open when I run this code and in the documentation I can't find anything about why this should be treated as a modal behavior.

So my question is this. Does the import procedure of XML ports really need to be treated as modal or is there some case which I'm not aware of which can cause a suspension of the code execution?

**Comment by kvaldik** [comment]
Hi @dennisfrostlander,
Took some time to recall the issue.

I'm using AL 0.16.26913 and BC 12.3.23590.23828-US.

This has happened in one or more occasions. The one I was able to reproduce was a subscriber to an OnRecModify. When I modify the record in a page and the `XMLPort.Import` from the subscriber hits I get the following error:

![image](https://user-images.githubusercontent.com/5981414/45482308-37b07780-b73d-11e8-93bf-2bf6f30b7ce3.png)

**Comment by dennisfrostlander** [comment]
Do you mean OnModifyRecord?

I tried the following sample, does not repro on the latest version.
Could you please provide the minimal repro which causes the error in your scenario?

```JavaScript
pageextension 50100 CustomerListExt extends "Customer Card"
{
    trigger OnModifyRecord(): Boolean
    var
        x: XmlPort MyXmlport;
        f: File;
        os: OutStream;
        is: InStream;
        rec: Record Customer;
    begin
        //f.Create('c:\temp\xmlport.xml');
        //f.CreateOutStream(os);
        //Xmlport.Export(Xmlport::MyXmlport, os);

        f.Open('c:\temp\xmlport.xml');
        f.CreateInStream(is);
        Xmlport.Import(Xmlport::MyXmlport, is);
        Message('imported xml port');
    end;
}

xmlport 50100 MyXmlport
{
    schema
    {
        textelement(CustomerElement)
        {
            tableelement(Customer; Customer)
            {
                fieldattribute(CustomerName; Customer.Name)
                {
                }
            }
        }
    }
}
```
