### ISSUE TITLE
Page Extension Triggers vs. Event Subscribers

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#238]
What is the design phylosophy behind supporting both Page Extension Triggers and Page Event Subscribers.

They seem to do the same, execute code after the standard Microsoft code is executed.

![pageextension](https://cloud.githubusercontent.com/assets/7205122/26275153/71bcbd0c-3d5a-11e7-832b-a9de429801be.png)

**Comment by esbenk** [comment]
Events came first, but we felt that with the new extension objects we could provide an easier and better way. We have no plans to remove the event support, but we expect that developers will prefer the trigger model over the events.

In the current implementation the new triggers are called "closer" to the original trigger than the events. This is an implementation detail that could changed and shouldn't be relied upon.
