### ISSUE TITLE
Modal in write transaction in upgrade code

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#2380]
Hi all. 

We just had our extension fail validation due to the following error when upgrading.

```
Start-NAVAppDataUpgrade : Could not upgrade the extension LS Express for tenant default due to the following error: The following C/AL 
functions are limited during write transactions because one or more tables will be locked. Form.RunModal is not allowed in write 
transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is 
not allowed. Report.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'Report.RunModal(...,FALSE)' is 
allowed. XmlPort.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'XmlPort.RunModal(...,FALSE)' is 
allowed. Use the COMMIT function to save the changes before this call, or structure the code differently.
    + CategoryInfo          : InvalidOperation: (:) [Start-NAVAppDataUpgrade], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.StartNavAppDataUpgrade
```

It took me quite some time to pinpoint the cause of it since as discussed in [#1614](https://github.com/Microsoft/AL/issues/1614) it is not possible to debug upgrade code. In the end I did pinpoint the failing code and added as many commits (suggested in the error message) as I could but that didn't make any difference. My guess then is that modal functionality is not allowed in upgrade/install code, which is logical since that would require user input.

I would like to point out that the error message in that case could be more informative. Stating that modal functionality is not allowed in install/upgrade code. It would also be nice to see where the code is failing.

On a normal day I would never (I hope) attempt to place modal code, that requires user input, in upgrade or install code. Instead I was calling code that I know that never requires user input but for some reason is treated as model. I created another issue [#2379](https://github.com/Microsoft/AL/issues/2379) about that.

**Comment by StanislawStempin** [comment]
The error message already provides information that a potential root cause is the use of modal:
"Form.RunModal is not allowed in write transactions."

As I understand in your case you ran into another issue #1614 but we haven't recevied enough input to reproduce/investigate it further. 

Please log a new issue if you are still encountering this problem.
