### ISSUE TITLE
Publish operation failed with code PackageDeployFailed.

### ISSUE THREAD

**Issue by Twija** [Microsoft/AL#2383]
i created an app extension for a new report. it had page extensions, table extensions, report objects.
this app is uploaded successfully to the sandbox. 
however when i uploaded the app extension to the business central, it failed with below description. 

> Publish operation failed with code PackageDeployFailed. Details: The extension failed to be deployed successfully. View the error details for more information and then deploy again.  

in order to test, i created sample helloworld app. but it also failed.

1. i use the GB Dynamics NAV 12.0 (21812) and it was created on 05/12/2017 12:44
![image](https://user-images.githubusercontent.com/32067176/40640210-00026d20-6350-11e8-83a0-33b1fc3aff2b.png)

2. create the al project.
3. create the package with al code.
4. signed with signtool.
5. uploaded it for sandbox successfully.
![image](https://user-images.githubusercontent.com/32067176/40641807-eb03ab18-6355-11e8-99b0-7bc7ac4da686.png)

6. failed to upload for production.
![image](https://user-images.githubusercontent.com/32067176/40641812-f10210fe-6355-11e8-83aa-ab10cfc7b73b.png)

Q1. where can i see the error details?
Q2. is there any futher steps to upload?
Q3. is it neccessary to upload?

**Comment by kalberes** [comment]
I think you have got your answers through CSS. Isn't it?
