### ISSUE TITLE
Event Request Table 336 Tracking Specification

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2384]
Missing Event Publisher in all Init functions to for the possibility to fill your own fields into the tracking specification

InitFromAsmHeader | ==> | OnAfterInitFromAsmHeader
InitFromAsmLine | ==> | OnAfterInitFromAsmLine
InitFromItemJnlLine | ==> | OnAfterInitFromItemJnlLine
InitFromJobJnlLine | ==> | OnAfterInitFromJobJnlLine
InitFromPurchLine | ==> | OnAfterInitFromPurchLine
InitFromProdOrderLine | ==> | OnAfterInitFromProdOrderLine
InitFromProdOrderComp | ==> | OnAfterInitFromProdOrderComp
InitFromProdPlanningComp | ==> | OnAfterInitFromProdPlanningComp
InitFromReqLine | ==> | OnAfterInitFromReqLine
InitFromSalesLine | ==> | OnAfterInitFromSalesLine
InitFromServLine | ==> | OnAfterInitFromServLine
InitFromTransLine | ==> | OnAfterInitFromTransLine

**Comment by StanislawStempin** [comment]
These events already exist in the master branch.
