### ISSUE TITLE
AL Code Analyzer - [AL] The 'end' keyword should always start a line.

### ISSUE THREAD

**Issue by cosminah** [Microsoft/AL#2390]
Hi,

I have a strange AL Code Analyzer warning for a begin..end statement that say '[AL] The 'end' keyword should always start a line'.
The 'end' statement is on a new line and have the same indentation like 'begin'.

![untitled](https://user-images.githubusercontent.com/28861979/40645710-76abf474-6327-11e8-91f7-d6c483365a16.png)
Is something wrong in my coding or is a BUG?

Thanks,
Cosmina

**Comment by qutreson** [comment]
Hi @cosminah, this looks like a bug. Which version of the extension are you using? Can you provide us with the code that triggers the warning so that we can investigate it? It is pretty hard to guess what is happening based on the screenshot only.

**Comment by cosminah** [comment]
Hi,

I'm using Extension V2, Al Language 0.15.18771.

I saw that this error appear only if if have // some comments

pageextension 50251 pageextension50251 extends "Company Information" 
{
    layout
    {
    }
    actions
    {
        addafter("No. Series")
        {
            action(NewAction)
            {
                ApplicationArea = Test;
                CaptionML = ENU='Test',
                            NLD='Test'; 
                            
                trigger OnAction()
                var
                    Test :Text;
                begin
                    message(Test); // <<Test>>
                end;
            }
        }
    }

}

**Comment by qutreson** [comment]
Thank you for your answer, this actually got fixed with #1901.
Closing as duplicate.
