### ISSUE TITLE
How to fill Temp Global Variable in page using custom function from page extension

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2392]
Context:
--> Page 11309 Apply General Ledger Entries has as Source Table "G/L Entry Application Buffer".
--> The page is open using action from page 20 "Apply Entries".
--> Before the page is opened a temporary global variable of type "G/L Entry Application Buffer named "TempGLEntryBuf" is filled up using standard function "SetAllEntries".
--> Then, the values from global temp "TempGLEntryBuf" are displayed in the page using page triggers "OnFindRecord" and "OnNextRecord".

Issue:
--> Instead of using standard function "SetAllEntries", we created our own custom function in the page and we fill in the "TempGLEntryBuf" using our own function.
--> Moving to extension, the custom function is now in an extesion and does not have access to the global temp variable from the page ("TempGLEntryBuf").
--> In this extension, we are using also other global variables from the page. Ex: ShowTotalAppliedAmount, DynamicCaption etc. 

How can we set the Global varibles in page 11309 (before this page is Run) from action ApplyEntries in page 20 using our own function ?

Page 20 General Ledger Entries: Action "ApplyEntries":

Standard Code: 
`
ApplyEntries - OnAction()
CLEAR(ApplyGLEntries);
ApplyGLEntries.SetAllEntries("G/L Account No.");
ApplyGLEntries.RUN;
`

(ApplyGLEntries is page 11309)

Modified Code:
`
ApplyEntries - OnAction()
CLEAR(ApplyGLEntries);
ApplyGLEntries.empSetAllEntries(Rec,1); //we replaced standard function with our own
ApplyGLEntries.RUN;
`

**Comment by StanislawStempin** [comment]
This is currently not possible. We are aware of these types of scenarios and thinking about potential solutions but have no ETA yet
