### ISSUE TITLE
Auto Format Code

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#240]
One of the cool features of VSCode is automatically formatting.

http://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

This seems not to be implemented in AL. Is it on the radar?

**Comment by esbenk** [comment]
VsCode only provides a keyboard shortcut and a protocol. The rest must be implemented by us. We will eventually add support for this, but it is not on our short term radar.
