### ISSUE TITLE
The value can't be evaluated into type Date.

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2400]
Hi,
I receive from external web service text value in format "dd.mm.yyyy". I want to assign this value to a date variable.
If i do 
`
dateVariableInTextFormat := '29.05.2018';
Evaluate(dateVariable,dateVariableInTextFormat)`

I receive error 
The value "29.05.2018" can't be evaluated into type Date.

I also tried 
dateVariable := JsonValue.AsDate()

but i receive an error that could not be converted.

What could be the solution?

**Comment by EugeniaLe** [comment]
This works ok:
varDate     :Date;
value         :Text;
value :='30.05.2018';
Evaluate(varDate, value);
Maybe try to replace . to / : value := value.Replace('.','/');

**Comment by dkatson** [comment]
Well, i've done with the next as a temporary solution. But this a little bit "stupid". Searching for some elegant way.

`    local procedure ConvertFromTextToDate(var DateInDateFormat: Date; DateInTextFormat: Text)
    var
        dayValue: Integer;
        monthValue: Integer;
        yearValue: Integer;
    begin
        if DateInTextFormat = '' then begin
            DateInDateFormat := 0D;
            exit;
        end;
        if StrLen(DateInTextFormat) <> 10 then
            Error('Wrong format. Date value should be in format dd.mm.yyyy');
        Evaluate(dayValue, CopyStr(DateInTextFormat, 1, 2));
        Evaluate(monthValue, CopyStr(DateInTextFormat, 4, 2));
        Evaluate(yearValue, CopyStr(DateInTextFormat, 7, 4));
        DateInDateFormat := DMY2Date(dayValue, monthValue, yearValue);
    end;
`

**Comment by dkatson** [comment]
local procedure ConvertFromTextToDate(var DateInDateFormat: Date; DateInTextFormat: Text)
    var
        dayValue: Integer;
        monthValue: Integer;
        yearValue: Integer;
    begin
        if DateInTextFormat = '' then begin
            DateInDateFormat := 0D;
            exit;
        end;
        if StrLen(DateInTextFormat) <> 10 then
            Error('Wrong format. Date value should be in format dd.mm.yyyy');
        Evaluate(dayValue, CopyStr(DateInTextFormat, 1, 2));
        Evaluate(monthValue, CopyStr(DateInTextFormat, 4, 2));
        Evaluate(yearValue, CopyStr(DateInTextFormat, 7, 4));
        DateInDateFormat := DMY2Date(dayValue, monthValue, yearValue);
    end;

**Comment by thpeder** [comment]
Hi @dkatson,
The [Evaluate](https://docs.microsoft.com/en-us/dynamics-nav/evaluate-function) function uses the current culture to parse the text, unless you specify the format number to be 9, in which case we use the XML format.

**Comment by StanislawStempin** [comment]
Please also have a look at Codeunit 10 Type Helper, it might contain a relevant function. If not, I would encourage you to submit a helper to https://github.com/Microsoft/cal-open-library
