### ISSUE TITLE
Suggestion: Please add a CodeunitExtension

### ISSUE THREAD

**Issue by megel** [microsoft/AL#2402]
It would be very nice to have a **CodeunitExtension** in the future.

The reasons why:
- Add new methods to the same context
- Access to protected Members (in the future)
- Overwrite existing Methods (in the future)

My proposal:
```javascript
codeunitextension  50100 "My Item Jnl.-Post Line" extends "Item Jnl.-Post Line"
{
    // Overloaded Method (related context & access to internal / protected variables)
    procedure RunWithCheck(var ItemJnlLine2: Record "Item Journal Line"; var runRecord: Record "My Record"): Boolean;
    begin
        if Codeunit.RunWithCheck(ItemJnlLine2) then 
        begin
            // ...
        end;
    end;
}
```

**Comment by Gallimathias** [comment]
We have already discussed this topic several times.
#84,#120,#153,#186,#593,#699,#1004,#2274

I think to solve this very important problem only the principle of heredity remains. I'm open to alternatives, but I don't think there really is another solution.

From Stanislaw's statements so far it can be said that Microsoft is working on it:

* Protected Member access
* No overwriting 

They work on it. At least that's my current state. Maybe there is an update ^^.

**Comment by db-bc** [comment]
I wonder how useful/implementable this would be now? Interfaces now provide overriding. Base codeunits often have enough horrifying global state without _also_ letting 'derived' codeunits get at least some of it... And adding new functions to existing variables by extensions seems of dubious usefulness, when we could just put them in a new codeunit (those wanting to use them will need to depend on the new app, just as they would if a 'codeunit extension' existed, _but_ they won't be surprised by new functions appearing in a standard codeunit from some extension).

**Comment by pborring** [comment]
We still do not have any near term plans on adding this, but closing this issue as we have an idea tracking the same, and this AL GitHub is for bugs in AL and VSC VSIX
https://experience.dynamics.com/ideas/idea/?ideaid=8bb24ffa-7774-ec11-b820-0003ff45920b
