### ISSUE TITLE
Combine Shipments (295) report not available in Business Central

### ISSUE THREAD

**Issue by Dave-Saman** [Microsoft/AL#2403]
The combine shipment functionality is not available in BC.
The help states you can find it through the search functionality, but this is not the case.
"Combine Return Receipts' however is still present.

BE localisation
![image 11](https://user-images.githubusercontent.com/39729982/40653550-da1932e2-633b-11e8-91b7-234baf83c361.png)
.

**Comment by qutreson** [comment]
Hi @Dave-Saman, which version of BC are you currently using?

**Comment by StanislawStempin** [comment]
We could not repro this problem.
