### ISSUE TITLE
Question: Is there a syntax to add a documentation to AL content

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#2404]
I want to add documentation to my AL Content which is shown in VS Code.

Examples are:

![image](https://user-images.githubusercontent.com/15800069/40653450-7ed48f9e-633b-11e8-8ced-9eb742cc6d78.png)

![image](https://user-images.githubusercontent.com/15800069/40653517-baba4832-633b-11e8-9166-ad6bb684f908.png)

The comments should be added by each developer for his own work to document all public / protected Methods and variables:

```
// This comment should be available for MouseOver in VSCode
var myVar: Integer
```

**Comment by thpeder** [comment]
HI @megel,
We are aware of this since it has already been asked before #132.

Thanks for your feedback.
