### ISSUE TITLE
Event request CU 900 Assembly-Post

### ISSUE THREAD

**Issue by goetudose** [Microsoft/AL#2405]
Missing publisher from Assembly-Post
[IntegrationEvent] OnAfterCreateItemJnlLine(VAR ItemJnlLine : Record "Item Journal Line";AssemblyLine : Record "Assembly Line")

![image](https://user-images.githubusercontent.com/35959288/40654286-7d5cfa7e-6346-11e8-8bce-bdf35301daaa.png)
And
![image](https://user-images.githubusercontent.com/35959288/40654346-b72ac2d6-6346-11e8-8642-91b09478f75b.png)

need to post additional information from Assembly line

**Comment by VMashevBG** [comment]
Hi, is it possible to add the same publisher in PostItemConsumption procedure? 

LOCAL PostItemConsumption(AssemblyHeader : Record "Assembly Header";VAR AssemblyLine : Record "Assembly Line";PostingNoSeries : Code[20];QtyToConsume : Decimal;QtyToConsumeBase : Decimal;VAR ItemJnlPostLine : Codeunit "Item Jnl.-Post Line";VAR WhseJnlRegisterLine : Codeunit "Whse. Jnl.-Register Line";DocumentNo : Code[20];IsCorrection : Boolean;ApplyToEntryNo : Integer) : Integer

....
`  ItemJnlLine.Correction := IsCorrection;`
`  ItemJnlLine."Applies-to Entry" := "Appl.-to Item Entry";`
`  UpdateItemCategoryAndGroupCode(ItemJnlLine);`
`END;`

`//>>Change`
`OnAfterCreateItemJnlLine(ItemJnlLine , AssemblyLine);`
`//<<Change`

`IF IsCorrection THEN`
`   PostCorrectionItemJnLine(`
`      ItemJnlLine,AssemblyHeader,ItemJnlPostLine,WhseJnlRegisterLine,DATABASE::"Posted Assembly`
`Line",ApplyToEntryNo)`
.....
