### ISSUE TITLE
Missing [External] - table "My Notifications" - IsEnabledForRecord

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#241]
I expect lots of [External]-attributes missing on current functions... .  One of which I noticed today is the function "IsEnabledForRecord" in the table "My Notifications" - which now prevents me from using the "My Notifications" functionality decently in ExtensionV2.

And by the way - naming conventions would say that the tabel  "My Notifications" should be "My Notification" ;-)

**Comment by StanislawStempin** [comment]
We are actively reviewing requests for unblocking [Internal] functions. Please continue reporting instances that you require.

**Comment by waldo1001** [comment]
Can I ask why there is a difference between "global" and "external" functions? I mean - why not just have all global functions be "external"?

**Comment by StanislawStempin** [comment]
The difference is that "external" functions can be accessed by code modules compiled with all targets, whereas "global" "internal" functions can only be accessed by code modules compiled with target "Internal" (which means mostly Microsoft modules or on-prem code customizations).
