### ISSUE TITLE
SignFactor default exit integration CU 99000830

### ISSUE THREAD

**Issue by goetudose** [Microsoft/AL#2417]
To integrate Tracking into our localization we need to exit a positive or negative value for our table.
An event is required right before the SignFactor function end, whitch occur only if no exit happened("Source Type" is no standard table).
Example of integration: LOCAL [IntegrationEvent] OnAfterSignFactorVerification(ReservEntry : Record "Reservation Entry")
![image](https://user-images.githubusercontent.com/35959288/40665764-c2ca9448-6366-11e8-9261-95613a83cd5b.png)

No need to change ReservEntry, only to check "Source Type".

**Comment by AncaSterian** [comment]
Dear @thpeder ,

Can you please tell us in which cumulative this update will be included?
 We are currently working to a localization package and we need this functionality for a mandatory development.
 It's possible to have it on the CU7 which will be launched in July 2018 ?

Thank you very much in advance.

Kindest regards,
 Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

New events will be implemented to Dynamics 365 Business Central only. No new events will be implemented to NAV 2018 CU’s based on GitHub requests, please contact customer support to create a hotfix request for critical events.

**Comment by AncaSterian** [comment]
Dear Thomas,

Thank you very much for the prompt answer.

But should we proceed with the following development on NAV 2018?

Microsoft would stop the releases for it ?

Thank you very much.

Kindest regards,
Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

NAV 2018 is a released product which won't get all the fixes and changes futures versions will contain.
Updates will still get released like it has been done for previous releases.

Read more about the release schedule here: [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)

**Comment by AncaSterian** [comment]
Dear Thomas,

Thank you very much for the answers.

Kindest Regards,
Anca
