### ISSUE TITLE
Converting test codeunits from cal to Al issue

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#2418]
Hi 
I tried converting my test codeunits to AL objects ,after i tried checking my errors 
what i observed majorly is for testpage variables it is showing tabledataXXXXX ;
example : salesinvoicepage : Tespage TableDataXXXXXX
and one more thing is that the base Testpages are also updated with some other page names
 ex: SalesInvoice: TestPage "Purch. Comment Line";
![13](https://user-images.githubusercontent.com/39740300/40672631-fe9148ac-638c-11e8-8dea-cc1c89809a57.png)

please check the attachments
![12](https://user-images.githubusercontent.com/39740300/40672517-ae852900-638c-11e8-907f-f2778957e38b.jpg)

**Comment by thpeder** [comment]
Hi @srinivasbanny,
What is the version of the server you got the Txt2AL converter from?

**Comment by srinivasbanny** [comment]
@thpeder 
AL Compiler version 0.15.18771
Version 12.0.21812

**Comment by srinivasbanny** [comment]
@thpeder  any update ?

**Comment by thpeder** [comment]
@srinivasbanny not yet, I have been busy with some other stuff, But i'll try to get back to you soon with some more info.
Usually we see these problems when people don't specify ExportToNewSyntax when exporting the objects from the database, since the default .txt is not good enough.
Is it from a delta file or a full object?

**Comment by srinivasbanny** [comment]
@thpeder it just came from the delta files after conversion

**Comment by thpeder** [comment]
And the two files used to generate the delta file was both exported with the ExportToNewSyntax command?

**Comment by srinivasbanny** [comment]
@thpeder yes both have been exported with exportnewsyntax

**Comment by thpeder** [comment]
@srinivasbanny, We don't have Codeunit extension objects in AL which leads to that we don't support delta files for Codeunits, so you need to just export the newest version of your codeunit and convert that.
But before you export that object try and compile the entire database first.

**Comment by srinivasbanny** [comment]
@thpeder  We have tested with converting from txt2al but there is no change

**Comment by thpeder** [comment]
@srinivasbanny Did you try and recompile your database in CSide and then do another export?

**Comment by thpeder** [comment]
I'll assume that it worked for you and close the Issue. If not feel free to add another comment.
