### ISSUE TITLE
Access to Global Temporary variable in page from Page extension 

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2422]
Version 13.0.22070.0

PAGE 161 "Purchase Statistics"

I am trying to convert custom modification made to this page to a Page Extension.

At the end trigger OnAfterGetRecord we have added a function that does some calculations and copies some values based on the values from global variable "**TempVATAmountLine**"

The issue is that in the Page Extension we don't have access to this global temporary variable.
![issue access global var](https://user-images.githubusercontent.com/29372522/40711463-8367e5b8-63fb-11e8-8929-bec3eb99d9f2.jpg)

We have this situation multiple times, not only at this example and sometimes we filled another temporary in the page extension but it is bad practice (duplicating code, executing similar code multiple times), so we want to ask you if there is a better workaround for this ?

**Our idea** is if you can **add an Event publisher in page 161 at the end of OnAfterGetRecord** trigger that will contain a **by reference parameter of the global variable "TempVATAmountLine"**. In this way if we subscribe to that event we could have access from the page extension to that global variable that contains values calculated in the page.

Thanks,
Andrei Lungu

**Comment by andreilungu** [comment]
Hello,

I tested with the event added in the new build, but now I think that this solves the issue partially:

- As I said in the previous message, we need to copysome values based on the values from global variable "TempVATAmountLine" to another global variable from the page extension called "TempVATAmountLine2".
- The issue now is because of the limitation that an event subscriber can be added only in a Codeunit. So I create a new codeunit, subscribe to the OnAfterCalculateTotals publisher you added in the new build and copy the needed values in a global variable "TempVATAmountLine2" in the newly created codeunit. 
- The "TempVATAmountLine2" cannot be retrieved from the Codeunit to the page extension (where we need to use it later on). (It is possible only if we make the codeunit SingleInstance but we want to use it like this only as a last option...)

We need the "TempVATAmountLine2" in the page extension because we use it later on to populate a custom added subform.

Please see how it was in 2017 version:
![customform](https://user-images.githubusercontent.com/29372522/41594922-5ef123e6-73c5-11e8-9738-2ec23d3d6245.jpg)
![populate and use tempvatline2](https://user-images.githubusercontent.com/29372522/41594931-63e3234a-73c5-11e8-86d0-3b9b18fca2fb.jpg)

How do you recommend to implement this (preferably without Single Instance Codeunit) ?
![subscriber codeunit](https://user-images.githubusercontent.com/29372522/41595093-ee4575a6-73c5-11e8-99d0-af06a2940fab.jpg)

Event Subscribers cannot be created in a page:
![event subscribers cannot be created in a page](https://user-images.githubusercontent.com/29372522/41595181-2e78c416-73c6-11e8-82f4-053dbe9eccd0.jpg)

**Comment by bogdan81GitHub** [comment]
The same issue happens also for page 401 Purch. Credit Memo Statistics. The scenario is the same with global variable "TempVATAmountLine".
