### ISSUE TITLE
Codeunit 5601 “FA Insert G/L Account”

### ISSUE THREAD

**Issue by goetudose** [Microsoft/AL#2425]
In our localization for some Fixed Assets is calculated “Limited deductibility”.  

In order to do that is needed to add a new parameter for OnGetBalAccAfterSaveGenJnlLineFields

LOCAL [IntegrationEvent] OnGetBalAccAfterSaveGenJnlLineFields(VAR ToGenJnlLine : Record "Gen. Journal Line";FromGenJnlLine : Record "Gen. Journal Line";VAR SkipInsert : Boolean)

Add a new line in GetBalAcc function.

![image](https://user-images.githubusercontent.com/35959288/40715809-7e3c7086-640f-11e8-8669-3f74074b424f.png)

Change Scope for InsertBufferEntry from LOCAL to Global.

**Comment by AncaSterian** [comment]
Dear @thpeder ,

Can you please tell us in which cumulative this update will be included?
 We are currently working to a localization package and we need this functionality for a mandatory development.
 It's possible to have it on the CU7 which will be launched in July 2018 ?

Thank you very much in advance.

Kindest regards,
 Anca

**Comment by thpeder** [comment]
Hi @AncaSterian,

New events will be implemented to Dynamics 365 Business Central only. No new events will be implemented to NAV 2018 CU’s based on GitHub requests, please contact customer support to create a hotfix request for critical events.
