### ISSUE TITLE
Generic Chart - not possible use tables from extensions

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#2427]
Is not possible to create chart with table from extension. I can select the table from list:
![table2](https://user-images.githubusercontent.com/39334704/40716304-2e24e0fe-6411-11e8-99f8-16ff8d07ecc3.PNG)
![table](https://user-images.githubusercontent.com/39334704/40716295-293c22aa-6411-11e8-9363-36a9e001e206.PNG)

**Comment by thpeder** [comment]
Copy of #856
