### ISSUE TITLE
Page with SourceTable = "Date" issue

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#2429]
I have an issue, If i use SourceTable = "Date";  on the page created on extension. NAV can not find this page neither the search box, neither in the menu, if I want to open this page with action button from the ribbon, the button disappears if i use SourceTable = "Date". Does anyone have the some or similar issue and can share expieiance with me?

![bug](https://user-images.githubusercontent.com/39334704/40719346-0953d1ee-641c-11e8-9f0a-7e4909324d76.PNG)

**Comment by SBalslev** [comment]
While building the navigation tree the platform removes all items you do not have license for. The date table is one of the system tables where you do not have direct access to the table data.
If you look at your licenses you'll see that 2000000007 is missing.
