### ISSUE TITLE
txt2al automatically converts to xliff?

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#2430]
I'm converting my deltas (C/AL pages) into page extensions using txt2AL.exe (13.0.22070), I noticed my captionML fields are converted into xliff files. The .al files now only contains captions.

Is this default behaviour now? Are there any command parameters that are non-documented that we can use to (temporary) use the CaptionML?

I read about handling of Xliff files on (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files). Which quite well to follow. However I don't understand how real life development scenario's will be implemented. In our environment we have two languages supported (Dutch and English). To my understanding process will look like:
- When generating the AL project default .xliff is also created
- Default .xliff must be copied and in header we can set the correct translation to NL
- File can be translated manually or using translation service

When new fields / pages are added to my extension a new Default .xlif will be created. How do the new fields/pages end up in my translated XLIF file? Manually? Is there a merge tool???

**Comment by markbrummel** [comment]
I noticed the same and have the same questions. I would like to see the Xliff files optional. Our database is a one-off customer specific solution and Xliff is overkill. We code in English and just add Dutch captions.

**Comment by Gallimathias** [comment]
We had already had this discussion in #1702. I stand by my statement there.

Good tools converted from the template file to the target files we collect here #919

I personally recommend Weblate or Pootle.

Before anyone gets the idea to reclaim the old CaptionML and can't do anything with the two mentioned tools, I would agree to make my own OpenSource Community tool.

But only after my exam :D

**Comment by StanislawStempin** [comment]
Thank you for the input. Regarding the txt2al converter there is currently no parameter to prevent xliff generation since this is the long-term direction for translations. 
As mentioned in #1702 there are multiple possible approaches to handle the translation flow, either though xliff tooling or scripting. 
Long-term we will consider optimizations for this process but it is currently not a top priority.
