### ISSUE TITLE
Table Snippet - Key

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#244]
Each time I create a new table I have to fix the primary key becuase it does not use the same name as the first field and it includes a second field that does not exist.

It would be easier if the PK just points to the first field and I can use the "F2" to update the fieldname and key at the same time.

I would have added that to the snippet on GitHub but to my surprise this was already the case in the Snippet from Feb. 23rd.

Are the snippets in the preview updated from this repository?
![key](https://cloud.githubusercontent.com/assets/7205122/26439057/e1c3c7a8-4115-11e7-9014-b4a4db2a9e21.png)

**Comment by StanislawStempin** [comment]
You're right, the name in the key should correspond to the first field name. We will fix that.

Existing snippets might be a little out of sync with the version present on GitHub. We will be releasing an updated version in the near future.

**Comment by markbrummel** [comment]
Thanks.
