### ISSUE TITLE
Adding Fields to a Page

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#2440]
This is probably more feedback than anything else.

Adding fields from a table to a page is probably one of the places where the speed difference between C/Side and VSCode is best illustrated.

If you create a page with for example 20 fields it is a terribly boring experience to create the first page. Once the page is created the second one is easier.

I know you guys are incredibly smart so I was hoping that when putting this somewhere in the back of your mind a solution might pop up at one point in time.

**Comment by RafaelKoch** [comment]
Hi Mark, try the VS Code Extension "AL Code Outline" by Andrzej Zwierzchowski. 
I found by accident that when I review the outline for a table I can right-click and have it create a card page, liste page, query, … for that table.

**Comment by markbrummel** [comment]
I'll give that a try.

I'm actually looking for something like SQL Server Management studio where I can create the syntax to the clipboard and paste where I want it.

Something like you add five fields to a table and want those five fields added to the pages.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider it for our backlog.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
