### ISSUE TITLE
RapidStart in BCSandbox, can't access Extension table?

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2444]
So I'm in the process of moving existing test data into my BCSandbox on Docker.  Trying to use the BC tools for importing data which means Configuration Packages.  I try to add my extension table to the Configuration Worksheet and I get this message:

> The field Table ID of table Config. Line contains a value (9095100) that cannot be found in the related table (Object).

The Table Id is for my table and it DOES appear in the lookup.
So how do I get test data into my sandbox?

**Comment by StanislawStempin** [comment]
This issue was fixed in Developer Preview June update and will be fixed in the online update 12.2 due next month.

**Comment by fibbert** [comment]
Is this fix going to be available in the next NAV 2018 CU?
