### ISSUE TITLE
Azure Function and Dlls

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/AL#2446]
We have a Visual Studio project (using C#) and we would like to deploy as an Azure Function or Dll. We want to keep (as mush as possible) one code base for Dlls and Azure Function.
Do you have any documentation/information of how to do it?

**Comment by BartPermentier** [comment]
I used this: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function

**Comment by SergioKelly** [comment]
Thank you
