### ISSUE TITLE
Disappearing Items in Search

### ISSUE THREAD

**Issue by RonSkalski** [Microsoft/AL#2448]
I'm having some inconsistent issues with adding pages that appear in the menu search on a sandbox tenant.  I built my .app and used extension management to load. It installs fine with no errors. After which, I was not able to find my new pages in the search menu. I had another user check and they were able to see the pages in search. Another user was not able to see the search menus but after a while had changed profiles to production manager and the search started to show. Overnight, they have disappeared for everyone. The app still shows as installed on the extension management list. The permission set for the new tables still exist. My login has the new permission set but the two others never had the permission set added to them (all of us are in as SUPER).  In another attempt with another custom build, I have similar issues with the search. In that instance, custom fields extended to standard tables and pages still show while the search does not show.  The sandbox system information shows as US Dynamics NAV 12.0 (21229)

Here is a sampling of code I added to one of the pages that are not showing in search.

page 66003 "SIK-QC Setup"
{
    PageType = Card;
    SourceTable = "SIK-QC Setup";
    DeleteAllowed = false;
    InsertAllowed = false;

    ApplicationArea = All;
    UsageCategory = Administration;

    Caption = 'QC Setup';

I also have  ApplicationArea = All;   in each of the fields on the page.

**Comment by RonSkalski** [comment]
BTW - I am using AL Language 0.15.18771

**Comment by kalberes** [comment]
This has been fixed in our main. Please raise an issue with CSS to get these backported.  
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-not-related-to-al-development-what-do-i-do

**Comment by RonSkalski** [comment]
This is the latest AL download from marketplace. The sandbox is a true BC sandbox and not a docker image. I believe that makes it the correct mix. 

It appears to be an issue for many users
https://community.dynamics.com/business/f/758/t/279427

**Comment by StanislawStempin** [comment]
The issue has been fixed in master builds this week and will be available in June Preview.
