### ISSUE TITLE
Question: How can we import an image (Media/MediaSet) via code (to initialize Demo Data)?

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#245]
In Extension 2.0 we cannot use any DotNet interop. 

I know we can use the <image>.IMPORTFILE and IMPORTSTREAM.
But if you want to import a file, you need a file, how can we create this file?
Possible solution is to store the Image as Base64 string in code.
But how can we decode the string without DotNet?

Or can we add the images seperated with the .navx file or something?

**Comment by StanislawStempin** [comment]
We are looking into an idea of embedding limited size resources as part of the .navx package. 
For now some of the other options are:
- fetch the images through HTTP request
- create a setup table in your extension, export the content using Export-NAVAppTableData and bundle it with your extension. [See the docs](https://msdn.microsoft.com/en-us/dynamics-nav/how-to-export-data-for-an-extension)
- your own suggestion of using BASE64 encoded string - you can use TempBlob.FromBase64String to decode it (procedure is blocked in April Update but it will be enabled in June Update coming out soon)

**Comment by bvbeek** [comment]
Ok, we will use the TempBlob.FromBase64String feature for this

Thanks!
