### ISSUE TITLE
trigger OnAssistEdit  doesn't show an Assist button on page

### ISSUE THREAD

**Issue by joergrau** [Microsoft/AL#2451]
Adding a trigger OnAssistEdit on a page field compiles without problems but doesn't show an Assist Button. 
OnLookup works fine.

**Comment by atoader** [comment]
Hi @joergrau ! Could you please provide a sample that reproduces this issue? It would be great if you could also let us know what your environment is.

**Comment by Fbreus** [comment]
Hello

I'm facing the same issue, I created a tableextension on the "Prod. Order Routing line" table where I added a field "Filepath
`tableextension 50003 "UPA1 Prod. Order Routing Line" extends "Prod. Order Routing Line"
{
    fields
    {
        field(50000; Filepath; Text[250])
        {
            Caption = 'Filepath';
        }   
    }`

I also created a Pageextension on the "Prod. Order routing Line" Page where I added this new field and want to use the "OnassistEdit()" trigger to call the filedialogwindow.

However when deploying the code the "..." assistedit icon does not appear on the field that the page is extended with.
`pageextension 50008 "UPA1ProdOrderRouting" extends "Prod. Order Routing"
{
    layout
    { 
        addlast(Control1)
        {
            field(Filepath;Filepath)
            {
                ApplicationArea = All;
                ToolTip = 'Filepath';
                trigger OnAssistEdit();
                var
                    FileMgt:Codeunit "File Management";
                    FileDialogWindowTxt:label'Please select a file';
                begin
                    FileMgt.OpenFileDialog(Copystr(FileDialogWindowTxt,1,50),'','');                 
                end;
            }   
        }  
    }
}`

**Comment by joergrau** [comment]
Hi @atoader, 

Using AL Language 0.15.18771
Here a complete sample page:

![assistedit](https://user-images.githubusercontent.com/6723135/41033104-82a2b2f0-69d9-11e8-85b1-d3f49571068c.png)

On the left you see an Assist Edit button which is actually a lookup. On the right there is no button at all where there supposed to be the Assist Edit button.

Full code below.

`page 50000 "Assist Edit Test Page"
{
    

    CaptionML = ENU = 'Assist Edit Test Page',
                ENZ = 'Assist Edit Test Page';
    PageType = Card;

    layout
    {
        area(content)
        {
            group(General)
            {
                group("Field to Modify")
                {
                    field("Table No."; SelectedTableNo)
                    {

                        trigger OnLookup(Text: Text): Boolean;
                        var
                            Tables: Record "AllObjWithCaption";
                        begin
                            Tables.RESET;
                            IF PAGE.RUNMODAL(669, Tables) = ACTION::LookupOK THEN BEGIN
                                SelectedTableNo := Tables."Object ID";
                                SetTableNo;
                            END;
                            CurrPage.UPDATE(FALSE);
                        end;

                        trigger OnValidate();
                        begin
                            SetTableNo;
                        end;
                    }
                    field("Table Name"; Field.TableName)
                    {
                        Editable = false;
                    }
                    field("Field No."; SelectedFieldNo)
                    {

                        trigger OnLookup(Text: Text): Boolean;
                        begin
                            Field.SETRANGE("No.");
                            IF PAGE.RUNMODAL(6218, Field) = ACTION::LookupOK THEN BEGIN
                                SelectedFieldNo := Field."No.";
                                SetFieldNo;
                            END;
                        end;

                        trigger OnValidate();
                        var
                            SelectTableNoFirstError: TextConst ENU = 'Please select a Table first.', ENZ = 'Please select a Table first.';
                        begin
                            IF SelectedTableNo = 0 THEN
                                ERROR(SelectTableNoFirstError);
                            SetFieldNo;
                        end;
                    }
                    field("Field Name"; Field.FieldName)
                    {
                        Editable = false;
                    }
                }
                group("Filter")
                {
                    field("Table Filter"; TempPermission."Security Filter")
                    {

                        trigger OnAssistEdit();
                        var
                            TableFilter: Record "Table Filter";
                            TableFilterPage: Page "Table Filter";
                        begin
                            TableFilter.FILTERGROUP(2);
                            TableFilter.SETRANGE("Table Number", SelectedTableNo);
                            TableFilter.FILTERGROUP(0);
                            TableFilterPage.SETTABLEVIEW(TableFilter);
                            TableFilterPage.SetSourceTable(FORMAT(TempPermission."Security Filter"), TempPermission."Object ID", TempPermission."Object Name");

                            IF ACTION::OK = TableFilterPage.RUNMODAL THEN
                                EVALUATE(TempPermission."Security Filter", TableFilterPage.CreateTextTableFilter(FALSE));
                        end;
                    }
                }
                group(Change)
                {
                    field("New Value"; NewValue)
                    {
                    }
                }
            }
        }
    }

    var
        "Field": Record "Field";
        SelectedTableNo: Integer;
        SelectedFieldNo: Integer;
        NewValue: Text;
        TempPermission: Record Permission temporary;

    local procedure SetTempPermission();
    begin
        WITH TempPermission DO BEGIN
            INIT;
            "Object Type" := "Object Type"::"Table Data";
            "Object ID" := SelectedTableNo;
            IF INSERT THEN;
        END;
    end;

    local procedure ClearTempPermission();
    begin
        TempPermission.RESET;
        TempPermission.DELETEALL;
    end;

    
    local procedure SetTableNo();
    begin
        IF SelectedTableNo <> 0 THEN BEGIN
            Field.RESET;
            Field.SETRANGE(TableNo, SelectedTableNo);
            Field.FINDFIRST;
            SelectedFieldNo := Field."No.";
            ClearTempPermission;
        END;
        CurrPage.UPDATE(FALSE);
    end;

    local procedure SetFieldNo();
    begin
        Field.SETRANGE("No.", SelectedFieldNo);
        Field.FINDFIRST;
        SetTempPermission;
        CurrPage.UPDATE(FALSE);
    end;
  

    
}

`

**Comment by may2503** [comment]
Hello, 
i have the same Problem with the AL Language 0.12.15355. I created a Card-page with a "No." field and i add the "OnAsisstEdit"-trigger. In RTC i missing the AssistButton. 

i changed my Code and i use the OnLookup-trigger and OnValidate-trigger, but it doesn't work. 

` layout
    {
        area(content)
        {
            group(General)
            {
                field("No.";"No.")
                {
                    Caption = 'No.';
                    trigger OnLookup(Text : Text) : Boolean;
                    begin                       
                        AssistEdit(xRec);        
                    end;

                    trigger OnValidate();
                    begin
                        AssistEdit(xRec);
                    end;
                    
                    //trigger OnAssistEdit();
                    //begin
                    //    AssistEdit(xRec);
                    //end;
                }`
![fehler](https://user-images.githubusercontent.com/40017102/41081772-60ae0aa2-6a2c-11e8-8bfe-820b7024cbff.JPG)
