### ISSUE TITLE
Data deletes when I published Extension 2.0 in NAV 2018 CU5

### ISSUE THREAD

**Issue by MesutGulsuyu** [Microsoft/AL#2453]
Hi,
I use NAV 2018 CU5 and I create Table in Visual Studio Code. When I published extension data was delete

**Comment by pjanfred** [comment]
Hi,
add "schemaUpdateMode": "Synchronize" to your launch.json.

**Comment by MesutGulsuyu** [comment]
Hi @pjanfred 

I tried "schemaUpdateMode" but it didn't work

![image](https://user-images.githubusercontent.com/35994170/40912088-466d2dec-67f9-11e8-8bb6-839242b23e29.png)

**Comment by StanislawStempin** [comment]
Could you please contact regular support channel with this problem. 
This forum is only for supporting the latest Developer Preview release. 

https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

As suggested above the schemaUpdateMode - Synchronize should have solved the problem.

https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
