### ISSUE TITLE
Query - DataItemTableFilter does not work with extension fields

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#2454]
Let's say that we create an extension table object that adds a boolean field to the Customer table:

```
tableextension 50100 CustomerExt extends Customer
{
    fields 
    {
        field(50100; TestField; Boolean)
        {
            DataClassification = CustomerContent;
        }
    }
}
```

Then we create a Query that publishes a few fields from the Customer table, but just for those records where *TestField* is *false*.

```
query 50100 CustomerQuery
{
    QueryType = Normal;
    
    elements
    {
        dataitem(Customer; Customer)
        {
            DataItemTableFilter = TestField = const(false);
            column(No; "No.") {}
            column(Name;Name) {}
        }
    }
}
```

Finally, we include an XML in our extension so that the Query is published through OData:
```
<?xml version="1.0" encoding="utf-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>9</ObjectType>
            <ServiceName>Test</ServiceName>
            <ObjectID>50100</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```
If we try to access the query through its URL, (https://server:7048/NAV/ODataV4/Company('CRONUS%20ES')/Test?tenant=default), we get the following error:

```
{"error":{"code":"Unknown","message":"El siguiente error SQL no se esperaba:\r\nThe multi-part identifier \"Customer_e3.TestField\" could not be bound.\r\nStatement(s) could not be prepared.\r\n"}}
```

The part in Spanish (we deployed the NAV ES preview) says "Unexpected SQL Error". 

It looks like NAV is generating an SQL sentence that tries to filter using this field, as if it where in the Customer Table, but the extension field is actually in a different table, created by NAV when the extension was published.

We are currently using the latest Business Central Preview (May 2018) + AL Extension 0.15.18771, but this is a problema that also occurred with the previous preview + the AL Extension in the Marketplace.

**Comment by cmrudolph-msft** [comment]
Looks like an internal platform defect. I will get this fixed tomorrow.

**Comment by salgiza** [comment]
@cmrudolph-msft  

I just discovered that the same error happens in the DataItemLink (joining two data items using a new extension field in one side of the relation).

Hopefully this will have been fixed as well, but I thought I should mention it just in case.

**Comment by cmrudolph-msft** [comment]
@salgiza 

Thanks for reporting this. Some of the DataItemLink cases work, but based on your feedback I found a few more things that are unhandled. I will take a new bug on this.
