### ISSUE TITLE
OnBeforeAction and OnAfterAction not working

### ISSUE THREAD

**Issue by gnaaktgeboren** [Microsoft/AL#2455]
Hi,

I've made a page extension for page 5725 Nonstock Item Card.
On the page extension I've added the code below to modify the Create Item action.
This is not working.

If I try the same with the Substitutions action it does work.
The difference is that the Substitutions action as a RunObject specified and the Create Item Action has a OnAction trigger.

Is this a bug?

`        modify("&Create Item")
        {
            trigger OnBeforeAction();
            begin
                Message('Before');
            end;
            trigger OnAfterAction();
            begin
                Message('after');
            end;
        }
`

**Comment by qutreson** [comment]
The server does not support it for now. See #942.
