### ISSUE TITLE
XLIFF and tracing back to source

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2457]
How do I trace back from a XLIFF entry to it's source in the code?  The XLIFF "id" is some generated number that does not appear to have any reference to the object ID.  If a translator asks me what the context of a caption is how to do I find it?

Example below "id="Codeunit 3220928611" comes from an Codeunit with the Object ID of 9095101.
```
        <trans-unit id="Codeunit 3220928611 - NamedType 3114637384" maxWidth="999" size-unit="char" translate="yes" xml:space="preserve">
          <source>WIP %1</source><target state="translated">WIP %1</target>
          <note annotates="general" from="Developer" priority="2">%1 is a description</note>
          <note annotates="general" from="Xliff Generator" priority="3">Codeunit - Label</note>
        </trans-unit>
```

**Comment by SirBETE** [comment]
[Go to the may update of the Developer Preview](https://blogs.msdn.microsoft.com/nav/2018/05/25/developer-preview-may-2018-update/)

**Comment by StanislawStempin** [comment]
Correct, this was fixed in the recent preview release.
