### ISSUE TITLE
[ControlAddin question] Editing the id of <div> element

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#2461]
Hi,

As i am trying to put two controladdins in the same page, I'm facing the problem that my two controladdin are sharing the same id for their "div" element: I have to use the "#controlAddin" selector for both of them ..!

Will it be possible, at the creation of the controladdin object, to add, as a new property, something like 
**ElementID =**  in order to be able to control more than one controladdin in the same page ..?

Or maybe there is some ways that already existing i'm not aware of..?

Thanks !

[EDIT]
I just found how to do this by modifying my Javascript file:

**document.getElementById('controlAddin').id = 'newId';**

But adding this as a property of the controladdin object could be interesting :)

**Comment by SCullman** [comment]
Each ControlAddin is placed in its own iframe. Therefore you don't need to modify the id at all.

**Comment by JulienDecottignies** [comment]
Yes thank you for your answer. I figured it with another project. I don't know what was in my head re-reading me now..!

**Comment by atoader** [comment]
I will close this issue as it appears that it has been resolved.
