### ISSUE TITLE
DOTNET variables are not supported with AL Extension for NAV, we can see the variables but we cannot use its classes. 

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#2465]
Before logging a new issue please make sure to:
1) Read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)
2) Search if there is an existing issue for what you want to log. If it's closed you can reopen it and add your comments.
3) Use the latest Developer Preview release both the server part and the AL Language extension in VS Code (listed on the [repository home page](https://github.com/Microsoft/AL))
4) If you're not using the latest released version (or are using a private build drop that is newer) please provide the version number in the issue

To help us reproduce the issue and find the root please try to:
A) Attach a minimal set of AL code that causes the issue
B) If the error occurs on the server - copy/paste the server stack trace from the Event Viewer

**Comment by atoader** [comment]
Hi @rishiaurrishabh . Could you please explain what you mean?

**Comment by rishiaurrishabh** [comment]
Hi @atoader , I mean that on AL Code I can see that there is a variable for dotnet but when try to use that variable for ex- TableList of in the same way we have it on BuildDynamicRequestPage function of COD1530 so I am not able to find class for System.Collections.ArrayList.'mscorlib'.
I understand that for some of the dotnet variable like xml's I have alternate option in AL but still not all of them are available to use in AL.

**Comment by atoader** [comment]
Hi @rishiaurrishabh  ! In the FAQ : https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#dotnet-types-are-not-available-in-extensions-v2-what-now . Right now, we do not support .NET interop.

**Comment by atoader** [comment]
In the following weeks we will provide an update on this topic.
