### ISSUE TITLE
INIT doesn't work when using WITH for a record variable.

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#2467]
When I Try to use INIT function on for a record variable using 'WITH' then AL gives an error on as 
	
"message": "The call is ambiguous between the following methods or properties: 'Init()' and 'Init()'"

Code snippet :   
with TempEmailItem do begin
   Init();
end;

**Comment by atoader** [comment]
Hi @rishiaurrishabh ! Could you please attach a minimal set of AL code dthat causes the issue?

**Comment by Gallimathias** [comment]
@rishiaurrishabh
It would be nice if you didn't just only use  the title of the Issues. This is a very bad style and is not seen well in the github community ^^.

The title of an issue should be short and meaningful. The explanation and details come then in the description. ;)

**Comment by atoader** [comment]
Hi @rishiaurrishabh ! This is by design. You need to qualify the Init procedure with the instance name.
