### ISSUE TITLE
WebPageViewer AddIn bug

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#247]
We are working on Extensions 2.0 and want to use the standard WebPageViewer Add-In (also available on page 9980)

If we use the url "https://en.wikipedia.org/", it works
If we use the url "https://www.boltrics.nl/", it does not works

What are the requirements of the WebPageViewer URL's or the web-page-content?

![image](https://cloud.githubusercontent.com/assets/28626283/26626219/d8db76c8-45f6-11e7-84fa-9f80abd3cd30.png)

![image](https://cloud.githubusercontent.com/assets/28626283/26625730/4b3ded42-45f5-11e7-84c8-6164f2ee28be.png)

**Comment by StanislawStempin** [comment]
Add-ins are not yet available in Extensions v2. 
We passed on your question about the URL issues to the owning team and will update this thread once we hear more.

**Comment by StanislawStempin** [comment]
There are two requirements that we have are:
-	The site must be served over HTTPS
-	The site must allow the content to be embedded within an iframe
The actual rendering is done by IE, so any connectivity errors you see (like the one in the screenshot) should reproduce in IE also.
