### ISSUE TITLE
Sales Line AutoReserve

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#2470]
In the function AutoReserve on Sales Line we have changed the function:
```
[External] AutoReserve()
TESTFIELD(Type,Type::Item);
TESTFIELD("No.");

ReserveSalesLine.ReservQuantity(Rec,QtyToReserve,QtyToReserveBase);
IF QtyToReserveBase <> 0 THEN BEGIN
  ReservMgt.SetSalesLine(Rec);
  TESTFIELD("Shipment Date");
  ReservMgt.f_SkipReservFromPurchase(TRUE); // TFS4920 no AutoReserve for purchase
  ReservMgt.AutoReserve(FullAutoReservation,'',"Shipment Date",QtyToReserve,QtyToReserveBase);
  FIND;
// TFS4920 start
// TFS4920 no manual reservation needed
//   IF NOT FullAutoReservation THEN BEGIN
//     COMMIT;
//     IF CONFIRM(Text011,TRUE) THEN BEGIN
//       ShowReservation;
//       FIND;
//     END;
//   END;
// TFS4920 stop
END;
```

Part 1 is the addition of an extra function `f_SkipReservFromPurchase` that sets a global variable on the COD 99000845 Reservation Management.
This global variable is used in the function `AutoReservePurchLine` of Reservation Management, in order to let us exit that function.
```
LOCAL AutoReservePurchLine(ReservSummEntryNo : Integer;VAR RemainingQtyToReserve : Decimal;VAR RemainingQtyToReserveBase : Decimal;Description : Text[50];AvailabilityDate : Date;Search : Text[1];NextStep : Integer)
// TFS4920 start
IF gblnSkipReservFromPurchase THEN
  EXIT;
// TFS4920 stop
...
```
We do want to have all other parts working of the `AutoReserve `on COD 99000845 Reservation Management.
To have the same functionality in events, we would need an event before the `IF QtyToReserveBase <> 0 THEN BEGIN` on the `AutoReserve` function to set a global variable in a singleinstance codeunit and an event at the start of AutoReservePurchLine in COD 99000845 Reservation Management that allows us to skip that entire function (by the Handled-pattern).

-----
Part 2 is the skipping of the `ShowReservation `function in `AutoReserve `on Sales Line.
We would need an event that checks against the Handled pattern, or an event at the end of `AutoReserve` in COD 99000845 Reservation Management that allows us to change FullAutoReservation (with having knowledge of the context from where `AutoReserve` is called).

**Comment by AlexanderYakunin** [comment]
That looks pretty complex, should we have setup parameter to skip auto reservation instead?

**Comment by SirBETE** [comment]
No, we want to have the autoreservation working except not for purchase lines.

In C/AL doing these modifications was easy, except the search of where to skip the purchase line autoreservation function.
But now, to have the same functionality in Al with extensions is near impossible (specially cause there aren't any events ...).

**Comment by SirBETE** [comment]
A setup parameter to skip manual reservation would be nice.

**Comment by SirBETE** [comment]
How has this been solved?
