### ISSUE TITLE
How can I create a group Folder for Menusuite using AL Extension

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#2474]
How can I create a group Folder for Menusuite using AL Extension, ex- I want to put my "Customized Master" Page under a custom group like "My Config. Master", I am aware of UsageCategory but not sure if we can use the same here.

**Comment by Gallimathias** [comment]
@rishiaurrishabh
Please don't write your whole message in the title, it's really ugly and looks a little disrespectful to the other users. That's about like when you advertise your own stream on other Twitch chat. You just don't do that.

Titles should be short and meaningful, so you can find them again. The explanation and details come then in the description. ;)

**Comment by rishiaurrishabh** [comment]
Hope it is ok now . :)

**Comment by kalberes** [comment]
V2 extensions do not support menu suites. The usage category just serves just as a UI hint for your page in the web client
