### ISSUE TITLE
Syncronize destructive tables changes when developing.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#2475]
Hi there. 

A question. I'm aware that destructive table changes will not be allowed in 365, however when developing you might want to remove a field, or change it's type. Are there no way to do a sync similiar to force from VS code? 

Is recreate the only syncmode that will work? 

Previously as i recall you you just do an upgrade codeunit invoking NavApp.RestoreArchiveData for your tables and you would be fine. I might remember wrong, it does not seem to work anymore however.

**Comment by thpeder** [comment]
HI @NicolaiEsbensen,
please have a look at #1499

**Comment by NicolaiEsbensen** [comment]
@thpeder seems to answer my question, not the answer i was hoping for however :)
