### ISSUE TITLE
Data Migration from NAV to Business Central

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2476]
[https://docs.microsoft.com/en-us/dynamics365/business-central/across-import-data-configuration-packages](url)

My question relates to a customer switching to the new Business Central solution. A customer wants to switch from his Azure Cloud NAV database to the new version Business Central but wants to take all his data with him. What is a scenario for migrating the data in the future? Is there a connector for such a change? Will there be a data migration tool from Microsoft?

**Comment by jenolson** [comment]
This is something we are currently working on in the development team so customers will have a path for migration.  Stay tuned to get more details around this process as we are still defining exactly how we will be able to migrate those customers' data!

thanks
Jennifer Ranz
Senior Program Manager
Microsoft Dynamics SMB R&D

**Comment by ThorstenEngelsGOB** [comment]
Hello Jennifer, thank you very much for the quick answer to my question. Can you give me an estimated time when further information on this topic will be provided and on which channel I will receive these messages?
Kind regards
Thorsten

**Comment by jenolson** [comment]
Thorsten,

Since we are in the beginning stages of research it is hard to put an estimated date, as we get further along we will definitely share this information within the business central webpage.

thanks
Jen

**Comment by ThorstenEngelsGOB** [comment]
Hi Jen,
thanks for telling me. Could you please give me a link where these messages might be published? As you probably know, there are countless websites where Microsoft stores its information. It is difficult to keep track as a hunter-gatherer. And we all want to be successful at hunting.....    ;O)
kind regards
Thorsten

**Comment by rstefanetti** [comment]
Hi, any news about this topic ? "Data Migration from NAV to Business Central"
is it possible to use only rapid start services today ?
new data migration tools will be released in the BC release of October \ November?

Thanks !

**Comment by rstefanetti** [comment]
Great news Jennifer !
I have several customers asking when the migration tools will be available.
Will it be possible to migrate only from NAV 2018 or even from older versions?

Thanks

**Comment by pierreLouise** [comment]
Jennifer,

In order to avoid me to spend more time on develop a extension for migration, can to you indicate us towards what solutions they work?

What is what they turn towards: 
1/SQL Backup/Restore (but how manage development specific)?
2/Application Backup/Restore (as the former format FBK, but how to manage development specific)?
3/Rapidstart with an option booked for the partners for the sensitive tables.
4/an Extension for BC and a FOB for Nav who consumes Web services and API BC (with access to sources to adapt the specific dev)?

Another way ?

Many thanks.

**Comment by Aastha2121** [comment]
“Thanks Jennifer
So as of now can I assume that Process is not clear for Data Migration to Business Central from NAV atleast for now but it will be clear is future. Is it right statement to assume ?”

**Comment by rstefanetti** [comment]
hi, 
a tool is in development, take a look here: "Extension for Data Migration (Import from NAV)"
https://experience.dynamics.com/insider/public-profile/ideas/dynamics-financials/ID0003487

**Comment by SUD-D365** [comment]
Hi @rstefanetti and @jenolson ,

Can anybody help me on this issue #3710 ?

Thanks
