### ISSUE TITLE
Test Codeunit: PTE0007: Assertion function 'AssertError' must not be invoked.

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/AL#2478]
Using the AssertError function in an AL test codeunit results in the following error: 
PTE0007: Assertion function 'AssertError' must not be invoked.

PTE0007 says: Test assertion functions are not allowed in a non-test context.
So it looks like codeunits with SubType = Test are not recognized as a test context.

DockerImage: bcinsider.azurecr.io/bcsandbox-master:13.0.22070.0-nl
AL Lanuage: 0.15.14407

**Comment by atoader** [comment]
Hi, @richardrobberse! You are right, this looks like a bug, but I need to investigate. Are you building a Per Tenant Extension? From what I know, these extensions should not contain tests.

**Comment by atoader** [comment]
I think the fastest way around this is to disable the "${PerTenantExtensionCop}" for your test extension. That doesn't need to respect the rules of the analyzer.

**Comment by atoader** [comment]
As far as I can see, this issue has been fixed in the latest version of the AL extension.

**Comment by atoader** [comment]
You're welcome :) ! Please close the issue if it works or let me know if it doesn't.

**Comment by richardrobberse** [comment]
It worked :)
Can you add the tags so that it's clear it will be fixed in a future release, this will help other people facing the same thing.
