### ISSUE TITLE
Event Request Table 37 Sales Line

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2479]
Missing Publisher in function ValidateReturnReasonCode ==> OnAfterValidateReturnReasonCode(CallingFieldNo,Rec)

**Comment by anuj-inecta** [comment]
Another Publisher is missing in "Sales Line" function SetDefaultQuantity == >
OnAfterSetDefaultQuantity(Rec,xRec);
Similer Event is available in "Purchase Line" in function SetDefaultQuantity.
Please add this as well.

![image](https://user-images.githubusercontent.com/40057282/41151359-280bab3e-6b2e-11e8-972b-af7fd9ef1617.png)

**Comment by ThorstenEngelsGOB** [comment]
@anuj-inecta Please enter your feedback in a separate issue. Otherwise your event requests will not be considered

**Comment by anuj-inecta** [comment]
@ThorstenEngelsGOB - Ok, thanks .. i'll create a separate request.
