### ISSUE TITLE
Windows authorization fails during app publishing 

### ISSUE THREAD

**Issue by djole1391** [Microsoft/AL#2480]
Hi,

I was able to publish app so far (with some run-time 5 minutes limitation problems), but now that I have installed latest build and latest AL extensions I have authorization problem:

![image](https://user-images.githubusercontent.com/12559226/41028649-2ec1e3ea-697a-11e8-9114-f0307599c349.png)

I will try PS script as a workaround, but any info if this is a known issues or when it will be fixes is appreciated. 

Thanks

**Comment by atoader** [comment]
Can you clear your credentials and try again? There is a VSCode command `AL: Clear credentials cache` that you can use for this purpose.

**Comment by djole1391** [comment]
I tried this but it didn't work. 

I forgot to mention that I use Windows authentication. 

I was able to publish and install my extension using PS Script. Didn't have any issues with authentication there...

**Comment by dennisfrostlander** [comment]
Hi @djole1391,
Are you running in a multi-tenant environment? 
If so, this issue was already fixed a couple of days ago (in extension build 0.17.23263)
