### ISSUE TITLE
Handling XmlPorts similar to pages and reports in Test codeunits

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#2481]
Hi,

When we are trying to create handlers for xmlports similar to page we cannot find the **_xmlporthandler_** attribute and **_testxmlport_** datatype.

Can you please suggest how can we handle this?

Thanks & regards
Varun Reddy

**Comment by bachii1010** [comment]
@atoader  we have a xmlport and we are using that to import data so we are writing an automate test codeunit for this process and here we have to invoke the xmlport to test it automatically which is not possible now due to the above missing datatypes and attributes.

Can you please suggest how to accomplish this?

**Comment by StanislawStempin** [comment]
I don't think that's currently possible apart from running with RequestWindow = false. 
We will need to add support for TestXmlPort and a handler for the XmlPort Request Page.

**Comment by Joerio** [comment]
Any progress on this? Still can't handle the XmlPort RequestPage, the requestpagehandler still only supports a requestpage for a report.

**Comment by atoader** [comment]
Hi! We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, I recommend that you post this on our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.

**Comment by Joerio** [comment]
Why is this closed? This is related to the AL development tools. It's missing any helper functions to actually test a XmlPort. 
You immediately get an exception that you don't handle the UI Requestpage, but you don't have any actual tools to handle this.
Or is testing xmlports just not supported in the AL test tools?
