### ISSUE TITLE
Is table extension also consume licensed table ids 

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#2482]
Assume if client have 50 table license and all they have occupied with the new custom tables in the series of 50000 ..now almost 30 base table there is new field addition or custom code written for that table extension will create.
So how the licensed ids will behave in this scenario is there need to procure more 30 more table licenses?

AL Version- 1.22.1
NAV - 2018 on Prem

**Comment by Deepakalle123** [comment]
Hi @StanislawStempin  Any update on this.

**Comment by StanislawStempin** [comment]
Extension objects can use the same IDs as tables. 
So you can use ID for example 50100 both for a new table and for a table extension of the base.
