### ISSUE TITLE
Addafter action with default name is not possible if same default name exists on multiple actions

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#2485]
Was trying to find if already reported, but no luck. I was trying to extend "Order Processor Role Center", but I cannot add action e.g. after Action "\<Page Customer List\>". All actions with default name are listed under the Caption string, but in this case, there are two Actions with default name "\<Page Customer List\>" having same caption "Customers". ALC will automatically use the first one (ID 26), but I need to place it after second one, with id 61. Main problem is the duplicity if no ID is used to identify the action.

**Comment by atoader** [comment]
Hi @kine ! We should be generating a name for the second action that doesn't conflict with any other action name. Could you check if you have any action with Action{ActionId} ?

**Comment by kine** [comment]
Ah, Ok, now I have found the control. It is as Action61. Didn't know that in this case it will generate such a control name. I will expect e.g. "Page Customer List 61" or "Customers (61)" or something like that to easily find the action and make it unique.

**Comment by StanislawStempin** [comment]
We will not do any further tooling changes in the area of default name generation. The individual naming issues will be addressed by the application going forward.
