### ISSUE TITLE
Event Request in Table 5407 Prod. order Component

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2488]
Missing Publisher in function ProdOrderNeeds

We need a publisher at the beginning of the function with the option of abort by a Handled variable.
The reason for this is that you want to influence the calculation of the variable ProdOrderNeeds. 
In my case it would be possible to calculate the quantity component independent. 

The abort should take place after the date fields have been updated.

**Comment by AlexanderYakunin** [comment]
Can you please provide code suggestion?

**Comment by ThorstenEngelsGOB** [comment]
LOCAL ProdOrderNeeds() : Decimal
ProdOrderLine.GET(Status,"Prod. Order No.","Prod. Order Line No.");

"Due Date" := ProdOrderLine."Starting Date";
"Due Time" := ProdOrderLine."Starting Time";
UpdateDatetime;


**// S/ERP11.01**

//****Publisher like e.g.
OnBeforeCalculateProdOrderNeeds(rec,VAR ProdOrderNeedQty,handled);

IF handled THEN
  EXIT(ProdOrderNeedQty);

// actual Code in ERP Solution
IF "Component Qty Lot Size independend" THEN
  EXIT(1 or whatever...);
**// E/ERP11.01**

ProdOrderRtngLine.RESET;
ProdOrderRtngLine.SETRANGE(Status,Status);
ProdOrderRtngLine.SETRANGE("Prod. Order No.","Prod. Order No.");
ProdOrderRtngLine.SETRANGE("Routing Reference No.",ProdOrderLine."Routing Reference No.");
IF "Routing Link Code" <> '' THEN
  ProdOrderRtngLine.SETRANGE("Routing Link Code","Routing Link Code");
IF ProdOrderRtngLine.FINDFIRST THEN
  EXIT(
    ProdOrderLine.Quantity *
    (1 + ProdOrderLine."Scrap %" / 100) *
    (1 + ProdOrderRtngLine."Scrap Factor % (Accumulated)") *
    (1 + "Scrap %" / 100) +
    ProdOrderRtngLine."Fixed Scrap Qty. (Accum.)");

EXIT(
  ProdOrderLine.Quantity *
  (1 + ProdOrderLine."Scrap %" / 100) * (1 + "Scrap %" / 100));
