### ISSUE TITLE
Container spin-up fails: "The Windows account could not be mapped to a valid security identifier (SID)."

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#2489]
I'm using image bcinsider.azurecr.io/bcsandbox-master:de, NAV Version: 13.0.22490.0-DE

This image behaves differently than the older ones we had up to now, here the only user who is accepted to spin-up a container is the system administrator himself.

For all 'normal' users (which are fit to be used for this purpose e.g. with the version 12 public sandboxes like build 21229) , the local spin-up of a new container fails with the error message in the title.
In Detail
> Setting SA Password and enabling SA
WARNING: This license is not compatible with this version of Dynamics NAV.
Creating SUPER user
The Windows account could not be mapped to a valid security identifier (SID).
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 158
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container bc1234 failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.7.5\ContainerHandling\Wait-NavContainerReady.ps1:40 Zeichen:17
throw "Initialization of container $containerName failed" ...
CategoryInfo          : OperationStopped: (Initialization ...bc1234 failed:String) [], RuntimeException
FullyQualifiedErrorId : Initialization of container bc1234 failed

If I type  
`wmic useraccount get name,sid`
into the command prompt I can see the SIDs of all users , but what has to be mapped here?

For the above licence warning we are currently getting see #2354.

**Comment by Kowa63** [comment]
I've tried that once more, but this time with 12.2.22539.0-DE out of current image pulled bcinsider.azurecr.io/bcsandbox:de, but here also the same SID error message comes up. Only the incompatible licence warning does not show up any more since it is version 12.

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
