### ISSUE TITLE
Why is Record."Modify" quoted?

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#249]
Intellisense suggests that Modify should be quoted:

![image](https://cloud.githubusercontent.com/assets/1166791/26629962/ec76fce4-4604-11e7-855f-6c37d8f513f2.png)

This is only seems to be the case for Modify and not for Insert, Delete, Rename:

![image](https://cloud.githubusercontent.com/assets/1166791/26629997/18971ac0-4605-11e7-87e5-2f89e1e21f60.png)

I would prefer not having the quotes.

**Comment by esbenk** [comment]
It is a bug. Modify() is a keyword in the context of page/table extensions metadata, but not in AL code.
