### ISSUE TITLE
[Suggestion] XML port ignore header

### ISSUE THREAD

**Issue by ln1000000** [Microsoft/AL#2491]
Hello,

It would be nice to have an XMLPort feature enhancement that allows a property (or otherwise) to be defined that tells the XMLPort to ignore field headers in CSV files.
I.E. FirstLineHasHeaders=true; or IgnoreHeader=true;

If there is a roundabout way to accomplish this, please let me know.

**Comment by srenders** [comment]
currXMLPort.SKIP ;-)

**Comment by ln1000000** [comment]
Works like a charm thanks!
