### ISSUE TITLE
Wrong vsix is included in CU6

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#2492]
I think this was fixed, but now it's not working again.
Al Language 12.17091

When I run Format Document on a repeat until loop, only the first line is indented.
Similar to closed issue #1895

![image](https://user-images.githubusercontent.com/7827702/41063953-f66598d8-698e-11e8-942a-39a56e3b4b24.png)

I also see case statement formatting is bad:
![image](https://user-images.githubusercontent.com/7827702/41064236-d7caba4c-698f-11e8-8976-bf887dc93668.png)

**Comment by atoader** [comment]
Hi @reiniroosh ! You are right, this has been fixed in more recent releases of the extension, but we have not backported it. If you consider this is important enough to be backported, please request it through the standard support channels.

**Comment by reiniroosh** [comment]
Oh, yes, I think you might be right...
But I got this vsix out of the container for CU6. So maybe the wrong vsix is in the container?

**Comment by reiniroosh** [comment]
I wanted to use a new vsix, since there's some issues in the development that I was hoping was resolved. (False positive code cop warnings about text overflows are spamming, for example.)

However I couldn't find the new vsix?
![image](https://user-images.githubusercontent.com/7827702/41119965-0e8d5760-6a49-11e8-9d34-68cafa24b4d3.png)
I installed this vsix from Temp1_**CU 06** NAV 2018 NA.zip\NAV.11.0.22292.NA.DVD.zip\ModernDev\program files\Microsoft Dynamics NAV\110\Modern Development Environment

It's a bit hard to know, since:
1. there's no library of vsix (see #1916)
2. the change log isn't maintained, and the version nos. confuse me - it's hard to tell what version I'm even on
3. things are randomly not working without any clear cause or documentation (Format Document, crashing VS Code)
4. the vsix files included in the install is the wrong one..

Overall, I have to admit that this ended up kind of just a waste of my time, and it's a bit of a minefield.

Is this really necessary?

There's lot of ways you could, in the interim before you have some official solution, provide an archive of the vsix files. One idea would be to just check them into the AL repository here.

**Comment by reiniroosh** [comment]
Yes, I understand about the KB articles. What I mean is that the change log in the vsix says "December" so it's hard to tell from the installed vsix what should or shouldn't be working. (especially combined with the version reset you can see how that would be confusing)

I think it's the wrong one, because you said it got fixed. But I got it out of CU6. So either there's a bug, or it's an old vsix. 
I'll leave it up to you to determine which it is. :)

Maybe you could have a "kitchen sink" type of al file that you run Format Document on.
Then if the file changes it would indicate there might be some regressions.

**Comment by atoader** [comment]
Hi @reiniroosh ! By "it is fixed", I meant that is fixed in master, the master from which we will ship the next major release. Fixes do not get backported by default to NAV 2018 i.e. they do not get included in CUs. Please read https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do .  Please also read this https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ to understand better our release/fix policy. You are right that we do not mention bug fixes in the release log. We considered that the KB articles should be sufficient, but we will take your feedback into consideration and try to offer more information in the following CUs.

**Comment by reiniroosh** [comment]
Thank you @atoader 

What I meant is that from VS Code, it's hard to know what version of the vsix I am using.
It has a version no., but of course that doesn't mean anything to me.
It has a change log, but it's not maintained. (By maintained, I mean even just something like "vsix from CUX, link to kb article here" would be a good indicator.)

Yeah, I think it's critical that Format Document works properly.
1. It's a bit of change to a new style for us C/AL developers, so this is a really great feature and a big time saver. It teaches newbies how to write the code properly. Even just in general it's a big time saver.
2. When Format Document starts changing parts of the file that are not involved in the development, it creates a lot of noise during reviews, and potential for merge conflicts.
3. We use Format Document as an arbiter of style. Basically we say let's just go with whatever the automated standard is.

If you have not already considered it already, I would suggest you set up a test with a "kitchen sink" type of AL file that has all the various elements (tables, pages, flowfields, repeat...until, case statements, etc.) with all the proper style.
You run Format Document against it when you release new vsix versions. That will give you a quick and data based way to identify potential bugs or regressions, if the file ends up changing unexpectedly.
