### ISSUE TITLE
Suggest object id creates duplicates in vsix CU5 + CU6

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#2493]
When I suggest the id of a codeunit using Ctrl+Space in CU5 and 6 it suggests an id that's already been used.

**Comment by qutreson** [comment]
Hi @reiniroosh, this looks like a bug. I have a few question to understand how it reproduces: After using IntelliSense, do you get a diagnostic for duplicate id in VS Code or do you get an error from the server when trying to publish your extension? If the error happens in VS Code, do you have any other dependencies on other extensions which may use this id?

**Comment by reiniroosh** [comment]
It's happening as a "problem" which I think is VS Code compiling the code as it watches for changes.
It's the duplicate of another file in my own extension.

However I think we can close the issue... I think I was accidentally using an old vsix.
