### ISSUE TITLE
'Record "Excel Buffer"' does not contain a definition for 'SelectSheetsNameStream'

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#2496]
Hi,

Connectiong to Business Central Sandbox I get this error, no compile error when building the extensions only when publishing to api.businesscentral.dynamics.com

2018-06-07 10:13:07.18] Authenticating...

[2018-06-07 10:13:07.66] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize

[2018-06-07 10:13:20.82] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed

Src/report/Rep80400.SCBImportSetupEntryExcel.al(44,51): error AL0132: 'Record "Excel Buffer"' does not contain a definition for 'SelectSheetsNameStream'

Src/report/Rep80400.SCBImportSetupEntryExcel.al(61,51): error AL0132: 'Record "Excel Buffer"' does not contain a definition for 'SelectSheetsNameStream'

I was told that 'SelectSheetsNameStream was availble in business central.

I did the same test on docker image bcinsider.azurecr.io/bcsandbox-master:dk 
but newer build which I´m able to publish with no error.

I´m stuck here in my customer extension, so when will the api.businesscentral.dynamics.com be updated.

**Comment by JesperSchulz** [comment]
The SelectSheetsNameStream function was added to main branch of Business Central and is hence available and visible in developer previews. The function is, however, not available in production yet, as the code change wasn't backported to be included in a minor release. For the full picture, please refer to https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/. As things are now, the function will ship with the next major release in the fall. Based on this issue I assume you would like that to happen earlier and I'll hence backport the fix right away. Release will not be before a couple of months though anyway, I'm afraid.
