### ISSUE TITLE
Can we have ApplyRelationshipFilters Function of CU 1501 as Public and External ?

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#2498]
I am trying to build some generic config. functionality for which I would like to save relation between two different, I have noticed that standard NAV has a function in COD : 1501 as ApplyRelationshipFilters which can be used in this purpose as well, as it has only two parameters for Source and related RecordRef. Can we have this Function as non Local and External ?

**Comment by grobyns** [comment]
Hi,

we don't change a local to global and external unless there is a very good reason for it. As it does not sound like you need this to extend WF functionality but rather as a helper to a new feature I suggest you copy the code into your extension instead. 

Cheers,
Gert
