### ISSUE TITLE
"Reference to object ... is ambiguous" error when creating a tableextension with dependencies

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#250]
Create two simple extensions: ExtA and ExtB. ExtA declares one simple table object. ExtB declares ExtA as its dependency inside ExtB app.json manifest file.

Then, within ExtB, try doing this:

tableextension 74007042 "Item Extension" extends Customer
{

}

Even with symbols downloaded, it will underline "Customer" and show error tooltip: "Reference to object Customer is ambigious..."

This is an excerpt from ExtB manifest dependency declaration:

  "dependencies": [
    {
      "appId": "f27ae0de-bad1-475d-a3d1-f9b68c5d5397",
      "name": "Extension A",
      "publisher": "Cloud Ready Software GmbH",
      "version": "1.0.0.0"
    }
  ]

When you change the "dependencies" property to remove the dependency declaration, like this:

  "dependencies": [
  ]

... everything just starts working, and the tableextension object does not complain about Customer being ambiguous.

Example project (zipped, for some reason I can't attach it here): https://www.dropbox.com/s/4kr76vxm5ww2hvj/ExampleWorkspaces.zip?dl=0

**Comment by StanislawStempin** [comment]
This is fixed as part of #184
