### ISSUE TITLE
Extending standard CRM type table

### ISSUE THREAD

**Issue by Linas-Tisski** [microsoft/AL#2508]
Hello,

  We're working on the integration implementation between Busincess Central and Dynamics Sales. One of the requirements is to integrate custom CRM sales order field with Business Central. When we try to extend BC "_CRM_" table type table "CRM Salesorder", we get the following error message: **"[AL] The Table "CRM Salesorder" of type CRM cannot be extended. Table "CRM Salesorder""** 

The sample code we're using: 
```
tableextension 60013 CRMSalesOrderExt extends "CRM Salesorder"
{
    fields
    {
        // Add changes to table fields here
    }
    
    var
        myInt: Integer;
}

```
AL extension version no.: 0.15.18771

Thanks,

**Comment by qutreson** [comment]
It is currently not possible to extend CRM table as it is not supported by the server and the compiler. This is something we are considering for the future, but we don't have any time estimation for it. We will use this issue for tracking the extendability of CRM tables and keep you updated.

**Comment by jigneshdhandhanav** [comment]
I would like to extend CRM Account Table. I would like to add new custom field in CRM Account Table.

Is there any update ? Can we do that currently ?

**Comment by charlespockert** [comment]
@jigneshdhandhanav see https://github.com/Microsoft/AL/issues/3844#issuecomment-458592525

It's not ideal as it's not configurable, but it works - you could probably make this configurable by adding the right front-end and configuration tables as an extension. It's something that I've not done yet due to time constraints.

**Comment by svwfr** [comment]
I read from MS Docs that BC support creating new D365forSales tables. 
Could it be a work-around to create a table: CRMAccount2, and only add the new customized fields to that new table?? How would the mapping logic work for syncronize account to customer table, when the account-data is divided into two tables?
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-integrating-dynamics-365-for-sales-extension-development

**Comment by kalberes** [comment]
Please check  if the new integration answers your questions;
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration
