### ISSUE TITLE
How to change the return value of function used as parameter of another function?

### ISSUE THREAD

**Issue by VMashevBG** [Microsoft/AL#2509]
I have problem with function GetPostingNoSeriesCode in “Sales Header”. It is used as parameter in other functions in OnValidate and OnLookup triggers of “Posting No. Series” field. 
I create a new field “Posted Sales Protocols Nos.” and if the document is “Sales Protocol” I want to use it for functions NoSeriesMgt.TestSeries and NoSeriesMgt.LookupSeries. The problem is that the function GetPostingNoSeriesCode is used directly as a parameter and I can’t use any Event before or after the function to change the value it returns. 

Maybe I will face this case not only here and it is good to know if there is workaround for this.

![image](https://user-images.githubusercontent.com/40030550/41104495-2aa60af2-6a74-11e8-96e6-5671d789b0bf.png)

![image](https://user-images.githubusercontent.com/40030550/41104513-362563fa-6a74-11e8-96fa-f735ed741ddd.png)

**Comment by atoader** [comment]
Just to clear things up: the function is not used as a parameter, the value returned by the function invocation is used as an argument for the two other procedures.
Do you have any suggestion for a better, more extensible design? Please tell us what events you need and or how you think this should be better designed to suit your scenario. 
I am asking this because I think that your scenario might be a bit more complex that what you've presented so far. I would suggest that you perform any code modifications necessary to make your scenario work and the propose the changes here so that they can be implemented in the application.

**Comment by VMashevBG** [comment]
Thank you for the clarification of this case. 
What I do is to extend the Sales Setup table with one new field: Posted Sales Protocol Nos.. and I want GetPostingNoSeriesCode procedure to return this no. series if the document is set as Sales Protocol.

My suggestion is to rewrite the code of the procedure GetPostingNoSeriesCode and add Event OnAfterGetPostingNoSeriesCode(VAR SalesHeader, VAR PostedNos): 

    LOCAL PROCEDURE GetPostingNoSeriesCode() : Code[20];
    VAR
      PostedNos@46000001 : Code[20];
    BEGIN
      IF IsCreditDocType THEN
        PostedNos := SalesSetup."Posted Credit Memo Nos."
      ELSE
        PostedNos := SalesSetup."Posted Invoice Nos.";

      OnAfterGetPostingNoSeriesCode(Rec , PostedNos);

      EXIT(PostedNos);
    END;

      [Integration]
    LOCAL PROCEDURE OnAfterGetPostingNoSeriesCode@46000002(VAR SalesHeader@46000001 : Record 36;VAR PostingNos@46000000 : Code[20]);
    BEGIN
    END;

    BEGIN
    END.

**Comment by grobyns** [comment]
Hi,

How are you defining that a Sales Header is a "Sales Protocol"?

br/Gert

**Comment by VMashevBG** [comment]
Hi, 

I create a new field Sales Protocol in Sales Header and I have a new page filtered by this field.

**Comment by grobyns** [comment]
Hi,

Thanks, I understand the issue. I'll have a look to see how best to solve the problem.

br/Gert

**Comment by grobyns** [comment]
Hi,

Can you try if this workaround will work for you?

You will have to add a relationship between the No. Series so that the Posted Invoice Nos. and Posted Credit Memo Nos. series have a relationship to your new Posted Sales Protocols Nos. series.

Then, in the OnValidate trigger of Sales Protocol add this code:

                trigger OnValidate()
                var
                    SalesSetup : record "Sales & Receivables Setup";
                    NoSeriesMgt : Codeunit NoSeriesManagement;
                begin
                    SalesSetup.Get;
                    if "Sales Protocol" then
                      VALIDATE("Posting No. Series",SalesSetup."Posted Sales Protocols Nos.")
                    else
                      NoSeriesMgt.SetDefaultSeries("Posting No. Series",SalesSetup."Posted Invoice Nos.");
                end;             

You will also need to add two subscribers in a codeunit because the Posting No. Series gets reset when validating the customer.


    [EventSubscriber(ObjectType::Table, DATABASE::"Sales Header", 'OnAfterInitNoSeries', '', false, false)]
    local procedure SetPostedSalesProtocolNosOnAfterInitNoSeries(var SalesHeader: Record "Sales Header")
    var
        SalesSetup : record "Sales & Receivables Setup";
    begin
        if SalesHeader."Sales Protocol" then begin
            SalesSetup.Get;
            SalesHeader.VALIDATE("Posting No. Series",SalesSetup."Posted Sales Protocols Nos.")
        end;
    end;

    [EventSubscriber(ObjectType::Table, DATABASE::"Sales Header", 'OnAfterInitRecord', '', false, false)]
    local procedure SetPostedSalesProtocolNosOnAfterInitRecord(var SalesHeader: Record "Sales Header")
    var
        SalesSetup : record "Sales & Receivables Setup";
    begin
        if SalesHeader."Sales Protocol" then begin
            SalesSetup.Get;
            SalesHeader.VALIDATE("Posting No. Series",SalesSetup."Posted Sales Protocols Nos.")
        end;
    end;

this should fix your issue but of course, you'll need to test to see if there are other places the Posting No. Series gets reset.

br/Gert

**Comment by VMashevBG** [comment]
Hi Gert, and thank you for your suggestion. 
I will try this scenario and give you feedback if it is working in my case.

**Comment by grobyns** [comment]
Closing this thread. Please let us know if you have issues with the workaround.

**Comment by Bhawan-Bhangu** [comment]
Hi Developers, I have created a new field in "Sales & Receivables Setup" table using Visual Studio code. But when a try to use this field in my other table for using "No. Series", this field id not accessible to me. In definition of "Sales & Receivables Setup" table inside Visual Studio Code, I'm not able to see this field but inside my sandbox I can see that this field is created. 
Here is my code to create new field in this table

tableextension 50125 "Sales Ext" extends "Sales & Receivables Setup"
{
    fields
    {
        field(50126;"WebUser Nos.";Code[30])
        {
            TableRelation="No. Series";
            Enabled=true;
        }
    }
}
Any changes required to make this field named "WebUser Nos." accessible inside Visual studio code for using inside another table?

**Comment by StanislawStempin** [comment]
What is the code that fails for you when you say "this field is not accessible to me".

**Comment by Bhawan-Bhangu** [comment]
Hi Stainslaw Thanks for replying 
Here is my code to create new table and use that created field



fields
    {
        field(1;"No."; Code[20] )
        {
            
        trigger OnValidate()
        var SalesSetup: Record "Sales & Receivables Setup";
        NoSeriesMgt: Codeunit NoSeriesManagement;
          BEGIN
           IF "No." <> xRec."No." THEN BEGIN
              SalesSetup.GET;
              NoSeriesMgt.TestManual(SalesSetup."<<<<ERRrrorrrr>>>>");
             "No. Series" := '';
          
           END;
            end;
        }

**Comment by StanislawStempin** [comment]
Is that AL code in the same extension as the newly added table extension field? If not, you need to make sure there is a dependency declared between the extensions in app.json "dependnecies" element

**Comment by Bhawan-Bhangu** [comment]
Thanks a lot Stainslaw. It's working for me. Cheers.
