### ISSUE TITLE
Trigger OnAssistEdit doesn't show Assist button

### ISSUE THREAD

**Issue by riki815** [Microsoft/AL#2510]
Like issue #2451 i have the same problem on reports, AL Language 0.12.20065, Cumulative Update 6.

In the example below i used trigger "OnDrillDown" and "OnAssistEdit", the OnDrillDown trigger show the Assist Edit button:

    requestpage
    {
        layout
        {
            area(content)
            {
                group(Options)
                {
                    Caption = 'Options';
                    field(ItemNo;ItemNo)
                    {
                        TableRelation = Item."No.";

                        trigger OnDrillDown();
                        begin
                            Message('OnDrillDown');
                        end;
                    }
                    field(VariantCode;VariantCode)
                    {
                        trigger OnAssistEdit();
                        begin
                            Message('OnAssistEdit');
                        end;
                    }
                }
            }
        }

![cattura](https://user-images.githubusercontent.com/16220695/41111690-055da814-6a7d-11e8-9d98-4efc36839e27.JPG)

**Comment by rishiaurrishabh** [comment]
Hi @riki815 you have to make AssistEdtit as TRUE to make it work , its strange because on Drilldown you don't have to define Drilldown as true

![assistedit](https://user-images.githubusercontent.com/39942971/41148515-ca617cae-6b26-11e8-96df-d89f732584a4.PNG)

**Comment by riki815** [comment]
Hi @rishiaurrishabh, i tried AssistEdtit and it works.

Thanks.
