### ISSUE TITLE
OnAfterPostGLAndCustomer symbol isn't working

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#2511]
There's an event OnAfterPostGLAndCustomer  in CU80 that isn't available in the compiler after downloading the symbols.
The interesting thing is that OnBeforePostGLAndCustomer is working though.

![image](https://user-images.githubusercontent.com/7827702/41125219-a1f93442-6a58-11e8-9c43-941872a8ae35.png)

![image](https://user-images.githubusercontent.com/7827702/41125290-d70f3c94-6a58-11e8-8ff7-19fba73978d4.png)

**Comment by atoader** [comment]
My bad :) Thanks for clarifying @AlexanderYakunin !

**Comment by reiniroosh** [comment]
@StanislawStempin yes. I gave that another try now to confirm, but it persists. Strange huh?

@AlexanderYakunin it is NA.

**Comment by reiniroosh** [comment]
Hello,
I found the problem. I had to `generatesymbolreference` from finsql
