### ISSUE TITLE
OnBefore/OnAfterProcedure events

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#2512]
_I guess this issue had already been discussed, but I can't find it :( 
In case this issue is still open somewhere, please reference it here._

We're looking in refactoring lots of codeunits to support eventing. First of all, historic code has to be rewritten / converted towards functions. Next, the function need to support events, including the handled pattern. One option can be to do this on a case by case basis, using e.g. the [CRS ](https://github.com/CloudReadySoftware/crs-al-language-extension) tcodeunit snippet.

```
codeunit id "Name Meth"
{
    procedure MethodName();
    var
        Handled : Boolean;
    begin
        OnBeforeMethodName(Handled);

        DoMethodName(Handled);

        OnAfterMethodName();
    end;

    local procedure DoMethodName(var Handled: Boolean);
    begin
        if Handled then
            exit;

    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeMethodName(var Handled : Boolean);
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterMethodName();
    begin
    end;
}
```

Another option might be to have this native available in AL. Are there any plans to support some kind of OnBefore / OnAfter procedure events, supporting the Handled pattern and providing access to local / globals?

**Comment by esbenk** [comment]
We have discussed a concept like this, but it is currently not in our plans.
