### ISSUE TITLE
SET CURRENCY CODE ERROR

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2513]
Hello guys, Im deployment a delivery note report (this report has been replicated from the standard Report  208). The standard report include the function SetCurrencyCode and It works fine in C/Side but when I export and import in VS Code it and throws the next error:

> The type or method 'SetCurrencyCode' cannot be used for 'Solution' development. 

Im using in the app.json the label target as solution.

Some idea of this error or a possible solution??
 
Thanks!

**Comment by atoader** [comment]
Hi @alvarotellez ! You should be using either Extension or Internal . Solution should not be used.
