### ISSUE TITLE
Question: RunPageView missing FIELD expression for WHERE

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#2515]
Since I have updated to a newer version of my AL Language extension, I get this error:

[AL] The property expression is not valid. A CONST or FILTER expression is expected.

Where is the FIELD expression or how do I use the filter now?

Here is the code:
```
Action("Beer Category")
{
    // ...
    RunObject = page "My Card";
    RunPageView = order(ascending) where("Code" = field("My Code"));
}
```

```
Microsoft (R) AL Compiler version 0.17.19506
Copyright (C) Microsoft Corporation. All rights reserved
```

**Comment by rishiaurrishabh** [comment]
Hi @megel,
You have to define that in RunPageLink property of page from you want to run this page, on RunPageView you can only definer CONST of FILTER,  
Ex : - RunPageLink = Code=FIELD(Code),"Parent Table ID"=field("Table Id");

**Comment by megel** [comment]
Ahh thanks a lot!
