### ISSUE TITLE
Show file/stream in the preview window

### ISSUE THREAD

**Issue by Chielve** [Microsoft/AL#2517]
Hello,

We have an archive page where we get files from an API that we show in NAV. Now we want to open those files in the same way as you preview a report.

Is it possible to open the preview page with our own files/streams or is this only accesible via running a report?

**Comment by atoader** [comment]
What do you mean by "open those files in the same way as you preview a report" ? Do you mean that you want to use something like a smaller window in which you can preview files?

**Comment by Chielve** [comment]
Yes, by using this window:
![vmplayer_2018-06-07_13-35-18](https://user-images.githubusercontent.com/13106808/41158185-4b072b78-6b28-11e8-9c16-57fd67ce0485.png)

I think it should be possible to create a pdf viewer control add-in. But I want to know if we could use this window?

**Comment by atoader** [comment]
@JesperSchulz what do you think?

**Comment by StanislawStempin** [comment]
This is only accessible via reports. You would need to use a custom control add-in for your scenario.
