### ISSUE TITLE
Suggestion: Add "Event" to Business and Integration decorations

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#252]
The procedure decorations Business and Integration do not in any way indicate that they turn your procedure into a published event. Just by reading the code, you cannot deduct the intent of the code.

I suggest you add the word "Event" (or something similar) to the decorations.

They would then look like this:
```
[BusinessEvent(false)]
local procedure MyProcedure();
begin
end;
```

And:
```
[IntegrationEvent(false,false)]
local procedure MyProcedure();
begin
end;
```

**Comment by StanislawStempin** [comment]
Thanks, that's a good suggestion.
