### ISSUE TITLE
Question: Missing image property on page actions

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2520]
Right now we are not able to modify image property for page actions. What should our approach be in that case? 

We identified some cases where image is missing from base app and we would like to solve that. One example is on deposit page:

![image](https://user-images.githubusercontent.com/20359384/41157299-9e386d32-6b25-11e8-8552-b5ab98b030ff.png)

I am using bcinsider.azurecr.io/bcsandbox-master:ca docker image.

**Comment by atoader** [comment]
I will pass this to the app teams so that they can fix the problem.

**Comment by fvet** [comment]
Could this be implemented in a(n) (optional) rule of the code analysis, to ensure all actions have at least a valid image assigned? Can be interesting to get our extensions validated the same way.

**Comment by grobyns** [comment]
Hi,

thanks for reporting the issue. The fix should be in the next update.

br/Gert
