### ISSUE TITLE
Colour Changing when Style enabled/disabled.

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2521]
In BC, I have an extension where the user can select whether some values are bolded (Strong).  Before they change the option the field displays in the aqua blue like all the other fields on the page.  When the bold option is selected the field displays bolded and black (which is fine) but if the unselect the bold option the field is grey and not the aqua blue it was originally. 

This does NOT happen in the NAV 2018 CU06, Web Client using the SAME AL code (i.e. copy the page from the BC machine and use it on the NAV 2018 machine).

This the field definition.  AmountEmphasis is set by using a checkbox on the page and updated in the OnAfterGetRecord trigger.
```
                field(Period1; Amt[1])
                {
                    BlankNumbers = BlankZero;
                    CaptionClass = Period[1];
                    DrillDown = true;
                    Editable = false;
                    ApplicationArea = Basic;
                    Style = Strong;
                    StyleExpr = AmountEmphasis;
```
Is this a BC issue or an Extension issue in BC?

**Comment by atoader** [comment]
It seems to be a BC issue. I will pass it to the client team.
