### ISSUE TITLE
How to hide Manager Time Sheets action group from Job Manager role Center Page (9015)

### ISSUE THREAD

**Issue by srkkoneti** [Microsoft/AL#2528]
How to hide Manager Time Sheets action group from Job Manager role Center Page (9015).

Please find the below screen shot for reference.

![role center page 9015](https://user-images.githubusercontent.com/39953344/41161824-9775cf8c-6b23-11e8-80d5-6fdad25d19b0.png)

also found another issue on same Role Center (9015). Even after hiding the Self-Service actions (which are standard actions) they are still visible, please find the attached screen shot for your reference.

![image](https://user-images.githubusercontent.com/39953344/41216360-9d0c7112-6d71-11e8-909b-b70c0caf16d3.png)

**Comment by StanislawStempin** [comment]
I have not tested this code but have you tried to just set the Visible to false for that action group?
```
pageextension 50101 ManagerRC extends "Job Project Manager RC"
{
    actions
    {
        modify("Manager Time Sheets")
        {
            Visible = false;
        }
    }
}
```
