### ISSUE TITLE
Intellisense not working inside parentheses after EXIT command

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#253]
When I use the exit command, intellisense doesn't work inside the round brackets.

So, when typing inside the round brackets of exit() intellisense doesn't work.

**Comment by StanislawStempin** [comment]
Intellisense for method call arguments is not fully implemented yet (apart from some built-in methods). It is on our backlog.

**Comment by StanislawStempin** [comment]
This has been implemented at some point. Please log a new issue if there are specific cases that are still not supported.

**Comment by TheDenSter** [comment]
I'm still having this issue in the Feb developer preview (AL Language 0.13.15836), no intellisense inside the exit parentheses
![image](https://user-images.githubusercontent.com/23434319/36338704-4576d22e-1373-11e8-9214-286d4ea8cd47.png)
