### ISSUE TITLE
[Event Request] Codeunit 6501 : OnAfterCreateEntrySummary

### ISSUE THREAD

**Issue by shalamai** [Microsoft/AL#2531]
We need to transfer fields from TrackingSpecification to TempGlobalEntrySummary.

_Codeunit 6501 – Function CreateEntrySummary:_ 
**OnAfterCreateEntrySummary(TrackingSpecification,TempGlobalEntrySummary)** (event at the end of the function)

Thank you!

**Comment by AlexanderYakunin** [comment]
We already have event OnAfterCreateEntrySummary2(TempGlobalEntrySummary,TempReservEntry) in CreateEntrySummary. Seems it solve this problem, can you please recheck if you still need another event here?
