### ISSUE TITLE
[Event Request] Codeunit 99000845: OnAfterInitFilter

### ISSUE THREAD

**Issue by shalamai** [Microsoft/AL#2532]
We need to apply additional filter on CalcItemLedgEntry.“Expiration Date” for specific CalcReservEntry.

_Codeunit 99000845 – Function InitFilter_:
**OnAfterInitFilter(CalcItemLedgEntry, CalcReservEntry, EntryID)** (event at the end of the function)

Thank you!

**Comment by AlexanderYakunin** [comment]
Is this event specific for CalcItemLedgEntry? If so, should it be placed after block of code for CalcItemLedgEntry in CASE statement for 1:?

**Comment by AlexanderYakunin** [comment]
No reply for 10+ days, have to close this ask.
