### ISSUE TITLE
HttpContent.ReadAs should also accept OutStream

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#254]
I would expect to HttpContent.ReadAs be able to store its content into an OutStream. That would make it possible to store the content directly into a BLOB field. Now we have to create an OutStream and call COPYSTREAM to get it into a BLOB.

**Comment by StanislawStempin** [comment]
We will look into this suggestion. It leads to a broader discussion about having simply a Stream type to handle both in and out directions.
