### ISSUE TITLE
Question to the Label: ships-in-future-update

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2542]
I have a question about the Labe ships-in-future-update.
If an event request is submitted and receives the above-mentioned label, in which product do we then receive the event extension? Only in the current release of Business Central 365 or do the updates also find space in the respective published CUs such as NAV2018?
Many of my requests marked with the delivery date April cannot be found in the NAV2018 CU6, for example.
Is there an overview of the way of proceeding?

**Comment by atoader** [comment]
Hi @ThorstenEngelsGOB ! This blog posts covers our release process: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ .
By default, all fixes that are marked with ships-in-future-update, are put into the main branch and will be in the daily docker drops and in the next major release of the product. If you want a certain fix to be included in the next CU, you have to go through the regular support channels.
