### ISSUE TITLE
Cannot download symbols for new extension

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#255]
Maybe this is just not implemented yet. But VSCode tries to download symbols for dependent apps, so I guess it should work.

Created and published a new extension. After that, created a another extension that depends on the first one. Set dependencies in app.json and issued command to download symbols. However, it was unable to download it from the server.

Compared the download url with the url for the system and us symbols. It all looks correct.

These url's work like expected:
http://localhost:7049/navision_main/dev/symbols/Microsoft/System/10.0.12925.0
http://localhost:7049/navision_main/dev/symbols/Microsoft/US/10.0.16477.0

This url doesn't work (generated by VSCode)
http://localhost:7049/navision_main/dev/symbols/ArendJanKauffmann/RESTWebServicesBase/1.0.0.0

Copy navx file to the packages folder solves the issue. But according to the behavior, it should be possible for VSCode to get the navx file from the server, am I right?

**Comment by StanislawStempin** [comment]
This is a bug, we'll take a look at it
