### ISSUE TITLE
Can I set the caption for the whole project to be included in the translation file?

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#2552]
In the app.json file, it is possible to set the name of the project.

  "id": "fc6df0b5-53e3-43a2-b538-35df4f62e8ac",
  "name": "Seminar Module",
  "publisher": "D. E. Veloper",

The name from the app.json is also used as the heading in the Departments menu.
Can the caption of the project be included in the translation file somehow?

**Comment by qutreson** [comment]
Hi @peikba, this is not possible for now. See #2374.
