### ISSUE TITLE
VS code looses the symbol file randomly

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#2553]
In the middle of a project where symbols have been downloaded many times and the solution has been published many times, VS code suddenly looses the connection to the symbol.

![missingsymbols](https://user-images.githubusercontent.com/33752561/41235078-3721edce-6d8e-11e8-9dd6-1e7f3c7c967e.png)

Downloading the symbols once more, the downloaded symbol file is only 3 K  in size.
![symbolsfile](https://user-images.githubusercontent.com/33752561/41235107-498ade80-6d8e-11e8-8782-2d67dbac1a9c.png)

The only way to get them back is by running the finsql.exe" Command=generatesymbolreference, Database="Demo Database NAV (11-0)", ServerName=.\localhost command

This has happened at least once per course (and I am at my tenth course in app development)
I am running  NAV 2018 CU6 and the VSIX file is version 0.12.17091 and there are no patterns in what is triggering it.

**Comment by atoader** [comment]
Hi @peikba ! We haven't noticed this issue until now. If you can record a session of events that leads to this, it would be great.

**Comment by peikba** [comment]
I have now managed to recreate the problem:
Use an existing AL project with existing tables, pages a.o.
1) Start the Development Environment without the generatesymbolreference=yes parameter
2) Import a number of objects
3) Close the Development Environment
4) Start the Development Environment with the generatesymbolreference=yes parameter
5) Mark the Objects that were imported
6) Compile the marked objects
7) Go to VS code and download symbols again

Now only the new objects are included in the symbol file and the only way to recreate the full symbol file is to recompile ALL objects in the Development Environment.

The  finsql.exe" Command=generatesymbolreference, Database="Demo Database NAV (11-0)", ServerName=.\localhost command is not always enough

**Comment by kalberes** [comment]
The  Command=generatesymbolreference will always generate symbols out of all application objects that you have in the object metadata table.
Have you issued that command or the finsql.exe command=compileobjects generatesymbolreference=yes or the Command=generatesymbolreference ?

This "compileobjects" command will behave as you said. It will only compile the objects and generate symbols  for which in the Object table the Compiled flag is set to false.

**Comment by peikba** [comment]
I'm sorry to say, in CU6 it is not sufficient to run the Command=generatesymbolreference.

And the Microsoft guide lines for Side-by-side development says:

**Continuously generate symbols each time you compile objects in C/SIDE
Use generatesymbolreference set to yes as a command line argument each time you start finsql.exe to have all compilations add a symbol reference to the Object Metadata table. The default setting of the argument is no.**

Emphasis on the ADD a symbol reference to the Object Metadata.

Otherwise you will have to compile ALL objects every time you have changed one in the Development Environment.

BTW It worked fine in previous CU's

**Comment by dennisfrostlander** [comment]
Hi @peikba,
Apologies for a late reply.

Do you still have the problem with generating symbols?
Just to recap:
- `Command=generatesymbolreference` has to run at least once to generate the symbols for all objects in the database.
- `generatesymbolreference=yes` has to be added every time C/SIDE is started to continuously re-generate symbols for new/modified objects.

**Comment by peikba** [comment]
I just checked it on CU7 today and the problem seems to be fixed. Compiled one table and the symbol file was intact after that, but thanks for asking.
