### ISSUE TITLE
Cannot Generate Symbols NAV 2018

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2555]
I'm trying to create on event(publisher 'OnAfterReverseAmount') on codeunit 80 in NAV 2018. Even though I set a shortcut with the property: `"C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client CU06\finsql.exe" generatesymbolreference=yes`

I still can't my symbols updated:
![image](https://user-images.githubusercontent.com/13696679/41237482-7d1d6ec8-6d8b-11e8-9a89-77a773bdfa36.png)

On VSCode I'm getting this error:

error AL0280: The event 'OnAfterReverseAmount' is not found in the target

Is there anything I'm missing?

**Comment by reiniroosh** [comment]
I'm not sure but here's some potential troubleshooting steps...

1. Download symbols again in AL. Also try deleting the old .app files, and then download symbols.
2. Try turning on "Enable loading application symbol references" in the service tier admin.
3. And, try recompiling the object again.
4. Also I think someone mentioned something about running finsql as admin

![image](https://user-images.githubusercontent.com/7827702/41240003-53a440ea-6d4e-11e8-99f0-c6cbc5950446.png)

**Comment by martinhocosta88** [comment]
@reiniroosh Solved By deleting the .app files thanks a lot!
