### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#256]
I'm straight through. Can you tell me which version of the extension is just the latest?

**Comment by StanislawStempin** [comment]
0.4.9209 is the latest released version.

**Comment by Gallimathias** [comment]
0.4.9209 Are you sure? I have here a 0.4.9309 from Azure. @StanislawStempin

**Comment by StanislawStempin** [comment]
Yep, you're right, 9309

**Comment by Gallimathias** [comment]
Thank you @StanislawStempin . 

In the future, the information problem is solved by the readme :)

Closed with #258
