### ISSUE TITLE
[Question] Use ISV range for my App.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#2562]
Hi All!

I need to change my app to ISV range. Then, I want to register to bring my app to AppSource.
I need change all IDs to ISV range ID.
For Table extension, I need change ID of new Fields to ISV range ID. It is OK.

**My question:**  so, for new Table, Do I must change ID of all Fields to ISV range or I can use ID 1..
Please confirm for me because i have many new tables in my app.

**Comment by StanislawStempin** [comment]
For tables you can start numbering fields from 1.  For table extensions you need to number the new fields in your app.json range.

**Comment by hgnamvn** [comment]
OK! Thank StanislawStempin!
