### ISSUE TITLE
[EventRequest] Codeunit 395 - FinChrgMemo-Issue, new event - OnAfterInitGenJnlLine

### ISSUE THREAD

**Issue by VMashevBG** [Microsoft/AL#2565]
If it's possible to add one event in codeunit 395 - FinChrgMemo-Issue, in procedure InitGenJnlLine - OnAfterInitGenJnlLine. I have additional fields in "Finance Charge Memo Header" that I want to transfer to Gen. Journal Line.

Procedure
LOCAL InitGenJnlLine(AccType : Integer;AccNo : Code[20];SystemCreatedEntry : Boolean)

......
`  GenJnlLine."Source Code" := SrcCode;`
`  GenJnlLine."Reason Code" := "Reason Code";`
`  GenJnlLine."System-Created Entry" := SystemCreatedEntry;`
`  GenJnlLine."Posting No. Series" := "Issuing No. Series";`
`  GenJnlLine."Salespers./Purch. Code" := '';`
`END;`

`//>>Change`
`OnAfterInitGenJnlLine(FinChrgMemoHeader , GenJnlLine);`
`//<<Change`

Publisher: 
LOCAL [IntegrationEvent] OnAfterInitGenJnlLine(FinChrgMemoHeader : Record "Finance Charge Memo Header";VAR GenJnlLine : TEMPORARY Record "Gen. Journal Line")

**Comment by StanislawStempin** [comment]
The event already exists.
