### ISSUE TITLE
Cannot deploy / debug after VSCode Update

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#2566]
![image](https://user-images.githubusercontent.com/15800069/41288100-70ec44b6-6e45-11e8-9477-4836aeb676bd.png)

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Microsoft cloud sandbox",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "server": "https://myserver-xyz.westeurope.cloudapp.azure.com",
            "serverInstance": "NAV",
            "tenant": "",
            "authentication": "UserPassword",
            "schemaUpdateMode": "Recreate",
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

AL Language:
![image](https://user-images.githubusercontent.com/15800069/41288198-cdabdc3e-6e45-11e8-82f7-f881f6f4a6b7.png)

VS Code:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

![image](https://user-images.githubusercontent.com/15800069/41288631-4c47fbb2-6e47-11e8-9b29-340a959eb582.png)

Where can I search for more Information? Is there a detailed logfile, what's going wrong?

**Comment by tfenster** [comment]
@megel Maybe VS Live Share is enabled? That results in the same error

**Comment by megel** [comment]
@tfenster No VS Live Share wasn't it - I found the Problem :) 

In my current VSCode Workshop - I have used a Folder Name with whitespaces for my example:

`d:\workshop\01 start here\...` 

**The full Story:**

…Today, one of my colleagues got the problem in his VS Code Workshop VM. I tried everything but could not fix it - so he got a new VM. After lunch, the VS Code on my machine sugessted me to install an update. After the installation I got the same problem. So I removed Extension, each line of code and tried several docker versions - nothing worked. Last try with a new AL GO Project could be deployed to the NST. Then I realized the difference :) the **WHITESPACES in the Project Folder Name was the fault**.

**Comment by bwdeleeuw** [comment]
@megel I had the same issue, and your post helped me solve it. Thanks!

**Comment by megel** [comment]
@bwdeleeuw seem to me this is a VSCode bug because it was present direct after install the VSCode Update.

**Comment by StanislawStempin** [comment]
Thanks for reporting, we will investigate it

**Comment by JohanStenberg100** [comment]
Hi @megel. Thanks once again for reporting this issue. With the latest AL extension from the marketplace I'm unable to reproduce this issue. A scaffolded project using `AL:Go!` with a project folder with spaces in it deploys as expected to the cloud sandbox. To be crystal clear - I have a project located at: `C:\Users\<user>\Documents\AL\AL whitespace test`, and in that folder the `app.json` resides.

Can you verify that the latest extension works properly for you as well? If not, please provide some additional repro steps and I will continue investigating.
