### ISSUE TITLE
[Error - Search on List - Flowfilter Field] Invalid column name 'xy'. Statements(s) could not be prepared.

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/AL#2568]
Adding a flow filter field to a list, when searching, the web client crashes with an error message:
![image](https://user-images.githubusercontent.com/36630655/41291453-06e60f1a-6e50-11e8-902c-ee38b1a32fff.png)

Example:

pageextension 50101 ContactListExt extends "Contact List"
{
    layout
    {
        addlast(Control1)
        {
            field("Campaign Filter";"Campaign Filter")
            {
                ApplicationArea = All;
            }
        }
    }
}

**Comment by cmrudolph-msft** [comment]
Reproduced - this is a bug in the platform. I will fix it.

**Comment by cmrudolph-msft** [comment]
@bleisibach - what is your use case here? I am not aware of any legitimate cases for adding FlowFilter fields as controls on a page.

On the RTC, FlowFilter fields are automatically available in the 'Limit Totals' functionality. In the web client, this functionality is not available. No scenarios I know of require said field to be added to a page.

**Comment by bleisibach** [comment]
@cmrudolph-msft 
In some scenarios, users have been complaining that adding flowfilters over 'Limit Totals' takes much time and ueses much space on the top of the list. Where heavily used, we added the flowfilter field to the list in order to provide an alernative filter entry in the "Type to filer (F3)" field. e.g. Location Filter on item list or Global Dimension 1 Filter on chart of accounts.

**Comment by StanislawStempin** [comment]
Adding Flow Filter fields to the grid is not a supported scenario and has been blocked in the compiler since July 2018 Preview. It only worked by accident in the win client but will not work in the web client.
Instead the web client is getting support for Limit Totals as well.
