### ISSUE TITLE
Unexpected FilterFrom for UploadIntoStream

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#2572]
In my example, I use the following Code:

```
local procedure ImportJsonFile()
var    fileFilter:  TextConst ENU = 'All Files (*.*)|*.*|Json Files (*.json)|*.json', 
                            DEU = 'Alle Dateien (*.*)|*.*|Json Dateien (*.json)|*.json';
    
    name:        Text;
    stm:         InStream;        
begin
    
    if not UploadIntoStream('Json Import', '', fileFilter, name, stm) then exit;
end;
```

The result:

![image](https://user-images.githubusercontent.com/15800069/41295281-7873a5e8-6e5a-11e8-9356-f89390cc13f9.png)

Version(s):
![image](https://user-images.githubusercontent.com/15800069/41295451-eaeb32ee-6e5a-11e8-9e75-f22c19d3adf2.png)

Microsoft (R) AL Compiler version 0.17.19506
Copyright (C) Microsoft Corporation. All rights reserved

Success: The package is created.

**Comment by atoader** [comment]
Hi @megel ! I cannot reproduce this issue. I have created an extension containing the code you've posted and published it. I executed the function from both the Web client and the Windows client. What client are you using? What platform version?

**Comment by megel** [comment]
Hi @atoader ! Right now I had some time and tested the problem again. 
The issue is still there:
![image](https://user-images.githubusercontent.com/15800069/41581257-477abba4-739e-11e8-808d-be9eea25ff1c.png)

My used example project:
[Microsoft_AL_[Upload2Stream-Filter].zip](https://github.com/Microsoft/AL/files/2114148/Microsoft_AL_.Upload2Stream-Filter.zip)

My current Version(s):
Microsoft (R) AL Compiler version 0.17.20571
Copyright (C) Microsoft Corporation. All rights reserved
Success: The package is created.

Used docker Image: `bcinsider.azurecr.io/bcsandbox-master:de`
![image](https://user-images.githubusercontent.com/15800069/41581392-9f8638e6-739e-11e8-994c-427742beacc0.png)

**Comment by atoader** [comment]
Hi @megel ! I still cannot reproduce it on master. I will try to reproduce it on the Docker image.

**Comment by atoader** [comment]
I tried the same code on Docker and it worked just as before. I switched the language to German and it still worked in the same manner. What is the Locale settings of your machine? That shouldn't matter, but maybe it does.

**Comment by megel** [comment]
I have a German Windows 10 as OS and my colleagues too.
I normally use NAV from docker of the workshop VMs from FreddyDk in azure 
I try too connect to one of this machines and see if I have the same result.

**Comment by StanislawStempin** [comment]
This is by design:
https://docs.microsoft.com/en-us/dynamics-nav/uploadintostream-function--file-

FromFilter
Type: Text 
The type of file that can be uploaded to Microsoft Dynamics NAV Server. 
In the Microsoft Dynamics NAV Windows client, the type is displayed in the upload dialog box, so the user can only select files of the specified type. For the Microsoft Dynamics NAV ***Web client, a user can try to upload any file type but an error occurs if the file is not the specified type.***
