### ISSUE TITLE
Business Central SOAP Authorization for AAD Guest Accounts

### ISSUE THREAD

**Issue by zpfaltersack** [Microsoft/AL#2574]
Hello,
We have some users that have access to multiple Business Central tenants through a single AAD account that has been added as a Guest to AAD/Business Central. This works fine for the web client but SOAP services rejects them across the board with authentication/authorization errors. I don't see any known issues listed around this type of setup. Is this a use-case that is expected to be supported?

Thanks,
Zachary

(I accidentally posted this to the wrong page first: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/66 and can't delete it but don't want to close it without an answer)

**Comment by atoader** [comment]
Hi @zpfaltersack ! This is more of a product question than a question about the development environment. Please read our [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#nav-2018-issues) . I suggest that you contact the support channel.

**Comment by zpfaltersack** [comment]
Sorry. I saw similar questions posted so assumed it was fair game. Thanks.
