### ISSUE TITLE
The type or method  cannot be used for extension development

### ISSUE THREAD

**Issue by nanla** [Microsoft/AL#2577]
we need below methods to be opened for our app. Please check.
page 560.GetSelectionFilter
codeunit419.UploadFile
codeunit762.DrillDown
codeunit1319.DrillDown
codeunit1317.UpdateChart
codeunit1319.UpdateChart
codeunit763.UpdateDataPerGroup
codeunit764.UpdateData
codeunit8614.DecompressPackage
codeunit8614.ImportPackageXML
codeunit762.UpdateData
codeunit8.CalcCell
table 370.OpenBook
table 370.CreateBookAndOpenExcel
table 485.GetPeriodFromMapColumn
report 111.InitializeRequest
report 116.InitializeRequest

The type or method 'SetUserPassword' cannot be used for 'Extension' development.

TableRelation = Object.ID WHERE (Type=CONST(Report)

System/outlook not support in VS code

Length of the identifier cannot exceed 120 characters
CameraOptions : DotNet "'Microsoft.Dynamics.Nav.ClientExtensions, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.Microsoft.Dynamics.Nav.Client.Capabilities.CameraOptions";

NAV version we are using is: NAV2018CU5
thanks.

**Comment by grobyns** [comment]
Hi,

regarding the following:

codeunit419.UploadFile
codeunit8614.ImportPackageXML
table 370.OpenBook
table 370.CreateBookAndOpenExcel

you cannot get access to the file system so these will not work in an extension. We will not expose them. You have to use stream based functions instead and upload from the client file into a stream.

regarding:
The type or method 'SetUserPassword' cannot be used for 'Extension' development.

have you tried using Page 9810 Set Password ?

regarding:
Length of the identifier cannot exceed 120 characters
CameraOptions : DotNet "'Microsoft.Dynamics.Nav.ClientExtensions, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.Microsoft.Dynamics.Nav.Client.Capabilities.CameraOptions";

you cannot use DotNet variables in an extension. You can either create a DotNet wrapper codeunit and post it on Open C/AL Library or (in this case) you can use Page 1910 Camera Interaction.

regarding:
TableRelation = Object.ID WHERE (Type=CONST(Report)
System/outlook not support in VS code

Please elaborate on the problem and what you are trying to do.


regarding:

page 560.GetSelectionFilter 
codeunit762.DrillDown
codeunit1319.DrillDown
codeunit1317.UpdateChart
codeunit1319.UpdateChart
codeunit763.UpdateDataPerGroup 
codeunit764.UpdateData
codeunit762.UpdateData
Table 485.GetPeriodFromMapColumn 

these are already marked as external, please try a more recent version.

regarding:
codeunit8614.DecompressPackage 
report 111.InitializeRequest
report 116.InitializeRequest

I will need to look into these. the two reports should pose an issue but DecompressPackage will need a closer look as it uses the filesystem on the server.

br/Gert

**Comment by nanla** [comment]
Hi grobyns,
Thank you for your response.

regarding  "TableRelation = Object.ID WHERE (Type=CONST(Report)"
get error "The type or method 'Object' cannot be used for 'Extension' development." when trying to set table relation property

regarding 'System/outlook not support in VS code"
When trying to define a system part as Outlook, get error message "The value assigned to the SystemPart type is not valid. Valid values are Notes, Links, MyNotes."

We are using NAV2018CU5, we will try NAV2018CU6 

thank you again

**Comment by grobyns** [comment]
Hi,

instead of using the Object table you can use the AllObj or AllObjWithCaption tables I think.

I'll forward your issue about outlook to the appropriate team but I fear that's simply not supported...

br/Gert

**Comment by grobyns** [comment]
Hi again,

regarding the exposed methods. I don't think we are backporting these back to NAV2018. You should find them in the latest docker images for Business Central though...

br/Gert

**Comment by nanla** [comment]
Thank you, Gert.

**Comment by grobyns** [comment]
Hi,

regarding the outlook issue: The team has filed a bug for this so it will be fixed in the next major version.

br/Gert

**Comment by nanla** [comment]
Thank you Gert!


________________________________

**Comment by JesperSchulz** [comment]
I have exposed the following:
- report 111.InitializeRequest
- report 116.InitializeRequest
- codeunit8.CalcCell

I cannot expose codeunit8614.DecompressPackage, as it uses serverside files, which are not supported for extension development. For extensions, please use streams. You might consider using DecompressPackageToBlob in the same codeunit, which uses streams instead of files.

**Comment by nanla** [comment]
Thank you very much!


________________________________

**Comment by nanla** [comment]
Hi Gert,

Thank you for all your help.

I have another question related with AL.

Our customer who is using Dynamics 365 Business Central wants to get a customized role center page. The page will have links combined from 5 different role center pages such as 9022,9027,9006,9026, and 9028.  The role center page in Business Central has different links than the role center page in NAV2018. We don't have access to the Business Central database. Is there a way to figure out which page/report the link pointing to?


For example, how to find out which page/report Deferrals pointing to?


[cid:f2f35f4c-782a-4eaf-b95f-4cfa2dfceb0f]

Thank you very much for your help.

Lan


________________________________

**Comment by grobyns** [comment]
Hi Lan,

you can use docker images and set them up as business central. Freddy has a series of blogs with all the info. Have a look here to see which image you can use for your scenario: 
https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/

I'll close this issue now, please open new issues if you have further questions.

cheers,
Gert

**Comment by nanla** [comment]
Hi Gert,
Sorry to bother you again. You closed this issue. But my question is still related with this issue. You replied "these are already marked as external, please try a more recent version.". But I still get the same error message when I use docker image "microsoft/bcsandbox:us" which should be the current version. 
Can you please tell me which version the methods we requested are open to use?
thank you very much!

**Comment by grobyns** [comment]
Hi,
please try this one: 

cinsider.azurecr.io/bcsandbox-master

or 

cinsider.azurecr.io/bcsandbox-master:us

br/Gert

**Comment by nanla** [comment]
Hi Gert,

Thank you for your response.

I tried docker run to get the image. I got error "unable to find image locally". I tried docker pull cinsider.azurecr.io/bcsandbox-master:us. it asks for user name and password. What user name/password should I provide?


[cid:2ec25c3b-f4cc-4d0b-8434-31c9cbf78d11]

Thank you again.


________________________________
