### ISSUE TITLE
Download Symbols With AccessControlService Credentials

### ISSUE THREAD

**Issue by araratnalbantoglu** [microsoft/AL#2581]
Hi All,

I have a multitenant, on-prem NAV2018 testing environment which is configured for single sign-on O365 authentication. I have no problems with this deployment and users can access both web/windows clients with their credentials. However, I could not manage to find the right type of configuration to download symbols when the NAV server instance configured as AccessControlService. Since this configuration is very new for me, I may be missing some basic configurations in launch.json file which I will be more than happy if you can point it out for me. Can you kindly let me know how is it possible to download symbols, how the launch.json file should be adjusted if your NAV servers credential type configured as AccessControlService.

NAV Version : 11.0.21441
VS Code Version : 1.24.0

Thanks,
Ararat

**Comment by dennisfrostlander** [comment]
Hi @araratnalbantoglu,
Unfortunately, AL extension in VSCode does not yet support on-premise servers with AccessControlService authentication mode.
As a workaround, you can manually place the symbol files into the .alpackages folder in the project and manually publish the extension with powershell.

**Comment by araratnalbantoglu** [comment]
Hi @dennisfrostlander,
Thank you for your answer. I will go with the workarounds for now whilst hoping the feature is added.

**Comment by kalberes** [comment]
AADAuthentication (Entra) ONPrem should be supported by the toolset.
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-aad-auth-onprem
