### ISSUE TITLE
Problem with license in Business Central 

### ISSUE THREAD

**Issue by mynavblog** [Microsoft/AL#2587]
Hi, 
I tried to find the solution for my problem but unsuccessfully. My issue is similar to this on https://github.com/Microsoft/AL/issues/2232 but I could not find there a solution.

I using Business Central and my own container on Docker locally. I got the object range from 70138921-70139920. License is generated for Product Version 2018; Product Line: Microsoft Dynamics NAV Perpetual (other option was not possible).

However when I try to publish my extension I got error:

`[2018-06-13 22:35:03.27] The request for path /nav/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Your program license does not allow you to publish 'CustomerTest'.`

Object looks like this (created only for tests): 
![image](https://user-images.githubusercontent.com/37371997/41377486-7317cb12-6f5c-11e8-83f9-ae23788302c8.png)

I did a test with the Permission Range and it seems that all is fine. There is permission to execute the objects:
![image](https://user-images.githubusercontent.com/37371997/41377643-06fcbefa-6f5d-11e8-8055-834c7ff5cc1e.png)
 
Could you help me and guide what I am doing wrong?

**Comment by JulienDecottignies** [comment]
Hi,

Did you try to use import your flf to your Docker Container with this powershell comand line ?

Import-NavContainerLicense -containerName yourcontainername -licenseFile "pathToYourFlf"

(The path to the flf can also be an Url)

https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-license/

**Comment by mynavblog** [comment]
Dear All,

Thank you for help. problem was with license file. I fix it and now all works properly.
