### ISSUE TITLE
How can we handle the code written inside the standard local function in codeunit 12

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#2594]
In codeunit 12 inside the function "HandleAddCurrResidualGLEntry" some custom code is written that i want to move into Extension how can i handle that.
I have found some more scenarios where standard function has been modified.

**Comment by StanislawStempin** [comment]
It needs to be done through event subscribers. Either by subscribing to existing events in the app or requesting a new event. 
Please search for issues labeled  event-request on this forum to see what other developers are requesting to get a better feel for it.
