### ISSUE TITLE
Menu Structure for ISV Extensions

### ISSUE THREAD

**Issue by AncaSterian** [Microsoft/AL#2598]
Dear All, 

We are currently  developing a localization add-on using only extensions and AL code. 

Currently   we categorized all the pages and reports  with a certain Usage Category and they appear in the menu with one of the categories:
•Lists
•Tasks
•ReportsAndAnalysis
•Documents
•History
•Administration

The problem is that we want to have subgroups as in the standard Financial Management. 
How can we do that ? 
We know about the workarounds to extend the standard role centers by adding pages and modifying the ribbons but it's not what we want at all. 
The UsageCategory it's not enough.
Why this facility is not available anymore  as  for the classic modification of the menusuite? 

Does Microsoft have in mind this feature?

I've checked and the functionalities for the extensions as Paypal and  Forecast are included somehow in the standard Departments. 
How is this possible? 
You cannot extend it also for the extensions developed by partners? 

Thank you very much in advance.

Kindest Regards, 
Anca

**Comment by StanislawStempin** [comment]
We are currently not planning for any hierarchical menu structures. Navigation can be achieved either through adding pages to search or by adding direct links from Role Centers.
