### ISSUE TITLE
AL language features

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#2599]
Just 3 of the (IMHO) required language features for AL to be a successfuly replacement of C/AL.

1. A serious `DateTime`. Something like .NET offers. I ran into an issue last week where I needed to format a given DateTime in various locales. It was basically data that got sent to an external system for printing labels. This data is just a list of strings. Depending on the final customer the labes were for, I had to format them in different DateTime locales. I successfully used `DateTime.ToString` together with `CultureInfo`. But I cannot do this anymore in AL.
Making a WebService for such a task makes no sense. I cannot risk such a trivial operation failing because of our WebService being down - for whatever reason.

2. Some basic PDF metadata management. Example: In Italy, VAT registers are usually printed monthly. Plus we have the need to "mark" each page with it's page number. The VAT register for february needs to start with the page number (+1) that january ended with. That's because you need to make sure you don't have any gaps in those registers. Or otherwise the police comes to steal your souls.
The italian localization solved this problem by simpy asking the user, after the VAT register finished printing, how many pages were printed. This is embarassing, to say the least. It's 2018 and we cannot count page numbers?
In OnPrem NAV environments we solved this by not printing directly, but saving a PDF and then counting it's pages. With no .NET available, we cannot do this anymore.
A WebService for sending around PDFs only to count their pages would be a little troubling. Picture telling your customer, that his trial balance and VAT registers are sent around over the interwebs.

3. RegEx. For real. We need regular expressions.

**Comment by atoader** [comment]
Hi @hemisphera ! Thank you for the input! We will consider it moving forward.
