### ISSUE TITLE
Installing the Developer Experience installation fails

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#260]
I get an error in the installation script. Do you have a problem with generic names in the Windows user?

````powershell
The Windows account could not be mapped to a valid security identifier (SID). (at <ScriptBlock>, C:\DEMO\New Developer Experience\install.ps1: line 63)

````

**Comment by StanislawStempin** [comment]
I'm not sure I understand what you mean. Could you please provide the steps that you followed that result in this error?

The recommended way to use Dev Previews is to deploy through aka.sm/navdeveloperpreview and wait 5-7min after the Azure deployment succeeds to let the machine initialization scripts finish running as well.

**Comment by ajkauffmann** [comment]
Once in a while, the deployment fails. I have now literally deployed about 200 developer preview VM's for training classes, and seen problems initialization problems with maybe 10 of them. Just throw the resource group away and redeploy it.

**Comment by Gallimathias** [comment]
@StanislawStempin The problem is in the initialization and install script, so this breaks. Waiting therefore does not help.
I have the problem actually every time, it is because the script can not create a Navision user or no valid SID to the user.
I think the problem is the windows username. Currently, this is NewNavExp

@ajkauffmann What kind of windows user names do you have? Small or uppercase windows usernames?

Just a new machine does not solve the cause

**Comment by ajkauffmann** [comment]
I leave the user names to the default settings.
Checked your scenario, and I was able to create a machine with user name NewNavExp (status.aspx showed installation complete).

**Comment by Gallimathias** [comment]
I now have 4 machines, each time the same settings. Every time the same error. The error can be reproduced.

**Comment by ajkauffmann** [comment]
Created 47 new machines last Saturday. Two of them had an error, recreated them and it worked fine.
I guess you need to share the exact steps you do (e.g. how do you create the VM, what do you fill in the parameters), otherwise nobody has an idea how to reproduce.

**Comment by Gallimathias** [comment]
Step 1: I'll get a coffee
Step 2: I look for the preview in the catalog of the new virtual computers
Step 3: After clicking Create I enter the following parameters:
* Name: NewNavExp
* Storage: HDD
* Username: NewNavExp
* Passwort:
* Abbonement: Visual Studio Enterprise - MPN
* Ressource group: new Resourscegroup = NewNavExp
* Location: Westeurope
Step 4: I Select the DS3_V2 Standard (4 Cores, 14 GB)
Step 5: I accept the default values on settings:
* new storageaccount: newnavexpdisks140 (new)
* virtual network: NewNavExp-vnet (new)
* Subnet: default
* IP: NewNavExp-ip (new)
* Security: NewNavExp-ns (new)
* Extension: no
* Availability group: no
* Startdiacnostic: Active
* Guest diacnostic: Disabled
* Diacnosticaccount: newnavexpdiag194 (new)

Step 6: I'm waiting for completion
Step 7: I connect with RDP
Step 8: I wait and get the error message
Step 9: I wait a bit and then try to manually trigger the script and get the error message again

**Comment by ajkauffmann** [comment]
Why not use http://aka.ms/navdeveloperpreview ?

That is not only using the same vm image, but also includes a deployment template that executes the initialization script in the correct way. I'm not sure that script will get executed correctly when you create the VM manually like you do.

**Comment by Gallimathias** [comment]
I thought it was the same. Ok I try my luck. And of course, keep step 1 XD

**Comment by Gallimathias** [comment]
Ok with the link it works, nevertheless the error remains when you try it manually.

**Comment by ajkauffmann** [comment]
I'm glad it worked. Of course you can create your own deployment template to create a VM based on the same image. That's what I did actually. But that's another story.
