### ISSUE TITLE
[Debug mode] Error: Not an application method

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#2600]
Hi,

When I try to publish my extension (into docker container bcsandbox:12.0.21405.22535-fr) in debug mode I have this following error after succesfull pusblish to the server:

`Error: Not an application method.`

My extension depends on another extension, "showMyCode" = true in both of them. 

When I hit CTRL+F5 instead of F5 it works fine..!

AL Language 0.15.18771

**Comment by thpeder** [comment]
Hi @JulienDecottignies,
Do you have any breakpoints set, and are any of them placed not on a statement?
![image](https://user-images.githubusercontent.com/24276180/41705969-de2761a4-753a-11e8-8dd7-528cfb6f4f7e.png)

**Comment by JulienDecottignies** [comment]
Hi !

That's it ! I had a breakpoint on a ControlAddin event:

![image](https://user-images.githubusercontent.com/29598240/41706737-d092084e-753c-11e8-8b8f-ab3e6d96678f.png)

Removing it fixed the problem.

Thanks !
