### ISSUE TITLE
Attempt to Divide by Zero when posting to General Journal

### ISSUE THREAD

**Issue by Robrownn** [Microsoft/AL#2605]
The following code currently throws an "Attempt to divide by zero" error. Essentially we have an extension codeunit that is posting payments to the general journal using the Gen. Jrnl.-Post Line RunWithCheck function. 

```
IF NewCVLedgEntryBuf."Currency Code" = OldCVLedgEntryBuf2."Currency Code" THEN BEGIN
  AppliedAmountLCY := ROUND(AppliedAmount / OldCVLedgEntryBuf."Original Currency Factor"); <---
  OldAppliedAmount := AppliedAmount;
```
What could be the circumstances that cause this error?

Thanks for your help.

**Comment by RomanZanizdra** [comment]
Hi Robert. If the question is still relevant can we dive a little bit deeper in details.
Follow from your description you post payments through the journal and apply it invoice. That's mean the OldCVLedgEntryBuf is invoice entry. From my experience that's a quite "difficult task" to post initial entry with zero currency factor. So can you share with me the information about initial invoice and payment is applied to it, I'll try to help you.

**Comment by Robrownn** [comment]
Hey Roman, thanks for the reply. We eventually got around the error although I forget what steps we took to fix it. Sorry I can't be of more help to this issue, but we haven't experienced a problem yet with our new approach. This issue can be closed if need be. Thanks.

**Comment by ikoletic** [comment]
Closing as we're unable to repro.
