### ISSUE TITLE
Idea: Implement code-documentation like in C#

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2607]
I would really love to see code-documentation be available in AL as it is in C#. That is: Add documentation tags to methods and be able to document the method itself and it's various parameters. Something like:

````
/// <summary>This is a very important method</summar<>
/// <param name="Param1">The first parameter. An integer.</param>
/// <param name="Param2">The first parameter. An boolean.</param>
/// <returns>A number. An important one.</returns>
````
````
local procedure MyFunction(Param1: Integer; Param2: Boolean): Decimal;
begin
  // really important stuff happening here
end;
````

This could then be integrated into IntelliSense, exported as documentation XML, included in packages and whatnot ... would be helpful. ... and maybe even encourage people to document stuff.

**Comment by qutreson** [comment]
Hi @hemisphera, thank you for your feedback. Adding documentation is tracked by the issue #132.
