### ISSUE TITLE
Double Cursor

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#261]
During Edit I have got a "Double Cursor", which allows to add text in both positions at the same time.

![grafik](https://user-images.githubusercontent.com/15800069/26877390-122eeff2-4b8a-11e7-9e9e-38770a7069af.png)
![grafik](https://user-images.githubusercontent.com/15800069/26877494-6a53d30a-4b8a-11e7-89e9-9a7748b6669d.png)
![grafik](https://user-images.githubusercontent.com/15800069/26877518-7dfd0e62-4b8a-11e7-927a-d648acb29645.png)
![grafik](https://user-images.githubusercontent.com/15800069/26877584-a12e2394-4b8a-11e7-8d88-8a26b95c7cae.png)

**Comment by StanislawStempin** [comment]
This is a VS Code feature. It activates if you Alt + click in the source text. To deactivate just click without Alt anywhere in the source.

**Comment by megel** [comment]
Thx
