### ISSUE TITLE
[Question] Will the Windows Client disappear for OnPrem Solutions?

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/AL#2611]
One of the hottest discussion points in our company is about WebClient vs WindowsClient. We have had many difficulties using the WebClient in OnPrem solutions mainly with file manipulation.

Could we get a reply from Microsoft saying yes the WindowsClient will disapear for OnPrem between this and X - Months/ Years?

I believe the WebClient is great for all the small businesses but not for the bigger ones that need a lot of custom functionality.

I hope both of them stay an option indefinately :)

**Comment by mikebcMSFT** [comment]
Hi @BartPermentier,

Microsoft has not announced any date of discontinuation for the Windows client.

However, rest assured that the Web client is the future and is the only technology stack that allows us to innovate at a rapid pace and deliver modern experiences across platforms and devices. If you're not embracing the Web client today, you may be falling behind already. We're investing aggressively in making this better on all fronts, from performance to productivity to accessibility to aesthetics and ease of use.

Consider that the implementation challenges we face now, including local file handling, are not necessarily with the Web client itself, but the fact that we need to rethink how we design for a cloud-first, mobile-first world. Can it be done differently? Does it need to be on a local PC? Can web services be used? Can Office 365, Dropbox, Azure storage or similar help complete the story?

I hope this helps you put the debate to rest at your company :)
Best regards,
Mike Borg Cardona
Program Manager, Microsoft

**Comment by jglathe** [comment]
Web Client only == no longer NAV, ever. End of Story. We have enough examples of companies who have tried this and failed big time. It is not feasible in the SMB ERP world. Stop trying this nonsense, please.

**Comment by BartPermentier** [comment]
Hi @mikebcMSFT ,

thank you for your response! I'm wondering if this is also the place to post feedback that we get from our customers about the WebClient?
For Example: Not being able to close a SubPart (Like Sales Lines on Sales Order Page) is one that frequently comes up.

We have used Microsoft's suggestion to use Azure Functions to re-enable some of the functionality but it is just not fast enough (and tbh just feels like a way to scam us/our customers out of extra subscriptions fees). We used it to generate barcodes which resulted in a report running 15-30 seconds longer.

Today we even noticed different behaviour when using IE vs Chrome vs Edge. You can imagine the customers reaction when we told him he cant use his favorite browser.. Currently we can't check in the code what browser the customer is running and I don't think anyone will want to develop and maintain all these differences. So if the WindowsClient goes I hope by then MS has worked out all those quirks.

**Comment by FSharpCSharp** [comment]
@mikebcMSFT 
Thank you for telling me Microsoft's point of view on using the Web Client. Perhaps a technical follow-up question. In the past, the Web Client was not as powerful as before. One of the main problems customers reported time and again was that they could no longer record orders or many book page lines so quickly, for example. That has improved in the meantime.

But there is also a new plant growing in web development - web assembly. This is a special technology for transferring previously complex client applications or other complex interfaces to the web. This format is slowly approaching something useful. Would it be possible for the Web Client to benefit from this technology in the future? This would make many things much easier to implement if you look at the current examples. Is Microsoft open to such developments, or is the focus currently on other things?

**Comment by mikebcMSFT** [comment]
Thanks for all the great questions and feedback.

@BartPermentier: Go ahead and add your Web Client feature suggestions to aka.ms/BusinessCentralIdeas, or vote up ideas already listed! We're constantly looking at features that gather momentum that could delight our customers in a future release.

@BartPermentier: There should be very few functional differences across browsers. If you believe the browser difference you encountered is a defect that is affecting your customers, kindly file a support request with Microsoft Support.

@FSharpCSharp: We also think that WebAssembly is a technology path that could add value. We are tracking a couple of others such as Electron, and PWA which could also unlock richer customizability in the future.

@rdebath: Yes, that is also a potential solution that would unlock a number of integration customization scenarios.

Whilst integration with local resources or specialized hardware remains a challenge, the Web client continues to improve. Check out the [powerful new features available in the Business Central October '18 update](https://docs.microsoft.com/en-us/business-applications-release-notes/October18/dynamics365-business-central/high-productivity-user-experience) for more information.
