### ISSUE TITLE
Publishing a WebService from an Extension could be easier

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#2614]
Publishing a WebService from an Extension is possible by adding a record to table `2000000168 Tenant Web Service`. However it would be a lot easier if procedure `CreateTenantWebService `in codeunit `9750 Web Service Management` was external. Is it a design decision to not make that procedure external? From my point of view as the table is available for extensions, the procedure should also be available

**Comment by IvoMol** [comment]
Add into your AL project XML file such:

<?xml version="1.0" encoding="utf-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>8</ObjectType>
            <ServiceName>Training</ServiceName>
            <ObjectID>50101</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>

You will see...

**Comment by IvoMol** [comment]
Again:
![vystrizek](https://user-images.githubusercontent.com/17826638/41475625-d10f03ae-70ae-11e8-97e2-6dd4f1b2c983.PNG)

**Comment by tfenster** [comment]
I guess this is creating and publishing the WebService? While that is very nice, I think there still should be an easy way to publish a WebService dynamically on runtime, e.g. based on data or some kind of trigger

**Comment by JesperSchulz** [comment]
Agree. That function should be exposed! There is no risk in doing so, seeing that you can (and should be able to) create web services from extensions. I'll fix that right away! Thanks for reporting!
