### ISSUE TITLE
No translations available for extension name in app.json affects menu department

### ISSUE THREAD

**Issue by cherabomb** [Microsoft/AL#2616]
I am following up to the resolution implemented for the following (closed) issue:
https://github.com/Microsoft/AL/issues/1264
I am developing for NAV 2018 on-premise with AL 0.12.17720

The display of my extension name as "department" in both Web Client search results and RTC Menu Suite is extremely unsatisfactory because there is no ability to translate the name to the languages available in my extension. Please add a displayName property to app.json with support for multiple languages.

**Comment by qutreson** [comment]
Hi @cherabomb, it is not possible at the moment (see issue #2374).
