### ISSUE TITLE
Event Request: Codeunit 1510 - Notification Management - OnBeforeGetDocumentTypeAndNumber (with a 'Handled' parameter) or OnAfterGetDocumentTypeAndNumber (supposing the ELSE part of the case structure)

### ISSUE THREAD

**Issue by KristofKlein** [Microsoft/AL#2619]
Hi, 
to be able to hock up with the Notification/Approvalflow I need to be able to redirect the fieldnumber for new tables. Hardcoded fieldNo3 is no good. 

(This has been also requested in the closed issue #534)
Br Kristof

**Comment by AlexanderYakunin** [comment]
Can you please be more specific and describe needed events and their placement?

**Comment by KristofKlein** [comment]
Hi,

sure! Or well, i will try :) 

So Codeunit mentioned 1510 has  Procedure GetDocumentTypeAndNumber. The good think is it takes all kind of Records due to the RecRefs pattern. The stupid thing is that it is checking HARD on the type of Record. And based on that it decides what to return to the calling Function.

If I now want to establish a new approval flow for a new type of record which involves notification I'm hit in here because NAV will go into the else case of the case statement and tries to set the Field No to 3. But I do not have a Field No. 3 or it does not fit the need (e.g. I want field 1 instead). So I was hopping since also other parts of the approval flow haven been put into an Event Pub/Subscriber context that this element will also follow. 

You can also read in the issue #534 what "fvet" wrote on "commented on Sep 4, 2017" he is addressing this in an even more advance way than i do!

Br, 
Kristof
