### ISSUE TITLE
Question: Where is the error log ?

### ISSUE THREAD

**Issue by ryanbudge** [Microsoft/AL#2621]
Hi Guys,

When installing an extension fails we get the error message below
 
_Publish operation failed with code PackageDeployFailed. Details: The extension failed to be deployed successfully. View the error details for more information and then deploy again._

I have managed to figure out what was wrong, but it took me a long time.

Surely we can get better error messages out of the system?
Where is the error log ?

Cheers,
R

**Comment by StanislawStempin** [comment]
Improved error log will be available in the upcoming Business Central online update started being rolled out next week.
