### ISSUE TITLE
[Feature Request] "Record Based FlowField" or "Expression Filled Variable"

### ISSUE THREAD

**Issue by hhfiddelke** [microsoft/AL#2622]
To reduce the complexity of NAV you should implement a fuctionality i would name "Record Based FlowField" or "Expression Filled Variable".
There are many redundant variables in NAV- records like "Qty. Shipped not Invoiced" or "Outstanding Quantity" in T37. These variables have no real new information because they have a fixed calculation of other variables like  "Qty. Invoiced" -"Qty. Shipped" respectively "Quantity" -"Qty. Shipped".

Handling like a automaticaly calcuated flowfield would reduce the effort in code to update these fields, and would reduce the need of  knowledge about "to validate or not to validate" or to call functions to upate these variables.   

Another way could be to assign these varibales by an expression- property like 'Value="Qty. Invoiced" -"Qty. Shipped"' which is automaticaly triggered by assigns (with validate or not) to the used Variables. This would have the advantage not to break other NAV- functionalites, and there would be only a small impact to the NAV- Structure.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider it for the long term backlog.

**Comment by blrobl** [comment]
Hi, thank you for your suggestion! We are not prioritizing this for the immediate future, but if still relevant for BC we recommend you submit this at aka.ms/BCIdeas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
