### ISSUE TITLE
Event Request: Add OnAfterSetFilter events for accounting schedules

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2625]
In `Codeunit 8 AccSchedManagement` please add a few events that let us customize the filters that are set on the G/L account and cash flow account. Something like

`OnAfterSetGLAccRowFilters`
`OnAfterSetCFAccRowFilters`
`OnAfterSetGLAccColumnFilters`
`OnAfterSetCFAccColumnFilters`

called just after the relative function. This way we can add some more filters without having to completely rewrite the calculation code in `OnBeforeCalcCellExit`.

Plus: an event `OnAfterSetEntryFilters<InsertTableNameHere>` that provides us the possibility to customize the filters set on the various entry tables that are summed up for calculation (= `G/L Entry`, `Analysis View Entry`, `Analysis View Budget Entry` `Cash Flow Forecast Entry` and `G/L Budget Entry`) would come in handy to customize the filters that effectively get set for calculation.

**Comment by AlexanderYakunin** [comment]
Please provide more information about OnAfterSetEntryFilters.

**Comment by hemisphera** [comment]
I have currently designed the events on my local database as follows:

````
OnAfterSetFilterGLEntry(
  VAR GLAcc: record "G/L Account";
  VAR AccSchedLine: record "Acc. Schedule Line";
  VAR ColumnLayout: record "Column Layout";
  VAR GLEntry: record "G/L Entry);
````

The same goes for the following events
OnAfterSetFiltersCFForecastEntry (`Cash Flow Forecast Entry`)
OnAfterSetFiltersGLBudgEntry (`G/L Budget Entry`)
OnAfterSetFiltersAnalysisViewEntryGL (`Analysis View Entry`)
OnAfterSetFiltersAnalysisViewEntryCF (`Analysis View Entry`)
OnAfterSetFiltersAnalysisViewBudgEntry (`Analysis View Budget Entry`)

depending on whether it is a G/L Account or CF Account, the respective record should be passed.

The events are raised in the method `CalcGLAcc` (and `CalcCFAccount` respectively) just after all the various filters have been applied to the entry table.

![image](https://user-images.githubusercontent.com/8897936/41604124-c55c3210-73de-11e8-9a73-4c9359c16de8.png)
