### ISSUE TITLE
Time datatype field - wrong lookup in page

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2628]
Create a field with Time Datatype in table
add field to page
run the page.
the time datatype field has lookup to Date.

![image](https://user-images.githubusercontent.com/23735402/41548841-afeb2be0-7341-11e8-9191-1a7606e0a9fd.png)

**Comment by dennisfrostlander** [comment]
This looks like a webclient issue. The RTC client does not show any dropdown for the time fields, but the webclient shows the date dropdown for the time fields.
The same happens for pages designed in C/SIDE as well.
