### ISSUE TITLE
Page Management - PageRun / PageRunModal etc. on "Internal"

### ISSUE THREAD

**Issue by dNsl9r** [Microsoft/AL#263]
I tried to use the functions "PageRun" / "PageRunModal" from Codeunit 700 "Page Management" in .al, but the functions are set to FunctionVisibility "Internal". Will this be changed or is there any reason to not have this functions available for . al extensions?

![grafik](https://user-images.githubusercontent.com/5330063/26878993-c9efcb7a-4b8f-11e7-891a-bf73a3e17f64.png)
![grafik](https://user-images.githubusercontent.com/5330063/26879010-dc524b30-4b8f-11e7-8294-0b1f7e92692c.png)

**Comment by StanislawStempin** [comment]
This will be re-enabled in June Update.

**Comment by dNsl9r** [comment]
Thanks @StanislawStempin - another one: What about the Error Log Functions in Table Error Message (Table 700)?

**Comment by StanislawStempin** [comment]
We will look into it. I will log it as a new issue to track resolution separately.
