### ISSUE TITLE
Visibility to External codeunit 57,  8617

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/AL#2631]
Hi can we get These External

1. Codeunit 8617 Config. Validate Management
Function - EvaluateValueWithValidate Change the function Visibility to External

2. Codeunit 57 Document Totals
Function - SalesCalculateTotalsWithInvoiceRounding Change the Function to Global with Function Visibility to External

**Comment by JesperSchulz** [comment]
Hi!

Thank you for reporting your issues!

About 1: That function was already exposed and should be visible in the latest developer previews. As per the following blog post, changes are not backported automatically. If that is needed, please follow instrcutions in the blog (https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/).

About 2: Preferably, we'd like to avoid exposing local functions, as doing so locks down our opportunities for change of design in the future. Function SalesRedistributeInvoiceDiscountAmounts seems to have the same list of parameters and eventually calls into SalesCalculateTotalsWithInvoiceRounding. That function already IS public and external. Would that function fullfill your needs and if not, what has to change?

**Comment by JesperSchulz** [comment]
Closing isse for now. If suggestions don't work for you, please reopen and we will take another look!
