### ISSUE TITLE
Microsoft /AL: Business Central: "The Item Ledger Entry does not exist. Identification fields and values: Entry No.='0'"

### ISSUE THREAD

**Issue by EelcoWijr** [Microsoft/AL#2633]
"The Item Ledger Entry does not exist. Identification fields and values: Entry No.='0'" error message when you post a sales invoice with drop shipment where some sales lines have item tracking and others not.

We noticed that in NAV2018 we had the same error. This is fixed in NAV2018 CU6. When can we expect this to be fixed in Business Central?

267926
COD 90

**Comment by StanislawStempin** [comment]
If this is fixed in a CU then it should be available in the next release of Business Central in Fall.

Note that this repo should only be used for AL development related issues and not for regular application bugs.
