### ISSUE TITLE
Suggestion: Add a new DataType / Object called Interface

### ISSUE THREAD

**Issue by megel** [microsoft/AL#2635]
There are some common datatypes e.g. for records and fields - RecordRef and FieldRef. Yes they work pretty good.

But what can you do with Pages and the other Kinds objects e.g. Reports, ...? 
I suggest to define a **Interface** in as a new object. Interfaces could be assigned by a property e.q.:

```javascript
interface 50100 "My Interface"
{
      procedure DoSomething(...)
      begin        
           // no Code allowed
      end;
}

page 50100 MyPage
{
     // …
     Interfaces = Interface::"My First Interface", Interface::"My Second Interface";
     // …

     // This Object must implement the interface method (local or global)
     procedure DoSomething(...)
     begin        
           // no Code allowed
     end;
}
```

The generating of this Code / Objects in the NST with C# / .NET IL is not so difficult.

How to use such interface objects - the `Variant` DataType must be improved with several Methods:
```javascript
var varInterface: Variant;
var myInterface: Interface::"My Interface";

if varInterface.IsInterface(Interface::"My Interface") then
begin
   myInterface := varInterface;
   myInterface.DoSomething(…);
end;
```

What do you think About my sugestion?

**Comment by Gallimathias** [comment]
I fully support this because I and my colleagues so often face "generic" problems and push Nav to its limits. I thought the topic had already discuss here and there, but I only found the #111.

**Comment by pborring** [comment]
Closing this old suggestion as we added interface support a year ago
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al
