### ISSUE TITLE
App building and Publishing performance

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2638]
We have around 900+ objects in our app folder/project. It is taking around 2 min for building app and around 3 min for publishing. we are using containers (8 GB RAM). our VM is 32GB RAM. is it due to resources of VM/container or size of the objects? is there any way we can improve the time?

**Comment by StanislawStempin** [comment]
We have planned performance improvements for Fall release. In the meanwhile the only way to optimize it is to split the extension into two or more smaller extensions.

**Comment by AskeHolst** [comment]
Looking forward to performance improvements.
I can add that it is the deployment of the package and the following schema sync that takes the most time. Creating the package about 30sec, deploy/sync about 90sec.

**Comment by StanislawStempin** [comment]
We have made several improvements to creating the package on recent master builds. Could you please try the performance on the latest bcsandbox-master?

The publishing performance will be similar but compiling performance should be better.
