### ISSUE TITLE
Moving default data tenant from old BC build to new

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2651]
I'm trying to move data tenant from one build of bcsandbox-master to another, but I'm not sure I am applying all the steps in correct order or I am missing some. I guess the same steps should apply when moving tenant from one nav container to another.

In container A, I have tenant 'default' and installed extension. I can create SQL backup of tenant database using Backup-SqlDatabase. I'm now creating new container B and installing same extension to it's default tenant.

I want to Restore-SQLDatabase of a backup file of tenant from container A to container B and sync it, but I'm getting errors saying that either app is missing, tenant is not mounted or in sync, etc.

From that point I'm not able to re-install app, sync tenants or app. 

What are the steps of moving 'default' tenant from one BC container to another?

**Comment by cmrudolph-msft** [comment]
Simplest plan I can think of assuming the builds have minimal changes between them:

_Assuming single tenant with default tenant mode as you have said_

1. Use Export-NavData to export ONLY tenant data (-IncludeGlobalData -AllCompanies) for the specified tenant
2. Make sure the same extensions (same versions too) are published & synced on the destination service. They do NOT need to be installed there
3. Use Import-NavData to import your file into the new service with the same flags as in 1

This process assumes schema (base and extension) is identical between the two, so it will not work as a migration across versions where those kinds of differences exist.

If the move scenario involves differences, you're in more traditional upgrade territory. I do not believe you can count on this working for arbitrary master -> master builds (data upgrade paths do not exist from all builds to all other builds). However, you should be able to try something like:

1. Set up both servers as multitenant (split app DB and tenant DB)
2. Set up the destination environment with whatever extensions you will need (have them published)
3. Dismount the tenant from the source
4. Mount the tenant on the destination
5. Sync-NavTenant
6. If extension versions have changed -> Sync-NavApp on each
7. Start-NavDataUpgrade (should run upgrade code from base and extensions)
8. Tenant should be operational

**Comment by ivandjordjevic** [comment]
@cmrudolph-msft Thanks for the detailed steps provided. 

The first scenario mentioned might be hard to pull of because of all the Microsoft's extensions already published, and they have different versions as well on two builds. It's also unlikely that we will have our extension with same version running on two different base app builds.

Import-NavData breaks as soon as it detects different app versions between apps on source and destination, and not to mention that base app schemas are different. This might work only in case where we need to transfer data between two environments on same build.

I think we fall into second scenario you mentioned, where data tenant is dismounted from one build and mounted to destination build (that has recent base app and extensions installed). Since we are talking here about two different BC containers, along with steps Dismount tenant from source and mount tenant to destination (Steps 3 & 4), I would need to first do SQL-Backup of source tenant and restore it to destination container, (where build01 and build02 are two BC containers running on different builds with same apps installed but different version):

````
Enter-NavContainer build01

Backup-SqlDatabase 
  -ServerInstance "BUILD01\SQLEXPRESS" 
  -Database "test" 
  -BackupFile "C:\Run\my\test.bak"
````
After moving .bak file into new container, I can successfully restore tenant db into new environment: 
````
Enter-NavContainer build02

Restore-SqlDatabase 
  -ServerInstance "BUILD02\SQLEXPRESS" 
  -Database "test" 
  -BackupFile "C:\Run\my\test.bak" 
  -ReplaceDatabase 
````
However, when I try to mount this database to new application:
````
Enter-NavContainer build02
Mount-NavDatabase  
  -DatabaseServer "build02" 
  -DatabaseInstance "SQLEXPRESS" 
  -ServerInstance "NAV" 
  -DatabaseName "test" 
  -TenantId "test"
````

I receive this message:

````
Mounting Database for template on server BUILD02\SQLEXPRESS
Mount-NAVTenant : The tenant template could not be mounted because the following installed NAV extensions are missing, matching content could not be 
found, or have a higher version than those that are published and synchronized: "My Solution" by Ivan, version 11.19281.1.1.
At C:\Run\HelperFunctions.ps1:360 char:5
+     Mount-NAVTenant -ServerInstance $ServerInstance `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Mount-NAVTenant], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/template,Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant
````

Even though I see my extension installed in both containers (in this case I have same app version):

````
ServerInstance : MicrosoftDynamicsNavServer$NAV
PSComputerName : da0e390e74629475ede654ccbc9383327a3619eddc5a2974596d83521c577871
RunspaceId     : 1b4f72f2-d68b-4e96-81b5-72e7ef62e7b8
AppId          : xxxxx-xxxx-xxxx-xxxx-xxxxxxx
Name           : My Solution
Publisher      : Ivan
Version        : 11.19281.1.1
ExtensionType  : ModernDev
Scope          : Global
````

**Comment by cmrudolph-msft** [comment]
If the extension is published on both services, the rules for successful binding on mount are:

**Older Version**
Not allowed for obvious reasons.

**Newer Version**
Always allowed - will mount into a state requiring a sync & upgrade to become operational.

**Same Version**
Allowed as long as the content of the package is the same. This means one of two things must be true. Either the package ID must be the same (a byte-for-byte match) or the internal content hash must match (a rebuild of package but with identical contents). Both of these values can be inspected by looking in the NAV App table in the app DB. **If you aren't sure about the exact content state, can you check these values?**

If your case involves a content change, you must change the version for the package to be bound successfully on the new service.
