### ISSUE TITLE
Translation error: User Experience "Premium" is "Paid-in surplus" in Spanish.

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#2652]
I don't know if this is the right place to report it, but...

I guess someone translated Premium without context, and in Spanish we can choose between "Basic", "Essential" and "Paid-in surplus" user experiences.

It is incredibly funny (when read in Spanish, at least), but it also makes it look like that no-one in Microsoft Spain has ever used this option, and that doesn't give much confidence.

**Comment by salgiza** [comment]
Note: I found this error in the current sandbox version.

**Comment by StanislawStempin** [comment]
Thanks, I will pass it on to the owning team. I'll not track it here since this repo is only used for AL development and app extensibility related issues.
