### ISSUE TITLE
Error when debugging extension

### ISSUE THREAD

**Issue by JuanJesus14** [Microsoft/AL#2654]
Hello, I am developing an extension for business central, and after making several changes and debugging several times, I have given the following error message, I do not know the reason. Can you indicate what happens? Thank you.

The Visual Code version is 1.24.1

[Error - 18:09:39] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Referencia a objeto no establecida como instancia de un objeto.'
StackTrace:
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetBoundOptionValueOrdinal(BoundEqualsPropertyExpression expression) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 149
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetConstConditionValue(BoundEqualsPropertyExpression expression) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 241
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteFilterAttributes(XmlWriter writer, BoundEqualsPropertyExpression equalsExpression, String filterValueAttribute, String filterTypeAttribute, String filterGroup, Boolean isCondition) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 294
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass1_1.<WriteTableFilters>b__0() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 51
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:línea 24
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteTableFilters(XmlWriter writer, Boolean isCondition, String metadataElement, BoundTableRelationConditionExpression tableRelationExpression, String filterGroup) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 49
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__1() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 78
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:línea 24
   en Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__0() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:línea 76
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:línea 24
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.TryUseSpecialPropertyValueMetadataEmitter(XmlWriter xmlWriter, PropertySymbol property) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:línea 127
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter.WritePropertyValueMetadata(XmlWriter xmlWriter, PropertySymbol property) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitter.cs:línea 50
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteElementProperties(XmlWriter xmlWriter, IEnumerable`1 properties, Action`2 writePropertyMetadata) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:línea 58
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.<>c__DisplayClass4_0.<WriteField>b__0() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:línea 47
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:línea 24
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableExtensionMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableExtensionMetadataEmitter.cs:línea 45
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:línea 36
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitMetadata(ObjectTypeSymbol containingType) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 251
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 234
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass16_0.<CompileObjectAsTask>b__0() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 211
   en Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:línea 150
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 161
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 145
   en Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:línea 816
   en Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:línea 791
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 551
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 414
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 313
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:línea 32
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() en C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:línea 59

**Comment by JuanJesus14** [comment]
I have already seen what happens, in the field "Source subtype" of table 336 I had assigned as CONST and that causes the error to occur, when changing it to FILTER it no longer gives the error. Thank you.
This is the error
CalcFormula = Sum("Reservation Entry"."Quantity (Base)" WHERE ("Source Type"=CONST(5741),
                                                                                    "Source Subtype"=FILTER(0),
                                                                                    "Source ID"=FIELD("Document No."),
                                                                                    "Source Ref. No."=FIELD("Line No.")));
Corrected
CalcFormula = Sum("Reservation Entry"."Quantity (Base)" WHERE ("Source Type"=CONST(5741),
                                                                                    "Source Subtype"=FILTER(0),
                                                                                    "Source ID"=FIELD("Document No."),
                                                                                    "Source Ref. No."=FIELD("Line No.")));

**Comment by kalberes** [comment]
Can you please try this on a newer AL version. I have no repro on this on the latest version

**Comment by svwfr** [comment]
Yes, it Works With "Compiler version 0.12.28462". Is there any issues to mix the VSIX build With NAV server build? I only updated vsc to cu8, but leaved the nav-platform at cu6.

**Comment by kalberes** [comment]
Yes it is. VSIX versions work (safely) with their corespondent server versions. That said you maybe lucky, but it is not advised.
 From the "July" AL extension (13.xxxx) version you would actually get compiler errors if there is a version mismatch between the server and what the Al extension would support.
