### ISSUE TITLE
Function-Expose Request in COD5407 - Prod. Order Status Management

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/AL#2655]
Hi Team,

Could we make this function "ChangeStatusOnProdOrder" as 'External' in CU5407 - Prod. Order Status Management.

Thanks!

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! I've got good news for you :-) ChangeStatusOnProdOrder in CU5407 has already been exposed. The change should be visible in the latest developer preview. The change is not automatically backported to earlier releases. For more info on our branching strategy, please refer to https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/.

**Comment by anuj-inecta** [comment]
Great, thanks for the update..!!
