### ISSUE TITLE
CurrPage.Control.Activate?

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#2657]
In some scenarios, we want to be able to activate a specific field / control on a page. Before the Windows client, we had the controlName.Activate command, in Windows client we could  misuse the SendKeys in some scenarios. Using QuickEntry did not always provide a solution. What about the WebClient / BC? Any plans to support CurrPage.Control.Activate again?

**Comment by StanislawStempin** [comment]
I received a reply from the owning team:

We do not have plans to support this A/L construct in the future. Introducing the ability to set focus from application code has to be carefully considered, as the users should not experience that the focus changes unexpectedly.

Could we get more information about the scenarios where SENDKEY is needed ? 
We have plans for adding QuickEntry capability to the web client and we would appreciate the feedback on how this feature can be improved further.
