### ISSUE TITLE
Please provide System.Text.RegularExpressions.Regex and MatchCollection

### ISSUE THREAD

**Issue by megel** [microsoft/AL#266]
For some reason we use Regex to Validate, Split and Repleace text by complex expressions.

> Name := RegEx.Replace(Text, '[^a-zA-Z0-9_\w]', ' ');

>FOREACH Item IN RegEx..Split(Line, ';|#') DO
>BEGIN
>  // ...
>END;

**Comment by StanislawStempin** [comment]
Thanks, this is on our backlog.

**Comment by bvbeek** [comment]
Need this too

**Comment by DanielGoehler** [comment]
Would be very nice, e.g. for an advanced check if the E-Mail Address is valid:

```
procedure CheckValidEmailAddress(EmailAddress : Text);
  var
    RegEx : DotNet "'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Text.RegularExpressions.Regex";
    RegExOptions : DotNet "'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Text.RegularExpressions.RegexOptions";
    RegExPattern : Text;
  begin
    RegExPattern := '\A(?:[a-z0-9!#$%&''*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z';
    if not RegEx.IsMatch(EmailAddress, RegExPattern, RegExOptions.IgnoreCase) then
      ERROR(InvalidEmailAddressErr,EmailAddress);
  end;
```

**Comment by FSharpCSharp** [comment]
Is there anything new about this issue? We would also need access to these classes. That would be very helpful for many problems.

**Comment by StanislawStempin** [comment]
No updates yet. It is still on the backlog

**Comment by josnelissen** [comment]
We also use RegExReplace and RegExMatch for Enrichment of Ebanking (Dutch localization). So it would be very welcome so we can upgrade to extension

**Comment by pjanfred** [comment]
We would also need this for complex validations. It is very well suited to validate the parameters of REST APIs on the client side. I am looking forward to hearing about the current status.
