### ISSUE TITLE
Page Metadata Bug with additonal records

### ISSUE THREAD

**Issue by twityde** [Microsoft/AL#267]
If you add a page field based on an other record from a global variable, NAV tries to find the field ID in the source table. Attached you get an sample project. I tried to build an Wizard page and added the images from the media repository. If i start the page ii get the following error:
> The supplied field name '3' cannot be found in the '70000000' table.

If I remove the SourceTable expression the page will work.
[SampleWizard.zip](https://github.com/Microsoft/AL/files/1060918/SampleWizard.zip)

Callstack from Eventlog:

> Server instance: Navision_main
> Category: Runtime
> ClientSessionId: e221b495-f3d0-4c3c-b752-182636bd40e4
> ClientActivityId: 83e65d27-c685-4493-b04b-1c34ebc78907
> ServerSessionUniqueId: 4d062354-e58f-4252-88d3-0f5cb2236018
> ServerActivityId: 438fe4fd-c743-4e33-899c-c4d3ec714235
> EventTime: 06/08/2017 12:04:00
> Message <ii>(NavMetaFieldNotFoundException): <ii>The supplied field name '3' cannot be found in the '70000000' table.
> ExceptionStackTrace:
>    at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPageDependencies(MasterPage page, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip)
>    at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAllItsDependencies(Int32 pageId, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip)
>    at SyncInvokeGetMetadataForPageAndAllItsDependencies(Object , Object[] , Object[] )
>    at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
> CallerStackTrace:
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass9_0.<PerformanceCounterCombinator>b__0()
>    at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationDuration(Stopwatch stopWatch, Action action)
>    at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationAction(Action action, NavSession session)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
>    at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
>    at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
>    at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
>    at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
>    at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
>    at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
>    at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 
> </ii></ii>
> ProcessId: 3380
> Tag: 00000HC
> ThreadId: 82
> CounterInformation:

**Comment by StanislawStempin** [comment]
I cannot reproduce it on the latest codebase. Let's keep the issue open until you have a chance to retest on June Update.

**Comment by dennisfrostlander** [comment]
Yes, this has been fixed already. Will be available in the next update.

**Comment by twityde** [comment]
Perfect.
I will retry it on the June Update

**Comment by twityde** [comment]
Perfect!
I will retest it on the June Update.
