### ISSUE TITLE
Subpage not updating after creation new record in Web client

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#2674]
Hi. I want to create an extension that will add Default dimensions part to Item Card, and after the creation of new item from the template will fill default dimension for that item and show on that subpage.

The problem is that after the creation of new item card from a template -> subpage is not updating. I need to close and open item card or make item card non-editable and the editable to see a record in a subpage. 

This problem occurs only web client.
Windows client works as expected.

A code example is here https://github.com/dkatson/AL-Test-SubPage

However, another question here, how to make an added subpage collapsed in a web client?

Scenario.
Step 1. Create new Item, choose a template (Dimensions for template should be setup)
![image](https://user-images.githubusercontent.com/29101017/41708410-35f275f0-7549-11e8-87c3-ef159b17a4c2.png)

Step 2. Look at Default Dimensions tab (it's blank)
![image](https://user-images.githubusercontent.com/29101017/41708485-6924511e-7549-11e8-8db7-8457efe8b079.png)

Step 3. Make item card non-editable (record appears)
![image](https://user-images.githubusercontent.com/29101017/41708527-7d69a084-7549-11e8-94aa-a94493054a54.png)

**Comment by thpeder** [comment]
Hi @dkatson,
In order for the Item Card to be updated, CurrPage.UPDATE should be called after the item is created. In the WIndows Client it works due to RefreshOnActivate functionality.
