### ISSUE TITLE
Personalization cannot be enabled due to technical issue

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2688]
We are getting below error while trying to use "Personalize" option. We are using tenant based profiles. Is it something to do with that?

 Personalization cannot be enabled due to technical issues. Try again later , or contact system administrator.

**Comment by StanislawStempin** [comment]
We would need more information to investigate this issue.

Which versions of AL and server are you using?  Which type of environment and what exactly steps you took that lead to this error?

**Comment by pmohanakrishna** [comment]
Build 21812

Al compiler 0.15.18771
Docker environment.

we created new profile manually in database.
and added it to User Personalization.

**Comment by StanislawStempin** [comment]
Can you please try with a profile created in AL and uploaded as part of an extension? 
See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object

**Comment by pmohanakrishna** [comment]
Didn't use profile object but directly created record in profile table while installing the extension and it worked.
it looks like we cannot use personalization if we create new record in database manually.

**Comment by pmohanakrishna** [comment]
If we use Profile object then it is creating as Scope= tenant profile and again we cannot use personalize option.
