### ISSUE TITLE
By-reference (var) is not observed in event signatures

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#269]
Subscribing to an event publisher that includes a by-reference parameter in its signature will accept subscribing both with or without the "var" keyword.

So, this is valid (as expected):

    [EventSubscriber(ObjectType::Page,21,'OnOpenPageEvent','',false,false)]
    local procedure OnCustomerCardOpen(var Rec: Record Customer);
    begin
    end;

... but this is valid, too (which shouldn't be the case):

    [EventSubscriber(ObjectType::Page,21,'OnOpenPageEvent','',false,false)]
    local procedure OnCustomerCardOpen(Rec: Record Customer);
    begin
    end;

**Comment by StanislawStempin** [comment]
This is actually by design. Do you see any adverse side-effects of not specifying the var keyword?

In this piece of code, if you do specify var on the subscriber the message shown will be 11, if you don't specify var the message shown will be 10.

```
page 70700000 SomePage 
{
    trigger OnOpenPage();
    var 
       c : codeunit Publisher;
    begin
        c.Run();
    end;
}


codeunit 71000001 Publisher {

    trigger OnRun();
    var
        i : integer;
    begin
        i := 10;
        RaiseEvent(i);
        Message(Format(i));
    end;

    [Integration(false, false)]
    local procedure RaiseEvent(var i : integer);
    begin        
    end;    
}

codeunit 70000002 Listener
{
    [EventSubscriber(ObjectType::Codeunit, 71000001, 'RaiseEvent', '', false, false)]
    procedure Test(i : integer);
    begin
        i := 11;
    end;
}
```

**Comment by StanislawStempin** [comment]
Note that the opposite case is verified. You cannot add "var" keyword to a publisher parameter that doesn't specify "var".

**Comment by vjekob** [comment]
Yes, you are right. There are no actual adverse effects of omitting "var". I was thinking far too much from C# shoes :) Also, Arend-Jan pointed me to a slide-deck where this is explicitly stated, so I stand corrected. Sorry for bugging you, and thanks for taking time! I'll close this now.
