### ISSUE TITLE
[Event Request] New Events in Page 232 and 233

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#2690]
Some events are required in Page 232. Furthermore, some of the functions must also be externally callable to be able to map certain functionalities.

![p232_handlechosenentries](https://user-images.githubusercontent.com/22373356/41723536-b1fd44f0-756b-11e8-882f-ee950285b04d.png)

The following functions must be externally callable.

- ExchangeAmountsOnLedgerEntry
- CheckRounding

The same functionalities must be made available in the same way on page 233.

![p233_handlechosenentries](https://user-images.githubusercontent.com/22373356/41723836-65290ce4-756c-11e8-945d-98d849856ace.png)

**Comment by FSharpCSharp** [comment]
I just noticed that I made a mistake when applying for these events. There are simply no parameters without which the event doesn't make sense, because you can't overwrite everything completely.

For this reason, here is a rework. I need the following parameters in this event, so that everything really works.

```
Type: Option Direct,GenJnlLine,SalesHeader; 
CurrentAmount: Decimal; 
CurrencyCode: Code[10]; 
PostingDate: Date; 
VAR AppliedCustLedgerEntry: Record "Cust. Ledger Entry"; 
VAR IsHandled: Boolean;
VAR FromZeroGenJnl: Boolean;
VAR CanUseDisc: Boolean;
VAR CustLedgEntry: Record "Cust. Ledger Entry";
VAR GenJnlLine2: Record "Gen. Journal Line";
VAR PossiblePmtDisc: Decimal;
VAR PmtDiscAmount: Decimal;
VAR AppliedAmount: Decimal;
VAR CorrectionAmount: Decimal;
VAR RemainingAmountExclDiscounts: Decimal;
VAR OldPmtDisc: Decimal;
VAR DifferentCurrenciesInAppln: Boolean;
VAR ApplnCurrencyCode: Code[10]);     
```

Furthermore, I slipped through a function, which is on the page, and which must also be callable by external, so that everything works.

`CalcOppositeEntriesAmount`

I apologize for the inconvenience. Please improve on these two events. Unfortunately, I didn't think enough.

**Comment by FSharpCSharp** [comment]
@thpeder 
I have seen that the events already exist in the daily BC builds. But unfortunately it contains the wrong variant, with too few parameters. For these events I absolutely need the parameters described in the article above, otherwise I cannot overwrite the function. What good is it that I can overwrite the functionality, but the new values are not displayed to the user, or are used for other calculations. Is there already a plan whether the event adaptations will be taken over soon? I only need it as fast as I can. I'm sorry I overlooked on the original request that a lot more parameters were needed to ensure a complete overwrite.

**Comment by StanPesotskiy** [comment]
@FSharpCSharp 
Both pages are built on global variables, so we tend to think of including the sender and giving global variables access instead of adding 10+ parameters tightly coupled to existing implementation that you are going to overwrite. Will it resolve your issue?
CalcOppositeEntriesAmount will become external as requested.

**Comment by FSharpCSharp** [comment]
@StanPesotskiy 
How you solve this technically doesn't matter to me in principle. The main thing is that I can extend and overwrite the existing functionalities accordingly. Of course this is unfavorable with so many parameters. To the completeness I have once everything needed with indicated.

Can I expect the adjustment here in the coming days? That would be really great! :-)

**Comment by StanPesotskiy** [comment]
@FSharpCSharp
Unfortunately this fix hasn't made it to the Update 18 that was branched last week. It will be part of the next update.
Please verify that the changes we have done to PAG232 and PAG233 resolve your issue.
1. Exposed CalcOppositeEntriesAmount:
`    [External]`
`    PROCEDURE CalcOppositeEntriesAmount@17(VAR TempAppliedCustLedgerEntry@1000 : TEMPORARY Record 21) Result : Decimal;`
2. Added Sender and access to global variables for  OnBeforeHandledChosenEntries:
`    [Integration(TRUE,TRUE)]`
`    LOCAL PROCEDURE OnBeforeHandledChosenEntries@23(...);`

**Comment by FSharpCSharp** [comment]
@StanPesotskiy 
Looks great! Thank you for adapting and implementing my request! I like this solution even better than my own proposed one!
