### ISSUE TITLE
Question: Wrapping Methods (Feature)

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/AL#2696]
Good day,

Is Method Wrapping going to be introduced at some point, like what I understand is being used in AX?

i.e. That you write a method with the same signature as an existing method,
and a property that indicates to execute before or after the existing method.

This would imply that a CodeunitExtension object type become available.

Kind Regards,

Ewald

**Comment by StanislawStempin** [comment]
We currently have no plans to introduce that functionality. It is mostly a syntactic sugar on top of event subscription. If you have a scenario that cannot be solved by using existing or adding new events we would be interested to look at that case and see what we can do.

**Comment by ewaldventer** [comment]
The only reason would be to avoid modifying standard objects in order to add publishing events.
Actually, this doesn't apply to just codeunits, but methods on any object type. 

Happy with adding new events.
Thank you.
