### ISSUE TITLE
Suggestion: Please review 'FillInvPostingBufferPrimaryKey' on Table 49 [IT]

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2699]
Table 49 Invoice Post. Buffer in the W1-Version has a composite primary key with all the various fields that the bufer is to be grouped by. In the italian localization this key must've become too lare, as they have added a new field `Primary Key [Text250]` that is the new primary key. The following method on that table is used to generate the primary key of the record.

````
FillInvPostingBufferPrimaryKey()
TypeValue := Type;
RefersToPeriod := "Refers to Period";
"Primary Key" :=
  FORMAT(TypeValue) + "G/L Account" + "Gen. Bus. Posting Group" + "Gen. Prod. Posting Group" +
  "VAT Bus. Posting Group" + "VAT Prod. Posting Group" + "Tax Area Code" + "Tax Group Code" +
  FORMAT("Tax Liable") + FORMAT("Use Tax") + FORMAT("Dimension Set ID") + "Job No." +
  FORMAT("Fixed Asset Line No.") + "Deferral Code" + "Service Tariff No." + FORMAT("Related Entry No.") +
  FORMAT("Include in VAT Transac. Rep.") + FORMAT(RefersToPeriod) + "Contract No.";
````

It basically generates a composite key made up from all the various fields that the buffer has to be grouped by. Needless to say that this is a little ugly and pretty hard to extend.

So here my suggestions:
1. Do not use the primary key to group the buffer. Use a simple PK like `Entry No.` or similar, and implement the grouping logic through filters and code (or similar).
2. If this is too tricky, at least provide us with some event that let's us extend the generation of that primary key. Like `OnAfterFillPrimaryKey` that is called at the end of that method.
3. I know that this is about a localization, and I don't know how it will look, once (and if ever ...) IT becomes available as extension. But please keep this situation in mind.

**Comment by sgiordy** [comment]
Hi @hemisphera see #2499

**Comment by hemisphera** [comment]
Yes, @sgiordy, this makes this table extensible and matches with my suggestion, I agree. But it is ugly design nontheless. This is one classical example where a native hash function (be it MD5 or SHA1 or SHA256 or whatever, does not really matter here) would be handy. Should I ever need to add a field that exceeds the Text250 limit I am pretty much out of options. Wheras hashing things up would at least eliminate the length restriction.
