### ISSUE TITLE
Question: TryFunction attribute

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#270]
When I try to create a TryFunction, I get a compiler error stating that it cannot be used for extension development.

Is this just a temporary consequence of the AL Language still being in development, or is it a permanent decision that there will be no TryFunctions in extensions at all?

**Comment by esbenk** [comment]
We haven't enabled it yet. We are considering what the syntax should like. The attribute style syntax used by .txt files seems a bit odd for this.

**Comment by vjekob** [comment]
Thanks. That's the answer I hoped for :)
