### ISSUE TITLE
Error on publishing: Value cannot be null

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2703]
The request for path /XXX/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Value cannot be null.
Parameter name: value

I'm getting the standard error above. Anyone got this before? The projet seems to have no errors but this log message appears on debug console after trying to publish the project.

**Comment by DominikDitoIvosevic** [comment]
Hi @martinhocosta88. We need more information to be able to find out what is the issue.
What are your platform and compiler versions? How big is your extension? Have you been able to publish that extension before?

**Comment by martinhocosta88** [comment]
Hello,

I'm developing in vscode 1.24.1 with Al Language Extension 0.15.18771 over a Dynamics NAv 2018 CU06 instance.
I was able to publish the app before. It has 38 Objects/Objects Ext. Previously the App had around 30... after I included and developed the last 8 around I started to get this feedback from the debug console.

**Comment by StanislawStempin** [comment]
The AL Language that you're using is not for NAV. It is for Business Central.
For NAV 2018 you need to use the AL Language that comes bundled on the product DVD.

**Comment by martinhocosta88** [comment]
Thank you Stanislaw... I've been alternating between both. Somehow vs code was not reloading for the "new" Al Language Extension uploaded. Had to restart and change. Thanks a lot!
