### ISSUE TITLE
Will Object ID continue to be a field in object tables?

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#2705]
We have some cases where we run codeunits based on their ID, so that it can be configured by the user in settings somewhere. 

`Codeunit.Run(Settings.codeunitID);`

There have been mentions of object IDs going away. Is that still happening? If it is, will there be an alternative to the above?

**Comment by StanislawStempin** [comment]
IDs are not going away any time soon. For now you should continue using this approach.
