### ISSUE TITLE
Regarding #2631 

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/AL#2708]
Regading 1.
In ver .BC Version 12.2.22782, we still have no external and visibility 
And 
Microsoft (R) AL Compiler version 0.16.21713
Copyright (C) Microsoft Corporation. All rights reserved

c:\Users\bcdelv\Documents\AL\AutoTask\Codeunit\Cod61063.ATMapInvoiceToSalesDoc.al(292,47): error AL0296: The type or method 'EvaluateValueWithValidate' cannot be used for 'Extension' development.
Error: The package could not be created.

**Comment by JesperSchulz** [comment]
I just checked once more. The function was exposed on 4th of April. Please allow me to refer to https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github once more. All fixes addressed through this forum, will only be implemented in the main branch and will be released with the next major release. For development, you can pull the latest developer preview (version 13.0.22913.0), which contains the fix (given that you are in the Ready2Go program - more info at  http://aka.ms/ReadyToGo). If you need the fix to get backported, please find the instructions in the previously mentioned blog post. I hope this clarifies why you cannot find the fix in version 12. If you have further questions, please re-open this issue and I'll try to elaborate :-)

**Comment by clausmacali** [comment]
Thanks Jesper, we tried with the ver 12. 

As you are reffering to ver 13. when do we have a release

**Comment by JesperSchulz** [comment]
According to the blog post, "Business Central will ship one major release every 6 months." The previous release was in April :-) You can hence expect a release somewhen this fall - October if all goes according to plan.
