### ISSUE TITLE
Boolean constants must be uppercase when used in expression properties

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#271]
When you attempt to use Boolean constants true and/or false inside expression properties, they must be spelled in uppercase. Any other case will be rejected at runtime with message saying that identifier could not be found, like this: "The identifier 'true' could not be found"

For example:

pageextension 70770077 CustomerListExt extends "Customer List"
{
    layout
    {
        modify("Phone No.")
        {
            Visible = MyBool = true;
        }
    }

    var
        Mybool : Boolean;
}

Changing the property value from "MyBool = true" to "MyBool = TRUE" suddenly works.

I know that there is no real reason why anyone would want to use Boolean constants in expression properties, but still the language should be consistent.

**Comment by esbenk** [comment]
I think it is the client side evaluation that is the problem. It is a bug.

**Comment by StanislawStempin** [comment]
This is fixed in the upcoming June Update.
