### ISSUE TITLE
Testautomation limitation in AL Langauage

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#2710]
Hi ,
I have a doubt that although i am able to run test automation from windows client why because when i tried to run from webclient then the session is closing, Is there any limitation to AL test automation that we should only use the windows client ?

Please suggest ASAP

**Comment by thpeder** [comment]
I received a reply from the owning team:
Currently we don't support the web DT in the Test A/L language. This is an unfortunate limitation that we need to address in the future releases.

**Comment by ashik-ivor** [comment]
First, check whether the normal web client (create a sales invoice) is working or not. 
If it works and still test tool does not work, then there is some problem with the code in the test codeunit.
