### ISSUE TITLE
Make standard function external

### ISSUE THREAD

**Issue by bogdan81GitHub** [Microsoft/AL#2712]
In build 13.0.22621.0 -nl we need to make the function  InsertStep from codeunit 131101 Library - Workflow external so it can be used in some extension (test codeunits).
Thank you.

**Comment by JesperSchulz** [comment]
Thank you very much for your request!

Unfortunately, we cannot accept your request to expose the InsertStep function, as that function is (and should remain) local. Please use the already exposed InsertEntryPointEventStep, InsertEventStep, InsertResponseStep or InsertSubWorkflowStep functions, which are the public functions for inserting steps. If you need to insert into the WorkflowStep table directly for some reason, please create helper function of your own.

We are trying not to expose local functions, unless there is a really good reason, as every exposed function reduces our ability to refactor and improve our code base. If you have a good reason for why this function should get exposed, please reopen this issue and I will have another look!

Thanks again for your suggestion. I hope you understand why we cannot implement it.
