### ISSUE TITLE
ERROR : Unable to load DLL 'vmcompute.dll' - unable to add FIN user to test my app

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#2715]
Hello @freddydk , 

used below command to spin up my docker container,

`**New-NavContainer -containerName Sachin20180625 -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:us -includeCSide -memoryLimit 3G -restart no -shortcuts Desktop -updateHosts -useSSL**`

everything till here is great.

Now to test my app with **FIN user**,  to do this I've to add a **new** user to my container **Sachin20180625**. Used below command 

`**PS C:\WINDOWS\system32> Setup-NavContainerTestUsers -containerName **Sachin20180625****
cmdlet Setup-NavContainerTestUsers at command pipeline position 1
Supply values for the following parameters:
Downloading C:\Users\SACHIN~1.CHA\AppData\Local\Temp\CreateTestUsers.fob
New-PSSession : Unable to load DLL 'vmcompute.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
At <C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.9.0\ContainerHandling\Get-NavContainerSession.ps1:37> char:24
+ ...  $session = New-PSSession -ContainerId $containerId -RunAsAdministrat ...
+ CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
+ FullyQualifiedErrorId : CreateRemoteRunspaceForContainerFailed,Microsoft.PowerShell.Commands.NewPSSessionCommand`

Please suggest steps to resolve error : **_Unable to load DLL 'vmcompute.dll': The specified module could_** not be found. 

Thanks in advance.

Regards,
Sachin Chavan

**Comment by freddydk** [comment]
Please post docker related issues on https://github.com/Microsoft/nav-docker/issues or https://github.com/Microsoft/navcontainerhelper/issues (if navcontainerhelper).
For this one - your commands are correct - I have run them both - works as a charm.
Are you running the Setup-NavContainerTestUsers in an administrator Powershell prompt?

**Comment by tfenster** [comment]
@chavansachin20 had this problem on the machine of a colleague and there disabling and then enabling the Containers feature in Windows again has helped

**Comment by chavansachin20** [comment]
@freddydk , yes, I'm running PS as run as Administrator mode.
![image](https://user-images.githubusercontent.com/5293496/41900030-616d80ca-794b-11e8-9a99-746b74d51714.png)

@tfenster : can you provide details how to _disable and then enable the Containers feature in Windows_.

**Comment by tfenster** [comment]
@chavansachin20 Go to "turn windows features on or off" in the control panel or something like that (not sure about the exact english caption) and turn feature Containers off, then restart. Open it again, turn feature Containers on and restart

**Comment by chavansachin20** [comment]
thanks @tfenster, followed same steps, but still facing error while using command.

tried all my steps in another Win10 machine and as @freddydk said, it worked for me.

I'm still analysing the issue and will update if solution found. As of now I'm not blocked for testing against FIN user / Essential user.  
Thanks @freddydk  / @tfenster .

Regards
Sachin Chavan

**Comment by chavansachin20** [comment]
while executing command : Setup-NavContainerTestUsers -containerName Sachin20180625
open you Power shell with normal mode (No run as admin option)
