### ISSUE TITLE
WebService wsdl call from VisulStudio fails

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#2719]
This bug cost me a lot of nerves!

I had a WebService in a codeunit like this:

```JavaScript
codeunit 50100 WebService
{
    procedure DoSomething(query: Text; var result: Text);
    var jObject: JsonObject
    begin
       if not jObject.ReadFrom(query) then exit;

       // Do some other stuff ….
    end;
}```


However - this webservice is published by using these XML:
```XML
<?xml version="1.0" encoding="utf-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>CodeUnit</ObjectType>
            <ServiceName>DoSomething</ServiceName>
            <ObjectID>50100</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

When you use Visula Studio or `?wsdl` to discover the WebService you get this error:

Browser: 

`https://myappon.azure.com:7047/NAV/WS/CRONUS%20USA%2C%20Inc./Codeunit/DoSomething?wsdl`

the result was:

`a:Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLNotSupportedTypeExceptionThe type JsonObject is not supported.The type JsonObject is not supported.`

my current solution is to wrap the call in a seperate Codeunit like this:

```JavaScript
codeunit 50101 WebService2
{
    procedure DoSomething(query: Text; var result: Text);
    var mgt: Codeunit "Intent Handler ccAI";
    begin
        mgt.HandleIntent(query, result);
    end;
}
```
and Register with:
```XML
<?xml version="1.0" encoding="utf-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>CodeUnit</ObjectType>
            <ServiceName>DoSomething</ServiceName>
            <ObjectID>50101</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

OK - the big Question is: Why `JsonObject` is not supported?

My versions:
Microsoft (R) AL Compiler version 0.15.18771
Copyright (C) Microsoft Corporation. All rights reserved

![image](https://user-images.githubusercontent.com/15800069/41874461-49aa8e48-78c8-11e8-90b6-2eeee77ea14f.png)

**Comment by megel** [comment]
Oh, I found my mistake!

I have added a second method to my webservice which uses a `JsonObject` as Parameter:

```JavaScript
codeunit 50100 WebService
{
    procedure DoSomething2() result : JsonObject;;
    begin
       // … some code
    end;
}```


Maybe there should be a sugesstion / warning from Compiler, when such a codeunit is registered as WebService.

**Comment by thpeder** [comment]
Thanks for the feedback, we have created a ticket for the backlog and will look into improving it.
