### ISSUE TITLE
Question: Multiple Invoice Posting rollback feature

### ISSUE THREAD

**Issue by zuhadmahmood** [Microsoft/AL#2720]
Hi,
I have a scenario in business central that i could not figure out how to achieve
the scenario is of sales and purchase invoice posting automation that for each sales invoice created and posted by my AL code i have to create its related 2 different purchase invoices and post them. i have successfully mapped this scenario,

but the issue is that for this situation there a requirement that if any of the invoice failed to post due to any error the other 2 invoices should be rollback.

I have tried using the commit command along with error command to achieve this. but it won't work in case if the first 2 invoices are posted and the last invoice will have any error.in that case it does not rollback the previously created other 2 invoices (1 of sales and 1 of purchase).

This situation is the key problem in my case and i really need to resolve this issue.

Thanks

**Comment by zuhadmahmood** [comment]
Hi, i have successfully mapped a solution of this issue using preview post and assert error and tested it on sandbox. but i am not able to deploy this package on production environment due to error "Package validation failed".Is this due to assert error function ? because  when i run code analyzer it shows warning on that line "Only use ASSERTERROR in Test Codeunits."

I really need this feature to be done by this week as my golive date is close. 

Thanks.

**Comment by zuhadmahmood** [comment]
Hi @dennisfrostlander, 
Thanks for the reply 
 **"When you add an explicit commit, then yes, if the error happens after the commit, the previously committed data will not be rolled back."**
 yes this won't work in my case . 

my issue is that let say  I've written a code for my client to automate the sales cycle for which i need to call code unit **"Sales-Post"** and after that i need to call code unit **"Gen. Jnl.-Post Line"**.
but the only problem i am facing is that there is nothing i can do to handle the exception and revert the **"sale-post"** code if  **"Gen. Jnl.-Post Line"** code failed.

Not sure if in C\SIDE **try function** can work for this. and also i could not find try function on AL.

Hope you completely understand my issue.Perhaps if it is possible i can contact you on Skype call to completely demonstrate my issue. 

thanks.

**Comment by dennisfrostlander** [comment]
If you don't want to commit in sales-post, you can try calling `SetSuppressCommit`.

P.S. Please also note that this is a repository for development tools issues for the latest developer preview environment. There are very few people here who could advise on specific functionality of the application itself.
