### ISSUE TITLE
Accessing table fields from another extension

### ISSUE THREAD

**Issue by mtaanquist** [Microsoft/AL#2722]
- AL Extension Version: 0.16.16948
- Server Version: DK Dynamics NAV 11.0 (22292)

With a recent NAV update, certain fields used in Danish payments for Vendors [were moved from the table to extensions](https://docs.microsoft.com/en-us/dynamics-nav/deprecated-fields). 

I'm now trying to build an extension that reads the value from the field "Giro Acc No.", but I'm not able to see it in a Vendor record variable.

Is this intended, or am I missing something in the symbols I download from the server?

If it is intended, how am I supposed to use these fields that were previously standard fields in an extension? RecordRefs and FieldRefs?

**Comment by thpeder** [comment]
Hi @mtaanquist,
You need to declare in your app.json that you take a dependency on the extension, which will then require you to download the symbols for that extension afterwards.
```
  "dependencies": [
    {
      "appId": "644f7e5b-a81c-408a-aaa2-766e655a80a3",
      "name": "Payment and Reconciliation Formats (DK)",
      "publisher": "Microsoft",
      "version": "1.0.0.0"
    }
  ]
```

**Comment by mtaanquist** [comment]
Hi @thpeder,

Thanks for the answer, that's very helpful! Is there a specific way to find the `appId`, other than looking into the "NAV App" table?

Cheers!

**Comment by thpeder** [comment]
There is a Powershell command to get all the published extensions: `Get-NAVAppInfo`

**Comment by mtaanquist** [comment]
Thank you for the assistance. I'll close out the issue. 😊
