### ISSUE TITLE
Adding features to HelpLink Property

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/AL#2726]
Hi, as far as I know there is no possibility for including a parameter to the helplink as e.g. the PageID, right?
When pressing help (Ctrl + F1) I'm directly redirected to the defined help URL.  So it would be nice to have the Page ID or Page Name included (for example with %1 or something like that).

Another nice possibility would be not only to enter static links, but also to use a returnvalue of a functioncall.
So we would have the possibility, if our helpserver URL changes, not to go through all pages and change it in every page, but only to change it in one Codeunit or Table.

**Comment by atoader** [comment]
Hi @dNsl9r ! The solution to this has been shipped in the Spring 2019 release https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/context-sensitive-help
