### ISSUE TITLE
Question - Issue with "Edit in Excel" on business Central 

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/AL#2727]
Hi Team,

We have deployed an extension on business central. Now, when we open a custom pages and click on "Edit in Excel", it opens the Excel with columns of the page but Column sequence is not same as we have on the page. it changes when we do "Edit in Excel".
Is there anything we can do to keep the column sequence same in Excel as it is on page.

Thanks.

![editinexcel_bc](https://user-images.githubusercontent.com/40057282/41909154-efbf58c2-7963-11e8-8d8a-6d69e83c92f1.png)

**Comment by anuj-inecta** [comment]
Hi Team, Good Morning..
Any update on the issue, thanks!

**Comment by anuj-inecta** [comment]
Hi Team, Good Morning..
Please give some update on the issue.

**Comment by StanislawStempin** [comment]
I passed the question on to the owning team and will let you know once we have a reply.

**Comment by StanislawStempin** [comment]
The column list in Excel is based on the ODATA Web Service that is created for that entity.  The page is only used to understand the source table and the web service is based from that definition.  This means the column list might not match when the web service is created by default.  A user, from the Excel Addin, could design the column list and then save the workbook for future usages.
