### ISSUE TITLE
Open in Excel vs Edit in Excel

### ISSUE THREAD

**Issue by jngillard** [Microsoft/AL#2728]
I need to know what, if anything controls the difference between having the "Open In Excel" action or the "Edit in Excel" action available in business central.

Using the General Ledger Entries page for example:

I have a tenant that has the "Edit in Excel" action on this page. It seems like the "Edit in Excel" action only pulls in table level records from the page. So if you have added custom fields that only exist on the page, they are not in the excel output. This is a problem.

But, my company Sandbox business central environment has the "Open in Excel" action on this same page instead. This "Open in Excel" action pulls down all of the fields from the page into the excel file. This is what I want. 

So, why do these two environments have different excel actions?

Sandbox:
![image](https://user-images.githubusercontent.com/33632558/41909239-82837f08-7914-11e8-95e4-68a160350185.png)
Customer Business Central:
![image](https://user-images.githubusercontent.com/33632558/41909279-a1c74c6e-7914-11e8-8471-85e271b2f26d.png)

Note: When testing on my docker build, I have the "open in excel option" available. This is image: microsoft/bcsandbox:ca

**Comment by freddydk** [comment]
Edit in Excel requires AAD setup and configuration - if you haven't set that up - it will default to Open In Excel, create the spreadsheet and download.
