### ISSUE TITLE
In-client designer doesn't close correctly

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#273]
After closing the in-client designer, the purple triangles remain visible.

Scenario (on a fresh installed developer preview VM):

1. Open Customer List
2. Start in-client designer
3. Set page to list mode
4. Remove Location code by clicking on the purple triangle and choose Remove
5. Click on stop designing
6. Choose Save for everybody and click Go

The in-client designer exits, but the triangles remain visible and clickable.

See screenshot, note that the designer is not visible,

![image](https://user-images.githubusercontent.com/19155831/26993498-9a6cd980-4d63-11e7-992d-2385eee1f1b2.png)

**Comment by StanislawStempin** [comment]
This looks like a bug. We will investigate further. 
Can you share which version of IE you are using?

**Comment by ajkauffmann** [comment]
It's on the developer preview image.

![image](https://user-images.githubusercontent.com/19155831/27002676-d6a4a3c2-4de7-11e7-927c-4e8804bf7b22.png)
