### ISSUE TITLE
Error when using the OutStream.Write(Variant,[Integer]) method

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#2730]
- AL Extension Version: 0.17.20571
- Server Version: 13.0.22621

The following misbehaviour occurs when programming is used. If you want to write a variant to an OutStream, then a strange error is displayed that has nothing to do with the current context at all. The following code causes the error.

```
    local procedure WriteVariant(Vari: Variant)
    begin
          OStream.WRITE(Vari);
    end;
```

OStream: OutStream

Error Message:
`The call is ambiguous between the following methods or properties: 'Write(Boolean, Integer)' and 'Write(Byte, Integer)'`

**Comment by qutreson** [comment]
Hi @FSharpCSharp, it seems that the error message is slightly misleading here. The compiler is confused between Write(Boolean, [Integer]) and Write(Byte, [Integer]) where [Integer] represents an optional parameter. We will fix the display of the error message to show optional parameters as optional.

According to our [docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-outstream-write-method), this should accept any type for the first parameter, but we are currently not supporting the use of Variant. As a temporary workaround, while we enable it, you can explicitly cast the variant before using it in the write method.
