### ISSUE TITLE
Personalizing Issue.

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#2731]
When I tried to move fields on the page using Personalize mode, am getting the following message without enabled OK button. Please find the attached file.

![image](https://user-images.githubusercontent.com/39764447/41913655-88dd4b36-796e-11e8-8e5a-bfdd7068da7f.png)

Please enable the OK button.

**Comment by dennisfrostlander** [comment]
Hi @A-R-Shaji,
Apologies for a late reply.

If you still could reproduce the same issue, could you please specify:
- What build version you have (from the System Information page)
- What environment it is - production/sandbox
- Does it happen for a specific field? Any field? On any page?

**Comment by A-R-Shaji** [comment]
Hi @dennisfrostlander,
I checked in Latest master build. It is working fine.

You can close this issue.
