### ISSUE TITLE
Fragmented objects within the property "idRange" in the file app.json

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#2732]
We have a problem with the assignment of the "idRange" variable. We now want to move our ISV module, but it is fragmented into several areas. There are several historical reasons for this.

There is no single contiguous number range. The reason is the history of Granule.

**Level 1**

- On the first application, we applied for and activated 10 objects.
- Range: 70000..70009
- This also affected the field numbers.

**level 2**

- During the development it was determined that we need more than 10 numbers due to the fields.
- A new application for 25 numbers led to a second area, which was, however, separate from the previous one.
- Range: 100420..100444
- The objects from level 1 were moved completely to this area, the original area was emptied.

**Level 3**

- A further development was also included in the Granule, reusing the old area from level 1.
- This area was maintained even after the restructuring.

**Level 4**

- Additional objects were required for the introduction of a new feature.
- The last 30 of the 1000 objects we received for another product were used (at that time Microsoft always assigned 1000 numbers per module request).
- Range: 141215..141244

I have alienated the numbers mentioned for data protection reasons. It's more about the principle of what actually happened in the course of time. In principle, however, all these objects are assigned to the same "granule".

But it is unfortunately unclear to us how we should specify all these number ranges within the property "idRange" during development. We can't create a separate app for each of these areas because we have some overlaps. So far, we have simply activated the "Granule" for the respective customer, and this customer has access to all the areas mentioned above.

**Comment by thpeder** [comment]
Hi @FSharpCSharp,
As you have discovered we only support having one range, so for now you need to specify a range that covers all your ranges.

**Comment by FSharpCSharp** [comment]
@thpeder 
All right. So that means that I have to take the smallest and the largest number. But does this property have any other effects, except that you get error messages when an object is outside this range? If not, then we can indeed do so. Is there anything wrong with that?

**Comment by thpeder** [comment]
@FSharpCSharp, 
Yes you need to take the smallest to the biggest for now.
It was first added as a convenience for you to make sure you stay within your license Id range, and now AppSource submissions requires it, but it will work.

Your best option might be to request a new range which can contain all your objects and a bit more.

**Comment by StanislawStempin** [comment]
We are finalizing a feature that will allow you to specify multiple Id ranges in the app.json. Stay tuned for the November preview release.
