### ISSUE TITLE
Make functions external om Page 5098 Task Card

### ISSUE THREAD

**Issue by bogdan81GitHub** [Microsoft/AL#2737]
In build 13.0.22621.0 -nl we need to make the follwing functions external in page 5098 : EnableFields, SwitchCardControls, TeamCodeOnAfterValidate ,TypeOnAfterValidate, AllDayEventOnAfterValidate, SalespersonCodeOnAfterValidate, OpportunityNoOnAfterValidate.

I give an example in the picture below .
In the left side it is standard page 5098 Task Card and in the right our customized page. Because the editability of some fields was changed, in order to migrate this change to a page extension, I have to hide those fields and create new ones. The problem is I cannot access the functions from the page as they are local functions.  Could you please, make them external? 

![git](https://user-images.githubusercontent.com/30693206/41963269-9db35136-79e6-11e8-8f27-54d07addbb74.png)

**Comment by bogdan81GitHub** [comment]
Hello! I also need local  function Caption to be external  in page 5096 Task List for the same reason. Thank you.

**Comment by PooyaKharamesh** [comment]
Hi 

would you provide an explanation on why you need these functions to be external? 

Regards
Pooya

**Comment by bogdan81GitHub** [comment]
In page 5096 Task List  the function Caption was modified in order to add to CaptionStr information about some new fields we add in our solution. The function was used in DataCaptionExpr property on the page.
I thought I could create another function in the pageextension for example CaptionB (too manage our customization) and then set DataCaptionExpr=Caption+CaptionB. This is why I needed the function external.So I can Access it from the page extension.
But changing DataCaptionExpr in the page extension rises an error when I try to publish the extension. So, also in this case it will not work.

**Comment by bogdan81GitHub** [comment]
For page 50098 I need the functions to be external because if I can't change some properties for some fields from AL  then I have to hide those fields and create new customized ones in extension. So , in order not to duplicate the code, I need the functions external.

Thank you,
Bogdan

**Comment by PooyaKharamesh** [comment]
Hi 

Thanks for the clarification and your request. These functions either control the UI behavior or do the validations or similar behaviours and shouldn't be external, having said that I agree with you that there is a need to call these functions from the page extensions. Therefor after a discussion about the proper solution we added these requests to our backlog for implementation. 

Thanks and regards
Pooya
