### ISSUE TITLE
What if i want to use a Table from a already installed extension on my tenant, in my another Extension?

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#2739]
Hi,

I am creating Extension B, and already published Extension A on the same tenant.
Now I want to use a Table from Extension A in Extension B , as I m creating a Page based on that table(SourceTable = "Some Table from Extension A").

Is it possible to inherit that table in this Extension? If yes then please suggest.

Thanks

**Comment by thpeder** [comment]
Hi @SUD-D365,
In the app.json file you can specify that you take a dependency on another extension which allows you to reference objects from other extensions. For your case in the app.json file for Extension B you would write Extension A.
Read more about it here [App.json file
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#appjson-file)

**Comment by SUD-D365** [comment]
Hi @thpeder , Yes I have defined the properties in dependencies.
But I m able to inherit normal tables only. I have published some CRM type table in that Extension A, I need to inherit them in Extension B. Those tables are not showing.

**Comment by qutreson** [comment]
Hi @SUD-D365, it is currently not possible to extend CRM tables. The issue #2508 is used in order to track the CRM table extensibility.
