### ISSUE TITLE
tprocedure snippet suggestion

### ISSUE THREAD

**Issue by awcowan** [Microsoft/AL#274]
Hi,

In VS Code when you use the 'tprocedure' snippet the function that is created is 'Global' as default. In the NAV development client this now defaults as 'local' when a new function is created and has done for the last few versions. Is it possible to either add a new snippet like: 'tprocedurelocal' or change the snippet to be local as default?

Thanks
Andy

**Comment by StanislawStempin** [comment]
Thanks, this was already reported under #213.
