### ISSUE TITLE
Testpage values cannot be assigned to variables only if that values are text or code

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#2740]
Hi i am unable to assign values from test page to my variable. this is only for text or code values 
example:
**VAR
        Periods: TestPage "Periods";
        ResourceNo: code [20];**

 ResourceNo := format(Periods."Resource No.");
i am getting  issue for this

The expression Microsoft.Dynamics.Nav.Runtime.NavTestField cannot be type-converted to a Microsoft.Dynamics

May i know is there any possibility to overcome this

**Comment by srinivasbanny** [comment]
Hi @thpeder  
Al version is al-0.17.22710
nav build is 13.0.22815
the data type of "resource no." is code of length 20
i am assigning it from test page
VAR
Periods: TestPage "Periods";
ResourceNo: code [20];

ResourceNo := format(Periods."Resource No.");

**Comment by srinivasbanny** [comment]
And one more thing how the behavior of the test functions 
lets say i have 4 test functions from testcodeunit 
if i run testcodeunit the data will rollback function wise or until the execution of test codeunit the data will be there?

**Comment by ashik-ivor** [comment]
ResourceNo := format(Periods.value."Resource No.");
