### ISSUE TITLE
You do not have the following permissions on TableData NAV App: IndirectInsert

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2743]
getting below error while trying to publish app to sandbox environment.
is it license related issue or how can we solve this?

![image](https://user-images.githubusercontent.com/23735402/41981385-6b4d5178-7a46-11e8-9d80-4dd4b574b55b.png)

**Comment by thpeder** [comment]
It seems to be related to #2721.

**Comment by pmohanakrishna** [comment]
I am super user but has company name populated. can it be the issue?

**Comment by StanislawStempin** [comment]
We have seen this in cases when there is a new sandbox to which no one logged in through the web client yet. Can you confirm that the problem goes away after you logged into the sandbox?
