### ISSUE TITLE
Download Content of BLOBs

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#2745]
What is the suggested way to download the content of a BLOB to a local drive?
Most of the functions in CU419 are set to INTERNAL (for whatever reason).

Would it be possible to allow the following procedures as External ?
BLOBImport
BLOBImportWithFilter
BLOBExport
BLOBExportWithEncoding

**Comment by ftornero9** [comment]
We are using DownloadFromStream

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-downloadfromstream-method-file

Regards

**Comment by ThomasBrodkorb** [comment]
That is what we are doing right now as well.
But in CU419 File Management, there are additional functions which are very useful, such as "GetToFilterText" to define the required filter string. These are "Internal", 
So we end up with code duplication if we use the basic functions provided by the development environment - which we could prevent as soon as those functions are defined as EXTERNAL.

**Comment by DuttaSoumya** [comment]
We shall not be making these functions as External as these are related to client file import and export functionality and will only work on OnPrem.

**Comment by Joel-NAVDev** [comment]
BLOBImportWithFilter is now externally available on the latest BC insider image, why not make BLOBImport external too? @StanislawStempin
