### ISSUE TITLE
Additional Hashing functions in Encryption Mgt.

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#2746]
Please provide additional functions to generate hashes from streams (InStream) additionally to the ones which calculate the hash based on Text.

GenerateHash
GenerateHashAsBase64String

**Comment by dNsl9r** [comment]
You can add the function yourself and create a pull request in the c/al open library:
https://github.com/Microsoft/cal-open-library/

**Comment by ThomasBrodkorb** [comment]
Sorry, I do not understand the follwoing terms:
"Pull Request" and "Granular"
I do also not know how to "submit" code and I'm not aware of how to "extend" an existing Codeunit with additional functions using a new codeunit in the range of 50K-99K.

That means, I can not make any sesnse out of your reply.

**Comment by Gallimathias** [comment]
If so, you should refresh your git basics as soon as possible.

[Git - Getting Started](https://git-scm.com/book/en/v1/Getting-Started)

You can use the Open Library repository, fork and clone and then customize. When you're done, you can submit your changes. The process of submitting is called Pull Request.

A more detailed explanation can be found in the link above, after all you are already on __Git__ Hub ^^.

**Comment by ThomasBrodkorb** [comment]
I have never used github - except for "download as zip". So I have absolutely no clue - and also no time for discovering this "another cloud storage" thingy.
But thanks for the guide.

**Comment by Gallimathias** [comment]
Whatever you say. By the way, this has nothing to do with cloud storage. Git is a version control and for development is git the standard, GitHub has nothing to do with it except that they provide a server.

If you want to save work and time, a lot of time, then Git would definitely be worth a look ^^. (very lot of time)

So now you have to wait until MS implements the functions or someone implements them for you. With the latter I would only find it a pity that one consumes a community but does not contribute anything.

**Comment by ThomasBrodkorb** [comment]
Well, I'm a developer for 30 years now (started at the age of 15) and 19 years with NAV. 
I'm an NAV ISV with certified solutions for 18 years and use several development tools like VS for .NET add ins and NAV DevEnv for NAV development.

I read thru the link you provided and I'm still not closer to any understanding of how that should help me or what I could do in order to "support the community".

My understanding was that this "issue" list on github/Microsoft/al was to provide feedback to Microsoft if we find something we consider being worth to be added or modified in the base application.

And on another note: It seems that the modifications in there are not implemented in the base app on a monthly base as mentioned.

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! I'm happy to inform you, that such functionality already was implemented through function GenerateHashFromStream. If this implementation doesn't meet your needs, you can indeed add capabilities yourself by contributing to the library through https://github.com/Microsoft/cal-open-library/. You can read much more about GitHub and how to use it online. We would be very happy to have you join our community and improve Business Central together with you! But maybe GenerateHashFromStream is what you're looking for already? I will close this issue for now. Please reopen, if this answer did not unblock you! Thanks again!
