### ISSUE TITLE
Unhandled UI: ReportData

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/AL#2749]
My Codeunit use test report
[Test]
    [HandlerFunctions('RHGeneralLedgerReport')]
    procedure GeneralLedgerReport()
    begin
        Report.Run(Report::"DIC General Ledger", true, false);
    end;

    [RequestPageHandler]
    procedure RHGeneralLedgerReport(var GeneralLedgerPage: TestRequestPage "DIC General Ledger")
    begin
        GeneralLedgerPage."From Date".SetValue(WorkDate());
        GeneralLedgerPage."To Date".SetValue(WorkDate());
        GeneralLedgerPage."Document No.".SetValue('OTH-1712-00001');
        GeneralLedgerPage.Preview().Invoke();
        //GeneralLedgerPage.SaveAsXml();
    end;
![image](https://user-images.githubusercontent.com/26807095/42010941-47b4c00a-7abb-11e8-8038-5d6915c6ff5f.png)

When run CAL Test tool return result Fail
![image](https://user-images.githubusercontent.com/26807095/42010956-55dd926a-7abb-11e8-88da-23a8bb358c39.png)

Help me with this proplem
Thanks

**Comment by qutreson** [comment]
Hi @chiecnhanco, I just tried something similar on another report and could not reproduce the error you had. Can you send us a repro also including the report object that you are using?

**Comment by ashik-ivor** [comment]
You can use a "ReportHandler" additionally because you are previewing the report and Test Automation does not allow you to check the UI.

**Comment by chiecnhanco** [comment]
Thanks for support.
