### ISSUE TITLE
How Can I get Client Directory Files List (with JOB queue)

### ISSUE THREAD

**Issue by czeslaw6300149** [Microsoft/AL#2752]
Hi, I want to know is there any solution to get Client Directory Files List (with JOB queue)?

When I Create a Codeunit name "MyTest" (maybe 89999) ,
and use "File Management"( Codeunit 419) procedure "GetClientDirectoryFilesList".

ex:
codeunit 89999 MyTest
{
  trigger OnRun();
  var
       NameValueBuffer : record "Name/Value Buffer";
       FileManagement : codunit "File Management";
  begin
       FileManagement.GetClientDirectoryFilesList( NameValueBuffer, --FolderPath--);
  end;
}

Then I create a button to run MyTest on a page (maybe 9001).

It work fine, And I can find list in "Name/Value Buffer" (Table 823).

But when I Create a job queue to run MyTest, It Can't Find folder any more.

Always Return Error.

Is possible to slove this question?
Or if not possible, how can I do?

PS:I'm using CU5, and "AL Language" version is 0.12.20065

**Comment by diveshbora** [comment]
Hi 

Dot net variables with RunOnClient = Yes cannot be used in Web Client & in NAS (Job Queue), but it can be used in Windows Client. So try to use GetServerDirectoryFilesList function it will work in Job Queue. I hope you have tested this in Windows Client right ?

Best Regards,
Divesh

**Comment by dennisfrostlander** [comment]
Correct, closing the issue.
