### ISSUE TITLE
How can we handle  Excel Interop (.NET) in AL 

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#2753]
I have one  report that is used to create multiple sheets and pivot in excel for which i have used .NET variable, How can i handle this in AL because .NET library doesn't support in AL.
 for example :  
   xlApp : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.ApplicationClass" RUNONCLIENT;
        xlSheet : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.Worksheet" RUNONCLIENT;
        xlWkSheet4 : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.Worksheet" RUNONCLIENT;
        ExcelHelper : DotNet "'Microsoft.Dynamics.Nav.Integration.Office, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.Microsoft.Dynamics.Nav.Integration.Office.Excel.ExcelHelper" RUNONCLIENT;
        xlPivotCache : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.PivotCache" RUNONCLIENT;
        xlRange : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.Range" RUNONCLIENT;
        xlPivotTable : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.PivotTable" RUNONCLIENT;
        xlPivotField : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.PivotField" RUNONCLIENT;
        PivotFieldOrientation : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.XlPivotFieldOrientation" RUNONCLIENT;
        PivotFieldFunction : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.XlConsolidationFunction" RUNONCLIENT;
        PivotFieldCalculation : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.XlPivotFieldCalculation" RUNONCLIENT;
        XLWkInfoSheet : DotNet "'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.Microsoft.Office.Interop.Excel.Worksheet" RUNONCLIENT;

**Comment by Gallimathias** [comment]
DotNet is ONLY available again for OnPremise, since the last preview update.

For cloud solutions you have to use Microservices or JavaScript.

Unfortunately, the preview is only available through the readyToGo program. The public preview comes in about a month.

**Comment by StanislawStempin** [comment]
That's correct. You cannot use DotNet in the cloud and moreover that code would not even work in the web client On-Premise since it uses client-side .NET, only supported in the windows client.

The DotNet functionality for On-Premise is available since June developer preview and is available through aka.ms/ready2go program. We no longer provide publicly available previews, all builds go through ready2go.

**Comment by Deepakalle123** [comment]
@StanislawStempin  How can we use that developer preview - can you please brief on it
In my knowledge Redy2go program consist three segnments/elements
Element 1: "Ready to Go" online learning
Element 2: "Ready to Go" coaching
Element 3: "Ready to Go" platform

From where we can download the developer preview
