### ISSUE TITLE
Test Codeunit functions in worng order 

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#2754]
Hi, 

I got a problem, I am developing Test Codeunit on extensions. I am using NAV2018 CU05.  When I import my test Codeunit with Test Tool, my test functions order is different then in VS Code and of course I am getting errors when I run codeunit from Test Tool because of that. Why? Does anyone have similar problem?

**Comment by pmohanakrishna** [comment]
you mean this?
https://github.com/Microsoft/AL/issues/2711

**Comment by linasostreika** [comment]
Yes, thank you @pmohanakrishna
