### ISSUE TITLE
Testcase for Report using AL

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#2756]
Hi !

I need create test app for my business app.
But i can't create test case for testing report.
Because SAVEASEXCEL, SAVEASPDF, SAVEASWORD,SAVEASXML cannot be used for Extension.

Please support me a method so that I can export a report to file for checking data.

**Comment by thpeder** [comment]
Hi @hgnamvn,
Take a look at "SaveAs". It allows you to write it to a stream instead of directly to a file.
![image](https://user-images.githubusercontent.com/24276180/42088719-cd0697c6-7b9a-11e8-8747-a613e6709ec4.png)

**Comment by hgnamvn** [comment]
Hi @thpeder ,

I checked it but "SaveAs" cannot be used for extension.

**Comment by hgnamvn** [comment]
Thank @thpeder,

I will check SaveAs again with outstream.

**Comment by ashik-ivor** [comment]
You can use table filter (SETRANGE or GET) and then run the report. This can help you in a different way

**Comment by hgnamvn** [comment]
Thank @thpeder,

Your suggestion is OK for me.
