### ISSUE TITLE
[Function Expose] Functions of Codeunit 1439 - Headline Management must be publicly accessible.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#2757]
When building a new role center, we noticed that we cannot use the standard functionality in which the user is welcomed and can call help, because various functions within Codeunit 1439 - Headline Management cannot be used within an extension.

Specifically, this applies to the following functions:

- HeadlineManagement.ScheduleTask
- HeadlineManagement.ShouldUserGreetingBeVisible

Could you adjust these functions accordingly so that you can access them and use the standard functions of the role center? That would really be very helpful.

**Comment by JesperSchulz** [comment]
Absolutely! I will expose those functions asap.
