### ISSUE TITLE
NAV app Company wise

### ISSUE THREAD

**Issue by Nagaraju17** [Microsoft/AL#2761]
Hi,

   Is there any possibility to install NAV APP company wise. If we have please suggest me the steps.
If we have this feature, it will be good.

Thanks in Advance.

**Comment by dennisfrostlander** [comment]
Hi @Nagaraju17,
Nav apps are installed in a tenant, which should include all companies for that tenant.

**Comment by Nagaraju17** [comment]
Hi dennis,

thanks!

So it is not possible for single company(without tenant concept) ?

**Comment by dennisfrostlander** [comment]
No
