### ISSUE TITLE
Need searchable, community editable, index of NAV functionality -- codeunits, reports, etc.

### ISSUE THREAD

**Issue by quadfin** [microsoft/AL#2763]
There are a lot of hidden gems in existing NAV code but many are hard to find.  E.g., if you wish to use a hash function you can search on the web or in this forum for "hash" and buried in a response to a request for the same you will find the answer -- codeunit 1266, Encryption Management, GenerateHash.

It would be infinitely helpful if we had a searchable, community modifiable, index where we could maintain such a beast -- perhaps a dedicated page on the Wiki for this project.

Enabling community contributions would allow it to be self governing and dynamic.  It might also go a long way toward lessening the volume on the Issues queue for things that already exist.

**Comment by Gallimathias** [comment]
I think the idea is a good one and I would support it. If MS didn't want a community driven index, we could do it as a community alone. (GitHub Group + GitHub Page)
