### ISSUE TITLE
System tables are no longer accessible

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#2769]
Since System tables are no longer accessible, what are the alternatives? How to create a Profile for Role Center programmatically now?

NAV system tables not recognized in VSC-AL:[/b]
“The type or method 'XXX' cannot be used for 'Extension' development”
Where ‘XXX’ is defined as a Record var pointing to a system table,
e.g. Table 2000000072 Profile
T. 2000000022 File
T. 2000000112 Server Instance
T. 2000000076 Web Service

**Comment by dNsl9r** [comment]
Regarding to profile: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object

**Comment by dennisfrostlander** [comment]
Hi @naveksa and thanks @dNsl9r. 
Regarding other system tables, we have restricted access to only those system tables which could compromise safety when running a cloud multi-tenant environment. This includes `Server Instance`, `File` and others. 

If you are developing an on-premise solution though, you can switch to `"target": "Internal"` in the `app.json` file and you will have access to all system tables as before. However, note that you will not be able to publish such extensions to the cloud.

**Comment by dennisfrostlander** [comment]
P.S. And if you believe that a certain system table has been incorrectly categorized as 'unsafe', just let us know which table it is and what is your scenario and we will have a look.
