### ISSUE TITLE
launch.json not valid in powershell

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#277]
When I try to do some automation with PowerShell, I noticed that the launch.json doesn't seem to be a valid json-file - at least not for PowerShell.

I try:
```
get-content -Path '.\.vscode\launch.json' | ConvertFrom-Json`
```
and I get:
```
ConvertFrom-Json : Invalid JSON primitive: .
At line:1 char:45
+ get-content -Path '.\.vscode\launch.json' | ConvertFrom-Json
+                                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonComm
   and

```

or are there other ways to read the json?

**Comment by thpeder** [comment]
The default launch.json that gets generated contains comments at the top of the file which Powershell don't know how to read. Remove those and try again.

**Comment by StanislawStempin** [comment]
We will remove the comments from the generated launch.json file to make it valid for the parser used by Convert-FromJson.

**Comment by waldo1001** [comment]
Perfect!  Thanks!
(and it's ConvertFrom-Json) ;-)
