### ISSUE TITLE
Our add-on is based on standard functionality which is no longer accessible, since they are internal. What is the recommended approach?

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#2770]
Question:
Our add-on is based on standard functionality which is no longer accessible, since they are internal. What is the recommended approach?

Is there a list of functionalities no longer accessible and alternatives somewhere, so we can reprogram it?
Use/Reference of functions on standard objects defined as Internal
“The type or method 'XXX' cannot be used for 'Extension' development”
Where ‘XXX’ is a function on a standard table or codeunit,
e.g. Table 900, Assembly Header, fct. AddBOMLine, property FunctionVisibility = Internal
T. 901, Assembly Line, fct. ValidateDueDate, property FunctionVisibility = Internal

**Comment by dennisfrostlander** [comment]
Hi @naveksa,
You can always request the function to be exposed right here.
In fact, Table 901, ValidateDueDate has been already made external in the latest codebase.

Sending a request to expose Table 900, AddBOMLine as well.

**Comment by JesperSchulz** [comment]
I will happily expose the AddBOMLine function :-)
