### ISSUE TITLE
UninstallApp trigger?

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2777]
Is there a trigger that gets called when the app is uninstalled?  I would like to be able to delete data generated in BC base tables from my app.  For instance, remove No. Series (and Lines).

**Comment by ashik-ivor** [comment]
NAVAPP.DELETEARCHIVEDATA

**Comment by thpeder** [comment]
This suggestion is tracked as part of #191 - closing as duplicate.
