### ISSUE TITLE
Facing issue with error 422

### ISSUE THREAD

**Issue by RagRawat** [Microsoft/AL#2779]
hi,

Getting the Issue when I am Publish or publish without debugging.

**The request for path /DynamicsNAV110/dev/apps failed with code 422. Reason: The extension was unable to be deployed due to a dependency between extensions.**

Can anyone please help how can I do the same, previously I am working with the same.

**launch.json**
_{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "al",
      "request": "launch",
      "name": "Raghubir",
      "server": "http://localhost:7049",
      "serverInstance": "DynamicsNAV110",
      "authentication": "Windows"
    }
  ]
}_

**Comment by dNsl9r** [comment]
Do you have any dependencies in the app.json?
`  "capabilities": [],
  "dependencies": [{ "appId": "abc12345-6789-0123-de45-fghi67890jkl","name": "My App", "publisher": "Myself", "version": "1.0.0.0"}],
  "screenshots": [],`

As you are developing for NAV 2018 (I'd guess based on the ServerInstance Name), which AL Language Extension are you using?

**Comment by RagRawat** [comment]
Thanks,

But I don't have any dependency.

**app.json**
_{
  "id": "0e4d8830-1f7a-4b91-8a5c-7fad9f31863c",
  "name": "ALProject3",
  "publisher": "Raghubir",
  "brief": "",
  "description": "Testing AL ",
  "version": "1.0.0.0",
  "compatibilityId": "0.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.12925.0",
  "application": "11.0.19394.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}_

**Comment by tfenster** [comment]
@RagRawat I've seen this when another extension depends on the extension you want to update. Maybe this is the case for you as well?

**Comment by RagRawat** [comment]
@tfenster means if I use 50000 in NAV with another project I cant do the same in another project.

**Comment by dNsl9r** [comment]
If you have another app with the ID range of 50100 .. 50149 you will not be able to publish the extension. But you'll get another error as far as I know.
In my opinion Tobias question is, if you do have another extension that depends on your extension "ALProject3".

Just to be on the safe side I'd recommend you to uninstall and unpublish all previous extensions from your test database.

**Comment by dennisfrostlander** [comment]
Hi @RagRawat,

This error means that there is another extension on the server, which depends on your extension.
This could happen, for example, if you use an in-client designer. The current behavior is that the designer automatically takes a dependency on all currently published extensions (see https://github.com/Microsoft/AL/issues/1704)

You can open Extension Management page and uninstall/unpublish the extensions which might have a dependency on yours.

**Comment by RagRawat** [comment]
Thanks a lot to all friends. 👍 

by uninstall and un publish will work.
