### ISSUE TITLE
Evaluation order in if-statements

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#278]
Consider the following code example:

```
codeunit 70770000 BooleanEvaluation 
{
    [EventSubscriber(ObjectType::Page, 21, 'OnOpenPageEvent', '', False, False)]
    local procedure MyProcedure();    
    begin
        if ReturnTrue or TestSomething then
            Message('At least one value is true');

        if ReturnFalse and TestSomething then
            Message('Both values are true');
    end;

    local procedure ReturnTrue() : Boolean;
    begin
        exit(True);
    end;
    
    local procedure ReturnFalse() : Boolean;
    begin
        exit(False);
    end;    

    local procedure TestSomething() : Boolean;    
    begin
        Message('Running TestSomething');
        exit(False);
    end;
}
```
When you run it and open the Customer Card the message in `TestSomething` will be shown for each if-statement even though the first value in both statements determine the outcome. 

The execution of `TestSomething` is in my opinion both unnecessary and unwanted.

Other examples could be this:
```
if GuiAllowed and ConfirmedByUser then
    DoSomething;

if not GuiAllowed or not ConfirmedByUser then
    DoSomething;
```
Which would both create an error when `GuiAllowed` evaluates to `False`.

**Comment by esbenk** [comment]
C/AL have never had short-circuit boolean evaluation. This is legacy and I agree it is uncommon today. 

Unfortunately this is not just something we can change. Not only does all our own AL code rely on that, but also all the code written by partners.

**Comment by kaspermoerch** [comment]
Thanks for clearing that up.

**Comment by pborring** [comment]
Note related entry on ideas 
https://experience.dynamics.com/ideas/idea/?ideaid=1264ee71-01ea-eb11-ba5e-0003ff45af84
