### ISSUE TITLE
Is there any alternate of XML document parsing or creation and web services integration without of .NET Variable

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#2780]
Hi I have multiple codeunits having .NET variable is Involved with Assembly - System.Xml.XmlDocument 

How can we handle this in AL.

Few examples :
 1. XMLDocIn : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, 
                                                        PublicKeyToken=b77a5c561934e089'.System.Xml.XmlDocument";
2.  XMLDocOut : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, 
                                                        PublicKeyToken=b77a5c561934e089'.System.Xml.XmlDocument";
 3. ReturnNode : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, 
                                              PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";
  4. RootNode : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, 
                                                           PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";

**Comment by Deepakalle123** [comment]
Hi Thanks for your suggestion it looks pretty good ...
I have created one Varible with type XMLDocument like : 
XMLDocIn : XmlDocument;

How can i use loadxml method there is no such method 
XMLDocIn.LoadXml(FORMAT(Request))  //

**Comment by Deepakalle123** [comment]
@dNsl9r  Need your suggestion on it.

**Comment by Deepakalle123** [comment]
Ok let me try that.. Thanks :)

**Comment by Deepakalle123** [comment]
ReadFrom looks good ,it will handle it.
Now In my Codeunit there are many more .NET variable is used that is not provided in defined classes:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview

Like - System.Xml.Xsl.XslTransform" ,System.Xml.Xsl.XsltArgumentList, Microsoft.Office.Interop.Excel.Workbook , 

Few are of them is for SQL connection 
System.Data.SqlClient.SqlConnectio, etc.

@dNsl9r : Any idea about to handle this if you want i can attach the .al file for the same.

**Comment by dNsl9r** [comment]
Pretty sure there is nothing like SQL Connection via .NET in BC - if you are going to be OnPrem you could still create normal Codeunits in the C/Side Dev Env. Maybe @dennisfrostlander  could help you out in this situation - better than me 😃

**Comment by Deepakalle123** [comment]
Ok thanks  😃

**Comment by StanislawStempin** [comment]
@Deepakalle123 - for XslTransform please check the http://github.com/microsoft/cal-open-library.  I recall that someone submitted a library function to perform what you might need.

For SQL Connection there is no replacement in the cloud since you should not be making direct SQL connections from a cloud tenant. You would need to communicate with your external storage through Http.

**Comment by Deepakalle123** [comment]
Thanks @StanislawStempin  let me check with that 👍
