### ISSUE TITLE
"The type or method 'NAV App' cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by Waynerad2000** [Microsoft/AL#2781]
I am trying to use a record from a page I have subscribed to but I get the error "The type or method 'NAV App' cannot be used for 'Extension' development".

I am using VS code to publish an App but I have no work around.

sample code:
[EventSubscriber(ObjectType::Page, Page::"Extension Details", 'OnBeforeActionEvent', 'Uninstall', false, false)]
local procedure UninstalledSTDSTMTImportCode(var Rec: Record "NAV App")

This is possible in nor C/AL but I cannot get this to work in AL.

Thanks in advance.

**Comment by dennisfrostlander** [comment]
Hi @Waynerad2000,

We have restricted access to only those system tables which could compromise safety when running a cloud multi-tenant environment.

If you are developing an on-premise solution though, you can switch to "target": "Internal" in the app.json file and you will have access to all system tables as before. However, note that you will not be able to publish such extensions to the cloud.

See also #2769
