### ISSUE TITLE
[External Function Request] Page 51

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/AL#2786]
We would like to have the following two functions on page 51 marked as external:
- Post
- VerifyTotal

**Comment by PooyaKharamesh** [comment]
Hi, 

Would you provide an explanation on why you need these function? and in general why you need external functions on a Page?

Regards
Pooya

**Comment by PooyaKharamesh** [comment]
Hi 

Thanks for the clarification and your request. These functions either control the UI behavior or do the validations or similar behaviours and shouldn't be external, having said that I agree with you that there is a need to call these functions from the page extensions. Therefor after a discussion about the proper solution we added these requests to our backlog for implementation. 

Thanks and regards
Pooya

**Comment by richardrobberse** [comment]
Thanks for your reply, and indeed the base object need a bit of refactoring before exposing the function.
