### ISSUE TITLE
Assembly could not be found

### ISSUE THREAD

**Issue by IvoMol** [Microsoft/AL#2787]
Using AL 0.17.2497, define new DotNet assemblies, selected from GAC (I hope).

Some of them are accepted (mscorlib), many of them are not (for example System.Drawing):
![asseblymissing](https://user-images.githubusercontent.com/17826638/42266473-07bc4c3e-7f66-11e8-9414-000aafa569e6.JPG)

Both registered in system correctly, both can be used together in C/AL:
![asseblyvisible](https://user-images.githubusercontent.com/17826638/42266536-31d7138c-7f66-11e8-9431-921f7f65bfa8.JPG)

Is there some limitation or restriction? Different syntax?

**Comment by dennisfrostlander** [comment]
Hi @IvoMol,

The Global Assembly Cache folder is by default not considered when loading .NET types.
If you'd like to use additional assemblies, you can manually add it to the list of probing paths.

In the `settings.json` file, add the following setting:
```
    "al.assemblyProbingPaths": [
        "c:\\windows\\Microsoft.NET\\assembly"
    ],
```
Then you should be able to use System.Drawing assembly among others.

**Comment by IvoMol** [comment]
Yes, worked now!
I did not find the difference between mscorlib and others.

Thank you!
