### ISSUE TITLE
[Event Request] Codeunit 5510 Production Journal Mgt., Handling()

### ISSUE THREAD

**Issue by sirhc101** [Microsoft/AL#2789]
Please add the following event to codeunit object 5510 Production Journal Mgt. function Handling(). We developed a small solution handling output and consumption postings in some kind of a mobile interface, using Phone- & Tablet-Client.
The Handling() function is calling the Page 5510 Production Journal. This page is not suitable for small displays, like a smartphone or scanner, and we would like to call another one instead.

My idea is to create an event publisher before entering the `REPEAT UNTIL` loop and adding a little bit of Code to prevent mutliple callings.

Currently the code is looking like this:
```` C/AL
Handling(ProdOrder : Record "Production Order";ActualLineNo : Integer)
MfgSetup.GET;

SetTemplateAndBatchName;

InitSetupValues;

DeleteJnlLines(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo);

CreateJnlLines(ProdOrder,ActualLineNo);
REPEAT
  LeaveForm := TRUE;
  CLEAR(ProductionJnl);
  ProductionJnl.Setup(ToTemplateName,ToBatchName,ProdOrder,ActualLineNo,PostingDate);
  ProductionJnl.RUNMODAL;
  IF DataHasChanged(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo) THEN
    LeaveForm := CONFIRM(Text001,TRUE);
UNTIL LeaveForm;

DeleteJnlLines(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo);
````
It would be great to add a publisher `OnBeforeRunProductionJnl` before entering the `REPEAT UNTIL` loop with the following signature:
```` C/AL
OnBeforeRunProductionJnl(
  ToTemplateName : Code[10],
  ToBatchName : Code[10],
  ProdOrder : Record "Production Order",
  ActualLineNo : Integer,
  PostingDate : Date,
  VAR Handled : Boolean)
```` 
The main point is the `Handled` parameter which is a VAR parameter and a local variable in Handling() function. The parameter should set to true when an subscriber handled the journal lines, to make sure the `REPEAT UNTIL` loop is not entered. Therefor it would be necessary to add a small `IF` statement.
My suggestion for the new code, including the event publisher, would be this:
```` C/AL
Handling(ProdOrder : Record "Production Order";ActualLineNo : Integer)
MfgSetup.GET;

SetTemplateAndBatchName;

InitSetupValues;

DeleteJnlLines(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo);

CreateJnlLines(ProdOrder,ActualLineNo);
// ---New Code Begin---
OnBeforeRunProductionJnl(ToTemplateName, ToBatchName, ProdOrder, ActualLineNo, PostingDate, Handled);
IF (NOT Handled) THEN
// ---New Code End---
REPEAT
  LeaveForm := TRUE;
  CLEAR(ProductionJnl);
  ProductionJnl.Setup(ToTemplateName,ToBatchName,ProdOrder,ActualLineNo,PostingDate);
  ProductionJnl.RUNMODAL;
  IF DataHasChanged(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo) THEN
    LeaveForm := CONFIRM(Text001,TRUE);
UNTIL LeaveForm;

DeleteJnlLines(ToTemplateName,ToBatchName,ProdOrder."No.",ActualLineNo);
````

Thank you!

**Comment by sirhc101** [comment]
Hello there,

the requested event publisher in Codeunit 5510 seems to be still missing in the newest bcsandbox docker image. When will it be shipped or is it only missing in the docker image?

Thanks
Chris

**Comment by AndreBreitenbach** [comment]
Sorry, there was an issue with my docker :(
After a restart i just noticed that the Publisher now is present (timestamp of CU5510 is 01.10.18).
So everything is fine!!
