### ISSUE TITLE
JavaScript components in AL

### ISSUE THREAD

**Issue by RasmusTidselbak** [microsoft/AL#279]
This is not an issue, but a suggestion.
I think it could be cool, to incorporate JS directly into the AL objects, like my example below.
![image](https://user-images.githubusercontent.com/2745613/27169288-7c1819d2-51a9-11e7-9c9d-2e43f3273a09.png)

**Comment by RasmusHoppe** [comment]
In particular TypeScript and React would be really cool, to have easier access to in AL objects.
