### ISSUE TITLE
BC Production - Migrate historical data failed

### ISSUE THREAD

**Issue by pierreLouise** [Microsoft/AL#2795]
I need to migrate historical data from Nav2016.
On the production business central, package on entries like Table 21 Customer ledger entries is not allowed to user with super role (missing insert right of dev license).
Seems natural of course.

May BC have a temporary paraméters, allowing partners to upload entries until standard solution appear end this year?

**Comment by pierreLouise** [comment]
How many of us are doing more or less the same extension to use web service in order to migrate entries from Nav 15..  to BC?

**Comment by jenolson** [comment]
PierreLouise, 

Could you please provide more details on exactly what you are doing so we can try and replicate this issue and work to resolve it if needed.

thanks
Jennifer Ranz
Microsoft Sr. Program Manager

**Comment by jenolson** [comment]
Within On Prem NAV you should get the same error message when you try and import into the cust ledger entry file.  I ran through the same process in NAV 2018 and get permissions errors as well.   If you want to enter transaction you should enter them into the general journal line and then post them to update the customer ledger file.

**Comment by pierreLouise** [comment]
I'm agree but the point is on Nav18 or older we don't have to use rapidstart, we just upgrade/convert.
Currently on BC we just can't upgrade but only use rapidstart ;)

I know dev team is actually working on it. I know web service is a workaround.
I wonder 

btw, your proposal on general journal line mean users must redo appling on all history, no? 
and what about item history?

**Comment by StanislawStempin** [comment]
Please have a look at the newest issues about data migration for more information.
