### ISSUE TITLE
Cannot convert from 'Record XXX' to 'var Record XXX'

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#2798]
We are getting a very weird validation error from the AL VS Code extension, that goes away as soon as we edit *any* .al file (not necessarily the one shows the error), but reappears every time we reopen the project folder.

We have a local procedure that receives a record by reference:

```
    local procedure GetVendorWithNotes(Var Vendor: Record Vendor)
    begin
         // Init Vendor Record and Values.
    end;
```

It's called from other procedures, just like this (it's a Test Codeunit, FWIW):

```
    [SendNotificationHandler]
    procedure SendVendorNotificationHandler(var notification: Notification): Boolean
    var
        Vendor: Record Vendor;
    begin
        GetVendorWithNotes(Vendor);
        // More code...
    end;
```

And, when we open the project:
![image](https://user-images.githubusercontent.com/6630306/42307088-a67656a0-8031-11e8-9da2-bbba9a0bd4e6.png)

It's mostly an annoyance, because, as I mentioned, it goes away as soon as we edit any file. But regardless...

P.S. This is happening to us with v0.16.16948 of the AL Language extension.

**Comment by dNsl9r** [comment]
Same here, 
but I do not even need to edit any file. I just have to wait 5-10 seconds, after that time the AL Language Extension / Compiler seems to be fully loaded.. 
But still - that's a kinda strange behavior..
