### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line event-request

### ISSUE THREAD

**Issue by ashishsharmanav** [Microsoft/AL#2799]
Request to update an already Published Event **OnAfterCreateDimTableIDs** by adding VAR to last 2 parameters of the Published event, as this function has parameters (arrays) which can be used to generate new dimension set entry based on newly added fields by using their respective default dimension :

Existing :
LOCAL [IntegrationEvent] OnAfterCreateDimTableIDs(VAR GenJournalLine : Record "Gen. Journal Line";FieldNo : Integer;TableID : ARRAY [10] OF Integer;No : ARRAY [10] OF Code[20])

Modified :
LOCAL [IntegrationEvent] OnAfterCreateDimTableIDs(VAR GenJournalLine : Record "Gen. Journal Line";FieldNo : Integer;VAR TableID : ARRAY [10] OF Integer;VAR No : ARRAY [10] OF Code[20])

Same changes should also be implemented for all other Document tables where CreateDim function is used and OnAfterCreateDimTableIDs is Published (ex : Table 36 "Sales Header", Table 38 "Purchase Header")

**Comment by AlexanderYakunin** [comment]
This is already done this way long time ago, please check latest code base

**Comment by ashishsharmanav** [comment]
Couldn't find the relevant changes till Navision 2018 CU 5, Is it after the CU 5?

**Comment by StanislawStempin** [comment]
This repo is not related to NAV 2018. 

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by ashishsharmanav** [comment]
Alryt Thanks, Closing the Issue,
