### ISSUE TITLE
Suggestion: default name of packages folder to .alpackages

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#280]
I want to suggest to change the default name of the packages folder to .alpackages

Changing the name from packages to alpackages to make it crystal clear this is a folder used by the AL language extension.

Adding a leading dot makes the folder to stay on top instead of mixed up with other folders that are created by the developer, e.g. folders containing AL objects or other files that must be included with the output. The folders with a leading dot (like the .vscode folder) are considered to be folders that contain files which are essential for the development environment but excluded from output.

**Comment by StanislawStempin** [comment]
Good suggestion.
In the meanwhile you can change the default location by adding the following setting to your user or workspace settings:
`"al.packageCachePath": "./.alpackages"`

**Comment by ajkauffmann** [comment]
Yep, already did that in my current workspace. ;-)
Looks so nice, thanks for supporting the idea!
