### ISSUE TITLE
CodeUnit File Management function OpenFileDialog bug

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#2800]
Hi,

When I call Codeunit "File Management" function OpenFileDialon
ClientFileName := FileManagement.OpenFileDialog('Select the picture','','');
  I recieve an error message: 
![err](https://user-images.githubusercontent.com/39334704/42321583-2a4183ee-8062-11e8-8d0f-36f7e0592f2f.PNG)
Why is that? Does anyone have the same issue?

**Comment by linasostreika** [comment]
@thpeder Hi, do you have any new about this issue?

**Comment by thpeder** [comment]
Hi @linasostreika,
No I don't have any more information to you at the moment, but thanks for reporting the issue.

**Comment by StanislawStempin** [comment]
This feature can only be used in the windows client since it relies on client-side .NET.

The function should probably be marked as Internal.

**Comment by linasostreika** [comment]
@StanislawStempin so "File Management" function OpenFileDialog can not be used in Extensions?

**Comment by StanislawStempin** [comment]
It can be used in Extensions with Target = Internal (meaning On-Premise) and only in the Win Client. But cannot be used in the cloud or in the web client.
