### ISSUE TITLE
External functions in Page 5077 Create Interaction

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2801]
We are using the following functions from page 5077 Create Interaction in a Page Extension:
Local UpdateUIFlags
Local AttachmentReload

_Later Edit:_
I just discovered that also function **CheckStatus from Table 5077** (Segment Line) needs to be external.

Could you please make these Global and External ?

Thanks

**Comment by PooyaKharamesh** [comment]
Hi

Thanks for the your request. We have got similar requests. These functions either control the UI behavior or do the validations or similar behaviours and shouldn't be external, having said that I agree with you that there is a need to call these functions from the page extensions. Therefor after a discussion about the proper solution we added these requests to our backlog for implementation.

Thanks and regards
Pooya
