### ISSUE TITLE
Variables in field trigger not recognized

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#281]
Variables declared in field trigger event are not recognized in code.
See screenprint. Variable textvar is declared, but not recognized as a variable. The contextual intellisense doesn't show the variable.

![image](https://user-images.githubusercontent.com/19155831/27217531-803aebda-527a-11e7-922c-68debff3f90e.png)

**Comment by StanislawStempin** [comment]
Thanks, it reproduces on the latest codebase. We will have a look into it.
