### ISSUE TITLE
CS1955: Non-invocable member 'Microsoft.Dynamics.Nav.Runtime.NavTestField.ALCaption' cannot be used like a method

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#2811]
I am trying to publish with my testcodeunits with the build . But i am unable to publish the package. Can somebody tell me what is the reason behind this .Please find the attachment

![image](https://user-images.githubusercontent.com/39740300/42377728-28e1fbce-8142-11e8-9922-7bfdf2e3a7e8.png)

Al compiler version : 0.17.22710
Nav build : 13.0.22815

**Comment by thpeder** [comment]
Hi @srinivasbanny,
It looks like you have a TestField which you call the procedure Caption on in Codeunit 70011509.
If you could please find the code and send back a small snippet so we have a clear repro of the problem, since that makes it much easier to fix.

**Comment by srinivasbanny** [comment]
@thpeder  i didn't find the testfield anywhere in the test codeunit .but what i observed is the normal procedures and handler procedures are in different order i made them in the order 
but still i am facing the same issue .please suggest

**Comment by srinivasbanny** [comment]
@thpeder  i found the issue in my code i am verifying the caption of the control in page .if i comment my below code it is running properly ,but if we can check the code in standard 
Referance : testcoduenit no. 134327 procedure PurchaseAnalysisMatrixRequestPageHandler() i am doing the same way to my code .
![image](https://user-images.githubusercontent.com/39740300/42383610-573b7f64-8155-11e8-98e4-d696de64d51e.png)


**Mycode:** 
Assert.AreEqual(SendEmailAlertonTimesheet,TimesheetConfig."EmailAlertOnApproval PGS".CAPTION,RecordsMisMatchErr);

**Comment by thpeder** [comment]
@srinivasbanny I don't think there is a workaround for you to get the caption.

**Comment by grabnar** [comment]
Hello @thpeder, any progress on this bug?
