### ISSUE TITLE
How to create different CU NAV Server Instance on the same server?

### ISSUE THREAD

**Issue by robertoscaringella** [Microsoft/AL#2816]
Hi,
I need to create different NAV Server Instance of different CU NAV Version. I have installed on the server the NAV2018 CU5 and with the standard NAV cmdlet I create New NAV Server Instance with this command:"New-NAVServerInstance -DatabaseServer NAV2018 -DatabaseName "Demo Database NAV_2018_CU4" -ClientServicesPort 7146 -SOAPServicesPort 7147 -ODataServicesPort 7148 -ManagementServicesPort 7145 -DeveloperServicesPort 7149 -Verbose", but I cannot choose the CU Version and also I cannot choose the path of installation. I making sothing wrong? You have some suggestion/solution? With the installation of the web client will I have the same problem?

Thank you in advanced,
Roberto.

**Comment by StanislawStempin** [comment]
Please contact regular support channel. Your question is not related to Business Central nor to AL development.
