### ISSUE TITLE
vsix.err file after installing VS Code extension

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#2819]
I noticed a vsix.err file in the AL extension folders. It seems to happen with all vsix installation, not with the downloaded extensions from marketplace. Maybe it is only local, but then I would like to know if something is missing on my computer.

Content of the vsix.err file:

```
vsce.cmd : Executing prepublish script 'npm run vscode:prepublish'...
At C:\a\285\s\build-vsix.ps1:123 char:1
+ & vsce package --baseContentUrl https://www.microsoft.com/en-us/dynam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Executing prepu...:prepublish'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

```

I noticed because version 0.17.27450 didn't install correctly. For (yet) unknown reason, the extension did not show up in the installed extension list after installing from the vsix file. But the extension installation folder in %USERPROFILE%\.vscode\extensions was there, including the vsix.err file. Then I went back to previous versions, and all of them had the same file.
Eventually I got 0.17.27450 installed by reinstalling 0.16.14305 and then install a few newer versions up to the latest. Still no idea why it couldn't be installed correctly in the first place.

**Comment by thpeder** [comment]
Hi @ajkauffmann,
It is an error we are getting when building the extension, it shouldn't impact you in any way, but we will do some more investigation on it.
Regarding the failed installation of the extension, if you run into the problem again could you try in VSCode to run the command "Toggle Developer Tools" and install the extension again to check if there is anything logged to the console.
