### ISSUE TITLE
Error message when Json object is not passed by var

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#282]
Got this error message:
Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'This program location is thought to be unreachable.'

Steps to reproduce: on a function, declare a parameter of any of the Json types without using var.

**Comment by StanislawStempin** [comment]
Thanks, this is already fixed based on you finding the same issue during the workshop:)

**Comment by ajkauffmann** [comment]
Yeah, I wasn't sure about that. But not it is least documented as an issue here. ;-)
