### ISSUE TITLE
error AL0185: Codeunit 'ArchiveManagement' is missing

### ISSUE THREAD

**Issue by robertoscaringella** [Microsoft/AL#2820]
Hi,
I created an app with VS Code for a custom (with in old style mode C/Side and C/AL) NAV2018CU4 db, I downloaded the symbols, in the symbols I see all the objects and all the fields added, and all the standard object.

I created one custom report with VS Code, and I added a codeunit variable linked to ArchiveManagement (I see ArchiveManagement in the symbols).

When I publish and debug the report from VS Code (F5 Key), VS Code return this error message: "dev/apps?tenant=default&SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed
Layout/al/report/Report%2050100%20-%20RPT%20Sales%20Order.al(1161,29): error AL0185: Codeunit 'ArchiveManagement' is missing"

If I publish and debug the same app on the standard database, run FINE.

Could you help me?

Thank you in advanced,
Roberto Scaringella.

**Comment by robertoscaringella** [comment]
Hi @thpeder,

NAV version: 
- 2018 CU4 (Build 21441)

Symbols in VS Code:
- Application: 11.0.21441.0
- System: 11.0.12925.0

Now, I tried to download the symbols and now there are missing some objects.

Roberto.

**Comment by thpeder** [comment]
Hi @robertoscaringella,
it seems like you don't have every object compiled while CSide was enabled to generate symbol information.
Open CSide with the argument `generatesymbolreference=yes`, recompile every object and download symbols again.

Here is the docs link if other people finds this issue: [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)
