### ISSUE TITLE
microsoft/bcsandbox missing data

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/AL#2827]
I have noticed that Docker image for Business Central has no data in it.
Is this intended?

Docker image version: 12.2.22932.23097.

Database: FinancialsW1.
Company: My Company.

Command for creating the container:
```
docker run -it --name mytest -h mytest -m 4g -e accept_eula=Y microsoft/bcsandbox
```

**Edit:** I am talking about W1 image.

**Comment by tfenster** [comment]
Company "CRONUS USA, Inc." should have Cronus data

**Comment by ikoletic** [comment]
Yes, for W1 docker image it is intended.
W1 Docker images come exactly as you described. Only with My Company and without demo data pre populated. 
Demo data is, however, loaded to image (look for Configuration Files, you'll find both Evaluation and Standard RS packages). You just need to import and apply the package.

**Comment by tfenster** [comment]
thanks @ikoletic for correcting me. The company I mentioned only exists in the bcsandbox:us image

**Comment by ernestasju** [comment]
Thank you. I have found configuration packages.

But it is still unclear how to import them using Powershell (I already tried ordinary way).
I tried to use Powershell command Import-NavConfigurationPackageFile, but that did not do anything.

**Comment by StanislawStempin** [comment]
Did you get some errors when running the command? Have you specified all required parameters and executed it from the Docker powershell command prompt? 
https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/import-navconfigurationpackagefile?view=dynamicsnav-ps-2018

**Comment by ernestasju** [comment]
No. Command runs just fine. The Import-NavConfigurationPackageFile command only imports package so it would be used when creating new company (from user interface).
New-NavCompany command can only use EvaluationCompany data - for example, you cannot use Extended data package, or custom data package.
