### ISSUE TITLE
COD312 Cust-Check Cr. Limit - SalesHeaderCheck

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#2829]
SalesHeader should be passed as VAR parameter in COD312 Cust-Check Cr. Limit in SalesHeaderCheck !
If not (current situation): any changes to SalesHeader (via OnCustomerCreditLimitExceeded) are lost !

![cod312](https://user-images.githubusercontent.com/34303738/42450607-08dea0da-8385-11e8-9596-81203afdcd45.png)

NAV2018CU3

**Comment by kalberes** [comment]
According to the owning team this will be fixed for the Fall release versions

**Comment by SirBETE** [comment]
Better late than never ...
TY! :)
