### ISSUE TITLE
Compiler error message when calling a member directly on the returned Json object

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#283]
Got this error message, so I dutifully follow this.

Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'This program location is thought to be unreachable.'

Steps to reproduce:
Use a Json object as return type of a functon an call a member directly on the return.
First screenshot is the function, second how I tried to use it. (I know, no error handling here)

![image](https://user-images.githubusercontent.com/19155831/27219353-b46a412e-5281-11e7-9511-2ed95b9b2e7e.png)

![image](https://user-images.githubusercontent.com/19155831/27218926-229bc0d4-5280-11e7-80d5-b3580412e6b0.png)

**Comment by StanislawStempin** [comment]
This is also already fixed. Thanks for reporting.
