### ISSUE TITLE
Initializing Table Data

### ISSUE THREAD

**Issue by fibbert** [Microsoft/AL#2833]
Hi Everyone,

I want to initialize table data with about 100 rows.  I see the examples which are essentially hard-coded data in code units.  Is there a more elegant way? Is there someway to embed an XML file in a manifest and read from it into the table?  What have other users done?

Thanks
-Rob

**Comment by thpeder** [comment]
Hi @fibbert,
You can publish table data with your extension which allows you to seed your tables. Take a look at [Exporting data for Extensions.](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-data-for-extension#to-export-table-data)
