### ISSUE TITLE
Error or warning if XLIFF translations are missing.

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#2834]
I have already searched all existing topics. Unfortunately I could not find a similar question on this subject. So far the English XLIFF files are created automatically. Now it can happen that you have already created several additional language files, and now make a change to the code. And here it is very easy to forget to adapt the other languages. In my view, this is actually a mistake, but at least a warning. How can you notice as a developer that you have to add something here if you don't know how and where. I think it would be enough to display a message here, where in the way like the error message if a key already exists in the file. This would ensure that all translations have been entered. That in itself would only be a small thing, but it could make your life much easier.

**Comment by thpeder** [comment]
Hi @FSharpCSharp,
Thanks for the feedback!
We have been hearing this from other people as well and it is on the backlog but I don't have any time frame for you regarding when it will be there.

**Comment by FSharpCSharp** [comment]
@thpeder 
Thank you very much for the information! I'm glad to hear you've already grasped the subject. Then I'm curious, and I'm looking forward to it.

**Comment by thpeder** [comment]
Hi,
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
