### ISSUE TITLE
Add publishers on page 542 Default Dimensions-Multiple

### ISSUE THREAD

**Issue by bogdan81GitHub** [Microsoft/AL#2838]
Hello,

In  our solution we have added in table 352 Default Dimension a new field  "Dimension Value Range" in order to manage ranges of dimensions.

We need one publisher in the function SetCommonDefaultDim, after the line DefaultDim.INSERT(TRUE)  with following signature:
OnAfterSetCommonDefaultDim(Rec,DefaultDim)
DefaultDim should pe passed with var.

The code we need to migrate is in the printscreen below:
![setcommondefaultdim](https://user-images.githubusercontent.com/30693206/42506679-1cebedbe-8432-11e8-8b87-97d766e04d0b.png)

Also we need another publisher in function GetDefaultDim with following signature:
OnGetDefaultDim(Rec, TempDefaultDim2) that should be position were the green code is in the printscreen below.
Rec should pe passed with var.

![getdefaultdim](https://user-images.githubusercontent.com/30693206/42506476-88598bb6-8431-11e8-9b6f-858a5282dbda.png)

Thank you

**Comment by RonKoppelaar** [comment]
Any update on the event request?

**Comment by cosminah** [comment]
We need also the requested publisher OnGetDefaultDim, OnGetDefaultDim(Rec, TempDefaultDim2).
This will be done?

In BUILD 13.0.23896 I cannot find it.
