### ISSUE TITLE
How do I change path where compiled NAVX is created?

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#284]
I know there's a property to change where the "packages" folder lives, however when I press F5 to compile and deploy my extension, the NAVX file is created at the root of my repo. Is there a way to change this so that the NAVX file is created somewhere else?

**Comment by StanislawStempin** [comment]
This is currently not possible when building from vscode directly. However you can achieve it by using alc.exe:
```
alc.exe /project:<path to project folder> /packagecachepath:<folder containing navx reference packages> /out:<path to output navx file>
```

We will consider adding a setting to the vscode extension to control the output path

**Comment by MikeGlue** [comment]
Closing this as it is old and using the command line is sufficient for my needs.
