### ISSUE TITLE
Select/mark records in a TestPage

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#2840]
We have the following feature that we want to test:

- There is an action in Page A.
- The action shows Page B using RunModal().
- Page B shows, in a subpage (Page C), a list of records. 
- Page C is showing a temporary table, with records created when the action in Page A was pressed.
- When the user presses "OK", we get all the data entered in Page B, and use it to create a new record for each selected record (in the subpage).

In order to test this feature, we need to invoke the action in Page A, and use TestPage variables to work with the dialog that shows a list of records to select... and we are stuck there.

Is there any way to "select" records in a TestPage of List type?

**Comment by esbenk** [comment]
This is not possible today. The feature is on our backlog but without any ETA.
