### ISSUE TITLE
Can't use CalcFormula on FlowField

### ISSUE THREAD

**Issue by dmytrk** [Microsoft/AL#2842]
Can't use CalcFormula (it's hard to believe) on FlowField.
- AL Extension Version: "December Update (CURRENT)"
- AL Compiler version 0.12.15355
- Server Version: "Microsoft cloud sandbox"

adding this field to a table:
        field(2;TableName;Text[30])
        {
            FieldClass = FlowField;
            Editable = false;
            **CalcFormula** = Lookup(AllObjWithCaption."Object Name" WHERE ("Object Type"=CONST(Table),"Object ID"=FIELD(TableNo)));
            // CalcFormula = Lookup(Customer.Name);
        }
Throwing "Object reference not set to an instance of an object." error.
You can find StackTrace and failing project in the 
[CalcFormula.zip](https://github.com/Microsoft/AL/files/2180278/CalcFormula.zip).

The same error if I replace it with CalcFormula = Lookup(Customer.Name) or if use example from https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-flowfields-and-flowfilters .

**Comment by kalberes** [comment]
I have no repro on this. But your setup is not valid. The December update is not a valid one for cloud sandbox. You should  get a newer AL extension version from the marketplace.
