### ISSUE TITLE
How to add new group in existing card page?

### ISSUE THREAD

**Issue by JPALMA11** [Microsoft/AL#2846]
Hello everyone!

I'm trying to add new group in an existing page, is it possible?

**Comment by dNsl9r** [comment]
Sure,
example for "Customer Card":

`pageextension 50100 theBestCustomerCardExt extends "Customer Card" 
{
    layout
    {
        addafter(Statistics)
        {
            group(MyGreatGroup)
            {
                Caption = 'The greatest group ever';
                field("my Great Field";"my Great Field")
                {
                    ApplicationArea = All;
                }
            }
        }
    }
. . .`

**Comment by JPALMA11** [comment]
Thank you very much Sir. 👍
