### ISSUE TITLE
Unable to convert from JsonValue to DateTime

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#285]
The JsonValue has value: 2017-06-16T17:50:06Z
Which is the "o" pattern, according to https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings.

Error message:

![image](https://user-images.githubusercontent.com/19155831/27280937-1a65cb78-54ea-11e7-9831-3ca9a9d3acea.png)

**Comment by StanislawStempin** [comment]
This is a bug, we will investigate.
