### ISSUE TITLE
[Event Request] Codeunit 7310 Whse.-Shipment Release - Issue 2150

### ISSUE THREAD

**Issue by NAVRockClimber** [Microsoft/AL#2857]
Hi,

this is related to my [issue 2150](https://github.com/Microsoft/AL/issues/2150). This is marked as shipped, but the event is not existing in the most current W1 docker container (NAV Version: 12.2.22932.23097-W1). 
There is an event a few lines later at least giving me the possibility to hook in after the releasing a Warehouse Shipment. But being able to skip the commit is crucial for me here. 

with kind regards

**Comment by StanislawStempin** [comment]
Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
