### ISSUE TITLE
Suggestion to allow foreach on Json variables

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#286]
It would be nice to be able to do:

```
foreach JsonToken in JsonArray do begin
...
end;

```
instead of

```
for i := 0 to JsonArray.Count - 1 do begin
  JsonToken := JsonArray.Get(i, JsonToken);
  ...
end;

```

**Comment by waldo1001** [comment]
It would be nicer to be able to do:

```
foreach JsonToken in JsonArray {
...
}
```

;-)

**Comment by ajkauffmann** [comment]
Didn't want to push it... But yes, you are right. Another issue, though.

**Comment by StanislawStempin** [comment]
Thanks, we'll include these suggestions for long-term backlog consideration.

**Comment by waldo1001** [comment]
well .. syntax shouldn't be long-term ;-).  
On the other hand, you're probably talking about the "foreach" part..

**Comment by StanislawStempin** [comment]
Foreach will be available in October Update.
