### ISSUE TITLE
Function Request : CalcCell in AccSchedManagement (CodeUnit 8)

### ISSUE THREAD

**Issue by ClintonSaunders** [Microsoft/AL#2865]
Please make the function "CalcCell" in Codeunit 8 - AccSchedManagement an "External" available function so that it can be referred to in Extensions. I am creating a custom version of the KPI Service page and need to be able to call this function.... not sure why the FunctionVisible property is Internal.

**Comment by grobyns** [comment]
Thank you for your request! We have exposed the function in the upcoming major release.
