### ISSUE TITLE
Suggestion: Report an 'unused function' as an 'Info' message

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#2868]
That would be nice: 😀

**Comment by MODUSCarstenScholling** [comment]
I feel I am too late, but a local function with no reference should show as a warning while (another rule) should show unused global procedures as info.

**Comment by mjmatthiesen** [comment]
It'd be a nice rule. A long time ago, I wrote an extension to figure out what was/wasn't local:
https://marketplace.visualstudio.com/items?itemName=mmatthiesen.localize-lens

Source is available so you can modify as needed. Keep in mind you may want some things public for extensions that the base product doesn't use.

**Comment by DavidFeldhoff** [comment]
I think we should consider the access modifiers as well. So global procedures could be marked as unused if the codeunit is interal (or the procedure itself)
