### ISSUE TITLE
Publish-NAVApp 

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#287]
I don't seem to be able to publish an extension with PowerShell.  I know it's done by the dev environment, but I should be able to publish it with PowerShell once I want to go live with it, I guess.

Is it normal it isn't possible for ExtensionV2 yet?

If so, what is the scope?  Is it going to be possible?  How else would I publish an extension on a new (live?) environment?

**Comment by StanislawStempin** [comment]
The Publish-NavApp is not supported for Extensions V2.
For the cloud the final deployment will happen through AppSource. For on-prem we haven't finalized the design yet but quite likely the deployment will go through the http dev endpoint and there likely will be a powershell wrapper available for it.

**Comment by waldo1001** [comment]
clear!
