### ISSUE TITLE
Suggestion: ID placeholder for AL to get rid of IDs

### ISSUE THREAD

**Issue by megel** [microsoft/AL#2872]
Just an idea, what if we could remove IDs simply from AL development?

1) IMHO the IDs are not necessary when you write code in AL except when you define new objects or extend objects.
1) The NST compiler will check the IDs during publishing

Let's us a `NAVautoID` as placehloder which will be **resolved and replced** during publishing and compilation **by the NST** . This could look like this:
```javascript
page NAVautoID "MyPage"
{
   // some code
}

table NAVautoID "MyTable"
{
   fields
   {
        field(NAVautoID; MyField; Integer)
        {}
   }
}

tableextension NAVautoID "MyTableExt" extends Item
{
   fields
   {
        field(NAVautoID; MyText; Text[30])
        {}
   }
}
```

In the application manifest `app.json` we could add a section / element where we are able to add JSON files which contains the licensed IDs e.g.:
```json
{
     "NAVautoID": {
           "Table": ["50100..50150"],
           "Page": ["50100", "50102", "50200..50300"]
     }
}     
```

Could this work? What do you think?

**Comment by FSharpCSharp** [comment]
That sounds like a great idea! Then you would be able to completely save yourself the renumbering in the future. Furthermore, it would also be much easier to expand, and one would not always need to know the free IDs. I hope that Microsoft will take care of this issue in any case.

**Comment by esbenk** [comment]
Unfortunately not. From a compiler perspective it could, but not without major changes to the runtime. 

Specifically tables are problematic. For synchronization and upgrade we rely the ids for a specific table to be fixed. 

Persisted RecordIds contains the table id, and that will break if you suddenly get a different id for the table.

**Comment by megel** [comment]
@esbenk, I believe it could be possible. From outside we don't need the IDs and from inside, NAV can save the used IDs in a special table, for reuse after update by sync/upgrade. The identification of fields and tables can be done by `Name` and `Type`.

Another possibility is to add an unique ID e.g. a `GUID` to fields and objects. Both would not break something like persisted RecordIds, because the used (internally stored) ID is still the same.

The only question is, how to transfer the possible / licensed IDs to the NST? Add them to the `app.json`?

**Comment by kine** [comment]
It will be problematic when I will want to rename existing filed. It will automatically create new one instead rename.

**Comment by RafaelKoch** [comment]
Is the NAVUUID just another Identifier just like the combination of type and ID we have today?
Anyway I still like the idea a lot because that could maybe help build for topics most of us will be struggling with that are not directly related to getting rid of IDs. Just some thoughts:

+ help identifying a connection between a label/caption in a translation file and its location in the code
+ help to identify if extension dependencies are actually really used. We could use the unique identifiers proposed to build a "database" of given structures and query if they are used more easily. 
* probably more...

**Comment by JSebastianN** [comment]
Good thinking!
As an ISV who maintain a solution from NAV 2009 til AL, I work hard to have the same code in the same objects for easy maintenance.
So I need my AL file to still contain a reference to a numbered object for the c/side versions...

**Comment by kalberes** [comment]
Long term plan. We are at the early namespace phase
