### ISSUE TITLE
How to make my Dynamics 365 BC available online using Docker container?

### ISSUE THREAD

**Issue by JPALMA11** [Microsoft/AL#2874]
Hi everyone!

I just want to ask if it is possible to get my Dynamics 365 BC online? if yes how?

Thank you.

**Comment by dNsl9r** [comment]
Please explain what do you want to do in detail. I do not understand what you mean. You can download docker images of microsoft d365bc.

**Comment by ashik-ivor** [comment]
This is for windows. 
Run the docker with windows containers. (Right click and click on windows container, if its showing switch to Linux container, then leave it as such.)
Open the Powershell in Admin, download the image 
1. download the image "microsoft/bcsandbox:us"
2. create a new container using 
New-NavContainer -accept_eula -imageName "microsoft/bcsandbox:us" -includeCSide -licensefile <path> -containerName BC -auth Windows

**Comment by StanislawStempin** [comment]
Please check the following GitHub forums for more information. 
Keep in mind that the Docker images are meant only for development and testing, not for hosting a production system on them. 
**https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
