### ISSUE TITLE
Application Area is missing

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#2875]
Hi all,

Application Ares is missing for some fields in page 1 - Company Information and fields are not visible in extension:

![image](https://user-images.githubusercontent.com/34686682/42625243-8fe54496-85c7-11e8-9114-bf4bc8c9c2fb.png)

Regards,
Radovan

**Comment by grobyns** [comment]
Hi,

these fields are part of MX localization so they are only tagged in MX builds.

br/Gert

**Comment by grobyns** [comment]
Hi,
I'm closing the issue for now as there hasn't been a reply in a while.
br/Gert

**Comment by radovandokic** [comment]
OK, thanks
Radovan
