### ISSUE TITLE
HttpContent not allowed as return type of a function

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#2880]
Previously it was possible to use HttpContent as return type of a function (checked with build 0.16.19969).

But starting with 0.17 builds, it is not possible anymore. I get a message 'HttpContent is not a valid return type'. 

Is this by purpose?

**Comment by kalberes** [comment]
Yes unfortunately. The implementation allowing it, was not correctly integrating into the server's internal implementation of complex types that can be shared instances.

**Comment by ajkauffmann** [comment]
Ok, thanks, then I will test if passing them by var will work. I guess it does.
