### ISSUE TITLE
txt2Al unspported feature warning

### ISSUE THREAD

**Issue by ayhanozbay** [Microsoft/AL#2881]
Hi,

when we try to convert simple page modification to page extension via txt2al, we get warning like " Unsupported feature: Unknown on "(Action: TEst)". Please convert manually". this change is very simple and adds only one action to sales order list page. (we already tried different tests like adding field to a standard page or adding a new field to a standard table, but the result were same: Unsupported feature: Unknown on ....)

here is the command list that we run:
[commands.txt](https://github.com/Microsoft/AL/files/2189189/commands.txt)

those are the files we generate:

[Original.txt](https://github.com/Microsoft/AL/files/2189182/Original.txt)
[Modified.txt](https://github.com/Microsoft/AL/files/2189183/Modified.txt)
[PAG45.DELTA.txt](https://github.com/Microsoft/AL/files/2189186/PAG45.DELTA.txt)
[PAG45.al.txt](https://github.com/Microsoft/AL/files/2189177/PAG45.al.txt)

what is wrong with our procedure?

PS: we are running the test on nav build 11.0.23019.

**Comment by qutreson** [comment]
Hi @ayhanozbay, this issue has been fixed in our master. You should use a newer version of the txt2al in order to access the fix we made.

The result is as follows:
```
pageextension 70000001 pageextension70000001 extends "Sales List" 
{
  // version NAVW111.00.00.19846

  actions
  {
    addafter("Sales Reservation Avail.")
    {
      action(TEst)
      {
        RunObject = Report "General Journal - Test";
      }
    }
  }
}
```
