### ISSUE TITLE
Add  function Patch to HttpClient

### ISSUE THREAD

**Issue by finstx** [microsoft/AL#2889]
Rest APIs use http method "patch" to update resources.
For example the Graph API: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_update

The httpClient seems to support only get, post, put and delete.
Please add the missing http method(s).

Is there a workaround to make "patch" working with current implementation of HttpClient?

thanks &
regards

Tobias

**Comment by kalberes** [comment]
None as far as I know.

**Comment by StanislawStempin** [comment]
Have you tried the following? 
```
procedure Test()
    var
     client : HttpClient;
     request : HttpRequestMessage;
     response : HttpResponseMessage;
    begin        
        request.Method('Patch');
        client.Send(request, response);
    end;
```

**Comment by finstx** [comment]
I get an error message:
Invalid value for parameter httpMethod: patch

        if httpMethod = 'patch' then begin
            httpReqMsg.Method('patch');
            httpReqMsg.Content.WriteFrom(content);
            httpReqMsg.GetHeaders(httpHeaders);            
            httpHeaders.Remove('Content-Type');
            httpHeaders.Add('Content-Type', 'application/json');
            _HttpClient.SetBaseAddress(url);
            _HttpClient.Send(httpReqMsg, httpRspMsg);
        end;

**Comment by finstx** [comment]
I get a 400 - Bad Request

{
	"error": {
		"code": "BadRequest",
		"message": "Request type is not supported.",
		"innerError": {
			"request-id": "7268c0c6-cee7-49bd-8ba9-ec821aa318e3",
			"date": "2018-07-14T06:37:21"
		}
	}
}

From Postman it works.

My code is:

httpContent.WriteFrom(content);
httpContent.GetHeaders(httpHeaders);            
httpHeaders.Remove('Content-Type');
httpHeaders.Add('Content-Type', 'application/json');
httpReqMsg.Content(httpContent);
httpReqMsg.Method('patch');
httpClient.DefaultRequestHeaders().Add('Authorization', StrSubstNo('%1 %2', 'Bearer', accessToken));
httpClient.SetBaseAddress(url);           
httpClient.Send(httpReqMsg, httpRspMsg);

Another problem is that I can't change BaseAddress after the first Send() call.
So I have to use a new httpClient for every call.
My experience is that using a new httpClient for every call consumes a lot of resources, if making a lot of calls.

**Comment by finstx** [comment]
Can you foresee, when it'll be  available in NAV 2018?
We need it for a project with a golive date in 2018.

It would be really annoying, if we have to implement the patch calls in C/AL and every other calls in AL.

thanks &
regards

Tobias

**Comment by finstx** [comment]
Stanislaw's code snippet works, if you change

request.Method('Patch');
to
request.Method('PATCH');

(uppercase PATCH).

**Comment by StanislawStempin** [comment]
Thanks @finstx. I updated my sample with this fix

**Comment by eivindgiske** [comment]
Odata API (for example in NAV 2016) also uses MERGE. Not quite the same as PUT, because MERGE only updates the fields specified in the body, whereas PUT NULLS the non-specified fields. Should also support MERGE, but I can also confirm the "workaround" works

**Comment by pborring** [comment]
I am going to close this issue as PATCH is supported, but as HttpClient.Send(). You can find more about HttpClient in the Docs e.g., https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-httpclient#supported-http-methods
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-send-method
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-send-method#example-http-patch
