### ISSUE TITLE
Suggestion: Please provide "Microsoft.ClearScript" or an other solution to evaluate formular

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/AL#289]
Hi,

we are using "Microsoft.ClearScript" in our solution to evaluate user defined formulars.
Can you please add a Function to Evaluate Scripts to AL?

**Comment by pborring** [comment]
Thanks for logging this. With cloud not supporting .net, nor scripts natively in AL, this 6 year old suggestion is still not in our backlog. If still relevant, you can suggest it on https://aka.ms/bcideas. Likely it will not be prioritized, but it also depends on amount of votes.
Closing the issue, as this GitHub only tracks bugs for the VSC VSIX and AL language, not suggestions for new functionality.
