### ISSUE TITLE
No standard Cronus International company in BC Insider latest image

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#2891]
Hi,

I have made a pull to bcinsider.azurecr.io/bcsandbox-master latest version (13.0.23231.0-W1) and after that when i try to open the webclient i am getting the below message:
![image](https://user-images.githubusercontent.com/26792519/42721557-54c2043c-875a-11e8-84e0-70d9b8a99425.png)

When i click next and click start trial it is intializing an empty company with name "MyCompany".

Can you please let me know what happened to the standard company and how to get that?

Thanks & Regards
Varun Reddy

**Comment by dNsl9r** [comment]
See #2827 in W1 there is no Cronus Company.

**Comment by bachii1010** [comment]
@dNsl9r  thanks for the update
