### ISSUE TITLE
[Function Expose] GetPrivacyBlockedGenericErrorText TAB18 and Tab23

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2897]
In our localization Scope we've a specific Check object. As the standard object we are using the function GetPrivacyBlockedGenericErrorText on table Customer and Vendor. So we would like to request to expose the function.

**Comment by thpeder** [comment]
Hi @martinhocosta88,
It will be part of the next major release.
You can read about the release schedule: [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
