### ISSUE TITLE
Publishing table extension fails in June update with SQL error

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#290]
I have a very simple table extension, actually doesn't contain anything but modify field. It fails on June update. Same code publishes fine in April update. Originally I had an OnBeforeValidate event added, but removing it didn't solve the issue. Here is a screenshot with the minimum of code that causes the error.

![image](https://user-images.githubusercontent.com/19155831/27345046-af2e1914-55e8-11e7-9251-f7c78e00bf1a.png)

**Comment by StanislawStempin** [comment]
This is an issue with processing field modifications. We are looking into it.
