### ISSUE TITLE
Publish/Create Package indication suggestion

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2900]
Is it possible to add some more info during the package-action (CTRL + SHIFT + B) and the Publish-action (F5) as well?

For example:

![image](https://user-images.githubusercontent.com/28626283/42752083-1eeb47a8-88ed-11e8-8f42-81b33399e8d1.png)

**Comment by StanislawStempin** [comment]
We have added the following message when starting the build process:
`Compilation started for project 'X' containing 'Y' files at 'HH:MM:SS.mmm'`

**Comment by bvbeek** [comment]
👍
