### ISSUE TITLE
Business Central: Publishing an extensions fails when path to extension contains space

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/AL#2902]
- AL Extension Version: 0.16.19969
- Server Version: 12.2.22932.23097-W1

When path to extension contains space, extension publishing fails.

I've created demo extension using AL: Go! command in "C:\Users\ernjus\Desktop\my test".
When publishing VS Code shows
```
Microsoft (R) AL Compiler version 0.16.19969
Copyright (C) Microsoft Corporation. All rights reserved

Success: The package is created.
```
in OUTPUT and
```
[2018-07-16 13:55:40.64] Error: An internal error has occurred
```
in DEBUG CONSOLE.

Changing extension path to "C:\Users\ernjus\Desktop\mytest" fixes that.

**Comment by qutreson** [comment]
Hi @ernestasju, thank you for reporting this issue. I could reproduce this issue on the extension from the marketplace, but it is now working in our current master branch. The fix will then be available with the next update.

**Comment by tfcrowther** [comment]
Check you are using the latest AL Language Extension within VS Code. 
Find the ALLanguage.vsix file where you install the RTC.

Open the Command Pallatte > Extensions: Install from VSIX > "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\130\AL Development Environment\ALLanguage.vsix"

Reload

Uninstall the older AL Language.

Reload

Try Ctrl+F5
