### ISSUE TITLE
Test Extension - "Reference to object Assert is ambiguous..."

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#2903]
I get following error message in the pre-compiler, when i try to reference the test toolkit from NAV:
```
Reference to object Assert is ambiguous. Make sure you are not referencing packages containing objects with the same names.
```

I'm working in a docker Environment and I created this as follows:
```
New-NavContainer -accept_eula -containerName DevPreview -imageName bcinsider.azurecr.io/bcsandbox-master:de -enableSymbolLoading -licenseFile C:\temp\license.flf -includeCSide -includeTestToolkit
```

In my app.json file I added the test setting with the value "12.0.0.0". When I delete this setting everything works fine, but when I add it, as shown in the docs, the error appears.

**Comment by qutreson** [comment]
Hi @OlivierHellmann, it looks like the symbols already got included in the application symbols. We will investigate this issue.
