### ISSUE TITLE
Microsoft/AL: Business Center - Automatic create put-away

### ISSUE THREAD

**Issue by EelcoWijr** [Microsoft/AL#2905]
We have created in Business Central a new location with directed put-away and pick. Also we have enabled the check mark Always create Put-away Line.
![image](https://user-images.githubusercontent.com/40356789/42759712-39c3f26c-8908-11e8-9ddc-0b9d3f64940a.png)

But when we post a warehouse receipt document, then no put away is created. Also we don't receive an error. When we open the posted warehouse receipt document and we choose the button Create Put-Away, then the put-away document is created. 

Why is the put-away document not created automatically? Like in Microsoft Dynamics NAV?

**Comment by StanislawStempin** [comment]
This question is out of scope for the AL development repository. Could you please use the Yammer group or contact official support channels.
