### ISSUE TITLE
FindAttributeValue from table "Item Attribute Value Selection" (7504)

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2909]
Per #2065 this function is to be marked as External. What build was this released in?
I am using the Docker image with NAV Build 22932, microsoft/bcsandbox:gb downloaded 2018-07-13. 

![image](https://user-images.githubusercontent.com/4333956/42767853-f17833d4-8915-11e8-9def-55cde2c1c322.png)

**Comment by StanislawStempin** [comment]
GitHub fixes are tied to bcsandboxmaster images. Please read the following for a full explanation:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
