### ISSUE TITLE
Event Request - Modify Placement of Publisher

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#2910]
Codeunit 86 Sales-Quote to Order
The publisher OnBeforeInsertSalesOrderHeader seems to have been placed in the wrong place. It is located before the modify instead of before the insert is executed. If necessary, a second publisher should be used at the specified location.

**Comment by ThorstenEngelsGOB** [comment]
The same places are shown in the following codeunits:
87 - Blanket Sales Order to Order
96 - Purchase Quote to Order
97 - Blanket Purch. Order to Order

Why is it important to add another publisher?
So that we can set a SingleInstance flag before the Insert(true) is executed to prevent the processes of the subscribers that trigger the RunTrigger. This is necessary so that data is transferred from the quote to the order but not reloaded.
@qutreson

**Comment by Pieterheinevdm** [comment]
yes the name of the publisher is now really misleading.

**Comment by NKarolak** [comment]
About codeunit 86 OnBeforeInsertSalesOrderHeader: This has not been fixed yet even in the D365BC RTM release.

**Comment by NKarolak** [comment]
The very same bug can be found in codeunit 96, function **CreatePurchHeader**.

**Comment by StanislawStempin** [comment]
Reply from the application team:
Placement is correct, name is not good but we cannot change anymore.

**Comment by ThorstenEngelsGOB** [comment]
Why did you close the request. There is still a need of the recommended Events @StanislawStempin

**Comment by elweilando** [comment]
@StanislawStempin what does it mean? 
the reply from the application team is not really a solution.
Will there be a new event publisher? Do you rename the existing wrong named publisher?

**Comment by ThorstenEngelsGOB** [comment]
@StanislawStempin: Still waiting for an answer...
