### ISSUE TITLE
Regarding Language Translation

### ISSUE THREAD

**Issue by ndpatel0074u** [Microsoft/AL#2911]
Hello,

What i have to do if we want only "en-us" language support,
should i create xlf with source and destination both with value "en-us", or i can directly define caption on all occurrence? 
Please suggest.

Thanks in advance

**Comment by thpeder** [comment]
Hi @ndpatel0074u,

When you enable the feature TranslationFile then it will generate a translation file for en-us, so you don't need to do anything beside writing the captions, labels and etc. in the AL code.

**Comment by ndpatel0074u** [comment]
thanks for replying @thpeder 

is it mandatory to generate Translation file ? even i dont want multilanguage support.
I just want en-us language support.

**Comment by thpeder** [comment]
Yes, but if you don't want to see the folder in VSCode then you can hide it with the configuration setting: `"files.exclude" : {"Translations/": true}`

**Comment by ndpatel0074u** [comment]
Hello @thpeder 
We got the response from microsoft app validation team, they suggested below things:

**The reason why the generated translation file doesn’t specify target is because you cannot translate in this file since it’s overwritten on each run.
A simple thing to do (if someone doesn’t want to do proofreading or something else is to simply copy the file and just do a regex repace (below). Just use these expressions in vscode.
(<source>([^<]*)</source>)
$1\n\t\t\t\t\t<target>$2</target>**

so, i have added Target values in whole xlf file with same as source value using above regEx expression
using find and replace.
Now i have the xlf file with source language: en-US and Target language en-US with same source and target values of captions, tooltips etc.
![image](https://user-images.githubusercontent.com/40850576/42861286-fdfa462a-8a77-11e8-8308-70a014b1d4d9.png)

i just need your feedback, is that right or not?

Thanks,
Nishit Patel

**Comment by thpeder** [comment]
@ndpatel0074u yes, that looks fine.
