### ISSUE TITLE
A package with publisher ABC, name XYZ, and a version compatible with a.b.c.d could not be found in .alpackages folder

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#2916]
Extension version: 0.16.16948

I see this error reported in the app.json file. I have a .app file in the .alpackages folder for the app in question with a higher build than is required by the dependency in app.json.

I can build and publish my app and download symbols - it is just the app.json file that complains about this.

**Comment by thpeder** [comment]
Hi @jimmymcp,
The error you are seeing is because you used the build command in VSCode, which is telling you that it couldn't find all the packages specified in the app.json file.
If you were to use alc.exe then it would not give that error, since you don't have any code that uses the symbol information from that package.

**Comment by jimmymcp** [comment]
Hi,

Sorry, I obviously wasn't clear enough - the error is reported under "Problems" for the app.json file. I can build from within VS Code without an error - and I do have code that uses that symbolic info.

![image](https://user-images.githubusercontent.com/19267298/42816299-51d60ccc-89c2-11e8-8771-6197f80bb7b7.png)

**Comment by thpeder** [comment]
I'm surprised to hear that you have code that depends on the symbolic information in the package while it can't find the package, since that should be a compile-time error.
Does Intellisense also find your objects?

**Comment by jimmymcp** [comment]
Yes, I have dependent code and the objects in the dependency appear correctly in intellisense and code which uses them compile and the app builds and publishes.

It is only the app.json file that appears to have a problem with this. Strange, but true. Then again, if it wasn't strange I wouldn't have reported it as an issue :-)

**Comment by thpeder** [comment]
Hi @jimmymcp,
If you could share a small project that reproduces the problem, that would make it a lot easier for us to locate and fix it.

Thanks,
Thomas
