### ISSUE TITLE
How to replace functionality in OnDrillDown in extension

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#2917]
Now migrating our main solution to an extension I am running into the limitation that I cannot use the _OnDrillDown_ trigger on a standard page control within the context of a pageextension object.
We have used this trigger in a zillion places to add a nice feature.

Without going into to details: all tips are welcome how to tackle this in an extension.

BTW: what is actually reason why we cannot subscribe the _OnDrillDown_ action anyway?

**Comment by StanislawStempin** [comment]
Can you give an example of how you would use it from a page extension? And would you require overriding the trigger or is Before/After enough?

**Comment by lvanvugt** [comment]
Hi @StanislawStempin,

Sorry for keeping you waiting while a was enjoying an extended summer vacation. ;-)

On user requests, we are using the DrillDown feature for giving quick access to the related Card page. By addding code to the OnDrillDown trigger the DrillDown control appears on the field control, allowing the user to click on it with their mouse. It tales too long to select an action on the ribbon. And apparently many users are not keyboard oriented.
> Can you give an example of how you would use it from a page extension? 

The following is example on Page 131 (Posted Sales Shpt. Subform) is typically what we have implemented in various pages:
```
    { 4   ;2   ;Field     ;
                SourceExpr="No.";
                OnDrillDown=VAR
                              Item@1000000000 : Record 27;
                              GLAccount@1000000001 : Record 15;
                            BEGIN
                              CASE Type OF
                                Type::Item:
                                  IF Item.GET("No.") THEN
                                    PAGE.RUNMODAL(PAGE::"Item Card",Item);
                                Type::"G/L Account":
                                  IF GLAccount.GET("No.") THEN
                                    PAGE.RUNMODAL(PAGE::"G/L Account Card",GLAccount);
                              END;
                            END;
                             }
```
> And would you require overriding the trigger or is Before/After enough?

For our examples, and given the fact that in almost all cases there is no MS code in those OnDrillDown triggers, Before/After will do.

As we are currently deploying our extension on NAV 2018, it would be great if it could also be down-ported to NAV 2018.

**Comment by lvanvugt** [comment]
@StanislawStempin input given, are you going to pick this up again?

**Comment by StanislawStempin** [comment]
Yes, thank you. We are looking into it.
