### ISSUE TITLE
The type or method 'YYY' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by surajpatel038** [Microsoft/AL#2918]
we need below methods to be opened for our app. Please check.

The type or method 'BLOBImportFromServerFile' cannot be used for 'Extension' development.
==> Codeunit 419: BLOBImportFromServerFile
==> Codeunit 419: BLOBExportToServerFile

**Comment by rishiaurrishabh** [comment]
Hello @surajpatel038 ,

Import and export a file in AL Extension can be handled with 
DOWNLOADFROMSTREAM and UploadIntoStream function.

may be below code will help you export a blob data to a file.

PurchaseHeader.SETFILTER("No.","No.");
TempBlob.Blob.CREATEOUTSTREAM(OStream);
REPORT.SAVEAS(1322,PurchaseHeader.GETFILTERS,REPORTFORMAT::Pdf,OStream);
TempBlob.Blob.CREATEINSTREAM(ReportInStream);
MagicPath := 'abcd.pdf';
DOWNLOADFROMSTREAM(ReportInStream,'','<TEMP>', '',MagicPath);

**Comment by surajpatel038** [comment]
Hello Rishabh Shukla,
Thanks for the update and help.
It worked for us.
