### ISSUE TITLE
Auto-complete issue

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2920]
The auto-complete of a function call within a function call reproduce a compile error:
```
Codeunit.Function(Test.Function();); // Current output reproduce a compile error
Codeunit.Function(Test.Function()); // Expected output

Message(UserId()); // This is working fine (no semicolon after ()
```

So you first write:

`Codeunit.Functio`

press enter, you will get:

`Codeunit.Function();`

place the cursor within the () and start typing 'Test.Functi' press Enter, Result:

`Codeunit.Function(Test.Function(););`

Beside of this repro, sometimes the semicolon is not printed, test it with these two commands:

```
Customer.CheckBlockedCustOnDocs();  // This will add a semicolon
Customer.CreateNewCustomer()        // This will not add a semicolon

```

**Comment by qutreson** [comment]
Hi @bvbeek, autocompletion should add a semi-colon only when the method does not have a return type. Is it the case here for CreateNewCustomer?

**Comment by bvbeek** [comment]
hi @qutreson, thanks for your explanation, this is indeed the same reason for my repro.

You can close this issue 👍
