### ISSUE TITLE
DataItemLink in Query causing a hang

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2921]
VSCode can't handle a project with 3500+ objects.

I can wait until the cows come home... 😄 but no response....

1. Code Analyzer is enabled
2. No Problems...

![image](https://user-images.githubusercontent.com/28626283/42839796-12a2bf94-8a05-11e8-80ee-d1b263d919d1.png)

Unable to create a new object:
![image](https://user-images.githubusercontent.com/28626283/42841161-7db70994-8a09-11e8-807f-795b0e7dc54a.png)

**Comment by dNsl9r** [comment]
I'm not really surprised, why should an extension contain that much objects? 😕 😆

**Comment by bvbeek** [comment]
Hi @thpeder 

I was looking for the reason why this is happening, I couldn't believe that the number of files is the problem.
So I found one reason for so far, (there should be more reasons):
Please try this below:

1. Copy paste it in your solution
2. The compiler should give an error on a := b in the Query object;
3. Enable the code line in the Query object:

`// DataItemLink = Table=Line.Table,"No."=Line."No."; `

4. Restart the VS Code.
5. You will not get any errors.

```
table 50100 Header
{
    fields
    {
        field(1;Table; Integer)
        {
        }
        field(2;"No."; Code[10])
        {
        }
    }
    
    keys
    {
        key(PK; Table,"No.")
        {
            Clustered = true;
        }
    }   
}

table 50101 Line
{
    fields
    {
        field(1;Table; Integer)
        {
        }
        field(2;"No."; Code[10])
        {
        }
        field(3;"Line No."; Integer)
        {
        }
    }
    
    keys
    {
        key(PK; Table,"No.","Line No.")
        {
            Clustered = true;
        }
    }    
}

query 50200 "Query object"
{
    elements
    {
        dataitem(Headers;Header)
        {
            dataitem(Lines;Line)
            {
                // DataItemLink = Table=Line.Table,"No."=Line."No."; 
                column(InvoiceNo;"No.")
                {
                    a := b;
                }
            }
        }
    }
}
```

**Comment by bvbeek** [comment]
Total time to load for 5918 objects on a Azure VM Standard E8s v3 (8 vcpus, 64 GB memory)

**Comment by StanislawStempin** [comment]
@bvbeek - can you look into the AL Language folder in users/.vscode/extensions/microsoft.al and look for EditorServices.log file? See if that perhaps contains some more detailed error message. 

We will use this issue to track the fix for DataItemLink. Could you please log a new issue for the analyzer crashing on your large project?

**Comment by bvbeek** [comment]
@StanislawStempin ok done (Analyzer Crash = #3159)

Did you try this already on your side?

1. Copy paste it in your solution
2. The compiler should give an error on a := b in the Query object;
3. Enable the code line in the Query object:

`// DataItemLink = Table=Line.Table,"No."=Line."No.";`

4. Restart the VS Code.
5. You will not get any errors.

```
table 50100 Header
{
    fields
    {
        field(1;Table; Integer)
        {
        }
        field(2;"No."; Code[10])
        {
        }
    }
    
    keys
    {
        key(PK; Table,"No.")
        {
            Clustered = true;
        }
    }   
}

table 50101 Line
{
    fields
    {
        field(1;Table; Integer)
        {
        }
        field(2;"No."; Code[10])
        {
        }
        field(3;"Line No."; Integer)
        {
        }
    }
    
    keys
    {
        key(PK; Table,"No.","Line No.")
        {
            Clustered = true;
        }
    }    
}

query 50200 "Query object"
{
    elements
    {
        dataitem(Headers;Header)
        {
            dataitem(Lines;Line)
            {
                // DataItemLink = Table=Line.Table,"No."=Line."No."; 
                column(InvoiceNo;"No.")
                {
                    a := b;
                }
            }
        }
    }
}

```

**Comment by AndreyKorepanov** [comment]
@bvbeek It seems it is not reproducible anymore. Could you try it with the build version 2.0.48254+?
