### ISSUE TITLE
"The type or method 'AddAttachment' cannot be used for 'Extension' development" even if it is external

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#2923]
Hi ,

I am trying to use SMTP.Addachment function in AL Extension 2.0 but it is throwing an error : 
	"message": "The type or method 'AddAttachment' cannot be used for 'Extension' development.",

![image](https://user-images.githubusercontent.com/39942971/42859191-1db620cc-8a70-11e8-92ab-e004cad0b254.png)

when i see it in development environment of my sandbox then it is showing this function as external

![image](https://user-images.githubusercontent.com/39942971/42859216-41b4a8c2-8a70-11e8-9db1-83d95b289d66.png)

strange thing is that it only happens when I create a new package using my sandbox but if I copy and paste a package from NAV 2018 and link it with same sandbox then it works.

**Comment by dNsl9r** [comment]
When I'm opening my sandbox C/Side Dev Environment I can see that the function "AddAttachment" is **internal**.

In **NAV 2018** the function was **external**.

When you copy and paste a package from NAV 2018 you are referencing to the wrong symbols, when creating a new package you are using the symbols of the BC sandbox.

Conclusion: Always keep your symbols up2date 😄

**Comment by StanislawStempin** [comment]
The function is Internal on the latest BC builds so you should not use it anymore:)
Whether you see a compiler error or not depends on which exact symbols you have downloaded locally and it looks correct based on your description/screenshots.

**Comment by rishiaurrishabh** [comment]
Thanks @StanislawStempin ....I got a workaround for it so closing the issue.

**Comment by kapoorsidhant** [comment]
Hi,
what was the work around for this ?
