### ISSUE TITLE
Extension completely unusable due to object range

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#2932]
After a little break I've recently picked up work again on a large extension I've been working on for 5 months. First thing I did was update the Business Central sandbox container (image: microsoft/bcsandbox). The container was running on our NAV 2018 dev license. The extension is written in our normal on-prem certified range ("from": 11260662, "to": 11261661). This is allowed as stated here: https://blogs.msdn.microsoft.com/nav/2018/04/05/business-central-object-ranges/

Previously this worked just fine. But after updating my container, I can publish the extension only if I disable the al.enableCodeAnalysis setting. After publishing I can't see a single field on any of my extension's new pages. All pages show up empty, with just the page caption showing. They are also not visible in the search menu.

When I enable al.enableCodeAnalysis again, my whole workspace is marked in red, all showing errors like: `Record '*******' has an ID of [11260662]. It must be between 50000 and 99999.`
This error is also thrown when I publish the extension.

Even though app.json clearly states:
`  "application": "12.0.0.0",
  "idRange": {
    "from": 11260662,
    "to": 11261661
  }`

**Comment by ndpatel0074u** [comment]
Hi @erikrijn ,
It seems that your docker container doesn't have the NAV License which allows you to create new objects on Range `"idRange": { "from": 11260662, "to": 11261661 }`     

Kindly Upload the NAV Developer license file that allows to create objects on range "from": 11260662, "to": 11261661.

Use following powershell cmdlet to upload license file on Docker Container.
`Import-NavContainerLicense -containerName "ContainerName" -LicenseFile "Path of .flf license"`

**Comment by srenders** [comment]
Maybe a stupid question, but did you set the following properties on your pages?
ApplicationArea and UsageCategory

**Comment by ajkauffmann** [comment]
Isn't it a little bit strange that rules in the PerTenantExtensionCop analyzer are not in the AppSourceCop? E.g. PTE0003 Functions must not subscribe to CompanyOpen events. Shouldn't that one also be part of AppSouceCop? (And this is just an example).

**Comment by StanislawStempin** [comment]
@ajkauffmann - yes, we have some consolidation to do regarding the various code cops. Ideally you should only need to enable PTECop, AppSourceCop or CodeCop depending on the development target.

@erikrijn - Regarding the overall issues in this thread, can we consider them solved?

**Comment by erikrijn** [comment]
@StanislawStempin yes the PerTenantExtensionCop was somehow enabled again. I don't think it should be enabled by default anyway, as we're all pushing to create more standard apps instead of customer specific customizations.
