### ISSUE TITLE
[Event Request] OnAfter Event on function IncrAmount in COD80 and COD90

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2933]
In our localization scope we have withholding tax code executed on function IncrAmount in Cod80 and 90.
So we would like to request and event OnAfterIncrAmount in both codeunits 80 and 90.

**Comment by StanislawStempin** [comment]
These are already implemented. Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
