### ISSUE TITLE
Building an extension using the Internal "Table Information" table.

### ISSUE THREAD

**Issue by armela1981** [Microsoft/AL#2937]
This is regarding Virtual table 2000000028.
We were able to create a page for it  using an extension
ON the Json file I set the target to Internal.
I am able to install it using my sandbox environment.
I get an error towards the end of the process, but the extension shows up in my extension list in my sandbox..

 When I install in a production environment, the extension fails and here is the error.

Package validation failed due to the following error(s): error PTE0005: App.json 'target' property must not be set to 'Internal'. - Job Id : 87dc5152-3152-448f-9834-66ca581fd4cc

Any ideas ? It does not like my target property of internal in a production environment.

Any ideas ??

**Comment by qutreson** [comment]
Hi @armela1981, the error you are getting is coming from the [PerTenantAnalyzer](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-codeanalyzer-pertenantextensioncop-rules) which does not allow you to use target internal. The target internal can only be used for on prem. You can read more about the internal target in this issue #1763, in our [docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#appjson-file) and in the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#the-type-or-method-xyz-cannot-be-used-for-extension-development).

**Comment by armela1981** [comment]
Thank you for your reply .
How do I than create my extensions so that I can have access to the internal  Virtual table 2000000028 on a hosted environment ?
I need to create a page from that table to see the tables and number of records stored in those tables ?

**Comment by hemisphera** [comment]
You can not. Instead, use the table `AllObj` and filter on Type = Table, then use a RecordRef to count the records therein.

**Comment by armela1981** [comment]
Thank you for your suggestion.
That worked for my extension.
I am running now into an internal error when publishing the extension.
It says "Internal Error" check your JSON file., however it publishes it because I am able to see the extension in the list of Extensions.
Here is what JSON file looks like.
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://MyBizCentralApp",
            "serverInstance": "NAV",
            "tenant": "",
            "authentication": "UserPassword",
            "startupObjectId": 50098,
            "startupObjectType": "Page",
            "schemaUpdateMode": "Synchronize"
            
        }
    ]
}
I also have set the code so that the new page is available on the search menu but that does not show up.
Ideas or suggestions ?
Here is what the properties look like on the new page

page 50098 "Objects Custom View"
{
    Caption = 'Objects_List';
    Editable = false;
    PageType = List;
    SourceTable = AllObj;
    UsageCategory = Lists;
    ApplicationArea = ALL;
    SourceTableView = SORTING("Object ID")
                      ORDER(Ascending)
                      WHERE("Object Type" = filter(Table));

**Comment by armela1981** [comment]
Quick update on this one.
I packaged my extension and installed it on a live environment just to test it out.
Installed with no issues and I see it on the Extension list.
I can't search for it though on the search toolbox. 
I guess at this point I don't care about the internal error, but want to see why the page is not showing on the search box.

**Comment by JSheeper** [comment]
I had the same issue with my page not showing up when using "AllObjWithCaption" as the source table. 
However, now I'm using the virtual table "Table Metadata" as my source table and that way my page also shows up when searching for it.

**Comment by armela1981** [comment]
That worked great.
Thank you for your response.
I also have another extension that is using tables 50098 and 50099 and page 50096 . The search does not work for that extension.
Any ideas / suggestions ??

Thank you so much.
