### ISSUE TITLE
PAGENO in AL

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2939]
On a report I'm using CurrReport.PAGENO and VSCode warns the following:

`[AL] 'PageNo' is deprecated`

Any idea how it should be done now?

**Comment by srenders** [comment]
CurrReport.PAGENO has been depreciated for years, in RDLC you can't use it anyway. Please use PageNumber and Totalpages in RDLC instead. AL is not aware of any pagenumbers in the layout, imho...
