### ISSUE TITLE
Unable to download extension

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/AL#294]
Using the In-Client Designer.
Clicked Stop Designing, selected Download Code
![image](https://user-images.githubusercontent.com/8598877/27368782-bfc2ad0a-5654-11e7-9903-d6f2fdaf4105.png)

Click Save
![image](https://user-images.githubusercontent.com/8598877/27368845-114ae7be-5655-11e7-94bb-9c96a6435623.png)

Same Error from extensions page.

**Comment by ewaldventer** [comment]
Think I found the reason. The Extension and Publisher Names are automatically populated and uneditable.

Closing and reopening the client, entering design mode - same issue.
Did it a couple of times, changes kept being saved to the same Extension.

Unsure if I did something different, but after closing client and reopened it again, started designing and Stop Designing, fields were editable and could enter publisher name without invalid characters.

**Comment by StanislawStempin** [comment]
Thanks, we are looking into it.

**Comment by waldo1001** [comment]
In my case, the fields are not automatically populated :-/

**Comment by ewaldventer** [comment]
Not sure if it has anything to do with the initialization of the VM / solution? 
Only provisioned it yesterday and had the issue on first attempt.
Nothing since.
