### ISSUE TITLE
Deploy perTenant Extension to Business Central from TFS/VSTS

### ISSUE THREAD

**Issue by jngillard** [Microsoft/AL#2940]
Is there any way to publish per-tenant extensions to business central from TFS/VSTS? I know the process is to publish the extension to the tenant using the extension management page. (which obviously is not using TFS/VSTS)

If not, are there any plans to provide this functionality in the future?

Thanks,

**Comment by henrikwh** [comment]
Hi jngillard,
We're currently working on APIs (web services) that will allow you perform some administrative tasks on tenants. Focus has been on supporting automation of tenant initialization.
Installing per tenants extensions is one of those APIs, besides Creating companies, assigning permission sets and usergroups, uploading and applying rapidstart packages.

Everything, but installing per tenant extensions, is rolling out now. Installing per tenant extensions will come with fall release.

/Henrik
