### ISSUE TITLE
[Question] ModalPageHandler Close Page with OK

### ISSUE THREAD

**Issue by OleTeichmann** [Microsoft/AL#2943]
In a Test Codeunit there is a modal call to a Page. I am handling this Page with a ModalPageHandler. In order to execute the Page Logic I need the Page to be closed with OK. Does anybody know how i do that? There is a function called TestPage.OK(), but I do not know how to use  it.

**Comment by tfenster** [comment]
@OleTeichmann should be TestPage.OK.Invoke()

**Comment by vytjak** [comment]
`TestPage.OK.Invoke()`, I believe. OK is an action _object_ which you need to _invoke_, not a function

**Comment by OleTeichmann** [comment]
@tfenster @vytjak Thanks that works 👍
