### ISSUE TITLE
[PermissionsSet] Can't find RoleID in Business Central

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#2946]
Hi,

I have a problem to find the permissions set I publish in my app:
![image](https://user-images.githubusercontent.com/29598240/42935065-0322fc1a-8b49-11e8-95d2-3d5f79ab6c81.png)
First I had a Permission Set missing problem I solved by creating a permissionset.xml file containing:
![image](https://user-images.githubusercontent.com/29598240/42935143-2c0fb852-8b49-11e8-8567-1ef94d0bb389.png)

Now in the Permissions Sets Page I can't find the permission sets i published with my app.
![image](https://user-images.githubusercontent.com/29598240/42935319-a483be46-8b49-11e8-85b5-07e9df9e9e07.png)

Is VSCode correctly take the xml file to Business Central ? Do I write it correctly ? If I do, how can I find the permission set I transmit to BC ?

I tried this with BC Docker container and in Dynamics365 Sandbox

Thanks !

**Comment by rdebath** [comment]
In the file I generated with the powershell script the `<ObjectType>` (That is `ObjectType` not `ObjetTye`) value is an integer (0=>tabledata, 1=>table, etc) Also Table,Page etc need the execute permission not the others.

**Comment by JulienDecottignies** [comment]
Yes sorry I just found it was not typed correctly. I wrote it again with the permission snipped given by CRS AL Language extension.
Also I didn't put integer for ObjectType (I let TableData) and it worked fine ..!

You can close this issue. Thank you

**Comment by dNsl9r** [comment]
You can close the issue by yourself :-)
