### ISSUE TITLE
Default Publisher - make it a configurable setting

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#295]
Every time a manifest app.json is created you get "Default Publisher" as the publisher name.

Why not making it a configuration option so all your new workspaces would get your own publisher name as configured?

**Comment by esbenk** [comment]
Very good idea.

**Comment by markbrummel** [comment]
How many apps are you going to create? I would guess once in your life for each App on AppSource and Once for each of your customers. Like eventually it will be a few times per year.

**Comment by epernst** [comment]
Or default it to the company name from the license. 
And add that to extensions created via in-page designer.

**Comment by kalberes** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
