### ISSUE TITLE
Environment is broken... probably by the In-client designer

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#296]
Apparently, i'm still able to "break" my environment.  And it's difficult to reproduce .. because once it's broken, I can't get it working again.

It seems that when you play around with the in-client visual designer, that after that, creating any extension with VSCode is not working anymore.  It compiles, it publishes, it even starts - but nothing actually is being changed on the runtime.

even when creating a new table with a new page .. the fields are not shown, like here:
![image](https://user-images.githubusercontent.com/12088142/27384266-96f1e302-568e-11e7-9f5d-8458f2ef443a.png)
it actually has fields in that table/page.

even the card is empty:
![image](https://user-images.githubusercontent.com/12088142/27384290-aa19a460-568e-11e7-9d40-68cc0d048960.png)

why the definition should be correct:
![image](https://user-images.githubusercontent.com/12088142/27384314-bbbdb17a-568e-11e7-84e4-6e9a8de231c1.png)

I noticed the same in the april-release, and there, it happened by playing around with the in-client visual designer.  So I assume it's the same here.. .

**Comment by waldo1001** [comment]
Just tried the same app on another June-update-environment, and there it works:
![image](https://user-images.githubusercontent.com/12088142/27384457-3d65f2e6-568f-11e7-8416-baaa690342ce.png)

**Comment by StanislawStempin** [comment]
If you run into this problem again please try Unpublishing the extension created from the designer using the Extension Management page. 
The designer takes dependency on other extensions to be able to reference fields added through these extensions. This will become smarter over time but for now it block republishing of the dependent extensions until the designer extension is removed.

**Comment by waldo1001** [comment]
well - I did that, both with PowerShell and the extension management page until the situation where I didn't have any extensions installed or published ...

I have fixed my situation by basically restoring the original database.. .  I had copied the db to another one, so I was able to restore it.  

this basically means it's due to "values" in the database, I guess?

This is the script I used:


```
Import-NAVModules

$Backup = Backup-NAVDatabase -ServerInstance Itemclassification_DEV 


$Defaultinstance = get-navserverinstancedetails -ServerInstance NAV

Set-NAVServerInstance -ServerInstance NAV -stop
Set-NAVServerInstance -ServerInstance Navision_main -Stop

Restore-SQLBackupFile `
    -BackupFile $Backup.FullName `
    -DatabaseServer $Defaultinstance.DatabaseServer `
    -DatabaseInstance $Defaultinstance.DatabaseInstance `
    -DatabaseName $Defaultinstance.DatabaseName `
    -TimeOut 0

Set-NAVServerInstance -ServerInstance NAV -Start
Set-NAVServerInstance -ServerInstance Navision_main -Start

Sync-NAVTenant -ServerInstance NAV -Mode Sync -Force
Sync-NAVTenant -ServerInstance Navision_main -Mode Sync -Force

Add-NAVEnvironmentCurrentUser -ServerInstance NAV -PermissionSetId SUPER

Get-NAVServerInstance | ft -AutoSize
```

**Comment by vjekob** [comment]
This absolutely has to do with the in-client designer. Every single time during trainings after I show in-client designer, I am unable to see any page changes made by my other extensions I create afterwards. Today I did a demo of the VS Code and all, and I didn't touch the in-client designer, and it all worked like a charm.

Perhaps the easiest steps to reproduce:
1. Create a new VM
2. Start in-client designer
3. Edit a couple of pages by adding and removing fields in a list page, and then adding, removing and rearranging fields in a card page, and renaming a fasttab.
4. Then when finishing, instead of saving the changes in the database, export changes as a VSCode zip file.
After that, when you create a new extension, it may include a pageextension object, or plain new page objects - these pages will not show anything. If you manage to get them running in the windows client using dynamicsnav:/// protocol access, then you see that they are in the chart design view, without possibility to switch to grid/lines view.

Hope this helps.

**Comment by RobAnderson42** [comment]
Hi Vjekoslav. I was wondering if you had some more specific steps for the repro you've described. I've tried adding/removing/moving fields on both the Customers and Items list pages as well as adding/removing/ moving fields and renaming fast tabs on the Customer and Item card pages and haven't been able to see the issue.

Are there certain pages that you are using, or specific fields that you are adding or moving on those pages when you encounter the issue? Do you have any other extensions installed before you start using the designer? If so, were they installed through VSCode? Is there anything else you can think of that may help me to reproduce the issue?

Thanks!
Rob Anderson

**Comment by waldo1001** [comment]
Thing is, I think it "needs" to crash.  I'm mostly using:
- Item List
- Customer List
- Customer Card
- Item Card
- Role Center
and doing:
- move parts on role center
- move fields
- add fields

Once in a while, it crashes - and I have the feeling that when is has crashed - it has this consequence.

hope that helps
