### ISSUE TITLE
[EventRequest] OnAfterPostGLAndVendor in codeunit 90 - Purch.-Post

### ISSUE THREAD

**Issue by TriangleSPV** [Microsoft/AL#2960]
In Dynamics NAV 2018 Cumulative Update 5 the new event OnAfterPostGLAndCustomer in Sales-Post Codeunit was created (hotfix 264215).

The equivalent event must exist in purchase. The new event OnAfterPostGLAndVendor must be created in Purch.-Post Codeunit.

**Comment by StanislawStempin** [comment]
This event already exist
 
OnAfterPostGLAndVendor(PurchHeader
,GenJnlPostLine,TotalPurchLine,TotalPurchLineLCY,SuppressCommit);

Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
