### ISSUE TITLE
Multiple AL extensions with dependencies break navigation in Web and Windows

### ISSUE THREAD

**Issue by cherabomb** [Microsoft/AL#2961]
Running NAV 2018 CU4 OnPremise (11.0.21441.0), we have established that extensions with interdependencies cause NAV's automatic navigation to stop working. With "automatic navigation" I mean, the NAV search that automatically allows you to find pages provided by the Extension without defining an old-style MenuSuite.

After installing Extension A the menu item "Extension A" reliably appears and the navigation in Web and Windows using the search functions as expected. Then I install Extension B, which depends on Extension A, and at first both appear in the menu and navigation (usually) but often after a few seconds Extension B disappears from the menu and Extension A no longer contains any navigation entries except one. (And why that particular entry is always the one left is a mystery to us. We removed that object but still, when the navigation build crashes, it always leaves a single item from Extension A in the menu/search.) If the bug does not appear, installing a third extension, Extension C, which depends on Extension A, will fairly reliably cause the issue. At the very latest Extension D which depends on Extension B will cause it.

We tried to create a code sample for this but it is a fairly random problem. By restarting the NAV service tier, the problem disappears (often only momentarily). We are able to access the items missing from the menu using Start Object from the search, so they do work.

**Comment by qutreson** [comment]
Hi @cherabomb, this issue has been fixed in the [CU7 of NAV 2018](https://blogs.msdn.microsoft.com/nav/2018/07/09/cumulative-update-07-for-microsoft-dynamics-nav-2018-has-been-released/). You can find the fix reported as 273220 in the [Overview of the CU](https://support.microsoft.com/en-us/help/4341448/cumulative-update-07-for-microsoft-dynamics-nav-2018-build-23019).

**Comment by cherabomb** [comment]
Hi @qutreson, thanks for the tip. We are not running a multitenant installation.
