### ISSUE TITLE
[Migrate nav2018 to Business Central (AL)] Can't use these commnad in the powershell "-ExportToNewSyntax"

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#2962]
I am trygin execute the following command:

`Export-NAVApplicationObject -DatabaseServer "myComputer\NAVDEMO" -DatabaseName "Demo Database NAV (11-0)" -Path "C:\Convert\CAL\CustomObjects.txt" -LogPath "C:\Convert\log.txt" -Force -ExportToNewSyntax`

I execute this command in Windos PowerShell ISE running as administrator but I am receiving the following stack error:

**Spanish**
```
Compare-NAVApplicationObject : No se encuentra ningún parámetro que coincida con el nombre del parámetro 
ExportToNewSyntax.
En línea: 1 Carácter: 165
+ ... tomObjects.txt" -DeltaPath "C:\Convert\CAL\DELTA\" -ExportToNewSyntax
    + CategoryInfo          : InvalidArgument: (:) [Compare-NAVApplicationObject], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Dynamics.Nav.Model.Tools.Cmdlets.CompareNavApplicatio 
   nObject
```

**English**
```
Compare-NAVApplicationObject: No parameter matching the name of the parameter is found
ExportToNewSyntax.
Online: 1 Character: 165
+ ... tomObjects.txt "-DeltaPath" C: \ Convert \ CAL \ DELTA \ "-ExportToNewSyntax
    + CategoryInfo: InvalidArgument: (:) [Compare-NAVApplicationObject], ParameterBindingException
    + FullyQualifiedErrorId: NamedParameterNotFound, Microsoft.Dynamics.Nav.Model.Tools.Cmdlets.CompareNavApplicatio
   nObject
```

With this commnad I am trying to convert Dynamics Nav 2018 code to Business Central AL code.

**Comment by bvbeek** [comment]
The error goes about **Compare-NAVApplicationObject** and not about **Export-NAVApplicationObject**, or I am wrong?

**Comment by sssolammm** [comment]
Yes you are right the come from Compare-NAVApplicationObject but It only crash when I add the flag -ExportToNewSyntax I would like to use it to avoid future error in the migration.

**Comment by Kowa63** [comment]
Compare-NAVApplicationObject is only for normal C/AL objects, not the intermediate code intended solely for the txt2AL conversion tool which is generated when -ExportToNewSyntax is used. The newer versions of txt2AL can process DELTA files.

To convert C/AL to AL, It is much easier to use the cmdlet Convert-ModifiedObjectsToAl or Convert-Txt2AL provided by the navcontainerhelper module. 
https://github.com/Microsoft/navcontainerhelper/tree/master/ObjectHandling

Before these cmdlets came along, I wrote two conversion scripts which do the trick as well, but nowadays I only need these if docker is not used. 
http://www.msdynamics.de/viewtopic.php?f=17&t=34503
http://www.msdynamics.de/viewtopic.php?f=17&t=34521

**Comment by sssolammm** [comment]
@Kowa63 thanks for your answer. Finally I found my error, I solved downloading last cu from nav2018 and it has the flag -ExportToNewSyntax
