### ISSUE TITLE
Editable does not return the correct value when doing tests with a TestPage.

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#2968]
Docker Version: 12.1.22475.22720 (ES)
AL Extension: 0.16.19969

We have created a test that checks that, depending on the value of a field (Status), some other fields are editable, or not, on a page. When we run the page on the web client, everything works perfectly.

When we run the test, though, the Editable property of the field (in the TestPage) is not updated, though, so we cannot run any tests that check that everything is working ok.

Let's say we have a "Category" table with three fields (Code, Description & Status):

```
table 50100 "Category"
{
    Caption = 'Category';

    fields
    {
        field(1; Code; Code[20])
        {
            Caption = 'Code';
        }
        field(2; Description; Text[50])
        {
            Caption = 'Description';
        }
        field(3; Status; Option)
        {
            Caption = 'Status';
            Editable = false;
            OptionCaption = 'Open,Closed';
            OptionMembers = Open,Closed;
        }
    }

    keys
    {
        key(PK; Code)
        {
            Clustered = true;
        }
    }
}
```

And a page that shows records from this table, with two actions: Close & Reopen.

```
page 50100 "Category Card"
{
    Caption = 'Category Card';
    PageType = Card;
    SourceTable = Category;

    layout
    {
        area(content)
        {
            Group(General)
            {
                Editable = IsEditable;
                field("Code"; Code)
                {
                    ApplicationArea = All;
                }
                field("Description"; Description)
                {
                    ApplicationArea = All;
                }
                field("Status"; Status)
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    actions
    {
        area(processing)
        {
            action(CloseCategory)
            {
                ApplicationArea = All;
                Caption = 'Close Category';
                Enabled = IsEditable;
                Image = Close;

                trigger OnAction()
                begin
                    Rec.Status := Rec.Status::Closed;
                    Rec.Modify();
                    CheckEditable();
                end;
            }
            action(ReopenCategory)
            {
                ApplicationArea = All;
                Caption = 'Reopen Category';
                Enabled = not IsEditable;
                Image = ReOpen;

                trigger OnAction()
                begin
                    Rec.Status := Rec.Status::Open;
                    Rec.Modify();
                    CheckEditable();
                end;
            }
        }
    }

    var
        IsEditable: Boolean;

    trigger OnNewRecord(BelowxRec: Boolean)
    begin
        IsEditable := true;
    end;

    trigger OnAfterGetRecord()
    begin
        CheckEditable();
    end;

    local procedure CheckEditable()
    begin
        if Status = Status::Open then
            IsEditable := true
        else
            IsEditable := false;
        CurrPage.Update(false);
    end;
}
```

Whenever one of the two actions is executed, the value of "Status" is modified, the global variable "IsEditable" is updated, and the "Update" method of the page is run, so that the UI is updated. 

Up to here, everything works as expected.  

We have also created a Test Extension, with a codeunit that includes this Test procedure: 

```
    [Test]
    procedure CloseCategory()
    var
        CategoryCode: Code[20];
        CategoryCardTestPage: TestPage "Category Card";
        Category: Record Category;
        Assert: Codeunit Assert;
        IsEditable: Boolean;
    begin
        // [Scenario] The user closes a category.

        // [Given] There is an open Category.
        CategoryCode := CreateCategory();

        // [When] The "Close Category" action is selected.
        Category.Get(CategoryCode);
        CategoryCardTestPage.OpenView();
        CategoryCardTestPage.GoToRecord(Category);

       // Editable() RETURNS FALSE EVEN THOUGH THE FIELD IS EDITABLE
        Assert.IsTrue(CategoryCardTestPage.Code.Editable(),'An Open category must be editable.');
        CategoryCardTestPage.CloseCategory.Invoke();

        // [Then] The fields in the Category Card page are not editable.
        Assert.IsFalse(CategoryCardTestPage.Code.Editable(),'The category must not be editable once closed.');
    end;
```

When we get to the first Asset, our code fails, because Editable() returns false (it also returns false after the CloseCategory action is invoked).

If we check whether the CloseCategory action is enabled, though (it depends on the same global variable), it works correctly, and it is updated after the CloseCategory action is invoked.

**Comment by AndreyKorepanov** [comment]
@salgiza 
Test Field's Editable() returns the value indicating if the current field is currently in editing state. That is it returns True if and only if the field is editable and is editing, and False otherwise. Please, use Test page OpenEdit() method to open page in editing mode, like in the code bellow. It should help to fix your code:
Category.Get(CategoryCode);
CategoryCardTestPage.OpenEdit(); // OpenEdit opens page in editing mode
CategoryCardTestPage.GoToRecord(Category);

CategoryCardTestPage.ReopenCategory.Invoke();
IsEditable := CategoryCardTestPage.Code.Editable(); // it is True as the page is in the editing mode
Assert.IsTrue(IsEditable, 'An Open category must be editable.');

CategoryCardTestPage.CloseCategory.Invoke();
IsEditable := CategoryCardTestPage.Code.Editable();
Assert.IsFalse(IsEditable, 'The category must not be editable once closed.');

**Comment by salgiza** [comment]
@AndreyKorepanov Thanks a lot, we have just updated our test code, and it works perfectly using OpenEdit 

(Arg! It is so obvious once you know the answer :man_facepalming:)
