### ISSUE TITLE
Event-request - OnBeforeRunReport in CU 449 Job Queue Start Codeunit

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#2969]
We're scheduling lots of processes via the job queue using codeunits. However, transferring parameters using the job queue parameters is quit 'technical' and error-prone. I'm in favor of moving our code towards 'processing only' reports, allowing us to use the 'report request page' action to add filters (instead of the job queue parameters). Downside is that the report inbox is flood with entries that are of no interest to us. We'd like to be able to prevent report inbox records from being inserted.

Either privide a solution to overrule following code ...

```
CASE JobQueueEntry."Report Output Type" OF
  JobQueueEntry."Report Output Type"::"None (Processing only)":
    BEGIN
      JobQueueEntry."Notify On Success" := TRUE;
      JobQueueEntry.MODIFY;
    END;
  JobQueueEntry."Report Output Type"::Print:
    ;
  ELSE BEGIN
    ReportInbox."Created Date-Time" := ROUNDDATETIME(CURRENTDATETIME,60000);
    ReportInbox.INSERT(TRUE);
  END;
END;
```

... either provide a **OnBeforeRunReport** integration event using the handled pattern.

**Comment by AlexanderYakunin** [comment]
Please specify how you would like to use event to solve this issue?
