### ISSUE TITLE
'table field option' does not contain a definition for 'optionstring value' after June update

### ISSUE THREAD

**Issue by MrDavid5465** [Microsoft/AL#297]
An error that I am experiencing after installing the June update is that anywhere I try to reference or check to see what a record's value from a field of the option datatype is and compare it to the available optionstring values, I get an error saying that the optionstring does not contain a definition for the given value. This appears to be affecting only default fields in the default tables.

for example: Sales Line is table 37. As you can see in the third image though, I am having this issues with more than just that one table.

![capture1](https://user-images.githubusercontent.com/29601581/27384614-86a460dc-565d-11e7-8692-ab0bfd673874.PNG)
![capture2](https://user-images.githubusercontent.com/29601581/27384597-7309d0f2-565d-11e7-8869-7aa68382a000.PNG)
![capture3](https://user-images.githubusercontent.com/29601581/27384705-dfb3ba42-565d-11e7-91fb-9e957f2b112f.PNG)

**Comment by StanislawStempin** [comment]
Can you provide a stand alone code that reproduces the issue? For example the following code works correctly:
```
procedure Test();
    var
      SalesLine : record "Sales Line";
    begin
      SalesLine.Validate(Type, SalesLine.Type::Item);
    end;
```
Also, to confirm that these are not caused by the incremental compiler getting out of sync, could you please build with Ctrl+Shift+B and see if you're getting the same errors?

**Comment by MrDavid5465** [comment]
I made a new project and it works. The difference was the navx files were out of date in my project.
