### ISSUE TITLE
One line excuse for CodeCop et. al.

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#2970]
Many tools like CodeCop have the ability to turn off one or more messages for the next statement. Please add this.
If the next statement is a multiple (begin, repeat etc) the change applies to the entire statement.
After the statement the analyser returns to the old settings.

This is because the rules are often a matter of opinion and are trying to "legislate" good/common sense. Of course, fixed inflexible rules tend to give rise to unintended consequences.

A trivial example, the expressions below are rather complex. The `AA0001` rule tries to make expressions look more tidy and for normal NAV expressions that is good. But for the below it might be clearer to use a different rule using the spacing to highlight the expression evaluation order instead.
 
``` pascal
  Str := UPPERCASE(SHA1(RecStr));
  //$codeAnalyzers: Disable AA0001
  for I := 1 to STRLEN(Str) do Str[I] := Str[I] - 7*(Str[I] div 64);
  //$codeAnalyzers: Disable AA0001
  for I := 1 to STRLEN(Str) / 2 do Hash[I] := 10240 + (Str[I*2-1]-48)*16 + (Str[I*2+0]-48);
```

**Comment by StanislawStempin** [comment]
Thank you for the suggestion. We will consider it for the long term backlog.

**Comment by EmilDamsbo** [comment]
Closing this as we implemented `#pragma warning disable/restore` some time back: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma

**Comment by rdebath** [comment]
Technically you haven't implemented this, you have implemented the old "dumb and lazy" variant.
As is said in the third line this is supposed to turn back on automatically for the blocks after the flagged one.

But I wouldn't expect Microsoft to fix something they deem "Meh, good enough".
