### ISSUE TITLE
EventRequest]Codeunit 5055 CustVendBank-Update

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#2972]
Within this codeunit event publishers were added in the functions:
- UpdateCustomer (OnAfterUpdateCustomer)
- UpdateVendor (OnAfterUpdateVendor)

Based on the location where this publisher is located (just before the modify) I would expect this publisher would have been named: OnBeforeUpdateCustomer/Vendor

Besides the naming I would like to have an additional publisher in function: UpdateBankAccount just before the modify with following name: OnBeforeUpdateBankAccount

Signature: OnBeforeUpdateVendor(VAR BankAccount : Record 270;Contact : Record 5050);

**Comment by AlexanderYakunin** [comment]
Please check if you are looking into latest code base, these eventa already exists

**Comment by RonKoppelaar** [comment]
Validated in build 13.0.23620 but I don't see the requested event.

**Comment by AlexanderYakunin** [comment]
Here is what we have, same for Vendor and BankAccount:

[External] UpdateCustomer(VAR Cont : Record Contact;VAR ContBusRel : Record "Contact Business Relation")
WITH Cust DO BEGIN
  GET(ContBusRel."No.");
  NoSeries := "No. Series";
  VATRegNo := "VAT Registration No.";
  TRANSFERFIELDS(Cont);
  "No." := ContBusRel."No.";
  "No. Series" := NoSeries;
  **OnAfterUpdateCustomer(Cust,Cont);**
  MODIFY;
  IF ("VAT Registration No." <> '') AND ("VAT Registration No." <> VATRegNo) THEN
    VATRegistrationLogMgt.LogCustomer(Cust);
END;

**Comment by RonKoppelaar** [comment]
Two publishers are there:
LOCAL [IntegrationEvent] OnAfterUpdateCustomer(VAR Customer : Record Customer;Contact : Record Contact)
LOCAL [IntegrationEvent] OnAfterUpdateVendor(VAR Vendor : Record Vendor;Contact : Record Contact)

I'm requesting a third one in function: UpdateBankAccount:

    [External]
    PROCEDURE UpdateBankAccount@3(VAR Cont@1000 : Record 5050;VAR ContBusRel@1001 : Record 5054);
    BEGIN
      WITH BankAcc DO BEGIN
        GET(ContBusRel."No.");
        NoSeries := "No. Series";
        OurContactCode := "Our Contact Code";
        VALIDATE("Currency Code",Cont."Currency Code");
        TRANSFERFIELDS(Cont);
        "No." := ContBusRel."No.";
        "No. Series" := NoSeries;
        "Our Contact Code" := OurContactCode;
**==> Requested EventPublisher**
        MODIFY;
      END;
    END;

**Comment by RonKoppelaar** [comment]
Found in build: 13.0.23896.0-nl
