### ISSUE TITLE
Function SaveFile on Document Service codeunit (9510) change sign request

### ISSUE THREAD

**Issue by Enomis82** [Microsoft/AL#2974]
Hi, 
we would like to have a new parameter inside this function to specify what is the subfolder where file has to be saved.
That can be used for example to save invoice and delivery note in different paths.

Thanks in advance for your collaboration

**Comment by AndreiIvanescu** [comment]
This would be very helpful, any chance to have an update on this request?

**Comment by StanislawStempin** [comment]
The SaveFile function is Internal which means you cannot use it in the online version of Business Central.
For On-Premise usage you are free to modify the function as you need.
