### ISSUE TITLE
OnAfterGetCurrRecord Production BOM List

### ISSUE THREAD

**Issue by deano808** [Microsoft/AL#2975]
I have a page extension that extends Production BOM List.

I'm trying to control the Enabled property of an Action in my extension based on the record selected.
I've created a trigger OnAfterGetCurrRecord that contains the call to my code.
The page extension events triggers run only when I first open the page.
Selecting different records in the list doesn't call the expected trigger.

If i modify the standard object and add code to the OnAfterGetCurrRecord and OnAfterGetRecord trigger, the trigger in the page extension is called.

**Comment by StanislawStempin** [comment]
Could you please provide sample AL code that illustrates the problem?

**Comment by StanislawStempin** [comment]
I cannot reproduce your issue using the following sample code:
```
pageextension 50100 BomExtension extends "Production BOM List"
{
    trigger OnAfterGetCurrRecord()
    begin
        Message('trigger');
    end;
}
```

**Comment by StanislawStempin** [comment]
Closing due to the fact that we couldn't reproduce the issue and for lack of additional input.
