### ISSUE TITLE
Create package and manifest with PowerShell

### ISSUE THREAD

**Issue by marcelvos1** [Microsoft/AL#2976]
It will be nice if there is a way to create a package and manifest file with powershell. We need this to automate some steps in our branch strategy.

Case:
Our developers added changes only in feature branches. The next step is merge this changes in de developer branch. In this branch (and the other branches: release and master) we will create packages and manifest files automaticly. 

The New-NAVAppPackage is only for extension v1.0. Please change this for v2.0
Thanks

**Comment by dNsl9r** [comment]
The good @tfenster wrote in his blog about automated builds here: https://www.axians-infoma.com/navblog/dynamics-365-bc-extension-build-in-tfs-vsts-using-containers/

Maybe this will help you

**Comment by StanislawStempin** [comment]
We do indeed want to introduce CLI support for AL Language but can't promise any timeframe at this point.

**Comment by marcelvos1** [comment]
Thanks. This is very helpfull.
