### ISSUE TITLE
Migrate code C/AL to AL

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#2978]
I dont know how I can convert this line into AL code

`Window.INPUT(2,faplicac);`

My AL Extension Version it's 0.16 and the error that I receive it's;

`'Dialog' does not contain a definition for 'INPUT'`

How do you resolve this error?

**Comment by srenders** [comment]
Since there's no INPUT dialog in BC you will need to do something else. For example, create a mini page with a textbox and use that instead.

**Comment by sssolammm** [comment]
Thanks @srenders I will check it

**Comment by dNsl9r** [comment]
No, the popup will appear when you click the action **ClickMe** on the **Customer List**

**Comment by sssolammm** [comment]
I dont know why I am not finding the modal, I click in costumer list but nothing appear, I try to click multiple actions in the menu but theres nothing called ClickMe and I trying to click in the first section called "General" but theres no way. Can you give me another tip? 

Thanks,

**Comment by srenders** [comment]
When you deploy the extension, to your server (change the launch.json) then in the customer list you should see the action ClickMe:
![clickme](https://user-images.githubusercontent.com/17511254/43126730-d0d7a632-8f2d-11e8-808a-feee5943b96d.jpg)

**Comment by srenders** [comment]
Maybe? To be sure, you can try to add the action somewhere else on that page or on another page?

**Comment by StanislawStempin** [comment]
We haven't seen any problem with actions not showing up. Can you make sure that the extension got successfully deployed to your server? The action might be somewhere else on the ES version of the product or it might have been moved by a profile.
As @srenders suggested, please try adding the action somewhere else on that page.

**Comment by sssolammm** [comment]
Thanks for your time @StanislawStempin  and @srenders I solve the problem
