### ISSUE TITLE
[EventRequest]Codeunit 5602 FA Get G/L Account No.

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#2979]
We have some customized code in Procedure "GetAccNo" to retrieve to GLAccNo. For this we would like an event publisher just before the Exit.

```
....
           "FA Posting Type"::"Custom 2":
              GLAccNo := FAPostingGr.GetCustom2BalAccountOnDisposal;
          END;
      END;
==> New Event publisher
      EXIT(GLAccNo);
    END;
```

Signature: OnAfterGetAccNo(FALedgEntry : Record 5601; VAR GLAccNo : Code[20])

**Comment by StanislawStempin** [comment]
The event already exists. Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
