### ISSUE TITLE
txt2al: Converting Table.Flow Fields does not work

### ISSUE THREAD

**Issue by AxelLeder** [Microsoft/AL#298]
The code of Flow Fields does not work correctly.
- the Calc Formular itself is not build correct

Example
[TAB5370415.TXT](https://github.com/Microsoft/AL/files/1091746/TAB5370415.TXT)
[Table 5370415 - dynamo Report List [AL]..txt](https://github.com/Microsoft/AL/files/1091748/Table.5370415.-.dynamo.Report.List.AL.txt)

**Comment by esbenk** [comment]
The problem seems to be that "Object Type" and "Object ID" should be quoted. The order of properties shouldn't matter.

Did you exports the objects from C/SIDE using Command=ExportToNewSyntax? See documentation [here](https://msdn.microsoft.com/en-us/dynamics-nav/newdev-txt2al-tool)

**Comment by AxelLeder** [comment]
Hi Espben,

you’re right, I’m so sorry.
I used the wrong folder (with the normal object export).

Again, sorry.
Axel

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Esben Nyhuus Kristoffersen<mailto:notifications@github.com>
Gesendet: Mittwoch, 21. Juni 2017 16:45
An: Microsoft/AL<mailto:AL@noreply.github.com>
Cc: AxelLeder<mailto:axel.leder@live.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Microsoft/AL] txt2al: Converting Table.Flow Fields does not work (#298)


The problem seems to be that "Object Type" and "Object ID" should be quoted. The order of properties shouldn't matter.

Did you exports the objects from C/SIDE using Command=ExportToNewSyntax? See documentation here<https://msdn.microsoft.com/en-us/dynamics-nav/newdev-txt2al-tool>

**Comment by esbenk** [comment]
No problem.
