### ISSUE TITLE
New-NAVServerPermission does not recognize Extension tables

### ISSUE THREAD

**Issue by cherabomb** [Microsoft/AL#2984]
_Running NAV 2018 CU4 OnPremise (11.0.21441.0)_

I need to define permission sets for my AL extension and Permissions.xml is a very tedious way of doing it. I wanted to automate it with Powershell but the command New-NAVServerPermission cannot see my extension objects, erroring out with the message:

"New-NAVServerPermission : Im Filter wurde Folgendes nicht gefunden: AllObj.
Filter: Object Type: Table, Object ID: 50000" which in English means "The following was not found in the Filter: AllObj."

I guess I must resort to Rapidstart packages if I don't want to use Permissions.xml?

**Comment by rishiaurrishabh** [comment]
I think they Microsoft already have that in plan, with the June developer preview, you can also generate the permission set file with VS Code or export them directly from the client. See https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/ for more info (scroll down to Permission Set Creation).

**Comment by StanislawStempin** [comment]
That's correct. June preview update contains an improved way of generating permission sets as linked above. We do not plan more improvements for NAV 2018.

**Comment by cherabomb** [comment]
Thank you for your helpful replies.
