### ISSUE TITLE
Option to disable browser when debugging.

### ISSUE THREAD

**Issue by graknol** [Microsoft/AL#2986]
Hi, I usually develop using the RTC client, since it's faster. But, each time i publish the extension from VS Code by hitting F5 (or ctrl+F5) the browser always opens. Like I get it if you're developing for BC365, but we are still primarily targeting NAV2018 while future proofing for BC365.

So, could we please have a launch option like: "openInBrowser": true|false

Thank you.

**Comment by ChrisBlankDe** [comment]
Maybe you can use "CRS AL Language Extension".
This will add a new Command: "CRS: Run Object (Windows Client)"
![image](https://user-images.githubusercontent.com/18051656/43084697-7b364632-8e99-11e8-82f7-fd42f4267806.png)
You can find more Infos about this Extension in the blog of @waldo1001  http://www.waldo.be/2018/04/18/crs-al-language-extension/

**Comment by graknol** [comment]
@ChrisBlankDe Thank you for sharing this extension, yes it allows me to run an object that I specify, but it doesn't support building/publishing the extension without opening the browser 😢

**Comment by StanislawStempin** [comment]
We received this request from multiple sources and it is something we would like to implement in the near future.

**Comment by BartPermentier** [comment]
Just blank the Web Client Base URL in your Navision Service (Under Client Services) and publish using F6; that's what I'm doing :)

PS: You might want to rebind F7 since that button pulls the code from your Navision. I did it the first time I accidentally pressed it and lost a lot of code.

**Comment by graknol** [comment]
Awesome, it works thank you!

But does F7 overwrite your AL files too??

Den tir. 24. jul. 2018, 16:55 skrev Bart Permentier <
notifications@github.com>:

**Comment by BartPermentier** [comment]
F7 Overwrites your AL files with the version deployed on the server so you should rebind that function to Shift-F7 or something :)

**Comment by graknol** [comment]
Oh, thank you, lifesaver :-)

Den tir. 24. jul. 2018, 18:14 skrev Bart Permentier <
notifications@github.com>:

**Comment by StanislawStempin** [comment]
This has been implemented in the latest insider images and in the upcoming November preview release.

![image](https://user-images.githubusercontent.com/23653165/47999340-9f15f280-e102-11e8-99cd-20abd34440ae.png)
