### ISSUE TITLE
[Question] File management - About compressed files

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#2988]
Hi,

I want to create a text file in which I put some datas in order to send it into an external API. This API wants the file to be compressed in tar.gz format. 
Is there ways (or a way..!) to create a file, and compress it by only using AL or do I have to learn and do it with Azure Functions ? 
I think for the 'compress part' I'll do have to use Azure Functions (but I still ask) but it could be interesting to create the file with AL, and juste send them as parameters for the Azure Function wich will just compress these given parameters.

Thanks for your advices ! :)

**Comment by grobyns** [comment]
Hi,

As you can't use files in BC you'll need to be able to compress a stream. We do have some compression support in BC but i do not know if it is the format you need. You can have a look in Codeunit 706. 

If this doesn't work you but there's a standard .net library you can use then you can submit a wrapper for the .net here: https://github.com/microsoft/cal-open-library . We will review your submission and if it follows the rules and the functions are safe then we'll add it in a next version of BC.

If all this fails then maybe Azure Functions is the way to go. 

br/Gert

**Comment by JulienDecottignies** [comment]
Hi,

Thanks for your answer. 
I do have to give a tar.gz file in my post request in order to get the expected result. As I have to work with file, I think the "better way" (the only I see right now) is to build it with an azure function. I keep in my existence of CodeUnit 706, it will may be helpful in the future.

I took a look at cal-open-library, how can I find a functionality I want in the repo ? I see a lot of objects but I can't find any short description of what they do. 
Last question: I see a lot of dotnet types, so if I take an object from the repo, I'll have to import in the CSide environment. But here I want to work only with extensions. So for now, is it a project to translate safely dotnet functionality in order to make them available for BC in the future ?

**Comment by grobyns** [comment]
Hi,

the cal open a library is where you can contribute wrappers to business central. There's no catalog of which ones are available already but they are all in the 3xxx range of codeunits. 
If you can't find what you need, you can submit a new wrapper. When you do, we will review the code and if all is ok, we will include it in a future update of BC for you to use.
For development purposes you can import the wrapper into your database and code against it. For use in production systems you need to wait until we ship a version with the codeunit.

br/Gert

**Comment by JulienDecottignies** [comment]
Hi,

Ok thank you for these informations, I keep them in mind :)
