### ISSUE TITLE
[Function Expose] CalcCell function on Codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#2990]
On our localization scope we need to use the function CalcCell on a report. So I would like to request for the function CalcCell to be set as external.

**Comment by thpeder** [comment]
Hi @martinhocosta88,
It will be part of the next major release.
You can read about the release schedule: [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
