### ISSUE TITLE
In Client Designer: Only able to add one extension ...

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#300]
... while it asumes I can do more... .

Repro:
In Inclient designer, add "No. 2" to the list.
Stop designing
name it "ItemList" with publisher "waldo"
Start the inclient designer again on the customer list
add a field (search name)
stop designing
name it "customerlist" with publisther "waldo"

Open the "Extension Management" and try to find the "customerlist" extension... .  Looks like all additinal changes are saved to the first extension.

**Comment by waldo1001** [comment]
when I do that for the third time, and try to save the extension, i see that:
- the filename is the one that I give in my third "extension"
- the name in the app.json is the one that I gave originally.

so I guess it's "by design", only some work left in the client itself..

**Comment by StanislawStempin** [comment]
This is already fixed in the July Update.
