### ISSUE TITLE
Integer DataItem with Number field in conditional check or setrange in report  

### ISSUE THREAD

**Issue by bhavank-g** [Microsoft/AL#3000]
Report having Integer Data Item with Number field in conditional check or setrange could not generate Success package on VS Code and gives error.

- AL Extension Version: 0.16.19969

- Server Version: 2018 CU7

```
report 50102 IntegerTest
{
    dataset
    {
        dataitem(ItemLedgEntry; "Item Ledger Entry")
        {
            trigger OnAfterGetRecord();
            begin
                If "Invoiced Quantity" > 0 then begin
                        TempItemLedgEntry.INIT;
                        TempItemLedgEntry.TRANSFERFIELDS(ItemLedgEntry);
                        TempItemLedgEntry.INSERT;
                        CurrReport.SKIP;
                end;
            end;
        }
        dataitem(LastDataItem; Integer)
        {
            trigger OnPreDataItem();
            begin
                If TempItemLedgEntry.Count = 0 then
                    SETRANGE(Number,1,1)
                else
                    SETRANGE(Number,1,TempItemLedgEntry.Count);
            end;

            trigger OnAfterGetRecord();
            begin
                If Number >= 1 then
                    Message('Invoice Quantity- %1',TempItemLedgEntry."Invoiced Quantity");
            end;
        }
        
    }
    
    requestpage
    {
        layout
        {
        }
    
        actions
        {     
        }
    }
    
    var
    TempItemLedgEntry  : Record "Item Ledger Entry" temporary;
}
```

**Comment by MikeGlue** [comment]
try changing dataitem(LastDataItem; Integer) to dataitem(LastDataItem; "Integer")

**Comment by bhavank-g** [comment]
Hi Mike, I tried that but no luck!!

**Comment by StanislawStempin** [comment]
I cannot reproduce the problem. The code compiles successfully on the latest build.

Note:  For Nav2108 you should be using AL Language that comes on the DVD. (Version 0.12.XXX)

**Comment by bhavank-g** [comment]
Hi Stanislaw,

We tried to compile with NAV2018 AL language version comes with DVD but  have same issue. Please find attached screenshot for error.

![image](https://user-images.githubusercontent.com/41594314/43127398-4afe8270-8f27-11e8-942f-a199ec2111ba.png)

**Comment by bhavank-g** [comment]
Hi Stanislaw,

I tried disable previous AL language on VS Code and installed from 2018 CU7 DVD which compiled solution successfully

Thanks for help
