### ISSUE TITLE
[Event Request] Codeunit 23, 213, 1013, 5633, 5653 - UpdateAnalysisView

### ISSUE THREAD

**Issue by smartinckl** [Microsoft/AL#3008]
We have own Analysis Views which have to be updates after item item Journal Posting.
Therefore an Event is missing after "UpdateItemAnalysisView" and before COMMIT like "GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);" of codeunit 13

--- procedure Code of codeunit 23 ---
  Window.CLOSE;
  IF NOT SuppressCommit THEN
    COMMIT;
  CLEAR(ItemJnlCheckLine);
  CLEAR(ItemJnlPostLine);
  CLEAR(WhseJnlPostLine);
  CLEAR(InvtAdjmt)
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
UpdateItemAnalysisView.UpdateAll(0,TRUE);
**-->Missing Event**
IF NOT SuppressCommit THEN
  COMMIT;

--- procedure Code of codeunit 213 ---
  COMMIT;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
**-->Missing Event**
COMMIT;

--- procedure Code of codeunit 1013 ---
  UpdateAndDeleteLines;

  COMMIT;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
UpdateItemAnalysisView.UpdateAll(0,TRUE);
**-->Missing Event**
COMMIT;

--- procedure Code of codeunit 5633
  CLEAR(FAJnlCheckLine);
  CLEAR(FAJnlPostLine);
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
**-->Missing Event**
COMMIT;

--- procedure Code of codeunit 5653 ---
  COMMIT;
  CLEAR(InsuranceJnlCheckLine);
  CLEAR(InsuranceJnlPostLine);
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
**-->Missing Event**
COMMIT;

--- procedure Code of codeunit 13 ---
  IF NOT SuppressCommit THEN
    COMMIT;
  CLEAR(GenJnlCheckLine);
  CLEAR(GenJnlPostLine);
  CLEARMARKS;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);
IF NOT SuppressCommit THEN
  COMMIT;

IF SkippedLine AND GUIALLOWED THEN
  MESSAGE(SkippedLineMsg);

**Comment by AlexanderYakunin** [comment]
Can you please be more specific, reference to COD13 does not answer which events you need in pother places and for what purpose? Please provide event definition with parameters and properties and where it should be called for each case.

**Comment by smartinckl** [comment]
Here is the Code of codeunit 13 where the Event GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID) is called.

-- procedure Code of codeunit 13 ---
IF NOT SuppressCommit THEN
COMMIT;
CLEAR(GenJnlCheckLine);
CLEAR(GenJnlPostLine);
CLEARMARKS;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
**GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);**
IF NOT SuppressCommit THEN
COMMIT;
IF SkippedLine AND GUIALLOWED THEN
MESSAGE(SkippedLineMsg);

As you can see in the othe codeunits mentioned (see <Missing Event>), there is a equal event call missing. Mybe it should be implemented in the same way with the same paramters than GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID) or as and event call like
**OnAfterUpdateAnalysisView(..JnlPostine,..Reg)**

**Comment by smartinckl** [comment]
Please, reopen it.

**Comment by smartinckl** [comment]
Reopen it.

**Comment by smartinckl** [comment]
Any Proggress?

**Comment by smartinckl** [comment]
@AlexanderYakunin Can you start with the last comment and the bold spots? It's hard for me to pledge the exact structure of the event. I mean, they should all be the same, but the code in the posts isn't always the same. So I just marked the code places where I missed the event.

**Comment by AlexanderYakunin** [comment]
Let's take COD80 as example. We already have event OnAfterPostSalesDoc in the end. Here you have Rec (=Sales Header) and GenJnlPostLine. And also posted document numbers. Why do you need specific event after UpdateAnalysisView then, can you use this event for your purpose?

**Comment by smartinckl** [comment]
In that issue noCOD80 is mentioned.
But in base Code function UpdateAnalysisView is only called IF NOT (InvtPickPutaway OR SuppressCommit) 


And Event OnAfterPostSalesDoc will be called every time. That's the reaseon for a new Event for COD80.

**Comment by AlexanderYakunin** [comment]
Sorry, I don't understand how you are going to use GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);? Can you please explain your scenario and provide exact code sample for implementation of new event in COD23, for example?

**Comment by AlexanderYakunin** [comment]
Let me add that we have new event OnAfterUpdateAll(Which,DirectlyFromPosting) in UpdateAnalysisView.UpdateAll, so you can use it for any update across application,

**Comment by smartinckl** [comment]
Will this new event come with the next CU1 for BC on Prem?

**Comment by AlexanderYakunin** [comment]
It will come in next minor update, but next OnPrem release will be in 6 months

**Comment by smartinckl** [comment]
Won’t we get cumualtive updates every month than for NAV 2018?

Von: Alexander Yakunin <notifications@github.com>
Gesendet: Dienstag, 16. Oktober 2018 14:15
An: Microsoft/AL <AL@noreply.github.com>
Cc: Stefan Martin <s.martin@ckl-kore.de>; State change <state_change@noreply.github.com>
Betreff: Re: [Microsoft/AL] [Event Request] Codeunit 23, 213, 1013, 5633, 5653 - UpdateAnalysisView (#3008)


It will come in next minor update, but next OnPrem release will be in 6 months

**Comment by AlexanderYakunin** [comment]
You will get monthly updates for earlier supported versions including NAV 2018 as before, although please do not expect new events to be implemented for NAV 2018. We implement event requests into latest branch only, so monthly updates for D365 BC will contain all events. And will be available via cloud only. Next OnPrem release is scheduled for Spring 2019.

**Comment by StanislawStempin** [comment]
For more details see: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

**Comment by AlexanderYakunin** [comment]
I'm going to close this request, please let me know if you still need it after implementation of events in UpdateAnalysisView.UpdateAll.
