### ISSUE TITLE
[Event Request] codeunit 80 and codeunit 90 - UpdateAnalysisView

### ISSUE THREAD

**Issue by smartinckl** [Microsoft/AL#3009]
We have own Analysis Views which have to be updates after item item Journal Posting.
Therefore an Event is missing after "UpdateItemAnalysisView" in the IF-Statement to update add. Analysis views maybe like in codeunit 13

--- procedure OnRun of codeunit 80 ---
FinalizePosting(SalesHeader,EverythingInvoiced,TempDropShptPostBuffer);

Rec := SalesHeader;
SynchBOMSerialNo(TempServiceItem2,TempServiceItemComp2);
IF NOT (InvtPickPutaway OR SuppressCommit) THEN BEGIN
  COMMIT;
  UpdateAnalysisView.UpdateAll(0,TRUE);
  UpdateItemAnalysisView.UpdateAll(0,TRUE);
  <Missing Event>
END;

OnAfterPostSalesDoc(
Rec,GenJnlPostLine,SalesShptHeader."No.",ReturnRcptHeader."No.",SalesInvHeader."No.",SalesCrMemoHeader."No.",SuppressCommit);
OnAfterPostSalesDocDropShipment(PurchRcptHeader."No.");

--- procedure OnRun of codeunit 90 ---
FinalizePosting(PurchHeader,TempDropShptPostBuffer,EverythingInvoiced);

Rec := PurchHeader;

IF NOT InvtPickPutaway THEN BEGIN
  COMMIT;
  UpdateAnalysisView.UpdateAll(0,TRUE);
  UpdateItemAnalysisView.UpdateAll(0,TRUE);
  <Mising Event>
END;

OnAfterPostPurchaseDoc( Rec,GenJnlPostLine,PurchRcptHeader."No.",ReturnShptHeader."No.",PurchInvHeader."No.",PurchCrMemoHeader."No.");
OnAfterPostPurchaseDocDropShipment(SalesShptHeader."No.");

--- procedure Code of codeunit 13 ---
IF NOT SuppressCommit THEN
COMMIT;
CLEAR(GenJnlCheckLine);
CLEAR(GenJnlPostLine);
CLEARMARKS;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);
IF NOT SuppressCommit THEN
COMMIT;
IF SkippedLine AND GUIALLOWED THEN
MESSAGE(SkippedLineMsg);

**Comment by AlexanderYakunin** [comment]
Please specify event with parameters you need

**Comment by AlexanderYakunin** [comment]
Closing issue due to no reply

**Comment by smartinckl** [comment]
Here is the Code of codeunit 13 where the Event GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID) is called.
-- procedure Code of codeunit 13 ---
IF NOT SuppressCommit THEN
COMMIT;
CLEAR(GenJnlCheckLine);
CLEAR(GenJnlPostLine);
CLEARMARKS;
END;
UpdateAnalysisView.UpdateAll(0,TRUE);
**GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID);**
IF NOT SuppressCommit THEN
COMMIT;
IF SkippedLine AND GUIALLOWED THEN
MESSAGE(SkippedLineMsg);

As you can see in the other codeunits mentioned (see -->**Missing Event**'), there is a equal event call missing. Maybe it should be implemented in the same way with the same paramters than GenJnlBatch.OnMoveGenJournalBatch(GLReg.RECORDID) or as and event call like
**OnAfterUpdateAnalysisView(..JnlPostine,..Reg)**
