### ISSUE TITLE
Business Central - (sandbox) Job queue issue Object of type CodeUnit with ID - could not be found

### ISSUE THREAD

**Issue by tkane823** [Microsoft/AL#3015]
Hi,

We're running a codeunit in JobQueue in the licensed range for us and it is deployed as part of the extension. In the log entries window we keep seeing this error message "Object of type CodeUnit with ID - could not be found." I've omitted the object ID from here. Not sure why it's doing this. We initially had no. of minutes between runs set to 1 then increased to 3. Ideally we'd like a minute interval for what we're doing. Eventually, the errors would cause the Job queue to error and stop. Is it because the job is taking too long before next run cycle or is it some sort of business central specific issue that it's not recognizing our object? We have increased maximum no of attempts to 20 from 10. This still doesn't guarantees a successful day run for this.  Any ideas?

I'm not sure how to flag this as a question or if I even have that capability.

Thanks!

**Comment by rishiaurrishabh** [comment]
Hi @tkane823 can you share some screen shot of the codeunit and error.

**Comment by StanislawStempin** [comment]
This question is out of scope for AL forum. I will mark it as a question and leave it open for a while in case the community can help with the answer. 
For Microsoft assistance with this you would need to contact support.

**Comment by tkane823** [comment]
hi @rishiaurrishabh,
It's a custom Codeunit. Some normal functions being executed on run. Proper use of error handling is in place as well. Here is the screen cap  with the codeunit object ID omitted. This message can be seen from the log entries page. Depending on your no. of attempts it should re-attempt even with error showing untl the maximum attempt count. Then it should fail with that error. However, the error in itself is confusing... It doesn't makes any sense for the object to be not found. It is deployed part of extension. Our process provides automation with use of Job queue and manual process which also calls this same codeunit object type. No issues finding object when run manually. Good luck!
<img width="196" alt="jobqueueerror" src="https://user-images.githubusercontent.com/26280929/43233362-5d7cefbe-902a-11e8-85ce-0c37ef5b9c4c.png">
