### ISSUE TITLE
Create FastTabs in PageExtension

### ISSUE THREAD

**Issue by JSheeper** [Microsoft/AL#3016]
Currently it is not possible to add FastTabs to an existing Page with a PageExtension. 
It is only possible to add fields and groups to existing FastTabs.

Suggestion: Provide a solution to add new FastTabs to existing Pages in a PageExtension Object.

- AL Extension Version: 0.16.19969

**Comment by StanislawStempin** [comment]
I'm not sure what you mean. You can add groups to area(Content). Doesn't that get rendered as fast tabs?

**Comment by JSheeper** [comment]
Can you give me an Example for that? For me "area(Content)" only works on **Page** Objects but not on **PageExtension** Objects.

The only available options I see in PageExtensions are:
- addafter
- addlast
- addfirst
- addbefore
- modify
- moveafter
- moverbefore
- movefirst
- movelast

But these only let me specify FastTabs that already exist on the original page. I can't create new ones.

**Comment by Deepakalle123** [comment]
Have you tried like this
    addafter(General)  ---This will be new tab**
         {
             group(New)
            {
            }
        }

**Comment by StanislawStempin** [comment]
Or addlast(content), addfirst(content)

**Comment by JSheeper** [comment]
Thank you, the last suggestion worked for me!
