### ISSUE TITLE
Add Visual Studio Online build and release templates/steps

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/AL#3017]
To help automate TestSuites and packaging, there should be AL-compatible build and release templates in Visual Studio Online.

A new extension in the following category would be awesome; https://marketplace.visualstudio.com/search?target=VSTS&category=Build%20and%20release

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider it for the long term backlog. 

At the same time, this is a popular topic in the community so maybe some partners already have building something like this in their plans.

**Comment by EmilDamsbo** [comment]
This suggestion has been superseded by AL: Go for GitHub: https://github.com/microsoft/AL-Go

If you require 1st party supported CI/CD solution please use that.
