### ISSUE TITLE
Table Definition not updating in SQL

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/AL#302]
Initially created table with PK **Code**

Saw another post with issue of using **Code** as a field name, so renamed it to **"No."**, in the hope that it would solve the problem with the key as shown below, however renaming the field doesn't change the table definition in SQL. (Think the updating table definition is same problem with the key)
So, I added the **No.** field instead.

Modified Primary Key to be composite key:
![image](https://user-images.githubusercontent.com/8598877/27430560-4d50bc3a-5749-11e7-9f65-bf0ae6080677.png)

It shows up in RTC:
![image](https://user-images.githubusercontent.com/8598877/27430585-6207568e-5749-11e7-95aa-ff4ca92681f3.png)

However in SQL:
![image](https://user-images.githubusercontent.com/8598877/27430621-83ddef20-5749-11e7-9c81-24f993d05080.png)

Or will I need to create a table extension for modification to the table?

**Comment by StanislawStempin** [comment]
This will be fixed in July Update.
