### ISSUE TITLE
[.Get] If part not in group, wrong number of parameters doens't show error

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#3021]
Hi,

I have a Card page in which I have a page part.

In the OnOpenPage trigger of the card I call a CodeUnit function which call a Get function which bring data from a table to a page part.
I first put wrong number of parameters in the Get function:
If the page part is not in a group, nothing happen.
If the page is in a group, I have an error message which warns me that the given number of parameters 
is not correct. 

I can't understand why the error is displayed only if my part is in a group.

I don't have any interest to put my page part in a group for now, but it's a problem if I can't see any message when I made a mistake in the Get call if my part is not in a group.

Could someone explain me what happened ?

Thanks :)

(with a AllObj.Get(param1, param2, param3) instead of AllObj.Get(param1, param2) and part in a group)

![image](https://user-images.githubusercontent.com/29598240/43189657-5a999bcc-8ff7-11e8-9a2e-16d763cbf9aa.png)

![image](https://user-images.githubusercontent.com/29598240/43189661-5dbd61c6-8ff7-11e8-8218-1e24de29bc62.png)

**Comment by StanislawStempin** [comment]
Could you give an example of the code that results in this error? I'm not sure I fully understand the problem

**Comment by JulienDecottignies** [comment]
Hi,

The code that results in this error is just a wrong number of parameters given to the Get() method. So the error is normal and I was waiting for it. The problem is that it is displayed only if my page part is in a group. Here is code samples:

CodeUnit (OurCodeUnit):
...
`if (TableID <> 0) and **AllObj.Get(AllObj."Object Type"::Table, '', TableID**) then begin`
...

(for this line, it should be **Allobj.Get(AllObj."Object Type"::Table, TableId** so it has to show the error message) 

Page:
OnOpenPage()
-> Makes a call of the CodeUnit to fill the part
```
OurTable.GET(GETRANGEMIN(Code));
        CurrPage.StructureLines.PAGE.InitPage(OurTable.Code);
        DataMapping.SETRANGE("Primary Table ID",OurTable."NAV Table ID");
        if DataMapping.IsEmpty() then
          OurCodeUnit.ReadStructure(OurTable."NAV Table ID",OurTable."NAV Table ID",0,false,LineNo);
```
and the layout looks like this:
```

    layout
    {
        area(content)
        {
            group(General)
            {
                Editable = false;
                field("Code";Code)
                {
                    ApplicationArea=All;
                }
                field(Description;Description)
                {
                    ApplicationArea=All;
                }
            }
            // uncomment group to display the error 
           // Group(Lines)
          //  {
                part(StructureLines;"Structure Lines")
                {
                    ApplicationArea=All;
                }
          //  }
        }
    }
```

As in this example, if I run my page with this configuration, I won't see any error message. If I just uncomment the commented lines in the layout, the error message will be displayed.

**Comment by StanislawStempin** [comment]
Got it, thanks. We will need to investigate further.

**Comment by StanislawStempin** [comment]
This does no longer reproduce on the latest bcsandbox-master build. Please let me know if you're still running into the issue. I will keep this ticket open for a week.
