### ISSUE TITLE
Reports testing in test automation

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#3024]
![image](https://user-images.githubusercontent.com/39740300/43201131-40f6e6aa-9035-11e8-871a-ddd460cb74d7.png)

![image](https://user-images.githubusercontent.com/39740300/43201323-c8499ba2-9035-11e8-9784-1715b6477bb5.png)

I am trying to check the reports in test automation i am getting the issues like this could somebody suggest me how to overcome this

**Comment by StanislawStempin** [comment]
You can use the Report.SaveAs function that allows exporting the report into a stream in various formats.

**Comment by srinivasbanny** [comment]
@StanislawMinksztym  could u suggest any base codeunits or any examples if possible

**Comment by srinivasbanny** [comment]
@StanislawMinksztym   @thpeder 
I tried writing the below code but its not working can u suggest 
            TempBlob.Blob.CreateInStream(NVInStream);
            TempBlob.Blob.CREATEOUTSTREAM(NVOutStream);
             Report.SaveAs(REPORT::"Sales - Invoice",'',ReportFormat::Xml,NVOutStream);
i am getting the below error 

A call to System.IO.File.ReadAllText failed with this message: Empty path name is not legal.

please do suggest

**Comment by thpeder** [comment]
HI @srinivasbanny,
What version are you running?
That code you have looks fine, and runs without a problem for me.

**Comment by srinivasbanny** [comment]
version 13.0.22815
al build 0.17.22710
