### ISSUE TITLE
[Event Request] COD80 Sales-Post DeleteAfterPosting

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#3027]
Can we have an `OnBeforeDeleteAfterPosting` in `DeleteAfterPosting` in COD80 Sales-Post with handled pattern please?
```
LOCAL DeleteAfterPosting(VAR SalesHeader : Record "Sales Header")
///>>>///
OnBeforeDeleteAfterPosting(VAR SalesHeader, Handled);
if Handled then 
  exit;
///<<<///
```

**Comment by StanislawStempin** [comment]
The event already exists. Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
