### ISSUE TITLE
Report word layout

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#3028]
Hi all,

Is it possible to add new line inside repeater section in word layout, like in RDLC:

![image](https://user-images.githubusercontent.com/34686682/43211874-e2d4d552-9032-11e8-956f-288e66224303.png)

It looks like Word doesn't allow it. Or we are missing something.
Our clients use additional description field (text 250), and it must be printed below each line in all sales and purchase documents (orders, invoices, memos...)

Thanks,
Radovan

**Comment by StanislawStempin** [comment]
Closing since this is being discussed on Yammer.
