### ISSUE TITLE
Field added through designer not accessible through extension

### ISSUE THREAD

**Issue by dvlpr-life** [Microsoft/AL#3029]
- AL Extension Version: 0.16.19969
- Version: 11.0.23019 

A field was added through the Object designer (including custom and ISV)
![image](https://user-images.githubusercontent.com/33629813/43212491-1473b596-9002-11e8-8771-7651341e9e70.png)

Downloaded symbols (published/installed other extensions)

The added field is not accessible through AL. Other extension fields are accessible.
![image](https://user-images.githubusercontent.com/33629813/43212501-1eab026c-9002-11e8-95b0-7e72c20f9d25.png)

Is there an option that allows for "custom" field access?

**Comment by dNsl9r** [comment]
Please check if _EnableSymbolLoadingAtServerStartup_ is enabled in your Server Settings. Read more here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side

**Comment by dvlpr-life** [comment]
That solved it! Thank you!
