### ISSUE TITLE
Suggestion: Discard Changes In-Client Designer

### ISSUE THREAD

**Issue by ewaldventer** [microsoft/AL#303]
Hi,

Although you are able to delete the Extension after designing, it would be nice to discard changes.
Ideally a "Discard Changes to Current Page" function.

Kind Regards,

Ewald

**Comment by StanislawStempin** [comment]
This is on our backlog but we don't have a timeline for it yet.

**Comment by qutreson** [comment]
Hi! Thank you for your suggestion about having a more granular way to remove changes in the designer. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product (client, application and server), we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
