### ISSUE TITLE
Q: How are you working with translation files?

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#3038]
I'm wondering how everyone is working with the translation files.
It's great we can enable the 'TranslationFile' feature, which generates 'yourextension.g.xlf' and continuously adds new fields/captions while you are developing. But what is the best practice for maintaining multiple languages while actively developing your solution?

My issue:
- Create a table.
- Add 5 fields.
- Build the app.
- File yourextension.g.xlf is generated with those 5 fields.
- Copy yourextension.g.xlf to yourextension.nl.xlf.
- Change the target language of yourextension.nl.xlf to nl-NL.
- Translate the 5 fields in yourextension.nl.xlf to Dutch.
- Great, the extension is translated.
- Now add a 6th field to the table.
- Rebuild the app.
- The 6th field is now added to yourextension.**g**.xlf
- But the 6th field is not added to yourextension.**nl**.xlf

Is there a mechanism I'm overlooking or is everyone manually merging the translation files?
If it's a manual process, that's a real pain in the butt when you're working on an app with a large development team, with members who are all actively adding new tables and pages at the same time.

**Comment by DennisReinecke** [comment]
You should use a tool to manage your translations.
* generate "yourextension.g.xlf"
* upload "yourextension.g.xlf" to your tool
* translate to nl language
* download "yourextension.nl.xlf"

after you add a new field to your table 
* upload the file to your tool again
* the tool should know the last 5 translations 
* translate the new one
* download the new "yourextension.nl.xlf"

**Comment by GreatScott000** [comment]
What tool should we use?

**Comment by StanislawStempin** [comment]
There was another long thread about XLIFF tooling and a lot of suggestions shared.
