### ISSUE TITLE
Suggestion : Compiler check on 'Image'

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#304]
(_Nice to have_) In previous versions of NAV we had some '8ball' images due to wrong 'Image' properties, mainly related to typos.  The IntelliSense available in the new designer assists us in minimizing typos. However, it could be interesting having the compiler to alert on non-existing image properties.

![image](https://user-images.githubusercontent.com/25268332/27437865-dd8f43ec-5763-11e7-91de-d5c9afb2b83c.png)

![image](https://user-images.githubusercontent.com/25268332/27437883-ecac8736-5763-11e7-86f3-89327a0e45fb.png)

**Comment by qutreson** [comment]
Hi @fvet, we recently made some work around the image property in the compiler and we are now returning a warning in case the image name is not valid.

In your example, it would look like this:

![image](https://user-images.githubusercontent.com/31541422/38603006-beca2ee6-3d6c-11e8-864d-0705f8476544.png)

In case of typos or non-existing images, you can then use Intellisense to get the correct spelling of the image.
