### ISSUE TITLE
AL Code for Extension Sales and Inventory Forecast

### ISSUE THREAD

**Issue by superduck1302** [Microsoft/AL#3047]
Hello,

is it possible to provide me with the AL Code for the Sales and Inventory Forecast Extension? I would like to recreate something similar and would like to use this Extension as a basis for my own Cortana Intelligence Predictive Analytics Forecast. Thank you very much for your help and I'm looking forward to your reply.

**Comment by JesperSchulz** [comment]
Absolutely! We are one by one publishing our extensions onto https://github.com/Microsoft/alappextensions for you learn from, contribute to, branch off of. I will put the Sales & Inventory Forecast Extension on my list as the next extension to publish. It should be available within a week. If that isn't timely enough, please let me know and I can find another way to provide the code to you. Btw. if you have acccess to the DVD, you will also find the source code under the Extensions folder!
If you have any improvements you'd like to make to the extension and would like to share with the community, I would love to get a PR on GitHub, once the extension has been published :-)

**Comment by JesperSchulz** [comment]
Were you ever able to get your hands on the code? Publishing the code onto GitHub is delayed, but the code was published on the DVD the past couple of releases. Did you find it?

**Comment by JesperSchulz** [comment]
Cloing issue for now. If you were having problems getting the code, please reopen issue and I'll provide you with the code in some other way :-)
