### ISSUE TITLE
Mail 397 throws error in Internal Extension

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#3049]
I am getting following error when using a button which uses Code from codeunit 397 Mail. 
```
The process cannot be completed because an unsupported function is used (.NET Framework-Interoperability)
```
 For this Extension I used a daily build from the 27 July, 2018 and I got the AL Version: 0.17.26287

Here are my test files:

[page.txt](https://github.com/Microsoft/AL/files/2235900/page.txt)
[app.json.txt](https://github.com/Microsoft/AL/files/2235901/app.json.txt)
[launch.json.txt](https://github.com/Microsoft/AL/files/2235903/launch.json.txt)

**Comment by rdebath** [comment]
Client side DotNET does not work with the web client only the Windows client.
Though they could make it work with a specially configured Windows browser.

**Comment by OlivierHellmann** [comment]
@rdebath I thought I can use codeunit 397 as a dotnet replacement. How am I supposed to send mails via Outlook then?

**Comment by rdebath** [comment]
You can use any existing objects that contain server side DotNET as long as the methods you call have the `[External]` decorator. So Codeunit 400 SMTP is available as are many of the objects that call DotNET classes. If a method doesn't have `[External]` you can submit an "expose request" here.

But anything that would talk to DotNET on client side with BC has to deal with the the fact that a normal web browser will not have any trust in the remote. This includes anything trying to use Word, Excel and Outlook on the client. For Word and Excel the Nav objects are being altered to create files on server side and trigger a simple download. Outlook is harder; though as well as the traditional SMTP stuff, there appears to be some functionality that works with O365 (Haven't tried it, or even looked at it properly though).

More complete integration, such as extracting the email currently highlighted in Outlook into the database is simply impossible with the web clients.

**Comment by OlivierHellmann** [comment]
But when I set the target property in the app.json I can use all functions, not only the [External] ones. So if I understand you corractly this is a restriction depending from the web browser?

**Comment by rdebath** [comment]
Exactly. The web browser has no way to trust any host so it won't trust BC or even a service tier running on the same machine.

**Comment by OlivierHellmann** [comment]
@rdebath thank you very much for your help
