### ISSUE TITLE
get june update in may update azure machine

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#305]
Hi,

how can i get the latest june update on my existing azure machine which has old version of al extension.

Please suggest me on this.

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
You cannot do that right now, you need to provision a new VM from https://aka.ms/navdeveloperpreview and move your AL source code over.

**Comment by bachii1010** [comment]
Okey,

But how long will this continue as every month when a new update is created we have to create a new vm.
This is not going to work all time .

do you have a time frame when this can be upgradable without creating a new vm

**Comment by StanislawStempin** [comment]
We are working on a new distribution mechanism that will not require a new vm each time. Stay tuned for announcement
