### ISSUE TITLE
The type or method 'EvaluateValueWithValidate' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/AL#3051]
NAV Version: 12.3.23139.0-W1

Can we this Visibel and External

local procedure SetFieldValue(var FieldRef : FieldRef;Value : Text[250]);
    var
        ConfigValidateManagement : Codeunit "Config. Validate Management";
        ErrorText : Text;
    begin
        TruncateValueToFieldLength(FieldRef,Value);        
        ErrorText := ConfigValidateManagement.EvaluateValueWithValidate(FieldRef,Value,true);
        if ErrorText <> '' then
          Error(ErrorText);
    end;

Thanks

**Comment by grobyns** [comment]
Hi,

Please provide object type, object id and object name as well as the function name you would like us to consider making external.

From the title and text you've provided it is not clear to me whether you want EvaluateValueWithValidate or SetFieldValue to be made external.

Also, we generally do not make local functions global and external so please provide an explanation of why you need this method exposed and why a workaround will not work.

br/Gert

**Comment by clausmacali** [comment]
Hi gert

Change the FunctionVisibility to External for the Function EvaluateValueWithValidate available in the Code unit 8617 – “Config. Validate Management”, this function helps us in validating the Value to a field reference, otherwise I need to create all these functions in AL .

Hilsen/ regards

Claus
Navapp/Macali
+45 5223 7070

________________________________
Fra: Gert Robyns <notifications@github.com>
Sendt: torsdag, august 2, 2018 09:04
Til: Microsoft/AL
Cc: Claus Petersen; Author
Emne: Re: [Microsoft/AL] The type or method 'EvaluateValueWithValidate' cannot be used for 'Extension' development. (#3051)


Hi,

Please provide object type, object id and object name as well as the function name you would like us to consider making external.

From the title and text you've provided it is not clear to me whether you want EvaluateValueWithValidate or SetFieldValue to be made external.

Also, we generally do not make local functions global and external so please provide an explanation of why you need this method exposed and why a workaround will not work.

br/Gert

**Comment by grobyns** [comment]
Hi,

EvaluateValueWithValidate is already external in the latest version.

br/Gert

**Comment by clausmacali** [comment]
Thanks Gert

Med venlig hilsen
Best Regards

Claus Petersen
MACALI ApS
Hegnsgårdsvej 38
DK-7120 Vejle Ø
claus@navapp.dk<mailto:claus@navapp.dk>

Mobil + 45 52 23 70 70
_______________________________________________________________________________________________
[macali-03]    [navapp-05]
_______________________________________________________________________________________________




Fra: Gert Robyns <notifications@github.com>
Sendt: 3. august 2018 09:06
Til: Microsoft/AL <AL@noreply.github.com>
Cc: Claus Petersen <claus@navapp.dk>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/AL] The type or method 'EvaluateValueWithValidate' cannot be used for 'Extension' development. (#3051)


Hi,

EvaluateValueWithValidate is already external in the latest version.

br/Gert
