### ISSUE TITLE
[Performance Issue]VAT Posting Setup - Page opening very slow

### ISSUE THREAD

**Issue by hhfiddelke** [Microsoft/AL#3054]
Opening if the VAT Posting Setup-Page in a database with small real data ( 2Mio G/L Entries) takes about one minute. 
This is caused by the field "Used in Ledger Entries". 
The Calcformula:
> Count("**G/L Entry**" WHERE (VAT Bus. Posting Group=FIELD(VAT Bus. Posting Group),VAT Prod. Posting Group=FIELD(VAT Prod. Posting Group)))

counts on a filter for which there is no key in G/L Entry exists. Switching formula to:
> Count("**VAT Entry**" WHERE (VAT Bus. Posting Group=FIELD(VAT Bus. Posting Group),VAT Prod. Posting Group=FIELD(VAT Prod. Posting Group)))

fixes this and the page opens fast.

**Comment by hhfiddelke** [comment]
if you remove this field, you should also remove it also from "General Posting Setup" and "Inventory Posting Setup" to give even more performance. ;)

**Comment by grobyns** [comment]
Hi,

The 'feature' was redesigned so now the value is calculated in code, the functionality itself was not removed.

br/Gert
