### ISSUE TITLE
Dynamics 365 BC Export-NAVApplicationObjectLanguage Warning

### ISSUE THREAD

**Issue by NickLin1017** [Microsoft/AL#3055]
Hi

I exported the Dynamics 365 BC W1 version of the objects from my docker.

Try to export the Native language from this object.

But I got the following warning.
![image](https://user-images.githubusercontent.com/34726930/43380154-9ac1c45e-9402-11e8-94d2-c90bf017c196.png)

Does anyone know what the reason is?Thanks.

**Comment by StanislawStempin** [comment]
Hi, 
Are you using the latest version of the commandlet? The warnings that you see about APIPublisher indicate that you might be using too old of a version of the commandlet compared to the exported .txt file.
