### ISSUE TITLE
Option string in table extension

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#306]
Hi,

How can we add an extra option in option string of the existing fields in table extension?

Please let us know.

Thanks,
Varun Reddy

**Comment by esbenk** [comment]
It is not possible. The current option implementation doesn't support multiple customisations.  We are aware of that, but don't have a solution for it yet..

**Comment by AL4Github** [comment]
when can we expect the solution.

**Comment by StanislawStempin** [comment]
We do not have a specific timeframe. This is one of many things on our long-term backlog.
