### ISSUE TITLE
How Permission Set XML work

### ISSUE THREAD

**Issue by RuiningFan** [Microsoft/AL#3066]
- AL Extension Version: 0.16.19969

- Server Version: US Dynamics NAV 12.2 (23241)

Hi All,

I'm not quite sure how the Permission Set works in BC. I create some tables and add them into the permission set. When I uploaded them to the production environment. It failed with error "table *** missing permission set". My Permission XML has been create successfully and I could see a new permission set with the role name and extension name. It didn't added into the permission set that I have created.
![image](https://user-images.githubusercontent.com/34213721/43392722-22d3dfca-9427-11e8-8c8f-98ed0fb4b878.png)
![image](https://user-images.githubusercontent.com/34213721/43392768-426340ec-9427-11e8-91f0-764e500abc3d.png)

So I am wondering that what steps it usually takes for permission set when we create a new table? Creating a new role in the web client and publish the permission set xml? Why I saw the table missing permission error even I have the permission set xml? 

Thank in advance!!

**Comment by rishiaurrishabh** [comment]
Please refer to issue #2977 , it has steps for defining permission set.

**Comment by StanislawStempin** [comment]
ObjectType in your xml should be TableData and not Table.  
TableData can be assigned Read, Insert, Modify, Delete permissions
Table can be assigned only the Execute permission

**Comment by RuiningFan** [comment]
Yes, I'm keeping set permission set to table and it always return the same error when I upload the extension. When I switch to tabledata, it all works well.
