### ISSUE TITLE
Const(0d)

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#3072]
I get the following error if I try and publish my extension from VS Code or PowerShell:

The request for path /nav/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Unexpected value 'Date' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.ConstantValueTypeDiscriminator'

Some notes:
- The extension builds without errors or warnings.
- This extension contains about 2500 files
- This extension is an ISV solution that was converted from CAL

Is there any indication of where I should look for issues on this error? With so many object files it's going to be quite difficult to try and pinpoint down the solution blindly. Normally I'd remove the files and add them back one by one to try and find the bad file but it's not going to be easy when so many of these files reference each other.

**Comment by rishiaurrishabh** [comment]
The way I see it, you have an issue in the code with a Date variable, because it says in Reason : Unexpected value 'Date'.
I recommend you to enable code analysis from user setting 
"al.enableCodeAnalysis" , which may help you to identify the exact line of the error.

**Comment by MikeGlue** [comment]
Was out at lunch and thought of the same thing. Going through the process now, but turning on the code analysis on 2500+ AL files is not super fast..... :)

**Comment by MikeGlue** [comment]
I found the issue! None of the code analysis tools caught this in VS Code. Looks like the issue is if you use 'const (0D)' in the RunPageLink property.

The following sample AL object will replicate the issue. If you change the 'const (0D)' to 'filter (0D)' it works.
```
page 50000 MyPage
{
    PageType = List;
    UsageCategory = Lists;
    ApplicationArea = All;
    SourceTable = Item;

    layout
    {
        area(Content)
        {
            repeater(Group)
            {
                field("No."; "No.")
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    actions
    {
        area(Navigation)
        {
            action(ItemLedgerEntries)
            {
                ApplicationArea = All;
                Caption = 'Item Ledger Entries';
                RunObject = page "Item Ledger Entries";
                RunPageLink = "Posting Date" = const (0D);
            }
        }
    }
}
```

**Comment by MikeGlue** [comment]
Forgot to mention that I am using BC build 23500
