### ISSUE TITLE
[Function expose] Codeunit 397 Mail - Send

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#3081]
In Codeunit 397 the function Send() should be external. Thanks.

**Comment by grobyns** [comment]
Hi,

Could you explain why you want this method to be external? 

Just FYI, this method will not work on the web client (so it won't work in SaaS) because it uses client side .net to communicate with Outlook.

br/Gert

**Comment by grobyns** [comment]
closing the thread as no reply for quite a while...
