### ISSUE TITLE
[Event Enhancement] OnAfterInitGLEntry Parameters

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#3084]
The function `OnAfterInitGLEntry(GLEntry,GenJnlLine);` on COD12 is used in our localization context and would be usefull if the GLAccNo would be part of the parameters just like this:
OnAfterInitGLEntry(GLEntry,GenJnlLine,GLAccNo);

**Comment by AlexanderYakunin** [comment]
Record GLEntry alredy have GlAccNo assigned, therefore there is no need for additional parameter here

**Comment by martinhocosta88** [comment]
That's true but also InitGLEntry comes with GLEntry and GLAccNo as parameters. Doesn't seem consistent but gonna do so as you said and test.
