### ISSUE TITLE
Build performance in VSCode is slow on RDS

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#3088]
I have 2 environment with the same repo.  On both, I run the build-process (CTRL+SHIFT+B).  Version of VSCode and the AL Extension is the same.  Performance of the build is "slightly" different:
- my laptop - 20 seconds
- our RDS environment - 20 minutes
This while the resources on the RDS are better.. .

This is what we see:
![image](https://user-images.githubusercontent.com/12088142/43458780-bedf07ec-94cb-11e8-9d6b-b5356a746f78.png)
the "Microsoft.Dynamics.Nav.EditorrServices.Host" eats up all the CPU - of all cores:
![image](https://user-images.githubusercontent.com/12088142/43458808-d2f9346e-94cb-11e8-99d4-7aa3f7ef1b75.png)

When I kill the process, it goes back to about 5% utilization (on my laptop, I have a constant 30% utilization because of Hyper-V running)
![image](https://user-images.githubusercontent.com/12088142/43458878-0e0b2472-94cc-11e8-8abc-f15e72011b0e.png)

Funny thing, if we run this on the same RDS-server (compile without VSCode), then there is no problem at all.. :
```alc.exe /packagecachepath:"$($ProjectCachePath)" /project:"$($ProjectPath)" /out:"$($AppFilePath)" /analyzer:"$($ALCompilerCopPath)" /fullpaths  ```

Conclusion is that there is something seriously wrong in the VSCode-part of the compiler...

**Comment by waldo1001** [comment]
We just noticed that the majority of the performance loss is not due to the NAV-Codeanalysis, but it seems it comes from the .Net-CodeAnalysis:
![image](https://user-images.githubusercontent.com/12088142/43463523-0b7fbfd0-94d9-11e8-965f-37dc8315a1e1.png)
So what we will do this evening, is we will update our .Net Framework on our server and tomorrow, I'll come back to you...

**Comment by waldo1001** [comment]
Well, same version of VSCode, x64, same AL extension ...

**Comment by waldo1001** [comment]
Solved!

A windows update fixed it.  For completeness - this is the one that fixed the issue:
![image](https://user-images.githubusercontent.com/12088142/43517210-30354020-9588-11e8-87e4-293f9d248572.png)

**Comment by kalberes** [comment]
Ok, I wander how did you get that picture though? Since the current codebase does not call NormalizeWhiteSpace anymore?

**Comment by waldo1001** [comment]
That pic was indeed from the older version.  As my colleague took that screenshot, while I was testing the new version on my VSCode on that server... .
