### ISSUE TITLE
Add OnBefore/After- Lookup, Drilldown, NewRecord event support for page extensions

### ISSUE THREAD

**Issue by Anna-Gudimova** [microsoft/AL#3090]
![image](https://user-images.githubusercontent.com/10453174/43473070-fd00108e-94a3-11e8-9f8a-873e625abb91.png)

In case the image above doesn't load here's the code snippet:

pageextension 60089 "TRG General Journal" extends "General Journal"
{
    layout
    {        
            modify(CurrentJnlBatchName)
            {
                trigger OnLookup();
                begin
                    OnSetBatchReversalDateEvent(Rec,ReversalDate); 
                end;

                trigger OnValidate();
                begin
                    OnSetBatchReversalDateEvent(Rec,ReversalDate); 
                end;
            }
            modify(Amount)
            {
                trigger OnValidate();
                begin
                    SAVERECORD(); 
                end;
            }
      }
}

**Error Message:** OnLookup is not a valid trigger/ OnValidate is not a valid trigger. 
Is there a way to add code/functions/publishers to the page triggers of the native fields?

**Comment by StanislawStempin** [comment]
Currently you can only add code before or after the OnValidate trigger by using OnAfterValidate and OnBeforeValidate triggers:
```
modify("Cause Of Absence Filter") 
{
            trigger OnAfterValidate() 
            begin
            end;
}
```

You can always see the available triggers by pressing Ctrl + Space (IntelliSense) after the trigger keyword.

**Comment by Anna-Gudimova** [comment]
Will access to those field triggers be added at some point though? I need to put code on Lookup, Drilldown, OnNewRecord and other native page and page triggers that aren't available now.

**Comment by SirBETE** [comment]
@Anna-Gudimova `OnNewRecordEvent` does exist, like here on Purchase Prices page:
`OnNewRecordEvent(VAR Rec : Record "Purchase Price"; BelowxRec : Boolean; VAR xRec : Record "Purchase Price")`
But OnlookUp publishers doesn't exist yet ...

**Comment by demiliani** [comment]
Possibility of handle OnLookup event is a need. There are tons of customization here (opening custom lookup pages, applying filters and so on).

**Comment by Walwode** [comment]
hi Stanislaw, what's the status on any native OnValidate/OnBeforeValidate/OnAfterValidate events for pages and tables?

**Comment by SergioKelly** [comment]
Any news on this?

**Comment by gintuoklis** [comment]
any update on the issue?

**Comment by dtkb** [comment]
`pageextensions` now have triggers for `OnAfterValidate()`, `OnAssistEdit()`, `OnBeforeValidate()`, `OnDrillDown()`, and the much-discussed `OnLookup()`.

Is there anything else still needed here? If so, what is it? The discussion is long and not that clear.

**Comment by atoader** [comment]
Let's close this issue as most of the triggers have been added. For any new triggers, please go to BCIdeas
