### ISSUE TITLE
ConvertToPdf in codeunit 9651 "Document Report Mgt."

### ISSUE THREAD

**Issue by jvak** [Microsoft/AL#3096]
#1866 

I am reviewing this issue since it has been reported as shipped since 25th of may.
When I look at the latest daily build (bcinsider.azurecr.io/bcsandbox-master), I see that the function "ConverToPdf" is still defined as Local?

Has this issue been reverted or incidentally set as closed?

**Comment by StanislawStempin** [comment]
I can see that instead of ConvertToPdf being made global a new function in COD10 has been introduced:
PROCEDURE TryConvertWordBlobToPdf@67(VAR TempBlob@1000 : Record 99008535);
Does that meet your needs?

**Comment by jvak** [comment]
Yes, this meet our needs. This may be closed.
Thanks.
