### ISSUE TITLE
Question: Is it possible to enable and use API endpoint from local docker BC environment?

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#3098]
Is it possible to enable and use API endpoint from local docker BC environment?

I did try endpoints mentioned in this link but without success so I'm wondering if it's even possible to do that locally:

https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics

I'm using bcinsider.azurecr.io/bcsandbox-master image and I changed server configuration to have API Service enabled.

**Comment by henrikwh** [comment]
Hi ivandjordjevic,
Yes this is  possible. 
1) docker run  -m 4G -e ACCEPT_EULA=y  -e username=admin -e password=<<password>> -e UseSSL=n -e databaseInstance=SQLEXPRESS  -e CustomNavSettings=ApiServicesEnabled=true   <<image>>
2) Login to the webclient and enable & get the web services access key
3) Access the APIs using http://<containername:7048/NAV/api/beta/companies/ using basic auth header.

/Henrik
