### ISSUE TITLE
Extension Upgrade Codeunit not executing

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/AL#310]
Is the extension upgrade codeunit structure still the same and does it get executed on install?

I have tried a couple of times, but it doesn't seem to be working yet.
Skeleton structure I'm using:

```
codeunit 70072001 "Extension UPG"
{

    trigger OnRun();
    begin
    end;

    procedure OnNavAppUpgradePerCompany();    
    begin
        NavApp.RestoreArchiveData(70072000);
    end;
}
```

**Comment by ajkauffmann** [comment]
I guess it's work in progress: https://github.com/Microsoft/AL/issues/62

**Comment by StanislawStempin** [comment]
That's correct, it is still work in progress and the RestoreDataArchiveData will not do anything at this point. We plan to use it for Extensions V1 that are getting upgraded to Extensions V2.
