### ISSUE TITLE
Dynamics 365 BC Data Upgrade Error

### ISSUE THREAD

**Issue by VNikolajevas** [Microsoft/AL#3103]
Hello,

Pulled latest Dynamics 365 BC on docker and found some error.
When I'm trying to Start Data Upgrade (standard Cronus database), error occurs

![ss_1](https://user-images.githubusercontent.com/42024316/43568207-aa3f9a3c-963c-11e8-88ac-423401270c70.png)

Checked error log (pulled from docker EventViewer), there is a log (for me it seems like, that missing some files in NAV folder):
[EventError.txt](https://github.com/Microsoft/AL/files/2252484/EventError.txt)

The same error occurs, even with imported UpgradeToolKit fob or without it.

One time dropped Automation error when tried to Start Data Upgrade, it was found in Page 5432, Import() and Apply() functions, DotNet variable, which using version 13.0.0.0

![automation error page5432](https://user-images.githubusercontent.com/42024316/43569482-433e2cc8-9640-11e8-8893-31a06c85f3f1.png)

Then I tried to start NAVDataUpgrade through PowerShell, occured a bit different error at first (Also tried to uninstall all extensions, but also didn't help). After that, tried to add -SkipAppVersionCheck and i reached the same error as it was in first picture.

![pws upgrade](https://user-images.githubusercontent.com/42024316/43569607-a1382cc0-9640-11e8-8e98-9e0f954a008f.png)

**Comment by raymsft** [comment]
Hi @VNikolajevas I was unable to reproduce this. Could you please try again to upgrade to the latest image? If it still fails could you also provide some information on the source version, please?

**Comment by VNikolajevas** [comment]
Hi @raymsft,
This issue was on version 12.2.22932, you just couldn't start Data upgrade, now with newer version 12.3.23590 issue fixed and working properly. We can close this issue ticket.
