### ISSUE TITLE
Operator '-' is ambiguous on an operand of type 'Option'

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#3109]
The following code throws an error:

`PrintJobLine.Alignment := -Alignment;`

This code does not:
`PrintJobLine.Alignment := -1*Alignment;`

Would it be possible to teach the compiler that an Option is just an Integer and all operands (and integer values) are valid on Options?

We initialize option fields (and variables) from time to time with -1 and run thru a case construct or some other code.
After that code we check if the field or variable is still -1 and throw a runtime error or run code for this special condition.

This is not possible anymore with AL and needs additional variables and code to solve a simple issue.

**Comment by StanislawStempin** [comment]
This looks like a bug. The compiler converts Option to Integer in relevant contexts but it seems that we missed support for a unary minus operator.

**Comment by AndreyKorepanov** [comment]
It seems we already implemented unary minus, could you try it in the  the build version 2.0.48254+.
