### ISSUE TITLE
FlowField - Incorrect Syntax near ')'

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/AL#311]
Created the following flowfield:
``` 
field(72001;"Accrued Absence Quantity";Decimal)
{
    FieldClass = FlowField;
    CalcFormula = sum("Accrued Absence Entry".Quantity where ("Cause of Absence Code"=field("Cause of Absence Filter")));
}
```

Results in error:
```
[2017-06-23 17:19:27.77] Error: The request failed with code 422, reason: 
The following SQL error was unexpected:
Incorrect syntax near ')'.
```

**Comment by ajkauffmann** [comment]
Same error, similar scenario: https://github.com/Microsoft/AL/issues/290
But unexpected, a FlowField should not cause any update on SQL.

Too bad this worked in previous versions. I hope a new update comes out soon, the June update is now somewhat limited.
