### ISSUE TITLE
InStream.ReadText does not return value

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#312]
I have those two functions to set and read a Blob value. The GetBlobValue function does not return anything. After a lot of testing it looks like the function ReadText on the InStream object does not return a value while the Blob actually has a value.

![image](https://user-images.githubusercontent.com/19155831/27500590-5f5b523e-5869-11e7-9bc8-57bf46f64854.png)

**Comment by thpeder** [comment]
Just tried it on the June update and it worked for me.
I copied your code and first invoked the set procedure and then the get procedure, which gave me back my text.

**Comment by ajkauffmann** [comment]
Thanks, your message pointed me to what I missed. And apparently nobody noticed what I did wrong in the code. ;-)

It's a schoolboy error... I forgot to do CALCFIELDS before creating the InStream. After adding that one line of code it worked like expected.
