### ISSUE TITLE
[Suggestion] Filter Inline-AutoCompletion by target?

### ISSUE THREAD

**Issue by srenders** [microsoft/AL#3123]
When you set the target in the app.json file to: Extension, then create a complex variable in an AL-file, or do a peek definition, the compiler shows methods that are not allowed, and then when you build the solution throws the error message: "[AL] The type or method ... cannot be used for 'Extension' development. "

What if you would filter this depending on the selected value of target in the app.json?
For example, if set to Extension, then only show/propose or enable to select, functions that are allowed for Extension development. And similar to the other options.

(If this a question/suggestion that was already suggested/answered, then I apologize. I did not take the time to search all topics here ;-))

**Comment by StanislawStempin** [comment]
That's a good suggestion to help avoid running into blocked methods. However, this will also mean that there is no easy way to discover functions that are available on the base object but just need to be requested to be made External.
Ideally we wanted to still show them in the IntelliSense list but grey them out. This was not possible in VS Code last time we checked. Another option would be to use another glyph for the blocked methods.
In general, they need to stay visible in order for the function-expose requests to continue.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.

We are constantly monitoring top ideas and will consider them for a future release.
