### ISSUE TITLE
Event Request in Report-7053 (Sales Price Worksheet-OnAfterGetRecord)

### ISSUE THREAD

**Issue by AnkithShah** [Microsoft/AL#3128]
We have some customized fields in the table "Sales Price Worksheet" and "Sales Price" tables. We are inserting the values from "Sales Price Worksheet" to "Sales Price" using this report.

Can you please provide a publisher as **OnBeforeSalesPriceInsert("Sales Price Worksheet",VAR SalesPrice);** as shown below

2nd(SalesPrice) parameter must be Var type.

![image](https://user-images.githubusercontent.com/29921541/43715578-8a2b4ee8-999e-11e8-8a52-bc7c0c57db1b.png)

**Comment by thpeder** [comment]
The event already exists. Please make sure to always use a recent bcsandbox-master Docker image before filing new requests.
