### ISSUE TITLE
Getting last error text not possible in AL code?

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#313]
It appears that functions like GETLASTERRORTEXT and GETLASTERROROBJECT are not available in AL code. Is that by purpose or maybe somewhere in the backlog?

**Comment by StanislawStempin** [comment]
It's on our backlog

**Comment by StanislawStempin** [comment]
GetLastErrorText and GetLastErrorCode will be unblocked in the August Update. GetLastErrorObject will not be available for Extensions as it returns a DotNet type.
