### ISSUE TITLE
Missing IntelliSense in XmlPort - LinkFields property

### ISSUE THREAD

**Issue by Nyryus** [Microsoft/AL#3134]
Linkfields property in XmlPort doesn't show the fields to the user.

![immagine](https://user-images.githubusercontent.com/40896051/43720318-75785526-9990-11e8-90b3-8e6a04f734f7.png)

**Comment by AndreyKorepanov** [comment]
@Nyryus Thank you for reporting the issue. Fix will be shipped in the next updates.
