### ISSUE TITLE
Powershell window stuck on "Creating container SB-D365BC-US from image microsoft/bcsandbox:12.1.22475.22720-us"

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/AL#3138]
I did try many different solutions but still does not work. I did try Install/Uninstall (Docker) (Images) (Containers) (bios setup).
The bios setup (by pressing F2 on my workstation) and enable the Virtualization did not work for me. Still I cannot create a container. HELP!!!!!!!!

![container-issue](https://user-images.githubusercontent.com/22604702/43744751-6ba8a8b6-9990-11e8-8921-ce4cdf8e4b0a.png)

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
