### ISSUE TITLE
Suggestion: Add functionality to run object like with Alt+R in C/SIDE

### ISSUE THREAD

**Issue by tfenster** [microsoft/AL#314]
One of the quite few things from C/SIDE I miss in VS Code is to run an object with Alt+R. As it is quite easy to build, I created a simple VS Code extension to do that (see [marketplace](https://marketplace.visualstudio.com/items?itemName=tfenster.alrunner)) but from my point of view it would be nice to have this a s part of the product

**Comment by StanislawStempin** [comment]
This is an interesting suggestion. We will consider it for our backlog.

**Comment by waldo1001** [comment]
or: http://www.waldo.be/2017/06/14/al-with-vscode-run-extension-objects-with-powershell/
;-)

**Comment by tfenster** [comment]
@waldo1001 thanks for that hint, that gave me a new idea (see [here, last paragraph](http://navblog.infoma.de/index.php/2017/06/25/run-an-object-in-the-new-nav-dev-env-with-altr/) ) to differentiate between "publish and run" and just "run" :)
