### ISSUE TITLE
How to trigger "post" action in the Sales Order to create Posted Invoice and Shipment

### ISSUE THREAD

**Issue by RuiningFan** [Microsoft/AL#3141]
Hi everyone,

I don't know how to trigger post action in the Sales Order to create posted Invoice and posted shipment. I tied to send POST request and I got the "Entity does not support insert" error. So I am thinking that is it possible trigger the post in sales order to create Shipment in AL.

![image](https://user-images.githubusercontent.com/34213721/43769418-3f7528d2-9a6c-11e8-910e-c4b9fb06608b.png)

![image](https://user-images.githubusercontent.com/34213721/43769403-35114e02-9a6c-11e8-9656-f0966ef7e19f.png)
![image](https://user-images.githubusercontent.com/34213721/43769443-5030bfba-9a6c-11e8-905b-e1343bc97ad8.png)
![image](https://user-images.githubusercontent.com/34213721/43769482-63967180-9a6c-11e8-869c-7f224d432436.png)

**Comment by StanislawStempin** [comment]
The answer to #3140 will cover this one as well. Let's track only one of the issues.
