### ISSUE TITLE
Suggestion: Add quick sample for ExportToNewSyntax

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#315]
As the April update blog post includes a sample how to use ExportToNewSyntax with finsql but the June update seems to have removed that functionality (I get an "unknown command" error), I think it would make sense to quickly show how Export-NAVApplicationObject -ExportToNewSyntax works. There is one line on the June update blog post but I am not sure how many are going to read that and I would guess even less will know what to do

**Comment by StanislawStempin** [comment]
The blog post doesn't link to it but here is the documentation page for txt2al: 
https://msdn.microsoft.com/en-us/dynamics-nav/newdev-txt2al-tool
I can see it is missing the powershell commandlet description we will try to add that as well.

**Comment by StanislawStempin** [comment]
We have updated the help topic with a mention of Export-NAVApplicationObject and a reference to the full help of how to use the cmdlet. It will be public with January Update.
