### ISSUE TITLE
COD426 Payment Tolerance Management CallPmtDiscTolWarning

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#3150]
Can in COD426 Payment Tolerance Management function `CallPmtDiscTolWarning` have an extra parameter type (Customer/Vendor)?
And can it be passed on to PAG599 Payment Disc Tolerance Warning function `SetValues `?
If possible, can it be used to get the customer/vendor and display the name (in standard NAV/BC)?

Our client knows nothing with just the customer/vendor no.
So we had to modify 2 objects and 3 functions in order to display the Customer/Vendor Name:

In COD426:
```
[External] PmtTolCust(VAR CustLedgEntry : Record "Cust. Ledger Entry") : Boolean
...
    IF GLSetup."Payment Tolerance Warning" THEN BEGIN
      gtxtCustVendName := Customer.Name;  // IT
...
```

```
[External] PmtTolVend(VAR VendLedgEntry : Record "Vendor Ledger Entry") : Boolean
...
    IF GLSetup."Payment Tolerance Warning" THEN BEGIN
      gtxtCustVendName := Vendor.Name; // IT
...
```
```
LOCAL CallPmtDiscTolWarning(PostingDate : Date;No : Code[20];DocNo : Code[20];CurrencyCode : Code[10];Amount : Decimal;AppliedAmount : Decimal;PmtDiscAmount : Decimal;VAR RemainingAmountTest : Boolean) : Boolean
IF PmtDiscAmount = 0 THEN BEGIN
  RemainingAmountTest := FALSE;
  EXIT(TRUE);
END;
// IT start
IF gtxtCustVendName <> '' THEN
  PmtDiscTolWarning.f_SetCustVendName(gtxtCustVendName);
// IT stop
PmtDiscTolWarning.SetValues(PostingDate,No,DocNo,CurrencyCode,Amount,AppliedAmount,PmtDiscAmount);
PmtDiscTolWarning.LOOKUPMODE(TRUE);
...
```

And in PAG599
```
f_SetCustVendName(ptxtName : Text)
gtxtCustVendName := ptxtName; //IT
```
And on the page that extra field:
Expanded	Type	SubType	SourceExpr		Name			Caption
0	                Field			gtxtCustVendName	CustVendName	<CustVendName>

**Comment by ikoletic** [comment]
Will ship in first update after Fall release of Business Central.

**Comment by SirBETE** [comment]
Awesome! TY!
