### ISSUE TITLE
Setting XmlNode Value

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#3153]
Node.AsXmlElement().Add(XmlText.Create('NewValue')) appends to the value, how do you set it to blank or set a new value? 

I ended up creating and replacing the node with a new node, which is a pain if you have attributes as well.

Thanks
Joel

**Comment by atoader** [comment]
The RemoveNodes method will remove any child nodes i.e. set the contents of the element to blank.

**Comment by Joel-NAVDev** [comment]
thanks @atoader, but if you don't want to remove the child nodes and just want to change the value.

**Comment by atoader** [comment]
@Joel-NAVDev it depends on how you want to change it. Take a look at the docs we have on this https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/api/xmlelement-class . Try to implement your code in C# and if you cannot find an API that does the same thing in AL, please let me know by opening another issue.
