### ISSUE TITLE
Exposed methods are hidden in the last release

### ISSUE THREAD

**Issue by zhaohowie** [Microsoft/AL#3156]
Hi,

I asked to expose the following methods in the Issue #2117 
SetDoNotFillQtytoHandle in the Report "Get Source Documents"
GetLastReceiptHeader in the Report "Get Source Documents"
SetOneCreatedShptHeader in the Report "Get Source Documents"
SetOneCreatedReceiptHeader in the Report "Get Source Documents"
SetSkipBlocked in the Report "Get Source Documents"
SetHideValidationDialog in the Codeunit "TransferOrder-Post Receipt"
Calculate in the Codeunit "Calculate Prod. Order"

I updated the latest package today and found those methods are not exposed anymore. Can someone take a look what's going on ? 

Thanks,

**Comment by zhaohowie** [comment]
I am using "Developing for Dynamics 365 Business Central". The packages in
the VS Code are "Microsoft_Application_12.3.23590.23730.app" and
"Microsoft_System_12.0.12928.0.app".

The last working packages are "Microsoft_Application_13.0.22070.0.app" and
"Microsoft_System_13.0.12928.0.app".

**Comment by StanislawStempin** [comment]
Yes, precisely. Issues fixed on GitHub will currently end up in version 13.0.XXX. So you moved from version 13.0 back to 12.3 - that's why you see these methods as Internal.

**Comment by zhaohowie** [comment]
Thanks, I re-created another VM with 13.0.XX version. Everything is working
fine.
