### ISSUE TITLE
[EventRequest] Codeunit 80 - ReverseAmount Function

### ISSUE THREAD

**Issue by Bevalti** [Microsoft/AL#3157]
AL Language : 0.12.17091
Dynamics Nav : 11.0.22292.0

We need for our customer to add new fields in the sales lines, some of these fields are amounts, and they should be reversed in the ReverseAmount function, so we need an event (**OnAfterReverseAmount**)  : 

````
LOCAL ReverseAmount(VAR SalesLine : Record "Sales Line")
WITH SalesLine DO BEGIN
  "Qty. to Ship" := -"Qty. to Ship";
  "Qty. to Ship (Base)" := -"Qty. to Ship (Base)";
  .
  .
  .
  "Inv. Discount Amount" := -"Inv. Discount Amount";

  // New event request >>
  OnAfterReverseAmount(SalesLine);
  // New event request <<

END; 
````

Signature :

`LOCAL [IntegrationEvent] OnAfterReverseAmount(VAR SalesLine : Record "Sales Line")`

Thank you
Kind Regards

**Comment by thpeder** [comment]
The event already exists. Please make sure to always use a recent bcsandbox-master Docker image before filing new requests.
