### ISSUE TITLE
Problem with copy of report 1306

### ISSUE THREAD

**Issue by KylliS** [Microsoft/AL#3161]
Problem with Sales Invoice report. I made an extension based on Report 1306. Extension publishes to the client, but when i try to run it there, it gives me error message:
 
![setsalesinvoiceline](https://user-images.githubusercontent.com/34376290/43826409-e77785dc-9aff-11e8-9e1c-ac032dc17ab8.jpg)

It seems like there is a version difference, but the symbols are downloaded from the same place where the extension is published. No error in visual studio code. And if I look the definition of the function inside the visual studio code, its defined with 4 parameters. 
 
![setsalesinvoiceline2](https://user-images.githubusercontent.com/34376290/43826622-69f99cd4-9b00-11e8-934d-375f4b1052d5.jpg)

Has anyone faced this kind of problem?

**Comment by StanislawStempin** [comment]
Can you show the code with which you are calling the new report?

**Comment by KylliS** [comment]
Sorry, maybe my explanation was a bit misleading. 
I made a new report (copied 1306 and made some changes for client) and used txt2Al for the conversion. Publishing the extension to client works, but running it from there gives the errormessage("The user defined C/AL...").

[salesinvoice.txt](https://github.com/Microsoft/AL/files/2269720/salesinvoice.txt)

**Comment by StanislawStempin** [comment]
It looks like your symbols are out of sync with the C/AL code. In February this year the function SetSalesInvoiceLine had a 5th parameter added to it. 
It looks like you compiled against symbols which still have the old siganture of that function whereas the runtime has the new version.
Please try again on a fresh docker image from bcsandbox-master.
