### ISSUE TITLE
How to export all compilation errors and warnings from Problems view to txt/excel or similar?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#3162]
Hi, team.
Is there any opportunity to export all compilation errors and warnings from Problems view to some tabular format?

If the number of errors is quite big, it's useful to analyse them somewhere, outside of VSCode.

**Comment by StanislawStempin** [comment]
The best approach would be to compile using alc.exe. This will list all errors in the standard console output.

**Comment by dkatson** [comment]
This is 1 object example

The result from ALC.exe
![image](https://user-images.githubusercontent.com/29101017/43834116-aa282f5e-9b15-11e8-88fc-eb272ee21fea.png)

The result from VSCode problem view
![image](https://user-images.githubusercontent.com/29101017/43834149-c83a8d2a-9b15-11e8-81cb-1992e03fef11.png)

You see that alc.exe don't show about 19 errors

**Comment by StanislawStempin** [comment]
That's interesting, there shouldn't be any differences in the reported errors. Alc.exe is just a command line wrapper for the same compiler code as used from VS Code. 
Perhaps you're using different settings from VS Code? Specifically these 3 needs to be in sync:
/packagecachepath:<directory> Specify the cache location for the symbols.
 /target:<target>              Specify the compilation target.
 /features:<feature list>      List of feature flags.

**Comment by dkatson** [comment]
Strange.
I've added `/target:extention` => the result is as expected. Identical to vscode problems view.
Then I deleted `/target:extention` => the result is as expected. Identical to vscode problems view.
Seems yesterday was not my day)

Will experiment tomorrow

**Comment by StanislawStempin** [comment]
The difference is currently by design. Alc.exe fails early since it is primarily targeted towards automated builds where we don't normally expect to encounter issues. VS Code on the other hand lists all issues since it is often used with projects that don't correctly compile yet. We are currently not planning changes to this behavior.

**Comment by StanislawStempin** [comment]
There doesn't seem to be a straightforward way to do it. See if this API might help: https://github.com/Microsoft/vscode/issues/30075
