### ISSUE TITLE
Search Issue In Business Central

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#3165]
page 50000 SalesOrderLine
{
    Caption='Sales Order Line';
    PageType = List;
    SourceTable = "Sales Line";
    Editable=false;
    UsageCategory = Lists;
  .......
I have created list page according above syntax and it works fine but when I try to search this page in search bar in business central it does not show this page.
Every time i have to run with ctrl+F5 to see this page from my AL project.

**Comment by StanislawStempin** [comment]
You seem to be missing ApplicationArea and AccessByPermission properties.

**Comment by harshilpatel984** [comment]
I have Used ApplicationArea and it works
thanks..
