### ISSUE TITLE
[Event Request] Codeunit 1001, Function PostPurchaseGLAccounts

### ISSUE THREAD

**Issue by AndreBreitenbach** [Microsoft/AL#3166]
We need an Event in CU 1001 to handle own ISV Code.
![image](https://user-images.githubusercontent.com/40287548/43835472-5ccb5c0c-9b12-11e8-86b9-386d84639e6b.png)

The Event need the following parameters:
![image](https://user-images.githubusercontent.com/40287548/43835476-6414499c-9b12-11e8-9d78-3016c3917202.png)

Thanks

**Comment by ThomasBrendel** [comment]
We need a Handle-Publisher instead of the "normal" Publisher:

![image](https://user-images.githubusercontent.com/42136602/44513020-8b8aec00-a6bc-11e8-8844-753f63d5642e.png)
