### ISSUE TITLE
How to deploy .app file to the client

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#3168]
I have created test application which has one list page and i have to delploy that application on to business central without giving any kind of source code.

**Comment by StanislawStempin** [comment]
Set "showMyCode" : false in app.json and then deploy using the Upload button on Extension Management page.

**Comment by harshilpatel984** [comment]
I am working on on premises through docker image then what are the steps for deploying code

**Comment by MikeGlue** [comment]
If you install the NavContainerHelper module via PowerShell (on the Docker host) you can use the following script to publish and install an app:

```
$containerName = 'myContainer'
$appFile = 'C:\_dev\myApp.app'
$tenant = 'default'

Publish-NavContainerApp -containerName $containerName -appFile $appFile -tenant $tenant -skipVerification -sync -install
```

**Comment by harshilpatel984** [comment]
I used this command but i was unable to unpublished that application through it everytime i have to fire Unpublish-NAVApp command

**Comment by MikeGlue** [comment]
Uninstalling and unpublishing an app would look like this:

```
$containerName = 'myContainer'
$appName = 'myApp'

UnPublish-NavContainerApp -appName $appName -containerName $containerName -ErrorAction SilentlyContinue -unInstall
```

**Comment by harshilpatel984** [comment]
Thank you
