### ISSUE TITLE
[Event Request] Codeunit 1013, Function Code

### ISSUE THREAD

**Issue by AndreBreitenbach** [Microsoft/AL#3169]
We need an Event in CU 1013, Function Code to handle own ISV Code.
![image](https://user-images.githubusercontent.com/40287548/43835881-c6797b1a-9b13-11e8-93d8-f9755d85b0de.png)

The Event need the following parameters:
![image](https://user-images.githubusercontent.com/40287548/43835889-cd7f9a2a-9b13-11e8-9126-72b1f5467f0d.png)

Thanks

**Comment by thpeder** [comment]
The event already exists, it seems like you are looking at an older version.

**Comment by AndreBreitenbach** [comment]
Perfect. Just updated my BC-Docker and there it is :)
Sorry, this request can be closed.
