### ISSUE TITLE
[Question] Add more key into native table

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#317]
[Question]
Please help me.
I'm a new developer for Extension 2.0.
Example: 1. Add more file Offset Type into Table 17 G/L Entry. -> It is OK.
2. I need add more key:
keys
{
key(Key9;"Transaction No.","Document No.","Offset Type")
{
}
}
But It isn't OK.
**So how to do it. OR this isn't supported.**
From [the help link](https://msdn.microsoft.com/en-us/dynamics-nav/extension-packages-capability-support-matrix). "You can add table keys, but you cannot delete or modify existing keys".

**Comment by esbenk** [comment]
Currently this is not supported. In V1 the original table was modified when adding a field. In V2 new fields are in a companion table. 

We investigating ways to support key in tableextensions that includes fields from the base-table. We don't have a timeline for that.

**Comment by hgnamvn** [comment]
Hi Esbenk,

Thank for your reply quickly!
I hope extension can support it in the future.

**Comment by fvet** [comment]
@esbenk Related to the so-called 'companion' tables. I guess these tables are the ones referred to in the below screenshot (where I've published 2 extensions, extending the 'Customer' table), named with the Source table followed by the id of my extension?

![image](https://user-images.githubusercontent.com/25268332/27806197-7bde113a-6039-11e7-8c81-a5baea24a3f2.png)

But once I uninstall and unpublish all my extensions, **should these companion tables be deleted** as well (which is not the case), or do these tables act as the 'archive' tables to eventually restore the appdata??

Cfr. previous naming of appdata archive tables...

![image](https://user-images.githubusercontent.com/25268332/27806298-fab4b23e-6039-11e7-801b-bb03b90a7835.png)

**Comment by esbenk** [comment]
Yes, that is the companion tables. In extensions V1 the data was preserved in $AppData$* tables after uninstall, but with the separate companion tables that is not needed.
