### ISSUE TITLE
[EventRequest] Codeunit 90- Purch.-Post - ReverseAmount Function

### ISSUE THREAD

**Issue by Bevalti** [Microsoft/AL#3179]
AL Language : 0.12.17091
Dynamics Nav : 11.0.22292.0

We need a new event in the Codeunit 90, for our customer, we added new fields in the Purchase Line, some of these fields are amounts, and they should be reversed in the ReverseAmount function, so we need an event (**OnAfterReverseAmount**) :

```
LOCAL ReverseAmount(VAR PurchLine : Record "Purchase Line")
WITH PurchLine DO BEGIN
  "Qty. to Receive" := -"Qty. to Receive";
  "Qty. to Receive (Base)" := -"Qty. to Receive (Base)";
  .
  .
  .
  "Tax To Be Expensed" := -"Tax To Be Expensed";

  // New event request >>
  OnAfterReverseAmount(PurchLine); 
  // New event request <<
END;
```

Signature :

`LOCAL [IntegrationEvent] OnAfterReverseAmount(VAR PurchaseLine : Record "Purchase Line")`

Thank you
Kind Regards

**Comment by thpeder** [comment]
The event already exists in a newer version.

**Comment by Bevalti** [comment]
thank you
