### ISSUE TITLE
[Question] Obsolete parameters?

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#318]
Prior to the June Preview the launch.json did contain the following two parameters:

            "projectRoot": "${workspaceRoot}",
            "packageFileName": "${command:resolvePackageFileName}",    

These give errors in the June Preview. Are they now obsolete parameters?

If so, please remove them from the sample projects.

**Comment by StanislawStempin** [comment]
That's right, these parameters are now obsolete. We will clean up the samples.

**Comment by lvanvugt** [comment]
Thanx for the quick response
