### ISSUE TITLE
[EventRequest] Codeunit 90 - Purch.-Post - FinalizePosting Function

### ISSUE THREAD

**Issue by Bevalti** [Microsoft/AL#3181]
AL Language : 0.12.17091
Dynamics Nav : 11.0.22292.0

In the Codeunit 80 we found a usuful event in the FinalizePosting function, unfortunatly this event doesn't exist in the FinalizePosting  function of the Codeunit 90 (Purch.-Post), can you please add this event also.

```
LOCAL FinalizePosting(VAR PurchHeader : Record "Purchase Header";VAR TempDropShptPostBuffer : TEMPORARY Record "Drop Shpt. Post. Buffer";EverythingInvoiced : Boolean)
WITH PurchHeader DO BEGIN
  IF ("Document Type" IN ["Document Type"::Order,"Document Type"::"Return Order"]) AND
     (NOT EverythingInvoiced)
  THEN BEGIN
    MODIFY;
    InsertTrackingSpecification(PurchHeader);

    // New event request >>
    OnBeforePostUpdateOrderLine(PurchHeader,TempPurchLineGlobal);
    // New event request <<

    PostUpdateOrderLine(PurchHeader);
    UpdateAssocOrder(TempDropShptPostBuffer);
    UpdateWhseDocuments;
    .
    .
    .
```
Signature :
```
LOCAL [IntegrationEvent] OnBeforePostUpdateOrderLine(PurchaseHeader : Record "Purchase Header";VAR PurchaseLine : Record "Purchase Line")
```
Thank you
Kind Regards

**Comment by AlexanderYakunin** [comment]
Can you please recheck referenced events in COD80, we are working with version 13.0 and I see no events at this place. Also you added event OnBefore just after PostUpdateOrderLine(PurchHeader). Looks like mistake.

**Comment by Bevalti** [comment]
Hi Alexander,

Thank you for your return, yes it was a mistake it should be before the **PostUpdateOrderLine(PurchHeader)**, I've just corrected the code in my open issue, we have the Nav 2018 CU 6.0, this is what I have in my COD80 : 

![image](https://user-images.githubusercontent.com/42188196/44092898-be5b468a-9f9f-11e8-817a-b67e3a1dacbc.png)

This event doesn't exist in the COD90.

Kind Regards
Abdelatif EL HANI
