### ISSUE TITLE
Can we have a System Indicator?

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/AL#3184]
We have a client that has over 80 companies and one group regularly needs to switch between seven companies. It is essential for them to be able to quickly tell which company they are in. The BC Web Client shows the company name on Role Center and List Pages but does not show it on Card pages. There also does not appear to be any way to change colors or offer any other visual cue to help people to see which company they are in quickly. Can I suggest we include something within the UI that will show the system indicator. Here is my mockup of what it could look like. You could use the existing system indicator settings on the Company Information. It would be really, really nice if you could add the ability to set the color instead of picking from a set of pre-canned styles.

![image](https://user-images.githubusercontent.com/6288989/43865309-51339022-9bb6-11e8-82de-62f3b10678f9.png)

**Comment by ShadowXVII** [comment]
There was talk of system-wide theming at Directions ASIA -- the whole UI could be a different colour ;)

![image](https://user-images.githubusercontent.com/446329/43895598-32d56b60-9c19-11e8-80a9-66940bde11e0.png)

**Comment by DavidRoys** [comment]
Yeah a combination of a selectable tint color (like in Reporting services where you can pick from a list of names or enter an RGB value) and displaying the company name in the title bar for all page types would be perfect.

**Comment by thpeder** [comment]
Response from the team:

Great idea! That would help customers who regularly switch companies/environments or those who occasionally need to switch to a sandbox environment. Go ahead and post this to our Ideas forum at [https://aka.ms/BusinessCentralideas](https://aka.ms/BusinessCentralideas). If the idea gets voted up, we will surely consider it for a future release.

Thanks,
Mike Borg Cardona
Program Manager at Microsoft

**Comment by DavidRoys** [comment]
OK, I have created a new idea suggestion called [Can we have a System Indicator in Business Central?](https://experience.dynamics.com/ideas/idea/?ideaid=b9653f1f-16a0-e811-b96f-0003ff68e07f)

Can everyone that gave a thumbs up on this issue please go to the ideas site and upvote this issue?

Idea URL is https://experience.dynamics.com/ideas/idea/?ideaid=b9653f1f-16a0-e811-b96f-0003ff68e07f

**Comment by DavidRoys** [comment]
Ok - 7 thumbs up on GitHub. 1 upvote on ideas (which was me). I’m worried that the ideas site is too hard to use for people to be bothered with. I couldn’t sign in as a partner because the profile would not accept the MPN ID that is defined against our account in PartnerSource. I had to set my profile to customer.

**Comment by StanislawStempin** [comment]
Since this is a Client feature suggestion it gets tracked on the Ideas site. I will close the ticket here.
