### ISSUE TITLE
Where can I _download_ the Nav/BC Store APPs ?

### ISSUE THREAD

**Issue by rdebath** [Microsoft/AL#3188]
The clients follow best business practice and kill the store app.

I (or they) need to download the APPx file so they can load it onto the PCs with a script or during imaging.

Where do I get the file?

**Comment by StanislawStempin** [comment]
I'm not sure what you mean. Are you asking where can you download the AppSource apps for On-Premise usage? This is not possible, you need to obtain the app from the ISV directly and receive a license update to be able to run the code.

**Comment by rdebath** [comment]
We are the ISV.
As far as I can tell it is impossible to download the APP from:  https://www.microsoft.com/en-us/p/dynamics-nav/9wzdncrfjbds  
If I try to use the "Store for Business" it has the same problem.

The NAV or BC service tier and IIS site for the web client already exists and the web client works fine in a browser.

The APP is not on the DVD image (AFAICS).

As the "store app" is killed it is impossible for the client to use this Nav APP.

Is there a solution that would be acceptable to the client?

**Comment by kotelko** [comment]
Our mobile/companion apps are only available via official store(s). There is no other distribution channel.

**Comment by rdebath** [comment]
Okay, I'll tell them to use Google Chrome's `--app` mode.
