### ISSUE TITLE
Suggestions: Method overriding and event prioritizing

### ISSUE THREAD

**Issue by erikrijn** [microsoft/AL#319]
I've been really missing a few key features in NAV when trying to write clean and separated code.
Over the years, most VARs (and even ISVs) have been heavily modifying the NAV core while writing add-ons. Obviously this cannot continue in a cloud-first approach. Which is a good thing.

I come from a c#/c++/java background. While creating customizations and add-ons for multiple other platforms, I'm always able to achieve everything I need in a clean manner. But NAV has some important limitations.

**Events**:
I'd like to see a prioritizing system for event subscribers. Tenants would have the option to prioritize subscribers, not the coders (because we'll all just end up using the highest possible priority for our add-on ;)). That way the tenant can decide in what order to invoke.

**Method overriding**:
I'd like full method overriding possibilities. For example, in table 18 I want to be able to completely override the GetBillToCustomerNo method, with the possibility to call the base method if for some reason I need to fall back on it. These overrides should of course have the same kind of prioritizing system as mentioned for events.

I know this is a huge deal and a big ask, based on the current NAV tech. But it would be a massively powerful addition.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
