### ISSUE TITLE
[investigate] Create/Update of a Contact's Company produces error via API

### ISSUE THREAD

**Issue by srenders** [Microsoft/AL#3194]
We have created an API page:
PageType = API;
EntityName = 'members';
EntitySetName = 'members';
SourceTable = Contact;
DelayedInsert = true;
In the page there are several fields from the Contact table. It allows us to create contacts.

When we create a contact of type Person, it is created as it should be, without errors. But when we provide it with a Company No, then appearantly it gets a type::Company and then an error is thrown:
![contactperson](https://user-images.githubusercontent.com/17511254/43887334-cdbaa0ec-9bbe-11e8-910f-452af71a898e.png)

This is probably because of a TESTFIELD here:
![testfield](https://user-images.githubusercontent.com/17511254/43887397-02a084f2-9bbf-11e8-89fb-72de6fab9db3.jpg)

But we create the contact as Type::Person, so the error should not occur. Can't figure out what we are doing wrong here...

**Comment by AndersLarsenMicrosoft** [comment]
Great to see that you have started creating API's.
 To me this looks like the validation order play in here. the default value of type is Type::Company. Could you list the fields that you have in our api in the order same order as in our API. 

The validation on the contact table is a bit special with the Type and Company No. 
If you create a contact without Company No. and Type = company then company no becomes No.
If you create a contact with type = person then you should be able to define the company number manual.

Send me the list of fields and let me know if you have validation on the contactType and the companyNo 

 
Thanks
Anders

**Comment by AndersLarsenMicrosoft** [comment]
I took another look at this issue. The problem that you are facing is not API related. 

In the UI I needed to create a contact.
Change the type to person.
Set the intended company. 
Change type to company.

We should try to improve this from our side

Thanks
Anders
