### ISSUE TITLE
VM Name

### ISSUE THREAD

**Issue by ftornero9** [Microsoft/AL#32]
When creating the virtual machine I get an error because I already have another one with the name Server1.

**Comment by ftornero9** [comment]
After changing this variable:

    "server1Name": "Server1",

I get the next error
{
  "error": {
    "code": "InvalidTemplate",
    "message": "No se pueden procesar las expresiones de lenguaje de plantilla para el recurso '/subscriptions/e03b2e1d-5111-4e0b-892c-b450b43ee896/resourceGroups/PTNAV2017RECURSOS/providers/Microsoft.Compute/virtualMachines/Server2/extensions/vmextension1' de la línea '1' y la columna '17674'. 'No existe la propiedad de expresión de lenguaje disponible 'templateLink', las propiedades disponibles son 'template, parameters, mode, provisioningState'.'"
  }

This say that there is not property "templateLink", and that is the part of the script with the code.

        "settings": {
          "fileUris": [
            "[uri(deployment().properties.templateLink.uri, 'initializeTenerife.ps1')]"


Regards

**Comment by waldo1001** [comment]
Strange, I have two "Server1"s running at the same time without any problems.. .  You probably used an already existing resource group .. I don't do that .. .

**Comment by ftornero9** [comment]
Yes, but I change de name and the resource group and I get the next reported error.

Regards.

**Comment by freddydk** [comment]
Don't change the template - deploy to a new resource group and you can have as many server1's as you like in different resource groups.

**Comment by waldo1001** [comment]
Indeed, that's what I do.  Mind the costs though ;-).

Thx,

/waldophone

On 20 Dec 2016, at 18:34, Freddy Kristiansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't change the template - deploy to a new resource group and you can have as many server1's as you like in different resource groups.

-

**Comment by freddydk** [comment]
Resource groups themselves are free - you pay for compute hours and it is the same if you have 2 VMs in 2 resource groups or in one. Just remember to delete or shut down what you don't use/need then you should be fine.
There are several reasons why you cannot have 2 NAV Vms in the same resource group - stuff like the security group, the storage account and all have calculated names because people shouldn't answer 20 questions to get a simple VM deployed:-)
