### ISSUE TITLE
Error when open extended native-page.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#320]
I tested on version Microsoft Dynamics NAV TENERIFE, Version US Dynamics NAV 10.0 Build 10.0.17303.0
1. I created tableextension for "G/L Account" to add more field "Name VN"
tableextension 70000001 GLAccountExt extends "G/L Account"
{
    fields
    {
        field(70000002;"Name VN";Text[120])
        {
            CaptionML=ENU='Name VN';
        }
    }
}
2. I created pageextension for "G/L Account Card" to show added field.
pageextension 70000003 ChartAccountExt extends "G/L Account Card"
{
    layout
    {
        addlast(General)
        {
            field("Name VN";"Name VN"){}
        }
    }
}

Result:
After I build, publish and install the package. When I open Chart of Accounts page, I get a error:
**The multi-part identifier "G/L Account.No_" could not be bound. Statement(s) could not be prepared.
Page Chart of Accounts must close.**
If I uninstall and unpublish the package, I can open Chart of Accounts page well.

**Comment by StanislawStempin** [comment]
It reproduces on our latest builds as well. We will investigate further.

**Comment by hgnamvn** [comment]
Hi StanislawStempin,
Thank for your reply.
I will test again with the next builds.

**Comment by Avanti05** [comment]
This seems to be an issue with the Payment Journal/ Gen. Jnl. Line as well.
