### ISSUE TITLE
How to setup Business central environment

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#3202]
Currently I am using On-Premises with docker but I have to work with the actual Azure Environment What are the steps to setup whole test environment on the AZURE

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
