### ISSUE TITLE
Need access to 'ThrowGenJnlLineError' in Codeunit 11

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#3204]
Function 'ThrowGenJnlLineError' in Codeunit 11 needs to be made external so that I can use it in our ISV extension. Thanks.

**Comment by JesperSchulz** [comment]
Preferably, we should not expose that local function, as there really isn't any logic that would make sense to expose (unless of course I misunderstand something here). To me it looks like the function simply throws the error message provided, based on a condition of another function parameter. It would look like you could throw that error by yourself without taking a dependency on our code here. I will close this request. Please re-open, if I have misunderstood something of if you strongly believe this should get exposed.
