### ISSUE TITLE
FlowField CalcFormula using Code Field added with tableextension

### ISSUE THREAD

**Issue by eknraw** [Microsoft/AL#3210]
Using docker image: microsoft/bcsandbox:12.3.23590.23730-us

- AL Extension Version: 0.16.26913

I have a Code field "Job Status" defined in a tableextension against the Job table.  

```
        field(50100; "Job Status"; integer)
        {
            FieldClass = Flowfield;
            CalcFormula = Count("Job" where("Job Status" = filter("AWAITING")));
        }
```

error AL0186: Reference 'Job Status' in application object 'Job' does not exist
Error: The package could not be created.

Works fine if the field is of type Option.  Besides being poor design on my part, is this a bug or desired behavior? 

Looks very similar to issue: 
#196

**Comment by StanislawStempin** [comment]
I cannot reproduce the problem. Is this more or less the code that you are using?
```
tableextension 50100 JobExtension extends Job
{
    fields
    {
        field(50100; "Job Status"; Code[20]) { }
    }
}

table 50101 NewTable
{
    fields
    {
        field(1; Key2; integer)
        {

        }
        field(50100; "Job Status"; integer)
        {
            FieldClass = Flowfield;
            CalcFormula = Count ("Job" where ("Job Status" = filter ('AWAITING')));
        }
    }
}
```

**Comment by kalberes** [comment]
You do not need to quote Awaiting. The error message is not the best one for sure. Also you should be able to cast an option to an integer.
Looks like a bug #3117

**Comment by eknraw** [comment]
@StanislawStempin Yes, you have my exact scenario.  It's my double quotes.  As a literal like you have it then it works like I expected.  

@kalberes Yes, if I change from a Code to Option then without quotes works fine.
