### ISSUE TITLE
[Event Request]Codeunit 5760, functions Code & InitSourceDocumentLines

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3217]
Hi,
We need 2 new events in Codeunit 5760 Whse.-Post Receipt.

1. Function InitSourceDocumentLines
![image](https://user-images.githubusercontent.com/41729653/43948275-b6a8231c-9c8a-11e8-9920-69f022aee603.png)
With parameters:
![image](https://user-images.githubusercontent.com/41729653/43948321-ce520348-9c8a-11e8-9694-a4d9ff1f4357.png)

2. Function Code
![image](https://user-images.githubusercontent.com/41729653/43948360-eac3221e-9c8a-11e8-9f4f-de48d5bf831e.png)
With parameters:
![image](https://user-images.githubusercontent.com/41729653/43948392-fc85df50-9c8a-11e8-96c5-82a5efd5b74d.png)

Thanks in Advance

**Comment by thpeder** [comment]
These events already exists
