### ISSUE TITLE
Add Report to menu

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#3218]
I have created report regarding sales order and i have to put it in to menu how i can i put this report on to the list of sales report?

I used Usage Catagory but it only works when i search that report

**Comment by StanislawStempin** [comment]
This is not possible and the menu suite is not supported in the Web Client. There are alternative ways to expose the report - please see this FAQ entry for more details:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#menusuite-objects-are-not-supported-what-do-i-do

**Comment by harshilpatel984** [comment]
Thanks
