### ISSUE TITLE
Deploy (F5) and Error - Root Folder

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#322]
Hello,
i have created a new Project. After dveloping my stuff i tried to deploy the Project. 
- i pressed Crtl-Shift-B and all went fine (Success: The package is created.)
- after pressing F5 visual Studio Code Comes up with an error

"The root folder for AL files must be added to the debugger configuration file."

What to do now?

**Comment by esbenk** [comment]
Are you running on the latest preview (June)?

**Comment by KaiSwitalla** [comment]
i will check and answer as soon as possible.

**Comment by KaiSwitalla** [comment]
where can i check it? When i take a look at the nav build, it is 10.0.16477. Hope that will do...

**Comment by esbenk** [comment]
Please check the extension version.

![image](https://user-images.githubusercontent.com/24257835/27689360-3b76aa66-5cde-11e7-8ccd-c2959279c642.png)

**Comment by StanislawStempin** [comment]
Closing based on the assumption that this was an old version. Please reopen if you encounter it on the latest version.
