### ISSUE TITLE
The server  was unable to process the request. The application will close

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#3222]
NAV is getting crash ,when i am running a RDL report, it has been designed in extension 
This issue coming for the particular report all others reports are running perfectly.

Platform- NAV2018 on Premise
Visula Studio Code AL Compiler version 0.16.19969

**Comment by StanislawStempin** [comment]
AL 0.16  +  NAV 2018 = Problem:) 
Please try again with AL 0.12.XXX that comes with the product DVD

FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

**Comment by Deepakalle123** [comment]
ok let me check.
