### ISSUE TITLE
[Event Request] Codeunit 5818, Function PostItemJnlLine 

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3227]
Hi,
We need an Event in Codeunit 5818 Undo Service Shipment Line, in function PostItemJnlLine.
![image](https://user-images.githubusercontent.com/41729653/43954711-c6c14c20-9c9d-11e8-94e1-db8e18f03393.png)

With Parameters:
![image](https://user-images.githubusercontent.com/41729653/43954737-dd22cb6a-9c9d-11e8-8c5f-17ecbbda8364.png)

Thanks in Advance

**Comment by thpeder** [comment]
The event already exists, you might be running on an older version.
