### ISSUE TITLE
[Event Request] Table 5902. Function CopyFromitem

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3231]
Hi,

We need an event in Table 5902 Service Line in function CopyFromitem.

![image](https://user-images.githubusercontent.com/41729653/43956860-008c1e50-9ca6-11e8-83c6-4247ead8ad09.png)

With Parameters:
![image](https://user-images.githubusercontent.com/41729653/43956878-1263d410-9ca6-11e8-97ca-886ce7596a41.png)

thanks in advance

**Comment by thpeder** [comment]
The event already exists, it seems like you are running on an older version.

**Comment by LFlamme** [comment]
Hi,
I looked into the newest Version of BC. There i can see the Event, right at the End of the Function.
But it only got 2 Parameters.
![image](https://user-images.githubusercontent.com/41729653/44272823-28253800-a23e-11e8-9b94-13937ad385c6.png)
We need to have parameters added in that case.
VAR xRecL : Record "Service Line";
ServiceHeaderL : Record "Service Header";
CurrfieldNoL : Integer
