### ISSUE TITLE
[Event Request] Codeunit 80, Function DeleteAfterPosting

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3236]
Hi,
We need an event in function DeleteAfterPosting of Codeunit 80 Sales-Post.
![image](https://user-images.githubusercontent.com/41729653/43962971-5acbcc68-9cb9-11e8-8b8b-ceee72758a58.png)

With parameters:
![image](https://user-images.githubusercontent.com/41729653/43962997-703643ee-9cb9-11e8-903e-65f838d081c9.png)

thanks in advance

**Comment by thpeder** [comment]
The event already exists, it seems like you are running on an older version.
