### ISSUE TITLE
Azure authentication for calling from codeunit

### ISSUE THREAD

**Issue by zhaohowie** [Microsoft/AL#3239]
Hi,

I have an Azure function which will be called from a codeunit. I want to authenticate callers. I know Azure supports AAD, windows account, facebook, etc authentication. But, they look like can't be used by codeunit in business central.

Are there any existing solutions in business central or I have to authenticate callers by myself (Like, manually put my own authentication info in the http header)?

Thanks,

**Comment by StanislawStempin** [comment]
For now, you need to hand-craft the authentication headers. A more integrated authentication solutions are on our backlog.
