### ISSUE TITLE
"Reversal Entry".ReverseTransaction not accessible

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#324]
Hello,

we try but fail to call procedure ReverseTransaction in table Reversal Entry from an extension which makes sense as it is not marked as [External]. Any special reason for that or was it maybe just forgotten? And what is the way to request access for those cases? Should it be done here?

Regards,
Tobias

**Comment by StanislawStempin** [comment]
We will look into exposing this function for extension development.
