### ISSUE TITLE
Question Evaluate Formulas

### ISSUE THREAD

**Issue by Hilbekale** [Microsoft/AL#3243]
I have a question, because of the lack of .NET Support (for Cloud). It would be nice, if you can provide an idea to solve this in AL.

I'm looking for a formula expression evaluation:

```EvaluateFormula(Formula : Text[1000]) : Text
CREATE(MSScriptControl);
MSScriptControl.Language('VBScript');
Result := MSScriptControl.Eval(Formula);
CLEAR(MSScriptControl);```

‘Microsoft Script Control 1.0’.ScriptControl (GUID: {0E59F1D2-1FBE-11D0-8FF2-00A0D10038BC})

**Comment by StanislawStempin** [comment]
This would need to be handled similar to other .NET scenarios:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#dotnet-types-are-not-available-in-extensions-v2-what-now

**Comment by Hilbekale** [comment]
Thanks. I will take al lot into this.
