### ISSUE TITLE
Issue reported #2171 still remain as an issue in NAV2018CU8?

### ISSUE THREAD

**Issue by hsiungw** [Microsoft/AL#3248]
Hi,

In codeunit 8800 the function SaveReportRequestPageParameters has the following code that preventing the same report from being run more than once in other language than ENU. This is reported in #2171 but I still see the same code in CU8?

WITH ObjectOptions DO BEGIN
  IF GET(LastUsedTxt,ReportID,"Object Type"::Report,USERID,COMPANYNAME) THEN
    DELETE;
  INIT;
  "Parameter Name" := 'Last used options and filters'; // <-- The problematic code still seen in cu8
  "Object Type" := "Object Type"::Report;
  "Object ID" := ReportID;
  "User Name" := USERID;
  "Company Name" := COMPANYNAME;
  "Created By" := USERID;
  "Option Data".CREATEOUTSTREAM(OutStr);
  OutStr.WRITETEXT(XMLText);
  INSERT;
END;

**Comment by StanislawStempin** [comment]
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
