### ISSUE TITLE
Property SECURITYFILTERING in Visual Studio Code

### ISSUE THREAD

**Issue by malue19** [microsoft/AL#3249]
Hey guys,
I have a problem with the property "SECURITYFILTERING(Filtered)".  I get always an error, when I want to use it...but if I use the property "temporary" instead of "SECURITYFILTERING" there is no error?! 

`LOCAL procedure SetCommonFilters(VAR TheResCostBuf  : Record "Resource Cost Contr. Buffer" SECURITYFILTERING(Filtered))`

**Comment by StanislawStempin** [comment]
This functionality is not implemented yet. I will use this issue for tracking.

**Comment by blrobl** [comment]
Closing this issue, as this functionality can be achieved by using an attribute when defining the variable.

```
    [SecurityFiltering(SecurityFilter::Filtered)]
    Record "Resource Cost Contr. Buffer"
```

or on the body of the method itself:

```
LOCAL procedure SetCommonFilters(VAR TheResCostBuf  : Record "Resource Cost Contr. Buffer")
begin
   TheResCostBuf .ECURITYFILTERING(Filtered)
end;
```
