### ISSUE TITLE
[Question] Delete record from test page

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#3253]
Hello,

I am wondering how I can delete a record from a test page while making test functions.
Obviously I can delete the records from the table but in this specific scenario I want to delete them from a list page. It seems like there is no usable function according to https://docs.microsoft.com/en-us/dynamics-nav/testpage-functions

When I search all the default Test codeunits/functions from the installation DVD I cannot find any usable functions.

What is your guideline to achieve this functionality?

Regards
Joriek

**Comment by esbenk** [comment]
You can't right now. The functionality is on our backlog, but without an ETA.

Your only option is to go straight to the Record, but that wont allow you to test OnDelete() code on the page.
