### ISSUE TITLE
In-app designer: pulled changes badly formatted

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#326]
I like the In-app designer feature that allows me to make changes to a page layout and pull into my .al objects, but I was badly surprised by the formatting of my .al files
I have attached a project called DeactivateCustomer with two subfolders. One with the project before and one with it after pulling in the changes.

I also have another issue that I will report separately: why pull in all the objects? Probably technically easier, but they haven't been changed.

[DeactivateCustomer.zip](https://github.com/Microsoft/AL/files/1112287/DeactivateCustomer.zip)

**Comment by StanislawStempin** [comment]
This is unfortunately a known issue until we implement the auto-formatting support. We will make sure not to reformat sections and files that haven't been touched though.

**Comment by nndobrev** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
