### ISSUE TITLE
Extending the code in standard reports with events

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3264]
Hey guys, I would like to extend some standard reports and I have seen when you want to use the event subscriber that there is the possibility "report" like "page, table...". Would that be a way to extend the code in a report?
Is there also a way to extend the fields in a report?

**Comment by StanislawStempin** [comment]
Yes, you would extend report business logic using event subscribers and requesting additional event publishers if they are missing.
Extending report dataset is not possible yet but we are planning to add that functionality in the near future.
