### ISSUE TITLE
How can I share my BC instance in local net?

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#3265]
I have an instance running in the docker container with an image bcsandbox:latest. How I share/access to my container IP from local computers in my net?

**Comment by StanislawStempin** [comment]
For support related to navcontainerhelper or docker please use **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

**Comment by sssolammm** [comment]
Ok, thanks.
