### ISSUE TITLE
In-app designer: pull only changed object

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#327]
With issue https://github.com/Microsoft/AL/issues/326 I also ran into the fact that all objects are being pulled when using the In-app designer to change the layout of a page. Not only the updated page object.
Probably this is technically easier, but they haven't been changed and I don't want my objects that haven't changed by me to be changed by the system.

**Comment by StanislawStempin** [comment]
This behavior would be actually a bug, it is not intended.
We are not able to reproduce this issue on the latest builds. Could you share the exact steps that lead to this situation?

**Comment by StanislawStempin** [comment]
We have found the root cause and fixed it for August Update. Only the changed objects will be pulled from the server.

**Comment by lvanvugt** [comment]
OK, great. So you were able to reproduce. I just wanted to start to provide report steps. Thanx!
