### ISSUE TITLE
Extra function for List data type

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#3270]
Hello,

Currently the List datatype has the following functions:
List: List of [Text];

![image](https://user-images.githubusercontent.com/6583705/44096578-e386b9da-9fdb-11e8-8e87-a7597ee0d121.png)

Would it be possible to add an extra function which returns a value for the index given in the parameter?
It could be used like this:

var
     List: List of [Text];
     Index: Integer;
begin
     for Index := 1 to 5 do
         List.Add('Hello World ' + Format(Index));
     for Index := 1 to 5 do
         Message('Index %1 contains value %2',Index,List.ValueAtIndex(Index));
end

Preferably if the index doesn't exist it returns an empty string and not an error message.

Currently the only function that can be used for this is the Get function but then we have to use an additional variable to store the value in. This works in almost all cases but the new function would be nice to have.

Thanks in advance,
Joriek

**Comment by thpeder** [comment]
Hi @Joriek,
The `Get` function has an overload where it simply returns the value, but in the case that you specify an index outside the range of the list then it throws an error.
