### ISSUE TITLE
Quickly add Tooltip property to every page field

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#3273]
Hi all, 

is there a quick way, to add the tooltip property for every pagefield over the whole project?
Maybe prefilled with the Caption or fieldname?
Would be an amazing feature for all recurring properties, which you want to set afterwards.

Best regards,

Hendrik

**Comment by thpeder** [comment]
Hi @hendrik244,

Microsoft doesn't provide a tool that can do that, but I'm not sure if there exists some community project that can help you.

**Comment by BartPermentier** [comment]
now it is to late, but you should just use a snippet during development.
"Snippet: Field Page":{
		"description": "Add a field to a page",
		"prefix": "rFieldPage (ALTB)",
		"body": [
			"field(${1:FieldName})",
				"{",
					"\tApplicationArea = All;",
					"\tToolTip = 'ToolTip: ${2:FieldName}';",
				"}",
			"$0"
			]
	},
