### ISSUE TITLE
Json Object assignment reference the same variable 

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#3275]
I have a global Json Object with some values I want to reuse so I assign this to a local Json Object and add more values, however the local variable reference the global variable and the new values are also added to the global variable.

    _trigger OnRun()
    begin
        GlobalJsonObject.Add('Title','Test');  
        BuildJsonObject('This is a test.');
        GlobalJsonObject.WriteTo(JsonContent);
        Message(JsonContent);    
        //{"Title":"Test","Body":"This is a test."}
    end;
    
    var 
        GlobalJsonObject: JsonObject;
        JsonContent: Text;

    procedure BuildJsonObject(Body:Text)
    var
        JObject: JsonObject;
    begin
        JObject := GlobalJsonObject;
        JObject.Add('Body',Body);
    end;_

**Comment by thpeder** [comment]
Hi @Joel-NAVDev,

If you want the local variable to be a copy of the global variable then you can make a clone of it: [JsonToken.Clone()](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/api/jsontoken-clone-method)

**Comment by Joel-NAVDev** [comment]
Thanks @thpeder, I can confirm JObject :=  GlobalJsonObject.Clone().AsObject() works as expected in the above example.
