### ISSUE TITLE
Blob.Length not recognised

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#3277]
I get the below error message on the latest microsoft/dynamics-nav image
_'Blob' does not contain a definition for 'Length'_

Headers.Add('Content-Length', Format(TempBlob.Blob.Length()));

**Comment by StanislawStempin** [comment]
Do you get this as a compiler error or when running the code?  Could you provide a more complete sample, is TempBlob a variable of type Record TempBlob in your case?

**Comment by Joel-NAVDev** [comment]
Must have been resolved, I cannot seem to replicate this in the latest image.
