### ISSUE TITLE
Deposit pages and reports missing from web client

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#3278]
Deposit pages and reports are available in Windows Client, bur are missing from web client. I'm using image version: 

````
bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca
````

**Windows Client:**
![image](https://user-images.githubusercontent.com/20359384/44145071-688eb354-a08a-11e8-9c35-fbb50b56a611.png)

**Web Client:**
![image](https://user-images.githubusercontent.com/20359384/44145050-5979b742-a08a-11e8-8729-9ffc8fe857ce.png)

I tried to add UsageCategory and Application Area from c/side for Pages but that also didn't fix the issue.

**Comment by StanislawStempin** [comment]
We were missing the updated UsageCategory property in the NA version of the codebase. This has been fixed since, could you please check on the latest docker image.
