### ISSUE TITLE
Get NAV Version, Localisation, Tenant Name in AL

### ISSUE THREAD

**Issue by chrismonck** [Microsoft/AL#3279]
Hi,

i'm trying to capture this information as part of the assisted setup. this information is going to be pushed via Azure function for our marketing team along with other information so we know who, what and when our app has been installed. I can capture most of what i want except this information; NAV version (i suppose not that import on BC), Localisation and tenant (this is just useful information not strictly needed).

in older version there was a dotnet control that allowed me to capture this? is there an alternative in AL?

(I know people might frown on me capturing this information, i might end up scrapping this approach but currently I'm looking for it).   

thanks
Chris

**Comment by StanislawStempin** [comment]
Please have a look at codeunit 417. Localization will be found in ApplicationFamily,  tenant is under AadTenantId (we will be adding AadTenantDomainName for Fall release) and PlatformVersion to get the verison of BC.
