### ISSUE TITLE
External Function Request

### ISSUE THREAD

**Issue by MattTraxinger** [Microsoft/AL#3282]
I didn't see any requests for the following and was hoping that they could be made external.

Codeunit 900 Assembly-Post
   UndoFinalizePostATO
   UndoPostATO

Codeunit 408 Dimension Management
   GlobalDimObjectNoList

Codeunit 22 Item Jnl.-Post Line
   Reapply

Codeunit 1001 Job-Post Line
   PostSalesGLAccounts

Codeunit 43 LanguageManagement
   SetGlobalLanguageByCode
   RestoreGlobalLanguage

Codeunit 1630 Office Management
   CheckForExistingInvoice

Page 1870 Credit Limit Notification
   InitializeFromNotificationVar

[Edit - Apologies, missed these two in the original post]
Table 27 Item
  TryGetItemNoNoOpenCard
  GetItemNo

Additionally for the following I saw requests that they had been shipped, but I am still receiving errors about them not being available with bcsandbox:12.3.23590.23730-us . Are these just not available until October?

Codeunit 408 Dimension Management
   DefaultDimObjectNoList [2079](https://github.com/Microsoft/AL/issues/2079)

Codeunit 22 Item Jnl.-Post Line
   RedoApplications [2604](https://github.com/Microsoft/AL/issues/2604)

Thank you for your help.

**Comment by JesperSchulz** [comment]
I've exposed all requested functions. They will all be made available in October :-)

**Comment by MattTraxinger** [comment]
Thank you so much for the quick turnaround. We will look forward to the October release.
