### ISSUE TITLE
Suggestion: Usability Improvement - Add the object ID to tooltip for extended objects / focus on object definition

### ISSUE THREAD

**Issue by megel** [microsoft/AL#3284]
A small improvement for the Usability of AL in VS Code.
Until IDs exist, please add the ID of the original object to the tooltip.

![image](https://user-images.githubusercontent.com/15800069/44192005-0046af00-a12e-11e8-84d6-a3c965fa97ad.png)

The Tooltip should look like:
```code
Page "Service Item Card" 5980
```

Because, when you are Looking for the ID - you have to search in the extended object:
![image](https://user-images.githubusercontent.com/15800069/44192157-a5618780-a12e-11e8-82b9-1b91ee833c62.png)
![image](https://user-images.githubusercontent.com/15800069/44192174-bad6b180-a12e-11e8-9944-72861ce6a6cd.png)

An alternative could be, to focus on the obejct definitin when you use `CTRL+ Left Mouse Click`.

**Comment by pborring** [comment]
CTRL + hover over object name will enable code peek and show object ID
![image](https://user-images.githubusercontent.com/28434210/75165711-13730b80-5723-11ea-8d75-a0b870396a6e.png)
