### ISSUE TITLE
Inconsistent behavior of adding groups/fields to the FactBoxes

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#3289]
There is an inconsistent behavior of adding content to factboxes. Unfortunately, the compiler don't show any errors or warnings, when you add **groups** or **fields** in an extensionpage to a `Factbox`.

```JavaScript
pageextension 50100 MyExtension extends "Service Item Card"
{
    layout
    {
        // This content is possible, but not shown
        addfirst(FactBoxes)
        {
            group(MyGroup)
            {
                Caption = 'Direct Added Content';
                field(myContent; myContent)
                {
                    ApplicationArea = All;
                    Caption = 'My Simple Content';
                }
            }
        }

        // If the content is wrapped in a CardPart, then it will be shown
        addfirst(FactBoxes)
        {
            part(MyFactboxContent; MyFactboxContent) { ApplicationArea = All; }
        }
    }
    var
        myContent: Text;

    trigger OnOpenPage()
    begin
        myContent := 'Show some information';
    end;
}
```

![image](https://user-images.githubusercontent.com/15800069/44198300-4eb17900-a141-11e8-8a7a-17b0b0f39617.png)

I would expect to get a warning from compiler, if I add groups/fields to a Factbox instead of pageparts.

**Solution:**
You have to wrap this additional fields / content in a seperate `page` (`PageType = CardPart;`)

**Version(s):**
![image](https://user-images.githubusercontent.com/15800069/44198992-33476d80-a143-11e8-94d2-b64808e7a575.png)
Microsoft (R) AL Compiler version 0.17.30289
Copyright (C) Microsoft Corporation. All rights reserved

**Sample Project:**
[Microsoft_AL_[Add_Fields_to_Factbox].zip](https://github.com/Microsoft/AL/files/2293048/Microsoft_AL_.Add_Fields_to_Factbox.zip)

**Comment by StanislawStempin** [comment]
We have discovered a larger gap between validations performed on page extensions as compared to base pages. We will be addressing it more comprehensively in the future and therefore closing this particular issue.
