### ISSUE TITLE
Dependencies doesn't work (March update)

### ISSUE THREAD

**Issue by ArkhaLime** [Microsoft/AL#329]
I have a new project with a dependency on another project I made. But when compiling, I get a error message like ```error AL0265: Reference to object Customer Card is ambiguous. Make sure you are not referencing packages containing objects with the same names```. The dependency only add a new code unit.
Before that VSCode couldn't download the dependency from the NAV instance.  
I haven't yet tested with the june update.
(Sorry for bad english)

**Comment by waldo1001** [comment]
Did you place the navx of the extension it depends on into the package folder manually? 
I have tested dependent extension in both versions - and both worked fine.. .

**Comment by ArkhaLime** [comment]
Yes, I placed it manually because VSCode couldn't download it from the server.

**Comment by StanislawStempin** [comment]
Could you please move to June Update. We do not support previous preview releases.
