### ISSUE TITLE
how to make changes in base code?

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#3291]
what if i have to write code on the specific first line of sales header's field's on validate trigger?

<img width="1008" alt="screenshot 25" src="https://user-images.githubusercontent.com/28805630/44202524-dca15a00-a169-11e8-898f-3cec5237876c.png">

**Comment by pmohanakrishna** [comment]
you have to use OnBeforeValidate event
https://docs.microsoft.com/en-us/dynamics-nav/introducing-events

**Comment by StanislawStempin** [comment]
Please read about event recorder here:
https://blogs.msdn.microsoft.com/nav/2018/07/30/developer-preview-july-2018-update/

And about browsing into Base Application code from AL here (section Debugger Enhancements):
https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/
