### ISSUE TITLE
EventSubscriber

### ISSUE THREAD

**Issue by Kraver88** [Microsoft/AL#33]
Hey,

IntelliSense does not suggest anything usefull when completing the EventSubscriber Syntax.

I'd like some more information on how to form the [EventSubscriber] syntax.
We get [EventSubscriber(ObjectType::ObjectType, ObjectId, OnSomeEvent, ElementName, SkipOnMissingLicense, SkipOnMissingPermission)].
However, I've tried everything for the OnSomeEvent parameter but none seem to work. Also not sure what ElementName should refer to.

My code: 
[EventSubscriber(ObjectType::Table, 18,OnAfterInsertEvent,'',TRUE,TRUE)]
OR
[EventSubscriber(ObjectType::Table, 18,OnAfterInsertEvent(VAR Rec : Record Customer; RunTrigger : Boolean),'',TRUE,TRUE)]

**Comment by StanislawStempin** [comment]
We are actively working on implementing InelliSense for this scenario.

In the meanwhile the syntax to use in this case is:
[EventSubscriber(ObjectType::Table, 18, 'OnAfterInsertEvent', '', true, true)]

Element name is either blank in case of events defined on the objects itself or a field/action name in case of events defined on these elements
