### ISSUE TITLE
Add elapse feature to VSCode to give overview of all functions that exists in a .al file

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#331]
When creating multiple functions in an AL file there is no overview yet available in VSCode to shows me in one glance what functions do reside in an AL file.
Taking the example of COD70000600 in the TowersOfHanoi AL example VSCode shows me now:

![vscode towersofhanoi - collapse](https://user-images.githubusercontent.com/18466198/27769913-654d71e0-5f35-11e7-846a-110d1a29f62f.PNG)

The only way to find out what function the file SolveTowersOfHanoi.al contains is to browse through the file and find out.
It would be great is VSCode would show this like Visual Studio already does like it the following example:

![vs - elapse cs file](https://user-images.githubusercontent.com/18466198/27769955-6bcc7466-5f36-11e7-96d6-2cd4eca554d3.JPG)
The following mockup visualizes it somewhat:

![vscode towersofhanoi - elapse](https://user-images.githubusercontent.com/18466198/27769986-269c5310-5f37-11e7-9f94-e8e5faf07a7d.PNG)

Maybe the use of icons in front of the function (like in VS) would make it even better.

### Justification
This would make a developers productivity much higher.

**Comment by StanislawStempin** [comment]
VS Code implements this functionality in a slightly different way:
https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol
Try it through Go -> Go To Symbol in File ...  or keyboard shortcut Ctrl + Shift + O

If you type ":" as the first character in the prompt the symbols will be grouped by type

**Comment by lvanvugt** [comment]
Hi Stanislaw,

Thanx, but it is somewhat cumbersome as you do not have overview over multiple files and the developer needs to type this every time again. Somewhat counter productive IMHO.

Or is there another trick to achieve that?

**Comment by waldo1001** [comment]
Hi Luc,

did you try an extension?  I just searched and found this:
![image](https://user-images.githubusercontent.com/12088142/27789297-4f7aaed4-5fec-11e7-9035-5e36f98ae4ee.png)

simply press "Shift+Windows+A" and you have this kind of thing:
![image](https://user-images.githubusercontent.com/12088142/27789339-819f37cc-5fec-11e7-9c7a-36ed57253eaf.png)

in a "window on the side" - and you can click and navigate to the symbol .. .

**Comment by lvanvugt** [comment]
Thanx, Eric. Installed and going to use and see. First question: any idea what the "categories"  Arr, Pro, Cla, Int etc. are meaning? Looking at https://marketplace.visualstudio.com/items?itemName=igbenic.symbolstreeview I did not get any info.

**Comment by waldo1001** [comment]
Well - I know it doesn't make sense .. but ..:
Arr = Array
Cla = Class
Pro = Property

You can find out when you look at the extension-details in VSCode.. .

don't know why it makes these mappings..
