### ISSUE TITLE
EmailItem.Init() call is ambiguous

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#3312]
Init function on Record "Email Item" (TAB9500) cannot be called.
The call is ambiguous between the following methods or properties: 'Init()' and 'Init()'

**Comment by rishiaurrishabh** [comment]
That's because Table "Email Item" has a Function in table with name Init :)

![image](https://user-images.githubusercontent.com/39942971/44310223-492d8a80-a3f0-11e8-9005-8e369515cb43.png)

**Comment by atoader** [comment]
Hi! We are aware of the issue. I have created a bug for the application teams to rename that method.

**Comment by atoader** [comment]
Hi! We have renamed this. You will need to call Initialize() to get the same effect.
