### ISSUE TITLE
Make reference count a hyperlink to allow easy access to referencing code

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#332]
It's great to have the reference count shows above functions and variable in AL.  But it would be super if this reference count, like in Visual Studio, would be a hyperlink that allows to easily access the referencing code.

### Justification
This would make a developers productivity much higher.

**Comment by StanislawStempin** [comment]
This is also something that we are planning to implement at some point in the future.

**Comment by StanislawStempin** [comment]
For now you can use Shift + F12 to view the actual references. It will be the same UI that the hyperlink points to.

**Comment by lvanvugt** [comment]
Hi Stanislaw,

Well, I hadn't used ALT+F12 sofar, but at the moment it is only showing the referenced object itself, so that does not show me the referencing statements.

**Comment by StanislawStempin** [comment]
Alt + F12 is a shortcut for "Peek Definition". Shift + F12 is "Find References"

**Comment by lvanvugt** [comment]
Ouch, bad reading ... Thanx!

**Comment by thpeder** [comment]
Hi, 
The idea seems to be captured in Ideas, so I'm closing this issue.
https://experience.dynamics.com/ideas/idea/?ideaid=ef198658-bf39-ed11-97b1-0003ff45a617
