### ISSUE TITLE
Make reference count also work on trigger that have AL methods related

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#333]
It's great to have these reference count headers for variables and user defined functions. And ... it would be super when this also becomes available for those triggers that have AL methods related to them, like:

- OnInsert, OnModifiy, OnRename and OnDelete for tables
- OnValidate for table fields

### Justification
This would make a developers productivity much higher.

**Comment by StanislawStempin** [comment]
That's a good idea, we will add it to the backlog.

**Comment by fvet** [comment]
An idea has been created to gather votes.
https://experience.dynamics.com/ideas/idea/?ideaid=56458708-fb7f-eb11-8ced-0003ff45d48e

**Comment by atoader** [comment]
Thanks! Let's focus input and discussion in the BC Idea.
