### ISSUE TITLE
[Question] How to add more group into native page.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#334]
Hi!

**Please give me a syntax to add new group into a native page.**
If it isn't supported now, please let me know.

Example: I need to add more some fields into Table 79 Company Information. I need show these fields to Page "Company Information" with new group "Information For Reports".
**So how to do it.**

pageextension 70000000 CompanyInformExt extends "Company Information"
{
CaptionML=ENU='Company Information Extension';  
  layout
  {     
    addbefore("System Indicator")
    {
      group(ReportInfor)
      {
        CaptionML=ENU='Report Information';
        field("Name (VN)";"Name (VN)")
        {
        }
        field("Address (VN)";"Address (VN)")
        {
        }
        field("Address 2 (VN)";"Address 2 (VN)")
        {
        }
      }//End group
    }    
  }
}

I build, publish and install OK. But when I open "Company Information" page, The Window Client show error and close App.
**The server "DynamicsNAV100" was unable to process the request. The application will close.**

**Comment by waldo1001** [comment]
Hope this helps:
![image](https://user-images.githubusercontent.com/12088142/27789800-197336f6-5fee-11e7-9c24-7f1d0b32d718.png)

Result:
![image](https://user-images.githubusercontent.com/12088142/27789789-1133f598-5fee-11e7-939d-3e0f601bc6c3.png)

**Comment by hgnamvn** [comment]
Thank Waldo!

I tested your example. It run OK.
But when I uninstall, Unpublish the package, I extend TAB Company Information by adding more some fields. Then, I build, install package again, but i get some errors. (sometime I get error 500 or unable install extension, or syn. ). I testing my case. I will notify the result later.

**Comment by hgnamvn** [comment]
Hi Waldo!
This is step step by step I get the first error:

1. I create a new package with your example. I build, publish, and install extension OK. I run page Company Information OK.
2. I uninstall, unpublish that extension.
3. Back Visual Studio tool. I create new **al** file to add more field ("Name VN") into TAB 79 Company Information.
   Modify Pageextension to replace "Home Page" field by my new field "Name VN".
4. I build, publish, install the package again. But I get the error:
![image](https://user-images.githubusercontent.com/24407031/27815057-80e554c8-60ab-11e7-92d7-258e8e1e19cc.png)

**Comment by hgnamvn** [comment]
Hi Waldo,

I create another case. I only add  more 1 field into Tabe 79 Company Information. I also can't install extension.

![image](https://user-images.githubusercontent.com/24407031/27815279-10afe0f4-60ad-11e7-99c7-0788be7533d6.png)

**Comment by waldo1001** [comment]
First - you don't need to uninstall yourself - VSCode will replace the extension.  Just press F5 to see the updated result.

Second - what can I say - I can't repro your scenario:
![image](https://user-images.githubusercontent.com/12088142/27830594-688152bc-60c7-11e7-9dfb-d511acb984b2.png)

So I guess it need to be something with your environment.  May be you can try to rebuild it?  Like:
http://www.waldo.be/2017/07/04/nav-developer-preview-fix-script/

**Comment by hgnamvn** [comment]
Thank Waldo,

I reinstall my environment on local server. My Case is OK now.
