### ISSUE TITLE
Object Designer - Page Extension?

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#335]
Doing some testing on the TXT2AL conversion and noticed that in C/Side PageExtension is added as an object type.

What is the reason for this change?

![object pageextension](https://user-images.githubusercontent.com/7205122/27785504-206b7316-5fde-11e7-8b1e-c3a6efbcd124.png)

**Comment by StanislawStempin** [comment]
This is a side effect of adding PageExtension type to C/SIDE for Export purposes. We will leave it like this unless we find that there are some serious issues with it.

**Comment by markbrummel** [comment]
Thanks, but I am not 100% sure if I understand your answer.

Are you saying we can export Page Extensions from C/Side? How would that work?

**Comment by StanislawStempin** [comment]
Sorry, I rushed my first answer. The PageExtension type was actually added much earlier, in December, to support debugging Page Extensions with the current debugger. (https://github.com/Microsoft/AL/issues/58)
There is no other functionality available in C/SIDE related to page extensions.

**Comment by markbrummel** [comment]
Got it. Thanks.
