### ISSUE TITLE
Reference to object Assert is ambiguous. Make sure you are not referencing packages containing objects with the same names.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#3368]
Created new container with master build (13.0.23947) with New-NavContainer command and with includeTestToolkit

when trying to build package, getting below errors

it was working before in previous builds.

![image](https://user-images.githubusercontent.com/23735402/44270494-5104f780-a255-11e8-81b3-0d5a5c110f88.png)

![image](https://user-images.githubusercontent.com/23735402/44270558-78f45b00-a255-11e8-854d-7cc108850036.png)

**Comment by KaiSwitalla** [comment]
you are Right,
i have the same Problem with build (latest bc) 13.0.23802.0.

Example
![referenceobjects](https://user-images.githubusercontent.com/26924867/44323116-04314480-a440-11e8-9c78-90dc4114a70c.jpg)
![referenceobjects_appjason](https://user-images.githubusercontent.com/26924867/44323119-072c3500-a440-11e8-9928-84822dab3dff.jpg)

**Comment by StanislawStempin** [comment]
If you use includeTestToolkit command then you shouldn't use Test symbols (test setting in app.json) as these will result in duplicate symbols.
