### ISSUE TITLE
Global vars on about each snippet

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#337]
Hi,

I noticed there is a section of global variables with one global var on each snippet.  I understand that it's not very "clear" on where to put global vars in the syntax .. but in terms of a general development rule: "keep all as local as possible", this is not very convenient.  Now, about all snippets that people use, we need to remove these global vars all the time.. .

I would suggest to remove them from the snippets.. .

because .. keep in mind: 
![image](https://user-images.githubusercontent.com/12088142/27789036-25cd94d0-5feb-11e7-9634-fc5bff0bc858.png)

**Comment by markbrummel** [comment]
I agree. Please remove them.

**Comment by StanislawStempin** [comment]
I completely agree with you. Keeping the global vars in the snippets for now is a tradeoff between teaching the new AL syntax and promoting good practices. 
We will most likely remove it in 2-3 months once the community is more familiar with the new syntax.
