### ISSUE TITLE
Code Analyzers and AppSource Validation

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#3370]
We are currently developing a number of apps for AppSource. The development team wants to specifically know which rules in the code analyzers will result in a failure of the code verification.

The rules in the AppSourceCop  are straightforward to follow, no problem.

The rules in the CodeCop are a different matter: Most warnings we get are easy to fix - but does a failure to comply also mean we will fail verification? 

- As an example: Rule AA0139 (Possible overflow assigning '{0}' to '{1}'.) cannot always be resolved. For example: assign a Text Constant to some field, the warning cannot be circumvented.

- Another example: Rules regarding parantheses -> easy enough to follow but silly. If we decide to ignore this, do we fail verification?

**Comment by BartPermentier** [comment]
You can circumvemt AA0139 by using a copystr with the length of the field. You should also add the maximum length parameter to the label:
![image](https://user-images.githubusercontent.com/24684493/44331523-f1336a00-a469-11e8-80d9-36752c2931d9.png)

But anyway still a valid question which warnings would fail verification. I've got a colleague who absolutely hates the then-begin rule and we are wondering if that one is really necessary.

**Comment by StanislawStempin** [comment]
Only the failures from AppSourceCop count towards App Source validation. The CodeCop and UICop are for your own usage to make sure that code follows the same best practices that Microsoft is using internally.
