### ISSUE TITLE
IIF as function

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/AL#3371]
It would be of great help to have a function available which takes in three parameters (bool;variant;variant) and returns the first variant value when bool parameter is true, else return false.

This would make a lot of code a way shorter.

Alternatively it would be nice to have the construct

bool ? variant1 : variant2;

available (like in c#).

**Comment by mrabus** [comment]
Nice idea to simplify some statements!

**Comment by EmilDamsbo** [comment]
This belongs at aka.ms/bcideas. This is currently tracked by at least one idea over there: https://experience.dynamics.com/ideas/idea/?ideaid=d62c7a8d-7f56-ec11-a3ee-0003ff45ac6d
