### ISSUE TITLE
Button To Edit List Pages in BC

### ISSUE THREAD

**Issue by Anna-Gudimova** [Microsoft/AL#3373]
Hello Everyone,
When I get to some list pages through search in Dynamics Business Central I don't see an option to Edit /Manage the page:
![image](https://user-images.githubusercontent.com/10453174/44294063-9c63d980-a246-11e8-8c00-ad4d19abec96.png)

If I refresh/reload this page the option appears:
![image](https://user-images.githubusercontent.com/10453174/44294092-dfbe4800-a246-11e8-8c7f-f809219dc6ae.png)
Is it a bug of some sort or a matter of incorrect settings? Can this be fixed?
Thanks

**Comment by pmohanakrishna** [comment]
Did you try clicking on Home tab which opens actions tab? in your first screenshot.

**Comment by Anna-Gudimova** [comment]
Got it. Indeed actions are hiding under the Home tab. Thank you
