### ISSUE TITLE
Duration with Init Value = Bug

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#3376]
I would like to file a bug. While working on the AL programming book I noticed that it is no longer possible to have an Init Value for a Duration field.

This was possible in C/Side and has been part of our programming book since Navision 5.0.

Can this be fixed please?

![image](https://user-images.githubusercontent.com/7205122/44307830-c681dc80-a3a9-11e8-8507-3a452349b747.png)

**Comment by JohanStenberg100** [comment]
Hi @markbrummel, thanks for reporting this issue. We discussed this internally and we will treat this as an enhancement. 

Primarily we want to be able to offer a similar experience as C/SIDE with a markup not only letting you enter numeric values but more sophisticated entries. Please let me know if you have any questions.

**Comment by blrobl** [comment]
Hi, thank you for your suggestion! We are not prioritizing this for the immediate future, but we recommend you submit this at aka.ms/BCIdeas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
