### ISSUE TITLE
Ambiguous Compile Message - BUG

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#3377]
The pre-compiler gives an ambiguous message

![image](https://user-images.githubusercontent.com/7205122/44308007-79076e80-a3ad-11e8-8169-3688913e7fa3.png)

**Comment by thpeder** [comment]
Hi @markbrummel,

The correct syntax for this case is:
```
{ OptionMembers = "Vendor", "Customer" }
or just
{ OptionMembers = Vendor, Customer }
```

Is you question related to the fact that the message says option **values** but the property writes option **members**?

**Comment by markbrummel** [comment]
I know the correct syntax.

Yes, it says Values instead of Members.

**Comment by AndreyKorepanov** [comment]
Thank you for reporting the issue.
