### ISSUE TITLE
Problem calling reports using task queues / scheduling

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#3378]
We have a customer here for whom we wrote an extension. Within these, we offer the user the option of calling up a report dynamically. He or she can save the settings separately because the report is usually executed at night.

However, we have identified a few problems that we do not see ourselves in a position to solve. This affects the execution sequence. If the customer executes a report from us, and we still have logic for initializing the request page in our report, then the planning settings are overwritten again. This is very unpleasant, because of course the result does not work. We have found a solution to this problem in our own reports. We have to ask within the RequestPage if we can use them. We can do this, for example, with the function "UseRequestPage". So we only have to execute the entire code if this option is "True".

So far so good. So we can intervene in our own reports. However, since we also use standard reports and cannot adapt them here, the archiving settings for these reports are repeatedly overwritten by the logic on the RequestPage, for example, and we cannot prevent it. The same applies to other settings that are overwritten by the program. Our customer is very angry here, because not all of his settings are applied, and the result is sometimes really different.

So I'm going to put my client's question here. When calling up a report via the task queue, would it not be possible to ensure that the request page logic does not overwrite the existing settings? In principle, one would only have to change the logic of the execution. First accept the options of the standard request page and then overwrite the desired parameters. So far, things have been going exactly the opposite way. In the on-premise world you have at least still the chance to intervene here, but that ends in the cloud world at the latest, because you don't get to the code positions here. So there must be some solution from Microsoft.

**Comment by fvet** [comment]
Maybe not entirely linked to this issue, but can we imagine having 'date filters' like 'TODAY' in the request page options for job queue entries, just the way we have when saving page filters as views?

If I save a page with a date filter value 'TODAY' as a view, the date filter value is calculated each time the view is called, so the date filter is automatically updated each day. The same behavior on the request page options for job queue reports would be appreciated too. (Storing 'TODAY' as a filter value instead of the fix date)

**Comment by StanislawStempin** [comment]
In that case you would need to request a change to the specific reports as it sounds they were coded incorrectly. Please try the ALAppExtensions repository.

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
You're not serious, are you? That applies to almost all reports. Why can't you extend the whole system and introduce additional control parameters when calling CURREPORT.SAVEAS? That concerns nevertheless also reports from other Extensions and so on. There are thousands of objects. This does not solve the original problem. Why one cannot make here at the system any change so that these problems do not occur any more. I think that all sounds somehow like a pretended answer, without going into the actual topic.

I would have liked Microsoft to give me a lot more self-reflection, and to admit that the user might want to pretend this option is the way it works. Adjusting all standard documents doesn't solve the problem, it just shifts it. And since there are additional reports in the system for each country version, this would have to happen everywhere.

**Comment by StanislawStempin** [comment]
Thank you for the additional details, in was not clear from previous posts that this is the behavior on all reports. We will investigate what we can do on the platform side.

**Comment by StanislawStempin** [comment]
Could you please provide sample AL code that works incorrectly? 

Using the following code I could invoke the request page separately from running the report and the selected values were not overriden.

```
page 50100 RunReportOffline
{
    trigger OnOpenPage()
    var
        customerReport: report "Customer - List";
        parameters: text;
        outstr: OutStream;
        savedReportFile: file;
    begin
        savedReportFile.Create('c:\temp\file.xml', TextEncoding::UTF8);
        savedReportFile.CreateOutStream(outstr);
        parameters := customerReport.RunRequestPage();
        Clear(customerReport);
        customerReport.SaveAs(parameters, ReportFormat::Xml, outstr);
        savedReportFile.Close();
    end;
}
```

**Comment by StanislawStempin** [comment]
Closing due to no input. Please reopen or log a new issue with the AL code that demonstrates the issue.
