### ISSUE TITLE
Microsoft.Dynamics.Nav.Model.IO.Txt.TxtImportException: Begin expected.

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#338]
For some reason this text export has a ; where the begin should be.

![beginexpected](https://user-images.githubusercontent.com/7205122/27789142-aa4a10d0-5feb-11e7-9097-63388f1496e1.png)
![2017-07-03_12-31-07](https://user-images.githubusercontent.com/7205122/27789151-b004fc56-5feb-11e7-812b-5f33010ba1ad.png)
[BeginExpected.zip](https://github.com/Microsoft/AL/files/1119202/BeginExpected.zip)

**Comment by waldo1001** [comment]
Here's your problem:
![image](https://user-images.githubusercontent.com/12088142/27791114-c6641d58-5ff3-11e7-94c6-cf244f0a2568.png)

I come across this during merges as well - the model.tools have problems with this as well.

**Comment by markbrummel** [comment]
Thanks. ;-)
