### ISSUE TITLE
API in AL language

### ISSUE THREAD

**Issue by hollydonut** [Microsoft/AL#3384]
hi all,

i am trying to create a custom api using AL.
below i my code.
but i got error when "start without debuging" my object, the errors are  

> The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed
page%2050102%20-%20API%20AIR%20Airplane%20Type.al(6,5): error AL0124: The property 'APIGroup' cannot be used in this context
page%2050102%20-%20API%20AIR%20Airplane%20Type.al(7,5): error AL0124: The property 'APIPublisher' cannot be used in this context

have anyone face the same issue? and any suggestion how to resolve this?

```
page 50102 "API AIR Airplane Type"
{
    
    EntityName = 'AIRAirplaneType';
    EntitySetName = 'AIRAirplaneTypes';
    APIGroup = 'localhost';
    APIPublisher = 'localhost';
    PageType = API;
    SourceTable = "AIR Airplane Type";
    
    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("ICAO Code"; "ICAO Code")
                {
                    
                }
                field("Description"; "Description")
                {
                    
                }
                field("Popularity"; "Popularity")
                {
                    
                }
                field("Id"; "Id")
                {
                    
                }
            }
        }
    }
    
    actions
    {

    }
}
```

**Comment by hollydonut** [comment]
currently i am using docker, and i pull microsoft/dynamics-nav:2018,
my docker version is as followed

> PS C:\Windows\system32> docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by StanislawStempin** [comment]
NAV2018 doesn't support that feature. You would need to use Business Central Spring or Fall 2018
