### ISSUE TITLE
Microsoft.Dynamics.Nav.Model.IO.Txt.TxtImportException: String expected.

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#339]
Very, very old report converted from classic to RDLC. Boat anchor, not in use anymore.

![2017-07-03_12-50-12](https://user-images.githubusercontent.com/7205122/27789822-32d72882-5fee-11e7-8fed-4df066944671.png)
[StringExpected.zip](https://github.com/Microsoft/AL/files/1119239/StringExpected.zip)

**Comment by DominikDitoIvosevic** [comment]
I think the problem is that there is a multi line text const in the file.
After I remove it it works

```
GBK_NummerCaptionLbl@1109943792 : TextConst 'NLD=GBK Nummer;LTH=DidØiosios knygos

    ';
```

**Comment by DominikDitoIvosevic** [comment]
@markbrummel Are you still experiencing problems from this issue? This seems to be a result of the ability to paste anything (in this case text with /r/n) into the textbox in CSIDE so you accidentally added a newline even though you shouldn't have.
Is there any need to support this?

**Comment by markbrummel** [comment]
I have not tested this in a long time. I'll look into the project after all the events are over. Too busy right now with other stuff.

**Comment by DominikDitoIvosevic** [comment]
this has been fixed
