### ISSUE TITLE
Removing/adding variables via In-client page designer

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#340]
On the 'Cash Receipt Journal' (page 255) I wanted to remove the 'Account Name' and 'Bal. Account Name' field from the footer group and see if I could include them as columns (per line) instead. During the design (using the in-client page designer), I've removed the fields (~ variables) from the footer group, but afterwards I was no longer able to restore / add the deleted fields (variables: AccName, BalAccName) again.

![image](https://user-images.githubusercontent.com/25268332/27803730-4886a17a-602b-11e7-8536-d10ee6efb819.png)

**Comment by fvet** [comment]
A similar issue appears on the 'Sales Invoice Subform' when working with the Shortcut Dimension columns. Columns based on variables seem not to appear in the list of fields (I'm looking for 'Shortcut Dimension 7' that I first removed and tried to add again). Neither on the 'Dimension Name' , nor on the 'Shortcut Dimension' value.

![image](https://user-images.githubusercontent.com/25268332/27803988-c34ee344-602c-11e7-906d-104d1225e599.png)

**Comment by StanislawStempin** [comment]
We will look into it.
