### ISSUE TITLE
Problem System Extensions Import NavData File to New DB

### ISSUE THREAD

**Issue by abenbetka** [Microsoft/AL#3409]
Hello All;

I'm creating a New DB and trying to Import a NavData File to it from a DB containing Published Extensions.
Before importing the File, the below steps have been made :

1. Database creation from scratch;
2. Importing FOB from the Source DB & Synch Shema with Validation [Later];
3. Creating Company;
4. Synch Schema with Force from PoweShell;
5. DB & Company Access OK;
6. Publishing Application, Test & System Extensions;
7. Generating Symbol References;

When I try to Import the NavData File, I get the Error in the message below :

![image](https://user-images.githubusercontent.com/42576877/44404337-aaef1100-a524-11e8-8235-d43e4af5b9a6.png)

Thanks in advance.

**Comment by rishiaurrishabh** [comment]
It is happening because you are trying to import a Datafile which has references from above mentioned extension. you can install these extensions using by installing the app files in the NAV setup folder(Path : <NAV Setup folder path>/Extension).
So first you have to install those extensions then you can import your NAV Data file.

**Comment by abenbetka** [comment]
Hi Rishabh & thank you for your answer;
I've made a Publishing for Symbols Only to that DB for the Application, Test & System Extensions (the APP Files found under ModernDev Folder of NAV DVD).
I did that kind of Publishing because in Standard Cronus these 3 Extensions are not visible in [Extension Management] so I assumed they need to be Published as Symbols Only.
Could you please confirm that what I need to do is Publish/Install, Not only Symbol Publishing ?

**Comment by StanislawStempin** [comment]
Have you installed the exact same versions of the extensions as on the database from which the Nav data file was created? The App, Test & System can be published as symbols only but for example Image Analysis shown in your error message must be published as a full app.

**Comment by abenbetka** [comment]
Hi every one;
I ended up avoiding the import from a datafile and making the actions for installing System symbols, extensions and creating the common data.
Thank you all for your support.
