### ISSUE TITLE
Request for new events in the NAV standard.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#341]
Unfortunately, there are currently very few events in the NAV standard. However, these are absolutely necessary in the posting processes. But in most important places they are still missing. There was once the statement that one can propose events, so that these are included in the standard. How is the future going? Unfortunately, we can not convert some of our modules as an extension, since in Codeunit 21, For example, an "ContinuePosting" event is missing. In addition, it is very difficult to pick up the posting preview by event. I ask times for a statement, how the whole is designed, so that you can convert relatively simple existing modules in the future.

**Comment by StanislawStempin** [comment]
Currently we don't have a public process for suggesting these. We are working on a new approach and will announce it in the coming weeks.
