### ISSUE TITLE
[Event Request] Table 4 - OnBeforeGetGainLossAccount

### ISSUE THREAD

**Issue by brankoradovic** [Microsoft/AL#3410]
Hi,

Please add new event **OnBeforeGetGainLossAccount** in function **GetGainLossAccount** of Table 4 - Currency.

![image](https://user-images.githubusercontent.com/40798600/44406729-a3e3f500-a55c-11e8-8987-4f1e742038be.png)

**With parameters:**
![image](https://user-images.githubusercontent.com/40798600/44407422-59fc0e80-a55e-11e8-9adb-6c8656dad8a1.png)

**Comment by AlexanderYakunin** [comment]
Please comment what you need to do with this event? You may need different event here depending on purpose.

**Comment by AlexanderYakunin** [comment]
So you need handled OnBefore event here to replace our business logic by your own?

**Comment by brankoradovic** [comment]
If our new field "Post Adjust. Per Postin Group" is not checked function will return accounts from Currency table, standard NAV functionality.
But for purpose of Serbian Localization, there should be setup where users can set different accounts for some currencies depending on Posting Group Type (Customer or Vendor) and Posting Group. Result will be same as user manually changed this accounts on currency table before every posting, but accounts will be used from this setup instead from currency table if field "Post Adjust. Per Postin Group" for that currency is checked.

![image](https://user-images.githubusercontent.com/40798600/44460928-4066cf80-a60f-11e8-9106-bc87f6bebe0b.png)
