### ISSUE TITLE
July Update :build no is not same or more than what is mentioned in MSDN blog

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#3412]
Hi,

When i was creating a container after downloading the latest image of **bcinsider.azurecr.io/bcsandbox-master**  i am getting the below version:
![image](https://user-images.githubusercontent.com/26792519/44445212-bf530c80-a5fd-11e8-85c6-4423a92b53ba.png)

but when i see in the blog it is more than
![image](https://user-images.githubusercontent.com/26792519/44445366-4a340700-a5fe-11e8-8a98-756fa9d69f35.png)

Please suggest me

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
We had some changes in internal build numbering. We will make sure this number is correctly communicated from the next blog post.
In any case, there is no longer such thing as a "developer preview release". We release daily builds in which you will get new features as they are checked in to our master branch. The monthly blog posts serve just as a summary and disclosure points. After a feature has been described in the blog post it is no longer bound by NDA.
