### ISSUE TITLE
Q: Wich trigger will run first?

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3413]
Hi,

I have a question regarding the OnAfterGetRecord - trigger on Pages.

If i put Code into an event subscriber in a codeunit and i put code in a page extension trigger of OnAfterGetRecord, wich one will be executed first?

Thanks in advance

**Comment by qutreson** [comment]
Hi @LFlamme,

The server currently behaves as follows:
1. The `OnAfterGetRecord` of the page is exectued,
2. The `OnAfterGetRecord` of all the page extensions is executed one after the other,
3. Finally the event is raised and all the event subscribers are executed one after the other.

You can verify it by running the following code:
```
pageextension 50105 MyExtension extends "Customer Card"
{
    trigger OnAfterGetRecord()
    begin
        Message('OnAfterGetRecord');
    end;
}

codeunit 50105 MyCodeunit
{
    [EventSubscriber(ObjectType::Page, Page::"Customer Card", 'OnAfterGetRecordEvent', '', true, true)]
    local procedure MyProcedure()
    begin
        Message('Event');
    end;
}
```
