### ISSUE TITLE
Question : Handling a specific customization where file needs to be saved in directory?

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/AL#3417]
Hi Team,
Good Morning.

We are working on a functionality where we need to export some files i.e. PDF, Excel from NAV and save it on some directory (Client or Server). Is there any way to do this on business central because i'm not sure how or what path we will define to export files. 
Same is the query in case if we need to import file into NAV.
Any suggestions..

Regards,
Anuj Nagpal

**Comment by Kowa63** [comment]
Not supported (unless you set the compiler target to 'internal' for on-prem extensions)
https://github.com/Microsoft/AL/issues/2981

What you can try is to engage a cloud storage provider and then exchange the files using Streams, TempBlob table and the BLOB fields in table 1220 Data Exch. with it.
