### ISSUE TITLE
txt2Al: Standard objects creating as objects and not extensions

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#342]
Hi,

When i run the txt2al to convert the customer table where i have added a field it is creating a new al file with customer.al but it has object of table and not table extension.

Please suggest me if i am doing wrong.

Thanks,
Varun Reddy

**Comment by StanislawStempin** [comment]
Have you created a .delta file before running it through the txt2al tool?

The full process is:
1. Export the baseline using ExportToNewSyntax
2. Export the modified objects using ExportToNewSyntax
3. Create .delta files
4. Run txt2al converter

**Comment by bachii1010** [comment]
Hi,
Thanks for the response.

Can you please provide an sample commands to create a delta file or the process you told above.

Thanks in Advance

**Comment by waldo1001** [comment]
First: you need an original version.  So please make sure you always have the original objects of a certain database you're modifying.
next: you export both Original and MOdified objects
then, you use "Compare-NAVApplicationOBject" cmdlet in PowerShell to create our deltas..
