### ISSUE TITLE
Report.SaveAs takes a long time

### ISSUE THREAD

**Issue by Joel-NAVDev** [Microsoft/AL#3424]
Report.SaveAs takes 30 seconds to a minute on my BC master docker container, the container has 4G memory limit.

**Comment by StanislawStempin** [comment]
Can you please provide more details? 
Does the same SaveAs run faster on other environments? What report is it? Does it depend on the data format being used?  Does it depend on the size of the input data for the report?
Which version are you using, etc?

**Comment by Joel-NAVDev** [comment]
Hi @StanislawStempin 

I am using the latest BC insider image. I find Report.SaveAs to be generally slow, with or without specifying a parameter.

In the example below I set the document No. to a single record and find the routine to takes about 30s. 
![image](https://user-images.githubusercontent.com/27202678/45547020-3a7f9b00-b817-11e8-889f-82f4e6e16998.png)

**Comment by jensmpmsft** [comment]
A few follow-up questions:
If you just run the report - is it then also slow.
Are all reports slow - both Word layout reports and RDLC?
Is there a custom layout being applied here - and how large is it?
Did you establish that it is the .SaveAs call, and not the DownloadFromStream call that takes time

**Comment by Joel-NAVDev** [comment]
Hi @jensmpmsft 
Printing the report from the page action and Report.Run is fast in comparison to Report.SaveAs.
I have not played around with different type of layout, these are built-in RDLC.
The file size comes to 188KB for the resulting PFD.
I can confirm the delay is in .SaveAs, I have debugged and it seems to hang while the process is complete.
![image](https://user-images.githubusercontent.com/27202678/47907433-26edc980-de83-11e8-9e24-80f6839754ee.png)

**Comment by jensmpmsft** [comment]
It sounds like it is the disk access that is slow in your container setup. We have not been able to repro same behavior locally, so I would assume this could be related how you have set up the file access.
