### ISSUE TITLE
Set Visibility on Pagefields based on Expression

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#3428]
I recently tried to set the visibility of fields on the "Item Card", based on the following expression:

IsVisible := "Type" = "Type"::"XXX";

I already tried multiple things:
- I added code in the "OnAfterGetRecord" and "OnAfterGetCurrRecord". --> Nothing happened (Fields didn't appear on Item Card)

- I added a public procedure on the Item Card, which includes the Visibility Expression and  subscribed to the "OnAfterGetRecordEvent" of the Item Card --> How am I able to access the Page from which the Event was triggered to run my procedure on the Item Card?
Because of the Event parameters, I'm only able to access the regarding Item Record.

- I created a procedure with a bool return value on the Item Card, which i tried to call right from the Visible Pagefield Property. --> Got an error, which says "Procedure calls is not valid for client expressions."

Is there any best practice for doing this scenario in AL?

Thanks for your help in advance.

**Comment by hendrik244** [comment]
Can nobody help me with this one?

**Comment by demiliani** [comment]
Setting the visibility with a Boolean variable assigned on code should work.
See also #1969

**Comment by StanislawStempin** [comment]
There is a workaround described in #1969
