### ISSUE TITLE
How to check field numbers created through tableextensions in a NAV Database?

### ISSUE THREAD

**Issue by Jlferro** [Microsoft/AL#3429]
Hi all.

Is there any place where we can check all the fields created through tableextensions in a NAV Database? The problem is, when I have many extensions developed for the same database is hard to know wich is the last number I have used for new fields in a table. Now I'm writing it in an excel file but I think it isn´t the best way to do it.

**Comment by BhaskarJani** [comment]
Hi,

Have you seen this article : https://dynamicsuser.net/nav/b/peik/posts/developing-extensions-blindfolded-in-dynamics-nav

It may help.

Regards - Bhaskar

**Comment by Jlferro** [comment]
It works perfectly.

Thank you very much!
