### ISSUE TITLE
DOWNLOADFROMSTREAM is not supported

### ISSUE THREAD

**Issue by frankmnielsen** [Microsoft/AL#343]
DOWNLOADFROMSTREAM is currently not supported in Extensions A workaround would be to use BlobExport in CU419 File export - but the function is marked as internal.

Having the ability to download a blob/stream to client is crucial to create apps like expense or document management where there is a need to show images or pdfs on the client

Can you please enable DOWNLOADFROMSTREAM or make BlobExport external

Michael

**Comment by StanislawStempin** [comment]
We will make DownloadFromStream external.
