### ISSUE TITLE
DecimalPlaces property ignored in AL Page ?

### ISSUE THREAD

**Issue by BhaskarJani** [Microsoft/AL#3430]
Hi All,

I have been trying to set number of decimal places in an AL page extension but it seems to be ignored.

                Field(TestDecimal;TestDecimal)
                {
                DecimalPlaces=0:7;
                }

Note: Field TestDecimal is of data type Decimal.

Has anyone else tried this property in an AL page ?

Thank you - Bhaskar

**Comment by BhaskarJani** [comment]
Hi, 

I checked further and found this reported in #2155 and a comment saying a fix for this was going to be made available.

Can Microsoft please confirm which CU of NAV2018 includes this fix ? I have tried in CU3 and it did not work.

Thanks - Bhaskar

**Comment by thpeder** [comment]
Hi @BhaskarJani,
The fix should be in 2018 CU6

**Comment by BhaskarJani** [comment]
Many thanks Thomas.

Regards - Bhaskar

------ Original Message ------
Received: Fri, 24 Aug 2018 12:36:39 PM +05
