### ISSUE TITLE
Usabilty of Keys in VS Code

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#344]
I have a question based on a comment that was placed yesterday in a different issue.

Keys.

What is the reason to have keys besides the primary key? I mean, there is no way to know up front what SQL indexes you need for performance. Are SQL Indexes created on the fly when performance degrades?

For things like SETCURRENTKEY and Report view we don't need to explicitly define a key, we can just sort on anything.

CALCSUMS and flowfields have the same, SUMINDEXFIELDS are no longer mandatory.

What sense does it have to continue to support the key?

About the primary key. There is a Design Pattern which is extremely popular in NAV called the Rules Table. To make use of this pattern one has to add fields to the primary key of a table. AFAIK this is not supported using extensions which essentially makes using this pattern obsolete and we have to come up with a new way of handling this.

Just a brainwave of a crazy dude...

**Comment by markbrummel** [comment]
Stan? Esben?

**Comment by StanislawStempin** [comment]
When it comes to defining keys on table objects nothing changed here compared to Extensions V1. Indexes are not created on the fly, they are created based on the defined keys. If you know you'll be sorting or doing lookups on given columns defining indices on these will help improve performance. Of course, in SaaS, without having operational control of the DB you cannot tweak these indices at runtime in response to different data compositions but that's a different discussion not really related to Dev Preview/Extensions V2. (I suggest reaching out to Kennie if you're more interested in this topic)

The only change is not being able to modify/add keys on base tables any more. You are correct in that any approaches that relied on being able to do that will have to be changed.

**Comment by markbrummel** [comment]
Then I hope it will be changed before one of your customers reach a database size of more than 50GB. ;-)

**Comment by Gallimathias** [comment]
50 Gb is easy to reach if you have big customers. With us one speaks of one or other of TB and not of GB. ;)
