### ISSUE TITLE
Oninit trigger of page is not available in Business central

### ISSUE THREAD

**Issue by shyamraoo** [microsoft/AL#3442]
Hi

I am trying to change the "Update Unit Cost" field is checked by default when changing status in production order.

In NAV, if we modify the oninit() trigger of "Change status on Prod. order status" page as shown below it works fine but in D365 BC if we try to extend this page in visual studio code and try to add oninit trigger it shows the trigger is not valid and also the global variable is ReqUpdUnitCost is not found.

Even OnAfterinit trigger also not found. Please advice.

![image](https://user-images.githubusercontent.com/14193656/44580062-21567200-a7b6-11e8-9860-e5c156423315.png)

![image](https://user-images.githubusercontent.com/14193656/44580293-0f290380-a7b7-11e8-8730-fb6813bd0077.png)

![image](https://user-images.githubusercontent.com/14193656/44580333-2c5dd200-a7b7-11e8-923a-511c49aa3a60.png)

**Comment by thpeder** [comment]
Hi @shyamraoo,
Global variables are not available at the moment but we have discussions internally how we could do that.
There are no OnAfterInit trigger, the best so far is the OnOpenPage, but we will take you suggestion into consideration.

**Comment by Bleika** [comment]
Hi @shyamraoo 
Did you figure out how to work around this?
I'm refactoring to AL and although I'm struggling with a different scenario, I have to place a line of code (filtergroup) that used to be in the OnInit trigger 
@thpeder do you have any further feedback on this?

**Comment by thpeder** [comment]
I don't have any more information at the moment, but if an event could resolve your specific issue for now then I'll recommend going to [Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions/issues) and create a request for the need ones.

**Comment by atoader** [comment]
Going forward, both scenarios should be solved by requesting extensibility points in the base application via the [Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions/issues) repository.
