### ISSUE TITLE
[Event Request] Codeunit Whse.-Activity-Post ; Function Code

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3443]
Hi,

we need an event in Codeunit 7324 Whse.-Activity-Post in function Code:
There are 2 possiblities how we could work with it. The first is the one shown below. We want to be able to delete the Whse Activity Line based on a custom field. Therefor we have an event with handler variable that is then checked in the inf-clause.
![image](https://user-images.githubusercontent.com/41729653/44582267-4ee4f080-a7a1-11e8-9871-4ef8eb170aa3.png)

**needed for this:**
variable: 
M365_deleteWhseActiveLineL : Boolean

Event:
M365_OnBeforeDeleteWhseActiveLine(
whseActivityLineL : Record "Warehouse Activity Line";
VAR deleteWhseActivLineRL : Boolean)

The second possible solution would be an evend with handler in the Else Begin 
![image](https://user-images.githubusercontent.com/41729653/44582681-acc60800-a7a2-11e8-84bc-b939d3f478d2.png)

We would prefer the first solution. Please tell us wich of those your are going to implement.

_Thanks in advance_

**Comment by AlexanderYakunin** [comment]
First option is fine
