### ISSUE TITLE
Question : Cannot see AU functionality

### ISSUE THREAD

**Issue by ryanbudge** [Microsoft/AL#3450]
Hi,

I am using the below configuration :--
AL Extension Version : 0.17.23984
Server version : AU Dynamics NAV 13.0 (23540) 

I run the code stolen from one of Freddy's blogs to create users but still cannot see the EFT Register that you can see in the AU functionality.

Any ideas ?

Thanks for your time.

[Create Multi-User Setup.txt](https://github.com/Microsoft/AL/files/2321630/Create.Multi-User.Setup.txt)

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
