### ISSUE TITLE
Question : Permission Set Issue

### ISSUE THREAD

**Issue by ryanbudge** [Microsoft/AL#3451]
Hi,

I am using the below configuration :--
AL Extension Version : 0.17.23984
Server version : AU Dynamics NAV 13.0 (23540)

I am trying to package up permission sets for my extension, generated the with VS Code as per https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets

Get the following error when building 
warning AD0001: Analyzer 'Microsoft.Dynamics.Nav.PerTenantExtensionCop.ExtensionHasPermissionSetEntriesForAllTables' threw an exception of type 'System.Xml.XmlException' with message 'Data at the root level is invalid. Line 1, position 1.'
c:\Code\IP\extension\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Code\IP\extension\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.

Any ideas ?

**Comment by thpeder** [comment]
Hi @ryanbudge,
I think it is the same issue as #1513 ran into. Change the file encoding from UTF8-BOM to UTF8.

**Comment by thpeder** [comment]
It looks like we haven't fixed that issue everywhere.

Thanks for reporting the issue.

**Comment by hendrik244** [comment]
Any updates on this one? I also got this problem in the moment ...

**Comment by AndreyKorepanov** [comment]
It seems to be fixed in the latest build. Could you, please, try it again with the latest AL extension from the marketplace (2.0.48254+).

**Comment by ryanbudge** [comment]
All working.
Thanks !
