### ISSUE TITLE
Suggestion: "source" in XLIFF files is never updated.

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#3457]
I am currently handling my XLIFF files like so:
- I take the generated `.g.xlf` file as the one that contains the "base" language. ENU, that is.
- Before packaging my app, I copy the `.g.xlf` file 1:1 into a `en-US.xlf` and it becomes a real translation
- I therefore **never** manually modify the `en-US.xlf` file to correct captions. All changes to the ENU language **must** happen on the `Caption` properties inside the source `.al` files.

Now here is my problem. When building and packaging the app, the compiler only updates the `.g.xlf` file. Which leads to the following problem:

- I create the app and let the compiler generate the `.g.xlf`.
- I take this `.g.xlf` file and translate my app into *de-DE* and *it-IT* among others.
- I then realize that there is an error in one of my english captions. I go into the source `.al` file and correct the error and rebuild the app.
- The `.g.xlf` file is rebuilt and reflects my change. But the compiler also gives the following error: `Translations\MyApp.de-DE.xlf(14,25) warning AL0472: The source of the translation item does not match the label value. Ignoring the translation item.`

I understand that the problem is, that the `source` tag inside the `.xlf` files for each language does not get updated with the new caption from the `.al` file.

My question is: Could you please automate this?

You could loop over all `.xlf` files and update all `source` tags. The strings share the same key, so it should be easily doable. Otherwise changing an ENU caption becomes a monumental task.

**Comment by crodriguezinn** [comment]
Hi @hemisphera,

Recently, I have answered a post that deals with translation files, in case it may be of interest to you.

It is a solution to keep the translation files

https://github.com/Microsoft/AL/issues/4361

I hope it will help you.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
