### ISSUE TITLE
Suggestion: Provide access to custom build scripts

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#3458]
I would love to see a feature being implemented that allows us to hook into the build process of an app by using PowerShell. Something like NuGet does. This would allow us to provide scripts that are automatically executed **before** and **after** (just examples) the building of the app and perform project-specific custom tasks whenever someone builds the app.

To make it simple you could look for the scripts inside a folder called `scripts` were we can deploy scripts. A file called `prebuild.ps1` is executed before the build and a file `postbuild.ps1` is executed after the build completed. It might also provide a result of the build to the script.

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
