### ISSUE TITLE
How to create control actions in VCS

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3459]
Hey guys,
I am trying to create a page extension with control actions. But I do not know where to place them in the code. 

```
{
    layout
    {
        addlast(Control8)
        {
            field("Holiday - Requested"; "Holiday - Requested")
            {
                ApplicationArea = all;
                DrillDownPageId = "Pending `Absences";
            }
        
        }
    }
}
```

**Comment by thpeder** [comment]
Hi @malue19,

It needs to be placed in a cuegroup. 
```
layout
{
    addfirst(Content)
    {
        cuegroup(MyCueGroup)
        {
            actions
            {
                action(NewControlAction)
                {
                    trigger OnAction()
                    begin
                        Message('Hello World!');
                    end;
                }
            }
        }
    }
}
```

Read more about it [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-cues-action-tiles#create-an-action-tile)

**Comment by malue19** [comment]
Hi @thpeder,
thank you for your answer :) now I have another question: I would like to extend a standard page. That is why I created a page extension with some fields, which should extend the standard page. Additionally I would like to add some page controls in the same layout like the fields before. Unfortunately it is not possible to add any actions in this area...how do I solve this? The group in the standard page is a cue group.

**Comment by thpeder** [comment]
If you want to add actions to an existing cuegroup then you will addbefore/addafter an existing action. eg.
```
actions
{
    addAfter(SomeActionName)
    {
        Action(MyAction)
        {
            trigger OnAction()
            begin
                message('Hello!');
            end;
        }
    }
}
```
