### ISSUE TITLE
Cannot extend data migration

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#346]
In our extension we have extended the data migration feature to allow a user to import into our extension tables. This essentially involves copying codeunit 1806 (Excel Data Migrator) and modifying it for our tables. 

The problem now is there are so many things within that codeunit that are now not allowed with extension development:
- file management
- exporting to Excel
- configuration package access

How is this going to be addressed? Not sure that you can simply make all of the functions available due to the nature of what they are, so is there going to be a better way to hook into the data migration?

This is extremely important for getting our users up and running quickly with our extensions.

**Comment by StanislawStempin** [comment]
We are looking at comprehensively enabling RapidStart for SaaS, considering all the limations that you mentioned. We don't have a timeline yet but acknowledge that it's an important scenario

**Comment by MikeGlue** [comment]
I hope we can get this resolved sooner rather than later. I don't know how we will be able to move our existing published app to v2 without access to these features. We have invested in a lot of time making the customer journey as smooth and easy as possible and things like data migration and rapidstart are a major part of that.

**Comment by StanislawStempin** [comment]
This area has been refactored to no longer rely on files. It will be available in January 2018 update and include new method:
COD1806 ImportExcelDataByStream

**Comment by MikeGlue** [comment]
Just having a look at the new functions in build 20048. As far as I can see we still need to make our own Excel Migrator codeunit in order to import our extension data, which is fine, however the new function **ImportExcelDataStream** calls **FileManagement.GetToFilterText**, which is not an external function.
