### ISSUE TITLE
Translation file generation does not generate all TextConst

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#3460]
I have a working Extension and when I package it visual Studio generates a new g.xlf, everything is fine but in three TextConst it doesn't generate a source. I don't know why These three textconsts aren't generated, they are referenced and everything works fine.

**Comment by epernst** [comment]
TextConsts are not included in the translation files. Use the new "Label" property instead.
_**Syntax**
As stated above, the ML properties (CaptionML, TooltipML etc.), the old report label syntax, and TextConst do not get included in the .xlf file for translation. Make sure to update your code from the old ML syntax to the new label syntax described below."_

[](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)

**Comment by OlivierHellmann** [comment]
I know that, but I thought they are added to the xlf file if you generate them with the txt2al tool, i mean some where added.

**Comment by DominikDitoIvosevic** [comment]
Txt2al is meant as a one way upgrade so it also changes all your textconsts in converted al code into labels. When you build the converted code you should no longer have textconsts in your al.

In your app.json add `features: translationfile` and you should get warnings for all the textconsts which you should convert to labels
