### ISSUE TITLE
[EventRequest] Codeunit 12 - InsertVAT function

### ISSUE THREAD

**Issue by SDTotti** [Microsoft/AL#3469]
We are converting our localization to Business Central, and we need 2 - parameter extended - event publishers in Codeunit 12 (Gen. Jnl.-Post Line) in **InsertVAT** function, to run our country specific VAT calculation logic. We need to create additional VAT and GL Entries.

```
LOCAL InsertVAT(GenJnlLine : Record "Gen. Journal Line";VATPostingSetup : Record "VAT Posting Setup";GLEntryAmount : Decimal;GLEntryVATAmount : Decimal;GLEntryBaseAmount : Decimal;SrcCurrCode : Code[10];SrcCurrGLEntryAmt : Decimal;SrcCurrGLEntryVATAmt
// existing event
//OnBeforeInsertVAT(GenJnlLine,VATEntry,UnrealizedVAT,AddCurrencyCode);

//+ existing event with additional parameters
OnBeforeInsertVAT(GenJnlLine,VATEntry,UnrealizedVAT,AddCurrencyCode,
                  VATPostingSetup,GLEntryAmount,GLEntryVATAmount,GLEntryBaseAmount,
                  SrcCurrCode,SrcCurrGLEntryAmt,SrcCurrGLEntryVATAmt,SrcCurrGLEntryBaseAmt);
//- existing event with additional parameters


WITH GenJnlLine DO BEGIN
  // Post VAT
  // VAT for VAT entry
  VATEntry.INIT;
  VATEntry.CopyFromGenJnlLine(GenJnlLine);
  VATEntry."Entry No." := NextVATEntryNo;
.
.

.
.
          VATPostingSetup."VAT Calculation Type"::"Sales Tax":
            InitGLEntryVAT(GenJnlLine,TaxJurisdiction.GetSalesAccount(UnrealizedVAT),'',
              GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);
        END;
    END;
END;

// existing event
//OnAfterInsertVAT(GenJnlLine,VATEntry,UnrealizedVAT,AddCurrencyCode);

//+ existing event with additional parameters
OnAfterInsertVAT(GenJnlLine,VATEntry,UnrealizedVAT,AddCurrencyCode,
                 VATPostingSetup,GLEntryAmount,GLEntryVATAmount,GLEntryBaseAmount,
                 SrcCurrCode,SrcCurrGLEntryAmt,SrcCurrGLEntryVATAmt,SrcCurrGLEntryBaseAmt,
                 NextConnectionNo,NextVATEntryNo,NextTransactionNo,TempGLEntryBuf."Entry No.",AddCurrGLEntryVATAmt);
//- existing event with additional parameters

```

Signature:

    [Integration]
    LOCAL PROCEDURE OnBeforeInsertVAT@199(VAR GenJournalLine@1000 : Record 81;VAR VATEntry@1001 : Record 254;VAR UnrealizedVAT@1002 : Boolean;VAR AddCurrencyCode@1003 : Code[10];VAR VATPostingSetup@1011 : Record 325;VAR GLEntryAmount@1010 : Decimal;VAR GLEntryVATAmount@1009 : Decimal;VAR GLEntryBaseAmount@1008 : Decimal;VAR SrcCurrCode@1007 : Code[10];VAR SrcCurrGLEntryAmt@1006 : Decimal;VAR SrcCurrGLEntryVATAmt@1005 : Decimal;VAR SrcCurrGLEntryBaseAmt@1004 : Decimal);

    [Integration]
    LOCAL PROCEDURE OnAfterInsertVAT@203(VAR GenJournalLine@1000 : Record 81;VAR VATEntry@1001 : Record 254;VAR UnrealizedVAT@1002 : Boolean;VAR AddCurrencyCode@1003 : Code[10];VATPostingSetup@1016 : Record 325;GLEntryAmount@1015 : Decimal;GLEntryVATAmount@1014 : Decimal;GLEntryBaseAmount@1013 : Decimal;SrcCurrCode@1012 : Code[10];SrcCurrGLEntryAmt@1011 : Decimal;SrcCurrGLEntryVATAmt@1010 : Decimal;SrcCurrGLEntryBaseAmt@1009 : Decimal;VAR NextConnectionNo@1008 : Integer;VAR NextVATEntryNo@1007 : Integer;VAR NextTransactionNo@1006 : Integer;TempGLEntryBufEntryNo@1005 : Integer;AddCurrGLEntryVATAmt@1004 : Decimal);

**Comment by AlexanderYakunin** [comment]
Which country require such extras?

**Comment by SDTotti** [comment]
Hungary. Related to the specific VAT Currency Exchange Rate and VAT Analytics calculation.
