### ISSUE TITLE
Maximum record size (question) 

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#347]
How will the maximum record size behave in combination with extensions? If an extension on the 'Customer' table would be published, is the maximum record size of a 'Customer' record, including the companion table fields limited to 8000 bytes in total, or would we have 8000 bytes for the base 'Customer' table and an **additional** 8000 bytes for each companion table as well?

**Comment by esbenk** [comment]
Companion tables don't count against the base table limitation.
