### ISSUE TITLE
FTP Integration with Business Central

### ISSUE THREAD

**Issue by NAVAttainUser** [Microsoft/AL#3478]
I am working on a FTP integration where I need to connect to FTP server to pick .csv files and consume those files in Business Central through XMLPorts/CSV Buffer table. Since DotNet type are not supported in Business Central, what could be the best way to integrate the FTP with BC. Need clarity on how we can accomplish this without dotnet variable. 

Thanks,

**Comment by alanb999** [comment]
Use scripted FTP commands...
http://techblog.byllemos.com/2009/06/uploading-a-file-with-ftp-from-navision/

**Comment by ShadowXVII** [comment]
@NAVAttainUser , you may want to look into using Azure Blob Storage or Microsoft Flow to help integrate your FTP to Business Central. There's no native FTP interface (which hopefully is only Secure FTP, or similar, these days!).

@alanb999 , that will not work on Business Central hosted.

**Comment by StanislawStempin** [comment]
Your only option right now is to use Azure Function as an intermediary between Business Central and the FTP service. We currently don't have plans for adding native SFTP (as pointed out above Secure FTP is the only one you should use) support.
