### ISSUE TITLE
Renaming symbols misses object references in code

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#348]
When I rename a symbol, it seems to miss the references to the object that are directly in the code.

To reproduce this issue see the pic below. If you rename 'CodeunitA' by using the rename symbol function, the reference in the VAR section of codeunitB will be updated, however the codeunit.run reference will not.

![capture](https://user-images.githubusercontent.com/5204734/27843117-613ee4a8-60de-11e7-9eb7-15b054e4757d.PNG)

**Comment by jimmymcp** [comment]
Using "Rename Symbol" on a field doesn't rename references to it in event subscribers. By design? Would be useful is this was possible.

AL Extension: 0.11.15001

**Comment by dennisfrostlander** [comment]
Not by design, rather a missing feature. Arguments of EventSubscriber referencing global variables are not identified as references and therefore are not renamed. 
If you could open a separate issue on this, it will be properly prioritized.

**Comment by dennisfrostlander** [comment]
You can put both together - yet another missing cases for renaming symbols :)
