### ISSUE TITLE
Question about Text Constants in AL

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/AL#3485]
How can I declare "quotation marks" as a text constant so that I can use this constant as a default for fields?
Unfortunately, quotes are used as text delimiters.

**Comment by kalberes** [comment]
Identifiers are escaped with double "", if that was the question. Literals with double ''.

**Comment by ThorstenEngelsGOB** [comment]
That is a step in the right direction. 
I just have the problem that I want to predefine a programmed filter field for a function with the default value of the double quotation mark. 
In the variable declaration I use either a label or a direct assignment but both types do not give the desired result.
Filter: Label ' ' ' ';
or
Field := ' ' ' ';
In both cases only a single quotation mark appears in the WebClient and my function leads to an error in the following. If I add another quotation mark in the field and in the client, then the filtering works.

**Comment by ThorstenEngelsGOB** [comment]
The "problem" is solved. 
To program a double quotation mark as default for a filter criterion, you need two escape sequences.
In addition to the declaration of the text there are therefore six! Quotation marks which are needed for the conversion in Visual AL.
Filter: Label ' ' ' ' ' ';
The case can be closed.
