### ISSUE TITLE
Query - DataItemTableFilter does not work with filter on Date and OData webservice

### ISSUE THREAD

**Issue by cosminah** [Microsoft/AL#3488]
Hi,

AL Extension Version: 0.17.30289

We need to filter a DataItem from a Query by using DataItemTableFilter on a field of type Date.

It seems that the query compile and the extension can be publish but when we are publishing the OData web service for this Query we have an error.

**Query format** 

query 50000 "Cust. Ledger Entry"
{
    QueryType = Normal;

    elements
    {

        dataitem(Cust__Ledger_Entry; "Cust. Ledger Entry")
        {
            DataItemTableFilter = "Posting Date" = filter (29082018);

            column(Customer_No_; "Customer No.")
            {

            }

        }
    }
}

**Error:**

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code/>
<m:message xml:lang="en-US">
The value "29082018" can't be evaluated into type Date.
</m:message>
</m:error>

This is a BUG ? Or we need to write in another way the 

DataItemTableFilter = "Posting Date" = filter (29082018); (Is strange that the object is compiling)

Thanks,
Cosmina

**Comment by cosminah** [comment]
Hi,

Date format is : Month/Day/Year
And filter DataItemTableFilter = "Posting Date" = filter ('5/27/2016'); works fine :)

If I go with this solution in my extension and at customer side they have other configuration for date format I will not have the same problem ?

**Comment by alantipo** [comment]
Solution would depend on the goal and conditions :)

If you have an option to programmatically define the filter with DMY2DATE(27,5,2016), it would be much better - DMY2DATE should take care of localization issues. You can use both SetFilter and SetRange for that. Format property to set Date format may also come in useful:
https://docs.microsoft.com/en-us/dynamics-nav/format-property

However, if you have to hard code the date in that format (for example, it came from some other function as a string), you would have to go with just '5/27/2016' put into the code or perform some extra parsing to turn '5/27/2016' into '/27/5/2016' (as an example of the other date format). 
The more things you have hardcoded in the code, the less flexible it is for changes (such as localizations).

**Comment by cosminah** [comment]
Thanks for your answer :)
