### ISSUE TITLE
Centralize the PrepareHeader/Footer Method for Sales Documents

### ISSUE THREAD

**Issue by joshua-lehmann** [Microsoft/AL#3496]
In all the sales document reports 204,205,206,207,208 etc. there are the local functions PrepareHeader/PrepareFooter used.
![r205-prepeareheader-preparefooter](https://user-images.githubusercontent.com/23728611/44837942-4118ea80-ac3b-11e8-8be6-3ad4d8dc8cac.jpg)
![r206-prepeareheader-preparefooter](https://user-images.githubusercontent.com/23728611/44837943-4118ea80-ac3b-11e8-913a-9e936d40d3d4.jpg)
![r207-prepeareheader-preparefooter](https://user-images.githubusercontent.com/23728611/44837944-4118ea80-ac3b-11e8-80f5-5bd4e0b46ed6.jpg)

**Request:**
It would be great theese functions would be centralized in a codeunit and an event would be added to theese functions. So in the reports there would be something like SalesDocumentCodeunit.PrepareFooter(Passing the record right here for ex. Sales Invoice Header)
And then an event in this centralized function like OnAfterPrepareFooter[FooterLabel,FooterTxt]

**Use Case:**
If you want to customize the header/footer on all sales documents at the moment you need to modify the code of the functions in every report. If the function would be centralized and an event would be added to it you could easily customize the header/footer with a subscriber function and without redundant code.

**Comment by joshua-lehmann** [comment]
@kalberes Hi, any news on this issue? 😃

**Comment by thpeder** [comment]
Hi @joshua-lehmann 
The team has added the workitem to their backlog but I do not have any estimates as to when or if it is going to be changed.

**Comment by StanislawStempin** [comment]
We no longer track application issues in this repo. The status for this change can be enquired in the future on ALAppExtensions GitHub repo.
