### ISSUE TITLE
Cannot implicitly convert type 'Text' to 'Char' 

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#3497]
After using the daily build pulled on date 300818

I´m beginnig to get this error : error AL0122: Cannot implicitly convert type 'Text' to 'Char'
The code that is causing the error is this.
![image](https://user-images.githubusercontent.com/28138717/44843109-d1f5c300-ac47-11e8-9caa-56e15f67def6.png)

![image](https://user-images.githubusercontent.com/28138717/44843326-59433680-ac48-11e8-97ac-06025f86a53d.png)

**Comment by kalberes** [comment]
Can you try a build from September. It should have been fixed.

**Comment by MortenRa** [comment]
Yes it works now
