### ISSUE TITLE
Warning AL0468: Length of the table field name must not exceed 30 characters

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#3498]
So, we have a field that is 33 characters long and we have been receiving this warning for a while:

```warning AL0468: Length of the table field name must not exceed 30 characters. Longer field names are prone to cause SQL errors.```

We haven't been stressed about it since it is only a warning, although having a warning is never fun. Now however if we build against the future release of Dynamics 365 Business Central, namely `bcinsider.azurecr.io/bcsandbox-master`, we get another message:

```warning AL0468: Length of the table field name must not exceed 30 characters. Longer field names are prone to cause SQL errors. This warning will become an error in a future release.```

Since it will become an error in a future release we need to address this before that happens. But since our extension is live in Business Central there is nothing we can do at this point since breaking scheme changes are not allowed as mentioned in issue [#1499](https://github.com/Microsoft/AL/issues/1499).

Thought I'd point out this dilemma and use the opportunity to reiterate the need for breaking scheme support :).

**Comment by kalberes** [comment]
Catch 22.

**Comment by AndreyKorepanov** [comment]
We are working on the tool which allows to edit/remove the fields in the existing extensions to maintain the backward compatibility via deprecating process. Once it is ready we turn the mentioned warning into exception. So nothing wrong with the message.
