### ISSUE TITLE
ClientCrash

### ISSUE THREAD

**Issue by LeoSharma** [Microsoft/AL#35]
After deploying an extension, I experienced a repeated client crash. The extension added a field in item table and made that field visible on the item page. 

![crash](https://cloud.githubusercontent.com/assets/24705746/21408306/4101b996-c7cc-11e6-9faa-bf98c6e708cd.png)

**Comment by esbenk** [comment]
What Id did you assign to the added table field? Unfortunately ids still have to unique across both base-table and extensions. Can you try to change the field id to a different range and redeploy?

If that doesn't work, can you share the code?

**Comment by LeoSharma** [comment]
HI Thanks for you response. Table id's and Field id's are also a puzzel for me. Is there a documentation where i can check what i can use and what not. Besides it would be cool if VS Code would automatically suggest Table ID & Field ID. 

The client crashed a few times and i redeployed the solution without changing the ID's and after 4 crashes it worked on itself. Kindly find attached the extension.

**Comment by esbenk** [comment]
For the object ids the valid range are enforced by the compiler. Using field ids in the same range (70000000..74999999) should be safe in the preview.

Ids are working much like NAV today. We are looking into how to improve the experience around ids in the future.
