### ISSUE TITLE
Automatic Object ID assignment

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#350]
Since we never really use the Object ID, I would like to have some kind of functionality, which auto assign object id's. For example could I define my object id range in my app.json file and then just insert the next available number whenever I use one of the object snippets.

**Comment by StanislawStempin** [comment]
This is on our backlog. The current plan is that Intellisense will suggest the next available ID per object type.

**Comment by RasmusTidselbak** [comment]
Okay, thank you for clarifying :)

**Comment by StanislawStempin** [comment]
This is available as of Anniversary Update.
