### ISSUE TITLE
What does 'Verbosity' mean?

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#351]
What is the meaning of this?

Seems to be a new variable type in C/Side.

![verbosity](https://user-images.githubusercontent.com/7205122/27902041-7fd40a40-6234-11e7-8cc0-326d1ec20e4d.png)

**Comment by StanislawStempin** [comment]
Verbosity is a new system option used by a new internal method (SendTraceTag). You are free to use the Verbosity option but the new method will not be available externally.

**Comment by markbrummel** [comment]
I'm affraid that this answer does not help Stan. What does SendTraceTag mean? Is it not better to hide this variable type if we are not suposed to use it?

**Comment by StanislawStempin** [comment]
As I wrote above - you are actually allowed to use this variable type. It's just an option with values Critical, Error, Normal, Verbose, Warning. 
SendTraceTag will not be allowed to be used in extensions so I won't go into more details about it.
