### ISSUE TITLE
[Event Request] Codeunit 90 - Add a parameter in the event OnAfterPostUpdateOrderLine 

### ISSUE THREAD

**Issue by BalajiGi** [Microsoft/AL#3519]
- AL Extension Version: 0.16.19969

- Server Version: W1 13.0 (24209)

Request to Add a parameter VAR PurchLine in OnAfterPostUpdateOrderLine event in Codeunit 90.

```

- OnAfterPostUpdateOrderLine(VAR PurchaseLine : Record "Purchase Line";WhseShip : Boolean;WhseReceive : Boolean; CommitIsSupressed : Boolean)

+ OnAfterPostUpdateOrderLine(VAR PurchaseLine : Record "Purchase Line";WhseShip : Boolean;WhseReceive : Boolean;VAR PurchLine : Record "Purchase  Line";CommitIsSupressed : Boolean)


```

**Comment by AlexanderYakunin** [comment]
PurchaseLine is first parameter for this event

**Comment by BalajiGi** [comment]
We are updating in the procedure **PostUpdateOrderLine** which needs to updated in **global variable PurchLine**.  Hence we request to provide the **global variable PurchLine** as VAR parameter.

**Comment by AlexanderYakunin** [comment]
This is not possible as COD90 use TempPurchLine for internal processing, not original PurchLine. You may have solution based on older version of COD90, please recheck if you can make it differently.
