### ISSUE TITLE
WebClient crashing on HttpHeader.Contains

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#352]
My client is crashing when I call the HttpHeader.Contains function with an invalid header type. 
If I remove the function, it will not crash.

This is the error I can see in the eventviewer:
"Type: System.InvalidOperationException
Message: <ii>Misused header name. Make sure request headers are used with  HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.</ii>"

```
HttpHeaders := HttpClient.DefaultRequestHeaders();        
if HttpHeaders.Contains('Content-Type') then
   Message('Crash test');
JSONObject.Add('name','John Doe');
JSONObject.AsToken.WriteTo(JSONText);
HttpContent.WriteFrom(JSONText);

HttpClient.Post('https://foo.azurewebsites.net/api/bar?code=GEJwiop2r12onioigeSFGSionqodwdmwa', HttpContent, ResponseMessage);
```

**Comment by ajkauffmann** [comment]
You should set the Content-Type header on the HttpContent object instead of the HttpClient object.
See also this topic: https://stackoverflow.com/questions/10679214/how-do-you-set-the-content-type-header-for-an-httpclient-request

**Comment by RasmusTidselbak** [comment]
Okay, sorry. 
Though the entire client still crashed instead of throwing an error.
