### ISSUE TITLE
System crashes on posting Warehouse Picks

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#3524]
Using Local docker W1 12.3 (23945)

"Object reference not set to an instance of an object"

We are having system crashes when posting WareHouse Picks.

We call  Codeunit 7307 "Whse.-Activity-Register"
I have traced the problem to Line No 83     "AutoReserveForSalesLine(TempWhseActivLineToReserve);"

And further using the logs to Codeunit 99000830 "Create Reserv. Entry" -> Function "CreateEntry"

The system crashes, so debugging is difficult.
I have attached logs etc.

This is a blocking error for our Product.

![error from rtc](https://user-images.githubusercontent.com/6465685/44901138-e1881100-ad06-11e8-8538-a385c57e0600.png)
![error from webclient app](https://user-images.githubusercontent.com/6465685/44901139-e1881100-ad06-11e8-9b23-2a6cf4c2bea0.png)
[Reduced Log.txt](https://github.com/Microsoft/AL/files/2339248/Reduced.Log.txt)
[VSCode error.txt](https://github.com/Microsoft/AL/files/2339249/VSCode.error.txt)
[Docker Container Log.txt](https://github.com/Microsoft/AL/files/2339247/Docker.Container.Log.txt)

**Comment by kalberes** [comment]
I can see that you have tried to go to definition, or were breaking into on some base object. That is the exception from the VsCode. What was that object?

**Comment by JSebastianN** [comment]
Hello :)

This is as far as I have gotten:

We call Codeunit 7307 "Whse.-Activity-Register"
Line No 83 "AutoReserveForSalesLine(TempWhseActivLineToReserve);"
Into:
Codeunit 99000845 "Reservation Management" "AutoReserveOneLine"

That is where I lost it the last time.

-
The service logs points to Codeunit 99000830 "Create Reserv. Entry" -> Function "CreateEntry". 
This is used by 99000845 


I would love to reproduce it in a standard environment but have not gotten so far yet.

**Comment by kalberes** [comment]
This has been fixed for the Fall release of BC.

**Comment by JSebastianN** [comment]
Wow I am impressed!
What would be the October Release right?
https://docs.microsoft.com/en-us/business-applications-release-notes/October18/dynamics365-business-central/

**Comment by kalberes** [comment]
Yes.

**Comment by parulmakkar07** [comment]
Could you please advise if the fix was released already? And if not, any expected date for the fix to be released?
