### ISSUE TITLE
Compile with ALC gives different app as compile with VSCode

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#3526]
We have the issue there is a difference in size when we build an app-file from VSCode  or an app-file with directly built with the ALC.exe:
![image](https://user-images.githubusercontent.com/12088142/44907839-a93dfe00-ad19-11e8-92d5-5d4c88c7c040.png)

We use the ALC.exe in the build-process.  And it's something like this:-
![image](https://user-images.githubusercontent.com/12088142/44907856-bfe45500-ad19-11e8-88cb-ae1b3b43f028.png)

Same code all along!
Same version (we tried multiple versions - also the latest daily build (today)) of the compiler/al-extension.

The reports don't work with the VSCode-version - so I assume there are not report layouts in the appfile.

You have any idea what we can do?

**Comment by kalberes** [comment]
App files from VsCode do not contain anything that the server compilation would otherwise create like metadata and c# code. For ALC.exe you can achieve the same size using the skipcodegeneration flag.
Which we will invert in a later release. Thus by default alc.exe won't add any metadata and c# code to the package.
The report layout being missed was supposed to be fixed with #3083 .

**Comment by waldo1001** [comment]
Ok, thank you.
File size is equal size now:
![image](https://user-images.githubusercontent.com/12088142/44922304-5a0dc280-ad45-11e8-823e-93202f92580e.png)

I don't think this is the same issue.

what we tested:
it **always works** when we build it with the **ALC** directly (code above - and also with your "skipcodegeneration" flag.

-	al-0.16.14305 - reports work when built with VSCODE
-	al-0.16.19969 - reports work when built with VSCODE
-	al-0.16.26913 - reports work when built with VSCODE
-	al-0.17.30289 - reports **do not work** when built with VSCODE
-	al-0.17.36600 - reports **do not work** when built with VSCODE

We want to use the 17-version for performance-reason (mentioned here #3088).

**Comment by kalberes** [comment]
True,, there was yet another RDLC issue fixed a few days ago. It should have been made it to the August release.

**Comment by waldo1001** [comment]
Question is - what is the august release, as we are using the very latest build ...

**Comment by kalberes** [comment]
@dennisfrostlander Has your change on RDLC issue made it to main?

**Comment by Kowa63** [comment]
> We want to use the 17-version for performance-reason (mentioned here #3088).
@waldo1001 
Actually, 0.17… is history as of today ;-).
The current 13.0.24263 build now has a VSIX version jump from 0 to 2: al-2.0.41872.vsix

**Comment by waldo1001** [comment]
It did.  Wow ...

**Comment by dennisfrostlander** [comment]
Yes, 0.17 version had an above mentioned bug with report layouts, that has been fixed in vsix version 2.0.
