### ISSUE TITLE
Publishing Error: SchemaUpdateMode=synchronize - A Task was canceled

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#3527]
Our App includes round about 500 objects. During the publish process the ouput console shows the following:
- Success: The package is created.
- [2018-08-31 12:33:58.17] Sending request to "http://[...]:7049/nav/dev/apps?SchemaUpdateMode=synchronize"
- [2018-08-31 12:38:58.13] Error: A Task was canceled.

The mysterious thing about it is. It lasts always exact 5 minutes until this error appears. 
But the app is published and works fine.

The Event log in the docker machine has no entry for this time period.

Any ideas for it?

**Comment by kalberes** [comment]
Have you published from VsCode with Ctrl F5 or F5?

**Comment by MaKnauer** [comment]
yes from Vs Code with F5

**Comment by kalberes** [comment]
F5 starts a debugging session. That way publishing it is a bit (a lot actually) different then doing Ctrl F5.
IMO what has happened is that the debugging session timed out.

**Comment by MaKnauer** [comment]
Ctr+F5 leads to the same error.

**Comment by MaKnauer** [comment]
I tried to publish it via powershell with the option LogPath. The error message is:
"The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'."

**Comment by kalberes** [comment]
What versions are you using?

**Comment by ashik-ivor** [comment]
1. Check if your container is "Healthy" before hitting F5.
2. Restart your docker and container once and try again.

**Comment by MaKnauer** [comment]
The Container is healthy before I try to publish the app. 
I restarted the Container several times :)

I set up the docker with the latest sandbox (microsoft/bcsandbox:de   /  12.3.23590.23945)

When I publish in the powershell command prompt without ErrorLog Parameter, the following message apperas:
WARNING: UnhandledErrorMessage
Publish-NAVApp : The socket connection was aborted. This could be caused by an error processing your message or a
receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was
'10675199.02:48:05.4775807'.
At line:1 char:1
+ Publish-NAVApp -Path ".......
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-NAVApp], CommunicationException
    + FullyQualifiedErrorId : System.ServiceModel.CommunicationException,Microsoft.Dynamics.Nav.Apps.Management.Cmdlet
   s.PublishNavApp

**Comment by MaKnauer** [comment]
Now it works. Thanks
