### ISSUE TITLE
Missing external methods in AL

### ISSUE THREAD

**Issue by orange-gobbler** [Microsoft/AL#353]
The following methods are currently not enabled for extensions.
Could you please check this?

- "ChooseCustomerTemplate" - Table Contact
- "UpdateRecord" - Codeunit Config. Template Management
- "InsertDimensionsFromTemplates" - Table Dimensions Template
- "HandleEvent" - Codeunit Workflow Management
- "WriteBlob" - Codeunit Type Helper
- "GetAzureKeyVaultSecret"  - Codeunit Azure Key Vault Management
- The type or method 'Record Link' cannot be used for 'Extension' development.
- The type or method 'Permissions' cannot be used for 'Extension' development.

Kind Regards

Stefan

**Comment by StanislawStempin** [comment]
I have requested for the first five functions to be made External.
Regarding the last 3 - could you share the scenarios that you are trying to accomplish?

**Comment by StanislawStempin** [comment]
Record Link will be made External as well.

So the question is only about these two:
GetAzureKeyVaultSecret"  - Codeunit Azure Key Vault Management
The type or method 'Permissions' cannot be used for 'Extension' development.
What is the scenario that requires access to these?

**Comment by orange-gobbler** [comment]
Thank you so much.
I`ve renewed my code for not using these two methods anymore.

**Comment by orange-gobbler** [comment]
Maybe I`ve closed the issue to quickly!?!
Are you planning the points above for the next update?

**Comment by dennisfrostlander** [comment]
Yes, the first 5 methods + record link should be available in the next update.

**Comment by Kraver88** [comment]
Thank you for making those changes!
I also have a request to make the Record "Database" available.
I have created a workflow Response that can send mails to users and in those mails I mention the Database.Name.
Or is there another way of knowing which Database I am currently using?

Thanks!

**Comment by dennisfrostlander** [comment]
Database will probably not make it. The extensibility is designed with the cloud/SaaS model in mind, where there are multiple tenants running on the single server/database. Therefore getting access to global things like database is not secure or even practical. 
SMTP needs to be evaluated.
