### ISSUE TITLE
How to update a Sandbox environment with unlocked methods?

### ISSUE THREAD

**Issue by GHDevNav** [Microsoft/AL#3536]
Hi,

Is there a way to upgrade a sandbox with the latest release?

Do you have a documentation for that? 

Thank you.

**Comment by kalberes** [comment]
If you reset the sandbox it will be provisioned with the latest available cloud release.
For details on dockers versions please read this blog issue.
https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
