### ISSUE TITLE
BLOB fields & Owner property

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#3537]
In C/side there was an ambiguous property for Blob fields called Owner.

AL does not recognise the property anymore.

Discontinued?

![image](https://user-images.githubusercontent.com/7205122/44956734-01ffc900-aec9-11e8-8009-8e0acb0fdedc.png)

**Comment by kalberes** [comment]
The Owner property has been ignored for a while. I do not know exactly which version from.

**Comment by markbrummel** [comment]
It was still in the NAV 2017 programming book. I removed it for the new BC version. Thanks.
