### ISSUE TITLE
Problem using Extension embedded Custom Report Layout 

### ISSUE THREAD

**Issue by SorenAU** [Microsoft/AL#3538]
My extension includes a Custom Report Layout (.LAYOUTDATA file) for a new report and is to be used as a default email body template in the extension.
The new Custom Report Layout record is inserted on Extension install with Built-In = TRUE; but no Tab2000000082 Report Layout record is created, which is required when using Built-In layouts. 
The actual Layout is instead (incorrectly) saved in the Custom Report Layout record - possibly using Tab9650 function HandleW10Layout ?.  

Is this a Bug or am I doing something wrong here ?

System Version: AU 12.3 (23918)

**Comment by SorenAU** [comment]
Do you have any idea when this will be investigated ?
@kalberes

**Comment by StanislawStempin** [comment]
For built-in report layouts for new reports you should simply use the properties on the report object:
```
report 50100 NewReport
{
    RDLCLayout = ''./Layout.rdlc';
    DefaultLayout= RDLCLayout;
}
```

.LAYOUTDATA will always be treated as a custom report layout
