### ISSUE TITLE
Problem for extension in Visual Studio Code

### ISSUE THREAD

**Issue by Ceidon** [Microsoft/AL#3542]
- AL Extension Version: 11.0.0.0

- Server Version: 1.0.0.0

The request for path /DynamicsNAV110/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: 
TableExtension 50100 :: Unsupported table change. Table:Customer; Change:Remove
Table 50100 :: Unsupported table change. Table:book; Change:Remove

the problem is: I change the number of table to 50110 but not change and give me the table 50100

**Comment by kalberes** [comment]
This looks like a Nav 2018 issue. Do you have a repro on the newest docker releases. If not please consult the regular service channels.
See for details the wiki:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions

**Comment by Ceidon** [comment]
Thanks kalberes, i haven´t any repro in docker, but persist the error, I don´t know what to do..

**Comment by kalberes** [comment]
See the  "I found an issue on NAV 2018, what do I do?" in https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions

**Comment by ashik-ivor** [comment]
On the launch.json file , enter "schemaUpdateMode":"Recreate"

Note: Recreate will delete the data from the table.
