### ISSUE TITLE
Suggestion: partial AL files

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3544]
Have you ever considered allowing us to split a single AL-Object file into multiple AL-Files? Looking at you, `public partial class`.

I am asking because now with events and stuff, there really is a lot of event-subscriber-code around. I would therefore love to group my functions into separate "logical units". 

Ok, I could create multiple Codeunits, I give you that. But: that would mean I would consume a Codeunit for the sake of structuring code. In a world where Codeunits are limited and / or counted, this feels a little strange. 

With partial files, I could create any number of partial files that help me group and structure my code. You'd then just have to mount them all together into one file at build-time.

**Comment by kalberes** [comment]
Thanks for the suggestion. It is in our backlog. See also #64

**Comment by StanislawStempin** [comment]
Closing as duplicate of #64
