### ISSUE TITLE
Upload extension into sandbox

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#3545]
Why can I only upload the extension in the live of BC?
Shouldn't our consultants and customer be able to test the new changes/extension in the sandbox?
(So when they approve we can upload it into the live?)

= Why does the action 'Upload Extension' on page 2500 'Extension Management' got the visibility = 'IsSaaS AND NOT IsSandbox'?

- AL Extension Version: 0.16.26913
- Server Version: BE Dynamics NAV 12.3 (23918)
CSS: 118090318916820

**Comment by demiliani** [comment]
I agree that it could be useful, also in scenarios where you have only a third party .app file to test.

**Comment by kalberes** [comment]
See #2106

**Comment by SirBETE** [comment]
> For Business Central cloud sandboxes it was also possible to deploy tenant specific customizations (on the Extension Management page), but it will not be the case anymore. You can still of course upload an extension to the cloud sandbox with VSCode.

= how?
By putting the customers url of the sandbox in the "server" tag?

**Comment by pmohanakrishna** [comment]
We have to use tenant tag instead of server
