### ISSUE TITLE
Any functionality similar to Tuples / Inline Tables as a new data type

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#3560]
As is well known, NAV/BC has its problems with data set lengths, text lengths and complex variable values. The dictionary and the list have already been introduced as new data types. That's awesome. The advantages are obvious. You can benefit from the many advantages of .NET and thus complete certain tasks much faster. Now I had the concrete case that I would have needed something like a tuple. In .NET these are very practical, and since C# 7 they are even more powerful than ever before. What would I like tuple for? Here are a few applications where it is worth using them in any case:

> Tuples are commonly used in four ways:
> 
> 1. To represent a single set of data. For example, a tuple can represent a database record, and its components can represent individual fields of the record.
> 2. To provide easy access to, and manipulation of, a data set.
> 3. To return multiple values from a method without using out parameters (in C#) or ByRef parameters (in Visual Basic).
> 4. To pass multiple values to a method through a single parameter. For example, the Thread.Start(Object) method has a single parameter that lets you supply one value to the method that the thread executes at startup time. If you supply a Tuple<T1, T2, T3> object as the method argument, you can supply the thread’s startup routine with three items of data.

Wait a minute, now you will say, in NAV there are already tables and a record. That is correct. It is also possible to use the table to pass parameters to a function. But unfortunately there are a few minor problems. Texts can be up to 250 characters long. A physical table is always required, even if the data is purely virtual and temporary. Yes, there are certainly some tables that are always empty in the database and are only used at runtime.

So I thought of something like a tuple, or some kind of inline table, which is pure in memory and has no size restrictions on the texts. That would be simply super practical, if one could work with it, because everything already exists in the.NET environment. I'll put this issue here as food for thought, maybe you can do something with it.

**Comment by kalberes** [comment]
Thanks for the suggestion. Most of the size restrictions are legacy from C/SIDE. I would think that as the dependency to C/SIDE fades away we will remove these restrictions.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
