### ISSUE TITLE
API Calls in test script to test the extension..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#3561]
Hello,

We are creating a test script to test our extension. But i found the following text in instruction list.

**Assisted Setup - Customer Rewards Wizard page. We will verify that the wizard behaves as expected. It can be used to completion without errors. _The Assisted Setup contains code that mimics making calls to an external service or API. Because our tests cannot make requests to an external service, we will mock the requests and the responses.**_

But we need to call some API to transfer the data. Is it possible have the same functionality with the test script and submit to Microsoft along with our extension.

Can anyone suggest me on this..

Thanks.

**Comment by StanislawStempin** [comment]
I'm not sure I understand your question. What do you mean by "is it possible have the same functionality with the test script"
