### ISSUE TITLE
Question re. user/data migration of older NAV on prem to Business Central

### ISSUE THREAD

**Issue by robertosb** [Microsoft/AL#3563]
Hi guys,

   I would like to know if we have any guidelines to start with for projects where existing on prem customers want to transition to Business Central.
   I would like to see the best answers/guidelines around these questions (which I am sure are blogged about but I want some verified answers):
   - recommended process to migrate data? We cannot do what we used to do (sql database backup restore and convert/data migration), would Config Packages be the way to go and would ledger entries need to be re-created through journals?
    * I assume the above has to be backed by transitioning any customization to extensions
   - could we transfer the user's specific data as well? how would that be done, is it as easy as mapping the users to the Azure AD through the domain provider?
   - from a licensing perspective: if a customer just subscribes to Office 365, maps his domain to the Azure AD, creates his users and buys the BC license, would he need to buy any other O365 licensing or just flick the switch for BC on each user and they would be able to use the service?

Cheers,
Rob

**Comment by StanislawStempin** [comment]
Please see:   
https://github.com/Microsoft/AL/issues/2476  
https://github.com/Microsoft/AL/issues/1689

Perhaps @jenolson has an update on this topic as well

**Comment by ThorstenEngelsGOB** [comment]
@StanislawStempin 
Your answers only lead to requests and questions that have already been closed, but that have not been answered either. There is still a need for an answer as to how a customer can be transferred to the new Azure world with an existing OnPrem solution and when or whether Microsoft plans to provide the appropriate tools.

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
