### ISSUE TITLE
Spaces in 'Enum' value definitions

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3566]
I don't know if this is intended or not. I have defined an enum like so:

```
enum 18004103 MyEnum
{
    Extensible = true;
    value(0; "Some Value") { }
    value(1; "Some Other Value") { }
    value(2; "Third Value") { }
}
```

I am now trying to use this enum like this:

```
trigger OnValidate()
var
    ZheEnum: Enum MyEnum;
begin
    if (ZheEnum = ZheEnum::"Some Value") then
        message('Huzzah!');
end;

```

Note that qualifying of the enum value `Some Value` like this has been suggested by code completion - thus I expected it to be correct.

But ALC complains that the value "Some Value" is not defined and it also does not compile. The message is this one:

`error AL0132: 'MyEnum' does not contain a definition for 'Some Value'`

Doing the following makes it work:
1. Remove all spaces from the value names
2. Remove the double quotes (") from the value names, even if there are no more spaces left.

Right now enum values cannot contain spaces and/or double quotes. Even if the definition of the enum itself is correct and compiles, I cannot **use** the values in code.

**Comment by JavierFuentes** [comment]
I would like to say that actually we can't use labels where all characters are digits (and don't need Translations)...

Someting like this:

```php
enum 50000 "Subkeys"
{
    Extensible = true;

    // Old Option values:  ,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25

    value(0; _Blank) { Caption = ''; } //No-Translatations-Needed... how can I say this to compiler? 

    // This compiles OK... but then can't use it
    value(1; "01") { } 
    
    // We can do this, but it looks ugly using later...
    value(2; _02) { Caption = '02'; } //No-Translatations-Needed... how can I say this to compiler?  
}

procedure Test()
var
    myEnum: Enum "Subkeys";
begin
    Message(Format(myEnum::"01");    // error AL0132: 'myEnum' does not contain a definition for '00'
    Message(Format(myEnum::_02));    // OK, but ugly
    Message(Format(myEnum::"_02"));  // OK, but ugly too
end;
```

**Comment by esbenk** [comment]
Message(Format(myEnum::"01");    // error AL0132: 'myEnum' does not contain a definition for '00'

This is fixed in the latest update.

**Comment by JavierFuentes** [comment]
Hi @esbenk ,
is that latest update available for downloading at the moment?

**Comment by esbenk** [comment]
There is an updated version available in the Visual Studio Code marketplace. You will need the just released CU1 to get the server support.
