### ISSUE TITLE
Numeric value for 'Enum'

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3567]
There are a few problems I face when using the new `Enum` type:

1. An `Enum` cannot be converted to or from `Integer`. Even though every value is uniquely identified by an integer value, ALC currently does not allow converting to or from `Integer`. I dearly hope this is a bug and/or will be supported in future versions.
2. Because of the above, we currently do not have any means to 'extract' the numeric value of a given Enum. One of the advantages of the `Enum` type is that I can have an enum value with - say - ID 40 without having the need to declare 40 empty options. Take interfaces to external systems as an example. At one point or another I will have to import from / export to `Integer` so I need the numeric value.

**Comment by esbenk** [comment]
It is by design that there is no implicit conversion to/from integer. We want to avoid the relaxed conversions that characterizes options.

We will add functionality to explicitly convert to/from enums in a future update. 

For backwards compatibility with C/AL we support implicit conversion to/from the Option type. We may restrict that in the future when C/SIDE & C/AL is gone.

**Comment by hemisphera** [comment]
OK, I can understand that. I don't necessarily need a relaxed conversion. I would be more than happy with the following:

````
var
  ZheEnum: Enum MyEnum;
  ZheInt: Integer;
begin
  ZheInt := ZheEnum::FirstItem.Value;
  ZheEnum := ZheEnum.Evaluate(20);
end;
````

... or something similar. This way it's no longer as relaxed as options were and you have the possibility to execute runtime checks during `Evaluate` to check if the value actually exists.

**Comment by esbenk** [comment]
It is functionality like that, we plan for a future update.

**Comment by esbenk** [comment]
We will add programmatic access to enum values in a (near) future update. This is especially important for the Extensible flavour where you at design-time don't know all possible values.

**Comment by BrianThorChristensen** [comment]
You can use:
evaluate(int, format(enum, 0, 9))
and
evaluate(enum, format(int))

**Comment by GreatScott000** [comment]
@esbenk  Any information on "programmatic access to enum values"?

**Comment by esbenk** [comment]
No. Maybe next release, but it could slip.

**Comment by navdotnetreqs** [comment]
Yeah, we need this too. I see there is enum.asinteger(), but how to set the enum without knowing the values during coding? Eg. loop the enums and select the third.

**Comment by esbenk** [comment]
It is possible to get the Enum Names and Ordinals using either the specific Enum or through a FieldRef.
