### ISSUE TITLE
Extension 2.0 Media.ImportFile

### ISSUE THREAD

**Issue by nsyilmaz2** [Microsoft/AL#3568]
Hi,

We want to use ImportFile function Media DataType in Nav 2018 Extension but We get error for this function. 

![image](https://user-images.githubusercontent.com/43000815/45090187-4d0f1b80-b117-11e8-9f6a-0c91e59e9256.png)

Please can help us.
Thanks.

**Comment by MikeGlue** [comment]
This post might help. You need to use streams now to import/export.   https://navbitsbytes.wordpress.com/2017/12/08/al-extensions-importing-and-exporting-media-sets/
