### ISSUE TITLE
TableRelation: Problem with option field i WHERE condition

### ISSUE THREAD

**Issue by Heimdaldk** [Microsoft/AL#357]
I'm making a new table with a field with tablerelation to "Object Metadata" for "Object Type"::Table but this does not seems to be allowed i AL. I'm I doing something wrong?

![image](https://user-images.githubusercontent.com/7301364/28056394-1ced85a4-661d-11e7-8e29-a0ecfd72dbd4.png)

**Comment by StanislawStempin** [comment]
Object Metadata table is currently not available for extension development. Can you use Table Metadata for your scenario?

**Comment by Heimdaldk** [comment]
Thank's for your quick answer, yes I can use Table Metadata instead.

**Comment by IvoMol** [comment]
"Oject Type" or "Object Type"?
