### ISSUE TITLE
Report Word layout

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#3570]
Hi all,

We recently updated to image 'bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca'.
Now all our reports don't see layouts, neither RDLC or Word.
I created new container and followed this link https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-report-layout to create simple word layout report. Step 2 doesn't generate file. Never mind, I generated it manually, and tried different wordlayout paths:

WordLayout = '.\TestReport.docx'; or 
WordLayout = 'reportlayout/TestReport.docx'; or 
WordLayout = 'TestReport.docx'; 

but result is always the same,

![image](https://user-images.githubusercontent.com/34686682/45092289-3f589680-b115-11e8-9af7-9c7ad3c83295.png)

RDLC reports have good dataset, but only blank page is shown to the user.
In prev version we used path like this 
RDLCLayout = 'report layout/rdlc layout/ReportName.rdlc';

We tried to move files and to update layout paths (same like for Word above) but nothing changes.

Is something changed, is there additional setup in this version?

Thanks,
Radovan

**Comment by kalberes** [comment]
See bottom remark for #3526

**Comment by radovandokic** [comment]
Thanks!
