### ISSUE TITLE
Can't publish to Business Central

### ISSUE THREAD

**Issue by Dreckiger-Dan** [Microsoft/AL#3571]
We recently switched from developing on a local Nav18 server to developing on Business Central.
When I try to publish the app to the sandbox I get the following error:
`[2018-09-05 12:49:59.05] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.`

The error also shows up after resetting the sandbox.

- AL Extension Version: 
0.16.19969

- Server Version: 
DE Dynamics NAV 12.3 (23918)

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Microsoft cloud sandbox",
            "startupObjectId": 22,
            "startupObjectType": "Page"
        }
    ]
}
```

**Comment by ashik-ivor** [comment]
Unpublish your app from Business central search for "Extensions", and unpublish your app.

Publish your app again.

**Comment by Dreckiger-Dan** [comment]
The app is not listed in the extension menu.

**Comment by ashik-ivor** [comment]
Increase the version in the app.json file

**Comment by Dreckiger-Dan** [comment]
Increasing the Z value of the version by one resulted in the following error:
`[2018-09-05 15:12:44.66] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: 
Mehrere veröffentlichte Erweiterungen passen zu den angegebenen Parameterwerten. Sie müssen weitere Informationen zur verwendeten Erweiterung angeben.`

**Comment by dNsl9r** [comment]
Try to Unpublish it with PowerShell.

**Comment by Dreckiger-Dan** [comment]
I can't use PowerShell since I'm using the SaaS sandbox hosted by Microsoft.

**Comment by ashik-ivor** [comment]
1. Clear the cache from your VS Code
>AL:Clear credentials cache

2. add this "schemaUpdateMode": "Recreate" in the launch.json.

**Comment by Dreckiger-Dan** [comment]
This didn't help either. I get the same message as in my first post.
