### ISSUE TITLE
Reference to symbol 'Address' is ambiguous.

### ISSUE THREAD

**Issue by KoselM** [Microsoft/AL#3572]
![image](https://user-images.githubusercontent.com/43002659/45094177-d6741d00-b11a-11e8-91b1-fd26c34f34cb.png)
![img0001](https://user-images.githubusercontent.com/43002659/45093926-3b7b4300-b11a-11e8-8e92-fb00ef520b8b.png)
![img0003](https://user-images.githubusercontent.com/43002659/45094020-6d8ca500-b11a-11e8-853a-8d5510627960.jpg)

The problem is, in VS Code I just can choose the group and not the field. Is there a solution planned for this problem?

I have found the same problem in the following issue, but there is no solution for this problem. #1472

Table: Contact (5050)
Page: Contact Card (5050)

**Comment by kalberes** [comment]
Where can you only use the group and not the field? In moveafter you specify a list of controls.
What versions of AL are you using?

**Comment by KoselM** [comment]
I am using Version 0.16.19969.
![image](https://user-images.githubusercontent.com/43002659/45139256-73809580-b1af-11e8-89a4-5a0a7b900405.png)
I think the problem is that the field and the group has the same name (Address).

**Comment by StanislawStempin** [comment]
I can no longer reproduce the issue on AL Language 2.0.52543 and application symbols version 13.0.24012.0. 
Please create a new issue if you are still encountering it on the latest bcsandbox-master images.
