### ISSUE TITLE
Page not searchable

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#3573]
Hi all,

We have a page on our range, which is not searchable. We can run it with Action, but not search for it.

Properties are:
UsageCategory = Administration;
ApplicationArea = All;
Editable = false;
LinksAllowed = false;
PageType = List;
SourceTable = AllObjWithCaption;
SourceTableTemporary = true;

As you see, UsageCategory and ApplicationArea have values.

Thanks,
Radovan

**Comment by kalberes** [comment]
Is this a BC based solution, a docker one, Nav 18?

**Comment by radovandokic** [comment]
Sorry for lack of information.
We use docker image 'bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca'. But had same case with previous containers.

**Comment by kalberes** [comment]
Is it also persistent if you uninstall/reinstall the app?
Are your settings in the webclient set to en-ca region?
Are you also providing Caption ML-s for this region in your page? Or labels that would then be generated to this Caption ML
What happens if you switch to en-us, had you been on en-ca? Does search work then?

**Comment by radovandokic** [comment]
I tried all mentioned steps and result is the same.
Here is page code:
`page 23046333 "Attribute Setup"
{
    CaptionML = ENU = 'Attribute Setup',
                FRC = 'Configuration de l''attribut',
                ENC = 'Attribute Setup';
    UsageCategory = Administration;
    ApplicationArea = All;
    Editable = false;
    LinksAllowed = false;
    PageType = List;
    SourceTable = AllObjWithCaption;
    SourceTableTemporary = true;

    layout
    {
        area(content)
        {
            repeater(Control1101766004)
            {
                field("Object ID"; "Object ID")
                {
                    ApplicationArea = All;
                    CaptionML = ENU = 'ID',
                                ESM = 'ID',
                                FRC = 'Code',
                                ENC = 'ID';
                }
                field("Object Caption"; "Object Caption")
                {
                    ApplicationArea = All;
                    CaptionML = ENU = 'Name',
                                ESM = 'Nombre',
                                FRC = 'Nom',
                                ENC = 'Name';
                    DrillDown = false;
                }
                field("Object Name"; "Object Name")
                {
                    ApplicationArea = All;
                    CaptionML = ENU = 'Object Name',
                                ESM = 'Nombre objeto',
                                FRC = 'Nom d''objet',
                                ENC = 'Object Name';
                    Visible = false;
                }
            }
        }
    }

    actions
    {
        area(creation)
        {
            action(Attributes)
            {
                ApplicationArea = All;
                CaptionML = ENU = 'Attributes',
                            FRC = 'Attributs',
                            ENC = 'Attributes';
                Image = Category;
                Promoted = true;
                PromotedCategory = Process;
                Scope = Repeater;

                trigger OnAction();
                var
                    ItemAttribute: Record "Item Attribute";
                begin
                    ItemAttribute.FILTERGROUP(2);
                    ItemAttribute.SETRANGE("Table ID", "Object ID");
                    PAGE.RUNMODAL(PAGE::Attributes, ItemAttribute);
                end;
            }
        }
    }

    trigger OnInit();
    begin
        CLEAR(TempAllObjWithCaption);
        AttributeManagement.CreateTablesList(TempAllObjWithCaption);
    end;

    trigger OnOpenPage();
    begin
        if TempAllObjWithCaption.FINDSET then
            repeat
                Rec := TempAllObjWithCaption;
                INSERT;
            until TempAllObjWithCaption.NEXT = 0;
    end;

    var
        TempAllObjWithCaption: Record AllObjWithCaption temporary;
        AttributeManagement: Codeunit "Attribute Management";
}

`

**Comment by kalberes** [comment]
The issue here seems to be that in order to make a page searchable you have to have execute permission on the table description  and read permission on the table data associated to your source table from the license. In this case the virtual table 2000000058. Which you probably do not have.

**Comment by TimothyWatkins** [comment]
As an example of the described permission set would you expect to see something like this for table xxx?
```
    <Permission>
      <ObjectType>0</ObjectType>
      <ObjectID>xxx</ObjectID>
      <ReadPermission>1</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectType>1</ObjectType>
      <ObjectID>xxx</ObjectID>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>
```

**Comment by TimothyWatkins** [comment]
Sure, understand. We've been having issues with search in our extensions and I saw this post. Our search works intermittently, for some tenants it's ok but others it's not. 
We have only used tabledata permissions, read, insert, modify and delete In our permission sets for our partner object range. We have not been using the executepermission property anywhere. I wonder whether this may solve our strange search result issues?

**Comment by kalberes** [comment]
I have also been investigating some of these intermittent search vanishing issues. As I could see when search was not working there were always multiple versions of the same app published. And for some reason one or more of navigation items were not searchable out of the rest having defined a usagecatgory and an applicationarea.
To see what "items" make part of the search you can open the app that you have created and look for a file called navigation.xml. The permissions mentioned refer to the RunObjectSrcTable.
I cannot say that would solve your problem but it is required.

**Comment by radovandokic** [comment]
Regarding my issue - I used another table as a source and it worked.
