### ISSUE TITLE
[Question] ATT Code Coverage for Extension

### ISSUE THREAD

**Issue by OleTeichmann** [Microsoft/AL#3576]
I want to see how much code our automated tests for our extension covers. But if i start the "Code Coverage" and filter on our object range i get following Error: "Index was outside the bounds of the array.".
Also if i do not filter the "Code Coverage" my whole client crashes if i scroll down the list.
Does anybody have an idea how to fix that?

**Comment by StanislawStempin** [comment]
Code Coverage is not yet supported for AL. It is on our backlog, currently planned to be implemented within the next 6-9 months.

**Comment by OleTeichmann** [comment]
@StanislawStempin that means we can not check if our extension meets the required code coverage for release in the store?

**Comment by jwikman** [comment]
@OleTeichmann  it would also mean that Microsoft can't check that...

**Comment by StanislawStempin** [comment]
Closing as duplicate of https://github.com/Microsoft/AL/issues/1827
