### ISSUE TITLE
Pageextension New Action Shortcut not working

### ISSUE THREAD

**Issue by LAGLSystemcenter** [Microsoft/AL#3577]
- AL Extension Version: 0.12.28462
- Server Version: DK Dynamics NAV 11.0 (23572)

pageextension 50102 "Test SalesHeaderExtension" extends "Sales Order"
{
    actions
    {
        addlast("P&osting")
        {                     
            action(DisplayMessage)
            {
                Caption = 'Display Message AL';
                ShortcutKey = 'CTRL+F5';
                Promoted=true;
                PromotedCategory=Category6;
                trigger OnAction();
                begin
                    Message('Ok'); 
                end;
            }            
        }
    }    
}

![al_code](https://user-images.githubusercontent.com/42537134/45104048-72108800-b131-11e8-966b-beb49c3ce639.PNG)
![al_result](https://user-images.githubusercontent.com/42537134/45104044-7177f180-b131-11e8-98d3-058b18bd0f8d.PNG)

The shortcut do work when made in CAL

![cal_code](https://user-images.githubusercontent.com/42537134/45104045-72108800-b131-11e8-8192-601eb9248d91.PNG)
![cal_result](https://user-images.githubusercontent.com/42537134/45104047-72108800-b131-11e8-80a4-b8144f5dcd9c.PNG)

**Comment by kalberes** [comment]
Does this refer to the RTC client. We may not support that from extensions,

**Comment by LAGLSystemcenter** [comment]
Yes.
What do you mean by 'may not'

**Comment by kalberes** [comment]
May not means that I forgot how it works on the RTC and need to verify it.  Actually it is supported but it is case sensitive. Have you tried with Ctrl+F5

**Comment by LAGLSystemcenter** [comment]
"Ctrl+F5" works 👍 
Thank a lot for your swift answer.
