### ISSUE TITLE
Cannot change Content-Type in http request header

### ISSUE THREAD

**Issue by larswestman** [Microsoft/AL#3579]
In NAV2018 I can do as below and it will post a request using Content-Type 'text/xml;charset=utf-8', but when I do the same in a Docker  container with BC 12.3.23590.23945-SE, the request use 'text/**plain**;charset=utf-8' (which NAV2018 also does without replacing the content type explicity). The result is an "Error 415 Unsupported Media Type" response from the host.

Am I doing something wrong or do we have an issue here?

```
var
    MyHttpClient: HttpClient;
    RequestMessage: HttpRequestMessage;
    ResponseMessage: HttpResponseMessage;
    Headers: HttpHeaders;
    Content: HttpContent;
    XMLRequest: text;
    XML_text: text;
    URL: text;

begin
    RequestMessage.SetRequestUri(URL);
    RequestMessage.Method('POST');
    Content.GetHeaders(Headers);
    Headers.Remove('Content-Type');
    Headers.Add('Content-Type', 'text/xml;charset=utf-8');
    XmlDoc.WriteTo(XML_text);
    Content.WriteFrom(XML_text);
    RequestMessage.Content := Content;
    MyHTTPClient.send(RequestMessage, ResponseMessage);
```

**Comment by Joriek** [comment]
We had the same issue, we had no problem publishing to a NAV2018 CU8 but when we tried on the latest BC we had the same notification. 
To fix this issue, put your Headers.Add function after you do your Content.Writeform function. Our guess is that the Content.WriteFrom does some type of Clear function on the headers, since Text\plain is the default value for the Headers.



var
    MyHttpClient: HttpClient;
    RequestMessage: HttpRequestMessage;
    ResponseMessage: HttpResponseMessage;
    Headers: HttpHeaders;
    Content: HttpContent;
    XMLRequest: text;
    XML_text: text;
    URL: text;

begin
    RequestMessage.SetRequestUri(URL);
    RequestMessage.Method('POST');
    XmlDoc.WriteTo(XML_text);
    Content.WriteFrom(XML_text);

    Content.GetHeaders(Headers);
    Headers.Remove('Content-Type');
    Headers.Add('Content-Type', 'text/xml;charset=utf-8');

    RequestMessage.Content := Content;
    MyHTTPClient.send(RequestMessage, ResponseMessage);

**Comment by larswestman** [comment]
Thanks Joriek! That solved it.

I've confirmed that this works both in NAV and BC:

```
RequestMessage.SetRequestUri(URL);
RequestMessage.Method('POST');
XmlDoc.WriteTo(XML_text);
Content.WriteFrom(XML_text);
Content.GetHeaders(Headers);
Headers.Remove('Content-Type');
Headers.Add('Content-Type', 'text/xml;charset=utf-8');
RequestMessage.Content := Content;
MyHTTPClient.send(RequestMessage, ResponseMessage);
```

**Comment by larswestman** [comment]
@kalberes Should I have closed this or did you want to investigate the differences further? At least from my perspective the case is closed. I know my way around now.
