### ISSUE TITLE
Txt2Al : field and group names on pages

### ISSUE THREAD

**Issue by nicolassaleron** [Microsoft/AL#358]
Hello,

When we use Txt2Al.exe, it converts fields and groups like that :

`field(;"Description") { }
group() { }
repeater() {}`

It creates an error when compiling the AL code because the name is missing.
Could the name be optional or at least, might it possible to fill the name automatically (for fields by using the same value as the source expression) ?

**Comment by StanislawStempin** [comment]
Have you exported the .txt file using the Command=ExportToNewSyntaxSwitch?

**Comment by nicolassaleron** [comment]
I did not.
Thanks it works now
