### ISSUE TITLE
Make functions/event in CU 1535 External instead of Local

### ISSUE THREAD

**Issue by Anna-Gudimova** [Microsoft/AL#3582]
Hello Team,

I need help getting access to the following functions/events in Codeunit 1535 Approvals Mgmt.:

LOCAL [IntegrationEvent] OnPopulateApprovalEntryArgument
![image](https://user-images.githubusercontent.com/10453174/45123978-76cb4100-b11d-11e8-9ad4-6d1e9d48bc88.png)

LOCAL GetLastSequenceNo
![image](https://user-images.githubusercontent.com/10453174/45124027-ab3efd00-b11d-11e8-8135-f024ebc4bb42.png)

LOCAL CreateApprovalRequestForUser
![image](https://user-images.githubusercontent.com/10453174/45124055-cad62580-b11d-11e8-9ec6-7c8451ea7af9.png)

LOCAL MakeApprovalEntry
![image](https://user-images.githubusercontent.com/10453174/45124118-007b0e80-b11e-11e8-9673-8dbcf34e2500.png)

Let me know if it's possible to make those functions/event publisher external.
Thanks!

**Comment by GiorgosPa** [comment]
Hello Anna,

what are you trying to achieve?

**Comment by Anna-Gudimova** [comment]
I'm creating a custom approval process for requisition worksheet and I need to create/modify approval entries for workflow user groups.

**Comment by Anna-Gudimova** [comment]
We have a project for the client who needs this for their functionality. They are going Live in 2 months, so we need it urgently.

**Comment by Anna-Gudimova** [comment]
Hello Microsoft team. When will I be able to see this code released?

**Comment by GiorgosPa** [comment]
Hello @Anna-Gudimova there are already available now in the delevoper preview. They will be in the main product with the April Release

**Comment by dicksonkimeu** [comment]
Any code samples for OnPopulateApprovalEntryArgument ? 

Am doing customer approvals, and i need to add a new document type in approvals table, and also i want to insert document no for my custom table. advice please.

Below code is not now working.

[EventSubscriber(ObjectType::Codeunit, Codeunit::"Approvals Mgmt.",
         'OnPopulateApprovalEntryArgument', '', false, false)]
     procedure PopulateApprovalEntryArgument(
         RecRef: RecordRef; 
         ApprovalEntryArgument: Record "Approval Entry")
     var
         StoreReq: Record "Store Requisition";
     begin
         CASE RecRef.Number of
             DATABASE::"Store Requisition":
                 begin
                     RecRef.SetTable(StoreReq);
                     ApprovalEntryArgument."Document Type" := StoreReq."Document Type";
                     ApprovalEntryArgument."Document No." := StoreReq."Requisition No.";
                     ApprovalEntryArgument.Amount := StoreReq."Expected Total Cost";
                     ApprovalEntryArgument."Currency Code" := StoreReq."Currency Code"; 
                 end
         END
     end;

**Comment by GiorgosPa** [comment]
The event signature is
`LOCAL [IntegrationEvent] OnPopulateApprovalEntryArgument(VAR RecRef : RecordRef;VAR ApprovalEntryArgument : Record "Approval Entry";WorkflowStepInstance : Record "Workflow Step Instance")`

Try this code

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Approvals Mgmt.",
'OnPopulateApprovalEntryArgument', '', false, false)]
procedure PopulateApprovalEntryArgument(
var RecRef: RecordRef;
var ApprovalEntryArgument: Record "Approval Entry";WorkflowStepInstance : Record "Workflow Step Instance")
var
StoreReq: Record "Store Requisition";
begin
case RecRef.Number of
  DATABASE::"Store Requisition":
  begin
    RecRef.SetTable(StoreReq);
    ApprovalEntryArgument."Document Type" := StoreReq."Document Type";
    ApprovalEntryArgument."Document No." := StoreReq."Requisition No.";
    ApprovalEntryArgument.Amount := StoreReq."Expected Total Cost";
    ApprovalEntryArgument."Currency Code" := StoreReq."Currency Code";
  end
end
end;

```

**Comment by dicksonkimeu** [comment]
[image: image.png]

**Comment by muleso** [comment]
Hello,

Below is the error, seems something is wrong. Have you tested it ?

![image](https://user-images.githubusercontent.com/1630443/50088120-2af76000-0213-11e9-9d29-ab4d4fdfb7e7.png)


![image](https://user-images.githubusercontent.com/1630443/50088008-d5bb4e80-0212-11e9-895d-636f881512fa.png)

**Comment by dicksonkimeu** [comment]
Hello,

Am using Dynamics 365 onpremise. What can i do ?

**Comment by GiorgosPa** [comment]
Adding var on the subscriber function parameters should fix the issue

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Approvals Mgmt.",'OnPopulateApprovalEntryArgument', '', false, false)]
procedure PopulateApprovalEntryArgument(var RecRef: RecordRef;var ApprovalEntryArgument: Record "Approval Entry")
var
StoreReq: Record "Store Requisition";
begin
CASE RecRef.Number of
DATABASE::"Store Requisition":
begin
RecRef.SetTable(StoreReq);
ApprovalEntryArgument."Document Type" := StoreReq."Document Type";
ApprovalEntryArgument."Document No." := StoreReq."Requisition No.";
ApprovalEntryArgument.Amount := StoreReq."Expected Total Cost";
ApprovalEntryArgument."Currency Code" := StoreReq."Currency Code";
end
END
end;
```

**Comment by GiorgosPa** [comment]
Unfortunately the Document Type Option Field on the Approval Entry table is not extensible. We are working on making Document type Options extensible. For now you may only choose one of the following values Quote,Order,Invoice,Credit Memo,Blanket Order,Return Order. 

Note that the option value is an integer on the background so you need to align the values of the Document Type option on the Store Requisition table with those on the Document type of the Approval entry table.

**Comment by dicksonkimeu** [comment]
Am using D365 on premise. 

Any short cut for now ?

**Comment by dicksonkimeu** [comment]
Hello,

It has worked thank you, any idea on how i can make the email notifications more descriptive like the ones for purchase orders. Currently, the look like below. Like adding amount, document no etc

_**Purchase Requisition  requires your approval.
--
  | Due Date 12/17/18
  | Store Requisition
Details Created By xx\xxx**_

**Comment by GiorgosPa** [comment]
The email is generated by report 1320 Notification Email take a look

**Comment by dicksonkimeu** [comment]
My production is NAV 2018/ on my dev is BC Central, on production is NAV 2018.

All worked well except this error.

The event OnPopulateApprovalEntryArgument is not found in the target!
