### ISSUE TITLE
HyperLink Reports

### ISSUE THREAD

**Issue by SahilGuptaBS** [Microsoft/AL#3583]
how we can open another report from one report with parameter 
for example, i have a report where some data has already populated month and year wise and on every column there is an hyperlink on month and year. so by clicking on that hyper link i want to open new report  which takes two parameters which is month and  year .

i able to open the report but whenever i click on hyperlink it opens the request page for that report for month and year but i don't want to open request page. i already tried with by removing request page property but doesn't work.
 consider the following screen short for the reference

![image](https://user-images.githubusercontent.com/38460823/45136555-3f62a000-b1c2-11e8-8e93-9ca5378dcefe.png)

**Comment by thomasbarbut** [comment]
Hello,

https://businesscentral.dynamics.com/?report=104&filter=Customer.%22No.%22:%22+asd&company=CRONUS%20USA%2C%20Inc.

https://businesscentral.dynamics.com/?report=ReportID&filter=**TABLE**.**FIELD**:+**FilterSTRING**&company=**CompanyName**

This is a example.
Please confirm if it works.

best regards,
Thomas Barbut

**Comment by SahilGuptaBS** [comment]
it doesn't work ... it gives compile time error in the following line

**http://NAVBC/nav/?report=23065944**&f**ilter=BssiArcbMRRDetailTEMP**

**Comment by StanislawStempin** [comment]
This is a general C/AL development question, not covered by this repository.

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by SahilGuptaBS** [comment]
i have already done this .. thank you
