### ISSUE TITLE
Page not visible in Sandbox, but visible in docker container

### ISSUE THREAD

**Issue by ashik-ivor** [Microsoft/AL#3589]
AL Extension Version: 0.16.19969
Image: microsoft/bcsandbox:us

I am currently unable to find pages in the search bar in Sandbox environment. But when I use the Docker container, I am able to search and view the pages.

Page Properties:
Caption = 'Testing';
DeleteAllowed = false;
InsertAllowed = false;
SourceTable = Customer;
ApplicationArea=All;
UsageCategory=Tasks;

**Comment by kalberes** [comment]
looks similar to issue #3573

**Comment by StanislawStempin** [comment]
Please try granting the proper permissions to the user trying to search for the page. Depending on the SourceTable used by your pages some of them might not be searchable when used in the Cloud due to licensing differences.
