### ISSUE TITLE
Migration Extensions V1 to V2

### ISSUE THREAD

**Issue by YvesDesrumaux** [Microsoft/AL#359]
In extension V1, new fields are part of the "standard" table. Which is not the same with extension v2.
Now we have a tool to convert **objects** from v1 to v2. But is there any thing plan for **data** ?
We have several customers running v1 extension. I hope we will get a solution to migrate them inthe futur ?

**Comment by StanislawStempin** [comment]
Yes, there will be a data upgrade path between Extensions V1 and V2. The details are still being worked through.
