### ISSUE TITLE
Can't financially void an Employee Check

### ISSUE THREAD

**Issue by generaljim99** [Microsoft/AL#3593]
When adding the ability to Financially Void an Employee check in 2018, there is a piece missing in Codeunit 367. See the code below. Lines marked between //SW00-01 ns and //SW00-01 ne should solve the issue. (I like providing solutions as well as problems...) This is in version 11.0.20348

  CheckLedgEntry."Bal. Account Type"::"Fixed Asset":
    WITH FALedgEntry DO BEGIN
      SETCURRENTKEY("Transaction No.");
      SETRANGE("Transaction No.",BankAccLedgEntry2."Transaction No.");
      SETRANGE("Document No.",BankAccLedgEntry2."Document No.");
      SETRANGE("Posting Date",BankAccLedgEntry2."Posting Date");
      IF FINDSET THEN
        REPEAT
          GenJnlLine2.VALIDATE(Amount,-Amount);
          BalanceAmountLCY := BalanceAmountLCY + GenJnlLine2."Amount (LCY)";
          GenJnlLine2."Shortcut Dimension 1 Code" := "Global Dimension 1 Code";
          GenJnlLine2."Shortcut Dimension 2 Code" := "Global Dimension 2 Code";
          GenJnlLine2."Dimension Set ID" := "Dimension Set ID";
          GenJnlPostLine.RunWithCheck(GenJnlLine2);
        UNTIL NEXT = 0;
    END;
  //SW00-01 ns
  CheckLedgEntry."Bal. Account Type"::Employee:
    BEGIN
      IF ConfirmFinancialVoid.GetVoidType = 0 THEN BEGIN    // Unapply entry
        IF UnApplyVendInvoices(CheckLedgEntry,ConfirmFinancialVoid.GetVoidDate) THEN
          GenJnlLine2."Applies-to ID" := CheckLedgEntry."Document No.";
      END;
      WITH EmployeeLedgerEntry DO BEGIN
        //SETCURRENTKEY("Transaction No."); No key for this field in this table
        SETRANGE("Transaction No.",BankAccLedgEntry2."Transaction No.");
        SETRANGE("Document No.",BankAccLedgEntry2."Document No.");
        SETRANGE("Posting Date",BankAccLedgEntry2."Posting Date");
        IF FINDSET THEN
          REPEAT
            CALCFIELDS("Original Amount");
            SetGenJnlLine(
              GenJnlLine2,-"Original Amount","Currency Code",CheckLedgEntry."Document No.",
              "Global Dimension 1 Code","Global Dimension 2 Code","Dimension Set ID");
            BalanceAmountLCY := BalanceAmountLCY + GenJnlLine2."Amount (LCY)";
            IF ConfirmFinancialVoid.GetVoidType <> 0 THEN BEGIN
              GenJnlLine2."Applies-to ID" := CheckLedgEntry."Document No.";
              "Applies-to ID" := CheckLedgEntry."Document No.";
              "Amount to Apply" := CheckLedgEntry.Amount;
              MODIFY;
            END;
            GenJnlPostLine.RunWithCheck(GenJnlLine2);
          UNTIL NEXT = 0;
      END;
    END;
  //SW00-01 ne
  ELSE BEGIN
    GenJnlLine2."Bal. Account Type" := CheckLedgEntry."Bal. Account Type";

**Comment by kalberes** [comment]
This looks like a Nav 2018 issue. Do you have a repro on the newest docker releases. If not please consult with the regular service channels.
See for details the wiki:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
