### ISSUE TITLE
Calling a local procedure from a table triggers an error message

### ISSUE THREAD

**Issue by orjanbrun** [Microsoft/AL#3597]
Calling a local procedure from within a table object, triggers an error message stating that this function is not a member of that object. Changing the procedure to a global resolves the error.

- AL Extension Version: 0.12.20065

- Server Version: SE Dynamics NAV 11.0 (21836)

![2018-09-07 11_00_01-tab78006 metapiactivitylog al - integrationer-kontrollcenter - visual studio cod](https://user-images.githubusercontent.com/43063136/45210665-7c956380-b290-11e8-92b0-5a40d91ec79c.png)
![2018-09-07 10_58_49-microsoft edge](https://user-images.githubusercontent.com/43063136/45210689-8dde7000-b290-11e8-8400-a6e5b21fa7a5.png)

**Comment by kalberes** [comment]
Can you repro the same on the newest docker images.
Else see the WIKI https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
How to handle Nav 2018 issues.

**Comment by orjanbrun** [comment]
Hello Kalman,

Thanks you for feedback!

That I need to find out. I’m quite new to VS Code/AL and have only been working with NAV2018CU5…

Best regards

Örjan Brun
+46 42-400 52 32
​orjan.brun@orango.se<mailto:​orjan.brun@orango.se>
[cid:image002.png@01D448E0.718F5500]<http://www.orango.se/>
Florettgatan 24
SE-254 67 Helsingborg
www.orango.se<http://www.orango.se>

Från: Kálmán Béres <notifications@github.com>
Skickat: den 9 september 2018 15:51
Till: Microsoft/AL <AL@noreply.github.com>
Kopia: Örjan Brun <Orjan.Brun@orango.se>; Author <author@noreply.github.com>
Ämne: Re: [Microsoft/AL] Calling a local procedure from a table triggers an error message (#3597)


Can you repro the same on the newest docker images.
Else see the WIKI https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
How to handle Nav 2018 issues.
