### ISSUE TITLE
Cloud Publishing error 422 "Compilation destination"

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#3599]
We have NAV2018 installed, created Extensions and published to OnPremise installations.
Works Fine.

Now we are signed up for Business Central and has created a Cloud Sandbox.
In VSC created a new project with al-objects.
Symbols downloaded fine.
Compilation is fine.
Creation of package is fine:
Output-message: "Success: The package is created."

But publishing fails with the error:
"The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Udvidelsen angiver en højere kompileringsdestination end tilladt."
(Reason can be translated to something like "The Extension states a higher compilation destination than allowed)
In FAQ I read that for NAV2018, AL Language Extension shall be from the NAV-installation, and for Cloud, AL Extension Language shall be from VS Code Marketplace.
Is this causing the error above ?
If so, how can we develop for OnPremise as well as Cloud ?
Shall we change uninstall / install the AL Language Extension each time we want to publish for one or the other platform ?

- AL Extension Version: 
AL Compiler version 0.12.17091

- Server Version: 
Cloud, Business Central

**Comment by kalberes** [comment]
An extension is compatible with a given server. A NAv 2018 server will not work with the newest released August version of the AL extension for example.
This is the error message you have received. As a not too nice solution you can install the green (experimental VSCode, which is as stable as the blue one to my experience) and install the NAv 2018 AL extension there and use the blue one for the BC development, or vice-versa.

**Comment by naveksa** [comment]
Hi,
Thanks a lot for the reply.
The green experimental VSCode, you are referring to, is that what is "officially" called
VS Code Insiders
which is found here: https://code.visualstudio.com/insiders/
?

**Comment by kalberes** [comment]
Yes

**Comment by naveksa** [comment]
Thanks.
Works fine :-)
