### ISSUE TITLE
The Target Page Job for the extension object is not found.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#36]
I am trying to extend table job using a tableextension.
I am getting attached error referring to "page job" not found etc.
though I guess it is because of the app.json file missing (Am I correct?), it should show error "table job" not found instead of "page job"
![error](https://cloud.githubusercontent.com/assets/23735402/21419344/10aff25e-c84d-11e6-90ec-72d12c8966b6.png)
?

**Comment by esbenk** [comment]
The error message is clearly wrong. It should have been Table Job. 

You guess is right. You need the app.json file to point to the directory with the symbol files for the base-application. When the symbol references are in places you will also get intellisense for the available tables.

First time you type "Ctrl+Shift+B" to build or F5 to deploy, we will create one for you. Just make sure the   "packageCachePath": "../../resources" points to the same folders as the installed samples.

**Comment by pmohanakrishna** [comment]
It would be helpful if you can share the action items taken and when can we get the solution also.

**Comment by esbenk** [comment]
Sorry. The bug is fixed, but the timeframe for next update has a lot of dependencies, and is yet to be determined.
