### ISSUE TITLE
Objects acces in extension v2

### ISSUE THREAD

**Issue by YvesDesrumaux** [Microsoft/AL#360]
We have a v1 extension with many reports available in menusuite (and then in search filed).
Considering the migration in v2, how can me manage to have quite the same acces to those objects ?
This is so user friendly to search the report. I hope that we do not need to create a table to run those objects or a "dummy" page with actions.
Any idea ? Even for th futur ?

**Comment by StanislawStempin** [comment]
In the future we will add a new mechanism for exposing objects in search results. For now you can extend the Navigation Pane or go with one of your suggestions.
