### ISSUE TITLE
Creating a Page with source table Date doesn't showing in the client.

### ISSUE THREAD

**Issue by FrankAuwers** [Microsoft/AL#3600]
- AL Extension Version: 0.12.17091
- Server Version: 11.0.22292.0

Try to use the following subpage on a page, and it will not show up.

page 50000 Test
{
    Caption = 'Test';
    PageType = ListPart;
    SourceTable = Date;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("Pe"; "Period Start")
                {
                    
                }
            }
        }
    }
}

If you change de SourceTable property to Customer and the field to NO. the page will work.

**Comment by kalberes** [comment]
I do not have a repro on the latest docker release for this issue. Probably it is something that got fixed and not merged to the NAv 2018 code base.
See the Wiki.
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions

**Comment by Fkoehnen** [comment]
I was facing the same issue. I wanted to extend the Item Card with a listpart of my own and it did not even show the caption of the part on the extended page.

What I did was set the ApplicationArea Value for all fields in the listpart to 'All'. Now it is showing up correctly on the Item Card.
