### ISSUE TITLE
Part with SubPageLink finds wrong source table field

### ISSUE THREAD

**Issue by maze93** [Microsoft/AL#3602]
Hi all,

We have a problem.
If we have a page extension and then create a part to a factbox and both the factbox source table and the page extension source table have the same field name, the subpagelink will go against the table extensions field instead of the factbox source table field. This means that the part subpagelink tries to go against the wrong table. Please see below images and get back to me if you need more info.

NAV 2018 CU 8 -SE with VSIX 0.12.28462.

The error:
![image](https://user-images.githubusercontent.com/6834090/45218978-a6a74f80-b2a9-11e8-893e-1c5553e3b8b2.png)

The factbox source table with "Order Type" field of type integer:
![image](https://user-images.githubusercontent.com/6834090/45219017-d22a3a00-b2a9-11e8-819d-4bfa3eae3aa5.png)

The page extension source table with the "Order Type" field, here an option:
![image](https://user-images.githubusercontent.com/6834090/45219100-161d3f00-b2aa-11e8-8f27-f5045bf73bff.png)

Thank you.

Rgds from Mattias

**Comment by kalberes** [comment]
I do not have a repro for this on the latest docker image.
For Nav 2018 please see the https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
