### ISSUE TITLE
CheckDocumentType in Table 179 is not public

### ISSUE THREAD

**Issue by Nyryus** [Microsoft/AL#3605]
Hi,
please expose function CheckDocumentType in table 179 Reversal Entry.

Thank you for your help.

**Comment by JesperSchulz** [comment]
I assume you mean in the Italian version, as I can only find that function in that version.

**Comment by Nyryus** [comment]
Yes, the function come from the italian version, but I found that in the daily build of business central.
I assume that it will be present in the release, that why I asked to expose it.

**Comment by JesperSchulz** [comment]
It will be part of the release, yes. But only the Italian one. I will expose that function for you :)
