### ISSUE TITLE
Create a tableextension to add procedure without adding field

### ISSUE THREAD

**Issue by g-franck** [Microsoft/AL#361]
Hello,
It seems that we can not create a tableextension to add a procedure without adding field.

Extension without field:

![ko](https://user-images.githubusercontent.com/30076420/28068667-ccff98aa-6646-11e7-941b-40f353e9dbc1.jpg)

Extension with field:

![ok](https://user-images.githubusercontent.com/30076420/28068723-0ccdc344-6647-11e7-82f1-5a173b305622.jpg)

So, we can not proceed to encapsulation.

**Comment by StanislawStempin** [comment]
Same issue as #362, will be fixed in July Update.
