### ISSUE TITLE
BC RC1 new dialog when trying to connect to an external web service

### ISSUE THREAD

**Issue by ftornero9** [Microsoft/AL#3612]
With the new BC RC1 I got this dialog when try to connect to an external web service using HttpClient, in previous versions that does not happen.

![image](https://user-images.githubusercontent.com/12720964/45252586-3952f780-b359-11e8-94df-67c6328ff7de.png)

If I choose "Allow Always" I get the next message:

![image](https://user-images.githubusercontent.com/12720964/45252593-60112e00-b359-11e8-82a6-f892f4363e26.png)

Is there any way to avoid the first dialog or if that it is not possible how get the Insert permission in the TableDta "NAV App Setting".

Regards.

**Comment by atoader** [comment]
Hi! We are aware of this problem. We have added features that require a license update. The license update is in progress.

**Comment by clausmacali** [comment]
It seems that this new licens we have too wait for more than a week to get this fixed, which seems a very long time, and the release not very good perpared.

**Comment by jwikman** [comment]
> pull an updated NAV 2018 license that contains the object.

Haha, then we can enjoy our weekends looking at a loading browser... I can't believe how slow a site could be. ;-)

**Comment by clausmacali** [comment]
Thanks, and the new licens is working, rember a new thing in extension manger, too configure
