### ISSUE TITLE
Can't upload/deploy extension with PageType = API

### ISSUE THREAD

**Issue by thomasbarbut** [Microsoft/AL#3613]
Hello everyone,

I'm trying to deploy/upload an .app package where PageType=API and I get this error:
Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again.

Strange thing is that it work when using PUBLISH command in the sandbox.

- AL Extension Version: 0.16.19969

- Server Version: US Dynamics NAV 12.3 (23918)

I will be publishing a another table and page. This is just an example.
`page 50113 WLTCustomerAPI3
{
    PageType = API;
    SourceTable = Customer;
    EntityName = 'WLTCustomer';
    EntitySetName = 'WLTCustomers';
    APIPublisher = 'UGP';
    APIGroup = 'WLT';
    ODataKeyFields = "No.";
    APIVersion = 'beta';
    DelayedInsert = true;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
              field("No."; "No.")
              {
                  ApplicationArea = All;
              }
            }
        }
    }
}`

**Comment by kalberes** [comment]
Anything in the server's eventviewer?

**Comment by thomasbarbut** [comment]
Hello, 
it is Business Central. It's on the cloud.  No event viewer.

**Comment by thomasbarbut** [comment]
Hello,

unfortunately I have the same error:
Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again. - Job Id : 0c888067-d120-4ca0-b4ff-c393b767a3a2

Here is the code I've tried according to your suggestion.

page 50113 WLTCustomerAPI3
{
    PageType = API;
    SourceTable = Customer;
    EntityName = 'wltcustomer';
    EntitySetName = 'wltcustomers';
    APIPublisher = 'UGP';
    APIGroup = 'WLT';
    //ODataKeyFields = id;
    APIVersion = 'beta';
    DelayedInsert = true;
    Caption = 'testAPI';


    layout
    {
        area(content)
        {
            repeater(Group)
            {
              field(No; "No.")
              {
                  Caption = 'No';
                  ApplicationArea = All;
              }
            }
        }
    }
}

**Comment by kalberes** [comment]
This exact code works for me on the latest docker image. Can you deploy other type of pages?

**Comment by thomasbarbut** [comment]
It's not working with Live/Production of Business Central(dynamics.com). Try it there. 
Stop trying to reproduce it with the docker image and/or sandbox and you will experience the same error.

**Comment by RobAnderson42** [comment]
Hi Thomas. I'm also having difficulty experiencing the error. We do get an error log for the Job ID that you posted that indicates that the error is happening during validation. Using the API page code that you posted I've created an extension and have tried enabling the PerTenantExtensionCop analyzer in VSCode to validate it and have also tried uploading that extension to Business Central. Neither of those show any errors for me.

Is there anything else that your .app file contains besides the API page? (permission sets, other objects, etc..)
Does your .app file contain any protected IP? If not, would you be willing to post the .app file that you were trying to upload?

**Comment by thomasbarbut** [comment]
Hello Rob,

first of all I'd like to thank you for your feedback.
Below image and zip for the entire project.
![entire project](https://user-images.githubusercontent.com/40474090/45518090-12f9e580-b7b9-11e8-872c-97b390e1e343.JPG)

Here is the entire project folder.
[ALProject15try2.zip](https://github.com/Microsoft/AL/files/2381125/ALProject15try2.zip)

Hopefully you can figure it out.

best regards,
Thomas Barbut.
