### ISSUE TITLE
Synchronize force option required to keep old records and just remove  values for new field

### ISSUE THREAD

**Issue by robertosb** [microsoft/AL#3616]
Hi team,

   Could we have a force option for Synchronize so we get a similar behavior to the on prem version of NAV, where we can force changing a data type for one field and keep the rest of the records, but delete values for this changed field?
"schemaUpdateMode": "Synchronize"

Kind Regards,
Robert

**Comment by StanislawStempin** [comment]
Thank you for the suggestion. We will add it to our long term backlog.

**Comment by atoader** [comment]
Hi @robertosb ! This functionality is available starting with the 2019 Spring release. See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing for more information.
