### ISSUE TITLE
Order of execution for different extensions (extending the same standard object)

### ISSUE THREAD

**Issue by robertosb** [Microsoft/AL#3617]
Hi team,

   Is there a plan that we have a priority property when we publish extensions to control which extension executes first if two different extensions extend the same object?

Kind Regards,
Robert

**Comment by ashik-ivor** [comment]
If extension one has an object id 50000 and is published.
Than, while publishing the second extension with same object id 50000, will give an error.

**Comment by JulienDecottignies** [comment]
What if Object IDs are different but extending the same object ? 
For example, if I have code in OnDelete trigger in each Customer's tableextension I published. Which one is triggered first ? And how to give priority to one or the other ?

**Comment by dNsl9r** [comment]
I'd guess it's the same as subscribing to events - there is no possibility to give priority. Write your code to be safe everything is always working..

**Comment by StanislawStempin** [comment]
We are thinking about this scenario. Let's combine the discussion under suggestion #154
