### ISSUE TITLE
Table Extension with fields Enabled=false

### ISSUE THREAD

**Issue by nicolassaleron** [Microsoft/AL#362]
Hello,

I have the following piece of code with a (strange?) table extension creates only one field that is not enabled.

`tableextension 71000001 ItemExtension extends Item
{
    fields
    {
        field(71000001;"Item Classification Code";Code[10])
        {
            TableRelation="Item Classification".Code;
            Editable=false;
            Enabled=false;
            CaptionML=ENU='Item Classification Code';
        }
    }
}`

At compile time, every works and the package is successfuly created but when we install it, we receive the following error: 
`Error: The request failed with code 422, reason: 
The following SQL error was unexpected:
Incorrect syntax near ')'.`

It seems that a tableextension with only fields where Enabled=false creates that kind of error.
It seems understandable but a clearer error message should be provided.

**Comment by nicolassaleron** [comment]
In fact it seems that if you create a tableextension with just procedures (no new fields), you get the same error message.

**Comment by StanislawStempin** [comment]
This is a known issue, that's fixed in the coming July Update.
