### ISSUE TITLE
My notifications, empty screen.

### ISSUE THREAD

**Issue by ekeukens** [Microsoft/AL#3620]
My notifications:

Minor issue:
If i search for [my ] i can find [My notifications] and [My settings] (in webclient and windows client).
If I open [my notifications] in webclient I only see an empty screen.
If I open [my settings] in web client I can go to [change when i receive notifications].

In the windows client [my notifications] opens this page directly.

So it seems [my notifications] cannot be called directly in the web client. Maybe it's better to remove this option from the departments, because in both webclient and windowsclient you can set this setup through [my settings] page.

See docx.
[My notifications.docx](https://github.com/Microsoft/AL/files/2366573/My.notifications.docx)

**Comment by StanislawStempin** [comment]
Unfortunately this is out of scope of this repo. We are dealing only with AL development issues. You'd need to go through regular support.
