### ISSUE TITLE
Upload Item pictures via an xmlport.

### ISSUE THREAD

**Issue by armela1981** [Microsoft/AL#3629]
Hello there.
I have a request to upload item picture files via an  xmlport for Dynamics BC365 on the cloud.
I created an xmlport extension to do that, however the import command is not supported in Extension development. Code I am using is below.
itemrec.Picture.ImportFile(picturepath);

Any ideas how I can accomplish a mass import of item pictures ?
Thanks

- AL Extension Version: 

- Server Version:

**Comment by qutreson** [comment]
Hi @armela1981, the following issues (#3568, #1825, #3035) are also discussing the import of pictures and files in BC, do you see anything that could help you get started?

**Comment by armela1981** [comment]
Thanks for the info.
I looked at the article you referenced and it seems like a manual process of picture import.
I'm trying to import pictures when I create and insert a series of import records.
Either way, I was going to give it a try, however when I publish the xml port I can't find it in my search box. Is there a trick to get an xmlport in the Search box ?
Here is my AL code.
xmlport 50100 "Import Item Picture"
{
    Direction = Import;
    Format = VariableText;
    //UsageCategory = ReportsAndAnalysis;
    //ApplicationArea = ALL;

    schema
    {
        textelement(Root)
        {
            tableelement(Item;Item)
            {
                XmlName = 'ItemPictureImport';
                UseTemporary = true;
                fieldelement(itemno;Item."No.")
                {
                }
                textelement(picturepath)
                {
                    XmlName = 'pictureval';
                }

                trigger OnBeforeInsertRecord()
                begin
                    IF itemrec.GET(Item."No.") THEN BEGIN
                      //itemrec.picture.
                      //itemrec.Picture.ImportFile(picturepath);
                     // itemrec.Picture.IMPORT(picturepath);
                      
                      //if UploadIntoStream()
                      //File.UploadIntoStream()() needs user input
                      picture.ImportStream(PicInStream,picturepath);
                      itemrec.MODIFY();
                    END;
                    currXMLport.SKIP();
                end;
            }
        }
    }

    requestpage
    {

        layout
        {
        }

        actions
        {
        }
    }

    var
        itemrec: Record Item;
        PicInStream: InStream;

}

**Comment by qutreson** [comment]
Are you using the web client or the Windows client? The web client currently does not support displaying XmlPorts, so you won't be able to see it there. 

XmlPorts are not searchable. The UsageCategory property can only be used on reports and pages (see [Adding Pages and Reports to Search](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-menusuite-functionality)).

**Comment by armela1981** [comment]
Yes, using the web client.
So should I call the xml port from somewhere else ? Like a codeunit or a page action ??

**Comment by armela1981** [comment]
Anyone have any ideas on this please ?

**Comment by GiorgosPa** [comment]
Hello,

You could use an XMLport with no input if you convert your images to Base64Text.

You could then use this code to convert the Base64Text  into image

 ```
textelement(ImageText)
{
    trigger OnBeforePassVariable()
    var
        InStr: InStream;
        TempBlob: Record TempBlob temporary;
    begin
        TempBlob.FromBase64String(ImageText);
        TempBlob.Blob.CreateInStream(InStr);
        Item.Picture.ImportStream(InStr, 'description');
    end;
}        
```

Another solution would be to upload all the images in a zipfile and the use the function CreateNameValueBufferFromZipFileStream from codeunit 705 to get the images into Blob fields. The filename of the picture in the zip is stored in NameValueBuffer.Name field and the Blob for the pictrue in NameValueBuffer."Value Blob" field.

You could add the following code on your Xport implementation.

```
trigger OnBeforeInsertRecord()
var
     InStr: InStream;
begin
    IF itemrec.GET(Item."No.") THEN BEGIN
        NameValueBuffer.SetRange(Name,picturepath)
        if NameValueBuffer.FindFirst() then begin
            NameValueBuffer."Value Blob".CreateInStream(InStr);
            itemrec.Picture.ImportStream(InStr,picturepath);  
            itemrec.Modify();
    END;
    currXMLport.SKIP();
end;

trigger OnInitXmlPort()
    var 
        StreamManagement: Codeunit "Stream Management";
        instr: InStream;
        filename: Text;
    begin
        UploadIntoStream('Pictures','','',filename,instr);
        StreamManagement.CreateNameValueBufferFromZipFileStream(instr, NameValueBuffer);
        NameValueBuffer.
    end;

    var
        NameValueBuffer: Record "Name/Value Buffer" temporary;
```

I hope this helps.

**Comment by armela1981** [comment]
Giorgos
Thank you for your reply. Just got back from Directions NA and need to catch up, but will look at your solution next week.
I wanted to Thank you for your response and will update next week.

Armela

**Comment by GiorgosPa** [comment]
Hi @armela1981, I am sorry didn't notice the function StreamManagement.CreateNameValueBufferFromZipFileStream(instr, NameValueBuffer); has not been released yet. It will be released in the next update. I am not aware of any other way to achieve what you need.
