### ISSUE TITLE
Suggestion: Image Manipulation

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#363]
Hello,

As .Net variables are not available, we frequently need to create images (using mainly System.Drawing.Bitmap and System.Drawing.Graphics) for our customers or for our extensions v1.
For instance,
- creating barcodes,
- creating QR Codes,
- creating on the fly visual data (like progress bar indicator on a sales shipment preparation dashboard)

If we could avoid using Azure functions for that (or reprogramming the .Net class in AL) it would be nice.

**Comment by FSharpCSharp** [comment]
I have already discussed the use of such special cases in another issue. You can find the answer here in the topic [276](https://github.com/Microsoft/AL/issues/276). It is more or less the last 5 replies to the issue.

Fast facts summarized: We will probably have to offer as a partner in future Web services for this is to map these functions.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
