### ISSUE TITLE
error CS0010: Unexpected fatal error -- '㱐銃Ř' 

### ISSUE THREAD

**Issue by AskeHolst** [Microsoft/AL#3636]
Compiling and syncing against the latest docker images we sometimes get strange fatal errors. Restarting the container resolves it, but it would be nice with some more informative errors :-)
We are running the containers on a Windows Server, 8GB ram allocated to each container. I'm guessing the containers run of of resources even though the host has plenty.

```
[2018-09-11 15:02:18.76] The request for path /NAV/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: 
error CS0010: Unexpected fatal error -- '㱐銃Ř' 
```

AL Version: 2.0.42188
BC Version: 13.0.24284.0-W1

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
