### ISSUE TITLE
[Event Request] Table 38 Purchase Header; Buy-from Vendor No. - OnValidate

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3637]
Hi, 
we need an Event in Table 38 Purchase Header in Function Buy-from Vendor No. - OnValidate.

![image](https://user-images.githubusercontent.com/41729653/45368327-9a8dfb80-b5e3-11e8-8dc6-c9e27843caba.png)

With parameters:
VAR purchaseHeaderRL : Record "Purchase Header";
vendorL : Record Vendor

_Thanks in advance_

**Comment by StanislawStempin** [comment]
The event already exists. Please read: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
