### ISSUE TITLE
[Event Request] Codeunit 408 ; Function GetDefaultDimID

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3638]
Hi,
we need an Event with handler pattern in Codeunit 408 Dimension Management in Function GetDefaultDimID.

![image](https://user-images.githubusercontent.com/41729653/45368713-87c7f680-b5e4-11e8-9bba-e852b9623a4a.png)

With Parameters:
VAR DimensionBufferTmp2RL : TEMPORARY Record "Dimension Buffer";
TableIDL : Integer;
NoL : Code[20];
GLSetupShortcutDimCodeL : ARRAY [8] OF Code[20];
VAR globalDimCode1RL : Code[20];
VAR globalDimCode2RL : Code[20];
var isCreatedRL : boolean

_Thanks in Advance_

**Comment by LFlamme** [comment]
In our solution we use Item variants. We have custom variant tables, that we want to use in the Dimensions, therefore we want to insert our own Dimensions, instead of using the ones created here.

**Comment by AlexanderYakunin** [comment]
Does it mean what actually you need possibility to set up Dimensions for Item Variants?

**Comment by LFlamme** [comment]
Well to keep it simple, in this event subscriber we insert into temp table TempDimBuf2 and we also create entries in DimValue (Rec 349). If you need further information i will have to ask the original programmer.
