### ISSUE TITLE
On Prem .Net, yes or no?

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#364]
Someone, I think it was James Crowter, tweeted from Inspire that on prem .Net would be possible in NAV 2018. Does that mean VS Code or does that meen keep using C/Side?

I'm planning the upgrade of our system (bespoke, NAV 2017, on prem) at the end of the year and it would be nice to know which direction to aim at.

**Comment by Gallimathias** [comment]
Look at the discussion in Issue #276 on there we could get a statement from @esbenk. I think this answers your questions ;)

**Comment by StanislawStempin** [comment]
.NET interop in C/SIDE will be available in NAV 2018. 
Depending on the release schedule and other factors, .NET interop might also be available in VS Code but we cannot commit to this yet. It will be available eventually.

However, note that using .NET on-prem will mean that you cannot use the same app for the cloud so we still encourage migration to the new native AL types and utilizing Azure Functions where it makes sense.

**Comment by markbrummel** [comment]
Thanks, yes this pretty much covers it.

I asume you would also be ok if I call a non-Microsoft web server that runs a non-Microsoft programming language? ;-)

The native support for Json allows a differnt kind of dependency-inversion where with the correct API we can have other programming languages used for NAV problems like Machine Learning.
