### ISSUE TITLE
Empty, white page in Business Central

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#3642]
We are developing Extensions including several new tables, pages and functions.
Everything compiles fine i VSC.
Publishing to BC works fine, and we can see our Extensions as Installed in the BC Sandbox, we have set up.
Our searchable pages shows up, when we search for them
BUT
when we open a page (any page from the Extension) all we get is at totally blank, white page just with the page name in upper left corner. No fields, no actions, no nothing.
Have tried to create an extremely simple page for testing, just with two fields (example below).
Same behaviour.
Our BC Sandbox operates with two languages, Danish and US-English.
Same behaviour on both languages.
Please advice

- AL Extension Version: 0.16.19969

- Server Version: Business Central

page 50111 "XYZ Setup"
{
    CaptionML = DAN='XYZ Opsætning',
                ENU='XYZ Setup';
    DeleteAllowed = false;
    InsertAllowed = false;
    PageType = Card;
    SourceTable = "xyz Setup";
    UsageCategory = Administration;
    ApplicationArea = All;

    layout
    {
        area(content)
        {
            group(xyz)
            {
                CaptionML = DAN='XYZ',
                            ENU='XYZ';
                field("Nos.";"Nos.")
                {
                    CaptionML = DAN='Numre',
                                ENU='Numbers';
                    RowSpan = 2;
                }
                field("Description";"Description")
                {
                    CaptionML = DAN='Beskrivelse',
                                ENU='Description';
                }
            }
        }
    }

    trigger OnOpenPage();
    begin
        RESET;
        if not GET then begin
          INIT;
          INSERT;
        end;
    end;
}

**Comment by AndriusAndrulevicius** [comment]
shouldn't there be ApplicationArea on fields set?

**Comment by naveksa** [comment]
Thanks a lot.

Thought it was sufficient to have the ApplicationArea on the page in general.
Adding the property to each field solved the problem.
:-)
