### ISSUE TITLE
[Event Request] Codeunit 57 Document Totals

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3649]
Hi, we need 2 new events in codeunit 57

### 1: SalesUpdateTotalsControls (handler pattern)
![image](https://user-images.githubusercontent.com/41729653/45413549-c3f96680-b679-11e8-879a-3547fd87d7a2.png)
**parameters**
VAR salesHeaderRL : Record "Sales Header"
VAR invDiscExistRL : Boolean

### 2: PurchaseUpdateTotalsControls (handler pattern)
![image](https://user-images.githubusercontent.com/41729653/45413629-edb28d80-b679-11e8-90ab-59ffd5234ba6.png)
**parameters**
VAR purchaseHeaderRL : Record "Purchase Header"
VAR invDiscExistRL : Boolean

_thanks in advance_

**Comment by AndreBreitenbach** [comment]
Please add a third Publisher in Function "CalculateSalesTotals"
![image](https://user-images.githubusercontent.com/40287548/45425428-9de3be80-b699-11e8-9e09-f8be061ac081.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/45425449-b05df800-b699-11e8-851b-32275ee673a2.png)

Thanks

**Comment by qutreson** [comment]
Hi @AndreBreitenbach, it already happened in the past that the comments in an event-requests were forgotten and then not considered. In order to make sure your event request will be considered, can you please log it as a separate issue?

**Comment by AndreBreitenbach** [comment]
Hi @qutreson, ok -> done :) 
I just created a new Github Entry here: https://github.com/Microsoft/AL/issues/3680.
So there is no need to handle my comment.
