### ISSUE TITLE
On Prem - Object ID's

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#365]
When developing with Visual Studio Code for On Prem bespoke projects, which object ID's do you want us to use? Can we use the 50.000 object numbers? Can we also convert the CFMD objects to AL?

How are you going to handle licensing? Are you still going to charge for codeunits? Or can we now add codeunits without adding them to the license?

**Comment by StanislawStempin** [comment]
The current plan of record is that VS Code for on-prem will follow the same licensing rules as C/SIDE. It might change in the future.

**Comment by fvet** [comment]
Any views yet on whether table / page extensions will be free of charge? (Also see #128)

**Comment by markbrummel** [comment]
I kind of have a colored view on the topic.

What I see is a lot of code which is hard to maintain because people are cheap on purchasing codeunits. It would be nice if they would be free. The amount of money Microsoft charges these days can hardly cover the administrative costs anyway.

Another thought would be on Application Builder and Solution Developer licenses. Will they become obsolete?

Application Builder has always been "codeunit designer" and with VS Code everyone can write code and publish it.

Solution Developer costs an arm and a leg and allows customers to add code to financial processes. This can now be easily done with subscribing to events.

Saying in public "this might change" is more or less creating a situation where people will wait with investing until it changes. Nobody wants to spend money that was wasted given new information.

I would already advise agains buying Application Builder or Soludion Developer now.

Page Extensions and Table Extensions MUST be free. Nobody is charging today for adding fields to existing tables.

For this product to be succesful and compete with open source platforms the licensing has to change.

**Comment by epernst** [comment]
Exactly Mark! 

The fact that customers have to pay for new objects is a reason many don't follow development best practices today. If this is not changed, or for example that page and table extensions objects are free, but new table and page objects are not, then a lot of the "bad habits" from the C/SIDE will just continue to exists in VSCode.

Microsoft have a great opportunity to say to customers, "upgrade to NAV "Tenerife" and get the objects for free! Objects created the old fashioned way you still have to pay for." Customers need all the carrots they can get to upgrade faster. 

The only reason I can see for why Microsoft would even care and continue to charge for the objects, is that they use the statistics to show something about how customized their customers are.... ?

**Comment by TheDoubleH** [comment]
I would like to add that I wholeheartedly agree with Marknon this.

I just finished a custom functionality for a customer. Using the philosophy of separate codeunits for separate functions I ended up using 12 codeunits - and I proberbly should have used at least three more - but realistically another 8 or so.

While this functionality is pretty big, it wasn't bigger that I COULD have made one huge GOD object and placed some code on a action items on the page.

2017 is my 20th year working with NAV as a developer. It's hard to teach an old dog new tricks, but the new patters makes this old dog fresh and I embrace them. But a customer can agree - until you tell them that they need to cough up more money for objects to make this the 'right way'.

Just my $0.02

/Henrik
_____________________________

**Comment by waldo1001** [comment]
I agree, but I must say - I have never given the chance to customers nor internal sales to interfere with the design or architecture of any of our solutions.  If someone wants new functionality, I might need a new set of codeunits.  No set, no functionality.  It's part of the deal, part of the contract, part of the budget.  No questions asked..

On top of that, I have had our sales always include a minimum of 100 codeunits on any type of project.  That is usually sufficient.

What I don't agree on is that people will wait to invest for this.  Come on .. it's not THAT big money.  

But again, I do agree on the principle fact that customers shouldn't have to pay for objects.  That doesn't make sense .. and it never has..
I don't pay for the amount of dlls, do I?

Just my €0,02 ;-)

/waldo

**Comment by markbrummel** [comment]
Thanks Waldo.

You and iFacto are not an average representation of our community, and I mean that in a positive way. ;-)

**Comment by Gallimathias** [comment]
I do not believe in ID's and the licensing of individual objects. Apart from this the license a) are not particularly well secured. And b) any SQL developer can give his objects anyway any ID and create as many objects as he likes. Who does know something of SQL, can find more than one guide for this work around ;)
