### ISSUE TITLE
UsageCategory not working for new page in CSide 

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#3654]
I have added new page in C/Side with code and description fields, and on the page level I have assigned ApplicationArea, UsageCategory and Caption:

![image](https://user-images.githubusercontent.com/20359384/45420180-cd8aca80-b689-11e8-9450-d93ced39c3f4.png)

However, I'm still not getting this page when using Search from both Web and Windows client:

![image](https://user-images.githubusercontent.com/20359384/45420256-fca13c00-b689-11e8-9b35-45ce7791d563.png)

I'm using **bcinsider.azurecr.io/bcsandbox:ca** image (NAV Version: 13.0.24285.0-CA).

I can add page using new MenuSuite but that will only show Page from departments on Windows client, not on Web Client.

Any ideas why is this page not working? I can still access it and edit it using direct URL:

http://ivan/nav/?tenant=default&page=23020229&company=CRONUS%20Canada%2C%20Inc.

**Comment by qutreson** [comment]
Hi @ivandjordjevic, after modifying the properties, did you also run `Tools > Build Object Search Index` in C/SIDE?

**Comment by qutreson** [comment]
In order to use this from PowerShell, you can do as follow:
```
$buildSearchIndex = ".\finsql.exe Command=buildobjectsearchindex, Servername=YourServer, Logfile=out.txt, Database=YourDatabase"
cmd /c $buildSearchIndex 
```

**Comment by ivandjordjevic** [comment]
Thanks for the info @qutreson - problem solved.
