### ISSUE TITLE
AL Extension for VS on MAC

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#366]
Hi. I've tried to install AL extension on VS Code on Mac. 
But it doesn't work properly.

1.I'm downloading VS Code for Mac from here: https://go.microsoft.com/fwlink/?LinkID=534106
2.I copy VSIX file from VM: al-0.7.11459.vsix
3.I'm installing AL Extension from Extension -> Install from VSIX

After installing I see only AL: Go command.
When I execute it , it doesn't create .vcode folder with launch.app.
After second try to execute AL: Go, it shows error "command 'al.go' not found".

**Comment by StanislawStempin** [comment]
MAC is not supported yet. The extension only contains windows binaries. MAC support is on our backlog

**Comment by TheDenSter** [comment]
Any indication about an expected timeline? I'm not expecting to do 'real' NAV/D365 development on my MacBook any time soon, but it would be great not to have fire up a VM for code review.

**Comment by Gallimathias** [comment]
@StanislawStempin Is Linux also in the backlog?

**Comment by dennisfrostlander** [comment]
We don't have any specific timeframe for Mac yet. Linux is not yet on the backlog, however, it will depend on how much we would need to change comparing to the Mac version. We are not ready to say yet.

**Comment by tonioknuth** [comment]
Is there a timeline for the release yet ? I do remember seeing a working version at the NAV Tech Days ;)

**Comment by kalberes** [comment]
Still no timeline yet. It is still worked on.

**Comment by dbellingroth** [comment]
@StanislawStempin Are there still any plans to include Mac support in the future or was it canceled?

**Comment by erkie24** [comment]
So when the enchanment project will be done?

**Comment by taddeozanga** [comment]
Same here?! When can we have support for Mac?no news is bad news?
