### ISSUE TITLE
Event Request: Missing OnAfterInsert and OnBeforeInsert events on CU80

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3671]
In Codeunit 80 the following events are missing the function `PostDropOrderShipment`:
- `OnBeforePurchRcptHeaderInsert`
- `OnAfterPurchRcptHeaderInsert`
- `OnBeforePurchRcptLineInsert`
- `OnAfterPurchRcptLineInsert`

Please refer also to #3670. In my opinion the events on sales & purchases should match each other.

**Comment by NKarolak** [comment]
@thpeder The events are missing in D365BC RTM OnPremise. How come?

**Comment by AlexanderYakunin** [comment]
This is correct, more events will be available each month

**Comment by NKarolak** [comment]
Thanks. Does it mean we do not need to create new issues for "shipped" publishers, but still missing in D365BC On-Premise?
