### ISSUE TITLE
Codeunit 6620 (Copy Document Mgt.) function CopyPurchLine scope

### ISSUE THREAD

**Issue by AcererakTheLich** [Microsoft/AL#3677]
Hi,

In our functionality we had a possibility to copy one **Purch. Line** through the copy document functionality.
We did that by adding a function **CopyOnePurchaseLine** to the **Copy Document Mgt. codeunit**. Eventually this function calls existing function **CopyPurchLine**

We want to achieve the same functionality in AL, so we can add our new function to a separate codeunit, but function **CopyPurchLine** is LOCAL.
Can this function be changed to become a global / external function?

**Comment by IhorHandziuk** [comment]
The function CopyPurchLine is supposed to be local and indirectly used in CopyPurchDoc.

The workaround that we can suggest is to use external function CopyPurchDoc (located in the same codeunit 6620) and once you have a copy of the whole doc you can extract the specific purchase line and insert them to the document you need.
