### ISSUE TITLE
Question: Calling SOAP Web Services

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#368]
Hello,

You improved NAV with HttpWebRequest codeunit ; in July Update we have these Xml* data types in AL, and it will really help. But for me it looks still difficult to call a web service.

Let me explain: we have sometimes to deal with complex web services (i.e.: like those provided by shipping agents - Fedex, DHL, UPS or many others). And the definition is provided by a WSDL.

With .Net, I am able to create a .Net library, I register my WSDL and thanks to wsdl.exe, I get all my classes, methods, ... available. Then I can put that assembly in my Add-ins folder and write all my logic in C/AL by referencing .Net objects.

In AL, it looks to me very time-consuming to develop a valid Soap message to send the request and retrieve the response. 

Have you planned to provide a wsdl2al/wsdl2xmlport tool? A new datatype?
Or should we expect to write Soap messages almost manually with XmlPorts/XmlDocument/Text variables in the near future?

Thank you for your help :)

**Comment by mcerdeira** [comment]
I thinks forging XML manually is not viable for a real the real world in 2017. I hope they add more functionality :)

**Comment by FSharpCSharp** [comment]
Yes, I absolutely agree! There must be a better way to interact with webservices. I have already written that with complex Web services with the standard codeunits can come to some problems. There should really be such a kind of NAV wrapper for the webservices, because XML serialization is not hand-on fun.

**Comment by dennisfrostlander** [comment]
Thanks, we recognize this is a valid concern and we need to do further improvements here.

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
