### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post :  **OnAfterDivideAmount**

### ISSUE THREAD

**Issue by Hamdi-Amine** [Microsoft/AL#3686]
Hi,
We need a new event in Code Unit 80 (Sales-Post) to update several amounts ( Add others Tax)  before posting sales documents
Event Publisher : # **OnAfterDivideAmount**

Parameters
![image](https://user-images.githubusercontent.com/23724827/45433151-69750000-b6a3-11e8-955f-17c0501ba80c.png)

Thanks.

**Comment by thpeder** [comment]
The event already exists in a newer version of the product.
