### ISSUE TITLE
Question about File Management in BC

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/AL#3695]
Hello,

I am creating an extension in which I am required to create a text file of data and export it to a pre-defined location on the client's computer (or shared location of their network). Would you please let me know if it is possible in BC as there is very limited file management functionality for Extensions.

Thank you.

**Comment by dNsl9r** [comment]
Only if BC is running OnPrem and you have change the targetlevel in the app.json to internal.
`"target": "Internal"`

**Comment by rdebath** [comment]
In addition you must be using the Windows client as a web browser will not allow the web client direct access to the client filesystem.
