### ISSUE TITLE
Is there a way to hide or replace standard pages?

### ISSUE THREAD

**Issue by chris-amco** [Microsoft/AL#3698]
Is there a way to hide standard pages so that they do not appear in search? Or replace a standard page with a custom page?

Background: I'm trying to convert a localization that introduces a special kind of sales invoice. It uses a boolean flag on the Sales Invoice Header table to mark such invoices. These special invoices must be displayed in their own separate list page. In our C/AL implementation, a new page was added to display the 'special' invoices, and the standard Sales Invoice List page (9301) was modified with an additional filter (SourceTableView) on the boolean field, in order to display only 'ordinary' invoices.

Since page extensions do not allow changes to the SourceTableView property, I cannot simply convert the C/AL implementation.

Therefore I am thinking of replacing page 9301 with a new page that has the required filter. This is feasible for role centers as I can hide the actions which link to the original page and add new actions to link to the new page. But the issue is that the original page will still be visible through search (Departments/Financial Management/Receivables, Departments/Sales & Marketing/Order Processing). Hence I am looking for a way to hide it.

Or are there any other ways to implement a separate list page for the special invoices. I want to avoid going to the length of creating a dedicated table for the special invoices.

Thanks in advance.

**Comment by AskeHolst** [comment]
Would setting a filter in an OnOpenPage subscriber not work?
```
[EventSubscriber(ObjectType::Page, 9301, 'OnOpenPageEvent', '', false, false)]
local procedure OnOpenPage(var Rec: Record "Sales Header")
begin
    with Rec do begin
      FilterGroup := 2;
      SetRange("Special Invoice",false);
      FilterGroup := 0;
    end;
end;
```

**Comment by chris-amco** [comment]
Ah yes, I didn't think of that! It's a simple solution which seems to work fine.
Thank you for your help.
