### ISSUE TITLE
Download symbols VSC localhost

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3699]
Hi guys, I have developed an extension for NAV2017 on my local PC and now I want to test it against the standard application of NAV2017. Therefore I want to download the symbols in Visual Studio Code, which is unfortunately not possible. Do I have to consider something specific? 

This is my launch.json:

![grafik](https://user-images.githubusercontent.com/42337107/45469086-5a846100-b728-11e8-99c8-86b500cbef35.png)

Is it possible to download the symbols, also when you want to test your extension on-prem and not on server?

**Comment by joshua-lehmann** [comment]
@malue19 Extensions in AL are not possible with NAV2017 as far as I know. You need NAV2018 or Business Central version to be able to develope Extensions in AL/VSCode

**Comment by malue19** [comment]
@joshua-lehmann In the meantime, I also found out, that it is not possible with NAV2017, but with NAV2018, that is why I am upgrading my database from 2017 to 2018...

**Comment by malue19** [comment]
Hey guys, I have upgraded my NAV from 2017 to 2018. It is working fine and now I would like to download the symbols in Visual Studio Code to test my extensions...

This is how my launch.json looks like:
![grafik](https://user-images.githubusercontent.com/42337107/45536303-5710d880-b801-11e8-8f54-30cd0bdf625e.png)

And this is my app.json, where I say, which version my NAV is:
![grafik](https://user-images.githubusercontent.com/42337107/45536340-7a3b8800-b801-11e8-808e-571056e43910.png)

When I try to download the symbols I get the following output:
![grafik](https://user-images.githubusercontent.com/42337107/45536376-a0f9be80-b801-11e8-8edd-022001ed62eb.png)

Any ideas what my mistakes are?

**Comment by joshua-lehmann** [comment]
Hi, in an upgraded DB I think there are no symbols you need to manually import them to NAV2018.
Maybe those Links helps you: [](https://blogs.msdn.microsoft.com/nav/2018/02/02/import-symbols-in-new-or-upgrade-databases-with-microsoft-dynamics-nav-2018/)
[](https://blogs.msdn.microsoft.com/nav/2018/01/16/generate-symbols-in-a-modern-development-environment-with-microsoft-dynamics-nav-2018/)

**Comment by malue19** [comment]
@joshua-lehmann Thank you for your help, but I do not know how to handle the different steps in your documentations...
