### ISSUE TITLE
The keyword "not" is not recognized by intellisense

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#37]
When you try using the keyword "not", it does not show up in auto-completion dialog. 

![image](https://cloud.githubusercontent.com/assets/1166791/21424312/636bf3ea-c842-11e6-9954-d7876a9e9b18.png)

**Comment by esbenk** [comment]
Keyword completion is work in progress. There is no keyword completion in the preview, we add it over the next iterations.

We have treated not as an operator keyword, that are (can be) colored differently from the other keywords. The operator keywords are AND|DIV|MOD|NOT|OR|XOR.

Some themes use the same colors for operator keywords and for normal keywords. I'm currently using the "One Monokai" theme where they have the same color.
