### ISSUE TITLE
Extension translation

### ISSUE THREAD

**Issue by nicolassaleron** [Microsoft/AL#370]
Hello,

Have you planned something about translating extensions?

Something like a language file that could be included in and or installed upon an extension?

**Comment by markbrummel** [comment]
I think you can use the same translation files as Extensions V1. I have to dig into it too. Should be good for a video. ;-)

**Comment by StanislawStempin** [comment]
For changing translations on base objects you can use the same translation files as in Extensions V1. For translations on new objects you will need to provide all languages in source as part of CaptionML property.
We are working on a new approach that decouples translations from source code.

**Comment by waldo1001** [comment]
that would make me sooooo happy ;-)
