### ISSUE TITLE
Event Request: C11 - OnAfterDateNoAllowed

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3700]
The event `OnAfterDateNoAllowed` in Codeunit 11 should pass the entire current `Gen. Journal Line` that it is called for, not only `Posting Date`. This also means that the function `DateNotAllowed` should operate on an entire `Gen. Journal Line` and not just a date value. This is because most of the time, it depends on series of factors whether a date is allowed, not only the date value itself.

Btw: there seems to be a typo in the event name.

**Comment by AlexanderYakunin** [comment]
You can use your own check using event OnBeforeDateNotAllowed(GenJnlLine,DateCheckDone); and skip standard check just after. Changing of event name is not possible.

**Comment by hemisphera** [comment]
OK for the name. I just stumbled upon it, does not really matter to me.

For the event: the problem is, that the italian version is calling `DateNotAllowed` directly from within Codeunit 12 Gen. Jnl.-Post Line and the event `OnBeforeDateNotAllowed` therefore does not fire. You could solve this if you move `OnBeforeDateNotAllowed` inside the function `DateNotAllowed`.

Or even better:
Remove the extra call from within Codeunit 12 from the italian version. Checks should generally be done in Codeunit 11 only, and I don't know why this additional check is even present in Codeunit 12.

**Comment by AlexanderYakunin** [comment]
Be default ask goes for W1, I agree IT is different and may contain some redundant code. I will review it and make proper changes if appropriate according you feedback. Thanks!

**Comment by hemisphera** [comment]
Of course you are right. My fault, that I did not check if it's W1 or IT.
