### ISSUE TITLE
Event Request: Table 295 Reminder Header - OnBeforeInsertReminderTextLine

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3701]
Similar to the event `OnBeforeInsertReminderLine` on Table 295 Reminder Header, we need an event `OnBeforeInsertReminderTextLine` that is called for each reminder text line that is inserted, passing us the source `ReminderText` aswell.

Something like this:
````
procedure InsertTextLine (...)
begin
  ...
  IF ReminderText.Position = ReminderText.Position::Beginning THEN
    ReminderLine."Line Type" := ReminderLine."Line Type"::"Beginning Text"
  ELSE
    ReminderLine."Line Type" := ReminderLine."Line Type"::"Ending Text";
  //***
  OnBeforeInsertReminderTextLine(ReminderLine, ReminderText);
  //***
  OnBeforeInsertReminderLine(ReminderLine);
  ReminderLine.INSERT;
  ...
end;

**Comment by AlexanderYakunin** [comment]
This construction looks quite strange, can you somehow use existing event OnBeforeInsertReminderLine here?

**Comment by hemisphera** [comment]
No, I cannot. I have no access to the source `ReminderText` record using that event. I need to copy some fields over from from `ReminderText` to the newly created `ReminderLine`.

Alternatively: 
Add a parameter to `OnBeforeInsertReminderLine`. But I wouldn't know what to pass here. A Record? A RecordRef? Source-Type/Subtype/ID? That would break all other calls to that event, meaning that you would need to pass an empty record or RecordRef or whatever along (making no sense). I really don't see how that would be "cleaner".
