### ISSUE TITLE
 Standard objects modified in extension v1: convert all in one step

### ISSUE THREAD

**Issue by giann85** [Microsoft/AL#3706]
Hi, I have an extension created in the old Extension v1 system, I want to convert it and import it into business central. Standard objects (tables with new fields, page with new fields displayed, and new actions), if I have not misunderstood, we need to create the delta file and then convert to AL format. Is there a guide to convert all modified standard objects in one step?

**Comment by qutreson** [comment]
Hi @giann85, you need to compile your objects, export them, generate the delta files for them and use the txt2al to convert the delta files into AL code.
You can follow the steps here: [The Txt2AL Conversion Tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)

**Comment by giann85** [comment]
the delta files generated by comparing all the standard objects  with all new or modified objects,  are delta files of the whole db: so we have delta files of objects that have not been modified.
 it's a bad job.
i found the way:extract only the standard objects individually, and create a single updated text file (copy and paste on a single file , the new extracted object), so that I can actually compare only the original .AL objects that interest me,  with the .AL modified and new objects.
for this I asked if it was possible to not extract all object from the clean database.
