### ISSUE TITLE
XmlDocument Validate against schema

### ISSUE THREAD

**Issue by jwinberg** [microsoft/AL#3708]
Is there any way that you can validate a generated xml document against a schema in AL?
We have a e-invoicing solution that I'm currently redeveloping as an extension. One feature of this solution was that after generating the xml (from posted invoices) we did a validation of the xml against a schema. This was quite simple, and allowed a user to get an error or message if for some reason the generated xml did not comply to the schema. Usually the reason for not valid xml would be something like the customer address missing and the user could then easily correct this before sending actual .xml invoices to the bank or an intermediate operator (who would otherwise do the exact same schema validation but with all the overhead and costs involved with that).

Would it be possible to add a method for example in XML DOM Management codeunit to do this? Or even better if XmlDcoument had a Validate() method for this.

A workaround would be to do this via azure function I know, but that to me seems like a bad option at least in this case.

**Comment by klktraveloperations** [comment]
Since our solution also requires XML validation, we also support this suggestion.

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
