### ISSUE TITLE
.NET interoperability - Issue using static methods from .NET classes in an extension

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/AL#3709]
Hello all!

I am developing an extension in AL, targeting _on-premise_, where I would like to use functionality from a .NET class. Using 'regular' methods from an object works fine, but as soon as I try to call a _static_ method from a class I am getting the following error:
```
A call to <class>.get_<static_method> failed with this message: 
The type of one or more arguments does not match the method's parameter type.
```

I have also tested this with a class from the standard library, please see the snippet below where I try to use the `System.String.Format` method:

```
 procedure exampleFunction()
 var
     string: DotNet String;
 begin
     string := string.Format('Hello {0}', 'world!');
 end;
```

(_Note_: Of course, for this particular code, there are plenty alternatives for .NET interoperability, but this is just to give a simple example of code that may result in the error)

This will produce the following error message:

```
A call to System.String.get_Format failed with this message: The type of one or more arguments does not match the method's parameter type.
```

Is there something I am doing wrong, or is this a bug in the .NET interoperability in AL?
I have tested my code as well from C/SIDE where I don't get this error message when I try to use the same static method(s).

For your information, here is the version I am using:
- AL Extension Version: 2.0.42188
- Server Version: W1 13.0 (24285)

Hope to hear your thoughts! Thank you in advance for any responses!

**Comment by atoader** [comment]
This has been fixed in the latest release.

**Comment by rvanbekkum** [comment]
Ok, thanks, I will try this with the next release when it is available.

**Comment by rvanbekkum** [comment]
This issue seems to be fixed now in the new builds. I will therefore close the issue.
