### ISSUE TITLE
How to start in VS Code, continue in In-Client Designer, and finish in VS Code?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#371]
Hi, 
For example, I want to create 1 extension, which adds a new field in the customer table, shows it on customer list page, and also I want to add Action.

So I started new AL project, created table extension 
![image](https://user-images.githubusercontent.com/29101017/28181220-77e40db2-6810-11e7-8eba-bb86bb52c3a9.png)

Then I pressed F6 (AL: Publish and open in designer). I've added created a field in Customer list page, but what do next?

![image](https://user-images.githubusercontent.com/29101017/28181312-d9cf7836-6810-11e7-8756-da33325c40ac.png)

After clicking on Stop Designing I can save, or save and download code.
I expect that my VS Code will be updated, but it's not.

Is it a bug, or still under development, or I'm doing something wrong?
Thanks

**Comment by StanislawStempin** [comment]
Once you are done with changes in the Designer go back to VS Code and press F7. It will download the latest sources from the server into the VS Code project.
