### ISSUE TITLE
Event Request: Missing events on Codeunit 5762 Whse.-Post Receipt + Print

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3711]
The Codeunit 5761 contains the events `OnAfterConfirmPost` and `OnBeforeConfirmWhseReceiptPost`. These events are missing on the following corresponding Codeunits:
- Codeunit 5762 Whse.-Post Receipt + Print.
- Codeunit 5766 Whse.-Post Receipt + Pr. Pos.

**Comment by StanislawStempin** [comment]
Reply from the app team: Codeunits 5762 and 5766 use different approach and cannot use same events. If you need specific events here, please describe it.
