### ISSUE TITLE
Error with the function "UPLOADINTOSTREAM" in the Web Client.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#3719]
- AL Extension Version: 2.0.42188

- Server Version: 13.0.24279

Currently there is an error with the RC1 version, which only occurs in the Web Client. If you use the function "UPLOADINTOSTREAM" to load a file into an InStream, you can also select the file. There is also no error when uploading the file. If you want to use the InStream in the program afterwards, the following error appears:

![instreamwebclienterror](https://user-images.githubusercontent.com/22373356/45543942-3bfc9380-b816-11e8-8672-53b50ba764e6.PNG)

However, this only occurs in the Web Client. If you run the classic Windows client, then everything works without problems and errors.

**Comment by atoader** [comment]
@FSharpCSharp could you please provide a snippet of code to reproduce this?

**Comment by FSharpCSharp** [comment]
@atoader 
I'd like to provide an example, but it looks like the problem has been solved by now. I don't know exactly what caused it, but if I now run exactly the same information, it will suddenly work in both clients, without any problems. I didn't change anything over the weekend. Somehow such mistakes frighten me because they suddenly appear and suddenly disappear again. I close the issue with a strange feeling in the belly area.
