### ISSUE TITLE
Write transaction to database through test codeunit..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#3724]
Hello,

Is test codeunit or test function can write the transaction to database. I had some logic to update the values to table in my test function and executing the same through test tool page. I can't see the the values updated even the function ran successfully..

Can you help me on this..

Thanks.

**Comment by dNsl9r** [comment]
what do you mean with "you can't see the values updated"? Do you verify the changes in the testcodeunit? the data is not permanently written to the database

**Comment by srinivasdes** [comment]
Yeah, Data is not written to the database as per the changes in my test codeunit..

**Comment by dNsl9r** [comment]
That's the expected behavior.

**Comment by StanislawStempin** [comment]
That's by design. Test codeunits roll back the transaction not to change the state of the tested system.
