### ISSUE TITLE
Test Libraries availability in Extension

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#3725]
I like the existing libraries (for example: Codeunit 130509 - Library - Sales)
So I can call the function CreateCustomer

Is this allowed to call this function in the Business Central environment (outside our SandBox)?
Or should I copy all these functions to our Test Library?

**Comment by hemisphera** [comment]
I would actually really REALLY love, if the entire Test Toolkit would become available as (one or more) Extensions.

**Comment by ashik-ivor** [comment]
You can use the test libraries in the VS code development.

For docker container, include the test tool kit. And in the tag "test" : "12.0.0.0" in the app.json file.

**Comment by StanislawStempin** [comment]
Test Toolkit will be available as an extension in the future.

For now, follow the steps provided above by @ashik-ivor. Use Docker Container and the IncludeTestToolkit parameter combined with the "test" setting in app.json
