### ISSUE TITLE
Business Central Crashed and will not re open (I think due to FlowField / Filtering)

### ISSUE THREAD

**Issue by James-French** [Microsoft/AL#3726]
- AL Extension Version:  0.16.19669

- Server Version:  12.2

Hello all, I have made a custom page and tried to figure out how to add filters to it, I thought I was on the right track with this code, (and I think I am because before I tried to interact with the filter it was displaying no results because it was blank). But when I clicked on the filter to change it my BC crashed and I am unable to relaunch into the web client through the browser or through my VSCode. I have pasted the code below that I was using to filter.  I also tried removing / commenting out the code, and changing the SchemaUpdateMode to Recreate to try and clear out the issue. I'm still really new to AL Code, and Business Central in general, and hope that someone can assist me with getting back in, and can hopefully tell me what the cause of the error was.

(Also, how do I add a label to my posts so they're easily searchable?)

Thanks, 
James

field(50127; FilterNo; Text[50])
FieldClass = FlowField;
CalcFormula = lookup("Item Charge"."No." WHERE (FilterNo =field("No.")));
 field(FilterNo;FilterNo)
        {
          ApplicationArea = All;
          Editable = true;
          TableRelation = "Item Charge"."No.";
         // LookupPageId = 50120;
        }

**Comment by StanislawStempin** [comment]
Could you please try resetting your Sandbox tenant and trying AL Language version 2.0 from the Marketplace. We had bugs related to FlowFilters that I expect were fixed in the latest release.
