### ISSUE TITLE
Multilanguage with xlf files - Different basic language than en-US

### ISSUE THREAD

**Issue by MarkusWinBI** [Microsoft/AL#3727]
Hi All,

I have a question about translation via xlf files. I created big parts of the extension by using Text2AL, which is creating "illegal" syntax: "The multilanguage syntax is being deprecated. Please update to the new syntax.". As there are more than 9.000 constants, texts, fields,... I thought it would be a good idea to do so. So I invested half a day to do the correct syntax. My problem is now: 

My extension is for a german customer, therefore they want the german labels from their old solution be the base for translation to en-US (the result auf auto-translated en-US to de-DE), so all my "captions" and "labels" are german now.

Every build of my extension is now destroying my base xlf file by setting the source language to en-US. I did not find a property or option to set this to de-DE. 

Thanks in advance for your help
Markus

**Comment by Kowa63** [comment]
Regarding the first issue, if you use a recent docker container, txt2Al will work differently than before. Then all CaptionML parts will be removed from the source code if you use Convert-Txt2Al from navcontainerhelper.
Setup as in the picture in my post here:
http://www.msdynamics.de/viewtopic.php?f=17&t=34503&%2A#p133942

**Comment by BartPermentier** [comment]
For your 2nd part I don't think they will help you as it is best practice to develop your app in enUS.

**Comment by MarkusWinBI** [comment]
> 
> 
> Regarding the first issue, if you use a recent docker container, txt2Al will work differently than before. Then all CaptionML parts will be removed from the source code if you use Convert-Txt2Al from navcontainerhelper.
> Setup as in the picture in my post here:
> http://www.msdynamics.de/viewtopic.php?f=17&t=34503&%2A#p133942

Thanks very much! This will help for next customer. :-)

**Comment by MarkusWinBI** [comment]
> 
> 
> For your 2nd part I don't think they will help you as it is best practice to develop your app in enUS.

Thanks for your reply. Obviously they don't. ;-)
Of cause you are right. But how good can an auto-translated NAV be compared to a "native" german NAV? I think this is the same for the belgian.

Translation seems to have a very low priority, as even their described way to translate NAV via AL is only working for english and other languages without "funny characters". Neither german nor french or spanish possible as AL only accepts ANSI files and turning "special characters" into question marks.

**Comment by Kowa63** [comment]
> Neither german nor french or spanish possible as AL only accepts ANSI files and turning "special >characters" into question marks.

That seems to be the same code page issue we have here: #3928
Were the files converted to code page 850?
