### ISSUE TITLE
Txt2Al conversion error - CONST('') in property converted to const('') in AL

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/AL#3733]
Dear AL team,

A little backstory: I had developed a page object (a list page) in an extension where I tried to apply a filter to only show records for which the `Code` field is equal to `''`. So what I tried to do is setting the `SourceTableView` property to the following:
```
SourceTableView = sorting (Tag, Code) where (Code = const (''));
```
However, I noticed that no filter was applied to the page, instead it showed all records.
I didn't see any particular problem with the propery-setting directly, but after some time I noticed that the property should instead be set to:
```
SourceTableView = sorting (Tag, Code) where (Code = const (''''''));
```
(i.e., using `''` to escape each single quote in the string; if you know an easier way, please feel free to share!)

For developing my extension I made use of the output of the Txt2Al conversion tool as a starting base for multiple new object definitions in AL.
I noticed that the Txt2Al tool suggests to convert `CONST('')` from the 'classic' object to `const ('')` in the AL object definition. This seems to be a bug in the Txt2Al conversion tool.

This also applies to other object types and similar properties, for example the `DataItemTableView` property for a dataitem in a report object. This applies to the Txt2Al tool that ships with W1 13.0 (24285).

Hope you can look into this! Thank you in advance for any responses!

**Comment by rvanbekkum** [comment]
Another related error: 
When you have the DataItemTableView property in a report dataitem set to `CONST()`, then the Txt2Al tool will convert this to `const('')`.

**Comment by qutreson** [comment]
Hi @rvanbekkum, can you try reproducing it on the latest developer preview from the version 14.x? If it still reproduces, can you share with us some C/AL code that would reproduce this issue after being converted to AL?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
