### ISSUE TITLE
Event Request Codeunit 2500 function UnpublishNavTenantExtension and/or UninstallNavExtension

### ISSUE THREAD

**Issue by thomasbarbut** [Microsoft/AL#3735]
Hello,

there are certain moments when we need to change records within Business Central when we install an extension.
For example, one of my extension needs to change standard Invoice and Credit Memo report.
This can be done with Installation Codeunit, that's clear to me.

But when uninstalling I'd like to set them back to standard Reports.
For example Codeunit 2500 function UnpublishNavTenantExtension and/or UninstallNavExtension.

best regards,
Thomas Barbut

**Comment by AlexanderYakunin** [comment]
We cannot take this ask as event request as it require additional considerations. Please ask same on Ideas site to submit this ask properly.
