### ISSUE TITLE
Cannot modify field standard to add trigger

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/AL#374]
Trigger OnValidate is not support ?

layout
   {
      // Add changes to page layout here
      modify("Qty. to Ship")
      {
         trigger OnValidate();
         begin
            //to do something
         end;
      }
   }

**Comment by StanislawStempin** [comment]
You can use OnBeforeValidate or OnAfterValidate.  
In general in these cases use Intellisense to see the list of available triggers. You can do it by pressing [Ctrl] + [Space] after the trigger keyword

**Comment by chiecnhanco** [comment]
Thanks
