### ISSUE TITLE
Function Expose Request

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#3740]
Hey Guys, 
We are making our first baby steps toward extension development. While converting our solution to AL extensions we made a list of LS functions that we would like to like to be exposed as external functions. Here's the list:

Codeunit 130000 Assert 
(all functions)

Codeunit 130509 Library - Sales
CreateCustomer
CreateSalesperson

Codeunit 130512 Library - Purchase
CreatePurchHeader
CreatePurchaseLine
CreateVendor
CreateVendorNo
CreateVendorWithVATBusPostingGroup
CreateVendorWithVATRegNo
FindVendorPostingGroup

Codeunit 131000 Library - Utility
CreateNoSeries
CreateNoSeriesLine
CheckFileNotEmpty
GetFieldLength
GetNewLineNo
GetGlobalNoSeriesCode
GenerateRandomCode
GenerateRandomCodeWithLength
GenerateRandomText
GenerateRandomAlphabeticText
GenerateGUID
UpdateSetupNoSeriesCode

Codeunit 131004 Library - Variable Storage
Enqueue
DequeueText
DequeueInteger

Codeunit 131007 Library - Report Dataset
AssertElementWithValueExists
LoadDataSetFile

Codeunit 131009 Library - Setup Storage
Save
Restore

Codeunit 131300 Library - ERM
CreateCountryRegion
CreateGenBusPostingGroup
CreateGeneralPostingSetup
CreateGeneralPostingSetupInvt
CreateGenProdPostingGroup
CreateGLAccount
CreateGLAccountNo
CreateGLBudgetEntry
CreateGLBudgetName
CreateGenJournalBatch
CreateGenJournalTemplate
CreateNoSeriesCode
CreateVATBusinessPostingGroup
CreateVATPostingSetup
CreateVATPostingSetupWithAccounts
CreateVATProductPostingGroup
FindGeneralPostingSetupInvtFull
FindPaymentMethod
FindPaymentTerms
FindPaymentTermsCode
FindVATPostingSetup
FindVATPostingSetupInvt
SetGeneralPostingSetupMfgAccounts
SetInvRoundingPrecisionLCY

Codeunit 131902 Library - Service
CreateReasonCode

Codeunit 132201 Library - Inventory
CreateInventoryPostingGroup
CreateInventoryPostingSetup
CreateItem
CreateItemNo
CreateItemCategory
CreateItemCharge
CreateItemChargeNo
CreateItemJournalTemplate
CreateItemJournalBatch
CreateItemJournalBatchByType
CreateItemJournalLine
CreateItemUnitOfMeasure
CreateItemUnitOfMeasureCode
CreateItemVendor
CreateUnitOfMeasureCode
PostItemJournalLine
UpdateGenProdPostingSetup
UpdateInventorySetup
UpdateInventoryPostingSetup

Codeunit 132202 Library - Manufacturing
CreateBOMComponent

Codeunit 132207 Library - Assembly
SetupItemJournal

Codeunit 260 Document-Mailing
EmailFile 

Codeunit 397 Mail
NewMessageAsync 

Codeunit 6224 XML DOM Management
AddElement
FindNode
FindNodesWithNamespaceManager

Codeunit 7500 Item Attribute Management
FindItemsByAttribute

Table 472 Job Queue Entry
SetReportParameters 

Table 485 Business Chart Buffer
SetValue

- AL Extension Version: 0.12.17720
- Server Version: 11.0.21441

Best Regards,
Gintautas

**Comment by JesperSchulz** [comment]
Most of these functions are already exposed in the most recent version of Business Central, which will be released shortly. Some of the requested functions could not be exposed, as they either contain .NET parameters (which aren't supported) or are unsafe (e.g. are using files rather than streams).
