### ISSUE TITLE
Unable to convert from Microsoft.Dynamics.Nav.Runtime.NavXmlText to Microsoft.Dynamics.Nav.Runtime.NavXmlElement

### ISSUE THREAD

**Issue by georgii01** [Microsoft/AL#3743]
Hi,

The problem described here https://github.com/Microsoft/AL/issues/796 appeared again

The build RC1 13.0.24285.0 (SE)

In case of execution the code directly from web client - **OK**
In case of SOAP call error message: **System.Web.Services.Protocols.SoapException:** 'Unable to convert from Microsoft.Dynamics.Nav.Runtime.NavXmlText to Microsoft.Dynamics.Nav.Runtime.NavXmlElement.'

**Comment by atoader** [comment]
Hi! Can you please provide code to reproduce the issue?

**Comment by atoader** [comment]
I will assume that this problem does not reproduce anymore and close this issue. Feel free to reopen the issue and add steps to reproduce the problem on the latest build.
