### ISSUE TITLE
Error: The package could not be created. 

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3744]
Hey guys, is it possible to create a package of an extension, where errors still exist or do I have to fix all errors first? 

In some objects I will extend some standard objects, like tables and pages: also in the extending objects I got errors, like that the standard object is missing, this is also a reason, why I cannot create a package. How should I solve this?

**Comment by malue19** [comment]
Hey @thpeder,
thank youn for answering. Now I have the symbols for my standard objects. 

Unfortunately I have a new issue: I created three different extensions and for one extension I have downloaded the symbols, now I get some new errors, because some objects are missing other objects, which are in the other two extensions. That is why I made them dependent from each other with the property "dependencies" in the app.json, but I get the error "...failed with code NotFound. Reason: No published package matches the provided arguments." after trying to download the symbols.

![grafik](https://user-images.githubusercontent.com/42337107/45613660-52e5f480-ba67-11e8-92ad-aff74f4f16e5.png)

So the first extension is not able to find the other ones...

**Comment by dNsl9r** [comment]
You have to add the .app files of the dependencies to the alpackages folder of your new, third app.

**Comment by thpeder** [comment]
If the two other extension are published to the server then you can invoke the VS code command: AL: Download Symbols with will download the .app package of the other extensions so you have the necessary symbol information to build the extension.

**Comment by malue19** [comment]
@thpeder thepeder What do you mean with published? I thought I can only publish my extensions after downloading the symbols?

**Comment by dNsl9r** [comment]
@malue19 sorry for late reply, easiest way is as described by @thpeder.
