### ISSUE TITLE
SMTP AddAttchement not supported

### ISSUE THREAD

**Issue by kapoorsidhant** [Microsoft/AL#3745]
Hi,

What will be the workaround for SMTP Addattachment.
![image](https://user-images.githubusercontent.com/43333750/45610717-8e3dee80-ba7a-11e8-9997-fa19665ca3ca.png)

**Comment by davidwCP** [comment]
You should be able to use the below as a replacement. You'll just need to load your image into a Blob first (which it looks like it is), then create an InStream from that to be passed into function:

`SMTP.AddAttachmentStream(AttachmentInStream,AttachmentName);`
