### ISSUE TITLE
OnAfterSubstituteReport request extra parameters

### ISSUE THREAD

**Issue by Pieterheinevdm** [Microsoft/AL#3748]
Can the OnAfterSubstituteReport" publisher in report:44:"ReportManagement" be extended with the parameters RecordRef; RunMode; RequestPageXml?

Use case: 
For example if country_code is 'RU' use substitute report id with 50001 else don't substitute the reportid.
or if print use reportid 50001 if RunMode=execute use 50002.

**Comment by rovelgoenne** [comment]
This is a good suggestion. We also need an additional parameter (RecordRef or RecordID will be fine). We substitute a report with another report depending on a field in the record. To select the right substition we need the record.

**Comment by StanislawStempin** [comment]
I'm not sure if this is what you're reffering to but the SubstituteReport already has all the parameters that you mentioned. See if the following works for your case:

![image](https://user-images.githubusercontent.com/23653165/47488380-8d9c3300-d844-11e8-85b0-717a59664432.png)

**Comment by rovelgoenne** [comment]
Thanks for the answer. That is exactly what we need.
