### ISSUE TITLE
Cannot set InitValue for field with data type = Duration

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/AL#375]
ex:
field(22;"Process Duration";Duration)
    {
      InitValue=60 days;
    }
The property 'InitValue' can only be set if the property 'Type' is set with any of the values of :'BigInteger,Boolean,Code,Date,DateFormula,DateTime,Decimal,Integer,Option,RecordID,Text,Time,TextConst'

**Comment by dennisfrostlander** [comment]
Yes, the InitValue for the Duration type is not supported. 
Do you see this as a big problem for your scenarios? 
We did not see this used often therefore the addition of the new syntax (like 60 days, 2 minutes, etc) keeps being postponed.
