### ISSUE TITLE
Add new Fields on Item Tracking Lines

### ISSUE THREAD

**Issue by RamboAngello** [Microsoft/AL#3750]
Hi, it's possible to add events for add new fields on Item Tracking Lines?

Like this post.  

https://www.olofsimren.com/add-fields-to-the-item-tracking-lines/

Regards.

- AL Extension Version: 

- Server Version:

**Comment by AmolSalvi** [comment]
If required events available then you can...

**Comment by RamboAngello** [comment]
No existing events to do this...

**Comment by StanislawStempin** [comment]
Please request specific events to be added by Microsoft.
