### ISSUE TITLE
[Event Request] CU5988 "Serv-Documents Mgt."

### ISSUE THREAD

**Issue by BenjaminHochstetter** [Microsoft/AL#3751]
Please add Events into the CU5988 "Serv-Documents Mgt." (there are no Events in NAV 2018 CU4).
Into the following functions:
- [External] Initialize(VAR PassedServiceHeader : Record "Service Header";VAR PassedServiceLine : Record "Service Line")
`OnAfterInitialize(PassedServiceHeader, PassedServiceLine); With Sender; Global Var Access`
- [External] PrepareInvoiceHeader(VAR Window : Dialog "In Use"): `OnAfterPrepareInvoiceHeader(ServHeader, ServInvHeader, Window);`
- LOCAL PrepareInvoiceLine(VAR passedServLine : Record "Service Line"): `OnAfterPrepareInvoiceLine(passedServLine, ServInvLine);`
- [External] PrepareCrMemoHeader(VAR Window : Dialog "In Use")
`OnAfterPrepareCrMemoHeader(ServHeader, ServInvHeader, Window) With Sender; Global Var Access`
- LOCAL PrepareCrMemoLine(VAR passedServLine : Record "Service Line")
- [External] Finalize(VAR PassedServHeader : Record "Service Header")
- LOCAL FinalizeHeader(VAR PassedServHeader : Record "Service Header")
- LOCAL PrepareShipmentLine(VAR passedServLine : Record "Service Line";passedWarrantyNo : Integer)
- [External] PrepareShipmentHeader()
- LOCAL PrepareDocument(VAR PassedServHeader : Record "Service Header";VAR PassedServLine : Record "Service Line")
- PostDocumentLines(VAR Window : Dialog "In Use")

**Comment by AlexanderYakunin** [comment]
Please be more specific with events description. Please also consider that many events already implemented.
