### ISSUE TITLE
[Event Request] Codeunit 5005396 Print Document Comfort

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3754]
Hi,

we need an Event in Codeunit 5005396  in Function IssuedDeliveryRemindPrint.
![image](https://user-images.githubusercontent.com/41729653/45623221-e0850c80-ba86-11e8-9a38-03fee2e7d0db.png)

**parameters**
VAR dACHReportSelectionsRL : Record "DACH Report Selections"
issuedDelivReminderHeaderL : Record "Issued Deliv. Reminder Header"

_thanks_

**Comment by AlexanderYakunin** [comment]
I think you can simply update report selection setup to print another report.
