### ISSUE TITLE
"Allow Always" does not appear to be working 

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#3755]
#3720 and #3612 don't to seem have mention of an additional issue. 

We use an external service for self monetization and also to use an API for one of our features. 

Choosing "Allow Always" when prompted by “The extension is making a request to an external service. Do you want to allow this request" does not appear to stick. In some cases it's necessary to accept multiple times, and then the calls fail anyways (return a 500, never hitting the external service). 

The only way to get it to work is to choose "Allow Once," which is causing the user to have to accept many times. Or they choose "Allow Always" and it looks like our app isn't working. 

Will the "Allow Always" feature work soon? Is there an idea of when? If not is there a workaround so we can avoid this dialogue and having the setting block our features?

**Comment by atoader** [comment]
Hi @strophanthus ! The option does not stick due to the licensing issue mentioned in one of the bugs. This prompt only happens in a sandbox environment which is meant for testing. Can you try updating your license? After the license update, inserting a record into the NAV App Setting table should work without raising any permission errors.

**Comment by strophanthus** [comment]
Hello. I updated the VM and can now see the "Configure" option, enabling HTTP calls from that screen works. Thanks!

**Comment by chavansachin20** [comment]
Today, I updated my container with new docker container and facing same issue.

current version : 
![image](https://user-images.githubusercontent.com/5293496/46417654-c1a19e00-c747-11e8-927a-5596e42d0684.png)

message which i recived when we try to use our app : 
![image](https://user-images.githubusercontent.com/5293496/46417581-9f0f8500-c747-11e8-838e-cc6de7ef06af.png)

**Comment by strophanthus** [comment]
I understand that for this error you require an updated license. 

The "enable HTTP" option is in the Extension Management page. If you click the ... on your app's card, and go to Customize, there is a toggle there.

**Comment by chavansachin20** [comment]
As of now Configure option is not present under Extension page, so used this blog and updated Runtime in app file as '1.0'

Blog : https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions

**Comment by atoader** [comment]
@chavansachin20 have you updated your license?

**Comment by chavansachin20** [comment]
@atoader , I'm using NAV 2018 dev license which I've used for App v1 & V2 development .

**Comment by chavansachin20** [comment]
**Configure option visible only when you use latest License.**
 
follow below steps: 
- Generate new license 
- Create new container : use same license while creating a docker container 
- Open NAV client > search for extension management > select your app > Click on manage > select Configure > tick "**Allow HttpClient Requests**" 

![image](https://user-images.githubusercontent.com/5293496/46850479-bf0f0a80-ce11-11e8-8fa2-35ac54306ca5.png)
