### ISSUE TITLE
File is not support ?

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/AL#376]
The type or method 'Object' cannot be used for 'Extension' development.
The type or method 'File' cannot be used for 'Extension' development.
The type or method 'Open' cannot be used for 'Extension' development.
The type or method 'CreateInStream' cannot be used for 'Extension' development.
The type or method 'Close' cannot be used for 'Extension' development.
The type or method 'SaveAsExcel' cannot be used for 'Extension' development.
The type or method 'Read' cannot be used for 'Extension' development.
The type or method 'ClearLastError' cannot be used for 'Extension' development.
The type or method 'GetLastErrorText' cannot be used for 'Extension' development.
The type or method 'Copy' cannot be used for 'Extension' development.
The type or method 'Erase' cannot be used for 'Extension' development.
The type or method 'Create' cannot be used for 'Extension' development.
The type or method 'CreateOutStream' cannot be used for 'Extension' development.
The type or method 'Len' cannot be used for 'Extension' development.
The type or method 'Seek' cannot be used for 'Extension' development.
The type or method 'TextMode' cannot be used for 'Extension' development.
The type or method 'WriteMode' cannot be used for 'Extension' development.
The type or method 'Exists' cannot be used for 'Extension' development.
The type or method 'CreateMessage' cannot be used for 'Extension' development.
The type or method 'AppendBody' cannot be used for 'Extension' development.
The type or method 'ServerTempFileName' cannot be used for 'Extension' development.
The type or method 'ClearLastError' cannot be used for 'Extension' development.
The type or method 'Download' cannot be used for 'Extension' development.

**Comment by StanislawStempin** [comment]
File APIs are not available yet. Replacement that enables temporary files is on our backlog.

**Comment by Avanti05** [comment]
So there is no timeframe for functions to up/download files from client (e.g. payment files and account statements etc.)?

In case of Object you should be able use AllObjWithCaptions if thats what you need..

**Comment by dennisfrostlander** [comment]
No, no specific timeframe yet.

**Comment by StanislawStempin** [comment]
We will use #507 for tracking this work. Closing this issue.
