### ISSUE TITLE
[Question] Display notification after install

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#3767]
Hi,

After the installation of my extension, I want to check if some datas are present in a table, and if not, display a notification at the end of the installation. 
As NavApp Table  is not available in extension development, I now have no solution to do something after the (re)installation of my app.

In the Install CodeUnit, I can only fill some data, check and do some controls but it's not possible (in my knowledges) to warn the user that some informations are missing.

If I want to open a page which will shows the user the informations he has to give in order to set up the extension, I can't too (At the moment, he has to go by himself to the configuration page)
Also, I saw that in the documentation of the Install Codeunit:
![image](https://user-images.githubusercontent.com/29598240/45688462-b4828d80-bb51-11e8-9665-7ce2c33be74f.png)

> Setup 'welcome back' messaging for next user access.

But instead in the vscode console, by adding an error message, I'm not able to display any message for now.

Is there a way to do that ? Is someone have some "tips" to do that, or these kind of feature will be possible in the future ?

Thank you a lot !

- AL Extension Version: 0.16.19969
- Server Version: W1 12.3 (23945)

**Comment by BartPermentier** [comment]
I subscribe to the Role Centers to check this and show a notification (Allow tthe notification to be disabled).
For example:
![image](https://user-images.githubusercontent.com/24684493/45695372-8f961680-bb61-11e8-9cb4-288007bcb703.png)

**Comment by JulienDecottignies** [comment]
Yes thank you ! I've tried to do the same but it's not directly linked to the installation just done. I mean, when the user has finished the installation, he has to go back to the role center (or all the other pages we subscribed to) to be warned something is missing. 
But I think for now, it's this kind of tip we have to use to warn the user.

**Comment by JulienDecottignies** [comment]
(Sorry for double-post)

How do you fire the OnOpenPage Event of the Role Center ? 

I've tried to display a notification I firstly insert in MyNotifications table and enabled it
![image](https://user-images.githubusercontent.com/29598240/45756579-810f3400-bc21-11e8-992c-38219efc6911.png)

But nothing appears on the page. 
Any advices ?

**Comment by BartPermentier** [comment]
Are you inserting it directly into the table or are you using the design patern? I don't think directly inserting would work.
https://community.dynamics.com/nav/w/designpatterns/284.in-context-notifications

My vscode extension ALToolbox has a snippet that generates the design pattern to add it to my notifications table:
![image](https://user-images.githubusercontent.com/24684493/45803196-435dea00-bcb9-11e8-8925-15836c5fa9f0.png)

**Comment by JulienDecottignies** [comment]
Hi,

I inserted it directly ! It's probably why it doesn't work ! Thanks for your sample :)
