### ISSUE TITLE
AL:Go in July update sets wrong locale in app.json

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#377]
When you create a new workspace with AL:Go! in the July update, you have to correct locale setting in app.json to 'W1'. (See also https://github.com/Microsoft/AL/issues/367)

Please update GenerateAppJson function in contentService.json to include W1 instead of US.

**Comment by dkatson** [comment]
Yes, this was described in https://github.com/Microsoft/AL/issues/367

**Comment by ajkauffmann** [comment]
Issue 367 is about existing projects and got labels 'question' and 'bydesign'.

I'm referring to new created projects in July update. Those should get W1 instead of US, because of that 'bydesign'. But they don't. For that, the code that creates the app.json needs to be changed. That is what I tried to tell. I'm sure @StanislawStempin will know what I'm talking about. I guess the change was just overlooked.

For those who want to have this in July update, follow these steps:

1. open `C:\Users\vmadmin\.vscode\extensions\Microsoft.al-0.7.11459\out\src\services\contentService.js` in VS Code
2. go to line 64 and change US into W1
3. save the file, close and reopen VS Code

All new projects, initialized with AL:Go! will now have W1 instead of US.

**Comment by StanislawStempin** [comment]
As this was just a temporary change in the July Update we will not be fixing it for August update.
