### ISSUE TITLE
[Function Expose] Table 290 VAT Amount Line: GetVATAmountLCY and GetECAmountLCY

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#3771]
We need would like to call these two functions, in table 290 VAT Amount Line, for a report:

* GetVATAmountLCY
* GetECAmountLCY

For some reason the other "GetXXLCY" functions in the table (GetBaseLCY, GetAmountLCY) are marked as external, but not these two.

Note: I checked the visibility of these functions on a docker with version 12.3.23590.23945 (ES)

**Comment by salgiza** [comment]
Hi @StanislawStempin , have these changes (new events & function visibility) stopped to apply to the monthly BC updates? 

Last info I had, these kind of changes applied to both the "next" BC release, and to the "small" monthly updates. However, I just deployed a 13.1.25341.0 (ES) docker image and a 14.0.25897.0 (ES) one, and I can see that the functions are marked as External in the later (14.0.x) but not the former (13.1.x).

I'm asking this because we are waiting for this change in order to publish a couple of apps in AppSource, and we have no idea whether we will be able to do it this month, next month, in April...

**Comment by StanislawStempin** [comment]
These have never automatically applied to the minor monthly releases (although the applicaiton team might have manually ported a lot of them). See here for more details:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

**Comment by salgiza** [comment]
@StanislawStempin Thanks. I can't remember where we got that info from, but we thought that the SaaS updates did include the new events that were being added to the platform. 

What's the protocol Microsoft expects us to use for this kind of situation? (we can't publish an app to AppSource because an event is in the next preview but not in the stable release) 

Should we open a partner support request, or is there any other channel that we should use?

**Comment by StanislawStempin** [comment]
Yes, please open a support request. It should all be described in the link above.
