### ISSUE TITLE
AL Code Analyzer Possible Overflow assigning text

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#3772]
According to #2291 this should be solved, but we are getting the same warning using the AL Language 0.16.26913 extension (included in the august docker image).

![Screenshot](https://user-images.githubusercontent.com/6630306/45697508-41cfdd00-bb66-11e8-965f-017a4f0f7de9.png)

**Comment by AskeHolst** [comment]
It is solved in the August devpreview, just tested it.

**Comment by salgiza** [comment]
@AskeHolst What AL Language extension version are you using? 
(Just to confirm whether you are using a newer preview of the AL Extension, or I'm hitting a different condition that triggers the bug).

**Comment by AskeHolst** [comment]
AL Extension 2.0.41872

**Comment by salgiza** [comment]
Ok, so it is solved in the "next" docker, but not in sandbox docker (I just checked with a newly deployed VM).

My mistake then, I thought AL bugs where solved in the monthly releases, just as events were added.

Thanks for your help, @AskeHolst !
