### ISSUE TITLE
Error Deploying Extension on NAV 2018 CU6

### ISSUE THREAD

**Issue by fibbert** [Microsoft/AL#3777]
Hi Everyone,

I have code that is deploying to my devlopment version of NAV 2018 CU8, and I am trying to deploy to a NAV 2018 CU6 environment.

Symbols download fine. Compiles without errors.  Hello World deploys.  The Client Web URL in settings opens into the client without problem in chrome.  Everything looks fine.

I get this error:
**_The request for path /localhost/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type._**

app.json
{
  "id": "062f2f86-685f-44bf-881f-b9847e982771",
  "name": "xxxx",
  "publisher": "Sabre Limited",
  "brief": "xxxx",
  "description": "xxx",
  "version": "2.0.0.0",
  "privacyStatement": "xxxx",
  "EULA": "",
  "help": "",
  "url": "http://www.sabrelimited.com",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 57300,
    "to": 57399
  },
  "target": "Internal",
  "showMyCode": true

- AL Extension Version: 0.16.19969
- Server Version: US Dynamics NAV 11.0 (22292)

**Comment by qutreson** [comment]
Closing this issue as this repository aims at fixing issues for the latest preview of the AL extension and this is a NAV 2018 issue and it should be handled by customer support.

For more information, you can read about our processes and approach here:
- https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
- https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

**Comment by fibbert** [comment]
I identified the cause of this issue, which occurs in both BC and NAV 2018

It is possible to compile the following code:


> tableextension 50100 tabxCustomer extends "Customer" 
> {
>     fields
>     {
>         modify(Name)
>         {
>             trigger OnAfterValidate()
>                 txtSomeText: Text;
>             begin
>                 txtSomeText := 'foo';
>                 Message(txtSomeText);                
>             End;
>         }
> 
>     }
>     
> }

You may note that there is no VAR keyword in the variable declaration after the Trigger statement in the Modify. This compiles but will not deploy with the error message shown in the original post.

This should be identified as a defect
