### ISSUE TITLE
[Question] Enable access to all installed extensions

### ISSUE THREAD

**Issue by sirhc101** [microsoft/AL#3780]
Hello there,

We're currently working for some kind of a C/SIDE to AL Upgrade Toolkit. It works pretty good, but we tried to build a generic solution which we can use in different environments and here we got some trouble.

The requested scenario is the following. We're trying to upgrade a customer solution (NAV 2009) and of course we've a lot of individual fields in standard tables and customer tables in id range 50000 - 99999. We upgraded all this and now we have a "up and running" new version with custom fields and tables.

To keep the database clean now we want to transport the customizations AND the data into a "customer app/extension". Therefor we developed a small data migration tool, consisting of two apps. The first app is backing up the data into a buffer table. After this we delete all custom fields and tables in C/SIDE, install the customer individual app/extension to get the fields (table extensions) and tables back in AL and finally install the second data migration app. This app is restoring the data from the buffer table back to the original field nos. and tables, this time provided by the AL app/extension.
Of course we need some dependencies in the second app to make sure, that we can access the buffer table of the first app (that's not the problem) and the newly created custom fields and tables from the customer app/extension.
This is where we are in trouble a bit. The initial plan was to provide a generic toolkit (backup app and restore app) to backup and restore data, which can be used (without any modifications) for different projects and environments. But this isn't working because every customer app/extension of course will get a unique AppId's and we need to create a specific "dependencies" entry in the app.json. Because the app is designed on base of RecordRef and FieldRef the specific symbols of the dependent customer app/extension are not important. So it would be nice if it would be possible to use some kind of a wildcard instead of AppId, etc. in app.json

Is there any way to use wildcards or enable access to all installed app's/extensions, right now? Would it be possible to add this kind of feature?

I know in our current scenario we're talking about NAV 2018 but the problem still remains in BC that's why I adress this in here.

Thanks a lot!
Chris

**Comment by StanislawStempin** [comment]
We are planning to optimize moving data from C/AL tables in the base into AL tables in extensions. I will use this issue for tracking this topic.

To your specific approach - is there a reason why you cannot iterate over all possible IDs using RecordRef and detect which tables exist?

**Comment by pborring** [comment]
We built support for moving data from C/SIDE tables to AL/extensions and tables between extensions, see
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-table-fields

There are some limitations to supported scenarios, and above does not completely address this GitHub entry, however, given age of ask and overlap I will close this entry, and refer to http://aka.ms/bcideas for additional asks.
