### ISSUE TITLE
Excel import in Business Central

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#3782]
Trying to create an Excel import function to our Extensions.
Previously we used the function:
ExcelBuf.OpenBook(ServerFileName,SheetName);

That function is still used by MS in NAV standard.
However in the Cloud Sandbox that function is not allowed.
Error:
"The type or method 'OpenBook' cannot be used for 'Extension' development."

What to do ?

- AL Extension Version: 
0.16.19969

- Server Version: 
BusinessCentral Cloud Sandbox

**Comment by ftornero9** [comment]
I don't know if in your BC version the function is external but in the RC3 version you can use:

      OpenBookStream

Regards.

**Comment by naveksa** [comment]
Thanks,
I will try that solution.
K.R.
