### ISSUE TITLE
App Role Centers in Business Central

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#3783]
We have created RoleCenter pages for our Extensions.
The pages compile without problems in VSC and we can publish to the Cloud Sandbox.
However the RoleCenters does not show up as available RoleCenters to be selected in "My Settings".

We have added ApplicationArea to the page and the parts and actions in the page, but with no effect.

Are we missing some property to be able to see (and select) our App-based RoleCenters in BC Cloud ?

- AL Extension Version: 
0.16.19969

- Server Version: 
Business Central Sandbox

**Comment by Kowa63** [comment]
One possible cause would be that the basic setup routine of your app has yet not been run.

**Comment by OleTeichmann** [comment]
Have you created a Profile with your RoleCenter ID and a User Group with the "Default Profile ID" filled?

**Comment by naveksa** [comment]
Thanks.
Of course - a Profile was missing.
Just a little confusing, that it asks for a Profile ID and actually means a profile.
