### ISSUE TITLE
AL0296: The type or method 'Permission Set' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by fibbert** [Microsoft/AL#3784]
I am getting the error from the subject.

In reading back through issues, this appears to have been fixed as far back as january, but it is failing to compile as "Extension" - compiles as "Internal" but then I get another error deploying which is a separate issue.

I want to have users select alternate permission sets vs: the ones I am installing if they so wish.

- AL Extension Version: 0.16.19969
- Server Version: US Dynamics NAV 11.0 (22292)

        field(50001;"SBR ETO Planner Code";Code[20])    
        {
            CaptionML = ENU='ETO Planner Permission Set Code',
                        ENC='ETO Planner Permission Set Code';
            TableRelation = "Permission Set"."Role ID";
        }
        field(50002;"SBR ETO Designer Code";Code[20])
        {
            CaptionML = ENU='ETO Designer Permission Set Code',
                        ENC='ETO Designer Permission Set Code';
            TableRelation = "Permission Set"."Role ID";

**Comment by qutreson** [comment]
Hi @fibbert, the Permission Set table has been enabled for "Extension" deployment. However, I don't think it made into NAV 2018. The AL extension that you are using now is the one from the VS Code marketplace which should be used with Business Central. Your server and your extension are not in sync, this is why you are getting an error when trying to deploy as your server relies on an older version of the AL compiler which does not allow using the Permission Set table with target Extension.

Closing this issue as this repository aims at fixing issues for the latest preview of the AL extension.

For more information, you can read:
- https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
- https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
