### ISSUE TITLE
Enhancement: Add the same result after using "t*" and "Ctrl+Space"

### ISSUE THREAD

**Issue by DmitryKatson** [microsoft/AL#379]
Hi, when we use a snippet, we get all the structure, but when we use Ctrl+space we get the only function without structure. Ctrl+space is very useful, but without structure, it is a headache.

For. example:
_tcaptionml_
`CaptionML = ENU = 'englishText',
                                  languageShortcut = 'languageText';`
_CaptionML_
`CaptionML`

**Comment by dennisfrostlander** [comment]
Thanks for the suggestion, added to the backlog.

**Comment by nndobrev** [comment]
Hi, we are closing these is probably has been noted in the backlog, please check if you can still reproduce the old behaviour on the latest version and reopen if needed.
