### ISSUE TITLE
bug - txt2al - Converting Codeunit Delta Files doesnt work

### ISSUE THREAD

**Issue by snc-kmanson** [Microsoft/AL#3791]
- AL Extension Version: CU8

- Server Version: CU8

As far as I know, the txt2al converter is supposed to work by creating delta files from modified and original objects and converting those into AL files. In my current test, i added a function to the Codeunit 80. Afterwards the Codeunit was exported via Powershell and the new syntax tag. 

The same was done to an original Codeunit 80. These 2 txt files were used in the compare Objects Powershell command to create a single delta file. 

The new delta file includes the new function and is run through the conversion tool. 

Sadly nothing happens. No Errors and no file. 

The Files used are attached and the NAV Version used is CU8 for the Objects and NAV Environment. Both the CU 8 and CU9 Version of the txt2al Tool were tried to the same effect.
[Modified CU80 NAV 110.txt](https://github.com/Microsoft/AL/files/2400074/Modified.CU80.NAV.110.txt)
[Chronus CU80 NAV 110.txt](https://github.com/Microsoft/AL/files/2400075/Chronus.CU80.NAV.110.txt)
[COD80 Delta File.txt](https://github.com/Microsoft/AL/files/2400080/COD80.Delta.File.txt)

**Comment by OleTeichmann** [comment]
Maybe because in AL there is nothing like a Codeunit Extension Object?
