### ISSUE TITLE
Page Extension actions not appearing on TestPage of extended page

### ISSUE THREAD

**Issue by AddEleven** [Microsoft/AL#3792]
When extending a page with a new action, the action does not appear when trying to invoke it on a TestPage variable in a given Test Suite.
This seems to have occurred only in the below version.

- AL Extension Version: 2.0.46000
- Server Version: 13.0.24629.0-W1

```
pageextension 50000 TestExtension extends "Contact Card"
{
    
    actions
    {
        addafter("Apply Template")
        {
            action(TestAction)
            {
                Caption = 'TestAction';
                ApplicationArea = All;

                trigger OnAction()
                begin
                    message('HelloWorld');
                end;
            }
        }
    }
}


codeunit 50001 "TestCodeunit"
{
    Subtype = Test;
    TestPermissions = Disabled;

    [Test]
    procedure TestPageExtensionAction();
    var
        ContactCardTestPage: TestPage "Contact Card";
    begin
         ContactCardTestPage.TestAction.Invoke();
    end;
}
```

"message": "'TestPage Contact Card' does not contain a definition for 'TestAction'",
"source": "AL",

**Comment by dNsl9r** [comment]
Do you have defined the dependency to your Base App in your Test App?

**Comment by AddEleven** [comment]
Yes. Have tried with multiple Apps/Test apps as well.

**Comment by atoader** [comment]
We fixed this issue yesterday. It should be out soon.
