### ISSUE TITLE
[Function expose] : Some function in Codeunit and Report, Page, Table

### ISSUE THREAD

**Issue by giann85** [Microsoft/AL#3797]
Hello,
I am developing my extension package, but receiving errors that many methods can not be used in the development of extensions.

When I used target internal in app.json it worked.

But if I use it internally it will not work in D365, so please look into this and make it possible to get those features available,

Type | ID | Method
-- | -- | --
  |   |  
Report | 25 | SetAccSchedName
  |   | SetColumnLayoutName
  |   | SetFilters
  |   |  
Report | 29 | SetOptions
  |   | SetUpdateExistingWorksheet
  |   |  
Report | 35 | TransferDocEntries
  |   | TransferFilters
Report | 292 | SetSalesHeader
  |   |  
Report | 6529 | TransferDocEntries
  |   | TransferRecordBuffer
  |   | TransferFilters
  |   |  
Report | 6699 | SetSalesHeader
  |   | ShowDocument
  |   |  
Codeunit | 1001 | PostInvoiceContractLine
Codeunit | 5632 | GenJnlPostLine
Codeunit | 6529 | FindTrackingRecords
Codeunit | 12101 | CalculateWithholdingTax
  |   |  
Page | 47 | ShowPrices
  |   |  
Table | 49 | FillInvPostingBufferPrimaryKey

Thanks & Regards
Gianfranco

**Comment by giann85** [comment]
hi, are there any news?

**Comment by IhorHandziuk** [comment]
Thank you for your request and sorry for delayed reply. We are now looking at functions you suggested to be external. Probably all of them or almost all of them will be external in the next release. 
I will write about our decision here soon.

**Comment by IhorHandziuk** [comment]
Thank you, requested functions will be external in the next update.

**Comment by giann85** [comment]
Great news. Thanks for the support. Good job.

**Comment by rstefanetti** [comment]
hi,
the table functions listed below are "internal" and not work in Dynamics 365 Online; would it be possible to set them to "external"?  They are useful for reports.

Table 36.FindVATExemption
Table 291.GetTDDAdr
Table 23.GetTDDAdr
Table 5050. GetTDDAdr
Table 79. GetTDDAdr
Table 291. GetTDDAdr

Thanks for support
Roberto Stefanetti

**Comment by IhorHandziuk** [comment]
Hello Roberto, thank you for the request, but can you, please, create a new issue (since we automatically track the status of Github issues in our internal system)
