### ISSUE TITLE
Extend "Res. Availability Lines" not possible?

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#3806]
Hi everybody,

I'm currently trying to extend the "Res. Availability Lines" by two new fields from Resource.
For this i need to access the variables "Res", "NetAvailability" or AmountType for example.
Actually this is not possible because there are no events, which i can subscribe to and and the variables "are not accessable due its protection level".

I think we need a fix for this...

Best regards,

Hendrik

**Comment by qutreson** [comment]
Hi @hendrik244, if you feel that you are missing some events in some base app objects, can you open a new issue specifying where you want the events to be called in the code, in which object and with which signature. You can find a lot of examples of event requests in this repo. Just look for issues that are tagged with the label `event-request`.

**Comment by StanislawStempin** [comment]
Just to add to the above reply, the event requests should now be filed on: https://github.com/Microsoft/ALAppExtensions

**Comment by hendrik244** [comment]
[](https://github.com/Microsoft/ALAppExtensions/issues/26)

**Comment by hendrik244** [comment]
I just created a event request on the recommended repository: https://github.com/Microsoft/ALAppExtensions/issues/26
