### ISSUE TITLE
Dynamic Editable property doen't work.

### ISSUE THREAD

**Issue by FrancoOrazio** [Microsoft/AL#3809]
Hi,
I create a new Page in NAV Extension, in this page some of the fields use a global variable to set the editable property dinamically.  
This is the Esample :
![cattura](https://user-images.githubusercontent.com/43472330/45881398-53ee8d00-bdab-11e8-8605-1fe9ca16c586.PNG)

In field's definition i've used globals variable to set the editable property : 
![image](https://user-images.githubusercontent.com/43472330/45881470-90ba8400-bdab-11e8-87fc-8c35b3577ea0.png)
![image](https://user-images.githubusercontent.com/43472330/45881500-a6c84480-bdab-11e8-9c45-49bacf2f092e.png)

This code works fine in Web Client but it doesn't work on my local Nav Client.

**Comment by OleTeichmann** [comment]
Maybe you have to set [InDataSet] for the variable. Like `[InDataSet] gBlnEditableDischargeLocation: Boolean;`

**Comment by FrancoOrazio** [comment]
Thanks for the reply but also in this way it does'nt work on my local client.

**Comment by thpeder** [comment]
Hi @FrancoOrazio,
You should be using the OnAfterGetCurrRecord trigger instead, then it should work.
