### ISSUE TITLE
Text [250] in tables and data record lengths

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#381]
A topic that is extremely important for the future is that the maximum length of text [250] is within tables. This limitation is nowadays neither timely, nor really meaningful, because the SQL server can deal clearly with significantly longer character strings. Up to now, overlapping text has to be split into several texts, or stored in a BLOB field, which greatly reduces the performance.

In this context, the maximum data record length in tables should also be considered. There are very large tables, which nowadays have to be split into several tables because the number of fields is not sufficient. This limitation is also ancient, and also no longer contemporary.

The same applies to the number of keys and indices. How will this be handled in the future? An SQL performance optimization is anyway no longer in the future, if everything runs with the help of extensions. In any case, the number of possible keys should also be increased significantly.

**Comment by dennisfrostlander** [comment]
Thanks, we will take it up for a discussion with the platform teams.

**Comment by Gallimathias** [comment]
I would say this fits together with this discussion @FSharpCSharp #227 :)

**Comment by FSharpCSharp** [comment]
@Gallimathias Yes in a certain way is true. But from my point of view, it is no longer up-to-date to save texts in a BLOB field (SQL-side as image). These times should really be over. Especially since the SQL server can really do more, and you should use BLOB fields only for very specific purposes.

**Comment by Gallimathias** [comment]
This is exactly what I wrote in my comment in this issue below :D. I always have to smile, I think we will be good friends here @FSharpCSharp 

> __Gallimathias commented on 13 Jun Issue #227:__
> 
> I believe BLOB to use for these purposes is not the right way. The 250 character limit is silly, I believe we are all agreed.
> 
> For me, a blob is a compressed byte array and not a text variable.
> 
> My alternative would be to use a nvarchar(max) in the background if the length property of the text variable is not set.
> 
> A) could be parsed in the background text instead of in NavText in string
> B) string has a limit of 2Gb and nvarchar(max) has a limit of 2GB
> C) The adjustment effort is worthwhile

**Comment by bvbeek** [comment]
This would be nice, please add this a.s.a.p. Microsoft!

**Comment by atoader** [comment]
The maximum length of text fields has been increased to 2048 starting with the 2019 Spring release.
