### ISSUE TITLE
How to use unlocked methods?

### ISSUE THREAD

**Issue by GHDevNav** [Microsoft/AL#3810]
Hi,

These methods should be unlocked by referring to this ticket: https://github.com/Microsoft/AL/issues/3099

```
    var
        PaymentRegistrationMgt : Codeunit "Payment Registration Mgt.";
    begin
        PaymentRegistrationMgt.ConfirmPostLumpPayment(Rec);
        PaymentRegistrationMgt.ConfirmPost(Rec);
    end;

```

With a Sandbox and Visual Studio Code with AL Language v 0.16.19969 we still have the same issue for using it:

[AL] The type or method 'ConfirmPostLumpPayment' cannot be used for 'Extension' development.

and

[AL] The type or method 'ConfirmPostLumpPayment' cannot be used for 'Extension' development.

If this issue comes from AL Language version, we didn't find how to update it.

Do you have a solution for this issue?

Thank you.

**Comment by qutreson** [comment]
Hi @GHDevNav, based on the issue you are referencing, these methods should have been exposed with the August preview (version 2.0.41872). If you want to have access to them, you should then update your extension to this version. You can read more about it in the August 2018 blog post below:
https://blogs.msdn.microsoft.com/nav/2018/08/31/developer-preview-august-2018/

**Comment by GHDevNav** [comment]
Hi qutreson,

With the newest version ( 2.048254), it seems that both methods are still unaivalable:

Consol Output:

The type or method 'ConfirmPostLumpPayment' cannot be used for 'Extension' development.

The type or method 'ConfirmPost' cannot be used for 'Extension' development.

**Comment by qutreson** [comment]
Hi @GHDevNav, I can also reproduce it. I am labeling this issue as Event-Request then.

**Comment by qutreson** [comment]
Hi @GHDevNav, the functions being exposed or not actually only depends on the symbols that you have downloaded from your server (and not from you AL version number). Which version of the server are you running? (To find it, go into the System Information page in BC).

According to #3099, your server build revision number should be at least 23754 if you want these functions to be available.
