### ISSUE TITLE
[Event Request] CU83 "Sales-Quote to Order (Yes/No)"

### ISSUE THREAD

**Issue by BenjaminHochstetter** [Microsoft/AL#3811]
Please add an Events in `CU83 "Sales-Quote to Order (Yes/No)"` in the `OnRun(VAR Rec : Record "Sales Header")` Trigger.
- before the `SalesQuoteToOrder.RUN(Rec);`
- and after the `SalesQuoteToOrder.GetSalesOrderHeader(SalesHeader2);`
- and to skip the Confirmation Dialog before `IF GUIALLOWED THEN`
```
// ... ---------- Start
OnBeforeQuote2Order(Rec);
// ... ---------- End
SalesQuoteToOrder.RUN(Rec);
SalesQuoteToOrder.GetSalesOrderHeader(SalesHeader2);
// ... ---------- Start
OnAfterQuote2Order(Rec, SalesHeader2);
// ... ---------- End
COMMIT;
// ... ---------- Start
IF NOT SalesProcessMdtr.BeforeQuestionOnRunQuote2Order(Rec, SalesHeader2, OpenNewInvoiceQst) THEN
// ... ---------- End
```

We whant to implement some additional user interaction some checks before and some modifications after.

Thanks in advanced!
Benjamin

**Comment by GaryFrostick** [comment]
I agree with this as it is a common requirement to perform checks before converting  quote.
If would be good to have an event at the end of the function as well.
