### ISSUE TITLE
Debugger: Last Error

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#3816]
Maybe I overlooked it, but is there or will there be in VSCode AL debugger a similar feature as in C/SIDE debugger to show the last error message again?

**Comment by lvanvugt** [comment]
Clear. Already on the Backlog?

**Comment by kalberes** [comment]
This has been implemented AFAIK.

**Comment by lvanvugt** [comment]
> This has been implemented AFAIK.

Hi @kalberes, can you point out how?
