### ISSUE TITLE
Groups and Labels without fields in a page are not shown on the client

### ISSUE THREAD

**Issue by crisnicolas** [Microsoft/AL#3818]
I have created an Assisted Setup kind of page for an extension I am developing.

The page has some groups with labels inside but with no fields. This is to be able to write text to the user.
Neither groups nor labels have the ApplicationArea property available.

The text in the captions on those groups and labels is not shown on Business Central.
How do I have to define those texts to be able to see them in the page?

Here an example of one of those groups:

                group(FirstPage_Text1)
                {
                    Caption = '', locked = true;
                    label(Text1_Label1)
                    {
                        Style = Strong;
                        Caption = 'Welcome to the Extension Setup',
                    }
                }

**Comment by qutreson** [comment]
Hi @crisnicolas, as suggested by @OleTeichmann, you should use the [InstructionalText property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-instructionaltext-property).

```
page 50120 MyPage
{
    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                InstructionalText = 'This text will be displayed';
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/31541422/45998337-cbba0180-c0a2-11e8-9bd6-fc2e914ae8dd.png)
