### ISSUE TITLE
formatting is breaking after F7

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#382]
When we publish and design app (F6) and then download code back (F7) all formatting is breaking.
Screenshot **before** publish:
![image](https://user-images.githubusercontent.com/29101017/28267276-083ae0fe-6b02-11e7-9696-9d45bedf9fd1.png)

Screenshot **after** code download:
![image](https://user-images.githubusercontent.com/29101017/28267339-608d3c8e-6b02-11e7-9dc7-a494d9572108.png)

**Comment by thpeder** [comment]
We were made aware of this bug in #327 and as noted in there, it will be fixed in the next update.
