### ISSUE TITLE
Need Events to customize Workflows

### ISSUE THREAD

**Issue by nareshbandariD365** [Microsoft/AL#3821]
Need events for below codeunits to customize workflows:
1. 1520, 
2. 1521,
3. 1535 .

**Comment by dNsl9r** [comment]
It would be a lot, a lot easier for Microsoft to support you if you could provide exactly WHICH events you need at WHICH position in these codeunits..

**Comment by qutreson** [comment]
Hi @nareshbandariD365, as suggested by @dNsl9r, can you re-open an issue specifying which signature you want to get for your events and where you expect them to be raised in the codeunit? 
You can find examples on how to request new events in this repository by looking at issues with the label `event-request`.
