### ISSUE TITLE
[AL] 'OnNextRecord' is not a valid trigger

### ISSUE THREAD

**Issue by malue19** [microsoft/AL#3825]
Hey guys, I am trying to create a trigger in my extension, but VSC shows me, that my trigger is not a valid trigger...
Does anybody know, how to solve this?

![grafik](https://user-images.githubusercontent.com/42337107/45953583-cf9a4500-c00a-11e8-85db-3dafc71cbad9.png)

**Comment by qutreson** [comment]
Hi @malue19, can you provide us with the following information so that we can start investigating your issue?

Which version of the compiler are you using?
What is the error you are getting? 
On which type of object are you using this trigger?  

The [OnNextRecord Trigger](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onnextrecord-trigger) can only be used on pages and request pages.

**Comment by malue19** [comment]
Hi @qutreson,

![grafik](https://user-images.githubusercontent.com/42337107/45955478-556cbf00-c010-11e8-85ef-68da07dbc962.png)

The error message I get is:
`[AL] 'OnNextRecord' is not a valid trigger
local trigger OnNextRecord(Steps: Integer): Integer
`

The object I would like to extend is not a standard object of NAV, it is a page of my own extension. 

The version of the AL Language Package I am using is 0.16.19969.

**Comment by qutreson** [comment]
It is currently not possible to use this trigger on a page extension. It can currently only be used from a page or a request page object. 

We will use this issue to track this issue if we consider making this trigger available from page extensions in the future.

In the meanwhile, what you can do, is create an event in the base page and raise this event in the OnNextRecord trigger on the page. Then, you can subscribe to it from your extension and re-use it there.

**Comment by bssi-danielf** [comment]
As a clarification: it is not possible to use the `OnNextRecord` trigger on base product pages (i.e. Customer Card), as the only way to modify these resources is through page extensions or event subscribers.

**Comment by epernst** [comment]
Any progress on this? We need this in our extension in v14.

**Comment by atoader** [comment]
@epernst @bssi-danielf as this is a request for a new feature, please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by epernst** [comment]
The suggestion:
https://experience.dynamics.com/ideas/idea/?ideaid=f4c5909f-bbb1-eb11-89ee-0003ff45a9b7
