### ISSUE TITLE
error AL0304: Length of the identifier cannot exceed 120 characters

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#383]
Getting this error when we have any statement with more than 120 characters.
how can we extend it to 2nd line?

![length issue](https://user-images.githubusercontent.com/23735402/28279876-87950658-6b3f-11e7-83f8-3d789019d5ba.png)

**Comment by markbrummel** [comment]
Hmmm. Just my humble 0.02$ but maybe the "field" should be the return value of a function? Is this on a page? You can add functions to a table extension.

**Comment by dennisfrostlander** [comment]
The first value in the field() syntax is the field name (or an identifier, in the technical terms). Therefore the string "STRSUSTRNO(..." becomes the name of the field.
It should be something like this:
```JavaScript
field("My field name"; StrSubstNo('...'))
{
}
```
