### ISSUE TITLE
Worksheet page with no actions and no manage still shows action area

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#3832]
We have a control add-in that we want to give the maximum amount of screen real estate. We use a Worksheet page to host it because that page seems to provide the most vertical and horizontal space in the content area. In the new BC UI, however, if you create a Worksheet page with no Actions, and set the InsertAllowed and DeleteAllowed to false, the resulting page still shows an action area that takes up a large portion of the screen (and looks odd):
![image](https://user-images.githubusercontent.com/19348055/45986786-9e863880-c03b-11e8-908f-882d362b25f5.png)
If there are no actions, the action area should be hidden to provide more real estate to the content area.

page 50100 MyWorksheetPage
{
    PageType = Worksheet;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Tenant Media Set";
    InsertAllowed = false;
    DeleteAllowed = false;

    layout
    {
        area(Content)
        {
            field(Name; "Company Name")
            {
                ApplicationArea = All;

            }
        }
    }

}

**Comment by StanislawStempin** [comment]
Response from the Client team:
We have a special layout for an add-in to let it stretch to full available space. To enable the full-screen layout, the page needs to satisfy these conditions:
The page type is Card.
The control add-in needs to be the only visible field on the page.
