### ISSUE TITLE
'CaptionClass' can only be set if the property 'Type' is set with any of the values of :'BigInteger,Boolean,Code,Date,DateFormula,DateTime,Decimal,Duration,Integer,Guid,Label,Media,MediaSet,Option,RecordID,Text,Time,TextConst'

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#3833]
In build 24690, suddenly it doesn't like any of my CaptionClasses. Here's an example:
            field(Control1000000004;'')
            {
                ApplicationArea = Basic,Suite;
                CaptionClass = Text001;
                HideValue = true;
                ShowCaption = false;
                Style = Attention;
                StyleExpr = TRUE;
            }
Nothing I enter in the CaptionClass property will be accepted by the compiler in this build.

**Comment by atoader** [comment]
Hi @jcooper01 ! I fixed this issue yesterday. It should be available in the next days.
