### ISSUE TITLE
VS Code Intellisense when input boolean value

### ISSUE THREAD

**Issue by hydhart** [Microsoft/AL#3834]
Hi,

when input boolean value intellisense does not show the right value for **true** or **false**.
![image](https://user-images.githubusercontent.com/41423177/45994107-62df8300-c0bc-11e8-8dc2-3f0a24a8cab1.png)

the value considered as text value.
![image](https://user-images.githubusercontent.com/41423177/45995662-3c711600-c0c3-11e8-8f5a-d068f3e82f7d.png)

**Comment by qutreson** [comment]
Hi @hydhart, this seems to have been fixed in our latest master. 

![github3834](https://user-images.githubusercontent.com/31541422/45998679-dde86f80-c0a3-11e8-9ef3-1a4aaeeff7f0.gif)

**Comment by qutreson** [comment]
I was meaning our internal master for the AL extension. This is not a VS Code issue, IntelliSense only depends on your current AL extension. I believe this issue should be fixed when using the AL extension version 2.0.41872 from the [August Preview](https://blogs.msdn.microsoft.com/nav/2018/08/31/developer-preview-august-2018/).
