### ISSUE TITLE
Function expose: SetupNewLine in Table Phys. Inventory Comment Line

### ISSUE THREAD

**Issue by mrabus** [Microsoft/AL#3837]
Hello all,

I am working on a helper tool to create comments more easily. 

Therefor, I use the SetupNewLine functions all over NAV a lot but unfortunately the function is blocked for extension development in table "Phys. Inventory Comment Line". Can you please remove that restriction? 

Thanks a lot

**Comment by darjoo** [comment]
Hi @mrabus, we’ve decided to go ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
