### ISSUE TITLE
failed with code 422. ...Reason: Token StartAttribute in state Element Content would result in an invalid XML document.

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3840]
Hey guys, I get the above message and I am not sure how to solve this: I am trying to create the package of my extension, but after executing the F5 key, it shows me the following error message...

![grafik](https://user-images.githubusercontent.com/42337107/46014184-b5c23600-c0ce-11e8-8932-cc3c64c254c9.png)

**Comment by qutreson** [comment]
Hi @malue19, which version of the extension are you using?  Which server version are you using?
Can you try to extract a piece of code that reproduces this issue?

**Comment by malue19** [comment]
Hi @qutreson ,

this is a part of my app.json:

![grafik](https://user-images.githubusercontent.com/42337107/46189919-70ca1980-c2f1-11e8-977c-ba1c980e23c2.png)

The version here is 1.0.0.0

The AL Language package I am using is 0.16.19969

The application is NAV 2018 (11.0.20348.0) and the SQL server is version 13.0.5153.

**Comment by qutreson** [comment]
Hi @malue19, you are using the one from the VS Code marketplace right? 
But, which is the version of the AL extension you received with NAV 2018?

**Comment by malue19** [comment]
Hi @qutreson, yes it is the one from the marketplace. 

With the version of the AL extension you mean the vsix-file in the Modern Development Environment? If yes, I do not know where to find the version.

**Comment by qutreson** [comment]
When you received NAV2018, you should also have received an AL extension (vsix file) with it. Do you know which version is it? 

In the DVD, we ship NAV with an AL version that is compatible with your server. If you use an extension which is not in sync with your server, you may end up with some strange errors. My guess is that you received there an AL version that is older than the one on the marketplace and this is why you are now getting errors when publishing.

**Comment by malue19** [comment]
I got NAV2017 and I upgraded it to NAV2018. This is maybe important to know.

I think the version is 0.12.16641.0.

This is the file, I got the version number from: Microsoft.Dynamics.Nav.CodeAnalysis.dll

**Comment by qutreson** [comment]
Can you try using one of our [sandbox](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sandbox-overview) to publish your extension and tell us if it reproduces there as well?

If it does not reproduce on Business Central, as you are using NAV 2018, please contact your regular customer support channel.

**Comment by malue19** [comment]
Solution for me:
Compile error with SourceTableView #781 
[https://github.com/Microsoft/AL/issues/781]

**Comment by MahyarFar** [comment]
> Solution for me:
> Compile error with SourceTableView #781
> [https://github.com/[/issues/781](https://github.com/Microsoft/AL/issues/781)]

Thanks, it solved my problem.
