### ISSUE TITLE
Dependent extensions: error AL0132: 'TestPage G/L Account Card' does not contain a definition for 'Test Field-Xyz'

### ISSUE THREAD

**Issue by gregoral** [Microsoft/AL#3843]
Unable to build dependent extensions.

We're supposed to upload tests for our extension as a separate package.
So we need to separate our testing codeunits into a dependant extension.test.app.

If we build our packages with al-2.0.46000 or al-2.0.47152 this does not work any more.
If we build with al-2.0.42188 it still works as expected.

The error we get is:
error AL0132: 'TestPage G/L Account Card' does not contain a definition for 'Test Field-Xyz'

I have attached code for two extensions ( range 60200 and 60201 ).
TST.BASE.DEP app extension has a dependency on TST.BASE app extension.

As mentioned, building with al extension gives the following results:
- al-2.0.42188  ... works as expected
- al-2.0.46000  ... compilation fails
- al-2.0.47152  ... compilation fails

[dep.ext.test.20180925.001.zip](https://github.com/Microsoft/AL/files/2415317/dep.ext.test.20180925.001.zip)

**Comment by DominikWidmann** [comment]
Same issue here:
Building test automation with al-2.0.46000 doesn't recognize Page Fields and Controls of depending app.
Building test automation with al-2.0.43900 everything works fine.

**Comment by atoader** [comment]
Hi! The issue has been fixed in the latest release. It should be available shortly.
