### ISSUE TITLE
Shouldn't we get rid of the TableNo property of a codeunit?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#3845]
Teaching AL development to an experienced _outside_ developer is an many aspects interesting. Just take this topic.

So he starts programming a codeunit object in AL like this:
```
codeunit 66666 MyCodeunit
{
    trigger OnRun()
    begin
        
    end; 
}
```
And now he would like to add a parameter to the OnRun trigger. What is the most intuitive way to do that? What would be most logic for any non-NAV developer to do that?
Right, like adding a parameter to any function. Place your cursor in between the bracket and start typing:
```
codeunit 66666 MyCodeunit
{
    trigger OnRun(var Rec : Record "My Table")
    begin
        
    end; 
}
```
Indeed, VSCode will error telling that this is a wrong signature. All NAV developers know you have to define the TableNo property (well, I even dare to argue that):
```
codeunit 66666 MyCodeunit
{
    TableNo = "My Table";

    trigger OnRun( )
    begin
        
    end; 
}
```
IMHO this doesn't make sense anymore, so please change AL to allow to add a record parameter to the signature of the OnRun trigger and deprecate the TableNo property.

Note: in C/SIDE it was already a somewhat strange way of working, but there, after populating the TableNo property the OnRun trigger would at least be displayed with the signature deriving from it:

![image](https://user-images.githubusercontent.com/18466198/46040235-0d34c600-c110-11e8-9b16-bec2ab31ab62.png)

**Comment by esbenk** [comment]
Hi! Thank you for your suggestion. We recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
