### ISSUE TITLE
Nested virtual Tables

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#385]
I already had lists and dynamic arrays addressed. But a really cool feature would be in my eyes still nested virtual tables.

Let's imagine a lookup. For this you do not want to build a table on the SQL server, actually you need it only once.

Now it would be cool at this point a nested table or a Tamplate.

The following is pseudocode

````csharp
procedure Something(var Rec : Record Customer)
{
      var nested : virtual table
      {
         No : integer(autoincremented: true),
         Description : Text[250],
         Comment : Text[100]
      };

     nested.Description :=  Rec.Description;
     nested.Comment := 'this is a Commend for Customer ' + Rec."No.";
     nested.Insert();
};
````

**Comment by dennisfrostlander** [comment]
Thanks, interesting suggestion. More detailed consideration would need to go to the longer term backlog since it will require quite some changes in the platform and the language.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
