### ISSUE TITLE
[Function Expose] Table 38 - Purchase Header

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/AL#3850]
We need  "**ConfirmUpdateCurrencyFactor**" and "**UpdateCurrencyFactor**" functions available as global/external

**Comment by darjoo** [comment]
Hi @InnovaACAdmin, what is the reason that you require these functions to be external?

**Comment by InnovaACAdmin** [comment]
We are a subscribed to standard publisher "OnAfterValidateEvent" of field "'Document Date" and we need to call those functions.

**Comment by InnovaACAdmin** [comment]
yes, those two OnValidates execute those two functions, but We only want to execute this segment of code
```
IF "Currency Code" <> '' THEN BEGIN
  UpdateCurrencyFactor;
  IF "Currency Factor" <> xRec."Currency Factor" THEN
    ConfirmUpdateCurrencyFactor;
END;
```

because  on function `UpdateCurrencyFactor`we have created a subcriber to standard publisher` OnBeforeUpdateCurrencyFactor(Rec,Updated);`  to update "CurrencyDate" with "'Document Date" instead of "Posting Date" as standard code

**Comment by darjoo** [comment]
`UpdateCurrencyFactor` will be made external while `ConfirmUpdateCurrencyFactor` will not, however, you are welcome to copy it into your codeunit. 
You’ll see the function as external in the next minor release.

**Comment by InnovaACAdmin** [comment]
Sorry, but we need the same in T36. Thanks.

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application bugs, application requests and application enhancements.
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
