### ISSUE TITLE
Function Request: Page 350 G/L Acc. Balance/Budget Lines needs a GetGLAcc

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3853]
On Page 350 G/L Acc. Balance/Budget Lines we need a global external function `GetGLAcc` that returns the currently calclated G/L Account. Otherwise we do not have any means of knowing the current G/L Account is and extending this page is impossible. Something like this:

````
procedure GetGLAcc(VAR NewGLAcc: Record "G/L Account");
begin
  NewGLAcc.COPY(GLAcc);
end;
````

**Comment by darjoo** [comment]
Hi @hemisphera, we’ve decided to go ahead with your request. The function GetGLAcc will be added to the Page. We usually include these types of changes in the next minor release, so look for it there.
