### ISSUE TITLE
Authorization Problem in Postman when Calling APIs for BC with Windows Authentication 

### ISSUE THREAD

**Issue by zulezmaj** [Microsoft/AL#3858]
Can anyone help me with the following issue?

Problem is happening in BC which is installed in container with Windows authentication.

I am constantly receiving the 401 Unauthorized error when I try to hit simple API URL (http://nemanja:7048/NAV/api/beta/companies?tenant=default) via Postman with Basic Auth. On other hand can access it easily via browser:
 
![image](https://user-images.githubusercontent.com/40229810/46085634-ba5a1d80-c1a6-11e8-8d34-6e561b1a3559.png)

Also, in BC which runs in container with NAVUserPassword authentication I can easily hit any APIs either from Postman with Basic Auth or through browser.

**Comment by tfenster** [comment]
if you use Win Auth in your container, you need to use Win Auth (NTLM) in Postman as well. You can change the authorization type in your Postman request

**Comment by zulezmaj** [comment]
Thanks @tfenster for the suggestion. It works, just had to set ServicesUseNTLMAuthentication to true, because it is by default set to false.
