### ISSUE TITLE
[Function Expose] Codeunit 12 - Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/AL#3861]
We need functions "CheckGLAccDimError" and "CalcAddCurrForUnapplication" availables as global/external

**Comment by darjoo** [comment]
Hi @InnovaACAdmin, what is the reason that you require these functions to be external?

**Comment by InnovaACAdmin** [comment]
Hi, We were able to solve the problem we asked for this modification. You can close our requiriment. Thanks
