### ISSUE TITLE
Unpublish an App from Business Central Sandbox

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#3864]
We have more Extensions published and installed in our BC Sandbox-environment for extensive testing.
The version of one of the apps was unintentionally modified and as a consequence when uploading that App to our sandbox, we got an error, telling that we needed to run an update.
We have corrected the version in the app.json file and reloaded the App, but now we get error 422: The Extension can not be synchronized as a newer version has already been synchronized.

However when we open the sandbox, the correct App is there with newest modification and correct version. The App just needs to be installed manually. Then everything works.

The error 422 just keeps coming up every time we upload new modifications for this App.

How can we remove the App totally from the sandbox without removing the entire sandbox ?
We have test-data in other App's we would like to keep.

Expected an Unpublish would solve the task but we can't find any guide of unpublishing from the sandbox.

**Comment by naveksa** [comment]
Thanks, that worked :-)
Just wondered about the unpublish.
In NAV2018 OnPremise we have the Unpublish function, but that function seems not to be available in D365 BC Cloud sandbox. Maybe it will be there in a future release (?)

**Comment by StanislawStempin** [comment]
We are not planning changes in this area in the near future but will consider it for our long term backlog.
Closing this issue as it seems to be solved.
