### ISSUE TITLE
Extending Custom Navision Table

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/AL#3866]
We currently have a product that is only in C/AL and will eventually be transitioned
 to AL.  We have a second product in AL.  I wanted to create another app that would be dependent on the AL app, but extend the product the is still in C/AL.  When I go to create the page extension for that app 
 I get the error message "The target Page "CBS Setup" for the extension object is not found."  I see the Tables are not in the Microsoft_Application.app file.  Is there a way to use custom table/pages in your app that are stil in C/AL?

**Comment by qutreson** [comment]
Hi @MatthewMcCarthy7, this should answer your question: [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side).

**Comment by MatthewMcCarthy7** [comment]
Thanks! That worked, and this ticket can be closed.
