### ISSUE TITLE
Procedure Scope

### ISSUE THREAD

**Issue by nicolassaleron** [Microsoft/AL#387]
Hello,

This suggestion is linked with question #67 .

We have the property Local for procedures and since several months, FunctionVisibility property has been added.
If my understanding is correct, I think these two properties (Local and FunctionVisibility) should be summarized in one property (for instance called "Scope") where :

Local=Yes => Scope=Private
Local=No, FunctionVisibility=Internal => Scope=Protected
Local=No, FunctionVisibility=External => Scope=Public

I don't know what others would think about that, but IMHO it would be much more clear for any non C/AL-AL developer and should not disturb others.

**Comment by kalberes** [comment]
Hi,
FunctionVisibility is related to something called compilation scope.  This is not a function access modifier in the "normal" sense. The compiler gets as input a compilation scope and uses this scope to determine what symbols are legitimate within a compilation unit.
Example: If you compile an extension with the compilation scope external then if a W1 function scoped with function visibility internal is referenced in your extension that would not compile. This is particularly useful when we recompile a published application on the server. 
Anything that could have an effect in creating a symbol has a compilation scope.  Example :  builtin AL members even system option members may have their own compilation scope.  
That said the name FunctionVisibility is not the best one.

**Comment by nicolassaleron** [comment]
Okay... thank you for your answer but still, I am not sure to understand the whole concept :)

If I made a parallel with .Net, what you call a compilation unit might be something like an assembly, isn't it ? An extension is like an assembly, objects in the object designer also ?

So an Internal procedure (more generally a "symbol") is something like a method with a Scope=Friend in an .net class ?

**Comment by StanislawStempin** [comment]
This is not related to visibility as understood in .NET terms. Think about it more as  Target = Internal is On-Premise and Target = Extension is multi-tenant cloud environment where less things are safe.
