### ISSUE TITLE
T370 UpdateBookExcel not available for extension development.

### ISSUE THREAD

**Issue by rdebath** [Microsoft/AL#3870]
I can use currently use the below from an extension to create a bare spreadsheet.
I would like to use `UpdateBookExcel` so that I can fill my data into a template spreadsheet previously uploaded into the database.

``` pascal
ExcelBuffer.CreateNewBook(Sheetname);
Populate(ExcelBuffer);
ExcelBuffer.CloseBook;
ExcelBuffer.SetFriendlyFilename(SSName);
ExcelBuffer.OpenExcel;
```

**Comment by GiorgosPa** [comment]
Sorry, after reviewing your suggestion we’ve decided that unless something changes we cannot implement it. UpdateBookExcel function is file based which is not safe on the cloud. We will be refactoring all file usages to work with streams but it will take some time until we are ready

**Comment by GiorgosPa** [comment]
Maybe the functions
 [External] SelectSheetsNameStream(FileStream : InStream) : Text[250]
and
[External] WriteSheet(ReportHeader : Text;CompanyName2 : Text;UserID2 : Text)
can do the trick

**Comment by rdebath** [comment]
Your suggestion is obviously wrong. The `SelectSheetsNameStream` function uses the `XlWrkBkReader` DLL whereas the `WriteSheet` function uses the `XlWrkBkWriter` DLL. This means that they do not have anything to do with each other and it's not possible for them to work together.

As I already have the spreadsheet in the database a stream would be more convenient.
