### ISSUE TITLE
[Function expose] Codeunit 1248 "Process Bank Acc. Rec Lines"

### ISSUE THREAD

**Issue by Tharangac** [Microsoft/AL#3873]
Codeunit 1248 "Process Bank Acc. Rec Lines"

We would like to be able to call below two methods in Codeunit 1248 .
**ImportBankStatement
CreateBankAccRecLineTemplate**

Thank you.

**Comment by IhorHandziuk** [comment]
Thank you for your request, these procedures will be exposed in the future update.
