### ISSUE TITLE
D365 Localized database

### ISSUE THREAD

**Issue by IgorPcelnikov** [Microsoft/AL#388]
Hello,
is there localized database for NA and D365? Current one is W1 on Azure that comes with image.

Thanks!

**Comment by dennisfrostlander** [comment]
Not NA, but we used to have a US localized database. In July Updated we had to release though on W1 due to internal build process changes.
For more details see #367.

**Comment by IgorPcelnikov** [comment]
How can we develop US market specific solution if no US database available? (Deposits/Checks/NA Bank Recs functionality and etc.)

**Comment by dennisfrostlander** [comment]
We are working on returning the US database back.

**Comment by IgorPcelnikov** [comment]
Thanks
