### ISSUE TITLE
New event request Codeunit 12 - Function FinishPosting

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#3881]
new Integration Event:

**LOCAL [IntegrationEvent] OnAfterFinishPosting(VAR GlobalGLEntry : Record "G/L Entry";VAR GlobalGLRegister : Record "G/L Register";IsTransactionConsistent : Boolean)**

=============================================================

**FinishPosting() IsTransactionConsistent : Boolean**
IsTransactionConsistent :=
  (BalanceCheckAmount = 0) AND (BalanceCheckAmount2 = 0) AND
  (BalanceCheckAddCurrAmount = 0) AND (BalanceCheckAddCurrAmount2 = 0);
..........................................

IF CostAccSetup.GET THEN
  IF CostAccSetup."Auto Transfer from G/L" THEN
    TransferGlEntriesToCA.GetGLEntries;

FirstEntryNo := 0;

**// new event code
OnAfterFinishPosting(GlobalGLEntry,GLReg,IsTransactionConsistent);**

LOCAL PostUnrealizedVAT(GenJnlLine : Record "Gen. Journal Line")

**Comment by AlexanderYakunin** [comment]
I can implement this event but without IsTransactionConsistent paramerer. It will always be TRUE for this event call. Otherwise this event will never be reached due to earlier error produced by GlobalGLEntry.CONSISTENT(IsTransactionConsistent) statement.

**Comment by Halilovast** [comment]
I am sorry for late, but @AlexanderYakunin  I need this event with IsTransactionConsistent parameter. Because my code must run only if  IsTransactionConsistent=true. 

**skip case:**
![image](https://user-images.githubusercontent.com/34268528/48128256-8df9ec80-e28e-11e8-9eeb-1b91d5acc24d.png)

**run case:**
![image](https://user-images.githubusercontent.com/34268528/48128339-d5807880-e28e-11e8-8345-d96abf045250.png)
