### ISSUE TITLE
[Question] Auto Install dependency app

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#3882]
Hi,

Will it be possible to install a dependency app automatically ?

As I have an app which will give some functionalities commonly used by others, I want to prevent installation Errors by detecting if the app which gives the dependencies is well installed, by auto-download it if it isn't yet. 

Is a feature like that possible in a cloud perspective ?

**Comment by StanislawStempin** [comment]
This is already the implemented system behavior if you install apps from AppSource.
