### ISSUE TITLE
NAV Web Client vs BC Web Client

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#3884]
I am working with BC1810 RC03 (October Release Candidate 3).

By default, in the RTC, it appears that some profile personalization has been done to both of these pages.  For the Resources list, there is no Navigate option in the ribbon; just a Prices group on the Home ribbon.  For the Resource Card this is a Navigate option; however there is also a Prices group on the Home ribbon.  This same personalization does **not** appear in the BC web client.  The same default personalization was in NAV 2018 and the 2018 Web Client showed the personalization.  

Is this a change for BC or a bug?  If it is a change, does that mean you can't "configure" the ribbon on page in the web client any more?

NAV/BC RTC Ribbon
![image](https://user-images.githubusercontent.com/4333956/46147068-58f48600-c25c-11e8-8473-4133a9cc9778.png)
BC Web Client ribbon
![image](https://user-images.githubusercontent.com/4333956/46147107-73c6fa80-c25c-11e8-88d7-d4bc6fd1dc2a.png)
NAV 2018 Web Client
![image](https://user-images.githubusercontent.com/4333956/46149743-e0dd8e80-c262-11e8-9e57-f8ada642e0c9.png)

**Comment by GreatScott000** [comment]
Okay so I found something else weird.  If I "search" for the Resources list from the "light bulb" I get the ribbon in my original post.  If I use http://localhost:8080/BC130/WebClient/?Page=77 (like it does from the from VS Code using startobjectid/startobjecttype).  I get this this ribbon, which **does** have the personalization.

![image](https://user-images.githubusercontent.com/4333956/46154360-e8099a00-c26c-11e8-85ff-13c0822db3dd.png)

What is the difference?  Is this a bug?  Intentional?

**Comment by StanislawStempin** [comment]
We received a reply from the client team:
The page gets different personalization ID depending if it is opened as ListPlace or ListPage in V1 personalization. In WebClient list pages from Tellme are opened as ListPages and as ListPlaces when navigating by url or navigation action. WinClient opens list pages as ListPlaces both from search and navigation. ​V2 personalization is applied differently and does not have this issue. We are working on enabling V2 action personalization in Web Client.
