### ISSUE TITLE
Converting Translations with txt2al - missing state-property

### ISSUE THREAD

**Issue by herojo** [microsoft/AL#3886]
In the process of migrating existing solutions from C/AL to AL we use the txt2al-Tool (from BC 123 build).

In the created XLIFF Files which we tried to use with the Lifecycle-Translation-Service as Memory Files the property "state" is missing. 

so i think it would be nice, if it would be part of the created files, because the translations in C/AL (Captions ML and Tooltips ML) have a kind fixed status for us.

**Comment by StanislawStempin** [comment]
We will consider it as an enhancement. Until then I believe you can use Microsoft Translation Studio to add the status for each translation item: https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit
