### ISSUE TITLE
question re: cloning a production BC environment + data to sandbox

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#3888]
Say we have a tenant-specific extension (i.e. AL objects in the 50000..99999 range) and would like to test/debug it against the tenant's production data. 

I understand that there is a new sandbox mechanism in Business Central to spin up a sandbox of the production environment (where the sandbox runs on azure or locally via docker). This is the URL that explains it:

https://docs.microsoft.com/en-ca/dynamics365/business-central/across-how-create-sandbox-environment

The link does mention that the sandbox that BC creates does not have any production data and is instead loaded with default demonstration data. This means the sandbox needs to be loaded with prod data manually e.g. rapidstart. Personally I would find this process both time consuming and error prone. 

For extensions tailored for a specific tenant, testing against production data against that tenant is important. A sandbox without a clone of all prod data negates its usefulness as an accurate testbed. 

I can't find the link, but I once stumbled onto an MS blog mentioning that one of the features coming soon for BC will be sandbox creation WITH production data - utilizing azureSQL backup/restore under the hood (the article did mention that any integrations in the sandbox (e.g. CRM I'm assuming for one) will be turned off in the sandbox (and rightfully so). 

Can Microsoft elaborate on this if that is the case?  Can they share a link? An ETA? The excel  methodology for transferring prod data to a sandbox as it's currently documented seems very cumbersome and it would be great to hear that a better solution is on the horizon.

**Comment by BrianAllrich-MSFT** [comment]
For tenants running on the Fall release of Business Central, administrators can use the new Business Central Admin Center to create a sandbox based on the production environment (that has restrictions - see below).  This feature is not available using the original way of creating the sandboxes (using the steps in the docs you link to).  Once you have the sandbox created, you can connect your VSCode environment to it and publish your extension to be tested.    

Here's the link to the docs for the new Business Central Admin Center.  
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center

I see that this is not easily navigated to from the section of the docs you reference above.  I will see what I can to do fix this.  

**Restrictions for a Sandbox created from the production environment:**
The job queue is automatically stopped.
Any base application integration settings are disabled or cleared. Caution should be taken to not integrate with production services unless intended.
Users will be copied as well, with same permissions as in production.
Outbound HTTP calls from extensions are blocked by default and must be approved per extension.  When an extension makes an outbound call a dialogue to the user appears.
Any GDPR action must be handled separately and repeated for the sandbox, there is no synchronization with the production environment after the sandbox has been created.

**Comment by CanuckNav74** [comment]
THANK YOU @BrianAllrich-MSFT

PS - Any help you can add offer to the upcoming Admin Center documentation would be great
