### ISSUE TITLE
LookupPageID and DrillDownPageID

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#389]
We cannot change LookupPageID and DrillDownPageID properties of table to create extension,
we have created different pages than standard pages to use while selecting the values etc. and due to above limitation we are not able to achieve it.
Can you please review to provide access to change above properties.

**Comment by dennisfrostlander** [comment]
Thanks, we will look into this.

**Comment by pmohanakrishna** [comment]
any update on this?

**Comment by dennisfrostlander** [comment]
Apologies for the delay, slipped away. Checking...

**Comment by dennisfrostlander** [comment]
This requires some platform support, but generally it can follow the "last man wins" strategy in case more than one extension modifies the property.

**Comment by dennisfrostlander** [comment]
After further discussion between different teams it has been decided that LookupPageID and DrillDownPageID properties should not be customized in table extensions. The reason is that if multiple extensions change the same property, then the "last man wins" strategy will be confusing as it affects the behavior of the system, and not only the display (such as caption/description properties which are customizable).
Apologies for setting wrong expectations before.

**Comment by lvanvugt** [comment]
@dennisfrostlander I understand the reasoning, but how am I going to get the following working:

- I am creating a dependent extension (**B**), depending on one of my own extension (**A**)
- In B I extend a table in A (**TableA**)  with a new FlowField (in a table extension object, **TableExtB**)
- CalcFormula is pointing to a **TableA**
- I am adding the FlowField (through a pageextension object **PageExtB**) to a page in A (**PageA**)

OK, no issue so far, but now I would like to enable that the user can drilldown on the FlowField. So, I need to have a page linked to **TableA**, by means of the DrillDownPageID property, but this is not enable in AL.

How to get this working?

**Comment by dennisfrostlander** [comment]
Hi @pmohanakrishna, @lvanvugt,
I think we have reached a consensus that these properties should be customizable in extensions.

**Comment by lvanvugt** [comment]
Great. As we are mainly on NAV 2018, can I apply for a downgrade?

**Comment by dennisfrostlander** [comment]
Sure, but only when this issue gets resolved here on the latest version of the product.

**Comment by lvanvugt** [comment]
I recon a milestone will be attached to this issue in due time?

**Comment by dennisfrostlander** [comment]
Sorry, was not involved into the related issue. We'll provide feedback on it shortly as well.

**Comment by pmohanakrishna** [comment]
@dennisfrostlander what is the fix here and how to use that? any help is appreciated.

**Comment by JavierFuentes** [comment]
Hi @dennisfrostlander ,
please look at [my issue 4363](https://github.com/Microsoft/AL/issues/4363) where I propose a separation in the definition of the tables in the physical part and the non-physical part, together with some other things to cover the OnPremise scenarios of final clients like us.

**Comment by dennisfrostlander** [comment]
@StanislawStempin
