### ISSUE TITLE
Functions related to file management needed to be external

### ISSUE THREAD

**Issue by miljance** [Microsoft/AL#3891]
- Server Version: MS Dynamics 365 Business Central RC3

I suposse functions for management of files are not planned to be made externally accessible for cloud solutions but what about On-Premise?

We stumbled upon following functions that we need to use inside Extension.
Codeunit 419 "File Management" : UploadFile and UploadFileSilent
Table 370 "Excel Buffer" : SelectSheetsName and OpenBook

Any plans for making those [External]?

**Comment by dNsl9r** [comment]
If you work OnPrem change the extension scope to internal

**Comment by miljance** [comment]
That is true but that was not the question at all. We need these functions to be externaly available for extensions. Since some other functions in these codeunits are already marked as External i suppose that ones that we need were deliberatly not changed to be externaly acessible because one canot rely on file system in cloud system. Since we are OnPrem we would still gladly use file system if possible.

**Comment by dNsl9r** [comment]
I fully understand - so you want your extension always be able to use the functions, no matter if you work OnPrem or in Cloud, right?
Pretty sure the ones marked as internal will stay internal, but you never know..

If your extension is only for your OnPrem solution I'd still suggest you to change the scope to internal.

**Comment by miljance** [comment]
I believe you are probably right about the statement that these functions will stay internal and therefore might even been deprecated in future. I prefer to make the question nevertheless.

It is exclusevely OnPrem extension and not our solution but rather customisations for customers.

**Comment by miljance** [comment]
Case closed since Danis was right. Setting property in app.josn is enough for OnPrem.
"target": "Internal" 
It must be that i haven't set this property to app.json during my test.
