### ISSUE TITLE
Events to print all the Warehouse documents

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#3892]
Hello,

Can we get events with handled pattern for all the warehouse reports so we can overrule the hard coded Navision reports? Or maybe selecting this reports using report selection (such as all the other printed documents) which would be even better.
I am talking about all the functions in Codeunit 5776 Warehouse Document-Print.

![image](https://user-images.githubusercontent.com/6583705/46198032-c4e1f780-c30b-11e8-9bc6-e9ddf6e4948c.png)

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
This change cannot be done as simple event request, it require data model change, some refactoring and testing. Converted to application enhancement slice. Expected to be done for next major release.
