### ISSUE TITLE
tablerelation property/drilldown

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#39]
I tried to create an extension using visual studio code.
[http://mohana-dynamicsnav.blogspot.in/2016/12/developing-extensions-using-new-visual_17.html](url)
Tablerelation property seems to be not working or did I miss something?

**Comment by dennisfrostlander** [comment]
Seems to be a bug when TableRelation property is defined within a table extension.

**Comment by kalberes** [comment]
Table relations and calculation formulas are not yet supported in extended tables, only in "normal" tables

**Comment by pmohanakrishna** [comment]
It will be a big hurdle. When can we expect a solution?

**Comment by esbenk** [comment]
TableRelations in extensions will be supported in the update to the preview.

**Comment by pmohanakrishna** [comment]
When can we expect the update? Any approximate time frame?

**Comment by Avanti05** [comment]
Is this the same issue that causes RunPageLink not to work on extended pages? (no object reference..)

**Comment by esbenk** [comment]
It is a different issue. It will also be fixed in the next update.
