### ISSUE TITLE
The property 'CalcFormula' cannot be customized

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#390]
I am using July update and converted CAL to AL.
I got below error while changing CalcFormula property of standard field.

Isn't it supported? 

severity: 'Error' message: 'The property 'CalcFormula' cannot be customized'

![image](https://user-images.githubusercontent.com/23735402/28365423-23b3fe06-6ca6-11e7-84b7-2563df7991ac.png)

**Comment by dennisfrostlander** [comment]
No, calculation formulas cannot be customized. The conceptual problem here is that what if multiple extensions customize the CalcFormula on the same field - then there is no deterministic order to decide which customization is more important. Therefore the only properties that can currently be customized are the ones that have (let's call it) not so serious impact on the runtime.
