### ISSUE TITLE
Error while generating symbols

### ISSUE THREAD

**Issue by Joriek** [Microsoft/AL#3901]
Hello,

I've added a couple of new events in the C/Side environment in a SQL on Azure Database. While generating the new symbols to use in AL with the following command in the correct folder with elevated permissions (for obvious reasons I blanked out the login information):

![image](https://user-images.githubusercontent.com/6583705/46209998-bb6a8680-c32f-11e8-9d81-798ac333ee87.png)

I am not getting any logs in the command folder. Neither is there a finsql proces starting in the Task Manager. I do get some error messages in the Event viewer but I have no idea how to correct them.

![image](https://user-images.githubusercontent.com/6583705/46210110-26b45880-c330-11e8-8ef8-14cdef592157.png)

![image](https://user-images.githubusercontent.com/6583705/46210150-3fbd0980-c330-11e8-9f91-55865c2ae034.png)

![image](https://user-images.githubusercontent.com/6583705/46210130-359b0b00-c330-11e8-8052-0f23c94fe97f.png)

![image](https://user-images.githubusercontent.com/6583705/46210118-2ddb6680-c330-11e8-8dd7-5651b32228f2.png)

Can anyone help me with this issue? I've used this command before but on local databases, not on a SQL on Azure.

Kind Regards
Joriek

**Comment by BartPermentier** [comment]
I have the same issue, can anyone help please?

**Comment by kalberes** [comment]
Have you tried starting finsql.exe in the Client folder and not the server. probably you have some .net variable and you are missing the add-in dll?
https://blogs.msdn.microsoft.com/nav/2018/01/16/generate-symbols-in-a-modern-development-environment-with-microsoft-dynamics-nav-2018/

**Comment by BartPermentier** [comment]
I succeeded with finsql.exe generatesymbolreference=yes and then compiling all the objects.

**Comment by Joriek** [comment]
Seems like @BartPermentier his trick worked. Thanks!
