### ISSUE TITLE
[Event Request] Codeunit 12 - Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/AL#3903]
Add new event

**Function FinishPosting**
```
...
GlobalGLEntry.CONSISTENT(IsTransactionConsistent);

IF CostAccSetup.GET THEN
  IF CostAccSetup."Auto Transfer from G/L" THEN
    TransferGlEntriesToCA.GetGLEntries;

FirstEntryNo := 0;

//NEW CODE BEGIN>>
OnAfterFinishPostingGenJnlPostLine
//NEW CODE END<<
```
with new publisher
`LOCAL [IntegrationEvent] OnAfterFinishPostingGenJnlPostLine()`

**Function PostBankAccCreate. Created and modified standard function** 

We want to reproduce the same code below. This code have a new boolean global variable and a new publisher
```
 ...
  BankAccPostingGr.TESTFIELD("G/L Bank Account No.");

  //++ START
  BoleeanVariable := FALSE;
  OnBeforeCreateGLEntryBalAcc(
    GenJnlLine,BankAcc,BankAccPostingGr,BoleeanVariable,
    DecRetainedAmountLCY,DecRetainedAmount,
    DecAmountwithRetentionLCY,DecAmountwithRetention,NextEntryNo,NextTransactionNo);
  IF NOT BoleeanVariableTHEN
  //-- END
  CreateGLEntryBalAcc(
    GenJnlLine,BankAccPostingGr."G/L Bank Account No.","Amount (LCY)","Source Currency Amount",
    "Bal. Account Type","Bal. Account No.");
  DeferralPosting("Deferral Code","Source Code",BankAccPostingGr."G/L Bank Account No.",GenJnlLine,Balancing);
  OnMoveGenJournalLine(BankAccLedgEntry.RECORDID);
END;
```

Best solution we found to reproduce it, is create a new publisher and modify the funcion below adding a new boolean variable "Handled". 

```
...
  BankAccPostingGr.TESTFIELD("G/L Bank Account No.");

  //NEW CODE BEGIN>>
  OnBeforeCreateGLEntryBalAcc(
    GenJnlLine,BankAcc,BankAccPostingGr,
    DecRetainedAmountLCY,GDecRetainedAmount,
    DecAmountwithRetentionLCY,DecAmountwithRetention,NextEntryNo,NextTransactionNo,Handled);
  //NEW CODE END<<

  //OLD CODE BEGIN>>
  CreateGLEntryBalAcc(
    GenJnlLine,BankAccPostingGr."G/L Bank Account No.","Amount (LCY)","Source Currency Amount",
    "Bal. Account Type","Bal. Account No.");
  //OLD CODE END>>

  //NEW CODE END>>
  CreateGLEntryBalAcc(
    GenJnlLine,BankAccPostingGr."G/L Bank Account No.","Amount (LCY)","Source Currency Amount",
    "Bal. Account Type","Bal. Account No.",Handled);
  //NEW CODE END>>

  DeferralPosting("Deferral Code","Source Code",BankAccPostingGr."G/L Bank Account No.",GenJnlLine,Balancing);
  OnMoveGenJournalLine(BankAccLedgEntry.RECORDID);
END;
```

the first line in function CreateGLEntryBalAcc should be:

`If Handled the exit;`

new Publisher:
`LOCAL [IntegrationEvent] OnBeforeCreateGLEntryBalAcc(VAR GenJournalLine : Record "Gen. Journal Line";BankAccount : Record "Bank Account";BankAccountPostingGroup : Record "Bank Account Posting Group";DecRetainedAmountLCY : Decimal;DecRetainedAmount : Decimal;DecAmountwithRetentionLCY : Decimal;DecAmountwithRetention : Decimal;NextEntryNo : Integer;IntNextTransactionNo : Integer; VAR Handled : Boolean)`

**Comment by AlexanderYakunin** [comment]
Seems you work in ES version, but our COD12 does not contain variables DecRetainedAmountLCY, GDecRetainedAmount, DecAmountwithRetentionLCY, DecAmountwithRetention. Please make sure you ask for events in our code (W1 or ES).

**Comment by InnovaACAdmin** [comment]
Yes, C12 does not have those variables. We are working in W1. I forgot write the publisher without those variables.
The function is **PostBankAcc** and the publisher we need should have these variables:

`LOCAL [IntegrationEvent] OnBeforeCreateGLEntryBalAcc(VAR GenJournalLine : Record "Gen. Journal Line";BankAccount : Record "Bank Account";BankAccountPostingGroup : Record "Bank Account Posting Group";NextEntryNo : Integer;NextTransactionNo : Integer; VAR Handled : Boolean)`

**************
**1.-** I wish to ask for new publishers we need in same function **PostBankAcc**


```
WITH GenJnlLine DO BEGIN
  BankAcc.GET("Account No.");
  BankAcc.TESTFIELD(Blocked,FALSE);
  IF "Currency Code" = '' THEN
    BankAcc.TESTFIELD("Currency Code",'')
  ELSE
    IF BankAcc."Currency Code" <> '' THEN
      TESTFIELD("Currency Code",BankAcc."Currency Code");

  BankAcc.TESTFIELD("Bank Acc. Posting Group");
  BankAccPostingGr.GET(BankAcc."Bank Acc. Posting Group");

  BankAccLedgEntry.LOCKTABLE;

  //NEW CODE BEGIN>>
    OnInitRetentionProcessPostBankGenJnlPostLine(
      GenJnlLine,CurrencyFactor,NextEntryNo,NextTransactionNo);
  //NEW CODE END<<

  InitBankAccLedgEntry(GenJnlLine,BankAccLedgEntry);

  BankAccLedgEntry."Bank Acc. Posting Group" := BankAcc."Bank Acc. Posting Group";
  BankAccLedgEntry."Currency Code" := BankAcc."Currency Code";
  IF BankAcc."Currency Code" <> '' THEN
    BankAccLedgEntry.Amount := Amount
  ELSE
...
```
with new publisher
`LOCAL [IntegrationEvent] OnInitRetentionProcessPostBankGenJnlPostLine(VAR GenJournalLine : Record "Gen. Journal Line";VAR CurrencyFactor : Decimal;NextEntryNo : Integer;NextTransactionNo : Integer);`

***********
**2.-** 
```
...
  BankAccLedgEntry."Bank Acc. Posting Group" := BankAcc."Bank Acc. Posting Group";
  BankAccLedgEntry."Currency Code" := BankAcc."Currency Code";
  IF BankAcc."Currency Code" <> '' THEN
    BankAccLedgEntry.Amount := Amount
  ELSE
    BankAccLedgEntry.Amount := "Amount (LCY)";
  BankAccLedgEntry."Amount (LCY)" := "Amount (LCY)";

  //NEW CODE BEGIN>>
  OnChangeAmountsBankLedgEntryPostBankGenJnlPostLine(
  BankAccLedgEntry,GenJnlLine,BankAcc);
  //NEW CODE END<<

  BankAccLedgEntry.Open := Amount <> 0;
  BankAccLedgEntry."Remaining Amount" := BankAccLedgEntry.Amount;
  BankAccLedgEntry.Positive := Amount > 0;
  BankAccLedgEntry.UpdateDebitCredit(Correction);
  BankAccLedgEntry.INSERT(TRUE);
...
```
with new publisher
`LOCAL [IntegrationEvent] OnChangeAmountsBankLedgEntryPostBankGenJnlPostLine(VAR BankAccountLedgerEntry : Record "Bank Account Ledger Entry";VAR GenJournalLine : Record "Gen. Journal Line";BankAccount : Record "Bank Account");`

****
**3.-**  
```
...
          InitCheckLedgEntry(BankAccLedgEntry,CheckLedgEntry);
          CheckLedgEntry."Bank Payment Type" := CheckLedgEntry."Bank Payment Type"::"Manual Check";
          IF BankAcc."Currency Code" <> '' THEN
            CheckLedgEntry.Amount := -Amount
          ELSE
            CheckLedgEntry.Amount := -"Amount (LCY)";

          //NEW CODE BEGIN>>
          OnChangeAmountsCheckLedgEntryPostBankGenJnlPostLine(
          CheckLedgEntry,BankAccLedgEntry,GenJnlLine,BankAcc);
          //NEW CODE END<<

          CheckLedgEntry.INSERT(TRUE);
          NextCheckEntryNo := NextCheckEntryNo + 1;
        END;
...
```
with new pulbisher
`LOCAL [IntegrationEvent] OnChangeAmountsCheckLedgEntryPostBankGenJnlPostLine(VAR CheckLedgerEntry : Record "Check Ledger Entry";VAR BankAccountLedgerEntry : Record "Bank Account Ledger Entry";VAR GenJournalLine : Record "Gen. Journal Line";BankAccount : Record "Bank Account");`
