### ISSUE TITLE
Function Expose Request T1003 Job Planning Line

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#3905]
Please expose the UpdateAllAmounts function.

It would appear that the Jobs granule has received limited attention for use in an extension.  Is there a process that you perform to review areas or is it strictly reactive to developer requests?

**Comment by darjoo** [comment]
Hi @GreatScott000, is it possible for you to achieve what you are trying to do with any of the following calls to access the UpdateAllAmounts? `VALIDATE("Unit Cost")`, `VALIDATE("Unit Price")`, `VALIDATE("Line Amount")`, `VALIDATE("Line Discount Amount")`, `VALIDATE("Cost Factor")`, `VALIDATE("Line Discount %")`. We are trying to limit the amount of local functions being exposed.

It is strictly reactive to developer requests.

**Comment by GreatScott000** [comment]
I have to review the situation again.  The scenario is that I am adding an additional currency related fields for a currency other than Job currency and LCY.

**Comment by darjoo** [comment]
Thanks for the request, however, after evaluating it, we concluded that it isn't something we'll implement.
