### ISSUE TITLE
[Function expose] Table 7501 Item Attribute Value

### ISSUE THREAD

**Issue by hindsight2020** [Microsoft/AL#3906]
Hi,

could you please expose the function GetAttibuteValueTranslation. It does almost the same as GetTranslatedName which is already External, but is easier to use is most cases as it takes the Language Code instead of the Windows Language Id.

Thanks

**Comment by darjoo** [comment]
Hi @hindsight2020, we've decided to go ahead with your request. The function GetAttributeValueTranslation is now called GetTranslatedNameByLanguageCode and external. 
We usually include these types of changes in the next minor release, so look for it there.
