### ISSUE TITLE
Accessing AL functions in C/AL

### ISSUE THREAD

**Issue by mrabus** [Microsoft/AL#3907]
Hello all, I am playing around with some developments and try to move them from good old C/AL to AL. As there is quite a lot of work to be done, I try to leave some parts in C/AL and move them over part by part.

Now, I am at a dead end because I need a function I already transfered to AL in C/AL. Is it somehow possible to use/call a functions (for example in a codeunit) from an extension in AL (extension was of course published and installed)?
Acessing fields and tables should be possible by using RecRef and FieldRef.

**Comment by StanislawStempin** [comment]
Accessing AL symbols from C/AL is not possible. As you mentioned you can still access objects from AL if you access them by Id, using RecRef, FieldRef, but also for example Codeunit.Run(Id).
