### ISSUE TITLE
Problem on AL extension migration

### ISSUE THREAD

**Issue by misterzen85** [Microsoft/AL#3909]
Hello, I have a question about the AL Extension migration. How to modify an OptionString and a TableRelation in a standard table ? For example, I added a generic type on the "Type" field on the T39 and a TableRelation on the "No." field which points to my generic table. How can I migrate this in extension ? I saw on a forum that this would be possible in the future, is it true ? when ? 
Thank you.

**Comment by dNsl9r** [comment]
OptionString enhancement will be possible when field type option is changed to enum:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums

**Comment by misterzen85** [comment]
and for TableRelation, an idea ?

**Comment by dNsl9r** [comment]
I do not think it will be downgraded to NAV 2018.
In the current D365BC RC3 it is available.
For TableRelation I do not know how to deal with it, workaround could be to "double" the field..

**Comment by StanislawStempin** [comment]
Enum and enumextension are only available from Business Central Fall 2018 and will not be ported back to earlier releases.
Extending a conditional table relation is not yet possible but we are working on it.

**Comment by GreatScott000** [comment]
Can an EnumExtension be used in a CalcFormula?

**Comment by kalberes** [comment]
Not today but we have it in our backlog and we will get started on it soon.
