### ISSUE TITLE
Cannot modify the same 'Action' multiple times

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#391]
If we have modified 2 properties of same control/field then Txt2AL creating new sections which is causing issue.

severity: 'Error' message: 'Cannot modify the same 'Action' multiple times.'

![image](https://user-images.githubusercontent.com/23735402/28365812-a2eda96e-6ca7-11e7-8636-9bb223a6bf7b.png)

**Comment by Gallimathias** [comment]
Why do you do this in two sections?

**Comment by dennisfrostlander** [comment]
That's the output of txt2al conversion tool. It should not create multiple sections for no reason.

**Comment by pmohanakrishna** [comment]
any update please?
