### ISSUE TITLE
Bug: LookupPageId / DrilldownPageId on Table definition not working

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#3913]
I have a table that is defined something like this

````
table 123456 SomeTable
{

    Caption = 'An entry Entry';
    LookupPageId = 123456;
    DrillDownPageId = 123456
}
````

Furthermore I have a FlowField on Table 15 G/L Account that calculates it's values from this table. Just like so:

````
        field(123456; "ZheValue"; Decimal)
        {
            FieldClass = FlowField;
            CalcFormula =
                Sum ("An entry Table"."Amount" where (
                    "G/L Account No." = field ("No."),
                    "G/L Account No." = field (filter (Totaling))
                );
        }
````

If I add this FlowField to the chart of accounts, the values are correctly calculated. But I am unable to open the drilldown. I have tried setting **LookupPageId** and **DrilldownPageId** by ID or by name. Does not make a difference.

Furthermore. Code like this:

````
var
    ZheEntry: record "SomeTable";
begin
    ...
    Page.RunModal(0, ZheEntry);
    ...
````

Gives a "something went wrong"-error in the WebClient and on the RTC I get:

![image](https://user-images.githubusercontent.com/8897936/46293053-ae999d00-c592-11e8-8834-599fe5d7fcfb.png)

When I explicitly define the page to be run, it works correctly. The same goes if I define `DrilldownPageId` on the `FlowField` **on the page** where I add it.

I am on a freshly pulled docker image of BC bcsandbox-master:it v13.0.24691.0

**Comment by OleTeichmann** [comment]
Maybe try `DrillDown = true;` in your Page field. 
`Page.RunModal(0, ZheEntry);`cthrows an Error because you are trying to run a Page with the ID 0 (`procedure RunModal(Number: Integer, [Record: Table], [Field: Joker])`)

**Comment by hemisphera** [comment]
`Drilldown = true` does not change anything. Besides: BC already recognizes my fields as "drilldownable" because it shows the field with a link I can click on. This used to work a few releases ago, just like it did for years in NAV because it implicitly knew which table (and therefore wich page) to run. What sense do these properties have then?

`Page.RunModal` is not supposed to throw an error when the page ID given is 0. PageId = 0 means "use the default LookupPageId", just as it is clearly stated in the documentation (https://docs.microsoft.com/en-us/dynamics-nav/page-runmodal-function).

**Comment by OleTeichmann** [comment]
Oh ok I didnt know that 👍

**Comment by dennisfrostlander** [comment]
This is a recent regression, apologies for that. The fix is already made, it will be available on docker in the coming days.
