### ISSUE TITLE
Codeunit 12 "Gen. Jnl.-Post Line" method request

### ISSUE THREAD

**Issue by vlkov** [Microsoft/AL#3914]
Codeunit 12 "Gen. Jnl.-Post Line"

I would like to be able to call below methods in Codeunit 12.
**InitGLEntry**
**CreateGLEntriesForTotalAmounts**

**Comment by darjoo** [comment]
Codeunit 12 is designed for General Journal Posting, what are you attempting that requires the functions for General Ledger Entries in this codeunit to be external?
