### ISSUE TITLE
Application Object Tree

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#3917]
In AX we have an Application object explorer, it is very much the same as C/AL Object Designer but in a tree view.
I'm so missing out this visibility when doing development in AL. A couple of these abilities would make the development much easier.
- we able to see the existing standard code and even put a break point on them. 
- right click on any table/code unit public procedure to subcrible a pre and post event.

I'm looking forward for these features in the next AL update.

**Comment by AskeHolst** [comment]
While waiting I recommend the [AL Code Outline](https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline) extension for VScode. It does some of what you request.

**Comment by devhigh1992** [comment]
Thank you, I have been using that VS Code extension, It has many nice features .

I'm looking for the way to view existing standard actual code. Learning from existing standard code, the ready made library are very valuable.

**Comment by EmilDamsbo** [comment]
Today the AL Explorer (for all objects including dependencies) and project outline should serve this need, so I am closing this issue.
