### ISSUE TITLE
Codeunit 12 PostDtldCVLedgEntry

### ISSUE THREAD

**Issue by vlkov** [Microsoft/AL#3919]
Hi,
I need event OnBeforePostDtldCVLedgEntry(GenJnlLine: Record "Gen. Journal Line";VAR 
VAR DtldCVLedgEntryBuf : Record "Detailed CV Ledg. Entry Buffer",VAR AccNo : Code[20] ,Unapply : Boolean)

in CU12 "Gen. Jnl.-Post Line" Function PostDtldCVLedgEntry.

**Comment by IhorHandziuk** [comment]
PostDtldCVLedgEntry is a local function. Can you, please, explain why exactly do you need OnBeforePostDtldCVLedgEntry event?

**Comment by IhorHandziuk** [comment]
Hi, since this request hasn't been updated in a while we're going to shelf it. You can restart the process by submitting a new request.
