### ISSUE TITLE
The property 'DecimalPlaces' can only be set if the property 'Type' is set to 'Decimal'

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#392]
I have decimal variable in SourceExpr property of a page which is of type Decimal with DecimalPlaces property set.

![image](https://user-images.githubusercontent.com/23735402/28366043-9e2658f8-6ca8-11e7-8865-d29044d35fd7.png)

![image](https://user-images.githubusercontent.com/23735402/28366057-adf73d38-6ca8-11e7-9860-866db617113a.png)

Txt2Al converted them as Integer property which is causing issue

![image](https://user-images.githubusercontent.com/23735402/28366102-dbcadf80-6ca8-11e7-9cd3-58b52deb75f2.png)

severity: 'Error' message: 'The property 'DecimalPlaces' can only be set if the property 'Type' is set to 'Decimal''

**Comment by atoader** [comment]
Until we push out a better solution, this issue can be circumvented by replacing 0 with 0.0.
When we determine the type, we consider numbers without a decimal point to be integers. The compiler determines that the type of the field is Integer and it returns the above error.

**Comment by DominikDitoIvosevic** [comment]
problem: Wront type is inferred
current state: Right now the type is inferred from the source type.
potential solution:  The only way to go around this is to have an explicit way of specifying explicitly the type of the field. Either add a type specifying syntax like `(decimal)0` or `(0 : Decimal)` or a property in which you specify the type.

I don't believe any of these solutions are worth spending time and adding more complexity. A simple working solution is to specify that a number is decimal by using the decimal dot.
