### ISSUE TITLE
Codeunit 1 ApplicationManagement missing

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#3925]
Hi,

I just deploy the latest image version of Business Central. After downloading symbols, I have this error that appears for these code samples:

![image](https://user-images.githubusercontent.com/29598240/46336368-de947f00-c62a-11e8-990f-0beeddd63c1c.png)

![image](https://user-images.githubusercontent.com/29598240/46336376-e3f1c980-c62a-11e8-99c7-67f6e9618d3b.png)

![image](https://user-images.githubusercontent.com/29598240/46336342-cde40900-c62a-11e8-8bf9-ab96e528f855.png)

Is there now another way to access to these events ?

Thanks for your help!

- AL Extension Version: 2.0.48254

- Server Version: W1 13.0 (24844)

**Comment by DennisReinecke** [comment]
Codeunit 1 is removed
https://blogs.msdn.microsoft.com/nav/2018/09/12/new-system-events-replace-codeunit-1-in-business-central-october18-release/

**Comment by JulienDecottignies** [comment]
Thanks!
