### ISSUE TITLE
French characters in translation via extension

### ISSUE THREAD

**Issue by MarkusWinBI** [Microsoft/AL#3928]
I created a translation of the standard objects like described here

[https://docs.microsoft.com/de-de/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files](https://docs.microsoft.com/de-de/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files)

The problem is that the source language (french) uses characters that seem not to be suitable in ANSI? In Windows Client all french characters are "question marks". When I change the character set of the text file to UTF-8 or unicode, AL compiler no longer accepts the file:

file at location '...fr-FR_1.txt' does not match any definition.

In ANSI the AL Compiler states: 
file at location '...fr-FR_1.txt' matches the definition for 'TranslationFile'.

Example:
T36-F8-P8629-A1036-L999:Adresse (2Šme ligne)

![grafik](https://user-images.githubusercontent.com/42672449/46352496-39919a80-c65a-11e8-90dd-694ab46b04f9.png)

**Comment by MarkusWinBI** [comment]
I tried the second way described in the link:
---
Place the translated files on the server, or on each service instance in a /Translations folder. For more information, see this guidance.
---

and removed the file from the extension and republished. The result stays the same... "Mojibaake" in the client.

**Comment by titofffffff** [comment]
Hello Marcus,

I already have this type of issue. I'm french :)

the best wait to manage this is the following : 

1. extract translation file (file 1)
2. copy translation file (file 2)
3. do your translation (file 2)
4. copy/paste translation from file 2 to file 1

you have an issue because when you modify directly extracted file and save it your change the character set of the file from UTF8 to ANSI.

**Comment by MarkusWinBI** [comment]
> 
> 
> Hello Marcus,
> 
> I already have this type of issue. I'm french :)
> 
> the best wait to manage this is the following :
> 
>     1. extract translation file (file 1)
> 
>     2. copy translation file (file 2)
> 
>     3. do your translation (file 2)
> 
>     4. copy/paste translation from file 2 to file 1
> 
> 
> you have an issue because when you modify directly extracted file and save it your change the character set of the file from UTF8 to ANSI.

Salut Christophe,

I do not really understand what you mean. VS Code / the AL compiler only accepts language files (the .txt files as I want to translate the standard objects) that are encoded in ANSI

Best regards
Markus

**Comment by Kowa63** [comment]
The translation files which you get from C/SIDE are not in ANSI (=code page 1252) but rather Code page 850 (sometimes misnomed as ASCII).

The *.xlfs (XLIFF) and AL itself use UTF-8.
If you have existing C/AL objects and use a recent txt2AL converter it will generate XLIFFs in UTF-8.

For other sources, I have written several scripts to convert code pages in text files. You can adapt these for all existing ones, here OEM850->UTF-8 is suitable. 
http://www.msdynamics.de/viewtopic.php?f=17&t=25726&p=107219 
With GUI
http://www.msdynamics.de/viewtopic.php?f=17&t=25726&p=107219&#p129455

**Comment by Kowa63** [comment]
If you understand you correctly, you are trying to do this step here: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translation-and-localization-apps
Have tried converting the ANSI file from the translation service to code page 850? 
As mentioned, OEM850 is what comes out of NAV, ever since the days of DOS and the 'blue version'.
I've written a script for that direction as well, see above link ( ANSI1252 -> OEM850). 
A right or wrong code page in a text file can never be detected by a programme (only by visual examination),  but all currrent systems of course use ANSI for non-Unicode files. But the file format of NAV started 30 years ago, when OEM850 was normal.

**Comment by StanislawStempin** [comment]
Please let us know if you still encounter the problem that AL compiler doesn't recognize the file even when using code page 850

**Comment by MarkusWinBI** [comment]
> 
> 
> If I understand you correctly, you are trying to do this step here:
> https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translation-and-localization-apps
> Have you tried converting the ANSI file from the translation service to code page 850?
> As mentioned, OEM850 is what comes out of NAV, ever since the days of DOS and the 'blue version'.
> I've written a script for that direction as well, see above link ( ANSI1252 -> OEM850).
> A right or wrong code page in a text file can never be detected by a programme (only by visual examination), but all currrent systems of course use ANSI for non-Unicode files, the Unicode files can be detected by the BOM (Byte Order Mark) in the file header. But the file format legacy of NAV started 30 years ago, when OEM850 was normal.

Hi Kai,
danke für die aufschlussreiche Erklärung! Thanks for the very informative description. Funny that even 2018 creates the files from blue time, so everything stays blue! :-)

I tried your script, it worked, but seems the translation service creates some sort of different code page as 1252, the file is recognized but the text now looks even worse. 

The é for example lost its "e". ;-)

Can I somehow find out which codepage is used by translation service? @StanislawStempin perhaps you have good connections and can ask your colleagues? That would be very nice. :-) 
The windows editor states it as "ANSI" and it seems to be not 1252. 

Thanks for your help so far.
Markus

**Comment by Kowa63** [comment]
It might indeed be something different, ANSI stands for lots of code pages, 1252 applies to Western Languages only. 
Could you upload some lines of the file you received from the translation service with special characters?
Then I can try to convert these. Missing diacritic marks are usually caused by Unicode conversions which lack normalization.

The check the conversion before the compiler processes it, you can switch Notepad++ to display code page 850 correctly like this:
http://www.msdynamics.de/download/file.php?id=5296&t=1

**Comment by MarkusWinBI** [comment]
> 
> 
> It might indeed be something different, ANSI stands for lots of code pages, 1252 applies to Western Languages only.
> Could you upload some lines of the file you received from the translation service with special characters?
> Then I can try to convert these. Missing diacritical marks are usually caused by Unicode conversions which lack normalization.
> 
> To check the conversion before the compiler processes it, you can switch Notepad++ to display code page 850 correctly like this:
> http://www.msdynamics.de/download/file.php?id=5296

Hi Kai,
the funny thing is: if I open the original file from translation service in Notepad++ it and switch to Code 850 the strings are displayed correctly. The source is displayed to be encoded in "ANSI". :-)

Attached you find a sample of the file.

[fr-FR_sample.txt](https://github.com/Microsoft/AL/files/2471963/fr-FR_sample.txt)

Thanks for your help
Markus

**Comment by Kowa63** [comment]
Yes, the sample file is already in code page 850, pure and simple. So if that turns out wrong in the extension the AL compiler presumably now expects code page 1252 or maybe ISO 8859-1. I've got scripts for both conversions (added one for OEM850->ISO 8859-15 just now), same link above.

**Comment by MarkusWinBI** [comment]
> 
> 
> Please let us know if you still encounter the problem that AL compiler doesn't recognize the file even when using code page 850

Hi Stanislaw,

can you perhaps tell us which codepage the AL compiler is expecting for correctly displaying "funny characters"? :-)

Thanks very much
Markus

**Comment by PooyaKharamesh** [comment]
Hi All,

The translation file should be encoded in UTF-8 to support the special characters. For the on-prem versions, make sure to use the correct collation in your DB, so sorting and search for example in the customers' name with special charecters also works fine.

Regards
Pooya

**Comment by MarkusWinBI** [comment]
Hi PooyaKharamesh,
sorry, but please see the original request! ;-)
Files encoded in UTF-8 are not accepted by the AL compiler! Translation of "native" = original NAV objects can only be translated via .txt files, not .xlfs
Please re-open this as I still do not have a clue how to do this!
Thanks
Markus

**Comment by PooyaKharamesh** [comment]
Thank you Markus,

I could successfully use both txt and xlfs files to translate strings contain special chars. It works both on win and web client.

would you please send us the code that you have or your sample code in a zip file?

![translation](https://user-images.githubusercontent.com/39521917/48847382-afd09480-eda1-11e8-9cb0-2bad13e080b2.png)

Regards
Pooya

**Comment by MarkusWinBI** [comment]
[Translation.zip](https://github.com/Microsoft/AL/files/2604608/Translation.zip)

Hi Pooya,
on your Screenshot you see exacly the wrong characters. :-)

2..me ligne should be 2ème Ligne

Attached you find the txt file I received from MS Translation Service and the one coded with OEM850

Both do not show the correct "funny characters" in NAV. ;-)

The same with the äöü in the "german text" sample.

Best regards
Markus

**Comment by PooyaKharamesh** [comment]
Hi Marcus,

Those are exactly the chars that I put in the file and are shown as expected.

I also converted your translation files encoding and I can see that all the special chars are shown correctly. The same result for the German special chars, äöü.

Please notice that the fr-FR.txt does not have the correct encoding and needs to be converted -using an external tool (e.g VS code , Notepad ++ , ...)- to UTF-8. In vs code, you can use the Command Palette (Ctrl+Shift +P) and search for "Change File Encoding". Try to reopen the file with encoding and choose OEM-850, then change the encoding, using the same command and this time save with encoding, make sure to choose UTF-8. 

![translation](https://user-images.githubusercontent.com/39521917/48897408-4e183500-ee4a-11e8-9943-adae7df74bee.jpg)

/Pooya

**Comment by r4luk** [comment]
Hello everyone,
We are working on an Eastern European translation for BC (ro-RO). 

We tried to use the file we got from Microsoft Dynamics Lifecycle Services, but for our language is translated word by word and most of the translations are not correct or don't have the correct meaning.

We imported our old translations from NAV 2018 to BC and i exported the .txt file, which has of course ANSI encoding.
I tried to covert the file to UTF-8 (with VS code and also notepad++), but i don't get the correct diacritics. We have ăîâţş. And for example for ă we have Ç (in UTF-8).

How can we correct this?

Thanks a lot.
Raluca

**Comment by Kowa63** [comment]
If you export from C/SIDE with the regional OS settings in Romania, the code page for Central Eastern Europe should be 852.
I've got conversion scripts for that too here:
http://www.msdynamics.de/viewtopic.php?f=17&t=25726

Look for: Convert_OEM852_UTF8_Dlg

**Comment by r4luk** [comment]
Hello,
Thank you very much. It didn't work for us :( but it was a starting point and we resolved this.

What did you do about the resources? I didn't find the Partner Translation Toolkit for BC.
How did you translate them?

Raluca

**Comment by MarkusWinBI** [comment]
Hi Raluca,

can you please share the solution? As the standard objects can still only be translated via .txt files which the compiler still does not accept in utf-8 ;-)

Best regards
Markus

**Comment by r4luk** [comment]
Hi Markus,
We did the following steps:
1. export .flm from NAV 2018 (Export -> Language module)
2. import .flm from C/SIDE in BC
3. export with powershell the objects in .txt to correct the modified captions and to fill in the captions for the new translations with UTF-8 encoding (careful that some tables, pages and reports are skipped by powershell, so they will be done manually)
4. import again from C/SIDE using powershell the new version of .txt
5. export from C/SIDE using Translate -> Export the .txt that then we put in the extension and it compiled perfectly, also with the correct

**Comment by phenno1** [comment]
If this could be helpful, I had similar issue (Bosnian charset with special characters) and found rather easier solution. 

What I have done is:
1) export CSIDE objects as txt.
2) Using development module shell, command Export-NAVApplicationObjectLanguage -Source objects.txt -Destination translation.txt -LanguageId BSB -Encoding UTF8 -Force
3) Open translation.txt in VStudio Code (which says it's encondig is  "UTF-8 with BOM", and in that way cannot be published
4) Save translation.txt as UTF-8 encoding

After that, publish worked properly and I've got all characters ok. 

Regards, 
Ph

**Comment by r4luk** [comment]
Thanks a lot, phenno1. 

It works like a charm. :)
