### ISSUE TITLE
In Dynamics 365 Bussiness Central, Everytime i create a new folder and write code in it I get new Extensions published...How can i combine these Extensions in one 

### ISSUE THREAD

**Issue by adityasalwan** [Microsoft/AL#3929]
- AL Extension Version: 

- Server Version:

**Comment by strophanthus** [comment]
Are you changing the app ID every time?

**Comment by AmolSalvi** [comment]
Why you are creating different folder for every al file  ?.You should create different .AL file in one folder.
Within that same folder you can create different sub folder to hold different object file like codeunit,tables etc.

**Comment by kalberes** [comment]
We also support multiroot workspaces for AL language server in  VsCode.

**Comment by StanislawStempin** [comment]
You should not be creating a new extension for each al file but instead create new al files in the same project in the root folder or any subfolder.
