### ISSUE TITLE
'Internal error: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.FieldModificationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.FieldSyntax'.', Stack trace=unknown'

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#393]
Any thoughts on this error?
It is pointing at Codeunit word.

severity: 'Error'
message: 'Internal error: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.FieldModificationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.FieldSyntax'.', Stack trace=unknown'

![image](https://user-images.githubusercontent.com/23735402/28366232-7259e1da-6ca9-11e7-8823-29c9721b9c53.png)

**Comment by dennisfrostlander** [comment]
@pmohanakrishna  The compiler went a little crazy here. Would you be able to narrow down the scope for us a little?
- Try AL:GO and paste this codeunit into the HelloWorld.al - will it fail with the same error?
- If it fails in isolation, could you try removing the pieces until you find the one which is causing the issue?
