### ISSUE TITLE
Event modify OnBeforeCreateRegActivHeader CU7307

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#3930]
Hi,

in the event "OnBeforeCreateRegActivHeader" in CU7307 is missing handling of RegisteredInvtMovementHdr. In case WhseActivHeader is of "Invt. Movement" type and external handling is true, the registered header will be uninitialized.

Similarly in "CreateRegActivLine" is missing the "OnAfterInitRegMovementLine".

Thank you
S.

**Comment by AlexanderYakunin** [comment]
Sorry, COD7370 does not exist in base application. Please correct you ask.

**Comment by sgiordy** [comment]
> Sorry, COD7370 does not exist in base application. Please correct you ask.

Sorry, was COD7307 :)
