### ISSUE TITLE
Publish .app in  customer Sandbox for tests

### ISSUE THREAD

**Issue by giann85** [Microsoft/AL#3931]
Hello,
I have developed an extension in my environment. I created the .app file and I want to install it in the client's sandbox environment for testing. How can I publish it without going through the whole project and publishing it via VSCode? Possible that there is not a way? the version is the latest Italian.

Thanks

**Comment by pzentner** [comment]
If it's a tenant specific extension, you should be able to upload the file through extension management in the web client. You can deploy extensions there. However, you cannot publish "AppSource apps", so the extension must be defined as "internal".

**Comment by StanislawStempin** [comment]
Currently the only way to publish your own apps to Online Sandboxes it to publish them from VS Code with Ctrl + F5 or F5. The Upload button is not available on sandboxes and can only be used on Production tenants. We are planning to enable it on sandboxes in the future.

The comment above about "Internal" is not correct.  Target = Internal mens the app is targeting On-Premises. For any apps targeting the cloud you have to use target = Extension. 
Target Internal will be rejected when trying to publish in the cloud.

**Comment by tecturahk** [comment]
> Currently the only way to publish your own apps to Online Sandboxes it to publish them from VS Code with Ctrl + F5 or F5. The Upload button is not available on sandboxes and can only be used on Production tenants. We are planning to enable it on sandboxes in the future.
> 
> The comment above about "Internal" is not correct. Target = Internal mens the app is targeting On-Premises. For any apps targeting the cloud you have to use target = Extension.
> Target Internal will be rejected when trying to publish in the cloud.

Can we get some hints how can we connect the visual studio code directly to the online sandboxes? I mean where can we get the linke of "server" and "serverinstance" of a online sandbox, which need to be defined in the launch.json file? Thanks.

**Comment by giann85** [comment]
when you create a new project on VSCode , it ask you what server do you want to use: select   Microsoft Cloud Sandbox and   insert your credentials (the same of web client).
The file launch don't have   server, serverinstance and authentication.
If you don't have inserted credentials , no problem:  launch  "Clear Credentials Cache" (from  Ctrl+Shift+P  and search it) and when you  download symbols or deploy ,  window pop-up ask you credentials.

**Comment by tecturahk** [comment]
Thanks a lot! Why did I miss this part?!

**Comment by tecturahk** [comment]
> when you create a new project on VSCode , it ask you what server do you want to use: select Microsoft Cloud Sandbox and insert your credentials (the same of web client).
> The file launch don't have server, serverinstance and authentication.
> If you don't have inserted credentials , no problem: launch "Clear Credentials Cache" (from Ctrl+Shift+P and search it) and when you download symbols or deploy , window pop-up ask you credentials.

Sorry, it's me again. I tried to setup a project and selected the Microsfot Cloud Sandbox. I am sure the login is correct but I am not able to download synbols. It shows "Reason: You do not have the following permissions on TableData NAV App: IndirectRead.".

I tried to update the user permission setting. The "D365 EXTENSION MGT" is there and the "COMPANY NAME" is blank. However, it still does not work. Any hints?

**Comment by StanislawStempin** [comment]
The permission error for NAV App Indirect Read is fixed for the next major version of Business Central.

On the current version you need to log in with the same user to the same sandbox via the web client and the permissions will get correctly initialized. Just make sure you're logging into the exact same sandbox. If you still encounter issues please contact the regular support channel.
