### ISSUE TITLE
"editor.formatOnSave": false not respected

### ISSUE THREAD

**Issue by larswestman** [Microsoft/AL#3935]
Today my VS Code started formatting automatically on save. If I disable the AL extension it does not so it's a "feature" in the latest vsix

**Comment by larswestman** [comment]
OK. It the autoformat actually does a good job.... Not the way I'm used to, but I guess I'll get used to it :-)

**Comment by thpeder** [comment]
For future references: if you want to disable that you can change it in your settings, like so:
`"[al]": { "editor.formatOnSave": false }`
