### ISSUE TITLE
[License issue?] Extension settings page not available when I publish my license

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#3936]
Hi,

As I have an extension which makes calls to external web services, I want to configure it in order to enable HTTPClient requests.
I pull the last Business Central image, and at the first run, I can access to the Extension Settings page:
![image](https://user-images.githubusercontent.com/29598240/46396263-30064200-c6ef-11e8-91c0-aa1ce1506861.png)

At this time I have the Cronus license, and as it's not possible to publish my extension with these id range, I published my partner license.

First way: by Import-NavContainerLicense powershell command
When i click to Extension Setting Page I have this following error message:
![image](https://user-images.githubusercontent.com/29598240/46396345-76f43780-c6ef-11e8-9f7c-5e417d267906.png)

Second way: changing license by the C-SIDE client:
The Extension Settings page doesn't appear anymore in the search results:
![image](https://user-images.githubusercontent.com/29598240/46397007-50cf9700-c6f1-11e8-92a9-923cbc5d2e8a.png)

At this time I didn't yet publish any extensions, this is just the effect after publishing my license..!

So now, after publishing my extension I can't get rid of this window
![image](https://user-images.githubusercontent.com/29598240/46397133-b0c63d80-c6f1-11e8-8909-e33f018c5639.png)

Thanks for any help

- AL Extension Version: 2.0.48254

- Server Version: W1 13.0 (24844)

**Comment by StanislawStempin** [comment]
We are in the process of updating Cronus license. Stay tuned

**Comment by StanislawStempin** [comment]
By now this should have been fixed. Please log a new issue if this is still a problem in a license that is freshly obtained.
