### ISSUE TITLE
TAB key doesn't trigger onValidate event (TO DELETE)

### ISSUE THREAD

**Issue by jpagessummar** [Microsoft/AL#3937]
SORRY: It's my fault. Don't pay attention.

Hi
When you change of field in a page through TAB key, the onValidate event in the page doesn't trigger. But if you press the ENTER or RETURN key, it does.

- AL Extension Version: 2.0.48254
- Server Version: ES Dynamics NAV 12.3 (23918) - Sandbox

                        field("AccPurch"; AccPurch)
                        {
                            ApplicationArea = all;
                            Caption = 'Purch.';

                            trigger OnValidate()
                            var
                                AccRec: Record "G/L Account";
                            begin
                                if AccPurch <> '' then
                                    AccRec.Get(AccPurch);
                            end;

                            trigger OnLookup(var Text: Text): Boolean
                            var
                                AccRec: Record "G/L Account";
                                AccPag: Page "G/L Account List";
                            begin
                                if AccPurch <> '' then
                                    if AccRec.get(AccPurch) then
                                        AccPag.SetRecord(AccRec);
                                AccPag.LookupMode(true);
                                if AccPag.RunModal() = Action::LookupOK then begin
                                    AccPag.GetRecord(AccRec);
                                    AccPurch := AccRec."No.";
                                end;
                            end;
                        }

**Comment by qutreson** [comment]
Closing this issue as it seems not to represent a problem anymore.
