### ISSUE TITLE
GETURL functionality does not work with variant

### ISSUE THREAD

**Issue by Kraver88** [Microsoft/AL#394]
Hey,

I get this error:

**[AL] The call is ambiguous between the following methods or properties: 'GetUrl(ClientType, Text, ObjectType, Integer, RecordRef, Boolean)' and 'GetUrl(ClientType, Text, ObjectType, Integer, Table, Boolean)'**

 when I try to use this code:
"GetUrl(CurrentClientType, CompanyName,ObjectType::Page,WorkflowStepArgument."Link Target Page",PVar_Variant)"

This code works in the old developer so I'm guessing you forgot the option to use Variants with that function.

**Comment by atoader** [comment]
GetUrl has two overloads, once accepting a RecordRef and one accepting a Table as the 5th argument. You are passing a Variant which can be converted, with the same priority, to both types. The compiler cannot decide which conversion is better so it cannot decide which overload is 'better'. 
A workaround would be to assign PVar_Variant to a RecordRef or Record variable and pass that to GetUrl.

**Comment by Kraver88** [comment]
Yes I know what the workaround would be but the old development environment manages just fine with this so I was hoping this new one could manage as well.

**Comment by atoader** [comment]
The old environment managed to do this and more magic by having a large number of special cases hard-coded. We will look into it to see if we can roll out a better solution.
