### ISSUE TITLE
Can't seem to make a ruleset effective.

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#3941]
Using BC 1810 release.

I am trying to get a ruleset active and I can't seem to make it work.  I had this working back in July on a different test project (long since deleted) but with the October release I cannot get it to work.

I am getting this warning when I add `"${CodeCop}"` to  `"al.codeAnalyzers":` 

> Only use BEGIN..END to enclose compound statements.

This message is perfectly valid but I want to turn it off (the reasons do not matter).

So I create a ruleset with a rule as follows and put it in the root folder of my project.
```
{
    "name": "iMS Project ruleset",
    "description": "A list of company specific rules",
    "includedRuleSets": [
        {
            "action": "Default",
            "path": "./ims.ruleset.json"
        }
    ],
    "rules": [
        {
            "id": "AA0005",
            "action": "None",
            "justification": "Only use BEGIN..END to enclose compound statements. For this specific project, this diagnostic should be informational."
        }
    ]
}
```
and put this line in `"al.ruleSetPath": "."` in my user settings section of settings.json.  
When I do that I see this message in my "Problems" window:

> An error occurred while loading the included rule set file <longish folder path>\AL\ESM - Access to the path '<longish folder path>\AL\ESM' is denied.

I don't see this as a Windows file permission error as this is my project folder and I can read/write to this ruleset.json and other files in my project via VS Code.  I have tried putting the ruleset in other folders as well and I get the same message.

I have gone through everything here: [Using the Code Analysis Tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool) I bet I am missing something obvious but I don't see it.   

 Help please.

AL Language extension version: 2.0.48254
VS Code Info:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by pzentner** [comment]
> and put this line in "al.ruleSetPath": "." in my user settings section of settings.json.
When I do that I see this message in my "Problems" window:

If I read the "al.ruleSetPath" description, it should point to the actual file with the rules, not to a directory. I think that you are getting this error, because the file "." doesn't exist.

**Comment by GreatScott000** [comment]
Okay, so making that change resolved the error but the rule is not taking effect.  Is there something wrong there?

**Comment by atoader** [comment]
Did you reload the project after changing the ruleset? This is a known limitation: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool-with-rule-set#limitations .
I have tried the following ruleset : 
```
{
    "name": "iMS Project ruleset",
    "description": "A list of company specific rules",
    "rules": [
        {
            "id": "AA0005",
            "action": "None",
            "justification": "Only use BEGIN..END to enclose compound statements. For this specific project, this diagnostic should be informational."
        }
    ]
}
```

on the following snippet:
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        begin
            Message('App published: Hello world');
        end;
    end;
}
```
and everything works as expected.

**Comment by GreatScott000** [comment]
This is now working.  I am not sure what changed.  I had reloaded the project several times.  Thanks for the help.
