### ISSUE TITLE
Error with the new version of AL Langauge extension (2.0.48254)

### ISSUE THREAD

**Issue by ftornero9** [Microsoft/AL#3942]
Today the AL Language extension has been updated to 2.0.48254 and with that version I get this error when I try to publish an extension to the Microsoft cloud sandbox.

![image](https://user-images.githubusercontent.com/12720964/46426162-0294b500-c73e-11e8-825b-4acaf2200c72.png)

It's the same error that I got when installed the AL Language extension delivered with the RC3 (2.0.43900) and that I solved reinstalling the version 0.16.19969 and disabling the new one.

I need to get a new Sandbox or is there another solution ??

Regards.

**Comment by AmolSalvi** [comment]
May be this link will be helpful 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions

**Comment by SirBETE** [comment]
And also [Steven Render's blog](http://thinkaboutit.be/2018/10/how-do-i-set-the-runtime-version-of-the-extension-package/)

**Comment by ftornero9** [comment]
Ok, problem solved.

Thank you all @SirBETE and @AmolSalvi 

Regards.

**Comment by AmolSalvi** [comment]
Welcome @ftornero9
