### ISSUE TITLE
Issue on Business central Extension Page.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#3943]
Hello experts,

I need your attention here, as I am facing an unexpected error in BC while opening extension page.

I was tried to add bank account in BC, but in my BC instance I am not able to see a action **Bank statement service** on Bank account page. Like below.
![screenshot 38](https://user-images.githubusercontent.com/33481576/46428278-31705280-c761-11e8-8b28-67af6e680dc3.png)

And when I tried to open extension page to set up YODLEE extension( For setting up online bank account) , I got a message like below.
![image](https://user-images.githubusercontent.com/33481576/46428342-59f84c80-c761-11e8-894c-8aa42ce1da05.png)

Can anyone get me out of this error?

Kind Regards
Sudarshan

**Comment by StanislawStempin** [comment]
It seems you upgraded from Invoicing to Business Central. In that case you cannot use extensions.
Please contact your CSP or Microsoft Support as instructed by the message that you pasted above.
