### ISSUE TITLE
Migration plan from on Prem NAV2017/2018 to BC

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3944]
Hey guys, in the last weeks I have developed some extensions for Business Central based on some adjustements in NAV2017 ( I did also an upgrade to NAV2018). 

Now I would like to know, if there is a migration plan to migrate all my data - I have in the old system - into BC? I have seen, that we have kind of interface in BC called "Data Migration". Is this the only and also easiest way to migrate data? Do I have to pay attention on anything? Are there any pitfalls, so I could lose data?

The special thing is, I have objects in the old system (NAV2017), in BC they will be represented by my extensions, but what happens to the data? Imagine, I have fields in some tables and also data behind them, the tables and so on are not in the standard, now I created some extensions for them, but what happens to the data behind that fields during the migration? Do I have to create some temporal objects to save the in the meantime?

**Comment by StanislawStempin** [comment]
Please see if this topic answers your question:
https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-v1-to-v2-overview

**Comment by LauraNicolas** [comment]
@malue19 This topic was also discussed here: https://github.com/Microsoft/AL/issues/1689

I hope it helps.

Salut!
Laura Nicolàs
