### ISSUE TITLE
Dynamics 365 BC Installations fails when installing or detecting iis prerequisites 

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#3945]
The installation of the brand new Dyn 365 BC onPremise fails if the setting:
IIS Prerequisites: Install or Detect is set.

The Installation is rolled back with this error message:
![image](https://user-images.githubusercontent.com/33752561/46463749-e851ea00-c7c4-11e8-8b52-0a7194ff63ad.png)

The only way to install it is to skip the prerequisites

This has been tested on 
- Windows 10 (1607) 
- Windows 10 (1803)
- Windows Server 2008 R2

**Comment by thpeder** [comment]
Hi @peikba,
Could you please attach the installation log?

**Comment by StanislawStempin** [comment]
Please contact the regular support channel if you're still hitting this problem.
