### ISSUE TITLE
Upgrading to Dyn 365 BC from NAV 2018 gives an unnecessary warning

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#3946]
The following warning is shown when installing a Dyn 365 BC on top of a NAV 2018.

It does not have any effect and everything works, but the Installation looks like it failed:

![image](https://user-images.githubusercontent.com/33752561/46463993-96f62a80-c7c5-11e8-821c-2b3f02f90e2b.png)

This was also the case Upgrading a NAV 2018 to a newer CU

**Comment by StanislawStempin** [comment]
This turned out to be a bug that has now been fixed.
