### ISSUE TITLE
Migrate FILE.EXISTO to BC

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#3948]
Hi,

I am trying to migrate Migrate FILE.EXISTO to Business Central, I check multiple post that explain how has been deprecated and they tell that I have to use Codeunit File Management to solve the problem.

I'm working on it but I can't solve the problem:

**Old code:**

`if FILE.EXISTS(filePath) then begin`

**New code (migrated):**

`if FileManagement.ClientFileExists(filePath) then begin`

I am adding this code in a Codeunit but and Visual Studio Code is giving this error:

**_The type or method 'ClientFileExists' cannot be used for 'Extension' development._**

How I can use File Management Codeunit in one of my Codeunit? Someone find a way to do it?

Thanks for your time,

**Comment by CanuckNav74** [comment]
Following this one. 

I know this is not possible for OnCloud (*no* filesystem i/o period), but is there a way to access on-prem internal functions from an extension? If so, what's the trick?

This is the URL for the JSON structure and it doesn't say anything about how to target an extension for on-prem only. 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files

**Comment by dNsl9r** [comment]
> I know this is not possible for OnCloud (_no_ filesystem i/o period), but is there a way to access on-prem internal functions from an extension? If so, what's the trick?

Sure. You have change the Targetlevel in the app.json to internal.
`"target": "Internal"`

**Comment by CanuckNav74** [comment]
@dNsl9r thank you! The "target" property was in the the docs all along. My bad. Don't know how I missed it.

**Comment by Drakonian** [comment]
Same questions, what to do when need to create or read .TXT file from client side?

**Comment by StanislawStempin** [comment]
You can use File.UploadIntoStream
