### ISSUE TITLE
Codeunit 229 Procedure PrintSalesHeader

### ISSUE THREAD

**Issue by stephanweidmann** [Microsoft/AL#3949]
Hi,

is there a reason that function PrintSalesHeader is not external?

Most of the functions in this codeunit are external, but not this one.

Build is BC On Premise Release

Best Regards,
Stephan

**Comment by darjoo** [comment]
Hi @stephanweidmann, this function was made external in preview 24477 last month. If you update your preview version, you should be able to use it.

**Comment by stephanweidmann** [comment]
Thank you.
