### ISSUE TITLE
 The debugger options cannot be used for this server. in Dynamics 365 Business Central

### ISSUE THREAD

**Issue by adityasalwan** [Microsoft/AL#3952]
- AL Extension Version: 

- Server Version:

**Comment by adityasalwan** [comment]
![debugger](https://user-images.githubusercontent.com/30633451/46476286-63d38b80-c805-11e8-9c36-cff3a4349805.PNG)

**Comment by StanislawStempin** [comment]
Closing the issue. No version of AL Extension or Server was specified.

**Comment by AbsolutelyFreeWeb** [comment]
I have the same issue with the new NAV container version: 13.0.24630.24844-US 
Let me know what else you need.
Can closed issues be re-opened?
