### ISSUE TITLE
AL Dialog limitations from BC web client?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#3955]
One of the biggest reasons I find to utilize the dialog datatype is to augment long running processes (such as processing thousands of records). In the windows client this works wonderfully well in the past. 

In the web client for however, the business central dialog doesn't have a cancel button. Furthermore, it doesn't update nearly as frequently as the same dialog in the windows client. 

The lack of a cancel button especially is not an easy pill to swallow. A web client user cannot cancel out of a long running operation. 

Does Microsoft have anything on the roadmap to address this?

**Comment by StanislawStempin** [comment]
Answer from the client team:
We are aware that cancelation action is missing in the WebClient and we are continuously working on improving capabilities of the WebClient. At this moment, I can't definitely answer when it will be available in the WebClient.

**Comment by CanuckNav74** [comment]
@StanislawStempin thank you for the update. 

I didn't find any "feature limitations" documentation specific to BC, but I did find this for NAV2018:

https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client

It doesn't mention anything about the missing cancel action for dialogs

**Comment by StanislawStempin** [comment]
You can log a documentation issue on the Docs site and the missing limitation will be added.

**Comment by CanuckNav74** [comment]
@StanislawStempin duly noted - I've since logged an issue to the docs site.
