### ISSUE TITLE
Unable to connect neither to C/Side nor to RTC

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#3958]
Hi,
after pulling latest docker images (13.0.24937.0-W1 and 13.0.24630.0-W1) I'm not able to connect neither to C/Side nor to RTC. When connecting to web client it only works if using IP address (DNS seems not to work). I'm using latest version of navcontainerhelper.
Is this issue with my machine or was there something changed?

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
