### ISSUE TITLE
Ability to change location of dependency packages

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/AL#396]
Can we get a change so that we can define where the dependency packages are stored? Right now they have to be placed in the same package folder as the standard NAV packages, but this makes using dependent packages difficult.

Example:
I have 3 apps that all use the same library extension. Right now I have to copy the library package into each of the app package folders. What I'd like to do is create a central folder because anytime the library extension changes, I want all of my apps to be updated to use the new version, and copying the library package multiple times on my development machine is messy.

Alternatively, if it was possible to have the download symbols function download dependency packages from a folder location into the packages folder, then that would suffice as well. We'd then be able to store dependent packages wherever and organized however we want and have them pull into the development environment automatically.

**Comment by dennisfrostlander** [comment]
This is possible. The path to a folder is stored in the settings.json file and is defaulted to ./packages
In order to change it, press Ctrl+comma (or F1 -> Open user settings) and add the following key:
```javascript
{
    "al.packageCachePath": "MyFolder"
}
```

The path could be either relative to a project or an absolute one.
You can also choose whether to store this configuration in the workspace settings (settings.json per-project) or globally for your user (settings.json for your user).

**Comment by MikeGlue** [comment]
The problem though is that this setting changes the package folder for all of the dependent packages. 

What I really want to do is pull the standard NAV packages from the one folder, and have my 3rd party dependent packages pull from other places. This way I can more easily manage my dependent packages by keeping them in separate folders. Within each app, all I need to do then is manage which version of each dependent package I need to use.

**Comment by dennisfrostlander** [comment]
Ok, then I'll mark this as a suggestion, but that would need to undergo a further consideration.

**Comment by DominikDitoIvosevic** [comment]
I suppose we could have a property in the manifest file in which you specify the location of the package folder. How does that sound @dennisfrostlander ?

**Comment by atoader** [comment]
@MikeGlue check out the latest developer preview https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ . It contains several improvements to how you can work with multi-project workspaces. 
Those improvements should remove the need for this feature.
