### ISSUE TITLE
Codeunit 5601 Function GetBalAcc Event  OnGetBalAccAfterSaveGenJnlLineFields

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/AL#3961]
For injecting our code and evtl. overriding existing InsertBufferBalAcc we need to expand the event with a bool handler.

Instead of:

  OnGetBalAccAfterSaveGenJnlLineFields(TempGenJnlLine,GenJnlLine);
   InsertBufferBalAcc(
      "FA Posting Type" - 1,-Amount,"Depreciation Book Code",
      "Posting Group","Shortcut Dimension 1 Code","Shortcut Dimension 2 Code","Dimension Set ID",FALSE,FALSE);

We need:

 OnGetBalAccAfterSaveGenJnlLineFields(TempGenJnlLine,GenJnlLine, handler);
 IF NOT handler then  
 InsertBufferBalAcc(........................

**Comment by AlexanderYakunin** [comment]
This is already implemented, see

  SkipInsert := FALSE;
  OnGetBalAccAfterSaveGenJnlLineFields(TempGenJnlLine,GenJnlLine,SkipInsert);
  IF NOT SkipInsert THEN
    InsertBufferBalAcc(
      "FA Posting Type" - 1,-Amount,"Depreciation Book Code",
      "Posting Group","Shortcut Dimension 1 Code","Shortcut Dimension 2 Code","Dimension Set ID",FALSE,FALSE);
