### ISSUE TITLE
AL Pages where PageType = API: field name validation too strict

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#3962]
I think the AL Language compiler is a little too strict on how API page fields are named. 

Say I want to expose a field BlobValueEncoded64 on an API page. The compiler won't let me.

`(The name of field controls in pages of the type API must not include spaces or special characters.)`

I undertand the need to prevent these field names prefixed with a number, but it should be perfrectly allowable to allow a number in a an API field if the number isn't in the first character.

**Comment by qutreson** [comment]
Hi @CanuckNav74, this is something that we have noticed as well. The fix will be available with the next developer preview.
