### ISSUE TITLE
BC Web Client: Report request page limitations?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#3965]
Say I developed an AL report and one of the RequestFilterFields is an option field on a table. 

In the BC windows client, I can select multiple values on on that filter field since the option picker is multi-select. 

In the web client, I can't do that. I can only select zero or one option. ctrl-clicking has no effect.

Will Microsoft address this in the future to make the web client report request page something that is more feature parity with the windows client?

**Comment by CanuckNav74** [comment]
To add to this, I noticed that if I perform a setfilter on an option field of a data item with boolean operators, it crashes the web client. It will crash if the filtered table is passed into the report via report.run(...), and will crash if the filter is set internally in the report itself (e.g. in the request page OnOpenPage.

It's almost as if the web client reporting does not like multi-option filtering at all. 

Samples (assume the TableMetaData refers to Record "Table Metadata")

```
//TableMetadata.SetFilter(ObsoleteState, '%1|%2', TableMetadata.ObsoleteState::No, TableMetadata.ObsoleteState::Pending); // <<-- this crashes the web client
            //TableMetaData.SetFilter(ObsoleteState, 'No|Pending'); // <<-- this crashes the web client
            TableMetaData.SetRange(ObsoleteState, TableMetadata.ObsoleteState::No); // <<--this doesn't. conclusion: the web client doesn't like multi-option selects.
```

**Comment by CanuckNav74** [comment]
any update?

**Comment by thpeder** [comment]
Reply from the team:
Option field support is in our backlog and we are continuously working on improving Web Client experience. At this point, I can't provide more specific information on when the feature will be available in the Web Client.

**Comment by mikebcMSFT** [comment]
Just a brief update: 
We announced in early June 2019 that this is part of our release plan for next major update: [https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/filtering-option-fields-multiple-values](https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/filtering-option-fields-multiple-values)

We expect to announce through our usual social media channels once this becomes available to Insider Builds for you to try out.

best regards,
Mike and the Business Central team at Microsoft
