### ISSUE TITLE
Timepicker

### ISSUE THREAD

**Issue by Frederig** [Microsoft/AL#3966]
In the webclient on a field of the type Time, you get a datepicker presented for entering the value.
When selecting a date like today 5/10/2018 and press enter, it transforms to a time 5:10:20.

Suggestion: disable datepicker as it makes no sense. 
If possible it would be nice to have it replaced by a timepicker similar as what we know from selecting time on smartphones.

**Comment by dennisfrostlander** [comment]
It was addressed in #2628. The popup was removed.
