### ISSUE TITLE
How to protect our extension code ?

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#3967]
Hi All,

I made showmycode property in my app.json as false, so on debugger I am not able to see my code and same is not available for download which is right.

But now if I try to open my .app file on tools like winrar then it opens all related .al files and all content of vscode in fully readable format which can easily use used by some other developer.

please suggest the right way to protect our extension code.

Thanks!
Rishabh.

**Comment by AmolSalvi** [comment]
App file need to digitally signed to avoid tampering
More details on this link
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension

**Comment by rishiaurrishabh** [comment]
Hi @AmolSalvi ...I already tried that it does give password to your app file but you can still see your code once you open that file on winrar .
my point here is to do not share my code by any means if showmycode is false.
like .DELTA files, if you open navx file from winrar you will see encrypted format in the file.

Thanks..Rishabh.

**Comment by AmolSalvi** [comment]
If that's the case then I think Microsoft need to answer on the same. May be there is some properties need to set in JSON files .
@StanislawStempin

**Comment by rishiaurrishabh** [comment]
Yes...that's what I was thinking @StanislawStempin .... we need your help here :)

**Comment by rishiaurrishabh** [comment]
Hi @thpeder ,

Thanks for your help, approach worked for me (y).

Thanks... @all I am closing the issue now.

**Comment by Kowa63** [comment]
> When you publish your app to AppSource and you have the ShowMyCode set to false, then when other 
people tries to download the app package then it will only contain the Symbol information.
That is not solution I'm afraid.
If you try to submit your app to MS for all the preliminary testing and reproduction of key usage scenarios before it appears in AppSource, ShowMyCode=false is currently not accepted.

**Comment by thpeder** [comment]
Hi @Kowa63,
The default value you are getting when not specifying the setting is False, which means that most of the Apps already in AppSource has ShowMyCode set to false.
I'm not sure what problem you are running into, but it should work just fine. Contact them and they will help you out.

**Comment by ryanweigel** [comment]
Hi @Kowa63, who mentioned to you that ShowMyCode=true was a requirement? We recommend it but it is not a requirement for Appsource.

**Comment by Kowa63** [comment]
Hi @ryanweigel ,
my colleague who conferred with you quite freqently during the submission phase ;-). Maybe he got you wrong.
Even if it may be so theoretically, since you deprive yourself of being able to debug even your own app unless you set ShowMyCode=true you will have a hard time trying to maintain support once people are working with it.

**Comment by ryanweigel** [comment]
Yes, that must have been a misunderstanding. We have never required ShowMyCode=true
