### ISSUE TITLE
How to USE dotnet variables on NAV Extensions(for custom dlls)

### ISSUE THREAD

**Issue by cihandurmaz** [Microsoft/AL#3970]
Hello all, is it possible to use dotnet variables on NAV Extensions? Ive read so many articles but didnt find a clue exactly(i may missed the right answer). I know it is possible for D365 Business Central applications but i could not manage to work for NAV 2018 CU9 with the latest AL Version. Im using the VSIX file from CU9 but there is no "al.assemblyprobingpaths" configuration in that version as you know. Is there a way for that or it is not usable for NAV 2018? (Or only Azure functions?) Thanks in advance.  #dotnet #navextensions #nav2018

**Comment by dNsl9r** [comment]
It is explained quite good here, only works OnPrem!
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al

**Comment by cihandurmaz** [comment]
Hello @dNsl9r , yes it is but i can not see "al.assemblyProbingPaths" configuration in my CU9 VSIX file version.

**Comment by dNsl9r** [comment]
I'd guess it doesn't work with NAV2018..

**Comment by cihandurmaz** [comment]
i guess so, i want to be sure if its a way for NAV2018 except Azure Functions.

**Comment by cihandurmaz** [comment]
Thank you for the information @CanuckNav74 . is there any article or document to follow your suggestion?

**Comment by CanuckNav74** [comment]
Sure thing @cihandurmaz

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side

**Comment by cihandurmaz** [comment]
thanks @CanuckNav74 . as i understand, we have to define all custom dlls  on classic dev environment and send parameters from Extension objects to it. There is only way for nav 2018 working with extensions for custom dlls.

**Comment by StanislawStempin** [comment]
That's correct. 
Closing the issue since this forum doesn't cover NAV 2018.
