### ISSUE TITLE
Modify option field from table extension

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#3977]
Hi,

I am trying to modify an Option field using the following line:

`        modify("Contact Type")
        {
            OptionCaptionML = ENU=' ,Companies,People,NV';
        }`

Theres no error in this line but when I try to find the options from field "Contact Type" I can reach the new variable NV.

How I can modify and reach this value from other Codeunit?

Using version: 0.16.26913

Thanks,

**Comment by AskeHolst** [comment]
You can only code against OptionMembers, not OptionCaption. And you cannot modify OptionMembers in table extension.
So if you are trying to add a new option with an extension you are out of luck, you need to find another way.

**Comment by pzentner** [comment]
you also should not be using the "ML" versions of the captions, etc. anymore.

in general, you cannot really modify standard fields in a table extension, you can add triggers to them, but mostly everything else is locked as @AskeHolst said

**Comment by sssolammm** [comment]
Thanks!
