### ISSUE TITLE
RC3 - Search issue with role center pageextension actions

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#3978]
Issue: Search freezes when you use any text contained in the pageextension action caption

1. Install extension with the page extension below
2. Search 'employee'
3. Business Central freezes 

This is not resolved by having xliff files. Same behavior with or without. If you type fast enough and the text in search is different from the caption text, there is no issue (for example if you typed "employees" for this test case). 

- AL Extension Version: 2.0.43900

- Server Version: W1 13.0 (24573)

```
pageextension 50100 TestPageExtension extends "Business Manager Role Center"
{
    actions
    {
        addafter(Reports)
        {
            group(TestGroup)
            {
                Caption = 'Test Group';
                action(TestAction)
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Test Employee';
                    RunObject = Page 5200;
                }
            }
        }
    }
}
```

**Comment by coffeecup007** [comment]
@StanislawStempin  is there more information that can be collected for this bug?

**Comment by DavidBastide** [comment]
Thanks for reporting this issue. The bug occurs when an action matching the search term is found on the current page, and this action has no icon. 
A fix is on the way.
Until then, possible workarounds consists in adding an Image to the action (Image = Action; for example), or searching from a different page.

**Comment by JesperSchulz** [comment]
Closing this issue, as a fix is on its way. We expect to hotfix this issue, as well as the fix will ship with the upcoming November release.
