### ISSUE TITLE
How I can convert text to byteArray?

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#3979]
Hi,

I need to migrate this code from navision 2018 to BC:

`SystemByteArray := SystemUTF8Encoder.GetBytes(s);`

I find the way to enconde s but how I can convert encoding text to byteArray?

Thanks,

**Comment by pzentner** [comment]
it depends on what the end result is for what you want to do. if it's for hashing, there are already hash functions in the encryption management codeunit. if it's for something else, you can always suggest an update to the open library here: https://github.com/Microsoft/cal-open-library

**Comment by sssolammm** [comment]
thanks
