### ISSUE TITLE
How we can add field in general ledger entry

### ISSUE THREAD

**Issue by adityasalwan** [Microsoft/AL#3981]
I have created field in sales order and when i post it i see same field in posted sales invoice with same data i have input in sales order.  i have created same field with same ID and Type in both sales order and posted sales order
but now i want this field to appear in general ledger entries also 
i have done the same step Created same field with same ID and Type . but its not working there
field is coming on the page but the data which i have input is not coming.

if you can help me with that

**Comment by AskeHolst** [comment]
That is a general AL development question. This is not the right place for that kind of question. 
You can get help in the [BC Community](https://community.dynamics.com/business/f/758), on [mibuso](https://forum.mibuso.com/categories/nav-three-tier) or [Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by dNsl9r** [comment]
What you are looking for are events. And you should learn about BC in general I'd guess..
