### ISSUE TITLE
Excel buffer functions

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#3985]
Hi,

Migrating my project I found can't some functions that I used to call with Excel Buffer:

- ADDRESS 
- OverwriteAndOpenExistingExcel
- GiveUserControl

Excel buffer functions gonna  be added in next updates?

Thanks,

**Comment by sssolammm** [comment]
Hi,

function-expose mean it will be added in future versions? @StanislawStempin 

Thanks,

**Comment by StanislawStempin** [comment]
Not necessarily. It will be evaluated by the application team who owns these functions and they will reply back here

**Comment by sssolammm** [comment]
Ok perfect.

Thanks,

**Comment by GiorgosPa** [comment]
I cannot find these functions on Table 370 Excel Buffer, maybe you are reffering to a different object?

**Comment by sssolammm** [comment]
@rdebath  yes I am looking at 2018.

What do you mean when you say W1? In navision the ADDRESS is only for my country navision version? I check it in Excel and it is a generic function.

Thanks,

**Comment by GiorgosPa** [comment]
@sssolammm I was lloking on the last release and I couldn't find the functions.  We've decided not to go through with your suggestion.
