### ISSUE TITLE
DotNet Wrapper needed for XMLHandling

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [Microsoft/AL#3988]
Hello,
we need DotNet wrapper codeunits for XML handling espacially for System.XML.XmlDocument, System.Xml.XmlNode and System.Xml.XmlProcessingInstructions.

We need to create some special xmlfiles which are not possible via xmlport

Best Regards
Patrick

**Comment by OleTeichmann** [comment]
Is it possible for you to use the XML API for Business Central to solve your problem? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview

**Comment by StanislawStempin** [comment]
Please try to use the new AL types as much as possible for this task and let us know if you're missing anything in them.
