### ISSUE TITLE
Error 422: Sequence contains no matching element

### ISSUE THREAD

**Issue by GOB-Andrea** [Microsoft/AL#399]
Hello and help :)
I wrote a small app with a 2-field-table extension, 2-field-page-extension and a small codeunit with a subscriber. There seems to be no problem within the workspace during the debugging. But at the end, when the app should be published, the following error occurs:
"Error: The request failed with code 422, reason: Sequence contains no matching element"
I thought there could be something wrong with the launch.json or app.json files, but I cannot see a difference between the files in this project and another project that can be compiled and published without an error.
Anybody an idea? 
Thanks in advance!!

**Comment by GOB-Andrea** [comment]
The error is gone... what did I do? I saved the table-extension-file to another folder and deleted it from the project, added a new table-extension to the project and inserted the same code manually again. Afterwards the project could be published without an error!
Out of curiosity I deleted the new table-extension file and copied the old one back to the project folder. And it worked with the old one too: no error.
I don't know the reason, but I am happy it worked.

**Comment by dennisfrostlander** [comment]
This is a bug on the server. Could you please search in the *Event viewer* for the phrase `Sequence contains no matching element` and send us the full error text?
- Start menu -> Event viewer
- Expand Widows Logs -> Application
- Ctrl+F, paste `Sequence contains no matching element`
- Enter

**Comment by GOB-Andrea** [comment]
Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 670974d2-5a29-4d4a-846f-f7b2eba5a816
ServerActivityId: da416146-3e3c-4b3c-9c3c-ebee27a348f8
EventTime: 07/21/2017 08:14:05
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/Navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nSequence contains no matching element\r\n"}</pi></ii>
ProcessId: 108
Tag: 00000LY
ThreadId: 25
CounterInformation:

**Comment by dennisfrostlander** [comment]
Could I bother you for a few more errors around this one? There should be more descriptive errors within 20-30 seconds of the one you have found. Thanks a lot!

**Comment by GOB-Andrea** [comment]
I have an error 6 minutes earlier and a warning 37 minutes later. I think the earlier error is just the same, only triggered again by the debugging.
Error:

Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 670974d2-5a29-4d4a-846f-f7b2eba5a816
ServerActivityId: da416146-3e3c-4b3c-9c3c-ebee27a348f8
EventTime: 07/21/2017 08:08:14
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/Navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nSequence contains no matching element\r\n"}</pi></ii>
ProcessId: 108
Tag: 00000LY
ThreadId: 36
CounterInformation: 

After the first error-entry in the event viewer there are a lot more of this errors, just seconds after. But I think this entries exists because of the same reason: I debugged and tried to publish again.
Here are some examples:

Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 670974d2-5a29-4d4a-846f-f7b2eba5a816
ServerActivityId: da416146-3e3c-4b3c-9c3c-ebee27a348f8
EventTime: 07/21/2017 07:51:20
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/Navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nSequence contains no matching element\r\n"}</pi></ii>
ProcessId: 108
Tag: 00000LY
ThreadId: 14
CounterInformation: 

Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 670974d2-5a29-4d4a-846f-f7b2eba5a816
ServerActivityId: da416146-3e3c-4b3c-9c3c-ebee27a348f8
EventTime: 07/21/2017 07:51:29
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/Navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nSequence contains no matching element\r\n"}</pi></ii>
ProcessId: 108
Tag: 00000LY
ThreadId: 14
CounterInformation: 

Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 670974d2-5a29-4d4a-846f-f7b2eba5a816
ServerActivityId: da416146-3e3c-4b3c-9c3c-ebee27a348f8
EventTime: 07/21/2017 07:53:31
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/Navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nSequence contains no matching element\r\n"}</pi></ii>
ProcessId: 108
Tag: 00000LY
ThreadId: 25
CounterInformation: 

The warning 37 minutes after the last error isn't probably interesting, but I send it to you anyway:

Server instance: Navision_main
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 07/21/2017 08:51:58
Message <ii>Threshold Trace Tag. Execution Time = 7613 milliseconds
    Long Running SQL statement Task ID:9, ConnectionId=13
    Commit</ii>
ProcessId: 108
Tag: 000007S
ThreadId: 9
CounterInformation:

**Comment by dennisfrostlander** [comment]
Ok, thank you for the information. We will try to explore what could have gone wrong in this case.

**Comment by StanislawStempin** [comment]
We cannot reproduce the issue. We have made a number of changes that fixed this particular error message. 
Please reopen or open a new issue if you ever run into it again.
