### ISSUE TITLE
Override RunObject property in an Action

### ISSUE THREAD

**Issue by j-wilder** [Microsoft/AL#3990]
I have an Action that has the RunObject and RunPageLink property set.  I need to override this with code to open a different page (with some logic).  When I extend the action with code it now opens the runobject page and the page with my code.  How do I override the RunObject property to be blank (Layout\Modify doesn't have access to these properties)?

Or do I have to hide the Action and create my own?

**Comment by OleTeichmann** [comment]
I think at them moment it is not possible to override these properties. You will need to create your own action as you said.

**Comment by j-wilder** [comment]
Thanks!
