### ISSUE TITLE
AL on-prem: debugging an extension via windows client? not the web client?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#3994]
Is there anything on the roadmap to facilitate AL debugging by spinning up and attaching to a windows client process?

Some of my customers will have no interest in using the web client for BC365 on-prem. Many will prefer to use the on-prem windows client. Debugging via the web client wouldn't be an apples-to-apples testing & troubleshooting process (there are enough differences between the two to warrant windows client AL debugging)

**Comment by StanislawStempin** [comment]
We have no plans to add AL debugging for windows client sessions, especially since windows client will be retired in 12-24 months.

You can use the old debugger to debug windows client sessions, even for AL code. If you search through this GitHub forum you will find instructions how to do it.

**Comment by CanuckNav74** [comment]
Thank you for the feedback @StanislawStempin - I'll keep that in mind (i.e. use the windows client debugger as-needed)

I was unaware that windows client (even on-prem?) is going to be retired in the next 1-2 years. Hmmm...

Once the windows client is retired, I fear it's retirement will introduce another problem. According to this issue https://github.com/Microsoft/AL/issues/604 , SOAP debugging is currently not possible in the web client and is on the development backlog.  I hope Microsoft has a solution for AL SOAP debugging before the windows client is retired.

**Comment by StanislawStempin** [comment]
That issue will be addressed before the win client debugger is retired.
