### ISSUE TITLE
Multilanguage in reports created as extension

### ISSUE THREAD

**Issue by kennethd1** [Microsoft/AL#3998]
Hi 

I have a problem showing multiple language in my reports.
I have created an extension (v2), added the feature: TranslationFile, got the .xlf file
and runned it through the MS Lifecycle service, to get it translated to my language (nb-NO).
Then I copied this file to both to the root folder of my project and to the Translations folder.
When I'm building the project, I then have two .xlf files. One original with only the source
language (en-US) and my new language file, that have both source and target for each label.
The translation seem to be correct, but when I'm running my report, the target
value is not used as labels in the report. It is still using the source language.
What am I missing? or is this a bug?

The Globallanguage is set to 1044 (nb-NO) and some of the menus and page actions is
showing in the wanted language.
I'm running the report like this:
    actions
    {
        area(processing)
        {
            action(RunCustomReport)
            {
                trigger OnAction()
                begin
                    Report.Run(50002,true,false);
                end;
            }
        }
    }

**Comment by StanislawStempin** [comment]
Do any other translations from that xliff file work correctly and only the report is incorrect?
