### ISSUE TITLE
Preview page

### ISSUE THREAD

**Issue by Morten-KS** [microsoft/AL#400]
It is possible to do a preview on a page or page extension developed in VS code?

Thanks in advance.

**Comment by dennisfrostlander** [comment]
Do you mean a preview inside VS code? Then no, but this is on our backlog.

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.

**Comment by nndobrev** [comment]
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-explorer
