### ISSUE TITLE
How to access default configuration

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#4003]
This is why I found #3884 and now I need to find the answer to the original problem.
I am using the Business Central October 2018 release on prem.  I am using the Project Manager profile as my default profile.

The Job Card has been configured out-of-the-box to move some actions around and add them to the Home ribbon.  I want to hide one of these promoted/moved actions in my Page Extension but I can't seem to find it.  I can hide the action under the Navigate menu (where it originated from) but not from where it was moved to on the home ribbon.  

This shows the Job Card has some OotB configuration:
![image](https://user-images.githubusercontent.com/4333956/46732307-09af4c00-cc85-11e8-8fa0-c7761831f282.png)

On the Job Card, on the Home ribbon, in the Job section is Job Planning Lines
![image](https://user-images.githubusercontent.com/4333956/46730902-32cddd80-cc81-11e8-9add-90535c4c1327.png) and here under the Navigate option
![image](https://user-images.githubusercontent.com/4333956/46731122-cdc6b780-cc81-11e8-9dbf-651d96d73b24.png)
I want to hide this.  However, looking at the page's (88) Actions in the Development Environment this action is Promoted to the Process category.
![image](https://user-images.githubusercontent.com/4333956/46731019-8809ef00-cc81-11e8-9c2f-7358efa6e99b.png)
![image](https://user-images.githubusercontent.com/4333956/46731700-4aa66100-cc83-11e8-9b21-3abb3b64d13b.png)

So I create this PageExtension
![image](https://user-images.githubusercontent.com/4333956/46731258-21390580-cc82-11e8-93e4-91ace23956df.png)
And you can see the Navigate, Job, Job Planning Lines is gone.
![image](https://user-images.githubusercontent.com/4333956/46731790-89d4b200-cc83-11e8-8dfe-57165308eedd.png)
But it remains on the home ribbon
![image](https://user-images.githubusercontent.com/4333956/46731845-b7b9f680-cc83-11e8-9e69-e3bed12fa109.png)

How do I hide this promoted and moved action that is the result of configuration done in the base BC application?

**Comment by StanislawStempin** [comment]
You would need to remove the "legacy configuration" for this to work with AL. Otherwise the old configuration  creates a copy of the action that cannot be accessed from AL.

**Comment by GreatScott000** [comment]
So is the way to do this to delete the profile personalization?

**Comment by StanislawStempin** [comment]
Yes, delete the profile personalization or move the profile personalization to the new Profile object in AL:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object
