### ISSUE TITLE
Modifying the existing check report gives 'Index out of bounds' error

### ISSUE THREAD

**Issue by olisterr** [Microsoft/AL#4004]
Hi All,

There a client requirement to add new feilds in the existing Check Report(10401) along with MICR font. Thus I tried the follwoing approaches.
1. Modified the existing Check Report(10401) and added the feilds, converted to AL using Text-To-Al and compiled & publish it to Business Central
When executing the report, the Business Central gives an error 'Index out of bounds for PrnChkCheckAmountToText'.
2. Converted the Standard Report(non-modified) to AL using Text-To-Al, compiled and published on Business Central resulting in the same error.
3. Created a new report with the required feilds, created new RDLC layout and set the font of the Textbox to MICR. Everything works fine, but the MICR font is not printed when printing the report to PDF. It tried printing the report in Word which gives correct MICR font but the report layout changes.
4. Created new report with required feilds, created new Word Layout but the data appears to be blank.

Kindly advise!.

**Comment by olisterrcf** [comment]
Hi StanislawStempin,

Can you please take this issue on highest priority as we are stuck with the Go-Live!

Thanks!

**Comment by StanislawStempin** [comment]
For Go-Live issues you need to work with the Support team. This is a feedback forum for the latest preview versions of Developer Tools. We provide no SLAs for resolution here.

**Comment by olisterr** [comment]
Hi Stanislaw,

I've already raised the support ticket with the Microsoft Support Team, thus I got a reply stating that the issue has been escalated to the development team.
Kindly advise.

Thanks!

**Comment by StanislawStempin** [comment]
Ok, in that case let's track the resolution through the Support channels. I will close it here.

**Comment by AbsolutelyFreeWeb** [comment]
Its resolution is interesting for others. I need status on this please.
