### ISSUE TITLE
Publishing App Throws Error Sometimes.

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#4008]
Hi,
Sometimes during publishing APP from VS throws following error but it publish the app
**Cannot read property 'sendRequest' of null**

It happens only sometimes but not stopping publishing the app

Regards
Amol

**Comment by epernst** [comment]
I'm seeing the same message sometimes, but didn't really record a pattern yet.

**Comment by AmolSalvi** [comment]
To be more specific during publish process if we close down/log off the web client which is already open then throw this error.
May be it required to be log off /close all client during publish process.

**Comment by StanislawStempin** [comment]
It should not be required to log off or close any existing browser windows. Which version are you running on?

**Comment by AmolSalvi** [comment]
Vs Version 1.28.0

**Comment by epernst** [comment]
I am on same VSCode version, BC 13.0.24838. It happens to me whenever I am running the debugger, and while execution is with focus on a breakpoint the debugger, then I cancel the debugging session manually from VSCode.

**Comment by JohanStenberg100** [comment]
Thanks @AmolSalvi, I will keep an eye out for this error. 

However, without a consistent repro I can't help you in fixing it. I will close this issue now, but please re-open this issue or file a new issue if you find consistent steps for reproducing the issue.
