### ISSUE TITLE
Function Expose Request

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/AL#4011]
Hi Guys,
We are making our steps toward extension development. While converting our solution to AL extensions we made a list of LS functions that we would like to be exposed as external functions. Here's the list:

---Format---
Object ID--Object Name
Function Name
---Format-----

Report 5851 Suggest Item Standard Cost
SetCopyToWksh
Initialize

Report 493 Carry Out Action Msg. - Req.
SetReqWkshLine
InitializeRequest

Report 698 Get Sales Orders
SetReqWkshLine
InitializeRequest

AL Extension Version: 2.0.43900 (RC3)
Server Version: NL 13.0.24535

thanks!

srinivas

**Comment by darjoo** [comment]
Hi @srinivasGangadhara, thanks for weighing in. We're evaluating your request and will return with a decision ASAP.

**Comment by darjoo** [comment]
We've decided to go ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
