### ISSUE TITLE
Overflow warning when using PadStr

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#4013]
If you write this simple code:

```
local procedure Test()
var
     Tmp: Text[10];
begin
     Tmp := PadStr('', 8, ' ');
end;
```

You get a:

`"Possible overflow assigning 'Text' to 'Text[10]'.`

As PadStr actually truncates the string, if it is longer than the specified number, this shouldn't raise the warning.

Tested with AL Extension 2.0.48254.

P.S. While looking whether someone had already reported this, I found tickets #1462 and #583, also related to overflow warnings. Shouldn't someone close those tickets? (the bugs reported in them have been already fixed).

**Comment by AndreyKorepanov** [comment]
@salgiza Thank you for reporting the bug. The fix will be shipped in the future update.
