### ISSUE TITLE
How to debug Business Central Sandbox?

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#4014]
Hi,

i'm currently want to debug my extension via Business Central Sandbox.
It doesn't work.
The debugger doesn't stop on my set breakpoints.
I'm working on the current release.
I'm publishing my extension via F5.
Is there anything more i need to do to get this running?

Best regards,

hendrik

**Comment by Kowa63** [comment]
Have you set showmycode=true in the app.json? Otherwise debugging is not possible.

**Comment by StanislawStempin** [comment]
Which version of AL Language are you using?
Which runtime have you set in app.json?

**Comment by hendrik244** [comment]
> Have you set showmycode=true in the app.json? Otherwise debugging is not possible.

I did that.

**Comment by hendrik244** [comment]
> Which version of AL Language are you using?
> Which runtime have you set in app.json?

I'm using AL 2.0.56865.
My runtime is set to 2.1.

**Comment by hendrik244** [comment]
Currently I also have the problem that i cannot publish to my BC Sandbox anymore.
This message occurs:
![2018-11-27_1758](https://user-images.githubusercontent.com/33331414/49097891-0d675400-f26e-11e8-9709-efa6fb02ac04.png)

Debugging Console is empty.
