### ISSUE TITLE
Set table functions below to "EXTERNAL" for MSDYN365BC Online, they are useful for reports

### ISSUE THREAD

**Issue by rstefanetti** [Microsoft/AL#4015]
Hi,
the table functions listed below are "INTERNAL" and not work in MSDYN365BC Online; would it be possible to set them to "EXTERNAL"? They are useful for reports.

Table 36.FindVATExemption
Table 291.GetTDDAdr
Table 23.GetTDDAdr
Table 5050. GetTDDAdr
Table 79. GetTDDAdr
Table 291. GetTDDAdr

Thanks for support
Roberto Stefanetti [MVP]

**Comment by darjoo** [comment]
We've decided to go ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
