### ISSUE TITLE
not possible to connect to the NAV SOAP web service exposed on the same computer

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#4018]
In the extension it’s not possible to connect to the NAV SOAP web service exposed on the same computer because HttpClient class has not neither UseDefaultCredentials property, nor Credentials property (and NetworkCredential class as well).
The Basic authorization which can be entered to HttpHeader doesn’t work for NAV web services, and I didn’t find any way to pass authorization without using UseDefaultCredentials property or NetworkCredential class in external C# project.

**Comment by JulienDecottignies** [comment]
I've already pass authorization to an HttpClient type by

`Client.DefaultRequestHeaders().Add('Authorization', 'Basic ' + Credentials);`

Credentials (Text) that I set with:
`TypeHelper: Codeunit "Type Helper"`
`Credentials := TypeHelper.ConvertValueToBase64('UserName' + ':' + 'Password');`

Is it what you want to do ?

**Comment by bennyvanlyssebettens** [comment]
Same as Issue #550 and #4085 (My own)

**Comment by StanislawStempin** [comment]
Correct, closing as duplicate
