### ISSUE TITLE
Event exists in W1, but not in DE nor AT.

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#4022]
Talking about event "OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine" in TAB111.

The problem is in NAV2018 CU8

in BC, it seems to exist - so I don't know if this can be backported to all localizations of NAV2018, so they are in line with its W1.

**Comment by AlexanderYakunin** [comment]
No, we are not backporting events to NAV 2018.

**Comment by waldo1001** [comment]
This is not backporting.  You already have the event in W1 in NAV2018.  Just not in the localizations.

**Comment by StanislawStempin** [comment]
This has been implemented and will be available in master images soon.
