### ISSUE TITLE
Unable to extend User table.

### ISSUE THREAD

**Issue by JohnBlackmar** [Microsoft/AL#4025]
- AL Extension Version: 2.0.48254

- Server Version: US Dynamics NAV 13.0 (24630)

I try to add new field to User table (2000000120) but when add new field to "User Card" page I received an error that the supplied field number cannot be found in the 'User' table.

**Comment by StanislawStempin** [comment]
This is not supported. We are in the process of adding compiler checks to prevent it at compilation stage.

**Comment by JalmarazMartn** [comment]
Don´t know if supported to modify "User" table, but I know it´s no good. Instead modify "Company" or "User" tables, long time ago we would rather modify "Company information" and "User Setup" tables instead.

**Comment by AndreyKorepanov** [comment]
@JohnBlackmar Thank you for reporting the bug. The fix will be shipped in future update.

**Comment by StanislawStempin** [comment]
In this case the fix is that the compiler will prevent extending system tables. So the scenario is still not supported.
