### ISSUE TITLE
UPLOADINTOSTREAM encoding

### ISSUE THREAD

**Issue by mortenseifert** [Microsoft/AL#4029]
When using the UPLOADINTOSTREAM I am missing the options of defining the encoding of the file, the user selects. Or perhaps I am doing something wrong?

Running BC Sandbox 
AL Lanaguage 0.16.26913

I am defining the InStream as UTF8 encoding

``TempBlob.Blob.CreateInStream(FileInStream, TextEncoding::UTF8);
UploadIntoStream(TxtImportTitle,ImportFilepath,TxtImportFilter,Filename,FileInStream);``

However, when I import the text into the database, the encoding gets messed up.

When I open the source file as UTF-8 it looks OK. When I open the file as Windows-1252 i see the same text as gets imported into BC.

Source file viewed as Windows 1252
![image](https://user-images.githubusercontent.com/26865832/46860253-55dac780-ce10-11e8-9b8d-24b8bb764635.png)

Imported content in BC
![image](https://user-images.githubusercontent.com/26865832/46860322-7b67d100-ce10-11e8-826b-f06a4b7e3ef6.png)

**Comment by kalberes** [comment]
Hi, 

Can you create a small repro example?

**Comment by mortenseifert** [comment]
I found the problem in my code and want to post this should others run into the same issue.

In my original code I had
```
TempBlob.Init();
TempBlob.Blob.CreateInStream(FileInStream, TextEncoding::UTF8);
ResponseMsg.Content.ReadAs(FileInStream);
FileInsStream.ReadText(Line) 
```

Now I first copy the Content to Text and then write it to BLOB and read it again.
```
ResponseMsg.Content.ReadAs(Content);
TempBlob.Init();
TempBlob.Blob.CreateOutStream(FileOutStream, TextEncoding::UTF8);
FileOutStream.WriteText(Content);
TempBlob.Blob.CreateInStream(FileInStream, TextEncoding::UTF8);
FileInsStream.ReadText(Line) 

```

I suspect that the original code was doing some double encoding or something.
It would be nice if the HttpContent did offer a CreateInStream() to read the content from without having to copy the content back and forth (though it is still in memory)
