### ISSUE TITLE
OpenFileDialog in FileManagement Codeunit

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#403]
Related to #220.
We have used this to just get the name of a file to reference we don't actually want to upload the file.  The OpenFileDialog returns the filename selected, which is all we need.  Do you have a alternative suggestions?  We can't use the File table either.

The scenario we do this is we have a setup table to point to a document template that a user later adds links to a page and fills out.

The dialog allows for a nice user interface rather than just an empty textbox and the user has to enter the correct path and name to the file.

**Comment by StanislawStempin** [comment]
The OpenFileDialog procedure has been made available for Extension development. However, note that the functionality will not work in the web client since it cannot run client side .NET
