### ISSUE TITLE
Debugger doesn't work - BreakOnError / breakOnRecordWrite

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#4038]
I don't get the "BreakOnRecordWrite" and "breakOnError" to work at all.  it NEVER breaks on both.. .  Strange, because I have been showing this hundreds of times.  And now it doesn't work on all my machines (so not only on 1 environment).

It might be a setting (while setting up docker?) I'm not aware of .. if so, sorry.

AL  Language Version: 2.0.52543
Business Central: W1 14.0 (25097)

my Launch.json:
![image](https://user-images.githubusercontent.com/12088142/46867772-71e96380-ce26-11e8-897d-56ac5f385ec9.png)

My intentional error:
![image](https://user-images.githubusercontent.com/12088142/46867795-7d3c8f00-ce26-11e8-9708-03ef5149a76b.png)

But no break, not even on record writes, not even on other PCs.

**Comment by StanislawStempin** [comment]
Do normal breakpoints work?

**Comment by waldo1001** [comment]
Yes, they do.  Same environment with normal breakpoint:
![image](https://user-images.githubusercontent.com/12088142/46868423-95ada900-ce28-11e8-8f7e-2d9a6c45e2f1.png)

**Comment by lucahochreutener** [comment]
I have the exactly the same problem, when will this be fixed?

**Comment by sbuescher** [comment]
I have the same issue. But latest build of BC onprem, pulled today.

**Comment by kalberes** [comment]
This is a bug that appeared with the latest Visual Studio 1.28.  Things have changed in the debug adapter protocol that we have not adapted too.
