### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post: on before FinalizePosting  

### ISSUE THREAD

**Issue by iuridavid** [Microsoft/AL#4039]
We need an event on before FinalizePosting on Codeunit 80 Sales-Post

OnBeforeFinalizePosting(SalesHeader,SalesShptHeader,SalesInvHeader,SalesCrMemoHeader,ReturnRcptHeader,GenJnlPostLine);

We need to get some data before finalize posting in our solution.
Please check example of what we need to change bellow:

![codeunit 80 event request](https://user-images.githubusercontent.com/32514408/46869799-d0154700-ce24-11e8-9a59-77cae826b4a6.png)

Thank you.
Iúri

**Comment by StanislawStempin** [comment]
This repo is no longer dedicated to handling application requests and enhancements.
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
