### ISSUE TITLE
Bug: Reference count no longer working on methods

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#4041]
**Describe the bug**
- The reference counter no longer seems to be working on methods. 
- It continues to work correctly on global variables though.
- It appears that alc.exe tries to count references for the reserved `var` in the globals.

**Screenshots**
![image](https://user-images.githubusercontent.com/8897936/46873203-48383880-ce36-11e8-922d-6a501db4313c.png)

**Versions:**
 - AL Language: 2.0.52543
 - Business Central: IT Dynamics NAV 13.0 (24630)

**Comment by AndreyKorepanov** [comment]
@hemisphera Thank you for reporting the bug, we will ship the fix in the future updates.
