### ISSUE TITLE
Read and Write Data to Web Service using SOAP URL

### ISSUE THREAD

**Issue by aguschnd325** [Microsoft/AL#4042]
Hello, I am a newbie in AL Language Extension.
Right now I am learning how to read and write to/from Web Services.
I am using Dynamics NAV 2018 to develop extension.

I am able to read ODataV4 data from ODatav4 URL in dynamics nav client.
Is there a way to post a new data for example new customer to the ODatav4 web service?
How to write my new customer data to the odatav4 URL ?
and Is it possible to read and write from SOAP URL Web Service ? I thought that .NET is needed when we are working with SOAP.
I open the SOAP URL in browser and only WSDL is shown without record like JSON data from ODatav4.

I am sorry to ask this but I hope anyone can help me to solve this problem in AL.
Thank you so much

**Comment by StanislawStempin** [comment]
We have made a recent change to this repository. We no longer handle general questions and this forum is now only dedicated to bug reports and feature suggestions for the AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
