### ISSUE TITLE
Event Request  Table 36 and Codeunit 80 for our ISV solution

### ISSUE THREAD

**Issue by iuridavid** [Microsoft/AL#4044]
We need one event on Table 36 and one event on Codeunit 80 for our ISV solution (in NAV 2018 that we will later move to BC)

Table 36: 
[External] InitInsert()
We need an event OnBeforeInitRecord(Rec,xRec);
Just before InitRecord;
Print Below
![image](https://user-images.githubusercontent.com/32514408/46945512-deee3a80-d06c-11e8-9c90-8463eb8c4a4b.png)

Codeunit 80:
We need an event on before FinalizePosting on Codeunit 80 Sales-Post

OnBeforeFinalizePosting(SalesHeader,SalesShptHeader,SalesInvHeader,SalesCrMemoHeader,ReturnRcptHeader,GenJnlPostLine);

We need to get some data before finalize posting in our solution.
Please check example of what we need to change bellow:

![codeunit 80 event request](https://user-images.githubusercontent.com/32514408/46945623-2a084d80-d06d-11e8-80c5-b98237539e83.png)

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
