### ISSUE TITLE
Reading xml files

### ISSUE THREAD

**Issue by NarendraReddyMotla** [Microsoft/AL#4045]
Hi 

I started developing extensions for Microsoft Dynamics NAV in Visual Studio Code.
I am trying to read data from xml files.

I am trying out the XMLDocument Class and I can successfully load the file. But cannot able to navigate to the specific nodes.
For example if I have the following xml file:

`<?xml version="1.0" encoding="UTF-8" ?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header>Header</soapenv:Header><soapenv:Body>Body Info</soapenv:Body></soapenv:Envelope>`

How can get to the node of <soapenv:Body>?

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by atoader** [comment]
Could you please provide a full snippet to repro this?

**Comment by NarendraReddyMotla** [comment]
I am using the following to read the xml document, which is provided as web response.
XML document is attached here.

```
XmlDoc: XMLDocument; // loaded from web response.
dnNsmgr : XmlNamespaceManager;
XmlResponse : XmlNode;

dnNsmgr.AddNamespace('soapenv', 'http://schemas.xmlsoap.org/soap/envelope/');
dnNsmgr.AddNamespace('nrg', "http://www.dnbnordic.com/nrg");
If not XmlDoc.SelectSingleNode('//Envelope/Body/nRGCompanyReportStandardResponse', dnNsmgr, XmlResponse) then
  ERROR('Response from service not found!');
```

[Receive.zip](https://github.com/Microsoft/AL/files/2481684/Receive.zip)

**Comment by ftornero9** [comment]
I had the same issues and find a workaround using the "XML Buffer" table

XMLBuffer: Record "XML Buffer" temporary;
tmpBlob.Blob.CreateOutStream(OutStr);
xmlDoc.WriteTo(OutStr);
XMLBuffer.DeleteAll();
XMLBuffer.Load(OutStr);
XMLBuffer.SETRANGE(XMLBuffer.Type, XMLBuffer.Type::Element);
 If XMLBuffer.FindSet() then repeat
........

Where xmlDoc is the XML loaded from the web response.

Regards.

**Comment by ftornero9** [comment]
Looking into an example from @waldo1001 in "MostUselessAppEver", he add a previous line of code before assign the NSmanager, in your example:


dnNsmgr.NameTable(XmlDoc.NameTable());

dnNsmgr.AddNamespace('soapenv', 'http://schemas.xmlsoap.org/soap/envelope/');
dnNsmgr.AddNamespace('nrg', "http://www.dnbnordic.com/nrg");

XmlDoc.GetRoot(RootElement);

if not RootElement.SelectSingleNode(
''//soapenv.Envelope/soapenv.Body/nrg:nRGCompanyReportStandardResponse', dnNsmgr, XmlResponse) then ...

And you need to put the NS in front of the tags to find the Node that you want.

**Comment by NarendraReddyMotla** [comment]
Hei Fernando,
Thanks for helping to solve this.
I tried the following 

```
XmlDocText := '<?xml version="1.0" encoding="UTF-8" ?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header>Header</soapenv:Header><soapenv:Body><nRGCompanyReportStandardResponse xmlns="http://www.dnbnordic.com/brg/NRGCompanyReportStandard/response">Hei</nRGCompanyReportStandardResponse></soapenv:Body></soapenv:Envelope>';
XmlDocument.ReadFrom(XmlDocText, xmldoc);
dnNsmgr.NameTable(xmldoc.NameTable);
dnNsmgr.AddNamespace('soapenv', 'http://schemas.xmlsoap.org/soap/envelope/');
dnNsmgr.AddNamespace('nrg', 'http://www.dnbnordic.com/nrg');
xmldoc.GetRoot(RootElement);
 XMlPathText := '//soapenv:Envelope/soapenv:Body/nRGCompanyReportStandardResponse';
if not RootElement.SelectSingleNode(XMlPathText, dnNsmgr, XmlResponse) then
  Error('Node didnot found')
else begin
   message(XmlResponse.AsXmlElement.InnerText);
   message(XmlResponse.AsXmlElement.InnerXml);
end;
```

Node Cannnot be found with the above xpath. 
But if xpath is `//soapenv:Envelope/soapenv:Body` then it works.

**Comment by NarendraReddyMotla** [comment]
Hei @atoader  It is not working in all the cases. Please see my comments as the xpath is combined with multiple namespaces and no namespaces. (Ex: '//soapenv:Envelope/soapenv:Body/nRGCompanyReportStandardResponse')

**Comment by ftornero9** [comment]
Hello @NarendraReddyMotla 

To ignore the NS you can use this

        if not xmlDoc.SelectSingleNode('/*[local-name()="Envelope"]/*[local-name()="Body"]/*[local-name()="nRGCompanyReportStandardResponse"]', XmlResponse) then
            Error('Node didn''t found 1')
        else begin
            message(XmlResponse.AsXmlElement.InnerText);
            message(XmlResponse.AsXmlElement.InnerXml);
        end;

**Comment by NarendraReddyMotla** [comment]
Thanks Fernando. It works. You made my day.
It is working even as bellow

``XmlDoc.SelectSingleNode('//soapenv:Envelope/soapenv:Body/*[local-name()="nRGCompanyReportStandardResponse"]', dnNsmgr, XmlResponse)``

But hope the calling of select nodes needs to improve. If the name space is not exists for one of the nodes then also it should work. instead of using it with local-name.

**Comment by TabrezAjaz** [comment]
> Hei Fernando,
> Thanks for helping to solve this.
> I tried the following
> 
> ```
> XmlDocText := '<?xml version="1.0" encoding="UTF-8" ?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header>Header</soapenv:Header><soapenv:Body><nRGCompanyReportStandardResponse xmlns="http://www.dnbnordic.com/brg/NRGCompanyReportStandard/response">Hei</nRGCompanyReportStandardResponse></soapenv:Body></soapenv:Envelope>';
> XmlDocument.ReadFrom(XmlDocText, xmldoc);
> dnNsmgr.NameTable(xmldoc.NameTable);
> dnNsmgr.AddNamespace('soapenv', 'http://schemas.xmlsoap.org/soap/envelope/');
> dnNsmgr.AddNamespace('nrg', 'http://www.dnbnordic.com/nrg');
> xmldoc.GetRoot(RootElement);
>  XMlPathText := '//soapenv:Envelope/soapenv:Body/nRGCompanyReportStandardResponse';
> if not RootElement.SelectSingleNode(XMlPathText, dnNsmgr, XmlResponse) then
>   Error('Node didnot found')
> else begin
>    message(XmlResponse.AsXmlElement.InnerText);
>    message(XmlResponse.AsXmlElement.InnerXml);
> end;
> ```
> Node Cannnot be found with the above xpath.
> But if xpath is `//soapenv:Envelope/soapenv:Body` then it works.

**Can you please provide the whole method code?**

I have following snippet and unable to read node data, please tell me how to loop and get text of each node one by one and store text data into table:
<Access_Token>
    <Instance_Url>https://www.concursolutions.com/</Instance_Url>
    <Token>0_YsH/AzvFGCKyy6fx0b/sY6avs=</Token>
    <Expiration_date>10/28/2019 11:50:14 PM</Expiration_date>
    <Refresh_Token>0_i1G4yHMN316Mtqsac4GjD5R5UoP5f</Refresh_Token>
</Access_Token>

Thanks in advance!

**Comment by TabrezAjaz** [comment]
> Hello @NarendraReddyMotla
> 
> To ignore the NS you can use this
> 
> ```
>     if not xmlDoc.SelectSingleNode('/*[local-name()="Envelope"]/*[local-name()="Body"]/*[local-name()="nRGCompanyReportStandardResponse"]', XmlResponse) then
>         Error('Node didn''t found 1')
>     else begin
>         message(XmlResponse.AsXmlElement.InnerText);
>         message(XmlResponse.AsXmlElement.InnerXml);
>     end;
> ```

**Can you please provide the whole method code?**

I have following snippet and unable to read node data, please tell me how to loop and get text of each node one by one and store text data into table:
<Access_Token>
    <Instance_Url>https://www.concursolutions.com/</Instance_Url>
    <Token>0_YsH/AzvFGCKyy6fx0b/sY6avs=</Token>
    <Expiration_date>10/28/2019 11:50:14 PM</Expiration_date>
    <Refresh_Token>0_i1G4yHMN316Mtqsac4GjD5R5UoP5f</Refresh_Token>
</Access_Token>

Thanks in advance!
