### ISSUE TITLE
Connect Business Central On Premises from AL

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/AL#4050]
Hi All,
When I am trying to connect Business Central On Premises from AL getting below error message ,
Note:
But I can able connect to NAV 2018 from AL and can do customization also with out any issue
Please help 
![error](https://user-images.githubusercontent.com/44170162/46959164-f6114480-d0cd-11e8-8fd9-6accb6f37219.jpg)

**Comment by StanislawStempin** [comment]
Which version of AL Language are you using?

**Comment by CanuckNav74** [comment]
@TharunMuthu sounds like you have the NAV2018 AL Language extension installed for VS Code. Not the Business Central one. Did you try uninstalling it and installing the .vsix that ships with the BC on-prem install media?

**Comment by TharunMuthu** [comment]
>  Language are you using?
Is this correct Version ? 
![image](https://user-images.githubusercontent.com/44170162/46963004-2b6e6000-d0d7-11e8-94c2-5a556c9fa035.png)

**Comment by StanislawStempin** [comment]
No, as the issue template states:

**Comment by TharunMuthu** [comment]
>           No, as the issue template states:
> Go to Visual Studio Code → Extensions panel → AL Language

Hi StanislawStepin,
Thanks for your reply now I have updated my AL code  .
Now I am getting below error message ,

![image](https://user-images.githubusercontent.com/44170162/46993239-bc2d5600-d140-11e8-949f-bf0a42832ac9.png)
But I have already set it in NAV Admin as below
![image](https://user-images.githubusercontent.com/44170162/46993257-d5360700-d140-11e8-881b-08846d257a99.png)

and I made NetFx40_LegacySecurityPolicy enabled="false also from below folder
C:\Program Files\Microsoft Dynamics 365 Business Central\130\Service

Is any thing missing Can you please guide me !

**Comment by TharunMuthu** [comment]
Hi All issue has been closed I just close and reopened .I Can able to published to the server.
Thanks for your support
