### ISSUE TITLE
Change to WhseLinesExist in Whse. Validate Source Line

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#4051]
BC OnPremise October 2018 Release

Not sure if this should be here or in the new [ALAppExtensions](https://github.com/Microsoft/ALAppExtensions).

In our extension we have added a new document called Manifest (similar Sales Quote/Order/Invoice/Cr. Memo), if the `WhseLinesExist` function in CU5777 Whse. Validate Source Line, had a VAR parameter for the `TableCaptionValue` variable then we could easily duplicate the `SalesLineVerifyChange` and `SaleLineDelete` functions without having to modify the CU.

**Comment by StanislawStempin** [comment]
It should go to ALAppExtensions:)
