### ISSUE TITLE
While creating NAV Container for D365 BC We see this type of error

### ISSUE THREAD

**Issue by Gokulnath024** [Microsoft/AL#4052]
DockerDo : docker.exe: Error response from daemon: container 
b26e4accdea2623fb8dd237aaff1f6a7b0bb289a9717c0da543c7ca3c00c91e6 encountered an error during 
CreateContainer: failure in a Windows system call: The locale specific resource for the desired 
message is not present. (0x3ab9) extra info: {"SystemType":"Container","Name":"b26e4accdea2623fb8dd23
7aaff1f6a7b0bb289a9717c0da543c7ca3c00c91e6","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFol
derPath":"C:\\ProgramData\\Docker\\windowsfilter\\b26e4accdea2623fb8dd237aaff1f6a7b0bb289a9717c0da543
c7ca3c00c91e6","Layers":[{"ID":"d6a3c4f2-5af1-5c01-98ab-0ac8f885bcc5","Path":"C:\\ProgramData\\Docker
\\windowsfilter\\4bbf93effd422c58d90bc7c21293555db88a2dfde2c3b160911d628bef120ce2"},{"ID":"d1fd2412-d
953-52f1-a1d2-4d73460bc5a0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b6edac823f5c4912a785995e7
de2e6a39f3dc2db673c989dd23779806a45c222"},{"ID":"3c55dd7a-83f0-5731-977b-925af00b5d1d","Path":"C:\\Pr
ogramData\\Docker\\windowsfilter\\b794174c99e2f2546338694445b258cf78ae60a084f94c8a03267151962fa207"},
{"ID":"f2584625-2f8c-5e28-81f7-bb63f360f355","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8fe86789
92a84c952c1993b816cec04e3b740c2ecb8d49152ed856bceb7632f9"},{"ID":"f258dd8f-822c-5e9e-8c81-99f53e9af45
0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ccc69f8cb0ef0ae81be1397bf0aef5a90090a22910e3348a97
5b141d6f48469b"},{"ID":"3d3a3ab5-f902-5bc4-b814-cd009321e758","Path":"C:\\ProgramData\\Docker\\window
sfilter\\8f1969f99c8e7004fe5d4cd7fe949f4a62d4ee0cc9e69a8983a48153695f3423"},{"ID":"d0ba0c03-256a-573a
-99b1-b88f9d70d676","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cb9f3dedead1d63676d8433d4417d207f
bd41db28feced3358203919fef6f4d7"},{"ID":"eba3298f-0551-57aa-a033-1dcef8276c4c","Path":"C:\\ProgramDat
a\\Docker\\windowsfilter\\2c30131eb8c87e894bc1df574b94d800fc6ba6b605970912aa4e3a2485cd6b7e"},{"ID":"d
df7b39d-ac5a-58f2-88ea-80187d56647f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bf759e84d42dcdc7
725d1e752586fbe6e37e351dfec9ac284e36fa8e03230a7a"},{"ID":"67dd013d-8890-5f5f-9208-afc5873e8673","Path
":"C:\\ProgramData\\Docker\\windowsfilter\\0f1a346a03bdcd8376a9b8018463ea79c8c892617960ecb744cf69b481
73ec89"},{"ID":"98b65ae2-1cfb-5ad2-a38d-9f87277268d7","Path":"C:\\ProgramData\\Docker\\windowsfilter\
\a361f681473ec3017e0a19feabeb3344a3d0d8602008c3532c97c841d342a703"},{"ID":"41a39709-ac6f-5018-93ea-e1
bb02c4a7b8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8fee6207a9c6e274ce477649b72fa87a634ffe415
1326eaf3e1aea83e6f58f4d"},{"ID":"4e188e1c-ba82-57c7-9558-85e349428f06","Path":"C:\\ProgramData\\Docke
r\\windowsfilter\\57b5aee2da172acc5864c625baa8d312e511c2d4d3041f1a579e066286cad75b"},{"ID":"fb1e0a3b-
5cb4-56a6-97d3-ca15404ac106","Path":"C:\\ProgramData\\Docker\\windowsfilter\\94e60c5fc20a7d2cb470284f
2d5644996b386677b8930e88bfc50d37873f9a8c"},{"ID":"5cb25fc6-7fb7-592d-a970-3c771937d0db","Path":"C:\\P
rogramData\\Docker\\windowsfilter\\6cd7ab02e3e3bd7aaa4e39f85230b8b4dd4a8800a27c6e569ef849b0d8faec10"}
,{"ID":"c7737436-62c1-5e55-853a-cb066846e79a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0d2b4ac
e3389f4f53ed43898c296f0a29ac596ed0fb544af167b211762c10bbc"},{"ID":"b03e9b80-854f-5524-8d68-b10dd5047f
ee","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ce7cd5cec3fad1dc84005109a4f5d12f2b477c077938e7ab9
9c832d0b4292e1c"},{"ID":"46b3e479-fde4-58ff-86ad-d6cfd5c8dd80","Path":"C:\\ProgramData\\Docker\\windo
wsfilter\\580bdd1c542b89b32ba3d428153d7af08e69e488653fed224f161e0438e2359a"},{"ID":"77393070-2c05-518
1-aa5d-f87ca9797da7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7fd3a2ed61a48427280fcbce68c03914
b894dcbeda68749e65c63873dee5e491"},{"ID":"34007ac5-ac01-51e3-82b4-5204ee2b11dd","Path":"C:\\ProgramDa
ta\\Docker\\windowsfilter\\2902de47202eb53c8052700e0f19929d5d292b03ce7f4af2eb8a8194d5b91c18"},{"ID":"
f7e5de56-e6b1-51c8-8586-5c95749508ef","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1beb8c8f4aacbc3
cdb785d3c342ee758f31d568bc4fa10f2a78238f9e75b1f34"},{"ID":"6b1afb9e-a459-56da-848a-fc3cec089f2a","Pat
h":"C:\\ProgramData\\Docker\\windowsfilter\\9a945a1a98e0fa80f092ea05c269c5086cb146b95aa27c0d7401e932c
ddbfdc2"}],"MemoryMaximumInMB":4096,"HostName":"MSD365SandboxGB","MappedDirectories":[{"HostPath":"c:
\\programdata\\navcontainerhelper\\extensions\\msd365sandboxgb\\program files","ContainerPath":"c:\\n
avpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath
":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthM
aximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper
\\extensions\\msd365sandboxgb\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":
0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","Conta
inerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0
,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["d6429fbf-af1e-4f9a-9235-c31c047dfec8
"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\1beb8c8f4aacbc3cdb785d3c342ee758
f31d568bc4fa10f2a78238f9e75b1f34\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.
ExitCode: 125
Commandline: docker run --name MSD365SandboxGB --hostname MSD365SandboxGB --env auth=NavUserPassword 
--env username="admin" --env ExitOnError=N --env locale=en-GB --env 
licenseFile="c:\run\my\license.flf" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\MSD365SandboxGB\my:C:\Run\my" --restart unless-stopped 
--memory 4G --isolation hyperv --env enableApiServices=Y --env enableSymbolLoading=Y --env useSSL=N 
--volume "C:\ProgramData\NavContainerHelper\Extensions\MSD365SandboxGB\Program Files:C:\navpfiles" 
--volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b1
6050a5345MgB8AGgAZgBlAFEAYQBuADIAcwA2ADAAcwBnAHUASABvAHEAdAAyAEYAbABDAEEAPQA9AHwANQA2AGMAOQA0ADgAZABh
AGEANwA2AGIANwA4ADAANABlAGIAOABlADYAOQAzADgAYQA1ADIANABhAGQAYgBjADMAYgBlAGUANgA5ADAANwA4AGEANgAwADUAZ
AA2ADMAYgBiAGMAZQA1ADUAZgBlADkAZQA1ADQAZQA4ADgAMwA= --env passwordKeyFile="c:\run\my\aes.key" --env 
removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcsandbox:gb
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.4\ContainerHandling\New-NavCon
tainer.ps1:530 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by sssolammm** [comment]
What command line did you use ?

**Comment by Gokulnath024** [comment]
> What command line did you use ?

New-NavContainer -accept_eula -containerName "MSD365SandboxGB" -imageName "microsoft/bcsandbox:gb" -auth NavUserPassword -licenseFile "D:\Gokul\Setup Files\5430114-NAVLS2018W1-100318.flf" -includeCSide -enableSymbolLoading -doNotExportObjectsToText -assignPremiumPlan -shortcuts Desktop -updateHosts

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
