### ISSUE TITLE
Repeator Header Row Is Disappearing

### ISSUE THREAD

**Issue by JayDashti** [Microsoft/AL#4053]
For example, when you select an Account Schedule from Account Schedules list and then go to Process –> Overview, if you scroll down or (use Ctrl+End) the Header row disappears and the only way to bring it back is to close the page and reopen. 

Is there any workaround for this?

**Comment by StanislawStempin** [comment]
This is a known issue that will be addressed by an upcoming feature. Since it's not related to AL or developer tools we will not track it in this repo but it should be fixed by the Spring release.
