### ISSUE TITLE
Two AL Extensions 2.0 installed instead of updating older version

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#4056]
Installed was 2.0.43900, and 2.0.48254 was installed from AppSource but this did recognise the older version to replace it and thus installed itself side-by-side which lead to an unusable state in VS Code until the older version was disabled.
![alextensionconflict](https://user-images.githubusercontent.com/16236672/47020549-e2abbb00-d159-11e8-872b-46c72d923f67.png)

**Comment by StanislawStempin** [comment]
This is by design. You must have installed one of them from Docker and that one has a different publisher name.

**Comment by StanislawStempin** [comment]
We will be changing the AL Language from the insider program to be named AL Language - Insider in the near future and will be distributing it through the Marketplace as well.

**Comment by Kowa63** [comment]
That's good to hear.
