### ISSUE TITLE
Language not showing?

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4058]
Hi All,

I am not able to select a different language for my BC instance. I am doing it from below window in screenshot.
However I am able to change **Region ** in this window but I cant change language , as it is showing only English(United States) for every region.
![image](https://user-images.githubusercontent.com/33481576/47028321-cbcf8d80-d186-11e8-960c-a60ff73d36d5.png)

Any help would be highly appreciated.

**Comment by StanislawStempin** [comment]
Since this is related to a live BC tenant you would need to contact support with this case.
