### ISSUE TITLE
Issue with nested block comments

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#406]
There's an issue with nested block comments.

I comment out a block in the middle of my code and it works fine:
![image](https://user-images.githubusercontent.com/5204734/28534598-422e4db0-706f-11e7-8113-d2e15b25128e.png)

If I go now and comment out the entire block, it's not formatted correctly, and it gives me a compiler error:
![image](https://user-images.githubusercontent.com/5204734/28534715-98105c0a-706f-11e7-8b7c-e48d63dec3d5.png)

![image](https://user-images.githubusercontent.com/5204734/28534682-82b07980-706f-11e7-9ed7-2e6d1e809f3c.png)

**Comment by atoader** [comment]
Hi! A comment starts with the first /* and ends with the first */.
The behavior you are seeing is what is expected. For example, in XML:
```xml
<test>
<!--  -->
</test>
```

And now if you comment the whole thing:
```xml
<!-- <test>
<!--  -->
</test> -->
```
you will see that the last part of the comment is broken.

**Comment by MikeGlue** [comment]
Ok something to get used to I suppose. :)

**Comment by Gallimathias** [comment]
It's not a bug it's a feature
