### ISSUE TITLE
Modifying the General Journals Page gives error in 'Edit in Excel' functionality

### ISSUE THREAD

**Issue by olisterr** [microsoft/AL#4060]
Hi,
I've made changes in General Journals such as adding and removing the feild through page extension. When I use the 'Edit in Excel' functionality, error comes(refer Screnshot below) not allowing to publish
![genjnl1](https://user-images.githubusercontent.com/35020704/47062312-f8b98a00-d1f2-11e8-8881-fa99f3f8566a.png)

After uninstall and unpublishing the extension following error occurs
![genjnl2](https://user-images.githubusercontent.com/35020704/47062350-20105700-d1f3-11e8-9dc9-07e5ef18b121.png)
![genjnl3](https://user-images.githubusercontent.com/35020704/47062351-20105700-d1f3-11e8-91e6-a6fc8ccf6fbc.png)

To Reproduce
Add feilds 'Shortcut Dimension1' & 'Shortcut Dimension2' and remove few random feilds. Publish the extension in Production. Click the 'Edit in Excel' action
Uninstall and Unpublish the extension and try clicking 'Edit in Excel' action

Expected behavior
Excel should allow publishing the changes in data without any error.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
