### ISSUE TITLE
[Event Request] Table 38: OnAfterValidateShortcutDimCode

### ISSUE THREAD

**Issue by OSHK** [Microsoft/AL#4061]
We need the following publisher to implement additional logic after the ValidateShortcutDimCode function is executed:
_Table 38 - Function ValidateShortcutDimCode:_
**OnAfterValidateShortcutDimCode(Rec,xRec,FieldNumber,ShortcutDimCode)** (_event at the end of the function_)
Thank you!

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by OSHK** [comment]
Event request was moved to the mentioned repository: [https://github.com/Microsoft/ALAppExtensions/issues/29](url)
