### ISSUE TITLE
Can't use BrowseForFolderDialog from Codeunit "File Management"

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#4062]
Hi,

When I test it it give me the following error:

_The_ operation can not be completed because a feature is incompatible (.NET Framework interoperability).

To test it Im using the following code:

`FileMngt.BrowseForFolderDialog('select', '', true);`

I'm using the flag "target": "Internal", and Business Central onPrem image for the docker as the documentation explain.

Thanks,

**Comment by StanislawStempin** [comment]
Are you testing it in the windows client? 
It will not work in the web client, since web client cannot run client side .NET code.

**Comment by sssolammm** [comment]
Thanks for the answer, I am using web client but how I could use windows client with BC docker? Do you mean using dynamics nav 2018 connecting to the docker?

**Comment by sssolammm** [comment]
Found what u told.

Thanks,
