### ISSUE TITLE
County Code Field not found in Table Post Code

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#4065]
Hi,

I can't find field County Code in the Table Post Code however I can see the County Code when I run the table Client table.

Using AL : al-2.0.43900
Docker image: mcr.microsoft.com/businesscentral/onprem:es

This field have been deleted from Post Code?

Thanks,

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
