### ISSUE TITLE
Txt2AL - On after Control Ids & Control names error

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#407]
Hi,

After converting from text to AL see below screen it is giving errors in the onafter control ids and the name of the new control. is it how the Txt2Al converter behaves or do we do something worng please suggest
![image](https://user-images.githubusercontent.com/26792519/28559105-bc6c57fc-7132-11e7-89e3-bfb24bfd9b65.png)

Thanks & regards
Varun Reddy

**Comment by atoader** [comment]
If you export to the new syntax and then convert using the Txt2Al converter, the control should be given a new name. Try to lookup "Assigned User ID".
We tried to give controls more meaningful names. When a control is exported, the exported name is generated in the following manner:
```
name = "";
if(control.hasName())
   name = control.Name;
else if(control.hasSourceExpr())
          name = control.SourceExpr;
      else if(control.hasCaption())
          name = control.Caption

if(name.isEmpty() || alreadyExportedNames.contains(name))
  name = control.Type.ToString() + control.Id;
```
