### ISSUE TITLE
Cannot download Symbol

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/AL#4073]
Hi, 
We have two container running of BC on prem on Azure VM
1. Container1 - Developer Port is 7049
2. Container2 - Developer Port is 5050

Both the container are accessible from WebClient and Developer Environment.

In AL symbols can be downloaded

In AL when using Container2 with port 5050, it gives below error.
launch.json file
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "https://bc2app.southeastasia.cloudapp.azure.com",
            "port": 5050,
            "serverInstance": "NAV",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page"
        }
    ]
}
Sending request to https://bc2app.southeastasia.cloudapp.azure.com:5050/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0
[2018-10-17 23:32:32.71] Error: An error occurred while sending the request.
Unable to connect to the remote server
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.76.6.42:5050

**Comment by Frantic42** [comment]
Did you clear credentials cache? (Ctrl+Shift+P, type clear credentials)

**Comment by anwar0206** [comment]
Yes, tried clearing the credential cache. But same error.

**Comment by Frantic42** [comment]
Conatiner 2 is using SSL also? I had that issue before.

I assume you restarted the container. Are both containers the same version?

Hopefully someone in the loop here will help you better.

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
