### ISSUE TITLE
Unbound controls on page are always editable

### ISSUE THREAD

**Issue by larswestman** [Microsoft/AL#4079]
Controls not bound to a field in the record stays editable regardless if the page is in edit or view mode. At least if PageType = Card. Haven't tried other page types.

"platform": "13.0.0.0",
"application": "13.0.24623.0",
AL Extension: 2.0.48254

**Comment by Frantic42** [comment]
I'd suggest playing with different page types as a workaround, Card Plus, Worksheet, Document.

Be careful with Lists though, as often a variable will have values saved per record, and to get around that I usually send the value back and forth to a codeunit just to store and retrieve it so it remains static.

**Comment by NKarolak** [comment]
This is old behaviour since old NAV versions (Windows Client) even. 
Just "mend" it by assigning another global variable (e.g. named DynamicEditable) to your page field for dynamic visibility.
Set the variable like this:

```
OnAfterGetCurrRecord()
DynamicEditable := CurrPage.EDITABLE;
```

**Comment by NKarolak** [comment]
(sorry if posted twice; somehow GitHub does not display correctly for me today)

This is old behaviour since NAV Windows Client days.
Simply create a new global variable (e.g. Named DynamicEditable) and assign it to the Editable property of your page field(s).

Set the variable like this:
```
OnAfterGetCurrRecord()
DynamicEditable := CurrPage.EDITABLE;
```
