### ISSUE TITLE
Txt2AL - Added key, but after creating the AL file. It came Key1.

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#408]
Hi,

There is only one key added in the table after converting to Al from text it is showing Key1 as shown below

Can you please suggest what we are doing wrong here or does keys do not support for extensions
![image](https://user-images.githubusercontent.com/26792519/28559336-c7acf35a-7133-11e7-95d6-46ce159ffd99.png)

Thanks,
Varun Reddy

**Comment by atoader** [comment]
Looking at the unmodified "Sales Invoice Line" table, I see that all the keys up to and including "Bill-to Customer No." are already defined. 
When you export an extension, only the keys/fields that are added in the delta are exported.

**Comment by bachii1010** [comment]
Hi,

Yes that is correct.
Can you tell me why we are getting this issue what needs to be changed or is it a bug in july update.

**Comment by atoader** [comment]
That is by design. Take a look at #412 for more information.

**Comment by bachii1010** [comment]
Hi,

Can you tell me if in future releases this will be supported for standard table fields also apart from extension table fields.

**Comment by DominikDitoIvosevic** [comment]
@bachii1010 Could you please provide more details on what feature you're asking about?

**Comment by bachii1010** [comment]
@DominikDitoIvosevic  see in my first question comment it is about the support of standard fields in key of extension tables

**Comment by DominikDitoIvosevic** [comment]
This has also been discussed in https://github.com/Microsoft/AL/issues/412
