### ISSUE TITLE
No Windows Authentication possible in AL on webservicecalls between BC instances

### ISSUE THREAD

**Issue by bennyvanlyssebettens** [Microsoft/AL#4085]
Using webservices in AL between 2 BC-instances with windows authentication is not possible?

 TempBlobT.blob.CreateInStream(InStr);

 XmlDocument.ReadFrom(Instr, XMLRequestDoc);

 RequestMessage.Method := 'POST';
 RequestMessage.SetRequestUri(Rec.WebServiceURL);
 RequestMessage.GetHeaders(Headers);
 Headers.Add('SOAPAction', 'sendMessage');

 //AuthText := StrSubstNo('%1:%2', 'Van Lyssebettens', 'MyPwd');
 //SecurityTempBlobT.WriteAsText(AuthText, TextEncoding::Windows);
 //Headers.Add('Authorization', StrSubstNo('Basic %1', SecurityTempBlobT.ToBase64String()));

 RequestContent.WriteFrom(InStr);
 RequestContent.GetHeaders(Headers);
 Headers.Remove('Content-type');
 Headers.Add('Content-type', 'text/xml; charset=utf-8');

 RequestMessage.Content := RequestContent;
 Client.Send(RequestMessage, ResponseMessage);
 Headers := ResponseMessage.Headers();

 ResponseContent := ResponseMessage.Content();

 Message(Format(ResponseMessage.ReasonPhrase()));

 This example is using the Basic authentication, so If i create NST's with database login it will probably work. On Prem we want to use Windows Auth. But it seems there is no way to add a authorization header other than a Basic?

 Why? We use a Master Database that contains all central data. Since we will be working muti-tenant, we will have more than 100 databaes, i don't want to create for every database 1 NST with Windows Auth & 1 with Database Auth.

**Comment by StanislawStempin** [comment]
This is not possible right now. Issue https://github.com/Microsoft/AL/issues/550 is tracking this enhancement.
