### ISSUE TITLE
alc.exe: Add option to build symbols-only package

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#4087]
If I am not mistaken, the only way to get a "symbols-only" package from my app is deploying it to a NAV server and then downloading it's symbols. Is there another way?

It would be awesome if I we'd have an option / or flag in alc.exe to be able to compile an app into a symbols-only package.

The reason why I would like to have this is that this way I can better automate my build processes. I currently need to build and deploy my app onto a NAV server and then download them again. This gets messy quick. Mainly when talking about dependencies.

I know that I can drop the complete .app package into the `.alpackages` folder and alc.exe happily accepts it as a symbol source. But I'd would feel a little better if my sources don't float around if they don't really have to. A symbols-only package would suffice.

**Comment by coffeecup007** [comment]
I vote for this as well, same goal: auto-builds with multiple dependent extensions.

**Comment by pborring** [comment]
Good suggestion. Added to the backlog

**Comment by pborring** [comment]
Good suggestion. Added to the backlog

**Comment by pborring** [comment]
Thanks, good suggestion. Added to our backlog to track it.

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
