### ISSUE TITLE
Table 'XXXX' is missing a matching permission set.

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#4089]
We developed application which works fine in our local environment with no errors but when we are trying to deploy our application on production environment of business central it gives below error.

Package validation failed due to the following error(s): (1,13): error PTE0004: Table '50001' is missing a matching permission set.

(1,13): error PTE0004: Table '50002' is missing a matching permission set.

(1,13): error PTE0004: Table '50003' is missing a matching permission set. 

After error we referred git hub issue #1880 , #2977 , #3066 but none are useful. 

We are giving permission for table 50001 , 50002 and 50003 as under .

        <Permission>
            <ObjectType>TableData</ObjectType>
            <ObjectID>50001</ObjectID> 
            <ReadPermission>Yes</ReadPermission>
            <InsertPermission>Yes</InsertPermission>
            <ModifyPermission>Yes</ModifyPermission>
            <DeletePermission>Yes</DeletePermission>
            <ExecutePermission>0</ExecutePermission>
            <SecurityFilter />
        </Permission>
        <Permission>
            <ObjectType>Table</ObjectType>
            <ObjectID>50001</ObjectID> 
            <ReadPermission>1</ReadPermission>
            <InsertPermission>1</InsertPermission>
            <ModifyPermission>1</ModifyPermission>
            <DeletePermission>1</DeletePermission>
            <ExecutePermission>0</ExecutePermission>
            <SecurityFilter />
        </Permission>

We are using AL Language version 0.16.26913.

We want to deploy our app in "**CA Dynamics NAV 13.0(24630)**" but it gives an error which i mentioned.

**Comment by StanislawStempin** [comment]
Please update to the latest version of AL Language and then try running the new command "Generate permission set containing current extension objects". This will help ensure that all relevant permission sets are created in the right xml format.

**Comment by IvoMol** [comment]
TableData: Read,Insert,Modify,Delete
Table: Execute

**Comment by harshilpatel984** [comment]
We have been trying to solve this issue since last two day than we
generated this issue and we got solution after your reply. I would like to
thank you from me and my team.

**Comment by harshilpatel984** [comment]
> Please update to the latest version of AL Language and then try running the new command "Generate permission set containing current extension objects". This will help ensure that all relevant permission sets are created in the right xml format.

Thank you so much for your reply on the behalf of my team.
