### ISSUE TITLE
Change calculation of Balance fields in Customer and Vendor tables

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/AL#4096]
Customer table has two fields about Balance - Balance and Balance (LCY), but they are not affected by Date Filter.

Change calculation of these fields like:
**old:**
Sum("Detailed Cust. Ledg. Entry".Amount WHERE (Customer No.=FIELD(No.),Initial Entry Global Dim. 1=FIELD(Global Dimension 1 Filter),Initial Entry Global Dim. 2=FIELD(Global Dimension 2 Filter),Currency Code=FIELD(Currency Filter)))

**new:**
Sum("Detailed Cust. Ledg. Entry".Amount WHERE (Customer No.=FIELD(No.),Initial Entry Global Dim. 1=FIELD(Global Dimension 1 Filter),Initial Entry Global Dim. 2=FIELD(Global Dimension 2 Filter),Currency Code=FIELD(Currency Filter),Posting Date=FIELD(Date Filter)))
![balance](https://user-images.githubusercontent.com/34268528/47297576-17b68280-d61e-11e8-9fb0-9729e0cbd5dd.png)

Тhe same case is valid for a table Vendor.

**Comment by stephanweidmann** [comment]
You can use "Net Change"-fields.
there the date filter will be used.

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
