### ISSUE TITLE
XMLport and file transfer to a directory

### ISSUE THREAD

**Issue by armela1981** [Microsoft/AL#4098]
Hello there.
I have created an export xmlport with AL for BC 365.
I have defaulted the file name, smth like PO.csv.
It works great as far as exporting data, however after it is done generating the file, I want to get this file that downloads in the Downloads folder, and place it in a directory on the server connected to my local workstation.
I tried to use the download method but that did not work.

smth like this

DOWNLOAD(FromFile, DialogTitle, ToFolder, ToFilter, ToFile)  

Someone suggested codeunit 419, but I can't figure out which function to use.

I want the xml port to run via the job queue, so the creating of the file and moving it on the server should happen without any user input or interaction. Any ideas ?

**Comment by dNsl9r** [comment]
If you are not talking about OnPrem there is no way to do that. Otherwise you could try to change the Targetlevel in the app.json to internal.
`"target": "Internal"`

**Comment by StanislawStempin** [comment]
For On-Premises solution you can directly use the File APIs or even .NET. 

This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
