### ISSUE TITLE
Native language support for azure functions

### ISSUE THREAD

**Issue by pro4dynamix** [Microsoft/AL#41]
At EMEA Conference 2016 someone told us, that the usage of .net functions will be restricted in the new dev platform. As a compensation I would love to have native language support for azure functions.

**Comment by esbenk** [comment]
For Dynamics 365 for Financials we will for security reasons block access to .net interop. We are investigating other ways to allow developers to solve many of the problems that they have previously used .net interop to solve. Easy access to Azure functions is one of them.

**Comment by pro4dynamix** [comment]
That's great. Thx.
