### ISSUE TITLE
Global Variable used as Expression and tablerelation is not acccepting

### ISSUE THREAD

**Issue by AL4Github** [Microsoft/AL#410]
Hi All,

we have declared a global variable, and used the Global variable as expression for a field and added table relation to the field which is not accepting as shown below. 
![image](https://user-images.githubusercontent.com/28556102/28564461-bae6a98c-7146-11e7-9eda-d52881d3775b.png)

![image](https://user-images.githubusercontent.com/28556102/28564512-d5215d42-7146-11e7-914a-5e8853e8c657.png)

please suggest on this.

**Comment by atoader** [comment]
Hi,

The property 'Type' in the above error message refers to the type of the field on which you are setting the property and the type of the field is determined by the type of the global variable.
What is the type of the CodItemCategory global variable? Is the variable marked with the [InDataSet] attribute?
