### ISSUE TITLE
Codeunit 419 function "UploadFileSilent"

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/AL#4103]
If you can use this function "UploadFileSilent" in an Extension (AL dont throw an Error)
Why isnt the function "DeleteServerFile" available?

So you can pump up the Server with Files, without the chance to delete them correctly

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
