### ISSUE TITLE
Business Central stacks on large invoice posting.

### ISSUE THREAD

**Issue by vrough** [Microsoft/AL#4104]
**Describe the bug**
Hi. We faced the issue with posting Sales Invoices with large numbers of lines in PROD environment of our client AppXite.
After October'18 release of Business Central process of posting Invoices takes much more times than earlier.
For example Invoice with 400-600 line is processed about 4 hours.
Invoice with 1500-2000 lines was processing more than 12 hours and after that was not posted at all.
But no any errors message appear.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Generate Sales Invoice with 1000 or more lines
2. Try to post it.

**Expected behavior**
The invoice should be posted within a reasonable amount of time. Previously it took up to 15 minutes.

**Versions:**
 - Business Central: NL Dynamics NAV 13.0 (24813)

We know that Microsoft is fixing this issue now and we are ready AppXite to be an early trial of the fix.
As it is very important and critical for us.

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application requests and enhancements 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
