### ISSUE TITLE
Docker images/Containers issue

### ISSUE THREAD

**Issue by TweetImrank** [Microsoft/AL#4106]
I am having issue connecting to previous nav docker databases and able to connect to latest one. 
All the previously created databases have same issue  : error

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
The nav2018cu5\SQLEXPRESS server cannot be found. Try again later or contact your system administrator.
---------------------------
OK   
---------------------------

The script I use is (for example)

$imageName = "microsoft/dynamics-nav:2017-cu14-gb"
$containerName = "nav2017cu14"#Split-Path $PSScriptRoot -Leaf

New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -imageName $imageName `
                 -memoryLimit 3G `
                 -auth Windows `
                 -licensefile $mylicense `
                 -updateHosts `
                 -includeCSide

This works without any issues but when I create a new different container/image I cant connect to previous one and get error described above.

Any ideas?

Thanks

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
