### ISSUE TITLE
W1 Version with Azure Container..

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#4107]
Hello,

We have developed an extension with North America version and using the sales tax functionality. When we installed our extension for W1 we are facing some compile related issues. So we would like to redevelop our extension with W1 version and remove the sales tax functionality.

So can someone help me to install a Azure container with W1 version to re develop our extension. Please suggest me the instructions to use W1 for development

Thanks.

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
