### ISSUE TITLE
ReportExtension object type Feature Request

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#4109]
This is an official feature request for extending reports.

This reportextension must allow for:

* extand datasets with new dataitems
* extend existing dataitems with additional columns
* extend requestpage with additional controls

The following events should be made available:

* OnInit
* OnPreReport
* OnPostReport
* OnPreDataItem
* OnAfterGetRecord
* OnPostDataItem

**Comment by StanislawStempin** [comment]
Thank you for officially reporting it:) We will use this issue for tracking.

**Comment by StanislawStempin** [comment]
I have just noticed this is already tracked by https://github.com/Microsoft/AL/issues/1452
Closing as duplicate
I still can't provide any ETA for this feature.

**Comment by StanislawStempin** [comment]
The requests are linked so we will take into account all information provided by you here as well. Scope hasn't changed, We are just keeping chronological order of issues.
