### ISSUE TITLE
Same Action & field Name

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#411]
Hi,

After converting from txt 2 al the it is saying that field and action names should not be same. but we can have an action and field as same name.

This is not correct, please suggest
![image](https://user-images.githubusercontent.com/26792519/28573576-b15cc532-7168-11e7-92eb-8e1704400a38.png)

Thanks & Regards
Varun Reddy

**Comment by atoader** [comment]
Hi Varun,

We have decided to not allow actions and fields with the same name in the same page to prevent common errors and to prevent confusion. Do you get this diagnostic a large number of times in your project?

**Comment by bachii1010** [comment]
Hi,

Yes we have lot of this diagnostic errors coming.
We change for this now.
But is it a possibility that it is going to change in the future releases?

**Comment by StanislawStempin** [comment]
We are not planning to change it in future releases. Our recommendation would be to make sure that names are unique in the original C/AL code if you foresee doing the TXT2AL conversion multiple times in the future.
