### ISSUE TITLE
New AL page created, not available for extending in a new page extension

### ISSUE THREAD

**Issue by ashishsharmanav** [Microsoft/AL#4111]
I created a new page in a workspace. Published the workspace as an extension. And now i am able to see installed extension on the web client. Afterwards i have created a new workspace. Downloaded the symbols. When i am creating a new pageextension using the page i created in previous step however i am not able to get the page created in first step in the list of pages available. Can anyone help please?

**Comment by StanislawStempin** [comment]
You need to add the original extension into the dependency list for the second extension. You do that through app.json "dependencies" property.
