### ISSUE TITLE
[Function Expose] Codeunit 5940 CreateServHeader & CreateAllServLines

### ISSUE THREAD

**Issue by amploba** [Microsoft/AL#4112]
We would like to able to call this two methods in codeunit 5940

- CreateServHeader
- CreateAllServLines

We wil use this two methods to create service invoices

Thanks

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application bugs, application requests and application enhancements.
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
