### ISSUE TITLE
Request for Publishers in Codeunit 22(Item Jnl.-Post Line)

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#4114]
Please add Handled with var in Publisher OnGetValuationDateOnBeforeFindOldValueEntry(OldValueEntry, **var Handled**);

//OnGetValuationDateOnBeforeFindOldValueEntry(OldValueEntry);
Handled := FALSE;
OnGetValuationDateOnBeforeFindOldValueEntry(OldValueEntry,Handled);
IF Handled THEN   
  EXIT; 

Please add OnBeforeInitValueEntry publisher in function InitValueEntry in cu22
OnBeforeInitValueEntry(ValueEntry,ItemJnlLine,ValueEntryNo);
ValueEntryNo is the global variable with var

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application bugs, application requests and application enhancements.
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
