### ISSUE TITLE
Error when publishing/installing NAV Extension

### ISSUE THREAD

**Issue by hermannsson** [Microsoft/AL#4116]
I am trying to publish an app with VS Code to a local NAV Server and get the following error

"The request for path /KronanDataImport/dev/apps?SchemaUpdateMode=recreate failed with code InternalServerError. Reason: Requested value 'Blob' was not found."

However the Extension is visible in the client but when I try to install the following error is displayed:

![image](https://user-images.githubusercontent.com/20382388/47509967-af0e1680-d866-11e8-8e4e-ccef94b339e3.png)

I was previously able to publish and install the app on the same NAV Server, I have also restored another clean database but the error also occurs there.

Any ideas what might be causing this?

**Comment by StanislawStempin** [comment]
Please follow the issue templates
