### ISSUE TITLE
tableextension key references non-extension fields

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#412]
When I add a key to an existing table in a tableextension that references a field in the "base" table AL reports errors.

E.g.
```
tableextension 70000012 tableextension70000012 extends "Human Resource Comment Line" 
{
  fields
  {
    field(50000;"Comment Type";Option)
    {
      CaptionML=ENU='Comment Type';
      OptionCaptionML=ENU='HR,Logistics,Training';
      OptionMembers=HR,Logistics,Training;
    }
  }
  keys
  {
    key (Key2; "Table Name", "No.","Comment Type","Table Line No.","Alternative Address Code","Line No.") 
    {
    }
  }
}
```
Generates the following errors on the fields that are in Table 5208.

> file: '../Modification - Human Resource Comment Line(Table 5208).al'
> severity: 'Error'
> message: 'Reference '"Table Name"' in application object 'tableextension70000012' does not exist'
> at: '17,16'
> source: 'AL'

> file: '../Modification - Human Resource Comment Line(Table 5208).al'
> severity: 'Error'
> message: 'Reference '"No."' in application object 'tableextension70000012' does not exist'
> at: '17,30'
> source: 'AL'

> file: '../Modification - Human Resource Comment Line(Table 5208).al'
> severity: 'Error'
> message: 'Reference '"Table Line No."' in application object 'tableextension70000012' does not exist'
> at: '17,51'
> source: 'AL'

> file: '../Modification - Human Resource Comment Line(Table 5208).al'
> severity: 'Error'
> message: 'Reference '"Alternative Address Code"' in application object 'tableextension70000012' does not exist'
> at: '17,68'
> source: 'AL'

> file: '../Modification - Human Resource Comment Line(Table 5208).al'
> severity: 'Error'
> message: 'Reference '"Line No."' in application object 'tableextension70000012' does not exist'
> at: '17,95'
> source: 'AL'

How do I resolve these errors?

**Comment by atoader** [comment]
The problem is that you cannot reference keys defined on the base table in a table extension. A table extension is a separate "companion" table so you can only define keys containing the fields added in the extension.

**Comment by GreatScott000** [comment]
Okay but I can see this as being a real problem for performance with Flowfields and other high volume table processing.

**Comment by cmrudolph-msft** [comment]
We are aware of the potential for performance issues and have ideas for features to make this better. However, preventing extensions from modifying the base schema (e.g. adding fields or keys directly to it) was a purposeful decision to support other architecture changes - not an oversight.

Please keep us informed about specific scenarios you encounter so we make sure we are thinking about the correct real-world cases.

**Comment by GreatScott000** [comment]
What about sorting?  Say I want a page that lists my employees by Cost Center and Birth Date?  Each are base fields but now index?  Can I set the SourceTableView Sorting to this combination without a key?  It seems to give me a warning message now with now way to resolve it.

Do I need a key for sorting?

**Comment by cmrudolph-msft** [comment]
I am not aware of a case where a key is **required** for sorting. On a large table an index is a good idea (for obvious reasons), which is why the warning exists. Nevertheless, you can choose to ignore the warning and things will still sort. At least they do for me.

The future features I alluded to earlier are intended to solve the "base field is not in an index" case, which runs the risk of not performing very well (for now).

Let us know if you encounter specific scenarios that flat out do not work because of key/index issues.

**Comment by johndcollins** [comment]
I'm getting warnings on a key I added on my extension table. The system doesn't seem to know about the extension table key I added and is still warning me that a key does not exist.

severity: 'Warning'
message: 'Sorting field 'xxxx.' should be part of the keys for table 'Item Ledger Entry''

I added the key to my extension table.

This is on a page where I set the RunPageView=SORTING(xxxx)

**Comment by StanislawStempin** [comment]
The last comment from @johndcollins looks like a bug, thanks for reporting.
