### ISSUE TITLE
Country is not shown in report BC365

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4120]
Hey guys, in my report I would like that not only the address but also the country is displayed under the sender. I do all this in Business Central. Unfortunately, this does not seem to work for me ... If I look at the layout of the report, under the sender there are several fields, which are intended for the address data. Is it normal that the country is never printed or do I have to change the company data?

Thank you for your help in advance

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
