### ISSUE TITLE
Codeunit 12 Function FinishPosting

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/AL#4121]
For extracting our own code out of this function, we need this function with parameter.

FinishPosting(GenJnlLine : Record "Gen. Journal Line") IsTransactionConsistent : Boolean

**Comment by dNsl9r** [comment]
I think you should post the issue here:  https://github.com/Microsoft/ALAppExtensions

**Comment by StanislawStempin** [comment]
This repository is no longer dedicated to handling application bugs, application requests and application enhancements.
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
