### ISSUE TITLE
[Bug] Parts not available in TestPages when they are extending pages

### ISSUE THREAD

**Issue by tomfica** [Microsoft/AL#4123]
**Describe the bug**
If the user creates a page type=ListPart or CardType, then creates page extension and add this part it is not available in TestPage

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a new page of PageType=ListPart; SourceTable = Customer; add "No" and "Name" in the repeter
2. Create page extension for "Customer Card" page and add the part that has been created in step 1 after invoicing tab. Name the part as "ABC"
3. Create a test codeunit and a test within it. Add variable CustomerCardPage: TestPage "Customer Card"
4. When you try to reference to CustomerCardPage.ABC it says that the TestPage doesn't contain its definition.

**Expected behavior**
all extended elements should be available on TestPage - including parts

**Screenshots**
![image](https://user-images.githubusercontent.com/36666101/47557609-082e8680-d909-11e8-8bee-e522588caee4.png)
![image](https://user-images.githubusercontent.com/36666101/47557617-0fee2b00-d909-11e8-8e52-af0c98b2a8da.png)
![image](https://user-images.githubusercontent.com/36666101/47557641-20060a80-d909-11e8-8fe2-81db86f0fc6a.png)

**Versions:**
 - AL Langauge: 0.12.28462

**Comment by StanislawStempin** [comment]
NAV 2018 is no longer supported through this forum. Can you try these steps on the latest Business Central developer preview ?

**Comment by ashik-ivor** [comment]
1. Have you published the app, in which you have extended the page ?

2. If you have published, have you defined the dependencies on the app.json file. ?

3. If you have defined the dependencies, download symbols and then try again.
