### ISSUE TITLE
ExportToNewSyntax Bug with TestPages

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#4125]
Exporting test objects using ExportToNewSyntax flag leads to the issues. All TestPage variables starts referencing TableData objects instead of Testpage objects.

See the screenshot. On the left it's exported withouth ExportToNewSyntax flag, on the right with ExportToNewSyntax  flag.
![image](https://user-images.githubusercontent.com/16342128/47593368-6eea8900-d977-11e8-8cd2-2d7b78de926e.png)

Same issue reported long time ago twice. In both cases it was closed but not solved...
#3037 , #2418

- AL Langauge: 2.0.48254
- Using NAV Model Tools from NAV 2018 build 23572 

Best Regards, 
Gintautas

**Comment by atoader** [comment]
Hi @gintuoklis ! Could you please provide a repro?

**Comment by gintuoklis** [comment]
Here it is:

Create new object

```
OBJECT Codeunit 50000 ExportToNewSyntax Bug
{
  OBJECT-PROPERTIES
  {
    Date=29-10-18;
    Time=13:07:31;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    Subtype=Test;
    OnRun=BEGIN
          END;

  }
  CODE
  {

    [Test]
    PROCEDURE Foo@10014500();
    VAR
      CompanyInformationTestPage@10014500 : TestPage 1;
    BEGIN
      CompanyInformationTestPage.OPENVIEW;
    END;

    BEGIN
    END.
  }
}

```

Export it using newsyntax:

```
Export-NAVApplicationObject -DatabaseName $dbName -Path c:\temp\COD50000-newsyntax.txt -DatabaseServer $dbServer -LogPath $logFilePath -ExportToNewSyntax -Filter 'ID=50000;Type=Codeunit'
```
Export using NAV Model Tools from NAV 2018 build 23572.

**Comment by atoader** [comment]
The issue has been fixed in the latest release. Requests for backporting a bug fix should go through customer support.

**Comment by gintuoklis** [comment]
Well, I will report it through support system. It's not a problem. The problem I see here is your strategy how to handle the bugs and manage releases in general.

I'm pretty sure many partners started or will start their (like we are doing as well) upgrade journey to AL using 2018 version. During our attempt, we stumbled so many bugs that we lost count already. Most of the bugs were already reported that shows that community works. But it really does not add any trust using AL and gives really bad first impression...
