### ISSUE TITLE
How to handle XML Result in D365 BC? because the service never returns JSON result.

### ISSUE THREAD

**Issue by TabrezAjaz** [Microsoft/AL#4128]
Hello everyone,
I am working on API and wrote code in CAL for accessing each XML tag value. But now I want to write code in AL, but don't know how to write. Please help me:

**My XML Content [XmlText] snippet:**
<Access_Token>
    <Instance_Url>https://www.mywebsite.com/</Instance_Url>
    < YourToken>0_YdG/DRSVGCKyy6fx/fdasdY6avs=</ YourToken>
    <Expiration_date>05/28/2019 11:50:14 PM</Expiration_date>
    <Refresh_Token>0_i1G4fADRTVRDfdsac4GjD5R5UoOPks</Refresh_Token>
</Access_Token>

For reference you can look into my previous CAL code:
**getToken(XmlText : Text) : Text**
XmlDocument:=XmlDocument.XmlDocument;
XmlDocument.LoadXml(XmlText);
XMLNodeList := XmlDocument.GetElementsByTagName('Access_Token');
count:=XMLNodeList.Count;

//First for loop to iterate the Access_Token Node-- START
FOR I := 0 TO count - 1 DO BEGIN
DOMNode := XMLNodeList.Item(I);
TempXMLNodeList:= DOMNode.ChildNodes;
childcount:= TempXMLNodeList.Count;
DOMChildNode:=TempXMLNodeList.Item(I);
FOR J := 0 TO childcount - 1 DO BEGIN
  DOMChildNode:=TempXMLNodeList.Item(J);
  IF ( FORMAT(DOMChildNode.NodeType)='Text' ) OR ( FORMAT(DOMChildNode.NodeType)='Element' ) THEN BEGIN
  CurrentElementName:=DOMChildNode.Name;
  IF CurrentElementName = 'Instance_Url' THEN BEGIN
    Instance_URL := DOMChildNode.InnerText;
  END
  ELSE IF CurrentElementName = 'YourToken' THEN BEGIN
    TOKEN := DOMChildNode.InnerText;
  END
  ELSE IF CurrentElementName = 'Expiration_date' THEN BEGIN
    Expiration_date := DOMChildNode.InnerText;
  END
  ELSE IF CurrentElementName = 'Refresh_Token' THEN BEGIN
    Refresh_Token := DOMChildNode.InnerText;
  END
  END; // END of major If condition
END; //Second for loop to iterate the child nodes Access_Token Node -- END
END;//First for loop to iterate the Parent or first node : Access_Token Node -- END

Thanks in Advance.

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
