### ISSUE TITLE
how to access each XML node one by one in AL?

### ISSUE THREAD

**Issue by TabrezAjaz** [Microsoft/AL#4129]
My XML Content [XmlText] snippet:
<Access_Token>
<Instance_Url>https://www.mywebsite.com/</Instance_Url>
< YourToken>0_YdG/DRSVGCKyy6fx/fdasdY6avs=</ YourToken>
<Expiration_date>05/28/2019 11:50:14 PM</Expiration_date>
<Refresh_Token>0_i1G4fADRTVRDfdsac4GjD5R5UoOPks</Refresh_Token>
</Access_Token>

Please provide AL code snippet for reading above XML if anybody already wrote code for XML Reading and iteration.

Thanks in Advance!

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
