### ISSUE TITLE
System Tables in Listparts in Extensions not showing

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#4131]
Under very special circumstances, system tables (such as Date or Integer) are not shown when running an extension:

To reproduce:

- Make sure you have no user permisisons set up in BC on Premise (users may exist, but no user may have any permissions assigned)
- Create a page, similar to (or copy of) 353 "Item Availability Lines" as page 50000 "MyLines"
- extend (or create a copy of) page 157 "Item Availability by Periods" and add the page 50000 as part to it
- run the new (or extended) page. The page part is not showing.

To show it, a user must exist and have user rights assigned.

This occurs with the above conditions only. We have not seen it with any other tables (except for system tables). The sub page even shows when the listpart uses "SourceTableTemporary"=Yes.

If required, I can provide an example extension to demonstrate this issue, but it seems quite easy to reproduce when following the steps above.

**Comment by StanislawStempin** [comment]
Closing due to this being corner case scenario and no additional input.

**Comment by ThomasBrodkorb** [comment]
Well, just as an info:
It happens on a new CRONUS database while developing.
In the dev phase, nobody sets up users (as far as I remember) in a CRONUS database!!!!
