### ISSUE TITLE
How to remove an extension after a failed upload? (Cloud demo)

### ISSUE THREAD

**Issue by chris-amco** [Microsoft/AL#4134]
AL version : 2.0.43900
Server version : 13.0.24630.25242-US

I am trying out the Upload Extension function in a demo tenant on https://businesscentral.dynamics.com/.

- My 1st attempt failed due to a compilation error (caused by a difference between the US version of the demo system and the W1 version I used in development).
- I downloaded the correct sandbox, resolved the compilation error and recompiled.
- My 2nd attempt failed with error "An extension with same App ID and version has already been uploaded. Resolve and deploy again."

Question : how can I uninstall & unpublish the first upload to make way for the recomplied app? 
The extension is not listed in the Extensions page and I don't know of a way to use PowerShell on a cloud demo. 

For now I have worked around the problem by altering the App ID.

Thank you in advance.

**Comment by JohanStenberg100** [comment]
@chris-amco are you using the sandbox? You can reset it by heading to  [ https://businesscentral.dynamics.com/](https://businesscentral.dynamics.com/) and then searching for _Sandbox_ and select _SANDBOX ENVIRONMENT (PREVIEW)_. Then you can reset your sandbox. Later you can try to redeploy with the original app id.

Can you try to provide a clear repro for this issue? When you deploy and the App ID is used but you don't see the extension in the _Extensions_ page.

**Comment by chris-amco** [comment]
[4134.zip](https://github.com/Microsoft/AL/files/2530211/4134.zip)

Thanks for your reply. I was not using the online sandbox. I was uploading to the "production" demo system.

I've attached 2 copies of the same repro app. 
- Folder "4134_1" : compiled on docker container v13.0.24630.25242-W1.
- Folder "4134_2" : compiled on docker container v13.0.24630.25242-US.

I usually use the W1 container for development. I obtained US container from "Container Sandbox Environment (Preview)" -> "Host locally" on the cloud demo system.
The .app file in 4134_1 cannot be uploaded to a US system due to a compilation error. In 4134_2, I made a change to avoid the compilation error.

Repro steps
1. Log in to a cloud demo environment (US).
2. Extensions > Upload Extension > choose the .app file in folder 4134_1. It will fail with the following error:

> Deployment failed. Errors: App ID : 2854f490-2e7a-4bdf-b5ff-c5d8587674a7 Message : { Extension compilation failed
> 
> code/pageextension/Pag-Ext50100.4134_PostedPurchaseInvoice.al(5,18): error AL0248: '"Payment Method Code"' is not found in the target } - Job Id : 0cb2259e-ea40-4dab-a59f-9b6682fe8c03
> 

3. Try again with the .app file in 4134_2. It will fail with the following error:

> Deploy Operation rejected. Error: An extension with same App ID and version has already been uploaded. Resolve and deploy again.; - Job Id : 6504db0e-dd3d-435b-8eb8-21b9eddff14a

But the failed extension does not appear in the Extensions page and I cannot see any other way to remove it.

**Comment by HunterFeltman-MSFT** [comment]
In order to get around this issue (without changing the AppId) you will have to bump the version number of your extension as the original one is already stored and cannot be 'overridden'.

There is some future work in/around some better management of the packages uploaded in this manner that may include this feature (deletion), but for now you have to be conscious of what you upload.

**Comment by chris-amco** [comment]
Okay, understood. It was the first time I had tried uploading a package and I just wanted to make sure that I hadn't missed anything. 

Thanks for the advice.
