### ISSUE TITLE
It is not possible to have the editable field for the page which has UsageCategory=List or UsageCategory=History

### ISSUE THREAD

**Issue by RedFoxUA** [Microsoft/AL#4136]
Hi.

I'm using the build Dynamics.110.NA.2468045.
I have something like a historical table (e.g. payment Ledger Entry) and I want to organize a page with the filter or search "field" on the top of this page. And it is not possible to have an _editable_ field for the page which has property UsageCategory=List or UsageCategory=History.
It very inconvenient if I want to set any filters.

**Comment by StanislawStempin** [comment]
I'm not sure I understand your issue. Can you provide sample AL code for this problem if it's related to the new development tools?

If it's a general product feature suggestion then you should go to https://aka.ms/bcideas site.

**Comment by RedFoxUA** [comment]
OK, np.
We have the page like below (with filter field).
If we have UsageCategory=List or UsageCategory=History the source field "Payment Request Id Filter" is not editable at all. And if we need to have editable TextField or Combo (option) it is not possible.

page 50140 RESTWebServiceLogEntries
{
    PageType = Worksheet;
    SourceTable = RESTWebServiceLogEntry;
    Caption = 'Web Service Log Entries';
    UsageCategory = Documents;
    ApplicationArea = All;
    ShowFilter = false;
    InsertAllowed = false;
    ModifyAllowed = false;
    DeleteAllowed = false;

    layout
    {
        area(Content)
        {
            field("Payment Request Id Filter"; PaymentRequestIdFilter)
            {
                ApplicationArea = Advanced;
                Caption = 'Payment Request Id Filter';
                ToolTip = 'Test value';

                trigger OnValidate()
                begin
                    if PaymentRequestIdFilter <> '' then
                        SetFilter(PaymentRequestId, PaymentRequestIdFilter)
                    else
                        SetRange(PaymentRequestId);
                    CurrPage.Update(false);
                end;
            }
            repeater(Group)
            {
                Editable = false;
                field("Entry No."; "Entry No.")
                {
                    Visible = false;
                    ApplicationArea = All;
                }
                field(Description; Description)
                {
                    ApplicationArea = All;
                }
                field("Document No."; "Document No.")
                {
                    ApplicationArea = All;
                }
                field(Amount; Amount)
                {
                    ApplicationArea = All;
                }
                field("Currency Code"; "Currency Code")
                {
                    ApplicationArea = All;
                }
                field("Posting Date"; "Posting Date")
                {
                    ApplicationArea = All;
                }
                field("User ID"; "User ID")
                {
                    Visible = false;
                    ApplicationArea = All;
                }
            }
            group(Balance)
            {
                Caption = 'Expected Bank Account Balance';
                Editable = false;
                Visible = ShowBalanceSecion;

                field(SourceBankBalance; SourceBankBalance)
                {
                    Caption = 'Current Balance : ';
                    ApplicationArea = All;

                }

                field(ReadyToGoPayment; ReadyToGoPayment)
                {
                    Caption = 'Total In Progress : ';
                    ApplicationArea = All;

                }
                field(FinalBalance; FinalBalance)
                {
                    Caption = 'Expected Updated Account Balance : ';
                    ApplicationArea = All;
                }
            }
        }
}

**Comment by thpeder** [comment]
Hi @RedFoxUA,
I have tried to reproduce your problem with the lastest bits but couldn't get to your problem. Please provide a small piece of AL code that reproduces on the latest bits, Either try the sandboxes we have available or consider signing up for the Ready To Go program in order to test on the bleeding edge.

**Comment by RedFoxUA** [comment]
It is very easy - just create Page with UsageCategory = Documents and Add any data like below with var PaymentRequestId: Text :
            field("Payment Request Id Filter"; PaymentRequestIdFilter)
            {
                ApplicationArea = Advanced;
                Caption = 'Payment Request Id Filter';
                ToolTip = 'Test value';

                trigger OnValidate()
                begin
                    if PaymentRequestIdFilter <> '' then
                        SetFilter(PaymentRequestId, PaymentRequestIdFilter)
                    else
                        SetRange(PaymentRequestId);
                    CurrPage.Update(false);
                end;
            }

Is this field editable when you run this page?

**Comment by thpeder** [comment]
I did that, I had PaymentRequestIdFilter as a global variable and tried having the UsageCategory as Documents and Lists and both had the same behavior, that the field was editable.

**Comment by RedFoxUA** [comment]
I will prepare example near time and try to attach it here

**Comment by atoader** [comment]
Hi @RedFoxUA ! Are you still facing this problem?
