### ISSUE TITLE
Alc.exe parameter 'assemblyProbingPaths' is not documented

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#4138]
alc.exe is missing documentation for assemblyProbingPaths parameter.
it's necessary to set this parameter if you are using dotnet types within you extension. Otherwise it gives compilation errors while using alc.exe compiler.

Here's example how you could use this parameter:
`alc.exe /project:$projectDirectory /packagecachepath:$packagecachepath /target:internal /assemblyProbingPaths:"C:/Windows/assembly/","C:/Program Files/Microsoft Dynamics NAV/110/Service/Add-ins"`

ALC Version: 2.0.48254

**Comment by atoader** [comment]
Hi @gintuoklis ! Thanks for reporting this. We will add documentation.
