### ISSUE TITLE
I can't access to Test Toolkit

### ISSUE THREAD

**Issue by jaloag** [Microsoft/AL#4139]
Hi all.

I can't Access to the "Test toolbox" page in my Docker sandbox. I've used the -includetesttoolkit option when I created it.

Steps:
1. I've created the Docker BCSandbox using NavContainerHelper:

> New-NavContainer -accept_eula -containerName "D365BC" -auth NavUserPassword -imageName "microsoft/bcsandbox:es" -licenseFile "C:\BusinessCentral\XXXX.flf" -includeTestToolkit -assignPremiumPlan

![image](https://user-images.githubusercontent.com/33660849/47726886-ab5e0380-dc5b-11e8-8299-74af1ea71e9a.png)

Everything seems ok, and my D365BC container is running and BC client accesible. But when I search the "Test toolbox" page... doesn't appear.

![image](https://user-images.githubusercontent.com/33660849/47727041-fd068e00-dc5b-11e8-995f-c38d419609b4.png)

 - Business Central: ES Dynamics NAV 13.0 (24844)

Any idea?

Thanks a lot.

**Comment by pmohanakrishna** [comment]
try below url
http://containername/nav/?page=13401

**Comment by jaloag** [comment]
Thanks Mohana.

It seems like the test toolkit hasn't been imported!

![image](https://user-images.githubusercontent.com/33660849/47801230-04966780-dd2e-11e8-9da8-f385d9af3f05.png)

I don't understand. You can see in previous pic that testtoolkit was successfully imported. :-?

**Comment by ashik-ivor** [comment]
Even I am facing the same issue. Test tool is not visible in Web Client.

But if you try to open the test tool on the Windows Client, it is populating from search box.

**Comment by ashik-ivor** [comment]
Create a new container with "-includeTestToolkit". 

When the container is successfully created, go to desktop and you will find a shortcut file, as .... Test Tool.

Double click and the test tool page will be opened.

![image](https://user-images.githubusercontent.com/38459860/47837940-c81d4700-ddd3-11e8-827c-7267f64f774f.png)

**Comment by StanislawStempin** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
