### ISSUE TITLE
Expose functions in library codeunits

### ISSUE THREAD

**Issue by CameliaPopescu** [Microsoft/AL#4143]
Hi,

We would need to use the following functions when creating a unit test codeunit in AL:
- CreateStandardTextWithExtendedText and CreateCustomer in "Library - Sales"
- Enqueue in "Library - Variable Storage"
- CreateCBGStatement and CreateCBGStatementLine in "Library - NL Localization"

Please make them external, so we can use them in AL.

Thank you!

**Comment by JohanStenberg100** [comment]
Hi @CameliaPopescu! Thanks for reporting this. This repository no longer handles these type of requests, just copy-paste your issue and post it over at [https://github.com/Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions).

**Comment by ashik-ivor** [comment]
Define the test tag on the app.json file and download symbols again.
![image](https://user-images.githubusercontent.com/38459860/47835655-167a1800-ddcb-11e8-8298-ecda973874ab.png)
