### ISSUE TITLE
How to set up business central app from windows store in window 10 for local host?

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#4146]
1)I have Downloaded Business Central Application from microsoft store.
2)I want to access my local hosted serveice.
3)It gives an error as under.
`Could not connect to Server`

**Comment by JohanStenberg100** [comment]
Hi @harshilpatel984, the business central app downloaded from the microsoft store is not a full server. For these types of questions which aren't directly related to the developer experience, please go through our support channels instead:

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)
