### ISSUE TITLE
Error: An internal error has occurred when publish app to Docker

### ISSUE THREAD

**Issue by TravisChe** [Microsoft/AL#4148]
I had created a BC sandbox and hosted on my local PC by following the user guide as below URL.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox#set-up-a-local-hosted-container-sandbox

I manage to create the sandbox on my local PC and it is accessible.
![image](https://user-images.githubusercontent.com/40016152/47840278-c8780b00-ddf0-11e8-8c04-2c271c39dfbb.png)

I'm able to download symbols for my project.
![image](https://user-images.githubusercontent.com/40016152/47840382-0b39e300-ddf1-11e8-87b9-50e4924b1902.png)

When I try to publish my app (regardless F5 or Ctrl + F5), I'm hitting the "Internal error has occurred".
Kindly advise is there anything I missed out or further configuration I should perform.
![image](https://user-images.githubusercontent.com/40016152/47840463-4a683400-ddf1-11e8-8069-0a9060a2a5c4.png)

**Versions:**
 - AL Langauge: 2.0.48254
 - Business Central: US Dynamics NAV 13.0 (25242)

**Comment by JohanStenberg100** [comment]
Hi @TravisChe, using the `AL:Go!` template I'm able to publish using the docker image. Please attach here a ZIP file with a consistent repro. If you wish to unblock yourself you can also try with a later version of the docker image.

**Comment by TravisChe** [comment]
Hi @JohanStenberg100, I didn't use docker anymore. I'm using Business Central on premise currently, same error after I published the package. Below is my launch.json settings.
![image](https://user-images.githubusercontent.com/40016152/48878582-f924f080-ee42-11e8-8292-215a29b58ec0.png)

The package doesn't publish to my BC as well.
I do not have issue with downloading symbol.

**Comment by JohanStenberg100** [comment]
Hi @TravisChe, thanks for the update. Please post me your BC on-prem version. Furthermore what type of AL program are you trying to publish? Can you try to create a small app which consistently reproduces the issue and then post it here as a ZIP file?

**Comment by StanislawStempin** [comment]
If you could also please provide the exception from the server Event Log that would be helpful

**Comment by atoader** [comment]
@TravisChe are you still facing this issue?

**Comment by atoader** [comment]
Hi @TravisChe! I will assume that the issue has been resolved and close it.
