### ISSUE TITLE
Object Already delcared

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#415]
Hi,
Whenever I execute the objects it displays the message that the number given to code unit object is already exist.
**An Application object of type codeunit with id 'XXXXXXXX' is already declared** 

Kindly let me know how to resolve.

Amol

**Comment by Gallimathias** [comment]
Change the ID then just try it until you get a non-assigned ID.

**Comment by thpeder** [comment]
If you see the error in the 'Problems' panel that means you have two codeunits with the same id in your source code and you can then click on the errors to go to the codeunits.
However if you get this message when you try to publish your extension, then you probably have another extension published to the server with a codeunit that uses the same id.

You can fix this by changing the id of your codeunit in the extension you are trying to publish to something not in use or uninstalling the extension on the server by going to the page 'Extension Management'.

**Comment by AmolSalvi** [comment]
Thanks for response as I changed the id of object as I couldn't find the same id object in my project and even though extension was not installed.

**Comment by DominikDitoIvosevic** [comment]
I could be that you published your extension, changed the name and then tried republishing. You may not have the source code for the previously named extension anymore but it's still published to the server

**Comment by DominikDitoIvosevic** [comment]
@AmolSalvi can we help you further with this? Right now we need more info to be able to try and repro this

**Comment by AmolSalvi** [comment]
Hi Domini
Thanks for your help. Its resolved 

Regards
Amol
