### ISSUE TITLE
Viewing standard source from VS Code - AL Extension

### ISSUE THREAD

**Issue by devhigh1992** [Microsoft/AL#4153]
Please find a way to view and debug standard Business Central source code from VS Code extension.
this would bring tremendous opportunity for this product to be more popular.
- Learning curve is much shorter
- Setting break points for diagnosis 
- faster to find where is the location to make a extension
- and there is so much more...
there is already an extension but it shows nothing else except id, name plus some code reflections.

furthermore, It would be so much convenient if we can add delegate and event subscriber without sending a request. I'm sure the product will grow, and there will be plenty more code units, tables.. 

Thank you so much.

**Comment by JohanStenberg100** [comment]
@devhigh1992 thank you for this feedback. We are in the process of completing the transition to AL and an app-based ecosystem. As of right now there are not any plans to allow this but I will mark your opened issue with a "suggestion" tag and we will make sure to discuss it internally.

**Comment by JohanStenberg100** [comment]
@devhigh1992 sorry I miss-understood your suggestion.

We will not allow adding delegates / event subscribers without sending requests to a cloud environment. But if you have an on-premise solution you can customize the base app.

Furthermore, you can today view and debug app code, so this should not be an issue. I will close this issue now, if you have issues debugging try using the latest AL extension and BC versions.

**Comment by devhigh1992** [comment]
Sorry, I would have missed something,
I know we can debug to the standard source code, but I don't know how to
view standard code before debugging. Could you please enlighten me?

example, we want to find a right integration point we would follow some
steps.
 1. we view the page code or job code,
2. putting a best break point assuming it'll run past this point.
3. then run the application to debug.

right now, I could not see any possible way without deploying a page
extension and delete this page afterward if we don't need.  Please show me
how to achieve the point (1) or there is other way to find the right
integration point which I did not know.

Also, we need to request for delegates/events, and making customisation in
the base app for the on-premise solution. are we maintaining two standard
AL and C/AL?

thanks

**Comment by JohanStenberg100** [comment]
@devhigh1992 if you customize your base app in an on-premise solution and then depend on that customization, you can't easily publish your extension. As this is an on-going process there is a big effort towards adding the correct delegates and events, which will help you to adapt to an app-based ecosystem.

To view the code you can usually use the "go to definition" functionality in Visual Studio Code. You can also try [this VS code extension](https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline).

If you have any further questions I'll recommend you try out one of these resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by kalberes** [comment]
Hi,

You should be able to do to definition to the base app code, and that should show the full code. Well it should show the code in the debug format that was available for the RTC debugger too. And you should be able to place breakpoints there and those should be hit.
See here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-code-navigation

Is this not what you are experiencing?

**Comment by devhigh1992** [comment]
Hi,
Yes, I can navigate to base code. That is I already know which I have
mentioned in my previous response.
>>>
There is the "Go to definition", but we need to have something to "Go to"
in the first place.
<<<

please close this one, I was looking for D365 FinOps' AOT
