### ISSUE TITLE
ApplicationArea without UsageCategory

### ISSUE THREAD

**Issue by IvoMol** [Microsoft/AL#4156]
**Describe the bug**
Not able set page properties to be page not searchable, but visible only in specific application area.

**To Reproduce**
page 50101 "Test Usage Category"
{
    UsageCategory = None;
    ApplicationArea = Basic;
}

**Expected behavior**
Analysis rule AL0167 does not allow put AppliactionArea propert if UsageCategory is missing (current state, OK).
Analysis rule AL0167 allows put AppliacationArea property if UsageCategory = None.

Please update Analysis Rules on documentation pages (no AL* rule described).

**Versions:**
 - AL Langauge: 2.0.48254
 - Business Central: Dynamics NAV 13.0 (24630)

**Comment by StanislawStempin** [comment]
This is currently by design. ApplicationArea on the page is not used for visibility of the page itself but only for the visibility of the search record.
We will be improving this in the upcoming release.
