### ISSUE TITLE
Language aware folding (depends on Microsoft/vscode#3422)

### ISSUE THREAD

**Issue by StHillmann** [microsoft/AL#416]
Could you please change the intendation of shortcut "tprocedure" to indent "var" and "begin...end" to make it possible to toggle procedures.

Old behaviour:
![image](https://user-images.githubusercontent.com/1138628/28620288-9706e4ca-720c-11e7-8b2e-7a73909845af.png)

New behaviour:
![image](https://user-images.githubusercontent.com/1138628/28620363-e6fcc922-720c-11e7-976b-e9427cb0b7ea.png)

**Comment by atoader** [comment]
It is mostly a coincidence that VSCode offers you the possibility of collapsing the entire procedure when it is indented as you've shown. 

We will try to teach VSCode how collapsible block looks like in AL in the future. For the moment, you can get around this inconvenience by creating your own snippet for procedures.

**Comment by DominikDitoIvosevic** [comment]
We are blocked by https://github.com/Microsoft/vscode/issues/3422

**Comment by StanislawStempin** [comment]
This is now unblocked and on our backlog for implementing the support

**Comment by TonyHemy** [comment]
> This is now unblocked and on our backlog for implementing the support

Thanks @StanislawStempin

**Comment by JavierFuentes** [comment]
@StanislawStempin,
please consider that mixing **{ ... }** with **begin .. end** for structural blocks is a problem with folding and indentations...

Now we have this for triggers:
![image](https://user-images.githubusercontent.com/5801847/48969490-a3e20e00-efff-11e8-900f-0542b64b5036.png)

In this case, indentation don't solve the folding problem:
![image](https://user-images.githubusercontent.com/5801847/48969583-f1ab4600-f000-11e8-8dd8-a520e85629a5.png)

I would like something like this (with triggers, procedures, and all structural blocks):
![image](https://user-images.githubusercontent.com/5801847/48969691-7a76b180-f002-11e8-9103-96ede13b1c76.png)

So, I could fold main blocks of every structure:
![image](https://user-images.githubusercontent.com/5801847/48969707-b3168b00-f002-11e8-8ee6-0fbdfb731fd0.png)

![image](https://user-images.githubusercontent.com/5801847/48969712-cf1a2c80-f002-11e8-9755-6d6ffd683008.png)

**I see cleaner to put { in the same line than in the next line with automatic format...**

**Comment by EmilDamsbo** [comment]
This feature has been implemented some time ago and is available in the latest extension version.
