### ISSUE TITLE
DataCaptionExpression error

### ISSUE THREAD

**Issue by thomasbook** [Microsoft/AL#4161]
In a page extension setting the  DataCaptionExpression property 

The following gives no AL error however will not run.
 DataCaptionExpression = "new field" 

The flowing gives and AL error
 DataCaptionExpression = "existing field" 

Was looking to add the new field with existing fields
Versions
AL: 2.0.48254
BC: 13.0.24623

**Comment by StanislawStempin** [comment]
Could you please give a more complete example. What do you mean by new field? 

Please also try the field names without the double quotes (especially if the field doesn't contain special characters/spaces). We had a bug where in some contexts the double quoted identifiers would be accepted by the compiler but rejected by the server.

**Comment by StanislawStempin** [comment]
Closing due to lack of input and no repro on our side.
