### ISSUE TITLE
REPORT.SAVEASPDF cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4163]
when i am trying to save the report in pdf format by using the  REPORT.SAVEAS function giving the below error

----------------------------------------------------
[AL] The type or method 'SaveAsPdf' cannot be used for 'Extension' development.
procedure SaveAsPdf(Number: Integer, FileName: Text, var [Record: Table]): Boolean
Saves a report as a .pdf file.**
----------------------------------------------------

How can we save the file in pdf in AL Extension ?

**Comment by StanislawStempin** [comment]
You can use Report.SaveAs, passing ReportFormat::Pdf parameter and save it into a PDF stream
