### ISSUE TITLE
Error message 'callback functions are not allowed' should not appear during app install

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#4165]
If you have an outgoing HTTP call during installation of an extensions, then you get the error message 'callback functions are not allowed'. Apparently because outgoing HTTP calls are blocked by default in the sandbox.

In fact this is the same error message as documented here: https://docs.microsoft.com/en-us/dynamics-nav/handling-ui-interaction-when-working-with-web-services.

I want to suggest to check GUIALLOWED (or whatever you have in the platform) before trying to display the popup to ask the user if he wants to allow or block the HTTP call. In case of a non-gui session, just block the call and set IsBlockedByEnvironment on the HttpResponseMessage to true.

Obviously, this only applies when there is no record in the NAV App Settings table for the app.

**Comment by ajkauffmann** [comment]
Latest sandbox:

![image](https://user-images.githubusercontent.com/19155831/48066645-71967b00-e1ce-11e8-8319-b742a4a2b53f.png)

What is that fix about?

**Comment by atoader** [comment]
The fix does exactly what you described in the proposed solution. It might be that the sandboxes have not been updated to the version that contains the fix. I will double check.

**Comment by atoader** [comment]
Hi @ajkauffmann ! I tested it on the branch from which the 13 updates are released and I get:
```
The request for path ... failed with code 422. Reason: Could not install the extension ALProject3 on tenant default due to the following error: The request was blocked by the runtime to prevent accidental use of production services.
```
The fix has not been deployed because it was not critical enough to warrant a hotfix. It will be deployed in the future.

**Comment by ajkauffmann** [comment]
Hi @atoader, thanks for the heads up.
Just to clarify: does this mean that instead of getting an error message about callback function, we now get a more informative error message about 'accidental use of production services'?

If that is correct, then please consider to change this. I'm afraid it's not really going to help because this will still block the development process. Why not allow the installation, but just block the web service call? In that case, set IsBlockedByEnvironment to true and let the developer handle it themselves.

Please keep in mind that most people use a sandbox (local or online) to develop against, and here we have this behavior already. It's not really helping us, and forces us to write code to enable the webservice calls. If all apps are going to implement that, because of the problems during development, then I'm afraid the whole safety procedure to block calls is not going to have the desired effect.

**Comment by ajkauffmann** [comment]
That makes sense, thanks for the clarification. I will update my blog post as well.

**Comment by dkatson** [comment]
Thanks god i found this thread:) Spent about half a hour trying to undersand what's going on. Met "The request was blocked by the runtime to prevent accidental use of production services." for the first time :) Thanks
