### ISSUE TITLE
Multiple idRange in one app.json

### ISSUE THREAD

**Issue by tomddlc** [Microsoft/AL#4169]
We have an ISV solution which has evolved over a period of 14 years. During that time we have two times had the need for an additional range of object numbers.
Now we are in the process of migrating the solution to an extension, and we are running into the limitation, that the app.json only allows for a single idRange. That means we are forced to have an idRange in the app.json which goes from the start of our first range to the end of our last range.

But that means, that we cannot use ctrl-space to suggest the next available number for a new object, because it will suggest a number not allowed. That results in manual handling of object numbers - and with 1600+ objects, that is a time consuming task.

So would it be possible to add support for multiple idRanges in the app.json file?

**Comment by PooyaKharamesh** [comment]
Hi @tomddlc, 

We are finalizing a feature that will allow you to specify multiple Id ranges in the app.json. Stay tuned for the November preview release.

thanks and regards 
Pooya
