### ISSUE TITLE
Adding integers and Dates

### ISSUE THREAD

**Issue by MrDavid5465** [microsoft/AL#417]
It appears that I cannot add a date and an integer together unless the date comes first in the calculation.

License.S365_PetLicenseDate : Date;
LicenseTerm.TermInDays : Integer;

![image](https://user-images.githubusercontent.com/29601581/28620640-d285faee-71db-11e7-84c8-396765ba8f47.png)

![image](https://user-images.githubusercontent.com/29601581/28620690-09a6a780-71dc-11e7-9622-ae4722afd7bf.png)

This is a bug I think.

**Comment by atoader** [comment]
This should be consistent with the behavior in C/SIDE. When we implemented this, our goal was to keep the old behavior until we got a better understanding of the subtleties of the language and the runtime. We will consider removing this restriction.

**Comment by nndobrev** [comment]
This has been fixed.
