### ISSUE TITLE
Unhandled exception using FilterAsYouTypeControl when default launch page set to 16

### ISSUE THREAD

**Issue by Wiechardt** [Microsoft/AL#4171]
When making use of the Global Search (the Lightbulb control top right) and clicking on the link of another list page in the search results whilst viewing the Chart of Accounts page, the browser crashes.

1. Change the "launch.json" file by adding these tags:
"startupObjectId": 16,
"startupObjectType": "Page",

2. Upon launching into the Chart of Accounts page, click on the Lightbulb and search "User Setup"
3.  Click on the User Setup in the search results

![image](https://user-images.githubusercontent.com/44084862/48116879-19b05080-e270-11e8-9f42-b67b61a948ca.png)

This is the error in the Application Event Log:

_Error accessing Website 
Unhandled error occurred on a browser or device client:
{
  "clientInfo": {
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
    "browserLanguage": "en-US"
  },
  "message": "Uncaught TypeError: Cannot read property 'Identifier' of null",
  "pageUrl": "http://localhost:13080/bc130/?page=16&debuggingcontext=55d78b44-cfd6-4794-938a-547dfc0ef0a0&sk=55d78b44-cfd6-4794-938a-547dfc0ef0a0&runinframe=1",
  "originalError": {},
  "location": {
    "name": "http://localhost:13080/bc130/js/desktopTSFramework.js?h=8D13AC71966E5A0ECE54A1AB1FF3D7B95570F33B80C6305A7D6679A64A59FAF5&_v=13.0.0.0",
    "url": "http://localhost:13080/bc130/js/desktopTSFramework.js?h=8D13AC71966E5A0ECE54A1AB1FF3D7B95570F33B80C6305A7D6679A64A59FAF5&_v=13.0.0.0",
    "lineNumber": 1,
    "columnNumber": 240300
  },
  "detailedMessage": "    at Array.map (<anonymous>)\r\n    at e.build (http://localhost:13080/bc130/js/desktopTSFramework.js?h=8D13AC71966E5A0ECE54A1AB1FF3D7B95570F33B80C6305A7D6679A64A59FAF5&_v=13.0.0.0:1:240142)\r\n    at DN.PageSearchFormAdapter.searchTermUpdated (http://localhost:13080/bc130/js/framework.js?h=326B70E6D3AB6E547BCB7012F6D2D5477E3205BD1A8BA90BB41F8F125406BABC&_v=13.0.0.0:2845:5520)\r\n    at Function.b [as invoke] (http://localhost:13080/bc130/js/mscorlib.js?h=1C249945039793E18112AD33FA6F4D426F22A89A96E2E163A0671BD1264A4100&_v=13.0.0.0:1:26172)\r\n    at DN.FilterAsYouTypeControl.<anonymous> (http://localhost:13080/bc130/js/framework.js?h=326B70E6D3AB6E547BCB7012F6D2D5477E3205BD1A8BA90BB41F8F125406BABC&_v=13.0.0.0:3740:71)\r\n    at Function.b [as invoke] (http://localhost:13080/bc130/js/mscorlib.js?h=1C249945039793E18112AD33FA6F4D426F22A89A96E2E163A0671BD1264A4100&_v=13.0.0.0:1:26172)\r\n    at DN.CallbackOperation.set_status (http://localhost:13080/bc130/js/framework.js?h=326B70E6D3AB6E547BCB7012F6D2D5477E3205BD1A8BA90BB41F8F125406BABC&_v=13.0.0.0:4934:339)\r\n    at DN.CallbackManager.$2F (http://localhost:13080/bc130/js/framework.js?h=326B70E6D3AB6E547BCB7012F6D2D5477E3205BD1A8BA90BB41F8F125406BABC&_v=13.0.0.0:4930:3985)\r\n",
  "requireUserToSignOut": false,
  "silent": true
}_

**Versions:**
 - AL Langauge: 2.0.48254
 - Business Central: W1 13.0 (24630)

**Comment by StanislawStempin** [comment]
Does it happen only if you published an extension or is it just a client search bug that always occurs?

**Comment by AndreyKorepanov** [comment]
Hi @Wiechardt, thank you for reporting the issue. I could not get repro with the latest version of AL extension, VS Code 1.30.0-insider. Is it stably reproducible issue?
