### ISSUE TITLE
Sorting report by no defined key

### ISSUE THREAD

**Issue by svwfr** [Microsoft/AL#4173]
The "Phys. Inventory List" (REP722) is not possible to sort by bin.

I want some way to add sorting fields to a report, build in AL, which does not appares in the table key.

I have red through "Creating Keys for Base Application is Essential #730", as you do not support adding Bin Code to the key for table "Item Journal Line (83)". The forum also comment "field mirroring", but find it as horrible workaround.

**Comment by StanislawStempin** [comment]
This is currently not possible until #730 is solved.
