### ISSUE TITLE
Business Chart Colours

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#4174]
**Is your feature request related to a problem? Please describe.**
Creating a Business Chart in "old C/SIDE" automatically showed columns in different colours (red,blue etc).
Creating a Business Chart for BC shows columns in grey, grey & grey.

**Describe the solution you'd like**
Can we have colours in Business Charts again

**Describe alternatives you've considered**

**Additional context**

**Comment by StanislawStempin** [comment]
Is this a difference between C/SIDE and VS Code or between windows client and the web client? 

If the former, can you share AL code with which you create the chart. If the latter, please log your request on http://aka.ms/bsideas and close the issue here.

**Comment by naveksa** [comment]
Actually I can't tell, as the code are different and the clients are different.
However, on the general role center page I notice similar behaviour, so I assume it is the web client.
I will move the request.

**Comment by naveksa** [comment]
Sorry to bother you.
Your link just sends me directly to the Microsoft.com main-page.
Can you give me a hint on where to go from there ?

**Comment by naveksa** [comment]
No problem.
Maybe I could have guessed, if I had reflected deeper on the name of the link
:-)
