### ISSUE TITLE
Folding at the function level

### ISSUE THREAD

**Issue by TonyHemy** [Microsoft/AL#4180]
Would it be possible to get the functions in codeunits to fold at the declaration level?

Currently, it's folding at the declaration and start of the function.

![image](https://user-images.githubusercontent.com/38471593/48235021-e2759880-e370-11e8-95be-3b39727915a6.png)

![image](https://user-images.githubusercontent.com/38471593/48235034-f5886880-e370-11e8-99e1-06b2f866b3d1.png)

**Comment by StanislawStempin** [comment]
This is not supported yet, tracked by https://github.com/Microsoft/AL/issues/416
