### ISSUE TITLE
Can't upload extension to Customer Environment:Unexpected error.

### ISSUE THREAD

**Issue by billyfuTC** [Microsoft/AL#4181]
Hi Experts:
We got the below error message during the installation of extension on our customers' environment.
Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again. - Job Id : ce54eecb-500a-4719-914c-11647bfe0dd3
Unexpected error. There was an unknown error when attempting to deploy the extension. Try to deploy again. - Job Id : 7bbd29c8-a11e-4316-9e7d-e12905876ed4 

Steps and/or AL code to reproduce the behavior:
1. Go to Extension Management
2. Upload Extension.
3. Failed ane got the exception below.

Expected behavior:
Add-on should be installed correctly.
Addon worked on our testing environment.

 - AL Langauge: 2.0.48254
 - Business Central:US Dynamics NAV 13.0 (25251)

Could you please help us to find the problem?

Thanks
Billy

**Comment by StanislawStempin** [comment]
Please contact customer support. We do not support live site issues through this forum.

**Comment by billyfuTC** [comment]
> Please contact customer support. We do not support live site issues through this forum.

Hi Stanislaw:
Thank you for your reply. Could you please show us how to get the customer support?

Thanks
Billy
