### ISSUE TITLE
GETTING ERROR The request for path /Dynamicsnav130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4186]

**Comment by sainath654** [comment]
Below error i am getting When i uninstall the depended extensions and republishing the extension after changes

**The request for path /Dynamicsnav130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension**

But when i see extension management page in the RTC it is not showing any extension with the same Extension name

**Comment by qutreson** [comment]
Hi @sainath654, this looks related to #3571. 

Which version of the AL extension and of the server are you using?
What does the command [Get-NavAppInfo](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps) return you? Can you try unpublishing/uninstalling the extension with the same name with any?

**Comment by mstjernfelt** [comment]
I am getting the exact same thing as @sainath654. I have tried to uninstall and unpublish using powershell. But for this to work I need to uninstall and unpublish all extensions that have Extension A as a dependency.

```
PS >Publish-NAVApp -Path 'C:\C0001-core_1.0.0.0.app' -PackageType Extension -ServerInstance DynamicsNAV130 -SkipVerification
Publish-NAVApp : This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.
At line:1 char:1
+ Publish-NAVApp -Path 'C:\c0001-core ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$DynamicsNAV130/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
```

**Comment by sainath654** [comment]
There was some dependencies in the Extension so i have uninstalled the dependencies extension and tried to publish the extension package

I am using Business Central Spring release

**Comment by qutreson** [comment]
Hi @sainath654, did uninstalling the extensions that were taking an extension on your extension fixed your problem? 
We are tracking this issue about dependencies with #2804.
