### ISSUE TITLE
Cannot use caption property for TestPages

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#4187]
Hey Guys, 
We are having an issue with using caption property of TestPage fields.

Here's the test code:
```
codeunit 51000 TestCaptionProblem
{
    Subtype = Test;

    [Test]
    procedure TestCaption()
    var
        PageOne: TestPage "Company Information";
        Assert: Codeunit Assert;
    begin
        Assert.AreEqual(1, 1, PageOne.Address.CAPTION);
    end;
}

```
publish it
`Publish-NAVApp -ServerInstance BC130 -Path "C:\Users\gps\Documents\AL\ALProject6\Default publisher_ALProject6_1.0.0.0.app" -SkipVerification
`

Sync it
`Sync-NAVApp -Name ALProject6 -ServerInstance BC130`

Error received:
```
Sync-NAVApp : c:\ProgramData\Microsoft\Microsoft Dynamics NAV\130\Server\MicrosoftDynamicsNavServer$BC130\source\Codeun
it\Group3d5509569facd6a7b228b62751bd568fe9a867d725af85cedfb3c43d27c99f91_Codeunit51000.cs(103,165) : error CS1955: Non-
invocable member 'Microsoft.Dynamics.Nav.Runtime.NavTestField.ALCaption' cannot be used like a method.
At line:1 char:1
+ Sync-NAVApp -Name ALProject6 -ServerInstance BC130
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC130/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manag
   ement.Cmdlets.SyncNavApp
```

tried to replace 
`PageOne.Address.CAPTION`
with method call (since it's looks like at method according to the documentation)
`PageOne.Address.caption() `
it did not have any effect. same error message 

 - AL Langauge: 2.0.58805
 - Business Central: 13.0.24623

**Comment by AndreyKorepanov** [comment]
Hi @gintuoklis. Thank you for reporting the issue. 
This is known issue and it has been recently fixed, you can try it with the latest daily build. It worth to note, that currently we support both property syntax and method call syntax for test field captions, so you can use either PageOne.Address.caption() or PageOne.Address.caption. However, if you get the code analysis enabled ("al.enableCodeAnalysis": true) you can see the AL warning for the property syntax: "You must specify open and close parenthesis after 'Caption'". Nothing to do with this warning, you still can use it as property.
