### ISSUE TITLE
XMLCdata function usage issue

### ISSUE THREAD

**Issue by ManishNavAspirant** [Microsoft/AL#4188]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by ManishNavAspirant** [comment]
Hello Friends,

Would like your suggestion on the below issue about a web service.
I was upgrading my NAV 2016 CAL code to AL for Web service Integration which include Cdata section.
In Nav 2016 , I achieved Cdata with AppendChild and CreateCdataSection function but in AL I can't see such functions.

I have created successfully created XML file in AL from the following reference.

https://community.dynamics.com/nav/b/diveshboramsdnavblog/archive/2018/03/05/vs-code-xml-dom-management-part-1
https://community.dynamics.com/nav/b/diveshboramsdnavblog/archive/2018/03/09/vs-code-xml-dom-management-part-2
community.dynamics.com/.../creating-soap-request-message-in-al

But I am stuck in inserting Cdata section.

I also tried XMLCdata Functions available in Business Central but error occured -->
The requested operation cannot be performed in this context.

Below is the codeunit and Page I created for genrating XML File.

Codeunit -->
codeunit 50104 WebSrv
{
    TableNo = 50104;
    trigger OnRun()
    var
        myInt: Integer;
        XMLReq: XmlDocument;
        XMLRes: XmlDocument;
    begin
        Url := 'https://moultonordervision.com/ws/OrderStatusWebService.asmx';

    end;

    procedure CreateSoapMessage();
    var
        lXmlDocument: XmlDocument;
        lEnvolopeXmlNode: XmlNode;
        lHeaderXmlNode: XmlNode;
        lBodyXmlNode: XmlNode;
        lXMLText: Text;
        OrdNo: code[8];

    begin
        CreateEnvelope(lXmlDocument, lEnvolopeXmlNode);
        CreateHeader(lEnvolopeXmlNode, lHeaderXmlNode);
        OrdNo := '043487';
        CreateBody(lEnvolopeXmlNode, lBodyXmlNode, OrdNo);

        lXmlDocument.WriteTo(lXMLText);
        Message(lXMLText);
    end;

    procedure CreateEnvelope(var pXmlDocument: XmlDocument; var pEnvelopeXmlNode: XmlNode);
    begin
        pXmlDocument := XmlDocument.Create();

        With XMLDomMgt do begin
            AddDeclaration(pXmlDocument, '1.0', 'UTF-8', 'Yes');
            AddRootElementWithPrefix(pXmlDocument, 'Envelope', 'soapenv', SOAPNamespaceLbl, pEnvelopeXmlNode);
            AddPrefix(pEnvelopeXmlNode, 'ord', XSDNamespaceLbl);
        end;
    end;

    procedure CreateHeader(var pEnvelopeXmlNode: XmlNode; var pHeaderXmlNode: XmlNode);
    begin
        XMLDOMMgt.AddElement(pEnvelopeXmlNode, 'Header', 'soapenv', SOAPNamespaceLbl, pHeaderXmlNode);
    end;

    procedure CreateBody(var pSoapEnvelope: XmlNode; var pSoapBody: XmlNode; var pOrderNo: code[8]);
    begin
        Clear(StrxmlNodeValue);
        XMLDOMMgt.AddElement(pSoapEnvelope, 'Body', 'soapenv', SOAPNamespaceLbl, pSoapBody);
        XMLDOMMgt.AddElement(pSoapBody, 'OrderStatus', 'ord', XSDNamespaceLbl, OrdStatusNode);
        StrxmlNodeValue := '<dataQuery><username>' + 'XXX' + '</username><password>' +
                           'XXXXX' + '</password><group_code>' + 'TEST' +
                           '</group_code><order_no>' + pOrderNo + '</order_no></dataQuery>';

        xmlcd := XmlCData.Create(StrxmlNodeValue);
        strXMLNode := xmlcd.AsXmlNode();
        xmlcd := strXMLNode.AsXmlCData();

        XMLDOMMgt.AddElement(OrdStatusNode, 'strXml', 'ord', XSDNamespaceLbl, strXMLNode);
        xmlcd.AddAfterSelf(strXMLNode);
    end;

    var
        XMLDomMgt: Codeunit "XML DOM Mgt.";
        URL: Text;
        myInt: Integer;
        SOAPNamespaceLbl: Label 'http://schemas.xmlsoap.org/soap/envelope/';
        XSDNamespaceLbl: Label 'https://moultonordervision.com/Ws/OrderStatusWebService.asmx';
        ContentTypeLbl: Label 'multipart/form-data; charset=utf-8';
        StrxmlNodeValue: Text;
        OrdStatusNode: XmlNode;
        strXMLNode: XmlNode;
        xmlcd: XmlCData;
}

Page -->
page 50100 "Soap Test Page"
{
    PageType = Card;
    Caption = 'Soap Test Page';
    actions
    {
        area(processing)
        {
            action("Create Soap Message")
            {
                Caption = 'Create Soap Message';
                ApplicationArea = All;
                Image = XMLFile;
                trigger OnAction()
                var
                    
                    WebSrv: Codeunit WebSrv;
                begin
                    
                    WebSrv.CreateSoapMessage();
                end;
            }
        }
    }
}

I am trying to generate below XML File with Cdata Section in Business Central.

<soapenv:Envelope xmlns:ord="https://moultonordervision.com/Ws/OrderStatusWebService.asmx" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
  <soapenv:Body>
    <ord:OrderStatus>
      <ord:strXml><![CDATA[<dataQuery><username>XXX</username><password>XXXXX</password><group_code>TEST</group_code><order_no>03027515</order_no></dataQuery>]]></ord:strXml>
    </ord:OrderStatus>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
