### ISSUE TITLE
ChartPart

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#419]
Is it possible to create a page with a ChartPart in the V2 Extension model?  If so, what is the syntax?

I have converted a RoleCenter page with a ChartPart and it gives me this set of errors.
```
        part(Part1190000006)
        {
          ChartPartID='T60027-001';
          UpdatePropagation=Both;
        }
```

> file: '../Page 60071 - HR.RoleCenter.al'
> severity: 'Error'
> message: 'The Page '' is not found'
> at: '28,28'
> source: 'AL'

> file: '../Page 60071 - HR.RoleCenter.al'
> severity: 'Error'
> message: 'Syntax error, ';' expected'
> at: '28,28'
> source: 'AL'

> file: '../Page 60071 - HR.RoleCenter.al'
> severity: 'Error'
> message: 'Syntax error, identifier expected'
> at: '28,28'
> source: 'AL'

> file: '../Page 60071 - HR.RoleCenter.al'
> severity: 'Error'
> message: 'The property 'ChartPartID' cannot be used in this context'
> at: '30,11'
> source: 'AL'

**Comment by atoader** [comment]
To add a chart you need to write something like this:
```
page 10 MyPage
{
    layout
    {
        area(content)
        {
            part(NameOfPart;NameOrIdOfPageOrSystemOrChartPart)
            {
                PartType=Chart;
            }
        }
    }
}

```

**Comment by GreatScott000** [comment]
In addition to the same type of errors I get this message related to PartType
        part(SomeChartPart;'T60027-001')
        {
          PartType=Chart;
        }

> file: '../Page%2060071%20-%20People.RoleCenter.al'
> severity: 'Error'
> message: 'The property 'PartType' cannot be used in this context'
> at: '31,11'
> source: 'AL'

**Comment by atoader** [comment]
Sorry! I misread a test when giving you the snippet. It seems that charts are not supported at the moment. System and page parts are supported and the syntax is:
```
part (MyPagePart; SalesLinePart){}  
systempart(MySystemPart; Links) {}    
```

**Comment by GreatScott000** [comment]
I assume this is on the development list then?

**Comment by esbenk** [comment]
It is on the list. 

The problem with existing Chart implementation is that it is half metadata (the page pointing to a chart by name) and half data (the actual chart being stored in the database under the same name). 

We still considering if we can provide a better developer story for this, or we just have to stick to the current implementation for now.
