### ISSUE TITLE
Control visibility of Chart Part in Page Extensions

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/AL#4191]
Problem description:  I created a Page Extension for the Purchase Order page (page 50) and set the visbility status on all Factbox Controls to false in an attempt to hide the Factbox area by default.

The issue I am faced with is the fact that there is an Inventory Forecast Chart displayed on the Purchase Order in the Chart Part factbox as a default and I am not able to remove/hide this, see below:

![image](https://user-images.githubusercontent.com/44084862/48413682-21309780-e751-11e8-8434-5b553ef3e74a.png)

I would like to be able to set the default visibility of the Chart Part from a Page Extension.

Kind Regards,
Wiechardt

**Comment by qutreson** [comment]
Hi @Wiechardt, are you are able to reproduce this issue on the latest developer preview (version 15.x)?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
