### ISSUE TITLE
CardPageId in Page Extensions

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#4196]
Summary: 
We want to add a a Card Page for a standard List Page that has no Card Page assigned, but that's currently not possible. Being able to set the CardPageId property would be a possible solution.

Context:
We are currently migrating a Customer to BC and, one of the customisations we are migrating, consists on adding several fields to a basic standard setup table. The standard table is so basic, in fact, that there is only a page list for it. In NAV, we had created a Card Page for the list, and linked it through the CardPageId property, because editing all the fields in the list page would be quite cumbersome.

Currently, however, there is no way to set the CardPageId in a table extension and thus, the only way to open the card page and edit the record is by using a menu action hidden in a dropdown, which is quite counterintuitive (more so, because the list is editable and there is no way to discover that there are more fields available).

**Comment by StanislawStempin** [comment]
Modifying of this property is currently not possible. We will consider it as an enhancement

**Comment by kevindstanley1988** [comment]
When these are marked as 'enhancement' is there any roadmap for release in a cumulative update? In our solution we also very much need this feature as there are list pages that don't have cards. We enhance those tables with fields and cards make it easier to work with the setup for a user.

**Comment by atoader** [comment]
@kevindstanley1988 enhancements will be released in major releases. We continuously evaluate the enhancements and suggestions received on GitHub, and the requests received on BC Ideas and we try to fit the most valuable features in the plan for the next release.

**Comment by fvet** [comment]
Hope to see this in the next major release...
Please vote on https://experience.dynamics.com/ideas/idea/?ideaid=db0e5a74-25c0-e911-b083-0003ff68d32d

**Comment by dtkb** [comment]
I've opened a request on `AlAppExtensions` for a system event from each `page` that could enable us to do this, and do it better than a `pageextension` property would allow, by enabling the resulting `CardPageId` to be dependent on fields in the record.

If anyone also thinks that would be a good idea, upvotes/affirmations could be useful!

https://github.com/microsoft/ALAppExtensions/issues/10747

**Comment by dtkb** [comment]
...which has now been moved to this repo as https://github.com/microsoft/AL/issues/6440

**Comment by atoader** [comment]
I will close this issue. Please upvote the BCIdea linked above.
