### ISSUE TITLE
Error starting with AL

### ISSUE THREAD

**Issue by AlPacino1205** [Microsoft/AL#4199]
Hi Guys
I am trying to learn AL and I am reading the : 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started

I have installed Visual Studio Code and created my Dynamics 365 Business Central sandbox.
After Installing the AL Language Extension ( 2.0.48254 ), I tried Downloading Symbols but it resulted into an error:

"The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code Forbidden. Reason: You do not have the following rights to TableData NAV App: IndirectRead"

and I also got this error : 
Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

My launch.json looks like : 
 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "startupObjectId": 22,
            "breakOnError": true,
            "breakOnRecordWrite": false
        },
       
    ]
 and my app.json loks like : 
{
  "id": "f33d411b-4675-423b-a625-3f977797bd65",
  "name": "MYExtension",
  "publisher": "Microsoft cloud sandbox",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  },
  "runtime": "2.0"
}

Can you please tell me where and what I am doing wrong ?
Thanks

**Comment by qutreson** [comment]
This looks similar to #2721. 
Can you try connecting once to the sandbox from the browser before downloading the symbols?

**Comment by AlPacino1205** [comment]
Hi , 
Thank you very much . It helped and when I reset my sandbox and tried again ,it was working, but now I am being prompted every time to enter the username and password, even after I entered it.

**Comment by StanislawStempin** [comment]
To get further help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
