### ISSUE TITLE
Some type or method cannot be used for Extension development

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#420]
Hi!

I developing my extension package.
I need some native method which can be used for extension.
- GetSelectionFilter of Page 18 G/L Account List; Page 31 Item List; Page 855 Cash Flow Account List; Page 22 Customer List; Page 27 Vendor List
- HandleEvent, CanExecuteWorkflow of Codeunit 1501 Workflow Management. (I need implement more workflow for Item Journal).
- ApproveRecordApprovalRequest, TrySendJournalBatchApprovalRequest, TrySendJournalLineApprovalRequests of Codeunit 1535 Approvals Mgmt.
- SetFilterOnWorkflowRecord of Page 1528 Workflow Status FactBox.
- GetSelectionFilter of Page 560 Dimension Value List
- LookupCostCenterFilter of Table 1112 Cost Center
- LookupCostObjectFilter of Table 1113 Cost Object
- LookupCashFlowFilter of Table 840 CashFlowForecast
- LookupCostBudgetFilter of table 85 Acc. Schedule Line
- OpenFileDialog, ClientFileExists, UploadFileSilent of Codeunit 419 File Management
- SelectSheetsName, OpenBook, ReadSheet of Table 370 Excel Buffer

I also need implement workflow for FA jounal, please add more event to support this task.

**Comment by atoader** [comment]
I have forwarded this to the appropriate teams. Thank you for the feedback!

**Comment by hgnamvn** [comment]
Thank Atoader!

**Comment by hgnamvn** [comment]
I add more method, please:
TrySendJournalLineApprovalRequests of Codeunit 1535 Approvals Mgmt.
