### ISSUE TITLE
Dot net variable with Business Central OnPrem issue

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#4200]
Hi All,

I'm using dot net variable in Business central onprem

This code works perfectly well in NAV 2018 but in D365 BC below error is thrown.

The code line is 

Window.UPDATE(3, FORMAT(ProdDetails.sku())); 
//here ProdDetails is a Dotnet variable and sku is a Dot net System.String variable.

![inkedissue_li](https://user-images.githubusercontent.com/24870777/48482756-91194d80-e837-11e8-9b56-93b050d531ac.jpg)

**Comment by atoader** [comment]
Does this repro when using the latest docker image? I have fixed something similar a long time ago. Have you applied the latest CU? If this still repros, please provide code to reproduce.

**Comment by StanislawStempin** [comment]
Closing due to no repro and lack of additional input.
