### ISSUE TITLE
Rename Key Words in Base Application

### ISSUE THREAD

**Issue by SKeiler** [Microsoft/AL#4202]
Hello, I'm not sure, if this are the right place for my problem/my suggestions. If not, please tell me, where it would be placed better. My problem is that we have to change a NAV Keyword in caption of the whole base application. A lot of our customers are placed in the food industry. And in the food industry, items have recipes, not Production BOMs (that's the language of manufactoring industry). The existing functionality meets the requirements of both industry sectors (okay, not exactly 100%, but nearly). So we have to switch every use of Production BOM to Recipe in the captions for usability reasons (hard to explain a customer that their food has a production BOM, especially in german the words have a very different context). 

We would like to use a extension for this. To rename field captions and page captions should be possible with extensions. But how can we change the captions of text constants etc.? Or do you know a better alternative for us?

It would be great, when there would be a dictonary to manage this texts outside the development environment (because why have a developer to assign the correct captions). In this case, captions could also be customized individually in every project.

**Comment by StanislawStempin** [comment]
Please look at https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translation-and-localization-apps

This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
