### ISSUE TITLE
RDLC Report shows blank 

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#4206]
Hi,

Issue facing is that sometimes RDLC report shows blank pages which was working fine earlier and no change in code and formats.

To resolve this issue I copy .RDLC file and publish the app again and it works fine.

Not sure whether it is bug or complier issue

AL version 2.0.48254

**Comment by CanuckNav74** [comment]
not sure if this applies to you but this is the issue I had (blank word layout):

https://github.com/Microsoft/AL/issues/4204

The way layout paths are handled in AL is really weird

**Comment by StanislawStempin** [comment]
We'd need more information to be able to help you. What do you mean by "I copy .RDLC file"? Copy it from where to where?

**Comment by StanislawStempin** [comment]
Closing due to not enough information. Note that RDLC layouts will stop working if any of the elements of the dataset have been renamed and no longer match the layout.
