### ISSUE TITLE
Publish timeout setting

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#4209]
When publishing our library app to a (local) sandbox from VScode (Ctrl+F5), the process will occasionally time out efter 2 minutes of synchronization. The app is successfully published and installed, but there will be a timeout error in VScode.

**I suggest a new setting for overriding the 2 minute timeout.**

This for a large app with 800 objects, synchronization seems to take longer after we added multiple translations (17,000 trans-units each).

**Comment by AskeHolst** [comment]
AL 2.0.43900, but compilation is not a problem, that takes 12-13 seconds. It is the upload of the app to the container and the synchronization that takes a long time. Sometime just under 2 minutes, sometimes more (the server is a Azure VM Standard DS12 v2 (4 vcpus, 28 GB memory). 
So if we could just extend the timeout to 2:30 it would be ok.

Thus the request for a setting to extend/override the standard 2 minute timeout for scenarios of a big app/slow server/limited upload rate.

**Comment by StanislawStempin** [comment]
The publishing and sync performance has also been substantially improved so I would still recommend to try it on the latest bcsandbox-master image.

**Comment by atoader** [comment]
@AskeHolst we have improved the performance of publish, sync, and install and we are routinely publishing the base application which has more than 6K objects without any issues. I will close this as it seems to have been resolved. If you are still encountering issues, please reopen this.
