### ISSUE TITLE
Error while downloading Symbols

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#421]
Hi,

While downloading Symbols getting below errors. How to resolve this?
![image](https://user-images.githubusercontent.com/30457269/28660639-ffcdf45e-72dd-11e7-9f78-5426c6be6568.png)

**Comment by dennisfrostlander** [comment]
If this is an azure gallery image from July Update, you need to change "locale" property in app.json to W1. See #367

**Comment by sanjeevasawale** [comment]
Thanks. Issue resolved.
