### ISSUE TITLE
[Aggregated Assisted Setup] OnUpdateAssistedSetupStatus Doesn't show right Assisted Setup Page ID

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/AL#4210]
Hi,

I've made an Assisted Setup for an extension. When my wizard is finished, the **OnUpdateAssistedSetupStatus** event is fired. 
In the procedure I just show the **Assisted Setup Page ID** value in a message

This message only shows the page 6711 (set up reporting data wizard) which is the row selected just after my wizard closes.

![image](https://user-images.githubusercontent.com/29598240/48558684-2d039180-e8ea-11e8-810c-c8de88f230d4.png)

![image](https://user-images.githubusercontent.com/29598240/48558452-9cc54c80-e8e9-11e8-9612-ea06f610c63f.png)

So when I modify the status, the wrong record is modified ..!

![image](https://user-images.githubusercontent.com/29598240/48558616-047b9780-e8ea-11e8-89f3-ec30087fa94c.png)

Al Language 2.0.48254

**Comment by JulienDecottignies** [comment]
It's ok I think I just understood the bad way how to use this event. 

So for my I thought I had to use the TempAggregatedAssistedSetup passed by reference to just update it.
But it looks like if I Get first the Assisted Setup I Inserted before, just calling AggregatedAssistedSetup.SetStatus(...) updates the correct row as the record contains the updated value (or at least, the last I gave to it).

![image](https://user-images.githubusercontent.com/29598240/49021311-a4f77480-f192-11e8-849e-f5516e61a0d6.png)

So I think this way is the good way (tell me if it's not) but I'm still asking myself: Why BC gives me an Aggregated Assisted Setup by "default" that isn't the one I'm leaving ..?

**Comment by atoader** [comment]
Hi @JulienDecottignies ! It seems you have found a solution. For questions on the design of this and why it works the way it does please use one of the following resources:
[AL App Extensions GitHub ](https://github.com/Microsoft/ALAppExtensions)
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

I will close this issue.
