### ISSUE TITLE
Get value of enum

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#4213]
I would like to be able to get the value of an enum. Currently, I only can get the corresponding number or the caption, but not the value itself.

Imagine I do have an enum like this:

enum 50000 "Customer Level"
{
    value(0; NONE) { Caption = ''; }
    value(1; BRONZE) { Caption = 'Bronze level'; }
    value(2; SILVER) { Caption = 'Silver level'; }
    value(3; GOLD) { Caption = 'Gold level'; }
}

And now I have a field of type enum "Customer Level" with value SILVER. How can I get that value out of the field into a text variable? If I do Format(MyEnumField) I get the caption 'Silver level'. There is no way to get the programmatic value 'SILVER'.

**Comment by rvanbekkum** [comment]
For what purpose do you want to be able to do this? Not saying there might not be a good reason for it, but I was wondering what you are trying to achieve. :wink: 
Sidenote, if I recall correctly, using the Format function with an Option variable results in the same behaviour.

As I see it, the names are just aliases/identifiers for the valid options for the enum type.
However, it's too bad that there isn't any way to retrieve the numeric values, which makes the enum type only useful for usage within extensions 'internally'. See also #3567 with some other suggestions for improvements on this. 

So more generally, I think it would be nice to have some built-in functions that can be used with the enum type. As I understood from the replies to #3567, there are 'some' plans to have this improved in a future version. Hope to hear whether there is any update on this. :smiley:.

**Comment by JavierFuentes** [comment]
@ajkauffmann , I've added [some proposals for Enums](https://github.com/Microsoft/AL/issues/3567#issuecomment-441386698) at #3567

**Comment by JavierFuentes** [comment]
Maybe, 
but what about to get the Captions or to be able to iterate using FOR and FOREACH?

You can see [my proposal here](https://github.com/Microsoft/AL/issues/3567#issuecomment-441386698)...

Many work to do with Enums yet I think...
