### ISSUE TITLE
Event Reuqest on Codeunit 99000773 

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#4214]
Hi
Need to have one event to modify prod order components when it is transfer from BOM
Though We have event for insert the customer values but not for modify. 

![image](https://user-images.githubusercontent.com/17919257/48598531-e1a6bd00-e995-11e8-9e44-b6a71a1b4497.png)

Regards
Amol

**Comment by dNsl9r** [comment]
Wrong Repo and wrong Issue tracker - you should post it here: https://github.com/Microsoft/ALAppExtensions/issues

**Comment by AmolSalvi** [comment]
Thank you I will post there

**Comment by AmolSalvi** [comment]
Posted Here
https://github.com/Microsoft/ALAppExtensions/issues/375

**Comment by AmolSalvi** [comment]
Posted in right place.
