### ISSUE TITLE
How to display media type field

### ISSUE THREAD

**Issue by wingsrutherford** [Microsoft/AL#4215]
I want to display a media type field on a card page, I tried the usual way but the field did not appear.
I can see there is a media id in the db column, but I have no idea how to link it to the actual image.

Please help, thanks in advance!

**Book.al**
field(6; "Book Cover Picture"; Media)
{
    Caption = 'Book Cover Picture';
}

**BookCard.al**
field("Book Cover Picture"; "Book Cover Picture")
{
    ApplicationArea = All;
}

**Comment by AmolSalvi** [comment]
Check standard pages like customer card .You will get an idea.

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
