### ISSUE TITLE
Missing page control field metadata

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/AL#4218]
As we see there are many tables to describe objects metadata. We have found almost everything what we need, but there are some field properties what are still missing.

For example, we would like to use decimal places metadata in our solution.

Please add a new field "Decimal Places" to virtual table 2000000192 (Page Control Field)

The value should be inherited from the source table if it is not defined on the page.

Maybe you should add some other properties e.g. MinValue, MaxValue, NotBlank, BlankZero, ...

**Comment by blrobl** [comment]
Hi, thank you for your suggestion! We are not prioritizing this for the immediate future, but we recommend you submit this at aka.ms/BCIdeas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
