### ISSUE TITLE
AL type HttpRequestMessage does not works with credentials

### ISSUE THREAD

**Issue by HegedusZsolt** [Microsoft/AL#4219]
We would like to call web services what are using NTLM authentication, but as we see, the built-in AL type can use basic authentication only.

We have found a codeunit 1297, where we can use this, but there are some functions what are not enabled at Extension side. We have requested to open those methods, but our request had refused.

The reason was, we should use the built-in AL type instead. :) But we can't, because there are no credentials.

So, please extend the built-in HTTP wrapper with credentials or open the following methods for extensions.

Codeunit 1297:
- GetResponseStream
- Initialize
- SetTimeout
- SetMethod
- SetContentType
- SetReturnType
- AddHeader
- AddBodyAsText
- AddBodyBlob
- ProcessFaultXMLResponse

**Comment by StanislawStempin** [comment]
We plan to enhance the http types in AL to support NTLM authentication. See #550.
For a request to add base app functions/wrappers you'd need to go to ALAppExtensions GitHub repo.
