### ISSUE TITLE
MyAddon requires Menu-Option in Administration Menu

### ISSUE THREAD

**Issue by BobFaber** [Microsoft/AL#4222]
I created a new Add-on (MyAddon) for Dynamics NAV 365 BC. This add-on needs a Setup-record, and a Setup-page.

Imho, this should require adding an option to the Administration Setup menu, showing 'MyAddon' (in blue). Clicking on it, it should at least show the option to open the page with the settings of 'MyAddon'.

How about adding to menus (menu suites) in Visual Code for AL?

**Comment by RianeAziz** [comment]
Hello,

I think you have to specify in the pages that can be linked in Departement the following properties:
- **ApplicationArea** = **All**; _(or Basics, Suite, ...)_
- **UsageCategory** = **Lists**; _(or Tasks, History, Archives, ...)_

Good luck.

**Comment by BobFaber** [comment]
Thanks for your reply.
I added both proporties to my setup page. 
![image](https://user-images.githubusercontent.com/45129950/48666284-f763d180-eabe-11e8-8e94-a5bad3d4ab26.png)
I recreated the package. No result at all. 
My page is also not recognized in the search bar.

**Comment by rvanbekkum** [comment]
You mean in the Windows client?

There is no way to change menusuites from extensions. The only thing that you'll get in the Windows client is a new (automatically generated) department for your extension (Departments | MyAddon) that will include all pages that have a UsageCategory.

**Comment by RianeAziz** [comment]
It's just Rob van BEKKUM,

I will also add a precision; if you use the web client, it is possible to find your pages and your reports in the search box using the name you gave to the object:
![image](https://user-images.githubusercontent.com/44979247/48673450-d6909000-eb41-11e8-8aa9-3122c79b64b0.png)


In the Windows client...

**Comment by RianeAziz** [comment]
In the Windows client:
![image](https://user-images.githubusercontent.com/44979247/48673602-5408d000-eb43-11e8-8c33-d53cb60302e4.png)
Here is.

**Comment by rvanbekkum** [comment]
Yes, exactly, that's what I said. You'll automatically get a new Department in the Windows client for your extension , and in the Web client you'll be able to find the pages/reports using search instead. That is, if the UsageCategory is set, otherwise they won't show up in either.

**Comment by StanislawStempin** [comment]
Here's the documentation for how to enable pages/reports showing up in search in AL:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-menusuite-functionality

Menusuites are not supported in AL.
