### ISSUE TITLE
Numbering of single-use objects outside of the customer's license range to perform data correction tasks and similar cases

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4223]
In Navision 2009 with Classic Client it is possible to change the License of the Customer for the one of the Partner to be able to create objects of a single use that allow us to execute processes of massive correction of data...

I can not find a way to do it in Business Central OnPremise under the Web Browser, so I wonder how we have to do that kind of maintenance tasks with Extensions now?

If it can be done, I would need directions on how to proceed ...

If it can not be done, I would need indications of how this typical OnPremise maintenance case is covered.

There is some numbering, type or subtype or any special object, not errors when executing it with the final Customer's license and that allows to design this type of processes, usually of a single execution, to test them in the QA environments and to promote them to the PROD environments to execute them from any IT administration console?

**Comment by StanislawStempin** [comment]
I am not aware that this is still possible but please reach out to support since this is outside of the scope of AL compiler/feature suggestions.

**Comment by JavierFuentes** [comment]
Hi @StanislawStempin , 
can you put here de URL where can I ask this?

Thanks in advance.
