### ISSUE TITLE
Using Caption with TableExtensions produces ERROR in Publishing time and not in Compiling time

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4227]
**Description**
If you need to use Captions because activate `"mandatoryPrefix"` in `AppSourceCop.json` and set a __Caption in a TableExtension__, compiler doesn't throw errors, but in Publishing Time an Error throws and can't upload your changes to server.

I have activated `"features": ["TranslationFile"]` in `app.json` too. 

**Expected behavior**
Compiler should throw an Error when compiling at development time.

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/48678008-a36bf200-eb7d-11e8-95b3-470c762b9345.png)

**Versions:**
 - AL Language:  __2.0.48254__
 - Business Central: __ES Dynamics NAV 13.0 (24630) OnPremise__

**Comment by kwettermann** [comment]
Can confirm this on Insider build. Caption in TableExtension breaks on Publish without error details.

**Versions**:

- AL Language: **2.0.58805**
- Business Central: **14.0.25906.0-W1**

**Comment by qutreson** [comment]
HI @JavierFuentes  and @kwettermann, thank you for reporting this issue, I can reproduce it when defining:

``` 
tableextension 50125 MyExtension extends Customer
{
    Caption = 'New caption';
}
```
