### ISSUE TITLE
Compiler Error 'Unexpected value 'BadStatement' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind''

### ISSUE THREAD

**Issue by robertabel** [Microsoft/AL#423]
Getting a compiler error:

   Processing of message 'al/createPackage' failed with error: 'Unexpected value 'BadStatement' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind''

The full compiler output is attached:

[compileroutput.txt](https://github.com/Microsoft/AL/files/1180908/compileroutput.txt)

Is there any resolution for this?

**Comment by atoader** [comment]
Hi! This looks like another bug. Could you please provide a snippet to repro? The error log you've attached contains a consequence of the bug but no details to what is actually causing it.

**Comment by robertabel** [comment]
Hi Alexandru,

Unfortunately, I cannot tell what file it is on from the stack trace and there are 60 files in the project. How could I identify the snippet?

Robert

**Comment by atoader** [comment]
I took a better look at the log and you are using an old version of the compiler. We've picked up this bug a few months ago and I added more diagnostic information. Make sure you are using the latest Dev Preview and try to recompile. If the error still happens, we should at least get more information from the stacktrace.

**Comment by robertabel** [comment]
Thank you, I'll get the latest Dev Preview.
