### ISSUE TITLE
New Database Creation, Download the platform symbols, the test symbols, and the application symbols.

### ISSUE THREAD

**Issue by muratvezir** [Microsoft/AL#4233]
I want to try create new empty Nav 2018 Database 
But I dont have Microsoft_Application_11.0.23572.0.app
This Link provide https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-databases
Microsoft_Application_11.0.19738.0.app but I cant find 23572 app. 
I have system and test app in Modern Dev folder.

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools on the latest developer preview release.

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
