### ISSUE TITLE
How to upload a font file for a check report requires MICR font?

### ISSUE THREAD

**Issue by jeffgit** [Microsoft/AL#4237]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by StanislawStempin** [comment]
Closing since you answered already:)
