### ISSUE TITLE
Request more events

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#424]
Hi!

I developing my extension package.
I need more some events to implement. So please add more some events for these methods:
1. Table 81 _Gen. Journal Line_: **CopyCustLedgEntry** . To apply, unapply post entries
2. Table 5601 _FA Ledger Entry_: **MoveToGenJnl**, **MoveToFAJnl** . To cancel FA Ledger Entries, copy Depreciation Books.
3. Codeunit 13 _Gen. Jnl.-Post Batch_: **PostAllocations** . To post data With Allocation data on Recurring Journal page.
4. Codeunit 80 _Sales-Post_: **InsertICGenJnlLine** . To post data for InterCompany.
5. Codeunit 227 _VendEntry-Apply Posted Entries_ : **VendPostApplyVendLedgEntry**, **PostUnApplyVendor** . To apply, unapply posted entries.
6. Codeunit 1521 _Workflow Response Handling_: **AllowRecordUsage** . To allow record usage for another journal batch: **Item journal Batch**, FA journal batch.
7. Codeunit 5604 _Make FA Ledger Entry_ : **CopyFromFAJnlLine**, **CopyFromGenJnlLine** . To assign data for FA Ledger Entry.
8. Codeunit 5647 _Make Maintenance Ledger Entry_ : **CopyFromFAJnlLine**, **CopyFromGenJnlLine** . To assign data for Maintenance Ledger Entry.

Thank so much!

**Comment by atoader** [comment]
Thank you! I've forwarded the request. Keep the feedback coming! :)

**Comment by hgnamvn** [comment]
Thank Atoader !

**Comment by johndcollins** [comment]
1. Codeunit 5704 TransferOrder-Post Shipment: **PostItemJnlLine**
2. Codeunit 5705 TransferOrder-Post Receipt: **PostItemJnlLine**
3. Table 5744 Transfer Shipment Header: CopyFromTransferHeader
4. Table 5746 Transfer Receipt Header: CopyFromTransferHeader
5. Table 5745 Transfer Shipment Line: CopyFromTransferLine
6. Table 5745 Transfer Receipt Line: CopyFromTransferLine
7. Codeunit 5750 Whse.-Create Source Document: For all the functions where data is transferred.
8. Codeunit 5802 Inventory Posting To G/L: SetAccNo Need to be able to transfer fields to the InvPostBuf variable. PostInvtPostBuf Need to be able to transfer fields back from the InvPostBuf to the GenJnlLine.

**Comment by hgnamvn** [comment]
Hi!
I have some request:
**_1._** Please add more some events for these methods:
   - Codeunit 5895 _Inventory Adjustment_ : **PostItemJnlLine**
   - Codeunit 7310 _Whse. Jnl.-Register Line_ : **InitWhseEntry** 
   - Codeunit 7302 _WMS Management_ : **CreateWhseJnlLine**

**_2._** Please implement more workflows for FA Journal, Item Journal as General Journal have done.

**_3._** For Codeunit 408 _DimensionManagement_ - Method **CheckDimValue**, Current the system 
only allow to post Dimension with Type=Standard|Begin-Total. But there are some our customers request that user only allow to post Dimension with Type=Standard. Please support us an option to do it.

**_4._** On **Customer Card** page have a Customer Picture Factbox, Please support us a function to import pictures for multi Customer at the moment. And please also do that for Vendor, Item, FA, Contact 
![image](https://user-images.githubusercontent.com/24407031/31069281-fe0337b0-a785-11e7-9979-edc57373790f.png)
I have implemented a report on-premise. I also try do it with AL language, but AL still don't support IMPORTFILE method of Media DataType, some methods of File DataType, DeleteServerFile method of Codeunit FileManagement.

**_5._** For Codeunit 5601 _FA Insert G/L Account_ - Method **GetBalAcc**, please support us a method to assign data for general journal line from original general journal line as the system did for Description field.
![image](https://user-images.githubusercontent.com/24407031/31069518-10a818d0-a787-11e7-935a-2dad10286d38.png)


6

**Comment by StanislawStempin** [comment]
@hgnamvn - could you please log a new issue for your follow up request? We were originally tracking only the first request and the the first comment from johndcollins.

Also, could you please open a separate issue for different issue types (i.e. event requests vs exposing functions as External)

**Comment by hgnamvn** [comment]
Sorry StanislawStempin for reply late, because i have some private's problems.

So now, Do I need log new issue for this request because I see that **AlexanderYakunin** tagged **_accepted ships-in-future-update_** label and **you** tagged **_November Update_** label

**Comment by StanislawStempin** [comment]
The issues from this comment have not been addressed:
https://github.com/Microsoft/AL/issues/424#issuecomment-333474415

I would suggest that you log 4 new issues:
1.  For event requests mentioned in points 1.-3.
2. For new functionality request in point 4.
3. For new functionality request in point 5.
4. For exposing a system table in point 6.

**Comment by hgnamvn** [comment]
OK! Thank StanislawStempin so much!!!

**Comment by hgnamvn** [comment]
Hi StanislawStempin,

My requests aren't still updated on "November Update" (W1 11.0 (19097)). Please check again and reopen this thread for me (I can't reopen be myself).

**Comment by StanislawStempin** [comment]
As I mentioned in my comment above, please log separate issues per request. This thread was only tracking your original request. Please see 
https://github.com/Microsoft/AL/issues/424#issuecomment-334691634

**Comment by hgnamvn** [comment]
OK, thank StanislawStempin.
I will log new requests.
