### ISSUE TITLE
Extension is not published and no error shown on output log

### ISSUE THREAD

**Issue by rishiaurrishabh** [microsoft/AL#4240]
I am using Business central On prem, when I am trying to publish an extension then Visual Studio code says that extension cannot be published on a message and gives me option to open launch.json.
But when I go to output log then I don't see any error there, although when I go to Extension Management page of business central then I see the extension is publish and if I try to Install the extension from there it then gives me a proper error that I am trying to deploy an object which is already deployed by another extension.

I believe, similar message should be available on Visual Studio code as well.

**Comment by AKhileshTiwari91** [comment]
Hi Rishabh,

Try also deploying with F6 instead of F5 from VS Code. F6 will provide detailed error.

**Comment by rishiaurrishabh** [comment]
Hi Akhilesh ,

still same result, normally it should show the same message.

**Comment by StanislawStempin** [comment]
This is a bug in VSCode version 1.29.x https://github.com/Microsoft/vscode/issues/61986

You can downgrade to VSCode 1.28 or see the workaround in the referenced bug. VSCode team doesn't know yet if they will fix it in 1.29.2 or if we'll need to wait until 1.30

**Comment by sainath654** [comment]
Hi All,

@StanislawStempin  as you suggested i have downgraded the VS Code editor to 1.27.2 and its working.

Thanks.

**Comment by rishiaurrishabh** [comment]
Hi @StanislawStempin with Visual Studio 1.30 my issue got fixed, i can now see a proper error message.

Thanks for you help :)

**Comment by pborring** [comment]
Closing as this seems to have been solved
