### ISSUE TITLE
ListPart in NavigatePage does not show all entries

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#4241]
**Describe the bug**
When a ListPart is not in the first page of a NavigatePage, it only shows some of the entries from the list. 

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Install the test project
2. Navigate to "List Wizard" 
3. Navigate to chooseName
4. Scroll to the bottom of the list, note it stops at 23

**Expected behavior**
Can view all entries

**Attachments**
[TestWizard.zip](https://github.com/Microsoft/AL/files/2604389/TestWizard.zip)

**Versions:**

 - AL Langauge: al-2.0.48254

 - Business Central: CA Dynamics NAV 13.1 (25341)

**Comment by StanislawStempin** [comment]
How does it work if you create the same page in C/AL? In other words, is this a regression compared to what you used to get with C/AL and/or Windows Client?

**Comment by strophanthus** [comment]
In the Windows Client of this same build, using the same extension, the full list is visible.

**Comment by strophanthus** [comment]
Hello, 

This is affecting one of our partners, is there any update we can forward on to them?

**Comment by atoader** [comment]
Hi! This is fixed in the latest CU.
