### ISSUE TITLE
Translated Event Subscriber generates output with request to report the issue

### ISSUE THREAD

**Issue by BobFaber** [Microsoft/AL#4244]
**Describe the bug**
Processing of message 'textDocument/codeLens' failed with error: 'De objectverwijzing is niet op een exemplaar van een object ingesteld.'
StackTrace:
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.InternalCheckEventParameter(ParameterSymbol parameter, TypeSymbol publisherParameterType, Boolean publisherParameterIsVar, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 748
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.CheckEventSubscriberParameters(ImmutableArray`1 subscriberParameters, ImmutableArray`1 publisherParameters, IApplicationObjectTypeSymbol publisherApplicationObject, Boolean includeSender, Boolean globalVariableAccess, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 703
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.InternalCheckEventSubscriber(AttributeSymbol attribute, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 596
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.CheckEventAttribute(DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 464
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.LazyMethodChecks() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 251
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.get_Parameters() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 392
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.AddParametersIfRequired(MethodSymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:regel 414
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitMethod(MethodSymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:regel 398
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:regel 106
   bij Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayString(SymbolDisplayFormat format) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:regel 503
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<>c__DisplayClass0_0.<GetSymbolInformations>b__2(ISymbol s) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:regel 36
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<GetSymbolInformations>d__0.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:regel 33
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensRequestHandler.cs:regel 31
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:regel 59

[Error - 5:23:50 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeLens' failed with error: 'De objectverwijzing is niet op een exemplaar van een object ingesteld.'
StackTrace:
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.InternalCheckEventParameter(ParameterSymbol parameter, TypeSymbol publisherParameterType, Boolean publisherParameterIsVar, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 748
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.CheckEventSubscriberParameters(ImmutableArray`1 subscriberParameters, ImmutableArray`1 publisherParameters, IApplicationObjectTypeSymbol publisherApplicationObject, Boolean includeSender, Boolean globalVariableAccess, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 703
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.InternalCheckEventSubscriber(AttributeSymbol attribute, DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 596
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.CheckEventAttribute(DiagnosticBag diagnostics) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 464
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.LazyMethodChecks() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 251
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SourceMethodOrTriggerSymbol.get_Parameters() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:regel 392
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.AddParametersIfRequired(MethodSymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:regel 414
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitMethod(MethodSymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:regel 398
   bij Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:regel 106
   bij Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayString(SymbolDisplayFormat format) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:regel 503
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<>c__DisplayClass0_0.<GetSymbolInformations>b__2(ISymbol s) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:regel 36
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<GetSymbolInformations>d__0.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:regel 33
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensRequestHandler.cs:regel 31
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:regel 59

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
Created a Codeunit (70000) with an Event subscriber:
![image](https://user-images.githubusercontent.com/45129950/48854956-68530400-edb3-11e8-8e0b-03e3625ed91a.png)
(The exit was added after translation)
Exported the object as txt, using the command: finsql.exe Command=ExportToNewSyntax et cetera, following guidelines on URL: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool
After that, I used Txt2Al to convert the object, and added the resulting file into my AL Workspace.
![image](https://user-images.githubusercontent.com/45129950/48855447-5aea4980-edb4-11e8-804f-5f2a99281ce3.png)
After that, I got loads of messages in the Output Tab, and the application can not be generated.
However, the 'Problems' Tab says "No problems have been detected so far".

**Expected behavior**
After InitQtyToShip in the Sales Line, a message should appear: "The SYSTEM says: Qty. to Ship has been initialized." 
The message does not appear.

**Screenshots**

**Versions:**

 - AL Langauge: 0.12.15898

 - Business Central: NL Dynamics NAV 13.0 (24630)

**Comment by StanislawStempin** [comment]
Please use AL Language extension from the marketplace (directly in VS Code go to Extensions, search for AL Language and install it). It looks like you're using version 0.12 which is not for Business Central but for NAV 2018.

**Comment by BobFaber** [comment]
Nice :-( ! Please reopen this issue.
I went to Extensions, and indeed I have version 0.12 installed.
The only meaningful option is More, Check for updates.
The message I get: "All extensions are up to date."

**Comment by StanislawStempin** [comment]
That's because it's not an update to 0.12, you should uninstall 0.12 and search for AL Language again

**Comment by StanislawStempin** [comment]
Or install from here: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by BobFaber** [comment]
I installed the extension from the URL you mentioned.
No more output issues.
Thanks! Please close the issue.
