### ISSUE TITLE
Commit from install codeunit not supported?

### ISSUE THREAD

**Issue by JoelJame5** [microsoft/AL#4245]
As part of the installation process we download and apply a rapidstart package, however we get the _'OK := Codeunit.Run() is not allowed'_ in write transactions error. 

![errorapplyingpackage](https://user-images.githubusercontent.com/27202678/48858910-8e2cd880-edb4-11e8-9751-b991fb6dd8d7.gif)

I can confirm I get the same error on a simple "if Codeunit.Run(..) then" after modifying a record from within the Install Codeunit.

**Comment by StanislawStempin** [comment]
To allow rollback of the Install/Upgrade operations we do not support any commits in these scopes.
OK := Codeunit.Run() would commit a transaction and therefore is not allowed.

The specific problem of RapidStart is being looked at by the application team but from the platform side we will maintain this restriction.
