### ISSUE TITLE
Use webservices.xml to autocreate webservices-record gives error on F5 in VS Code

### ISSUE THREAD

**Issue by bennyvanlyssebettens** [Microsoft/AL#4247]
**Bug**
Pressing F5 in VSCode with a webservices.xml to create the record on install returns:

c:\Users\Van Lyssebettens\Documents\AL\KTN Replica\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Users\Van Lyssebettens\Documents\AL\KTN Replica\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.
c:\Users\Van Lyssebettens\Documents\AL\KTN Replica\IN\webservices.xml(1,1): info AL1027: The file at location 'c:\Users\Van Lyssebettens\Documents\AL\KTN Replica\IN\webservices.xml' matches the definition for 'TenantWebService'.

Compilation ended at '20:34:39.599'.

Success: The package is created.
[2018-11-21 20:34:39.59] Sending request to http://localhost:7179/BC130BE/dev/apps?SchemaUpdateMode=synchronize
[2018-11-21 20:34:41.07] The request for path /BC130BE/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Could not install the extension KTN Replica on tenant default due to the following error: String was not recognized as a valid Boolean.

**To Reproduce**
Add webservices.xml with the following content
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>5</ObjectType>
            <ServiceName>ReplicaImport</ServiceName>
            <ObjectID>99050</ObjectID>
            <Published>1</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

**Expected behavior**
Webclient runs, extensions installed and there 's a record in the webservices-table for my entry

If you use the following code, it's ok

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>5</ObjectType>
            <ServiceName>ReplicaImport</ServiceName>
            <ObjectID>99050</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

If you use the following code, it's also not ok

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>Codeunit</ObjectType>
            <ServiceName>ReplicaImport</ServiceName>
            <ObjectID>99050</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

Or u use a "integer" as value for ObjectType & Published or you use a "string" for both,
not a combination :(

If you use Page as ObjectType, it's also OK

**Versions:**
 - AL Langauge: 2.0.43900
 - Business Central: BE Dynamics NAV 13.0 (24630)

**Comment by StanislawStempin** [comment]
How did you create the xml content? By exporting from business central or by hand-crafting it (possibly using the twebservice snippet)?
At the very least the twebservice snippet should be suggesting content that works and exported xml should work out of the box.

**Comment by qutreson** [comment]
Hi @bennyvanlyssebettens, the snippet has been fixed and is available using the latest AL extension in the marketplace. Please feel free to open a new issue if we missed something.
