### ISSUE TITLE
Permission property of new report.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#425]
Hi!

This is my case.
1. I add some fields into **Table 17 G/L Entry**. Example: _Field A_ and _Field B_
2. I create new report (ProcessingOnly=true) to update these fields.

When I add Permission property for this report. I get an error as bellow.

![image](https://user-images.githubusercontent.com/24407031/28710880-e6a44a8c-73af-11e7-865e-2c46915039a0.png)

So, please show me how to solve this problem. If permission property is not supported. Please let me know.

**Comment by atoader** [comment]
Hi! Take a look at #214 . It explains the current usage of the Permissions property.
