### ISSUE TITLE
Why don't all system events provide access to global vars

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/AL#4250]
Similar to the Issue # 157, I would extend the question to why doesn't all system events such as OnOpenPageEvent for example provide access to all of the Global Vars on the page as part of the signature.

An example would be I need to add a field to a page, which I would like to show or hide based on a value configured elsewhere. To do this I create the Global Var and assign it to the field, and subscribe to the OnOpenPageEvent to determine what the setting for the global var should be.

The only problem with the above scenario stopping me from doing this is the system events do not give me access to any global variables, or the sending page itself, only the record the page is going to show.

To provide a comprehensive extensibility we should be able to have access to global vars as required.
At this point we have a large add-on which is 99% extension compliant but because of this limitation we cannot get it across the line. If there is some other way to achieve what we need without having access to the global vars, that does not include having a new event added simply for this purpose I would be grateful to hear it.

**Comment by StanislawStempin** [comment]
We do not want to expose all global variables across all event publishers. This would lead to too much coupling. Even worse, it would lead to coupling to state (through the global variables) that was originally not designed with being public in mind.
The solution that we're considering is #593. Until then the only way to get access is to request specific changes.
