### ISSUE TITLE
Standard Event on every function

### ISSUE THREAD

**Issue by SKeiler** [Microsoft/AL#4251]
Hello,

in the recent years, Microsoft has invested a lot of energy in souce code structure. A lot of existing source code was relocated in new functions and sub functions (for example the big CU80-Code-functions was divided in many small functions). 

With 2 standard events in every function like the trigger events, OnBeforeFunction and OnAfterFunction, there would be thousands of new events in NAV and partners would have a lot of possibilities to subscribe this ones for their apps.

And every source code refactoring would create new events automatically.

**Comment by StanislawStempin** [comment]
We have a similar suggestion where we talk about your idea as well. Feel free to upvote and add comments here: #1592
