### ISSUE TITLE
When will the features from previous issues ship?

### ISSUE THREAD

**Issue by Anna-Gudimova** [Microsoft/AL#4252]
I have requested some features in issues #3562 and #3582.

The issues have been closed with status "ships-in-future-update":
![image](https://user-images.githubusercontent.com/10453174/48918232-23c17a00-ee40-11e8-8d13-874e11f5ab77.png)

We have pulled the latest image with updates but the code is still not there. When can I expect it to ship?

**Comment by StanislawStempin** [comment]
They should be there. Make sure that you do docker pull for the bcsandox-master image. 

If they are still not there please follow up on the ALAppExtensions repo.
