### ISSUE TITLE
bug: SaaS sandbox issues re: installing an app that was previously unpublished

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#4257]
This issue sort of relates to https://github.com/Microsoft/AL/issues/4221 but, now knowing that extensions are non-upgradable in the SaaS sandbox, I think encountered a new artifact issue. 

Having trying to previously experiment unsuccessfully with .app version upgrades in my tenant's SaaS sandbox (this was before I was educated that .apps are not upgradable in the SaaS sandbox), I ultimately left behind a published 2.0.0.0 version of my app in the tenant SaaS sandbox.

I uninstalled the 2.0.0.0 version of my app and unpublished it. The extension is now gone from extension management. Good. 

I then revert the version number back to 1.0.0.0 in my app's app.json file and try do deploy it form VS code. The SaaS sandbox tenant server errors out with a code 422 in the VS Code output console, complaining that another app by the same name and publisher is already installed and won't allow me to install my 1.0.0.0 version. 

But.... my extension is no where to be found in extension management. Why is the sandbox complaining that it's installed?

I tried publishing from VS code via both schemamode=recreate as well as synchronize. No avail. Same error. 

My only workaround (short of recreating the sandbox which would cost my team a half day of setting up test data all over again, which made that option a hard **NO**) was to give my app a new name as well as a new app guid in app.json. Since this is a brand new implementation (go-live is this weekend), I don't mind.

For customers that are already live however, this isn't an option.

When I unpublish an extension from the sandbox, I would expect all traces of that extension to be removed from the sandbox. Why isn't this happening? Is there an ETA to correct this behaviour?

**Comment by StanislawStempin** [comment]
Could you please contact support with this case. They'd need to diagnose your specific tenant and GitHub is not the right forum for that.
