### ISSUE TITLE
Developing on-prem & cloud extension / dev license

### ISSUE THREAD

**Issue by erikrijn** [Microsoft/AL#4260]
For the past year I've been able to develop and publish our extension in our normal certified object range  (11260662-11261662) in the microsoft/bcsandbox container image without ever importing a license. Never had any issues or warnings. We are developing for both BC on-prem and cloud. Microsoft has assured us our range was valid and updated to include BC cloud.

Now, after spinning up the current bcsandbox I'm getting a licensing error while publishing:
`[2018-11-24 14:42:50.00] The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Your program license does not allow you to publish 'BCC Setup'.`

Creating a bcsandbox with our BC on-prem dev license is not possible.
```
Import License
....
Creating SUPER user
The license information is not valid.
```
What is the correct way of developing a solution that targets both on-prem and cloud? I don't want to go back to developing against local on-prem installations as cloud should always be leading.

**Comment by StanislawStempin** [comment]
It is very strange that you were able to publish your range on the Docker sandbox. The demo license does not allow publishing anything outside of the 50100-50150 range. 
Nothing should have changed here - you still need to use your partner license to develop On-Prem (Docker images count as On-Prem). It looks like you have an invalid (corrupt) license file at the moment. There were recently issues in the license portal, I'd suggest that you try obtaining a renewed license and if that doesn't work please contact support team.
