### ISSUE TITLE
Treat AL compiler warnings as errors and suppress Info 

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4261]
**Describe the bug**
Rule AL1027 doesn't deactivate after custom ruleset setting.

**To Reproduce**
I've attached a tiny example with 3 Rules deactivated but only AL1027 is steel showing the info warning

[RulesetIssue.zip](https://github.com/Microsoft/AL/files/2612949/RulesetIssue.zip)

`settings.json`
```js
{
    // Sets the list of paths to code analyzers to use for performing code analysis.
    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}",
        "${PerTenantExtensionCop}"
    ],
    // Specifies whether the code analysis should be performed for all source files in the opened folder
    "al.enableCodeAnalysis": true,
    // Sets the path to the file containing the customized rules to use when running code analysis.
    "al.ruleSetPath": "./rules/my.ruleset.json",
}
```
`my.ruleset.json`
```js
{
    "name": "My Ruleset",
    "description": "These rules must be respected by all the AL code written within the company.",
    "rules": [
        {
            "id": "AA0005",
            "action": "Hidden",
            "justification": "This is OK -> Avoid AA0005 warning notification for BEGIN .. END only with compound statements"
        },        
        {
            "id": "AL1027",
            "action": "Hidden",
            "justification": "This is KO -> Avoid AL1027 info notification for PermissionSet definition matches"
        },
        {
            "id": "AS0015",
            "action": "Hidden",
            "justification": "This is OK -> We don't need translations at the moment."
        }
    ]
}
```

**Expected behavior**
All rules must be deactivated or reduce their level of importance in the same way, without exceptions.

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/48977343-be1bfa80-f098-11e8-9ffa-418140502208.png)

**Versions:**
 - AL Language: **2.0.48254**
 - Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by JavierFuentes** [comment]
I'm Sorry to hear this... the AL1027 rule messages are a litle anoying...

**Comment by IvoMol** [comment]
It's a pity.
Modify AL rule "Error" to "Ignore" is bad idea.
But why not modify ""Warning" to "Error" or "Info" to "Hidden"?

**Comment by StanislawStempin** [comment]
Thanks, it does make sense. We will consider the Warning -> Error and Info -> Hidden as a suggestion.

**Comment by SBalslev** [comment]
I am closing this issue because it appears that it has been resolved as part of analysis framework changes in the 2023 Wave 1 timeframe. Please open a new issue if you believe this has not been resolved and reference the current issue

**Comment by JavierFuentes** [comment]
Hi @SBalslev,
due to Microsoft's Universal Code Initiative, we are trying to use **Scope=Cloud** in all of our new BC projects and trying to follow ALL official **Best Practices by enabling all CodeCops**...

BUT, when we try to use for compliance reasons some Spanish SII [OnPrem] functions to verify the "VAT Registration Number", we get **Compiler error AL0296**

We can't avoid that Error either by using `#pragma` or by a `ruleset.json` file for changing from Error to *Warning*, *Info* or *Hidden*.

`ruleset.json`
```json
{
    "name": "Name",
    "description": "Description",
    "rules": [
        {
            "id": "AL0296",
            "action": "Hidden",
            "justification": "Avoid AL0296 The application object or method '{0}' has scope '{1}' and cannot be used for '{2}' development."
        }
    ]
}
```

<img width="957" alt="image" src="https://user-images.githubusercontent.com/5801847/212704009-0e78ada7-14b2-4b4c-b18c-7ec02e4c8157.png">

Any idea how we can follow MS policies in these cases?
