### ISSUE TITLE
Suggestion: Show Primary Key info in IntelliSense

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4262]
I would like that when we type `recAnyTable.` in VSCode, IntelliSense could show with a **Key Icon** all the fields that are part of **Primary Key**... Ideally, they should always be correctly ordered **at Top of the field list  when the PK is composite**.

**Comment by EmilDamsbo** [comment]
This was partially delivered release 2022 Wave 2, based mostly on this idea:
https://experience.dynamics.com/ideas/idea/?ideaid=f88fb471-6507-ea11-b864-0003ff68ac6b

The view order in IntelliSense is not changed, as the view order is designed to correspond to the field ID, however the primary key fields are denoted by 'PKx' where x is the order in the key.
