### ISSUE TITLE
Versions are different between Prod and Sandbox.

### ISSUE THREAD

**Issue by Twija** [Microsoft/AL#4263]
**Describe the bug**
i created a new internal app on the docker container. this docker container has created with powershell which i downloaded from Prod environment using "Container Sandbox Environment (Preview)" environment. 

version of the container is same as the production environment. however the sandbox on the cloud is different. thus i couldn't publish and install on the sandbox on the cloud.

how could i test on the could sandbox?

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. sign in Prod environment
2. go to System Information
3. check the version
4. go to sandbox environment
5. go to system Information
6. compare the version

**Expected behavior**
the versions are same.

**Screenshots**
![image](https://user-images.githubusercontent.com/32067176/48992188-e3cd0080-f179-11e8-972d-a07317b2be5a.png)

![image](https://user-images.githubusercontent.com/32067176/48992192-e891b480-f179-11e8-89b6-e765c1d9f51c.png)

**Versions:**

 - AL Langauge: 2.0.48254

 - Business Central:

**Comment by StanislawStempin** [comment]
Why couldn't you test on the sandbox? As far as I can see the difference between the environments is only in the build number which means it's still the same major/minor version of the product and you should be able to test the same code on both your Docker and the sandbox.

**Comment by StanislawStempin** [comment]
Closing due to no sufficient input.
