### ISSUE TITLE
Error Code 502 when using web client (Daily Build)

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#4264]
Hi,
i am using the daily bc-build to develop extensions for my Company. But after creating it crashes after using it a few timers. It dosen't matter if i use it just to develop via vs-code or try the application. The web Client Comes up with error Code 502 (take a look at the attachment).

Every time i recreate my azure-container it only takes a few steps in web Client to see error 502 again. What Can i do.

**Comment by KaiSwitalla** [comment]
![502_invalid_response](https://user-images.githubusercontent.com/26924867/49014865-c56b0300-f181-11e8-842b-fa786764c0e9.jpg)

...here is my attachment

**Comment by atoader** [comment]
Hi @KaiSwitalla ! We do not have sufficient information to reproduce this issue. Could you please provide:
- Docker image tag
- Dump from Get-NavContainerDebugInfo command
- If Client crashes, then EventLog dump is needed. It can be retrieved by running Get-NavContainerEventLog
- If something is misconfigured then server settings are useful. Settings can be retrieved with Get-NavContainerServerConfiguration
Commands are available in navcontainerhelper module (https://github.com/Microsoft/navcontainerhelper).
