### ISSUE TITLE
Unable to connect  AL - Upgraded DB from 2015 to Business Central 

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/AL#4268]
Hi ,
I cannot able to connect Business Central on Premises from AL using Upgraded DB from 2015 
Please help !!
Note:
But Normal Default Cronus DB  I can able to connect  Business Central on Premises from AL.

Regards,
Muthu 
![issues](https://user-images.githubusercontent.com/44170162/49067136-22d48200-f25e-11e8-8cb0-a1cc09e6a2dc.JPG)

**Comment by StanislawStempin** [comment]
Please contact support. We can't troubleshoot specific upgrade issues through this forum.
Make sure to read the upgrade documentation and follow all the required steps: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/converting-a-database

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company

**Comment by IvoMol** [comment]
https://saurav-nav.blogspot.com/2018/10/msdyn365bc-data-upgrade-to-microsoft.html
Step 11 ???

**Comment by TharunMuthu** [comment]
Hi IvoMol No not this one I already did migration with out any issue and can able to connect RTC and Web Client also but my issue is after  migration I using VS Code cannot able to connect !!Please help

**Comment by shashiranjan3307** [comment]
It is not very proper while going to implement  [Microsoft dynamics 365 business central](https://prudencesoftech.com/microsoft-dynamics-365/)

**Comment by shashiranjan3307** [comment]
[supply chain management system](https://prudencesoftech.com/what-is-supply-chain-management/)
[supply chain management software](https://prudencesoftech.com/what-is-supply-chain-management/)
[supply chain management solution](https://prudencesoftech.com/what-is-supply-chain-management/)
[supply chain management](https://prudencesoftech.com/what-is-supply-chain-management/)
[ERP Software](https://prudencesoftech.com/what-is-erp/)
[ERP Solution](https://prudencesoftech.com/what-is-erp/)
[ERP Software Solution](https://prudencesoftech.com/what-is-erp/)
