### ISSUE TITLE
Multilayer Dependencies

### ISSUE THREAD

**Issue by LFlamme** [microsoft/AL#4269]
Hi,

I experience an issue when working with the dependencies.
I have 3 Extensions:
A, B and C.
A is the Base.
B has a dependency on A.
C has a dependency on B.

Now in C i can´t build a tableextension for a table i created in A. Since the Symbos of A should be in Extension B. I´m woundering, why I can´t extend those Tables. If i put both as dependencies in my app.json it works. I just feel like thats not the right was to do it, as by how I understand i would have the Symbols of A 2 times.

**Comment by kalberes** [comment]
This is not supported yet. No transitive closure on references is yet supported. On the other hand we have it in our backlog to make it easier to work with dependencies.

**Comment by atoader** [comment]
We have added support for propagated dependencies https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files and also improved the experience of working with dependencies. I will close this issue.
