### ISSUE TITLE
Error "Not Found" when downloading symbols

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#427]
I'm getting this error when trying to download symbols in VS Code:

[2017-07-30 13:35:28.00] Using reference symbols cache path: c:\Users\Administrator\Documents\AL\DynamicsShip\packages
[2017-07-30 13:35:31.17] Downloading from http://localhost:7049/navision_main/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0 ... Error (NotFound)
[2017-07-30 13:35:31.17] Could not download reference symbols

I've checked the service, the development flag. Everything seems to be running. I get the following error in the event log from the service:

Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 07/30/2017 20:35:31
Message <ii>Failed request -- Method:GET; Url:<ii>http://localhost:7049/navision_main/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0</ii>; StatusCode:NotFound; ReasonPhrase:Not Found; ResponseBody: </ii>
ProcessId: 3256
Tag: 00000LY
ThreadId: 33
CounterInformation: 

I tried to look at : http://localhost:7049/Navision_main/devhealth
But it's just blank.

**Comment by johndcollins** [comment]
So it looks like it was because the Application/Locale was set to US by default when creating a new VS Code project. It needed to be changed to W1
Error message could be better.

**Comment by AmolSalvi** [comment]
Changed locale it to W1 from US in App.JSON
