### ISSUE TITLE
Make DecimalPlaces property extendable on the standard table fields

### ISSUE THREAD

**Issue by OSHK** [microsoft/AL#4272]
Our customer has been using certain UOM since the beginning of its operating.
This particular UOM has 10 decimal points (_for which customization was made_) and due to the specifics of the industry, use of this a UOM with this level of decimal precision is a common practice.
Currently, the clients of our customer expect purchase documents with quantities specified in this UOM, and all of the sales/purchase documents history and ledgers display information are in this UOM.
 
Our customer would like to move its customizations to AL extension, however this seems to be not feasible, because standard Qty. field supports only 5 decimal points, and it is not possible to override **DecimalPlaces** property due to extensions limitation.

Without making this property editable, our customer will not be able to move to extension, since using of another UOM will lead to inconsistency of historical data and non-compliance with common practice in the industry.

Is it possible to provide us with the possibility to override **DecimalPlaces** property for the standard fields?

**Comment by OSHK** [comment]
Is there any news regarding this issue?

**Comment by Teming** [comment]
Has this been shipped to any release yet?  Thanks.

**Comment by Teming** [comment]
![image](https://user-images.githubusercontent.com/49729094/208776308-b371fb90-203b-45c2-b456-2c544ef874b0.png)
![image](https://user-images.githubusercontent.com/49729094/208776390-c1dff0e5-6cda-4bbc-83ac-cd89853f328a.png)

Did I do something wrong about DecimalPlaces?  We are using BC 21 version 
![image](https://user-images.githubusercontent.com/49729094/208776521-f95924d3-5d28-4f82-ad2a-420138d3b5a1.png)

Thanks very much.

**Comment by JMA1972** [comment]
Extensibilty of this property would be nice, but even without it the problem can be easily worked around. You just have to place another field with the required decimal places in the pages and then validate the standard field with it. Contrary to the documentation about decimal places this property doesn't impact the storage of the decimal places in any way, it just rules the user input and the displaying.

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
