### ISSUE TITLE
No debug session is getting started

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#4277]
**Describe the bug**

I'm trying to publish my extension package out of visual studio code by pressing F5 to my BC Sandbox which contains "production data".
The debugging console looks like this:
![2018-11-28_1433](https://user-images.githubusercontent.com/33331414/49155288-dc912880-f31a-11e8-90d9-d5c5ff661a4a.png)

So the Extension got successfull uploaded. But there is no debugging session started.
This is completly missing:
![toolbar](https://user-images.githubusercontent.com/33331414/49155725-fd0db280-f31b-11e8-97de-1bb7a8b90377.png)

I already installed Version 1.28.2 of VSC.
Because with 1.29 the debugging console was completly empty.
I also tried to reinstall the VSC AL Extension. Sadly, without any success...
ShowMyCode Property is set to "true".
My launch.json looks like this: 
![2018-11-28_1439](https://user-images.githubusercontent.com/33331414/49155527-76f16c00-f31b-11e8-8c04-88a1ced4708c.png)

**Versions:**

 - AL Langauge: 2.0.56865

 - Business Central: DE Dynamics NAV 13.0 (25789)

**Comment by kalberes** [comment]
For Cloud sandbox debugging your server should not be set, nor your instance. Also you should for safety run the Clear Credential cache command before debugging.
As you start debugging you will be prompted (once) to logon to your Azure sandbox instance.

**Comment by hendrik244** [comment]
Hi @kalberes,
Thanks for your quick answer.
sadly this did not helped...

Now I'm additionally got into this problem:
#4221 

Seems like it's very hard to just debug your own extension in the bc sandbox environment...

Best regards,

Hendrik

**Comment by StanislawStempin** [comment]
Can you try without specifying the "tenant" property in launch.json?

**Comment by hendrik244** [comment]
Hi @StanislawStempin ,

Sadly i couldn't tried this, because, as I said before i additionally ran into this problem: #4221
It was not possible to publish the app again...

I ended up making a bc docker container, publishing my app to it and debugging it there.

**Comment by StanislawStempin** [comment]
If you're still encountering the problem you would need to contact support, since we will need to look into telemetry and identify the specific problem for your tenant.
