### ISSUE TITLE
The type or method 'Event Subscription' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by johndcollins** [microsoft/AL#428]
I'm just trying to reference the Table 2000000140 to filter on events from code.
Why would this not be possible?

**Comment by StanislawStempin** [comment]
We currently cannot expose this table since it contains cross-tenant data. We will look into implementing a tenant-scoped version of this virtual table.

**Comment by kine** [comment]
I support to add something to be bale to access this table, because e.g. part of our testing app is to test that all our events are OK by checking this table. It is simple test to check that something is not broken.

**Comment by JalmarazMartn** [comment]
I think is inconsistent not allow this virtual table access: If we go to definition of Codeunit "Gen. Jnl.-Post Preview" we can see that is accessing to "Event Subscription" table to check manual events in "IsActive" function.
![eventsu](https://user-images.githubusercontent.com/44129743/50733459-021d1780-118e-11e9-8cf9-7531336056ab.png)
How we can perform this check?

**Comment by thpeder** [comment]
Hi, It seems this has been changed and access to the table is now possible.
