### ISSUE TITLE
Control Add-In PDF Security Issue

### ISSUE THREAD

**Issue by hrolfurh** [Microsoft/AL#4280]
**Issue**
I have a simple Control Add-In that displays a local PDF in iframe like so.

`$('#controlAddIn').html("<div><iframe id='controlAddInFrame' src='" + filepath + "' style='position:absolute;left:0px;top:0px;bottom:0px;right:0px;width:100%;height:100%;max-height:1000px'/></div>");`

Where the filepath is something like `C:\Contracts\abc.pdf`

This requires Adobe Reader to display the PDF and works fine in older versions of Dynamics NAV. However when I created an extension for Business Central (and also Dynamics NAV 2018 for that matter) I ran into a problem that the PDFs were not being displayed and Adobe gave me an error.

![image](https://user-images.githubusercontent.com/6655164/49156399-9b4e4800-f31d-11e8-8c07-2635d8d9aab2.png)

After a lot of digging around I found a way to fix this, by removing some security options in Adobe Reader. Mainly 

> Enable Protected Mode at startup

and

> Enable Enhanced Security

This is not optimal. It seems that Adobe Reader is blocking the Control Add-In from the extension while it would not do that in older versions, or the extension blocks the iframe from loading the PDF perhaps? 

**Versions:**
 - AL Langauge: 2.0.48254

 - Business Central: W1 13.0 (25789)

**Comment by atoader** [comment]
HI @hrolfurh ! Is this a Javascript Add-In or a .NET Add-In?

**Comment by hrolfurh** [comment]
This is a Javascript Add-In.

**Comment by atoader** [comment]
My guess is that this is related to the security model of Adobe Reader and not to how extensions work per se. Do you have access to the source code? Can you just use the Javascript and CSS files in a browser to see if the same issue reproduces? If that is the case, it might be a question for Stackoverflow

**Comment by hrolfurh** [comment]
I have tried using the same Javascript code in a browser but I can't reproduce the problem there. The only place where the code fails is in the extension. As I said before, the same Javascript also works in a Dynamics NAV 2017 Control Add-In. I've tried hard coding in the filepath to make sure that wasn't the problem but I get the same result. Therefore I concluded that it had something to do with how extensions work.

**Comment by atoader** [comment]
Thank you for looking into this, I just wanted to make sure that we cover as much as possible before forwarding your question.

**Comment by StanislawStempin** [comment]
We got a reply from the owning team:

This is not possible due to security restrictions. IE might allow opening a PDF file if the website and the file are both on the same machine. All other browsers block the loading off the file.

The only way to load files in the client is if the path of the document is pointing to the same URL as the website, so the file needs to be stored on the Business Central or Dynamics NAV web server.
