### ISSUE TITLE
Event Recorder AL Snippet enhancement

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#4284]
It would be nice if the AL Snippet of the Event Recorder would also contain the related parameter. Vincent Nicolas hat a matching Snippet in his [NAV TechDays 2018 - Opening Keynote Demo](https://youtu.be/qVu0XK7T4Uk?t=1139), but I don’t ;-).

Current AL Snippet:
```
[EventSubscriber(ObjectType::Tabelle, Database::"Customer", 'OnBeforeValidateEvent', 'E-Mail', true, true)] 
local procedure MyProcedure()
begin
end;
```

Would be nice AL Snippet:
```
[EventSubscriber(ObjectType::Tabelle, Database::"Customer", 'OnBeforeValidateEvent', 'E-Mail', true, true)] 
local procedure CustomerEMailOnBeforeValidateEvent(var Rec : Record Customer; var xRec : Record Customer, var CurrFieldNo : Integer)
begin
end;
```

**Comment by StanislawStempin** [comment]
You can simply place your cursor in the parenthesis, press Ctrl+Space and you will get all parameters suggested by IntelliSense.
We do not want to generate event subscriber signatures with all possible parameters since many will not be used and just clutter the code.

**Comment by IvoMol** [comment]
I rather liked the idea of generating the proper procedure name.

**Comment by StanislawStempin** [comment]
Aaaah, I missed that part. That is indeed a good idea

**Comment by DanielGoehler** [comment]
Hi @StanislawStempin,

you are right. I saw this with eye of C/SIDE where all parameter gets automatically added. I'm also for a proper procedure name.

To improve visibility a comment could be added, but I get if you say this should be clear. E.g.:
```
[EventSubscriber(ObjectType::Tabelle, Database::"Customer", 'OnBeforeValidateEvent', 'E-Mail', true, true)] 
local procedure CustomerEMailOnBeforeValidateEvent()
begin
//To add parameters place your cursor in the parenthesis, press Ctrl+Space and you get all parameters suggested by IntelliSense.
end;
```

**Comment by DanielGoehler** [comment]
Hi @atloader, just a hint: The programming of the Event Recorder should be extended. Has not much to do with the "al-snippets".
