### ISSUE TITLE
No error shown if the app file cannot be published

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#4289]
This is something we've found in at least two cases:

* If you try to publish the app to a docker with a different runtime from the one selected in the app.json (ex. the docker has "2.0" and the app.json has "2.1").
* If there is any compilation error while publishing the app (ex. we made a function external while MS makes the change, and we tried to publish it in a docker where the function was not external).

If we manually copy the app file to the docker VM and try to install the app, the server actually shows you what's wrong. Ex:

```
Publish-NAVApp : The runtime version of the extension package is currently set to '2.1'. The runtime version must be
set to '2.0' or earlier in the app.json file in order to install the extension package on this server.
```

However, this message is not shown in VS Code. Instead, we get this dialog, and an empty debug console:

![image](https://user-images.githubusercontent.com/6630306/49234852-1f293280-f3f9-11e8-9f4e-9853d1f25255.png)

![image](https://user-images.githubusercontent.com/6630306/49234940-497af000-f3f9-11e8-8d98-6c9d68c92e82.png)

It would be quite nice if VS Code showed the same error message as shown in the server powershell console.

**Comment by kalberes** [comment]
We do show error messages triggered by the server on publishing issue from VsCode too. Aren't you on VsCode 1.29.X? See issue #4240?

**Comment by salgiza** [comment]
Arg. You are right, I tried to find whether this had been reported before opening the ticket, and it looks like I should practice my searching skills.

I am in VS Code 1.29.x , so this is a duplicate of #4240 . Thanks!
