### ISSUE TITLE
How can I use enums in properties

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#4292]
I have created a enum:
![image](https://user-images.githubusercontent.com/33752561/49283891-46344280-f493-11e8-9176-1e833a363ec7.png)

I now want to use it in a record field:

![image](https://user-images.githubusercontent.com/33752561/49283944-682dc500-f493-11e8-9d33-3a57226eac32.png)

And include that field int a table relation:

![image](https://user-images.githubusercontent.com/33752561/49283973-8693c080-f493-11e8-88ec-072094e28910.png)

I cannot see how to do that.

**Comment by dNsl9r** [comment]
See #3953 it's not possible at the moment..

**Comment by StanislawStempin** [comment]
Note that #3953 has been fixed as of the platform build number 26249.
