### ISSUE TITLE
Error on flowfield of type enum

### ISSUE THREAD

**Issue by BrianThorChristensen** [Microsoft/AL#4296]
When I add a flowfield to lookup a flowfield from a related table, I get an error from the compiler:

The property 'FieldClass' can only be set if the property 'Type' is set with any of the values of :'BigInteger,Boolean,Code,Date,DateFormula,DateTime,Decimal,Duration,Integer,Guid,Media,MediaSet,Option,RecordID,Text,Time,TextConst' [AL0167]

I don't see any reason why this shouldn't work.

**Versions:**

 - AL Langauge: 2.0.43900

 - Business Central: DK Dynamics NAV 13.0 (24844)

**Comment by StanislawStempin** [comment]
Could you provide the sample AL code that triggers the error?

**Comment by BrianThorChristensen** [comment]
table 70001 KeyTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; KeyField; Integer)
        {
            DataClassification = ToBeClassified;
        }
        field(2; ValueField; enum "My Enum")
        {
            DataClassification = ToBeClassified;
        }
    }

    keys
    {
        key(PK; KeyField)
        {
            Clustered = true;
        }
    }
}

table 70002 ValueTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; KeyField; Integer)
        {
            DataClassification = ToBeClassified;
        }
        field(2; idField; integer)
        {
            DataClassification = ToBeClassified;
        }
        field(3; FlowField; enum "Camp Month")
        {
            FieldClass = FlowField;
            CalcFormula = lookup (KeyTable.ValueField where (keyField = field (keyField))); //ERROR WAS HERE
        }
    }

    keys
    {
        key(PK; keyField)
        {
            Clustered = true;
        }
    }
}


Since I have upgraded to AL extension 2.0.56865, I don’t get this error anymore. 😊
Feel free to close the issue.


Med venlig hilsen
Brian Thor Christensen
Systemudvikler
Computer Camp
btc@computercamp.dk
Færgeparken 21
DK-3600 Frederikssund
Telefon: +45 47 36 05 00
www.computercamp.dk
Fra: Stanislaw Stempin <notifications@github.com>
Sendt: ma 3. december 2018 15:18
Til: Microsoft/AL <AL@noreply.github.com>
Cc: Brian Thor Christensen <btc@computercamp.dk>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/AL] Error on flowfield of type enum (#4296)


Could you provide the sample AL code that triggers the error?
