### ISSUE TITLE
FileManagement.BLOBExport save last file only

### ISSUE THREAD

**Issue by dmatiukas** [Microsoft/AL#4298]
Function BLOBExport from codeunit 419 (FileManagement) able to save only last file.
Browser: Chrome. File save dialog doesn't appears.
BC Sandbox, FI localization.

Function BLOBExport is called multiple times in REPEAT/UNTIL statement. Code resist in Codeunit.
Codeunit Function is called from Page Action. Debugger shows that BLOBExport is executed after Page onAfterGetRecord code is finished and only one time.
I expected that function will be executed in REPEAT/UNTIL statement.
How to export multiple files without the file save dialog ?

BLOBExport function also add NULL symbol to the end of file.
Does exist some way to avoid adding NULL symbol to end of file ?

**Comment by dmatiukas** [comment]
Function BLOBExport from codeunit 419 (FileManagement) able to save only last file.
Browser: Chrome. File save dialog doesn't appears.
BC Sandbox, FI localization.

Function BLOBExport is called multiple times in REPEAT/UNTIL statement. Code resist in Codeunit.
Codeunit Function is called from Page Action. Debugger shows that BLOBExport is executed after Page onAfterGetRecord code is finished and only one time. 
I expected that function will be executed in REPEAT/UNTIL statement.
How to export multiple files without the file save dialog ?

BLOBExport function also add NULL symbol to the end of file. 
Does exist some way to avoid adding NULL symbol to end of file ?

**Comment by dNsl9r** [comment]
See #3575 - at the moment there is only a workaround of adding all files in a zip.

**Comment by StanislawStempin** [comment]
As mentioned in #3575 this is on the client team's backlog but there is no ETA. The workaround is to use a ZIP archive.
