### ISSUE TITLE
Upgrading a NAV 2016 environment with table C/AL customizations to a Business Central AL extension?

### ISSUE THREAD

**Issue by srikar1405** [Microsoft/AL#4299]
I want to upgrade NAV 2016 CAL Customized table(Containing data) to D365 BC AL Extension, How can I move data of my customized table into AL Table?

I have been following this link 
https://github.com/Microsoft/AL/issues/1512

I'm stuck at creating upgrade Codeunit 90001, can anyone help me in this?

**Comment by StanislawStempin** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
