### ISSUE TITLE
some Action Groups not showing

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#43]
I would like to add new action in Process group but it is not showing under addlast() function.
what is the reason? same with manage and reports.
other groups like Prices and WIP are showing.
![issue](https://cloud.githubusercontent.com/assets/23735402/21494818/0baf0862-cc3a-11e6-9c3e-0aff81dc0a2b.png)

**Comment by esbenk** [comment]
The actions on the front tab is either promoted or configured to be shown there. The mechanism here is the same for the new extension design. The page extension allows you to places controls/actions as if you are working on the original place in C/SIDE. The configuration and personalization layer are still applied on top.

**Comment by pmohanakrishna** [comment]
So we cannot change those personalizations using visual code, right?
Thanks..

**Comment by esbenk** [comment]
Page extensions are applied to the base page before customization and personalization. The shown page is the result of all the layers.

**Comment by pmohanakrishna** [comment]
Thanks..
