### ISSUE TITLE
[Request] Add more event into ContinuePosting.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#430]
Hi!

I need create the feature "Offset" to get offset accounting.
This feature base on Transaction No.
But I have a problem: there are so many transactions for each Transaction No. set (which be created by system). I need separate the Transaction No. set to many sub Transaction No. set as below:

![image](https://user-images.githubusercontent.com/24407031/28765428-e6bd75ec-75f4-11e7-9084-549e426d5673.png)

So please, if you can, please add more event to solve my problem. Maybe, you can add more event into condition (return a boolean value).

Thank so much !

**Comment by AlexanderYakunin** [comment]
Thank you for suggestion, we plan to separate condition for increase of Transaction No. to separated procedure and add events to alter this condition.
