### ISSUE TITLE
ShowAsTree type repeaters not showing complete dataset from the beggining

### ISSUE THREAD

**Issue by arvitis** [microsoft/AL#4303]
When running page 634 (Chart of Accounts Overview) from Business Central, the initial dataset does not include all the records. You have to expand and scroll down to fetch more records, in order to see all the results.This does not happen in the RTC client.

Moreover the same issue exists when developing a new worksheet type page with showastree in the repeater.

![image](https://user-images.githubusercontent.com/13156254/49403382-50856380-f755-11e8-8c58-3e554d96b920.png)

![image](https://user-images.githubusercontent.com/13156254/49403456-80346b80-f755-11e8-8765-4f5a22034f7c.png)

**Comment by thpeder** [comment]
Hi @arvitis,
I tried opening the page 634 (Chart of Accounts Overview) like you said, but I'm getting all the items like the image from the RTC client shows, except all of them were expanded.
System info: US Dynamics NAV 13.1 (26435)

Could you please provide a small extension that reproduces the problem.

**Comment by arvitis** [comment]
Hi @thpeder .

here are the steps:

1. open the page.
2. collapse the accounts.
3. check how many of them are displayed.
4. expand the accounts.
5. scroll down
6. collapse again.
7. check how many are displayed now.

**Comment by KristofKlein** [comment]
I have the same with the Test Tools Page - if you have many testitems it should show the described behavior.

**Comment by JohanStenberg100** [comment]
Hi @arvitis, can you please try and repro this on the latest BC instance you can get a hold of? And then mention the version you are using?

**Comment by arvitis** [comment]
Hi all, i m getting the same behaviour.

I m just using the latest online version.

**Comment by arvitis** [comment]
Hi all,

any progress on the above?
thanks!

**Comment by JohanStenberg100** [comment]
Hi @arvitis we have become more strict with the issues we accept here in this repository.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
* Open a support request to CSS through the PartnerSource portal
* Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by arvitis** [comment]
> Hi @arvitis we have become more strict with the issues we accept here in this repository.
> 
> Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
> 
> To open a support case, you can:
> 
> * Open a support request to CSS through the PartnerSource portal
> * Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
> 
> If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

Hi @JohanStenberg100 ,

thanks for coming back to me, but this issue is placed 5 months ago..
now we ll have to open a new ticket and wait for who knows again???
i really don;t think this is right.

**Comment by JohanStenberg100** [comment]
I understand your frustration, but since this repository is maintained by the dev team building the AL compiler and tools, we can't scale it to handle other issues as well. We should have been more strict before accepting your issue to begin with.

If you reach out to support they will be much faster.
