### ISSUE TITLE
Cannot publish to cloud sandbox from VS Code (any extension)

### ISSUE THREAD

**Issue by himalpatel81** [Microsoft/AL#4304]
- AL Extension Version: 2.0.56856

- Server Version: Sandbox

- Created a new project and set the proper name/publisher in app.json file.
- HEre is my launch.json file.
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Publish",
            "type": "al",
            "request": "launch",
            "startupObjectId": 22
        }
    ]
}`
-Getting the following error during publish. There is no other error in Debug Console or event viewer. 

Could not publish the package to the server. See Visual Studio Code debug console for more details.

**Comment by RuiningFan** [comment]
I have the same issue.

**Comment by JulienDecottignies** [comment]
Is your vscode version 1.29.x ? If it is, downgrade to 1.28.x:
https://code.visualstudio.com/updates/v1_28

**Comment by Tharangac** [comment]
Check if you have "runtime": "2.0"  in your app file. We got the same issue around 2 weeks ago and spend some considerable time to realise the issue which we didn't had previously. If you try to install it to your on-premise installation it will show the error on the event log.

**Comment by atoader** [comment]
@himalpatel81 have you resolved your problem? You can see more information about runtime versioning here: https://youtu.be/7jNByP3kFPk?t=2804

**Comment by himalpatel81** [comment]
Thanks for sharing the link. Yes, i got the issue resolved by changing the
runtime version to 2.0.
