### ISSUE TITLE
CANNOT ABLE TO PUBLISH EXTENSION IN BUSINESS CENTRAL CU01 NA

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4307]
Hello,

I have worked on the AL Extension in spring base release of Business Central, Now i have installed the Business Central for NA 

when i tried to publish the same extension in Business Central CU01 NA in the ouput tab it is saying that package is created and in the Debug console it is not saying the Package is created and in the BC windows client in the Extension page it didn't created any extension package file 

Thanks in Advance.

**Comment by dNsl9r** [comment]
Did you download the Symbols of the BC 365 CU01 NA?

**Comment by sainath654** [comment]
Yes symbols are downloaded

**Comment by thpeder** [comment]
Hi @sainath654,
Please have a look at [#4240](https://github.com/Microsoft/AL/issues/4240#issuecomment-440596262)

**Comment by sainath654** [comment]
Thanks @thpeder i have downgraded the VS Code Editor (1.27.2) and now its working fine.
