### ISSUE TITLE
It is good to have some Properties or Event (or something like this) which developer can use to catch moment of the collapse or expand action for the Group

### ISSUE THREAD

**Issue by RedFoxUA** [microsoft/AL#4308]
It is good to have Property or Event (or something like this) which developer can use to catch a moment of the collapse or expand action for the Group.
Additionally, it is good to have property for a Group, which inform JS how to show Group (collapsed or expanded) when the new page opened.

Example - we have "list of Tabs" (like a collapsed card page) with accounts and when a new page is opening we have just "header" of this page with the list of the fields with property Importance = Promoted.
When a user expands the Group, all these fields (Importance = Promoted) either hide or updated.

P.S. it is good to have also the possibility to show updated grid (maybe updated grid) without push any button.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
