### ISSUE TITLE
Txt2Al - Permissions Property 

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#431]
Hi,

Permissions Property is giving error after converting from txt2Al see below

![image](https://user-images.githubusercontent.com/26792519/28780414-426dc50c-7624-11e7-8d8b-d12712134129.png)

So does this property will not support in al or how it works. can you please suggest?

Thanks & regards
Varun Reddy

**Comment by johndcollins** [comment]
I think what's happening is that you are not allowed to add permissions for tables outside your Extension.
This however will not work very well. We need the ability to add permissions to tables outside the Extension. For instance, I'd like to change some data on the Sales Shipment Table, but this would not let me do that. Hopefully this will be looked soon.

**Comment by atoader** [comment]
The problem is discussed in #214 . We are still looking into ways of enabling this scenario.

**Comment by bachii1010** [comment]
Hi

Is it possible that this will be enable in future releases and if yes do you have any timeframe.
