### ISSUE TITLE
Control Add-In does not stretch to full available width when on a card page

### ISSUE THREAD

**Issue by spapke** [microsoft/AL#4311]
AL Language: 2.0.56856
 Business Central: US Dynamics NAV 13.1 (26323)

Based on the response to issue #3832 (see below), the control add-in should stretch to use the full available space in a full-screen layout on a card type page in which the only visible field on the page is the control add-in. However, the page width does not allow the control add-in to display at full width.

![image](https://user-images.githubusercontent.com/29461382/49529417-f2a36980-f883-11e8-84d8-1c92e8d3c39d.png)

Response to Issue #3832:

> Response from the Client team:
> We have a special layout for an add-in to let it stretch to full available space. To enable the full-screen layout, the page needs to satisfy these conditions:
> The page type is Card.
> The control add-in needs to be the only visible field on the page.

**Comment by qutreson** [comment]
Closing this issue as it seems like a client issue which is beyond the scope of this repository which is only for issues relateds to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
