### ISSUE TITLE
PTE0005 App.json 'target' property must not be set to 'Internal'

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#4317]
**Describe the bug**
We want to build an OnPrem Extension using .NET as suggested in the ".NET Interoperability from AL"-docs (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al) we added a "target: internal" 

But now we get an error "PTE0005 App.json 'target' property must not be set to 'Internal'" in VSCode

We checked https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#appjson-file but there is only a reference that "The Dynamics NAV Server" must also be set to internal. 

We found a "ExtensionAllowedTargetLevel" Key in the NST CustomSettings.config, which is set to "Internal" which I guessed the doc meant. 
![image](https://user-images.githubusercontent.com/35929603/49597829-8e64d080-f97d-11e8-83ef-ae167f39265f.png)

I don't know what else to set or check, please help me understand and set up our development enviroment correctly.

**Comment by StanislawStempin** [comment]
You should not be using PTECop when developing On-Prem. Your settings are all correct.

**Comment by JulianTillmann** [comment]
>           You should not be using PTECop when developing On-Prem. Your settings are all correct.

What is PTECop and how do I not use it?

**Comment by JulianTillmann** [comment]
Found it

one request: please don't use abbreviations that are not googleable, took me a Long time to find "PerTenantExtensionCop"

**Comment by NAVFreak** [comment]
A colleague of mine had this problem.
Go to File/Preferences/Settings, search for "code analyzers" until you find "AL: Code Analyzers".
Choose "Edit in settings.json".
Remove the line "_"al.enableCodeAnalysis": true_ "
