### ISSUE TITLE
suggestion: purge .app files at build

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/AL#4318]
**Is your feature request related to a problem? Please describe.**
When upping the version of an AL .app, the build process doesn't clean up any previously created .app files in the project's root directory and they slowly build up there over time e.g.

* {publisher-name}_{app name}_1.0.0.0.app
* {publisher-name}_{app name}_1.0.0.1.app
* {publisher-name}_{app name}_1.0.0.2.app
* {publisher-name}_{app name}_1.0.0.3.app

A developer may mistakenly grab the wrong .app version to manually deploy to a BC production environment. Automatically cleaning up the .app files would negate much of this risk. 

**Describe the solution you'd like**
When building or deploying an app from visual studio code, it would be nice if the compiler purged any .app files it finds in the root dir before creating the latest .app file. This would be consistent with typical visual studio build behaviour.

To compliment this, add an "AL: clean" VS code command task. Executing that task would purge all .app files it finds (not only in root, but any .app files it finds in .alpackages as well. 

**AL Language Extension currently installed**
AL Language extension v.2.0.56865

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
