### ISSUE TITLE
Txt2Al - Curreport.PageNo property

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#432]
Hi

We are getting the below error regarding PageNo property after converting from Txt2Al

![image](https://user-images.githubusercontent.com/26792519/28780688-4e3ebd04-7625-11e7-97de-b2bbc935bf6a.png)

Can you please suggest on this.

Thanks & Regards
Varun Reddy

**Comment by atoader** [comment]
Please see #477 . I have unblocked the procedure for extension development so that you do not get this error message. In the long run, I think that it would be better to remove CurrReport.PageNo from your code.
