### ISSUE TITLE
Codeunit- Event Subscibers on BC365 on premise

### ISSUE THREAD

**Issue by armela1981** [Microsoft/AL#4321]
Hello there.  
Not sure if I am on the right section, but wanted to report the following issue that I am having and hoping that someone can shed some insight.

I have created a codeunit to handle eventSubscribers.
I have these functions among others (see pic below).
What the below does, is take a custom field and pass value from the Purchase header to the vendor ledger entry.
So 2 events (one Purchheader to GenJnl and the other event from GenJnl to Vendor ledg).
This works great in my SBX environment running locally on Docker, however does not work on the client environment.
The client is running BC365 on Premise.
This codeunit has other EventSubscibers but they use table Events and they work great.
Any idea why the code below does not work on the client's environment ?

FYI, the extension is installed and everything else works , even other subcriber functions in this codeunit, that are not pointing to other codeunits.
Any ideas ? Is there smth different with BC365 on Premise that we need to handle differently ?

 
![screenshot](https://user-images.githubusercontent.com/39662533/49601274-fcdc6b00-f94a-11e8-8951-2d36bc7f1cfe.png)

**Comment by thpeder** [comment]
Hi @armela1981,
Sorry that it took us this long to return to you, if you are still having the issue, have you looked at page 9510 "Event Subscriptions" it has a error information column all the way to the right.

**Comment by thpeder** [comment]
Since I haven't heard anymore I'll close this issue, but feel free to open a new issue if you find a bug in the latest developer preview.
