### ISSUE TITLE
VSCode creates duplicate files

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#4322]
I am designing an Extension with quite a few Reports, which slows down the realtime warnings. There have been a lot of issues with my txt2al converted Reports which were basically the same issue over and over again so I got quite fast at solving this. 

It happend around 10 times that VSCode copied my file (with an Suffix with my local machine Name) and the original file was empty or in an old Version of my code. VSCode switched the files opened in my Editor without me noticing first, so that I had to go back and compare those files and delete one of them. 

Is this a known issue? Can I surpress this behavior somehow?

**Comment by thpeder** [comment]
Hi @JulianTillmann,
Please open a new issue about the Txt2AL convertion and include a .txt file that reproduces the problem.

What files are copied and have their filename changed? I'm not aware that we are doing anything like that.
The compiler will keep your .rdl and word files updated so when you change your reports dataset then the files also have the correct view of what the system provides them.

**Comment by JulianTillmann** [comment]
This is not a Problem with a single file but rather seems a strange behaviour of VSCode. 

I have, for example, a Report file "Rep56789.SomeReport.al" and I'm searching and replacing some Code, that the Txt2al provided. The real time warning thingy (I don't know what to call it) is checking all the changes I'm doing and suddenly I have a new file called "Rep56789.SomeReport-localmachinename.al". The old file is empty or has a previous state with Code I already changed.

**Comment by thpeder** [comment]
Are you sure this is not the effect of some other extension you have installed in VSCode. Try disabling all other extensions and see if the behavior is still there,

**Comment by JulianTillmann** [comment]
Nothing I would think: German Language for VSCode, AL Language, a XML Formatter and a GUID Creator. But I'll try. 

Is there a way to disable or slow down the real time warning thingy? I'd suspect this would be to blame

**Comment by qutreson** [comment]
In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it still reproduce on the Wave 1 2020 release?

**Comment by JulianTillmann** [comment]
hasn't happened in months I think. so I guess this can be closed

**Comment by qutreson** [comment]
I will close it then, thank you for your answer!
