### ISSUE TITLE
NotBlank = true with Enums throws an Error in Publishing time

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4323]
**Describe the bug**
When you **set NotBlank = true in an Enum field** compiler don't shows any error but when you try to publish the extension, it throws a *Could not publish the package to the server* error.

**To Reproduce**
Set NoBlank = true in an Enum field.

**Expected behavior**
I would like Enums behaves like Options with this property (see my attached example).

Otherwise, compiler should throw an Error in compiling time because the message when you try to publish your extension don't tell you where is the problem.

[NotBlankEnumIssue.zip](https://github.com/Microsoft/AL/files/2654271/NotBlankEnumIssue.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/49602817-bbb77b80-f989-11e8-936d-ec84118be8a6.png)

![image](https://user-images.githubusercontent.com/5801847/49602824-bfe39900-f989-11e8-9187-af258e4d14c4.png)

**Versions:**
- AL Language: **2.0.48254**
- Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by esbenk** [comment]
Please to update to the latest CU.

**Comment by JavierFuentes** [comment]
On List and Card Pages there is the same Bug.

Sorry @esbenk, but in our OnPremises environment we can't update to the latest CU every month...
