### ISSUE TITLE
Page Captions doesn't update dynamically in 'gray-Lists' (first open from VSCode)

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4324]
**Describe the bug**
When we need to change the Caption of a Page dynamically, it runs on Editable white-List Pages and on Card Pages.

It doesn't works on 'gray-Lists' Pages (a Page List open directly from VSCode with F5)

Aditionally, **on Card Pages** if you don't do **CurrPage.Update(true)** after change Caption, it doesn't changes when you are creating a NEW record... in Editions on Cards or Lists this is not necessary... ¿why?

**To Reproduce**
Use this example:
[UpdateCaptionIssue.zip](https://github.com/Microsoft/AL/files/2654940/UpdateCaptionIssue.zip)

**Expected behavior**
Caption should change dynamically in all Page types and States without need to execute CurrPage.Update(true)... maybe missing **CurrPage.UpdateControls()** is needed?

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/49609887-30e07c00-f99d-11e8-946a-207c5692df97.png)

![image](https://user-images.githubusercontent.com/5801847/49609803-e52dd280-f99c-11e8-9494-d3dbddc47e32.png)

![image](https://user-images.githubusercontent.com/5801847/49610231-46a27100-f99e-11e8-9b22-7daf4b5c2491.png)

![image](https://user-images.githubusercontent.com/5801847/49612064-d1399f00-f9a3-11e8-9223-90c46923b868.png)

**Versions:**
 - AL Language: **2.0.48254** 
 - Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by hoovercj** [comment]
@JavierFuentes thanks for reporting this to us. 'gray-lists' (or embedded lists, as we call them) are considered "read only", so we do not have any immediate plans to support this behavior.

**Comment by qutreson** [comment]
Closing this issue as it seems like a client issue which is beyond the scope of this repository which is only for issues related to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
