### ISSUE TITLE
Business Central RTC/Mobile App doesn't support Microphone and sound

### ISSUE THREAD

**Issue by rishiaurrishabh** [microsoft/AL#4326]
I have built an controladdin where I am using sound and microphone on my html page using javascript.
Now If I add this control on a NAV page and use it on web client it works fine as expected.

But when I use the same page on my RTC or mobile app then Sound and microphone setting doesn't work and neither I get any error (may be because of html and script).

I do understand that there is difference in running them on browser and App but it would be great if there is any way or workaround for the same.

Thanks.

**Comment by thpeder** [comment]
Hi @rishiaurrishabh,
We don't know of any workaround since the mobile app currently doesn't have built-in sound and microphone support capabilities.

**Comment by qutreson** [comment]
This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
