### ISSUE TITLE
Codeunit Assert is not reachable

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4327]
Hey guys,

I am creating a test codeunit and in that I would like to use the standard codeunit "Assert" like Microsoft does it here:

![grafik](https://user-images.githubusercontent.com/42337107/49635736-ff999780-fa00-11e8-81f1-5668855ac1a2.png)

I developed my own extension, created in VSC a dependency to it and downloaded the symbols. I installed the test toolkit, so what is missing?

Do you have any ideas?

**Comment by thpeder** [comment]
Hi @malue19,
Have you updated your app.json to depend on the testing toolkit?
![image](https://user-images.githubusercontent.com/24276180/49636405-c95d1780-fa02-11e8-8a1b-94f75b32c71b.png)

**Comment by malue19** [comment]
Hi @thpeder,

Now I did as you told me and it works ;) Thank you 👍

**Comment by thpeder** [comment]
I don't know how the testing toolkit works unfortunately.
