### ISSUE TITLE
Cannot display blob on page with temporary record; cannot assign blob fields

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#433]
Not sure if this is actually one or two issues:

I want to insert some pictures into an app. Not wanting to have to think about where to obtain pictures and get them in the db I lazily went to get the base64 signature and hardcoded it as text into the setup wizard rountine we need anyway.

Now I see two strange things not working: 

1. When I stream my text into TempBlob and then to Company Information (to test if it arrived how and  where it should) all seems well and I can see my picture displayed there. Now when I do the very same to my temporary records and display those as a list the pictures do not show. I debugged a bit and to me it seems the blob goes into the temp record as I expect. So maybe there is an issue here? In our On Prem solution a similar approach works fine.

2. When I assign the blob to records I have to use cumbersome Instream/Outstream/CopyStream because when I simply assign a blob field the code compiles but throws an error at runtime. This happens regardless if the target table is temporary or not. This also works fine in OnPrem Nav using C/SIDE.

**Comment by DominikDitoIvosevic** [comment]
I'm working on a bugfix where assigning to a blob field was failing at runtime. The fix should be available in the next update. Could you possibly be so kind to provide me with a small verifiable example which is failing so that I can check if I have you fix?

**Comment by RafaelKoch** [comment]
@DominikDitoIvosevic please find attached:
[SimpleBLOBAssign.zip](https://github.com/Microsoft/AL/files/1191819/SimpleBLOBAssign.zip)

On the Company Information try these Actions:
![pictureassignments](https://user-images.githubusercontent.com/25029667/28845525-a4b98cac-7708-11e7-85da-8f47d198139e.png)

**Comment by DominikDitoIvosevic** [comment]
@RafaelKoch So I have identified and fixed the problem with assigning to a blob field but I'm having problems identifying why the list doesn't show the picture. I'm still working on that one
