### ISSUE TITLE
txt2al - Error extracting application object from file: <xxxx> Error extracting application object from file: <xxx> Message: <EndOfStream> expected.

### ISSUE THREAD

**Issue by antarescorscorpi** [Microsoft/AL#4332]
am trying to use the txt2al converter to generate AL Code for my custom report object. The tool parses all the files from "C:" and gives the error - 

"Error extracting application object from file: <xxxx> Error extracting application object from file: <xxx> Message: <EndOfStream> expected "

![2018-12-08](https://user-images.githubusercontent.com/43426944/49687635-51d0da80-fb1f-11e8-8382-5f614596c7c4.png)

- AL Extension Version: 2.0.56865

- Server Version: NAV2018CU12

txt2al --source=D:\R60009-reformatted.txt --target=D:\

![2018-12-08](https://user-images.githubusercontent.com/43426944/49687640-61e8ba00-fb1f-11e8-9ec8-87307c2b12b8.png)

**Comment by JulienDecottignies** [comment]
You have to provide an source **_folder_** and a  target **_folder_**

put your txt file in a "source" folder in D:\ so 
`--source=D:\source`

Do the same for target
