### ISSUE TITLE
Unable to create Sandbox with production data

### ISSUE THREAD

**Issue by Tharangac** [microsoft/AL#4334]
**Describe the bug**
Unable to create Sandbox with Production Data. 
Error message: "The source environment with name 'Production' and Family 'BusinessCentral' could not be found"

**To Reproduce**
1. Go to the admin centre
2. Click create sandbox
3. Click copy production data
4. Click ok. 

**Expected behaviour**
The sandbox should create with production data

**Screenshots**
![image](https://user-images.githubusercontent.com/18136791/49703828-fb72b180-fc6e-11e8-9256-9e6ba79ae20c.png)

**Versions:**
 - Business Central: V198

**Comment by atoader** [comment]
Hi! Could you please go to the "System Information" page and take a screenshot? As far as I know, V198 is not a valid BC version.

**Comment by Tharangac** [comment]
![image](https://user-images.githubusercontent.com/18136791/49763333-36d5b480-fd31-11e8-9641-39ed3612302f.png)

![image](https://user-images.githubusercontent.com/18136791/49763383-5240bf80-fd31-11e8-90cc-cc950b614d60.png)

**Comment by Tharangac** [comment]
Hi guys, 

Any update on this?

**Comment by auzhhv** [comment]
Any updates to this issue? Got the same error today after deleting the Sandbox and trying to create new.

![image](https://user-images.githubusercontent.com/46031720/50990035-4ce1bb00-1511-11e9-8362-91a49b3c5196.png)

**Comment by atoader** [comment]
@Tharangac has the issue been resolved? @auzhhv can you try again and let me know if the issue still occurs?

**Comment by auzhhv** [comment]
@atoader  I'm still getting the error, with new tracking ID:
![image](https://user-images.githubusercontent.com/46031720/51019894-fa3de880-157c-11e9-8b4f-9aebe8cc35c8.png)

**Comment by atoader** [comment]
@auzhhv  can you retry once more? Thanks!

**Comment by auzhhv** [comment]
@atoader Its working! Thank you 👍

**Comment by craigbarberini-theta** [comment]
This issue has appeared again for our tenant. I think it is because the Sandbox gets created with version 13.4 but production is 13.3. When will a fix be provided for this?

**Comment by mustafachohan** [comment]
We are also not able to create the Sand box for our customer; when we create the sand box it should Preparing; after few minutes it shows removing and environment is never created. Version: 13.5.29483.0

<img width="1280" alt="Screen Shot 2019-04-06 at 1 28 32 PM" src="https://user-images.githubusercontent.com/49344354/55671547-380f8c00-58a2-11e9-8eac-3ede03a41792.png">
<img width="1280" alt="Screen Shot 2019-04-06 at 1 29 29 PM" src="https://user-images.githubusercontent.com/49344354/55671548-38a82280-58a2-11e9-8081-23b6f0597f18.png">

**Comment by atoader** [comment]
We have forwarded this issue to the responsible team when it was created and the initial instance was resolved. 

Going forward, you should open a support case and work with our customer support team to gather all the information necessary to fix this problem. This will guarantee that we can address your issue with the correct priority.
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

**Comment by LieYanuar** [comment]
Hi, i also have problem when create sandbox from production. The sandbox appear as 'Preparing' then later after a while it's 'Removing' and then removed.
![image](https://user-images.githubusercontent.com/54498631/118596929-37ae8280-b7d6-11eb-92f0-63393edbd84f.png)

![image](https://user-images.githubusercontent.com/54498631/118597064-62004000-b7d6-11eb-8a22-d6f284040baf.png)

Version: 18.1.24822.24906

I don't have support plan with microsoft therefore i can't open a support ticket.

**Comment by atoader** [comment]
We cannot provide assistance for this issue here. What is most likely happening is that one of your PTEs does not compile because one of its dependencies changed. You should ensure that all the PTEs on your sandbox work together.
