### ISSUE TITLE
Application Installation Issue in Prod Environment

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#4336]
> **Cannot install the extension Routing Report by XYZ 1.0.0.5 because the tenant msca1a7355t53497180 already uses a different version of it.**

When We are trying to deploy our application to the production environment it is published successfully but it gives an error as described above while installing.

**Comment by atoader** [comment]
Have you followed the instructions in this article https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions ?
