### ISSUE TITLE
Drop down options field with assist edit not showing correct value

### ISSUE THREAD

**Issue by AddEleven** [microsoft/AL#4337]
Error when there is a Option drop down field with an assist edit on a list. After selecting a value via the option drop down, the value does not display correctly.
Possibly linked to #3786 

Example:
1. Go to Change Log Setup. 
2. Click Setup > Tables.
3. Change the Log Insertion value on any row. 
4. Select another row and then go back to the previous row and it will be blanked out.
5. Also, try to select blank option in 'Log Insertion' and it will not let you.

**Expected behavior**
Value should be displayed when you select the row.
Should be able to select blank option for row.

![msbug](https://user-images.githubusercontent.com/38120867/49714390-c0897180-fca0-11e8-9ffa-6c13a305f93d.png)

**Versions:**
 - AL Language: Vsix 2.0.56865
 - Business Central: W1 14.0 (26140)

**Comment by atoader** [comment]
Hi @AddEleven ! Thank you for reporting the issue and for the instructions on how to reproduce. This is what I get:
![2018-12-12_07-30-10](https://user-images.githubusercontent.com/3097909/49853724-51b73000-fde8-11e8-9c7e-a9847894e431.gif)

Are you experiencing the same?

**Comment by AddEleven** [comment]
Hey @atoader,

Yes that is the issue. As well as not being able to select blank Log Insertion value after already inserting a different value

**Comment by atoader** [comment]
This issue has been fixed in the Wave 2 2019 release.
