### ISSUE TITLE
Test if existing fields are implemented on page

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4338]
Hey guys, 
after knowing, how to use all standard objects in my test codeunit, I would like to test, if my implemented fields on the page "item card" exist and in that case, the ouput should be true. I am doing this for my extension, I have developed. For that kind of testing I would like to use the standard codeunit "Assert". Should I use the function IsTrue?

Or do you have another idea, how to test that?

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
