### ISSUE TITLE
Cannot "open" fields of page

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4339]
Hey guys, 

I created in my test codeunit a global variable of the page "Item Card":
ItemCard: Page "Item Card"

In the test procedure I want to use the fields of that page, so I did:
ItemCard.xxx

But if I do so, in VSC it opens only Activate, Caption, Close, GetRecord and so on, but there is no field mentioned?!

**Comment by NKarolak** [comment]
In test codeunits, you need to use object type TestPage, not Page.

**Comment by atoader** [comment]
Hi @malue19! Please be advised that this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
