### ISSUE TITLE
no way to launch browser from AL debugger via inprivate/incognito?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#4340]
As a BC partner, I often have to jump around to various tenants. However, if I'm not careful, the browser will remember that I last logged into a tenant site. Due to 2FA issues we're currently experiencing with VS code (I have an open git issue on this), I'm having to resort to using tenant logins to debug our SaaS sandboxes.  

This presents an issue with VS code integration. When VS Code launches the browser, there is a good chance that the browser will take me to the wrong tenant such as our own sandbox, and not the tenant's sandbox that I actually want to debug. 

If there were a way optionally to spin up Edge -inPrivate or Chrome -incognito when the VS Code debugger launches, that would eliminate many of these issues. If that's not possible, then treat this as a feature request.

Currently I have to make sure I'm signed out from azure on my default browser before I launch the VS code debugger (that works as well as clearing cookies). Incognito would work much better though.

**Comment by atoader** [comment]
You can use the 
"al.browser": "edge" or "chrome"
and the 
"al.incognito" : true
options to trigger this behavior.

You will not get autocomplete in the current release, but it will be available from the next release of the extension.

**Comment by CanuckNav74** [comment]
THANK YOU @atoader !

I was looking into the AL extension settings and I couldn't find anything (makes sense now as to why)

**Comment by BrianThorChristensen** [comment]
Could you please make the action "Copy And Open" respect these settings when downloading symbols.

**Comment by dnpb** [comment]
You should open a new issue requesting that, as closed issues aren't tracked, especially if they're from 3 years ago ;-)
