### ISSUE TITLE
Actions in CardPart pages on the role center do not run in the tablet client

### ISSUE THREAD

**Issue by spapke** [Microsoft/AL#4341]
Actions in CardPart pages on the role center do not work in the tablet client. This occurs only for actions that are accessed from the vertical ellipsis button in the left sidebar. Note that this occurs for the native action "Set Up Cues".

When debugging, it appears that this code does not run at all. Attempting to break all in the debugger and then selecting the action does not appear to trigger any code.

1. Open the Role Center in the tablet client as a Sales Order Processor role.
2. Open the menu from the vertical ellipsis button.
3. Attempt to run "Set Up Cues".
4. Note that code does not run.

![image](https://user-images.githubusercontent.com/29461382/49765993-fbd87000-fca1-11e8-9fed-91d9efaa8d9c.png)

 - AL Language: 2.0.56856
 - Business Central: US Dynamics NAV 13.1 (26323)

**Comment by atoader** [comment]
Hi @spapke ! Do you know if this still happens on the latest docker preview?

**Comment by spapke** [comment]
Hi @atoader, this does not occur on the latest preview build, US Dynamics NAV 14.0 (26608).

**Comment by atoader** [comment]
Thank you!

**Comment by kokkeonghow** [comment]
Actually, I currently have the same issue.
Within my docker container and also in the cloud at the customer (!!!).

The customer is using the Version DE Dynamics NAV 14.0 (32094) and  I am using the version US Dynamics NAV 14.0 (32248). So mine is a quite new version.

Can anyone help me with this one? Especially at the customers environment its not very smart.

Thank you,
KK

**Comment by atoader** [comment]
@kokkeonghow if you are still experiencing this issue please open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
