### ISSUE TITLE
while opening sand box from business central environment getting tenant issue

### ISSUE THREAD

**Issue by pacific2029** [Microsoft/AL#4342]
When i am trying to open sandbox environment i am getting below error.

![image](https://user-images.githubusercontent.com/45781694/49783234-1cf99900-fd54-11e8-9fff-4cdd082d360f.png)

**Comment by atoader** [comment]
Hi @pacific2029 ! Where are you opening the sandbox from? What are you clicking to open the sandbox?

**Comment by MortenRa** [comment]
I Experience the same error if I create a sandbox with production data, meaning if I push reset and also tried to create this from the admin site through CSP interface, it only works with cronus demo data

**Comment by atoader** [comment]
Hi! I have create a bug for this and I hope it will be addressed in the following week.

**Comment by MortenRa** [comment]
@atoader  It is now working for me again

**Comment by pacific2029** [comment]
@atoader  ya its working
