### ISSUE TITLE
AL0452: The type 'System.Xml.XmlNode' could not be found in assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

### ISSUE THREAD

**Issue by EmoHP** [Microsoft/AL#4345]
**Describe the bug**
I have a working solution with a lot of DotNet used. I declared over 15 DotNet types. All works fine. Instaled to NAV thru VSCode. But when I change working folder of VSCode, I have the above error when I reopen the solution. Nothing helps except modify lookup path for DotNet in settings.
All good so far, but when I try to install .App file, I got the same error. And I don't want to install VScode on Customer's server as a workaround solution. Except this particular error, all other DotNet do not create random compilation problems.

**To Reproduce**
Just use this DotNet - System.Xml.XmlNode. I've never tried a clean project, but obviously it's a BUG.

**Expected behavior**
No compile errors. I cannot use build-in XML handling as it's a converted solution with a lot of DotNet as parameters.

**Versions:**

 - AL Langauge: 2.0.43900

 - Business Central: IT Dynamics NAV 13.0 (24630)
(also tested on IT Dynamics NAV 13.1 (25940))

**Comment by atoader** [comment]
Hi, @EmoHP ! 
The AL Language extension, including the AL compiler, and the server to which you publish your code are completely decoupled. When publishing, the server recompiles your code and tries to resolve all the references to external assemblies. In order for the compilation to succeed, the server must be able to locate and load all the referenced assemblies and types.
To make the paragraph above more concrete:
1. In VSCode, you must set the assemblyProbingPaths to point to the folder(s) containing the assemblies that you will use.
2. The server must contain, in the Add-Ins folder, the assemblies that you will use. In the 13.0 and 13.1, the server only searches the Add-Ins folder, the Temp Add-Ins folder and the Add-Ins table. It does not search the GAC. You should be able to get around this by creating a symbolic link to the GAC folder from the Add-Ins folder.

If you have done this and you are still encountering issues, we should try to narrow it down. We are also using System.Xml.XmlNode in the standard application and it is compiling and publishing fine.

**Comment by EmoHP** [comment]
Hi, atoader !
1. I know. My paths are as follows:
"al.assemblyProbingPaths": [
        "./.netpackages",
        "C:/windows/assembly",
        "C:/Program Files/Microsoft Dynamics 365 Business Central/130/Service/Add-ins"
    ]
Changing this list (for example adding "C:/Temp") temporary resolves the problem and I'm able to compile, but after loading another folder (only close and open VS Code does not bring the error) and then reopen my project's folder brings the error again. On the customer's server I got the same error only about this assembly. I cannot workaround on their server as I don't have VS Code, so I'm not able to change the settings file (which maybe forces the compiler to refresh). But I must notice I use many more defined DotNet types, which doesn't make any issues. An interesting fact is that I installed successfully the extension locally on the test DB (where the VS Code is located), just after successful compile, but this from VS Code. I tried in local test DB to install manually by .App file just to see the same error. Only from VS Code install is possible.
2. Symbolic link didn't help. I left only Add-ins folder. I saw errors for many DotNet types. After creating the link and I reopened the folder I see the error only for XML.

**Comment by EmoHP** [comment]
I attached a test project with only DotNet definitions that results in the same compile problem.
[AL Solution - Copy.zip](https://github.com/Microsoft/AL/files/2671299/AL.Solution.-.Copy.zip)

**Comment by atoader** [comment]
Thanks! I can reproduce it locally.

**Comment by atoader** [comment]
Does this work?
[AL Solution - Copy.zip](https://github.com/Microsoft/AL/files/2672132/AL.Solution.-.Copy.zip)

**Comment by EmoHP** [comment]
No. It compiles and somehow it completely solved the issue on the local test server, probably because of the parameters or the order of type declarations. But I get the same error when I try to install the new .App file on the customer's server. I don't get the error any more with the OLD .App file on the local. I suspect it's some kind of declaration order/assembly cache bug.

**Comment by atoader** [comment]
A bit more context:
- You should always specify the Version of the assembly, at least the major version. Otherwise, the compiler will pick whatever it thinks is the best match, which, depending on many other factors, might be version 2.0.
- System.Xml.XmlNode is part of the System.Xml assembly . 

Have you restarted the server before publishing the version I sent you?

**Comment by EmoHP** [comment]
No. But I cannot do that, and it's not applicable as:
1. Local did not need restart. Your version is actually the same, except properties un-commented and order is changed. I should mention that XML is present in System assembly, too as it worked.
2. Customer's server does not have anything installed of the old app. It just shows the error as the local server. Successful compile in VS Code in the local server made possible to manually install the old (problematic) .App file on it. But before that compile it was not possible.
3. I made the same symbolic link on the customer's server. No change. And the problem is always and only limited to this XML assembly.

**Comment by atoader** [comment]
When you compile in VSCode, the compiler verifies that it can locate all the .NET assemblies and resolve all the references. After this process is completed, it creates an app file containing your AL files. This app file is sent to the server where the AL files are recompiled in the server's context. If the server's context is missing some references, the compilation will fail and you will not be able to publish.
