### ISSUE TITLE
Intermittent issue when selecting a file - file is not uploaded

### ISSUE THREAD

**Issue by craigbarberini-theta** [Microsoft/AL#4347]
**Describe the bug**
I have found an intermittent issue when selecting a file in business central. When browsing to select a file, the file does not get uploaded. 
This was initially experienced on an extension but I have had the same issue when uploading a .app file.

**To Reproduce**
1. Go to Extensions
2. Select action "Upload Extension".
3. Select the .app file and click choose.
4. Browse to the .app file and select it.
5. The filename is not shown in the field.

Note: this issue is intermittent. I am not sure what conditions cause it but I can confirm that if I close the browser and reopen it, then I am normally able to select the file.

I have used the extensions as an example but I think this relates to uploading the file rather than extensions specifically.

**Expected behavior**
If I choose a file it should be uploaded. If for any reason it can't be uploaded we should receive a message.

**Versions:**
 - Business Central: NZ Dynamics NAV 13.0 (25789)

**Comment by atoader** [comment]
Hi @craigbarberini-theta ! Could you test this on the latest dev preview? Are you experiencing the same behavior? If you manage to reproduce it again, could you post a GIF of what is happening?
