### ISSUE TITLE
Remove the warning about OIOUBL prefix for "EAN No."

### ISSUE THREAD

**Issue by BrianThorChristensen** [Microsoft/AL#4353]
**Is your feature request related to a problem? Please describe.**
It is quite annoying to see alot of problems because the compiler has an incorrect warning.

**Describe the solution you'd like**
Please remove the compiler warning about using the OIOUBL prefix for the "EAN No." field because no such field exists.

**Additional context**
Also, the warning should not show up if I create a field called "OIOUBL Account Code" on my own table.

The warning message is:
Field 'EAN No.' is marked for removal. Reason: Moved to OIOUBL extension, the same table, same field name prefixed with OIOUBL-.

**Comment by atoader** [comment]
Hi! Can you post a screenshot with the problem? The code shows the expected errors in my environment.

**Comment by BrianThorChristensen** [comment]
<img width="787" alt="dmp" src="https://user-images.githubusercontent.com/31523525/50001595-a5b74580-ff9d-11e8-807c-efb1833fc2e2.PNG">

**Comment by atoader** [comment]
Hi @BrianThorChristensen ! You are right, the field is not present in the latest version of the extension, but you might have symbols for an older version of the extension which still contain the "EAN No." field. The warning is valid in all the cases you've shown here. Make sure you are using the latest developer preview, delete the symbols in your .alpackages folder, and download them from the new server.
