### ISSUE TITLE
"opaque" is missing during use Digest Web request. 

### ISSUE THREAD

**Issue by RuiningFan** [Microsoft/AL#4355]
Hi experts,
When I set up a Nav server environment in a VM and set authentication method as "UserName". When I send the web request, the server respond with
 "Digest qop="auth",algorithm=MD5-sess,nonce="+Upgraded+v1bf662ec1815d6f6752d81038323ceca171e594efd392d4013f5ecd15009e16908d175b053a8741d44c753dc755b14022819a3c9b25366fc7",charset=utf-8,realm="Digest""

However, there is no "opaque" in the response, and I tried resend the request based on "Digest" rule both in my code and postman. Always return 401 Unauthorized error. Is that caused by missing "opaque" or I have some steps missing? 
Thank in advance.

**Comment by atoader** [comment]
Hi! Thank you for opening this issue. This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
