### ISSUE TITLE
Enable getting selected row(s) on subpage from main page

### ISSUE THREAD

**Issue by eaathan** [Microsoft/AL#4357]
When you create a page that contains a Page Part list you're unable to get the selected row from the main page.

```
currpage.Somepage.Page.GetRecord(currRec); //=> Not working you'll always get the first row
currpage.Somepage.Page.SetSelectionFilter(currRec); //=> Not working you'll always get the first row
currpage.Somepage.Page.OwnMethodThatSetsCurrRecEqualsRec(currRec); //=> Not working you'll always get the first row

```
It's a very strange behavior because it sub page does know which row it's on. if from the sub part the same action is executed the result is the selected.

Anyways. It would be a nice improvement.

**Comment by atoader** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resource [Business Central - Ideas](http://aka.ms/bcideas) . This GitHub repository handles issues with the latest developer preview.

If would would like to find a workaround, you can post your question to the following resources: 
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
