### ISSUE TITLE
Error on Report 10411 Check (Stub/Check/Stub) when converted to AL

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#4359]
**Describe the bug**
Error on Report 10411 Check (Stub/Check/Stub) when converted to AL
Microsoft Dynamics NAV
---------------------------

The SourceExpr for report control 'PrnChkCheckAmountText_CheckStyle__US_' is not valid. The following error occurred: Index out of bounds.
---------------------------
OK
---------------------------

**To Reproduce**
Convert the check to AL and publish it. Try to print a report from the payments journal

**Expected behavior**
Print the check

**Screenshots**

**Versions:**

 - AL Langauge: 0.12.28462

 - Business Central: US Dynamics NAV 11.0 (24232)

**Comment by atoader** [comment]
Hi @andrecavalcanti! Thank you for reporting this issue! As this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
