### ISSUE TITLE
ShowMandatory don't show red asterisk on a Enum based Primary Key

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4362]
**Describe the bug**
I have a Primary Key based on a custom Enum and when I set **ShowMandatory = true** under the Page field, Business Central don't show the red asterisk for this field but for other field types this works OK.

**To Reproduce**
The Enum is like this:

```php
enum 50000 "MyEnum"
{
    Extensible = false;

    value(0; _) { Caption = ' '; }
    value(10; Value1) { Caption = 'Value 1'; }
}
```

**Expected behavior**
The red asterisk should be visible unless the User selects a non-zero enum value.

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/50047593-9bd63500-00b8-11e9-9f22-1450da0b7747.png)

**Versions:**
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by atoader** [comment]
Hi @JavierFuentes ! Have you set the BlankZero property? https://community.dynamics.com/nav/f/34/t/177754
It works fine for me:
![image](https://user-images.githubusercontent.com/3097909/50079743-ba3c4d80-01ea-11e9-9a9a-f637c3d5eb84.png)
There are several blog posts around about this property detailing the different options that you need to set depending on the context.

**Comment by JavierFuentes** [comment]
Hi @atoader,
**please don't close my Issues until I can answer your suggestions or messages**... we only can evaluate Business Central new development paradigm on week-ends... thank you...

I will test this week-end, but I opened another issue ([4323](https://github.com/Microsoft/AL/issues/4323)) because I can't set NotBlank = true on Enum fields at Table level...

Do you refer to set this at Page level?

Thanks again for your help & patience.

**Comment by atoader** [comment]
Hi! I set the property on the page field. I will post my code later today. Make sure you are using the latest development preview or at least the latest CU so that you do not encounter bugs we have fixed already.

**Comment by atoader** [comment]
@JavierFuentes does it reproduce on the latest CU?

**Comment by atoader** [comment]
@JavierFuentes I apologize for not seeing your question about how to install the latest CU. Unfortunately, I am not familiar with this process. I think you might be able to find more information on: 
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Before posting a question there, make sure you check our docs. For example: https://support.microsoft.com/en-us/help/4072484/how-to-install-a-microsoft-dynamics-nav-2018-cumulative-update

**Comment by atoader** [comment]
@JavierFuentes here's the sample code I promised: 
```
enum 50100 MyEnum
{
    Extensible = true;

    value(0; MyValue)
    {
    }

    value(1; MyOtherValue)
    {
    }
}

table 50100 MyTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; PK; enum MyEnum)
        {
            DataClassification = ToBeClassified;
        }

        field(2; SK; enum MyEnum)
        {
            DataClassification = ToBeClassified;
        }
    }
}

page 50100 MyPage
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = MyTable;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(PK; PK)
                {
                    ApplicationArea = All;
                    BlankZero = true;
                    ShowMandatory = true;
                }

                field(SK; SK)
                {
                    ApplicationArea = All;
                    BlankZero = true;
                    ShowMandatory = true;
                }
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/3097909/50585468-69c52100-0e75-11e9-9344-b2c95046a558.png)

**Comment by atoader** [comment]
@JavierFuentes can I close this issue? Do you have any other questions?

**Comment by JavierFuentes** [comment]
Hi @atoader,
I regret not having answered before... yes, I think that if this problem is solved in the next versions this issue can be closed. 

Thank you very much for your help.

**Comment by qutreson** [comment]
Closing this issue as we believe it has been fixed. If you are still able to reproduce it on the latest version of Business Central, please create a new issue
