### ISSUE TITLE
Zero data-lost risk on deployments needed: decouple TableData Object from Table Object

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4363]
### The Problem
We are a final customer with internal development team and we are evaluating the migration to Business Central OnPremise of our own Solution with thousands of objects created or customized and the simple idea of ​​losing data in any deployment makes us sleepless.

Another important factor is how long the daily deployments of patches and evolutives will require (increasing with the years) since, unlike until now, with the Extensions, **each deploy includes ALL the code** and not only the Modified Objects in each case (many times, only 1 or 2).

We have thought about creating **a first Extension for the Data** (with Tables, TableExt, Enums & EnumExt) **and another Extension for the rest of the UI** (with any other type of Object) that depends on the first ...

The _**first problem**_ with which we find ourselves is that, **the Pages for the Lookup and DrillDown are defined by Properties in the Tables**, so that this would generate circular dependencies with the second Extension.

_**Another problem**_ is **the code at the level of Table Triggers**, which could never reference any other type of object such as Codeunits, Reports or Pages since it would also generate circular dependencies with the second Extension.

We are attracted by the idea of ​​being able to version our code, work with GIT and reduce Upgrade efforts, but I hope that Microsoft will look for solutions for the OnPremise developments on Business Central because right now seems there are many more disadvantages than advantages in Extensions model for OnPremises scenarios like ours.

### Describe the solution you'd like
We believe that in order to enable a model of "binary" extensions in which the structure of the tables can be defined and deployed separately from the rest of the development objects, it could be a good solution to **define new types of _TableData_ and _TableDataExt_ objects** that only allow to declare the physical fields and types (those that will be created in SQL Server).

A third **type of _TableDataDiff_ object** could be used **to force physical changes in the structure of both the standard and custom tables** at the level of the Database and would be of only-one execution per each environment... Some things they could provide are:

- Reduce field lengths (only those declared under the same extension if you want)
- Delete fields once they have no data in any Company 
- Change the Primary Key
- Make a TableData, standard or new, Common to all Companies if it only has data in 1 Company.

From there, **the Objects of type _Table_ and _TableExt_ could support the declaration of non-physical fields only, such as the _FlowFields_ and the _FlowFilters_ together with the Triggers and the code** they need and because they are framed under the second Extension that depends on the first , they would have **access to everything as they are now**, even to properties like _LookupPageId_ and _DrillDownPageId_ that in AL can not be reproduced by code with the same effectiveness.

It would also be important **to be able to generate a file with extension _.appdiff_ that only contains the objects with differences between the project code and the server code** so that the differential deploys were faster and not that each time it was taking more and more time.

**Versions**:
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by atoader** [comment]
Hi @JavierFuentes ! Thank you for providing this feedback! I have a few questions so that I can better understand your concerns:
- Why would you lose data during deployments? Could you give an example for a series of events that could lead to this?
- Are you facing issues deploying upgrades right now? We are actively working on improving the performance of this scenario and it is of high priority for us to make upgrades fast and issue free. 

In general, we recommend that you create your extensions around areas of functionality. For example: one extension for inventory management, one extension for accounting etc. An extension should include all the extension objects it needs including tables and pages. 
This is how Microsoft is developing its extension and it is the scenario that will receive the most improvements. Alignment in this area will ensure that you benefit from all the work we are doing.

I encourage you to watch our keynote from TechDays: https://www.youtube.com/watch?v=qVu0XK7T4Uk .

Feel free to also reach out to: 
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

to get suggestions on patterns and deployment models that work today.

**Comment by JavierFuentes** [comment]
Hi @atoader,
the problems that we are having when making the deployments on our OnPremise server are somewhat random and we are not able to say under what conditions they occur (except for some specific cases that we have been able to report) ...

The issue is that under many circumstances, for the deploy to work, **we are forced to use schemaUpdateMode: "recreate" which is not even valid for a QA environment** where we have all the settings and customizations with which to test well the changes before installing them in the PROD environment.

**In our scenario, in which WE MAKE CHANGES EVERY DAY** to correct bugs, to implement new functionalities or to change the behavior of the program at the request of our business users, separating our code into several extensions is not at all agile and supposes a surplus effort at the time of development to keep the changes synchronized between all those extensions...

On the other hand, we estimate that **in the day to day (after the Project stabilization phase), 75% of the changes we make do NOT affect the structure of the tables, but only the code** (reports, codeunits, pages, etc), so we think a project workspace model with 2 projects, one for tabledata structure and another one for the rest of the object types, can reduce de data lost risk because 75% of the times we only make modifications and deploy the second project that has not any changes in tabledata structures... this guarantee us that tables will never been touched in this type of deployments...

The other 25% of times that tabledata structures need to be modified, we can focus on do it independently and with less deployment/re-deployment cicles on every environment...

In other technologies like Java, .NET, Javascript, Typescript, etc data structures are managed separately from source code... 

I think this aproach is more secure to avoid data lost.

The aproach of having many-more small-extensions is valid only for Partners developing Apps for the Store and must not make changes ALL DAYS with live data, but this is a totally different scenario than OnPremises software manteinance.

**In this scenario Data is Gold!**

Please, consider improve this scenario because **final customers like us, don't have unlimited tables, pages, codeunits, etc... only licensed and payed ones**...

We don't have range numbers dedicated to TEST our developments or to develop little batch process to fix amounts of erroneous data when something was wrong...

**We need too the same flexibility on changing tabledata structures we have now with Navision** (to reduce field lenght, to change the type of an empty field, to change the primary key of a table, to make standard tables shared, to drop empty unnused custom tables, etc)

**Comment by qutreson** [comment]
Thank you for your perspectives on how to structure AL code. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product, we recommend that you post your suggestions on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
