### ISSUE TITLE
I would like to decide in app.json where my compiled .app file will be generated

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4364]
### Suggestion
If you see [my suggestion 4363](https://github.com/Microsoft/AL/issues/4363), I propose **a workspace model based on binary projects of extensions (Data + UI)** for OnPremises maintenance scenarios reducing the times physical schema is syncronized (or recreated).

In this context, it would be desirable to be able to indicate in `app.json` file of the _Data-Project_ the route in which to automatically generate the `.app` file with the definition of Symbols so that it could be the folder `.alpackages` of the _UI-Project_. 

![image](https://user-images.githubusercontent.com/5801847/50054245-2f067d80-0140-11e9-9e0e-30b0f4b5b9f9.png)

**Comment by atoader** [comment]
Hi @JavierFuentes ! You could create your own extension for VSCode that supports this. https://code.visualstudio.com/docs/extensions/developing-extensions

**Comment by JavierFuentes** [comment]
Hello @atoader,
I'm sure I could spend time learning how to develop my own Visual Studio Code extensions, but right now I do not have much time to do something that I can solve with a simple .BAT file

I think my suggestion should not be so strange when most development environments generate their compiled in a subfolder and not in the root of the project ... also knowing that we actually can define the path for the rules file of the codeAnalyzers, for the logo or the screenshots for example.

**Comment by atoader** [comment]
Hi @JavierFuentes ! I've marked this issue as a suggestion and we will consider it when planning our development for the next releases. We have a large number of suggestions for improvement and it might take time until we get to implement your request.

**Comment by JavierFuentes** [comment]
Hello again @atoader,
I've just read this entry about [Working with multiple AL project folders within one workspace](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-multiroot-workspaces) and discover that exists a parameter `al.packageCachePath` we can configure in our `.code-workspace` file to share `.app` symbol files between all Extension Projects inside the same Workspace...

I've just tested and VSCode downloads my `DATA_Extension.app` symbols file to this folder from my OnPremise Server :-), so at this point, **I think, ALL `.app` compilation files generated from any project of my workspace should be generated at this route too by default**...

This guarantee I always have all my latest data-symbols changes in `DATA_Extension` available for the other `UI_Extension` after every `Package (Ctrl+Shift+B)` execution and wihout downloading it all (including the 2 standard of +6MB files) every time...

**Comment by RafaelKoch** [comment]
@atoader : I think this should be either classified as a bug or a good workaround provided. 

We are working with a workspace and use a central folder for AL packages just as @JavierFuentes does. The setting looks like this

```json
"al.packageCachePath": "./../.alpackages"
```
and is working fine for downloaded symbols.

Now, why is it problematic as it is today: One uses a workspace mainly to work on multiple extensions at the same time and when these have dependencies one needs to compile and have all packages somewhere central to be able to develop on dependend extensions.

Stuff that goes wrong:
+ conflict between package file in cache path and one generated in the extension root
+ clicking party to collect all packages from multiple roots

Suggested resolution:
+ make AL:Package aware of the setting
+ or alternatively add another setting and use that one

**Comment by atoader** [comment]
Please try the latest development preview and check out the improvements we've made around working with multiple projects: https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/improved-app-dependency-handling-build-deploy

**Comment by RafaelKoch** [comment]
You are pointing towards an improvement that manages the compilation and installation of multiple apps in the correct order. Very useful and we can then discard our own custom scripts we use for that purpose. 
YET this has nothing to do with this issue, which is about the correct place where compiled packages should go.

**Comment by JavierFuentes** [comment]
I am totally agree with @RafaelKoch... Latest deploy improvements doesn't seem to solve this need...

**Comment by kalberes** [comment]
@RafaelKoch 

There is way more then what is described there.
In the Fall release there will be support for project references. Though this concept will bear no user semantics. Anything that exists in a workspace that is also described as a dependency will be treated as a project reference 
Symbols will be resolved from a project reference for the diagnostic service. And an app for a project if built will be copied to the package cache folder of all other projects that depend on it, though strictly speaking resolution may not need it.

**Comment by RafaelKoch** [comment]
@kalberes 

Thanks for clarifying - and yes: that sounds more like it. I am curious to see that project reference at work but from Your explanation it sounds like this will be what this thread is about. Maybe it would be a good idea to have @edupont04 include this piece into the Wave 2 announcement content - I guess more people are looking for improvement here and may be excited to know.

**Comment by edupont04** [comment]
@pborring owns the release plan.

**Comment by thpeder** [comment]
Hi,
I believe this has been added to the tools.
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/set-new-output-folder-setting-storing-app-files-at-al-project-build

If you have more ideas, please go ahead and post it to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up other ideas. We're constantly monitoring top Ideas and will consider them for a future release.
