### ISSUE TITLE
Bin code is not on Sales Order Subform

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4369]
Hi All,

I am developing a simple extension for extending the **Sales Order Subform** page to make **Bin Code** field to be available on line. So problem is that, when I am selecting this field in AL, its giving me error, that "A member with name Bin Code already defined".
![image](https://user-images.githubusercontent.com/33481576/50106216-34a1b780-0255-11e9-9a11-ab438a74df07.png)

However I am pretty sure, that I haven't published any extension to fulfill this need on my tenant,
I also noticed that there is a field in very last in Sales Order Line with blank caption. Is it bin code?
![image](https://user-images.githubusercontent.com/33481576/50106287-74689f00-0255-11e9-91c1-94574bcd1a5f.png)

Please help me out

Regards
Sudarshan

**Comment by atoader** [comment]
If you set your cursor on the "Sales Order Subform" and press F12, you will see the definition of the page and you will see that a Bin Code field already exists. You could also open the page in C/SIDE. 
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

In the future, please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by SUD-D365** [comment]
Hi @atoader 

Thanks for your prompt revert!
I know its already placed on "Sales Order Subform", but I am not able to see this on Sales Line in a Sales Order, Like I attached a screenshot of Sales Line.

Please Help
