### ISSUE TITLE
Publisher Event Local 

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#4372]
The Event-Publisher Snippets (Business & Integration) create a local procedure. That seems to be okay because the documentation says it should be local (see 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publishing-events Step 2) 

I tried creating two dependent extensions, the first one with a local Event Publisher and the second with a subscriber to the first Publisher. The subscriber didn't know the Event, so I changed it to a global procedure in Ext1, now it works. 

Could you please verify whether a Publisher Event Needs to be local or global?

**Comment by qutreson** [comment]
Hi @JulianTillmann, 

You can have an event that is local or not depending on who you want to be allowed to publish the event. If you want your event to be only published from the object where it is defined, you should use local. If you want to be able to publish the event from another object, then it should not be local.

```
page 50100 TestPage
{
    [BusinessEvent(true)]
    local procedure LocalEvent()
    begin
    end;

    [BusinessEvent(true)]
    procedure NotLocalEvent()
    begin
    end;
}

codeunit 50100 MyCodeunit
{
    // Subscribing to events

    [EventSubscriber(ObjectType::Page, Page::TestPage, 'LocalEvent', '', true, true)]
    local procedure LocalSubscriber()
    begin
    end;

    [EventSubscriber(ObjectType::Page, Page::TestPage, 'NotLocalEvent', '', true, true)]
    local procedure NotLocalSubscriber()
    begin
    end;

    // Publishing events

    trigger OnRun()
    var
        p: Page TestPage;
    begin
        p.NotLocalEvent();
        p.LocalEvent(); // [AL] 'LocalEvent()' is inaccessible due to its protection level [AL1061]
    end;
}
```

**Comment by JulianTillmann** [comment]
hmm, what's the Scenario of using an Event ionly inside the same object? why wouldn't I just call a procedure?

**Comment by qutreson** [comment]
When you call the event `p.NotLocalEvent`, it raises the event and all the event subscribers (like `NotLocalSubscriber` above) are run. The event publisher being local or not does not matter for event subscribers as they get all run.

**Comment by qutreson** [comment]
In the documentation, I think the sentence `If you do not want to make the event available to event subscribers, make it a local method by affixing it with local.` is not correct. It should be something like `If you do not the event to be raised by other objects than the one declare it, make it a local method by affixing it with local`.

**Comment by JulianTillmann** [comment]
I'm sorry, but the local Publisher did matter in my Case, as explained above.

**Comment by qutreson** [comment]
Which version of the AL extension are you using?
Can you please copy here some snippet of what you are doing? Including the event publisher, the event raiser and the event subscriber?

**Comment by JulianTillmann** [comment]
I'm using AL 2.0.56865 

**Event Subscriber**
>[EventSubscriber(ObjectType::Codeunit, Codeunit::"Document Mgt. SDS", 'OnBeforeGetPreText', '', true, true)]
>local procedure RunOnBeforePreText(RecVar: Variant; var PreText: Record "Temp. Text Buffer SDS"; Handled: boolean)
>    begin
>        PreText.init();
>        PreText."Line No." := 10000;
>        PreText.Text := HELLO WORLD';
>        PreText.insert();
>    end;

**Event Publisher**
>    [IntegrationEvent(true, true)]
>    _**local**_ procedure OnBeforeGetPreText(RecVar: Variant; var PreText: Record "Temp. Text Buffer SDS"; var Handled: Boolean)
>    begin
>    end;

**Event Raiser**
>    procedure GetPreText(RecVar: Variant; var PreText: Record "Temp. Text Buffer SDS")
>    var
>        RecRef: RecordRef;
>        Handled: Boolean;
>    begin
>        OnBeforeGetPreText(RecVar, PreText, Handled);


the "local" in the Publisher was the Problem, I removed it. Re-Deployed the App, Downloaded the Symbols in the second app and voilà

**Comment by qutreson** [comment]
So the event publisher `OnBeforeGetPreText` is defined in the Codeunit `Document Mgt. SDS` is deployed in a first app. The event subscriber `RunOnBeforePreText` is defined in the second app. Where is the publisher defined?

What is the error you are getting when trying to use the event publisher? It is at compile time, publish time or a runtime error?
Is it similar to this: `The event 'OnBeforeGetPreText' is not found in the target?

**Comment by JulianTillmann** [comment]
Publisher & Raiser are in App1, Subscriber in App2. 

Yes it's similar to the error "The event 'OnBeforeGetPreText' is not found in the target [AL0280]"

**Comment by JulianTillmann** [comment]
@qutreson any News? 

I can't find an Explanation for Errors like 'AL0280' on Google. Is there a list somewhere in your documentation like the Cop-Errors?

**Comment by qutreson** [comment]
Hi @JulianTillmann, I haven't had time to look further into it yet, for now the work around might be for you to set it as public until we figure out what the issue is. We don't have a list of documentation for the AL compiler diagnostics. The one you are getting says that, for some reason, the event cannot be found inside of your project or its dependencies.

**Comment by qutreson** [comment]
Hi @JulianTillmann, are you still facing this issue when using our latest developer preview (version 15.x)?

**Comment by kalberes** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
