### ISSUE TITLE
Caption ML Property is missing for Enum Value

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/AL#4374]
**Describe the bug**
Caption ML Property is missing for Enum Value.

**To Reproduce**
Create a new Enum... See Screenshot

**Expected behavior**
Enum Value has a Property CaptionML

**Screenshots**
![image](https://user-images.githubusercontent.com/18051656/50146679-99402f00-02b4-11e9-95c8-6ef431e437f4.png)

**Versions:**

 - AL Langauge: 2.0.56865

 - Business Central: W1 13.0 (24630)

**Comment by OleTeichmann** [comment]
I think it is because the multilanguage syntax is being deprecated. You have to use the Caption property and XLIFF-Files.

**Comment by ChrisBlankDe** [comment]
>           I think it is because the multilanguage syntax is being deprecated. You have to use the Caption property and XLIFF-Files.

CaptionML will be still allowed in onPrem Deployments, they said at NAV TechDays:
![1](https://user-images.githubusercontent.com/18051656/50156852-204ed080-02d0-11e9-80a4-4ca103fc89ad.jpg)
