### ISSUE TITLE
Cannot upload the same Tenant Customization to more than 1 production Tenant

### ISSUE THREAD

**Issue by DmitryKatson** [microsoft/AL#4377]
Hi team,

Look, I have created Tenant customization, with 
- app id = guid1
- app name = app name 1
- publisher = publisher 1
- version = 1.0.0.0

Then i uploaded that to the Online Business Central Production Tenant A => Everything works fine.
Then i uploaded the same tenant customization (with the same id, publisher name, app name and a version) to the Online Business Central Production Tenant B => And I've got an error that the same version of this app is already exists!

So why is that? Is it a bug? Or this is by design?
Thanks.

P.S. Sorry if i created that in a wrong thread.

**Comment by atoader** [comment]
@dkatson how are you uploading the extension to the BC production tenant?

**Comment by dkatson** [comment]
Hi, Extension Management => Upload Extension

Dmitry

**Comment by JuricaB** [comment]
We are experiencing the same issue when deploying tenant customizations on production tenants. Is there any way to avoid or mitigate this issue?

**Comment by ligoendeavor** [comment]
This behavior has been explained on the BC Yammer group (https://www.yammer.com/dynamicsnavdev/threads/1168396130) and it's due to the 3 keys that must be unique for each extension and upload (and they must be unique over all tenants in a regional service):

a. Package ID (this is unique for every compilation of the extension)
b. App ID and Version
c. Name, Publisher, and Version

**Comment by JulienDecottignies** [comment]
Does this means that for two customers located in the same region (as West Europe) who want the same extension, we have to provide differents PackageId's ?
If I understood correctly, how will it work for an extension available in the market place ? Does this key "evolve" each time the extension is downloaded in a specific region ?

**Comment by dkatson** [comment]
Hi, no Package ID should be the same for 2 PTC if you want to upload it on 2 diff tenants.

Dmitry

**Comment by giann85** [comment]
this is a really terrible management !!! if I have many customers who need the same app, it is necessary to have a different project for each customer. If we have other apps that depend on each other, to which  to make updates ... you become crazy !!! Also it is not sure that changing only the app id the publication is successful! Can anyone has found a way to manage apps in a centralized way, and branch out the deployment based on the necessary tenants?

**Comment by dkatson** [comment]
Hi, read here 
https://community.dynamics.com/nav/b/katsonsnavblog/archive/2019/01/23/top-tips-and-tricks-on-how-to-create-per-tenant-extensions

Dmitry Katson,
MVP
 
My Blog
My Twitter
My LinkedIn

**Comment by thpeder** [comment]
We are aware of the issue but we don't have a good solution for it yet.
You are able to publish the extension for another tenant if you change the version number and I know it is just a workaround and not a solution to the problem.

**Comment by charlespockert** [comment]
This is a big issue for us and will be an issue for a lot of other developers. We really want to be able to write tools that we can deploy to multiple tenants, even if they aren't functionality the client themselves will use.

We have data import tools we use for implementation that we've converted to BC that help us mass apply templates. We've also created customisations that we've found multiple customers are interested in, but we aren't an ISV so we aren't putting these on the app store.

Being able to only publish these tools to a single tenant without having to bump the version numbers is frustrating to say the least!

**Comment by JuricaB** [comment]
Hi @charlespockert ,

We resolved these problems through changes in internal process. See here for details, it may help: https://funwithcside.wordpress.com/2019/05/03/versioning-per-tenant-extensions-using-github-releases/

Cheers
Jurica

**Comment by charlespockert** [comment]
@JuricaB so what the error is actually saying is that some differences between one package and another exist, and in fact you can deploy the same customisation across multiple tenants as long as you use the same build files from tenant to tenant.

I have no issue with this as we can just generate build artifacts or check in packaged versions (it's a shame that Azure DevOps doesn't have the same "releases" functionality as GitHub).

Going to give this a shot.

**Comment by charlespockert** [comment]
@JuricaB are you aware if the limitation on deployment extends to sandbox? e.g. if we deploy to sandbox, does this prevent us publishing a recompile of the same extension to a production tenant?

**Comment by JuricaB** [comment]
> @JuricaB are you aware if the limitation on deployment extends to sandbox? e.g. if we deploy to sandbox, does this prevent us publishing a recompile of the same extension to a production tenant?

I have not run into any such issues - so far! Maybe I have just been lucky?

**Comment by dkatson** [comment]
Vote [here](https://experience.dynamics.com/ideas/idea/?ideaid=32240752-691d-e911-9461-0003ff68d30d) to make this possible

**Comment by qutreson** [comment]
Closing this issue as it has been converted to an idea which was implemented a few releases ago. Thank you for the input.
