### ISSUE TITLE
Suggestion: Replace configuration mode - designer saves to profile + pagecustomizations

### ISSUE THREAD

**Issue by JuricaB** [Microsoft/AL#4378]
**Is your feature request related to a problem? Please describe.**
In RTC/on-premise, profile configuration was easily handled by consultants or even clients themselves.
Currently, the process of Profile Configuration in BC Cloud is quite manual and requires some development knowledge and tools. 

**Describe the solution you'd like**
Desired changes:
Enable functionality in Designer:
	- Parts hide/show/move
	- Actions hide/show/move
Enable saving changes from designer as profile + pagecustomization objects

Desired process:
1. Open designer in BC Sandbox, click "configuration mode"
2. Using visual designer in BC Sandbox, make changes to pages (fields,actions,parts)
3. When closing designer/saving changes, specify Profile Name and Description, and Role Center ID
4. Changes are saved and published as Extension which contains Profile configuration (e.g. profile object + pagecustomization objects)

- allow download of source code and F7 use from VSCode to grab source code, as in current Extensions

**Describe alternatives you've considered**
This is the current process, which is unwieldy and prone to errors:
1. Using visual designer in BC Sandbox, make changes to pages 
(NB:  currently designer has very limited functionality - only Fields appear to be fully supported; Parts you can remove but not add; Actions you can't change at all)
3. Closing designer saves the page changes as pageextension objects 
4. Download source code and copy to VSCode (or use F7 from VSCode)
5. In VS Code, manually convert all pageextension objects to pagecustomization objects
6. Create Profile object, manually add reference to each pagecustomization object
7. In VSCode, add changes which are not currently possible via designer (e.g. show Parts, show/hide Actions)
8. Publish profile as an extension

**Comment by atoader** [comment]
Hi @JuricaB ! Thank you very much for the input! I suggest that you also post it on the Dynamics 365 Ideas site. https://aka.ms/bcideas

I think the Ideas site is a better place for this suggestion because it will get better visibility and others might be able to vote on it. 

This blog post offers guidelines on where to submit different issues for Business Central: https://community.dynamics.com/business/b/financials/archive/2018/12/04/find-the-right-resources-and-provide-feedback

**Comment by JuricaB** [comment]
Thanks @atoader , I now posted to bcideas per your suggestion (see [here](https://experience.dynamics.com/ideas/idea/?ideaid=29bcb4bc-bf03-e911-9461-0003ff689eb8)).  

I posted here as my proposal would replace what is currently a development process. 

If you feel this is not the right venue, please close this issue.

**Comment by atoader** [comment]
Hi @JuricaB! I forgot to mention that you should check if the idea is already posted in another form. I think this proposal is pretty similar https://experience.dynamics.com/ideas/idea/?ideaid=b72077ad-2bd6-e811-b96f-0003ff68b04e . The ideas with the most votes have the highest chance of being implemented so you might want to add your votes to the existing idea.
