### ISSUE TITLE
[Event Request] new event on function VendPostApplyVendLedgEntry on Codeunit 227 “VendEntry-Apply Posted Entries”

### ISSUE THREAD

**Issue by mannavmej** [Microsoft/AL#4383]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

Hello, we need a new event on function VendPostApplyVendLedgEntry on Codeunit 227 “VendEntry-Apply Posted Entries”
OnBeforePostApplyVendLedgEntry(GenJnlLine,VendLedgEntry);
GenJnlPostLine.VendPostApplyVendLedgEntry(GenJnlLine,VendLedgEntry);

EntryNoAfterApplication := FindLastApplDtldVendLedgEntry;
IF EntryNoAfterApplication = EntryNoBeforeApplication THEN
 ERROR(NoEntriesAppliedErr,GenJnlLine.FIELDCAPTION("Applies-to ID"));

IF PreviewMode THEN
  GenJnlPostPreview.ThrowError;

COMMIT;
Window.CLOSE;
//NEW EVENT
OnAfterPostApplyVendLedgEntry(GenJnlLine,VendLedgEntry);
// NEW EVENT
UpdateAnalysisView.UpdateAll(0,TRUE);

with new publsiher:
[External] [IntegrationEvent] OnAfterPostApplyVendLedgEntry (VAR GenJnlLine: Record "Gen. Journal Line"; VAR VendLedgEntry: Record “Vendor Ledger Entry”)

**Comment by kalberes** [comment]
Please use the repo https://github.com/Microsoft/ALAppExtensions to request events.
