### ISSUE TITLE
The type or method 'Array' cannot be used for 'Extension ' development

### ISSUE THREAD

**Issue by EDGZTNSR** [Microsoft/AL#4384]
**Describe the bug**
In the Error Log I get the following messages:
![image](https://user-images.githubusercontent.com/39260158/50223628-1397ae80-039c-11e9-93fc-5b47e579f450.png)

I know I can only use External Functions and some restrictions to tables were made. But am I not able to use Arrays?

**Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.0.56865
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al: 

 Business Central: CH Dynamics NAV 13.1 (26678)

**Comment by atoader** [comment]
Can you please show where you are using that?

**Comment by EDGZTNSR** [comment]
The Problem was solved when I added the ```"target": "Extension"``` to the app.json.
I still think the Error Log is a bit confusing.
