### ISSUE TITLE
Virtual table call issue

### ISSUE THREAD

**Issue by abouraoui** [Microsoft/AL#4386]
I try to declare a RECORD var as WS: Record "Web Service", I keep getting this error
"The type or method 'Web Service' cannot be used for 'Extension' development. AL(AL0296)

![image](https://user-images.githubusercontent.com/45698976/50239354-f4931f80-038f-11e9-8660-baf68529b818.png)

Thanks.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
