### ISSUE TITLE
Table Extension Keys

### ISSUE THREAD

**Issue by RickTweede** [Microsoft/AL#4388]
Creating a table extension should allow new keys to be created utilizing the extended tables fields and not just the extensions fields.

I.e. create an extension to the Item Ledger Entry table to add a new field "Qty. (Weight)" (i.e. for weighted items sold in cases but we need to record the weight as well (steaks sold by the case but priced by the LB so need the weight)).

Without being able to create a key i.e. "Item No.", "Qty. (Weight)" you cannot quickly pull data from the table for use in reports/pages..... 
Adding keys using the base table fields is a fairly fundamental gap (i noticed another issue was closed on this already but this is a major issue for anyone wanting to build anything remotely useful in D365).

The only alternate is to replicate all of the fields you need from the original table to your extension.
i.e. in the extension table have a field called "Item No. Copy" so that you create a key on "item no. copy", "qty. Weight"
BUT then you have the overhead of duplicating data, and having to ensure it is kept in sync with the original table.

**Comment by atoader** [comment]
Hi @RickTweede ! Thank you for opening this issue! We are fully aware of the problem and we are trying to provide viable alternatives. Please see #730 for more information.
