### ISSUE TITLE
"al.enableCodeAnalysis" ignores target:"Internal" in app.json

### ISSUE THREAD

**Issue by ArthurSchwarz95** [microsoft/AL#4390]
If "al.enableCodeAnalysis" is set to true in the settings.json the target:"Internal" in app.json is ignored.

![al enablecodeanalysis](https://user-images.githubusercontent.com/45875517/50273993-64f77a80-043c-11e9-8606-2e12d10a07e3.png)

I get different warnings that are assuming I want to publish on cloud, e.g. that the ApplicationArea property does not have a value. But I want to publish on-prem. 

If I add a code analyzer to the "al.enableCodeAnalysis" it works just fine, e.g.:

![al enablecodeanalysis_with_al codeanalyzers](https://user-images.githubusercontent.com/45875517/50231543-53b45c80-03af-11e9-8096-4f6611582c8d.png)

AL Language Version: 2.0.56865
Business Central: DE Dynamics NAV 13.1 (25940)

**Comment by atoader** [comment]
Hi @ArthurSchwarz95! Please read this article and the related ones: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool . The Internal target and the code analysis do not have any influence on each other. If you want to change a diagnostic, you need to use a ruleset.
