### ISSUE TITLE
New function for FieldRef: DataClassification :=   FieldRef.DataClassification()

### ISSUE THREAD

**Issue by louagej** [microsoft/AL#4392]
**Feature request for GDPR general improvement**
This is not an issue but an improvement for more general GDPR functionality

**Access DataClassification with AL**
Like there is already `Class :=   FieldRef.Class()`
returning the fields class I would like a function to be added to the FieldRef data Data Type, e.g.:
`DataClassification :=   FieldRef.DataClassification()`
`Return Value:`
` -   DataClassification`
` -   CustomerContent`
` -   EndUserIdentificationInformation`
` -   AccountData`
` -   EndUsePseudonymousIdentifiers`
` -   OrganizationIdentifiableInformation`
` -   SystemMetadata`
` -   ToBeClassified`

This makes it possible to take customer specific actions on fields that have a special DataClassification
:alembic:
https://eugdpr.org/

**Comment by atoader** [comment]
Thank you for the suggestion @louagej !

**Comment by louagej** [comment]
> Thank you for the suggestion @louagej !

Can you please take following with you in case this should get developed in the future...
### GDPR compliance for governmental solutions
In order for us to get our solution certified by our government, we need to be able to monitor and audit who's performing CRUD operations on classified data.
In Business Central, we're currently not able to do so because of above mentioned feature.

### This is what we already tried
1. Adding SQL Data Discovery and Classification
    ![2019_01_11_000](https://user-images.githubusercontent.com/7229592/51024802-ce296400-158a-11e9-95da-9ef887c54fd8.png)

2. Creating a SQL Audit
    ![2019_01_11_001](https://user-images.githubusercontent.com/7229592/51024833-d84b6280-158a-11e9-8157-7d56efa4d988.png)

3. Creating a SQL Database Audit Specification
   In this step, we can for example specify that all selects on the Customer object should be logged
    ![2019_01_11_002](https://user-images.githubusercontent.com/7229592/51024862-e8fbd880-158a-11e9-8971-a1a07f415e05.png)
    ![2019_01_11_003](https://user-images.githubusercontent.com/7229592/51024872-edc08c80-158a-11e9-9e28-14de719e33f6.png)

4. Activate the Audit and Database Audit Specification

### Problems
1. SQL Auditing logs every read, not only the data that is classified as Highly Confidential – GDPR, Highly Confidential,Confidential – GDPR, Confidential, General, Public
2. Business Central DataClassification is not the same as SQL Data Classification (is this for a specific reason?)
3. Looking into the Log, you can see that the log is filled with a SQL Statement from Business Central but is working with **@local_variable** instead of the real values from the selection. This way it's not possible to monitor who read specific data.
   ```sql
    SELECT TOP (1) ISNULL("Customer"."timestamp",@0) AS "timestamp",
        ISNULL("Customer"."No_",@1) AS "No_",
        ISNULL("Customer"."Name",@2) AS "Name",
        ...
        ...
    FROM "BC_Demo".dbo."CRONUS BELGIË NV$Customer" AS "Customer" WITH(READUNCOMMITTED) OUTER APPLY
        ...
        ...
    WHERE (ISNULL("Customer"."No_",@1)<@12)
    ORDER BY "No_" DESC OPTION(OPTIMIZE
                            FOR UNKNOWN, FAST 50)
   ```
![2019_01_11_005](https://user-images.githubusercontent.com/7229592/51025240-c6b68a80-158b-11e9-9241-5a0086218433.png)

4. In comparison to a Microsoft SQL Server Management Studio - Query, you can see the real values in the select statement:
   ```sql
    SELECT [Name],
        [Address],
        [City],
        [Phone No_]
    FROM [BC_Demo].[dbo].[CRONUS BELGIË NV$Customer]
    WHERE [No_] = '01905902'
   ```
    ![2019_01_11_004](https://user-images.githubusercontent.com/7229592/51025237-c28a6d00-158b-11e9-890b-0ec9c796b34b.png)

5. The Username inserted when the log is filled from Business Central is the Name of the machine where the service is running on... not the username
    ![image](https://user-images.githubusercontent.com/7229592/51025270-de8e0e80-158b-11e9-8f12-a3dd32c524cb.png)

6. A List Page View Is even more difficult as it statement starts with:
   ```sql
    SELECT TOP (50) ISNULL("Customer"."timestamp",@1) AS
   ```

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

As this issue appears to require changes across multiple areas of our product and the runtime, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.

We are constantly monitoring top ideas and will consider them for a future release.
