### ISSUE TITLE
FieldGroups - All tables need default DropDown FieldGroup

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#4393]
It is not possible to extend a `FieldGroup `without it already existing.  E.g. the Item Variant (5401) table has no DropDown FieldGroup so I can't add any field from a tableextension to the default dropdown in a lookup.  It defaults to just Description.

**Comment by JesperSchulz** [comment]
This is better to be implemented on compiler level than on application tables. Transferring to al repo.

**Comment by atoader** [comment]
Hi @GreatScott000 ! This is not currently possible. We will consider it for our backlog.

**Comment by tinfister** [comment]
Any info regarding this issue? Is it planned to be changed? Any ETA or maybe a workaround?

**Comment by update-jeremy** [comment]
This is still an issue.  

Either add default DropDown and Brick fieldgroups to all base tables or change the TableExtension object to allow us to create it.  

Either will suffice, but right now, it's just a hard stop.   We also can't change LookupPageID, so we're very stuck here.

**Comment by Update-ABS** [comment]
I can understand why you may not be able to add fieldgroups with mixed base/extension fields, but I do not understand the underlying reasons why we can't specify fieldgroups with all base fields, or all extension fields.  Likewise with the lookuppageID.  This is a very difficult restriction to work with.

**Comment by radovandokic** [comment]
Any ETA or maybe a workaround?

**Comment by atoader** [comment]
Thank you the input! We have had a lot of great suggestions from the community and we have tried our best to prioritize the most important ones for the Fall release. Unfortunately, this did not fit in. It would be of great help if you could post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will allow us to better prioritize the issue for a future release.

**Comment by AbsolutelyFreeWeb** [comment]
@atoader @JesperSchulz this is something that was possible before, and is now lacking functionality. Without giving us a work around, why do you not treat it as a bug rather than a would be enhancement ?

**Comment by update-jeremy** [comment]
@JesperSchulz @atoader  - Hey, when the Fall release comes out as pure AL code, could the community do one massive pull request with default DropDown and Brick fieldgroups to all the objects that are missing them?  From what I understand, the base app will be in GH, so we should be able to get this done where you cannot, yes?  (That's not criticism - we just need this fixed.)

**Comment by JesperSchulz** [comment]
I'm afraid we will not be publishing the BaseApp on GitHub - at least not now. What we _are_ publishing, are the modules and add-on extensions we extract out of the BaseApp one by one. The reason for not publishing the BaseApp is that we would be struggling to keep up with the inflow of pull requests, as we know that many partners have many great ideas - but not all of them are compatible with each other and desiderable in the standard product. It would require a big investment to understand and polish all of the incoming suggestions. We're not in a state yet, where we can make that change and go truly open source on all of our application code. 
So, for now you will have to stick with http://aka.ms/bcideas - try to get enough votes and we will take a look at it. And maybe some day, everything will be aligned to make the big move to open source all of our code - but that does require build system integration, a community which is prepared to chip in and review, a more structured base code and so on...

**Comment by JesperSchulz** [comment]
With that being said, it does not mean that we won't be looking at the concrete issue mentioned in this thread. My previous comment was purely on the aspect of open sourcing the BaseApp.

**Comment by markusfjolnisson** [comment]
@JesperSchulz @atoader Are there any plans to implement default fieldgroups for atleast the main header tables (Sales Header, Purchase Header etc...) to allow us to work around this issue while you find a propper solution?

**Comment by JesperSchulz** [comment]
Hi @markusfjolnisson, if you could give me a complete list of the tables you'd like use to implement default fieldgroups in, I will process it for the upcoming major and minor release - while we wait for the correct solution in our platform.

**Comment by JesperSchulz** [comment]
Ideally, I would also need the definitions of the fieldgroups. That would speed up processing ;-)

**Comment by markusfjolnisson** [comment]
Hi @JesperSchulz, Thanks for the fast response. It is a pleasure to be able to interact with your team on these issues!

As i see it, the most important tables would be the unposted header tables, and their corresponding line tables...

36		Sales Header		
37		Sales Line			
38		Purchase Header		
39		Purchase Line		
295		Reminder Header		
296		Reminder Line		
5740	Transfer Header		
5741	Transfer Line		
5900	Service Header		
5901	Service Item Line	
5902	Service Line	

As for the definitions of the fieldgroups, i think the current default "Drilldown" options are fine. If I remember correctly, when a fieldgroup is not defined, the system uses the primary key of the table and the description or name field (If that is a field included in the table). My problem is not the default fieldgroups used by the system, but that i am unable to add a field to the dropdown list to aid the customer in registering data.

**Comment by JesperSchulz** [comment]
:-) I get that! I just don't want to add default fieldgroups (which are used by the majority of our users), which make the product worse. But I'll check what the functionality defaults to, and then I will set those explicitly on the tables you mention.

**Comment by TKapitan** [comment]
Hi @JesperSchulz 
We have just implemented BC15.0 (upgraded to 15.2) and default fieldgroups are really missing and we are struggling with that a lot... The project is about 300MD and it is very hard to explain to our clients that we are able to change almost everything except this (that is from their point of view so easy). 

I know that we can change baseapp (we are onPremise); however, we did the whole project without any change in baseapp... 

Could you please add the default DrillDown fieldgroup to:
 - Shipment Method (ID10)
 - Transport Method (259)
 - Payment Method (289)
 - Shipping Agent (291)
 - Bank Account Statement (275)

**Comment by JesperSchulz** [comment]
I surely can! Adding those 5 tables to my pack to be released with next minor :-)
Any other requests out there while I'm at it?

**Comment by tinfister** [comment]
table 99 "Item Vendor" 
table 7012 "Purchase Price" 

thanks

**Comment by JesperSchulz** [comment]
You got it! Final call for more tables ;-)

**Comment by JesperSchulz** [comment]
Pack is being processed in the build system now. All requested tables will be released with the next minor update. Keeping this issue open, as the proper implementation through language support is pending.

**Comment by miracleitconsulting** [comment]
> I surely can! Adding those 5 tables to my pack to be released with next minor :-)
> Any other requests out there while I'm at it?

Sorry if i'm too late.. but can we have dropdown fieldgroup for Bin Contents table as well?

**Comment by JesperSchulz** [comment]
I'll see what I can do for you :) The other fieldgroups are getting released with the next minor end of month.

**Comment by miljance** [comment]
So, no hope to be able to define the fieldgroup for a base table from extension?

**Comment by ALDeveloperin** [comment]
> So, no hope to be able to define the fieldgroup for a base table from extension?

H,I I agree this should be available to create new FieldGroups in AL extensions. When can we expect it?

**Comment by JesperSchulz** [comment]
@pborring/@atoader, that question would be for you to answer.

**Comment by Techcronus-NAV** [comment]
@JesperSchulz Can you please consider to add fieldgroup for **Location** table in next minor release.

**Comment by atoader** [comment]
@ALDeveloperin there is a BC Idea on this topic. Please upvote it :)

**Comment by JesperSchulz** [comment]
@Techcronus-NAV, the Location table already has a FieldGroup!
    fieldgroups
    {
        fieldgroup(Dropdown; "Code", Name)
        {
        }
    }

**Comment by JesperSchulz** [comment]
Please create new issues for new requests, as this one has been closed a long time ago.

This last one I'll process in this issue though ;-) Item Variant seems to have a field group already:
    fieldgroups
    {
        fieldgroup(DropDown; "Item No.", "Code", Description)
        {
        }
    }

**Comment by Wilkai8** [comment]
Hi~ 
@JesperSchulz 

I create a new issue , 
Could you please help me solve it?
[#6644 ]

Thank you in advance.

**Comment by dzakojc** [comment]
Hi,
I now this thread is closed, but we need to add fieldgroups and brick on all Documents Archived tables (T5107 - Sales Header Archive, T5109 - Purchase Header Archive and all related tables - T5108 - Sales Line Archive, T5110 - Purchase Line Archive).

And, it must be supported that fieldgroups, and bricks can be added to the base tables via the tableextension objects. My customers ado not understand when I say to them, that sorry, not possible.

**Comment by GreatScott000** [comment]
I'd open a new issue
