### ISSUE TITLE
idRanges property

### ISSUE THREAD

**Issue by nmahate** [Microsoft/AL#4394]
**Describe the bug**
Compiler doesnt accept the declaring of the idRanges property on the app.json file, to support multiple id ranges. I've used the example from the following online documentation:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files

**To Reproduce**
1. Go to app.json
2. Add property for idRanges as `"idRanges": {"from": 50100,"to": 50200},{"from": 50202,"to": 50300}`

**Expected behavior**
No compiler issue

**Screenshots**
![image](https://user-images.githubusercontent.com/27202612/50280904-b5bfa100-0445-11e9-8733-2e5a72dade9f.png)

**Versions:**

 - AL Langauge: 2.1.6.9331

 - Business Central: W1 13.2 (26556)

**Comment by nmahate** [comment]
The documentation is incorrect. Resolved by including the square brackets.

`"idRanges": [{"from": 50100,"to": 50200},{"from": 50202,"to": 50300}]`

However still get a compiler warning about the property `idRanges` not being allowed?

**Comment by nmahate** [comment]
The compiler issue was resolved by including square brackets, as follows 
`"idRanges": [{"from": 50100,"to": 50200},{"from": 50202,"to": 50300}]`

However, cannot publish the app due to the following error...
error AS0014: The project manifest must contain the allocated identifier range.

**Comment by atoader** [comment]
Hi @nmahate ! If you enter the name of the property ```"idRanges":``` and then use Ctrl+Space, Intellisense will guide you towards the right syntax. AS0014 is an AppSourceCop error. Are you trying to publish to AppSource?

**Comment by deano808** [comment]
Hi, I have a similar problem but the compiler is reporting an issue with the property.

![image](https://user-images.githubusercontent.com/17627914/50904952-8636ff80-1419-11e9-972d-f991b3fee53a.png)

**Comment by JohanStenberg100** [comment]
Hi, this issue is not reproducing on our master branch. In runtime 3.0 this issue is resolved, which is our spring release. Please work around the issue for now and make sure to update your extension when our new version is out, and this issue should be resolved. If you are a BC customer and need this feature activated sooner, please open a support ticket and we can consider to make it available for previous runtime versions.

Thanks!

Johan
