### ISSUE TITLE
ShowMyCode on object level

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/AL#4395]
The global decision, if to hide AL code or not is not the best choice under all circumstances.
I would love to hide code within certain codeunits only.
Therefore I would like to introduce the idea to set "ShowMyCode" on a per object base, if possible.

**Comment by epernst** [comment]
I have never really liked the ability to hide code, neither in C/Side or here with AL. 
But if we have the option to put it on a single object, instead of the whole extension, then it would not be quite as bad. It would "limit" the damage. So you got my vote for this suggestion!

**Comment by ThomasBrodkorb** [comment]
Well, you need to store your private key for the monetizing access somewhere. 
You usually do that inside the code.
If you do not hide that part, you are screwed and fraud can happen with your app.

I am not so much scared from customers, it is more other NAV partners stealing code and ideas.

**Comment by epernst** [comment]
Thomas, I wouldn't store such a key hard coded. Instead I would use a web service to retrieve it, upon setting it up. Or import it as data upon installation (if the table is shared by all companies).

**Comment by quadfin** [comment]
I would like to vote this up - it seems to have gone dormant for +two years.

As an example - consider the case of an extension that is primarily designed to support derivative extensions.
If you have a valuable algorithm that you would like to include but not necessarily share in AL code then you are in a tough spot.
You can hide your code, thus reducing the appeal of your solution.
Or you can split out the algorithm into a dependent extension, thus introducing complexity for deployment and maintenance.

A per object decorator that limits visibility of the code in the object would be useful.
I would also request that the feature apply to both runtime packages and standard app packages (if that is possible).
The ability to distribute a standard app package that supports XML documentation, object browsing, etc., but also protects selected IP would be appealing. (e.g., think of the "horizontal toolkit" ecosystem).

**Comment by atoader** [comment]
Let's channel this feedback on the BCIdea https://experience.dynamics.com/ideas/idea/?ideaid=f7e87a45-fe5a-eb11-8fed-0003ff68c3d2 . It has gathered a large number of votes and we are considering it for the next Wave.

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
