### ISSUE TITLE
Missing CRONUS Data in BC Docker Sandboxes

### ISSUE THREAD

**Issue by FelixBrenkel** [microsoft/AL#4398]
**Describe the bug**
We are missing the production items (bicyles) and further production data in the docker BC sandboxes even with Premium experience activated. In BC OnPremise docker images the data is available. All our automated tests which are passing in OnPremise Version will _fail in sandboxes_ due to missing CRONUS data.

**To Reproduce**
Use current microsoft/bcsandbox:us docker image and see the item list. No bycicles items are available.

**Expected behavior**
CRONUS data in BC Sandboxes is equal to the OnPremise version.

**Screenshots**
BC OnPremise docker (mcr.microsoft.com/businesscentral/onprem:w1) :

![image](https://user-images.githubusercontent.com/13744090/50334954-1fa17e80-050a-11e9-98af-4e01a3d668fe.png)

BC Sandbox docker (microsoft/bcsandbox:us) : Items are missing:

![image](https://user-images.githubusercontent.com/13744090/50334973-2def9a80-050a-11e9-81ea-1b5386894fe1.png)

**Versions:**
microsoft/bcsandbox:us
mcr.microsoft.com/businesscentral/onprem:w1

**Comment by FelixBrenkel** [comment]
Thanks for the information. The :base 
I also found more information about the packages here :
https://diveshboramsdnavblog.wordpress.com/2018/07/27/demo-data-for-business-central-docker-image/

Is there a way to automate the import of the packages for the country versions ? Would be great if that could be done when creating the docker container.

**Comment by atoader** [comment]
Hi @FelixBrenkel ! For certain questions. like this one, we lack the expertise to assist you on this forum. Please use one of the following resources to get more help:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
