### ISSUE TITLE
Category name change in page actions

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#44]
Created new action using category5 and it is showing same in page.
how can we change the name?
![category name change](https://cloud.githubusercontent.com/assets/23735402/21496024/6dd0e176-cc41-11e6-9cb5-5c73ffa70d36.png)

Visual Studio Code is
![properties](https://cloud.githubusercontent.com/assets/23735402/21496101/f320718e-cc41-11e6-91dc-43999bdfb6d8.png)

Did I miss anything?

**Comment by esbenk** [comment]
Category names are controlled by the PromotedActionCategoriesML property (https://msdn.microsoft.com/en-us/library/jj672900(v=nav.90).aspx) on the page. The defined "Job Lost" group is found inside the Prices group on one of the other tabs.

**Comment by pmohanakrishna** [comment]
Adding this code under page extension changed the name of the category name.
pageextension 70000001 "Reason Code for Lost Quote" extends "Job Card"
{
    **PromotedActionCategoriesML=ENU='New,Process,Report,Prices,Job Lost';**
    layout.............

![issue solved](https://cloud.githubusercontent.com/assets/23735402/21497534/a439699a-cc4b-11e6-9674-74dce93bd694.png)

1. My intention to add "Job Lost" group under Prices group is to add after prices group in ribbon but realized that I need to use "Addafter" function? but still its working with addlast also?

2. As per the help.
_If you want to modify existing fields and groups on a page, you use the modify() function. See the code example below for syntax._
But I simply added 
_PromotedActionCategoriesML=ENU='New,Process,Report,Prices,Job Lost';_
without any modify function and still worked? so when should we exactly use Modify function?

**Comment by esbenk** [comment]
1. The prices group you see on the front tab is not the same prices group that is defined on the page. The one on the front tab is the promoted category named prices. You can promote your action into that category instead of Category5, but you can't control the order in that group.
2. Page properties can be set (modified) directly on the pageextension object. You need modify to change existing actions/controls-.

**Comment by pmohanakrishna** [comment]
Got it.
Thank you.

**Comment by pmohanakrishna** [comment]
I would like to add new group(Job Lost) after promoted prices group in home ribbon. that is the reason added category5.
I should use addafter function only right?
addafter(existinggroup;newgroup)
is above syntax Correct?
can we control promoted groups or not?

**Comment by pmohanakrishna** [comment]
I am getting errors while using AddAfter function
layout
    {
        // Add changes to page layout here
        
        addafter(General;Comment)
        {
            field(Comments;ChechComments.CheckCommentsExist(Rec."No."))
            {
                Editable = false;
            }
        }
    }

showing errors at position ; (which is between General and Comment)
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(7,25): error AL0104: Syntax error, ')' expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(7,25): error AL0104: Syntax error, '{' expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(7,25): error AL0104: Syntax error, '}' expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(7,25): error AL0198: Expected one of the application object keywords (table, tableextension, page, pageextension, codeunit)
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(17,40): error AL0107: Syntax error, identifier expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(17,40): error AL0104: Syntax error, '{' expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(17,40): error AL0104: Syntax error, '}' expected
c:\DEMO\New Developer Experience\Samples\ReasonCodeforLostJobQuote\PagJobCardExtCheckComments.al(17,40): error AL0198: Expected one of the application object keywords (table, tableextension, page, pageextension, codeunit)
Error: Package could not be created.

**Comment by esbenk** [comment]
addafter() only takes a single argument. The argument can either be an existing group or field.

The positioning is relative to a control/group on the other tabs. It corresponds to placing the control/action at specified position using control/action list in C/SIDE.

You can only get to the home ribbon by using "Promoted", but you don't have control over placement on the home page, except for the PromotedCategory. The client decides the order.

**Comment by pmohanakrishna** [comment]
https://msdn.microsoft.com/en-us/dynamics-nav/newdev-page-ext-object
addafter(AddressDetails; "Post Code")	Fields and groups
Then the above link should be corrected. right?

**Comment by esbenk** [comment]
Yes, Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is fixed with the next refresh on msdn.
