### ISSUE TITLE
Error when trying to publish extension

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#440]
I'm getting an error when trying to publish my extension. I've successfully published the Hello World extension so I know the connection works.
I see the extension in the Extension Management, but I get the same error when trying to install it from there. (Object reference not set to an instance of an object)

I get the following messages in the event log, one error and one warning:

Error:
Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 2498be68-2158-409b-8dcc-49be44de52d2
ServerActivityId: 69c46e4c-ad12-4304-b549-7630964d4bad
EventTime: 08/01/2017 05:45:00
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nObject reference not set to an instance of an object.\r\n"}</pi></ii>
ProcessId: 3256
Tag: 00000LY
ThreadId: 8
CounterInformation: 

Warning:
Server instance: Navision_main
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 08/01/2017 05:44:54
Message <ii>Threshold Trace Tag. Execution Time = 1009 milliseconds
    Long Running SQL statement Task ID:3, ConnectionId=6
    SELECT DISTINCT CT.SYS_CHANGE_VERSION, 0[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Object Metadata], @maxChangeTrackingNumberObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 1[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [Debugger Breakpoint], @maxChangeTrackingNumberDebuggerBreakpoint) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 2[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Add-in], @maxChangeTrackingNumberAddIn) CT WHERE CT.SYS_CHANGE_OPERATION = 'U'
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 3[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], CT.[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Object Metadata], @maxChangeTrackingNumberNavAppObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 4[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Tenant App], @maxChangeTrackingNumberNavAppTenantApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 5[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App], @maxChangeTrackingNumberNavApp) CT</ii>
ProcessId: 3256
Tag: 000007L
ThreadId: 178
CounterInformation:

**Comment by esbenk** [comment]
Can you check if there is any additional information in the EventLog for the Dynamics NAV server? There should be an Error there.

**Comment by johndcollins** [comment]
This is from the VS Code Debug Console:
[2017-08-01 08:53:48.84] Publishing package to http://localhost:7049/navision_main/dev/apps?tenant=default
[2017-08-01 08:53:55.62] Error: The request failed with code 422, reason: 
Object reference not set to an instance of an object.

This is the error in the event log:
Log Name:      Application
Source:        MicrosoftDynamicsNavServer$Navision_main
Date:          8/1/2017 8:53:55 AM
Event ID:      701
Task Category: (33)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-LPB41KDF8L8
Description:
Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 2498be68-2158-409b-8dcc-49be44de52d2
ServerActivityId: 69c46e4c-ad12-4304-b549-7630964d4bad
EventTime: 08/01/2017 15:53:55
Message <ii>Failed request -- Method:POST; Url:<ii>http://localhost:7049/navision_main/dev/apps?tenant=default</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"\r\nObject reference not set to an instance of an object.\r\n"}</pi></ii>
ProcessId: 3256
Tag: 00000LY
ThreadId: 138
CounterInformation: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MicrosoftDynamicsNavServer$Navision_main" />
    <EventID Qualifiers="0">701</EventID>
    <Level>2</Level>
    <Task>33</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-08-01T15:53:55.579616800Z" />
    <EventRecordID>4245</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WIN-LPB41KDF8L8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Server instance: Navision_main
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 2498be68-2158-409b-8dcc-49be44de52d2
ServerActivityId: 69c46e4c-ad12-4304-b549-7630964d4bad
EventTime: 08/01/2017 15:53:55
Message &lt;ii&gt;Failed request -- Method:POST; Url:&lt;ii&gt;http://localhost:7049/navision_main/dev/apps?tenant=default&lt;/ii&gt;; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: &lt;pi&gt;{"Message":"\r\nObject reference not set to an instance of an object.\r\n"}&lt;/pi&gt;&lt;/ii&gt;
ProcessId: 3256
Tag: 00000LY
ThreadId: 138
CounterInformation: </Data>
  </EventData>
</Event>

**Comment by esbenk** [comment]
If you have published the extension from VsCode it should already be installed. You should not need to install it from the Extension Management page.

**Comment by johndcollins** [comment]
I know, but it doesn't install. It's there in the Extension Manager, but not installed.

**Comment by johndcollins** [comment]
Can I send you a screenshot? 
It's weird, it shows in the web client, but not in the Windows client.

**Comment by johndcollins** [comment]
[https://ibb.co/cFxGek](url) This is the web client and the windows client side by side. Web client shows my extension, but it's not installed. Windows Client doesn't show the extension.

**Comment by esbenk** [comment]
I'm not sure why is not showing in the Windows Client. How do you know it isn't installed? Publishing from VsCode is installing it. 

I assume the VsCode showed a succesful publish. Could there be a functional problem in the code? Have you tried to add a OnOpenPage with a Message() like in the Hello World sample?

**Comment by johndcollins** [comment]
The Web Client says Not Installed. It looks to me that it get's published, but the install fails. I get the same error if I try and install from the web client.

If it never gets installed, then how can I get it to run a page?
Not sure how a functional problem in the code would prevent it from installing. There is no errors in the VS Code.

**Comment by johndcollins** [comment]
So I went through and started over and I was able to produce an error that could be the cause of the issue I was having.

Here is the code that will break the Install:
tableextension 71050000 LocationExtension extends Location
{
    fields
    {
        field(82001;"My New Field";boolean) {}
    }
}

If I change the boolean to Boolean with uppercase B then it works fine.

Let me know if you need me to send more information. You should be able to reproduce yourself.

**Comment by johndcollins** [comment]
So the above is not only related Boolean, it's also Code, Text etc. They all have to be correct case.
However, this didn't solve my issue with my main app not deploying, That seems to be related to setting the SumIndexFields on a key. I'll create a new Issue for both these.
