### ISSUE TITLE
EventSubscriber For Account and Accounting Manager

### ISSUE THREAD

**Issue by BSSIRajbir** [Microsoft/AL#4400]
**Describe the bug**
I want to run a notification on Account/Accounting Manager/IT Manager.

I write down my code for it under 
EventSubscriber on codeunit Conf./Personalization Mgt. 
Page 'Accountant Role Center'
Page 'Administrator Role Center'

But It is not showing me the Notification.
However I tried it for Page 'Business Manager Role Center', It worked for Business Manager Role center.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Write down the EventSubscriber on codeunit Conf./Personalization Mgt. 
Page 'Accountant Role Center'
Page 'Administrator Role Center'
2. Go to My Settings - Change Your Role to respected Areas. 
3. Check your custom Notification, It will not be visible.

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by atoader** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
