### ISSUE TITLE
[Bug] Code Analyzer check rule AL0253 cannot recognize key in virtual table

### ISSUE THREAD

**Issue by OSHK** [Microsoft/AL#4404]
I've created a new page **License Permission** based on the virtual table **License Permission** with the following sorting order:
`The SourceTableView = SORTING ("Object Type", "Object Number") WHERE ("Object Type" = FILTER (<> TableData));`

The **Code Analyzer** shows me an error that sorting fields should be part of the table keys:

![image](https://user-images.githubusercontent.com/39983751/50447727-e449ea00-0925-11e9-9e93-992d3b5e26b5.png)

As far as I see, _"Object Type","Object Number"_ is a primary key in the **License Permission** table:

![image](https://user-images.githubusercontent.com/39983751/50447868-c16c0580-0926-11e9-8415-e7a7c681066f.png)

In my opinion, there should not be such warning in this case.

**Additional Info:**
AL Langauge: 2.1.69331
Visual Studio Code: 1.30.1
Target Database: D365BC CU 02 26413 (on premises)
The following rules were used:
```
    "al.codeAnalyzers": [
        "${CodeCop}",
        "${PerTenantExtensionCop}",
        "${AppSourceCop}"
```

**Comment by OSHK** [comment]
I have just checked on the following version and it seems to be that it still works in the same way:
- AL Langauge: 2.1.91153
- Visual Studio Code: 1.31.1
- Target Database: D365BC SandBox (on cloud)

**Comment by qutreson** [comment]
Hi @OSHK, I just tried using the latest extension from the marketplace and from our master branch and it seems that this issue has been fixed. Please feel free to open a new issue if it still reproduces on the latest versions.
