### ISSUE TITLE
Creation of multiple Report Layouts

### ISSUE THREAD

**Issue by srenders** [microsoft/AL#4407]
When creating a report, you can add the layouts using the RDLCLayout and WordLayout properties. What if I would like to create and upload multiple layouts? For example adding some custom layouts for the report? I know I can add them in my extension, but they don't seem to get published.

For example, I create a report with an RDLC and a WORD built-in layout, using the RDLCLayout and WordLayout properties. Then I add an extra custom layout, by copying the RDLC and or WORD layout and changing it's color. (Similar to the custom layouts of report 1306). The reason for doing that would be to use those custom layouts in the email body selections.

Do I have to manually upload those layouts, or can they added automatically when publishing my extension? Or do I need to write some install code to accomplish this?

**Comment by atoader** [comment]
Hi @srenders ! At the moment, you have to manually upload the layouts. The compiler only packages the default layouts for the report.

**Comment by atoader** [comment]
I suggest that you post your question to one of the following resources to get more help:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by srenders** [comment]
I can't say I like this answer: which is basically: 'figure it out yourself'. I'm not the only one with this question: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1212255705 

Are there any plans to update the compiler to take into account multiple report layouts, or enabling these to be installed in an install codeunit?

**Comment by rvanbekkum** [comment]
I agree this might be a great enhancement.
I've seen quite some people (e.g. on Yammer) that have a desire/need for such functionality.

**Comment by atoader** [comment]
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
