### ISSUE TITLE
BC C/AL event publisher methods not visible in AL EventSubscriber

### ISSUE THREAD

**Issue by johbor** [Microsoft/AL#4408]
In AL some publisher methods are not available in the list of methods when defining an EventSubscriber.
In this case you can't use the OnAfterUpdateDates integration method of Sales Line.
But also others are not visible.
Even when I make my own OnTestMe event publisher this method is not visible in AL. Also after downloading the symbols after making a mod in C/AL.

I expect to see al the methods in the list of Intellisense when defining an EventSubscriber.

![screen shot 2018-12-28 at 15 21 56](https://user-images.githubusercontent.com/9353297/50518655-0f177800-0ab7-11e9-967a-a4f723b0ce4f.png)
![screen shot 2018-12-28 at 14 50 44](https://user-images.githubusercontent.com/9353297/50518675-2fdfcd80-0ab7-11e9-99ed-c906727fb98d.png)
![screen shot 2018-12-28 at 15 21 11](https://user-images.githubusercontent.com/9353297/50518733-71707880-0ab7-11e9-858c-7345cdd947cf.png)

**Versions:**

 - AL Langauge: 2.1.69331

 - Business Central: NL Dynamics NAV 13.2 (13.0.24623.0)

**Comment by atoader** [comment]
@johbor have you followed the instructions in this article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side ?

**Comment by johbor** [comment]
@atoader Actually no. I did not know about adding the generatesymbolreference=yes parameter to final.exe.
But after your hint I did add the generatesymbolreference=yes to startup the cside development environment (final.exe) and then compiled a table object with custom event producer.
Then after downloading the symbols again in VSCode and I managed to get the OnTestMe listener working.
And also all the other missing stabdard event producers (e.g. OnAfterUpdateDates) are visible in AL.
But it is not really clear to me when the symbols are regenerated server side.
Is this happening when I compile 1 object e.g. Job Planning Line?

**Comment by atoader** [comment]
If you run the command: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side#get-started-generating-symbols-and-compiling-all-objects , it will generate symbol metadata for everything in your database. The symbol package is created on the fly when you download it.

If you run C/SIDE with generatesymbolreferences=yes as described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side#continuously-generate-symbols-each-time-you-compile-objects-in-cside , the symbol metadata will be updated when you compile objects and the symbol package will be generated on the fly when you download it, just as before.

**Comment by johbor** [comment]
The issue can be closed. It is working fine with the 2 different approaches to regenerate the symbols in the database.
