### ISSUE TITLE
CodeCop rule for missing Captions and OptionCaptions

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#4409]
Developers some times forgets adding captions (especially OptionCaption) and these mistakes are hard to catch in QA when testing is done in English as BC will fall back to using names when captions are not present. 

I suggest adding four new CodeCop rules:
1. "Field {0} should have a Caption." applies to table fields with no Caption.
2. "Field {0} should have a OptionCaption." applies to table fields of type Option with no OptionCaption.
3. "Field {0} should have a Caption." applies to _page_ fields with no Caption when SourceExpr is _not_ a table field.
4. "Field {0} should have a OptionCaption." applies to _page_ fields of type option with no OptionCaption when SourceExpr is _not_ a table field..

**Comment by atoader** [comment]
Hi @AskeHolst ! Thank you for the suggestion. I will forward it to the team that owns the CodeCop analyzer.

**Comment by fvet** [comment]
@atoader 

I'd like to add one related:

"ActionGroup {0} should have a Caption." applies to _page_ ActionGroups (without subtype) with No Caption.

If no caption is available, the actiongroup doesn't render well in the webclient (no issue in the RTC)

**Comment by MarcHansenMicrosoft** [comment]
This is implemented in rules AS0221-AS0226

**Comment by rdebath** [comment]
This doesn't notice missing Action captions, it probably should.
