### ISSUE TITLE
"Property showMyCode is not allowed." in app.json

### ISSUE THREAD

**Issue by dibyanugraha** [Microsoft/AL#4410]
**Describe the bug**
showMyCode property in app.json inside the compiled extension always set to false even though in development has been set otherwise.

**To Reproduce**
Add "showMyCode" = true in app.json, package the file, publish the extension, force tamper NAV App table's record using SQL Server Management Studio to make source code available to be downloaded or edit page 2500 to force show Download Source Code button to appear.

FYI, tested on older BC on premises CU 01 W1 would also reproduce the same behavior (extension version 2.0.5xxxx) 

**Expected behavior**
showMyCode should be able work properly in app.json.

**Screenshots**
In app.json there's a warning shows that "Property showMyCode is not allowed."

![code_2018-12-30_23-28-26](https://user-images.githubusercontent.com/11976855/50549244-180d7280-0c8c-11e9-9081-9467e20636a4.png)

**Versions:**

 - AL Language: 2.1.69331

 - Business Central (on premises): CU 02 W1

**Comment by atoader** [comment]
The property is case sensitive. Please use intellisense instead of typing it yourself to avoid this kind of problems.
