### ISSUE TITLE
Add multiple Fields in Fieldgroups between two fields

### ISSUE THREAD

**Issue by jigneshdhandhanav** [microsoft/AL#4412]
Hello All,

I have table 27 and for that fieldgroups 

DropDown : No.,Description,Base Unit of Measure,Unit Price

I need to create tableextension with below field groups in which "No. 2" and "Shelf No." are added after the No. field. How can we do that ?

No.,"No. 2","Shelf No.",Description,Base Unit of Measure,Unit Price

**Comment by thpeder** [comment]
Hi @jigneshdhandhanav,

Thanks for your feedback.
That is currently not possible, but we will add it to backlog of features

**Comment by pjllaneras** [comment]
Yeah. Would be interessant interact with FieldGroups fields in the same way we do with Page fields in a Page Extension: removing a field and adding a field (in any possition we want).

I have an interesting project in mind, but, at this moment, I can't do it due to current limitations with FieldGroups: I need to replace current "_Description_" fields, by my own "_Translated Description_" field.

**Comment by deadmouse** [comment]
Please we need this. Implement "addafter" for fieldgroups, not just "addlast".

**Comment by doschulze** [comment]
I would also be very happy about the implementation of this feature.
Is there an implementation planned for this in the near future?

I assume that there is no WorkAround for this problem at the current time either, right?

Best regards

**Comment by atoader** [comment]
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by dtkb** [comment]
I think you want these:
* https://experience.dynamics.com/ideas/idea/?ideaid=654c8767-5505-ea11-b862-0003ff68954d

and to see also:
* https://experience.dynamics.com/ideas/idea/?ideaid=bcbba207-1258-ea11-b698-0003ff68bc25

**Comment by JDreher-MC** [comment]
This feature would be much appreciated by one of our customers as well.
