### ISSUE TITLE
Image preview of action Image property not fully visible

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#4413]
**Describe the bug**
Image preview of suggested images on actions isn't completely visible.

**To Reproduce**
1. Create an action
2. Add image property
3. Trigger intellisense
4. Scroll through the images
5. Only appears when viewing the image for the first time.
  When returning to a previous loaded image and going to the 'bad loaded' image again, the image is shown fully.

**Expected behavior**
Icons are always fully visible.

**Screenshots**
![2019-01-02_08-27-42](https://user-images.githubusercontent.com/34303738/50583338-dede2980-0e68-11e9-8572-20319f5761b7.gif)

**Versions:**

 - AL Language: 2.1.69331  

 - Business Central: BE 13.2 (26556)

**Comment by qutreson** [comment]
Hi @SirBETE, thank your for reporting this issue. We believe it might be related to the way VS Code handles our request. I opened a new issue on their repository.

**Comment by qutreson** [comment]
@SirBETE closing this issue as it does not reproduce anymore with the latest version of Visual Studio Code (I tried with 1.52.0). 
For more information, you can see the updates and the fix that were done on the related issue.

![ImageRenderingWorks](https://user-images.githubusercontent.com/31541422/102116005-a01ac180-3e3c-11eb-89ab-8dfa21401302.gif)
