### ISSUE TITLE
[AssistedSetup]  Page Field not visible in FR version

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#4414]
**Describe the bug**
Hi,
For an assisted setup developed in W1 version in which I have some DrillDown Field to give access to pages to configure, I'm not able anymore to display these same fields, with the exactly same code on the FR version

For this code sample:
![image](https://user-images.githubusercontent.com/29598240/50584987-0934e480-0e73-11e9-8692-ffaf99eb5cc4.png)

**Behaviors**:
**W1 13.2 (26556):** 
![image](https://user-images.githubusercontent.com/29598240/50585049-67fa5e00-0e73-11e9-84b8-446977f1bc04.png)

**FR Dynamics NAV 13.2 (26556)** : 
![image](https://user-images.githubusercontent.com/29598240/50585041-5e70f600-0e73-11e9-805c-bc28ab53e53a.png)

**Expected behavior**
Same behavior on both versions

**Versions:**
 - AL Language: 2.1.69331

EDIT: Idem on latest be version (BE Dynamics NAV 13.2 (26556))

**Comment by atoader** [comment]
@JulienDecottignies can you reproduce this issue on the latest release?

**Comment by qutreson** [comment]
Hi @JulienDecottignies, can you verify if you are still experiencing this issue when using our latest developer previews (BC15)?

**Comment by qutreson** [comment]
Thank you for your update, I will then close the issue :)
