### ISSUE TITLE
TestPage method FindFirstField error

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#4416]
Today trying to use the TestPage method FindFirstField it gives the following run time error:
> The expression Microsoft.Dynamics.Nav.Runtime.NavTestField cannot be type-converted to a Microsoft.Dynamics.Nav.Runtime.NavValue value.

This issue https://github.com/Microsoft/AL/issues/505, reported in August 2017, says that "Find*Field() have issues with the first argument'. It appears to never have been resolved.
When is this going to happen?

**Comment by AndreyKorepanov** [comment]
Hi @lvanvugt, thank you for reporting the issue. Could you, please, provide the code (file or project) which causes the error?

**Comment by lvanvugt** [comment]
Hi Andrey,

Should have provided that code on my intitial post. Now I cannot find and cannnot reproduce. Probably would have when it wouldn't have taken 4 weeks for a first reply.

Nevertheless, now trying to reproduce I am having a hard to get this method do what the help tells (in all it's vagueness) it will do: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-findfirstfield-method

Could you please elaborate on what is should do and how to program that? Thanx in advance.

**Comment by esbenk** [comment]
It is a programmable way of finding a specific row in a list. It searches through the rows in the list by paging forward until it finds a row with PageField.Value = Value.

**Comment by pborring** [comment]
Hi Luc, given the age of this entry, no repro (sorry for that delay back then) and Esben answering the recent question, I am going to close this entry. If you feel there is still a bug, or have a repro, then please reactivate with details. Thanks.
