### ISSUE TITLE
Test automation execution is not running in the order (still)

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#4417]
With https://github.com/Microsoft/AL/issues/2711 this issue should have been fixed as would have been shipped in November 2018. On the December release of BC (CU02) it's still not working.

When will this fix be released?

**Comment by thpeder** [comment]
Hi @lvanvugt,
The issue got fixed in our master branch and not also in the major branch, so It wasn't part of the CU, but I'll correct that.

**Comment by lvanvugt** [comment]
@thpeder when will this finally be released?

Writing a book on test automation and getting all tests in (seemingly) random order is highly frustrating when creating screen shots etc.

Or is the insider build containing the fix already?

**Comment by qutreson** [comment]
@lvanvugt, thank you for your feedback, closing the issue.
