### ISSUE TITLE
Add GUIALLOWED oninsert trigger

### ISSUE THREAD

**Issue by jigneshdhandhanav** [Microsoft/AL#4419]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by thpeder** [comment]
Please open a new issue that describes the problem in greater details than just a title.
