### ISSUE TITLE
NAV_Visual Studio Code - Single Instance Codeunits

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#442]
Hello all,
i have Problems using single instance codeunits to store values. I am using the latest Version of tenerife. I stored a value (integer) in a single instance codeunit (building simple functions like setvalue and getvalue) to get it later at another object. 
But - the value is 0 later! It works if i tried to get the value in the same object i used to store it. But if i changed the object, the value seems to get lost by nav. Why? I have my example Code attached to this issue.
![vendorlist_readvalue_windowsclient](https://user-images.githubusercontent.com/26924867/28826995-6fbfe8d4-76cc-11e7-9d62-f5cc45b586ab.jpg)
![vendorlist_readvalue](https://user-images.githubusercontent.com/26924867/28826996-6fc300f0-76cc-11e7-88e8-3ccb1264f1da.jpg)
![customerlist_fillvalue](https://user-images.githubusercontent.com/26924867/28826993-6fb9f654-76cc-11e7-9949-b28eda2ad041.jpg)
![singleinstance_codeunit](https://user-images.githubusercontent.com/26924867/28826994-6fbcb5d8-76cc-11e7-8d9c-8f4976fc7934.jpg)

**Comment by esbenk** [comment]
That is a bug. It is not being executed as a single instance.

**Comment by KaiSwitalla** [comment]
When this will be fixed?

**Comment by Gallimathias** [comment]
@KaiSwitalla Dann wird da einfach so auf deutsch programmiert :D 

@esbenk A cool idea would be to use single instance as a keyword. This can not be seen at a glance as a property. It is however important to distinguish single instance from normal.

````cSharp
codeunit single 70051011 SingleInstance
{
}
````
