### ISSUE TITLE
Scheduled Task Error: You do not have permission to create or run scheduled tasks

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#4421]
Our app uses Scheduled Tasks to run daily processes that have to occur at a specific time. Today, we had two customers report that they are getting "You do not have permission to create or run scheduled tasks" when our app attempts to create the task. Did something change?

![image](https://user-images.githubusercontent.com/19348055/50615202-7ebfa580-0eb1-11e9-8db2-9e5c37815916.png)

The user is a SUPER user. This error does not occur in my sandbox tenant.

**Comment by jcooper01** [comment]
@atoader this one is high priority for us

**Comment by atoader** [comment]
@jcooper01 please contact support. As a rule, issues reported through support get a higher priority than ones reported through GitHub. You can close this issue after you've contacted support.

**Comment by jcooper01** [comment]
@atoader @ryanweigel suggested that I post it here, as we don't have an official production support channel as a non-CSP ISV. How can we escalate this?

**Comment by atoader** [comment]
@jcooper01 I've forwarded your issue and I will update you as soon as I find out more.

**Comment by pborring** [comment]
If you have production tenants/customers and you are not a CSP, you should have a CSP Partner, who you can escalate to.

Here is an overview of support channels
https://community.dynamics.com/business/b/financials/archive/2018/12/04/find-the-right-resources-and-provide-feedback
 
Summary of where to file bugs and issues:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.

**Comment by BartPermentier** [comment]
So how am I supposed to test my code that should be run by the job queue?
