### ISSUE TITLE
SqlJoinType  in query object dataitem in not working

### ISSUE THREAD

**Issue by RuiningFan** [microsoft/AL#4423]
Hi Experts,

SqlJoinType  in query object dataitem in not working. No matter I was using  SqlJoinType=FullOuterJoin;   SqlJoinType=LeftOuterJoin;or    SqlJoinType=RightOuterJoin; It always return the result as    SqlJoinType=InnerJoin. 
In Item Table, we have a new item Test1
![image](https://user-images.githubusercontent.com/34213721/50943033-c784e900-14c5-11e9-8916-812eaa380461.png)
In Item Ledger Entry. It doesn't have the new item 1001. Because it does not have any inventory change.
![image](https://user-images.githubusercontent.com/34213721/50943120-116dcf00-14c6-11e9-82c9-8148c5ddcd73.png)
So I group by the Item by Item No and Location Code in Item Ledger Entry and full outer join on item table. 
![image](https://user-images.githubusercontent.com/34213721/50943244-9fe25080-14c6-11e9-8e92-25878837e440.png)
we could not found 1002 in the result.

![image](https://user-images.githubusercontent.com/34213721/50944520-bd65e900-14cb-11e9-92c4-c2f31a6fb0b1.png)

Actually I tried, left join, right join and switch the position of these two table. All get the same result. Did I just used the Query Object in the wrong way? 

AL 2.1.69331

**Comment by atoader** [comment]
@RuiningFan could you please provide a sample that used to work in C/AL and the equivalent that does not work in AL?

**Comment by RuiningFan** [comment]
Sorry for the delay. I have update the post. I'm not sure this is caused by using the query object in a wrong way.

**Comment by LPhanMCS** [comment]
Hi,
I have the same issues in AL, trying left, right or fullouterjoin did not work.
The query is fairly simple, just to get dimension 3 value from dimension set entry in Item Ledger Entry table

query 50009 "ItemTracking"
{
    QueryType = Normal;
    Caption = 'Item_Tracking';
    elements
    {
        dataitem(Item_Ledger_Entry; "Item Ledger Entry")
        {
            DataItemTableFilter = "Serial No." = filter ('<>''''');

            column(Entry_No; "Entry No.") { Caption = 'Entry No'; }
            column(Item_No; "Item No.") { Caption = 'Item No'; }
            column(Posting_Date; "Posting Date") { Caption = 'Posting Date'; }
            column(Entry_Type; "Entry Type") { Caption = 'Entry Type'; }
            column(Document_Date; "Document Date") { Caption = 'Document Date'; }
            column(Document_No; "Document No.") { Caption = 'Document No'; }
            column(Document_Type; "Document Type") { Caption = 'Document Type'; }
            column(External_Document_No; "External Document No.") { Caption = 'External Document No'; }
            column(Location_Code; "Location Code") { Caption = 'Location Code'; }
            column(Lot_No; "Lot No.")
            {
            }
            column(Serial_No; "Serial No.")
            {
            }
            column(Source_Type; "Source Type") { Caption = 'Source Type'; }
            column(Source_No; "Source No.") { Caption = 'Source No'; }
            column(Quantity; Quantity) { Caption = 'Quantity'; }
            column(Purchase_Amount_Actual; "Purchase Amount (Actual)") { Caption = 'Purchase Amount'; }
            column(Sales_Amount_Actual; "Sales Amount (Actual)") { Caption = 'Sales Amount'; }
            column(Cost_Amount_Actual; "Cost Amount (Actual)") { Caption = 'Cost Amount'; }
            column(Cost_Centre; "Global Dimension 1 Code") { Caption = 'Cost Centre'; }
            column(Department; "Global Dimension 2 Code") { Caption = 'Department'; }
            
            dataitem(DimSet3; "Dimension Set Entry")
            {
                SqlJoinType = LeftOuterJoin;
                DataItemTableFilter = "Dimension Code" = const ('SALES CHANNEL');
                DataItemLink = "Dimension Set ID" = Item_Ledger_Entry."Dimension Set ID";
                column(Sales_Channel; "Dimension Value Code") { Caption = 'Sales Channel'; }
            }
            
        }
        
    }
}

The same query in CAL is working

**Comment by louagej** [comment]
#### LEFT JOIN, the filter applied before or after

Hi,
I'm experiencing the same problem.
I guess the problem lays in the combination of Option of the DataItemLink

This is the case in my Cronus company:

- Item 1000 has a `Sales Unit of Measure` of `GR`
- The `Item Unit of Measure` `GR` for this Item 1000 is missing
So I created a Query object to verify this:

```al
query 50001 "Item Unit of Measure"
{
    QueryType = Normal;

    elements
    {
        dataitem(Item; Item)
        {
            DataItemTableFilter = "No." = filter ('1000');
            column(No_; "No.") { }
            column(Description; Description) { }
            column(Base_Unit_of_Measure; "Base Unit of Measure") { }
            column(Sales_Unit_of_Measure; "Sales Unit of Measure") { }
            dataitem(Item_Unit_of_Measure; "Item Unit of Measure")
            {
                SqlJoinType = LeftOuterJoin;
                DataItemLink = "Item No." = Item."No.", Code = Item."Sales Unit of Measure";
                DataItemTableFilter = "Qty. per Unit of Measure" = filter (> 0);
                column(Code; Code) { }
                column(Qty__per_Unit_of_Measure; "Qty. per Unit of Measure") { }
            }
        }
    }

    trigger OnBeforeOpen()
    begin

    end;
}
```

Unfortunately, the output of my Query doesn't return any records.
When I'm translating my Query Object to an SQL Query, this is how my Query looks:

```SQL
SELECT [No_]
      ,[Description]
      ,[Base Unit of Measure]
      ,[Sales Unit of Measure]
      ,iuom.Code
      ,iuom.[Qty_ per Unit of Measure]
  FROM [CRONUS BELGIË NV$Item] item
  LEFT OUTER JOIN [CRONUS BELGIË NV$Item Unit of Measure] iuom
ON iuom.[Item No_] = item.No_
AND iuom.Code = item.[Sales Unit of Measure]

WHERE [No_] = '1000'
AND iuom.[Qty_ per Unit of Measure] > 0
GO
```

But again, no output here
![2019_07_03_002](https://user-images.githubusercontent.com/7229592/60592991-1723dd80-9da2-11e9-8d75-54a724f1b30b.png)

So What goes wrong exactly?
When you place filters in the ON clause on a LEFT JOIN, the filter is applied before the results are joined to the outer table. When you apply a filter in the WHERE clause, it happens after the LEFT JOIN has been applied.

So when I change my SQL Query to:

```SQL
SELECT [No_]
      ,[Description]
      ,[Base Unit of Measure]
      ,[Sales Unit of Measure]
      ,iuom.Code
      ,iuom.[Qty_ per Unit of Measure]
  FROM [CRONUS BELGIË NV$Item] item
  LEFT OUTER JOIN [CRONUS BELGIË NV$Item Unit of Measure] iuom
ON iuom.[Item No_] = item.No_
AND iuom.Code = item.[Sales Unit of Measure]
AND iuom.[Qty_ per Unit of Measure] > 0

WHERE [No_] = '1000'
GO
```

... I get the output I wanted.
![2019_07_03_003](https://user-images.githubusercontent.com/7229592/60593004-2014af00-9da2-11e9-9144-b8ba81938f2c.png)

Unfortunately, when I try to adapt my Query object in AL, I get a `Syntax error, '=' expected` (`AL(AL0104) [17,121]`)

```AL
query 50001 "Item Unit of Measure"
{
    QueryType = Normal;

    elements
    {
        dataitem(Item; Item)
        {
            DataItemTableFilter = "No." = filter ('1000');
            column(No_; "No.") { }
            column(Description; Description) { }
            column(Base_Unit_of_Measure; "Base Unit of Measure") { }
            column(Sales_Unit_of_Measure; "Sales Unit of Measure") { }
            dataitem(Item_Unit_of_Measure; "Item Unit of Measure")
            {
                SqlJoinType = LeftOuterJoin;
                DataItemLink = "Item No." = Item."No.", Code = Item."Sales Unit of Measure", "Qty. per Unit of Measure" > 0;
                column(Code; Code) { }
                column(Qty__per_Unit_of_Measure; "Qty. per Unit of Measure") { }
            }
        }
    }

    trigger OnBeforeOpen()
    begin

    end;
}
```

So my guess is that there should be a syntax update allowing us to add `"Qty. per Unit of Measure" > 0` in the DataItemLink as it is allowed in an native SQL query.

Kind regards,
Job Louage

**Comment by kalberes** [comment]
Can you still reproduce the issue on the latest 15.X based release?
