### ISSUE TITLE
Generic Chart Page - Field Selection from extension in BC (Cloud)

### ISSUE THREAD

**Issue by Busslar** [Microsoft/AL#4424]
hi,

i try to create a custom generic chart from a query with a custom datasource table.
unfortunetly it's not possible to select a data field for the x/y-axis from the query.

the reason is that nav is fetching available fields from the Object Metadata in CU 9180, Fct. GetQueryColumnList. but as we know, app extensions metadata are stored in table "NAV App Object Metadata"

will it be possible to fetch fields from this table too/instead?

Marvin

**Comment by atoader** [comment]
Hi @Busslar! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
