### ISSUE TITLE
cuegroup Caption not working

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#4426]
**Describe the bug**
Create a new cue table and cardpart page for that cue, within the layout you can set the caption of the cuegroup but it will not show as the Name of the cuegroup appears instead.
The ShowCaption property may not be working - as it does not hide the name of the cuegroup.

**To Reproduce**
```
page 50100 "Project Issue Cue"
{
    Caption = 'My Project Issues';
    PageType = CardPart;    
    SourceTable = "MyCueTable";

    layout
    {
        area(content)
        {
            cuegroup(projectIssues)
            {
                Caption = 'Project Issues';                
                field("Project Issues"; "Project Issues")
                {
                }               
            }
        }
    }
}
```

**Expected behavior**
The caption "Project Issues" should appear above the cuegroup OR should be hidden if the ShowCaption property is set to false

**Screenshots**
![image](https://user-images.githubusercontent.com/35546166/50658238-8fbdf480-0f4d-11e9-9727-ff1ffe189e3d.png)

The name of the cuegroup is always show in bold however and not the caption / cannot be hidden

**Versions:**
 - AL Langauge: 2.1.69331

 - Business Central: US Dynamics NAV 13.2 (26556)

**Comment by tinfister** [comment]
For me cuegroup property ShowCaption = False doesn't work
![image](https://user-images.githubusercontent.com/29481795/52904356-57d3ed80-322b-11e9-873b-d229bdf7c6fd.png)
