### ISSUE TITLE
The timeout value of '0' is longer than the maximum supported value of '5' minutes

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#4427]
When using the new HttpClient, setting a timeout value of longer than 5 minutes results in an error. In our application, we communicate with web services that sometimes take 20 or 30 minutes (or more) to process a request. Therefore, we have to wait for longer than 5 minutes for a response. This has always worked in our MSXML implementations in Classic Client and in our .NET implementations in Windows Client.

**To Reproduce**
HttpClient.Timeout(3600 * 1000)

**Expected behavior**
The timeout value is set to the desired number of miliseconds.

**Comment by atoader** [comment]
Hi @jcooper01 ! We will investigate if we can fulfill your request.
My concern at the moment is that in an environment where resources are shared between multiple tenants, a request such as this one would consume system resources for a long time, potentially worsening the experience for other tenants.
Would it be possible to do this work in a manner that is async? 
For example, you can create another service to which you send requests and which returns immediately. This service forwards the request to your web service and waits for 20-30 minutes for the response to come back. Once the response has arrived, you call an API endpoint in the BC system to complete the initial request.

**Comment by jcooper01** [comment]
Given the nature of the data involved (credit card numbers), this is not possible for PCI compliance reasons.

**Comment by atoader** [comment]
Are you facing this issue OnPrem or in the cloud?

**Comment by jcooper01** [comment]
On prem for the customer that's being impacted right now, but it would be an issue in the cloud if we had a customer using this particular function.

**Comment by nhsejth** [comment]
For OnPrem customers this can be mitigated by changing the server custom settings file.

  <add key="NavHttpClientMaxTimeout" value="00:05:00"/>

No need for platform changes related to this topic.

For cloud based solutions, it will not be feasible with such a long timeout on the network operations as it most likely will impact performance for other tenants on the same node.
