### ISSUE TITLE
Object Reference Error when setting SumIndexFields on key

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#443]
When setting the SumIndexFields on a key in an extension table I get the following error when I try to publish:

[2017-08-01 11:21:01.75] Publishing package to http://localhost:7049/navision_main/dev/apps?tenant=default
[2017-08-01 11:21:06.76] Error: The request failed with code 422, reason: 
Object reference not set to an instance of an object.

Example extension table to re-produce:
tableextension 71050012 PurchRcptLineExtension extends "Purch. Rcpt. Line"
{
    fields
    {
        field(82000;"Some Location Code";Code[10]) { }
    }

    keys
    {
        key(Key8;"Some Location Code") 
        {
            SumIndexFields=Quantity;
        }
    }
}

**Comment by esbenk** [comment]
This repro and causes the same error. The crash is of course a bug. The problem is related to using a SumIndexField from the base table, which is not supported right not. We are investigation this limitation can be removed.

**Comment by johndcollins** [comment]
Can this be marked as a bug then?

**Comment by atoader** [comment]
The crash is fixed and you will get a compile-time error if you try to set the SumIndexFields property using fields from the base table. You can only use fields from the tableextension.
