### ISSUE TITLE
Can't add users to Business Central.

### ISSUE THREAD

**Issue by thomasbarbut** [Microsoft/AL#4430]
Hello,

when trying to pull users from Office 365 on Business Central (Cloud Version) I'm getting this error.

Something went wrong.
Der opstod en fejl
Date and time: Mon, 07 Jan 2019 13:31:48 GMT
Azure AD tenant ID: 3cb16a1f-f7b9-4d3c-ae8b-88b354b145a6
Client operation ID: a9ffab50-49cc-4078-9316-306dcd70dbf8

How can I trace down the problem and get this solved?

Your help is appreciated.

best regards,
Thomas Barbut

**Comment by atoader** [comment]
Hi @thomasbarbut ! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
