### ISSUE TITLE
[Browser compatibility] My Notifications Page "blank" on all except Edge

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#4432]
**Describe the bug**
Hi,

When calling My Notifications page, it correctly displays on Edge (even in rtc on docker image) but not on Chrome or Firefox.

I don't know from when is coming this incompatibility, but I always worked with Firefox and I was able to display My Notifications page, before.

Also, the following screenshots are taken from Docker Image ( FR 13.2 (26556)) but I reproduced it also in my Cloud Sandbox environment (FR 13.1 (26678)), and on the latest W1 docker image (pulled yesterday).

Finally, please let me know if there is a specific repository for this kind of issue, as this is not an AL Language issue, or enhancement proposal.

**Screenshots**
**My Notification Page**

**Chrome  (v71.0.3578.98):**
![image](https://user-images.githubusercontent.com/29598240/50836523-adc69300-1359-11e9-99ef-dc4190d7a0ee.png)

**Firefox (v65.0b8):**
![image](https://user-images.githubusercontent.com/29598240/50837250-76f17c80-135b-11e9-9dcc-3111d7f1abeb.png)

**Edge:**
![image](https://user-images.githubusercontent.com/29598240/50836627-f0886b00-1359-11e9-9eff-e458385b73e1.png)

**Expected behavior**
Same behavior on both browsers

**Comment by qutreson** [comment]
Closing this issue as it seems like a client issue which is beyond the scope of this repository which is only for issues related to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
