### ISSUE TITLE
Event Request : OnBeforeIncrementBatchName in Codeunit 13 "Gen. Jnl.-Post Batch" 

### ISSUE THREAD

**Issue by Wiechardt** [Microsoft/AL#4433]
Hi Team,

Is it possible to add the event OnBeforeIncrementBatchName to codeunit 13 "Gen. Jnl.-Post Batch"?

![image](https://user-images.githubusercontent.com/44084862/50839763-a909db00-1369-11e9-830d-6cd152cdd239.png)

This event can be called from the function UpdateAndDeleteLines before the increment of the batchname - I would like the option of preventing the batch name from incrementing.

![image](https://user-images.githubusercontent.com/44084862/50839829-df475a80-1369-11e9-96ed-9304ae9aee91.png)

Many thanks,

**Comment by dNsl9r** [comment]
Wrong github Issue tracker, should be posted here: https://github.com/Microsoft/ALAppExtensions/issues

**Comment by Wiechardt** [comment]
Logged in wrong github issue tracker
