### ISSUE TITLE
Code Signing certificate

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4435]
We are in the process of validating the checklist to submit the app to business central, in order to sign the code digitally we need buy the third party "Code Signing certificate".
Can any one suggest me which type of  "Code Signing certificate" we need to buy?

**Comment by pmohanakrishna** [comment]
we are using DigiCert https://www.digicert.com/code-signing/
you can check GoDaddy etc. also

**Comment by Kowa63** [comment]
Good bang for the buck from Comodo.   
https://comodosslstore.com/uk/codesigning.aspx
That was totally sufficient to get the app off the ground.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
