### ISSUE TITLE
Application Package is not updated

### ISSUE THREAD

**Issue by ToraVision** [Microsoft/AL#4437]
- AL Extension Version: 0.12.20065
- Server Version: 11.0.21836.0

In the NAV 2018 Database i changed a functionvisibility to External to use it in my Extension.
I generated the symbols and downloaded them in VS Code, but the changes were not commited. In the Application.app the function's visibility is still set to Internal. If i look in the Object Metadata "Symbol Reference" Field the Symbols are correct created and the property is set to External. The problem i guess is that the Application Package is not updated.

**Comment by dNsl9r** [comment]
You need to generate the symbols: https://blogs.msdn.microsoft.com/nav/2018/01/16/generate-symbols-in-a-modern-development-environment-with-microsoft-dynamics-nav-2018/

**Comment by ToraVision** [comment]
i already generated them and they're already correct updated in the Object Metadata.

**Comment by atoader** [comment]
@ToraVision please read this documentation article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side . If your changes still do not show up in the symbols, please open a support issue.
This repository only accepts issues related to the latest AL development environment.

**Comment by ToraVision** [comment]
@atoader thanks for your reply. I walked trough al of these step but it didnt worked. How respectively where can i open a support issue

**Comment by atoader** [comment]
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
