### ISSUE TITLE
Error if field type is not correct Case

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#444]
When creating a field in a table, if the type starts with a lowercase letter, the publish will fail with error 500.

Example to re-produce:
tableextension 71050000 LocationExtension extends Location
{
fields
{
field(82001;"My New Field";boolean) {}
}
}

**Comment by esbenk** [comment]
I'm unable to repro this. Can you retry on a clean installation? I have checked the compiler code, the emitted information doesn't contain the capitalization from the source.

**Comment by johndcollins** [comment]
I tried a new VM and couldn't reproduce the issue either. Not sure what happened to my old VM.
