### ISSUE TITLE
Can't select resource code in Job Resource Prices because of Issue #2250

### ISSUE THREAD

**Issue by DavyVerbeek** [Microsoft/AL#4441]
Because of the following code on Page 1011 - Job Resource Prices: 

Code - OnLookup(VAR Text : Text) : Boolean
  OnAfterLookupCode(Rec);

It seems that the standard dropdown functionality is broken.
I'm not able to select a resource code in the Job Resource Prices page (in a BC production environment)

I think this code can be the only reason why it fails, but please correct me if i'm wrong.

**Comment by atoader** [comment]
Hi @DavyVerbeek! Thank you for reporting this problem. Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
