### ISSUE TITLE
Codeunit Graph Mgt - Inc Doc Attachment

### ISSUE THREAD

**Issue by georgii01** [Microsoft/AL#4442]
**Versions:**
 - AL Langauge: 2.1.69331
 - Business Central: 13.2.26556.0 (SE)
 - Codeunit: 5509 Graph Mgt - Inc Doc Attachment
 - Procedure: UpdateRelatedDocument

**LOCAL UpdateRelatedDocument(VAR IncomingDocumentAttachment : Record "Incoming Document Attachment")**
IF IncomingDocumentAttachment.ISTEMPORARY OR (NOT GraphMgtGeneralTools.IsApiEnabled) THEN
  EXIT;

IF NOT IncomingDocument.GET(IncomingDocumentAttachment."Incoming Document Entry No.") THEN
  EXIT;

IF NOT IncomingDocument.GetRecord(RelatedDocument) THEN
  EXIT;

**RelatedRecRef := RelatedDocument;**
_RelatedRecRef – rec reference
RelatedDocument – variant_

IF NOT RelatedRecRef.WRITEPERMISSION THEN BEGIN
  SENDTRACETAG('00006WH',AttachmentCategoryLbl,VERBOSITY::Error,NoPermissionErr,DATACLASSIFICATION::SystemMetadata);
  EXIT;
END;

IF NOT IntegrationManagement.IsIntegrationRecord(RelatedRecRef.NUMBER) THEN
  EXIT;

RelatedRecRef.MODIFY(TRUE);`

**Comment by atoader** [comment]
@georgii01 what is the issue? Could you please explain?

**Comment by qutreson** [comment]
Hi @georgii01, can you elaborate a bit more about the issue? 
What is the scenario you are trying to achieve, the result you expect and what is the current result?
Is this an issue with with an existing page in the base app? If yes, which one is it?

**Comment by georgii01** [comment]
Hi @qutreson,

The scenario is very simple. I want to attach file: Incoming Documents -> Incoming Document Files -> Attach File
The result: File not added, no error message.
Yes, Incoming Documents is the base page/app.

**Comment by qutreson** [comment]
Hi @georgii01, this looks like an application issue. This repository is no longer dedicated to handling application requests. Instead please log a new issue in the following repository: [https://github.com/Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions)

**Comment by finn777** [comment]
Looks like 299273 - No file is added through Attach File action in the Incoming Document Files just registered for this story.
