### ISSUE TITLE
Extend options via enum

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#4443]
I'm aware enum was introduced earlier so we are able to extend an "option" datatype that we create.. But how it works if we pretend to extend a standard microsoft option?

**Comment by atoader** [comment]
@martinhocosta88 what do you mean by pretend to extend a standard microsoft option?

**Comment by martinhocosta88** [comment]
A simple Debit Memo as a new Document Type for example. But I'm closing this thread, gonna re-eng this development.
