### ISSUE TITLE
Role Centers in D365 BC production & Docker Image

### ISSUE THREAD

**Issue by Bssivivek** [Microsoft/AL#4444]
I see lot of role centers missing in D365 BC Production vs role centers in D365 BC Docker images.
In Docker image we have lot of role centers. Please find the screen shot below
![image](https://user-images.githubusercontent.com/38437776/50996604-3454af00-14d7-11e9-9350-94f36191823b.png)

In D365 BC production, we have following role centers
![image](https://user-images.githubusercontent.com/38437776/50996632-47677f00-14d7-11e9-9df0-3cd65d462541.png)

The problem is, we added few pages in IT manager Role center but since its missing in production we cannot access those pages. Please let me know if i am missing something.

**Comment by Bssivivek** [comment]
We have added our pages in 
1) Accountant
2) Sales order processor
3) account receivable administrator
4) IT manager
Account receivable administrator & IT manager role which is available in docker image is missing in D 365 BC production.

**Comment by atoader** [comment]
Thank you for opening this issue! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
