### ISSUE TITLE
system.xml library is not found in al probing path

### ISSUE THREAD

**Issue by Priti-1** [Microsoft/AL#4445]
**Describe the bug**

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by atoader** [comment]
Please read this documentation article https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al . Please fill in the template when creating new issues.
