### ISSUE TITLE
Custom ruleset gets ignored after changing app.json

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#4446]
As soon as I make a change to the app.json file, the custom rulesets are ignored and the list of problems is filled with al message that I tried to suppress with the rulesets. I need to close and reopen the workspace to activate the rulesets again.

Steps and/or AL code to reproduce the behavior:
1. Enable code analysis
2. Create a custom ruleset and check if it works
3. Make a change to app.json and watch the suppressed messages come up in the problem list

**Versions:**
AL Language: 2.1.69331

**Comment by JohanStenberg100** [comment]
Hi @ajkauffmann, thanks for reporting this. I can reproduce it in the latest released VS code version `2.1.79379` but not in our master branch, so it will be fixed in a future release.

Johan
