### ISSUE TITLE
Menu Suite Question?

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#445]
Sorry if this has been asked.

What's the best practice when it comes to setup tables and showing data from an Extension?
Doesn't look like we can extend the Menu Suite at this time. What's the time frame for this?

Right now is seems that everything has to be launched from existing pages with actions.
Can anyone confirm this?

**Comment by esbenk** [comment]
That is correct. We don't support MenuSuite at the moment. 

The MenuSuite has it roots in the old classic C/SIDE UI and is not really suited for our current UI model. We are considering a new concept to replace the menusuite. We don't have a timeline for that.

**Comment by StanislawStempin** [comment]
I created an FAQ entry for it since the question came up a few times. Please refer to:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
