### ISSUE TITLE
Rename Symbol with F2 (Refactor) doesn't extend to all Workspace's files

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4450]
We have 2 interdependent projects (Business Central Extensions), each in a different folder, but within the same Workspace opened with VSCode.

When we press F2 to rename a symbol it is only doing it in all the files within the same project when in fact it is expected and necessary that it be done in all the files of the Workspace.

Steps to Reproduce:

1. Create 2 BC Extension Projects with a dependency but under the same Workspace
2. F2 to rename symbol in Project1 
3. We expect it refactors all ocurrences in both projects and all files, including xml translations

Example:
[WorkspaceRefactorIssue.zip](https://github.com/Microsoft/vscode/files/2751263/WorkspaceRefactorIssue.zip)

Screenshots:
![image](https://user-images.githubusercontent.com/5801847/51061807-cef6e000-15f4-11e9-986e-ddc5973794ed.png)

![image](https://user-images.githubusercontent.com/5801847/51061820-d6b68480-15f4-11e9-9318-72f50e375808.png)

![image](https://user-images.githubusercontent.com/5801847/51062325-dae3a180-15f6-11e9-980a-08c78a2c6fff.png)

**Versions:**
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

VSCode Version: **1.30.2** (user setup)
Commit: 61122 f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

PD.- We don't know if this is a bug of VSCode, AL Compiler or both, so [we have opened this issue here](https://github.com/Microsoft/vscode/issues/66417) too.

**Comment by JavierFuentes** [comment]
Hi, VSCode Team has answered in the copy of this issue that **this behaviour is responsibility of AL Compiler Extension**...

I've just read this entry about [Working with multiple AL project folders within one workspace](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-multiroot-workspaces) so I think this should be supported...

**Comment by atoader** [comment]
@JavierFuentes  this is not supported at the moment.
If you have two projects, A, and B in the same workspace and B uses A, B is actually depending on the symbols from A, not on project A itself. Project dependencies in a workspace is on our road map, but I cannot give you an ETA.

**Comment by NKarolak** [comment]
@atoader A year has passed - is the issue still on your road map; any ETA available?
Thank you

**Comment by atoader** [comment]
As far as I remembered, I demoed this at TechDays. Are you encountering any issues?

**Comment by NKarolak** [comment]
Thanks for the quick reply.
My workspaces in general do not work as expected (publishing a the leaf project does not publish the root project, despite correct settings and using BC16; @kalberes is currently investigating). 
Hence I did not know whether F2 "usually" works in this context or not. For me, it still does not work from root to leaf.

**Comment by atoader** [comment]
If you can provide a repro project + a video recording of the actions, we can take this as a bug. It might be that there is an interaction that is not loading the projects in the correct order and leading to this issue.

**Comment by NKarolak** [comment]
Hum, I can try. Should I post it as a new AL Issue, then, or just add it here?

**Comment by atoader** [comment]
A new issue is the best. I will close this one as the feature to which this issue was referring has been implemented.

**Comment by NKarolak** [comment]
Just FYI, I've tried it with a new repository, and F2 worked as expected. Hence my F2 issue is related with the broken project dependencies in my other repo.
