### ISSUE TITLE
Can't publish extension with No-Reason error message

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4451]
**Describe the bug**
The attached paired-project-extensions throws an Error whithout Reason message when we try to publish the **DataExtension**

**To Reproduce**
1. Open attached workspace with VSCode and try to publish first DataExtension project
2. We see this error without any reason and can't publish it
![image](https://user-images.githubusercontent.com/5801847/51063014-58a8ac80-15f9-11e9-9a37-680a471ff8da.png)

**Expected behavior**
A clear and concise description of what is happening to solve the problem.

Source Code:
[WorkspaceRefactorIssue.zip](https://github.com/Microsoft/vscode/files/2751263/WorkspaceRefactorIssue.zip)

**Versions:**
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by atoader** [comment]
Thank you for reporting this issue @JavierFuentes ! We will investigate and let you know once it is fixed.
