### ISSUE TITLE
Suggestion: Add Debugger.Log() function to AL Language

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4452]
The AL language debugger does not yet show all variable and property values ...

For this reason, we are currently forced to debug using the old method of displaying those values with messages on screen, but this has the risk of publishing our code with any of those messages and confusing our users ...

It would be convenient to have a new function **Debugger.Log ( )** that would allow you to see the text strings of debugging only in the DEBUG CONSOLE of VSCode and also in the Console of the Browser itself ...

For convenience, this new function should not require using FORMAT () to convert Numbers, Dates or Booleans to text and should be **automatically deactivated when Publish to a Production Instance** (that should be marked as DEV, QA or PROD too).

![image](https://user-images.githubusercontent.com/5801847/51078435-2492c180-16b5-11e9-8855-812535b28bda.png)

![image](https://user-images.githubusercontent.com/5801847/51078330-d29d6c00-16b3-11e9-8d6d-7b7a5cbfccd6.png)

![image](https://user-images.githubusercontent.com/5801847/51078316-b39eda00-16b3-11e9-8cd8-b07daafbd1af.png)

**Comment by atoader** [comment]
@JavierFuentes were you thinking about something similar to https://code.visualstudio.com/docs/editor/debugging#_logpoints ?

**Comment by JavierFuentes** [comment]
Hi @atoader,
not really ... personally, I would like a new function or AL language command and not something like this that seems intrinsic to VSCode and not portable to other IDEs...

I do not lose hope of being able to program in AL language with other cross-platform or multi-language IDEs like [IntelliJ IDEA](https://www.jetbrains.com/idea/) or [Rider](https://www.jetbrains.com/rider/) so that members of the development team can choose the IDE that they like the most...

Now we have Events and Subscribers, so using the Browser Console to display loggin messages can also be much more convenient to follow the trace of the code than doing it on VSCode...

Finally, I think it would also be great too, to integrate the Business Central Development environment based on VSCode inside the Browser like [StackBlitz](https://stackblitz.com) does.

**Comment by AbsolutelyFreeWeb** [comment]
in bc saas where dumping data into a file is not straight forwrd anymore, thsi would be very handy

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
