### ISSUE TITLE
Automatic format incompatible with AA0018 Ruleset disabled

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4453]
**Describe the bug**
Seems actually its imposible to disable ruleset AA0018 in the same way you can do with AA0005 because automatic formatter do a break line with my `.. END ELSE IF ..` statement...

**To Reproduce**
Set in your `ruleset.json` file this:

```json
{
    "rules": [
        {
            "id": "AA0005",
            "action": "Hidden",
            "justification": "Avoid AA0005 warning notification for BEGIN .. END only with compound statements"
        },        
        {
            "id": "AA0018",
            "action": "Hidden",
            "justification": "Avoid AA0018 warning notification for END and IF should start a new line"
        }, 
   ]
}       	
```

... and in your `.al` file something like this:

```php
        rangeOperatorPosition := StrPos(atDateFilter, '..');
        if (rangeOperatorPosition = 0) then begin
            atDateFilter := '..' + CopyStr(atDateFilter, 1, 8);
        end else if (rangeOperatorPosition > 1) then begin
            atDateFilter := CopyStr(atDateFilter, rangeOperatorPosition)
        end;
```

**Screenshots**
Automatic format change my code like this:
![image](https://user-images.githubusercontent.com/5801847/51079588-e94ebd80-16c9-11e9-9702-193885b8a1cc.png)

**Expected behavior**
- The `then begin` statements remains in the same line with a visual warning.... its OK
- The `end else if` statements should remain in the same line too with a visual warning... it doen't do now.

Versions:
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by JohanStenberg100** [comment]
Hi @JavierFuentes! First off - you can decide to fully disable the message by using `None` instead of `Hidden` in your ruleset. Secondly, the formatter is not controlled by the ruleset, so you'll still get your `end else if` split even if you disabled the rule as you did now.

Thanks,

Johan

**Comment by JohanStenberg100** [comment]
Hi again, the formatter will set the `IF` to a new line, no matter what your ruleset is. They are not connected. I'll do a double-check internally to see if the desired result is the if statement on a newline with tabs.

**Comment by JohanStenberg100** [comment]
Hi again @JavierFuentes, we have discussed this internally and will stick to the current formatting. Thanks
