### ISSUE TITLE
Restart Debugger should automatically re-compile and re-publish the new .APP extension

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4455]
Actually seems that **Restart (Ctrl+Shift+F5)** VSCode debugger action don't do nothing usefull because when you continue debugging after have been changing you code, the code behaves like the old one and not the new one...

![image](https://user-images.githubusercontent.com/5801847/51083824-9e13c980-1720-11e9-8015-be2a2b208c0b.png)

![image](https://user-images.githubusercontent.com/5801847/51083729-f944bc80-171e-11e9-9df8-c05584e1ba4e.png)

![image](https://user-images.githubusercontent.com/5801847/51083823-85a3af00-1720-11e9-91c9-cf16b46052e8.png)

The expected behaviour of this action **should be automatic _re-compile_ & _re-publish_ & _update the debugger sesion_ in the same Browser Page that you were before**...

Versions:
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by kalberes** [comment]
![image](https://github.com/microsoft/AL/assets/12760483/a594981d-3b11-45b1-b399-f666acc26773)
