### ISSUE TITLE
alc.exe does not correctly escape commandline args

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#4456]
alc.exe seems to have a bug when resolving it's command line arguments. A folder that ends with a `\` (backslash) causes that final `\` to escape the next character.

Here is an example:

````
alc.exe /project:"c:\path\to\my\app\" /out:"c:\path\to\app.app"
````

alc.exe in this case errors out stating that the folder `c:\path\to\my\app\" /out:"c:\path\to\app.app` could not be found. I assume that the final `\` in my value for `project` causes its closing `"` to be escaped and therefore not being recognized as "closure".

If I pass the value without the final `\`, everything works as expected.

**Comment by JohanStenberg100** [comment]
Hi, your example works fine in powershell but not in the regular command prompt. Try this: 

```
alc.exe /project:"c:\path\to\my\app\\" /out:"c:\path\to\app.app"
```

And it works in the command prompt as well. We can't fix it, it's how the CMD works. Thanks
