### ISSUE TITLE
XMLPort 1225 "Imp / Exp Data Exch Def & Map" does not export all data from tables

### ISSUE THREAD

**Issue by AMCJN** [Microsoft/AL#4459]
**Describe the bug**
When exporting a Data Exchange Definition from Page 1210 "Data Exch Def Card",
the XMLPORT 1225 "Imp / Exp Data Exch Def & Map" is called, but this is not exporting
All fields involved for the tables defined in the XML PORT. 
For examlple the field "Overwrite Value" from table 1225 "Data Exch. Field Mapping"
is not exported nor imported.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Go to Data Exchange Definitions page
2. Chose any Data Exchange definition
3. Chose button "Export Data Exchange Definition" and save somewhere on computer
4. Open the saved XML file and look at the bottom of the file, NOT all field information is exported

**Expected behavior**
That all DATA from the defined tables in the XML PORT is exported/Imported, otherwise
information may be lost, trying to export/import data between two BC's.

**Screenshots**

**Versions:**

 - AL Langauge: 2.0.58805

 - Business Central: 

W1 14.0 (27042)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
