### ISSUE TITLE
Setting Permissions in Object for other Objects

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#446]
When transferring a module to the new extension framework, we have to conclude that the permission within an object (ie, a codeunit) can not be accepted 1: 1. In this case, our Codeunit "Read" and "Modify" needs access to Tables 21 and 25. However, we can not assign these permissions because of the following error:

"It is only possible to grant permissions to objects that are defined within the same module"

Is there a solution for this? It is quite common in practice that changes have to be made.

**Comment by kalberes** [comment]
See issue #214
