### ISSUE TITLE
Null Reference error on Global Record Var in event call stack.

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#4461]
BCoP RTM
Getting an error that crashes the web client: 

> Something went wrong.

or terminates the RTC client with:

> The server "BC130" was unable to process the request. The application will close.

Examining the event log shows this Message:

> NullReferenceException occured in OnRun

Complete set of event log messages in the attached file.

It appears to be related to referencing a global record variable in the call stack from an event call.  In this case OnBeforeManualReleaseSalesDoc in Codeunit "Release Sales Document" (C414), calls a function that loops through the Sales Lines for a sales document (quote in this use case, but happens on Sales Order as well).  The loop calls a function on the tableextension for "Sales Line" (T37).  This function in turn calls a local function that references the global variable and the error occurs.

I have experienced this type of error before and managed to work around it with refactoring the code but this case seems pretty straight forward.

**To Reproduce**
1. Build/Publish/Install attached extension example
2. Run web client (Demo Database)
3. Navigate to Sales Quote list
4. Select a Sales Quote with Status of Open
5. Go to Actions, Release, Release
6. Error occurs.  In the RTC the RTC terminates,
I have attached an example that reproduces the error reliably.
[ALProject15.zip](https://github.com/Microsoft/AL/files/2755410/ALProject15.zip)

**Expected behavior**
No error should occur.

**Screenshots**
None

**Versions:**
 - AL Langauge: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.1.69331
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
GB Dynamics NAV 13.0 (24630)
BC13 Build 24623 RTM using Cronus Demo Database

 - VS Code
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

**Comment by GreatScott000** [comment]
Thanks @JohanStenberg100 
I will do, it may take me a few days as I have other commitments I need to deal with.

**Comment by qutreson** [comment]
Hi @GreatScott000, did you have a chance to look back at this issue you reported?

**Comment by GreatScott000** [comment]
@qutreson I have just completed testing and it appears that the problem is resolved in the latest insider build.  It also appears to be resolved in BC130 CU03.#

Thank you for you time.

**Comment by qutreson** [comment]
Thank you for verifying both the insider build and the CU.
