### ISSUE TITLE
Can not call local Procedures in test codeunit

### ISSUE THREAD

**Issue by KoFrank** [Microsoft/AL#4462]
It is not possible to call main extension procedures marked local from a test Codeunit. We don't want to make the procedures of the extension public, as they will not be useful for any external application. Do we have to make them public to run through them from a test code coverage point of view?

Is the preffered way to have the local functions be called via the public procedures actually using them in a test codeunit?

**Versions:**
 - AL Langauge: 2.0.43900

**Comment by atoader** [comment]
@KoFrank if the function is not part of your public interface, you should keep it local and test it by calling methods that are part of your public interface. You do not have to call the method directly for it to be included in the code coverage analysis. 
I suggest you post this question to one of the following resources to get more opinions on the matter:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by JohanStenberg100** [comment]
@KoFrank I will close this issue now since @atoader answered your question. Thanks!
