### ISSUE TITLE
Web Service Access Key per Extension

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#4463]
**Is your feature request related to a problem? Please describe.**
I'd like to have an app, which creates a web service and a key without bothering the user.
This is something, which @ajkauffmann already asked for in #496 and @kvaldik in #911

As @SBalslev writed on 19 Dec 2017 (https://github.com/Microsoft/AL/issues/911#issuecomment-352729760), there is a feature description extending the current functionality to be web services key pr. extension, which sounds very good and was planned to release in the spring of 2018.

So I wanted to ask what's the current status of this? Would be great to have something like this.
For example you can then use odata web services to write data in a page of your extension, without bothering the user.

Any tips, how to build a work around would also be amazing! :)

**Comment by JohanStenberg100** [comment]
Hi @hendrik244, I asked around and we do not have any commitment to that feature in spring or fall releases 2019. It's likely it might not ever be done and the feature will be discarded.

Regarding your search for a workaround - you can try the following forums::
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Thanks,

Johan

**Comment by hendrik244** [comment]
Hi Johan,

Mhm, very sad to hear this.
Would be a very usefull feature. For the developers and also for the users.
But thanks for your answer.

Thanks,
Hendrik
