### ISSUE TITLE
.NET: AES + CRC support

### ISSUE THREAD

**Issue by SDTotti** [Microsoft/AL#4465]
Hi,

We are sometimes using AES encryption and CRC error detecting code techniques in various interfaces with NAV/BC and external services. (https://en.wikipedia.org/wiki/Advanced_Encryption_Standard, https://en.wikipedia.org/wiki/Cyclic_redundancy_check)

In C/AL we were used a standard .NET library for these functions.

In AL we can only use Azure Functions for these functions at the moment, and of course, it is working, but it is not a preferred solution in a long term, 
I wonder whether MS will be able to add these features into the base application DotNet library (Codeunits 3000+) or into the Encryption Management codeunit (1266).

I suggest please add these .Net features into the base application, because it would make our life much easier developing interfaces in Extension.

Thank you.

**Comment by JohanStenberg100** [comment]
Thanks for posting this idea. This idea is not strictly related to the development process and implementing it will require a coordinated effort across many teams in our organization. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
