### ISSUE TITLE
Cannot download symbols on NAV2018 container name, it only works when I use the ip address of the container.

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/AL#4466]
The settings I use(d):
Container is NAV2018-nl  
"platform": "11.0.0.0",
 "application": "11.0.0.0",

Error message: 
[2019-01-15 21:47:38.59] Error: Er is een fout opgetreden bij het verzenden van het aanvraag.
De externe naam kan niet worden omgezet: 'name'
Roughly translated: Error: An error has occured when sending the request: the external name cannot be resuloved: 'name'

**Comment by AndriusAndrulevicius** [comment]
try using -updateHosts (I'm guessing you're using NavContainerHelper).

**Comment by Chingyz** [comment]
> try using -updateHosts (I'm guessing you're using NavContainerHelper).

Thank you! This worked for me! 😃
