### ISSUE TITLE
Move AppSourceCop.json into .codeAnalysis folder

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/AL#4467]
**Is your feature request related to a problem? Please describe.**
The `AppSourceCop.json` file currently lives in the root directory of the application. 

This is messy and makes it trickier to organize and locate.
Being in a sub-folder also lends itself better to centralized settings, i.e. sub-modules.

**Describe the solution you'd like**
The `AppSourceCop.json` file should live under the `.codeAnalysis` folder, as it's directly related to code analysis.

**Alternatives?**
- Have the AppSourceCop look in multiple locations for the file?
- Merge into another settings file, i.e. ruleset.json?

**Comment by qutreson** [comment]
Closing this issue as by-design as we do not have plans going in this direction. In the last months, we have introduced the AppSourceCop.json property `baselinePackageCachePath` which allows to clean up projects by separating baselines for the AppSourceCop from the extension dependencies.

If you would like to have a .codeAnalysis folder introduced, please log an idea at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
