### ISSUE TITLE
IIS Goes down during debug

### ISSUE THREAD

**Issue by LoanVision** [Microsoft/AL#4468]
Hello,
in latest versions of BC (docker/prem) when debugger is attached to session - IIS (Tcpip stack) goes down after 5-10 minutes with warning. IIS restart required to release port pool.

Log Name:      System
Source:        Tcpip
Date:          1/15/19 9:01:10 PM
Event ID:      4227
Task Category: None
Level:         Warning
Keywords:      Classic
Description:
TCP/IP failed to establish an outgoing connection because the selected local endpoint was recently used to connect to the same remote endpoint. This error typically occurs when outgoing connections are opened and closed at a high rate, causing all available local ports to be used and forcing TCP/IP to reuse a local port for an outgoing connection. To minimize the risk of data corruption, the TCP/IP standard requires a minimum time period to elapse between successive connections from a given local endpoint to a given remote endpoint.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Tcpip" />
    <EventID Qualifiers="32768">4227</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-01-16T02:01:10.611477100Z" />
    <EventRecordID>14996</EventRecordID>
    <Channel>System</Channel>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>

And:
Log Name:      System
Source:        Tcpip
Date:          1/15/19 9:01:10 PM
Event ID:      4231
Task Category: None
Level:         Warning
Keywords:      Classic
Description:
A request to allocate an ephemeral port number from the global TCP port space has failed due to all such ports being in use.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Tcpip" />
    <EventID Qualifiers="32768">4231</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-01-16T02:01:10.676747700Z" />
    <EventRecordID>14997</EventRecordID>
    <Channel>System</Channel>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>

**Comment by JohanStenberg100** [comment]
Hi, I tried just debugging an arbitrary solution for 10 minutes (navigating back and forth) and this did not trigger the error that you are describing.

Can you please post a comment on this issue with which version of BC and and the extension you are using. Also please attach a ZIP file with an (anonymized) application which you are debugging and seeing this error with. Furthermore please describe your exact actions to trigger this issue.

**Comment by thpeder** [comment]
Since we haven't heard anymore I'll close this issue, but feel free to open a new issue if you find a bug in the latest developer preview.
