### ISSUE TITLE
CurrReport.PREVIEW is not work correctly on-prem

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/AL#4469]
I had been post a issues at [this link.](https://github.com/Microsoft/AL/issues/1017)
This issues is fixed with Win Client.

But, now I test this case on Web Browser of D365 Business Central CU (on-prem).
I test standard report 206 Sales - Invoice.

![previewerr3](https://user-images.githubusercontent.com/24407031/50877020-8f68a200-1402-11e9-8579-13b4e1446db8.png)

![previewerr4](https://user-images.githubusercontent.com/24407031/50877023-91cafc00-1402-11e9-935f-a2df1116ec76.png)

**Expect**: I expect the "Download to file" and "Print" button isn't display on preview mode.
**_So, what is solution for this case._**

**Comment by hgnamvn** [comment]
There are any updates for this issues???

**Comment by dtkb** [comment]
Obviously not or they would have been posted.

Anyway, unless I'm mistaken, aren't those buttons a function of the particular web browser/viewer being used? So how could BC possibly disable them?

**Comment by qutreson** [comment]
Closing this issue as it seems like a client/runtime issue which is beyond the scope of this repository which is only for issues related to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
