### ISSUE TITLE
The type or method xxx cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#447]
we need below methods to be opened for our app. Please check.

Codeunit 426 : PmtTolCust
Codeunit 12 : CustPostApplyCustLedgEntry, UnapplyCustLedgEntry
Codeunit 423 : LogModification
Codeunit 397 : NewMessage
Codeunit 7301 : RegisterWhseJnlLine
Codeunit 5912 : InsertServLedgerEntry, InsertServLedgerEntrySale, CreateCreditEntry, InsertWarrantyLedgerEntry
Codeunit 5950 : CalculateWithServHeader, CalculateWithServHeader
Codeunit 5986 : RoundAmount, FillInvPostingBuffer
Codeunit 5895 : MakeMultiLevelAdjmt
Table 5992 : SendProfile
Codeunit 19 : Preview
Codeunit 1535 : DeleteApprovalEntries, PrePostApprovalCheckSales
Codeunit 312 : SalesHeaderCheck
Table 5093 : GetSalesDocValue
Codeunit 311 : SalesLineCheck
Codeunit 7000 : FindSalesLinePrice, FindJobJnlLinePrice, GetServLinePrice
Codeunit 7010 : FindPurchLinePrice
Table 38 : IsApprovedForPostingBatch
Codeunit 80 : ArchiveUnpostedOrder
Codeunit 5920 : CreateServItemOnSalesLineShpt, CreateServItemOnSalesInvoice
Codeunit 1720 : RoundDeferralAmount
Codeunit 900 : PostATO, FinalizePostATO
Table 112 : SendProfile
Codeunit 90 : ArchiveUnpostedOrder
Codeunit 1026 : ApplyUsage
Codeunit 1004 : FromJobLedgEntryToPlanningLine
Codeunit 5837 : CalcACYAmt
Codeunit 7301 : RegisterWhseJnlLine
Codeunit 5802 : BufferInvtPosting, PostInvtPostBufPerEntry
Codeunit 5804 : FindUpdateUnitCostSKU, UpdateUnitCost
Table 5804 : UpdateValuationDate
Codeunit 7301 : RegisterWhseJnlLine
Table 9178 : SetExperienceTierCurrentCompany
Codeunit 1090 : SetBatch
Codeunit 9200 : GeneratePeriodMatrixData
Codeunit 359 : FindDate, NextDate
Codeunit 6080 : ResetAdjustedLines
Codeunit 5981 : PostDocumentWithLines
Table 370 : CreateBookAndOpenExcel, SelectSheetsName, OpenBook, ReadSheet
Codeunit 419 : UploadFile, GetFileName

EnableExternalAssemblies property of Reports
Table 2000000074 access
Table Object

**Comment by esbenk** [comment]
Thanks. We are looking into these functions.

**Comment by StanislawStempin** [comment]
We have enabled all functions except the following ones which are unsafe:
Codeunit 397 : NewMessage
Codeunit 419 : UploadFile
Table 370 : CreateBookAndOpenExcel

**Comment by pmohanakrishna** [comment]
these seems to be missed? can you please check.
Codeunit 12 : UnapplyCustLedgEntry
Table 5994 : SendProfile
Codeunit 1535 : DeleteApprovalEntries, 

Codeunit 397 : NewMessage (**alternate**)?

**Comment by StanislawStempin** [comment]
These were done for September Update which is not live yet.

**Comment by pmohanakrishna** [comment]
we created new devpreview yesterday using docker, wasn't it September update?

**Comment by Gallimathias** [comment]
@pmohanakrishna: In the readme in the repo is the next update to September update therefore the current version is: august. 0.8.11706  is august. I guess and say the next version will probably be 0.9. 
:D ;)

You can also always check the nav blog:). The last news is about the August update.

https://blogs.msdn.microsoft.com/nav/

https://github.com/Microsoft/AL

**Comment by pmohanakrishna** [comment]
I am using version 0.9.12465, I hope it is September update only?

**Comment by StanislawStempin** [comment]
I logged a new entry for the methods that were missed:
Codeunit 12 : UnapplyCustLedgEntry
Table 5994 : SendProfile
Codeunit 1535 : DeleteApprovalEntries,

**Comment by maplum** [comment]
When i understand it correctly, the table "object" should be included.
When i use ist, i get still the message described in the title:  
I use it in this way:  TableRelation = Object.ID  where(Type = const(Report));

**Comment by GedasB** [comment]
Virtual tables: Object, Permission Sets are not supported??
