### ISSUE TITLE
HttpClient using proxy

### ISSUE THREAD

**Issue by kine** [microsoft/AL#4470]
During development of App we hit some problems when using HttpClient to download file from URL to import some initial data. To debug the problem, I wanted to use e.g. Fiddler web debugger. I am using BC on Docker for development. To use the Fiddler, I need to set Proxy for the HttpClient. The function is implemented in codeunit 1297 which is part of https://github.com/Microsoft/cal-open-library but it is not external. Is there some plan for supporting the proxy on HttpClient datatype?

Thanks

**Comment by JohanStenberg100** [comment]
Hi, thanks for opening this issue. I'll mark this issue as a suggestion and we'll consider it. It would be a nice enhancement.

**Comment by ThomasBrodkorb** [comment]
Please speed up consideration and implement this.

**Comment by LoVc-GH** [comment]
+1

**Comment by larswestman** [comment]
+1

**Comment by pri-kise** [comment]
This would really help by debugging

**Comment by LoVc-GH** [comment]
@JohanStenberg100 any update on this, is in the backlog? thx

**Comment by JohanStenberg100** [comment]
Hi, thank you all for raising this. Right now this feature request is only tracked here, I can see if I can get it pushed in for the next major release, but no promises as of now.

**Comment by antonbasecloud** [comment]
+1

**Comment by pjllaneras** [comment]
I've just found that there is an entry for this in BC Ideas: [Allow Setting a Proxy for the HttpClient](https://experience.dynamics.com/ideas/idea/?ideaid=9545da70-666f-eb11-8fed-0003ff459a70#).

I think this is a must and not just an idea that needs votes to be implemented, please vote it and leave your comments there if you think so.

**Comment by christianbraeunlich** [comment]
> Remind me, what year is it?

**2023**

112 upvotes on BC Ideas: [Allow Setting a Proxy for the HttpClient](https://experience.dynamics.com/ideas/idea/?ideaid=9545da70-666f-eb11-8fed-0003ff459a70#)

**Comment by pri-kise** [comment]
@KennieNP is asking for feedback on how to implement a HTTP Proxy in yammer/ viva engage:
https://www.yammer.com/dynamicsnavdev/threads/2398372146438144
