### ISSUE TITLE
Export-NAVAppPermissionSet doenst works for all PermissionSets

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/AL#4472]
Export-NAVAppPermissionSet only works for system PermissionSets. PermissionSets of other types (Extension or Userdefinied) result in an error

Example Powershell Export-NAVAppPermissionSet for a system PermissionSet:
![examplesystem](https://user-images.githubusercontent.com/16033297/51250797-e1c43880-1997-11e9-876c-719fda89b58e.jpg)

Example Powershell Export-NAVAppPermissionSet for a Extension PermissionSet:
![exampleextention](https://user-images.githubusercontent.com/16033297/51250801-e7218300-1997-11e9-9cb5-13a412e11939.jpg)

PermissionSET PAYPALSTANDARD exists:
![examplepermissionsets](https://user-images.githubusercontent.com/16033297/51250838-03bdbb00-1998-11e9-86f1-d6331031a14b.jpg)

**Comment by Pieterheinevdm** [comment]
what is the status?

**Comment by kalberes** [comment]
Is this still an issue for you? If yes the best would be to create a Request for Hotfix using the standard channels. Old Xml permission sets are slowly deprecated in favor of the xml permission set application object.
