### ISSUE TITLE
Start debugger 

### ISSUE THREAD

**Issue by LNitzsche** [Microsoft/AL#4473]
**Describe the bug**

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by LNitzsche** [comment]
NAV Server is installed using HTTP protocol and not standard port 8080.

When I try to start debugger with F5, the AL extension publishs the .app correctly, but starts the webbrowser with URL
http://localhost/BC130.... 
and that does not work because standard port 80 for http is used.

The expected behaviour is, that URL
http://localhost:8080/BC130.... 
is submitted to the webbrowser.

If I change the URL manually to http://localhost:8080/BC130....  the debug session is started correctly.

There is no way in to tell AL in the launch.json, to use a different HTTP port than the standard.
Changing the entry in launch.json to
      "server": "http://localhost:8080"
results in an internal error when publishing the app package.
(I think this happens because the string ":7047" is simply appended to the server name without removing the ":8080")

**Comment by Chielve** [comment]
I am running into the same issue.

We are setting up a dev server with docker containers and editted the ports where they are running on.

In the launch file we set the server like this: "server": "http://win-md365bcdev2:82/" and "port": 7059.
The app is published correctly but when we want to debug it it opens the browser with this url: http://win-md365bcdev2/NAV where it should be: http://win-md365bcdev2:82/NAV.

Is there a fix for this?
