### ISSUE TITLE
Txt2AL Converter converts empty string to 0D

### ISSUE THREAD

**Issue by amulaj** [Microsoft/AL#4474]
**Describe the bug**
When you create a new flowfield on a table with CalcFormula set to "Count". And you set a filter like this: 
Archive Date	FILTER	<>'' the txt2Al Converter converts it to "Archive Date" = FILTER (<> 0D)));

the correct way to convert this line is:
"Archive Date" = FILTER (<> '')));

**Screenshots**
C/Side Code: 
![image](https://user-images.githubusercontent.com/35767790/51258762-007ffa80-19ab-11e9-86a9-228fb46234cb.png)

Converted AL Code:
![image](https://user-images.githubusercontent.com/35767790/51258835-260d0400-19ab-11e9-9e84-6b841d0a67cf.png)

**Versions:**
 - AL Langauge: 2.1.79379
 - Business Central: CH Dynamics NAV 13.3 (27312)

**Comment by JohanStenberg100** [comment]
Hi, I could not reproduce this. Can you double check that your `Archive Date` is in fact a string and not a date? If so, please provide a small example where you modify a base table and attach it here as one or more filesso I can run TXT2AL and confirm the bug?

**Comment by thpeder** [comment]
Since we haven't heard anymore I'll close this issue, but feel free to open a new issue if you find a bug in the latest developer preview.
