### ISSUE TITLE
Why the legacy XLIFF 1.2 standard instead of the newer 2.0 version?

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#4475]
This may be a stupid question, but I really mean it. Why do you use the ancient 1.2 version instead of the 2.0 version (also from 2014)? The question doesn't come from me, but from our translators.

**Comment by thpeder** [comment]
Hi @FSharpCSharp,
Our internal tools only supported 1.2, but support for 2.0 is on the backlog.
