### ISSUE TITLE
OnDrillDown vs. OnAssistEdit Trigger

### ISSUE THREAD

**Issue by amulaj** [microsoft/AL#4477]
AL Langauge: 2.1.79379
Business Central: CH Dynamics NAV 13.3 (27312)

I read that the Field Property "AssistEdit" should be set when we use the OnAssistEdit Trigger. 
My question is: 
For OnDrillDown and OnLookUp trigger i am able to show the field without setting the according Field Property  (DirllDown / LookUp). 
Could you handle this three triggers in the same way or is this by design diffrent?

**Comment by JohanStenberg100** [comment]
Hi @amulaj, thanks for filing this issue. I agree it's quite ambiguous, we'll try and align this.

**Comment by fvet** [comment]
Any plans to ship this shortly? 
We're wondering if we need to start reviewing all our objects having an OnAssistEdit trigger :(

**Comment by JohanStenberg100** [comment]
@fvet thanks for pinging this issue. We have this item in our backlog but haven't yet gotten around to it, I can't give you a date when it will be done.

**Comment by atoader** [comment]
@fvet I believe this was fixed in the latest developer preview. Could you please verify?

**Comment by fvet** [comment]
Thanks for the fix. Maybe @amulaj can further test this? 
My reality is still BC 14 and I'm currently not coding against a DEV preview / BC 15 environment ... Any chance in seeing this in the BC 13 / 14 cumulative updates to ease our testing?

**Comment by atoader** [comment]
@fvet can you please open a request to support to have the fix backported? For versions of Business Central that are in mainstream support, all fixes must go through our standard hotfix process.

**Comment by amulaj** [comment]
@fvet i have tested the OnAssistEdit property in the latest DEV Preview BC 15 environment. 
Everything works fine and like expected. 
This issue can be closed.
