### ISSUE TITLE
This AL extension version for Visual Studio Code cannot be used with the specified server

### ISSUE THREAD

**Issue by himalpatel81** [Microsoft/AL#4478]
I am using latest sandbox image for dynamics 365 business central. With the old image there wasn't any issue until yesterday,. 

**To Reproduce**
Publish the AL application from VS Code. (1.30.2)
**Expected behavior**
It should publish the package. 

Error
This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 2.3
- Web API: 2.0
- Debugger: 2.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2
- Supported Web API: 1.0, 2.0
- Supported debuggers: 1.0, 2.0

**Versions:**

 - AL Langauge: 2.1.699331

 - Business Central: US Dynamics NAV 13.3 (27233)

**Comment by IvoMol** [comment]
Laic recommendation: error message is not correct.

Try install AL extension not from marketplace, but from local file C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\130\AL Development Environment\ALLangue.vsix.
This version (2.1.79379) should be compatible with NAV 13.3.

**Comment by himalpatel81** [comment]
Thanks any idea on how can I access this file from container ? Please
excuse my tiny docker knowledge.

**Comment by kwettermann** [comment]
Assuming you are using the default container settings you can find the .vsix at `http://<containername>:8080/`

**Comment by JohanStenberg100** [comment]
Hi all, closing this issue since it seems Himal got the help he needed. Thanks for helping out.

**Comment by robvon** [comment]
It's Back!.. Someone isn't paying attention to their production releases...

[2020-03-20 12:43:49.03] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 4.4
- Web API: 4.0
- Debugger: 3.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3
- Supported Web API: 1.0, 2.0, 3.0, 4.0
- Supported debuggers: 1.0, 2.0, 3.0

**Comment by navdotnetreqs** [comment]
Yes, we keep getting this ridiculous bloody annoying error all the time!

For God's sake could you please keep the version lists up to date! Keep having these problems even with the the newest bloody compilers from inside builds.

I cannot affect the version of the saas sandboxes, so could the bloody compiler that makes 6.0 not also make 5.3 !?

Server details - Runtime: 5.3, - Web API: 4.0, - Debugger: 3.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 5.0, 5.1, 5.2, 6.0

BUT NOT 5.3 WHAT THE FK?

**Comment by JohanStenberg100** [comment]
Hi @navdotnetreqs, this is already fixed and will be rolled out soon. Thanks for reporting this and thank you for your passion towards our product.

**Comment by txeriff** [comment]
Hi, 

This issue keeps happening with latest extension version. I've accidentally updated it and... here we go. 
"'ObsoleteState' is not available in runtime version '2.2'. The supported runtime versions are: '4.0' or greater."

**Comment by NKarolak** [comment]
Microsoft does not process already closed issues. Create a new one and refer to this one, if you like.
