### ISSUE TITLE
Cannot run debugger when App is deployed by another way than from VSCode

### ISSUE THREAD

**Issue by kine** [microsoft/AL#4479]
This is related to issue #4256 
If App is deployed by e.g. powershell, there is no way how to run debugger.

Could you add possibility to run debugger from VSCode without publishing the app first (if it is not there already, I didn't find it)? If I have tooling to publish the app through powershell (because depending apps compilation/publication/unpublication etc.), I cannot debug because I cannot run the debugger just because the app cannot be deployed (see the issue 4256). App is installed and working, but I have no way how to start the debugger because the conflict of scope of the existing app and the publication of the app during starting the debugger...

**Comment by kine** [comment]
Even it will help to debug app which have depending apps installed.

**Comment by JohanStenberg100** [comment]
Hi @kine, thanks for opening this issue, and we are aware of this.

We will very likely have a feature implementing support for this in the near future since we understand the pain points you are experiencing. I'm going to double-check internally if we have any commitment on this as of today.

**Comment by pborring** [comment]
We hope to add support for attaching debugger for Spring 2019, and debug without publish for Fall 2019. They are related, so might be bundled.

**Comment by epernst** [comment]
Am I wrong, but isn't the support for attaching supported for the Fall 2019 release? But not the Spring 2019?

**Comment by pborring** [comment]
2019 Spring: We added ability to attach to already active web client without having to redeploy
2019 Fall: We added the ability to attach to next session (breakOnNext). 
2020 Fall: We added snapshot debugging, and when using that (not normal debugger) also attach to specific session ID or session for user.
