### ISSUE TITLE
Generated PermissionSet error "There is an error in XML document (0, 0)"

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#4487]
I've created very simple extension
![image](https://user-images.githubusercontent.com/29101017/51463900-7a323280-1d75-11e9-8a03-2c0e3cc52f10.png)

Then I used "Generate permission set" option in AL.
It resulted in the next xml file

![image](https://user-images.githubusercontent.com/29101017/51464375-7652e000-1d76-11e9-9801-cb20bf6868d5.png)

`
<?xml version="1.0" encoding="utf-8"?>
<PermissionSets>
  <PermissionSet RoleID="NAME 2 IN CC" RoleName="Name 2 in Customer Card">
    <Permission>
      <ObjectType>0</ObjectType>
      <ObjectID>50100</ObjectID>
      <ReadPermission>1</ReadPermission>
      <InsertPermission>1</InsertPermission>
      <ModifyPermission>1</ModifyPermission>
      <DeletePermission>1</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectType>1</ObjectType>
      <ObjectID>50100</ObjectID>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>
  </PermissionSet>
</PermissionSets>

`

When I try to upload this extension to online tenant I get an error
"There is an error in XML document (0, 0)"

![image](https://user-images.githubusercontent.com/29101017/51464134-f167c680-1d75-11e9-8f83-458a1740c37d.png)

The same for local docker image
![image](https://user-images.githubusercontent.com/29101017/51464202-13614900-1d76-11e9-8d88-c97f8dd7d92b.png)

I tried different variations of permissions set.xml file, but all resulted in the same error.

**Comment by dkatson** [comment]
May be the problem not in the permissionset.
I just created another extension (without tables)
![image](https://user-images.githubusercontent.com/29101017/51465432-f417eb00-1d78-11e9-8064-83eea1eece24.png)

and when I tried to publish it directly to my local docker sandbox using Ctrl+F5 I've got the same error 
![image](https://user-images.githubusercontent.com/29101017/51465494-1578d700-1d79-11e9-802e-10fab9d288d7.png)

AL version seems to be the last one (I've reinstalled it just now)
![image](https://user-images.githubusercontent.com/29101017/51465578-393c1d00-1d79-11e9-852d-683548335864.png)

![image](https://user-images.githubusercontent.com/29101017/51465684-76a0aa80-1d79-11e9-91d4-48083369730b.png)

**Comment by dkatson** [comment]
When I reproduced the same scenario it worked correctly... very strange. Ok for now I think you can close the issue.

**Comment by JohanStenberg100** [comment]
@dkatson at your request I'm closing this issue, thanks.
