### ISSUE TITLE
[Suggestion] Extend Field and Object names to 50 characters

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/AL#4488]
We ask you to consider extending the max length for naming fields and object to 50 characters. This would help to avoid ugly abbreviations and clearer definition of code. Thank you.

**Comment by JohanStenberg100** [comment]
Hi @bleisibach, thanks for opening this issue. The current limit is not arbitrary - our internal representation of fields and objects require such strict limits. Raising the limit to 50 characters would require a major refactoring of our system and is not likely to be invested in any time soon.

That said, we are considering for AL extensions implementing namespaces, which might help you to more nicely group your code. Investing in namespaces is probably the more likely approach from our side, and if you draw a parallel to other programming languages, you often don't want too long names, then namespaces are better. I can't give you any promises on when or even if we will implement namespace support however, but it is being discussed.

Thanks,

Johan
