### ISSUE TITLE
Documenting code with XML comments

### ISSUE THREAD

**Issue by darrenwaller** [Microsoft/AL#4489]
Why not implement XML comments, same that is used in c#

https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

**Comment by pborring** [comment]
Thanks for the suggestion, we are already tracking this in the backlog, currently as a should for fall 2019. It has been discussed multiple times in the past but prioritized down as there are no resources to comment the base code. It could still have value for ISV and VARs though, and our new APIs (for Swagger documentation).

Feel free to suggest on ideas site to get votes and higher prioritization, then also add some more on you expectations for coverage (i.e., mostly for own use or expected support in base app).
https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1

**Comment by JohanStenberg100** [comment]
I'm going to close this issue now @darrenwaller, as Peter mentioned we do have an internal item tracking this. Thanks!
