### ISSUE TITLE
Exported permission set from client has wrong format / PowerShell export fails

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/AL#4490]
- AL Extension Version: 2.1.69331

- Server Version: DE Dynamics NAV 13.2 (26556)

Hi Everyone,

I'm currently working on adding permission sets to an extension, following the instructions provided by https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets

	1. Use AL Language Extension in VS Code to create a default permission set for all extension objects
	2. Publish the extension
	3. Copy the default permission set and edit it in client
	4. Export the permission set via functions provided in Permission Sets page OR Export via PowerShell command

However, both ways of exporting the permission set fail at a certain point. Using the export function on Permission Sets page gets me a .xml file with the wrong format (even if I confirm, that I need the extension format, when prompted). VS Code stating "warning AL1025: The file at location xxx does not match any definition.".

With the PowerShell command, I don't even get a .xml file, as apparently only permission sets of type "SYSTEM" can be exported using this command. Alas, those permission sets can't be edited.

This leaves me with only one option - manually editing the .xml files, something I would really like to prevent.

So for now I'm using a slightly modified version of XMLport 9173 "Export Permission Sets" to export the permission sets, that I finished editing in Windows Client.
Of course this is not optimal, so I suggest that you provide a proper way of exporting permission sets, that have been edited in client, in extension format. That could either be:

-  When using the in-client export function and confirming that you need the extension format, make sure the obtained .xml file actually has the correct format, so that it can be added to an extension (right now, this is a bug in my opinion)
- Making permission sets of type custom and/or extension exportable via the PowerShell command

Thanks!

**Comment by srkkoneti** [comment]
Hi @JohanStenberg100 
Do we have any solution for exporting the  custom specific permission sets, still we have the same issue mentioned above.
1. We were not able export the custom permission sets from Export-NAVAppPermissionSet.
2. If we are exporting from Client, it's not matching the required format. And to match the definition we have to do a lot changes manually.

Currently we are working on 
Version: US Business Central 16.3 (Platform 16.0.14073.14279 + Application 16.3.14085.14363)

**Comment by JohanStenberg100** [comment]
Hi @srkkoneti, we'll look into this when we have capacity. If you can provide an example we can likely speed up the investigation.

**Comment by miljance** [comment]
Any updates on this issue?

**Comment by JohanStenberg100** [comment]
Hi, unfortunately we don't have an update.

**Comment by miljance** [comment]
Thanks for the update. Doesn't it make sense to export user defined permission sets and integrate them into the App? I can provide you with the examples if needed but basic use case would be:

Permission Specialist (non-developer) gets the App in development and prior to releasing it on App Source it is his job to prepare multiple Permission Sets. After he is done the developer should take over those Permission Sets and integrate them into the App. At the moment a developer needs to add missing XML elements in order to make the format compatible.
