### ISSUE TITLE
CodeCop rule for testing field length (Lookup Flowfields)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4494]
**Is your feature request related to a problem? Please describe.**
If a new flowfield of type Lookup is created, the field datatype/length is set. If the related table definition is changed, e.g. increase of related field length from text 50 to text 100, the related Lookup flowfields should be increased as well.

**Describe the solution you'd like**
Have a new CodeCop rule that checks any Lookup flowfields to match the EXACT length of the related field 

**Describe alternatives you've considered**
Running the fields table and manually check all fields.
Using Prism

**Comment by JohanStenberg100** [comment]
Hi @fvet, thanks for filing this issue. This is a valid suggestion and we will consider it.

**Comment by fvet** [comment]
Also posted on Experience Ideas
https://experience.dynamics.com/ideas/idea/?ideaid=564dbb74-e66f-e911-80e7-0003ff689ebe

**Comment by atoader** [comment]
Thanks for posting this on BCIdeas! It seems that it has gathered traction there. I will close this issue. Any new votes and comments should go to BC Ideas.

**Comment by MarcHansenMicrosoft** [comment]
Moved back to GitHub as a CodeCop improvement

**Comment by MarcHansenMicrosoft** [comment]
40 votes on ideas.
https://experience.dynamics.com/ideas/idea/?ideaid=564dbb74-e66f-e911-80e7-0003ff689ebe

**Comment by dnpb** [comment]
Isn't this already done in some recent AL extension version?

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

Going forward we will not track progress on CodeCop issues here on GitHub. Hence, we are closing this issue.
