### ISSUE TITLE
RLDC Report doesn't show output (tested also with  "Customer - Top 10 List" report)

### ISSUE THREAD

**Issue by steiul** [microsoft/AL#4497]
**Describe the bug**
I have an rdlc report that doesn't show output when used in an extension.
For ease of demonstration, I took report 111 "Customer - Top 10 List" and built it for extension. 
That doesn't show the output either.
When I test the report in the windows client, it works as it should.

Note: I had to do small changes to the report because data item variables are not accessible outside the dataitem in the AL compiler. But that has been tested in the windows client and brought expected results.

**To Reproduce**
Download the report files from this article, and apply them as extension in a CRONUS installation.
Run the report and you will only see a blank page, as the one in the **Screenshots** section.
Otherwise, feel free to take any of the standard reports and see if it works as an extension.

[Report 111 - Top 10 Customers - extension.zip](https://github.com/Microsoft/AL/files/2783057/Report.111.-.Top.10.Customers.-.extension.zip)

**Expected behavior**
I expect the output to reveal the normal output of top 10 customer, like presented below.

**Screenshots**
![output as extension](https://user-images.githubusercontent.com/312179/51540507-e5a00100-1e56-11e9-88ef-97d6e8ed315c.png)
Expected result (executed with the same report before conversion to AL).
![output on premise rtc](https://user-images.githubusercontent.com/312179/51540515-ea64b500-1e56-11e9-861d-b885ea740f64.png)

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: GB Dynamics NAV 13.2 (26542)

**Comment by lippertmarkus** [comment]
@steiul just in the Preview-Mode or also when generating a PDF out of it? We experienced this bug in the preview mode only and solved it by setting PdfFontEmbedding Property of the NAV Server to true (https://docs.microsoft.com/en-us/dynamics-nav/pdffontembedding-property).

**Comment by steiul** [comment]
@lippertmarkus Thanks for input but it doesn't seem to be the case. I don't get any output in any of the situations. I set the property just for the sake of it but didn't help.

**Comment by JohanStenberg100** [comment]
Hi @steiul, I'm able to reproduce this and will file it as a bug. Thanks for reporting this.

**Comment by steiul** [comment]
Hi @JohanStenberg100. Do you have any updates on this ?

**Comment by JohanStenberg100** [comment]
Hi @steiul, no update yet unfortunately. Thanks

**Comment by Pieterheinevdm** [comment]
Hallo Steiul,
I had the same problem after moving the .rdlc files to a Rdlc folder.

after changing the path of the RDLCLayout in de report.al, my problem was fixed.

old RDLCLayout = './Some_report_name.rdlc';
new RDLCLayout = './Rdlc/Some_report_name.rdlc';

**Comment by eque2al** [comment]
I have exactly the same issue with BC Wave 2 (15.0.0) .. **no** report converted from C/AL (with the Txt2Al tool) works!  Only a blank page is presented when using 'Preview' and sending it to the printer just spits out the same ie. a single blank page.

I've copied the RDLC file from the 'src/Reports' folder where the '.al' file resides to the root folder and it made no difference (in fact the compiler copies the RDLC file from 'src/Reports' to the project root folder automatically but to no avail).

This is critical & quite simply a show stopper - if we can't provide any reports with our Extension then Extensions aren't fit for purpose!  Is there anything I can do to solve this or is the current release fundamentally flawed?

(Like the author of this post I've tested this to rule out a problem with my custom reports by making a copy of the 'Customer - Top 10 List' report but again this copy only shows a blank page).

**URGENT -** Please provide a solution as without this we have nothing to sell (well apart from our 'good old C/AL solution')..!

**Comment by ledziu** [comment]
Hi, did you find any solution? I have similar problem... 
On my container everything works, but when i publish app on other enviroment (Different Container with the same BC version, Client Server) one report doesn't ganerate any layout...
