### ISSUE TITLE
Bug with too long field names (>30 signs) coming via extension

### ISSUE THREAD

**Issue by MarkusWinBI** [Microsoft/AL#4501]
**Describe the bug**
Via extension it is possible to extend a table with a field with a field name more than 30 signs. In NAV the internal fields table is than having an entry with a field name "cut" to 30 signs. This causes problems with fieldrefs and table relations as the field is not found. 

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a table extension with a field name > 30 signs, like "My Extension of Customer Table - Show my funny discounting" (58 Signs)
2. Create and Publish Extension
3. See Fields table, you will find a field "My Extension of Customer Table"

**Expected behavior**
AL Compiler does not allow field names > 30 signs

**Screenshots**
![al bug](https://user-images.githubusercontent.com/42672449/51592714-98706d80-1ef0-11e9-84a1-1192802966bb.png)

**Versions:**
Module for NAV 2018 Build 23572
Replicable with AL Language 0.12.28462

**Comment by JohanStenberg100** [comment]
Hi @MarkusWinBI! Please update your VS Code extension, our master branch version is blocking > 30 character names. Thanks!

**Comment by MarkusWinBI** [comment]
Hi @JohanStenberg100, thanks for your fast reply and help. I also forwarded this information to the solution partner which provided the extension. Best regards, Markus
