### ISSUE TITLE
[Application Enhancement] Additional fields in table 2000000203 - Report Data Items

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#4502]
The new virtual table 2000000203 - Report Data Items is very practical, but unfortunately important fields are missing. Could you please add the following fields?

1. the caption of the data item (only displayed in the RequestPage) - Text[250]
2. an additional consecutive number for DataItems (so that you can run through it in the correct order) should also be sortable by this consecutive number. At the moment the order is rather arbitrary, and you have no idea in which order the DataItems occur.  The Data Item ID must of course be kept. [Integer] 
![image](https://user-images.githubusercontent.com/22373356/51388289-364aed80-1b29-11e9-856a-f8c0cb3eb6c2.png)

3. the parent ID of the DataItem, so that the hierarchy can be determined (0, if top) [Integer]

**Comment by JesperSchulz** [comment]
Transferred to correct repo.

**Comment by JohanStenberg100** [comment]
Thanks for posting this idea. This idea is not strictly related to the development process and implementing it will require a coordinated effort across multiple teams in our organization. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
