### ISSUE TITLE
Exposing "CalledFromPageId" in OnOpenPageEvent 

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#4503]
Dear Development Team,

We would like to filter the records on the Lookup Page when the user is using the Quick Search functionality (looking up from a field) but based on the information of "from what Page the Lookup has been Opened from".
We know that adding filters in the OnOpenPage trigger will filter the Lookup List. Using "traditional development" we can add a field to the TableRelation and filter the Page based on that; but this is  not possible using Extensions.

Would it be possible to expose the information of "where the Page has been Opened from" in the OnOpenPageEvent? E.g. CalledFromPageId is populated with the Page ID when the Page has been opened from a Lookup but zero when the Page has been opened from the RoleCenter/Search etc.

Possible usage scenario 1: we have Sales and Purchase related G/L Accounts and we would like to restrict the Lookup list for Sales related Account when the Page has been opened from the Sales Order Subform and do the same for Purchases

Possible usage scenario 2: we would like to restrict the Items in the Lookup List when the Page has been opened from a Purchase Order - filter down the list for the Items only where the Vendor No. is the same as in the header.

**Comment by JohanStenberg100** [comment]
Hi @martonnagy, thanks for filing this issue. I'll label this as an enhancement and we'll process it when we have the capacity.

**Comment by qutreson** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
