### ISSUE TITLE
Business Central - Access ODATA from Azure Function error 401

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/AL#4505]
**Describe the bug**

Hi, I need to access and write data through NAV webservices from an azure function.
This azurefunction is a http callback function which only should forward the incoming http request to a dedicated odata webservice.

I can connect to BC with 
https://api.businesscentral.dynamics.com/v1.0/" + tenant + "/sandbox/ODataV4/" + companyname
 using Postman and User/ WebAccesskey Authentication.  

When I test my azure function and provide the authentication values within the Test Feature of Azure Functions it also works and the data is getting forwarded to BC.
But when the http callback is executed by a website or external function I receive the error " Response status code does not indicate success: 401 (The server has rejected the client credentials.)."

Can anyone help me with this?

Best Regards,
Hendrik

**Comment by JohanStenberg100** [comment]
Hi @hendrik244, this issue you are experiencing seems like an issue related to Azure functions in particular and not to AL. Please try to limit the issues filed to follow our guidance rules.

I will close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. You can also try one of these forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
