### ISSUE TITLE
CodeCop [AA0139] on UserId()

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#4506]
**Is your feature request related to a problem? Please describe.**
On this piece of code
```
IF NOT SkipDim THEN
 SelectedDim.GetSelectedDim(USERID(), 3, REPORT::"Calculate Inventory", '', TempSelectedDim);
```
 I get the following codecop warning:
[AL] Possible overflow assigning 'Text' to 'Code[50]'. 

on `UserID()`.

Parameters of `GetSelectedDim: UserID2: Code[50], ObjectType: Integer, ObjectID: Integer, AnalysisViewCode: Code[10], var TempSelectedDim: Record "Selected Dimension"`

**Describe the solution you'd like**
Could `UserId()` return a Code[50] instead of a text variable?
Since it IS a code[50] field ...

**Describe alternatives you've considered**
`CopyStr` is overkill ...

**Additional context**
BC CU3
compiler 2.1.79379

**Comment by JohanStenberg100** [comment]
Hi @SirBETE and @IvoMol, we have discussed this internally and we don't want to limit the return type to a certain range. This is because there might be changes in the future. The `Code[50]` field backing the procedure can be seen as an "implementation detail" and the type of the procedure to get the `UserID` should be respected. I'll go ahead and close this issue now. Thanks!

**Comment by SirBETE** [comment]
Ok, I understand.
But then CodeCop shouldn't give a warning on a possible overflow when I fill in a UserID field (Code[50])  with the USERID() function (that returns a text, but actually it's a Code[50]).
After all, there's no problem ...

**Comment by JohanStenberg100** [comment]
It will continue to give the warning, because CodeCop can't know implementation details about the `UserID` function. I would suggest that you just use the `Text` type instead of `Code[50]` for your field.

**Comment by SirBETE** [comment]
For variables this is possible.
But not for fields in tables.
There it would be limited to text[250], so the same warning still applies.

You suggest it would be better to add everywhere we us the USERID() function, a CopyStr from 1 to MaxStrLen?
`"Assigned UserId" := CopyStr(USERID(), 1, MaxStrLen("Assigned UserId");`

**Comment by JohanStenberg100** [comment]
Not everywhere you use it, only when you assign it to the field. That way you avoid unnecessary copying.

**Comment by SirBETE** [comment]
Ok, so be it then ...
Thanks anyway :)
