### ISSUE TITLE
Extension Deployment Status - Findlast

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#4514]
**Is your feature request related to a problem? Please describe.**
Could the last (=most recent) record be selected when opening the Extension Deployment Status page?
Currently it's on the first (=oldest) one, so you have to scroll to view the current upload-status.

**Describe the solution you'd like**
Selection is on the last record.
(= top of the page now)

**Additional context**
![image](https://user-images.githubusercontent.com/34303738/51675229-64ba4400-1fd3-11e9-9222-71e01ef4a716.png)

**Comment by JohanStenberg100** [comment]
Hi, this improvement makes sense. Thanks, I'll tag this as an enhancement.

**Comment by charlespockert** [comment]
@SirBETE in the meantime you can just click on the "Started Date" twice to sort the records by deployment start date (descending).

You can then spam F5 in order to refresh the page without affecting the sort.

**Comment by BazookaMusic** [comment]
This was addressed in the past, closing.
