### ISSUE TITLE
Saving XML File BC Online

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#4515]
I'm aware extensions is not supporting the old write and fileMgmt methods so I'm migrating and old xml exportation to BC online.
From the Microsoft Documentation I've managed to create the following method:
`  
                        
                         tmpBlob.Blob.CreateOutStream(OutputStream);

                         exportXML.SETDESTINATION(OutputStream);

                         exportXML.Export;

                         tmpBlob.Blob.CreateInStream(Inputstream);

                         DownloadFromStream(Inputstream, '', '', '', FileName);`

However when exporting, I'm only getting the xml tags but no value between them even though I've data to be exported.
Is there something I'm missing in this "new" way?

**Comment by AndreyKorepanov** [comment]
Hi @martinhocosta88, thank you for reporting the issue. Could you please provide full al file/project to make it easier to reproduce the bug?

**Comment by martinhocosta88** [comment]
Not an issue from the export code. Problem solved.
