### ISSUE TITLE
Query - OData Filter (HTTP QueryString) does not work with extension fields 

### ISSUE THREAD

**Issue by megel** [microsoft/AL#4517]
The OData query filter cannot find the fextended field too. This bug may related to https://github.com/Microsoft/AL/issues/2454

The TableExtension:
![image](https://user-images.githubusercontent.com/15800069/51705073-f26d5200-201a-11e9-9a50-b31da3fbba43.png)

The Query:
![image](https://user-images.githubusercontent.com/15800069/51704998-b508c480-201a-11e9-8881-276421306420.png)

Simulation (HTTP-RestClient for VS Code)
```code
@apiHost = <url>
@apiUser = <user>
@apiToken = <token>
@queryName = MyCompanyInfo
@copmanyName = CRONUS%20USA%2C%20Inc.
### Call the Query … Works
GET  {{apiHost}}:7048/nav/odata/Company('{{copmanyName}}')/{{queryName}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{apiUser}} {{apiToken}}

### Filter the Query … Error
GET  {{apiHost}}:7048/nav/odata/Company('{{copmanyName}}')/{{queryName}}?$filter=IsSpecial eq true
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{apiUser}} {{apiToken}}
```

The query runs correct without filters and the field is found. When I add a filter to the call, an error occurs.

The HTTP-Rest Call:
![image](https://user-images.githubusercontent.com/15800069/51704917-82f76280-201a-11e9-8b65-324cee9e9169.png)

Version:
![image](https://user-images.githubusercontent.com/15800069/51706022-8dffc200-201d-11e9-97d2-a129cfa7b099.png)

**Comment by megel** [comment]
There may be a big difference between **OData** and **ODataV4**.

Query with **OData-URL**:
![image](https://user-images.githubusercontent.com/15800069/51827299-56c53580-22e9-11e9-8bfc-1e7ea9072faf.png)
**Internal Server Error:**
![image](https://user-images.githubusercontent.com/15800069/51827358-79efe500-22e9-11e9-8daa-89d6b370b578.png)

Query with **ODataV4-URL**
![image](https://user-images.githubusercontent.com/15800069/51827309-5fb60700-22e9-11e9-93b8-a78731a5b553.png)
Runs:
![image](https://user-images.githubusercontent.com/15800069/51827399-8ffda580-22e9-11e9-9f12-3faf94526061.png)

**Comment by atoader** [comment]
We could not repro this issue on the latest build from master. If you are using an older build, please open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
