### ISSUE TITLE
The property 'TableIDExpr' cannot be used in this context, as a property on a table field.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#452]
Is this property being discountinued for extensions or just not done yet?

**Comment by esbenk** [comment]
There has been no runtime support for this since the Classic Client. We have just removed the property.

**Comment by NicolaiEsbensen** [comment]
Ok, as will we then :) I can see we handle it using the Table Filter record now, and just left left property as it was.
