### ISSUE TITLE
OnPrem multiple dotnet.al files breaks the download of the App

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#4523]
**Describe the bug**
My App has two dotnet.al files.  The App compiles and executes fine.  Using that App as a dependency for another app fails.

**To Reproduce**
Create an App that has two dotnet.al files for mscorlib.  Publish the App.
Create another app that has dependencies on the first app.  Download symbols.  
Try to use any of the objects in the first App.  Try to publish the second App.  Both will fail.

**Expected behavior**
After combining all dotnet definitions into one file in the first App everything works perfectly

**Screenshots**
![builderror](https://user-images.githubusercontent.com/23558797/51742825-bd9ce180-2092-11e9-80b7-a9bca59530f7.PNG)

**Versions:**
Business Central OnPrem CU3

**Comment by AndreyKorepanov** [comment]
Hi @gunnargestsson, thank you for reporting the issue. We recently fixed this bug, it will be shipped in future updates.
