### ISSUE TITLE
An extension with same App ID and version has already been uploaded. Resolve and deploy again

### ISSUE THREAD

**Issue by JuanJesus14** [microsoft/AL#4526]
Hello,

I have installed in business central production in the cloud with an extension whose version is 1.0.1.2, I have made a change in the extension to add a new report, and I have updated to version 1.0.1.3. in the sandbox it works correctly but when I'm going to load the extension into production, I get the following error "An extension with same App ID and version has already been uploaded. Resolve and deploy again", and I do not know what the reason may be.

I would greatly appreciate any comments to see the reason for the error.
Thank you.

**Comment by JohanStenberg100** [comment]
Hi, can you create a small (anonymized) app that can reproduce this issue? And also list your AL language version and BC version? If this is not possible, I suggest you contact Microsoft support instead since your question is very tenant-specific.

Thanks!

**Comment by rivolemmik** [comment]
Hi,
We have similar issue in BC Cloud Production. If extension upload and installation failed in some reason it's stucked there. It's not possible to uninstall/unpublish or reinstall it.

**Comment by JuanJesus14** [comment]
Hello, 
The BC version is 13.1.26678. 
I consult with Microsoft to detail what happens. 
Thank you.

**Comment by JohanStenberg100** [comment]
Hi, thanks for providing input. We'll take a look

**Comment by bbrown5962** [comment]
I am getting the same error. But I am uninstalling/unpublishing my extension than reloading the same extension. Nothing has been changed.  I understand I can use ""schemaUpdateMode": "Recreate"" in a test environment. But how would I handle this in production?

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 

 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

**Comment by bbrown5962** [comment]
This is not a production system. I am only asking how this would be handled in a production system. In other words, a theoretical question.

**Comment by atoader** [comment]
Hi @bbrown5962 ! The first question was related to our cloud environment, which is slightly different than the onprem environment. There are several ways in which you can end up getting this error message. Please open another issue describing the exact steps that you followed to end get this error and we will try to help out. Please don't forget to mention the version of the environment that you are using.
