### ISSUE TITLE
IntelliSense in Report dataset/dataitem

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/AL#4529]
**Description:**
When entering a 2nd dataitem there is no IntelliSense support for the properties: DataItemLink, DataITemLinkReference and DateItemTableView.

![image](https://user-images.githubusercontent.com/39938430/51790352-62ebae80-2194-11e9-8fb3-c28dba07261e.png)

**AL Extension Version:** 2.1.65951

**Comment by AndreyKorepanov** [comment]
IntelliSense actually works for DataItemLink after DatItemLinkReference is set, but does not work for other items from the bar.
