### ISSUE TITLE
NullReferenceException with Ruleset AA0005 doesn't show the Object and Line where the problem is

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4530]
**Describe the bug**
When you `Hide` the Ruleset `AA0005` and you leave a block `if () then begin ... end` with no active code inside it, a **NullReferenceException** occurs, **but it does not indicate where the problem is**, so you have to look for it throughout your entire code.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Set `AA0005` Ruleset to `Hidden` in your `ruleset.json` file
2. Write a block of Code like in the Screenshot below
3. Observe the PROBLEMS console

NOTE.- I know that setting to `None` the ruleset this Exception doesn't occurs.

**Expected behavior**
I agree with Warnings (not Errors that prevent compiling our code) in this type of circumstance in our code, but it should indicate the exact place where they are happening to be able to take the necessary actions that are considered appropriate in each case.

**Screenshots**
![image](https://user-images.githubusercontent.com/5801847/51798825-08e0fc80-2219-11e9-9a49-fa1f1338c386.png)

**Versions:**
AL Language: **2.0.48254**
Business Central: **ES Dynamics NAV 13.0 (24630) OnPremise**

**Comment by JavierFuentes** [comment]
The same Exception in a `with REC do begin ... end` block

```php
with PurchLine do begin
   // TODO: Do something here
end;
```

**Comment by AndreyKorepanov** [comment]
Hi @JavierFuentes, thank you for reporting the issue. This bug was recently fixed and will be shipped in the future update.
