### ISSUE TITLE
Cannot publish App on Sandbox environment.

### ISSUE THREAD

**Issue by ashik-ivor** [Microsoft/AL#4531]
I am getting an error while publishing the extension on the Sandbox environment. 

AL Compiler: 2.1.79379

![image](https://user-images.githubusercontent.com/38459860/51816260-c0deda00-22eb-11e9-9390-ee861dc17d1c.png)

I have the following permissions in the Sandbox environment, 

![image](https://user-images.githubusercontent.com/38459860/51816376-4cf10180-22ec-11e9-82f3-165a6e918798.png)

Solution tried : 

Changed the runtime to 2.0, 2.2, 2.3, but still facing the same issue. 

Also tried the solution on #4304

**Comment by AndreyKorepanov** [comment]
Hi @ashik-ivor, thank you for reporting the issue. Have you tried to reset your Sandbox environment? The following steps should help:
1. In Business Central click light bulb, type Sandbox, choose Sandbox Environment (Preview) option.
2. In the dialog box click Reset (in the bottom). It resets the sandbox.
3. In VS Code: clear credentials (Ctrl+Shift+P, type Clear credentials) and delete al symbols from .alpackages.
4. Re-start VS Code. Download al symbols (Ctrl+Shift+P, download symbols).
5. Try to run F5.
Please let us know if it does not help.

**Comment by ashik-ivor** [comment]
Thanks @AndreyKorepanov . Resolved now.
