### ISSUE TITLE
App package is stuck after cloud extension upload failed

### ISSUE THREAD

**Issue by rivolemmik** [microsoft/AL#4535]
**Describe the bug**
In cloud production, if extension upload failed then it is not possible to unpublish and reinstall it

**To Reproduce**
[Default publisher_ALProjectTest_1.0.0.0.zip](https://github.com/Microsoft/AL/files/2804013/Default.publisher_ALProjectTest_1.0.0.0.zip)

Attached zip file contains .app and _runtime.app versions of simple HelloWorld extension.

1. Upload "Default publisher_ALProjectTest_1.0.0.0_runtime.app" to Cloud production - will get error: "Deployment failed. Errors: App ID : 25dbc06f-ee64-4a53-a5c3-ced842e465fe Message : { The extension specifies a higher compilation target than allowed. }"
2. Upload now "Default publisher_ALProjectTest_1.0.0.0.app" to the same Cloud production - will get error: "Deploy Operation rejected. Error: An extension with same App ID and version has already been uploaded. Resolve and deploy again.;"

If you upload first the .app package from step 2 then it is in good working order and installs without problems. After one failed try to install runtime package of the same extension, it is not possible to install the right .app package anymore.

**Expected behavior**
Expected that there should be some possibility to delete failed packages and to upload and install the same app once again.

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: Cloud W1 13.2 (27438)

**Comment by AndreyKorepanov** [comment]
Hi @rivolemmik, thank you for reported issue. Have you tried to uninstall and unpublish the first extension before installing the other one? The following steps would help:
1. Open BC and click the light bulb (top-right corner)
2. In the search bar type "Extension management". Click Extension Management from the list.
3. Find your extension click 3-dots (right-top corner of the app). 
4. First Uninstall it, then Unpublish.
Hopefully it helps.

**Comment by rivolemmik** [comment]
It's not possible to Uninstall and Unpublish extension which installation was failed! This extension package is not listed in Installed Extension list.

As described in Expected behavior:
Expected that there should be some possibility to delete (uninstall/unpublish) failed packages and to upload and install the same app once again.

**Comment by atoader** [comment]
Hi @rivolemmik ! The updated extension failed to be uploaded because you made app/code changes but did not bump the version number of the extension.  Please bump the version number of the extension described in 'Step 2' and the upload will be allowed.
