### ISSUE TITLE
CurrReport.CREATETOTALS and Cproperty

### ISSUE THREAD

**Issue by JuditNavarro** [Microsoft/AL#4540]
Hello everyone,

A report that I am migrating to AL uses **CurrReport.PAGENO** and **CurrReport.CREATETOTALS**. However, both of them are deprecated in AL. 

![createtotalsdeprecated](https://user-images.githubusercontent.com/44970454/51896042-80db2e00-23a3-11e9-9076-3393703a3223.png)
![pagenodeprecated](https://user-images.githubusercontent.com/44970454/51896047-83d61e80-23a3-11e9-81eb-b70d33366657.jpg)

Is there any alternative way to do this? Can you please give and example?
I already saw that they give an alternative to PAGENO in this issue [https://github.com/Microsoft/AL/issues/2939](url) but I don't really understand what they really mean without and example.

Thank you.

**Comment by rvanbekkum** [comment]
The report dataset/object and layout are separated in NAV, unlike it was in the classic (e.g., NAV2009) client where report execution and layout generation where intertwined (i.e., you could access C/AL variables/functions from controls and layout section triggers).
This change was for the better in most regards (apart from RDLC as report engine being overly complicated for simple reports), the main advantage being that you are no longer bound to a single report engine for your layouts.
That is, you can choose to create your layout in RDLC, Word or any other format and report engine you would prefer. 

In classic reports you could use `CREATETOTALS` to let the report compute totals in footer-sections of the layout where your field was used.
This procedure doesn't do 'anything' when used in C/AL or AL code. You may however still see it in some of NAV's standard code as a remainder of automatic conversions.
When you want to have totals within your report, you should instead define/compute them in your layout. In RDLC layouts you will often see this happening with RDLC's built-in Sum(...) function.
(Of course you can also add totals as columns to the dataset of your report object, but that is a different story) 

With `Currreport.PAGENO` it's roughly the same story, it doesn't do anything useful when used in C/AL or AL code. If you want to show or use the current page number in your report, you will need to use the built-in functions/system variables of the report engine in your layout. With that being RDLC, you can take a look at some of the standard report layouts that also show the page number at the top of the page (achieved using the corresponding system variable).

**Comment by AndreyKorepanov** [comment]
Hi @JuditNavarro,
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
