### ISSUE TITLE
DotNets: CameraOptions and CameraProvider

### ISSUE THREAD

**Issue by JuditNavarro** [Microsoft/AL#4541]
Hello,
We are migrating our code to AL, and in some pages, we need to use DotNet  **CameraOptions** and **CameraProvider**. 

![cameraprovider](https://user-images.githubusercontent.com/44970454/51898080-0a8cfa80-23a8-11e9-8678-850b06f1a11f.png)
![cameraoptions](https://user-images.githubusercontent.com/44970454/51898086-0c56be00-23a8-11e9-85f7-670b2e1ce27c.png)

We search in the API for Business Central [link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview) but we couldn't find something similar to use. What can we do with the functionality that they gave us? Could you give a suggestion about it?

Best Regards

**Comment by AndreyKorepanov** [comment]
Hi @JuditNavarro, thank you for reporting the issue. You can find more information regarding the camera in the following document:
https://blogs.msdn.microsoft.com/nav/2017/12/20/nav-development-preview-anniversary-update/
Section "Working with camera". I hope it helps.
