### ISSUE TITLE
Bug header comments

### ISSUE THREAD

**Issue by FrancoOrazio** [Microsoft/AL#4543]
There is a bug in Purchase Comments.
If the flag "Copy Comments Order to Receipt" in "Purchases & Payables Setup" is set as true, if you have an header comment and the order has more than 1 line , when you create 1 Warehouse Receipt with more lines of this order and you try to post the receipt, the comment will be moved to the posted receipt for every line, It doesn't work and will be shown an error message (EX: "... LINE ALREADY EXIST).

Probably it does'nt work also for Warehouse Shipment because the function who copy the comment to shipment is similar.

**Comment by AndreyKorepanov** [comment]
Hi @FrancoOrazio, thank you for reporting the issue. Could you please provide slightly more info to make it easier to repro the bug: what app version do you use? what environment? repro steps? Thank you.

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
