### ISSUE TITLE
Business Central CU 03 GB Database Warehouse Shipment Post And Print

### ISSUE THREAD

**Issue by harshilpatel984** [Microsoft/AL#4545]
I am using CU 03 On prim GB version.
I am posting sales invoice and shipment from warehouse shipment. I need both report for posting sales shipment and sales invoice. 
Both reports are printing from RTC but when i am using Webclient only posted sales invoice report is downloaded instead of both reports.
I have debug this process and found that base code is written for printing both reports in codeunit 5763. But I am getting only sales invoice report.

```
IF Print THEN
          IF "Source Document" = "Source Document"::"Sales Order" THEN BEGIN
            SalesShptHeader."No." := SalesHeader."Last Shipping No.";
            SalesShptHeader.SETRECFILTER;
            SalesShptHeader.PrintRecords(FALSE);
            IF Invoice THEN BEGIN
              SalesInvHeader."No." := SalesHeader."Last Posting No.";
              SalesInvHeader.SETRECFILTER;
              SalesInvHeader.PrintRecords(FALSE);
            END;
         END;
```

**Comment by AndreyKorepanov** [comment]
Hi,
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by harshilpatel984** [comment]
I found this is a bug because code us already there.
