### ISSUE TITLE
[ControlAddIn] Use "Previous" Page Button remove controladdins in page 

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#4546]
**Describe the bug**
In a page in where I have some controladdins (three). The first time I open it, if I click the Previous button, two of my controladdins are disappearing one by one as you can see in the gif bellow:

 ![addinbug](https://user-images.githubusercontent.com/29598240/51978187-beb28200-2489-11e9-923a-bfd9d9902f1d.gif)

I can't reproduce it if I open the page again. I have to CTRL + R before.

If I hit ESC key the page closes correctly.

The "weird" thing too is that the canvas (second group) which is also a controladdin is not disappearing.

Appends on a List Page type object:
```
<layout
   <area
      <group
            repeater
                 field
                       ...
        >
      <group
              usercontrol(canvas)
       >
       <group
              usercontrol(first) (disappears)
              usercontrol(second) (disappears)
        >
   >
>
```

I don't know if it's a bug, if it's not, Could you please tell me why does the page / my controladdins are acting like this ?

Thank for any help

**Versions:**

 - AL Language: 2.1.79379

 - Business Central: W1 13.3 (27233)

**Comment by JulienDecottignies** [comment]
Hi @AndreyKorepanov ,

I've attached a zip file containing the piece of code to reproduce the issue.

[#4546_controladdinissue.zip](https://github.com/Microsoft/AL/files/2827019/4546_controladdinissue.zip)

**Comment by AndreyKorepanov** [comment]
Hi @JulienDecottignies, we I've tried your code on 14.x/15.x/latest BC versions and could not repro the issue. Are you still experiencing the problem? Could you try it on the latest BC version?

**Comment by JulienDecottignies** [comment]
Hi,

No i'm not. I close the issue. Thanks
