### ISSUE TITLE
PageExtension addfirst non-functional when using groups

### ISSUE THREAD

**Issue by mjmatthiesen** [Microsoft/AL#4547]
**Describe the bug**
When extending a role centre, addfirst does not work if a group is used.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
[See the following repo](https://github.com/mjmatthiesen/al-rolecentre-bug).

**Expected behavior**
When addfirst is used, the added group (with actions) should be first in the interface.

**Screenshots**
[Screenshot](https://i.imgur.com/WypHmcL.png)

**Versions:**
 - AL Langauge: 2.1.69331
 - Business Central: CA Dynamics NAV 13.3 (26990)

Is this intended behaviour? Is my code incorrectly formatted? Or is it just a bug / unexpected usage?

**Comment by AndreyKorepanov** [comment]
Hi @mjmatthiesen, thank you for reporting issue. Yes, it is intended behaviour, nothing wrong with your code. The items in the Reporting area are sorted, so that the groups are always in the end of the list. No way to change it from Al, just take it into account adding the new groups and actions.
