### ISSUE TITLE
Option datatype giving error through API (POSTMAN)

### ISSUE THREAD

**Issue by ashik-ivor** [microsoft/AL#4548]
Hi,

I have created a page type API. I am able to GET the data and Modify the data through POSTMAN application.

![image](https://user-images.githubusercontent.com/38459860/52037984-c3913780-2556-11e9-9bf6-4c611c0cec4b.png)

But when I am trying to POST data, the field TransactionType (OPTION datatype) variable giving me an error. 

Eg: I have 4 options, 'Sales Invoice, Purchase Invoice, Sales Journal, Purchase Journal'.
I am able to POST data with 3 values "Purchase Invoice, Sales Journal, Purchase Journal" but not able to POST data with option type "Sales Invoice".

![image](https://user-images.githubusercontent.com/38459860/52037877-5f6e7380-2556-11e9-9818-fceb85906b8d.png)

![image](https://user-images.githubusercontent.com/38459860/52037756-e707b280-2555-11e9-9699-d4bddeeba194.png)

Also, there is no code OnValidate of the Field "Transaction Type" on the table.

**Comment by AndreyKorepanov** [comment]
Hi @ashik-ivor, thank you for reporting the issue. Could you, please, provide slightly more information: what version of BC, what environment, source code?

**Comment by ashik-ivor** [comment]
@AndreyKorepanov  
I am using BC sandbox environment "CA Dynamics NAV 13.2 (27692)".

**Comment by qutreson** [comment]
Hi @ashik-ivor, can you try reproducing this issue on the latest developer preview?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
