### ISSUE TITLE
How to do Changes in fields display in web client

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4549]
I wanted to change the view of displaying the fields in the grid view 

![image](https://user-images.githubusercontent.com/44765649/52046578-0c53eb00-256d-11e9-921c-1d33d7feb3ef.png)

**Comment by ashik-ivor** [comment]
![image](https://user-images.githubusercontent.com/38459860/52050784-a91b8600-2577-11e9-919f-388c6bdb2308.png)

**Comment by AndreyKorepanov** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
