### ISSUE TITLE
Ability to create SIFT on standard tables using AL

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#4551]
Need the ability to create SIFT on standard tables.  This is a crucial feature for many of our add-on.  Without this many ISV, like us will not be able to adapt extension V2.  Currently we have stopped all our effort to convert our vertical to extension due to this.

**Comment by Rama-M** [comment]
Hi Andrey,

Using C/Side i know you can create new SIFT in standard table like G/L Entry table. Can the same is available in AL using extension? Can you please clarify.

**Comment by Rama-M** [comment]
Hi Andrey,
My question is related to any restrictions when it comes to creating SIFT. The requirements are exactly the same for index creation see call #4550 in AL.

We want to do the following using AL language in an extension when extending standard table.

1) Creting SIFT on existing standard fields in standard table.
2) Creating SIFT on newly created fields in a standard table.
3) Creating SIFT which involves both standard and new fields in a standard table.

Can you please confirm if AL language supports all the 3 scenarios. If not, can you kindly add this requirement to your future release.

We tried to convert our vertical solution to extension and hitting practical issue and limitations and this has prompted me to raise this request.

**Comment by yandko** [comment]
@AndreyKorepanov do you have any updates on this one. What is the target delivery date? Crucial for our vertical as well.

**Comment by nndobrev** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the latest compiler?
