### ISSUE TITLE
Query Object to be cashed in Service Tier

### ISSUE THREAD

**Issue by Rama-M** [Microsoft/AL#4552]
We need the Query object to be cashed in service tier.  Currently Query Objects are not cashed in service tier as a result it's use is limited in the code for performance reasons.  Can this restriction could be relaxed so that like rest of the objects Query object will be cached in service tier.

**Comment by AndreyKorepanov** [comment]
Hi @Rama-M, thank you for reporting the issue. 
BC does not cache query results, it always gets the data directly from SQL Server. We do not plan to change this strategy, but query performance can be significantly improved by using for example covering indexes. For more information, please, refer:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-query-objects-and-performance

**Comment by Rama-M** [comment]
Hi Andrey,
You mis understand my question. The service tier caches the data for normal CSide and AL code. However if a Query object is used to gather data the data are not cached currently. My request is to change this behaviour to cache the data obtained via running a query object to behave the same as data gathered using CAL or CSide code.
