### ISSUE TITLE
The TestClient is not installed on the server.

### ISSUE THREAD

**Issue by stefanoPrimo** [Microsoft/AL#4555]
**Describe the bug**
Hi, I've multiple environments with the same version in order to run multiple times the Test codeunits.
With my last extension I've made also the test codeunit but this time the test Tool returns this error for all the Procedure that I've written:
`The TestClient that is needed for page testability is not installed on the server.`

I don't think that my procedures are broken and I can truly say it because this happens only for one environment.

Thanks in advance

**Versions:**

 - AL Langauge: 2.1.79379 / 

 - Business Central: RTM

**Comment by AndreyKorepanov** [comment]
Hi @stefanoPrimo, thank you for reporting the issue. Could you, please, provide slightly more details? What is BC version? what are the reproduction steps, environment, in what moment did you get the error?

**Comment by stefanoPrimo** [comment]
Currently, I have 2 environments both Version 13.0.24623.0.
Honestly, I don't really know how to reproduce this issue. One environment executes the tests returning a success, the other one returns the error.
The other apps that I've already made and tested work perfectly in both the environments, only the last ones have this problem.

**Comment by stefanoPrimo** [comment]
Hi,
After a while, I found the problem: During the installation of Business Central I didn't check the "PageTestability" flag and so my server instance was missing these files:

```
Microsoft.Dynamics.Framework.UI.Navigation.dll
Microsoft.Dynamics.Framework.UI.UX2006.dll
Microsoft.Dynamics.Nav.Client.Builder.dll
Microsoft.Dynamics.Nav.Client.ServiceConnection.dll
Microsoft.Dynamics.Nav.Client.TestPageClient.dll
```

It will be very helpful if there were a documentation page!
For now thanks

**Comment by sandeepkumar022** [comment]
Good Day
I am working on CAL Test Tool.
Could  you please tell me how to Enable this property.
Thanks
