### ISSUE TITLE
Cannot hide fields of a subform depending on field value.

### ISSUE THREAD

**Issue by martinhocosta88** [microsoft/AL#4556]
I'm aware there is a limitation of hiding fields in a page depending on a field value. Like this article says, inserting the fields inside the group resolves the problem.
https://demiliani.com/2018/09/17/dynamics-365-business-central-show-hide-fields-on-pages/

But this time I have an issue because I want to hide some fields on my SubForm depending on my series type. Just realized I cannot insert them inside of a group because groups are not allowed inside a repeater. Since the page is a list page, the fields are inside a repeater.

Any other way for me to hide those fields based on a condition?

**Comment by nareshbandariD365** [comment]
Hi @martinhocosta88 , 

It is not possible to hide a field on list or subform pages based on field value due these will display multiple records at a time. Instead, you can hide field value.

**Comment by martinhocosta88** [comment]
Hi @nareshbandariD365,
I think I understand what you mean, but in my case I want to hide it based on a value from a configuration in another record, not in the Lines/List record.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
