### ISSUE TITLE
OnAfterUpdateDocumentTypeAndAppliesToFields() event cannot be subscribed

### ISSUE THREAD

**Issue by jeffgit** [Microsoft/AL#4557]
**Describe the bug**
OnAfterUpdateDocumentTypeAndAppliesToFields() event cannot be subscribed for some reason even though it's published and raised on Table 81.

**To Reproduce**
Create a codeunit and add Event Subscriber function to subscribe the event OnAfterUpdateDocumentTypeAndAppliesToFields() from Table 81 "Gen. Journal Line".

**Expected behavior**
The event should be visible and able to be subscribed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2955741/52090340-ed9e2600-2565-11e9-9213-175ade60a79c.png)
However, the event can be found in the dal file, please see below.
![image](https://user-images.githubusercontent.com/2955741/52090466-4d94cc80-2566-11e9-8a08-182021b40ce6.png)

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: US Dynamics NAV 13.3 (27233)

**Comment by jeffgit** [comment]
Additional screenshot for the place where the event is raised.
![image](https://user-images.githubusercontent.com/2955741/52090707-f9d6b300-2566-11e9-9876-673ef6326d41.png)

**Comment by AndreyKorepanov** [comment]
Hi @jeffgit thank you for reporting the issue, it looks like a bug. Could you, please, provide us the event publisher code to make it easier to reproduce the issue?

**Comment by jeffgit** [comment]
It's from the native object Gen. Journal Line table as in the screenshot above.

**Comment by thpeder** [comment]
Hi @jeffgit,
I have set up a US server, downloaded the symbols and wrote a codeunit that subscribes to said event, and it worked. So I'm not sure what failed for you.
You can try and recreate the symbols by following this feature: [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side)

Have you done modifications to the C/AL objects?

**Comment by jeffgit** [comment]
Thanks. I tried downloading the symbol again, restart VSC, it works now. This issue can be closed.
