### ISSUE TITLE
On Condition AssistEdit button not working in Workflows D365BC CU3

### ISSUE THREAD

**Issue by nareshbandariD365** [Microsoft/AL#4558]
I'm unable to define a workflow in business central due to OnCondition AssistEdit not working.
Below is the screenshot:

![image](https://user-images.githubusercontent.com/43364621/52106495-09aecf80-2619-11e9-8de2-d6da16cc851c.png)

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by AndreyKorepanov** [comment]
Hi @nareshbandariD365, thank you for reporting the issue. Could you, please, provide slightly more information: BC version, your browser, environment?

**Comment by nareshbandariD365** [comment]
Hi @AndreyKorepanov , 
Thanks for responding, please find details below:

Versions:
AL Language: 2.1.79379
Business Central: 13.0.27183 (Cumulative Update 03 W1)

**Comment by thpeder** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by CyrilleCargo** [comment]
Hi all,
Have you news for this trouble ?
It's not solve for us :(

**Comment by finn777** [comment]
Should be fixed (platform fix) in upcoming cumulative update BC 365 (on-Prem) CU04/CU05

**Comment by dantherriault** [comment]
Does anyone know if this was ever fixed and, if so, which CU fixed the issue?
