### ISSUE TITLE
EnumExtension Support

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#4559]
Before I create a scenario for review, does BC130 CU3 support the creation/use of EnumExtensions based upon an Option field marked as extensible in a base object (e.g. Document Type in Sales Header)?

**Comment by AndreyKorepanov** [comment]
Hi @GreatScott000. Yes, you can extend extensible Options with EnumExtensions in the same way as normal Enums. For more information, please, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums
