### ISSUE TITLE
Standard Table Field Keys in Table Extension

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#456]
Hi,

Creating extension for table and trying to add key by using standard field but AL is not allowing /compiling 

 **'"Posting Date"' in application object 'ItemLedgeEntryExtension' does not exist'**

For field which is added in extension is allows to create.

**Comment by esbenk** [comment]
Yes. We currently only allow adding keys with fields from the tableextension itself. We are investigation if we can remove that restriction in a future update.

**Comment by AmolSalvi** [comment]
Thank you so much and hope restriction will be removed in near future.

**Comment by jcooper01** [comment]
Do you have an update on this? It's something that I believe that most ISVs will need (we certainly do).

**Comment by gunnargestsson** [comment]
tableextension 10935 tableextension10935 extends "G/L Account" 
{
  // version NAVW111.0

  fields
  {
    field(10900;"IRS Number";Code[10])
    {
      CaptionML=ENU='IRS Number',
                ISL='Númer á rekstrarframtali';
      TableRelation="IRS Number";
    }
  }
  keys
  {
    key(IRS; "IRS Number", "No.")
    {}
  }
}


Error is:

message: 'Reference '"No."' in application object 'tableextension10935' does not exist' at: '16,28'

**Comment by pmohanakrishna** [comment]
we have around 50+ errors in our app while converting to extension 2.0.
any update or alternative?
