### ISSUE TITLE
Query - OData Filter does not work with new table/query

### ISSUE THREAD

**Issue by mhiDynalogic** [Microsoft/AL#4563]
This bug may relate to #4517 

New table and query using extension - just a small example:

![image](https://user-images.githubusercontent.com/46438214/52211866-60bbdb00-288b-11e9-8d05-1ed541cfb8a9.png)

When opening the query WITHOUT filter - is shows data.
When adding a filter ( ex "filter=test eq 1") to the URL - it shows this error:

![image](https://user-images.githubusercontent.com/46438214/52211931-8b0d9880-288b-11e9-8be8-20025a78e6c9.png)
( Message translated:  The object type Table with id 70105 was not found )

Version: 13.0.24623.0

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
