### ISSUE TITLE
Request for event in codeunit 11

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#4565]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

We would like to avoid the error with "Job No." as empty for this we need a publisher for it

In codeunit 11 CheckBalAccountNo() function we need a on publisher with 

OnAfterCheckBalAccountNo(GenJnlLine,CheckDone);

![image](https://user-images.githubusercontent.com/39740300/52219416-96c88180-28c2-11e9-8ea2-4ee7857b1820.png)

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: [https://github.com/Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions)
