### ISSUE TITLE
REST webservice setting headers correct

### ISSUE THREAD

**Issue by Hornsyld** [microsoft/AL#4566]
I have the same issue as  [#1911](https://github.com/Microsoft/AL/issues/1911).
"Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects."

I am a bit stuck, so I hope you can help.

I used the POST example in the other thread.

My code looks like this

```
    procedure foo();
    var
        gcontent: HttpContent;
        gHttpClient: HttpClient;
        gheaders: HttpHeaders;
        greqMsg: HttpRequestMessage;
        gResponseMsg: HttpResponseMessage;
        ltext: Text;
        lheaders: HttpHeaders;
        lurl: text;
        lresptext: text;
    begin

        lurl := 'http://distribution.virk.dk/cvr-permanent/_search' + '&country=dk&format';
        ltext := '{"from": 0,"size": 1,"_source": ["Vrvirksomhed.virksomhedMetadata.*","Vrvirksomhed.virksomhedMetadata.nyesteNavn.navn"],"query":{"term": {"Vrvirksomhed.cvrNummer": 19263096}}}';

        gHttpClient.DefaultRequestHeaders.Add('Authorization', 'Basic' + lbase64key);
        gHttpClient.DefaultRequestHeaders.Add('Content-Type', 'application/Json');
        gcontent.Clear();

        gcontent.WriteFrom(ltext);

        lheaders.Clear();

        gcontent.GetHeaders(lheaders);
        lheaders.Remove('Content-Type');
        lheaders.Add('Content-Type', 'application/Json');
        gcontent.GetHeaders(lheaders);

        if not gHttpClient.Post(lurl, gcontent, gResponseMsg) then
            Error('API Authorization token request failed...');

        gResponseMsg.Content.ReadAs(lresptext);
        Message(CopyStr(lresptext, 1, 100));

    end;
```

In Postman it looks like this :
![postman1](https://user-images.githubusercontent.com/6792253/52219760-8fdb4800-289d-11e9-8c47-831690aee2af.PNG)
![postman2](https://user-images.githubusercontent.com/6792253/52219761-9073de80-289d-11e9-9363-c3c420d9d599.PNG)

**Comment by JohanStenberg100** [comment]
Hi @Hornsyld! As you might have guessed, the AL HttpClient is a thin wrapper around the .NET HttpClient, which divides headers into two groups - content headers and request headers. Here is a list of request headers: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httprequestheaders?view=netframework-4.8 and here is a list of content headers: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpcontentheaders?view=netframework-4.8.

You are assigning a content header (`Content-Type`) to the request headers in your example, this will not work. Just remove this line: `gHttpClient.DefaultRequestHeaders.Add('Content-Type', 'application/Json');` and you should be good to go. Also as an extra tip, don't forget the space between `Basic` and your Base64 key in your code.

I will close this issue now, please comment here if you still are experiencing issues. Open a new issue if you run into a new problem. Thanks!
