### ISSUE TITLE
Modified caption doesn't show in Tell me

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/AL#4569]
**Describe the bug**
When I change the caption of a page in a pageextension object, the new caption does not show in 'Tell me'.

**To Reproduce**
Create a pageextension for the Vendor List, and set the Caption to 'Suppliers'. Publish the app and you can see that the caption has indeed changed. Open 'Tell Me' and type 'Suppliers', this doesn't yield any results. Search for 'Vendors' and you get the regular Vendor List. Open that and the caption has changed to 'Suppliers'

**Expected behavior**
I expect to be able to search using the new caption.

**Screenshots**
Search for 'Suppliers':
![image](https://user-images.githubusercontent.com/23434319/52247777-7f7c9a80-28a8-11e9-95da-934199fd4a71.png)

Search for 'Vendors':
![image](https://user-images.githubusercontent.com/23434319/52247813-9a4f0f00-28a8-11e9-98b8-494ec2696517.png)

Note that the caption of the Vendor list is 'Suppliers'

**Versions:**
 - AL Langauge: 2.1.79379
 - Business Central: GB Dynamics NAV 13.2 (26556)

**Comment by qutreson** [comment]
Hi @TheDenSter, thank you for reporting this issue. This is a problem that we are aware of and that we have on our backlog. We will use this issue to track this problem on Github.

**Comment by TheDenSter** [comment]
Thanks for the comment, do you have any idea when this will be implemented?

**Comment by pborring** [comment]
This is a missed scenario for caption extension, which require some rework of the search page. This means it will take some time (months at this point), before we will address it.

Also, note that there can be a race condition - if multiple page extensions override the caption, the last loaded will be shown in UI. We could still allow search to support the variants, all pointing to the same page. Once we support last mile extensions (i.e., a PTE being loaded last), the partner will be able to resolve race conditions like this and decide who wins.

**Comment by TheDenSter** [comment]
Alright thanks Peter. In a multi-extension scenario I think it would be great if you could find the page by using the captions for all extensions, at the very least by the caption of the original page object. Kind of like how in my example, if my app changes the caption to 'Suppliers', you would still be able to find the vendor list by using 'Vendors' as the search term.

**Comment by mpopelka** [comment]
Has there been any progress into this? I am running into the same issue with a client wanting to change a large amount of captions. In my attempts changing captions(ml), or additionalsearchterms(ml) does not resolve this issue.

**Comment by pborring** [comment]
This is fixed in v15 (2019 Wave 2) CU1 - translation and AdditionalSearchTerms works for pageextensions. 

Note that XLIFF translations take precedence if present (as applied after metadata flattening of extension contributions), so if doing a pageextension of a base object like Vendor, you need to provide the caption in XLIFF and not as a Caption property in the pageextension object. Also, if multiple extensions change the caption property or XLIFF translation, the last loaded extension "wins".

**Comment by TheDenSter** [comment]
Thanks Peter, I'll check it out
