### ISSUE TITLE
al and Arrays

### ISSUE THREAD

**Issue by KaiSwitalla** [Microsoft/AL#457]
Hello all,

how can i define a new variable (for example a global variable of type integer) as an Array (2,9) ? What is the Syntax to do it. Can you post an example? Thank you.

**Comment by esbenk** [comment]
`
codeunit 70770077 MyGlobal
{
    var
        arr : array[2,9] of Integer;
}
`

**Comment by KaiSwitalla** [comment]
Thanks!
