### ISSUE TITLE
How to modify field property TableRelation

### ISSUE THREAD

**Issue by StephanFeijen** [Microsoft/AL#4571]
Property TableRelation of field "No." in table Item needs to be extended with an extra condition.
So instead of ... if (Type = CONST (Item)) Item WHERE (Blocked = CONST (false),
                    "Sales Blocked" = CONST (false))
it needs to be … if (Type = CONST (Item)) Item WHERE (Blocked = CONST (false),
                    "Sales Blocked" = CONST (false),
                    "Standard Item" = CONST (true))
I've added boolean field "Standard Item" as a table extension on table Item.
How do I solve this issue?

**Comment by esbenk** [comment]
In the spring release we will support adding additional conditional relations like

`If(Type = Const(Resource)) Resource WHERE(Blah)`

we don't currently have a way to modify an already existing line.

**Comment by StephanFeijen** [comment]
OK, Thanks for your answer.
We'll wait till spring.

**Comment by esbenk** [comment]
The current design for spring won't solve your problem. You can add new lines, but since the lines are evaluated top down you will get the original line first without the additional Where(StandardItem = Const(true))
We will evaluate if we can change the design so it is possible to also support your scenario.

**Comment by TRASERDanielGorski** [comment]
After the spring release, we can modify the table relation but the system does not recognize it.
Is it planned to break the top-down evaluation for table relations?

**Comment by dtkb** [comment]
It seems like this should be reopened, if it didn't solve the problem and you still need to evaluate a larger fix.

**Comment by atoader** [comment]
Please file a BCIdea for requests for additional enhancements.
