### ISSUE TITLE
CodeCop rule for unused procedures

### ISSUE THREAD

**Issue by eclipses24** [microsoft/AL#4572]
Hi,

I've enavbled the Code Analysis and tested a bit the funcitonality. I've noted that it does not retrieve possible variables/functions declared but never used.

In my opinion at least a worning should appear.

I know that the developers can see the number of references in VS Code but I need a valid check to include in my scripts for Continuous Integration.

**Comment by qutreson** [comment]
Hi @eclipses24, we have a code cop rule for verifying that variable which are not used (see code cop rule [AA0137](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop)). We currently don't have a rule for finding methods which are not used. So you should at least get a warning for unused variables.

![image](https://user-images.githubusercontent.com/31541422/52402981-ed51dd80-2ac5-11e9-9c92-0334abadca7b.png)

Are you not getting these warnings about unused variables?
Which version of the AL extension are you using?

Please refer to [Using the Code Analysis Tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool) for information on how to enable code analyzers in AL.

**Comment by eclipses24** [comment]
Hi, 

I'm not getting these warnings.
I'm using the latest version ms-dynamics-smb.al-2.1.79379

Here my workspace settings
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${CodeCop}",
        "${UICop}"
    ]    
}

**Comment by IvoMol** [comment]
By our opinion, missing warning is only for unused **global** variables.

**Comment by eclipses24** [comment]
By my opinion to avoid to release _useless/unused code_ it should be valid for **local** as well. 

By the way, it does not work for me with **global**
![image](https://user-images.githubusercontent.com/46592566/52404415-3e170580-2ac9-11e9-858b-ffa47ff5f283.png)

**Comment by eclipses24** [comment]
> "We currently don't have a rule for finding methods which are not used."

Can you please consider to add a new rule for it as well?

**Comment by qutreson** [comment]
This rule is implemented for both global and local variables.

![image](https://user-images.githubusercontent.com/31541422/52407407-81c13d80-2ad0-11e9-82cd-428f827ee162.png)

The issue has been fixed in our master, so if you use the latest developer preview, all unused variables would be reported, but I could reproduce your issue with the extension from the marketplace. This will be available with the next major release.

We will use this issue to track the improvements of CodeCop in order to report a diagnostic on unused procedures.

**Comment by eclipses24** [comment]
Hi, 
perfect, thanks, I will wait for the new release. 

Can you confirm that if a run from command prompt ALC.exe I will receive same error/wornings?

When is planned to happen the new release in the market?

Thanks

**Comment by ashik-ivor** [comment]
You can try restarting your VS code or your system once you change the settings. 

Hope this helps.

**Comment by eclipses24** [comment]
Hi ashik-ivor,

They replied that was a bug and it has been fixed

> The issue has been fixed in our master, so if you use the latest developer preview, all unused variables would be reported, but I could reproduce your issue with the extension from the marketplace. This will be available with the next major release.

**Comment by MarcHansenMicrosoft** [comment]
This should be working now
