### ISSUE TITLE
Txt2Al not handling CAL option fields with enum assigned

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#4574]
**Issue:**
When using Txt2AL to convert a table that contains an option field that has an Enum assigned, the resulting AL file contains compile errors. Example below.

![convertenumoption3](https://user-images.githubusercontent.com/5204734/52407064-3ccfe380-2a9d-11e9-9755-3e1345936c86.png)

![convertenumoption](https://user-images.githubusercontent.com/5204734/52406772-7e13c380-2a9c-11e9-8cc3-9e9bee4c2459.png)

**Expected Result**
Would be nice if the option field was changed to an enum field in the AL file. Would also be great if the enum object file was also created. Example below.

![convertenumoption2](https://user-images.githubusercontent.com/5204734/52407005-16aa4380-2a9d-11e9-9a87-f0e9d21c18b9.png)

**Comment by qutreson** [comment]
Hi @MikeGlue are you using our latest developer preview? This bug should have been fixed there some time ago.

**Comment by MikeGlue** [comment]
I tried this with the BC on prem CU1 Docker image. I can try with the latest daily build if you think it's fixed there.

**Comment by MikeGlue** [comment]
Yes this does work as expected in the daily build image I'm using. My mistake for not trying that first. :(
