### ISSUE TITLE
Codeunit 1012 OnBeforeInsertJobLedgEntry - please add this before JobLedgEntry.INSERT(TRUE); so we can move custom fields from job journal to job ledger

### ISSUE THREAD

**Issue by davmac1** [Microsoft/AL#4576]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: [https://github.com/Microsoft/ALAppExtensions](https://github.com/Microsoft/ALAppExtensions)
