### ISSUE TITLE
Publish an App with DotNet requirements does not look into Add-ins folder

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/AL#4578]
**Describe the bug**
The DLL is added to the Add-ins cache folder.  The Service Tier will pick them up for compiling.  Publishing an app does not look into that Add-ins cache folder and we need to restart the service tier after adding the DLL to get this to work.

**To Reproduce**
Copy a DLL into the Add-ins cache folder.

```
local procedure GetApplicationVersion() ApplicationVersion: Text
var
    FileManagement: Codeunit "File Management";
    ServerFileVersionInfo: DotNet FileVersionInfo;
begin
    ServerFileVersionInfo :=
      ServerFileVersionInfo.GetVersionInfo(
        FileManagement.CombinePath(ApplicationPath(), 'Microsoft.Dynamics.Nav.Server.exe'));
    ApplicationVersion := ServerFileVersionInfo.FileVersion();
end;

local procedure GetAddinsFolder() AddInsFolder: Text
var
    FileManagement: Codeunit "File Management";
    Environment: DotNet Environment;
begin
    AddInsFolder :=
      FileManagement.CombinePath(
        FileManagement.CombinePath(
          FileManagement.CombinePath(
            Environment.GetEnvironmentVariable('TEMP'),
            'Microsoft Dynamics NAV\Add-ins'),
          GetApplicationVersion()),
        'Advania');
end;
```

That DLL is used in the App and is in the .netpackages folder.

**Expected behavior**
App should publish without issues.

**Screenshots**
![appissue](https://user-images.githubusercontent.com/23558797/52465779-ca800180-2b77-11e9-9573-4dcae0592a16.PNG)

Restart the service tier
![restartservice](https://user-images.githubusercontent.com/23558797/52465832-fd29fa00-2b77-11e9-8e80-1c8e54dda8b8.PNG)

Publish works fine
![published](https://user-images.githubusercontent.com/23558797/52465868-1fbc1300-2b78-11e9-882c-fc71cb0c1d5c.PNG)

**Versions:**
"country":  "is",
"created":  "201901171535",
"cu":  "",
"eula":  "https://go.microsoft.com/fwlink/?linkid=861843",
"legal":  "http://go.microsoft.com/fwlink/?LinkId=837447",
"maintainer":  "Dynamics SMB",
"nav":  "",
"osversion":  "10.0.17763.194",
"platform":  "13.0.27183.0",
"tag":  "0.0.9.0",
"version":  "13.3.27233.0"

**Comment by thpeder** [comment]
Hi @gunnargestsson,

This is by design, since it can be a considerable performance hit to look through the GAC, the Add-ins folder, etc. every time it compiles an extension.
We are aware that there a room for improvements.

**Comment by atoader** [comment]
One way of improving this could be to use a file system watcher in the service and listen for changes in the folders included in the assembly probing paths.

**Comment by nndobrev** [comment]
Hi, unfortunately, this is a very niche scenario that we still don't support. In addition, this is consider an improvement and not an issue, please feel free to log it into aka.ms/BCIdeas.
