### ISSUE TITLE
Feature suggestion: replace PromotedActionCategories with a proper way to add new menus

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#4580]
Right now, the way to create custom menu actions in a Page is to assign the list of menus to the PromotedActionCategories property of a page, but this is prone to conflicts if several page extensions try to modify the property. 

Not only that, the current method is cumbersome to use, as you have to assign a meaningless Promoted Category (Category7) to your actions, which makes it quite a lot of fun when you decide to insert a new menu menu between the existing ones.

To make matters even more thrilling, there are action menus (Page 7326) that "are just there" by means of magic, or something (see https://www.yammer.com/dynamicsnavdev/threads/1235750900 ).

Giving us a "Promoted" property to an action group would probably be enough to replace the current feature (or to give a second way to do it, which would be better to maintain compatibility).

As an added benefit, this would open the way to define icons for the action menus.

**Comment by qutreson** [comment]
Hi @salgiza, thank you for your suggestion. This is something that we are aware of and improving the programming model around promoted actions is on our future backlog.

**Comment by qutreson** [comment]
Closing this issue as there have been investments in defining a new syntax that captures more explicitly the structure of the action bar, see https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-promoted-actions. You can also define new categories inside the Promoted area now which should minimize potential conflicts.
