### ISSUE TITLE
Crash in textDocument/didChange upon save (autoformat?)

### ISSUE THREAD

**Issue by extensionsv2training** [Microsoft/AL#4582]
I'll just leave this here. Don't know how to reproduce. It messed up my source code with random spaces etc. while it crashed, luckily I had version control. After restarting VS Code didn't happen again.

![vscode_crash](https://user-images.githubusercontent.com/42800440/52498515-b07b0900-2be1-11e9-8441-87f6dd453c3f.JPG)

**Comment by thpeder** [comment]
Hi @extensionsv2training,

Thanks for reporting the issue, but it is really hard to find and fix the issue if we don't have more information.
If you run into the issue again and can provide some reproduction steps then feel free to open a new issue.
