### ISSUE TITLE
Improvement of moving to Extensions

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#4583]
Moving forward to extensions I transfer the customizations of our customers (tables, fields and code) with **txt2al** into an extension. That works very nice.

Now what I need is an easy way of transferring the data into the extension. It would be nice if I could delete the tables and fields in the classic development environment with synchronization schema later and when publishing the extension with same table and field ids the Service Tier could move the removed fields into the companion table and the tables into the extension table.

**Comment by thpeder** [comment]
Hi @DanielGoehler,
Thanks for your suggestion!

**Comment by nicolassaleron** [comment]
Hello,
This is a must have if we intend to move existing Dynamics NAV customers to Business Central.
We have a procedure described here: https://capvision.visualstudio.com/Capvision.Innovation.UpgradeFromCAL
But it cannot imagine using it for large databases.
