### ISSUE TITLE
Suggestion: Non-Breaking Dependencies should not prevent publish a new version of an Extension

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#4584]
Regarding #2804, I suggest that even if other extensions depend on an extension it, while publishing the Service Tier should check further if this chance breaks the dependent extensions.

What I experience (even with Build 14.0.27617 aka Partner Preview 04 of April Release) that if I rearrange page extensions fields on a page with the new Designer (which saves that changes as Designer Extension) and try to publish the base extension I get the error message:

`The request for path /bc140/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The extension was unable to be deployed due to a dependency between extensions.`

Even though I didn't change anything in the extension. As long I don't remove that rearrange fields in the page extension publishing should be possible.

**Comment by thpeder** [comment]
Hi @DanielGoehler,

Thanks for your suggestion, but I'll ask you to keep the discussion on the thread you linked to, since it involves the general workflow of having multiple extensions with dependencies.
