### ISSUE TITLE
AA0008 reports warning when using options of TEXTENCODING collection

### ISSUE THREAD

**Issue by JuricaB** [microsoft/AL#4587]
**Describe the bug**
Code Analyzer reports AA0008 reports : 
You must specify open and close parenthesis after 'TextEncoding'.

This is reported on following line and TEXTENCODING option should obviously not have parentheses:

currXMLport.TextEncoding(TEXTENCODING::MSDos);

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
Declare XMLPort variable, add line as per above.

**Expected behavior**
Compiler should differentiate between function TextEncoding and collection TextEncoding

**Screenshots**
![image](https://user-images.githubusercontent.com/24306390/52543165-3c707900-2e0c-11e9-8940-4ceb84c0aa96.png)

**Versions:**

 - AL Language: 2.1.91153

 - Business Central: NZ Dynamics NAV 14.0 (27970), platform 14.0.27940.0

**Comment by JuricaB** [comment]
Hi folks, 

This is still an issue with AL extension 3.0.115791, Platform 14.0.29608.0 + Application 29651 (NZ Dynamics NAV 14.0)

Any ETA on resolution?

Thanks,
Jurica

**Comment by JuricaB** [comment]
This is still an issue with AL extension 4.0.182565.

**Comment by MarcHansenMicrosoft** [comment]
Fixed in master
