### ISSUE TITLE
Part Page in API page not visible in POSTMAN

### ISSUE THREAD

**Issue by ashik-ivor** [Microsoft/AL#4591]
I have an API page (Header) in which I have declared a part page(Line). 
All the properties are also set, ApplicationArea, EntityName, EntitySetName, Caption, SubPageLink.

I am able to GET the data of the header through POSTMAN. But when I include the Header ID and expand the line "**header(id)?expand=line**", I am not able to see the LINE information.

Complier : 2.1.79379
SandBox Environment : CA Dynamics NAV 13.2 (27692)

I tried to reset my Sandbox environment also, but still the same issue.

**Comment by henrikwh** [comment]
Hi ashik-ivor
It should work. But your url seems wrong.
Try 
- header(id)/?$expand=lines
- header(id)/lines
If those do not work, then please send a small sample that reproduces the issue.
/Henrik

**Comment by ashik-ivor** [comment]
Hi @henrikwh 

- Header(id)/lines are working fine **but** I wanted to expand the lines with the header. 

- salesheaders(id)?expand=saleslines
![image](https://user-images.githubusercontent.com/38459860/52614192-e86e9e80-2eb6-11e9-8df3-5fc31b9ac705.png)

- salesheaders(id)/?expand=saleslines
![image](https://user-images.githubusercontent.com/38459860/52614261-25d32c00-2eb7-11e9-9d7f-65d0ab1c83f9.png)
 
The problem here is I am not able to expand the lines with the header.

**Comment by henrikwh** [comment]
Hi @ashik-ivor
Your URL is still wrong. You're missing $
.../companies({{companyId}})/salesInvoices({{salesInvoiceId}})/?$expand=salesInvoiceLines
Above works.

A good reference is https://www.odata.org/getting-started/basic-tutorial/

If you still have an issue, then please share a sample of your custom API page, so I can reproduce.
/Henrik

**Comment by ashik-ivor** [comment]
Thanks, it worked. @henrikwh
