### ISSUE TITLE
Different properties for primary key and clustered index

### ISSUE THREAD

**Issue by narongschmidt** [microsoft/AL#4596]
Currently, if you define a key as `Clustered = true` it will become the primary key of the table. And it seems to work well the way it is in 90% of use cases, especially with natural keys.

However it would be even better if you could define the primary key as a separate property `PrimaryKey = true`.

This would enable us to accomplish some more efficient table designs when using sequential primary keys.

As far as backward compatibility is concerned, you could default the `PrimaryKey` attribute on the key that has the `Clustered` attribute and no separate `PrimaryKey` defined.

**Comment by Sunnyfrost** [comment]
Seems like a good idea

**Comment by meilel** [comment]
This is a great idea! I hope it will be accepted.

Many of my surrogate key tables I've created for my customers performed very poor on list pages. That could really improve them.

**Comment by kalberes** [comment]
Good idea, indeed.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.

We are constantly monitoring top ideas and will consider them for a future release.
