### ISSUE TITLE
what is source in field page snippet

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#46]
field(MyField;**# Source**)
          {
              FieldPropertyName = FieldPropertyValue;
          }

**Comment by freddydk** [comment]
On the VM, in the folder C:\DEMO\New Developer Experience\AL you will find some of the base objects as .al files (2 pages, a codeunit and a table). Source is the source expression (typically the same as the field name in the page). One example where they are different is the customized calendar field:
field("Customized Calendar";CalendarMgmt.CustomizedCalendarExistText(CustomizedCalendar."Source Type"::Customer,"No.",'',"Base Calendar Code"))

**Comment by pmohanakrishna** [comment]
so Its SourceExpr property in page. Thanks..

**Comment by pmohanakrishna** [comment]
Is this Source property working in preview?
I am trying to create a field like below and is not working 

pageextension 70000003 CheckComments extends "Job Card"
{
    layout
    {
        // Add changes to page layout here
        addlast(General)
        {
            field(Comments;ChechComments.CheckCommentsExist(Rec."No."))
            {
                Editable = FALSE;
            }
        }
    }

    var 
      ChechComments : Codeunit 70000000;
    
}

It added a field but not showing any check box.

![issue](https://cloud.githubusercontent.com/assets/23735402/21539082/1b5b3084-cdc9-11e6-9f5c-f1a8a083c209.png)
