### ISSUE TITLE
How to comment several lines of code in AL?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#460]
In C/AL we used {} to comment several lines of code https://msdn.microsoft.com/en-us/library/dd301180.aspx?f=255&MSPPError=-2147217396 

How should we do the same in AL?
// is working as expected

**Comment by johndcollins** [comment]
use 
/*
your commented
lines of code 
*/

**Comment by pmohanakrishna** [comment]
/*
multiple lines
*/
