### ISSUE TITLE
Enable AL tooltips to wrap nicely

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/AL#4600]
**Is your feature request related to a problem? Please describe.**
When long tooltips are specified in AL they don't wrap. That is, the entire tooltip is shown in a single line in the web client.
The tooltips from the standard application (specified in C/AL) wraps nicely on multible lines.

**Describe the solution you'd like**
I would like my tooltips to look at least as nice as the ones from the standard application.
I would prefer if I could also specify hard linebreaks like "&lt;br/&gt;" or "\\".

**Describe alternatives you've considered**
I have tried every character I could imagine that would give me a hard linebreak.

**Comment by dNsl9r** [comment]
Any update on this?

**Comment by EmilDamsbo** [comment]
Tooltips will automatically wrap in the Business Central web client. The behaviour is to fill the horizontal space available in the control's group:
![image](https://github.com/microsoft/AL/assets/67266681/910049d6-5cbf-41c8-bf00-9bc2c9966580)
