### ISSUE TITLE
Query 'Data Exch. Field Details' is missing in Business Central Symbols

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/AL#4601]
**Describe the bug**
Query 'Data Exch. Field Details' (1232) is not found in shipped Application Symbols

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
var
  DataExchFieldDetails: Query "Data Exch. Field Details";

not found

**Expected behavior**
Should be part of symbols.  If I compile Query and download symbols again I am happy.

**Screenshots**
![image](https://user-images.githubusercontent.com/23558797/52660256-3b684600-2ef7-11e9-8113-8166a70b2b4e.png)

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: 13.3.27233.0-is

**Comment by atoader** [comment]
@gunnargestsson was this fixed in subsequent versions? This might have to go to support to track down the root cause.

**Comment by gunnargestsson** [comment]
We have had several object missing in symbols.  But we are going to AL so who cares...
