### ISSUE TITLE
Sanbox environment with specific localization

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#4603]
Hello,

I have tried to create a Sandbox environment using this link: [https://aka.ms/getsandboxforbusinesscentral](https://aka.ms/getsandboxforbusinesscentral)

I always end up with a Cronus USA company. I suppose it means that the database is also that of the US localization.

Is there a way to create a Sandbox with a different localization?

Salut!
Laura Nicolàs

**Comment by JesperSchulz** [comment]
This is not really al language related either, but the AL team is very knowledgeable about the sandbox environment. I hope they can help. If not, please try our public forums:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by AskeHolst** [comment]
You always get a sandbox matching the country/region of you Azure AD. To create an online sandbox in a another country/region you need to create a new Azure AD tenant.

**Comment by ajkauffmann** [comment]
https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2018/11/08/get-a-demo-of-bc
