### ISSUE TITLE
[Question] CurrFieldNo not a System-Variable anymore?

### ISSUE THREAD

**Issue by CptBlaubart** [Microsoft/AL#4604]
Hey,
I'm really not sure if I'm missing the elephant in the room right now, or what is going on, but even though there are issues here, demanding features related to "CurrFieldNo" and it's existence is swiftly noted in this docs page here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-system-defined-variables

I'm not even able to use that variable. Is it discontinued and the references I found are remedies? Am I trying to receive it from the wrong object/in the wrong context? (I tried several)

I wanna open a new page and the filter of that page is based on the current field of the page I'm opening it from. - At least that was my plan. Maybe you know an alternative solution.

edit:
I'm currently working with OnPrem cu3 ch
- Application 13.0.27183.0
- System 13.0.12929.0
- Al Language 2.1.79379

I tried using CurrFieldNo in a page extension of the opening page, inside the opened page. As a parameter of Rec in both of the above objects. As a parameter of CurrPage on both objects. Based on other issues here, i assumed that CurrFieldNo might have been turned into the method "GetCurrFieldNo". - But I'm not sure anymore if i tried that one on all of the above options.

**Comment by thpeder** [comment]
Hi @CptBlaubart,
That is a bug in the documentation, it is only available inside table objects.

**Comment by SusanneWindfeldPedersen** [comment]
This will be fixed with the next refresh of our docs. Thanks for the feedback. Closing issue.
