### ISSUE TITLE
Compiling fails for apps with indirect dependencies

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#4605]
Scenario:
- App2 has dependency in app.json to App1
- App3 has dependency in app.json to App2

Now try and build app3......

When doing the above and using the VSIX that's available on the BC Daily Insider (bcinsider.azurecr.io/bcsandbox-master:us) image (version 2.1.91153 as of this post) you will get an error when building App3 because it wants the symbols for App1, which will not download unless you make a specific dependency to App1.

If you repeat the process but use the VSIX from the BC Sandbox (mcr.microsoft.com/businesscentral/sandbox:us) image (currently version 2.1.79379) the process will work without error and you will not need to add a direct dependency form App3 to App1.

I figure this is either a bug or a new feature. Please I hope this is a bug because if we have to add indirect dependencies like this then it will complicate a lot of things.

@epersnt created a nice AL project to prove this out. It has the repro steps to perform this scenario. 
https://github.com/epernst/AL-multi-dependency

**Comment by thpeder** [comment]
Hi @MikeGlue,
We did have a bug that when it was loading your dependencies then it also tries to loaded the dependencies of your dependencies (level 2 dependencies) which is fine, but in doing so it would also raise an error that the level 2 dependency was not there, That is fixed now.
However the designer is still that if you want to reference something then you need to specify that dependency, ie. we don't support transitive dependencies.

**Comment by MikeGlue** [comment]
Any idea when this fix will hit the insider images?   I agree, that if I need to reference something I need to put the dependency.

**Comment by qutreson** [comment]
Hi @MikeGlue, this fix is part of the current April 19 release and should have been in the insider images for some time now. Closing the issue then. If the issue still reproduces on those versions, please log a new issue.
