### ISSUE TITLE
Font issue on Reports with new container

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#4606]
**Describe the bug**
Recently we have build new container using build 1709 and we found issue on reports where in standard font like Seoug UI showing weird results. 

Do we need to add fonts into container ? or is this bug 

How do we add standard windows font in container ? 

![image](https://user-images.githubusercontent.com/17919257/52762930-4385ca00-304c-11e9-94a9-7b781714ae30.png)

Look at this font Arial Unicode MS
![image](https://user-images.githubusercontent.com/17919257/52763858-10ddd080-3050-11e9-9780-a480ec0590df.png)

**Comment by freddydk** [comment]
When you say build a container - I assume that you are running some of the NAV or Business Central containers?
If you are using NavContainerHelper, there is a function called Add-FontsToNavContainer, which will copy and install the fonts you specify.
```
PS C:\WINDOWS\system32> help Add-FontsToNavContainer -Detailed

NAME
    Add-FontsToNavContainer
    
SYNOPSIS
    Copy Font(s) to a Nav container
    
    
SYNTAX
    Add-FontsToNavContainer [[-containerName] <String>] [[-path] <String>] [<CommonParameters>]
    
    
DESCRIPTION
    Copies and registers missing fonts in a container to use in report printing or preview
    

PARAMETERS
    -containerName <String>
        Name of the container to which you want to copy fonts
        
    -path <String>
        Path to fonts to copy and register in the container
        
    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see 
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216). 

    -------------------------- EXAMPLE 1 --------------------------
    PS C:\>Add-FontsToNavContainer

    -------------------------- EXAMPLE 2 --------------------------
    PS C:\>Add-FontsToNavContainer -containerName test2

    -------------------------- EXAMPLE 3 --------------------------
    PS C:\>Add-FontsToNavContainer -containerName test2 -path "C:\Windows\Fonts\ming*.*"

    -------------------------- EXAMPLE 4 --------------------------
    PS C:\>Add-FontsToNavContainer -containerName test2 -path "C:\Windows\Fonts\mingliu.ttc"
```
If you do not specify path, it will install all missing fonts from the host (will take some time).

**Comment by AmolSalvi** [comment]
Yes we are running business central container

**Comment by AmolSalvi** [comment]
Thank you Freddy .It works like a charm. 
Just one question how it will work when customer will use it when published on their BC container and font is not there ? I am sure they will also face this problem.

**Comment by anwar0206** [comment]
Hi Freddy similar question what @AmolSalvi asked. 

We have special fonts which are used for displaying Barcode in reports. How shall we proceed for getting our App tested and how the end user will get this font when they subscribe to our App.
Please guide us on this.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
