### ISSUE TITLE
Gen. Journal Page abnormal behavior 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#4608]
We have extended the Gen. Journal Page, and we moved "Shortcut Dimension 1 Code" field before the posting date. 
![image](https://user-images.githubusercontent.com/38460823/52784480-49df6a80-307b-11e9-8ff4-e5ce48f950b0.png)

Now, if we manually enter a dummy value on the "Batch Name" field on the Page and tab off the field, the page gives an error.
![image](https://user-images.githubusercontent.com/38460823/52784542-76938200-307b-11e9-9490-c43dbaa6b387.png)

Now, when we click on "Revert the change", then the Gen Journal Page is refreshed, and the "Shortcut Dimension 1 Code" field becomes invisible. 
![image](https://user-images.githubusercontent.com/38460823/52784708-06393080-307c-11e9-875b-e5b6633a08e4.png)

**Comment by kalberes** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
