### ISSUE TITLE
[Upgrade] NavApp.GetArchiveRecordRef always returns false

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#4611]
Hi,

For an upgrade, I want to pass data from a field which becomes obsolete to another new one. 
But the call of  **NavApp.GetArchiveRecordRef(MyTable, RecRef);** always return false so I can't process the values transfer.
See the sample above:

**Table 50105**

![image](https://user-images.githubusercontent.com/29598240/52791034-45f61d00-3068-11e9-960b-c68d7ecc7059.png)

**Upgrade Codeunit Sample**

![image](https://user-images.githubusercontent.com/29598240/52791107-7b9b0600-3068-11e9-9fd6-bac3ce298333.png)

The program never pass the line 23.

I also tested by passing **Database::TestData** instead of 50105 but have the same behavior 

For the upgrade, I use these PowerShell commands to perfom upgrade to the 1.0.0.1 version of my app
![image](https://user-images.githubusercontent.com/29598240/52791526-71c5d280-3069-11e9-856c-7cc791f910a5.png)

Thanks for your help

**Versions:**

 - AL Language: 2.1.79379

 - Business Central: W1 13.3 (27233)

**Comment by demiliani** [comment]
Just tested. NavApp.GetArchiveRecordRef returns false always, I think it's because it's V1 related.
The upgrade works directly by using RecordRef on the table:

DestinationRecRef.OPEN(TableId, FALSE);
            if DestinationRecRef.FindSet() then
                repeat
                    OldField := DestinationRecRef.Field(OldFieldNo);
                    NewField := DestinationRecRef.Field(NewFieldNo);
                    NewField.Value(OldField.Value());
                    DestinationRecRef.Modify();
                until DestinationRecRef.Next() = 0;

**Comment by JulienDecottignies** [comment]
Thanks Stefano for your answers. It works :)

Just tried **NavApp.GetArchiveRecordRef()** on BC **14.0.29537.29654-W1**. Method is still available but has the same unexpected behavior as in BC 13 version
