### ISSUE TITLE
Compiler in VS Code get's out of sync

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#4612]
From time to time (happens a couple of time per day for me) the compiler starts complaining about errors that doesn't exists. If I use "Reload Window" the errors goes away. Sometimes the text in the editor also gets corrupted with strange line breaks, but not always. It's seems as the AL Language extensions gets out of sync with the editor in VS Code and needs a new sessions to get back in sync.

I'm on version 2.1.79379 of the extension.

**Comment by thpeder** [comment]
Hi @larswestman,

Thanks for reporting the issue, but could you please provide some more information.

The project you are working in how many .al files are there?
Do you have multiple workspaces?
Is there some pattern for when it happens?

**Comment by larswestman** [comment]
Hi Thomas

I have approx 400 files in the repo. It's a single root workspace. I've got more folders/workspaces in my c:\repos but that shouldn't have any effect on this I guess.

Its very random. Suddenly I just get compilation errors even though the code is perfectly fine and after a reload it's all fine again. This is a bit annoying btu what's more dangerous is that the code also gets coruppted from time to time and I'm sure this correlates.

I'm not alone on this. I've got colleagues with the same issues. This problem has been around quite long. I've had it for several months.

**Comment by extensionsv2training** [comment]
Yup, happens here as well.

**Comment by larswestman** [comment]
And more here: https://www.yammer.com/dynamicsnavdev/threads/15250068250624

**Comment by larswestman** [comment]
Take a look here. I have these kind of errors several times per day. Here you can see that what I have on the screen is not what the compiler reads.
![2019-02-19_14-15-09](https://user-images.githubusercontent.com/43792551/53017746-01e08f00-3451-11e9-8e2c-a5abf2809d23.jpg)

**Comment by larswestman** [comment]
As you can see its all over the place....

![image](https://user-images.githubusercontent.com/43792551/53018549-f2fadc00-3452-11e9-9660-471e9f7c836d.png)

**Comment by larswestman** [comment]
I can't remember having seen these errors lately.

**Comment by larswestman** [comment]
I must correct myself... This bug is still around.

**Comment by kalberes** [comment]
Is it around like in the newly released 4.0 version?

**Comment by qutreson** [comment]
Hi @larswestman, can you try to see if this still reproduces on the latest developer preview?

**Comment by kalberes** [comment]
This issue has been closed because it has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
