### ISSUE TITLE
AL0304 - Length of the identifier cannot exceed 120 characters (dotnet type)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4616]
**Describe the bug**
While converting our solution to AL using txt2al, we encounter the AL0304 error when dealing with the dotnet types, having a fully-qualified name over 120 chars.
```
assembly("XTourIntegration")
    {
type("XTourIntegration.XServerIntegration.Facade.Contract.XTour.PlanningParams.StandardParams.BalancingParams.BalancingParamsDto";"BalancingParamsDto"){}
```

**Expected behavior**
Avoid the AL0304 'Length of the identifier cannot exceed 120 characters' error?

**Versions:**

 - AL Langauge: 2.1.79379

**Comment by kalberes** [comment]
Wow,that is a handsome namespace. I am not sure your request is doable though.

**Comment by atoader** [comment]
@fvet you can get by this by removing the quotes:
```
assembly("XTourIntegration")
 {
type(XTourIntegration.XServerIntegration.Facade.Contract.XTour.PlanningParams.StandardParams.BalancingParams.BalancingParamsDto ; BalancingParamsDto){}
}
```
