### ISSUE TITLE
F5 and data lose

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#462]
When we create an app we also test it. If we use F5 to publish app, then go to pages, fill some data. If we find some bug, we go back to VS Code, change code and ... press F5 once again? In such case we lose all data inputed earlier. How to avoid this?

**Comment by pmohanakrishna** [comment]
Seems this is not yet fixed.. #62

**Comment by StanislawStempin** [comment]
This is not implemented yet. It will be a couple more updates before we get to this feature.
