### ISSUE TITLE
OnBeforeEvent not raised if Currpage.Update

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#4623]
Hi,

we have a bug/problem with actions and events.
We have an action, where all the code is in a subscriber of OnBeforeAction.
The only thing left in the event is a currpage.update, as that won´t work in subscribers.
When the currpage.update is there, the OnBeforeAction is not executed. When we remove the currpage.update then the OnBeforeAction event in executed.

**Comment by kalberes** [comment]
Hi, 
Please tell us about your versions, and also a clear repro step if possible,

**Comment by LFlamme** [comment]
Hi,
We are on CU2, but after we build the extension again the bug is gone and we are not able to reproduce it again. Consider this done.
