### ISSUE TITLE
[Feature request] automate .gitignore creation

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#4627]
It would be amazing if the AL extension could automate creation of .gitignore file.

Two possibilities:
- "AL: Go!" command creates the .gitignore file during project creation
- "AL: Create .gitignore" command creates just .gitignore

You have a default .gitignore which is good enough for 99% situations, but I (and everyone else) has always to manually copy it from somewhere, which wastes time. There is no reason why .gitignore file wouldn't just be created during AL: Go! and then whoever doesn't need it can delete it (just like we all do with HelloWorld.al)

**Comment by atoader** [comment]
@vjekob would you mind sharing your .gitignore file together with comments on why you ignore and why?

**Comment by EmilDamsbo** [comment]
This is currently available in the new AL: Go for GitHub templates. Alternatively, we are currently in the process of updating the one available through the third-party site www.gitignore.io via this Pull Request:

https://github.com/toptal/gitignore/pull/514
