### ISSUE TITLE
Unhandled exception in Microsoft.Dynamics.Nav.EditorServices.Host.Exe

### ISSUE THREAD

**Issue by jhwkendall** [Microsoft/AL#4629]
I'm new at AL development and was trying to follow the "Getting Started with AL" guide at
"https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started" to connect to a cloud version of Business Central.

Things go fine until I get to step 5 which says: "Press Alt+A, Alt+L to trigger the AL Go! command, and then choose Cloud." Immediately after pressing Alt+A, Alt+L,  a Just-In-Time Debugger dialog pops up stating: 
"An unhandled Microsoft.NET Framework exception occurred in Microsoft.Dynamics.Nav.EditorServices.Host.exe [18808]."

![image](https://user-images.githubusercontent.com/1424888/53032316-a3111a80-343c-11e9-9090-e78b5b961cda.png)

Now, just opening an AL project causes the same dialog pops up. 

I have tried uninstalling and re-installing the AL Language extension and have deleted the 
folder: "C:\Users\<user>\.vscode\extensions\ms-dynamics-smb.al-2.1.79379" between times. Nothing helps.

In the past I successfully used an earlier version of the extension with on-premise  Microsoft Dynamics 365 Business Central version 13.0.24623.0.  But I'm stuck after updating to the latest AL Language extension. 

**Versions:**
Visual Studio Code Version 1.31.1
AL Language Extension Version 2.1.79379

**Comment by kalberes** [comment]
Do you have by accident somewhere in the many Al setting you can have (local, workspace, global) a settings called al.debug=true somewhere?
What happens if you ignore the dialog?

**Comment by jhwkendall** [comment]
Yes! It works if the dialog is ignored. Thanks.

In VSCode I found "User Settings", "Workspace Setting", and have a settings.json file in the project.  None of them have an al.debug setting. Maybe I'm looking in the wrong places.

**Comment by kalberes** [comment]
But that is still weird. I wander what happens that triggers a break in the language server. (*EditorServices.Host.exe)
What happens if you start debugging (F5) or just Ctrl F5 to publish? Does the same window appear?

**Comment by jhwkendall** [comment]
The same window appears in both cases. It happens when the project is opened and between when the extension is compiled and when it is uploaded.

Right now it is just an annoyance. I can set breakpoints and examine variables. I don't know what "EditorServices" provides that I'm missing out on.

**Comment by kalberes** [comment]
That is extremely peculiar. What about any option name that is called "debug" and it is set to true?

**Comment by jhwkendall** [comment]
The VSCode debug settings are set to their default values in "User Settings" and "Workspace Settings":
    "debug.allowBreakpointsEverywhere": false
    "debug.enableAllHovers": false
    "debug.inlineValues": false
    "debug.internalConsoleOptions": "openOnFirstSessionStart" **
    "debug.openDebug": "openOnSessionStart" **
    "debug.openExplorerOnEnd": false
    "debug.showInStatusBar": "onFirstSessionStart"
    "debug.node.autoAttach": "disabled"

    **I tried setting these to "neverOpen" but it didn't help.

Where else should I look?

**Comment by kalberes** [comment]
Can you install the insiders version of VsCode (https://code.visualstudio.com/insiders/) and install there the Al extension.

**Comment by jhwkendall** [comment]
That was a good suggestion.  The insiders version of VSCode doesn't have the problem.

**Comment by thpeder** [comment]
It seems like the issue has been fixed in newer version of VSCode so I'll close the issue. If you run into this issue again feel free to open a new issue.
Thanks for reporting it.

**Comment by SUD-D365** [comment]
Hi @kalberes 

It seems i am also facing same issue on my machine.
It taking around 15-20mins for saving a AL file. I am not sure it happend due to window update, vS code or AL language update.
**microsoft.Dynamics.Nav.EditorServices.Host** process is consuming around 75% of CPU.

Can you please help?
Cc : @thpeder
