### ISSUE TITLE
AL behaviour when working with large number of objects

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/AL#463]
Hi, do anyone experience similar thing.

When we open a folder with .AL files (around 373 files). 
a) AL becomes too slow in displaying the intellisense, 
b) It take long time in AL when you correct the field name in the code either by typing the Field Name or selecting the same through intellisense.

We, also found that when any table extension fields is referred in the code, sometime AL recognises it some it shows in the problems window. to resolve this quickly if you open that table extension file, then the issues are removed from the problems window.

**Comment by esbenk** [comment]
We have made a lot of optimizations around intellisense and error feedback in the next version. We now that the current release have some issues with larger projects. As a result there is significant performance improvements.

You can improve the speed in the current release by turning the codelens feature off. Set  

`"editor.codeLens" : false 
`

in the settings file.

**Comment by anwar0206** [comment]
Thanks @esbenk , eagerly waiting for the next release. :)

**Comment by NicolaiEsbensen** [comment]
We have a similar issue, with an even larger amount of files. 
 @esbenk where is the settingsfile you mention located?

**Comment by esbenk** [comment]
The easiest way to do it is to download the "Toggle CodeLens" extension for VsCode. 

Alt. you can go to File|Preferences|Settings and add it to either "user settings" or "workspace settings" depending on the scope you want to set it for.

**Comment by NicolaiEsbensen** [comment]
Didn't make a difference to me, autocomplete doesn't work at all. The project also have a lot of errors still, however i would expect that autocomplete for the objects that does parse/compile would work. However i can see that you addressed the issue in the next version which i look forward to :)

**Comment by esbenk** [comment]
Turning off CodeLens will not solve the problem - only reduce it. 

As mentioned have we done a lot of optimizations in this area. We have also changed when we refresh errors to give a better editing experience.  

I'm running the august on the 6000+ files with CodeLens turned off. I'm using a i7 Surface Pro 4. Initially when loading the project it takes around a minute to get all errors, which is comparable to similar size projects (140MB source files) in e.g. C#. You can start editing before the initial load is done, but you will get less intellisense support. After that you get the full experience.

You can of course feel a difference between a 10 file project and a 6000+ file project, but with changes made in the August release you should be fine.
