### ISSUE TITLE
Publish-NAVApp with AL0451

### ISSUE THREAD

**Issue by MarkoPoljanc** [Microsoft/AL#4630]
**Describe the bug**
I can make error-free package from VSCode with 'AL:PAckage'. When I try to publish it to the server with Publish-NAVApp command I get two errors AL0451 (and then some more depending on those two). And I have assemblies in both probing path directories.
Other assemblies ("Microsoft.Dynamics.Nav.Integration.Office", "System.Xml", "System", "mscorlib", "System.Windows.Forms") are without errors.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
Use PdfSharp or Word Interop .Net with BC365 on-prem.

**Expected behavior**
I would like to publish my package.

**Screenshots**
Dotnet/dotnet.al(3,14): error AL0451: An assembly named 'PdfSharp, Version=1.32.2608.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics 365 Business Central\130\Service\Add-Ins, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft Dynamics NAV\Add-Ins
\13.0.25924.0'

and

Dotnet/dotnet.al(26,14): error AL0451: An assembly named 'Microsoft.Office.Interop.Word, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics 365 Business Central\130\Service\Add-Ins, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft Dynamics NAV\Add-Ins\13.0.25924.0'

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: 13.0.25924

[dotnet.zip](https://github.com/Microsoft/AL/files/2882275/dotnet.zip)
[Microsoft.Office.Interop.Word.zip](https://github.com/Microsoft/AL/files/2882280/Microsoft.Office.Interop.Word.zip)
[PdfSharp.zip](https://github.com/Microsoft/AL/files/2882281/PdfSharp.zip)

**Comment by kalberes** [comment]
You would need these assemblies present on one of the folders on the server too exactly as the compiler error suggests.

**Comment by MarkoPoljanc** [comment]
Thank You. I have both assemblies in right folder(s). But I haven't restarted service. Solved.

**Comment by danielonsombi** [comment]
A server Instance restart saved my day.
