### ISSUE TITLE
How to change the service configuration file for BC Production/Sandbox

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#4631]
I am having the issue when need to call the Standard API for Production. I get the following message.

{"error":{"code":"Internal_CompanyNotFound","message":"Cannot process the request because the default company cannot be found. You can specify a default company in the service configuration file, or specify one for each tenant, or you can add a query string in the form of \"company=[name]\". You can see the available companies by accessing the default OData web service, Company. For more information, see \"OData Web Services\" in Help."}}

Does anyone here know how to solve it ?

**Comment by AndersLarsenMicrosoft** [comment]
Which authentication is used AAD or webservice access key and can you please provide the URL

**Comment by Tonygithub17** [comment]
> 
> 
> Which authentication is used AAD or webservice access key and can you please provide the URL

I am using Web Service access key. Here is a the URL to access API.
https://api.businesscentral.dynamics.com/v1.0/376ca222-0508-4937-9d40-dedde184b756/api/beta/paymentTerms

**Comment by AndersLarsenMicrosoft** [comment]
You need to be in the scope of a company to get the paymenttems (just like in the client)

Try 
https://api.businesscentral.dynamics.com/v1.0/376ca222-0508-4937-9d40-dedde184b756/api/beta/companies 

to get the companies
and then

https://api.businesscentral.dynamics.com/v1.0/376ca222-0508-4937-9d40-dedde184b756/api/beta/compnaies('the id of the company)paymentTerms

**Comment by m12lrpv** [comment]
Unfortunately there is a bug where the default Company is not recognised by the API's despite the error message falsely stating that setting a default company will work.

Until the bug is fixed the only way to overcome this is to add the company to the URL 
i.e.
https://api.businesscentral.dynamics.com/v1.0/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/odataV4/Company('CRONUS AU')/VendorLedgerEntries

**Comment by qutreson** [comment]
Closing this issue as it seems like an application issue which is beyond the scope of this repository which is only for issues related to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
