### ISSUE TITLE
Modify Control Editable Property Is not reverting to previous state

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#4632]
**Describe the bug**
Modify Control Editable Property Is not reverting to previous state

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
![capturebug](https://user-images.githubusercontent.com/38439762/53068564-f055c080-34fe-11e9-8d92-e8a8aa7e9375.PNG)

**Expected behavior**
After inserting wrong value in batch filed system gives error, when revert dimension column in not visible 

**Screenshots**
![capturebug2](https://user-images.githubusercontent.com/38439762/53068728-76720700-34ff-11e9-933f-8319b96ef2fe.PNG)

dimension has gone
![capture3](https://user-images.githubusercontent.com/38439762/53071791-43cd0c00-3509-11e9-9126-f30a0f17bffc.PNG)

**Comment by atoader** [comment]
@shashiBssi are you able to reproduce this in the latest development environment?

**Comment by shashiBssi** [comment]
@atoader I have verified and couldn't reproduce. Looks it has been rectified and latest environment.

**Comment by atoader** [comment]
Thanks! I will close the issue.
