### ISSUE TITLE
Can't visualize an image in control addin for Business Central

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4633]
Hey guys,

related to this issue : **Can't visualize an image in control addin #126** I have a question: I made the same adjustments as suggested by @DavideVD, but I do not understand why it does not work for me, I still cannot see my added image in Business Central?! 

I used also:
` page = $('<img id="mypic" src='+ Microsoft.Dynamics.NAV.GetImageResource('Images.jpg') + 'height="100" width="250" >'+
               ' <button type="button">Click Me!</button> '`

So I think the control addins are not working right...

![grafik](https://user-images.githubusercontent.com/42337107/53092343-d030fc00-3514-11e9-860a-89015b8381c1.png)

Thank you for your help.

**Comment by kalberes** [comment]
Please provide the followings:

a. Versions
b. Repro steps

Thanks

**Comment by malue19** [comment]
Hey @kalberes 
the version of my al package is:

![grafik](https://user-images.githubusercontent.com/42337107/53149936-7d585280-35af-11e9-900d-4fc29ee87a99.png)

And the code I have inserted is the same like in the other issue, which I have added to my one.

**Comment by DavideVD** [comment]
Hi malue19, have u used folders inside  your project?
i.e. In my Visual Studio code version of the add in i have:
- Control Add-in page
...
  _Images = 'Resource/Image/DocDark.png',_
...
- Javascript call 
...
_var imgDocDark = new Image();
imgDocDark.src = Microsoft.Dynamics.NAV.GetImageResource("Resource/Image/DocDark.png");__
...

Inside my VSC folder i have a Resource folder with inside a Image folder.

I hope it can helps

**Comment by malue19** [comment]
Hey DavideVD,
yes I have folder in my project:

![grafik](https://user-images.githubusercontent.com/42337107/53167002-fdde7980-35d6-11e9-9622-bd247395b7b4.png)

The version of my al language package is:

![grafik](https://user-images.githubusercontent.com/42337107/53167034-1b134800-35d7-11e9-8a76-30f7deb9b1b4.png)

The code you have mentioned above I do not have....

That is my controladdin:

![grafik](https://user-images.githubusercontent.com/42337107/53167324-e6ec5700-35d7-11e9-88b3-3daba8103a7b.png)

There is the StartupScript:

![grafik](https://user-images.githubusercontent.com/42337107/53167354-fb305400-35d7-11e9-8897-9bfb9acfc522.png)

And here is my extended page, where I would like to integrate any picture...
Do you see my error/-s?
Do I have to add your additionally code from above to solve the issue?

**Comment by DavideVD** [comment]
Try to do the same of my post: 

- 1 remove ./ before the word ControlAddin inside ur addin, on _Image=_ line
- 2 call ur GetImageResource with _("ControlAddIn/Images.jpg")_

If i remember well it should be all case sensitive inside JavaScript

**Comment by malue19** [comment]
Aaaaahhh, now it works :) thank you so much 👍 

Do you have also some knowledge about Chart.js? How I can implement some chart via javascript for Business Central?

**Comment by thpeder** [comment]
Thanks @DavideVD for helping with resolving the issue.
In this repository we focus on the developer tools for AL development, if you want advice for writing a chart in JavaScript please use the community.
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
