### ISSUE TITLE
Function in Table Sales header and Purcahse header is different UpdateAllLineDim

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#4634]
**Describe the bug**
I want to bypass confirm message in this function. In Sales header i can do but in Purchase header i cannot do because both have different style of the code.
Sales Header:
![image](https://user-images.githubusercontent.com/38439762/53095278-6a5b6900-3542-11e9-957a-b256e397b4e0.png)

Purchase Header:
![image](https://user-images.githubusercontent.com/38439762/53095339-91b23600-3542-11e9-9817-7f1b0149e469.png)

Please Make Purchase Header Same as Sales header otherwise provide a way to bypass.

**Comment by kalberes** [comment]
This repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by shadow747** [comment]
Any idea if this bug will be fixed in Business Central October release ?

**Comment by shashiBssi** [comment]
As i can see in the October preview, this is resolved,
