### ISSUE TITLE
Colour changing on active record

### ISSUE THREAD

**Issue by naveksa** [microsoft/AL#4635]
I don't know, if this has relation to #2521.

We have fields in a repeater-table, where we want to highlight negative values to the user.
We do this using the following code on the field:

                    Style = Unfavorable;
                    StyleExpr = StockUnfavorable1;

And then OnAfterGetRecord we have the code:

        StockUnfavorable1 := ("Expected Stock" < 0);

This marks the negative values in bold and red.
It works almost ok.
Only thing is that the red colour disappears and becomes black when a record is selected.
Please see attached screenshots.

**Versions:**
 - AL Langauge: 2.1.79379
 - Business Central: DK Dynamics NAV 13.2 (27692)

[BC_Disappearing_colour.pdf](https://github.com/Microsoft/AL/files/2884820/BC_Disappearing_colour.pdf)

**Comment by kalberes** [comment]
This looks like a candidate for a Request For Hotfix. Please use the standard channels to create a Request For Hotfix for faster resolution.
