### ISSUE TITLE
Set cloud sandbox tenant per workspace

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#4636]
The launch.json shows all information about the local development environment you are using. But you can't see to which cloud tenant you are publishing from VS Code. Apparently, the credentials you use for publishing to the cloud sandbox is not stored per workspace. As a result, you can't simply switch between cloud sandboxes, you have to clear the credentials cache first.

If would be nice if you could set cloud sandbox tenant information that should used to publish to the online sandbox. Preferably the user id so you can clearly see what tenant is being used.

During the publish process, the output only shows to which endpoint the package is published. It doesn't tell you anything about the tenant. Please add at least a line here with the actual user id being used.

**Comment by rdebath** [comment]
If you just want to see the tenant there's an option `"tenant": "randomname.onmicrosoft.com"` that forces the right tenant. It errors if you don't have access with the cached user; but that's better than nothing.

As I added to #920, IMO the host (already there) and username should be in the `launch.json` file. The password should be stored in "Credential Manager".

Just like everything else from Microsoft does.

Actually, I wonder where it stores it's "cache" and why that isn't a security issue.

**Comment by kalberes** [comment]
Agree. We should not bind an authentication scheme for the whole workspace. Things are even worse now, since you can only one configuration settings in your launch.json.

**Comment by extensionsv2training** [comment]
This also presents a risk that you accidentally publish something to a wrong customers sandbox, if you don't remember to clear the credentials.

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.

**Comment by pborring** [comment]
Vote on this idea instead, which really tracks the same: https://experience.dynamics.com/ideas/idea/?ideaid=99f623eb-34a2-ed11-9ac4-0003ff45c94c
