### ISSUE TITLE
Functions in Customized Codeunit not able use in other objects

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#464]
Hi,

We have functions written in Customized Codeunits, but those are not visible for using in different objects. I defined [Scope('Extension')] above those functions so that, they are visible but no use.

Any suggestion ?

**Comment by esbenk** [comment]
If you by Customized codeunits means that you have modified codeunits with C/SIDE, then that is not supported right now. The symbol files are currently generated when we built the database and changes to objects using C/SIDE is not reflected.

**Comment by sanjeevasawale** [comment]
Let me brief you with the help of scenario -
We have converted Codeunit of let say 50000 range using Text2AL and added to VSC Project. There is Function "CalculateWeight" which i wanted to use in another Page. I declared this CU in Global Variable but when i use above function it gives error "Codeunit does not contain defination for Function".

Hope am clear with my question.

**Comment by esbenk** [comment]
Is the function marked as local? Can you post a repro of the problem?
