### ISSUE TITLE
Drill Down not Working in Matrix Page.

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#4640]
Drill Down is not working in Web Client for our customized Matrix Page.

We did same as standard, but still drill down is not showing.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/39764447/53193469-0c5c7d80-3637-11e9-8919-89578a92e1da.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/39764447/53193328-b5ef3f00-3636-11e9-9b17-af03c0873102.png">

Version : US Dynamics NAV 13.4 (27969)

**Comment by kalberes** [comment]
Can you please provide a short repro?

**Comment by qutreson** [comment]
Closing this issue as we didn't get further information about it. Please open a new issue if you are still facing it on the latest developer preview.
