### ISSUE TITLE
How-to include non-Image Resources with Dynamics NAV Javascript Add-Ins in BC?

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#4641]
Hey guys,
after knowing how to insert a picture in a control addin ([https://github.com/Microsoft/AL/issues/4633](url)) for Business Central. I tried to insert a dynamic chart as well. Unfortunately it did not work, because I get no output on my extended "CustCard"

`page = $('<img id="mypic" src='+ Microsoft.Dynamics.NAV.GetImageResource('ControlAddIn/index.html') + 'height="100" width="250" >'`

It looks that "GetImageResource" is not working with html-files...do you have an alternative or is it a bug? 

Thank you for your help ;)

**Comment by ajkauffmann** [comment]
There is currently only one way, which is actually a workaround: http://vjeko.com/abusing-images

**Comment by atoader** [comment]
Great idea! This idea is not strictly related to the development process and implementing it will require a coordinated effort across many teams in our organization. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
