### ISSUE TITLE
AL Error Code:Metadata Object Not Found Connection type:WebClient

### ISSUE THREAD

**Issue by aetxebarria** [Microsoft/AL#4645]
Hi everyone, 
I've created an extension for deleting a few items in BC cloud. I run that codeunit with an action added into the company info page.
When I run, I can see this error into the BC admin center:
![imagen](https://user-images.githubusercontent.com/41778563/53241543-3f882680-36a2-11e9-85b7-2eeaedf7c8ae.png)
I've tried to publish the extension into my docker, and run it debugging, but the error still happens, without stoppind the debugger.
Why can this be happening?
Thank you very much

**Comment by aetxebarria** [comment]
I forgot to put the "BreakOnError". 
This is what provokes the error:

` trigger OnAction();
                    begin
                        Run(Codeunit::Mending);
                    end;`

**Comment by kalberes** [comment]
CAn you specify your versions and provide a small repro.

**Comment by aetxebarria** [comment]
Hi kalberes. It is the last vesion, it's jsut been updated. It's the cloud version. Anyway, the issue was that it seems that it doesn't "like" to run directly the CU from the action in the page. I've inserted the code into a procedure in the CU, and call to that fucntion from the action, and the problem as been solved...
