### ISSUE TITLE
Not publish the package to server/Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/AL#4646]
I'm trying to publish a HelloWorld package to my docker instance (CTRL+F5)
I manages to create the package and then in the output I get this:

> Success: The package is created.
> [2019-02-22 13:08:39.94] Sending request to http://dockermall:7049/nav/dev/apps?SchemaUpdateMode=synchronize
> [Error - 13:08:44] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.Details:

When I run the "Get-NavAppInfo" I get the following for the app:

> ServerInstance : MicrosoftDynamicsNavServer$NAV
> PSComputerName : 6d8356181d39ec1f93b9a6b10b8d54d499a260d9163913ad621baa732eb21226
> RunspaceId     : da88b9f2-b2f1-4206-b76d-abc9f534d783
> AppId          : a6a3459d-444c-4c05-99c4-f3b968c9e65e
> Name           : Default App Name
> Publisher      : Default Publisher
> Version        : 1.0.0.0
> ExtensionType  : ModernDev
> Scope          : Tenant

The app is installed and shows the "hello world" message when open customer list.

When I press F6 to see the output of the error I get:
```
Success: The package is created.
[2019-02-22 13:19:21.63] Sending request to http://dockermall:7049/nav/dev/apps?SchemaUpdateMode=synchronize
[Error - 13:19:24] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.Details:
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<SendPackage>d__7.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:rad 125
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<Publish>d__5.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:rad 76
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPageDesignerRequestHandler.<ProcessRequestAsync>d__3.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPageDesignerRequestHandler.cs:rad 48
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:rad 36
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() i C:\a\316\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:rad 59
```

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create your average docker container with image: XXX
2. Create a  simple helloworld app
3. Press CTRL+F5  and the error will appear

![compileerror](https://user-images.githubusercontent.com/34970096/53242607-89264080-36a5-11e9-88a4-c403301339c6.PNG)

**Versions:**
AL Language 2.179379
Docker Image: mcr.microsoft.com/businesscentral/onprem  but have experienced this over multiple images.

**Comment by atoader** [comment]
@NAVFreak have you been able to reproduce this issue on the latest development environment?

**Comment by qutreson** [comment]
Hi @NAVFreak can you try reproducing this issue on the latest development environment?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
