### ISSUE TITLE
Problem with Purchase Line Discounts

### ISSUE THREAD

**Issue by gasalazar** [Microsoft/AL#4649]
When posting a Purchase Order, the Line Discount Amount is not being taken into consideration. After checking the code, I have found that there is a problem with the codeunit 90 in the DivideAmount function.

        "Line Amount" := ROUND(PurchLineQty * "Direct Unit Cost",Currency."Amount Rounding Precision");
        IF PurchLineQty <> Quantity THEN
          "Line Discount Amount" :=
            ROUND("Line Amount" * "Line Discount %" / 100,Currency."Amount Rounding Precision");
         "Line Amount" := CalcLineAmount;

And it should be: "Line Amount" := "Line Amount" - "Line Discount Amount";

**Comment by thpeder** [comment]
HI @gasalazar,

This repository is meant for the new development environment, not for bugs in the applications business logic.
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

Thanks for reporting the issue.
