### ISSUE TITLE
Adding XML Signing (Read and Create)

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#465]
Would it be possible to implement the XML signing available in .NET? There are unfortunately some processes which only work with this. If possible, this should be done with a private / public key procedure, but not necessarily with a certificate, which must be installed on the client (because of the Webclient). For this, only a few more XML variables and a RSA variable would be necessary, see this example:

https://msdn.microsoft.com/de-de/library/ms229745(v=vs.110).aspx

In any case, it would be a very great help to map processes that work with signed data and should not be changed in any case.

**Comment by StanislawStempin** [comment]
We do plan on providing more cryptography functionality, since it is often required for making service calls. Once we get to it we will evaluate this particular scenario in more details to see if we can cover it as well.

**Comment by finstx** [comment]
We are using SigendXml (System.Security.Cryptography.Xml) with public/private Rsa keys for some licensing scenarios. 

Could also be very helpful with licensing NAV extensions.

So it would be nice to see this features in NAV.

**Comment by anzwdev** [comment]
I've just added SignedXml pull-request to cal-open-library. You can find it here:

https://github.com/Microsoft/cal-open-library/pull/54

**Comment by FSharpCSharp** [comment]
@anzaman This looks great! Now you can set the XML signature and also check if an existing document is valid! Thank you very much!

**Comment by pborring** [comment]
Closing this issue. If there are any remaining asks, they should go into https://aka.ms/bcideas or System app module.
