### ISSUE TITLE
Error: Object of type Codeunit with ID ***** could not be found.

### ISSUE THREAD

**Issue by ashik-ivor** [microsoft/AL#4650]
I am getting this error after publishing the app on the Sandbox Environment and also on Docker environment. And the debugger breaks automatically. 

![image](https://user-images.githubusercontent.com/38459860/53320210-fd0d5680-38fa-11e9-8cb2-5d81f8020614.png)

I also noticed that I started getting this Error when I used "CurrentClientType()". And also the ID showing on the error is the object where I have used the "CurrentClientType()" function. 

When I remove the function "CurrentClientType()", after 3 or 4 debugging sessions, the error messages do not show up and does not break the debugger.

**Comment by atoader** [comment]
@ashik-ivor can you by any chance share code to reproduce this issue?

**Comment by kine** [comment]
I am having same issue, but not on the docker, only on the online Sandbox.

In my case I am debugging without publishing. I have open exactly same source code, which was used to generate the app installed on the sandbox. VSCode will open browser with the session and than the debugger ends.

The code in the codeunits is not using CurrentClientType. Mostly it is simple code calling basic things.

**Comment by kine** [comment]
Ok, seems the problem is on my side. I am automatically running the debugger with F5 - which leads to publishing the app to the sandbox - but this fails, leading to uninstalled app on the sandbox. Than I realize this, I run Debug without publishing - and I get this error, because the app is not installed now. I need to install the app again manually, and run the Debug without publishing.

**Comment by atoader** [comment]
Thanks for the valuable input @kine!

**Comment by qutreson** [comment]
Hi @ashik-ivor, are you still experiencing this issue on our latest developer previews? Can you also verify if you were in a similar scenario to the one described by kine?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
