### ISSUE TITLE
Need a List to see events and it's subscribers and to debug a session in a multiuser environment + Turn on/off SQL Tracing in VSCode development environment

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#4652]
We need a list to see events and it's subscribers and to debug a session in a multiuser environment + Turn on/off SQL Tracing in VSCode development environment.  This is a very practical requirement to debug and code, performance issues in AL code.  By having a visual development environment request (see #4592) will go towards addressing this.  But in that request these elements are not explicitly mentioned.

**Comment by thpeder** [comment]
Hi, 
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by thpeder** [comment]
Please have a look at the Event Recorder and see if it helps your case
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-events-discoverability
