### ISSUE TITLE
httpclient Response message

### ISSUE THREAD

**Issue by abouraoui** [Microsoft/AL#4653]
Httpclient post method returning an error message regarding the content of the response message, below screenshots with error message and code, please help, Thank you.

![image](https://user-images.githubusercontent.com/45698976/53339697-07b4f500-38d5-11e9-9fb0-d00c1f162401.png)

![image](https://user-images.githubusercontent.com/45698976/53339716-1b605b80-38d5-11e9-80f7-8af27e56d21e.png)

**Comment by wisa1** [comment]
I think you need to get the Headers of your HttpContent and set the Header for Content-Type and encoding there.

varHttpContent.GetHeaders(headers) //headers: HttpHeaders
headers.Add('Content-Type', 'text/xml'); //or application/xml

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
