### ISSUE TITLE
Bug: OnLookup trigger added to Table field in C/SIDE not available from Web Client

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/AL#4654]
**Describe the bug**
After adding an implementation of the OnLookup trigger to a standard table field through C/SIDE, the field becomes 'clickable' in the Windows client, but it does not become clickable in the Web client.

**To Reproduce**
Open finsql and through the object designer start designing table 36 Sales Header.
Go to the Status field and add an implementation of its OnLookup trigger, e.g.:
![bug_onlookup](https://user-images.githubusercontent.com/7383241/53423921-8a77a600-39e2-11e9-96b6-e25211f87f4d.png)

Save the changes, then open up both the Windows client and Web client.
When we open the Sales Order page in both clients, then in the Windows client we can click the field and get our message, but in the Web client we cannot click the field.

For example in the **Windows** client we will see:
![bug_windows](https://user-images.githubusercontent.com/7383241/53424071-cc085100-39e2-11e9-9d03-9638a0bb48dc.png)

and in the **Web** client:
![bug_web](https://user-images.githubusercontent.com/7383241/53424081-cf034180-39e2-11e9-9c43-cfb9e6944845.png)

_Note:_ Everything works fine when providing an implementation of the OnLookup trigger for a _new_ field in AL. However, on-premise, we need to change the base object to add an OnLookup implementation to an existing field through C/SIDE, because there is no `OnBeforeLookupEvent` (see #3090) yet available to use for this in AL.

**Expected behavior**
Have the field become clickable in the Web client as well, so that when clicked, the implementation of the OnLookup trigger is executed.

**Versions:**
- Application: W1 14.0 (28593)
- Platform: 14.0.28496.0 (14.0.28496.0)

**Comment by rvanbekkum** [comment]
Updated the issue: This applies to any field. The OnLookup cannot be triggered from the Web client.

**Comment by atoader** [comment]
Hi! This has been fixed in the latest developer preview. Please open a support request to CSS through PartnerSource if you need this to be backported.

**Comment by tfenster** [comment]
@atoader Does that mean it will appear in spring release in CU1 or would that also only happen through a CSS backport request

**Comment by tfenster** [comment]
@atoader any feedback on this?

**Comment by atoader** [comment]
@tfenster I apologize for the lack of clarity around this. The latest developer preview is always shipped from master, the CUs are shipped from the release branch. By default we do not put things into the release branch. There are multiple reasons why the process is like this:
1. Backporting issues is time consuming and it always comes at the cost of new features and improvements
2. We are only able to backport issues that are related to the development experience. Issues related to other parts of the product, such as this one, are maintained by other teams.

Please open a support request if you require this to be backported.

**Comment by tfenster** [comment]
@atoader ok, I was hoping that someone else had already requested a backport. But I now requested it myself

**Comment by atoader** [comment]
Hi @tfenster, @rvanbekkum ! I have followed up on this issue with the team responsible for this area of the product and they have added a slice for the Fall release to address this inconsistency. I apologize for the miscommunication. This GitHub is meant for issues related to the development experience, but we try our best to pass input about other areas of the product to the owning teams.

**Comment by stefanoPrimo** [comment]
Hi @atoader @tfenster @rvanbekkum 
I've not understood what's happening to this topic. 
Are there any updates? 
It will be a part of the new upcoming CUs? If yes which one?
Or it will be part of the 2019 fall release?

Thanks

**Comment by dtacconi** [comment]
@stefanoPrimo . As mentioned previously, this scenario is still a feature limitations for web client. There is a slice to improve this behavior upon client team to address this inconsistency in the Fall 2019 release.
