### ISSUE TITLE
Filteration on Archived Documents (Sales & Purchase (Order, Quote, Return List) Archives

### ISSUE THREAD

**Issue by BSSIRajbir** [Microsoft/AL#4655]
**Describe the bug**
I am trying to filter the archive list pages [For Example "Sales Order Archives"] on the open of this page. I am putting my filtration code on the OnOpenPageEvent of the page. My filtration is not working only on the archived page however on the other list pages it is working fine. I am trying to achieve it though EventSubscriber - OnOpenPageEvent. 
![image](https://user-images.githubusercontent.com/43894249/53438335-8cc30b80-39b4-11e9-9779-b919985f5366.png)
I noticed "RefreshOnActivate" for all archived pages is set to "No" however all the other list pages have it as 'Yes'. I believe this is giving trouble. 
![image](https://user-images.githubusercontent.com/43894249/53438535-f2af9300-39b4-11e9-8810-013479ea9845.png)

Is there any other way to filter the archived list page?

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
