### ISSUE TITLE
D365 BC On Premise : Posting failing with error "G/L inconsistency", after USER modifies date on transaction or changes WORKDATE

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#4656]
**If a user "Changes workdate inside NAV client" or "Changes Document Date and Posting date from transaction pages, and while posting NAV fails with Inconsistency error.**

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

1. "Change work date inside NAV client" or "Change Document Date and Posting date from transaction pages"
2. Create Sales Order
3. Perform Post operation 

**Expected behavior**
User should be able to post the transaction in NAV without error.
![image](https://user-images.githubusercontent.com/5293496/53440735-1a552a00-39ba-11e9-972f-2cff97a414f9.png)

**Screenshots**
wrong entry created if date modified in NAV - Tax amount is not posted correctly 
![image](https://user-images.githubusercontent.com/5293496/53440484-79ff0580-39b9-11e9-994a-4b32fc29c0df.png)

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central: US Dynamics NAV 13.0 (24630)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
