### ISSUE TITLE
Can i use trigger  OnInit in page extension? Please Help me

### ISSUE THREAD

**Issue by ta3113ta** [Microsoft/AL#4657]
Can i use trigger  OnInit in page extension? Please Help me
i can't use trigger OnInit or i can find orther way to find out

**Comment by qutreson** [comment]
Hi @ta3113ta, it is not possible to use the OnInit trigger on a page extension. The triggers you can use are the following one: 
![image](https://user-images.githubusercontent.com/31541422/53495310-fbc95e80-3a9f-11e9-8286-27881f33fadc.png)

You can find more information about triggers in AL in our [online documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-triggers).

If none of them can help in your current scenario, you can also request the creation of an event in the init trigger of the page (in this (repository)[https://github.com/Microsoft/ALAppExtensions/issues]) and subscribe to this event in your extension.

**Comment by qutreson** [comment]
In case you have further questions about the AL language, you can refer to one of the following forums:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
