### ISSUE TITLE
Better size control for subform

### ISSUE THREAD

**Issue by Hornsyld** [microsoft/AL#4659]
Would like an enhancement so that you are able to control the subpage - for example a width and height propperty.

In my example below I only have 3 lines from the General Journal and the rest of the page is used by some other information. I would like to control the size better how big the subform.

![image](https://user-images.githubusercontent.com/6792253/53490077-12b58400-3a93-11e9-8892-3028d94bbeb4.png)

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
