### ISSUE TITLE
Strange errors when executing a TableExtension / PageExtension

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#466]
Following situation:

An extension of the table "G/L Account" has been carried out. A new field was added (another account). The user should be able to select the account via the standard lookup. Therefore, the following TableExtension was created:

```
tableextension 70000003 "G/L Account Extension" extends "G/L Account"
{
    fields
    {
        field(50001;"New Account";Code[20])
        {
            TableRelation="G/L Account";
        }
    }
}

```

In addition, the following PageExtension was created so that the user can see and edit the new field:

```
pageextension 70000002 "Chart of Acc. Ext" extends "Chart of Accounts"
{
    layout
    {
        addafter("VAT Bus. Posting Group")
        {
            field(Test;"New Account")
            {

            }
        }
    }

    actions
    {
        // Add changes to page actions here
    }
}
```

The extension can be compiled and deployed without errors. The default page "Chart of Accounts" can not be executed afterwards. The following error always occurs:

```
The multi-part identifier "G/L Account.No_" could not be bound.
Statement(s) could not be prepared.

Page Chart of Accounts must close.
```

Edit: It does not seem as initially intended to lie at the Property TableRelation. An extension of the table "G / L Account" + extension of the page does not appear to be possible.

**Comment by esbenk** [comment]
This is fixed in the upcoming release.
