### ISSUE TITLE
application app.json structure should be changed

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/AL#4660]
When using bcinsider.azurecr.io/bcsandbox-master:14.0.28630.0-al I have to manually specify dependency to BaseApp and remove "application": "14.0.0.0". I think this should be changed to have default values.

**Comment by thpeder** [comment]
HI @AndriusAndrulevicius,
Thanks for your feedback.

**Comment by atoader** [comment]
In the latest release we have improved the experience around "AL Go!" to allow for selecting a target runtime so that the manifest that is generated has the correct dependencies. Would a code action for updating the manifest suffice?
