### ISSUE TITLE
error AL1024: A package with publisher 'Microsoft', name 'Application', and version compatible with '13.0.0.0' could not be loaded.  

### ISSUE THREAD

**Issue by kine** [microsoft/AL#4661]
After I have recreated my container to version:
                "osversion": "10.0.17763.253",
                "platform": "13.0.28538.0",
                "tag": "0.0.9.1",
                "version": "13.5.28640.0"
I have problems with basic things - creating the package for the App. When I try to generate package, I am getting the error from the title:

error AL1024: A package with publisher 'Microsoft', name 'Application', and a version compatible with '13.5.0.0' could not be loaded.

even when the symbols were automatically downloaded successfully.

Full output in the VSCode:

```
[2019-02-27 16:06:53.90] Using reference symbols cache path: c:\git\MSDyn365BC_AppTemplate\MainApp\..\
[2019-02-27 16:06:53.92] Sending request to http://bc:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.5.0.0
[2019-02-27 16:06:53.93] Sending request to http://bc:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-02-27 16:07:49.39] All reference symbols have been downloaded.
Microsoft (R) AL Compiler version 2.1.1.27070
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'MainApp' containing '1' files at '16:7:49.439'.

error AL1024: A package with publisher 'Microsoft', name 'Application', and a version compatible with '13.5.0.0' could not be loaded.

Compilation ended at '16:7:51.694'.

Error: The package could not be created.

```

On another project, I had same problem after the update of container, but it started to work lately, I do not know why. Do you have some tip what could be a problem?

**Comment by kine** [comment]
Docker image used is bcinsider.azurecr.io/bcsandbox:latest-ltsc2019

**Comment by kine** [comment]
More research:
Each time the symbols are downloaded, the Application .app package have different App Id in the NavxManifest.xml inside app zipped folder. The compiler is working only with package, which have App ID = 84dfe9b4-7638-46ba-87d5-c7c242cbec6e. If there is something else, I will get mentioned error. Seems that there is some problem with generating the symbols (may be in connection with transforming the app from C/AL to AL?).

**Comment by kine** [comment]
And during the tests, I found that the AL is caching the app packages, thus even when I remove the .app files, it is working until next restart of the VSCode... complicating the tests because I need to restart the VSCode each time I download the symbols to be sure that the real one on the disk are used and not some old, which were loaded first...

**Comment by thpeder** [comment]
Hi @kine,
Does it work if you target Application version 13.0.0.0?
When you look inside the NavxManifest.xml what version is stamped in there?

**Comment by kine** [comment]
No, it is same if I use 13.0.0.0 or 13.5.0.0. No difference. 
In the app there is version 13.5.28640.0 in all cases. See this comparison (top is ok, middle and bottom not working):
![image](https://user-images.githubusercontent.com/110221/53578211-7ca75980-3b77-11e9-8d3c-0832ae4ca07c.png)

**Comment by kine** [comment]
Interesting is, that now I cannot simulate it again. It was not working yesterday and today morning, now it looks stable. Is there some process in the docker which takes the symbols sometime from outside the container? I mean e.g. from Azue blob store... because for me it looks stable now, but was not few hours ago, and the container image is still same.

**Comment by kine** [comment]
Today new image was downloaded, seems stable for now.

**Comment by atoader** [comment]
@kine we have not been able to get to this in time, but it seems that the issue has gone away. I will close this issue. Please open a new one if you can reproduce it again on newer releases.
