### ISSUE TITLE
No Application symbols in Dev preview February update

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#4664]
Hi!
I use bcinsider.azurecr.io/bcsandbox-master:14.0.28630.0-al image.
System and BaseApp packages were downloaded successfully but Application package failed. I understand that I don't need it? but I can't publish any package because it throws an exception that:

A package with publisher 'Microsoft', name 'Application', and a version compatible with '14.0.0.0' could not be found in the package cache folder 'c:\Users\abaludin\Documents\AL\ALProject7\./.alpackages'

Exception on symbols download:

[2019-02-28 07:00:34.66] Sending request to http://bcal:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2019-02-28 07:00:34.66] Sending request to http://bcal:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-02-28 07:00:34.66] Sending request to http://bcal:7049/NAV/dev/packages?publisher=Microsoft&appName=BaseApp&versionText=14.0.28496.0
[2019-02-28 07:00:35.45] The request for path /NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-02-28 07:00:37.23] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

app.json is next:

{
  "id": "246869ad-0118-483e-aec8-05c7215cd319",
  "name": "Hello world",
  "publisher": "abaludin",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [{
    "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
    "name": "BaseApp",
    "publisher": "Microsoft",
    "version": "14.0.28496.0"}
    ],
  "features": ["TranslationFile"],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "showMyCode": true,
  "runtime": "3.0"
}

**Comment by kine** [comment]
Try to remove the "application" line from the json.

**Comment by ABaludin** [comment]
Thanks a lot Kamil! Now it works fine.

> 
> 
> Try to remove the "application" line from the json.

Thanks a lot Kamil! Now it works fine.

**Comment by ftornero9** [comment]
Hello @kine and @ABaludin,

After removing the "application" line, how you solve the error:

{
	"resource": "/c:/Users/vmadmin/Documents/AL/ALNUevo/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL1022",
	"severity": 8,
	"message": "A package with publisher 'Microsoft', name 'BaseApp', and a version compatible with '14.0.28496.0' could not be found in the package cache folder 'c:\\Users\\vmadmin\\Documents\\AL\\ALNUevo\\./.alpackages'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

Regards

**Comment by ftornero9** [comment]
Hello @kine and @ABaludin,

I figured out what the problem was.

In the app.json file I changed

"version": "14.0.28496.0" to "version": "14.0.0.0"

And then I could got the application symbols.

Regards

**Comment by ftornero9** [comment]
Sorry, that change was here: 

"dependencies": [{
"appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
"name": "BaseApp",
"publisher": "Microsoft",
"version": "14.0.28496.0"}
],

**Comment by ABaludin** [comment]
Hi @ftornero9 !
I took all the dependence requisites directly from base app on Extension management page. I think you have next version of app - so symbols download failed. And yes, you're right - it's allowed to use just 14.0.0.0 as version value and everything will be ok.

**Comment by ftornero9** [comment]
Hello @ABaludin,

Actually the version I have is 14.0.28496.0, but with this value in the "version" key I got the error that the app symbols can be downloaded

![image](https://user-images.githubusercontent.com/12720964/53725438-4c5c0580-3e6c-11e9-9a6f-6dc86418d943.png)

Anyway with the 14.0.0.0 value works and I not going to think much more about it.

Regards.

**Comment by avnishdss** [comment]
Hi Team,
On downloading symbol ,It is showing error while app.json and Launch.json
are as :
**App.json**

  {
    
    "version": "0.2.0",
     "configurations": [
         {
          "type": "al",
          "request": "launch",
           "tenant": "",
           "name": "Tenerife Azure",
           "server": "'URL'",
           "serverInstance": "nav",
           "authentication": "AAD",             
           "startupObjectId": 22,
           "schemaUpdateMode": "Recreate",

         }
     ]
}


**Launch.json**

{
  "id": "79b9828b-0218-4d8d-bb2e-40e0bca81267",
  "name": "Hello world",
  "publisher": "My file",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "features": [
    "TranslationFile"
  ],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": 
    {
      "from": 50100,
      "to": 50149
    }
  ,
  "showMyCode": true,
  "runtime": "2.0"
}

Error Log :

![image](https://user-images.githubusercontent.com/49236464/55478133-8588c080-5638-11e9-8e78-81b96fe6a592.png)

As Target is before Spring'19 Release, Kindly put some light to get through it.

Regards,
