### ISSUE TITLE
TCP/IP port exhaustion by Prod.Client.WebCoreApp.exe

### ISSUE THREAD

**Issue by AMCJN** [microsoft/AL#4665]
We are using Business Central W1 14.0 (27727) OnPremise (Installed from dvd)
When ever we start BC webclient, within a few mintues all TCP/IP port
has been consumed by Prod.Client.WebCoreApp.exe and then after working in BC
it stops with and error "Something went wrong". To get pass this error, you have to close BC
and restart IIS. (We had the same problem with BC Prerelease 3)

Is there anything we can do, so that BC does not consume all TCP/IP ports?????

Steps and/or AL code to reproduce the behavior:
1. Install Business Central W1 14.0 (27727) OnPremise from dvd on a 
    Microsoft Windows Server 2016 Standard
2. Start BC with the webclient
3. Start resource monitor, and open tappage Network, look at the TCP Connections

**Expected behavior**
That BC reuse/closes its TCP/IP connections, instead of just exhausting all port (over 16000 ports)

**Screenshots**
Before starting Business Central V. 
 
![image](https://user-images.githubusercontent.com/31441034/53552944-cde62780-3b3c-11e9-9425-3c7b95e17db4.png)

Right after starting Business Central V.
 
![image](https://user-images.githubusercontent.com/31441034/53552963-d9395300-3b3c-11e9-90c2-1d5ca1616edb.png)

Then this happens very often, only solution to get further is to restart IIS.
 
![image](https://user-images.githubusercontent.com/31441034/53552981-df2f3400-3b3c-11e9-863e-96ba3b361c6f.png)

**Versions:**

 - AL Langauge: 2.1.86206

 - Business Central: W1 14.0 (27727)

**Comment by AMCJN** [comment]
I just installed following BC version :

AL Language : 3.0.102444
Business Central: W1 14.0 (14.0.28867.0) (PRERELASE 5 from DVD)

and it seems like this version does NOT have the problem with exhausting the TCP/IP ports.

**Comment by gdrenteriag** [comment]
Hello, AMCJN do you find the error?  Why Prod.Client.WebCoreApp.exe colapses connections.

**Comment by AMCJN** [comment]
Hi gdrenteriag,

No I did not find the source to the problem.
For me it helped to install the BC version mentioned above.
I have also not had the problem with Spring Release or CU1 of pring release.

**Comment by gdrenteriag** [comment]
Ok AMCJN Thanks But this link is broken: https://www.microsoft.com/en-us/download/details.aspx?id=58318 … I get that link from: https://support.microsoft.com/de-de/help/4501146/cumulative-update-01-for-microsoft-dynamics-365-business-central-sprin ….

**Comment by gdrenteriag** [comment]
The link was reactived.

**Comment by Addice73** [comment]
We are having the same issue also on 15.2 environment . Anyone solved ?

**Comment by Addice73** [comment]
Following the below picture , if a user connect using IE to Site C. We found that process “A” start consuming ports.
If we stop service “B” the problem does not occurs.
if user access with Google Chrome  or Microsoft Edge the problem does'not occurs
We checked this setting on both service and were right. We don’t have any further idea how to check or solve….
![image](https://user-images.githubusercontent.com/33353905/75450835-ce8fe480-596f-11ea-85c2-efc5e7bcb1d5.png)

**Comment by qutreson** [comment]
Closing this issue as it seems like a client issue which is beyond the scope of this repository which is only for issues related to the AL compiler in the latest developer preview environment for Dynamics 365 Business Central.

If you are still experiencing this issue on the latest version of Business Central, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
