### ISSUE TITLE
how to write code when there is not events in the function

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4666]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by thpeder** [comment]
Hi @sainath654,
You will have to provide a more detailed description of your issue.

**Comment by sainath654** [comment]
Hello thpeder,

I wanted to modify the base code. But there is no events available in that codeunit. So how can i write a code where there is no events availble.

Thanks & Regards,
Sainath

**Comment by thpeder** [comment]
Then you need to request changes to the base code so it includes the specific events that you need.
Go you [Microsoft/ALAppExtensions issues](https://github.com/Microsoft/ALAppExtensions/issues)
