### ISSUE TITLE
MaxStrLen Deprecated?

### ISSUE THREAD

**Issue by stefanoPrimo** [Microsoft/AL#4667]
Hi,
I'm trying to resolve some CodeCop error but I'm stuck here:
I was used to solving the error "Possible overflow assigning 'Text' to 'Code[128]'. (AL0139)" simply by adding a `CopyStr(myVar,1,MaxStrLen(MyVar))`.
But today I found out this Warning message:
```
{
	"resource": "",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL0141",
	"severity": 4,
	"message": "'MaxStrLen' is deprecated",
	"source": "AL",
	"startLineNumber": 55,
	"startColumn": 81,
	"endLineNumber": 55,
	"endColumn": 104
}
```

Assuming that I would not like to implement some hard-coded code (like `CopyStr(myVar,1, MaxStrLen(50))` ) also to make my code easier to maintain, How can I fix that?

Thanks
Stefano Primo

- AL Extension Version: 2.1.99743

- Server Version: BC RTM (13.0.24623.0) with a W1 Cronus DB

**Comment by stefanoPrimo** [comment]
I leave an Update:
I was watching my code where throws this warning and I saw this:
![image](https://user-images.githubusercontent.com/36199751/53571567-89bd4c00-3b69-11e9-8c0c-71ee8503bc63.png)


Now I'm a bit disappointing: If you watch carefully you will see the MaxStrLen that throws the warning and a few lines before there is also another MaxStrLen that does not throw any type of error/warning.

**Comment by thpeder** [comment]
Hi @stefanoPrimo,
The reason why you are getting an error on one and not the other is because the method has an overload. The first takes a text and the second a variant.
The method that takes a variant results in a error being raised not matter what, so you need to change it to a text if you want to use that method.

**Comment by stefanoPrimo** [comment]
Hi @thpeder,
Thanks a lot, I didn't saw or knew that the MaxStrLen method could have an overload.
