### ISSUE TITLE
XmlDocument.Load() and XmlDocument.ReadFrom()

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#4668]
Developing in BC online, I've tried to use a variable of type XmlDocument. Then I realized I cannot use .Load Method. Then I've been adviced to use the ReadFrom method but as far I could I understand, it also is not available. By other side I have the method WriteTo. Is there any other method I can use that replaces Load/ReadFrom?

**Comment by thpeder** [comment]
Hi @martinhocosta88,
What version of the compiler are you using?
Why you do think that ReadFrom is not available, with that you can parse a Text variable or an InStream to get a XmlDocument.
[Here are the docs for XmlDocument](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmldocument/xmldocument-data-type)

**Comment by martinhocosta88** [comment]
Hello @thpeder .
using 2.1.79379 at the moment
Since it's available, gonna pull the lattest and check again thanks.
