### ISSUE TITLE
importing config. package error

### ISSUE THREAD

**Issue by boych83** [microsoft/AL#4669]
Hello,
I've had issue when importing predefined package with testability object included on my container.
I've received error "Something went wrong" during import.

1. Import testability objects
2. Create new company with no data
3. Go to "Config. package" and import predefined package "W1.ENU.EVALUATION"

There is event subs. defined in Codeunit 130232 referencing to non existing Codeunit 130231.
```
    [EventSubscriber(Codeunit,130231,OnCheckIgnoringNotification)]
    LOCAL PROCEDURE SetIgnoreOnCheckIgnoringNotification@1000(NotificationID@1000 : GUID;VAR Ignore@1001 : Boolean);
    BEGIN
    END;
```
Event Viewer errors:
```
Message Fatal error during metadata load -- Type:CodeUnit; Id:130231; MetadataGroup:0; MetadataLoaded:True; CLRLoaded:False; ThreadGroup:0
Message (NavNCLMetadataObjectNotFoundException): RootException: NavNCLMetadataObjectNotFoundException
Object of type CodeUnit with ID 130231 could not be found.
```
Business Central version:
```
"platform": "14.0.28496.0"
"version": "14.0.28630.0"
```

**Comment by atoader** [comment]
Hi! What docker image are you using? It might be a packaging issue because as far as I can see, codeunit 
130231 exists in the source.

**Comment by boych83** [comment]
Hi,
I'm using this:
"bcinsider.azurecr.io/bcsandbox-master:rs-ltsc2019"
"sha256:f7288dea8671ab3640ca3b11a3ff5ec777e78805bd4c32f5c52df576ce1d0e9f"

BR,
Bojan

**Comment by kalberes** [comment]
@boych83  

is this still an issue?

**Comment by boych83** [comment]
After 3y probably not😊

**Comment by kalberes** [comment]
Ok closing it then

**Comment by boych83** [comment]
Ok
