### ISSUE TITLE
Objects not compiled in C/SIDE export incorrectly to new syntax - add a warning

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#467]
When a Object is not Compiled in the source database, the Txt2Al converter generates inconsequent compile errors.

Using: "Update-AppFolderAL -DevInstance Dev -AppFolder Name"
Output:
`TableRelation="WMS Item Unit of Measure".Code WHERE (Item No.=FIELD(No.));`
should be
`TableRelation="WMS Item Unit of Measure".Code WHERE ("Item No."=FIELD("No."));`

Maybe write a note in the object that the objects is not compiled in the source database?

![image](https://user-images.githubusercontent.com/28626283/28961028-1a931d86-7901-11e7-87de-e896764e3b16.png)

**Comment by esbenk** [comment]
It is a requirement that the object is compiled in the database. Thanks for the suggestion.

**Comment by bvbeek** [comment]
Yes, but it would be fine that it's mentioned in the al-object

**Comment by atoader** [comment]
We have documented that you should compile objects before exporting to the new syntax: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool 
This problem can be avoided by scripting the conversion process to always compile the objects before exporting.
