### ISSUE TITLE
Enable Field on Report Requestpage by using a global variable

### ISSUE THREAD

**Issue by achim-t** [microsoft/AL#4673]
**Describe the bug**
The Property Enabled on fields in a Report's Requestpage can't be set by a variable. If set directly by `Enabled = true;` it works.

The Property Visible doesn't work either.

**To Reproduce**
```
report 51000 "test report"
{
    UsageCategory = None;
    ProcessingOnly = true;
    requestpage
    {
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    field(used; PaymentsTo)
                    {
                        ApplicationArea = All;
                        Caption = 'Payments to';
                        Enabled = PaymentDateEnabled;
                    }
                }
            }
        }
        trigger OnOpenPage()
        begin
            PaymentDateEnabled := true;
        end;
    }
    trigger OnInitReport()
    begin
        PaymentDateEnabled := true;
    end;
    var
        PaymentsTo: Date;
        PaymentDateEnabled: Boolean;
}
```

**Expected behavior**
The field should be enabled. Either by OnOpenPage or by OnInitReport.

**Versions:**

 - AL Language: 2.1.79379 

 - Business Central: US Dynamics NAV 13.3 (27233)

**Comment by sd484** [comment]
Still open? 
I would like to offer different option values depending on values set via program code. For this purpose I duplicated a selection field and created different selections using the OptionCaption and ValuesAllowed properties. Unfortunately, I cannot show the appropriate field via the Visibility property.

**Comment by achim-t** [comment]
@sd484, thank you.

It is working now as expected.
