### ISSUE TITLE
UICop: A Blob cannot be used as a source expression for a page field

### ISSUE THREAD

**Issue by erikrijn** [microsoft/AL#4675]
I think this warning is not justified: A Blob cannot be used as a source expression for a page field

**Table field:**

>     field(49; "Base Image"; Blob)
>     {
>          Subtype = Bitmap;
>          DataClassification = CustomerContent;
>     }

**Page:**

>     layout
>     {
>         area(content)
>         {
>             field("Base Image"; "Base Image")
>             {
>                 ApplicationArea = All;
>             }
>         }
>     }

**Comment by RobynGee** [comment]
Blobs other than bitmaps do cause problems, see below earlier issue.

https://github.com/Microsoft/AL/issues/2346

The bitmap type should not require a warning though, it works OK.
