### ISSUE TITLE
Service Crash in 14.0.28496.0 On Page With Control Add-In

### ISSUE THREAD

**Issue by jcooper01** [microsoft/AL#4676]
We are experiencing a BC service tier crash in Platform 14.0.28496.0 + Application 28630 (US Dynamics NAV 14.0) running in a Docker container. We aren't quite clear on the steps to reproduce, but the same .app file does not cause the crash in the current BC release. The crash happens while the user is sitting on a page that has a JavaScript add-on on it. The crash seems to happen after a certain amount of time, rather than by any user interaction (if the page loads and the user does not interact with it, the service will crash within two minutes). Again, we have not been able to determine the cause, and stepping through AL code does not reveal anything (the crash happens at different places in the code, as it seems to be more related to timing than anything else). I dumped some of the container event log and included it below. Let me know what other information you need.

   Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
    1850 Feb 28 10:37  Information Windows Error                1001 Fault bucket , type 0
                                   Reporting                         Event Name: CLR20r3
                                                                     Response: Not available
                                                                     Cab Id: 0

                                                                     Problem signature:
                                                                     P1: Microsoft.Dynamics.Nav.Server
                                                                     P2: 14.0.28496.0
                                                                     P3: eeda9862
                                                                     P4: Microsoft.Dynamics.Nav.Ncl
                                                                     P5: 14.0.28496.0
                                                                     P6: e01e815e
                                                                     P7: f5b
                                                                     P8: 13
                                                                     P9: D5WU24HOIWMNSBCWI3QEYEJRFIGFIY40
                                                                     P10:

                                                                     Attached files:

                                                                     These files may be available here:
                                                                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\A
                                                                     ppCrash_Microsoft.Dynami_ce4fc9ff4adb7b70c424588f6
                                                                     d2ea1a0e8ba1fce_084b03e1_34c3ef37

                                                                     Analysis symbol:
                                                                     Rechecking for solution: 0
                                                                     Report Id: dd913ada-045e-46e0-98d4-4e1443d7589f
                                                                     Report Status: 96
                                                                     Hashed bucket:
    1849 Feb 28 10:36  Information Windows Error                1001 Fault bucket , type 0
                                   Reporting                         Event Name: CLR20r3
                                                                     Response: Not available
                                                                     Cab Id: 0

                                                                     Problem signature:
                                                                     P1: Microsoft.Dynamics.Nav.Server
                                                                     P2: 14.0.28496.0
                                                                     P3: eeda9862
                                                                     P4: Microsoft.Dynamics.Nav.Ncl
                                                                     P5: 14.0.28496.0
                                                                     P6: e01e815e
                                                                     P7: f5b
                                                                     P8: 13
                                                                     P9: D5WU24HOIWMNSBCWI3QEYEJRFIGFIY40
                                                                     P10:

                                                                     Attached files:

                                                                     These files may be available here:
                                                                     C:\ProgramData\Microsoft\Windows\WER\ReportQueue\A
                                                                     ppCrash_Microsoft.Dynami_ce4fc9ff4adb7b70c424588f6
                                                                     d2ea1a0e8ba1fce_084b03e1_34c3ef37

                                                                     Analysis symbol:
                                                                     Rechecking for solution: 0
                                                                     Report Id: dd913ada-045e-46e0-98d4-4e1443d7589f
                                                                     Report Status: 4100
                                                                     Hashed bucket:
    1848 Feb 28 10:36  Error       Application Error            1000 Faulting application name:
                                                                     Microsoft.Dynamics.Nav.Server.exe, version:
                                                                     14.0.28496.0, time stamp: 0xeeda9862
                                                                     Faulting module name: KERNELBASE.dll, version:
                                                                     10.0.14393.2636, time stamp: 0x5bda7edc
                                                                     Exception code: 0xe0434352
                                                                     Fault offset: 0x0000000000034048
                                                                     Faulting process id: 0xe78
                                                                     Faulting application start time:
                                                                     0x01d4cf79def958fb
                                                                     Faulting application path: C:\Program
                                                                     Files\Microsoft Dynamics
                                                                     NAV\140\Service\Microsoft.Dynamics.Nav.Server.exe
                                                                     Faulting module path:
                                                                     C:\Windows\System32\KERNELBASE.dll
                                                                     Report Id: dd913ada-045e-46e0-98d4-4e1443d7589f
                                                                     Faulting package full name:
                                                                     Faulting package-relative application ID:
    1847 Feb 28 10:36  Error       .NET Runtime                 1026 Application: Microsoft.Dynamics.Nav.Server.exe
                                                                     Framework Version: v4.0.30319
                                                                     Description: The process was terminated due to an
                                                                     unhandled exception.
                                                                     Exception Info: Microsoft.Dynamics.Nav.Types.Excep
                                                                     tions.NavNCLNotInitializedException
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.get_Element()
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.Finalize()

    1846 Feb 28 10:36  Warning     MicrosoftDynamicsNav          218 Server instance: NAV
                                   Server$NAV                        Tenant ID:
                                                                     User:
                                                                     Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavN
                                                                     CLNotInitializedException
                                                                     SuppressMessage: False
                                                                     ContainsPersonalOrRestrictedInformation: False
                                                                     DiagnosticsSuppress: True
                                                                     MessageWithoutPrivateInformation: Microsoft.Dynami
                                                                     cs.Nav.Runtime.NavXmlAttributeCollection variable
                                                                     not initialized.
                                                                     SuppressExceptionCreatedEvent: False
                                                                     FatalityScope: None
                                                                     Message: Microsoft.Dynamics.Nav.Runtime.NavXmlAttr
                                                                     ibuteCollection variable not initialized.
                                                                     StackTrace:
                                                                          at Microsoft.Dynamics.Nav.Runtime.NavXmlAttri
                                                                     buteCollection.get_Element()
                                                                          at Microsoft.Dynamics.Nav.Runtime.NavXmlAttri
                                                                     buteCollection.Finalize()
                                                                     Source: Microsoft.Dynamics.Nav.Ncl
                                                                     HResult: -2146233088
                                                                     StackTrace:
                                                                          at Microsoft.Dynamics.Nav.Runtime.NavXmlAttri
                                                                     buteCollection.get_Element()
                                                                          at Microsoft.Dynamics.Nav.Runtime.NavXmlAttri
                                                                     buteCollection.Finalize()

    1845 Feb 28 10:36  Error       MicrosoftDynamicsNav          700 Server instance: NAV
                                   Server$NAV                        Category: Runtime
                                                                     ClientSessionId:
                                                                     00000000-0000-0000-0000-000000000000
                                                                     ClientActivityId:
                                                                     00000000-0000-0000-0000-000000000000
                                                                     ServerSessionUniqueId:
                                                                     00000000-0000-0000-0000-000000000000
                                                                     ServerActivityId:
                                                                     8667edea-d922-4b6a-ba62-a5d1d5d1c9f3
                                                                     EventTime: 02/28/2019 15:36:43
                                                                     Message (NavNCLNotInitializedException):
                                                                     RootException: NavNCLNotInitializedException
                                                                     Microsoft.Dynamics.Nav.Runtime.NavXmlAttributeColl
                                                                     ection variable not initialized.
                                                                     ExceptionStackTrace:
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.get_Element()
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.Finalize()
                                                                     CallerStackTrace:
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.get_Element()
                                                                        at Microsoft.Dynamics.Nav.Runtime.NavXmlAttribu
                                                                     teCollection.Finalize()

                                                                     ProcessId: 3704
                                                                     Tag: 00000MX
                                                                     ThreadId: 2
                                                                     CounterInformation:

**Comment by atoader** [comment]
Hi @jcooper01 ! We need more information before we can find the root cause. We suggest that you open a support case or file a bug in Collaborate.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
