### ISSUE TITLE
Need dotnet variable support in AL code

### ISSUE THREAD

**Issue by Rama-M** [Microsoft/AL#4678]
Due to the lack of support for dotnet variable, we could not convert our C/AL code to AL code.  It is a very important feature, which needs to be there before the C/AL code is retired.  So please add support of dotnet variable at least for the on premises edition of business central.

**Comment by atoader** [comment]
@Rama-M what do you mean by dotnet variable? Do you mean? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al

**Comment by dNsl9r** [comment]
OnPrem as @atoader wrote, in Cloud - depends on your needs. What .NET Classes do you use? For what kind of solution? Maybe you can use other (new) variable types like HttpClient, XmlNode and so on (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview) - or with Azure Functions?

**Comment by Rama-M** [comment]
We are using call to EFT payment provider. It is a big limitation not having full support of dot net variable especially on Azure cloud environment.

**Comment by AndreyKorepanov** [comment]
You can declare .Net type inside the dotnet packages and reference it using DotNet. For more information please see the reference sent by @atoader.

This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get further help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
