### ISSUE TITLE
Crash of compiler

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/AL#4679]
With #4117 , one case of an error was fixed.

I have found probably 3/4 cases, where the compiler still crashes:

All Cases are with 
- activated translation file
- Pageextensions on a page of an extension
- moving fields/actions around

case 1: Seems to be similar to ticket 4117, but crashes
Case 2: Moving Actions
Case 3/4: adding several new items, move one existing between them.

To reproduce it, i attached a demo project, based on sales and inventory forecast.
- Just delete the comments to let it crash.

- AL Extension Version: 2.1.92604

- Server Version: W1 13.5 (28640) (from preview)

[ALProject1 - Demo.zip](https://github.com/Microsoft/AL/files/2927533/ALProject1.-.Demo.zip)

**Comment by qutreson** [comment]
Hi @stephanweidmann, can you elaborate a bit more about the crashes that you are experiencing?

I tried publishing the extension you attached and it was published and installed successfully.

**Comment by stephanweidmann** [comment]
Hi, 

on the page extension, there are several lines with comments (//). If you uncomment one or all of them, the compilation crashes.

**Comment by qutreson** [comment]
I published it with the moveafter/movebefore uncommented and couldn't reproduce it. 

Are you experiencing the crash when compiling the extension, when trying to publish it or at runtime, when trying to open it? 
What is the error that you are getting? Can you share a stack trace with us or some event logs?

**Comment by stephanweidmann** [comment]
The crash occures on compiling or after Compiling (CTRL-Shift-B).

Seems, that the compile itself works, but the creation of the xlf file crashes.

Compilation started for project 'ALProject1' containing '2' files at '10:36:37.511'.
Compilation ended at '10:36:37.615'.
[Error - 10:36:37] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.'
Details:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.<>c__DisplayClass12_0.<VisitSymbolWithProperties>b__1(PropertySymbol property) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 77.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source, Action`1 action) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\EnumerableExtensions.cs:Zeile 55.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitSymbolWithProperties(Symbol symbolWithProperties) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 70.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.DefaultVisit(Symbol symbol) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 29.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 118.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 118.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:Zeile 118.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:Zeile 24.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:Zeile 24.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:Zeile 24.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:Zeile 24.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.WriteDefaultNodesAndContinue(XmlWriter writer, String appName, String targetLanguage, Action groupContentWriter) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:Zeile 65.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LanguageFileOutputter.OutputLanguageFile(Compilation compilation, Stream outputStream, String appName) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LanguageFileOutputter.cs:Zeile 33.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.OutputLanguageFile(Compilation compilation, CompilerTextWriter consoleOutput, ErrorLogger errorLogger) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 512.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 440.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 313.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__4.MoveNext() in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:Zeile 47.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:Zeile 45.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\84\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:Zeile 59.

**Comment by qutreson** [comment]
Hi @stephanweidmann, I just gave it a try on our master branch and with the extension from the marketplace (version 3.0.126610) and I couldn't reproduce the issue. Can you give it a try as well?

**Comment by stephanweidmann** [comment]
I hope it is fixed finally, I do not want to invest any more time in this bug. I'll close the issue
