### ISSUE TITLE
Save the collapsed state in the 'Problems' window

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4683]
**Describe the bug**
When dealing with compiler errors / warning, we often tend to close / collapse errors on a certain file and continue with the error of another file. However, the collapsed errors / warning often are expanded automatically ...

**To Reproduce**

Closing ...

![image](https://user-images.githubusercontent.com/25268332/53790491-5b53be00-3f27-11e9-9f23-000b28e57789.png)

.. few seconds after, the collapsed state is no longer saved and the first object is expanded again.

![image](https://user-images.githubusercontent.com/25268332/53790704-dcab5080-3f27-11e9-8ccc-2d09b43d4136.png)

Even when clicking on the 'Collaps' icon ('-'), the lines do not stay collapsed ...

**Expected behavior**
Save the state of the collapsed files in the 'Problems' windows.

**Versions:**

![image](https://user-images.githubusercontent.com/25268332/53790735-f64c9800-3f27-11e9-97cb-437c82400a6c.png)

**Comment by kalberes** [comment]
Probably caused by the nondeterministic way the background compiler works.
