### ISSUE TITLE
How to Check visibilty of Action TestPage in Test Suite Codeunit

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/AL#4684]
Hi 

I have followed the Below scenario for my test Suite codeunit for visibility check to Action,
   
[Test]
    procedure TestActionVisibilityTRUEFromSalesInvList()
    var
        SalesInvoices: TestPage "Posted Sales Invoices";
    begin
        // [SCENARIO ] 
        // [Given] 
        CleanSetup(Setup);

        // [When] Open the posted sales Invoice List page
        SalesInvoices.OpenView();

        //[Then] Check field visibility
        Assert.IsTrue(SalesInvoices."ActionName".Visible(),'Action should be visible');
        SalesInvoices."ActionName".Invoke();
        SalesInvoices.Close();
    end;
SalesInvoices.ActionName.Visible always getting **False**, 

**#Page Extension
#Development APP Installed** 
pageextension  50000 "TEST Posted SalesInvces" extends "Posted Sales Invoices"
{

    layout
    {
    }
    actions
    {
        addafter(ShowLog)
        {
            action("ActionName")
            {
                Caption = 'ActionName';
                Promoted = true;
                PromotedCategory = New;
                PromotedIsBig = true;
                Visible = FieldActive;
                Image = Calls;
            }
        }
    }
     var
        FieldActive: Boolean;

    trigger OnOpenPage()

    begin
        CheckActive();
    end;

    local procedure CheckActive()
    begin
        FieldActive := True;

    end;
}

Please let us know how we can write Visibility check in Test Suite Codeunit?

thanks!

**Comment by dejfidson** [comment]
What ApplicationArea of the action? If you don't specify ApplicationArea for action (or any other control) then the action is not visible.

**Comment by srinivasGangadhara** [comment]
Yes we have added applicationArea like below 

addafter(ShowLog)
    {
        action("ActionName")
        {
            ApplicationArea=AL00;
            Caption = 'ActionName';
            Promoted = true;
            PromotedCategory = New;
            PromotedIsBig = true;
            Visible = FieldActive;
            Image = Calls;
        }
    }

also extended the application Area Setup 

tableextension 50001 "TEST Application Area Setup" extends "Application Area Setup"
{
    fields
    {
        // Add changes to table fields here
        field(50001; AL00; Boolean)
        {
            Caption = 'AL00TEST';
            DataClassification = CustomerContent;
        }
        
    }

    var
        myInt: Integer;
}

But still we are getting Visible False, Let me know if am wrong 

thanks!

**Comment by dejfidson** [comment]
Try ApplicationArea = All;

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
