### ISSUE TITLE
Field "Creditor Identifier" in table "Bank Account" and field "Direct Debit Mandate ID" in table "Customer Bank Account" not available in Visual Studio Code

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/AL#4685]
Field "Creditor Identifier" in table "Bank Account" and field "Direct Debit Mandate ID" in table "Customer Bank Account" are not availabe in Visual Studio Code. Docker container is CU14 and AL Language is from CU13. The fields are available in the webclient on de Customer Bank Account Card and Bank Account Card.

**Comment by Chingyz** [comment]
@StanislawStempin @JesperSchulz, can someone elaborate on this issue?

Thank you in advance.

**Comment by JesperSchulz** [comment]
I just checked our latest code and cannot find any Creditor Identifier field. What version are you using? Which country? In which version did you last see the field? Do they maybe come from an extension?

**Comment by Chingyz** [comment]
Thank you for the quick response.
I believe the fields are part of the dutch localization.

Version: 11.0.26893, Netherlands.
AL Language version: 0.13.68736
Docker container version: microsoft/dynamics-nav:2018-nl-ltsc2019

Object versions:
Table 270, Bank Account, NAVW111.00.00.26893,NAVNL11.00.00.26893  
Table 287, Customer Bank Account, NAVW111.00.00.26893,NAVNL11.00.00.26893

**Comment by JesperSchulz** [comment]
I just checked the latest build of version 11.0 of our Dutch application. Both fields exist and should be available for extension development. @atoader, any idea what's going on here?

**Comment by Chingyz** [comment]
@atoader , have you had te time to take a look?

Thank you in advance.

**Comment by atoader** [comment]
Hi! It seems that you are not using the latest developer preview. Could you please open a support case with CSS? They will guide you through the process of reproducing this issue and they will open a request for hotfix with us.
