### ISSUE TITLE
Mismatch Streams: From SaveAs to EmailFileFromStream

### ISSUE THREAD

**Issue by stefanoPrimo** [Microsoft/AL#4687]
Hi,
I have the need to send an E-Mail with a PDF attachment created from a report.
I've seen from another issue that to CU "Document-Mailing" has been added a new procedure "EmailFileFromStream" that permits to send emails with attachment. 
Now I'm stuck because I use the method 
`Report.SaveAs(Id, XmlParameters,ReportFormat::Pdf,OutStream,RecRef);`
that saves the output of the report into an OutStream Variable but the method to send the email with the attachment requires an InStream Variable:
`DocumentMailing.EmailFileFromStream(OutStream, [OtherParam])`

Is there any CUs that can convert an OutStream to an InStream (in order to send this email)?
I've also seen that in the procedure EmailFileFromStream there is this code:
```
[External] EmailFileFromStream(AttachementStream : InStream;AttachmentName : Text;Body : Text;Subject : Text;MailTo : Text;HideDialog : Boolean;ReportUsage : Integer) : Boolean
TempFileName := FileManagement.ServerTempFileName('');
TempFile.CREATE(TempFileName);
TempFile.CREATEOUTSTREAM(OutStream);
COPYSTREAM(OutStream,AttachementStream);
TempFile.CLOSE;
```
It cannot be more useful if the parameter's data type (`AttachementStream`) could be converted into a Variant one and check:
```
if (Variant.IsInStream()) then begin
   TempFile.CREATEOUTSTREAM(OutStream);
   COPYSTREAM(OutStream,AttachementStream);
   TempFile.CLOSE;
end else if (Variant.IsOutStream()) then begin
   TempFile.CREATEOUTSTREAM(OutStream);
   OutStream := AttachementStream;
   TempFile.CLOSE;
end else ERROR('Not a Stream Datatype');
```
Let me know
Stefano

- AL Extension Version: 2.1.99743

- Business Central Version: RTM with W1 DB

```
XmlParameters := Report.RunRequestPage(ReportId);
        RecRef.GetTable(Rec);        
        Report.SaveAs(ReportId, XmlParameters,ReportFormat::Pdf,OutStrea,RecRef);
        DocumentMailing.EmailFileFromStream(OutStrea,'name' + '.pdf','','',EmailAddress,false,-1);
```

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by stefanoPrimo** [comment]
Hi @atoader 
This it was intended as a feature suggestion

**Comment by atoader** [comment]
Hi @stefanoPrimo ! I misunderstood your request, but I think it might be better if you post this on BC Ideas as the application teams are monitoring that channel.
