### ISSUE TITLE
Debugger stops correctly then hangs the service tier

### ISSUE THREAD

**Issue by SCreanor** [microsoft/AL#4688]
When using the Daily Build and attempting to use the debugger, the breakpoint is hit correctly, however when attempting to F11, step into the code, the debugger might proceed between 1 to 5 steps and then never stop again. The service tier stops responding and requires a restart to allow any client to connect again. I tried to isolate this to an issue with my machine, however a colleague managed to achieve the same issue using the repro steps outlined below.

To reproduce this issue, download the daily build (AU Version), open a new Hello World project and put a loop from 1 to 50 in the OnOpenPage trigger. Apply a breakpoint to the start of the loop and deploy the extension and debug. The breakpoint will be hit, pressing F11 will continue between 1 to 5 times and then the debugger stops responding and no client can connect until the service tier is restarted.

The expected behaviour is as per the Current Build which does not have this issue. The debugger halts in the breakpoint, and pressing F11 steps through the code, pressing F5 continues processing and completes correctly and the client displays the page.

By analysing the difference between the event logs of the working Current Build and the broken Daily Build the only difference seen is the signalr attempts to negotiate where the Current Build seems to skip this step and just goes straight to the start request. This issue has been present about 3 weeks. Prior to that the Daily Build debugger worked as expected.

One further thing observed trying to isolate this issue. If you start the Windows Client and leave it open, then start debugging the Web client, the issue behaves differently. The debugger will step through the code a few times, and then appear to hang. It generally will come back after a few seconds, up to 10 or 15 seconds at worst. If however when it has appeared to hang, you click on a list (any list) in the Windows Client to force the Windows client to query the database, the debugger returns control immediately to VS code, ready for the next F11. I have no explanation for why it does this, just an observation. If you then close the Windows client and attempt to start a new debug session, the system hangs completely requiring a service restart. This is a reproducible observation.

Any assistance would be appreciated, this is very frustrating.

AL Language Version: 2.1.100277
BC Version: 14.0.28773.0-AU

**Comment by kalberes** [comment]
Thanks for the detailed analysis.

**Comment by SCreanor** [comment]
Sorry I am not a SQL guy, so have no idea how to run SQL analytics, but if you guide me through it I can probably turn it on for you and send you what you need. Yes my build does support Ctrl+Shift+F5 and I tried that and got the exact same issue as a normal Debug.

I have managed to try this on a later version. AL: 3.1.102444, BC: 14.0.28831 but it exhibits the same issue. Of note is that a different colleague does not seem to have this issue with the same build, so there is clearly something triggering this that is on some machines but not others. The current test case, has a clean Server 2019, with SQL 2017, VS Code and a NAV install and it is showing the problem, as is the Daily Build docker download. The Install version is using Windows Authentication whilst Docker is using UserPassword, so even the authentication method is different.

I have attached the event log from the time I started debugging to when I had to shutdown the service because it had stopped responding, but there is not a lot in there. I have also included a video showing the issue so you can see it in action, there is clearly a link between the Windows client and the debugger. But returning control to the debugger, only works if you do something in the Windows client that causes it to query the database. 

[Files.zip](https://github.com/Microsoft/AL/files/2935626/Files.zip)

**Comment by kalberes** [comment]
Thanks for the input. I think what you see is by design. You were trying to access records on the Windows client, while  a debugging session was going on. It is true that the session debugged belongs to the webclient, but you have probably locked a record used by both. While you are debugging a session, and others are using the same server these kind of things can happen. The probability is higher if using the RTC client in correlation with the VsCode debugger, where response time is much faster. 
But I will investigate further what can be done. Even if the Windows client is now reaching the retirement age.

**Comment by SCreanor** [comment]
I only mentioned the Windows client out of curiosity, it does not change the initial problem. Developing and using only the Web Client, and not having the Windows client open at all causes the debugger to hang. So the fundamental problem is developing for BC on the latest builds seems to be hanging. I would be very happy to drop the Windows client altogether but at the moment it is the only way I can continue developing for the Web client and maintain the debugger responsiveness.

**Comment by nixpt82** [comment]
How many cores where you are running the service? Initially i was runing with 2 after i upgrade the VM to 4 stop having that issue.

**Comment by kalberes** [comment]
The CPU Core issue is a known issue that will be fixed in the next update.
Details/workaround here:
https://freddysblog.com/2019/06/03/debugging-hangs-in-business-central-spring-2019-rtm-and-cu1/

**Comment by SCreanor** [comment]
Yes I can confirm that upping my cores to 4 fixed the problem immediately, thanks for the tip it lets me use the workaround until a permanent fix is released.
