### ISSUE TITLE
Hyperlink function not working correctly in BC Web Client

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/AL#4689]
**Description:**
The Hyperlink function is working differently between Windows Client and Web Client.
When trying to open a Word document using the Protocol Handler functionality (ms-word:ofe) the Windows Client works perfectly fine and opens the document, the Web Client tries to prefix the link with the Web Client's base address.

**Reproduce:**
Make some dummy code that executes the Hyperlink function with a URL in this format:
'ms-word:ofe|u|file://[share]/filename.docx'
Try running it from both a Windows and a Web Client. The Windows Client nicely opens the document, the Web Client won't.

**Expected Behaviour:**
That both the Windows and The Web Client nicely open the document.

**Screenshots**
![image](https://user-images.githubusercontent.com/18245218/53812574-18f8a400-3f5c-11e9-9c79-cfb27384e228.png)

**Versions:**
13.0.27183

**Comment by atoader** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by nathanbrittles** [comment]
I am testing with version 17.0.16993.0 and if you use hyperlink with a file, for example Hyperlink ('file: /// C: /TestDes/Fichero10.pdf');
It doesn't work, if you use a normal address it does.
Does anyone know why this happens and how to solve it?

**Comment by Danieldwe** [comment]
Hi,

i have the same problem. I try to open a local file in web client. 
Earlier, i used Hyperlink('C:/Temp/test.pdf'), but this doesn't work in webclient. Is there a possibility to open a local file in Web client? Maybe in an extra tab or something else.

Thanks a lot.

**Comment by NKarolak** [comment]
You cannot. It's been always like that in the web client.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-hyperlink-method#remarks

What does work: pasting such links manually into a new browser tab. Text files will be displayed instantly, but other file types will require a download (with confirmation) first.
