### ISSUE TITLE
Conversion issues

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#469]
When you convert files with txt2al, flowfields (or any reference to fields) is a mess.  
To solve, I suggest you put double quotes around all named symbols.

Example of flowfield:
![image](https://user-images.githubusercontent.com/12088142/28971234-896759b4-792b-11e7-8e02-eaaf26a1078a.png)
Should be:
![image](https://user-images.githubusercontent.com/12088142/28971303-c142d34a-792b-11e7-9e79-7046abe1d51d.png)

or:
TableRelation="Planning Header LCX".No.;
should be:
TableRelation="Planning Header LCX"."No.";

Also, new fields on a table extension are being generaged without a "name", so you get an obvious syntax mistake, like:
field(;"My New Field");
{
}

**Comment by esbenk** [comment]
Is the object compiled before exporting with the Command=ExportToNewSyntax switch? That is a requirement.

**Comment by waldo1001** [comment]
Well, these were deltas.. so I need to create deltas from the txt files with new syntax?

**Comment by esbenk** [comment]
Yes.

**Comment by waldo1001** [comment]
Ok, clear! 
Thanks!
