### ISSUE TITLE
XMLNode properties

### ISSUE THREAD

**Issue by giann85** [Microsoft/AL#4690]
Hi, i need to migrate a function from NAV to Business Central, but i don't find a new way to works:

in NAV thic code works:

NodeList := Node.ChildNodes;   (to get a general nodes)
ChildNode:= nodelist.item(x)      (select first node for example)
ChildNode.Name = textvalue (to check if is the specific node)

in business central     the  proprierties  Name  on  XMLNode type not exist.

is there an alternative method to recover the value?

**Comment by giann85** [comment]
i've found solution:

if Node.AsXmlElement.HasElements then begin     // for not get error if node not has any elements          
NodeList := Node.AsXmlElement.GetChildElements;
NodeList.Get(x,ChildNode);
if  ChildNode.AsXmlElement.Name = textvalue then
.....more line code
end;

but if the node has no elements, the node name there is no way to recover it.

any suggestions?

**Comment by AndreyKorepanov** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
