### ISSUE TITLE
New Publisher Function Request on Page 193 OnAfterLoadDataFromRecord

### ISSUE THREAD

**Issue by ClintonSaundersSeeSide** [Microsoft/AL#4691]
Please can we have a new publisher function as above that has the 'MainRecordRef' as a parameter, and is called at the end of the "LoadDataFromRecord" function? That will allow developers to subscribe to the Publisher function and access the 'MainRecordRef' variable from the subscriber function.

I need this as I have written a 'Drag and Drop' ControlAddIn extension to select files using Drag and Drop (instead of the File Dialogue), and need to be able to dynamically access the record to which the attachments needs to be attached.

Much appreciated!

Clinton

**Comment by dNsl9r** [comment]
You should post EventRequests in this Repo: https://github.com/Microsoft/ALAppExtensions/issues

**Comment by ClintonSaundersSeeSide** [comment]
Thank you for the response and advice. I have posted the request there.

**Comment by qutreson** [comment]
Closing this issue as it is related to [ALAppExtensions](https://github.com/Microsoft/ALAppExtensions/issues)
