### ISSUE TITLE
[Intellisense] Validate a procedure hides procedure definition

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#4692]
Hi,

When we want to call a procedure, if we write its name until the end we could see its definition all the time. But if we hit the return key to force autocompletion, we lose the window with these useful informations and have to re-open the parenthesis to be able to see again the procedure definition.

I think an image will be more eloquent:
![procedureautocompletion](https://user-images.githubusercontent.com/29598240/53941110-8ec55280-40b7-11e9-8a7c-2854f3bc81bf.gif)

It could be very usefull to keep the procedure definition displayed even if we chose to autocomplete!

Thanks!

**Comment by AndriusAndrulevicius** [comment]
have you tried Ctrl+Shift+Space?
source: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by JulienDecottignies** [comment]
I didn't know this shortcut, but it's a solution.
I'm often switching between Visual Studio and Visual Studio Code, and in Visual Studio the autocompletion doesn't print the parenthesis, so we have an eye on the definition without losing it. 
The CTRL + SHIFT + SPACE shortcut is also available in Visual Studio anyway.
Finaly it's maybe more a question of habits..!

**Comment by qutreson** [comment]
Signature help is triggered after the parenthesis is opened on the procedure or when the shortcut is used. It seems that our implementation of Intellisense that automatically adds the parenthesis of methods without parameters does not trigger signature help, hence the confusion. We will try to improve this in the future whenever we have time for it.

**Comment by nndobrev** [comment]
Hi,
 
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
 
Thanks,
