### ISSUE TITLE
Korean Encoding Bug

### ISSUE THREAD

**Issue by bhlDeex** [Microsoft/AL#4694]
**Korean Encoding Bug**
I tried to print a Sales Quote with Korean written but it seems that the encoding doesn't work.
As you can see on the screenshot, please include the Korean encoding in the next release. 
![img](https://user-images.githubusercontent.com/48191630/53943729-1e432380-4101-11e9-9fe3-54e6d3c8541b.jpg)

 - Business Central: 
The version that I have is the latest version: W1 13.3 (28186).

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
