### ISSUE TITLE
DEV License when publishing extension

### ISSUE THREAD

**Issue by pcornacora** [Microsoft/AL#4695]
We developed an extension V2 for NAV 2018 CU  10 our customer intends to automate via PowerShell script the installation/upgrade of the extension: expectations are for us to provide the upgraded .app file in a designated path and for the customer to then been able to perform the upgrade autonomously. We prepared a PowerShell script implementing the following steps:

1 - Uninstall previous extension version
2 - Unpublish previous extension version
3 - Publish new extension version
4 - Synchronize extension versions (using Sync-NAVApp)
5 - Performing the required data upgrade (Start-NAVAppDataUpgrade)

The customer does not have a developer license and their customer license, with all objects correctly assigned, is running on all services.

When running step 3 (Publish new extension version) we receive an error caused by the fact that the customer license does not allow publishing.

The issue is resolved if we add to additional steps to the script using Import-NAVServerLicense to temporary import our partner license prior the first step and to restore the customer license after the last step.

Having to import our license while having to automate the installation/upgrade of an extension forces as to potentially leave our license accessible to the customer (obviously something we do not want to do).

Is their a way to automate the installation/process and to install/publish an extension while using a Customer license?

**Comment by AskeHolst** [comment]
Create a [Runtime Package](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages).

**Comment by pcornacora** [comment]
Thanks that solves our issue.
