### ISSUE TITLE
[txt2al] Pages with controladdinns are not converted

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#4697]
**Describe the bug**
Hi,

we have trouble converting custom pages to al, if they include Control-AddInns.
Those objects are skipped with the error:
Error converting   file: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.

**To Reproduce**
Create a new page with a ControlAddinn and try to convert it

**Screenshots**
This is one of the pages, the controladdin is PingPong, so its standard and none of our own.
![image](https://user-images.githubusercontent.com/41729653/53968505-7b39dc00-40f7-11e9-9c14-0a232258d4cf.png)

 - Business Central: CU2

**Comment by atoader** [comment]
Hi! This is supported in the latest developer preview. You should always use the Txt2Al tool that is released with the developer preview.
