### ISSUE TITLE
Enum Field Usage for linking Main / SubPage

### ISSUE THREAD

**Issue by wweidl** [microsoft/AL#4698]
Description: 

If the Records of a SubPage and Main Page are linked via a Enum Field, the System does not correctly populate the values in the SubPage and the Client also does not show the Enum Values, if a Tablerelation was defined.

![image](https://user-images.githubusercontent.com/46991052/53975083-59932180-4104-11e9-87a2-290d3e5ea4f0.png)

[ALProject10.zip](https://github.com/Microsoft/AL/files/2942458/ALProject10.zip)

I have attached a Sample Project.

Versions:
 - AL Langauge: 3.0.102444
 - Business Central:14.0.28823

**Comment by BartPermentier** [comment]
Have you tried the setting PopulateAllFields?

**Comment by wweidl** [comment]
Even, if it should not be necessary to set PopulateAllFields - I have tried it with PopulateAllFields = true, but the Behaviour is the same - the Field MyField1 in the SubPage has no Value and in the DropDown-Box no Enum Values are shown.

**Comment by kevindstanley1988** [comment]
This is a serious bug that makes enums not able to replace optionstrings. I am experiencing this same behavior in the spring release. This I believe is also related to a bug with enums and GetFilter and Evaluate. 

This also does not work if you do page variables and record setranges like below. There is no filter set on the opened page.
`tableA.SetRange("Enum Field 1", "EnumValue1");`
`listPageA.SetTableView(TableA);`
`listPageA.Run();`

**Comment by kine** [comment]
Please, move this bug higher on the queue, because it is already known many months and not solved. We cannot use ENUM till this is solved, because any page using enums is not behaving as option regarding auto-filling the values based on the filters and this is BIG BLOCKING BUG to adopt enums!

If you want example of the difference, I can send you simple app I made to test that.

**Comment by esbenk** [comment]
Fixed in the 2019 Wave 2 release and the upcoming CU of the Wave 1 release
