### ISSUE TITLE
AL crashes when i try to make Navigation Page

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#470]
While I creating Navigation page my AL crashes. May be this is not because of this page type, but the problem exists.
![image](https://user-images.githubusercontent.com/29101017/28974365-d29d3b68-793e-11e7-822e-1a576da7bf39.png)

**Comment by DominikDitoIvosevic** [comment]
@dkatson does this bug always reproduce or was it a one time thing which stopped happening after you reloaded vscode?
I tried various combinations similar to what you have in the screenshot and I cannot reproduce the bug.
Could you try and provide us with some steps or whole source file which causes this issue?
