### ISSUE TITLE
The type or Method 'file' can not be used for 'Extension' Development

### ISSUE THREAD

**Issue by SangitPPanchal** [Microsoft/AL#4701]
Here, I'm having a below error for record variable (File).

![the type or method file can not be used for extension development](https://user-images.githubusercontent.com/35402654/54028246-72fea100-41ca-11e9-8eb6-69fc2ad34780.png)

- In this case I want to get all the files name with full path from folder credential.
  **example** :  this is credential folder '**E:\Credentials\**' and i want to get all the files name with full 
  path like this '**E:\Credentials\techcronus.txt**', '**E:\Credentials\sangit.txt**'.

So, is there any other way to get all the files path? if any then please let me know.
Thanks !
@StanislawStempin, @SUD-D365, @pmohanakrishna

- here is the example of code
           `action("Get Files Name")
            {
                Caption = 'Get Files Name';
                image = GetLines;
                trigger OnAction();
                var
                    fileRec: Record File;
                begin
                    fileRec.Reset;
                    fileRec.SetRange(Path, 'E:\Credentials\');
                    if fileRec.FindSet then begin
                        repeat
                            Message(fileRec.Name);
                        until fileRec.Next = 0;
                    end;
                end;
            }`

**Comment by BartPermentier** [comment]
It is not possible if you build something for the SaaS solution. For the OnPrem you set your target to "Extension"in the app.json file. (Don't forget to update your settings in the Service)

**Comment by SangitPPanchal** [comment]
> It is not possible if you build something for the SaaS solution. For the OnPrem you set your target to "Extension"in the app.json file. (Don't forget to update your settings in the Service)

Thank you for the reply @BartPermentier . And I'm working on D365 BC Saas. So, there is no any possibility to get paths of all files right now or in the near future?

**Comment by thpeder** [comment]
Hi @SangitPPanchal,

@BartPermentier is correct.
To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
