### ISSUE TITLE
Operator '=' cannot be applied to operands of type 'Option' and 'Enum' (AL0175)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4703]
**Is your feature request related to a problem? Please describe.**
_Not sure about what's supported / what's in the pipeline for enum conversion in the next release..._ 

Our C/AL code is currently full of integer <> option conversions. To support the move to AL, we're gradually integrating enum properties on our table fields in C/AL. When converting the C/AL code to AL, AL0122 error shows up:

> Cannot implicitly convert type 'Integer' to 'Enum NVTStatus'

```
procedure SetStatusType(piStatusType: integer) // Cast integer to ENUM = NOK
    begin
        bolFinancialStatus := (piStatusType = Type::Financial); 
```

Since we're on C/AL, we're trying to fix the error in C/AL first. To avoid this error, we changed the integer parameters in to options. However, now we're running into AL0175

> Operator '=' cannot be applied to operands of type 'Option' and 'Enum' (AL0175)

```
procedure SetStatusType(piStatusType: option) // Integer > Option
    begin
        bolFinancialStatus := (piStatusType = Type::Financial); // Compare option to ENUM = NOK
```
Seems like implicit conversion from Option to Enum is not supported.
Although when changing the code to first cast the option to an enum, no errors show up...

```
procedure SetStatusType(piStatusType: option)
    var
        MyEnum: enum NVTStatus;
    begin
        MyEnum := piStatusType; // Cast option to ENUM = OK
        bolFinancialStatus := (MyEnum = Type::Financial);
```

**Describe the solution you'd like**
Please provide support for enum <> option conversion.
Please provide better documentation on what conversion are / will be supported using enums. (Taking into account the fact that partners are still on C/AL and are preparing for AL conversion in C/AL)

**Comment by esbenk** [comment]
We have lifted the restriction for converting/comparing enums for the spring release. We expect to long term add again to improve code-quality, but we need everything to be on AL first.

This should work if you work the bcinsider.azurecr.io/bcsandbox-master docker images.
