### ISSUE TITLE
Include 'Enum' type as part of a TableRelation definition

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4704]
**Is your feature request related to a problem? Please describe.**
Somehow related to #4703 : How should I refactor my table relations in C/AL in case my field has an EnumTypeId/Name assigned? Code below does not compile ('Type' field is an Enum. Enum contains the value 'Operational').

`TableRelation = "NVT Status".Code where (Type=const(Operational));` 

> "Reference 'Type' in application object 'NVT Status' does not exist",

**Describe the solution you'd like**
Provide support for table relations converted from C/AL to AL.
Same remark for AL, can you provide a sample code on how to include enum types in the table relation definition?

**Comment by kalberes** [comment]
@esbenk

**Comment by esbenk** [comment]
This is supported in upcoming spring release. Please try with the bcinsider.azurecr.io/bcsandbox-master docker images.

We have added support for marking an table Option field as an enum, but that is to generate symbols for AL code to work with. In C/AL and C/SIDE it is still just seen as an Option. We are not planning to back-port more enum functionality to C/AL.

**Comment by frivadulla** [comment]
> 
> 
> This is supported in upcoming spring release. Please try with the bcinsider.azurecr.io/bcsandbox-master docker images.
> 
> We have added support for marking an table Option field as an enum, but that is to generate symbols for AL code to work with. In C/AL and C/SIDE it is still just seen as an Option. We are not planning to back-port more enum functionality to C/AL.

Why are you not adding the enums request?

**Comment by esbenk** [comment]
We are working on adding enums, but the work associated is much higher than just adding an event. We need to make sure that all the places that uses the enum are handling "unknown"/new values added.

**Comment by fvet** [comment]
We're in 'hybrid' mode, leaving us with the main part of the objects (5000+) still in C/AL, but gradually updated with the EnumTypeId, EnumTypeName properties in C/AL to support new modules to be developed in AL. In AL, we thus need to be able to define a proper table relation as in the original post.

**Comment by esbenk** [comment]
It is supported in the latest CU for the fall release and in the upcoming spring release. If you have a failure in on of those please provide complete repro steps.
