### ISSUE TITLE
I am not able to make any changes in Design Mode opened through F6 from VS Code in Sandbox Environment

### ISSUE THREAD

**Issue by tjaitly1986** [Microsoft/AL#4705]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by tjaitly1986** [comment]
I have stopped the designer and reopened it and it worked fine and than I pressed F7 in VS Code and it has successfully applied the changes.

**Comment by qutreson** [comment]
Hi @tjaitly1986, may I close this issue if the problem is now fixed for you?

**Comment by tjaitly1986** [comment]
Yes please.

Thanks
