### ISSUE TITLE
How to access CAL Customization object from AL Extension?

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4706]
Hello,

I wanted to access a custom function which is created in CAL. Someone in GITHUB suggested to go through with the CAL and AL side by side.So I have gone through with the MSDN C/AL and AL side by side. Still i couldnt able to access the CAL Customisation in AL. Please help me on this. Below is things i have done after going through the MSDN website.
[navcommandresult.txt](https://github.com/Microsoft/AL/files/2950939/navcommandresult.txt)

1.I have enabled the Enable loading application symbols at server startup checkbox in the BC Administration. 
2.I have compiled the objects with powershell with the generatesymbolreference, it create navcommandresult.txt with the message [0] [03/11/19 12:09:39 PM] The command completed successfully in '0' seconds.

Thanks&Regards,
Sainath.

**Comment by mynhardt7** [comment]
@sainath654 
It's definitely not working if it completed in zero seconds. Try running the finsql.exe from the command line to generate the symbols. You can reference the MSDN site for the exact command.

**Comment by AndreyKorepanov** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
