### ISSUE TITLE
Translation files missing in BC CU3 in DVD

### ISSUE THREAD

**Issue by Ajef** [Microsoft/AL#4707]
**Describe the bug**
Translation files are missing in Elster.app and Elster.Source.zip for Business Central on premise CU3 DEU DVD, which are required for an upgrade.
While the Demo-Database has the translated app preinstalled the directory "Extensions" does not provide the .app-file with translations.

**Versions:**
Business Central CU3 13.0.27183

**Comment by Ajef** [comment]
Seems to be fixed in CU4.

**Comment by kjlhgfds** [comment]
@Ajef Sorry to post here for nothing about this issue, but I couldn't find any other way to contact you.
I have a question about a problem you had with a closed repository : https://github.com/filebrowser/filebrowser/issues/635
You said that you "removed the .htaccess- authorization requirement". What do you mean exactly and how did you do this ? I'm having the same issue right now : /
Thanks and sorry again for the unrelated post.
