### ISSUE TITLE
Publish-NAVApp error on server version '0.12'

### ISSUE THREAD

**Issue by StephanFeijen** [Microsoft/AL#4708]
On executing the statement below, I get error:
Publish-NAVApp : The runtime version of the extension package is set to '1.0', which is newer than what is compatible with this server version '0.12'.
Please build the extension package with the version of the AL Language extension shipped with this server.
Statement: Publish-NAVApp -Path -ServerInstance -SkipVerification
NAV Server version: 11.0.24742
A runtime version below 1.0 is not supported by the AL compiler.
Do you have a solution for this? Is there a way to set the server version?

**Comment by StephanFeijen** [comment]
On executing the statement below, I get error:
Publish-NAVApp : The runtime version of the extension package is set to '1.0', which is newer than what is compatible with this server version '0.12'.
Please build the extension package with the version of the AL Language extension shipped with this server.

Statement: Publish-NAVApp -Path <path appfile> -ServerInstance <instancename> -SkipVerification
NAV Server version: 11.0.24742

A runtime version below 1.0 is not supported by the AL compiler.
Do you have a solution for this? Is there a way to set the server version?

**Comment by qutreson** [comment]
Hi @StephanFeijen, are you using the AL extension that matches your server or are you using the one from the VS Code marketplace? 

As you are using NAV11, I believe you should be using the extension that you got from the DVD. The versioning system for the AL extension was introduced when BC Spring 2018 (runtime 1.0) was released, so NAV 11 is not supported by newer extensions (including the one from the market place).

**Comment by StephanFeijen** [comment]
Hi qutreson,

Thank you for your answer, it looks promising.
I’ve installed the extension from the DVD (0.13.82793) but now I’m having difficulties downloading the symbols.
It says “All reference symbols have been downloaded.” but in fact the symbol files seem to be incomplete.
Any idea how to get around this problem?
I’ve tried running “finsql.exe Command=generatesymbolreference …” and on hyperlink for finsql generatesymbolreference is set to Yes.

Met vriendelijke groet,
Stephan Feijen
[UDP-logo zonder achtergrond]
M +31 6 2862 3063

Van: qutreson <notifications@github.com>
Verzonden: dinsdag 12 maart 2019 13:07
Aan: Microsoft/AL <AL@noreply.github.com>
CC: Stephan Feijen <s.feijen@uwdynamicspartner.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Microsoft/AL] Publish-NAVApp error on server version '0.12' (#4708)


Hi @StephanFeijen<https://github.com/StephanFeijen>, are you using the AL extension that matches your server or are you using the one from the VS Code marketplace?

As you are using NAV11, I believe you should be using the extension that you got from the DVD. The versioning system for the AL extension was introduced when BC Spring 2018 (runtime 1.0) was released, so NAV 11 is not supported by newer extensions (including the one from the market place).

**Comment by qutreson** [comment]
Hi @StephanFeijen, are you sure you followed the steps listed [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side) and did not forget anything about it? 

As this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
