### ISSUE TITLE
The name 'AssignQuote' does not exist in the current context AL(AL0118)

### ISSUE THREAD

**Issue by SangitPPanchal** [Microsoft/AL#4709]
Here I'm having issue while i try to call the function **AssignQuote** from Table **Opportunity** .

![Issue AL(AL0118)](https://user-images.githubusercontent.com/35402654/54066957-05e91b00-425f-11e9-8423-b65db31e8f26.PNG)

So, after that i opened NAV2018 and tried to find the function **AssignQuote**, I found this function in Opportunity table as below image.

![NAV 2018](https://user-images.githubusercontent.com/35402654/54066974-392baa00-425f-11e9-9400-10fabcc98e25.PNG)

but, after that i tried to find **AssignQuote** function in the D365 On-premise, but i was not able to find, So where can i find this function?

Thanks!

**Comment by thpeder** [comment]
The procedure seems to have been renamed to CreateQuote but this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
