### ISSUE TITLE
BC Timout when sending big Files from JavaScript to BC

### ISSUE THREAD

**Issue by IamLerxx** [Microsoft/AL#4710]
- AL Extension Version: ﻿# Business Central Fall 2018 update (CURRENT - 2018/08/27)

- Server Version: DE Dynamics NAV 13.0 (24630)

In my JavaScript extension i send a JSON to BC. No problem until the JSON gets quiet big. When sending more than about 30 mb BC times out and all related processes get terminated.

event SendFilesToBC(MyFile: JsonObject);

Showing code here wouldn't help much since i am just calling a function with a lot of data.

**Comment by frankmnielsen** [comment]
In the BC Admin Console snapin there is a Client setting called "max upload size". Up until recently this was 30mb and it sounds like it is what you run into.  In later versions MS has changed this to 150mb.

If you want more - you simple change the setting unless you use BC cloud and it cannot be changed. In that case your have to implement chunking = you javascript needs to break up the json and send it in smaller blocks

On the BC side you will run into an array of limitations - but this snippet will get you around it:
 
        tempBlob.Blob.CreateInStream(is);
        tempBlob2.Blob.CreateOutStream(os);
        block := 0;
        repeat
            httpClient.Post(serviceUrl + '&b=' + Format(block), httpContent, httpResponse);
            statusCode := httpResponse.HttpStatusCode();
            if (statusCode = 200) or (statusCode = 201) then httpResponse.Content.ReadAs(is);
            if block = 0 then begin
                CopyStream(os, is);
            end else begin
                while not is.EOS() do begin
                    readLen := is.Read(buf2);
                    os.Write(buf2, readLen);
                end;
            end;
            block := block + 1;
            httpContent.Clear();
            httpContent.WriteFrom('');
        until statusCode <> 201;
        readLen := tempBlob2.Blob.Length;
        tempBlob2.Blob.CreateInStream(is);

Have fun

Michael - Father of C/AL

**Comment by atoader** [comment]
Thanks for the reply @frankmnielsen ! :) You are completely right. @IamLerxx I recommend you use one of the following resources for future questions as this repository is only meant to help with bugs and questions related to the latest development environment preview for the AL language.:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
