### ISSUE TITLE
Suggestion: support using const in DataItemLink (Query)

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#4711]
You should consider adding the option to specify a const in the DataItemLink.

As an example, the idea would mean being able to do this:

```
dataitem(Customer; Customer)
{
    // (...)

    dataitem(SalesPrice; "Sales Price") 
    {
        DataItemLink = "Sales Code" = Customer."No.",
                       "Sales Type" = const ("Customer");    
         // (...)                 
    }
}
```

Business Central frequently uses the pattern of having two fields for an external key (one to specify the table you are linking, another to specify the key). Ex: when configuring a Sales Price, you can choose whether it applies to a Customer, Customer Group or All Customers.

Now, let's say that I want to do a left outer join to that table, because I want two get all customers with a count of all salesprices assigned for the particular customer (among other customer related info).

That is currently impossible, as any dataitem query filters are added to the Where clause (and that automatically excludes all records where the join didn't find a Sales Price, transforming the outer join in an inner join equivalent). 

I've tried to simplify the example, but in the last months I've been involved in several integrations between BC and external apps, that use OData to read data, and today marks the third time where a simple query has to be transformed into something much more complex (and less efficient) due to the fact that I had to link data against a table that used this pattern.

**Comment by kalberes** [comment]
Makes sense. I do not remember what was the historical reason not supporting const here and some other places.

**Comment by louagej** [comment]
Hi @kalberes ,

Beside using a `const` as @salgiza  mentioned, we should also be able to add a `filter` as well.
See comment in issue: https://github.com/microsoft/AL/issues/4423#issuecomment-508080164

Kind regards,
Job Louage

**Comment by matthiasbier** [comment]
Hi @kalberes ,

is there any progress on this issue? Seems quite important to be able to insert a const or a filter in the DataItemLink working with tables that are linked through "Source Type" like "Warehouse Shipment Line" fo example....

Thank you

Best regards
Matthias

**Comment by kalberes** [comment]
No progress. You should add it as an idea,  gather some votes and than it will be considered.
![image](https://user-images.githubusercontent.com/12760483/140616958-f87ce7c3-cd71-4438-96c1-517b9a315320.png)

**Comment by dnpb** [comment]
I might not have searched exhaustively, but didn't find an Idea yet, only this, which mentions it indirectly:
[Allow Queries to link to setup tables](https://experience.dynamics.com/ideas/idea/?ideaid=472f445d-a24b-ea11-b698-0003ff68dcf8)
> This could be achieved by allowing the DataItemLink to be of the format DataItemLink = "Primary Key" = Const('');

It would indeed be good to have this (generally; I don't specifically care about setup tables).
So, I've created the Idea, for everyone to go and upvote please:
* _**[Support using const or filter in Query DataItemLink property, equivalent to including constant value(s) in SQL JOIN](https://experience.dynamics.com/ideas/idea/?ideaid=fc893249-7841-ec11-a3ee-0003ff45ebbf)**_

**Comment by pborring** [comment]
Daniel reposted this on https://aka.ms/bcideas, where it will be tracked going forward, thus closing this entry. Please continue voting on the ideas site.
https://experience.dynamics.com/ideas/idea/?ideaid=fc893249-7841-ec11-a3ee-0003ff45ebbf
