### ISSUE TITLE
RoleCenter-Extension Triggers don't work

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#4713]
**Describe the bug**
We tried adding a new Activities Part to a RoleCenter. This Activities-Cardpart should only be shown if certain data is set. So we added a Visible-Boolean-Variable in the RoleCenter-PageExtension, changed the Visible-Property in the Part and set the variable in the OnOpenPage-Trigger. 

![image](https://user-images.githubusercontent.com/35929603/54137213-848bb700-441d-11e9-9983-637d47f98a10.png)

But the PagePart is shown regardless of any Code in the OnOpen Page. 

![image](https://user-images.githubusercontent.com/35929603/54137242-94a39680-441d-11e9-8daa-7d8e20e7876a.png)

So we added a message to the OnOpenPage(Extension)-Trigger, but nothing's Happening. Same with the OnAfterGetRecord. 

![image](https://user-images.githubusercontent.com/35929603/54137153-64f48e80-441d-11e9-9aae-1dcc465c3999.png)

I've attached the whole ALProject 

[ActivityPageVisibleTest.zip](https://github.com/Microsoft/AL/files/2953006/ActivityPageVisibleTest.zip)

**Versions:**
 - AL Langauge-Version: 2.1.79379
 - Business Central-Version: mcr.microsoft.com/businesscentral/onprem:cu2-de

**Comment by qutreson** [comment]
Hi @JulianTillmann, role centers in AL do not allow having triggers defined. When defining a new role center you would get the following diagnostics:

![image](https://user-images.githubusercontent.com/31541422/54180244-6cf31380-449b-11e9-95fd-c17d3ae14908.png)

You would also get similar diagnostics when defining a trigger on page elements like in a field or an action.

It seems that we are missing some validation in page extensions that are targeting a page of type role center.

**Comment by JulianTillmann** [comment]
ok, we found out ourselves that Code in the RoleCenter-Triggers doesn't work in C/SIDE, but at least we get a Compiler error. Could you please see to that Validation in AL? Thanks in Advance

Also: how do you propose to solve this requirement? To dynamically set the visibility of a RoleCenter-Part?

**Comment by qutreson** [comment]
We will fix the missing validation from page extensions.

I do not know if there is an alternative that you can use to dynamically set the visibility of a part in a RoleCenter. Did you try posting your question in one of the following forums?
[Business Central Community](https://community.dynamics.com/business/f/758)
[Mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by JulianTillmann** [comment]
I'm sorry, but I thought this was the place to find the Solutions for cloud Ready extensions for Business Central? 

We are not interested in workarounds but would like to have a solution to this requirement within the AL standard.

**Comment by qutreson** [comment]
We will add to our backlog to investigate on the possibility to remove this restriction on role centers in future releases. We can use this issue to track it on Github.

**Comment by qutreson** [comment]
We added validation for triggers defined in Role Centers in our master branch (targeting Fall 2019) as well as some better validation around Role Centers in page and page extensions.  Concerning the ability to define trigger code in Role Centers, please consider logging it on https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by ZjTham** [comment]
ddd
