### ISSUE TITLE
PermissionSet doesn't manage PageExt

### ISSUE THREAD

**Issue by Nyryus** [microsoft/AL#4715]
Hi,

the AL PermissionSet cannot manage permission sets exported from NAV BC.

Through NAV I've recorded all the actions that the user should do with the extension.

This extension is dependent from another extension.
The result is a permission set that contains objects of:
* type = 14
* id = object ID
* description = the obj description

![immagine](https://user-images.githubusercontent.com/40896051/54137407-ea783e80-441d-11e9-8a57-dc005c895a23.png)

The exported permission set, contains this node:
```
<Permission>
      <ObjectType>14</ObjectType>
      <ObjectID>18122022</ObjectID>
      <ExecutePermission>Yes</ExecutePermission>
</Permission>
```
Edited version for AL
```
<Permission>
      <ObjectType>14</ObjectType>
      <ObjectID>18122022</ObjectID>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
</Permission>
```
The usage of this node in the ExtensionsPermissionSet.xml cause this warning:
warning AL1025: The file at location '[ExtLocation]\extensionsPermissionSet.xml' does not match any definition.

Would be nice to have this type of permission managed in AL.

Versions:
 - AL Langauge: 2.1.79179
 - Business Central: W1 13.0 (24630)

Thank you for your support.
Nyryus

**Comment by stefanoPrimo** [comment]
Hi @thpeder,
first of all, any news? 
I've also noticed that the permission set won't work if there are also TableExtensions.
Are the Table and Page Extension are supported by the permission sets? 
Thanks
Stefano

**Comment by atoader** [comment]
@stefanoPrimo @Nyryus we will try to accommodate this for a future release. I cannot give you an estimate on when this will be available.

**Comment by kalberes** [comment]
@Nyryus

xml based permission sets are slowly deprecated. Does the issue also reproducible with the permission set application object?

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
