### ISSUE TITLE
txt2al: Put references to option values between quotes to prevent collisions with reserved words

### ISSUE THREAD

**Issue by jhoek** [microsoft/AL#4716]
**Describe the bug**
When referencing option values from properties, txt2al should probably surround the option value with double quotes, as some option values may collide with reserved words

**To Reproduce**
1. Create a table with an option field called MyField with the word "Sorting" as one of the option members. 
2. Create another table with a field that has a TableRelation to the first table. The table relation filter should filter on field MyField, with constant value Sorting. 
3. On my machine, this leads to AL0104 - Syntax error ")" expected. 
4. All works OK if I surround the const value Sorting with double quotes.

**Expected behavior**
Txt2al should probably add the double quotes around any reference to an option member, since these option members may be the same as current/future reserved words.

**Screenshots**
![Option_value_names_that_are_reserved_words](https://user-images.githubusercontent.com/1273387/54195921-38458300-44c0-11e9-9858-7dc2e2d66d9d.png)

**Versions:**
 - AL Language: 2.1.79379 
- txt2al from 2019 CU3
 - Business Central: n/a

**Comment by fvet** [comment]
I might want to add the same remark for 'dotnet variables' too. Please add " " around the dotnet type when in the variable declaration to avoid reserved keyword conflicts.
