### ISSUE TITLE
Could not load file or assembly System.Net.Http

### ISSUE THREAD

**Issue by srenders** [Microsoft/AL#4717]
**Describe the bug**
Error when downloading symbols

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
AL GO to create new project
AL: Download symbols

**Expected behavior**
Symbols to be downloaded

**Screenshots**

**Versions:**

 - AL Langauge: 3.0.104632

 - Business Central:
bcinsider.azurecr.io/bcsandbox-master:base

More error info:
[Error - 12:56:48] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
Details:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in C:\a\189\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\189\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

-------------------------------------------------
Solutions that did not work:
-------------------------------------------------
Removing all extensions in VSCode
Restarting VSCode
Deleting the folder: 
C:\Users\Administrator\.vscode\extensions
Reinstalling the .vsix from the docker image

**Comment by kalberes** [comment]
Do you have .net framework 4.7.2 installed on your machine with VsCode?

**Comment by srenders** [comment]
I did, and first it didn't solve the issue, then I uninstalled and re-installed and now it works again. Very strange, because I'm using a Win Server 2016 with Docker and VSCode, nothing else installed.

**Comment by umang11** [comment]
didn't worked for me same error persist

**Comment by lvanvugt** [comment]
AL Version: 3.0.115791

Today I downloaded the latest bc on-prem docker image (BC build 14.0.29530) and build a container with it. Everything is installed. All clients (windows, web, dev) can be run. Now wanting to deploy the extensions I am currently working on I opened these projects in VSCode. I removed the old symbol files and triggered a new download getting exactly the same error as @srenders describes.

Installed .Net framework 4.7.2 as per @kalberes suggestion and things are working right, now.

**Question**: How does anybody know .Net framework 4.7.2 needs to be installed for BC spring 2019? New-NAVContainerHelper does not check this.

**Comment by ryancairnsy** [comment]
+1 on what Luc says. My whole team couldn't download symbols this morning after it seems AL Language has updated to 3.0.115791

We are all on Windows Sever 2016 1607 Build 14393.

Glad to have found this issue quickly this morning! :)

**Comment by SatyaRaghamreddy** [comment]
![image](https://user-images.githubusercontent.com/49481770/55875647-9028e580-5b63-11e9-8cef-94ae4e5a0e40.png)
 

Please guide me on this issue...

**Comment by Sid12345678** [comment]
Install .Net framework 4.7.2. The issue should be resolved.

**Comment by anilkumar15** [comment]
MSBuild.exe -version
Microsoft (R) Build Engine version 4.7.2053.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

4.7.2053.0

Connect-MicrosoftTeams : Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1

Connect-MicrosoftTeams -Credential $credentials

**Comment by Sid12345678** [comment]
Hi Anil,

Download .NET Framework 4.7.2. This should solve the issue.

Thanks & Regards
H Siddharth
