### ISSUE TITLE
Notification appears on Customer list page instead of card page.

### ISSUE THREAD

**Issue by pbhavsar** [Microsoft/AL#4718]
I open a customer card page and show a notification in OnAfterRecordGet trigger.
The issue I'm having is that the notification always appears on the list page behind the card page dialog.
Here is my code:
```
pageextension 70166830 MyCustomerCardExtension extends "Customer Card"
{
    trigger OnAfterGetRecord()
    var
        notification: Notification;
    begin
        notification.Message('test notification');
        notification.Send();

    end;
    
}
```

**Comment by thpeder** [comment]
Please provide the versions on the server and the VSCode AL language extension.

**Comment by qutreson** [comment]
Closing this issue as we didn't get further information about it. Please open a new issue if you are still facing it on the latest developer preview.
