### ISSUE TITLE
Support for additional text encodings

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#472]
Up to now, only a few encodings can be distinguished in text coding. For example, ASCII says nothing about the codepage used (can be 437, or any 8XX, depending on the country). This can be problematic when implementing interfaces. For this reason, it would be good if one could also pass the text encoding as a number. So you could decide exactly how to read a text. Likewise, it would be good in this respect if the standard .NET functionalities would be available for converting different text encodings (Encoding.Convert). This would make working with texts much easier.

**Comment by Avanti05** [comment]
Convert.GetEncoding() would be nice as well.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
