### ISSUE TITLE
How to create field to store website link and Open URL from BC

### ISSUE THREAD

**Issue by Tonygithub17** [Microsoft/AL#4722]
I having issue when i need to create the new field to store my web site link. In On premise version we create the new  field  then can set property "ExtendedDatatype" to URL.

From Interface we can click that link to open web site, is it this support in AL code or any other alternative way ?

below is a screenshot : 
Windows Client Interface
![image](https://user-images.githubusercontent.com/34825577/54329478-c9e1fb80-464c-11e9-82d8-d217ef60f775.png)

BC interface
![image](https://user-images.githubusercontent.com/34825577/54329524-f564e600-464c-11e9-8c46-9d51d652b347.png)

**Comment by AndreyKorepanov** [comment]
In AL we in works in the same way ExtendedDatatype = URL;

**Comment by AndreyKorepanov** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
