### ISSUE TITLE
TestSuiteApp  :  not able to find the Custom Tables data which are in Base App which is used as dependency for creating Test Suites.

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/AL#4726]
we are working on Automated Test Suite taken Base App as dependency for test app. 

In one of the case we have to insert data in setups of Custom Tables (Base App). Created data needs to be update in Sales Order for this we have used OnInsert subscriber of Table 36 which is working for Base App. 

where as, while trying the same for Test suite, we are not able to find the Custom Tables data which are in Base App which is used as dependency for creating Test Suites.

**Sales Header Extended Below**
tableextension 50001 ExtendSalesOrder extends "Sales Header"
{
    fields
    {
        // Add changes to table fields here
        field(50001; "Order Status"; Code[50])
        {
            DataClassification = ToBeClassified;
        }
    }
    
    trigger OnAfterInsert()
    var
        OrderStatus : Record "Order Status";
        RecRef : RecordRef;
    begin
        RecRef.SetTable(Rec);
        OrderStatus.SetRange(ObjectID,RecRef.Number());
        OrderStatus.SetRange("Object Type",Rec."Document Type"::Order);
        if OrderStatus.FindFirst() then
            "Order Status" := OrderStatus.Status;
    end;
}

**Custom Table Setup**

table 50002 "Order Status"
{
    DataClassification = ToBeClassified;
    
    fields
    {
        field(1;ObjectID; Integer)
        {
            DataClassification = ToBeClassified;
            
        }
        field(2;"Object Type"; Option)
        {
            OptionMembers = Quote,Order;
            DataClassification = ToBeClassified;
            
        }
        field(3;"Status"; Code[50])
        {
            DataClassification = ToBeClassified;
            
        }
    }
    
    keys
    {
        key(PK; ObjectID)
        {
            Clustered = true;
        }
    }
}

Please let us know if we are missing any setup?

thanks!

**Comment by atoader** [comment]
@tejabalusu I am not sure I understand the issue you are facing. Could you please elaborate? This question might be better suited for one of the following forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by qutreson** [comment]
Hi @tejabalusu can you provide us with some more information about the issue that you are experiencing?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
