### ISSUE TITLE
Upload Extension button in Cloud Sandbox Environment

### ISSUE THREAD

**Issue by SteveyN** [microsoft/AL#4727]
I have looked through these issues and found [#2106](https://github.com/Microsoft/AL/issues/2106) and [#3545](https://github.com/Microsoft/AL/issues/3545) which are similar issues, but they do not actually answer the question.

**Why exactly is the Upload Extension button on the Extension Management page disabled in Sandbox environments?**

For consultant ease of use, and the deployment of third-party .apps where we don't have the source code, it makes little sense that we can upload .apps freely to the Production Environment but not the Sandbox Environment.

Can an explanation be provided? The addition of this button to the Sandbox Extension Management page would be extremely useful. If it is planned to be enabled in a future update, what is the timeline for this (as mentioned in [#3931](https://github.com/Microsoft/AL/issues/3931#issuecomment-428709952) Oct, 2018)?

**Comment by MortenRa** [comment]
Seems to be handled in April release :https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2019/03/27/scheduling-your-spring-2019-upgrade-for-business-central
