### ISSUE TITLE
Actions on notifications dosent work in BC 2019 spring

### ISSUE THREAD

**Issue by kguldbaek** [Microsoft/AL#4729]
**Describe the bug**
In the lates BC 365 Spring build, when on a notification try to click on an action, nothing happens. It doesn't matter if it is a custom notification or a build-in notification.

**To Reproduce**
Open role center
Click "Don't show this again" at the Sandbox notification
Then nothing happen

**Expected behavior**
Should launch the action 

**Versions:**
 - AL Langauge:  3.0.104632
 - Business Central: GB Dynamics NAV 14.0 (29065)

**Comment by MortenRa** [comment]
We Experience the same behavour, none of our notification react on click makes it unable to start our Wizard for our app activation. 

Versions:

AL Langauge: 3.0.107312
Version: Platform 14.0.29248.0 + program 29399 (DK Dynamics NAV 14.0)

**Comment by MortenRa** [comment]
Currently working again in

AL Language AL Language 3.0 106655
Version: Platform 14.0.29563.0 + program 29610 (DK Dynamics NAV 14.0)

**Comment by atoader** [comment]
Hi @MortenRa! It seems the fix made its way to you before the GitHub message. :) I will close this issue.
