### ISSUE TITLE
Differentiate between Jobs Blocked::All and Blocked::Posting

### ISSUE THREAD

**Issue by alexlang24** [Microsoft/AL#4730]
Jobs can be set to different "blocked" options but different than in customers or vendors there is no difference between these options.

In function [External] TestBlocked() the field Blocked is checked on option value "empty":

IF Blocked = Blocked::" " THEN
EXIT;
ERROR(TestBlockedErr,TABLECAPTION,"No.",Blocked);

I am missing the difference between Blocked::All and Blocked::Posting.

// possible solution
[External] TestBlocked(CheckValue BOOLEAN)
IF CheckValue THEN BEGIN
IF (Blocked = Blocked::" ") OR (Blocked = Blocked::Posting) THEN
EXIT;
END ELSE
IF Blocked = Blocked::" " THEN
EXIT;
ERROR(TestBlockedErr,TABLECAPTION,"No.",Blocked);

Blocked::Posting means, it is not allowed to post anything related to this job but entering the job no. in e.g. job time journal or sales documents is allowed.

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
