### ISSUE TITLE
Inconsistency of data in Jobs after Bill-to Contact No. OnValidate

### ISSUE THREAD

**Issue by alexlang24** [Microsoft/AL#4731]
In the field Bill-to Contact No. an INIT command is used. This is executed if you remove the Bill-to Customer No. which results in a complete empty Job record except the No., No. Series and Description field.

If you have added Job Dimensions to the Job before removing the Bill-to Customer No., these are not removed from the Default Dimension table. But the fields "Global Dimension 1 Code" and "Global Dimension 2 Code" are cleared.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Go to Job List, create new Job
2. Add Bill-to Customer No. 10000
3. Add Global Dimension 1 Code and Global Dimension 2 Code
4. Remove Bill-to Customer No.

**Expected behavior**
Variant 1) The Default Dimensions are deleted
Variant 2) Remove the INIT comand

**Versions**
 - AL Language: 2.1.79379
 - Business Central: Build 27233

**Comment by thpeder** [comment]
Hi @alexlang24 

Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
