### ISSUE TITLE
XLIFF translatoins only worked for Caption, not worked for Label

### ISSUE THREAD

**Issue by alphazzzzz** [microsoft/AL#4732]
**Describe the bug**
I want to translate captions and labels with XLIFF file and find out the translations for captions are displayed correctly but the translations for labels don't work at all.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Using a hello world AL project created by AL:GO!.
2. Add any field with a customized caption in pageextension.
![image](https://user-images.githubusercontent.com/33475811/54508323-83f4a280-4980-11e9-82b3-e487955640c4.png)

3. Add features: translation files
4. Run AL:Package and the xliff file generated, rename the xlf file to avoid to be overwritten.
5. add target translations
![image](https://user-images.githubusercontent.com/33475811/54509114-5c530980-4983-11e9-8083-023aa5aefe29.png)

**Expected behavior**
the caption and label translations will display correctly.

**Screenshots**
Lable translation doesn't work
![image](https://user-images.githubusercontent.com/33475811/54508626-683dcc00-4981-11e9-971a-f9b3b4b9ea1f.png)

but caption translation workes
![image](https://user-images.githubusercontent.com/33475811/54508698-a2a76900-4981-11e9-92fd-468b2d4024c5.png)

**Versions:**

 - AL Langauge: Name: 
AL LanguageId: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.0.56865
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=microsoft.al

 - Business Central: W1 13.1,  13.0.26198.0
![image](https://user-images.githubusercontent.com/33475811/54508799-15184900-4982-11e9-84dd-036de7925e1f.png)

I tested this issue both on Docker container with image microsoft/bcsandbox:hk which pulled 3 month ago
and on D365BC On-Premise CU03 W1

**Comment by alphazzzzz** [comment]
Finally, I find out how to resolve this issue. according to the locale code list from https://www.science.co.il/language/Locale-codes.php, the target language should be zh-hk with language id 3076. I used zh-CHT and it only worked for caption translation but not label tranlsation.

Please close this issue.

**Comment by atoader** [comment]
Thank you for letting us know about the fix @alphazzzzz ! I will close this issue.
