### ISSUE TITLE
Automatic prefix not work for pageextension with CRS

### ISSUE THREAD

**Issue by SarahBirrer** [Microsoft/AL#4734]
After I added a microsoft standard NAV field to a pageextension, the prefix was not automatically set. 

1. I created a new page extension for the "Sales Order" page
2. I added the field "Sell-to Customer Name 2"
3. The field was added but the fieldname hadn't set a prefix after saving the file

Is this behaviour correct? What are the advantages for not setting a prefix on standard pageextension fields?

This is my code:

```
pageextension 3040897 "LOG BASE SalesOrder" extends "Sales Order" //42
{
    layout
    {
        addafter("Sell-to Customer Name")
        {
            field("Sell-to Customer Name 2"; "Sell-to Customer Name 2") // I think here should be a prefix
            {
                ApplicationArea = All;
            }
        }
}
```

**Comment by atoader** [comment]
Hi! This is not supported. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
