### ISSUE TITLE
InternalServerError, Symbols not downloading?

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#4735]
Hi Experts,

I am facing a very strange error. I am trying to download Symbols from a sandbox instance.
But I am getting below error, and also it seems that its a tenant specific error. Because with other sandbox instance I am able to download symbols without any error.

publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-03-18 14:51:46.47] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-03-18 14:52:28.83] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-03-18 14:52:28.84] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

Below is my app.json
{
  "id": "6be441ec-9121-4a38-908a-1ce0bbee86f6",
  "name": "ALProject8",
  "publisher": "ABC",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "features": [
    "TranslationFile"
  ],
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  },
  "runtime": "2.3",
  "showMyCode": true
}

Thanks

**Comment by SUD-D365** [comment]
Referenced to #4733

**Comment by SUD-D365** [comment]
*4733

**Comment by SUD-D365** [comment]
#4733

**Comment by ivan9876** [comment]
How you fixed that with internal server error? I get the same error.

**Comment by Ajageavi** [comment]
i am getting similar error, any body found solution with Microsoft Cloud sandbox?

**Comment by SUD-D365** [comment]
Still getting this error , while downloading symbols.

**Comment by Ajageavi** [comment]
yes.still same error

**Comment by atoader** [comment]
Hi! We've been working on fixing this issue and a fix will ship with the next update. You can use the symbols from the Docker image corresponding to the update your cloud sandbox is running to get unblocked. For critical issues such as this one, please contact Customer Support, that is the fastest way to get unblocked.

**Comment by SUD-D365** [comment]
Hi @atoader
Thanks for your prompt revert.
But there is different scenario, I have defined dependency in my extension , that can only be downloaded from cloud sandbox.

Kindly suggest.

**Comment by atoader** [comment]
I think that only the download of the application symbols is failing.
You can work around this by:
1. Removing `"application": "13.0.0.0"` from your app.json, 
2. Downloading the symbols. This will download the symbols for your extension.
3. Adding the Application symbols to your .alpackages folder manually by getting them from a Docker imag.
4. Adding back "application": "13.0.0.0" to the app.json

**Comment by SUD-D365** [comment]
Still not working :(

**Comment by SUD-D365** [comment]
Hello sir, 
Any update on this.
I need to fix something in one of our extension, before upgrade to next major release.

**Comment by arifai1979** [comment]
I'm facing same error, while downloading symbols 
I'm using trial tenant cloud sandbox,

**Comment by arifai1979** [comment]
I have latest VS code and AL extension, did any one find a solution?!!!!!!!

**Comment by SUD-D365** [comment]
Hi @atoader ,

Is there any update on this?

Kindest regards

**Comment by atoader** [comment]
I apologize for the delay in responding to this issue. In preparation for the Fall release and the full switch to AL, we have been working very hard on fixing issues in the core compiler. @SUD-D365 are you still experiencing problems? 
For any other issues concerning production systems, please open a support ticket as they will allow us to fix the issues you are encountering faster.

**Comment by SUD-D365** [comment]
Good luck for your hard work!!
I am not facing this issue anymore.

Thanks
