### ISSUE TITLE
Problem downloading Symbols

### ISSUE THREAD

**Issue by ftornero9** [Microsoft/AL#4736]
I am getting this error when I trying to download the symbols form my SandBox

![image](https://user-images.githubusercontent.com/12720964/54522989-c44b2500-496e-11e9-83d8-4755dbf99cda.png)

I can access to the same Sandbox without any problem

![image](https://user-images.githubusercontent.com/12720964/54523224-48051180-496f-11e9-9658-c8962a031363.png)

It is the first time that that happens.

In the other hand with the new version my extension has disappeared, It's for that that I am trying to download the new symbols to publish the extension again.

![image](https://user-images.githubusercontent.com/12720964/54523468-e5604580-496f-11e9-8717-8f8b9e346eb5.png)

Regards

**Comment by thpeder** [comment]
Please contact Support to get immediate help with your issue.
This is not related to the development environment.
