### ISSUE TITLE
app.json Download Symbols for Specific/Latest Version

### ISSUE THREAD

**Issue by SteveyN** [microsoft/AL#4737]
We have developed an extension, but placed contingency to make improvements to the extension when requested Event's are shipped in future updates of Business Central.

At the moment, we are not notified when our customer's Business Central (in the cloud) is updated to the latest version by Microsoft, and therefore we don't know if our event request was shipped in that particular update.

At the moment, in the app.json, for "platform" and "application", specifying anything other than "13.0.0.0" prevents downloading symbols.

**How can we verify that the symbols we're developing against contains the very latest version of the application objects?** 

**How can we find out what symbol packages are available for our tenant?**

The [Microsoft Docs page](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files) says these properties are to specify the _minimum supported version_ for our app; if the app relies on an event that was added in a later update, **why am I unable to specify a specific version for downloading symbols that isn't 13.0.0.0?** 

I have tried with the following versions: 13.4.28874.0, and 13.3.27908.29304, in various combinations.

Additionally, the way the version is specified in Business Central's "System Information" table is _unhelpful_ because it does not show the version format.
![image](https://user-images.githubusercontent.com/10519634/54528063-b51aa600-4973-11e9-9b35-1f1b4c62ae26.png)
13.3.0.29060? 13.3.29060.0? Something else?

**Comment by atoader** [comment]
Hi @SteveyN ! It should be sufficient to specify the minimum major and minor numbers and leave the rest 0 e.g. 13.3.0.0 . We do not ship new events in as hotfixes, so specifying the build/revision numbers should not be necessary.

**Comment by qutreson** [comment]
You can also see from the extension management page which is the latest version of the Base Application installed on your tenant. Closing this issue based on the answer provided in the previous comment.
