### ISSUE TITLE
How I can Filter Archive Pages?

### ISSUE THREAD

**Issue by BSSIRajbir** [Microsoft/AL#4738]
I am using On Open Page Trigger Event And trying to Filter the Page.
But Page Shows All the lines. Does anyone have a suggestion on it?

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
