### ISSUE TITLE
Which version of AL has fix for Issue 2454 "Query - DataItemTableFilter does not work with extension fields"

### ISSUE THREAD

**Issue by BhaskarJani** [Microsoft/AL#4740]
**Describe the bug**

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by thpeder** [comment]
Please remember to include the version of the runtime and the VSCode extension.
The issue has been fixed since August 2018

**Comment by BhaskarJani** [comment]
Hi thpedar,

Sorry about that.

Here are details 

VSCode runtime 1.32.3

AL Code Extension 0.12.28462

Target NAV Platform: Dynamic NAV2018, Build 22292.

Can you please clarify if any of the above needs updating ?

Regards - Bhaskar
