### ISSUE TITLE
Not able to view field of Record Variable

### ISSUE THREAD

**Issue by ashik-ivor** [microsoft/AL#4741]
In compiler "AL 2.1.91153", we were able to view the fields of the record when we keep the cursor over the variable.

![image](https://user-images.githubusercontent.com/38459860/54601972-67cb3100-4a66-11e9-9dfe-f27aac4ce876.png)

But in compiler "AL 2.1.109895", we are unable to view the fields of the record.
![image](https://user-images.githubusercontent.com/38459860/54602072-9cd78380-4a66-11e9-8856-85deb7e682af.png)

**Comment by atoader** [comment]
@ashik-ivor please use the latest VSIX available in the marketplace. It is compatible with all versions of Business Central and it will receive any bug fixes we make to intellisense, tooltips, and codelens.
