### ISSUE TITLE
Visibility on Role Center Extended Pages ?

### ISSUE THREAD

**Issue by jigneshdhandhanav** [microsoft/AL#4742]
Hello All,

I have added one part section in Order Processor Role Center Page. I would like to show that part based on User Setup. If "Show on Role Center" = Yes then system will show part section in Role Center Page otherwise system will hide that section.

Can we do that in Extension for Business Central

Thanks,
Jignesh Dhandha

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
