### ISSUE TITLE
Expression expected on TableRelation property in AL

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/AL#4744]
In AL we are not able to set expresion on TableRelation property like on C/AL

![1](https://user-images.githubusercontent.com/31925856/54607658-32671900-4a4f-11e9-99ba-810959fdbb02.png)

Any idea how it should be done now?

**Comment by ftornero9** [comment]
The error is that an "Expression expected",

Try to use 
`FILTER(='*AC*')`

Regards

**Comment by tomasevicstefan** [comment]
It doesn't allow me to use '=', but we can compile object with '*AC*'
