### ISSUE TITLE
Including install data with extension?

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#4746]
**Is your feature request related to a problem? Please describe.**
We were looking into the option to use Export-NAVAppTableData to generate a navxdata file to include install data with our extension. However, the commandlet seems limited to company-wide (DataPerCompany = No) tables only. (#2335)

**Describe the solution you'd like**
Just like adding permissions on installing the app (via the PermissionSets.xml), what is the best option to include standard data 'per company' with the app? Should we include data via navxdata files? Should we include data using files created via RapidStart (on how to refer those upon installing the app)? Should we 'code' the creation of data (like codeunit 2 'Company Initialize' / Workflow Initialization, ...)

**Comment by fvet** [comment]
Additionally, data can refer to 'files' / BLOB as well. We're considering to include PDF files (official templates / certificates) as part of the demo data as well. Instead of converting the content to base64 and import via RapidStart / codeunits, including them as part of the extension could be an option too. 

An alternative is to make the content publically available and import trhough an API call.

**Comment by stefanoPrimo** [comment]
Hi, we're looking for this feature too, are there any updates?

**Comment by atoader** [comment]
We have discussed this recently, but we have decided to postpone this until we get more feedback from partners. There are multiple ways of achieving this, as @fvet has mentioned, but we would like to improve the story.
Could you please post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will help us prioritize this feature for a future release.

**Comment by larswestman** [comment]
The ugly workaround for this is to create separate tables for your setup data that are not company specific. When you package your app you copy data from the real tables to these "setup data tables" and from there export them using Export-NAVAppTableData. 

When you install/upgrade the app you import the data using NavApp.LoadPackageData and after that you can copy the data to the real tables in the companies where you need the data. It's indead a workaround since we do not have any other working mechanism for shipping data along with the app.

**Comment by fvet** [comment]
We've opted to put our data on Azure storage (blobs, rapidstarts, ...) and fetch it when needed (using Assisted Setup, based on the page context, ...). It leaves some freedom for the consultant in charge of the install data to add / translate settings in the rapidstart and deliver them through Azure instead of us having to release an updated version of the app.
