### ISSUE TITLE
Get-NAVAppRuntimePackage : No published package matches the provided arguments.

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/AL#4747]
**Describe the bug**
The Get-NAVAppRuntimePackage doesn't seem to be working.

Get-NAVAppRuntimePackage -Id 9acfa8a0-7159-4791-a575-884a741a2384 -Name 'STST_Core_Tables' -Publisher 'ESC bvba' -Version 1.0.0.0 -Path 'C:\temp\Prosware SmartApp_2.3.4.500_runtime.app' -ServerInstance BC130

**To Reproduce**
Just create an extension in BC CU2 I guess.
get-navappinfo gives the following:
![image](https://user-images.githubusercontent.com/24684493/54642879-ee4b3700-4a95-11e9-9849-6357e6d57a15.png)

**Expected behavior**
A runtime app should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/24684493/54642933-0de25f80-4a96-11e9-8834-4c602d6b0e3e.png)

**Versions:**

 - AL Language: 2.1.109895

 - Business Central: BE Dynamics NAV 13.2 (26556)

**Comment by davmac1** [comment]
I have the same problem. What makes it strange, is it worked the first time. Then I updated the package and re-published it. Now it cannot make the runtime - same error.
This is for Business Central on premise 13.3 (27183) AL 2.1.79379 installed from CU3 visix

**Comment by davmac1** [comment]
I found my answer - had published from VS Code. I unpublished it, then republished it with skip verification. Now it created the runtime package.
Is there an option in the app.json file or the launch.json to skipverification?

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project and steps to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by Srbaxter52** [comment]
I am trying to make a runtime package for the Business Central OnPrem.  My app publishes fine from VS Code.  I can see it when I open the client and when I run get-navappinfo from PowerShell.  But when I run the Get-NAVAppRuntimePackage script it fails and gives me the same thing they were seeing.
![Get-NavAppInfo](https://user-images.githubusercontent.com/41059145/68807478-dc765f80-0635-11ea-839c-0c2b5da36f7c.GIF)

![Get-runtimepackage](https://user-images.githubusercontent.com/41059145/68807488-e0a27d00-0635-11ea-8b92-da32e072df84.GIF)

I am using the onprem:13.5.29483.0-na image.  I have not attempted to move this to Wave 2 2019 release as I am trying to do an update for a client.

**Comment by atoader** [comment]
Hi @Srbaxter52 , extensions published from VSCode are published in the tenant scope. You need to specify the tenant ID: See https://github.com/microsoft/AL/issues/5286

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
