### ISSUE TITLE
DataCaptionExpresion property on Page

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#4749]
Does anyone know how this property should be formatted to fix compilation error? This worked in C/AL.

![1](https://user-images.githubusercontent.com/31925856/54672054-87f70080-4af7-11e9-9ed8-9066c87a188f.png)

**Comment by thpeder** [comment]
Have you created a procedure with the name TableCaption, since it is also system method.

Please provide a full page that reproduces the issue.

**Comment by tomasevicstefan** [comment]
No, we got this in AL while converting functionality from C/AL to AL. We regularly use it on pages in C/AL.

![1](https://user-images.githubusercontent.com/31925856/54815099-777a8d80-4c91-11e9-9ac3-e721035b94bb.png)
