### ISSUE TITLE
Control Addins in V2 extensions

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#475]
How am I able to create and include JS control addins in my V2 extension?

**Comment by Gallimathias** [comment]
I think you will get a very similar answer to JS as in Issue #276 . That is, JS in on premise ok, but not in the cloud.

Alternatively, you can use Azure Functions, or other HTTP APIs, for example, from your own webservice.

In the case of cloud solutions, however, you probably have to pay attention to the EU data protection guidelines, just as I do ;).

**Comment by RasmusTidselbak** [comment]
What I'm looking for is the gui control addins we create with js. For example to include Bing Maps to the client, as in the Microsoft example.
I can imagine the resource file being the same, but I will not be able to include an interface in the addins folder.

**Comment by Gallimathias** [comment]
Ok then look times here in #146 , Kalbers has said a response to GUI JS Addins something. Relatively at the end.

> We do not yet support JavaScript client control add-ins. It is in our plans though, but we do not have >an exact date for when it is going to be delivered.
>
>Thanks
>Kalman

**Comment by StanislawStempin** [comment]
We are starting the work on JS control add-ins and they should be available within the next 2-3 updates.

**Comment by MikeGlue** [comment]
Does this mean that built-in addins such as the 'Microsoft.Dynamics.Nav.Client.WebPageViewer' will also be available to use in the next 2-3 updates?

**Comment by StanislawStempin** [comment]
We will work on them after completing the generic control add-in support so they will be ready soon after.
