### ISSUE TITLE
AL Extension for BC Spring Release (version 14) not in VSC marketplace

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#4750]
We are trying to create an App against the upcoming BC Spring Release.
We have downloaded to our Docker and have the App ready, but when we try to create and publish the App we get the following:

![image](https://user-images.githubusercontent.com/40754213/54673790-4d8f6280-4afb-11e9-88f8-6c1dbec4a951.png)

When we go to SVC marketplace the only available version is the one we already have installed.

**Versions:**
 - AL Langauge:   2.1.109895.
 - Business Central: 14.0.28496.0

**Comment by naveksa** [comment]
Typing mistake. Not SVC but VSC (of course)

**Comment by ftornero9** [comment]
Hello @naveksa ,

From the docker container you can get the right AL Language version, your container will have other name but that it is an example:

![image](https://user-images.githubusercontent.com/12720964/54686389-77f01880-4b19-11e9-8878-c8d5f470d82e.png)

![image](https://user-images.githubusercontent.com/12720964/54686516-cb626680-4b19-11e9-8984-5fa5f76c201e.png)

Regards

**Comment by naveksa** [comment]
Thanks. Found it.
However installing it gives other errors.
Opened a new issue #4758
