### ISSUE TITLE
Can't download symbols after update. Internal Server Error.

### ISSUE THREAD

**Issue by ivan9876** [Microsoft/AL#4752]
Hi Guys.

I was not able to publish an extension because of RunTime 2.4. 
[2019-03-18 08:19:32.70] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details

Runtime: 2.4
Web API: 2.0
Debugger: 2.0
AL extension details

Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3
Supported Web API: 1.0, 2.0
Supported debuggers: 1.0, 2.0

Yesterday the new  AL extension become available so I installed the new AL Extension version I added the credentials and now I get a new error. I am not able to install symbols.

The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-03-20 10:06:43.12] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
Microsoft (R) AL Compiler version 2.1.1.44361
Copyright (C) Microsoft Corporation. All rights reserved

Do you know what can be the cause of this?
Thanks

**Comment by qutreson** [comment]
Hi @ivan9876, this issue was also reported under #4733. It should be fixed by now if you download the latest AL extension from the market place

**Comment by ivan9876** [comment]
Hi @qutreson , even after downloading the latest AL extension i get this error. 

The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-03-20 10:06:43.12] Could not download reference symbols. Please ensure that:

The correct server name and instance are specified in the launch.json file.
The correct application version is specified in the app.json file.
Microsoft (R) AL Compiler version 2.1.1.44361
Copyright (C) Microsoft Corporation. All rights reserved
