### ISSUE TITLE
MinValue MaxValue extensible

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/AL#4754]
Is there any plans to extend minValue and maxValue properties on tables?

**Comment by thpeder** [comment]
We kindly to ask you to post your enhancements to [Microsoft Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) if it is not already there.
