### ISSUE TITLE
License problem when creating new Temporary Table in Extension

### ISSUE THREAD

**Issue by jbakach** [Microsoft/AL#4756]
**Describe the bug**
I have created a new extension, and in this one I've created various tables using "Temporary" IDs. I mean, that are out of Customer's license. In older versions there was the possibility to create tables for temporary purpose.

Thank you so much!!

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
When I publish the extension using the ID 62000 (out of customer's licence), It gives me the error:
The request for path /XXX/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Your program license does not allow you to publish 'TABLEID_62000'.

**Expected behavior**
There must be a way to create temporary tables out of license without consuming customer's licence. It should do this check when you try to write physically (in SQL) to this table, as it was doing on previous NAV versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/3531482/54687841-d8cd2000-4b1c-11e9-83d8-de1052418e91.png)

**Versions:**

 - AL Langauge: Versión: 2.1.109895

 - Business Central: 13.0.27183

**Comment by ftornero9** [comment]
Hello @jbakach,

Have you tried to create the table with your developper licence and then used it as temporary with the client licence ?

Regards.

**Comment by jbakach** [comment]
Hi @ftornero9 thanks for your answer.

When publishing the extension to the customer's database, I had to change the license to our developer one, restart service, publish extension, upload again customer's license and then he had the chance to run the extension succesfully.

I think we have to search a better way of doing this, because it's a common practice to use "Buffer tables". And if this is the only way to publish an app containing this kind of tables, it's kinda awkward.

Thanks again

**Comment by ftornero9** [comment]
Hello @jbakach,

I agree with you, anyway you could create the table or tables with your license in the Developper Environment and later use as temporary in the extension, so is the old way of doing it, because with the user license you can not create tables outside its range.

Regards

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by jbakach** [comment]
This issue has to be reviewed, because every time we change an extension including tables as temporary range and out of customer's license, we have to change the license to our developer one and restart service and put another time the customer's license.

Please take a look at this as it's very annoying this kind of work.

Thanks so much,

Best Regards 

jbakach

**Comment by atoader** [comment]
@jbakach please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will increase the chance that it will be considered for one of our future releases.
