### ISSUE TITLE
Error / Problem with AL version 3

### ISSUE THREAD

**Issue by naveksa** [Microsoft/AL#4758]
We have pulled a new docker environment for the Spring Release from
bcinsider.azurecr.io/bcsandbox-master

We have installed the supplied 
al-3.0.107312.vsix
in VSC extensions.

We have run a download symbols from the new docker giving us
Microsoft_Application_14.0.28630.0.app
and
Microsoft_System_14.0.28496.0.app

We have disabled the previous al-extension
2.1.109895.

Now we try to compile and publish our extension and get the following error:

(1,1): error AL0999: Internal error: The type initializer for 'Microsoft.Dynamics.Nav.CodeAnalysis.TriggerDefinitions' threw an exception.

1 error for each of our files.

**Comment by naveksa** [comment]
Correction:
The Microsoft.app versions are as follows:
Microsoft_Application_14.0.29399.0.app
Microsoft_System_14.0.29248.0.app

**Comment by pmohanakrishna** [comment]
Is your .Net Framework updated to 4.7?

**Comment by naveksa** [comment]
Nothing is done locally.
Our Docker-environments are all on Azure.

**Comment by pmohanakrishna** [comment]
I was facing same issue and it got resolved after installing .Net framework 4.7
#4570

**Comment by naveksa** [comment]
Brilliant :-)
Thanks.
Problem solved.

Just wondering why the Azure servers are not being updated automatically with critical components like this and why the compiler extension does not give a more "user-friendly" error message telling that this is the actual problem.
Well, never mind, things works now, and another note on the long lists of things to check in future updates.
