### ISSUE TITLE
Global Variable Issues in Page

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#476]
Hi,
Issue 1: This seems bug. I moved global variable gtPermission to Local variable ltPermission but still throws below error.

![image](https://user-images.githubusercontent.com/30457269/29055667-e73101b8-7c27-11e7-95d8-fac42e5d6279.png)

Issue 2: I Moved Global Text Constant Text0001 to Local but still AL throws below error.
![image](https://user-images.githubusercontent.com/30457269/29055684-0ea1e4ce-7c28-11e7-96cd-764729e29252.png)

Similar to above there are many variables am getting error of inaccessibility due to protection level.

Any Solution?

**Comment by sanjeevasawale** [comment]
Solved the issue after i close the Folder and restarted Visual Studio Code. Surprised.

**Comment by doivosev** [comment]
If you are interested into recreating a smaller version of this bug we could investigate this further. Does it always repro when you move a variable from global to local in this specific case?

**Comment by svwfr** [comment]
I do have similar issue (inaccessible) with pageextension where I add an action that will change a global variable as Item given in PAG5530.
![image](https://user-images.githubusercontent.com/34069541/37478700-3fa55970-287b-11e8-82a6-069354bbc478.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @svwfr . Please open a new issue as this one is very old and closed
