### ISSUE TITLE
Cannot download Test App Symbols (Docker container environment)

### ISSUE THREAD

**Issue by bhlDeex** [microsoft/AL#4761]
Hello,

I am trying to create Automated Testing App for Dynamics 365 Business Central. I installed the VSIX AL extension that was given after creating the container. I installed same extension for both Test App and the ExtensionApp. I published the ExtensionApp to the docker container and when I try to download symbols from the Testing App app.json, it keeps on saying:

**[2019-03-21 10:50:46.32] The request for path /nav/dev/packages?publisher=Microsoft&appName=Test&versionText=13.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-03-21 10:50:53.77] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.**

Here is my Test App app.json:

```
{
  "id": "",
  "name": "KR AddFinder Test",
  "publisher": "DEEX Korea Co Ltd",
  "brief": "KR Address Finder Test",
  "description": "Testing KR Address Finder",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "screenshots": [],
  "test" : "13.0.0.0",
  "dependencies": [
    {
    "appId": "",
    "name": "Korean Address Finder",
    "publisher": "DEEX Korea Co Ltd",
    "version": "1.0.0.0"
    }
  ],
  "platform": "12.0.0.0",
  "application": "12.0.0.0",
  "idRange": {
    "from": 50000,
    "to": 50100
  }
  
}
```

And this is my TestApp launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "peter",
            "server": "http://peter",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 130401,
        }
    ]
}
```

Here is my ExtensionApp app.json:

```
{
  "id": "",
  "name": "Korean Address Finder",
  "publisher": "DEEX Korea Co Ltd",
  "brief": "Finds the Korean road address according to the keyword that the user inputs",
  "description": "Finds the Korean road address according to the keyword that the user inputs",
  "version": "1.0.0.0",
  "privacyStatement": ",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "Img\\Korean_Address_Finder_216_216.png",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "runtime": "2.4",
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": {
    "from": 70273075,
    "to": 70273124
  },
  "features": [
    "TranslationFile"
  ]
}
```

And this is my ExtensionApp launch.json:
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "peter",
            "type": "al",
            "request": "launch",
            "server": "http://peter",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 21,
            "schemaUpdateMode": "Recreate"
        }
    ]
        
}
```

I would appreciate any comments or suggestions. Please give me any help. I really do need some help.

Thank you.

**Comment by atoader** [comment]
@bhlDeex have you published the Test symbols to the container before trying to download them? What does calling [Get-NavAppInfo](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps) return? What does calling Get-NavAppInfo -SymbolsOnly return?

**Comment by qutreson** [comment]
Hi @bhlDeex, are you still experiencing this issue? It seems that your container does not contain the Test symbols required to publish the extension `KR AddFinder Test`. Did you trying running Get-NavAppInfo -SymbolsOnly to verify whether they are published on your server or not?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
