### ISSUE TITLE
Authorization httpClient get fail

### ISSUE THREAD

**Issue by RCORELLA** [Microsoft/AL#4762]
Hi,

I try to connect with a dynamics CRM online from BC.  With Postman I use the OAuth 2.0 to grant the authorization, but in AL I can't use it.

How can I obtain a token in AL? or can I use NTLM authorization to connect from BC to CRM (online)?  Can I use NTLM in AL?

Thanks

Roberto

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
