### ISSUE TITLE
Modifications to property ApplicationArea are not supported.

### ISSUE THREAD

**Issue by michaelsimonsendk** [Microsoft/AL#4766]
**Error in 'PageExtension'**
The error was: InvalidOperationException - Metadata delta application failed due to the following error(s): Modifications to property ApplicationArea are not supported.

**To Reproduce**
AL code to reproduce the behavior:

```
pageextension 50000 "PageExt Budget" extends "Budget"

{
    layout
    {
        modify(MatrixForm) { ApplicationArea = All; }
    }

    actions
    {
    }
}
```

**Expected behavior**
modify app. area is working on controls of type field - why is that not working on controls of type part?

**Versions:**
 - AL Langauge: 2.1.109895
 - Business Central: DK Dynamics NAV 13.3 (27233)

**Comment by JohanStenberg100** [comment]
This is by design. We have also added an error annotation which will be shipped in an upcoming version of our VS Code extension. Thanks
