### ISSUE TITLE
The request for path ""apps?SchemaUpdateMode=recreate failed with code 422. Reason: Extension compilation failed

### ISSUE THREAD

**Issue by rajprince0** [Microsoft/AL#4769]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by thpeder** [comment]
Please follow the template and provide adequate information to reproduce the issue.
