### ISSUE TITLE
CURREPORT.PAGENO

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#477]
Hi

CURREPORT.PAGENO  method is not available while report development . Any specific reason or restriction?

Amol

**Comment by srenders** [comment]
Why would you need that? CurrReport.PAGENO was only used with the Classic Client, in RDLC it has no use.

**Comment by esbenk** [comment]
The runtime implementation in the current stack always returns 1.

**Comment by AmolSalvi** [comment]
Pleasw close this issue
