### ISSUE TITLE
A procedure can't return an array type

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#4770]
In C/Al it's possible to create (local) functions which returns an array as its return/exit value. With AL this seems not to be allowed anymore.

Version: 3.0.107312 (recent insider build: 14.0.29346.0-nl-ltsc2016)

**To Reproduce**
- Create new project (AL ==> GO)
- Open hello World and create following function:

```
local procedure MyProcedure() MyVar: array[10] of Text
    var
        myInt: Integer;
    begin
        Myvar[1] = 'blabla';        
    end;
```

**Expected**
This to compile succesfull.

**Result**
Following compile error

Compilation started for project 'ALProject8' containing '1' files at '10:50:34.350'.

c:\Users\r.koppelaar\Documents\AL\ALProject8\HelloWorld.al(12,42): error AL0105: Syntax error, identifier expected; 'array' is a keyword
c:\Users\r.koppelaar\Documents\AL\ALProject8\HelloWorld.al(12,42): error AL0104: Syntax error, '}' expected
c:\Users\r.koppelaar\Documents\AL\ALProject8\HelloWorld.al(12,42): error AL0198: Expected one of the application object keywords (table, tableextension, page, pageextension, pagecustomization, profile, codeunit, report, xmlport, query, controladdin, dotnet, enum, enumextension)

Compilation ended at '10:50:34.429'.

Error: The package could not be created.

**Comment by qutreson** [comment]
Hi @RonKoppelaar, we are currently not supporting procedures reporting an array. We are aware of this limitation and have added to our long term backlog, but we cannot provide information on when this will be implemented. In the meanwhile, we advise you to refactor your code to not return an array. You can achieve this for instance by returning it by var.

**Comment by RonKoppelaar** [comment]
Okay clear. We rewqrite our code bit to work around this
