### ISSUE TITLE
The data cannot be shown because it is not valid

### ISSUE THREAD

**Issue by jigneshdhandhanav** [Microsoft/AL#4771]
Hello Team,

In D365 Business Central, When we add Notes through Code system add the notes with Text - "The data cannot be shown because it is not valid"

Please see the attache Code.

Can anyone has idea about this ?

Thank you

![CustomerList](https://user-images.githubusercontent.com/46296969/54816924-9beb5f80-4cbb-11e9-84f3-1db69c03edc3.png)

**Comment by jigneshdhandhanav** [comment]
Hello Team,

Can anyone have idea about above issue ?

Thank you.

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by Theundevreede** [comment]
Had the same issue after an upgrade from NAV2017CU4 (local serverinstallation) to NAV2017CU18 (on Azure).
Seems to be occuring only if the note is 20 or 21 characters long.
