### ISSUE TITLE
Get User from Office 365 limited to 100 Users

### ISSUE THREAD

**Issue by giann85** [Microsoft/AL#4772]
Hi, in Business Central CU3, the function CreateNewUsersFromAzureAD, in codeunit 9010 "Azure AD User Management" has changed from previous version:    now, if select  action "Get user form Office 365" in user list page,     i get max 100 user,  because there's a   variable "MaxNoToRetrieve"  set to  100.  WHy??  if i've  more than 100 users in Office 365 that i want to set in Bcentral, what's the way?? there's a a reason for this limitation?

thanks

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
