### ISSUE TITLE
Problem with field "Name" in Table "Item Journal Batch"

### ISSUE THREAD

**Issue by JuditNavarro** [Microsoft/AL#4773]
Hello!

We think that we just found a bug while we were developing code in our migration project. 
We created a page extension that extends of "Phys. Inventory Journal", and when we add an action, in its trigger OnAction we put some setranges before showing a report:

![image](https://user-images.githubusercontent.com/44970454/54817875-d9d28e80-4c8f-11e9-8333-63c89e26c190.png)

The problem is that, if we add the line that do a setrange of the field "Name" (ItemJournalBatch2.SetRange(Name, "Journal Batch Name")), the page extension gives an error, and in the app.json too:

![1](https://user-images.githubusercontent.com/44970454/54818228-ab08e800-4c90-11e9-8286-97a0d6087820.png)

I add the error of the page extension in the next txt: 
[ErrorInPageExtension.txt](https://github.com/Microsoft/AL/files/2996137/ErrorInPageExtension.txt)

If we comment the line that use the field "Name", those two errors disappear
![image](https://user-images.githubusercontent.com/44970454/54818534-66318100-4c91-11e9-94e6-2594ccfa369d.png)

It doesn't make sense for us, because that field exists in the table, so we think that it's a bug.
We tried it with app.json target = "Internal" case and target = "Extension" case, and it shows the same error message.

**Versions:**
 - AL Language: 2.1.109895

**Comment by tinfister** [comment]
Create function in TableExtension for Item Journal Batch where you filter what you need and call that function instead of filtering in action.
Something like


ItemJournalBatch2.FilterMyRecord(ItemJournalBatch2,Template_Name,Batch_Name);
PhysInventoryList2.SetTableView(ItemJournalBatch2);
...
...


procedure FilterMyRecord( var ItemJournalBatch: Record "Item Journal Batch", Template : Code[20], Batch: Code[20])
begin
ItemJournalBatch.setrange("Journal Template Name", Template);
ItemJournalBatch.setrange("Journal Batch Name", Batch);
end;

**Comment by JuditNavarro** [comment]
Hi again, 

We tried what you tell us, but this idea didn't work too, but thanks for your help, @tinfister

**Comment by tinfister** [comment]
> Hi again,
> 
> We tried what you tell us, but this idea didn't work too, but thanks for your help, @tinfister

Can you post your code?

**Comment by JuditNavarro** [comment]
> > Hi again,
> > We tried what you tell us, but this idea didn't work too, but thanks for your help, @tinfister
> 
> Can you post your code?

Here it is, you just need to change the extension to .al:
[Pag-Ext7074312.PhysInventoryJournalHtl.txt](https://github.com/Microsoft/AL/files/3003277/Pag-Ext7074312.PhysInventoryJournalHtl.txt)

**Comment by tinfister** [comment]
See this

[Pag-Ext7074312.PhysInventoryJournalHtl.txt](https://github.com/Microsoft/AL/files/3003320/Pag-Ext7074312.PhysInventoryJournalHtl.txt)
[TabExt233-Ext70000.EXT_ItemJournalBatch.txt](https://github.com/Microsoft/AL/files/3003321/TabExt233-Ext70000.EXT_ItemJournalBatch.txt)

**Comment by JuditNavarro** [comment]
> See this
> 
> [Pag-Ext7074312.PhysInventoryJournalHtl.txt](https://github.com/Microsoft/AL/files/3003320/Pag-Ext7074312.PhysInventoryJournalHtl.txt)
> [TabExt233-Ext70000.EXT_ItemJournalBatch.txt](https://github.com/Microsoft/AL/files/3003321/TabExt233-Ext70000.EXT_ItemJournalBatch.txt)

ok, thank you, like this it works :) 
But I don't really understand why is It not possible to use the filter in the page instead

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
