### ISSUE TITLE
Publishing app retrieved by Get-NavAppRuntimePackage does not work

### ISSUE THREAD

**Issue by robertsedeljsak** [Microsoft/AL#4774]
**Describe the bug**
My settings:
Local On-premise BC installation, CU 3 without multi-tenancy.

I am publishing and installing app trough PowerShell. (App is built trough VS Code).

Problem is when using Get-NavAppRuntimePackage command (the second time) and then using generated app file for further Re-Publish and Re-Install. Publish and install does work ok, but objects are not there. 

The app is can be found under extensions management as published and installed.

It seems that first Get-NavAppRuntimePackage download objects (from .al to binary). 
Publishing binary app works ok, but running Get-NavAppRuntimePackage against published binary app cannot be performed. 

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Generate new AL project in VS code.
2. Set app property to showmycode = true.
3. Create new page.
4. Build app.
5. Copy app file to another folder.
6. Open powershell as administrator and load module.
7. Run script steps by step and check app in BC between:
        # Step 1 >>
        $nst = 'BC130'
        $App = 'PublisherTest'
        $path1 = 'C:\temp\AL\Default publisher_PublisherTest_1.0.0.0.app' #built app file from VS Code
        $path2 = 'C:\temp\AL\mytest.app' #downloaded app file 1
        $path3 = 'C:\temp\AL\mytest1.app' #downloaded app file 2
        
        Publish-NAVApp -ServerInstance $nst -Path $path1 -SkipVerification
        Install-NAVApp -ServerInstance $nst -Name $app
        #app work OK
        # Step 1 <<
        
        # Step 2 >>
        Get-NavAppRuntimePackage -ServerInstance $NST -Name $App -Path $path2 
        Uninstall-NAVApp -ServerInstance $nst -Name $App
        Unpublish-NAVApp -ServerInstance $nst -Name $App
        Publish-NAVApp -ServerInstance $nst -Path $path2 -SkipVerification
        Install-NAVApp -ServerInstance $nst -Name $app
        #app work OK
        # Step 2 <<<
        
        # Step 3 >>
        Get-NavAppRuntimePackage -ServerInstance $NST -Name $App -Path $path3
        Uninstall-NAVApp -ServerInstance $nst -Name $App
        Unpublish-NAVApp -ServerInstance $nst -Name $App
        Publish-NAVApp -ServerInstance $nst -Path $path3 -SkipVerification
        Install-NAVApp -ServerInstance $nst -Name $app
        #app is not seen
        # Step 3 <<

8. After step 3 app does not work anymore.
9. Furthermore, if I check my app file and unzip it, every version looks different. 

**Expected behavior**
I expect that Get-NavAppRuntimePackage against published binary app, would again return binary app as it does from published .al app.

I would like to use Get-NavAppRuntimePackage for unpublishing and republishing child app which has a dependency on my changed Parent app without building it again in VS Code.

**Screenshots**
![image](https://user-images.githubusercontent.com/41987840/54825136-1b256700-4cad-11e9-823a-b3355d7bb6b6.png)

![image](https://user-images.githubusercontent.com/41987840/54825073-f8934e00-4cac-11e9-8c35-20dca16724d1.png)

**Comment by thpeder** [comment]
Hi @robertsedeljsak,
That is not a support way of using Runtime Packages, since the package is made to be published to a customers server without the need to run the compiler on their server and check against the license since that was done when you produced the runtime package.
I will recommend you to store your al source code under version control and don't use the server as a ad-hoc version control system.
