### ISSUE TITLE
Debugging on macOS: StatusCode: 500, ReasonPhrase: 'Internal Server Error'

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#4777]
**Describe the bug**
When I try to Debug on macOS I get the error message in VS Code:

```
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  ms-correlation-x: 7707ff4b-ef9c-400e-9b5b-9b92ed5945ae
  Set-Cookie: RuntimeTenantAffinity=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
  Set-Cookie: RuntimeTenantAffinity=msweua1602t99384527; path=/; secure; httponly
  Date: Sat, 23 Mar 2019 10:06:02 GMT
  Content-Length: 0
}
```

**To Reproduce**
Command **AL: Go!**, selecting **Microsoft Cloud Sandbox** and hit **F5** to Debug.

**Expected behavior**
Debugging should work like on Windows.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/9556549/54864771-27b4c880-4d5c-11e9-8367-7247dfdb21ca.png)

**Versions:**
 - VS Code: Version 1.32.3 (1.32.3)
 - AL Langauge: 2.1.109895
 - Business Central: DE Dynamics NAV 13.4 (29469)

**Comment by JohanMelin** [comment]
I have the same problem too.

VS Code: Version 1.33.0
AL Langauge: 3.0.115791
Business Central: (SaaS Sandbox) SE Dynamics NAV 13.5 (31011)

**Comment by ClausJonathansen** [comment]
I have a similar problem on PC with Windows 7
:
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  ms-correlation-x: 43a001d8-15a4-4fe0-a6a3-e6fc7d5d2dc6
  Date: Thu, 04 Jul 2019 18:53:29 GMT
  Set-Cookie: RuntimeTenantAffinity=msneua5672t63739757; path=/
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 0
}

Versions:

VS Code: Version 1.36.0
AL Langauge: 3.0.145991
Business Central: (SaaS Sandbox) DK Dynamics NAV 
Application version: 14.1.33107.0
Platform version 14.2

**Comment by atoader** [comment]
Can you still reproduce this issue? Does the event log contain any additional information?

**Comment by DanielGoehler** [comment]
Hi @atoader, with 15.0.35406.0 it works now.
