### ISSUE TITLE
can we generate Symbol Reference and store the file in Blob field of our Addon Table

### ISSUE THREAD

**Issue by tejabalusu** [Microsoft/AL#4782]
While we are publishing Extension can we generate Symbol Reference and
store the file in Blob field of our Addon Table , Is it Possible?

For now we have generated symbol Reference externally and we are trying to upload the generated file using FILE.OPEN Method which is not supporting in Extensions, we have tried below link to #1825 to upload the file which is asking dialog box, is there any way to upload files without any dialog box.

thanks!

**Comment by atoader** [comment]
Hi! The scenario you mentioned is not supported.
