### ISSUE TITLE
Client Add-In in Factbox are not restored.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [microsoft/AL#4783]
Hi i don't know if this is the right place to report this issue, however i don't know where else to go. 

We are trying to get ready for the spring release both Cloud and Om-Prem. However we found an issue when using add-ins in the factbox area. The issue is in the web client. 

If you minimize the factbox area and restore it, the code for the add-in is not restored, and the content of the iframe is empty. So it's pretty obvious its a bug. 

It can be reproduced by adding the "Generic Chart" page as a factbox part to any page, and then open the page. Hide the factbox area and restore it, then the content of control add-in is wiped, only showing the standard control in the factbox page.

The issue have been reproduced both in 
14.0.29286.0 and 14.0.29532.0.

**Comment by Joriek** [comment]
Hello,

I also have the same issue. I have a javascript addin running in a factbox, it seems like the iframe doesn't render after you hide the factbox area. There are no page triggers called so there is no way to reinitialize the addin.
I've tested this in the webclient of the spring release.

Kind regards,
Joriek

**Comment by kwettermann** [comment]
Hi,

the same issue happens when you have a control add-in within a collapsible group.

When you collapse and restore a group with control add-ins, then the IFrame content stays empty. Events or scripts such as recreate or refresh are not triggered, which means that we cannot reinitialize our control add-in.
