### ISSUE TITLE
AppSourceCop Cannot read property kind of null

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#4784]
**Describe the bug**
Hi,
Although I had some errors that the AppSourceCop had to report (in my case it was missing the prefix in 2 fields in 2 different pages), it was so quiet, too much. 
So, due to an article that I read, I opened the settings.json and I removed all Code Analyzer except for the AppSourceCop. Then I restarted VSCode but with no success and with no returned errors 
I've searched for some logs and I found this in the Developer Tools of VSCode.
```
  ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (C:\Users\sprimo\.vscode\extensions\microsoft.al-3.0.107312\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (C:\Users\sprimo\.vscode\extensions\microsoft.al-3.0.107312\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
```
Hope it can help

**Versions:**

 - AL Langauge: 3.0.107312

 - Business Central: RTM W1 Localization

**Comment by stefanoPrimo** [comment]
Any updates?

**Comment by qutreson** [comment]
Hi @stefanoPrimo are you still experiencing this issue with the latest versions of the AL compiler and the AppSourceCop?

**Comment by stefanoPrimo** [comment]
Hi, no the issue seems fixed.
Thanks
