### ISSUE TITLE
Web client hangs when Creation of new lines (same table) happens in OnAfterInsert or OnAfterModify event

### ISSUE THREAD

**Issue by darench** [microsoft/AL#4785]
**Describe the bug**
In the latest insider preview: When triggering the creation of new lines in same table in OnAfterInsertEvent or OnAfterModifyEvent, the web client hangs. Nothing happening in the debugger but after a while the "Working on it" message is displayed and never goes away. After closing the web client and reopening, the page is displayed without issue and the data is correct. Tried to reproduce the error in the RTC client and I couldn't.

**To Reproduce**
Create a new table and page (my app has a card page with header and lines). Add the event subscriber for OnAfterInsertEvent onthe new table and in that table, trigger the creation of additional lines in the same table. Add DelayedInsert = true on the page.

**Expected behavior**
In previous version of Microsoft Dynamics Business Central and NAV, lines were created as expected and the page refreshed with the new data.

**Screenshots**
![image](https://user-images.githubusercontent.com/33038024/55014684-0a2c6c80-4fb1-11e9-91ac-c3b3cb59fe7a.png)

**Versions:**
 - AL Langauge: 3.0.106655
 - Business Central: Version: 14.0.29551.0-US

**Comment by freddydk** [comment]
There was a bug in 14.x WebClient (described here https://freddysblog.com/2019/04/25/bugfix-something-went-wrong/) which should be fixed in the latest navcontainerhelper or latest docker images.
Could you please retry and let us know if the problem persists?
Thanks

**Comment by darench** [comment]
Tried with latest version and still an issue.
NavContainerHelper is version 0.6.0.13
Version: 14.0.29537.31808-US
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6

**Comment by darench** [comment]
Tracked down what's causing the issue but I don't know why. Inside the "OnAfterGetCurrRecord" trigger, a Boolean is conditionally set that is also used in the StyleExpr. When this line is commented out, it works fine.

**Comment by nixpt82** [comment]
I tried with Spring CU1 and still got the message box behind the Dialog window.
