### ISSUE TITLE
VSCode - AL - Unable to download symbols

### ISSUE THREAD

**Issue by ciyav** [microsoft/AL#4787]
**Describe the bug**

I am not able to download symbols in vscode. One of the Business Central On Cloud account started giving error few days ago, but I was still able to download symbols with other Business Central accounts. 
But, since yesterday, I am not able to download the symbols using any of the account. Tried creating new demo account but did not work. 

Tried some combinations of version and runtime but did not work. 

**To Reproduce**
Command Palette -> AL: Download Symbol 

**Expected behavior**
To download the symbols successfully

**Screenshots**

![app](https://user-images.githubusercontent.com/46242083/55056675-ceff6b80-508c-11e9-8553-3713c39208a5.png)

![image](https://user-images.githubusercontent.com/46242083/55056712-e9394980-508c-11e9-9c2c-73c8658d091d.png)

![image](https://user-images.githubusercontent.com/46242083/55056725-f3f3de80-508c-11e9-88dd-f516817ac6aa.png)

**Versions:**

Vs Code: 1.32.3
AL Language: 2.1.87871

**Comment by ajdel1** [comment]
I am facing the same issue

![nav](https://user-images.githubusercontent.com/16917108/55070081-7e4b3b00-50ab-11e9-86e4-745836c6cf32.png)

**Comment by ciyav** [comment]
@StanislawStempin , Kindly guide us for the above issue

**Comment by ciyav** [comment]
@surajpatel038, any inputs?

**Comment by ciyav** [comment]
@kalberes, kindly guide us further

**Comment by Tonygithub17** [comment]
I am having same issue on run time 3.0.

![image](https://user-images.githubusercontent.com/34825577/55218951-84255580-523e-11e9-8338-19055b6f166d.png)

**Comment by kalberes** [comment]
@ciyav 

Have you tried without the tenant entry in the launch.json?

**Comment by ciyav** [comment]
@kalberes 

I tried without tenant entry but was unable to download symbols. It gave the same error.

**Comment by Tonygithub17** [comment]
@kalberes 

I just download latest version 14.0.29530. The download Symbol issue solved.

**Comment by ciyav** [comment]
@Tonygithub17 

I have the vscode with below version and am not able to download symbols in it. 

Visual Studio Code

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

And AL Language of version: 2.1.87871

**Comment by ajdel1** [comment]
Hi, I am still getting the same error. I am suing the cloud sandbox 

[2019-04-01 15:33:09.62] Using reference symbols cache path: c:\Users\akjai\Documents\AL\ALProject6\./.alpackages
[2019-04-01 15:33:09.66] Authenticating...
[2019-04-01 15:33:11.43] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-04-01 15:33:11.45] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-04-01 15:33:54.89] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-04-01 15:33:54.94] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

**Comment by ac2707** [comment]
Still getting the same error - 

[2019-04-02 11:22:37.12] Using reference symbols cache path: c:\Users\AartiChopra\Documents\AL\ALProject6\./.alpackages
[2019-04-02 11:22:37.12] Authenticating...
[2019-04-02 11:22:38.17] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-04-02 11:22:38.17] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-04-02 11:25:26.09] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-04-02 11:25:26.09] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

Please advise

@kalberes

I just download latest version 14.0.29530. The download Symbol issue solved. 
14.0.29530 - for ? can you please elaborate .. thanks

**Comment by ac2707** [comment]
This worked with the following settings -
permissions - 
You have granted the D365 EXTENSION MGT in the Cloud Sandbox environment (and not in the main environment)

Reset the Sandbox environment.

**Comment by umang11** [comment]
Same error after doing below
@ac2707
You have granted the D365 EXTENSION MGT in the Cloud Sandbox environment (and not in the main environment)

Reset the Sandbox environment.

**Comment by umang11** [comment]
ac2707

**Comment by ac2707** [comment]
Clear cache credentials and try again.

**Comment by umang11** [comment]
same issue

**Comment by ac2707** [comment]
You do not have permission to insert '' charts because the tenant is mounted with the application database as read-only. Contact your system administrator."
Can someone advice please what permissions to be updated for this ?

![image](https://user-images.githubusercontent.com/49182510/55719965-361e0800-5a1d-11e9-823b-c6b9497218dd.png)

**Comment by umang11** [comment]
is anyone got solution for this

**Comment by VikalpSharma** [comment]
I have tried all the suggestion and solution provided above. But getting the same error.  Is anyone get the idea how to rectify this issue.

**Comment by propagating** [comment]
This is still occuring for me as well, and it's occuring on trial versions, and on paid tenants. Extremely frustrating as it makes developing new extensions impossible if you don't already have the symbols downloaded.

**Comment by atoader** [comment]
Hi! In the last months we have been laser focused on getting the development tools ready for supporting large solutions on AL and we have fixed hundreds of bugs across the product. Unfortunately, this meant that we could not dedicate as much attention to the issues you have reported. 

In general, for issues concerning the online sandboxes, please we suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
