### ISSUE TITLE
Bug: On-Lookup of Table Fields not working in Web Client

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#4788]
**Describe the bug**
This issue is closely related to #4654.
Just any OnLookup-trigger of standard table-fields can't seem to be triggered from the web client.

**To Reproduce**
Open the Web Client and go to page "Customer Ledger Entries", try to click on field "Document No." nothing happens.

**Expected behavior**
As a reference, open the Windows client and try the same, this will open the page for the corresponding document.
I would expect the same to happen in the Web client, so that you can quickly navigate to related records.

**Versions:**
 - Business Central: W1 13.4 (28874) _or_ Platform 14.0.29248.0 + Application 29346 (W1 14.0)

**Comment by rvanbekkum** [comment]
In addition, I would like to point out the main issues:
* There are non-editable fields in standard BC with an OnLookup-trigger. These can never be triggered from the web client, so this code in standard BC is unreachable in the modern clients.
* I received a reply on Yammer on the subject.The suggested work-around for our _own_ fields is to add an OnDrillDown trigger on the _page_ fields. This however requires that we add an OnDrillDown implementation to ALL pages where the field is used. Wouldn't it be better to have something like an **OnDrillDown on table-level** so that we only have to provide the implementation for the field once and not on every page?

**Comment by atoader** [comment]
Hi! Thank you for reporting this issue. This is a missing feature from the Web Client and the team owning that component has added it to the backlog. When this gets fixed, the workaround will not be needed.

For issues that are not related to the development experience, such as this one, we suggest that you open a support case or file a bug in Collaborate. This will ensure that the issue gets to the appropriate team faster and that it gets resolved or prioritized accordingly.
