### ISSUE TITLE
Business Central Unable to download 

### ISSUE THREAD

**Issue by Sid12345678** [microsoft/AL#4789]
Unable to deploy reports in the cloud sandbox as I am unable to download symbols. It is getting logged in the web client but unable to download symbols. Please find the below screen shots.  

![issue](https://user-images.githubusercontent.com/48983048/55067294-76889800-50a5-11e9-8d61-b4dc39cc3cd0.jpg)

**Comment by ajdel1** [comment]
I am facing the same issue. 

Funny, I was able to download symbols on my Mac yesterday evening but no luck with Windows today.

**Comment by ajdel1** [comment]
![nav](https://user-images.githubusercontent.com/16917108/55070035-62e03000-50ab-11e9-8c6d-2a7ec992e3df.png)

**Comment by deano808** [comment]
> Unable to deploy reports in the cloud sandbox as I am unable to download symbols. It is getting logged in the web client but unable to download symbols. Please find the below screen shots.
> 
> ![issue](https://user-images.githubusercontent.com/48983048/55067294-76889800-50a5-11e9-8d61-b4dc39cc3cd0.jpg)

Hi Sid12345678
try updating your launch.json file
![image](https://user-images.githubusercontent.com/17627914/56360405-79763480-61dc-11e9-8b2b-6387cafd7a2f.png)

**Comment by atoader** [comment]
Hi! This issue has been fixed. For issues concerning the online sandbox experience, please open a support case and work with our customer support team to gather all the information necessary to fix this problem.
