### ISSUE TITLE
TEMPORARYPATH is not supported in Extension

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#479]
It seems TEMPORARYPATH is not supported in Extension. Is there any alternate.

![image](https://user-images.githubusercontent.com/30457269/29062764-386d3248-7c4d-11e7-8a43-41fbfe791887.png)

**Comment by esbenk** [comment]
No, but it wont be of much use since the use of files on the server is also not available for extensions.

**Comment by sanjeevasawale** [comment]
Ok..Thanks for the feedback.
