### ISSUE TITLE
Substitution for UploadFileSilent on web client

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/AL#4790]
Does it exist substitution for UploadFileSilent (not supported on web client) in AL. I tried with UploadIntoStream, but it opens dialog box to choose file, which I don't want.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
