### ISSUE TITLE
Publish error: failed with code 422. Reason: Requested value 'Blob' was not found.

### ISSUE THREAD

**Issue by crsc** [microsoft/AL#4791]
When i try to publish the project to my Business Central docker i get the message:

-Sending request to http://testbc3:7049/NAV/dev/apps?SchemaUpdateMode=recreate
-The request for path /NAV/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Requested value 'Blob' was not found.

![imagen](https://user-images.githubusercontent.com/3490446/55085272-4db0d480-509e-11e9-9ae8-11484ea09a1e.png)

I do not have any errors in the code, i also have installed the license in the docker that allows me to use my objects range.
I have Blob fields in a couple of tables but that type seems to be supported.

The image i used to create the docker is microsoft/bcsandbox:es-ltsc2019

**Comment by hvogelpohl** [comment]
I got this error when I added a XML Port to the project. There was no Blob field at all in my extension. Turned out to be a fieldelement in the XML Port that caused this behaviour.

**Comment by atoader** [comment]
@hvogelpohl I know it was a long time ago, but do you still have the code that caused the error?

**Comment by atoader** [comment]
@crsc were you able to work around this issue?

**Comment by hvogelpohl** [comment]
> @hvogelpohl I know it was a long time ago, but do you still have the code that caused the error?

Hi atoader,

yes, i still have the code. And I looked further into it and could break it down to the point where the Error occurs. In an nutshell: 

1 create an extension1 
2 insert a dependency to another extension2
3 create a XML port in extension1 and use fieldelement to move the data to a table in the dependency extension2

=> failed with code 422. Reason: 
Requested value 'Blob' was not found.

If you want I can create a demo vs code project and publish it on monday.

**Comment by atoader** [comment]
We would appreciate it greatly if you could publish the code that reproduces the issue. It would greatly increase the chances that we can fix this by the time we branch for the next major release.

**Comment by hvogelpohl** [comment]
@atoader  Okay, it's here:
https://github.com/hvogelpohl/BC_AL_Code422

The error occurs when published to a 13.* Version. When published to 14.* the sample AL code "works".

Compiling works for both 13 and 14. Publishing to 13 brings up Error 
=> failed with code 422. Reason:
Requested value 'Blob' was not found.

The error seems to be the validation of blobs from fieldelement in XML ports.

**Comment by atoader** [comment]
@hvogelpohl for versions of BC that are in mainstream support, you will have to open a request for hotfix through the usual channels. As we have a limited capacity to fix issues reported on GitHub, we will prioritize fixing the ones that are present in the latest preview builds and latest mainstream version.

**Comment by qutreson** [comment]
Hi @hvogelpohl, it seems that the link your provided in your last comment is now broken.. Can you please update it or provide us another repro of this issue? 
We had some bug fixes around XMLPorts in the last weeks, can you give it a try with the latest developer preview (version 15.x) and tell us if your issue is fixed there?

**Comment by hvogelpohl** [comment]
I fixed the link

**Comment by thpeder** [comment]
Thanks for reporting the issue,
We have had some fixes around xmlports in version 15 which might have resolved the issue since I just tried reproduce it both with the code from @hvogelpohl repository and by trying to split the code into two extensions but it worked just fine in both cases.

@hvogelpohl could you please test it on the latest developer preview and check if it is actually fixed.
Thanks
