### ISSUE TITLE
Copy Document Doesn't copy "Shortcut Dimensions"

### ISSUE THREAD

**Issue by BSSIRajbir** [Microsoft/AL#4792]
**Describe the bug**

On Sale Orders, I have set the Dimension for the Sales Order. Now, when I copy the Sales Order, All the fields are getting copied except Shortcut Dimension Except Dimension. 

**To Reproduce**
1. Go to "Sales Order'. Create One Sales Order and define the Dimension for it. 
2. Now Create another Sales Order and Navigate to Actions->Functions->Copy Document

3. Now Select the previously created Sales Order and enable "Include Header" as well as enable "Recalculate Lines". 

4. After Processing, You will see, all the fields are copied except Dimension. 

**Expected behavior**
All the fields should be copied on Copy Document including Dimension

**Screenshots**
![image](https://user-images.githubusercontent.com/43894249/55118260-ff560280-50aa-11e9-8e7f-137d786fb1fb.png)

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
