### ISSUE TITLE
Advanced View for items in BC SaaS return wrong value

### ISSUE THREAD

**Issue by podgaard** [Microsoft/AL#4793]
**Describe the bug**
Advanced View for items - does not return selected value if you have added extension to page. 

**To Reproduce**
1) Add an extension to the page "Item Lookup" with 1 additional field
2) Go to Sales Order 
3) Add New Line of type Item
4) Lookup Number, and go to Process - Advanced View 
5) Select an item, and notice it does not use the selected item from the Advanced View 

Like this
```
pageextension 70148 ItemLookupMG extends "Item lookup"
{
    layout
    {
        addafter(Description)
        {
            field(VendorItemNoMG; "Vendor Item No.")
            {
                ApplicationArea = all;
                Editable = true;
            }
        }
    }
}
```

**Expected behavior**
That it adds the selected item to the order.

I can´t reproduce in BC 14.0 On Premise, but I can´t see any mention of this bug if I search

**Screenshots**

**Versions:**

 - AL Langauge: 3.0.102444

 - Business Central:  DK Dynamics NAV 13.4 (29469)

**Comment by thpeder** [comment]
Let's get the issue to a team who will backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
