### ISSUE TITLE
Phys. Inventory Journals: Posting no longer working for ItemTrackingCode LOTALLEXP 

### ISSUE THREAD

**Issue by mivtf** [Microsoft/AL#4796]
Phys. Inventory Journals: Positive adjustments no longer working for ItemTrackingCode LOTALLEXP 

Posting fails with  “Error: "Expiration Date must have value in Tracking Specification: Entry No.=1. It cannot be zero or empty."

**To Reproduce**

1.   Inatall docker bcinsider.azurecr.io/bcsandbox-master:base

2.   Go to Items, Item No. 80025 : Change item tracking code to LOTALLEXP  

3.   Go to Inventory Journals, DEFAULT : create new journal line
Entry Type: Positive Adjm.
Item No. 80025
Location Code: BLUE
Quantity: 10

4.   Go to Line/Item Tracking Lines (add column Expiration Date, reopen form) : populate tracking
Lot No.: EXISTINGLOT
Quantity (base): 10
Expiration Date: 10-10-2019

5. (Post)

6.   Go to Phys. Inventory Journals, DEFAULT
Calculate Inventory:
Filter: Item No: 80025

7.   At the new calculated journal line : 
Enter "Qty. (Phys. Inventory)" = 15     (trigger positive adjm. 5 pcs)

8.   Go to Line/Item Tracking Lines : populate tracking
Lot No.: NEVERUSEDBEFORE
Quantity (Base): 5
Expiration Date: 11-11-2019

9.   (Post)

Error: "Expiration Date must have value in Tracking Specification: Entry No.=1. It cannot be zero or empty."

**Expected behavior**
A positive adjustment for the new lot no. and expiration date was posted with no error.
I have tested/confirmed this has been working as late as Update23 W1 13.4 (29613) 

**Versions**
Version: Platform 14.0.29608.0 + Application 29651 (W1 14.0)
Version: Platform 14.0.29530.29573 + Application 29654 (W1 14.0)
(but is still working as intended in Update23 W1 13.4 (29613) )

**Screenshots**
The error was introduced between Update23 W1 13.4 (29613) and Spring Release W1 14.0 (29654), where in CU22 PostItemJnlLine.CheckExpirationDate() ExpirationDate is now set unconditionally when item journal line is Phys. Inventory, with no respect for the “EntriesExists” flag that was picked up a few lines earlier in the code.
This will wipe the Expiration Date from phys. inventory journals item tracking when no existing item ledger entry exists for the lot no. and itemtrackingcode LOTALLEXP is used.

![CU22](https://user-images.githubusercontent.com/46669432/55175810-4d890580-5180-11e9-8d55-826dc2baef9a.png)

**Comment by JSebastianN** [comment]
This has been raised as Issue Id  175769 in MPN Collaborate

**Comment by thpeder** [comment]
Thanks, please follow the ticket on collaborate for further updates.
