### ISSUE TITLE
No semicolons for method signatures

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#48]
I find the semicolons at the end of the method signatures Terrible. Here is the example of OnRun (). Are the Really Necessary?

![unbenannt](https://cloud.githubusercontent.com/assets/16351673/21567510/edda9dfe-ceac-11e6-9245-b2a2253fd9ce.PNG)

And I would prefer curly braces instead of BEGIN and END.

**Comment by StanislawStempin** [comment]
Thank you for the feedback. Many of these cases are a matter of preference and we will take it into account when considering future syntax changes.

**Comment by Gallimathias** [comment]
Thanks for the answer :). On Microsoft connect I always think nobody reads the feedback. I still hope with my community that Microsoft in the near future AL will be replaced by C#. ;)
