### ISSUE TITLE
info: How Do I : Create a Report, and layout, in VSCode?

### ISSUE THREAD

**Issue by srenders** [Microsoft/AL#480]
FYI, I created a blog about how to create a report, and the layouts, in VSCode:
[http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/](http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode)

**Comment by AmolSalvi** [comment]
Thats nice one steven

**Comment by cristianvalgar19** [comment]
Css not showing......When i hit go live on vscode(firefox default browser) it only shows my html but if i open the file with chrome it does shows my css...why is that happening and how can i fix it?

**Comment by atoader** [comment]
I will forward this to the client team. Could you please provide information about the system you are running? We need to know the version of the server, the client, the compiler and the version of Firefox you are running. Thanks!
