### ISSUE TITLE
Adding an Action to a Page that does not have any

### ISSUE THREAD

**Issue by JJMadrigal** [Microsoft/AL#4801]
I tried to add an action in a page extension that does not contain any Action, but as this one does not have any, then with AddAfter, AddBefore, etc, it does not appear any option.

Is it possible?, or do I need to create a new page?

**Comment by qutreson** [comment]
Hi @JJMadrigal, if your page does not have any action, you can still insert relatively to one of the action areas of the page using `addfirst` or `addlast`. 

See our online docs on:
- [Page Extension Objects](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)
- [Actions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-actions-overview)
