### ISSUE TITLE
Reference to object Stockkeeping Unit List is ambiguous. Make sure you are not referencing packages containing objects with the same names.

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/AL#4803]
Hi
Using Business Central CU03 and found the issue 

Reference to object Stockkeeping Unit List is ambiguous. Make sure you are not referencing packages containing objects with the same names.

Not Sure why ?

Regards
Ammolh Saallvi

**Comment by AmolSalvi** [comment]
Found the issue and it is because of authentication .Closing the same

**Comment by VikalpSharma** [comment]
Hi Amol,

Can you please explain how you have solved the problem. We are facing the same issue and not sure why ? It is saying for all standard objects used in projects.

Thanks,
Vikalp Sharma

**Comment by AmolSalvi** [comment]
This issue happened to us when we upgrade the database and authentication was not set for the DB
