### ISSUE TITLE
REST API Put of Blob results in error

### ISSUE THREAD

**Issue by StephanFeijen** [Microsoft/AL#4804]
Hi,

Concerns Business Central Cloud version.
Using an extension a Blob-field is added to the Sales Line:
        field(50001; "Extended Description"; Blob)
        {
            Caption = 'Extended Description';
            Subtype = Memo;
        }

REST API Method Put is used to enter data in this Sales Line Blob field.
Using Postman it results in respons "204 No Content".
Every next REST API method (GET, POST, PUT) results in respons "500 internal Server Error".

How can I solve this issue?
Wild guessing for a cause: thread on blob stream remains open, if so, how to close the stream?
It looks as if the next REST API method is doing this job.

Also after timeout of 5 secs after initial PUT, the next REST API POST method correctly results in "201 Created".

Issue introduced somewhere in last two weeks, before it worked fine.

**Comment by tinfister** [comment]
Use text variable instead of blob. Store text variable data to blob on validate.
Similar approach to Work Description on Sales Order page

**Comment by StephanFeijen** [comment]
Thanx Tinfister,
We came up with the same idea of using the text variable as a workaround (it used to work fine up to two weeks ago... Any idea what has changed?)
To store in new 2K text-data field is not sufficient for larges texts I'm afraid, so I'd like to stick to the Blob.
We were wondering if there is a REST functionality to close the stream to avoid "500 internal Server Error" messages?

**Comment by tinfister** [comment]
Well the April release came and with it, new API changes. There is just too many new stuff in BC, we've probably missed something in release notes.

**Comment by thpeder** [comment]
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
