### ISSUE TITLE
schemaUpdateMode: preventing recreating by mistake

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#4805]
When I need to recreate data on a Dev environment, I follow these steps:
1. Edit the launch.json to insert this line: "schemaUpdateMode": "Recreate"
2. Publish
3. Edit the launch.json to delete this line: "schemaUpdateMode": "Recreate"

If you forget the 3rd step... you might unintentionally lose your data the next time you publish.
It just happened to me, and I had to recreate lots of data :-(

Since the Recreate option is meant to be used only once in a while, could it be specified some other way?
Or maybe the system could throw a confirmation question if the launch indicates it has to recreate,
Or maybe the system could delete the "schemaUpdateMode": "Recreate" line right after publishing this way one time,

Any other ideas on how to prevent recreating by mistake are welcome.

Salut!
Laura Nicolàs

**Comment by JohanStenberg100** [comment]
Hi Laura, thanks for filing this issue. I'm sorry that you had to recreate the data you created. The _recreate_ option however doesn't necessarily need to be used once in a while, and can be used continously when for example designing your database schema using tables. As of right now we will not commit to redesigning this feature to avoid accidental data deletion. But if more developers run into these types of issues, we'll definitely take another look. Thanks
