### ISSUE TITLE
Txt2al - Dotnet type conversion for namespaces including spaces / weird charachters

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4806]
**Describe the bug**
Testing the txt2al conversion with the ForNAV report converter results in dotnet conversion errors in case the namespaces contain a spaces or weird charachter (- or _). After reporting to ForNAV support, Michael Nielsen informed us MS will be providing a fix 'later this year'. Any plans on when this fix will be available?

**To Reproduce**
Use a dotnet variable in C/AL with a namespace containing a non-supported charachter.
Convert the objects via txt2al (ForNAV converter)
The dotnet.al file created does not contain references to the namespaces containing a space.

**Expected behavior**
Provide support in txt2al conversion for namespaces with spaces, '-' or '_'.

**Comment by atoader** [comment]
@fvet this has been fixed in the latest Docker image from the Spring release. Can you please confirm?
