### ISSUE TITLE
List Datatype cannot be used as Return List

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/AL#4808]
we need the list datatype as Return List, But facing an issue,

```
codeunit 50001 TestCodeunit
{
   procedure TestingFunctionList()
    var
      String : Text;
   begin
         ListString := SplitingStringtoList(String);
   end;

  local procedure SplitingStringtoList(String: Text) : List of [Text]
  begin
        Exit(String.Split(','));
  end;
}
```

we don't want to write String.split every time, if return accepts then it will easy and Re-Usable.

**Comment by thpeder** [comment]
Please report your suggestion on [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central)
