### ISSUE TITLE
Can't access fields from "Active Session"

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/AL#4810]
**Describe the bug**
I want to add an action to the page "Session List" to stop the sessions of users. The code gives an error when you try to publish the Extension. (OnPrem obviously)

> [2019-04-02 11:29:06.93] The request for path /BC130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed
src/pageextension/Pag9506-Ext89506.SessionList.al(24,39): error AL0118: The name '"Server Instance ID"' does not exist in the current context
src/pageextension/Pag9506-Ext89506.SessionList.al(24,61): error AL0118: The name '"Session ID"' does not exist in the current context

**To Reproduce**
```
pageextension 89506 "STSTSessionList" extends "Session List" //9506
{
    layout
    {

    }

    actions
    {
        addafter(Session)
        {
            action("STSTKillSession")
            {
                ApplicationArea = All;
                Caption = 'Kill Session', comment = 'NLB="Kill Session"';
                Promoted = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                Image = Delete;
                trigger OnAction()
                var
                    ActiveSession: Record "Active Session";
                begin
                    ActiveSession.Get("Server Instance ID", "Session ID");
                    IF Confirm('You sure?') THEN
                        StopSession(ActiveSession."Session ID");
                end;
            }
        }
    }
}
```
**Expected behavior**
No error when publishing.

**Screenshots**

**Versions:**
 - AL Langauge: 2.1.69331
 - Business Central: BE Dynamics NAV 13.2 (26556)

**Comment by tomasevicstefan** [comment]
You dont have server instance id and session id on session list, at least there are not visible on page

![1](https://user-images.githubusercontent.com/31925856/55393430-8852bb00-553d-11e9-9a67-3960db821e54.png)

**Comment by BartPermentier** [comment]
Well that shouldn't matter. I'm taking the values from the Rec.

**Comment by tomasevicstefan** [comment]
yes, but can you return rec with server computer name and server instance name
Session.get("server computer name", "server instance name")

**Comment by BartPermentier** [comment]
No also doesn't work.
![image](https://user-images.githubusercontent.com/24684493/55408911-450a4380-5561-11e9-9077-075a7873a63e.png)

**Comment by RedFoxUA** [comment]
Received the same error 2 day ago..  No changes or updates from my side.. just wanted to receive updated version of extension:
![image](https://user-images.githubusercontent.com/39195466/56766919-19622e00-679a-11e9-976c-b6b8ed02cb14.png)

**Comment by Hajime-Kusakabe** [comment]
I am having the same issue.  Has this been solved?   Let me know.

**Comment by SShadowS** [comment]
Anyone found a solution? We are getting the same error now.

**Comment by StefanMaron** [comment]
I believe that I have the same error. I added a field to the SalesHeader table and I can not access this field in my Test App. But I can even access this field in the UI. So it is there for sure. 
Error happens on Publish.
