### ISSUE TITLE
Rule021VariableDeclarationsShouldBeOrderedByType threw and exception

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#4811]
Related to #4002, I continually get this warning:

> Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Readability.Rule021VariableDeclarationsShouldBeOrderedByType' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'

I can't find where I may have variables declared out of order (230+ objects to scan).  I was under the impression that #4002 would resolve this issue (back in November) but I am currently using the 13.03 release and the latest AL Extension.

Has this been ported to the recent on premise builds?  

AL Info:
> Name: AL Language
> Id: ms-dynamics-smb.al
> Description: AL development tools for Dynamics 365 Business Central
> Version: 2.1.109895
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
 
VS Code Info:
> Version: 1.32.3 (user setup)
> Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
> Date: 2019-03-14T23:43:35.476Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by AskeHolst** [comment]
Try the vsix that comes with the [2019 Spring Release](https://www.microsoft.com/en-US/download/details.aspx?id=58106) that should solve it.

**Comment by AskeHolst** [comment]
Try updating the the latest extension from the marketplace (3.0.115791).

**Comment by GreatScott000** [comment]
The new version of the extension does appear to resolve this issue but raises two, so far, issues that make it inconvenient to use.  See #4814 and #4820.

**Comment by JohanStenberg100** [comment]
Hi @GreatScott000, I'll close this issue since you are stating it's resolved in the latest release.
