### ISSUE TITLE
Error while opening PO?

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4812]
Hi All,

So what i am getting , when trying to open a purchase order on SANDBOX environment in CRONUS USA Inc.
![image](https://user-images.githubusercontent.com/33481576/55404509-a76d3f00-5575-11e9-872f-d842745f4af0.png)

However, this is not causing any issue in my work.
Intent is just letting know about this error.

Thanks

**Comment by JohanStenberg100** [comment]
Hi @SUD-D365, thanks for reporting this issue, we'll take a look.

**Comment by IhorHandziuk** [comment]
Hello @SUD-D365 and thank you for reporting the issue. 
It looks like one of the knows issues that we looked into recently, did you have "Microsoft Dynamics GP" extension installed in your sandbox?

**Comment by SUD-D365** [comment]
Hello @IhorHandziuk , thanks for prompt revert.
Yes i have installed below extensions, If you are talking about one of these. But these extensions came with default sandbox.
![image](https://user-images.githubusercontent.com/33481576/56186384-dc30ca00-603c-11e9-8cb0-be6f4ccacd7b.png)

**Comment by IhorHandziuk** [comment]
Thank you for the quick response. This bug will be fixed in an upcoming update. As a mitigation we can suggest to uninstall these extensions.
