### ISSUE TITLE
Can't publish my extension to sandbox

### ISSUE THREAD

**Issue by Mr-Pingu** [Microsoft/AL#4813]
[2019-04-02 15:22:17.27] Authenticating...
[2019-04-02 15:22:17.96] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/metadata
[2019-04-02 15:22:19.01] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 3.0
- Web API: 3.0
- Debugger: 2.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4
- Supported Web API: 1.0, 2.0
- Supported debuggers: 1.0, 2.0

**Versions:**
2.1.109895
 This doesnt work anymore btw
 - Business Central:
14.0.29537.29654

Where can I find updated AL language extension? 

Thanks in advance.

**Comment by tomasevicstefan** [comment]
If you are using docker, the best is to install from container

**Comment by atoader** [comment]
I've pushed a new version of the extension to the marketplace. Can you try again?

**Comment by Mr-Pingu** [comment]
That fixed it
