### ISSUE TITLE
Could not download reference symbols. Please ensure that: 1. The correct server name and instance are specified in the launch.json file. 2. The correct application version is specified in the app.json file.

### ISSUE THREAD

**Issue by umang11** [microsoft/AL#4817]
[2019-04-03 08:59:09.45] Using reference symbols cache path: c:\Users\usrivastava\Documents\AL\ALProject8\./.alpackages
[2019-04-03 08:59:09.45] Authenticating...
[2019-04-03 08:59:10.10] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-04-03 08:59:10.10] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-04-03 08:59:52.94] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code InternalServerError. Reason: Internal Server Error
[2019-04-03 08:59:52.94] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
![Screenshot_21](https://user-images.githubusercontent.com/12784260/55451024-da9fe480-55ee-11e9-8667-dab18123aa70.png)

**Comment by atoader** [comment]
Hi! We are currently looking into this issue. What country version is your sandbox tenant? From what country are you downloading symbols?

**Comment by umang11** [comment]
my sandbox version is AU and i am downloading symbols from IN

**Comment by umang11** [comment]
> my sandbox version is AU and i am downloading symbols from IN



> Hi! We are currently looking into this issue. What country version is your sandbox tenant? From what country are you downloading symbols?

my sandbox version is AU and i am downloading symbols from IN

**Comment by NikolayVityuk** [comment]
Any news on this issue? I have the samr problem with downloading symbols from AU

**Comment by atoader** [comment]
This issue should have been resolved with the minor update released in May. An update to one of the underlying service components was was causing the timeout. We have patched the service so that the download does not timeout anymore.
In the future, please contact customer support if experience any issues in the online sandbox environment.

**Comment by martin-juul** [comment]
Still experiencing this issue.

app.json
```json
{
  "id": "REDACTED",
  "name": "business-central",
  "publisher": "REDACTED",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "1.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "showMyCode": true,
  "runtime": "4.0"
}
```

**Comment by samination** [comment]
Is it possible to download the symbols from the demo version of BC? 

Am getting this error
[2020-10-23 13:09:29.49] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**Comment by JazzminnNo** [comment]
Still getting the error as well. It is not fixed

**Comment by ravenboilinux** [comment]
I am getting this error too 
[2021-04-20 19:27:23.75] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.
Microsoft (R) AL Compiler version 7.1.6.48380
Copyright (C) Microsoft Corporation. All rights reserved
