### ISSUE TITLE
How to Remove the fields from Field Groups in AL Table Extension ?

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4819]
Hello,

I wanted to remove the old field groups and want to add a new field in that place. Is it possible to remove the field groups in AL Table extension ? if possible how to do that ?

Thanks & Regards,
P.Sainath.

**Comment by JohanStenberg100** [comment]
Hi @sainath654, thanks for opening this issue. We do not support this at the moment and we don't have any plans to support it in the future as of today.
