### ISSUE TITLE
Created table -shows up on Dynamics business central page on publishing - how to add records to this table ?

### ISSUE THREAD

**Issue by ac2707** [Microsoft/AL#4821]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by JohanStenberg100** [comment]
As your message suggests, please use the groups listed to ask questions such as these.
