### ISSUE TITLE
Unable to provide a valid identifier to Repeater control

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#4822]
Getting the warning below on what would appear to be all my repeater controls but only in one project (in the same workspace as 5 others).  Regardless of what I change the identifier to it always produces a warning.  I have tried Bob, Control1, Group, "Accidents" serveral unprintable words, nothing seems to be accepted but only in 1 project????.

Any suggestions.
![image](https://user-images.githubusercontent.com/4333956/55459442-7a597480-55e7-11e9-95ef-a9cc8edbc023.png)

> The repeater 'Accidents' is not supported by the Web client.

> 
> {
> 	"resource": "/c:/EvolveiMS/Repos/dev/Nav/DRON001/13.0 (Nav BC)/Extension/HR/Page/iMS Accidents 9043230.al",
> 	"owner": "_generated_diagnostic_collection_name_#1",
> 	"code": "AW0008",
> 	"severity": 4,
> 	"message": "The repeater 'Accidents' is not supported by the Web client.",
> 	"source": "AL",
> 	"startLineNumber": 12,
> 	"startColumn": 22,
> 	"endLineNumber": 12,
> 	"endColumn": 31
> }

AL Language Information:
> Name: AL Language
> Id: ms-dynamics-smb.al
> Description: AL development tools for Dynamics 365 Business Central
> Version: 3.0.115791
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

VS Code Information
>  Version: 1.32.3 (user setup)
> Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
> Date: 2019-03-14T23:43:35.476Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

BC Information
>On Premise
> Version: GB Dynamics NAV 13.3 (27233)
> Created: 09/10/2018 17:07

**Comment by JohanStenberg100** [comment]
Repeaters are not supported for pages of type `Card`, `Document` or `ListPlus`, I assume this is why you see this warning only for the one project. We will treat this as a bug to improve the error message.

**Comment by larswestman** [comment]
In previous version of AL this wasn't detected, that's why it started to popup today. Just change PageType to "List" as it should be when you have a repeater

**Comment by GreatScott000** [comment]
@JohanStenberg100 thank you for improving the message. 

The issues were that the PageType was incorrect or not specified.  This extension was built from older custom code that we inherited. There are a few pages the that have an "embedded" repeater control on a card type page.  I will have to move these to a ListPart I guess.

**Comment by RobertdeRoos** [comment]
> Repeaters are not supported for pages of type `Card`, `Document` or `ListPlus`, I assume this is why you see this warning only for the one project. We will treat this as a bug to improve the error message.

ListPlus indicates it is a list. How can you have a list without a repeater??

**Comment by RobertdeRoos** [comment]
> In previous version of AL this wasn't detected, that's why it started to popup today. Just change PageType to "List" as it should be when you have a repeater

The List page has different behavior when you use it in loopup mode. The ListPlus starts in edit mode and allows us to use it as a selector (with a Ok and Cancel button) and the List page starts in view mode.

**Comment by atoader** [comment]
@GreatScott000 is it clear what is happening here? Can I close this as by-design or is there more information that we can provide?

**Comment by GreatScott000** [comment]
@atoader yes, I understand and you can close this.

**Comment by atoader** [comment]
Thanks! I'll close it.
