### ISSUE TITLE
launchBrowser property invalid in launch.json 

### ISSUE THREAD

**Issue by papillon** [Microsoft/AL#4825]
**Describe the bug**
In more recent versions of the AL Language extension (e.g. 2.1.106653) the previously valid and useful setting "launchBrowser" is ignored and marked as invalid.

**Expected behavior**
I would like to control whether a new browser session starts when running "Publish without Debugging" (Ctrl+F5), just like before. Since there is no documentation available about this change, I classified this report as a bug.

**Comment by JohanStenberg100** [comment]
Hi @papillon, on the latest AL version (3.0.115791) from the VS Code marketplace, the `launchBrowser` works fine as far as I can see. Please try and install that version, if it still doesn't work please comment on this issue, but I will close it for now.

**Comment by papillon** [comment]
Hi @JohanStenberg100, yes that is right, the marketplace version has got the option. But I am talking about the versions shipped with Business Central CU4 and/or CU5, which have been released just a couple of days ago. The marketplace changelog says the extension is for "Business Central Fall 2018 update (CURRENT - 2018/08/27)", so older than the Cumulative Updates.

Are you telling me the recent CU releases are already obsolete and that I should use the 3.0.x version from marketplace, no matter what the target BC version is and ignore the fact that it is supposed to be for the older Fall 2018 release?

**Comment by JohanStenberg100** [comment]
Hi again @papillon, the changelog is outdated in the marketplace and we will fix that, thanks for pointing this out. You should always trust the version number, the higher the number the later the release. The extension tries to never break backward compatability if you want the latest extension with the latest bug fixes etcetera, please go for the marketplace one.

The CU releases' extension is not obsolete, the compiler which is built into the server and the extension are the same in the CU releases. But if you want the latest then use the marketplace one.

**Comment by papillon** [comment]
Thanks @JohanStenberg100, that helps a lot. 

TBH, it's quite confusing to me with BC having a build number, and internal version number like 13.4, the extension/compiler has one, and then there is the "runtime" property in app.json with another apparently loosely related number(*). Maybe the logic behind that could be explained somewhere.

(*) The 3.x marketplace extension has runtimes values 1.0, **2.2**, and 3.0. While the CU5 extension has 1.0 and **2.4**. So the marketplace version appears a bit older when you want to do 2.x stuff.

**Comment by JohanStenberg100** [comment]
The marketplace extension is essentially our "master" version, so if you want to use the latest features, stick to that one. But as you say, some runtimes might not be supported, then you should use the extension provided by that CU. We are in the process of unifying this, a long term goal is to have 1 "version" (no branches) of the compiler support all BC / NAV installations. However, we don't have a date on when this is achieved.
