### ISSUE TITLE
Hi I need to Upload or send a file as attachment with HttPClient.Send , how can I achieve this I need to send or Upload a file over HTTP Post, multipart form data

### ISSUE THREAD

**Issue by vkt12sep** [Microsoft/AL#4827]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by thpeder** [comment]
Hi @vkt12sep,
The API allows you to write whatever you want in the body, but you need to get the format of the request body correct.
