### ISSUE TITLE
VSC Opens Old PublicWebBaseURL

### ISSUE THREAD

**Issue by meilel** [Microsoft/AL#4829]
**Describe the bug**
I changed the PublicWebBaseURL of my NavServer with the follwoing commads:
Set-NAVServerConfiguration  -KeyName PublicWebBaseURL -KeyValue 'test.example.ch/NAV/'
Restart-Service 'MicrosoftDynamicsNavServer$NAV'

But VSC still opens the old PublicWebBaseUrl in my browser when i press F5 / ctrl+F5.
If I uninstall the VSC AL Language Extension and reinstall it, VSC opens the new url(test.example.ch/NAV/) in my webbrowser.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Run your extension with F5
2. Browser should open the PublicWebBaseUrl
3. Change the PublicWebBaseUrl of the NavServer
3.1 Set-NAVServerConfiguration  -KeyName PublicWebBaseURL -KeyValue 'test.example.ch/NAV/'
3.2 Restart-Service 'MicrosoftDynamicsNavServer$NAV'
4. Run your extension again with F5
5. Browser still opens with the old PublicWebBaseUrl
6. Uninstall AL Language VSC extension
7. Install AL Language VSC extension
8. Run your extension with F5
9. Browser should open the new PublicWebBaseUrl

**Expected behavior**
By pressing F5/ctrl+F5 the browser should always open with the current PublicWebBaseUrl

**Versions:**
 - AL Langauge:  3.0.115791
 - Business Central: latest

**Comment by JohanStenberg100** [comment]
Hi @meilel, you can control which URL that is opened using the `launch.json` file. See more [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Launchjson). Can you try and update the `server` and potentially the `serverInstance` attributes and see if this helps?

**Comment by meilel** [comment]
Hi @JohanStenberg100 thanks for your reply. 
The `server `and `serverInstance `parameter don't affect the weburl which is opened in the browser. These Parameters are only for downloading symbols and publishing the extenesion etc. VSC get this information from the `PublicWebBase `Settings on the NavServer.

**Comment by JohanStenberg100** [comment]
Hi @meilel thanks for pointing this out ( nice catch :) ). Did you restart VS Code and it still opened the old URL?

**Comment by meilel** [comment]
@JohanStenberg100 If I close all VSC windows, it opens the new URL.

**Comment by JohanStenberg100** [comment]
@meilel this is by design. For now please continue to remember to close and re-open VS code if you change this URL. We might improve this in the future however, thanks by the way for taking the time to verify all of this.
