### ISSUE TITLE
Missing External Methods

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#483]
Been converting our app, and we're missing some external methods:
- 400 | Codeunit | SMTP Mail 
  - SMTPMail.**CreateMessage**
- 9200 | Codeunit | Matrix Management
  - MatrixManagement.**GenerateMatrixData**
- 485 | Table | Business Chart Buffer 
  - BusinessChartBuffer.**AddMeasure**
  - BusinessChartBuffer.**SetXAxis**
  - BusinessChartBuffer.**AddColumn**
  - BusinessChartBuffer.**SetValueByIndex**

**Comment by StanislawStempin** [comment]
Thanks, waldo. I passed on the request to the application team.

**Comment by StanislawStempin** [comment]
All requested functions have been exposed and will be available in the next update.
