### ISSUE TITLE
Problem creating new sandbox

### ISSUE THREAD

**Issue by fsporck** [Microsoft/AL#4831]
Hi! I'm trying to create a new sandbox in BC Saas for our customer Rocks of Norway. It prepares the new sandbox, but then proceeds to remove it after a little while. I did manage to get into it once, but it didn't include all companies, and suggested the setup guide, when the company already is setup and has been in use since January. 

Regard,

Fredrik Spørck

**Comment by thpeder** [comment]
Hi @fsporck;
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
To open a support case, you can, Open a support request to CSS through the PartnerSource portal

**Comment by Mr-Pingu** [comment]
@thpeder, how to do when you are not a partner?

**Comment by fsporck** [comment]
It seems like this was fixed in our case. Looked like Microsoft published the wrong version. Then they published the old one again. After that it worked.
