### ISSUE TITLE
create a sandbox with the production data not work

### ISSUE THREAD

**Issue by mannavmej** [Microsoft/AL#4832]
We are trying to create a sandbox with the production data, but the system remains in the Preparing state until the sandbox environment disappears.
![image](https://user-images.githubusercontent.com/43881281/55491421-bb787580-5635-11e9-9013-a4c5b0ab9d8d.png)

When we try to access the sanbdox environment directly one is created automatically with a test company with a higher version but without the production data.

**Comment by JohanStenberg100** [comment]
Hi @mannavmej, please open up a support ticket or reach out to your Dynamics BC partner to get this resolved. We can't help you with a tenant-specific error here in this forum. Thanks!
