### ISSUE TITLE
[UICop] Avoid Group section within a Repeater Control

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4834]
**Is your feature request related to a problem? Please describe.**
When you create a List / ListPart page, with a Repeater, and below / beneath the repeater control, you add a 'group' control / section, the pages don't render well in the webclient. (all was ok in the Windows / RTC client) Removing the group from the repeater section fixes the problem.

**Describe the solution you'd like**
Add a new UICop rule to detect pages with repeater sections, containing a child group section.

**Additional context**
See https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=89076893999104

**Comment by JohanStenberg100** [comment]
Hi @fvet, thanks for filing this issue. We'll investigate to see if there's an issue with the web client rendering or if we should add a UICop rule.

**Comment by qutreson** [comment]
The behavior of the web client is as expected. This rule suggestion has been brought to the owning team which has added it to their backlog.
