### ISSUE TITLE
Extension compilation error while creating package. AL symbols are downloaded and when using Shift+F5 package is getting created but not working with F5

### ISSUE THREAD

**Issue by SangeetaSewani** [microsoft/AL#4835]
[2019-04-04 10:32:50.91] Publishing AL application using launch configuration 'Your own server'.

[2019-04-04 10:32:50.95] Targeting server 'http://localhost', server instance 'BC130' and tenant ' '.

[2019-04-04 10:32:50.95] Using Windows authentication.

[2019-04-04 10:32:50.96] Sending request to http://localhost:7049/BC130/dev/apps?SchemaUpdateMode=synchronize

[2019-04-04 10:32:51.05] The request for path /BC130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed

Codeunit/SDH_CodeunitExt_50000_ExtensionSubcriber.al(8,54): error AL0132: 'Codeunit' does not contain a definition for 'Item Jnl.-Check Line'

Table%20Extension/SDH_TableExt_50007_PurchaseHeaderArchive.al(1,60): error AL0247: The target Table "Purchase Header Archive" for the extension object is not found

Table%20Extension/SDH_TableExt_50011_PurchaseCreditMemoLine.al(1,62): error AL0247: The target Table "Purch. Cr. Memo Line" for the extension object is not found

Table%20Extension/SDH_TableExt_50009_PurchaseRcptLine.al(1,55): error AL0247: The target Table "Purch. Rcpt. Line" for the extension object is not found

Table%20Extension/SDH_TableExt_50003_PurchaseHeader.al(44,26): error AL0185: Table 'Purchase Line' is missing

Codeunit/SDH_CodeunitExt_50000_ExtensionSubcriber.al(9,58): error AL0185: Table 'Item Journal Line' is missing

Table%20Extension/SDH_TableExt_50003_PurchaseHeader.al(45,24): error AL0185: Table 'Purchase Line' is missing

Table%20Extension/SDH_TableExt_50005_PurchaseInvoiceHeader.al(1,63): error AL0247: The target Table "Purch. Inv. Header" for the extension object is not found

Codeunit/SDH_CodeunitExt_50000_ExtensionSubcriber.al(22,19): error AL0185: Table 'Location' is missing

Table%20Extension/SDH_TableExt_50003_PurchaseHeader.al(46,17): error AL0185: Table 'Vendor' is missing

Page%20Extensions/SDH_PageExt_50004_Location.al(8,50): error AL0118: The name 'Allowed Diff. in Stock Take' does not exist in the current context

Page%20Extensions/SDH_PageExt_50002_PurchaseInvoice.al(8,38): error AL0118: The name 'Expense Invoice' does not exist in the current context

Table%20Extension/SDH_TableExt_50012_PurchaseHeaderArchiveLine.al(1,58): error AL0247: The target Table "Purchase Line Archive" for the extension object is not found

Table%20Extension/SDH_TableExt_50003_PurchaseHeader.al(1,58): error AL0247: The target Table "Purchase Header" for the extension object is not found

Table%20Extension/SDH_TableExt_50010_PurchaseInvLine.al(1,54): error AL0247: The target Table "Purch. Inv. Line" for the extension object is not found

Table%20Extension/SDH_TableExt_50008_PurchaseLine.al(1,56): error AL0247: The target Table "Purchase Line" for the extension object is not found

Page%20Extensions/SDH_PageExt_50002_PurchaseInvoice.al(1,52): error AL0247: The target Page "Purchase Invoice" for the extension object is not found

Page%20Extensions/SDH_PageExt_50004_Location.al(1,49): error AL0247: The target Page "Location Card" for the extension object is not found

Table%20Extension/SDH_TableExt_50013_Location.al(1,45): error AL0247: The target Table "Location" for the extension object is not found

Table%20Extension/SDH_TableExt_50004_PurchaseRcptHeader.al(1,60): error AL0247: The target Table "Purch. Rcpt. Header" for the extension object is not found

Table%20Extension/SDH_TableExt_50006_PurchaseCreditMemoHeader.al(1,63): error AL0247: The target Table "Purch. Cr. Memo Hdr." for the extension object is not found

Table%20Extension/SDH_TableExt_50002_VendorExt.al(8,29): error AL0185: Table 'G/L Account' is missing

Table%20Extension/SDH_TableExt_50002_VendorExt.al(1,49): error AL0247: The target Table "Vendor" for the extension object is not found

Page%20Extensions/SDH_PageExt_50001_Vendor.al(8,46): error AL0118: The name 'Expense G/L Account No.' does not exist in the current context

Page%20Extensions/SDH_PageExt_50003_PostedPurchaseInvoice.al(8,38): error AL0118: The name 'Expense Invoice' does not exist in the current context

Page%20Extensions/SDH_PageExt_50001_Vendor.al(1,42): error AL0247: The target Page "Vendor Card" for the extension object is not found

Page%20Extensions/SDH_PageExt_50003_PostedPurchaseInvoice.al(1,59): error AL0247: The target Page "Posted Purchase Invoice" for the extension object is not found

**Comment by DevelopmentNewVision** [comment]
Same as me. I found a similar article of this problem. They are suggested to re-store the previous version of AL Language extension.

**Comment by DevelopmentNewVision** [comment]
Until the latest version is not stable I recommend to re-install the previous version.
Before that set the Auto Update to FALSE, otherwise it will install automatically the latest version.
![image](https://user-images.githubusercontent.com/48213224/55537265-1785dd00-56bc-11e9-87ab-404de8b84136.png)

**Comment by SangeetaSewani** [comment]
I followed steps but it is not working for me.

**Comment by DevelopmentNewVision** [comment]
![image](https://user-images.githubusercontent.com/48213224/55540667-b7933480-56c3-11e9-95c4-f232fd146a05.png)
![image](https://user-images.githubusercontent.com/48213224/55540676-bc57e880-56c3-11e9-93f3-e476906b6cc7.png)

did you restored the previous version? 
i put here the link of a similar issues:
https://github.com/Microsoft/AL/issues/4508
https://github.com/Microsoft/AL/issues/4301

**Comment by SangeetaSewani** [comment]
Yes i did and restarted application again but same issue exists. In event viewer i am getting below error 

Server instance: BC130
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 64eb3e7d-fdf1-4bfe-866c-d71689966ced
ServerSessionUniqueId: 71e692b6-32f8-4ed7-938b-5829e48ec8be
ServerActivityId: 04568af1-f9a4-442e-bd7b-e808a82d1a05
EventTime: 04/04/2019 08:17:25
Message Failed request -- Method:POST; Url:http://localhost:7049/BC130/dev/apps?SchemaUpdateMode=synchronize; StatusCode:422; ReasonPhrase:Unprocessable Entity; Token:
ProcessId: 12484
Tag: 00000LY

**Comment by atoader** [comment]
Hi! The original issue is caused by not having the correct symbols published to the server. We need more information in order to help you. What is the version of your runtime? What is the version of the VSCode extension that you are using? Can you reproduce this with a smaller extension that you can share?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
