### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jvincke** [microsoft/AL#4841]
**Describe the bug**
Within a project with around 600 objects (converted from C/AL to AL) we open e.g. each tableextension object one by one and fix remaining issues. For instance we modfiy the tableextension object name. After a while, like 30 opened and closed files, the memory consumption of the process Microsoft.Dynamics.Nav.EditorServices.Host exceeds 2GB. And it goes on and on. It appears that opening a file -obviously- takes up memory, but closing the file does not release the memory in use.

In order to exclude that the error arises from another VS Code Extension, I deactivated all other extensions, except AL Language and the German Language Pack.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a project with a reasonable high amount of tableextension objects (e.g. 100)
2. Open, modify, save **and close** each file one by one
3. While doing step 2 monitor memory consumption of Visual Studio Code within Task Manager

**Expected behavior**
Free up memory when the object is closed.

**Screenshots**
Task Manager after opening 1st file: https://pasteboard.co/I8zFiQH.png
Task Manager after opening 5th file: https://pasteboard.co/I8zFTFs.png
Task Manager after opening 10th file: https://pasteboard.co/I8zG8eg.png
Task Manager after opening 20th file: https://pasteboard.co/I8zGirA.png

**Versions:**
 - AL Language: 3.0.115791
 - Business Central: irrelevant, but in my case build 13.0.24623.0 is running on my localhost

**Comment by esbenk** [comment]
The memory allocation depends on many things. When editing source files the language compiler is constantly running in the background to provide diagnostic information (errors and warnings).

The language service is written in C# and the the garbage collection of memory may not happen immediately. You may have to wait for a while before the memory are released.

That said, we have recently found and fixed a couple of minor leaks, but not it didn't make it to the April release. 

I noticed that your are using the Insider version of VsCode, do you see that same for the released version?

**Comment by jvincke** [comment]
I cannot confirm that the c# garbage collection triggers at any time, because I noticed it after working half a day in a large project. I noticed the problem as my workstation slowed down. I checked Task Manager and VS Code / AL Language ate up my entire available memory (6.5GB at that point). I would guess that the variables used are not discarded. Then no effect is expected from the garbage collection.

I usually do not work with VS Code Insiders. I noticed this behavior with the stable version and I switched to the Insiders build to test if the problem exists there too.

**Comment by esbenk** [comment]
As I mentioned we have fixed some minor leaks after the April release and maybe that is what you see.

**Comment by marknitek** [comment]
We have the same issue here, the following screenshot is from a collegue:
![image](https://user-images.githubusercontent.com/2346803/56339823-0ce54080-61b0-11e9-97ad-74de61ce760d.png)
The Problem here is that at some point you are not able to run the docker containers any more! That is a real problem.

The memory requirement can go insanly high when using local docker development with vscode eating up that much memory. Even regular Visual Studio with Resharper does not eat that much (which is a real resource hog).

If you have any fixes to the gc then you should consider to release that for the stable asap...

**Comment by fvet** [comment]
Facing similar issues over here as well. When trying to convert (part of) our solution and loading the objects in VSCode (only one al file is opened in the editor), VScode eats almost all CPU/memory. Project consists of 5132 al objects, with 845 errors and 219 warnings (CodeAnalysis is not activated)

![cpu](https://user-images.githubusercontent.com/25268332/56443092-5e4a1880-62f3-11e9-9098-fad2e7260d24.png)

![image](https://user-images.githubusercontent.com/25268332/56443164-b1bc6680-62f3-11e9-9165-28a6a926ac97.png)

**Comment by esbenk** [comment]
Depending on your machine, it will take a minute or two (for your project size) for the initial full compilation to complete. In that period there will be constant high cpu load. That is expected.

**Comment by marknitek** [comment]
CPU load is not an issue. Memory usage is an issue since it can prevent container start for example...

**Comment by shashiBssi** [comment]
![image](https://user-images.githubusercontent.com/38439762/61384216-c8139780-a8cd-11e9-8487-2a33e0b853f3.png)

**Comment by shashiBssi** [comment]
![image](https://user-images.githubusercontent.com/38439762/61385077-6b18e100-a8cf-11e9-9389-a5496c230d98.png)

**Comment by AitorLD** [comment]
Try to deactivate the code analysis in background. 
You have to writte this in your settings.json

"al.backgroundCodeAnalysis": false

**Comment by kalberes** [comment]
Try disabling the below:
"editor.codeLens": false,
 "al.enableCodeAnalysis": false,

**Comment by atoader** [comment]
To reduce memory consumption further during publishing and full build (Ctrl+Shift+B), use "al.incrementalBuild": true . We have addressed the major performance issues and you can benefit from them by trying the latest developer preview from https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

**Comment by KristofKlein** [comment]
same here. two code cops (web and ui), approx 1200 Objects with 866 Problems (only warning and Information)
memory consumption makes VSC almost unusable (worst thing until now 24 GB used by Microsoft.Dynamics.Nav.EditorServices.Host out of 32). AL Version 3.0.152816

**Comment by KristofKlein** [comment]
> same here. two code cops (web and ui), approx 1200 Objects with 866 Problems (only warning and Information)
> memory consumption makes VSC almost unusable (worst thing until now 24 GB used by Microsoft.Dynamics.Nav.EditorServices.Host out of 32). AL Version 3.0.152816

Switch to 4.0.152993 - a bit better --- while coding have not seen more than 8 GB in usage...while compile it goes above 12 GB and drops again after that... but code cops are so slow ... If I change just  a single character in a file all code cops results are disappearing until i stop typing and wait for 10 seconds ...

**Comment by atoader** [comment]
Are you also using the incremental build setting that I mentioned above, that should reduce the memory consumption of the full build to under 8 GB? We are aware that the performance of cops is not ideal for large projects and we have it on our backlog to improve it.

**Comment by KristofKlein** [comment]
> Are you also using the incremental build setting that I mentioned above, that should reduce the memory consumption of the full build to under 8 GB? We are aware that the performance of cops is not ideal for large projects and we have it on our backlog to improve it.

well I don't mind about the build RAM usage....for me it is the solution just gets unusable over time and forces me to restart it ... (at the moment I have not done ANY build with the code that I have) only removing warnings and make my code clean. 
so on 4.0 it also goes up and up and up :
![image](https://user-images.githubusercontent.com/23500845/63335090-0c66dd00-c33d-11e9-9d7c-34f516c8098d.png)

**Comment by KristofKlein** [comment]
and up 
![image](https://user-images.githubusercontent.com/23500845/63336026-b3984400-c33e-11e9-8d3f-211bdf4bab2a.png)

**Comment by marknitek** [comment]
Yes it is very annoying... Ctrl+shift+p reload window every now and then helps but anything above 8gb is just unusable tbh...

**Comment by atoader** [comment]
It seems that we have a memory leak in one of the code cops. For the moment, I suggest disabling code analysis and running them as part of your CI/CD pipeline and only enabling it when needed.
