### ISSUE TITLE
code unit 0145 E-Invoice Mgt. and codeunit 10147 E-Invoice Object Factory

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4845]
Hello i need to view the code for this two code units in order to create the best way to integrate standar funcionality of Mexico E-Invoice to another PACs

**Comment by JohanStenberg100** [comment]
Hi @adrianordonez, thanks for filing this issue. There will be improvements in this area after we stop shipping C/SIDE, but you can today reference the code unit inside your code, make sure you have a running server connected to your VS Code instance, and then right click and "Go To Definition" to see the code. Another option would be to use C/SIDE.

**Comment by adrianordonez** [comment]
Thanks for the reply, one last doubt on cside i got the error that my user do not have permissions to design on the code unit, this enviroment was created with Sandbox container option from BC hosted locally, where can i assign the correct permissions to my user?

**Comment by JohanStenberg100** [comment]
Are you unsuccessful using "Go To Definition"? I think that's the easiest way to do it.
