### ISSUE TITLE
Multiple launch configurations and VSCode 1.33.0

### ISSUE THREAD

**Issue by papillon** [Microsoft/AL#4846]
**Describe the bug**
Since VSCode 1.33.0, Publishing does not work and more when multiple launch configurations are defined. Previously, in 1.32.3, a selection dialog would pop up, asking which configuration to use.

Might or might not be an issue of AL Language.

**To Reproduce**
Set up launch.json like this:

    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "serverInstance": "NAV13-3",
            "port": 7050,
            "authentication": "Windows",
            "startupObjectId": 78551,
            "startupObjectType": "Page",
            "breakOnError": true,
            "schemaUpdateMode": "Synchronize",
            "launchBrowser": false,
        },
        {
            "type": "al",
            "request": "launch",
            "name": "Microsoft cloud sandbox",
            "startupObjectId": 78551,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": false
        }
    ]

When publishing, the selection dialog briefly pops up and is immediately closed.

**Expected behavior**
Behaviour as before in earlier VSCode version: Let user select the configuration.

**Versions:**
 - AL Langauge: 3.0.115791

**Comment by JohanStenberg100** [comment]
Hi @papillon, thanks for reporting this issue. This issue has been fixed in our master branch and will be shipped in a future release. I'll close this issue now, please keep an eye out for new releases to the extension on the VS Code marketplace.

**Comment by JohanStenberg100** [comment]
FYI @papillon tracking this now under #4861
