### ISSUE TITLE
All Extension pages are showing as blank

### ISSUE THREAD

**Issue by Rachit14** [Microsoft/AL#4848]
I am using Docker to test my app and I am facing a challenge after publishing my app that all pages are showing as blank pages with no controls appearing on them.

I cannot perform any operations on them. Same pages were looking fine on Business Central onPrem version earlier(CU03). Please suggest if I am missing something here. On Role Tailored Client same page is showing as chart with no permission to convert them to the list. Attached screenshots below-

**RTC Screenshots**
![2019-04-05 18_45_22-Window](https://user-images.githubusercontent.com/3817269/55630321-08458300-57d3-11e9-9fa8-7173d3346c2e.png)

**WebClient Screenshots**
![2019-04-05 18_41_13-Edit - Retail Tender Global - Dynamics 365 Business Central](https://user-images.githubusercontent.com/3817269/55630118-82c1d300-57d2-11e9-9369-35f8dceba706.png)

**Comment by wisa1** [comment]
I have the exact same problem using
mcr.microsoft.com/businesscentral/sandbox:at-ltsc2019

**Comment by thpeder** [comment]
Hi @Rachit14,
Does this happen for all your pages or just some of them from your extension?
Could you please provide which versions seen in "System Information" page in the client.

A wild guess is that you are missing [ApplicationArea](https://docs.microsoft.com/en-us/dynamics-nav/applicationarea-property) for your page controls.

**Comment by Rachit14** [comment]
Hi @thpeder ,
Thanks for this clue. Yes ApplicationArea property was missing from controls. This issue is now resolved.

**Comment by wisa1** [comment]
That resolved it for me too @thpeder, thank you. 
For anyone coming across this issue, thinking this would not apply to CAL Pages - it does - the Application Area Property is also available in CAL, use it.

Suggestion: Can we get squiggly lines in VSCode when we create Page-Fields that would never be shown?
