### ISSUE TITLE
appSyntax.json Warning message?

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#4849]
All of a sudden today I have this warning message when I start VS Code. Where is this coming from?

It seems to only come up if I have app.json (1 or more as I have 6 extensions in my workspace), close VS Code with app.json open (unmodified) in the editor and then re-open VS Code.  It also has appeared when I do a build (Ctrl+Shift+B) with an app.json open.

FYI, VS Code 1.33 was installed today.

> String is not a URI: URI with a scheme is expected.

> {
> 	"resource": "/c:/Users/todd.scott/.vscode/extensions/ms-dynamics-smb.al-3.0.115791/syntaxes/appSyntax.json",
> 	"owner": "_generated_diagnostic_collection_name_#0",
> 	"severity": 4,
> 	"message": "String is not a URI: URI with a scheme is expected.",
> 	"startLineNumber": 2,
> 	"startColumn": 11,
> 	"endLineNumber": 2,
> 	"endColumn": 44
> }
 
VS Code Information

> Version: 1.33.0 (user setup)
> Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
> Date: 2019-04-04T15:14:28.026Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

AL Language Information

> Name: AL Language
> Id: ms-dynamics-smb.al
> Description: AL development tools for Dynamics 365 Business Central
> Version: 3.0.115791
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by JohanStenberg100** [comment]
Hi @GreatScott000, thanks for filing this issue. This seems to be a VS Code issue, but we will further investigate and determine how to proceed.

**Comment by konysh** [comment]
I had the same problem when I had 2 launch specifications. When I removed one of them it works. Just tried.

**Comment by TheDenSter** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/23434319/56029168-19821880-5d1a-11e9-8df3-fb3a43594573.png)
Freshly updated Docker image, freshly updated navcontainerhelper, and installed the vsix from the container.

F5 or Ctrl+F5 are not responding. It builds the app file, but it seems to just ignore the publish command. The 'compilation started' flashes across the output window and then it blacks out, and then nothing further happens.

**Comment by michielhageman** [comment]
Same here guys. Try to publish my 'old' ;-) BC130 apps to a brand new BC140 instance. 
AL version: 3.0.106655
BC version: platform 14.0.29530.0 + application 29537 (NL Dynamics NAV 14.0)

**Comment by davmac1** [comment]
I am getting the same error with a new never published extension for NAV 2018 CU10 - AL 0.12.17720.
The id is a GUID, but the error implies it is expecting a web address.

**Comment by MajorBarf** [comment]
Getting this error with an existing extension that was previously OK before VS Code 1.33.0 was installed. I'm publishing to a local database using Windows authentication. The error only appears if you open the app.json file so you can workaround by saving app.json, then restart VS Code and make your AL changes without touching app.json again.

Found that <F5> will still publish the extension despite this message but will not open the client (launch.json error) - which means that you can't use the debugger!!!

**Comment by GreatScott000** [comment]
Issue continues to occur on the lastest public versions of VS Code (1.34) and AL Extension 3.0.1.126610

**Comment by bbrown5962** [comment]
I am using VS code 1.35 and the issue still seems to be happening.

**Comment by tinfister** [comment]
Same here. Any info when will this be fixed?

**Comment by DEDhead** [comment]
You can get around the issue by putting any valid URI in the "id" field in the appsyntax.json file.  I simply copied the value from the "$schema" field into the "id" field and saved the file. The extension then builds without error, publishes and launches the browser.

**Comment by atoader** [comment]
This will be fixed for the Fall 2019 release.
