### ISSUE TITLE
Cannot use DotNet on Extension

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4853]
Hello

When i try to use XMLdocument from DotNet y get the error "The type or method 'DotNet' cannot be used for 'Extension' development.AL(AL0296)" is there a way to achieve this

**Comment by rvanbekkum** [comment]
You can use DotNet types only if you are developing for on-premise only. For this you will need to set the `target` property to "Internal" in the app.json file of your project.
Please see:  https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al

If your solution is supposed to be for on-premise only, then you should look into using built-in types and objects.
For your case, you might also want to look into the new AL type "XmlDocument" (see: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmldocument/xmldocument-data-type)

**Comment by adrianordonez** [comment]
Thanks for the reply this help me so much

**Comment by JohanStenberg100** [comment]
Thanks @adrianordonez for filing this issue. As @rvanbekkum correctly points out, you can't invoke `dotnet` code directly on BC servers. Thanks
