### ISSUE TITLE
rad.json

### ISSUE THREAD

**Issue by jeffgit** [Microsoft/AL#4854]
After I compile the AL against the sandbox, I noticed there is additional file called rad.json created, I don't documentation about this. I heard it's something to do with incremental publish but is there official document from Microsoft for how to use it?

- AL Extension Version: 
3.0.115791

- Server Version: 
13.4 (29682)

**Comment by JulienDecottignies** [comment]
You can find a documentation here: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rad-publishing

**Comment by JohanStenberg100** [comment]
Hi @jeffgit, thanks for filing this issue. As @JulienDecottignies kindly commented, you can read more about this in our official documentation. I'll go ahead and close this issue now, thanks.
