### ISSUE TITLE
could not download symbols

### ISSUE THREAD

**Issue by 1870824vivek** [Microsoft/AL#4856]
Launch.json file
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "serverInstance": "BC130",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }
    ]
}

App.json 

{
  "id": "e7653ec6-06f0-4525-bb29-dfcddc683683",
  "name": "ALProject3",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject3.com/help/",
  "showMyCode": true,
  "runtime": "3.0"
}

Errors while downloading symbols. This is On premise BC version.

**Comment by JohanStenberg100** [comment]
Hi @1870824vivek, can you verify that your server instance is named `BC130`? Thanks

**Comment by qutreson** [comment]
@1870824vivek which version of BC are you targeting? If this is one of the CU of the Fall 18 release, then you should use 13.0.0.0 as 14.0.0.0 will only work for BC on the April 19 release

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
