### ISSUE TITLE
Unable to Create Sandbox Environment from Production Environment 

### ISSUE THREAD

**Issue by mustafachohan** [Microsoft/AL#4857]
**Describe the bug**
Unable to create the sandbox environment from production environment

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Go to bc admin center
2. create new environment
3. select type sand box 
4. select copy environment

**Expected behavior**
Environment should created; but it starts preparing and after that it starts removing. Environment is not created. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49344354/55671305-ef56d380-589f-11e9-9677-9342ec4d2a14.png)

![image](https://user-images.githubusercontent.com/49344354/55671309-f8e03b80-589f-11e9-9eb7-4d92d37e265c.png)

**Versions:**
13.5.29.483.0

 - AL Langauge: 

 - Business Central:

**Comment by Mr-Pingu** [comment]
Same here, still stuck on 13.3 though.

**Comment by thpeder** [comment]
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
