### ISSUE TITLE
Generic charts creation permission

### ISSUE THREAD

**Issue by ac2707** [Microsoft/AL#4860]
You do not have permission to insert '' charts because the tenant is mounted with the application database as read-only. Contact your system administrator."
![charts](https://user-images.githubusercontent.com/49182510/55708638-044c7780-5a04-11e9-8eba-d59203b445d4.png)

Can someone advice please what permissions to be updated for this ?

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
