### ISSUE TITLE
Select server dropdown disappears

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#4861]
**Describe the bug**
The dropdown to select a server disappears immediately when you want to publish and you have multiple configurations in launch.json.
The dropdown works as expected for downloading symbols.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a new project with AL:Go!
2. Add a local server to the launch.json
3. Add a cloud sandbox to launch.json
4. Download symbols (the dropdown let you select the server to download from)
5. Publish the app. The dropdown appears for a split second but disappears immediately

**Expected behavior**
The dropdown should let you select to which server you want to publish.

**Screenshots**
I'm talking about this dropdown:
![image](https://user-images.githubusercontent.com/19155831/55708823-2d124400-59e7-11e9-8d39-3091b4c39f99.png)

**Versions:**
 - AL Langauge: 3.0.106655 (from sandbox image) and 3.0.115791 (from marketplace)
 - Business Central: Platform 14.0.29530.29573 + Application 31096 (W1 14.0)
- VS Code: 1.33.0

**Comment by nicolassaleron** [comment]
Hello,
I have also noticed that since the last VSCode update.

**Comment by FSharpCSharp** [comment]
Unfortunately it is no longer displayed here. This is really a bit strange.

**Comment by calcifieddeveloper** [comment]
Hi,
I am having the same issue too..

**Comment by srenders** [comment]
I'm noticing it too as from today...

**Comment by jwikman** [comment]
@JohanStenberg100 any news on this?

We started to see this behavior after VSCode got updated to v1.33, but it is still present in VSCode v1.34.
We where running the same version (3.0.126610) of AL Language extension just fine before the update of VSCode, so there seems to be some incompatibility between the current AL Language extension and the recent builds of VSCode.

All my colleagues are reporting the same issues. As long as you're having only one configuration in launch.json it works, but as soon as you add another configuration and the Quick Pick (where the server should be selected) you're not able to select anything. Sometimes we see the quick pick flashing away, but not always.

If I debug the extension I see that the showQuickPick function call below (in out\src\services\launchService.js) doesn't return any item when this occur. If I step into (F11) showQuickPick everything works fine, if I step over (F10) showQuickPick the issue occur.

```
 vscode.window.showQuickPick(items, options).then(item => {
                if (item) {
                    const i = items.indexOf(item);
                    if (i !== -1) {
                        resolve(configurations[i]);
                    }
                    else {
                        reject();
                    }
                }
                else {
                    reject();
                }
```

So there seem to be some issues with vscode.window.showQuickPick, but not always...

Are you still not able to repro?

**Comment by jwikman** [comment]
@JohanStenberg100 I think I found a solution to this issue. Note,  "a" solution, maybe not "the" solution. ;)

Anyways, there seems to be some change of focus that are messing with us. 

If I add the ignoreFocusOut option to the showQuickPick call, it seems to work!

```
chooseLaunchConfiguration(configurations) {
        return new Promise((resolve, reject) => {
            const items = configurations.map(x => ({
                label: x.name,
                detail: this.formatLaunchConfiguration(x),
                description: ""
            }));
            const options = ({
                placeHolder: resources_2.default.chooseServerPrompt,
                matchOnDetail: true,
                ignoreFocusOut: true // <<-- Added line
            });
            vscode.window.showQuickPick(items, options).then(item => {
                if (item) {
                    const i = items.indexOf(item);
                    if (i !== -1) {
                        resolve(configurations[i]);
                    }
                    else {
                        reject();
                    }
                }
                else {
                    reject();
                }
            });
        });
    }
```

So if someone wants to workaround this until this gets fixed in the AL Language extension, you just need to find your launchService.js file (probably in "%USERPROFILE%\.vscode\extensions\ms-dynamics-smb.al-3.0.126610\out\src\services\") and add this line.

**Comment by JohanStenberg100** [comment]
Hi @jwikman! This issue has been fixed in our master branch and we will try and get it into the next CU for Spring 2019. Thanks

**Comment by jwikman** [comment]
> Hi @jwikman! This issue has been fixed in our master branch and we will try and get it into the next CU for Spring 2019. Thanks

"Next" as in CU1 or CU2?

**Comment by JohanStenberg100** [comment]
CU1 is about to be released so it might not get into that update. If not, CU2 will contain it, thanks.

**Comment by jwikman** [comment]
Ok, glad I found a workaround then :)

**Comment by JohanStenberg100** [comment]
Good! Note that our insider builds for Fall 19 is not out yet, when those are out you can run the VS Code extension from there and you'll get the latest updates much faster. ETA on that is 2-3 weeks.

**Comment by rvanbekkum** [comment]
The issue seems to be resolved in BC14, CU02.

**Comment by jwikman** [comment]
At least now (v3.0.152816) the dropdown list is usable, but there is still a focus issue (the same issue as I had with my workaround above).
I'm not able to select anything with the keyboard, since the focus is moved to the Output window right after the dropdown is shown. But using the mouse works at least.

**Comment by atoader** [comment]
This issue has been fixed in the Wave 2 2019 release. Please open a new issue if you encounter any problems.
