### ISSUE TITLE
SMTP Mail Setup invalid format of guid string. the correct format of the guid string is :CDEF 7890-ABCD-0123-

### ISSUE THREAD

**Issue by srkkoneti** [Microsoft/AL#4863]
Set the SMTP Email Setup.
![image](https://user-images.githubusercontent.com/39953344/55718284-ffde8980-5a18-11e9-8812-7e83503b1cc5.png)
Test Email Setup worked successfully.

Now when we try to generate an email from Page, it's getting following error.

![image](https://user-images.githubusercontent.com/39953344/55718028-57c8c080-5a18-11e9-933d-46061bc6b351.png)

Note: Also tried with Outlook setup too. It's also getting same error.

Tried with below version (AL Language Extensions)
Al Language : 3.0.106655,  3.0.115791

  "platform": "14.0.0.0",
  "application": "14.0.0.0",

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
