### ISSUE TITLE
Purchase Invoice error

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#4864]
**Describe the bug**
Error while opening Purchase Invoice page

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Go to Purchase Invoice Page
2. Click New/Edit

**Expected behavior**
Page should open without error

**Screenshots**
![image](https://user-images.githubusercontent.com/23735402/55721480-1a1c6580-5a21-11e9-8c27-9e8f59800058.png)

**Versions:**

 - AL Langauge: 3.0.106655

 - Business Central: 14.0.29537.0

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
