### ISSUE TITLE
Unable to get property 'NativeSealedControl' of undefined or null reference (Error opening BC Web Client)

### ISSUE THREAD

**Issue by lucacostamagnaeos** [Microsoft/AL#4865]
**Describe the bug**
One of the users can't access to Business Central Web Client.
Using Internet Explorer this is the error that appears (translated in english):

> Unable to get property 'NativeSealedControl' of undefined or null reference (Error opening BC Web Client)"

Using Google Chrome, no error appears but the loading screen freezes.

**Screenshot**
![image](https://user-images.githubusercontent.com/45294593/55724994-eb948f80-5a0c-11e9-8407-21ccf670db5b.png)

**Version:**
 Business Central CU02

**Comment by lucacostamagnaeos** [comment]
This is the error shown in the Event viewer:

[Event error.zip](https://github.com/Microsoft/AL/files/3054348/Event.error.zip)

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
