### ISSUE TITLE
New API Call Confirm

### ISSUE THREAD

**Issue by lksg** [Microsoft/AL#4866]
Hi, 
I assume this message is new since the latest major:
![image](https://user-images.githubusercontent.com/44197501/55728931-7083a700-5a15-11e9-9e6b-ffde31fe4830.png)

Where is this information stored?
Is there a way to preconfigure domains so the user doesn't have to confirm them?
Is there a way to make the displayed message more expressive? i.e. tell the user which domain is used.

local procedure MyProcedure()
    var
        client: HttpClient;
        response: HttpResponseMessage;
    begin
        client.Get('google.com', response);
    end;

This information would be very helpful to us, thanks.

**Comment by ajkauffmann** [comment]
I don't think it has been documented somewhere, but I wrote a blog post about this a while ago:
https://www.kauffmann.nl/2018/11/05/outbound-http-calls-blocked-in-business-central-sandbox/

**Comment by lksg** [comment]
Thanks ajkauffmann, that indeed cleared up most of my questions.
