### ISSUE TITLE
On open rolecenter "Power BI Report Spinner Part" errors

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#4867]
**Describe the bug**
Deploy debug from VS Code (F5) will have the debugger stop in "Power BI Report Spinner Part"

**To Reproduce**
Deploy anything and debug from VS Code (F5)

**Expected behavior**
No error on startup

**Screenshots**
![image](https://user-images.githubusercontent.com/6465685/55788662-03295200-5ab9-11e9-9a50-4d9be525f935.png)

**Versions:**

 - AL Langauge:  3.0.106655

 - Business Central: Version: Platform 14.0.29530.29573 + Application 31096 (NL Dynamics NAV 14.0)

**Comment by qutreson** [comment]
Hi @JSebastianN, do you have `breakOnError` set to to true or not set (the default value is true) in your launch configuration (see [launch.json](
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files))? 

This property enables you to break on errors when debugging. In this case, if you are using this page part (or if it gets executed) on SaaS, it seems to be the expected behavior to raise an error (looking at the AL Code) and break there.

**Comment by JSebastianN** [comment]
Hi, thanks for replying.

Its a Docker SaaS.
It is a default part/behaviour.

ERROR should be avoided, at least in a page page on a rolecenter IMO :)

**Comment by MarcHansenMicrosoft** [comment]
I do not see a general problem in having errors in the role center.
Could you elaborate on why it should be avoided?

**Comment by JSebastianN** [comment]
Hello Marc

When deploying from VS Code for debugging.
The web client will start up.

The first thing that will happen is the debugger stopping at such errors like this, since they are run by the rolecenter starting up.

The developer is about to test/debug a customization but will have base system will throw an error on it's own as the first thing.

This makes for an unnecessarily ugly experience.

ERROR CAN have it's place, but rolling back changes on start-up is perhaps not the finest approach.

I any case, this is only my personal experience and opinion.

**Comment by MarcHansenMicrosoft** [comment]
Thanks for you feedback.
We will not be added this rule.
But if we want to improve the first time debug experience would defaulting breakOnError = FALSE be a better change?

**Comment by JSebastianN** [comment]
Thanks

-
No getting fast up and running with the debugger enabled is perfect.

-
Perhaps a review of ERROR that are really meant as EXIT's instead.

Rolling back changes can be warranted, but I have seen it in Role center parts and last time in a wizard.
That seems weird to me.
