### ISSUE TITLE
AL Snippet with intellisense

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#4868]
I created a simplee Snippet to create a Event Subscriber for Tables

	"EventSubcriber_Table":{
		"prefix": "fscEventSubscriber_Table",
		"body": [
			"[EventSubscriber(ObjectType::Table, Database::\"${1:Object}\", '${2:Publisher}', '${3:Field}', true, false)]",
			"local procedure Tab$1_$0$2_$3()",
			"begin",
			"",
			"end;"
		],
		"description": "EventSubscrier for Tables"
	}

The problem is, when I insert the snippet and want to Subscribe the table "Payment Terms". I type Pay and the intellisense opend with the suggestion Payment Terms. When i accept it with enter I got the following
[EventSubscriber(ObjectType::Table, Database::"Payment Terms", '${2:Publisher}', '${3:Field}', true, false)]
local procedure Tab**Pay"Payment Terms"**_$0$2_$3()",
begin
end;

In the second line is now the value who I typed and the value who I got from the intellisense

**Versions:**
 - AL Langauge: 3.0.107312

**Comment by Joriek** [comment]
Hello,

I've also found this to be quite difficult to handle. I discovered a VS Code extension with a lot of useful snippets which might help you:
https://marketplace.visualstudio.com/itemdetails?itemName=BartPermentier.al-toolbox

Hope you like it.

Regards,
Joriek
