### ISSUE TITLE
Intellisense when instantiating XML elements

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#487]
When I try to instantiate an XML element, the intellisense, will not help me finish the last part of the statement. If I start on a new line the intellisense, will help type XmlElement, but on the right side of the assignment keyword, it will not work until after I have written the entire class name "XmlElement".
![8a427130-529d-4465-9d64-3108acc1fa68](https://user-images.githubusercontent.com/2745613/29173194-d3ba875a-7de2-11e7-9006-25a78aa51a3d.GIF)

**Comment by thpeder** [comment]
It is fixed in the next update. Thanks for reporting it.
![xmlintellisense](https://user-images.githubusercontent.com/24276180/29183373-b4953bd4-7e02-11e7-9cef-72a3416efcbd.gif)
