### ISSUE TITLE
Codeunit "Certificate Management" method 'GetCertAsBase64String' cannot be used for 'Extension' development.AL(AL0296)

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4872]
Hello

I am trying to extend the e.Invoice functionality for Mexico, when i try to use Codeunit "Certificate Management" method 'GetCertAsBase64String' i get the error "cannot be used for 'Extension' development.AL(AL0296)" i look into the codeunit and copy the method in the line IF NOT ISOLATEDSTORAGE.GET(IsolatedCertificate.Code, GetCertDataScope(IsolatedCertificate), CertString) THEN enters the if, my question is what type of variable is ISOLATEDSTORAGE i do not find it

I put my procedure GetCertAsBase64String that copy from Certificate Management

local procedure GetCertAsBase64String(IsolatedCertificate: Record "Isolated Certificate"): Text
    var
        CertString: Text;
        
    begin
        CertString := '';
        IF NOT ISOLATEDSTORAGE.GET(IsolatedCertificate.Code, GetCertDataScope(IsolatedCertificate), CertString) THEN
            ERROR('Error al leer el certificado');
        EXIT(CertString);
    end;

**Comment by qutreson** [comment]
Hi @adrianordonez you can read more about IsolatedStorage on our [online documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-isolated-storage).

**Comment by qutreson** [comment]
Closing this issue as this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
