### ISSUE TITLE
Sales Tax - Tax Above and Below Maximum should have 1:4 Decimal places.

### ISSUE THREAD

**Issue by simcrest** [Microsoft/AL#4873]
Standard BC has a default of DecimalPlaces 1 : 3 in Tax Above Maximum and Tax Below Minimum (Table 322, field 5 and 6), however many tax jurisdictions have up to 4 decimal places. We are not allowed to make a change to this with an extension.
Please expand Decimal Places to at least 1 : 4 to support these customers getting into the new BC extensions.
Attached examples of rates for New Mexico, USA:
![NewMexico](https://user-images.githubusercontent.com/15910725/55837524-a8f7b380-5aef-11e9-95d2-679e3e30deb3.png)

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
