### ISSUE TITLE
Codeunit "Certificate Management" method 'GetCertAsBase64String'

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4874]
Hello

i cannot Use Certificate Management.GetCertAsBase64String method for extensions for this i create my own becuase i need the certificate that the user Upload, when i debug the native BC the Certificate Management.GetCertAsBase64String get the certificate string with no problems but when i call my method do not find the data on the ISOLATEDSTORAGE.GET i am sending the same parameters that the native code

i am loosing something to call the get from ISOLATEDSTORAGE correctly?

**Comment by qutreson** [comment]
Isolated storage enables to store data with different datascopes which can be User, Module, Company or CompanyAndUser, which means that your app might not be allowed to retrieve the secret stored by the one from which you copied the code. There are some nice blog posts from partners that you can read about this functionality.

To get help for your question please use one of the following resources as some people might already have found a way around this limitation:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Closing the issue as this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

**Comment by adrianordonez** [comment]
The data storage is configure as company and User and when i send it on the get i send it the rigth scope and nothing is retrieve this is why i am asking if something is missing

**Comment by adrianordonez** [comment]
and no i try with the other two options (user and company) and i have the same result with natvie code retireve the data and with my code don't
