### ISSUE TITLE
NAV & Business Central Web Client - Possibility to add multiple filters on option values.

### ISSUE THREAD

**Issue by lucacostamagnaeos** [Microsoft/AL#4875]
**Is your feature request related to a problem? Please describe.**
In NAV 2018 and Business Central RTC, users can easily add filters on multiple option values.
For example:
![image](https://user-images.githubusercontent.com/45294593/55862785-7397a800-5b79-11e9-8a00-4671dcf5c962.png)

In the Web Client users can not apply this kind of filter.

**Describe the solution you'd like**
I would like to have the same feature on the Web Client, because I think it's quite crucial in some cases.

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
