### ISSUE TITLE
Codeunit "Certificate Management" method 'GetCertAsBase64String'

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4878]
Hello

i cannot Use Certificate Management.GetCertAsBase64String method for extensions for this i create my own becuase i need the certificate that the user Upload, when i debug the native BC the Certificate Management.GetCertAsBase64String get the certificate string with no problems but when i call my method do not find the data on the ISOLATEDSTORAGE.GET i am sending the same parameters that the native code

The data storage is configure as company and User and when i send it on the get i send it the rigth scope and nothing is retrieve this is why i am asking if something is missing

i try with the other scopes and i get the smae result with natvie code retireves the data and with my code don't

i am loosing something to call the get from ISOLATEDSTORAGE correctly?

**Comment by PooyaKharamesh** [comment]
My first guess is that you call the Set function and Get Function on IsolatedStorage from 2 different application (maybe base app and your extension). Isolated Storage **always** respect the application boundaries. So For example if you set the scope to CompanyAndUser it means that the value is accessible for one specific user in only one company and Get should be invoked from the same app that sets the value.

/Pooya

**Comment by qutreson** [comment]
@adrianordonez the IsolatedStorage is behaving as expected (the [online documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-isolated-storage) also mentions that IsolatedStorage provides isolation between extensions). Concerning your original issue #4872, you should consider finding another way of implementing the scenario you want to achieve. 

The best resource for you is to ask the developer community on one of these forums:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Closing this issue as this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.
