### ISSUE TITLE
FindSet The record in table already exists in Business central

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4880]
Hello

I am inserting on buffer some data the buffer is "Document Line" and en other part of the code i want o iterate on the records of that buffer (4 lines in example) with the following code

TempDocumentLine.SETRANGE("Document No.","No.");
TempDocumentLine.SETFILTER(Type,'<>%1',TempDocumentLine.Type::" ");
IF TempDocumentLine.FINDSET THEN
REPEAT
TotalTaxes := TotalTaxes + (TempDocumentLine."Amount Including VAT" - TempDocumentLine.Amount);
TotalDiscount := TotalDiscount + TempDocumentLine."Line Discount Amount";
UNTIL TempDocumentLine.NEXT = 0;

But when reach the FindSet line i got the error "The record in table Document Line already exists. Identification fields and values: Document No.='103010',Line No.='10000'"

How can achieve this

**Comment by AskeHolst** [comment]
You are not seeing the true problem due to buffered inserts, the service waits until the findset to do that actual insert that fails. 
Turn of buffered inserts on the BC service and the debugger will show you the real problem.

**Comment by adrianordonez** [comment]
Thanks for the reply 
where can i turn that feature?

**Comment by adrianordonez** [comment]
Thanks for the reply i was missing the reset for the buffer
