### ISSUE TITLE
error AL0133: Argument 1: cannot convert from 'Record "Record Link"' to 'var __MissingTypeSymbol_

### ISSUE THREAD

**Issue by eknraw** [Microsoft/AL#4881]
**Describe the bug**
Using WriteRecordLinkNote or ReadRecordLinkNote in Codeunit "Type Helper" results in error "error AL0133: Argument 1: cannot convert from 'Record "Record Link"' to 'var __MissingTypeSymbol_" on publishing extension. 

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1.  Add the following function to an object: 
```
    procedure WriteRecordLink();
    var
        RecLink: Record "Record Link";
        TypeHelper: Codeunit "Type Helper";
    begin
        RecLink.Init();
        RecLink."Link ID" := 0;
        TypeHelper.WriteRecordLinkNote(RecLink, 'Text');
        RecLink.Insert();
    end;
```
2. Publish

**Expected behavior**
Extension successfully publishes.

**Versions:**

 - AL Langauge: 3.0.115791

 - Business Central: 14.0.29537.31154

**Comment by thpeder** [comment]
Hi @eknraw,
I'm not able to reproduce your issue.
Could you tell more about your setup.

Thanks,
Thomas

**Comment by Joel-NAVDev** [comment]
@thpeder see https://github.com/Microsoft/AL/issues/4795#issue-426467994

**Comment by eknraw** [comment]
Just rebuilt the container with image pullled today 4/12/2019  mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019

Version: 14.0.29537.31313-US
Platform: 14.0.29530.31247
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)

I'm putting that function into a codeunit.

I could probably put a solution together that included a container creation script.  What else would you need to know about the environment?

**Comment by eknraw** [comment]
It looks like this might be navcontainerhelper related.  If I use navcontainerhelper version 0.5.0.2 instead of 0.5.0.11 this is not an issue.

**Comment by eknraw** [comment]
Related: #4795.  The enableSymbolLoading parameter on New-NavContainer (navcontainerhelper) causes the application symbols to be unpublished.
