### ISSUE TITLE
E-Invoice for Mexico Business Central

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/AL#4882]
Hello 

I am using e-Invoice localization for Mexico, i comunicate with the PAC correctly and the Pac Webservice return me the xml in the correct format but when the code reach the following line FileManagement.BLOBImportFromServerFile(TempBLOB,QRCodeFileName); in procedure CreateQRCode(QRCodeInput : Text;VAR TempBLOB : Record TempBlob) for code unit "E-Invoice Mgt." return the Error "Files outside of the current user's folder cannot be accessed. Access is denied to file C:\windows\TEMP\tmpA155.tmp."

i already try to give full access to TEMP to Everyone but i got the same error

I create my enviroment from a Business central 365 with the option Sanbox(container) Host locally

**Comment by adrianordonez** [comment]
Hello i try the same test with the online enviroment of the customer and get the same error just on different folder "Files outside of the current user's folder cannot be accessed. Access is denied to file  D:\SvcFab\_App\NAVApplicationType_App8\temp\tmp7221.tmp."

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
