### ISSUE TITLE
Error when upload extension on production environment

### ISSUE THREAD

**Issue by mitreadaniel** [Microsoft/AL#4883]
**Describe the bug**
I'm trying to upload an extension on production environment(https://deonline.bc.dynamics.com) but i received and error when i'm doing that. Error : "Object reference not set to an instance of an object. Page View - Extension Deployment Status has to close". What could be the cause ?

**To Reproduce**
1. Go to Extension Management.
2. Upload Extension.
3. Deployment Status
4. Error

**Expected behavior**
I expected that the extension to be uploaded.

![appjson](https://user-images.githubusercontent.com/24981291/55939275-b02cd780-5c3d-11e9-8b3f-573f81948c46.jpg)
![launchjson](https://user-images.githubusercontent.com/24981291/55939280-b28f3180-5c3d-11e9-90c6-b34f37f29460.jpg)
[system information error.docx](https://github.com/Microsoft/AL/files/3067458/system.information.error.docx)

**Versions:**
 - AL Langauge: 3.0.115791
 - Business Central: 13.3.27437.0-NL

**Comment by mitreadaniel** [comment]
I attached the error from system information in that word document and also the app.json and launch.json files

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
