### ISSUE TITLE
Enable Txt2al tool to create .rdl files instead of .rdlc

### ISSUE THREAD

**Issue by isatech-jremaud** [Microsoft/AL#4884]
**Is your feature request related to a problem? Please describe.**
Txt2Al generate .rdlc file when converting report.

**Describe the solution you'd like**
A way to choose the extension of the layout report : .rdl ou .rdlc

**Describe alternatives you've considered**
Enable the Report Builder to read .rdlc report...

**Additional context**
N/A

**Comment by srenders** [comment]
I don't think we really need this option, since you can configure to choose VSStudio or ReportBilder to open one or the other, for example: https://thinkaboutit.be/2019/01/how-do-i-configure-my-rdlc-layout-designers-for-vscode/

**Comment by isatech-jremaud** [comment]
Alright, thanks for the link to your blog article ! 😊
