### ISSUE TITLE
'CurrFieldNo' is inaccessible due to its protection levelAL(AL0161)

### ISSUE THREAD

**Issue by FSchneiderYav** [Microsoft/AL#4885]
**Describe the bug**
I have a new page with Warehouse Receipt Line as SourceTable.
When I use the CurrFieldNo variable i got the following error.

(global) CurrFieldNo: Integer
'CurrFieldNo' is inaccessible due to its protection levelAL(AL0161)

**Versions:**
 - AL Langauge: 3.0.107312

**Comment by qutreson** [comment]
@FSchneiderYav can you share with us a short code snippet we can use to reproduce the issue?

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by TomHedegaardTrimit** [comment]
How was this solved and where to find the solution comment ?
