### ISSUE TITLE
Test tool crashes under load

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#4887]
**Describe the bug**
We have 80 unit tests we run on an ISV solution.
Select all and run, will crash the Web client.
"Integration Record" table is locked herafter.

Running the exact same tests from RTC gives no problem at all.

**To Reproduce**
Have lots of unit tests with posting and XML handling.
![Test Tool Crashes](https://user-images.githubusercontent.com/6465685/56030799-0d985580-5d1e-11e9-8b01-b66013bd381f.png)

**Expected behavior**
No crashes

**Screenshots**
WEb client crash and the following record locking.

**Versions:**
 - AL Langauge: 3.0.106655
 - Business Central: Version: Platform 14.0.29530.31247 + Application 31313 (W1 Dynamics NAV 14.0)

**Comment by AskeHolst** [comment]
Same as #4823

**Comment by JohanStenberg100** [comment]
Closing since same as #4823 as @AskeHolst kindly pointed out. @JSebastianN Please add any additional information you may have in the referenced issue. Thanks!
