### ISSUE TITLE
After importing Configuration Package and Applying it, Restart Docker is needed

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#4888]
**Describe the bug**
After importing Configuration Package and Applying it, Restart Docker is needed.
We import the W1 Extended Cronus data in other country specific builds.

But running our units tests without first restarting the Docker container, will result in CRL exceptions.

**To Reproduce**
1 - Use the build-in pre configured Extended configuration package
OR
1 - Spin up a W1 and a country like DEU.
Take the NAV14.0.W1.ENU.EXTENDED.rapidstart from W1 container and import it in DEU.

2 -
Do NOT stop and start the docker container.
Use the Test Tool to run an extended amount of tests in one-go.

**Expected behavior**
No Crash

**Versions:**
 - AL Langauge: 3.0.106655
 - Business Central: Version: Platform 14.0.29530.31247 + Application 31313 (W1 Dynamics NAV 14.0)

**Comment by OldNavDog** [comment]
Nevermind Powershell; I have a similar problem when attempting to Apply Predefined Configuration Packages using the GUI actions from the Web Client "Configuration Packages" Page. The Web Client Crashes every single time; no matter the Configuration Package, and no matter how I try different sequences of steps. When I click "Apply", after a few seconds, the Client crashes.

Also, Interestingly, the "EVAL" and "EXTENDED" Packages will "Validate" with the "Validate Package" Action; but the "STANDARD" Package CONSISTENTLY Crashes the Web Client during the "Validation" Process (from the "Package Card"). But they ALL fail the "Apply" step, with or without Evaluation first.

This just started happening a couple of weeks ago, when I updated my On-Prem BC Sandbox environment (US version) and AL VSC "Extension". With the previous version, I had no problems Importing and Applying the packages listed below.

These are the Configuration Packages I have been trying. I have tried every combination, in every order, singly, and in combination, all with the same result:

Code                                  Product Version
US.ENU.EVALUATION        NAV14.0
US.ENU.EXTENDED            NAV14.0
US.ENU.STANDARD           NAV14.0


Here is my AL Language Version:

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.121490
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
