### ISSUE TITLE
What Version License is required for BC docker environment ???

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4890]
Hello,

I have a BC onPrem license  now i am installing the Docker for Testing Extension app. so i am using the BC onPrem License while creating the new container but it is giving the warning like below.

WARNING: This license is not compatible with this version of Business Central.

I have published my app in the docker environment successfully, but the extension which i installed it not showing any page or customization in the role tailored client. 

is this is license issue ? if yes which license i have to use.

Thanks & Regards,
Sainath.

**Comment by PooyaKharamesh** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
