### ISSUE TITLE
OnAfterValidate not working for Unit Cost(LCY).

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#4891]
**Describe the bug**
**OnAfterValidate** trigger for the **Unit Cost(LCY)** field on **Sales order Subform** is not working, while extending this page through Page Extension.

**To Reproduce**
Modify **Unit Cost(LCY)** field on **Sales Order Subform**. In modification, write some code on **OnAfterValidate** trigger of this field.

**Expected behavior**
OnAfterValidate should work.

**Versions:**
 - AL Langauge: 3.0.115791 
 - Business Central: CA Dynamics NAV 13.5 (31011)

NOTE : Its also not working while achieving this through EventSubscription.

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
