### ISSUE TITLE
Could not download symbols. Please see the Visual Studio Code output log for more details.

### ISSUE THREAD

**Issue by NavTechAnas** [microsoft/AL#4895]
[2019-04-13 13:01:45.59] Using reference symbols cache path: c:\Users\anas.mohammad\Documents\AL\ALProject13\./.alpackages
[2019-04-13 13:01:45.61] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2019-04-13 13:01:45.62] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-04-13 13:01:47.57] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-04-13 13:01:47.82] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-04-13 13:01:47.85] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**Comment by NavTechAnas** [comment]
App. jason file is

{
  "id": "4b65445b-99bd-4c5c-a13e-e406dffafd0a",
  "name": "ALProject13",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject13.com/help/",
  "showMyCode": true,
  "runtime": "3.0"
}

**Comment by qutreson** [comment]
Hi @NavTechAnas can you provide us with more information?
Which version are you using for the AL compiler, VS Code and Business Central? 
Are you targeting OnPrem, a docker image or sandbox deployments, etc?

What if you try specifying 13.0.0.0 as the version for platform and application?

**Comment by ajansari** [comment]
> Hi @NavTechAnas can you provide us with more information?
> Which version are you using for the AL compiler, VS Code and Business Central?
> Are you targeting OnPrem, a docker image or sandbox deployments, etc?
> What if you try specifying 13.0.0.0 as the version for platform and application?

Hi qutreson,

_Pasting my response from another issue on the same topic (https://github.com/Microsoft/AL/issues/4903) which helped me resolve this issue. That said, we'll still need a long term fix so we can create app.json reference 14.x.x.x and runtime 3.0:_ 

Through trial and error, here's what I found out.

I'm able to download symbols if I change the following in app.json from:

```
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "runtime": "3.0"
```

to 

```
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "runtime": "2.2"
```

Also, note that runtime 2.2 does not support "idranges" (for multiple id ranges); be sure to change to "idrange" as shown below.

```
  "idRange": {
      "from": 60000,
      "to": 60005
    },
```

With these changes, I am able to download symbols just fine.

**Comment by qutreson** [comment]
The extension from the marketplace suggests by default 14.0.0.0 as this is the latest released version (April 19).

If you are targeting the April 19 release, then you should keep 14.0.0.0 for the application and system symbols versions in your manifest.
If you are targeting one of the CU of the Fall 18 release, then you should use 13.0.0.0 instead.

**Comment by tguangithub** [comment]
We have exactly the same error when we are trying to work with April 19 release sandbox.  We also tried to use design mode to make minor change to customer page and download code, but still cannot download symbol. Any update or solution for this issue.

Thanks
Tom

**Comment by AndreyKorepanov** [comment]
Same issue in #4935

**Comment by AndreyKorepanov** [comment]
Thank you, We are working on fix for this issue. A work around would be to get the symbols from another source and update the package. In case it is blocking you please open a support ticket.

**Comment by qutreson** [comment]
We are working on a fix that is currently being deployed. As mentioned, the workaround is to get the symbols from another source, eventually by opening a ticket or by downloading them from one of our containers as explained in #4935.

**Comment by atoader** [comment]
@NavTechAnas are you still facing this issue?

**Comment by qutreson** [comment]
@NavTechAnas, I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
