### ISSUE TITLE
Adding comments on Sales Order in Sandbox?

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4898]
**Describe the bug**
Not able to add comments  on Sales order, on Header level through NEW button.

**To Reproduce**
1. Go to any Sales Order --> Navigate --> Order --> Comments ->New

**Expected behavior**
A new comment should be added when click on new and fill comments.

**Screenshots**
![image](https://user-images.githubusercontent.com/33481576/56130343-421c4380-5fa2-11e9-9192-845001f4633d.png)

Version
 - Business Central: CA Dynamics NAV 13.5 (31113)

Thanks

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
