### ISSUE TITLE
Argument count mismatch in ProtocolDiagnostic causes AL to crash

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#4899]
This is most probably related to the issues #4897 and #4628 (among others?).

The problem is that on certain projects the AL language server crashes in VSCode because IDs (object or fields) are out of the range(s) defined in `app.json`. In my case it was a field that had an ID that was out of the defined idRange.

I am currently using ALC.exe version 3.0.118998. 

Here is some rather in-depth info that I have dug up from the insides of ALC.exe. Might be helpful in tracking down:

The issue occurs in the constructor of class `ProtocolDiagnostic`. This one: 
`public ProtocolDiagnostic(Diagnostic diagnostic)` 

The property `Message` of this instance is read from the passed paramter `diagnostic` which in turn formats a placeholder string with some arguments. The problem, (I think) is the fact that the placeholder string expects 3 arguments, but there are only 2 provided:

`diagnostic.MessageFormat` is `The field identifier '{0}' is not valid. It must be within the allowed range '{1}' - '{2}'.`

But the arguments that get passed are only these two:
````
[0]: 12345
[1]: "[12345..12346]"
````

As you can see, the second argument is not really a number but the actual range. I think that the second argument is supposed to be split into `from` and `to`?

Maybe there is an issue between how ranges were defined/handled in `runtime 2.0` vs. `runtime 3.0`. My project is targeting runtime 2.0.

**Comment by qutreson** [comment]
@hemisphera, thank you for reporting this issue (and investigating it). This is something we have also noticed internally and the error is exactly as you described. The fix will be available in the next version of the AL extension on the marketplace.

**Comment by qutreson** [comment]
@hemisphera, closing the issue as it should now be fixed with the new version we published on the marketplace.
