### ISSUE TITLE
Contact Variable in OnBeforeCustomerInsert Event

### ISSUE THREAD

**Issue by SarahBirrer** [Microsoft/AL#4900]
It would be very helpful if the Contact Record Variable would be available in the Contact.OnBeforeCustomerInsert(Cust,CustomerTemplate) Event.

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
