### ISSUE TITLE
Close Dialog before Message?

### ISSUE THREAD

**Issue by eknraw** [Microsoft/AL#4901]
**Describe the bug**
Calling the message function with a dialog open will not display the message.  

In my code example below only the second message displays.  If I comment out the Close() function neither Messages display.  

**To Reproduce**
Steps and to reproduce the behavior:
1. Open Dialog
2. Call Message
3. Close Dialog
4. No Message

``` AL Code to reproduce the issue ```

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        ProgressDialog: Dialog;
        Progress_Txt: Label 'Couting up: #1\';
        i: Integer;
    begin
        Clear(ProgressDialog);
        ProgressDialog.Open(Progress_Txt);

        For i := 1 to 100000 do begin
            i += 1;
            ProgressDialog.UPDATE(1, Format(i));
        end;

        Message('First Finished.');
        ProgressDialog.Close();
        Message('Second Finished.');
    end;
}
```

**Expected behavior**
I would expect to see both the "First Finished." and "Second Finished".  This is the behavior in the Windows Client.  

**Versions:**

 - AL Language: 3.0.115791

 - Business Central:
Version: 14.0.29537.31313-US
Platform: 14.0.29530.31247

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
