### ISSUE TITLE
Events in Contact Table

### ISSUE THREAD

**Issue by SarahBirrer** [Microsoft/AL#4902]
It would be very helpful if the Events OnCreateCustomerOnBeforeCustomerModify and OnCreateCustomerOnTransferFieldsFromTemplate exists for the Vendor in the Contact Table.

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
