### ISSUE TITLE
ID Field in Sales Header Archive Side.

### ISSUE THREAD

**Issue by Akil123** [Microsoft/AL#4905]
Hi,

We need ID(GUID) field(8000) same as like in sales header need in Sale Archive Header also.

This would be helpful for our extension.

Please suggest us.

Thank you
Ramesh.

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
