### ISSUE TITLE
ID(8000) Field in Purchase Header Archive.

### ISSUE THREAD

**Issue by Akil123** [Microsoft/AL#4906]
Hi,

We need ID(GUID) field(8000) same as like in Purchase header need in Purchase Archive Header also.

This would be helpful for our extension.

Please suggest us.

Thank you
Ramesh.

**Comment by qutreson** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
