### ISSUE TITLE
AdditionalSearchTerms not working for Page Extensions

### ISSUE THREAD

**Issue by mynavblog** [microsoft/AL#4907]
Dear Team,

AdditionalSearchTerms is not working for Page Extensions. It is possible to set the parameter in the object but after Publish and Install Extension (even after restart service) the Additional Search is not working.

Steps and to reproduce the behavior:
1. Create Page Extension for Customer List
2. Add Parameter AdditionalSearchTerms (see screen)
3. Publish the App

**Expected behavior**
It depends on the classification:
1. If it should be possible to add AdditionalSearchTerms to Page Extensions - should be possible to search
2. If it should not be possible to add AdditionalSearchTerms to Page Extensions - AdditionalSearchTerms should not be possible to add on the object in AL

**Screenshots**
![image](https://user-images.githubusercontent.com/37371997/56226751-3bf69780-6074-11e9-9992-429df1223d1e.png)
![image](https://user-images.githubusercontent.com/37371997/56226782-4add4a00-6074-11e9-8cf6-840ca3689ca8.png)

**Versions:**
 - AL Language: al-3.0.106655
 - Business Central: bcsandbox and newest BC on-prem

**Comment by qutreson** [comment]
As a note, we also have #4569 related to search from extensions.

**Comment by pborring** [comment]
AdditionalSearchTerms support fixed for PageExtensions in 2019 Wave 2 (version 15) CU1.
