### ISSUE TITLE
"Allow Always" does not appear to be working with Platform 14.0

### ISSUE THREAD

**Issue by chavansachin20** [Microsoft/AL#4911]
how to enable HTTP call and where you find the option to enable it.

Last week, I've updated container with new docker container and now facing below issue.

current version :
Version: Platform 14.0.29530.29573 + Application 31203 (US Dynamics NAV 14.0)

Steps: 

![image](https://user-images.githubusercontent.com/5293496/56340825-c18f5a00-61d0-11e9-8bbf-bf4957f3439b.png)

if I select Allow Always, system gives me below error  
![image](https://user-images.githubusercontent.com/5293496/56340860-dbc93800-61d0-11e9-9271-87867cc67ea6.png)

THis was error in prev docker version & I have provided solution but now same option is not present : ref : https://github.com/Microsoft/AL/issues/3755

we do not have option to config App in Extension management 
![image](https://user-images.githubusercontent.com/5293496/56340961-29de3b80-61d1-11e9-9524-dedb6e584b44.png)

Thanks in Advance.

**Comment by PooyaKharamesh** [comment]
Hi 

You can find the answer in the following threads #3720, #3612

-Pooya

**Comment by chavansachin20** [comment]
@PooyaKharamesh : Thanks for comments, but links to other threads #3720, #3612 didn't help us to a resolved issue.

Root Cause: The main root cause was we used NAV License to create a Docker container
Solution: Create a docker container with OnPrem License file, the issue is resolved.

@freddydk / @waldo1001 / @ajkauffmann  : FYI.
