### ISSUE TITLE
BC recommendations when dealing with AL(AL0486)

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#4915]
While preparing the move to AL, we get tons of AL0486 warnings:

> A member with name 'ContractOut' is already defined. This warning will become an error in a future release. AL(AL0486)

This seems to be due to actions having the same name as other controls (fields / groups) or functions within the same object.

```
action(ContractOut)
                {
                    ApplicationArea = Basic;
                    Caption = '&Contract Out';
                    Image = MakeAgreement;
                    Promoted = true;

                    trigger OnAction()
                    begin
                        ContractOut;
                    end;
                }
```
I agree actions needs to be unique within the collection of actions, fields with the collection of fields, ... But if I understand the message well, we need to uniquely name ANY control (action / group / field / function) on the entire page object to avoid future conflicts? 

What are the naming recommendations of MS / Business Central? How will standard objects name their controls? Should we precede each Action control with **Action-**Name, each group with **Group-**Name, each field with **Field-**Name, ...? Seems like a lot of overhead ...

**Comment by JohanStenberg100** [comment]
Hi @fvet, you can inspect some of the base app's declared pages to get inspired of how we solved it, but AFAIK we don't have any official guidance. You can also choose to ignore the warning if you find it obtrusive by using a ruleset file, but I wouldn't recommend this.

Try to refactor your code to avoid the warning, I would probably avoid making up my own name convention and give a more semantic meaning to each name instead, however take the path you find most convenient for your code path.
