### ISSUE TITLE
Error while downloading symbols after installing april 2019 business central W1

### ISSUE THREAD

**Issue by TinaCarolMenezes** [Microsoft/AL#4921]
Hi,
I installed business central W1 April 2019 version. But the reference symbols are not getting downloaded. All other details like server instance, etc. are correct. The below error comes up.

[2019-04-23 15:27:31.54] Using reference symbols cache path: c:\Users\tinamenezes\Documents\AL\ALProject1\./.alpackages
[2019-04-23 15:27:31.54] Sending request to http://localhost:7049/BC130/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2019-04-23 15:27:31.54] Sending request to http://localhost:7049/BC130/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-04-23 15:27:33.58] Error: Could not connect to the server. Please verify that:
1. The server is started.
2. The development endpoint is enabled (DeveloperServicesEnabled server setting).
3. The service name matches the one specified in the URL.
4. The port number matches the one specified in the URL (DeveloperServicesPort server setting).
5. The protocol matches the one specified in the URL (DeveloperServicesSSLEnabled server setting), and that a trusted certificate is used in case of an SSL connection.
[2019-04-23 15:27:33.58] Error: Could not connect to the server. Please verify that:
1. The server is started.
2. The development endpoint is enabled (DeveloperServicesEnabled server setting).
3. The service name matches the one specified in the URL.
4. The port number matches the one specified in the URL (DeveloperServicesPort server setting).
5. The protocol matches the one specified in the URL (DeveloperServicesSSLEnabled server setting), and that a trusted certificate is used in case of an SSL connection.
Microsoft (R) AL Compiler version 3.0.1.55956
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'ALProject1' containing '1' files at '15:27:34.800'.

error AL1045: The package cache c:\Users\tinamenezes\Documents\AL\ALProject1\./.alpackages could not be found.

Compilation ended at '15:27:35.2'.

Error: The package could not be created.

Thanks

**Comment by JohanStenberg100** [comment]
Hi @TinaCarolMenezes, we can't help you troubleshoot your local setup. I suggest that you post this question to one of the following resources to get help on AL extension development issues:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Using these resources will assist you in getting help from other AL developers.

An alternative is to verify once again that your server is running and that all of the details in your `launch.json` file is correct. You can also open up a support ticket instead.

Thanks,

Johan
