### ISSUE TITLE
'Rename Symbol' fails

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#4922]
**Describe the bug**
When trying to use 'Rename Symbol' on a function / procedure or Field, the rename does not succeed.

**Screenshots**
![Rename](https://user-images.githubusercontent.com/25268332/56582513-b88af800-65d7-11e9-90c0-950327e26c6e.gif)

**Versions:**

 - AL Language: 3.0.121490

 - Business Central:

**Comment by PooyaKharamesh** [comment]
Closing the issue as it should now be fixed with the new version.

/Pooya

**Comment by fvet** [comment]
@PooyaKharamesh, what is the 'new' version? Marketplace's latest version shows 3.0.121490.
