### ISSUE TITLE
Table extension do not work properly in some tables

### ISSUE THREAD

**Issue by jmcouque** [Microsoft/AL#4923]
**Describe the bug**
I have noticed that if you create a table extension to any of the tables not W1 (at leas in the Spanish version) as well as system tables (200000000 ..), the triggers OnInsert, OnModify, OnDelete, etc, do not work. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to a new table extension for table 2000000068 "Record Link" for instance.
2. Write code in any trigger
3. Run the App and Insert, modify or delete a record
The same with tables in Spanish version (7000002 to 7000024)

**Expected behavior**
After Insert, modify, delete a record, etc, I expected that BC run my code, but it does not.

**Versions:**
 - AL Language:  2.0.56865

 - Business Central: 13.0.25924.0

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
