### ISSUE TITLE
Pageextension trigger OnAfterGetCurrRecord not fired

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#4925]
**Describe the bug**
It seems that the OnAfterGetCurrRecord trigger in a pageextension only fires when there is code in C/AL. However, when you set a breakpoint on the code in this trigger, then the debugger stops at the breakpoint. After that, the trigger works like expected, until you publish the extension again or the server is restarted.

A similar issue was reported earlier: https://github.com/Microsoft/AL/issues/1383

**To Reproduce**
Steps and to reproduce the behavior:
Create a pageextension for a page that has no code in the OnAfterGetCurrRecord trigger, e.g. for Page 15 Location List.
Add a trigger OnAfterGetCurrRecord to the pageextension and add some code to it, a message will do the job.
Publish and run the extension, the code will not be executed.
Set a breakpoint on the code and publish again. The debugger will now stop at the code. Stop the debugger and the code will now continue to run.

**AL Code to reproduce the issue** 
```
pageextension 50101 LocationListExt extends "Location List"
{
    trigger OnAfterGetCurrRecord()
    begin
        Message('Hello from OnAfterGetCurrRecord');
    end;
}
```

**Expected behavior**
The OnAfterGetCurrRecord trigger in a pageextension should always execute, regardless of C/AL code in the base object.

**Versions:**
 - AL Language: 3.0.118998
 - Business Central: Platform 14.0.31606.0 + Application 31632 (W1 14.1)

**Comment by Frederig** [comment]
Any update on this? This is blocking some functionalities at the moment

**Comment by AndreyKorepanov** [comment]
Hi @Frederig I forwarded the issue to the right team, no updates yet.

**Comment by bwdeleeuw** [comment]
Will this be in CU2 of the April 2019 release? It is not working in CU1

**Comment by geeknikolai** [comment]
Still not working on 14.1.33107.0... When can we expect this?

**Comment by GregoryAA** [comment]
Can you provide any deadline when this issue will be fixed?
