### ISSUE TITLE
Anchor rename issue in BC 14 release

### ISSUE THREAD

**Issue by JayDashti** [Microsoft/AL#4926]
Hello,

We are experiencing some issues with previously used anchor names from version 13 that now are renamed in version 14. One example is Item List repeater that had Name: `<Control1>` Caption: `Item ` but in version 14 the Name now has been changed to `Control1 `without <> which is giving us following error when compiling the app:

 ##... Item List Ext.al(7,17): error AL0270: The control 'Item' is not found in the target"

- Were those control renames on purpose? 
- Should we update our apps to use new anchor names?
- Is there a list of pages that have such anchor renames?

Thanks

**Comment by atoader** [comment]
Hi @JayDashti ! As you probably know, most controls in C/AL do not have the Name property set. In AL, everything must have a name as we switched from ID based to Name based. When generating symbols from the C/AL application or converting the C/AL application to AL, we used an algorithm to generate assign names to controls that did not have the Name property set.
What we discovered while converting the base application to AL was that this algorithm was generating the same name for actions and controls on the same page and this could lead to issues when using the page from test code (as a TestPage).
We had to change the naming algorithm to prevent duplicates and this meant that some controls have a different name in the 14.
You should update your apps to use the new anchor names. 
Unfortunately, there is no list of pages, but the compiler will error out if you are referencing an invalid name.

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
