### ISSUE TITLE
'Go to Definition' on Table triggers

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#4928]
**Describe the bug**
In C/AL, you could use 'Go to definition' on code lines calling the INSERT/MODIFY/... (table) triggers to navigate to the table object trigger code.

In AL,  you can no longer use 'Go to definition' on code lines calling the INSERT/MODIFY/... (table) triggers to navigate to the table object trigger code (only when present). (unless I'm unaware of a hidden feature?)

![image](https://user-images.githubusercontent.com/25268332/56747447-47397980-677e-11e9-864b-3f0ed0f07e70.png)

**Expected behavior**
Please re-enable the 'Go to definition' for table triggers and open the table object, positioned on the OnXXX table trigger (only when the table trigger / code is present).

**Versions:**

 - AL Language: 3.0.121490

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by fvet** [comment]
Update the idea on experience to get back at least the C/AL 'Go to Definition' features in AL
https://experience.dynamics.com/ideas/idea/?ideaid=ec9e4af6-f060-e911-b047-0003ff68a0b2

Feel free to upvote!
