### ISSUE TITLE
[CodeCop Rule] Warning for unused parameters in local functions

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#4929]
**Describe the bug**
In #4572 it is stated that CodeCop detects unused variables, both global and local. This works. However, when a **local** function is created, containing function **parameters** that are never used, it would be interesting to have a CodeCop for these as well.

**Versions:**

 - AL Language: 3.0.121490

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by fvet** [comment]
As a reference
https://experience.dynamics.com/ideas/idea/?ideaid=74e32fdf-416b-e911-b047-0003ff68e45b

Feel free to upvote.

**Comment by MarcHansenMicrosoft** [comment]
Activating as we now support using GitHub for static code analysis.

**Comment by MarcHansenMicrosoft** [comment]
40 votes from Ideas

**Comment by MarcHansenMicrosoft** [comment]
Is fixed in latest version of AL
