### ISSUE TITLE
Error While publishing a package

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#493]
Hi,

We are getting the below when press F5 to publish the package which is created.

![image](https://user-images.githubusercontent.com/26792519/29270489-aff33184-8114-11e7-9946-2e588c4ddea4.png)

Can you please suggest us.

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
Could you provide more details? When did the error start happening, did you change anything compared to the standard configuration provided on the Dev Preview VM?

**Comment by bachii1010** [comment]
Hi Stains,

No we did not changed anything in the config we only changed the default publisher to our Name and added a description for the package and changed US to W1.

Rest is all standard we created a package which consists of reports pages and tables and we pressed F5 and we are getting this error.

Please let me know if any queries.

Thanks,
Varun Reddy

**Comment by StanislawStempin** [comment]
If you're still encountering the error could you please provide the server logs for it?

**Comment by bachii1010** [comment]
HI Stains,

We did not faced this issue in august update.

Thanks for your help..
