### ISSUE TITLE
Hiding Columns in Webclient causes List to be rendered incorrectly

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#4932]
- Server Version: 

![image](https://user-images.githubusercontent.com/48217797/56795840-95e42380-6811-11e9-90fc-da25e48b08af.png)

- Issue: 

When a Column is removed from a List Page using the Column Chooser, the Data Columns are rendered incorrectly is displayed in the following animation:

![Hide column issue](https://user-images.githubusercontent.com/48217797/56795672-430a6c00-6811-11e9-9171-99604a065c58.gif)

- Code:

This the page where the issue occurs:

`page 2013048 "NVT XD Parcel Log List"
{

    PageType = List;
    SourceTable = "NVT XD Parcel Log";
    Caption = 'Cross Dock Parcel Log List';
    ApplicationArea = All;
    UsageCategory = History;
    CardPageId = "NVT XD Parcel Log Card";
    Editable = false;

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field("Log No."; "Log No.")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Parcel No."; "Parcel No.")
                {
                    ApplicationArea = All;
                }
                field("Action"; "Action")
                {
                    ApplicationArea = All;
                }
                field("Log Datetime"; "Log Datetime")
                {
                    ApplicationArea = All;
                }
                field("Log User"; "Log User")
                {
                    ApplicationArea = All;
                }
                field("External Parcel Code"; "External Parcel Code")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Operational Status"; "Operational Status")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Parcel Status"; "Parcel Status")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Unit of Measure"; "Unit of Measure")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Gross Weight"; "Gross Weight")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Volume"; "Volume")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Length"; "Length")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Width"; "Width")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Height"; "Height")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Grouped on Transport Unit"; "Grouped on Transport Unit")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Ungrouped from Transport Unit"; "Ungrouped from Transport Unit")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Terminal"; "Terminal")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Placed In Type"; "Placed In Type")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Placed In"; "Placed In")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Taken From Type"; "Taken From Type")
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field("Taken From"; "Taken From")
                {
                    ApplicationArea = All;
                    Visible = false;
                }

            }
        }
    }

}
`

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
