### ISSUE TITLE
Handle conditional statements in Subscriber Event

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#4934]
Hello Everyone,

I have a situation where I need to skip confirmation dialog message while updating the dimensions in sales / purchase order. In C/AL code I can handle using the "IF" condition. But I am not so sure how I can handle this situation using "AL" events. I have attached the image for the reference. Any help /suggestion.

![image](https://user-images.githubusercontent.com/44765649/56806025-5edd3480-6848-11e9-9a8f-cc004cf3c6fb.png)

Thank you.

**Comment by PooyaKharamesh** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
