### ISSUE TITLE
Error while downloading symbols in VS code in NAV Developer MS Cloud Sandbox

### ISSUE THREAD

**Issue by Ajageavi** [microsoft/AL#4935]
I am getting an error on downloading symbols in VS code with latest version of 365BC. It is asking me to login. I am entering 'admin' as username and my password. But an error comes up and the symbols aren't downloaded. 
The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.29537.29654 failed with code InternalServerError. Reason: Internal Server Error
[2019-04-28 10:47:15.27] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
``` AL Code to reproduce the issue ```

![image](https://user-images.githubusercontent.com/43781253/56860082-6533f380-69a3-11e9-9950-f9d64c0699b5.png)

![image](https://user-images.githubusercontent.com/43781253/56860086-73820f80-69a3-11e9-8d5d-199f3f49dacb.png)

**Comment by BCRog** [comment]
Same issue in https://github.com/Microsoft/AL/issues/4903

**Comment by PooyaKharamesh** [comment]
Hi 

Thank you, We are working on fix for this issue. A work around would be to get the symbols from another source like a docker image and update the package. In case it is blocking you please open a support ticket.

/Pooya

**Comment by khadimali** [comment]
> Hi
> 
> Thank you, We are working on fix for this issue. A work around would be to get the symbols from another source like a docker image and update the package. In case it is blocking you please open a support ticket.
> 
> /Pooya

I am new to D365 Business Central development and I am facing the same issue while tried to setup a development environment for the trial account. I followed this simple 'Getting Started with AL' walkthrough https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started#steps-to-set-up-a-sandbox-environment-and-visual-studio-code

I don' have any on-premises licence as well. Can you please guide me from where can I download the docker image or how can I update the package from any other source? Thank you.

**Comment by ashikkrux** [comment]
@khadimali 

1. Download Docker for Desktop. 
https://docs.docker.com/docker-for-windows/install/

2. Switch to the Windows container if you are working with Windows OS.

3. Run this script in "Install-Module -Name navcontainerhelper" Powershell As Administrator.

4. Download the image using this command 
"docker pull mcr.microsoft.com/businesscentral/sandbox:us"

5. Create a new container.

**Comment by khadimali** [comment]
> @khadimali
> 
> 1. Download Docker for Desktop.
>    https://docs.docker.com/docker-for-windows/install/
> 2. Switch to the Windows container if you are working with Windows OS.
> 3. Run this script in "Install-Module -Name navcontainerhelper" Powershell As Administrator.
> 4. Download the image using this command
>    "docker pull mcr.microsoft.com/businesscentral/sandbox:us"
> 5. Create a new container.

@ashikkrux 

Many thanks for your reply. I followed the steps you mentioned from 1 to 4. However, I don't know how to do the 5th one, creating a new container. Can you please help me more?

I googled also and found this 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox#set-up-a-local-hosted-container-sandbox

Is this something I should follow next now to set up a local hosted container sandbox?

**Comment by tfbtrading** [comment]
Interestingly I've been working fine on my Windows 10 machines. Recently tried to clone a repository on the Mac and despite it authenticating correctly I get this same error above. I wonder whether it is related at all to the client. I'm also connected to Azure DevOps on this machine. I hadn't used this Visual Code client prior to my cloud sandbox being upgraded to April 19 release.   All targets are correct and worked on Windows for 14.0.0.0.

**Comment by Ajageavi** [comment]
> Hi
> 
> Thank you, We are working on fix for this issue. A work around would be to get the symbols from another source like a docker image and update the package. In case it is blocking you please open a support ticket.
> 
> /Pooya

How can we open ticket, we are customer not partner?

**Comment by Ajageavi** [comment]
> Interestingly I've been working fine on my Windows 10 machines. Recently tried to clone a repository on the Mac and despite it authenticating correctly I get this same error above. I wonder whether it is related at all to the client. I'm also connected to Azure DevOps on this machine. I hadn't used this Visual Code client prior to my cloud sandbox being upgraded to April 19 release. All targets are correct and worked on Windows for 14.0.0.0.

i am trying on windows 10, but still getting same error with 14.0

**Comment by qutreson** [comment]
@khadimali, you can read more about containers here: https://github.com/microsoft/navcontainerhelper/blob/master/NavContainerHelper.md

**Comment by qutreson** [comment]
Closing this issue as it is tracked by #4895

**Comment by ashikkrux** [comment]
Creating a new container 

New-NavContainer -containerName test -accept_eula -auth Windows -imageName mcr.microsoft.com/businesscentral/sandbox:us -licenseFile "****" -shortcuts Desktop -updateHosts
