### ISSUE TITLE
Error Compiling 3.0.121490 Extension "Value Cant be null path' "

### ISSUE THREAD

**Issue by BCRog** [microsoft/AL#4936]
- AL Extension Version: 3.0.121490

- Server Version: ES Dynamics NAV 13.5 (31774)

****************
****************
app.json

{
  "id": "*****************",
  "name": "*********",
  "publisher": "*****",
  "brief": "",
  "description": "",
  "version": "1.1.1.11",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "********",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "showMyCode": true,
  "idRange": {
    "from": 50000,
    "to": 99999
  },
  "runtime": "3.0",
  "features": ["TranslationFile"]
}
****************
****************

I don't not have any special code to trigger this issue.

[Error - 10:42:28] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'The value can't be null.  <<!This is transaletd from spanish version, El valor no puede ser nulo/>>
Parameter name: path'  <<!This is transaletd from spanish version, Nombre del parámetro: path'/>>
Details:
System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: path
   en System.IO.Directory.CreateDirectory(String path)
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportRdlcUtilities.GenerateRdlcLayout(ReportTypeSymbol report, IFileSystem fileSystem, String rdlFileName) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\ReportRdlcUtilities.cs:línea 133
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.GenerateLayout(DiagnosticBag diagnostics, PropertyKind propertyKind, Action`3 generator, String layoutType) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:línea 34
   en Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.Emit(DiagnosticBag diagnostics) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:línea 28
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitNonObjectCode(ObjectTypeSymbol containingType, Action`1 emitter) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 212
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 198
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass15_0.<CompileObjectAsTask>b__0() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 175
   en Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:línea 151
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 136
   en Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:línea 125
   en Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:línea 827
   en Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:línea 802
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, Compilation analyzerCompilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 636
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, Compilation analyzerCompilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 477
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 429
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 330
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:línea 57
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:línea 43
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() en F:\a\209\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:línea 64

**Comment by AndriusAndrulevicius** [comment]
Try deleting the generated translation file.

**Comment by BCRog** [comment]
> Try deleting the generated translation file.

Didn't work. Same error. I remove my transaltion folder and the   "features": ["TranslationFile"] from app.jason but still have same error.

Thanks for the reply

-->I attach my app.json to the head of thread.

**Comment by PooyaKharamesh** [comment]
Hi 

This issue might be related to the RDLC file path. Please check if there is any special char or something similar that can trigger the issue. To investigate more please send us a full package that repros the issue?

/Pooya

**Comment by BCRog** [comment]
The issue was related with rdlc files. I solved with the old files before the merge. I can`t find anything strange.
