### ISSUE TITLE
WebEndpoint (PublicWebBaseUrl) is not returned when publishing and building app

### ISSUE THREAD

**Issue by louagej** [Microsoft/AL#4937]
**Describe the bug**
When publishing an app from VSCode, the final step to launch the startup page is failing with this message:

> Could not open the specified startup page. Please check that the server configuration key PublicWebBaseUrl has been properly set.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to CustomSettings.config
2. Element PublicWebBaseUrl is empty
      2.1. Element PublicWebBaseUrl is defined (second test)
3. Create new AL. project in visual studio code
4. Press F5 to publish and launch the app
5. launch.json
``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "My Dev Server",
            "server": "http://xxx.xxx.xxx.xxx",
            "serverInstance": "serverinstance",
            "port": 9044,
            "authentication": "Windows",
            "startupObjectType": "Page",
            "startupObjectId": 31,
            "schemaUpdateMode": "Synchronize"
        }
    ]
}
 ```

Debug Console
``` Powershell
[2019-04-29 15:20:38.24] Publishing AL application using launch configuration '<ServerName> <ServerInstance>'.
[2019-04-29 15:20:38.31] Targeting server '<ServerName>' and server instance '<ServerInstance>'.
[2019-04-29 15:20:38.31] Using Windows authentication.
[2019-04-29 15:20:38.33] Sending request to http://<ServerInstance>:<ServerPort>/<ServerInstance>/dev/apps?SchemaUpdateMode=synchronize
[2019-04-29 15:20:39.99] Success: The package 'xxxxx_1.0.0.0.app' has been published to the server.
[2019-04-29 15:20:40.25] Error: Could not open the specified startup page. Please check that the server configuration key PublicWebBaseUrl has been properly set.
 ```

**Expected behavior**
In the Success response After publishing the app, BC should return something like
``` Powershell
{
    "WebEndpoint": "http://<ServerInstance>/<ServerInstance>/WebClient"
}
 ```
When I trace the traffic with Fiddler, I see no such a response.
Then of course VSCode outputs an error like this:
``` Powershell
[2019-04-29 15:20:40.25] Error: Could not open the specified startup page. Please check that the server configuration key PublicWebBaseUrl has been properly set.
 ```

**Screenshots**
![2019_04_29_001](https://user-images.githubusercontent.com/7229592/56900529-5843fc80-6a96-11e9-88b0-435b4269b4ae.png)

![2019_04_29_000](https://user-images.githubusercontent.com/7229592/56900536-5bd78380-6a96-11e9-9ea0-63e696414cf6.png)

![2019_04_29_002](https://user-images.githubusercontent.com/7229592/56900629-92150300-6a96-11e9-8d26-4f38c9a93671.png)

![2019_04_29_003](https://user-images.githubusercontent.com/7229592/56900903-3eef8000-6a97-11e9-84f4-8e9067c4e550.png)

**Versions:**

 - AL Language: Microsoft_Application_14.0.29537.0.app

 - Business Central: Microsoft_System_14.0.29530.0

**Comment by louagej** [comment]
Strange, but it seems to working fine today.
So I couldn't find the cause to prevent this from happening again.

**Comment by RudolfEisele** [comment]
After changing the PublicWebBaseURL key it is necessary to restart both the Server Instance and Visual Studio Code; then Publishing the app should work. without "Error: could not open the specified Startup page…"  (we had the same Problem today with BC / Dynamics NAV 130)
