### ISSUE TITLE
HttpClient.AddCertificate method is not working properly

### ISSUE THREAD

**Issue by ProdwareJuanan** [microsoft/AL#4939]
**Describe the bug**
When trying to send a request to a web service that needs a certificate there is an error when using AddCertificate method: "Cannot find the requested object".
App compiles, it's a runtime error.

**To Reproduce**
```
HttpWebContent.WriteFrom(RequestStream);
HttpWebRequest.Content := HttpWebContent;
HttpWebClient.AddCertificate(txtCertificate, txtPassword);
if not HttpWebClient.Send(HttpWebRequest, HttpWebResponse) then
 `Error(CommunicationErr);`
```

**Expected behavior**
A response from the webservice with data as works in C/SIDE using dotnet.
If the line is commented, the webservice sends an expected response "there is no certificate".

**Versions:**
3.0.121490 and previous versions

**Comment by PooyaKharamesh** [comment]
Hi 

What is the Server runtime version? could you send us a full package that repro the issue?

/Pooya

**Comment by ProdwareJuanan** [comment]
> Hi
> 
> What is the Server runtime version? could you send us a full package that repros the issue?
> 
> /Pooya

Hi, I cannot send app due to company regulations.

```
  "platform": "14.0.29530.29573",
  "application": "14.0.29537.29654",
  "runtime": "2.2",

```
Thanks in advance

**Comment by PooyaKharamesh** [comment]
Please consider sending a subset of the package or a dummy package that reproes the issue in case you have restrictions on sending the full package.

/Pooya

**Comment by ProdwareJuanan** [comment]
HI,

Codeunit 10752 SII Doc. Upload Management. developed with pure AL could be the dummy package.
`HttpWebRequest.ClientCertificates.Add(X509Certificate2);`
transformed to AL does not response as in C/AL attaching a certificate and a password.

thanks

**Comment by PooyaKharamesh** [comment]
We will try to investigate the issue that you are facing. Having said that we prioritize to fix the bugs that have a clear repro. A full code unit or a package would help to get the fix faster.

/Pooya

**Comment by qutreson** [comment]
Could be similar to #5299

**Comment by 48010** [comment]
Sorry but the error here is "Cannot find the requested object" and the error in [#5299](https://github.com/microsoft/AL/issues/5299) is "The requested operation cannot be performed in this context".
The solution in issue [#5299](https://github.com/microsoft/AL/issues/5299) is to CLEAR the HHTPWebClient variable but that solution does not solves the error of this issue.
