### ISSUE TITLE
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Sequence contains more than one element

### ISSUE THREAD

**Issue by Mr-Pingu** [Microsoft/AL#4940]
When trying to publish to sandbox I receive the following order. Didn't change any code only republish

The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Sequence contains more than one element

Couldn't find any documentation on this error.

**Versions:**

 - AL Language: 3.0.121490

 - Business Central: NL Dynamics NAV 13.5 (31813)
Saas

**Comment by PooyaKharamesh** [comment]
Hi @Mr-Pingu 

would you please provide us the information mentioned in the template, including if it is an onprem or a SaaS sandbox along with server runtime and AL language extension version. The package itself also would be helpful to investigate the issue.

**Comment by Mr-Pingu** [comment]
Updated the version information,
Where can I send the package to? Prefer not to upload it in public space, thanks.

**Comment by PooyaKharamesh** [comment]
looking at the version, the best solution is to get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

/Pooya

**Comment by Mr-Pingu** [comment]
As I am not a partner I can't do the above. It's really hard as customer who develops his own solution to get right documentation and responses. Really  frustrating at times. 
Anyway FYI,
Seems it had to do with visual studio code cache somehow. Cloned repo in fresh machine, exactly the same code I could publish.
