### ISSUE TITLE
Multiple AL Files Error

### ISSUE THREAD

**Issue by EDGZTNSR** [Microsoft/AL#4943]
**Describe the bug**
Most of my Objects are generating an Error.
"An application Object of type 'Codeunit' with ID '52665' is already declared" and
"An application Object of type 'Codeunit' with name 'FOFunctions' is already declared"

The Problem is there are no other Codeunits with the following Name and ID (Codeunit 52665 FOFunctions).

I tried redownloading the Symbol Files. Didn't work.

``` AL Code to reproduce the issue 
Codeunit 52665 FOFunctions
{
    trigger OnRun()
    begin
    end;
}
```

**Expected behavior**
No Compiler Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/39260158/57016962-3628b680-6c1d-11e9-8008-11763e8583b2.png)

**Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.121490
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: CH Dynamics NAV 13.4 (29517)

**Comment by dNsl9r** [comment]
You are developing for OnPrem, right?
Are there any C/AL customizations?

**Comment by PooyaKharamesh** [comment]
Hi,

Please provide us a package that reproes the issue?

/Pooya

**Comment by EDGZTNSR** [comment]
@dNsl9r No, I'm developing on a Docker Environment.
@PooyaKharamesh Here are my Files. I added a Screenshot with the Error.
![image](https://user-images.githubusercontent.com/39260158/57067545-a5f77980-6ccf-11e9-988d-bec362dcb24e.png)
Files: [BookShelf.zip](https://github.com/Microsoft/AL/files/3137518/BookShelf.zip)

**Comment by AndreyKorepanov** [comment]
Hi @EDGZTNSR,
I tried the project and it works fine on my machine: both compiled and published without any errors.
Do not you have any hidden folders in the project folder, containing the files (for example .git)?

**Comment by PooyaKharamesh** [comment]
I could succesfully publish the package that you sent without any issues. 
Please uninstall and unpublish any other apps from your database and make sure that the same object is not published in another app with a different app name. 

/Pooya

**Comment by EDGZTNSR** [comment]
Hi @AndreyKorepanov @PooyaKharamesh 

I don't know what is causing the problem but I just realized I can publish the Extension even with these Error messages.

![image](https://user-images.githubusercontent.com/39260158/57122660-adc22700-6d7e-11e9-9f04-057c7184b3ba.png)
![image](https://user-images.githubusercontent.com/39260158/57122707-ef52d200-6d7e-11e9-907c-254c3ea2ea8d.png)

I'm not sure if I should close this Issue. But working like this works for me.

**Comment by EDGZTNSR** [comment]
Hi @AndreyKorepanov @PooyaKharamesh 

I don't know what is causing the problem but I just realized I can publish the Extension even with these Error messages.

![image](https://user-images.githubusercontent.com/39260158/57122660-adc22700-6d7e-11e9-9f04-057c7184b3ba.png)
![image](https://user-images.githubusercontent.com/39260158/57122772-53759600-6d7f-11e9-878e-50545addcb0e.png)


I'm not sure if I should close this Issue. But working like this works for me.

**Comment by PooyaKharamesh** [comment]
Thanks for update. 

I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

/Pooya
