### ISSUE TITLE
TestToolkit installation support in Online Sandbox

### ISSUE THREAD

**Issue by francisharvey** [Microsoft/AL#4944]
Hi,

Is the Test Toolkit installation now supported in an Online Sandbox environment?
If not, will it be supported soon? 

I ask because docker / azure represent extra work not only for the installation but also to maintain it. It also defeats the whole development sandbox purpose...

Thanks a lot!
Francis Harvey

**Comment by atoader** [comment]
Hi @francisharvey ! We have recently discussed this topic, and while we will make investments in this area in the future, I think that your best option for the next 6 to 12 months is to setup a CI pipeline using Docker/Azure. I think this blog post from Freddy will be a good read if you decide to go down this path: https://freddysblog.com/2019/04/13/running-tests-in-containers/

**Comment by francisharvey** [comment]
Great! Thank you for your answer!

I have read Freddy's blog page already, it is indeed a very good start.
Next step is to setup it...

Regards,
Francis Harvey
