### ISSUE TITLE
conditional visibility on a page extension control bound to a global decimal variable crashes the web client + Windows RTC

### ISSUE THREAD

**Issue by CanuckNav74** [microsoft/AL#4945]
**Describe the bug**
AL Page Extensions allow for conditional visibility on page field controls (e.g. Visible = "Bool Field"), however setting this conditional visibility on a field control bound to a global decimal variable declared in the page extension object itself crashes the client (both web and RTC). The bug can be repro'd in both BC14.x as well as BC13.x docker sandboxes.  

The app compiles just fine in AL but crashes the web client and RTC at runtime. 

Pages with field controls bound to record fields however do not crash the client

**To Reproduce**
Steps and to reproduce the behavior:
1. Extend the Sales Header table and add a Boolean field "BoolFoo"
2. Create a page extension to extend Page 42 Sales Order
3. declare a global decimal variable "DecFoo" in the page extension. 
4. add a field control to the page extension. It should be bound to "DecFoo" and set it's Visible = "BoolFoo"
5. for good measure, initialize DecFoo := 0 via the page extension's OnOpenPage trigger. 
6. Deploy the .app and navigate to the relevant page from the web browser. The page will crash. 

**Expected behavior**
Conditional visible on control bound to global primitive-type variables shouldn't crash the page
Removing the Visible property on the control eliminates the page crash. 

**Versions:**

 - AL Language: 3.0.126381

 - Business Central: 14.0.29530.0 + Application 29537 (CA Dynamics NAV 14.0)

**Comment by JohanStenberg100** [comment]
Hi @CanuckNav74. the crash will be fixed, but:

1. We do not support dynamic expressions that rely on table fields in the properties of a field.
2. We do not support dynamic visibility for fields.
[https://docs.microsoft.com/en-us/dynamics-nav/visible-property](https://docs.microsoft.com/en-us/dynamics-nav/visible-property)

The docs specify that the variables used in the expressions need to be resolved during OnInit or OnOpenPage triggers, and the record variables are resolved after.

So you still need to modify your functionality.

**Comment by CanuckNav74** [comment]
Thanks for the update @JohanStenberg100 

The visibliity properly currently in my page extensions isn't bound to a dynamics expression (such as a function that returns a true/false). The code currently follows Microsoft's documented practices.

![2019-05-13 08_39_54-PagExt50009-Ext42 CWD Sales Order al - canworld-bc - Visual Studio Code](https://user-images.githubusercontent.com/35810192/57622188-136e9a00-755b-11e9-9756-f0f18a40fca8.png)

In the screenshot I attached, is a code snippet from my page extension for page 42 sales order. You can see that two table-based field controls that derive their visibility on a a boolean table field called "CWD Indirect" (which is a custom field added to a table extension for table 36 sales header). 

As you can see I follow the same pattern described here:

https://docs.microsoft.com/en-us/dynamics-nav/visible-property#example-dynamic-property-change-using-a-boolean-field

The code compiles and runs just fine. It only crashes when the field's value expression points to a variable and not a table field.
