### ISSUE TITLE
Error after translation #1518 is back

### ISSUE THREAD

**Issue by MarkusWinBI** [microsoft/AL#4949]
**Describe the bug**
The bug described in "Error after translation #1518" is back

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an extension, use translate with xlif and use "german umlauts" in translation file
-> You get the error... Processing of message 'al/createPackage' failed with error: 'Value cannot be null.
Parameter name: value'
2. Replace the german umlauts in the de.xlif file according to html reference
-> Package can be created and published again

**Expected behavior**
Translations can be done even with german. :-)

**Versions:**
 - Visual Studio Code: 1.32.3
 - AL Language: 0.12.28462

**Comment by MarkusWinBI** [comment]
Edit / correction: the package is built and published, but all (!) translations from the xlif are completely ignored!

**Comment by MarkusWinBI** [comment]
Found the problem: I had an empty caption in a page (without a comment entry). This caused a cascade of errors. After replacing the umlauts with the html tags I could build again, but the xlif was completely ignored.

After building up my xlif file trans-unit by trans-unit I found an entry resulting from an empty caption from a grid layout on a page I created:

group("general")
            {
                Caption = 'General', comment='Allgemein';
                grid(Gen_Grid)
                {
                    GridLayout = Rows;
                    // ShowCaption = false;
                    **Caption = '';**

As the "ShowCaption" is no more supported for grids I was forced to use an empty caption. 

Now I replaced this Section with

                grid(Gen_Grid)
                {
                    GridLayout = Rows;
                    // ShowCaption = false;
                    **Caption = '', comment = '';**

and everything was okay again...

**Comment by PooyaKharamesh** [comment]
Thank you for sharing. it appears that you find a workaround. I still think that this case should be covered therefor tag the issue as a bug.

/Pooya

**Comment by PooyaKharamesh** [comment]
This bug is fixed in the newer versions. I suggest you to use the latest version of AL language extension.

/Pooya
