### ISSUE TITLE
Page Caption is not reflecting CaptionClass function Text

### ISSUE THREAD

**Issue by LoanVision** [microsoft/AL#4950]
When CaptionClass is used on RC activities listpart tile - it's not reflected on page when opened (title). See screenshot. It shows caption if defined or control name if caption doesn't exists, but not the value that's assigned via function to CaptionClass.

![Bug_142](https://user-images.githubusercontent.com/45673357/57188452-de17db80-6ecc-11e9-836e-3e918a6c33ac.PNG)

**Comment by PooyaKharamesh** [comment]
Hi,

Please provide us all the information mentioned in the bug template including AL language and server runtime version and code snippet that reproes the issue. A package that clearly reproes the issue helps to priorities the issue 

/Pooya

**Comment by qutreson** [comment]
Closing this issue as we didn't get the requested information. Please open a new issue with the requested information if you are still facing this problem.
