### ISSUE TITLE
new event needed codeunit 6620

### ISSUE THREAD

**Issue by SahilGuptaBS** [Microsoft/AL#4951]
Hi 

please add more events on function 
![image](https://user-images.githubusercontent.com/38460823/57209526-6cd44780-6ff6-11e9-8403-15c2cf7798b5.png)

here is the postion
![image](https://user-images.githubusercontent.com/38460823/57209704-2b906780-6ff7-11e9-94b4-a26919eb1639.png)

on the same way, for sales we already have 

![image](https://user-images.githubusercontent.com/38460823/57209797-8fb32b80-6ff7-11e9-928b-94c9cb50aecc.png)

i need new event with the same position on purchase too.

**Comment by wisa1** [comment]
There is a seperate repo for eventrequests, chances are higher you'll get a reponse there.

https://github.com/Microsoft/ALAppExtensions/issues

**Comment by PooyaKharamesh** [comment]
Thank you @wisa1.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
