### ISSUE TITLE
The type or method 'SetValueFilter' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by navailable** [Microsoft/AL#4953]
For my extension I need to use the [SetValueFilter] function of the Item Attribute Value table.
But it's not possible:

The type or method 'SetValueFilter' cannot be used for 'Extension' development.AL(AL0296)

![image](https://user-images.githubusercontent.com/50248792/57228810-f7c43a80-7014-11e9-8751-daef1b78588f.png)

AL Language Version: 3.0.126610
"runtime" : "3.0"

**Comment by PooyaKharamesh** [comment]
"SetValueFilter" is not an external function therefore not exposed to AL extensions. 
Since this repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
