### ISSUE TITLE
An application object of type with ID is already declared when package solution

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#4955]
Hi All,

I having issue when package my solution no issue but Visual Studio Code show the error.
Anyone know why ? I am using version 14. Runtime 3.0. Based on the article install .NET Framework 4.7.2 but still error.

![image](https://user-images.githubusercontent.com/34825577/57268992-5393cf80-70b8-11e9-9585-88d3b6d9717d.png)

**Comment by PooyaKharamesh** [comment]
I suggest to uninstall and unpublish all your extensions and try again or try to publish the extension to a clean DB, The same extension might be installed with a different name. If it didn't help you to solve the issue, it would be helpful to send us a package that clearly reproes the issue.

/Pooya

**Comment by EDGZTNSR** [comment]
Same problem I have. #4943

**Comment by SUD-D365** [comment]
I am facing same error, if its an error.
![image](https://user-images.githubusercontent.com/33481576/57291756-acc22a00-70dd-11e9-9c13-65ff17879c5f.png)

**Comment by SUD-D365** [comment]
Guys.
For now its better to use .vsix from spring release.

**Comment by thpeder** [comment]
Hi @Tonygithub17
You probably have a dependency on another extension that also declare a table with the same Id.
If you comment out your table and in another object declare a variable:
Foo : record 70000
and you right click on the 70000 and pick Go-To Definition then you should be able to see the other table, whom your table is colliding with.

**Comment by qutreson** [comment]
Closing this issue as it was inactive for the last month. If you are still facing this problem, please a log a new issue and attach some AL packages that we could use to reproduce and investigate the issue.

**Comment by yurim108** [comment]
I have got the same problem today. 
AL Language v8.2.545335.
That's obviously not a problem of the compiler, the app can be compiled and published without an error.
Solution (worked for me):
- disable Visual Studio Code extension "AL Language".
- enable Visual Studio Code extension "AL Language".
- wait till it loads and parses the source code.

**Comment by amorgan1982** [comment]
@thpeder Thank you for this.  This was the first thing I should have tried.  Turns out there were two pages that were causing a symbol reference in 'Codeunit 0'.  Removing these two pages from the project was the resolution to my issue.
