### ISSUE TITLE
Multiple keys in JSON Path

### ISSUE THREAD

**Issue by HannesHolst1** [microsoft/AL#4957]
- AL Extension Version: 3.0.126610

- Server Version:  Version	10.0.17763 Build 17763

`if JsonObject.SelectToken('$.[ApiMessage,Message]', JsonToken) then`

Hello,

the above code-snippet returns a false when either the key 'ApiMessage' or 'Message' is available in 'JsonObject'. 
Using '$.ApiMessage' or '$.Message' only, SelectToken returns a true.

The expression '$.[ApiMessage,Message]' is valid and should be supported. It can happen that an API returns different json-structures for the same status (e.g. different kinds of presentation of errors).

Thanks for your help,
Hannes

**Comment by PooyaKharamesh** [comment]
Hi @HannesHolst1 

To investigate the issue, please send me the JSON file and snippet of code that you are using.

/Pooya

**Comment by HannesHolst1** [comment]
Hi,

In my response payload I can either get the Json-Object #1
`{"ApiMessage":"Not Authorised","ApiNumber":"XXX001","inventoryResponse":null}`

or Json-Object #2 back
`{"Message": "No HTTP resource was found that matches the request URI 'https://test.com'."}`

Both messages contain an error, but I can't control which structure I receive.
Therefor, when receiving any other Http status than 200, I must search for "ApiMessage" or "Message" to present the user with an error notification.

To extract the error message from the payload, I do use the following (simplified) code:
`        JsonObject.ReadFrom(InStream);

         if JsonObject.SelectToken('$.[ApiMessage,Message]', JsonToken) then
             Error(JsonToken.AsValue().AsText());`

As mentioned above, SelectToken does not comply with "$.[ApiMesage,Message]" and returns a false even when either keys are available in the Json object. 

The JPath expression "$.[ApiMessage,Message]" is valid and therefor I'm report it as an issue.
The expression should either return one matching value or all matching values.

Thanks,
Hannes

**Comment by kalberes** [comment]
Hi! Are you still encountering this issue on the latest 15 based docker images?

**Comment by JohanStenberg100** [comment]
Hi @HannesHolst1, under the hood we (currently) use Newtonsoft which doesn't support that type of syntax. However this will work: `['ApiMessage','Message']`. I will close this issue now, thanks.
