### ISSUE TITLE
HttpClient.Send returns 'false', but HttpResponseMessage.IsSuccessStatusCode returns 'true'

### ISSUE THREAD

**Issue by HannesHolst1** [microsoft/AL#4958]
**Describe the bug**
When the function 'HttpClient.Send' returns a false due to an unknown URI, the method 'IsSuccessStatusCode' of HttpResponseMessage returns a true.

**To Reproduce**
``` 
    local procedure SendRequest()
    var
        client: HttpClient;
        request: HttpRequestMessage;
        response: HttpResponseMessage;
        requestHeaders: HttpHeaders;
        RequestSuccess: Boolean;
    begin
        request.GetHeaders(requestHeaders);
        requestHeaders.Clear();

        request.SetRequestUri('https://sdfdsfdsfd.com/dsfdsfd/');
        request.Method := 'GET';

        RequestSuccess := client.Send(request, response); // returns false
        RequestSuccess := response.IsSuccessStatusCode; // returns true
    end;
```

**Expected behavior**
Because the URI is unknown, 'IsSuccessStatusCode' should return a false.
Actually, in this situation, 'HttpResponseMessage' should be in its initialized state.

**Screenshots**
Let me know if necessary.

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: Platform 14.0.29530.31296 + Application 31430 (GB Dynamics NAV 14.0)

Thanks for listening,
Hannes

**Comment by ajkauffmann** [comment]
If client.Send returns false, then the server didn't even give a response at all. The response object will (most probably) just have some default values, but you should not even test against it because it doesn't represent anything from the server.

Your code should rather look like:
```
if client.Send(request, response) then
        RequestSuccess := response.IsSuccessStatusCode;
```

**Comment by HannesHolst1** [comment]
Hi,

Yeah, I've already applied the same code which you posted.
It's odd, that client.Send returns a false and the response-object contains a status code that represents a success.

It's the same for inconsitancies when it comes to indexes.
The index of a JsonArray starts at 0 and the index of a List starts at 1.
This makes the AL language look inconsistent.
