### ISSUE TITLE
NAV App object Metadata table access for extensions developement 

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#4960]
Hi,

We need Nav App object metadata table in extension development.
We need this because we want to use the User AL code blob field and retrieve the functions in a codeunit.

Can you please provide this or any alternatives?

Thanks & regards
Varun Reddy

**Comment by PooyaKharamesh** [comment]
Nav App object metadata table cannot be exposed in the cloud environment. You can still use it on on-prem solutions by setting the target to internal. 

Please provide us more information about your scenario and what you would like to achieve?

/Pooya

**Comment by bachii1010** [comment]
Hi Pooya,

As said in above description we want to get the functions of the codeunit and it is only possible now in AL with the "User AL Code" field in NAV App Object Metadata table with which we can read the blob field and get the functions list.

If it is not possible to expose this table in AL hen can you please suggest us an alternative workaround?

**Comment by kalberes** [comment]
This is not possible today and probably it will never be possible on sandboxes. 
Please bear in mind that how we store and package information in the blobs is internal and can change from one version to another.

**Comment by bachii1010** [comment]
SO there is no work around also  @kalberes 

Please let me know

**Comment by kalberes** [comment]
No, there is none. You can maybe add a suggestion here https://aka.ms/BusinessCentralideas that the codeunit virtual table to contain function signature information too.

**Comment by qutreson** [comment]
Closing this issue as this should be handled through a feature suggestion on BC ideas.

**Comment by jmadrigalTCN** [comment]
Good morning.

I need this table in SaaS. 
I need to know which table extends a TableExtension. I use this table because in the field "Object subtye" I have this informatios.

Is there any other way to know this for SaaS?

Thank you
