### ISSUE TITLE
CONFIRM in Microsoft code without GUIALLOWED

### ISSUE THREAD

**Issue by FabianBigler** [microsoft/AL#4962]
This is still an issue in the latest CU6:
In the Codeunit 7304 - Whse. Jnl.-Register Batch there is a CONFIRM within the function CheckItemAvailability.

CONFIRM is evil if I call the function via SOAP or ODATA (it will simply fail, whenever it hits CONFIRM).

I kindly ask you to fix this for all objects in the next CU the same way as in Sales-Post (with the ConfirmManagement CU).

Kind regards
Fabian

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
