### ISSUE TITLE
Issue with Uploading Extension: There was an internal error validating the tenant, please try again.

### ISSUE THREAD

**Issue by oleksdynamics** [microsoft/AL#4963]
In Business Central Sandbox (Cloud version) I am trying to upload my extension from the *.app file but upload fails with error message: 
> The job for id '38ab0c03-2e45-4a92-8183-1c375448b428' was not found. - Job Id : 38ab0c03-2e45-4a92-8183-1c375448b428

The same app can be installed in BC On Premises without any problems...

**Details:**
To upload .app file in BC Sandbox I go to: Setup & Extensions -> Upload Extension, Select .app file from the disk, click Deploy. Then go to Deployment Status: See result:
_Operation Type_: Upload
_Status_: Failed
_Summary_: There was an internal error validating the tenant, please try again. Job id:'b802ab54-e983-4588-be68-c9a3f35810c3'

Click View Details: The job for id '38ab0c03-2e45-4a92-8183-1c375448b428' was not found. - Job Id : 38ab0c03-2e45-4a92-8183-1c375448b428

**Versions:**
 - AL Language: 3.0.126610
 - Business Central: NL Dynamics NAV 13.5 (31813)

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by Mr-Pingu** [comment]
@PooyaKharamesh I am having the same on other version:
14.0.29537.29654 (Preview)

Please reopen.

**Comment by oleksdynamics** [comment]
Hi @PooyaKharamesh, this issue appears on the latest developer preview environment. 

Please reopen.

**Comment by nongminh** [comment]
Hi all, I am having the same on other versions: 14.1.33107.0
