### ISSUE TITLE
FlowField results not searchable 

### ISSUE THREAD

**Issue by RafaelAyala** [microsoft/AL#4964]
Hello,

I have extended a table(Vendor Ledger Entries) with a couple of FlowFields and exposed them on the VLE page. Very straightforward code so far and the fields are showing the correct data when  the page is opened. 

I would expect the Search box on the page to include results from the newly added FlowField columns but it does not include them. The filter functionality works.  Is the Search not functional with FlowFields created in table extensions?

- AL Extension Version:  3.0.126610

- Server Version:  14.0.29530.31296 (31430)

**Comment by PooyaKharamesh** [comment]
We will investigate the issue. Please send us the code snippet that you used to repro the issue.

/Pooya

**Comment by RafaelAyala** [comment]
Here's the FlowField for the Vendor Ledger Entry table ext.
![image](https://user-images.githubusercontent.com/681803/57462723-67ba0700-7247-11e9-8443-ce104d9fed19.png)
And the Vendor Ledger Entries page extension field 
![image](https://user-images.githubusercontent.com/681803/57462979-e616a900-7247-11e9-981c-5da9f92158d1.png)

Thanks, 
Rafael

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
