### ISSUE TITLE
Captions Show in NavigatePage even though ShowCaption = false

### ISSUE THREAD

**Issue by OleTeichmann** [microsoft/AL#4965]
- AL Extension Version: 3.0.126610

- Server Version: 14.0.29530.31573

Field Captions show in a NavigatePage even though I set ShowCaption = false.
In previous versions it worked fine.

Code Example:

                    field(Spacer4; '')
                    {
                        ApplicationArea = All;
                        ShowCaption = false;
                        Editable = false;
                        MultiLine = true;
                    }

**Comment by AndreyKorepanov** [comment]
Hi @OleTeichmann, it does not seem to be reproducible on my machine. Could you please provide the project where the issue is observed.

**Comment by OleTeichmann** [comment]
Here is a Test Project I created which has the same issue. Thank you in advance :)
[TestProject.zip](https://github.com/microsoft/AL/files/3166186/TestProject.zip)

**Comment by AndreyKorepanov** [comment]
Hi @OleTeichmann, I still can not reproduce it on your project. Could you please try it with the latest daily build?

**Comment by OleTeichmann** [comment]
Hi @AndreyKorepanov, with the daily build it works fine. Thank you very much :D
