### ISSUE TITLE
Multiple object in a single .al file

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#4968]
Hi Team,

Is it possible to force developer , to not define multiple objects in a single .al file.
Like i have an .al file, in which i defined a **PageExtension**, i can define another **PageExtension** or **TableExtension** in the end of first PageExtension code. Like below

![image](https://user-images.githubusercontent.com/33481576/57765391-f7b5f000-7722-11e9-83b6-301584c2414c.png)

As per my view , this is not an example of best practice. 
Correct me if i am wrong anywhere.

Thanks

**Comment by JohanStenberg100** [comment]
Hi @SUD-D365. This is a suggestion that you should post to [http://aka.ms/bcideas](http://aka.ms/bcideas) which our PMs regularily monitor. Thanks!
