### ISSUE TITLE
Field showing on Page without ApplicationArea

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#4969]
**Describe the bug**
Extended fields are showing on the page without defining the property **ApplicationArea**

**To Reproduce**
Extend **Sales Order** page and add customized fields without adding **ApplicationArea** property.

**Expected behavior**
Fields should not be visible.

**Versions:**

 - AL Language: Version: 3.0.126610

 - Business Central: Spring Release 
![image](https://user-images.githubusercontent.com/33481576/57766918-d9052880-7725-11e9-885e-30e847f111f5.png)

Thanks

**Comment by kalberes** [comment]
@SUD-D365 Looks like a runtime/client issue to me. For faster resolution a Request For Hotfix should be created using the known channels, if the issue still persists with the latest Vsix version
