### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#497]
I have some webservices, which require me to hash a value in the request.
Since I cannot use the .NET components, do we have any function available, that I can use to hash the value?

**Comment by Gallimathias** [comment]
The functions are in process. I also link you the answer when I find it :)

**Comment by Gallimathias** [comment]
#465 @StanislawStempin 11. Aug

>We do plan on providing more cryptography functionality, since it is often required for making service calls. Once we get to it we will evaluate this particular scenario in more details to see if we can cover it as well.

**Comment by StanislawStempin** [comment]
That's correct, #465 covers hashing as well.
