### ISSUE TITLE
D365 - Indexing error when closing page Purchase Quote Archive

### ISSUE THREAD

**Issue by bogdan81GitHub** [microsoft/AL#4970]
When closing the purchase quote archive card the following error occurs:

One or more errors occurred while closing the page.

The value of INDEXING parameter 1 is outside of the permitted range. The current value is: 2. The permitted range is: from 0 to 0.

**Versions:**

 - Business Central:
Created container using docker image:
mcr.microsoft.com/businesscentral/sandbox:14.0.29537.31096-nl-ltsc2016

**Comment by bogdan81GitHub** [comment]
![Error_PurchaseQuoteArchive](https://user-images.githubusercontent.com/30693206/57772072-d0582680-7714-11e9-88c8-1edbba3f3408.png)

**Comment by JohanStenberg100** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
* Open a support request to CSS through the PartnerSource portal
* Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by diogoma** [comment]
Is this issue closed?
If yes, where can I get the Hotfix for this?

Many thanks
DMA
