### ISSUE TITLE
The extension could not be deployed because it is already deployed on another tenant

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/AL#4972]
This issue is a re-open attempt for issue [4265](https://github.com/Microsoft/AL/issues/4256).

Using Freddy's navcontainerhelper tool, create a new docker container for mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-na-ltsc2019
Publish our app with powershell Publish-NavContainerApp
Publish from VSC

Error message is

The extension could not be deployed because it is already deployed on another tenant

**Comment by JohanStenberg100** [comment]
Hi @kylehardin6. We still have no plans for fixing this unfortunately, we are focusing on the C/AL to AL transition. You can post this to [aka.ms/bcideas](aka.ms/bcideas) and see if you get some traction there, our PMs regularily look at that forum and if enough people want this we will do it. Thanks

**Comment by freddydk** [comment]
The reason for this is, that the PowerShell cmdlet Publish-NavApp (which is called from Publish-NavContainerApp) is publishing in "production mode".
I have just published a new version of NavContainerHelper (0.6.1.2), where Publish-NavContainerApp has an additional switch:

-useDevEndpoint

Which causes the app to be published using the dev endpoint.
Note, when you use the dev endpoint, the app is always installed. You can specify syncmode to clean or forcesync if you do not want the standard synchronize behavior.
If you are running multi-tenancy, you must specify -Scope Tenant and -Tenant tenantname
-install and -skipverification parameters are ignored when using the devendpoint.

So, update NavContainerHelper and use -useDevEndpoint - then you should be able to publish using VSCode afterwards.
