### ISSUE TITLE
"Action Cue" is not working in Tablet Client

### ISSUE THREAD

**Issue by kokkeonghow** [microsoft/AL#4974]
**Describe the bug**
Create a page with SourceTable = "Sales Header". In the same page, i have added Action Cue called "Pay". I try to run it in normal web client is working fine. Anyhow, i try to change to tablet client mode, click on Action Cue totally no response. 
After then, I'm trying to make breakpoints (Pay OnAction trigger) in debugger, but it no response as well. 

**To Reproduce**
Just click the **Pay** Action Cue only, it will found the problems.

**Expected behavior**
Expected in tablet client mode will trigger coding **OnAction** of **Pay** Action Cue. 
It should be work for both web client and tablet client.

**Screenshots**
Refer to screenshot below, click on "Pay" Action Cue will not get any response in tablet client mode.  
![image](https://user-images.githubusercontent.com/50661133/57824659-5dab8180-77ce-11e9-9031-2a961c35b1d4.png)

Refer to screenshot below,  It is working fine when click **"Pay"** Action in tablet client.  
![image](https://user-images.githubusercontent.com/50661133/57825037-b596b800-77cf-11e9-86be-6c3122e5f3c6.png)

**Versions:**
 - AL Language: 
3.0.126610

 - Business Central:
US Dynamics NAV 14.0 (32248)

**Comment by JohanStenberg100** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
* Open a support request to CSS through the PartnerSource portal
* Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
