### ISSUE TITLE
Cannot download source code of run-time package from Extension Management page, however it is possible via "AL: Download source code"

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#4975]
**Describe the bug**
I've a run-time package installed into a BC database, which has property "showMyCode" set to true in the app.json file of the project. The run-time package itself was also generated with the `Get-NAVAppRunTimePackage` cmdlet with flag `-ShowMyCode 1` set explicitly.

First off, I should note that in the "Extension Management" page, the action to download the source code is unavailable for this extension (Enabled=false).
I want to be able to download the source code though, so that I could debug it without needing to have the source code next to having the package.

Then, what I tried is downloading the source code via command "AL: Download source". This actually downloads the source code, however it causes yet a **different** issue for my extension (reported in #4225):
I have objects of different object types with the same object name (but different file names, although that shouldn't be necessary either), but the **file names** of the objects that are downloaded only have the **object name**, which is probably the reason why not all of the source code is downloaded.

**To Reproduce**
Create an extension with "showMyCode" set to true.
Create a run-time package from it (and set flag -ShowMyCode 1). Publish it to a BC database.
Open "Extension Management" page. Try to download the source code.

**Expected behavior**
Being able to download source code from both the "Extension Management" and command "AL: Download source code" from VSCode.

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 14.0.29530.0

**Comment by hamidrzeinali** [comment]
I am trying to download source code via API, is it possible ?

**Comment by kalberes** [comment]
@rvanbekkum  Do you have the same issue with the latest vsix and the new resourceExposure policy setting?
