### ISSUE TITLE
Standard object translation - Option caption

### ISSUE THREAD

**Issue by fmoric** [microsoft/AL#4977]
**Describe the bug**
I don't know if this is AL Compiler issue, bug is in combined enviroment's.

Translating standard app objects through extension using txt file, option caption is not working as intended when options values are used in messages, errors, form C/AL code.

Problem appeared in standard code that is generating mail to send to customer, where C/AL tries to get document type that it is sending. 

Further testing showed that AL can retrieve translated caption but C/AL returns original language (en-US).

**To Reproduce**
Steps and to reproduce the behavior:
1. Translate some standard object using extension, eg. Sales Header to some language.
2. Change to said language.
3. Open table, or page, and Option caption can be seen on pages (so it works).
4. Try print value of option in a message through C/AL, value is in an original language (en-us).

``` AL Code to reproduce the issue ```
C/AL Code

SalesHeader.Init;
MESSAGE('%1 - %2', SalesHeader.FIELDCAPTION("Document Type"), FORMAT(SalesHeader."Document Type"));

**Expected behavior**
Value of option to be in same language as system is.

**Screenshots**

![SShot](https://user-images.githubusercontent.com/18283753/57850878-5d67b200-77df-11e9-816b-247cda600363.png)

**Versions:**
Any

 - AL Language: 
Any

 - Business Central:
Any

**Comment by thpeder** [comment]
Thanks for reporting the issue,
We are working on getting it fixed.

**Comment by adesz444** [comment]
I've encountered the same behaviour when running reports. The option fields in the dataset always get the original optioncaption.
If the translation txt file is put in the instance folder on the application server as with the previous NAV versions it shows the correct translation of the option field. So it's at least a workaround for the problem, but I hope you'll find the solution soon!

**Comment by fmoric** [comment]
I did not realize the report issue also. I don't get the solution with instance folder...
You mean to translate it internally? I'd hope to skip that, we did not modify any objects...

@thpeder Is there any progress on this?

**Comment by adesz444** [comment]
@fmoric See this guide (Point 2): https://docs.microsoft.com/en-us/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files#importing-multilanguage-files
With this method you can use only the txt file without modifying any object in the designer for a long time now.

**Comment by fmoric** [comment]
Thanks a lot, did not see that part, but as you said it it is temporary fix.

**Comment by rznd** [comment]
It appears this is fixed in BC Spring 2019 CU3, I tried installing our translation app into a cu3 container and it worked. Can anyone else confirm?

**Comment by r4luk** [comment]
Hello,
We are encoutering the same problem in BC CU8.
e.g.: in Report 7318 Whse.-Shipment - Create Pick the WhseActivHeader.Type is not translated.
It should be "Culegere", but the ENU version is shown "Pick".
MESSAGE(STRSUBSTNO(SingleActivCreatedMsg,FORMAT(WhseActivHeader.Type),FirstActivityNo,CannotBeHandledReason)
![image](https://user-images.githubusercontent.com/21063415/66048455-3ca3bd00-e532-11e9-8bdd-0794674efb2d.png)

![image](https://user-images.githubusercontent.com/21063415/66048606-812f5880-e532-11e9-8a0b-b9ad639b09fb.png)

@atoader could you please confirm that it will be shipped in the October release?

Thanks a lot.

**Comment by atoader** [comment]
@r4luk this has been fixed in the latest release. For backports to version 13, please go through the standard support channels.
