### ISSUE TITLE
Subscribing on API Page OnOpenPageEvent does not work

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/AL#4978]
I am trying to subscribe to on OnOpenPageEvent of API pages and seems like that code is never triggered. Tried with my own API page and also with native Vendor Entity page, but it doesn't work in both cases. But I managed to subscribe on integration event which I added to my API page.

Here you can see my codeunit with subscriber examples:

![image](https://user-images.githubusercontent.com/40229810/57854615-f3eca100-77e8-11e9-8a2f-11161886716d.png)

And here is my integration event added to OnOpenPage trigger of my API page:

![image](https://user-images.githubusercontent.com/40229810/57854722-34e4b580-77e9-11e9-9b8e-71fbf812e5b3.png)

I would like to avoid this workaround with creating my own integration event (hook also works) if that is possible.

Here you can also see data from Event Subscriptions:

![image](https://user-images.githubusercontent.com/40229810/57855435-f223dd00-77ea-11e9-991c-27543235b6be.png)

 - AL Language: 2.1.106653
 - Business Central: 13.5.29614.0-ca-ltsc2019

**Comment by zulezmaj** [comment]
Forgot to add that it can also be seen in Event Subscriptions:

![image](https://user-images.githubusercontent.com/40229810/57855106-2f3b9f80-77ea-11e9-8b60-04b34071784f.png)

**Comment by JohanStenberg100** [comment]
Hi @zulezmaj!

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. You are using an older version. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
* Open a support request to CSS through the PartnerSource portal
* Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

If you can reproduce this in the latest BC version, please open up a new issue.
