### ISSUE TITLE
BC 14.00 SERVICE INVOICE STATISTICS doesn't show any values

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/AL#4980]
**Describe the bug**
I've configured the Service module as Demo data is not available.
After configuration / Setup, created Service Order / Invoice and on Click on Statistics,> system shows blank screen without any details line we used to have in NAV version. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to 'Service Order / Invoice'
2. Create a statndard transaction with a single line 
3. click on Statistics 

**Expected behavior**
System should show details with respect amount and Tax applied on transaction

**Screenshots**
![image](https://user-images.githubusercontent.com/5293496/57867021-033a1180-781e-11e9-9dc9-b8bc7d7467b3.png)

**Versions:**
Version: Platform 14.0.29530.31705 + Application 31808 (US Dynamics NAV 14.0)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
