### ISSUE TITLE
API in AL is not possible connect in Flow

### ISSUE THREAD

**Issue by RCORELLA** [microsoft/AL#4981]
When I develop an API page in C/SIDE in Business Central OnPremise, I can use it to connect in Flow, but If I use AL to do the same API page in VsCode and publish it in the onCloud, I can't select it to work with Flow.
![image](https://user-images.githubusercontent.com/23438653/57883366-46987e00-7826-11e9-8fa3-9524e9c2583a.png)

What's the problem?

Roberto

**Comment by qutreson** [comment]
Which version of the AL compiler and of BC are you using?

**Comment by RCORELLA** [comment]
Hi,

This is the compiler (3.0.1.61076)

![image](https://user-images.githubusercontent.com/23438653/59053391-a7e5c700-8891-11e9-9e70-aacc6b8f452a.png)

The Business Central version is 14:

![image](https://user-images.githubusercontent.com/23438653/59054195-740ba100-8893-11e9-882f-c012315cd690.png)

Thanks

Roberto

**Comment by qutreson** [comment]
@RCORELLA can you reproduce this issue on the latest developer previews (version 15.x) ?
Can you also attach here some files that reproduces the issue:
- the C/AL file you are using in C/SIDE on prem
- the AL file you are now using in VS Code and for which the issue appears

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
