### ISSUE TITLE
enum dependencies

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#4982]
**Describe the bug**
I created a App with a App with a enum. Now I create a new App with a enumextension and some new values. After that I create a third App and want to use a value from the second app. But I got only the values from the base enum.

**To Reproduce**
1. Create App **A** with enum
```
enum 50000 "App A Enum"
{
Extensible = true;

    value(0; "App A Value")
    {
        Caption = 'App A';
    }
}
```

2. Create App **B** with a enumextension
```
enumextension 50000 "App B Enum Extension" extends "App A Enum"
{
    value(50000;  "App B Value")
    {
        Caption = 'App B';
    }
}
```

3. Create App **C** with a codeunit
```
codeunit 50000 "App C Code"
{
    local procedure TestEnum()
    var
        AppAEnum: Enum "App A Enum";
    begin
        AppAEnum := AppAEnum::"App B Value");
    end;
}
```

4. The Value "App B Value" is not avaiolable in codeunit "App C Code"

**Versions:**
 - AL Language: 3.0.126610

**Comment by FSchneiderYav** [comment]
One fix is to use the enum directly "App A Enum" instad of var AppAEnum

```
codeunit 50000 "App C Code"
{
    local procedure TestEnum()
    var
        AppAEnum: Enum "App A Enum";
    begin
        AppAEnum := "App A Enum"::"App B Value");
    end;
}
```

**Comment by marknitek** [comment]
I have this same issue still with AL Language 3.0.152816
The suggested Fix is not working for me.

Will this be fixed with Spring 2019 Release?
