### ISSUE TITLE
Prevent app from compiling if warnings exist

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/AL#4983]
Is it possible to prevent app from compiling if any warnings exist?
So far I've tried with custom ruleset:
{
    "name": "Test"
    ,"generalAction": "Error"
}
This show an error instead of warning bet the package is created (which doesn't really makes sense).
I've also tried running alc.exe with warnaserror parameter but this also creates an app (without any information).

**Comment by JohanStenberg100** [comment]
Hi @AndriusAndrulevicius! This should work on the latest developer preview. You have not listed your extension version, please try it out from the insider build.

**Comment by JohanStenberg100** [comment]
Hi again @AndriusAndrulevicius, it seems we don't have docker images for the fall release preview just yet. So wait until those are out or wait until a CU update for spring 19, then try it in either of those.

**Comment by AndriusAndrulevicius** [comment]
any information on when those images will be available? Current insider image is almost a month old (2019-04-23) which is a bit odd....

**Comment by JohanStenberg100** [comment]
Hi, it seems like it will be roughly 3 weeks until it's updated.

**Comment by AndriusAndrulevicius** [comment]
any news on this topic? Tried yesterday with latest container - still not working...

**Comment by JohanStenberg100** [comment]
The docker images has been released so please use those now. I will close this issue, thanks!
