### ISSUE TITLE
Multilanguage caption not change

### ISSUE THREAD

**Issue by SandipDomadiya** [microsoft/AL#4986]
I am using SaaS spanish sandbox environment.

I am using this environment with the US English language and performing copy document in the sales order where i get the proper caption in Type of Document field.

When I change the language to the spanish the caption of the Type of Document is still remain in Us instead of spanish.

What is the solution for this problem? Is this a bug?

**Comment by thpeder** [comment]
Hi @SandipDomadiya,
Please tell us the version you are running.

I'm guessing that you are using the translationFile feature, if so try use "es-ES_tradnl" in your target language instead of "es-ES".

**Comment by SandipDomadiya** [comment]
I am using spanish online sandbox
Versión: Plataforma 14.0.29530.32718 + aplicación 32618 (ES Dynamics NAV 14.0)

**Comment by SandipDomadiya** [comment]
Also,We have tried with "es-ES_tradnl" instead of "es-ES" but it won't work.

**Comment by SandipDomadiya** [comment]
Latest Versión: Plataforma 14.0.29530.33686 + aplicación 32618 (ES Dynamics NAV 14.0)
but still this issue.
can you please update.

**Comment by atoader** [comment]
@SandipDomadiya we believe this issue has been resolved in the Wave 2 2019 release. Could you please confirm?

**Comment by AndreyKorepanov** [comment]
Hi @SandipDomadiya could you please attach the code sample/project demonstrating the issue? It would help us to get a repro.
