### ISSUE TITLE
ObsoleteState table with TableRelation and rename, rise an Error

### ISSUE THREAD

**Issue by navlarste** [microsoft/AL#4988]
A table set with ObsoleteState = Removed and with a TableRelation give an error when renaming the related record.

It would be great if the compiler take care of that.

**Comment by atoader** [comment]
Hi! Could you please provide a sample that exhibits the issue and describe the steps needed to reproduce the error?

**Comment by navlarste** [comment]
- Create an Extensions like this.

table 50100 ReproHeader
{
    ObsoleteState = Removed;
    ObsoleteReason = 'Repro';
    fields
    {
        field(2; Code; Code[10])
        {
            NotBlank = true;

        }
        field(3; "Customer No."; Text[30])
        {
            TableRelation = Customer;
            DataClassification = CustomerContent;
        }
    }

    keys
    {
        key(PK; Code)
        {
            Clustered = true;
        }
    }

}

- Rename a Customer.

- You will have an Error This.
![image](https://user-images.githubusercontent.com/32996357/59502314-c5242200-8e9d-11e9-9d4d-331e3b5bf2ee.png)

- That is correct.

- It is very easy to miss it on delivery.
- It would be great if it had a compilation error.

**Comment by kalberes** [comment]
The compiler is a design time concept and cannot "take care" of runtime renames of records. 

Can you try reproing this on the latest docker version?
If it still reproes than maybe you should :
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by navlarste** [comment]
I've tested it.
In the latest version I get no runtime error.
So it looks good.
