### ISSUE TITLE
Debugger does not stop after May 19 Release

### ISSUE THREAD

**Issue by 48010** [microsoft/AL#4989]
After the last BC update (14.0.29537.29654) I can not debugg any extension. Has it happened to someone the same? I have been searching for and I have not found anything.

VSCode version: 1.34.0
VSIX: Al Languaje 3.0.126610

I am developing directly in Sandbox and a second Sandbox.

Thank you.

**Comment by 5141252151** [comment]
Same thing happens to me. Debugging works in local container but not in cloud sandbox.

**Comment by atoader** [comment]
Hi! Are you trying to debug your extension or 1st party extensions/the base application?

**Comment by 5141252151** [comment]
I have gotten base application errors that should have been caught by the debugger. I have also placed breakpoints in my extension code that were ignored.

**Comment by 48010** [comment]
I Don´t understand you. What I'm doing is trying to debug my extension publishing it from VS Code.
