### ISSUE TITLE
Deactivating and activating AL Languages for workspace

### ISSUE THREAD

**Issue by MarkusWinBI** [microsoft/AL#4990]
**Describe the bug**
Options "Deactivate in Workspace" and "Activate in Workspace" does not work for AL Languages 

**To Reproduce**
1.) Two different projects, one with an 2018 AL Language, one with a BC AL Language
2.) Switching between them always needs to uninstall the wrong language and reinstall the correct AL Language via .vsix

**Expected behavior**
Having workspaces with different AL Languages is a must-have if you have two or more customers with different AL Versions

**Versions:**
All versions of AL and VS Code

**Comment by atoader** [comment]
Hi! We will investigate this issue. One workaround for this would be to use the insider build of VSCode with one extension installed and the mainstream version of VSCode with the other extension installed.

**Comment by MarkusWinBI** [comment]
Hi atoader, thanks but that is not really a suitable workaround for me as i am currently working on 5 projects with 5 different versions of AL. I think reinstalling the AL Language every time is pretty much faster. :-)

**Comment by atoader** [comment]
You should need at most 2 versions of the extension. Starting with the 2018 Spring release of Business Central you can always use the latest version of the AL extension independent of the server version. You still need to use the version of the AL language extension that comes on the DVD for NAV 2018. You can read more here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions

**Comment by atoader** [comment]
@MarkusWinBI I can confirm that the latest extension can be disabled per workspace. You can try it out by using the latest developer preview: https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/
