### ISSUE TITLE
Page Customization cannot trigger Visible property on Page (BC 14)

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#4991]
I having issue on Page Customization with it cannot apply Visible property on Page.

Below is my AL Code for Page Customization.
![image](https://user-images.githubusercontent.com/34825577/58090218-5682da00-7bf9-11e9-95e8-65c2162f2e59.png)

![image](https://user-images.githubusercontent.com/34825577/58090194-42d77380-7bf9-11e9-87a7-8cecf5691072.png)

**Comment by qutreson** [comment]
Hi @Tonygithub17, did you also create a profile object to link your page customization to? Page customizations are only applied within the context of a given profile. If you are not linking to a profile object and you are not using this profile in your session, then you won't see the change applied. 
If you just want to modify the page for any user, then you should use a page extension object instead.

You can read more about it in our online docs:
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-customization-object

**Comment by Tonygithub17** [comment]
After follow the link given above issue solved.
Thanks qutreson.
