### ISSUE TITLE
How reach license information BC OnPrem

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#4992]
hi all,
It's clear that system\virtual tables are forbidden for extension development, but how to get Qty of licensed users for BC OnPrem?

**Comment by dkorinets** [comment]
any idies?

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
