### ISSUE TITLE
Error AL0451: An assembly could not be found in the assembly probing paths

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#4993]
I'm getting this error when I'm trying to publish extension to server on container
`source/dotnet.al(3,14): error AL0451: 
An assembly named 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
could not be found in the assembly probing paths 
'C:\Program Files\Microsoft Dynamics NAV\130\Service\Add-Ins, 
C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\13.0.29718.0'`

Why I need to have this library in one of these paths and why these paths different from those defined in workspace file?
```
"al.assemblyProbingPaths": [
	"./.netpackages",
	"C:\\Windows\\assembly" ]
```

**Comment by andreassallstrom** [comment]
I have a related problem. 

0 errors when building the project and package, but when I try to publish it I get "An assembly could not be found in the assembly probing paths". For some reason it searches completely different folders than what I've specified.  I don't even have the "Microsoft Dynamics NAV/140"-folder.

![bild](https://user-images.githubusercontent.com/38279731/58695851-ac444880-8396-11e9-9594-fcc1d4ff8289.png)

I tried placing the DLL in the "C:\Windows\Microsoft.NET\assembly\"-path but that still gives the same error.

**Comment by tomasevicstefan** [comment]
Are you running BC on docker? Library that you are trying to use is custom, so you should have .netpackages folder in your project, and dll in that folder

```
"al.assemblyProbingPaths": [
			"./.netpackages",
			"C:\\Windows\\assembly"
		]
```

**Comment by andreassallstrom** [comment]
Yes, I'm running on Docker. I added the "./.netpackages"-path in the config, but was missing the folder in my project so I created that also and put the DLL there.

![bild](https://user-images.githubusercontent.com/38279731/58700015-3db7b880-839f-11e9-8468-fc4db4579ac4.png)

![bild](https://user-images.githubusercontent.com/38279731/58699934-12cd6480-839f-11e9-9235-6bcea2346ae8.png)

Still the same error though :/

**Comment by tomasevicstefan** [comment]
Yes, I also had same problem with standard .net library, and to solve problem I switched from zip standard library to standard codeunit 706 zip stream wrapper.

You can't make step like me, but you can copy dll library to folder where he is looking in docker

`Copy-FileToNavContainer -containerName <containerName> -localPath <localPath> -containerPath <containerPath>`

I assumed that you are using navcontainerhelper

**Comment by andreassallstrom** [comment]
That's it, I just also had to restart the container after copying the files. 
Thanks a lot!

**Comment by tomasevicstefan** [comment]
Yes, you had to restart nav service inside container.

```
Enter-NavContainer -containerName <containerName>
Set-NavServiceInstance -serviceInstance <instanceName> -restart
exit
```

**Comment by qutreson** [comment]
@tomasevicstefan, your initial issue seems to be fixed, can we close this issue?

**Comment by danielonsombi** [comment]
A restart of the Instance worked for me too.
