### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials.You do not have permission to view this directory or page using the credentials that you supplied

### ISSUE THREAD

**Issue by adrianordonez** [microsoft/AL#4994]
Hello i create my server with container sandox enviroment and hosted locally, my server ask for password change and when i change it i cannot sig in into Business central anymore i already change the password for the first i used but i have the same issue. am i missing something else?

Thanks in advance

**Comment by esbenk** [comment]
@freddydk ?

**Comment by atoader** [comment]
@adrianordonez have you found a solution for your problem? Can you share it for future reference?

**Comment by qutreson** [comment]
@adrianordonez, can we close this is issue or are you still facing it? Also, can you try to reproduce it on our latest developer previews?

**Comment by adrianordonez** [comment]
no, i have to create a new sandbox enviroment
