### ISSUE TITLE
Enum and CalcFileds

### ISSUE THREAD

**Issue by jmadrigalTCN** [microsoft/AL#4996]
**Describe the bug**
I have an Emun field in a table, and I want another table to have a FlowField dependeable of this enum field, but I can't. It doesn't matter how I refer to in the formula (=CONST(Option01Enum), =FILTER(Option01Enum), ect), I always get a compilation error.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new EnumObject
2. In a table Create 2 fields i.e. 1 = Amount (Dec), 2 = Option (Enum)
3 In another table create a FlowField and link it with this enum field in a formula.

**Comment by esbenk** [comment]
Please provide complete sample code.

**Comment by jmadrigalTCN** [comment]
enum 50100 MyEnum01
{
    Extensible = true;

    value(0; Value00)
    {
    }
    value(1; Value01)
    {
    }
}

table 50100 MyTable01
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "MyField"; Integer)
        {
            Caption = 'MyField';
            DataClassification = ToBeClassified;
        }
        field(2; "MyEnum"; Enum MyEnum01)
        {
            Caption = 'MyEnum';
            DataClassification = ToBeClassified;
        }
        field(3; "Amount"; Decimal)
        {
            Caption = 'Amount';
            DataClassification = ToBeClassified;
        }
    }

    keys
    {
        key(PK; "MyField")
        {
            Clustered = true;
        }
    }

}

table 50101 MyTable02
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "MyField"; Integer)
        {
            Caption = 'MyField';
            DataClassification = ToBeClassified;
        }
        field(3; "TotalAmount"; Decimal)
        {
            Caption = 'Total Amount';
            Editable = false;
            FieldClass = FlowField;
            CalcFormula = sum (MyTable01.Amount where (MyEnum = const (Value00)));
            /* ERROR
            "resource": "/c:/Users/Jmarin/Documents/AL/ALProject39/.vscode/Test01.al",
            "owner": "_generated_diagnostic_collection_name_#1",
            "code": "AL0186",
            "severity": 8,
            "message": "Reference 'MyEnum' in application object 'MyTable01' does not exist",
            "source": "AL",
            "startLineNumber": 62,
            "startColumn": 71,
            "endLineNumber": 62,
            "endColumn": 78
            */
        }
        field(4; "TotalAmount2"; Decimal)
        {
            Caption = 'Total Amount';
            Editable = false;
            FieldClass = FlowField;
            CalcFormula = sum (MyTable01.Amount where (MyEnum = filter (Value00)));
            /* ERROR:
            "resource": "/c:/Users/Jmarin/Documents/AL/ALProject39/.vscode/Test01.al",
            "owner": "_generated_diagnostic_collection_name_#1",
            "code": "AL0186",
            "severity": 8,
            "message": "Reference 'MyEnum' in application object 'MyTable01' does not exist",
            "source": "AL",
            "startLineNumber": 83,
            "startColumn": 73,
            "endLineNumber": 83,
            "endColumn": 80

            */
        }

    }

    keys
    {
        key(PK; "MyField")
        {
            Clustered = true;
        }
    }

}

**Comment by esbenk** [comment]
What version of the compiler are you using? I have just pasted the sample into the latest version (3.0.126610) available on the marketplace. It compiles without any problems.

**Comment by jmadrigalTCN** [comment]
Microsoft (R) AL Compiler version 2.0.56865
Copyright (C) Microsoft Corporation. All rights reserved

But is the compiler that Visual Code has. I have this version of Visual Code:

Version: 1.34.0 (user setup)
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by jmadrigalTCN** [comment]
I changed the compiler version to 3.0.126610 and it works.

Thank you ever so much
