### ISSUE TITLE
Purchase Quote Archive when close page Prompt error on BC14

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#4998]
After upgrade from BC13 to BC14 i hit the error message when close the Purchase Quote Archives page. Even-though open debugger also cannot detect where the error coming from. 
Seem like BC14 bug.

![image](https://user-images.githubusercontent.com/34825577/58295372-856b9c80-7e01-11e9-96b4-e547cd3ff3ee.png)

**Comment by Tonygithub17** [comment]
Anyone have solution for this ? This look like BC bug not customer support.

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
