### ISSUE TITLE
Cannot access Profile table

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#500]
I need to access the Profile table for our app. I only need read access, in order to load some role center specific data as part of our customer journey.

If access to the table directly is not on the table, then an API to return the list of all available profile IDs would also work.

**Comment by StanislawStempin** [comment]
We will look into exposing the system table or providing an API for it.

**Comment by kvaldik** [comment]
Hopefully there will be write access as well. We have been writing the LS Express role center directly to the Profile table and we are unable to do that at this point.

**Comment by MikeGlue** [comment]
Karl, no need to write to the table actually. You can add profiles using the new Profile object type. I think this was added as part of the July update so you can get the details from the release notes.

**Comment by kvaldik** [comment]
Awesome, I thought I had read all the updates thoroughly but clearly I haven't been thorough enough.
Thanks Mike!
Cheers, Valdi.

**Comment by StanislawStempin** [comment]
The Profile table has been exposed to extension development.
