### ISSUE TITLE
WebClient crashes after page Edit/View swith

### ISSUE THREAD

**Issue by robertsedeljsak** [microsoft/AL#5000]
**Describe the bug**
After extending "Contact Card" page with additional Subpage part within the group, web client crashes after switching Edit/View by having group collapsed.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open Contact Card. (make sure added group is collapsed).
2. 
    a) Swtith Edit/View twice.
    b) trigger  any error (exmaple: by entering invalid SalesPerson)

3. Web client freezes. (using chrome or IE).

Full code in attachment
Page Extension object:
```
pageextension 61001 ContactCard extends "Contact Card"
{
    layout
    {
        addafter(Communication)
        {
            group(DemographicAttributes)
            {
                part(ContactDemogAttributeSubPage; ContactDemogAttributeSubPage)
                {
                    SubPageLink = ContactNo = field ("No.");
                }
            }
        }
    }
}
```
SubPage:
```
page 61002 ContactDemogAttributeSubPage
{
    PageType = ListPart;
    SourceTable = ContactDemographicAttribute;
    DelayedInsert = true;

    layout
    {
        area(Content)
        {
            repeater(GroupName)
            {
                field(DemographicAttributeCode; DemographicAttributeCode)
                {
                }
                field(ValueCode; ValueCode)
                {
                }
            }
        }
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/41987840/58311737-f4e58a00-7e09-11e9-9752-04299679affe.png)

**Versions:**
W1 - On-premiss
 - AL Language: 
3.0.106655
 - Business Central:
14.0.29530.0

Full app archive:
[RobertWebclientCrash.zip](https://github.com/microsoft/AL/files/3215810/RobertWebclientCrash.zip)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atoader** [comment]
@robertsedeljsak an update on this. I have received information from the team responsible for this area that the problem has been fixed.

**Comment by robertsedeljsak** [comment]
@atoader Thank you. Is there a way to avoid this issue on V 14 RTM? Or in which build/release of OnPremis business central is this fixed?

**Comment by atoader** [comment]
It should be fixed in builds more recent than 32683. I think this will be included in CU3.
