### ISSUE TITLE
Error while downloading symbols in VS code edtor from  BC Microsoft cloud sandbox

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#5001]
Hello,

I couldn't able to download the symbols from BC Microsoft cloud sandbox in VS Code editor. Please see the below screenshots of App Json and Launch Json.

![image](https://user-images.githubusercontent.com/44765649/58319868-15c4d400-7e38-11e9-9131-ce2a77941b22.png)

![image](https://user-images.githubusercontent.com/44765649/58319903-237a5980-7e38-11e9-8689-fc19b5ca9a79.png)

**Error**
![image](https://user-images.githubusercontent.com/44765649/58320068-794f0180-7e38-11e9-8788-00af89bf5b45.png)

Thanks,
Sainath.

**Comment by tfbtrading** [comment]
Experienced same on Mac but not Windows clients.

**Comment by qutreson** [comment]
Which versions of the AL extension of BC are you using? 
What happens if you are targeting 13.0.0.0 instead of 14.0.0.0?

**Comment by tfbtrading** [comment]
It seemed to have resumed working everywhere now. Not sure if some hot fixes were applied.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by qutreson** [comment]
@tfbtrading, not sure what happens, but it looked like no symbols matching your requests were found on the tenant. Are you sure you are experiencing the same issue or are you getting an InternalServerError?

**Comment by qutreson** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
