### ISSUE TITLE
Debugger not initializes in Sandbox Environment

### ISSUE THREAD

**Issue by BCRog** [microsoft/AL#5005]
- AL Extension Version: 3.0.121490

- Server Version: ES Dynamics NAV 13.5 (32250)

Last days, when I try to use the debugger in the Sandbox Environment I can’t use it. When I try to publish  with debugger (F5) it always said me   The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: “There are multiple extensión pusblished with same parameters”

**Comment by atoader** [comment]
Hi @BCRog ! Could you please open a support case so that our CSS team can gather the information needed to resolve your issue?

**Comment by finn777** [comment]
The error-la:
---
Publishing AL application using launch configuration 'Microsoft cloud sandbox'.
…
The request for path /v2.0/SandboxCopy/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use.
---
Can be relate to a conflict between Dev (VS Code) extension and PTE (Per-Tenant-Extension) extension.
A PTE (Per-Tenant-Extension) extension is an extension that is installed from the extension management page (web client) via uploading the app and a DEV extension is an app that is deployed via visual studio code. Right now.. there is a uniqueness requirements for coexistence of these 2 kinds of extensions. If a PTE extension is installed on an application service a DEV extension cannot be deployed there.
you can read about it here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization#extension-uniqueness-requirements
Potential solution: unpublished the PTE in sandbox and changed the id, name, version and publisher of DEV extension
P.S. maybe Development base on 'Microsoft cloud sandbox' not best choice. I think better use docker container.

**Comment by atoader** [comment]
Thanks for helping, @finn777 ! I will close this issue for now.
