### ISSUE TITLE
Json SelectToken Array Query fails

### ISSUE THREAD

**Issue by lksg** [microsoft/AL#5006]
Hi,

I wanted to use the SelectToken Function. As soon as I use any kind of array in my JsonPath SelectToken always returned false. For validation I tried to reproduce the problem with the given example in the documentation. Version is BC 140.

My test page with the slightly modified example code (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonarray/jsonarray-selecttoken-method):

```
page 50101 JsonSelectTokenTest
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(SelectTest)
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    JText: Label '{ "company": {"employees": [{ "id": "Marcy",  "salary": 8.95},{ "id": "John",  "salary": 7},{ "id": "Diana",  "salary": 10.95}]}}';
                    companyData: JsonToken;
                    employeeId: Text;
                    salary: Integer;
                begin
                    companyData.ReadFrom(JText);
                    Message(Format(companyData));
                    employeeId := 'Marcy';
                    salary := SelectEmployeeSalary(companyData, employeeId);
                end;
            }
        }
    }

    local procedure SelectEmployeeSalary(companyData: JsonToken; employeeId: Text) salary: Decimal;
    var
        SalaryQuery: Text;
        salaryToken: JsonToken;
    begin
        SalaryQuery := '$.company.employees[?(@.id=="' + employeeId + '")].salary';
        if not companyData.SelectToken(SalaryQuery, salaryToken) then
            error(SelectFailed);

        salary := salaryToken.AsValue().AsDecimal();
    end;

    var
        SelectFailed: Label 'Select returned false.';
}
```

All query tools I've tried returned what I was expecting without a problem.

I'd be happy if you can help me.

Leon

**Comment by DennisReinecke** [comment]
Hey,

your query is wrong.

if you execute this
'$.company.employees[?(@.id=="' + employeeId + '")].salary';
it will be
$.company.employees[?(@.id=="Marcy")].salary
but you need 
$.company.employees[?(@.id=='Marcy')].salary


this will work:
SalaryQuery := StrSubstNo('$.company.employees[?(@.id==''%1'')].salary', employeeId);
(2 single quotes)

Best
Dennis
