### ISSUE TITLE
Error AL0133 Problem that solved itself

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5007]
For the second time I'm facing the same issue while I'm upgrading solution to AL.

> error AL0133: Argument 2: cannot convert from 'DotNet "Newtonsoft.Json.Linq.JToken"' to 'DotNet "Newtonsoft.Json.Linq.JToken&"'

error occurs in function TryGetvalue of dotnet Json object, expecting JToken& object instead of JToken.

` JObject.TryGetValue('', JToken) `

Things that I did to skip this problem are copy Newtonsoft library to .netpackages, and restart VS Code. After I successfully publish extension, I remove .netpackages folder, and I didn't have that problem again. Did I have problem or this is bug?

This code works properly on C# and NAV. 

I'm using BC CU6 on docker.

**Comment by qutreson** [comment]
Hi @tomasevicstefan, which version of the AL extension of BC are you using? Can you attach a small sample reproducing your issue (including the dll for Newtonsoft that you are trying to use in AL) ?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
