### ISSUE TITLE
xmlAttributeCollection

### ISSUE THREAD

**Issue by abouraoui** [microsoft/AL#5010]
Hi,

trying to get the attribute list from an xml file, I use xmlAttributecollection but cannot get the list of attributes.

here is my code:
 xmlNode: XmlNode;
 xmlAttributeList: XmlAttributeCollection;
 xmlAttribute: XmlAttribute;

xmlNodeList := pTableDATA.GetChildNodes();  (pTableDATA is an xmlFile as listed below)

                    for i := 1 to xmlNodeList.Count do begin

                        xmlNodeList.Get(i, xmlNode);
                        xmlElement2 := xmlelement.create('Attributes');
                        xmlElement2.add(xmlNode);
                        xmlAttributeList := xmlElement2.Attributes();
                        
                        Message('xmlAttributeList.Count ' + Format(xmlAttributeList.Count));

the message shows value of 0, here is the xml file:

<?xml version="1.0" encoding="utf-16"?>
<RECORDS>
	<Record RecordID="Currency: AED" />
	<Record RecordID="Currency: AUD" />
	<Record RecordID="Currency: BGN" />
	<Record RecordID="Currency: BND" />
	<Record RecordID="Currency: BRL" />
	<Record RecordID="Currency: CAD" />
	<Record RecordID="Currency: CHF" />
	<Record RecordID="Currency: CZK" />
	<Record RecordID="Currency: DKK" />
	<Record RecordID="Currency: DZD" />
	<Record RecordID="Currency: EUR" />
	<Record RecordID="Currency: FJD" />
	<Record RecordID="Currency: HKD" />
	<Record RecordID="Currency: HRK" />
	<Record RecordID="Currency: HUF" />
	<Record RecordID="Currency: IDR" />
	<Record RecordID="Currency: INR" />
	<Record RecordID="Currency: ISK" />
	<Record RecordID="Currency: JPY" />
	<Record RecordID="Currency: KES" />
	<Record RecordID="Currency: MAD" />
	<Record RecordID="Currency: MXN" />
	<Record RecordID="Currency: MYR" />
	<Record RecordID="Currency: MZN" />
	<Record RecordID="Currency: NGN" />
	<Record RecordID="Currency: NOK" />
	<Record RecordID="Currency: NZD" />
	<Record RecordID="Currency: PHP" />
	<Record RecordID="Currency: PLN" />
	<Record RecordID="Currency: RON" />
	<Record RecordID="Currency: RSD" />
	<Record RecordID="Currency: RUB" />
	<Record RecordID="Currency: SAR" />
	<Record RecordID="Currency: SBD" />
	<Record RecordID="Currency: SEK" />
	<Record RecordID="Currency: SGD" />
	<Record RecordID="Currency: SZL" />
	<Record RecordID="Currency: THB" />
	<Record RecordID="Currency: TND" />
	<Record RecordID="Currency: TOP" />
	<Record RecordID="Currency: TRY" />
	<Record RecordID="Currency: UGX" />
	<Record RecordID="Currency: USD" />
	<Record RecordID="Currency: VUV" />
	<Record RecordID="Currency: WST" />
	<Record RecordID="Currency: XPF" />
	<Record RecordID="Currency: ZAR" />
</RECORDS>

**Comment by abouraoui** [comment]
<?xml version="1.0" encoding="utf-16"?>
<RECORDS>
	<Record RecordID="Currency: AED" />
	<Record RecordID="Currency: AUD" />
	<Record RecordID="Currency: BGN" />
	<Record RecordID="Currency: BND" />
	<Record RecordID="Currency: BRL" />
	<Record RecordID="Currency: CAD" />
	<Record RecordID="Currency: CHF" />
	<Record RecordID="Currency: CZK" />
	<Record RecordID="Currency: DKK" />
	<Record RecordID="Currency: DZD" />
	<Record RecordID="Currency: EUR" />
	<Record RecordID="Currency: FJD" />
	<Record RecordID="Currency: HKD" />
	<Record RecordID="Currency: HRK" />
	<Record RecordID="Currency: HUF" />
	<Record RecordID="Currency: IDR" />
	<Record RecordID="Currency: INR" />
	<Record RecordID="Currency: ISK" />
	<Record RecordID="Currency: JPY" />
	<Record RecordID="Currency: KES" />
	<Record RecordID="Currency: MAD" />
	<Record RecordID="Currency: MXN" />
	<Record RecordID="Currency: MYR" />
	<Record RecordID="Currency: MZN" />
	<Record RecordID="Currency: NGN" />
	<Record RecordID="Currency: NOK" />
	<Record RecordID="Currency: NZD" />
	<Record RecordID="Currency: PHP" />
	<Record RecordID="Currency: PLN" />
	<Record RecordID="Currency: RON" />
	<Record RecordID="Currency: RSD" />
	<Record RecordID="Currency: RUB" />
	<Record RecordID="Currency: SAR" />
	<Record RecordID="Currency: SBD" />
	<Record RecordID="Currency: SEK" />
	<Record RecordID="Currency: SGD" />
	<Record RecordID="Currency: SZL" />
	<Record RecordID="Currency: THB" />
	<Record RecordID="Currency: TND" />
	<Record RecordID="Currency: TOP" />
	<Record RecordID="Currency: TRY" />
	<Record RecordID="Currency: UGX" />
	<Record RecordID="Currency: USD" />
	<Record RecordID="Currency: VUV" />
	<Record RecordID="Currency: WST" />
	<Record RecordID="Currency: XPF" />
	<Record RecordID="Currency: ZAR" />
</RECORDS>

**Comment by abouraoui** [comment]
<?xml version="1.0" encoding="utf-16"?>
<RECORDS>
	<Record RecordID="Currency: AED" />
	<Record RecordID="Currency: AUD" />
	<Record RecordID="Currency: BGN" />
	<Record RecordID="Currency: BND" />
	<Record RecordID="Currency: BRL" />
	<Record RecordID="Currency: CAD" />
	<Record RecordID="Currency: CHF" />
	<Record RecordID="Currency: CZK" />
	<Record RecordID="Currency: DKK" />
	<Record RecordID="Currency: DZD" />
	<Record RecordID="Currency: EUR" />
	<Record RecordID="Currency: FJD" />
	<Record RecordID="Currency: HKD" />
	<Record RecordID="Currency: HRK" />
	<Record RecordID="Currency: HUF" />
	<Record RecordID="Currency: IDR" />
	<Record RecordID="Currency: INR" />
	<Record RecordID="Currency: ISK" />
	<Record RecordID="Currency: JPY" />
	<Record RecordID="Currency: KES" />
	<Record RecordID="Currency: MAD" />
	<Record RecordID="Currency: MXN" />
	<Record RecordID="Currency: MYR" />
	<Record RecordID="Currency: MZN" />
	<Record RecordID="Currency: NGN" />
	<Record RecordID="Currency: NOK" />
	<Record RecordID="Currency: NZD" />
	<Record RecordID="Currency: PHP" />
	<Record RecordID="Currency: PLN" />
	<Record RecordID="Currency: RON" />
	<Record RecordID="Currency: RSD" />
	<Record RecordID="Currency: RUB" />
	<Record RecordID="Currency: SAR" />
	<Record RecordID="Currency: SBD" />
	<Record RecordID="Currency: SEK" />
	<Record RecordID="Currency: SGD" />
	<Record RecordID="Currency: SZL" />
	<Record RecordID="Currency: THB" />
	<Record RecordID="Currency: TND" />
	<Record RecordID="Currency: TOP" />
	<Record RecordID="Currency: TRY" />
	<Record RecordID="Currency: UGX" />
	<Record RecordID="Currency: USD" />
	<Record RecordID="Currency: VUV" />
	<Record RecordID="Currency: WST" />
	<Record RecordID="Currency: XPF" />
	<Record RecordID="Currency: ZAR" />
</RECORDS>

**Comment by abouraoui** [comment]
![image](https://user-images.githubusercontent.com/45698976/58435427-849b6a80-808e-11e9-914e-c76152592a50.png)

**Comment by angela2389** [comment]
I have the same issue, once I do VarXmlNodeList.Get(0, VarXmlNode) I get an error message with "0".

**Comment by angela2389** [comment]
@thloke ,why is this marked as a question? It seems a bug to me...

**Comment by esbenk** [comment]
@angela2389 The Get() method on XmlNodeList is 1-based like most of AL. It is also stated in the documentation https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmlnodelist/xmlnodelist-get-method.

The error-message is lacking and will be updated.

**Comment by esbenk** [comment]
@abouraoui The code sample does exactly what it should. 

`xmlElement2 := xmlelement.create('Attributes');`

Creates a new element named 'Attribute' e.g. <Attributes/>

`xmlElement2.add(xmlNode)`

Add the content of xmlNode to the newly created element e.g. <Attributes>Content from XmlNode</Attributes>

`xmlAttributeList := xmlElement2.Attributes();`

Gets a list of attributes on the <Attributes> element, which is empty and hence have Count = 0.
