### ISSUE TITLE
Web client crashing Issue on build 14.0.29530

### ISSUE THREAD

**Issue by srkkoneti** [microsoft/AL#5011]
Scenario:
I have one Sales invoice contains more than 80 lines. And when I click on action (Preview posting and Post) system crashing after few entries count. Please find the below error.
![image](https://user-images.githubusercontent.com/39953344/58472101-1ecce280-8163-11e9-94ea-7cd51fa5e24c.png).

After verifying through debugging, found that 
Window.Update(1,Counter) where the code is breaking after counter touches 50, it's crashing.

**Version: Platform 14.0.29530.0
Application 29537 (US Dynamics NAV 14.0)**

I have commented above code and rerun the process and , it worked successfully.

Note: Also, when I ran the same code without commenting the code on below Platform, it worked successfully.

**Version: Platform 14.0.29530.32339 ,
Application 32452 (US Dynamics NAV 14.0)**

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
