### ISSUE TITLE
BC 14.00 Service Module demo data is not present

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/AL#5012]
**Describe the bug**
Now we are planning to rlease a app which will help user to calculate Tax on Service transaction. to test same we need a demo database which will help us to post some transaction same like NAV Service Module demo database. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Company information and change User Experience to Premium

2. Click on New, the system gives an error

1. Search for "service setup" --> system open window with blank data

**Expected behavior**
The system should have a demo database and user should able to create and post Service transaction (Quote / Order / Invoice / Credit Memo)

**Screenshots**
![image](https://user-images.githubusercontent.com/5293496/58485339-78dca080-8181-11e9-936e-af48f9817e02.png)
![image](https://user-images.githubusercontent.com/5293496/58485469-be00d280-8181-11e9-9f84-7280cdc94bb3.png)

**Versions:**
Version: Platform 14.0.29530.31705 + Application 31808 (US Dynamics NAV 14.0)

**Comment by dNsl9r** [comment]
Not an AL Language Problem, so it should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
