### ISSUE TITLE
Not able to change the caption for SubPart pages

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#5014]
Hello,

I tried to change the field caption "No." in the "Sales order subform" page but it is not working, and i tried to do it in the other subforms like sales quote subform, purchase quote subform, i observe that for cardpart and listpart pages it is not working.

Thanks,
SainathP.

**Comment by qutreson** [comment]
Please follow the template and provide adequate information to reproduce the issue:
- AL extension version
- BC version
- AL Code reproducing the issue
- Eventually, some screenshots showing the problem you mention
