### ISSUE TITLE
Error function doesn't stop the wizard. 

### ISSUE THREAD

**Issue by Lktijoker** [microsoft/AL#5015]
**Describe the bug**
I have created a wizard, where i have a local procedure, which must be stopped whith Error() function when my fileds in the table are blanked. The Error() function works as Message() it means the Error() function displays an error message but doesn't end the execution of AL code.

**Screenshots**
First Step
![Git](https://user-images.githubusercontent.com/51151782/58538305-23da7200-81f5-11e9-8093-64582e3816a0.png)
Second Step
![Git2](https://user-images.githubusercontent.com/51151782/58538613-c98de100-81f5-11e9-8d5d-789d6470a70d.png)
Step 3
![Git3](https://user-images.githubusercontent.com/51151782/58538862-52a51800-81f6-11e9-9c56-304c7b7a1c15.PNG)
Here is my AL Code
![Git4](https://user-images.githubusercontent.com/51151782/58538921-7b2d1200-81f6-11e9-91ab-4f973e665dda.PNG)

**Versions:**
AL VERSION 
![Git5](https://user-images.githubusercontent.com/51151782/58538980-a4e63900-81f6-11e9-92a1-588e1f1776cf.PNG)

 - Business Central:
Version: Platform 14.0.29530.0 + Application 29537 (DE Dynamics NAV 14.0)

**Comment by kalberes** [comment]
This looks like a runtime/client issue. For a faster resolution a Request For Hotfix should be created using the regular channels.
