### ISSUE TITLE
Event request on Codeunit 443

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5018]
I need an event on codeunit 443 on function PostPrepmtInvoiceYN

IF Print THEN
    GetReport(SalesHeader,0);

  COMMIT;
OnSalesPostPrepaymentCode(SalesHeader); // I need this event

[IntegrationEvent] OnSalesPostPrepaymentCode(VAR PRecSalesHeader : Record "Sales Header")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
