### ISSUE TITLE
Event request on codeunit 445

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5019]
I need an event on codeunit 445 on function PostPrepmtInvoiceYN

IF Print THEN
    GetReport(PurchHeader,0);

  COMMIT;

  OnPurchPostPrepmtCode(PurchHeader); // I need this event

[IntegrationEvent] OnPurchPostPrepmtCode(VAR PRecPurchaseHeader : Record "Purchase Header")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
