### ISSUE TITLE
Rename text to string

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#502]
Somehow the description "Text" disturbs me. In the classic AL, I could resign myself because the SQL type "text" was called. Nowadays the SQL type "Text" is obsolete. Meanwhile, he says, according to my opinion, the wrong. These are not texts or a text, but a string. Moreover, the term string is more sophisticated in computer science.

**Comment by StanislawStempin** [comment]
Thanks for your suggestion. For now we have no plans of renaming the Text type and prefer to stay consistent with the C/AL language.

**Comment by Gallimathias** [comment]
Thanks for your reply stanislaw :)

**Comment by Gallimathias** [comment]
I don't think we need to keep the subject open. I'll come back to that sometime.
