### ISSUE TITLE
Event request on codeunit 12

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5020]
I need an event on codeunit 12 on function InsertVAT

![image](https://user-images.githubusercontent.com/51155305/58545035-bdf4e700-8202-11e9-8e1e-5794c06fc97d.png)

IF "VAT Calculation Type" = "VAT Calculation Type"::"Sales Tax" THEN BEGIN
    IF TaxDetail."Tax Jurisdiction Code" <> '' THEN
      TaxJurisdiction.GET(TaxDetail."Tax Jurisdiction Code");
    IF "Gen. Posting Type" <> "Gen. Posting Type"::Settlement THEN BEGIN
      VATEntry."Tax Group Used" := TaxDetail."Tax Group Code";
      VATEntry."Tax Type" := TaxDetail."Tax Type";
      VATEntry."Tax on Tax" := TaxDetail."Calculate Tax on Tax";
    END;
    OnCopyVatEntryFromTaxDetail(VATEntry,TaxDetail); // I need this event
    VATEntry."Tax Jurisdiction Code" := TaxDetail."Tax Jurisdiction Code";
  END;

[IntegrationEvent] OnCopyVatEntryFromTaxDetail(VAR PRecVATEntry : Record "VAT Entry";PRecTaxDetail : Record "Tax Detail")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
