### ISSUE TITLE
Event request on table 37

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5021]
I need an event on table 37 on functions:

 **Amount - OnValidate**

"VAT Calculation Type"::"Sales Tax":
    BEGIN
      SalesHeader.TESTFIELD("VAT Base Discount %",0);
      "VAT Base Amount" := ROUND(Amount,Currency."Amount Rounding Precision");
      "Amount Including VAT" :=
        Amount +
        SalesTaxCalculate.CalculateTax(
          "Tax Area Code","Tax Group Code","Tax Liable",SalesHeader."Posting Date",
          "VAT Base Amount","Quantity (Base)",SalesHeader."Currency Factor");
          OnSalesTaxCalculateTaxValidateAmount(Rec,SalesHeader,Currency); **// I nedd this event**
      IF "VAT Base Amount" <> 0 THEN
        "VAT %" :=
          ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
      ELSE
        "VAT %" := 0;
      "Amount Including VAT" := ROUND("Amount Including VAT",Currency."Amount Rounding Precision");
    END;

-------------------------------

[IntegrationEvent] OnSalesTaxCalculateTaxValidateAmount(VAR SalesLine : Record "Sales Line";SalesHeader : Record "Sales Header";Currency: Record "Currency")

And on function: **UpdateVATAmounts**

"VAT Calculation Type"::"Sales Tax":
        BEGIN
          Amount := ROUND(CalcLineAmount,Currency."Amount Rounding Precision");
          "VAT Base Amount" := Amount;
          "Amount Including VAT" :=
            TotalAmount + Amount +
            ROUND(
              SalesTaxCalculate.CalculateTax(
                "Tax Area Code","Tax Group Code","Tax Liable",SalesHeader."Posting Date",
                TotalAmount + Amount,TotalQuantityBase + "Quantity (Base)",
                SalesHeader."Currency Factor"),Currency."Amount Rounding Precision") -
            TotalAmountInclVAT;
            OnSalesTaxCalculateTaxUpdateVATAmounts(Rec,SalesHeader,Currency); // I need this event
          IF "VAT Base Amount" <> 0 THEN
            "VAT %" :=
              ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
          ELSE
            "VAT %" := 0;
        END;

[IntegrationEvent] OnSalesTaxCalculateTaxUpdateVATAmounts(VAR SalesLine : Record "Sales Line";SalesHeader : Record "Sales Header";Currency: Record "Currency")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
