### ISSUE TITLE
Event on table 81

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5023]
I need this event on table 81 on functions:

**VAT Base Amount - OnValidate**

"VAT Calculation Type"::"Sales Tax":
    IF ("Gen. Posting Type" = "Gen. Posting Type"::Purchase) AND
       "Use Tax"
    THEN BEGIN
      "VAT Amount" := 0;
      "VAT %" := 0;
      Amount := "VAT Base Amount" + "VAT Amount";
    END ELSE BEGIN
      "VAT Amount" :=
        SalesTaxCalculate.CalculateTax(
          "Tax Area Code","Tax Group Code","Tax Liable","Posting Date",
          "VAT Base Amount",Quantity,"Currency Factor");
        OnSalesTaxCalculateTaxVATBaseAmountValidate(Rec); **// I need this event**
      IF "VAT Base Amount" <> 0 THEN
        "VAT %" := ROUND(100 * "VAT Amount" / "VAT Base Amount",0.00001)
      ELSE
        "VAT %" := 0;
      "VAT Amount" :=
        ROUND("VAT Amount",Currency."Amount Rounding Precision");
      Amount := "VAT Base Amount" + "VAT Amount";
    END;

[IntegrationEvent] OnSalesTaxCalculateTaxVATBaseAmountValidate(VAR GenJournalLine : Record "Gen. Journal Line")

**Bal. VAT Base Amount - OnValidate**

  "Bal. VAT Calculation Type"::"Sales Tax":
    IF ("Bal. Gen. Posting Type" = "Bal. Gen. Posting Type"::Purchase) AND
       "Bal. Use Tax"
    THEN BEGIN
      "Bal. VAT Amount" := 0;
      "Bal. VAT %" := 0;
      Amount := -"Bal. VAT Base Amount" - "Bal. VAT Amount";
    END ELSE BEGIN
      "Bal. VAT Amount" :=
        SalesTaxCalculate.CalculateTax(
          "Bal. Tax Area Code","Bal. Tax Group Code","Bal. Tax Liable",
          "Posting Date","Bal. VAT Base Amount",Quantity,"Currency Factor");
        OnSalesTaxCalculateTaxValBaseAmountValidate(Rec); **// I need this event**
      IF "Bal. VAT Base Amount" <> 0 THEN
        "Bal. VAT %" := ROUND(100 * "Bal. VAT Amount" / "Bal. VAT Base Amount",0.00001)
      ELSE
        "Bal. VAT %" := 0;
      "Bal. VAT Amount" :=
        ROUND("Bal. VAT Amount",Currency."Amount Rounding Precision");
      Amount := -"Bal. VAT Base Amount" - "Bal. VAT Amount";
    END;

[IntegrationEvent] OnSalesTaxCalculateTaxValBaseAmountValidate(VAR GenJournalLine : Record "Gen. Journal Line")

-------------------------------------------------------------------------------------------------------

On **VAT % - OnValidate**

"VAT Calculation Type"::"Sales Tax":
    IF ("Gen. Posting Type" = "Gen. Posting Type"::Purchase) AND
       "Use Tax"
    THEN BEGIN
      "VAT Amount" := 0;
      "VAT %" := 0;
    END ELSE BEGIN
      "VAT Amount" :=
        Amount -
        SalesTaxCalculate.ReverseCalculateTax(
          "Tax Area Code","Tax Group Code","Tax Liable",
          "Posting Date",Amount,Quantity,"Currency Factor");
        OnSalesTaxReverseCalculateTaxVAT(Rec); **// I need this event**
      IF Amount - "VAT Amount" <> 0 THEN
        "VAT %" := ROUND(100 * "VAT Amount" / (Amount - "VAT Amount"),0.00001)
      ELSE
        "VAT %" := 0;
      "VAT Amount" :=
        ROUND("VAT Amount",Currency."Amount Rounding Precision");
    END;

[IntegrationEvent] OnSalesTaxReverseCalculateTaxVAT(VAR GenJournalLine : Record "Gen. Journal Line")

---------------------------------------------------------------------------------------------------------

On **Bal. VAT % - OnValidate**

"Bal. VAT Calculation Type"::"Sales Tax":
    IF ("Bal. Gen. Posting Type" = "Bal. Gen. Posting Type"::Purchase) AND
       "Bal. Use Tax"
    THEN BEGIN
      "Bal. VAT Amount" := 0;
      "Bal. VAT %" := 0;
    END ELSE BEGIN
      "Bal. VAT Amount" :=
        -(Amount -
          SalesTaxCalculate.ReverseCalculateTax(
            "Bal. Tax Area Code","Bal. Tax Group Code","Bal. Tax Liable",
            "Posting Date",Amount,Quantity,"Currency Factor"));
         OnSalesTaxReverseCalculateTaxBalVAT(Rec); **// I need this event**
      IF Amount + "Bal. VAT Amount" <> 0 THEN
        "Bal. VAT %" := ROUND(100 * -"Bal. VAT Amount" / (Amount + "Bal. VAT Amount"),0.00001)
      ELSE
        "Bal. VAT %" := 0;
      "Bal. VAT Amount" :=
        ROUND("Bal. VAT Amount",Currency."Amount Rounding Precision");
    END;

[IntegrationEvent] OnSalesTaxReverseCalculateTaxBalVAT(VAR GenJournalLine : Record "Gen. Journal Line")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
