### ISSUE TITLE
Event on Table 39

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5024]
I need on table 39 this events on functions:

**Amount - OnValidate()**

 "VAT Calculation Type"::"Sales Tax":
    BEGIN
      PurchHeader.TESTFIELD("VAT Base Discount %",0);
      "VAT Base Amount" := Amount;
      IF "Use Tax" THEN
        "Amount Including VAT" := "VAT Base Amount"
      ELSE BEGIN
        "Amount Including VAT" :=
          Amount +
          ROUND(
            SalesTaxCalculate.CalculateTax(
              "Tax Area Code","Tax Group Code","Tax Liable",PurchHeader."Posting Date",
              "VAT Base Amount","Quantity (Base)",PurchHeader."Currency Factor"),
            Currency."Amount Rounding Precision");
            OnSalesTaxCalculateTaxValidateAmount(Rec,PurchHeader,Currency); **// I need this event**
        IF "VAT Base Amount" <> 0 THEN
          "VAT %" :=
            ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
        ELSE
          "VAT %" := 0;
      END;
    END;

[IntegrationEvent] OnSalesTaxCalculateTaxValidateAmount(VAR PurchaseLine : Record "Purchase Line";PurchaseHeader : Record "Purchase Header";Currency: Record "Currency")

------------------------------------------------------------------------------------------------------

On **UpdateVATAmounts**

 "VAT Calculation Type"::"Sales Tax":
        BEGIN
          Amount := ROUND(CalcLineAmount,Currency."Amount Rounding Precision");
          "VAT Base Amount" := Amount;
          IF "Use Tax" THEN
            "Amount Including VAT" := Amount
          ELSE
          BEGIN
            "Amount Including VAT" :=
              TotalAmount + Amount +
              ROUND(
                SalesTaxCalculate.CalculateTax(
                  "Tax Area Code","Tax Group Code","Tax Liable",PurchHeader."Posting Date",
                  TotalAmount + Amount,TotalQuantityBase + "Quantity (Base)",
                  PurchHeader."Currency Factor"),
                Currency."Amount Rounding Precision") -
              TotalAmountInclVAT;
              OnSalesTaxCalculateTaxUpdateVATAmounts(Rec,PurchHeaderCurrency); // **I need this event**
          END;

[IntegrationEvent] OnSalesTaxCalculateTaxUpdateVATAmounts(VAR PurchaseLine : Record "Purchase Line";PurchaseHeader : Record "Purchase Header";Currency: Record "Currency")

-----------------------------------------------------------------------------------------------------

On **Amount Including VAT - OnValidate**

"VAT Calculation Type"::"Sales Tax":
    BEGIN
      PurchHeader.TESTFIELD("VAT Base Discount %",0);
      IF "Use Tax" THEN BEGIN
        Amount := "Amount Including VAT";
        "VAT Base Amount" := Amount;
      END ELSE BEGIN
        Amount :=
          ROUND(
            SalesTaxCalculate.ReverseCalculateTax(
              "Tax Area Code","Tax Group Code","Tax Liable",PurchHeader."Posting Date",
              "Amount Including VAT","Quantity (Base)",PurchHeader."Currency Factor"),
            Currency."Amount Rounding Precision");
        
        OnSalesTaxReverseCalculateTaxAmtInclVATValidate(Rec,PurchHeader,Currency); **// I need This event**
        IF "VAT Base Amount" <> 0 THEN
          "VAT %" :=
            ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
        ELSE
          "VAT %" := 0;
      END;

[IntegrationEvent] OnSalesTaxReverseCalculateTaxAmtInclVATValidate(VAR PurchaseLine : Record "Purchase Line";PurchaseHeader : Record "Purchase Header";Currency: Record "Currency")

--------------------------------------------------------------------------------------------------------

On UpdateVatAmounts

"VAT Calculation Type"::"Sales Tax":
        BEGIN
          PurchHeader.TESTFIELD("VAT Base Discount %",0);
          "Amount Including VAT" :=
            ROUND(CalcLineAmount,Currency."Amount Rounding Precision");
          IF "Use Tax" THEN
            Amount := "Amount Including VAT"
          ELSE
          BEGIN
            Amount :=
              ROUND(
                SalesTaxCalculate.ReverseCalculateTax(
                  "Tax Area Code","Tax Group Code","Tax Liable",PurchHeader."Posting Date",
                  TotalAmountInclVAT + "Amount Including VAT",TotalQuantityBase + "Quantity (Base)",
                  PurchHeader."Currency Factor"),
                Currency."Amount Rounding Precision") -
              TotalAmount;
            OnSalesTaxReverseCalculateTaxUpdateVATAmounts(Rec,PurchHeader,Currency); **// I need this event**
          END;
          "VAT Base Amount" := Amount;
          IF "VAT Base Amount" <> 0 THEN
            "VAT %" :=
              ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
          ELSE
            "VAT %" := 0;
        END;

[IntegrationEvent] OnSalesTaxReverseCalculateTaxUpdateVATAmounts(VAR PurchaseLine : Record "Purchase Line";PurchaseHeader : Record "Purchase Header";Currency: Record "Currency")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
