### ISSUE TITLE
Event on table 290

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5025]
I need on table 290 on functions:

**Update Lines**

"VAT Calculation Type"::"Sales Tax":
          BEGIN
            "VAT Base" := CalcLineAmount;
            IF "Use Tax" THEN
              "VAT Amount" := 0
            ELSE
              BEGIN
              "VAT Amount" :=
                SalesTaxCalculate.CalculateTax(
                  TaxAreaCode,"Tax Group Code",TaxLiable,PostingDate,"VAT Base",Quantity,CurrencyFactor);
              OnSalesTaxCalculateTax(Rec,Currency); **// I need this event**
              END;
            IF "VAT Base" = 0 THEN
              "VAT %" := 0
            ELSE
              "VAT %" := ROUND(100 * "VAT Amount" / "VAT Base",0.00001);
            "VAT Amount" :=
              "VAT Difference" +
              ROUND("VAT Amount",Currency."Amount Rounding Precision",Currency.VATRoundingDirection);
            "Amount Including VAT" := "VAT Base" + "VAT Amount";
          END;

[IntegrationEvent] OnSalesTaxCalculateTax(VAR VATAmountLine : Record "VAT Amount Line";PRecCurrency : Record Currency)

-----------------------------------------------------------------------------------------------------

"VAT Calculation Type"::"Sales Tax":
          BEGIN
            "Amount Including VAT" := CalcLineAmount;
            IF "Use Tax" THEN
              "VAT Base" := "Amount Including VAT"
            ELSE
              BEGIN//LOC-ERS
              "VAT Base" :=
                ROUND(
                  SalesTaxCalculate.ReverseCalculateTax(
                    TaxAreaCode,"Tax Group Code",TaxLiable,PostingDate,"Amount Including VAT",Quantity,CurrencyFactor),
                  Currency."Amount Rounding Precision");
              OnSalesTaxReverseCalculateTax(Rec,Currency); **// I need this event**
            "VAT Amount" := "VAT Difference" + "Amount Including VAT" - "VAT Base";
            END;//LOC-ERS
            IF "VAT Base" = 0 THEN
              "VAT %" := 0
            ELSE
              "VAT %" := ROUND(100 * "VAT Amount" / "VAT Base",0.00001);
          END;
      END

[IntegrationEvent] OnSalesTaxReverseCalculateTax(VAR VATAmountLine : Record "VAT Amount Line";PRecCurrency : Record Currency)

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
