### ISSUE TITLE
Event on codeunit 12

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/AL#5026]
I need this events on table 12:

Function **PostVAT**

"VAT Calculation Type"::"Sales Tax":
      BEGIN
        CASE "VAT Posting" OF
          "VAT Posting"::"Automatic VAT Entry":
            SalesTaxBaseAmount := GLEntry.Amount;
          "VAT Posting"::"Manual VAT Entry":
            SalesTaxBaseAmount := "VAT Base Amount (LCY)";
        END;
        IF ("VAT Posting" = "VAT Posting"::"Manual VAT Entry") AND
           ("Gen. Posting Type" = "Gen. Posting Type"::Settlement)
        THEN
          InsertVAT(
            GenJnlLine,VATPostingSetup,
            GLEntry.Amount,GLEntry."VAT Amount","VAT Base Amount (LCY)","Source Currency Code",
            "Source Curr. VAT Base Amount","Source Curr. VAT Amount","Source Curr. VAT Base Amount")
        ELSE BEGIN
          CLEAR(SalesTaxCalculate);
          SalesTaxCalculate.InitSalesTaxLines(
            "Tax Area Code","Tax Group Code","Tax Liable",
            SalesTaxBaseAmount,Quantity,"Posting Date",GLEntry."VAT Amount");
            OnSalesTaxInitSalesTaxLines(GenJnlLine,SalesTaxBaseAmount,GLEntry); **// I need this event**
          SrcCurrVATAmount := 0;
          SrcCurrSalesTaxBaseAmount := CalcLCYToAddCurr(SalesTaxBaseAmount);
          RemSrcCurrVATAmount := AddCurrGLEntryVATAmt;
          TaxDetailFound := FALSE;

[IntegrationEvent] OnSalesTaxInitSalesTaxLines(VAR GenJournalLine : Record "Gen. Journal Line";SalesTaxBaseAmount : Decimal;GLEntry : Record "G/L Entry")

-------------------------------------------------------------------------------------------------------

On **InitVAT**

 "VAT Calculation Type"::"Sales Tax":
              BEGIN
                IF ("Gen. Posting Type" = "Gen. Posting Type"::Purchase) AND
                   "Use Tax"
                THEN BEGIN
                  GLEntry."VAT Amount" :=
                    ROUND(
                      SalesTaxCalculate.CalculateTax(
                        "Tax Area Code","Tax Group Code","Tax Liable",
                        "Posting Date","Amount (LCY)",Quantity,0));
                      OnSalesTaxCalculateTax(GenJnlLine,GLEntry,LCYCurrency); **// I need this event**
                  GLEntry.Amount := "Amount (LCY)";
                END ELSE BEGIN

[IntegrationEvent] OnSalesTaxCalculateTax(VAR GenJournalLine : Record "Gen. Journal Line";SalesTaxBaseAmount : Decimal;GLEntry : Record "G/L Entry")

--------------------------------------------------------------------------------------------------------

On **InitVAT**

END ELSE BEGIN
                  GLEntry.Amount :=
                    ROUND(
                      SalesTaxCalculate.ReverseCalculateTax(
                        "Tax Area Code","Tax Group Code","Tax Liable",
                        "Posting Date","Amount (LCY)",Quantity,0));
                      OnSalesTaxReverseCalculateTax(GenJnlLine,GLEntry,LCYCurrency); **// I need this event**
                  GLEntry."VAT Amount" := "Amount (LCY)" - GLEntry.Amount;
                END;
                GLEntry."Additional-Currency Amount" := "Source Currency Amount";
                IF "Source Currency Code" = AddCurrencyCode THEN
                  AddCurrGLEntryVATAmt := "Source Curr. VAT Amount"
                ELSE
                  AddCurrGLEntryVATAmt := CalcLCYToAddCurr(GLEntry."VAT Amount");
              END;

[IntegrationEvent] OnSalesTaxReverseCalculateTax(VAR GenJournalLine : Record "Gen. Journal Line";SalesTaxBaseAmount : Decimal;GLEntry : Record "G/L Entry")

**Comment by dNsl9r** [comment]
Should be posted in ALAppExtensions: [https://github.com/Microsoft/ALAppExtensions/issues](url)
