### ISSUE TITLE
Error modifing TableRelation: Token StartAttribute in state Element Content would result in an invalid XML document

### ISSUE THREAD

**Issue by frivadulla** [microsoft/AL#5027]
**Describe the bug**
If you modify a field of a table, and in that modify you modify TableRelation and also you include a trigger, then you will get the following error:

_The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Token StartAttribute in state Element Content would result in an invalid XML document._ 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7207127/58556486-74b19100-821c-11e9-98d6-30e0fb3b52ae.png)

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 14.0.29530.31705

**Comment by thloke** [comment]
Hi,

Could you provide us with a code sample that reproduces the issue? Having a clear repro will help us in processing this issue faster.

Thanks,
Thaddeus

**Comment by Verndroid** [comment]
```
        modify("Creditor No.")
        {
            TableRelation = "SomeTAble";

            trigger OnAfterValidate()
            var
                something: Codeunit "something";
            begin
            end;
        }
```

This should reproduce it.

**Comment by frivadulla** [comment]
I think you dont need more input, Verndroid show you the case.

Kind regards.

**Comment by ajkauffmann** [comment]
Just wondering, as far as I know the TableRelation property is not available for tableextension. See also this overview: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-table-properties

**Comment by atoader** [comment]
@ajkauffmann that looks like a documentation bug. Thank you for pointing it out!
