### ISSUE TITLE
warnings for Text Overflow don't come up

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL#5029]
With the spring release, you have longer Item Descriptions and Customer Names (and similar fields). When you create a new app using AL:Go! and then replace "HelloWorld.al" with this code, I would expect warnings about a text overflow in those two lines:

`
            CustName := cust.Name;
`

`
            ItemDesc := item.Description;
`

However, I do not get any warnings. I would consider this an issue when trying to rely on the dev tools to warn about issues and then not finding them. 

Here is the code for HelloWorld.al. This was tested with the latest docker image on "Microsoft/bcsandbox:us", using compiler 3.0.1.41121 and AL extension version 3.0.106655.

`
table 50103 "test"
{
    Caption = 'Test';
    DataClassification = SystemMetadata;

    fields
    {
        field(1; PrimaryKey; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = SystemMetadata;
        }
        field(2; ItemDesc; Text[50])
        {
            Caption = 'Item Description';
            DataClassification = SystemMetadata;
        }
        field(3; CustName; Text[50])
        {
            Caption = 'Customer Name';
            DataClassification = SystemMetadata;
        }
    }

    keys
    {
        key(PK; PrimaryKey)
        {
            Clustered = true;
        }
    }

    procedure TestMe()
    var
        cust: Record Customer;
        item: Record Item;
    begin
        if cust.FindFirst() then
            CustName := cust.Name;
        if item.FindFirst() then
            ItemDesc := item.Description;
    end;
}
`

**Comment by atoader** [comment]
@pzentner have you enabled code analysis? If yes, what analyzers do you have enabled?

**Comment by pzentner** [comment]
@atoader yes, I do have code analysis enabled:

    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"
    ]

**Comment by atoader** [comment]
Thank you for confirming! We will investigate.

**Comment by MarcHansenMicrosoft** [comment]
Are you sure that the analyzers are enabled?

Have this in your settings.json
    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"
    ],
    "al.enableCodeAnalysis": true

You can verify if it is enabled by adding a new variable, this should now be shown as unused.

**Comment by MarcHansenMicrosoft** [comment]
![image](https://user-images.githubusercontent.com/33726800/69042729-093dc480-09f2-11ea-8054-40bdc887edee.png)

**Comment by pzentner** [comment]
When I reported that 6 months ago, I did have everything enabled and it wasn't working properly. I know that it does work in the Fall release (2019 wave 2). I have not tested it with any of the old versions again

**Comment by MarcHansenMicrosoft** [comment]
Thanks that explains.
I did a fix to this 3 months back based on another github request.

Marc
