### ISSUE TITLE
Edge in Preview machine

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#503]
Would it be possible to have the Edge Browser in the preview machine by default? Or am I just too stupid to find him :)?

**Comment by StanislawStempin** [comment]
Since the preview VMs are based on Windows Server 2016 the Edge browser is unfortunately not available on them.

**Comment by Gallimathias** [comment]
Ok Pity. I would have liked it. Thanks for the reply Stanislaw.
