### ISSUE TITLE
[AL0468] Length of the table field name must not exceed 30 characters. Longer field names are prone to cause SQL errors. This warning will become an error in a future release.

### ISSUE THREAD

**Issue by BCRog** [microsoft/AL#5034]
How to solve this.

I used this and I Still have same warnings.

```
ObsoleteState = Removed;
ObsoleteReason = 'Lenght must not exceed 30 characters';
```
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/50100471/58861707-4403a880-86af-11e9-8d87-73abc11ceea3.png)

I need to solve all the warnings in order to upgrade my tenant correctly to V14.

AL Language 3.0.126610

**Comment by castordafonte** [comment]
Same here, ObsoleteState is not working.

**Comment by gdrenteriag** [comment]
Hello, What should do to overcome this incident?.
Create a new field with shorter name, mark the old one obsolete and add a ugprade CU. ??

**Comment by AitorLD** [comment]
> Hello, What should do to overcome this incident?.
> Create a new field with shorter name, mark the old one obsolete and add a ugprade CU. ??

@gdrenteriag El problema persiste aun cuando crear un nuevo campo(Esa es la incidencia). En realidad cuando marcas como obsoleto un campo nunca se eliminará de la BC es un borrado lógico que solo desactiva el campo (al menos por ahora). Posteriormente tienes dos soluciones para mover los datos de la vieja variable a la nueva. 
 1- Crear una CU de upgrade como comentas
 2- Crear un proceso que mueva tus datos como tu quieres y cuando tu quieras.



The problem persists even when creating a new field (That's the issue). Actually when you mark as obsolete a field will never be deleted from the BC it is a logical deletion that only deactivates the field (at least for now). Then you have two solutions to move the data from the old variable to the new one.
 1- Create an upgrade CU as you comment
 2- Create a process that moves your data as you want and when you want.

**Comment by gdrenteriag** [comment]
Ok, I understand. it's necessary to create another fields first with the name shorter. I then the rest of the process.

**Comment by atoader** [comment]
I will close this issue as it appears that it has been resolved.
