### ISSUE TITLE
Problem at calculating tax statistics/Vat Amount BC CU07:ES

### ISSUE THREAD

**Issue by jamercues** [microsoft/AL#5035]
Hi
When we view the statistics from a posted invoice or credit memo it does not calculate correctly the "VAT Amount".
If we have 2 or more invoice lines with TAX 0% where the TAX 0% configuration with "VAT Calculation Type" is at "Full VAT", we generate only the "VAT Amount" for the first line.
I’ve checked the code, and have found the problem, in the table 290, function "InsertLine", if the "VAT % + EC%" is different to 0, it calculates again the "VAT Amount" but, if the "VAT % + EC%" is 0, is does not increase the Field "VAT Amount".
Thanks

Original code:
`........`
` "VAT Difference" += VATAmountLine."VAT Difference";`
` "EC Difference" += VATAmountLine."EC Difference";`
`  IF "VAT %" + "EC %" <> 0 THEN BEGIN`
`    "VAT Amount" :=
      ROUND(
        ("Amount Including VAT" - "VAT Base" - "VAT Difference" - "EC Difference") / ("VAT %" + "EC %") * "VAT %",RoundingPrec) +
      "VAT Difference";`
`    "EC Amount" :=
      ROUND(
        ("Amount Including VAT" - "VAT Base" - "VAT Difference" - "EC Difference") / ("VAT %" + "EC %") * "EC %",RoundingPrec) +
      "EC Difference";`
`  END;`
`.........`
 

Suggested fix:
`.........`
`  "VAT Difference" += VATAmountLine."VAT Difference";`
`  "EC Difference" += VATAmountLine."EC Difference";`
`  "VAT Amount" += VATAmountLine."VAT Amount"; //FIX ME`
`  IF "VAT %" + "EC %" <> 0 THEN BEGIN`
 `   "VAT Amount" :=
      ROUND(
        ("Amount Including VAT" - "VAT Base" - "VAT Difference" - "EC Difference") / ("VAT %" + "EC %") * "VAT %",RoundingPrec) +
      "VAT Difference";`
 `   "EC Amount" :=
      ROUND(
        ("Amount Including VAT" - "VAT Base" - "VAT Difference" - "EC Difference") / ("VAT %" + "EC %") * "EC %",RoundingPrec) +
      "EC Difference";`
`  END;`
`...........`

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
