### ISSUE TITLE
jSon string including XML passed via Web Service

### ISSUE THREAD

**Issue by Acora-Michael** [microsoft/AL#5037]
**Describe the bug**
I've published a Nav Web Service which returns a jSon as a string. In this jSon I've included an attribute which contains an XML Test. Below the jSon I'm creating:

`{
   "PIN":"20000",
   "ID":"{8661F9E3-1D87-4FB2-A7BC-795CBE8BFFD4}",
   "OrderId":"1001",
   "CommunicationType":"ORDER CONFIRMATION",
   "XML":"<?xml version=\"1.0\" encoding=\"utf-8\"?><xml>  <Pin>20000</Pin>  <Title />  <FirstName>Test Ltd.</FirstName> </xml>"
}`

When consuming the WS from SOAP UI or any external application, what I get is instead the follow:

`<![CDATA[{"PIN":"20000","ID":"{8661F9E3-1D87-4FB2-A7BC-795CBE8BFFD4}","OrderId":"1001","CommunicationType":"ORDER CONFIRMATION","XML":"<?xml version=\"1.0\" encoding=\"utf-8\"?><xml>  <Pin>20000</Pin>  <Title />  <FirstName>Test Ltd.</FirstName></xml>"}]]>`

As you can see, the Web Service somehow recognises that the jSon includes an XML value and adds the CDATA tag automatically at the beginning of the string.

**To Reproduce**
Just Create a codeunit and publish it as a Web Service. The codeunit can simply contain the following code: 

`
codeunit 50000 WS_NAV
{
    procedure getjSon() jSonStr: text;
    var
        jSonStrRet: Text;
    begin
        jSonStrRet := '{   "PIN":"20000", "ID":"{8661F9E3-1D87-4FB2-A7BC-795CBE8BFFD4}", "OrderId":"1001", "CommunicationType":"ORDER CONFIRMATION", "XML":"<?xml version=\"1.0\" encoding=\" utf-8\"?><xml>  <Pin>20000</Pin>  <Title />  <FirstName>Test Ltd.</FirstName> </xml>"}';
        jSonStr := jSonStrRet;
    end;
}
`

**Expected behavior**
The string should not change when calling the Web Service

**Versions:**

 - AL Language: 0.12.28462

 - NAV 2018 On Premise CU 10: 11.0.24742

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
