### ISSUE TITLE
Sandbox creation from Admin Center

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5038]
**Describe the bug**
Not able to create a sandbox with copy of production data.

**To Reproduce**
Steps and to reproduce the behavior:
Go to admin center
Create a sandbox environment with selecting **Copy environment** option on admin center. Like below.
![image](https://user-images.githubusercontent.com/33481576/58857114-0ceac280-86c2-11e9-9678-96d162468cd3.png)

**Expected behavior**
A sandbox environment should be created with copy of production data. Also it stuck on **Preparing** state.
![image](https://user-images.githubusercontent.com/33481576/58857334-99958080-86c2-11e9-9faa-2d5a39d417b9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/33481576/58857201-458a9c00-86c2-11e9-92ec-f13bef59ed59.png)

**Versions:**

 - Business Central: 14.0.29537.0

Thanks

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
