### ISSUE TITLE
Error on Installing NewNavExp

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#504]
I get again an error in the install script.

Perhaps the user account is linked?

![errorinstall](https://user-images.githubusercontent.com/16351673/29362817-b9e32b3e-828d-11e7-92fa-f9f41b5de67f.PNG)

![error](https://user-images.githubusercontent.com/16351673/29362596-f8166de0-828c-11e7-8cd3-d015e929edcc.PNG)

![nav](https://user-images.githubusercontent.com/16351673/29362599-f8a41d3e-828c-11e7-802c-e9da615d9a70.PNG)

![windows ok](https://user-images.githubusercontent.com/16351673/29362601-f9ec65d4-828c-11e7-87dc-cd2aaf516103.PNG)

![default](https://user-images.githubusercontent.com/16351673/29362605-fd4a764e-828c-11e7-99f3-b3b0dbe1a69b.PNG)

![powershell](https://user-images.githubusercontent.com/16351673/29362607-fe52877a-828c-11e7-8866-8f3326bfbbbf.PNG)

**Comment by freddydk** [comment]
If you are using the aka.ms/navdeveloperpreview, then the new developer experience script has already been run (or it is running).
Look at the landing page and wait until it says Installation Complete.
It seems like it cannot restore the DB because it already has been restored.

**Comment by Gallimathias** [comment]
Unfortunately, the script seems to have failed ^ ^.

My main problem seems to be the Windows user (see above and new screenshot).

I will now delete the machine and make a new one.

![capture](https://user-images.githubusercontent.com/16351673/29445582-ec6e40f6-83e7-11e7-9945-3113efbc100e.PNG)

**Comment by Gallimathias** [comment]
Update: 

Ok, the machine has been deleted and a new one created

No new Nav Experience is installed after launch
Installation Runs an error
I have no access to Navision. The error when attempting to open the client speaks of a protocol error.
I have the VSC extension manually installed but also it has logically no access.
My next attempt would be to uninstall Nav manually and reinstall completely.

![error](https://user-images.githubusercontent.com/16351673/29448953-223306fc-83f9-11e7-9935-1784b1caa330.PNG)
![missmatch](https://user-images.githubusercontent.com/16351673/29448951-1d6c2892-83f9-11e7-87b0-ca40f40130c0.PNG)
![launchfailed](https://user-images.githubusercontent.com/16351673/29448947-194acf7a-83f9-11e7-92a5-461a81378e44.PNG)


![user](https://user-images.githubusercontent.com/16351673/29448956-249bbfe2-83f9-11e7-90ef-c5e1f54e97e7.PNG)

**Comment by freddydk** [comment]
Please shoot me an email at freddyk at microsoft.com with the URL on the landing page on this machine, including the password for the user - then I will have a look.

**Comment by Gallimathias** [comment]
email is on the way

**Comment by Gallimathias** [comment]
@freddydk Have you any news about the problem yet? I tried to set up the NEW EXPERIENCE on my own machine, but I was able to reproduce the problem manually and with the script.

Could it be related to the language settings?

**Comment by Gallimathias** [comment]
Ok the September update doesn't cause any problems anymore. The script is not started automatically but still works very well.

The new Azure image is very well established. Praise be to you.
