### ISSUE TITLE
Problem loading a global variable in a new page

### ISSUE THREAD

**Issue by aetxebarria** [microsoft/AL#5040]
Hi everyone,

I've just created an extension, that works perfectly into my docker, both in windows and web client. 
But when deploying the extension into a cloud installation, I'm finding a problem.
In one of the pages, I have defined a global variable, That global variable is shown in the page. 
While I confirm different lines of that page, I'm doing some calculation, and the result of those calculation is laoded into the global variable, and must be shown into the page. But the value of the variable is not changing.
AS I've said before, in the docker this issue is working perfectly.
May be I should add a new property into the variable ort the page itself?
Thak you very much

**Comment by aetxebarria** [comment]
I've just made more tests, and I get new info, that drives me mad....
I'll try to explain as good as possible. `    page 50201 «Time Tracking Entries»
    {
    Caption = ‘Movs. seguim. tiempo’;
    PageType = Worksheet;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = «Time Tracking Entry»;
    SourceTableView = SORTING («Posting Date», «Resource No.», «Time-from», «Movement Type») WHERE (Confirm = FILTER (false), Posted = FILTER (false));
    DelayedInsert = true;
    ShowFilter = false;
    RefreshOnActivate = true;

    layout
    {
    area(Content)
    {
    field(gTotalTime; gTotalTime)
    {
    ApplicationArea = all;
    Caption = ‘Total tiempo:’;
    //Editable = false;
    Enabled = false;

    }
    repeater(group)
    {

    field(Confirm; Confirm)
    {
    ApplicationArea = All;

    trigger OnValidate()
    var
    lTimeTrackingEntryCheckConfirmed: Record «Time Tracking Entry»;
    lText002: TextConst ESP = ‘Las lineas deben seguir la secuencia Inicio-Parada’;

    begin

    CurrPage.SaveRecord();
    gTotalTime := gBeteaStandardFunctions.CalcDuration;
    CurrPage.UPDATE(TRUE);

    end;
    }
    }
    part(Subpart; «Time Tracking Subpart»)
    {
    ApplicationArea = All;
    }
    }
    }`

As you can see, "gTotalTime " is the global variable that gets the result of a funticion. That function is called every tiem we confirm a line from the list. Once the line is confirmed, that line should be shown in the subpart you can see. 
The behaviour of the development isn't the same all the clients. This is happening:
- Docker Windows clients: Everything works correclty, the total is being calculated, and the lines are shown in the subpart when updateing the currpage.
- Docker Web Client: The totals are being correctly calculated, but the lines aren't shown in the subparte. If I close the paget, and open it again, they lines are correclty shown in the subpart (Problem with the update of the subpart)
-BC online version: The subpage is correctly update when I confirm the lines, and the lines are shown correctly in the subpart. But the total is not being updated.

I'm going crazy with all this scenarios.... Any tip will be really appreciated.

Thank you!

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
