### ISSUE TITLE
StyleExpr does not work in Repeaters/Lists

### ISSUE THREAD

**Issue by marknitek** [microsoft/AL#5045]
**Describe the bug**
StyleExpr should work for Repeater Controls as well but it does not. It seems like colors are not supported/working for repeater controls.
The same StyleExpr on a Control on a Card Page do work as intended.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a List Page and add Controls in a Repeater with StyleExpr:
```
repeater(Control1) 
{
                field(Ambiguous; 'Ambiguous')
                {
                    Style = Ambiguous;
                    ApplicationArea = All;
                }
                field(Attention; 'Attention')
                {
                    Style = Attention;
                    ApplicationArea = All;
                }
                field(Favorable; 'Favorable')
                {
                    Style = Favorable;
                    ApplicationArea = All;
                }
                field(StandardAccent; 'StandardAccent')
                {
                    Style = StandardAccent;
                    ApplicationArea = All;
                }
                field(Strong; 'Strong')
                {
                    Style = Strong;
                    ApplicationArea = All;
                }
                field(StrongAccent; 'StrongAccent')
                {
                    Style = StrongAccent;
                    ApplicationArea = All;
                }
                field(Subordinate; 'Subordinate')
                {
                    Style = Subordinate;
                    ApplicationArea = All;
                }
                field(Unfavorable; 'Unfavorable')
                {
                    Style = Unfavorable;
                    ApplicationArea = All;
                }
}
```
**Expected behavior**
The Styles should be rendered on repeaters the same way as in regular/card controls.

**Screenshots**
Issue with Repeater:
![image](https://user-images.githubusercontent.com/2346803/58894684-b9dd3380-86f2-11e9-9c32-75bf099d9bcb.png)
Working Card Example:
![image](https://user-images.githubusercontent.com/2346803/58894865-0de81800-86f3-11e9-9516-f9bd6dd44b93.png)

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 14.0 Spring Release

**Comment by AskeHolst** [comment]
Colors are not shown on a selected lines, try creating multiple lines or un-select the line.

**Comment by fvet** [comment]
Reported this sometime ago on the Yammer group as well. Colors should be respected, even on selected lines. How would you be able to distinguish favorable from unfavorable?

**Comment by AskeHolst** [comment]
I'm not saying colors _should_ not be shown, that is a valid suggestion for [bcideas](https://aka.ms/bcideas) (it would require changing the colors so the text is still readable when highlighted with a light teal background).
But it is not a bug, it is clearly by design (to solve the readability issue).
The issue was about it not working at all, I just pointed out that a selected line is a special case.

**Comment by marknitek** [comment]
@AskeHolst thanks for clarification. Actually I was only testing with one line and was realy surprised that it was not working... 
So this issue seems **partly** resolved, altough I think it should render colors even on selected lines because not all repeater controls show light teal background on selected lines, and even then the style colors are not rendered.

Here is an example of that behaviour on a matrix page (where i actually need the feature)
![image](https://user-images.githubusercontent.com/2346803/58934233-247d8600-876a-11e9-9bf1-2a3ec7a6056d.png)
![image](https://user-images.githubusercontent.com/2346803/58934278-3fe89100-876a-11e9-9d86-2f88e6fb3050.png)
![image](https://user-images.githubusercontent.com/2346803/58934299-568ee800-876a-11e9-9d9b-69140c37c6a8.png)

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by fvet** [comment]
@thloke Do we really need to vote for something that was actually working fine in RTC and is no longer available in webclient? Seems like a lost feature / bug to us.

**Comment by dtkb** [comment]
It seems this got fixed in the meantime. Good, as it would've been insufferable otherwise!
