### ISSUE TITLE
Can't see the contents of an XML or a long Text

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#5048]
I'm currently debugging an existing app where XML are exchanged with an external system and I've discovered that in BC14/runtime 3.0 I can no longer see the contents of the XML, even if I write them into a text variable, because both the XML variable and Text variable are truncated in the debugger.

So yeah, it is nice that now I don't need to write the XML into a Text variable to see its value, but the feature is killed by the fact that now I can only see the first few lines (I can see the namespaces, yay!) and I can not debug any problems with the contents of the XML.

In order to reproduce this problem:
* Load an XML (it doesn't have too big) into an XML variable.
* Write the XML into a Text variable using the "WriteTo" method.
* Try to read the contents of either the XML or the Text variables.

My problem is currently with an XML, but this would be problem in any project where data is interchanged through HTTP (that is, where no disk files are created) using Text or XML messages.

Tested on VS Code 1.34 + AL Extension 3.0.126610, connected to a 14.1.31955.0 (ES) docker.

**Comment by esbenk** [comment]
It is truncated by design. If we don't truncate the a very large string (or xml)  it can kill or seriously degrade the debugging experience. We could maybe raise the limit, but we can't allow arbitrary long strings.

**Comment by jglathe** [comment]
Can‘t you just link for the object (content)? Whoever clicks that link knows it will take some time, but at least you could download and analyze it.

**Comment by esbenk** [comment]
There is some limitations in what we can do with the VsCode debugger interface/protocol. I agree that the user would accept to wait after a click. We will investigate and see if we can make that work with the VsCode debugger protocol.

**Comment by thloke** [comment]
Hi,

Thanks for the suggestion, we have added this to our internal backlog, but at this stage we do not have an ETA. To help us prioritize this, you can create an idea at our ideas form: https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. 

Thanks,
Thaddeus
