### ISSUE TITLE
Most of TestPage functions not working in AL

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#505]
Trying to create automated testing in AL doesn't seem possible. List of functions not working ("The type or method <name> cannot be used for 'Extension' development":
	• FindFirstField
	• FindNextField
	• FindPreviousField
	• GetOption (field level)
	• OptionCount(field level)
	• GetValidationError(document and control level)
	• ValidationErrorCount(document and control level)
	• Activate
	• AsBoolean
	• AsDecimal
	• AsInteger
	• AssistEdit
	• AssertEquals
	• Caption
	• Drilldown
	• Lookup
	• SetValue
	• Value
	• Filter functions (FILTER property it self isn't recognised)
		○ Ascending
		○ Currentkey
		○ GetFilter
		○ Setcurrentkey
		○ Setfilter
	• Invoke
	• Enabled
	• Visible

**Comment by esbenk** [comment]
The functions is unblocked in the August preview, but there are still some known issues.

Find*Field() have issues with the first argument
The Filter property is still not implemented
