### ISSUE TITLE
HTTP Client POST failed to retrieve oauth2 token

### ISSUE THREAD

**Issue by marybricco** [microsoft/AL#5050]
- AL Extension Version: 3.0.126610

- Server Version: 14.0.29537.0

    var
        ReqBody: Text;
        RespBody: Text;
        XMLDoc: XmlDocument;
        URL: Text;
        contentHeader: HttpHeaders;
        request: HttpRequestMessage;
        Client: HttpClient;
       Content: HttpContent;
      response: HttpResponseMessage;
Code-
        URL := 'https://us.api.concursolutions.com/oauth2/v0/token';
        request.SetRequestUri(URL);
        request.Method := 'POST';
        Content.Writefrom(ReqBody);
        Content.GetHeaders(contentHeader);
        contentheader.remove('Content_Type');
        contentheader.remove('Content_Length');
        contentHeader.add('Content_Type', 'application/x-www-form-urlencoded');
        contentHeader.add('Content-Length', '437');
        request.Content := Content;
        client.Send(request, response);
Result-
Debugger stops on client.send with error- An error occurred while sending the request. 
Note- Content type and content legth are required.

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
