### ISSUE TITLE
Currpage.close does not work as expected on pagetype confirmationDialog and Onvalidate trigger do not react on enter

### ISSUE THREAD

**Issue by MortenRa** [microsoft/AL#5051]
[Dialog Test.zip](https://github.com/microsoft/AL/files/3261510/Dialog.Test.zip)
We have 2 issues related to pagetype= confirmationDialog when using Onvalidate trigger

1. using currpage.close do not close the page after the onvalidate trigger is done

2. If you default some input into a field on a confirmationDialog page eg. on OnOpenPage you can not press enter to initiate the onvalidate trigger code to be triggered. 
You have to enter some new text, this works in C/AL if you press ctrl+enter but not in the webclient and a scenario where this could be an issue would be in a scanner scenario where you do not want to write the input you need, but just need to confirm this by pressing enter to go to next step in the flow.

**Steps and to reproduce the behavior:**
I have attached a simple app that shows the problem, add Page 50101 as the startuppage in launch.json for issue 1 press enter

for step 2, enter something different to trigger the validation code, and a message should be shown but the dialog page do not close automatically.

**AL Code to reproduce the issue**
See attached files

Expected behavior
1. Expect the onvalidate code to be trigger when pressing enter og ctr+enter without changing the text in the input field.
2. expect the dialogpage to close when onvalidate code has been triggered.

**Versions:**
 - AL Language: 3.0.106655

**This is no longer searchable  but under help**
 - Business Central: Version: Platform 14.0.29530.31705 + program 31808 (DK Dynamics NAV 14.0)

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
