### ISSUE TITLE
Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized.

### ISSUE THREAD

**Issue by VikalpSharma** [microsoft/AL#5053]
Can anyone help me on below issue.
When i'm trying to read the data from the D365 standard Rest API response getting the below error "Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized." 
Below is the code i'm using :
```
var
        client: HttpClient;
        Content: HttpContent;
        gHeaders: HttpHeaders;
        lHeaders: HttpHeaders;
        Request: HttpRequestMessage;
        Response: HttpResponseMessage;
        Url: Text;
        APIKey: Text;
        RString: Text;
        lText: Text;
        ResHeaders: HttpHeaders;
        ResContent: HttpContent;
Begin 
lText := 'scope=APIServices&grant_type=client_credentials';
Content.Clear();

        Content.WriteFrom(lText);
        Request.SetRequestUri(Url);
        gHeaders.Clear();
        lHeaders.Clear();

        Content.GetHeaders(lHeaders);
        lHeaders.Remove('Content-Type');
        lHeaders.Add('Content-Type', 'application/x-www-form-urlencoded');
        Content.GetHeaders(lHeaders);

        Request.GetHeaders(gHeaders);
        gHeaders.add('accept', 'application/Json');
        gHeaders.add('authorization', APIKey);
        Request.Content(Content);
        Request.GetHeaders(gHeaders);
        Request.Method := 'get';
   
        IF client.Send(Request, Response) THEN
            IF NOT Response.IsSuccessStatusCode THEN
                Error('Web service returned error:\\' + 'Status code: %1\' + 'Description: %2',
                        Response.HttpStatusCode(), Response.ReasonPhrase());

        Response.Content().ReadAs(RString);
        JsonReadWrite.ReadJSonToJSonBuffer(RString, JsonBuffer);
END;
```
Getting the error at this line : Response.Content().ReadAs(RString);

**I have allowed the Httpclient in extension.**

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: Platform 14.0.29530.32718 + Application 32618 (W1 14.0)

Thanks a lot !

**Comment by SUD-D365** [comment]
Hi Habibi,

Can you please add below line before this **Response.Content().ReadAs(RString);** line. And then try.
ResContent := Response.Content();

Thanks

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
