### ISSUE TITLE
How to hide Faxtboxes on sales order list page?

### ISSUE THREAD

**Issue by yogipatel07081992** [microsoft/AL#5054]
Version : plateforme 14.0.29530.32718 + application 32630 (CA Dynamics NAV 14.0)

**Comment by qutreson** [comment]
Hi @yogipatel07081992, you should define a page extension object to modify the visibility of the fact box.
See our documentation on [Page Extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)

**Comment by qutreson** [comment]
Please note that this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your future questions please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
