### ISSUE TITLE
Nav 2017 CU 29 -  Web client bug- the application closes when searching in a page that has a duration field

### ISSUE THREAD

**Issue by bogdan81GitHub** [microsoft/AL#5056]

**Comment by bogdan81GitHub** [comment]
[Web client Bug.docx](https://github.com/microsoft/AL/files/3275557/Web.client.Bug.docx)

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by bogdan81GitHub** [comment]
Partner source  - tehnical support is not working. Could you please, advice me where can I address the request for support?


![image](https://user-images.githubusercontent.com/30693206/59329846-2c03d880-8cf0-11e9-892d-183c9a3088d9.png)

**Comment by bogdan81GitHub** [comment]
Same problem happens also in Business Central.

![image](https://user-images.githubusercontent.com/30693206/59333908-9c632780-8cf9-11e9-87e0-65e1c3a3dffd.png)
