### ISSUE TITLE
UICop Rule AW0006 not throwing error for application area

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5057]
**Describe the bug**
Although I have the UICop enabled, all the actions are not marked with the error "Missing Application Area"

**Expected behavior**
Throw the errors like for fields

**Versions:**

 - AL Language: Name: Version: 3.0.126610

 - Business Central: 140 RTM

**Comment by SUD-D365** [comment]
#4969

**Comment by SUD-D365** [comment]
#4969

**Comment by thpeder** [comment]
Hi @stefanoPrimo, 

[UICop Rule AW0006 ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0006-useusagecategoryproperty) is there to make sure a page or report is searchable.
I think what you are looking you can find in the [PerTenantExtensionCop Rule PTE0008](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop-pte0008-useapplicationareaproperty)

**Comment by stefanoPrimo** [comment]
hi @thpeder  
yes, sorry, I was looking exactly to PerTenantExtensionCop Rule PTE0008
