### ISSUE TITLE
Navision 2018 extension menu items disapears

### ISSUE THREAD

**Issue by dzafon** [microsoft/AL#5059]
Hi,

Sorry by my english is not good.

I have a problem with my extension menu items in a client. When I install my extension all the items appear but at the time they disappear. I have two databases (test and production) and I only have this problem in the production database.

I checked the license and all the objects are included.

I'm working with servers of www.1clickfactory.com.

Does anyone know what is the problem?

Trank

**Comment by Joriek** [comment]
Hello, 

What CU are you using? We had the same issue with one of our customers. Upgrading to the last CU of 2018 will fix this. 
Even a better solution would be to upgrade the customer to the latest BC since performance and development tools are much better there.

Regards,
Joriek

**Comment by dzafon** [comment]
Hello,

We are using the CU 10. I will upgrade to the last CU as you say.

I will inform you if the issue is resolved.

Thank you

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
