### ISSUE TITLE
Question/issue about extending/using other extension

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#506]
In my app.json I've specified a standard extension as a dependency: 
    {
      "appId": "29b9a394-eea5-4018-9d24-32b77a33ffb4",
      "name": "PayPal Payments Standard",
      "publisher": "Microsoft",
      "version": "1.0.17816.0"
    }
The symbols were downloaded successfully and I can see a navx file in packages folder. But when I'm trying to build my extension the following error is thrown: error AL1023: The package file <path>\packages\Microsoft_PayPal Payments Standard_1.0.17816.0.navx is not valid
Error: The package could not be created.

**Comment by StanislawStempin** [comment]
The reason is that PayPal is Extension V1. We do not support scenarios that mix Extensions V1 and Extensions V2. We expect all extensions to be migrated to V2 eventually.
