### ISSUE TITLE
ControlNames are no longer surrounded double quotes

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5060]
**Describe the bug**
It seems like control names (containing one word / no spaces only) were enclosed by " in previous versions. When modifying an existing AL file with the latest AL extension, the " are removed?

![image](https://user-images.githubusercontent.com/25268332/59343195-924a2480-8d0b-11e9-9af2-77dce38f8ca5.png)

**Versions:**

![image](https://user-images.githubusercontent.com/25268332/59343294-d5a49300-8d0b-11e9-8c41-61c7f92430be.png)

**Comment by thloke** [comment]
Hi,

Thanks for raising this. Do you have more detailed reproduction steps? Does this happen even when the AL extension is disabled? And are there any actions such as saving that are performed before the double quotes are removed?

Thanks,
Thaddeus

**Comment by fvet** [comment]
It seems like related to the CRS extension, not to the AL extension. I'll report an issue in this repo instead.
