### ISSUE TITLE
[2019-06-11 04:42:43.19] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: ForceHandleTrackingEvent failed to acquire a lock

### ISSUE THREAD

**Issue by Rathnakmr** [microsoft/AL#5062]
Hi,

I am facing the below issue, while trying to publish in visual code. I am facing this error only after publishing directly through **Upload Extension** in sandbox.

Now I have to publish through visual code, Please provide any solution to fix this.

[2019-06-11 04:42:43.19] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: ForceHandleTrackingEvent failed to acquire a lock

**Comment by 48010** [comment]
I am facing the same issue but trying to download symbols

**Comment by AitorLD** [comment]
Same issue here. Can't download symbols and cant pusblish too.

**Comment by 48010** [comment]
It also takes a lot of time befor getting this error

**Comment by asaez85** [comment]
Same issue here.

**Comment by AitorLD** [comment]
Try to change app and platform version from 14 to 13. It works for me but It has no sense.

**Comment by johndcollins** [comment]
I have the same issue downloading symbols from my sandbox. Takes a long time for the error.

**Comment by thloke** [comment]
Hi all,

We are aware of this issue, and are working to get a hotfix deployed to production as soon as possible. Unfortunately, we do not have any workarounds for this issue. Thanks for your patience.

In the future, please contact support for issues impacting production.

Thanks,
Thaddeus

**Comment by thloke** [comment]
Hi all,

We are in the process of rolling out the hotfix now. When it will be available depends on your region, but we expect to complete the rollout across all regions within 24 hours.

Thanks,
Thaddeus

**Comment by BSSIRajbir** [comment]
I have the same issue downloading symbols from my sandbox.

**Comment by muazmd** [comment]
having the same error when trying to publish to sandbox or download symbols 
I am using V19
