### ISSUE TITLE
Multiple published extensions

### ISSUE THREAD

**Issue by Rathnakmr** [microsoft/AL#5064]
Hi, 

I am facing the below issue, while trying to publish in visual code. Please provide some solution.

[2019-06-13 04:53:29.04] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use.

Regards,
Rathnakumar

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
