### ISSUE TITLE
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Sequence contains more than one element

### ISSUE THREAD

**Issue by LaurenzDolly** [microsoft/AL#5067]
Hi all! 

When I try to publish my extension onto a Sandbox environment I get the following error: 

_The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: Sequence contains more than one element_ 

I didn't change anything to the code.. 
I cloned the repo onto a new system and cleared VS Code Cache since that was suggested in ticket: [https://github.com/microsoft/AL/issues/4940](4940)

I also gave a new version number to my extension. 
I deleted the XLF files and some other folders to see if it has something to do with some AL files. 

My colleagues cloned the repo on their system but the issue persists. 
If I upload the extension manually onto the Sandbox, no errors are given and the extension is installed correct. 

Any suggestions what else I could do? 

Thanks in advance! 

**Version:** 

- Business Central SaaS Version: 14.0.29537.29654 
- AL Version; 3.0.126610

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
