### ISSUE TITLE
Upgrade NAV2018 to BC issue

### ISSUE THREAD

**Issue by torr3400** [microsoft/AL#5069]
I am upgrading a NAV2018 database to BC 13 CU1 and when I get to task 11 (Run the schema synchronization on converted database) I get the following error message:

"Microsoft Dynamics 365 Business Central server is currently not ready to serve requests"

The NAV2018 database is without modifications.

If I change the BC130 service  to use the demo database it works perfect.

The service is using Network service and Network service is dbowner

Any Ideas what's wrong?

**Comment by torr3400** [comment]
I have solved. I created a new server and did the work there. But I still don't understand why it didn't work locally.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
