### ISSUE TITLE
Virtualized file system for handling temporary files in the online service

### ISSUE THREAD

**Issue by chiecnhanco** [microsoft/AL#507]
![image](https://user-images.githubusercontent.com/26807095/29402636-e411cba4-835f-11e7-99ec-19cd28747f13.png)

**Comment by AndriusAndrulevicius** [comment]
not yet supported https://github.com/Microsoft/AL/issues/376

**Comment by StanislawStempin** [comment]
File handling is not available in SaaS since it would allow you to operate on the server's filesystem. We have plans to provide a virtualized, temporary file system but no specific timeline yet. 
Would it be feasible to use streams and blobs to handle your scenario?

**Comment by NicolaiEsbensen** [comment]
@StanislawStempin  can you elaborate a bit on your plans for the virtualized file system? 
Will it be a new type or do you plan for the existing types (File table, FILE.* and File type) to work with the
new virtualized file system. The reason this is of interest is due to the amount of refactoring we will have to do will depend heavily on this.

**Comment by StanislawStempin** [comment]
We do not have a detailed design for it yet. I will use this issue for tracking and share an update once we are closer to working on this area.

**Comment by ivandjordjevic** [comment]
Hey @StanislawStempin, any news on using File handling from extension 2.0?

Our idea is to create a temporary file on server temp location and then prompt the user to download that file from web client? Is this possible at the moment? I see that for example FileMgt.ServerTempFileName is not exposed for extension development.

**Comment by fvet** [comment]
@StanislawStempin, bump up.

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
