### ISSUE TITLE
WEB API 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#5072]
can anyone suggest me that, how we can call or run BC webapi through Docker Container?

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
