### ISSUE TITLE
Rule137DoNotDeclareVariablesThatAreUnused ArgumentNullException with empty options

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#5076]
**Describe the bug**
A combination of an Option parameter with empty string and local variable declaration causing an ArgumentNullException in CodeCop.

**To Reproduce**
```    
procedure AnalyzerException(someOptions: Option FirstOption,,LastOption): Boolean
var
    removeMeToRemoveExceptions: Boolean;
begin
    exit(removeMeToRemoveExceptions);
end;
```
The above procedure causes the following exception:
*Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule137DoNotDeclareVariablesThatAreUnused' threw an exception of type 'System.ArgumentNullException' with message 'System.ArgumentNullException: Value cannot be null.*

If you either remove the local variable OR give a proper name to the empty option, the exception disappears.

**Exception**
```    
procedure AnalyzerException(someOptions: Option FirstOption,,LastOption): Boolean
var
    removeMeToRemoveExceptions: Boolean;
begin
    exit(removeMeToRemoveExceptions);
end;
```

**NO Exception**
```    
procedure AnalyzerException(someOptions: Option FirstOption,SecondOption,LastOption): Boolean
var
    removeMeToRemoveExceptions: Boolean;
begin
    exit(removeMeToRemoveExceptions);
end;
```

**NO Exception**
```    
procedure AnalyzerException(someOptions: Option FirstOption,,LastOption): Boolean
begin
    exit(removeMeToRemoveExceptions);
end;
```

**Expected behavior**
No exception in first example procedure.

**Versions:**
 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.126610
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

Example app: [AnalyzerException.zip](https://github.com/microsoft/AL/files/3301219/AnalyzerException.zip)

**Comment by tinfister** [comment]
Try to use
someOptions: Option FirstOption,"",LastOption;

**Comment by MODUSCarstenScholling** [comment]
Well, it's not the option or the option values that are the problem, but rather the fact that something like that, which is valid code, must not lead to an exception without getting information about the code position. Fixing is our smallest problem.

**Comment by MarcHansenMicrosoft** [comment]
Fixed

**Comment by MODUSCarstenScholling** [comment]
Thank you!
