### ISSUE TITLE
REP295 Combine Shipments - OnAfterShouldFinalizeSalesInvHeader event gives ErrorParameterMismatch

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#5077]
**Describe the bug**
Trying to subscribe on `OnAfterShouldFinalizeSalesInvHeader` in REP295 Combine Shipments.
Even with the correct subscriber event, the Event Subscriptions keeps giving `ErrorParameterMismatch`, although the AL-compiler gives no errors.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create subscriber on OnAfterShouldFinalizeSalesInvHeader` in REP295 Combine Shipments
2. Place a function in it with a breakpoint or an UI element.
3. Debugger won't stop at that point or show the UI

``` AL Code to reproduce the issue ```
![Subscriber](https://user-images.githubusercontent.com/34303738/59751764-62f26500-9281-11e9-9f8d-1a68ddc4739b.png)

**Expected behavior**
Event triggers

**Screenshots**
![Publisher](https://user-images.githubusercontent.com/34303738/59751696-4ce4a480-9281-11e9-843e-f00e1f4151a8.png)

![Publisher2](https://user-images.githubusercontent.com/34303738/59751704-4f46fe80-9281-11e9-8b8a-2d30c0344311.png)

![EventSubscription](https://user-images.githubusercontent.com/34303738/59751771-65ed5580-9281-11e9-8161-e57de1f69608.png)

**Versions:**

 - AL Language: al-3.0.106655

 - Business Central:
Microsoft_Application_14.0.29537.31808
Microsoft_System_14.0.29530.31705
- Docker: BCSandbox:be

**Comment by matteomontanari** [comment]
Hi
Same issue here. 
Exception "ErrorParameterMismatch" is raised when adding "Finalize" parameter.
But it works if you add a C/AL subscriber with finsql.

Something like a parameter called like a c# reserved word? (Object.Finalize() ?)

AL Language 3.0.145991
BC14 W1 RTM

Matteo

**Comment by atoader** [comment]
Hi! We believe this issue has been fixed in the 2019 Wave 2 release and in any CU7 and later of the 2019 Spring release. Please feel free to reopen the issue if you can still reproduce it.
