### ISSUE TITLE
Error AL0427 - when defining Flowfield of field which property SQLDataType = Integer

### ISSUE THREAD

**Issue by qperis** [microsoft/AL#5079]
**Describe the bug**
I am getting compiler error when trying to define new flowfield type code[20] with property SQLTadaType = Integer.
Error text: Field "MyFlowFieldB" cannot be converted to type Code[20].AL(AL0427)

I tried to change field's MyFlowFieldB type from Code to Integer, had no effect.
I tried to remove field's MyFlowFieldB property SQLTadaType = Integer, had no effect.
Field MyFieldA must be SQLTadaType = Integer.

**To Reproduce**
table 17025508 "TableA"
{
    DataClassification = ToBeClassified;
    
    fields
    {
        field(1;"MyFieldA"; Code[20])
        {
            Caption = 'MyFieldA';
            DataClassification = ToBeClassified;
            SqlDataType = Integer;
        }
        
    }
    
    keys
    {
        key(PK; "MyFieldA")
        {
            Clustered = true;
        }
    }
    
}
table 17025509 "TableB" 
{
    DataClassification = ToBeClassified;
    
    fields
    {
        field(1;"MyFieldB"; Code[20])
        {
            Caption = 'MyField';
            DataClassification = ToBeClassified;
            SqlDataType = Integer;
        }
        
        field(2;"MyFlowFieldB"; Code[20]) //Error on this line
        {
            Caption = 'MyFlowFieldB';
            SqlDataType = Integer;
            FieldClass = FlowField;
            CalcFormula = Lookup ("TableA"."MyFieldA" WHERE (MyFieldA = FIELD (MyFieldB)));
        }
        
    }
    
    keys
    {
        key(PK; "MyFieldB")
        {
            Clustered = true;
        }
    }
    
}
**Expected behavior**
I expect successfully compile the object.

**Screenshots**

**Versions:**
 - AL Language: 3.0.126610 (- 3.0: Business Central Spring '19 Release)
 - Business Central: 14.0.29530.0

**Comment by atoader** [comment]
Hi! It appears that the compiler was emitting the wrong metadata and this property was ignored. We have fixed the compiler to emit the correct metadata, but this means that if you have an extension where the SqlDataType property was set to anything other than Varchar, you will have to do the following when upgrading to the new platform:
1. Remove the property from this field and obsolete the field
2. Create a new field and set the SqlDataType property 
3. Write upgrade code that takes the values from the old field and moves them to the new field while accounting for possible conversion issues.
