### ISSUE TITLE
Dialog Data Type - Dialog not showing up

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#508]
I'm trying to create a dialog from a page, but the dialog never show up.
I have created a new page and opened the page directly, then I copy/pasted the example from the [How to: Create a Progress Window](https://msdn.microsoft.com/en-us/library/dd338672(v=nav.90).aspx) guide. Now when I click the button to start the dialog, I get nothing but the little spinner on my curser, telling me something is happening.

Is this not working or is it not supposed to work on all types of pages in the webclient?

**Comment by atoader** [comment]
Is this what are you trying to run? Is the ProgressWindow a global variable?
page 70000009 MyAwesomePage
{
    PageType = Card;

    actions
    {
        area(processing)
        {
            action(ActionName)
            {
                trigger OnAction();
                begin
                    ProgressWindow.OPEN('Processing account number #1#######');
                    REPEAT
                        SLEEP(1);
                        ProgressWindow.UPDATE(1,ChartOfAcc."No.");
                    // Process the account.
                    UNTIL ChartOfAcc.NEXT = 0;
                    ProgressWindow.CLOSE;
                end;
            }
        }
    }
    
    var
        ProgressWindow : Dialog;
        ChartOfAcc : Record "G/L Account";
}

**Comment by RasmusTidselbak** [comment]
This is what I have done.
![2017-08-17_15-37-46](https://user-images.githubusercontent.com/2745613/29415079-0d316ee8-8362-11e7-889e-4bba0cdc7bb5.png)

**Comment by atoader** [comment]
Try making it a global variable. The runtime might now support it as a local variable.
![image](https://user-images.githubusercontent.com/3097909/29415199-865336a8-8362-11e7-8c5e-1201f8f824c7.png)

**Comment by RasmusTidselbak** [comment]
That did it, thanks 👍

**Comment by RasmusTidselbak** [comment]
Actually I just tested with the local variable instead.
It seems that the dialog doesn't show up right away and there might be a 3-5 second delay, I was not aware of, before anything is shown for the user.

**Comment by AMCJN** [comment]
I just tried this in our extension, and I can't get it to Work.
Only thing happens is the little spinner on my cursor, telling me something is happening.

What am I doing wrong ? or does this still not Work.

**Comment by AMCJN** [comment]
Sorry it does Work, but it takes a LONG time for the Dialog to show.
Will have to make som other solution.
