### ISSUE TITLE
.rdl file handling

### ISSUE THREAD

**Issue by xamsFooBar** [microsoft/AL#5081]
**Describe the bug**
In latest CU of NAV2018, we are experiencing following problem:

- We can not right click on an .rdl file and choose 'open externally'
![open external]
(https://user-images.githubusercontent.com/33894304/59921634-a3dbac80-942e-11e9-85b4-8709344df073.PNG)
- When we add a field to the dataset, the field is not being added to the .rdl file when building

VSC version 1.35
AL Language extension version (used from DVD): 0.13.11304

if we use another AL Language extension , eg. 2.1.109895, then we can 'open externally' and the fields are getting added to the .rdl file, but we can not publish because the runtime version is not supported anymore...

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
