### ISSUE TITLE
Attachment page api return error

### ISSUE THREAD

**Issue by robertzengcn** [microsoft/AL#5082]
Hello All, I try to query the attachment page api, because I want to know the data structure in D365 business center, and upload attachment, but after I visit the api, I get follow error:

{
    "error": {
        "code": "Application_CallbackNotAllowed",
        "message": "Microsoft Dynamics 365 Business Central Data Services attempted to issue a client callback to create a DotNet object: Microsoft.Dynamics.Nav.Client.Capabilities.CameraProvider (Page 2322 BC O365 Inc. Doc. Attch. List). Client callbacks are not supported on Microsoft Dynamics 365 Business Central Data Services."
    }
}

May I know how to solve it ? and How to upload file by attachment api

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
