### ISSUE TITLE
Can not open Saas Business Central Sandbox

### ISSUE THREAD

**Issue by SandipDomadiya** [microsoft/AL#5085]
> **Something went wrong.
> Could not open the '' company. Sorry, we just updated this page. Reopen it, and try again.
> Date and time: Wed, 26 Jun 2019 05:57:23 GMT
> Go back home**

I am facing this error while opening business central sandbox of Australian localization.
And Because i can not open the sand box i can't give you the other specification information.

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
