### ISSUE TITLE
[feature-request] Improve syntax definitions to allow more highlighting options

### ISSUE THREAD

**Issue by widrsde** [microsoft/AL#5087]
The alsyntax.tmlanguage file contains only 17 patterns, with only 1 (procedure/trigger) real syntax pattern.

With few ways to change the code highlighting, this makes writing AL code in Visual Studio Code seems like writing code in a text editor.

Is it possible to extend the alsyntax file, or perhaps a repository to contribute?

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
