### ISSUE TITLE
Execute flowfield for native-table.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#509]
Hi All !
I have a case as below:
 - I add more fields into "G/L Entry" table.
 - I add new table, add a flowfield which collect data from "G/L Entry" which reference new field of "G/L Entry".
   
![image](https://user-images.githubusercontent.com/24407031/29403318-3613d97c-8362-11e7-8e08-834775b85e86.png)
![image](https://user-images.githubusercontent.com/24407031/29403409-7168ba06-8362-11e7-8895-578bd54308a9.png)
![image](https://user-images.githubusercontent.com/24407031/29403490-a56c7b94-8362-11e7-8b98-1ed3cac238bf.png)
![image](https://user-images.githubusercontent.com/24407031/29403456-8ce6ae0a-8362-11e7-9130-2b5690a4863a.png)

After I build, publish and test this extension. I get the error:
![image](https://user-images.githubusercontent.com/24407031/29403588-f20ec1c8-8362-11e7-99ef-b7fe8d23d817.png)

Maybe, I understand this error: because new field of "G/L Entry" table is in a companion table.
**But this case is a demand really**.
_So, this case will be supported in next builds or have another solution to solve this problem ???_

Note: I tested on the build: Version W1 10.0 10.0.18032.0 (August Update).

**Comment by StanislawStempin** [comment]
This is a bug, it was also reported under #501.
