### ISSUE TITLE
System Layer Event Request

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/AL#5090]
Please create an event in the system layer that can be used to trigger a discovery between extensions.

    [IntegrationEvent(false, false)]
    procedure OnDiscovery(var ReferenceRec: Variant)
    begin
    end;

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by gunnargestsson** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=d41d5706-f197-e911-80e7-0003ff688f4e
