### ISSUE TITLE
OData parallel loading error

### ISSUE THREAD

**Issue by rivolemmik** [microsoft/AL#5091]
**Describe the bug**
PowerBI is getting error message when loading data from BC OData v4 feed with parallel loading enabled.

Error message in PowerBI: The remote server returned an error: (400) Bad request: (Sorry we just updated this page. Reopen it, and try again.)

Error message in BC server Event Log: Another user has modified the record for this 5151 after it was retrieved from the database. Identification fields: Integration ID

**To Reproduce**
AL Extension Query objects are published as WebService.
PowerBI is connected to BC OData feed with parallel loading enabled.

**Expected behavior**
Parallel loading data from BC OData feed without error message.

**Fix**
Codeunit 5150 - Integration Management
Add LOCKTABLE on Integration Record table update
```
[External] InsertUpdateIntegrationRecord(RecRef : RecordRef;IntegrationLastModified : DateTime) IntegrationID : GUID
IF IsIntegrationRecord(RecRef.NUMBER) THEN
  WITH IntegrationRecord DO BEGIN
    //+RLE
    LOCKTABLE;
    //-RLE
    IF FindByRecordId(RecRef.RECORDID) THEN BEGIN
.
.
```

**Screenshots**
![PowerBI_Conf](https://user-images.githubusercontent.com/47107018/60167326-90a05680-980b-11e9-9573-177e630ed600.png)
![PowerBI_Error](https://user-images.githubusercontent.com/47107018/60167327-90a05680-980b-11e9-896c-158579318f98.png)

**Versions:**
 - AL Language: 3.0.124247
 - Business Central: 14.0.32615.0

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

**Comment by nikolakukrika** [comment]
We have looked into the issue and the decision is to won't fix for now. Introducing LOCKTABLE would impact the performance in a negative way, and this is a high traffic table. We are working on discontinuing the Integration Record table, the optimizations will be done at that point.
