### ISSUE TITLE
Warning when publishing OIOUBL.APP: Length of the table field name must not exceed 30 characters

### ISSUE THREAD

**Issue by CorpitalMAS** [microsoft/AL#5092]
**Describe the bug**
When publishing OIOUBL.APP I get a warning: Length of the table field name must not exceed 30 characters.

When I got to the source of the OIOUBL.APP extension I can see that, among others, name of field 13635 "OIOUBL-Sell-to Contact Phone No." in tableextension 13630 exceeds 30 characters.

**To Reproduce**
1) Download MS Dynamics Business Central on-premises for DK-Danmark . 
2) Publish the OIOUBL.app with powershell in a Business Central that do not have OIOUBL.app already published and installed earlier.

```
$serverinstance = "INSERT SERVERINSTANCE HERE"
$extensionpath = "C:\Dynamics.365.BC.Spring2019.29537.DK.DVD\Extensions\OIOUBL.app"
Publish-NAVApp -ServerInstance $serverinstance -Path $extensionpath -SkipVerification
```

**Expected behavior**
I would expect the OIOUBL.app to be published .

**Screenshots**
![image](https://user-images.githubusercontent.com/40602188/60175513-17593180-9814-11e9-8aa4-fea0e0023c8f.png)

**Versions:**
 - Business Central: 14 Spring2019.29537

**Comment by OleTeichmann** [comment]
I think the reason it is not publishing is, that Table "OIUBL Profile" is missing.

**Comment by CorpitalMAS** [comment]
> I think the reason it is not publishing is that Table "OIUBL Profile" is missing.

Hi Ole, 

The table 13600 "OIOUBL Profile" is not missing.

Why do you think the table was missing?

**Comment by OleTeichmann** [comment]
Because you can publish an app regards of warnings and the only error I see in your screenshot is:
![image](https://user-images.githubusercontent.com/41419577/60182554-d0276c80-9824-11e9-8b3c-25fc5c42017c.png)

**Comment by CorpitalMAS** [comment]
I did not see that. My bad. After I enabled loading application symbol references at server startup, a restart and synk. it published and installed without problems. Thanks Ole
