### ISSUE TITLE
Ambiguous call in json GetValue.ToObject

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/AL#5094]
When using txt2al on [kaufmanns ](https://github.com/ajkauffmann/DynamicsNAV/blob/master/ODataWebServiceExample/NAVODataWebServicesExample.txt) excellent json functionality I am now getting an error for the functions using DateTime
DotNetDateTime := JObject.GetValue(PropertyName).ToObject(GETDOTNETTYPE(DotNetDateTime));

**Describe the bug**
Compilation error/warning "The call is ambiguous between the following methods or properties: 'ToObject(DotNet "Newtonsoft.Json.JsonSerializer")' and 'ToObject(DotNet "System.Type")'AL(AL0196)"

``` AL Code to reproduce the issue ```
Add/create dotnet.al
    assembly("Newtonsoft.Json")
    {
        Version = '4.5.0.0';
        Culture = 'neutral';
        PublicKeyToken = '30ad4fe6b2a6aeed';

        type("Newtonsoft.Json.Linq.JObject"; MyJObject) { }
    }

    assembly("mscorlib")
    {
        Version = '4.0.0.0';
        Culture = 'neutral';
        PublicKeyToken = 'b77a5c561934e089';

        type("System.Datetime"; MyDatetime) { }
    }

Cod50000.al
    procedure GetValueAsTime(JObject: DotNet MyJObject; PropertyName: Text) ReturnValue: Time
    var
        DotNetDateTime: DotNet MyDateTime;
    begin
        DotNetDateTime := JObject.GetValue(PropertyName).ToObject(GETDOTNETTYPE(DotNetDateTime));
        ReturnValue := DT2TIME(DotNetDateTime);
    end;

**Expected behavior**
No errors. 

Same code in C/AL will not throw an error
Documentation()
OnRun()
LOCAL GetValueAsTime(MyJObject : DotNet "Newtonsoft.Json.Linq.JObject";PropertyName : Text) ReturnValue : Time
DotNetDateTime := MyJObject.GetValue(PropertyName).ToObject(GETDOTNETTYPE(DotNetDateTime));
ReturnValue := DT2TIME(DotNetDateTime);
ots to help explain your problem.

**Versions:**
 - AL Language: 3.0.124247
 - Business Central: 14.0.32615

**Comment by plagijat** [comment]
Hi,

Same issue here. 

> The call is ambiguous between the following methods or properties: 'DeserializeObject(DotNet "System.String", DotNet "Newtonsoft.Json.JsonConverter[]")' and 'DeserializeObject(DotNet "System.String", DotNet `"Newtonsoft.Json.JsonSerializerSettings")'`

When trying to use DeserializeObject Method of JsonConvert using the following code:
```
StatusNET := JsonConvert.DeserializeObject(StatusNew, GetDotNetType(StatusNET));
```

> **JsonConvert.DeserializeObject Method - Overload List**
DeserializeObject(String)
DeserializeObject<T>(String)
DeserializeObject<T>(String,JsonConverter[])
DeserializeObject(String, JsonSerializerSettings)
DeserializeObject<T>(String, JsonSerializerSettings)
DeserializeObject(String, Type)
DeserializeObject(String, Type,JsonConverter[])
DeserializeObject(String, Type, JsonSerializerSettings)

So the sixth method is not recognized as usable one.

However, I came out with a workaround, by declaring StatusNETType variable as DotNet of Type and passing it to the DeserializeObject Method - call is not ambigous anymore:
```
procedure SetDocumentStatus(User: Integer; StatusNew: Text): Text
    var
        StatusNETType: DotNet Type;
        JsonConvert: DotNet JsonConvert;
        StatusNET: DotNet StatusNew;
    begin
        StatusNetType := GetDotNetType(StatusNET);
        StatusNET := JsonConvert.DeserializeObject(StatusNew, StatusNetType);
    end;
```

I expect that the AL compiler should be able determine the output of the **GetDotNetType** as Type and selecting the correct method since this was possible in C/AL and is the main reason for the use of this function.

Best,
Zoran

**Comment by Rukkulakki** [comment]
My issue may have been that I was using an old dll file. Turns out that BC ships with a new version of newtonsoft.json.dll in the Service folder.
When I deleted my own, and instead just declared the new in the dotnet.al file it worked.

**Comment by atoader** [comment]
Hi! This is a more generic issue with how GetDotNetType works. In C/AL, the GetDotNetType method, and a few others, returned a value of type DotNet without specifying the subtype or any additional type information.
In AL, although we added support for strongly typed .NET values, we kept the same interface and we had to add some special cases for supporting this untyped DotNet. One special property of this type is that it can be converted to anything with the same precedence, so if you have two overloads for a method, and you are trying to pass in the return type of a GetDotNetType(...) call, the compiler will not know which one to choose.
The solution for this is the one @plagijat has found. 

I agree that the new compiler could have been smarter, but this would have come at the cost of breaking other scenarios. 

In the last months, we have been hard at work on the next release of the developer tools. You can read Freddy's blog post to find out more https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ . Let us know what you think!

**Comment by atoader** [comment]
As it appears that the main issue has been resolved, I will close this thread.

**Comment by KitoCoding** [comment]
I am also getting this issue. I unfortunately do not understand the proposed solution. can you please elaborate?
