### ISSUE TITLE
"Tenant ID" and Scope fields in "NAV App" table

### ISSUE THREAD

**Issue by martonnagy** [microsoft/AL#5095]
The Scope and "Tenant ID" fields are populated differently from VSCode and PowerShell

1. Publish the AL/Go extension from VSCode, "NAV App" looks like this:

| Name          | Tenant ID | Scope |
|---------------|-----------|-------|
| ScopeTestBC14 | default   | 1     |

2. Uninstall and Unpublish using PowerShell
3. Try to rebublish:
![image](https://user-images.githubusercontent.com/39408604/60197634-a88dcf80-9837-11e9-993d-71846d4e06f0.png)
4. Restart the service tier
5. Republish from PowerShell, "NAV App" looks like this:

| Name          | Tenant ID | Scope |
|---------------|-----------|-------|
| ScopeTestBC14 | **blank**   | **0**     |

"Tenant ID" is blank and the Scope is Global

6. Restart the Service Tier 
7. Uninstall and Unpublish using PowerShell 
8. Republish using "-Scope Tenant -Tenant default" 
9. Reinstall using "-Tenant defult", "NAV App" looks like this:

| Name          | Tenant ID | Scope |
|---------------|-----------|-------|
| ScopeTestBC14 | **blank**   | **1**     |

"Tenant ID" is still blank but the Scope is Tenant

What's going on here? 
Why the same thing from VSCode and PowerShell have different results?
Why PowerShell is disregarding the parametres from Steps 8 and 9?

We are using AL Language Version 3.0.126610 and non-insider VSCode

Cheers,
Marton

**Comment by martonnagy** [comment]
Guys,

any update on this?

Cheers,
Marton

**Comment by kalberes** [comment]
This is really internal stuff, but briefly.
Publishing from VsCode and publishing from powershell are not the same things. When you publish from VsCode you will publish in the tenant scope a developer extension. When you publish from powershell you will just publish into the global or tenant scope.  But these are not developer extensions.
Developer extensions are special and targeted only to VsCode publishing.

**Comment by martonnagy** [comment]
Hi Kálmán,

so this is the right behaviour then? What about point 3? How can I republish?

Cheers,
Marton

P.S.: Szép napot 😃

**Comment by kalberes** [comment]
If a tenant has been published in the tenant scope, and now you want to publish it in the global scope you will have to unpublish it and restart the server :( 

P.S. Viszont kívánom!

**Comment by martonnagy** [comment]
OK, fine then.
At least we know what's going on.
