### ISSUE TITLE
Codeunit is already declared error requires restart of VS Code

### ISSUE THREAD

**Issue by johndcollins** [microsoft/AL#5096]
When I create a new Codeunit I get an error that it is already declared. I have to close the file and the close VS Code. Once I re-open VS Code and the file, the error goes away.

Steps and to reproduce the behavior:
1. Create a new al Codeunit file and save it.
2. The error should appear
3. Close the file
4. Close VS Code
5. Open VS Code
6. Open the file and the error should be gone

 - AL Language: 3.0.126610

**Comment by EDGZTNSR** [comment]
By any chance do you have the "AL Object Designer" installed ?

**Comment by johndcollins** [comment]
No, I don't have that installed at this time. I used to, but never used it so I uninstalled it.
This happened after this was uninstalled and still happens.
![CU Error](https://user-images.githubusercontent.com/1684130/60826741-659af880-a163-11e9-9dd7-bb708326b30e.PNG)

**Comment by johndcollins** [comment]
Here is a better picture of the error. There is no other CU called "PS MyCodeunit".
If I close the file and close and re-open VS Code it is fixed. However, if I don't close the file and I close and re-open VS Code it doesn't fix it.
![CU Error](https://user-images.githubusercontent.com/1684130/60827056-2ae59000-a164-11e9-92e2-1d9d2c873970.PNG)

**Comment by EDGZTNSR** [comment]
Are you developing on your local machine?
There seems to be a problem regarding UNC paths. 
https://www.dynamicstailor.eu/201906/an-application-object-of-type-x-is-already-declared/

**Comment by atoader** [comment]
@johndcollins we could not reproduce the issue locally. Is there any other information that you can provide?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
