### ISSUE TITLE
Report substitution for multiple regions (US/GB etc)

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/AL#5098]
Hi,

Currently we have our product in APP store for US region.
We have substituted standard D365 BC  **Chart of accounts** report and implemented our logic in US region and works fine.
Report Substitution process:
1) Exported the report from V1.
2) Converted it to V2.
3) Imported the report in my project.
4) Assigned new object ID to the report and fixed all compiler errors.
5) substituted the object ID in OnAfterSubstituteReport trigger.
6) Now, when user select **Chart of accounts** in D365 BC, it opens our report and run our logic.

Now, we are trying to publish the same app for UK/GB region.
When i downloaded the UK image and downloaded the symbol in my project, this report error out because the standard **Chart of accounts** in US and UK are different.

Now how do i deal with this issue.

 I can also extract the standard **Chart of accounts** report from UK and invoke the report based on the region, however, when i submit the app to Microsoft for validation, we dont submit separate app for US and separate app for UK. We just send one and select the multiple supported region (in this case US and UK).
IT will not compile my app. 

Please help!!

**Comment by thloke** [comment]
Hi! In this case, our recommendation is to submit two separate extensions for US and UK because the difference in the base app are significant. We don't have any other workaround for this.

**Comment by Bssivivek** [comment]
@thloke thanks!!

**Comment by Bssivivek** [comment]
@thloke quick question - when we submit 2 separate extensions for US and UK,  (everything is the same except the reports) can we use same app ID. in app.json or do we need to have separate app ID per region.

**Comment by thloke** [comment]
@Bssivivek - different app extensions require different app IDs and names. So you will need to name and ID 
 your regional apps differently.

**Comment by SergioKelly** [comment]
> @Bssivivek - different app extensions require different app IDs and names. So you will need to name and ID
> your regional apps differently.

@thloke Can we use the same object id (Ranges) for both App ID?
