### ISSUE TITLE
AppSourceCop should test for translation files regarding supportedLocales in app.json

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5099]
Hello,

I was wondering if the AppSourceCop should raise a warning (or an error) if there is no XLIFF for this locale for one supportedLocales declared in the app.json.

It is mandatory for submitting the app to the app source.

- AL Extension Version: 3.0.145991

**Comment by qutreson** [comment]
Hi @nicolassaleron, we have added a new rule to the AppSourceCop that verifies this: [AS0057 Translations must be provided for all the locales in which the application will be available.](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0057-translationsnotprovidedforlocale).

Note that this rule is not enabled by default (see its default severity [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)). You might then need to use a [ruleset](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools) to enable it.
