### ISSUE TITLE
true keyword is replaced by tprocedure

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/AL#510]
Often when I try to type the "true" keyword, the intellisense think that I am trying to use the "tprocedure" snippet. Which is quite annoying.
I have solved the issue myself, by creating a snippet called true, which just write true. This way the intellisense pick my "true" snippet instead of the "tprocedure".

`"True bug":{
		"prefix": "true",
		"body": "true",
		"description": "True bug"
	},`

**Comment by StanislawStempin** [comment]
We will look into it. I suspect it requires providing "true" as an intellisense suggestion in all valid contexts, which might not be trivial to detect.
