### ISSUE TITLE
Error in when Debugging file import in C/AL

### ISSUE THREAD

**Issue by MarceeMarc** [microsoft/AL#5101]
When attemping to debug C/AL on RTC when importing file for G/L budget.

**To Reproduce**
Steps and to reproduce the behavior:
1. Set breakpoint on OnQueryClosePage of Request Page of report 81 and debug the current or next session. 
2. Go to Budgets page (page 113), and press "Import from File". Error message will read "The metadata object Page 81 was not found.".

``` AL Code to reproduce the issue ```

![metadata](https://user-images.githubusercontent.com/6153719/60424742-e8163c00-9be8-11e9-82d3-cb2f57c46b3e.png)

**Versions:**
 - Business Central: 14.30.32600

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
