### ISSUE TITLE
WDSL codeunit parameter names in lowercase

### ISSUE THREAD

**Issue by dzafon** [microsoft/AL#5103]
Sorry but my english is not good.

Recently we updated one Navision 2018 from CU 10 to 18 and now the parameters of the codeunits published as web services start with lowercase (with the CU 10 they started with capital letters). This generates us a problem since an integration that we have has stopped working. This codeunit is developed in AL extension.

Has anyone the same problem?

Thks

**Comment by atoader** [comment]
Hi! This change is by design. The AL compiler has changed how parameters are named in the emitted metadata. Changing this at this point in time would break existing consumers.
