### ISSUE TITLE
BusinessChartBuffer Methods Disallowed for Extensions

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#511]
Modern dev heroes,

I've got a few methods on the BusinessChartBuffer that are currently off limits that I need.

- AddMeaure
- AddColumn
- SetValueByIndex

Presumably other methods in that table are also not supported, I just haven't tried them. This is all a little academic until we can use the Business Chart control add-in, or have some other means of creating charts, but I'll create a separate issue for that.

Cheers,
JP

**Comment by StanislawStempin** [comment]
These methods have been enabled for the September Update, see #483.

Business Chart control add-in was mentioned in #481, they are not available yet but are high on our priority list.
