### ISSUE TITLE
CodeCop : AA0008 warning allows use and execution of OnPrem functions in BC sandbox

### ISSUE THREAD

**Issue by JuricaB** [microsoft/AL#5114]
**Describe the bug**
Warnings raised by compiler rule AA0008 can hide errors, allowing an app to compile that should not normally compile.

**To Reproduce**
Steps and to reproduce the behavior:

1. Start a new project, set target Extension, turn on CodeCop
2. Create page based on T36 Sales Header
3. Add any trigger/function.
4. In code call  CheckItemAvailabilityInLines;
5. AA0008 reports warning "You must specify open and close parenthesis..." 
6. Add parentheses
7. Warning transforms to error AL0296 - function is marked as internal in T36

``` AL Code to reproduce the issue
page 50000 Test
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Sales Header";

    trigger OnAfterGetCurrRecord()
    begin
        CheckItemAvailabilityInLines;
    end;
}

page 50000 Test
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Sales Header";

    trigger OnAfterGetCurrRecord()
    begin
        CheckItemAvailabilityInLines();
    end;
}
```

**Expected behavior**
I expect errors to be raised as higher priority than warnings, warnings should never overrule the errors.

**Versions:**

 - AL Language:  3.0.145991

 - Business Central: Microsoft_Application_14.1.33107.0 ; Microsoft_System_14.0.32600.33003

**Comment by atoader** [comment]
Hi @JuricaB ! We will investigate this as soon as possible. 

In the last months, we have been hard at work on the next release of the developer tools. You can read Freddy's blog post to find out more https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ . Let us know what you think and especially if you still encounter this issue.

**Comment by JuricaB** [comment]
HI @atoader,

This is still an issue with Wave 2 - replicated on 4.0.182565. 

Furthermore, the error is somewhat worse than I thought, as it also allows you to use functions marked as OnPrem in bc sandbox docker. 
See below, screenshots taken on new 15.0 docker:
![image](https://user-images.githubusercontent.com/24306390/66018267-dcfddf80-e53a-11e9-9864-b45618a6b227.png)
![image](https://user-images.githubusercontent.com/24306390/66018290-f56dfa00-e53a-11e9-8506-a608628b1ff6.png)
