### ISSUE TITLE
Page OnValidate is not triggered in Chrome

### ISSUE THREAD

**Issue by lukacetko** [microsoft/AL#5115]
**Describe the bug**
The OnValidate of the page is not triggered when changing the value in fhe field and then clicking to the empty space (not a control or button/link).
It seems to only be an issue with chrome and certian page configurations.

**To Reproduce**
Use attached examples. 
[PageValidateTrigger.zip](https://github.com/microsoft/AL/files/3368303/PageValidateTrigger.zip)

Steps:
1. Open Page ExampleNoRecord in Chrome (tested with latest version - 75.0.3770.100)
2. Enter 1 into the MyInteger field. **Do not press enter or tab.**
3. **Click** into the empty space below (on the page) -> **Validate is NOT triggered**
4. Click on Show Attached -> **Validate is triggered**

Step 3 will trigger in IE Version: 11.2848.14393.0
Step 3 will not trigger in RTC but the control will not lose focus.

``` 
page 70004 ExampleNoRecord
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    layout
    {
        area(Content)
        {
            group(TestGroup)
            {
                field(MyInteger; myInt)
                {
                    ApplicationArea = All;

                    trigger OnValidate()
                    begin
                        Message('Page OnValidate triggered!');
                    end;
                }
            }
        }
    }

    var
        myInt: Integer;
} 
```

The Isssue seems to be related to the group element.
If there is no group element on the page it works as expected but if there is one if fails to call OnValidate. Also if PageType is List and it contains group elements the issue is **not** present.

There are 3 additional Example pages in the example app.
1. Page ExampleRecordCard**WithoutGroup** - OnValidate is triggered
2. Page ExampleRecordCard**WithGroup** - OnValidate is **NOT** triggered
3. Page ExampleRecord**TypeList** - OnValidate is triggered

**Expected behavior**
Step 3 should trigger OnValidate. As I understand it field con
trol losing focus should trigger OnValidate if the contents were edited.

**Versions:**
 - AL Language: 3.0.106655
 - Business Central: Platform 14.0.29530.0 Application 29537 (W1 14.0)

**Comment by atoader** [comment]
Hi @lukacetko ! Does this issue still reproduce on the latest D365 Business Central preview? You can find more information here https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ .

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
