### ISSUE TITLE
Debug without publishing starts incorrect sandbox

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5117]
**Describe the bug**
The option Debug without publishing starts webclient with sandbox name 'sandbox', instead of using the sandboxname setting from the launch.json

**To Reproduce**

``` 
        {
            "name": "Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "tenant": "mytenant.com",
            "sandboxName": "dev"
        }
 ```

With these settings, the webclient is started as https://businesscentral.dynamics.com/mytenant.com/sandbox instead of https://businesscentral.dynamics.com/mytenant.com/dev

It is possible to correct the url in the browser, after which the debugging session will still work.

**Expected behavior**
Web client should be started with correct sandbox name.

**Versions:**
 - AL Language: 3.0.145991

**Comment by ajkauffmann** [comment]
Update - seems to be a problem with updating the setting from launch.json
Closing and reopening the workspace resolves the issue.

**Comment by kalberes** [comment]
@ajkauffmann I think this has been fixed. If not please reopen the issue.
