### ISSUE TITLE
You do not have permission to insert 'OData Edm Type' records because the tenant is mounted with the application database as read-only on Cloud Sandbox

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#5120]
I having issue when publish Install codeunit for "OData Edm Type" table in Cloud sandbox.
Tested in Hosted Sandbox no issue. Is it limitation for BC oncloud ?

![image](https://user-images.githubusercontent.com/34825577/60938305-1e00a200-a306-11e9-8937-77c7e1d16a72.png)

**Comment by atoader** [comment]
@Tonygithub17 sorry for getting back to you so late. As you have automatically labelled this issue or used the wrong template, we did not triage it.
Were you able to get around this problem?

**Comment by Tonygithub17** [comment]
Still waiting the solution from Microsoft how to solve this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atoader** [comment]
@Tonygithub17 are you able to reproduce this issue on the latest sandbox? Can you please provide the repro?

**Comment by atoader** [comment]
@Tonygithub17 I have just noticed that the issue is described in the title of the issue. I apologize for the confusion. 
This is by design and we will not change it. In a multi-tenant SaaS environment, the application database is read-only.
