### ISSUE TITLE
Production BOM area not visible on US, UK Sandbox Environment

### ISSUE THREAD

**Issue by Rachit14** [microsoft/AL#5121]
Hi,

We are using BC Sandbox Environment for US and UK localization and unable to find the Production BOM pages (all Production related functionality) in this sandbox. However, we are able to work on these pages on OnPrem version of Business Central therefore this does not seems to be a license related issue.. So, anyone please confirm if this a bug or are we missing something here? Screenshot attached below showing no result on searching "Production BOM." 

![image](https://user-images.githubusercontent.com/3817269/60944238-ded25100-a305-11e9-91c1-6c81900c68c8.png)

- AL Extension Version: 3.0.145991

- Server Version: Version: Platform 14.0.29530.31705 + Application 31808 (US Dynamics NAV 14.0)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
