### ISSUE TITLE
NAV 2015 upgraded to BC On Prem. Unable to download the symbol

### ISSUE THREAD

**Issue by ponnadarajesh** [microsoft/AL#5122]
- AL Extension Version: 

- Server Version:

**Comment by ponnadarajesh** [comment]
Hi 

We have upgraded NAV 2015 standard database to Business Central CU8 On prem version. Now trying to create extension but unable to download the symbol. I have tried to run the command and finsql.exe Command=generatesymbolreference, Database="BASENAV2015", ServerName=localhost
and it got successful. try to download the reference still getting error


getting following error:
[2019-07-10 17:03:33.88] Using reference symbols cache path: c:\Users\rponnada\Documents\AL\BCtest_0907\./.alpackages
[2019-07-10 17:03:33.88] Sending request to http://localhost:2119/BCTestNAV15/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-07-10 17:03:33.89] Sending request to http://localhost:2119/BCTestNAV15/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-07-10 17:03:33.90] The request for path /BCTestNAV15/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code ServiceUnavailable. Reason: The tenant 'default' is not accessible.
[2019-07-10 17:03:33.90] The request for path /BCTestNAV15/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0 failed with code ServiceUnavailable. Reason: The tenant 'default' is not accessible.
[2019-07-10 17:03:33.90] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**Comment by sirhc101** [comment]
Hello,

Did you enabled the Developer Service Endpoint and enabled the "Enable loading application symbols at server **startup** " option in Service Administration?
Looks like it's not available!?

Further did you published the System App from the product DVD?

**Comment by ponnadarajesh** [comment]
I have enabled them and tried to publish extension from installation folder

**Comment by BartPermentier** [comment]
Did you install the symbols from the cd?
![image](https://user-images.githubusercontent.com/24684493/61106470-9178ef80-a47d-11e9-8e64-afe84a0e42ad.png)

**Comment by sirhc101** [comment]
Does the windows client connects to service? Do you see the server instance in c/side development environment listed?

The message "The tenant 'default' is not accessible" looks like the service does not work properly!? Any error messages in event log?

**Comment by ricardopaiva** [comment]
Did you enabled the "Developer Service Endpoint" in your Business Central server?
Make sure it is enabled and restart the service then try again.
In the url you have the port 2119. Is this the Developer endpoint port?
Can you paste your launch.json file in here?
Server tag must point to the web client url.
Port tag must be added and must point to Developer service port.

Start by running the Get-NAVTenant command against your server instance and tell the "State" of your tenant. It should be Mounted or Operational.
Even if it's ok, try to run the Sync-NAVApp against your server instance to make sure that your app schema is synchronised against the database.
Finally, make sure that the application family and version are updated. Please take a look at step 10 on this webpage:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data
You may need to run the Sync-NAVApp again after updating the application family/version.

The steps mentioned by BartPermentier will be needed if you get the following error: "Reason: No published package matches the provided arguments."

**Comment by ponnadarajesh** [comment]
Hi All,

Thanks a lot. After implementing *Bart Permentier *suggestion symbols got
downloaded.

**Comment by ricardopaiva** [comment]
Good to hear that although I wasn't expecting it to be resolved (just) with Bart's suggestion.

**Comment by atoader** [comment]
Thank you @sirhc101 , @ricardopaiva, and @BartPermentier  for helping out with this issue!
