### ISSUE TITLE
IntelliSense description for the JsonArray.IndexOf function is wrong

### ISSUE THREAD

**Issue by Jeeve65** [microsoft/AL#5123]
IntelliSense for the method 'IndexOf' of a JsonArray variable  says: 'Replaces the value at the given index with a new value'.  This is wrong.
The developer documentation says: 'Determines the index of a specific value in the JsonArray.'

![JsonArray IndexOf](https://user-images.githubusercontent.com/19321004/60961114-b51c2880-a30b-11e9-9b61-c3b61b034ca8.jpg)

**Comment by bjarkihall** [comment]
I also noticed this one, but reported #5159 too, have you been able to JsonArray.Add values and retrieve their index afterwards?

**Comment by Jeeve65** [comment]
Yes and No ;)
Yes, I can add items to a JsonArray using JsonArray.Add
No, JsonArray.IndexOf doesn't work for me. I don't have to do that a lot, so I just built a custom 'loop-the-loop' function that Gets each array element and compares it to the value that I'm looking for.

**Comment by atoader** [comment]
Hi, @Jeeve65 ! We have fixed the documentation issue in master. We will publish the updated the documentation with the next release.
