### ISSUE TITLE
Target: (Extension/Internal) in app.json file

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/AL#5126]
Hi,
Currently we have our app in app store for D365 BC SaaS.
Currently **we dont specify** the target if it is Extension/Internal in app.json.
We publish the app in docker container and it works fine. We have also submitted the app and its in Microsoft app store.

Now, we were trying to publish the app in D365 BC on Premise.
So, **i created run time package** and installed D365 BC on premise (latest spring version) and i was able to publish the app successfully.
![image](https://user-images.githubusercontent.com/38437776/61007225-24504780-a321-11e9-8801-747d856f51df.png)

But one of our end user who below version
![image](https://user-images.githubusercontent.com/38437776/61007286-506bc880-a321-11e9-98c9-9cbaadaa1616.png)

is getting following error when we try to publish the app using power shell.

![image](https://user-images.githubusercontent.com/38437776/61007374-8446ee00-a321-11e9-97aa-dd28d470f3d0.png)

I tried changing the "Allowed Extension Target Level" to both Extension/Internal and i am still getting the same error

![image](https://user-images.githubusercontent.com/38437776/61007426-a7719d80-a321-11e9-8bb5-69a5a5962a9a.png)

1) Please let me know how to deal with this? is this issue because they are using older version of D365 BC?
2) If we dont specify the target in app.json what is the default value?

**Comment by Bssivivek** [comment]
I tried installing D365 BC on premise version 13.0.26413.0 and I can replicate this issue.
SO, do I need to run that container image 13.0.26413.0 and try creating runtime package? can some one help me out on this?

**Comment by thpeder** [comment]
Hi @Bssivivek,
Runtime packages contains the compiled content that the runtime needs, without the need to run the compiler when publishing the package.
This has the effect that the system you construct the package on needs to match the system you intend to publish it to.

**Comment by Bssivivek** [comment]
@thpender - thanks for the feedback. the issue is because, I was trying to publish runtime package of version14.0 in D365 BC on premise version 13.2 and that's why its erroring out. The error message was misleading and I thought it has something to do with target (internal/extension) that we specify in app.json file. you can close this ticket. thanks again!!

**Comment by thpeder** [comment]
You are welcome, 
Thanks for the feedback that we should consider improving the error message.
