### ISSUE TITLE
[CodeCop Request] for Integer Overflow

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#5127]
I don't know if I'm in the Right place, but it's the best I've found. If not, please direct me to the correct place. 

It would be great if the CodeAnalyzer would detect possible Integer Overflows from decimal. So we avoid error Messages like.
![image](https://user-images.githubusercontent.com/35929603/61029780-17346680-a3bc-11e9-9116-48fe769f7994.png)

Similar to Text Overflow [AA0139](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0139-donotassigntostringwithsmallercapacity)

### [CodeCop Request] for Integer Overflow
When handling Decimal calculactions which are parsed into integer variables there can be an Overflow. 

**Reason for the rule**
To catch possible Overflow before runtime. 

**Bad code sample**
Example of what bad code the rule should catch:
`local procedure DivideSomething(SomeDividend: Integer; SomeDivisor: Integer): Integer
begin
  exit(SomeDividend / SomeDivisor);
end;
`

**Good code sample**
Example of what code should look like:
`local procedure DivideSomething(SomeDividend: Integer; SomeDivisor: Integer): Integer
 begin
 exit(Round(SomeDividend / SomeDivisor,1,'>'));
 end;
`

**Remarks**
I don't know how to explain it any clearer :-(

**Comment by atoader** [comment]
Thank you for the suggestion @JulianTillmann !

**Comment by MarcHansenMicrosoft** [comment]
@JulianTillmann in most cases the value assigned a integer value is calculated at runtime.

I am not sure that we do a lot of static integer overflow.

Could you please elaborate?

**Comment by JulianTillmann** [comment]
@MarcHansenMicrosoft 
When Calculating a number for an integer variable programmers sometimes Forget to use a ROUND() and then there's an error at runtime. It would be great if the developers would get a hint that they Need to re-think their Code. 

The CodeAnalyzer for Text already checks if there could be a possible Overflow, I would like to have the same for Integer.

**Comment by MarcHansenMicrosoft** [comment]
It is still on clear to me.

Could you try to express in this template?
It would be nice if you could place it the main post.
Thanks
Marc

**Title**
Brief, descriptive string, explaining the overall problem. 

**Description**
Longer, descriptive string, elaborating on the problem.

**Reason for the rule**
Description of why this rule is important.

**Bad code sample**
Example of what bad code the rule should catch:

``` Example of bad code ```

**Good code sample**
Example of what code should look like:

``` Example of good code ```

**Good and bad practices for fixing the rule**
Description of good and bad solution to fixing this warning (only add this section if you have additional information besides the good and bad code samples).

**Remarks**
​Add additional comments to the rule in this section.

**Comment by JulianTillmann** [comment]
@MarcHansenMicrosoft 
done

**Comment by MarcHansenMicrosoft** [comment]
Thanks :-)
Is the only solution to the problem round or do see other ways to fix it?

**Comment by JulianTillmann** [comment]
I don't know what all the fixes might look like, I just want a hint from CodeAnalyzer like this
![image](https://user-images.githubusercontent.com/35929603/72732964-309e4280-3b97-11ea-83c4-abca04388a41.png)

**Comment by JalmarazMartn** [comment]
I come here to make the same suggestion , because I got yesterday the same overflow error, and it is very hard to find...and I respecfully think it could be very easy to implement code cop rule in two basic situation, direct assign: MyInteger := MyDecimal and parameter in procedure calling: 
MyProcedure(MyDecimal)
.....
procedure MyProcedure(MyInteger: Integer)

I think you can use the same pattern you use to detect Text overflow. Do you think you can do it in short term? Must this be posted in Microsoft ideas instead here?

Thank you very much!!
