### ISSUE TITLE
Referencing Standard Fields in Key Added by TableExtension

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#513]
1. Create a tableextension object to extend the Sales Header table
2. Add a new field in the extension object
3. Add a key that references a standard field in the Sales Header table e.g. Status

"Reference 'Status' in application object 'SalesHeaderExt' does not exist."

**Comment by esbenk** [comment]
See #456

**Comment by jimmymcp** [comment]
Ah, sorry for the duplicate.
