### ISSUE TITLE
Error in Production Order Component

### ISSUE THREAD

**Issue by nilpan20** [microsoft/AL#5131]
**Describe the bug**
When we use 100 Character in Item Card it is producing below error. Due to DataCaptionExp Property. There is a function called "Caption", Which generate the error.

![image](https://user-images.githubusercontent.com/43797630/61059696-10f3b980-a3bf-11e9-87b6-9f4ef5d21249.png)

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Firm Planned Production Order ->  Line - > Component.

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Language: 

 - Business Central:

**Comment by nilpan20** [comment]
It is due to if Production Header's description is near to 100.

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
