### ISSUE TITLE
Control Addins - Cannot read property 'NAV' of undefined

### ISSUE THREAD

**Issue by RickTweede** [microsoft/AL#5132]
I have upgraded a test (on prem) environment to BC Spring edition, and am now having and issue with ControlAddin objects...
When the page with my addin loads the console logs the below...

Uncaught TypeError: Cannot read property 'NAV' of undefined
    at __controlAddInInitialize (?runinframe=1:2)
    at window.onload (?runinframe=1:1)
__controlAddInInitialize @ ?runinframe=1:2
window.onload @ ?runinframe=1:1
load (async)
(anonymous) @ ?runinframe=1:1

I've tracked this down to the startup.js script... (show below)
console.log('Startup Script - OnStartUp');
Microsoft.Dyanmics.NAV.InvokeExtensibilityMethod("OnControlReady",[]);  
console.log('Startup Script - OnAfterStartup');

so i believe it cannot see the Microsoft.Dynamics assembly or the NAV part more specifically.

**Comment by AskeHolst** [comment]
Seems you have Dynamics misspelled, could that be the reason?

**Comment by RickTweede** [comment]
hahaha lol - i'm an idiot

ty
