### ISSUE TITLE
Could not publish new page or table but I can extend any table or page that is exist

### ISSUE THREAD

**Issue by Farzad-Jalali** [microsoft/AL#5134]
I'm using docker and I run an instance of business central on docker for development.
I install te license file successfully and I should be able to create a new table/page based on my license file.

**Note:**
I'm using the latest version of everything including the docker image, AL, visual studio code.

**What I can do:**

I successfully publish the hello world project and then I successfully extend items table and page (list & card), I added a new field to them and it works.

**What I can not do:**

but when I try to create a new page or table I get the below error:
[2019-07-12 16:13:00.22] The request for path /nav/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Your program license does not allow you to publish 'ItemEntityApi2'.
![image](https://user-images.githubusercontent.com/3695669/61139233-da05cc80-a4c0-11e9-99df-6c32e6224d1c.png)

**Comment by pmohanakrishna** [comment]
Did you upload Partner license? or use 50100 to 50149 range.

**Comment by Farzad-Jalali** [comment]
Hi 
thanks for coming back to me.
I have a license which is like the below (I believe it's not a partner license but I'm not sure)
anyway, in top of that I'm using the 50100 to 50149 range.


here is the part of my license in text:

```
Product Line            : Microsoft Dynamics 365 Business Central on premises
Product Edition         : Premium
Product Version	        : 14
Country                 : United Kingdom
Language                : English (US)
Created Date            : 6/26/2019 6:20:30 AM (-07:00)
****************************************************************************
Name                                                                  Amount
----------------------------------------------------------------- ----------
Country Code: Great Britain                                                1
Dyn365 Business Central Application Builder                                1
Dyn365 Business Central Codeunits (100)                                  100
Dyn365 Business Central Codeunits (each)                                  20
Dyn365 Business Central Pages (100)                                      500
Dyn365 Business Central Premium                                           85
Dyn365 Business Central Premium - Upgrade                                170
Dyn365 Business Central Reports (100)                                    100
Dyn365 Business Central Solution Developer                                 1
Dyn365 Business Central Tables (10)                                      250
Dyn365 Business Central XML Ports (100)                                  100

****************************************************************************

```

**Comment by atoader** [comment]
@pmohanakrishna in what range are you trying to publish? You can create extensions to existing objects if your license contains modify permissions and you are using BC Fall 2018 CU1 or later, but if you want to create new objects, your license must contain Insert permissions for those objects.

**Comment by Farzad-Jalali** [comment]
@atoader 
range in my setting file : 50100 to 50149 

* also I have a partner license which supports the range from 50000 -99999
the actual ids which I use are:
* one table extension with id 50100
* two page extension with id 50101, 50102
* new page (API Page) with id 50103

**Comment by atoader** [comment]
This issue seems to be related to your particular license and unfortunately we cannot help you on this forum.
We suggest that you open a support case. To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
