### ISSUE TITLE
Error Downloading Symbols BC On-Prem SQL 2017

### ISSUE THREAD

**Issue by fibbert** [microsoft/AL#5135]
With a SQL 2017 back end, and a standard CRONUS database configuration we receive the error 
Same development environment with the same database connected to SQL 2106 works fine.

Any ideas welcome!

ERROR:

[2019-07-12 13:34:34.90] Using reference symbols cache path: d:\Development\Scratch\newal07122019\./.alpackages
[2019-07-12 13:34:34.90] Sending request to https://localhost:7019/TEST-HANDSHAKE/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0
[2019-07-12 13:34:34.90] Sending request to https://localhost:7019/TEST-HANDSHAKE/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0
[2019-07-12 13:34:34.93] Error: An error occurred while sending the request.
**The underlying connection was closed: An unexpected error occurred on a send.
The handshake failed due to an unexpected packet format.**

AL VERSION: 3.0.145991
SERVER BC On-Prem Fall 2018 CU5

Using AL:Go! Project

Launch.json
"
      "name": "TEST Handshake",
      "type": "al",
      "request": "launch",
      "server": "https://localhost",
      "serverInstance": "TEST-HANDSHAKE",
      "authentication": "Windows",
      "startupObjectId": 89,
      "port": 7019,
      "breakOnError": true,
      "breakOnRecordWrite": false,
      "schemaUpdateMode": "Recreate"
"

App.json
{
  "id": "2b3cc640-e6de-4151-b497-3aae51a72fa3",
  "name": "newal07122019",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://newal07122019.com/help/",
  "showMyCode": true,
  "runtime": "2.0"
}

**Comment by EasyStep2Lean** [comment]
Fibbert,

Same here, any news on how to solve this? I'm using a standard D365 BC Onpremise April CU01 Dutch version. Everything else works like webclient, ODATA interfacing etc, etc.....

![image](https://user-images.githubusercontent.com/17320737/61458178-2db56180-a96a-11e9-9670-f99577169e8e.png)

**Comment by atoader** [comment]
@fibbert @EasyStep2Lean does the event log on the machine running the service contain any additional information?

**Comment by EasyStep2Lean** [comment]
I will have a check but the normal event logs are clear and normal when starting the NST

Any other logs I have to look into

ps SP2 didn't solved the issue

**Comment by jensmpmsft** [comment]
Not something I have heard of before, but the symptom is the same as you will get if you get http and https mixed up - or in case of a missing / wrong certificate. So the first thing I would check would be the certificates and setup of SQL Server and NST.

**Comment by EasyStep2Lean** [comment]
Hi Jens,

No https but only http at this server, but are yoy suggesting only https is supported?

**Comment by atoader** [comment]
Hi! Are you still encountering this issue? Did you find a workaround?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
