### ISSUE TITLE
The type or method 'CreateTempFile' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by adk107** [microsoft/AL#5136]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Language: 

 - Business Central:

**Comment by adk107** [comment]
This method does not work on Cloud Version. What can we use in place of that.?

**Comment by boych83** [comment]
You need to use Streams.

**Comment by atoader** [comment]
Hi @adk107 ! You will find several similar issues in this repository. As boych83 suggested, you should use streams for this.

To get help more help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
