### ISSUE TITLE
Development for customers with BC on premise..

### ISSUE THREAD

**Issue by srinivasdes** [microsoft/AL#5138]
Hi ,

We have developed an extension and deployed to one of our client BC on premise via Publish-NAVApp. So our standard extension functionality is working fine. 

But our client requested some additional customization which is very specific to him. Part of that we have to use new customized field (Which is created by their own extension) in sales price table. In order to proceed with we need to utilize the client customized field in our own development server. 

**Question :**  How can we get the client customization in to our development, Is there any way to get the symbols to proceed with the developing a new dependent extension and deploy to clients.

Please help me on this..

Thanks.

**Comment by srinivasdes** [comment]
Anyone please help me on this..

**Comment by OleTeichmann** [comment]
Are you able to get the app file from your customer? If so then you can implement that in your extension via dependencies in app.json :)

**Comment by srinivasdes** [comment]
Hi OleTeichman,

Thanks for you reply.

I have the customer's app. when i update the app id in dependencies symbols are downloading to see the client customized field in my visual studio for code.

can you please explain how can i download the symbols of customer's app through dependency. I knew we can able to get the symbols from any app by app id if that app is in app store.

**Comment by atoader** [comment]
If you have customer's app file you should:
1. Publish the app file to your server. If you have an on-prem server/Docker, you can use Publish-NavApp to accomplish this. You can follow https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2 
2. Connect with VSCode to your server and download the symbols.
3. Compile your project against the downloaded symbols.

Of course you can also add the app file to you .alpackages folder for your solution and compile against that, but I guess you will want to test this E2E.

For questions of this type, you should ask on:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
