### ISSUE TITLE
Not able to deploy extension to tenant through Extension Management

### ISSUE THREAD

**Issue by kavila02** [microsoft/AL#5139]
I created an AL Extension and it deploys and publishes when I publish locally through VS Code but when I try to upload to customer's BC tenant, I get the following error:

Deployment failed. Errors: App ID : eda53984-2de3-4895-8755-292b0dcde658 Message : { Failure status code InternalServerError returned } - Job Id : 41403e1e-7a96-44ed-a660-83f297697154

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 

 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
