### ISSUE TITLE
Fields and actions not visible since August update

### ISSUE THREAD

**Issue by MrDavid5465** [Microsoft/AL#514]
I installed the august update, but when I publish the extension that I am working on to any of the D365 Instances, none of the fields or actions on pages, both new or extended, show up. My code in triggers like onopenpage runs though.

![image](https://user-images.githubusercontent.com/29601581/29412423-b8fbafe0-8326-11e7-9777-e7f0f25aa85a.png)
![image](https://user-images.githubusercontent.com/29601581/29412455-e6b3d7b4-8326-11e7-8bfc-8763843ec68f.png)

**Comment by MrDavid5465** [comment]
![image](https://user-images.githubusercontent.com/29601581/29412495-0da7a4cc-8327-11e7-8407-dc2bee16ca63.png)
![image](https://user-images.githubusercontent.com/29601581/29412541-41f907ac-8327-11e7-8083-f544ebce7a7d.png)

**Comment by MrDavid5465** [comment]
I just found that the applicationarea property needs to be set to fix this issue. is there a way to set this globally for the entire extension

**Comment by esbenk** [comment]
Yes. The change is the August preview is running Financials were the ApplicationArea is required. Unfortunately the is no global way. 
We are consider/investigate if we can "inherit" from the parent group/area.

**Comment by bachii1010** [comment]
Hi 

We also missed this application area in our addon is there a way to update in bulk for all the fields and actions in our addon.

Please suggest.

Thanks & regard
Varun Reddy

**Comment by hvogelpohl** [comment]
Jepp, I was also confused. The _Hello World_ sample isn't updated, so I spent some time to figure out. Since it's the first example on the azure image I think it should be updated. :-)

**Comment by esbenk** [comment]
Good point. We will update the samples.

**Comment by lvanvugt** [comment]
Made my da,y guys!
