### ISSUE TITLE
Export multiple file with XmlPort 

### ISSUE THREAD

**Issue by RioArfn** [microsoft/AL#5142]
Hi,

I want to export 2 files from BC SaaS. The first file is the main XML file and the second is trigger file. How to do it?
I tried to use Xmlport.run() twice in a trigger on a page, but it's only export the last xmlport.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
