### ISSUE TITLE
New Role Center activity / insight cues not working in BC Cloud

### ISSUE THREAD

**Issue by PP1986** [microsoft/AL#5144]
I have added a new section with activities / insights. They worked perfectly fine in both cloud and on prem, but all of a sudden randomly stop working in the cloud. For example, with the same extension installed in two different BC Cloud Sandbox environments, in one them it never worked, while in the other it did work for at least a while. 
Once it stops functioning, there seems to be no way to get it back to working again.
On prem, I have not experienced the issue yet at all.

Expected behavior:
Same like the standard BC Role Center activities and insights blocks. They show the corrent numbers and on click the dropdownpage shows.
What it does now is show zero's only and when clicking on them a 'something went wrong' error occurs.

![image](https://user-images.githubusercontent.com/44785533/61291407-bc8d7700-a7ce-11e9-971a-4c869473ae17.png)

 - AL Language: 3.0.145991

**Comment by erikrijn** [comment]
Same issues here.
The same codebase does work in onprem:14.1.32615.0-w1 but not in the current cloud sandbox.

**Comment by PP1986** [comment]
I have found the issue, it was related to the filtering on one of my flow fields. The error message however is not the most helpful.
