### ISSUE TITLE
Need support for Runtime: 3.2

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/AL#5145]
I'm not able to publish my extension.  

[2019-07-16 14:14:08.53] This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 3.2
- Web API: 3.0
- Debugger: 2.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0
- Supported Web API: 1.0, 2.0, 3.0
- Supported debuggers: 1.0, 2.0

**Comment by atoader** [comment]
@AmandaTest can you please update your extension and try again?

**Comment by qutreson** [comment]
This issue is now fixed after a new version of the AL extension was published to the market place.
