### ISSUE TITLE
Caption not translated/not working

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5146]
**Describe the bug**
As you can see from the image below:

1. The caption `Create Document Preview` it is not found in the entire project (red color)
2. The real caption is different and has the correct translation (yellow color)
3. The green color is to underline the current page id

![image](https://user-images.githubusercontent.com/36199751/61377236-165f7100-a8a3-11e9-965b-573c0b84fca2.png)

**Versions:**

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.145991
Publisher: Microsoft

 - Business Central: Business Central 14.0 RTM - IT Localization

**Comment by atoader** [comment]
@stefanoPrimo what is the generated ID for this action? Is it the same as in the it-IT.xlf ? Could it be that they went out of sync?

**Comment by stefanoPrimo** [comment]
Hi,
If I don't remember wrong they had the same ID (using the past because I have to modify the caption and the problem disappears)
also because the compilation output didn't show up any errors.

**Comment by AndreyKorepanov** [comment]
Hi @stefanoPrimo. When you build the app you can find the generated xlf-file (something like "Electronic Invoice for Italy.g.xlf"). To make sure that the objects are not out of sync please compare it with the existing one "Electronic Invoice for Italy.it-IT.xlf". trans-unit id must be the same in both files. If they are not the same, just replace the old id with the correct one from g.xlf.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
