### ISSUE TITLE
TableRelation on page does not rely on the control but on the source expression

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5148]
**Describe the bug**
Hello,

I have noticed the following behaviour when we had to develop an wizard page.
We ask the user to select an Item No. and depending on previous selection, we display the control ItemNoA or ItemNoB, both linked to the global variable ItemNo.

The difference between these fields is the TableRelation.
An unexpected behaviour is that the TableRelation is correct on ItemNoA but incorrect on ItemNoB: ItemNoB uses the same TableRelation as ItemNoA.

It looks like the tablerelation rely on the source expression instead of the control.

You will find an simplified version below.

**To Reproduce**
Steps and to reproduce the behavior:
1. Publish this page:

 ```
page 8117310 "MyPage"
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

 layout
    {
 area(Content)
        {
 group(GroupName)
            {
 field(ItemNoA; ItemNo)
                {
                    ApplicationArea = All;
                    TableRelation = Item where (Blocked = const (true));
                }
 field(ItemNoB; ItemNo)
                {
                    ApplicationArea = All;
                    TableRelation = Item where (Blocked = const (false));
                }
            }
        }
    }

 var
        ItemNo: Code[20];
}
 ```

2. Look the lookup of each list: it is the same.

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**Versions:**
 - AL Language: 3.0.152816
 - Business Central: 14.0.29530.31705

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
