### ISSUE TITLE
Analyzer 'Microsoft.Dynamics.Nav.UICop.Rule003RepeaterWithPartsCannotBeDisplayed' threw an exception of type 'System.InvalidCastException'

### ISSUE THREAD

**Issue by kine** [microsoft/AL#5149]
When compiling one of our app, I am getting this warning:

```
##[warning] Analyzer 'Microsoft.Dynamics.Nav.UICop.Rule003RepeaterWithPartsCannotBeDisplayed' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IPageTypeSymbol'. |  
-- | --
  | at Microsoft.Dynamics.Nav.UICop.Rule003RepeaterWithPartsCannotBeDisplayed.AnalyzeRepeater(SymbolAnalysisContext ctx) in F:\a\91\s\source\Prod\Microsoft.Dynamics.Nav.UICop\Rules\Rule003RepeaterWithPartsCannotBeDisplayed.cs:line 49 |  
  | at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in F:\a\91\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658 |  
  | at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in F:\a\91\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1082'


```
Because I do not know if it is related to AL code compiled or the codecop itself, I can reproduce it just by opening the VSCode with the wrokspace with my project. The warning is automatically displayed in the "Problems" tab and is "connected" to app.json file. But when I open different project, all is ok.

Screenshot from VSCode:
![image](https://user-images.githubusercontent.com/110221/61465177-d5855c00-a977-11e9-903f-201b697f5832.png)

Same error in CI pipeline:
![image](https://user-images.githubusercontent.com/110221/61465237-f9e13880-a977-11e9-85c2-bc95e11b57a5.png)

**Versions:**
 - AL Language: 3.0.150570

Docker image platform: 14.0.34195.0

**Comment by kine** [comment]
Ok, we have found the problem and I can write the reproduce steps for you:

The analyzer fails when you add Repeater to Report Request Page:
![image](https://user-images.githubusercontent.com/110221/61513783-70c11480-a9fe-11e9-83d7-010a22105477.png)

Repro steps:
1) Create new app, enable UICop
2) Add report
3) Set source table for the request page
4) Add repeater to the request page

**Comment by atoader** [comment]
Thank you for the repro, @kine !
