### ISSUE TITLE
Bulk Insert for Standard API Error

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#5150]
I having issue when i try bulk insert record to BC Item table it show me below error message.
{
    "error": {
        "code": "BadRequest",
        "message": "An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected."
    }
}

![image](https://user-images.githubusercontent.com/34825577/61501510-32c5ef80-aa02-11e9-98a3-35412aded64d.png)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by jlrfarooq** [comment]
Hi,
any idea what is the solution of this issue please? I am having similar runtime Error
