### ISSUE TITLE
Getting error in sorting 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#5151]
i have extended the table "Payment Registration Buffer" table no : 981 
i added two new filed which are flow fields and calculated from "sales invoice header" 

![image](https://user-images.githubusercontent.com/38460823/61524305-d7acf080-aa33-11e9-828b-890cef860101.png)

now, when i open the "register customer payment" and then try to sorting [asc or desc ] with that field 

![image](https://user-images.githubusercontent.com/38460823/61524383-03c87180-aa34-11e9-82d2-14bc81c33ac3.png)

then i am getting following error

![image](https://user-images.githubusercontent.com/38460823/61524483-28244e00-aa34-11e9-8c9e-703726a5c5bf.png)

guys, do you have any idea about this?

**Comment by RobynGee** [comment]
Sorting on a flow field is not possible, if you want to sort on it, it must be a normal field.
This applies regardless of the field being defined in a table or an extension to a table.

**Comment by SahilGuptaBS** [comment]
@RobynGee 
but I used flow fileds in other tables too and it doesn't give any error see bellow

![image](https://user-images.githubusercontent.com/38460823/62023813-1c811600-b1f0-11e9-8051-5454921c867e.png)

![image](https://user-images.githubusercontent.com/38460823/62023847-3f132f00-b1f0-11e9-9038-8133c07b93ba.png)

![image](https://user-images.githubusercontent.com/38460823/62023861-54885900-b1f0-11e9-8ff7-b6939ddc4136.png)


![image](https://user-images.githubusercontent.com/38460823/62023881-67029280-b1f0-11e9-8070-85071e91e428.png)

**Comment by SahilGuptaBS** [comment]
and even i tried the same fields on another page  and its working fine means i am able to do sorting on those fields

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by bssi-danielf** [comment]
> Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked. Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

Hi @atoader, I work with the original contributor and we are again facing this issue in one of our AppSource extension. 

To summarize: when a `FlowField` is calculated and then used for sorting, there is no issue, so long as the table is NOT declared as `temporary`. 

But when we try the same code with the table declared `temporary`, we get the following error instead: 
![image](https://user-images.githubusercontent.com/56848245/155244294-9fb2c2a4-f648-42e7-8257-c365d4bf5eaa.png)

This runtime error _does not seem_ like an intention error to me, as it is not very descriptive, nor does it occur during compiling (where it could easily be determined to be in error). 

Here is a simple code example that demonstrates this issue:
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addlast("&Customer")
        {
            action(TestFlowFieldSorting)
            {
                ApplicationArea = All;
                Caption = 'Test Sort on Temp Record FlowField';

                trigger OnAction()
                var
                    // When the 'temporary' declaration is removed, there are no errors
                    tempCustomer: Record Customer temporary;
                begin
                    tempCustomer.CalcFields(TestComment);
                    tempCustomer.SetCurrentKey(TestComment, "No.");
                    tempCustomer.SetFilter(TestComment, '<>%1', '');
                    if tempCustomer.FindSet() then
                        repeat
                            Message('In ascending order, first comments are: "%1"', tempCustomer.TestComment);
                        until tempCustomer.Next() = 0;
                end;
            }
        }
    }
}

tableextension 50100 CustomerExt extends "Customer"
{
    fields
    {
        field(5800; TestComment; Text[80])
        {
            // A simple TEXT based flowfield
            // gets the first comment associated with each customer
            CalcFormula = LOOKUP("Comment Line".Comment WHERE(
                "Table Name" = CONST(Customer),
                "No." = FIELD("No."))
            );

            Caption = 'First Comment';
            Editable = false;
            FieldClass = FlowField;
        }
    }
}
```

Let me know if I am missing a simple property / declaration that would make the above code work. _(The `temporary` table declartion, the `SetCurrentKey`, and the ` FieldClass = FlowField` are hard to change in our solution)_ 

**Does Microsoft plan to support sorting on temporary table flow fields in the future?** 

If not, is there documentation that outlines this limitation? In my research so far, I've only ever seen speculation by NAV users / developers that this is a limitation, and nothing from an official source. It would also be nice if this limitation can be added to the AL compiler diagnostic messages?
