### ISSUE TITLE
Page based on Virtual Table "Date" crashes web client when entering text in search box

### ISSUE THREAD

**Issue by Zee980** [microsoft/AL#5152]
Page based on Virtual Table "Date" crashes web client when entering text in search box

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a sample page based on Virtual table "Date"
2. Run in web client. 
3. Input text in search box

**Expected behavior**
Web Client crashes

**Screenshots**

**Versions:**
 - AL Language: 2.1.106654

 - Business Central: 13.0.29718

**Comment by atoader** [comment]
@Zee980 can you post the page you used to crash the client?

**Comment by Zee980** [comment]
Hi Alexandru, please find

 attached 
[Page50000_VirtualTableTest.zip](https://github.com/microsoft/AL/files/3466072/Page50000_VirtualTableTest.zip)

**Comment by atoader** [comment]
Thanks @Zee980 ! We will investigate.

**Comment by thpeder** [comment]
Hi @Zee980 

Sorry for letting you wait and thanks for the repro steps, but let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
