### ISSUE TITLE
Problem generating virtual tables symbols

### ISSUE THREAD

**Issue by Sergisoft** [microsoft/AL#5153]
I'm trying to publish the ukmakingtaxdigital extension into a recently upgraded business central database. Initially, I got a long list of errors due to symbols not created. So, I created them using the generatesymbolreference command on finsql.exe.

After this, the list of errors is just about Company and Integer tables.

I thought this could be caused because this is an upgraded database and maybe I need to publish Test.app and System.app to database before trying again.

However this also raised a new error saying:

Your program license does not allow you to publish 'Access Control'.

![AA](https://user-images.githubusercontent.com/49785039/61551709-2a979f80-aa56-11e9-8e9c-3887b6ef6d43.png)

Please note this is done on a testing environment so my published license on the server is a partner BC development license.

I was wondering if both issues were related to some kind of permissions problem.

Thanks in advance for your help.

**Comment by jbakach** [comment]
Hi @Sergisoft, this is because the license you're using is not updated with latest BC objects.
Check if you have the latest assignment ones.

Best regards,

Jamal Bakach

**Comment by Sergisoft** [comment]
Hi @jbakach, We created a brand new license for both versions 13 and 14 and none of them worked. Is there anything special to pay attention when creating the license that we are missing?

Regards,
Sergi.

**Comment by jbakach** [comment]
Hi again @Sergisoft, have you downloaded the symbols from the project you are trying to install after the regenerate of symbols? That is needed to have both project and ServerInstance symbols equal.

**Comment by Sergisoft** [comment]
Good news! I managed to fix the issue.

The problem was that there were already some TEST objects on C/SIDE so when the extension for Test.app was published, this caused issues due to have objects twice on the background. I fixed it by searching those codeunits and deleting them from C/SIDE one by one.
