### ISSUE TITLE
The debugger options cannot be used for this server - Error while debug in Sandbox

### ISSUE THREAD

**Issue by nilesh4381** [microsoft/AL#5154]
Getting issue while debug in sandbox environment on on-cloud version  (Australia Localization - wisse)
We are able to bedug our US Client sandbox environment on-cloud, There is only issue with AU Client.

Getting following error
![image](https://user-images.githubusercontent.com/53175476/61639267-cc1e2b80-acb8-11e9-811b-a724a16ee72d.png)

**The debugger options cannot be used for this server**

Launch.json file setting
![image](https://user-images.githubusercontent.com/53175476/61639682-9a599480-acb9-11e9-843b-11dc113e47f6.png)

App.json file
![image](https://user-images.githubusercontent.com/53175476/61639338-ed7f1780-acb8-11e9-97f7-661f07ad7025.png)

Can you help me find issue with debugger, Client getting some error but we doesn't able to solve it.

**Comment by kalberes** [comment]
The AU version is probably running on a server that does not support the breakOnError. Is that also based on a 14.X sandbox?
You can try removing the breakOnError if you are targeting the AU ssandbox

**Comment by nilesh4381** [comment]
Hi Kalberes,

We have remove break on error setting from launch.json but again it give same error
![image](https://user-images.githubusercontent.com/53175476/61681950-438da280-ad2d-11e9-82a4-d754a033daf2.png)

@Micorosft Team - Can you give some feedback

**Comment by kalberes** [comment]
Can you maybe restart VsCode and try again. Config options maybe cached by VsCode, other people have also complained that not all changes are effective immediately

**Comment by nilesh4381** [comment]
Hi Kalberes,
I have restart VS Code after remove breakOnError option but again it is giving same error
We have tried to debug multiple customer instance on wisse (AU Locationlization) but every instance get same error while all us client instance debugging properly.

@MicorosoftTeam or @Wisse Team - Can you look into above issue.

**Comment by kalberes** [comment]
Looks like there is no workaround unless the AU server version is updated to the same as for your US servers.

**Comment by nilesh4381** [comment]
Hi Kalberes,

AU wisse client version is 
![image](https://user-images.githubusercontent.com/53175476/61883760-ab541100-af18-11e9-9a45-9a0813751768.png)

NA client version is
![image](https://user-images.githubusercontent.com/53175476/61883813-b9099680-af18-11e9-8669-3c0456490e40.png)

So here AU Client version higher than NA Client but still get the same error while debug in sandbox

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked. Is this issue still a problem for you? 

In the future, we recommend that you go through the standard customer support channel for issues related to our online sandboxes and production environments so that we can address them as quickly as possible.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
