### ISSUE TITLE
Hyperlink not working on action in rolecenter pages

### ISSUE THREAD

**Issue by MortenRa** [microsoft/AL#5155]
Adding action to rolecenter actions with a hyperlink do not work. nothing happens when pressing action. would expect that it opens the hyperlink.

Action with hyperlink on other pages works fine.

**To Reproduce**
Steps and to reproduce the behavior:
1. Code added below to test

``` AL Code to reproduce the issue ```
pageextension 50100 "Test Order Proc RC" extends "Business Manager Role Center" //9022
{
    actions
    {
        addafter("Excel Reports")
        {
            group("Use Dynamics")
            {
                action(QuestionURL001)
                {
                    ApplicationArea = All;
                    Caption = 'Basic Training';
                    Image = UserInterface;
                    trigger OnAction()
                    begin
                        Hyperlink('https://usedynamics.com/business-central/training/');
                    end;
                }
                action(QuestionURL002)
                {
                    ApplicationArea = All;
                    Caption = 'Upgrading Business Central';
                    Image = UserInterface;
                    trigger OnAction()
                    begin
                        HyperLink('https://usedynamics.com/business-central/upgrade/');
                    end;
                }
            }
        }
    }
}

**Expected behavior**
Expected that action open new window

**Screenshots**
![image](https://user-images.githubusercontent.com/28138717/61648644-223aa100-acb0-11e9-9c16-3943c8ca0f2d.png)

**Versions:**

 - AL Language: 
Name: AL Language
Id: microsoft.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.106655
Publisher: Microsoft

 - Business Central: Version: Platform 14.0.32600.33975 + Application 34093 (DK Dynamics NAV 14.1)

**Comment by qutreson** [comment]
Using triggers is not supported on pages of type Role Centers. We have validation for it on the page level, but we were missing it for page extensions on Role Centers. This has been fixed in our master and will be part of the next release.

**Comment by qutreson** [comment]
See #4713
