### ISSUE TITLE
Error: Invoice ID is not specified; when posting sales order in test function

### ISSUE THREAD

**Issue by krregg** [microsoft/AL#5157]
**Invoice ID is not specified.**

I am writing a test scenario for custom Business Central app. I have a simple case where I want to post a Sales Order. When I perform the posting step I get this error in BC:

``` 
The changes to the Sales Header record cannot be saved because some information on the page is not up-to-date. Close the page, reopen it and try again.
``` 

Code breaks in codeunit 80 (Sales-Post) inline 1317, on action DELETE, where Sales Header should be deleted. This kind of behavior is super strange. In case if I prepare Sales Order manually trough Web client and I try to post also manually, everything works as expected.

If I prepare Sales Order manually trough Web client and I do NOT perform any Post action and if I use this Sales Order in my test scenario only to execute Posting, everything works well also. What is super strange. So if I prepare Sales Order trough my code I get problems with posting, otherwise no.

Sales Order is prepared using functions in codeunit 130509 (Library - Sales), CreateSalesHeader and CreateSalesLine.

I was also comparing Sales Header record right before posting for both cases I mentioned above and honestly there is no difference except few DateTime fields.

In Event Viewer is also something. There is an error saying **Invoice ID is not specified**. Hm, what is that? Does anyone have any idea about that?

**ERROR:**
``` 
Server instance: BC140
Category: Sales Invoice Aggregator
ClientSessionId: ***************************
ClientActivityId: ***************************
ServerSessionUniqueId: ***************************
ServerActivityId ***************************
EventTime: 07/23/2019 06:52:20
Message Invoice ID is not specified.
ProcessId: 19512
Tag: 00006TK
ThreadId: 154
``` 

**WARNING:**
``` 
EventTime: 07/23/2019 06:52:21
Message (NavCSideException): RootException: NavCSideException
The changes to the Sales Header record cannot be saved because some information on the page is not up-to-date. Close the page, reopen it, and try again.

Identification fields and values:

Document Type='Order',No.='SO19-00832'
  AppObjectType: CodeUnit
  AppObjectId: 80
  AL CallStack: "Sales-Post"(CodeUnit 80).DeleteAfterPosting line 8
"Sales-Post"(CodeUnit 80).FinalizePosting line 55
"Sales-Post"(CodeUnit 80).OnRun(Trigger) line 92
"Library - Sales"(CodeUnit 130509).DoPostSalesDocument line 44
"Library - Sales"(CodeUnit 130509).PostSalesDocument line 1
``` 

**Steps To Reproduce**
1.) Install TestToolKit
2.) Create Sales Header using function CreateSalesHeader in codeunit 130509 (Library - Sales).
3.) Create two Sales Lines using function CreateSalesLine in codeunit 130509 (Library - Sales).
4.) Perform post-action using function PostSalesDocument in codeunit 130509 (Library - Sales).

Here is my code where I prepare Sales Order:
``` 
// Prepare Sales Header
lcLib.CreateSalesHeader(lrSalesHdr, lrSalesHdr."Document Type"::Order, lrIcPartner."Customer No.");
lrSalesHdr.Validate("Posting Date", CalcDate('CY-1Y+1D'));
lrSalesHdr.Validate("Location Code", 'ABOVE');
lrSalesHdr.Validate("External Document No.", 'PO99-00999');
lrSalesHdr.Validate("Posting No.", lcNoSeriesMgt.GetNextNo(lrSalesHdr."Posting No. Series", lrSalesHdr."Posting Date", true));
lrSalesHdr.Validate("Shipping No.", lcNoSeriesMgt.GetNextNo(lrSalesHdr."Shipping No. Series", lrSalesHdr."Posting Date", true));
lrSalesHdr.Modify(true);

// Prepare Sales Line
lcLib.CreateSalesLine(lrSalesLine, lrSalesHdr, lrSalesLine.Type::Item, '20001', 2);
lrSalesLine.Validate("Location Code", 'ABOVE');
lrSalesLine.Modify(true);

// Post Sales Order
lcIvnNo := lrLib.PostSalesDocument(lrSalesHeader, true, true);
 ```

**Versions:**
 - AL Language: 3.0.106655
 - Business Central: W1 14.0 14.0.29530.0

**Comment by krregg** [comment]
Update:
I tried to Post manually prepared Sales Order. I got the same error but this time code breaks on action MODIFY. It is strange, because before this case worked out without issues. The code breaks inline 257 in codeunit Sales-Post. 

Anyway strange is that I got the same error for DELETE or MODIFY action on a record.

In Event Viewer I got this error now:
```
Server instance: BC140
Category: Development

EventTime: 07/23/2019 08:31:01
Message Failed request -- Method:GET; Url:http://localhost:6049/BC140/dev/signalr/start?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"DebuggerHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl...........
```

**Comment by atoader** [comment]
Hi @krregg ! We appreciate that you took time to investigate this issue. Unfortunately, we are not able to provide you with much support on this forum as this appears to be an application issue.
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
