### ISSUE TITLE
Adding ActionContainer & ActionGroup in Page Extensions

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#516]
Hi,
Is it possible to add your own Action Container & Action Group in Page Extensions? Currently i see it allows to added action before or after existing actions.

**Comment by esbenk** [comment]
Yes. 
```

pageextension 50100 CustomerListExt extends "Customer List"
{
    actions {
        addlast(Creation) { // Area Name not used in orignal object
            group(MyOwnGroup) {
                action(MyOwnAction) {
                    trigger OnAction();
                    begin
                        Message('Hello from my own Action')
                    end;
                }
            }
        }
    }
}
```

**Comment by BrianThorChristensen** [comment]
Hi,
I tried this code, and it created a new group named "New Document" with new dropdown menu named "MyOwnGroup" inside. The group was placed to the left of the existing groups.
To move the group to the right I used addafter(TheLastGroup)
