### ISSUE TITLE
Text encoding UTF8 is not working in production environment

### ISSUE THREAD

**Issue by manjusree16** [microsoft/AL#5160]
Hi there,

I have a soap web service which exports purchase journal data. XMLport has text encoding set to UTF-8.
![Untitled](https://user-images.githubusercontent.com/22266498/61762460-ae9fad80-adef-11e9-9f91-6a752350d6d8.jpg)

But I am not getting the same result in production environment with the same .app file from sandbox.
![xmlProd](https://user-images.githubusercontent.com/22266498/61762566-03432880-adf0-11e9-90ea-d1a45028d03d.jpg)

Could someone help me with this?. Thanks in advance.

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
