### ISSUE TITLE
Report 12120 VAT Register - Print  - Customization problems

### ISSUE THREAD

**Issue by giann85** [microsoft/AL#5161]
**Describe the bug**

Hi, I had to change the standard 12120 report for a customer. I only added a text box in the report footer, which is displayed through a Boolean variable that is valued in the OnPreReport.

I exported the file with txt2al from onpremises and created an app with file.al and .rdl file.

At the launch of the report I get the following error:
![image](https://user-images.githubusercontent.com/43236847/61884869-3d4e2080-aefd-11e9-9957-a6d9f0e74733.png)

Nothing has changed from the standard except the new box in the footer.

i dont'understand what's the problem.

thanks for the tips

**Versions:**

 - AL Language: 3.0.152816

 - Business Central: 13.0.25924

**Comment by atoader** [comment]
@giann85 can you provide a diff between the TXT file before and after adding this text box?

**Comment by giann85** [comment]
Hi, i've solved :
i've changed the  column name  "Base" of dataitem "VAT Book Entry"   to  "BaseCust" 
as is:    column(Base; -Base)
to be:  column(BaseCust; -Base)

and all his reference in the  rdl  file.

I don't know why there is this problem ... maybe there is a duplication of variable names...

regards
