### ISSUE TITLE
Can't add all fields in DropDown Fieldgroups BC14 CU1 (BC14 RTM works)

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/AL#5162]
EDIT(something went wrong)
**Describe the bug**
You can't add all fields to fieldgroups DropDown.
You can test by adding "Search Description"to the Item Table DropDown

**To Reproduce**
tableextension 50100 TestItem extends Item //27
{
    fields
    {

    }
    fieldgroups
    {
        addlast(DropDown; "Vendor Item No.", "Search Description") { }
    }
}

**Expected behavior**
Search Description should be visible in DropDown

**Screenshots**
![image](https://user-images.githubusercontent.com/24684493/61939308-42f64580-af93-11e9-8903-13922f5d5e91.png)

**Versions:**
 - AL Language: 3.0.15816
 - Business Central:
![image](https://user-images.githubusercontent.com/24684493/61939363-602b1400-af93-11e9-9558-4249878045dc.png)
Strange thing is, this works in BC14 but not in BC14.1

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
