### ISSUE TITLE
Mailing word document with tags as attachment doesn't work in BC cloud

### ISSUE THREAD

**Issue by Chingyz** [microsoft/AL#5163]
When trying to e-mail a word document as an attachment with tags such as Customer_Name, the tags aren't replaced with the values (in BC cloud).

**Comment by Chingyz** [comment]
Has anyone been able to look into this?

Thank you in advance.

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atoader** [comment]
Alternatively, you can try to get help for your question by posting to one of the following forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
