### ISSUE TITLE
[Bug] Variable content is not shown if WITH statements are used

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5164]
**Describe the bug**
When debugging code that is part of a 'WITH Record' statement, the field values of the referenced record are not shown while hovering the field, although they are listed in the variables tab.

![image](https://user-images.githubusercontent.com/25268332/62049052-b657bb80-b20e-11e9-9686-c9359ba10b43.png)

**Versions:**

![image](https://user-images.githubusercontent.com/25268332/62049194-fe76de00-b20e-11e9-9a27-4d56d165eaf6.png)

**Comment by kalberes** [comment]
Unfortunately this is a lack from the Debug Adapter Protocol that we use to communicate with the Debugger Client in VsCode. 
I have requested an enhancement. Let's see how far we get with that.
https://github.com/microsoft/vscode-debugadapter-node/issues/137
