### ISSUE TITLE
Text in RDLC reports cuts off on the right 

### ISSUE THREAD

**Issue by fedonb** [microsoft/AL#5167]
In certain cases when I set the alignment of a cell in an RDLC report to the right, it cuts off a small portion of the last character. This is not happening in every cell that is printed, but only in a few rows of my printed document.

I have already set the CanGrow and CanShrink property of the cell in the Report Builder to False and tried to add a right padding, but still the cutting off occurs. So my only valid guess is that there is a rendering issue in Navision when I preview the document. Even when I try to print the document as a PDF the cases where the cutting off occurs are minimized but still not nullified.

![image](https://user-images.githubusercontent.com/9832350/62120922-422f1d80-b2cb-11e9-81bf-e1f983c2052c.png)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by Pavel-Titov** [comment]
Hi, do you know if that issue has been fixed for BC14?

**Comment by PG-Ayaney** [comment]
Bug is still there even for BC18.

Easiest fix is adding a space at the end of the text field. Or convert to text and add that & " ".

Other fixes are setting "Can grow" to true AND setting a Background color, for ex. white. But sometimes this makes boxes move.

Hope this gets fixed.

**Comment by Tuncion** [comment]
Bug is still there even in 2025

**Comment by RostyslavVoitovych** [comment]
I've changed Padding Left/Right to 0, and it works in my case.
Right-click on the Text Box → Text Box Properties → Alignment → In the Padding Options tab, set Left and Right to 0

![Image](https://github.com/user-attachments/assets/0fadd6b3-37d7-4886-967f-1dc337303608)

Hope this helps

**Comment by deerware** [comment]
Bug is still there in BC26, but setting the background color to "White" instead of "No color" seems to fix it.

![Image](https://github.com/user-attachments/assets/1bb72d95-9ce5-46a2-b000-e6a811e22a10)

![Image](https://github.com/user-attachments/assets/c1867a0b-61ce-4677-a4a4-dbe13c672376)
