### ISSUE TITLE
Publish Extension with only EXECUTE rights in license

### ISSUE THREAD

**Issue by jiwanovski87** [microsoft/AL#5170]
Hi everybody,

yesterday we were not able to publish an extension because of the error message:
Your program license does not allow you to publish 'ObjectName'.

This object is a codeunit and the object number is available for the license. 
Since this Message is a known as a license issue we started to investigate time on that issue.. 

The result:
- We are not working with standard cronus; Base app includes a partner module
- this partner module have several publishers which are used by the extension
- One subscriber of our extension uses a publisher of a codeunit which only have EXECUTE rights within the license
- if we use a license with also READ / WRITE / DELETE / EXECUTE rights in the tenant, we are able to publish the extension

So we are not able to publish the extension because the customer license only have EXECUTE rights on the codeunit which have a publisher event. 

I assume this is a bug. Because the customer don't need more rights than EXECUTE rights on this object. So the publishing process of an extension should also be okay even if there are only EXECUTE rights on an object which is used because of events..

I hope you can help and this is the correct channel to share this issue...

Thanks

**Comment by RobynGee** [comment]
You can install a runtime version of an app with execute only permissions.
See below link.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages

**Comment by atoader** [comment]
Thank you for helping out, @RobynGee ! In general, to publish an extension, the license used on the server must have INSERT or INSERTINDIRECT permissions for the objects that you are publishing.  @jiwanovski87 have you found a solution to your problem?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
