### ISSUE TITLE
Error Loading Configuration Packages from AL -> Root Element Missing

### ISSUE THREAD

**Issue by EasyStep2Lean** [microsoft/AL#5171]
We have two methods available in codeunit 8620 – Config. Package Import:

**ImportAndApplyRapidStartPackageStream**: receives a TempBlob record as input and loads and apply the package.
**ImportRapidStartPackageStream**: only loads the package passed as TempBlob argument. This function wants also a Config. Setup record (temporary) as input. To apply the package, you need to call the ApplyPackage method defined in Config. Setup table.

When calling this functions using the following AL code:

local procedure ImportConfigData()
    var
        UploadResult: Boolean;
        RapidStartFileName: text;
        TempBlob: Record TempBlob temporary;
        RapidStartInStream: InStream;
        ConfigPackageImport: Codeunit "Config. Package - Import";
        ConfigSetupTemp: Record "Config. Setup" temporary;
        errors: integer;
    begin
        // Get RapidStart File and move into stream
        TempBlob.Blob.CreateInStream(RapidStartInStream);
        UploadResult := UploadIntoStream('Config. Package Selection', '', '*.rapidstart', RapidStartFileName, RapidStartInStream);
        if UploadResult then begin
            // Single step: Load and apply package
            //ConfigPackageImport.ImportAndApplyRapidStartPackageStream(TempBlob);

            // Two steps
            ConfigPackageImport.ImportRapidStartPackageStream(TempBlob, ConfigSetupTemp);
            errors := ConfigSetupTemp.ApplyPackages();
         end;
    end;

it gives an error **Root Element Missing** due to a internal call to the procedure 

1. ReadPackageHeaderFromStream in Codeunit Config.Package Import
2.     XMLDOMManagement.LoadXMLDocumentFromInStream(InStream,PackageXML);
3.  XMLDocument.Load(Instream)

Causing the follwing error:
"A call to System.Xml.XmlDocument.Load has failed with the following message: Root element is missing."

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
