### ISSUE TITLE
Issue with Uploading Extension: IternalServerError

### ISSUE THREAD

**Issue by Auzeuze13** [microsoft/AL#5172]
In Business Central Sandbox (Cloud version) I am trying to upload my extension from the *.app file but upload fails with error message:

> Deployment failed. Errors: App ID : 5e4bed1c-a1f7-4b29-ae39-b7e5f08de3c3 Message : { Failure status code InternalServerError returned }

Details:
To upload .app file in BC Sandbox I go to: Setup & Extensions -> Upload Extension, Select .app file from the disk, click Deploy. Then go to Deployment Status: See result:
Operation Type: Upload
Status: Failed
Summary: 

> Deployment failed. Errors: App ID : 5e4bed1c-a1f7-4b29-ae39-b7e5f08de3c3 Message : { Failure status code InternalServerError returned } - Job Id : bffd5fdc-ecfd-4802-8d55-aed9ff9bd0b9

Versions:
AL Language: 3.0.126610
Business Central: Business Central 14.1.33107.0

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
