### ISSUE TITLE
Cannot convert Variant to List

### ISSUE THREAD

**Issue by konstantinlevchenko** [microsoft/AL#5173]
When I'm trying to assign Variant to List, I'm getting following error in VS Code:
Cannot implicitly convert type 'Variant' to 'List of [Text]'

Here is an example how to reproduce this error:
    local procedure ListToVariant()
    var
        SourceList: List of [Text];
        SourceVariant: Variant;
        TargetList: List of [Text];
    begin
        SourceVariant := SourceList;
        TargetList := SourceVariant; //Error: Cannot implicitly convert type 'Variant' to 'List of [Text]'
    end;

**Comment by atoader** [comment]
Hi @konstantinlevchenko ! We don't currently support converting a variant to a List. Can you better describe your scenario? Is there something else that, if added to the language, would help you better achieve your goal?

**Comment by bjarkihall** [comment]
@atoader we can store most types in an array, arrays can hold variants, we can assign most types to variants but we can't check some of them or convert them back to the original type.
The docs just state: "The AL variant data type can contain many AL data types." and when there are types missing it kinda sticks out.

The workaround is to use an alternative supported structure for storing the List, like IsJsonArray, and iterate through the keys into a new List when retrieving it, which isn't very performant (and just feels unnecessary).

**Comment by atoader** [comment]
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by bjarkihall** [comment]
@atoader it just looks more like something that was forgotten to add, instead of being a "new idea".
You can assign list to a variant (without any compiler errors) but later you can't get it back again, isn't that considered broken?

I would submit a PR if I could:
```C#
// inside NavVariant class:

public bool ALIsList
{
  get
  {
    return this.IsOfNavType(NavType.NavList);
  }
}

internal void ALAssignNavComplexValue(NavValue other)
{
    this.Clear();
    switch (other.NclType)
    {
        //...
        case NavNclType.NavList:
            this.ClearAndSetValue(other);
            break;
    //...
}

// and same for NavDictionary, etc.
```

This also relates to the next release:
https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave1/smb/dynamics365-business-central/returning-complex-types

If a procedure can accept any NavValue by accepting a Variant, it won't be able to return any NavValue by returning a Variant, right?

**Comment by vody** [comment]
@atoader, can you update a milestone for this one?

**Comment by NKarolak** [comment]
atoader left Microsoft already in 2021 or 2022.

**Comment by atoader** [comment]
@qutreson or @thpeder might be able to help :)

**Comment by vody** [comment]
@qutreson, any option to include Variant to Codeunit and Variant (with Codeunit) to Interface? Then [my Service Provider concept](https://github.com/vody/ServiceProvider-al) will work. :)

**Comment by BazookaMusic** [comment]
This will come with the next major release of the compiler, or one of the pre-release versions if someone wants to try it early.

**Comment by BazookaMusic** [comment]
> @qutreson, any option to include Variant to Codeunit and Variant (with Codeunit) to Interface? Then [my Service Provider concept](https://github.com/vody/ServiceProvider-al) will work. :)

Unfortunately, we are not looking into allowing this yet.
