### ISSUE TITLE
PerTenantExtensionCop throws wrong errors

### ISSUE THREAD

**Issue by MaxBelohoubek** [microsoft/AL#5175]
**Describe the bug**
When using the navcontainerhelper to compile an app, it throws following error message:

[error]Specified part does not exist in the package. |  
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.91\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37

At first I thought it was related to navcontainerhelper itself, but after further investigation I also had a look at the errors thrown by the code analyzers.
For every file there was an error complaining about ID's (PTE0001). Looking at the app.json the id range was correctly defined.

The app was still built even though the resulting .app file didn't have any content.
When disabling the PerTenantExtensionCop the app was built successfully.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an app
2. Specify own object id range 
3. Use id's from within that range for your files
4. Enable PerTenantExtensionCodeCop

**Expected behavior**
The PerTenantExtensionCodeCop shouldn't complain about wrong id's when the app.json and all files use the correct id range.

**Versions:**
 - AL Language: 3.0.150570

 - Business Central:
   - Client: 14.3.34444.34812-DE
   - Platform: 14.0.34724.0

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
