### ISSUE TITLE
Uninstall an app (in cloud) using powershell 

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/AL#5179]
HI,

I have a scenario where one of the app is crashing and I am not able to login to business central.
can i use powershell to uninstall the app from that tenent? will this work? please advice.

Uninstall-NAVApp -ServerInstance DynamicsNAV -Name 'Proseware SmartApp' -Version 2.3.4.500 -Tenant 'Tenant1'

https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/uninstall-navapp?view=dynamicsnav-ps-2018

**Comment by atoader** [comment]
Hi @Bssivivek ! Please open a customer support case and and we will uninstall it from the tenant. We need some additional information that our CSS representative will gather.

**Comment by Bssivivek** [comment]
@atoader thanks a lot!!
