### ISSUE TITLE
Error while accessing Function from subpage

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#518]
Getting error while accessing function from subpage. In this below statement getting error for "SalesLines" subpage.

ltSalesLine.SETRANGE("Line No.", CurrPage.**_SalesLines_**.PAGE.ibsGetSalesLineNo());

**Comment by StanislawStempin** [comment]
Could you provide more context in which this error happens and what error you are actually getting? In general it is possible to access page parts and call methods on them.

**Comment by sanjeevasawale** [comment]
Hi StanislawStempin,

Here is real life example in which <SalesLines> Page is part of Page 42 - Sales Order. In the below example, SalesLines gets underlined with RED COLOR.
![image](https://user-images.githubusercontent.com/30457269/29655669-001c0522-88dc-11e7-85a8-33c3fc8d7b09.png)
