### ISSUE TITLE
Error when trying RAD install

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#5181]
**Describe the bug**
Exception when installing in RAD Mode
**To Reproduce**
No way to reproduce it, it's intermitent.

[Error - 13:21:05] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'La parte especificada no existe en el paquete.'
Details:
System.InvalidOperationException: La parte especificada no existe en el paquete.
   en System.IO.Packaging.Package.GetPart(Uri partUri)
   en Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppPackageReader.ReadNavAppManifest() en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\NavAppPackageReader.cs:línea 64
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.RadLanguageServerCompiler.CreateNavAppPackageWriterAndStream(String outputFilePath, CompilerTextWriter consoleOutput) en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\RadLanguageServerCompiler.cs:línea 64
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 619
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.RadLanguageServerCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\RadLanguageServerCompiler.cs:línea 130
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 433
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 330
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:línea 56
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:línea 43
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() en F:\a\50\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:línea 64

**Versions:**
 - AL Language: 3.0.152816

 - Business Central: 14.0.29530

**Comment by atoader** [comment]
@jbakach can you try to publish this using the latest VSIX from https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ ? Does the issue still occur?
