### ISSUE TITLE
Subscriber with array parameter doesn't add array

### ISSUE THREAD

**Issue by SirBETE** [microsoft/AL#5182]
**Describe the bug**
When adding parameters to a subscriber where one of it is an array, the array variables aren't added correctly.

**To Reproduce**
Steps and to reproduce the behavior:
1. create a subscriber on Database::"Item Journal Line", 'OnAfterCreateDimTableIDs'
2. add the parameters to the subscriber
3. Select TableID
4. Only the var, name and : are added, no array, array length nor type

``` AL Code to reproduce the issue ```
```
    local procedure Table_83_ItemJournalLine_OnAfterCreateDimTableIDs(
var ItemJournalLine: Record "Item Journal Line"; CallingFieldNo: Integer; var TableID: )
//var TableID: ARRAY[10] OF Integer; VAR No: ARRAY[10] OF Code[20]);
    begin

    end;
```

**Expected behavior**
The full parameter definition gets added
`LOCAL [IntegrationEvent] OnAfterCreateDimTableIDs(VAR ItemJournalLine : Record "Item Journal Line";CallingFieldNo : Integer;VAR TableID : ARRAY [10] OF Integer;VAR No : ARRAY [10] OF Code[20])`

**Screenshots**

**Versions:**

 - AL Language: 3.0.152816

 - Business Central:
Version: Platform 14.0.29530.32339 + Application 32452 (BE Dynamics NAV 14.0)

**Comment by EmilDamsbo** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by SirBETE** [comment]
> I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

Wow, this an old one ...
Didn't even remember it was still open.
Looks like it's fixed :D
