### ISSUE TITLE
[META] Wrong method to get BC version info

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#5183]
When reporting a bug here, there's in the comment of **Versions:**:
 -- In the client search for: System Information --
 - Business Central:

But searching for that, gives no results...
The BC info is moved to the '?' , Help and Support -> troubleshooting tab.

![image](https://user-images.githubusercontent.com/34303738/62707227-52dd4300-b9f1-11e9-81e7-ac5c7e4dd1b1.png)

**Comment by atoader** [comment]
Thanks @SirBETE ! We will update the templates.
