### ISSUE TITLE
Error creating a namespace without prefix

### ISSUE THREAD

**Issue by ftornero9** [microsoft/AL#5184]
I am trying to create a namespace without a prefix and I get the next runtime error:

![image](https://user-images.githubusercontent.com/12720964/62807276-46daa980-baf5-11e9-85b6-332a96aef1d1.png)

The third line is the one that trigger the error:

        xmlElem[1].Add(XmlAttribute.CreateNamespaceDeclaration('xsi', 'http://www.w3.org/2001/XMLSchema-instance'));
        xmlElem[1].Add(XmlAttribute.CreateNamespaceDeclaration('xsd', 'http://www.w3.org/2001/XMLSchema'));
        xmlElem[1].Add(XmlAttribute.CreateNamespaceDeclaration('', 'http://www.facturae.es/Facturae/2009/v3.2/Facturae'));  
In the documentation looks like is possible:

![image](https://user-images.githubusercontent.com/12720964/62807293-51953e80-baf5-11e9-94be-e0629c5a2e2f.png)

Regards

**Comment by ftornero9** [comment]
I am using this compiler version:

![image](https://user-images.githubusercontent.com/12720964/62807754-7b029a00-baf6-11e9-8a3e-c9c72ec6793d.png)


And this platform version:

![image](https://user-images.githubusercontent.com/12720964/62807826-b309dd00-baf6-11e9-8ab2-28a69926a1d8.png)

Regards

**Comment by PP1986** [comment]
Hi @atoader,
Im having this same issue still, in BC17.

**Comment by atoader** [comment]
The issue is in our backlog, but we cannot provide an ETA. I will work on clearer guidance on how to escalate issues.
