### ISSUE TITLE
The extension is not synchronized.

### ISSUE THREAD

**Issue by SShadowS** [microsoft/AL#5186]
![image](https://user-images.githubusercontent.com/3491765/62861944-40228100-bd05-11e9-89f8-761ce4554590.png)

Trying to Sync an App.
Without mode Clean = Expected error (Removing table)
 - Eventlog show the expected error.

With mode Clean = WARNING: The extension '*removed*' is not synchronized.
 - No new entries in eventlog, so can't debug.

ApplicationVersion
13.0.25924.0

ApplicationFamily
DK

**Comment by atoader** [comment]
@SShadowS we will investigate if we can reproduce this on the latest release.

**Comment by RobynGee** [comment]
I have this warning on trying to sync in clean mode a user created design extension on business central 13 CU3.
Is there any update as to what could cause it?

**Comment by atoader** [comment]
@RobynGee @SShadowS can you provide a sample to reproduce this issue on the latest release?

@RobynGee  for releases older than Wave 2 2019, you should contact support through the standard channel. As described in our FAQs https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions , we can only help with the latest release of our extension.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
