### ISSUE TITLE
Issue in Report Vendor 1099 Magnetic Media

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#5188]
Hi Team,
I converted the "Vendor 1099 Magnetic Media" report from "C/al" to "AL" language through Txt2al.exe file 

then i include that AL file into our project.  as I include it is giving error for a variable of type "File" 

![image](https://user-images.githubusercontent.com/38460823/62993154-e4c2d100-be73-11e9-99b5-50243e948289.png)

and if you look into variable

![image](https://user-images.githubusercontent.com/38460823/62993190-015f0900-be74-11e9-8c67-7370a9883af4.png)

and i hover the cursor to that function to see the error then it showing the following error

![image](https://user-images.githubusercontent.com/38460823/62993245-33706b00-be74-11e9-9e1c-ad59f6dc6556.png)

can anyone here to guide something on this issue

**Comment by atoader** [comment]
@SahilGuptaBS the question has been answered a few times on this forum. If you would like learn more, please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
