### ISSUE TITLE
While calling API getting error msg #397

### ISSUE THREAD

**Issue by jyotivarade** [microsoft/AL#5189]
![image](https://user-images.githubusercontent.com/50901499/63006115-7abe2200-be9b-11e9-88be-cdbbc267acc6.png)

begin
ReadLicencesdetails();
RequestMessage.SetRequestUri(url);
RequestMessage.Method := 'POST';
BodyParameter := ('{' +
'"headerParam": {' +
'"user_Key": "' + User_Key + '",' +
'"license_key":"' + license_key + '"' +
' },' +
'"state": "' + State + '",' +
'"methodName": "GetAllInventoryTransfer",' +
'"methodType": "GET"' +
    ' }');
    HttpContent.WriteFrom(BodyParameter);
    RequestMessage.Content(HttpContent);
    HttpClient.Send(RequestMessage, ResponseMessage);
    HttpContent := ResponseMessage.Content;
    HttpContent.ReadAs(ResponseInReadibleFormat);
    if ResponseInReadibleFormat = '{"Response":"Success"}' then begin
    end;

**Comment by atoader** [comment]
@jyotivarade Send will throw an error if you do not handle the return value as described in the documentation: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-send-method 
I am guessing you are trying to post a JSON request, but you have not set the content type. 

Please use one of the following resources to get more help:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This repository focuses on handling bugs and suggestions for the latest developer preview. Please read our https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions to find the proper place for your queries.
