### ISSUE TITLE
How can I access the Record "Object" by extension

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#519]
How to access the record object from extension?
![grafik](https://user-images.githubusercontent.com/15800069/29453955-c49eff9c-840b-11e7-9e8b-44a8acf54b6c.png)
![grafik](https://user-images.githubusercontent.com/15800069/29454452-8ee2c7c4-840d-11e7-8872-8d6f113dfc18.png)

I want to get the following information:
![grafik](https://user-images.githubusercontent.com/15800069/29454147-651d2084-840c-11e7-8b77-e266f740c393.png)

Or are there events e.g. "OnBeforeObjectModifiedEvent" / "OnAfterObjectModifiedEvent" / ...?

**Comment by esbenk** [comment]
The Object table is not available for extension development and will be obsolete when we replace all development with VsCode.

What is your scenario?

**Comment by megel** [comment]
Yes this is ok when the change is done. But until you replace all development by VSCode the information of the object table is important. In my case I need the change information of the objects e.g. Date, Time and Version List. For identification is still the ID important.

I believe the full (OnPrem) development won't change until 2019 or 2020. So the deprecated information from Object are relevant in the comming Versions. I think the access of these objects should / could be limited to readonly.

**Comment by esbenk** [comment]
For SaaS there will be no online changes of objects. The object table never changes on a running production system.

The Date,Time, and Version fields have little value on SaaS. The entire baseapp is now considered a single module with a version. 

For On-Prem development you will still have access to the Object table.

**Comment by megel** [comment]
I fully agree about the SaaS scenario. My current target is to combine both worlds for the
OnPrem development.

The solution in my case is, I have to wrap these objects inside the old world (FinSQL) and provide external access to the new world (VSCode) of the wrapper objects. Right?

**Comment by esbenk** [comment]
For On-Prem deployment/development you will be able to access all tables. The restriction is for SaaS. 

For development the restriction is controlled by the target attribute in the app.json. For deployment it is controlled on the server-side. E.g. even though if you change it in the app.json you won't be able to deploy to SaaS.

**Comment by megel** [comment]
Oh didn't know. Do you have an example app.json for this case?

**Comment by megel** [comment]
@esbenk: Thx, I found the right attribute:

![grafik](https://user-images.githubusercontent.com/15800069/29506180-a11a876c-864a-11e7-975a-f7e5987f2d3d.png)
