### ISSUE TITLE
BC13 CU2 transtlations not working

### ISSUE THREAD

**Issue by kadrikekk** [microsoft/AL#5194]
AL Language Version: 3.0.152816

I have the same app with translations for et-EE (Estonian) language.
One is for W1 13.2 (26556) and the other one is for W1 13.5 (29483).
For the first one many translations for labels are not working, for the second one everytihng is translated correctly.

translation sample is here. 
This label unit is translated in both. 
<trans-unit id="Page 2853395046 - NamedType 1469225628" size-unit="char" translate="yes" xml:space="preserve">
          <source>Payroll Info Types</source>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">Page PLK Menu Suite - NamedType PayrollInfoTypes</note>
        <target state="translated">Palga info liigid</target></trans-unit>
       
this one is translated only for the W1 13.5 (29483).
 <trans-unit id="Page 2853395046 - NamedType 3673655514" size-unit="char" translate="yes" xml:space="preserve">
          <source>Employee Documents</source>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">Page PLK Menu Suite - NamedType Employee Documents</note>
        <target state="translated">Töötajate dokumendid</target></trans-unit>

Is this a bug that has been fixed for CU5? or does it have some other reason?

BR, Kadri

**Comment by atoader** [comment]
@kadrikekk can you provide more information? I am afraid I am missing a bit of context. Are you translating the standard application to estonian? I would guess that this has been fixed in CU5 so you should use that one.

**Comment by kadrikekk** [comment]
@atoader I'm translating extension with more then 7000 tokens to estonian. It seems that for CU2 at some point new Labels were not translated any more. Caption translations are fine but every new Label is missing translation.  I'll take it as bug of CU2 then and come back to this issue if it should occour on later versions also.
