### ISSUE TITLE
Pages are not visible in Tell Me

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5197]
Pages build on virtual tables (AllObjWithCaption...) are not visible in Tell Me, even if I added UsageCategory and ApplicationArea property.

Is there any way to see these pages in Tell Me?

**Comment by atoader** [comment]
We've recently encountered this bug internally. We are still investigating.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
