### ISSUE TITLE
Can't display correctly Decimal Places of local variables in page extension

### ISSUE THREAD

**Issue by bachtruong** [microsoft/AL#5198]
Dear Team, 

I am making a customization to Blanket Purchase Order Subform Page.
In VS Code, I added 3 local variables to the extension of this page, and set AutoFormatExpression as below.

![BC code](https://user-images.githubusercontent.com/53859300/63148428-1dada200-c03c-11e9-8e2b-f860c70aee89.JPG)

then the result is like this

![BC screen](https://user-images.githubusercontent.com/53859300/63148450-2ef6ae80-c03c-11e9-986f-f8eaa8a5ae99.JPG)

You can see that 2 variables "Total Amount to Receive" and "Total Remaining Amount" are displayed with decimal places 0:0.
It seems that AutoFormatExpression of these 2 variables did not get the right value. 
Expected value is EUR but in fact, it was blank so decimal places of local currency JPY (decimal places 0:0) was used to display these 2 variables.

I tried the same thing in NAV2018 CU13,  it worked correctly.

Setup: 
![NAV setup](https://user-images.githubusercontent.com/53859300/63148706-fe634480-c03c-11e9-9569-027dca674074.jpg)

Result:
![NAV screen](https://user-images.githubusercontent.com/53859300/63148720-09b67000-c03d-11e9-9d85-b8333bc6b648.jpg)

Do you think that I missed something
or do you have any idea why my source code in page extension did not work?

Please kindly tell me if you have any idea. I really appreciate your help.

Thanks & Best Regards

**Comment by atoader** [comment]
@bachtruong can you try this code on the latest preview https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/ ? Does it still repro?

**Comment by bachtruong** [comment]
@atoader Thanks for your reply. I will try on 2019 release wave 2, but it is going to take time a litle bit because actually I don't have experience with Docker ^^. I will tell you the result after that. Thanks.
