### ISSUE TITLE
FilterPageBuilder on Desktop and Web client

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5199]
Why **FilterPageBuilder.RunModal()** is not the same on Desktop and Web client?

![1](https://user-images.githubusercontent.com/31925856/63160843-0dd39500-c01f-11e9-95fb-7dd0eeb5e451.png)

![2](https://user-images.githubusercontent.com/31925856/63160853-12984900-c01f-11e9-866b-53a744c54cea.png)

**Comment by atoader** [comment]
@tomasevicstefan what versions are you using? Have you tried it out on the latest developer preview?

**Comment by tomasevicstefan** [comment]
We are currently on CU06 container and azure sandbox, Icelandic localization ("mcr.microsoft.com/businesscentral/onprem:13.6.29777.0-is").

It was the same on previous cu. I will try on some newest image.

**Comment by qutreson** [comment]
Hi @tomasevicstefan did you give it a try on our latest developer preview (version 15.x) ?

**Comment by tomasevicstefan** [comment]
No, unfortunately I can't build environment on version 15, because I'm not registered on microsoft collaborate. So I didn't try if this problem still exist.

**Comment by thpeder** [comment]
Hi @tomasevicstefan, 
I just tried with the following code and it seems to work on the latest version.
Please register on collaborate and give your code a try on the latest version.
```AL
action(LaunchModal)
{
    trigger OnAction()
    var
        builder: FilterPageBuilder;
        myRec: Record MyTable;
    begin
        builder.AddRecord('MyTable', myRec);
        builder.RunModal();
    end;
}
```
![image](https://user-images.githubusercontent.com/24276180/66642527-3772fc00-ec1d-11e9-8185-b571f5f9e0cf.png)

**Comment by atoader** [comment]
@tomasevicstefan the wave 2 2019 release is now available via public docker images. Please let us know if you can reproduce it on an image from that release.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
