### ISSUE TITLE
Error while creating flowfield in table extension using Visual studio code

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#52]
Hi all,
I have created a new tableextension object using Visual studio code which extends Item table. 
I have created a field which is a flow field.
I have coded the following:
field(70000000;"Control Sample Qty";Decimal)
{
Editable=False;
FieldClass=FlowField;
DecimalPlaces=0:5;
CalcFormula=Sum(ControlStabilitySample."Sample Qty" WHERE ("Item No."=FIELD("No."),Status=FILTER(<>"QC Completed"),"Sample Type"=CONST("Control Sample"),"Loan License No."=FILTER(=''))); 
}
where, 'ControlStabilitySample' is a new table I have created in Visual studio code.
But the CalcFormula statement give me following error:
error AL0999: Internal error: 'Object reference not set to an instance of an object.', Stack trace=unknown

The statement which is creating error in CalcFormula is:
 "Item No."=FIELD("No.").
Kindly suggest how to solve this.

**Comment by esbenk** [comment]
Hi,

Unfortunately this is a bug in the preview. The good news is that it is already fixed and will be available in the next update.

**Comment by TinaMenezes** [comment]
Hi @esbenk,
Great. Thank you!
