### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#520]
The function Goto Definition does not work with me at all. There is always a similar error:

`Payment Terms.al can not be opened: resource is not available`

Do I still have to do something that works?

**Comment by thpeder** [comment]
I'm not able to reproduce this. 

Can you provide a simple piece of code that reproduces this.
What application locale are you using?
Are you running on the latest update?

**Comment by FSharpCSharp** [comment]
Yes I use the latest version. OK I have found the error I found. The problem is that with my project, which I had created in the July version still the old symbols were present. Also a call of the function to re-download the symbols has done nothing here because apparently it was not recognized that there is a new version of the symbols.

I have now done the following. The old symbol files I have completely deleted, and then the symbols re-downloaded. Then went the function "Go to Defininition".
