### ISSUE TITLE
Missing functions for XML handling in AL

### ISSUE THREAD

**Issue by LFlamme** [microsoft/AL#5203]
HI,

so i tried to get our "old" extension using dotnet to use the al-BuildIn XML Tools.

This worked quiet good, until i came to use the XMLNode.

Right there i miss some functionality.

I need to be able to check if the XMLNode hast ChildNotes and to get them(previous functions "HasChildNodes" and "ChildNotes")

on the other hand i need to be able to get name and value of the current XMLNode.
(previous functions "Name" and "Value".

Please add these functions to XMLNode in AL

**Comment by thpeder** [comment]
Hi @LFlamme, 

If you are having a XmlNode you don't know for sure that it is a XmlElement, but you can check with IsXmlElement as you said as well. In cases where you still want to get the name or value then you need to check for the other types and cast it to the correct one.
If you would like to have that on the XMLNode, then header over to [Ideas](https://aka.ms/BusinessCentralideas) and either upvote an existing entry or create a new one if you can't find any that matches that.
