### ISSUE TITLE
AL compiler (alc.exe) compiling app when it shouldn't

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/AL#5205]
With the latest image bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019 VS Code now respects the ruleset file as expected. Example .json file:
{
    "name": "Test"
    , "generalAction": "Error"
}

Which changes all warnings to errors and prevents app from compiling (using AL 4.0.161867)
Command used:
$ExtensionBinFolder = "C:\Users\user\.vscode-insiders\extensions\microsoft.al-4.0.161867\bin"
$ProjectFolder = "C:\Users\user\Documents\AL\ALProject26"
cd $ProjectFolder
. "$ExtensionBinFolder\alc.exe" /project:$ProjectFolder /packagecachepath:$ProjectFolder/.alpackages /warnaserror /ruleset:.\.vscode\Test.ruleset.json /errorlog:log.log /loglevel:Verbose

However alc.exe doesn't work (or I'm doing something wrong):
1. switch /warnaserror should automatically convert all warnings to errors so we don't have to use ruleset (to my understanding) - this does nothing.
2. Specifying ruleset as in the command above does nothing (app file is being created)
3. /errorlog is empty unless there is an actual error (i.e. missing semicolon). Example of log.log:
{
  "version": "0.1",
  "toolInfo": {
    "toolName": "Microsoft (R) AL Compiler",
    "productVersion": "4.0.2",
    "fileVersion": "4.0.2"
  },
  "issues": [
  ]
}

**Comment by AntoineTal** [comment]
Hello, any news on this issue? 

Got the same thing with this command : 

`        & "$env:CURRENT_TASK_ROOTDIR\alc\alc.exe" /project:$ProjectFolder /packagecachepath:$SymbolsFolder /analyzer:$pathAnaly /ruleset:$pathJson /out:$PackageOutputFile | Convert-ALCOutputToADO -FailOnWarning $FailOnWarning
`

Package is created, just like if in VSCode "al.enableCodeAnalysis" is false.

**Comment by kalberes** [comment]
@AndriusAndrulevicius Is this issue still happening for you with the latest vsix version? If yes please open a new issue.
