### ISSUE TITLE
AL Code Analyzer no overflow warning from record to record

### ISSUE THREAD

**Issue by SarahBirrer** [microsoft/AL#5206]
I have the following issue, that the Code Analyzer does not mark the critical Code which could triggers an text overflow.

When I save the Item Description (Text[100]) into a Custom Table Field (Text[50]) no warning or error Shows up. It would be very helpful if this could be marked, so we can easily react when a Standard field is changed.

Thanks, Sarah

**Comment by atoader** [comment]
Hi! What code analyzers have you enabled? Do you have any specific rule set enabled?

**Comment by SarahBirrer** [comment]
![image](https://user-images.githubusercontent.com/48559946/63675677-a02b2400-c7e9-11e9-9e93-8032b5d324ba.png)
Thats our ruleset.. The Bug is only in Record variables..

**Comment by SarahBirrer** [comment]
![image](https://user-images.githubusercontent.com/48559946/63675752-d072c280-c7e9-11e9-9879-8741095758a3.png)
This is out ruleset. Ad described above, the bug is only in record variables....

**Comment by atoader** [comment]
Thanks Sarah! I will forward this issue to the team handling the code analysis rules.
