### ISSUE TITLE
Reason: Sequence contains more than one element

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5210]
**Describe the bug**
Reason: Sequence contains more than one element

**To Reproduce**
Steps and to reproduce the behavior:
1. Just created an upper version of an Ext A (1.0.0.1 >> 1.0.0.2), which have dependency of some other extensions.
2. When tried to publish it on Cloud Sandbox, got (Reason: Sequence contains more than one element) error.
3. So tried it to publish on Local on-Prem business central solution, then getting below error.
**error** AL1024: A package with publisher 'XXX', name 'XXX for Margin', and a version compatible with 
'1.0.0.4' could not be loaded.

``` AL Code to reproduce the issue ```
NA
**Expected behavior**
It should be publish on On-Prem at-least with Puiblish cmd, but in process of this command error is coming.

Even i have the dependent extension version 1.0.0.4 installed on my local on-prem solution.

**Screenshots**
Dependency extension
![image](https://user-images.githubusercontent.com/33481576/63339604-e2c0ac80-c362-11e9-8027-bfe364376382.png)

Defined dependency in Ext A
![image](https://user-images.githubusercontent.com/33481576/63339725-274c4800-c363-11e9-81c8-9f6a7271ccdc.png)

Getting error in VS Code while publishing on Cloud Sandbox
![image](https://user-images.githubusercontent.com/33481576/63339760-3af7ae80-c363-11e9-97ae-ee4fa26fbcbc.png)

Getting error while publishing on Local On-Prem solution
![image](https://user-images.githubusercontent.com/33481576/63339824-5cf13100-c363-11e9-8ad5-faf4a84a171e.png)

**Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/33481576/63339912-89a54880-c363-11e9-9f75-4edcb66ad449.png)

 - Business Central:
![image](https://user-images.githubusercontent.com/33481576/63340035-cb35f380-c363-11e9-9b72-7d947790e7e5.png)

Thanks

**Comment by atoader** [comment]
Hi @SUD-D365 can you reproduce this on the latest preview? https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

**Comment by SUD-D365** [comment]
Thanks for your response.
It has been resolved by other way.
Since it was urgent that time.
Closing
