### ISSUE TITLE
about production environment 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#5211]
Hi All

can anyone tell me, how can i install my app to production environment 
( https://businesscentral.dynamics.com/ ) ?
i have installed my app to my sandbox environment but i need to install production environment also.   

i have following launch.json 

![image](https://user-images.githubusercontent.com/38460823/63427239-5087d980-c432-11e9-89a5-9e2d272e1362.png)

and when i am going to compile this, then it is installing app in our sandbox environment not in production environment. 

please suggest

**Comment by ChrisBlankDe** [comment]
You should develop against an sandbox and upload to generated app file in the extension management page of your production environment.

**Comment by SahilGuptaBS** [comment]
@ChrisBlankDe  Thank !!!

i done with the same steps  then under the deployment status page, it is getting failed 

and its showing, some messages like 

table : ****** must have id between 5000 to  9999

**Comment by SUD-D365** [comment]
You cant publish your app directly in production environment.
You have to upload the .app file in production via **Upload Extension** button from Extension management page.

If possible than please share app.json

**Comment by atoader** [comment]
@SahilGuptaBS you developer your per-tenant-extension in a sandbox as Chris said and then deploy it to production using the extension management page. You can read more about this here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization
https://community.dynamics.com/nav/b/katsonsnavblog/posts/top-tips-and-tricks-on-how-to-create-per-tenant-extensions

It seems you are using IDs that are outside the range of IDs allowed for per-tenant-extensions.

**Comment by SahilGuptaBS** [comment]
@SUD-D365  i am doing the same steps but giving the same errors

**Comment by atoader** [comment]
@SahilGuptaBS what errors are you getting? Could you post the full list?

**Comment by SUD-D365** [comment]
> @SUD-D365 i am doing the same steps but giving the same errors

It would be better if you could share the **app.json** file here for understanding the issue.
Thanks

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
