### ISSUE TITLE
Your program license does not allow you to publish

### ISSUE THREAD

**Issue by Phfo** [microsoft/AL#5213]
We want to make an app for appsource and first trying to publish the app in an docker container for testing; we're using our developing license.
"platform": "14.0.34251.0"
"application": "14.3.34444.0"
F5 -> **Your program license does not allow you to publish**
object no : codeunit 70320075 xyz

**Comment by Bssivivek** [comment]
The only reason i can think off is, your docker container doesn't have the correct license.
you can validate it by creating the container with -includeCside flag. Once the container is created you can open the C/SIDE and see if you have created container with right license.
you can also upload the correct license file, restart the container and then try publishing the app using power shell.
Hope this helps!!

**Comment by Phfo** [comment]
Have checked this and is correct license (our dev license). However when we create a new license, we have only following option for the product line : Microsoft Dynamics 365 Business Central on premises. Is this right ?

**Comment by SUD-D365** [comment]
I guess, you should first get a license for your unique object ID's like **70320075**.
You would not allowed to publish any object ID outside 50k..99999 range with your developer license.

**Comment by atoader** [comment]
Thank you for answering @SUD-D365 ! @Phfo you will need a license that contains rights to publish this object. In other words, your license will need to contain Insert permissions for Codeunit 70320075.

You can get more help by using one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
