### ISSUE TITLE
Alignment issue in standard report

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/AL#5215]
Hi - We have our apps publish in app store. wrt report, we do substitute the standards report.
We are running Vendor 1099 report (for example) where we setup Federal ID No. in vendor card

![pic1](https://user-images.githubusercontent.com/38437776/63467641-c97b3700-c41a-11e9-9205-09f4f74b2c4d.jpg)

Now when we print the report we see that the federal ID No. is not displayed correctly. It only prints first 4 characters. Please find the screen shot below

![pic2](https://user-images.githubusercontent.com/38437776/63467712-eca5e680-c41a-11e9-8c3d-dc67774f60bf.jpg)

Now, when we print the standard D365 BC report (not our substituted report), we are still getting the same issue.

Do, we have to fix it on our substituted report? please confirm. We can replicate this scenario in latest docker image.
Please help!!

**Comment by dNsl9r** [comment]
Seems to be report layout - so it should be posted here: https://github.com/Microsoft/ALAppExtensions/issues

**Comment by Bssivivek** [comment]
ok thanks!!
