### ISSUE TITLE
Web client crashes when user moves to new line on a sales order and reservation message pops up

### ISSUE THREAD

**Issue by Cosimo2001** [microsoft/AL#5216]
**Describe the bug**
On Sales Order lines, if the user enters a quantity and moves to a new line, the web client crashes if the item is out of stock and the reservation message pops up.

**To Reproduce**
1. Create a Sales Order
2. Enter an out-of-stock Item
3. Enter the quantity and press down arrow (or page down, or use mouse to click on new line) - the pointer will be positioned on a new line
4. The reservation confirmation message pops up
5. Regardless of the user choice (yes/no), the web client crashes

**Expected behavior**
Pointer should not move to next line until all checks have been performed on sale line

**Versions:**
GB 14.3.34444.0

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
