### ISSUE TITLE
On-Premise development

### ISSUE THREAD

**Issue by doctorpartlow** [Microsoft/AL#522]
I've been looking around for quite a bit and can't seem to find the configuration to connect vs code to an on-premise nav instance. is this possible yet? also is 7049 a new default port that vscode is referring to? is it possible to development in vscode now for 2017 and create an extension? if so are there any set up guides?

**Comment by StanislawStempin** [comment]
On-Premise development is only available in the NAV Developer Preview builds and will be available in the next version of NAV. It's not available in NAV 2017.
The NST configuration keys that control this are:
```
<!-- 
    The listening TCP port for the Microsoft Dynamics NAV Development Services Endpoint.
    Valid range: 1-65535
  -->
<add key="DeveloperServicesPort" value="7049" />
  <!--
    Configures the server to support development services.</value>
  -->
  <add key="DeveloperServicesEnabled" value="true" />
  <!--
    Turns on or off the https for development services.
  -->
  <add key="DeveloperServicesSSLEnabled" value="false" />
```

**Comment by dkatson** [comment]
Hi Stanislaw, the same question from me. I've created VM from august update template. And I want to use NAV instance to work with W1 version. It changed "authentication": "UserPassword" and I found that user ADMIN exist in this database. But I don't know password. So how can I log to NAV instance on august update VM?

**Comment by StanislawStempin** [comment]
If I recall correctly it is the same password as you enter when deploying the Dev Preview template.

**Comment by dkatson** [comment]
No

**Comment by StanislawStempin** [comment]
@freddydk - can you comment on this one?

**Comment by StanislawStempin** [comment]
Username to log into NAV is 'admin'. Can you try that one?  (password the same as you used for Azure template)
