### ISSUE TITLE
Misc. compiler errors when changing GIT Branch.

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/AL#5224]
**Describe the bug**

The "Old" references still lingers.
"Download symbols" action does not fix it unfortunately.

To remedy you can:
- Close VS Code
- Delete .alpackages folder
- "Download symbols"

I would suggest a clean command is made available and possible that runs by itself when large file changes are detected.

**To Reproduce**
Change you branch making all your source code change.

``` AL Code to reproduce the issue ```

**Expected behavior**
No compiler errors

**Screenshots**

**Versions:**

3.0.152816

14.0.32600.34788 + Application 34813 (W1 14.1)

**Comment by RafaelKoch** [comment]
On this one I had a lengthy support call on 14.x and no true fix delivered a while ago.

You can add to the triggers for this unpleasant behaviour:

- Change to a different file of a different extension in the same VS Code Workspace -> still shows all sorts of analyzer results related to the last thing You worked on and will therefore not work properly for the thing You are working on now.

There should be at least a way to manually reset the analysis.

Our developers all are reloading VS Code multiple times a day just for this very reason. Some have put the reload on a shortcut even. All well and good, the true impact ist not the 20sec that takes to reload but more the things that get overlooked if the reload is forgotten...  

As it stands changing a branch or changing Extension will always result in a disfunctional code analysis and retaining the analysis cache can never be of any use.
