### ISSUE TITLE
Extensions Missing in Sandbox

### ISSUE THREAD

**Issue by Rathnakmr** [microsoft/AL#5226]
Hi Team,

All of my custom published extensions are missing in sandbox. This problem is occurring second time now. previously there were only two extensions. so I uploaded again, but now I have 14 to 17 customized extensions to be uploaded again, in those most of them are dependency related extensions. it is getting difficult to upload again.

I don't know for what reason all the extensions are vanished in a single day. My sandbox version and production version are same only.

Kindly provide a solution to stop this problem in future.

Note: All the extension which was uploaded already in production is available. The problem is only in sandbox.

Thankyou,
Rathnakumar

**Comment by atoader** [comment]
@Rathnakmr sandboxes have a different upgrade path than production environments. Extensions published by developers are discarded whenever a sandbox is recreated or upgraded. With the next release, we will make it easier to publish extensions with dependencies.
We will take your feedback into consideration when planning the next release of our product.
