### ISSUE TITLE
Unable to set permission set to all users in my app extension

### ISSUE THREAD

**Issue by antoniotrives** [microsoft/AL#5227]
Hi,
I'm unable to set a permission set to all users from my app extension.
Does anyone know if this is a know issue?

Thanks,

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
