### ISSUE TITLE
Subpage line not editable after reinsert

### ISSUE THREAD

**Issue by JoelJame5** [microsoft/AL#5228]
We have a case where modification of a sales line will recreate a related line, deletes and inserts the child line. In the latest onprem and bc sandbox images the child line becomes non-editable.

Take the following as an example
![image](https://user-images.githubusercontent.com/27202678/63604235-2ade0a00-c5c3-11e9-812f-9f83b17c3428.png)

Onprem CU5: W1 13.5 (29483)
![EditableOnpremCU5](https://user-images.githubusercontent.com/27202678/63604992-f2d7c680-c5c4-11e9-9967-7e44beeb40f6.gif)

OnPrem: Version: Platform 14.0.34251.0 + Application 34444 (W1 14.3)
![LineNotEditable](https://user-images.githubusercontent.com/27202678/63605146-41856080-c5c5-11e9-91c5-1aa251846ceb.gif)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repo is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
