### ISSUE TITLE
Hyperlink on Reports

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/AL#5229]
Hi - We have our product in APP store and while working on reports, we found an issue and hence posting here to seek help.
We have our custom report, that prints information based on month
<img width="506" alt="image" src="https://user-images.githubusercontent.com/38437776/63627280-d4b99880-c5bb-11e9-96f2-597a12760429.png">
As per the screen shot, you can see that we have month,year as hyper link (highlighted in the screen shot)
On the report layout, we select "Go to URL" option and we hardcode the URL with the parameters (https://businesscentral.dynamics.com/)

<img width="641" alt="image" src="https://user-images.githubusercontent.com/38437776/63627342-282be680-c5bc-11e9-84b3-ca50ba06750e.png">

The problem is, when we run this report in docker image or on prem, it error out because its hardcoded to point to https://businesscentral.dynamics.com/.

How to deal with these kind of scenarios.
Please help!!

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
