### ISSUE TITLE
ConvertValueToBase64 is missing in BC15

### ISSUE THREAD

**Issue by svwfr** [microsoft/AL#5231]
BC Insider (platform 15.0.0.0) seems to not include the procedure .ConvertValueToBase64 within codeunit 10 (Type Helper).

Have this procedure been replaced? 

I use this command with BC14 Cu2 today.

**Comment by ftornero9** [comment]
Hello @svwfr 

There is a new codeunit "Base64 Helpers" with the base64 related functions.

Regards

**Comment by svwfr** [comment]
Thank you for fast response. I do confirm that the move-job works in my application.
Regards Sven

**Comment by rsgilbert** [comment]
You can use `Base64Text := TempBlob.ToBase64String();`   .
