### ISSUE TITLE
AL debugging isn't working

### ISSUE THREAD

**Issue by AntoineTal** [microsoft/AL#5234]
When trying to debug in Visual Studio Code by publishing on a Sandbox environment, the extension is published but the debug just stop working and the "LaunchBrowser" options doesn't work aswell. 

Publish your AL extension with visual studio code.

The correct behavior should be a debug which stay up, and allow us to see the current state of business central.

We are 4 working on the same kind of environment with VSC, and everyone have the same issue

**Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.152816
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Sandbox  v14.3.34444.0

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 

 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
