### ISSUE TITLE
on-premise development SSRS report 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#5236]
i installed my app on premise and in my app, i have a report (SSRS Report)  and from that   need to open new SSRS report having two parameters. 

my question is this, i need an URL dynamically which can open the report. 

NOTE: It is working fine for sandbox environment as i am able to get tenant ID dynamically and i pass that to SSRS report. but in case of on-premise I have No idea. 

Thanks in Advance !!!

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
