### ISSUE TITLE
BaseApp is now Base Application in version 15.x

### ISSUE THREAD

**Issue by ftornero9** [microsoft/AL#5237]
When creating a new project with AL:Go! in the last insider version it is created this dependecies:

![image](https://user-images.githubusercontent.com/12720964/63770077-a21de180-c8d4-11e9-8352-d2a331c7556d.png)
  
But after get an error downloading symbols and checking out the Extensions the new name is this one:

![image](https://user-images.githubusercontent.com/12720964/63770175-d8f3f780-c8d4-11e9-87b5-ddf643d3e000.png)

Regards

**Comment by atoader** [comment]
Hi! This was a minor omission on our part. It has been fixed in master and it will be available in the Docker preview in the following days.
