### ISSUE TITLE
Performance Issues with Custom Report Layouts

### ISSUE THREAD

**Issue by SteveyN** [microsoft/AL#5243]
Given that the design intention is that we cannot modify standard objects, we are forced to use Custom Report Layouts to modify the layout of a standard report.

This is useful, but we have noted critical performance issues that require us to go back to modifying and using the built-in RDLC layout.

In some cases, the running a report with a Custom Report Layout took around 6x longer that running a report using the Built-In Layout.

This obviously hampers our ability to move a customer's bespoke customisations out of standard modifications.

This was true as of BC v14.4, and performance was consistently poor on our machines and customer machines of varying ability.

**Comment by mynhardt7** [comment]
We have also noticed this exact issue with various customers of ours.

**Comment by atoader** [comment]
Thank you for the feedback @SteveyN! Unfortunately, we cannot help with resolving this issue. As noted in our FAQ https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-not-related-to-al-development-what-do-i-do , this repository is not the best place to report this type of issues. 

We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by Addice73** [comment]
Any news on this ? Was it posted to collaborate ?

**Comment by SteveyN** [comment]
@Addice73 
Our team is having trouble getting our accounts sorted for Collaborate, so we are unable to post at this time. If you (or anyone else who sees this message) are able to post to Collaborate, can you post this issue and link your post back here?

Many thanks

**Comment by Addice73** [comment]
[image: image.png]
Andrea
