### ISSUE TITLE
Printing multiple reports in Business Central

### ISSUE THREAD

**Issue by Chingyz** [microsoft/AL#5247]
I am trying to print multiple reports with one button.
When I try it with Report.RunModal it only prints the last report.
Functions Print and SaveAs are not available for extension development.
Is there something available to get this working?

Thank you in advance.

**Comment by ftornero9** [comment]
Hello @Chingyz,

The function Report.SaveAs() it is available for extensions.

Regards.

**Comment by Chingyz** [comment]
Hi @ftornero9,

Ah I see, apologies, I mistook the same error of Print for SaveAs.
I will try this method.

Thank you very much!

Kind regards.
