### ISSUE TITLE
How to  modify the quantity of any item?

### ISSUE THREAD

**Issue by jyotivarade** [microsoft/AL#5249]
Is possible to modify quantity of item pragmatically?

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
