### ISSUE TITLE
Unable to download Symbols for BC - On Premise 14.0.32600.0

### ISSUE THREAD

**Issue by ashishsharmanav** [microsoft/AL#5253]
Hello,
We have an On-Prem LS database that was created with BC 14 CU1. I have installed the VSIX from the DVD for BC14 CU1. I created a new project using AL Go!. When I download the symbols, app.json file is marked with an error as shown in attached screenshot, however, I tried to download symbols for Standard NAV database of the same version and it worked.
Steps and to reproduce the behavior:
1. Follow the same steps as mentioned above.
Versions:
LS Version: 14.01
AL Language: 3.0.168874
Business Central: Platform 14.0.32600.0 + Application 32615
Additionally, I have restarted the service tier afterwards. My service tier has the "Enable loading application symbol references" enabled.
![2019-09-04_16-57-04](https://user-images.githubusercontent.com/40493697/64262348-05e08400-cf3f-11e9-983a-cd52dea0ceb6.jpg)
![2019-09-04_16-57-34](https://user-images.githubusercontent.com/40493697/64262349-05e08400-cf3f-11e9-81c5-a650e650f657.jpg)

**Comment by atoader** [comment]
Have you generated the symbols using C/SIDE? Do you have the developer endpoint enabled? What records do you have in the Nav App table?

**Comment by ashishsharmanav** [comment]
Hi,

I was able to resolve the issue by downloading the latest version VS code 1.38.0.

Thanks.

**Comment by MatDDev** [comment]
Hi @ashishsharmanav

I have exactly the same problem #5308 

I am using the newest version of VS 1.31.1 and the problem remains. DId you do anything besides that? When i use Get-NAVAppInfo I don't see any symbols. Did you have the same?

**Comment by ashishsharmanav** [comment]
Hi @MatDDev , apologies for replying late. My issue was i couldn't download the symbols at all. Following are the steps i performed after downloading the latest version.

Powershell:
1.	Delete old symbols files if needed
Unpublish-NAVApp -ServerInstance $serverInstance -Name "System"
Unpublish-NAVApp -ServerInstance $serverInstance -Name "Application"
Unpublish-NAVApp -ServerInstance $serverInstance -Name "Test"
 
1.	Publish new symbols from path
$path = "C:\folder"
Publish-NAVApp -ServerInstance $serverInstance -PackageType SymbolsOnly -Path "$path\Microsoft_System_14.0.32600.0.app" -SkipVerification
Publish-NAVApp -ServerInstance $serverInstance -PackageType SymbolsOnly -Path "$path\Microsoft_Application_14.1.32615.0.app" -SkipVerification
Publish-NAVApp -ServerInstance $serverInstance -PackageType SymbolsOnly -Path "$path\Microsoft_Test_14.1.32615.0.app" -SkipVerification
 
1.	Check what symbols are published in database
Get-NAVAppInfo $serverInstance -SymbolsOnly | Format-Table

**Comment by VikalpSharma** [comment]
Hi @ashishsharmanav 

We are also facing this issue. we are using version 1.40.0 for VS code. LS and NAV version is same like yours. 
In step 2, you have mention the new symbols from path. How you got the new symbols ?

**Comment by ashishsharmanav** [comment]
Hi @VikalpSharma 

You can find new symbols in the Nav Setup DVD. 
For me, I could find it in : D:\Dynamics.365.BC.32615.W1.DVD\ModernDev\program files\Microsoft Dynamics NAV\140\AL Development Environment\

**Comment by VikalpSharma** [comment]
Hi @ashishsharmanav 

Thanks for the reply. We have generated the symbol for the on prem database by using the below link. 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side
then we download from the VS code it worked fine.
