### ISSUE TITLE
Relative paths for al.packageCachePath

### ISSUE THREAD

**Issue by paul-lbmc** [microsoft/AL#5256]
This is either not working or not documented (that I can find). The fact that there is a ./ in the default value for al.packageCachePath implies that relative paths should be supported, but to find the .alpackages folder in a peer folder, setting the value to ../PeerFolder/.alpackages or ..\\PeerFolder\\.alpackages both result in error AL1045: The package cache could not be found.

**To Reproduce**

Create folder structure like:
~\Project1\.alpackages
~\Project2

1. Add settings.json to Project2
2. Edit the settings.json file and add:
{
  "al.packageCodePath":"../Project1/.alpackages"
}
3. Build Project2

Example output:

```Microsoft (R) AL Compiler version 4.0.2.34975
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Wave2Tests' containing '1' files at '10:51:40.451'.

error AL1045: The package cache c:\Users\phaag\Documents\AL\Wave2Tests\.././.alpackages could not be found.

Compilation ended at '10:51:40.453'.

Error: The package could not be created.
```

**Versions:**
- AL Language: 4.0.1.166043
 - Business Central: n/a (occurs with multiple version targets)

**Comment by fvet** [comment]
@atoader  Any update on this issue?

I would also prefer the same behavior for the **al.ruleSetPath**, so I can share one 'company' ruleset across our extensions.

Somewhat related would be to have support for a shared '**Launch.json**' in multiroot workspace.
https://experience.dynamics.com/ideas/idea/?ideaid=557af51b-335d-ea11-b698-0003ff68bc25

**Comment by atoader** [comment]
Hi! The issue is in our backlog, but I cannot provide an ETA. We will set the appropriate milestone once the issue is picked up.
