### ISSUE TITLE
Cannot Download Symbols from Cloud Sandbox

### ISSUE THREAD

**Issue by EDGZTNSR** [microsoft/AL#5258]
**Describe the bug**
Cannot download Symbols from Cloud Sandbox
Im using the newest AL Language Version aswell as Sandbox Version: 14.4.35602.0
here are my App.json and launch.json
```
  "platform": "14.4.35602.0",
  "application": "14.4.35602.0",
  "idRanges": [{
    "from": 65000,
    "to": 65100
  }],
```
```
            "type": "al",
            "request": "launch",
            "name": "Microsoft cloud sandbox",
            "sandboxName": "Sandbox20190906",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
```

**Comment by EDGZTNSR** [comment]
[2019-09-06 14:28:55.65] Targeting Dynamics 365 Business Central.
[2019-09-06 14:28:55.66] Sending request to https://api.businesscentral.dynamics.com/v2.0/Sandbox20190906/dev/metadata
[2019-09-06 14:28:56.95] Error: An internal error has occurred

This is the Error Message I get.

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 

 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
