### ISSUE TITLE
Can't add factbox to page Listpage 516 from extension at BC365 SAAS

### ISSUE THREAD

**Issue by BjarneBilstrup** [microsoft/AL#5259]
I have created the following code 
![image](https://user-images.githubusercontent.com/45655355/64427696-1cf3b300-d0b2-11e9-874b-9cbd9eeeb5b9.png)
But the factbox does not appear on the page.
![image](https://user-images.githubusercontent.com/45655355/64427810-5d533100-d0b2-11e9-9319-5f6cbdbded94.png)
What can I have done wrong?

Bjarne Bilstrup

**Comment by dNsl9r** [comment]
I see that you are missing the ApplicationArea Property at the Factbox, that could be the reason. :-)

**Comment by BjarneBilstrup** [comment]
Hi Danis.

1000 Thanks for Your help.

Med venlig hilsen / Best regards / Mit Freundlichen Grüßen / Saludos cordiales
Bjarne Bilstrup
[cid:image001.png@01D567B0.541DECD0]
Telefon
+45 7478 3400
Mobil/SMS
+45 2014 2570
E-mail
bb@balance.as <mailto:bb@balance.as>
www.balance.as <http://www.balance.as>
[cid:image002.png@01D567B0.541DECD0]<http://www.balance.as/brancheloesninger/nav4/>[cid:image003.png@01D567B0.541DECD0]<http://www.balance.as/navision-e-handel/sana-webshop/>[cid:image004.png@01D567B0.541DECD0]<http://www.balance.as/microsoft-dynamics/microsoft-dynamics-nav/>[cid:image005.png@01D567B0.541DECD0]<http://www.balance.as/go-cloud/>
Fra: Danis F. <notifications@github.com>
Sendt: 10. september 2019 07:43
Til: microsoft/AL <AL@noreply.github.com>
Cc: Bjarne Bilstrup • balance.as <bb@balance.as>; Author <author@noreply.github.com>
Emne: Re: [microsoft/AL] Can't add factbox to page Listpage 516 from extension at BC365 SAAS (#5259)


I see that you are missing the ApplicationArea Property at the Factbox, that could be the reason. :-)

**Comment by atoader** [comment]
I will close this issue as it seems it has been resolved.
