### ISSUE TITLE
Publish-NAVApp for signed V2 packages

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#526]
Hello,

I've created a D365 Sandbox through @freddydk 's ARM template using the latest .isos from connect. If I try to publish with the Publish-NAVApp cmdlet my .navx file, i always get

```
VERBOSE: Opening admin connection to ServerInstance 'MicrosoftDynamicsNavServer$NAV'
VERBOSE: Admin connection to ServerInstance 'MicrosoftDynamicsNavServer$NAV' has been opened
VERBOSE: Performing the operation "Publish-NAVApp" on target "ServerInstance = MicrosoftDynamicsNavServer$NAV".
Publish-NAVApp : You cannot publish an extension that has not been code signed. To overrule this check and publish the
unsigned extension, set the –SkipVerification parameter.
At line:1 char:1
+ Publish-NAVApp -Path 'C:\temp\Axians Infoma_Entry search and find_1.0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Dynam...s.PublishNavApp:PublishNavApp) [Publish-NAVApp], Inv
   alidOperationException
    + FullyQualifiedErrorId : Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
```

If I check the file with signtool it seems to be ok:

```
signtool.exe verify /pa "F:\vscode\rmt\D365\Entry search and find\Axians Infoma Entry search and find_1.0.1.0.navx"
File: F:\vscode\rmt\D365\Entry search and find\Axians Infoma_Entry search and find_1.0.1.0.navx
Index  Algorithm  Timestamp
========================================
0      sha1       None

Successfully verified: F:\vscode\rmt\D365\Entry search and find\Axians Infoma_Entry search and find_1.0.1.0.navx
```

If I run the cmdlet with -SkipVerification it works fine. I use the following command to sign the file

```
signtool.exe sign /f "f:\temp\Axians Infoma Code Signing.p12" /p "…" /t http://timestamp.verisign.com/scripts/timestamp.dll "F:\vscode\rmt\D365\Entry search and find\Axians Infoma_Entry search and find_1.0.1.0.navx"
```

Any ideas why this fails?

**Comment by StanislawStempin** [comment]
We did not yet look into publishing of signed V2 packages. I suspect that most of the flow works just because it's similar to V1. I will use this issue for tracking of when the functionality is ready.

**Comment by tfenster** [comment]
How could I then test the deployment of a signed V2 extension? Or is this only possible when actually uploading to AppSource?

**Comment by pzentner** [comment]
while you are working on this, maybe add an option to the packaging process in VSCode to allow signing when building it - I guess we could always add it as a post build step ourselves though

**Comment by StanislawStempin** [comment]
This problem should have been solved by now. The key is to sign the app using an updated navsip.dll available since NAV 2018.
