### ISSUE TITLE
PingPong AddIn Error

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5260]
Are there any substitute for PingPong addin in AL?

![1](https://user-images.githubusercontent.com/31925856/64433485-d6f11c00-d0be-11e9-971c-b305522f3854.png)

**Comment by atoader** [comment]
@tomasevicstefan what version of the platform are you using?

**Comment by tomasevicstefan** [comment]
docker sandbox
image: "mcr.microsoft.com/businesscentral/onprem:13.6.29777.0-is"

**Comment by atoader** [comment]
As far as I remember, the issue has been fixed in the 14.x version. If possible, upgrade to that version or open a hotfix request.

**Comment by tomasevicstefan** [comment]
Tnx, will check that.
