### ISSUE TITLE
The property 'CaptionClass' can only be set if the property 'Type' is set with any of the values

### ISSUE THREAD

**Issue by dmaxwe11** [microsoft/AL#5261]
I've upgraded docker from: 
Version: Platform 14.0.34251.0 + Application 34444 (W1 14.3)
Azure AD tenant: common, Environment: Production

to:

Version: Platform 14.0.35570.0 + Application 35602 (US Business Central 14.4)
Azure AD tenant: common, Environment: Production

My Code is a simple PageExtension to the Customer List that modifies a flowfield caption via the captionclass property so I can do a function call.  The following code use to work, now it doesn't:

        modify("Balance Due (LCY)")
        { CaptionClass = GetCaptionClass(FIELDNO("Balance Due (LCY)")); }

**Comment by atoader** [comment]
@dmaxwe11 what type is "Balance Due (LCY)"? Does it come from a standard page?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
