### ISSUE TITLE
Error compiling apps when 2 Tables with the same ENU Caption exist

### ISSUE THREAD

**Issue by PatrickSchiefer** [microsoft/AL#5263]
**Describe the bug**
When 2 tables with same caption exists apps won't compile

**To Reproduce**
1) create a Table "50000 Customer Upgrade" 
2) set the caption to Customer
3) compile, sync and generate Symbols 
4) Download Symbols via VSCode
5) Compile a app against generated Symbols you get following error.

error AL1024: A package with publisher 'Microsoft', name 'Application', and a version compatible with '14.0.0.0' could not be loaded. An element with the same key but a different value already exists. Key: Customer

**Expected behavior**
The Name of the object should be used for checking of duplicates not the caption

**Versions**
AL Language 3.0.168874
BC 14.0.29530

Best Regards,
Patrick

**Comment by epernst** [comment]
I'm getting the same error in the AL output in VSCode on version 14.0.35916.0, but with different key. 

Mine is a standard DB with one c/al table and one page and the key is "Test Tool" (not part of my code, but test toolkit is loaded).

**Comment by epernst** [comment]
We were able to track back the error to a specific page. Here there were a action caption called "Print [PDF]". Changing it to "Print PDF" and recompile cleared up the error. 
It has not been something I could create a repo for, as our system has many other "XXXX [XXX]" captions not causing any issues.
