### ISSUE TITLE
Issue with a Repeater/ListPart in a NavigatePage

### ISSUE THREAD

**Issue by SmartNavisys** [microsoft/AL#5266]
This regards application version 14.4.35602.0 as an extension. For a wizard type page with PageType of NavigatePage, if a Repeater (or ListPart contianing a Repeater) is hidden though its visible property (eg a Back button), repeating an action to make it visible again locks up the session.
Oddly, when the repeater is partially drawn on screen and seems to remember the previous Rec position (more noticible with MultipleNewLines set to True). When this occurs, often the first column is moved one colum to the right, the first colum has a blank caption, and reserved space for the repeater is whitespace after this row and second column.
Simple objects to reproduce this issue. Run in web client, then click Toggle Subpage twice.

[Wizard.zip](https://github.com/microsoft/AL/files/3595317/Wizard.zip)

**Comment by SmartNavisys** [comment]
Appologies for posting here as I could not find the correct bug reporting page in Collaborate.

**Comment by atoader** [comment]
Hi @SmartNavisys ! As the bug you are reporting is in a version that is in mainstream support and in an area of the product that is not related to the development experience, we cannot provide assistance on this forum. 
You can file a bug on Collaborate at https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/bugs/create . If you do not have access to that page, please contact dyn365bep@microsoft.com

**Comment by SmartNavisys** [comment]
No bug to report now. This works as intended in 15.0.36560.0 : )
