### ISSUE TITLE
Best Practice to support extra fields on Record Link

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#5268]
The AL compiler give the error:

`The system or virtual table 'Record Link' cannot be extended. AL(AL0525)`

In C/AL we have 5 extra fields added in the Record Link table, what is the best practice to move to AL?

**Comment by bvbeek** [comment]
Any news on this?

**Comment by EmilDamsbo** [comment]
I realize this is an old issue, however, this repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://www.dynamicsuser.net/nav)
