### ISSUE TITLE
Modify applicationarea property with pageextensions

### ISSUE THREAD

**Issue by michaelsimonsendk** [microsoft/AL#5271]
**Describe the bug**
It seems not to be possible to modify the app.area property on page objects. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to VS Code:

``` 
pageextension 50001 "Extending Budget" extends Budget

{
    Description = 'My Exteded Budget';
    ApplicationArea = All;

    layout
    {
        modify(BudgetName) { ApplicationArea = All; }
    }

    actions
    {
        modify(GLBalanceBudget) { ApplicationArea = All; }
    }

} 
```

**Expected behavior**

In the documentation of "ApplicationArea Property" the page object is mentioned.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview

**Versions:**
 - AL Language: 3.0.168874
 - Business Central: DK Business Central 14.3 Build: 34444

**Comment by JohanStenberg100** [comment]
Hi @michaelsimonsendk, we do not allow modification of the page object. We will update the documentation, thanks!

**Comment by JohanStenberg100** [comment]
@michaelsimonsendk if you aren't satisfied with this answer, please go to [https://aka.ms/BusinessCentralideas,](https://aka.ms/BusinessCentralideas) and file this feature request or upvote it if it's present. We will update the documentation on the next docs refresh. Thanks
