### ISSUE TITLE
Publish-NAVApp fails with AL0132

### ISSUE THREAD

**Issue by peikba** [microsoft/AL#5277]
Running version 11.0.23572.0 (NAV2018)
I have 4 x 2 databases (4 live and 4 testing databases), all with this version
The app has been developed in Visual Studio code and works fine in the development environment.
When I copy the app to the live and testings servers, I use PowerShell to install the app. Here I get the following result:
- Live databases: all are installed fine and working fine
- Testing databases: Two testing databases are installed fine and working fine 
The last two databases I get the AL0132 error as shown below and it does not seem to recognize the standard tables.

I have already tried to run:
  Sync-NAVTenant -ServerInstance $ServerInstance 
  Sync-NavApp $ServerInstance -Name $AppName
Then I switched version and ran:
  Sync-NAVTenant -ServerInstance $ServerInstance 
  Sync-NavApp $ServerInstance -Name $AppName
  Start-NAVAppDataUpgrade -ServerInstance $ServerInstance -Name $AppName

I restarted the service tier

All with no luck

Any suggestions?

![image](https://user-images.githubusercontent.com/33752561/64970453-1df0c580-d8a6-11e9-8244-d81e6f26a3cf.png)

**Comment by peikba** [comment]
Just an extra information.
The extension has been installed in the database previously.
It was during an upgrade it started failing.

**Comment by atoader** [comment]
@peikba do you have the Application symbols published to the two testing databases? It seems that your extension is using objects that come from the base application.

**Comment by peikba** [comment]
I did this test to check
1) installed VS code on the server
2) Uploaded the whole project to the server
3) Downloaded symbols from the testing databases - No problem
4) Pressed Ctrl+F5 to publish and install the extension to the server
Same error

**Comment by atoader** [comment]
What does the "Nav App" table contain in the database where you are trying to publish? What happens if you restart the server?
Considering the version that you are targeting, the best way forward would be to go through the usual channels for requesting a hotfix.

**Comment by peikba** [comment]
Restarted the server - No change.
NavApp does not contain any sign of this extension - all others remain

We are going to upgrade as soon as we have a stable situation, but I thought that you could 1) maybe help out or 2) wanted to know about the issue

**Comment by atoader** [comment]
It appears you have not published the Application symbols. If you are doing side-by-side development with C/SIDE, what application version are you targeting and what is the value of the applicationversion column in the dbo.$ndo$dbproperty ? 
A solution is to download the Application symbols from VSCode and then publish them to the database using the Publish-NavApp command with the switch -SymbolsOnly. Can you try this and let me know if it works?

**Comment by peikba** [comment]
Solved it myself:
- Opened the Development Environment with GenerateSymbolReference=Yes
-  Compiled all objects
- Ran the Power Shell scripts:
     Publish-NAVApp -ServerInstance $ServerInstance -Path $Path -SkipVerification 
     Sync-NAVTenant -ServerInstance $ServerInstance 
     Sync-NavApp $ServerInstance -Name $AppName
     Start-NAVAppDataUpgrade -ServerInstance $ServerInstance -Name $AppName  

Problem solved
