### ISSUE TITLE
Not enough memory resources are available to complete this operation

### ISSUE THREAD

**Issue by skkulla** [microsoft/AL#5278]
I have NAV2018 container with CU14 with 4G memory on Windows 10 host. When I try to publish the app using VS Code f5, I get the above error message.

After I close and try a few times, the error will go away but reappears in the next publish. Do we know what causing the above error

This is the full error message

"The request for path /nav/dev/apps?SchemaUpdateMode=synchronize failed with code InternalServerError. Reason: error CS0013: Unexpected error writing metadata to file 'c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\assembly\NavAppGroup_13549268f906f2e4b56e48302ea63f15.dll' -- 'Not enough memory resources are available to complete this operation. '

**Comment by atoader** [comment]
@skkulla how big is the application that you are publishing? Have you tried increasing the amount of memory to 8GB? 
We have invested significantly in improving the performance of the compiler, but most of these investments will be visible starting from the Wave 2 2019 release.

**Comment by skkulla** [comment]
I have recreated it with 8GB and looks like it is stable now, but when I check docker stats it still shows the memory as 3.4 GB.

**Comment by atoader** [comment]
I am glad this is stable. I am not sure how memory is reported in Docker, but it is something outside our control. I will close the issue as it seems the main problem has been resolved. Thank you for reporting this issue!
