### ISSUE TITLE
Assisted Setup / Business Setup

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#528]
Currently, you are blocking access to all system tables for target=Extension. This also means that we do not have any way right now to add our app logo to the entries in the aggregated assisted setup or the business setup (obviously, only through the discovery event pattern). 

It would be great, if you either would provide access to the necessary tables or if you would change the scope of function "AddExtensionIconToBusinessSetup" in table 1875 to global (external) so we can call it and then also implement the same functionality in table 1808 "Aggregated Assisted Setup".

**Comment by StanislawStempin** [comment]
Can you list the system tables which you require for this scenario? We will evaluate either enabling the right system tables or changing the application to support this scenario.

**Comment by pzentner** [comment]
Table 2000000160 NAV App
Table 2000000181 Media

Both are required for the following scenario:

Access NAVApp.Logo.MEDIAID to get the Media and then create a stream from the media and stream it into the "Icon" fields in Tables 1876 and 1810.

Ideally, this wouldn't even be needed, because (at least partially), the functionality is already in the base app. So, proposed changes:

Option 1:
- Add Read permissions to tables 2000000160 and 2000000181 for target = extension

Option 2:
- Include access to NAVApp logo into table 2000000151 "NAV App Tenant App", since we can access this one with target = extension
- Include ability to get App logo stream from NAV App Tenant App

Option 3:
- Table 1875: Change scope of "AddExtensionIconToBusinessSetup" to global (external)
- Table 1808: Create similar function "AddExtensionIconToAssistedSetup" with scope global (external)

Option 4:
- Provide AL function to access the App Logo as readonly stream directly from object NavApp

Not sure, which one would be the best, Option 3 would be the easiest from a partner perspective, Option 4 might be the most versatile option. Option 1 might be the easiest from your perspective, as it's no base app code changes and no new AL functions.

**Comment by DominikWidmann** [comment]
We have the same issue and unsuccessfully tried a workaround with the tables Media Resources (2000000182) and Media Repository (9400). 
From our point of view another option (Option 5) would be, to reference in one of these tables to the media which is installed with an app.

**Comment by StanislawStempin** [comment]
Is the method Tab1875.InsertExtensionBusinessSetup() sufficient?  It does call AddExtensionIconToBusinessSetup internally

**Comment by pzentner** [comment]
Yes, it is sufficient. I was originally adding the extension icon to the setup at the time of initializing the extension, but this is actually more elegant, since the icon only is added, if a user ever goes to the manual setup and doesn't only use the wizard.

**Comment by StanislawStempin** [comment]
Ok, thanks. We will look into adding a corresponding function for the Assisted Setup.

**Comment by thpeder** [comment]
@pzentner take a look at Table 1808 "Aggregated Assisted Setup" procedure AddExtensionAssistedSetup.
