### ISSUE TITLE
Business Central 150 Preview 2 download symbols

### ISSUE THREAD

**Issue by dpvanes** [microsoft/AL#5281]
**Describe the bug**
We installed a new server with preview 2 on it. When I create a new project and try to download the symbols in Visual Studio I get the following error (long)

> Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
> Processing of message 'al/downloadSymbols' failed with error: 'Kan bestand of assembly System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.'
> Details:
> System.IO.FileNotFoundException: Kan bestand of assembly System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
> Bestandsnaam: System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>    bij Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext()
>    bij System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
>    bij Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken)
>    bij Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\360\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:regel 43
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\360\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:regel 64
> 
> WRSCH: registratie van assembly-bindingen is uitgeschakeld.
> Als u assembly-bindingsfouten wilt registreren, stelt u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) in op 1.
> Opmerking: er is een prestatiestraf gekoppeld aan de registratie van assembly-bindingsfouten.
> Als u deze functie wilt uitschakelen, verwijdert u de registerwaarde [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> 

**To Reproduce**
Try to download symbols...

``` AL Code to reproduce the issue ```
My launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "https://MyServer",
            "serverInstance": "MyInstance",
            "authentication": "Windows",
            "port": 7149,
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
**Expected behavior**
I expected the symbols to be downloaded

**Screenshots**

**Versions:**

 - AL Language: 4.0.172584

 - Business Central: 150 Preview 2

**Comment by atoader** [comment]
Do you have .NET Framework 4.7.2 installed on the machine that has VSCode installed? Our extension depends on .NET Framework 4.7.2 and this seems like the extension cannot startup because it cannot find an assembly from the framework.

**Comment by dpvanes** [comment]
I do now, and it works, thanks
