### ISSUE TITLE
Using backslash to start a new line in the message window can not work on latest preview release

### ISSUE THREAD

**Issue by monchangg** [microsoft/AL#5282]
**Describe the bug**
Using backslash to start a new line in the message window can not work on latest preview release. 
Following is my AL code. Is this the latest preview version's bug?
```
local procedure ShowMessage()
    var
        lText: Text;
        iNumber: Decimal;
    begin
        lText := 'ABCDE';
        iNumber := 12345.678;
        Message('You can use message windows to display text and numbers: \' + 'The number:%1\' + 'The text:%2', iNumber, lText);
    end;
```

The result on latest preview release:
![image](https://user-images.githubusercontent.com/22004532/65131217-6e485e80-da31-11e9-8f73-4e20f48bb028.png)

The result on current BC version is expected:
![image](https://user-images.githubusercontent.com/22004532/65131290-8e781d80-da31-11e9-809b-b67ff1ce502b.png)

 - AL Language: 3.0.168874
 - Business Central: 14.0.29537.31808-US

 - AL Language (Preview Release): 4.0.170493
 - Business Central (Preview Release): 15.0.36145.0-us

**Comment by JuricaB** [comment]
I have the same issue on using full release of 15.0 (Platform 15.0.36510.0 + Application 15.0.36560.0) with AL Language 4.0.182565

**Comment by thpeder** [comment]
Seems related to #5350

**Comment by dtkb** [comment]
This is fixed now:

![image](https://user-images.githubusercontent.com/63455896/105981773-60c3cf80-608e-11eb-9293-ecf4c3b2e25e.png)

Version: GB Business Central 17.3 (Platform 17.0.20458.21149 + Application 17.3.20469.21180)

**Comment by DmitrijYudin** [comment]
The same bug on Version: DK Business Central 21.4 (Platform 21.0.52534.53780 + Application 21.4.52563.52602)

**Comment by dnpb** [comment]
Yes, it came back, and was apparently fixed again; from a search:

https://github.com/microsoft/AL/issues/7327
