### ISSUE TITLE
Could not able create user in docker

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#5283]
Hello,

I have downloaded power-shell script to create sandbox container from the BC online, after executing the script, it installed BC Docker, it is not able to create the users.

Getting this below error.

App successfully published
Invoke GET on http://172.26.26.53:7048/NAV/api/beta/companies?$filter=name%20eq%20%27CRONUS%20UK%20Ltd.%27&tenant=default
Invoke POST on http://172.26.26.53:7048/NAV/api/Microsoft/Setup/beta/companies(b145ef70-e92d-437e-be23-39b865f70e22)/testUsers?tenant=
default
Invoke-RestMethod : {"error":{"code":"Internal_ServerError","message":"The new users do not meet the terms of the current license. 
The current license allows 2 full users and 0 limited users.  CorrelationId:  12530956-dd8f-40c0-8805-819ab6dfef6c."}}
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.1\Api\Invoke-NavContainerApi.ps1:139 char:5
+     Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Thanks,
Sainath

**Comment by abison007** [comment]
Can you please share here, if you have identified any way to resolve this issue?

**Comment by thpeder** [comment]
Issues related to navcontainerhelper or docker should be filed on **https://github.com/microsoft/navcontainerhelper** or **https://github.com/microsoft/nav-docker**.

Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and if that doesn't resolve your issue, create a new issue in the right repo.
