### ISSUE TITLE
Change company after creating company (sessionSettings)

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/AL#5285]
After creating a new company
`codeunit 1800 "Assisted Company Setup" - CreateNewCompany(NewCompanyName)`
then using the sessionSettings to open new company
```
    local procedure RefreshSession()
    var
        sessionSetting: SessionSettings;
    begin
        sessionSetting.Init();
        sessionSetting.Company := TempCompanyInformation."Phone No. 2";
        sessionSetting.LanguageId := 3081;
        sessionSetting.LocaleId := 3081;
        sessionSetting.RequestSessionUpdate(true);
    end;
```
the page just hangs, and does not open the role center in the new company.
This may be related to [ALAppExtensions #4114](https://github.com/microsoft/ALAppExtensions/issues/4114) which I believe is fixed in version 15.

**Comment by PooyaKharamesh** [comment]
Hi @TimothyWatkins 
As a quick hint you need to also initialize the company after creating it. 

This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

/Pooya
