### ISSUE TITLE
 Get-NavAppRuntimePackage in App with dependecies

### ISSUE THREAD

**Issue by CarlosAndreuLlaneras** [microsoft/AL#5286]
**Describe the bug**
I am using  Get-NavAppRuntimePackage succesfully with apps with no dependencies, but when I try to use it with a app that has dependencies the command throws a compilation error that says that the dependant app could not be loaded and therefore, the resources (tables, codeunits, etc.) from this app are missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/53298196/65376013-7572a500-dc9b-11e9-9bd0-35c586f08c57.png)

**Versions:**

 - AL Language: 3.0.172401

 - Business Central: 14.6.36449.0 (ES)

**Comment by atoader** [comment]
@CarlosAndreuLlaneras can you reproduce this issue on the latest build from the Wave 2 2019 release?

**Comment by CarlosAndreuLlaneras** [comment]
Hi @atoader.
I get the same result on a 15.0.36145.0 (es) docker.

But I've found a way to get the runtime package for apps with dependencies.
I have generated the runtime package, installing the root extension via powershell (instead of doing it from Visual Studio Code (by pressing F5))
In this example, I installed "iDynamics License Management Library" via Powershell and "iDynamics Printing Documents" from Visual Studio Code. 
![image](https://user-images.githubusercontent.com/53298196/66204182-93cc9d80-e6aa-11e9-8aff-0acb850789c9.png)

Could you please tell us the considerations to take into account regarding the runtime packages generation and Visual Studio Code? 

Thanks

**Comment by kalberes** [comment]
This is a bug as I see it. Getting runtime packages should work even if published from VsCode.

**Comment by JohanStenberg100** [comment]
Hi @CarlosAndreuLlaneras, can you verify that you really can reproduce this on 15.x? I'm unable to reproduce it. I see also in your last message you state that you installed `iDynamics Printing Documents` from VS Code, and you manage then to download it?

**Comment by CarlosAndreuLlaneras** [comment]
Hi Johan,
Yes I've reproduced it again on 15.2 (ES).
The steps I've followed are:
**Test 1:**
1- Create a new docker "bc152es" (Version: ES Business Central 15.2 (Platform 15.0.37954.0 + Application 15.2.38034.0)
2- Install the library app from Visual Studio Code (in this case "iDynamics License Management Library")
3- Generate the runtime package for this app. 
`Get-NavContainerAppRuntimePackage -containerName bc152es -appName 'iDynamics License Management Library'`
4-. Install the second app (that depends on the first one) from Visual Studio Code. In my case "iDynamics Printing Documents".
5- Try to generate the runtime package and I get this error message: 
![image](https://user-images.githubusercontent.com/53298196/69168775-96b70c80-0af7-11ea-829a-06e11386fdf5.png)

6- I've tried again with another app (that also depends on the first one)("iDynamics IRPF"), with the same result.

**Test 2:**
1- Uninstall and unpublish all the previously installed apps.
2- Install the library app using Powershell: 
`Publish-NavContainerApp -containerName bc152es -appFile 'D:\iDynamics Business Solutions_iDynamics License Management Library_1.4.0.0.app' -skipVerification -install -scope Tenant`
3- Generate the runtime package for this app. 
4-. Install "iDynamics Printing Documents" **from Visual Studio Code**.
5- Generate the runtime package without errors: 
![image](https://user-images.githubusercontent.com/53298196/69170260-1645db00-0afa-11ea-9790-85908b2c4caa.png)

If you need mor info, please let me know.

Thanks
Carlos

**Comment by JohanStenberg100** [comment]
Hi @CarlosAndreuLlaneras, thanks for these clear repro steps. We will investigate thanks

**Comment by JohanStenberg100** [comment]
Hi again @CarlosAndreuLlaneras. Try specifiying the tenant ID and it should work. When you are working with development extensions, these are scoped by tenant ID.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by dam-pav** [comment]
This issue is far from resolved. I'm facing exactly the same obstacle in v22:
![image](https://github.com/microsoft/AL/assets/46426230/088792a6-5820-45c4-bc6c-b8e6097cfc3e)

Should we open a new thread or continue this one?

More importantly, what kind of information would be helpful?

**Comment by dam-pav** [comment]
The solution is to explicitly specify the tenant. Thanks.
