### ISSUE TITLE
Cannot implicitly convert type 'None' to 'Text'

### ISSUE THREAD

**Issue by EDGZTNSR** [microsoft/AL#5287]
**Describe the bug**
I'm trying to call the Method "BLOBExportToServerFile" in the "File Management" Codeunit but I get an Error I can't explain to myself.

When I try to Call the Function with its TempBlob and Text parameter
![image](https://user-images.githubusercontent.com/39260158/65405419-4e6fbc80-dddc-11e9-9296-98214cd9cfe8.png)
I get the following Error Message:
![image](https://user-images.githubusercontent.com/39260158/65405446-6f381200-dddc-11e9-875a-0069346ef1b2.png)
How the Function is called: 
![image](https://user-images.githubusercontent.com/39260158/65405462-8119b500-dddc-11e9-9ffe-9c588092e39a.png)
As you can see the LocalTempFile is a Text Variable.
![image](https://user-images.githubusercontent.com/39260158/65405485-968edf00-dddc-11e9-8e2c-4ad29e6930df.png)
![image](https://user-images.githubusercontent.com/39260158/65405722-6b58bf80-dddd-11e9-8c9d-378f996a671a.png)

But when I change the Text Parameter to an Integer I get an Error as wanted.
![image](https://user-images.githubusercontent.com/39260158/65405599-db1a7a80-dddc-11e9-829d-7c49afa872c9.png)
![image](https://user-images.githubusercontent.com/39260158/65405607-e372b580-dddc-11e9-9469-4653a064419f.png)

Do I understand something wrong or is there an Error in the AL Compiler?

**Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.168874
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:

**Comment by PooyaKharamesh** [comment]
would you please provide us the version of BC that you are using?

The signature of method has been changed in BC 15 and it is marked for only On-prem usage. here is the new signature 
procedure BLOBExportToServerFile(var TempBlob: Codeunit "Temp Blob"; FilePath: Text)

and a sample usage 

                var
                    fileManagment :Codeunit "File Management";
                    tempBlob : Codeunit "Temp Blob";
                begin
                    fileManagment.BLOBExportToServerFile(tempBlob,'some path');
                end;

/Pooya

**Comment by EDGZTNSR** [comment]
Hi @PooyaKharamesh 
Were using Application Build 32990, Platform Build 32943.

**Comment by EDGZTNSR** [comment]
I've only met the problem in one Extension. Another Extension that uses the same symbol files does not have this problem.
![image](https://user-images.githubusercontent.com/39260158/65517669-6847f700-dee3-11e9-833b-506d53163e61.png)

Here it works without a problem

**Comment by adrian-panaite** [comment]
The function BLOBExportToServerFile has NO return type, but you are trying to retrieve the return value.
You have to change 
**TxtPath_l := FileManagement_l.BLOBExportToServerFile(TempBlob_l, LocalTemp_l);**
to 
**FileManagement_l.BLOBExportToServerFile(TempBlob_l, LocalTemp_l);**
and it will work. I don't know what you need to do with the **TxtPath_l** variable, but you need to find another way to assign a value to it.

**Comment by qutreson** [comment]
Closing this issue as the compiler diagnostic reported is valid. Following the guidance from @adrian-panaite and @PooyaKharamesh will fix your issue.
