### ISSUE TITLE
Empty Values in SymbolReference.json for table fields

### ISSUE THREAD

**Issue by JoergBrugman** [microsoft/AL#5288]
In versions BC 15 Preview , the TableReleation and CalcFormula properties are created with empty values ​​for table fields. 
This error occurs in the base app, the system app, and even a self-created app.

We assume that this is an error, because in earlier versions the properties and their values ​​were generated by the compiler.

We urgently need these property values ​​back for analysis and for an AL Developer tool. Without these properties and values ​​we would have to stop our tool development.

We have tested this behavior in the AL version al-4.0.170493.

**Comment by PooyaKharamesh** [comment]
Hi,

would you please provide us some instances and why would it interrupt your development. A clear repro or code snippet will help us to address the issue faster.

/Pooya

**Comment by kalberes** [comment]
I am sorry, but this cannot be treated as an error. The internals of the symbolreference file is really internal. They will change. The previous symbol generation for the Baseapp was C/SIDE based, teh current one on teh AL compiled base app. Different code, different architecture.

We can do what we can but this is also work for us.

**Comment by kalberes** [comment]
WE have decided to fix this issue.

**Comment by JoergBrugman** [comment]
Hi, 
are you already planning when the fix will be available?

**Comment by atoader** [comment]
Hi! The next major release of the product will contain this change.
