### ISSUE TITLE
Length of the identifier cannot exceed 120 characters

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#529]
The last field on the Shipping Agent Services page has a non-field source expression. Extending that page and using the last field as an anchor (which was generated by txt2al) results in an error:
![image](https://user-images.githubusercontent.com/19348055/29597770-dd1ec16c-8792-11e7-8061-558e05caa4d5.png)

**Comment by StanislawStempin** [comment]
This is a bug in how we generate the default name for a field that wasn't explicitly named. We will look into ways of fixing it.

**Comment by StanislawStempin** [comment]
This is fixed in November Update. Source Expression based controls that exceed 120 characters will fall back to ControlXXX naming scheme, where XXX is the Id.
