### ISSUE TITLE
Set permissions in code for page and table extensions

### ISSUE THREAD

**Issue by hhout** [microsoft/AL#5291]
For a Table or Page it's possible to set the Permissions property via code if applicable.
_Example: Permissions = tabledata _TableName_ = RD;_

The Permissions property should also be available for page- and table **extensions**. For example specific validation code in this case shouldn't be placed in codeunits to make it possible to give permissions via code.

- AL Extension Version: 3.0.118998
- Version: Platform 14.0.32600.33003 + Application 33107 (W1 14.1)

**Comment by kalberes** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas  
We're constantly monitoring top Ideas and will consider them for a future release.
