### ISSUE TITLE
IF NOT HideDialog THEN missing from codeunit 5982 (Service-Post+Print)

### ISSUE THREAD

**Issue by buyerstown** [microsoft/AL#5293]
- AL Extension Version: 3.0.168874

Codeunit 5981 (Service-Post (Yes/No) contains the following code:

OnBeforeConfirmServPost(PassedServiceHeader,HideDialog,Ship,Consume,Invoice,IsHandled,PreviewMode,PassedServLine);
IF IsHandled THEN
  EXIT;

WITH PassedServiceHeader DO BEGIN
  **IF NOT HideDialog THEN**
    CASE "Document Type" OF

but in Codeunit 5982 (Service-Post+Print) the equivalent code is:
OnBeforeConfirmPost(ServiceHeader,HideDialog,Ship,Consume,Invoice,IsHandled);
IF IsHandled THEN
  EXIT;

WITH ServiceHeader DO BEGIN
  CASE "Document Type" OF

There is no IF NOT Hide Dialog THEN in this code meaning that extensions cannot suppress the STRMENU Dialog menu from being displayed to users.

**Comment by kalberes** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
