### ISSUE TITLE
Processing of message 'al/gotodefinition' failed with error: 'SyntaxTree

### ISSUE THREAD

**Issue by kavila02** [microsoft/AL#5294]
Processing of message 'al/gotodefinition' failed with error: 'SyntaxTree 'page 49 "Purchase Quote"
{
  layout
  {
    area(Content)
    {
      group(General)
      {
        field("No.";"No.")
        {
        }
        field("Buy-from Vendor No.";"Buy-from Vendor No.")
        {
        }
        field("Buy-from Vendor Name";"Buy-from Vendor Name")
        {
        }
        group("Buy-from")
        {
          field("Buy-from Address";"Buy-from Address")
          {
          }
          field("Buy-from Address 2";"Buy-from Address 2")
          {
          }
          group(Control79)
          {
            field("Buy-from County";"Buy-from County")
            {
            }
          }
          field("Buy-from Post Code";"Buy-from Post Code")
          {
          }
          field("Buy-from City";"Buy-from City")
          {
          }
          field("Buy-from Country/Region Code";"Buy-from Country/Region Code")
          {
          }
          field("Buy-from Contact No.";"Buy-from Contact No.")
          {
          }
        }
        field("Buy-from Contact";"Buy-from Contact")
        {
        }
        field("Document Date";"Document Date")
        {
        }
        field("Due Date";"Due Date")
        {
        }
        field("Order Date";"Order Date")
        {
        }
        field("No. of Archived Versions";"No. of Archived Versions")
        {
        }
        field("Requested Receipt Date";"Requested Receipt Date")
        {
        }
        field("Vendor Order No.";"Vendor Order No.")
        {
        }
        field("Vendor Shipment No.";"Vendor Shipment No.")
        {
        }
        field("Purchaser Code";"Purchaser Code")
        {
        }
        field("Campaign No.";"Campaign No.")
        {
        }
        field("Order Address Code";"Order Address Code")
        {
        }
        field("Responsibility Center";"Responsibility Center")
        {
        }
        field("Assigned User ID";"Assigned User ID")
        {
        }
        field(Status;Status)
        {
        }
      }
      part(PurchLines;"Purchase Quote Subform")
      {
      }
      group("Invoice Details")
      {
        field("Currency Code";"Currency Code")
        {
        }
        field("Expected Receipt Date";"Expected Receipt Date")
        {
        }
        field("Payment Terms Code";"Payment Terms Code")
        {
        }
        field("Payment Method Code";"Payment Method Code")
        {
        }
        field("Transaction Type";"Transaction Type")
        {
        }
        field("Shortcut Dimension 1 Code";"Shortcut Dimension 1 Code")
        {
        }
        field("Shortcut Dimension 2 Code";"Shortcut Dimension 2 Code")
        {
        }
        field("Payment Discount %";"Payment Discount %")
        {
        }
        field("Pmt. Discount Date";"Pmt. Discount Date")
        {
        }
        field("Shipment Method Code";"Shipment Method Code")
        {
        }
        field("Payment Reference";"Payment Reference")
        {
        }
        field("Creditor No.";"Creditor No.")
        {
        }
        field("On Hold";"On Hold")
        {
        }
        field("Tax Liable";"Tax Liable")
        {
        }
        field("Tax Area Code";"Tax Area Code")
        {
        }
      }
      group("Shipping and Payment")
      {
        group(Control45)
        {
          group(Control20)
          {
            field(ShippingOptionWithLocation;ShipToOptions)
            {
            }
            field(ShippingOptionWithoutLocation;ShipToOptions)
            {
            }
            group(Control57)
            {
              group(Control55)
              {
                field("Location Code";"Location Code")
                {
                }
              }
              field("Ship-to Name";"Ship-to Name")
              {
              }
              field("Ship-to Address";"Ship-to Address")
              {
              }
              field("Ship-to Address 2";"Ship-to Address 2")
              {
              }
              group(Control90)
              {
                field("Ship-to County";"Ship-to County")
                {
                }
              }
              field("Ship-to Post Code";"Ship-to Post Code")
              {
              }
              field("Ship-to City";"Ship-to City")
              {
              }
              field("Ship-to Country/Region Code";"Ship-to Country/Region Code")
              {
              }
              field("Ship-to Contact";"Ship-to Contact")
              {
              }
            }
          }
        }
        group(Control51)
        {
          field(PayToOptions;PayToOptions)
          {
          }
          group(Control67)
          {
            field("Pay-to Name";"Pay-to Name")
            {
            }
            field("Pay-to Address";"Pay-to Address")
            {
            }
            field("Pay-to Address 2";"Pay-to Address 2")
            {
            }
            group(Control84)
            {
              field("Pay-to County";"Pay-to County")
              {
              }
            }
            field("Pay-to Post Code";"Pay-to Post Code")
            {
            }
            field("Pay-to City";"Pay-to City")
            {
            }
            field("Pay-to Country/Region Code";"Pay-to Country/Region Code")
            {
            }
            field("Pay-to Contact No.";"Pay-to Contact No.")
            {
            }
            field("Pay-to Contact";"Pay-to Contact")
            {
            }
          }
        }
      }
      group("Foreign Trade")
      {
        field("Transaction Specification";"Transaction Specification")
        {
        }
        field("Transport Method";"Transport Method")
        {
        }
        field("Entry Point";"Entry Point")
        {
        }
        field("Area";Area)
        {
        }
      }
    }
    area(FactBoxes)
    {
      part("Attached Documents";"Document Attachment Factbox")
      {
      }
      part(Control13;"Pending Approval FactBox")
      {
      }
      part(Control1901138007;"Vendor Details FactBox")
      {
      }
      part(Control1904651607;"Vendor Statistics FactBox")
      {
      }
      part(Control1903435607;"Vendor Hist. Buy-from FactBox")
      {
      }
      part(Control1906949207;"Vendor Hist. Pay-to FactBox")
      {
      }
      part(Control5;"Purchase Line FactBox")
      {
      }
      part(ApprovalFactBox;"Approval FactBox")
      {
      }
      part(IncomingDocAttachFactBox;"Incoming Doc. Attach. FactBox")
      {
      }
      part(WorkflowStatus;"Workflow Status FactBox")
      {
      }
      systempart(Control1900383207;RecordLinks)
      {
      }
      systempart(Control1905767507;Notes)
      {
      }
    }
  }
  actions
  {
    area(Navigation)
    {
      group("&Quote")
      {
        action(Statistics)
        {
        }
        action(Vendor)
        {
        }
        action("Co&mments")
        {
        }
        action(Dimensions)
        {
        }
        action(Approvals)
        {
        }
        action(DocAttach)
        {
        }
      }
    }
    area(Processing)
    {
      group(Approval)
      {
        action(Approve)
        {
        }
        action(Reject)
        {
        }
        action(Delegate)
        {
        }
        action(Comment)
        {
        }
      }
      group(Action92)
      {
        action(Print)
        {
        }
        action(Send)
        {
        }
      }
      group(Action3)
      {
        separator(Action148)
        {
        }
        action(Release)
        {
        }
        action(Reopen)
        {
        }
      }
      group("F&unctions")
      {
        action(CalculateInvoiceDiscount)
        {
        }
        separator(Action144)
        {
        }
        action("Get St&d. Vend. Purchase Codes")
        {
        }
        separator(Action146)
        {
        }
        action(CopyDocument)
        {
        }
        action("Archive Document")
        {
        }
        group(IncomingDocument)
        {
          action(IncomingDocCard)
          {
          }
          action(SelectIncomingDoc)
          {
          }
          action(IncomingDocAttachFile)
          {
          }
          action(RemoveIncomingDoc)
          {
          }
        }
      }
      group("Request Approval")
      {
        action(SendApprovalRequest)
        {
        }
        action(CancelApprovalRequest)
        {
        }
      }
      group("Make Order")
      {
        action(MakeOrder)
        {
        }
      }
    }
    area(Reporting)
    {
      action("Purchase Advice")
      {
      }
      action("Vendor/Item Catalog")
      {
      }
    }
  }
  var CopyPurchDoc: report "Copy Purchase Document";
  ApplicationAreaMgmtFacade: codeunit "Application Area Mgmt. Facade";
  DocPrint: codeunit "Document-Print";
  UserMgt: codeunit "User Setup Management";
  ArchiveManagement: codeunit ArchiveManagement;
  PurchCalcDiscByType: codeunit "Purch - Calc Disc. By Type";
  FormatAddress: codeunit "Format Address";
  ChangeExchangeRate: page "Change Exchange Rate";
  ShipToOptions: Option "Default (Company Address)", Location, "Custom Address";
  PayToOptions: Option "Default (Vendor)", "Another Vendor", "Custom Address";
  HasIncomingDocument: Boolean;
  DocNoVisible: Boolean;
  OpenApprovalEntriesExistForCurrUser: Boolean;
  OpenApprovalEntriesExist: Boolean;
  ShowWorkflowStatus: Boolean;
  CanCancelApprovalForRecord: Boolean;
  ShowShippingOptionsWithLocation: Boolean;
  IsBuyFromCountyVisible: Boolean;
  IsPayToCountyVisible: Boolean;
  IsShipToCountyVisible: Boolean;
}' not found to remove
Parameter name: trees[0]'
Details:
System.ArgumentException: SyntaxTree 'page 49 "Purchase Quote"
{
  layout
  {
    area(Content)
    {
      group(General)
      {
        field("No.";"No.")
        {
        }
        field("Buy-from Vendor No.";"Buy-from Vendor No.")
        {
        }
        field("Buy-from Vendor Name";"Buy-from Vendor Name")
        {
        }
        group("Buy-from")
        {
          field("Buy-from Address";"Buy-from Address")
          {
          }
          field("Buy-from Address 2";"Buy-from Address 2")
          {
          }
          group(Control79)
          {
            field("Buy-from County";"Buy-from County")
            {
            }
          }
          field("Buy-from Post Code";"Buy-from Post Code")
          {
          }
          field("Buy-from City";"Buy-from City")
          {
          }
          field("Buy-from Country/Region Code";"Buy-from Country/Region Code")
          {
          }
          field("Buy-from Contact No.";"Buy-from Contact No.")
          {
          }
        }
        field("Buy-from Contact";"Buy-from Contact")
        {
        }
        field("Document Date";"Document Date")
        {
        }
        field("Due Date";"Due Date")
        {
        }
        field("Order Date";"Order Date")
        {
        }
        field("No. of Archived Versions";"No. of Archived Versions")
        {
        }
        field("Requested Receipt Date";"Requested Receipt Date")
        {
        }
        field("Vendor Order No.";"Vendor Order No.")
        {
        }
        field("Vendor Shipment No.";"Vendor Shipment No.")
        {
        }
        field("Purchaser Code";"Purchaser Code")
        {
        }
        field("Campaign No.";"Campaign No.")
        {
        }
        field("Order Address Code";"Order Address Code")
        {
        }
        field("Responsibility Center";"Responsibility Center")
        {
        }
        field("Assigned User ID";"Assigned User ID")
        {
        }
        field(Status;Status)
        {
        }
      }
      part(PurchLines;"Purchase Quote Subform")
      {
      }
      group("Invoice Details")
      {
        field("Currency Code";"Currency Code")
        {
        }
        field("Expected Receipt Date";"Expected Receipt Date")
        {
        }
        field("Payment Terms Code";"Payment Terms Code")
        {
        }
        field("Payment Method Code";"Payment Method Code")
        {
        }
        field("Transaction Type";"Transaction Type")
        {
        }
        field("Shortcut Dimension 1 Code";"Shortcut Dimension 1 Code")
        {
        }
        field("Shortcut Dimension 2 Code";"Shortcut Dimension 2 Code")
        {
        }
        field("Payment Discount %";"Payment Discount %")
        {
        }
        field("Pmt. Discount Date";"Pmt. Discount Date")
        {
        }
        field("Shipment Method Code";"Shipment Method Code")
        {
        }
        field("Payment Reference";"Payment Reference")
        {
        }
        field("Creditor No.";"Creditor No.")
        {
        }
        field("On Hold";"On Hold")
        {
        }
        field("Tax Liable";"Tax Liable")
        {
        }
        field("Tax Area Code";"Tax Area Code")
        {
        }
      }
      group("Shipping and Payment")
      {
        group(Control45)
        {
          group(Control20)
          {
            field(ShippingOptionWithLocation;ShipToOptions)
            {
            }
            field(ShippingOptionWithoutLocation;ShipToOptions)
            {
            }
            group(Control57)
            {
              group(Control55)
              {
                field("Location Code";"Location Code")
                {
                }
              }
              field("Ship-to Name";"Ship-to Name")
              {
              }
              field("Ship-to Address";"Ship-to Address")
              {
              }
              field("Ship-to Address 2";"Ship-to Address 2")
              {
              }
              group(Control90)
              {
                field("Ship-to County";"Ship-to County")
                {
                }
              }
              field("Ship-to Post Code";"Ship-to Post Code")
              {
              }
              field("Ship-to City";"Ship-to City")
              {
              }
              field("Ship-to Country/Region Code";"Ship-to Country/Region Code")
              {
              }
              field("Ship-to Contact";"Ship-to Contact")
              {
              }
            }
          }
        }
        group(Control51)
        {
          field(PayToOptions;PayToOptions)
          {
          }
          group(Control67)
          {
            field("Pay-to Name";"Pay-to Name")
            {
            }
            field("Pay-to Address";"Pay-to Address")
            {
            }
            field("Pay-to Address 2";"Pay-to Address 2")
            {
            }
            group(Control84)
            {
              field("Pay-to County";"Pay-to County")
              {
              }
            }
            field("Pay-to Post Code";"Pay-to Post Code")
            {
            }
            field("Pay-to City";"Pay-to City")
            {
            }
            field("Pay-to Country/Region Code";"Pay-to Country/Region Code")
            {
            }
            field("Pay-to Contact No.";"Pay-to Contact No.")
            {
            }
            field("Pay-to Contact";"Pay-to Contact")
            {
            }
          }
        }
      }
      group("Foreign Trade")
      {
        field("Transaction Specification";"Transaction Specification")
        {
        }
        field("Transport Method";"Transport Method")
        {
        }
        field("Entry Point";"Entry Point")
        {
        }
        field("Area";Area)
        {
        }
      }
    }
    area(FactBoxes)
    {
      part("Attached Documents";"Document Attachment Factbox")
      {
      }
      part(Control13;"Pending Approval FactBox")
      {
      }
      part(Control1901138007;"Vendor Details FactBox")
      {
      }
      part(Control1904651607;"Vendor Statistics FactBox")
      {
      }
      part(Control1903435607;"Vendor Hist. Buy-from FactBox")
      {
      }
      part(Control1906949207;"Vendor Hist. Pay-to FactBox")
      {
      }
      part(Control5;"Purchase Line FactBox")
      {
      }
      part(ApprovalFactBox;"Approval FactBox")
      {
      }
      part(IncomingDocAttachFactBox;"Incoming Doc. Attach. FactBox")
      {
      }
      part(WorkflowStatus;"Workflow Status FactBox")
      {
      }
      systempart(Control1900383207;RecordLinks)
      {
      }
      systempart(Control1905767507;Notes)
      {
      }
    }
  }
  actions
  {
    area(Navigation)
    {
      group("&Quote")
      {
        action(Statistics)
        {
        }
        action(Vendor)
        {
        }
        action("Co&mments")
        {
        }
        action(Dimensions)
        {
        }
        action(Approvals)
        {
        }
        action(DocAttach)
        {
        }
      }
    }
    area(Processing)
    {
      group(Approval)
      {
        action(Approve)
        {
        }
        action(Reject)
        {
        }
        action(Delegate)
        {
        }
        action(Comment)
        {
        }
      }
      group(Action92)
      {
        action(Print)
        {
        }
        action(Send)
        {
        }
      }
      group(Action3)
      {
        separator(Action148)
        {
        }
        action(Release)
        {
        }
        action(Reopen)
        {
        }
      }
      group("F&unctions")
      {
        action(CalculateInvoiceDiscount)
        {
        }
        separator(Action144)
        {
        }
        action("Get St&d. Vend. Purchase Codes")
        {
        }
        separator(Action146)
        {
        }
        action(CopyDocument)
        {
        }
        action("Archive Document")
        {
        }
        group(IncomingDocument)
        {
          action(IncomingDocCard)
          {
          }
          action(SelectIncomingDoc)
          {
          }
          action(IncomingDocAttachFile)
          {
          }
          action(RemoveIncomingDoc)
          {
          }
        }
      }
      group("Request Approval")
      {
        action(SendApprovalRequest)
        {
        }
        action(CancelApprovalRequest)
        {
        }
      }
      group("Make Order")
      {
        action(MakeOrder)
        {
        }
      }
    }
    area(Reporting)
    {
      action("Purchase Advice")
      {
      }
      action("Vendor/Item Catalog")
      {
      }
    }
  }
  var CopyPurchDoc: report "Copy Purchase Document";
  ApplicationAreaMgmtFacade: codeunit "Application Area Mgmt. Facade";
  DocPrint: codeunit "Document-Print";
  UserMgt: codeunit "User Setup Management";
  ArchiveManagement: codeunit ArchiveManagement;
  PurchCalcDiscByType: codeunit "Purch - Calc Disc. By Type";
  FormatAddress: codeunit "Format Address";
  ChangeExchangeRate: page "Change Exchange Rate";
  ShipToOptions: Option "Default (Company Address)", Location, "Custom Address";
  PayToOptions: Option "Default (Vendor)", "Another Vendor", "Custom Address";
  HasIncomingDocument: Boolean;
  DocNoVisible: Boolean;
  OpenApprovalEntriesExistForCurrUser: Boolean;
  OpenApprovalEntriesExist: Boolean;
  ShowWorkflowStatus: Boolean;
  CanCancelApprovalForRecord: Boolean;
  ShowShippingOptionsWithLocation: Boolean;
  IsBuyFromCountyVisible: Boolean;
  IsPayToCountyVisible: Boolean;
  IsShipToCountyVisible: Boolean;
}' not found to remove
Parameter name: trees[0]
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.RemoveSyntaxTrees(IEnumerable`1 trees) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 355
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.FindSymbolInContent(ISymbol symbol, String content, Int32 lineOffset) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 201
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.FindDeclaration(ISymbol symbol, SourceContent sourceContent, String metadataContent) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 104
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.<TryGetDefinitionFromReference>d__8.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.<GetResponseForSymbol>d__5.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.<ProcessRequestAsync>d__4.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**Comment by qutreson** [comment]
@kavila02, please re-open an issue following the required template. Without more information about what you were doing (repro steps) and without the versions of the AL extension and Business Central that you are using, it is almost impossible for us to investigate your issue.
