### ISSUE TITLE
Cannot add documentation comments into created Functions

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#5298]
**Describe the bug**
I can't find a way to add a description comment of what it does a created function in VS Code

Do we have a way to add comment describing a function for our own created functions?

Like in NodeJS, there is a way to do that, and I saw that for primmitive functions you include a description like this:

![image](https://user-images.githubusercontent.com/3531482/65763136-fcec6800-e122-11e9-9eac-f4f0891441b2.png)

Waiting for your response.

Thanks so much in advance for your effort and all the work you do!

Best regards,

Jamal Bakach

**Comment by qutreson** [comment]
Hi @jbakach, this is not currently possible, but we have it on our backlog. We also have an issue already tracking it on Github #132.
