### ISSUE TITLE
How can i define global variables and trigger on a page

### ISSUE THREAD

**Issue by StefanHovenbitzer** [Microsoft/AL#53]
Hi everyone,
i checked the given examples to solve this problem described above. I only foud how to add global variables on a codeunit. If i try to go the same way on a page i get confusing error messages.
![grafik](https://cloud.githubusercontent.com/assets/24838311/21604936/4b57a87c-d1a6-11e6-8e5c-677d7d7ff65d.png)

Thanks for any help in advance.

**Comment by esbenk** [comment]
There is an order when defining the page. 

1. Page properties 
2. layout {} section
3. actions {} section
4. global vars, triggers, methods in no particular order.

**Comment by StefanHovenbitzer** [comment]
Nice to know. Thanks a lot especially for your fast answer.
Greetings.
