### ISSUE TITLE
Intellisense does not work when opening a folder with an UNC path.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#530]
I had an ongoing issue that intellisense did not work. 

I realized that if I moved the project folder to my local machine or mapped the folder as a
network drive, intellisense was working. I know that normally you would download a local repository
and everything would be swell, and that the network share mapping is a suitable workaround. However
still i think it should work.

I confirmed that it is also an issue with smaller projects such as the HelloWorld sample.

**Comment by StanislawStempin** [comment]
Thanks, we will look into it.
