### ISSUE TITLE
Codeunit 99000755 CalendarManagement missing

### ISSUE THREAD

**Issue by naveksa** [microsoft/AL#5302]
**Describe the bug**

In our Apps we are using functions from base codeunit 99000755 CalendarManagement.
Apparently this codeunit no longer exists in Fall 2019 Release.
We assume, that the functions have been moved to some other codeunit
(not 7600 Calendar Management, as we first thought).
Can anyone point at where to find the functions.

Error:
Codeunit 'CalendarManagement' is missing AL(AL0185)

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 
4.0.172584

 - Business Central:
Platform 15.0.36117.0 + Application 15.0.36145.0

**Comment by larswestman** [comment]
This is one of many breaking changes in BC15. Search for "Calendar" in this document: https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md

**Comment by naveksa** [comment]
Thanks.
Found it.
