### ISSUE TITLE
Rows getting duplicated when using External Sql as table type in Business Central

### ISSUE THREAD

**Issue by tjaitly1986** [microsoft/AL#5303]
I have used the External Table concept in table type while defining the new table in Business Central because I want to import the data from SQL Table and post it in Business Central. Connectivity is working fine, I can see the SQL table data in Business Central through the page but when I click on any row on the page to edit the record, it will duplicate the rows on the page.

However, when you refresh the page you still see the original number of records from Sql table, the only issue is duplication of rows which looks really weird visually.

**To Reproduce**
Steps and to reproduce the behavior:
1. Created a table with table type - "External Table", Table Name-"X" and Schema-"dbo".
2. Created the Page for displaying the table records.
3. Created the Code Unit for connecting to the SQL Server.
4. Executed the Code Unit from the page by referencing the Code Unit from init trigger.

**Expected behavior**
I want to edit the row and when I click on any row then I want it won't duplicate, it should behave normal like editing any other row on any other page in Business Central.

**Screenshots**
![image](https://user-images.githubusercontent.com/26621684/65807687-11883900-e1d3-11e9-8643-57201bdb103b.png)

![image](https://user-images.githubusercontent.com/26621684/65807696-1ea52800-e1d3-11e9-880f-b385ac551655.png)

![image](https://user-images.githubusercontent.com/26621684/65807707-295fbd00-e1d3-11e9-9d2e-73bcda86b88b.png)

![image](https://user-images.githubusercontent.com/26621684/65807807-b9056b80-e1d3-11e9-8f7b-ec8356f08697.png)

![image](https://user-images.githubusercontent.com/26621684/65807944-a2abdf80-e1d4-11e9-9b78-0980c4a3c362.png)

In above screenshot, there are only 4 original lines in the table but when clicked on a row (first or last), it duplicates the rows.

**Versions:**

 - AL Language:  **3.0.168744**

 - Business Central: **14.0.29530.0 + Application 29530**

**Comment by qutreson** [comment]
Hi @tjaitly1986, were you also able to reproduce this issue on our latest developer previews? (AL version 4.x and BC version 15.x)?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
