### ISSUE TITLE
Error: Could not connect to the server. Please verify that: 1. The server is started. 2. The development endpoint is enabled (DeveloperServicesEnabled server setting). 3. The service name matches the one specified in the URL. 4. The port number matches the one specified in the URL (DeveloperServicesPort server setting). 5. The protocol matches the one specified in the URL (DeveloperServicesSSLEnabled server setting), and that a trusted certificate is used in case of an SSL connection.

### ISSUE THREAD

**Issue by brucecotter** [microsoft/AL#5304]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by qutreson** [comment]
Hi @brucecotter, can you specify which version of the extension you are using, which version of BC you are targeting, but also whether you are in Cloud or OnPrem setup?

**Comment by atoader** [comment]
@brucecotter please follow the template we have provided, it helps us help you :)

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
