### ISSUE TITLE
Table No. and Protection Level AL0161

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/AL#5305]
**Describe the bug**
I'm having an issue with AL0161 'Table Name' is inaccessible due to its protection level.  I'm doing some stuff with RecordRef and I don't actually want to access the table, I just want to do something different if it is that table, since I can't access it.  So when I do DATABASE::"User Login", just so I know the table Number I get an error.  I feel like you should still be able to user DATABSE::"Table Name" without getting the error AL0161.  For now, I have to put in the actual Objects ID, which isn't the best in case a table is changed or deleted.

**To Reproduce**
Steps and to reproduce the behavior:
1. Add code with DATABASE::"User Login"

``` AL Code to reproduce the issue ```

**Expected behavior**
No error when using DATABASE::"Table Name".

**Screenshots**
![image](https://user-images.githubusercontent.com/32099690/65825963-16c8a080-e232-11e9-9da5-a5d673a06e02.png)

**5. Versions:**

 - AL Language: 4.0.176004

 - Business Central: 15.0.36510.0

**Comment by atoader** [comment]
@MatthewMcCarthy7 can you give us examples of a few other tables that exhibit this issue? I cannot reproduce the issue with the following snippet:
```
trigger OnAction()
begin 
  if 1 in [Database::"User Login"] then begin end;
end;
```

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by NavDeb** [comment]
I also have similar issue.  If we want to loop all tables to check for some data that we want to remove for example for data obfuscation purposes how can we skip tables that have a protection level of internal?
