### ISSUE TITLE
Evaluate Bigger then Integer size gives Error

### ISSUE THREAD

**Issue by ppvandermark** [microsoft/AL#5307]
**Describe the bug**
Evaluate(decValue, '999999999999999.99‬') doesn't work. and the documentation tells me that this should be the max value allowed.
![image](https://user-images.githubusercontent.com/50981177/65868736-256d9f80-e379-11e9-91b5-482852a20e0b.png)

**To Reproduce**
`

    [Test]
    procedure TestOn_TextMaxDecimal_ConversionFunctions();
    var
        decText: Text;
        decValueCorrect: BigInteger;
        decValue: Decimal;
    begin
        decValueCorrect := 999999999999999.99;
        decText := '999999999999999.99‬';

        Evaluate(decValue, decText);

        if not (decValue = decValueCorrect) then
            Error(StrSubstNo('The Text to Decimal was expecting an %1 as value got %2', decValueCorrect, decValue));

    end;

`

**Expected behavior**
No error

**5. Versions:**
 - AL Language: 
![image](https://user-images.githubusercontent.com/50981177/65869301-7a5de580-e37a-11e9-8935-69327b0fffef.png)

 - Business Central:
Platform 15.0.36117.0 + Application 15.0.36145.0

**Comment by qutreson** [comment]
We can now reproduce this issue based on the code provided above. The AL code compiles, but fails at runtime.

**Comment by jehelles** [comment]
As far as I can see, there are 2 issues with the listed sample code:
1. You cannot assign a decimal to a biginteger when the decimal contains a fractional value. That will give you an error similar to:
Overflow under conversion of Microsoft.Dynamics.Nav.Runtime.Decimal18 value 999999999999999.99 to System.Int64.
which is expected and correct as the .99 cannot be represented in an integer type.

2. Your code contains an invisible unicode character as part of the decText string. You can see this if you put the cursor at the end of the line and delete until you get to the first 9. When trying to delete that character, you instead delete the invisible unicode character.

I have tested the following code and it works fine:
```
[Test]
procedure TestOn_TextMaxDecimal_ConversionFunctions();
var
    decText: Text;
    decValueCorrect: Decimal;
    decValue: Decimal;
begin
    decValueCorrect := 999999999999999.99;
    decText := '999999999999999.99';

    Evaluate(decValue, decText);

    if not (decValue = decValueCorrect) then
        Error(StrSubstNo('The Text to Decimal was expecting an %1 as value got %2', decValueCorrect, decValue));
end;
```

**Comment by qutreson** [comment]
Closing this issue based on the previous comment.
