### ISSUE TITLE
Can't download system symbols - BC Spring Release

### ISSUE THREAD

**Issue by MatDDev** [microsoft/AL#5308]
**Describe the bug**
Cannot download the system symbols for Business Central Spring Release CU1. Database has been upgraded from NAV 2018 to BC

**Screenshots**
I did regenerate the symbols following:
https://docs.microsoft.com/pl-pl/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side

I did get navcommandresult with the success.
When trying to download the symbols, only application symbols are being downloaded
![1](https://user-images.githubusercontent.com/13900033/65871326-6f0cb900-e37e-11e9-8c84-a55c1d403452.png)

**5. Versions:**
 - AL Language: 3.0.168874
 - Business Central: 14.0.32600.0

Am I missing something here? I've been working with c/side and al running simultaneously for a couple of months already and I didn't have this problem. 

There is a license valid for BC 13.0.0.0, and I cannot use Get-NAVAppInfo to check which symbols are installed. Could that be the issue? 

Thanks

**Comment by qutreson** [comment]
@MatDDev, did you run [Get-NavAppInfo](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps-15) with `-SymbolsOnly`? This switch needs to be specified to verify if the application and system symbol packages are published on your NST.

Can it be that they have a version whose major is lower than 14 while your app.json requests for at least 14?

**Comment by MatDDev** [comment]
@qutreson 
Yes, with -SymbolsOnly and there was nothing. I am trying to solve this issue step by step and observations are as follows:
- On clean installation symbols are still there
- When I uninstall the standard extensions (needed for LS objects), the symbols are still there
- However when the LS objects are being imported, the symbols are gone (I need to investigate this one)

**Comment by qutreson** [comment]
Are you importing the objects as C/AL through C/SIDE or importing everything directly as a bacpac?

In the first case, you should publish the system symbols provided by Microsoft and then generate the application symbols for it from C/SIDE see [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side).

In the second case, it looks like the bacpac does not contain symbol which should have been generated before exporting it. Same thing, system symbols should be published and the application symbols should be generated from C/SIDE.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
