### ISSUE TITLE
QR Code Printing

### ISSUE THREAD

**Issue by sanjeevasawale** [Microsoft/AL#531]
Is it possible to print QR Code in Report? Since dll cannot be used is there any way to print QR Code in Report.

**Comment by StanislawStempin** [comment]
Assuming that you used a DLL to create the QR Code, that DLL would most likely need to be created in an external service (we recommend Azure Functions) and transferred back to AL through a REST API call using the new AL types for HTTP* and JSON*.

Please check the FAQ for more details about .NET replacement options:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
