### ISSUE TITLE
Linked Objects in AL

### ISSUE THREAD

**Issue by RobbieRoss** [microsoft/AL#5310]
**Describe the bug**
When creating/running a table in an AL extension with the LinkedObject property set to true no records are being displayed.  The view runs correctly from SQL.  If the linked table is created in C/AL the records are displayed.  I believe this is because a physical table is being created when the new table is published from AL.

**To Reproduce**
Steps and to reproduce the behavior:
1. From a browser run the new table.  Eg,
http://localhost:8080/BC140/?company=CRONUS%20LS%201401%20W1%20Demo&table=50011

No records from the linked table are displayed when you run the table.

``` AL Code to reproduce the issue ```
1. In SQL Server Management Studio create a SQL View and save it as Customer Balance View
SELECT        c.No_, cb.Balance
FROM            dbo.[CRONUS LS 1401 W1 Demo$Customer] AS c INNER JOIN
                         [OldSQLSystem].dbo.[Customer Balance View] AS cb ON c.No_ = cb.No_

2. In AL create a new table object, set the LinkedObject property to true and DataPerCompany to false with a name of Customer Balance View.
 ![image](https://user-images.githubusercontent.com/55992766/65895671-bd807e80-e3a3-11e9-907f-30fbdfcb7096.png)

3. Publish the extension

**Expected behavior**
1. From a browser run the new table.  Eg,
http://localhost:8080/BC140/?company=CRONUS%20LS%201401%20W1%20Demo&table=50011

Records from the linked table should be displayed when you run the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/55992766/65896629-7a270f80-e3a5-11e9-9022-5494ca649e5e.png)

**5. Versions:**

 - AL Language:
![image](https://user-images.githubusercontent.com/55992766/65896592-64194f00-e3a5-11e9-9477-c95c163bf6a6.png)

 - Business Central:
![image](https://user-images.githubusercontent.com/55992766/65896548-4fd55200-e3a5-11e9-919c-4dfa1c9764b7.png)

**Comment by atoader** [comment]
Hi @RobbieRoss ! Does this reproduce on the Wave 2 2019 release?

**Comment by RobbieRoss** [comment]
This was on Wave 2 2019/10

![image](https://user-images.githubusercontent.com/55992766/66110702-3a3b7480-e5bf-11e9-801b-83634062d75f.png)

Thanks,
Robbie

**Comment by kalberes** [comment]
Possible bug, need more investigation.

**Comment by KristofKlein** [comment]
I assume you have a similar problem than I have...the View that you are using is called [Customer Balance View] ? this will not work with linked Object any longer....for some "strange" reason you can see in the debugger on the SQL trace within VS Code that it will query a view called [Customer Balance View$YOURAPPID] ... I think this is wrong and should be changed by MS as the linked object maybe something that you have no control about at all...it does not belong to the App .... why you have the table called like that I don't get...could it be that you have published the app without setting linked object before you switched it?

**Comment by RobbieRoss** [comment]
The issue is that a physical SQL table is created called [Customer Balance View$YOURAPPID] when creating the linked object using AL.  A physical table shouldn't be created, the linked object should just point to the existing named object, which in my case is a View in my SQL database.

Creating a Linked Object in C/AL works fine in the same version.

**Comment by IvoMol** [comment]
We are using T-SQL workaround:
CREATE VIEW [dbo].[Customer Balace View] AS SELECT * FROM [dbo].[Customer Balance View$YOURAPPID]
Linked table is joined to view (not to table) and works as expected.

**Comment by KristofKlein** [comment]
> We are using T-SQL workaround:
that is a no go for me :) i need to tell BC the SQL Name that it has to use ... no workaround allowed! 
it is not allowed to just add in the SQL Statement the APPID to the linked object... assume two extensions (like App and Test....) you have the View twice due to two App IDs?!

**Comment by IvoMol** [comment]
Second application (Test) works with first application (App). You should create SQL view only for application which creates SQL table.
But you are true - this workaround needs access to SQL.

Are we traying TableType = ExternalSQL instead of LinkedObject = true? Works fine from BC (without any next SQL hint).

**Comment by KristofKlein** [comment]
> Second application (Test) works with first application (App). You should create SQL view only for application which creates SQL table.

got me there ;) never considered ExternalSQL....
