### ISSUE TITLE
AppSource:  AppTest with input external file/data

### ISSUE THREAD

**Issue by giann85** [microsoft/AL#5311]
Hi, I developed an app for AppSource. In the test app would go to test file import and export features. I have not found any way to insert in the test app, the external files that are used to simulate the functionality of the app itself.
Let me explain: I need to import a text file with some data, which must be read and written in tables. In the test app how can I simulate this feature?

Thanks

**Comment by atoader** [comment]
Hi, @giann85 this is a problem that is highly tied to the architecture of your application and we cannot really advise you on this here. My advice is to post this question on one of the following forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
