### ISSUE TITLE
Using OCX Datatype in A/L

### ISSUE THREAD

**Issue by lakmalrhm** [microsoft/AL#5314]
**Describe the bug**
In NAV C/AL side there is a data type OCX. when i convert object in to AL there is no data type OCX. I need to use the Microsoft Communications Control, version 6.0. This is regrading getting the data from weighbridge. is there any solution or workaround?

**To Reproduce**

**Expected behavior**

**Screenshots**
![OCX](https://user-images.githubusercontent.com/6760775/66031221-8c37b800-e535-11e9-835c-442c4cabee2c.JPG)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by qutreson** [comment]
Hi @lakmalrhm, I think what you are looking for is .Net Interoperability in AL, you can read more about it here: [Getting started with Microsoft .NET Interoperability from AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al).

Did you get this by using the [txt2al conversion tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)?

**Comment by atoader** [comment]
@lakmalrhm that seems to be Automation interop which has been deprecated for multiple years. You need to rewrite the code. If you are planning to distribute your extension in our SaaS product, you should rely on AL builtin functions or external services. If you are only planning to distribute your extension OnPrem, you can use .NET interop.

**Comment by lakmalrhm** [comment]
@qutreson Yes , from txt2al tool. Is it possible to use DotNet variable in NAV 2018 extension?

**Comment by lakmalrhm** [comment]
@atoader , sorry i forgot to mention the Version. i am trying to create application in AL 0.13.91787 for NAV 2018. target = Internal. Using DotNot for NAV 2018 is possible? or should i do C/AL ,AL side by side?

**Comment by atoader** [comment]
@lakmalrhm on versions older than the 2018 Fall Release, you should use C/AL and AL side by side. Your best option is to code the functionality that uses .NET interop in C/AL and expose a wrapper that can be called from AL.
