### ISSUE TITLE
Debugger doesn't work well

### ISSUE THREAD

**Issue by TakayukiIso** [microsoft/AL#5317]
**Describe the bug**
From October 2, when I try to debug my extention at SaaS sandbox enviromet, process stops at break-point but although  I pushed Cotinue/SteoOver/StepInto/Stepout in VSCode, on the BC screen "processing" is displayed and processing does not proceed.

**To Reproduce**
Steps and to reproduce the behavior:
1. set a break-point on my entention code
2. cmd "AL: Publish and debug" at VSCode
3. push my extention's button at BC sandbox 
4. push Cotinue/SteoOver/StepInto/Stepout  button in VS Code debugger
``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.182565

 - Business Central:14.5.35970.0

**Comment by kalberes** [comment]
Does this always repro?

If yes, can you tell us your tenant Id and the exact time you have tried to debug and the client has not responded to a  continue call.

**Comment by TakayukiIso** [comment]
Hi kalberes,
Thank you for your reply.

I tried it again, but it didn't work.

Details is 
tenatid: 491790b8-7bb1-4e66-a910-ea814a67dad4
from: 09:45:51(UTC)   to: 09:46:43(UTC)

Thanks.

**Comment by TakayukiIso** [comment]
Hi, thank fou your investigation.

I need a workaround because it hinders my development tasks till my sandbox is updated.
If the server and AL version mismatch is the reason, I wonder if there is no problem with the old AL version, but they were the same though I tried the following older AL versions.
3.0.168874
3.0.152816
Details: from  06:58:00(UTC)  to 06:58:00(UTC)

Is there no workaround...?

**Comment by kalberes** [comment]
Ok, for those it should work. In principle even 4.0 should be able to debug against 14.x. 
It is very hard to tell you what went wrong. I do not have enough data from the logs. IS breakOnerror set to true. maybe try with breakonreadwrite too.
I have not seen anything special in the logs. Like you deadlock the Azure SQL server, or similar.

**Comment by TakayukiIso** [comment]
Hi,
I haven't taken any measures, but the debugger started to work normally from this morning.
I wonder  it was a temporary server or client issue.
Thanks
