### ISSUE TITLE
Chnage ServicesLanguage on the BC Oncloud

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#5319]
Is there any possibility to switch ServicesLanguage = 'en-US' to any other for BC onCloud? Can't find any documentation regarding that...

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
