### ISSUE TITLE
This method is obsolete. Call the other CreateMessage instead.'

### ISSUE THREAD

**Issue by Charan-D365** [microsoft/AL#5322]
![Capture](https://user-images.githubusercontent.com/54058714/66199163-f36c7e00-e695-11e9-8653-5906350326a3.PNG)
How do i call the other CreateMessage Function both have the same names, one marked as obsolete? 

 [Obsolete('This method is obsolete. Call the other CreateMessage instead.')]
    [TryFunction]
    **procedure CreateMessage**(FromName: Text; FromAddress: Text; Recipient: Text; Subject: Text; Body: Text; HtmlFormatted: Boolean)
    var
        Recipients: List of [Text];
    begin
        Recipients.Add(Recipient);
        CreateMessage(FromName, FromAddress, Recipients, Subject, Body);
    end;

    /// <summary>
    /// Creates the email with the name and address it is being sent from, the recipients, subject, and body.
    /// </summary>
    /// <param name="FromName">The name of the email sender</param>
    /// <param name="FromAddress">The address of the default sender or, when using the Send As or Send on Behalf functionality, the address of the substitute sender</param>
    /// <param name="Recipients">The recipient(s) of the mail</param>
    /// <param name="Subject">The subject of the mail</param>
    /// <param name="Body">The body of the mail</param>
    [TryFunction]
    **procedure CreateMessage**(FromName: Text; FromAddress: Text; Recipients: List of [Text]; Subject: Text; Body: Text)
    var
        MailboxAddress: DotNet MimeMailboxAddress;
    begin

**Comment by JoelJame5** [comment]
@Charan-D365 call the other function with the different parameters. 

Obsolete function parameters were 
`procedure CreateMessage(FromName: Text; FromAddress: Text; Recipient: Text; Subject: Text; Body: Text; HtmlFormatted: Boolean)`

Replacement function parameters are: 
`procedure CreateMessage(FromName: Text; FromAddress: Text; Recipients: List of [Text]; Subject: Text; Body: Text)`
