### ISSUE TITLE
Job Queue Entry Key fields not in key

### ISSUE THREAD

**Issue by AronChaan** [microsoft/AL#5323]
**Describe the bug**
The AL compiler interprets the lack of a key on the Job Queue Entry table as a notification/warning when setting filters on said tables fields.

**To Reproduce**
Write a simple codeunit like:

```
    local procedure IsJobQueueEntryDelayed(ParameterString: Text): Boolean
    var
        JobQueueEntry: Record "Job Queue Entry";
    begin
        JobQueueEntry.Reset();
        JobQueueEntry.SetRange("Object Type to Run", JobQueueEntry."Object Type to Run"::Codeunit);
        JobQueueEntry.SetRange("Object ID to Run", CODEUNIT::"<codeunit name>");
        JobQueueEntry.SetRange("Parameter String", ParameterString);
        JobQueueEntry.SetRange(Status, JobQueueEntry.Status::Ready, JobQueueEntry.Status::"In Process");
        JobQueueEntry.FindFirst();
        if CurrentDateTime() > JobQueueEntry."Earliest Start Date/Time" + 3 then
            exit(true)
        else
            exit(false);
    end;
```

``` AL Code to reproduce the issue ```

**Expected behavior**
The compiler should not warn against unavoidable issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/16116105/66200484-39cfd600-e6b2-11e9-8e24-fa195f27e0bd.png)

**5. Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/16116105/66200586-83202580-e6b2-11e9-8a87-0f8fd9227199.png)

 - Business Central:
![image](https://user-images.githubusercontent.com/16116105/66200705-b8c50e80-e6b2-11e9-9424-8f4101647ffc.png)

**Comment by qutreson** [comment]
Hi @AronChaan, thank you for reporting this issue! As we already have an issue tracking it (#5276), I will close this one as a duplicate, but feel free to contribute to the discussion on the issue that linked.
