### ISSUE TITLE
Paste Record variables gives error

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/AL#5324]
**Describe the bug**
Copy n paste declared record variables from one procedure to another, make the inserted variable gives an error "Table "xx" is missing".
Deleting the table name and use intellisense to insert the exact same - will fix the error.

**To Reproduce**
Copy variable from one procedure to the next.
Use a spaced variable i.e. "name here and here" 

``` AL Code to reproduce the issue ```

**Expected behavior**
I expected no errors

**Screenshots**

**5. Versions:**
 - AL Language: 
4.0.182565

 - Business Central:
Version: Platform 14.0.32600.35571 + Application 35597 (W1 14.1)

**Comment by qutreson** [comment]
Hi @JSebastianN, we tried reproducing the issue based on what you described, but couldn't reproduce it. Can you try to update this issue with more detailed repro steps? Are you using a workspace with multiple projects/extensions open? A gif recording of the issue could help as well.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by NzureAdmin** [comment]
> This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

Im sorry for the late reply.
I have not been able to reproduce lately either.
