### ISSUE TITLE
how to add 'control add in' in report ?

### ISSUE THREAD

**Issue by jyotivarade** [microsoft/AL#5325]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by qutreson** [comment]
Hi @jyotivarade, in order for you to get started on control add-ins in AL, you can have a look at the following documentation [Control Add-In Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object). In order to add it to a report, you have to declare the control add-in in the `layout` section of the `requestpage` of your report. See more about reports here, [Report Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object).

**Comment by jyotivarade** [comment]
pageextension 50106 SalesInvoice extends "Posted Sales Invoice"
{
    layout
    {
addafter("Shipping and Billing")
        {
            part(map; GoogleMapCardCustomer)
            {
                Caption = 'Google map';
                ApplicationArea = all;
                // SubPageLink = "No." = field("Bill-to Customer No.");
                SubPageLink = "No." = field("No.");

            }
        }
}

page 50114 GoogleMapCardCustomer
{
    PageType = CardPart;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Sales Invoice Header";
    layout
    {
        area(Content)
        {
            usercontrol("Google Map"; GoogleMapControlAddIn)
            {
                ApplicationArea = All;
                trigger ContorlAddInReady()
                begin
                    ControlIsready := true;
                    showAddress();
                end;
            }
            usercontrol("Google Direction"; RouteDirection)
            {
                ApplicationArea = All;
                trigger ContorlAddInReady()
                begin
                    ControlIsready := true;
                    showAddress();
                end;
            }
        }
    }
    trigger OnAfterGetRecord()
    begin
        showAddress();
    end;

    local procedure showAddress()
    var
    begin
        if not ControlIsready then
            exit;
        ShipperAddress := Rec."Sell-from Address";
        if Rec."Sell-from City" <> '' then begin
            ShipperAddress += ',' + rec."Sell-from City";
        end;
        if Rec."sell-from County" <> '' then begin
            ShipperAddress += ',' + rec."sell-from County";
        end;
        if Rec."Sell-from Post Code" <> '' then begin
            ShipperAddress += ',' + Rec."Sell-from Post Code";
        end;
        if Rec."Sell-from Country/Region Code" <> '' then begin
            ShipperAddress += ',' + Rec."Sell-from Country/Region Code";
        end;


        ReceiverAddress := Rec."Sell-to Address";
        if Rec."Sell-to City" <> '' then begin
            ReceiverAddress += ',' + rec."Sell-to City";
        end;
        if Rec."sell-to County" <> '' then begin
            ReceiverAddress += ',' + rec."sell-to County";
        end;
        if Rec."Sell-to Post Code" <> '' then begin
            ReceiverAddress += ',' + Rec."Sell-to Post Code";
        end;
        if Rec."Sell-to Country/Region Code" <> '' then begin
            ReceiverAddress += ',' + Rec."Sell-to Country/Region Code";
        end;
        CurrPage."Google Map".ShowAddress(ShipperAddress, ReceiverAddress);
        CurrPage."Google Direction".ShowAddress(ShipperAddress, ReceiverAddress);
    end;

    var
        ControlIsready: Boolean;
        ShipperAddress: Text;
        ReceiverAddress: Text;
}
In POSTED SALES INVOICE i am able see map but i want to show this map and direction in report .  how to show this map and direction in report.

![image](https://user-images.githubusercontent.com/50901499/66295575-4dc14500-e909-11e9-9a4b-96dd74fdf628.png)

**Comment by qutreson** [comment]
@jyotivarade, this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
