### ISSUE TITLE
Saas: BC 15 Sandbox - Could not download symbols..

### ISSUE THREAD

**Issue by auzhhv** [microsoft/AL#5326]
Hi.

I'm not able to download symbols from Sandbox with BC 15 in Saas.
![image](https://user-images.githubusercontent.com/46031720/66292036-92d28080-e8e3-11e9-82a5-2f2ff031a433.png)
![image](https://user-images.githubusercontent.com/46031720/66292057-a4b42380-e8e3-11e9-8db4-65c779ccbbc0.png)

I'm able to get the System app, but not the Application app.
![image](https://user-images.githubusercontent.com/46031720/66290722-43d71c00-e8e0-11e9-97ac-cc56142aea31.png)

I have tried to create a new sandbox, but still same issue.

Also tried clearing credentials.

When I now create a Sandbox as a copy of Production with BC 14, I also get "Could not download symbols".
![image](https://user-images.githubusercontent.com/46031720/66291941-50a93f00-e8e3-11e9-8578-93acff804bbd.png)
![image](https://user-images.githubusercontent.com/46031720/66291995-75051b80-e8e3-11e9-9ac7-1ee4b2750b78.png)

I also get this error when creating sandbox with the name Sandbox:
![image](https://user-images.githubusercontent.com/46031720/66291051-19d22980-e8e1-11e9-9458-ef5acfcea6a8.png)
But I do have not any sandboxes with that name, and I dont't know if this is a related issue.
After a while a Sandbox with name "Sandbox" with BC 15 appeared. This was after I created the two other sandboxes.

**Comment by qutreson** [comment]
Hi @auzhhv, when using previews from BC version 15.x, the base application has been converted from C/AL to AL. This means that the Base Application now behaves like any other extensions.

In order to take a dependency on it, you now have to specify it as follows:

```
"dependencies": [
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ]
```

instead of `"application": "14.0.0.0"`

Using `application` now only works with the runtime versions 3.x and 4.x.

**Comment by auzhhv** [comment]
Thank you. That seems to work :)
