### ISSUE TITLE
AL Language CPU Usage on save

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5327]
Hi
I've just found out that when I save a document, even thou it has only a line modified, the AL Language extension use at least 20% of CPU resources. 
Can it be improved? 
Thanks

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.182565
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: 140 CU04

**Comment by atoader** [comment]
@stefanoPrimo how large is your solution? Do you have code lens turned off? Do you have code analysis disabled?

**Comment by stefanoPrimo** [comment]
My solution has 60 objects in total. 
I have code analysis enabled (PerTenantExtensionCop, CodeCop, UICop)
Code Action enabled
code lens enabled.

Of course, the combination of all use a bit of CPU but I think that it is the minimum requirement for having a great developing experience.

**Comment by atoader** [comment]
@stefanoPrimo do you experience the same behavior if you disable the code analysis? It might be that one of the tens of rules in the cops is not as efficient as it could be. The only way to find this out is by profiling the compiler under similar conditions. Can you provide any sample code that reproduces this?
