### ISSUE TITLE
Error: The request failed with code 422

### ISSUE THREAD

**Issue by pedperpat** [Microsoft/AL#533]
Hi, visual studio code fails when I want to publish a extension and it prompts me the following;

> An item with the same key has been added. <

I know that is problem of changing the id from app.json, changing the version,etc...

But I changed all the parameters above, I delete the package and hit Ctrl+Shift+B and then F5 to publish and the error occurs all the time.

**Comment by StanislawStempin** [comment]
Hi, could you please go to Event Viewer for the NAV Server and paste the full stack trace here?

**Comment by pedperpat** [comment]
Nah, just fixed. As I was unable to download symbols, I was extending from a table that I created at .al file. Now with symbols downloaded this problem doesn't happen.

Sorry for the misunderstanding.
