### ISSUE TITLE
How to upload dev license to Business Central Online and on Prem

### ISSUE THREAD

**Issue by adrianordonez** [microsoft/AL#5332]
Hello 

i got my dev license and with it my own ids but when i update my objects ids i got the following error
error AL0297: The application object identifier '70375845' is not valid. It must be within the allowed ranges '[50100..50149]'.

**Comment by qutreson** [comment]
@adrianordonez, you need to update the idRange in your app.json to reflect the ID range that was assigned to you in your developer's license (see [our online documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Appjson)).

**Comment by adrianordonez** [comment]
For Sandbox eviroment i have no problem, in my app.json i have the correct id range but when i want to install in Production enviroment i got an error for each object, example:

(1,24): error PTE0001: PageExtension 'GRWPostSalesInvcSubForm_CFDI33' has an ID of [70375904]. It must be between 50000 and 99999.
(1,15): error PTE0001: Page 'GRWCFDICertificate' has an ID of [70375905]. It must be between 50000 and 99999.
(1,15): error PTE0001: Page 'GRWCFDIEntry' has an ID of [70375906]. It must be between 50000 and 99999.
(1,19): error PTE0001: Codeunit 'GRWXmlHandler' has an ID of [70375881]. It must be between 50000 and 99999.
(1,19): error PTE0001: Codeunit 'GRWSATUtility' has an ID of [70375882]. It must be between 50000 and 99999.

**Comment by qutreson** [comment]
Are you getting this error when compiling your extension in VS Code or when trying to publish it?

**Comment by qutreson** [comment]
The system is behaving as expected, when trying to publish a PTE extension you should use object IDs from the range 50 000 to 99 999.

**Comment by rdebath** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

http://www.waldo.be/2018/03/26/enable-the-updated-code-analysis-for-al/

There are several "errors" that the `$COP` programs generate that are either a matter of opinion or just plain wrong. The above feature lets you either disable them or downgrade them to "Info messages".

PTE0001 and PTE0002 are top of my list of worthless errors.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by mhenricus** [comment]
So, does this mean that it is not possible to publish an app with object id is the 7 million to a SaaS Sandbox?
Would be nice to be able to do this to test the app, without having to renumber the object en field id's.
