### ISSUE TITLE
Regex Match no longer available?

### ISSUE THREAD

**Issue by LoanVision** [microsoft/AL#5333]
Hello,
previously in Type Helper codeunit we had Regex Match functionality. Was it moved somewhere or it was just removed?

Thank You!

**Comment by qutreson** [comment]
@LoanVision, did you have a look at the ALAppExtensions repository? There is there a list of the breaking changes that were introduced and of how to fix them: [BREAKINGCHANGES](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md). If you cannot find what you need in the list, they are also providing some guidelines about what to do next [here](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#cant-find-what-youre-looking-for).

Closing this issue as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central.
