### ISSUE TITLE
Extension creates records in new table but no visibility! (in sandbox)

### ISSUE THREAD

**Issue by navaddict** [microsoft/AL#5339]
**Describe the bug**
I have created a new table which stores records per Vendor and also a page for the table.  However, no records are visible even though I know they have been created (checked in the browser with Ctrl+Alt+F1 and can see the new record has the correct data)

**To Reproduce**
1. Create a new table and page 
2. Create table and page extensions for the Vendor adding a new boolean field
3. Add code to OnValidate of the new field so when set 'true' it creates a new record in the new table that was added in step 1.
4. Add an Action to the Vendor page extension to run the new page (for the new table).
5. Hit F5 in VS Code and once loaded select a Vendor record, set the boolean 'true' then click on the new Action - result: no record displayed!

**Expected behavior**
I expect to see the record that was just created as I can when I use Ctrl+Alt+F1 and click 'Table Fields'

**Screenshots**

**5. Versions:**
14.0.0.0

I'm hoping this isn't by design & a limitation of the Sandbox? :O

**Comment by qutreson** [comment]
Hi @navaddict, did you set the application area property on your page controls?

**Comment by navaddict** [comment]
Argh!  It turns out that I'd put them everywhere but that page .. thanks **very much** for that!!

I wish the MS Base App would default ApplicationArea = All; if it isn't specified (as it does with Visible, Editable etc) as it's going to catch everyone out at some point!
