### ISSUE TITLE
inaccessible due to its protection level

### ISSUE THREAD

**Issue by manishratan** [microsoft/AL#5342]
Platform:  Dynamics 365 Business Central. 
Version :   US Business Central 14.3

Code:
```
pageextension 50999 MyExtensionPage51999 extends "Sales Order"
{
    layout
    {

        modify(ShippingOptions)
        {
            ApplicationArea = all;

            trigger OnAfterValidate()
            begin
                if ShipToOptions = ShipToOptions::"Custom Address" then;
            end;
        }
    }
}
```

Error: error AL0161: 'ShipToOptions' is inaccessible due to its protection level
![e](https://user-images.githubusercontent.com/45168210/66556087-426e5380-eb6d-11e9-8bbb-7806733f24ad.png)

**Comment by thpeder** [comment]
Hi @manishratan, 

You are trying to access a global variable which can only be accessed within the page itself or if the variables are marked with protected then within page extensions.
This is by design.

**Comment by thpeder** [comment]
The "Sales order" page needs to be updated to expose the global variables. If you need it then raise a issue on [microsoft/ALAppExtensions](https://github.com/microsoft).
For seeing the protection level, the default is that it is only accessible from within the page itself, and "Go to definition" doesn't show the access levels  at the moment either, so it can be a bit hard to discover, but the error message you got is exactly for this case.
