### ISSUE TITLE
Upgrading from Dynamics 365 Business Central 2019 April Release unmodified application to Dynamics 365 Business Central 2019 Release Wave french localisation

### ISSUE THREAD

**Issue by chaouachi-ayoub** [microsoft/AL#5346]
Hello,
when Upgrading from Dynamics 365 Business Central 2019 April Release unmodified application to Dynamics 365 Business Central 2019 Release Wave 2 french localisation
I have the issue when i try to excute this code with powershell

There is already an object named '**** $ Prod_Line Order Routing' $ 437dbf0e-84ff-417a-965d-ed2bb9650972 $ VSIFT $ Key5 'in the database.

when i try to excute this code with powershell
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Application" -Version 15.0.36560.36649
My reference : 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application

**Comment by chaouachi-ayoub** [comment]
I have the same issue when I try to upgrade a demo database

 https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application

**Comment by AskeHolst** [comment]
From the [docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application):
**Prerequisite**
Upgrade to the latest Business Central Spring 2019 Cumulative Update (version 14).

**Comment by chaouachi-ayoub** [comment]
Hello, I upgraded to the latest cumulative update 14.5 the database ,and now i have another issue

Type: System.InvalidOperationException Message: Table OAuth 2.0 Setup ::  Unsupported field change. Field:Access Token Due DateTime; Change:Remove  
when trying 
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Application" -Version 15.0.36560.36649

**Comment by stevenoruzi** [comment]
there is a change, a column has been removed on the new version. you should use 
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Application" -Version 15.0.36560.36649 -Mode ForceSync

**Comment by qutreson** [comment]
Hi @chaouachi-ayoub, this behavior is by-design as we do not allow destructive table changes with the default synchronization mode. You can either use -Mode ForceSync as suggested or you should consider re-introducing the element removed with the property ObsoleteState set to Removed. For more information, you can read #1499
