### ISSUE TITLE
Calculation of translation key

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#5349]
Inspired by my issue #5192 (at the bottom end) and @qutreson:
The generated .xlf language files correspond to the extension names (e.g. tableextension50105). 
If we want to reorganize/rename the extension objects we need to recalculate the `<trans-unit id>`.
But how?

```
<trans-unit id="TableExtension 3470817506 - Field 1644257177 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
  <source>Belongs to Operation No.</source>
  <target>Gehört zu Arbeitsgangnr.</target>
  <note from="Developer" annotates="general" priority="2"></note>
  <note from="Xliff Generator" annotates="general" priority="3">TableExtension tableextension50105 - Field Belongs to Operation No. - Property Caption</note>
</trans-unit>
```

**Comment by thpeder** [comment]
Hi @ralf-escher, 
There currently is no easy way of doing it. You need to do your renaming in AL, build the project, and find the new translation id in the generated translation file (*.g.xlf) and update in your translation files all the translations with the new id.
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by ralf-escher** [comment]
Thanks for your fast reply!
I guess the easiest approachfor us would be to program some kind of routine which is going to update the translation id's in our language files.
