### ISSUE TITLE
SetFilter with pipe on Enum field yields empty dataset

### ISSUE THREAD

**Issue by DragonMrak** [microsoft/AL#5351]
**Describe the bug**
When using SetFilter(Field, FilterExpression) on the field of type Enum while FilterExpression contains several Enum values separated with pipe, it won't yield any results even if it should be.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create new AL project
2. Create Enum object for testing:
```AL
enum 50000 MyEnum
{
    value(1; TestValue1) { }
    value(2; TestValue2) { }
    value(3; TestValue3) { }
    value(4; TestValue4) { }
}
```
3. Create list table for tests:
```AL
table 50000 MyTable
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Primary Key"; Integer) { DataClassification = CustomerContent; AutoIncrement = true;}
        field(10; "Description"; Text[250]) { DataClassification = CustomerContent; }
        field(11; "Test Enum"; Enum MyEnum) { DataClassification = CustomerContent; }
    }

    keys
    {
        key(PK; "Primary Key") { Clustered = true; }
    }
}
```
4. Create test page:
```AL
page 50000 MyTestPage
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = MyTable;
    Caption = 'Test List';

    layout
    {
        area(Content)
        {
            repeater(Group)
            {
                field("Primary Key"; "Primary Key") { ApplicationArea = All; }
                field(Description; Description) { ApplicationArea = All; }
                field("Test Enum"; "Test Enum") { ApplicationArea = All; }
            }
        }
    }
}
```
5. Run project and enter some records with different enum values

``` AL Code to reproduce the issue ```
```AL
procedure DoesntWorkAsExpected()
var
    MyTable: Record MyTable;
    MyTestPage: Page MyTestPage;
begin
    MyTable.Reset();
    MyTable.SetFilter("Test Enum", 'TestValue1|TestValue3');
    MyTestPage.SetTableView(MyTable);
    MyTestPage.RunModal(); //Displays empty list
end;
```

**Expected behavior**
//The following code FOR SOME REASON works as expected:
```AL
procedure ActuallyWorksAsExpected()
var
    MyTable: Record MyTable;
    MyTestPage: Page MyTestPage;
    MyEnum: Enum MyEnum;
begin
    MyTable.Reset();
    MyTable.SetFilter("Test Enum", '%1|%2', MyEnum::TestValue1, MyEnum::TestValue3);
    MyTestPage.SetTableView(MyTable);
    MyTestPage.RunModal(); //Displays empty list
    Message(MyTable.GetFilter("Test Enum")); //Returns TestValue1|TestValue3
end;
```

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.176004

 - Business Central: Platform 15.0.36510.0 + Application 15.0.36649.0

**Comment by thpeder** [comment]
Hi @DragonMrak, 

Thanks for reporting the issue!
I just tried reproducing the issue using your code, but in both cases the page that opens have entries for the enum values. However I have a slightly newer build than you, so you might just have to wait for next update.
In the meantime, you can give it a try on the latest developer preview to verify too that the issue is resolved, or open a new issue if that is not the case.
