### ISSUE TITLE
Rename Symbol is now working right on field names with spaces

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#5352]
Working with AL Language extension 4.0.182565

Wanting to name a field the _Rename Symbol_ (F2) was not doing what it should do when the field name contains spaces. Two scenarios:

1. Selecting the field with spaces (not including the quotes), f.e. _Qty. per Day,_ and pressing F2 will only show the last part of the field name in the editable dropdown textbox, i.e. _Day_. Adding a suffix _ASD_ to Day will now rename the field name and its references to "Day ASD". **Workaround**: retype the original field name and add suffix to it, which is quite a nuissance.

1. Selecting the field name including quotes, i.e."Qty. per Day", does not give me a editable dropdown textbox, like it does on an object (f.e. table) name. **No workaround**.

PS: it seems that it sometimes works right and sometimes don't, as I am experiencing right now.

**Comment by IvoMol** [comment]
In my experience: Before pressing F2, you must position cursor at first word of filed name, before first space (i.e. "Qty.)

**Comment by qutreson** [comment]
@lvanvugt, thank you for reporting this issue. As we already have an issue tracking it: #498, I am closing this one as duplicate, feel free to contribute there.

**Comment by lvanvugt** [comment]
Great. Had been trying to find an existing bug, but could not find it. #498 is quite old though. The issue is becoming a nuissance, so I would like to know how to get this higher on the backlog?

**Comment by qutreson** [comment]
@lvanvugt, we understand that this issue can be a nuisance, but considering our current backlog for the next months, we unfortunately cannot promise you we will get to it or give you a timeline for when this issue will be resolved.
