### ISSUE TITLE
Excessive Microsoft.Dynamics.NAV.EditorServices memory usage. Is that normal?

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#5354]
**Describe the bug**
Excessive Microsoft.Dynamics.NAV.EditorServices memory usage 

**To Reproduce**
When I go to Windows Task Manager, I see a huge memory consumption on the process.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3531482/66740075-7cdc3700-ee72-11e9-9f19-e50caf674cf2.png)

**5. Versions:**

 - AL Language: 4.0.182565

 - Business Central: 14.0.29530

**Comment by atoader** [comment]
@jbakach is that ~350 MB? It seems to be in line with expectations. 
What is the size of your project? Do you have code analysis enabled? What analyzers do you have enabled?

**Comment by jbakach** [comment]
Hi @atoader deeping on this issue, I found a pattron:

My project is 9,52 MB:

I have 1 instance of VS Code:

Without publishing the extension it consumes the following;

![image](https://user-images.githubusercontent.com/3531482/66747507-05fc6980-ee85-11e9-9d83-affc035178dd.png)

Once I publish...
![image](https://user-images.githubusercontent.com/3531482/66747571-275d5580-ee85-11e9-8494-bc49f456dd8b.png)

And it keeps consuming this amount of memory until I close the VS Code and open it again. If I open VS Code again it keeps consuming a lot of memory once I open a *.AL file.

Why that? Does it upload in memory all the NAV source code to analyze?

I have the following configuration:

![image](https://user-images.githubusercontent.com/3531482/66747973-401a3b00-ee86-11e9-8432-ca5a2ddba753.png)

Maybe disabling the option of background analyze would help?

Thanks in advance!

Best regards,

Jamal Bakach

**Comment by atoader** [comment]
Hi! The source will be read into memory and the state will be maintained in memory for the duration of the process. The memory will not be freed until the .NET GC decides it needs to do so and even then, certain artifacts, are cached and kept in memory so that later compilations can be faster.
You can learn more about how this works internally by reading about the architecture of the Roslyn compiler (we follow the same architectural patterns) and by reading how the .NET GC works internally.
I will close this issue as "by-design" as there is no action we can take at the moment. We are continuously improving the performance of our compiler and you might see improvements in this area in the future.

**Comment by jbakach** [comment]
Hi @atoader,

Thanks for your response and explanation.

Is there any way to only compile and check for errors when publishing or creating the package? Like we've been using within C/Side for all these years?

Thanks again for your help.

Best regards,

Jamal Bakach.

**Comment by thpeder** [comment]
Hi @jbakach, 

If you just want to compile the code into an .app file and it doing that check for errors then you can use alc.exe from Powershell. 
alc.exe can be found in the VSCode extension.

**Comment by jbakach** [comment]
Hi @thpeder, what I pretend is to only compile when I want to genere the app through VS Code. 
Is there any way to prevent the error check while developing and just only check for errors when you try to generate the app?

I think that in this way the compiler will only need to check for any errors in that moment. Just like in C/SIDE.

Thanks again.

**Comment by thpeder** [comment]
Hi @jbakach, 
No, at the moment you can get that. You could disable the extension in VSCode when you don't need it, but we don't provide any such feature.
If you want to see that, head over to [https://aka.ms/BusinessCentralideas](https://aka.ms/BusinessCentralideas) and either upvote the idea or be the first to suggest it there.

**Comment by austinmoca** [comment]
Running into this issue in April 2026 on MacOS and it ends up with dozens of these processes running simultaneously completely overloading the memory on the computer. I've created an issue for this: https://github.com/microsoft/vscode/issues/307474
