### ISSUE TITLE
standard table and extension table

### ISSUE THREAD

**Issue by haemi256** [microsoft/AL#5355]
In a project we have implemented an extension table for the Item Table. Using an external tool, our customer wants to query the data from both tables simultaneously. Basically this could be solved with a data item link (Join SQL Query, Query...). But it is not clear which of the tables is the standard and which is the extension.

In the pages it is no problem to add fields from the extension table with a page extension. We are looking at how this construct works.

Does anyone know if there is a "Link table" or another "mechanism" in BC15 for it?

Thank you.

**Comment by thpeder** [comment]
Hi @haemi256, 
Take a look at the table "Nav App Object Metadata".

This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
