### ISSUE TITLE
Reference to object User is ambiguous (AL0265) / Table 'User' is missing (AL0185)

### ISSUE THREAD

**Issue by navaddict** [microsoft/AL#5358]
**Describe the bug**
local BC150 setup and working however I receive the error shown in the screenshot throughout the AL code, whenever 'User' is referred to.

I have checked the BaseAppSource folder in the Installation Media and the User table is missing - could this be the problem (all virtual tables missing in fact) and if so how can I solve it?

**To Reproduce**
Steps and to reproduce the behavior:

**Expected behavior**
I expect to be able to refer to the User table as this is vital.

**Screenshots**
![image](https://user-images.githubusercontent.com/55881379/66845612-3c5ee500-ef68-11e9-9334-77af4722d100.png)

**5. Versions:**
latest release of BC150

**Comment by atoader** [comment]
Hi! Can you please provide a sample extension to reproduce this issue? What other packages are you referencing?
Please specify the exact version of the product and of the extension that you are using. "latest" does not have the same meaning for all our users.

**Comment by navaddict** [comment]
Hi, I can't provide a sample extension as the second I reference any of the 'virtual tables' (ie. ID = 2000000004 or greater) I get the error and it will not compile.  I'm not referencing any other packages (well except for MS Base and MS System of course).

To prove this I just created a new AL project containing only a very simple table with one field that has a TableRelation to AllObj and the error is shown below:

![image](https://user-images.githubusercontent.com/55881379/66902131-079a6e80-eff8-11e9-9df6-4a5745408a17.png)

The AL source code:

![image](https://user-images.githubusercontent.com/55881379/66902167-141ec700-eff8-11e9-8da5-c0dfd4bb22bb.png)

Simplified app.json file:

![image](https://user-images.githubusercontent.com/55881379/66902261-429ca200-eff8-11e9-9742-124710c42162.png)

The version is Business Central Wave 2 (BC150 - 1st October 2019 release, build = 36649).

Many thanks for any help you can provide as this is driving me nuts!

Not a clue how to solve other than wondering if the dependancies I've specified (Base and System) are somehow wrong/to blame?!

**Comment by navaddict** [comment]
Solved it!

I took out the MS System dependency and left only the Base dependency and this resolved it :)

Seems V15 doesn't need System?

**Comment by atoader** [comment]
That app.json has the answer :).
"platform" and "System" are the same object, you are basically referencing the package twice.
There is some confusion generated by the fact that we now have "System.app" which contains the system and virtual tables and the "System Application" which contains platform-like functionality.

Does that make sense?

**Comment by navaddict** [comment]
All good :)
