### ISSUE TITLE
VS don't get extension logo

### ISSUE THREAD

**Issue by pedperpat** [Microsoft/AL#536]
Good morning, I'm playing with the AL extension at Visual Studio code and I want to put some example logo at my extension.

The logo help says the following: 'URL to the app package logo'.
I thought that if I put some url of googling image will work, but doesn't works.

**Below my app.json code:**

`{
  "id": "c8c89fbb-12e4-4478-b463-e08119392b5c",
  "name": "PackagePrueba",
  "publisher": "Paperez",
  "brief": "",
  "description": "",
  "version": "1.0.6.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "http://www.staffcreativa.pe/blog/wp-content/uploads/IMAGEN-4.png",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "10.0.0.0",
  "application": {
    "version": "10.0.6.0",
    "locale": "US"
  }
}`

And the error I get is:

> error AL1001: Source file 'http://www.staffcreativa.pe/blog/wp-content/uploads/IMAGEN-4.png' could not be found

The url logo could be a local path to the dir of my extension project?

**Comment by thpeder** [comment]
Yes, the url to the logo file needs to be in your extension project directory.
For instance you could have: "media/myLogo.png"

**Comment by pedperpat** [comment]
Solved, thanks :)
