### ISSUE TITLE
Error Reference when creating variable

### ISSUE THREAD

**Issue by hydhart** [microsoft/AL#5360]
hello,

i got an issue, i have 3 reports and each of them use tempblob codeunit to create a file.
however, after the second reports, when i declare the var tempblob, the error show up.

![image](https://user-images.githubusercontent.com/41423177/66895922-0bd98280-f01e-11e9-8976-93094f1f71f4.png)

now the 3 reports i have got the same error.

and also all the function in this codeunit cannot called.

![image](https://user-images.githubusercontent.com/41423177/66896031-50fdb480-f01e-11e9-8e1e-af575d9fb864.png)

i tried use different var name for each report, but still no use.

here is the app.json config
```json
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "1.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "target": "Cloud",
```

**Comment by hydhart** [comment]
i use Business Central 2019 Release Wave 2.W1.36649 on my local to create this extension.

**Comment by thpeder** [comment]
Hi @hydhart, 
I'm not able to reproduce the issue, would it be possible for you to cut down you extensions to the bare minimum that reproduces the issue and upload that extension here on Github.
Thanks

**Comment by atoader** [comment]
@hydhart what packages do you have in your package cache path for this project?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
