### ISSUE TITLE
Dynamics 365 Business Central Wave 2: customizing the Base Application Error

### ISSUE THREAD

**Issue by DmitryPozhilov** [microsoft/AL#5362]
**Describe the bug**
Error during  Publish-NAVApp: Publish-NAVApp : Extension compilation failed 

**To Reproduce**
Steps and to reproduce the behavior:
1. Get Docker container mcr.microsoft.com/businesscentral/onprem:ru.
2. Export Base Application Create-AlProjectFolderFromBcContainer.
3. Open VS Code, made some modifications.
4. Put "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Office.Tools.Excel\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.Office.Tools.Excel.dll" to "C:\Program Files\Microsoft Dynamics 365 Business Central\150\Service\Add-ins\Microsoft.Office.Interop.Excel.dll".

5. Compile project. Warning exists, no errors.
5. Use Publish-NAVApp in PowerShell ISE. Error exists:
- src/dotnet_RU.al(3,14): error AL0451: An assembly named 'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics 365 Business Central\150\Service\Add-Ins, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft Dynamics NAV\Add-Ins\15.0.36510.0, C:\Program Files\Microsoft Dynamics 365 Business Central\150\Service\, C:\Windows\Microsoft.NET\assembly\'

- src/XMLElementLine.Table.al(346,31): error AL0185: DotNet 'XlRangeValueDataType' is missing

``` AL Code to reproduce the issue ```

[Test Publisher_Base Application_15.1.36560.36649.app.zip](https://github.com/microsoft/AL/files/3734515/Test.Publisher_Base.Application_15.1.36560.36649.app.zip)

**5. Versions:**

 - AL Language: 4.0.0

**Comment by atoader** [comment]
Thank you for reporting this issue! What happens if you copy the dll in one of the folders in the probing paths inside the Docker image and then restart the NST? Does publishing succeed in this case?

**Comment by DmitryPozhilov** [comment]
Hello Alexandru,Thank you very match, it's work.I didn't expect such
behevior.

Can I influence the search paths for .net assemblies that the
Publish-NAVApp function uses (pass some parametrs)?

ср, 16 окт. 2019 г. в 21:34, Alexandru Toader <notifications@github.com>:

**Comment by atoader** [comment]
Hi! You cannot influence the search paths, but you can add DLLs in the existing probing paths.
