### ISSUE TITLE
FilterBuilder doesn't respect filters defined on table

### ISSUE THREAD

**Issue by LoanVision** [microsoft/AL#5363]
Hello,
looks like in BC when building FilterBuilder system is not respecting filters defined on table fields.

```al
   var
        Item: Record Item;
        fb: FilterPageBuilder;
    begin
        fb.AddRecord(Item.TableName, Item);
        fb.AddFieldNo(Item.TableName, Item.FieldNo(Item."Global Dimension 1 Code"));
        fb.AddFieldNo(Item.TableName, Item.FieldNo(Item."Global Dimension 2 Code"));
        fb.RunModal();
    end;
```

As a result Global Dimension 1 Code and Global Dimension 2 Code has lookup to all dimension values regardless of what Global Dimension No. is defined on Item table.

<img width="724" alt="Screen Shot 2019-10-16 at 2 53 08 PM" src="https://user-images.githubusercontent.com/45673357/66949565-bf457580-f024-11e9-86a2-b8c1d1109424.png">

<img width="524" alt="Screen Shot 2019-10-16 at 2 52 27 PM" src="https://user-images.githubusercontent.com/45673357/66949467-9ae99900-f024-11e9-9074-7aaaf711fd35.png">
<img width="520" alt="Screen Shot 2019-10-16 at 2 52 20 PM" src="https://user-images.githubusercontent.com/45673357/66949475-9cb35c80-f024-11e9-9a12-a45b939e696e.png">

**Comment by qutreson** [comment]
@LoanVision, can you add which version of the AL extension and of Business Central you are using? Also can you describe what would be the expected behavior for this issue and share with us a full code snippet that we could use in order to easily reproduce this issue?

**Comment by LoanVision** [comment]
It's wave 2 version (Release), 15.0.36510 NA version (Cronus DB, no changes)
AL: 4.0.182565

**Steps to reproduce:**
1 - Create page and replace with code:

`page 50000 TestIssue
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    trigger OnOpenPage()
    var
        Item: Record Item;
        fb: FilterPageBuilder;
    begin
        fb.AddRecord(Item.TableName, Item);
        fb.AddFieldNo(Item.TableName, Item.FieldNo(Item."Global Dimension 1 Code"));
        fb.AddFieldNo(Item.TableName, Item.FieldNo(Item."Global Dimension 2 Code"));
        fb.RunModal();
    end;
}`

2 - Open this page in Business Central, Filter Builder will show up
3 - When looking up to Global Dimension 1 Code -> lookup should filter only values that belong to Dimension 1, When looking up to Global Dimension 2 Code -> lookup should filter only values that belong to Dimension 2

Issue:
Currently lookup shows all dimension values, so when looking up Global Dimension 1 it shows also Global Dimension 2 (and 3..8) values in a list

Let me know if you need anything else.

**Comment by thpeder** [comment]
Hi @LoanVision, 
I ran your code and got the following:
![image](https://user-images.githubusercontent.com/24276180/66998455-92509b80-f0d4-11e9-9db9-37fe09834c99.png)

I'm that familiar with the application, but that is the expected output, right?

**Comment by LoanVision** [comment]
Hello @thpeder 
The result you show is what we expect. However in our CLEAN NA version Build 15.0.36510 the result is as per screenshots. Not sure if it's something you fixed on your internal builds?

<img width="763" alt="Screen Shot 2019-10-23 at 1 13 39 PM" src="https://user-images.githubusercontent.com/45673357/67417676-55364e80-f597-11e9-97d0-4a16fa2be331.png">
<img width="754" alt="Screen Shot 2019-10-23 at 1 13 47 PM" src="https://user-images.githubusercontent.com/45673357/67417687-59fb0280-f597-11e9-8830-9ab67665eaca.png">

**Comment by atoader** [comment]
Hi @LoanVision ! After investigating, we have concluded that this is not a problem with the development tools.
Let's get the issue to a team who will fix and backport it. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
