### ISSUE TITLE
Visibility of override arguments in methods from Visual Studio Code

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/AL#5365]
Could you please improve the visibility of override arguments in a method?
A good example is the new method ToBase64() of the "Base64 Convert" codeunit.

The visible parameter for this method is a Text variable.
This is the only visible parameter in Visual Studio Code:
![image](https://user-images.githubusercontent.com/44872320/66928871-56fd9080-f032-11e9-8590-51223d9710a7.png)

So after hours of trying to convert the stream to text I found out (by coincidence) that the function also accepts an Instream parameter. (I found out by opening the source file in the repository).
This override argument is however not visible in Visual Studio Code.

**Comment by thpeder** [comment]
Hi @Rub19Luc21, 
As you discovered, when you see the list of procedures you can't see that there are more overloads, but as soon as you picked the method you can navigate through the different overloads.

Go ahead and post your idea to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
