### ISSUE TITLE
Deploy Extension is not working in sandbox

### ISSUE THREAD

**Issue by Rathnakmr** [microsoft/AL#5368]
Hi Team,

I am developing new extension in "3.0 Business central Spring 19 Release". Here i am developing under the range of 50000...series only. The package build sucessfully and when i am publishing directling from visual code using "ctrl+F5". 
The message coming successfully published to the server, but when I am checking in sandbox extension its not available.
Right now I am using only upload extension. Its getting to difficult to work with report development because I required to test multiple times by changing some design. each time I have to upload extension and also the app id is increasing for small corrections.

Please do help me to sort out this ASAP.

Also in addition, kindly provide the link for wave 2 release, what are the steps to be followed for the development in visual code, sandbox and production.

Thankyou,
Rathnakumar Paulpandian

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

Regarding your question, nothing has changed with the Wave 2 release. Are you sure the credentials you are using in VSCode are for the sandbox you are targeting? Do you have multiple sandboxes by any chance?

**Comment by Rathnakmr** [comment]
Thanks for the time, I will proceed with support team.
