### ISSUE TITLE
Not able to deploy the old extension after modify

### ISSUE THREAD

**Issue by Rathnakmr** [microsoft/AL#5369]
Hi Team,

I am getting the below error while deploying the extension in sandbox. I am modifying an old extension and then uploading its getting failed.

Please give your suggestion.

Error Msg:
Deployment failed. Errors: App ID : c8081857-e44d-4dce-929e-4ab1bfb3d77b Message : { The extension is not available for your release. Check the country and version availability in the extension marketplace. }
App ID : c85a4670-e818-469b-978f-c1c67f2d88c3 Message : { A request to the Data Plane Admin Service failed.
Http status code: BadRequest
Error:
{

Thanks & Regards,
Rathnakumar

**Comment by atoader** [comment]
Hi! This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

You can find more information here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization . 
Is the extension you are trying to publish an extension that has been published to AppSource? What do you mean by "old extension"?

**Comment by atoader** [comment]
As this issue concerns a production system we suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem. 
 
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
