### ISSUE TITLE
Change functions to External

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#537]
Hi, we are using the following functions which "cannot be used for 'Extension' development".

Table 4 (Currency): ResolveGLCurrencySymbol
Codeunit 312 (CustCheckCrLimit): SalesHeaderCheck
Codeunit 7000 (SalesPriceCalcMgt): GetSalesLinePrice

Can those functions be changed to External?

**Comment by StanislawStempin** [comment]
We will look into these.

**Comment by anwar0206** [comment]
Thanks @kvaldik, for requesting function exposure on Codeunit 312::SalesHeaderCheck and Codeunit 7000 GetSalesLinePrice.
We have been stuck in our App development. 
@StanislawStempin please consider this in next release.
