### ISSUE TITLE
Unused variable in property (AA0137)

### ISSUE THREAD

**Issue by IvoMol** [microsoft/AL#5371]
**Describe the bug**
Code Analyzer is generating warning AA0137, though variable is used in property (not in code).

**To Reproduce**
1. Create global variable
        NewCaptionTxt: Label 'New ';
2. Use this variable in table field property:
        field(45; "New Shortcut Dimension 1 Code"; Code[20])
        {
            CaptionClass = '1,2,1,' + NewCaptionTxt;
            Caption = 'New Shortcut Dimension 1 Code';
etc.

**Expected behavior**
No warning.

**Screenshots**

**5. Versions:**
 - AL Language: 4.0.182565
 - Business Central:15.0.36560.36649

**Comment by qutreson** [comment]
Hi @IvoMol, thank your for reporting this issue. I am closing it as this looks like a duplicate of #5341. Feel free to contribute on the issue linked.
