### ISSUE TITLE
Support "launch browser" with remote development

### ISSUE THREAD

**Issue by tfenster** [microsoft/AL#5372]
**Describe the bug**
When AL runs through the remote dev extension, it fails to create a browser session for debugging. I think what happens is that it tries to run the browser on the remote host. Publishing works, but the VS Code just hangs, see the screen recording below.

Maybe this https://code.visualstudio.com/api/advanced-topics/remote-extensions#opening-something-in-a-local-browser-or-application could be helpful as it seems to describe what needs to be done to open a browser locally or remotely

**To Reproduce**
Steps and to reproduce the behavior:
I hope I have provided a fairly detailed description here https://tobiasfenster.io/remote-development-for-bc-with-vs-code of how to set up an environment to repro

**Expected behavior**
Even with remote development, it should be possible to debug

**Screenshots**
![debug hang](https://user-images.githubusercontent.com/15346084/67166221-9eb34d80-f38d-11e9-8eb5-14ff74068ae9.gif)

**5. Versions:**

 - AL Language: 4.0.182565

 - Business Central:

**Comment by thpeder** [comment]
Hi @tfenster, 
It is as you expected that the browser is opened where the compiler is running.
But what a great idea to add support for remote development in Visual Studio Code! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by tfenster** [comment]
If anyone comes across this issue: I found a possible workaround as described [here](https://tobiasfenster.io/debugging-with-remote-development)
