### ISSUE TITLE
How to Update sales Lines using the Webservices ?

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#5374]
Hello Everyone,

Using the Microsoft document (https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_salesorderline_update) i have created the sales line using the Postman application with POST method, but now when i am trying to update the sales line using the PATCH method in postman application i am getting the below issue.

**Error:**
{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "Bad Request - Error in query syntax."
    }
}

Thanks,
Sainath.

**Comment by qutreson** [comment]
Please follow the template and provide adequate information to reproduce the issue.

**Comment by sainath654** [comment]
Hello,

Below is the url i am using for the update statement. 

Api.businesscentral.com:7048/DEV/ODataV4/Company('Test')/SalesOrder('SO000400557')/salesOrderLines(documentId=('SO000400556'),sequence=(10000))

Thanks,
Sainath

**Comment by kalberes** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
