### ISSUE TITLE
Control Addin is not loading the html resource

### ISSUE THREAD

**Issue by dbsae** [microsoft/AL#5375]
**Need Urgent help.**

We have Control Addin in which we are loading the html resource . Below the code of files. But when we running on Business central 15 version it's giving us the an error. 

**HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://msasiseaas3331-t5kqfo.applicationservices.businesscentral.dynamics.com/Resources/ExtractedResources/9B4AE231/Equation/MKEquation.html?_v=15.0.36437.0**

In On-Premise version is working perfectly. It was working perfectly on cloud as well but suddenly it not founding the resource. but when we click this link it show the html.

Control Addin Code
=============
controladdin  ftext
{
 Scripts =
        'Equation/Scripts/jquery-3.3.1.min.js',
        'Equation/Scripts/Html.js',
        'Equation/Scripts/Equation.js';
    StartupScript = 'Equation/Scripts/loadHtml.js';
    StyleSheets = 'Equation/Styles/CEquation.css';
    Images = 'Equation/MKEquation.html';

    RequestedHeight = 750;
    RequestedWidth = 420;
    HorizontalStretch = true;

    procedure SendEquation(vEquation: Text);
    event ControlReady();
}

Load Html.js
========

$(document).ready(function(){   
    dbs.com.loadControlHtml("Equation/MKEquation.html", function () {  
        Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("ControlReady", [],true);
    });
});

Html.js
=====
(function ($) {    
    window.dbs = {
        com: {
            loadHtml: function (url, callback) {
                var url = Microsoft.Dynamics.NAV.GetImageResource(url);
                $.get(url, function (data) {
                    callback(data);
                });
            },
            loadControlHtml: function (url, callback) {
                this.loadHtml(url, function (data) {
                    document.getElementById("controlAddIn").innerHTML =  data;
                    callback();
                });
            }
        }
    };
})(jQuery);

🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by kalberes** [comment]
This repo is no longer dedicated to handling application requests and enhancements
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
