### ISSUE TITLE
Cannot open xxx page with a filter and sorting from table xxxx

### ISSUE THREAD

**Issue by stijn9830** [microsoft/AL#5376]
I tried to use the tables "Time Sheet header" and "Time sheet line" to make some other functionality. But when I make a header, and try to navigate to the lines, I always get the same error.
So I made new tables, familiar to the existing ones. getting the same error. 
When trying to open the lines pages on the default pages: index out of bounds.

See new tables and pages attachted : always getting this error. Not finding a solution on git or elsewhere. Must be something stupid, sorry

Cannot open "PB PA Times Sheet line" page with a filter and sorting from table "52157431".

[Tab52157431.PBPATimeSheetHeader.txt](https://github.com/microsoft/AL/files/3754249/Tab52157431.PBPATimeSheetHeader.txt)
[Tab52157432.PBPATimeSheetLine.txt](https://github.com/microsoft/AL/files/3754250/Tab52157432.PBPATimeSheetLine.txt)
[Pag52157437.PBPATimesSheetline.txt](https://github.com/microsoft/AL/files/3754251/Pag52157437.PBPATimesSheetline.txt)
[Pag52157436.PBPATimeSheetList.txt](https://github.com/microsoft/AL/files/3754252/Pag52157436.PBPATimeSheetList.txt)

- AL Extension Version:  4.0.182565

- Server Version:  14.0.35916

**Comment by ashikivor** [comment]
The Card Page source table is "PB PA Time Sheet Line"
![image](https://user-images.githubusercontent.com/28855499/67390548-29b66280-f59d-11e9-83f6-7a261d827feb.png)

And you are entering values into the Header.
![image](https://user-images.githubusercontent.com/28855499/67390607-4bafe500-f59d-11e9-8d88-d1357ca0fab5.png)

The header table has value and you are able to see the list on the page. (The line table is still empty)

And when you click on the list page to open the card page(source table - line), it does not find any line with "No". 

Hence you are getting this error.

**Comment by stijn9830** [comment]
@ashikivor 
Stupid indeed, thank you
