### ISSUE TITLE
AL Compiler stops working if an Event Subscriber has a wrong Element Name within

### ISSUE THREAD

**Issue by JonasPatto** [microsoft/AL#5377]
**Describe the bug**
If you create an Event Subscriber with a wrong Element Name, the compiler won't notice that the field does not exists (so no Error) and after that the Compiler just stops working. It does not show 99% of the Warnings (e. g. our own Ruleset stops working and it only shows "deprecated" Warnings) and at the moment no Errors at all.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new Project and create a simple Tableextension like this:
![image](https://user-images.githubusercontent.com/48987445/67273706-44b2a500-f4bf-11e9-8afa-2f9feb8b268b.png)

As you can see this file contains one warning and one error.

Now create a new Codeunit with an Eventsubscriber to any table and enter a non existing Field into the "Element Name"-Parameter and reopen your Project:
![image](https://user-images.githubusercontent.com/48987445/67273941-c30f4700-f4bf-11e9-9758-3f0d043ff8c4.png)

After you reopen your Project it shouldn't show you any Errors or Warnings and you can write anything and it wouldnt count it as an Error:
![image](https://user-images.githubusercontent.com/48987445/67274015-e639f680-f4bf-11e9-8f6c-92c805680109.png)
 
If you try to compile in this state it gives you the following Error Message: (I commented out the little text on the bottom of the Codeunit for this)

Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Der Index, basierend auf 0 (null), muss größer als oder gleich Null sein, und kleiner als die Größe der Argumentenliste.'
Details:
System.FormatException: Der Index, basierend auf 0 (null), muss größer als oder gleich Null sein, und kleiner als die Größe der Argumentenliste.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(IFormatProvider provider, String format, Object[] args)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticFormatter.Format(Diagnostic diagnostic, IFormatProvider formatter) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Diagnostics\DiagnosticFormatter.cs:Zeile 57.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.ReportErrors(IEnumerable`1 diagnostics, CompilerTextWriter consoleOutput, ErrorLogger errorLogger) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 258.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 524.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 490.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:Zeile 349.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<Build>d__8.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:Zeile 174.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__7.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:Zeile 103.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:Zeile 43.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:Zeile 64.

You have to remove the Subscriber (at least the wrong Element Name) and then compile or reopen the project to see "normal" Errors again.

**Expected behavior**
InteliSense knows what fields exist in the table you want to extend but we had many Convertions form C/AL to AL in which we had the situation that some fields did not exist anymore or were changed and it took us some time to figure out why the Compiler behaved like that.
If you enter a wrong Value in "Element Name" it should give you a normal Error like it does with "OnSomeEvent". If you enter an invalid Value there it shows you a clear Error.

**Screenshots**
See above.

**5. Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.182565
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - AL Language: 

Application 15.0.36560.0
 - Business Central:
Platform 15.0.36510.0 

I can provide my project if needed. If you need any more Information please ask.

Best Regards

Jonas Be Patto

**Comment by qutreson** [comment]
@JonasPatto thank you for reporting this issue. I am closing it as this is a duplicate #5292

**Comment by JonasPatto** [comment]
Sorry, I didn't find any Issues resembling this error. Thanks for quick answer
