### ISSUE TITLE
[Action Group Visibility] Dynamicaly set visibility doesn't show the action group

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5378]
**Describe the bug**
Hi,

Don't know if it's a bug or by design: I want to display a group of actions dynamically using the **visible property of the group** equals to a boolean variable.

All my actions has their default visibility (true). When I switch to true a boolean field on the page, I'm expecting that the action group is displayed but it's not.
To do what I want, I have to set the visibility of all the actions of the group to my boolean value. 

Note that with field groups it works as expected (see the code bellow).

**To Reproduce**

``` AL Code to reproduce the issue ```
```
page 50200 MyPage
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(myBool; _myBool)
                {
                    ApplicationArea = All;

                }
            }

            group(someothergrp)
            {
                Visible = _myBool;
                field(SomeVar; _someVar)
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            group(ActionGrp)
            {
                Caption = 'My Actions';
                Visible = _myBool;
                action(ActionName)
                {
                    ApplicationArea = All;
                    Caption = 'MyAction';
                    trigger OnAction()
                    begin
                        Message('MyAction');
                    end;
                }

            }

        }
    }

    var
        [InDataSet]
        _myBool: Boolean;
        _someVar: Text;
}

```
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/29598240/67279391-2ce11e00-f4cb-11e9-9825-3b2126fe871d.png)

![image](https://user-images.githubusercontent.com/29598240/67278964-636a6900-f4ca-11e9-8788-4b60301c3112.png)

**5. Versions:**

 - AL Language: 4.0.182565

 - Business Central: 
![image](https://user-images.githubusercontent.com/29598240/67279444-4d10dd00-f4cb-11e9-87a4-8b208f164f32.png)

**Comment by AndreyKorepanov** [comment]
Hi @JulienDecottignies, thank you for reporting the issue. It seems to be a bug, we'll take a look on it.
Meanwhile a workaround for this issue is to add Visible = _myBool; to each action in the group, then hiding all the items in the group automatically hides enclosing group.

**Comment by qutreson** [comment]
We have reported this issue to the owning team which has added it to their backlog.

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
