### ISSUE TITLE
[InDataSet]

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#538]
Suggestion to enhance the compiler / "build problems":

When you want to make controls/actions invisible based on some logic, you need to use a Boolean variable. If you want to change the text style, you need to use a text variable. All those variables would be assigned to the appropriate property. This only works when you add [InDataSet] to the variable declaration, which can easily be forgotten. 

It might make sense to have the compiler test for any variables used in those property declarations that do not have the flag set. Not sure how difficult it is, but it surely would help.

**Comment by StanislawStempin** [comment]
We are actually already doing it in a lot of cases. If you find scenarios that don't work please let us know.

**Comment by pzentner** [comment]
Specific scenario is that I created a new page in the extension and created a variable controlling the property "StyleExpr".

Here is a test page - this compiles and doesn't show any errors, but you will receive runtime error when executing the page that "NameStrong" not found. Once you add [InDataSet] to variable declaration, it works. Would be great if this would be caught on build time.

`
page 70000000 TestPage
{
    PageType = ListPart;
    SourceTable = Integer;

    layout
    {
        area(content)
        {
            group(GroupName)
            {
                field(Name;Number)
                {
                    StyleExpr=NameStrong;
                }
            }
        }
    }

    actions
    {
        area(processing)
        {
            action(ActionName)
            {
                trigger OnAction();
                begin
                end;
            }
        }
    }
    
    trigger OnAfterGetRecord();
    begin
      if Number mod 2 = 0 then
        NameStrong := 'Strong'    
      else
        NameStrong := 'Standard';
    end;

    var
        NameStrong : Text;
}
`

**Comment by StanislawStempin** [comment]
Thanks, we'll have a look.
