### ISSUE TITLE
Error compiling because I changed the name of fields

### ISSUE THREAD

**Issue by Lcisguz** [microsoft/AL#5381]
**Describe the bug**
When I rename a field on a table extesion on VS Code, then I compile and give me an error:

**To Reproduce**
Steps and to reproduce the behavior:
1. Select then name of a field, and press F2,
2. Change the Name for a shorter name and press Intro, so will change the rest of reference with the same name.
3. Save the changes and when I compile give me an error

(*)If I use Replace in files for renaming the field, I get the same error when compiling

``` AL Code to reproduce the issue ```
Microsoft (R) AL Compiler version 4.0.2.51497
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'IRPF by Nunsys' containing '116' files at '10:6:55.306'.

Compilation ended at '10:6:55.405'.

[Error - 10:06:55] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'El índice (basado en cero) debe ser mayor o igual a cero y menor que el tamaño de la lista de argumentos.'
Details:
System.FormatException: El índice (basado en cero) debe ser mayor o igual a cero y menor que el tamaño de la lista de argumentos.
   en System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   en System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   en System.String.Format(IFormatProvider provider, String format, Object[] args)
   en Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticFormatter.Format(Diagnostic diagnostic, IFormatProvider formatter) en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Diagnostics\DiagnosticFormatter.cs:línea 57
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.ReportErrors(IEnumerable`1 diagnostics, CompilerTextWriter consoleOutput, ErrorLogger errorLogger) en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 258
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 524
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 490
   en Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:línea 349
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<Build>d__8.MoveNext() en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:línea 174
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__7.MoveNext() en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:línea 103
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:línea 43
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() en F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:línea 64
**Expected behavior**

There are no errors and when I compile, the program must show Success: Package is created

**Screenshots**
![image](https://user-images.githubusercontent.com/47604792/67373112-552a5480-f57f-11e9-867b-1c411325fa02.png)

![image](https://user-images.githubusercontent.com/47604792/67373159-6ecb9c00-f57f-11e9-9805-d8cbdba763fa.png)

**5. Versions:**

 - AL Language: 4.0.2.51497

 - Business Central: 15.0.36590.0

**Comment by AndreyKorepanov** [comment]
Hi @Lcisguz, thank you for reporting the issue. It seems to be a bug, but I could not get repro using the snapshots you've provided, the most interesting part is how you referencing this field in your code. Could you provide the project/code demonstrating the issue, it would help us significantly to get a repro.

**Comment by qutreson** [comment]
Hi @Lcisguz thank you for reporting this issue. I am closing it as this is a duplicate of #5292
