### ISSUE TITLE
Can we use Publish-NAVApp command to publish app to D365 Business central cloud sandbox environment

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/AL#5385]
Hello Experts,

can we use [Publish-NAVApp](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/publish-navapp?view=businesscentral-ps-15) to deploy an app to D365 Business central cloud sandbox environment

I have used the below command but getting an error while using the same. 

**Command** 
`$LocalServerInstance = "https://businesscentral.dynamics.com/<tenant_ID>/Sandbox"
$LocalPath = ".\Test.app"

Set-ExecutionPolicy unrestricted
Import-Module 'C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\130\RoleTailored Client\NavModelTools.ps1'
Import-Module 'C:\Program Files\Microsoft Dynamics 365 Business Central\130\Service\NavAdminTool.ps1'
Publish-NAVApp -ServerInstance $LocalServerInstance -Path $LocalPath
`

**Error**
Publish-NAVApp : ServerInstance 'MicrosoftDynamicsNavServer$https://businesscentral.dynamics.com/<tenant_ID>/Sandbox' contains at least one invalid character. **You cannot use the following characters: ':/.'**

Thanks in Advance!

**Comment by atoader** [comment]
Hi! No, you cannot use the commandlets to publish an application to BC. You can use the APIs the application exposes to achieve this https://github.com/microsoft/AL/issues/5353 . 

To get more help for your questions please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
