### ISSUE TITLE
Can not remove page actions with designer

### ISSUE THREAD

**Issue by RobKirsten** [Microsoft/AL#5387]
**Describe the bug**
During customization of page actions, I encountered the repeated error, that Business Central can not handle removing the "Statistics" Action in the Customer Card.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to 'Customer Card'.
2. Start Designing the page.
3. Chose either 'Customer' -> 'Statistics' order 'Navigate' -> 'History' -> 'Statistics'
4. 'Remove' action

(Thus, I am able to hide the whole 'History' block. All the other fields provide just hiding the field. 'Statistics' is the only with remove. Perhaps this is the source of the error.

``` AL Code to reproduce the issue ```

**Expected behavior**
I expect the action to be removed from the action bar.

**Screenshots**
![Bildschirmfoto 2019-10-24 um 10 08 01](https://user-images.githubusercontent.com/56954964/67465936-70ac6280-f646-11e9-833e-a3d961d82e0e.png)
![Bildschirmfoto 2019-10-24 um 10 07 21](https://user-images.githubusercontent.com/56954964/67465937-7144f900-f646-11e9-8d12-4432de6d751b.png)

**5. Versions:**

 - AL Language: 

 - Business Central: Version: Plattform 14.0.35916.0 + Anwendung 35970 (DE Business Central 14.5)
Azure AD tenant: common, Environment: Production

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
