### ISSUE TITLE
Bug: (Wave 2) Job with Job Tasks, fatal error when attempting to change Customer No.

### ISSUE THREAD

**Issue by navaddict** [microsoft/AL#5389]
**Describe the bug**
When a Job has related Job Tasks it is impossible to Enter/Change the Bill-to Customer No.

**To Reproduce**
Create a new Job by just entering 'No.' and 'Description'.
Create a Job Task for this Job
Attempt to enter a 'Bill-to Customer No.' on the Job record

In my example I created some dimensions on the Job and the Customer I chose also had Dimensions (I do not think this will make a difference so only try this if you cannot reproduce the bug at first)

``` AL Code to reproduce the issue ```

**Expected behavior**
I expect to be able to add/remove/amend 'Bill-to Customer No.' with any amount of Job Tasks and/or Dimensions in existance.  And not to ever receive the message shown below.

**Screenshots**
![image](https://user-images.githubusercontent.com/55881379/67482030-f20df000-f65a-11e9-9cbc-69156285791f.png)

**5. Versions:**
15.0.0.0 (BC150)

**Comment by AndreyKorepanov** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
