### ISSUE TITLE
UserSecurityId cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#539]
We are using the UserSecurityId to differentiate between logged in users but it doesn't seem to be available in extension V2 for D365.

Will it never be allowed on D365 or is there perhaps something else that we can us to differentiate between users?

**Comment by pzentner** [comment]
I haven't looked into this, but isn't the "normal USERID still available?

**Comment by bvbeek** [comment]
Can we expect the global function in SaaS: 

`USERSECURITYID`

**Comment by StanislawStempin** [comment]
We will expose this function for use in extensions.

**Comment by epernst** [comment]
Will this still be in the November update? It's strongly missed.

**Comment by StanislawStempin** [comment]
Yes, it will be part of November Update. We will most likely ship it next week.
