### ISSUE TITLE
Wave 02 - Bug in Fixed Controls

### ISSUE THREAD

**Issue by GeekEding** [microsoft/AL#5390]
**Describe the bug**
I found a feature or bug in the fixed controls on pages in BC15. 
We have some pages with this feature. It worked fine for the last versions. But now the Captions is displayed, even though it should be hidden. 

**To Reproduce**
Steps and to reproduce the behavior:
I searched for your pages in the webclient (Page 39 or 253 or 254 for example). The caption is shown there too.
This is an example for the page 39: 
 
![grafik](https://user-images.githubusercontent.com/40355993/66983114-15afc400-f0b8-11e9-810c-8125deb7a4c8.png)

``` AL Code to reproduce the issue ```

**Expected behavior**
I think it should be fixed and the „AccName“ should not be shown there. 

**Screenshots**
This is the code example (which was copied from a standard page before):
 
![grafik](https://user-images.githubusercontent.com/40355993/66983105-12b4d380-f0b8-11e9-9f78-eafc941877eb.png)

**5. Versions:**
15.0.0.0 (BC wave 2)

**Comment by AndreyKorepanov** [comment]
Hi @GeekEding, thank you for reporting the issue. We've already fixed this bug on our side by putting ShowCaption = false on this field. Please try the latest BC build, it should be fixed there.
