### ISSUE TITLE
Wave 2 - Base app translation web search index

### ISSUE THREAD

**Issue by fmoric** [microsoft/AL#5391]
**Describe the bug**
Translating base app in wave 2 with XLIFF file does not update search index.
The app is showing translation, but web search index is still in english.
I don't if i missed a step.

**To Reproduce**
1. Translate base app whit XLIFF

**Expected behavior**
Update web search index

**Screenshots**
![image](https://user-images.githubusercontent.com/18283753/67552714-e29aaf80-f70b-11e9-8f0f-a235677ff5be.png)

**5. Versions:**

 - AL Language: 
4.0.176004
 - Business Central:
platform 15.0.36510.0 + app 15.0.36560.36649

**Comment by atoader** [comment]
Hi! Thank you for reporting this issue! It will be fixed in CU1.
