### ISSUE TITLE
NullException by git checkout with a multiproject workspace

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/AL#5392]
**Describe the bug**
Get an error when using "git checkout" on a multiproject workspace right after opening VSCode.

```
[Error - 10:28:18] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'workspace/didChangeWatchedFiles' failed with error: 'Der Wert darf nicht NULL sein.
Parametername: projectId'
Details:
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: projectId
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentId.CreateNewId(ProjectId projectId, String debugName) in F:\a\460\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\DocumentId.cs:Zeile 74.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.TryAddTransientDocument(String filePath, String text, Boolean handleRad, DocumentId& documentId) in F:\a\460\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:Zeile 177.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeWatchedFilesRequestHandler.HandleAsync(DidChangeWatchedFilesRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\460\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeWatchedFilesRequestHandler.cs:Zeile 30.
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\460\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:Zeile 43.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\460\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:Zeile 64.
```

**To Reproduce**
1. Open a .workspace-file from VSCode with more than one AL-Project.
2. Checkout a different branch than your current one with "git checkout [branchname]". I even can reproduce the bug by using the "Checkout To"-Action from my source control.
3. Exception is thrown.

**Expected behavior**
The error should not be thrown. I am not sure what is effected by the error, but from time to time VSCode shows some warning/errors in my project B that objects from my project A "does not contain a definition", but they do.
Already discussed here: https://www.yammer.com/dynamicsnavdev/threads/361551778758656. Not sure if this error is related to this behavior.

**5. Versions:**
 - AL Language: 4.0.176004
 - Business Central: Plattform 15.0.36510.0 + Anwendung 15.0.36590.0 (docker hosted)

**Comment by atoader** [comment]
Hi! What is different between the two branches?

**Comment by AndreasGloeckner** [comment]
The only difference I can see so far is that the branch I want to check out is not available on remote. Not sure what happens if the remote branch still exists. Need to check it on Monday.

**Comment by AndreyKorepanov** [comment]
Hi @AndreasGloeckner thank you for reporting the issue. I tried to reproduce it using your steps with no success. We recently worked on something similar, could try to reproduce it with the latest AL Extension from market place. If it is still there, could you please attach a workspace demonstrating the issue. Thanks.

**Comment by AndreasGloeckner** [comment]
Hi @AndreyKorepanov. I installed the latest verison from the marketplace (4.0.19.1880) and deactivated the old version. Nevertheless, I still get the exception.
No files were opened in the same or another instance of VSCode.

Tested following scenarios:
1. Open one folder, checkout another branch => no error
2. Open one folder, add another project, checkout another branch => no error
3. Open one folder, add two other projects, ceckout another branch => no error. This is nearly the same initial situation unless I added the folders manually.
4. I open the original saved .code-workspace file with the three projects from step 3. Checkout a branch => Error occurs.

Then I created the same workspace again (see step 3). Saved it. Closed VSCode. Opened the .code-workspace and checkout another branch => no error.

I compared the workspaces: They are identical. Don't know what's the cause...

See here (had to rename the file extension):
[Test.txt](https://github.com/microsoft/AL/files/3779074/Test.txt)

**Comment by AndreyKorepanov** [comment]
Hi @AndreasGloeckner, it seems the problem is with the documents added in the branch you are switching to. We'll take care of it.

**Comment by AndreasGloeckner** [comment]
Sorry, but what documents? And why does it work if I create the same workspace again?

**Comment by AndreasGloeckner** [comment]
Are there any news? Still got the error with VSCode Version 1.42.1 and AL Language 4.0.206840.

**Comment by qutreson** [comment]
This issue has been added to our backlog, but we cannot provide an estimate of when we will actively start working on it.
