### ISSUE TITLE
AL problem (AA0210) GenJournalBatch

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/AL#5393]
Following filter gives an AL compiling notification (AA0210) with runtime 4.0 V15.

`GenJournalBatch.SetRange("Bal. Account Type", GenJournalBatch."Bal. Account Type"::"Bank Account");
`
> (field) "Bal. Account Type": Option
> The table Gen. Journal Batch does not contain the key with the field Bal. Account Type.AL(AA0210)

I think I can assume this is a base code issue? If not would appreciate a way of resolving. :)

**Comment by atoader** [comment]
Hi Timothy,

You can find more information here: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop

As far as the rule is concerned, the error reported is correct. You can ignore it by using a ruleset if you do not find it useful.

**Comment by atoader** [comment]
Is there more information we can provide?
