### ISSUE TITLE
Enhancement to intellisense on method overloads

### ISSUE THREAD

**Issue by charlespockert** [microsoft/AL#5394]
Could we get a number of overloads in the dev tools?

With C# we get that, but I often forget that AL allows overloading because C/AL didn't and sometimes miss things...

![image](https://user-images.githubusercontent.com/9073518/67588809-ee5b9580-f74e-11e9-92d0-9bcac54f86fd.png)

In AL we just get:

![image](https://user-images.githubusercontent.com/9073518/67588863-0d5a2780-f74f-11e9-82a6-ae077e7ceb1d.png)

Despite there being 4 overloads for this:

![image](https://user-images.githubusercontent.com/9073518/67588888-1a771680-f74f-11e9-92e1-f2f2be82359f.png)

**Comment by rvanbekkum** [comment]
See also: https://experience.dynamics.com/ideas/idea/?ideaid=69116e0b-dc8d-e911-80e7-0003ff68d305

**Comment by BazookaMusic** [comment]
This was mostly covered through the work on suggesting the correct overloads. If you type the parens after the function name you get a list of the overloads sorted by relevance.

I will be closing this as fixed.
