### ISSUE TITLE
[InternalEvent] CS0117 'NavEventType' does not contain a definition for Internal

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5397]
**Describe the bug**
Hi,

Susbscribing to an InternalEvent give this error when publishing: 
`error CS0117: 'NavEventType' does not contain a definition for 'Internal' `

If I only publish my InternalEvent it's ok. But if i'm subscribing to it (from the same module) the error occurs.

Documentation doesn't specify to do anything else:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-internal-attribute

Thanks for your help

**To Reproduce**
Copy/Paste bellow code

``` AL Code to reproduce the issue ```
```
codeunit 54000 MyCodeunit
{
    var


    [InternalEvent(false)]
    procedure MyPublisher()
    begin
    end;


    [EventSubscriber(ObjectType::Codeunit, Codeunit::MyCodeunit, 'MyPublisher', '', false, false)]
    local procedure MySubcriber()
    begin

    end;
}
```

**Expected behavior**
App should publish

**Screenshots**
The error is located in a csharp file at line 49:
Here is a screenshot of the copy
![image](https://user-images.githubusercontent.com/29598240/67681787-4c29f080-f98e-11e9-8303-f0c11205c93b.png)
**5. Versions:**

 - AL Language: 4.0.191880

 - Business Central: Platform 15.0.36985.0 + Application 15.0.36626.37063

**Comment by atoader** [comment]
Thank you for reporting this issue! It has been fixed in builds newer than 37404 and it is now available through Collaborate. It will be available in CU1 of the OnPrem release.

**Comment by JulienDecottignies** [comment]
Ok thanks for the quick answer!
