### ISSUE TITLE
Debugging AL code using Visual Studio Code

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#54]
Hi all,
Can someone please suggest how to debug  AL code using visual studio code ?
The problem is I have put breakpoints in my code. When I press the  debug button, it does not show any variable values or anything. It becomes equivalent to pressing F5. It does not debug actually.

**Comment by StanislawStempin** [comment]
Debugging AL code in Visual Studio Code is not implemented yet. It will be available in the future but we don't have a specific date that we can promise. 
We are currently integrating into the debugger flow (F5) in VS Code but only to do deploy and "launch without debugging".

**Comment by StefanHovenbitzer** [comment]
I could imagine that this feature would be quite difficult to achieve as you need user interaction for most code to debug. But i am looking forward to see how it will work

**Comment by TinaMenezes** [comment]
Hi,
Ok. Thank you. Hope this feature is available soon.
