### ISSUE TITLE
The AL Server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#540]
Suddenly after a day of hard work with code, Publishing and debugging my VS Code Show this
![image](https://user-images.githubusercontent.com/29101017/29624558-0e61d94a-8832-11e7-9f10-492c3ba7f8b0.png)

The AL server crashed 5 times in the last 3 minutes. The server will not be restarted.
Could not download symbols. Please see the Visual Studio Code output log for more details.

I did not change any connections. Reboot does not help.

**Comment by MrDavid5465** [comment]
I had this issue before, It seemed to happen when invoking intellisense on the TableRelation property, However it only did that for a short time. A coworker of mine had the issue when Invoking intellisense on the Image property, but again, only for a short time.

**Comment by MrDavid5465** [comment]
Essentially, the issue seemed to right itself after a little while.

**Comment by esbenk** [comment]
The AL server is the Language server (the background compiler) that Visual Studio Code is communicating with. If the language server crashes there will normally be a stacktrace in the log windows.

If the language server crashes 5 times it won't be restarted again by VsCode. Closing the folder and opening it again will restart the server, but the crash is most likely a bug related to your latest changes.

The crash can also be triggered by hover over syntax or invoking intellisense if there is a bug.

Try to revert your last changes or remove a files from the project one at a time until it don't crash. We are very interested in finding what triggered the crash.

**Comment by dkatson** [comment]
ok, I found the reason.
I've created group in page extension with name , which length is greater than 32 symb. 
![image](https://user-images.githubusercontent.com/29101017/29655168-b82db602-88b8-11e7-9850-a4868ffef15a.png) - was the reason of crashing AL

![image](https://user-images.githubusercontent.com/29101017/29655216-e9eeecf6-88b8-11e7-96e3-dc2700f42edc.png)
solved the problem.

I think this is a bug.

**Comment by StanislawStempin** [comment]
Thanks for narrowing it down for us. We will address the bug

**Comment by atoader** [comment]
@dkatson , I would be very grateful if you could attach a snippet or small project that reproduces the crash. 
I cannot repro this issue on the latest build. I've tried using the snippet below. 
```
pageextension 50109 MyExtension extends "Customer Card"
{
  layout
  {
    addfirst("Address & Contact")
    {
        group(Step1QuestionDoYouWantToCopyExistingProjectStep1QuestionDoYouWantToCopyExistingProjectStep1QuestionDoYouWant)
        {   
            field(dasdasdas;''){}
        }
    }
    
  }

  actions
  {
    addfirst("&Customer"){
        group(Step1QuestiondDoYouWantToCopyExistingProjectStep1QuestionDoYouWantToCopyExistingProjectStep1QuestionDoYouWant)
        {   
        }
    }
  }
}
```

**Comment by dkatson** [comment]
Try my project https://github.com/dkatson/NavInTheAir .
I had this error on wizard page https://github.com/dkatson/NavInTheAir/blob/master/Page%2071000003%20-%20AIR%20Flight%20Register%20Wizard.al
