### ISSUE TITLE
CurrFieldNo in OnAfterInsert not set when set from TestPage

### ISSUE THREAD

**Issue by hindsight2020** [microsoft/AL#5400]
Hello,

**Describe the bug**
When i set the Sell-To Customer Name on a SalesInvoice Testpage the OnAfterInsert Trigger in the Tableextension is triggered. However the CurrFieldNo is not set. If i do a manual test where i open a new Sales Invoice, the CurrFieldNo is set when filling the "Sell-to Customer Name".

**To Reproduce**
Steps and to reproduce the behavior:
1. Create the extension  (code below)
2. add breakpoint to "if CurrFieldNo = FieldNo("Sell-to Customer Name") then" line
3. publish extension
4. go to test tools
5. Add Codeunit 90101 and run the test

``` AL Code to reproduce the issue ```

```
tableextension 90100 MyExtension extends "Sales Header"
{
    trigger OnAfterInsert()
    begin
        if CurrFieldNo = FieldNo("Sell-to Customer Name") then
            Message('DoSomething');
    end;

}

codeunit 90101 MyTestCodeunit
{
    Subtype = Test;

    [Test]
    procedure MyTestProcedureName();
    var
        SalesInvoiceTestPage: TestPage "Sales Invoice";
    begin
        SalesInvoiceTestPage.OpenNew();
        SalesInvoiceTestPage."Sell-to Customer Name".SetValue('Adatum Corporation');
        SalesInvoiceTestPage.Close();
    end;

    var
}
```
**Expected behavior**
I expect the CurrentFieldNo in the debugger to be the FieldNo of the "Sell-to Customer Name" field.

**Screenshots**

CurrFieldNo in Manual Test
![grafik](https://user-images.githubusercontent.com/8753511/67765198-d8e6b400-fa4b-11e9-9ad9-58689d6648c0.png)

CurrFieldNo in Automated Test
![grafik](https://user-images.githubusercontent.com/8753511/67765218-e734d000-fa4b-11e9-9ef0-d814888dbb29.png)

**5. Versions:**

 - AL Language: 4.0.191880

 - Business Central: Version: Platform 15.0.36985.0 + Application 15.0.36626.37063

**Comment by kalberes** [comment]
Please follow the template and provide adequate information to reproduce the issue.

**Comment by hindsight2020** [comment]
Updated the initial comment to follow the template.
