### ISSUE TITLE
Function "UploadIntoStream()" does ignore Encoding Options. So german special Characters cant get displayed in BC 15 SAAS

### ISSUE THREAD

**Issue by Jbb93** [microsoft/AL#5403]
**Describe the bug**
If i use the AL-function UploadintoStream() then the Encoding of the Instream gets ignored. This means i cant change the Encoding, so if I import a file with german special characters like ß,ä,ö... cant get displayed in any Buisness Central table. I have this problem in BC15 SAAS-System.

**To Reproduce**
Use the function UploadIntoStream() to upload an ANSI-File wich has german letters to a stream.
If you load the data from the stream to a table, then german special characters are shown as a "?".

Code Example:
tempblob.CreateInStream(FileInstream, TextEncoding::Windows);
UploadIntoStream('Please chose a .txt import file', ImportFolder, 'txt files (*.txt)|*.txt', ImportFile, FileInstream);
        CSVBuffer.DeleteAll();
        CSVBuffer.LoadDataFromStream(FileInstream, ';');
        IF CSVBuffer.FindSet() then
            repeat
                if (CSVBuffer."Field No." = 2) then
                    ORVProtelCustomerImport.Init();
                case CSVBuffer."Field No." of
                    2:
                        begin
                            ORVProtelCustomerImport."Customer No." := FORMAT(DeleteBadChars(CSVBuffer.Value), 20);
                            IF Cust.Get(ORVProtelCustomerImport."Customer No.") then
                                ORVProtelCustomerImport."Customer exists" := true
                            else
                                ORVProtelCustomerImport."Customer exists" := false;
                        end;
                    4:
                        ORVProtelCustomerImport.Name := Format(DeleteBadChars(CSVBuffer.Value), 100);
                    5:
                        ORVProtelCustomerImport."Name 2" := Format(DeleteBadChars(CSVBuffer.Value), 50);
                    ... 
After filling the Values, ORVProtelCustomerImport gets inserted.

**Expected behavior**
Special chars should be shown as the right char in Table ORVProtelCustomerImport  and not as a "?"

**Screenshots**
![1](https://user-images.githubusercontent.com/57138407/67768680-5661f280-fa53-11e9-8735-6d9d20e5f8ac.PNG)
![2](https://user-images.githubusercontent.com/57138407/67768698-5eba2d80-fa53-11e9-9b52-890253de62d9.PNG)

Data:
[Protel Debitoren.txt](https://github.com/microsoft/AL/files/3783595/Protel.Debitoren.txt)

**5. Versions:**

 - AL Language: 
4.0.191880

 - Business Central:
Version: Platform 15.0.37395.0 + Application 15.0.36560.0

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
