### ISSUE TITLE
Chinese Language Translation for Base or Native Business Central Pages

### ISSUE THREAD

**Issue by Saran-il** [microsoft/AL#5404]
I would like to know whether it is possible to create the Translation file for Base or Standard Business Central Pages. Eg. Customer, Item, Role Center Pages of Standard Business Central in Chinese Language.

Also, Chinese Translation solution I'm looking for is not only for the captions,tooltip alone. It needs to translate thing like eg. 'New,Edit,View,Delete,Refresh' in the pages and all the system related captions as well. Is that possible in anyways?

**Comment by thpeder** [comment]
Hi @Saran-il, 

You cannot translate the platform language for Business Central cloud. Only Microsoft can do so.
Currently we have no plans to translate more platform languages in that region.
This is aligned with partners in the region, with whom we worked to enable the countries. It is expected that BC will be able to attract customers with the current language offerings.
If this is not the case we will need to know more.

For translating the base application, you can get hold of the base xliff file and translate that from a docker image.
Read more about it here: [Translating other extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions)

**Comment by r4luk** [comment]
Hello,
I have the .txt file translated for the previous version of BC and I want to "upgrade" it to BC15, and by upgrade i mean i would like to compare the ENU version that i have already translated with the BC15 ENU version (W1) to see if there are some modified or new added captions.

For the previous version i used the C/AL tools: https://docs.microsoft.com/en-us/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files to get the ENU version, in .txt.
For BC15 how can i do this? 

Or is there a new approach about this?

Thanks,
