### ISSUE TITLE
Compiler get's out of sync

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#5408]
This is a follow up of issue #4612 

**Describe the bug**
After changing code that should compile I get compiler warnings and need to refresh to get rid of the warnings.

**To Reproduce**
See attached movie
[2019-10-31_10-48-39.zip](https://github.com/microsoft/AL/files/3793164/2019-10-31_10-48-39.zip)

**Expected behavior**
No compiler warnings when writing correct code

**Screenshots**
See attached movie

**Versions:**

 - AL Language: 4.0.191880

 - Business Central: 15.0

**Comment by atoader** [comment]
Hi! Does this happen on any solution or only a particular solution? Is there any code you could post that could help us reproduce this issue?

**Comment by NKarolak** [comment]
Me and my colleagues see this quite often too. It does not seem to be related to the actual code used. The compiler just reacts too slow, and after some (longer) waiting the result is as expected. 

In order to reproduce, customize the base app on a machine with 32 GB memory, let's say.

**Comment by atoader** [comment]
@NKarolak is the issue transient? What are the settings for your project? This is what we use internally:
```
{
    "al.enableCodeAnalysis":  false,
    "editor.codeLens":  false,
    "al.incrementalBuild":  true,
    "al.enableCodeActions":  false
}

```
You can also consider excluding your source folder from Windows Defender and the Microsoft.Dynamics.Nav.EditorServices.Host.exe process .

**Comment by atoader** [comment]
@larswestman is there any code that you can provide that could help us track down the root cause of this issue?

**Comment by NKarolak** [comment]
@atoader We are using the same settings as suggested, except `al.incrementalBuild: true`, since false works better for us.
Could you please assist me where in the Windows Defender to exclude the folder and the process?

**Comment by larswestman** [comment]
I have excluded my c:\repos and Microsoft.Dynamics.Nav.EditorServices.Host.exe process but are still having issues. 

For me the most common issues is as in the screenshot below. I inserted the framed line and the compiler complaines about my OnBefore procedure.

If I comment out the line [IntegrationEvent(false, false)] the compiler error goes away immideately. Then I remove the // and the codeunit compiles just fine.

![image](https://user-images.githubusercontent.com/43792551/68377937-8abc6980-014b-11ea-9b60-fa8364afcf9a.png)

**Comment by kalberes** [comment]
Looks like a parser issue,  a non recovering state. Probably it has to do with the "With" statement.
It will be very hard to reproduce it on the other hand, given the completely non deterministic nature of the diagnostics service within the compiler.
But will have a look and try to repro it.

**Comment by larswestman** [comment]
I understand. But "not repro" does not always mean that it's working. It's just harder to verify the effect of the fix. This is an annoying issue that we should try to get rid of.

**Comment by larswestman** [comment]
It's always the first IntegrationEvent tag that cause problems for me. Instead of reloading VSC as I used to du I can solve it by commenting theIntegrationEvent tag and then removing the comment
