### ISSUE TITLE
[Bug?] No error when declaring an Enum object directly in a page field

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5409]
**Describe the bug**
Hi,

Declaring a page field and reference an enum directly (not an instance of it) is allowed by AL and it even compile. See the code bellow.

I can compile but if I try to publish I have an **Unexpected value 'EnumType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind** error. 

I think it's normal but how does the AL compiler doesn't react to this ?

I found this behavior when moving a field that was referenced by a page. The field I moved is an Enum and is named the same as the Enum it references.
After moving I expected the compiler to warn me for the references it doesn't find anymore, but as the Enum has the same name the reference was linked to it, even if I can't do anything with it.

Is it a bug or do I miss something ?

Thanks for any clarification!

**To Reproduce**
Copy Past the code bellow

``` AL Code to reproduce the issue ```
```
page 50100 EnumPage
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(MyEnumName; MyEnum)
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    var
}


enum 50100 MyEnum
{
    value(0; MyValue)
    {
        Caption = 'My Value';
    }
}
```

**Expected behavior**
(I think) AL Language should not link the Enum object directly from a page field, but an instance of it. Also (I think) AL Language must warn that the reference doesn't exists

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.191880

 - Business Central: Platform 15.0.36985.0 + Application 15.0.36626.37063

**Comment by atoader** [comment]
Thank you for reporting this issue! I can reproduce it.

**Comment by SUD-D365** [comment]
Any update about this issue?

**Comment by SUD-D365** [comment]
Or any work around ?

**Comment by atoader** [comment]
@PooyaKharamesh will update you once it is ready.

**Comment by atoader** [comment]
The issue has been checked into the master branch and it will be available with the next developer preview.
