### ISSUE TITLE
BlankZeros Does not compile

### ISSUE THREAD

**Issue by tanFiftytwo** [microsoft/AL#5410]
Hi, We are trying to show zeroes on the subform however 

pageextension 6032450 FtlSalesCrMemoSubformExt extends "Sales Cr. Memo Subform"
{
    layout
    {
        modify("Line Amount")
        {
            BlankZero = false; **<= this won't compile.** 
        }

so i have to not show it and then add it agian to show it
        addafter("Line Amount")
        {
            field(LineAmount; "Line Amount")
            {
                BlankZero = false; **<= it compiles fine here**
                ShowMandatory = false;
            }
        }

**Comment by AndreyKorepanov** [comment]
Hi @tanFiftytwo, please follow the template and provide adequate information to reproduce the issue. We need to know what the AL version you are using, what the compiler error, reproduction steps etc. Does it happen for any specific field? Please attach the project which demonstrates the error, if possible.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
