### ISSUE TITLE
Request Header restrictions

### ISSUE THREAD

**Issue by PP1986** [microsoft/AL#5414]
**Describe the bug**
When adding Content-Type to a Request Header I get an Error Message telling me I am misusing the header name. However, although it might not be common to use Content-Type in the request headers instead of content headers, the request I am writing now require this. 

**To Reproduce**
Execute a request with 'Content-Type' added to the request headers.

**Expected behavior**
I would expect AL not to check if Content-Type should be part of the Request Headers or not. I think it should accept whatever I put there and let the API Im calling decide if my call is valid or not.

**Screenshots**
![Content-Type Error](https://user-images.githubusercontent.com/44785533/68121846-1e522800-ff09-11e9-9c30-f0ce64583016.PNG)

**5. Versions:**
 - AL Language: 4.0.191880
 - Business Central: Platform 15.0.36510.0 + Application 15.0.36560.0

**Comment by atoader** [comment]
Hi @PP1986 ! What function are you calling to add the headers? Have you tried using https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-tryaddwithoutvalidation-method ?

**Comment by PP1986** [comment]
Hi @atoader  
It doesn't really make a difference if I use .add or .tryaddwithoutvalidation. Add returns the above error, tryaddwithoutvalidation returns a 'false'. So either way, I cannot add Content-Type to the request header, while the API I'm talking to requires this.

**Comment by atoader** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will help us greatly in prioritizing this work against other suggestions from the community.
