### ISSUE TITLE
Unable to locate Txt2AL.exe file in Business Central Wave2 OnPremise

### ISSUE THREAD

**Issue by Saran-il** [microsoft/AL#5418]
Hi.. 

Kindly excuse if this query was raised earlier or the misunderstood from my side.

Previously, Txt2AL.exe and its dll can be found in Programfiles (C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\Txt2Al.exe).

Similarly, when I tried to access the Txt2AL from the installed Business Central wave 2 location in Program Files (C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\150\RoleTailored Client) , I couldn't locate it. 

When I checked the Installation folders, I was able to locate it under the following path (Dynamics 365 Business Central 2019 Release Wave 2.AU.36649\LegacyDlls\program files\Microsoft Dynamics NAV\150\RoleTailored Client).

Would like to know whether it is available somewhere else in the Installed file in Program Files as well?

**Comment by atoader** [comment]
Hi! Txt2Al is strongly coupled to the TXT files and C/SIDE. We recommend that you use the one released with 14.x . We will continue adding features to it and any bug fixes that will come along. You can find it on the latest Docker image from these branches.
