### ISSUE TITLE
XmlNamespaceManager Code Sample

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#542]
Could you please provide a sample of how to use the XmlNamespaceManager in AL? I can't seem to find a way to attach it to an XmlDocument. I would have expected to be able to call XmlNamespaceManager.NameTable(XmlDocument.NameTable), but it doesn't seem that XmlDocument exposes that property.

**Comment by atoader** [comment]
Thanks for the feedback! It seems the functionality was not exposed in the compiler. We will fix it ASAP.

**Comment by jcooper01** [comment]
Thanks. I'm using Docker if that helps you get an update out faster :)

On Aug 24, 2017, at 3:13 AM, Alexandru Toader <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback! It seems the functionality was not exposed in the compiler. We will fix it ASAP.

**Comment by jcooper01** [comment]
Do you know if this will be in the next release? We can't function without namespace support.

**Comment by atoader** [comment]
Yes, it should be in the next docker drop.

**Comment by jcooper01** [comment]
Do you know when that will be? We are being held up by this.

**Comment by StanislawStempin** [comment]
@jcooper01, please contact Freddy to get the latest Docker image
