### ISSUE TITLE
[Bug] Test codeunits, error when trying use action from Subform

### ISSUE THREAD

**Issue by Drakonian** [microsoft/AL#5420]
Hello,
When I write a simple code in my test function:

![image](https://user-images.githubusercontent.com/16802407/68292602-e24bce00-0094-11ea-8b5a-6fb624771398.png)
(in this case, DB contain some record in Sales Header)

I get a weird error on run codeunit in TestTool:

**The part with ID = 321840514 was not found on the page.**

This error happens with any action on any subform.

 - AL Language: 4.0.191880
 - Business Central: 15 NA

**Comment by Drakonian** [comment]
Code in txt format:

```
codeunit 54007 "Test Example"
{
    Subtype = Test;

    [Test]
    procedure MyTestProcedureName();
    var
        SalesOrder: TestPage "Sales Order";
    begin


        SalesOrder.OpenView();
        SalesOrder.GoToRecord(SalesHeader);

        //ERROR
        SalesOrder.SalesLines."Co&mments".Invoke();
    end;

    var
        SalesHeader: Record "Sales Header";

}
```

**Comment by eknraw** [comment]
I just ran into this issue but the action was on a page extension object.

**Comment by atoader** [comment]
Hi! I tried running the code against the latest version of the application and platform. If I run it exactly like you posted it, I get the following error:
![image](https://user-images.githubusercontent.com/3097909/68533938-396ccf80-032f-11ea-9cdb-4448307fe5e6.png)

I adjusted the code slightly so that I initialize the record before passing it to the page.
```
codeunit 50100 "Test Example"
{
    Subtype = Test;

    [Test]
    procedure MyTestProcedureName();
    var
        SalesOrder: TestPage "Sales Order";
    begin

        SalesHeader.FindFirst();

        SalesOrder.OpenView();
        SalesOrder.GoToRecord(SalesHeader);

        //ERROR
        SalesOrder.SalesLines."Co&mments".Invoke();
    end;

    var
        SalesHeader: Record "Sales Header";

}
```

and I get
![image](https://user-images.githubusercontent.com/3097909/68533949-5e614280-032f-11ea-92b2-bba027049839.png)

I adjusted the code a bit so that the record is initialized and that modal pages are handled and it works:
```
codeunit 50100 "Test Example"
{
    Subtype = Test;

    [Test]
    [HandlerFunctions('MyModalHandler')]
    procedure MyTestProcedureName();
    var
        SalesOrder: TestPage "Sales Order";
        t: Page "Sales Order Subform";
    begin

        SalesHeader.FindFirst();

        SalesOrder.OpenView();
        SalesOrder.GoToRecord(SalesHeader);

        //ERROR
        SalesOrder.SalesLines."Co&mments".Invoke();
    end;

    var
        SalesHeader: Record "Sales Header";

    [ModalPageHandler]
    procedure MyModalHandler(var testPage: TestPage "Sales Comment Sheet")
    begin
        // Message('Hello');
    end;
}
```

**Comment by atoader** [comment]
I've seen the error message you have posted when an action's visibility was set to false in the code and then the test page tried to change it. In any instance, it does not appear to be an issue with the AL language extension or the development tools, which is the main focus of this repository.

We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by sandeepkumar022** [comment]
Hello Everyone
Is this resolved? I am also getting same error .

MS Dynamics 365 BC
Version (14.0.47686)

Could anyone  suggest?

**Comment by MichaelDieringer** [comment]
I get the same bug when testing against 23.4
Help needed???

**Comment by sandeepkumar022** [comment]
@MichaelDieringer - Thanks. I managed the situation and able to solve.
