### ISSUE TITLE
Bug: Wave 2 - Extension EventSubscriber cannot see standard local functions!

### ISSUE THREAD

**Issue by navaddict** [microsoft/AL#5422]
**Describe the bug**
So, if I create a new EventSubscriber and write code to access a local function in a standard object I am told the function doesn't exist.

**To Reproduce**
Create a new EventSubscriber to the Purchase Header 'Order Address Code' OnAfterValidate and add code as follows:

GetVend("Buy-from Vendor No.");
**CopyPayToVendorAddressFieldsFromVendor(Vendor, FALSE);**
"Buy-from Phone No." := Vendor."Phone No.";

This fails compilation on the 2nd line - stating that the CopyPayToVendorAddressFieldsFromVendor function doesn't exist.

I can see that it does exist in the standard PurchaseHeader.table.al object but that it is **local**.  And this is the problem.

I can solve this by copying that function to my own Codeunit and removing it's "local" command. 
 But this is no way to proceed as it means my code is divorced from the base product and when the base (local) function is altered then my version is out of date.  

There will be **many** instances where access to standard local functions is needed - so this must be resolved.

Please advise ASAP!

**5. Versions:**
 - Business Central:
15.0.0.0

**Comment by atoader** [comment]
Hi! "local" is an access modifier that says that it can only be accessed from within the scope of that object. 

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

If you need the function to be exposed, please post your question to https://github.com/microsoft/ALAppExtensions . 

Our FAQ offers guidance on this https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
