### ISSUE TITLE
Using SystemId in RunPageLink causes the client to crash

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5423]
**Describe the bug**
When you use the field SystemId in a RunPageLink the client crashes with no information in the telemetry.

**To Reproduce**
Steps and to reproduce the behavior:
Create an action with 
RunObject = Page
RunPageLink = RowId = field(SystemId);

to open a page with related records. The client will crash when you click the action.
It can be solved by writing code in the OnAction trigger to apply the filter.

**Expected behavior**
Either SystemId is not supported in a PageLink and then compiler should warn about it, or the runtime should just create the correct filter automatically (preferred).

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.191880

 - Business Central: Platform 15.0.37725.0 + Application 15.0.36560.0

**Comment by eknraw** [comment]
This also crashes the client when used in a page part subpagelink.

**Comment by tfbtrading** [comment]
Had the same issue when experimenting with linking the Documents Attachment Factbox using SystemID. Had thought perhaps we were moving to that pattern - but apparently not.

**Comment by scm6iwa** [comment]
Any news on getting this fixed as I'm going development using the systemid and linking to a factbox via SubPageLink and the client keeps crashing

**Comment by acjdekorte** [comment]
In issue #5696 it is mentioned that Microsoft is aware of the issue, but ETA when they will solve this.

**Comment by kevindstanley1988** [comment]
Hello, any status on this. This bug eliminates many of the positives that system id brings.

**Comment by kevindstanley1988** [comment]
Verified not working with version 16.4 using this project. https://dev.azure.com/wolcottgroupllc/_git/TestSubPageLink

This is a very simple example. I have a table with fields TableID and "Related To System Id". A generic list part with these 2 fields. On the Item card I added the list part with this subpagelink.

SubPageLink = TableId = Const(27), "Related To System Id" = field(SystemId);

We have been waiting for this feature to work since systemId got introduced. It makes table relations far more complex than needed by not allowing for this.

cross post from issue #5696

**Comment by tfbtrading** [comment]
This is related to in general the lack of ability to use systemid to relate and navigate between records.  Using GUID for navigation between relationships is in general best practice now – the more that we see a gap between how we do this via API’s and in AL – the more challenging it will be over time.

**Comment by thloke** [comment]
I'm closing this as this issue is to do with the actual server runtime rather than the VSCode extension or AL language itself. As explained in #5696 this should be raised through Collaborate. There's not much we can do from the extension side to make this work.
