### ISSUE TITLE
Microsoft.Dynamics.Nav.Deployment.Authentication.UserNotAuthorizedException

### ISSUE THREAD

**Issue by Phfo** [microsoft/AL#5426]
Version BC15 : 
Debug - Attach - shift-F5 error : 'Microsoft.Dynamics.Nav.Deployment.Authentication.UserNotAuthorizedException'
when using authentication : 'UserPassword'

**Comment by atoader** [comment]
Hi! Could you please follow the template and provide adequate steps to reproduce the issue?

**Comment by Phfo** [comment]
Please close this one...new = #5427
