### ISSUE TITLE
Microsoft.Dynamics.Nav.Deployment.Authentication.UserNotAuthorizedException when trying to debug with launch.json - attach not working

### ISSUE THREAD

**Issue by Phfo** [microsoft/AL#5427]
**Describe the bug**

> Microsoft.Dynamics.Nav.Deployment.Authentication.UserNotAuthorizedException when trying to debug with launch.json - attach not working

**To Reproduce**
Steps and to reproduce the behavior:
1. Create server instance with UsrPasswd authentication;
make new launch.json for debugging 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "attach",
            "name": "xxxxxxx",
            "server": "http://localhost/",
            "port": 7149,            
            "serverInstance": "serviceinstancexxxxxx",                
            "authentication": "UserPassword",                                                             
            "breakOnError": true,            
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            "breakOnRecordWrite": true,                
            "breakOnNext": "WebClient"            
        }
    ]
}

``` AL Code to reproduce the issue ```

**Expected behavior**
Start debugging

**Screenshots**
![image](https://user-images.githubusercontent.com/24912240/68402717-0f26e080-017c-11ea-9adc-4573cc475266.png)

**5. Versions:**

AL Language 4.0.194000
 - AL Language: 

 - Business Central:

Operation system version : Microsoft Windows Server 2019 Datacenter

**Comment by atoader** [comment]
What is the version of the server to which you are trying to publish? That is also important. You can edit your current post.

**Comment by Phfo** [comment]
I received an VSC update today...installed it and restarted VSC...now it works fine.
You can close the case.

**Comment by atoader** [comment]
Thanks @Phfo!
