### ISSUE TITLE
Need support for Runtime: 5.0

### ISSUE THREAD

**Issue by antoniotrives** [microsoft/AL#5428]
I cannot publish my extension

[2019-11-07 19:08:07.38] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 5.0
- Web API: 4.0
- Debugger: 3.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0
- Supported Web API: 1.0, 2.0, 3.0
- Supported debuggers: 1.0, 2.0

**Comment by atoader** [comment]
Hi! To what server instance are you trying to connect?

**Comment by atoader** [comment]
Please follow the template for opening an issue and provide us with sufficient information to understand your scenario.

**Comment by atoader** [comment]
Runtime 5.0 is only available through preview builds. In that case, you should use the VSIX from within the Docker image.
