### ISSUE TITLE
Lables for groups are shown in page

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#543]
If I create a group on the page, by default it shows the label. But for standard objects, it doesn't show it.

Example:
Page 1816
![image](https://user-images.githubusercontent.com/29101017/29668536-42be531e-88e9-11e7-9ef3-2e0424d233be.png)
result
![image](https://user-images.githubusercontent.com/29101017/29668561-5bf80050-88e9-11e7-93ba-afa35a0fb29c.png)

But if I copy the same code in extension layer
![image](https://user-images.githubusercontent.com/29101017/29668592-77cd4b6e-88e9-11e7-8460-9aedd4599343.png)
result is
![image](https://user-images.githubusercontent.com/29101017/29668612-837d5508-88e9-11e7-9ab5-e272a7a67a0d.png)

**Comment by pzentner** [comment]
I had the same issue. if you define CaptionML=ENU='', it will solve the issue  Shouldn't have to do this, but it's a workaround

**Comment by StanislawStempin** [comment]
That's correct. The workaround for now is to add an empty CaptionML. Eventually we will add a property ShowCaption = false to control this behavior for groups.
