### ISSUE TITLE
Cannot debug multiple clients without running into login issues eventually.

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#5431]
**Describe the bug**
When attempting to debug without publishing, you will be blocked because of a bad credentials

**To Reproduce**
Debug client 1. Debug other clients. Debug client 1. Get stuck with a bad login. I have to clear credentials on a weekly basis which is a very tired tedium.

``` AL Code to reproduce the issue ```
None, just configure your launch.json

**Expected behavior**
Use the correct credential so or at the very least give me the option to use another account.

**Screenshots**
![image](https://user-images.githubusercontent.com/16603906/68514921-68eedf80-023c-11ea-922e-73cfb047a5d0.png)
Text version:

> Sign in 
> 
> Sorry, but we’re having trouble signing you in.
>  
> AADSTS50020: User account 'xx' from identity provider 'https://sts.windows.net/xxx/' does not exist in tenant 'xxx' and cannot access the application 'xxx'(Dynamics 365 Developer) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. 
>  
> Request Id:  abedd73b-035e-44fc-b07e-9f844b997000 
> Correlation Id:  7a3f7aa3-f5f3-4223-811f-08074592469b 
> Timestamp:  2019-11-08T22:18:15Z 
>  
> Message:  AADSTS50020: User account 'xxx' from identity provider 'https://sts.windows.net/xxx' does not exist in tenant 'xxx' and cannot access the application 'xxx'(Dynamics 365 Developer) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. 
>    
> Advanced diagnostics: Disable 
> If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**5. Versions:**

 - AL Language: Name: 4.0.191880

 - Business Central: Platform 14.0.37683.0 + Application 37693 (US Business Central 14.5)

**Comment by atoader** [comment]
Hi! The problem you are describing seems very similar to https://github.com/microsoft/AL/issues/4636 . Is there any difference in the scenario? If not, I will close this issue as a duplicate of the other one.

**Comment by mjmatthiesen** [comment]
It seems to me like this isn't the same problem. I already specify the tenant in the launch.json as debugging is otherwise entirely impossible. Even with the tenant specified, after switching between enough tenants, the login credentials will fail and attempt to use an entirely unrelated account - in this case the account used for my visual studio subscription which shouldn't even be in the same store as it was never ever entered into vs code.

**Comment by atoader** [comment]
The credentials are cached independent of your launch.json and we do not track the tenant in any way. Whenever you switch tenants, you need to clear you credentials.

**Comment by mjmatthiesen** [comment]
How are the credentials cached then? It seems to me that it works up to a certain point and then breaks for anything and everything. I often work with a dozen or more customer  systems at a time, plus various BC dev systems.
We use a password manager, so it's not the end of the world to have to reset them, but I do wonder how it happens that credentials from a completely different system (enterprise vs) end up in vs code?

If this isn't considered a bug, then I would really consider this a feature request, maybe using the windows credential store to keep this on hand and manageable.
