### ISSUE TITLE
AL does not recognise symbol reference until a new project is created

### ISSUE THREAD

**Issue by olisterr** [microsoft/AL#5432]
Refer https://community.dynamics.com/business/f/dynamics-365-business-central-forum/371746/custom-fields-did-not-show-in-al/982648#982648

**Comment by atoader** [comment]
Hi! This repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
