### ISSUE TITLE
 lookup is not triggering everytime

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#5433]
**Describe the bug**
The onopenpageevent of Vandor, customer and item lookup is not triggering everytime we select the lookup. It only triggers 1st time and not subsequent time. 

Is it by design or is it  a bug? can you please help.

**To Reproduce**
subscribe to onopenpage trigger of  customer lookup page 33.
write some code on the subscriber function. a message for example.
try to open customer lookup page in sales invoice.

**Expected behavior**
message should be displayed every time we click on the lookup. 

**5. Versions:**

 - AL Language:  4.0.198182

 - Business Central: Platform 15.0.37582.0   Application 15.0.36626.37711

**Comment by atoader** [comment]
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by SergioKelly** [comment]
@atoader 
I did create a new support request "266557"
