### ISSUE TITLE
The compilation target is set to 'Internal', you must set to cloud or extension.

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/AL#5435]
![image](https://user-images.githubusercontent.com/35260264/68570142-3ae9e500-0460-11ea-87c5-4a5a11232f07.png)

Customer is on 14 on premises.

**Comment by atoader** [comment]
Hi! Diagnostics with the prefix AS come from the AppSourceCop analyzer. If you are not developing an extension for AppSource, you should disable it.
You can read more here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool
