### ISSUE TITLE
How to work with translations of the Base application BC15 (wave 2) - question

### ISSUE THREAD

**Issue by r4luk** [microsoft/AL#5438]
Hello,
I have the .txt file translated for the previous version of BC and I want to "upgrade" it to BC15, and by upgrade i mean i would like to compare the ENU version that i have already translated with the BC15 ENU version (W1) to see if there are some modified or new added captions.

For the previous version i used the C/AL tools: https://docs.microsoft.com/en-us/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files to get the ENU version, in .txt.
For BC15 how can i do this?

Or is there a new approach about this? 
In BC15 will be still using the .txt file? Or .xliff?

Thanks,

**Comment by atoader** [comment]
Hi @r4luk ! You can find more information here: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/758 .

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
