### ISSUE TITLE
Fixed assets and Item Variants in August Update

### ISSUE THREAD

**Issue by MrDavid5465** [Microsoft/AL#544]
In our extension, we were hoping to be able to create fixed asset on the sales line, however, in the August update we found that the fixed asset is no longer an option. Another thing that we were hoping to use was Item Variants however it appears that Item Variants are no longer available in the sandbox. Are these things going to be added back in a future update? Do we have a configuration issue?

"Only these types are available"
![image](https://user-images.githubusercontent.com/29601581/29674705-f1afbba2-88c0-11e7-8d12-895527e64ce8.png)

We were hoping to use items to sell Licenses use the Item Variants with special pricing to handle the different prices that a license could cost.

"The Variants button is missing, you can see also how I was hoping to use the variant"
![image](https://user-images.githubusercontent.com/29601581/29675795-3de50600-88c4-11e7-95be-38df92418223.png)

**Comment by MrDavid5465** [comment]
any comments from anyone?

**Comment by BardurKnudsen** [comment]
Fixed assets is still there behind the scenes, but is hidden for 'foundation' (application areas #Basic and #Suite) but is visible for #Advanced. Out of curiosity and lack of insight to all potential usages: Is it a core business scenario to sell a fixed asset via a sales invoice?

**Comment by BardurKnudsen** [comment]
Hmmm.... Didn't mean to close the thread....

**Comment by BardurKnudsen** [comment]
The Variant code is also only visible for #Advanced.

**Comment by MrDavid5465** [comment]
Our CPA suggested that the fixed assets should be able to be sold on the sales line as it is a core business scenario to be able to sell fixed assets. Of course in financials we can't choose the advanced user experience, but I think it would be quite beneficial to have variants available in Financials
