### ISSUE TITLE
The compilation target is set to 'Internal', you must set to cloud or extension. REF #5435

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/AL#5441]
Our customer is on version 14 on premises.
When setting target to internal, i get error when compilingproject.

![image](https://user-images.githubusercontent.com/35260264/68651441-b4003f80-0527-11ea-8f9b-5ac0817e4f93.png)

![image](https://user-images.githubusercontent.com/35260264/68651510-d6925880-0527-11ea-9ce9-bdbf2a40b271.png)

When i set target to OnPremise, I get error:

![image](https://user-images.githubusercontent.com/35260264/68651616-0c374180-0528-11ea-8f40-2a047f78d2f5.png)

We need to be able to use target "internal" on premise on version 14.
This was working before the new update in Visual studio code - AL Language.

**Comment by atoader** [comment]
From the issue you have referenced, what piece of information is missing to unblock you?

**Comment by DanielHaglo** [comment]
Our customer uses BC 14 on premises. As the customer uses dotnet code, we must set Target to Internal. In BC 15 Internal has been replaced with OnPrem. When we try to compile, we get an error message that Target must be set to OnPrem. But when we set Target to OnPrem we get the error that OnPrem is only used in BC 15.

**Comment by atoader** [comment]
There is nothing preventing you from using OnPrem target. That diagnostic is coming from an analyzer which it seems that you have enabled unwillingly. The AppSourceCop static analysis component is optional and should be used mainly for validating AppSource submissions.

You can read more about it here: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool

You can ignore/disable a specific diagnostic by following the guidelines set forth here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

**Comment by atoader** [comment]
To be a bit more specific, AS0053, and any diagnostic prefixed with AS is coming from AppSourceCop

**Comment by pschwambornMC** [comment]
Same Problem here but with 15 Onprem. Everytime I want to build with AppSourceCop and "target": "OnPrem" it comes the error: "error AS0053: The compilation target is set to 'OnPrem', but it must be set to 'Cloud' or 'Extension'".

**Comment by atoader** [comment]
@DanielHaglo please let me know if you are still blocked.

**Comment by DanielHaglo** [comment]
You can close this issue. 
When removing diagnostic it worked.
