### ISSUE TITLE
Deposit report is not opening

### ISSUE THREAD

**Issue by BSSIRajbir** [microsoft/AL#5443]
**Describe the bug**
I am facing difficulty in running the deposit report. I created a deposit and run the deposit report, but it throws an error.

**To Reproduce**
Steps and to reproduce the behavior:
1. Search for the deposit report, it will throw an error.

``` AL Code to reproduce the issue ```

**Expected behavior**
The report should open perfectly.

**Screenshots**
![image](https://user-images.githubusercontent.com/43894249/68697273-570a8680-0533-11ea-80f7-12ba6662eb46.png)
![image](https://user-images.githubusercontent.com/43894249/68697288-5b36a400-0533-11ea-9641-f6a85db89358.png)

**5. Versions:**
 - AL Language: 5.0.191295

 - Business Central:15.0.0.0

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
