### ISSUE TITLE
Unused variable in property (AA0137)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5444]
Maybe related to other issues #5237 

Having following code ...

![image](https://user-images.githubusercontent.com/25268332/68702017-4b957a80-0588-11ea-993e-c7bffcf980f4.png)

with some global vars

![image](https://user-images.githubusercontent.com/25268332/68702034-53551f00-0588-11ea-9179-8b716fd02006.png)

results in a CodeCop 'Unused variable' (AA0137) warning, while the variable is actually used in the DataCaptionExpr property.

AL version used
![image](https://user-images.githubusercontent.com/25268332/68702084-71bb1a80-0588-11ea-9510-340a82fdc719.png)

**Comment by ChrisBlankDe** [comment]
We have the same problem but with an other Property.

Code for MS to reproduce/test:
```
table 50100 MyTable
{
    DataClassification = CustomerContent;
    fields
    {
        field(1; "Demo"; Integer)
        {
            Caption = 'Demo';
            DataClassification = CustomerContent;
            CaptionClass = StrSubstNo(AnyLabelLbl, ''); //This Line cause an AA0137 Warning
            // CaptionClass = AnyLabelLbl;
        }

    }
    keys
    {
        key(PK; "Demo")
        {
            Clustered = true;
        }
    }
    var
        AnyLabelLbl: Label 'Whatever %1';
}
```

**Comment by MarcHansenMicrosoft** [comment]
fixed
