### ISSUE TITLE
ISOLATEDSTORAGE Runmodal error

### ISSUE THREAD

**Issue by geogarin** [microsoft/AL#5445]
The code:

ISOLATEDSTORAGE.SET(‘myKey’,’MyValue’,DATASCOPE::User); // and any other datascope
PAGE.RUNMODAL(0,customer);

Cause error:
Microsoft Dynamics 365 Business Central
—————————

The following C/AL functions are limited during write transactions because one or more tables will be locked. Form.RunModal is not allowed in write transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, ‘OK := Codeunit.Run()’ is not allowed. Report.RunModal is allowed in write transactions only if ‘RequestForm = FALSE’. For example, ‘Report.RunModal(…,FALSE)’ is allowed. XmlPort.RunModal is allowed in write transactions only if ‘RequestForm = FALSE’. For example, ‘XmlPort.RunModal(…,FALSE)’ is allowed. Use the COMMIT function to save the changes before this call, or structure the code differently.
—————————
OK
—————————

**Comment by geogarin** [comment]
Because it inserts record into "Isolated Storage" table, it starts new transaction and this cause such error. I can do such table myself and cover it with same functions. What is the advantages of using ISOLATEDSTORAGE?

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by geogarin** [comment]
It's not question. It's bug!

**Comment by atoader** [comment]
That was not apparent because you have not followed the bug reporting template.
