### ISSUE TITLE
Update Snippet for Profile

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5446]
**Describe the bug**
The Snippet `tprofile` for creating a profile seems to wrong prefilled compared to the [official documentation for profiles](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object)

https://github.com/microsoft/AL/blob/15ac1ee93f0b8eab624a756ab7f8a8798246ab63/snippets/profile.json#L7

**To Reproduce**
Steps and to reproduce the behavior:
1. Check the Source on https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-profile-object.md

**Expected behavior**
Change the Text of Description to 'Some internal comment that only the Dev can see' or change Description with ProfileDescription.

**Screenshots**
---

**5. Versions:**

 - AL Language: 4.0.198182

 - Business Central: sandbox:15.0.36626.37063-de-ltsc2019

**Comment by atoader** [comment]
Hi! Have you noticed that there are two snippets suggested for profiles?
![image](https://user-images.githubusercontent.com/3097909/68789715-4860c400-0646-11ea-976b-a0ea47aa854e.png)

The snippets are provided by VSCode and cannot be versioned with the same precision as some of our other language features, so we are providing both options in Intellisense.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
