### ISSUE TITLE
Bug in Dutch Telebanking (easy to fix)

### ISSUE THREAD

**Issue by MaartenGerritsen** [microsoft/AL#5450]
Codeunit 426 "Payment Tolerance Management" has Dutch localization code. 
The variable CBGStatementLineApplID is of Length 20, this should be 50.
This causes runtime errors when posting a CBG Statement with a lot of lines.

- AL Extension Version: 
![image](https://user-images.githubusercontent.com/25688441/68787797-7e9c4480-0642-11ea-80a9-102a3402e6ec.png)

- Server Version: 
![image](https://user-images.githubusercontent.com/25688441/68787856-9673c880-0642-11ea-9181-8be13dbf94aa.png)

![image](https://user-images.githubusercontent.com/25688441/68787552-0df52800-0642-11ea-9601-895d1fb55e02.png)

**Comment by atoader** [comment]
Hi @MaartenGerritsen ! Welcome to the AL repository! :) Thank you for the reporting this issue! Unfortunately, this repository is not the best place to report issues in the application.
Please make sure that you read our FAQs https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions and the readme file in the root of the repository https://github.com/microsoft/AL . 

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
