### ISSUE TITLE
FieldValidate property values (XMLport)

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#5451]
Today building an XMLport found out that not all boolean properties in AL use true/false as values. Apparently the FieldValidate property uses still Yes/No. Seems to me a bug.

**Comment by atoader** [comment]
Hi Luc! I think this might be by-design. As far as I can see, the property can have three states: Yes, No or Undefined and all the values are used in the runtime. I will double check to be sure.

**Comment by lvanvugt** [comment]
> Hi Luc! I think this might be by-design. As far as I can see, the property can have three states: Yes, No or Undefined and all the values are used in the runtime. I will double check to be sure.

Exactly and that's what is atypical AL where all binary properties should now be true/false. As far as I know the undefined defaults to yes.

**Comment by atoader** [comment]
Hi Luc! We have discussed this and we agree with you that it is quite an odd construct. If we would have caught this earlier, we would have probably changed it to true/false. We try to maintain the compiler and language backwards compatible and obsoleting the old Yes/No in favor for True/False will require us to develop a compatibility story. We may fix it in the future, but right now it doesn't meet the bar.
