### ISSUE TITLE
ISOLATEDSTORAGE Runmodal Error

### ISSUE THREAD

**Issue by geogarin** [microsoft/AL#5452]
**Describe the bug**
ISOLATEDSTORAGE.SET method begins new transaction. So you get error if you write after the SET method any code that breaks transaction Page.Runmodal, ok:=Codeunit.Run, Report.Runmodal 

**To Reproduce**
Steps and to reproduce the behavior:
Try this code:
ISOLATEDSTORAGE.SET(‘myKey’,’MyValue’,DATASCOPE::User); // and any other datascope
PAGE.RUNMODAL(0,customer);

where: customer : record 18

**Expected behavior**
It should not cause error. It should permit to set value to storage and open customer list page.

**Error description**
Microsoft Dynamics 365 Business Central
—————————
The following C/AL functions are limited during write transactions because one or more tables will be locked. Form.RunModal is not allowed in write transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, ‘OK := Codeunit.Run()’ is not allowed. Report.RunModal is allowed in write transactions only if ‘RequestForm = FALSE’. For example, ‘Report.RunModal(…,FALSE)’ is allowed. XmlPort.RunModal is allowed in write transactions only if ‘RequestForm = FALSE’. For example, ‘XmlPort.RunModal(…,FALSE)’ is allowed. Use the COMMIT function to save the changes before this call, or structure the code differently.

**5. Versions:**
 - Business Central:
any current version of Business Central

**Comment by atoader** [comment]
Thanks for providing info @geogarin ! I will forward it to a team member that can help.

**Comment by atoader** [comment]
@geogarin we have discussed this issue and the behavior is by design. IsolatedStorage uses tables in the background for storing data, but it can isolate data from other extensions. We will update the documentation to mention this.

**Comment by PooyaKharamesh** [comment]
As Alex mentioned this is a general behavior in BC. If a record is opened in a write session opening a modal is not allowed due to the locking issue. Isolated Storage follows the same pattern. you can consider to open the modal before setting anything in the Isolated Storage and keep the input in a variable and finally call the set function on Isolated Storage. 

/Pooya

**Comment by geogarin** [comment]
But if I need this value in that modal object? If I want to change transaction behavior depending on that value? But do not offer me to use commit, please.
You provide a technology that allows to pass variables around the system, but it turns out that there are such restrictions. With the same success, I can add a table myself and put all the values there. What are the advantages of using ISOLATEDSTORAGE? It seems it's dead technology in this form.

**Comment by geogarin** [comment]
The best way to fix it is to use temporary table.
