### ISSUE TITLE
Find OnInsert/OnModify/OnValidate... usages in Visual Studio Code

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#5453]
Hi,

Visual Studio Code provides a lot of useful features to see where code is used using the **References** functionality. Is there a way to easily find **OnInsert/OnModify/OnValidate**... **trigger usages** of a table/page,... in **AL**? In the old **C/AL** days (...a couple of weeks ago...)  we could use an external tool called **Prism** to do this, but in AL I haven't any solution for this.

Any ideas?

**Comment by atoader** [comment]
Hi! At the moment, there is no way to find references as the symbols used for a trigger are different than the ones used for the method that indirectly calls that trigger. 
We will add this to our long term backlog.

**Comment by fvet** [comment]
An idea has been created to gather votes.
https://experience.dynamics.com/ideas/idea/?ideaid=56458708-fb7f-eb11-8ced-0003ff45d48e

**Comment by atoader** [comment]
Thanks @fvet! Let's focus input and discussion in the BC Idea.
