### ISSUE TITLE
Lookup page trigger not raised every time

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#5457]
The onopenpageevent of Vandor, customer and item lookup is not triggering everytime we select the lookup. It only triggers 1st time and not subsequent time. 

Is it by design or is it  a bug? can you please help.

**Comment by atoader** [comment]
Hi! Could you please follow our issue template and provide instructions on how to reproduce this problem?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
