### ISSUE TITLE
Mismatched begin end in VS Code .al file

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#5459]
![image](https://user-images.githubusercontent.com/19267298/68866518-71d42b00-06ec-11ea-94a1-4a0531f1dc34.png)

Please see attached. Notice that the end has been matched to the wrong begin. It belongs with the begin at the top of the picture. Not sure if this is an AL extension bug or a VS Code bug? Threw me for a bit and had me scattering begins and ends around the code.

**Comment by atoader** [comment]
Hi! This is a new feature in VSCode 1.40 . We will investigate to see where this is coming from.

**Comment by jimmymcp** [comment]
Update: case statements are part of the problem. VS Code doesn't see an end as belonging to a case statement.

**Comment by bjarkihall** [comment]
I also provided a screenshot of the mismatch in #4449 (mismatch happens on "else if")
