### ISSUE TITLE
Extension of the Report XML parameters to the RequestPage structure

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#546]
If you want to run a report outside of Dynamics NAV and pass parameters, you can use the usual parameter XML file. However, this has a drawback. You need to know exactly how this is built for each report.

It is also not possible to save this file without having executed the report once in NAV. (Error occurs because the RequestPage must be displayed once).

This is however with the extension development very stupid. In an on-premise environment, you can easily find the structure of the RequestPage using the object metadata. Unfortunately, this table is not available in the extension development.

Therefore a perhaps satisfactory proposal:
It should be possible to read out the structure of the stored RequestPage so that the XML parameters can be built dynamically. This structure should contain not only the captions, but also the names of the DataItems, the stored tables and field options, if any. This is the only way to get a report about a web service or an external program whose parameters are completely unknown.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider it for the backlog.

**Comment by FSharpCSharp** [comment]
Is there anything new on this point? This was also mentioned in the referenced issue with the number 912. There I was told to make a point of my own, and then I referred back to that point.

Conversion as an extension is not possible if no proper solution is provided.

**Comment by FSharpCSharp** [comment]
@dennisfrostlander @StanislawStempin 
I have consulted with us in the company on this point once again. From our point of view, the simplest solution would be to either query all of these points via an additional option in the report, or simply revise the existing XML. For the first step, it would be enough to simply extend the existing XML to include the most important parameters. I've built an example here, which illustrates the whole thing a little bit, using the example of report 205, maybe you can just take these additional fields in so that we can get on with it. The only precondition would be that the structure can be retrieved as XML without having to open the report. Until now, it is the case that if you want to receive the XML, the report has to be opened once. Otherwise there is an error.

```
<?xml version="1.0" standalone="yes"?>
<ReportParameters name="Order Confirmation" id="205">
  <Options>
    <Field name="NoOfCopies" datatype="Integer" caption="No. of Copies">2</Field>
    <Field name="ShowInternalInfo" datatype="Boolean" caption="Show internal Information">false</Field>
    <Field name="ArchiveDocument" datatype="Boolean" caption="Archive Document">false</Field>
    <Field name="LogInteraction" datatype="Boolean" caption="Log Interaction">true</Field>
    <Field name="DisplayAssemblyInfo" datatype="Boolean" caption="Display Assembly Information" >false</Field>
    <Field name="OptionTest" datatype="Option" caption="Option Test" optionstring="Value1,Value2,Value3" optioncaption="Value 1,Value 2,Value 3">Value2</Field>
  </Options>
  <DataItems>
    <DataItem name="Sales Header" caption ="Sales Header" visible="true" requestfilterfields="1,3" table="36">VERSION(1) SORTING(Field1,Field3) WHERE(Field3=1(1000))</DataItem>
    <DataItem name="CopyLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="PageLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="DimensionLoop1" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="Sales Line" caption ="Sales Line" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1,Field3,Field4)</DataItem>
    <DataItem name="RoundLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="DimensionLoop2" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="AsmLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="VATCounter" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="VATCounterLCY" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="Total" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="Total2" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="PrepmtLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="PrepmtDimLoop" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="PrepmtVATCounter" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
    <DataItem name="PrepmtTotal" caption ="Integer" visible="false" requestfilterfields="" table="2000000026">VERSION(1) SORTING(Field1)</DataItem>
  </DataItems>
</ReportParameters>
```

The changes in the example are rather marginal. Only some additional information is transferred. But these make life easier. Thus it is possible to provide the user with the required information. As already mentioned above, it would be crucial that these options (in this case best value-log) can be read directly from the report, for example: `REPORT. GETREQUESTXMLSTRUCTURE (205)`. So you don't need a direct reference to a specific report. Just the number is enough. This should also be possible from a background session. This means that it is best to be able to run this information in the TASK Manager.

**Comment by FSharpCSharp** [comment]
@dennisfrostlander @StanislawStempin
One more question on this point. Would it also be possible to include the required routines in the C/AL Open Library? Then I could retrieve the required information from the metadata XML and pass it to a formatted form. And Microsoft could also maintain this code unit if there was a different internal data structure. This would only help me to make significant progress on this point if there is no system-wide solution to this problem.

**Comment by StanislawStempin** [comment]
If you can achieve this scenario fully in C/AL and expose a coherent set of APIs for AL then by all means this is a good candidate for the Open Library.

Otherwise this will need to wait a bit more in the backlog as we have a lot of competing priorities to work on.

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
In C/AL, the implementation of this topic was no problem. I already have the source code. I will make a pull request in the C/AL Open Library and refer to this topic. Then there is at least something to bridge the gap until the system might provide another solution.

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
I just wanted to ask if there is anything new to my pull request. It would be very nice if this adaptation could be included in any way, because then this complete point can also be closed and the product can be completely converted to extension 2.0. It would be really great if someone could comment on it! Even if there is a long-term solution for directly mapping this with system functions, it would be desirable if this code unit from the pull request would be available for the transitional period.

**Comment by dennisfrostlander** [comment]
Closing since an alternative solution was developed in the related pull request
https://github.com/Microsoft/cal-open-library/pull/56
