### ISSUE TITLE
[Enhancement] Configuration option for CORS Policy on Service Tier

### ISSUE THREAD

**Issue by NAVRockClimber** [microsoft/AL#5461]
Hi,

due to we are moving all our C# Add-Ins to JavaScript it would be nice if you could implmement a configuration option for Cross-Origin Resource Sharing (CORS) in the service tier. 

The missing CORS policy prevents you from reading any web service data from a browser application like e.g. the BC web client. 

For security reasons browsers do not allow reading data from other resources (e.g. ODATA service) as from which your application was served from (your web server / IIS). This can be resolved if the target service allows this by the CORS feature.

Due to we need to read larger amounts of data we love the possibility to fetch them via ODATA in our applications. But we always need to implement workarounds like reverse proxies for being able to access the service. 

Although you already offer the possibility on your Cloud environment. It is missing in the OnPremise environment.

Can you please add a possibility?

Best regards,
Bert

**Comment by atoader** [comment]
Hi! I think this is a great idea, but implementing goes beyond the scope of the AL language and the developer tools around it.
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
