### ISSUE TITLE
Unable to Login Dynamics 365 Business Central, if Company Name is given in Permission set

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/AL#5462]
we are working on below version.

**Version**: 15.0.36626.38042-us
**Style**: sandbox
**Platform**: 15.0.38019.0

Create an user with **D365 Basic** Permission Set and  **D365 Read** permission with Company Name Cronus Included in the permission set. 
![first permission2](https://user-images.githubusercontent.com/28556102/68943812-37dd5480-07d2-11ea-897d-639f6ca3b74b.png)

In the User Personalization, Profile ID - Business Manager is selected.
![2C88B03B](https://user-images.githubusercontent.com/28556102/68942930-cdc3b000-07cf-11ea-9173-38062198561f.PNG)

Now we are trying to login with PE user, Unable to login Business Central

Logout from Super User :
![logout](https://user-images.githubusercontent.com/28556102/68943070-26934880-07d0-11ea-81b6-4d4e65863c19.png)

Trying to Login in with another User :
![Again we are login with PE credentials](https://user-images.githubusercontent.com/28556102/68943117-49bdf800-07d0-11ea-90b4-64a38ce0d10e.png)

Unable to Login, because of below error
![output error](https://user-images.githubusercontent.com/28556102/68943139-58a4aa80-07d0-11ea-901d-df430dad001b.png)

Now we have tried to remove the Company from the Permission set which is defined above.
![final2](https://user-images.githubusercontent.com/28556102/68943592-9d7d1100-07d1-11ea-9dd5-f2f3874a8c6a.png)

We are able to Login now 
![able to login with pe](https://user-images.githubusercontent.com/28556102/68943627-b2f23b00-07d1-11ea-81f0-a35ce41e5f85.png)

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
