### ISSUE TITLE
'RunOnClient' is not a valid attribute on variables of type 'None'

### ISSUE THREAD

**Issue by MadoaHenry** [microsoft/AL#5466]
- AL Extension Version: 

- Server Version:

**Comment by atoader** [comment]
Hi! Your problem is caused by the fact that the .NET type is not found. Make sure you have resolved all errors related to .NET type loading before this.

**Comment by atoader** [comment]
Does that help?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
