### ISSUE TITLE
Tenant Permissions not updated on F5 for deleted objects

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5467]
**Describe the bug**
Using a PermissionSet.xml, when deploying extensions over VS Code to a sandbox, it seems that Tenant Permission Set Records from already deleted objects are still kept.

**To Reproduce**
1. Create/open an extension folder with at least two AL objects involved (at least one codeunit). 
2. If a PermissionSet.xml does not exist yet, create it with ["AL: Generate permission set containing current extension objects"](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets#to-export-permission-sets-using-visual-studio-code). 
3. Publish the extension to your sandbox using F5 or Ctrl + F5.
4. In the web client, open page "Permission Sets".
5. Navigate to your extension permission set and verify that all objects are included in fact box "Tenant Permissions"
6. Return to VS Code. Delete a codeunit object.
7. Run "AL: Generate permission set containing current extension objects" again. Verify that the deleted codeunit is not included.
8. Publish the extension to your sandbox using F5 or Ctrl + F5.
9. The deleted codeunit is still included under "Tenant Permission". You cannot call action "Permissions" due to a run-time error. You can neither delete that record using the web client.

I was able to resolve that issue by manually removing the extension completely, prior to running F5 again. 

**Versions:**

 - AL Language: 4.0.199169

 - Business Central: 15.2.38034.0-de

**Comment by thloke** [comment]
Hi @NKarolak,

I'm looking into the issue now, but I can't reproduce this with the steps given. When I publish the second version of the extension with a codeunit removed, the tenant permission entry is removed as well.

I have a few questions:

1. What permissions does the user who is doing the publishing have?
2. Is this a vanilla sandbox with no non-MS extensions installed? If not, does it reproduce on such a sandbox?

Thanks in advance! (:

Thanks,
Thaddeus

**Comment by NKarolak** [comment]
@thloke Due to NAV TechDays, I won't be able to check on that this week. But I will answer later.

**Comment by thloke** [comment]
No problem. I'll be monitoring this issue, so I'll pick it up again when you've had a chance to look at it.

**Comment by NKarolak** [comment]
Hi @thloke,

regarding your questions:

1. Honestly I don't understand the question. I am local adminstrator, working on this repo alone. My database user has SUPER rights.
2. I am pulling from "bcinsider.azurecr.io/bcsandbox:de". The app I am developing on is the only non-MS app in this database.

**Comment by AndreyKorepanov** [comment]
Hi @NKarolak, is the issue still actual? If so could you please test it with the latest BC daily build or provide us with a test AL project demonstrating the issue. It would significantly help us to get a repo. Thank you.

**Comment by NKarolak** [comment]
@AndreyKorepanov 
After 7 months, my memory about this issue is quite limited ;-) 
Let me return later to you, after some testing.

**Comment by NKarolak** [comment]
I could not reproduce the issue for BC 16 with AL Language 5.0.288712
