### ISSUE TITLE
Page Extensions Trigger OnAfterGetRecord executing multiple number of times.

### ISSUE THREAD

**Issue by ranjithabhimanyu** [microsoft/AL#5471]
**Describe the bug**
Page extension to customer card , trigger OnAfterGetRecord() is executing multiple number of times.
**To Reproduce**
Steps and to reproduce the behavior:
1. create page extension 
pageextension 50106 UpdateName extends "Customer Card"
{
    trigger OnAfterGetRecord();
    begin
        Message('%1', Rec.Name);
    end;

}
``` AL Code to reproduce the issue ```

**Expected behavior**
when we open customer card , customer name should message once.
but it executed multiple number of times , message box will not close,

I tested the same page extension for Location card, it works as expected. displayed location name once and message box will close. 

**Screenshots**
[Customer Card OnAfterGetRecord Multiple Times executing.docx](https://github.com/microsoft/AL/files/3861277/Customer.Card.OnAfterGetRecord.Multiple.Times.executing.docx)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
