### ISSUE TITLE
EditDimensionSet2 is missing in DimensionManagement

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5472]
In BC wave2 release i noticed that **EditDimensionSet2** function is missing in Dimension Management codeunit.
But i found **EditDimensionSet** function two times with different parameters.
Is it something like Function Overloading in AL that MS introduced earlier in AL development?

Thanks

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
