### ISSUE TITLE
Code Coverage Not showing all Lines

### ISSUE THREAD

**Issue by ToraVision** [microsoft/AL#5474]
**Describe the bug**
Code Coverage does not show all lines of code that were excecuted. 
That makes it hard to reach 90 percent Code coverage with the testapp.
The Lines were executed. I've debugged through it.

**To Reproduce**

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.199169

 - Business Central: Version: DE Business Central 15.1 (Platform 15.0.37769.0 + Application 15.1.37793.0)

**Comment by atoader** [comment]
Hi! Can you please provide a sample test app and a sample app so that we can investigate this issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
