### ISSUE TITLE
Poor Publish & Debug (F5/Alt+F5) Performance on Large Database

### ISSUE THREAD

**Issue by marknitek** [microsoft/AL#5475]
**Describe the bug**
On a large Database (140GB with lots of history data) we have very bad performance when publishing Extensions from VS Code. 
- It does not matter if we use RAD or not (F5 / Alt+F5)
- It does not matter if we use ForceSync or Synchronize SchemaUpdateMode
- It does not matter what kind of change we do, even the change of a caption property results in this issue.

Publishing takes several minutes to execute. On a Cronus Database the same extension publishes within a few seconds. 

While Publishing there is massive resource consumption on the sql server (CPU & Disk IO)
When looking at it with the profiler i can see that every table extension table is performed with some sort of data consistency logic:
- INSERT with PK Values for non existent Records in the extension table
- DELETE of any Record in the extension table that does not exist on the original Table

I understand the reason for this logic (to maintain data consitency across extension tables) but in my opinion it does not make any sense to do this if nothing has changed in the schema and we as a developer should have the possibility to prevent this consistency validation for increased performance (given the impact it can have on development speed)

**To Reproduce**
Steps and to reproduce the behavior:
Use a large Database with customization (TableExtension) on history tables like G/L Entry, Sales Invoice Header, Sales Invoice Line, etc.

**Expected behavior**
At least when using RAD and not changing anything table related (no fields added,removed,changed) the performance should be consistently fast no matter the size of the database. 
Right now it is not possible to work with large databases... 
Since this is a Upgrade Project, we need the data for validation

**Screenshots**

**5. Versions:**

 - AL Language: 
4.0.199169

 - Business Central:
CH Business Central 15.1 (Platform 15.0.37769.0 + Application 14.0.36457.0)

**Comment by PooyaKharamesh** [comment]
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release. It will help us positively to prioritize the issues and address the most common ones more quickly.

**Comment by marknitek** [comment]
@PooyaKharamesh this is not an idea this is a serious bug/issue!

**Comment by atoader** [comment]
@marknitek we agree that this is a problem and we appreciate very much that you have raised this issue. We are only asking you to post it on BCIdeas because it will give other partners the possibility to support your issue and if it raises a large number of votes, we will be able to allocate more time to improving this across multiple teams.

**Comment by larswestman** [comment]
This should not be voted as an idea! It's a bug that should be fixed.

**Comment by MarvinPowell** [comment]
Any update on this? I could not find anything in the ideas forum and we are having the same issues. Due to a very large database each publish takes up to 30 minutes.

The data consistency logic should only be run if the underlying tables have changed or it should be possible to disable them for a specific publish.
