### ISSUE TITLE
Cop Warnings

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/AL#5476]
- AL Extension Version: 4.0.199169
- Server Version: 15.0.36510

Now that we are not supposed to have both AppSourceCop and PerTenantExtensionCop turned on at the same time there are issues that are easily slipping through the cracks.

The one that has bitten us is forgetting to re-generate the permission set when we add a new table. [PTE0004 ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop-pte0004-tablesmusthavepermissionsetdefined)from PerTenantExtensionCop used to catch this.

While I hate to ask for duplicate checks, if we are not supposed to have both turned on, could we get the appropriate checks moved to the appropriate Cops?

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will help us to prioritise the tasks. We're constantly monitoring top Ideas and will consider them for a future release.
