### ISSUE TITLE
warning AL1025 Creating TenantWebService with snippet gives me warning does not match any definition

### ISSUE THREAD

**Issue by MortenRa** [microsoft/AL#5479]
**Describe the bug**
Creating TenantWebService with snippet twebservice gives me warning AL1025 when creating package with ObjectType Codeunit :  does not match any definition and do not publish the tenant webserviced

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a tenantwebservice with ObjectType Codeunit 
2. Build package 
3  See warning
4 Publish pacakge and verify that webservice is not published in webservice in BC due to warning

``` AL Code to reproduce the issue ```
`<?xml version="1.0" encoding="utf-8"?>
<TenantWebService>
    <ObjectType>CodeUnit</ObjectType>
    <ObjectID>6082710</ObjectID>
    <ServiceName>test</ServiceName>
    <Published>true</Published>
</TenantWebService>`

**Expected behavior**
Expected that webservice was published automatically when publishing package.
Works fine if I choose Query in the Objecttype

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.199169

 - Business Central:  DK Business Central 15.2 (Platform 15.0.38154.0 + Application 15.2.38235.0)

**Comment by thloke** [comment]
Hi,

The error is triggered because the `twebservice` snippet is meant to insert a new entry into an existing tenant web service definition file. To set up an entirely new file, use the `twebservices` snippet.

The snippet should look like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>CodeUnit</ObjectType>
            <ServiceName>serviceName</ServiceName>
            <ObjectID>50010</ObjectID>
            <Published>false</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

I'm surprised that it doesn't trigger the error with Query. I've tried it locally, and it gets the same error message - which is expected since the error is about the file format.

Regardless, the `twebservices` snippet should give you what you need.

Thanks,
Thaddeus

**Comment by MortenRa** [comment]
Thaks I actually tried that earlier, And just tested now and actually just notice if you write with capital letter in the published tag as below it gives you error AL1027 , it must be >true< to be accepted

<Published>True</Published>

**Comment by thloke** [comment]
Yes, that is correct. The parsing of that is case sensitive. We could definitely make the error message more descriptive (or better still, just make it case insensitive). I'll raise that as an internal usability bug. My suspicion is that it should be a easy QoL fix.

Thanks for the feedback!

**Comment by gmpopplewell** [comment]
For anyone that still gets this with a Codeunit web service, you have to use "CodeUnit" rather than "Codeunit"
