### ISSUE TITLE
How to get test libraries in the BC wave 2 release ??

### ISSUE THREAD

**Issue by sainath654** [microsoft/AL#5480]
Hello Every one,

In the previous versions of business central we do have test toolkit folder for creating the test package ,but now in the business central wave 2 release we don't have any test tool kit folder for creating the test package. How to get test libraries and test tool page in the business central wave2 release.

Thanks,
Sainath

**Comment by atoader** [comment]
Hi! have you checked the DVD under Applications\TestFramework ?

**Comment by sainath654** [comment]
Yes, i have published the all the extensions present in the Applications\TestFramework under the DVD folder.

**Comment by atoader** [comment]
I guess it depends on what you are searching for. The files in Applications\TestFramework  are the new test framework. If you are searching for the previous test libraries that are used by the Base Application, you can find them under Applications\BaseApp\Test.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
