### ISSUE TITLE
Question: Updating translations for Base Applications of Wave 2 and later

### ISSUE THREAD

**Issue by r4luk** [microsoft/AL#5483]
Hi,
For Wave 2 or later, what is the method to update the translations for Base Application, from one version to another.
We have 2 things to check:
     1. the new "captions" (or labels) added by Microsoft
     2. the modified "captions" (or labels), used in previos version as, for example: Production Forecast, and in Wave 2 is Demand Forecast.

Do you have a tool you recommend for this? 

The situation I have now, for example, is that i have the xlf for BC14 with all the translations I need, and I want to update it to Wave 2. How can I do this?

Thanks a lot.

**Comment by PooyaKharamesh** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by PooyaKharamesh** [comment]
you can also read more here https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/758

**Comment by r4luk** [comment]
Thanks a lot. :)
