### ISSUE TITLE
AppSourceCop active in workspace folder despite settings

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5489]
**Describe the bug**
In a repo with two folders (apps) A and B and a workspace containing these, AppSourceCop rules are used on the B folder app.json although activated only for folder A.

**To Reproduce**
Create a repo with subfolders `app` and `test`. Add a workspace and include both folders (and use that workspace of course ;-)).
Activate the AppSourceCop in the `app` folder only.
_Click somewhere into the `test` folder and wait._

These are my current settings:

**workspace.code-workspace**
```
{
	"folders": [
		{
			"path": "app"
		},
		{
			"path": "test"
		}
	],
	"settings": {
		"al.backgroundCodeAnalysis": false,
		"al.enableCodeAnalysis": false
	}
}
```

**app\\.vscode\settings.json**
```
[...]
    "al.enableCodeAnalysis": true,
    "al.backgroundCodeAnalysis": true,
    "al.codeAnalyzers": ["${CodeCop}","${AppSourceCop}","${UICop}"],
    "al.ruleSetPath": ".\\.vscode\\AppSourceCop.ruleset.json"
}
```

**test\\.vscode\settings.json**
```
[...]
    "al.enableCodeAnalysis": false,
    "al.backgroundCodeAnalysis": false
}
```

**Expected behavior**
The AppSourceCop should not be run for the `test` folder.

Instead, the AppSourceCop throws errors for the `test > app.json`
![image](https://user-images.githubusercontent.com/34504100/69608346-89ce7780-1027-11ea-902d-3d4deaea8b5a.png)
It might take some time until the errors show up.

**Versions:**

 - AL Language: 4.0.199169

 - DE Business Central 15.2 (Platform 15.0.37954.0 + Application 15.2.38034.0)

**Comment by PooyaKharamesh** [comment]
A work around could be to consider having them in 2 different workspaces.
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by kine** [comment]
Hi @PooyaKharamesh 
I see this as a bug - because if I am setting the CodeCops per folder, they should be working per folder. Having Test app and Main app in separate workspaces is complicating everything and is against what was done to support multiple roots in workspaces (automatic dependency publishing etc.). It is really just possible workaround, shortterm (and if it is workaround, there is bug...).

Please, reconsider this again, because it is really a bug, not feature...

**Comment by mjmatthiesen** [comment]
Agree with @kine and @NKarolak

This is most certainly a bug and now how workspaces are to function. There's vs code settings, workspace settings, and project settings. I may have subproject that wouldn't be on app source and thus need that cop disabled.

**Comment by NKarolak** [comment]
Upvote the idea: https://experience.dynamics.com/ideas/idea/?ideaid=5a5f8d29-4d10-ea11-b265-0003ff68d51d

**Comment by kalberes** [comment]
See #5585

**Comment by qutreson** [comment]
Closing this issue as it is tracked by a BC idea now.
