### ISSUE TITLE
txt2al may not generate addafter references to unnamed controls correctly

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#549]
It seems that txt2al creates addafter anchor names like Part1900316107 in the layout section of pageextensions, but the compiler expects an anchor name of Control1900316107.

**Comment by jcooper01** [comment]
Similarly, Separator123 should be changed to Action123 in AL.

**Comment by atoader** [comment]
Do you mean that the symbols in the reference package are named differently than the ones in the converted extension?

**Comment by jcooper01** [comment]
No, I mean that txt2al should either change the symbol names so that they work in AL or AL should recognize the symbols from the TXT export.

**Comment by gunnargestsson** [comment]
Converting a page change that will add a page on the top of the FactBoxArea (Control 1900000007) on page 9309.

    { Insertion         ;InsertAfter=Container1900000007(Control 1900000007);
                         ChangedElements=ControlCollection
                         {
                           { 10017351;1;Part     ;
                                       Name=Part10017351;
                                       SubPageLink="Document Type"=FIELD("Document Type"),
                                                   "No."=FIELD("No.");
                                       PagePartID="Workflow User Group Used";
                                       Visible=FALSE;
                                       PartType=Page }

                         }
                          }


is converted to 

  layout
  {
    addafter(Container1900000007)
    {
      part(Part10017351;"Workflow User Group Used")
      {
        SubPageLink="Document Type"=FIELD("Document Type"),
"No."=FIELD("No.");
        Visible=false;
      }
    }

and Container1900000007 is not found.

Looks like

  layout
  {
    addfirst(FactBoxes)
    {
      part(Part10017351;"Workflow User Group Used")
      {
        SubPageLink="Document Type"=FIELD("Document Type"),
"No."=FIELD("No.");
        Visible=false;
      }
    }
  }

should be working...
