### ISSUE TITLE
Unable to Show New Field in Purchase Order Subform Page Extension

### ISSUE THREAD

**Issue by AllienKiller** [microsoft/AL#5490]
Hi AL team,

I had created 2 new fields in Purchase Line ("Pack Qty" and "Packing UOM"), but these fields don't show in Purchase Order Subform. They are was presented in version 14 but in version 15 (Both Sandbox and Production, except Local) they aren't.

**To Reproduce**
1. Create new fields in Purchase Line
![image](https://user-images.githubusercontent.com/40055580/69608027-793af300-1061-11ea-9676-07ec1c5e5549.png)

2. Show new fields in Purchase Order Subform
![image](https://user-images.githubusercontent.com/40055580/69608074-9374d100-1061-11ea-8060-2a0827b171a2.png)

There are no new fields shown in Purchase Order Subform.
![image](https://user-images.githubusercontent.com/40055580/69608742-092d6c80-1063-11ea-88b3-f11d829cb430.png)

Similar steps applied on Sales Order Subform and these fields appear.
![image](https://user-images.githubusercontent.com/40055580/69608912-57427000-1063-11ea-9e14-168b0f00d241.png)

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
