### ISSUE TITLE
UploadIntoStream Limit Size

### ISSUE THREAD

**Issue by crodriguezinn** [microsoft/AL#5492]
Hi,

I'am triying to upload a big file (51 Mb) to Dynamics 365 Business Central 15.

![image](https://user-images.githubusercontent.com/44831410/69652229-a0012580-1071-11ea-9207-a83b9b3f6412.png)

I'am using the method UploadIntoStream and this issue occur:

![image](https://user-images.githubusercontent.com/44831410/69651992-3da82500-1071-11ea-953f-bb46e2140ddb.png)

The error say 350 Mb and my file has 51 Mb.

Has anyone got this error?

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
