### ISSUE TITLE
Wrong Page Type in Page Wizard

### ISSUE THREAD

**Issue by DanielSeiler** [microsoft/AL#5493]
**Describe the bug**
In the "New Page Wizard" Tool, the Page Type for NavigatePage is wrong.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to 'New AL File Wizard'
2.  Select Page Type "NavigatePane"
3. The page is not compilable
``` AL Code to reproduce the issue ```

**Expected behavior**
After configuring the page via the wizard, the page type "NavigatePage" and not "NavigatePane" should be set in the properties.

**Screenshots**
![AL_Page_Wizard_Untitled_Workspace_Visual_Studio_Code](https://user-images.githubusercontent.com/32063000/69720308-9ed40500-1112-11ea-9210-cc0575757bcc.jpg)

**5. Versions:**

 - AL Language: 4.0.194000

 - Business Central: Platform 15.0.37898.0 + Application 15.1.38071.0

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it related to a 3rd party VS code extension. Please open an issue for that specific extension.
