### ISSUE TITLE
Publish Custom API on Business Central

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/AL#5495]
Hi,

Application: Business Central On-premise 14.7 (localhost)

I created an AL Extension for the first test of API but doesn't work.

I put on the browser: http://localhost:7048/BC140/api/beta/
I see all the list of standard API, but not the custom.

Code Page:

page 79050 test_contactsentity
{
    PageType = API;
    Caption = 'testcontactsentity';
    APIPublisher = 'test';
    APIGroup = 'test';
    EntityName = 'testcontactentity';
    EntitySetName = 'testcontactentities';
    SourceTable = 5050;
    DelayedInsert = true;
    ODataKeyFields = "No.";
    
    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field(No; "No.")
                {
                    Caption = 'No.';
                }
            }
        }
    }
}

could anybody help me?

Thank you,
Roberto.

**Comment by PooyaKharamesh** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
