### ISSUE TITLE
Bug? - GB version 'Financially Voided BACS' missing from Source Code Setup

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5496]
**Describe the bug**
A field that was relied upon in the UK (GB) version was 'Financially Voided BACS' found in Table 242 Source Code Setup - this has been removed but is essential to my solution..!!  I presume this is a bug because there is still a field (37) 'Financially Voided Check' in the Source Code Setup table so if you were clearing out BACS fields you should have replaced with a 'Financially Voided Electronic Payment' field and not simply deleted a field essential for the UK market!

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

15.0.0.0

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
