### ISSUE TITLE
AL: Package does not respond

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5497]
When opening a large project, sometimes the AL:Package command does not respond, although the entire project is loaded. See enclosed zip for the issue encountered.

![image](https://user-images.githubusercontent.com/25268332/69799623-f1292a80-11d3-11ea-8168-1b120de32653.png)

[Package.zip](https://github.com/microsoft/AL/files/3901192/Package.zip)

**Comment by AndreyKorepanov** [comment]
Hi @fvet, thank you for reporting the issue. Could you please provide the code provoking the issue, otherwise it is almost impossible to detect and fix the problem.

**Comment by fvet** [comment]
I think it is due to multi-project workspaces.
When I open my workspace and no file is active, I run 'package', nothing happens.
Encountered the same when I debugged, stopped debugging, closed all editors and then run 'package' / 'publish', nothing happened.

It's not clear if I need to have at least one file in the editor open, or if I needed to set focus / select a folder / file (type?) in the explorer, to have the commands running on the proper folder / extensions.

**Comment by kalberes** [comment]
Yes you need to have an al file opened, or some known files to the project like the app.json, , rad.json ruleset etc, in order that an AL project is made active
The active project is shown in your statusbar:

![image](https://user-images.githubusercontent.com/12760483/71448037-e8763680-2736-11ea-9059-b3cd798e0483.png)

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
