### ISSUE TITLE
Codeunits license

### ISSUE THREAD

**Issue by nick-webbgh** [microsoft/AL#5499]
**Describe the bug**
The request for path /BC140/dev/apps?tenant=default&SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code 422. Reason: Your program license does not allow you to publish 'TestCode'.

**To Reproduce**
Steps and to reproduce the behavior:
1. Attempt to deploy an AL extension (specifically containing a codeunit) to this particular Business Central (On-Prem) installation. Without any codeunits (just pages and queries) works fine.

**Expected behavior**
NAV license says the following:-

Module                                                               Quantity       Included    Purchased      
-------------------------------------------------------------------------------------------------------------
Country Code: Great Britain                                1                   0               1              
Dyn365 Business Central Codeunits (each)         20                20              0              
Dyn365 Business Central Pages (100)                 100               100            0              

I'm fine with Pages. I can see further down the license data the range that is assigned and I'm successfully deploying and using some pages in an extension. However, codeunits are a puzzle? As you can see above, we have 20 included, but for what id range? There is no mention of codeunit id's in the 50,000 - 99,999 (Customer design) range anywhere in the license data? I took a flyer and tried creating a codeunit with an id of 50008 (inside the normal range), but when I try to deploy it, I get: 'failed with code 422. Reason: Your program license does not allow you to publish <my-codeunit-name>'.
Any help would be greatly appreciated?

**5. Versions:**

 - AL Language: 4.0.199169

 - Business Central: Version: Platform 14.0.29530.0 + Application 29537 (GB Dynamics NAV 14.0)
Azure AD tenant: common, Environment: Production

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
