### ISSUE TITLE
Event Subscriber in AL Visual Studio code

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#55]
Hi all,
What is the syntax of Event Subscriber in AL Visual studio code?
[EventSubscriber(ObjectType::Table, 99000763, OnAfterActionEvent,Release,SkipOnMissingLicense,SkipOnMissingPermission)]

Also for OnAfterInsertEvent I'm getting error.

It is giving me error that Invalid attribute argument syntax. Kindly suggest.
Thanks in advance.

**Comment by pmohanakrishna** [comment]
[EventSubscriber(ObjectType::Table, 99000763, 'OnAfterInsertEvent', '', true, true)]
use ''

**Comment by TinaMenezes** [comment]
Thanks a lot @pmohanakrishna !
