### ISSUE TITLE
NTLM Authentication with HttpClient

### ISSUE THREAD

**Issue by jcooper01** [microsoft/AL#550]
We need to be able to do Basic authentication and NTLM authentication with the HttpClient. I don't see a way to do that. I suppose that for Basic, we could manually construct and add the header ourselves, but that's not practical with NTLM.

**Comment by ajkauffmann** [comment]
Actually, you can do Basic Authentication with HttpClient. Here is how:

```
var
  RequestMessage : HttpRequestMessage;
  Headers : HttpHeaders;
  TempBlob : Record TempBlob temporary;
begin
  RequestMessage.GetHeaders(Headers);
  AuthText := StrSubstNo('%1:%2',Parameters.UserName,Parameters.Password);
  TempBlob.WriteAsText(AuthText,TextEncoding::Windows);
  Headers.Add('Authorization', StrSubstNo('Basic %1',TempBlob.ToBase64String()));
end
```

**Comment by jcooper01** [comment]
Right. That's what I meant by generating the header manually. However, we also need NTLM support.

On Aug 29, 2017, at 2:26 AM, Arend-Jan Kauffmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, you can do Basic Authentication with HttpClient. Here is how:

var
  RequestMessage : HttpRequestMessage;
  Headers : HttpHeaders;
  TempBlob : Record TempBlob temporary;
begin
  RequestMessage.GetHeaders(Headers);
  AuthText := StrSubstNo('%1:%2',Parameters.UserName,Parameters.Password);
  TempBlob.WriteAsText(AuthText,TextEncoding::Windows);
  Headers.Add('Authorization', StrSubstNo('Basic %1',TempBlob.ToBase64String()));
end

**Comment by StanislawStempin** [comment]
It's on our backlog, no timeframe yet.

**Comment by nareshwar** [comment]
Hi, @StanislawStempin any update on this?

**Comment by atoader** [comment]
Hi! NTLM support is available in the dev preview and will be shipped in the next major release. Please try it out and let us know what you think!

**Comment by atoader** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-usedefaultnetworkwindowsauthentication-method

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-usewindowsauthentication-method
