### ISSUE TITLE
Move a table from an extension to an other

### ISSUE THREAD

**Issue by Kichnifou** [microsoft/AL#5500]
Hi everyone (excuse me for my bad english),

Someone told me that he cannot move a table created in an extension to an other because GUID of the extension was directly save into the parameters of the table

I'd not the chance to test it by myself already, but I wonder if someone here has have to do that in the past and if he could share me his experience please ?

Thanks a lot !

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
