### ISSUE TITLE
Can't deploy App in Cloud because App is already deployed in another tenant.

### ISSUE THREAD

**Issue by EDGZTNSR** [microsoft/AL#5502]
**Describe the bug**
I can't publish my App into our Cloud Sandbox. I get the following Error Message 

> The request for path /v2.0/SandboxDev/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code 422. Reason: The extension could not be deployed because it is already deployed on another tenant.

I even tried unpublishing the Extension per Extension Mgt. Page. But now I still can't publish it.

**launch.json**
![grafik](https://user-images.githubusercontent.com/39260158/69856772-ab7d6800-128e-11ea-8d4f-7d06fbbd482c.png)

**Versions:**
Microsoft_System Application_15.0.36626.37536
Microsoft_System_15.0.36510.0
Microsoft_Base Application_15.0.36626.37711

**Comment by PooyaKharamesh** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
Or
To open a support case, you can:
Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
