### ISSUE TITLE
Table Field property "Numeric = true" is not respected by UI - entering of characters is possible as user

### ISSUE THREAD

**Issue by megel** [microsoft/AL#5503]
Table Field Property ```Numeric = true;``` does not enforce the limitation to digits in UI. 

4 fields (Code / Text) have ```Numeric = true;```, for 2 of them I added ```Numeric = true;``` also to the page. The result is:
![image](https://user-images.githubusercontent.com/15800069/69861079-db7d3900-1297-11ea-82b3-0c088567c662.png)

My Table:
```javascript
table 50130 "MyTable"
{
    DataClassification = ToBeClassified;
    fields
    {
        field(1; Code; Code[20])
        {
            Caption = 'Code (Numeric in Table)';
            Numeric = true;
            DataClassification = ToBeClassified;
        }
        field(2; Text; Text[50])
        {
            Caption = 'Text (Numeric in Table)';
            Numeric = true;
            DataClassification = ToBeClassified;
        }
        field(3; Code2; Code[20])
        {
            Caption = 'Code (Numeric in Page)';
            Numeric = true;
            DataClassification = ToBeClassified;
        }
        field(4; Text2; Text[50])
        {
            Caption = 'Text (Numeric in Page)';
            Numeric = true;
            DataClassification = ToBeClassified;
        }
    }
    keys
    {
        key(PK; Code)
        {
            Clustered = true;
        }
    }
}
```
My example Page:
```javascript
page 50130 "MyTable List"
{
    PageType = List;
    SourceTable = MyTable;
    Caption = 'MyTable List';
    ApplicationArea = All;
    UsageCategory = Lists;

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field(Code; Code)
                {
                    ApplicationArea = All;
                }
                field(Text; Text)
                {
                    ApplicationArea = All;
                }
                field(Code2; Code2)
                {
                    ApplicationArea = All;
                    Numeric = true;
                }
                field(Text2; Text2)
                {
                    ApplicationArea = All;
                    Numeric = true;
                }
            }
        }
    }
}
```

My expected behavior is - all 4 fields avoid entering of *NON-Digits*

Tested Versions:
* BC 15 US (Sandbox) `15.1.37881.38431-us`
* BC 13 W1 (CU5) `13.5.29483.0-W1`

My Test Apps:
[IsNumeric.BC15.zip](https://github.com/microsoft/AL/files/3904696/IsNumeric.BC15.zip)
[IsNumeric.BC13.zip](https://github.com/microsoft/AL/files/3904697/IsNumeric.BC13.zip)

**Comment by megel** [comment]
@PooyaKharamesh what is the state of this issue?

**Comment by megel** [comment]
Are there any new findings on this topic?

**Comment by atoader** [comment]
Hi @megel! I apologize for the delay. As the main purpose of this repository is to handle issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central, issues pertaining to other parts of the product might not get the needed level of priority.

In our FAQ for the repository, we suggest that you open a support case or file a bug in Collaborate for this kind of issues. We will try to investigate it before the Wave 1 release.
