### ISSUE TITLE
The request for path /[...]/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code 422. Reason: This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.

### ISSUE THREAD

**Issue by HennieBink** [microsoft/AL#5504]
Version 14 OnPrem side-by-side development.

When publish apps (several apps) we get the following error:

The request for path /[...]/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code 422. Reason: This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.

Extension Management show only 4 default apps. 
Apps are published and only visible in the SQL-table

**Comment by atoader** [comment]
Hi! Does the NavApp table contain any extensions with the same identity? Have you by any chance published these extensions using the PowerShell commands?

**Comment by TranLyTuong** [comment]
Dear HennieBink,
You can try command Start-NAVAppDataUpgrade with parameter is <AppName>. After that, try publish apps again.

![image](https://user-images.githubusercontent.com/58070142/70202859-994b7000-174d-11ea-8ccd-024892c031f2.png)

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
