### ISSUE TITLE
SchemaUpdateMode=recreate&DependencyPublishingOption=default failed with code 422. Reason: Could not install the extension [..] on tenant default due to the following error: Error code: 85132273

### ISSUE THREAD

**Issue by HennieBink** [microsoft/AL#5505]
Can't publish app after changing the key of a table.

Message:
SchemaUpdateMode=recreate&DependencyPublishingOption=default failed with code 422. Reason: Could not install the extension [..] on tenant default due to the following error: Error code: 85132273

"platform": "14.0.0.0",
"application": "14.0.0.0",
"runtime": "3.2"

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by HennieBink** [comment]
This is an AL Compiler issue. We work in AL and we can't publish this from VS Code.

**Comment by HennieBink** [comment]
Ok, i've figured out a solution for this, although i'm not exactly sure as to why this is needed to resolve this issue.

Whenever you get error code 85132273, it means you got the real error right before that and you tried to publish it again.

Access the database using SQL Server Management Studio and execute the following query:

DELETE
  FROM [<your_database_name>].[dbo].[NAV App Installed App]
  Where Name = [<your_app_name>]

You should be able to publish it again.

**Comment by HennieBink** [comment]
Real error is:

The following C/AL functions are limited during write transactions because one or more tables will be locked. Form.RunModal is not allowed in write transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed. Report.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'Report.RunModal(...,FALSE)' is allowed. XmlPort.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'XmlPort.RunModal(...,FALSE)' is allowed. Use the COMMIT function to save the changes before this call, or structure the code differently.

This is possibly caused by some datachanges while publishing. I some cases it worked to switch off some Flows (Power Automate).

**Comment by HennieBink** [comment]
The error _"The following C/AL functions are limited during write transactions because one or more tables will be locked."_ occurs when you make a change in fields of tables.

Using "schemaUpdateMode": "Recreate" is a solution. App wil publish again. But data is lost.

**Comment by dkartiq** [comment]
> Ok, i've figured out a solution for this, although i'm not exactly sure as to why this is needed to resolve this issue.
> 
> Whenever you get error code 85132273, it means you got the real error right before that and you tried to publish it again.
> 
> Access the database using SQL Server Management Studio and execute the following query:
> 
> DELETE FROM [<your_database_name>].[dbo].[NAV App Installed App] Where Name = [<your_app_name>]
> 
> You should be able to publish it again.

It works. thanks.
