### ISSUE TITLE
🛑🛑🛑Please contact customer support🛑🛑🛑

### ISSUE THREAD

**Issue by antoniotrives** [microsoft/AL#5506]
Describe the bug
When you use the field SystemId in a Query the client crashes with no information. 
Since Id is marked for removal, how long can we still use Id in future versions?
To Reproduce
Steps and to reproduce the behavior:
Created a simple query that returns the Customer SytemID, Name and Code.
Expected behavior
Exposing SystemId in a query should not make the web client crash.
Screenshots / Code Example
query 70104229 KecCusSel2
{
     elements
    {
        dataitem(Customer; Customer)
        {
            column("SytemId"; "SystemID")
            {
            }
            column("Code"; "No.")
            {
            }
            column(Name; Name)
            {
            }
        }
    }
}

5. Versions:
AL Language: 4.0.199169
Business Central Version: Platform 15.0.37867.0 + Application 15.0.36626.37934

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
