### ISSUE TITLE
This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.

### ISSUE THREAD

**Issue by HennieBink** [microsoft/AL#5509]
AL Extension Version: 4.0

"platform": "14.0.0.0",
"application": "14.0.0.0",
"runtime": "3.2"

Get-NAVAppInfo -ServerInstance [...] -Tenant default -Name [...] -TenantSpecificProperties

Id                     : [...]
Name                   : [...]
Version                : 1.0.1.0
Publisher              : [...]
ExtensionType          : ModernDev
Scope                  : Tenant
Compatibility Id       : 0.0.0.0
Developer Tenant ID    : default
Is Installed           : **True**
Extension Data Version : 1.0.1.0
Sync State             : Synced
Is Published           : **False**
Package Id             : [...]

Uninstall-NAVApp -ServerInstance [...] -Name [...] -Tenant default -Version 1.0.1.0
**Error:  Uninstall-NAVApp : Cannot find the extension '[...]' because it is not published.**

Publish-NAVApp -Path "[...]_1.0.1.0.app" -ServerInstance [...] -PackageType Extension -Scope tenant -SkipVerification
**Error: Publish-NAVApp : This Extension cannot be published as it has the same Publisher, Name, and Version as a previously published Extension.**

Extension is not visible in Extension Management.

Problem: 
1) Cannot Publish extention because same Publicer/Name/Version
2) Cannot Uninstall becasuse extension is not published
3) Can publish an exention with higher version but can't install this. (because the tenant default already uses a different version of it.)

Same problem for all other apps in this envoironment. Customer has planned LIVE next week. Urgent issue.

**Comment by HennieBink** [comment]
Solution (must be done for every app): 

1) In SQL-server (ssms) change **Scope** of the app in table "**NAV App**". Set Scope to 0. (App will be Global in stead of Tenant)

2) Restart BC Service
3) Extension is now visible in Extension Management
4) Uninstall-NAVApp -ServerInstance [...] -Name [...] -Tenant default 
5) Unpublish-NAVApp -Name [...] -ServerInstance [...]
6) Publish the app again from VSCode. 

I like to know what causes this problem. Any comment is appreciate.

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
