### ISSUE TITLE
Change the behavior of FieldSelection.Open in Field Selection codeunit

### ISSUE THREAD

**Issue by MortenRa** [microsoft/AL#5511]
We have previously used Page 7702 to enable the user to select among fields. In the original solution the selection list would be opened with the cursor on the last selected field.
When using the new Field Selection codeunit, the cursor will always be placed on the first entry in the presented list regardless of the passed field record. 

![1](https://user-images.githubusercontent.com/28138717/69959198-da9e0e80-1506-11ea-8d98-5805e391719b.jpg)

 

Please change the behavior of FieldSelection.Open so that the cursor will be placed on the record that is passed as parameter if this record falls within the filters. If the record passed is not initiated or falls outside the filter, the cursor should be on the first entry.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
