### ISSUE TITLE
Missing complete definition of the field relations in the standard table Table Relations Metadata.

### ISSUE THREAD

**Issue by MortenRa** [microsoft/AL#5512]
In our extension we allow the user to input and lookup data across all tables using RecordRef and Fieldrec. In order to do so in a transparent way, we need to be able to validate field relations the same way as it happens in other parts of the solution.

Unfortunately, it is not possible to find the complete definition of the field relations in the standard table Table Relations Metadata.

E.g. if you look at the data regarding Table 37 Sales Line Field 5403 Bin Code, you find this:
![2](https://user-images.githubusercontent.com/28138717/69959882-619fb680-1508-11ea-8d3c-945194c7f656.jpg)

However, if you look at the Tablerelation property for field 5403 it looks like this
![3](https://user-images.githubusercontent.com/28138717/69959931-8300a280-1508-11ea-8ed0-4356742027e6.jpg)

You will notice that it is only the conditions on the left which are documented in the Table Relations Metadata, whereas the Table Filter on the right is not mentioned. 

Hence the documentation in Table Relations Metadata is incomplete, and we have therefore created some logic for extracting the full set of relation data from a text object file containing all tables and place it in a supplementary table (SCB Table Relations Data). 

Below is the resulting data related to the Bin Code example. The data which completes the documentation is marked with red:
![4](https://user-images.githubusercontent.com/28138717/69959967-94e24580-1508-11ea-83c8-16c71e586dcc.jpg)

The same issue exists regarding the calcformula for flowfields; the table filters used when doing drill down to the underlying data, can only be found in the text object files. As example below, the definition for the Net Change field on Item table:

![5](https://user-images.githubusercontent.com/28138717/69961361-fe178800-150b-11ea-8f66-d2934a5517c3.jpg)

Moving to VS-code and extensions the text-file solution is no longer viable.

•	Is there a way to extract the Table Filter data in the current version of BC?
•	If not, could you add some method or system table that will expose this data?  

This is relevant both for Cloud and On-Prem

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by navdotnetreqs** [comment]
Still needed in 2024..
