### ISSUE TITLE
Debugger doesn't break on breakpoint placed in .DAL

### ISSUE THREAD

**Issue by jwynndev** [microsoft/AL#5513]
**Describe the bug**
If I place a break point in standard BC code (.dal files). Then "Debug without publishing". The break points I have defined get ignored. This occurs in SAAS sandboxes. I have tested in Great Britain and Norway tenants. I have tested with version 15 and 15.1 tenants.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open VS Code.
2. AL:Go!
3. Set Launch.json like this. Replace tenant and sandbox in the below:

``` 
{
    "version": "0.2.0",
    "configurations": [
        {
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "name": "NO",
            "type": "al",
            "request": "launch",
            "breakOnError": true,
            "breakOnRecordWrite": true,
            "sandboxName": "YOUR SANDBOX",
            "tenant": "YOUR TENANT",
            "dependencyPublishingOption": "Ignore"
        }
    ]
}
 ```
4. Create codeunit.
 ```
codeunit 50100 asd
{
    trigger OnRun()
    begin

    end;

    var
        salesinvlist: page "Sales Invoice List";
}
 ```
5. Go to definition of "Sales Invoice List".
6. Set Break point to first line of OnOpenPage trigger, Line 693
7. "Debug without publishing"
8. Client starts
9. Open Sales Invoice List. 
10. **Debugger does not break**

**Expected behaviour**
When opening Sales Invoice List the Debugger should break on the break point defined in Sales Invoice List page Line 693 OnOpenPage trigger.

**Screenshots**
![image](https://user-images.githubusercontent.com/24782331/69975219-b0f0e180-151e-11ea-907f-e0f819fa3cb3.png)

**5. Versions:**

 - AL Language:  Version: 4.0.199169

 - Business Central: Version: Platform 15.0.38375.0 + Application 15.0.36560.0

**Comment by jwynndev** [comment]
@PooyaKharamesh Is there any news on this? Were you able to replicate the issue?

**Comment by kalberes** [comment]
Debugging the base application on sandboxes has been disabled with version 15.

**Comment by jwynndev** [comment]
> Hitting breakpoints on the base application on sandboxes has been disabled with version 15.
@kalberes Thank you Kálmán, do you have a source for this? I'v not read it anywhere.

**Comment by kalberes** [comment]
If you have access to yammer it was announced On April 3d.
https://www.yammer.com/dynamicsnavdev/threads/89028034289664

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
