### ISSUE TITLE
new Event C\AL  not visible in AL ?

### ISSUE THREAD

**Issue by stijn9830** [microsoft/AL#5514]
**Describe the bug**
I'am not sure if this is a bug, but I hav a problem.
Working for a BC140 Cu5 Customer.  in T1315 I created an extra event publisher to add/fill up some fields in this table. 
But in my app, I can not subscribe to this event?
I re- download the symbols, but in AL , I am not able to subscribe

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**
I was hoping to make this event and go further in AL?
I know I can ask for new events, but then I have to wait until the next release, minimum

**Screenshots**
![image](https://user-images.githubusercontent.com/56073675/69999550-34c7bf80-1559-11ea-998c-12693370b8ab.png)

![image](https://user-images.githubusercontent.com/56073675/69999565-3b563700-1559-11ea-8408-10ea0a893c1f.png)

**5. Versions:**

 - AL Language:  4.0.199169

 - Business Central: 14 cu 5

**Comment by NKarolak** [comment]
Did you already [generate symbols for your C/AL changes](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side#get-started-generating-symbols-and-compiling-all-objects)?

**Comment by stijn9830** [comment]
hi;

I did generate symbols
after that, I did download symbols in VS code
but still I can not subscribe

![image](https://user-images.githubusercontent.com/56073675/70031153-ecd18880-15aa-11ea-9fc0-355516750b62.png)

**Comment by PooyaKharamesh** [comment]
If you already generated the symbols it seems that the new symbol pack does not contain the new event. in this case let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
