### ISSUE TITLE
Business Central Cloud Instance Database Size Limit

### ISSUE THREAD

**Issue by Saran-il** [microsoft/AL#5515]
Hi,

As my Customer wants to know the BC Cloud instance database size limits, Is there any restrictions from Microsoft on the Database size. Will there be any additional charges after exceeding say few 100 GBs. 

Thanks in advance.

**Comment by PooyaKharamesh** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
Or
To open a support case, you can:
Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
