### ISSUE TITLE
Control Add-In not working anymore after Rapid Application Publish 

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#5516]
- AL Extension Version: 4.00.199169

- Server Version: Version: W1 15.1 (Platform 15.0.37898.0 + Application 14.0.29530.0)

Hi,

Whenever you do a Rapid Application Publish of an object which contains a Control Add-In, a permission error is thrown:

![image](https://user-images.githubusercontent.com/48217797/70045542-92ddbc80-15c4-11ea-84ec-e10608dd33b2.png)

After a full publish the Control Add-In is rendered fine.

**Comment by thpeder** [comment]
Hi @daansaveyn,
Sorry for the late reply but I have not been able to reproduce the issue.
Could you tell me some more about how you got to that.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by daansaveyn** [comment]
> Hi @daansaveyn,
> Sorry for the late reply but I have not been able to reproduce the issue.
> Could you tell me some more about how you got to that.

Just create/use a page with a javascript control add-in.  Do a full publish, then change something in the page and do a rapid application publish. You'll notice the control add-in throws an error similar to the one shown above.

**Comment by atoader** [comment]
@daansaveyn can you reproduce the issue on the latest release of Business Central?

**Comment by daansaveyn** [comment]
> @daansaveyn can you reproduce the issue on the latest release of Business Central?

I'll give it a try and provide you with some feedback.
