### ISSUE TITLE
Buy-From Vendor Name/Sell-to Customer Name - OnLookUp does not validate the Cust/Vend No.s

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/AL#5517]
Hello,
when you create for example a sales order and select the sell-to customer name by the lookup.
It does not validate the "Sell-To Customer No.".
So in that case the "Bill-To Customer No." does not have a value.
When you enter the Customer No. manually to the field "Sell-To Customer Name". It validates the Sell-To Customer No.

So this bug is the same for the purchase ones.

Please fix it!

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
