### ISSUE TITLE
Wave 2 - Base app translation TableCaption

### ISSUE THREAD

**Issue by fmoric** [microsoft/AL#5518]
**Describe the bug**
Translating base app in wave 2 with XLIFF file does not update TableCaption.
The app is showing translation for all objects, but TableCaption far all tables is showing english..

I have checked xlif for caption translation, and it is there.

**To Reproduce**
1. Tanslate base app whit XLIFF
2. Try Navigate or print TableCaption

``` AL Code to reproduce the issue ```
Message(GLEntry.TableCaption).

**Expected behavior**
TableCaption to be translated...

**Screenshots**
![image](https://user-images.githubusercontent.com/18283753/70056072-1f937500-15db-11ea-99ab-1d4280a337cc.png)

**5. Versions:**

 - AL Language: 
4.0.194000
 - Business Central:
Application Build 15.1.38071 Platform Build 15.1.37898

**Comment by thpeder** [comment]
Hi @fmoric,
Thank you for reporting the issue!
You should find in the coming update that TableCaption will use the translations.

**Comment by tduy80** [comment]
Hi all,
I installed a instance of BC150 (Dynamic 365 Business Central Wave 2 Released) on my server with Docker Container Installation and it run on.

Then, I have built Base Application from source code that exported from Docker Container with custom version and it included my custom translated XLF file "Base Application.en-US.xlf" (the target content are my language terms (not support by Microsoft yet) and target language ="en-US" is still default). However, I deployed this Base App and it is published and installed then it is not fired change on the UI of web browse.

In another case, I tried to replace target language to "fr-FR" and I keep my target content, then I rebuilt and re-deploy this (ít is ok) and then I select France language on Dropdown of menu My Settings and it show correct in France language but it's not show my language terms.

So, how to deploy a language pack to BC150 that not support by Microsoft for countries yet?
(both On-Primes and Sandbox environment of On-Cloud)

Please, help me!
Thank you so much.

**Comment by tduy80** [comment]
> checked
Hi, 
What is your target language? I also translate my xlf file to Vietnamese language but it's not show.
Thanks
