### ISSUE TITLE
Cannot upgrade BC140 C\AL database to AL BC150 due to destructive changes

### ISSUE THREAD

**Issue by RobertdeRoos** [microsoft/AL#5519]
We have converted our solution (with lots of changes in standard NAV objects) from C\AL to AL. 
We then merged the converted objects with the new BC150 base application objects and resolved all errors. We have successfully build the new base application app.

We followed the guide [](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application) to upgrade our BC140 database but stranded on Task 6: Synchronize the tenant.
When running step 2, Synchronize the tenant with the application database, we get the error Sync-NAVTenant : The schema synchronization may result in deleted data. The following destructive changes were detected:
and then a list of all tables!

How can we resolve this?

- AL Extension Version: 4.0.199169
- Server Version: 15.0.36117

**Comment by atoader** [comment]
This repository is dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by RobertdeRoos** [comment]
Hi Alexandru,

This is clearly an upgrade problem caused by Microsoft.
Doesn’t the upgrade fall under the developers tools?

Kind regards,

Robert de Roos
Developer/Consultant


[K3 Business Technologies logo for email signature]

m +31 628 200 721
t +31 152 516 555

www.k3btg.com<http://www.k3btg.com/>
