### ISSUE TITLE
Missing attribute "Locked=true" on FormatString-Labels

### ISSUE THREAD

**Issue by StHillmann** [microsoft/AL#5521]
**Describe the bug**
There are several labels that are used as FormatString not locked for translation.
Within the excel-list you can find this labels within the xlf-file.

[MissingLocked.xlsx](https://github.com/microsoft/AL/files/3921596/MissingLocked.xlsx)

On top of this, there are Format-String-Labels within the **german** version, that have been translated and are giving errors within the application.
For example:
- Report Auto Posting Errors - NamedType Text023Txt
  source: &lt;Month Text&gt;
  target: &lt;Monatstext&gt;
- Report Vendor Pre-Payment Journal - NamedType E023Err
  source: &lt;Month Text&gt;
  target: &lt;Monatstext&gt;

**Expected behavior**
From my point of view, FormatString-Labels should be locked for translation.

**5. Versions:**
 - AL Language: 4.0.199169
 - Business Central: 15.1.37881.38263

**Comment by StHillmann** [comment]
Business Central version is: Business Central: 15.1.37881.38262

**Comment by qutreson** [comment]
We believe that this issue has been fixed. Please log a new issue if you can still reproduce it.
