### ISSUE TITLE
AL Report - Placeholder property

### ISSUE THREAD

**Issue by yannstlo** [microsoft/AL#5523]
Let's start with the issue at hand... 

When creating a .AL report for use with a WordLayout, the column names are displayed in Word an can create layout issues when the actual data that will be displayed is much smaller than the name that the column received in AL.

When creating a report in AL and defining its dataset, it would be great to have a property for each of the column that would be used when creating the actual .docx or .rdlc.

For example, if I have a column called "FirstRequestedDeliveryDate" but the date field will only ever be displayed as 01/01/2020, it creates layout issues in word if I try to place that field in a small text box or even more so within a table.

I understand that this can be implemented in AL but would the word XML Mapping or RDLC support this?

Thanks for the consideration.
Yann

**Comment by nndobrev** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
