### ISSUE TITLE
[IP Security] ShowMyCode = false shows my code anyway

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5525]
**Describe the bug**
When debugging or going to a definition for an app I am depending to, vscode shows me all the code in the object.dal. 
Even local procedures or internal procedures.

**To Reproduce**
Create a First App with a codeunit that exposes a global procedure, and has a local and an internal procedure.

Create a second app with an action in a page that calls the global procedure in the codeunit of the First App.

Put a breakpoint on the call of the global procedure in the action of the page of the second app
or
Go to the definition of the procedure with F12

=> You can see all the object code

 ``` AL Code to reproduce the issue ```

First app (set showMyCode = false in app.json)
```
codeunit 51100 SomeCodeunit
{
    procedure MyGlobalProcedure()
    var
    begin
        DoMyLocalProcedure();
    end;

    local procedure DoMyLocalProcedure()
    var
    begin
        Message('This Should not be visible');
    end;

    internal procedure MyInternalProcedure()
    var
    begin
        Message('This should not be visible');
    end;
}
```
Second App (make a dependency with the first app)
```
page 50100 MyPage
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    actions
    {
        area(Processing)
        {
            action(ActionName)
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    SomeCodeunit: Codeunit SomeCodeunit;
                begin
                    SomeCodeunit.MyGlobalProcedure();
                end;
            }
        }
    }
}
```

**Expected behavior**
I should not be able to see all the code, maybe only global procedures ?.
Also, (I think )I should be able to see internal procedure only if I give the right to Second App in app.json of my FirstApp by specifying "internalVisibleTo". Anyway, I though that just setting showMyCode = false must hide my code.

As said in MS Documentation:
![image](https://user-images.githubusercontent.com/29598240/70311860-bac25f80-1812-11ea-95cd-bfe181f93063.png)

**Screenshots**

**Debug**:

![image](https://user-images.githubusercontent.com/29598240/70312191-64a1ec00-1813-11ea-8d4d-46b502eb7ed5.png)

![image](https://user-images.githubusercontent.com/29598240/70312202-6bc8fa00-1813-11ea-9852-f18d0718ca31.png)

![image](https://user-images.githubusercontent.com/29598240/70312217-71bedb00-1813-11ea-9e41-aac817302ae1.png)

**Go To Definition**

![image](https://user-images.githubusercontent.com/29598240/70311977-fa894700-1812-11ea-9ae2-cf779ba48608.png)

![image](https://user-images.githubusercontent.com/29598240/70311957-ec3b2b00-1812-11ea-86df-5fc815bd1111.png)

**5. Versions:**

 - AL Language: 4.0.199169

 - Business Central: W1 15.1 (Platform 15.0.37865.38662 + Application 15.1.37881.38709)

**Comment by kalberes** [comment]
Hi,

Have you been working in one workspace the application with Page 50100 has a dependency (a project reference) to the app with SomeCodeunit.
a. If you are in the same workspace, you own both projects. References for SomeCodeunit will be resolved from the referenced project and not the symbols, thus this is expected behaviour.
b. For debugging it is similar. Code that you have published from VSCode - these are called per tenant developer extensions -  even if marked as showmycode false should be able to be debugged.

**Comment by JulienDecottignies** [comment]
Hi,

I'm working in two differents instances of vscode, so two workspaces, but both of these apps are deployed using vscode, not powershell.
So if I understood correctly, if I deploy my "motherapp" with Powershell. My 50100 page must not see the code inside the codeunit it depends on.

Thanks for your answsers!

**Comment by kalberes** [comment]
Yes, it should be like that.

**Comment by atoader** [comment]
@JulienDecottignies can we close this issue?

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
