### ISSUE TITLE
Wave 2 - W1 - On Premises: Debugging (with F5) leads to "HTTP Error 404.0 - Not Found"

### ISSUE THREAD

**Issue by tbebekis-ax** [microsoft/AL#5526]
I've an on-premises installation of a W1 Dynamics.365.BC.Spring2019.29537.W1.DVD.

I'm trying the "[Building Your First Sample Extension With Extension Objects...etc](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example)" 

When I hit F5 I get "HTTP Error 404.0 - Not Found" in the browser (Firefox).

The VSCode, in the output window, prints...
	"Sending request to http://localhost:7049/BC150/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default"

...but in the browser's address bar I get
	http://teo5:8080/BC140/Webclient/?page=22&tenant=default&debuggingcontext=20217bca-23de-4e4f-aa39-6f933d4fcb7d&sk=20217bca-23de-4e4f-aa39-6f933d4fcb7d

Looking at the Administration Tool I've found that the Client Services | Web Client Base URL was "http://TEO5:8080/BC140/Webclient/".

Changed that to http://localhost:8080/BC150/ and tried again. Same results: Error 404 and http://teo5:8080/BC140/Webclient/...etc in the address bar

Correcting manually the address in the browser's bar displays the right page.

Here is my launch.json

NOTE: Although ["port" is marked as optional in documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files) I was not able to "AL: Download symbols" without that.

```{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "launch",
			"name": "BCLocal_01",
			"server": "http://localhost:8080/",
			"serverInstance": "BC150",
			"authentication": "Windows",
			"tenant": "default",
			"startupObjectId": 50112,
			"startupObjectType": "Page",
			"port": 7049,
			"breakOnError": true,
			"launchBrowser": true,
			"enableLongRunningSqlStatements": true,
			"enableSqlInformationDebugger": true
		}
	]
}```

And here is my app.json

```{
  "id": "4e515c9a-db1e-45c9-9cc5-ed3a62652cb1",
  "name": "Local01",
  "publisher": "Microsoft",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",

  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "1.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
		"from": 50100,
		"to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://Local01.com/help/",
  "showMyCode": true,
  "runtime": "4.0"
}```

Any suggestion?

**Comment by tbebekis-ax** [comment]
Well, restarting the service, after correcting the **Client Services | Web Client Base** URL from http://TEO5:8080/BC140/Webclient/ to http://localhost:8080/BC150/ was not enough.

Restarting the machine was the solution. Now hitting F5 displays the browser with the right URL. No more 404 error.

But still SOAP Services and ODATA Services point to wrong Base URL. I guess I have to correct those as well.

**Comment by atoader** [comment]
Hi @tbebekis-ax ! Thank you for filing the issue! It seems you have already found the problem. Should we close this thread?

**Comment by tbebekis-ax** [comment]
I'm ok, I solved my problem and sure we may close this thread.

But, as I write above...

1.  there is a problem with the BC setup application (Wave 2) and 
2.  the "port" in the launch.json seems to be mandatory, contrary to what the documentation says about.

In an on-premises installation (the Demo option) the **Base URL** of the Client Services, SOAP Services and OData Services is wrong as it includes the "BC140" string while the correct is "BC150". 

Thanks
Theo
