### ISSUE TITLE
How to add Vietnamese Language to show and select it in My Settings menu

### ISSUE THREAD

**Issue by tduy80** [microsoft/AL#5527]
Hi all,
I'm working about Multi Language on Dynamic 365 Business Central Wave 2 Released
I tried translate target content to Vietnam and target language is default language (en-US) in my file translated.xlf and I published this extension on-primes of Version: Platform 15.0.36510.0 + Application 15.0.36560.0 and it shown on my web browse but I cannot select Vietnamese Language in My Settings menu because it not existing. I can select only Vietnamese in Region. However it 's incorrect for my case.

For Sandbox environment of Version: W1 15.1 (Platform 15.0.37865.38374 + Application 15.1.37881.38071), it is not show any my terms.

So, how to add Vietnamese Language to Dynamic 365 Business Central Wave 2 (both On-Primes and Sandbox environment of On-Cloud)?

Please, help me!
Thank you so much.

**Comment by atoader** [comment]
Hi! The configuration of the languages that are available in the settings menu, is completely decoupled from the applications that are published. Unfortunately, we cannot provide further assistance on this forum.

As stated in our readme, the main purpose of this repository is to track issues regarding the AL compiler and the Developer Tools for the latest developer preview environment for Dynamics 365 Business Central. 

As this is not related to the development environment, my recommendation is to post your question:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
