### ISSUE TITLE
App cannot be publish as soon as there is a protected array variable in the app

### ISSUE THREAD

**Issue by MattiLE** [microsoft/AL#5528]
**Describe the bug**
When you set an array variable to protected, you can no longer publish the app. The following error is displayed during the publish process: 
"This program location is thought to be unreachable. Array" 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new AL Project with AL: Go
2. add the following lines to file HelloWorld.al
      protected var
        TestArray: array[4] of Decimal;
3. press F5 to publish the app 

``` 
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('App published: Hello world');
    end;

    protected var
        TestArray: array[4] of Decimal;

}
 ```

**Expected behavior**
I expect that I have access to the protected array variable in a page or table extension. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48024891/70422883-c315d700-1a6c-11ea-9997-b674351cbe57.png)

**5. Versions:**
 - AL Language: 4.0.199169
 - Business Central: 15 RTM

**Comment by atoader** [comment]
Thanks for the good repro! I've marked it as a bug.

**Comment by qutreson** [comment]
This issue should be fixed in our latest developer previews.
