### ISSUE TITLE
Txt2AL: Empty strings in OptionCaptionML result in no options in the list

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#553]
An option string like the following: ' ,Once,All' gets converted to OptionCaptionML=ENU='" ",Once,All'. Apparently, the NAV engine treats this as an empty value and displays no options. It looks like Txt2AL should use the following format:
OptionCaptionML=ENU=' ,Once,All'.

**Comment by StanislawStempin** [comment]
This looks like a bug in the converter, thanks for reporting.
