### ISSUE TITLE
The file could not be uploaded because it was too large

### ISSUE THREAD

**Issue by Phfo** [microsoft/AL#5532]
**Describe the bug**
Using 'upload' of a 32 MB file gives following error : 
The file could not be uploaded because it was too large. The maximum file size that can be uploaded is 2047 MB.

**To Reproduce**
Make code like described below.
Change setting 'Max Upload Size' in configuration to maximum value - same result

``` AL Code to reproduce the issue ```
if not Upload(Text001, '', Text002, clientfilename, serverfilename) then
            error(Text003, serverclientfilename);

**Expected behavior**
File is not exceeding limitation, so it should be uploaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/24912240/70428688-58b66400-1a77-11ea-9a62-bf543b2fe5b0.png)

**5. Versions:**

4.0.199169 

 - Business Central:
15.0.37898.0

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by Phfo** [comment]
Hi Alexandru

Ok, but I think it is a bug ?

Best regards
Philip Foncke

Van: Alexandru Toader <notifications@github.com>
Verzonden: dinsdag 10 december 2019 7:32
Aan: microsoft/AL <AL@noreply.github.com>
CC: Philip Foncke <philip.foncke@sde.be>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/AL] The file could not be uploaded because it was too large (#5532)


This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
Business Central Community<https://community.dynamics.com/business/f/758>
mibuso forum<https://forum.mibuso.com/categories/nav-three-tier>
Dynamics User Group<https://dynamicsuser.net/nav/f/developers>
