### ISSUE TITLE
How Do I change the permission Set programmatically

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#5533]
I want to develop a system in which permission sets of user will be changing automatically based on some conditions.

i want to insert/delete permission sets of users programmatically, so that it happen at run time.

not all user will be super user.

how can i do that ?

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
