### ISSUE TITLE
Translation Compatibility

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#5535]
Hi all,

We have developed a document report extension in AL and have a customer project where we want to use those. The customer needs to have the following languages on those document reports
 
-           English
-           Spanish
-           Czech
-           French
-           Mandarin
-           Italian
-           German
 
We have the following layers for the application:
-           In C/SIDE we did have a problem with different code pages if we import languages in the NAV standard objects as CaptionML. It was previously recommended to use Multilanguage files in this case and we were warned about mixing CaptionML and Multilanguage files.
 
-           We’re using XLIFF files for our document report app, which we can translate so that shouldn’t be a problem.
 
-           The customization app does not use XLIFF files because those are very hard to handle without proper tools. Instead we use CaptionML.
 
So my questions are:
Is it possible to use MultilanguageFiles for C/SIDE / NST, XLIFF for one extension and CaptionML for another or what is the recommended path?
 
And how do we go about getting the Multilanguage files for the aforementioned languages?
 
What about translations in Mandarin for C/SIDE objects of the NAVDACH localization?

**Comment by atoader** [comment]
Hi! Just to provide more context for anybody coming later.
1. For any C/AL code base, the only translation mechanism is to use TXT files as described here https://docs.microsoft.com/en-us/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files
2. For any AL application, the translation can be done either using multi-language properties (CaptionML, ToolTipML etc) or XLIFF files, or a combination of both. If you have the TranslationFile feature disabled, you can only use multi-language properties.
If you have the TranslationFile enabled, then the following happens:
- If you have a construct that has a multi-language property, then that property will be used.
- If you have a construct that has a Caption/ToolTip (single-language), then an entry will be generated in the XLIFF file. This entry can be translated.

Does that answer your question?

**Comment by JulianTillmann** [comment]
@atoader 
thanks, but the question is not how to do it, but if different ways would work side by side. 

you already answered my question at Directions EMEA, but the speed in which questions are answered here is a bit disappointing

**Comment by atoader** [comment]
Our goal is always to provide the most value to our community, but to achieve this, we constantly have to balance between working on new features for the developer tools, fixing bugs, and engaging on GitHub. 
The different ways would work side by side, that is point number 2. Have you tried it and found the behavior confusing or did it produce incorrect results?

**Comment by JulianTillmann** [comment]
I know it's difficult for you guys, but it's difficult for us as well. Our customers want to have their solutions, the support tells us to go to GitHub and there we have to wait for months to get a response. 

I started the issue before we talked in Vienna, we didn't have any difficulties yet.
