### ISSUE TITLE
Need to show list of Keys

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#5538]
While developing in AL, we need list of index (keys) to be listed.  See below for example

**Comment by frobiii** [comment]
as a workaround when you have a page fpr the table you can use intelliSense in SourceTableView = sorting() property, then you get a list auf key names and fields. BTW: That's the solution i want for tables / general al development

**Comment by mynavblog** [comment]
Hi Rama, 
When you got to definition of the table (F12 on the variable) then you will see the Base App code. and there are keys as well. In the below example you can see the list from Customer Table

![2019-12-12 09_57_29-● HelloWorld al - ALProject27 - Visual Studio Code](https://user-images.githubusercontent.com/37371997/70697475-dc659000-1cc5-11ea-97f6-96844d71c145.png)


![2019-12-12 09_54_40-Customer dal - ALProject27 - Visual Studio Code](https://user-images.githubusercontent.com/37371997/70697413-c0fa8500-1cc5-11ea-84c8-7897d46c5675.png)

**Comment by Rama-M** [comment]
Hi,

This will not help, when you type methods like SETCURRENTKEY we need this selection from a list

Thanks

Rama Mathanmohan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by atoader** [comment]
Hi!  Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
