### ISSUE TITLE
[Feature Request] Support Custom Shortcuts on the web client

### ISSUE THREAD

**Issue by FabianBigler** [microsoft/AL#5540]
Our customers would like to have custom key bindings on the browser.
They would like to have the same behaviour as on premises (i.e. having the ability to define any keyboard shortcut). It would be nice if you could even define different key bindings to each device (desktop, tablet and mobile).

vjekob has built a ControlAddin for keyboard shortcuts [here](https://github.com/vjekob/controladdin-keyboardshortcut). However, I am not happy with it since it is directly accessing DOM elements (which is quite prone to futures changes).

So instead of building something hacky I am asking you:
Are you planning to implement this feature in the near future?

**Comment by bjarkihall** [comment]
Are you talking about:
https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/full-keyboard-shortcut-support

**Comment by FabianBigler** [comment]
Yes, exactly. Meanwhile it has been implemented.
