### ISSUE TITLE
Javascript AddIn is crashing in Wave 2

### ISSUE THREAD

**Issue by martonnagy** [microsoft/AL#5542]
Dear Dev Team,

the following Javascript code is crashing in Wave 2 but was working perfectly fine in BC14
Our guess in the Element is not called controlAddIn any more.

`function LoadBase64(Base64) {
    if (Base64 == '')
        Base64 = Base64Temp;
    document.getElementById('controlAddIn').innerHTML = '<img src="'+Base64+'" width="auto" height="400px;" style="display: block; margin-left: auto; margin-right: auto;">';
}`

Can you advise?

Cheers!

**Comment by bjarkihall** [comment]
The div element still has the "controlAddIn" id in BC15.
Check the section "Image loading errors" in the following link:
[img documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img )
Make sure your Base64 argument isn't empty or corrupted, it should start with something like "data:image/png;base64,", given it's a png format etc.

**Comment by martonnagy** [comment]
Hi @bjarkihall,

thanks for the info, we'll have a look

Cheers,
Marton

**Comment by atoader** [comment]
If you are still encountering this issue we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
