### ISSUE TITLE
Record context menu

### ISSUE THREAD

**Issue by IvoMol** [microsoft/AL#5543]
If you stay cursor on Record variable, table fields are shown and primary key fields are marked with asterix:
![PK](https://user-images.githubusercontent.com/17826638/70608053-d2795980-1bff-11ea-9929-f115db810f3f.JPG)

It would be nice if the field type FlowField and FlowFilter were marked likewise (exlamation mark, question mark or another character):
![FF](https://user-images.githubusercontent.com/17826638/70608186-fe94da80-1bff-11ea-8ec0-5f35add86dbe.JPG)

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
