### ISSUE TITLE
can the length of field which is part of Primary key increased

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/AL#5544]
Hi,

We have increased the length of field from 10 to 20 which is part of primary key. Then trying to publish the same. But we are facing the below issue.

** Unsupported field change.   Field: MyTestField ; Change :LengthChanged**

Can we increase the length of field which is part of Primary key.

**Comment by AskeHolst** [comment]
See #4620 
The only option at the moment is replacing the table.

**Comment by atoader** [comment]
I will close this as a duplicate of #4620
