### ISSUE TITLE
'Codeunit "File Management"' does not contain a definition for 'ExtractZipFile'

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5545]
Hi, 

I didn't find any solution for this breaking changes. Do we have substitution for ExtractZipFile and are we actually able to work with zip files in SaaS?

Thanks

**Comment by nicolassaleron** [comment]
Hi,
We are working with zip files in SaaS but everything have been moved to codeunit Data Compression in wave2

See https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md for more info.

**Comment by tomasevicstefan** [comment]
Tnx.
