### ISSUE TITLE
Upgrade to Business Central Wave 2

### ISSUE THREAD

**Issue by MadoaHenry** [microsoft/AL#5546]
Is it possible to upgrade Business Central Version 13 Extensions to Version 15 (Wave 2)?, if it is possible please guide me on how to do it.

**Comment by tomasevicstefan** [comment]
I think the easiest way to do that is to install/build environment for BC15, change lunch and app.json file to see BC15 instance, download symbols and fix errors if you have them. When you fix all errors, you will be able to publish extension to BC15 instance.

**Comment by atoader** [comment]
I recommend that you use one of the following resources to get assistance:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Please also take some time to read our FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
