### ISSUE TITLE
Using DownloadFromStream with Job Queue

### ISSUE THREAD

**Issue by TranLyTuong** [microsoft/AL#5547]
Hello,
I have write some code to export data record to a .csv file. After that i want to save that .csv file to folder.

![image](https://user-images.githubusercontent.com/58070142/70698323-d1c4ee00-1cf9-11ea-827e-a40170b268c9.png)

Next, i setup a scheduler job for auto run this feature.
And i am facing with one issue:
   - If i run this scheduler job by manual then successful.
   - But when Scheduler job run by automation then appear below error:

**MessageWithoutPrivateInformation**: Microsoft Dynamics 365 Business Central Server attempted to issue a client callback to download a file: \710_CT0105ANNUTIO01_191212160056.csv (Report 27014751 Crescent Mall Export). **Client callbacks are not supported on Microsoft Dynamics 365 Business Central Server._**

Anyone can support me to solve this issue? Thank you.

- AL Extension Version: 4.0
- Server Version: 14.0.36475

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
