### ISSUE TITLE
Reference to object xxx is ambiguous

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5548]
Following #2088

_An issue that we have seen in the past is if any of the structural keywords are missing (for example an Area inside of layout) then the parser might pick up variable declarations as object declarations leading to duplicate objects._

I faced 2k+ compilation errors related too

> Reference to object xxx is ambiguous. Make sure you are not referencing packages containing objects with the same names.

After some investigation, all these errors had nothing to do with the referenced object xxx, but were due do another object that could not be compiled due to syntax errors. In below example, I had added first a ',' instead of ';', which lead to an invalid syntax ...

![image](https://user-images.githubusercontent.com/25268332/70699419-619e7400-1cc9-11ea-8578-3c8cc85ca7a3.png)

Would it be possible for the compiler to first check on some basis valid syntax rules, before actually checking the symbols referenced?  If the syntax error would have been shown on top as the first critical to solve, it would have saved me lots of time...

Or any other plans to improve the parser?

**Comment by AndreyKorepanov** [comment]
Hi @fvet, thank you for reporting the issue.
Errors in the code base cause parser to build inconsistent syntax tree used for code analysis. We are constantly working on improvements in the parser and code analysis to provide the best user experience. Basically we do not provide patches for specific cases as it can hit the compiler performance and as far as I know we do not have plans regarding this specific type of issues.
