### ISSUE TITLE
Publishing my app erases extension fields and tables

### ISSUE THREAD

**Issue by ekesteloot** [Microsoft/AL#555]
I've added a couple tables as well as extended a couple tables with new fields.

Every time I publish my app, the new tables and new fields are completely deleted.

I'm using the August preview.

**Comment by StanislawStempin** [comment]
This is a known limitation for now. It is high on our priority list but I cannot share a more speicifc timeline yet. 
The issue was originally reported under #62 so I will keep the original for tracking purposes.
