### ISSUE TITLE
Loss of data in custom BLOB fields after posting  sales shipment

### ISSUE THREAD

**Issue by GregoryAA** [microsoft/AL#5550]
**Describe the bug**

After posting the partial shipment of the sales order, our client lost data in the Blob field that was added to the sales line table. This issue became after auto. update cloud tenant from 14.5 to 15.1 version

**To Reproduce**
Steps and to reproduce the behavior:
1. Create extension of sales line table 
2.  Add new Blob field,  Subtype = Memo
3. Publish extension
4. Create sales order with one line type-item  Qyantity = 10 , Qty to Ship  = 1
5. Populate any value to Blob field. You can use any method for that.
5. Pres the Post action and select the Ship
6. After posting check the Blob field in line of this Sales order. This field is empty.
 

``` AL Code to reproduce the issue ```

**Expected behavior**

The field value must be saved.

During investigation this issue in on-premise tenant   we found this critical changes:

Cu 80 function ModifyTempLine

![image](https://user-images.githubusercontent.com/45356755/70710841-2879fa00-1cf1-11ea-9b35-569548462fc6.png)

Transfield was added instead of a simple assignment.
As you can know Transfields can't copy blob field without using calcfields before it call. 

Our client does not understand how MS could release a new version of the system that destroys his data.

**Screenshots**

**5. Versions:**
![image](https://user-images.githubusercontent.com/45356755/70710539-6e828e00-1cf0-11ea-9eb5-a26a4f3bd329.png)

 - AL Language: 

 - Business Central:

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
