### ISSUE TITLE
NavAdminTool.ps1 enhancement suggestion

### ISSUE THREAD

**Issue by gregoral** [microsoft/AL#5554]
NavAdminTool.ps1 goes trough the registry key to locate the service directory.

```
  $nstPath = "HKLM:\SOFTWARE\Microsoft\Microsoft Dynamics NAV\150\Service"

  $snapInAssembly = Join-Path (Get-ItemProperty -path $nstPath).Path "\$snapIn.psd1"
  if(!(Test-Path $snapInAssembly)) { $snapInAssembly = Join-Path (Get-ItemProperty -path $nstPath).Path "\$snapIn.dll" }
```
I would like to propose a change to:
```
  if($PSScriptRoot.EndsWith('\Service')) { $nstPath = $PSScriptRoot }
  if(!(Test-Path $nstPath)) { $nstPath = (Get-ItemProperty -path "HKLM:\SOFTWARE\Microsoft\Microsoft Dynamics NAV\150\Service").Path }

  $snapInAssembly = Join-Path $nstPath "\$snapIn.psd1"
  if(!(Test-Path $snapInAssembly)) { $snapInAssembly = Join-Path $nstPath "\$snapIn.dll" }
```
This would load the dll files from the directory where NavAdminTool.ps1 is located.

Then importing this module from a directory like this would not be a problem:
```
Import-Module 'C:\Program Files\Microsoft Dynamics 365 Business Central\150.37898\Service\NavAdminTool.ps1' 
```
This is how NavModelTools.ps1 loads modules:
```
Import-Module (Join-Path $PSScriptRoot ($navAppToolsAssembly + ".psd1"))
Import-Module (Join-Path $PSScriptRoot ($navAppManagementAssembly + ".psd1"))
```

If this is not the correct place to suggest this change please advise on where to submit it.

**Comment by nndobrev** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
