### ISSUE TITLE
The extension could not be deployed because it is already deployed on another tenant

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5557]
Following #4256 #4972

We've prepared / converted an onprem C/AL 14 database via Powershell to AL via following path:
- Upgrade the database to v15 via some 'temporary' upgrade extensions to ensure data is properly moved to the extension tables. (Database contains approx. 15 extensions.)
- Upgrade the database to v15.1 with the actual / dev extensions to get the latest code modifications.

All is done via powershell commandlets and published to scope tenant and tenant default. 
All is ran OnPrem not using Docker.

Now we want to benefit from VSCode and publish new code modifications (without increasing the version no, since it all concerns internal dev for the upcoming weeks and to avoid the Start-NAVAppDataUpgrade like warnings) which results in following error

`The extension could not be deployed because it is already deployed on another tenant`

How can we ensure VSCode can connect to the previously executed PS steps? (Unsure about the whole -devenpoint and production scope features). We'd like to use VSCode without any additional PS scripts to publish / maintain new (dev) version of our extensions.

**Comment by JoshC94** [comment]
Hi,

I did not test that for other cases such as when multitenancy is involved, but as you already seem to use the scope and tenant used by a default VScode publish:
Have you tried to uninstall + unpublish the apps ( keeping the data by skipping the clean sync ) and publish using VScode afterwards?
That should enable you to do further publishs using VScode while keeping the data you migrated in your previous steps. 
Before doing a deployment for a live system I would reverse that process to ensure that all of your apps are in "production mode". 

Best Regards, 
Josh

**Comment by fvet** [comment]
@JoshC94 Uninstall / unpublish via PS and republish via VSCode indeed works. But that's the point I wanted to make. We're trying to prepare a dev database by scripting the installation of all our extensions. Having to manually publish tens of extensions manually afterwards in VSCode is a bit counter productive.

The same when the publishing of the base apps fails. All other dependend extensions get uninstalled and require manual reinstallation.

Having a force 'Full publish' in VSCode would at least ease working with multiple extensions.

**Comment by JoshC94** [comment]
Oh, sorry, I missed that point.
Well in that case, I guess you could just go by using the Dev Endpoint for the app installation in your scripts like NavContainerHelper does.
I suppose you are not using a container for your Dev System, so the function might not be helpful as-is. 
Anyways you can just take a look at the source (and adapt the same logic for your own scripts. You can find it here: [Publish-NAVContainerApp](https://github.com/microsoft/navcontainerhelper/blob/0f0c17bbfae12de7f09914417fdc34cdc15ab4e9/AppHandling/Publish-NavContainerApp.ps1#L111)

**Comment by fvet** [comment]
We've already tried to look at created a custom Publish-NAVApp based on the above -devendpoint code. However, this adds another complexity as described below https://freddysblog.com/2019/12/09/having-demo-data-while-developing-business-central-apps-with-docker/

Overall, it's just very frustrating that VSCode has been announced as the new dev environment, although the dev experience is just not good when dealing with several dependend extensions and that you'll have to revert to powershell scripts instead (that you need to create in case you're not on Docker ...) for most basic development tasks.

**Comment by kalberes** [comment]
Publishing with PowerShell and using VsCode to publish are apple and bananas.
When you publish with PowerShell you publish into the global scope , the app will be visible to all tenants in the system. When you use VSCode you publish into the dev scope. Dev scope is something that you use when developing your apps. 
Things published into the global scope are very special and protected. 
An app published to global scope should never reference apps published to dev scope or tenant scope (per tenant extensions).
A dev scope published app if it has a reference to a global scope published app , this global app will not be uninstalled/unpublished/republish(recompile)/reinstalled. Basically it is ignored in the dependency publishing logic from VsCode.

See here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-workspace-projects-references
"Any other app that directly depend on Base and are not published in the global scope - in this case Leaf and External - are unpublished."

**Comment by atoader** [comment]
This issue has been closed because it has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
