### ISSUE TITLE
Encrypt/Decrypt text in version 15

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/AL#5558]
Hi, 

In previous version of BC/NAV we used some system dotnet libraries to encrypt/decrypt text. Do we have any alternative for this in version 15 (Cloud)? 

I know for built in function's Encrypt/Decrypt. But can we used same encryption key on the other side for opposite process?

Thanks

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
