### ISSUE TITLE
Error: Date Selection returns Date in US format

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#5559]
Hi!

Not sure if this has been reported yet: if I choose a Date via the Calendar Lookup in Business Central 15 in my german environment it returns a Date in US format (which is -of course- not accepted):

![grafik](https://user-images.githubusercontent.com/47742057/71072600-25628c00-217f-11ea-815e-0bf9f307099e.png)

![grafik](https://user-images.githubusercontent.com/47742057/71072184-3b238180-217e-11ea-8682-df7309542614.png)

BC15 CU1 plattform 37898, application 38071
Webbrowser: Edge Beta & Firefox

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
