### ISSUE TITLE
How to get XmlText from XmlNode?

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#556]
How can you get the XmlText from an XmlNode? I don't see a clear way to do that.

**Comment by jcooper01** [comment]
So this seems to work:
XmlNode1.SelectSingleNode('text()', XmlNode2);
DNXmlNode2.AsXmlText.Value

Is that the best way? Seems circuitous.

**Comment by atoader** [comment]
That is the only way. SelectSingleNode will return an XmlNode. An XmlNode can be XmlText, XmlElement etc. Because we do not have explicit conversions in AL, we added them as methods to the type.
