### ISSUE TITLE
error AL0315: Control does not exist in group 'RepeaterControl'

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5560]
Working with AL Compiler version 5.0.3.12379, we often get errors when running 'AL: Rapid Application Publish' on controls used in the FreezeColumn property. Before compiling, there were no errors at all.

![image](https://user-images.githubusercontent.com/25268332/71074192-2517c000-2182-11ea-9266-d8b10abb5b9f.png)

After several new attemps, the error no longer shows and publish succeeds.

**Comment by atoader** [comment]
Thanks @fvet! It looks like a concurrency issue. We'll take a look.

**Comment by fvet** [comment]
@atoader  Any update on this? Got the warning tens of times today before it was able to do a RAD (not willing to 'reload window' since this forces me to do a full publish)

![image](https://user-images.githubusercontent.com/25268332/80464618-5aa39580-893a-11ea-9df1-aec502e17bb1.png)

**Comment by atoader** [comment]
We have not had a chance to fully investigate this issue. It is high on our backlog, but we are currently prioritizing issues encountered by our customers in SaaS. 
I will remove the in-progress tag. Once the bug is picked up, we will set a milestone and add the tag back.

**Comment by fvet** [comment]
@atoader Any update on this? Got the warning tens of times today before it was able to do a rapid publish (not willing to 'reload window' since this forces me to do a full publish)

**Comment by atoader** [comment]
We found what we believe was the cause of this in the last week. You can try it out in the insider preview. We will push an update later this week.

**Comment by fvet** [comment]
@atoader 

We're having the same errors since few weeks again. Running both the latest marketplace vsix as well as the latest insider vsix now frequently results in - incorrect - AL0315 errors when packaging / publishing our apps.

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.4.496506
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
