### ISSUE TITLE
Fast publishing failed when discarting changes

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5561]
I did a small change on a page (Added ShowMandatory = true). Afterwards, I decided to undo the changes via the source control > discard changes options, resulting in the 'Rapid Application Publish' no longer to work ...

> error AL0671: Fast publishing failed because the RAD file has specified an existing application object of type: 'Page' name: 'NVT Workflow Tasks Listpart' ID: '2009621' to be deleted. Please do a full publishing before issuing a fast publishing again.

Apparently, this was detected in the rad.json as a remove; although nothing changed to this object, nothing has been deleted, but still I'm forced to do a (slow) full publish. Can you please provide support for this scenario in the Rapid Publish command?

**Comment by AndreyKorepanov** [comment]
Hi @fvet thank you for reporting the issue. Reverting git changes bring the file system to the state you had before changes, as a result you get missing RAD file. The files are changed externally, AL extension can not control it. Please follow the suggestion from the error message, full publishing will re-create the missing RAD file and enable you to go on with the Rapid Application Publishing. Thank you.
