### ISSUE TITLE
Already declared - finding objects twice

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/AL#5562]
**Describe the bug**
Objects are found twice, and the analyzer says the objects are already declared.
When an object is selected, the error will disappear.
Only to re-appear shortly there after.

**To Reproduce**
The IDE searches from both the relative path of the root of the project folder and from C:\

**Expected behavior**
Only one search path.

**Screenshots**
![Unavngivet](https://user-images.githubusercontent.com/6465685/71094757-ccf5b380-21ab-11ea-98bf-01638d8e0c51.png)

**5. Versions:**

 - AL Language: 
4.0.209944

 - Business Central:
Version: Platform 14.0.38529.0 + Application 38566 (W1 14.5)

**Comment by MortenRa** [comment]
Seems I have seen this behavour when working with workspaces where I actually had the file both in the workspace folder and the project folder.

**Comment by JSebastianN** [comment]
Thanks Morten.
I am not using a workspace...

But I think I have resolved it by: Adding a folder to Workspace.
Removing it.

Weird!

**Comment by atoader** [comment]
Can you provide a project that reproduces this issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
