### ISSUE TITLE
finsql.exe commande is too long - generatesymbol

### ISSUE THREAD

**Issue by juliensavarese** [microsoft/AL#5563]
Hi,

I am upgrading a 2017CU9 version to BC14CU7.
I have made all the customisation in extension, so the 2017CU9 old base haven't any custom object.
I have made the application upgrade.
I can open my Migrated BC version with web client, with all my data and everything work well.
Now, I want to install my Extension.
I have made the Extension with a docker image , of the version BC14CU7, and everything worked perfectly.
Now, I want to install the package on my migrated BC14CU7 instance.
So, I get my package file , and try to install with the Publish-NAVApp command.
I get this error : 
"
Publish-NAVApp : Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Application', and a version compatible with '14.0.0.0' could
not be loaded. Symbols for the requested app Application by Microsoft 14.0.0.0 could not be found in the database
error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '14.0.0.0' could not
be loaded. Symbols for the requested app System by Microsoft 14.0.0.0 could not be found in the database"

So I understand the symbol are not generated in the BC14CU7 database.
So I try this : 

cd "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client"
.\finsql.exe Command=generatesymbolreference,Database=BC14CU7", ServerName=MyServer

and , I got this error : 

The Text generatesymbolreference,Database=BC14CU7", ServerName=MyServer is too long.
Text can have a maximum lengh of 47 characters
So...Cannot generate symbol....

Can you help me please ?

thank you

**Comment by juliensavarese** [comment]
I find out : 
Because of the copy and Past as it is from all the forums, I have copied the Space before each coma.
So , delete the coma, and the commande work well.
Hope will help others.

**Comment by calebrimborX** [comment]
It helped me, thanks!
