### ISSUE TITLE
Table: Page Action Field Field: ActionName values get cut off at 30 chars 

### ISSUE THREAD

**Issue by hougaard** [microsoft/AL#5565]
Several action names are longer than 30 chars, but the Name field in table "Page Action" only returns 30 chars.

![image](https://user-images.githubusercontent.com/3357237/71158546-fe48a080-21f8-11ea-9b43-6144ed6c7dd0.png)

![image](https://user-images.githubusercontent.com/3357237/71158585-0d2f5300-21f9-11ea-8865-988d496f3267.png)

![image](https://user-images.githubusercontent.com/3357237/71158731-4e276780-21f9-11ea-8149-59369fe7fda0.png)

![image](https://user-images.githubusercontent.com/3357237/71158649-2932f480-21f9-11ea-80e0-2bbd71f3777c.png)

**Comment by hougaard** [comment]
Wait..... Something is fishy... I'll close this for now until I have a bit more information....

**Comment by AndreyKorepanov** [comment]
Hi @hougaard, thank you for reporting the issue. As far as I can see from the screenshots this is UI problem. Could you please check if the Name is cut in the code (just check it in debugger). If it is UI issue then it is better to report the issue to the proper team, as this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 
You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

**Comment by hougaard** [comment]
Hi Andrey,

The issue is not UI, the table definition for Page Action has the field as only 30 chars

![image](https://user-images.githubusercontent.com/3357237/71264610-51a21800-22f9-11ea-8c0e-1415402419a0.png)

**Comment by efoqusca** [comment]
Hi @AndreyKorepanov 

Any update on this bug?
@KennieNP or @jensmpmsft perhaps?

/Erik

**Comment by hougaard** [comment]
Still no updates? This bug is currently blocking us for submitting an app to AppSource...

**Comment by AndreyKorepanov** [comment]
Must be a warning, that the name longer then 30 chars will be truncated.
