### ISSUE TITLE
BC 14 field length issue

### ISSUE THREAD

**Issue by RHansenEpimatic** [microsoft/AL#5566]
In BC 14 CU1 (on premise) I am unable to add a field with a length longer than 250 characters through the AL development environment.  I get an error that the max length is 250.  If i try through the classic C/AL object designer, i can add a field up to 2048 length with no problems.

**Comment by atoader** [comment]
Hi! What runtime are you targetting with your extension? It should be set to 3.0 or later.

**Comment by RHansenEpimatic** [comment]
Hi Alexandru.  The runtime in app.json was set to 2.4.  I updated it to 3.0, but still get the same error in VS Code.  Is there anything else i need to do other than changing the runtime setting in app.json?

**Comment by atoader** [comment]
Can you provide a sample to reproduce the issue? Can you share a screenshot of the errors that you are getting?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
