### ISSUE TITLE
Need Facility to SkipTriggers in all the Trigger Events

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#5569]
It is important to have a feature in all the Trigger Type events (OnBefore) Such as 
OnBeforeInsert,OnBeforeModify,OnBeforeDelete,OnBeforeRename,OnBeforeValidate to have an extra parameter such as 'SkipTrigger'.  Once this is set to true any subsequent execution of the trigger needs to be supressed for all the extensions.  Also the execution code needs to be prioritised as follows (from high priority to low priority).
1) Any event Subscription in Codeunit 50000 to 99999 (ie 50000 taking higher priority compared to 99999)
2) Any event Subscription in Codeunit 100000 and above
3) Any event Subscription in Codeunit up to 49999

This will allow solution centre to perform a possible code cloning and override the standard trigger code in an extension to accommodate any customisation for the customer in a custom extension.

Further All the 'OnAfter' trigger such as OnAfterInsert,OnAfterModify,OnAfterDelete,OnAfterRename,OnAfterValidate needs to be executed in the following order (from high priority to low priority) as well.  This will give a quite easy to follow and strict order of execution when the same event is subscribed by multiple extensions.

1) Existing code in the trigger code
2) Any event Subscription in Codeunit up to 49999
3) Any event Subscription in Codeunit 100000 and above
4) Any event Subscription in Codeunit 50000 to 99999 (ie 99999 taking higher priority compared to 50000)

See below for code example

[EventSubscriber(ObjectType::Table, Database::"Sales Line", 'OnBeforeValidateEvent', 'Status', true, true)]
    LOCAL PROCEDURE OnBeforeValidateOfType(VAR Rec: Record "Sales Line"; VAR xRec: Record "Sales Line"; CurrFieldNo: Integer;SkipTrigger: Boolean);
    BEGIN

	//Your Over ridden code
	SkipTrigger := True;

    END;

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
