### ISSUE TITLE
It is only possible to grant permissions to objects that are defined within the same module.

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#557]
Our extensions need to be able to grant permissions to native objects. I know this has been discussed on office hour calls, but I didn't see an issue for it on GitHub. Example scenario: we have an archive function that moves payment transaction records to an archive table. Those payment transactions are referenced by our fields in the G/L Entry table, the Cust. Ledger Entry table, etc. We need to be able to update those records during the archive process to indicate that the references are now to the archive and not to the active payment transaction list.

**Comment by mcoaggie** [comment]
+1 
To prevent the code from a complete rewrite of on premise functionality need access to 
grant explicit permissions in case of Extension upgrade codeunits as well as event subscribers.

**Comment by StanislawStempin** [comment]
This limitation will be removed in October Update.
