### ISSUE TITLE
unable to download Symbols from online Sandbox 

### ISSUE THREAD

**Issue by XavierAnnabi** [microsoft/AL#5570]
Hi,

**Thanks in advance for your help,**
 
Am trying to download symbols from online Sandbox but getting issue that path not found. 
Please, see pictures below for more details 
Do we need vsix file for online Sandox ?  (if is the case how can I get it )

![BC](https://user-images.githubusercontent.com/36770013/71450752-dc3da980-2735-11ea-9916-27269e38f9ab.png)

![BC2](https://user-images.githubusercontent.com/36770013/71450880-7c94cd80-2738-11ea-80e7-521e8471c2f1.png)

Thank you.

**Comment by kalberes** [comment]
Have you named your sandbox when creating it? If yes that name must be specified in the sandboxName parameter.

**Comment by NKarolak** [comment]
Did you already check bullet point 2 and 3 of the error text, about the application version numbers in the **app.json**? According to the compiler, you are depending on "Application" and "System", both version 11.0.0.0. Are these really the app names and versions installed on your sandbox?

**Comment by XavierAnnabi** [comment]
issue fixed by the same setting above, just change  app.json   "dependencies"   "version": "15.0.0.0"
in launch.json 
serverInstance must be lowercase 
set  port number   "port": 124X,
