### ISSUE TITLE
BC Release Wave 2 Chartpart

### ISSUE THREAD

**Issue by klarmio** [microsoft/AL#5573]
The Web Client is not showing the Generic Chart.
No Error is shown the Factbox is just not visible.

Code:
```
    layout
    {
        addfirst(FactBoxes)
        {
            chartpart(mychartPart; "T5406-01")
            {

            }
        }
    }
```

**Comment by atoader** [comment]
Hi! Have you tried setting the ApplicationArea on the control?

**Comment by klarmio** [comment]
Hi, yes i tried that. The chartpart still gets ignored in the webclient.

If i go back to springs release and use the same code the chartpart is visible in the Windows client.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
