### ISSUE TITLE
Objectreference

### ISSUE THREAD

**Issue by MariaFrederiksen** [microsoft/AL#5578]
[Error - 12.27.21] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Objektreferencen er ikke indstillet til en forekomst af et objekt.
StackTrace:
   ved System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   ved System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsAsync(Document document, Int32 position, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:linje 25
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.<HandleAsync>d__3.MoveNext() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:linje 54
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:linje 59

I have downloaded Symbols, I have make HelloWorld work, I make one tiny table with three fields in one group like this:

table 50001 "SVA Setup"
{
Caption = 'Setup';

    fields
    {
        field(10;Number;Code[10])
        {
            Caption='Number';
        }
        field(20;Name;Text[50])
        {
            Caption='Name';
            trigger OnValidate();
            begin 
                if StrLen(Name) <> 30 then 
                    Error('for lang');
            end;        
        }
        field(45;"Country/Region Code";Code[10])
        {
            Caption='Country/Region Code';
            Description = 'Udlejers landekode';
            TableRelation = "Country/Region";
        }
        field(60;"Vat Registration No.";Text[10])
        {
            Caption= 'Vat Registration No.';
            trigger OnValidate();
            var 
            VatRegNoFormat : Record "VAT Registration No. Format";
            begin
                VATRegNoFormat.Test("VAT Registration No.","Country/Region Code",'',DATABASE::"Company Information");
            end;    
        }
    }
    
}

**Comment by kalberes** [comment]
What versions are you using? 
And what are you doing after you have created the HelloWorld?
Have you compiled? Or the exception just suddenly appeared when typing, or hovering?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
