### ISSUE TITLE
GetAddPostedSalesDocumentToCRMAccountWallConfig - Add code based on setup.

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/AL#5582]
Codeunit: 5334 - CRM Setup Default
Can we please have the option to turn this off?

![image](https://user-images.githubusercontent.com/35260264/71881943-adf79b00-3133-11ea-8b55-abb69adec3e3.png)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
