### ISSUE TITLE
"View" button cannot open highlight record on Job Queue Entries card page

### ISSUE THREAD

**Issue by monchangg** [microsoft/AL#5583]
**Describe the bug**
BC opened another record after clicked "View" button on Job Queue Entries page.

**To Reproduce**
1. Open Job Queue Entries page through "TELL ME WHAT YOU WANT TO DO"
2. Click one record and use "Select More" action.
![image](https://user-images.githubusercontent.com/22004532/71881931-4dd21a80-316e-11ea-8301-83ec34d96deb.png)
3. Uncheck one record which has not arrow, then result should be following screenshot. The highlight record didn't have arrow.
![image](https://user-images.githubusercontent.com/22004532/71882044-98539700-316e-11ea-9b99-620848f87866.png)
4. Click "View" button, it opened non-highlight record.

**Expected behavior**
It should open highlight record.

**Other list pages have same issue. Does this BC's bug?**

**Versions:**
 - Business Central: 15.2.39060.0

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
