### ISSUE TITLE
Can't launch debugger. Error:  VS Code Unexpected token in JSON at position 876

### ISSUE THREAD

**Issue by johndcollins** [microsoft/AL#5584]
**Describe the bug**
When running F5 to debug an extension I get the error: "VS Code Unexpected token in JSON at position 876"
I can't find any way to get more information about the error, not logs show anything and nothing in the output window for AL. It just says that the package was created, but then stops.

**To Reproduce**
This only happens on a project where we have a lot of code. A new small project doesn't have this issue

``` AL Code to reproduce the issue ```
Can't give you all the code.

**Expected behavior**
Debugger starts up and launches 

**Screenshots**
![VS Code Error](https://user-images.githubusercontent.com/1684130/71939108-7c4bf780-3166-11ea-8ca4-81580ff89908.PNG)

**5. Versions:**
4.0.209944

 - AL Language: 
Not applicable

 - Business Central:
Not applicable

**Comment by kalberes** [comment]
What if you format document the launch.json within VsCode?

**Comment by johndcollins** [comment]
I'm not sure what you mean.

**Comment by kalberes** [comment]
Ctrl Shift P in VsCode
Run the command: Format document
on the launch.json. Maybe it really has some weird character.

**Comment by johndcollins** [comment]
But there is no position 876 in this file, it's not that big.
It must be another file that they are creating in the background. I just can't see which file as there is nothing in the error message or the log files.

**Comment by johndcollins** [comment]
This is really becoming a problem with our implementation. Can someone from MS please help out here?

**Comment by atoader** [comment]
Hi! Does this reproduce on the preview release of the extension? Can you provide a sample to reproduce this?

**Comment by johndcollins** [comment]
The issue was a bad character in one of the json files. The error in VS Code should be better and not just stop deploying.

**Comment by AndreyKorepanov** [comment]
You might want to open a BC idea if one is not already present. That will help us get an understanding of how much the community needs this relative to other features. Please follow the link: [BusinessCentralIdeas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central)
