### ISSUE TITLE
Code Analysis in combination with multi project workspace

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5585]
I've setup a multi project workspace.

The workspace file contains following settings

![image](https://user-images.githubusercontent.com/25268332/71959934-24f46880-31f4-11ea-96e7-0de822441bce.png)

My 'Base' project (5000+ objects) contains following settings

![image](https://user-images.githubusercontent.com/25268332/71959976-3e95b000-31f4-11ea-8d55-de59c0fd884e.png)

My 'Dependend' project (2 objects) contains following settings

![image](https://user-images.githubusercontent.com/25268332/71960056-61c05f80-31f4-11ea-9602-b3ce1b671c75.png)

Seems like CodeAnalysis is still applied for the entire workspace, since I get UICop errors for my Base project, where Code Analysis should not be applied.

![image](https://user-images.githubusercontent.com/25268332/71960096-76045c80-31f4-11ea-8bb7-07d9e172d39e.png)

Requirement:
"al" workspace settings should take priority on the indivual .vscode project settings for CodeAnalysis. Support for mixture of CodeAnalysis settings is needed (so we can gradually focus on fixing CodeCop stuff for minor extensions first)

Version :

![image](https://user-images.githubusercontent.com/25268332/71960204-b6fc7100-31f4-11ea-9cca-e508d6ee10bd.png)

**Comment by fvet** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=5a5f8d29-4d10-ea11-b265-0003ff68d51d

**Comment by atoader** [comment]
Thank you for posting that! I see that it has gathered a good number of votes :) That will help us in prioritizing it for a future release. I will close this issue.
