### ISSUE TITLE
CRM Integration sets wrong Modified on filter.

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/AL#5586]
**Describe the bug**
When setting latestmodifiedon to the IntegrationTableMapping table, the wrong date is set.
When synchronizing to the integration table, the  "Synch. Int. Tbl. Mod. On Fltr." is set, and when synchronizing from the integration table, "Synch. Modified On Filter" field is set. It should be the other way around, otherwise, if you have a sync that only goes in one direction, the filter will be emtpy and you have to loop through all records in the table each synchronization. 

**To Reproduce**
1. Set up CRM-syncronization with customers with one direction. Start the job que, and you will se that every record is either changed,failed or unchanged.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35260264/71964549-16ab4a00-31fe-11ea-8ac0-c56ed578ff14.png)

![image](https://user-images.githubusercontent.com/35260264/71964662-54a86e00-31fe-11ea-98d7-87a1aa97212f.png)

Either the index in the onRun or function UpdateTableMappingModifiedOn should be changed.

**5. Versions:**
- AL Language: 4.0.209944
- Business Central: 15.1.37881.39299

In Dynamics NAV 2018 version: 11.23572.0 this was not an issue. See screenshots:
![image](https://user-images.githubusercontent.com/35260264/71965236-984fa780-31ff-11ea-9f12-082ef4186b0b.png)
![image](https://user-images.githubusercontent.com/35260264/71965264-a271a600-31ff-11ea-81d9-348bc987dea8.png)

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

Please also take a minute to read our FAQs https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
