### ISSUE TITLE
AL Extension Publish Sales order Posting Issue

### ISSUE THREAD

**Issue by mohit0989** [microsoft/AL#5587]
Hi All,

We have created and published an extension in Business Central Wave 2(OnPrem). The issue is when we create a Sales Order on webclient and post it, it gives an error: "Something went wrong"
I have checked the tables,checked through debugger(the variable and record values are updated),deleted the browser history also.
Have anyone faced the same issue?
Same issue i am facing in Purchase order also. But i am able to post the journals.
Any suggestions?
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Sales Order and post it.
``` AL Code to reproduce the issue ```

**Expected behavior**
Sales Order should be posted
**Screenshots**
![image](https://user-images.githubusercontent.com/47515024/71968631-4fade380-322b-11ea-80e7-868aeaa8d68e.png)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
