### ISSUE TITLE
Determining Active Project Folder when Editor Groups are used

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/AL#5588]
**Describe the bug**
When AL files are being edited in multiple editor groups and an 'al.package' command is activated AL Extension is not choosing the correct Active Project Folder.
Group1 has fileOne.al open and Group2 has fileTwo.al open. fileOne.al resides in project folder Project1 and fileTwo.al resides in project folder Project2.
Now regardless of which file is being edited or has focus al.package will always compile the same project folder. I my opinion it should dynamically choose the project folder that belongs to the file that has focus. If fileOne.al as focus Project1 should be the one being compiled and if fileTwo.al has focus Project2 should be the one being compiled.

**To Reproduce**
Steps and to reproduce the behavior:
Open a workspace that contains at least 2 project folders each containing an AL Project. Make 2 Editor Groups. Have one group edit an AL file from one project and have Group 2 edit an AL file from another project.
Now swap between the 2 files and do edits on both and leave focus on both and execute 'al.package' command. Its always the same project folder being selected.

``` AL Code to reproduce the issue ```
AL Code is irrelevant to this issue

**Expected behavior**
That when AL file of Project2 is activated and edited that 'al.package' compiles Project2. Not Project1.

**Screenshots**
No screenshot

**5. Versions:**
Version 4.0.0
 - AL Language: 

 - Business Central:

Looked into the code of the extension and I've located the problem code.
To determine Active Project Folder extension is first using vscode.window.activeTextEditor and if that fails it then uses vscode.window.visibleTextEditors.
If multiple Editor Groups are used then there will be more elements in the resulting array but extension will always choose the first acceptable AL file that exists and therefor will never accept files being edited in Group 2+.

I am of the opinion that the extension should take note of the files being activated and edited and choose the last updated file to determine Active Project Folder by.

This is easily implemented by using a vscode event instead. onDidChangeActiveTextEditor is all you need. 

vscode.window.onDidChangeActiveTextEditor(event =>
{
    console.log(event.document.uri.fspath);
});

**Comment by qutreson** [comment]
This issue should be fixed and will be available soon in our developer previews
