### ISSUE TITLE
HTTPClient.AddCertificate does not work

### ISSUE THREAD

**Issue by 48010** [microsoft/AL#5589]
**Describe the bug**
I have a Code to add a certificate in Base64 and with any certificate returns the error "Cannot find the requested object."

I have already look at the issues [#4939](https://github.com/microsoft/AL/issues/4939) and [#5299](https://github.com/microsoft/AL/issues/5299) but I cannot solve my problem with their solutions.

**To Reproduce**
``` AL Code to reproduce the issue ```
HttpWebClient.Clear();
HttpWebClient.AddCertificate(<<X509Certificate in Base64>>, <<Certificate Password as Text>>);

**Expected behavior**
Certificate loads ok

**5. Versions:**
 - AL Language:  4.0.209944
 - Business Central: 15.2.39060.0

**Comment by atoader** [comment]
Are you still facing this problem? Can you provide a sample to reproduce this issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
