### ISSUE TITLE
File does not open from Compiler Error Output

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#559]
The link to the file is not working in the output screen for compiler errors, when the file name contains whitespaces:

![grafik](https://user-images.githubusercontent.com/15800069/29808646-465907ae-8c99-11e7-9309-015ce5f614a9.png)

**Comment by esbenk** [comment]
This is a bug in VsCode. It is files with the VsCode team, but there is no timeline for fixing it. The workaround is not using spaces.

**Comment by StanislawStempin** [comment]
Dominik fixed it in the VS Code codebase. If you switch to VS Code 1.22.1 this should now work.
