### ISSUE TITLE
MARKEDONLY Filter does not propagate from List to Card. 

### ISSUE THREAD

**Issue by bssi-danielf** [microsoft/AL#5591]
### Describe the bug
Unlike the other filters (`SetFilter` and `SetRange`), when using the `MarkedOnly(True)` filter with `Marks` on the record, the filter does not propagate with the record from list page to card page. I've searched and found this issue also described here without resolution: [https://forum.mibuso.com/discussion/65105](https://forum.mibuso.com/discussion/65105).

This particular question doesn't seem to have been raised or resolved on the GitHub previously, so I am asking if this is by design, or if this is a bug. 

### To Reproduce
Steps and to reproduce the behavior:
1. Create a dummy page with the dummy actions below.
2. Open the *list page* using the **First** dummy action.
3. Open a record's *card page* and browse to the second record using the next / prev arrows.
4. Repeat steps 2 & 3 but with the **Second** dummy action.
5. Note the differences in which records are accessible with the next / prev arrows. 

```
action(First)
{
	ApplicationArea = All;
	Caption = 'First';

	trigger OnAction()
	var
		Customer: Record Customer;
	begin
		Customer.RESET;
		Customer.FilterGroup(2);
		Customer.SetFilter("No.", '%1|%2', '10000', '30000');
		Customer.FilterGroup(0);
		Customer.FindSet();
		PAGE.Run(0, Customer);
	end;
}
action(Second)
{
	ApplicationArea = All;
	Caption = 'Second';

	trigger OnAction()
	var
		Customer: Record Customer;
	begin
		Customer.RESET;
		Customer."No." := '10000';
		Customer.FIND('=');
		Customer.MARK(TRUE);
		Customer."No." := '30000';
		Customer.FIND('=');
		Customer.Mark(TRUE);
		Customer.MARKEDONLY(TRUE);
		PAGE.Run(0, Customer);
	end;
}
```

You'll notice that despite the *list pages* looking the same, the *card page* of the `MarkedOnly` example allows the user to browse through all the records violating the filter on the underlying list. 

### Expected behavior
Since the underlying list pages have the same records, and are effectively filtered in the same way, I'd expect that the card pages opened from the lists, to also be filtered the same way. 

**Futhermore**, when you do the same test but with only the one record (remove the 30000 customer in both filters), you see the behaviour of MarkedOnly is inconsistent. In this new example, no next / prev buttons are available, and so the card page is correctly limited to the list page's filter. 

### Screenshots
An example of what both list pages look like:
![image](https://user-images.githubusercontent.com/56848245/72029522-0d8c9e00-323b-11ea-91cb-da7dd8cbbfa8.png)

### Versions

 - **AL Language:** 4.0.209944

 - **Business Central:** US Business Central 15.1 (Platform 15.0.37865.38547 + Application 15.1.37881.38576)

**Comment by bssi-danielf** [comment]
Is it possible to get a follow up about this issue?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
