### ISSUE TITLE
Reference to object XXX is ambiguous. Make sure you are not referencing packages containing objects with the same names.

### ISSUE THREAD

**Issue by anwar0206** [microsoft/AL#5592]
**Describe the bug**
**ERROR DISPLAYED ONLY FOR STANDARD PAGES**
All of a sudden AL started showing this error for all Standard Pages in our AL project. "Reference to object Item List is ambiguous. Make sure you are not referencing packages containing objects with the same names."

app.json contains following information
{
  "id": "xxxxxxxxxxxxxx,
  "name": "OnPrem",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "Set Brief",
  "description": "Description of the App",
  "privacyStatement": "http://mydomain.com ",
  "EULA": "http://mydomain.com",
  "help": "http://mydomain.com",
  "url": "http://mydomain.com",
  "logo": "logo.png",
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
      "from": 50000,
      "to": 50050
    }
  ],
  "contextSensitiveHelpUrl": "https://mydomain.com/help/",
  "showMyCode": true,
  "runtime": "4.0",
  "features": ["TranslationFile"]
}

Tried deleting the System Application dependency and the app. But the problem persists.

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**
4.0.209944
 - AL Language: 

 - Business Central:
Version: W1 15.1 (Platform 15.0.37898.0 + Application 15.1.37881.38071)

**Comment by atoader** [comment]
Hi! Could you please provide a full repro for this issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by WajahatAli110** [comment]
I am facing the same issue, could anyone please help me

**Comment by atoader** [comment]
Please open a new issue and provide a repro.
