### ISSUE TITLE
Not able to attch certificate on SOAP call

### ISSUE THREAD

**Issue by Ani4ket** [microsoft/AL#5593]
Hi,

We are able to hit the endpoint from the SOAP UI and getting the proper response. But when we are trying to access the same endpoint using our codebase(using proxy ref) we are getting “Authication failure” message. As per our understanding we able to send the certificate along with the proxy call. We have tried most of the google findings but still no luck.  if you have any suggestion please let us know.

Regards,
Aniket

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
