### ISSUE TITLE
ALC.EXE "-out" using the app.json information to contruct package name

### ISSUE THREAD

**Issue by hougaard** [Microsoft/AL#56]
When calling ALC.EXE without the -out: parameter the extension will be called Module.navx. Called with -out:<name> gives the extension the supplied name.

How do I ask ALC.EXE to use the information in the app.json to construct the <Publisher>_<name>_<version>.navx file name?

**Comment by dennisfrostlander** [comment]
ALC.EXE does not have capabilities to construct file name from app.json. This is done inside VSCode and then ALC is called with the proper parameters.

**Comment by hougaard** [comment]
This is not a very optimal design. When we get to use the new compiler in a DevOps environment (such as Team Services) the "VS Code" part will not be part of the setup, just the barebone compiler. ALC already uses the app.json for several other things, so it is really unlogical that this simple rename operation is left out.

There should be a command line method to perform a complete build, not relying on an IDE to perform some tasks. I actually do believe that we were promised this.

**Comment by StanislawStempin** [comment]
I recall we discussed this before and it does make sense. App.json should serve as the source of the default .navx naming that can be overriden from the command line. We will include it in one of the next updates.
