### ISSUE TITLE
Txt2AL Table Releation referenced fields not quoted

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#560]
The referenced field of the table relation was not quoted by Txt2Al:
![grafik](https://user-images.githubusercontent.com/15800069/29809250-b5c8d7f2-8c9b-11e7-9d2d-af2912d04316.png)

Source:
![grafik](https://user-images.githubusercontent.com/15800069/29809381-3bfe46fe-8c9c-11e7-8269-c8c26f947fdd.png)

**Comment by esbenk** [comment]
Have you used the Command=ExportToNewSyntax switch when exporting the .txt files?

Documentation for the Txt2Al tool can be found [here](https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool)

**Comment by megel** [comment]
No, I did not used FinSQL, because my sources are currently not in the database. So I started with splitting the sources and then I used:
`txt2al --source --target`

**Comment by esbenk** [comment]
You need to use C/SIDE. That is the problem. The Txt2Al tool doesn't have the necessary information to do it right. Not using the ExportToNewSyntax is also causing the problem in #558

**Comment by megel** [comment]
OK thx
