### ISSUE TITLE
Dimension Related Issue 

### ISSUE THREAD

**Issue by VAIBHAV-NAGAR** [microsoft/AL#5600]
**Describe the bug**
When we apply a dimension value to a Document(e.g. Sales Invoice) and after applying the dimension if we rename the Dimension Code Value(ADM to ADMIN) it will reflect to the document but after changing to the  Dimension value code in document(ADMIN to PROD) and again we apply the changed Dimension(PROD TO ADMIN) to the document it will update the same in header (ADMIN)but in the Line it update the dimension Code (ADM) which is not exist in dimensions

**To Reproduce**
Steps and to reproduce the behavior:

1. create a sales invoice and apply the dimension to the invoice 
![image](https://user-images.githubusercontent.com/58846308/72332889-ddcd1280-36e0-11ea-8a31-4904d47abdf2.png)
2. Go to the Dimension and Rename the Dimension Value ex.   ADM to ADMIN
![image](https://user-images.githubusercontent.com/58846308/72332987-094ffd00-36e1-11ea-876b-b320c731d890.png)

3.  After rename the Dimension if we again change the dimension to another dimension value i.e ADMIN to PROD . If will update perfectly but when we apply the renamed dimension again i.e. PROD TO ADMIN. It will reflect in the header but in LINE it Will update ADM which is not exist.
![image](https://user-images.githubusercontent.com/58846308/72333325-9abf6f00-36e1-11ea-9bf9-be991a8a2223.png)

**Expected behavior**
In Line Dimension ADMIN should be update instead of ADM 

Thank you
Vaibhav Nagar

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

Please take a minute to read our https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions to find the right place to post your questions.
