### ISSUE TITLE
Method overloading with certain lists fails on deployment

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/AL#5601]
**Describe the bug**
When using method overloading with lists of Code (different lenghts) as parameter no compiler error is thrown, but deployment fails.

**To Reproduce**
Here a code example:

``` 
    local procedure TryAddToList(ValueElement: Code[10]; var ListToAdd: List of [Code[10]]): Boolean
    local procedure TryAddToList(ValueElement: Code[50]; var ListToAdd: List of [Code[50]]): Boolean
 ```

**Expected behavior**
I would consider two differently typed lists as different parameters so overloading should work here.
If you disagree, the compiler should show an error at least.

**Screenshots**
Error Message:

> C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1449,23): error CS0102: The type 'Codeunit5022165' already contains a definition for 'TryAddToList_Scope_62675578'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1446,10): error CS0579: Duplicate 'NavName' attribute
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1447,10): error CS0579: Duplicate 'SignatureSpan' attribute
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1448,10): error CS0579: Duplicate 'SourceSpans' attribute
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1485,22): error CS0111: Type 'Codeunit5022165.TryAddToList_Scope_62675578' already defines a member called '.ctor' with the same parameter types
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1491,37): error CS0111: Type 'Codeunit5022165.TryAddToList_Scope_62675578' already defines a member called 'OnRun' with the same parameter types
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1372,66): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit5022165.TryAddToList_Scope_62675578.TryAddToList_Scope_62675578(Codeunit5022165, NavCode, ByRef<NavList<NavCode>>)' and 'Codeunit5022165.TryAddToList_Scope_62675578.TryAddToList_Scope_62675578(Codeunit5022165, NavCode, ByRef<NavList<NavCode>>)'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1375,36): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal' and 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1439,66): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit5022165.TryAddToList_Scope_62675578.TryAddToList_Scope_62675578(Codeunit5022165, NavCode, ByRef<NavList<NavCode>>)' and 'Codeunit5022165.TryAddToList_Scope_62675578.TryAddToList_Scope_62675578(Codeunit5022165, NavCode, ByRef<NavList<NavCode>>)'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1442,36): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal' and 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1396,56): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId' and 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1401,49): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId' and 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1409,56): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope' and 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1414,49): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope' and 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1420,22): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1421,22): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1426,42): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1426,74): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1429,26): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1429,53): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1431,26): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal' and 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1463,56): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId' and 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1468,49): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId' and 'Codeunit5022165.TryAddToList_Scope_62675578.αscopeId'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1476,56): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope' and 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1481,49): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope' and 'Codeunit5022165.TryAddToList_Scope_62675578.γeventScope'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1487,22): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1488,22): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1493,42): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1493,74): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1496,26): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd' and 'Codeunit5022165.TryAddToList_Scope_62675578.listToAdd'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1496,53): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement' and 'Codeunit5022165.TryAddToList_Scope_62675578.valueElement'
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\150\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\85\85C56EFE7D1C746AC24802DB78789023D8C34C6B7EAB6FBBBA33DF48A503C91E.cs(1498,26): error CS0229: Ambiguity between 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal' and 'Codeunit5022165.TryAddToList_Scope_62675578.γretVal'

**5. Versions:**

 - AL Language: 4.0.218468

 - Business Central: 15.1.37881.38709

**Comment by KristofKlein** [comment]
Hi ,

just a comment to this as i was also crashing with it. I have an overload like this:
local procedure DoStuffWith(lt: List of [Text])
     begin
     end;


   local procedure DoStuffWith(lt: List of [Code[20]])
      begin
    end;

also this one crashes the deployment on the service tier - while building worked fine. 

AL Language: 4.0.249486
BC 15.2.39040 OnPrem

**Comment by KristofKlein** [comment]
or something like this:

    local procedure DoStuffWith(doit: Dictionary of [Integer, Text])
    var
        item: Integer;
    begin
        foreach item in doit.Keys do begin
            Message('It is me: %1', doit.Get(item));
        end;
    end;

    local procedure DoStuffWith(doillt: Dictionary of [Integer, List of [List of [Text]]])
    var
        item: Integer;
    begin
        // I have no idea .....
    end;

**Comment by qutreson** [comment]
This issue has been fixed for AL extensions with version higher than 6.0.249350
