### ISSUE TITLE
“ProcessReportForData” function in Custom Layout Reporting codeunit 8800 is not working in AL

### ISSUE THREAD

**Issue by rajeshrawat14** [microsoft/AL#5602]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to '...'I have created a new report in AL and by using the function “ProcessReportForData” ,we need document wise PDF to be generated.This functions is available in OnPremise and it is working but not working in Extensions.
2. Need the function LOCAL GenerateFileName in codeunit 8800 to be external.

Before :
FileName := OutputFileBaseName + ' for '+ObjectName + Extension;

After

FileName := OutputFileBaseName + ' for ' + **FORMAT(IteratorJoinFieldRef.VALUE)**+ObjectName + Extension;//RR

This will generate documentwise PDF.

``` AL Code to reproduce the issue ```

RecRef.OPEN(DATABASE::"Cust. Ledger Entry");
CustomLayoutReporting.SetOutputFileBaseName('Invoice');
CustomLayoutReporting.ProcessReportForData(ReportSelections.Usage::"S.Invoice",RecRef,CustomerLedgerEntry.FIELDNAME("External Document No."),
  DATABASE::"Cust. Ledger Entry",CustomerLedgerEntry.FIELDNAME("External Document No."),TRUE);

**Expected behavior**
Use the above code in AL in a new report using the function ProcessReportForData,generate document wise pdf.

**Screenshots**

**5. Versions:**

 - AL Language: Yes

 - Business Central:

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
