### ISSUE TITLE
Error: Power() Function delivers wrong result / big decimal value calculation is wrong

### ISSUE THREAD

**Issue by DBiernat** [microsoft/AL#5603]
**Describe the bug**
The result of the Power function is incorrect for the last one or two digits, if the decimal values are big enough. Also subtracting a value delivers a wrong result 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new docker container from "bcinsider.azurecr.io/bcsandbox-master"
2. Create a new project with the given code (see below)
3. Build the app and call the procedure
4. As a result the Message 'Equal' is shown, which is wrong

```
    procedure TestPower()
    var
        v1, v11, v2, v22 : Decimal;
    begin
        begin
            v1 := Power(2, 63);
            v11 := v1 - 1.0;

            v2 := Power(2, 63);
            v22 := v2 - 5.0;

            if (v11 <> v22) then
                Message('Not Equal')
            else
                Message('Equal');
        end;
    end;
```

**Expected behavior**
The correct values should be calculated.

**5. Versions:**
 - AL Language: 5.0.212041
 - Business Central: W1 16.0 (Platform 15.0.39228.0 + Application 16.0.10771.0)

The error also occurs in minor versions and in C/SIDE.

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
