### ISSUE TITLE
RAD does not publish profile Objects

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/AL#5604]
**Describe the bug**
If your extension includes a profile object it gets transferred correctly with a full publish (e.g. can be checked in BC afterwards in the Profiles Page). If you now do a RAD of the same extension (without even changing a single line of code) the profiles are gone.

**To Reproduce**
1. do AL:Go
2. create a Profile Object
3. Publish the App normal
4. confirm that profile exists in BC
5. run a RAD
6. confirm that profile doe no more exists in BC

``` AL Code to reproduce the issue ```

profile "MyProfile"
{
    Caption = 'Profile Display Name';
    RoleCenter = "Accountant Role Center";
    ProfileDescription = 'Profile Description';
}

**Expected behavior**
no matter what if it is a RAD or normal Publish - RAD should not "delete" things/data

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.200795 and 4.0.218468

 - Business Central:
OnPrem - Version: Platform 15.0.36510.0 + Application 15.0.36560.36626

**Comment by kalberes** [comment]
That is true. Empty RAD removes the profile.

**Comment by atoader** [comment]
This issue has been fixed in the 16.0 release of the product. Please open a new issue if you believe this has not been resolved and reference the current issue.
