### ISSUE TITLE
Add ability to block blocks from analysis (or specific rules)

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#5605]
**Title**
Get a ton of warnings for issues that are a non-issue, where I want it to throw the run time error.

**Description**
I don't want to disable the rule as a whole, e.g. AA0139, but I want to be able to turn it off when I pass it into a function that is external to my code (and thus want it to throw) as the function should resolve this for me.

**Reason for the rule**
Hides warnings that are not relevant to dev, making it easier to process rules quickly.

**Good and bad practices for fixing the rule**
Good solution would be something that can turn off the compiler warnings for certain sections, such as:
//IGNORE-BEGIN:AA0139,AW0009,...
code
//IGNORE-END:AA0139,AW0009,...

**Remarks**
It would be a huge QoL improvement as I am currently diffing to find new issues.

**Comment by TKapitan** [comment]
+1 for this enhancement, need it too!
