### ISSUE TITLE
EnumExtension dependency

### ISSUE THREAD

**Issue by qperis** [microsoft/AL#5609]
**Describe the bug**
Getting an error when deploying an app C which uses enum from app A, which is extended in app B. All dependencies are defined. I can not use extended enums in other apps.

**To Reproduce**

Steps and to reproduce the behavior:
[AllApps A B C.zip](https://github.com/microsoft/AL/files/4086219/AllApps.A.B.C.zip)
1. Publish and install app A from VSCode;
2. Publish and install app B from VSCode, (dependencies:  A);
3. Publish and install app C from VSCode, (dependencies:  A,B); <- error occur here.

**Expected behavior**
Successful installation of 3 apps that depends from each other. 

**Screenshots**
Each app has only few lines of custom code:

A. App, create enum:
![image](https://user-images.githubusercontent.com/51997546/72726928-4bba8380-3b92-11ea-85e5-29c9a55226ac.png)

B. App, extend enum (using this enum in this app does not seem to cause any errors, but it does in app C):
![image](https://user-images.githubusercontent.com/51997546/72726979-70166000-3b92-11ea-812a-739db913cc68.png)

C. App, getting an error during deployment if this enum is used, error occur during publish, no compiler error is showen before:
![image](https://user-images.githubusercontent.com/51997546/72727227-0fd3ee00-3b93-11ea-8b3a-f81dabd8c469.png)
.

Event log shows:

Index              : 6869
EntryType          : Error
InstanceId         : 701
Message            : Server instance: NAV
                     Category: Development
                     ClientSessionId: 00000000-0000-0000-0000-000000000000
                     ClientActivityId: 0e272b0c-f156-4472-8e75-4be013eaed4e
                     ServerSessionUniqueId: 6f5fce64-5f9f-4d05-8e7f-baaa1f878db2
                     ServerActivityId: 568cf7fc-6e92-4288-816c-2b77a070b931
                     EventTime: 01/20/2020 12:41:43
                     Message Failed request -- Method:POST; Url:http://bc1:7049/nav/dev/apps?SchemaUpdateMode=forcesync
                     &DependencyPublishingOption=default; StatusCode:422; ReasonPhrase:Unprocessable Entity; Token:
                     ProcessId: 2292
                     Tag: 00006NR
                     ThreadId: 130
                     CounterInformation:
Category           : (33)
CategoryNumber     : 33
ReplacementStrings : {Server instance: NAV
                     Category: Development
                     ClientSessionId: 00000000-0000-0000-0000-000000000000
                     ClientActivityId: 0e272b0c-f156-4472-8e75-4be013eaed4e
                     ServerSessionUniqueId: 6f5fce64-5f9f-4d05-8e7f-baaa1f878db2
                     ServerActivityId: 568cf7fc-6e92-4288-816c-2b77a070b931
                     EventTime: 01/20/2020 12:41:43
                     Message Failed request -- Method:POST; Url:http://bc1:7049/nav/dev/apps?SchemaUpdateMode=forcesync
                     &DependencyPublishingOption=default; StatusCode:422; **ReasonPhrase:Unprocessable Entity;** Token:
                     ProcessId: 2292
                     Tag: 00006NR
                     ThreadId: 130
                     CounterInformation: }
Source             : MicrosoftDynamicsNavServer$NAV
TimeGenerated      : 2020-01-20 14:41:43
TimeWritten        : 2020-01-20 14:41:43
UserName           :

**5. Versions:**
Version: 14.6.36463.0-W1
Platform: 14.0.36457.0
VSCode: 1.41.1
AL: 4.0.218468

**Comment by kalberes** [comment]
I have tried reproing it with your code base but a slightly better workspace, since what you have in the zip file it is a bit messy. Many empty workspaces.
If you work with version >= 15
You should create a workspace outside your folders and add A, B, C folders belonging to that.
Build A then B then C,
Publish A, then B then C.
No repro, things work fine on the latest Spring 2020 code base.

**Comment by qperis** [comment]
Is it possible to fix it in:

Versions:
Version: 14.6.36463.0-W1
Platform: 14.0.36457.0
VSCode: 1.41.1
AL: 4.0.218468

**Comment by kalberes** [comment]
Unfortunately, we do not fix older version issues based on problems raised here. I have not changed the code, just have created 3 folders a proper workspace having these folders,  and added the proper project to project dependencies between the apps in the app.json -s. 

The official answer is below:

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by qperis** [comment]
Well, could you still attach the files/project that works for you please? Then we will close this issue :)

**Comment by atoader** [comment]
@qperis is this still a problem for you?

**Comment by qperis** [comment]
We moved project from bc14 to bc15, error does not occur in bc15, so we can probably close the issue.
