### ISSUE TITLE
Variable assignment in Visible Property of the Page Field is not working in V15.2

### ISSUE THREAD

**Issue by kristianeWiise** [microsoft/AL#5611]
**Describe the bug**
Global Variable were used in Visible Property of the Field in the Page to dynamically hide/show the field. However this doesn't seems to work in V15.2 even if we hard coded the value of the variable to true. 

Sample Code below : 

[Field Property AL Code](https://github.com/kristianeWiise/MSBug-Field-Property)

**Expected behavior**
The custom field 3 should show in the page if the value of the variable is true.

**Screenshots**
![image](https://user-images.githubusercontent.com/60126907/72856791-b8a75800-3d0f-11ea-9fe1-9a1103019d4e.png)

**Versions:**

 - AL Language:  4.0.218468

 - Business Central: AU Business Central 15.2 (Platform 15.0.39461.39737 + Application 15.2.39060.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
