### ISSUE TITLE
License covering ISV Range

### ISSUE THREAD

**Issue by Kapil365** [microsoft/AL#5612]
Hi All

We have an ISV Vertical Solution with Object ranging in 1400000 Series. My query is that now we are upgrading our solution from NAV to BC 15. Technically we are almost there wish some small stuff pending can you help us what could be Licensing requirements / Complexities in terms of moving to full Cloud.

-	Is moving to AppSource only way to migrate ISV Solutions ?
If your answer is ‘NO’ than can you please help us how do we need to load License covering ISV Object Range in the Cloud version since we have no ways to load License the way it used to be in old NAV days.

**Comment by mjmatthiesen** [comment]
AppSource is the only way, unless you renumber everything to the 50000-99999 range

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
