### ISSUE TITLE
Report.SaveAs with reportformat::Excel crashes for Word layouts

### ISSUE THREAD

**Issue by DunshineNL** [microsoft/AL#5616]
When using Report.SaveAs with reportformat::Excel on a report with a default Word lay-out, the client crashes. I've tested all other reportformats, and they work fine for the exact same report.

When I switch the same report to use an RDLC lay-out, the reportformat::Excel does work fine.

So it seems an issue with the combination of a Word layout and reportformat::Excel.

- AL Extension Version: 4.0.218468

- Server Version: 15.2.39558.39825-nl

                trigger OnAction()

                var
                    TempBlob_lRec: Codeunit "Temp Blob";
                    BlobOutStream: OutStream;
                    FileMgt: Codeunit "File Management";
                begin
                    TempBlob_lRec.CreateOutStream(BlobOutStream, TEXTENCODING::UTF8);
                    REPORT.SAVEAS(50112, '', reportformat::Excel, BlobOutStream);
                    FileMgt.BLOBExport(TempBlob_lRec, 'test.xlsx', TRUE);
                end;

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
