### ISSUE TITLE
WinForms C# performing a Post (or Patch) to insert/update data through AL/D365BC web service

### ISSUE THREAD

**Issue by clemenslinders** [microsoft/AL#5617]
LS,

Within some months we will be migrating from SAP to D365BC. We created a lot of work arounds for SAP using C# WinForms.

One of the things we will face is rewriting a lot of C# programs into AL.

But there will be cases where it is easier to have our existing C# program communicate with the D365BC database in stead of our current SAP database. (Especially in the beginning.)

In D365BC I created a simple table, ListPage and CardPage. I called it Workers and it contains No., First Name, Last Name and FunctionName.

I created a web service using the Card Page for this workers table.

I can use PostMan and I can read/insert/modify data.

Now I want to do the same in WinForms C#.

In C# I have successfully implemented the read/GET for both a list and a single record. So I can read all workers and I can read a single worker that are in D365BC in C# using the web service I setup in D365BC.
As it may help you to understand what it is that I am looking for I included this code. Also it is very difficult to find any data through Google on this subject, so perhaps I can help others by letting them know how at least I got the GET working.

The difficult part (I think) is to get to know what exactly I need to put in the RequestHeaders.
I know that for a PATCH I will have to use the odata.etag (to identify the right record). But where and how exactly and also how to pass my changed or new record back?

When I call upon the webservice with a GET, I get the following result (and as mentioned luckily I can intercept this data, the problem is the PUT and PATCH command):
{"@odata.context":"https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/ODataV4/$metadata#Company('CRONUS%20NL')/WorkersWebService","value":   [{"@odata.etag":"W/\"JzQ0O3oxcnZ1aEhkVlgxbFVtT2tvcXdpU0hwRU1xeG5rT0l3VVdYSk1EWWI4Ym89MTswMDsn\"","No":"1000","First_name":"Jan","Last_name":"Jansen","FunctionName":"Werker"},
{"@odata.etag":"W/\"JzQ0O01EQXJHWmhHTEhXaGJMVFZjMSttK2pXWVd5QkVrUnNVU3ZyQjJVeTBoUWs9MTswMDsn\"","No":"1001","First_name":"Piet","Last_name":"Pietersen","FunctionName":"Werker"},
{"@odata.etag":"W/\"JzQ0O1FkTk1jSStSVmExWUJhZDBOVlAzMmw3bWM4amI0bitpb2lrTWtqaVJJSDg9MTswMDsn\"","No":"1002","First_name":"Kees","Last_name":"de Vries","FunctionName":"Chef"}]}    

I use the NewtonSoft Json.Net library to deserialise the data and read it into my class, works great.
Before I do this I trim some junk (odata.context….. + \\\" twice in odata.etag) so that I get the json data I want.

 (To deserialise or serialise JSON data simply use Viusal Studio's Manage Nuget Packages for Solutions and without typing anything it is already there. Click on it to install is and add using Newtonsoft.Json )

To read the data from my web service I have the following code:

        private void button1_Click(object sender, EventArgs e)
        {
            string _url = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/ODataV4/Company('CRONUS%20NL')/WorkersWebService";
            HttpWebRequest _request = (HttpWebRequest)WebRequest.Create(_url);
            _request.ContentType = "application/json; charset=utf-8";
            _request.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes("USERNAME:PASSWORD"));
            _request.PreAuthenticate = true;
            HttpWebResponse _response = _request.GetResponse() as HttpWebResponse;
            using (Stream _responseStream = _response.GetResponseStream())
            {
                StreamReader _reader = new StreamReader(_responseStream, Encoding.UTF8);
                string _content = _reader.ReadToEnd();

                string _jasonPart = GetJsonPartMultiRecord(_content);

                List<WorkerClass> _jWorkers = JsonConvert.DeserializeObject<List<WorkerClass>>(_jasonPart);

                foreach (var _worker in _jWorkers)
                {
                    WorkersReadFromAlWebService.Add(_worker);
                }
            }
        }
To read a single record I created the following code (the trimming of junk data is a bit different):

        private void button2_Click(object sender, EventArgs e)
        {
            string _url = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/ODataV4/Company('CRONUS%20NL')/WorkersWebService('1000')";
            HttpWebRequest _request = (HttpWebRequest)WebRequest.Create(_url);
            _request.ContentType = "application/json; charset=utf-8";
            _request.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes("USERNAME:PASSWORD"));
            _request.PreAuthenticate = true;
            HttpWebResponse _response = _request.GetResponse() as HttpWebResponse;
            using (Stream _responseStream = _response.GetResponseStream())
            {
                StreamReader _reader = new StreamReader(_responseStream, Encoding.UTF8);
                string _content = _reader.ReadToEnd();

                string _jasonPart = GetJsonPartSingleRecord(_content);

                WorkerClass _jWorker = JsonConvert.DeserializeObject<WorkerClass>(_jasonPart);

                WorkersReadFromAlWebService.Add(_jWorker);
            }
        }

I hope someone can help me to do a PUT and PATCH so that we can insert and update records.
Another subject is that I have no idea how to delete a record (from C#)?

Kind regards,

Clemens Linders

**Comment by daansaveyn** [comment]
Hi,

Last couple of months I've been using the Business Central API's quite intensively. I also struggled to find out which headers to send. 

Below you can find a working C# sample of a PUT HTTP Request on one of our custom BC API's. 

`using System;
using System.IO;
using System.Net;
using System.Text;

namespace HttpPutSample
{
    class Program
    {
        static void Main(string[] args)
        {
            DoTest();
            Console.ReadLine();
        }

        private static void DoTest()
        {
            string _url = String.Format(@"http://productsrv.youngpartners.local:7276/CONFIG_09/api/navitrans/xd/v1.0/parcels('{0}')", "6823-0002");
            HttpWebRequest _request = (HttpWebRequest)WebRequest.Create(_url);
            _request.ContentType = "application/json; charset=utf-8";
            _request.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(@"USERNAME:PASSWORD"));
            _request.Accept = "*/*";
            _request.KeepAlive = true;
            _request.Method = "PUT";
            string _etag = "JzQ0O0lTQ0FGUCt1K1k4aU04V2p0aEdKdDIyT2FnWHZPajQ0bDhZTitOb3NKNW89MTswMDsn";
            _request.Headers["If-Match"] = String.Format("W/\"{0}\"", _etag);

            var body = @"{
              ""externalParcelCode"": """",
              ""customerParcelCode"": """",
              ""customerCode"": ""C10540"",
              ""customerReference"": ""TEST UPDATE PARCEL"",
              ""senderCode"": ""C10540"",
              ""senderName"": ""ASSFOR EXPEDITEURS NV"",
              ""senderAddress"": ""RIJNKAAI 21-22"",
              ""senderPostalCode"": ""2000"",
              ""senderCity"": ""ANTWERPEN"",
              ""senderCountry"": ""BE"",
              ""senderReference"": """",
              ""addresseeCode"": ""ADR-0000002"",
              ""addresseeName"": ""SUR-SERVICES"",
              ""addresseeAddress"": ""RUE D'ARTAGNAN 27"",
              ""addresseePostalCode"": ""4600"",
              ""addresseeCity"": ""VISE"",
              ""addresseeCountry"": ""BE"",
              ""addresseeReference"": """",
              ""length"": 0,
              ""width"": 0,
              ""height"": 0,
              ""grossWeight"": 0,
              ""loadingLength"": 0,
              ""quantityinParcel"": 0,
              ""orderDate"": ""2020-01-01"",
              ""unitofMeasure"": """",
              ""countryofOrigin"": """",
              ""tariffCode"": """",
              ""itemCode"": """",
              ""itemDescription"": """",
              ""uNNoPK"": 0,
              ""valueCurrency"": """",
              ""valueofGoods"": 0
            }
            ";

            byte[] data = Encoding.ASCII.GetBytes(body);

            _request.ContentLength = data.Length;

            Stream requestStream = _request.GetRequestStream();
            requestStream.Write(data, 0, data.Length);
            requestStream.Close();

            HttpWebResponse _response = _request.GetResponse() as HttpWebResponse;
            Console.WriteLine(_response.StatusCode);

        }
    }
}
`

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by clemenslinders** [comment]
Hi daansaveyn,

Your sample helped a lot.

Thanks.

**Comment by clemenslinders** [comment]
I understand that this repository no longer handles general questions.

But when I keep looking for this problem Google shows this issue. So other people will find this issue. And it would be a shame if they would find this issue but not a solution. Also it is incredible hard to find anything on this subject I think many people would like to have a working solution for this problem (although this solution is SOAP and not ODATA).

First of all let me start by stating that I could not (up to this moment) get this working in ODATA. The answer of DaanSaveyn helped me a lot to go into the right direction. And I expected it to work. But when I use it I get the error: 405 Method not allowed??

The approach above is based on ODATA and as mentioned something is missing as it gives the error 405 Method not allowed.

However if you use SOAP (D365BC gives 3 URL's the most right one being SOAP), than this is the solution.

First you need to add a reference. In solution explorer/reference/add reference. Pass the url here and click GO. If you need to logon and if that doesn't work. open a browser and pass that url. Your browser will now ask for username/password. Pass your credentials her, keep the page open. And back in visual studio continue with adding the reference. This should now not be a problem.

In your c# form page add at the top:
using AL_WS_Comm.D365BCWS;//Before the point the name of the namespace, after the point the name you entered when you added the service reference.

Reading from the web service:
        private void btnZoekWerkersHttp_Click(object sender, EventArgs e)
        {
            listBox1.Items.Clear();
            WorkersReadFromAlWebService = new List<WorkerClass>();
            string _wsURL = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/WS/CRONUS%20NL/Page/WorkersWS";
            string _userName = "USERNAME";
            string _wsKey = "PASSWORD";

            //Create an instance of the D365BC SOAP WS
            BasicHttpBinding _binding = new BasicHttpBinding();

            //Set https usage
            _binding.Security.Mode = BasicHttpSecurityMode.Transport;
            _binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

            using (WorkersWS_PortClient _ws = new WorkersWS_PortClient(_binding, new EndpointAddress(_wsURL)))
            {
                _ws.ClientCredentials.UserName.UserName = _userName;
                _ws.ClientCredentials.UserName.Password = _wsKey;

                //Filter
                List<WorkersWS_Filter> _filters = new List<WorkersWS_Filter>();
                WorkersWS_Filter _filter = new WorkersWS_Filter
                {
                    Field = WorkersWS_Fields.No,
                    Criteria = "*"
                };
                _filters.Add(_filter);

                try
                {
                    foreach (WorkersWS _workerWS in _ws.ReadMultiple(_filters.ToArray(), "", 0))
                    {
                        WorkerClass _wc = new WorkerClass();
                        _wc.E_Tag = _workerWS.Key;
                        _wc.First_Name = _workerWS.First_name;
                        _wc.Last_Name = _workerWS.Last_Name;
                        _wc.FunctionName = _workerWS.FunctionName;
                        WorkersReadFromAlWebService.Add(_wc);
                        listBox1.Items.Add(_workerWS.Last_Name + " / " + _workerWS.First_name + " (No: " + _workerWS.No + ")");
                    }
                }
                catch (Exception _ex)
                {

                }
            }
        }

Adding a record:
        private void btnCreateHttp_Click(object sender, EventArgs e)
        {
            string _wsURL = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/WS/CRONUS%20NL/Page/WorkersWS";
            string _userName = "USERNAME";
            string _wsKey = "PASSWORD";

            //Create an instance of the D365BC SOAP WS
            BasicHttpBinding _binding = new BasicHttpBinding();

            //Set https usage
            _binding.Security.Mode = BasicHttpSecurityMode.Transport;
            _binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

            WorkersWS_PortClient _ws = new WorkersWS_PortClient(_binding, new EndpointAddress(_wsURL));
            _ws.ClientCredentials.UserName.UserName = _userName;
            _ws.ClientCredentials.UserName.Password = _wsKey;

            try
            {
                WorkersWS _wws = new WorkersWS();
                _wws.No = tbNo.Text;
                _wws.First_name = tbFirstName.Text;
                _wws.Last_Name = tbLastName.Text;
                _wws.FunctionName = tbFunctionName.Text;

                _ws.Create(ref _wws);

                tbResult.Text = _wws.No;
            }
            catch (Exception _ex)
            {

            }
        }

Deleting a record:
            string _wsURL = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/WS/CRONUS%20NL/Page/WorkersWS";
            string _userName = "USERNAME";
            string _wsKey = "PASSWORD";

            //Create an instance of the D365BC SOAP WS
            BasicHttpBinding _binding = new BasicHttpBinding();

            //Set https usage
            _binding.Security.Mode = BasicHttpSecurityMode.Transport;
            _binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

            WorkersWS_PortClient _ws = new WorkersWS_PortClient(_binding, new EndpointAddress(_wsURL));
            _ws.ClientCredentials.UserName.UserName = _userName;
            _ws.ClientCredentials.UserName.Password = _wsKey;

            try
            {
                WorkersWS _wws = _ws.Read("1003");//Read contains a string that matches the primary key of the table. It's value is assigned by a way the programmer sees fit
                if (_wws.No == "1003")
                {
                    _ws.Delete(_wws.Key);//The Key field here (or E_Tag in ODATA) is the MASTER primary key. It's value is provided bij D365BC
                }
            }
            catch (Exception _ex)
            {

            }

Updating a record:
string _wsURL = "https://api.businesscentral.dynamics.com/v2.0/SomeFunkyGuid/Sandbox/WS/CRONUS%20NL/Page/WorkersWS";
            string _userName = "USERNAME";
            string _wsKey = "PASSWORD";

            //Create an instance of the D365BC SOAP WS
            BasicHttpBinding _binding = new BasicHttpBinding();

            //Set https usage
            _binding.Security.Mode = BasicHttpSecurityMode.Transport;
            _binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

            using (WorkersWS_PortClient _ws = new WorkersWS_PortClient(_binding, new EndpointAddress(_wsURL)))
            {
                _ws.ClientCredentials.UserName.UserName = _userName;
                _ws.ClientCredentials.UserName.Password = _wsKey;

                try
                {
                    WorkersWS _wws = _ws.Read(tbNo.Text);
                    if (_wws.No == tbNo.Text)
                    {
                        _wws.First_name = tbFirstName.Text;
                        _wws.Last_Name = tbLastName.Text;
                        _wws.FunctionName = tbFunctionName.Text;
                        _ws.Update(ref _wws);

                        if (_wws.No == tbNo.Text)
                        {
                            tbResult.Text = "Update success.";
                        }
                    }
                }
                catch (Exception _ex)
                {

                }
            }

In my attempts to get ODATA working I added 2 webservices. One is based on the Card Page (as suggested in all samples). But a Card Page doesn't have the ability to Create and Modify. So I created a second webservice, this time based on the List Page. I must say that this sample uses the web service based on the List Page. It's better that I tell you this as there is still the possibility that it doesn't work with a Card Page (haven't tried that yet, I am way to happy that this is working)

To be complete I also will add my D365BC code:

CpWorkers.AL
page 50108 "Workers Card"
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = Workers;

    layout
    {
        area(Content)
        {
            group(General)
            {
                field("No."; "No.")
                {
                    ApplicationArea = Basic;
                    Importance = Promoted;
                }

                field("First name"; "First name")
                {
                    ApplicationArea = Basic;
                }

                field("Last name"; "Last name")
                {
                    ApplicationArea = Basic;
                }

                field(FunctionName; FunctionName)
                {
                    ApplicationArea = Basic;

                }
            }
        }
    }
}

LpWorkers.AL
page 50109 "Workers List"
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = Workers;

    layout
    {
        area(Content)
        {
            repeater(Group)
            {
                field("No."; "No.")
                {
                    ApplicationArea = Basic;
                }

                field("First name"; "First name")
                {
                    ApplicationArea = Basic;
                }

                field("Last Name"; "Last Name")
                {
                    ApplicationArea = Basic;
                }

                field(FunctionName; FunctionName)
                {
                    ApplicationArea = Basic;
                }
            }
        }
    }
}

TabWorkers.AL
table 50109 "Workers"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "No."; Code[20])
        {
            DataClassification = ToBeClassified;
        }

        field(10; "First name"; Text[50])
        {
            DataClassification = ToBeClassified;
        }

        field(20; "Last Name"; Text[50])
        {
            DataClassification = ToBeClassified;

        }

        field(40; FunctionName; Text[50])
        {
            DataClassification = ToBeClassified;

        }
    }

    trigger OnInsert()
    var
        myInt: Integer;
    begin

    end;

    trigger OnModify()
    var
        myInt: Integer;
    begin

    end;

    trigger OnDelete()
    var
        myInt: Integer;
    begin

    end;
}

WorkersWebService.xml (based on the Card Page, this would be the generally excepted choice)
<?xml version = "1.0" encoding = "utf-8" ?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenanatWebService>
            <ObjectType>Page</ObjectType>
            <ObjectID>50108</ObjectID>
            <ServiceName>WorkersWebService</ServiceName>
            <Published>true</Published>
        </TenanatWebService>
    </TenantWebServiceCollection>
</ExportedData>

WorkersWS.xml (based on the List Page, I used this in my SOAP web service)
<?xml version = "1.0" encoding = "utf-8" ?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenanatWebService>
            <ObjectType>Page</ObjectType>
            <ObjectID>50109</ObjectID>
            <ServiceName>WorkersWS</ServiceName>
            <Published>true</Published>
        </TenanatWebService>
    </TenantWebServiceCollection>
</ExportedData>


Publishing the whole thing in D365BC may also be problematic as at this moment it seems to work differently from the samples I saw on the internet. What worked for me:

Ctrl-Shift P, Publish without debugging.

In D365BC at the top menu at the magnifier type web service (note the space) and type: web services. Click on Web services List.

On several YouTube video’s the webservice is created and after publishing it is immediately available in the Web services list. However for me this was not the case.
In the top menu of the web services list page there is a New button.

Click on this New button (an empty line will appear at the top or bottom of the grid) and copy Object Type, Object ID and Service name from the XML page.
Select Published and unselect All tenants, the object name can be selected (50109 is called WorkersList). You may of course also use 50108 based on the Card Page, Whatever you choose.

Now you have a complete set of documentation to get a SOAP web service up and use it in C# .


I hope they will keep and show this reply because I think many people would like to see this. It took me quite some days to figure all this out.

I hope it is of use to some people. And if someone knows how to do this in ODATA, I would still like to know (ODATA is faster).


Kind regards,


Clemens Linders
