### ISSUE TITLE
Bug in Insert with ChangeCompany

### ISSUE THREAD

**Issue by MBK75** [microsoft/AL#5618]
**Describe the bug**
Writing to a custom table across companies via ChangeCompany results in a primary key violation when no records exist.  We have been wrangling on this issue for weeks with support and they directed us to GitHub.  I realize that a StartSession call may avoid this problem but this is still a bug and should be addressed.  The overhead of StartSession may not be necessary in our case (in fact it is a little bit problematic at the moment).

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a Cronus Docker Container with the latest sandbox
2. Initialize the "My Company" company
3. Install the attached extension
4. Open a new tab in the browser and go to the Cronus company
5. Open a Vendor Card and make a small change (i.e. add a 2 to the end of the name)
6. The custom extension (attached) will write a log entry to the other company
7. #6 above results in a primary key violation even when no records exist.  This does not always happen on the first try in a clean container but will happen after the second update and then perpetually.  That said, I can see it in a new container 95% of the time on the first try

``` AL Code to reproduce the issue ```
Attached but the bulk of the logic is in the codeunit here:

`    procedure HandleSynchronization(TableID: Integer; RecID: RecordId; SyncAction: Option "Insert","Modify","Delete","Rename"; RenameValue: Code[20]; RunCodeunitId: Integer)
    var
        Company: Record "Company";
        MyEventLog: Record "My Event Log";
        EntryNo: Integer;
        LatestVersionSelected: Boolean;
    begin
        Company.FindSet();
        repeat
            if Company.Name <> CompanyName then begin
                if not LatestVersionSelected then
                    SelectLatestVersion();
                LatestVersionSelected := true;

                MyEventLog.ChangeCompany(Company.Name);
                MyEventLog.LockTable();
                MyEventLog.SetCurrentKey("Entry No.", Processed);
                MyEventLog.SetRange("From Company Name", CompanyName);
                MyEventLog.SetRange("Table ID", TableID);
                MyEventLog.SetRange("Record ID", RecId);
                MyEventLog.SetRange(Processed, false);

                MyEventLog.DeleteAll(true);

                MyEventLog.Reset();
                MyEventLog.ChangeCompany(Company.Name);
                //The below is removed to show that there are no records at all in the table
                // MyEventLog.SetRange("From Company Name", CompanyName);
                // MyEventLog.SetRange("Table ID", TableID);
                // MyEventLog.SetRange("Record ID", RecId);
                if MyEventLog.FindLast() then
                    EntryNo := MyEventLog."Entry No.";
                EntryNo += 1;

                MyEventLog.Reset();
                MyEventLog.Init();
                Clear(MyEventLog);
                MyEventLog."From Company Name" := CompanyName;
                MyEventLog."Table ID" := TableID;
                MyEventLog."Record ID" := RecID;
                MyEventLog."Entry No." := EntryNo;
                MyEventLog."Sync Action" := SyncAction;
                MyEventLog."Rename Value" := RenameValue;
                MyEventLog."Run Codeunit ID" := RunCodeunitID;
                MyEventLog.Insert(true);

                Commit();  //<<---------- Error Occurs
            end;
        until Company.Next() = 0;
    end;`

**Expected behavior**
An insert across companies with no primary key error

**Screenshots**
N/A

**5. Versions:**

 - AL Language: 4.0.218468

 - Business Central: bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
[CrossCompanyError.zip](https://github.com/microsoft/AL/files/4110828/CrossCompanyError.zip)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by MBK75** [comment]
Hi atoader, do you have a link for Collaborate? The state of BC support is terrible right now - they directed me here. I'm not finding an easy link for it
