### ISSUE TITLE
HttpClient GET with oauth2 token fails

### ISSUE THREAD

**Issue by elisav** [microsoft/AL#5619]
**Describe the bug**
HttpClient.Get(...) fails when an oauth2 bearer token is used for authentication.

The HttpStatusCode and ReasonPhrase are 200 OK.

This works in Postman, as a GET call with only the Authorization header specified. I tried many GET calls without authentication in AL and they worked fine.

**To Reproduce**
Run the following code with a valid bearer token and URL:

```
    procedure GetAPI(token: Text; url: Text): Text
    var
        client: HttpClient;
        responseMsg: HttpResponseMessage;
    begin
        client.SetBaseAddress(url);
        client.DefaultRequestHeaders.Add('Authorization', StrSubstNo('Bearer %1', token));
        if client.Get(url, responseMsg) then begin
            exit("Success");
        end
    end;
```

This similar code in C# works:

```
        private static string GetAPI(string token, string url)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
            var responseMsg = client.GetAsync(new Uri(url)).Result;
            return(responseMsg.Content.ReadAsStringAsync().Result);
        }
```

**Expected behavior**
A successful HttpClient.Get.

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.218468

 - Business Central: 15.0.38951.0

**Comment by navdotnetreqs** [comment]
I have the same problem with Basic-authorization. Otherwise exactly the same code.

I always get an error "An error occurred while sending the request."

Works with postman and Advanced REST client.

And obviously there is no way to get the real internal exception, even using c# getlasterrorobject().

Brilliant how this has been an open bug for more than half a year.

**Comment by elisav** [comment]
@navdotnetreqs I got it working by clearing the client before setting the request headers and removing SetBaseAddress. Does that work for you?

```
procedure GetAPI(token: Text; url: Text): Text
    var
        Client: HttpClient;
        ResponseMsg: HttpResponseMessage;
    begin
        Client.Clear();
        Client.DefaultRequestHeaders.Add('Authorization', StrSubstNo('Bearer %1', token));
        if Client.Get(url, ResponseMsg) then begin
            exit("Success");
        end
    end;
```
