### ISSUE TITLE
The type or method 'Aggregate Permission Set' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#562]
We have a scenario in our Extension that user will go through the Wizard to setup the Extension, a wizard screen wíll be prompted if the USER has SUPER as Permission, with Question if he/she want to add the Permission set associated to the Extension for all the users.

There is nothing WOW in having a super user to install the extension and then afterwoods have to locate the users setup to add permission set to all users. 

Do you have a nice solution to have the "Customers" adding th permission sets in a nicely manner during af WOW experience installed from Appsource.

**Comment by StanislawStempin** [comment]
This table has been exposed.
