### ISSUE TITLE
AL extension in macOS: can't publish web services

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#5620]
If you try to publish an AL app to Business Central that includes one or more xml files that publish objects as web services, publishing fails with an "Object reference not set":

    [2020-01-27 10:39:27.10] The request for path /navserverdev/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code 422. Reason: Could not install the extension Test on tenant default due to the following error: Object reference not set to an instance of an object.

In order to reproduce it, you just have to create a new project with a simple codeunit:

```
codeunit 50100 Test
{
    procedure Test()
    begin
    end;
}
```

And add an xml file that publishes it as a web service:

```
<?xml version="1.0" encoding="utf-8"?>
<ExportedData>
    <TenantWebServiceCollection>
        <TenantWebService>
            <ObjectType>5</ObjectType>
            <ServiceName>Test</ServiceName>
            <ObjectID>50100</ObjectID>
            <Published>true</Published>
        </TenantWebService>
    </TenantWebServiceCollection>
</ExportedData>
```

The app publishes without problems if using the AL Extensions in VS Code for Windows, but fails with the specified error if published from VS Code for macOS.

AL Language Extension: 4.0.218468
Business Central version: 15.1.37285.0 (es)

**Comment by atoader** [comment]
Can you try with the latest preview release? This should have been fixed.

**Comment by salgiza** [comment]
Hi @atoader , I've just checked with AL extension 5.0.236243 and I can confirm that it is indeed fixed! 😄
