### ISSUE TITLE
"You cannot change the value of the SystemId field" - when using SetPosition

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#5621]
We're passing the source record of a list page to a function as a VAR parameter. The code is something like this:

procedure (var OurRecord: Record "Our Table");
var
  Position: Text;
  View: Text;
begin
  Position := OurRecord.GetPosition();
  View := OurRedcord.GetView();

  OurRecord.SetRange("Some Field or Other", SomeValue);
  OurRecord.FindSet();
  repeat
    //something wonderful happens in here...but isn't relevant to the issue
  until OurRecord.Next() = 0;

  OurRecord.SetRange("Some Field or Other");
  OurRecord.SetView(View);
  OurRecord.SetPosition(Position);
end;

We use the method to draw a chart from the records on the page (we need to group the data first before drawing the chart) but then returning the record to the page with the same filters and active record as it had originally.

This function is throwing the error "You cannot change the value of the SystemId field".

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
