### ISSUE TITLE
Procedures should have less than 100 lines of code

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#5624]
**Title**
Procedures should have less than 100 lines of code

**Description**
Code is easier to understand when it is broken down into multiple procedures with a defined purpose..

**Reason for the rule**
Very long procedures are hard to read and result in code that is hard to maintain and reuse.

**Bad code sample**
Example of what bad code the rule should catch:

```     
    procedure DoSomethingComplicated()
    begin
        [Hundreds of lines of code doing everything]
    end;
```

**Good code sample**
Example of what code should look like:

``` 
    procedure DoSomethingComplicated()
    begin
        CheckSomething();
        CreateSomething();
        PostSomething();
    end;

    local procedure CheckSomething()
    begin
        [...]
    end;
    
    local procedure CreateSomething()
    begin
        [...]
    end;
    
    local procedure PostSomething()
    begin
        [...]
    end;
    [...]
 ```

**Good and bad practices for fixing the rule**
Refactor the code into smaller procedures each with a clear and defined purpose and a descriptive name. 
Do not move variables to globals and just break the procedure into parts. 

**Remarks**
​Possibly an info not a warning.

**Comment by hhfiddelke** [comment]
I would also prefer to have less than 100 lines of code per Procedure, but sometimes it is not usefull.

I would say, that a developer who creates permanent large functions has the wrong job in most cases. Functions should have a usefull structure to be readable. That might be one line or 200 lines.

I would prefer to have a rule that checks if the same code is only written once. That would reduce the more than 100 lines functions in most cases.

**Comment by mjmatthiesen** [comment]
AL is too verbose for this. Once you have a function that deals with more than two records, you're at a hundred lines because of all the setrange/setfilter.

Plus with the ugly else if formatting that AL now does, you lose even more lines. Then it's another issue on whether you count comments, empty lines, and so on.

You also run the risk of creating a function that just calls a dozen other function that only exists for this function to be under a hundred lines, which in itself can be useless.

**Comment by AskeHolst** [comment]
I would not suggest this if I had not seen a lot of cases of procedures growing too large over the years.
It is usually not a matter of one developer writing a huge procedure to begin with, but something that grows and grows over time, often by multiple developers.
There are a few good cases for a long procedure, in that case, ignore the warning. But a lot of devs need a reminder that it might be a good idea to start refactoring.

Only proper code  inside the body of the procedure/trigger should be counted. I would actually prefer counting statements, not physical lines.

A great example is Sales Post in the base app that back in the day had a thoundsands of lines in the Code function. After rewriting to comply with the 100 line limit it became much better structured and easier to extend. 

Why 100? Because it is already in [the guidelines C/AL coding by Microsoft](https://cloudblogs.microsoft.com/dynamics365/no-audience/2015/01/09/cal-coding-guidelines-used-at-microsoft-development-center-copenhagen/?source=nav). AL is not that different from C/AL. Other languages/linters have defaults of 50 or even 20, but AL does naturally have more value assignments, so it makes sense to have a higher limit.

**Comment by hhfiddelke** [comment]
Aske, iam fully with you. But i don't want ignorable warnings that hide the warnings, i should pay attention on.
Let's take anonther example: have a look at the codunits 60 Sales-Calc. Discount and 57 Document Totals. They both do the same. Try to understand both codeflows. (i removed "Document Totals" in NAV2018 and replced it by "Sales-Calc. Discount". Now it calculates the correct invoice discount, and has no problems doing this with documents with more than 100 lines.).
I have no problems with 100 lines of code if it shows the flow ( as in "Sales-Calc. Discount") and we have small code blocks between BEGIN and END. (that was the problem with the posting codeunits)

If there should be a rule, define it "Codeblocks should not be larger than 20 Lines". But this is also a developer in head rule, not a rule that should be checked normaly. 
If it is disabled by default, no problem. It should be checked from time to time. And if there is a pragma to disable the check for specific functions, it would reduce the fog in the warnings.

**Comment by dtkb** [comment]
> But i don't want ignorable warnings that hide the warnings, i should pay attention on.

But to be realistic, such a warning as this must probably be info-only, by default, to not annoy other developers who... shall we say... could use a little help writing clean code. Otherwise it will just result in noise on this issue tracker. You or I could use `ruleset.json` to promote it to a warning or error.

**Comment by mazhelez** [comment]
Thank you for reporting this issue. Unfortunately, we do not find it important enough to address at this point.
