### ISSUE TITLE
Adding a listpart to page too much space on the Group

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/AL#5627]
![image](https://user-images.githubusercontent.com/53824412/73177590-b5e1a400-410f-11ea-9587-2ae151effa8b.png)

shows me on page too much empty space:

![image](https://user-images.githubusercontent.com/53824412/73177653-d873bd00-410f-11ea-9282-fb39f4113ce4.png)

how can i resolve this or is this a bug?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
