### ISSUE TITLE
SMTP Mail CreateMessage Method overload

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#5628]
Hello,

i want to use the function 
`procedure CreateMessage(FromName: Text; FromAddress: Text; Recipients: List of [Text]; Subject: Text; Body: Text; HtmlFormatted: Boolean)`
but if I call the function with this parameters
```
lcuSMTPMail.CreateMessage(
  "Sender Name",
  "Sender Mail",
  RecipientMailAddrList,
  MailSubject,
  BodyText,
  true);
```
The compiler get's an Error and thinks, that I want to use function
`procedure CreateMessage(FromName: Text; FromAddress: Text; Recipient: Text; Subject: Text; Body: Text; HtmlFormatted: Boolean)`
So the compiler shows me the error "Argument 3: cannot convert from 'List of [Text]' to 'Text' AL(AL0133)

**5. Versions:**

 - AL Language:  4.0.206840

 - Business Central: DE Business Central 15.2 (Platform 15.0.38951.0 + Application 15.2.39040.0)

**Comment by FSchneiderYav** [comment]
@kalberes

**Comment by kalberes** [comment]
@esbenk

**Comment by FSchneiderYav** [comment]
Any news?

**Comment by esbenk** [comment]
This should be fixed in the latest CU. Pls try to upgrade compiler and platform.

**Comment by atoader** [comment]
@FSchneiderYav the fix should definitely be part of Wave 1 2020 CU1. If you have access to the insider builds, you can give it a try.

**Comment by FSchneiderYav** [comment]
It works. Thank you for your help 👍
