### ISSUE TITLE
Download symbols remotly

### ISSUE THREAD

**Issue by AitorLD** [microsoft/AL#5630]
How to connect to download symbols remotly from server.

I have the web client published and accessible, but I',m not able to download symbols from visual code. I have also opened the ports, 7045,7046,7047,7048,7049.

Versión AL: 4.0.218468
This is the launch.json

{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://pre.bc.********/",
            "port": 7049,
            "serverInstance": "BC150",
            "authentication": "Windows",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
            //"schemaUpdateMode": "ForceSync"
        }
    ]
}

Error message from visual studio code console when donwloading symbols:

[01/30/2020 09: 50: 10.49] Error: Error sending the request.
Connection terminated: Unexpected sending error.
The link protocol could not be performed due to an unexpected packet format.

**Comment by AitorLD** [comment]
Anyone?

**Comment by kalberes** [comment]
As I understand this is an onprem server? Do you maybe have any hints in the event viewer where the server is located?

**Comment by AitorLD** [comment]
> As I understand this is an onprem server? Do you maybe have any hints in the event viewer where the server is located?

Yes, this is an onprem server.  What kind of hints? Error logs?

**Comment by kalberes** [comment]
Yes, entries in the eventlog for server errors/warnings that maybe related.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
