### ISSUE TITLE
Dynamically Change the Caption in a Field using Caption Class

### ISSUE THREAD

**Issue by kristianeWiise** [microsoft/AL#5633]
**Describe the bug**
OnAfterCaptionClassResolve doesn’t seems to get the latest Custom Caption based on the Custom Caption Field Setup.

**Sample Code below :**
https://github.com/kristianeWiise/MSBug-OnAfterCaptionClassResolve-DoesNot-Refresh

**Expected behavior**
The Caption of the Field should retrieve based on the latest Caption in the Custom Caption Field setup
Steps to Reproduce. 
1.	Search for Custom Caption Field Setup in Global Search
 
![image](https://user-images.githubusercontent.com/60126907/73622476-b341fa00-468d-11ea-95e0-e8bfdf6691e7.png)

2.	Then Search for Sales Order at the Sales Order action button select Order  Custom Information
 
![image](https://user-images.githubusercontent.com/60126907/73622489-bdfc8f00-468d-11ea-97b5-8d57c35a1c05.png)

3.	In the Custom Information page should show the latest Application Caption based on the Custom Caption Field Setup.
 
![image](https://user-images.githubusercontent.com/60126907/73622505-c0f77f80-468d-11ea-998b-571d89ea2407.png)

4.	Search for the Custom caption Field Setup then Change the Caption to “Test 2”
 
![image](https://user-images.githubusercontent.com/60126907/73622515-c48b0680-468d-11ea-9beb-d3a4ee8de796.png)

5.	Then Go to Sales Order again then select Order  Custom Information , the Custom Information Page should show now the latest Caption which should be “Test 2” 
![image](https://user-images.githubusercontent.com/60126907/73622530-c785f700-468d-11ea-9aca-9f7f5e1dba00.png)

**OnAfterCaptionClassResolve Subscriber Function**
 
![image](https://user-images.githubusercontent.com/60126907/73622552-cce34180-468d-11ea-9766-833936fc244d.png)

Versions:
•	AL Language: 4.0.218468
•	Business Central: AU Business Central 15.2 (Platform 15.0.39461.39737 + Application 15.2.39060.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
