### ISSUE TITLE
Unprocessable Entity error

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5637]
I'm recently facing lots of 'Unprocessable Entity' error when doing a Rapid Application Publish, forcing me to do a Full Publish :( 

The changes are limited to single code line changes, no table schema changes. Rad.json contains one file (codeunit) only. Any clue on how to find the cause?

Here's the info I extracted from the event viewer.

```
Server instance: CONFIG_06
Category: Development
ClientSessionId: 31970311-764b-4ae7-b0ed-d002d344206b
ClientActivityId: 8d7dd527-c835-4051-8f4f-87be4924a54f
ServerSessionUniqueId: abba5c3a-aede-44dd-92a9-d08cf1014553
ServerActivityId: 46266f13-77e9-4de4-9280-b700d10a40ff
EventTime: 02/04/2020 08:32:42
Message Fast publishing requires a full publishing for app 'Base Application Test'.

ProcessId: 21500
Tag: 000099U
ThreadId: 113
CounterInformation: 
CustomParameters: 00000000-0000-0000-0000-000000000000
```
```

Server instance: CONFIG_06
Category: Development
ClientSessionId: 31970311-764b-4ae7-b0ed-d002d344206b
ClientActivityId: 8d7dd527-c835-4051-8f4f-87be4924a54f
ServerSessionUniqueId: 0909b0a1-4a9d-4447-9d45-b9d1851b710a
ServerActivityId: 5bc19851-57f7-4daf-8381-33e95be2b897
EventTime: 02/04/2020 08:32:42
Message Failed request -- Method:POST; Url:http://10.0.2.45:7470/CONFIG_06/dev/apps?SchemaUpdateMode=forcesync&IsRad=true&DependencyPublishingOption=default; StatusCode:422; ReasonPhrase:Unprocessable Entity; Token:
ProcessId: 21500
Tag: 00000LY
ThreadId: 113
CounterInformation: 
CustomParameters: 00000000-0000-0000-0000-000000000000
```

![image](https://user-images.githubusercontent.com/25268332/73728464-ab3c9580-4733-11ea-9ee4-90694fc7b6b2.png)

All runs OnPrem, no docker.

**Comment by fvet** [comment]
Just found out the possible cause.

My original code in the test codeunit used to be something like

```
[Test]
    [HandlerFunctions('MessageHandler')]
    procedure MyTestFunction()
```

that got changed to

```
[Test]
    procedure MyTestFunction()
```

(or vice versa)

**Comment by atoader** [comment]
@fvet can you still reproduce this issue on the latest bits?

**Comment by fvet** [comment]
Unfortunately, I'm not running on the latest insider builds and don't have the time to reproduce. The only info I can provided was listed above (changing test function signatures failing to do a RAD). If fixed in the latest AL extension, the better.

**Comment by AndreyKorepanov** [comment]
It seems we could not reproduce it with the info provided, unfortunately. A code demonstrating the issue would be helpful. 
I am going to close issue now, please re-open the issue if it is still there or you get more details regarding the repro steps. Thank you.
