### ISSUE TITLE
Unable to use a controladdin accross multiple apps

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5641]
**Describe the bug**
I run into an issue where my app A contains a controladdin I want to reuse in app B.

So B depends on A, everything is working fine when compiling and publishing ;

but at runtime, the page (in app B) shows an error My Control NSA;PublicKeyToken=696788772ef3f7d5, The page contains a control add-in that is not permitted. Contact your system administrator.

Actually, if my controladdin is in a page that belongs to A it works.

Is not it a supported scenario? Am I missing something or is it a bug?

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an app A with a controladdin
2. Create an app B with a dependency on app A
3. In app B create a page with a usercontrol that uses the controladdin create in app A
4. Run the page

**Expected behavior**
I would expect the addin to work if it is declared in app A or app B (at least if there is no modifier that says its internal for instance).
**Screenshots**
![image](https://user-images.githubusercontent.com/44807684/73756735-5c5d2300-4768-11ea-9681-d2c3ace97460.png)

**5. Versions:**
 - AL Language: 4.0 
 - Business Central: Platform 15.0.39461.39737 + Application 15.2.39558.39825

**Comment by NicolaiEsbensen** [comment]
We have the same issue for our products.

**Comment by fvet** [comment]
Same over here

**Comment by nicolassaleron** [comment]
This bug is fixed on plateform 16.0.11233.11546 + application 16.0.11240.11602

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by mjmatthiesen** [comment]
Can anyone confirm if this was resolved? I am currently experiencing the same. Both in SaaS and a sandbox vm.

App A is installed from app source.
App B is a page extension to App A.
App B has a control add in to display on that page.

Get the "The page contains a control add-in that is not permitted. Contact your system administrator." message.
