### ISSUE TITLE
function CreateInvtMvntWithoutSource   CU7322

### ISSUE THREAD

**Issue by manoj1976** [microsoft/AL#5643]
Hi,

My webservice is calling the function CreateInvtMvntWithoutSource (CU 7322). Because of the 'CONFIRM' statement, the web service is giving me error message.

Original code
IF NOT CONFIRM(Text004,FALSE) THEN
  EXIT;

Request -- Can you please insert a GUIALLOWED statement in the base code?

IF GUIALLOWED THEN //@003  
IF NOT CONFIRM(Text004,FALSE) THEN
  EXIT;

Thanks
Manoj

**Comment by atoader** [comment]
Hi! Please take a minute to read the README for this repository. The issue you have raised should go through Collaborate or the other channels for raising application related bugs.

If you have questions not related to the developer tools please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
