### ISSUE TITLE
Translations for Profile objects

### ISSUE THREAD

**Issue by gregoral** [microsoft/AL#5644]
**Describe the bug**
1. We have added translation strings for profile objects, but they are still untranslated.
   - this is untranslated even with MS provided German translations

2. Also there is no way we know of to translate "Explore all" button ( see screenshot below ).
   - if I choose german language it is translated "Alle erkunden"
   - but this text "Alle erkunden" does not appear in either "Base Application.de-DE.xlf" or "System Application.de-DE.xlf"
   - apparently this string is translated somewhere else
   - so I see no way how we could translate this string if it is not in either of those files

**To Reproduce**
(A)
1. Install MS provided german translation extension on W1 image
2. login and change to german language
2. choose "Explore all business features for my role ..." / "Alle verfügbaren Geschäftsfunktionen ..."
3. choose "Explore all" / "Alle erkunden"
4. observe the untranslated texts
   ( it should be "Verkauf und Marketing" instead of "Sales And Marketing" )

**To Reproduce**
(B)
1. Create a new translation app in VSCode
2. put the code below in a translation xlf file
3. install the extension
4. login and change to Slovenian language
5. choose "Explore all business features for my role ..."
6. choose "Explore all"
7. observe the untranslated texts
   ( it should be "Sales And Marketing ( TRANSLATED )" instead of "Sales And Marketing" )

Example translation for profile SALES ( Slovenian language ):
```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-US" target-language="sl-SI" original="System Application">
    <body>
      <group id="body">
        <trans-unit id="Profile 1801123188 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve">
          <source>Sales And Marketing</source>
          <target>Sales And Marketing ( TRANSLATED )</target>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">Profile SALES - Property Caption</note>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
```

**Expected behavior**
We expect this caption to be translated, but it is not.
Using the provided translation it should read: "Sales And Marketing ( TRANSLATED )"

**Screenshots**
Choose "Explore all business features for my role ...":
![image](https://user-images.githubusercontent.com/42441688/73863498-7b2ee880-4840-11ea-823d-5d94da61cbfa.png)

Choose "Explore all":
![image](https://user-images.githubusercontent.com/42441688/73863519-84b85080-4840-11ea-932f-e9d15b51b4df.png)

Observe untranslated text for Slovenian language:
![image](https://user-images.githubusercontent.com/42441688/73863545-8c77f500-4840-11ea-931f-fad0ad2889e0.png)

Observe untranslated text for German language:
![image](https://user-images.githubusercontent.com/42441688/73865329-5daf4e00-4843-11ea-93d5-e8e3ab7dcb2f.png)

**5. Versions:**
 - AL Language: 
( probably irrelevant )
Microsoft (R) AL Compiler version 5.0.3.22698

 - Business Central:
15.2 ( 15.2.39040.0 )
16.0 ( 16.0.10855.0 )

**Comment by thpeder** [comment]
Hi @gregoral,
This has been implemented, so please give it a try in the release 2020 wave 2.
