### ISSUE TITLE
Personalization of Chart of Accounts as super user is not possible?!

### ISSUE THREAD

**Issue by malue1991** [microsoft/AL#5648]
Hey gyus,

in my BC 14 on premise I try to personalize the Chart of Accounts.

I am not able there to make the columns bigger or to change the place of the columns.

In the Customer List I can make these changes?

Do you know the reason for that?

Thank you ;)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
