### ISSUE TITLE
Signing HTTP request with "Encryption Management"

### ISSUE THREAD

**Issue by GijsFranssens** [microsoft/AL#5649]
**Describe the bug**
When I want to sign a HTTP request using codeunit 1266 "Encryption Management".SignData I receive the following error:
A call to System.Security.Cryptography.RSACryptoServiceProvider.FromXmlString failed with this message: Invalid syntax on line 1.

**To Reproduce**
Steps and to reproduce the behavior:
1. Use function SignData of codeunit "Encryption Management" with HashAlgoritmType::SHA512 or SHA256
2. CryptographyMgt.SignData(SigningString, PrivateKeyFile, HashAlgorithmType::SHA512, SignatureOutStream);
- SigningString is a pre-generated random string
- PrivateKeyFile is a InStream containing the private key file
- HashAlgorithm is SHA512 or SHA256
- SignatureOutstream is the outstream with the result.

``` AL Code to reproduce the issue ```
        TempBlob.CreateOutStream(SignatureOutStream);
        CryptographyMgt.SignData(SigningString, PrivateKeyFile, HashAlgorithmType::SHA512, SignatureOutStream);

**Expected behavior**
I expect SignatureOutstream to contain the result of the signing procedure.

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.206840

 - Business Central: 15.2 (Platform 15.0.39461.39737 + Application 15.2.39558.39796)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
