### ISSUE TITLE
The value of the DataItemLinkReference property must be the name of a parent data item.

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#565]
I get this error on most of our reports as the DataItemLinkReference is not always set to the parent data item, if we need to loop through records, We have to restructure quite some reports so I hope this is a bug in the compiler.

[REP70094014.zip](https://github.com/Microsoft/AL/files/1260395/REP70094014.zip)

**Comment by atoader** [comment]
I added this check when implementing support for reports in the compiler. I will take a look to see what can be done.

**Comment by atoader** [comment]
We've removed the error. The error was added because the documentation for the old system specified that the DataItemLinkReference should be a parent data item.
