### ISSUE TITLE
UnprocessableEntity. Reason: Object of type Table with ID xxx could not be found.

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5650]
**Describe the bug**
When publishing an extension that has dependent extension, we get the error:

`The request for path /CONFIG_xx/dev/apps?SchemaUpdateMode=forcesync&IsRad=true&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Object of type Table with ID xxx could not be found.
`

**To Reproduce**
I've created a workspace with 2 extensions:
- Extension A (named 'System')
- Extension B (named 'Base') with a dependency on A
- Both extension have been published
- I make a one code line (non table schema) change to extension A - **5 secs of development**
- I do a Rapid Publishing from within the workspace
- Extension A is being compiled (the modified object appears in the rad.json)
- Publishing of extension A fails with the Reason: Object of type Table with ID xxx could not be found., where the table refered is part of extension B
- Extension B is unpublished, forcing me to do a full publish of both - **takes upto 4 minutes** ...

**Expected behavior**
- Make sure extension A is successfully published without having to republish extension B all over again.

**5. Versions:**
 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/74222323-8a84ba80-4cb4-11ea-82fe-20132b3622f1.png)

**Comment by atoader** [comment]
Can you provide a sample to help us troubleshoot?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
