### ISSUE TITLE
How to pull NAV14.0.32307 Appl14.0.32335 CU0 ?

### ISSUE THREAD

**Issue by malue1991** [microsoft/AL#5655]
Hey guys,
can someone explain to me, how the syntax is, if I want to install a BC for example with version 14.0.32307?

I tried it in that way:
docker pull mcr.microsoft.com/businesscentral/onprem:14.0.32307-na

The error message I get then is:
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/onprem:14.0.32307-na not found: manifest unknown: manifest unknown

Thank you.

**Comment by tomasevicstefan** [comment]
Seems like build no. is not correct
https://support.microsoft.com/en-us/help/4501292/released-cumulative-updates-for-microsoft-dynamics-365-business

**Comment by malue1991** [comment]
Ok, how can you recognize, that I installed a different version?

I would like to pull a image for the follwing BC version:

![grafik](https://user-images.githubusercontent.com/59683024/74338528-abc3d480-4da2-11ea-88c3-21a2ff9757b2.png)

**Comment by tomasevicstefan** [comment]
Why don't you try some other cu, like
docker pull mcr.microsoft.com/businesscentral/onprem:14.3.34444.0-na

**Comment by malue1991** [comment]
The only goal I have is, that my running docker container has the exact version:

![grafik](https://user-images.githubusercontent.com/59683024/74341931-e92b6080-4da8-11ea-83e8-ca26561bea15.png)

If your suggestion will also result in getting the same version like above, I would install it ;)

**Comment by tomasevicstefan** [comment]
I'm still thinking that build no. is not correct. I can't find that build no. for BC14

**Comment by malue1991** [comment]
Ok, but hasn't there be one? I thought for ervery NAV/BC version, which you can install locally, there is also an image, you can use for docker?!

**Comment by mjmatthiesen** [comment]
> The only goal I have is, that my running docker container has the exact version:
> 
> ![grafik](https://user-images.githubusercontent.com/59683024/74341931-e92b6080-4da8-11ea-83e8-ca26561bea15.png)

What BC shows you in the Help and Support tab is not the same thing as version number. It clearly says 14.1 which means you need to use one of the 14.1 images. How you correlate the exact version is a different question I cannot answer.

The Application number is the version of the System Application extension.

Platform is well, the platform version.

Base Application is a separate number.

My gut says you are likely looking for "14.1.33107.33481" or thereabouts, but honestly, whatever the madness to the version numbering, I don't know.

If possible, look for a way to see which version of the system and base app are installed, then compare that to what is in the images (if possible).

**Comment by malue1991** [comment]
@mjmatthiesen thank you for yor answer ;)

I fiund out through the Microsoft Support, that the version I am looking for had an incorrect build version number and was therefore withdrawn after the release and replaced with a new one that bears the build number 32600.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
