### ISSUE TITLE
VS Code shows Value in Watch but not in Locals

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#5660]
**Describe the bug**
VS Code does not show a value for a Record Field in the Variables Window (Locals). When I add Watch the Value is shown.

**To Reproduce**
(See Screenshot)

**Expected behavior**
Both Locals and Watches should display the same information

**Screenshots**
![image](https://user-images.githubusercontent.com/48217797/74344478-f9ddd580-4dac-11ea-932b-dfb92b0e84cb.png)

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.229698
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Version: W1 15.2 (Platform 15.0.38951.0 + Application 14.0.29530.0)

**Comment by atoader** [comment]
@kalberes can you take a look?

**Comment by kalberes** [comment]
I have not seen this issue, but many things have changed with the hovering support that would be available with the 16.X releases.

**Comment by atoader** [comment]
@daansaveyn can you download the latest VSIX and give it a try?

**Comment by daansaveyn** [comment]
I've just installed the latest VSIX and keep you posted.

**Comment by atoader** [comment]
@daansaveyn is the issue resolved? Can I close this?
