### ISSUE TITLE
Rule AA0218 on API Pages

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5661]
**Title**
The rule AA0218 (warning AA0218: The Tooltip property for PageField "xxx" must be filled.) is raised on pages of type API.

**Description**
This new rule is provided by the AL Language 5.0.229698 and in my opinion, as an API page is not displayed in the UI, it should not have a Tooltip in its fields.

**Reason for the rule**
./.

**Bad code sample**
./.

**Good code sample**
./.

**Good and bad practices for fixing the rule**
API pages should be excluded from this rule.

**Remarks**
./.

**Comment by MarcHansenMicrosoft** [comment]
Should already be fixed

**Comment by MarcHansenMicrosoft** [comment]
Fixed
