### ISSUE TITLE
Permission Item Ledger Entry from Item Card

### ISSUE THREAD

**Issue by angelocitro** [microsoft/AL#5663]
**Describe the bug**
On open "Item Card" page from Web Client i receive the following message: 
"You do not have the following permissions on TableData Item Ledger Entry..."

I set reading and writing for the Item and I set indirect permissions for the Item Ledger Entry table

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Item with item ledger entry associated.

``` AL Code to reproduce the issue ```

**Expected behavior**
I expect the item card to be shown if I set indirect permissions on the Item Ledger Entry table

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central: 13.0.29358.0

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
