### ISSUE TITLE
AA0214 - The record XXX should be modified before saving to the database.

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5665]
Not sure about what warning AA0214 means. I've this part of code, resulting in error AA0214. What's wrong with this function?

```

 local procedure ProcessMessage(precMessage: Record "NVT b-Alert Read Message")
    var
        lrecObcIntegration: Record "NVT OBC Integration";
        ldatPrevMessage: DateTime;
    begin
        //     Processes a b-Alert message and imports it into the OBC integration table

        ldatPrevMessage := 0DT;

        lrecObcIntegration.Reset;
        lrecObcIntegration.SetCurrentkey(Trailer, "From DateTime");
        lrecObcIntegration.SetRange(Trailer, precMessage.Trailer);
        lrecObcIntegration.SetRange(Vehicle, '');
        if lrecObcIntegration.FindLast then begin
            if lrecObcIntegration."From DateTime" < precMessage."Time Stamp" then begin
                ldatPrevMessage := lrecObcIntegration."From DateTime";
                lrecObcIntegration.Validate("To DateTime", precMessage."Time Stamp");
                lrecObcIntegration.Modify;
            end
        end;
```

![image](https://user-images.githubusercontent.com/25268332/74454096-ac806780-4e83-11ea-89e3-5ee5f908d1b1.png)

**Comment by nicolassaleron** [comment]
I also have this warning in procedures without Insert/Modify/Delete/Rename: these procedures are just reading the database.
Quite strange...

**Comment by DBiernat** [comment]
Same for me, even in the newest  AL Language extension (5.0.232930) this warning occurs. Sometimes twice for the same variable.

**Comment by AskeHolst** [comment]
I have disabled AA0214 for now. I like the idea, but the current implementation is broken.
I checked about 100 AA0214 warnings a not a single one of them was anything to warn about.

**Comment by atoader** [comment]
@MarcHansenMicrosoft

**Comment by stefanoPrimo** [comment]
same here:
![image](https://user-images.githubusercontent.com/36199751/75149904-5de49000-5703-11ea-829c-91fc4f86e332.png)

The record Customer should be modified before saving to the database.AL(AA0214)
But I'm only reading it, not modifying. 
P.S. sorry the useless code

**Comment by Random-PasserBy** [comment]
Also merely using a function with a var parameter triggers a warning. Independent of its contents.

![image](https://user-images.githubusercontent.com/61599431/75577855-23605780-5a63-11ea-9c5f-169c796ec8c1.png)

If this can't be fixed it would be practical to be able to individually ignore the "var" check, not lose to the other (then fixed) functionality as well while ignoring AA0214.

**Comment by TheDenSter** [comment]
Not just reading, even when the local variable is modified, it still tells me to modify it
![image](https://user-images.githubusercontent.com/23434319/77973082-16c06080-72a8-11ea-893c-5290ce9d3aa6.png)

I don't get the message to begin with, what are you trying to catch here?

**Comment by rdebath** [comment]
Nice variant here: Four copies (On the two variable definitions) of:
```
The record Field should be modified before saving to the database. 
The record TempField should be modified before saving to the database. 
```

A Filtered list of the 'Field' table is copied to 'TempField' and then "processed".

**Comment by stijn9830** [comment]
You can add line in settings.json
"al.ruleSetPath": "_BC.ruleset.json"

An put this _BC.ruleset.json in root directory to ignore this warnings.
This will not help solving the bug of course, and the risk is you can forget them once bug is solved
![image](https://user-images.githubusercontent.com/56073675/78243575-4fe51480-74e4-11ea-955d-97a565c487be.png)

**Comment by JSebastianN** [comment]
The record Rec2 should be modified before saving to the database.AL(AA0214)

Here is another one.

My I suggest running these rules on the base code before releasing them.

            trigger OnValidate()
            var
                Rec2: Record "ITF Template Setup";
            begin
                Rec2.SetRange(Usage, Rec.Usage);
                if Rec2.FindFirst() then
                    Error(OnlyOneTxt, Rec2.Name);
            end;

**Comment by mjmatthiesen** [comment]
Rule should be junked.

**Comment by MarcHansenMicrosoft** [comment]
The fix in latest master branch version.

**Comment by AndreasGloeckner** [comment]
> The fix in latest master branch version.

What exactly did you change? Just deleted the rule?
Btw, is the master branch available for public? This repo's master branch was updated in february ;)

**Comment by NKarolak** [comment]
@AndreasGloeckner You cannot use the published repo code for testing, but you must pull the latest bc insider docker container (bcsandbox-master). Only this docker container contains the latest VSIX version.

**Comment by AndreasGloeckner** [comment]
> @AndreasGloeckner You cannot use the published repo code for testing, but you must pull the latest bc insider docker container (bcsandbox-master). Only this docker container contains the latest VSIX version.

Didn't want to use it for testing, just wanted to have a look in the source ;) But thanks for your feedback.

**Comment by MarcHansenMicrosoft** [comment]
We did not removed the rule.
The rules had issues detecting the proper use of a variable this has been improved.

**Comment by ElmarFV** [comment]
The reports of this issue being fixed have been greatly exaggerated. This is still an issue.

This code…
“    procedure ShowAssemblyRecords(OrderRequisition: Record "WC GAP07 Order Requisition")
    var
        AssemblyHeader: Record "Assembly Header";
        PageManagement: Codeunit "Page Management";
        RecordRef: RecordRef;
    begin
        with OrderRequisition do begin
            Clear(AssemblyHeader);
            AssemblyHeader.SetRange("WC GAP07 Ord. Req. No.", "No.");
            if AssemblyHeader.IsEmpty then exit;
            AssemblyHeader.FindFirst();
            RecordRef.GetTable(AssemblyHeader);
”
Resulted in this error message…
The record AssemblyHeader should be modified before saving to the database.
{
	"resource": "/c:/Repo/Bioworld/GAP07-Contract Print and Kit Types/src/codeunit/WCGAP07CreateAOs.Codeunit.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AA0214",
	"severity": 4,
	"message": "The record AssemblyHeader should be modified before saving to the database.",
	"source": "AL",
	"startLineNumber": 99,
	"startColumn": 9,
	"endLineNumber": 99,
	"endColumn": 23
}

Only when I comment out the AssemblyHeader.SetRange("WC GAP07 Ord. Req. No.", "No."); does the error go away.

**Comment by mjmatthiesen** [comment]
@ElmarFV I would recommend disabling that warning. It's not actually useful to begin with imo. Also, you are identifying your client with the resource folder.

> if AssemblyHeader.IsEmpty then exit;
> AssemblyHeader.FindFirst();

Personally I would simplify this to
`if not AssemblyHeader.FindFirst() then exit;`
Though I don't know what optimizations BC does under the hood for each statement, or what caching, so realistically, it may not matter.

**Comment by dtkb** [comment]
If you have a more specific bug that hasn't been fixed, open a new issue for it, or it won't be.

Agreed that `if not FindFirst()` makes more sense. Also, the `Clear()` is totally redundant, since being a new local variable that hasn't been used yet, it's already clear by definition. We only 'needed' that kind of paranoid clear/reset rain-dance when all variables were global as folk were too lazy to make them local, but there's no excuse for that now IMO.
