### ISSUE TITLE
Base64-wrapper broken, unable to load images to mediaset

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#5666]
We want to write a base64 string we receive as binary data into a MediaSet, but have not found a way to do this with the very limited toolset (dotnet wrapper codeunits) available to us.

It seems the Base64-code is broken. I use the Base64 converter to decode a base64-encoded string. When I encode the result, it differs from the original. Sample code below.

//Base64: codeunit "Base64 Convert";
Base64String := 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAIAAABPxRC5AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAAgSURBVBhXY/iPCkB8BhhA8EFSYECkPIQDBAgWCPz/DwAmK02zB8YDEgAAAABJRU5ErkJggg==';
Message(Base64String);

lTxtType := base64.FromBase64(Base64String);
Message(base64.ToBase64(lTxtType));

The latter message gives us:
77+9UE5HDQoaCgAAAA1JSERSAAAABQAAAAcIAgAAAE/vv70Q77+9AAAAAXNSR0IA77+977+9HO+/vQAAAARnQU1BAADvv73vv70L77+9YQUAAAAJcEhZcwAAEnQAABJ0Ae+/vWYfeAAAACBJREFUGFdj77+977+9CkB8BhhA77+9QVJgQO+/vTzvv70DBAgWCO+/ve+/vQ8AJitN77+9B++/vQMSAAAAAElFTkTvv71CYO+/vQ==

BC 15.2

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
