### ISSUE TITLE
Modify "Enabled" property dinamically

### ISSUE THREAD

**Issue by aetxebarria** [microsoft/AL#5668]
Hi everyone,
I need to set into purchase lines the enabled property to false in the "Qty. to receive" field, depending a a setup table that I have created.  In that setup table I've made a function that returns if it is enabled or not.
In the purchase line page, I've created a procedure to call to the function created into the setup table, also returning a boolean. But it's not allowed to call that function from the enabled property:

![imagen](https://user-images.githubusercontent.com/41778563/74532667-12c2c400-4f30-11ea-9309-cfef8c3602e9.png)

is there any way to do this? Or is planified to allow to set uf the visibilty with a function?

Thank you very much

**Comment by JulienDecottignies** [comment]
Hi,

I thing you need to fill a boolean variable in the OnOpenPage trigger. Then set Enabled property equals to that variable.

Also, I don't think is the right place to ask that kind of questions, you can post a message in one of the community forum like https://community.dynamics.com/business/f/dynamics-365-business-central-forum 

Hope it helps !

**Comment by aetxebarria** [comment]
Thank you, realy appreciated!
