### ISSUE TITLE
Summarys and Summary files

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#567]
It would be really cool if the summary syntax from c# gets added with xml export or alternative a json export. The scenario would be a use of DocFx and so with an automatic generation of documentation for NAV extension. When you introduce this, I'll plan to write a DocFx plugin or fork  for al syntax.

````cSharp
/// <summary>
/// This is a useful summary
/// </summary>
/// <param name="value">this is an useful value</param>
/// <returns>return the number 1 </returns>
local procedure Test(value : Integer) : Integer
{
 //Do something
}
````

**Comment by StanislawStempin** [comment]
This is on our radar and was already requested in #132
