### ISSUE TITLE
AA0225 warns about missing caption when ShowCaption = false

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#5670]
**Describe the bug**
On page fields with ShowCaption = false there AA0225 warning about missing caption if the caption is not set, even though a caption would not be needed.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create code like below

``` 
field(SomeField; MyInteger)
{
    ApplicationArea = All;
    ShowCaption = false;
}
```

**Expected behavior**
No AA0225 warning when ShowCaption = false

**Screenshots**
![image](https://user-images.githubusercontent.com/8398485/74566496-e3ce4180-4f73-11ea-9da4-14b04c9e3239.png)

**5. Versions:**
 - AL Language: 5.0.232930

**Comment by qutreson** [comment]
This issue has been fixed for AL extension with a version higher than 5.0.272418
