### ISSUE TITLE
Length of Description in Output Journal

### ISSUE THREAD

**Issue by hydhart** [microsoft/AL#5672]
**Describe the bug**
Description in Prod Order already 100 in length, but in Page Output Journal there's variable **ProdOrderDescription** still have 50 length.

![image](https://user-images.githubusercontent.com/41423177/74633193-acd67680-5193-11ea-8e43-0324596afac8.png)

**Version**
Base App = 15.2.39558.40612
System App = 15.2.39060.0

**Comment by hydhart** [comment]
![image](https://user-images.githubusercontent.com/41423177/74635374-6fc0b300-5198-11ea-9ece-188fa7042dbb.png)
this is the error screenshot

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
