### ISSUE TITLE
Temporary record parameter in interface procedure 

### ISSUE THREAD

**Issue by kmi84** [microsoft/AL#5675]
**Describe the bug**
When interface defines a procedure with a temporary record parameter then:
1) when implementing the interface in the same extension:
 - QuickAction will omit the "temporary" attribute when creating procedures
 - This is visible as a violation of rule AL0582 but can be fixed manually

2) when implementing the interface in different extension **in the same workspace**:
- QuickAction will omit the temporary attribute when creating procedures 
- Missing "temporary" attribute will cause AL0582 violation, but the app can be compiled and deployed
- Manually adding the temporary attribute will not get rid of the AL0582 but will cause a compilation error

3) when implementing the interface in different extension:
- QuickAction will omit the temporary attribute when creating procedures 
- Missing temporary attribute will not cause AL0582 violation; the app can be compiled and run

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new app
2. Define an interface with a procedure that has a temporary record parameter
3. Create a codeunit implementing the interface
4. Use Quick Action to implement procedures
5. Note AL0582 error.
6. Create the second app with dependency on the first one within the same workspace
7. Create a codeunit implementing the interface
8. Use Quick Action to implement procedures
9. Note AL0582 error.
10. Add the missing temporary attribute to the procedure
11. Note AL0582 error.

``` AL Code to reproduce the issue ```
- First extension
interface ITest
{
    procedure TestProcedure(var TempCustomer: Record Customer temporary);
}

- Second Extension
codeunit 50001 ExtensionTest implements ITest
{
    procedure TestProcedure(var TempCustomer: Record Customer);
    begin
    end;
}

**Expected behavior**
Behaviour should be consistent regardless of whether extensions are in the same workspace or not.
Quick Action "Implement Interface" should result in code that does not raise AL0582.
"Temporary" attribute defined in an interface should carry over to implementations in different extensions (??).

**Screenshots**

![image](https://user-images.githubusercontent.com/15689606/74666020-0e511200-51a1-11ea-8cd4-22b3dacb3cba.png)

![image](https://user-images.githubusercontent.com/15689606/74666271-7dc70180-51a1-11ea-92de-b43ccfd97831.png)

![image](https://user-images.githubusercontent.com/15689606/74666323-933c2b80-51a1-11ea-9cfa-cb3960634e12.png)

**5. Versions:**

 - AL Language: 5.0.228194
 - Business Central: 16.0.10961.0

**Comment by kalberes** [comment]
Thank you for the detailed bug. We will have a look at it.

**Comment by jwikman** [comment]
@kalberes, @PooyaKharamesh any progress on this?
This is getting quite annoying... Let us know if you need any more info regarding this issue.

**Comment by qutreson** [comment]
@jwikman, this issue should have been fixed in our latest developer previews. Can you give it a try?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
