### ISSUE TITLE
AL Debug without publishing on OnPrem Multi Tenant

### ISSUE THREAD

**Issue by jiwanovski87** [microsoft/AL#5676]
Hi everybody,

we still do have an own BC Multi Tenant "On Premise" since we are working to become our solution as AL for AppSource. If we want to use the VS Code Debugger we do face a problem with that. 

For the multi tenant we have enables to accept host names for tenants and setup Alternate Tenant Ids for each tenant. So we do have urls like:
- CustomerA.solutionDomain.com
- CustomerB.solutionDomain.com

When we want to Debug with VS Code and feature "Debug without publishing" the debugger starts every time with taking the Base URL from instance directly. I would assume that this feature should take the "Alternate Tenant ID" from Tenant Setup to create the correct url. Otherwise we do have some problems with debugging each tenant, without changing the Base URL each time....

Is there another option?

Thanks!

**Comment by kalberes** [comment]
I am not sure I understand correctly the issue? 
Do you want to have a launch setting for the alternate tenant id in the debug configuration settings?
We do not support that, and since this is targeting an onprem scenario it will not be at the front of the backlog.
What versions are you using?

**Comment by jiwanovski87** [comment]
@kalberes there is a short missunderstanding. 
I don not want to have a new setting for this. 

When I run the feature "Debug without publishing" the web clients open with the "Web Client Base URL" from Service Instance. For a normal Single Tenant deployment this is fine. When you do have a multi tenant deployment this might not be the best situation. 

On a multi tenant deployment you already need to setup to accept host names (as written above) for using PowerBI, Excel Add In and other stuff. Then you are setting up a "Alternate Tenant ID" in the tenant settings.

This will be different per tenant and this value should, combined with the information "Web Client Base URL" setting should give a new URL to access the specific tenant. 

Maybe as example:
- Web Client Base URL = CustomerA.solutionDomain.com/BC140/WebClient/

Tenant Setting A
Alternate Tenant ID = CustomerA.solutionDomain.com

Tenant Setting B
Alternate Tenant ID = CustomerB.solutionDomain.com

Current Situation:
When I hit the feature "Debug without publishing" the system is callind allways: CustomerA.solutionDomain.com/BC140/WebClient/ (Web Client Base URL). For Tenant A this is okay because it machtes with Alternate Tenant ID. But if I want to debug Tenant B I have to change the Base URL first. Otherwise I am not able to connect to the tenant and start debugging.

That's why I thought you have to consider the Alternate Tenant ID when opening web client by feature "Debug without publshing". I also thing this problem could occur on the hosted by Microsoft Version... If not it would be interessting to know your setup ;)

Is this a bit clearer?

Thanks
Jesko

**Comment by kalberes** [comment]
I understand it but can't you create two launch configurations one for tenantA and one for tenantB and choose accordingly. From the fall version it is supported to choose any available configuration when debugging.

**Comment by jiwanovski87** [comment]
@kalberes Well I do have to create two launch.json files for each tenant (in that description). 
There I have only the option "tenant" available. When I put this to Tenant = CustomerA or Tenant = CustomerB this is not changing the call of web client. This is just only taking the value of Web Client Base URL.

What do you mean with fall version supports any available configuration? What do you mean with any configuration?

**Comment by AndreyKorepanov** [comment]
Hi @jiwanovski87 is it still actual? It seems your suggestion is a feature request, you might want to open a [BC idea ](https://aka.ms/BusinessCentralideas) if one is not already present. That will help us get an understanding of how much the community needs this relative to other features. Thank you.
