### ISSUE TITLE
Control Addin does not render in online sandbox

### ISSUE THREAD

**Issue by brooksca** [microsoft/AL#5677]
**Describe the bug**
When creating an HTML/javascript controladdin object, the add-in renders correctly when deploying to a virtual server with an onprem image in a docker environment, however, when deploying the same controladdin to an online sandbox environment, the page does not render. The AL page loads, however, none of the customer HTML/CSS/JavaScript render. Essentially an empty page is displayed.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a simple add-in using the AL: Go command in VS code.
2. Add a controladdin as described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object
3. Add a page to host the object
4. Deploy the project to an online sandbox
5. Open the page

Repro repo here: https://github.com/brooksca/ALAddInRepro

**Expected behavior**
The controladdin is expected to render reliably in both an online and docker container environment.

**Screenshots**

**5. Versions:**
 - AL Language: 4.0.206840
 - Business Central: Online Sandbox

**Comment by pmohanakrishna** [comment]
Make sure that "ApplicationArea" property is set for control adding part in page. :)

**Comment by brooksca** [comment]
Adding the ApplicationArea property to the page fixed the issue. Thanks for your help, Mohana.
