### ISSUE TITLE
Table "Cue Setup" does not support using suffixes on new Cue-Tables

### ISSUE THREAD

**Issue by MatthiasHierteis** [microsoft/AL#5678]
**Describe the bug**
Microsoft requires ISV solutions to use prefixes or suffixes (or both) for object names of the ISV solution. 
If the ISV solution contains a new cue-table for role centre tiles, it must get added to table "Cue Setup". This allows to configure the KPI-colours and limits of the new tiles.

If the new cue table uses a suffix, it cannot be entered into field "Table ID" of table "Cue Setup", because an error message is shown. The reason is, that the TableRelation-Property of the field "Table ID" filters on table object names ending with "Cue".

Microsoft leaves the decision whether using prefix or suffix (or both) to the ISV. That means that Business Central must support all 3 possibilities. Logically, if suffixes are not supported in this case, it must  be rated as a defect/bug.

The solution is easy: Just change the filter expression in the TableRelation-property to "*Cue*" by adding a "*" after "*Cue".

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new table "MyNewCueTSO" with "TSO" as suffix.

table 60000 "MyNewCueTSO"
{
    Caption = 'MyNewCueTSO';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
        }
    }
    keys
    {
        key(PK; "Primary Key")
        {
            Clustered = true;
        }
    }
}

2. Publish this new table to standard BC15
3. Log on to BC15 client
4. Open page "Cue Setup"
5. Click on "New" to create a new record
6. Make a look-up on field "Table ID"
7. Error 1: The new table is not shown in the lookup list
8. Close the lookup
9. Try to enter 60000 directly into field "Table ID". 
10. Error 2: An error is prompted to the user (see screenshot section).

**Expected behavior**
It must be possible to enter a table ID of a "Cue"-table having a suffix in the table name like "MyNewCueTSO". Also, the lookup must show such tables to allow the selection.

**Screenshots**
![image](https://user-images.githubusercontent.com/61226453/74816256-0b6a3480-52fb-11ea-89e9-20b849d88b58.png)

![image](https://user-images.githubusercontent.com/61226453/74817687-9b10e280-52fd-11ea-9bb8-ab82725afee7.png)

**5. Versions:**
 - Business Central: BC15.02

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by elweilando** [comment]
I filed the bug in collaborate. Resolved reason was "Won't Fix".
>The Cue tables are looked up from Suffix. please use Prefix for these tables.

**Comment by dtkb** [comment]
What a rubbish non-answer! I hope someone else has or will provide an actual response.

**Comment by JesperSchulz** [comment]
I'm going to look into this one. That behavior is off. Will verify if that simple fix indeed will cut it and if it does, we'll get that fixed for the next major.

**Comment by db-bc** [comment]
Awesome, thanks @JesperSchulz :-)

**Comment by stkillen** [comment]
This issue has already been fixed since 15.3. 

I verified that the table shows up in the lookup and can be selected as seen in the below image. 

![image](https://user-images.githubusercontent.com/65776111/124594314-f3e40b00-de5f-11eb-9ee7-68eee7a6162c.png)

**Comment by db-bc** [comment]
Hmm, weird that Approval Entry shows up, wonder what else changed to enable that.
