### ISSUE TITLE
Permission sets cannot be viewed for OnPrem 

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/AL#5679]
**Describe the bug**
while trying to open Permissions from Permission sets Page, unable to view permissions.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Permission Sets Page 
2. Select one of the below Permission Set and click Permissions action. 
      a.  **PAYPALSTANDARD**
      b.  **PAYPALSTANDARDREAD**
      c.   **INTELLIGENTCLOUDBASE**
      d.   **INTELLIGENTCLOUDBC**

**Expected behavior**
Should be able to see permissions.
it seems like if the permission set has any new object that is created in that app then we are getting error

**Screenshots**
Below are details of error 
![image](https://user-images.githubusercontent.com/28556102/74828263-d5e23d00-5334-11ea-967c-e107bbb10d08.png)

![image](https://user-images.githubusercontent.com/28556102/74828358-fca07380-5334-11ea-881f-52840e1c4d17.png)

![image](https://user-images.githubusercontent.com/28556102/74828467-2bb6e500-5335-11ea-8f1d-7960fab00c05.png)

![image](https://user-images.githubusercontent.com/28556102/74828549-50ab5800-5335-11ea-9e91-4e76f5648229.png)

![image](https://user-images.githubusercontent.com/28556102/74828600-691b7280-5335-11ea-99cf-14c3f95ae37e.png)

**5. Versions:**

 - Business Central: 15.2  OnPrem

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
