### ISSUE TITLE
Rename symbol function

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#568]
It will be better if when I click on **Rename Symbol** option, then the system will copy full field name to an input field. Now It copies only first word.
Example
![image](https://user-images.githubusercontent.com/29101017/29879386-9adeb0de-8dad-11e7-9deb-5d5107ee0f34.png)

![image](https://user-images.githubusercontent.com/29101017/29879412-a5199fc8-8dad-11e7-96ff-d5ec29f066ff.png)

![image](https://user-images.githubusercontent.com/29101017/29879420-ae3a68ee-8dad-11e7-93aa-48b8deb808bc.png)

**Comment by StanislawStempin** [comment]
See #498
