### ISSUE TITLE
Worksheet page with listpart subform overlap

### ISSUE THREAD

**Issue by BernBoit** [microsoft/AL#5680]
**Describe the bug**
When resizing a worksheet page that contains a subform, the subform overlaps the main section. Standard page like the Cash Flow Worksheet have this type of behavior.

**To Reproduce**
1- launch the Cash Flow Worksheet page
2 - Enter some lines in the upper grid
3- Resize down the main browser window

**Expected behavior**
Page should not overlap

**Screenshots**
Full page:
![image](https://user-images.githubusercontent.com/38114379/74879815-f19b1280-5337-11ea-806b-398bd01c23f1.png)

Resized down:
![image](https://user-images.githubusercontent.com/38114379/74879842-ffe92e80-5337-11ea-99c5-efbc11763861.png)

**5. Versions:**
 - AL Language:  
4.0229715
 - Business Central:
Saas Version: CA Business Central 15.2 (Platform 15.0.39461.40778 + Application 15.2.39060.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
