### ISSUE TITLE
Purchase order subform page tax total shows inaccurate values

### ISSUE THREAD

**Issue by BernBoit** [microsoft/AL#5681]
**Describe the bug**
On the purchase order subform page , the Total tax and Total including Tax values displayed are not accurate when using 2 different tax areas code on the lines. The general section of the statistics page however shows the correct amounts, and after posting the correct taxes are posted.

**To Reproduce**
On a CA tenant:
1. Create a purchase oder
2. Enter 1 line and assign the tax area code
3. Enter a second line and chose a different tax areacode
4. Release the document
5. Comapre the Tax amount to the one in the statistics.

**Expected behavior**
Tax amount should display correctly.

**Screenshots**
Purchase order page:
![image](https://user-images.githubusercontent.com/38114379/74880482-52771a80-5339-11ea-9279-00d54bdc8761.png)

Statistics pages:
![image](https://user-images.githubusercontent.com/38114379/74880563-78042400-5339-11ea-9538-d56498b8a1a5.png)

**5. Versions:**

 - AL Language: 
4.0.229715
 - Business Central:
Saas Version: CA Business Central 15.2 (Platform 15.0.39461.40778 + Application 15.2.39060.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
