### ISSUE TITLE
Debugger error - Internal Server Error on SaaS Sandbox

### ISSUE THREAD

**Issue by Nyryus** [microsoft/AL#5684]
**Describe the bug**
Sometimes when I use the debugger on a SaaS Sandbox environment and I debug the extension, the debugger stops working and leaves a session hanging on the Environment, blocking the developer for almost 30 minutes, cause the session is still alive, then it goes in timeout.
The error states "Internal Server error", but the SaaS tenant keeps responding on another tab.

**To Reproduce**
Steps and to reproduce the behavior:
1. Run the debugger
2. Run some code that has a breakpoint
3. Try to go to the next step
4. Be unlucky :)

This happened to me, some times while debugging code in a
``` if Codeunit.RUN then ```

**Expected behavior**
Keep debugging without problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/40896051/75020388-f6280e00-5492-11ea-8d07-fc3d45dfd586.png)

**5. Versions:**
 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.234544
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Version: IT Business Central 15.2 (Platform 15.0.39461.40778 + Application 15.2.39060.0)

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
