### ISSUE TITLE
BC 365 - Customer Ledger Entry Description "Rækkefølge" is wrong in Danish language

### ISSUE THREAD

**Issue by rasmumor** [microsoft/AL#5688]
**Describe the bug**
BC 365 - Customer Ledger Entry Description "Rækkefølge" is wrong in Danish language.

The description should have been "Faktura"

**To Reproduce**
This is happening when the user is set up to Danish Language.
1. Create a Sales Order for e.g. customer 10000
2. Enter some lines
3. Post the invoice
4. Go to the customer and view the Customer Ledger Entry for the Invoice

[BC 365 - Customer decription is wrong in Danish language.docx](https://github.com/microsoft/AL/files/4249450/BC.365.-.Customer.decription.is.wrong.in.Danish.language.docx)

``` AL Code to reproduce the issue ```

**Expected behavior**
The description should have been "Faktura"

**Screenshots**

**5. Versions:**
 - Business Central:
Version: DK BC 16.0 (16.0.11280.0 + 16.0.11209.0)

**Comment by rasmumor** [comment]
Hi, it seems that the same happens for Vendor Ledger entries when posting a Purchase Order.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
