### ISSUE TITLE
We need below procedures available for extension 2.0

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/AL#569]
The procedures are required for our extension:
Codeunit "Sales-Post"
[AL] The type or method 'GetSalesLines' cannot be used for 'Extension' development.
[AL] The type or method 'SumSalesLinesTemp' cannot be used for 'Extension' development.

Codeunit "Sales Price Calc. Mgt."
[AL] The type or method 'FindSalesLinePrice' cannot be used for 'Extension' development.

Codeunit "Sales-Calc. Discount"
[AL] The type or method 'CalculateWithSalesHeader' cannot be used for 'Extension' development.

Codeunit "Sales-Post Prepayments"
[AL] The type or method 'SumPrepmt' cannot be used for 'Extension' development.

Record "Cust. Invoice Disc."
[AL] The type or method 'GetRec' cannot be used for 'Extension' development.

Codeunit "Copy Document Mgt."
[AL] The type or method 'CopySalesInvLinesToDoc' cannot be used for 'Extension' development.

Record "Business Chart Buffer"
[AL] The type or method 'GetXValueAsDate' cannot be used for 'Extension' development.

Record "Business Chart Buffer"
[AL] The type or method 'AddMeasure' cannot be used for 'Extension' development.
[AL] The type or method 'AddPeriods' cannot be used for 'Extension' development.
[AL] The type or method 'SetValueByIndex' cannot be used for 'Extension' development.

HttpWebRequestMgtGlobal : Codeunit "Http Web Request Mgt."
[AL] The type or method 'Initialize' cannot be used for 'Extension' development.
[AL] The type or method 'SetMethod' cannot be used for 'Extension' development.
[AL] The type or method 'AddHeader' cannot be used for 'Extension' development.

**Comment by dkatson** [comment]
I will add 
Record "Item Template"
[AL] The type or method 'NewItemFromTemplate' cannot be used for 'Extension' development.

**Comment by StanislawStempin** [comment]
We will address the request.
HttpWebRequestMgtGlobal will not be made available, please use the new AL types for Http* handling:
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-restapi-overview
