### ISSUE TITLE
Smartlists

### ISSUE THREAD

**Issue by AlvaroMig** [microsoft/AL#5690]
Where are smartlists defined? Can I add a new smart list?
Now, in Items, there are some Smart lists. Can I add a new one or modify an exisiting one?

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
