### ISSUE TITLE
Business Central Performance Issue

### ISSUE THREAD

**Issue by vojislavni** [microsoft/AL#5691]
Hi,

We are facing the issue regarding extremely slow list scrolling, movements between cards and cards opening. The biggest problem is the customer table. This table has customizations - 10 extensions are published on this table. There are around 30 new fields added to this table, divided in 10 extensions in order to group logic parts of the process. Everything seemed to be fine until the client's data was imported. There are over 40000 records in the customer table. After data import managing customer data become extremely slow.

We did some testing with this number of records and 4th extension that is published on customer table is causing the issue. When 3 extensions are published (regardless of the number of the fields in each - testing was done with one field in each extension), everything is working fine. Fourth is blocking the process.

Does anyone have an idea what can be the reason for this and how can this be overcome?

BC version is 13.7.

**Comment by fvet** [comment]
https://www.linkedin.com/pulse/avoiding-table-extension-hell-james-crowter/

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
