### ISSUE TITLE
Team member in BC Cloud Saas not behaving as Limited user

### ISSUE THREAD

**Issue by naveksa** [microsoft/AL#5699]
**Describe the bug**

Naveksa is an ISV who has a Shopfloor solution. Both CfMD and Appsource approved. 

As part of this application, we have a so-called client which run against the NAV/BC database using a limited user on the dynamics NAV version, and a team member user on the BC On-premise versions.

Everything works fine on the on premise version. But it does not work in the BC Cloud SaaS version (BC 15.2).

This means we are stuck with more file access denials. F.ex. do we get an update denial on trying to update the field "routing status" in table 5409 Production Order routing line

Where is the difference between a limited user on-premise and the team member user in the cloud SaaS version, if any?

It is our firm belief that this is not in accordance with the rules for the Team member user?

This problem is a big one for our customers who have been forced to run a temporary full user solution.

Regards 
Bent Korsgaard

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by naveksa** [comment]
Apparently a Team member license does not allow permission rights to any tables in manufacturing.
It looks like the restriction is on the objects belonging to the Premium Edition.
Can anyone confirm?
![permissionerror](https://user-images.githubusercontent.com/40754213/75783142-5a36b600-5d60-11ea-9a8f-cfb341342152.png)

**Comment by atoader** [comment]
Hi! Could you please open a support case for this? This repository only handles issues related to the compiler and AL development tools.
