### ISSUE TITLE
After installing an extension...

### ISSUE THREAD

**Issue by markomolan** [Microsoft/AL#57]
Can you see new or changed objects in the designer? I cant find new objects. Can you debug them in old debuger?

Thanks.

**Comment by StanislawStempin** [comment]
You cannot see the new objects in the object designer and there are no plans to support this scenario.. Debugging will be available directly from VS Code but we don't have an ETA yet.

**Comment by markomolan** [comment]
I have found a way how to debug in old environment....its tricky
[http://marko.decmanmolan.com/wp/2017/01/11/how-to-debugg/](url)
