### ISSUE TITLE
AW0008 - The repeater 'RepeaterControl' is not supported by the Web client on 'ListPlus' pages.

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5703]
**Describe the bug**
I'm getting the AW0008 warning on lots of ListPlus pages. 

We're forced to use ListPlus pages for complex overviews, since they have different behavior as normal list / worksheet pages. ListPlus comes closest to what we really need. (suggested by MS support in earlier tickets)

Now, when enabling CodeCop, AW0008 shows up and states 'Repeater' are no longer supported on ListPlus pages?

On https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview, it is stated 

> Similar to a **List** page, a List Plus page displays content from a table in a **list format**. The difference is that the List Plus page type can contain two lists in one page, and can be used as a two-dimensional matrix.

This seems contradictionay? How to build a list page without using a repeater control?
I agree the rule applies for Card / Document pages, but why for ListPlus pages (Maybe related, but I've also wondered with the 'Contact Card' is the base app is really a ListPlus page instead?)

_Also see #4822 which has been closed, without answering the suggestion of @RobertdeRoos._

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/75787409-f95eac00-5d66-11ea-8fa4-a6127a8602af.png)

**Comment by MarcHansenMicrosoft** [comment]
Hi @fvet thanks for reporting the issue.

I have send it on internally and they will get back to you.

**Comment by stefanoPrimo** [comment]
Hi, 
same problem here! Any news?

**Comment by quadfin** [comment]
Same issue.
I would add that there seem to be no issues using a repeater on a ListPage.
It renders fine and I have found no functional issues.
I'd guess this is a legacy rule resulting in a warning that no longer applies.
Is it OK to disable the warning and use a repeater on a ListPage ?
Or will this warning result in AppSource certification failure?

**Comment by fvet** [comment]
Hi @MarcHansenMicrosoft , haven't heard from the team yet. Any status update?

**Comment by mhenricus** [comment]
Same 'issue' here. The Warning is given, but there seems no problem with rendering for PageType = ListPlus, Document, or Card.
