### ISSUE TITLE
AL1024: A package with publisher, name, and a version compatible with '1.0.0.0' could not be loaded. Symbols for the requested app YYY by XXX 1.0.0.0 could not be found in the database

### ISSUE THREAD

**Issue by sirhc101** [microsoft/AL#5704]
**Describe the bug**
I have on Library app (App A) which is an dependency of another app (App B). Both Apps are in Azure Pipelines for CI and once a week a build and test against current version, next minor & next major version.

App A is working fine in all three stages (current, next minor, next major).

App B is has been successful until 31th January 2020, but since than the `Publish` step is failing with the above mentioned error message, telling me, that App A is not there. 
`AL1024: A package with publisher, name, and a version compatible with '1.0.0.0' could not be loaded. Symbols for the requested app App A by Me 1.0.0.0 could not be found in the database`
Of course I need to publish the dependencies first and I'm taking care of this step before I get to the Publish step.
The funny things about this are:

1. If I look into the container App A is installed (current version is 15.1.x.y).
2. The previously run Step `Compile` (alc.exe) is working fine and downloading the App A dependency.
```
Compiling app
Using Symbols Folder: C:\agent\_work\6\s\.alPackages
Downloading symbols: Microsoft_System_16.0.11425.0.app
Url : http://172.29.201.212:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=15.0.0.0&tenant=default
Downloading symbols: Microsoft_Base Application_16.1.11449.0.app
Url : http://172.29.201.212:7049/BC/dev/packages?publisher=Microsoft&appName=Base Application&versionText=15.0.0.0&tenant=default
Downloading symbols: Microsoft_System Application_16.1.11449.0.app
Url : http://172.29.201.212:7049/BC/dev/packages?publisher=Microsoft&appName=System Application&versionText=15.0.0.0&tenant=default
Downloading symbols: XYZ_App A_15.1.x.y.app
Url : http://172.29.201.212:7049/BC/dev/packages?publisher=XYZ&appName=App A&versionText=1.0.0.0&tenant=default
Adding dependency to Application from Microsoft
Downloading symbols: Microsoft_Application_16.1.11449.0.app
Url : http://172.29.201.212:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=16.1.0.0&tenant=default
Compiling...
alc.exe /project:C:\Agent\_work\6\s\app /packagecachepath:C:\Agent\_work\6\s\.alPackages /out:C:\Agent\_work\6\a\app\XYZ_App B_15.1.x.x.app /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\160\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\160\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\windows\assembly","C:\Test Assemblies\Mock Assemblies"
Microsoft (R) AL Compiler version 5.0.3.39641
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'App B' containing '15' files at '18:21:15.822'.

C:\Agent\_work\6\s\app\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'C:\Agent\_work\6\s\app\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.

Compilation ended at '18:21:22.277'.

```
3. If I try to all the steps from VS Code it works.
4. `Publish` step does only fail against "Next Major" (BC 16)

**To Reproduce**
1. Create two apps, App A is depending on App B
2. Create two DevOps build Pipelines with next major as image source

**Versions:**
 - Sandbox Image: bcinsider.azurecr.io/bcsandbox-master:de-ltsc2019
 - Platform: 16.0.11425.0

**Comment by atoader** [comment]
Hi! Could you provide a small sample and the set of command needed to repro this?

**Comment by sirhc101** [comment]
Basically the pipeline is as described by [freddy](https://freddysblog.com/2018/11/12/developing-business-central-extensions-part-1/). Then it's enough to create two "Hello World" apps with one app has a dependency to the other one.

It's looks like if the App Version is something with 1.x.x.x it works. If the App Version is larger (e.g. 15.x.x.x) and the dependency is asking for 1.x.x.x it crashes.

**Comment by sirhc101** [comment]
It seams to be a problem with the navcontainerhelper. I will investigate a bit more and create a new issue at navcontainerhelper repo.

**Comment by christophbartl** [comment]
Dear @sirhc101 
have you found a solution for this problem?

**Comment by sirhc101** [comment]
Hello @christophbartel, it has been fixed by a update of navcontainerhelper.
Do you got exactly the same error message?

**Comment by christophbartl** [comment]
Thank you for your reply @sirhc101 
I get a quite similar error and do not find the cause of it. 
I have two extensions with 1 dependency from extension 2 to extension 1. 
when i try to publish extension 2 i get the following error: 


Publish-NAVApp -ServerInstance $ServerInstance -Path "C:\xxx –SkipVerification
Publish-NAVApp : Extension compilation failed
error AL1024: A package with publisher xxx', name 'xxx', and a version compatible with '16.4.0.0' could not be loaded. Symbols for the requested app xxx by xxx 16.4.0.0 could 
not be found in the database
At line:1 char:1
+ Publish-NAVApp -ServerInstance $ServerInstance -Path "C:\xxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$XXXnav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp


when i

**Comment by fartwhif** [comment]
Why is this closed?  I'm getting the same problem while using VSCode

**Comment by JuliusGeri** [comment]
I have a same error, do you have any solution ?

**Comment by ubavic** [comment]
I had the same problem with my local container. App `A` depends on  the app `B`; trying to publish the `A` would give me `error AL1024` even if the `B` was published. In my case, problem was that I tried to publish `A` as Global, while `B` was published from VS Code. Publishing `B` as global solved the issue.

```powershell
Publish-BcContainerApp `
    -containerName "bc1" `
    -appFile ".\B.app" `
    -skipVerification `
    -sync `
    -upgrade `
    -scope Global `
    -install
```
