### ISSUE TITLE
Page cannot be used for 'Extension' development when used in RunObject

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL#5705]
When I add `RunObject = Page "Extension Management";` as section trigger on a Role Center I get the error:
`The type or method 'Extension Management' cannot be used for 'Extension' development.`

In my opinion this is a bug as i dont want to "use" the page. I just want to display it.

**Comment by atoader** [comment]
Hi! Can you please provide the information requested by the issue template?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
