### ISSUE TITLE
calculate mathematical expressions with conditions

### ISSUE THREAD

**Issue by pro4dynamix** [microsoft/AL#5706]
Hello,
we would like to have a solution to calculate mathematical expressions with variabes and conditions.

In the past we have used ncalc to do the job:
https://archive.codeplex.com/?p=ncalc

In AL we are currently using DataColumn.Expression Property from DataTable which is part of the .net framework:
https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn.expression?view=netframework-4.8

Both solutions provide conditions.
Examples:
ncalc: „a != 0 ?  b / a : 0“
DataColumn Expr.: „iif( a <> 0, b / a, 0)“

But both solutions need .net, which is no allowed in saas.

We use these mathematical expressions very often in our solution, so it is not possible to do this calculation in azure functions due to performace issues - too much external web calls.

Otherwise it is not trivial to implement such a expression engine in AL.

So we would like to have such a mathematical expression engine in the system app. Maybe a module around the datacolum.expression to be useable without .net.

Thx, Jürgen

**Comment by nicolassaleron** [comment]
Hi,
You might be able to do what you want using XML transformations.

```
    procedure MyEvaluation()
    var
        XmlDomManagement: Codeunit "XML DOM Management";
        Ret: Text;
    begin
        Ret := XmlDomManagement.TransformXMLText(
            '<root><a>10</a><b>12</b></root>',
            '<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">' +
            '<xsl:template match="/">' +
            '    <xsl:variable name="a" select="/root/a" />' +
            '    <xsl:variable name="b" select="/root/b" />' +
            '    <result><xsl:value-of select="$a + $b"/></result>' +
            '</xsl:template></xsl:stylesheet>');
        Message('%1', Ret);
    end;
```

This piece of code opens a message box with the following content:

```
<?xml version="1.0" encoding="utf-8"?><result>22</result>
```

**Comment by hougaard** [comment]
You can also create a Javascript single dot control add-in and use the javascript eval functionality :) 

(Not very fast and require UI)

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
