### ISSUE TITLE
Using 'SystemId' in Query column is not supported

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5707]
**Describe the bug**
Using the 'SystemId' field on a query column is allowed by the AL compiler.

![image](https://user-images.githubusercontent.com/25268332/75979408-bb859300-5ee0-11ea-81dc-693301e52acc.png)

However, after publishing and calling the query via the webclient, i get an error 'Object query xxx is not found'. Eventviewer shows following error

`The metadata object FieldNumber 2000000000 was not found.`

pointing me in the direction that a 'systemid' field cannot be used on qeury objects?

**Expected behavior**
Provide support for the 'systemid' field in the query object

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/75979575-14edc200-5ee1-11ea-8058-c3f109a7dc81.png)

 - Business Central:

![image](https://user-images.githubusercontent.com/25268332/75979602-220ab100-5ee1-11ea-9461-7d308240c90e.png)

**Comment by NKarolak** [comment]
I think this is normal behaviour for every GUID field. Have you tried it already with `format(SystemId)`?

**Comment by atoader** [comment]
This issue has been fixed in the Wave 1 release. Could you please test it out and confirm?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity.  We believe it has been fixed with the Wave 1 release. Please open a new issue if you believe this has not been resolved and reference the current issue.
