### ISSUE TITLE
Does not allow on-prem compilers of different versions side-by-side

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/AL#5709]
I have many on-prem customers, each running their own version. 

There is functionality on the vs code extension to have it only enabled for a work space.

So ideally, when I open a project, it would enable the correct version of the AL compiler.

This is currently not possible: Whenever I install the AL compiler with a new .vsix, it is replacing the existing one, not allowing two compilers to co-exist and be enabled for their own workspaces.

Please add the possibility to have different versions of the AL compiler installed and preserve their projects/workspaces

**Comment by atoader** [comment]
Thanks @hougaard ! 
Here is a help article on the topic: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions . Please feel free to leave feedback on the article!

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
