### ISSUE TITLE
Integer to Option conversion does not work properly when there are blank option values

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#571]
When assigning an Integer to an Option field, the conversion does not work properly when there are blank option values. We receive the following compilation error:

severity: 'Error'
message: 'Constant value '11' is outside of the valid ordinal range for this option type'
at: '34364,42'
source: 'AL'

Example:
MyRecord.Industry := 11;

field definition:
    field(2;Industry;Option)
    {
      CaptionML=ENU='Industry',
                FRC='Secteur',
                ENC='Industry';
      OptionCaptionML=ENU='" ",,,"Direct Marketing (MOTO)","Food/Restaurant","Grocery Store/Supermarket",,,,,Retail,"E-Commerce"';
      OptionMembers=" ",,,"Direct Marketing (MOTO)","Food/Restaurant","Grocery Store/Supermarket",,,,,Retail,"E-Commerce";
    }

Option 11 should be E-Comerce

**Comment by Gallimathias** [comment]
@jcooper01 Try taking the 5 to see if that turns into e-comerce. If so, MS uses the option to remove empty entries from the array on string.Split().

Then this -> ,, becomes an empty entry in a string[] that is removed.

**Comment by jcooper01** [comment]
I think you're probably right, but we have literally thousands of lines of code that refer to options as their integer values. It should behave as in C/AL.

**Comment by Gallimathias** [comment]
I've never been very fond of keeping options free. But I understand what you mean. We also have the problem with old code.

I would be in favour of supporting this at the moment but to issue a compiler warning, in the future this habit should no longer be possible.

**Comment by jcooper01** [comment]
We have certain places where we use the fact that the integer values line up (like when communicating with external services, and the service needs an integer but we represent it in NAV as human-readable text).
