### ISSUE TITLE
Report.Execute does not work with parameters when report is a variable (BC15 CU3)

### ISSUE THREAD

**Issue by vitaliizz** [microsoft/AL#5710]
**Describe the bug**
The same parameters passed to a single report which is called differently:

Report.Execute(Report::MyReport, Params); - report takes parameters into account
MyReport.Execute(Params); - report ignores parameters

The problem started in BC 15 CU 3.

**To Reproduce**
Steps and to reproduce the behavior:
1. Deploy extension
2. Run Customer List page
3. Enter any text on report request page
4. Hit Ok
5. 2nd and 3rd messages should return the same result

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Params: Text;
        MyReport: Report MyReport;
    begin
        Params := Report.RunRequestPage(Report::MyReport);
        Message(Params);
        Report.Execute(Report::MyReport, Params);
        MyReport.Execute(Params);
    end;
}

report 50100 MyReport
{
    ProcessingOnly = true;

    requestpage
    {
        layout
        {
            area(Content)
            {
                group(GroupName)
                {
                    field(Name; Msg)
                    {
                        ApplicationArea = All;
                    }
                }
            }
        }
    }

    trigger OnPostReport()
    begin
        Message(Msg);
    end;

    var
        Msg: Text;
}
```

**Expected behavior**
Report.Execute should return the same result despite on how the report is called.

**Screenshots**
![image](https://user-images.githubusercontent.com/37546680/76061886-2ee4de80-5f8d-11ea-835f-9f40c5cf8ba4.png)

**5. Versions:**

 - AL Language: 
4.0.229715

 - Business Central:
Version: US Business Central 15.3 (Platform 15.0.40073.41044 + Application 15.3.40074.40822)

**Comment by primopayday** [comment]
This is a very critical issue for us, it prevents users from being able to run payroll batches.  Please let us know a timeframe on when it might be resolved.  Thank you

**Comment by atoader** [comment]
Hi @primopayday ! We are looking into this. Has this issue started happening with the 15.3 release or was it happening before?

**Comment by vitaliizz** [comment]
Hello @atoader ,
Yes, this issue started happening in 15.3 release. The same code works okay at least in 15.1 and all earlier versions. All our customers with BC online who has recently upgraded to 15.3 release reporting the issue in our app which is caused by this error.

**Comment by primopayday** [comment]
It did not happen until the 15.3 release.

Thank you

On Mar 7, 2020, at 2:10 AM, Alexandru Toader <notifications@github.com> wrote:

﻿

Hi @primopayday<https://github.com/primopayday> ! We are looking into this. Has this issue started happening with the 15.3 release or was it happening before?

**Comment by primopayday** [comment]
We know for sure it works correctly in 15.2 and below because we have many customers on those versions.

15.3 is the version that has the bug.

Thank you

On Mar 7, 2020, at 2:20 AM, vitaliizz <notifications@github.com> wrote:

﻿

Hello @atoader<https://github.com/atoader> ,
Yes, this issue started happening in 15.3 release. The same code works okay at least in 15.1 and all earlier versions. All our customers with BC online who has recently upgraded to 15.3 release reporting the issue in our app which is caused by this error.

**Comment by primopayday** [comment]
Do you have any updates for us regarding this issue?

Thank you,
Drew

**Comment by primopayday** [comment]
Hi, I'm still looking for an update on this, customers are being upgraded to 15.3 and it is breaking our payroll batch creation process which is the most critical process in our solution.  Please let us know when this will be resolved.  Thank you

**Comment by jensmpmsft** [comment]
This is an unfortunate regression we introduced as part of allowing 3rd party print providers. It affects versions 15.3, 15.4 and 16.0. We have a fix ready for next CU (for on-premise), and we are looking at how we can hotfix the affected versions in the hosted D365 Business Central.
We are sorry for the inconvenience

**Comment by qutreson** [comment]
This issue appears to have been fixed and backported to the impacted versions.
