### ISSUE TITLE
Issue while publishing app in Cloud SAAS Model

### ISSUE THREAD

**Issue by shikhapathaniasingh** [microsoft/AL#5713]
**Describe the bug**
I am trying to publish an existing app on Visual Studio code. This app was successfully publishing on Sandbox environment but it just stopped few days back and I have tried to resolve it but not happening. I get the following error when I try to compile and publish the app:

[2020-03-09 11:10:02.94] The request for path /v2.0/Sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code 422. Reason: The extension could not be deployed because it is already deployed on another tenant.

Solutions tried : I unpublished and uninstalled the app from the Sandbox environment. Although there are many articles specifying to un-publish using Business Central Command Powershell but in my case the Client database is under SAAS model hosted on cloud.

Kindly suggest how can I resolve this error or let me know if I am doing something wrong in the process.

**To Reproduce**
Steps and to reproduce the behavior:
1.We have to compile and publish the app.

**Expected behavior**
App should have been published successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/57476944/76195622-277a3b00-6202-11ea-8ae3-9cfe528b15d9.png)

**5. Versions:**

 - AL Language:  AL language Version - 4.0.229715

 - Business Central:Version: W1 15.3 (Platform 15.0.40073.41258 + Application 15.3.40074.40822)

Kindly help how I can resolve this.

**Comment by mjmatthiesen** [comment]
Honestly, never ever deploy from vs code. Just build the app and then upload the extension. Deploying from VS Code always results in issues and isn't worth the time.

**Comment by shikhapathaniasingh** [comment]
Thanks for your reply.

I tried uploading the app. Changing the app version and then uploading resolved this issue.

Thanks :)
