### ISSUE TITLE
Debugger does not show the 'Fields' of a record variable

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5714]
**Describe the bug**
Very often while debugging, the variables group contains a local / global variable of type "Record", showing Field : Count = X. Normally, one would expect to see the '>' icon to drill down to the actual fields and see the content. however, very often the '>' symbol is not available.

Only workaround to use is to hover over the variable in code and to drill down to the field contents.

![image](https://user-images.githubusercontent.com/25268332/76200615-3f49c300-61f2-11ea-8c1f-1215430bb021.png)

PS: In some scenarios it might refresh if you navigate to the next line, however this might be too late since the function / publisher / ... might have exited already...

**Expected behavior**
Get **real time** insights to the record variable field values in the variables group of the debugger.

![image](https://user-images.githubusercontent.com/25268332/76200844-9059b700-61f2-11ea-9130-391609faeb57.png)

**5. Versions:**

![image](https://user-images.githubusercontent.com/25268332/76200713-643e3600-61f2-11ea-8b38-d58a5d4131e5.png)

**Comment by mjmatthiesen** [comment]
[The updates to VSCode that was just released](https://code.visualstudio.com/updates/v1_43#_debugger-extension-api) will hopefully improve that, and the hover ability. Will likely take the team some time to implement.

**Comment by atoader** [comment]
Can you try out our preview build? We are working on uptaking the new VSCode API.

**Comment by fvet** [comment]
If you're confident the above will be solved in the newest builds, you can close the issue. I'm currently still running on v15 and it will take some months before we will actually adopt v16 / newer builds. Will log another issue if the issue would still appear.
