### ISSUE TITLE
The data cannot be shown because it is not valid.

### ISSUE THREAD

**Issue by MahyarFarshi** [microsoft/AL#5715]
Hi 
I'm trying to add notes to the note factbox through code. But I get this "The data cannot be shown because it is not valid." in the note box. 
The code I'm using is: 
``RecLink.Init();
                    RecLink.Validate("Record ID", ServiceHdr.RecordId);
                    RecLink.Validate(URL1, Rec.ExtURL);
                    RecLink.Validate(Type, RecLink.Type::Note);
                    RecLink.Validate(Created, CurrentDateTime);
                    RecLink.Validate(Company, CompanyName);
                    RecLink.Validate("User ID", UserId);
                    RecLink.Validate(Description, Rec.Description);
                    RecLink.CALCFIELDS(Note);
                    RecLink.Note.CREATEOUTSTREAM(OutStr);
                    OutStr.WRITE(RecLink.URL1);
                    RecLink.Insert();``

My intension is to add a link to Service Order, Sales Order and Jobs, but as the Link Factbox is hidden by default, I'll insert my document link into the note Factbox. 
I'll prefer to use Link instead of Note. But is there a way to see the link without extending the page?

BR
Mahyar 
<img width="328" alt="Anmærkning 2020-03-09 123934" src="https://user-images.githubusercontent.com/6927474/76209819-1847bd00-6203-11ea-98dd-a0436ac63446.png">

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
