### ISSUE TITLE
Unable to add 'Extension field' to 'Extension List Page' and 'Extension Card Page' with designer. 

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/AL#5719]
**Describe the bug**
We are trying to add '**Extension field**' directly to '**Extension List Page**' and '**Extension Card Page**' using designer.

Getting error, you can find in the attached screens and docker logs me out.

**To Reproduce**
Try to add 'Extension Field' to Extension List Page or Extension Card Page.

**Expected behavior**
It should be possible to add 'Extension Fields' to 'Extension pages'.

**Screenshots**
![Project Card](https://user-images.githubusercontent.com/57799519/76412039-f42ddc80-63b8-11ea-9b28-f1be1b889570.png)
![Projects List](https://user-images.githubusercontent.com/57799519/76412041-f4c67300-63b8-11ea-9dab-397a2382510f.png)
![Error](https://user-images.githubusercontent.com/57799519/76412038-f2fcaf80-63b8-11ea-8b2b-800297a72169.png)

**Versions:**

 - AL Language: 4.0.231354

**Comment by atoader** [comment]
The extension list page, as most pages in the System Application is not extensible, What fields  would you want to add?

**Comment by Rambabu-Billuri** [comment]
It is a custom 'Boolean' field.

**Comment by atoader** [comment]
I think that the best way to move forward with this would be to open an issue on the ALAppExtensions repository. After discussing it internally, the issue does not concern the developer tools or the designer .
