### ISSUE TITLE
The referenced page 'xyz' is not a part

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#572]
we have page as below in extension 1.0 
![image](https://user-images.githubusercontent.com/23735402/29925162-163ae93a-8e7d-11e7-8978-30a9f4790a73.png)

converted as extension 2.0
![image](https://user-images.githubusercontent.com/23735402/29925192-26c31f0c-8e7d-11e7-8252-7952b7d0aa4b.png)

Getting error as page is not a part.

**Comment by DominikDitoIvosevic** [comment]
But the page Job Ledger Entries is not a PageType = CardPart/ListPart. Why do you wan't to use it as a part?

**Comment by DominikDitoIvosevic** [comment]
This is an undocumented scenario and it has been allowed by cside but it was never intended to be used. The client is not tested for this scenario so it has previously been more like "a bug that is a feature". This is considered an anti pattern.

I have turned the error into a warning for the future update so you will be able to use it for some time but please refactor this code as we will eventually stop supporting this.
