### ISSUE TITLE
AA0205 Use of unassigned variable not relevant on List and Dictionary types

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5720]
**Title**
The rule AA0205 warns on the usage of Lists or Dictionaries if Contains is used before Add.

**Description**
We can use a list in a way we loop accross some set and test first if the elements already exists and then add it to the list.

```
if ItemLedgerEntry.FindSet() then
  repeat
    if not MyList.Contains(ItemLedgerEntry."Item No.") then
      MyList.Add(ItemLedgerEntry."Item No.");
  until ItemLedgerEntry.Next() = 0;
```

In that precise case, MyList.Contains throws AA0205 because it uses MyList before MyList.Add.

I understand this rule in .Net where MyList.Contains throws an error if there is no MyList = new List() but there is not such thing in AL.

**Reason for the rule**
./.

**Bad code sample**
./.

**Good code sample**
./.

**Good and bad practices for fixing the rule**
./.

**Remarks**
It could be interesting to know the goal of this rule because it makes sense in languages where we can have a null value in variable, it is not the case in AL.

**Comment by NKarolak** [comment]
Are there any news?

I've just encountered this warning on MyList.Get:
```
SomeInitializeFunction();
MyVal := MyList.Get(index);
```
 whereas MyList is a global variable that has been assigned/filled earlier in SomeInitializeFunction(), because it is used as a constant.

**Comment by MarcHansenMicrosoft** [comment]
This is fixed in master
