### ISSUE TITLE
BC SaaS Development License

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/AL#5721]
- AL Extension Version: 4.0.229715
- Server Version: 15.2.39060.0

This is less of a code issue and more of a need to understand. 

I am currently implementing a company on BC SaaS. They would like to do some of their own development. They have built a Docker container to do this.

Now in theory there is no more development license and no need to purchase objects. Since they are a SaaS customer they don't even have a license to load. Shouldn't this company be able to develop and publish any extension with objects between 50,000 and 99,999 to that local Docker container? Without a license that differs from what comes with the image?

Or is the only way to attach their development environment to a hosted sandbox?

**Comment by nicolassaleron** [comment]
Hi,
Docker sandboxes are really useful if you are developing ISV apps or if you need to test your app against next releases.
If an end customer wants to develop, they can do that against a SaaS sandbox: no need to work with Docker.

**Comment by MattTraxinger** [comment]
I just kind of expected the development process to be the same, regardless of the company that you work for. The same consistent, repeatable process, no matter what. We're basically saying end-users and partners can develop the same code, but not in the same way. Seems weird.

**Comment by atoader** [comment]
Hi! I would recommend using Docker for local development. It offers developers greater flexibility while getting a very similar experience to what they would see in SaaS. Sandboxes are great for when you want to troubleshoot an issue or are preparing to deploy the solution to the customer.

**Comment by MattTraxinger** [comment]
Except Docker doesn't let you locally test all of the objects that you have access to create. Doesn't make any sense.

**Comment by atoader** [comment]
What objects are those? Can you give an example?

**Comment by MattTraxinger** [comment]
I don't have a full object range, but I am aware of a customer who cannot test objects in the 70,000 to 70,099 object range, despite being able to develop in it. My thought is that they should be able to build a Docker container, with the license that comes with that, and build and test any object that their SaaS tenant has access to.
