### ISSUE TITLE
Tenant database has incompatible Application Family (), current Application Family is BE.

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/AL#5722]
**Describe the bug**
I can't download the symbols anymore when upgrading a database from NAV2018 to BC140.
get -navtenant returns this:
![image](https://user-images.githubusercontent.com/24684493/76438994-04938680-63bc-11ea-8ca0-606ee5152b37.png)
Visual Studio Returns this:
If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-03-11 17:01:56.00] Error: a server-side error occured while processing the request.
Request ID: c69b46e5-0adf-4788-9c77-30185ff45f07
Session ID: 94201593-ac93-428d-af4a-fa2545f6c8c2

**To Reproduce**
Steps and to reproduce the behavior:
Upgrade a NAV2018 database to BC140 and upgrade the Application Family:
Set-NAVApplication -ServerInstance BC140_TEST -ApplicationVersion 14.0.29537.0 -Force
Set-NAVApplication -ServerInstance BC140_TEST -ApplicationFamily BE -Force

**Expected behavior**
I want to download my symbols

**5. Versions:**

 - AL Language: 4.0.229715

 - Business Central: 14.0.29530.0

**Comment by BartPermentier** [comment]
Update: i was able to update my ApplicationVersion via SQL. I can download my Symbols again but still can't publish.
SELECT [applicationversion]
      ,[applicationfamily]
  FROM [dbo].[$ndo$tenantdatabaseversion]

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
