### ISSUE TITLE
Force to remove Per-Tenant Extension

### ISSUE THREAD

**Issue by sirhc101** [microsoft/AL#5724]
At one of my BC SaaS customers we installed a per-tenant extension which was intially planned to be published in AppSource. Because of the time we need for AppSource validation preperations we were forced to renumber the App from ISV range to customer range and publish it as per-tenant extension at the SaaS environment.
Now the app has been published in AppSource and we want to move the customer to use the AppSource app instead of the per-tenant extension.

While the development moved on and before we released the final version to AppSource we unfortunately splitted the app and moved two tables to a separate extension. Now we've 2 big problems we're we need some tool to solve.
1. We cannot update the per-tenant extension anymore
The per-tenant extension and the AppSource version use the same App-ID. This causes to problems when updating the per-tenant extension, because BC is complaining about a App in AppSource using the same App-ID.

2. We cannot install the AppSource app
The AppSource app cannot be installed because BC is complaining about destructive changes (deletion of the two tables). Because the two apps are now in a different app (with same table name) we do now have a really bad situation.

I know this is not the right place to ask for support, but I think in general we need some option to force the (complete) deletion of an per-tenant extension in BC SaaS. Is there any way to do this?

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/

**Comment by atoader** [comment]
@sirhc101 please open a request with support and we'll think of a way to fix this in the backend. Please reference this GitHub issue. Support will ask for any additional information that we will need.,
