### ISSUE TITLE
Interfaces and Options as parameters

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#5729]
**Describe the bug**
If you add a procedure in an interface with an option as a parameter, the "implementer" will always say that:
'MyImplementer' does not implement the interface member 'MyInterface.test'.AL(AL0582)

**To Reproduce**
Steps and to reproduce the behavior:
```
interface "MyInterface"
{
    procedure test(myParam: Option)
}

codeunit 50100 "MyImplementer" implements MyInterface
{
    procedure test(myParam: Option)
    begin
    end;
}
```

``` AL Code to reproduce the issue ```

**Expected behavior**
not throw error

**Screenshots**
![image](https://user-images.githubusercontent.com/36199751/76766497-61b28200-6798-11ea-933f-31c9a20fa120.png)

**5. Versions:**

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.236243
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

In Docker Container
Version: W1 16.0 (Platform 16.0.11233.11615 + Application 16.0.11240.11673)
Azure AD tenant: common, Environment: Sandbox

**Comment by stefanoPrimo** [comment]
I think this issue is dead, isn't it?

**Comment by atoader** [comment]
We mark issues that appear to be bugs with the "bug" tag, but we only add the "in-progress" tag when we have capacity to work on it.

**Comment by hemisphera** [comment]
Just to clarify: even if the options *does* have members it does not work either. So basically you cannot use `Option` in interfaces in any way.

**Comment by kine** [comment]
Same for return value of type Option.

Example:
```
procedure GetOptionValue(): Option;
```

Used to get old Option value for the specific enum type when interacting with standard code...
