### ISSUE TITLE
The control 'Part1904257908' is not found in the target

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#573]
standard page 9014 has controls like
![image](https://user-images.githubusercontent.com/23735402/29926107-0eeb8a24-8e80-11e7-9d28-90110a90c5fc.png)

when we are extending it, we are getting control not found.

![image](https://user-images.githubusercontent.com/23735402/29926153-3a921d6e-8e80-11e7-83cf-1e904f649277.png)

**Comment by pmohanakrishna** [comment]
Do I have to run txt2al command again to fix it or can directly build using previous files? somehow this fix is not working directly..

**Comment by StanislawStempin** [comment]
You would need to go through the conversion process again as this was fixed in the ExportToNewSyntax command. Remember about using the new switch -ExportToNewSyntax for the delta generation as well.

**Comment by pmohanakrishna** [comment]
do you mean in Compare-NAVApplicationObject command for delta generation?

**Comment by thpeder** [comment]
You need to export your code from the database again.
You can read more about it here: https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-txt2al-tool

When you have the two .txt files exported in the new syntax and you want to generate the delta file, you also need to give Compare-NavApplicationObject the flag ExportToNewSyntax.
You can read more about that here: https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-generating-delta-files

**Comment by pmohanakrishna** [comment]
I am using Anniversary update and didn't have option ExportToNewSyntax in Compare-NavApplicationObject.

Am I missing anything?

![exporttonewsyntax error](https://user-images.githubusercontent.com/23735402/34665554-a539a918-f486-11e7-87fe-83f0a2e845a2.png)

**Comment by thpeder** [comment]
I have just tried downloading the docker image: microsoft/dynamics-nav:devpreview-anniversary-w1
and ran the command: Compare-NAVApplicationObject -OriginalPath .\ORIGINAL.txt -ModifiedPath .\MODIFIED.txt -DeltaPath DELTA.txt -ExportToNewSyntax
Which all worked fine.

Are you using the Azure image or a docker image and if so which tag did you use?

**Comment by pmohanakrishna** [comment]
Azure image..

**Comment by thpeder** [comment]
I have just tried creating a new Azure Image and also there I have the parameter and the command works as expected.

It seems you have ended up with an older version, so I would recommend creating a new vm.
