### ISSUE TITLE
ClearAll should not clear variables from other apps/base

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#5730]
This is a weird situation that we discovered yesterday, and I'm reporting it here because I think it should be considered a bug in AL more than a problem with the base Business Central code:

A coworker was extending the Sales Invoice Statistics page. She added some code in the OnOpenPage trigger, to calculate one value and assign it to a global variable. Then, in the OnAfterGetRecord trigger, she used that value to calculate some record specific data. So far, so simple...

It didn't work. When the OnAfterGetRecord was invoked, the variable that she had assigned had no value. We spent quite some time trying to find out what the hell was happening (we step short of calling The Ghostbusters), until she remembered this method and searched for it in the base AL object. And lo and behold, there was a call to ClearAll in the OnAfterGetRecord trigger of the standard Sales Invoice Statistics page.

As far as I know this is dangerous, because it means that ClearAll is clearing all global variables, regarding of scope. We can try to overcome this particular problem in the Sales Invoice Statistics by getting the value that we want in every OnAfterGetRecord (performance be damned), but it is a bit worrying that the base AL code (and maybe other extensions?) can break our apps by calling this method.

**Comment by salgiza** [comment]
Some further info: we made some extra tests in BC15, and ClearAll worked correctly in that version, so this seems to be a bug en BC16. Sorry about that, I thought this wasn't particular of this version and forgot to mention the version were we got this problem was: ES Business Central 16.1 (Platform 16.0.11425.0 + Application 16.1.11449.0).

Published using v5.0.236243 of the AL extension

**Comment by atoader** [comment]
The issue should be fixed in the GA version of BC.

**Comment by CarlosAndreuLlaneras** [comment]
Hello @atoader,
I'm facing this problem in the current version of BC 17.3 ES.
Could please confirm that this problem is fixed in BC17?
Thanks
