### ISSUE TITLE
'in' statement overflow warning CodeCop

### ISSUE THREAD

**Issue by prakalovic** [microsoft/AL#5731]
**Describe the bug**
There is CodeCop analyzer overflow warning when using "in" statement with different Texts

Steps and to reproduce the behavior:
AL Language Version 4.0.229715
1. Enable CodeCop analyzer
2. Use the following code
![image](https://user-images.githubusercontent.com/62331086/76953170-f0e5a400-6916-11ea-848a-3b5187b0a5d4.png)

**Comment by qutreson** [comment]
I can reproduce this issue with the latest developer preview:
```
    local procedure MyProcedure()
    var
        varText50: Text[50];
        varText100: Text[100];
        varText: Text;
    begin
        if varText50 in [varText100, varText] then;
    end;
```

**Comment by qutreson** [comment]
This issue should be fixed in our latest developer previews.
