### ISSUE TITLE
I can't see my Page Extension in BC OnPrem

### ISSUE THREAD

**Issue by SabrinaSchulte** [microsoft/AL#5732]
Hello,

I already searched the Internet for quite some time but I never found a Solution.
There were similiar posts but they forgot ApplicationArea or UseCategory.. but I have it in mine.

This is all sorts of frustating.

Before we start.

I installed Business Central W1 Spring '19 on Windows Server 2012 R2.

Here is my Launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "port": 7049,
            "serverInstance": "BC140",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
```
With Get-NAVWebServerInstance I get the following:
```
WebServerInstance: BC140
Website: Microsoft Dyamics 365 Business Central Web Client
Uri: http://localhost:8080/BC140
SiteDeploymentType: SubSite
Configuration File: C:\inepub\wwwroot\BC140\navsettings.json
ClientServicesPort: 7046
ManagementServicesPort: 7045
ClientServicesCredentialTyp: Windows
DnsIdentity:
Server: localhost
ServerInstance: BC140
Version: 14.0.29530.0
```

TMI? Sorry. Anyways..

So I made a Page Extension in Visual Studio.
Went to the WebClient to see if it's there and it's not..

```
pageextension 60001 "JSMT-CustomerCard" extends "Customer Card" //MyTargetPageId
{
    layout
    {
        addlast(General)
        {
            field("JSMTNo. of Invoices"; "No. of Invoices")
            {
                Caption = 'My Test - SSC';
                ApplicationArea = All;
            }

        }
    }

    actions
    {
    }
}
```
Am I being stupid and missed something simple?
Forgive me if it is indeed simple.. I'm new to Business Central and Visual Studio Code.

Please help me.

Thank you and
Kind regards

**Comment by NKarolak** [comment]
> So I made a Page Extension in Visual Studio.

And you've published your change successfully to your local database specified in launch.json?

Your extension object looks good, so far.

**Comment by SabrinaSchulte** [comment]
Hey NKarolak,

Apparently I missed that step..
when I publish it, it's there. 

I didn't even know I had to do this step to be complety honest with you.
But it works now.. 

So!
Thank you!

**Comment by qutreson** [comment]
Closing this issue as it seems to have been resolved.
