### ISSUE TITLE
Report.RunModal stopped working with Custom Layouts in BC 15 (CU3)

### ISSUE THREAD

**Issue by charlespockert** [microsoft/AL#5733]
When using `Report.RunModal` after setting a temp custom layout, reports appear to run but never download to client.

e.g.

```
ReportLayoutSelection.SetTempLayoutSelected(ReportLayoutCode);
REPORT.RUNMODAL(ReportID, false, false, RecordToUse);
ReportLayoutSelection.SetTempLayoutSelected('');
```

This never downloads onto the client - they see nothing in their browser.

If I remove the `SetTempLayoutSelected` it works correctly and downloads.

This was working in 15.2 and stopped working in 15.3.

The workaround at the moment is to save the report to a stream instead:

```
TempBlob.CreateOutStream(OStream);
Report.SaveAs(ReportID, '', ReportFormat::Pdf, OStream, RecRef);
TempBlob.CreateInStream(IStream);
FileName := 'SomeFileName.pdf';
DownloadFromStream(IStream, 'Report', '', '', FileName);
```

As you can imagine, this has broken several tenant extensions which use `Report.RunModal`.

This is similar to other report issues happening in 15.3 such as:

https://github.com/microsoft/AL/issues/5710

**Comment by SirBETE** [comment]
We had a likewise problem on a SaaS customer, running BC15.3 .
A custom action on sales order ran a custom report where the customer changed the lay-out to a customized Word lay-out (That's a lot of 'custom' ... :p).
Clicking on the action did nothing.
Removing the lay-out to the default build-in, ran the report.

We made a MS Call (120031222000907), was recognized as a bug and product team worked on a fix. Now it works again.
Application: 15.4.41023.41400
Base application: 15.4.41023.41956
System application: 15.4.41023.41932

```
Action on sales order page
            action(SODelivNoteNoPrices)
            {
                ApplicationArea = All;
                Caption = 'Sales Order Delivery Note without Prices';
                Image = Order;
                Promoted = true;
                PromotedCategory = Process;

                trigger OnAction()
                var
                    SO: Record "Sales Header";
                    SODelivNoteNoPrices: Report SODelivNoteNoPrices;
                begin
                    CurrPage.SetSelectionFilter(SO);
                    SODelivNoteNoPrices.SetTableView(SO);
                    SODelivNoteNoPrices.RunModal();
                end;
            }
```

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
