### ISSUE TITLE
After Upgrade BC client crash when a query supply data to report

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#5734]
After upgrade BC client is crashing when the report tries to run.  Special feature of this report is it is getting the data from a query.  We can run the query on it's own and loop through and get the values.  But not sure what is causing the crash.  Can you please investigate and pass this object to the product development to get it resolved.  This is a key KPI report customer used in previous version of NAV.  Which worked perfectly worked until we upgrade 
the system to BC - Wave 2.
[Top Sales Report.zip](https://github.com/microsoft/ALAppExtensions/files/4345187/Top.Sales.Report.zip)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
