### ISSUE TITLE
Rename symbol (F2) should not be allowed on extension field rename

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5735]
**Describe the bug**
When modifying a standard field with a table or page extension, and using F2 on the name after the "modify" keyword, code using that field will be updated.

**To Reproduce**
Use a standard BC repo attached to Git.
Add the following table extension object:
```
tableextension 50000 "Test Rename Symbol" extends Item
{
    fields
    {
        modify("No.")
        {
            Caption = 'Item No.'; // just a dummy line
        }
    }

}
```
Enter `"No."`, press F2, and enter something else, e.g. "Item Number Test F2" and press Enter.
Review the changes tracked by Git: All fields that former referenced to field `Item."No."`, are now referencing to` Item."Item Number Test F2"`. This leads to new compiler errors, since no "Item Number Test F2" fields exists in the Item table.

**Expected behavior**
I expect that F2 is not allowed after keyword "modify".
The application should behave as if I had changed "Item No." manually into the new value, without F2 --> no update of other code lines

**Versions:**

 - AL Language: 5.0.236243

 - Business Central: any version

P.S.: if you're asking, why I should want to rename that field name after "modify": it was simply a mistake during a batch rename of extension fields to comply with AppSource.

**Comment by atoader** [comment]
Hi @NKarolak ! I agree that there are specific cases where rename could be prevented, but we do not plan to address this in the near future. I will close this as wontfix for now.
