### ISSUE TITLE
Extension is out of sync with BC runtime - again

### ISSUE THREAD

**Issue by robvon** [microsoft/AL#5737]
- AL Extension Version: 4.3

- Server Version: 4.4

 AL Extension, supported runtimes

Seems you have quietly fixed it on Friday 20 March

**Comment by robvon** [comment]
[2020-03-20 13:39:12.73] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 4.4
- Web API: 4.0
- Debugger: 3.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3
- Supported Web API: 1.0, 2.0, 3.0, 4.0
- Supported debuggers: 1.0, 2.0, 3.0

**Comment by robvon** [comment]
That should leave a few programmers out of work.

**Comment by atoader** [comment]
Thanks, @robvon ! We apologize for the inconvenience this has created. We are working on automating the release pipeline for the VSCode extension so that it does not fall behind. You can always grab the latest VSIX from the insider Docker image.
