### ISSUE TITLE
Lot No. Information not searchable

### ISSUE THREAD

**Issue by kevindstanley1988** [microsoft/AL#5741]
When searching for the Lot No. information page I cannot search in a non-cronus(copy of cronus) company. I have setup a new user as SUPER permissions and have the same problem so it is company specific, not user specific.

**Describe the bug**
I key in "Lot No." in the "Tell me what you want to do" search and nothing shows in the list

**To Reproduce**
This company was created months ago and now the Lot No. Information List is not searchable.

**Expected behavior**
Searching "Lot No." should come up with the list. I am not aware of a way to remove Base BC pages from the search.

**Screenshots**
![image](https://user-images.githubusercontent.com/5685997/77183121-3d121f00-6aa4-11ea-8483-9bb59b660b6b.png)

**5. Versions:**
 - AL Language: 4.0.249486
 - Business Central:
15.1 (Platform 15.0.37898.0 + Application 15.1.38071.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
