### ISSUE TITLE
Renaming an object causes all translations to be lost

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5746]
When an object is renamed (using F2), translation units in XLIFF file are not renamed. 

**Describe the bug**
When an object is renamed (using F2), translation units in XLIFF file are not renamed. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a page named MyPage
2. Add a field with the Caption = 'My Field'
3. Translate this field in a XLIFF file with fr-FR as the target language for instance.
4. Rename MyPage to "MyPage 2"

**Expected behavior**
The caption of the field has not been changed, it would be expected the translation unit would follow the renaming
In fact, due to the fact the trans-unit id has changed, the translation is lost.

**Screenshots**
./.

**5. Versions:**
 - AL Language: 5.0.236243

**Comment by atoader** [comment]
Hi @nicolassaleron ! At the moment, this is by design. 
Would you mind filing a BC Idea for this issue?

**Comment by nicolassaleron** [comment]
There is a already a more complete idea describing this improvement and others:
https://experience.dynamics.com/ideas/idea/?ideaid=521d0a28-8d74-e911-80e7-0003ff689b0e
