### ISSUE TITLE
The request for path failed with code NotFound. Reason: Not Found

### ISSUE THREAD

**Issue by jhanvincent14** [microsoft/AL#5748]
**Describe the bug**
Hello Good day. 

I'm a newbie in extension development in BC365.

I cannot publish my extension code on our server. it keeps saying **The Request Path xx/xx/xx  Failed with code NotFound. Reason: Not Found** 

**To Reproduce**
Steps and to reproduce the behavior:
1. I Just press Ctrl+F5

**Expected behavior**
I expect that my extension code will be publish on our local server

**Screenshots**
![image](https://user-images.githubusercontent.com/38903151/77497499-6e199780-6e88-11ea-96c3-f06430e32c67.png)

![image](https://user-images.githubusercontent.com/38903151/77497521-783b9600-6e88-11ea-9cdb-3ab77086963b.png)

**5. Versions:**
 - AL Language: 
**4.0.249486**

 - Business Central:
BC365 140 14.0.38650.0
"platform": "14.0.0.0",
"application": "14.0.0.0",
"runtime": "3.0"

**Comment by atoader** [comment]
Have you enabled the developer services for your instance? Can you access that endpoint from your favorite browser?

**Comment by atoader** [comment]
You can get further help for your question by using one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by jhanvincent14** [comment]
> Have you enabled the developer services for your instance? Can you access that endpoint from your favorite browser?

Yes, Sir. I already Enabled it. also I can access the endpoint on my browser. also the weird thing is it keeps asking Username and Password if I press ctrl + f5. i mean after I enter the credentials, it repeats itself and asking another credentials, its like it is on a loop.

**Comment by atoader** [comment]
What is your launch.json? What authentication is your server using?

**Comment by moedesign** [comment]
I had the same error message and in my case it was a typo in the launch.json right in the environmentName property.

**Comment by MunyaoN** [comment]
The credentials is because the authentication mode is userpassword. If you don't want to input username and password change the authentication mode to windows
