### ISSUE TITLE
Can not deploy extension to the cloud production

### ISSUE THREAD

**Issue by ansdk** [microsoft/AL#5749]
I am not able to publish my extension to the cloud production using object numbers within the range 6217181-6217281.

We applied for an object range at microsoft and were assigned this range 6217181-6217281.

I get this error in the production environment:

![image](https://user-images.githubusercontent.com/42337387/77525722-bdac9300-6e89-11ea-9a31-ad6bf58de921.png)

This issue only concerns the production system. **It works in the sandbox**.

Does anybody know why?

In this article section **_ISV number range_**:
https://www.kauffmann.nl/2018/03/30/object-licensing-with-microsoft-dynamics-365-business-central/

it tells:

> So ISV’s could choose to use their existing number range and convert (parts of) their existing solution to an AL extension. This AL extension will then be usable both on-premise and on Business Central. **_What’s more, it will be possible to publish these extensions as an app on AppSource_**. That means there is no need to split development between cloud and on-prem.

**It is possible to publish these extensions as an app on AppSource. It does not tell if it is possible to publish without AppSource.**

**Comment by nicolassaleron** [comment]
Hello,
Not sure about objects in the 6M range, but usually that kind of ranges (8M or 7M) are for ISV.

Meaning that you have to publish your app to App Source first and then install it from the marketplace.

**Comment by ansdk** [comment]
Thanks for your reply. 

However, I find it odd that it works in sandbox.

**Comment by qutreson** [comment]
Closing this issue as it seems to have been resolved
