### ISSUE TITLE
Field type Text is not convertible to field type Code

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#575]
we are adding change log entries page on resource card with 
RunPageLink = Table No.=CONST(156),Primary Key Field 1 Value=FIELD(No.)

which was working fine in Extension 1.0 but getting error in Extension 2.0

![image](https://user-images.githubusercontent.com/23735402/29934605-7bf8d234-8e99-11e7-982d-10dc72618d11.png)

**Comment by StanislawStempin** [comment]
We will investigate it, it's likely an omission in the new type conversion code
