### ISSUE TITLE
Method Upload doesn't work as expected.

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#5751]
**Describe the bug**
When calling Upload method, I pass '<TEMP>' thas is the "MagicPath", and it doesn't hide the window.

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```
        if not Upload('', FileMgt.Magicpath, FileMgt.GetToFilterText('', ''), FileMgt.GetFileName(ClientFilePath), ServerFileName) then
            Error(Text010, ClientFilePath);
**Expected behavior**
It shouldn't show the window when calling upload. I could use File Management, but I can't because there is a bug in BC15 when calling UploadFileSilentToServerPath, it should check that client is web.
**Screenshots**
![image](https://user-images.githubusercontent.com/3531482/77632701-a97e9980-6f4e-11ea-920e-de19ca1c1146.png)

![image](https://user-images.githubusercontent.com/3531482/77632890-e8145400-6f4e-11ea-81ed-f37523ee36e6.png)

**5. Versions:**

 - AL Language: 

 - Business Central: 15.0.37898.0.

**Comment by jbakach** [comment]
The thing here is that I want the client path to move it to another client path when processing.
I see that there's an intention to avoid that. But is there any possibilty to achieve that?
Using .NET won't help, as they're "deprecated" in BC15 when doing RUNONCLIENT.

Thanks.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
