### ISSUE TITLE
Take Picture functionality Issue

### ISSUE THREAD

**Issue by srkkoneti** [microsoft/AL#5755]
https://github.com/microsoft/cal-open-library/pull/20#issuecomment-571609943
We are able to work with Take Picture functionality in Version 15.4. But now it's not working on and getting error 
![image](https://user-images.githubusercontent.com/39953344/77769637-1c306780-706a-11ea-988f-de33a2a3ac60.png)
on  following build
"Platform 16.0.11233.11920 + Application 16.0.11240.11946". Will it work on this version?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
