### ISSUE TITLE
🛑🛑🛑Please contact customer support🛑🛑🛑

### ISSUE THREAD

**Issue by eat110** [microsoft/AL#5756]
how to write request page  with a option field in a report 
![1585361343(1)](https://user-images.githubusercontent.com/28883324/77812431-3efb6400-70dc-11ea-8808-79aaa2566ead.jpg)

it show a message "The property 'OptionCaption' can only be set if the property 'Type' is set to 'Option'"

**Comment by nicolassaleron** [comment]
Hello,
What is the datatype of the variable named IncludeRelatedTables ?

**Comment by eat110** [comment]
hello it is option.but i do not kown how to add this in al.

**Comment by nicolassaleron** [comment]
The documentation about how Option datatype works is available here : https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/option/option-data-type

Below is an example about how you can declare/use an option field in a page in AL:

```
page 8117324 "MyPage"
{
    PageType = Card;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(MyOptionVariable; MyOptionVariable)
                {
                    ApplicationArea = All;
                    OptionCaption = 'Value A,Value B,Value C';
                }
            }
        }
    }

    var
        MyOptionVariable: Option A,B,C;
}
```

**Comment by eat110** [comment]
thanks a lot. it is work well.

**Comment by eat110** [comment]
could you help have a look anther problem.
an error occours when i publish with debug.
https://user-images.githubusercontent.com/28883324/77880257-d0aad300-728e-11ea-833d-312b859e1d01.jpg
and i check the setting.
![image](https://user-images.githubusercontent.com/28883324/77886675-deb32080-729b-11ea-8917-b1d3f4570caf.png)
https://user-images.githubusercontent.com/28883324/77880161-96d9cc80-728e-11ea-9979-b31da98d0cef.png
https://user-images.githubusercontent.com/28883324/77880251-c8529800-728e-11ea-81e8-3f4fd4cee159.jpg
and i have also restarted nav instance.

**Comment by eat110** [comment]
an error occours when i publish with debug.
![image](https://user-images.githubusercontent.com/28883324/77886955-54b78780-729c-11ea-94bf-230e953be4da.png)
and i check the setting.
![image](https://user-images.githubusercontent.com/28883324/77886981-5ed98600-729c-11ea-8742-a41c105866de.png)
![image](https://user-images.githubusercontent.com/28883324/77886990-626d0d00-729c-11ea-9895-49d9c8d9fa90.png)
![image](https://user-images.githubusercontent.com/28883324/77887006-66992a80-729c-11ea-984d-27b6972802ec.png)
and i have also restarted nav instance.

**Comment by KristofKlein** [comment]
it is the publish that complains... the picture of the 150/service/Add-Ins folder... is this the service you deploy against? like if it is a server somewhere the file needs to be on that server. or if it is docker. it needs to be inside docker... dlls will not moved with the app to the Service tier...

Apart from that - don't use the newtonsoft.json...for is it messed up so many deployments with all sorts of strange errors. use the build-in types...apart from that many components of it are also already loaded in the dotnet.al of the system layer...so try to not used it ... it is evil!

**Comment by eat110** [comment]
thank a lot
![image](https://user-images.githubusercontent.com/28883324/77975717-714fd000-732d-11ea-9889-770ca8bf7db7.png)
it is work well when i remove the Version.
