### ISSUE TITLE
An assembly could not be found in the assembly probing paths

### ISSUE THREAD

**Issue by eat110** [microsoft/AL#5757]
an error occours when i publish with debug.
![1585547781(1)](https://user-images.githubusercontent.com/28883324/77880257-d0aad300-728e-11ea-833d-312b859e1d01.jpg)
and i check  the setting.
![1585547890(1)](https://user-images.githubusercontent.com/28883324/77880127-8295cf80-728e-11ea-964a-48767eb27b97.jpg)
![image](https://user-images.githubusercontent.com/28883324/77880161-96d9cc80-728e-11ea-9979-b31da98d0cef.png)
![1585548008(1)](https://user-images.githubusercontent.com/28883324/77880251-c8529800-728e-11ea-81e8-3f4fd4cee159.jpg)

**Comment by qutreson** [comment]
Hi @eat110, are you still facing an issue with publishing your extension? Did you try restarting the server after the dll was added to the add-ins folder?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
