### ISSUE TITLE
access to own app id

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#576]
Is there currently a way to access the app id defined in the app.json from within AL? We have licensing/payment functionality integrated in our extensions and use the app id to differentiate between our different apps. I know, I can use this as a text constant, but it would really be ideal, if we could reference the app id.

Another scenario would be to look for app data in the different app tables, which are using the app id.

**Comment by atoader** [comment]
This should be available in a future update. We are still testing so I cannot give you an exact ETA.

**Comment by pzentner** [comment]
great! thank you
