### ISSUE TITLE
Reports with UsageCategory = none are not runable anymore since 15.3 update

### ISSUE THREAD

**Issue by BernBoit** [microsoft/AL#5760]
**Describe the bug**
UsageCategory is enforced with AL(AW0006). Setting a the value to none gets rid of the warning. Still if a report needs to be launch from a specific page (and not be searchable) setting the usageCategory to None make the report to stop (break out of debug) without any error.

**To Reproduce**
1. added usageCategory = None to a report
2. add the report to a page action
3. run the report.

``` AL Code to reproduce the issue ```

**Expected behavior**
The report should run even if set to UsageCategory  = None,

**Screenshots**

**5. Versions:**
 - AL Language: 4.0.249846
- VSCode : 1.43.1
 - Business Central: 15.3, 15.4 (15.0.40939.41751, app: 15.4.41023.41345)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
