### ISSUE TITLE
Issue with AA0215

### ISSUE THREAD

**Issue by Jackeoh** [microsoft/AL#5762]
The rule AA0215 reports that the file name is incorrect, as it expects the suffix to be included, even though the suffix is in the 'AppSourceCop.Json'
For example:
Object: `pageextension 50100 "Customer List XPD" extends "Customer List"`
Object Name: `CustomerList.PageExt.al`
AppSourceCop.Json: `{
    "mandatoryAffixes": [
        "XPD"
    ]
}`
Result: 
![image](https://user-images.githubusercontent.com/43955934/78148307-a0993680-742c-11ea-93e7-434c5f3e2396.png)

See attached 'Hello World' project modified to in;cude the AppSourceCop.json
(please note symbols had to be excluded from project zip due to file size)
[ALProject3.zip](https://github.com/microsoft/AL/files/4415734/ALProject3.zip)

@MarcHansenMicrosoft

**Comment by MarcHansenMicrosoft** [comment]
Thanks

**Comment by MarcHansenMicrosoft** [comment]
The AppSourceCop.Json should be placed in the root folder of the extension.
