### ISSUE TITLE
CodeCop Analyzer Rule AA0215 is no more compliant with file naming best practice

### ISSUE THREAD

**Issue by elweilando** [microsoft/AL#5763]
**Describe the bug**
CodeCop Analyzer Rule AA0215 is no more compliant with file naming best practice https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming.

**To Reproduce**
Create a new file with Suffix in object name. Using file name like proposed in best practice naming notation result to a warning

```
table 50010 "MyTable N4DE"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(PK; MyField)
        {
            Clustered = true;
        }
    }

}
```
Its the same for other Types like codeunit, page, etc.

**Expected behavior**
No filename warning

**Screenshots**
![2020-04-01_16-34-07](https://user-images.githubusercontent.com/902622/78149950-e824c000-7436-11ea-96a7-d2df6fb6aebc.png)
![2020-04-01_16-34-20](https://user-images.githubusercontent.com/902622/78149961-ebb84700-7436-11ea-8727-df1c7068f3f3.png)

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: no version

**Comment by twityde** [comment]
Same issue, if u use a prefix instead of a suffix.

**Comment by MarcHansenMicrosoft** [comment]
please make sure to place the AppSourceCop.Json in the root of the extension
