### ISSUE TITLE
Missing function: 'Get Posted Document Lines to Reverse' doesn't exist in online BC150!!

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5764]
**Describe the bug**
The Action within the Purchase Credit Memo page of "Get Posted Document Lines to Reverse" has disappeared from Business Central

**To Reproduce**
Ensure you are using a cloud version ie. sandbox and open a Purchase Credit Memo.  Select Actions, Functions and you will see that the 'Get Posted Document Lines to Reverse' option is not there! (It should be after "Apply Entries" and before "Copy Document").

**Expected behavior**
This action is required - and whilst I know it's available for "On-Prem" that isn't the point .. how are we supposed to move our Customers to the cloud with such key functionality being restricted and unavailable in the cloud..!!

**5. Versions:**
15.0.0.0

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
