### ISSUE TITLE
Rule AA0217

### ISSUE THREAD

**Issue by Petyun** [microsoft/AL#5765]
**Describe the bug**
In the StrSubstNo - need to use procedure (that returns text) for format string.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a procedure that returns Text like 'DocNo %1'
2. Add a line like
SomeText := StrSubstNo(GetTranslatedText(),'12345');

``` AL Code to reproduce the issue ```
procedure GetTranslatedText(): Text[100]
begin
  exit('DocNo %1');
end;

procedure UpdateDescription(var SalesHeader: Record "Sales Header")
begin
  with SalesHeader do
       "Prepmt. Posting Description" := StrSubstNo(GetTranslatedText(),"No.");
end;

**Expected behavior**
Using returned text value of the  procedure in the StrSubstNo

**Screenshots**

**5. Versions:**
 - AL Language: 5.0.254558

**Comment by qutreson** [comment]
This issue has been fixed in our latest developer previews
