### ISSUE TITLE
Rule AA0139 when working with text

### ISSUE THREAD

**Issue by Petyun** [microsoft/AL#5766]
**Describe the bug**
the rule does not taking into consideration real length of assigned text

**To Reproduce**
``` AL Code to reproduce the issue ```
   procedure ShortDescription()
    var
        Position: Integer;
        Description1: Text[200];
        Description2: Text[200];
    begin
        Position := 100;
        Description2 := CopyStr(Description1, 1, Position);
        //here I have warning Possible owerflow assigning Text to Text[200]
    end;

**Expected behavior**
It should calculate real length of the text.
**Screenshots**

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central:

**Comment by MarcHansenMicrosoft** [comment]
CodeCop is a static analysis and we do not plan to include dynamic values into it.

If you instead of position write 100 then it should work fine.
Description2 := CopyStr(Description1, 1, 100);

So I have to reject this bug.
