### ISSUE TITLE
TestPage.New on ListPage doesn't open CardPage

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/AL#5767]
**Describe the bug**
In test automation I try to create a new customer bank account using test pages. But using TestPage.New() on the "customer bank account list" doesn't open the "customer bank account card" like it is done by creating it manually in the web client.

**To Reproduce**
    [Test]
    procedure TestTestPage()
    var
        customer: Record customer;
        CustomerCard: TestPage "Customer Card";
        CustomerBankAccountList: TestPage "Customer Bank Account List";
        CustomerBankAccountCard: TestPage "Customer Bank Account Card";
    begin
        customer.Get('01121212');
        CustomerCard.OpenView();
        CustomerCard.GoToRecord(customer);
        CustomerBankAccountList.Trap();
        CustomerCard."Bank Accounts".Invoke();
        CustomerBankAccountCard.Trap();
        CustomerBankAccountList.New();
        CustomerBankAccountCard.Code.SetValue('Test');
    end;

An error occurs at the SetValue line. The test page CustomerBankAccountCard is not open.

**Expected behavior**

**Screenshots**
The bank account card should be opened, so it can be used for further use.

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: (Platform 15.0.40073.40791 + Application 15.3.40822.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
