### ISSUE TITLE
No error when interface with event is not correctly implemented

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5769]
**Describe the bug**
When you implement an interface that contains an event, VS Code will not show an error if the event is just implemented as a function and not marked as an event.

**To Reproduce**

``` 
interface IDemo
{
    trigger OnWhatever();
    begin
    end;
}

codeunit 50000 Demo implements IDemo
{
    procedure OnWhatever()
    begin
    end;
} 
```

**Expected behavior**
As long as procedure OnWhatever() is not marked as an event, there should be an error that the interface is not correctly implemented.

**Screenshots**
![image](https://user-images.githubusercontent.com/19155831/78234953-35a53980-74d8-11ea-8fdc-22874ae2027b.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: n/a

**Comment by ajkauffmann** [comment]
Edit: Maybe I'm going too fast here... Just noticed that it is not even possible (yet?) to subscribe to an event from an interface... 

I do really hope that will become possible in the future!

**Comment by tfenster** [comment]
Yep, we had that discussion as well, you also can't define a publisher in an interface, which woudl be very helpful

**Comment by esbenk** [comment]
Being able to use the Trigger keyword in the interface is a bug.

**Comment by qutreson** [comment]
This issue has been fixed in our latest developer preview for AL extensions that are using version 6.0.307310 or higher. An error is now reported on interfaces declaring a trigger.

![image](https://user-images.githubusercontent.com/31541422/92483753-7e7cbf00-f1e9-11ea-9ca3-ff684aceb6a5.png)
