### ISSUE TITLE
CodeCop Rule AA0218 and AA0225 - Should not warn when ShowCaption = false

### ISSUE THREAD

**Issue by MiePlougstrup** [microsoft/AL#5772]
- AL Extension Version: 5.0.254558

- Server Version: not important

This is code that is very similar to the field on page 5200 Empleyee Card, where a label is used for the field to create a clickable "link".
ShowCaption = false, because the caption should not be shown.

The rules AA0218 and AA0225 should not be applicable when you use the property ShowCaption = false, as the Caption and the Tooltip are not shown in the page.
To follow the warning would only result in unused Caption and Tooltip text, that needs translations which would be unnecessary.

![image](https://user-images.githubusercontent.com/14122139/78245907-8c1a7400-74e8-11ea-9ac7-cb02fca3a8ef.png)

**Comment by AskeHolst** [comment]
See #5670 "AA0225 warns about missing caption when ShowCaption = false"

**Comment by atoader** [comment]
@MarcHansenMicrosoft can you take a look?

**Comment by qutreson** [comment]
This issue has been fixed for AL extension with a version higher than 5.0.272418

**Comment by qutreson** [comment]
![image](https://user-images.githubusercontent.com/31541422/92484423-f519bc80-f1e9-11ea-9229-86680266ab8f.png)

**Comment by MarcHansenMicrosoft** [comment]
Thanks
