### ISSUE TITLE
Service Item Line "Document Type" should be Enum

### ISSUE THREAD

**Issue by romann4u** [microsoft/AL#5774]
**Describe the bug**
ServiceItemLine.Table.al
Document Type = Option
ServiceHeader.Table.al
Document Type = Enum
Assignment of one document type to another one triggers AL0603 warning

**To Reproduce**
Steps and to reproduce the behavior:
    var
        ServHeader: Record "Service Header";
        ServItemLine: Record "Service Item Line";

ServItemLine.Init();
ServItemLine."Document Type" := ServHeader."Document Type";
ServItemLine."Document No." := ServHeader."No.";

**Expected behavior**
No AL0603 warning

**Screenshots**
![image](https://user-images.githubusercontent.com/54829279/78317175-91e77800-752f-11ea-956c-6db2d612f925.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: Version: US Business Central 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.11946)

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
