### ISSUE TITLE
Intellisense does not help on Permissions property

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5775]
**Describe the bug**
When filling the Permissions property on objects, the intellisense does not propose object names.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new codeunit.
2. Add the property Permissions
3. Set the property to tabledata Cust

```
codeunit 70004 "MyCodeunit"
{
    Permissions = tabledata Cust_
}
```

**Expected behavior**
In the code in the previous section, the underscore stands for the current cursor position.
It would be expected to have the following proposals in the intellisense:
* Customer
* Cust. Ledger Entry
* Customer Price Group
...

Currently, nothing is proposed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44807684/78343890-cbee6380-759b-11ea-80b8-ff84de5ffd2b.png)

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: 16.*

**Comment by hougaard** [comment]
Came here to report this too, even the tooltip is less than useful:
![image](https://user-images.githubusercontent.com/3357237/78839736-e797a680-79ad-11ea-9abe-63aa1bba6c8a.png)

**Comment by EmilDamsbo** [comment]
This issue has been fixed:
![image](https://user-images.githubusercontent.com/67266681/199734702-d2425694-c482-4021-b718-353aac61bb3f.png)
