### ISSUE TITLE
BUG - FlowFilters used on pages don't work at all when passing in Guids/Text !!

### ISSUE THREAD

**Issue by navaddict** [microsoft/AL#5777]
Essential functionality (used in C/AL successfully for many years) will not work in BC150 / AL...!

Basically, what I have is a 'Customer User Access' system whereby each User of the system can be given a restricted list of Customers that they can access and their view of the Customer Card / Customer List (etc.) is filtered to only show the records they have permission for.

This worked perfectly in C/AL (all versions from 2009R2 onward (ie. 2015, 2017, BC13 OnPrem, BC14 OnPrem) and so I can confirm this is a bug (also because it works if I comment out a single SetFilter command). Perhaps behind the scenes the MS application is missing a CalcFields command for certain types of applied FlowFilter or something along those lines?

**This is a show-stopper and needs to be resolved urgently.**

I've seen an issue that was logged previously by another user around FlowFields not working on cards (which MS confirmed as a bug) .. but it appears this issue is more wide-ranging hence logging this new call.

I've attached a password secured zip file with the solution contained within (as this is my I.P. and not for sharing!).  When this has been allocated to the relevant member of Microsoft for investigation please have them email me and I'll let them have the password.

I've included a Readme.docx file in the archive which contains user full instructions with screenshots showing how to reproduce this issue.

Many Thanks!

[CustomerUserAccess.zip](https://github.com/microsoft/AL/files/4428459/CustomerUserAccess.zip)

**Comment by dtkb** [comment]
It would be preferable to post a simple set of steps with which other interested users can test/replicate this issue. Is it really so complex or context-sensitive that it requires your entire app to demonstrate?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atoader** [comment]
Also see https://github.com/microsoft/AL/issues/5771
