### ISSUE TITLE
CodeCop Rule AA0218 - Should not warn in RoleCenter, HeadlinePart, Media CardPart etc.

### ISSUE THREAD

**Issue by MiePlougstrup** [microsoft/AL#5778]
**Describe the bug**
It is unnecessary to warn about missing tooltip for fields and actions where the tooltip is not shown in the client.

These are the places I have come across. There can be other places as well.

1. RoleCenter page - area Embedding - Actions
2. RoleCenter page - area Sections - Actions
3. HeadlinePart page - Fields
4. NavigatePage (wizard) - Actions where InFooterBar = true (Back, Next, Finish)
5. Media Field in CardPard - Media can only be shown in the client via a CardPart page. The tooltip for a media field is not visible in the client.

**To Reproduce**
Create pages, fields, and actions as described above without the tooltip property.

**Expected behavior**
I expect not to be warned about missing tooltip when the tooltip is unnecessary because it is not shown in the client.

**Screenshots**
![image](https://user-images.githubusercontent.com/14122139/78423908-00305580-766a-11ea-8cb6-0bb4bd574fdd.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central:

**Comment by atoader** [comment]
@MarcHansenMicrosoft can you take a look at this issue?

**Comment by MarcHansenMicrosoft** [comment]
fixed in master
