### ISSUE TITLE
Unexpected value 'None' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ActionAreaKind

### ISSUE THREAD

**Issue by alimans3** [microsoft/AL#5779]
**Describe the bug**
Upon upgrading from NAV 2018 to BC150, and after solving 2k+ problems, the extension was error-free and ready to publish.
When I tried to publish the extension, I got an error:
The request for path /BC150-Fox/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code 422. Reason: One or more errors occurred.
Unexpected value 'None' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ActionAreaKind'
I couldn't find why this error appeared.

**To Reproduce**
I don't know the reason behind it.

**Expected behavior**
Error-free extension to be published successfully 

Screenshots
<img width="1014" alt="Capture" src="https://user-images.githubusercontent.com/43284381/78455245-c9783080-76a5-11ea-9637-f93c70c16bb2.PNG">

5. Versions:

AL Language: 4.0.206840
Business Central: 15.0.38951.0

**Comment by qutreson** [comment]
Hi @alimans3, do you have any diagnostic for AL0597?

We have seen this kind of issue when your code is referencing some action in a page extension before it is being declared. For instance:

```
pageextension 50100 MyPageExt extends "Customer Card"
{
        actions
        {
                modify(MyAction) // Usage before use, results in warning diagnostic AL0597
                {
                       // Some property or trigger changes
                }

               addfirst(Creation)
               {
                        action(MyAction)   // Declaration
                        {
                        }
               }
        }
}
```

This construct is not allowed. We are currently returning a warning, but we are turning it into an error as it can cause some emit issues similar to the one you are experiencing.

Resolving any warning diagnostics for AL0597 should hopefully be fixing your issue.

If this is not the case, can you provide us with the full stack trace so that we can investigate it further?

**Comment by alimans3** [comment]
Hi @qutreson ,

I don't have any warnings with AL0597 code.

Can you help me with finding the stack trace, I looked into event Viewer and didn't find it.

**Comment by qutreson** [comment]
@alimans3 can you install the latest AL Extension from the VS Code market place (version 2.0.254558)? 
It may provide you with better diagnostics in page extensions than the one you have currently installed (version 4.0.206840)

**Comment by alimans3** [comment]
@qutreson I did already try to update the AL Language from the marketplace to version 5 (you mean?) but nothing changed. No new warnings appeared and nothing changed

**Comment by alimans3** [comment]
For anyone experiencing this in the future, the file that caused this error was a page extension to a CardPart adding an action with a trigger OnAction:

`pageextension 50195 "SmallBussRepCatalogExtPag9025" extends "Small Business Report Catalog"
{
    layout
    {

    }

    actions
    {
        modify(CustomerStatement)
        {
            Visible = false;
        }
        addafter(VendorTop10List)
        {
            action(CustomerStatementMP)
            {
                ApplicationArea = Basic, Suite;
                Caption = 'Customer Statement';
                ToolTip = 'Specifies a list of customer statements.';

                trigger OnAction()
                var
                    CodeExt: Codeunit "Codeunits Extension";
                begin
                    CodeExt.RunCustomerStatementReport(false);
                end;
            }
        }
    }

}`
