### ISSUE TITLE
Suggestion, automatically suggest next field id

### ISSUE THREAD

**Issue by kimnoer** [Microsoft/AL#578]
When creating/modifying a table, and adding fields to it, Intellisense should automatically suggest new ID based on previous ID.

Ie.
...
        field(3;"Code";Code[10])
        {

When I start typing field intellisense should suggest 4 as the next id.

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. This is something we are considering longer-term

**Comment by StanislawStempin** [comment]
This was implemented for the Anniversary Update.
