### ISSUE TITLE
How to add additional filter in edit in Excel in general journal page on

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#5781]
How to add additional filter in edit in Excel in general journal page

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
