### ISSUE TITLE
BC Wave 2 - Base app Translation Web search index problem

### ISSUE THREAD

**Issue by NedimYami** [microsoft/AL#5782]
**Describe the bug**
Translating base app in wave 2 with XLIFF file does not update search index.
The app is showing translation in Turkish, but web search index is still in English.
I translated all base objects.  And I used nav 2018 Lang Dll's which ones translated by partner with PLLP.

**To Reproduce**
Translate base app whit XLIFF
Expected behavior
Update web search index

**Screenshots**
You can see the screenshot as below
![image](https://user-images.githubusercontent.com/42783080/78570827-27d01b00-782e-11ea-9006-7d0058e59aad.png)

**5. Versions:**

AL Language:
4.0.176004
Business Central:
platform 15.0.36510.0 + app 15.0.36560.36649
It is CU3.

**Comment by NedimYami** [comment]
Hi, I have same problem. I can not solve. Could you help me?

**Comment by thpeder** [comment]
Hi @NedimYami,
You need to update to a newer version if you want to translate search items from another app, or you can build base app yourself and include in the xliff file in the translations folder, since then it gets baked into the metadata and is not applied at runtime.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
