### ISSUE TITLE
Saving and removing warning/error takes too long time 

### ISSUE THREAD

**Issue by anwar0206** [microsoft/AL#5783]
Issue Type: <b>Performance Issue</b>

When saving any file, VS Code take too long time. Also when any error or warning is corrected AL take too long to remove them from the count.

Extension version: 5.0.254558
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    69	  9784	code main
    0	    24	  2384	   utility
    1	    72	 10004	   shared-process
    5	   295	 12444	   window (MyItems.Page.al - onPREM.Team - Visual Studio Code)
    0	   131	  2208	     extensionHost
   46	  1184	 14544	       c:\Users\userName\.vscode\extensions\ms-dynamics-smb.al-5.0.254558\bin\win32\Microsoft.Dynamics.Nav.EditorServices.Host.exe /browser:Firefox /logLevel:Normal
    0	     5	 19816	         console-window-host (Windows internal process)
    0	    46	  5016	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    36	 14156	     searchService
    0	     5	 17340	     console-window-host (Windows internal process)
    0	    14	 22232	     watcherService 
    0	     5	 14236	       console-window-host (Windows internal process)
    9	   175	 19548	   gpu-process
    0	    13	 20404	   electron-crash-reporter
    2	    60	 22552	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (MyItems.Page.al - onPREM.Team - Visual Studio Code)
|    Folder (onPREM.Team): 946 files
|      File types: al(837) rdlc(78) json(14) app(2) gitignore(1) png(1) md(1)
|      Conf files: launch.json(1)
|      Launch Configs: al;
```

</details>

**Comment by thpeder** [comment]
Hi @anwar0206,

Thank you for the issue. We are continuously trying to improving performance while at the same time balancing it with adding more features.

**Comment by atoader** [comment]
@anwar0206 there is also an ongoing discussion on this thread https://github.com/microsoft/AL/issues/5768
