### ISSUE TITLE
CodeCop Rule AA00231 Do not use the StrSubstNo or string concatenation as a parameter in the Error method.AL(AA0231)

### ISSUE THREAD

**Issue by kristianeWiise** [microsoft/AL#5786]
**Describe the bug**
We recently updated the AL Language extension to the latest version ( 5.0.254.558 ) and encountered a warnings related to AA00231 rule set. 

Just wanted to ask if we put this as part of the Ruleset will this be deprecated in the future development? 

Otherwise if we need to refactor the codes and put it to a Variable. Is this the intended way to fix the warnings?

![image](https://user-images.githubusercontent.com/60126907/78754378-b7a2d000-79ba-11ea-9d47-53124421d1ee.png)

Any feedback is very much appreciated :) 

Thank you in Advance 

**Screenshots**

![image](https://user-images.githubusercontent.com/60126907/78754369-b2de1c00-79ba-11ea-9000-8186aa68131c.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: Microsoft_Base Application_16.0.11240.11912 ( Preview )

**Comment by NKarolak** [comment]
You should find all information about it here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0231-donotusestrsubstnoinerrormessage

**Comment by MarcHansenMicrosoft** [comment]
@NKarolak is spot on.

You should write 
Error('%1 %2', Text145041_Lbl, Text145045_Lbl);
