### ISSUE TITLE
CodeCop Rule: AA0214 The record {0} should be modified before saving to the database.

### ISSUE THREAD

**Issue by dyepri** [microsoft/AL#5787]
**Describe the bug**
We have recently update our AL Language extension into 5.0.254558 then having ${CodeCop} declared under code analyzer it is now giving me hundreds of warnings. One of them is the CodeCop Rule: AL0214 The record {0} should be modified before saving to the database.

**To Reproduce**
Steps and to reproduce the behavior:
1. Make sure you are using the updated AL Language extension (5.0.254558)
2. Declare a record variable on your code.
3. A warning will appear stating the variable record you declared should be modified before saving to the database.

``` AL Code to reproduce the issue ```

**Expected behavior**
There should be no warnings since it is being use.

**Screenshots**
![image](https://user-images.githubusercontent.com/41933086/78757778-5f6ecc80-79c0-11ea-9626-b46e7d43ea58.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0.11209.0 (Preview)

**Comment by Jeeve65** [comment]
Came here to report the same

**Comment by NCMiMa** [comment]
Hi, here the same!

**Comment by nicolassaleron** [comment]
Is not it a duplicate of [this issue](https://github.com/microsoft/AL/issues/5665)?

**Comment by dtkb** [comment]
> Is not it a duplicate of [this issue](https://github.com/microsoft/AL/issues/5665)?

Yes, so since this one has been marked as `in-progress`, that one should be closed.

**Comment by MarcHansenMicrosoft** [comment]
Just wanted to keep it if there was a variation to cover.
Thanks

**Comment by MarcHansenMicrosoft** [comment]
fixed in master

**Comment by shahramab** [comment]
Hi
How it is fixed?
