### ISSUE TITLE
CodeCop Rule: AA0100 Do not have identifiers with quotes in the name

### ISSUE THREAD

**Issue by RoieSantos** [microsoft/AL#5788]
**Describe the bug**
We are currently updating our extension to BC16 in the ${CodeCop} declared under code analyzer it is showing multiple warnings. Below is one "AL0100 Do not have identifiers with quotes in the name"

**To Reproduce**

1. AL Language extension is installed (5.0.254558)
2. Create a page extension of standard page "Customer Card" (21)
3. Modify the existing field """Balance (LCY)"" - ABS(""Post Dated Checks (LCY)"")"
4. A warning saying "Do not have identifiers with quotes in the name" will appear

**Screenshots**
![image](https://user-images.githubusercontent.com/63336107/78773734-04949f80-79d7-11ea-8913-0c29712a5462.png)

Standard Code BC16
![image](https://user-images.githubusercontent.com/63336107/78773874-360d6b00-79d7-11ea-856c-efe373b8f307.png)

**Versions:**
AL Language 5.0.254558
Business Central : 16.0.11209.0 (Preview)

**Comment by nicolassaleron** [comment]
Well, even Microsoft is not yet compliant with their own rules :)
If this warning annoys you, you can disable it in a ruleset file until Microsoft fix the control name.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

**Comment by MarcHansenMicrosoft** [comment]
It should be ok to refer to to something with a quote in.
Warning should only appear on the actual definition.

**Comment by MarcHansenMicrosoft** [comment]
fixed in master
