### ISSUE TITLE
Bug in BC150 & BC160 - Division by zero!  Currency Exch. Rate (Table 330) Show stopper - need fix urgently!

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5790]
4.0.249486

15.0.0.0

![image](https://user-images.githubusercontent.com/57717503/78791456-ccc23380-79a7-11ea-88d0-a754c59d37e2.png)

Further info:

Created a new Purchase Order and chosen a Job with a Foreign Currency where the Currency Exchange Rates are fully populated with data.

This error is reproduced consistently and we can't add any Purchase Lines to a Purchase Order using this FCY Job.

Not sure if it's relevant but we have extended the Purchase Header to include "Job No." and "Job Task No." and have these populated on both header and lines - so for you to reproduce this issue you may need to create a similar extension.  Although if you can simply amend the code to avoid the division by zero that would be best as we simply can't sell your product without this resolved.!

Many thanks!

**Comment by kalberes** [comment]
I donot think this is related to the AL compiler. Looks like an app issue.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by eque2al** [comment]
This is a definite bug in standard product, we don't have a "SAM" so I need to get this logged ('via collaborate'?) and not simply closed.!  

No clue how to file under collaborate please can you do this ASAP as this is a serious error that prevents us from taking your product to market.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

We cannot handle this type of issues in this repository and guidance has been provided on how to proceed.

**Comment by eque2al** [comment]
I have read that and in particular the 'collaborate' section (https://github.com/Microsoft/ALAppExtensions) but that is clearly talking about resellers helping to design extra parts of the application .. nothing to do with a serious bug in the standard product that needs a Microsoft fix.  Please help!
