### ISSUE TITLE
Tree view pages The property 'IndentationControls' cannot be used in this contextAL(AL0124)

### ISSUE THREAD

**Issue by stijn9830** [microsoft/AL#5792]
**Describe the bug**
When creating a new page, which I want to use as tree page, I Get
The property 'IndentationControls' cannot be used in this contextAL(AL0124)

**To Reproduce**

This gives an error whitout any explication

page 95000 "PBL Contact List"
{
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = Contact;
    Caption = 'Valcredo Contacts';
    CardPageID = "Contact Card";
    PageType = List;
    IndentationControls = "No.";

The property 'IndentationControls' cannot be used in this contextAL(AL0124)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/56073675/78878557-dfde0d80-7a52-11ea-9ab8-ee887b7f4827.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: BC

**Comment by nicolassaleron** [comment]
Hi,
The property has to be set on the repeater control, not on the page directly.

See: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-indentationcontrols-property

**Comment by stijn9830** [comment]
My bad.
Thanks for the quick feedback
