### ISSUE TITLE
Extended Enum values are not showing in WebClient!!

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5793]
1. Create a new Option value on SalesLine Table by Extending the predefined **Sales Line Type** enum.
Then publish it and check if it is appearing on the Sales Order page.
Also Compiler is not giving any error or warning when i am defining extendedEnum on ID no. 6 .
![image](https://user-images.githubusercontent.com/33481576/78900276-3ddf1500-7a94-11ea-9144-b83bbfb6e4ea.png)
![image](https://user-images.githubusercontent.com/33481576/78900305-48011380-7a94-11ea-906d-14dbb453f98b.png)

**Comment by thpeder** [comment]
Hi @SUD-D365,
I tried it out locally and it worked just fine for me, so we would need some more information in order to reproduce your issue.

Could you provide which version you are running on?
Where are looking to see that it is not there?
Are you sure you have published to the same instance you have open in the client?

**Comment by SUD-D365** [comment]
> Hi @SUD-D365,
> 
> I tried it out locally and it worked just fine for me, so we would need some more information in order to reproduce your issue.
> 
> 
> 
> Could you provide which version you are running on?
> 
> Where are looking to see that it is not there?
> 
> Are you sure you have published to the same instance you have open in the client?

Ok, so i am trying to do it on MSCloudSandbox as you can see in scrrenshot.
Version is below!!
-  USBusiness Central 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.11946)

**Comment by atoader** [comment]
We will take a look at this. We definitely need to fix checking for the ID of the enum values. For the other issue, can you provide a project to reproduce this and a video recording for where it fails to behave as expected? This will help us focus on the exact issue.

**Comment by AndreyKorepanov** [comment]
It is not reproducible on the local server, but still reproducible in the Sandbox environment. The project is attached.
[ALProject53.zip](https://github.com/microsoft/AL/files/4818683/ALProject53.zip)
