### ISSUE TITLE
Upgraded BC 15.4 database, export-NAVData error

### ISSUE THREAD

**Issue by tguangithub** [microsoft/AL#5794]
**Describe the bug**
We upgraded our customer database from BC 14.7 to BC 15.4, after database upgraded, upgrading success and users can access database, but when we tried to run powershell Export-NAVData to export data and move to Azure environment, we encounter the error. 

Then we ran upgrade by using demo Business Central 14.0 database upgrade to Business Central 15.4, upgrading process successful also, but we got same error when we ran powershell Export-NAVData, here is the error message:
![image](https://user-images.githubusercontent.com/26631688/78953715-0a51ba00-7a97-11ea-8cae-2a3a8f94c33d.png)

and when check SQL server side for standard Business Central tables, we found that compare to demo Business Central database, in table Contraints folder, missing the base application ID, for example, in demo Business Central database MDF$CRONUS USA, Inc_$Customer$437dbf0e-84ff-417a-965d-ed2bb9650972$$systemId and in upgraded database that show as $Customer$$SystemId, missing base application appId.
![image](https://user-images.githubusercontent.com/26631688/78954019-070afe00-7a98-11ea-9887-2efedca7e13d.png)

**To Reproduce**
Steps and to reproduce the behavior:
Using powershell to upgrade demo business central 14.0 to Business Central 15.4, after upgrading, run Powershell Export-NAVData to export all companies data.

``` AL Code to reproduce the issue ```

**Expected behavior**

We expect to have .navdata exported

**Screenshots**
![image](https://user-images.githubusercontent.com/26631688/78954144-69fc9500-7a98-11ea-8df5-ca43e5ad91ef.png)

![image](https://user-images.githubusercontent.com/26631688/78954160-71bc3980-7a98-11ea-8868-e2a33b4714fd.png)

**5. Versions:**

 - AL Language: 

 - Business Central: 15.4
after upgrading from Business Central 14

**Comment by thpeder** [comment]
Hi @tguangithub,

This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

I would recommend you to either open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
