### ISSUE TITLE
Issue with SecurityFiltering in procedure parameters

### ISSUE THREAD

**Issue by adejsy** [microsoft/AL#5796]
**Describe the bug**
In C/AL Code we used to be able to define the Security Filtering property on parameters in procedures. When running the txt2al tool it changes the Security Filtering to the new syntax in AL correctly, however the compiler always reports issues where the SecurityFiltering is a parameter in a procedure.

**To Reproduce**
Create a procedure whereby SecurityFiltering is set on a parameter in the procedure. The var declaration will work fine but the parameter in the procedure will report an error by the compiler.

    procedure UpdateContactFromRecord([SecurityFiltering(SecurityFilter::Ignored)]Contact: Record Contact)
    var
        [SecurityFiltering(SecurityFilter::Ignored)]Contact2: Record "Contact";        
    begin
        
    end;

**Expected behavior**
In the above example the compiler should not moan about SecurityFiltering declared on a parameter in a procedure. It should accept it the same way variables with Security Filtering are declared - as per the example above.

**Versions:**
 - AL Language: 5.0.254558

**Comment by dtkb** [comment]
What error? Does it perhaps go away if the argument is passed by ref by being declared as `var`?

**Comment by adejsy** [comment]
Not sure if any progress has been made on this but the issues still exists. Declaring as var makes no difference. It looks like you simply can't set SecurityFiltering on parameters in a method. You have to refactor the code to set the security filtering explicitly on the first line of code after the "begin" in the function.

So refactoring this we have to currently;
1) Remove the security filtering from the parameter
2) Set it in the start of the function - so in the example above after the "begin" the first line would be Contact.SecurityFiltering := SecurityFilter::Ignored;
