### ISSUE TITLE
alc.exe not working or undocumented change in usage

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#5797]
**Describe the bug**

Running our PS-compile script suddenly stopped working with newer docker images. Alc.exe gives no output whatsoever.

**To Reproduce**

Steps and to reproduce the behavior:
- Unpack c:\run\ALLanguage.vsix 
 - Run alc.exe, eg. 
c:\run\ALLanguage\extension\bin\alc.exe /project:"C:\myproject" /packagecachepath:"c:\run\prereqs"  /analyzer:"c:\run\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll"

-> no output

I have not managed to get ANY output from alc.exe with any parameters.

**Expected behavior**

alc.exe should compile the project and output debug information, as it previously has

**5. Versions:**

Docker-inside 16.0.11240.12052-fi

**Comment by navdotnetreqs** [comment]
Any ideas on this?

**Comment by atoader** [comment]
Can you provide detailed instructions on how to reproduce this? It seems related to https://freddysblog.com/2020/02/26/the-world-after-february-18th/ , but without a repro, it is hard to say.

**Comment by janrik** [comment]
> Can you provide detailed instructions on how to reproduce this? It seems related to https://freddysblog.com/2020/02/26/the-world-after-february-18th/ , but without a repro, it is hard to say.

Unpack alc.exe from the vsix-file in the container. Then run it. With ANY parameters.

**Comment by atoader** [comment]
We do the same in our gates and we have not seen any issues. Is there any additional information that you can provide that might help get to the bottom of this?
