### ISSUE TITLE
AL0603 An implicit conversion is being performed from a value of type 'Option' to a value of type 'Enum "Purchase Line Type"'. This conversion can lead to unexpected runtime issues. This warning will become an error in a future release.AL(AL0603)

### ISSUE THREAD

**Issue by RoieSantos** [microsoft/AL#5800]
**Describe the Warning**
We are currently updating our extension to BC16 in the ${CodeCop} declared under code analyzer it is showing multiple warnings. Below is one "AL0603 An implicit conversion is being performed from a value of type 'Option' to a value of type 'Enum'

**To Reproduce**
1. AL Language extension is installed (5.0.254558)
2. Create a page extension of "Purchase Line" (39)
3. In the table list there is a field "Type" which is now a "Enum" data type 
4. Previously we are inserting data from option and it was working fine. now it showing this warning.

**Screenshot**
![image](https://user-images.githubusercontent.com/63336107/79114640-20c58180-7dc7-11ea-8db5-ad0620a2c4e1.png)

**Versions:**
AL Language 5.0.254558
Business Central : 16.0.11209.0 (Preview)

Can we ask what is the best practice to eliminate the warning? thanks

**Comment by dtkb** [comment]
Simply change your extension's Line Types to be the base Purchase Line Type enum instead of Options...

**Comment by RoieSantos** [comment]
Hi dktb,

Thanks for your reply, This code is already in the production database (Live) we cannot just change, It will be a destructive change if we publish. Please advise if there is any other work around to this .

Thank you.

**Comment by esbenk** [comment]
Changing a field from Option -> Enum is not in itself a breaking change. 

It is however important consider the impact of the underlying change. The PurchaseLineType enum is now extensible. The means that another extension can add more values to the PurchaseLineType and your code should be able to handle the 'unknown' case gracefully.

**Comment by dtkb** [comment]
Is it any better if you instead write `SomeEnum := "Some Enum Type".FromInteger(SomeOption)` ?

**Comment by dtkb** [comment]
> It is however important consider the impact of the underlying change. The PurchaseLineType enum is now extensible. The means that another extension can add more values to the PurchaseLineType and your code should be able to handle the 'unknown' case gracefully.

Always using `case` is a good bet, instead of `if/else` where the `if` means 'the value I am actually checking for' and `else` means 'the other values I currently know about, but if someone adds one later, oops'. :D

**Comment by esbenk** [comment]
That should suppress the warning, but a better way is to avoid the Option in the first place.

'case' can still be problematic. E.g. if the 'else' part contains an ERROR('Bad Option') it could now disable the use of new values. This is no simple answer to this, since it depends very much on the actual code. Making an app extensible is not an easy task and some extensions may actually be mutually exclusive by design. 

Our goal here is to support as much extensibility as possible and reduce the potential pitfalls. Removing the support (for now only a warning) implicit conversions is one of the ways we can raise awareness of this.

**Comment by atoader** [comment]
We have fixed the issue where the compiler was reporting false positives for this warning. For the remaining warnings, you should either switch to using the enums from the Base Application or make the conversion to integer/option explicit.
