### ISSUE TITLE
Shift+Alt+E to lookup/insert event subscriber method contradicts AA0207 by not making it local

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#5802]
[AA0207 states](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0207-eventsubscriberfunctionsmustbelocal) that event subscriber procedures should be local. However, the new shortcut Shift+Alt+E to lookup and insert an event subscriber creates a procedure lacking the `local` keyword. So, the shortcut contradicts the documentation. There's no reason to make anything global by default, so the default should be to insert a local subscribing proc

**Comment by dtkb** [comment]
It would also be nice if the default subscriber method name could be prefixed by the (normalised) name of the object publishing the event. Right now it's just the event name. But some objects will publish the same event, so eventually in a large subscriber codeunit, you will need to differentiate them. Also, that is some shops' naming convention. So, it may make sense to do that by default.

**Comment by qutreson** [comment]
Hi @dtkb, can you log a separate issue with your suggestion about the naming of the event subscriber with some examples?

**Comment by dtkb** [comment]
Sure, thanks!
https://github.com/microsoft/AL/issues/5814

**Comment by atoader** [comment]
This issue should be fixed in the current preview build Please try it out and let us know if you encounter any issues.
