### ISSUE TITLE
AL0601: Table 'Product Group' is removed. Reason: Product Groups became first level children of Item Categories.. Tag: 15.0. This warning will become an error in a future release.

### ISSUE THREAD

**Issue by dyepri** [microsoft/AL#5804]
**Describe the bug**
I have updated my AL Language extension into 5.0.254558 then it is giving me this warning.
May i know how to resolve this warning. Any help would be appreciated. Thank you.

**To Reproduce**
Steps and to reproduce the behavior:
1. Make sure you are using the updated AL Language extension
2. Declare a field having a TableRelated property into the Product Group table.

``` AL Code to reproduce the issue ```

**Expected behavior**
This should not produce any warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/41933086/79295696-a73fa780-7f1c-11ea-9023-f65666ec8b7d.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0.11209.0 (Preview)

**Comment by qutreson** [comment]
Hi @dyepri, it seems that the extension declaring the table "Product Group" has marked its table as obsolete removed. It means that the extension declaring it does not maintain this extension anymore. The AL compiler reports then errors or warnings to warn you about it and let you update your extension.

This means that you should stop using this table. The obsolete reason: 'Product Groups became first level children of Item Categories' gives you an indication on what to do to achieve the same scenario as you used to.
