### ISSUE TITLE
Methods on the Enum data type are missing

### ISSUE THREAD

**Issue by je-258** [microsoft/AL#5805]
**Describe the bug**
The methods Names(), Ordinals() and most importantly FromInteger(Integer) on the Enum data type as described [here ](https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/developer/methods-auto/enum/enum-data-type) are unavailable.

**To Reproduce**
Steps and to reproduce the behavior:
1. Use command "Al:Go!" with target platform "5.0 Business Central 2020 release wave 1"
2. Try to use mentioned methods

**Expected behavior**
Methods should be available.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/63703792/79311534-df83bd80-7efd-11ea-8c7a-5f614d94ba73.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0

**Comment by nicolassaleron** [comment]
Hello, have you tried TestEnum.FromInteger ?
Because these methods are instance methods and not statics.

**Comment by esbenk** [comment]
They are static methods on the specific enum type. E.g.

`TestEnum := "Sales Document Type".FromInteger(1);`

or

`TestEnum := enum::"Sales Document Type".FromInteger(1);`

Same for both Ordinals() and Names().

**Comment by je-258** [comment]
That makes sense, thanks!

**Comment by nicolassaleron** [comment]
The documentation is not clear in that case.

Considering the syntax Enum::"My Enum".Names() to be _the static methods of the data type enum_, we should be able to do Codeunit::"Sales Post".Run() as well.

The documentation should be clarified about that: methods on the data type Enum (or Codeunit) and methods on the strongly type data type Enum::"My Enum" (or Codeunit::"Sales Post".

**Comment by esbenk** [comment]
There is a slight difference. The Codeunit.Run is a static method on the generic Codeunit class and run takes an argument that specifies what codeunit to run.

The static methods on the enum a related to a specific type of the enum. 

We will update the enum documentation to be more clear on this.
