### ISSUE TITLE
A transaction must be started before changes can be made to the database

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#5808]
**Describe the bug**
This is not possible to insert record in a table in 'OnAfterGetPrinterName' event subscriber.
An error "A transaction must be started before changes can be made to the database" occure when trying to insert a record in a new table. Event when CurrentTransactionType = UpdateNoLock.

**To Reproduce**
Goal : Create a tracking table for report frequency usage
Steps and to reproduce the behavior:
1. Create Table

```
table 5200 "Report Tracking"
{
    fields
    {
        field(1; "Report Id"; Integer)
        {
            DataClassification = SystemMetadata;
            Caption = 'Report ID';
            TableRelation = AllObjWithCaption."Object ID" where("Object Type" = Const(Report));
        }
        field(2; "Year"; Integer)
        {
            DataClassification = SystemMetadata;
            Caption = 'Year';
        }
        field(3; "Month"; Integer)
        {
            DataClassification = SystemMetadata;
            Caption = 'Month';
        }
        field(10; "User ID"; Code[80])
        {
            DataClassification = CustomerContent;
            Caption = 'User Id';
        }
        field(20; "Runs"; Integer)
        {
            DataClassification = SystemMetadata;
            Caption = 'Runs';
        }
        field(30; "Report Caption"; Text[30])
        {
            Caption = 'Report Caption';
            FieldClass = FlowField;
            CalcFormula = Lookup (AllObjWithCaption."Object Caption" WHERE("Object Type" = CONST(Report), "Object ID" = FIELD("Report Id")));
            Editable = false;
        }
    }

    keys
    {
        key(PK; "Report Id", Year, Month, "User ID")
        {
            Clustered = true;
        }
    }
}
```

2. Create Codeunit
```
codeunit 5200 "Report Tracking Mgt"
{
    Permissions = tabledata "Report Tracking" = RIMD;

    [EventSubscriber(ObjectType::Codeunit, codeunit::ReportManagement, 'OnAfterGetPrinterName', '', false, false)]
    local procedure RunAfterGetPrinterName(ReportID: Integer; var PrinterName: Text[250]; PrinterSelection: Record "Printer Selection")
    var
        ReportTrack: Record "isaLCM_Report Tracking";
        lYear: integer;
        lMonth: integer;
    begin
       // if IsProcessOnlyReport(ReportID) then
          //  exit;

        if not ReportTrack.WritePermission then
            exit;

        lYear := Date2DMY(Today(), 3);
        lMonth := Date2DMY(Today(), 2);
        ttype := CurrentTransactionType();

        if not ReportTrack.Get(pReportID, lYear, lMonth, UserId()) then begin
            ReportTrack.Init();
            ReportTrack."Report Id" := pReportID;
            ReportTrack.Year := lYear;
            ReportTrack.Month := lMonth;
            ReportTrack."User ID" := CopyStr(UserId(), 1, MaxStrLen(ReportTrack."User ID"));
            ttype := CurrentTransactionType();
            ReportTrack.Insert(true);
        end;

        ReportTrack.Runs += 1;
        ReportTrack.Modify(true);
    end;
}
```

3. Print a report like a posted sales invoice.

**Expected behavior**
We should have a new/modified record when printing without any transaction error message.

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: Version: W1 16.0 (Platform 16.0.11233.12163 + Application 16.0.11240.12188)

**Comment by charlespockert** [comment]
None of the new printing events allow any database modification during printing operations, this is an issue when using a printing service that requires a token that expires. 

In order to submit a refresh token you need to know when the printing service is going to be used, check the token expiry (or attempt to auth and handle the response). If a new token is issue using a refresh token, I'd like to be able to write this back to the database.

Currently this doesn't appear to be possible. I've been thinking I might be able to get around it with a single instance codeunit, but it's a bit of a hack.

Otherwise the alternative is to keep refreshing the token every time I print, which I'm sure will hit rate limits when placed in a multi-user environment.

**Comment by charlespockert** [comment]
@YvesDesrumaux did you manage to work around this?

The way I did is to create a codeunit with an `OnRun` trigger that does the writes and use `StartSession` to run that codeunit, passing in a rec if required.

Seems to work ok for now.

**Comment by YvesDesrumaux** [comment]
@charlespockert, I did the same but that is really a work around.

**Comment by atoader** [comment]
The problem this NoTransaction error was fixed. The codeunit provided in the Github, after the last statement ReportTrack.Modify(true); we should have Commit(); otherwise an error TransactionWorldWithActiveWriteTransaction will be shown.
