### ISSUE TITLE
AL0432: Page 'Sales Prices' is marked for removal. Reason: Replaced by the new implementation (V16) of price calculation.. Tag: 16.0.

### ISSUE THREAD

**Issue by dyepri** [microsoft/AL#5809]
**Describe the bug**
After i update the AL Language extension i and compile the extension against BC16 i got this warnings saying "Page 'Sales Prices' is marked for removal. Reason: Replaced by the new implementation (V16) of price calculation.. Tag: 16.0."

**To Reproduce**
Steps and to reproduce the behavior:
1. Update AL extension into 5.0.254558
2. Compile extension against BC 16.0.11209.0 (Preview)

``` AL Code to reproduce the issue ```

**Expected behavior**
How to address this into the current BC release or AL language.

**Screenshots**
![image](https://user-images.githubusercontent.com/41933086/79402230-9b142280-7fce-11ea-93c1-ae47d7201c5c.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0.11209.0 (Preview)

**Comment by NKarolak** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations

**Comment by dyepri** [comment]
hi @NKarolak, may i know if there is replacement for the page Sales Price? upon reviewing the documentation given by yours i found nothing. Appreciate your help. thanks

**Comment by NKarolak** [comment]
The article says in the first info box ("Note"):

> The new price calculation capabilities in 2020 release wave 1 exist in code only, and do not include any user experience. We will provide that in an upcoming release. For now, to use the new capability you must create your own page.

I guess it means that all warnings regarding the "old" sales price pages, you will need to ignore them. But I'm not an expert on this topic.

**Comment by qutreson** [comment]
Closing this issue as the compiler warning about deprecated objects is as expected. You can follow the documentation mentioned above in order to have more information about why this is deprecated and how to achieve the same scenario. If the documentation appears to be missing some information, you can contribute to the feedback at the bottom of the documentation page.
