### ISSUE TITLE
Possible overflow Assigning USERID in a Code[50] var

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5816]
1. Create a Variable/Field of Code[50].
  UserIDVar : Code[50];
![image](https://user-images.githubusercontent.com/33481576/79605603-d701d180-810d-11ea-84f3-9016281e4d18.png)

2. Assign return value of USERID method in this var.

UserIDVar := USERID;
![image](https://user-images.githubusercontent.com/33481576/79605626-e41ec080-810d-11ea-87ce-e0391797a04b.png)

Expected Behavior!!
   No warning should show since both have same Code[50] Datatype.

Thanks

AL Compiler : 
![image](https://user-images.githubusercontent.com/33481576/79605688-fc8edb00-810d-11ea-83c6-ae6cdffafa64.png)

**Comment by nicolassaleron** [comment]
```JournalLine."PP_User ID"``` is a Code[50] but [UserId](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/database/database-userid-method) returns a Text, not a Code[50], is not it?

**Comment by SUD-D365** [comment]
> ```JournalLine."PP_User ID"``` is a Code[50] but [UserId](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/database/database-userid-method) returns a Text, not a Code[50], is not it?
> 
> 

That seems also incorrect. Because USERID function definition says its returns value of **User Name** field from **_USERS_** table. The length of this field is code[50] there in this table.

**Comment by SirBETE** [comment]
Asked the same question, see #4506
The keyword `UserId()` should just return a Code50, not an unlimited text.

**Comment by atoader** [comment]
+ @MarcHansenMicrosoft

**Comment by AndreyKorepanov** [comment]
Hi @SUD-D365, thank you for reporting the issue. As @SirBETE noticed you can find the related discussion in #4506. Briefly, the value returned by UserId is Text. You should not relay on the Code[50] table field backing the procedure, as there might be changes in the future.
The workaround is to use explicit conversion, for example in your case:
UserIDVar := CopyStr(USERID(), 1, MaxStrLen("UserIDVar");
Thanks!
