### ISSUE TITLE
VS Code throws exception when renaming table already referenced by other objects

### ISSUE THREAD

**Issue by j2associates** [microsoft/AL#5819]
**Describe the bug**
I had a table name with abbreviations and periods (e.g. My Abbrev. Tbl.)  which was referenced in other pages. When I removed the periods from the table name it crashed.

**To Reproduce**
1. Create a table with periods in the name
    a. My table name also included embedded spaces, I don't know if this is significant or not
2. Reference said table in another object such as a page or page extension
3. Go back to the table definition and rename it by removing the periods.
4. The system will generate the error codes as shown in the attachment

I don't know whether the issue is removing the periods or just renaming a table after it is in use

``` AL Code to reproduce the issue ```

**Expected behavior**

The table rename should propagate throughout the project files automatically. 

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

[Visual Studio Code Stack Trace.txt](https://github.com/microsoft/AL/files/4498894/Visual.Studio.Code.Stack.Trace.txt)

**Comment by qutreson** [comment]
Which version of the AL extension are you using?

**Comment by j2associates** [comment]
AL Extension Pack 1.0.7
AL Language 5.0.254558

**Comment by thpeder** [comment]
Hi @j2associates,

I have tried the reproduction steps but it doesn't throw any exception for me.
Could you make a small project where you can reproduce it, zip it up and share it here. That will make it much easier for us to find and fix the issue.

Thanks,
Thomas

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
