### ISSUE TITLE
CodeCop should evaluate static Text to avoid overflow warning.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5820]
**Describe the bug**
The CodeCop Rule [(AL(AA0139))](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0139-donotassigntostringwithsmallercapacity)
should try to evaluate static text values, instead of showing a warning.

**To Reproduce**

For Example: 
```
procedure GetQueueEntryKey(): Code[30]
begin
	exit(UPPERCASE('QueueEntryKey'));
end;
```
results in the following warning:

> Possible overflow assigning 'Text' to 'Code[30]'.

**Expected behavior**
The Code Cop should try to evaluate static text and Labels with `Locked=true` and only show a warning when a resolution isn't possible.
**Screenshots**

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central:

**Comment by MarcHansenMicrosoft** [comment]
Thanks
We will have a look at it.

**Comment by pri-kise** [comment]
I'm really looking forward for this enhancement of the CodeCop :) Is there any ETA of this improvement?

**Comment by MarcHansenMicrosoft** [comment]
This has been fixed 2 month ago, I would expect that it is part of the docker for master.
