### ISSUE TITLE
Report Preview isn't working using Report.Execute method in BC16

### ISSUE THREAD

**Issue by raydilsons** [microsoft/AL#5826]
**Describe the bug**
We have upgraded an existing AL code from BC15 to BC16 (both on prem) and noticed that the behaviour of Report.Execute method has changed. Previously it opened a report in preview mode for the user for further action. Now it automatically downloads a PDF without displaying the preview mode.

**To Reproduce**
Steps and to reproduce the behaviour:
For example, create a new action in Sales Order page that runs a report (via variable) using Execute method. And run the action to see the system behaviour.

``` AL Code to reproduce the issue ```
//Below is an example. Report and record variables should be replaced with different.

                action(JobPrintPreview)
                {
                    ApplicationArea = Basic;
                    Caption = 'Job Print Preview';
                    trigger OnAction()
                    var
                        JobCardRep: Report "My Report";
                        RecRef: RecordRef;
                        ServHeader: Record "Service Header";
                    begin
                        ServHeader.Reset;
                        ServHeader.SetRange("Document Type", "Document Type");
                        ServHeader.SetRange("No.", "No.");
                        RecRef.GetTable(ServHeader);

                        JobCardRep.Execute('', RecRef);
                    end;
                }

**Expected behavior**
After user clicks on the action button, the system should run the report and show the preview window with report layout and data. 
Method description is found here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-execute-method

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: Version: GB Business Central 16.0; (Platform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by gatsby0121** [comment]
Was a case ever opened for this?  How can I see if one has?

**Comment by atoader** [comment]
@raydilsons would know.

**Comment by raydilsons** [comment]
> Was a case ever o

Hello! I did not open a case for this, I’m afraid.

**Comment by faaizahmed1995** [comment]
Dear All i am also facing the same issue.
