### ISSUE TITLE
Cannot declare a dictionary with option type

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/AL#5827]
**Describe the bug**
When trying to declare a dictionary variable, trying to use the option type results in a repeating loop of confusing syntax errors of either 'identifier is expected' or '',' is expected'. It looks like the compiler is accepting the option type, but doesn't know how to handle the option members, or lack there of, maybe the commas between option members is the cause.

**To Reproduce**
Declare a dictionary variable like the following

```
OptionByGuid: Dictionary of [Guid, Option] // Syntax error, identifier is expected (at ']')
OptionByGuid2: Dictionary of [Guid, Option "a","b"] // Syntax error, ',' is expected (at ']')
```

**Expected behavior**
Either the compiler should disallow option types in dictionaries (i.e. 'The type 'Option' cannot be used as a type argument in this context.'), or the option type should be allowed (with or without members, probably without)

**Version**
 - AL Language: 5.0.254558
 - Business Central: AU Business Central 15.3 (Platform 15.0.40073.40791 + Application 15.3.40074.40822)

**Comment by thpeder** [comment]
Hi @shuyusheng,
Have you tried using enums?

**Comment by shuyusheng** [comment]
> 
> 
> Hi @shuyusheng,
> Have you tried using enums?

Yes, dictionaries with enums work fine.

**Comment by atoader** [comment]
Is there any reason to not use enums? Considering the number of requests and our capacity, it might take a long time until we get to look at this issue.

**Comment by shuyusheng** [comment]
> 
> 
> Is there any reason to not use enums? Considering the number of requests and our capacity, it might take a long time until we get to look at this issue.

We have been using enums so no rush
