### ISSUE TITLE
al.enableCodeAnalysis warnings about overflow from text to code

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#583]
I guess, there are actually two different issues here:

1. When I declare a variable with Code[50] and assign UserId to it or having a Code[50] field and assigning UserId, you get a warning about a possible overflow from text to code. Since stock app used Code[50] for user id, I am assuming there is a limit to 50 characters. So, UserId shouldn't return Text, but a Code[50] to be correct - which also would resolve the code analysis warning.

2. If you do the following:

`var
  test : Code[50];
begin
  test := CopyStr(UserId, 1, 50);
end;`

You don't get an overflow warning.

If you do

`var
  test : Code[50];
begin
  test := CopyStr(userId, 1, MaxStrLen(test));
end;`

you do get an overflow warning. This should be addressed eventually in my eyes.

**Comment by DanielGoehler** [comment]
Why does _UserId()_ now returns **Text** instead of **Code[50]**?

![2017-10-05_10-41-52](https://user-images.githubusercontent.com/9556549/31218184-de6768b4-a9b9-11e7-8810-a66224d11e6d.png)

**Comment by bvbeek** [comment]
@DanielGoehler I got the same question ;)

Now we should handle this via the **CopyStr** and without the **MaxStrlen**

**Comment by StanislawStempin** [comment]
The following no longer generate warning:
app."Company Name" := LowerCase(app."Company Name");
        app."Company Name" := UpperCase(app."Company Name");
        app."Company Name" := ConvertStr(app."Company Name", '', '');
