### ISSUE TITLE
An implicit conversion is being performed from a value of type 'Integer' to a value of type 'Enum "Gen. Journal Account Type"'. This conversion can lead to unexpected runtime issues. This warning will become an error in a future release.

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5830]
In BC160 (16.0.0.0):

![image](https://user-images.githubusercontent.com/57717503/80114187-28c9b200-857b-11ea-8102-f302cd60b4be.png)

What are you doing about these Warnings in standard product?  I ask as our product will return this same error everywhere as we've copied & amended your standard code!

For clarity:

The exact error has been copied and is the Subject of this post.  The error relates to the highlighted line but obviously those other two 'AccType' lines will also have this error against them.

**Comment by thpeder** [comment]
Related to #5800

**Comment by charlespockert** [comment]
@eque2al the best option is just to change the type of `AccType` in your code to enum.

The standard product will eventually be updated to use enums in the correct places - there's just a fair bit of code to go through. I'd imagine at that point, MS will make the compiler warnings errors instead.

**Comment by atoader** [comment]
In this case, you should update the code to remove fix the warnings. To enable a smooth transition from C/AL to AL, we have allowed Integers to be converted to Enums implicitly. This is not desirable as it can lead to unexpected runtime issues.

**Comment by eque2al** [comment]
It's not our code that's the issue .. perhaps I gave the wrong example.  A better example of this error is where we need dimensions created in additonal places to standard so have copied your code (as below):

![image](https://user-images.githubusercontent.com/57717503/81189138-28370f80-8fae-11ea-94b3-921bb0c6ade6.png)

As you can see the "Type" field is giving a compile warning and it is these I'd much prefer to solve now during design than as bug fixes later!

**Comment by atoader** [comment]
Screenshot from the latest version of the code
![image](https://user-images.githubusercontent.com/3097909/81214135-ad82ea00-8fd7-11ea-9a2b-5c2f1be57f78.png)

The Base App codebase will be gradually updated to uptake this. You can suppress the warning using a ruleset.

**Comment by eque2al** [comment]
Ah ok .. please can you share the code from 'Type.AsInteger' here?

**Comment by atoader** [comment]
AsInteger is a built-in function on the enum type.

**Comment by FrankAuwers** [comment]
It would be also nice to have a function that can convert to the enum value. If the value is comming from with a http response message as Json, it would be nice if this can be converted to the enum.
Example:
SomeEnum := "Some Enum Type".FromInteger(SomeOption)
or
SomeEnum := "Some Enum Type".FromText(SomeOption)
or
SomeEnum := "Some Enum Type".FromText(SomeOption, IgnoreCaptials)

If this can't be cast, then the code gives an error.

Now we must do it our self for each enum value that is used in http communication and also create extensibility functions for it, if the enum can be extended.

**Comment by atoader** [comment]
Can you file a BC Idea for that feature?

**Comment by FrankAuwers** [comment]
Done

**Comment by epernst** [comment]
Could you also leave a link to this idea?
