### ISSUE TITLE
BC160 - BaseApp EnumCaption translation

### ISSUE THREAD

**Issue by fmoric** [microsoft/AL#5833]
**Describe the bug**
Translating base app in wave 1 with XLIFF file does not update EnumCaption.
The app is showing translation for all objects, but EnumCaption for all columns is shown english.

**To Reproduce**
1. Tanslate base app whit XLIFF
2. EnumCaption is shown in english, i have checked the translations and it is there.

**Expected behavior**
Translated EnumCaption

**Screenshots**
https://user-images.githubusercontent.com/18283753/80181704-a803c800-8605-11ea-84d1-320523135e51.png

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central:
16.0 (platform 16.0.11233.12061 + application 16.0.11240.12076)

**Comment by alimans3** [comment]
I am having the same issue. Any updates?

**Comment by atoader** [comment]
This issue should be fixed in CU3 of the 2020 Wave 1 release.

**Comment by atoader** [comment]
The fix is also available in the daily insider builds from the 16.x branch.
