### ISSUE TITLE
Filter set from code isn't visual for user in pages

### ISSUE THREAD

**Issue by COL-JBB** [microsoft/AL#5836]
Hi,

I'm creating a new page for "VAT Registration Log" table and in my page extension i've added a filter in the OnOpenPage trigger. 
Moving the filter to an EventSubscriber doesn't seem to make a difference.
The filter is applied correctly and the filter icon is shown on the column header, although the filter section doens't show the filter. 
Filter is (Status,'<>%1',"Verified")

Is it at all possible to make it visual in the filter selection?

![image](https://user-images.githubusercontent.com/48907945/70844893-1f4f7100-1e48-11ea-9ad8-374347b7b12a.png)

**Comment by Drakonian** [comment]
Did you check filtergroup for that filter/page?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
