### ISSUE TITLE
Issue in Extending “Sales Line Type” enum in Business Central 16.0

### ISSUE THREAD

**Issue by azharsaeedkhan** [microsoft/AL#5839]
**Describe the bug:**
i am working on Sandbox for BC 16.0 version

![image](https://user-images.githubusercontent.com/26054845/80300099-16d25400-87b3-11ea-844a-4fb2f737fea0.png)

as in BC 16.0 option field is replaced with enum, you can see here

![image](https://user-images.githubusercontent.com/26054845/80299986-49c81800-87b2-11ea-9c2d-f9ae0aa809a6.png)

that i am extending a "Sales Line Type" enum and adding a new value to it. But when i inspect the "Sale Order Subform" page it is showing that the field Type of table "Sales Line" is an option and not an enum

![image](https://user-images.githubusercontent.com/26054845/80300034-a9bebe80-87b2-11ea-9782-06adc1b72b7e.png)

And the value i have added to enum is not displayed. 

i have posted the same issue here, and later i also found the work around which i have posted as an answer, but i think its not the complete solution.
https://forum.mibuso.com/discussion/75202/extending-sales-line-type-enum-in-business-central-16-0/

**To Reproduce**
..

**Expected behavior**
..

**Screenshots**
..

**5. Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/26054845/80300228-42a20980-87b4-11ea-8cf4-73093835c25e.png)

**Comment by atoader** [comment]
The bug has been added to our backlog and it will be picked up as soon as we have capacity. Can you provide a sample project that will help reproduce the issue?
