### ISSUE TITLE
Page.Run / Report.Run

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#584]
In C/AL I can use a RecordRef or Variant of RecordRef to do a Page.Run(id,table) (and report). If I am trying to use a RecordRef now, I am getting a compile error that it cannot convert it into a Record. And if I try to use a variant with a RecordRef in there, I get a runtime error, but not a compile error.

Is this going to be made available?

**Comment by DominikDitoIvosevic** [comment]
I cannot use this in C/AL either. I get an error "Type conversion is not possible because 1 of the operators contains an invalid type. Record := RecordRef

Could you please give us a snippet which is causing problems?

**Comment by pzentner** [comment]
I guess we can close this. I have just tried it in AL again (and it does work in C/AL - at least on 2017 RTM) and it works in AL now as well. So, there might have been an update in the latest September release. The code that wasn't working for me was as follows:

`
  local procedure Test();
  var
    Cust : Record Customer;
    RecRef : RecordRef;
    TestVar : Variant;
  begin
    Cust.FindFirst;
    RecRef.GetTable(Cust);
    TestVar := RecRef;
    Report.Run(104,True,False,TestVar); // this failed (works in C/AL)

    Page.Run(Page::"Customer Card",TestVar); // I believe this failed, but not sure anymore (works in C/AL)
  end;
`

**Comment by DominikDitoIvosevic** [comment]
Ok. If you happen to see some similar issue we can reopen this :)
