### ISSUE TITLE
Business Central 2019 Wave 2 (15.2) upgrade to 2020 Wave 1 failed - Page 1752 was not found

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/AL#5840]
Hi there,

I ran into a problem upgrading a Business Central 2019 Wave 2 database (15.1.37881.38071) to Business Central 2020 Wave 1 database (16.0.11240.12076) - the old and new databases are both the GB version of the application/database.  

I would really appreciate assistance with this issue.

**Describe the bug**
I am following the steps in "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application" and when I run this command below:

_Sync-NAVApp -ServerInstance BC160 -Name "Base Application" -Version '16.0.11240.12076' -Mode ForceSync_

I get this error: 

_Sync-NAVApp : The metadata object Page 1752 was not found.
At line:1 char:1
+ Sync-NAVApp -ServerInstance BC160 -Name "Base Application" -Version ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC160/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.SyncNavApp_

This page is the DataClassificationWizard.Page.al page.

**To Reproduce**
As explained above.

**Screenshots**

![image](https://user-images.githubusercontent.com/44084862/80302973-92310700-87ad-11ea-9d88-e87c023e9e06.png)

This is my Get-NAVAppInfo:

![image](https://user-images.githubusercontent.com/44084862/80303029-04095080-87ae-11ea-9f31-46a09f383a52.png)

**5. Versions:**
 - AL Language:  5.0.254558
 - Business Central: 16.0.11240.12076

**Comment by kalberes** [comment]
Hi,
I wander why do you have the 15.X versions of System App and Base App still installed?
Here it says that all apps should be uninstalled/unpublished first
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16

**Comment by Wiechardt** [comment]
Hi there,

You are 100% correct, I saw that too and thought it was meant to still be there at that stage.

I followed the steps in the help topic you posted and I managed to upgrade the database without a problem.

Thanks so much, you can close this issue as resolved.

Regards,
Wiechardt
