### ISSUE TITLE
Enum translations not visible

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/AL#5842]
**Describe the bug**
I've published & installed the Microsoft_Swedish language (Sweden).app app in a FI (Finnish) database. However, the Swedish captions are not showing up for enum fields in the client. I've looked into the Microsoft_Swedish language (Sweden).app and the translations seems to be there but they aren't visible, only the English caption (or enum values?).

**To Reproduce**
1. Publish & install Microsoft_Swedish language (Sweden).app in a FI (Finnish) database.
2. Run the client and open for example Purchase Invoice and check the (lack of) enum captions in the Type field on the lines.

``` AL Code to reproduce the issue ```

**Expected behavior**
The translated enum captions should be visible in the enum fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/31550641/80401338-dc58dc00-88c4-11ea-9a80-f6a1d3153251.png)

**5. Versions:**
 - AL Language: 
5.0.254558
 - Business Central:
FI Business Central 16.0 (Plattform 16.0.11233.12061 + App 16.0.12076.0)

**Comment by ernestasjuska** [comment]
Same thing with our translation app.

E.g. VAT Calculation Type enum does not show Lithuanian captions.
![image](https://user-images.githubusercontent.com/53167314/82296859-85718e80-99ba-11ea-80d7-982e23daa2d3.png)
Everything else is translated.

Docker container image: mcr.microsoft.com/businesscentral/onprem:2018
Versions:
- AL Language:
  5.0.2718
- Business Central:
  W1 Business Central 16.1 (Plattform 16.0.12630.12758 + App 116.1.12629.12805)
