### ISSUE TITLE
PTE Extension Bookmarks Reports Caption

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/AL#5846]
When Bookmarking a report the Report Name shows up instead of the Report Caption in the Role Center.  

![image](https://user-images.githubusercontent.com/32099690/80551550-a5440280-8978-11ea-8e3b-4515d59cb9bd.png)

**Comment by qutreson** [comment]
This issue has been fixed in master and has been backported to 16.x as well, it should be part of 16.2.
