### ISSUE TITLE
Reminder Line / Issued Reminder Line - Type should be enum

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5847]
In 16.0.0.0 the Type field is still an Option field:

![image](https://user-images.githubusercontent.com/57717503/80577427-c3ecdc80-89fe-11ea-9fbc-17e6bdfb6581.png)

We need this to be an enum .. in both of these tables, it's vital for our solution.  Please can you provide an update/timescale?

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
