### ISSUE TITLE
wrong tooltip for ToolTip property

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#5848]
**Describe the bug**
The mouse-over tooltip in Visual Studio Code for the `ToolTip` property falsely implies it is a boolean that determines whether `ToolTipML` gets used. It is not. `ToolTip` _contains_ the tooltip text and replaces `ToolTipML`. 

**To Reproduce**
Hover over the word `ToolTip` name of said property in an AL Page or PageExtension.

**Expected behavior**
The tooltip for `ToolTip` should state that it _is_ the tooltip... if you see what I mean. `ToolTipML` should not be mentioned, at least not to falsely imply that it is still needed, but rather that it's deprecated and that `ToolTip` replaces it.

If I might also be cheeky here: Can we ever expect tooltips to be specifiable on the Table level? It is really painful and brittle having to copy and paste them to every new page that shows every field.

**Screenshots**
![image](https://user-images.githubusercontent.com/63455896/80615525-b1db6000-8a37-11ea-9e06-89dce4374224.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 14/15/16

**Comment by salgiza** [comment]
Just for reference: #2643

And yes, please. Most translation tools are paid by the number of translation strings, and a huge chunk of all strings in our apps are duplicated tooltips copy-pasted across two or more pages.

**Comment by dnpb** [comment]
It is still an issue in latest, yes.

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.3.570094
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

Please reopen :-)
