### ISSUE TITLE
XmlElement.Create overloads are ambiguous

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5851]
**Describe the bug**
XmlElement.Create has several overloads. Two of them have ambiguous parameters:

Create(String, String)
Usage: `XmlElement :=   XmlElement.Create(LocalName: String, NamespaceUri: String)`

Create(String, Any,...)
Usage: `XmlElement :=   XmlElement.Create(Name: String, Content: Any,...)`

For the second one, Any is specified as 'can be substituted by any other data type'.

However, when you want to create an Element without namespace, but with string content, then you have can't do that with 
`XmlElement.Create('name','content')`

This will produce: `<name xmlns="content" />`

Workaround is to use `XmlElement.Create('name',XmlText.Create('content'))`

**Expected behavior**
Don't see how this could be solved easily. At least make sure the documentation is clear about this. If Any is a string, then it is considered to be a namespace.
Unfortunately, this is not the same as the other overload Create(String, String, Any,...). Then the Any parameter will be content, no matter what type it is.

**Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.12474)

**Comment by atoader** [comment]
You are right, this could have been better designed. e will update the documentation with a note.
