### ISSUE TITLE
VS Code is unable to open Browser / You need an App to open this htps-Link

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5852]
**Describe the bug**
With the Release 5.0 of the VS Code Extension and Development for BC 16 I am unable to launch the webclient from VS Code.

**To Reproduce**
Steps and to reproduce the behavior:
1. Press Strg+F5 or F5 to publisch (+ debug) my app.
2. I receive the following error:
![image](https://user-images.githubusercontent.com/56249171/80943202-f293fa00-8de6-11ea-8370-4b68597fab69.png)
3. If I specify an Default-Browser for AL instead of the system-Default this browser opens with an empty tab.

One setting which worked perfect with the extensions 4.x and BC 15 that might cause this issue:
The webclient is only accesible per https, but I have to publish to http (and have to specify the path to the webclient inside the launch.json with http).

``` AL Code to reproduce the issue ```

**Expected behavior**
Like with version 4.0 and BC 15 the browser should open the link and I should be able to simple debug.

**Screenshots**
--
**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: DE Business Central 16.0 (Plattform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by ajkauffmann** [comment]
You have a typo in the link. It should be https (with 2 t's).

**Comment by pri-kise** [comment]
Well. Maybe I should have schon my launch.json before.
![image](https://user-images.githubusercontent.com/56249171/80972987-1410d800-8e1f-11ea-8fd2-d3cf9054cf30.png)

The problem is, that it does want to open a wrong url.
The package is getting publised succesfully.
![image](https://user-images.githubusercontent.com/56249171/80973272-72d65180-8e1f-11ea-9052-0e20f05f391c.png)

**Comment by dtkb** [comment]
What is your WebClient base path in the service tier config? I would expect that to get used instead of the server in the `launch.json`

**Comment by jrjofre** [comment]
Hi,
I have the same issue testing my first extension with BC 16:
![image](https://user-images.githubusercontent.com/53561034/81067449-f5721600-8ede-11ea-9c3c-1c9db372f6c4.png)
This is my launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Local",
            "server": "http://localhost",
            "serverInstance": "BC160",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
And this is my web client base URL:
![image](https://user-images.githubusercontent.com/53561034/81067569-25211e00-8edf-11ea-80af-7a0be98f51cb.png)

I have changed localhost to my computer name, but doesn't work.
Thanks in advanced!

**Comment by atoader** [comment]
Hi! If you are using SSL for the webclient, can you try enabling SSL for the developer endpoint and restarting the NST? Do you have EdgeBeta, Chrome, or Firefox installed? Does it repro with these browsers?

**Comment by jrjofre** [comment]
Hello,
I am using chrome.
I have finally configured everything correctly:
http://localhost:8080/BC156/ on "Web Client Base URL" in BC service configuration and "server": "http://localhost:8080/" in launch.json
 Thank you!

**Comment by pri-kise** [comment]
I don't know what has changed, but i works now.
