### ISSUE TITLE
Create New Company cancel button is not working

### ISSUE THREAD

**Issue by kristianeWiise** [microsoft/AL#5855]
**Describe the bug**
When Creating a New Company using Companies Page there is a dialog box that has an option to cancel the process. However the Company were still being created

**To Reproduce**
Steps and to reproduce the behavior:
1. Go To Companies
2. Select New --> Create New Company 
3. Fill in the required data then select Finish
4. While processing , Click Cancel in the Dialog box then Select Yes

**Screenshots**

![image](https://user-images.githubusercontent.com/60126907/81034055-349d6880-8ed9-11ea-86fd-7bea60ac0f43.png)

![image](https://user-images.githubusercontent.com/60126907/81034065-3cf5a380-8ed9-11ea-9ac1-686c3a6c4bf1.png)

![image](https://user-images.githubusercontent.com/60126907/81034068-3ff09400-8ed9-11ea-8832-c3af1c3148d5.png)

**Expected behavior**
The process should be cancelled and No Companies should be created

**5. Versions:**

 - Business Central: Version: AU Business Central 16.0 (Platform 16.0.11233.12727 + Application 16.0.11240.11946)

**Comment by dtkb** [comment]
I think it hints at this by saying it will cancel "all currently running processing tasks", which seems just precise enough to indicate that previously completed tasks will not be rolled back.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
