### ISSUE TITLE
[Event Request] Extension deployment on BC online tenant

### ISSUE THREAD

**Issue by pmatsconsulting** [microsoft/AL#5857]
For BC online tenant administration and supervision we should need event on tenant when any kind of new extension is deployed (published/installed) or unpublished/unistalled.

**Comment by atoader** [comment]
Hi! We have it in our backlog to add telemetry to AppInsights for these type of events. We plan to complete the work in the following months. 

For other ideas around administration events, please log them through Collaborate or BCIdeas. I will close this issue as it is outside the scope of this repository.
