### ISSUE TITLE
[Event Request] Codeunit Reporting Triggers, OnDocumentPrintReady(), DocumentStream VAR Parameter

### ISSUE THREAD

**Issue by sirhc101** [microsoft/AL#5858]
Please modify **OnDocumentPrintReady** Publisher in **Reporting Triggers** Codeunit to a **VAR** parameter.
Before:
`procedure OnDocumentPrintReady(ObjectType: Option "Report","Page"; ObjectId: Integer; ObjectPayload: JsonObject; DocumentStream: InStream; var Success: Boolean)`

After:
`procedure OnDocumentPrintReady(ObjectType: Option "Report","Page"; ObjectId: Integer; ObjectPayload: JsonObject; var DocumentStream: InStream; var Success: Boolean)`

We've published an app to apply digital signature, stationery and more to created PDF files from Business Central. This currently only works out-of-the-box with Word Reports (see [#4510](https://github.com/microsoft/ALAppExtensions/issues/4510)) due to the fact that there is no publisher available to catch the PDF document stream.
This could solve the problem, so we would be able to modify the `DocumentStream` and apply the changes.

**Comment by atoader** [comment]
Hi! The OnDocumentPrintReady event is part of the platform. I suggest that you open an issue on Collaborate or use BCIdeas.

**Comment by jensmpmsft** [comment]
We will not be modifying this event signature, as it is meant to pass the final document for printing / archiving etc. Allowing modification of the document in this event would mean that the printed / archived document would not be the final one.
In a future release we are expecting to raise a different event which allows for document modification
