### ISSUE TITLE
ShowFilter does not work 

### ISSUE THREAD

**Issue by miljance** [microsoft/AL#5861]
**Describe the bug**
ShowFilter property does not work as expected in Worksheet pages

**To Reproduce**
Steps and to reproduce the behavior:
1. Set ShowFilter to false for any page i.e. Sales Order List
![image](https://user-images.githubusercontent.com/42636293/81301897-f2f7f380-9079-11ea-954d-073eeac6490e.png)

**Expected behavior**
Filter Pane should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/42636293/81302198-571ab780-907a-11ea-98b4-9258814f12e7.png)

**5. Versions:**
 - AL Language: 5.0.249661
 - Business Central: Version: DE Business Central 16.0 (Platform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
