### ISSUE TITLE
getting this error for one of tenant (W1) for UAE users. This is a production database implemented last year. Other tenant are easily accessible in UAE.

### ISSUE THREAD

**Issue by Ajageavi** [microsoft/AL#5863]
**Describe the bug**

surprisingly getting this error for one of tenant (W1) for UAE users. This is a production database implemented last year. Other tenant are easily accessible in UAE.
Error We don’t support your country or region yet. We’ll add more countries and regions in the near future, so come back again.

**To Reproduce**
Steps and to reproduce the behavior:
Login to http://businesscentral.dynamics.com/ using Admin@clientDomain.onmicrosoft.com

**Expected behavior**
Should login as before, this is production database, even sandbox is also not working. Admin page is working fine

**Screenshots**
![image](https://user-images.githubusercontent.com/43781253/81417284-ff547d00-915b-11ea-9046-a2ca80c726a2.png)

**5. Versions:**

 - Business Central:

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
