### ISSUE TITLE
DateTime functions during BC SaaS web service calls

### ISSUE THREAD

**Issue by TomTaffin** [microsoft/AL#5864]
**Describe the bug**
When executing the functions DT2DATE and DT2TIME in a business logic that is published as a web service in BC SaaS I am unable to get a correct result.  For on premise installations we can change the parameter "Services Default time Zone" to "Server Time Zone" on the service tier, but in a SaaS environment everything is handled as UTC which is not always correct.

**To Reproduce**
We have a DateTime, e.g. 10/05/2020 23:00 (UTC).

When applying the DT2DATE function from a client context in time zone UTC+2, the result would be 11/05.
When doing the same thing in a web service context the result will always be 10/05 since the logic is  always applied on the UTC value.  
I am trying to update production routing lines via the web service so this results in a wrong calculation when taking e.g. shop calendars into account.  I tried a lot of workarounds but none gave me a correct result.  

**Expected behavior**
An option to indicate that a web service call needs to run in a certain timezone.  I also tried SessionSettings.TimeZone([NewTimeZone: String]) but that didn't seem to change any behavior.

Any other workaround I am missing?

**5. Versions:**

 - AL Language: 5.0.270354

 - Business Central: BE Business Central 16.0 (Platform 16.0.11233.12864 + Application 16.0.11240.11946)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atmike** [comment]
@TomTaffin 
have you found a Solution for this Problem? We have the same Problem

**Comment by TomTaffin** [comment]
> @TomTaffin have you found a Solution for this Problem? We have the same Problem

Unfortunately not and I don't think any action was taken in the platform to work around this.  We ended up adding logic to convert datetime to date and time manually taking a specific timezone into account.

**Comment by naradae** [comment]
We also had a discussion about this in Yammer https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2322620781699072

Issue is acknowledged but fixing is not a priority unfortunately

**Comment by DavidM29** [comment]
Hello, where can I check the status of this issue? The Yammer link does not seem to work anymore.

**Comment by NKarolak** [comment]
> Hello, where can I check the status of this issue? The Yammer link does not seem to work anymore.

The Yammer link is still valid. But you need to be a member of the dynamicsnavdev network to see it.

Last answer by Microsoft was in April 2024: 

> Webservices in Business Central use UTC for datetimes. This is also what we have documented here in docs:
> [Managing time zones with web services - Business Central | Microsoft Learn](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/managing-time-zones-with-web-services#time-zone-configuration-online) 
> 
> We are unlikely to invest in supporting offsets at the moment.
