### ISSUE TITLE
TableRelation Field triggers validation on blank new line.

### ISSUE THREAD

**Issue by carlosyuwono** [microsoft/AL#5867]
**Describe the bug**
A new line is created when page is closed. This occurs when an entry is created from a field that has table relation defined.   

This issue can be reproduced in base NAV using sales line and tax area group field. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Open/Create a sales order
2. On a new sales line select any Tax area group.
3. Press down button to trigger the record insertion and close the sales order page.
4. Reopen the order, and you will see a duplicate line was created when page is closed.

``` AL Code to reproduce the issue ```

**Expected behavior**
After inserting a new line a field validation should not be triggered on an empty line.

**5. Versions:**

 - AL Language: 5.0.270354

 - Business Central: CA Business Central 16.0 (Platform 16.0.11233.12968 + Application 16.0.11240.11946)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
