### ISSUE TITLE
Txt2AL Issue: Promoted-related properties are removed incorrectly

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#587]
When converting a page, the txt2al tool seems to comment out Promoted-related properties (PromotedCategory, PromotedIsBig) if Promoted is not true in the original page. However, even when Promoted is true in the original page, the txt2al tool still removes these properties:

        action("General Journal Batches")
        {
          ApplicationArea=Basic,Suite;
          CaptionML=ENU='General Journal Batches';
          Image=CurrencyExchangeRates;
          Promoted=true;
          //The property 'PromotedCategory' can only be set if the property 'Promoted' is set to 'true'
          //PromotedCategory=Category5;
          RunObject=Page "Account Type Gen. Jnl. Batches";
        }

**Comment by atoader** [comment]
Are you on the latest release? I think we had this issue a few months ago and I fixed it. If you are on the latest release, can you provide a sample for reproing this?

**Comment by jcooper01** [comment]
[PAG70001114.TXT](https://github.com/Microsoft/AL/files/1277068/PAG70001114.TXT)
We are on the September Docker image. Please use txt2al on the attached page.

**Comment by atoader** [comment]
It's working just fine for me. Are you sure the txt2al is on the latest version? My guess is that it is not in sync with the September Docker image. 
[PAG70001114.txt](https://github.com/Microsoft/AL/files/1277160/PAG70001114.txt)

**Comment by jcooper01** [comment]
Whoops. You're right. Deploying against the September Docker image but building using the August txt2al on the host. Sorry!
