### ISSUE TITLE
Identify data source (table and field numbers and/or names) in the web source code

### ISSUE THREAD

**Issue by michalcesek** [microsoft/AL#5874]
The current web client has only localized captions in the HTML source - it is complicated or even impossible to determine which table and field the values belong to. Many web tools, browser extensions or additional apps can read the web page content (HTML source) and add great value to the user UX.

We are ISV and have a development in a roadmap of such a browser extension but we need to know the exact data source (table, field) for each value displayed on the page. In addition, this would really help any web developer to understand better the output of the webpage in BC.

Can you please add this information (tag attributes) for us? I am attaching a screenshot of the needed information.

![d365bc_html_data_source](https://user-images.githubusercontent.com/18560177/81695630-2dd79e00-9463-11ea-8711-ee910ae7cdab.png)

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
