### ISSUE TITLE
FlowField CalcFormula filtering with Integer on Option field

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/AL#5876]
**Describe the bug**
When creating a FlowField with a CalcFormula, where an option field is filtered on with an integer field the code can be published just fine. However, this leads to a runtime error when opening a page where the FlowField is displayed.

**To Reproduce**
1. Create FlowField like this:

![image](https://user-images.githubusercontent.com/46815595/81794193-b4938600-950a-11ea-9a98-eaa5f0717131.png)

2. Run the table or include the field in a page and run the page.

**Expected behavior**
Like when using SetRange() to filter an option field with an integer value, an implicit type conversion should happen in this case as well. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46815595/81793865-38993e00-950a-11ea-8a2b-c08d606e564e.png)

**5. Versions:**

 - AL Language: 5.0.271898

 - Business Central: DE Business Central 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.12474)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
