### ISSUE TITLE
Getting error in "AL Table Proxy Generator"

### ISSUE THREAD

**Issue by aluzaja178** [microsoft/AL#5877]
**Describe the bug**

i am running "AL Table Proxy Generator" and getting an error that file cannot be load. Please see the error below 

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'altpgen, Version=5.0.4.8218, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

This is how i am running the tool:

.\altpgen
-project: 'some value'
-packagecachepath: 
-serviceuri: 
-username: 
-password: 
-entities: opportunity
-baseid: 50000
-tabletype: CDS

Please help me out in this regard
![error]

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/22441517/81807298-444f2980-9537-11ea-8f08-28090993aa60.PNG)

**5. Versions:**

 - AL Language:  5.0.271898

 - Business Central:

**Comment by Jupentti1** [comment]
I'm getting the same error. 
MS .net framework strong name utility gives the following result when verifying the strong name signature.

_Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

.\altpgen.exe is a delay-signed or test-signed assembly_

**Comment by aluzaja178** [comment]
@Jupentti1, are you able to resolve this issue ?

**Comment by MarkkuVento** [comment]
Workaround: http://www.nirsoft.net/dot_net_tools/strong_name_remove.html: SNRemove -r  altpgen.exe

**Comment by jwikman** [comment]
@atoader, do you know any better workaround than the suggested SNRemove suggested above?

**Comment by jwikman** [comment]
I ended up disabling Strong name validation for altpgen:
`sn -Vr altpgen,31bf3856ad364e35`

Be sure to use the x64 version of sn.exe, the x86 one was in my default path and it did not work.

You can revert above with 
`sn -Vu altpgen,31bf3856ad364e35`


You can read more about sn.exe and its parameters at [MS Docs](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool#parameters)

**Comment by mesamabbas** [comment]
were you able to resolve this?

**Comment by mesamabbas** [comment]
> I ended up disabling Strong name validation for altpgen:
> `sn -Vr altpgen,31bf3856ad364e35`
> 
> Be sure to use the x64 version of sn.exe, the x86 one was in my default path and it did not work.
> 
> You can revert above with
> `sn -Vu altpgen,31bf3856ad364e35`
> 
> You can read more about sn.exe and its parameters at [MS Docs](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool#parameters)

where are you running sn from?

**Comment by jwikman** [comment]
@mesamabbas, I run sn from "Developer Command Prompt for Visual Studio". Read more at https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs

**Comment by Jupentti1** [comment]
You can use command prompt command **dir /s sn.exe** to find the correct 64-bit sn.exe. I found it in the x86 program files folder _C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\_

**Comment by thloke** [comment]
Closing as this has been fixed.
