### ISSUE TITLE
Unexpected value 'EnumType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5879]
Hi All,

I am publishing an extension which is having many Enum assignment and use of enums.
I was able to compile this extension successfully.
But when i tried to publish this solution i got below error.
![image](https://user-images.githubusercontent.com/33481576/81909234-eaf30300-95e7-11ea-89fe-e370bcdb1820.png)

I am not sure what should i do in order to fix this issue.

Thanks
SUD

**Comment by dtkb** [comment]
What are your local AL and server BC versions?

**Comment by SUD-D365** [comment]
AL version is : 5.0.271898
BC version : 16.0.11233.12061

**Comment by atoader** [comment]
Does the event viewer contain additional information? There should be a stacktrace there that could give us some insight into what is throwing an exception.

**Comment by SUD-D365** [comment]
Yes, see below additional information in Event Log.

**Server instance: BC160
Category: Extensions
ClientSessionId: 596e9504-fcd9-463e-8248-f2f59bd9bda2
ClientActivityId: 8c5a1eb2-2f49-42e9-a998-21c1a63d3643
ServerSessionUniqueId: 3c5080ed-cec2-4852-86ae-e7ce5208d839
ServerActivityId: 7fe2f333-91fc-47d8-9c2b-c2e3c44030b4
EventTime: 05/18/2020 16:09:58
Message One or more errors occurred.
Unexpected value 'EnumType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'
ProcessId: 13972
Tag: 00001YV
ThreadId: 112
CounterInformation: 
CustomParameters: {
}
**

Although issue has been fixed.
Issue was due to placing an enum on page as a page field directly.
But i think we cant use enum like this on page, we should first declare a variable of that enum and then place that varibale on page field.

But the issue is with AL compiler,that it is not showing any useful information regarding the actual error. It was very difficult for me to find out the exact error.

Thanks

**Comment by atoader** [comment]
Thanks!

**Comment by dtkb** [comment]
> Issue was due to placing an enum on page as a page field directly.
> But i think we cant use enum like this on page, we should first declare a variable of that enum and then place that varibale on page field.

How did you 'place it directly'? As written, that sounds like using a table field of enum type as a direct source expression on a page, which should/does work fine. So I presume you were talking about something else.

**Comment by SUD-D365** [comment]
Due to the exact name of a field in table as enum "Sales Document Type". :)
![image](https://user-images.githubusercontent.com/33481576/82579426-6ab23c00-9bab-11ea-9a7a-b60dd4a23ce4.png)

**Comment by SUD-D365** [comment]
When you type manually "Sales Document Type" when defining a field on a page. Then Compiler would not mind, it allows you to write.

**Comment by dtkb** [comment]
Ah right, so specifying a type as a source expression. Of course, that shouldn't ever compile!

**Comment by atoader** [comment]
The issue has been fixed in the master branch and it will be part of the next Docker drop from the master branch.
