### ISSUE TITLE
Txt2AL: SourceTableView property does not properly encapsulate strings in filter

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#588]
A page object with a SourceTableView that includes a filter does not convert correctly.
Example:
  SourceTableView=WHERE(FieldName=FILTER(My Field 1|My Field 2));

I believe that this should be:
  SourceTableView=WHERE(FieldName=FILTER('My Field 1'|'My Field 2'));

**Comment by kalberes** [comment]
The input file to the txt2AL, should be the output of finsql run with the exporttonewsyntax command.
Is it how you got the issue in your example?

**Comment by jcooper01** [comment]
Yes.

**Comment by DominikDitoIvosevic** [comment]
Could you please check once more that you definitely use the exporttonewsyntax command?
The exporter should be quoting with double quotes (not single quotes as you wrote)

**Comment by StanislawStempin** [comment]
I tested it on Page 321 from base application which contains 
`SourceTableView=WHERE(VAT Report Config. Code=FILTER(EC Sales List));`

Running ExportToNewSyntax results in the correctly double quoted identifier
Command:
`.\finsql.exe Command=ExportToNewSyntax, File=exportedObjects.txt, Database="navision_nav", ServerName=., Filter=Type=Page;ID=321`

Result:
`SourceTableView=WHERE("VAT Report Config. Code"=FILTER("EC Sales List"));`

**Comment by jcooper01** [comment]
Sorry for the delay. I have a page that has a SourceTableView of:
WHERE(FieldName=FILTER(Encrypted Account Number|Protected Account Number))

I just tested in build 18825 and this resulted in the following AL:
SourceTableView = WHERE(FieldName=FILTER(Encrypted Account Number|Protected Account Number));

The fields did not get encapsulated in double quotes.
