### ISSUE TITLE
Line breaks in XML document are treated as text

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#5881]
**Describe the bug**
If an XML document is parsed from a text that includes line breaks between the elements, then those line breaks are treated as XML Text.

**To Reproduce**
Steps and to reproduce the behavior:

```     
    local procedure DemoXmlLineBreaks()
    var
        TxtBuilder: TextBuilder;
        XmlDoc: XmlDocument;
        NodeList: XmlNodeList;
        Node: XmlNode;
        RootElement: XmlElement;
    begin
        TxtBuilder.AppendLine('<?xml version=''1.0''?>');
        TxtBuilder.AppendLine('<bookstore>');
        TxtBuilder.AppendLine('  <book>');
        TxtBuilder.AppendLine('    <title>The Autobiography of Benjamin Franklin</title>');
        TxtBuilder.AppendLine('    <author>Benjamin Franklin</author>');
        TxtBuilder.AppendLine('    <price>8.99</price>');
        TxtBuilder.AppendLine('  </book>');
        TxtBuilder.AppendLine('  <book>');
        TxtBuilder.AppendLine('    <title>The Confidence Man</title>');
        TxtBuilder.AppendLine('    <author>Herman Melville</author>');
        TxtBuilder.AppendLine('    <price>11.99</price>');
        TxtBuilder.AppendLine('  </book>');
        TxtBuilder.AppendLine('  <book>');
        TxtBuilder.AppendLine('    <title>The Gorgias</title>');
        TxtBuilder.AppendLine('    <author>Plato</author>');
        TxtBuilder.AppendLine('    <price>9.99</price>');
        TxtBuilder.AppendLine('  </book>');
        TxtBuilder.AppendLine('</bookstore>');
        XmlDocument.ReadFrom(TxtBuilder.ToText(), XmlDoc);

        XmlDoc.GetRoot(RootElement);
        NodeList := RootElement.GetChildNodes();
        foreach Node in NodeList do
            if Node.IsXmlElement then
                Message('Element: "%1"', Node.AsXmlElement().Name)
            else
                if Node.IsXmlText then
                    Message('Text: "%1"', Node.AsXmlText().Value);
    end;
 ```
If AppendLine is replaced with Append, then it works like expected.
It doesn't make any difference if the leading spaces before the tags are removed. They are only for readability, but those spaces are ignored (as expected).

**Expected behavior**
Line breaks between XML elements should be ignored when parsing XML.

**Screenshots**
With the code above, I get these messages (also in this order, it starts with an empty XMLText node):

![image](https://user-images.githubusercontent.com/19155831/82025691-f8fd5e00-9691-11ea-9dd6-021618074a39.png)

![image](https://user-images.githubusercontent.com/19155831/82025735-01ee2f80-9692-11ea-91cf-7bd950d6d709.png)

**5. Versions:**

 - AL Language: 5.0.271898

 - Business Central: Platform 16.0.11233.12436 + Application 16.0.11240.12474

**Comment by atoader** [comment]
Have you tried using https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmlreadoptions/xmlreadoptions-data-type ?

**Comment by ajkauffmann** [comment]
Yes, tested with XMLReadOptions. Makes no difference.

```
ReadOptions.PreserveWhitespace := true;
XmlDocument.ReadFrom(TxtBuilder.ToText(), ReadOptions, XmlDoc);
```

**Comment by atoader** [comment]
Just to be sure, did you test with false as well?

**Comment by atoader** [comment]
Nevermind, I forgot that false is the default.

**Comment by atoader** [comment]
We'll have to dig into this and see what is causing it.
