### ISSUE TITLE
Debugger is slow since .vsix 5.0.270354

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/AL#5882]
**Describe the bug**
I try to debug codeunit 99000854 "Inventory Profile Offsetting", Function "CalculatePlanFromWorksheet" and step over function (F10). Every step takes about 3 seconds.

I tested version 5.0.254558 and the debugger is faster. Even the version 5.0.271898 is slow.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open Base Application.
2. Set a breakpoint in the function "CalculatePlanFromWorksheet". E.g. in the line, where the function "DemandToInvtProfile is called.
3. Press Ctrl+Shift+F5 (Debug without Publishing).
4. Start the planning worksheet and wait until the debugger hits the breakpoint.
5. Try to step through the lines. It takes very long.

See gif attached.

A colleague of mine told me that they even have this problem outside of the Base Application.

**Expected behavior**
Performance like in in vsix 5.0.254558.

**Screenshots**
With version 5.0.254558:
![debugger_faster_old](https://user-images.githubusercontent.com/10879877/82040621-27396880-96a7-11ea-9e6d-28e9c82f5c69.gif)

With latest version (5.0.271898):
![debugger_slow_new](https://user-images.githubusercontent.com/10879877/82040633-2dc7e000-96a7-11ea-889c-90662b4a7b72.gif)

**5. Versions:**
- Vsix
5.0.271898
 - AL Language: 
Version: DE Business Central 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.12474)
- Visual Studio Code
Version: 1.44.2 (system setup)

**Comment by kalberes** [comment]
It looks as a big bug, but I wander why other users do not complain about it?

**Comment by AndreasGloeckner** [comment]
Attached the log file. The file was located at:
C:\Users\<user>\.vscode\extensions\ms-dynamics-smb.al-**5.0.271898**\bin\win32

[DebuggerServices.log](https://github.com/microsoft/AL/files/4675586/DebuggerServices.log)

It seems that the latest version 5.0.277602 improved the time that the debugger needs to jump from line to line (F10). Nevertheless, still needs long to connect to vscode and not as fast as in the version 5.0.254558.

Attached the file for 5.0.277602 as well:
[DebuggerServices.log](https://github.com/microsoft/AL/files/4675628/DebuggerServices.log)

**Comment by kalberes** [comment]
Thanks for the log. That explains it. It is a bug.

**Comment by kalberes** [comment]
@AndreasGloeckner 
We have pushed a new vsix version where hopefully debugger stack trace handling - the issue seen from your log file -  should be improved.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
