### ISSUE TITLE
Documentation for Text instance methods says no instance ("data type") is needed...

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#5883]
TSIA really. Many documentation pages for instance methods, such as [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-substring-method), wrongly state that no instance or "type name" (I guess copy-pasto'd from the static methods) is needed.

![image](https://user-images.githubusercontent.com/63455896/82031319-9e640200-9691-11ea-8fe1-48a32299132e.png)

We need to type `SomeTextVar.Substring()`. The method is not available statically (not even as an overload taking an instance as the first argument).

The purple Note should be removed from the documentation pages for all such instance methods.

I don't know how many other built-in methods this might affect but would suggest checking.

**Comment by dtkb** [comment]
While here, it would probably be nicer to write something like `SomeTextVar.Method()` instead of using `Text` literally, since we presumably shouldn't be calling instances the same names as their types (and should be quoting them when events force us to! ;-) )

**Comment by dnpb** [comment]
This is still an issue, albeit in the documentation. Please can you move to https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues ? Or do I need to open a new issue there?
