### ISSUE TITLE
ApplicationArea warning AA0201 is spuriously reported multiple times per affected field/control

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#5884]
e.g. these 2 Report requestpage controls should be `Basic, Suite` or `All`, and I only want to be warned about each once, but instead I get each warning copied respectively 64 and 36 times!

![image](https://user-images.githubusercontent.com/63455896/82044147-b3965c00-96a4-11ea-908b-1654cafb78fb.png)

It seems the number gets limited to 100, e.g. this PageExtension triggers 100 warnings for the one field:

![image](https://user-images.githubusercontent.com/63455896/82044381-2b648680-96a5-11ea-9f1d-696c9cf1d654.png)

AL version: 5.0.271898

**Comment by PaulIvan** [comment]
I am closing this issue because it appears that it has been resolved, check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.
