### ISSUE TITLE
Add a KeyValuePair to do foreach loop with dictionaries 

### ISSUE THREAD

**Issue by Entreri86** [microsoft/AL#5885]
Hi! 
I would like you to add the possibility of iterating through a dictionary like in C #. Currently we do not have a way to copy the values ​​from 1 dictionary to another. 

For example, on 1 page or report, a user performs X action and you insert the values ​​1 to 1 in the dictionary. But since you do not know (or you should not know why) all the keys that this dictionary houses cannot be used as a temporary or virtual table with guarantees to optimize old routines.

With a KeyValuePair we could do something similar to this

`foreach(KeyValuePair<string, string> entry in myDictionary)
{
    // do something with entry.Value or entry.Key or just copy from 1 dictionary to another
}`

Thank you very much in advance!

**Comment by charlespockert** [comment]
You can always `foreach` over `Dictionary.Keys` and just retrieve the value via the key.

```
    local procedure Something()
    var
        Dict: Dictionary of [Text, Integer];
        KeyText:Text;
        IntValue:Integer;
    begin
        foreach KeyText in Dict.Keys do begin
            IntValue := Dict.Get(KeyText);
        end;
    end;
```

Admittedly it is an extra line of code unless you just use `Dict.Get(KeyText)` in the place of the value.

I suppose if we have support for generic `Dict<K,V>`, it's not a big ask to also have `KeyValuePair<K,V>`

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by annando** [comment]
You can vote here: https://experience.dynamics.com/ideas/idea/?ideaid=6ac0f833-d033-ea11-8454-0003ff68a104

**Comment by Entreri86** [comment]
@annando already voted, thanks!
