### ISSUE TITLE
AA087 Single line variable declaration warning

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#5886]
**Describe the bug**
Single line variable declaration bug (warning in app.json file)
![image](https://user-images.githubusercontent.com/37966300/82048449-feb86b00-96b4-11ea-8ff5-55ea330a7e4d.png)

**5. Versions:**

 - AL Language: 5.0.271898

 - Business Central: (platforma 16.0.11233.12061 + 16.0.12076.0 aplikace)

**Comment by dtkb** [comment]
See also https://github.com/microsoft/AL/issues/5835#issuecomment-620539842

**Comment by qutreson** [comment]
This issue has been fixed in our master branch and the fix will be available soon in our developer previews
