### ISSUE TITLE
Cannot convert RecordID to DotNet "System.Object" when using RecordID in dotNet functions with System.Object

### ISSUE THREAD

**Issue by hbaehren** [microsoft/AL#5887]
**Describe the bug**
It is not possible to use RecordID variables in DotNet functions with parameter of type System.Object.
It works with primitive types, e.g Text. It also worked in C/AL. 

**To Reproduce**
1. Declare a DotNet variable with a function with parameters of type System.Object, e.g. Dictionary_Of_T_U.Add
2. Call the function with a RecordID variable. 

``` pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
    MyRecordID: RecordId;
    MyDictionary: DotNet Dictionary_Of_T_U;
    MyText: text;
    begin
        MyDictionary.Add(123,MyRecordID);
        MyDictionary.add(123,MyText);
    end;
} 
```

**Expected behavior**
It should be possible to use RecordID variables in functions with parameters of type System.Object.

**Screenshots**
![image](https://user-images.githubusercontent.com/22095707/82052710-645c2580-96bc-11ea-9d02-e3e50842be80.png)

**5. Versions:**
 AL Language - 5.0.271898

**Comment by atoader** [comment]
Thanks for the clear repro!
