### ISSUE TITLE
Download symbols: The SSL connection could not be established, see inner exception.The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by mrabus** [microsoft/AL#5888]
**Describe the bug**
I have a BC16 RTM system setup on a Azure VM. There, I have enabled SSL using a LetsEncrypt Certificate. SSL is enabled for the development endpoint. 

**To Reproduce**
I created a new project in VS Code and tried to download the symbols. Then I get the error: "The SSL connection could not be established, see inner exception.The remote certificate is invalid according to the validation procedure"

There are no further exceptions, neither in my local event log nor on the server's event log. 

**Expected behavior**
I would expect the system to display a more helpful or guiding error message. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2485163/82053707-0e887d00-96be-11ea-8939-104b0ab7eec4.png)

 - AL Language: 
5.0.271898
 - Business Central: Version: DE Business Central 16.0 (Plattform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by atoader** [comment]
The exception you see is the one thrown by the low-level code that tries to connect to the endpoint. Was the problem different than what the error message said?

**Comment by MuriungiMartin** [comment]
The SSL connection could not be established, see inner exception.
Cannot determine the frame size or a corrupted frame was received.


I receiving the same error on prem
