### ISSUE TITLE
Feature Request: XSL Transformations

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#589]
We would like to be able to transform one XmlDocument into another XmlDocument using a supplied XSL XmlDocument within the AL language. We currently do this using DotNet.

**Comment by atoader** [comment]
I am just guessing, so please correct me if I am wrong, that this transformation is not central to the business logic, but it is an adaptation to the requirements of an external service. 
I would wrap this external service and other similar ones in a well tested Azure function or .NET Web API and only keep the logic for interacting with it in AL (constructing the request and using the response)
At the moment, we do not have any plans for supporting XSLT in AL, so the approach I suggested above would be a faster way to get your services up and running.

**Comment by pzentner** [comment]
would it make sense to add this to the cal open library as a function provided in the base app using .net? I would prefer keeping as much as possible within the base app and not having to introduce another potential point of failure (external call to azure function)

**Comment by atoader** [comment]
I think it is a good candidate. Maybe the best way forward would be to open an issue there and discuss it with the community.

**Comment by jcooper01** [comment]
Submitted to the C/AL Open Library.
