### ISSUE TITLE
VS Performance issue. 

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5890]
Hi MS,

I am really experiencing a very bad performance in VS code.
I am not sure that its happened due to Windows Update, VS Code update or due to AL language extension.
Its taking 15-30 mins for saving a single line change in a AL file. Intellisense also not working as usual.
![image](https://user-images.githubusercontent.com/33481576/82178885-b9857a80-98fa-11ea-88e8-230d890dbcbe.png)

I have tried both VS Code insiders and VS code.
VS Code Insider version : 
![image](https://user-images.githubusercontent.com/33481576/82179118-2dc01e00-98fb-11ea-8446-2a8d0e41b330.png)

VS Code version:
Version 1.46

AL Language Version:
![image](https://user-images.githubusercontent.com/33481576/82179094-21d45c00-98fb-11ea-8d4f-164d0ec7b1b1.png)

Any help?

Thanks
SUD

**Comment by SUD-D365** [comment]
@thpeder Can you please help me in to this?

**Comment by ShadowXVII** [comment]
How big is your AL Project? Perhaps a copy of your project (or at least File Count) might help provide context.

**Comment by SUD-D365** [comment]
661 counts of AL objects along with 11k warning :).

Some inputs from another developers who faced the same error that we cant use **al.BackgroundCodeAnalysis** in such heavy solution. But what if we need to use that setting in our solution.

Thanks

**Comment by atoader** [comment]
Hi! Have you followed the steps described here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-optimize-visual-studio-code ?

Please take a moment to read the change log as it contains some additional information on settings that you can use to tweak the behavior.

My recommendation is to only use CodeCop/UICop from the commandline and in your CI/CD pipeline.

**Comment by atoader** [comment]
You should also disable format on save as that is a known issue at the moment.

**Comment by SUD-D365** [comment]
Thanks @atoader  for your reply!!

But after disabling **al.BackgroundCodeAnalysis** VS performance is now much better.
But what if i need to use this setting.
Yes, i disabled **Format on Save** in AL extension but that did not work.

**Comment by atoader** [comment]
More features will demand more hardware resources. I guess the only solution if you really need to use it is to buy more powerful hardware.

**Comment by yrest** [comment]
@atoader what kind of hardware do you use internally?

**Comment by atoader** [comment]
We stick to the recommended specs https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#al-development-requirements . That being said, even with 32GBs of RAM, we do not use CodeCop in interactive mode.

**Comment by rznd** [comment]
I have the same issue on a project with 734 files and 150 warnings.

Disabling Format On Save does not work.

**Comment by AndreyKorepanov** [comment]
It seems there is nothing to fix in AL, looks mostly like request for improvements. So I am going to label it as an enhancement.

**Comment by MortenBLarsen** [comment]
I had the same issue, and had success with switching to use the .NET Framework runtime. Seems that the new .NET Core runtime is reducing performance even though it is supposed to be faster.
![image](https://user-images.githubusercontent.com/67372109/85549112-ef1b3300-b61f-11ea-8500-0df6e9602abe.png)

**Comment by rit-arh** [comment]
In a 1000+ AL project the performance is just abysmal even when using these workarounds that ultimately also reduce our productivity.

I only have the AL Language extension utilizing CodeCop, UICop and prtenantextcop.
My setup is i9 12900K, 32GB Ram, SSD.
It should be more than sufficient. It is impossible to work under these performance limitations.

**Comment by EmilDamsbo** [comment]
From version 11.0 of the AL Language extension, you can refine the use of the setting 'al.backgroundCodeAnalysis' to provide you with diagnostics for your current file, which should drastically improve load times and responsiveness. You can read more at https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-extension-configuration#settings
