### ISSUE TITLE
Obsolete code in Activities page(s) for Role Centers

### ISSUE THREAD

**Issue by MaartenGerritsen** [microsoft/AL#5891]
**Describe the bug**
Not a but, but obsolete code in Activities page(s) for Role Centers.
Actions on Cuegroups were used in the windows client, but not in the web client anymore. The actions are ignored and not shown. See second screenshot.

**To Reproduce**
In VSCode open the SOProcessorActivities.Page.al.

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25688441/82184058-4f170f00-98e7-11ea-993b-47d0b367deee.png)
![image](https://user-images.githubusercontent.com/25688441/82184455-f72cd800-98e7-11ea-8bb1-85df318e5b22.png)

**5. Versions:**

 - AL Language: ﻿# Business Central 2020 release wave 1 update (CURRENT - 2020/3)

 - Business Central: NL Business Central 16.0 (Platform 16.0.11233.13086 + Application 16.0.11240.11946)

**Comment by qutreson** [comment]
The web client does not display actions defined in cue groups which also have some fields. This is a known issue and the [UICop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop) also has some validation for it. See [AW0002](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0002-cuegroupscannotcontainbothactionsandfields). For now, you have to define cue groups with only actions or only fields.

**Comment by MaartenGerritsen** [comment]
> The web client does not support displaying actions defined in cue groups which also have some fields. This is a known issue and the [UICop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop) also has some validation for it. See [AW0002](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0002-cuegroupscannotcontainbothactionsandfields). For now, you have to define cue groups with only actions or only fields.

Yes, I understand. The code in the screenshot is from the Base Application. So, I reckon it can be removed there from BC15 upwards.

**Comment by dtkb** [comment]
It'd probably be better to move the actions to a new cue group so that they'll still be available for users.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
