### ISSUE TITLE
BUG: Purchase Order Error after posting (reproduced in standard product - Cronus Demo db V16)

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5894]
VS Code AL Version: 5.0.271898
BC Version 16.0.11240.12076

To reproduce:
- Create a PO with 3 lines: Line 1 = Item with Qty = 10 and a Direct Unit Cost, Line 2 = G/L Account with Qty = 10 and a Direct Unit Cost, Line 3 = Comment
- Drill-down on "No." on Line 3 and select a text code eg, SC for Shipping Charge
- Enter a partial 'Qty. to Receive' of 1 on Lines 1 and 2
- Select Post, Receive (only), Ok
- Click the back arrow at the top of the document to close it (to left of text 'PURCHASE ORDER')

Result - ERROR because the 1st line "No." has been overwritted with 'SC'.!!

Zipped video recording attached so you can see exactly what's happening.  It's definitely a bug in the standard product as we can reproduce it again & again without any of our extensions in play.

Can we have an urgent fix please?

[Error after PO posting - for MS.zip](https://github.com/microsoft/AL/files/4645054/Error.after.PO.posting.-.for.MS.zip)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by eque2al** [comment]
I urgently need help with this .. I'm told by our Director that it costs us £200 + VAT to log each support call and there is no way we will pay for a fault in your software (remember we have proven this in a vanilla database as evidenced in the video I attached).  I've also been told that we don't have an Account Manager despite being a reseller with hundreds of Customers. 

I find this completely unacceptable / unworkable .. **please** can you tell me what to do in these circumstances!?

**Comment by atoader** [comment]
I understand the issue that you are facing, but the team in charge of this repository cannot help with the issue above. We can only handle issues related to the developer tools, and even then, only after taking into account competing priorities.

You can post this issue on https://github.com/microsoft/ALAppExtensions , they might be able to provide better guidance.
