### ISSUE TITLE
Editable property with dynamic date expression gives run-time error

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#5895]
**Describe the bug**
When date comparison is used as dynamic expression on a Editable property a run-time error occurs.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a page
2. Add a field with an Editable property based on an expression comparing another date field to 0D
3. Compile and run

```c
page 50100 "Editable Bug Repro"
{
    PageType = List;
    SourceTable = "Sales Line";

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field("Planned Shipment Date"; "Planned Shipment Date")
                {
                    ApplicationArea = All;
                }
                field("Planned Delivery Date"; "Planned Delivery Date")
                {
                    ApplicationArea = All;
                    Editable = "Planned Shipment Date" = 0D; // This will cause a run-time error
                }                                 
            }
        }
    }
}
 ```

**Expected behavior**
Simple boolean expressions can be used for the Editable property.

**Screenshots**
The run-time error when opening the page:
![image](https://user-images.githubusercontent.com/8398485/82294059-cf07ac80-99ad-11ea-95ab-20d6353f9301.png)

**5. Versions:**

 - AL Language: 5.271898

 - Business Central: DK Business Central 16.0 (Platform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by AskeHolst** [comment]
@atoader Why would this not qualify as bug for this repository? Is it due to it generating a runtime error and not a compile time error?
Just trying to understand what goes where.

**Comment by NKarolak** [comment]
@AskeHolst As I understand it, this repo handles issues of the AL Language extension only, hence issues that may happen until the application is built. This does not cover run-time errors of the application that you _have_ created.

**Comment by AskeHolst** [comment]
@NKarolak Thank you, that makes some sense.

**Comment by atoader** [comment]
Thank you, Natalie! You are correct. We are trying to keep the scope of the repository focused so that we can offer value in our area of expertise. 
Unfortunately, 50-80% of the issues that hit the repository each day are not related to the tools, and to try to focus on the 20%, we try to close them with the standard reply and guidance on where to post them.
