### ISSUE TITLE
AA0217 warning

### ISSUE THREAD

**Issue by MaartenGerritsen** [microsoft/AL#5896]
**Describe the bug**
With the following code in the screenshot I get a warning message. But what is wrong with this code?

**To Reproduce**
Steps and to reproduce the behavior:
See code in sreenshot
``` AL Code to reproduce the issue ```

**Expected behavior**
No warning

**Screenshots**

![image](https://user-images.githubusercontent.com/25688441/82332529-ce8b0800-99e5-11ea-9399-94c2b4fa290b.png)

**5. Versions:**

 - AL Language: 5.0.271898

 - Business Central: na

**Comment by dtkb** [comment]
I would ask: What is wrong with the message? `LineTextArray` clearly is neither a text constant nor a label, and MS want us to only use those for substitutable/translatable strings. We could disagree with that, but as written, the diagnostic seems to be correctly diagnosing.

**Comment by MaartenGerritsen** [comment]
> Well `LineTextArray` clearly is neither a text constant nor a label, and MS seem to want only those for substitutable/translatable strings. We could disagree, but as written, the diagnostic seems to 'work'.
> 
> I have had cases where user-provided strings were to be substituted into, which would then fall foul of this rule - and I think MS themselves have used this, in something like the Deferral Line Templates. So I doubt it's a universal bad thing. I also wonder whether enough folk get it _wrong_ for it to help...

The base application uses similar code for Reminder Text. See screenshot.
So, I would say, either remove the warning, or Microsoft changes the code in the base app so this also complies with the rules.

![image](https://user-images.githubusercontent.com/25688441/82433769-37c85500-9a92-11ea-81d4-d13b95e294ee.png)

**Comment by mjmatthiesen** [comment]
I agree. There are **many use cases** in which you may have a text variable that needs text replaced - typically coming from user input. If it was straight text rather than a variable, I'd agree.

**Comment by MarcHansenMicrosoft** [comment]
This has been fixed in master
