### ISSUE TITLE
Business Central API v1.0 PATCH picture BadRequest_InvalidToken

### ISSUE THREAD

**Issue by louagej** [microsoft/AL#5897]
**Describe the bug**
According the Microsoft Docs, we should be able to update an item picture trough the default API: [Update picture](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_picture_update)

Unfortunately an error is thrown

`Could not validate the client concurrency token required by the service. Please provide a valid token in the client request.  CorrelationId:  8dbb4ed0-73d4-45c6-b5b1-efa0e9512563.`

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a API GET Request on the photographed Item: `GET businesscentralPrefix/companies({id})/items({id})`
![2020_05_19_004](https://user-images.githubusercontent.com/7229592/82334930-edd76480-99e8-11ea-8743-f7f17597f0ad.png)

2. Use ID to retrieve picture url: `GET businesscentralPrefix/companies({companyId})/items({itemId})/picture`
![image](https://user-images.githubusercontent.com/7229592/82335067-17908b80-99e9-11ea-9ff4-4400b0af2fb4.png)

3. Use content@odata.mediaEditLink to update or create a picture for this item: `PATCH businesscentralPrefix/companies({companyId})/items({itemId})/picture({pictureId})/content`

4. Error in response : `Could not validate the client concurrency token required by the service. Please provide a valid token in the client request.  CorrelationId:  8dbb4ed0-73d4-45c6-b5b1-efa0e9512563.`
![image](https://user-images.githubusercontent.com/7229592/82335311-70602400-99e9-11ea-8ba0-dd8d7a056db8.png)

**Expected behavior**
An update or creation of an item picture.

**5. Versions:**

 - API Version: v1.0 
 - Business Central: 14.0.36457

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
