### ISSUE TITLE
Add syntax highlighting for .al files to DevOps

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/AL#5899]
I've raised a feature request for DevOps *.al syntax highlighting.

Cross posting here:
https://developercommunity.visualstudio.com/idea/1039733/syntax-highlighting-for-al-files.html

**Comment by atoader** [comment]
Hi! For consistency, would you mind posting this on BC Ideas? We would also like to do this, but having the votes on BC Ideas will help us prioritize it against other suggestions from the community.

**Comment by ShadowXVII** [comment]
Seems to be listed here https://experience.dynamics.com/ideas/idea/?ideaid=2187bedd-002b-ea11-8454-0003ff68d144

I'll post a link to the DevOps side there.
