### ISSUE TITLE
Syntax Documentation

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#59]
IntelliSense is not helping much in the Syntax.

Besides the samples on "C:\DEMO\New Developer Experience\AL" (which are not complete), is there any way to get to the syntax decently in VSCode?  Or hasn't this been implemented just yet?

**Comment by StanislawStempin** [comment]
For the January Update we are adding Table and Page structure syntax IntelliSense (i.e. layout, area, group, field, keys etc.). For the February Update we are planning to add keyword IntelliSense for the remaining objects.

**Comment by waldo1001** [comment]
Clear! thanks!
