### ISSUE TITLE
FreezeColumn on repeater not working for Pages and Page Extensions

### ISSUE THREAD

**Issue by hemmsi** [microsoft/AL#5900]
Hello.

I wanted to freeze 3 columns to the left side of a list, I did so by adding the FreezeColumn property under the repeater element like so:
```
[...]
repeater(Items)
{
    FreezeColumn = "Description 2";
    field("No."; "No.")
    {
        ApplicationArea = All;
    }
    field("Description"; "Description")
    {
        ApplicationArea = All;
    }
    field("Description 2"; "Description 2")
    {
        ApplicationArea = All;
    }
[...]
```
But this has no effect and none of the columns are frozen. I am using the OnPrem version of Business Central 16.0.

### Steps to reproduce
1. Create the following extension (either in code or using the _Design_ functionality from within Business Central):
```
pageextension 50000 PageExtension50000 extends "Customer List"
{
    layout
    {
        modify(Control1)
        {
            FreezeColumn = Name;
        }
    }
}
```
2. Open up the Companies page
3. Shrink the browser window untill the scrollbar at the bottom appears.
4. Scroll to the right.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
