### ISSUE TITLE
CurrPage.Editable in pageextension

### ISSUE THREAD

**Issue by radovandokic** [microsoft/AL#5901]
Hello,

In version 16 there is a new feature - when we click on an Item code in e.g. non-editable page, like Posted Purchase Invoice, in a drop-down window we can click on Open (this is new action) and open item card. 

![image](https://user-images.githubusercontent.com/34686682/82424348-5542f200-9a85-11ea-980a-75ead0cb28e2.png)

This Open action ignores CurrPage.Editable(false) which we added in a page extension.

Is this a bug?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
