### ISSUE TITLE
Possible overflow assigning 'Text' to 'Text[50]'. Wrong CodeCop Warning

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5902]
**Describe the bug**
It is not really a bug, but a bad behaviour.
Assigning a variable the same variable with coypstr results in a warning.
**To Reproduce**
Steps and to reproduce the behavior:
See the following code

``` 

local procedure ConvertPkgNumber(Number: Text[50]): Text[50]
    begin
        PkgNumber := COPYSTR(Number, STRPOS(Number, '/') + 1);
    end;
```

**Expected behavior**
When the base String inside the CopyStr or other Other String operations is the same as the Text or Code Variable that I'm trying to assign a value then there shouldn't be such  a warning.

**Screenshots**
---

**5. Versions:**

 - AL Language: Name: Version: 5.0.271898

 - Business Central:

**Comment by atoader** [comment]
Hi! Can you please share the warning that the compiler emits?

**Comment by dtkb** [comment]
Looks like it's in the title. Indeed this seems superfluous since `CopyStr()` without a length argument means 'until the end of the string'. These "possible overflow" diagnostics could be a lot smarter about being context-sensitive, but then that could be tricky to implement.

**Comment by pri-kise** [comment]
@atoader Yes it's in the title:

> Possible overflow assigning 'Text' to 'Text[50]'.

This warning is logic since the copystr function without a lenght arguments returns an unbounded string, but in my opinion this string can only have the maximum length of the input string.

**Comment by mjmatthiesen** [comment]
> Looks like it's in the title. Indeed this seems superfluous since `CopyStr()` without a length argument means 'until the end of the string'. These "possible overflow" diagnostics could be a lot smarter about being context-sensitive, but then that could be tricky to implement.

It also doesn't do any maths. If the max is 50 and the copystr is 20 to 60, you'll still get the message, even though the stirng is guaranteed to be shorter.

I cannot stree enough that we need a way to suppress specific warnings in code sections! **This is vital**. I have 91 warnings that have zero resolution and will never ever have one.

**Comment by pri-kise** [comment]
I created another example related ot this CodeCop:
The following should raise a warning, since MaxStrLen minus a value is still short enough.
```
Customer."Name 2" := CopyStr(Customer."Name", 1, MaxStrLen(Customer."Name 2") - 1);
```
Warning: 

> Possible overflow assigning 'Text' to 'Text[50]'.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
