### ISSUE TITLE
Whse.-Shipment Release - Reopen 

### ISSUE THREAD

**Issue by selvajo1990** [microsoft/AL#5906]
In the latest version v16.1 - Microsoft_Base Application_16.1.12629.13149

Codeunit "Whse.-Shipment Release" - Reopen function is missing the call by reference. after the function call the value remains unchanged.

`procedure Reopen(WhseShptHeader: Record "Warehouse Shipment Header")`  - missing call by reference

![image](https://user-images.githubusercontent.com/48993374/82601907-e2915e00-9bcd-11ea-910c-d075f3b24532.png)

**Comment by dtkb** [comment]
Does it really need to be by reference? The caller can `Find()` the record afterwards. Changing this now would break API/ABI I think.

Do other Release codeunits take by `var` in their `Reopen()`s? Does this codeunit in its other methods?

**Comment by selvajo1990** [comment]
codeunit 414 "Release Sales Document" - `procedure Reopen(var SalesHeader: Record "Sales Header")`

after the `reopen` function call, again it has to be fetched from DB to get the latest. so it is better to have reference.

![image](https://user-images.githubusercontent.com/48993374/82651196-75b3ad80-9c39-11ea-8d9c-e64d33da9496.png)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
