### ISSUE TITLE
Change/remove TableRelation in standard

### ISSUE THREAD

**Issue by adinfo-theo** [microsoft/AL#5907]
Hi, is there a way to change/remove the standard TableRelation??
For example, I don't want the TableRelation in "Sales line".Description

**Comment by atoader** [comment]
Hi! There is no way to remove it and we do not have any plans to support this feature. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
