### ISSUE TITLE
OnBeforeActionEvent subscriber is not executed when page action does not contain any logic on OnAction trigger

### ISSUE THREAD

**Issue by sidser** [microsoft/AL#5908]
**Describe the bug**
If some page action does not contain any logic on OnAction trigger then OnBeforeActionEvent is not triggered and corresponding subscribers are not executed.

**To Reproduce**
Steps and to reproduce the behavior:
1.``` AL Code to reproduce the issue ```
a) Create event subscriber and subscribe to OnBeforeActionEvent of the page action that has some logic on OnAction trigger. Put some logic in the created event subscriber.

For example, I created two OnBeforeActionEvent subscribers
 - OnBeforeActionNewSalesInvoice subscribes to NewSalesInvoice action on the Customer Card page. This action does not have OnAction trigger but has RunObject property
-OnBeforeActionContact subscribes to Contact action on the Customer Card page. This action has OnAction trigger.

codeunit 50000 "Test Subscriber"
{
    [EventSubscriber(ObjectType::Page, Page::"Customer Card", 'OnBeforeActionEvent', 'NewSalesInvoice', true, true)]
    local procedure OnBeforeActionNewSalesInvoice()
    var
        ConfirmQst: Label 'Are you sure you want to execute this action?';
    begin
        // Some code, for example
        If Confirm(ConfirmQst) then;  // This code is not executed. NewSalesInvoice action does not have OnAction trigger but has RunObject = Page "Sales Invoice"
    end;

    [EventSubscriber(ObjectType::Page, Page::"Customer Card", 'OnBeforeActionEvent', 'Contact', true, true)]
    local procedure OnBeforeActionContact()
    var
        ConfirmQst: Label 'Are you sure you want to execute this action?';
    begin
        // Some code, for example
        If Confirm(ConfirmQst) then;  // This code is executed. Contact action has OnAction trigger.
    end;
}
b) Publish and Install your changes to Business Central
c) Open "Customer Card" for any customer and 
 - click on "Sales Invoice" action -> event subscriber logic is NOT executed
 - click on "Contact" action   -> event subscriber logic is executed

**Expected behavior**
OnBeforeAction event has to be triggered for page actions that do not have OnAction trigger and corresponding subscribers have to be executed.

**Screenshots**

**5. Versions:**
 - AL Language: 5.0.271898
 - Business Central: W1 16.0 (platform 16.0.11233.12061 + Application 16.0.11240.12076)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by miljance** [comment]
I just hit the same limitation. I will file a bug on collaborate.
