### ISSUE TITLE
W1 in August Update

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#591]
Hi,

in august update i have given the server instance as NAV in launch.json and application localae as W1 in app.json but i cannot download the symbols and it is not working and i am getting the below error.

![image](https://user-images.githubusercontent.com/26792519/30015584-ed4c0802-916e-11e7-876c-408ced30b2e3.png)

Please Suggest us.

Thanks & regards
Varun Reddy

**Comment by StanislawStempin** [comment]
Could you please try enabling the dev services endpoint as described in the blog post:
https://blogs.msdn.microsoft.com/nav/2017/08/03/nav-development-preview-august-update/

> If you need to code against W1, you will have to enable the developer service endpoint in the Administration Console for the NAV serverInstance and use “NAV” in the serverInstance setting in launch.json file. Note, that the NAV serverInstance is using UserPassword authentication and the other instances are using Windows Authentication.
