### ISSUE TITLE
CRM Table Extension with OptionOrdinalValues not possible

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/AL#5913]
**Describe the bug**
OptionOrdinalValues property is not possible to set on a CRM or CDS Table. 
You get the error:
The property 'OptionOrdinalValues' can only be set if the property 'TableType' is set with any of the values of :'CRM,CDS' AL(AL0167)

**To Reproduce**
Create a Table Extension on a CRM or CDS Table i.e. CRM Contact and add an option field with OptionOrdinalValues.

``` 
tableextension 50150 "CRM Contact NVX" extends "CRM Contact"
{
    fields
    {
        field(50150; "AnredeNVX"; Option)
        {
            ExternalName = 'nvx_anrede';
            ExternalType = 'Picklist';
            Description = '';
            Caption = 'Anrede';
            InitValue = " ";
            OptionMembers = " ",Herr,Frau;
            OptionOrdinalValues = -1, 100000000, 100000001;
        }
    }
}
 ```

**Expected behavior**
OptionOrdinalValues are accepted on a table extension on CRM or CDS Table.

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.277602

 - Business Central: AT Business Central 16.1 (Plattform 16.0.12630.13302 + Anwendung 16.1.12629.12805)

**Comment by atoader** [comment]
The issue has been fixed and it will be available in CU3 of the Wave 1 2020 release and the next major release.
