### ISSUE TITLE
Incomplete / incorrect .dal files

### ISSUE THREAD

**Issue by TeusV** [microsoft/AL#5914]
**Describe the bug**
When navigating to a .dal file, the .dal file only contains fields and global variables, but nothing else (like field properties, field triggers, table triggers, keys, procedures).

**To Reproduce**
Steps and to reproduce the behavior:
1. Declare a variable of an object on which your app is depending
2. F12/Go to Definition

```
var
    SalesLine: record "Sales Line";
```

**Expected behavior**
Getting a .dal file containing the entire object

**Screenshots**
5.0.271898 and earlier:

![image](https://user-images.githubusercontent.com/36189834/82888909-40b19e80-9f4a-11ea-8578-a07e05f3e317.png)

5.0.277602 and later:

![image](https://user-images.githubusercontent.com/36189834/82889422-00065500-9f4b-11ea-88b1-e1e28cd8439e.png)

Also note that in field 1 ```Enum "Sales Document Type"``` has been replaced by ```"Sales Document Type" Quote, Order, Invoice, "Credit Memo", "Blanket Order", "Return Order"```

**5. Versions:**
 - AL Language: 5.0.277602 and 5.0.279165
 - Business Central: W1 16.0 (Platform 16.0.11233.12061 + Application 16.0.11240.12076)

**Comment by dtkb** [comment]
Works here with AL 5.0.279165. Is this definitely consistent for you? IIRC I've seen it a couple of times, even in earlier versions, but a close/restart usually fixed it - something that's sadly needed often in VScode/AL with no apparent legitimate cause.

**Comment by Dam1Dam** [comment]
Same issue for me AL Language:  5.0.279165

**Comment by TeusV** [comment]
Yes it's consistent here, restarting does not fix it. Also I'm having the same behavior for a simple table like Geolocation (with only one GUID and two Decimal fields) - so it may be unrelated to the Enum thing I noticed in the Sales Line table.

**Comment by dtkb** [comment]
I take it that if you Download Symbols after changing to the new/bugged AL version, nothing changes?

**Comment by Dam1Dam** [comment]
No changes for me after downloading symbols

**Comment by TeusV** [comment]
No, no changes here as well after downloading symbols and restarting VS Code

**Comment by JulienDecottignies** [comment]
Do you have more than one configuration in your launch.json ?

It also happened to me (in v15 times) but never when I had only one configuration

**Comment by TeusV** [comment]
No, I have one configuration in my launch.json

**Comment by daansaveyn** [comment]
Same issue here. Very annoying. Workaround is using the AL Object Designer

**Comment by kalberes** [comment]
Unfortunately the latest vsxix has been released from a branch where gotodefinition is refactored 
to get rid of defaultLaunchConfigurationName  and also to support gotodefinition within a DAL file.
But this one needs  the latest 16.2 server. Thus until that is released gotodefinition would only show metadata information.

**Comment by kalberes** [comment]
We will release a fix that things will work as before the defaultLaunchConfigurationName has been introduced if one targets runtime < 5.2
For runtimes >= 5,2 the new gotodefinition logic will take place.

**Comment by TeusV** [comment]
Thanks a lot!
Also, great news that gotodefinition will become available in DAL files!

**Comment by kalberes** [comment]
We have pushed a new version where this issue should be fixed if you target apps with a runtime version < 5.1

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by TeusV** [comment]
Yes, it's resolved, thank you!

**Comment by NKarolak** [comment]
Can somebody please point me into the right direction?
I am currently developing on a 5.0 runtime (BC 16.0), and my dal files are still as empty as they used to be. Am I missing something, or does the fix not work for my runtime? 

I understood it should:

> We have pushed a new version where this issue should be fixed if you target apps with a runtime version <= 5.1

**Comment by TeusV** [comment]
What's the version of the VS Code extension 'AL Language'? Should work with 5.0.280447

**Comment by NKarolak** [comment]
It is the latest from Marketplace, 5.0.280447

**Comment by TeusV** [comment]
Then I don't know... Works for me with that version and runtime 5.0, BC16.0...
