### ISSUE TITLE
asserterror vs. intellisense

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5915]
**Describe the bug**
The `asserterror` keyword interrupts intellisense.

**To Reproduce**
First, try selecting a record variable field using intellisense (e.g. for a record "Sales Line" variable, choose field `Description`)
Next, create a new line, write `asserterror`, and enter the first letters of the record variable again. Intellisense does not recognize the record variable.
See video below.

**Expected behavior**
After `asserterror`, intellisense should not stop working.

**Video**
![Intellisense](https://user-images.githubusercontent.com/34504100/82912964-fe9a5400-9f6d-11ea-833c-c141313894dc.gif)

**Versions:**

 - AL Language: 5.0.279165

 - Business Central: 16

**Comment by kalberes** [comment]
What if you try asserterror**;** SalesLine.Description?
with asserterror SalesLine.Description you have just put the parser in an unrecoverable state.
That is normal. No parsing, no binding, no ahead symbols.

**Comment by NKarolak** [comment]
Of course using a semicolon works in terms of intellisense - but this is not how we must use [asserterror](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-testing-application#asserterror-keyword) in the code (*), so IMHO the parser should be able to handle this. 

(*) unless we test developers are forced by the compiler to put everything after asserterror into a new procedure instead of using record variables.

**Comment by kalberes** [comment]
It should

**Comment by kalberes** [comment]
Sorry for teh confusion. We have discussed it in the team and for now we stick the C/AL way procedure after the asserterror call.
But if you think it should be supported create a suggestion for it.

**Comment by NKarolak** [comment]
Pity.

So to everyone: please vote for https://experience.dynamics.com/ideas/idea/?ideaid=03236866-8fa1-ea11-8b71-0003ff68aeb2
