### ISSUE TITLE
Enum "Price Source Type" translation

### ISSUE THREAD

**Issue by Giumai** [microsoft/AL#5919]
I'm using the new BC16 table 7001 "Price List Line".
In this table there are some fields of type enum that implement interface.

I'm not able to translate the caption of them so I continue to see the fields not translated in user interface.

Here an example:

![image](https://user-images.githubusercontent.com/66070271/83141523-20bbdf80-a0f0-11ea-85e9-9a5ae05b3bb4.png)

🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by dtkb** [comment]
> I'm not able to translate the caption

How not? What did you try?

**Comment by Giumai** [comment]
I tried to extend the enum. One way was this for example:

enumextension 500100 "Price Source Type Ext" extends "Price Source Type"
{
    value(0;All)
    {
        modify()
        {
            Caption = 'Tutti';
        }
    }
}

But It's not a way permitted

**Comment by dtkb** [comment]
Translation should be done in `.xliff` files, not in `.al` code. You should use the appropriate localised version of BC, or if you are but it lacks some translations then file a bug with MS, but that's not for the AL repository.

**Comment by thpeder** [comment]
Hi @Giumai, 
We are aware that translating the values of enums hasn't been possible, but coming in 16.2 you can with the use of xliff files translate them from other apps.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
