### ISSUE TITLE
Show Picture on Word Layout Business Central V15

### ISSUE THREAD

**Issue by adrianordonez** [microsoft/AL#5921]
**Describe the bug**
i have a report with word layout with a blob field in that field i am saving a QR code in 64 base, in a previous version (V14) of business central i just add the field as a Picture object and the QR shows in my report, but when BC upgrade to V15 my report start to fail, so i include some code and i transform my blob field to text and that text field add it as a picture object but when i run the report i got the following message "The field x is a text field and is use as a picture object the report Z needs to be updated ¿Do you want to do the update?" if i hit ok the report shows the QR without a problem however i need that the updgrade message do not show to the user everytime they execute the report

i am using word layout becuase is easier for the user to modify than the layout than rdl

**Expected behavior**
Shows QR code without Business central upgrade message.

**5. Versions:**

 - Business Central: V15

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
