### ISSUE TITLE
Fasttab not collapsing when using RunModal

### ISSUE THREAD

**Issue by GALind88** [microsoft/AL#5922]
**Describe the bug**
On several pages that are opened via RunModal it is not possible to collapse the General fasttab.

**To Reproduce**
I have been unable to reproduce this with some of the pages in unmodified areas, but have found it to happen to several of our own card pages in the extension.

When one of these card pages is opened via a list page where the CardPageID is set, or via an action that uses Run instead of RunModal, the fasttab can be collapsed by clicking on it, but when the same card page is opened via RunModal the fasttab can not be clicked and collapsed.

```
if RecordX.Get(Code) then
    Page.RunModal(Page::"A Card Page", RecordX); 
```

**Expected behavior**
It should be possible to collapse and open the fasttab irregardless of the way the card page is opened.

**Screenshots**
n/a

**5. Versions:**
 - AL Language: 5.0.271898
 - Business Central: 16

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
