### ISSUE TITLE
Record variable tooltip not wide enough under certain circumstances

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5924]
(I cannot estimate whether this an issue for the AL compiler or for VS Code. Please advice.)

**Describe the bug**
Depending on the location of the last used tooltip window, the next tooltip window width for record variables is reduced, producing weird line breaks and being unreadable.

**To Reproduce**
Use this code
```
local procedure MyProcedure(var SalesLine: Record "Sales Line")
    begin      
    end;
```
Steps and to reproduce the behavior:
1. Reduce the VS Code window size, so that it ends near the code:
![image](https://user-images.githubusercontent.com/34504100/83231022-1c90d000-a18b-11ea-95b5-52da6557a5e9.png)

2. Hover over (1), next over (2), and check the width of the (2) tooltip window: all ok
3. Hover over (3) (=any tooltip that will be opened further right), next over (2) again and notice the reduced width and unreadability.
5. Hover over (1), next over (2): the tooltip is displayed correctly again.

![TooltipWidth](https://user-images.githubusercontent.com/34504100/83231627-13ecc980-a18c-11ea-8b9c-35ef1f6a80ee.gif)

**Expected behavior**
The tooltip should be always wide enough to display the content in a readable manner, else move the window more to the left.

**5. Versions:**

 - AL Language: 5.0.280447

**Comment by kalberes** [comment]
I do not think we do anything here. The language server does not handle UI just feeds the language client in VsCode with input. But maybe we are missing something, so I will take it as a bug until someone in the team will try debugging the issue.

**Comment by kalberes** [comment]
My colleagues have just told me that this is similar to this:
https://github.com/microsoft/AL/issues/4413
It is an issue in Vscode

**Comment by NKarolak** [comment]
Thanks. Does it mean that the VS Code team is already investigating?

**Comment by NKarolak** [comment]
@kalberes Any news on that issue?

**Comment by NKarolak** [comment]
It seems it was fixed in the meantime. I cannot reproduce anymore.
