### ISSUE TITLE
AL(AL0600) The property 'OptionCaption' can only be set on elements of type Option. I'm setting the option caption to enum field

### ISSUE THREAD

**Issue by dkatson** [microsoft/AL#5925]
**Describe the bug**
I have created a table.field of type enum. And enum itself with 5 values.
I have created a page and added this field to the page. 
I don't want the user to have an opportunity to select 5 values, but only 3.
So I set the property "Option caption" to : ' ,value1,,,value4,value5'.
And i get a warning
![image](https://user-images.githubusercontent.com/29101017/83239106-917efc80-a1c1-11ea-9c5d-385086de9b44.png)

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a enum with 5 values
2. Create a field of type enum and assign the previously created enum
3. Create a field on the page and add the option caption property.

**Expected behavior**
There should be some opportunity to use the same enum field in the different pages with different possible variants of choices. 

**Screenshots**

![image](https://user-images.githubusercontent.com/29101017/83239344-f20e3980-a1c1-11ea-9b99-48df360be179.png)

**5. Versions:**

 - AL Language: 5.0.280447
 - Business Central: Version: CA Business Central 16.1 (Platform 16.0.12630.12758 + Application 16.1.12629.12805)

**Comment by AskeHolst** [comment]
Use the ValuesAllowed property on the page field, that is the proper way to control it.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-valuesallowed-property

**Comment by NKarolak** [comment]
In case of extensible enums ValuesAllowed might be a problem, since you can only define the values that you know, not that of potentially other or any later installed apps. So if an app is installed later, the value won't show up. 
Of course, if it's only your very own enum, and it's not extendible, then you are ready to go.

For extensible enums: I'd suggest to work with a set of different enums instead. Not beautiful, though :-/

**Comment by AskeHolst** [comment]
I agree that it can cause problems for extensible enums, but using captions is even worse - if all translations are not updated correctly you can have options available in some languages but not in others. Also it causes extra translation work.
If I did a code review on code hiding option members on a page field using the OptionCaption hack Dmitry is using I would reject it.

**Comment by AndreyKorepanov** [comment]
Hi @dkatson, thank you for reporting the issue. As @AskeHolst mentioned the recommended way to set the values allowed in the field is ValuesAllowed. So I am going to close the issue. Thank you.
@NKarolak ValuesAllowed assumes that the values allowed in the given field are known in advance. Extending Enum you'll probable want to extend corresponding table/page.

**Comment by eque2al** [comment]
Thanks for your help with this, ValuesAllowed is perfect as it's our own page/IP so we can lock it down to just a couple of values and open it up further in future if necessary.  Many thanks 👍
