### ISSUE TITLE
Behavior of PromotedCategory = Process

### ISSUE THREAD

**Issue by CML1987** [microsoft/AL#5931]
**Describe the bug**
If I have only one or multiple actions in the page and all the actions are assigned to PromotedCategory **Process**, all the actions that I created is not being placed under the **Process** promoted action in the page. The behavior is different if I change the PromotedCategory to **New** or **Report**.

And if I pin the action and reopen the page, I will see duplicate actions which seems weird.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open the page **Test**
2. Pin the action menu
3. Close and reopen the page **Test** again.

``` page 50000 Test
{
    PageType = Document;

    layout
    {
        area(content)
        {
	}
    }

    actions
    {
        area(processing)
        {
            action(Disable)
            {
                ApplicationArea = All;
                Caption = 'Disable';
                Image = Reject;
                Promoted = true;
                PromotedCategory = Process;

                trigger OnAction()
                begin
                end;
            }
            action(Enable)
            {
                ApplicationArea = All;
                Caption = 'Enable';
                Image = Approve;
                Promoted = true;
                PromotedCategory = Process;

                trigger OnAction()
                begin
                end;
            }
        }
    }
}

 ```

**Expected behavior**
The actions should be grouped under Process category.

**Screenshots**
Actions assigned with PromotedCategory, Process
![image](https://user-images.githubusercontent.com/66260981/83418346-036f7400-a456-11ea-800e-f4aea48922b8.png)

Actions assigned with PromotedCategory, New
![image](https://user-images.githubusercontent.com/66260981/83418897-dff8f900-a456-11ea-9b46-8e9b625d9efd.png)

**5. Versions:**

 - AL Language: 5.0.280447

 - Business Central: W1 16.0 (Platform 16.0.11233.12061 + Application 15.0.36560.36649)

**Comment by dtkb** [comment]
It is quite handy to be able to promote actions directly to the toolbar, rather than to have a mandatory Process group. Does marking this as a bug mean that's not intended to work?

**Comment by kalberes** [comment]
This is marked as a bug, since for now I think that there are some inconsistencies in the behaviour as described in the repro steps.
That does not mean that it will end up fixed. It is my current early assessment. If i have some time I will debug the issue. If it is a compiler issue it will stay as a bug.
If not then the issue will have to be raised by some other means.  Example opening a support case.
For new ideas the best place is to add a new entry at the ideas site: https://aka.ms/BusinessCentralideas

**Comment by CML1987** [comment]
> It is very useful to be able to promote actions directly to the toolbar, rather than to have a mandatory Process group. Does marking this as a bug mean that's not intended to work? If so, it would be preferable to get some other way to do that added to the AL language.

I agree with you that it is a good idea of promoting the actions directly to the toolbar. But it would be good if we, the developer can configure it dynamically (group or individual) and not showing the actions repeatedly.
