### ISSUE TITLE
The file could not be uploaded because it was too large

### ISSUE THREAD

**Issue by RAJU334** [microsoft/AL#5932]
**Describe the bug**
A clear and concise description of what the bug is. Using the xmlport import / Upload of a 29 MB file gives following error:
The file could not be uploaded because it was too large. The maximum file size that can be uploaded is 2047 MB.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create Temp table >>create Xmlport>>Create test page/Action in existing page

![image](https://user-images.githubusercontent.com/45089434/83444318-d9737d00-a468-11ea-93aa-dc421651f7f1.png)

2. Publish and run xmlport>import the file

``` AL Code to reproduce the issue ```
![image](https://user-images.githubusercontent.com/45089434/83444350-e55f3f00-a468-11ea-8d8a-7887abb02276.png)

**Expected behavior**
Since the file is 29mB it should allow to import.

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
