### ISSUE TITLE
API based on AL is not working

### ISSUE THREAD

**Issue by rebisz** [microsoft/AL#5934]
**Describe the bug**
API (custom and standard) based on extensions is not published. Error 404 is raised.

**To Reproduce**
Get a new docker image with the latest CU ("14.13.42648.0-w1"). Try to open Standard API ex. http://w1:7048/NAV/api/v1.0/ will get an Error 404.

When new API is published as an extension Standard API is published either, but after Server Instance is restarted we get error 404.
After every uninstalls and install extension procedure API is visible till next restart.
```
page 50100 apiTest
{

    APIGroup = 'apiGroup';
    APIPublisher = 'dxcc';
    APIVersion = 'v1.0';
    Caption = 'apiTest';
    DelayedInsert = true;
    EntityName = 'Customers';
    EntitySetName = 'Customers';
    PageType = API;
    SourceTable = Customer;

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field(id; Id)
                {
                    ApplicationArea = All;
                    Caption = 'Id';
                }
                field(name; Name)
                {
                    ApplicationArea = All;
                    Caption = 'Name';
                }
                field(no; "No.")
                {
                    ApplicationArea = All;
                    Caption = 'No';
                }
            }
        }
    }

}
```

**Expected behavior**
Standard and Custom API based on AL is visible after every restart of an instance without uninstall and install procedure.

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: Version: Platform 14.0.42627.0 + Application 42648 (W1 14.13)

**Comment by kalberes** [comment]
Hi,
Can you repro this on the latest server release?

We have only capacity to handle questions based on the latest release.
The official answer being:
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/

You may also use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by rebisz** [comment]
It's the newest version for Business Central 14

**Comment by kalberes** [comment]
The latest version for BC is 16.1 as far as I know.

**Comment by rebisz** [comment]
Business Central 14 in no longer supported?

**Comment by kalberes** [comment]
It is, but this Githun chanel/repository is not for that.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
