### ISSUE TITLE
Page.RUN not working OnPostReport in BC16

### ISSUE THREAD

**Issue by Julian-Schaefer** [microsoft/AL#5938]
Hi everyone,

I just discovered what I think is a bug in Business Central 16 (Platform 16.0.12630.12758 + Application 16.1.12629.12805).

If I try to run a Page in the "OnPostReport" Trigger of a Report, the Page does **not** get displayed in BC16. However, if I run the **same** code in BC15 (Platform 15.0.38951.0 + Application 15.2.39040.0), it works just fine and opens the page.

To reproduce the error, use the below screenshot for a minimal example report.

![report](https://user-images.githubusercontent.com/11839572/83618790-40895280-a58b-11ea-9553-403dfb58e43d.PNG)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
