### ISSUE TITLE
Shortcutkey should be translated based on the selected language

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#5939]
**Describe the bug**
At the moment the Shortcutkeys aren't translated.

**To Reproduce**
Steps and to reproduce the behavior:
Create a Page with Actions and set a shortcutkey.

``` AL Code to reproduce the issue ```

**Expected behavior**
The ShortCutKeys should be translated for the selected language. 
Mostly this only applies to `Ctrl` and `Shift`.

**Screenshots**
![image](https://user-images.githubusercontent.com/56249171/83728653-f796d400-a646-11ea-8dd0-b98851088cfb.png)

**5. Versions:**

 - AL Language: 

 - Business Central: Version: DE Business Central 16.0 (Plattform 16.0.11233.12061 + Anwendung 16.0.12076.0)

**Comment by kalberes** [comment]
Do you mean that "Shift" and "Control" are not translated?

**Comment by mjmatthiesen** [comment]
> Do you mean that "Shift" and "Control" are not translated?

He does

**Comment by pri-kise** [comment]
Yes, that's exactly what I mean. Shift and Control are the ones I had in mind, not sure if there are some other keys which would need translation

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by SusanneWindfeldPedersen** [comment]
This is being forwarded to the team handling translations. Thanks.
