### ISSUE TITLE
Sugesstion: Multiple Event Subscriber decoration of procedures

### ISSUE THREAD

**Issue by megel** [microsoft/AL#594]
I suggest the support for Multiple Event Subscriber decoration of procedures. 

For Example is, the same procedure subscribe and handle more than one events by multiple adding the decoration (EventSubscriber - Attribute):
![grafik](https://user-images.githubusercontent.com/15800069/30032802-203ea46c-9198-11e7-83dc-aff7588a0b54.png)

**Comment by StanislawStempin** [comment]
Thanks for the suggestion, we will consider it for the long-term backlog

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
