### ISSUE TITLE
Procedure header / summary

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#5941]
**Describe the bug**
When hovering over a function, I do not see the function summary

**To Reproduce**
Following code:

```
codeunit 65123 funcHeader
{
    trigger OnRun()
    var
        recipients: List of [Text];
    begin
        recipients.Add('no@ema.il'');
        Smtp.CreateMessage('sender', 'email@inter.net', recipients, 'hello world', 'bye world');
    end;
}
```

**Expected behavior**
When I hover my mouse over CreateMessage, I expect to see the following header:
```
    /// <summary>
    /// Creates the email with the name and address it is being sent from, the recipients, subject, and body.
    /// This overload always uses HTML formatting for the body text.
    /// </summary>
    /// <param name="FromName">The name of the email sender</param>
    /// <param name="FromAddress">The address of the default sender or, when using the Send As or Send on Behalf functionality, the address of the substitute sender</param>
    /// <param name="Recipients">The recipient(s) of the mail</param>
    /// <param name="Subject">The subject of the mail</param>
    /// <param name="Body">The body of the mail</param>
```

**Screenshots**
The only thing we see is the procedure definition:
![image](https://user-images.githubusercontent.com/16603906/83829242-a8c95880-a69f-11ea-9caa-3aff672ca1ec.png)

**5. Versions:**

 - AL Language: 5.0.280447

 - Business Central: 16.1 something

**Comment by atoader** [comment]
Hi! The AL language extension does not have support for documentation strings at this point in time, but it is planned for a future release. I will close this as by-design.
