### ISSUE TITLE
Error when generating integration table for CDS entity with altpgen.exe

### ISSUE THREAD

**Issue by ligoendeavor** [microsoft/AL#5943]
**Describe the bug**
Getting "System.NullReferenceException: Object reference not set to an instance of an object." when trying to generate integrations table for CDS entity with altpgen.exe

**To Reproduce**
1. Using altpgen.exe from C:\Users\<user>\.vscode\extensions\ms-dynamics-smb.al-5.0.280447\bin folder.
2. Start Power Shell ISE as administrator
3. Run script from folder above:
.\altpgen 
-project:"C:\VSCode\CDSIntegration\" 
-packagecachepath:"C:\VSCode\CDSIntegration\\.alpackages"
-serviceuri:"https://mycrm.crm4.dynamics.com"
-entities:account
-baseid:50500

Cache folder contains symbol files from BC 16.1.

**Expected behavior**
A new AL file with a table extension of the account entity with the custom fields that were added in CDS.

**Screenshots**
![AL error](https://user-images.githubusercontent.com/43542521/83868290-e7582500-a72a-11ea-9883-ac6ee22400b0.png)

**5. Versions:**
 - AL Language: 5.0.280447

 - Business Central: Plattform 16.0.12630.13614 + App 16.1.12629.12805

**Comment by ligoendeavor** [comment]
Update on this issue: Seems like I can generate files for custom entities but not for standard ones.

**Comment by ligoendeavor** [comment]
Hi,

Any news about this? Still hitting exception, but now it looks different. In this new example I tried to generate file for the account entity in CE. The altpgen version is from ms-dynamics-smb.al-5.0.288712. alpackages are from BC 16.3.

altpgen.exe -project 'C:\VSCode\CDSIntegration\' -packagecachepath 'C:\VSCode\CDSIntegration\.alpackages' -serviceuri 'https://mycrm.crm4.dynamics.com' -entities account -baseid 50500

![image](https://user-images.githubusercontent.com/43542521/86903247-5bf9f700-c10f-11ea-808c-4b17f8a38204.png)

**Comment by ChronosBerlin** [comment]
Hello,

i have exactly the same issue, except BC Version 16.3.14085.14363, everything behaves sames. I already tested it with a CDX Demo Enviroment and it's work very well, but on another targeted enviroment i get the same error, too.

My guess is that i maybe have insufficient permissions on the enviroment?

@ligoendeavor Could you solve this problem?

**Comment by CChub402** [comment]
Hello,

Is there any update regarding this issue. I am struck, could not find any solution

**Comment by ligoendeavor** [comment]
@ChronosBerlin no, haven't solved this...

**Comment by onbuyuka** [comment]
Hi, could you please send the metadata of your CDS table 'account'? You can get it by two calls to CRM API: <environmenturl>/api/data/v9.1/EntityDefinitions(LogicalName='account') and <environmenturl>/api/data/v9.1/EntityDefinitions(LogicalName='account')/Attributes

**Comment by ligoendeavor** [comment]
@onbuyuka Attached files from both calls. Thank you!

[Metadata1.txt](https://github.com/microsoft/AL/files/5060990/Metadata1.txt)

[Metadata2.txt](https://github.com/microsoft/AL/files/5060991/Metadata2.txt)

**Comment by ligoendeavor** [comment]
Seems like the problem is solved with the latest AL-language (altpgen.exe) in VS Code. I'm now for instance able to generate file for the account entity.

**Comment by ligoendeavor** [comment]
I'm now using the altpgen.exe from this folder:
C:\Users\<user>\.vscode\extensions\ms-dynamics-smb.al-5.0.320540\bin

**Comment by thpeder** [comment]
It is great to hear the bug got resolved.
I'll close the issue and if you find another bug just open a new issue.
Thanks for reporting it.

**Comment by deadmouse** [comment]
Hello guys, I'm sorry for reopening this thread. Do you know if it is possible to do this with standard tables? I mean, I'd like to do somthing like this:

.\altpgen
-project:"C:\VSCode\CDSIntegration"
-packagecachepath:"C:\VSCode\CDSIntegration\.alpackages"
-serviceuri:"https://mycrm.crm4.dynamics.com"
-entities:serviceitems
-baseid:5940

Is it possible? If it isn't... is the alternative to create a duplicate table of Service Item table (5940) and then clone data from 5940 table to a 50100 new one?

Thank you

**Comment by onbuyuka** [comment]
@deadmouse Yes, you can use the alptgen tool with standard tables too.
