### ISSUE TITLE
.istemporary does not work in subscribers

### ISSUE THREAD

**Issue by bpiechowicz** [microsoft/AL#5944]
**Describe the bug**

.istemporary always returns 'No' in subscribers.
Please suggest a workaround if the bug is to be fixed in future versions.

**To Reproduce**

Run the below procedure 'CreateItemCategoryTemp':

    procedure CreateItemCategoryTemp()
    var
        ItemCatTemp: Record "Item Category" temporary;
    begin
        ItemCatTemp.Init();
        ItemCatTemp.Code := 'test';
        ItemCatTemp.Insert();
        Message(Format(ItemCatTemp.IsTemporary));
    end;

    [EventSubscriber(ObjectType::Table, Database::"Item Category", 'OnAfterInsertEvent', '', true, true)]
    local procedure OnAfterInsertItemCategory(Rec: Record "Item Category")
    begin
        Message(Format(rec.IsTemporary));
        if Rec.IsTemporary then
            exit;
        DoSomething(Rec);
    end;

As the result, 'DoSomething' procedure is ALWAYS executed, regardless the record being temporary or not. The code above gives messages 'No', 'Yes'.

**Expected behavior**
When the record is temporary the .istemporary in subscriber should return 'Yes'.

**Screenshots**
![image](https://user-images.githubusercontent.com/64404456/83883656-129b3e00-a744-11ea-859a-5500823afdb7.png)
First message:
![image](https://user-images.githubusercontent.com/64404456/83883730-2b0b5880-a744-11ea-8bfc-094a02c452b1.png)
Second message:
![image](https://user-images.githubusercontent.com/64404456/83883800-41b1af80-a744-11ea-9479-6510a168df89.png)

**5. Versions:**
 - AL Language: 
AL Language
microsoft.al
Microsoft
3.0.154634
AL development tools for Dynamics 365 Business Central
 - Business Central:
![image](https://user-images.githubusercontent.com/64404456/83883602-fe574100-a743-11ea-827a-90327e53e7eb.png)

**Comment by dtkb** [comment]
Pass the record by `var`.

**Comment by bpiechowicz** [comment]
You are right, that helped, thanks a lot!
