### ISSUE TITLE
Bulk Al code actions applying, after Txt2Al transformations

### ISSUE THREAD

**Issue by JalmarazMartn** [microsoft/AL#5945]
When we pass to C / AL to AL with Txt2al we have and old good practice that is write methods name without parenthesis:
Old C / AL way FIND -> New AL way Find (). Al code analyzer detects this issue and with Al code actions, I can fix it, but individually. The last transformation with a very small application, I have one hundred warnings due lack of parenthesis in methods and I must fix each one individually.
May I have a system to avoid click three times for each parenthesis issue? Put yourself in my place, 3 clicks x several hundreds of parenthesis issues.

**Comment by dtkb** [comment]
What would make more sense would be if `txt2al` didn't get this wrong in the first place.

**Comment by JalmarazMartn** [comment]
> What would make more sense would be if `txt2al` didn't get this wrong in the first place.

I agree, better idea.

**Comment by kalberes** [comment]
I would not treat them as bugs, but suggestions. Both of them.
And they should be suggested here:
https://aka.ms/BusinessCentralideas

Probably on longer term we should open the code actions API that anyone can integrate a new rule.

**Comment by JalmarazMartn** [comment]
> I would not treat them as bugs, but suggestions. Both of them.
> And they should be suggested here:
> https://aka.ms/BusinessCentralideas
> 
> Probably on longer term we should open the code actions API that anyone can integrate a new rule.

So I will close the issue and will leave them in ideas. Thank you very much Kálmán.

**Comment by JalmarazMartn** [comment]
I leave in ideas the txt2al idea from @dtkb in this publication: https://experience.dynamics.com/ideas/idea/?ideaid=53c600bd-0faa-ea11-8b71-0003ff68b7e1 

I am thinking about original idea, bulk applying of code actions , and I am not sure if it could be useful now. So, I keep using al code actions and testing if with new apps, would be necessary.
