### ISSUE TITLE
Import Excel - File contains corrupted data - Cloud SaaS

### ISSUE THREAD

**Issue by guilliano** [microsoft/AL#5946]
- AL Extension Version: 5.0.280447
- Server Version: 16.0.0.0
- Cloud SaaS

![image](https://user-images.githubusercontent.com/4299867/83967585-451f7500-a8c3-11ea-8757-e32c6dccbad2.png)

![image](https://user-images.githubusercontent.com/4299867/83967596-6aac7e80-a8c3-11ea-9b52-a3e98b93e089.png)

How can I import excel with BC SaaS?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
