### ISSUE TITLE
Info message on ExtensionsPermissionSet.xml when creating package

### ISSUE THREAD

**Issue by jvak** [microsoft/AL#5949]
Hi,

Is there a reason why we get an info message when we create a package in VS Code of our app, regarding the ExtensionsPermissionSet.xml, even when the xml is created correctly?

//***********************************************************
Microsoft (R) AL Compiler version 5.0.4.18311
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Core' containing '107' files at '10:32:55.806'.

c:\Users\jvak\Documents\AL\Navitrans.Core\app\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Users\jvak\Documents\AL\Navitrans.Core\app\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.

Compilation ended at '10:32:56.290'.

Success: The package is created.
//***********************************************************

**Comment by dtkb** [comment]
Isn't that just informational, i.e. 'we found this and will apply it to BC during deployment'?

**Comment by jvak** [comment]
ok, thanks. This may be closed.
