### ISSUE TITLE
Error if you make a clear on a interface variable

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/AL#5950]
You can create  a Package. But get an error during publish:
Error in VS Code
...failed with code UnprocessableEntity. Reason: One or more errors occurred.
This program location is thought to be unreachable.

``` AL Code to reproduce the issue ```
```
interface "IDemo"
{
    procedure GetName(): Text;
}
codeunit 50105 "MyDemoCodeunit"
{
    trigger OnRun()
    begin
        clear(myInterface);
    end;

    var
        myInterface: Interface IDemo;
}

```

**Screenshots**
![image](https://user-images.githubusercontent.com/39938430/84253214-f6b2e600-ab0f-11ea-8bce-b232760148cd.png)

**5. Versions:**
 - AL Language: 5.0.280447

**Comment by atoader** [comment]
Thank you for the repro! It does look like a bug.

**Comment by mhoury** [comment]
As of this writing, it seems, unfortunately, the bug remains.

**Comment by db-bc** [comment]
This seems fine now, as of:

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.4.496506
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

against a BC18.3 sandbox in Docker.

**Comment by Schnieringer** [comment]
I can confirm: with the AL version: AL Language v7.4.496506 the error is fixed.
Issue closed.
