### ISSUE TITLE
TableRelation on Table 5606 "FA Posting Group"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/AL#5951]
I would like to adjust the TableRelation. How is this possible in such a case?  

**original**  
```
        field(2; "Acquisition Cost Account"; Code[20])
        {
            Caption = 'Acquisition Cost Account';
            TableRelation = "G/L Account";

            trigger OnValidate()
            begin
                CheckGLAcc("Acquisition Cost Account", false);
            end;
        }  
```

**My wish**
```
field(3016008; "FA Accounting Fixed Asset"; Enum "FA Accounting Fixed Asset")
        {
            Caption = 'Accounting Fixed Asset', Comment = 'Rechnungslegung Anlagebuchhaltung';
            DataClassification = CustomerContent;
        }
        modify("Acquisition Cost Account")
        {
            Caption = 'Acquisition Cost Account';
            TableRelation = IF ("FA Accounting Fixed Asset" = const("Financial Accounting")) "G/L Account" ELSE
            IF ("FA Accounting Fixed Asset" = const("Cost Accounting")) "Cost Type";
        }
```

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by ddagkappeler** [comment]
@atoader I apologize for the wording. There still seems to be a bug. I've tested it with the latest preview version. If the original TableRelation has no condition it seems **not** to work.

**Comment by atoader** [comment]
What version of the runtime are you using?

**Comment by narongschmidt** [comment]
Can confirm, it's not possible to modify existing single table relations e.g. `TableRelation = "G/L Account"`. Multi table relations work though. Tested in CH Business Central 16.2 (Platform 16.0.13440.13772 + Application 16.2.13779.0)

**Comment by ddagkappeler** [comment]
@atoader What's going on here?

**Comment by atoader** [comment]
Please open an issue that follows the template with a full project that reproduces the issue and reference this one.
