### ISSUE TITLE
System automatically populates newly created field from first record in other table

### ISSUE THREAD

**Issue by rishitiwari1109** [microsoft/AL#5952]
- AL Extension Version: 5.0.260957

- Server Version: 

I created a new field in G/L Account extension which has a Table relation with another table but when I checked the G/L Account Card observed that all the Accounts are populated with the first value in another table which is creating an issue.Please help

**Comment by dtkb** [comment]
Hint: It sounds like you might have defined a FlowField of type Lookup, not a TableRelation

**Comment by rishitiwari1109** [comment]
@dtkb No it's TableRelation only Is it anyhow possible that On Card page it just shows the first record in TableRelation (for lookup purpose) field but actually does not save it

**Comment by dtkb** [comment]
It shouldn't be. And, in any case, you need to provide full minimised code that others can use to test/replicate the problem, and ideally also a screenshot of the output you see.

**Comment by rishitiwari1109** [comment]
tableextension 50000 "G/L Account Extension" extends "G/L Account"
{
    fields
    {
        field(50000; "Excise Posting Group"; Code[10])
        {
            Caption = 'Excise Posting Group';
            DataClassification = ToBeClassified;
            TableRelation = "Excise Posting Setup"."Excise Group Code";
        }
    }

}

pageextension 50005 "G/L Account Card Extension" extends "G/L Account Card"
{
    layout
    {
        addafter("VAT Prod. Posting Group")
        {
            field("Excise Posting Group"; "Excise Posting Group")
            {
                ApplicationArea = All;
                Caption = 'Excise Posting Group';
            }
        }
    }


}

![image](https://user-images.githubusercontent.com/60818730/84402431-09b5db00-ac22-11ea-945d-805989e7af40.png)

**Comment by dtkb** [comment]
What is the definition of `"Excise Posting Setup"."Excise Group Code"`? Is it the primary key field, part of a composite primary key, or something else?

**Comment by rishitiwari1109** [comment]
@dtkb It is part of Primary Key

**Comment by dtkb** [comment]
One field in a multi-field PK, or the only field in a single-field PK?

Just provide the full info ahead of time. It's so inefficient having to eke it out like this.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by rishitiwari1109** [comment]
> 
> 
> One field in a multi-field PK, or the only field in a single-field PK?
> 
> Just provide the full info ahead of time. It's so inefficient having to eke it out like this.

part of multi-field Primary Key
