### ISSUE TITLE
Enum appsource validation Question

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#5955]
Hi all

Is it ok to change enum type of a field for example I have field in my custom table with a custom Enum but due to issues changed to a similar standard Enum?

Is it ok to delete a value in an Enum i.e if an enum has around 6 values want to delete the last one?

**Comment by qutreson** [comment]
Hi @bachii1010, for the first question see [this comment](https://github.com/microsoft/AL/issues/5818#issuecomment-616436826) about why we do not allow it. 
For the second question, this is also a breaking change as removing an enum value would break the dependent extensions that are referencing it. The appsourcecop should validate for it. If not, it is a bug.

**Comment by qutreson** [comment]
The AppSourceCop currently allows to remove enum values while it should not, I will use this issue will track this scenario.

**Comment by atoader** [comment]
We have added rules in AppSourceCop to prevent removing enum values. This will be part of the next minor release (17.1) and of the developer preview.
