### ISSUE TITLE
Errors AD0001 in App.Json

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5956]
**Describe the bug**
these exceptions appear in the app.json:
[al-log.txt](https://github.com/microsoft/AL/files/4763537/al-log.txt)

to summarize:

- Rule066AddingPublicAPIProcedureNotAllowed
- RuleDestructivePageChangesNotAllowed
- RuleIdRangeMustBeRespected
- RuleAppManifestConfigurationMustBeProvided
- RuleDestructiveTablePropertyChangesNotAllowed
- RuleDestructiveTableKeyPropertyChangesNotAllowed
- RuleTranslationsMustBeProvided
- Rule050ApplicationObjectExtensibilityChangeNotAllowed
- RulePublicAPIBreakingChangesNotAllowed
- RuleTranslationsMustBeProvided
- RuleIdentifiersMustHaveValidAffixes
- RuleInvalidObsoleteTagsNotAllowed
- RulePreviousVersionNotFound
- RuleDestructiveInterfaceImplementationChangesNotAllowed
- RuleDestructiveTableFieldPropertyChangesNotAllowed
- EmailAndPhoneNoMustNotBePresentInTheSource

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.277481
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: BC160 RTM

**Comment by atoader** [comment]
Hi! We had a bug around how additional assemblies are loaded by the static analysis framework. The issue should be resolved in version 6.0.287158 or newer.

**Comment by stefanoPrimo** [comment]
Hi!
I've just installed the new AL Language from the daily Build W1. But for now no changes. I will wait! 
Thanks

**Comment by qutreson** [comment]
Hi @stefanoPrimo, did you get a chance to verify if this issue is fixed in our latest developer preview?

**Comment by stefanoPrimo** [comment]
Yes, I've just updated and No errors! Great work!
Thanks

**Comment by qutreson** [comment]
Thank you for reporting it and verifying it!
