### ISSUE TITLE
Invoking the AL: Publish without debugging from command palette or Ctrl + F5 hotkey starts debug session

### ISSUE THREAD

**Issue by cactozdev** [microsoft/AL#5957]
**Describe the bug**
Invoking the AL: Publish without debugging from command palette or Ctrl + F5 hotkey starts debug session.
Currently using mutli-root workspace.

**To Reproduce**
Ctrl + Shift + P -> AL: Publish without debugging
OR
Press Ctrl + F5

**Expected behavior**
Extension compiled successfully
Extension published and installed successfully on instance specified in launch.json

**Screenshots**

**5. Versions:**
 - AL Language: v5.0.280447
 - Business Central: Platform 14.0.36457.0 + Application 35970 (W1 14.5)

**Comment by atoader** [comment]
@kalberes

**Comment by cactozdev** [comment]
FWIW, perhaps it's a vscode issue.

This issue occurred on the latest release of vscode:

Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19645

It doesn't occur when using the insider build of vscode:

Version: 1.47.0-insider (user setup)
Commit: 7e4cc2c435927e5a2845897961a2af10ee7f784d
Date: 2020-06-12T06:03:53.183Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19645

**Comment by kalberes** [comment]
Yes it looks a like a VSCode glitch. There is a bug introduced as I see it in the Debug Adapter Protocol client part that ignores some of our internal state. I think until the 1.47 release of vscode it is better to use the insider build

**Comment by kalberes** [comment]
We have fixed it locally and will soon release a new vsix

**Comment by bjarkihall** [comment]
@kalberes I'm wondering if this is also related to that RAD has stopped working?

It started happening yesterday when most of the staff at my company switched over to 16.2 (both local and docker setups, OnPrem in all cases).
We've tried RAD (with and without debugging, doesn't matter ofc) on vscode 1.45 (browser opened up and only showed loading dots for at least half an hour without anything happening - client won't start) and 1.46 (browser opens up and shows error "something went wrong" once logged in, here's the [event log](https://pastebin.com/aVQRybac) I had for that case).

I'm using AL Extension v5.0.288712 but no one seems to have RAD working, so it would be greatly appreciated if you could confirm that RAD works for you with 16.2 and what the version number of the new vsix is. :)
I couldn't find any discussion about this issue but found it odd that this functions differently between vscode versions and this happened to everyone at my workplace at the same time, so I decided to try asking here first before opening a new issue.

**Comment by kalberes** [comment]
Yes, we are aware and have seen the 
Type: System.UnauthorizedAccessException
Message: MemoryStream's internal buffer cannot be accessed.
It is not related to the VSCode issue above. We are working on that too.
Unfortunately this will require a new server patch.

**Comment by Charan-D365** [comment]
When’s the fix out?

**Comment by atoader** [comment]
The issue has been fixed in master and it will also be fixed in 16.4.

**Comment by bjarkihall** [comment]
@atoader just to confirm, is it just "Publish without debugging" or has RAD also been fixed in master/16.4? :) I didn't raise an issue since @kalberes already knew about it.

**Comment by atoader** [comment]
Both :)
