### ISSUE TITLE
[CodeCop] Stops warning at certain file level

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#5958]
**Describe the bug**
In the kind of file I provide in attachment, CodeCop stops to display warnings at a certain lines. In the example I provide in **Reproduce Steps**, the warnings are not displayed in the **layout{}**objet at a certain line and for the rest of the **layout** lines. But outside the layout{} (in actions{}) warnings are displayed again.

**To Reproduce**
Steps and to reproduce the behavior:
1. Download the file attachment 

2. Comment the line 17 to remove the tooltip:
![image](https://user-images.githubusercontent.com/29598240/84370551-b1a6b680-abd8-11ea-804c-b68f48337b19.png)

=> The warning is displayed

Look for line 49:
![image](https://user-images.githubusercontent.com/29598240/84370639-d1d67580-abd8-11ea-9721-9f7c362e3427.png)

There is a missing tooltip, but CodeCop doesn't warn about it.

If you go to line 44, and comment the ShowCaption property, here, CodeCop wants to warn us:

![image](https://user-images.githubusercontent.com/29598240/84370737-faf70600-abd8-11ea-9e69-f968cbceb489.png)

For code outside of the Layout{} part, it seems to have no effects and warnings are shown correctly:

![image](https://user-images.githubusercontent.com/29598240/84370853-1feb7900-abd9-11ea-8f65-6537b6e0643d.png)

Thanks for your help
 

``` AL Code to reproduce the issue ```
[warningissue.zip](https://github.com/microsoft/AL/files/4763979/warningissue.zip)

**5. Versions:**
 - AL Language: 5.0.280447
 - Business Central: 16.1

**EDIT** 
Seems related to ShowCaption = false. When it's set to false for a field, the warnings that must follow are not shown.

**Comment by eque2al** [comment]
When taking a newly converted module into AL I've noticed the number of CodeCop bugs go down during the day as expected when I am adding missing properties (eg, ApplicationArea, DataClassification) but then after a while the number of errors jumps up WAY beyond where it started at in the morning!!  Which after doing a stack of work is very depressing let me tell you!!

Not sure if that's related to this problem that has been highlighted here or whether it's a 'caching' problem in VS Code.  Either way please fix it ASAP..!! Thanks :)

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
