### ISSUE TITLE
Processing of message 'al/gotodefinition' failed with error: 'SyntaxTree 'table 112

### ISSUE THREAD

**Issue by mcbones1812** [microsoft/AL#5960]
- AL Extension Version: 5.0.280447

- Server Version: ES Business Central 16.0 (Platform16.0.11233.12061 + Application 16.0.12076.0)

I've downloaded the standard symbols and they have shown me this message

-Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible. Processing of message 'al/gotodefinition' failed with error: 'SyntaxTree 'table 112 "Sales Invoice Header"

**Comment by atoader** [comment]
Can you provide a video that shows the repro and a sample project?
