### ISSUE TITLE
httpclient + 'GET' + Requestbody not working, 'Cannot send a content-body with this verb-type'

### ISSUE THREAD

**Issue by RajanBCDeveloper** [microsoft/AL#5961]
**Describe the bug**

Httpclient.send(RequestMessage,Responsemessage) not working, prompts error 'Cannot send a content-body with this verb-type'

**To Reproduce**
Steps and to reproduce the behavior:

         Uri := 'https://XXXX/xxxxx';        
        Content := Jsonbody;
        RequestContent.WriteFrom(Content);
        RequestContent.GetHeaders(Headers);
        Headers.Remove('Content-Type');
        Headers.Add('Content-Type', 'application/json');    
        RequestMessage.Content(RequestContent);
        RequestMessage.Method('GET');
        Client.DefaultRequestHeaders.Clear();
        Client.DefaultRequestHeaders.Add('Authorization', 'Basic XXXXX');
        Client.SetBaseAddress(uri);
        Client.Send(RequestMessage, ResponseMessage);

**Expected behavior**

Supports RequestMessage content in 'GET' method

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.280447

 - Business Central: 16.0.11240.12322

**Comment by atoader** [comment]
The AL HttpClient is a wrapper around the .NET class with the same name. Can you first check what the behavior of that class is in these circumstances?

**Comment by RajanBCDeveloper** [comment]
I need to send requestcontent in 'GET' method. How to achieve in AL BC Saas version

**Comment by ajkauffmann** [comment]
It is very uncommon to send a body with a HTTP GET command. It may be possible according to the specifications, but you would normally use the POST command.

In the .Net framework, this is not supported by the HttpClient. In .Net Core the HttpClient supports it.
Source: https://github.com/dotnet/runtime/issues/25485

**Comment by RajanBCDeveloper** [comment]
Thanks @ajkauffmann ,Is there possibilities to handle winhttphandler in BC Saas

**Comment by AndreyKorepanov** [comment]
Hi @RajanBCDeveloper, thank you for reporting the issue. As @atoader mentioned the AL HttpClient is a wrapper around the corresponding .NET class, which does not support HTTP GET request with a body. So I am going to close the issue now.  Thank you!
Please note that even if the body is allowed in HTTP GET, but not recommended for multiple reasons. As you noticed the WinHttpHandler wrapper might be a workaround in this case. Please also note that .NET Core HttpClient supports HTTP GET with a body by default.
