### ISSUE TITLE
Add FactBox Area with PageExtension

### ISSUE THREAD

**Issue by legrlion** [microsoft/AL#5963]
Hi,

We're trying to add a FactBox to "Sales Lines" Page (Id 516 for old NAV developers who always talk about objects by their numbers 😄).
Unfortunately, the FactBox area doesn't exists on this page, and we can't add it.
Or maybe I missed something...

Can we have the possibility to add an area (FactBox or other) to an existing Page using a PageExtension ?

Have a nice day !

**Comment by dtkb** [comment]
So, e.g., `addfirst(factboxes)` does not work, and tells you that no such area exists?

**Comment by legrlion** [comment]
Version is 16.0.11240.12076-be. I missed to include this info.
Indeed, it works. Even if this Area is not present in the page.
I don't know why I wasn't able to do this before opening this issue (mistyping, lack of concentration).
Thanks for your help.
