### ISSUE TITLE
Extensions created by the in-page designer 

### ISSUE THREAD

**Issue by RichardPostborg** [microsoft/AL#5965]
We have a page with a field and validation code on the page/field. This field is set to Visible=false.

The user/customer would like to have that field in the page and uses design to add the field. 

In the In-Page designer they are able to add the field, but the way its added is like a new field - meaning that there is no validation code on the field.

They are not able to see that the field is already in the page - and they are not able to just make it visible by extension (via the In-Page designer).

A simple solution would have been to just make an error if they add an filed that is already in the page, and the right solution would be to should all fields that are in the page - also thoose taht are not visible, and make it possible to make them visible.

NOTE that all this works prefect and ok - if they had added the field by personalize instead of using design

**Comment by dtkb** [comment]
Just to be That Guy: Doing validation on the table, not page, level is proper and would obviate this.

**Comment by RichardPostborg** [comment]
You are right, and that is what we normally do, however in this scenario - when we load the page we create and load a bunch of temporary records, and these are used in the validation code.  

I'm not saying that there isn't a workaround for it, I'm just stating that I see this as an issue, since I spent several hours to find out why it was working locally but not at the customer site, and I see this as a scenario that could occur as long as there is a option to put code on page triggers.

**Comment by AskeHolst** [comment]
If a table field requires special logic and other apps cannot be trusted to handle that, like in your example, it should have Access=protected. That will stop any other app directly referencing that field from compiling. Any other app needing to use that field will then have to call the procedures you have for accessing it correctly.

**Comment by AndreyKorepanov** [comment]
Hi @RichardPostborg, thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
