### ISSUE TITLE
BC Environment Issue 16.2

### ISSUE THREAD

**Issue by IAMKrishnaKumar** [microsoft/AL#5967]
Hi Team,

I am getting a warning regarding upgrade as per new changes.
I have downloaded the new symbols and updated all the customized extensions with new solution and fix.
I have uploaded the app file with current version.

Still Getting same warning message. "Your environment can't be updated to Business central Wave 1 16.0 Because of incompatibility issue."
Shall I just wait for Next version or shall I use Next Minor Version?

**Comment by pmohanakrishna** [comment]
If you are on 15.x version and getting errors while upgrading to 16.0 then you have to use "Next major" version.

If you are on 16.1 and getting errors while upgrading to 16.2 then you have to use "Next minor" version.

**Comment by LevtechConsultingServices** [comment]
Current Version of environment is 16.1. So I'll have to use Next Minor Version For all the Customized Extension. Right?
So After that it will not show this kind of error.

**Comment by LevtechConsultingServices** [comment]
But Microsoft is updating the version in all other Business central Environment. 
Is it really required to do that? Its production. I hope there would not be any data loss.

**Comment by AndreyKorepanov** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
