### ISSUE TITLE
API Automation extensionDeploymentStatus doesn't work

### ISSUE THREAD

**Issue by pmatsconsulting** [microsoft/AL#5973]
Build number : 16.0.11240.11946

Invoke of API Automation method extensionDeploymentStatus returns an empty list in BC16 online
Works fine in BC15 online

Steps to repro:
- Deploy an App per tenant (manually or by API Automation)
- Invoke of API Automation method extensionDeploymentStatus
Expected results:
- not empty list
Actual results:
- empty list

**Comment by AndreyKorepanov** [comment]
This is known issue not related to AL language, the other team is working on it. 
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
