### ISSUE TITLE
Issue while publishing App on Sandbox

### ISSUE THREAD

**Issue by mcnetronic** [microsoft/AL#5975]
Hi everybody,

I cannot deploy extension on the sandbox environment.
Following error I am getting while publishing:

[2020-06-03 14:39:03.29] The request for path /v2.0/Sandbox3/dev/apps?SchemaUpdateMode=recreate&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: You do not have the following rights on the TableData Published Application object: IndirectInsert. For the details of the rights, see the Applicable Rights page. To report a problem, reference the following server session ID: '22123'.

These permissions are set:

![image](https://user-images.githubusercontent.com/41568399/85220563-cd664580-b3ac-11ea-854b-637312f94529.png)

![image](https://user-images.githubusercontent.com/41568399/85220593-1b7b4900-b3ad-11ea-8d59-a54a796ef78a.png)

Further information:
AL Language: Version - 5.0.288712
Visual Studio Code: Version 1.45.1
Business Central: Version: W1 16.1 (Platform 16.0.12630.13560 + Application 16.1.12629.12805)

I cannot reset the sandbox, see the solution on https://github.com/microsoft/AL/issues/4531#issue-403657745, because the sandbox contains customer`s data.

Thanks in advance and regards!
Monica

**Comment by qutreson** [comment]
@mcnetronic can you verify that the permissions for D365 EXTENSION MGT is set for all companies (meaning no company is assigned to the permission set)? If you have SUPER or D365 EXTENSION MGT for only one company, publishing an extension won't work.

**Comment by mcnetronic** [comment]
Thanks for your prompt reply!

I will test it and give you feedback.

**Comment by mcnetronic** [comment]
Thanks! It works!
