### ISSUE TITLE
Debugger does not update List data type variables

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5977]
**Describe the bug**
When watching debugger variables, after a call of MyEnum.Names() or MyEnum.Ordinals(), the corresponding List data type variable won't get updated in the Variables sections. The update works only if the debugger is **started after** the method calls. 

**To Reproduce**
Use the following function:
``` 
    local procedure TestEnums()
    var
        Names: List of [Text];
        Ordinals: List of [Integer];

        MyEnum: Enum "Sales Line Type";        
    begin
        Names := MyEnum.Names(); // trigger point 1
        Ordinals := MyEnum.Ordinals();

        MyEnum := MyEnum::"Charge (Item)"; // trigger point 2       
    end;
 ```
Set a trigger on lines "trigger point 1" and "trigger point 2".
Run the code with a debugger until point 2: the List data type variables won't get updated:
![ListVariables](https://user-images.githubusercontent.com/34504100/85260060-5c856300-b46a-11ea-9929-ec8271e17a63.gif)

Stop debugging.
Remove trigger point 1 and start debugging directly at point 2:
The variables are filled correctly.
![image](https://user-images.githubusercontent.com/34504100/85260182-8d659800-b46a-11ea-9988-f6f3d77ee829.png)

**Expected behavior**
When starting at point 1, the variables should be updated when hitting point 2.

**5. Versions:**
 - AL Language: 5.0.288712

 - Business Central: 16.0

**Comment by txeriff** [comment]
The debugger is rubish, works really bad. Sometimes variables update the values, sometimes not. You can´t copy the value to clipboard...
It delivers poor quality.

**Comment by BazookaMusic** [comment]
This is fixed nowadays since version 12, closing this
