### ISSUE TITLE
Format(MyEnum, 1) returns unexpected value

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5978]
**Describe the bug**
Format(MyEnum, 1); returns the first letter of the enum value caption, instead of the whole value caption.

**To Reproduce**
Debug the following function:
``` 
    local procedure TestEnums()
    var
        MyEnum: Enum "Sales Line Type";
        Format0Text: Text;
        Format1Text: Text;
    begin
        MyEnum := MyEnum::"Charge (Item)";

        Format0Text := Format(MyEnum, 0);
        Format1Text := Format(MyEnum, 1);
    end;
```
Note that Format1Text will be "C", not "Charge (Item)".
![image](https://user-images.githubusercontent.com/34504100/85261103-04e7f700-b46c-11ea-88fa-3cef677bd560.png)

**Expected behavior**
According to the [online help](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property), `Format(MyEnum, 1)` should have returned the whole caption "Charge (Item)".
![image](https://user-images.githubusercontent.com/34504100/85260897-b20e3f80-b46b-11ea-8746-9a0c5701e568.png)

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: 16.0

**Comment by dtkb** [comment]
Isn't the `Format` column referring to the 3rd parameter of the `Format()` function, with the 2nd parameter being the length to return? Then this seems correct. AFAIK to get the localised translation of an option/enumerator/RecordID whatever, it's always `Format(Foo, 0, 1)`, where `0` means 'no limit on length'.

**Comment by NKarolak** [comment]
Outch, of course. It's just another manic Monday.... 🙃
