### ISSUE TITLE
Not able to use "Sales document Type" Enum in custom objects

### ISSUE THREAD

**Issue by RAJU334** [microsoft/AL#5979]
**Describe the bug**
A clear and concise description of what the bug is. When using a base Enum in custom page system 
giving error messge "The type navoption is unknowm"

**To Reproduce**
Steps and to reproduce the behavior:
1. Create new table with "sale document type" Enum , document no and new field technician.
![image](https://user-images.githubusercontent.com/45089434/85292640-da248f80-b4b9-11ea-8050-aa0531b1fe48.png)
2. Create List page
![image](https://user-images.githubusercontent.com/45089434/85292296-5074c200-b4b9-11ea-9b54-a3257d3cd6fd.png)
3.Add Action in sales order page
![image](https://user-images.githubusercontent.com/45089434/85292176-228f7d80-b4b9-11ea-8509-3aecc43ba1e7.png)
4.open sales order and click on the actions
![image](https://user-images.githubusercontent.com/45089434/85292471-8fa31300-b4b9-11ea-9d62-b9d01cabd780.png)

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by AndreyKorepanov** [comment]
Hi @RAJU334 thank you for reporting the issue. I tried the code from your description and it works fine on my side (see the project attached). We need some additional information regarding the version AL/BC you use. Please test it with the latest daily build, it might be fixed there. Could you also provide the test project demonstrating the issue, if you find that mine one lacks some details. Thank you.
[ALProject54.zip](https://github.com/microsoft/AL/files/4821775/ALProject54.zip)

**Comment by RAJU334** [comment]
Worked. Thank you @AndreyKorepanov .
