### ISSUE TITLE
Adding new actions with the WYSIWYG Designer

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#598]
It is well known that Microsoft introduced the new WYSIWYG Designer in the WebClient at the last Directions NA. In the future, users should be able to add fields, actions, parts and FactBoxes. A question has been asked recently, and because we didn't find anything here, I put it right here. 

How is it thought to link new actions that are added by the designer with logic? We think it would make sense if it would be possible to link the actions to an existing event. As an example, we build an extension in which the user should be able to insert actions into any page independently. How will we deal with such a case in the future? Are there special events where the user can link the action? Will these be made available for selection? Rather, the problem is the dynamics of events. It would somehow be possible to make the fixed static events more flexible and accessible for this kind of adaptation.

**Comment by StanislawStempin** [comment]
This is on our long term backlog.
