### ISSUE TITLE
AA0139 Rule gives an Error when passing the Text strings to a function

### ISSUE THREAD

**Issue by miljance** [microsoft/AL#5980]
**Title**
AA0139 Rule gives an Error when passing the Text strings to a function.

**Description**
The parameter in a function is declared as a text of unlimited length. The variable passed to the function has a limited length though. The Rule AA0139 gives an overflow error if a variable is passed to the parameter.

**Expected behaviour**
No Error should appear

Example:
![image](https://user-images.githubusercontent.com/42636293/85378698-2fed4c00-b53b-11ea-8bd4-2bd280a62525.png)

**Comment by dtkb** [comment]
It should warn, because those are `var` arguments, so the function might try to assign unlimited sized texts to your shorter ones and thus cause a run-time error.

**Comment by miljance** [comment]
Good point. Thanks. 

In this case the question is what to do in cases when we want to have a general function with unlimited text length as parameter but we want to pass the field with limited length. The only correct way in this case would be to use Variables before function call. I would love to see the implementation in the base app.

**Comment by MarcHansenMicrosoft** [comment]
The CodeCop warning it by design.

If you want a function that takes a fixed size then please log a normal public function request request.

Thanks
Marc
