### ISSUE TITLE
Warn when triggers are declared with no code

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5981]
**Title**
I suggest a code analysis rule when a trigger has been declared and contains no code between begin/end.

**Description**
Developers might create empty triggers by using VSCode templates.
The worst come from the txt2al tool: in C/AL+years of development and developers might have created empty triggers just by letting a local variable declared and not removing it.

**Reason for the rule**
Like warning AA0137 it would let us keep the code clean and prevent triggers to be called without reason.

**Bad code sample**
Example of what bad code the rule should catch:

```
    trigger OnAfterGetRecord()
    var
        Status: Text;
        i: Integer;
        j: Integer;
    begin
    end;
```

**Good code sample**
Example of what code should look like:

``` The trigger should be removed ```

**Good and bad practices for fixing the rule**
A code action could be provided to remove the trigger.

**Remarks**
A similar rule could apply on empty procedures.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t started on it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
