### ISSUE TITLE
Warn or Info when a local procedure is unused

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5982]
**Title**
Some functions might be developped or converted from C/AL and are not used anymore. They should be removed.

**Description**
Some functions might be developped or converted from C/AL and are not used anymore. They should be removed.

**Reason for the rule**
Same reason as rule AA0137.

**Bad code sample**
Example of what bad code the rule should catch:

```
**local** procedure MyUsefulFunction()
begin
  Message('I could be useful but if no one calls me, I am useless :)');
end;
```

**Good code sample**
Example of what code should look like:

``` The procedure should be either called or removed. ```

**Good and bad practices for fixing the rule**
./.

**Remarks**
./.

**Comment by PaulIvan** [comment]
hi @nicolassaleron we already have a rule for unused functions AA0228. Isn't this what you need here? 😄 
![image](https://user-images.githubusercontent.com/617029/103764685-37c69680-501c-11eb-8982-fc4d37c92ce0.png)

**Comment by nicolassaleron** [comment]
I am pretty sure this rule did not exist in June 2020 :)
