### ISSUE TITLE
Attachements are not flowing while creating Sales Order from Blanket Sales Order

### ISSUE THREAD

**Issue by MaheshUppala** [microsoft/AL#5983]
- AL Extension Version: 5.0.288712

- Server Version: v. 16.2.13509.13619

Codeunit 87 "Blanket Sales Order to Order"
Function CreateSalesHeader
![image](https://user-images.githubusercontent.com/34763546/85424595-be8eb700-b595-11ea-9cdc-3a8087e04fe0.png)
For above highlighted publisher there is a subscriber in codeunit 1173
![image](https://user-images.githubusercontent.com/34763546/85424973-3a88ff00-b596-11ea-923b-383e8a269bba.png)
the above highlighted condition becomes true because of see below image
![image](https://user-images.githubusercontent.com/34763546/85425086-5be9eb00-b596-11ea-917d-88572ee2b140.png)

It is working fine other document pages like blanket purchase orders,sales quotes...etc.

**Comment by AndreyKorepanov** [comment]
Hi @MaheshUppala, thank you for reporting the issue. Could you please clarify what's the problem there and what is expected result. Thanks.

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
