### ISSUE TITLE
Dynamic Visibility is not working for Card Pages

### ISSUE THREAD

**Issue by Anirudh053** [microsoft/AL#5984]
**Version**
Version: US Business Central 16.0 (Platform 16.0.11233.12436 + Application 16.0.11240.12474)

**To Reproduce**

Step 1: Add a new Boolean field "Show Document Total Fields" in any of the setup tables and bring the same in page as well.
Step2: Create a new decimal variable like "Total Document Amount" in Purchase Invoice Page Extension.
Step3: Create a new Global Boolean variable "DocumentTotalVisible" in Purchase Invoice Page Extension.
Step4: Create a new function "GetTotalDocumentAmountVisibility" in Purchase Invoice Page Extension and in this function assign the value of "Show Document Total Fields" from Setup table to "DocumentTotalVisible" in Purchase Invoice Page Extension.
Step5: Now, assign "DocumentTotalVisible" variable in visible property of "Total Document Amount" field in Purchase Invoice Page Extension.
Step6: Test this change by enabling and disabling "Show Document Total Fields" in Setup Page.

**Screenshots**
New Boolean field in Setup Table:
![image](https://user-images.githubusercontent.com/67334699/85434771-29df8580-b5a4-11ea-836d-1a4d2260ac74.png)

New function in Purchase Invoice Extension Page:
![image](https://user-images.githubusercontent.com/67334699/85435076-95c1ee00-b5a4-11ea-9e68-68b57838cb86.png)

Adding Boolean variable to Visible property for a Decimal variable field in Purchase Invoice extension page
![image](https://user-images.githubusercontent.com/67334699/85435267-d28de500-b5a4-11ea-971a-69b6eda7b850.png)

This visibility is working only when we close and open the business central web client.

**Comment by AskeHolst** [comment]
Put the field in a group and set visibility on the group. It's all in the docs: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-visible-property#remarks

**Comment by Anirudh053** [comment]
Thankyou for the reply, we have tried by adding the visibility condition to the Group. But, still it is getting applied only when we close and open the Business central web client.

![image](https://user-images.githubusercontent.com/67334699/85540559-c487a500-b634-11ea-8c9f-598322d5d143.png)

**Comment by NKarolak** [comment]
When is your function `GetTotalDocumentAmountVisibility` (or as in the screenshot: `CheckDocTotalFieldsVisibility`) ever called in your code? I found no hint in your initial post.

**Comment by Anirudh053** [comment]
I have called *CheckDocTotalFieldsVisibiliy* function in the below triggers.

OnOpenPage()
OnNewRecord()
OnAfterGetRecord()

**Comment by NKarolak** [comment]
Try OnAfterGetCurrRecord instead of OnAfterGetRecord and OnNewRecord.

**Comment by Anirudh053** [comment]
Still the same even calling the CheckDocTotalFieldsVisibiliy function in *OnAfterGetCurrRecord* and *OnNewRecord* triggers. The changes are getting applied only when we close and open the Business central web client.

**Comment by NKarolak** [comment]
Have you already tried debugging the function when called by a trigger? Is the ShowDocumentTotals variable really updated as expected?

**Comment by Anirudh053** [comment]
Yes, I have tried debugging the function and also the triggers where ever it is called. ShowDocumentTotals variable is getting updated based the changes in Setup table.

We were able to see the changes only if we close and open business central web client or else opening business central in new tab.

**Comment by AndreyKorepanov** [comment]
Hi @Anirudh053, thank you for reporting the issue. I tried a code you described, it seems it works fine on my side. Please find the project attached. As @AskeHolst suggested you need to use Group Visible property to change in runtime. Also make sure that you ever call the method GetTotalDocumentAmountVisibility (CheckDocTotals....) and check int the debugger the value of the SLSetup."Show Document Total Fields" (it must be set true before calling GetTotalDocumentAmountVisibility).
Your issue seems to be a question about existing functionality. Please reach out to Business Central Community Forum to ask questions: [Business Central Forum](https://community.dynamics.com/business/f/dynamics-365-business-central-forum).
[ALProject56.zip](https://github.com/microsoft/AL/files/4830366/ALProject56.zip)

**Comment by Anirudh053** [comment]
Hi @AndreyKorepanov , thankyou for the help, Calling CheckDocTotalFieldsVisibiliy function only in OnAfterGetCurrRecord resolved this issue. Thanks once again for providing the project (ALProject56).
