### ISSUE TITLE
Defining the DataCaptionExpression on a page extension causes the deployment failure if the same property is specified on the base page

### ISSUE THREAD

**Issue by adrogin** [microsoft/AL#5986]
**Describe the bug**
When the property DataCaptionExpression is specified on a page, a pageextension object based on this page cannot override the caption. Package is created successfully, but deployment fails

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a page extension object for any page that has the property DataCaptionExpression (for example, Acc. Schedule Overview).
2. Add the DataCaptionExpression property in the page extension.
3. Compile the package (Ctrl + Shift + B) - success
4. Deploy the package.
5. Deployment fails. Error: "The expression name 'DataCaptionExprCode' can only appear once in the page".

```
pageextension 50101 AccScheduleOverviewExt extends "Acc. Schedule Overview"
{
    DataCaptionExpression = 'My caption';
}
```

**Expected behavior**
Data caption expression specified in the page extension should override the value defined on the page.

**Screenshots**
Debug console output

[2020-06-24 19:03:00.01] Publishing AL application using launch configuration 'Your own server'.
[2020-06-24 19:03:00.30] Targeting server 'http://bc16-gb' and server instance 'BC'.
[2020-06-24 19:03:00.31] Using user name and password authentication. User name used is: '***'.
[2020-06-24 19:03:00.32] Sending request to http://bc16-gb:7049/BC/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2020-06-24 19:03:24.10] The request for path /BC/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: The expression name 'DataCaptionExprCode' can only appear once in the page 'Acc. Schedule Overview'.

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: 15.4.41023.41345
Also reproduced on 16.0.11240.12076

**Comment by AndreyKorepanov** [comment]
[ALProject56.zip](https://github.com/microsoft/AL/files/4830877/ALProject56.zip)

**Comment by developerchristiaens** [comment]
I've encountered the same issue on BC17.
Are they planning to solve this ?

**Comment by atoader** [comment]
We have it in our backlog, but we do not have an ETA at this point. Bugs reported on GitHub are addressed on a best-effort basis. If this is an urgent issue, please open a customer support case.

**Comment by dtacconi** [comment]
This issue is resolved starting from
18.6 and onwards 
19.1 and onwards
All previous major and minor versions does not have this platform enhancement.

**Comment by adrogin** [comment]
Thank you Duilio.
I just noticed your message. This works now, I will close the issue.
