### ISSUE TITLE
Filter Set through filtergroup on dimension field shows up on page.

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#5987]
steps:
in the us container.
create an extension app and extend sales invoice list page and on its onopenpage trigger put filter on dimension value using filtergroup.

![image](https://user-images.githubusercontent.com/38439762/83516279-67487a00-a4f4-11ea-8276-caa69cbb70c8.png)

now  publish the app and go to sales invoice list page.
try to filter on dimension 1 (department code).
It will show the filter set using filtergroup.
![image](https://user-images.githubusercontent.com/38439762/83517016-c490fb00-a4f5-11ea-8868-2074911ff20e.png)

even after chaning the value in the filter field i the page, it keep showing the same filters set through filtergroup.

we have tried with other filter groups, same issue

**Comment by dtkb** [comment]
> The typical usage of different filter groups considers that the field that got filtered at group 2 is not going to be available on the page for further filtering by users

Right. And the problem here is that apparently it **is**. That should not happen: filters set in group 2 should be hidden from the user and applied regardless of their own (group 0) filters.

**Comment by AndreyKorepanov** [comment]
Hi @shashiBssi, I tried your code and it worked as expected on my side. As @StanPesotskiy mentioned the FilterGroups other then 0 can not be changed by user, for details see [https://docs.microsoft.com/en-us/dynamics-nav/filtergroup-function--record-](https://docs.microsoft.com/en-us/dynamics-nav/filtergroup-function--record-). FilterGroup 2 is not intended to be available on the page. How did you manage to make it visible, any specific steps? Could you also provide the BC/AL version you use. Thank you.
[ALProject55.zip](https://github.com/microsoft/AL/files/4841425/ALProject55.zip)

**Comment by shashiBssi** [comment]
Also, when i filter on this field on top of extension applied filter, it is filtering erratically.
For first value it filters good.
2, 3 different value attempts .... it shows all data.

**Comment by shashiBssi** [comment]
![image](https://user-images.githubusercontent.com/38439762/86775539-17ba1880-c075-11ea-883a-0dea76697cad.png)

**Comment by dtkb** [comment]
I can replicate that now that it has been clarified. By revealing filters, adding an empty filter on Department Code, hiding filters, and then revealing filters again, suddenly the filter pane shows ADM|PROD from FilterGroup(2).

**Comment by shashiBssi** [comment]
Also, when i filter on this field on top of extension applied filter, it is filtering erratically.
For first value it filters good.
2, 3 different value attempts .... it shows all data.

create 2 sales invoice
one with department ADM
another with department PROD.

first sales invoice list will show above two invoice.

filter by ADM.... will show one invoice
filter by PROD.. will show one invoice
filter by ADM... will show TWO invoice (situation) ..... should be only one invoice....

**Comment by shashiBssi** [comment]
any update on this @AndreyKorepanov @dtkb

**Comment by dtkb** [comment]
Dunno why you're asking me, since I'm just a random user like you, but what I can say is that usually if there is an update then the devs would post it, and asking "any update" just bothers everyone else with useless emails.

**Comment by shashiBssi** [comment]
Looks like fixed in v17 of BC
