### ISSUE TITLE
Error during upgrade from BC 14 to BC 16.2

### ISSUE THREAD

**Issue by CheetahDK** [microsoft/AL#5988]
Hey

I'm trying to upgrade a BC 14 to BC 16.2 and got stuck at the process, where i need to sync the base application.

I am following this guide  in "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16". 

when running sync-NAVApp

Sync-NAVApp  BC160 -Name "Base Application"

I get the error:

_Sync-NAVApp : The metadata object Page 1752 was not found.
At line:1 char:1

my base and system application versions are 16.2.13509.13779. I don't have any other versions, and i uninstalled/unpublished them from start. 

i found similar issue in this:
https://github.com/microsoft/AL/issues/5840

**Comment by AndreyKorepanov** [comment]
Hi @CheetahDK, thank you for reporting the issue. We need a bit more information about your environment to qualify the issue. Could you please provide us the tenants info: Get-NAVTenant, apps:  Get-NAVAppInfo, upgrade info: Get-NAVDataUpgrade. Thanks.

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by IonesiC** [comment]
Hi,

I am having a similar issue:
upgrading from BC140-RTM to BC160  (16.4.14693.15445)

PS C:\WINDOWS\system32> Sync-NAVApp -ServerInstance BC160 -Name "OnlyTables" -Version 1.0.0.1
Sync-NAVApp : The metadata object Enum 13620 was not found.
At line:1 char:1
+ Sync-NAVApp -ServerInstance BC160 -Name "OnlyTables" -Version 1.0.0.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC160/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manag
   ement.Cmdlets.SyncNavApp

My app list:

Id            : 464d0f8d-a324-4514-b6ac-3c20895fc798
Name          : OnlyTables
Version       : 1.0.0.0
Publisher     : Default publisher
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : b1799bcb-ad56-4ef4-81ca-39d228d5f95b
Name          : MainExt
Version       : 1.0.0.2
Publisher     : Default publisher
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 464d0f8d-a324-4514-b6ac-3c20895fc798
Name          : OnlyTables
Version       : 1.0.0.1
Publisher     : Default publisher
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 16.4.14693.15445
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 16.4.14693.15445
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : c1335042-3002-4257-bf8a-75c898ccb1b8
Name          : Application
Version       : 16.4.14693.15445
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 4b915d7e-c02a-435f-85ab-649086c1e002
Name          : Continia Core
Version       : 2.0.4.1
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 6da8dd2f-e698-461f-9147-8e404244dd85
Name          : Continia Document Capture 365
Version       : 6.0.4.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 14340ba6-5934-4145-8e14-dbf1846fef80
Name          : Continia Payment Management 365
Version       : 1.6.1.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 1dafd1ac-6218-4a6e-9bd7-3dec0f14a072
Name          : Continia Payment Management 365 (DK)
Version       : 1.6.1.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 8d4eab29-8c7f-4b6c-be9a-b7fdfb9da196
Name          : Continia Expense Management 365
Version       : 4.0.4.0
Publisher     : Continia Software
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : ac762be1-e90f-4a72-b519-612a5e3ddc2e
Name          : OIOUBL
Version       : 16.4.14693.15445
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : 644f7e5b-a81c-408a-aaa2-766e655a80a3
Name          : Payment and Reconciliation Formats (DK)
Version       : 16.4.14693.15445
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
Tenant        :

Id            : b1799bcb-ad56-4ef4-81ca-39d228d5f95b
Name          : MainExt
Version       : 1.0.0.3
Publisher     : Default publisher
ExtensionType : ModernDev
Scope         : Global
Tenant        :
