### ISSUE TITLE
feature request: `const var`, i.e. ability to receive arguments by constant reference

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#5989]
We currently can only pass
 * by copy or
 * by modifiable reference (`var`).

***

Passing by value is problematic for things that are expensive to copy and which only need to be observed by the called function. This can range from strings to complete records. Why waste CPU cycles copying?

Passing by modifiable reference if the argument should not be modified is wrong semantically and opens us up to accidents later. It is especially bad if we are designing public API, because then the user will assume they can modify the argument, and/or that doing so has any effect. It is also not much better in internals because there is no way to document it except comments: 'this is passed by `var` for speed', etc. - one of which I have seen in MS base code!

So if we pass by modifiable `var` but say 'you should not modify this, although you _can_...', that is unimpressive and a ticking time bomb until some callee does something with the argument that interferes with anything/everything after the call.

***

Other languages such as C++ that have the option of passing by reference allow to pass by reference-to-constant, i.e. `const&` in that case. This avoids copying the argument by passing by reference but ensures and self-documents that the receiving callee cannot modify it at all. Thus, we get the ideal balance of efficiency and proper API declaration/restriction.

Please, please consider adding something like this to AL, e.g. `const var` in receiving functions.

***

(Perhaps this could also be accompanied by some way to make local values `const` after initialisation, but that seems far less important than preventing copying or accidental modification of references.)

**Comment by AndreyKorepanov** [comment]
Hi @dtkb thank you for reporting the issue. We do not have any work planned for the upcoming release to improve performance in this area. Please go ahead and post this to our Ideas forum at [https://aka.ms/BusinessCentralideas](https://aka.ms/BusinessCentralideas), or vote up the idea if its already there. This will help us allocate time and resources for improving this scenario.

**Comment by dtkb** [comment]
OK, I posted it there: https://experience.dynamics.com/ideas/idea/?ideaid=b937d7b7-20b9-ea11-bf21-0003ff68a8ad
