### ISSUE TITLE
Global Triggers from Codeunit "Global Triggers" not working on certain tables (unless change log is activated on tables)

### ISSUE THREAD

**Issue by JakobAaen** [microsoft/AL#5994]
**Describe the bug**
Global Trigger Events are not fired on specific tables (tested for table 901 and  table 7311) in codeunit "Global Triggers". The events not fired are in this case at least: OnDatabaseModify and OnDatabaseInsert. Subscribers to the events in the "Global Triggers" global database events are not fired when inserting or modifying records in the tables previously mentioned.

If the Change Log is activated and setup for the tables the events subscribers starts firing after the client is restarting. If the eventlog then is deactivated, the client restarted the events stops activating again.

This is not the case for Table 37 where the "Global Triggers" are always fired no matter what.

**To Reproduce**
Insert subscriber event in codeunit:
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Global Triggers", 'OnDatabaseModify', '', false, false)]
local procedure  ModifyGlobalTrigger(RecRef: RecordRef)
begin
    Message('Global Trigger Call')
end;

[EventSubscriber(ObjectType::Codeunit, Codeunit::"Global Triggers", 'OnDatabaseInsert', '', false, false)]
local procedure  InsertGlobalTrigger(RecRef: RecordRef)
begin
    Message('Global Trigger Call')
end;

Activate debugger or just change/insert record in table 901.

Message is not seen.

Activate Change Log and setup for table 901.
Restart Client

Change or insert record in table 901.

Message is seen.

``` AL Code to reproduce the issue ```

**Expected behavior**
Global trigger should always be fired and message should always be seen no mater change log settings.

**Screenshots**

**5. Versions:**
Business Central 16 RTM version (DK)

**Comment by nicolassaleron** [comment]
Hello

Have you registered your table when the event GetDatabaseTableTriggerSetup is raised?
For performance reasons, Global Triggers are only raised for table registered when this event is raised.
