### ISSUE TITLE
"Not serializable" error in controladdin procedures for serializable parameters

### ISSUE THREAD

**Issue by hbaehren** [microsoft/AL#5996]
**Describe the bug**
When using a serializable data type (e.g. System.Array) in a procedure of a controladdin VS Code shows the error message "The parameter 'X' has a type which is not serializable and therefore cannot be used in the given context. AL (AL0430)". 

**To Reproduce**
1. Create a new controladdin
2. Create a procedure within the controladdin with a parameter of type dotnet Array.  

```
controladdin proceduretest
{  
    procedure testArray(testArray: dotnet Array);
}
```

**Expected behavior**
It should be possible to use serializable parameters in procedures of controladdins. This was possible in C/AL.

**Version:**
AL Language - 5.0.288712

**Screenshots:**
![screenshot1](https://user-images.githubusercontent.com/22095707/86107262-e617df00-bac1-11ea-8dbe-be15fe221668.png)
![screenshot2](https://user-images.githubusercontent.com/22095707/86107278-e9ab6600-bac1-11ea-8d55-319f12d4d29a.png)

**Comment by qutreson** [comment]
@hbaehren, thank you for reporting this issue. The validation does not actually verify whether the .NET type is serializable or not. I will mark it as a bug. However, I don't know when we will start working on a fix for it so you should investigate for a workaround in the meanwhile.
