### ISSUE TITLE
Could you relax AS0049 if the object was obsolete in previous versions?

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5997]
**Title**
The access modifier of a codeunit cannot be changed to a less accessible level once published.

**Description**
I was wondering if this rule could be relaxed if in previous versions of the app the codeunit was marked with ObsoleteState = Pending.
Then, changing the access level from Public to Internal would not be so different than deleting and creating a new codeunit.

**Reason for the rule**
This rule would let us move our codeunits from Public (or implicit public) access level to internal as all apps have not get the time to implement this new visibility feature.

**Bad code sample**
Example of what bad code the rule should catch:

- Current Version
```
codeunit 50000 MyCodeunit
{
   Access = Public;
}
```

- Next Version
```
codeunit 50000 MyCodeunit
{
   Access = Internal;
}
```

**Good code sample**
Example of what code should look like:

- Current Version
```
codeunit 50000 MyCodeunit
{
   Access = Public;
   ObsoleteState = Pending;
   ObsoleteReason = 'This codeunit will be internal in the future.';
}
```

- Next Version
```
codeunit 50000 MyCodeunit
{
   Access = Internal;
}
```

**Good and bad practices for fixing the rule**
./.

**Remarks**
./.

**Comment by qutreson** [comment]
Hi @nicolassaleron, which version of the AL extension are you using?

**Comment by nicolassaleron** [comment]
I am using AL Language 5.0.288712

**Comment by qutreson** [comment]
I completely agree with the behavior that you are mentioning here. If the object was obsolete in the base line, it should be allowed to change its accessibility if the object is not obsolete anymore in the current version of the extension. 

I tried reproducing this scenario with the AL extension from the marketplace (i.e. 5.0.288712) and it works as expected. When changing the accessibility of an obsolete codeunit from Public to Internal, the package can be created. When changing the accessibility of a codeunit that is not obsolete, an error diagnostic for AS0049 is raised. 

You can find attached the project I used for testing 
[Gtihub5997.zip](https://github.com/microsoft/AL/files/4851117/Gtihub5997.zip)

Can you provide us with a project that reproduces the issue that you are experiencing on your side?

**Comment by nicolassaleron** [comment]
Indeed, it already works: my fault, I had to restart VSCode to get the rule works correctly with the new app version.
