### ISSUE TITLE
can i add new group in a page(Card) extension

### ISSUE THREAD

**Issue by eat110** [microsoft/AL#5999]
I want add a new group in a page(Card) extension.
i get a error when I use this
pageextension 50100 SalesOrderExt extends "Sales Order"
{
    layout
    {
         addlast(Delivery)
        {
             
        }
     }
}
The control 'Delivery' is not found in the target 'Sales Order'

**Comment by qutreson** [comment]
The AL syntax for it is:

```
addlast(AnchorName) // Existing control on the page
{
       group(NewGroupName) { } // New group
}
```

For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object
