### ISSUE TITLE
Run a Page (without MenuSuite)

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#60]
I'm looking at the sample "TowersOfHanoi".  In this case, it's a complete new app, with new objects.  How do I run something like this while there is no MenuSuite available?  Can I run an object (like the List) straight from VSCode?  Or do I need to do some URL-magic in the web client for this?

**Comment by StanislawStempin** [comment]
You can use the launch.json parameter: 
"startupObjectId": 22
It only supports launching pages for now but more object types will be added in the future.

Also note that both launch.json and app.json have JSON autocompletion with some description for each of the parameters.

**Comment by waldo1001** [comment]
Damn, looked at it, but didn't find it.
thanks so much!
(may be you should add that in the TowerOfHanoi-sample ?)
