### ISSUE TITLE
Accessing a profile defined through Profile object directly gives an error

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#600]
When you define a new Profile object, and then try to access it directly by appending &profile=PROFILENAME in the address bar, there is a blue screen error with the following:

A profile with ID 'PROFILENAME' in System Scope could not be found.

I understand from the error message that this may be by design (apparently the "profile" parameter looks only in the system profiles), but when developing profiles, it should be possible to somehow test them directly. Configuring them in the User Personalization card for the user works, however that's clumsy, as it requires a number of actions every time a profile needs to be tested.

Please, revise this behavior/policy.

**Comment by atoader** [comment]
@vjekob this should be fixed in the Wave 2 2019 release.
