### ISSUE TITLE
Cannot create a docker container with image BC 14 CU13...

### ISSUE THREAD

**Issue by malue1991** [microsoft/AL#6000]
Hey guys,

I do not know why it is not working. I had nver this kind of errors during the creation of a docker container....

This is my script:
![grafik](https://user-images.githubusercontent.com/59683024/86223956-833d4b00-bb88-11ea-8ba0-2c86949202ca.png)

That is the error stack:
![grafik](https://user-images.githubusercontent.com/59683024/86224089-b7187080-bb88-11ea-8b19-e3027766c2c6.png)
It says: Error during the execution of program"docker": No application is assigned to the specified file.

How can I solve this?

Thank you ;)

**Comment by NKarolak** [comment]
Wrong repository. This one is for AL issues, not for the navcontainerhelper issues. Use https://github.com/microsoft/navcontainerhelper/issues
