### ISSUE TITLE
Obsolete Pages not detected when used with RunObject

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6004]
**Describe the bug**
When you mark a page as obsolete, any references to it in actions, through the RunPageLink property, does not raise any warnings.

**To Reproduce**
Just create two pages: A and B. 
Reference B from an action in page A using RunObject. 
Mark B as obsolete.
Nothing happens...

**Expected behavior**
The AL analyzer should show a warning due to a reference to an obsolete object.

**Versions:**
 - AL Language: 5.0.288712
 - Business Central: 16.0.11240.11946 (es)

**Comment by qutreson** [comment]
Hi @salgiza, can you provide a small project reproducing this issue? 

I tried using this with the latest AL extension from the marketplace and from master and the warning was raised as expected:
![image](https://user-images.githubusercontent.com/31541422/86458976-66d71500-bd26-11ea-909a-a89dc5ec8fa5.png)

**Comment by salgiza** [comment]
😮

I thought that it was such a straightforward bug that I didn't consider to create a simple test project. I'll investigate to see if there were any other factors in our project that caused it.

**Comment by salgiza** [comment]
Ok, my bad. I thought we were using RunObject but we actually were launching the page using code. See this example:

![image](https://user-images.githubusercontent.com/6630306/86461984-2332da00-bd2b-11ea-85d5-576df3e06307.png)
 
The action that uses RunObject does raise the error, but the page var declaration in the first action does not.

**Comment by dtkb** [comment]
So does this affect any obsolete pages used in code, or just in an `OnAction()` trigger?

**Comment by qutreson** [comment]
Obsolete symbols should be reported by the AL compiler when used in code. As far as we know, this bug only refers to the scenario mentioned above. If you know about other ones, please open a new issue for them.

**Comment by salgiza** [comment]
Just for reference, as the ticket was closed by the bot due to its date: I checked using the current version of the AL Extension (8.3.570094) and I can confirm that the issue has been fixed.
