### ISSUE TITLE
AS0068: The target table of table extension 'xxx' has changed from 'MISSING' to 'Some Table'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6006]
**Title**
App Source Cop raises AS0068 on tableextension even if nothing changed between two versions.

**Description**
We run into a problem with rule AS0068. I first get this problem locally but ignored the error. Now, apps fail validation on App Source because of this problem.

The error message is :
```
 src/tableextension/MySalespersonPurchaser.TableExt.al(1,24): error AS0068: The target table of table extension 'My SalespersonPurchaser' has changed from 'MISSING' to 'Salesperson/Purchaser'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
```

What is strange is the **MISSING** there.
Most strange is that the table extension was already there in the previous version of the app with the same name, the same ID and the same extended table.

I have not been able to reproduce this issue with a quick example but I can share a project in private message.

**Reason for the rule**
./.

**Bad code sample**
./.

**Good code sample**
./.

**Good and bad practices for fixing the rule**
./.

**Remarks**
./.

**Comment by qutreson** [comment]
Hi @nicolassaleron, this looks like an issue resolving the extension in which the base table was defined in the previous version.

In your previous version of the extension, how is the dependency for the extension that declared the table object? 
In your current version of the extension, how is the dependency for the extension that declares the table object? 
Has the table been moved from one extension to another?

Can you try to simplify your extensions and provide us with a workspace that reproduces the issue?

**Comment by nicolassaleron** [comment]
Hi, I tried to understand but I am unable to reproduce the issue even if I simplify my project.

What I can tell you:
* the dependency concerns the ```Base Application```
* in previous version, the dependency has been declared both with the ```dependencies``` property AND ```application``` property in app.json.
* in the new version, the dependency is only declared with the ```application``` property.

**Comment by atoader** [comment]
Hi! The issue should be fixed in the latest developer preview. Could you confirm?

**Comment by nicolassaleron** [comment]
I confirm, it works

**Comment by Devaim1** [comment]
I'm getting this same error from a tableextension that has not changed in almost two years, except it's now '__MissingTypeSymbol__' rather than 'MISSING'.
The only thing that changed in my team's project repository is the application tag in app.json, from 23.0.0.0 to 23.3.0.0.

**Comment by iti-mikolaj-sledz** [comment]
@Devaim1 Did you find a solution?
