### ISSUE TITLE
Tile in a Cue Group ist not Updated, if SourceTable is Temporary

### ISSUE THREAD

**Issue by MarkDE87** [microsoft/AL#6007]
- AL Extension Version: 5.0.288712
- Server Version: 16.0.11233.12061

I have a Issue on Business central. I create a CardPard and add it to the Customer Card Page via Extension.
In the CardPard is a Integer Variable declared. I show this variable as field and as Tile. My Problem if the variable change the value, the Tile is not updated.  The normal field show the changed value. Look at the Screenshot. If i change the Property of the Cardpart to SourceTableTemporary to = false then work the system correctly.

Example .al Files with the Issue:
[PageEXT50300.zip](https://github.com/microsoft/AL/files/4878137/PageEXT50300.zip)

![BC_TileBug_20020706_001](https://user-images.githubusercontent.com/36551610/86581265-2a9ef100-bf80-11ea-8f14-711d6a598a97.png)

**Comment by dtkb** [comment]
probably somehow due to the temporary table having no records, and BC deciding it doesn't need to display any values, even variables.

usually we use a dummy cue record table, and ensure it contains at least one record, even if that's just a blank primary key and nothing further.

**Comment by MarkDE87** [comment]
This is more or less a good workaround for me. This may be a temporary bug fix.
The normal field shows the value correctly and whether it should be displayed as a tile or a normal field should not matter for BC. If I change the style at runtime, this also works for a temporary table. Only the value is not updated.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
