### ISSUE TITLE
Issue parsing content for few entities that accept stream

### ISSUE THREAD

**Issue by lekhashreep** [microsoft/AL#6008]
I am trying to send content as binary using apache olingo library. The apache olingo library constructs in an OData format as key/value pairs. However, this body is not parsed properly by the Business Central APIs. In the UI it says, preview not available.

This is how the olingo library constructs it:
{"@odata.type":"#Microsoft.NAV.attachments","content@odata.type":"Binary","content":"LS1mb29fYmFyX2Jheg0KQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PVVURi04DQoNCnsNCiAgIm5hbWUiOiAibXlPYmplY3QxLnR4dCIsDQogICJwYXJlbnRzIjogWw0KICAiMEFCTnR1X0JRbzFWNlVrOVBWQSJdDQp9DQoNCi0tZm9vX2Jhcl9iYXoNCkNvbnRlbnQtVHlwZTogdGV4dC9wbGFpbg0KDQpUaGlzIGlzIGZvciB0ZXN0DQotLWZvb19iYXJfYmF6LS0="}

**Comment by qutreson** [comment]
Please follow the template and open a new issue containing adequate information to reproduce the problem you are facing (project reproducing the issue, AL extension version, Business Central version, etc).
