### ISSUE TITLE
Page Customizations are not applied with the profile

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#601]
I have defined these:

pagecustomization 70000001 CustomerListCust customizes "Customer List"
{
    layout
    {
        modify(Name)
        {
            Visible = false;
        }
    }
}

pagecustomization 70000002 CustomerCardCust customizes "Customer Card"
{
    layout
    {
        modify(Name)
        {
            Visible = false;
        }
    }
    actions
    {
        modify(Statistics)
        {
            Visible = false;
        }
    }
}

profile "NewProfile"
{
    Description = 'This is a new profile';
    RoleCenter = 9008;
    Customizations = CustomerListCust, CustomerCardCust;
}

However, when I test this, the customizations are not applied in either of the customized pages.

I did select the profile in the User Personalization, and the correct profile did load.

**Comment by DominikDitoIvosevic** [comment]
@vjekob Could you try reproing this on September update?
We can't repro this

**Comment by yandko** [comment]
@StanislawStempin, @vjekob  I have the same issue on the following builds:

NAV2018 on premise build
    "version": "11.0.19394.0",
    "locale": "W1"
AL Language VCODE Extension
     "version": 0.12.15355

my code is 

pagecustomization ChartofAccountCust customizes "Chart of Accounts"
{
    layout
    {
        modify("Gen. Posting Type")
        {
            Visible = false;
        }
        modify("Gen. Bus. Posting Group")
        {
            Visible = false;
        }
        
    }

}

profile "MAIN"
{
    Description = 'MAIN';
    RoleCenter = 50000;
    Customizations = ChartofAccountCust;
}
