### ISSUE TITLE
OnInit

### ISSUE THREAD

**Issue by fastudio** [microsoft/AL#6012]
Hi
I am in trouble trying to execute something before the OnOpenPage of standard Pages, please make accessible OnInit

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
