### ISSUE TITLE
App does not compile when it uses an interface from another extension with codeunit parameter

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#6013]
**Describe the bug**
An app does not compile when it implements a function with a codeunit parameter of an interface from another extension. 

**To Reproduce**
Steps and to reproduce the behavior:
(See sample in the attachments)

1. Create a Base Extension with an interface. The interface should contain a function with a codeunit parameter.

    ![image](https://user-images.githubusercontent.com/48217797/86889124-8a6dd700-c0fb-11ea-9a28-4d0fcd3c28c5.png)

2. Create a Second Extension with the Base Extension as dependency. 

3. Create a Codeunit in the Second Extension implementing the interface of the Base Extension

    ![image](https://user-images.githubusercontent.com/48217797/86889178-a1142e00-c0fb-11ea-95ce-4fe078079a5c.png)

4. Save both Extensions to the same Workspace and try to compile it. The following error occurs:

    ![image](https://user-images.githubusercontent.com/48217797/86889236-b8531b80-c0fb-11ea-90d3-af6deaf382e6.png)

**Note: Both Extensions compile individually when they're not in the same workspace.**

**Expected behavior**
All Extensions should compile

**Screenshots**
(See "To Reproduce" section + sample in the attachments

**5. Versions:**

 - AL Language: 
   ![image](https://user-images.githubusercontent.com/48217797/86889447-09630f80-c0fc-11ea-8553-1ecdc1f1fc74.png)

 - Business Central:
   ![image](https://user-images.githubusercontent.com/48217797/86889558-39aaae00-c0fc-11ea-9138-8200c409722f.png)
[Sample Intefaces.zip](https://github.com/microsoft/AL/files/4889077/Sample.Intefaces.zip)

**Comment by qutreson** [comment]
@daansaveyn, thank you for reporting this issue, I can reproduce it as well.
