### ISSUE TITLE
ClientType causes Null Reference Exception

### ISSUE THREAD

**Issue by MarkusWinBI** [microsoft/AL#6014]
**Describe the bug**
Using the ClientType for making client-specific modification causes a null reference exception
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

**To Reproduce**
Steps and to reproduce the behavior:
case ClientType of
            ClientType::Phone:
                IsPhoneClient := true;
            else
                IsPhoneClient := false;
        end;

**Expected behavior**
Using ClientType is not causing a NullReference Exception

**5. Versions:**
 - AL Language: 3.0.150570
 - Business Central: 14.0.42627.0

**Comment by dtkb** [comment]
You need to use `CurrentClientType`. `ClientType` is just the option type, not an instance witha  value.

Sure, it should say this instead of crashing the compiler, but it's still invalid code either way.

**Comment by MarkusWinBI** [comment]
> 
> 
> You need to check `case CurrentClientType`. The symbol `ClientType` is just the option type, containing available values, not an instance with a current value that can be checked.
> 
> Sure, it should say this instead of crashing the compiler, but it's still invalid code either way.

Then can you give advice how to use the client Type option?

**Comment by dtkb** [comment]
I just said how.

```
case CurrentClientType of
  ClientType::Phone:
    IsPhoneClient := true;

  else
    IsPhoneClient := false;
end;
```

simplified:

`IsPhoneClient := CurrentClientType = ClientType::Phone;`

**Comment by MarkusWinBI** [comment]
As Phone client is just showing the first nonsense fields of a list I want to make fields invisible the customer has no use of in his use case (like the status

> 
> 
> I just said how.
> 
> ```
> case CurrentClientType of
>   ClientType::Phone:
>     IsPhoneClient := true;
> 
>   else
>     IsPhoneClient := false;
> end;
> ```
> 
> simplified:
> 
> `IsPhoneClient := CurrentClientType = ClientType::Phone;`

Ooooooh! Just tooo simple! :-)
Thanks very much!

**Comment by MarkusWinBI** [comment]
The Phoneclient is just ignoring it. It's not interested in "Visible = false", it's always showing the first five columns of the page, no matter if they are visible or not. But that's something different.

**Comment by dtkb** [comment]
Ugh, that sounds unfortunate. I'm glad to help with the easy bit but know nothing about that ;-)
