### ISSUE TITLE
Processing only report is showing: 'Report is being rendered'

### ISSUE THREAD

**Issue by MaartenGerritsen** [microsoft/AL#6015]
**Describe the bug**

In a report with the following properties:
ProcessingOnly = true;
ShowPrintStatus = false;
there is still a window shown saying:

_Working on it...
The report is being rendered. This can take a while, depending on the number of rows that have been generated._

But there is nothing to render!

**To Reproduce**
Steps and to reproduce the behavior:

Create a report like:
```
report 50100 "Test"
{
    Caption = 'Test';
    ProcessingOnly = true;
    ShowPrintStatus = false;

    dataset
    {
    }

    trigger OnPostReport()
    begin
        Sleep(5000);
        Message('Ready!');
    end;
}
```

If you program your own dialog, then the 'rendering' message is not shown.

unless an own dialog is programmed, like:
```
    trigger OnPostReport()
    var
        i: Integer;
        Window: Dialog;
    begin
        Window.Open('test #1#############');
        for i := 1 to 5 do begin
            sleep(1000);
            Window.Update(1, i);
        end;
        Window.Close();
        Message('Ready!');
    end;
```

**Expected behavior**
Another message saying something like: processing. 
Or better, a progress bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/25688441/86900796-1556cd80-c10c-11ea-8121-b099a8b8e7a3.png)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
