### ISSUE TITLE
[Feature Request] LASTERROROBJECT As String

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#6017]
If there is an error with a web service call, the information from the last error text or callstack is not sufficient. If the web service call is executed in a background session, it is nearly impossible to find the error.
LASTERROROBJECT provides all information needed, but is not available in the SaaS Scope because of return type DOTNET.

It would be great if we could read the Last Error Object as text in both scopes to be able to log this.

**Comment by qutreson** [comment]
@ChrisBlankDe doesn't [GetLastErrorText](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-getlasterrortext-method) covers the same scenario?

**Comment by ChrisBlankDe** [comment]
Especially when it comes to http communication the content of getLastErrorText is quite worthless.
Here only the .Net error really tells you what is not working.

In the meantime Microsoft has changed a lot of things and we can also access the .net error. So a separate function is no longer needed.

See the following code how we can solved this today:

```
    trigger OnRun()
    begin
        if not TryRunTest() then begin
            ShowErrorInfo();
        end;
    end;

    [TryFunction]
    local procedure TryRunTest()
    var
        client: HttpClient;
        repsonse: HttpResponseMessage;
    begin
        client.Get('http://not.existing/domain', repsonse);
    end;

    local procedure ShowErrorInfo()
    var
        DotNetExceptionHandler: Codeunit "DotNet Exception Handler";
    begin
        Message('LastErrorCode: %1', GetLastErrorCode); //LastErrorCode: HttpRequest:HttpRequest
        Message('LastErrorText: %1', GetLastErrorText); //LastErrorText: An error occurred while sending the request. <-- too generic
        DotNetExceptionHandler.Collect();
        message('DotnetMessage: %1', DotNetExceptionHandler.GetMessage()); //DotnetMessage: The remote name could not be resolved: 'not.existing' <-- specific enough
    end;
```
