### ISSUE TITLE
VS Generate permission set problem with latest version of BC 16.2

### ISSUE THREAD

**Issue by vpacker** [microsoft/AL#6018]
I have an issue with VS code not generating the proper permissions sets that allow me to deploy my extension into the production environment.My Extension works fine within the sandbox but when I try to deploy into production it comes back with the error regards
for example.  
Package validation failed due to the following error(s): (1,13): error PTE0004: Table '70000' is missing a matching permission set.
(1,13): error PTE0004: Table '70001' is missing a matching permission set.
(1,13): error PTE0004: Table '70002' is missing a matching permission set.
(1,13): error PTE0004: Table '70003' is missing a matching permission set.
(1,13): error PTE0004: Table '70004' is missing a matching permission set.
(1,13): error PTE0004: Table '70005' is missing a matching permission set.
(1,13): error PTE0004: Table '70006' is missing a matching permission set. - Job Id : eba2033f-c9cf-45b1-af79-6cfbeac56533

I'm aware of what I need to do ie import the generated permissions sets as per VS generation but this does not work the schema is invalid its missing the scope attribute ie the generated VS schema is invalid when I try to import the generated permission sets into the Production environment. I tried building my own permission sets from the sandbox and was able to export and import this into production but I still cannot deploy my extension I get the same error.I have no idea what  the problem is or what to do next and why this is occurring as I have followed all the suggestions to fix the issue but nothing seems to work.
I'm on the latest issue of BC version 16.2. I checked I have the latest version of AL code v5.0.288712 
Can somebody please enlighten me what I am missing here 

Thanks   

- AL Extension Version: 

- Server Version:

**Comment by qutreson** [comment]
@vpacker what happens when you try to run the PerTenantExtension analyzer in VS Code? Are these errors also reported?

You can have a look at the following docs in order to set the analyzer locally:
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop-pte0004-tablesmusthavepermissionsetdefined

Did you try using the command for building permission sets in VS Code?
![image](https://user-images.githubusercontent.com/31541422/87021407-7a2a2a80-c1d5-11ea-953a-5be9b1cc988e.png)


Can you provide us with a project containing both the AL code and the permission set that reproduces the issue?

**Comment by vpacker** [comment]
Hi 
 Thanks for your prompt reply. I thought about my issue and it could be an issue in that my extension uses table numbers in the 70000 range I will try a test tomorrow using 50000 range to see if this is the problem. Despite this there is still an issue with the VS Al using the generate permission set containing current objects it generates an XML that can’t be imported into BC properly so basically it’s useless? The only way I could generate a valid permission set was to manually do it in the sandbox and then export and import into production, but like I said this still did not help as trying to import my extensions fails complaining about my extension tables not having the permission set even though I imported the permission set from my sandbox. This is why I suspect there maybe a problem with me not using 50000 range I will confirm with a test tomorrow. If this does not work then I have no idea what it keeps complaining about as it makes no sense. How are other people deploying there extension in BC Saas environment. 
All my extension works fine in the sandbox this is not my problem just trying to deploy to the product is a mission in frustration really!. I suggest you try the VS Al command to generate permission set current objects and see if you are able to import into BC if you can please advise how.

Thanks

**Comment by vpacker** [comment]
Hi 

 

After a few trial and errors I figured out the scenario of what is happening as at the time it was not so obvious to me. Firstly I can confirm that the 

Generate Extension Permission sets via AL command does actually work. What was not obvious to me is how to use it. I was under the impression that

I needed to manually import this into my permission sets in my sandbox this is not correct, what actual happens is via VS the existence of the permissions

Set file created in my workspace is automatically creating the permission set within the sandbox for me with a  type called extension.  I then used this to import into

the BC production environment permission set and then after this I could successfully deploy my extension to the Production. 

What is a little strange is that when you upload the permission set exported from the sandbox it has a  type extension becomes after import into BC Production it’s type becomes

user defined permission set??

I can confirm that my original query regards AL generate permission not working was incorrect although a little confusing to say the least.

 

Thanks

**Comment by qutreson** [comment]
@vpacker I am closing this issue as it appears that the command for generating permission sets is behaving as expected. If you think that our [documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets#to-export-permission-sets-using-visual-studio-code) about it could be a bit more detailed, do not hesitate to report issues on the docs with the improvements that you would like to see.
