### ISSUE TITLE
Epic fail (!) the BC16.3 update has been carried out on some & postponed on other dbs.  Help!

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#6019]
So yesterday (Weds) early morning I received emails to say that some of our environments have been upgraded to 16.3 .. this means that our Apps are all uninstalled and I have to reinstall them (far from ideal but not insurmountable).

I then proceeded to uninstall 16.2 and I downloaded & installed 16.3 plus fixed the bug (at least I think/hope it's a bug) where I have to complete the Web Client Base URL (surely this could default in) as I do every month now due to the frequency of the updates from you (**sigh**).

After developing and testing in 16.3 for a little while I realise it just isn't fit for purpose.  Attempting to access standard items such as Purchase Order, Purchase Invoice, Sales Order etc. the web browser just didn't respond so I restarted it .. without any change .. so I restarted the service and then found it stopped automatically / refused to restart.

So I thought I know I'll check the BC admin center and I notice this:

![image](https://user-images.githubusercontent.com/57717503/87056582-bb363500-c1fd-11ea-87ab-7ca82eec239a.png)

Hmm...is this because someone has noticed similar issues to those I have?  

So I then throw 16.3 away and (re)download 16.2 and install it again and then have to reload my apps / recreate data etc.  None of this is what I want to be doing (or really have the time and patience for) but I don't have any choice now do I?

I've developed software for NAV (now BC) for 24 years and I honestly can't remember such an **epic fail** from you guys .. I hope someone there is suitable embarrased, chastised and this doesn't happen again.  In the 'new world' I already have plenty of MS bugs that I simply have to fix myself or code around (as you don't fix them or even respond to the posts that you have forced me to enter in the 'ideas' section (as they are closed if entered anywhere else)).  I really miss the Company: Navision which really always did an awesome job!!

Worst still (apart from my own frustrations) I now have all the Pre-Sales staff in the Company unable to demo our solution because you have automatically upgraded their environments to v16.3 (and uninstalled the Apps we are developing) and all our other environments are stuck at v16.2.

I'm posting this in the real hope that you will reply and tell me how/why this has been allowed to happen and what you are doing to ensure it doesn't happen again?  

Further, that you will give an idea of these problems will be solved & when all our environments will be upgraded to 16.3.

Thank you.

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/

**Comment by jglathe** [comment]
I would say this is debatable, if you care to read the opening post. All customers are updated, but the developer can't because of... what? This is really destructive. Customers can't be supported because developer environments are stuck on an old version for.. what reason? This is a total loss of control. You should be sued.

**Comment by atoader** [comment]
Please read the README of this repository. This will help you find the best place for your issues. Thank you!
