### ISSUE TITLE
GB,CA,US DB version list and modified Tag in August Db

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#602]
Hi,

In the august update their are three databases installed with names GB,CA,US. In all these databases the version list and modified tags are not correct according to the usual demo database see below:
![image](https://user-images.githubusercontent.com/26792519/30048286-228a9b22-9233-11e7-940c-43fbe1223f54.png)

Please suggest us.

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
Hi Varun,
Could you describe if/what problems does this cause for you? The version list update is currently not done in SaaS databases by design (which is what we make available on the Dev Preview images).

**Comment by bachii1010** [comment]
Hi Stains,

we have only installed the august update after that when we open the databases we see that there is no version list and the modified tag is true.

**Comment by StanislawStempin** [comment]
Yes, but what is the problem with that?

**Comment by bachii1010** [comment]
Hi,

Was just checking if this is a bug or it is standard

**Comment by StanislawStempin** [comment]
This is intended for now, unless we hear someone running into problems because of this change.
