### ISSUE TITLE
From options to enum for tables 169 and 210

### ISSUE THREAD

**Issue by adinfo-theo** [microsoft/AL#6020]
I've a problem in tables "Job Ledger Entry" and "Job journal line" for **type field**, i can't extend it while it's an option.
is it possible to enumerate them?

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
