### ISSUE TITLE
GetAllExtensionDeploymentStatusEntries

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6023]
The procedure [GetAllExtensionDeploymentStatusEntries](https://github.com/microsoft/ALAppExtensions/blob/6bfef02822bf9755350161ba69058920001f5224/Modules/System/Extension%20Management/src/ExtensionManagement.Codeunit.al#L108) is publicly available but the first and only argument is Record "NAV App Tenant Operation" and this table cannot be used for Cloud development.

The procedure should be marked with Scope(OnPrem)
or
The table NAV App Tenant Operation should be accessible in Cloud development
or
Another signature should be available to make it usable in Cloud development.

**Comment by crraita** [comment]
That's a good suggestion. I am fixing it right now and the fix will be available starting with version 17.0. Is this timeline good enough, @nicolassaleron ?

**Comment by nicolassaleron** [comment]
Thank you for the update !
Depending on the decision made the timeline is fine (if solution 2 or 3 is chosen), or do not matter (if solution 1 is chosen :) )

**Comment by crraita** [comment]
It is option 3 that I have implemented for Wave 2. We will use a different table that the PTE developers have access to.
Thank you for the feedback !
