### ISSUE TITLE
 Codeunit 10 - Change .NET Interop to native functions

### ISSUE THREAD

**Issue by rodotto** [microsoft/AL#6024]
Codeunit 10 currently contains functions for encoding and decoding HTML. These are based on .NET Interop. Is it planned to provide the corresponding functions as native functions so that they can be developed without including .NET Interop?

**Comment by qutreson** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
