### ISSUE TITLE
Hide items in search list (tell me)

### ISSUE THREAD

**Issue by garyguo1986** [microsoft/AL#6026]
Searching pages or reports with tell me is a very useful function in business central. but sometimes I need to hide items in the search list. for example, our company doesn't use production orders anymore. but it still can be found in the search list. it makes some confusion for end-users. 
so is there any way to hide standard pages or items in the search list?

**Comment by dtkb** [comment]
just set `UsageCategory = None`

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
