### ISSUE TITLE
Repeating bug in word layout

### ISSUE THREAD

**Issue by LukasK7** [microsoft/AL#6028]
**Describe the bug**
Almost every time the repeating does not work when creating word layout. It only works if the text on which the repeating is placed is in the table.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a report.
2. Open word layout.
3. Add Repeating.
4. Import layout to BC.

**Expected behavior**

I expected to see repeated report fields in the layout. Instead of that, the layout is empty.

**Screenshots**

First of all, I created a word layout. I added 2 fields from the report and applied repeating on both of them. 
![image](https://user-images.githubusercontent.com/58076001/87312668-88f04480-c529-11ea-86f1-2453a4d1166f.png)

After that I run my report but fields that were not in the table are empty.
![image](https://user-images.githubusercontent.com/58076001/87312791-b6d58900-c529-11ea-9754-ed3a1ab7c884.png)

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: 16.3.14085.14238

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
