### ISSUE TITLE
Possible overflow when creating Movement From Movementworksheet

### ISSUE THREAD

**Issue by iVervast** [microsoft/AL#6030]
**Describe the bug**
In certain cases we receive an overflow error when creating a pick from the Movement worksheet. Works in English, in dutch (NLB) we receive the error.

Code:
codeunit 7312 "Create Pick"

local procedure GetMessageForUnhandledQtyDueToBin(BinIsForPick: Boolean; BinIsForReplenishment: Boolean; IsMoveWksh: Boolean; AvailableQtyBase: Decimal; BinCode: Code[20]): Text[100]
    begin
        if AvailableQtyBase <= 0 then
            exit('');
        if not BinIsForPick and not IsMoveWksh then
            _exit(StrSubstNo(BinIsNotForPickTxt, BinCode));_
        if not BinIsForReplenishment and IsMoveWksh then
            _exit(StrSubstNo(BinIsForReceiveOrShipTxt, BinCode));_
    end;

The Returned message is sometimes longer than 100 Characters and overflow is caused.

**To Reproduce**
Steps and to reproduce the behavior:
LocationFullWMS
Create Fixed Bin for Item with min/max.
Only create inventory for Item on Bin which allows no actions (not Ship, Not Receive, Not Pick, Not Putaway)
Calculate The movement worksheet.
Set application To NLB (Dutch).
Will result in overflow error when creating movement.

**Expected behavior**
No Error.
Movement should be created.

**Screenshots**

**5. Versions:**

AL Language: 5.0.288712
Business Central: 16.2.13509.13779

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
