### ISSUE TITLE
Date Header in the HTTPHeaders object

### ISSUE THREAD

**Issue by Joriek** [microsoft/AL#6031]
**Describe the bug**
When you add the the "Date" header (in ISO-8601) using the HTTPHeaders object you get an error message that the date is invalid.
When you format a date and time to the following string <YYYY-MM-DDTHH:mm:ss.sssZ> and try to add it it will give a runtime error.

**To Reproduce**

``` 
FormattedDate := format(Today(), 0, '<Year4>-<Month,2>-<Day,2>') + 'T' + DelChr(Format(Time()), '=', DelChr(Format(Time()), '=', '0123456789:')) + 'Z'; //2020-07-14T08:17:00Z
        HttpHeaders.add('Date', FormattedDate);
 ```

**Expected behavior**
This should just add the header.

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: 16.3.14085.14287

**Comment by atoader** [comment]
Have you tried using TryAddWithoutValidation  instead of Add?

**Comment by Joriek** [comment]
@atoader Thank you, this works. Is this a new function or was it there already?

**Comment by thpeder** [comment]
I'm glad to hear that it worked, It has been in the code for more than a year.
if you find any bugs, feel free to open a new issue.
