### ISSUE TITLE
running a Query object against a datapercompany=false table crashes the web client

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/AL#6032]
To replicate, create a query object against a datapercompany=false table (such as a system table). VS Code will compile the app but when the query is run, it will crash the web client. A Windows Event Log entry is appended saying that you cannot run queries against datapercompany=false tables. 

This is something that should be caught upfront by the AL compiler and not as a runtime error. 

- AL Extension Version: 5.0.288712

- Server Version:  NA Business Central 16.2 (Platform 16.0.13440.13772 + Application 16.2.13779.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
