### ISSUE TITLE
Table 5406 "Prod. Order Line" - procedure GetStartingEndingDateAndTime

### ISSUE THREAD

**Issue by StijnBt** [microsoft/AL#6034]
Used docker container: mcr.microsoft.com/businesscentral/onprem:16.2.13509.13779

```
[Scope('OnPrem')]
procedure GetStartingEndingDateAndTime(var StartingTime: Time; var StartingDate: Date; var EndingTime: Time; var EndingDate: Date)
  begin
    StartingTime := DT2Time("Starting Date-Time");
    StartingDate := DT2Date("Starting Date-Time");
    EndingTime := DT2Time("Ending Date-Time");
    EndingDate := DT2Date("Ending Date-Time");
  end;
```

![image](https://user-images.githubusercontent.com/37275572/87475172-950cfc80-c624-11ea-93c7-a8e65e0b30ac.png)

Strangely it does not seem protected an I am working in an OnPrem environment. So the error seems off.

**Comment by qutreson** [comment]
@StijnBt what is the compilation target specified in your app.json?

See: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Appjson

**Comment by StijnBt** [comment]
Correct, it was actually missing completely from the app.json and then it defaults to "Cloud" apparently.
So adding it was indeed the solution.
Thanks!

```
"target": "OnPrem",
```
