### ISSUE TITLE
Issue setting PromotedActionCategories property on multiple extensions

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/AL#6036]
Hi,

I'm having an issue with the PromotedActionCategories property on multiple extensions.

I need to have different promoted action categories in the same page, in multiple extensions (I believe this behavior will also happens with different partner extensions promoting action categories).

Example scenario:

Please consider the demo project in this link: https://github.com/ricardopaiva/ALActionsDemo

I'm extending the Customer List page.
The standard PromotedActionsCategories is:
PromotedActionCategories = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate';

In ALDemo1 I added the ALDemo1 category in position 9:
PromotedActionCategories = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,**ALDemo1**';

In ALDemo2 I added the ALDemo2 category in position 9:
PromotedActionCategories = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,**ALDemo2**';

In ALDemo3 I added the ALDemo3 category in position 10 (and named the Category9 as ALDemo):
PromotedActionCategories = 'New,Process,Report,Approve,New Document,Request Approval,Customer,Navigate,**ALDemo,ALDemo3**';

The result is:
- Category9 was named ALDemo2. Ok, there's a conflict between ALDemo1 and ALDemo2 extensions so it could be named any of the two. Inside that category we have both ALDemo1 and ALDemo2 actions.

![image](https://user-images.githubusercontent.com/4399140/87555305-2de75a80-c6ad-11ea-9ae9-1ce2716f0e35.png)

- Category10 wasn't named at all. It should have been named ALDemo3. But it has the ALDemo3 action inside.

![image](https://user-images.githubusercontent.com/4399140/87555442-5bcc9f00-c6ad-11ea-98db-04b2fd27834b.png)

I've done this tests on BC v15.4 (US localization).
 - Microsoft_Base Application_15.4.41023.43755
 - Microsoft_System Application_15.4.41023.43755
 - Microsoft_System_15.0.40939.43706

Please let me hear your thoughts on this. Is this a bug? What should be the expected behavior?

Thanks

**Comment by ricardopaiva** [comment]
Hi,

After getting this issue moved from the ALAppExtensions to the AL repo, I’ve searched and found these similar issues.
https://github.com/microsoft/AL/issues/1398
https://github.com/microsoft/AL/issues/4580

Any suggestion on how to handle it?

Thanks

**Comment by qutreson** [comment]
Closing this issue as there have been investments in defining a new syntax that captures more explicitly the structure of the action bar, see https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-promoted-actions. If you are still experiencing issues using the new syntax, please create a new issue with updated repro steps.
