### ISSUE TITLE
AA0150: Parameter 'Handled' is declared by reference but never changed in method 'OnXXX'.

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6038]
**Title**
The rule AA0150 warns on events. As events have no body, this rule should ignore them.

**Description**
Rule AA0150  raises a warning in any case, even if the procedure is a BusinessEvent. Please note that it does not raise a warning on IntegrationEvent.

**Reason for the rule**
./.

**Bad code sample**
Example of what bad code the rule should catch:

```
    local procedure IAmDoingNothingWithHandled(var Handled: Boolean)
    begin
    end;
```

**Good code sample**
Example of what code should look like:

```
    [BusinessEvent(false)]
    local procedure OnBeforeDoingSomething(var Handled: Boolean)
    begin
    end;
```

**Good and bad practices for fixing the rule**
BusinessEvents should be ignored by this rule, like IntegrationEvents.

**Remarks**
Tested on AL Language v6.0.302409

**Comment by fvet** [comment]
Please also include the InternalEvents.

![image](https://user-images.githubusercontent.com/25268332/89192689-2547bd00-d5a5-11ea-9f35-00283836e9f6.png)

**Comment by MarcHansenMicrosoft** [comment]
internal bug loged

**Comment by ChristopherDedominici** [comment]
This issue has been fixed. The fix will be available in a near future release.
