### ISSUE TITLE
AA0240, strange behavior if the target trans-unit is a space

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6039]
**Title**
Rule AA0240 seems to detect e-mail or phone number is a trans-unit containing a space and only a space.

**Description**
The following warning is raised by rule AA0240.
```
AppSourceCop.json(1,1): warning AA0240: The Translations\MyApp.g.fr-FR.xlf 'Enum 3159656570 - EnumValue 1371923692 - Property 3830149458:target' must not be contain Email or Phone No.
```

In fact, the trans-unit is like below.
```xml
<trans-unit id="Enum 3159656570 - EnumValue 1371923692 - Property 3830149458" size-unit="char" translate="yes" xml:space="preserve">
  <source> </source>
  <target state="final"> </target>
  <note from="Developer" annotates="general" priority="2"></note>
  <note from="Xliff Generator" annotates="general" priority="3">Enum My Enum - EnumValue   - Property caption</note>
</trans-unit>
```

**Reason for the rule**
./.

**Bad code sample**
./.

**Good code sample**
./.

**Good and bad practices for fixing the rule**
I think the problem comes the fact the translation is just a space character. We are maybe doing wrong but we still use on some enums a space as the name of the default value of enum, like we did with options.

**Remarks**
AL Language v6.0.302409

**Comment by Jeeve65** [comment]
I get this same issue if the translated target is ' - '  (space dash space)

`<trans-unit id="Codeunit 2901867071 - NamedType 3380895707" size-unit="char" translate="yes" xml:space="preserve">`
`  <source> - </source>`
`  <target> - </target>`
`  <note from="Developer" annotates="general" priority="2"></note>`
`  <note from="Xliff Generator" annotates="general" priority="3">Codeunit OBZ Charts-Sales - NamedType NumberNameSeparatorTxt</note>`
`</trans-unit>`

**Comment by TKapitan** [comment]
Still not resolved...

**Comment by PaulIvan** [comment]
I am closing this issue because it has been resolved, please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.
