### ISSUE TITLE
Record Ref hangs on insert.

### ISSUE THREAD

**Issue by moizsoloman** [microsoft/AL#6043]
Hi Everyone. 

I've recently started getting a new problem in Business central.
I'm not able to insert using Record Ref any more it was working about a month ago when I first created the extension, but now the environment just hangs.

below is my code. copied from  
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-insert-method

```
RecRef.Open(3);
MyFieldRef := RecRef.FIELD(1);
RecRef.Init();
MyFieldRef.Value('30D');
RecRef.Insert(true);
```

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by moizsoloman** [comment]
> This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.
> 
> To get help for your question please use one of the following resources:
> [Business Central Community](https://community.dynamics.com/business/f/758)
> [mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
> [Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This is a bug not a code correction request
