### ISSUE TITLE
AL0190 Constant value '2359T' is outside the range for a Time

### ISSUE THREAD

**Issue by martonnagy** [microsoft/AL#6044]
**Describe the bug**
When using CreateDateTime the compiler doesn't accept any other value than 0T if I'm trying to specify the "Time" value explicitly

**To Reproduce**
1. Create the following function
```
procedure GetMaxDateTime(): DateTime
  begin
    exit(CreateDateTime(DMY2Date(31, 12, 9999), 2359T))
  end;
```
2. You'll get an Error:

`Constant value '2359T' is outside the range for a Time`

3. Change "2359T" to "0T" and the error disappears

4.  Now change "0T" to "1130T" for example. The same error appears

**Expected behavior**
Let me enter any valid Time value

**Screenshots**
![image](https://user-images.githubusercontent.com/63159395/87941500-26e88f80-ca93-11ea-93af-edc1a4cf5b2a.png)

**5. Versions:**

 - AL Language:  v5.0.288712

 - Business Central: 16.0.12630.12758

**Comment by NKarolak** [comment]
Did you try using 235900T instead?
The documentation does not suggest using 2359T only.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/time/time-data-type

**Comment by martonnagy** [comment]
> Did you try using 235900T instead?
> The documentation does not suggest using 2359T only.
> https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/time/time-data-type

Hi Natalie,

It works w/ 235900T, thanks!
The error message is still a bit misleading though... 😞 

Thank you for your help again.

Marton
