### ISSUE TITLE
[Event Request] T37 Sales Line IsCreditDocType

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/AL#6045]
Hello,
In Sales Header it is possible to specify custom document types as credit in OnBeforeIsCreditDocType, would it be possible to add same event in IsCredtiDocType in Sales Line?
Thanks,
Bartek

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
