### ISSUE TITLE
BC cannot run 32-bit .NET assembly on 64-bit server / AL does not recognise ProcessorArchitecture property

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6046]
I'm trying to use a .NET assembly in BC and have succesfully referenced it and deployed:

![image](https://user-images.githubusercontent.com/63455896/88164310-de081680-cc0b-11ea-9312-5d1e3cc1701b.png)

However, when I try to construct an instance, I get this runtime error:

![image](https://user-images.githubusercontent.com/63455896/88163968-591cfd00-cc0b-11ea-8705-4f48f2408166.png)

Can (and if so how) I "target x86", i.e. make BC run the .NET code in 32-bit mode?

I found that later .NET has the ProcessorArchitecture keyword, which seems to be for things like this, but the AL compiler won't let me write that as a property (alongside Version, etc.) as it concludes it's a syntax error.

Is this scenario meant to work? If so, how can I make it work? If not, is there any chance this can be supported in future? Thanks!

* AL 5.0.288712
* GB Business Central 16.0 (Platform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by atoader** [comment]
The main issue is that the server process is running as a 64 bit process. You will not be able to run assemblies compiled for x86 in this context. This StackOverflow question https://stackoverflow.com/questions/2301767/why-net-assemblies-differ-for-different-architectures points to the same answer.
As far as I can see, you need to get an assembly that has been compiled to work on AnyCPU or x64.
