### ISSUE TITLE
Cannot add multiple relations to a field with an existing single relation

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/AL#6049]
**Describe the bug**
It is not possible to add multiple table relations to a field with an existing single relation.

e.g. `TableRelation = "G/L Account"` vs `if ("MY Account Type" = const("G/L Account")) "G/L Account" else
            if ("MY Account Type" = const("Cost Type")) "Cost Type"`

When the user opens the fast lookup it only shows the existing single relation.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new project for BC 16.3
2. Create a table extension for any table that has a field with a single relation.
3. Extend the existing single relation with a conditional multi relation.
4. Run the extended table and open the fast lookup for the extended field.

```
tableextension 50100 "MY FA Posting Group" extends "FA Posting Group"
{
    fields
    {
        field(50100; "MY Account Type"; Option)
        {
            OptionMembers = "G/L Account","Cost Type";
            OptionCaption = 'G/L Account,Cost Type';
            Caption = 'Account Type';
        }
        modify("Acquisition Cost Account")
        {
            TableRelation = if ("MY Account Type" = const("G/L Account")) "G/L Account" else
            if ("MY Account Type" = const("Cost Type")) "Cost Type";
        }
    }
}
```
[TableRelation.zip](https://github.com/microsoft/AL/files/4966045/TableRelation.zip)
**Expected behavior**
When the user opens the fast lookup the correct conditional relation is used for the field.

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: CH Business Central 16.3 (Platform 16.0.14073.14195 + Application 16.3.14238.0)

**Comment by dtkb** [comment]
discussed at https://github.com/microsoft/AL/issues/4571#issuecomment-461428455 - but that got closed, so it makes sense to have a new one for overriding the standard, non-conditional relation.

**Comment by blrobl** [comment]
Closing as this was reported on a version out of support. If this continues to be an issue in the current version, please file a new bug.
