### ISSUE TITLE
NAV Webclient crash - When IIS is recycled it comes up

### ISSUE THREAD

**Issue by mrprasad2k** [Microsoft/AL#605]
Hi,

We have deployed NAV 2016 CU10 in a multi-tenant environment. Occasionally we have this issue wherein the web client becomes unresponsive and post restart or recycling IIS, the website comes up. Hardware resources are sufficiently available. Event viewer logs are not of help. Unable to replicate this issue in UAT or Dev environment.

Seeking your support.

Regards,
Ramprasad

**Comment by mrprasad2k** [comment]
@StanislawStempin - Seeking your support

**Comment by StanislawStempin** [comment]
Hi, this issue forum is related to Developer Preview and AL language topics. You would need to seek support through regular channels for your problem.
