### ISSUE TITLE
Extension Compilation failed with dependent extension BC16.2

### ISSUE THREAD

**Issue by jayalakshmi0395** [microsoft/AL#6050]
I have installed VMP365 app from App Source in my sandbox environment. I'm trying to extend this app.

For that i have created a new project. This is my app.json file.

`
{
  "id": "59777f92-1e66-45ec-9d11-0683e7397943",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "16.0.0.0"
    },
    {
      "id": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "16.0.0.0"
    },
    {
      "id": "016ee7d8-b2a8-41b9-b90d-5e625d8c0d0c",
      "publisher": "CETAS Information Technology",
      "name": "CETAS VMP365",
      "version": "3.0.0.1"
    }
  ],
  "screenshots": [],
  "platform": "16.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject1.com/help/",
  "showMyCode": true,
  "runtime": "5.0"
}
`

Downloaded symbols from sandbox environment. 

![image](https://user-images.githubusercontent.com/42033178/88366643-5525e200-cda7-11ea-8dd7-1a5e26c3b172.png)

Then I have created below table extension objects.

1. Extended a table from VMP365 App.

`
tableextension 50100 "TabExt Purch Req. Header" extends "CIT Purch Requisition Header"
{
    fields
    {
        field(50100; Remarks; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }
        field(50101; "Remarks 1"; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }

    }

}
`

2. Extended a default Purchase Header table.

`
tableextension 50101 "TabExt Purchase Header" extends "Purchase Header"
{
    fields
    {
        field(50100; Remarks; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }
        field(50101; "Remarks 1"; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }

    }

}
`

3. Created a new subscriber event.

`
codeunit 50100 "Purch. Req. Mgmnt"
{

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"CIT Vendor Portal", 'OnAfterInsertPurchHeadRFQ', '', false, false)]
    local procedure OnCreatePurchaseRFQHeader(var PurchaseRFQ: Record "Purchase Header"; PurchReqHeader: Record "CIT Purch Requisition Header")
    begin
        IF PurchaseRFQ."CIT Sub Document Type" <> PurchaseRFQ."CIT Sub Document Type"::RFQ then
            exit;

        PurchaseRFQ."Remarks" := PurchReqHeader.Remarks;
        PurchaseRFQ."Remarks 1" := PurchReqHeader."Remarks 1";
    end;
}
`

But I'm getting this error while referring VMP365 table extension fields.

![image](https://user-images.githubusercontent.com/42033178/88366557-1001b000-cda7-11ea-8393-0616f278b5a9.png)

Also tried to open the symbols using AL Object Designer and able to see the respective fields in Purchase Header table extension.
![image](https://user-images.githubusercontent.com/42033178/88366832-cf566680-cda7-11ea-90da-a93e595e1591.png)

_Originally posted by @jayalakshmi0395 in https://github.com/microsoft/AL/issues/5995#issuecomment-663373760_

**Comment by atoader** [comment]
Hi! Have you contacted the developer of the AppSource application for guidance? This issue does not seem to be related to how the developer tools work, but a misconfiguration of your project.

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
