### ISSUE TITLE
BC16 (AL - Cloud) "File Management"

### ISSUE THREAD

**Issue by ConchiJacobi** [microsoft/AL#6051]
Hello everyone! 
 
We are currently converting our solution from BC14 (C/AL - on premise) to BC16 (AL - Cloud).
During this process we have come across some commands, methods etc. that do not work in the cloud.
 
I am looking for a video or documentation that describes how to search, open and read several text files in a directory in the background.
 
Does anyone know any video or documentation for it?
 
Unfortunately BC16 does not accept internal methods of "File Management" like "GetClientDirectoryFilesList" or for file fields the Open command (FileF.Open(PathFile)). Unfortunately I can't find any documentation how to handle files in the cloud.
 
It would be nice if there was something "official" from Microsoft. 
 
The user must not be asked interactively to select the file! 
 
We need a fully automated variant that processes the files via the task queue (for example). Of course, the question arises as to which files or file system the cloud has access to at all.
 
Example: There are monthly (20-50) external text files with different file extensions (*.??| *.??) with price, quantities, information, etc. as an update for certain products or new products or products that need to be deleted. 
 
These delivered files are unpacked into a directory. These files must then be able to be processed using a list page. This should be done in a kind of batch processing, so that the user does not have to select each file individually
 
We have now done the opening with BlobImport. But unfortunately "BLOBImport" works with the "DialogCaption". We cannot use that.
 
Is there an import method without "DialogCaption"?

Many thanks
Best wishes
Conchi

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
