### ISSUE TITLE
Error downloading symbols for 16.3 - Microsoft System not found

### ISSUE THREAD

**Issue by nboettcher** [microsoft/AL#6053]
**Describe the bug**
I am trying to target platform 16.3.0.0 and application 16.3.0.0 so I can compile my extension against 16.3 for uploading into AppSource. I am using the online sandbox. When I 'download symbols' I get an error for the 'Microsoft System' app symbol file. 

Error:
The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=16.3.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.

I am able to pull in the other app files for 16.3
![image](https://user-images.githubusercontent.com/5880833/88394822-acb35600-cd85-11ea-9e68-17ab4cb89d15.png)

**To Reproduce**
Steps and to reproduce the behavior:
1. Setup AL project and target online sandbox
2. Set platform and application in app.json to 16.3.0.0
3. Download symbols

**Expected behavior**
All symbols should download without error and I should be able to compile for 16.3.0.0

**Screenshots**
app.json 
![image](https://user-images.githubusercontent.com/5880833/88394944-e5532f80-cd85-11ea-9509-87ccad40de34.png)

![image](https://user-images.githubusercontent.com/5880833/88394630-61994300-cd85-11ea-84a3-e554cdad47e9.png)

**5. Versions:**
 - AL Language: v5.0.288712

 - Business Central:
![image](https://user-images.githubusercontent.com/5880833/88394508-2b5bc380-cd85-11ea-9ee7-324657ec8674.png)

**Comment by atoader** [comment]
The "platform" tag identifies the version of the system symbols. As we do not increment the minor version for the platform, the version of the platform symbols does not get increased. Use "16.0.0.0" for the platform symbols.
