### ISSUE TITLE
AL extension version for Visual Studio Code cannot be used with the specified server

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6055]
Hi,

Server details - Runtime: 5.3, - Web API: 4.0, - Debugger: 3.0
AL extension details:
Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 5.0, 5.1, 5.2, 6.0

..but not version 5.3. What the hell? How can you publish an AL compiler which does not support 5.3, but does support 5.2 and 6.0? The server runtime version cannot be changed since that's on your saas platform.

**Comment by atoader** [comment]
Hi! You are using the VSIX from the insider build which is taken from the master branch (6.0). It appears that the minor versions have gone out of sync and made the insider version not work against the prod release. We have created a work item to address this in our release process to prevent it from happening in the future. The insider version is experimental and, although we strive to deliver software at the highest level of quality, there will be issues like this that get through and for which we appreciate early feedback.

I would like to underline that, although we appreciate that you took the time to report this issue, your post does not respect our code of conduct https://opensource.microsoft.com/codeofconduct/ . Please take a minute to read it and make sure to follow it in future posts.

**Comment by navdotnetreqs** [comment]
Yes, and I don't respect the quality of your work in the BC era either.
