### ISSUE TITLE
Issue Object Table: Conversion of OemText to Text fails 

### ISSUE THREAD

**Issue by MathurRahul** [microsoft/AL#6056]
**Describe the bug**

My app.json contains:

{ 
  "target": "Internal"
}

I'm encountering this error "The definition of the Name field has changed; old type: Text, new type: OemText. Start your activity again."

``` AL Code to reproduce the issue ```

The error comes on this line of code. When I try to set filter on "Name" field of  "Object Table" to get "Object ID".

![image](https://user-images.githubusercontent.com/50518051/88540312-fbc1eb00-d012-11ea-9a41-a381adedb55a.png)

**5. Versions:**

 - AL Language: v5.0.288712

 - Business Central: 16.0.11240.12076

Is there any way to convert the OemText into a valid string?

**Comment by atoader** [comment]
Can you provide a fully contained project that reproduces the issue?

**Comment by MathurRahul** [comment]
Hello,

I created a new AL project and edited the default "HelloWorld.AL" file to simulate the issue. 


![image](https://user-images.githubusercontent.com/50518051/88836262-b2ba9400-d1d6-11ea-888e-ebe7d6c20627.png)

**Comment by MathurRahul** [comment]
Hello, is there any update on this issue? Do you need any more input from my side?

**Comment by waldo1001** [comment]
@MathurRahul , Did you try to work with the "AllObj" virtual table?

**Comment by MathurRahul** [comment]
Hello @waldo1001 , Thank you for the input. It works. 

![image](https://user-images.githubusercontent.com/50518051/89491472-aa062700-d7af-11ea-8a36-bd5ae7ae97e4.png)

**Comment by atoader** [comment]
Hi! We've discussed this a bit internally. We will deprecate the "Object" and "Object Metadata" tables in 17.0 and later. These tables should not be used as they refer to objects and metadata generated by C/SIDE. The AllObj, AllObjWithCaptions, "Nav App Object Metadata" tables should be used instead.
