### ISSUE TITLE
Permissions seems to work differently on productions versus sandbox

### ISSUE THREAD

**Issue by Joerio** [microsoft/AL#6057]
We have a codeunit that has the following permissions set:
 Permissions = TableData 2000000185 = rimd;

This seems to work fine when we run this in a Sandbox. However, we deployed these changes to the app store, and now we get a permission error on this table.

Do permissions work differently in production than sandbox? Is this something we can work around in this example?

**Comment by atoader** [comment]
Permissions are verified in the same manner in production and sandbox environments. The main difference is that entitlements are not checked in sandboxes. If you are not familiar with entitlements, they are derived from the subscription you assign to a user. An entitlement/subscription can restrict the maximum permissions that can be assigned to a user.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
