### ISSUE TITLE
Browserproblem? Maybe Caching when setting up visibility of actions

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/AL#6058]
Hello Team, we have experienced following problem:

To follow the problem we do following steps:

1: PageExtension with one Action that we want to make "Visible" on a certain condition of a tablerecord (Setuptable)

- PageAction with a Visible Parameter
- Code in OnOpenPage for setting the global bool var.
`   trigger OnOpenPage()
    begin

        if EngSetup.Get() then
            ShowKumPrice := EngSetup."Accumulated pricing";
    end;
`
 

If you first start the Application, all seems correct, with the correct visibility. But if you change the field in the Setuptable and go back on this page, the old Visibility is taken. Although the code in "OnOpenPage" is running correct with correct setting of the global var.

If you "Reload" the Page (in Edge STRG-R) the Action has the correct state. 
So it must be a Cacheproblem somehow.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
