### ISSUE TITLE
Issue with redeployment of library extensions

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#606]
We have a library extension that our other apps use (and list as a dependency). When adding functions to a codeunit in the library extension, referencing those functions in another app, and redeploying the library extension using VS Code, the other apps fail deployment with an error that the new functions do not exist.

I have tried unpublishing the library extension, but that does not resolve the issue. However, incrementing the version number in the library extension seems to solve it.

**Comment by StanislawStempin** [comment]
This is most likely a caching issue. See if restarting NST solves it.  If it is indeed caching we will consider flushing that cache on F5.
Otherwise, incrementing the version number is the right workaround for now.

**Comment by cmrudolph-msft** [comment]
There is definitely a problem with cache invalidation here. I will write this bug up for my team to fix.
