### ISSUE TITLE
Control visibility on navigate pages is not consistently updated accross groups

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6060]
**Describe the bug**
In Navigate pages, if the visibility of a group is controlled with a variable, the visibility is only refreshed when the variable value is changed on the displayed tab. If the group is currently hidden (because you are on another tab), when the tab where the group is placed is displayed by the user the visibility might be incorrect.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a project with the page below
2. Run it and play with the IsChecked checkbox.

```
page 80000 "DRCVG TEST"
{
    PageType = NavigatePage;
    UsageCategory = Tasks;
    ApplicationArea = All;
    Caption = 'TEST';

    layout
    {
        area(Content)
        {
            group(General)
            {
                Caption = 'General';
                field(IsCheckedControl; IsChecked)
                {
                    ApplicationArea = All;
                    Caption = 'IsChecked';

                    trigger OnValidate()
                    begin
                        UpdateControls();
                    end;
                }
            }
            group(Other)
            {
                Caption = 'Other';
                field(IsCheckedControl2; IsChecked)
                {
                    ApplicationArea = All;
                    Caption = 'IsChecked';

                    trigger OnValidate()
                    begin
                        UpdateControls();
                    end;
                }
                group(AVisibleGroup)
                {
                    Caption = 'AVisible';
                    ShowCaption = false;
                    Visible = AVisible;
                    InstructionalText = 'AVisible';
                }
                group(BVisibleGroup)
                {
                    Caption = 'BVisible';
                    ShowCaption = false;
                    Visible = BVisible;
                    InstructionalText = 'BVisible';
                }
            }
        }
    }

    trigger OnOpenPage()
    begin
        UpdateControls();
    end;

    local procedure UpdateControls()
    begin
        AVisible := IsChecked;
        BVisible := not IsChecked;
    end;

    var
        [InDataSet]
        IsChecked, AVisible, BVisible : Boolean;
}
```

**Expected behavior**
When the page is loaded BVisibleGroup should be visible and AVisibleGroup should be hidden (because IsChecked is false).
When IsChecked is changed on the first tab, the visibility of AVisibleGroup and BVisibleGroup should be consistant when they are displayed again.

**Screenshots**
![Image](https://cvcapvignesdevstorage.blob.core.windows.net/public-share/NavigatePageBehavior.gif)

**5. Versions:**
 - AL Language: 6.0.302409
 - Business Central: FR Business Central 17.0 (plateforme 16.0.14638.0 + application 17.0.14981.0)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
