### ISSUE TITLE
FilterPageBuilder Raw GetView

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/AL#6061]
The data type FilterPageBuilder has the function GetView but it is missing the possibility to extract the raw filter of the user's input.

I use this data type to save the filter a user wants to use.

Example:
I have a function to delete all the sales orders which are within a filter that the user defines. For that, I am using the FilterPageBuidler and the user makes the input: "w-7" (workdate minus 7) at the moment I call "GetView" but I only get the resolved date returned. I have no chance to get the DateFormula.

would it be possible to add a parameter to get the raw inputs of the user? or a function GetRawView?

**Comment by dtkb** [comment]
What field(s) are you filtering, and how?

I'd be surprised if this can work, as I thought shorthands like those were always resolved before they get anywhere near the record/page view.

Maybe a FlowFilter of type DateFormula could be bent to work for this case, though not sure.

**Comment by Spycoclown** [comment]
The user experience is not the same as they can filter on views they saved in the role center.
If I filter my page list with the filter pane and I save it to the role center, it resolved the DateFormula every time I open the new view. But if I use the FitlerPageBuilder it returns directly the resolved date. I just want to give my users the same experience in the filter pane and the FitlerPageBuilder.

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by Spycoclown** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=586044ef-a9d7-ea11-bf22-0003ff688bae
