### ISSUE TITLE
[Code-defect] Error AL0118 for procedure with Argument Field when passed on field from extension.

### ISSUE THREAD

**Issue by PieterJacob** [microsoft/AL#6062]
Dear Microsoft,

Visual Studio Code shows an error when a field from an extension is passed on to a procedure with field as its argument, e.g. Record.TestField("Field Name").
It shows: _The name '"Extension Field Name."' does not exist in the current contextAL(AL0118)_, yet the field itself is known in the workspace.

Example:
`Record.TestField("Extension Field Name");`

It's possible to bypass this error by changing the code like below, this however is not preferable. Can you have a fix for this in the future?
`Record.TestField(Record."Extension Field Name");`

**Comment by dtkb** [comment]
can't replicate in BC16 / AL5.0.311003 with our own extension fields.

what versions are you running? where/how is the new field declared? can you attach a minimal project that shows the error? this is too vague otherwise.

**Comment by atoader** [comment]
Can you provide a project to reproduce the issue?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
