### ISSUE TITLE
AL AD0001 Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' 

### ISSUE THREAD

**Issue by robertosb** [microsoft/AL#6063]
AL Version v5.0.288712

**Description**
Docker image (current) downloaded this month on the 10'th of July.

I am getting a few 205 code analyzer errors as per below, pointing me to the App.Json file:
<<
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule205VariablesMustAlwaysBeInitialized.UnusedLocalVariableAnalyzer.AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule205VariablesMustAlwaysBeInitialized.cs:line 484
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 742
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1099'
>>

Anyone had this before and what is the fix if it's a known one?
Including @atoader  and @MarcHansenMicrosoft as you guys looked at something similar in #5694

Cheers,
Robert

**Comment by NKarolak** [comment]
No, you're not the first: https://github.com/Microsoft/AL/issues?q=sort%3Aupdated-desc+Rule205VariablesMustAlwaysBeInitialized

How to find out the root cause: https://github.com/microsoft/AL/issues/5835#issuecomment-620539842

**Comment by robertosb** [comment]
> No, you're not the first: https://github.com/Microsoft/AL/issues?q=sort%3Aupdated-desc+Rule205VariablesMustAlwaysBeInitialized
> 
> How to find out the root cause: [#5835 (comment)](https://github.com/microsoft/AL/issues/5835#issuecomment-620539842)

Thank you Natalie, not ideal with close to 100 objects in my project, but I'll give it a go, removing all AL objects and adding them one by one ( or sets of 10 or something) to see when it breaks. 
I hope that's what you meant by looking at the 5835 comments 👍 
Thank you again,
Rob

**Comment by NKarolak** [comment]
Correct 😉

**Comment by MarcHansenMicrosoft** [comment]
logged internally for investigation.
I think that it should have been fixed.

**Comment by robertosb** [comment]
> logged internally for investigation.
> I think that it should have been fixed.

thanks Marc, the issue was resolved by doing what's suggested in Natalie's link, copy paste the files out of the repository and add them back in sets of objects removed the issue. 
I will leave the ticket open in case you guys want to find out the real issue and fix it in the future, unless already resolved as you said.

Cheers,
Robert

**Comment by MarcHansenMicrosoft** [comment]
Thanks

**Comment by PaulIvan** [comment]
Hi @robertosb it looks like the System.NullReferenceException has been fixed earlier :) 
Please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by robertosb** [comment]
Brilliant, thank you Paul!
