### ISSUE TITLE
HttpClient, DNS cache and Dynamic IPs

### ISSUE THREAD

**Issue by HannesHolst1** [microsoft/AL#6064]
**Describe the bug**
The native HttpClient does lag an update of the DNS cache. I have an HTTP-endpoint that sits behind Cloudflare and changes the IP dynamically. When the IP changes, the DNS cache of HttpClient doesn't recognize the change and a connection cannot be established. In such situation, HttpClient returns the error: "An error occurred while sending the request."
The DNS-name is used as URL.

Only solution is to restart the ServiceTier.
Or, to utilize HttpWebRequest instead.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a HttpClient-instance
2. Send http-request to an endpoint that sits behind a service like cloudflare
3. let service change the IP-address
4. Send http-request again

**Expected behavior**
This is a common problem even for the HttpWebRequest-class.
A workaround is to set the property "KeepAlive" to false. 
https://stackoverflow.com/questions/7277582/how-do-i-clear-system-net-client-dns-cache

Unforatunately is this property not available in the HttpClient.

**5. Versions:**

 - AL Language: v5.0.311003

 - Business Central: GB Business Central 16.1 (Platform 16.0.12630.12758 + Application 16.1.12629.12805)

This bug does not exists in Platform 14.0.34251.0 + Application 29537 (GB Dynamics NAV 14.0)

**Comment by Joriek** [comment]
Hello Hannes, I had a similar issue where certain data was cached by the HttpClient object.
It was fixed by adding the clear(HttpClient) function right before the HttpClient.send(...) function.
My issue nothing to do with dynamic IP-addresses but this worked for me, I hope it also works for you.

**Comment by HannesHolst1** [comment]
> 
> 
> Hello Hannes, I had a similar issue where certain data was cached by the HttpClient object.
> It was fixed by adding the clear(HttpClient) function right before the HttpClient.send(...) function.
> My issue nothing to do with dynamic IP-addresses but this worked for me, I hope it also works for you.

Hi Joriek,

executing clear(HttpClient) right before the HttpClient.send-function would mean that any headers and the content would be deleted. I think an empty http-request would be send.

In my scenario, HttpClient was declared as local variable. That means, for each call a fresh HttpClient-instance was used.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by HannesHolst1** [comment]
When these are the official rules now 🤦‍♂️🤦‍♂️🤦‍♂️
