### ISSUE TITLE
AL Debugger OSX Not Triggering Breackpoint

### ISSUE THREAD

**Issue by svenauhagen** [microsoft/AL#6069]
Hi,

I am using the VSCode on OSX and Chrome as a Browser.
Developing on a Sandbox in the Cloud.

When deploying with debugging my VSCode connects just fine but my breakpoints are never triggered.
Also code errors hang in Chrome as they are waiting for the debugger to get triggered but that is not happening.

Any reason why this is not working on my OSX?

Best
Sven

**Comment by dtkb** [comment]
I suspect simply because only Windows is tested and supported for developing AL in VS Code.

**Comment by svenauhagen** [comment]
That is unfortunate

**Comment by atoader** [comment]
Hi! Although the AL language extension works on OSX, we do not officially support this platform at the moment: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#al-development-requirements 
Do you experience the same issues when using a Docker sandbox? Can you provide a project to reproduce the issue and a video recording of you experiencing it?

**Comment by svenauhagen** [comment]
Hi! So today it did work but this was the first time.
I do not have a local Windows Server I can use for Docker so I only have access to the online sandbox. I can send you my project files but they are calling a REST API server so I am not sure if that helps you a lot.

**Comment by atoader** [comment]
The project or any other project that reproduces the issue and a recording of the breakpoints being set but not hit would help a lot in tracking down the source of the bug.

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
