### ISSUE TITLE
Make function ProcessAllLinesColumnMapping in Codeunit 1201 accessible for extensions (URGENT)

### ISSUE THREAD

**Issue by AMCJN** [Microsoft/AL#607]
Hi

We are using the following function **'ProcessAllLinesColumnMapping'** in codeunit 1201
in our extension V1 to process Bankaccount statements we fetch from the users online bank.
Unfortunately this is not accessible in V2 for our extension, is it possible get accessible to call
from extensions V2 ??

Thanks.

**Comment by atoader** [comment]
I've forwarded your request to the App teams.

**Comment by AMCJN** [comment]
Any time frame for when this is exposed in D365 ?

**Comment by StanislawStempin** [comment]
This hasn't been processed by the app team yet but if the function is safe then I expect it will be delivered with October Update.

**Comment by AMCJN** [comment]
Hi,

I think this is not made available for all locales ?

I just downloaded the latest october preview from docker,
I downloaded W1, GB and DK.
With W1 and GB this is now available, but for DK I still get the same message as before it was made available.

'The type or method 'ProcessAllLinesComulmnMapping' cannot be used for 'Extension' Development.

Can you please make suer to open this function for all locales ?

**Comment by StanislawStempin** [comment]
Please make sure to always re-download the new symbol files (delete the old ones from the cache folder). We checked on DK and this method is correctly marked as External.
