### ISSUE TITLE
Removing a dependency is impossible if at least one field depended on a Enum

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6070]
**Describe the bug**
I do not know if this is the place or really a bug or suggestion. But the issue is if app B depends on app A, and app B is using in a table field an enum from app B ; then the dependency between A and B cannot be removed because of rule AS0004.

It is slightly related to #5818 I posted earlier this year but this one addresses a more reasonable issue... I think :)

**To Reproduce**
Steps and to reproduce the behavior:
1. Create project AppA with the enum below
```
enum 50000 MyEnum
{
  value(0; "A")
  {
    Caption = 'A';
  }
}
```

2. Create project AppB, add a dependency to AppB and create the table below
```
table 50000 MyTable
{
  fields
  {
    field(1; Code; Code[20])   {   }
    field(2; Val; Enum MyEnum) {  }
  }
}
```
3. Now we obsolete the field Val in AppB version 2
```
    field(2; Val; Enum MyEnum)
    {
      ObsoleteState = Removed;
    }
```
4. In AppB version 3, we want to remove the dependency with AppA

**Expected behavior**
We should have a way to remove a dependency, even if a field is depending on a Enum of the other app.
To prevent breaking change, I think ASCop should only allow changing field type if in the previous version the field was marked as Removed, then we should be able to change the type to Option or Integer.
This would allow removing the dependency without removing the field or breaking the table schema.

**Screenshots**
./.

**5. Versions:**
 - AL Language: 6.0.312152

**Comment by demiliani** [comment]
Unfortunately at the moment setting ObsoleteState = Removed it will not remove the field and so you cannot break the dependency, but I agree that this is something that must change soon.

**Comment by atoader** [comment]
Hi! We have it on our backlog to support removing schema elements from the database and from code, but it is not planned for the medium term. My suggestion is to upvote the idea on https://aka.ms/BusinessCentralideas if it is already there or create a new one. The community's input will help us prioritize this functionality against other features.

**Comment by nicolassaleron** [comment]
Thanks for the feedback, already upvoted for this idea 👍 

But just to be clear: this request was not to be able to definitively delete a field with its data. Just to be able to relax this rule to allow moving a field type from Enum to Option, when the field is already marked as Removed in a previous version.
It would not cause any data loss.
But if this is the same idea from your point of view, that's ok
