### ISSUE TITLE
Key Binding Ctrl+F4 for Show the started snapshots conflicts with View: Close Editor

### ISSUE THREAD

**Issue by mhenricus** [microsoft/AL#6074]
**Describe the bug**
Double VS Code keyboard shortcut

**To Reproduce**
Steps and to reproduce the behavior:
1. Open some files in VSCode
2. Try to close a file with Ctrl+F4, which is default VSCode behavior
This shortcut is taken over by the AL Language

**Expected behavior**
Default VS Code shortcut
Please find another shortcut key combination

**Screenshots**
![image](https://user-images.githubusercontent.com/69308907/89546149-8caf7800-d804-11ea-8016-cc82c046d379.png)

**5. Versions:**
- AL Language: v6.0.313479
- Business Central: NL Business Central 17.0 (Platform 17.0.15306.0 + Application 17.0.15311.0)

**Comment by thloke** [comment]
This issue has been fixed. The fix will be available in a near future release.
