### ISSUE TITLE
Error in validation appsource Extension 10675199.02:48:05.4775807

### ISSUE THREAD

**Issue by icapillaNubit** [microsoft/AL#6075]
Hi!!,

We are trying to validate our extension for appsource, but Microsoft engineers are getting the following error:

Critical Validations     1failure(s) 
These issues block the publish of your solution to Microsoft marketplace. Please refer to our Microsoft Marketplace policies for more details. Also, you can view full certification report on Partner Center for additional details. 
Technical Requirements 
1400.5.17  Testing 
We are unable to publish, sync, or install your app to our test tenant. See below for error message. To repro these errors, test the publish, sync, and install of your app. The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'. 

Does anybody know why this could be happening to them, let's go for our version 16.3.1.7, in the version 16.3.1.6 they could do the necessary tests without any problem and in the next version that only fixes small bugs, they are not being able to publish the extension. 

Best regards.

**Comment by atoader** [comment]
Hi! Do you have any upgrade/install code that makes requests to external services?

**Comment by icapillaNubit** [comment]
Yes, last Friday I managed to correct the error, when installing I have a template that fills a table, to that table I added a field and I completely forgot that I had to regenerate the template. It didn't occur to me that this might be the case because the error message that appeared didn't make me suspicious.

Thank you very much.
