### ISSUE TITLE
AppSourceCop is not throwing an error for 'OptionMembers' Change

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/AL#6078]
**Describe the bug**
We are not getting an error if we try to modify or add new options to the **'OptionMembers'** even the AppSourceCop and CodeCop are active.  

But we are getting a failure as breaking change in Microsoft Technical Validations. Please find the below for MS Technical Validation issue.

Failed to compile package: .vscode/AL%20Files/Table%20Extensions/Tab5740-Ext70174915.Transfer%20Header%20PSE.al(143,25): error AS0044: OptionMembers has changed value from ' ,,Prepaid,Third Party Billing,,,' to ' ,Prepaid and Charge,Prepaid,Third Party Billing,Collect,Consignee Billed,Bill Recipient', this is a destructive change, only appending new OptionMembers is allowed.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create New field of type 'Option' in TableExtension and give some options.
2. Go to Settings in VS Code -> Extensions -> Settings.json
3. Activate 'AppSourceCop' and 'CodeCop'
4. Modify the existing options in 'OptionMembers'

**Expected behavior**
AppSourceCop should identify this issue and throw an error.

**4. Versions:**

 - AL Language: 5.0.312966

 - Business Central:16.3 (Platform 16.0.14073.14279 + Application 16.3.14085.14363)

**Comment by NKarolak** [comment]
I believe you did not configure the AppSourceCop to compare code with the old app version:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop#configuration

**Comment by atoader** [comment]
Can you confirm that you configured AppSourceCop properly? Can you share a project to reproduce the issue?

**Comment by Rambabu-Billuri** [comment]
Yes, we configured AppSourceCop, added the old version in /.alpackages and we have given old app details in AppSourceCop.json

Here is the details in settings.json
![image](https://user-images.githubusercontent.com/57799519/90127054-369d8000-dd82-11ea-9c20-555592067ab5.png)

**Comment by NKarolak** [comment]
Your AppSourceCop.json is not in the [project's root folder](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop#configuration), but in subfolder .codeAnalysis.

**Comment by Rambabu-Billuri** [comment]
We tried by moving the AppSourceCop.json file to root folder, but we didn't get any error and the new app installed successfully.

**Comment by NKarolak** [comment]
Did you restart VS Code or "Reload window" after the change? Just a guess ...

**Comment by Rambabu-Billuri** [comment]
Yes we tried with "Reload window" and "Restart", still we didn't get the error while installing the new app.

**Comment by Rambabu-Billuri** [comment]
@qutreson any updates on this ?

**Comment by NKarolak** [comment]
Oh, good you're reminding me.
What I didn't know: the correct settings apparently do not provide instant errors, but only on publishing the actual app. Have you already tried that?

**Comment by Rambabu-Billuri** [comment]
Yes.

**Comment by qutreson** [comment]
Hi @Rambabu-Billuri, I tried reproducing this scenario, but without success as I am getting the AS0044 diagnostic reported when introducing a breaking change on the OptionMembers property.

I created an extension containing the following table in version 1.0.0.0:

```
table 10000000 FOO_MyTable
{
    fields
    {
        field(1; MyOptionField; Option)
        {
            DataClassification = SystemMetadata;
            OptionMembers = Yes,No,Maybe;
        }
    }
}
```

And containing the following table in version 2.0.0.0:
```
table 10000000 FOO_MyTable
{
    fields
    {
        field(1; MyOptionField; Option)
        {
            DataClassification = SystemMetadata;
            OptionMembers = Yes,None,Maybe; // No has been replaced by None
        }
    }
}
```

I am now getting this AppSourceCop analyzer diagnostic in VS Code:

![image](https://user-images.githubusercontent.com/31541422/93059460-00993780-f671-11ea-8e5a-85e580c580bc.png)

You can find attach the full project I used here: [Github6078.zip](https://github.com/microsoft/AL/files/5216951/Github6078.zip)

You can use it to verify that the AppSourceCop is correctly configured in your project. It is important to have:
- the AppSourceCop.json place at the root of your project 
- to have the `version` to use a base line in the AppSourceCop.json
- to have the baseline package added to your package cache path (this will result in [AS0003](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0003-previousversionnotfound) if not set properly).

If that did not help resolving this issue, can you share the project that you are using, or another one that could help reproducing the issue?

**Comment by Rambabu-Billuri** [comment]
Thank you so much @qutreson. We tried as you specified in the given project, it is working fine. AppSourceCop is throwing an error this time.
