### ISSUE TITLE
XmlDocument is saved with incorrect Encoding/Contents

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#6079]
[Test.txt](https://github.com/microsoft/AL/files/5063310/Test.txt)

**Describe the bug**
Importing an XML File with UTF-8 encoding and saving it using the native XmlDocument type results in an incorrect XML File with UTF-8 BOM encoding.

**To Reproduce**
Import/Export the attached XML file (please rename the extension) using the following code:
```     
procedure TestEncodingIssue()
    var
        FileMgt: codeunit "File Management";
        TempBlobIn: codeunit "Temp Blob";
        TempBlobOut: codeunit "Temp Blob";
        InStr: InStream;
        OutStr: OutStream;
        XmlDoc: XmlDocument;
    begin
        FileMgt.BLOBImportFromServerFile(TempBlobIn, '\\por16-05-01\Temp\Test.xml');

        TempBlobIn.CreateInStream(InStr, TextEncoding::UTF8);

        XmlDocument.ReadFrom(InStr, XmlDoc);

        TempBlobOut.CreateOutStream(OutStr, TextEncoding::UTF8);
        XMLDoc.WriteTo(OutStr);

        FileMgt.BLOBExport(TempBlobOut, 'Test.xml', true);

    end;        
 ```

**EDIT: the corrupt xml contents was caused by using the same Temp Blob variable. The encoding issue however remains.** 

**Expected behavior**
The resulting XML File should be identical to the original File.

**Screenshots**
Encoding original XML File (using Notepad++) (**EDIT: ignore the corrupt body**):

![image](https://user-images.githubusercontent.com/48217797/90022172-7eed6d00-dcb2-11ea-8d0f-d0f18c716941.png)

Resulting XML File (**EDIT: ignore the corrupt body**):

![image](https://user-images.githubusercontent.com/48217797/90022409-c70c8f80-dcb2-11ea-8866-c557c9fa516c.png)

**5. Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/48217797/90022637-0fc44880-dcb3-11ea-87fe-e9491afd156a.png)

 - Business Central:
![image](https://user-images.githubusercontent.com/48217797/90022804-3f735080-dcb3-11ea-92d3-a58303b90234.png)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by daansaveyn** [comment]
> Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
> 
> As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
> 
> To open a support case, you can:
> 
> * Open a support request to CSS through the PartnerSource portal
> * Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
> 
> If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

Hi,

Why isn't this a bug in the compiler? A similar issue was reported and solved here... [https://github.com/Microsoft/AL/issues/630](url).

**Comment by atoader** [comment]
At the point when the issue was reported, this repository also handled issues related to the runtime. As stated in our readme, we have chosen to focus solely on developer experience issues.

**Comment by fvet** [comment]
Loggon on collaborate 

https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/358971
