### ISSUE TITLE
Test if JsonValue is null

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#608]
Consider this Json part:

```
{
  "id": "sub_BL5QIUO4gcd3YP",
  "object": "subscription",
  "application_fee_percent": null,
  "cancel_at_period_end": false,
  "canceled_at": null,
  "created": 1504549511,
  "current_period_end": 1507141511,
  "current_period_start": 1504549511,
  "customer": "cus_BL5QyOmfW3AAyS",
  "discount": null,
  "ended_at": null,
}
```

How to test if property `ended_at` is null? It is supposed to be a BigInteger, but when I use `JsonValue.AsBigInteger`, then I get an error message that it could not be converted. So I have to test the value first. However, there is no IsNull method on JsonValue object.

For now, I managed to use: `Format(JValue) in ['null','undefined','']`
However, I think that having IsNull is a better option.

**Comment by atoader** [comment]
On variables of type JsonValue, there is an IsNull and an IsUndefined property. This should accomplish what you want. Let me know if you encounter any problems with those.

**Comment by ajkauffmann** [comment]
Ah... I totally overlooked that. Was looking with intellisense, and because of the missing scrollbar, I thought there were no more options. But it appears that you actually see a scrollbar when you move your mouse into the popup... It fooled me once again...

Tested and works, thanks for the swift reply!
