### ISSUE TITLE
Wrong implementation AA0181: The FindSet() or Find() method on the record '%1' must be used only in connection with the Next() method

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#6083]
**Title**
Wrong implementation AA0181: The FindSet() or Find() method on the record '%1' must be used only in connection with the Next() method 

**Description**
Beside the classical Find('-') and Find('+'), which should not be used without Next(), there are several exceptions which are not handled by the rule, making unnecessary noise. Like Find(), Find('<'), Find('>') and combinations.

**Reason for the rule**
Wrong implementation shows a lot of false positives.

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.314405
Publisher: Microsoft

**Bad code sample**
Example of what bad code the rule should catch:

```     procedure FindIssuesWrong()
    var
        item: Record Item;
        item2: Record Item;
    begin
        item.Find('-'); // Must raise AA0181

        item2.Find('+'); // Must raise AA0181
    end;
```

**Good code sample**
The analysis must NOT raise these.
Example of what code should look like:

```     procedure FindIssuesGood()
    var
        item: Record Item;
        item2: Record Item;
        item3: Record Item;
        item4: Record Item;
        item5: Record Item;
    begin
        item."No." := '1000';
        item.Find('><='); // Should not raise AA0181

        item2."No." := '2000';
        item2.Find('<'); // Should not raise AA0181

        item3."No." := '2000';
        item3.Find('>'); // Should not raise AA0181

        item4."No." := '2000';
        item4.Find('='); // Should not raise AA0181

        item5."No." := '1000';
        item5.Find(); // Should not raise AA0181
    end;
```

**Good and bad practices for fixing the rule**
The rule should apply to Find('-') and Find('+') only, not on variations like Find('<>='), Find('='), etc.

**Remarks**
See here for explanations: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-find-method#parameters

**Comment by miljance** [comment]
I just hit the same issue. The rule should in my opinion not force the usage of Next() when Find('<') or Find('>') are used.

**Comment by DanielGoehler** [comment]
Codeunit 88 also causes this error. Is there an better way after RecRef.SetTable to fetch the record?
```
codeunit 88 "Sales Post via Job Queue"
{
    TableNo = "Job Queue Entry";

    trigger OnRun()
    var
        SalesHeader: Record "Sales Header";
        BatchProcessingMgt: Codeunit "Batch Processing Mgt.";
        BatchPostingPrintMgt: Codeunit "Batch Posting Print Mgt.";
        RecRef: RecordRef;
        RecRefToPrint: RecordRef;
        SavedLockTimeout: Boolean;
    begin
        TestField("Record ID to Process");
        RecRef.Get("Record ID to Process");
        RecRef.SetTable(SalesHeader);
        SalesHeader.Find; // AA0181 Warning
```

**Comment by DanielGoehler** [comment]
Hi @atoader, any update?

**Comment by stefanoPrimo** [comment]
I have another example, but this time i think it must not raise anything:
![image](https://user-images.githubusercontent.com/36199751/104180952-45aa5c00-540e-11eb-9b88-ac5383362d72.png)

**Comment by dtkb** [comment]
Most simply, this occurs with `Find('=')` meaning 'get me the record whose primary key fields have the currently set values', and its implicit equivalent `Find()` (since `'='` is default). It shouldn't because that only gets a single record. In fact, combining that with `Next()` would be _bad_, not good!

This is a particular pain because `Find()` is a really convenient way to refresh a record that already contains field values but might be out of date. With this misfiring diagnostic, we must either suppress it and thus noise up local code (or lose legit warnings at project scope), or instead use the far more verbose and error-prone `Get(Maybe, I, Remembered, What, All, The, Key, Fields, Are, Here)`.

![image](https://user-images.githubusercontent.com/63455896/107535269-7ff74c80-6bb8-11eb-828d-9dffa1fdf6f8.png)

**Comment by pri-kise** [comment]
Hi @atoader is there any progress on this issue and shouldn't the label "Bug" being added, since there current warning is wrong in some cases?

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

**Comment by TeusV** [comment]
another 4 years later, this issue still remains...
