### ISSUE TITLE
Cannot open the sandbox on the android device by using url ms-businesscentral://businesscentral.dynamics.com/sandbox

### ISSUE THREAD

**Issue by RED-Lin** [microsoft/AL#6085]
**Describe the bug**
Cannot open the sandbox on the android device by using URL ms-businesscentral://businesscentral.dynamics.com/sandbox

**To Reproduce**
1. install the app Microsoft Dynamics 365 Business Central on the android device.
2. open the browser on the android device
3. entering the URL ms-businesscentral://businesscentral.dynamics.com/sandbox
4. nothing happened, 

``` AL Code to reproduce the issue ```

**Expected behavior**
I think after entering the URL, the app should open with the sandbox environment.

**Screenshots**

**5. Versions:**

 - AL Language: Latest

 - Business Central:

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
