### ISSUE TITLE
Table Event "RunTrigger is false" on Pages with MultipleNewLines = Yes

### ISSUE THREAD

**Issue by ReneGubler** [microsoft/AL#6088]
**Bug Description**
On List Pages with MultipleNewLines = Yes the Table OnAfterInsertEvent EventSubscriber is fired but empty lines always have false in the RunTrigger parameter. 

**Reproduce**
Steps and to reproduce the behavior:
1. Create an EventSubscriber (see below)
2. Go to Customer Card
3. Go to  Customer Comments
4. Enter any text (Line No. 10000)
5. The Event is fired with RunTrigger = true for Line No. 10000
6. Cursor down, down and enter any text (Line No. 30000)
7.1. The Event is fired with RunTrigger = true for Line No. 30000
7.2. The Event is fired with **RunTrigger = false** for Line No. 20000
``` AL Code to reproduce the issue
[EventSubscriber(ObjectType::Table, Database::"Comment Line", 'OnAfterInsertEvent', '', true, true)]
local procedure OnAfterInsertComment(var Rec: Record "Comment Line"; RunTrigger: Boolean)
begin
     // set a break point here and check "RunTrigger"
end;
 ```
   
**Expected behavior**
The Event is fired with RunTrigger = true also for "empty lines".

**Versions:**
 - AL Language: 5.0.312966
- Tested in BC14 & 16 latest CU

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
