### ISSUE TITLE
Issue 6087 is not solved - the debugger still does not work

### ISSUE THREAD

**Issue by davmac1** [microsoft/AL#6090]
I updated the AL Language to 5.0.320540 and restarted VS Code.
It now brings up the sandbox with the debugger on, but breakpoints are ignored and a known error causes the client session to hang.
Please fix and test that the debugger works - for breakpoints and errors.

**Comment by atoader** [comment]
Can you provide a repro?

**Comment by davmac1** [comment]
It hangs when it hits an error - I have a place in the code where it moves a 50 character field to a 100 character field where it got an error before. Now it hangs and cancel hangs as well - I have to kill the tab.
You can also set a breakpoint in any line of code, and it ignores it.

This line of code is the first line in OnAfterGetRecord trigger for example:
CLEAR(CertText);
It ignores the breakpoint.
Should be easy for you to duplicate.

**Comment by davmac1** [comment]
The debugger appears to be working now most of the time. There are some other problems. Are they related to this update?
1) it takes several minutes to publish an update to a fairly small extension.
2) had errors 2 of the times I ran the same report. Running it a second time always works.
![ReportError1](https://user-images.githubusercontent.com/15961672/90674553-e65d6c80-e21e-11ea-936b-c0864301679f.JPG)
![ReportError2](https://user-images.githubusercontent.com/15961672/90674582-ef4e3e00-e21e-11ea-8054-6b8a9acbe092.JPG)

**Comment by atoader** [comment]
The errors you have mentioned are not related to the VSIX update. For issues related to the SaaS sandbox or the runtime, please open a customer support ticket. 

For the debugger issue, a repro should contain:
1. A zipped project attached to the thread.
2. A video recording of the launch/debug cycle
3. AAD ID of the tenant
4. Timeframe (UTC) when the issue happened

**Comment by AlexxBenn** [comment]
Just FYI, we faced similar cases as described above (sandbox environment):
1. Breakpoints are ignored by the debugger (VS Code updated to the latest version 5.0.320540) - in our case, after clearing browser cache problem gone. 
2. Now, whenever we publish an extension via uploading .app or via VS Code: running debugger first time after publishing is hanging web-client and then shows"Something went wrong...". Start debugging the second time - works fine.

But as you've mentioned we are going to create a customer support ticket.

**Comment by qutreson** [comment]
@davmac1 @AlexxBenn are you still facing this issue?

**Comment by davmac1** [comment]
Once I have set a breakpoint, the object will no longer run.
I have to login to the sandbox and run it. It will not run from publishing in VS Code.

**Comment by AlexxBenn** [comment]
@qutreson, In my case, seems that issue is gone. Works fine with the latest updates of VS Code and AL language.

**Comment by qutreson** [comment]
@davmac1 can you update to the latest AL extension and try your scenario again?

**Comment by davmac1** [comment]
Looks like it is working after the update
