### ISSUE TITLE
Rule AA0205 fired on global List variable

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6092]
This issue was homehow related: https://github.com/microsoft/AL/issues/5720

**Describe the bug**
When a List data type variable is declared globally, GlobalList.Count returns AA0205 (Use of unassigned variable) although Count is our means to test whether (!) the variable has been already assigned.

**To Reproduce**
```
codeunit 50000 "Test AA0205"
{
    var
        AllowedPrefixesList: List of [Text];

    procedure CheckSubmissionNoPrefix(Prefix: Text; var ErrorTxt: Text)
    begin
        if ErrorTxt <> '' then
            exit;

        if not IsAllowedPrefix(Prefix) then
            ErrorTxt := 'Some Error Message';
    end;

    local procedure IsAllowedPrefix(var Prefix: Text): Boolean
    begin
        LoadAllowedPrefixes();
        exit(AllowedPrefixesList.Contains(Prefix));
    end;

    local procedure LoadAllowedPrefixes()
    begin
        if AllowedPrefixesList.Count > 0 then // < ----- AA0205
            exit;

        AllowedPrefixesList.Add('P');
        AllowedPrefixesList.Add('K');
    end;
}
```

**Expected behavior**
GlobalList.Count should not throw a warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/34504100/90752217-6810d100-e2d7-11ea-8de9-99828ef98651.png)

**5. Versions:**
 - AL Language: 5.0.320540

 - Business Central: 16.0

**Comment by PaulIvan** [comment]
I am closing this issue because it appears that it has been resolved in the latest **developer preview**. Please open a new issue if you believe this has not been resolved and reference the current issue.
