### ISSUE TITLE
The field with name 'SystemCreatedAt' and ID '2000000001' was found in the previous version, but is missing in the current extension

### ISSUE THREAD

**Issue by jwikman** [microsoft/AL#6093]
**Describe the bug**
I'm using the preview version 6.0.314405 of AL Language to verify that our apps will publish on BC17.
When using AppSourceCop to validate the app against the previous released version, I get error on rule AS0002 for every table. 

Error message:
`The field with name 'SystemCreatedAt' and ID '2000000001' was found in the previous version, but is missing in the current extension. This might break the upgrade of existing installations.`

This is probably related to the upcoming feature documented here: https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/smb/dynamics365-business-central/data-audit-system-fields-are-added-every-table

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an app for BC16, the app should contain at least one table.
2. Build the app file and copy the file to .alpackages folder
3. Configure AppSourceCop to compare to above app file
4. Increase version in app.json
5. Restart VSCode
6. Try to build your app file

Now you should receive above error.

**Expected behavior**
No errors should be thrown on the new system fields

**Screenshots**
N/A

**5. Versions:**

 - AL Language: 6.0.314405

 - Business Central: 17.0.15704.0

**Comment by qutreson** [comment]
This issue should now be fixed in our developer preview for AL extensions with version higher than 6.0.323892.
