### ISSUE TITLE
Implicit with cannot be replaced for BC 17 in Page (Extensions)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6095]
**Describe the bug**
`Rec` cannot be used for Expression of Page Field Properties.

**To Reproduce**
Steps and to reproduce the behavior:
I added a field to a sales order subform:
```al
field("Prefix Test"; TestValue)
{
    ApplicationArea = All;
    Caption = 'Test';
    Editable = Rec.Type = Rec.Type::Item;
    QuickEntry = Type = Type::Item;
}
 ```
The expression `Editable = Rec.Type = Rec.Type::Item;` does not work with BC17. Altough the Expression without `Rec` does work perfectly.

**Expected behavior**
I would expect that I can use `Rec` to avoid implicit **with**.

**Screenshots**

![image](https://user-images.githubusercontent.com/56249171/90857474-7bc64100-e384-11ea-894a-5a5769919dc2.png)
**5. Versions:**

 - AL Language: 6.0.308593

 - Business Central: Version: DE Business Central 17.0 (Plattform 16.0.15023.0 + Anwendung 17.0.15096.0)

**Comment by ZepposBE** [comment]
Tested this on 17.0.16297.0 (Preview) and the enabled/Visible/...  Expression of Page Field Properties are working with Rec.xxx there.
Still causes pages to give an error on 16.5.15897.16301 though.
Keeping the Rec.xxx fixes for the 17 release then.
People using extensions to quickfix this issue on 16.5.15897.16301 versions and before will have to check all the fixes on page field properties and undo those changes.

**Comment by NKarolak** [comment]
You are trying to implement a new BC 17 feature to BC 16 (runtime 5.x), right?
Follow the discussion here: https://twitter.com/KarolakNatalie/status/1302858502688444416?s=20

**Comment by esbenk** [comment]
This is only supported on the BC 17 runtime. The Quick/Warning should be (will be) disabled for runtime version below < 6.0

**Comment by nndobrev** [comment]
Hi @pri-kise, we can't reproduce this issue on our latest version. Please feel free to reopen if you think it is still present.
