### ISSUE TITLE
Multiple extension of enum fail with System_14.0.44327 Application_14.16.44342

### ISSUE THREAD

**Issue by michele-bendazzoli** [microsoft/AL#6098]
**Describe the bug**
The enum can only be extended to the first level of dependencie

**To Reproduce**

App A 
enum 58906 "ALPUOM Type"
{
    Extensible = true;
    value(0; None) { }
    value(1; Weigh)
    {
        Caption = 'Weigh';
    }
}
App B depend from A and extend enum "ALPUOM Type"

enumextension 59200 "ALPWMUOM Type" extends "ALPUOM Type"
{
    value(59200; Liter)
    {
        Caption = 'Liter';
    }
}
App C depend from A and B and extends enum "ALPUOM Type"

enumextension 18129251 "ALPEXUOM Type" extends "ALPUOM Type"
{
    value(59250; "Liter hydrate")
    {
        Caption = 'Liter hydrate';
    }
    value(59251; "Liter anhydrous")
    {
        Caption = 'Liter anhydrous';
    }
}

Steps and to reproduce the behavior:
1. Create and Publish App A, App B and App C

``` AL Code to reproduce the issue ```
It fails to pubblish the app C also if there is no code in the apps.

**Expected behavior**
I try the same on Business central  16.4 and it works without problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/1478846/90890904-20fc0c00-e3bb-11ea-8b09-44254ac80c1d.png)

**5. Versions:**

 - AL Language: v5.0.320540

 - Business Central: Versione IT Business Central 14.16 14.0.44327.0

**Comment by thpeder** [comment]
HI @michele-bendazzoli,
Thanks for reporting the issue, but this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
