### ISSUE TITLE
SourceTable of the DrillDownPageID / LookupPageID must match the Table ID 

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6099]
**Title**
We sometimes make a full copy of table from Business Central to new tables, copy from an existing table to a buffer / temporary / staging / import table, ... When copying these source tables, sometimes the DrillDownPageID and LookupPageID are forgotten to be updated on the new target table and still reference to the 'old' source table, which is wrong. DrillDown and Lookup will not work properly on the newly created table, since the SourceTable of the pages referenced by DrillDownPageID / LookupPageID does not match the ID of the parent table.

**Description**

**Reason for the rule**
The rule will help the developer to detect table definitions containing invalid DrillDownPageID / LookupPageID properties that are not in line with the SourceTable used on these referenced pages.

**Bad code sample**

![image](https://user-images.githubusercontent.com/25268332/91166340-84937b80-e6d2-11ea-9e54-d3c5797b0a9f.png)

**Good code sample**

![image](https://user-images.githubusercontent.com/25268332/91166420-a42aa400-e6d2-11ea-835a-06ade6932e5f.png)

**Remarks**
Other bad code sample

![image](https://user-images.githubusercontent.com/25268332/91166775-2c10ae00-e6d3-11ea-93b0-812a27ec1579.png)

**Comment by dtkb** [comment]
Yes, please consider this. Otherwise we only discover later that the drilldown/lookup can't work, at runtime, when we could've fixed it at compile time right from the start.

**Comment by fvet** [comment]
https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/39

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
