### ISSUE TITLE
Publish Events

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#61]
Can you briefly share on how to publish to an event?  I found how to subscribe to it (there is even a snippet) .. and expecting quite the same for publisher, but I couldn't figure out how.. .  ("EventPublisher" is not a valid attribute).

**Comment by StanislawStempin** [comment]
Event publishers are specified through the [Integration] and [Business] attributes (for an Integration and Business event respectively)

Integration attribute has two parameters: IncludeSender : Boolean and GlobalVarAccess: Boolean.
Business attribute has one parameter:  IncludeSender : Boolean

Here's an example:
[Integration(false, false)]
PROCEDURE OnNewCheckRemoveCustomerNotifications(RecId : RecordID;RecallCreditOverdueNotif : Boolean);
  begin
  end;

IntelliSense for attributes is coming in the January Update.

**Comment by waldo1001** [comment]
thanks!

**Comment by waldo1001** [comment]
And it's working just fine.

some totally useless code that proves it :-)

Codeunit 70066091 RentalSubscriptions
{
    [EventSubscriber(ObjectType::Table, 27, 'OnAfterModifyEvent', '', true, true)]
    local procedure TestMessage();
    begin
        message('Event is working!');
        OnAfterTestMessage();
    end;

    [Integration(false, false)]
    PROCEDURE OnAfterTestMessage();
    begin
    end;
        
    [EventSubscriber(ObjectType::Codeunit,70066091, 'OnAfterTestMessage', '', true, true)]
    local procedure TestMessage2();
    begin
        message('Published event Event is working!')        
    end;
}
