### ISSUE TITLE
 Common Data service connection setup issue in BC17

### ISSUE THREAD

**Issue by Nagaraju17** [microsoft/AL#6101]
**Describe the bug**
We are using BC17 docker environment and trying to configure Common Data service connection setup from assisted setup. After giving Connection URL, I just clicked on "Sign in with Administrator user" then am getting below error. Can some one assist on this.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Common Data service connection setup from Assisted Setup 

``` AL Code to reproduce the issue ```

**Expected behavior**
Should not give the error
**Screenshots**
![image](https://user-images.githubusercontent.com/30176345/91179658-71010880-e704-11ea-87a6-a637a3517d1d.png)

**5. Versions:**

 - AL Language: 

 - Business Central: NL Business Central 17.0 (Platform 17.0.15455.0 + Application 17.0.15704.0)

**Comment by crraita** [comment]
Thanks for reporting the issue.

Do you have an extension subscribing to OnGetCDSConnectionClientId or OnGetCDSConnectionClientSecret and providing different ClientId and ClientSecret to the setup?

**Comment by Nagaraju17** [comment]
Hi Crraita,

No, We are not using any Extensions. We are faction this issue in newly configured environment of BC17 Saass Docker Image.
Is there any limitation for Saas and Onprem Docker images for CDS connection setup ?. 
Earlier we had configured CDS in BC16.0 Saas version by providing Username and Password in CDS setup page. But now we are not able to see these fields in CDS setup page. So we tried to configured it from Assisted Setup page which is giving the error which we mentioned above.
Is there any different way to Configure CDS in BC17 version ?. 
![image](https://user-images.githubusercontent.com/30176345/91435303-bef04a80-e883-11ea-9134-2f2e88e5d946.png)

Thank You

**Comment by crraita** [comment]
In BC17 we are logging in to Common Data Service with OAuth2, and for security concerns, the docker images don't have access to Azure Key Vault. 

If you would like to work with Common Data Service from a docker container, what you can do is publish a sample PTE and inject the clientId and clientSecret of your Azure app to connect to.

Sample code:

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"CDS Integration Impl.", 'OnGetCDSConnectionClientId', '', false, false)]
    local procedure OnGetCDSConnectionClientId(var ClientId: Text)
    begin
        ClientId := PartnerDefinedAppClientId;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"CDS Integration Impl.", 'OnGetCDSConnectionClientSecret', '', false, false)]
    local procedure OnGetCDSConnectionClientSecret(var ClientSecret: Text)
    begin
        ClientSecret := PartnerDefinedAppClientSecret;
    end;

If you would like to learn more about how to create an app, the process is similar to the mandatory process for On-Premises versions, that is described in [Connecting On-Premises Versions](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-set-up-a-dynamics-crm-connection#connecting-on-premises-versions).

This is not going to be required live or in the official sandbox [preview environments](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/preview-environments), it is only if you are working with Docker.

**Comment by qutreson** [comment]
I am closing this issue because it appears that it has been resolved and did not have any activity in the last two weeks. Please open a new issue if you believe this has not been resolved and reference the current issue.
