### ISSUE TITLE
Dom't validate for Enum, Option Fields when apply config. package

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/AL#6102]
**Describe the bug**
When I import config. package with fields type: enum, option. I setup to Run Validate trigger of these fields.
But the OnValidate trigger is not executed.

**To Reproduce**
I add "E-Invoice Type" field with dataType=enum.
![image](https://user-images.githubusercontent.com/24407031/91250780-0a233400-e784-11ea-8ba3-dfed66fb0b8d.png)

I create config package and import
![image](https://user-images.githubusercontent.com/24407031/91250265-c7ad2780-e782-11ea-8890-2e784a2ce757.png)

Set validate field:
![image](https://user-images.githubusercontent.com/24407031/91250349-0642e200-e783-11ea-9616-3ece35d8acf4.png)

Run Apply Package

When I debug, I see:

1. Before get OptionNo, the FieldRef is blank (Old OptionNo=0), IntVar and IntVar1 is 0.
![image](https://user-images.githubusercontent.com/24407031/91250649-bca6c700-e783-11ea-92af-22e8fecef643.png)

2.After Get OptionNo=1. But, FieldRef also is change to VAT Invoice (OptionNo=1)
![image](https://user-images.githubusercontent.com/24407031/91250945-69814400-e784-11ea-98fd-6b1f41be514d.png)

3.So, when system get Old OptionNo to compare with New Option No. the value is the same.
The validate is not executed even though ToValidate=true.
![image](https://user-images.githubusercontent.com/24407031/91251099-deed1480-e784-11ea-9e8b-7c8ddf5020da.png)
![image](https://user-images.githubusercontent.com/24407031/91251128-f4623e80-e784-11ea-8a20-f1cb0c85a397.png)

**Expexted: Old OptionNo should get form step 1 (before get new OptionNo)**

**Expected behavior**
OnValidate trigger must be executed.

**5. Versions:**
 - AL Language:  v5.0.320540
 - Business Central: W1 16.3 (Platform 16.0.14073.14195 + Application 16.3.14085.14238)

**Comment by hgnamvn** [comment]
Any update for this problem???

**Comment by qutreson** [comment]
Hi @hgnamvn, thank your for reporting this issue. This looks like a runtime issue. Let's get it to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue (including a simple self-contained project would be really valuable), and the Business Central build number and country version you're using.

**Comment by navdotnetreqs** [comment]
Still relevant
