### ISSUE TITLE
Flashing BC Dialog Window If Updated/Created Through JavaScript Control-Add-In

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/AL#6111]
**Describe the bug**
If a dialog window is created or updated through an event fired by a JavaScript Control-Add-In it the dialog window will disappear immediately.

**To Reproduce**
I created a repository containing the code that is producing the error: https://github.com/Sven-Niehus/BC_FactBoxDialogFlashBug/

You need to open page 50100 to recreate the issue.

**Expected behavior**
The dialog is created or updated normally.

**Screenshots**
Behavior if created/updated through an OnDrilldown trigger:
![2020-08-28_11-34-50_bt5lq1Bu35](https://user-images.githubusercontent.com/9822857/91546656-15f92c80-e923-11ea-9c0c-a3a06329f57d.gif)
Behavior if created/updated through custom Control-Add-In events:
![2020-08-28_11-38-44_UUtHMJP66U](https://user-images.githubusercontent.com/9822857/91546756-3cb76300-e923-11ea-9a80-9803a8270d18.gif)

**5. Versions:**

* AL Language: 
    - Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.323892
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
    - Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.320540
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: 
    - latest 16.x docker image (Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.4.15445.0))
    - latest 17.x docker image (Business Central 17.0 (Platform 17.0.15855.0 + Application 17.0.15904.0))

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by Sven-Niehus** [comment]
@thpeder this issue does exist in the latest developer preview of BC

**Comment by aptMattKoe** [comment]
is this not a "AL compiler in latest developer preview environment"-Error? Or how could we add those kind of well documented errors/problems/bugs?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
