### ISSUE TITLE
Problem with System Fields "Created At" and "Modified At"

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#6113]
**Describe the bug**
We are not yet sure if this is a bug or not.

We have a curious error when handling data in the new system fields "Created At" and "Modified At". Basically (short version) these fields appear to save the timestamp in ISO 8601 format as for example "2020-08-28T09:08:00.0000000Z".

That appears to be incompatible with BCs expectation how a DateTime should look like, So trying to EVALUATE(SomeDateTime,"2020-08-28T09:08:00.0000000Z") fails: 
"The value "2020-08-28T09:08:00.0000000Z" can't be evaluated into type DateTime."

**To Reproduce**
```CAL
// retrieve value of Rec."Created At" into a TextVar and then do:
EVALUATE(SomeDateTimeVariable,TextVar);
```

**Expected behavior**
Either: Confirm nobody is supposed to use the fields contents in AL and make it inaccessible (also for FieldRef)
Or: Make EVALUATE accept ISO 8601 Strings
Or: Save to database as compatible String Format
Or: Other explanation... we are not sure what is what here after all :-)

**Screenshots**
n.a.

**5. Versions:**
AL Language: v6.0.321546
Business Central: Platform 17.0.15765.0 + Application 17.0.15854.0

**Comment by thpeder** [comment]
Hi @RafaelKoch,
First of, you are suppose to be able to access them from code.

if you just want to find a way to convert the text to a datetime, then I would suggest you use the following resources
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

However if you want to see the evaluate function changed then let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by RafaelKoch** [comment]
@thpeder : This is about the new fields in V17 somwhow saving the timestamp differently than other DateTime Fields seem to do. At least it looks that way. Is this intentional or did we just overlook something?

**Comment by thpeder** [comment]
The format the data is written in is picked on purpose, but unfortunately the evaluate function can handle it so I don't think there is something you have missed.

**Comment by RafaelKoch** [comment]
So - reopen? Because how will we make use of that field in AL code?

**Comment by thpeder** [comment]
I did a bit of searching around and found this: https://forum.mibuso.com/discussion/51130/iso-8601-datetime-format
