### ISSUE TITLE
Disable AA0217 for filter expressions

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6115]
**Describe the bug**
I'd like to question rule AA0217 being applied on filter expressions like these (example taken from standard code):
`FilterText := StrSubstNo('@*%1*', LowerCase(FilterText));`

Warning AA0217:
> Use a text constant or label for format string in StrSubstNo.

I understand the rule wants to prevent text (e.g. for error messages) being put into StrSubstNo directly instead indirectly by labels. However, the example above is a case where using a label would absolutely make no sense; and it would make the code less readable without any gain.

**Expected behavior**
No warning for filter expressions, hence texts including @, * or |.

**Versions:**
 - AL Language: 6.0.323892

**Comment by dtkb** [comment]
Other people's filter expressions might contain other characters that could make determining whether or not something is meant to be a filter expression (more) problematic.

Aside: Do "text constants" even still exist? And even if not, shouldn't `Label`s be the sole recommendation, since the old way of doing ML including `TextConst` is long deprecated? Such messages could then use updating not to recommend people to use old/wrong ways.

**Comment by NKarolak** [comment]
You could narrow down the search to * or |. Imho, introducing this check would heal more false positives than unintentionally hide true positives.
I agree about the text constants in the warning message.

**Comment by AskeHolst** [comment]
I would suggest having the rule apply _only_ when there are letters in the text. Texts without letters would almost warrant using a label.

**Comment by stefanoPrimo** [comment]
I have a code that is like that:
`StrSubstNo('%1|%2', SalesHeader."Document Type"::Order, SalesHeader."Document Type"::"Return Order");`
I think that that it is already a text constant, why this warning?

**Comment by stefanoPrimo** [comment]
Just find out a orrible workaround, but still a workaround:
just add a copystr 😃 
`StrSubstNo(CopyStr('%1|%2', 1, StrLen('%1|%2')), SalesHeader."Document Type"::Order, SalesHeader."Document Type"::"Return Order");`

**Comment by AskeHolst** [comment]
Adding a #pragma to disable the warning temporarily might be a solution
`
#pragma warning disable AA0217
StrSubstNo('%1|%2', SalesHeader."Document Type"::Order, SalesHeader."Document Type"::"Return Order");
#pragma warning restore
`

**Comment by stefanoPrimo** [comment]
it could be true if I was on a BC17, but for now, I'm stuck in BC16

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
