### ISSUE TITLE
Rule214BlindWriteLocalRecord exception (part 2)

### ISSUE THREAD

**Issue by kasperdj** [microsoft/AL#6116]
**Describe the bug**
The CodeCop still breaks in our projects and below is an example of this using the latest AL Language extension and working on a BC 16.2 DK OnPrem project:

![image](https://user-images.githubusercontent.com/54669593/91800755-ddf72f80-ec29-11ea-89a9-474e8fd47538.png)

Note: if we activate the AppSourceCop in the same project, then the compiler bugs related to the CodeCop goes away - maybe it's a priority in the compiler:

![image](https://user-images.githubusercontent.com/54669593/91800799-f8c9a400-ec29-11ea-8f46-4ec0c37fbd43.png)

**To Reproduce**
I cannot provide step-by-step instruction, BUT I can share a private link to a AL Project that has this issue.

**Comment by MarcHansenMicrosoft** [comment]
thanks

**Comment by kasperdj** [comment]
@MarcHansenMicrosoft if you drop me at mail at krj@elbek-vejrup.dk then I will provide a project you can use for the troubleshooting analysis.

**Comment by kasperdj** [comment]
Any updates on this issue?
We have so many CodeCop errors in our projects related to app.json and these different kind of "runtime error" in the compiler that we no longer trust the code analysis!

Also I have enclosed another one in attached screenshots incl. how to "resolve" the error - and the fix gives no meaning.....

![CodeCop ToolTip Error](https://user-images.githubusercontent.com/54669593/93752942-ab749d00-fbff-11ea-8572-94a6fb0410b2.png)
![CodeCop ToolTip Error - how to fix but give no meaning](https://user-images.githubusercontent.com/54669593/93752950-ae6f8d80-fbff-11ea-97c9-3c2d4969b291.png)

**Comment by PaulIvan** [comment]
Hi @kasperdj I've send you an email, please share the project that is triggering this error

**Comment by kasperdj** [comment]
@PaulIvan 2 x projects examples provided via a private link

**Comment by PaulIvan** [comment]
Hi @kasperdj I can see that the rule has indeed been fixed in June.
Please try the latest developer preview https://github.com/microsoft/AL#al-developer-preview-builds

**Comment by kasperdj** [comment]
Hi @PaulIvan 

It seems like the new AL Compiler you roled out today have solved the problem for this issue.
It also introduced a lot of warnings in my projects due to new code cop rules etc.
