### ISSUE TITLE
On table with RecordID in Primary Key the system part "Link" not working on view

### ISSUE THREAD

**Issue by Drakonian** [microsoft/AL#6117]
**Describe the bug**
On table with RecordID in Primary Key the system part "Link" is not working on view.  So, my table:

``` 
table 60008 "XPL Media Entity"
{
    Caption = 'Media Entity';
    DataClassification = CustomerContent;
    DrillDownPageId = "XPL Media Entity";
    LookupPageId = "XPL Media Entity";
    fields
    {
        field(1; "Record ID"; RecordId)
        {
            Caption = 'Record ID';
            DataClassification = CustomerContent;
            Editable = false;
        }
        field(3; "Entry No."; BigInteger)
        {
            Caption = 'Entry No.';
            DataClassification = CustomerContent;
            AutoIncrement = true;
        }
 }
    keys
    {
        key(PK; "Record ID", "Entry No.")
        {
            Clustered = true;
        }
    }
}
 ```

My page:
``` 
page 60009 "XPL Media Entity"
{

    ApplicationArea = All;
    Caption = 'Media';
    PageType = List;
    SourceTable = "XPL Media Entity";
    UsageCategory = Lists;
    SourceTableView = sorting("Presentation Order");

    layout
    {
        area(content)
        {
            repeater(General)
            {
            
                field(Description; Description)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the Description';
                }
             
            }
        }
        area(FactBoxes)
        {
            systempart("XPL Links"; Links)
            {
                ApplicationArea = RecordLinks;
            }
        }
    }
}

 ```
After, I try to add some Links to my list page and they added but not showing in systempart:
![image](https://user-images.githubusercontent.com/16802407/91862535-c5613680-ec76-11ea-8a99-4e766027908c.png)

 Also, when I inspect system table "Record Link" the record belongs to my table "XPL Media Entity" is presented.
![image](https://user-images.githubusercontent.com/16802407/91861631-b9c14000-ec75-11ea-8d49-76ca3fb64926.png)

**Expected behavior**
This is due to the fact that the system cannot successfully read RecordID + Integer from PK of my table within the system table PK RecordID. This functionality just should work.

**5. Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/25268332/91690548-6d3b0f00-eb66-11ea-82b8-4d634b1dad30.png)

 - Business Central:
Applies to BC 14, 15, 16

**Comment by thpeder** [comment]
HI @Drakonian,
Thanks for reporting the issue.
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
