### ISSUE TITLE
ToolTip is missing when CaptionClass is applied to the fields on extension card pages.

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/AL#6118]
**Describe the bug**
We used "**CaptionClass**" property for a base field on extension **card pages**. So, the ToolTip is missing on BC screens. For the field on list pages, it's working fine.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to VS Code
2. Create an extension card page.
3. In the layout section, modify any base field by applying CaptionClass preperty.
4. Publish and check the tooltip by hover the cursor on field. 

``` AL Code to reproduce the issue ```
pageextension 50091 "Customer Card Ext." extends "Customer Card"
{
    layout
    {
        modify("No.")
        {
            CaptionClass = 'Customer ID';
        }
   }
}
**Expected behavior**
We should get the ToolTip from base to the filed on extension card pages even if we use CaptionClass property.

** Versions:**

 - AL Language: 6.0.293448

 - Business Central: 17.0 (Platform 16.0.14248.0 + Application 17.0.14286.0)

**Comment by thpeder** [comment]
Hi @Rambabu-Billuri,
If you have a control on a regular page then having CaptionClass means that it will not show the tooltip, this is not an issue with the editor tools so let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
