### ISSUE TITLE
Could not install the extension XXXX on tenant default due to the following error: 'The User table is empty.' 

### ISSUE THREAD

**Issue by dbsae** [microsoft/AL#6121]
**Describe the bug**
We are facing issues if there is no user in the tenant instance. This error is only happening in our internal builds of Microsoft  It works fine during validation and works fine for customers in production.

        "Reason":  "Could not install the extension XXXX  on tenant default due to the following error: 'The User table is empty.' and AL stack trace:
"XXXX  License"(CodeUnit 70201311).RegisteredXXXX  - XXXX 
"XXXX  Install"(CodeUnit 70201300).InstallXXXXSetup - 
 "XXXX Install"(CodeUnit 70201300).OnInstallAppPerCompany - 
""Extension Triggers""(CodeUnit 2000000010).OnInstallAppPerCompany line 2

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by dtkb** [comment]
So, it looks like your `License Codeunit` is doing a `FindSet()` or similar, doesn't it? Then why not just to `if not FindSet() then exit` to make an empty table non-fatal?

**Comment by dbsae** [comment]
It's not a table. It's using external webservices in which we capturing the user information while installation of the app.

**Comment by dtkb** [comment]
It still looks like some code is trying to load some set of record(s), where none exist, without using `if` to indicate that 0 results is OK

Did the original stack trace have line numbers in it? Can you determine what AL statement it's failing on?

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

If you can notice a bug related to your scenario, please open a new Github issue, referencing this one, with a self contained project reproducing the issue. Please also provide the AL extension version and the version of BC you are targeting.

**Comment by atoader** [comment]
@dbsae can you try using the latest development preview and debug the install code? @thloke can you provide some guidance on how this can be setup.

**Comment by thloke** [comment]
If you're using the latest development preview, we have enabled debugging install and upgrade code. This will come in our next major release, but you can try it now to see if it sheds light on your issue. The flow to debug install code is:

1. Build your project. This step is important even if you have previously built it, as we will be publishing the built .app file and it has to have a unique package ID.
2. Setup breakpoints in your install codeunit.
3. Initiate a debug attach. You may need to add an attach configuration to your `launch.json` if you don't have an attach configuration. [See here for docs on how to set up attach](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-attach-debug-next)
4. Ensure that in your attach configuration, `breakOnNext` is set to `WebServiceClient`
5. Attach
6. Using `Ctrl+Shift+P` bring up the command menu and execute the `Publish extension without building` command
7.  Your breakpoint should be hit and you can now debug your install codeunit.

If you have any problems with the above flow, let me know.
