### ISSUE TITLE
view crashes after open

### ISSUE THREAD

**Issue by SarahBirrer** [microsoft/AL#6122]
Since BC 16.0.0.0 views don't work anymore. In my example, I'm extending the "Job List" and try to add a view which only filters on Status = Completed. The other on a boolean "Canceled"
After clicking the view, the Webclient crashes and needs a restart. When I'm on my custom page, the view work fine. Is this a bug or could it be a wrong definition?

Here is my code:
```al
pageextension 50000 "LOGPJJob List" extends "Job List" //89
{
    views
    {
        addlast
        {
            view(LOGPJCompleted)
            {
                Caption = 'Completed';
                Filters = where(Status = Const(Completed));
            }
            view(LOGPJCanceled)
            {
                Caption = 'Canceled';
                Filters = where(LOGPJCanceled = Const(true));
            }
        }
    }
}

```
I BC 15.0.0.0 the views worked fine.

**Comment by qutreson** [comment]
@SarahBirrer, I cannot completely re-use the snippet you provided because I don't know how the field LOGPJCanceled is defined, so I had to remove this filter. However, publishing this code worked fine for me and I did not experience any crash:

![image](https://user-images.githubusercontent.com/31541422/92361444-aa674a00-f0ee-11ea-9e8a-20db23b99031.png)

As requested by our template for Github issues, can you provide us with:
- the version of the AL extension that you are using,
- the version of BC that you are testing against,
- a self contained project that can be used to reproduce the issue?

**Comment by SarahBirrer** [comment]
@qutreson 
The Code of the Field "LOGPJCanceled" is:

```
        field(50000; LOGPJCanceled; Boolean)
        {
            Caption = 'Canceled';
            DataClassification = CustomerContent;
            trigger OnValidate()
            begin
                if LOGPJCanceled = true then
                    Validate(Status, Status::Completed);
            end;
        }
```

I'm using tAL Lanugage v5.0.320540

the version of BC that you are testing against,
a self contained project that can be used to reproduce the issue?
the version of BC that you are testing against,
a self contained project that can be used to reproduce the issue?

**Comment by qutreson** [comment]
@SarahBirrer, thank you for your answer, but I am still not able to reproduce the issue.

Here is the code that I have used based on your previous comments:
```
pageextension 50100 "LOGPJJob List" extends "Job List"
{
    views
    {
        addlast
        {
            view(LOGPJCompleted)
            {
                Caption = 'Completed';
                Filters = where(Status = Const(Completed));
            }
            view(LOGPJCanceled)
            {
                Caption = 'Canceled';
                Filters = where(LOGPJCanceled = Const(true));
            }
        }
    }
}

tableextension 50100 MyExtension extends Job
{
    fields
    {
        field(50000; LOGPJCanceled; Boolean)
        {
            Caption = 'Canceled';
            DataClassification = CustomerContent;

            trigger OnValidate()
            begin
                if LOGPJCanceled = true then
                    Validate(Status, Status::Completed);
            end;
        }
    }
}
```
This is how the view 'Completed' looks like:

![image](https://user-images.githubusercontent.com/31541422/93064355-b5365780-f677-11ea-8153-b609e2bd3051.png)

This how the view 'Canceled' looks like:

![image](https://user-images.githubusercontent.com/31541422/93064411-c97a5480-f677-11ea-9e6e-e6bbaee5bf1d.png)

When navigating from one view to the other, or when navigating back to the default view 'All', I do not experience any crash.

Can you verify this scenario on a build coming from our latest developer previews to see if the issue reproduces there?
If that still reproduces, can you share a video recording or some screenshots of the issue experienced in the web client?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
