### ISSUE TITLE
Constant Prompts to Authenticate

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6124]
**Describe the bug**
I authenticate to download the symbols. I then try to publish to the sandbox. I am asked to authenticate again. I later attempt to debug. I am asked to authenticate again. These prompts are constant. Maybe 1 in 10 I don't get it, and it uses the cached credentials as it should.

**To Reproduce**
Just try publishing???

**Expected behaviour**
Don't ask me every minute, on every action. I can understand asking this after a certain time frame, i.e. having them expire. But this is constant.

**Screenshots**
![image](https://user-images.githubusercontent.com/16603906/92158846-c1095a80-ede9-11ea-807d-c48fef63f5f3.png)

**5. Versions:**

 - AL Language: 5.0.320540

 - Business Central: US Business Central 16.4 (Platform 16.0.14648.15997 + Application 16.4.14693.15090)

**Comment by NKarolak** [comment]
Try specifying the tenant: https://twitter.com/steveendow/status/1295383415764611073

**Comment by mjmatthiesen** [comment]
> Try specifying the tenant: https://twitter.com/steveendow/status/1295383415764611073

This is on a SaaS instance, not a docker.

**Comment by NKarolak** [comment]
Sorry :-)
Then, I'd try downgrading the AL Language extension.

**Comment by Joriek** [comment]
Not a long term solution but you can set the al.useLegacyRuntime property to true in the settings.json file

**Comment by mjmatthiesen** [comment]
> Not a long term solution but you can set the al.useLegacyRuntime property to true in the settings.json file

I can confirm that this appears to work.


This isn't ideal, and I think the BC team still needs to look at resolving this long term.

**Comment by fartwhif** [comment]
the source downloading component is dilapidated and broken in general, please do something different...
