### ISSUE TITLE
Sync-NAVApp : The following SQL error was unexpected: Either the parameter @objname is ambiguous or the claimed @objtype (INDEX) is wrong.

### ISSUE THREAD

**Issue by abrarShaikh273** [microsoft/AL#6125]
**Describe the bug**
I am upgrading V14 to V16 with customized CAL,
I am following link below:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app

I am stuck on Task 10: Synchronize tenant:
3.Synchronize the tenant with the table migration extension.

**Expected behavior**
App must be Sync completely with out any error:

**Screenshots**
![image](https://user-images.githubusercontent.com/57489444/92165395-9bd21780-edfc-11ea-9819-c57f5a312494.png)

**5. Versions:**

 - AL Language: 5.0

 - Business Central: V16.4  Application:16.4.15445.0

**Comment by thpeder** [comment]
Hi @Devango,
Let's get the issue to a team who will fix and backport it in a timely manner, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by ewaldventer** [comment]
I have this issue. For some reason, indexes were missing for a table in a company.
Found the error in the event log and found which table gave the issue. 
![image](https://user-images.githubusercontent.com/8598877/106904292-b1c56a80-6703-11eb-93e7-c79925570779.png)


Compared its indexes to that of the same table in another company and scripted and recreated the missing indexes with t-sql.

Hope it helps!
