### ISSUE TITLE
Selected line unreadable in subpage wizard

### ISSUE THREAD

**Issue by MOomenMYS** [microsoft/AL#6127]
**Describe the bug**
Our application contains multiple wizards which have been converted to AL without problems. But when we step through the wizards some of the subpages exhibit peculair behaviour; the selected line in the ListPart is unreadable. It seems as if there is a different line superimposed on the selected line. See first and second screenshots for example. 

**To Reproduce**
See AL Code

``` AL Code to reproduce the issue ```
- A wizard page with (at least) 2 subpages, see third screenshot.
- The content on subpage2 is dependant on the choice made on subpage1, see fourth and fifth screenshot.
- Removal of the CurrPage.Update() in the fifth screenshot solves the readability problem, but then a second different choice on subpage1 doesn't update subpage2.
- After much trial and error we find that a Reset(), see screenshot 6, solves the problem, but we do not understand why.

**Expected behavior**
Readable selection with code that had no issues with earlier (C/AL) versions

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/70754759/92232968-bca77500-eeaf-11ea-84d3-80d08ca51f3c.png)
2. 
![image](https://user-images.githubusercontent.com/70754759/92233049-dea0f780-eeaf-11ea-9347-3e42f4254c9c.png)
3.
![image](https://user-images.githubusercontent.com/70754759/92233591-d5fcf100-eeb0-11ea-9e10-f50361c71f9b.png)
4.
![image](https://user-images.githubusercontent.com/70754759/92237007-e4e6a200-eeb6-11ea-84da-cd96db85a3b3.png)
5.
![image](https://user-images.githubusercontent.com/70754759/92237073-0051ad00-eeb7-11ea-9610-a45947ffa6ca.png)
6.
![image](https://user-images.githubusercontent.com/70754759/92237573-dfd62280-eeb7-11ea-9938-21445390bb4a.png)

**5. Versions:**

 - AL Language: v5.0.320540

 - Business Central: NL Business Central 16.4 Mysolution System Application 16.1.20247.9 (Platform 16.0.14648.15420 + Application 14.9.39277)

**Comment by dtkb** [comment]
looks like one of the placeholder lines shown when a list box has been rendered but the data not loaded into it yet

**Comment by qutreson** [comment]
@MOomenMYS can you share here the source code for a simple self-contained project that reproduces the issue?

**Comment by MOomenMYS** [comment]
@qutreson Attached you will find a project. But the strangest thing is that the problem does not occur here? While the only changes I've made are changing the sourcetables to match default tables Customer and Customer Bank Account instead of Resource and our own Project Resource.
[ALProject8.zip](https://github.com/microsoft/AL/files/5231424/ALProject8.zip)

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
