### ISSUE TITLE
[Event Request] OnShowCompanyBadgeTooltip

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/AL#6129]
Currently, the 'Company Badge' feature in Business Central allows a customer to display a four character colored badge at the top-right of the business central UI and when clicked, displays the current company name in the tooltip. There is currently no event publisher to override the tooltip text. It always displays the company name.

There are scenarios where we would like more flexibility than this and display custom data in the tooltip.

A simple event publisher OnShowCompanyBadgeTooltip(var ToolTipText: text; var IsHandled: boolean) would satisfy this requirement! With it, extension developers can can render whatever is needed into the tooltip box.

Also allow the event subscriber to use CRLF placeholders in the tooltip text payload e.g.:

```
TooltipText := STRSUBSTNO('Company:\%1\User:\%2', COMPANYNAME, USERID);
IsHandled := true;
```

Would render the tooltip as:
```
Company:
CRONUS International Ltd.
User:
MYDOMAIN\JOHNDOE
```

**Comment by qutreson** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
