### ISSUE TITLE
The compilation target is set to 'OnPrem', but it must be set to 'Cloud' or 'Extension'. > Fails in Multiroot workspace

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6130]
**Describe the bug**
When working with multiroot workspaces, with a mixed set of extensions (having both OnPrem and Cloud/Extension apps and different CodeCops), rules of Cloud apps are (wonrgfully) applied to OnPrem apps.

This blocks us in making full use of the workspace features, since part of our apps have been build for AppSource, where other apps have not yet / will not be targetted for AppSource, although all our apps should be able to be managed from within one workspace.

**To Reproduce**
Steps and to reproduce the behavior:
- Create one App with target 'Cloud' and CodeCop 'AppSourceCop' enabled.
- Create one dependend App with target 'OnPrem' and CodeCop 'AppSourceCop' not enabled.
- Create a code-workspace file with CodeAnalysis enabled 
- Open the workspace
- The second app will fail on "The compilation target is set to 'OnPrem', but it must be set to 'Cloud' or 'Extension'." since it seems like the AppSourceCop of the first app is wongfully applied to the second app as well.

**Expected behavior**
The CodeCops set in the settings.json of the apps / folder, should only apply to the scope of the app / folder and not to other apps when opened via a multiroot workspace.

**Screenshots**

![image](https://user-images.githubusercontent.com/25268332/92579574-a7ef2680-f28d-11ea-9195-e1c5b4ba7bff.png)

Sample project enclosed
[Demo.zip](https://github.com/microsoft/AL/files/5194020/Demo.zip)

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/92579619-b76e6f80-f28d-11ea-87cb-cb2bdda9b6c5.png)

**Comment by qutreson** [comment]
@fvet, thank you for reporting this issue, I was able to reproduce it following your repro steps

**Comment by thloke** [comment]
Closing as this has been fixed.
