### ISSUE TITLE
UploadIntoStream doesn't work in macOS

### ISSUE THREAD

**Issue by kaciurinas** [microsoft/AL#6132]
**Describe the bug**
We are using UploadIntoStream(DialogTxt, '', 'All Files (*.*)|*.*', ImportFromFile, InStr) to upload files. Client, which is on cloud, is trying to import file using macOS and on Mac this allows the user to look for files, but none of the files can be selected. On Windows everything is working well.

"Attach File" functionality in Incoming Documents page is working well, however I see that it uses functions from File Management codeunit but I believe we cannot use those in an extension.

``` AL Code to reproduce the issue ```
IF UploadIntoStream(DialogTxt, '', 'All Files (*.*)|*.*', ImportFromFile, InStr) then begin
                    "Attachment File".CreateOutStream(OutStr);
                    CopyStream(OutStr, InStr);
                    "S4RE File Name" := COPYSTR(FileMgt.GetFileName(ImportFromFile), 1, MAXSTRLEN("S4RE File Name"));
                    "File Extension" := COPYSTR(UPPERCASE(FileMgt.GetExtension(ImportFromFile)), 1, 250);
                    exit(true);

**Expected behavior**
User should be able to select a file.

**Versions:**
 - Business Central: NL Business Central 16.4 (Platform 16.0.14648.16184 + Application 16.4.14693.15090)

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
