### ISSUE TITLE
Action Image "Discount" has poor picture 

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/AL#6134]
**Describe the bug**
The Action Image "Discount" only shows a blue filled circle.

**To Reproduce**
Choose "Discount" as Action Image Property.

**Expected behavior**
It should show the percent sign inside the blue filled circle.
As you would expect with the preview image from old Windows Client Image..

**Screenshots**
In AL
![image](https://user-images.githubusercontent.com/34675109/92604811-39bc5b00-f2b1-11ea-8bbb-2e6c5c99c9f9.png)
In Webclient:
![image](https://user-images.githubusercontent.com/34675109/92605460-0a5a1e00-f2b2-11ea-9da7-4123a9d11c46.png)

**5. Versions:**
 - AL Language: 5.0.329509

 - Business Central: 16.5.15897.16301

**Comment by qutreson** [comment]
This issue appears to be beyond the scope of this repository.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
