### ISSUE TITLE
[PageExtension] Page level property modification - DelayedInsert

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/AL#6135]
Hi

Currently it looks as if it's not possible to modify the page property DelayedInsert from a Page Extension. Are there any plans to allow this in the future?

Thanks!

**Comment by qutreson** [comment]
Hi @andersnordmann, thank you for the suggestion. AFAIK we don't have anything tracking the request for making DelayedInsert extensible. We would then advise you to post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
