### ISSUE TITLE
[AA0175] Wrong Warning

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6138]
**Describe the bug**
If you want you find out if a value is inside an filter, this following code is one way to do this. But the CodeCop Rule AA0175 detects this as wrong and says:

> Variable 'GLAccount' queries the database in 'CreateClearingEntry' but does not use the queried record. Only find or get record if you need to access the values. Consider using ISEMPTY. 

**To Reproduce**
``` 
GLAccount.Reset();
GLAccount.SetFilter("No.", MyAccountFilter);
GLAccount."No." := GLAccountNo;
if GLAccount.Find('=') then begin 
  // true if GLAccountNo was inside of MyGLAccountFilter
  [..]
end;
```

**Expected behavior**
No warning in this case.

**5. Versions:**
 - AL Language: 6.0.324421
 - Business Central: 16.5

**Comment by dtkb** [comment]
A better way anyway, which doesn't require pulling over a row of data that is not used, would be to use 2 different filter groups and set one filter on `No.` in each.

**Comment by PaulIvan** [comment]
Hi @DanielGoehler I'm gonna have to agree with dtkb. 
The rule is working perfectly fine for what it is intended.

You have a very niche case of using records to determine if a No. is within a filter range, this can be done in other ways.
One way is to use filter groups, the other way is to use a temp table insert, filter and IsEmpty.

Please try the suggestions, if you agree I will close this issue in 1 week

**Comment by DanielGoehler** [comment]
Is okay. Will that also be change in the Base App? e.g.

![2020-12-18 15_40_04-](https://user-images.githubusercontent.com/9556549/102626661-67822d00-4147-11eb-9ddd-e02cfdcf5e82.png)

**Comment by PaulIvan** [comment]
We're not currently looking at changing base app for this purpose. I will close this issue now 😃
