### ISSUE TITLE
Scope - Application Areas

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#614]
Hi,

I see quite some changes in the "application areas".

Can anyone point me in the right directions on the documentation on this.  I have questions like:
- how are we supposed to "use" it in an app
- should we/can we create our own application area 
- how do customers add/remove application areas
... and many more ...

It's all quite unclear - but probably very important for the "Customer Journey".. .

**Comment by dkatson** [comment]
I found that if you did not add Application Area = all in your group, action or field it will not be displayed in Web client of D365 Sandbox. 

I'm also interesting in other application areas...

**Comment by StanislawStempin** [comment]
Please have a look here #176 and see if it answers your questions.
