### ISSUE TITLE
AA0232 The FlowField XXX of "TableName" should be added to the SIFT key.

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6140]
**Describe the bug**
The rule does not seem to be working correctly.

**To Reproduce**
We haven't been able to reproduce it outside our app (a test app using the same VSCode extension and BC server, with identical code as the one below does not raise the warning). There is something else that I must be missing, but I'm posting it here to see if we can find what.

This is, after a few simplifications, the code I've left in one table field (the original CalcFormula was much more complex):

        field(7142200; "IDPWHS Qty. Buffer"; Decimal)
        {
            CalcFormula = Sum("IDPWHS Read Buffer".Quantity where("Doc No." = field("Document No.")));
            Caption = 'Qty. Read';
            Editable = false;
            FieldClass = FlowField;
            DecimalPlaces = 0 : 5;
        }

It raises this warning: **The FlowField Quantity of "IDPWHS Read Buffer" should be added to the SIFT key.**

This is the key I've created for that CalcFormula, in the "IDPWHS Read Buffer" table:

        key(Key7; "Doc No.")
        {
            SumIndexFields = Quantity;
        }

Just for reference, this are the "Doc No." and "Quantity" fields:

        field(2; "Doc No."; Code[20])
        {
            Caption = 'Document No.';
            DataClassification = CustomerContent;
        }
        field(6; Quantity; Decimal)
        {
            Caption = 'Quantity';
            DataClassification = CustomerContent;
            DecimalPlaces = 0 : 5;
        }

**Expected behavior**
There is a SIFT index for the required key and the Quantity field, so no warnings should be raised.

**5. Versions:**
 - AL Language: 6.0.324421
 - Business Central: 16.

**Comment by MattTraxinger** [comment]
I can verify that I have the same issue with the rule.

**Comment by dtkb** [comment]
Confirmed, the warning still fires when it has been fixed very specifically: see warning here:

![image](https://user-images.githubusercontent.com/63455896/95181722-8cf3d180-07bb-11eb-86f3-09ba20907168.png)

but see the key I added just for that purpose here:

![image](https://user-images.githubusercontent.com/63455896/95181829-adbc2700-07bb-11eb-98b6-e8dd6e3856e2.png)

**Comment by dtkb** [comment]
It seems this is also another warning that fires for keys that exist in the base application but to which we cannot add SumIndexFields, which it should not do until we can add them... no point telling us 'you should do X' when you don't let us ;-)

**Comment by larswestman** [comment]
Same here. Take a look at this example. I get a warning on field 84 but not 85 even though they are delcared in the same way and use the same underlying table and key.

![image](https://user-images.githubusercontent.com/43792551/95508508-6ac4a400-09b3-11eb-886e-7977abbe503d.png)
![image](https://user-images.githubusercontent.com/43792551/95508518-7021ee80-09b3-11eb-93e9-7e8a59fb2900.png)

**Comment by TKapitan** [comment]
I have a bit different problem.
The rule does not respect field type, so if we use max on a date field (to find the last date) the warning is useless (SIFT index is for the numeric field only)...

![image](https://user-images.githubusercontent.com/37966300/95510474-46b69200-09b6-11eb-8d58-5d9e052a526e.png)

**Comment by waldo1001** [comment]
Confirmed.. this doesn't make sense either..
![image](https://user-images.githubusercontent.com/12088142/95585174-2a126c80-0a3f-11eb-8eff-02bdef30204d.png)

**Comment by mplze** [comment]
Same here, I have added an extension field for Vendor Table and Get sum to form my customize table, I have set SumIndexFields but still appear this misleading information

![image](https://user-images.githubusercontent.com/32490642/99034950-7142ce80-25a4-11eb-9bcf-5f2827f1b7ce.png)


![image](https://user-images.githubusercontent.com/32490642/99034988-920b2400-25a4-11eb-89bb-f2bb0dcad020.png)


![image](https://user-images.githubusercontent.com/32490642/99035120-eca48000-25a4-11eb-80a2-a2b17739c21a.png)

**Comment by mjmatthiesen** [comment]
I can also confirm that this is still creating false errors.

**Comment by nareshwar** [comment]
Happened to me on a Boolean field!

![Screenshot 2021-01-20 at 15 36 48 (2)](https://user-images.githubusercontent.com/1448455/105198619-be5b9780-5b35-11eb-99cc-fdeaa1cb3602.png)

**Comment by yrest** [comment]
Slightly different twist (I think):

tableextension 50000 "My Purch. Inv. Line" extends "Purch. Inv. Line"
{
    fields
    {
        field(50000; "My Application Entry No."; Integer)
        {
        }
    }
    keys
    {
        key(AE1; "My Application Entry No.")
        {
            SumIndexFields = Quantity;
        }
    }
}

Above code leads to an error:  "The property 'SumIndexFields' can only be set if the specified fields are from the same table.",

Fair enough.

But in another table linking to field in this table extension I get the AA0232 warning, that Quantity must be included in SIFT.

**Comment by Koubek** [comment]
Hello @PaulIvan, is there any progress on this and generally any ETA?

**Comment by GreatScott000** [comment]
Any progress?

**Comment by MikeGlue** [comment]
Anything happening with this? This warning is very useful when it acts correctly, but with all the false warnings and the fact it isn't even recognizing the things I'm fixing I am afraid I have to disable this rule, which is a huge shame.

**Comment by aptMattKoe** [comment]
I know Repos where Issues that no longer get comments are removed because of "not relevant" or "looks like resolved".
So: Hi to the other 19 People who not ignore warnings, I had the same wrong warning....

**Comment by GardarRunolfsson** [comment]
I have this problem as well.

**Comment by BaltzerLogicpartner** [comment]
Also having this problem

**Comment by PrebenRasmussen** [comment]
Still seeing this problem!
(AL Language v9.0.586671)

**Comment by runesig** [comment]
Me too on v9.0.611415. But it does not always pop up. Can't figure out why it is like this on some fields, but on others that looks exactly the same it does not show up.

**Comment by ernestasjuska** [comment]
Hi, here is some code for reproducing this issue.

.vscode/settings.json:
```jsonc
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${CodeCop}"
    ]
}
```

app.json
```json
{
  "id": "5bf931d1-ad10-4e81-a8d9-7860a57a688b",
  "name": "ALProject67",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "runtime": "10.0"
}
```

Example.al (I added both cases - without and with table extension; compiler will complain for table extension case, but it doesn't matter)
```al
#region A
table 50100 "XYZ Source A"
{
    fields
    {
        field(1; "Entry No."; Integer) { }
        field(2; "Some Field"; Integer) { }
        field(3; "Some Amount"; Decimal) { }
    }

    keys
    {
        key(PK; "Entry No.")
        {
            Clustered = true;
        }
        key(K2; "Some Field")
        {
            SumIndexFields = "Some Amount";
        }
    }
}

table 50101 "XYZ Target A"
{
    fields
    {
        field(1; "No."; Code[20]) { }
    }
}

tableextension 50101 "XYZ Target A Ext." extends "XYZ Target A"
{
    fields
    {
        field(50100; "Value"; Decimal)
        {
            FieldClass = FlowField;
            CalcFormula = sum("XYZ Source A"."Some Amount" where("Some Field" = const(123)));
            Editable = false;
        }
    }
}
#endregion A

#region B
table 50102 "XYZ Source B"
{
    fields
    {
        field(1; "Entry No."; Integer) { }
        field(2; "Some Field"; Integer) { }
        field(3; "Some Amount"; Decimal) { }
    }

    keys
    {
        key(PK; "Entry No.")
        {
            Clustered = true;
        }
        key(K2; "Some Field")
        {
            SumIndexFields = "Some Amount";
        }
    }
}

table 50103 "XYZ Target B"
{
    fields
    {
        field(1; "No."; Code[20]) { }
        field(2; "Value"; Decimal)
        {
            FieldClass = FlowField;
            CalcFormula = sum("XYZ Source B"."Some Amount" where("Some Field" = const(123)));
            Editable = false;
        }
    }
}
#endregion B
```

The compiler will show these warnings:
![image](https://user-images.githubusercontent.com/53167314/212271850-8d94a643-2fda-48ad-8957-1170688dd26f.png)

So the problems are:
1. The problem detection algorithm does not work sometimes - it should find key with fields used in `where` condition (in my example "Some Field") and if such key exists it should check if SumIndexFields property includes the source field (in my example "Some Amount").
3. "Some Amount" is not a flowfield. It is the field which is used to calculate flowfield value.
4. The message does not include flowfield filter field names - so you usually need to go back and forth between files.

Thanks.

**Comment by TKapitan** [comment]
I think it's not necessary to add additional information. Microsoft does not fix any of these CodeCop warnings soon as it is not their priority.

**Comment by salgiza** [comment]
@mazhelez Now that there is an example to reproduce it, and knowing that this bug still applies, could you consider reopening the ticket? Even if you don't plan to fix it now, at least to make it clear that it still is a problem.

**Comment by jonwlong** [comment]
Still not fixed.

**Comment by MichelDant21** [comment]
Still not solution.

**Comment by cr998** [comment]
Does anyone knows something about that?
Still not fixed at 2024?

**Comment by NKarolak** [comment]
The status of this issue is "Closed", which means that Microsoft won't ever look again into it.
We can only open new issues.

**Comment by ashishsharmainecta** [comment]
Still not Fixed. I am getting same warning in case of average based flow field.

**Comment by navdotnetreqs** [comment]
Still broken FOUR years after it was reported the first time..

**Comment by waldo1001** [comment]
@ashishsharmainecta , @navdotnetreqs , 
these mesages will not get read.  Issue is closed.  MS answered: not a prio - may be in some next major release.. .

Best is to create a new issue if you would like to raise new attention to it.. .

**Comment by amodaresi-archerpoint-com** [comment]
@waldo1001 there are two Microsoft practices that bothers the earth out of people. One is "we are closing this issue and trace it internally", and then for years there is no resolution. How does that even make sense! People open issues to track them.

The second, is what you see here. It's not a priority. OK, we knew that already upon creating the ticket. But it's still an issue. What's the purpose of closing tickets just for the sake of closing them to meet some KPR probably? this should be forbidden practice. but probably the managers too want to show that they are closing tickets....

**Comment by navdotnetreqs** [comment]
@amodaresi-archerpoint-com & @waldo1001 
And a third one is the propensity to try and discourage opening any issues at all! Hey, there are no problems if the issues don't exist or are closed. So let's make it very difficult to open new issues.

Just remove the crappy rule if you can't be bothered to fix it. :/
