### ISSUE TITLE
[AL0604] Wrong Warning for Runtime 3.0 (BC 14)

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6141]
**Describe the bug**
You get the warning

> Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.

if you don't use "Rec." on Page Field Properties like StyleExpr, Visible, HideValue, Editable and/or Enabled, but Business Central 14/Runtime 3.0 doesn't support to setup properties with Rec.OtherField and you get an Runtime Exception if try to open this Page in the Windows or Web Client

**To Reproduce**
``` 
page ... 
{
[..]
field(MyField; Rec.MyField)
{
    StyleExpr = OtherField;
}
[..]
}
```

**Expected behavior**
No Warning for runtime versions that doesn't support Page Field Properties with "Rec.".

**5. Versions:**
 - AL Language: 6.0.324421
 - Business Central: 14.7

**Comment by stefanoPrimo** [comment]
FYI: still occurs in yesterday daily build

**Comment by thloke** [comment]
Closing as this has been fixed. This should only be raised if the target runtime is 7.0 or higher.
