### ISSUE TITLE
Default languaje in generate xliff

### ISSUE THREAD

**Issue by cr998** [microsoft/AL#6142]
How can I change the language in which the xliff is generated, in the xliff that is generated when enabling the TranslationFile feature the source-langueje and target-language is "en-US" , bu ti want tha use "es-ES" as default languaje
![image](https://user-images.githubusercontent.com/6900835/93175083-60eeae80-f72f-11ea-9649-3abc86691529.png)

**Comment by qutreson** [comment]
Hi @cr998, the xliff file is always generated by default for "en-US", but you can manually edit it to specify another language, for instance "da-DK" or "es-ES". You can have a look at our [online documentation about translation files](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#the-xliff-file).

It mentions for instance:

_In the generated .xlf file, you can see a <source> element for each label. For the translation, you will now have to add the target-language and a <target> element per label. The <trans-unit id> attribute corresponds to the object ID in the extension. This is illustrated in the example below._

I hope this answers your question.

**Comment by cr998** [comment]
"Captions" inside code are written in spanish ,when i compile the xliff generated is in source-language="en-US" and the source tag is in spanish

**Comment by aptMattKoe** [comment]
Microsoft asumes that you write captions in english.
You have to translate that into spanish.
If you do not want to do that translation process I would recommend this VS Code Extension: https://marketplace.visualstudio.com/items?itemName=rvanbekkum.xliff-sync
