### ISSUE TITLE
AA0150 Parameter 'Key Fields Part 1' is declared by reference but never changed in method 'xxx' - false positive

### ISSUE THREAD

**Issue by Jeeve65** [microsoft/AL#6143]
**Describe the bug**
rule AA0150 gives a warning even though the condition is not met.
  
**To Reproduce**
1. Create new codeunit
2. Add this procedure:
    ```
    procedure SetKeyFields(KeyFields: JsonArray; var "Key Fields Part 1": Text[250]);
    var
        KeyFieldsAsText: Text;
    begin
        if KeyFields.WriteTo(KeyFieldsAsText) then
            "Key Fields Part 1" := CopyStr(KeyFieldsAsText, 1, 250);
    end;
    ```

**Expected behavior**
Warning AA0150 should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/19321004/93175273-a3b08680-f72f-11ea-9c50-cbf686a0e644.png)

**5. Versions:**
 - AL Language: 6.0.332161

**Comment by Jeeve65** [comment]
Seems to be depending on the name of the parameter; when I change "Key Fields Part 1" to KeyFieldsPart1 the warning does not appear.

I was renaming the parameters anyway...

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
