### ISSUE TITLE
Pages extension fields are not added on the brick layout on the phone client

### ISSUE THREAD

**Issue by BernBoit** [microsoft/AL#6145]
**Describe the bug**
Pages extension fields are not added on the brick layout on the phone client: Most table don't have fieldgroup (brick) defined, so it's not possible to extend the fieldgroup to add custom fields. If I add a new page I can manage the fields that will appear by setting them on the first 6 ones (even if none defined in the origin table)

**To Reproduce**
Create a table extension on "Time sheets Lines": add a text field
Create a page extension on "Time sheets list" where you add the new text field after the "No."
Open the My time sheets page on the phone client

``` AL Code to reproduce the issue ```

**Expected behavior**
When no brick fieldgroup are defined for a table, fields added to a pageextension should be inserted in the page in the same order as regular fields.

**Screenshots**

**5. Versions:**
 - AL Language: 5.0329509
 - Business Central: CA Business Central 16.4 (Platform 16.0.14648.16512 + Application 16.4.14693.15090)
- Phone client: Microsoft Dynamics 365 Business Central 2.8.12162 (Google play)

**Comment by qutreson** [comment]
Hi @BernBoit can you share here the code for the table extension and the page extension that reproduces the issue?
Can you also provide us with a screenshot that shows the issue on the phone client?

**Comment by BernBoit** [comment]
Hello @qutreson 

AL Code to reproduce the issue:

tableextension 74951 "ERA110 Timesheet Header" extends "Time Sheet Header"
{
    fields
    {
        field(74939; "ERA110 Resource Name"; Text[100])
        {
            Caption = 'Resource Name';
            CalcFormula = Lookup (Resource.Name WHERE("No." = FIELD("Resource No.")));
            Description = 'ERA.110 name of resource';
            Editable = false;
            FieldClass = FlowField;
        }
    }
	        fieldgroups
    {

        //addlast(brick; Quantity,"ERA110 Resource Name") { }

    }

}


pageextension 74948 "ERA110 Time Sheet List" extends "Time Sheet List"
{
    layout
    {
        addafter("No.")
        {
            field(Quantity; Quantity)
            {
                ApplicationArea = All;
                Style = Strong;
            }
            field("ERA110 Resource Name"; "ERA110 Resource Name")
            {
                ApplicationArea = all;
                ToolTip = 'Resource Name';
            }
        }
    }
}

Screenshots:
web client:
![Web client](https://user-images.githubusercontent.com/38114379/93333168-e7b79000-f7f0-11ea-8d13-2bf2fa5b71fe.PNG)

phone client:
![PhoneClient](https://user-images.githubusercontent.com/38114379/93333186-ed14da80-f7f0-11ea-8fba-b15ae6319c2e.PNG)

**Comment by Drakonian** [comment]
Yes, issue is presented, I am try to add some fields to Brick fieldgroup on Vendor table for Tiles list view, but it's just not work.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
