### ISSUE TITLE
Appsource validation will fail or not for BC17

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#6147]
Hi,

We are getting this warning 
**_Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release._**

If we do not solve this warning in our 17.0 apps, will the app source validation will pass or not?
Please let us know?

Thanks & Regards
Varun Reddy

**Comment by NKarolak** [comment]
This warning was introduced for BC 17; it is still just a warning. Only errors won't let the validation pass.

**Comment by bachii1010** [comment]
Thanks for the update what about another similar warning of with keyword will be deprecated for use in cloud

**Comment by atoader** [comment]
! The warning will not block the submission to AppSource. It is a warning meant to enforce a coding pattern that allows us to evolve the language by adding new system library functions without breaking extensions downstream.
All the diagnostics that are related to AppSource validation come from AppSourceCop and have the AS* prefix https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop
