### ISSUE TITLE
Processing of message 'textDocument/completion' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'

### ISSUE THREAD

**Issue by NabMike** [microsoft/AL#6149]
**Describe the bug**
Error occur and intellisense stops working 

Error message:
[Error - 10:15:45] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Node span: 0-1942, position: 1992 (Parameter 'position')'
Details:
System.ArgumentOutOfRangeException: Node span: 0-1942, position: 1992 (Parameter 'position')...

**To Reproduce**
1. Just write some AL code

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/71431654/93439960-77cc0700-f8cf-11ea-9f84-f98c7309c534.png)

**5. Versions:**
v5.0.335750

**Comment by qutreson** [comment]
@NabMike can you provide us with a small project that reproduces the issue? 

Is the issue reproducing consistently? What happens if you do Ctrl + Shift + P and then 'Developer: Reload Window'?

**Comment by qutreson** [comment]
For reference, this looks similar to #5929 and #5918

**Comment by NabMike** [comment]
@qutreson It seams it only occurs in a larger project I am working on so I not able to share my project.

Reloading window sometimes helps for a short period and yes #5929 and #5918 looks where similar. Must be some of my written code making this problem so is it possible to debug the VS Code application to find what causes then problem?

**Comment by qutreson** [comment]
We cannot provide you with what is necessary for debugging the AL extension. From the exception and the stack trace, we cannot provide you with more information on how to identify what is causing the issue. We will try to improve the exception thrown in this context to provide more information, but we cannot provide any ETA for that for now.
