### ISSUE TITLE
How to reach Object table? 

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/AL#615]
Our scenario assumed to get(read) info about (Name fields\Captions fields\Types fields\ Relation table inf ) from Objects table.
There are another scenarios:

Get table no by name;
Check availability of objects;
Advice please how we can solve it in SaaS scenario?

**Comment by esbenk** [comment]
The content of the Objects table is mostly binary, how did you manage to get that information extracted?

Here is some alternative tables to look at.

2000000058 AllObjWithCaption
2000000041 "Field"
2000000136 "Table Metadata"

**Comment by lvanvugt** [comment]
I guess  @dkorinets is talking about the virtual table Field, as that holds the mentioned info (Name fields\Captions fields\Types fields\ Relation table inf )

**Comment by dkorinets** [comment]
@lvanvugt You are right

**Comment by StanislawStempin** [comment]
The Field table is available for Extensions, closing this question.
