### ISSUE TITLE
UnprocessableEntity on Publishing app: Extension compilation failed Src/codeunit/...error AL0132 ... does not contain a definition for 'TBUOM_Pallet load'

### ISSUE THREAD

**Issue by louagej** [microsoft/AL#6150]
**Situation**
I've created a simple extension that uses a field from another app.
This depended app is installed on my development environment.
Symbols are downloaded and I can build my .app file without any errors or warnings.
When I want to publish and install my new app, the VSCode debug console return the following message:
> `[2020-09-17 11:31:58.53] Sending request to https://bc2020cu1w1:7049/BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default`
> `[2020-09-17 11:31:59.32] The request for path /BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Extension compilation failed
Src/codeunit/TBPCACommonFunctions.Codeunit.al(17,58): error AL0132: 'Record "Item Unit of Measure"' does not contain a definition for 'TBUOM_Pallet load'`

**To Reproduce**
Steps and to reproduce the behavior:
1. Start a new al project in VSCode
2. Define a depended app in the app.json
3. Install depended app on development environment
4. Download symbols in VSCode project
5. Use a field in your app from the dependend app
6. Press F5 to build and deploy the app to your development environment

```AL
begin
        if (Rec.Type = Rec.Type::Item) and (ItemUnitofMeasure.Get(Rec."No.", Rec."Unit of Measure Code")) then begin
            //"TBUOM_Pallet load" is field from depended app
            Rec."TBPCA_Pallet Load" := ItemUnitofMeasure."TBUOM_Pallet load";
            ...
    end;
```

**Expected behavior**
Succelfull Publish and install app in development environment

**Screenshots**
![image](https://user-images.githubusercontent.com/7229592/93460388-6d1b6d00-f8e3-11ea-82b9-0085e6db798b.png)

**5. Versions:**

 - AL Language: v5.0.335750

 - Business Central: Docker Container on localhost
>Using image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
>Version: 16.1.12629.12805-W1
>Style: onprem
>Platform: 16.0.12630.12758

Kind regards,
Job

**Comment by qutreson** [comment]
Hi @louagej, can you verify that the reference symbols in your al package cache (see al.packageCachePath setting in VS Code) and the symbols published on the server have the same version? It looks like the symbols in your package cache contain a definition for the Record "Item Unit of Mesure" while the ones on your server do not.

Can you try setting the "al.packageCachePath" to a different folder, download the symbols again and reload VS Code. Does the issue still reproduce?

**Comment by louagej** [comment]
Dear,

the al.packageCachePath setting in VS Code contains the correct symbols with the same version:
`I just blured our Customer Name`
![image](https://user-images.githubusercontent.com/7229592/93471983-592c3700-f8f4-11ea-8a82-b41559ce23de.png)

I did change the folder and downloaded the symbols again, but that didn't made any difference.
The error is not during the build of the app, but during publishing to the development environment.

Below a screenshot of the record "Item Unit of Measure" with the field present in my development environment.
![image](https://user-images.githubusercontent.com/7229592/93474063-28013600-f8f7-11ea-9da1-f9a556dfe4be.png)

The symbols on my development environment and the symbols in VSCode also have the same Version No.
![image](https://user-images.githubusercontent.com/7229592/93474369-875f4600-f8f7-11ea-988c-ea3db24482b5.png)

![image](https://user-images.githubusercontent.com/7229592/93474436-9e9e3380-f8f7-11ea-9d0a-662cbb80cf3d.png)

**Comment by qutreson** [comment]
Did you try to reproduce this on the latest developer preview? The build from your server seems to be from 16 CU1.

Can you provide us with some AL projects that would reproduce the issue so that we can investigate it further?

**Comment by GFR1** [comment]
Hi,
Did you have any news on this issue. I have exactly the same issue using BC 16 CU2

**Comment by louagej** [comment]
Hi @qutreson ,

the issue seem to be in the app.json.
Since BC16.2, you can't leave 'platform' in the app.json. As far as one knows , with 16.1, this wasn't an issue  :eyes:
![image](https://user-images.githubusercontent.com/7229592/94531295-a8e7f800-023c-11eb-84bd-cd5db7451a08.png)

After removing this line, the problem was :heavy_check_mark:

Kind regards,
Job

**Comment by Delpixe** [comment]
Hi @louagej ,

It appears that I am facing your same issue, 

here is my app.json:
![image](https://user-images.githubusercontent.com/38073933/94581180-0ef37000-027b-11eb-9818-b02b14ed649c.png)


here is the error i get from VS code:
![image](https://user-images.githubusercontent.com/38073933/94581012-de133b00-027a-11eb-89d8-bef2901456db.png)


Could you help me please?

Kind regards,
Mattia

**Comment by louagej** [comment]
@Delpixe ,

I can only give you the detailed steps I took to :heavy_check_mark: this problem. I hope they can help you as well.
:information_source:
- Start by checking the app.json in the app `app_where_i_need_to_get_some_extended_fields`
- In this app.json, there is probably the property `application: 16.0.0.0`.
- Remove this property
- Rebuild the app `app_where_i_need_to_get_some_extended_fields`
- Publish the app `app_where_i_need_to_get_some_extended_fields` in your dev environment
- Open the other project in VSCode where you want to use this app
- Remove the old `app_where_i_need_to_get_some_extended_fields.app` (in you case version 1.0.0.2) file in the `.alpackages` folder
- Download the symbols and check if the new version of your app is in the `.alpackages` folder
- Try to rebuild your app, publish and install...

Good luck :thumbsup:

Regards,
:point_right: Job

**Comment by Delpixe** [comment]
@louagej 

Thanks a lot, it worked !!!

Regards

**Comment by nvtopalov** [comment]
Same error is show if by mistake you are using AppId which already exist in the database you are trying to publish. I made such a mistake .. you know copy-past the app.json to save time. In my case it didn't save anything  :)
