### ISSUE TITLE
Gridlayout page field captions

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/AL#6154]
**Describe the bug**
Not possible to change caption in grid layout from page 

**To Reproduce**
1. My code

``` 
grid("Price Start/End Date Grid")
            {
                Caption = '';
                field("Price Start/End Date"; "SIK-Price Start Date")
                {
                    Description = 'SVT53156';
                    ApplicationArea = All;
                }
                field("Price Start/End Date2"; "SIK-Price End Date")
                {
                    Caption = '';
                    Description = 'SVT53156';
                    ApplicationArea = All;
                } 
}
grid("Pickup Date/Time Grid")
            {
                Caption = '';
                field("Pickup Date/Time"; "SIK-Pickup Date")
                {
                    Description = 'SVT53156';
                    ApplicationArea = All;
                }
                field("Pickup Date/Time2"; "SIK-Pickup Time")
                {
                    Caption = '';
                    Description = 'SVT53156';
                    ApplicationArea = All;
                }
 }
```

**Expected behavior**
The code is supposed to change the first field's caption to "Price Start/End Date", and remove the second field's caption.
A you can see in the screenshot the captions are not from the code. The original captions from the table are shown
Additionally if I try to remove the caption from the table, then the name from the page is shown (not the caption property) In the above example "Price Start/End Date2" which still makes it difficult to remove the caption. If I blank out or use spaces for the page field name, it will revert to table field name. It seems impossible to remove the caption

**Screenshots**
![image](https://user-images.githubusercontent.com/891314/93820315-d4059280-fc11-11ea-81aa-4f1658b0e191.png)
[image](https://user-images.githubusercontent.com/891314/93820315-d4059280-fc11-11ea-81aa-4f1658b0e191.png)

**5. Versions:**
 - AL Language: al-4.0.231354
 - Business Central: 15.3

**Comment by dtkb** [comment]
> It seems impossible to remove the caption

Did you try `ShowCaption = false`..?

**Comment by thloke** [comment]
To change the caption of the first field, you should be able to do

```
                field("Price Start/End Date"; "SIK-Price Start Date")
                {
                    Caption = 'Price Start/End Date'
                    Description = 'SVT53156';
                    ApplicationArea = All;
                }
```

Hiding the field captions with `ShowCaption = false` seems to be broken. I'm going to raise that as an internal bug.

**Comment by dtkb** [comment]
> Hiding the field captions with `ShowCaption = false` seems to be broken.

Interesting. So is `Caption = ''` meant to be equivalent or is that a wrong way?

**Comment by thloke** [comment]
The correct way is meant to be using `ShowCaption = false`. 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control#position
