### ISSUE TITLE
JSON Complex Type not supported by Business Central??

### ISSUE THREAD

**Issue by jbakach** [microsoft/AL#6155]
- AL Extension Version: 5.0.335750

- Server Version: Versión: ES Business Central 16.2 (Plataforma 16.0.13440.13772 + Aplicación 16.2.13779.0)

I want to publish an API page through BC to receive the following JSON, but nothing brings to me that possibilty. I think that should be introduced ASAP. Also alphanumeric tags are not supported. Why??

Thanks for the attention!!
{
  "portalId": XXXX,
  "objectType": "DEAL",
  "objectTypeId": "0-3",
  "objectId": XXXXXXXXXXX,
  "properties": {
    "dealname": {
      "versions": [
        {
          "name": "dealname",
          "value": "XXXXX",
          "timestamp": 1595451968018,
          "sourceId": "XXXXXXXXXX",
          "source": "CRM_UI",
          "sourceVid": []
        }
      ],
      "value": "XXXX",
      "timestamp": 1595451968018,
      "source": "CRM_UI",
      "sourceId": "XXXXXX"
    }
  },
  "version": 46,
  "secondaryIdentifier": null,
  "isDeleted": false
}

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. This question in particular is specific to our web service APIs, and not applicable to the compiler.

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
