### ISSUE TITLE
Field does not dissapear in the total sections

### ISSUE THREAD

**Issue by boomerama** [microsoft/AL#6158]
**Describe the bug**
I add a Extension with some new fields for the Page "Puchase Quote". Firstly i added them to the section adddlast(General) and they appeared in the above section in the second screenshot, but then i changed them to addafter "Expected Receipt Date". Now they appear after the "Expected Receipt Date", but they do not disapear in the General section. When uninstalling the extension everething disappears.
I also tried to add the same and other fields to the addlast(General) section, but they dont appear below the totals section, last screenshot

**To Reproduce**
Steps and to reproduce the behavior:
see above

``` AL Code to reproduce the issue ```

**Expected behavior**
After changeing the position the fields should appear only at the correct position.

**Screenshots**
code 
![grafik](https://user-images.githubusercontent.com/36401349/93915323-7a629e00-fccd-11ea-9008-d325abd8cc2f.png)

Wrong Appearence

![grafik](https://user-images.githubusercontent.com/36401349/93915432-a1b96b00-fccd-11ea-8798-cfaef9969c29.png)

After deleting the fields from the Pageextension
![grafik](https://user-images.githubusercontent.com/36401349/93915476-b72e9500-fccd-11ea-86b7-d56236e26976.png)

Uninstalling teh extension

![grafik](https://user-images.githubusercontent.com/36401349/93915575-e218e900-fccd-11ea-963c-09273c390c7d.png)

Otherwise add them to the addlast(General)  section

![grafik](https://user-images.githubusercontent.com/36401349/93916130-a7fc1700-fcce-11ea-9c49-12afeaf1c571.png)

**5. Versions:**

 - AL Language: v5.0.335750

 - Business Central: DE Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.4.14693.15445)

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. This question isn't about compilation, but about extension behaviour once it is published to the server. I can raise the bug internally, but it will have a higher chance of getting fixed if it's raised in the right channel.

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
