### ISSUE TITLE
TestToolkit issue - The test library CodeUnit is not accessible after TestToolkit was imported into container

### ISSUE THREAD

**Issue by deborahQinzm** [microsoft/AL#6161]
Installed Lasted Business central onPrem image: ltsc2019 , application version is:16.3.14085.14238
and imported Testtoolkit after development license imported.
The test tool is able to open and test assert test codeunit is there.  Run the test, it all passed.

But in my AL project, if I reference to Library - Assert codeunit, it is not there. None of the library code unit is accessible in my test project.

What should I check?

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
