### ISSUE TITLE
Avoid "obsolete" warnings when referenced by other obsolete objects

### ISSUE THREAD

**Issue by LNitzsche** [microsoft/AL#6165]
**Title**
Throw "obsolete" warnings only if the object is referenced from non obsolete code.

**Description**
This ist not a suggestion for a new rule but request to change behaviour of an existing rule.
Scenario:
You set a page and corresponding table to "obsolete".
This generates a warning (AL0432) , if you try to reference the page in your code. 
This is intended and ok.
But as you cannot delete the page immediately it still resides in your code and unavoidable references a table which is also set to obsolete.
This may generate a lot of warnings, even if you don't use this page and table anymore.

You cannot create extensions containing some obsolete objects without warnings!

**Reason for the rule**
To avoid too much warnings from code which is effectivly not in use it should be possible to suppress such warnings where not needed.

**Bad code sample**
Example of what bad code the rule should (NOT) catch:

page 12345 "MyPage"
{
    Caption = 'Tooltip Fields';
    PageType = ListPart;
    UsageCategory = None;
    
    SourceTable = "MyTable";  // This generates an unneccessary warning
                              // if MyTable is also set to "obsolete", but I can't remove this reference here
                              // without destroying the functionality (which may still be used by an other extension).

    ObsoleteState = Pending;
    ObsoleteReason = 'Deprecated';
    
    ....
}

**Good code sample**
Example of what code should look like:

No changes in code needed, but obsolete warning should be suppressed if the calling object is already obsolete.
That means throw this warning only, if an obsolete object is referenced by a not obsolete object.

**Good and bad practices for fixing the rule**

**Remarks**
​This is just to suppress needless warnings which make it difficult to notice other more important warnings.

**Comment by qutreson** [comment]
This looks like a duplicate of #5936

**Comment by LNitzsche** [comment]
Sorry, I did'nt find this entry. It seems to be exactly the same problem.
I will close this issue.
