### ISSUE TITLE
Codeunit 5986: New procedure "AmountsDifferByMoreThanRoundingPrecision" prevents initialization of "Line Amount"

### ISSUE THREAD

**Issue by meikcremer** [microsoft/AL#6166]
The recently introduced procedure "AmountsDifferByMoreThanRoundingPrecision" is called from "Divide Amount" and will lead to an error if the Serviceline has a "Unit Price" of "0.01" and a "Line Discount" of 100%. 
The posting of a service order will fail and the report 5915 will throw a "Line Amount" of "-0.01" for this line, in fact the "Line Amount" should be "0.00", therefore posting this service order will throw a Consistency-Bug.

The reason for this is a change in the following lines of code:

                LineAmountExpected := Round(ChargeableQty * "Unit Price", Currency."Amount Rounding Precision");
                if AmountsDifferByMoreThanRoundingPrecision(LineAmountExpected, "Line Amount", Currency."Amount Rounding Precision") then
                    "Line Amount" := LineAmountExpected;

The "Line Amount" is only "initialized" when the expected amount differs by more than the rounding precision. If the expected line amount is "0.01", because of a "Unit Price" of "0.01", this leads in a "Line Amount" of "0.00". Further Down the discount is still being deducted from this "0.00", leading to a negative line amount.

                "Line Amount" := "Line Amount" - "Line Discount Amount";

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
