### ISSUE TITLE
Dataclassification error (AS0016) should not be raised for tables / fields with ObsoleteState = Removed

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6167]
**Describe the bug**
We're in the middle of refactoring our solution (not yet on AppSource) and are obsoleting a lot of tables and fields and have replaced them by new tables / fields. When enabling the **AppSourceCop**, we get a lot of DataClassification (AS0016) errors on the obsoleted tables / fields (**ObsoleteState = Removed**). These will never be used and it seems overhead having to fix errors for tables / fields that will be forcely deleted whenever possible. (Tables / fields are currently needed to support C/AL > AL upgrade path)

**To Reproduce**
Steps and to reproduce the behavior:
- Create a table and set ObSoleteState to Removed
- Add a field to a TableExtension and set ObSoleteState to Removed
- Enable the AppSourceCop
- AS0016  "Field with name 'xxx' must use the DataClassification property and its value should be different from ToBeClassified.",

**Expected behavior**
AS0016 should not apply to tables / fields with ObsleteState = Removed

**Screenshots**

![image](https://user-images.githubusercontent.com/25268332/94360346-dd2cae80-00ac-11eb-8506-ccd23e4be143.png)

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/94360355-e9b10700-00ac-11eb-8426-e0cf83a0c9f7.png)

**Comment by qutreson** [comment]
@fvet tables and fields that are marked with ObsoleteState Removed still exist in the database and might still be containing data, so they still need to be classified. This behavior is then by-design. We will update the documentation for AS0016 to mention it.
