### ISSUE TITLE
Error when setting breakpoint: Cannot create empty object for type 'TableData'

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6171]
**Describe the bug**
I just tried to 'Debug without publishing' and upon 'Set a breakpoint' I get the error below.

`[2020-09-28 14:25:59.82] Error: Cannot create empty object for type 'TableData'`

When I add the breakpoints first and then start the debugger, the breakpoint state changes to 'Unverified' and the same error is added to the debug console.

What's might be the cause / how to resolve?

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/94432347-eeea8080-0196-11eb-824b-3a0103350257.png)

**Comment by fvet** [comment]
Seems like the issue is related to the 6.0 vsix used to target a **5.0 / BC 16 NST**. When reverting back to the 5.0 vsix, all seems to work fine.

**Comment by thloke** [comment]
Does this happen when you target a 6.0 / BC 17 NST as well, or is this just a backwards compatibility issue?

**Comment by fvet** [comment]
I don't have any 6.0 / BC 17 NST running yet. I used the insider vsix to be able to fix newest CodeCop warnings and checked if previously reported issues had been fixed. Then I started targetting my BC 16 NST with the 6.0 vsix and found out about the debugging issue.

**Comment by thloke** [comment]
Thanks for the clarification. We'll investigate this further.

**Comment by thloke** [comment]
Does this happen on a basic AL:Go! project? It looks like we've broken something with breakpoints here. If there's a minimal repro you can share, that would help a lot.

**Comment by fvet** [comment]
There's not a lot I can share. Tried a simple AL : Go! project with the insider vsix (6.x) ... and it fails once the app is publish / webclient is shown, the breakpoint state changes to unverified.

![vsix6](https://user-images.githubusercontent.com/25268332/94555857-7948e800-025c-11eb-9588-82d5749e43e2.gif)

and the same with the marketplace vsix (5.x). One published / webclient is shown, I can freely add/remove breakpoints.

![vsix5](https://user-images.githubusercontent.com/25268332/94555919-9087d580-025c-11eb-8197-5884452e30b0.gif)

In both scenarios, I published with debugging, targetting the same NST (BC 16).

**Comment by thloke** [comment]
Thank you, this is still very helpful. We're looking into this now and this helps.

**Comment by thloke** [comment]
@fvet this has been fixed in the latest **marketplace** release of the VSIX.

**Comment by thloke** [comment]
This is fixed in v6.0.344420
