### ISSUE TITLE
Json rounds large negative decimals to -1,000,000,000,000,000 and then blows up

### ISSUE THREAD

**Issue by j2associates** [microsoft/AL#6172]
**Describe the bug**
Per the spec, Decimal Data Type 04/01/2020
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/decimal/decimal-data-type
Denotes decimal numbers ranging from -999,999,999,999,999.99 to +999,999,999,999,999.99.

If you define a Json object with a value of -999,999,999,999,999.99, it throws an exception: The value of Decimal parameter is outside of the permitted range. The current value is -1,000,000,000,000,000. The permitted range is from -999,999,999,999,999.99 to 999,999,999,999,999.99.

**To Reproduce**
Steps and to reproduce the behavior:

JsonKey: Text;
JsonText: Text;
DecimalValue: Decimal;
JsonObject: JsonObject;
JsonValue: JsonValue;
JsonResult: JsonToken;

JsonKey := 'dec1';
JsonText := '{"dec1":-999,999,999,999,999.99}';
JsonObject.ReadFrom(JsonText);

if JsonObject.Get(JsonKey, JsonResult) then begin
    if JsonResult.IsValue() then begin
        Jsonvalue := JsonResult.AsValue();
        DecimalValue := JsonValue.AsDecimal();
    end;
end;

``` AL Code to reproduce the issue ```

**Expected behavior**

I expected DecimalValue to be set to -999,999,999,999,999.99. 

**Screenshots**

**5. Versions:**

 - AL Language: 5.0.335750

 - Business Central:
Azure AD tenant: 3f7c4867-1295-492e-8538-19bfaf1069c6, Environment: Sandbox (Sandbox)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
