### ISSUE TITLE
XML child node allways added with blank xmlns value

### ISSUE THREAD

**Issue by ChristianMuetzePrintVis** [microsoft/AL#6174]
**Describe the bug**
We switched from the .net XML creation to the native AL way. 
But now we struggle with XML child nodes, which get a "xmlns=""" in.
Seems the .AsXmlElement().Add(NewChildNode) adds this empty namespace by accident.

**To Reproduce**
Steps and to reproduce the behavior:
1. Take the example code from below and check the output in the message box.

2. You will see following file:

<JDF xmlns="http://www.CIP4.org/JDFSchema_1_1">
  <AuditPool xmlns="" />
</JDF>

``` AL Code to reproduce the issue ```

pageextension 50110 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        FXmlAttributeCollection: XmlAttributeCollection;
        FXMLDOMDocument: XmlDocument;
        XmlElement1: XmlElement;
        XmlElement2: XmlElement;
        FCurrentNode: XmlNode;
        NewChildNode: XmlNode;
    begin
        Clear(FXMLDOMDocument);

        FXMLDOMDocument := XmlDocument.Create();
        FXMLDOMDocument.SetDeclaration(xmlDeclaration.Create('1.0', 'UTF-8', ''));

        XmlElement1 := XmlElement.Create('JDF', 'http://www.CIP4.org/JDFSchema_1_1');

        FXMLDOMDocument.Add(XmlElement1);

        FXMLDOMDocument.GetRoot(XmlElement2);
        FCurrentNode := XmlElement2.AsXmlNode();

        FXmlAttributeCollection := FCurrentNode.AsXmlElement().Attributes();

        NewChildNode := XmlElement.Create('AuditPool').AsXmlNode();
        FCurrentNode.AsXmlElement().Add(NewChildNode);

        FCurrentNode := NewChildNode;
        FXmlAttributeCollection := FCurrentNode.AsXmlElement().Attributes();

        Message(format(FXMLDOMDocument));
    end;

}

**Expected behavior**

We would expect a XML file looking like this:

<JDF xmlns="http://www.CIP4.org/JDFSchema_1_1">
   <AuditPool />
</JDF>

**Screenshots**

![image](https://user-images.githubusercontent.com/36710633/94549350-5c0f1c00-0252-11eb-9068-cf4dc1d13a1e.png)

**5. Versions:**

 - AL Language:  5.0.335750

 - Business Central: W1 16.4 / PrintVis PV16.00 (Platform 16.0.14648.15076 + Application 14.7.37609.0)

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  This isn't a bug with the compiler or dev tooling itself, but the server's runtime behaviour.

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
