### ISSUE TITLE
Parser accepts multiple implementations of same interface in properties 'DefaultImplementation' and 'Implementation'

### ISSUE THREAD

**Issue by christian-clausen** [microsoft/AL#6175]
**Describe the bug**
The parser accepts multiple implementations of the same interface in properties 'DefaultImplementation' and 'Implementation'. However, such code cannot be published even though it compiles.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an AL project in VS Code with the code below.
2. Compile with "AL: Package" (this succeeds)
3. Publish with "AL: Publish without debugging" (this fails)

AL Code to reproduce the issue:

```
interface Work
{
    procedure DoWork();
}
codeunit 50100 MondayWork implements Work
{
    procedure DoWork()
    begin
    end;
}
codeunit 50101 TuesdayWork implements Work
{
    procedure DoWork()
    begin
    end;
}
enum 50100 MyEnum implements Work
{
    DefaultImplementation = Work = MondayWork, Work = TuesdayWork;

    value(1; Monday)
    {
        Caption = 'Monday';
        Implementation = Work = MondayWork, Work = TuesdayWork;
    }
}
```

**Expected behavior**
I expected the compilation step to fail, because:

1. It does not make much sense to specify two different implementations for the same interface
2. The code cannot be published anyway, so there is no reason to not let compilation fail

**Screenshots**
Publishing fails with the following error hinting indirectly at a 'duplication issue':

```
[2020-09-29 12:25:57.26] The request for path /BC160/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Extension compilation failed
error AL0594: An error occurred during XML serialization: 'An item with the same key has already been added.'.
```
Notice that there is no reference to which code causes this publish error.

**Versions:**
 - AL Language: v5.0.335750
 - Business Central: Version: W1 16.0 (Platform 16.0.11233.12061 + Application 16.0.11240.12076)

**Comment by thloke** [comment]
The latest compiler will fail during compile time with the same error, preventing publishing. The error is really not helpful though, and could be improved.

**Comment by BazookaMusic** [comment]
Fixed in the latest release. Closing
