### ISSUE TITLE
Error when generating integration table for CDS entity with altpgen.exe

### ISSUE THREAD

**Issue by ProdwareJuanan** [microsoft/AL#6176]
**Describe the bug**
This issue is exactly the same as #5943 
Getting "System.NullReferenceException: Object reference not set to an instance of an object." when trying to generate integrations table for CDS entity with altpgen.exe
Previous months I've been able to use this commando with no issues.
it happens with account, contact, businessunit, systemuser, product.
With non standard entities does not happen.

**To Reproduce**

1. Using altpgen.exe from C:\Users<user>.vscode\extensions\ms-dynamics-smb.al-5.0.335750\bin folder.

2. Start Power Shell ISE as administrator

3. Run script from folder above:
    .\altpgen
    -project:"C:\VSCode\CDSIntegration"
    -packagecachepath:"C:\VSCode\CDSIntegration\.alpackages"
    -serviceuri:"https://mycrm.crm4.dynamics.com"
    -entities:account
    -baseid:50100
    Cache folder contains symbol files from BC 16.5.

**Expected behavior**
A new AL file with a table extension of the account entity with the custom fields that were added in CDS.

**Screenshots**
![issue-screenshot](https://user-images.githubusercontent.com/45352779/94562964-4e639180-0266-11eb-8367-d1d0e29e393c.jpg)

**5. Versions:**

 - AL Language: v5.0.335750

 - Business Central: 16.5.15897.16082

**Comment by manichoy** [comment]
Anyone have ideas how to solve it?
I got similar issue on the same Business Central Version (16.5.15897.16082) but later AL Language Version (6.0.344420). 

Thanks in advanced.

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible. This is not an AL compiler issue, the CDS integration team will need to handle this.

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

**Comment by hd1370** [comment]
Why was this an issue last time, but this time it is beeing closed/ignored? The issue is the same and back?

**Comment by ProdwareJuanan** [comment]
Hi, after opening a support request, in the next minor release of the compiler it will be fixed because it is part of the compiler tools

best regards

**Comment by hd1370** [comment]
> 
> 
> Hi, after opening a support request, Support Team told us in the next minor release of the compiler it will be fixed because it is part of the compiler tools
> 
> best regards

That is great news! Thank you.

Have a nice day.

**Comment by ProdwareJuanan** [comment]
the tool is working smoothly after last minor release.
thank you
