### ISSUE TITLE
"A taks was canceled" - Azure time out error ?

### ISSUE THREAD

**Issue by ManuBlasco** [microsoft/AL#6177]
Hello everyone,

"Could not install the extension IN Translate on tenant default due to the following error: A task was canceled."
"The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'."

Basically we get no error clue but just  “A task was canceled” in Business Central when calling an external method (Azure function).  It is weird because sometimes returns a success response others a timeout.

As per all above it seems to us something from Azure end. 

We tested these Azure functions in other applications (SoapUI) and the issue also occurs, although, as I said before, not every time.

Thank you very much in advance.
Regards,
Manu.
P.S. This is the second time this happens, lats time was back on July 28th and next day was all working as usual until today.

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible. This is not an AL compiler question, but a question about the extension installation process.

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
