### ISSUE TITLE
AA0150 Parameter 'String' is declared by reference but never changed in method 'XXXXX'.

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#6179]
**Describe the bug**
Warning should not be raised

**To Reproduce**
Create a procedure as below:

local procedure ForceCar2(var String: Text[10])
begin
    String[2] := 'A';
end;

**Expected behavior**
The warning should not exist on that case (partial change of a string)

**5. Versions:**
 - AL Language: 6.0.344420

**Comment by atoader** [comment]
Duplicate #6421
