### ISSUE TITLE
The name of xRec is not valid. The name of variables and parameters must be suffixed with the type or object name. A (AA0072))

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6181]
**Describe the bug**
This CodeCop is NonSense for Event Subscribers.

**To Reproduce**
Steps and to reproduce the behavior:
Create an Event Subscriber like the following

```
[EventSubscriber(ObjectType::Table, Database::"Gen. Journal Line", 'OnAfterValidateEvent', 'Description', true, false)]
local procedure GenJnlLineOnAfterValidateEvent(var Rec: Record "Gen. Journal Line"; var xRec: Record "Gen. Journal Line")
begin
end;
```

**Expected behavior**
There shouldn't be an info or any CodeCop Action, since the subscriber cannot change the signature of an event.
**Screenshots**
![image](https://user-images.githubusercontent.com/56249171/94803296-61eb3580-03e9-11eb-96bc-b241b24c1f2c.png)

**5. Versions:**

 - AL Language: 6.0.344420

 - Business Central:

**Comment by dtkb** [comment]
Another one to add to the litany of errors mainly documented in https://github.com/microsoft/AL/issues/6120

This diagnostic should just be turned off until it's anywhere near ready for use. End-users should not have to act as unwitting alpha-testers.

**Comment by PaulIvan** [comment]
I am closing this issue because it has been resolved, please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.
