### ISSUE TITLE
AA0072 - The name of ItemJournalLine2 is not valid. The name of variables and parameters must be suffixed with the type or object name.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6182]
**Describe the bug**
The CodeCop **AL0072** gives wrong info/warning about an record with an Integer as suffix.

**To Reproduce**
Steps and to reproduce the behavior:
Declare a variable with the following name

```al
ItemJournalLine2: Record "Item Journal Line";
 ```

**Expected behavior**
There shouldn't be a warning or info, since it is very common to add an Integer to a Record Variable if you need different references to the same record table.
**Screenshots**
![image](https://user-images.githubusercontent.com/56249171/94803968-5e0be300-03ea-11eb-89c1-5fad6da4bfad.png)

**5. Versions:**

 - AL Language: 6.0.344420

 - Business Central:

**Comment by dtkb** [comment]
but nonetheless, apparently it _should_ work, as said here:
https://github.com/microsoft/AL/issues/6120#issuecomment-686320373

**Comment by PaulIvan** [comment]
I am closing this issue because it has been resolved, please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.
