### ISSUE TITLE
false 'Parameter "Text is declared by reference but never changed in method (AA0150)'

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6184]
**Describe the bug**
The mentioned warning is reported spuriously when the argument **is** changed, ~but only in certain branching conditions. It should not fire if the argument **can** be changed within the method. Not all paths will change all variables...~

**To Reproduce**
Steps and to reproduce the behavior:

This code causes the warning :
![image](https://user-images.githubusercontent.com/63455896/94819182-ded0dc00-03f6-11eb-909b-28cdae38a793.png)

~Changing the `exit()` for a `;` so the code always flows to the assignment suppresses the warning, but that is obviously wrong, and I can't imagine any workaround that wouldn't be noisy and stupid.~

**Expected behavior**
no warning!

**5. Versions:**
 - AL Language: 6.0.344420
 - Business Central: n/a

**Comment by dtkb** [comment]
In fact, this isn't dependent on branching; I wrongly concluded that because the warning goes away briefly after changing the code to the below - but it just comes back once it reanalyses.

![image](https://user-images.githubusercontent.com/63455896/94824837-56a20500-03fd-11eb-9ce3-1a60c0b4e1de.png)

**Comment by dtkb** [comment]
The error also propagates through callers of the originally shown function:
![image](https://user-images.githubusercontent.com/63455896/94824915-6d485c00-03fd-11eb-9c92-464918df476e.png)

**Comment by dtkb** [comment]
another, simpler example:

![image](https://user-images.githubusercontent.com/63455896/96431930-2085c300-11fc-11eb-8269-cc731cc5deeb.png)

**Comment by dtkb** [comment]
I can't replicate this with AL extension 7.1.441584, so thanks!

https://github.com/microsoft/AL/issues/6184 also seems in need of closing.

**Comment by dtkb** [comment]
Nope, I spoke too soon. Changing something unrelated in the project caused AA0150 to come back again...

![image](https://user-images.githubusercontent.com/63455896/114001844-3a6f9c80-9854-11eb-810b-75c283cf03cd.png)

**Comment by dtkb** [comment]
However... if I then click on those warnings, to go to the file/location, they disappear!! ...for a few seconds, and then come back. This is some X-Files stuff ;-)

**Comment by NKarolak** [comment]
@dtkb This behavior is "normal", unfortunately. This is not specific to any warning code. You cannot rely on the "Problems" list, but you can run "AL: Package" instead, to not miss any warning.

**Comment by dtkb** [comment]
OK, I don't recall noticing that before, or maybe I just normally fix warnings too fast after clicking on them to notice 0:-) I figured it was worth mentioning in case 'abnormal'. Thanks!

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
