### ISSUE TITLE
Global Translation File generates Trans-Unit for Codeunit Function

### ISSUE THREAD

**Issue by SarahBirrer** [microsoft/AL#6186]
Since September the 30th the AL Compiler generates for every Codeunit Function a Trans-Unit like the picture below.
![image](https://user-images.githubusercontent.com/48559946/94809890-8ba95a00-03f3-11eb-9d37-62b355deb086.png)

This problem only comes with the feature in the app.json "Generate Captions".
![image](https://user-images.githubusercontent.com/48559946/94810601-87ca0780-03f4-11eb-9b4a-497fa67e73e7.png)

Is there any workaround? Because we need this property, but we can't handle these function names in the translation file, because we have outsourced the translation to our project management.

**Comment by thloke** [comment]
@thpeder  - can you help with this one?

**Comment by thpeder** [comment]
I don't know of an easy workaround, but you could add Caption property on all application objects so you don't need the feature "GenerateCaptions" enabled for now, until we release a fix.
