### ISSUE TITLE
AA0073 The name of temporary variable 'TempLastResponseRaw' must be prefixed with Temp.

### ISSUE THREAD

**Issue by silasvd** [microsoft/AL#6188]
**Describe the bug**
I have a global variable in a codeunit:
TempLastResponseRaw: Record TempBlob temporary;

I get a warning AA0073: The name of temporary variable 'TempLastResponseRaw' must be prefixed with Temp.
The variable of Record TempBlob temporary is already prefixed with Temp. When I rename it to TempTempLastResponseRaw everything is fine. When I use another record for example 'item' the message dissapears too.

**To Reproduce**
Create a codeunit with a global variable of type record TempBlob temporary; and give it the name TempLastResponseRaw.

``` AL Code to reproduce the issue ```
var
        TempTempLastRequestRaw: Record TempBlob temporary;
        TempLastResponseRaw: Record TempBlob temporary;

**Expected behavior**
I expect no warning.

**Screenshots**

**5. Versions:**

 - AL Language: v6.0.344420

 - Business Central:
not related to any client version.

**Comment by larswestman** [comment]
And what if we use a temporary table in an extension object wher we are souppsoed to prefix variables with our unique prefix?

Example: LTC_TempWhseRecipient: Record "LTC Whse Shpm. Recipient" temporary;

This variable name is correct as I see it but the rule want's it to start with Temp. That would not go well in the Appsource validation

**Comment by dtkb** [comment]
that should presumably be `TempLTCWhseShpmRecipient`, or without the `LTC` once they fix it to not require prefix/suffix in variables.

**Comment by larswestman** [comment]
OK I'll give it a try

**Comment by PaulIvan** [comment]
Hi @larswestman 
What dtkb says is correct and we have fixed this. :)

I am closing this issue because it has been resolved, please check the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.
