### ISSUE TITLE
QuickFix "Convert With statement": Strange resolution on validate

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#6190]
**Describe the bug**
if I have the code like this:
```
 with PurchLine do
     Validate(Type, Type::" ");
```
the quickfix will resolve the issue like that:
```
     PurchLine.Validate(PurchLine.Type, PurchLine.Type::" ");
```
Why add the Rec also on the left validate side? 

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**
```
     PurchLine.Validate(Type, PurchLine.Type::" ");
```

**Screenshots**

**5. Versions:**

 - AL Language: Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.344420
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: 17.0

**Comment by dtkb** [comment]
I'm curious: Does it also do this on other record functions that can 'magically' use unqualified field names, e.g. `.FieldCaption()`, `.GetFilter()`, etc.?

**Comment by stefanoPrimo** [comment]
with setrange/setfilter no. 
With other i dunno

**Comment by dtkb** [comment]
I have seen this from "AZ AL Dev Tools" extension, which may be calling the underlying 'official' fixers? - and which also gets this wrong for other functions like `TestField`, `GetFilter`, `CalcFields` - and, worse, **also** appends a pointless 2nd record name to variables other than `Rec`!! e.g. I saw it producing `SEPADirectDebitMandate.SetRange(SEPADirectDebitMandate."Mandate ID", ...` - _gross!_

**Comment by NKarolak** [comment]
@dtkb Then you should file your finding here instead: https://github.com/anzwdev/al-code-outline/issues

**Comment by dtkb** [comment]
Thanks! Done: https://github.com/anzwdev/al-code-outline/issues/186
