### ISSUE TITLE
AL(AA0131) The number of parameters passed to a string must match the placeholders

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/AL#6194]
**Describe the bug**
Getting the warning:
AL(AA0131) The number of parameters passed to a string must match the placeholders
Despite having the same number of parameters as the number of placeholders.

**To Reproduce**
In VScode, use:
```
local procedure WhyIsThereAWarning()
    var
        SalesHeader: Record "Sales Header";
        PmtDiscText: Text;
        PmtDiscTxt: Label 'If we receive the payment before %1, you are eligible for a 2% payment discount.', Comment = '%1 Discount Due Date %2 = value of Payment Discount % ';
    begin
        PmtDiscText := StrSubstNo(PmtDiscTxt, SalesHeader."Pmt. Discount Date", SalesHeader."Payment Discount %");
    end;
```

**Expected behavior**
Since using two parameters and two placeholders, we do not expect a warning for this.
Also tried this with a field of the sales header without a '%' in the name, but that didn't change anything to the warning.

**Screenshots**
Summary:
![image](https://user-images.githubusercontent.com/59433642/94930102-3a1dcf80-04c6-11eb-95c2-6e85a8ea382e.png)

**5. Versions:**
 - AL Language: 6.0.344420

**Comment by dtkb** [comment]
Typo: You don't ever substitute in `%2`; instead, you write `2%` unconditionally...

**Comment by kalberes** [comment]
As mentioned above you have one placeholder and two substitutions.

**Comment by ZepposBE** [comment]
My bad, been staring at code whole day, fixing warnings for upcoming BC17 and just never saw the typo in it. Thanks!
