### ISSUE TITLE
Open a specific Company with a setting in the launch.json

### ISSUE THREAD

**Issue by mhenricus** [microsoft/AL#6195]
**Describe the bug**
Not a bug, but a request to add a setting, eg. to the launch.json, with which can specified which company to open when opening BC from VS Code; running F5 or Ctrl+F5.

**To Reproduce**
Steps and to reproduce the behavior:

When there are more than 1 Company in the tenant, it cannot be controlled which Company has to be opened.
Of course the company can be changed in the User Settings, but this some extra time consuming clicks.
Besides, when debugging (by running F5), the connection between VS Code and the browser is lost after changing company.

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by kalberes** [comment]
Good suggestion. The only caveat is that you would need an initialized company else you won't be able to debug anyway.
To be sure that it gets taken into consideration I would suggest add it to BC ideas:  https://aka.ms/BusinessCentralideas

**Comment by mhenricus** [comment]
For quick manual testing I often use CRONUS, but for the automated tests I want a fresh company that has only been initialized (codeunit 2).

**Comment by mhenricus** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=258c0f12-3ff9-e811-a140-0003ff68f008
