### ISSUE TITLE
Txt2AL does not convert subscription target correctly

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6197]
**Describe the bug**
We subscribe the OnBeforeActionEvent of Page 7335 Warehouse Shipment for the Actions `P&ost Shipment` and `Post and &Print` in CAL. After converting to AL with txt2al we are getting the error that `Action25` and `Action26` are not available. 

**To Reproduce**
Subscribe to OnBeforeActionEvent of Page 7335 Warehouse Shipment with Action `P&ost Shipment`
Create DELTA with -ConvertToNewSyntax
Run Txt2Al
Get the error in VS Code.

**Temporary fix:**
Manually changing the target to `P&ost Shipment` or `Post and &Print`.

**Expected behavior**
The txt2al should correctly convert the target of the subscription.
I guess it is because of the ampersand (&) in the caption. (similar problem for translations https://github.com/microsoft/AL/issues/5042?)

**Screenshots**
Current situation:
![grafik](https://user-images.githubusercontent.com/7450586/95077970-edbfd300-0703-11eb-97f5-7adac13ba9ff.png)
Expected situation:
![grafik](https://user-images.githubusercontent.com/7450586/95085379-ac80f080-070e-11eb-80c6-98d1002be6c7.png)

**Versions:**

 - AL Language: 
**AL Language 3.0.168874**
Also tested with the newest version: 6.0.344420

 - Business Central:
140CU16

- Txt2Al:
14.0.44656.0
Parameters: `-runtime 3.2` (also tested with 3.0 and 4.0)

**Comment by kalberes** [comment]
Yes it is probably because of the ampersand in caption.
