### ISSUE TITLE
Preserve data

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#62]
When I press F5 after a previous build, I notice that I lost all data.

Do I have to foresee an upgrade-codeunit with the global functions as I had to in ExtensionsV1 as well?

**Comment by dennisfrostlander** [comment]
Currently it is not possible to use NavApp functions when developing extensions, but this whole feature is on our radar. No ETA yet.

**Comment by waldo1001** [comment]
well, apparently VSCode recognises it .. 
![image](https://cloud.githubusercontent.com/assets/12088142/21856687/2877eb86-d823-11e6-8c6d-4ff14d9e24a7.png)

but you say it doesn't work.  So can I conclude there is no way to preserve data at this point?

**Comment by dennisfrostlander** [comment]
Intellisense does recognize it, however you will get a compilation error once you complete the code. "The type or method 'RestoreArchiveData' cannot be used for 'Extension' development.' 
At this point not all functions are allowed for extension development. 
We are currently discussing the scope of this feature, I will get back to you on this thread.

**Comment by waldo1001** [comment]
Thanks.

Well, I would appriciate that the scope would be "preserve data" - even in development phase ;-).

**Comment by kine** [comment]
Some progress on this? I can finish the code, it is compiled, but no data restored when I use 
`
codeunit 70000000 UpgradeData
{
    trigger OnRun();
    begin
    end;

    procedure OnNavAppUpgradePerDatabase();
    begin

    end;
    procedure OnNavAppUpgradePerCompany();
    begin
        NavApp.RestoreArchiveData(70000000,false);
        NavApp.RestoreArchiveData(70000001,false);
        NavApp.RestoreArchiveData(70000003,false);       
    end;
}`

**Comment by StanislawStempin** [comment]
This is still work in progress. We will update this thread once we have a solution proposal

**Comment by vjekob** [comment]
Apparently, I can add those functions (OnNavAppUpgradePerCompany and OnNavAppUpgradePerDatabase) and apparently they also execute and inside of them I can write into the tables. However, when extension is uninstalled it simply deletes the data, rather than archiving the data.

Has anything changed here?

**Comment by RasmusTidselbak** [comment]
@StanislawStempin Will we get a similar feature as in the V1 extensions or will it be completely different?

**Comment by hvogelpohl** [comment]
I used some _initialization_ functionality next to the NAVAPP Restore functions in _OnNavAppUpgradePerCompany_. These don't work as well for now. Anyway I guess it's bad coding to do so at that place.

**Comment by bwdeleeuw** [comment]
with NAV 2018 dropping on Friday, is there anything known on this issue?

**Comment by StanislawStempin** [comment]
We are currently working on it.

**Comment by yandko** [comment]
@StanislawStempin, do you have any timeline in mind? This becomes very critical for those folks that are planning to use VS Code as their primary dev environment for extensions on NAV2018. All workarounds to restore the data requires time to support that eliminate all efficiency we received with AL.

**Comment by DominikDitoIvosevic** [comment]
We are actively working on this but I don't think I'm allowed to promise you more than "very soon"

**Comment by DominikDitoIvosevic** [comment]
This feature has been implemented and you can read more about it here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-retaining-data-after-publishing
