### ISSUE TITLE
Intellisense not working for ValuesAllowed on Enum fields

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6200]
**Describe the bug**
When using intellisense on ValuesAllowed on an Enum page field, only true and false are suggested, but not the Enum values.

![image](https://user-images.githubusercontent.com/34504100/95181402-88331b80-07c3-11eb-8d05-ee527cae9995.png)

**To Reproduce**
```
page 50100 test
{
    
    Caption = 'test';
    PageType = Card;
    SourceTable = "Sales Header";
    
    layout
    {
        area(content)
        {
            group(General)
            {
                field("Document Type"; "Document Type")
                {
                    ApplicationArea = All;
                    ToolTip = 'a tooltip';
                    ValuesAllowed =  // use tooltip  here
                }
            }
        }
    }    
}
```

**Expected behavior**
Intellisense should list all Enum values.
One could then easily add e.g.
`ValuesAllowed = Order, "Return Order";`

**Versions:**

 - AL Language: 6.1.344970

**Comment by kalberes** [comment]
Thanks for the repro. It is a bug.

**Comment by NKarolak** [comment]
@kalberes Any update on this?

**Comment by kalberes** [comment]
Unfortunately none and yes, it is a very old issue.
If the status has not been changed to "In Progress" then it is still just a backlog entry meaning that we have not had time to address it. Not even triage it.
@pborring

**Comment by NKarolak** [comment]
#5925

**Comment by atoader** [comment]
I've marked this as an enhancement to IntelliSense and removed the requires-triage label. We will try to look at IntelliSense issues in the next couple of months.

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by NKarolak** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=ba9e1b87-f68d-ee11-a81c-000d3a7a4389
