### ISSUE TITLE
Filter Pane is not available when a Page is run with RunModal()

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6201]
This is the still-active part of https://github.com/microsoft/AL/issues/4719

**Describe the bug**
It is not possible to reveal the filter pane when running a page modally.

**To Reproduce**

Create and run an action like the below. The `SomePageObject.RunModal()` syntax is affected too.

            action("TestPageRunModal")
            {
                ApplicationArea = All;
                Caption = 'TEST ONLY Modal';
                Image = ShowWarning;
                ToolTip = 'TEST ONLY Modal';

                trigger OnAction()
                begin
                    Page.RunModal(Page::"Warehouse Shipment List");
                end;
            }

The filter pane is not shown, even if the page defaults to `ShowFilter = true`, and worse, there is no filter icon to reveal said pane as there would be on a non-modal page.

**Expected behavior**
The filter pane should be revealable via a filter icon as on a non-modal page, and default to showing if `ShowFilter = true`.

**Screenshots**

non-modal page:
![image](https://user-images.githubusercontent.com/63455896/95198083-8ae93d00-07d2-11eb-8324-e88fffb24f8e.png)

modal page:
![image](https://user-images.githubusercontent.com/63455896/95198002-5f665280-07d2-11eb-9215-2140732a94bb.png)

**5. Versions:**
 - AL Language: 6.0.344420
 - Business Central: GB Business Central 16.5 (Platform 16.0.15884.17299 + Application 16.5.15897.16082)

I currently don't have access to a v17 BC. Please don't just close this if 16.5 is not close enough, but instead just run the very simple test on v17 and keep open if it persists.

Also, if this has been fixed in v17, we would appreciate info on whether you can backport that fix to v16 and ideally also v15.

Thanks!

**Comment by kalberes** [comment]
I cannot either. On the latest master (v18)

**Comment by fvet** [comment]
Already raised via https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=423972241670144 
and logged on https://experience.dynamics.com/ideas/idea/?ideaid=9770261b-d96b-e911-b047-0003ff688f46

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
