### ISSUE TITLE
Incorrect Runtime used by compiler after switching git branches

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6202]
Straight forward bug. I was on a branch that had app file with runtime 4.0 for the bc15 version.

I switched to the current branch, which uses runtime 5.0. The app will not build, because the compiler is stuck on the previous runtime version. I assume it's using some sort of cache. This needs to be disabled or at least cleared whenever we switch branches.
![image](https://user-images.githubusercontent.com/16603906/95247549-3d210480-07d3-11eb-8948-9bf2f67c2d52.png)

Currently I have to reload vs code in its entirety to get this to compile correctly after I switch branches.

**Describe the bug**
Switch from git branch with a different runtime than what you need. Then try and compile.

**Expected behaviour**
Compile successfully as runtime is valid.

**Screenshots**
See above.

**5. Versions:**

 - AL Language: 6.0

 - Business Central: 17.0

**Comment by dtkb** [comment]
This also seems broken simply when you change the runtime in `app.json`; I have to close/reopen VS Code to get relevant diagnostics for the new value of the `runtime` key.
