### ISSUE TITLE
Table locking issue 

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/AL#6204]
**Describe the bug**
if stop debugger in between , then random table is locked and it did not release lock and not allow to publish again.

Previous versions of Al language didn't have this issue.

**To Reproduce**
debug any code and stop in between, then try to use any related bc feature or publish again.

``` AL Code to reproduce the issue ```

**Expected behavior**
no locking of tables , when i stop debugger in between.

**Screenshots**

**5. Versions:**
al language --- latest on marketplace

bc 16.5

**Comment by GhOnBc** [comment]
Can confirm, I am experiencing same issue lately.

**Comment by kalberes** [comment]
Can we have a repro please?

**Comment by shashiBssi** [comment]
#6233

**Comment by atoader** [comment]
@shashiBssi I'll close this as a duplicate of #6233
