### ISSUE TITLE
The variable 'XYZ' is initialized but not used.AL(AA0206)

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#6207]
**Describe the bug**
A variable that is assigned a value and used as a source expression for a control will raise this warning

**To Reproduce**
Steps and to reproduce the behavior:
Use a variable as source expression. Example below (simplified version of the real page which obviously does not make much sense)
<pre>
page 12064546 "LTC Consignment Cues"
{
    PageType = CardPart;
    SourceTable = "LTC Consignment Header";
    Caption = 'Totals';
    layout
    {
        area(Content)
        {
            cuegroup(Numbers)
            {
                Caption = ' ';
                ShowCaption = false;                
                field(FieldNoOfItemLines; "NoOfItemLines")
                {
                    ApplicationArea = All;
                    BlankZero = true;
                    Caption = 'Item Lines';                    
                }
            }
        }
    }
    trigger OnOpenPage()
    begin
        NoOfItemLines := 1;
    end;
    var
        NoOfItemLines: Integer;
}
</pre>

The line "NoOfItemLines := 1;" will have a warning

**Expected behavior**
Should not be a warning

**5. Versions:**
 - AL Language: 6.0.344420
 - SE Business Central 15.1 (Platform 15.0.37898.0 + Application 15.1.38071.0)

**Comment by dtkb** [comment]
Does the warning go away if you remove the quotes around the variable name? I have just discovered an equivalent warning for variables used as properties in fields and actions.

**Comment by larswestman** [comment]
Yes, without quoutes the warning goes away.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
