### ISSUE TITLE
FieldRef Data Type is missing mehtods GetEnumValueCaption(Integer) and GetEnumValueCaptionFromOrdinalValue(Integer)	

### ISSUE THREAD

**Issue by Jupentti1** [microsoft/AL#6208]
**Describe the bug**
As mentioned in [documentation ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-data-type) FieldRef Data Type should contain methods **GetEnumValueCaption(Integer)** and **GetEnumValueCaptionFromOrdinalValue(Integer)**, but they are missing and cannot be used. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create variable of type FieldRef
2. Try to use FieldRef.GetEnumValueCaption() or FieldRef.GetEnumValueCaptionFromOrdinalValue() method 

``` AL Code to reproduce the issue ```

**Expected behavior**
These methods should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/53898567/95559543-99c52f00-0a20-11eb-8c51-77578ddc16bd.png)
![image](https://user-images.githubusercontent.com/53898567/95562038-43f28600-0a24-11eb-8db0-32dd89e4d8b7.png)

**5. Versions:**

 - AL Language: v6.0.344420

 - Business Central: W1 16.4 (Platform 16.0.14648.15420 + Application 16.4.14693.15445)

**Comment by kalberes** [comment]
This only available if you specify runtime 7.0 or higher.

![image](https://user-images.githubusercontent.com/12760483/95602343-1540d380-0a55-11eb-92e5-de7015df3cd3.png)

**Comment by Jupentti1** [comment]
I'm not sure what do you mean by setting runtime 7.0? I don't receive the AL0666 error when specifying Runtime 6.0 with current AL extension v6.0.344420. If i get the current BC insider AL extension the error is there. I think the way Microsoft is writing documentation is not supporting the developer, only making it very confusing. There should be some indication what version supports the current feature, as writing documentation that has features that will be released in the future versions should be clearly marked!

**Comment by kalberes** [comment]
In the BC insider builds daily builds features are still in progress. They may change, be cut, refactored, break all kind of things.
As I can see GetEnumValueCaption needs a server 7.0 as the error message claims.

**Comment by dtkb** [comment]
@kalberes Good points were made though about the lack of "Since" annotations or suchlike in the docs, so devs can know whether/when they can use any given symbol, instead of wasting time. Are there any plans to resolve? If not, can you forward the idea from here? Thanks!

**Comment by kalberes** [comment]
I can forward it to the documentation team.

**Comment by edupont04** [comment]
Hi there,
FYI, the documentation generally reflects the latest version of the product. So if you cannot recognize your current experience with what's in the docs, then check which version you are on.
Just to clarify, we're not _not_  supporting other versions, but for a number of reasons we are optimizing for the latest version.

**Comment by Jupentti1** [comment]
Hi @edupont04,
Just to clarify what do you mean by the latest version of the product? The latest version on Microsoft development, the latest available in bcinsider or the latest version generally available? In this case the method is not available in any case because runtime version 7.0 is not available for development. Please feel free to correct me if I'm wrong.

**Comment by qutreson** [comment]
The documentation has been updated to show the runtime version required to use the built-in methods defined in the AL language. https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-getenumvaluecaptionfromordinalvalue-method 

Please create a new issue if you are still able to reproduce it with the latest version of the AL extension from our preview builds
