### ISSUE TITLE
August Developer Shell bug: Exception calling "Substring" with "2" argument(s):

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#621]
When I start the Developer Shell I get this error.

![image](https://user-images.githubusercontent.com/28626283/30110254-c04494cc-9309-11e7-9e21-b2bdd981312d.png)

The code is looking for a database language and split the database name with a white space, but the **CA** database does not have a space.

![image](https://user-images.githubusercontent.com/28626283/30110312-eecf582c-9309-11e7-9fbe-8e934143249b.png)

**Comment by freddydk** [comment]
Thanks for letting us know.
The extension development shell is part of the NAV DEMO environment samples and designed to make building v1 extensions easier.
You are right, that it doesn't work in the august update and in the september update (coming up) it will not be included, as the developer preview is going away from being build on the same images as the DEMO environments.

**Comment by bvbeek** [comment]
Hi Freddy,

Thanks for you reply, 
Does it mean that we had to create our own convert scripts in the feature?
