### ISSUE TITLE
AL Formater breaks code when there is a procedure annotation

### ISSUE THREAD

**Issue by MaxFalcone** [microsoft/AL#6210]
**Describe the bug**
When al formatter invoked it messes the code up if somwhere below there is a procedure with annotation.

**To Reproduce**
Steps and to reproduce the behavior:
1. Start new project with AL:Go!
1. Select any Platform (I tried 3.0 and 6.0)
1. Open HelloWorld.al and replace all code there with code from below. Downloading symbols is not necessary.
```
codeunit 50100 "Name"
{
    local procedure Init()
    begin
        i();
    end;

    [Normal]
    procedure TestProc()
    begin

    end;
}
```
3. Go to the line 5. This one: `i();` and remove brackets and semicolon.
1. Make a note that at the moment at the problems pannel there is only one message for file that 
> "The name 'i' does not exist in the current context".
5. Invoke formatter either by saving the file or with hotkey.

Formatter will add one more line break before then `[Normal]` annotation and will add two more errors to the file's problem panel.
> Syntax error, 'procedure' expected

> Expected one of the application object keywords (table, tableextension, page, pageextension, pagecustomization, profile, codeunit, report, xmlport, query, controladdin, dotnet, enum, enumextension, interface)

Which means that now it doesn't understand the file structure.
If I reopen the file errors will be gone but additional line break won't.
And what is more important if there was more code below the annotated procedure, the code would be completely ruined by adding line breaks in random places. See screenshots.
I used [Normal] annotation just for example. Annotations like [Test] and [TryFunction] fails as well.
If annotation is removed or line where you deleting brackets is not the lat line in the function then error is not reproduced.

**Expected behavior**
Formatter should not add line break. Rest of the code should remain intact.

**Screenshots**
Before formatter. See that `[Normal]` stands on the line 8.
![image](https://user-images.githubusercontent.com/72614595/95596711-69988300-0a56-11eb-9bc1-30922c1ab87f.png)
After deleting brackets and formatter.
Now  `[Normal]` is on hthe line 9 and code is messed up.
![image](https://user-images.githubusercontent.com/72614595/95596809-859c2480-0a56-11eb-9f10-9557e3992c7b.png)

**5. Versions:**
 - AL Language: v6.0.344420
 - Business Central: 14.0.38650
- VSCode
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kalberes** [comment]
Thanks for the good repro. We are aware of this issue. It is in our backlog. Hopefully we will fix it soon.

**Comment by bjarkihall** [comment]
We had some really weird formatting changes when saving which broke our code in development.
I guess it was [Scope('OnPrem')] annotations in our cases, which are all over the place.
These errors are not expected and not easily caught if the diff is large.
Thankfully the compiler crashed but I'm worried if the formatter can affect actual logic and break things now, just by saving our files?

**Comment by thloke** [comment]
This has been fixed in the latest version of the VSIX. Thanks for waiting. (:
