### ISSUE TITLE
AA0150 Parameter 'YYY' is declared by reference but never changed in method 'XXX' - issue with interfaces

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#6211]
**Describe the bug**
The warning reports that the VAR parameter is not modified in a Codeunit that implements interface functions with VAR parameters.

**To Reproduce**
1) Create an interface with a function that contains VAR parameter.
2) Create Codeunit that implements this interface
3) Do not use this parameter in the function.

``` 
interface "ART AA Audit Log Type"
{
    procedure ImportLine(Line: Text; InspectionDone: Boolean; var AuditNo: Integer; var AuditCompleted: Boolean); 
}

codeunit 79076 "ART AA Audit Log Type - N/A" implements "ART AA Audit Log Type"
{
    procedure ImportLine(Line: Text; InspectionDone: Boolean; var AuditNo: Integer; var AuditCompleted: Boolean);
    var
        NotAllowedErr: Label 'Action is not allowed.';
    begin
        Error(NotAllowedErr);
    end;
}
```

**5. Versions:**
 - AL Language: 6.0.344420

**Comment by dtkb** [comment]
I feel like this is a case where something like C++'s `[[maybe_unused]]` attribute would be good. Because if MS disable this here, it also disables it for people who may _want_ such warnings in their interface implementations. So the 'fix' for you is a regression for others.

**Comment by TKapitan** [comment]
I don't think so as it is almost the same as for subscribers that are not checked by this rule... 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0150-donotdeclareparametersbyreferenceifneverchanged

"Event subscribers, Integration Events, and ConfirmHanders are also not analyzed."

**Comment by dtkb** [comment]
That just means that my personal reservations about the idea of not ever warning on unused variables can also be extended to those contexts, too ;-)

**Comment by TKapitan** [comment]
On the other hand, something like [[maybe_unused]] for both subscribers and interfaces can be useful... But the behaviour should be the same for both of them.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
