### ISSUE TITLE
Intelligent Cloud Base Missing previous versions 17

### ISSUE THREAD

**Issue by RCORELLA** [microsoft/AL#6212]
Hi,

Looking for migratting to on-line bc17, I can not choose in the "types of migration" the option "Dynamics 365 Business Central (Previous versions".   You only can select "Dynamics 365 Business Central".  Then, when you migrate, the systems give you a mistake "both versions must be the same".

Why can not select any previous version?  In the documentation say you can upgrade directly v15 and v16.

Thanks in advance.

Roberto Corella

**Comment by dtkb** [comment]
may be related to #6193

**Comment by kalberes** [comment]
Not really related  to latest Developer Preview releases of the AL development tools.
