### ISSUE TITLE
Property Editable is not handled correctly on List and Worksheet Pages (Should act like StyleExpr)

### ISSUE THREAD

**Issue by Random-PasserBy** [microsoft/AL#6213]
**Describe the bug**
The Editable property is not behaving correctly on List and Worksheet pages. 
Initially all lines are (not) editable based on the first line, only after activating a line the editable status is updated.
The buffer of 50 lines appears to be a factor as shown in the examples below.

**To Reproduce**
1. Create a new workspace for an extension
2. Add the following Table definition: 
[BUG01DemoDataBUG.Table.al.txt](https://github.com/microsoft/AL/files/5362208/BUG01DemoDataBUG.Table.al.txt)
3. Add the following Page definition:
[BUG01DemoDataBUG.Page.al.txt](https://github.com/microsoft/AL/files/5362209/BUG01DemoDataBUG.Page.al.txt)
4. Build and deploy the extension
5. Open the page and activate the action FillDummyData
6. Reopen the page to see the behavior described below with screenshots.

**Expected behavior**
The booleans in the SetStyle column should always be editable based on the IsEditable boolean on the same line.
Also when they are not yet activated / selected.
Similar as the behavior of StyleExpr which is handled correctly and shows the correct style at every line.

**Screenshots**
When opening the page following lines are shown..  
If the boolean SetStyle is active the style is correctly applied to the first column
Similar the SetStyle column should be editable where IsEditable is true.

![image](https://user-images.githubusercontent.com/61599431/95691023-2c7ded80-0c1c-11eb-85b9-d67f8468d6ef.png)

Scrolling down this keeps the same

![image](https://user-images.githubusercontent.com/61599431/95691037-4e777000-0c1c-11eb-8133-95b84c440218.png)

But when the page is reopened and the focus is set to a line that should be editable, the SetStyle column turns editable

![image](https://user-images.githubusercontent.com/61599431/95691053-7961c400-0c1c-11eb-9710-69eb1e54c666.png)

Scrolling down to line 50, the new "last value" for editable is applied.

![image](https://user-images.githubusercontent.com/61599431/95691077-a4e4ae80-0c1c-11eb-95b9-21b6f0759d36.png)

**5. Versions:**
 - AL Language: v6.0.344420
 - Business Central: Versie: W1 16.5 (platform 16.0.15884.17483 + application 16.5.15897.17570)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
