### ISSUE TITLE
[IncrementalBuild] add possibility to clean background compilations

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#6214]
**Describe the bug**
If I rename a file (setting the filetype from al to something that will not be compilable e.g. .al1), the errors still remain in the background compilation. 
Even thou I've renamed the file, I still not compile the app because it will get the errors of the renamed file.

**To Reproduce**
Steps and to reproduce the behavior:
1. pick a file with errors, like missing symbols
1. compile (it will not compile because of errors)
1. rename the file from *.al to *.al1
1. recompile (same errors as the 2nd step)

``` AL Code to reproduce the issue ```

**Expected behavior**
if I rename a file, move it, background compilation must update. Or let the user to "Clean Background compilation" or "Recompile the app"

**Screenshots**

**5. Versions:**

 - Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.344420
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by dtkb** [comment]
maybe related to #6077

**Comment by kalberes** [comment]
This is a bug. Should work. The issue is not with background compilations but how vscode handles diagnostics and how we send it the information needed.
