### ISSUE TITLE
Symbol resolution for function overloads with complex types outside of a multi root workspace fails

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6215]
**Describe the bug**
When overloading a function (with complex types?), dependend extension are able to resolve the correct function when opened within a multi root workspace. However, when opening the dependend extension from a separate editor in VS Code, symbols can no longer be resolved.

**To Reproduce**

See [ALProject14-15.zip](https://github.com/microsoft/AL/files/5364952/ALProject14-15.zip)

- Create extension A and add a codeunit with functions
    procedure MyFunction2(Stream: instream)
    procedure MyFunction2(XMLDocument: XMLDocument)
- Create extension B and add a dependecy to extension A
- Add the extension B folder to the same workspace with extension A
- Add a codeunit that references the function of extension A
    MyCodeunit.MyFunction2(Stream);
    MyCodeunit.MyFunction2(XMLDoc);

No issues arise

![image](https://user-images.githubusercontent.com/25268332/95743268-c7fd7580-0c91-11eb-9907-34c3ff703d20.png)

When you now open extension B only in VS Code, (so targetting the app file), the compiler can no longer resolve the function overloads and shows an error instead.

![image](https://user-images.githubusercontent.com/25268332/95743504-275b8580-0c92-11eb-9d14-82848a4c8df7.png)

**Expected behavior**
- Either support function overloads with complex types, across extensions (not using multi root workspaces)
- Either disable function overloads with complex types and make the compiler fail.

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/95743632-5a057e00-0c92-11eb-89ee-10c124472f9b.png)

**Comment by kalberes** [comment]
Have you built A within the workspace before opening B standalone?
If not have you published A?
Have you tried downloading's symbols for the missing reference?
Since for standalone projects you have the old story. You need symbols to resolve from somewhere.

**Comment by fvet** [comment]
_Have you built A within the workspace before opening B standalone?_ Yes

If you look to the second screenshot, you'll see that the .alpackages folder contains the symbols for the dependend extension.
The 'MyCodeunit' variable is resolved, together with MyFunction. MyfFunction2 can't be resolved, although it is part of the referenced app file. See the .dal file (right part of the last screenshot)

**Comment by kalberes** [comment]
It has worked for me. 
a. I have one packageCachePath for the whole workspace.
b. When I had the workspace opened I have built A. The app files should appear in the packageCachePath 
c. I have opened B and built it It works.

![image](https://user-images.githubusercontent.com/12760483/95883883-b5f80180-0d7b-11eb-8e9e-f92b0e907579.png)
