### ISSUE TITLE
Error when executing Query in UpgradePerDatabasee function

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#6216]
**Describe the bug**
The error **"You must choose a company before you can access the 'XXX' table."** is thrown incorrectly in the following scenario:

- A Query is executed in the **OnUpgradePerDatabase** Trigger of an Upgrade Codeunit 
- The Query is based on a **CompanyWide Table** which **contains a Field with a Table Relation to a PerCompany table.**
- The Query **DOES NOT INCLUDE** the PerCompany field

This error should not occur since we're not using a PerCompany field. 

**To Reproduce**
Steps and to reproduce the behavior:
- Create a new **CompanyWide Table** including a **Field which has a Table Relation to a PerCompany table**
- Create a **Query** based on the previously created Table and **DO NOT INCLUDE** the Field mentioned earlier
- Execute the Query object in the **OnUpgradePerDatabase** Trigger of an Upgrade Codeunit
- **Increment the Version of the App** in the app.json File

See also attached Sample: [TestDataPerCompany.zip](https://github.com/microsoft/AL/files/5365152/TestDataPerCompany.zip)

``` AL Code to reproduce the issue ```

See sample above

**Screenshots**

See sample

![image](https://user-images.githubusercontent.com/48217797/95747858-680acd00-0c99-11eb-97bd-2913eb0c98eb.png)

**5. Versions:**

 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.344420
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central **(also occurs in latest version)**:

![image](https://user-images.githubusercontent.com/48217797/95747573-f9c60a80-0c98-11eb-905f-d2febc2a0eae.png)

**Comment by kalberes** [comment]
Thanks for the repro. Looks like a bug.

**Comment by kalberes** [comment]
This issue will possibly be available in the 17.1 release of Business Central

**Comment by pborring** [comment]
Closing as fixed back in Oct 2020 in 2020 Wave 2 (v18 and backported to v17 minor
