### ISSUE TITLE
Certain fields cannot be added to the dropdown menu for fields

### ISSUE THREAD

**Issue by SibrenVh** [microsoft/AL#6217]
**Describe the bug**
Not all fields can be added to the dropdown menu. Examples include:
- Vendor Item No. (Item table)
- Search name (Customer table)

Additionally, tables such as "Stockkeeping Unit" don't have a fieldgroup. Therefore, we can not define an extension for the dropdown.

**To Reproduce**
Add fields from bug description to dropdown fieldgroup.

``` AL Code to reproduce the issue ```
e.g.:
fieldgroups
    {
        addlast(DropDown; "Vendor Item No.") { }
    }

**Expected behavior**
These fields should be added to the dropdown, or we should get notified that certain fields are not supported by the dropdown feature.
Additionally, all tables should include a dropdown fieldgroup or we should be able to define one ourselves. 

**Screenshots**

**5. Versions:**

 - AL Language: v6.0.344420

 - Business Central: 16.5

**Comment by SibrenVh** [comment]
Update: these fields can be enabled by adding them via personalization on the lookup page.
E.g:
When adding the “Search Name” to the field groups of the customer page, you should add the “Search Name” field to the lookup page (in case of the Customer table: Customer lookup). This can be done via coding or personalization. After adding these fields, the "Search Name" field will be enabled in the dropdown box.

**Comment by SibrenVh** [comment]
Update: I found a new issue related to this one and my previous comment. 

The personalization issue is broader than i expected. The dropdown menu does not change consistently when changing the dropdown menu when fieldgroups are changed in extensions. This includes fieldgroupextensions of other fields (e.g. "City", "Salesperson Code", ...). 
When adding these fields on the customer lookup page via personalization, the order of the fields of the dropdown menu also changes. However, this does not work consistently so i don't think this was added as a feature but should be classified as a bug.

**Comment by atoader** [comment]
Hi @SibrenVh ! Can you provide a zip of the project showing where the failures happens? A video showing this working for other fields vs the fields you specified would also help.

**Comment by SibrenVh** [comment]
Hi @atoader I included a zip file in this comment. This zip file includes 3 files:

- An al file showing the extension i made to the dropdownfields
- A video illustrating the behaviour when adding fields to the lookuppage (filename: "Dropdown add field").
- A video illustrating the behaviour when moving and hiding fields in the lookuppage (filename: "Dropdown remove field"). Note that i had to reload the page at 00:48 to view the changed fields

Version of this project: Business Central: 17.0
[Github Dropdown.zip](https://github.com/microsoft/AL/files/5581662/Github.Dropdown.zip)

**Comment by atoader** [comment]
Thanks! We'll take a look!
