### ISSUE TITLE
Print should replace DynamicFileHandler.axd with the report caption

### ISSUE THREAD

**Issue by GrumpyNAVdev** [microsoft/AL#6218]
**Describe the bug**
Printing from Business Central to a PDF printer results in the PDF printer to suggest this filename: "DynamicFileHandler.pdf" or "DynamicFileHandler.axd.pdf". That was not the case for NAV RTC and Classic, where it suggests the report caption, i.e.: "Sales - Invoice.pdf"

We are printing to a special PDF printer, which integrates to a document management system with OCR. The documents are in some situations sent to the customers and they find it very insecure opening mails with an attached file called "DynamicFileHandler.axd.pdf"

**To Reproduce**
Steps and to reproduce the behavior:

1. Open BC in Chrome
2. Go to a Posted Purchase Invoice
3. Press Print/Send -> Print -> Print...
4. Set "Save as PDF" as Destination
5. Press Save

You will now see a Save As window with the suggested filename "DynamicFileHandler.axd.pdf"
You will see similar behavior using BullZip and other PDF printers.

``` AL Code to reproduce the issue ```
REPORT.RunModal(406, true, false, Rec);

**Expected behavior**
I would expect the filename to be i.e. "Purchase - Invoice.pdf" based on the report caption - just like in NAV.

**Screenshots**
N/A

**5. Versions:**
 - AL Language: 6.1.350698
 - Business Central: Platform 16.0.15884.17299 + Application 16.5.15897.16301

**Comment by AlexanderLundq** [comment]
@GrumpyNAVdev Having the exact same problem. Did you ever find a solution to this?

**Comment by GrumpyNAVdev** [comment]
@AlexanderLundq No, we had to get a third party vendor to modify the external application to change the file name from BC before it was sent to customers.

**Comment by aptMattKoe** [comment]
Did somebody have a solution for this?
