### ISSUE TITLE
Unable to publish to SaaS Sandbox with 6.1

### ISSUE THREAD

**Issue by Jamzy1234** [microsoft/AL#6219]
Updated to AL Language 6.1 and changed launch.json to use environment type of sandbox and name of the environment.

Go to publish and get the following [2020-10-13 12:08:34.76] The request for path /v2.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: A package with name 'Application', and a version compatible with '17.0.0.0' could not be found.

Tried with the hello world extension and get the same thing. 

Removing application from app.json causes Symbol errors.

Re installed to 6.0 and works fine.

Publishing to a 17.0 (Platform 17.0.17020.17400 + Application 17.0.16993.0) SaaS sandbox

**Comment by Jamzy1234** [comment]
Publishing to a 17.0 (Platform 17.0.17020.17400 + Application 17.0.16993.0) SaaS sandbox

**Comment by OsebergTSO** [comment]
looks like it always publish to default sandboxname - sandbox

but still checks metadata and open debugger in the sandbox specified in environmentname

**Comment by kalberes** [comment]
Yes, you are right.

**Comment by Jamzy1234** [comment]
> What if you do not use teh environment type and environment, but just the old sandboxname?

It works but I get the following warning. Reads as if sandboxName should not be used but is not the case

"This setting is obsoleted. Please use the 'sandbox' environmentType and the environmentName settings instead"

**Comment by OsebergTSO** [comment]
I got that as well, so i disabled, downloaded 6.0 from vsix and using that for now.

**Comment by kalberes** [comment]
As a workaround until we fix and you want to use 6.1.X, it should be safe to use just the sandboxname. We will not obsolete it for a while.

**Comment by kalberes** [comment]
This issue should have been fixed by the release 6.1.352568.
