### ISSUE TITLE
Enum value with blank caption is not displayed

### ISSUE THREAD

**Issue by Lazys** [microsoft/AL#6223]
**Describe the bug**
Enum value with blank caption is not displayed. In the BC 14 it works well, but in the BC 16 unfortunaltely not.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create Enum:
``` 
enum 51200 "Account Group N24"
{
    Extensible = true;

    value(0; Empty)
    {
        Caption = ' ', Locked = true;
    }
    value(1; CostTypeSystem)
    {
        Caption = 'Cost Type System';
    }
    value(2; CostPurposeSystem)
    {
        Caption = 'Cost Purpose System';
    }
} 
```

2. Use this enum on any table/page

**Expected behavior**
First enum value should display blank value.

**Screenshots**
1. In the BC 14 blank value is displayed correctly:
![image](https://user-images.githubusercontent.com/21179961/95987645-0167e980-0e28-11eb-986a-28a520ac3e87.png)

2. In the BC 16 the blank value is not available:
![image](https://user-images.githubusercontent.com/21179961/95987832-3f650d80-0e28-11eb-8c8f-5087caf19797.png)

**5. Versions:**

 - AL Language: 6.0.344420

 - Business Central: 16.5

**Comment by sayyamabbasi-DI** [comment]
Add space in first enum value 

Example 

```
enum 50001 "TEST Enum"
{
    Extensible = true;

    value(0; " ")
    {
        Caption = ' ';
    }
    value(1; S)
    {
        Caption = 'S';
    }
    value(2; M)
    {
        Caption = 'M';
    }
    value(3; XL)
    {
        Caption = 'XL';
    }
    value(4; XXL)
    {
        Caption = 'XXL';
    }
}
```
