### ISSUE TITLE
Reports: Typing the UsageCategory property gives error "The property 'dataset' cannot be used in this context"

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6225]
**Describe the bug**
Typing `UsageCategory = [whatever];` creates a spurious error about `dataset` not being valid/expected.

This might affect other code that can legitimately come after `UsageCategory` too, although I didn't have time to go looking for more trouble...

It's also possible that other properties that I didn't test can also cause this false error; I only checked `ApplicationArea`, which does _not_.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a report
2. Put an empty `dataset{}` in it
3. Go up to and type a `UsageCategory = ReportsAndAnalysis;` (e.g.) before the `dataset`, in the object properties area.

Interestingly, I can then cut and paste that line with the `vim` keybindings, and the error goes away (a) when it's cut obviously and (b) even after it's pasted back in the same form.

I also do not see this error when I type e.g. `UsageCategory=ReportsAndAnalysis;` i.e. without spaces and the auto-formatted runs and puts the missing spaces in; that's OK.

**Expected behavior**
This is not an error, as the ability to cut and paste the same code and get no error proves... so it should never be (sometimes) reported as one!

**Screenshots**

after adding the line by typing it:
![image](https://user-images.githubusercontent.com/63455896/96007786-c620e700-0e36-11eb-8a15-ad7024bbda0f.png)

after cut/paste:
![image](https://user-images.githubusercontent.com/63455896/96007870-d933b700-0e36-11eb-9b05-86415a3dcabf.png)

**5. Versions:**
 - AL Language: 6.1.350698
 - Business Central: n/a but latest 16.x dev sandbox

**Comment by kalberes** [comment]
Adding a new line after Typing UsageCategory = Administration; also fixes the issue for me. It is a bug though.

**Comment by dtkb** [comment]
This affects at least 2 properties in XMLports too; see #6232
