### ISSUE TITLE
Passing decimal as parameter is not handled Culture independent and leads to wrong result

### ISSUE THREAD

**Issue by StijnBt** [microsoft/AL#6226]
**Describe the bug**
Using both CalcQtyFromBase functions in codeunit 5402 "Unit of Measure Management" results in a wrong calculated result due
to wrong incoming value for the QtyBase parameter.
_Assumption_ The QtyBase is not handled Culture independent.

**To Reproduce**
Steps and to reproduce the behavior:
See below

``` 
NewQuantity := UnitofMeasureManagement.CalcQtyFromBase(RequisitionLine."Quantity (Base)", ItemUnitofMeasure."Qty. per Unit of Measure");
```

**Expected behavior**
Calculation should be handled Culture independent.

**Screenshots**
![image](https://user-images.githubusercontent.com/37275572/96010549-32551800-0e42-11eb-8ff9-c562130e6f6b.png)
![image](https://user-images.githubusercontent.com/37275572/96010637-544e9a80-0e42-11eb-83c9-9841171284c1.png)
![image](https://user-images.githubusercontent.com/37275572/96011049-c32bf380-0e42-11eb-9418-781d2741feb6.png)

**5. Versions:**

 - AL Language: v6.1.350698

 - Business Central: W1 16.2 (Platform 16.0.13440.13772 + Application 16.2.13509.13779)

**Comment by kalberes** [comment]
We do not handle production issue in here. Looks like an application issue.
![image](https://user-images.githubusercontent.com/12760483/96013623-c4125480-0e45-11eb-8883-cf77434cd764.png)
