### ISSUE TITLE
FieldRef.Number() documentation tooltip incorrectly states it returns "as a string"

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6228]
**Describe the bug**
`FieldRef.Number()` returns an `Integer`, yet the documentation tooltip says it `Gets the number of a field as a string.`

**To Reproduce**
Write `SomeFieldRef.Number()` and hover over the name of said function.

**Expected behavior**
It returns an `Integer`, so the `as a string` is wrong and should be dropped.

**Screenshots**
![image](https://user-images.githubusercontent.com/63455896/96120053-d8a62980-0ee5-11eb-86f2-9f4ba41087a7.png)

**5. Versions:**
 - AL Language: 6.1.352568
 - Business Central: n/a

**Comment by thloke** [comment]
Closing as this has been fixed.

![image](https://user-images.githubusercontent.com/39045749/126440310-ed14f0de-5a21-42d2-834b-46ebeb8359f4.png)
