### ISSUE TITLE
August Update: How to clear the lasterrortext

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#623]
because CLEARLASTERRORTEXT is not allowed:
![image](https://user-images.githubusercontent.com/28626283/30114301-c697559a-9317-11e7-9dab-ef89eb0c27ec.png)

We use the GetLastErrorText in a report to print the last error per line.
The line is created by a 

`IF CONEUNIT.RUN() THEN`

How can we clear the GetLastErrorText

**Comment by StanislawStempin** [comment]
This method was enabled in September Update.
