### ISSUE TITLE
Timeout after 2000 ms for 'terminate'

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#6230]
**Describe the bug**
 When I stop the debugger this message comes up:
Timeout after 2000 ms for 'terminate'

**To Reproduce**
Steps and to reproduce the behavior:

publish something, then stop the debugger.

**Expected behavior**
to work as it used to be. Nothng was updated, it started to happen a month ago or so. 

**Screenshots**

**5. Versions:**

 - Business Central: D365BC on premises

**Comment by dtkb** [comment]
mayb related to #6233 not stopping debug sessions.

**Comment by txeriff** [comment]
Thanks, yes looks like related to it.

**Comment by DanielGoehler** [comment]
@kalberes When will this get fixed?
