### ISSUE TITLE
AL functionalities not working on project cloned from git

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/AL#6231]
**Describe the bug**
When al repository is downloaded form git, it is not treated as an al repository: 
- download symbols is not available
- intellisense and code validation/formatting is not working
- standard objects defninitions cannot be viewed (Object definition no avaialble)

**To Reproduce**
Steps and to reproduce the behavior:
1. Download al repository form git, al download symbols will not be avaialble when opened from vs code
2. Observe intellisense and code formatting not working
3. Misc: in my case it is a multi-root workspace.

**Expected behavior**
After cloning git al repo download symbols command should be avaiable, intellisense working, standard object definitions browsable, as we cannot run al go on a non-empty folder,

**5. Versions:**

 - AL Language: 6.1.352568
 - Business Central: 17

**Comment by dtkb** [comment]
It has always worked fine for me. How are you downloading from Git, and how are you opening in VS Code?

**Comment by BWilczewski** [comment]
Hello,
like in this example:
- bc-XX folders are two seprate git repos
- xx-App and xx-Test are separate extensions, 4 of them here
- ive downloaded these 2 repos, added them to workspace, save the workspace
![image](https://user-images.githubusercontent.com/68582084/96429492-49f51d80-1201-11eb-9a7f-2bb368631569.png)

**Comment by bjarkihall** [comment]
Your workspace should open "Common - App", "Common - Test", "Sales Items - App" and "Sales Items - Test" separately, so 4 workspaces not just 2 - which makes 1 app.json + .vscode folder per workspace.

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
