### ISSUE TITLE
Error connecting to service tier in new iOS app

### ISSUE THREAD

**Issue by rulzart** [microsoft/AL#6234]
With the release of the new iOS Business Central app, there are issues connecting to the service tier. After receiving the bug report from the customer, I tried on my phone (old app version) and it worked fine. Then I updated the app, and now it says "Could not connect to the server".

**Comment by rulzart** [comment]
After looking into it a bit, it seems you need to set the GlobalEndpoints in the navsettings.json file now (for iOS to work). This works fine, if you just use NavUserPassword. But if you use AccessControlService, as is the case with our customer, it just gives us another error at login.

![error_iosapp](https://user-images.githubusercontent.com/4539665/96573632-bb4ed200-12ce-11eb-9683-5e73c4668981.jpg)

**Comment by taddeozanga** [comment]
Same Problem here

**Comment by wansong-yu** [comment]
![Please wait while the connection is restored](https://user-images.githubusercontent.com/80527370/110945467-91845f00-82f2-11eb-8cd0-b869d6365f48.jpg)
BC17.2, on premise, NAV password auth, SSL configured and GlobalEndPoints valued as well . Just the iOS app (on latest iOS version） cannot connect while Android's works fine, with following message: "Please wait while the connection is restored, it shouldn't take long". But it actually never connects. 
Has also tried with different devices/browers (iPad, iphone safary, iphone Edge), none works.

**Comment by wansong-yu** [comment]
Ok, here is the update.
In the past weekend, our technician made a upgrade from v17.2 to v17.4 and it works now.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
