### ISSUE TITLE
Translation Tool Inserts Extra Quotes(") in the Translation

### ISSUE THREAD

**Issue by BSSIRajbir** [microsoft/AL#6236]
**Describe the bug**
I am creating a translation file for the Austria region. The source file is in US English, and the target language is DE-AT. The issue is the translated file contains Double quotes in the translated text which throws run time errors in App functionality. 

For Example:
 _<trans-unit id="Page xxxx- Action xxxx- Property xxxx" translate="yes" xml:space="preserve">
          <source>XXX XXX Total XXX Value Details Report</source>
          <target state="needs-review-translation" state-qualifier="x-mt-cache">XXX-XXX-Bericht ' XXX Wert Details '</target>         
          <note from="Xliff Generator" annotates="general" priority="3">Page xxxx- Action xxxx- Property Caption</note>
  </trans-unit>_

We are using Microsoft Dynamics 365 - Translation Service Tool for the translation. 
**To Reproduce**
Steps and to reproduce the behaviour:
1. Go to https://support.lcs.dynamics.com/
2. Upload the Source Language file 
3. Set the Target Language to DE-AT 
4. Download the Translated file, You will see it has inserted Double Quotes(") for some of the captions(Mainly reports). 
5. Try to open the Same Report, it will throw an error for illegal Characters. 
Note:: This issue is mainly occurring in Reports.

``` AL Code to reproduce the issue ```

**Expected behavior**
There can be two expected behaviours
1.) Either the Translated file should not contain Double quotes.
2.) Or Dynamic 365 should not throw an error for Double(") Quotes in the Captions.

**Screenshots**
![image](https://user-images.githubusercontent.com/43894249/96773857-02ee6000-139a-11eb-8b60-2cad3c9e5dcf.png)

**5. Versions:**

 - AL Language: v6.1.352568

 - Business Central: US Business Central 16.3 (Platform 16.0.14073.16910 + Application 16.3.14085.17081)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
