### ISSUE TITLE
Auto-completion of fields on Page etc via Intellisense should prepend `Rec.`, etc.

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6240]
**Describe the bug**

From BC16 onwards, implicit `with` is marked for removal in future, so we should include `Rec.` before page fields, presumably(?) other record variable names before fields in report `dataitem`s, etc.

However, the auto-complete of field/control names on page/extension and report objects does not honour this, so it generates code that will cause a warning, which is very unhelpful

**To Reproduce**

1. Be on a page, somewhere you can add a control representing a field
2. Start typing the name of a field
3. Accept the suggested auto-completion
4. See that you get something like `field("Item Reference No.";"Item Reference No.")`

**Expected behavior**

Since we should not be using implicit `Rec.` anymore, that should be `field("Item Reference No."; Rec."Item Reference No.")`

Note that the auto-completion also does not include a space after the semicolon, when it should - the auto-formatter fixes that, so not the end of the world, but seems clearly wrong. Can this be fixed at the same time? It doesn't _quite_ seem worth its own bug...

**Screenshots**

auto-complete popup:
![image](https://user-images.githubusercontent.com/63455896/96867109-33023580-1464-11eb-942c-e248322c3854.png)

resulting field declaration:
![image](https://user-images.githubusercontent.com/63455896/96867130-385f8000-1464-11eb-8c20-23e595239ee7.png)

**5. Versions:**

 - AL Language: 6.1.352568
 - Business Central: n/a

**Comment by esbenk** [comment]
This is by design. If you opt-in for not using implicitwith with `#pragma implicitwith disable` the auto-completion includes the `Rec.`.

The rationale behind this design is that until you choose to switch over for an object, your source-code will look consistent.

**Comment by dtkb** [comment]
> The rationale behind this design is that until you choose to switch over for an object, your source-code will look consistent.

I feel like implicit `with` should be disabled by default, at the project level, so that the `Rec.` is included by default (since it hurts no one to have it there), and people who don't notice this won't get version-control noise later when they have to add the missing `Rec.`. Is this considered?

Anyway, I guess now I have to go and add `NoImplicitWith` in `app.json` to all my projects, to avoid the compiler deciding I don't want `Rec.` prefixes and thus generating wrong code.
