### ISSUE TITLE
Unable to Publish translation app runtime package to BC 17.0

### ISSUE THREAD

**Issue by rznd** [microsoft/AL#6243]
**Describe the bug**

We have a translation app without any objects inside and since v17 we are currently unable to Publish the Runtime Package.

The error message is: "The server "BC" was unable to process the request. The application will close."

I've had this behavior on both OnPrem (single tenant) and a Sandbox container (multi tenant).

If I use the standard app (not runtime) from the exact same build, it works.

It does not matter if the app is digitally signed or not.

**To Reproduce**

- Use the cmd Get-NavAppRuntimePackage to extract a runtime package from a Translation app
- Try to install the runtime package into another Server

**Expected behavior**
The app should publish correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/24936737/96874843-f4ad4c00-144c-11eb-8516-d1d58f40c6e8.png)
![image](https://user-images.githubusercontent.com/24936737/96875263-67b6c280-144d-11eb-8a28-c62a84287459.png)
![image](https://user-images.githubusercontent.com/24936737/96875344-7dc48300-144d-11eb-88b4-67919ca7c180.png)

**Versions:**

 - AL Language: 
![image](https://user-images.githubusercontent.com/24936737/96874571-a435ee80-144c-11eb-8614-2973a762e845.png)

 - Business Central:
![image](https://user-images.githubusercontent.com/24936737/96875083-363df700-144d-11eb-8f1d-e6f2c1067b77.png)

**Comment by PooyaKharamesh** [comment]
@rznd thanks for filing the issue. we can prioritize this issue if you could provide us a sample project that clearly reproduces the issue?

/Pooya

**Comment by rznd** [comment]
It seems the problem at the time was caused by mixing runtime apps from different versions (Sandbox build being installed into OnPrem).
