### ISSUE TITLE
Could not download symbols. Please see the Visual Studio Code output log for more details.

### ISSUE THREAD

**Issue by cscsindia** [microsoft/AL#6244]
- AL Extension Version: 

- Server Version:

**Comment by cscsindia** [comment]
Could not download symbols. Please see the Visual Studio Code output log for more details.

**Comment by dtkb** [comment]
You're gonna need to give people more info than that...

**Comment by qutreson** [comment]
Closing this issue as it does not follow the required template and does not provide information on how to reproduce the issue.
