### ISSUE TITLE
Can't open Enum .dal with "Go to Definition" or object explorer: "Unable to resolve text model content"

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6245]
**Describe the bug**
Trying to view the `.dal` definition for an `Enum` from BC17 does not work.

**To Reproduce**
1. Right-click on e.g, an `Email Connector` declaration, and `Go to Definition`, or
2. Open the `System Application.app` file in the 'object explorer' and double-click on same.

**Expected behavior**
The `.dal` file loads.

**Screenshots**

from `Go to Definition`:
![image](https://user-images.githubusercontent.com/63455896/96883127-f4767600-1477-11eb-99c1-b105e161401b.png)

from 'object explorer':
![image](https://user-images.githubusercontent.com/63455896/96883332-37384e00-1478-11eb-9fdb-946089a217c7.png)

**5. Versions:**
 - AL Language: 6.1.352568
 - Business Central: GB Business Central 17.0 (Platform 17.0.17020.17930 + Application 17.0.17126.17950)

**Comment by NKarolak** [comment]
@dtkb, you are again in the wrong repository ;-)
![grafik](https://user-images.githubusercontent.com/34504100/96897126-9608c200-148e-11eb-9cac-d1df23864730.png)

**Comment by dtkb** [comment]
No. The 1st screenshot comes from VS Code itself, and is the same error that Code Outline happens to throw, but it's just asking VS Code / AL to go to the definition either way.

**Comment by dtkb** [comment]
I'm still getting this with `Email Connector` and `Email Scenario` enums for example, but not Base (rather than System) ones such as `Sales Document Type`. Might be specific to System?

**Comment by atoader** [comment]
@kalberes @PooyaKharamesh can you follow up on this issue?

**Comment by kalberes** [comment]
This is not supported for now.

**Comment by EmilDamsbo** [comment]
Confirmed as working as expected in newest version:
![image](https://user-images.githubusercontent.com/67266681/199738384-4a0fca6b-14a8-48d2-ae54-e193be29878b.png)
![image](https://user-images.githubusercontent.com/67266681/199738308-ea820982-f237-4cad-8a10-cedd2a6a6188.png)
