### ISSUE TITLE
2 x false "name of Record is not valid" (AA0072) diagnostic reported for app.json - 1 per codeunit with TableNo?

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6246]
Yet another case of a diagnostic nonsensically being reported against `app.json`:

![image](https://user-images.githubusercontent.com/63455896/96976524-e0805200-1513-11eb-8979-7493748d0ebd.png)

I don't think this happens all the time, but nor do I know what would cause it in this specific project, so I just add it to the pile; obviously, let me know if I can help investigate any further.

AL Language 6.1.352568

**Comment by CorpitalFDP** [comment]
You get this warning one time for each codeunit with the parameter TableNo

**Comment by dtkb** [comment]
Indeed, the project from which I reported this does have 2 codeunits with `TableNo` parameter, and commenting out one of them (while of course causing lots of new errors) does reduce the count reported 'in' `app.json` to one. Thanks for that added info!

**Comment by PaulIvan** [comment]
Hi, @dtkb  could you try again with the latest version? (https://github.com/microsoft/AL#al-developer-preview-builds) .

**Comment by PaulIvan** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by dtkb** [comment]
I didn't have time to test with the preview build, but it seems that as of AL extension 7.1.441584 in VS Code the spurious warnings are not emitted, so thanks!
