### ISSUE TITLE
Common Data service connection setup issue in BC16.6

### ISSUE THREAD

**Issue by andrecavalcanti** [microsoft/AL#6248]
**Describe the bug**

I'm trying to set up common data services to connect to CRM. I'm using BC 16. 6 OnPrem. I enter the client id, client secret and I get the error below. I have tried it on BC16.3 and it works, as it uses user and password. BC16.6 uses client id and client secret.

**To Reproduce**

1. Go to Common Data service connection setup, enter the client id, client secret, and click on the enable.

**Expected behavior**
It should not give any error

**Screenshots**
![image](https://user-images.githubusercontent.com/6551266/97000906-76f94700-1505-11eb-995a-8df2585cccd8.png)

**5. Versions:**

- AL Language:

- Business Central: NA Business Central 16.6 (Platform 16.0.17024.0 + Application 16.6.17046.0)

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
