### ISSUE TITLE
A member of type Field with name 'Shipping Agent Code' is already defined in Table 'Sales Cr.Memo Header' by the extension 'Base Application by Microsoft (17.0.16993.0)'.

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/AL#6249]
Business Central 2020 wave 2 (v17) SaaS
Hi,
for honest mistake we added in a Tableextesion a field without prefix in our PTE, and now MS added a field with the same name. How can I solve this problem for the SaaS version? We need to generate the new version of PTE compatible with BC17, at now compatible with BC16.5.

Thank you,
Roberto.

**Comment by NavDeb** [comment]
I would also like to know the answer to this as we have similar situation.

**Comment by PooyaKharamesh** [comment]
@robertoscaringella here are the steps 

1.  Backup data
2.  Uninstall extension and wipe data in extension tables
3.  Install extension with field removed

For any questions in the future please note that this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

/Pooya
