### ISSUE TITLE
Data audit fields  on page extension.

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/AL#6251]
**Describe the bug**
Data audit fields SystemCreatedAt, SystemCreatedBy, SystemModifiedAt,SystemModifiedBy on page extensions.
if I add the new fields (here SystemCreatedAd and SystemCreatedBy) to a page extension and set visible = false the user can't see them (personalize)....  with the amount e.g. this works. 
See pictures.

**To Reproduce**
See pictures.

``` AL Code to reproduce the issue ```
See pictures.
![2020-10-23_17h01_23](https://user-images.githubusercontent.com/39938430/97103267-b1044d80-16ab-11eb-943c-51eedd0c7d80.jpg)
![2020-10-23_17h04_24](https://user-images.githubusercontent.com/39938430/97103268-b19ce400-16ab-11eb-9326-c1a6a35a3b9a.jpg)

**5. Versions:**
AL v6.1.352568
BC 17.0.16974.0

**Comment by IvoMol** [comment]
Agree.
Should be possible add into System Application new functions, generally applicable, converting SystemCreatedBy/SystemModifiedBy (GUID) to User ID (Code[50]) or User Name (Text)?

**Comment by qutreson** [comment]
Closing as this issue has been fixed in the latest developer previews and the current release version. The fix was part of 17.1.

**Comment by dtkb** [comment]
@IvoMol 
>  Should be possible add into System Application new functions, generally applicable, converting SystemCreatedBy/SystemModifiedBy (GUID) to User ID (Code[50]) or User Name (Text)?

Sounds good, can you raise it as a separate issue here and/or on Ideas? It won't get any attention now that the original issue here is fixed and the thread is closed.

**Comment by IvoMol** [comment]
Done.
https://experience.dynamics.com/ideas/idea/?ideaid=4f9d1241-c33e-eb11-8fed-0003ff68cf42
