### ISSUE TITLE
Return variable is described as "unused" and autofix damages code

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#6252]
**Return variable is described as "unused" and auto fix damages code**

**Description**

If the return value is named but the name isn't used an `AA0137` message is generated.
The return value is, of course, always used even if the label isn't directly so this is probably a false positive.

If I take your suggestion and try to apply the auto fix both the name and the type are deleted creating broken code as in Sample 2.

**Code sample 1**
``` pascal
    local procedure SHA1(InText: Text) HexHash: Text[40]
    var
        EncryptionManagement: Codeunit "Cryptography Management";
    begin
        exit(EncryptionManagement.GenerateHash(InText, 1));
    end;
```

**Code sample 2**
``` pascal
    local procedure SHA1(InText: Text)     var
        EncryptionManagement: Codeunit "Cryptography Management";
    begin
        exit(EncryptionManagement.GenerateHash(InText, 1));
    end;
```

**Comment by rdebath** [comment]
PS: Also breaks function parameter list if one is removed and does not make any attempt to fix calls (for example remove the calling argument if it's "simple"; ie not a function call)

**Comment by DavidFeldhoff** [comment]
The CaptionClass of labels is also not taken into account.
In this example it states that MyLbl is unused which is wrong
```
Page 50100 "MyPage"
{
    layout
    {
        area(Content)
        {
            label(MyText)
            {
                CaptionClass = MyLbl;
            }
        }
    }

    var
        MyLbl: Label 'My Text';
}
```

**Comment by PaulIvan** [comment]
@rdebath First of all the fact that an explicit return parameter is part of a function but not assigned in the function is indeed an unused variable. Yes of course the function will still return the value whether or not the variable is used but the point is, if the variable is not used, then why have it there in the first place and removing it will have absolutely no impact on the code. That is in the spirit of the rule and it is working correctly

Secondly, we do not currently provide an autofix action with our extension. You are probably using a 3rd party vsc extension to accomplish the auto fix removing unused variables. IF that's the case please create a bug with that project.

**Comment by PaulIvan** [comment]
@DavidFeldhoff I tried and it works fine with the latest version of the compiler. Can you try the
[latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) ?

![image](https://user-images.githubusercontent.com/617029/103903264-f7d6e080-50fb-11eb-8919-983d1f9b66b7.png)

**Comment by rdebath** [comment]
Ah, wrong extension, sorry about that.
I'm not going to argue "label vs instance" or "documentation" here, it's probably pointless.

BUT, in that case please separate the distinct classes of variables into different error numbers so that I don't end up disabling the useful warnings with the others.

For example:

* Local variables
* Return variable
* Function parameters
* Global variables

Obviously it's trivial to remove some, not so much for others.

**Comment by PaulIvan** [comment]
I will close the issue now, feel try to make an improvement suggestion or open a new issue if you believe this has not been resolved and reference the current issue.
