### ISSUE TITLE
'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.'

### ISSUE THREAD

**Issue by 7StoneMen** [microsoft/AL#6253]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to 'Visual Studio Code and run the application'

**Expected behavior**
expect to not have the output window endlessly puking up a stack trace

**Screenshots**
![image](https://user-images.githubusercontent.com/73539813/97337163-8948ed00-1845-11eb-92d6-0e1f45c5048d.png)

**5. Versions:**

 - AL Language:  v6.1.352568

 - Business Central: CA Business Central 16.5 (Platform 16.0.15884.18143 + Application 16.5.15897.16301)

**Comment by PooyaKharamesh** [comment]
@7StoneMen there is not enough information to start any investigation, please fill out the issue according to the instructions in the template. It will help us if you provide a sample project that clearly reproduces the issue.

**Comment by 7StoneMen** [comment]
I am sorry, what more information do you need?  install Visual Studio code.  launch the program.  watch it blow up.  are you asking for links on how to install Visual Studio Code?

**Comment by atoader** [comment]
The issue does not contain sufficient information to reproduce it reliably. We will close it as "no repro".

**Comment by 7StoneMen** [comment]
the issue is resolved.  just uninstall anything remotely tied to GitHub and the problem goes away.

**Comment by TheGreatBorg** [comment]
I have no Git-like extensions and "Go to definition" is of no use - it simply didn't work. But I found a workaround. 

First the error I get:
> [Error - 16.12.14] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
> Processing of message 'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.' 

The Workaround:
I found that using the AL Object Designer from the Panel doesn't work but if I browse the app-files and AL Object Designer opens then you can "Go to definition" from the Code opened from the AL Object Designer
