### ISSUE TITLE
"Width" field property does not work in a grid layout

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/AL#6255]
**Describe the bug**
See screenshot, the result is that the width property is completely ignored, and the fields are way too wide while the caption is cut off.

**To Reproduce**
"Width" field property does not work in a grid layout.
As you can see it decides to have a shorter date field, but a very long time field, and does not allow me to short the time field.

``` AL Code to reproduce the issue ```

`
            grid("Pickup Date/Time Grid")
            {
                field("Pickup Date"; "Pickup Date")
                {
                    ApplicationArea = All;
                    width=10;
                }
                field("Pickup Time"; "Pickup Time")
                {
                    ApplicationArea = All;
                    ShowCaption = false;
                    Width=10;
                }
            }
`

**Expected behavior**
The field width is set to 10, and the grid layout allows for the caption to be shown properly

**Screenshots**
![image](https://user-images.githubusercontent.com/891314/97355294-f2cff800-1853-11eb-94f6-2c76e7777b4b.png)

**5. Versions:**

 - AL Language: Runtime 4

 - Business Central: 15.3

**Comment by dtkb** [comment]
I imagine you need to test this in a current/preview version for it to get anywhere really.

But then, see the [docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-width-property):

> You use the Width property to help to improve readability in lists. The property only takes effect on pages of the type List, ListPlus, ListPart, Document, or Worksheet; when the field control is used in a repeater control. **It has no effect on Card pages.**

So this is not expected to work, and thus not a bug.

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by dtkb** [comment]
There's nothing to fix; what the OP was trying to do is documented as not supposed to work.
