### ISSUE TITLE
no configuration for the debug configuration type snapshotInitialize is available

### ISSUE THREAD

**Issue by cscsindia** [microsoft/AL#6256]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by cscsindia** [comment]
no configuration for the debug configuration type snapshotInitialize is available after pressing F7

**Comment by dtkb** [comment]
You forgot to include any context on what you were doing when this error presented. How is anyone meant to help, given only "something doesn't work"?

**Comment by PooyaKharamesh** [comment]
No enough to start any investigation. Please open a new issue and make sure to follow all the instructions.
