### ISSUE TITLE
Page renders ListParts collapsed if visibility handled from code

### ISSUE THREAD

**Issue by SzabolcsGyorke** [microsoft/AL#6258]
**Describe the bug**
On a Card/ Document page layout if you have a Part with a lispart page in it and if you control its visibility property from code it always appears collapsed - before v17 it started as open. And also messes up the list header - not scrolling with the columns.
**To Reproduce**
Steps and to reproduce the behavior:
1. Just add a list part to a Document page and populate the Visibility property with a Boolean field.

``` AL Code to reproduce the issue ```
part(SalesLines; "Sales Order Subform")
            {
                ApplicationArea = Basic, Suite;
                **Visible = SalesLinesVisible;**
                Editable = DynamicEditable;
                Enabled = "Sell-to Customer No." <> '';
                SubPageLink = "Document No." = FIELD("No.");
                UpdatePropagation = Both;
            }
**Expected behavior**
If the Visibility boolean set to true then show the part page opened and be able to scroll left or right with the column headers following the columns.

**Screenshots**

**5. Versions:**

 - AL Language: 6.0

 - Business Central: 17.0.16993.0

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
