### ISSUE TITLE
Codelens references not clickable

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/AL#6260]
**Describe the bug**
I'm not sure if this is a bug or a missing feature but I've seen references in other languages with "editor.codeLens": true in settings.json be clickable.

**To Reproduce**
Steps and to reproduce the behavior:
1. Enable "editor.codeLens": true.
2. Try clicking a references label.

**Expected behavior**
Clicking it should trigger Peek references (shows a window with the references) so you can navigate to it without switching between mouse/keyboard.
This is low priority but has a nice flow to it. :)
Is this kind of behavior supposed to be language specific in general?

**Screenshots**
![image](https://user-images.githubusercontent.com/8615374/97459163-6137b780-1933-11eb-8e86-5b2f22af869e.png)

**5. Versions:**
 - AL Language: v6.1.359074
 - Business Central: 17.0

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by pborring** [comment]
Added in 2025 release wave 1

![Image](https://raw.githubusercontent.com/microsoft/AL/master/resources/CodeLensReferences.gif)
