### ISSUE TITLE
Assignment error table 12174 "Customer Bill Header"

### ISSUE THREAD

**Issue by Giumai** [microsoft/AL#6261]
In the OnValidate trigger of the field 10 there's an error:

![image](https://user-images.githubusercontent.com/66070271/97462725-5125d500-193f-11eb-8c08-5ed1500ae7ca.png)

The Report Header field is a Text[30] field while Payment Method Description is a Text[100] field

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
