### ISSUE TITLE
Hovering constant's symbols (Label and EnumValue) lacks more detail.

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/AL#6263]
**Describe the bug**
This is just a minor enhancement suggestion for DX.
Currently we have abstractions over constant values, for Text we have Labels and for Integers we have Enums.

When working with Labels it can be useful to be able to see quickly what the label contains.
It's enforced by the CodeCop to name the labels descriptively but we have a lot of global Text001, Text002, Text003, etc. variables which can be refactored over time to appropriate names. But until then, it would be really nice to get a glimpse of the content without needing to navigate back and forth (and possible to rename it with F2 without looking for further context).
A similar concern is apparent when working with Enum values, as there is no way to see the ordinal it returns except if we go to the definition.

**To Reproduce**
Hover over a Label variable or Enum values (e.g. MyEnum::AnOption).

**Expected behavior**
Could the start of the string at least be shown for Labels (even just the start of it followed by ellipsis) and if it's Locked?
The Enum value might show us a bit more information about it - especially the ordinal and even the beginning of the caption, if present?

**Screenshots**
![image](https://user-images.githubusercontent.com/8615374/97461157-64cc3e00-1935-11eb-8e93-626da5185f9e.png)

**5. Versions:**
 - AL Language: v6.1.359074
 - Business Central: 17.0

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by bjarkihall** [comment]
@PooyaKharamesh is it normal that when debugging, Label variables also don't show any content on hover while Text variables do?
I know Text is a variable and Label is a named literal, but it just feels like this area was accidentally left out, rather than it being a feature/idea to upvote - is the Label variable blank on hover by design, even though it holds a value?

**Comment by atoader** [comment]
It is by design at the moment. We would like to enhance this, but we will need to weight it against other requests for Business Central. Posting it on BC Ideas will aid in prioritizing this in the future.

**Comment by bjarkihall** [comment]
@atoader Ok, I wasn't sure if it was a mistake/bug or lack of time/priority, thanks for clearing it up though. :)

**Comment by pborring** [comment]
See and vote on idea for this
https://experience.dynamics.com/ideas/idea/?ideaid=6392e5fb-bf39-ed11-97b1-0003ff45a617
