### ISSUE TITLE
Intellisense no longer finds AL specific Values when start writing with uppercase

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/AL#6264]
**Describe the bug**
When I start writing a new word for excample "rec" VS Code only suggests templates and not "Record". I would have to write "Rec" to get "Record" suggested. This works for all values.

**To Reproduce**
Create a new Variable in a procedure and start writing "rec" after ":".

``` table 50000 "Buffer"
{
    Caption = 'Buffer';
    TableType = Temporary;

    fields
    {
        field(1; "Line No."; Integer)
        {
            Caption = 'Line No.';
        }
        field(10; "Item No."; Code[20])
        {
            Caption = 'Item No.';
            TableRelation = Item;

            #region OnValidate
            trigger OnValidate();
            begin
                if "Item No." = '' then
                    ResetItemFields()
                else
                    CopyFromItem();
            end;
            #endregion OnValidate
        }
        field(11; Description; Text[100])
        {
            Caption = 'Description';
        }
    }

    keys
    {
        key(PK; "Line No.")
        {
            Clustered = true;
        }
    }

    #region CopyFromItem
    local procedure CopyFromItem();
    var
        Item: Record Item;
    begin
        Item.Get("Item No.");

        Description := Item.Description;
    end;
    #endregion CopyFromItem

    #region ResetItemFields
    local procedure ResetItemFields();
    begin
        Description := '';
    end;
    #endregion ResetItemFields
} 
```

**Expected behavior**
No difference between starting a word uppercase or lowercase.

**Screenshots**
rec:
![grafik](https://user-images.githubusercontent.com/46522333/97548033-e58b4880-19ce-11eb-9341-0afd7d61520d.png)
Rec:
![grafik](https://user-images.githubusercontent.com/46522333/97551448-487ede80-19d3-11eb-9496-6c973f374b34.png)

**5. Versions:**

 - AL Language: 6.1.359074

 - Business Central: AT Business Central 17.0 (Plattform 17.0.17020.18049 + Anwendung 17.0.16993.0)

**Comment by NKarolak** [comment]
Though I am using the very same AL Language version and I have copied your codeunit, I cannot reproduce your issue. It might be related to some other extension or a setting, or maybe the VS Code version. My VS Code version is 1.50.1.

**Comment by BernhardKloibmueller** [comment]
My VS Code Version is 1.50.1.

Thank you for the response, I checked it again and disabled all other extensions and discovered the one which issues this.
So this is not a problem of the AL Language Extension
