### ISSUE TITLE
BaseApp cannot be published (BC170)

### ISSUE THREAD

**Issue by Pavel-Titov** [microsoft/AL#6265]
Hi, I have a problem to publish the BaseApp from BC170 (the customized one, after merge and upgrade to BC170).
I am getting these errors:

CustomerCard.Page.al(2268,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'
CustomerCard.Page.al(2271,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'
CustomerCard.Page.al(2274,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'

Here is the code that stands in those lines:
```
            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetAvgDaysPastDueDateLabel(), DictionaryValue) then
                Evaluate(DaysPastDueDate, DictionaryValue);

            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetExpectedMoneyOwedLabel(), DictionaryValue) then
                Evaluate(ExpectedMoneyOwed, DictionaryValue);

            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetAvgDaysToPayLabel(), DictionaryValue) then
                Evaluate(AvgDaysToPay, DictionaryValue);
```

The function is new and was introduced recently:
```
    [TryFunction]
    local procedure TryGetDictionaryValueFromKey(var DictionaryToLookIn: Dictionary of [Text, Text]; KeyToSearchFor: Text; var ReturnValue: Text)
    begin
        ReturnValue := DictionaryToLookIn.Get(KeyToSearchFor);
    end;

```

Interesting fact - if I change the function definition like this:
```
    [TryFunction]
    local procedure TryGetDictionaryValueFromKey(var DictionaryToLookIn: Dictionary of [Text, Text]; KeyToSearchFor: Text; var ReturnValue: Text): **Boolean**
    begin
        ReturnValue := DictionaryToLookIn.Get(KeyToSearchFor);
    end;

```

Then I am getting the compilation error, so I cannot build the BaseApp:
**error AL0244: The signature of procedure 'TryGetDictionaryValueFromKey' does not match the signature required by attribute 'TryFunction': return value is expected to be of type 'None' but found type 'Boolean'. The expected signature is: TryGetDictionaryValueFromKey().**

- AL Extension Version: 6.1.359074

- Server Version: 
Version: (blank) (Platform 17.0.16974.0 + Application 17.0.16993.0)
Azure AD tenant: common, Environment: Production (Production)

**Comment by dtkb** [comment]
I don't see where your confusion is. You need to pass a Boolean to assign the `var ReturnValue`. It's done that way because a `TryFunction` always returns a bool of whether or not an error occurred, so whatever the named `ReturnValue` indicates must be done separately from that, and the only way to do so is as a `var` argument, meaning you must pass a boolean to match.

**Comment by Pavel-Titov** [comment]
ReturnValue parameter should be Text, but the return value of the function has to be Boolean. In the Try Function the type of the return value is not specified, which generates an error during the compilation. When I am specifying the return type in the function, and uploading the app, I am getting an error, that the type must not to be specified.
I am attaching the standard CustomerCard.Page.al file.
[CustomerCard.Page.txt](https://github.com/microsoft/AL/files/5458474/CustomerCard.Page.txt)

**Comment by PooyaKharamesh** [comment]
you can read more about try functions here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-tryfunction-attribute.

Please note that this repository is no longer dedicated to handling application requests and enhancements. So if you need any further assistance on this topic please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by dtkb** [comment]
I misunderstood `ReturnValue`, sorry. I can't see why the original code would be a problem, but then nor have I used that specific function personally.

Adding an explicit return type or value to a `TryFunction` is definitely wrong since it implicitly, and necessarily, returns a boolean: whether or not an error was thrown therein.
