### ISSUE TITLE
Bug: Warehouse Split Line Renumbering not working under certain circumstances

### ISSUE THREAD

**Issue by FabianBigler** [microsoft/AL#6266]
**Describe the bug**
Warehouse Split Line: If Renumbering of all numbers occurs, it can throw an error under certain circumstances (e.g. Deleting Lines before the split lines).

**To Reproduce**
Steps and to reproduce the behavior:
1. Location needs to have "Directed Pick and Put-Away" enabled.
2. Create a new purchase order and purchase line, add three item lines with quantity of 100 each.
3. Release the current purchase order and create a warehouse receipt
4. Post the warehouse receipt
5. Go to created warehouse put-away
6. Split Lines until there is no Line Space left (e.g. line numbers 199'999 and 200'000)
7. Delete some lines before the splitting
8. Split Line No. 199'999 so a renumbering of all lines has to happen
9. Error Message will appear, that a warehouse activity line already exists.

So: ReNumberAllLines on table "Warehouse Activity Line" is not working under all circumstances!

**Expected behavior**
Renumbering should happen as expected (i.e. not throwing an error).

**Applied Bug fix**
I have already fixed the problem in an older NAV Version.
Instead of looping and deleting warehouse activity lines, store them in a temporary table.

Here is the code:
ReNumberAllLines(VAR NewWhseActivityLine : Record "Warehouse Activity Line";OldLineNo : Integer;VAR NewLineNo : Integer)
IF NewWhseActivityLine.GETFILTER(NewWhseActivityLine."No.") = '' THEN
  EXIT;

LineNo := 10000 * NewWhseActivityLine.COUNT;

IF NewWhseActivityLine.FINDSET() THEN
REPEAT
  _TempWarehouseLine.INIT();
  _TempWarehouseLine.TRANSFERFIELDS(NewWhseActivityLine);
  _TempWarehouseLine.INSERT();
UNTIL NewWhseActivityLine.NEXT() = 0;

NewWhseActivityLine.DELETEALL();

_TempWarehouseLine.FIND('+');
REPEAT
  WarehouseActivityLine := NewWhseActivityLine;
  NewWhseActivityLine.INIT();
  NewWhseActivityLine.TRANSFERFIELDS(_TempWarehouseLine);
  NewWhseActivityLine."Line No." := LineNo;
  NewWhseActivityLine.INSERT;

  IF _TempWarehouseLine."Line No." = OldLineNo THEN
    NewLineNo := LineNo;
  LineNo -= 10000;
UNTIL _TempWarehouseLine.NEXT(-1) = 0;

**5. Versions:**
Latest Release as of 29.10.2020: BC 17.0.16974.0

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
