### ISSUE TITLE
Conditional in a Query

### ISSUE THREAD

**Issue by DavidRRA** [microsoft/AL#6267]
Hi Experts

I am having issues trying to create a conditional inside a query.
I have a date column ("LastModifiedDate"), which is sometimes null, in the case it is null I want to get the following date “01/01/1900”
Could you please help me ?

query 70639802 "Sales. Inv. Line"
{
    QueryType = Normal;

    elements
    {
        dataitem(SalesInvoiceLine; "Sales Invoice Line")
        {
            column(DocumentNo; "Document No.")
            {
            }
            column(LineNo; "Line No.")
            {
            }
            column(AmountIncludingVAT; "Amount Including VAT")
            {
            }
            column(LastModifiedDate; "LastModifiedDate")
{
            }

          }
    }

**Comment by PooyaKharamesh** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
