### ISSUE TITLE
AL: Go! does not create the .alpackages folder

### ISSUE THREAD

**Issue by j2associates** [microsoft/AL#6268]
**Describe the bug**
When using AL: Go! to create a new package, the .alpackages folder and files are not created.

**To Reproduce**
Ctrl+Shift+P to activate the command pallet
Select AL: Go!
Define folder
Select 6.0 Business Central 2020 release wave 2
Select Microsoft cloud sandbox
New package is built but with the following error:

The package cache c:\Users\MyName\Documents\AL\JunkTest\./.alpackages could not be found.

Note: If you select 5.0 Business Central 2020 release wave 1, the .alpackages folder and files are created, but you still have to download symbols. In the above scenario with version 6.0, attempting to download the symbols fails.

**Expected behavior**
The result of the AL: Go! process should be a new package that compiles cleanly

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.359074

 - Business Central: Version: US Business Central 17.0 (Platform 17.0.17020.18049 + Application 17.0.16993.0)

**Comment by WilcoHendriksen** [comment]
I've got the same problem, is there a work-a-round? I'm a beginner so not sure what should be done.

**Comment by atoader** [comment]
Have you tried creating the folder manually?

**Comment by j2associates** [comment]
Any ETAs or Work-Arounds in the mean time?

**Comment by EmilDamsbo** [comment]
> Any ETAs or Work-Arounds in the mean time?

That would be:

> Have you tried creating the folder manually?

If this doesn't work, you might have a version of the files in one of your other AL projects. Copying the '.alpackages'-folder from another project to your new one could be a workaround. We are unable to provide any ETAs on this issue.

**Comment by j2associates** [comment]
Working as expected for Visual Studio Code AL Language 6.1.381323, VS Code 1.52.1

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
