### ISSUE TITLE
Add function to change/fill request page required filter fields and properties

### ISSUE THREAD

**Issue by midego1** [microsoft/AL#6269]
Could you please add a function that makes it possible to change/fill the requested filter fields after opening the request page?

- I want to fill the fields from a setup table when running the report.

- Change the properties of the report, e.g. disable save values.

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
