### ISSUE TITLE
GetAddressService example: key id still used, please remove

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#627]
The table object in the GetAddressService example still have id's on the keys defined for these tables, please remove as key id's have become obsolete. As also the compiler tells use:

> file: 'file:///c%3A/Users/vmadmin/Documents/AL/Samples/GetAddressService/Tables/Address.al'
> severity: 'Warning'
> message: 'The use of a unique id has been deprecated and the id can be removed.'
> at: '29,13'
> source: 'AL'

**Comment by StanislawStempin** [comment]
It's fixed now.
