### ISSUE TITLE
Menu command Menu -> Run -> Start Debugging F5 does not work to update / publish to Business Central Sandbox

### ISSUE THREAD

**Issue by apaGitHub** [microsoft/AL#6274]
**Describe the bug**
Menu command Menu -> Run -> Start Debugging F5 does not work to update / publish to Business Central Sandbox. Restart debug icon does not work.

**To Reproduce**
Steps and to reproduce the behavior:

First, start with:
Ctrl + Shift + P 
AL: GO! 
Basic Hello World message app.
HelloWorld.al 
launch.json 
    environmentName: changed to my sandbox environment name
app.json -> change:
    "platform": "17.0.0.0",
    "application": "17.0.16993.0"
Symbols are downloaded.
F5
DEBUG CONSOLE shows Success -> app is published
sandbox browser tab launches -> see "Hello world" message

Then, make change to HelloWorld.al "Hello world" -> "Hello Big AL World!"
Menu -> Run -> Start Debugging F5
DEBUG CONSOLE shows Success -> app is published
sandbox browser tab launches -> see "Hello world" message  (no change, not "Hello Big AL World!")

If I use either the actual keyboard press (F5)
OR
Ctrl + Shift + P
AL: Publish with debugging F5 recently used (return to select)
Then will always get any change to the HelloWorld.al -> sandbox browser tab launches 
(again, Menu -> Run -> Start Debugging F5 never effects the change)

Similarly, the  Restart icon (Cntrl + Shift + F5) does not work. The DEBUG CONSOLE is cleared, but no Restart. 

Pressing the keys Cntrl + Shift + F5 produces warning: There is already a debug configuration "Microsoft cloud sandbox" running.

The Stop (Shift F5) icon works and  pressing the keys Shift F5 does show Warning: Timeout after 2000 ms for 'terminate') but pressing the keys Shift F5 still requires to hit the Stop (Shift F5) icon to remove the Debug icons from it the interface.

``` AL Code to reproduce the issue ```
I initially thought it may be a key-binding issue. On laptop needed to use Fn F5. Then changed in BIOS to default to "F-key behavior). No change in outcome.

Disabled all extensions - re-enabled  AL Language extension. No change in outcome.

**Expected behavior**
Menu -> Run -> Start Debugging F5 should have the same result as pressing F5.
The Restart debugging icon should restart the debugging process.
Pressing  Shift F5 should terminate the sessions and remove the debugging icons from the interface.

**Screenshots**
![hw0](https://user-images.githubusercontent.com/12699789/97924839-ec46f200-1d25-11eb-8de9-15dea210cf1d.JPG)
![hw1](https://user-images.githubusercontent.com/12699789/97924841-ecdf8880-1d25-11eb-8462-e4af34ef8fe6.JPG)
![hw2](https://user-images.githubusercontent.com/12699789/97924843-ecdf8880-1d25-11eb-91f8-868ecae44e88.JPG)
![hw3](https://user-images.githubusercontent.com/12699789/97924848-ef41e280-1d25-11eb-8823-a33232525006.JPG)
![hw4](https://user-images.githubusercontent.com/12699789/97924850-efda7900-1d25-11eb-9460-03813b86706e.JPG)
![hw5](https://user-images.githubusercontent.com/12699789/97924851-efda7900-1d25-11eb-8869-24c771d14328.JPG)
![hw6](https://user-images.githubusercontent.com/12699789/97924854-f0730f80-1d25-11eb-8b9c-65c0c70ad2c0.JPG)
![hw7](https://user-images.githubusercontent.com/12699789/97924858-f10ba600-1d25-11eb-98ab-565278707aaa.JPG)
![hw8](https://user-images.githubusercontent.com/12699789/97924863-f23cd300-1d25-11eb-9e61-04f63c5cb3be.JPG)
![hw9](https://user-images.githubusercontent.com/12699789/97925768-92472c00-1d27-11eb-944f-cdfd82060d11.JPG)
![hw10](https://user-images.githubusercontent.com/12699789/97925770-92dfc280-1d27-11eb-91b2-12dbb38b0643.JPG)

**5. Versions:**

 - AL Language: 
AL Language, ms-dynamics-smb.al, Microsoft, License v6.1.359074
AL development tools for Dynamics 365 Business Central

VSC Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

 - Business Central: Sandbox
    "platform": "17.0.0.0",
    "application": "17.0.16993.0"

**Comment by kalberes** [comment]
There is a bit of misdirection on the default VsCode menu here. 
If you use the menu or debug icon ![image](https://user-images.githubusercontent.com/12760483/98027723-62725400-1e0d-11eb-94b9-664e731eb201.png)
 that will  start a debugging session without publishing equivalent with "Debug without Publishing".
We will try to see if we can rename the built-in VsCode menu text, with the confusing F5 since it should Shift Ctrl F5 for us.   F5 in the AL language server is "publish and debug". The functionality is by design for now. 
Also restarting a debugging session is not implemented at all. Thus that is a missing functionality. If there is a demand for it I suggest creating a request here:  ![image](https://user-images.githubusercontent.com/12760483/98028399-5935b700-1e0e-11eb-9561-2c95b5b41268.png)

**Comment by danocharron** [comment]
I had the same issue.   
Go to Keyboard short cuts  and type the letter and number   F5
this will show all the bindings.
I had a "run task" assigned to F5, once I removed it, then F5 starts debugging.
