### ISSUE TITLE
Definition for field does not exist for field of type enum (AL0132) in dependent app

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6275]
I have an app (call it PROD) with a table of type enum which uses a the Sales Line Type enum from the base app. I also have a test app (call it TEST) which is dependent upon the first.

I can see my enum field in intellisense when working in TEST but the compiler throws an error saying that the definition of the field cannot be found. For now I have had to workaround using _SetFieldValue_ from the Data Type Management codeunit.

I have the same behaviour with a table extension in PROD adding a field to a standard table of type enum with an enum that is defined in PROD. Again, when developing in TEST I can write the code to assign the field value but the compiler throws an error. Again, using _SetFieldValue_ is a workaround for now.

AL Language v6.1.359074

**Comment by atoader** [comment]
Can you provide a set of sample projects that reproduce the issue and a video of the unexpected behavior?

**Comment by jimmymcp** [comment]
I've just tried a simple repro and it works as expected. I will harder to break it later, for now this is a snip of my code and the compiler output.

![image](https://user-images.githubusercontent.com/19267298/98097783-63df6300-1e85-11eb-97ae-fd3d3193acfd.png)

The Type field is a "Sales Line Type" field and the table belongs to the PROD app. The compiler error is in the TEST app.

**Comment by jimmymcp** [comment]
Actually, looks like there is something more fundamental here. Hopefully you can see in this gif that my field shows in intellisense but fails to build. Not sure how to get more info about what is going on here? This field is supplied by a table extension in the PROD app. I'm attempting to reference in and build the dependent TEST app.

![Compilation Error](https://user-images.githubusercontent.com/19267298/98126075-1676ec00-1ead-11eb-93d8-7e356c8f8776.gif)

**Comment by jimmymcp** [comment]
Update: I had been disabling code analysis in the TEST app. Enabling that (CodeCop, UICop) solves the problem 🤔

**Comment by NKarolak** [comment]
I saw something far related when my project references were not correctly defined, or when they weren't loaded yet.

Could you try the following?
1. Enable the code analysis again
2. In TEST, check that dependency to PROD contains the exact, current PROD version number. // project reference
3. Publish PROD
4. Reload Window (not sure it's actually needed).
5. Open any PROD object, then any TEST object. // reference load
6. Try to reproduce

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
