### ISSUE TITLE
Error Extensions V2

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#628]
When I open the al files on visual studio code I get loads of errors. How do I fix those error?

Those are some of the errors.

file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Codeunit%2070018003%20-%20EDI%20Foundation.al'
severity: 'Error'
message: 'The type or method 'Object' cannot be used for 'Extension' development.'
at: '24,11'
source: 'AL'

file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Codeunit%2070018003%20-%20EDI%20Foundation.al'
severity: 'Error'
message: 'The name '"Table No."' does not exist in the current context'
at: '225,23'
source: 'AL'

**Comment by atoader** [comment]
Could you please provide a snippet that gives you these errors?

**Comment by andrecavalcanti** [comment]
Atoader that is one of them
[var
    "3TierMgt" : Codeunit 419;
    ediType : Record 70018009;
    ediEvent : Record 70018008;
    spointFoundation : Codeunit 70018008;
    gotSetup : Boolean;
    ediSetup : Record 70018000;

  procedure CheckTableExists(tableNo : Integer) : Boolean;
  var
    obj : Record 2000000001;
  begin
    obj.SETRANGE(Type, obj.Type::Table);
    obj.SETRANGE(ID, tableNo);
    IF obj.FINDFIRST THEN
      EXIT(TRUE)
    ELSE
      EXIT(FALSE);
  end;

  procedure GetTableFieldNos(tableNo : Integer) : Text[100];
  var
    "field" : Record 2000000041;
    working : Text[1024];
  begin
    working := '';
    field.SETRANGE(TableNo, tableNo);
    IF field.FINDSET THEN REPEAT
      IF IsFieldKey(tableNo, field."Field Caption") THEN BEGIN
        IF working = '' THEN
          working := FORMAT(field."No.")
        ELSE
          working := working + ',' + FORMAT(field."No.");
      END;
    UNTIL field.NEXT = 0;
    EXIT(working);
  end;](url)

**Comment by andrecavalcanti** [comment]
![2017-09-07_0752](https://user-images.githubusercontent.com/6551266/30162239-09988d3e-93a2-11e7-9270-2b34cf41e86c.png)

**Comment by esbenk** [comment]
The object table is not support for extensions. Please use 2000000058 AllObjWithCaption

**Comment by andrecavalcanti** [comment]
It works . 

thanks
