### ISSUE TITLE
GridLayout showing blank

### ISSUE THREAD

**Issue by AmolSalvi** [microsoft/AL#6282]
**Describe the bug**
While applying following pattern for gridlayout it web client shows blank screen .This issue occurs for V17 but it was working properly in V16

**To Reproduce**
Steps and to reproduce the behavior:
page 40007992 TestGridlayoutCard
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Test Design Table";

    layout
    {
        area(Content)
        {
            group(General)
            {
                field("Design No."; Rec.Field1)
                {
                    ApplicationArea = All;
                }
                field("Product Group"; Rec.Field2)
                {
                    ApplicationArea = All;
                }
            }
            group(Variants)
            {

                grid(Grid1)
                {
                    GridLayout = Rows;
                    Grid(Group1)
                    {
                        GridLayout = Columns;
                        group(Control39)
                        {
                            ShowCaption = false;
                            part(Part1; "Test Surface Subpage")
                            {
                                ShowFilter = false;
                                SubPageLink = "Design No." = FIELD("Design No.");
                                ApplicationArea = All;
                            }
                        }
                        group(Control37)
                        {
                            ShowCaption = false;
                            part(part2; "Test ClrStone SubPage")
                            {
                                ShowFilter = false;
                                SubPageLink = "Design No." = FIELD("Design No.");
                                ApplicationArea = All;
                            }
                        }
                        
                    }
                }
            }
        }
    }

    
}

``` AL Code to reproduce the issue ```

**Expected behavior**
All the subpage should show column wise
![image](https://user-images.githubusercontent.com/17919257/98321785-8655b580-2018-11eb-803b-3a03f3c512f8.png)

**Screenshots**

**5. Versions:**

 - AL Language: v6.1.362735

 - Business Central:W1 17.0 (Platform 17.0.17020.17347 + Application 17.0.17126.17384)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by AmolSalvi** [comment]
Thank you..
