### ISSUE TITLE
Event request in 1099 statistic page

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#6283]
Hi 

during my app development, I Need a event trigger on "Vendor 1099 Statistics" page.  here is the screen shots whrere I need 

![image](https://user-images.githubusercontent.com/38460823/98324846-65d72c80-2013-11eb-9d3b-41b183bf6158.png)

I need to apply more filters here for my app.

Thanks 
Sahil Gupta

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
