### ISSUE TITLE
Event trigger request on Customer/Vendor entry statistics 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#6284]
Hi

during my app development, I Need a event trigger on "Vendor Entry Statistics" and "Customer Entry Statistics" page. here is the screen shots where I need trigger

vendor entry statistics 
![image](https://user-images.githubusercontent.com/38460823/98325533-0a0da300-2015-11eb-8f1a-881a8eeb0592.png)

Customer Entry statistics
![image](https://user-images.githubusercontent.com/38460823/98325693-6b357680-2015-11eb-96c7-2f2f9f4c65fb.png)
 

I need to apply more filters here for my app.

Thanks
Sahil Gupta

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
