### ISSUE TITLE
critical logical issue in all 1099 reports

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#6285]
in all 1099 reports, it process all entries vendor by vendor and then we build an array of amounts and then we have a logic to decide that do we need to print this amounts accordingly to minimum amounts here is the logic for it by MS

![image](https://user-images.githubusercontent.com/38460823/98326645-b05aa800-2017-11eb-826b-b48d5f193b61.png)

but the issues is when a vendor can have multiple ledger entries with multiple form 1099 codes look into following screen shot
![image](https://user-images.githubusercontent.com/38460823/98326696-d08a6700-2017-11eb-9caf-b443f3cc3d13.png)

these are the multiple ledger entries of a one vendor . now if you run 1099 report then it will work in that way what i explained above.
where MS checking the minimum amount there is a variable "PrintThis" if that is true for one of the code and then later if we found another code then it will never set again and we are using this one variable for all amounts. which is wrong... i thing if it is less than minimum amount then we should set the amount =0 in array rather than print this.

example:
suppose in the screen shot, we have div-09 code which i set minimum amount 600 and originally we have 200 in ledger entry so for me it should not print but it is still printing in the reports because he set up the variable true for rest of the code which are prior to div-09 .

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
