### ISSUE TITLE
VSCode doesn't publish changes 

### ISSUE THREAD

**Issue by Ninimjinde** [microsoft/AL#6288]
**Describe the bug**
I have some issues with publishing my apps lately. When I want to publish my app ( on prem or saas ) he doesn't change anything in my environment. Nothing changes and even if I do a "'schemaupdate' = recreate", nothing changes. Allready tried to uninstall VScode and extensions. Doesn't work

**To Reproduce**
Start VSCode, try to publish your app onprem or SAAs with ctrl + F5 or F5.
Nothing changes in your environment.

**Expected behavior**
Normally I see all my changes that I made in my code, pages, tables or codunits.

**5. Versions:**

 - AL Language: v6.1.362735

 - Business Central: BC170

**Comment by Ninimjinde** [comment]
It seems that there's a difference when you work with Ctrl + F5 or select it with mouseclick via 'Run' and then 'Run without debugging' ?

**Comment by BernhardReu** [comment]
I encountered exactly the same issue today and was also able to pinpoint it to a difference in behaviour between "Run -> Run Without Debugging" and simply pressing "Ctrl + F5" as shortcut! 
The shortcut is even written next to the command in the menu so it strongly suggests that it executes the same command.

AL Language Extension: v6.1.362735
Business Central 14

**Comment by kalberes** [comment]
See #6274
