### ISSUE TITLE
Bug: Lookup on subpage not working when field is populated, and subpage has dynamic visibility

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/AL#6289]
**Describe the bug**
On Page where we have multiple Subpages, we control the visibility of them by actions on top. Lookup on fields that have TableRelations in the background only works if the field value is empty. For a field with an existing Value, lookup can only be processed by ALT + down, not by mouse click!
When I comment Visible property of part, everything works as expected.
Probably similar to #4788 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a page with subparts (subpart must have at least one field with TableRelation to other table)
2. Put in Visible property on part  to some global boolean value
3. create action that will show/hide that part
4. populate a field on subpart with TableRelation from the list by using Lookup
5. Try again to click on the lookup button on that field (nothing will happen) 
6. Try to use ALT + down combination(lookup will be shown)

**Expected behavior**
The lookup should always work, no matter is field populated or not, and no matter of the Visibility property of the subpage.

**Screenshots**
![LookupIssue](https://user-images.githubusercontent.com/54843470/98533607-7beb2400-2283-11eb-86bb-299633831a50.gif)

**Versions:**

 - AL Language: 6.1.362735
 - Business Central: 17.0

**Comment by AskeHolst** [comment]
I have seen similar behavior and was able to solve it by giving the global booleans a value in the OnInit() trigger. 
https://twitter.com/AskeHolst/status/1316003300895064065

**Comment by NemanjaKutlesic** [comment]
That is not working in my case. I put init value to every boolean that controls the visibility of the parts, still the same behavior.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
