### ISSUE TITLE
Selecting a non-existing JSON property in a JsonObject using JPath gives a very non-descriptive strange error

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#629]
// JObj is JsonObject
// JToken is JsonToken

JObj.Add('name', 'John Doe');
JObj.SelectToken('$.nme', JToken); // this fails with error that only says: "$.nme"

It should fail with a more descriptive error message, such as: "Could not find $.nme in JsonObject." or something to indicate what exactly went wrong.

**Comment by atoader** [comment]
Good point! I will add a better error message.
