### ISSUE TITLE
Request a new key in Check Ledger Entry

### ISSUE THREAD

**Issue by ikuljeetsingh** [microsoft/AL#6291]
I need a key in Table 272 - Check Ledger Entry Table  (Key: "Bal. Account Type", "Bal. Account No.", "Posting Date"), that is much required in many areas to speed up the processing.

Requesting you to add this Key in the standard table, as we are unable to add this as a developer.

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
