### ISSUE TITLE
Error "Enum does not contain value x" after uninstalling an extension 

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6292]
**Describe the bug**

- I have a 'Core' app with an enum / interface and a default implementation (value 'Navitrans 365 API (Azure)'). 
In a setup table, the required enum can be configured.
- I have a second app 'OnPrem' extending the enum, implementing the interface, adding the enum value 'Itext'
- In the install codeunit of the second app, I update the setup table to refer to the new extended enum (value 'IText' is set in the Setup table)
- All works fine

![image](https://user-images.githubusercontent.com/25268332/98671836-297a3800-2355-11eb-87d9-63766b907707.png)

- However, when uninstalling the second app ('OnPrem'), I've no option to reset the enum value in the setup table back to the default value.
- When navigating to the setup page, I get an error '**Enum does not contain value 1**', since the setup field still contains an enum value, that is no longer supported, since the extension implementing the enum has been uninstalled in the meanwhile.

**Expected behavior**

- How can we avoid the technical / cryptical error message for end users?
- How can we restore / reset a value upon uninstalling an extension, to avoid invalid references to non-existing enums?

**5. Versions:**

 - Business Central: ersion: W1 17.1 (Platform 17.0.18204.18458)

**Comment by atoader** [comment]
We have this in our backlog and we are aiming to deliver functionality to improve this story. We will update this thread when we have more information.
