### ISSUE TITLE
LookUp on field in listpart does not work when visibilities are used for showing the listpart on the page

### ISSUE THREAD

**Issue by PP1986** [microsoft/AL#6293]
**Describe the bug**
Situation:
Card page with several fields, one of which is an enum. The chosen value for this field determines which listpart should be visible.
There are 2 listparts present on the page, one should show for all but one enum values, the other one should show for that one value. Both listparts have the exact same field in them with a lookup. 
For one of the listparts, the lookup works fine, while for the other one it is impossible to get it to work. 
When I remove the visibility property from both listparts, so they show both, all lookup work fine.
It doenst make a difference if visibilities are set directly, through a variable or on a group.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create an enum
2. Create a header table with an enum field in it
3. Create 2 lines tables
4. Create ListPart Pages for the 2 lines tables and make sure both have a field with a lookup (same field)
For example: 
                field("Table No."; Rec."Table No.")
                {
                    ApplicationArea = All;

                    trigger OnLookup(var Text: Text): Boolean
                    var
                        "Field": Record Field;
                        AllObj: Record AllObjWithCaption;
                        Objects: Page "All Objects with Caption";
                    begin
                        AllObj.SetRange("Object Type", AllObj."Object Type"::Table);
                        Objects.SetTableView(AllObj);
                        Objects.LookupMode(true);
                        if not AllObj.IsEmpty() then
                            Objects.SetRecord(AllObj);
                        if Objects.RunModal() = Action::LookupOK then begin
                            Objects.GetRecord(AllObj);
                            Rec.Validate("Table No.", AllObj."Object ID");
                        end;
                    end;
                }
5. Create a Header card page and add the two listparts
6. Add a visibility property to the parts where the visibilty is determined by the enum value being a certain value vs it not being that value.
7. Try to do a lookup in both cases.

**Expected behavior**
LookUp should work in both cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/44785533/98687280-d959a080-2369-11eb-9234-4f6906924436.png)
![image](https://user-images.githubusercontent.com/44785533/98687316-e4143580-2369-11eb-89c4-80b5c2833771.png)
![image](https://user-images.githubusercontent.com/44785533/98687372-f2625180-2369-11eb-9fe5-cb1f0eaaf619.png)
Clicking the Table No. "..." now doenst do anything, it should give the same page as in the second image.

**5. Versions:**

 - AL Language: v6.1.362735

 - Version: NL Business Central 17.0 (Platform 17.0.17020.17674 + Application 17.0.17126.17712)
(issue did not exist in BC14, BC15 and BC16)

**Comment by atoader** [comment]
Hi Petra! Is this strictly related to the fact that the enum is used for controlling visibility or the structure of the page and toggling visibility dynamically? Can you provide a zip of the project that you are describing?

**Comment by atoader** [comment]
My intuition is that this is a runtime bug, so it might not be something we can accept in this repository, but a repro will be helpful nonetheless

**Comment by PP1986** [comment]
Hi,

Here is a link to a zipped project with the described issue.
https://www.dropbox.com/t/3L4AFDrJax5D6BYp

Toggling the visibility (change enum value) gives the same result as opening the page and not changing the enum value anymore.

**Comment by PP1986** [comment]
Hi,
Is there any news on this issue? And if it turns out to be a runtime issue, where should I go to mention it?
Here is a new link as the former one has expired:
https://www.dropbox.com/s/tn7v3eioivpt9ef/LookUpIssue.zip?dl=0

**Comment by PieterJacob** [comment]
We have the same issue! 
For a main page with a subpage (listpart) that is linked with an expression for the visibility, the lookup does not get triggered.
When the visibility expression is removed, the lookup works again as normal.

**Comment by PP1986** [comment]
@atoader any news on this issue? It has quite an impact on our product.

**Comment by atoader** [comment]
Hi! Sorry for the late reply, a lot of messages were left unanswered in the holiday period. For runtime issues, you should file a support case or raise the issue through Collaborate. 

```
To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
```
