### ISSUE TITLE
Rec is not maintained properly in Factboxes starting in BC 17

### ISSUE THREAD

**Issue by jcooper01** [microsoft/AL#6294]
**Describe the bug**
We have a complex page that has actions on the main page, multiple subpages, and factboxes on the main page that are linked to subpages. The main page uses functions on the factboxes to query which record is selected on the linked subpage, as the provider of the factbox should supply this data. This has worked from NAV 2009 through BC 16. It stopped working in BC 17.

**To Reproduce**
Install our ChargeLogic Shipping app. The Shipping Station Interface is not able to track which record is selected as you go through the process of shipping an order.
``` AL Code to reproduce the issue ```

**Expected behavior**
Rec in the factbox should match the selected record from its provider. It seems to be empty.

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.362735

 - Business Central: 17.x

**Comment by atoader** [comment]
Hi Jonathan! As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

Support should be able to help create a repro for the teams owning those components.
