### ISSUE TITLE
ProcessReportData funciton in CU8800 not available for CLOUD

### ISSUE THREAD

**Issue by EpicRiceBall** [microsoft/AL#6295]
**Describe the bug**
We are trying to extend report selection to accommodate our custom report. 
I tried to use the ProcessReportData function in CustomReportLayout, but got compiler error that this function cannot be used for cloud, i couldnt find any similar function for CLOUD, can you suggest alternative function or let me know if this will be made available in the future release?

"error AL0296: The type or method 'ProcessReportData' cannot be used for 'Extension' development."

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new PageExtension object to extend Customer Card
2) Add a new action ( for Printing)
3) add the following codes in the OnAction trigger

trigger OnAction()
                var
                    ReportSelections: Record "Report Selections";
                    Customer: Record Customer;
                    CustomLayoutReporting: Codeunit "Custom Layout Reporting";
                    RecRef: RecordRef;

                begin
                    RecRef.Open(DATABASE::Customer);
                    //CustomLayoutReporting.SetOutputFileBaseName(StatementFileNameTxt);
                    CustomLayoutReporting.SetTableFilterForReportID(Report::"XX-New Report", Rec."No.");
                    CustomLayoutReporting.ProcessReportData(ReportSelections.Usage::"XX-NewReport", RecRef, 
                     Customer.FieldName("No."), DATABASE::Customer, Customer.FieldName("No."), true);
               end

**Expected behavior**
This did not compile as expected. 
"error AL0296: The type or method 'ProcessReportData' cannot be used for 'Extension' development."

**Screenshots**
N/A

**5. Versions:**

 - AL Language: 6.1.362735

 - Business Central: BC17

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
