### ISSUE TITLE
VSC open browser with Webclient Base URL

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/AL#6297]
**Describe the bug**
I am using sandbox on my PC. I set port sharing. So I have access to my snadbox on my PC from company network. Developers can connect to my sandbox through VSC and they can do changes. 
Developer can publish new extension version to my sandbox. Developer can download symbols from my sandbox. Everything works perfectly. Problem is that when developer use F5 for publishing and debugging VSC open browser where is different URL than developer set in launch.json. URL gets from my sanbox with container name and port. So developers have to manually change URL from containername:port to myPCname:port and after that everything works.

Example:
Container name: TEST
Container is on PC: PC-STATION1
Port mappings: 7049 --> 7249
                         80 --> 82

Publishing and debugging on PC-STATION
  publishing works and VSC open web browser with http://TEST/BC. It works

Publishing and debugging on STATION in network
  publishing works and VSC open web browser with http://TEST/BC. It doesn't works it have to be changed to http://PC-STATION:82/BC and after that everything works.

I can't change Webclient Base URL because it moves problem from one PC to another. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Create new container with sandbox (last version of BC 17) on PC 
2. Set port mapping (you can set it during container creation when you use BCContainerHelper)
3. Use different PC in same network to test it
4. Run VSC
5. Create Hello Word project
6. Use setup similar to "Publish to PC-STATION1" in my launch.json
7. Download symbols
7. Use F5 for publish project
8. Project is published without errors
9. Browser is opened with wrong URL 

``` 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch", 
            "name": "Publish to My SandBox 17",
            "server": "http://TEST",
            "tenant": "default",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "schemaUpdateMode": "Synchronize",
            "breakOnError": true,
            "launchBrowser": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements" : 10,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "dependencyPublishingOption": "Ignore",
        },
        {
            "type": "al",
            "request": "launch",
            "name": "Publish to PC-STATION1",
            "server": "http://pc-station1:82",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "schemaUpdateMode": "Synchronize",
            "port": 7249,
            "breakOnError": true,
            "launchBrowser": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements" : 10,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "dependencyPublishingOption": "Ignore",
        },
   ]
}
``` 

**Expected behavior**
VSC should follows parameter "server" in launch.json when open browser. If there is some reason for this behaviour it should be some optional parameter that force setup from web client base URL. 

**Screenshots**

**5. Versions:**
 - AL Language: v6.1.362735
 - Business Central: 17.0.17126.18832-CZ

**Comment by atoader** [comment]
This looks like a bug. We'll add it to our backlog for a more in-depth evaluation.
