### ISSUE TITLE
'Go To Definition" (F12) not available for "Library Assert"

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#6298]
**Describe the bug**
When I have a variable of Assert, I can go to the definition of this codeunit. 
With the "Library Assert" I don't so any code.

https://www.yammer.com/dynamicsnavdev/threads/942954636828672

**To Reproduce**
Steps and to reproduce the behavior:
1. Open the attached project (.zip) in VS Code
[ALProject1.zip](https://github.com/microsoft/AL/files/5536981/ALProject1.zip)

2. 'Go to definition' (F12) on both lines below in object codeunit 50100 MyCodeunit and see the difference.
        Assert.AreEqual();
        LibraryAssert.AreEqual();

**Expected behavior**
'Go to definition' available for Library Assert, like in Assert. See screenshots below.

**Screenshots**

![image](https://user-images.githubusercontent.com/69308907/99077242-b672fa80-25bc-11eb-8772-3398bba4e054.png)

![image](https://user-images.githubusercontent.com/69308907/99077261-bf63cc00-25bc-11eb-8ea2-7e27c8163ce6.png)

**5. Versions:**

 - AL Language: v7.0.341259

 - Business Central: Version: W1 17.0 (Platform 17.0.17020.18681 + Application 17.0.17126.18712)

**Comment by bjarkihall** [comment]
I'm guessing the System Application and Test-related applications have "showMyCode: false" when bundled, which I don't see any valid reason for doing.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by atoader** [comment]
Re-opened it for investigation. The semi-automated triage got a bit too aggressive.

**Comment by Drakonian** [comment]
I support the guys, I see no reason to hide System Application.
