### ISSUE TITLE
XmlPort Error (The Element is expected by Min Occurs value XXX: Once. Element received: YYY) . 

### ISSUE THREAD

**Issue by vpacker** [microsoft/AL#6300]
**Describe the bug**
Im Continually getting this error in my xmlport The Element <PL> is expected by Min Occurs value: Once. Element received: <PH>. Ive tried various MinOcurrs settings and MaxOccurs settings nothing seems to resolve my issue.. 

**To Reproduce**
Debugged the XmlPort Code but unable to ascertain what is causing this issue there is no clear reason why. I have looked
at examples of similar code and can't really see a difference

``` AL Code to reproduce the issue ```
xmlport 80002 "PC Purchase Order Import"
{
    Direction = Import;
    DefaultFieldsValidation = TRUE;
    Format = VariableText;
    UseRequestPage = false;
    TextEncoding = MSDOS;
    FieldDelimiter = '"';
    FieldSeparator = ',';
    RecordSeparator = '<NewLine>';
    TableSeparator = '<NewLine><NewLine>'; 
    TransactionType = UpdateNoLocks;
    
    schema
    {
        textelement(ROOT)
        {   
            TableElement(PH;"Purchase Header")
            {
                MinOccurs = Once;
                MaxOccurs = Once;
                SourceTableView = WHERE("Document Type"=Const(Order));
                Autosave = True;
                FieldElement(FLD1;PH."Buy-from Vendor No.")
                {
                }
             
                FieldElement(FLD2;PH."Location Code")
                {
                }
                FieldElement(FLD3;PH."Currency Code")
                {
                    trigger OnAfterAssignField()
                    begin
                        If PH."Currency Code" = 'AUD' then clear(PH."Currency Code");    
                    end;    
                }
                textelement(FLD4)
                {
                    trigger OnAfterAssignVariable()
                    begin
                        If not Evaluate(LineDisc,FLD4) then
                            Error('Invalid Line Discount')
                        else If LineDisc > 100 then
                            Error('Line Discount > 100');
                    end;
                }
                textelement(FLD5)
                {
                    trigger OnAfterAssignVariable()
                    begin
                        If not Evaluate(invDisc,FLD5) then
                            Error('Invalid Line Discount')
                        else If InvDisc > 100 then
                            Error('Inv Discount > 100');
                    end;  
                }
                TableElement(PL;"Purchase Line")
                {
                    AutoSave = true;
                    SourceTableView = Where(Type=Const(item));
                    LinkTable = PH;
                    LinkFields = "Document No." = field("No."), "Document Type" = Field("Document Type");
                    FieldElement(FLD1A;PL."No.")
                    {
                        trigger OnAfterAssignField()
                        var
                            myInt: Integer;
                        begin
                            lineNo += 10000;
                            PL.Validate("Line No.",lineno);      
                        end;    
                    }
                    FieldElement(FLD2A;PL."Quantity")
                    {
                    }
                    FieldElement(FLD3A;PL."Unit Of Measure Code")
                    {
                    }
                    FieldElement(FLD4A;PL."Direct Unit Cost")
                    {
                        trigger OnAfterAssignField()
                        begin
                            PL.Validate("Line Discount %",LineDisc);
                        end;    
                    }
                    trigger OnAfterInitRecord()
                    begin
                        Cnt2 += 1;
                        If Cnt2 < 4 then currXMLport.Skip();
                    END;    
                }
                trigger OnAfterInitRecord()
                begin
                    Cnt1 += 1;
                    If Cnt1 = 1 then currXMLport.Skip();
                END;    
            }   
             
        }
    }
    trigger OnPreXmlPort()
    begin
        Clear(cnt1);
        Clear(cnt2);
        Clear(LineNo);
        Win.Open('Importing SKU #1##############');
    end;
    trigger OnPostXmlPort()
    var
    begin
        Win.Close;
    end;
    
    var
        LineDisc:Decimal;
        InvDisc:Decimal;
        LineNo:Integer;
        Cnt1:integer;
        Cnt2:integer;
        win:Dialog;       
}
The CurrXmlPort Skip functionality is being used to skip over Excel header lines 
The Excel file layout is as follows It consists of two header rows One for purchase header information, Then Other for purchline
information
Supplier   No | Location | Currency | Line Discount % | Invoice   Discount %
SUP-00001 | NSW | AUD | 10 | 0 |  
SKU | Qty | UOM | Direct Unit Cost |   |  
SKU-000001 | 2 | PCS | 45 |   |  
SKU-000001 | 2 | PCS | 45 |   |  
SKU-000001 | 2 | PCS | 45 |   |  
SKU-000001 | 2 | PCS | 45 |   |  
SKU-000001 | 2 | PCS | 45 |   |  
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  

**Expected behavior**
'I'm Trying to Open a CSV excel file and read various fields to construct a purchase Order with attached purchase lines.
I expect that I could produce the Purchase header and via the lnkfields, link table build the purchase lines. 
But I continually get the error described and I can't understand what the issue is and why it occurs??

**Screenshots**
![image](https://user-images.githubusercontent.com/45345510/99098880-be1eb780-262d-11eb-8725-7d9e028cee7a.png)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by vpacker** [comment]
I figured out the issue by going back to the old CSide XmlPort Designer. It appears that when you use Variable Text format you are not allowed to use Indented Tables the only format it allows is XML Format to do this. Unfortunately AL happily compiles it all and doesn't notify you of a problem. You only see the problem when you run the code and it pops up with the obscure Msg. I spent hours and hours trying to understand what it was telling me, Just goes to show the old CSide XmlPort Designer tells you that what you are trying to do is invalid upfront before going thru the aggravations of trying to run the code. AL unfortunately is not so co-operative in that department. Live and learn I guess.

**Comment by atoader** [comment]
@vpacker we will look into adding more validation for this in VSCode. Could you provide the TXT file for C/SIDE and a screenshot of where the diagnostic is raised so that we can pick this up in the future? Sample code helps us reproduce the issue way faster than a textual description.

**Comment by vpacker** [comment]
Hi Alexandru,

 

The issue is that AL code does not recognise a problem exists before hand when you design an xmlPort that uses variable text format but have designed the XMlport to use multiple linked table structures.

In CSide Xmlport designer informs you of the problem before you attempt to run it. Al on the other hand has no concept of the problem before hand but gives you an obscure reference message after executing the code that I raised as the issue.

I’m guessing the way AL works it makes assumptions that you know before hand the possible pitfalls you can create without actually knowing it. The problem I experiences was very frustrating as I was 100% sure that the XMLport code I wrote was structurally sound, had no real clue as to what I was doing wrong. 

Out of necessity I went back to the CSide XmlPort dsigner to do exactly the same thing I did in AL and after coding it all up I got no errors then I remember I needed to change the format from XML to variable Text and presto the problem revealed itself straight away as Cside immediately complained of an error. It was at this point I realised just what the AL issue was all about!!! It seems obvious now but with out Cside Xmlport designer I would still be struggling trying to figure out just what I was doing was wrong.

 

Thanks

Vic
