### ISSUE TITLE
Cannot publish APP on Azure hosted Business Central container

### ISSUE THREAD

**Issue by anwar0206** [microsoft/AL#6301]
**Describe the bug**
When trying to publish the app from AL environment  gives below error.
[2020-11-14 18:16:16.34] Publishing AL application using launch configuration 'Your own server'.
[2020-11-14 18:16:16.66] Targeting server 'xxxxxx' and server instance 'xxxx'.
[2020-11-14 18:16:16.73] Using user name and password authentication. User name used is: 'user1'.
[2020-11-14 18:16:16.74] Sending request to xxxxx
[2020-11-14 18:16:16.95] Error: No such host is known.
No such host is known.

[2020-11-14 18:16:16.95] Error: An error occured while processing the request.
Request ID: 5339337c-9270-4834-9076-6415baa2cfef
Session ID: ce1164b0-9eb2-47bb-87d3-248055df313a

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.

**Expected behavior**
AL should publish the App

**5. Versions:**

 - AL Language: Version 6.1.362735
Business Central On Premise v16 as well as Business Central Sandbox v17

**Comment by atoader** [comment]
Hi! Do I understand correctly that you are trying to publish to a BC Docker container, not the SaaS environment. Have you tried to debug the resolution of the host xxxx ?
This does not seem to be a development tools issue, but an issue with your configuration. We will need more information to decide on how to triage this issue.

**Comment by anwar0206** [comment]
Hi,

You got it correct it's a BC Docker container on Azure.
 
Please find below the text from launch.json for your reference.

We tried removing the environmentType and checked giving the same error.
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "environmentType": "Sandbox",
            "server": "https://bcv172020.eastus.cloudapp.azure.com",
            "serverInstance": "navserverdev",
            "authentication": "UserPassword",
            "port": 443,
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default"
        }
    ]
}

**Comment by atoader** [comment]
Are you connecting to the container from within the VM or from outside the VM? In any instance, this appears to be outside the scope of this repository.  

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
