### ISSUE TITLE
Warning on maximum table/field caption length

### ISSUE THREAD

**Issue by Nyryus** [microsoft/AL#6303]
**Describe the bug**
I think that AL Language is missing a warning when inserting a table/field caption.
Starting from the tables the "Table Metadata".Caption is Text[80] and AllObjWithCaption."Object Caption" is Text[249]
Furthermore the output of "Table Metadata".Caption is not limited to 80 characters.

**To Reproduce**
I attach a sample extension to reproduce the issue.
[CaptionBehavior.zip](https://github.com/microsoft/AL/files/5546794/CaptionBehavior.zip)

Running the Action that I created in page "EOSSample Table" we can see the caption is different based on the table that we are getting it from.

![image](https://user-images.githubusercontent.com/40896051/99261037-77db7b00-281c-11eb-9804-6e7f0a49968b.png)

And running the table editing the URL to ?table=50100 we can see that the Caption is truncated.
![image](https://user-images.githubusercontent.com/40896051/99261277-c557e800-281c-11eb-97a8-351ee32e1862.png)

But when we try to run the table "Table Metadata" the caption is not truncated, ignoring the limit of 80 characters.

ID | Name | Caption | DataPerCompany | LookupPageID | DrillDownPageId | DataCaptionFields | PasteIsValid | LinkedObject | DataIsExternal | TableType | ExternalName | ObsoleteState | ObsoleteReason | DataClassification | ReplicateData | CompressionType | System ID | Created At | Created By | Modified At | Modified By
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
50100 | EOSSample table | CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____ | Yes | 0 | 0 |   | Yes | No | No | Normal |   | No |   | ToBeClassified | Yes | Unspecified | {00000000-0000-0000-0000-000000000000} | {00000000-0000-0000-0000-000000000000} | {00000000-0000-0000-0000-000000000000}

Closing the page it returns the error:
![image](https://user-images.githubusercontent.com/40896051/99248212-64261980-2808-11eb-8704-87213e7ef347.png)

The behavior is stranger on fields because on the page all the characters are exported.
I'm can't attach a screenshot, but I post the html produced in a list page:
```
<a draggable="false" href="#" role="button" class="thm-cont-c5-font-size thm-cont-c5-font-stack thm-cont-c5-color--medflat" id="column_header_16" data-sorting-column-link="true" title="Sort on 'CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____'" data-tabbable="true" data-prev-tabindex="-1" tabindex="0" aria-label="CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____, sorted in Ascending order">CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____CaptionOf300Char____</a>
```

In a card page:
![image](https://user-images.githubusercontent.com/40896051/99261599-38615e80-281d-11eb-9c14-ea0e347225d8.png)

The get of the caption from the "Fields" table return the Caption truncated
![image](https://user-images.githubusercontent.com/40896051/99261883-93935100-281d-11eb-90ff-bb5b93f6dc47.png)

Same things happen with xliff.

**Expected behavior**
I expect a warning when inserting a caption longer than 80 characters informing the developer that it could cause some kinds of problems.

**5. Versions:**
 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.0.361799
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central:
Version: W1 17.1 (Platform 17.0.18204.18738 + Application 17.1.18256.18792)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
