### ISSUE TITLE
REPORT 20 ERROR: The multi-part identifier <FieldName> could not be bound

### ISSUE THREAD

**Issue by MassimoMarraSerinf** [microsoft/AL#6305]
Hello,
I've added a new field (via Tableext) to table 254 (VATEntry).
On a clone of the Standard Report ID 20 - "Calc. and Post VAT Settlement" I've add a new filter on my new field. Build OK. When report run I receive the error:

Msg 4104, Level 16, State 1, Line 10
The multi-part identifier "254_e1.<field Name>" could not be bound.
Msg 8180, Level 16, State 1, Procedure sp_prepexec, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.

The filter has been added here:
![image](https://user-images.githubusercontent.com/61522905/99383448-2ab7e180-28ce-11eb-87ab-1e6b901e4769.png)

BC is the last v17 container version.
Versione: IT Business Central 17.0 (piattaforma 17.0.17020.18841 + applicazione 17.0.17126.18865)

Thanks in advance

**Comment by dtkb** [comment]
You should probably show how you added that field, as it might be relevant to whatever is causing it to fail on the SQL side...

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by Serenissima1** [comment]
This is not how to Compile.
It have been compiled as well.
This is a bug on BC.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
