### ISSUE TITLE
Modify Rule AA0215

### ISSUE THREAD

**Issue by IceOnly** [microsoft/AL#6307]
Based on the Best Pratice Guide (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming), the suffix/prefix in the filename is not optional.

The open issue for the guide is not comment since three months (https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1361)

Guide or rule should be modified to match each other.

I would prefer to revert the guide to the old definition:
> \<ObjectNameExcludingPrefix\>.al

**Comment by dtkb** [comment]
It seems the documentation was updated to match the actual practice of VS Code, so isn't this resolved?

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming

> In your extension, the name of each new application object (table, page, codeunit), can contain a prefix or suffix.
>
> The CodeCop analyzer suggests that the object name is part of the file name, which is encouraged as a best practice. Adding any affixes to the file names is voluntary.

**Comment by IceOnly** [comment]
Yes, issue solved!
