### ISSUE TITLE
Custom Dynamics 365 CRM Integration in Business Central - AL Table proxy generator

### ISSUE THREAD

**Issue by AjayJangiti** [microsoft/AL#6309]
Hi Team,

When I tried to create a Custom Dynamics 365 CRM Integration in Business Central by using AL Table proxy generator I am ending up with the "System.UnauthorizedAccessException" error as shown in below. 

Please suggest incase if I am missing something.

![image](https://user-images.githubusercontent.com/74677496/99571185-f68d0f80-29f8-11eb-8a2c-2cc628496eeb.png)

**Comment by atoader** [comment]
Hi @AjayJangiti ! Can you provide instructions to reproduce this issue? Can you reproduce it on your machine and other machiens?

**Comment by AjayJangiti** [comment]
Hi @atoader ! Able to resolve the issue by executing the commands from VS Code by following below docs.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-table-proxy-generator.

Thanks a lot for your response.
