### ISSUE TITLE
Report OnOpenPage Trigger Executed Twice with Preview Option

### ISSUE THREAD

**Issue by eknraw** [microsoft/AL#6310]
**Describe the bug**
Set a breakpoint on any report that has an OnOpenPage trigger that has report output that can be "Previewed".  If selecting preview the OnOpenPage trigger will run before the Request Page is shown and again before output is shown.  

Added an example report to demonstrate.  
We set some variables to a default that are exposed on the Request Page.  For example "Hide Bill-to Address" on a document.  By default we'll set this to false but a user can set the variable and display the address.  If the "Preview" option is selected to view the report, the OnOpenPage() trigger is run AGAIN before preview output is displayed and when this happens the variable that was set on the Request Page = true is "initialized" back to false.  

**To Reproduce**
Steps and to reproduce the behavior:
1. Publish this report
2. Execute and set the fldGlobalBoolean = true on the request page
3. Preview Report, GlobalBoolean will be equal to false during preview execution. 

```
report 50100 OnOpenPageTriggerReport
{
    UsageCategory = Administration;
    ApplicationArea = All;
    DefaultLayout = RDLC;
    RDLCLayout = './src/Reports/OnOpenPageTriggerReport.rdl';
    Caption = 'OnOpenPageTriggerReport';

    requestpage
    {
        SaveValues = true;

        layout
        {
            area(Content)
            {
                group(GroupName)
                {
                    field(fldGlobalBoolean; GlobalBoolean)
                    {
                        ApplicationArea = All;
                    }
                }
            }
        }

        actions
        {
            area(processing)
            {
                action(ActionName)
                {
                    ApplicationArea = All;

                }
            }
        }

        trigger OnOpenPage();
        begin
            GlobalBoolean := false;
        end;

    }

    trigger OnPostReport()
    begin
        Message(Format(GlobalBoolean));
    end;

    var
        GlobalBoolean: Boolean;
}
```

**Expected behavior**
OnOpenPage should only run once before output is generated in preview.

**Screenshots**

**5. Versions:**

 - AL Language: 7.0.361779

 - Business Central:  US Business Central 18.0 (Platform 17.0.18466.0 + Application 18.0.19068.0)

**Comment by atoader** [comment]
Hi @eknraw ! Thank you for the good quality repository. As this mentions runtime behavior, I do not think it is the appropriate repository. Could you help me understand how this relates to the developer tools?

**Comment by eknraw** [comment]
None!  Sorry!

**Comment by jaumebarbosa** [comment]
Hi, Same problem
Have you solved it?
How not repeat OnOpenPage trigger after Preview?
Thankyou

**Comment by aengrand** [comment]
Hello there,

I had the same problem. To resolve this problem, remove the savevalues property in your request page.

Have a good day,
Alexis.

**Comment by RichardJ70** [comment]
The savevalues trick is not a solution. It is a work around. This is still a problem on platform 20. No real solution found so far.

**Comment by nikolajovicic** [comment]
With single instance codeunit we can run our code only in "first" OnOpenPage 
`trigger OnOpenPage()
begin
    if not SingleInstanceCu.GetOnOpenRequestPageAlreadyRun() then begin
        //Set default vaues and filters

        SingleInstanceSKCGPO.SetOnOpenRequestPageAlreadyRun(true);
    end;
end;`
