### ISSUE TITLE
Processing of message failed with error:

### ISSUE THREAD

**Issue by sonicadv27** [microsoft/AL#6312]
**Describe the bug**
An error message pops up on the terminal forcing a restart.

**To Reproduce**
Steps and to reproduce the behavior:
1. Use Vs Code normally
2. Wait for the error to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/46959764/99670069-dcd6e100-2a67-11eb-97da-401f0c501a0f.png)

**5. Versions:**
 - AL Language: 6.1.362735
 - Business Central: Any version but i'm currently on Platform 17.0.18539.0 + Application 17.2.18548.0

I must say this issue, like a bunch of others with AL Language, drives me absolutely crazy. After this message, any action i do on VS Code makes the terminal open again with the same message and i have to restart VS Code. In a lot of cases, the message pops right back up after the restart and eventually leave me alone.

**Comment by kalberes** [comment]
Do you have some Al code that reproduces the issue? On what symbol have you pressed go to definition?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
