### ISSUE TITLE
Auto-Format on save cannot be disabled

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6313]
**Describe the bug**
Whenever a .al-File in VSCode is saved, it is automatically formatted. This behavior is often failing due to performance issues and/or analyzers behaving badly. This renders it impossible to save the file to disk. VSCode has an option to auto-format files on save, but this option is disabled (it is by default). Yet, the AL extension ignores this setting.

**To Reproduce**
1. Check the "Format on save" setting. It should be disabled by default. If not, disable it.
1. Open a AL file and make some changes that required re-formatting.
2. Save the file.
3. Watch as the file is formatted.

``` AL Code to reproduce the issue ```

**Expected behavior**
The file should only be automatically formatted if configured.

**Screenshots**
/

**5. Versions:**

 - AL Language: 6.1.362735

 - Business Central: 17.1

**Comment by atoader** [comment]
Do you have any other extensions installed other than the AL Language extension?

**Comment by hemisphera** [comment]
I do. Lots. I have the following installed:

- AL Code Actions
- AL Object Designer
- AZ AL Dev Tools
- Azure Account
- Azure Pipelines
- C#
- GitHubSharp Theme
- GitLens
- Hex Editor
- Insert GUID
- Material Icon Theme
- OpenAPI
- PowerShell
- SQL Server
- CRS AL
- XML Tools
- YAML

I have tried to disable them all and reproduce it with only the AL extension installed. Does not change anything.

**Comment by hemisphera** [comment]
@atoader I can see the "input-needed" tag is still there. Do you need any more info?

**Comment by dannoe** [comment]
Try the following settings inside your user/workspace settings:
```json
    "[al]": {
        "editor.formatOnSave": false,
    }
```

**Comment by hemisphera** [comment]
@dannoe : Ok, sure. This works fine, thanks for the hint. Yet, I do think AL should respect the "global" setting.
