### ISSUE TITLE
Renaming event publisher method (with F2, etc.) does not update i.e. breaks event subscriber annotations

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#6315]
**Describe the bug**
The title says it all.

**To Reproduce**
1. Have an event publisher method
2. Have another method that subscribes to it, with no problems
3. Hover over the event publisher method name, press F2, and rename it to something else
4. See that the subscriber now generates an error, because its annotation refers to the old name of the publisher (between `''`)

**Expected behavior**
The name should also be updated, in any subscribers within the current workspace, just as any other method reference would be. It should not matter that the way of referring the name is different (being a `'text string'`, instead of an unquoted symbol).

**5. Versions:**
 - AL Language: 6.1.362735

**Comment by dtkb** [comment]
See also https://github.com/microsoft/AL/issues/5128
