### ISSUE TITLE
feature request: add RecordRef.SetAutoCalcFields(), like new RecordRef.SetLoadFields()

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6316]
Partial records just landed, and with that we can pass a list of field IDs to `RecordRef.SetLoadFields()` in order to dynamically load fields while also ensuring we don't pull out columns we don't care about.

Now would be a great time to add the long-missing equivalent for FlowFields, i.e. `RecordRef.SetAutoCalcFields()`. This would let us avoid having to do two SQL calls, one for the initial `Get()`/`FindFirst()` and one to actually bring over the FlowField, which is wasteful.

This seems to be an omission and would be good to bring up to parity between normal and flow fields. Thanks!

**Comment by kalberes** [comment]
@KennieNP

**Comment by PhDuck** [comment]
From a server perspective I don't think this would be very hard, but I don't know reason why it wasn't originally done.

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by db-bc** [comment]
=> https://experience.dynamics.com/ideas/idea/?ideaid=509a8214-a3ef-eb11-ba5e-0003ff45bd51
