### ISSUE TITLE
Debugger does not stop

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#632]
Just recently tried out the September version. However, the debugger does not stop at the break point of the simple Hello World.

![debugger error](https://user-images.githubusercontent.com/16351673/30158105-63943eba-93c4-11e7-85f1-88234c2a8b61.PNG)

**Comment by kalberes** [comment]
Just refresh the page. It should stop then. This a known issue with entry point methods like OnOpenPage where the server receives later the set of breakpoints than client session is started up.
