### ISSUE TITLE
Get last element in Json Array with JSON Path

### ISSUE THREAD

**Issue by mckasp** [microsoft/AL#6323]
- AL Extension Version: v6.1.362735

- Server Version: CH Business Central 17.0 (Platform 17.0.16974.0 + Application 17.0.16993.0)

I get the following JSON reponse:

{
    "Datensätze": [
        {
            "Status": 0,
            "Datum": "2020-11-23T00:00:00",
            "Sollzeit": 480,
            "Istzeit": 0,
            "Differenz": "-8:00",
            "Auftragszeit": 0,
            "Gleitzeit": 0,
            "Ferien": 6733,
            "Überzeit": 3202,
            "Ruhezeit": null,
            "Bemerkung": "",
            "Arbeitszeitregel": "Erstes Arbeitszeitmodell"
        },
        {
            "Status": 0,
            "Datum": "2020-11-24T00:00:00",
            "Sollzeit": 480,
            "Istzeit": 0,
            "Differenz": "-8:00",
            "Auftragszeit": 0,
            "Gleitzeit": 0,
            "Ferien": 6733,
            "Überzeit": 3202,
            "Ruhezeit": null,
            "Bemerkung": "",
            "Arbeitszeitregel": "Erstes Arbeitszeitmodell"
        },
        {
            "Status": 0,
            "Datum": "2020-11-25T00:00:00",
            "Sollzeit": 480,
            "Istzeit": 0,
            "Differenz": "-8:00",
            "Auftragszeit": 0,
            "Gleitzeit": 0,
            "Ferien": 6733,
            "Überzeit": 3202,
            "Ruhezeit": null,
            "Bemerkung": "",
            "Arbeitszeitregel": "Erstes Arbeitszeitmodell"
        }
    ]
}

Now I would like to access the last element in the array (record with date 2020-11-25) and read the property "Überzeit".

If I use the **QueryString := '$.Datensätze[(@.length-1)].Überzeit';** it does not work. I get the error message: "The requested operation cannot be performed in this context".

If I use **QueryString := '$.Datensätze[?(@.Datum==''2020-11-25T00:00:00'')].Überzeit';** I get the desired result "3202".

But I do not know the date of the last element beforehand, that's why I must be able just to select the last element in the array:

I tested the syntax in the JSON Path Online Evaluator and it worked.
https://jsonpath.com/

This is my AL code:

    internal procedure APITest(var Employee: Record Employee; request: JsonObject)
    var
        api: Codeunit API;
        QueryString: Text;
        token: JsonToken;
        response: JsonObject;
    begin
        request.Add('PersonalNr', Employee."No.");
        request.Add('Von', '2020-11-23');
        request.Add('Bis', '2020-11-25');

        api.PostTagessumme(request, response);

        **QueryString := '$.Datensätze[(@.length-1)].Überzeit';**                                            // this line does not work
        // QueryString := '$.Datensätze[?(@.Datum==''2020-11-25T00:00:00'')].Überzeit';     // this line works

        response.SelectToken(QueryString, token);
        if token.IsValue() then
             if not (token.AsValue().IsNull or token.AsValue().IsUndefined()) then
                 Message('Überzeit: %1', token.AsValue().AsDecimal());
    end;

Any help will be appreciated. Thanks.

**Comment by thpeder** [comment]
Hi,
The json implementation is using Newtonsoft.Json behind the scenes, and the limitation you hit is in that library.
https://github.com/JamesNK/Newtonsoft.Json/issues/1318

**Comment by mckasp** [comment]
Thank you thpeder! It worked!
