### ISSUE TITLE
EDM Type issue with Nullable definition

### ISSUE THREAD

**Issue by eclipses** [microsoft/AL#6328]
I've created an EDM definition with the following XML.
``` xml
<ComplexType Name="pcPurchaseLineType"><Property Name="skuCode" Type="Edm.String" Nullable="false"/><Property Name="qty" Type="Edm.Decimal" Nullable="false"/><Property Name="price" Type="Edm.Decimal" Nullable="true" /><Property Name="deliveryDate" Type="Edm.Date" Nullable="true" /><Property Name="notes" Type="Edm.String" Nullable="true" MaxLength="100" /></ComplexType>
```

I included this type inside an API page as a collection.

```
field(lines; PurchaseLinesJson) 
{
    ODataEDMType = 'Collection(PC.PURCHASE-LINE)';
    Caption = 'lines', Locked = true;
}
```
This works, however, if one of the 'Nullable=true' fields is not present in the JSON, we get the following error.
```
{
    "error": {
        "code": "Unknown",
        "message": "Unable to convert from Microsoft.Dynamics.Nav.Runtime.NavJsonValue to Microsoft.Dynamics.Nav.Runtime.Decimal18.  CorrelationId:  eb588b1d-b007-4dc5-8a7b-12011d403bf6."
    }
}

```
Example request below:
``` json
{
    "type": "1",
    "parentId": "BPO-05",
    "lines": [
        {
            "skuCode": "1000",
            "qty": 1
        },
        {
            "skuCode": "1001",
            "qty": 2
        }
    ]
}

```
Working with the latest BC on-Premise GB localized.

**Comment by ajkauffmann** [comment]
Just asking, why don't you use a nested API page? The latest version has improved support for that.

**Comment by axiaqbenjamin** [comment]
Hi @ajkauffmann,

Let's say that in this case, we need to first do some logic with the lines, then, after the lines are processed, we need to do something with the parent. Is there a way to retrieve the lines on insert of the parent, like you can do with edm types by parsing the JSON?.

Also, I am eager to see what the latest version has improved in this regard. Can you point me to any documentation about this?

Many thanks.

**Comment by eclipses** [comment]
Hi @ajkauffmann,

For the particular task we need to process lines before and the header, tried this morning a different approach inserting in temporary tables but after inserting the lines I did not find any trigger/event to use for our purpose. An event, in this case, could be a workaround.

EDM Types would give us the correct flexibility if would work properly with Nullable.

**Comment by thpeder** [comment]
This looks like a runtime issue so let's get it to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by eclipses** [comment]
Hi @thpeder 

I've opened a support request in Collaborate, here the ID 2012020040001796, please help to prioritize it.
