### ISSUE TITLE
Combine Enum table field with a lookup

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6335]
Given: 
- **Enum E**.
- **Table A** with PK solely consisting of a field of type Enum E.
- **Table B** has a (non-key) **field B** also of type Enum E.

**Idea: In table B, let the user not choose from the drop down list of all possible enum E values, but only from values used in table A., using a lookup.**

But: 
- As soon as you enter a TableRelation on field B (to table A), the page field is not editable anymore. 
- You neither can choose a value from a drop down or lookup.
![image](https://user-images.githubusercontent.com/34504100/100759942-8071ab00-33f1-11eb-84a8-ef13fe93852c.png)
- If you do not specify a table relation but an OnLookup trigger, the trigger will be simply ignored.

**Apparently, using enum values as a table lookup is not supported**. If that observation is correct (please confirm):
1. Please add the restriction to the documentation
2. Please add a rule to forbid the TableRelation property and OnLookup trigger on enum table fields.

**Versions:**

 - AL Language: 6.1.36735

 - Business Central: 16.0

**Comment by NKarolak** [comment]
*bump*

**Comment by atoader** [comment]
Thanks! We'll take a look at this to see if it is a bug.

**Comment by atoader** [comment]
@NKarolak does this issue happen if you replace the enums with options? 
Can you provide a sample project for enums and one for options?

**Comment by NKarolak** [comment]
It works neither for option values.

Sample project:
[6335.zip](https://github.com/microsoft/AL/files/5849257/6335.zip)

How to test:
1. Open (always from TellMe) TableA_Enum and enter at least one record with MyEnum set to 1, 2 or 3.
2. Open TableA_Option and enter at least one record.
3. Open TableB  and enter a new record (Integer = 1).
4.  Now, try to lookup values in fields NewEnum and NewOpt: it does not work, see initial post. I would expect to see the values you have entered in step 1 and 2.

**Comment by atoader** [comment]
cc: @esbenk

**Comment by atoader** [comment]
We discussed this internally and considering the scope of the work we recommend that you go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there.

**Comment by NKarolak** [comment]
Done:
https://experience.dynamics.com/ideas/idea/?ideaid=402f75de-1bac-eb11-89ee-0003ff45b7ac

@atoader
Since you don't want to change the behavior short notice, please consider updating the documentation accordingly.

> 1. Please add the restriction to the documentation
> 2. Please add a rule to forbid the TableRelation property and OnLookup trigger on enum table fields.

**Comment by jcallaghan-sysco** [comment]
@NKarolak Did you find a workaround for this? It seems to still be an issue in the latest versions of BC and AL.

**Comment by NKarolak** [comment]
@jcallaghan-sysco 
I'd only redesigned my solution to not need a lookup on enum values, and I didn't need it ever again since 🤷
My solution is now based on codes.

Please try to get your colleagues to vote for [https://experience.dynamics.com/ideas/idea/?ideaid=402f75de-1bac-eb11-89ee-0003ff45b7ac](https://experience.dynamics.com/ideas/idea/?ideaid=402f75de-1bac-eb11-89ee-0003ff45b7ac) to make this ever implemented by Microsoft.

If you are on Yammer, you could promote my post there by adding an answer to it:
[https://www.yammer.com/dynamicsnavdev/threads/1193690290593792](https://www.yammer.com/dynamicsnavdev/threads/1193690290593792)
