### ISSUE TITLE
Conversion of JSONToken to JSONArray not possible

### ISSUE THREAD

**Issue by mckasp** [microsoft/AL#6340]
**Describe the bug**
I get a JSONToken back from a function call then I would like to convert it into a JSONArray and iterate over the elements with foreach. However everytime the compiler hits the line

foreach Antrag in resultJson.AsArray() do begin

then I get the error

Conversion of Microsoft.Dynamics.Nav.Runtime.NavJsonToken to Microsoft.Dynamics.Nav.Runtime.NavJsonArray is not possible (see screenshot below in German)

**To Reproduce**
    
internal procedure PostAntrag(body: JsonObject; var response: JsonArray)
    var
        resultJson: JsonToken;
        Antrag: JsonToken;
    begin
        SendPost(GetApiUrl('Antrag'), body.AsToken(), resultJson);
        foreach Antrag in resultJson.AsArray() do begin
            response.Add(Antrag);
        end;
    end;

I also tried with:

myJsonArray := myJsonToken.AsArray();

I get the same error.

**Expected behavior**
It should be possible to convert a JSONToken into a JSONArray

**Screenshots**
![ConversionError](https://user-images.githubusercontent.com/28837885/101148465-f195a600-361d-11eb-95cc-9034c38a4504.jpg)

**Versions:**
 - AL Language: v6.1.362735
 - Business Central: CH Business Central 17.0 (Platform 17.0.16974.0 + Application 17.0.16993.0)

**Comment by dtkb** [comment]
What is an example fragment of JSON that causes the error? Is the received JSON definitely OK?

**Comment by mckasp** [comment]
The content of resultJson is like this and contains two elements:

{"Datensätze":[{"Von":"2021-01-04T00:00:00","Bis":"2021-01-08T00:00:00","Antragsart":"Ferienantrag","Buchungsart":"Abwesend Ferien (22)","Status":0},{"Von":"2020-12-21T00:00:00","Bis":"2020-12-31T00:00:00","Antragsart":"Ferienantrag","Buchungsart":"Abwesend Ferien (22)","Status":2}]}

**Comment by dtkb** [comment]
Do you perhaps need to select the `Datensätze` token and convert _that_ to an array?

**Comment by mckasp** [comment]
Hi dtkb,

You are absolutely right. I needed to select the `Datensätze` token first and convert that to an array.

```
response.SelectToken('$.Datensätze', responseToken);
responseArray := responseToken.AsArray();
```
Thank you so much.

**Comment by alexiskoileken** [comment]
JSON tokens of type 'Array' are not supported by this implementation. i also get that error
