### ISSUE TITLE
Personalization does not work correctly when all actions in a group are not visible by default

### ISSUE THREAD

**Issue by RowaldNieswaag** [microsoft/AL#6341]
**Describe the bug**
When an actiongroup is added to a page, and all actions have the visible property set to false by default, the personalization does not work correctly. The 'Show' action is not available.

**To Reproduce**
Add an action group to a page and set the visibilty property to false for all actions. Publish the extension, navigate to the page in the webclient and personalize the page. Try to set the hidden action to 'Show'.

If a single action in the group is made visible by default, the personalization does work correctly for **all** the hidden actions in the group (ie. the 'Show' option is available).

``` AL Code to reproduce the issue ```
```
pageextension 50000 "My Customer Card" extends "Customer Card"
{
    actions
    {
        addlast(processing)
        {
            group("My Action Group")
            {
                action("Action 1")
                {
                    Caption = 'Action 1';
                    ToolTip = 'Executes Action 1';
                    ApplicationArea = All;
                    Image = Account;
                    Visible = false;

                    trigger OnAction()
                    begin
                        Message('Action 1');
                    end;
                }
                action("Action 2")
                {
                    Caption = 'Action 2';
                    ToolTip = 'Executes Action 2';
                    ApplicationArea = All;
                    Image = AccountingPeriods;
                    Visible = false;

                    trigger OnAction()
                    begin
                        Message('Action 2');
                    end;
                }
                action("Action 3")
                {
                    Caption = 'Action 3';
                    ToolTip = 'Executes Action 3';
                    ApplicationArea = All;
                    Image = Accounts;
                    Visible = false;

                    trigger OnAction()
                    begin
                        Message('Action 3');
                    end;
                }
            }
        }
    }
}
```
**Expected behavior**
The 'Show' action should be available as a valid action.

**Screenshots**
![Customer Card - Dynamics 365 Business Central](https://user-images.githubusercontent.com/75486312/101176022-32a1b080-3646-11eb-8345-8dffa2510bdd.png)

**5. Versions:**
 - AL Language: 6.1.36735
 - Business Central: BC container (artifacturl = https://bcartifacts.azureedge.net/onprem/17.1.18256.18792/nl)

**Comment by qutreson** [comment]
I can reproduce the issue and it seems that it can be mitigated by first using 'Show' on the action group 'My Action Group'. 
After this is had been done, it is now possible to also 'Show' the actions it contains.

![image](https://user-images.githubusercontent.com/31541422/101761807-e2f73500-3adc-11eb-9016-4a5aec3aa0f2.png)

Before showing the action group:
![image](https://user-images.githubusercontent.com/31541422/101761776-d8d53680-3adc-11eb-9247-344443013f67.png)

After showing the action group:
![image](https://user-images.githubusercontent.com/31541422/101761836-ec809d00-3adc-11eb-8495-6744b58102a8.png)

We will investigate this further.

**Comment by qutreson** [comment]
This appears to be an issue in the web client and is not directly related to the AL compiler or the developer tools in the scope of this repository.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by RowaldNieswaag** [comment]
Thank you for the response.

There seems to be another issue when all actions are promoted in a custom PromotedActionCategory. When clicking on the group, no options are show when personalizing the page.
See attachment for reproduction.

[cid:image002.png@01D6CEEC.85AA9100]

Hope this helps you in your investigation.

Met vriendelijke groet,

[Logo]

Rowald Nieswaag
M +31 6 82 85 91 03

Van: qutreson <notifications@github.com>
Verzonden: donderdag 10 december 2020 11:45
Aan: microsoft/AL <AL@noreply.github.com>
CC: Rowald Nieswaag <rnieswaag@mysolution.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/AL] Personalization does not work correctly when all actions in a group are not visible by default (#6341)


I can reproduce the issue and it seems that it can be mitigated by first using 'Show' on the action group 'My Action Group'.
After this is had been done, it is now possible to also 'Show' the actions it contains.

[image]<https://user-images.githubusercontent.com/31541422/101761807-e2f73500-3adc-11eb-9016-4a5aec3aa0f2.png>

Before showing the action group:
[image]<https://user-images.githubusercontent.com/31541422/101761776-d8d53680-3adc-11eb-9247-344443013f67.png>

After showing the action group:
[image]<https://user-images.githubusercontent.com/31541422/101761836-ec809d00-3adc-11eb-8495-6744b58102a8.png>

We will investigate this further.
