### ISSUE TITLE
The error text created by a TestField adds an extra space character behind the expected value.

### ISSUE THREAD

**Issue by mhenricus** [microsoft/AL#6346]
**Describe the bug**
I don't know if it is a (recent) bug, of if it is by design or has been in the system for a long time. 
When creating a negative test I found the following.

**To Reproduce**
Steps and to reproduce the behavior:
Create a test function with the code below:

    procedure TestFieldSpace()
    var
        Vendor: Record Vendor;
        LibraryPurchase: Codeunit "Library - Purchase";
    begin
        LibraryPurchase.CreateVendor(Vendor);
        asserterror Vendor.TestField("Prices Including VAT", true);
        LibraryAssertG.ExpectedError(StrSubstNo('Prices Including VAT must be equal to ''Yes''  in Vendor: No.=%1. Current value is ''No''.', Vendor."No."));
    end;

**Expected behavior**
As seen above, the expected error text is:
StrSubstNo('Prices Including VAT must be equal to ''Yes''  in Vendor: No.=%1. Current value is ''No''.', Vendor."No.")

I'd expected:
StrSubstNo('Prices Including VAT must be equal to ''Yes'' in Vendor: No.=%1. Current value is ''No''.', Vendor."No.")

The difference is just on space less after ''Yes''. 
Note, It seems that GitHub hides the second space. Look at the AL code and you will see 2 spaces.

**Screenshots**

**5. Versions:**

 - AL Language: v7.0.341259

 - Business Central: Version: W1 17.0 (Platform 17.0.17020.18681 + Application 17.0.17126.18712)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
