### ISSUE TITLE
Rule AA0232 for Enums

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6348]
**Describe the bug**
The rule AA0232 

> The FlowField "My Enum" of "My New Table" should be added to the SIFT key.

 is raised on Enum fields although they cannot be created as SIFT key.

**To Reproduce**
Enable the CodeCop in the settings.json
```AL
"al.enableCodeAnalysis": true,
"al.backgroundCodeAnalysis": true,
"al.codeAnalyzers": ["${CodeCop}"]
```

New Enum

```AL
enum 50100 "My Enum"
{
    value(0; Open)  { Caption = 'Open'; }
    value(1; Closed) { Caption = 'Closed'; }
}
```

New Table 1
```AL
table 50101 "My Table 1"
{
    Caption = 'My New Table';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "My PK"; Integer)
        {
            Caption = '';
            DataClassification = CustomerContent;
        }
        field(2; "My Enum"; Enum "My Enum")
        {
            Caption = 'My Enum';
            DataClassification = CustomerContent;
        }
    }
    keys
    {
        key(PK; "My PK")
        {
            Clustered = true;
        }
        key(MyEnum; "My Enum") { }
    }
}
```

New Table 2 with AA0232
```aL
table 50102 "My Table 2"
{
    Caption = 'My Table 2';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "My PK"; Integer)
        {
            Caption = 'My PK';
            DataClassification = CustomerContent;
        }
        field(2; "FlowField on Enum"; Enum "My Enum") // AA0232
        {
            Caption = 'FlowField on Enum';
            CalcFormula = min("My Table 1"."My Enum");
            Editable = false;
            FieldClass = FlowField;
        }
    }
    keys
    {
        key(PK; "My PK")
        {
            Clustered = true;
        }
    }
}
```

You cannot add the Enum field as SumIndexField in table 1:
```AL
 key(PK; "My PK")
        {
            Clustered = true;
            SumIndexFields = "My Enum" // AL0199
        }
```
This would raise AL0199:

> The type of the sum index field '"My Enum"' must be numeric(Decimal, BigInteger, Integer, or Duration) 

which is weird since Enums are numeric.

**Expected behavior**
Either the warning AA0232 shall not appear, or it must be possible to use Enums as SumIndexFields.

**Versions:**
 - AL Language: 6.1.362735

**Comment by NKarolak** [comment]
When do you think this might get corrected?

**Comment by atoader** [comment]
@PaulIvan can you provide an ETA?

**Comment by NKarolak** [comment]
Still no update :-(

**Comment by PaulIvan** [comment]
Hi @NKarolak I agree this looks a bit weird but just because something is possible doesn't mean it should be used.

I'm just a bit confused as to why a lookup flowfield wouldn't be better in this case?

**Comment by dtkb** [comment]
I guess the example code is deliberately oversimplified, to the point of being nonsensical in practice, but it demonstrates the issue in theory.

That said, it seems brittle to rely on the numeric values of enums or options, and I never like it when I find code that does that.

Did this work with options? If not, I guess it was never intended to work.

**Comment by NKarolak** [comment]
@dtkb
In reality, my enum flow field is a "Print Status" (1 = Open; ... 10 = Error; 20 = Printed) on a header record. It returns the minimum Print Status value from all related line records. Hence: only if all lines are printed (without errors), then the header record is displayed as printed.

**Comment by NKarolak** [comment]
@PaulIvan Can you give an ETA?

**Comment by NKarolak** [comment]
@qutreson *push* ;-)

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

Going forward we will not track progress on CodeCop issues here on GitHub. Hence, we are closing this issue.

**Comment by amodaresi-archerpoint-com** [comment]
@mazhelez 

> Going forward we will not track progress on CodeCop issues here on GitHub. Hence, we are closing this issue.

Where do you track progress on CodeCop instead then ?
