### ISSUE TITLE
Analyzer AD0001 'Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions'

### ISSUE THREAD

**Issue by MS-net** [microsoft/AL#6352]
**Describe the bug**
When resolving the new codecop warnings in AL Language 6.1.x, this warning was displayed. Ignoring, resolving, or leaving warnings for rule 218 doesn't seem to make any difference.

`Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.MethodDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationBaseSyntax'.
   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.ExtractCountOfOptions(ISymbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Localizability\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 318
   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzeCaptions(SymbolAnalysisContext symbolAnalysisContext, SyntaxNode node, IdentifierNameSyntax identifierName, ISymbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Localizability\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 298
   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzePageFields(SymbolAnalysisContext symbolAnalysisContext, ImmutableArray`1 controlSymbols, PageTypeKind pageTypeKind) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Localizability\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 76
   at Microsoft.Dynamics.Nav.CodeCop.Localizability.Rule218TooltipMustBeFilledOnPageForFieldsAndActions.AnalyzePage(SymbolAnalysisContext symbolAnalysisContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Localizability\Rule218TooltipMustBeFilledOnPageForFieldsAndActions.cs:line 66
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 656
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1100'`

**To Reproduce**
Steps and to reproduce the behavior:
1. Open existing project while AL Language 6.1.x is installed
2. activate codeanalyzers
3. warning appears

**Expected behavior**
No warning or a warning which points to a solvable issue.

**5. Versions:**
 - AL Language: 6.1.362735
 - Business Central: 17.1.18256.19616-W1

**Comment by SHermann73** [comment]
Is there a way to get further debug information regarding exceptions in case the CodeCop crashes?
If we could get the information which .al file or even better which line is causing the exception, we could try to find a way around it on our own.
As this error seems to get trigger by a complete other code change, which is unsuspicious and has no connection to Tooltips, it's not directly the last change which is the real cause of the exception.

**Comment by MS-net** [comment]
Could we get an update on the current state of the error or plans for solving it?

**Comment by atoader** [comment]
@PaulIvan can you follow up?

**Comment by SHermann73** [comment]
@atoader @PaulIvan 
Hi all. Any news reagarding this?
An updated would still be highly appreciated.

**Comment by LNitzsche** [comment]
I also get from time to time an error like this.
I am using AL Language Extension 7.1.441.584.
Switching to 6.6.434101 reduces the number of errors, but it still remains faulty.
The package can always be created, but I fear that the Codecop stops with this error and will not detect any real errors which should have been detected.

{
	"resource": "/d:/Work/DevOps/VAPS-BCv18/MainApp/app.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RulePublicAPIBreakingChangesNotAllowed' threw an exception of type 'System.ArgumentException' with message 'System.ArgumentException: An item with the same key has already been added. Key: 1507148336\r\n   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\r\n   at Microsoft.Dynamics.Nav.AppSourceCop.Helper.ProcedureVerificationHelper.MatchFunctions(IEnumerable`1 newMethods, IEnumerable`1 oldMethods, PooledDictionary`2 unmatchedNewMethods, PooledDictionary`2 unmatchedOldMethods, PooledList`1 matchedMethodPairs) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.AppSourceCop\\Helper\\ProcedureVerificationHelper.cs:line 66\r\n   at Microsoft.Dynamics.Nav.AppSourceCop.Helper.ProcedureVerificationHelper.MatchFunctions(IEnumerable`1 newMethods, IEnumerable`1 oldMethods, PooledList`1 unmatchedNewMethods, PooledList`1 unmatchedOldMethods, PooledList`1 matchedMethodPairs) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.AppSourceCop\\Helper\\ProcedureVerificationHelper.cs:line 45\r\n   at Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RulePublicAPIBreakingChangesNotAllowed.CompareApplicationObjects(SymbolAnalysisContext ctx, ITypeSymbol oldObject, ITypeSymbol newObject) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.AppSourceCop\\Upgrade\\RulePublicAPIBreakingChangesNotAllowed.cs:line 86\r\n   at Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RulePublicAPIBreakingChangesNotAllowed.AnalyzeModule(SymbolAnalysisContext ctx) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.AppSourceCop\\Upgrade\\RulePublicAPIBreakingChangesNotAllowed.cs:line 55\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 656\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1100'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

**Comment by atoader** [comment]
@LNitzsche please open another issue and provide a project that reproduces the issue. Your issue is triggered by a rule in AppSOurceCop not in CodeCop

**Comment by PaulIvan** [comment]
@MS-net Please try again with the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds).
Verify that it still triggers the error.
If it does please attach a code example that triggers it and the error itself.

**Comment by SHermann73** [comment]
@PaulIvan 
Hi Paul
Thanks for the feedback.
Unfortunately it looks like the error still persist.
Finally I could hunt this down to the following code example:

`Test
test
test`

**Comment by SHermann73** [comment]
Hi @atoader, @PaulIvan 
I would like to kindly ask if this issue will someday going to be fixed?
Currently it's still open and I still get the error.
The above provided code can still be used to reproduce.

Tested now with
AL Language v8.4.586670

Thanks in advance

**Comment by SHermann73** [comment]
Hi @kalberes 
Maybe you can give some more insights on this?

Thanks in advance

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

**Comment by SHermann73** [comment]
Hi @mazhelez 
Thanks for the update.
I would prefer if you could keep this issue open and include it in your overhaul rather than just closing it.
By closing it, it's just going to be forgotten.

**Comment by mazhelez** [comment]
@SHermann73 do not worry about that. I have created an internal work item to track the issue.

However, since CodeCop-related work is yet to be planned, we want to set the right expectations. Namely, as we are focusing elsewhere, so we cannot promise a fix soon.
