### ISSUE TITLE
[Parameter Request] Add CloseAction parameter to OnQueryClosePageEvent

### ISSUE THREAD

**Issue by j2associates** [microsoft/AL#6354]
The page trigger OnQueryClosePage exposes a CloseAction parameter. This allows code to only process when the CloseAction = Action::OK.

The integration event OnQueryClosePageEvent does NOT expose the CloseAction so a codeunit subscribing to that event cannot tell if the page was being canceled or not. Obviously, most of the time you don't want any code to run if the page is being canceled.

The kludgy work around is to do a PageExtension for a given page and trap trigger OnQueryClosePage and then call an event subscriber codeunit procedure to set it up. It would then available to the codeunit when the OnQueryClosePage is subscribed.

A cleaner and simpler solution is to expose the CloseAction in the integration event OnQueryClosePageEvent. Then a subscriber codeunit could directly determine whether or not its code should run.

**Comment by thpeder** [comment]
Thanks for providing feedback, we are aware of the request before from Microsoft Idea - [Pass CloseAction as parameter in OnQueryClosePageEvent](https://experience.dynamics.com/ideas/idea/?ideaid=aed9f089-e4e6-ea11-bf21-0003ff68cd76)

**Comment by robertbacu** [comment]
Hi team, I'd like to reopen this issue since at this stage I am looking for that CloseAction and I don't see it introduced.
I think it would be a great idea, it is useful and I don't see why we should go around with alternatives, unless you know a really straightforward one?

**Comment by dnpb** [comment]
It's still a platform request, not really an AL one, and MS probably think the Idea suffices as a place to record it and gauge interest.

**Comment by robertbacu** [comment]
@dnpb even so, it's not consistent if you use the trigger inside the page you have the parameter, if you use the event subscriber you don't have it. Even from that point of view it has to be implemented.

**Comment by dnpb** [comment]
I don't disagree. That doesn't mean it's necessarily on topic though. Anyway, just my PoV, let's see what they say.
