### ISSUE TITLE
BC Application Bug in Item Tracking GetVariables()

### ISSUE THREAD

**Issue by amandajb27** [microsoft/AL#6355]
In Item Tracking Lines page, trying to use GetVariables; however, there is an invalid array in SourceQuantityArray.  Global is set at 5 and local is set at 3 so it will error in copyarray method.  

**To Reproduce**
Create a page extension and procedure to call GetVariables in Item Tracking Lines Page.  

``` AL Code to reproduce the issue ```
GetVariables(TempItemTrackLineInsert, TempTrackingSpecModify, TempTrackingSpecDelete, Item, UndefinedQtyArray, SourceQuantityArray, CurrentSignFactor, InsertIsBlocked, DeleteIsBlocked, BlockCommit)

![CopyArrayError](https://user-images.githubusercontent.com/60188122/101488427-d5934c80-391c-11eb-886c-59d8df5c84c0.PNG)
**5. Versions:**
 - Business Central 16

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
