### ISSUE TITLE
Inserting the UserId method from intellisense is missing parenthesis

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6356]
**Describe the bug**
Unlike system methogs in general, the `UserId` method chosen from intellisense does not automatically insert the method parenthesis.

**To Reproduce**
Enter `User` and choose entry `UserId` from intellisense:
![image](https://user-images.githubusercontent.com/34504100/101492277-08f9c980-3965-11eb-9682-08d50f6f18c6.png)
The inserted value will be `UserId`

Repeat with UpperCase: the inserted value will be
`UpperCase()`

**Expected behavior**
Insert `UserId()` instead of `UserId`

**Versions:**
 - AL Language: 6.1.362735

**Comment by dtkb** [comment]
The same goes for `.RecordId` on record variables. I don't know if that needs its own issue.
