### ISSUE TITLE
TextBuilder.RegExReplace and TextBuilder.RegExMatch

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#636]
Thanks for creating the TextBuilder!

Is it possible to add:
- RegExReplace
- RegExMatch

![image](https://user-images.githubusercontent.com/28626283/30159020-821dd032-93c7-11e7-96a5-05c6ee445f09.png)

**Comment by vjekob** [comment]
+1

Also: Having more comprehensive RegEx functionality would also be welcome through RegEx API.

**Comment by Gallimathias** [comment]
I'll link to #266 ;)

**Comment by StanislawStempin** [comment]
It's on our backlog

**Comment by kalberes** [comment]
Should be part of the system.app
https://github.com/microsoft/BCApps/tree/main/src/System%20Application/App/Regex/src
