### ISSUE TITLE
Missing intellisense in report objects

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6361]
**Describe the bug**
Several report object properties do not offer or no complete intellisense. These are the ones I've encountered so far, but there are probably more:

- WordMergeDataItem: Should suggest the top-level DataItem name.
- DataItemTableView: after `= sorting()`, we cannot select a field from a field list between the `()`
Actually, after choosing "sorting" from intellisense, the `()` could be added automatically as well.
- DataItemLinkReference: we cannot choose from existing DataItem names.

**Versions:**

 - AL Language: 6.1.381323

**Comment by nndobrev** [comment]
We will add this to our queue for future fixes. :)

**Comment by Jose-agg** [comment]
Thank you for your question, @NKarolak. I am currently looking into this issue with the following code to reproduce the problem:
  ```
report 50101 MyReport
  {
      dataset
      {
          dataitem(Customer_DataItem; Customer)
          {
              DataItemLinkReference = // We don't have an ancestor item to suggest
  
              dataitem("Customer Bank Account"; "Customer Bank Account")
              {
                  DataItemLinkReference = // We suggest the parent "Customer_DataItem" as a value
  
                  dataitem("Customer Amount"; "Customer Amount")
                  {
                      DataItemLinkReference = // We suggest both ancestors: "Customer_DataItem" and "Customer Bank Account"
                  }
              }
          }
  
          dataitem(DataItemName; Item)
          {
              DataItemLinkReference = // We don't have an ancestor item to suggest
          }
      }
  }
```

Whenever I use the "DataItemLinkReference" property, the suggestions provided by VSC extension are the ones I listed in my comments, so I would like to know what specific scenario you have encountered where the suggestions are not displayed correctly.

**Comment by dnpb** [comment]
For me, `DataItemLinkReference` *mostly* works, but if you accept a suggested referenced data item, which has spaces in its name... it fails to quote it, leading to this syntax error:

![image](https://user-images.githubusercontent.com/63455896/135866203-5e2b935b-9dd6-4556-b1f3-defdaad10bab.png)

To confirm, the prior 2 points are still valid (i.e. not suggested) for me.

I'm using:

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.1.525271
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by NKarolak** [comment]
Hi @Jose-agg , since my issue is already 10 months old, the language has obviously evolved ;-)
Your code comments exactly describe the behaviour that I had expected. But 10 months ago, it seems there was never a suggestion at all. I cannot remember ;-)
