### ISSUE TITLE
When using a boolean to set visibilities on a page field, this only works for the first record you open, the second record is still visible/invisible based on the previous value

### ISSUE THREAD

**Issue by midego1** [microsoft/AL#6362]
**Describe the bug**
When using a boolean to set visibilities op a page field, this only works for the first record you open, the second record is still visible/invisible based on the previous value

**To Reproduce**

If the first letter of a project starts with the G, the visibility of the 2 fields should be set to true.
This works for the first record with a G that I open. If I open another record where the No. starts with another letter the visibility is set to false but still shows the fields.

``` AL Code to reproduce the issue ```

    trigger OnOpenPage()
    begin
        ActivateFields;
    end;

    local procedure ActivateFields()
    begin
        FirstLetterProjectNo := Text.CopyStr("No.", 1, 1);
        if FirstLetterProjectNo = 'G' then
            FirstLetterGBoolean := true
        else
            FirstLetterGBoolean := false;
    end;

Also tried this in the ``` OnAfterGetRecord() ```

**Expected behavior**
Make the fields (in)visible based on the current value and not the first value.
As seen on the screenshot below I first opened a project that starts with G, after that, I opened a project that starts with F, I expect the 2 fields ("Gekoppeld project" and "Project omschrijving") to be invisible now.

**Screenshots**
![chrome_EcnWFKcrhe](https://user-images.githubusercontent.com/61051030/101635340-204eba80-3a2a-11eb-854f-0d344975df69.png)

**5. Versions:**
 - AL Language: v6.1.381323
 - Business Central: v. 16.0.11240.12076

**Comment by dtkb** [comment]
You need to update the boolean in `OnAfterGetRecord()`, so that it is set for every record... you are only currently doing it for the first one in `OnOpenPage()`, so of course that'll happen! This is not new, rather ancient behaviour.

Also, on a Card, you'll need to put those fields in a Group and set Visible on it, not on the fields directly - not that we can see whatever you're currently doing.

**Comment by midego1** [comment]
@dtkb I also tried the OnAfterGetRecord(), same issue.

**Comment by dtkb** [comment]
You probably need to show a minimal complete example for MS to be able to diagnose it

**Comment by midego1** [comment]
> You probably need to show a minimal complete example for MS to be able to diagnose it

What is incomplete?

**Comment by dtkb** [comment]
You don't show nearly any of the page definition, e.g. what table it's on, how the fields are declared, how their visibility is controlled, etc.

Doing that in `OnOpenPage()` definitely seems wrong to me. If it still doesn't work after setting the boolean in `OnAfterGetRecord()` (or `OnAfterGetCurrRecord()`, but that shouldn't be needed), then something subtle is wrong, and people need info to figure it out.

**Comment by midego1** [comment]
field("Project Description"; "Project Description")
            {
                ApplicationArea = all;
                Visible = FirstLetterGBoolean;

**Comment by jthoerner-tso** [comment]
Hello,

have you tried to set the InDataSet attributes? 
Normally it should work with the attribute.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-indataset-attribute

**Comment by NKarolak** [comment]
Dynamic visibility does not work directly on page fields. You need to put the field in question into a new field group and assign the Visible property to the group instead.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-visible-property#dynamic-visibility-of-controls

![image](https://user-images.githubusercontent.com/34504100/101648320-fb624380-3a39-11eb-87f3-a6284fa21dda.png)

**Comment by midego1** [comment]
Cheers @jthoerner-tso and @NKarolak I will try this soon!

**Comment by dtkb** [comment]
I said that already too...

> Also, on a Card, you'll need to put those fields in a Group and set Visible on it, not on the fields directly - not that we can see whatever you're currently doing.

**Comment by midego1** [comment]
> I said that already too...
> 
> > Also, on a Card, you'll need to put those fields in a Group and set Visible on it, not on the fields directly - not that we can see whatever you're currently doing.

Please be salty somewhere else.

**Comment by dtkb** [comment]
Sorry, I didn't remember that, so deleted my silly comment.

**Comment by atoader** [comment]
Closing the issue as it seems a resolution was found within the community. The issue was outside of the scope of this repository.
