### ISSUE TITLE
'All' action in filterpane removes filters in all filtergroups

### ISSUE THREAD

**Issue by RowaldNieswaag** [microsoft/AL#6363]
**Describe the bug**
Pressing the 'All' action (ie: remove user filters) in the filterpane on a listpage also removes filters set in **all** filtergroups.

We have a solution where we and our customers have to comply with privacy legislation, and this behavior far from acceptable.

**To Reproduce**
Set filters on a record in filtergroup 2 and run a listpage with the record as an argument.
The first time the page is opened the filters are applied and not visible in the filterpane.
Now show the filterpane and click 'All'.
All records in the source table are now shown.

``` AL Code to reproduce the issue ```
```
                trigger OnAction()
                var
                    Cust: Record Customer;
                begin
                    Cust.FilterGroup(2);
                    Cust.SetRange("Country/Region Code", 'NL');
                    Cust.FilterGroup(0);
                    Page.Run(Page::"Customer List", Cust);
                end;
```
**Expected behavior**
Filters set in filtergroups other then 0, should never be removed.

**Screenshots**
Initial filters when opening the page:
![Filtergroup-1](https://user-images.githubusercontent.com/75486312/101653723-eee0e980-3a3f-11eb-9c46-622a64af36c7.png)

Remove filters with 'All':
![Filtergroup-2](https://user-images.githubusercontent.com/75486312/101655166-9579ba00-3a41-11eb-9edc-14a9aace5006.png)

**5. Versions:**
 - AL Language: AL Language: 6.1.36735
 - Business Central: Business Central: BC container (artifacturl = https://bcartifacts.azureedge.net/onprem/17.1.18256.18792/nl)

**Comment by thpeder** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
