### ISSUE TITLE
Many methods/property accessors on RecordRef do not autocomplete with, or warn about, parentheses

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6365]
Shouldn't all methods require parentheses, and thus (a) include them when auto-completing from Intellisense and (b) warn about them if omitted (e.g. from manually written or migrated code)?

Many of them on `RecordRef` type do not; the below is not necessarily exhaustive, as I got bored, but illustrates my point well.

![image](https://user-images.githubusercontent.com/63455896/101797966-7bec7700-3b02-11eb-92f0-739e87c275aa.png)

**Comment by dtkb** [comment]
See also
https://github.com/microsoft/AL/issues/6356
https://github.com/microsoft/AL/issues/6357
https://github.com/microsoft/AL/issues/6365
(etc.?)

**Comment by dnpb** [comment]
apparently intentional: https://github.com/microsoft/AL/issues/6908#issuecomment-1028644117
