### ISSUE TITLE
Parenthesis and IsEmpty(), Count(), IsTemporary(), ...

### ISSUE THREAD

**Issue by IceOnly** [microsoft/AL#6366]
**Describe the bug**
IsEmpty(), Count() and IsTemporary() are inserted by intelisense without parenthesis:
![image](https://user-images.githubusercontent.com/3911556/101791619-08e40000-3b04-11eb-95f6-00f4a1a480ca.png)

**To Reproduce**
Type "Rec.IsTemp" and use Intelisense to insert the complete call.

**Expected behavior**
The procedures IsEmpty, Count and IsTemporary (maybe more) are documented as methods and not as properties (Online and in VS Code). Why should this procedures used different?

And from the logic perspective IsEmpty and Count are no properties, because the system has to ask the sql server.

**Versions:**
AL Language v6.1.381323

**Comment by IvoMol** [comment]
GuiAllowed too

**Comment by thpeder** [comment]
Thanks for reporting the issue, we will track the progress in #6365 as they report the same issue.

**Comment by dnpb** [comment]
apparently intentional: https://github.com/microsoft/AL/issues/6908#issuecomment-1028644117
