### ISSUE TITLE
Conditionally visible page parts cause wrong initial collapse/tab of factboxes pane

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6367]
Tested on latest BC17 dev Sandbox and AL extension.

If a page has only conditionally visible factboxes, BC opens it with those factboxes hidden/unfocussed, seemingly because it decides whether to show the factbox pane - and whether to focus its Details (user) or Attachments (system) tab - during **`OnOpenPage()`**. But it is a very common need to decide part visibility later, in **`OnAfterGetCurrRecord()`**.

***

If there are System parts (Notes/Links) then the page shows those, and **user must click back to to Details tab** to see the normal factboxes:

![image](https://user-images.githubusercontent.com/63455896/101905256-0f7b8180-3baf-11eb-9e48-cac2f94bde4b.png)

If not, it shows the factbox pane collapsed, and **user must expand it**, or if there are no factboxes at all that end up being visible, the pane disappears.

Neither of the bold provide an adequate user experience: we need the first tab to be focussed, showing relevant custom factboxes, not just standard system ones.

We found this when using Continia Document Capture / Expense Management, but it happens with custom factboxes too. Users opening those pages expect to see the document right away if one exists; having to click from Attachments to Details is unnecessary work and very underwhelming UX to have to give them.

For that last reason... I found that a workaround is to **make a dummy factbox with Caption = ' '** and add it at the end of `area(factboxes)`, always visible, but that is insane!

Please, make this work better! It might suffice just to add re-evaluating whether to show the pane - and which of its tabs to focus - after a record is got in `OnAfterGetCurrRecord()`.

***

sample:

```al
page 50100 TestCustomerCard
{
    ApplicationArea = All;
    Caption = 'Test Customer Card';
    PageType = Card;
    SourceTable = Customer;
    UsageCategory = Administration;

    layout
    {
        area(FactBoxes)
        {
            part(CustomerDetailsFactbox; "Customer Details FactBox")
            {
                ApplicationArea = All;
                Visible = CustomerDetailsFactboxVisible;
            }

            /*
            systempart(Links; Links)
            {
                ApplicationArea = All;
            }

            systempart(Notes; Notes)
            {
                ApplicationArea = All;
            }
            */
        }
    }

    var
        CustomerDetailsFactboxVisible: Boolean;

    trigger OnAfterGetCurrRecord()
    begin
        CustomerDetailsFactboxVisible := Rec.Name[1] = 'A';
    end;
}
```

Try it on Customers whose Name does and doesn't begin with A, and with the `systempart`s both commented and uncommented.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by dnpb** [comment]
I was reminded of this ticket and now have access to PartnerSource, so I've logged it there, as ticket 2110140040003162.
