### ISSUE TITLE
Next logo

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#637]
I don't know what the next NAV logo will be, but I'd prefer this:

![logo](https://user-images.githubusercontent.com/16351673/30160900-d81e80b0-93ce-11e7-83b4-e241e5c5136d.PNG)

(From the d365 community group in Yammer)

**Comment by StanislawStempin** [comment]
This is not related to AL Language/extensions, closing the issue. If the Yammer group you mentioned includes MS representation please mention it there.
