### ISSUE TITLE
Error on hidden expression on Inventory Posting - Test Report BC17 CU1

### ISSUE THREAD

**Issue by emimadamsa** [microsoft/AL#6371]
**Describe the bug**
Error **"Rendering output for the report failed and the following error occurred: The Hidden expression for the tablix ‘Table1’ contains an error: Input string was not in a correct format."** when running the report Inventory Posting - Test on BC17 CU1 from page Item Journal.

**To Reproduce**

1. Go to Item Journal Page
2. Insert a new line with random data
3. Select Action ->Posting -> Test Report -> Preview
![image](https://user-images.githubusercontent.com/76034795/102187373-95077600-3ebc-11eb-9f8d-4523b3a92f10.png)

4. Error **"Rendering output for the report failed and the following error occurred: The Hidden expression for the tablix ‘Table1’ contains an error: Input string was not in a correct format."** is thrown.
![image](https://user-images.githubusercontent.com/76034795/102187436-a81a4600-3ebc-11eb-8395-fe4ed0806a17.png)

**Expected behavior**
To run the report.

**Screenshots**
![image](https://user-images.githubusercontent.com/76034795/102187373-95077600-3ebc-11eb-9f8d-4523b3a92f10.png)
![image](https://user-images.githubusercontent.com/76034795/102187436-a81a4600-3ebc-11eb-8395-fe4ed0806a17.png)

**5. Versions:**
 Standard BC17 Cu1
 - Business Central: 17.1.18256.18792

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
