### ISSUE TITLE
Error Inconsistent read of field(s): 'Printing Date', in Report "Vat Fiscal Register - Print"(Italian localization)

### ISSUE THREAD

**Issue by RobbieBonini** [microsoft/AL#6378]
**Describe the bug**
When you try to print the Vat Fiscal Register - Print in final mode you collect the error: 

Inconsistent read of field(s): 'Printing Date', on table 'VAT Book Entry', identification values: 'Entry No.='xxxxx''

**To Reproduce**
Steps and to reproduce the behavior:
1. Open VatFiscal Register - Print report
2. Select a sales vat register
3. Input starting and endig date
4. Select Final in Printing Type Field
5. Run the report
``` AL Code to reproduce the issue ```

**Expected behavior**
The report should present the report layout and update entries in vat book entry table

**Screenshots**
![image](https://user-images.githubusercontent.com/76102605/102342254-47147000-3f99-11eb-8939-605910455de6.png)

![image](https://user-images.githubusercontent.com/76102605/102342331-63181180-3f99-11eb-8f01-87a5982bc42b.png)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.

**Comment by RobbieBonini** [comment]
Hi,

could you please provide me the right repository, where I can subit issues related to standard bugs?

Regards
________________________________
Da: Alexandru Toader <notifications@github.com>
Inviato: mercoledì 16 dicembre 2020 21:37
A: microsoft/AL <AL@noreply.github.com>
Cc: Robbie Bonini <roberto.bonini@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [microsoft/AL] Error Inconsistent read of field(s): 'Printing Date', in Report "Vat Fiscal Register - Print"(Italian localization) (#6378)


Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.

**Comment by dtkb** [comment]
Check [the FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions) about support:

***

I found an issue in a version of the product that is not the latest, what do I do?
=
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. If you run into an issue in NAV 2018 or Business Central 2018 Fall you need to open a regular support case. You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

I found an issue not related to AL development, what do I do?
=
Similarly to the above question, an issue not related to AL development is beyond the scope of this GitHub repository. In these cases please open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
>>>
