### ISSUE TITLE
"Trigger Parameter Hint" (Ctrl+Shift+Space) Command Not Working

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6379]
Sorry, I can't pin this down to a specific version of AL Language extension - or even if this is a problem with the extension, VS Code, or something specific to my machine.

**Symptoms**
- Trigger Parameter Hint command (Ctrl+Shift+Space) doesn't seem to do anything
- Hovering over the method name does still show the signature and types correctly
- It does work for built-in functions - FindFirst, SetRange etc. that don't require any symbolic info
- Only .al files are affected - it works as expected for a .js file in the same project

**I've tried:**
- Installing the latest version of Code - Insiders, I get the same problem
- Reinstalling Code
- Removing all extensions apart from AL Language

**Versions**
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z (5 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

AL Language: v6.1.381323

**Comment by NKarolak** [comment]
> It does work for built-in functions - FindFirst, SetRange etc. that don't require any symbolic info

Not entirely.
It works for e.g. `Rec.SetRange()`, but not for `Rec.Get()`. Other than that, I can confirm it does not work for my own procedures.

**Comment by jimmymcp** [comment]
Thanks @NKarolak, glad it's not just me! It was driving me crazy yesterday 🤪

**Comment by KabukiJoe** [comment]
I was facing the same issue and it drove me nuts.
But turning off auto updates and installing version 1.51.1 solved it for me.

**Comment by dtkb** [comment]
maybe related to https://github.com/microsoft/AL/issues/6392 ?

**Comment by jimmymcp** [comment]
Bump 👋

Any update on this?

**Comment by kalberes** [comment]
It is a bug.

**Comment by jwikman** [comment]
It seems as if this only happens with VSCode 1.52.
I was fed up with this bug earlier today and downgraded to VSCode 1.51.1. Now I get this working again!

I think I'll stay on VSCode 1.51.1 until this is properly solved...

**Comment by DavidFeldhoff** [comment]
And in the AL language extension it stopped working at 6.x
With the latest 5.x version it's still working.

**Comment by JSebastianN** [comment]
Is this the same as https://github.com/microsoft/AL/issues/6392 ?

Perhaps close of the these.

**Comment by DavidFeldhoff** [comment]
Yes, it's the same

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21216 and VS Code Extension Version 7.0.402309. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by jwikman** [comment]
@JesperSchulz will this not be backported to the public AL Language extension?

**Comment by JesperSchulz** [comment]
I'll have to forward that question to @atoader or @kalberes. My message was an autogenerated one ;-)

**Comment by jwikman** [comment]
This seems to have been backported to v6.5 that was just released. Thanks!
