### ISSUE TITLE
Event subscribers do not offer intellisense on event publisher names anymore (August release)

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#638]
I am pretty sure this worked before.

When you declare an event subscriber, you have intellisense on most elements, however you don't have it on the most important - the event publisher name.

Try this:

local procedure Something();
begin
end;

Then start adding the EventSubscriber attribute:

[EventSubscriber( * )]

At * point, you start using Intellisense to suggest the elements of the subscriber, and it works for objecttype parameter, for object id parameter, however when you attempt to intellisense the list of publishers on the selected object, you don't get that list anymore. I am pretty sure it worked in an earlier update, but doesn't seem to work anymore with August release.

**Comment by Gallimathias** [comment]
In Current Version (September) is the same problem

**Comment by kalberes** [comment]
Lame. We will look at it and fix it.

**Comment by kalberes** [comment]
@vjekob
After the object type, asking completion for the id may have left an empty completion opened. This maybe the reason why you did not get intellisense for the publisher method names
If you would try "esc" before asking for completion on the publisher names, than it should work.?
Or if you have not asked intellisense on the object id, than it would also work,
Looks a VsCode problem, that comma does not close an intellisense session. Nevertheless we can see if they accept this  as an issue.
