### ISSUE TITLE
Rule AA0219 is being applied to Page Actions

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6383]
**Describe the bug**
If CodeCop analyzer rule "AA0219" is enabled, warnings are raised for all action tooltips that don't start with "Specifies".

**To Reproduce**
Add this rule to your custom ruleset.json:
        {
            "id": "AA0219",
            "action": "Warning"
        }

Add an action to a page with any text that does not start with 'Specifies'.

**Expected behavior**
Warnings should be raised for field tooltips, but not for page actions, as specified in the docs: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop

**Screenshots**
None

**5. Versions:**

 - AL Language: 6.1.381323

 - Business Central: Platform 17.0.18204.18738 + Application 17.1.18256.18792

**Comment by salgiza** [comment]
Any news on this? We just enabled the AA0219 rule and it still raises warnings in action tooltips, using v8.1.525271 of the AL extension.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

Going forward we will not track progress on CodeCop issues here on GitHub. Hence, we are closing this issue.

**Comment by salgiza** [comment]
Hi @mazhelez, going forward, if I ever found another bug on CodeCop, what will be the proper way to report it?

**Comment by mazhelez** [comment]
@salgiza If you consider the issue important enough and it reproes on the latest version, feel free to report it again.

We simply want to set the right expectations: CodeCop is, unfortunately, not a priority for us at the moment, so these issues will not be addressed in the near future. 

We do acknowledge all these issues, but if no one will be working on them in the foreseeable future, there is no point of having them open.
