### ISSUE TITLE
What is a Joker in AL?

### ISSUE THREAD

**Issue by Kushal5** [microsoft/AL#6387]
![image](https://user-images.githubusercontent.com/17171560/102564919-ed4aac00-4138-11eb-9712-5e742f46e6cb.png)

I would like to better understand the code behind SetRange. I see that there is a Joker Type that is being used. Is this open to AL Extension Developers?  

It seems like its more closely resembles a Generic Type T as we use it in C#?

Would be really good to better understand this piece of functionality, could help in making libraries around AL more easier.

**Comment by dannoe** [comment]
The Joker just means that you can insert any table field (doesn't matter if code, integer, boolean, etc.) as parameter.
It's similar to the [variant](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/variant/variant-data-type) data type. I don't think you can use the joker type for your own implementations.

**Comment by dtkb** [comment]
Yes, it seems like a `Variant` but where it can also accept field names, and uses them as (lists of) ID(s) for generic functions like `SetRange()`, instead of getting and using their value.

Seems like an implementation detail for sure, which we only know about because they had to call it _something_ in the API.

I would sure like some new `RecordRef`/`FieldRef`-like types that could automatically convert from record/field names in argument lists without me having to do `.GetTable()`, `.Field()`, etc...

**Comment by atoader** [comment]
Joker is an internal type that is not exposed to AL developers. As in some card games, the Joker can replace any other type. In certain cases, it plays the role of a generic T which is inferred from the type of the left hand side of the invocation expression, on other cases, it is inferred from another parameter.

**Comment by atoader** [comment]
We will update the docs on this topic to prevent confusion in the future.

**Comment by Kushal5** [comment]
Thanks for the information. Would such a data type be open to AL developers in future?
I can think of a couple of use cases where this might come in very handy.

**Comment by atoader** [comment]
It will probably not be exposed in its current shape. What use cases do you have in mind?

**Comment by Kushal5** [comment]
Well actually, what I would really have practical use for would be to be able to create extension methods to available datatypes that can be applied to all record types as an example. So I could potentially create helper methods that are universal across all my extensions.

Just like we have the SETRANGE method available across all record types.

**Comment by Kushal5** [comment]
So for example, we could have 

codeunit 50000 extentionmethod
    procedure somemethod(joker) extends record

when using it anywhere in my extension 
Record.somemethod is aval

Does that sound like a good idea?

**Comment by dtkb** [comment]
Do you mean you want something like

```al
procedure GetNameOrDescription(j: Joker) extends Record: Text
begin
  // code to find the Name or Description field and return its value
end;

// elsewhere:

procedure UseIt()
var
  Customer: Record Customer;
begin
  Customer.FindFirst();
  Message(Customer.GetNameOrDescription());
end;
```

Then why are extension methods needed? Can't one instead just create a free function? AFAICT it is nowadays generally advised that things should not be member functions (which in AL includes being a record/table method) if they don't absolutely need to be, i.e. they don't need any private data from the record instance.

What I was thinking of was instead something like

```al
procedure GetNameOrDescription(r: Record: Text
begin
  // use r like a RecordRef
end;
```

where the `Record` type is like a 'base class' that could accept any record, like one would normally use a `Variant`, but the `Record` could immediately be used like a `RecordRef` without the user having to declare a `RecordRef` and do `GetTable(RecVariant)`, and so on. That to me still makes developers' lives easier / less repetitive while not overdoing OOPisms

**Comment by atoader** [comment]
We'll fix the documentation bug, but for the feature, I suggest you file it on BC Ideas

**Comment by NKarolak** [comment]
The documentation was updated yesterday.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-joker-datatype

**Comment by atoader** [comment]
We have updated the documentation. I will close this issue. For suggestions or improvements, please open a new idea on BCIdeas
