### ISSUE TITLE
For SAAS BC trying to open BC from mail using GETURL

### ISSUE THREAD

**Issue by gchede1990** [microsoft/AL#6389]
Dose anyone try with GETURL in al for opening BC saas from mail?
Or any other way ?

I am sending mail to users from SAAS bussines central and from same mail i want open purchase order list.
I used GETURL function for opening SAAS BC with page filters of po list.

Below one is code i am trying
 PH.reset;
 PH.SetRange(CreatedUserId, usersetup."User ID");
   SmtpMail.AppendBody('<a href=' + GETURL(ClientType::Default, COMPANYNAME, ObjectType::Page, 9307, PH) + '</a>');
``` AL Code to reproduce the issue ```

With above code mail is gating Triger with expected body and with clicking link to open BC saas.

But when i am trying to opne BC saas from mail from link it showing me error of datetime.
![image](https://user-images.githubusercontent.com/55437793/102869164-a6202c00-4454-11eb-8b2c-c6d40a4398c2.png)
Error+++
Something went wrong.
An error has occurred
Date and time: Tue, 22 Dec 2020 08:53:03 GMT
Operation: 17d023e0-520e-4509-af86-5ea71194be1d

i think by link it's trying to open in default time zone GMT, if this will get open with currect time zone then i think my error will get solved.

Please suggest me way to handle above case.
thanks in advance .

 - Business Central:

**Comment by dtkb** [comment]
The error is not anything to do with date or time; that is just the timestamp of the error.

Have you checked the link that gets loaded when you click in the email? Is it valid? Does it work when copied/pasted into the address bar but just not when clicked? etc.

Anyway, this seems like support, so probably off-topic for here as not about AL dev tooling.

**Comment by gchede1990** [comment]
Ya i checked that url is not open in other address bar also.

**Comment by dtkb** [comment]
So show an example of actual HTML that you generate, and the link that results from it.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
