### ISSUE TITLE
Nav APP

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#639]
If I see it correctly, the windows client is dead. On the preview machine is only the web client, can we already get the universal app for the machine or can I just not see it?

**Comment by twityde** [comment]
The windows client isn't dead.
The september devpreview Azure VM is docker based (https://github.com/Microsoft/nav-docker).
The navserver container is created without "-e ClickOnce=Y", so only the webclient is deployed.
You can setup a new container with ClickOnce enabled or copy out the client with the "NAV Container PowerShell Prompt" (cp -r 'C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\' C:\Run\my\).
"C:\run\my" is mapped to "C:\myfolder" of the azure machine.

**Comment by Gallimathias** [comment]
Ok thanks for the help :) @twityde.

I used the whole day through the web client today. I like it now: D

I have to say the new deployment with docker pleases me extraordinarily well.

**Comment by Gallimathias** [comment]
Ok docker's new to me. But the way this looks like, it promises to be exciting.

![wtf](https://user-images.githubusercontent.com/16351673/30198324-5d8e54b6-946d-11e7-9c63-b85f23252d2f.PNG)
