### ISSUE TITLE
BC17 AU localization Error while upgrade Sync

### ISSUE THREAD

**Issue by hpmindquad** [microsoft/AL#6390]
Sync-NAVApp : Table Company Information :: The field 'EORI Number' cannot be located. Removing fields is not allowed.
Table Intrastat Jnl. Line :: The field 'Partner VAT ID' cannot be located. Removing fields is not allowed.

Table Company Information :: The field 'EORI Number' - 92 no field
able Intrastat Jnl. Line :: The field 'Partner VAT ID' - 30 no field

**Comment by dtkb** [comment]
While upgrading what kind of BC, from which old version to which new version? Anyway, seems not related to AL dev tooling so probably off-topic for here.

**Comment by konysh** [comment]
Hi, I have the same problem with FI localization. Upgrading from NAV2018 to BC17.

Any idea?
