### ISSUE TITLE
Modal card pages with factbox pane are artificially limited to 1 column of fields

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6391]
**Describe the bug**
If a Card page is opened modally (with `Page.RunModal()`, etc.) and has its factboxes pane revealed, the web client forces it to only render 1 column of fields, even if enough space is available, which looks awful on any sufficiently wide screen.

This means as developers we can't have the expected/desired layout on such modal pages, and we have to (if even possible) rewrite code, which in previous versions of BC just behaved as we expected, to work around this new bug in rendering.

BC15 (and maybe 16, not tested) was fine with this and just worked as expected, although there the factboxes must be revealed via a mysterious "<" button instead of the usual "i"...

**To Reproduce**
```al
page 50100 Test
{
    actions
    {
        area(Processing)
        {
            action(RunNonModal)
            {
                ApplicationArea = All;
                Caption = 'Run Non-Modal';
                Image = ViewPage;

                trigger OnAction()
                var
                    Customer: Record Customer;
                begin
                    Customer.FindFirst();
                    Page.Run(Page::"Customer Card", Customer);
                end;
            }

            action(RunModal)
            {
                ApplicationArea = All;
                Caption = 'Run Modal';
                Image = ViewPage;

                trigger OnAction()
                var
                    Customer: Record Customer;
                begin
                    Customer.FindFirst();
                    Page.RunModal(Page::"Customer Card", Customer);
                end;
            }
        }
    }
}
```

**Expected behavior**
We expect that a modal card will render basically the same as a non-modal one, except the obvious difference that it will need to be closed in a different way. That is: it should render the same number/distribution of columns for the same page width, not artificially force one.

**Screenshots**
**BC17**, Customer Card, run **modally**, with factboxes **collapsed**:
![image](https://user-images.githubusercontent.com/63455896/102885504-5a1cb980-444b-11eb-98e6-8e7817312957.png)

ditto, run modally, with factboxes fully **expanded**:
![image](https://user-images.githubusercontent.com/63455896/102885521-6143c780-444b-11eb-82d4-5fbcbe723ea2.png)

Note that in the process of animating the expansion of the factbox pane, BC **briefly** shows the expected result in modal mode, as captured in this lucky screenshot:
![image](https://user-images.githubusercontent.com/63455896/102885567-7a4c7880-444b-11eb-846e-6e4f1622922b.png)

ditto, but run **non-modally**, and stably showing both factboxes and 2 columns as expected:
![image](https://user-images.githubusercontent.com/63455896/102885614-8b958500-444b-11eb-9610-b048a5a7a616.png)

**BC15, modal**, working as expected (apart from the "i" button to reveal being replaced by "<"...):
![image](https://user-images.githubusercontent.com/63455896/102889795-32315400-4453-11eb-8934-2bcad9aa4861.png)

**5. Versions:**

 - AL Language: 6.1.381323

 - Business Central: GB Business Central 17.2 (Platform 17.0.19353.20198 + Application 17.2.19367.19525)

**Comment by atoader** [comment]
Hi @dtkb! Thank you for the great repro! I might be wrong, but it seems like this is not a development tools issue, but more of a runtime/web client issue. Am I missing something?

**Comment by dtkb** [comment]
Yeah, I guess so. I didn't have anywhere better to report it, and it is causing us quite a problem with affected pages. Are you able to forward it? I don't know if it's in scope of what our partner will forward to MS; I know next to nothing about that side of things.

Just to check today, I created a new BC 17.x sandbox container to see if it still persists in the latest release, and it does: I see the same results in GB Business Central 17.3 (Platform 17.0.20458.21149 + Application 17.3.20469.21180)

**Comment by dtkb** [comment]
This sounds like it's fixed in 17.5, but I haven't got (convenient) access to that to test yet.

![image](https://user-images.githubusercontent.com/63455896/110451811-7cbe8600-80bc-11eb-8c1f-23c5b5199d3b.png)

**Comment by atoader** [comment]
You can try signing up for a sandbox tenant or creating a new sandbox.

**Comment by atoader** [comment]
I'll close the issue. Let me know if it is still a problem.

**Comment by dtkb** [comment]
Yes, that seems fine now. Thanks - and also to whoever fixed it, and whoever managed to report it at the right place :-P

![image](https://user-images.githubusercontent.com/63455896/110610897-93311400-8186-11eb-8c37-fcb74bafa0a4.png)
