### ISSUE TITLE
missing Intellisense popup/tooltip for function argument list when opening with (

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6392]
**Describe the bug**
The title says it all. It used to be that after typing the opening `(` of a function argument list (after first deleting the auto-filled `()` that defeat that...), we would get a popup/tooltip showing the arguments with names/types (for the first overload, at least). This is now gone.

**To Reproduce**
Type a function name, then `(`, and see that there's not a popup anymore.

I rolled back the AL extension a couple of months, when I think this was OK, and it still seems to be the same, so maybe this is a VS Code bug, in which case please advise whether it's reported upstream and if not then do so. Thanks!

**Expected behavior**
Same as before.

**Screenshots**
after typing the opening `(`, no guidelines/suggestions as to the arguments:
![image](https://user-images.githubusercontent.com/63455896/102888987-b4b91400-4451-11eb-8a42-d18a35299b8f.png)

**5. Versions:**

 - AL Language: 6.1.381323

 - Business Central: n/a

**Comment by MBK75** [comment]
I have the same exact issue and came here looking for a fix.  No Intellisense.  Not only that, but it often enters a bunch of random code after closing a parenthesis.

**Comment by JSebastianN** [comment]
I have this too.

CTRL+SHIFT+SPACE only works for system functions like SetRange.
Not my own procedures.

Preeettyyy annoying.

**Comment by JSebastianN** [comment]
I wonder when this will be handled....

**Comment by dtkb** [comment]
This seems fixed in AL Language extension v6.5.413786 now available/updated via VS Code.
