### ISSUE TITLE
DotNet_Regex Obsolete?

### ISSUE THREAD

**Issue by MBK75** [microsoft/AL#6393]
Hello, 

I am receiving compiler warnings as follows:

warning AL0432: Codeunit 'DotNet_Regex' is marked for removal. Reason: This codeunit is obsolete. Use the Regex codeunit in the Regex Module instead.. Tag: 18.0.
warning AL0432: Codeunit 'DotNet_Match' is marked for removal. Reason: This codeunit is obsolete. Use the Matches table in the Regex Module instead.. Tag: 18.0.
warning AL0432: Codeunit 'DotNet_Group' is marked for removal. Reason: This codeunit is obsolete. Use the Groups table in the Regex Module instead.. Tag: 18.0.
warning AL0432: Codeunit 'DotNet_GroupCollection' is marked for removal. Reason: This codeunit is obsolete. Use the Groups table in the Regex Module instead.. Tag: 18.0.

However, there are no code samples or source code available as to how to use these new codeunits, and going to the definition yields an empty codeunit file.  Would it be possible to please include a Url in the warning to link to a demonstration of how to replace this functionality?  The functions in the Regex codeunit are nothing like what was in DotNet_Regex.

Thank you!

**Comment by dannoe** [comment]
You can find the source code here: https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Regex

**Comment by atoader** [comment]
@MBK75 issues related to the AL application should go to ALAppExtensions (see their readme) or to support.
