### ISSUE TITLE
"Partial" objects

### ISSUE THREAD

**Issue by anzwdev** [microsoft/AL#64]
It would be nice to be able to split object definition between multiple files the same way as it can be done with partial classes in c#. It would allow us to separate page or table definition and code and design them visually in other editors (i.e. design page layout in web client and write code in vs code). It will also be possible to generate part of the objects from another file format (i.e. WSDL), add additional functions manually to them and regenerate code later, when that source file changes without losing our manual modifications.

Obviously to fully separate page layout from code, trigger properties of controls would have to contain function names instead of code.

**Comment by pborring** [comment]
This is an (old) idea, which are tracked on aka.ms/bcideas. In fact, this suggestion is already there, so continue voting on that
https://experience.dynamics.com/ideas/idea/?ideaid=babeae6f-0e0f-eb11-b5d9-0003ff68ded8

Closing this GitHub entry
