### ISSUE TITLE
Elements "help", "url", and "logo" from the manifest (app.json) don't have any effect

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#640]
Copy/paste from my manifest file:

  "help": "http://vjeko.com/help",
  "url": "http://vjeko.com/",
  "logo": "./hand_thumb_up.png",

However, when the extension is published, these do not show or do not have any effect.

I tried "logo" without "./", but it didn't help. I tried putting into a subfolder, and it didn't work either.

I also tried a http path for the logo, but it even broke the publishing stage for the extension.

This is all on August release, I don't know if it ever worked or if it is already fixed for September.

**Comment by hvogelpohl** [comment]
I can't reproduce the behavior. Apparently it was fixed. Maybe I misunderstood something, but I just put my _logo.png_ in the path where the _.app_ files are located. Then I added logo _logo.png_ ("logo": "logo.png",) to _app.json_. 

Works.

**Comment by DominikDitoIvosevic** [comment]
I have verified this and it works for both the logo and the other values
