### ISSUE TITLE
Add Multiline Tooltip Support

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6400]
**Describe the bug**
Tooltips currently need to be on one line, meaning complicated tooltips will far exceed legibility.

**To Reproduce**
Add a tooltip to a field, eventually the text is excessively long and doesn't support line breaks.,

``` 
                field("Some Field"; Rec."Some Field")
                {
                    ApplicationArea = All;
                    ToolTip = 'This is a complicated field where each individual option is explained. Now the text has gotten excessively long. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisi quis eleifend quam adipiscing vitae. Elementum curabitur vitae nunc sed velit. Sed enim ut sem viverra aliquet. Molestie a iaculis at erat. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Dictum non consectetur a erat nam at lectus urna duis. Eget egestas purus viverra accumsan in nisl. Egestas maecenas pharetra convallis posuere morbi leo urna. In nisl nisi scelerisque eu ultrices vitae auctor. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Pulvinar sapien et ligula ullamcorper. Mauris cursus mattis molestie a iaculis. Leo vel fringilla est ullamcorper eget. Nibh nisl condimentum id venenatis a condimentum. Elit pellentesque habitant morbi tristique senectus et netus et malesuada.';
                }
 ```

**Expected behaviour**
A way to add line breaks so we can keep our files to a desired widths. E.g. a plus between the strong literals. I'd even accept a special char for multiline tooltips, or something.

**5. Versions:**
 - AL Language: All
 - Business Central: All

**Comment by dtkb** [comment]
> E.g. a plus between the strong literals.

Why not just a `\`, as in `StrSubstNo()` _et al._? Not sure what you mean by adding a plus (within or outwith quotes?), but that seems unconventional and no need since we have `\`.

**Comment by dtkb** [comment]
(read this wrongly at first)

I would like this, but would suggest it be a general AL feature for any `'string'`, to support escaping onto a new line, without actually adding a new line into the string (which we _also_ can't do, at least not generally/reliably).

At first I thought you were asking for the ability to specify line breaks to be shown in tooltips, but that seems not the case - however, that could also be a desirable feature.

**Comment by AskeHolst** [comment]
The big question to me is translations. In the xliff file it would need to be one long text anyway to not break translation tooling. 
I would suggest just turning on word-wrap in VScode.

**Comment by atoader** [comment]
I second AskeHolst's comment. For multi-line string support, please file a new idea on https://aka.ms/BusinessCentralideas, or vote up the idea if its already there.
