### ISSUE TITLE
Support to avoid Overloads allowing Functions with Parameters with default values

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#6405]
In the codeunits of libraries within BC it is more and more common to find overloaded Functions with different signature in their API.

Sometimes, this also means that the previous one is marked as obsolete to eliminate it completely at some point.

The _RecordRef_ and the _Interfaces_ have been a step forward in the right direction, but it is necessary to continue...

I think it would be a good point to **support Functions with optional parameters that take default values** as is already done in other programming languages such as **Python** or **Typescript**.

```al
procedure myOverloadedFunction(param1: Variant; optional param2 := 'hello' : Text; optional param3 := 10.5 : Decimal)
var
begin
    // do something
end;
```

**Comment by Drakonian** [comment]
Agree, also we have some wierd "overload" 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-overload-method

**Comment by dtkb** [comment]
What is "weird" about that link? What should change? The suggested overloading doesn't look weird to me (at least in a language that lacks template functions)

**Comment by JavierFuentes** [comment]
My suggeston is about to avoid obsolescense of Funtions only because we would need to add 1 new parameter for example... It's happening now in BC v17 standard code and I think there are better tecnichal solutions implemented in other languages.

Regarding the link above, I think all DataTypes should have nativelly the capacity of transform to Strings, maybe, implementing its own method like Number.ToText(decimals) , Date.ToText(format) and so on... generating an homogeneous API.

**Comment by atoader** [comment]
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release. This is a bigger feature and we need to weight it against other features suggested for BC.
