### ISSUE TITLE
Length of the application object identifier

### ISSUE THREAD

**Issue by Pomaroli** [microsoft/AL#6407]
AL Extension Version: 6.1.381323

Is it possible to make the text Length available for Object identifier longer then Text[30] ?
i Think Text[50] would be a good value.

Example of tablextension :

**tableextension 60297 "Microsoft-bas Issued Reminder Header" extends "Issued Reminder Header"**

**Comment by atoader** [comment]
There's already a BC Idea on this topic https://experience.dynamics.com/ideas/idea/?ideaid=7dce671b-7802-ea11-b862-0003ff68edfa . I'll close this one. Please submit your vote there.
