### ISSUE TITLE
Intellisense for pagecustomization objects lists addfirst, addbefore, addafter, addlast functions

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#641]
When defining a pagecustomization object, intellisense will suggest functions that the compiler will reject.

Inside customizations only move* functions and modify function should be suggested by intellisense.

**Comment by kalberes** [comment]
Yeah, we are not as fine grained as we want on scope yet.

**Comment by DominikDitoIvosevic** [comment]
When you say "functions" do you mean these "addafter/addlast..." or do you mean something else is recommended somewhere as well when it shouldn't?
