### ISSUE TITLE
CaptionClass is not taken into account in lookup pages on role centers

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#6410]
Scenario: We extended the O365 Activities Page and added a Cue. The source of it is a function - not a field.
To have a good caption, we use the CaptionClass.  You can see the source code in the first screenshot. 
That works fine.
Code:
![image](https://user-images.githubusercontent.com/53570297/104187450-1ac50580-5418-11eb-98d3-c46e477a5b2d.png)
Webclient:
![image](https://user-images.githubusercontent.com/53570297/104187456-1d275f80-5418-11eb-8560-8aff221d0aa9.png)

But as far as we use the DrillDown where we have a Page.Run(0, Variant) then for some reason a wrong caption is displayed.
Drilldown:
![image](https://user-images.githubusercontent.com/53570297/104187484-26b0c780-5418-11eb-9f98-ccce8eab02d9.png)

Note: I can only reproduce this behaviour on role centers.

**Comment by atoader** [comment]
CaptionClass is not supported on Role Centers. The most we can do is add a warning in UICop to make this easier to detect.

**Comment by DavidFeldhoff** [comment]
Okay, understood thanks. But just for clarification:
The cue which is placed on the role center works with the caption class, so that's fine. 
The not working captionclass is on the page "Customer Lookup" when I open that page from the role center via drilldown as you can see in the screenshot. 
Is that the known limitation you meant?

**Comment by atoader** [comment]
Thanks for clarifying, David! That sounds more like a bug in the runtime, which would fall outside the scope of this repository. I suggest that you open a bug through Collaborate or a support case if it makes sense.

**Comment by DavidFeldhoff** [comment]
Okay, thanks, I opened a bug on collaborate and will keep this github issue updated, but as there are no further steps to do from your site, I'll close this one.
