### ISSUE TITLE
AA0150 Unneeded warning of 'declared by reference but never changed'

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#6411]
**Describe the bug**
I got a test procedure that tests a procedure which contains a strmenu.
`Choice := StrMenu(OptionProjects_Txt, 1);`

```
[StrMenuHandler]
 procedure StrMenuHandler(Option: Text[1024]; var Choice: Integer; Instruction: Text[1024])
 begin
 ///Choice := 1;////
 end;
```

CodeCop gives a warning on Choice 
```
(parameter) var Choice: Integer
Parameter 'Choice' is declared by reference but never changed in method 'StrMenuHandler'.AL(AA0150)
```
(
Removing the var gives error:
```
The signature of procedure 'StrMenuHandler' does not match the signature required by attribute 'StrMenuHandler': parameter 2 is expected to be of type 'var Integer' but found type 'Integer'. The expected signature is: StrMenuHandler(Options: Text[1024], var Choice: Integer, Instruction: Text[1024]).AL(AL0240)
```
)

The default option of the choice is 1, and I want to continue with that value.

**To Reproduce**
Create a test procedure for a procedure that has a strmenu with default option.
Add a StrMenuHandler for that tes.
Don't assign choice to a value.

``` AL Code to reproduce the issue ```

**Expected behavior**
No need to assign choice to the default option to remove the warning

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.396068

 - Business Central: BC17.2

https://www.yammer.com/dynamicsnavdev/threads/1031264763748352

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
