### ISSUE TITLE
Unable to switch culture when using web services

### ISSUE THREAD

**Issue by Joerio** [microsoft/AL#6413]
I have published a web service that can return reports as PDF, for example an invoice. Based on the language of the customer the report should be returned in either Dutch or English. 

AL provides some methods to change language and locale settings (globallanguage and SessionSettings). However, no matter what I set only the language gets changed and the date format. The date format is correctly switched between the cultures.
The number format is however never changes and always uses the . as decimal separator.

When trying this from the client itself, and changing my regional and language settings before running the report does give the correct values.

It seems that the culture isn't applied on the number format. There seems no function available to set this correctly. Is this a bug or is there another way to correctly switch the culture of a session?

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
