### ISSUE TITLE
Debug - Variables - Database Statistics - Cannot see / copy full SQL statement

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6415]
**Describe the bug**
When debugging, I'm trying to analyse the SQL statements created via the Variables - Database statistics fields. However, I don't succeed at all in seeing the **full** SQL statement.

- When hovering the value, the SQL statement is truncated with '...' (OK)
- When trying to copy the value / expression (right click), I get another irrelevant SQL statement than the line / value which is currently selected.
- Add watch is no option either, because over here the value is different too.

**Expected behavior**
I would like to easily copy a **complete** SQL statement so I can analyse the contents (especially the joins at the end of the query)

**Screenshots**
Right click on this location does not give me the full content of the SQL statement.

![image](https://user-images.githubusercontent.com/25268332/104515001-7519be00-55f2-11eb-8f6b-4931601a415b.png)

**5. Versions:**

 - AL Language: 
Version: 6.1.397164

 - Business Central: 17.2

**Comment by dtkb** [comment]
Indeed, I noticed the other wrong query being copied/shown, months ago, but I forgot to report it. This basically is not usable at the moment.

**Comment by kalberes** [comment]
Have you tried the Debug Console Window in teh debugger. By just typing SQL4 at the console? Or SQL4.Statement.

**Comment by dtkb** [comment]
I'll try it and let you know.

That doesn't change the fact that the more easy/obvious functionality for doing this is broken and returns unrelated SQL statements.

**Comment by dtkb** [comment]
So, it looks to me like what you said works - go to Debug Console, type `SQLn` where `n` is the number of the statement you actually want to see, then expand the resulting arrow and scroll down to see the statement. That gets me the content that is shown in the sidebar and previewed in a tooltip (which is **not** what gets copied with right-click > Copy Value or Add Watch, as reported).

Thanks for the workaround, but presumably the main bug needs fixed?

**Comment by kalberes** [comment]
The main bug will not be fixed soon. The UI is controlled by the VSCode debug adapter client. And it has its limits. Like, it does not support multiline values ((\r\n or \n depending on the context). 
BTW. You can type SQL(n).Statement and then you only get the statement.
We use the debug console to evaluate variables that do not fit the UI. 
I am not sure this was not mentioned but AL variables with size > 1024 bytes are truncated.  Anything that you see as hovered ending with ... is a truncated value.
We have just added support that large strings are also available, but only in the debug console.

**Comment by atoader** [comment]
We have improved the experience for working with large variables, and updated the documentation. The fix will be released in the next major release.
