### ISSUE TITLE
XMLport TableSeparator property default is not '<NewLine>' as documented

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6416]
The [current BC](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tableseparator-property) and [historical NAV](https://docs.microsoft.com/en-us/dynamics-nav/tableseparator-property) developer doc pages state that `TableSeparator` if not specified defaults to `<NewLine>`.

However, this is not the case. It seems to default to **two** newlines, and thus add a blank line between tables, i.e.

```none
Table 1 Fields

Table 2 Fields
```

but we need

```none
Table 1 Fields
Table 2 Fields
```

Thus, if we have e.g. one table to add headers and another for the data rows, we get an unwanted blank line between them - until we realise that those docs are wrong and that we have to explicitly set `TableSeparator = '<NewLine>'` to only get **one** line break between the tables, because the actual default is really **two**.

I'm not the only dev who's found this and had to waste time fixing it because of the wrong documentation; see e.g. [this thread](https://dynamicsuser.net/nav/f/developers/96632/xmlport---set-column-headers-for-the-csv-file).

Please fix the documentation to specify the real default, i.e. `<NewLine><NewLine>` presumably, so that devs will realise that to get just one newline they must override it, paradoxically with the same value that the docs currently wrongly claim is the default... Ta!

**Comment by atoader** [comment]
I've accepted the bug, but in the future, open it straight on the documentation page, that way it gets to our writers without delay.

**Comment by dtkb** [comment]
Thanks for that. Do you mean using the below button? Apologies, not sure I ever noticed that!

![image](https://user-images.githubusercontent.com/63455896/105215627-64fd6380-5b49-11eb-859b-258352c66771.png)

**Comment by atoader** [comment]
That's the one. It will open an issue on the docs repo. You can also submit a PR directly :)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This will be fixed with the next doc refresh.

**Comment by dtkb** [comment]
@SusanneWindfeldPedersen Thanks! I see it is fixed at the link for BC I originally posted. It isn't fixed at the link for NAV, but I guess such old documentation will be frozen now, so no matter.
