### ISSUE TITLE
Trigger webhook programmatically without modifying the entity

### ISSUE THREAD

**Issue by thrasheri** [microsoft/AL#6417]
I have custom API for Item that has subpages for Unit of measure and prices. I want to trigger the Item API webhook when price or unit of measure is added or modified. Is there a way to trigger the webhook via code without modifying the item record?

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
