### ISSUE TITLE
Calculate Depreciation (Report ID 5692)

### ISSUE THREAD

**Issue by porta76** [microsoft/AL#6419]
**Describe the bug**
OnOpen page overwrites variables set with procedure InitializeRequest 

**To Reproduce**
Steps and to reproduce the behavior:
1. Write a function that sets initial values using procedure InitializeRequest in report 5692
2. Open report witn Run/Runmodal
3. Values are overwritten

``` AL Code to reproduce the issue ```

var
   requestReport: Report "Calculate Depreciation";
begin
   requestReport.InitializeRequest('',
      date1,
      false,
      0,
      date2,
      '',
      '',
      false
   );
requestReport.Run();

**Expected behavior**
Reques pae should have default dates set to date1 and date2

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.397164
 - 

 - Business Central: Version: SE Business Central 17.2,SweBase 17.1.13988.0 (Platform 17.0.19353.20040 + Application 17.2.19367.20109)
Azure AD tenant: (blank), Environment: Sandbox (Sandbox)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
