### ISSUE TITLE
Compiler complains when pagecustomization reuses the ID of a pageextension object

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#642]
If you declare a pageextension object with id 70000001 and then a pagecustomization object with id 70000001, the compiler will complain.

These should not be intermixed, and the IDs should be reusable between different object types.

There used to be a bug that you couldn't declare a pageextension with the ID of a page declared in the same extension, or a tableextension with the ID of a table declared in the same extension, but this was fixed in (I think) June release.

This is the same kind of issue, and it should also be allowed to use the same ID for customizations and extensions.

This is especially important because profiles are expected to deliver a lot of page customizations, there will always be more page customizations than there are page extensions, and we should not be forced to use larger object ranges to support large volume of customization objects.

**Comment by DominikDitoIvosevic** [comment]
Page Customizations won't have IDs in the next update
