### ISSUE TITLE
No info regarding parameters are shown anymore

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#6420]
**Describe the bug**
Since AL Language Extension version 6.x I can't see anymore the help of overloaded procedures. I think it's called the "SignatureHelpProvider" which is missing. In the version 5.x it was triggered with Ctrl+Shift+Space. The screenshot where it's working is of AL Language Extension version 5.0.335750 (latest 5.x). In the first 6.x version it's not working anymore.

**To Reproduce**
1. Create a procedure which overloads another (e.g. MyProcedure() and MyProcedure(Customer: Record Customer)). Then call the procedure MyProcedure( and execute Ctrl+Shift+Space inside the parenthesis. Nothing shows up anymore.

``` 
codeunit 50109 TestMe
{
    local procedure MyProcedure()
    begin
    end;

    local procedure MyProcedure(Customer: Record Customer)
    begin
    end;

    local procedure TestMe()
    begin
        MyProcedure();
    end;
}
```

**Expected behavior**
See the overloaded procedure possibilities again (and if there's no overloaded procedure, then see the parameters from the available procedure).

**Screenshots**
Working example of latest 5.x version
![image](https://user-images.githubusercontent.com/53570297/104810146-225b2480-57f3-11eb-9ab9-d6b44ff28664.png)
Current example of latest version.
![image](https://user-images.githubusercontent.com/53570297/104810155-2edf7d00-57f3-11eb-8736-4fba4a68ad1a.png)

**5. Versions:**
 - AL Language: 6.1.397164

**Comment by jwikman** [comment]
Duplicate of #6379

**Comment by DavidFeldhoff** [comment]
Thanks for referencing :) I'll close this one.
