### ISSUE TITLE
CodCop AA0072: Valid Name for DotNet variables

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/AL#6422]
**Describe the bug**
Always  get information AL(AA0072) "The name of ... is not valid. The name of variables and parameters must be suffixed with the type or object name."

**To Reproduce**
Use a DotNet variable
``` AL Code to reproduce the issue ```
var
  Array: DotNet Array;

**Expected behavior**
Either no information of type AL(AA0072) or a rule how to name the variable.

**Screenshots**

**5. Versions:**

 - AL Language: 6.1.397164

 - Business Central:17.2.19367.19735

**Comment by dtkb** [comment]
I don't suppose naming it `DotNetArray` satisfies the warning?

**Comment by JoergPernberg** [comment]
Unfortunately, no. Still the same message.

**Comment by dtkb** [comment]
https://github.com/microsoft/AL/issues/6457 might explain what this was trying to determine, i.e. what the AA0072 CodeCop currently considers a "valid" name for .Net objects:

> MyDateTime: DotNet MyDateTime; //AL(AA0072) Warning
> "System.DateTime": DotNet MyDateTime; //Not warning

**Comment by PortHH** [comment]
var
"System.Array": DotNet Array;  

is the solution. Looks strange but it works fine.

**Comment by dtkb** [comment]
Hopefully MS can come up with a better preferred naming scheme than that! It looks underwhelming and might invite confusion with `"Record Name"."Field Name"` syntax.

I'd agree with you and the other user on your issue: the preferred name should be the alias, not the 'raw' assembly name.

That said, until AA0072 is less strict/naive then many developers will just turn it off, including for cases like this...

**Comment by qutreson** [comment]
Closing in favour of #6457
