### ISSUE TITLE
Could not download symbols. Please see the Visual Studio Code output log for more details.

### ISSUE THREAD

**Issue by Jimish-Shah24** [microsoft/AL#6425]
**Describe the bug**
 While trying to connect VS Code with Dynamics Business Central Online, getting mentioned error in one of the step and not able to establish the connection.

Could not download reference symbols. Please ensure that:
The correct server name and instance are specified in the launch.json file.
The correct application version is specified in the app.json file.
The dependencies are correctly specified in the app.json file.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to 'AL: Download Symbols'

``` AL Code to reproduce the issue ```

**Expected behavior**
I should be able to download symbols and go ahead with my development as shown in given links.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started
https://www.youtube.com/watch?v=oyLXQiBZx8g

**Screenshots**
![image](https://user-images.githubusercontent.com/77672132/105174805-194aba00-5b49-11eb-80dc-e948535dc02d.png)
![image](https://user-images.githubusercontent.com/77672132/105174955-4e570c80-5b49-11eb-962d-d7a801c2455d.png)

**5. Versions:**
 - AL Language: v6.1.397164
 - Business Central: Business Central Online (v6.0 Latest Release Wave 2 2020)

**Comment by dtkb** [comment]
Why does your `app.json` show version 17.0.0.0 but your errors show 14.0.0.0? Which is it?

**Comment by Jimish-Shah24** [comment]
> Probably not the problem, but note your `app.json` and screenshot of errors show version 17.0.0.0 but your pasted errors show 14.0.0.0, which is a tad confusing

Sorry for that actually by mistake I did that, I have updated the description now.

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
