### ISSUE TITLE
altpgen generates wrong fieldgroups

### ISSUE THREAD

**Issue by hougaard** [microsoft/AL#6428]
When altgen generates fieldsgroups, **Dropdown** is not camel-cased and is ignored by the runtime.

`fieldgroups
    {
        fieldgroup(Dropdown; Name)
        {
        }
    }
}`

Should be:

`fieldgroups
    {
        fieldgroup(DropDown; Name)
        {
        }
    }
}`

**Comment by atoader** [comment]
@hougaard could you give us some insight into how big of an issue this is for you? How often have you hit it? How easy is it to figure out what went wrong? It is clearly a bug, but we're trying to prioritize this against other bugs.

**Comment by atoader** [comment]
It would be great if you could provide an input project and the steps that we could follow to reproduce this issue.

**Comment by hougaard** [comment]
You can see it here https://github.com/hougaard/Youtube-Video-Sources/tree/master/Altpgen

It's doing it on all tables, all projects.

This is a BIG issue because it prevents automatic schema updating without going in and doing an edit...

Looks like it's hardcoded in the TableBuilder type in Microsoft.Dynamics.NAV.TableProxyGenerator
![image](https://user-images.githubusercontent.com/3357237/105215566-45911700-5b06-11eb-95ed-1e5bbb9e1309.png)

and is case sensitive as you can see here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups

![image](https://user-images.githubusercontent.com/3357237/105215666-65283f80-5b06-11eb-85d5-ce8e904ab77b.png)

**Comment by atoader** [comment]
Total game changer. :) Accepting and sending a PR right away.

**Comment by thloke** [comment]
Closing as this has been fixed in extension version 6.4.408011
