### ISSUE TITLE
Cannot directly publish table scheme updates to a LoadPackageData table

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6430]
**Describe the bug**
Error on publish from VS Code: 
`Could not install the extension <name> on tenant default due to the following error: The given value of type String from the data source cannot be converted to type nvarchar of the specified target column.`

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new table (with DataPerCompany = false) + page with any fields you like
2. Run the page and enter at least one record.
3. Export table data and add the navxdata to your project as described [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-data-for-extension#to-export-table-data).
In addition, load it that way:
```
YourNewTable.Reset();
YourNewTable.DeleteAll();
NavApp.LoadPackageData(Database::"<your table name>");
```
If set up correctly, you can now publish and the data in the table data is still kept.
4. Add an arbitrary field to your new table.
5. Publish. It will fail with the error message above.

 **The issue actually is, that the data in the given navxdata file to load do not match with the new table scheme.**

**FYI: How to resolve**
1. Comment out:
```
// YourNewTable.Reset();
// YourNewTable.DeleteAll();
// NavApp.LoadPackageData(Database::"<your table name>");
```
2. Publish your other changes.
3. Open your new page and enter missing data in your new field, if necessary.
4. Export table data again and copy the navxdata file to your repo.
5. Uncomment your code.
6. Publish.

**Expected behavior**
Could the error message be made more informative? If not, please add the error message and solution to the documentation linked above, so that other users could google the error message.

**Versions:**

 - AL Language: 6.1.397164

 - Business Central: 16.0

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
