### ISSUE TITLE
New System Event in a page of type API after the parts are processed

### ISSUE THREAD

**Issue by eclipses** [microsoft/AL#6431]
Hi, 

A new system event is required after the parts are processes in a page of type API.

Scenario:

We need to handle a request which must update purchase blanket order line quantities and then create a purchase order from this blanket order, within the same request (to optimize the request and minimize the web calls).

We have a request similar to the following:

{
“blanketNo”: “BO-0001”,
“lines”: [{
sku: “1000”,
qty: 2
},{
sku: “1001”,
qty: 3
}]
]

The web call must first process the lines and then do an action in the header. I can do this using EDM that I know is going to be removed, so in order to do it using parts, I'd like if a new event could be raised after the parts are processed.

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.

**Comment by eclipses** [comment]
Hi, I've raised this issue via Microsoft Collaborate support and I've been asked to open it here. 
Please I need someone that analyses my request properly. 
Happy to have a call if needed.

**Comment by atoader** [comment]
Hi! There are several GitHub repositories, with the right one being mentioned in the README that I linked above. Please open an issue there.

**Comment by dtkb** [comment]
hint: https://github.com/microsoft/ALAppExtensions/issues
