### ISSUE TITLE
AL Code Bug in BC 17.0.16993.0 - Copying Text50 Field into a Code20 Field

### ISSUE THREAD

**Issue by The-J-Bird** [microsoft/AL#6432]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

**Comment by The-J-Bird** [comment]
Sorry to log this one here... I've tried logging in PartnerSource, however as I don't have a service contract (and I don't want to spend £200 in reporting the bug):

There is a bug in Codeunit 5702.
FillItemCrossReferenceFromItemVendor Function

This line of code:
ItemCrossReference."Cross-Reference No." := ItemVend."Vendor Item No.";

Cross Reference No. is a Code 20 field
Vendor Item No. is a Text 50 field.

![Bug](https://user-images.githubusercontent.com/51637057/105494580-ea505780-5cb2-11eb-861c-da41c4622a68.PNG)

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
