### ISSUE TITLE
Changing the name of a custom application area many times tilts the compiler

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#6435]
**Describe the bug**
Changing the name of a custom application area many times tilts the compiler

**To Reproduce**
Steps and to reproduce the behavior:
1. Activate AppSourceCop
2. Create a table extension on "Application Area Setup"
3. Add a field on it = new Area
3. Add a page where you add a field to that new area
4. Change the name (not rename) of the field
5. Rename again to something else
6. Watch the compiler create new warnings of AA0189

`Value 'wApplicationArea' found on control Control x. Valid values are Invoicing, Basic, Suite, RelationshipMgmt, Jobs, FixedAssets, Location, BasicHR, Assembly, ItemCharges, Advanced, Warehouse, Service, Manufacturing, Planning, Dimensions, ItemTracking, Intercompany, SalesReturnOrder, PurchReturnOrder, Prepayments, CostAccounting, SalesBudget, PurchaseBudget, ItemBudget, SalesAnalysis, PurchaseAnalysis, InventoryAnalysis, XBRL, Reservation, OrderPromising, ADCS, Comments, RecordLinks, Notes, VAT, SalesTax, BasicEU, BasicCA, BasicUS, BasicMX, BasicAU, BasicNZ, BasicAT, BasicCH, BasicDE, BasicBE, BasicCZ, BasicDK, BasicES, BasicFI, BasicFR, BasicGB, BasicIS, BasicIT, BasicNL, BasicNO, BasicRU, BasicSE, wApplicationArea.`

`Value 'wApplicationArea' found on control Control y. Valid values are Invoicing, Basic, Suite, RelationshipMgmt, Jobs, FixedAssets, Location, BasicHR, Assembly, ItemCharges, Advanced, Warehouse, Service, Manufacturing, Planning, Dimensions, ItemTracking, Intercompany, SalesReturnOrder, PurchReturnOrder, Prepayments, CostAccounting, SalesBudget, PurchaseBudget, ItemBudget, SalesAnalysis, PurchaseAnalysis, InventoryAnalysis, XBRL, Reservation, OrderPromising, ADCS, Comments, RecordLinks, Notes, VAT, SalesTax, BasicEU, BasicCA, BasicUS, BasicMX, BasicAU, BasicNZ, BasicAT, BasicCH, BasicDE, BasicBE, BasicCZ, BasicDK, BasicES, BasicFI, BasicFR, BasicGB, BasicIS, BasicIT, BasicNL, BasicNO, BasicRU, BasicSE, ezfzegezwApplicationArea.`
(added some random letters)

``` AL Code to reproduce the issue ```
```
tableextension 0 "Applic Area Setup" extends "Application Area Setup"
{
    fields
    {
        // Spaces in field name are omitted in the ApplicationArea attribute
        // e.g. ApplicationArea = ExampleAppArea;
        // ApplicationArea = wApplicationArea;
        field(1; "w Application Area"; Boolean)
        {
            DataClassification = CustomerContent;
            Caption = 'w Application Area';
        }
    }
}
```
**Expected behavior**
Compiler recompiles and only shows latest warning

**Screenshots**
![image](https://user-images.githubusercontent.com/34303738/105716722-841c3c80-5f1f-11eb-95df-f0a371ebdad7.png)

**5. Versions:**

 - AL Language: 6.1.397164

 - Business Central: BE Business Central 17.2 (platform 17.0.19353.20441 + toepassing 17.2.19367.20601)

**Comment by guidorobben** [comment]
Still happening in 17.4

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
