### ISSUE TITLE
Multiplicity property not working in API Page

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/AL#6436]
#

[TestMultiplicity.zip](https://github.com/microsoft/AL/files/5878791/TestMultiplicity.zip)

**Describe the bug**
The Multiplicity property is not working when specified for a part in a API Page. This when the runtime is set to 6.1

**To Reproduce**
Steps and to reproduce the behavior:

(Please check sample in the attachments)

1. Set the runtime to 6.1 in the app.json file
2. Add a part to an existing API Page
3. Set the Multiplicity property to ZeroOrOne:
![image](https://user-images.githubusercontent.com/48217797/105966912-87c9d380-6085-11eb-9705-ac6cb680a66b.png)
4. Execute a API Request (POST) with the EntityName (instead of the EntitySetName):
![image](https://user-images.githubusercontent.com/48217797/105967131-ce1f3280-6085-11eb-9649-0f0182dd3ac0.png)
5. The Request fails with the following error:
![image](https://user-images.githubusercontent.com/48217797/105967247-edb65b00-6085-11eb-9a18-be02dadf1243.png)
6. When replacing the Multiplicity property by "CaptionML = ENU = 'Multiplicity=ZeroOrOne';" (a dirty hack), the following (correct) result is returned:
![image](https://user-images.githubusercontent.com/48217797/105967436-1fc7bd00-6086-11eb-995f-19ae64b5a755.png)

``` AL Code to reproduce the issue ```
(Please check sample in the attachments)

**Expected behavior**
The Multiplicity property should work the same as the "CaptionML = ENU = 'Multiplicity=ZeroOrOne';" hack.

**Screenshots**
(See above)

**5. Versions:**

 - AL Language: 
 ![image](https://user-images.githubusercontent.com/48217797/105967657-64535880-6086-11eb-8a56-12116dfcef4b.png)

 - Business Central:
 ![image](https://user-images.githubusercontent.com/48217797/105967822-9795e780-6086-11eb-9e0f-e405a9c2ee8e.png)

**Comment by thpeder** [comment]
Hi @daansaveyn,
Good catch, we found that we wrote the wrong version the property is available from, it should have been Runtime Version 6.3.

**Comment by atoader** [comment]
@thpeder can you update the status of this issue/

**Comment by daansaveyn** [comment]
I've tested this on BC18 and there's it's ok. The compiler also indicates this is available from runtime version 6.3

![image](https://user-images.githubusercontent.com/48217797/116410978-8ef3af80-a835-11eb-985b-453bb4d024bf.png)

The issue can be closed I guess?

**Comment by atoader** [comment]
The issue has been resolved starting from 18.0. There was an issue in the compiler where the property was not correctly marked as available from the right release.
