### ISSUE TITLE
should error if Codeunit.Run() or Page.Run() are called with the wrong record/table type

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6438]
**Describe the bug**
We can call `Codeunit.Run()` or `Page.Run()` with incompatible combinations of object ID and record/table type, which can be proven before compilation to be wrong, but which don't cause any compiler errors and instead can be published, only to fail at runtime.

**To Reproduce**
![image](https://user-images.githubusercontent.com/63455896/105995538-054f0d00-60a1-11eb-8b4b-de8ba0d9ae36.png)

**Expected behavior**
If the object ID is a literal constant and the record has a known type (i.e. is not a `Variant`), this should be diagnosed at compile time as an error and not slip through to production.

**5. Versions:**
 - AL Language: 6.1.397164

**Comment by StefanMaron** [comment]
Also see https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/16

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
