### ISSUE TITLE
Can not open Extension Mgt.

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#644]
I have tried to rebuild the problem #640 from @vjekob in the latest version. But this doesn't work because the extensions overview cannot be opened. A "working on it" window will appear and then load endlessly long.

Picture is after 20 minutes waiting

![after20min](https://user-images.githubusercontent.com/16351673/30163415-30946804-93d9-11e7-9548-c079f766ed48.PNG)

**Comment by DominikDitoIvosevic** [comment]
I cannot repro this. It opens immediately for me

**Comment by Gallimathias** [comment]
How many apps have you installed? I have three of my own apps with customization, but I don't get the bug since I uninstalled it. 

Maybe it was an interplay of the apps.

**Comment by DominikDitoIvosevic** [comment]
I have on average 2-3 extensions installed. It could be that this was some rare hiccup. Without a clear repro I don't have much to work with

**Comment by Gallimathias** [comment]
Ok then we close the issue and put it to the files. If the error reappears, we can reopen the issue.
