### ISSUE TITLE
[Event Request] New System Event in a page of type API after the parts are processed

### ISSUE THREAD

**Issue by eclipses** [microsoft/AL#6443]
Hi,

A new system event is required after the parts are processes in a page of type API.

Scenario:

We need to handle a request which must update purchase blanket order line quantities and then create a purchase order from this blanket order, within the same request (to optimize the request and minimize the web calls).

We have a request similar to the following:

{
“blanketNo”: “BO-0001”,
“lines”: [{
sku: “1000”,
qty: 2
},{
sku: “1001”,
qty: 3
}]
]

The web call must first process the lines and then do an action in the header. I can do this using EDM that I know is going to be removed, so in order to do it using parts, I'd like if a new event could be raised after the parts are processed.

**Comment by dtkb** [comment]
This was reposted at AlAppExtensions because it was closed as off-topic here: https://github.com/microsoft/AL/issues/6431

and now it just got moved back... Could the two repos at least make a clear statement whether this is definitely on/off-topic for either/both of them, instead of bouncing it around?

It's not clear to me what is really requested (but I don't know much about API pages, so maybe that's why), but if it's a system event, i.e. one that can't/shouldn't be implemented in individual objects but instead automatically, then it seems AlAppExtensions don't want those and consider them to be requests for the AL language instead. Is that not the case?

**Comment by atoader** [comment]
I've reached out to Stan to ensure that issues are routed more efficiently. If the request is for a platform event, this is outside the scope of both repositories and the request should go to BCIdeas.

**Comment by atoader** [comment]
@eclipses can you provide more detail for your request?

**Comment by eclipses** [comment]
Hi @atoader,

Please read the following scenario: 

Creating a Custom page of type API. We need to handle a request which must update purchase blanket order line quantities and then create a purchase order from this blanket order, within the same request (to optimize the request and minimize the web calls).

We have a request similar to the following:

```
{
    “blanketNo”: “BO-0001”,
    “lines”: [{
        sku: “1000”,
        qty: 2
    },{
        sku: “1001”,
        qty: 3
    }]
]
```

Desired Result:
Process the lines first and then do an action in the header. 

I can do this using EDM which is now deprecated and BC does not offer any valid alternative. My request is if possible create a page with parts and have system events after parts are processed.

If I send a Post request to this API currently the Events raised are:
1) Open Page
2) Header Insert
3) Line Insert (for every line)

There is no event on the page after the Lines are inserted/processed.

What Microsoft is doing to improve API? Any development to replace the EDM? Maybe allow publishing a function as Web Sevice that accepts JSON structure as a parameter?

The only workaround that I found at the moment is to pass lines as text and use escaped JSON (only for the part of the lines) 
```
{ 
    “blanketNo”: “BO-0001”,
    "lines": "[{\"skuCode\":\"1000\",\"qty\":2},{\"skuCode\":\"1001\",\"qty\":3}]"
}
```

Please let me know if you need further details.

Thank you in advance for your support

**Comment by atoader** [comment]
Hi @eclipses ! Thank you for providing the additional information. It was not clear to me if this concerns the AL extension for VSCode. As far as I understand, this is a request for enhancing the runtime of the product by adding additional system events.

Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there.
