### ISSUE TITLE
RecordID: Use the Caption property instead of the table name

### ISSUE THREAD

**Issue by reiniroosh** [microsoft/AL#6449]
When the `RecordId()` is formatted to string, can the `Caption` property of the table name be used?
The app/extension tables have the partner code, and don't look nice.

Most of the time the application is good about always using the `Caption` property and the partner codes aren't usually visible to the user.
It seemed like some odd corner cases that still have to be updated for it to be as consistent as possible.

`MissingCalendarLbl: Label 'The %1 has not been entered for the period from %2 to %3.';`

![image](https://user-images.githubusercontent.com/7827702/103247779-f0a21c80-491c-11eb-999e-611610b89933.png)

![image](https://user-images.githubusercontent.com/7827702/103247812-06174680-491d-11eb-9076-5014be33a0b0.png)

![image](https://user-images.githubusercontent.com/7827702/103247849-22b37e80-491d-11eb-9502-9b19e881e244.png)

**Comment by NKarolak** [comment]
The RecordId method is not intended to be used for user friendly messages, but to technically describe or find a record in a unique manner, and language independent.
Use `HarvestSchedule.TableCaption` + the PK fields instead.

**Comment by reiniroosh** [comment]
Hey Natalie, thx for taking a look. OK. I see in the documentation it says to use the Format() function on the record id, and I see that this does use the table cation like I was hoping in some cases.

If I call `format(TheRecordId, 0, 0)` I get the "table name" version of it.
If I call `format(TheRecordId, 0, 1)`  I get the table caption version of it.

The third parameter to Format is the "FormatString"  It was surprising to me that it caused a different object property to build the string.

**Comment by NKarolak** [comment]
Good to know, thanks!
You should create a GitHub issue for the corresponding article to get that feature mentioned there.
What article were you reading, by the way?

**Comment by reiniroosh** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-recordid-method-record
