### ISSUE TITLE
Caching issue of the webclient

### ISSUE THREAD

**Issue by wdet** [microsoft/AL#6450]
**Describe the bug**
We noticed a caching bug if we try to open pages via a proxy page with an hyperlink.
When we open a second page via a proxy page then this page is loaded with the first loaded page (contains no data) in the background (probably because it has been cached).

**To Reproduce**
I added a sample app that simulates this issue. After publishing this sample, the issue can be simulated by following these steps:

Goto:  http://\<server\>:\<port\>/\<instance\>/?company=\<company\>&page=50100&filter='Entry%20No.'%20IS%20'1' (this will open the customer card)
then goto: http://\<server\>:\<port\>/\<instance\>/?company=\<company\>&page=50100&filter='Entry%20No.'%20IS%20'2' (this will open the vendor card, with the previously opened customer card in the background (screenshot 1)

[Caching Issue.zip](https://github.com/microsoft/AL/files/5919177/Caching.Issue.zip)

**Expected behavior**
Only the requested page should be opened. In this case the vendor card.

**Screenshots**
![image](https://user-images.githubusercontent.com/36985016/106761144-cf77ce80-6634-11eb-8bf5-62383164bcff.png)

**5. Versions:**
 - AL Language: 6.1.397164
 - Business Central: 17.2

**Comment by fvet** [comment]
Caching is one issue, however we encounter the BC client to hang / crash in some scenarios too when closing the Vendor card (leaving the 'Customer Card' in a loading / in progress state)

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by fvet** [comment]
Logged on Collaborate
https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/438331
