### ISSUE TITLE
Request for new event publisher OnAfterCreateCustomerLink in Table5050

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/AL#6452]
After Customer Link has been created in the function **CreateCustomerLink** in Table 5050. i would like to be able to intervene with code, so please add new integration event called OnAfterCreateCustomerLink at the end of the function CreateCustomerLink

Signature
[IntegrationEvent(false, false)]
local procedure OnAfterCreateCustomerLink (var Contact: Record Contact)

**Comment by dtkb** [comment]
wrong repo => https://github.com/microsoft/ALAppExtensions/issues
