### ISSUE TITLE
Add parameter in Event -"OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters"

### ISSUE THREAD

**Issue by manishs-acumencentral** [microsoft/AL#6453]
Hi Team,

This event is published in codeunit 226 "CustEntry-Apply Posted Entries" 
Can you please add one boolean parameter (IsHandled) in event OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters and also some code. i.e. if not IsHandled then execute the below code.

Current
[IntegrationEvent(false, false)]
local procedure OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgerEntry: Record "Cust. Ledger Entry" temporary);
begin
end;

Perposed :
[IntegrationEvent(false, false)]
local procedure OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgerEntry: Record "Cust. Ledger Entry" temporary; var IsHandled: Boolean);
begin
end;

Thanks,
Manish Sinha

**Comment by dtkb** [comment]
wrong repo => https://github.com/microsoft/ALAppExtensions/issues

**Comment by dtkb** [comment]
If someone can remove the off-topic `event-request` label from being selectable, it might help

**Comment by manishs-acumencentral** [comment]
New request submitted:
https://github.com/microsoft/ALAppExtensions/issues/10963
