### ISSUE TITLE
Failed to publish/install extension with error "failed with code UnprocessableEntity. Reason: Input string was not in a correct format."

### ISSUE THREAD

**Issue by dibyanugraha** [microsoft/AL#6455]
**Describe the bug**
Unable to publish/install extension with error "**failed with code UnprocessableEntity. Reason: Input string was not in a correct format.**" Package is successfully created. Any methods of publishing (schemaUpdateMode) - ForceSync or Recreate - yields the same result.

**To Reproduce**
Reproducing the bug is almost impossible without sending the full codes as I have tried with my other extensions, they were successfully published without any error. Just this particular extension.

**Expected behavior**
Expect extension is successfully published without any error.

**Screenshots**
Installing from web yielded this message
![JBPCOWt1FM](https://user-images.githubusercontent.com/11976855/107316668-b60ad280-6acb-11eb-9f3d-a5845ee51f57.png)

While publishing from VSCode yielded this:
![cf3eUdgycv](https://user-images.githubusercontent.com/11976855/107316704-cc189300-6acb-11eb-80d3-fd8951876b43.png)

Latest error from web showed this:
![msedge_bOAb1GtSKT](https://user-images.githubusercontent.com/11976855/107316749-e5b9da80-6acb-11eb-9ba9-da50a8ae7467.png)

**5. Versions:**

 - AL Language: v6.1.397164

 - Business Central: sandbox, v17.3.20469.20653

**Comment by dibyanugraha** [comment]
I'm completely clueless in here what might caused that. Any kind of help, guidance, or hint is welcomed.

**Comment by kalberes** [comment]
Are you using partner telemetry?  Then you can lookup the publish/install errors in the partner telemetry. 
Can you maybe try with other sync options?

**Comment by dibyanugraha** [comment]
As I have mentioned before, I did try all those schemaUpdateMode: Sync, ForceSync, Recreate - all of them failed too. Recreate usually fixes almost all those weird problems but in my case, it's not. And about telemetry, yes I did peek in the Admin panel, there were no records mentioning any kind errors too. Publish, error occurs, wait around for 1-2 minutes, check the telemetry, set around -30 minutes of the troubled environment, none. None of the recorded telemetry mentioned anything about the publishing error. And this error happened to all my sandbox environments - I have 3 sandboxes, all of them failed to publish this extension. I don't know how to trace this error, no clue how submit detailed reports without submitting the entire source code.

**Comment by kalberes** [comment]
Can you share the C:\Users\<you>\.vscode\extensions\<your al version>\bin\EditorServices.log file, after subtracting anything you find personal.
That may contain some hints of what is going on.

**Comment by dibyanugraha** [comment]
I have found the culprit: I tried to add SumIndexFields as new index, and accidentally used "true" as its value where it should be list name of the fields (I forgot to read the docs). Apparently this didn't cause any compilation error in AL compiler thus it proceeds to cause publishing error.

Can we get an error during AL package if this happens next time?

**Comment by kalberes** [comment]
Looks like a bug.  For clarity can you please detail below how exactly your SumIndexFields was added as a Key?

**Comment by dibyanugraha** [comment]
Sure, it is simple as this:
```AL
keys
{
    key(NewIndex; "Amount Excl. VAT (LCY)")
    {
        SumIndexFields = true;
    }
}
```
It passed the compilation and thus created that error.

**Comment by atoader** [comment]
We will need more information to reproduce this. Can you provide a project that reproduces the issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
