### ISSUE TITLE
Confirm() should check AA0131 that message placeholders match parameters

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6456]
**Describe the bug**
`Confirm()` takes a message string that can contain substitutions and a variable number of trailing arguments that will be substituted into it as if by `StrSubstNo()`, but it does not check that the placeholders and their arguments have the same counts/arities like `StrSubstNo()` does and indeed like `Error()` also does fine.

**To Reproduce**
Here I pass three parameters for each message, but the labels only substitute two:

![image](https://user-images.githubusercontent.com/63455896/107496784-a94cb400-6b89-11eb-9a6f-c3140593d273.png)

See that `Confirm()` does not warn, as `StrSubstNo()` and `Error()` _do_. All three should.

**Expected behavior**
warnings in all three cases, and anywhere else that a message string and variadic arguments are substituted

**5. Versions:**
 - AL Language: 6.1.397164

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
