### ISSUE TITLE
Warning on rule AA0072 triggered on app.json file

### ISSUE THREAD

**Issue by titofffffff** [microsoft/AL#6458]
**Describe the bug**
I have an issue with rule AA0072 which is triggered on app.json and I don't understand why
See screen shoot

**To Reproduce**
I don't know.. I can send you my app as example.

**Expected behavior**
Don't have this type of warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/5903546/107419205-ce084380-6b17-11eb-81ba-d6e24dfb7936.png)

**5. Versions:**
 - AL Language: v6.1.397164
 - Business Central: 17.3

**Comment by dtkb** [comment]
According to https://github.com/microsoft/AL/issues/6246 it can be because you have that many codeunits with `TableNo` properties set. Is that the case for you? If so, it's a duplicate.

**Comment by PaulIvan** [comment]
Hi @titofffffff could you try again with the latest version (https://github.com/microsoft/AL#al-developer-preview-builds) ?

**Comment by PaulIvan** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by PaulIvan** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
