### ISSUE TITLE
Intellisense triggers too early for variable types

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#646]
![image](https://user-images.githubusercontent.com/28626283/30164223-0c66ee9a-93dc-11e7-8b71-3fc44e87128f.png)

As you can see, the Txt2AlVariable  contains a space before and after the colon ` : `
If you create a custom variable you type the `CustomVariable :` and at this point (enter the colon sign) you will get the intellisense box.
I think it's better to show the intellisense box after enter a space after the colon for the readability of the variables.

Like this:
![image](https://user-images.githubusercontent.com/28626283/30164252-1f806bf0-93dc-11e7-94e6-bd9c8314b116.png)

**Comment by StanislawStempin** [comment]
We will take a look. It makes sense in this scenario

**Comment by StanislawStempin** [comment]
After further looking into it, we have decided not to make a special case for this. First of all if you press a space after the colon the Intellisense will be closed and re-trigerred in the correct place. Second of all we now have autoformatting which will fix the issue even if you selected a type right after the colon.
