### ISSUE TITLE
PrintOnlyifDetail marked as 'cannot be used for SaaS', although it is employed in Report 4 

### ISSUE THREAD

**Issue by Kowa63** [microsoft/AL#6463]
**Describe the bug**
The attempt to use PrintOnlyIfDetail in one of our reports is marked as 'cannot be used for 'Cloud' development' within a sandbox, even though Report 4 "Detail Trial Balance" does just that.

**To Reproduce**
Procedure PrintOnlyIfDetail yields these results when used within our own report.
![grafik](https://user-images.githubusercontent.com/16236672/107774415-3edd7480-6d3f-11eb-93d0-da419c21907f.png)
![grafik](https://user-images.githubusercontent.com/16236672/107774695-9f6cb180-6d3f-11eb-82fc-128250a68029.png)

Yet Report 4 Detail Trial Balance uses exactly the same method we are trying to employ. 
![grafik](https://user-images.githubusercontent.com/16236672/107774736-af849100-6d3f-11eb-9afa-ad77090c7e70.png)
![grafik](https://user-images.githubusercontent.com/16236672/107774755-b7dccc00-6d3f-11eb-853a-d898630181f8.png)

**Expected behavior**
We expect to be able to use this property in our reports as it is used in Report 4.

**Screenshots**
See above.

**5. Versions:**
 - AL Language:
 - 6.1.397164 
 - Business Central:  -
![grafik](https://user-images.githubusercontent.com/16236672/107778279-2de33200-6d44-11eb-99d8-47cb0a0145cc.png)

**Comment by dtkb** [comment]
> The attempt to use PrintOnlyIfDetail in one of our reports is marked as 'cannot be used for 'Cloud' development'

That sounds crazily wrong!

> even though Report 4 "Detail Trial Balance" does just that.

Standard objects can do OnPrem stuff, otherwise BC would not be implementable as it is.

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions

**Comment by Kowa63** [comment]
New Issue at: https://github.com/microsoft/ALAppExtensions/issues/11353
