### ISSUE TITLE
New account External deployment is not allowed on sandbox tenants in BC by design.

### ISSUE THREAD

**Issue by chrisnrick** [microsoft/AL#6466]
External deployment is not allowed on sandbox tenants in BC by design.
Deployment of extensions on a sandbox is meant to be done via VS Code to allow you to test out/develop your extension in a BC-like environment. 

The external deployment feature is not meant to be used as a method of 'trying out' your extension, but rather as a means of deploying a 'final' product to a live tenant. Once you have finished with the development cycle for your extension, you will need to log into the live production tenant and upload your package from there.

Note: the upload process runs the same 'validation' as can be run from the compiler locally by setting up the PerTenantExtensionCop AL Code Analyzer. 
E.g. adding the following to your settings:
```
"al.codeAnalyzers": [
        "${PerTenantExtensionCop}"
    ]
```

_Originally posted by @HunterFeltman-MSFT in https://github.com/microsoft/AL/issues/2310#issuecomment-391034692_

**Comment by dtkb** [comment]
So what is your issue? Are you asking for the quoted behaviour to be changed? In what way? This is for specific issues, not a knowledgebase.

**Comment by atoader** [comment]
I'll close the issue because it does not follow the template.
