### ISSUE TITLE
adding keyVaultUrls to app.json , breaks publishing

### ISSUE THREAD

**Issue by bgestel** [microsoft/AL#6467]
**Describe the bug**
 noticed that when I add a 
```
"keyVaultUrls": [ 
 "https://*****.vault.azure.net/" 
        ] ,
```
to App.json VSCode isn't able to publish or download symbols anymore.
The output window shows the error :   "Error: No server has been chosen."

packaging and deploying via powershell does work.
the moment you remove keyvaultURLs from app.json everything starts working again.

**To Reproduce**
Steps and to reproduce the behavior:
1. open app.json
2.  add keyVaultUrls
3. try to publish app with AL:publish with or without debugging of try to download symbols
4. the compiler will run and the package will be created but publishing will fail, in case of download symbols  "Error: No server has been chosen." appears in the vscode output window

``` AL Code to reproduce the issue ```

**Expected behavior**
The app is  published to the server

**Screenshots**

**5. Versions:**
BC sandbox 17.2 W1 in a docker container
al version  v6.1.397164 
vs code 1.53.1

**Comment by bgestel** [comment]
some extra information:  publishing and installing the same package via Powershell does work.  So I'm under the impression the issue is only happening in vscode when publishing via the al extension

**Comment by PooyaKharamesh** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
Or
To open a support case, you can:
Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

**Comment by bgestel** [comment]
for future reference for annybody finding this issue.

It was causes by invisible characters in the 

"keyVaultUrls": [ 
 "https://*****.vault.azure.net/" 
        ] ,

part of app.json.

You can solve it by removing all blank spaces
