### ISSUE TITLE
XLIFF file causes error: Cannot find the declaration of element 'xliff'.

### ISSUE THREAD

**Issue by JanGrefe** [microsoft/AL#6468]
**Describe the bug**
XLIFF file in my app is producing the error below:

**cvc-elt.1.a: Cannot find the declaration of element 'xliff'.**

\<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">

When I replace http with https in the above line, it works, but since the xliff is regenerated with each build, I cannot fix the issue that way.

**Screenshots**
Please refer to the attached screenshot
![xliff_error](https://user-images.githubusercontent.com/52327301/108067359-f258a880-7060-11eb-8bac-5efaa0ef247a.png)

**Comment by kalberes** [comment]
This is by design for now.  We could change it though. We have not made a decision yet.
According to the spec: https://www.w3.org/TR/2009/REC-xml-names-20091208/#ns-decl
 "It is not a goal that it be directly usable for retrieval of a schema (if any exists). " (The URL)

**Comment by krajniks** [comment]
This would be solved properly in xsi:schemaLocation. Currently it expect xsd of schema in local folder. If this would be exchanged with url of actual schema xsd found at http://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core-1.2-transitional.xsd, there would be no error. 

Would that change be feasible?

example before:
![image](https://user-images.githubusercontent.com/17533900/114991874-61545100-9e9a-11eb-9c0c-2bae21d58060.png)

example after
![image](https://user-images.githubusercontent.com/17533900/114991910-6c0ee600-9e9a-11eb-9783-27c73a3fc0b3.png)

**Comment by krajniks** [comment]
Every Xml schema validator should throw the same error, as it cannot find the valid schema. If you would copy schema to the Translations folder the error would also go away.

As this is open specification, it should always be available at the known url. why not use it. Is there any security concerns involved? Anything else to consider? @kalberes can this be reopened and reevaluated?

**Comment by Liam-Olivier-Dynetek** [comment]
You can solve that problem by adding an s to the end of "http" making it "https". 
Hope this helps.
