### ISSUE TITLE
Global Translation File do not generates for Enum

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#6469]
**Describe the bug**
While using Features "GenerateCaptions", if we do not put any caption in enum, there nothing in .xlf file

**To Reproduce**
1. Create a simple project, with "features": ["TranslationFile","GenerateCaptions"],
2. Create a Enum like
enum 50100 "MyEnum"
{
    value(0; Customer) { }
    value(1; Vendor) { }
    value(2; Item) { }
}
3. Compile
4. Check .g.xlf file
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-US" target-language="en-US" original="ALProject1">
    <body>
      <group id="body" />
    </body>
  </file>
</xliff>

**Expected behavior**
Excpected trans-unit section for each enum values

**5. Versions:**
 - AL Language: 6.5.413786
 - Business Central: plateforme 17.0.21485.21985 + application 17.4.21491.22066

**Comment by kalberes** [comment]
GenerateCaptions only supports application objects for now.
