### ISSUE TITLE
Suggestion: Add 'Code' Data Type functions like the 'Text; Data Type

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#647]
![image](https://user-images.githubusercontent.com/28626283/30164898-53884114-93de-11e7-9f42-4ed063940ed1.png)

**Comment by Gallimathias** [comment]
I would add the question of char functions to this issue.

![charsuggestion](https://user-images.githubusercontent.com/16351673/30211176-35fb673a-94a0-11e7-8335-4afb0a6aa77a.PNG)

````csharp
            tmpChar.IsControl;
            tmpChar.IsDigit;
            tmpChar.IsLetter;
            tmpChar.IsLetterOrDigit;
            tmpChar.IsLower;
            tmpChar.IsLowSurrogate;
            tmpChar.IsNumber;
            tmpChar.IsPunctuation;
            tmpChar.IsSeparator;
            tmpChar.IsSurrogate;
            tmpChar.IsSurrogatePair;
            tmpChar.IsSymbol;
            tmpChar.IsUpper;
            tmpChar.IsWhiteSpace;
````

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
