### ISSUE TITLE
Global Translation File do not generates for Groups in layout page

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#6470]
**Describe the bug**
While using Features "GenerateCaptions", if we do not put any caption in layout groups, there nothing in .xlf file.

**To Reproduce**
1. Create a simple project, with "features": ["TranslationFile","GenerateCaptions"],
2. Create a Page like
page 50100 "MyCustPage"
{
    SourceTable = Customer;
    Caption = 'My Cust Page';
    PageType = Card;
    UsageCategory = None;

    layout
    {
        area(Content)
        {
            group(General)
            {
                field(Code; Rec."No.")
                {
                    ApplicationArea = All;
                }
            }
        }
    }
}
3. Compile
4. Check .g.xlf

**Expected behavior**
Expected trans-unit section for the group.
May be can not be created if "ShowCaption = false"; but here not the case.

**Screenshots**
![image](https://user-images.githubusercontent.com/30075742/108090711-35277a00-707b-11eb-9044-5417a89538fd.png)

**5. Versions:**
 - AL Language: 6.5.413786
 - Business Central: plateforme 17.0.21485.21985 + application 17.4.21491.22066

**Comment by kalberes** [comment]
GenerateCaptions only supports top level application objects for now.

**Comment by PooyaKharamesh** [comment]
Thank you for reporting this issue. This is a problem that we are aware of and that we have on our backlog. We will use this issue to track this problem on Github.
