### ISSUE TITLE
Al formatter not found - Extension failing to activate per Developer Console

### ISSUE THREAD

**Issue by KellyMarchewa** [microsoft/AL#6471]
**Describe the bug**
I am trying to get started with AL development. I just downloaded the extensions. When attempting to format a .al file, I received a There is no formatter for 'al' files installed. I uninstalled and reinstalled the extension and tried multiple versions (including the latest). Looking at the errors in the Developer Console, I noticed the following: `abstractExtensionService.ts:718 Activating extension 'ms-dynamics-smb.al' failed: ENOENT: no such file or directory, chmod '/home/kelly/.vscode/extensions/ms-dynamics-smb.al-6.5.413786/bin/Microsoft.Dynamics.Nav.EditorServices.Host'.` This file indeed does not exist. 

I also received no prompt to connect the project with a sandbox tenant; something the tutorial (from MS) indicated would happen.

**To Reproduce**
Steps and to reproduce the behavior:
1. Extension downloaded (latest version).
2. Create new AL project using the "AL: Go!" command.
[-1613505329479.log](https://github.com/microsoft/AL/files/5991419/-1613505329479.log)

3. Attempted to format file and received error  message.

**Expected behavior**
I expected the file to format without any issue and to be able to deploy/connect my app to the sandbox tenant.

**Screenshots**

**5. Versions:**

 - AL Language: v6.5.413786

 - Business Central: NA (Never even got to "connect" the extension to the client in any way)

I have attached the log. Far more data than needed, but figured I would include in case there was some conflict with other extensions for some reason. Actual error (above) does not occur until line 590

[-1613505329479.log](https://github.com/microsoft/AL/files/5991427/-1613505329479.log)

EDIT: I am using Linux (Debian 10). I did not see anything that indicated Windows was required for AL development, but was this assumption mistaken?

**Comment by kalberes** [comment]
We do not have official support on Linux at this moment.

**Comment by atoader** [comment]
I will close this issue as it appears to be a Linux specific issue. Please reopen it if you can reproduce it on Windows.
