### ISSUE TITLE
"Go To Symbols in Editor" displays different symbols than "Go To Symbols in Workspace"

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6473]
Link to Microsoft Idea: https://experience.dynamics.com/ideas/idea/?ideaid=495d9f82-d376-eb11-8fed-0003ff45c929

**Describe the bug**
When I am using the "Go To Symbols in Editor" command I can find symbols on procedure level. But when I am using the "Go To Symbols in Workspace" command I can only find symbols on object level. (eg. tables, codeunits, etc.).

**To Reproduce**
Steps and to reproduce the behavior:
1. Open AL solution with at least one procedure
2. Enable the "Go To Symbols in Workspace" command in VS Code
3. Search for any procedure in the "Go To Symbols in Workspace" command.

**Expected behavior**
It want to be able to find every procedure via "Go To Symbols in Workspace".

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7450586/108225582-fa354d00-7133-11eb-83f7-113e2caccff4.png)
![grafik](https://user-images.githubusercontent.com/7450586/108225678-10430d80-7134-11eb-8aa3-43f9db5ff91b.png)

**5. Versions:**

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.5.413786
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by kalberes** [comment]
We do not support the "Go To Symbols in Workspace" yet.

**Comment by dannoe** [comment]
Thank you for the information. Is there an ETA on the feature? It would be pretty useful for navigating big AL solutions or to find suitable library functions.

**Comment by kalberes** [comment]
No ETA for now. Maybe you can also create an entry here that it gets some visibility
![image](https://user-images.githubusercontent.com/12760483/109050959-4b1be700-76da-11eb-858e-21f1490df961.png)

**Comment by dannoe** [comment]
Thank you, I have done that. (see https://experience.dynamics.com/ideas/idea/?ideaid=495d9f82-d376-eb11-8fed-0003ff45c929)

**Comment by PooyaKharamesh** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by dannoe** [comment]
@BazookaMusic I just noticed the changelog regards "Go To Symbol in Workspace". 
You can mark this issue's [idea](https://experience.dynamics.com/ideas/idea/?ideaid=495d9f82-d376-eb11-8fed-0003ff45c929) as completed if you wish.
