### ISSUE TITLE
error AL0185: DotNet 'HttpStatusCode' is missing (macOS)

### ISSUE THREAD

**Issue by ma7eopl** [microsoft/AL#6476]
**Describe the bug**
I can't use DotNet variable on macOS. When I want to package the app I see this error:
error AL0185: DotNet 'HttpStatusCode' is missing
Is any way to resolve this error?

**To Reproduce**
Define DotNet variable

``` HttpStatusCode: DotNet HttpStatusCode;```

**Versions:**
v6.5.413786

**Comment by dtkb** [comment]
Have you installed .Net on the Mac? How/where/what version? Anyway, macOS is unsupported AFAIK.

**Comment by ma7eopl** [comment]
I solved the problem.
I installed the mono and set the path to the assemblies as below
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/4.0-api/
and now I can package the app

**Comment by atoader** [comment]
Hi! macOS is unsupported, but if you want to compile an extension that uses .NET interop, you should point it to a folder containing .NET 4.8 SDK for Windows. The Mono libraries might work, but there might be slight differences as compared to the framework on which the product runs. I'll close this issue as it is outside of the scope of this repository.
