### ISSUE TITLE
CurrPage.Update(false) does not refresh listpage correctly.

### ISSUE THREAD

**Issue by jvak** [microsoft/AL#6478]
**Describe the bug**
The list page does not refresh correctly when using CurrPage.Update(false) if you change the field in code on which the listpage is sorted , e.g. by using custom developed actions on the page like moveup / movedown. It seems that integer/decimal fields in the list are not refreshed, in contrast to other fields. See the screen recording in attachment.
This has been tested on the latest sandbox environment.

**To Reproduce**
Steps and to reproduce the behavior:
Screen recording:

[Edit - General Journals - Dynamics 365 Business Central.zip](https://github.com/microsoft/AL/files/6027834/Edit.-.General.Journals.-.Dynamics.365.Business.Central.zip)

``` AL Code to reproduce the issue ```
Here you can find the page extension for the general journal page with the sorting set and the moveup - movedown actions:

pageextension 71000 "NVT General Journal Ext" extends "General Journal"
{
    actions
    {
        addlast(processing)
        {
            action("NVT MoveUp")
            {
                ApplicationArea = All;
                Caption = 'Up';
                Image = MoveUp;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                begin
                    MoveUp();
                end;
            }
            action("NVT MoveDown")
            {
                ApplicationArea = All;
                Caption = 'Down';
                Image = MoveDown;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                begin
                    MoveDown();
                end;
            }
        }
    }

    trigger OnOpenPage()
    begin
        Rec.SetCurrentKey(Amount);
    end;

    var
        JournalLine: Record "Gen. Journal Line";

    local procedure MoveUp()
    begin
        JournalLine.Copy(Rec);
        JournalLine.Get(Rec."Journal Template Name", Rec."Journal Batch Name", Rec."Line No.");
        if JournalLine.Next(-1) <> 0 then begin
            JournalLine.Amount := JournalLine.Amount + 1;
            JournalLine."Amount (LCY)" := JournalLine."Amount (LCY)" + 1;
            JournalLine.Modify();

            Rec.Amount := Rec.Amount - 1;
            Rec."Amount (LCY)" := Rec."Amount (LCY)" - 1;
            Rec.Modify();

            CurrPage.Update(false);
        end;
    end;

    local procedure MoveDown()
    begin
        JournalLine.Copy(Rec);
        JournalLine.Get(Rec."Journal Template Name", Rec."Journal Batch Name", Rec."Line No.");
        if JournalLine.Next() <> 0 then begin
            JournalLine.Amount := JournalLine.Amount - 1;
            JournalLine."Amount (LCY)" := JournalLine."Amount (LCY)" - 1;
            JournalLine.Modify();

            Rec.Amount := Rec.Amount + 1;
            Rec."Amount (LCY)" := Rec."Amount (LCY)" + 1;
            Rec.Modify();

            CurrPage.Update(false);
        end;
    end;
}

**Expected behavior**
The entire listpage should be correctly refreshed, displaying the correct information in all lines and columns.

**Screenshots**
Initial state before pressing <down> action. List is sorted on <amount> column.
![image](https://user-images.githubusercontent.com/35299582/108823055-39deb780-75c0-11eb-8ad0-e0659235d775.png)

after pressing <down> action:
![image](https://user-images.githubusercontent.com/35299582/108823335-9215b980-75c0-11eb-809e-44aaacf8fca2.png)

After manually focusing on the amount field in the previous line, the amount fields are the correctly refreshed.
![image](https://user-images.githubusercontent.com/35299582/108823459-bd98a400-75c0-11eb-8e27-c8e143ee7ad9.png)

**5. Versions:**

 - AL Language: v6.5.413786

 - Business Central: Latest Sandbox Environment (application version: 17.4.21491.21531 / platform: 17.4)

**Comment by dtkb** [comment]
> It seems that integer/decimal fields in the list are not refreshed, in contrast to other fields.

Do you mean that changing e.g. text fields, such that a different sort order would result, _does_ cause reordering upon `CurrPage.Update()`?

**Comment by jvak** [comment]
@dtkb 
Reordering works fine, only the values in some integer/decimal columns of the previous record are not refreshed correctly until you manually put your cursor in those fields.

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by srinivasbanny** [comment]
@jvak may i know what is the resolution for this ? i am also facing same sort of issue

**Comment by mumarkhann** [comment]
I am facing this issue as well, any solution to this?
