### ISSUE TITLE
AA0211 should error for standard, non-FlowField/Blob passed to SetAutoCalcFields(), etc.

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6479]
This rule correctly catches non-FlowField/-Blob fields passed to `CalcFields()`, but it does not warn for `SetAutoCalcFields()`, instead resulting in a runtime error. It should warn for both, thus stopping developers from publishing a wrong `SetAutoCalcFields()` and only finding out later.

Saying that: if the current diagnosed case is a runtime _error_, why is it only a compile-time _warning_? If that code cannot possibly work at runtime, don't let devs think they can ignore the 'warning', because it will just be transmuted into an error later, thus again wasting our time. That is: make any such attempt to calc a non-flowfield be a compile error

Edit: This should also apply to other places where one can specify `CalcFields`, e.g. in a `Report` `dataitem`. Please ensure that it does.

![image](https://user-images.githubusercontent.com/63455896/108854352-aae19780-75df-11eb-8173-821833031d5d.png)

![image](https://user-images.githubusercontent.com/63455896/108854306-9f8e6c00-75df-11eb-81ed-d33179a281a8.png)

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
