### ISSUE TITLE
Foreign code visible through debugging

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#648]
We just played something with different apps. When debugging through an event in my app, I can see the code from the other app as I jump to that point next. So it is very easy for me to view the source code of other companies.

Is that a feature or a bug?

**Comment by kalberes** [comment]
The plan is that in the future you will only able to debug through (non extension based) code from the base app.

**Comment by StanislawStempin** [comment]
As of December Update each extension can declare if they want to show their code to third parties. More info in the blog post:
https://blogs.msdn.microsoft.com/nav/2017/12/06/nav-development-preview-december-update/
