### ISSUE TITLE
no compile/runtime warning if SetLoadFields()/AddLoadFields() are passed fields of wrong type

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6480]
Passing a field that is not a FlowField or a BLOB to `CalcFields()` is diagnosed by AA0211 as a warning, although (a) it should be an error and (b) said rule does not catch the same in `SetAutoCalcFields()`; see https://github.com/microsoft/AL/issues/6479

In contrast, `SetLoadFields()`/`AddLoadFields()` have no such diagnostic, either at compile- or run-time. They should. If a FlowField or BLOB is passed to them, it gets ignored and not loaded (I've tested). To load such fields requires one of the `*CalcFields()` methods above.

Thus, passing non-normal fields to `*LoadFields()` should be a compile-time error, as it can't possibly achieve anything at runtime, and so someone writing such code either expects the wrong thing from these functions and will be disappointed, or has made a typo. It should be an error rather than a warning for the same reasons; there's no point letting people write no-op code like this.

My other issue linked above asks for the existing warning for `CalcFields()`, as well as being extended to `SetAutoCalcFields()`, also to be an error. In the case of those functions, if the user gets warned or no diagnostic at compile-time, it **does** error at runtime. That seems bad.

![image](https://user-images.githubusercontent.com/63455896/108855808-49222d00-75e1-11eb-9b1b-a25d7270cd9f.png)

**Comment by PooyaKharamesh** [comment]
related to #6479

**Comment by atoader** [comment]
We have reached out to the team owning this feature to ask for guidance.

**Comment by PhDuck** [comment]
Thanks for the issue, I do believe the code analyzer should assist here.
I will need to look into which information we have about the fields, I would expect it not to be too hard to implement.

I'm a bit conflicted if it should be an error or warning, if anyone else has input on this, please voice it.
I will see/hear when we generally report errors versus warnings, since we for a similar API (CalcFields) choose warning, I'm trending towards that.

@atoader please assign to me.

**Comment by NKarolak** [comment]
From what I've read here, I'd say it should be a warning, not an error.

**Comment by atoader** [comment]
We'll take a look at this issue and see how we need to split the issue between bugs and requests for new functionality.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
