### ISSUE TITLE
Variant.IsDictionary() & Variant.IsList() are missing

### ISSUE THREAD

**Issue by TysvdHeuvel** [microsoft/AL#6481]
As discussed on Twitter already. Variant.IsDictionary() and IsList() are missing. For now I'm using JsonArray, but I'd much rather stick with Dictionary and List.

**Comment by dtkb** [comment]
Part of the problem here might be that just knowing it's a container is not enough; to make use of that knowledge, we'd also need to know the type of the elements.

**Comment by TysvdHeuvel** [comment]
Just knowing that it is a container would help a lot already. But, I agree, something like Variant.IsDictionary(Dictionary of [Code[10], Integer]), would be way cooler.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
