### ISSUE TITLE
Price Calculation Issue

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/AL#6482]
Hello, our company prepare NAV addon to BC cloud version for app source. Do we need rewrite sales prices to price calculation? 
Because in many places of the standard code, sales prices have not even been rewritten. Price Calculation Setup is absent. I can enable Price Calculation only with using code (Set boolean to TRUE). 

Sorry, I didn`t find any repo where I can ask this question. 
If I made a mistake with the repository, please tell me where I can ask this question, since the question is quite serious and concerns App Source.

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
