### ISSUE TITLE
TableExtension XXXXX ::They key name 'Key1' is used multiple times in table 'Reservation Entry'.

### ISSUE THREAD

**Issue by bachii1010** [microsoft/AL#6483]
**Describe the bug**
We are getting the above error when we publish our apps in 18.0.
Can anybody let us know what is the best way to solve this issue?
 
Also this is not coming as a warning or error in VSCode when it compiles with vsix file.

**To Reproduce**

**Expected behavior**
we expect the app to be published

**Screenshots**

**5. Versions:**

 - AL Language: 7.0.415152

 - Business Central: 18.0.22441.0

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
