### ISSUE TITLE
FilterGroup(-1) does not work with FlowFields / include them in the WHERE clause

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6486]
**Describe the bug**
Setting filters in group -1 where one or more of the ORd fields is a FlowField does not work (properly).

**To Reproduce**

Run the below. If need be, create a new `Customer` whose `Balance (LCY)` (a FlowField) is `0`.

Click the new `Process`/`Test` action. See that, although we verify that `Balance (LCY)` is `0`, the filter that should mean '`Name` is empty (false) OR `Balance (LCY)` is 0 (true)` does not work: the `FindFirst()` throws an error because no record is found.

Yet... We just verified that it exists.

The resulting error does not acknowledge that any filter was even set on `Balance (LCY)`:
![image](https://user-images.githubusercontent.com/63455896/109033145-3df0ff00-76be-11eb-9513-0b84e36539d5.png)

...whereas if putting multiple Normal fields in `FilterGroup(-1)`, it would recite them all:
![image](https://user-images.githubusercontent.com/63455896/109033301-6973e980-76be-11eb-9a1e-5f21e6ab7e1f.png)

So clearly something is going wrong here, and the FlowField is just being ignored, not ORd.

```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {
            action(Test)
            {
                ApplicationArea = All;
                Caption = 'Test';
                Image = TestDatabase;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;
                ToolTip = 'Run the test.';

                trigger OnAction()
                var
                    Customer: Record Customer;
                begin
                    Rec.TestField("No.");
                    Rec.TestField("Name");
                    Rec.TestField("Balance (LCY)", 0);

                    Customer.SetRange("No.", Rec."No.");

                    Customer.FilterGroup(-1);
                    Customer.SetRange(Name, '');
                    Customer.SetRange("Balance (LCY)", 0);

                    Customer.FindFirst();
                end;
            }
        }
    }
}
```

**Expected behavior**
FlowFields in `FilterGroup(-1)` should be ORd with the other fields. If they are not supported here, that needs to be
- documented,
- a compile-time error so that no one else wastes their time debugging and figuring out a repro for this, and
- ideally fixed later.

**5. Versions:**
 - AL Language: 6.5.413786
 - Business Central: Version: GB Business Central 17.4 (Platform 17.0.21485.22158 + Application 17.4.21491.21531)

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by dtkb** [comment]
Are you saying this clear bug with how AL statements are compiled into SQL code is not present in 18.x? Otherwise it's an on-topic issue and should be reopened.

**Comment by dtkb** [comment]
In the meantime, I've posted this to Yammer/DynamicsNavDev for hopefully relevant attention, and I'll be opening a support request with our partner.

https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1095110187753472

**Comment by dtkb** [comment]
@atoader Can we get a second opinion re: whether this is on-topic? It concerns the compiler not producing correct SQL queries for the code it's given. How is that not related to AL dev?

**Comment by dtkb** [comment]
@atoader Sorry to keep banging on about this, but since I've seen a few bugs wrongly closed lately, I'd like to have a certain 2nd opinion on this. It seems to me that the AL compiler is either generating wrong SQL/logic when FlowFields are filtered in FilterGroup(-1) - or at the minimum this is not supported and shouldn't even compile, or if infeasible to detect at compile time, give a runtime error. How is that not an AL dev issue?

Our partner said they don't think normal partner support channels will do anything with this, as they tested older versions of NAV/BC and it has been like this for a while. That's not a good enough excuse to me! If it's meant to work, it should; if not, it should be diagnosed

**Comment by nicolassaleron** [comment]
I am interested by this topic.

@dtkb : If I get your example, if the selected Rec is the customer no. = 'CASH', then you would expect the sql query to be the one below? Is that right?

```
SELECT *
FROM [MyCompany$Customer$...]
WHERE
	[No_] = 'CASH'
	AND (
		Name = ''
		OR [Balance (LCY)] = 0
	)
```

(where [Balance (LCY)] is replaced by a subquery that computes the flowfield)

**Comment by dtkb** [comment]
Yes, exactly. Thanks for the interest!

I thought I had previously found some cases where ORing FlowFIelds _did_ work, and that it worked if we didn't have a filter in a 'normal' ANDing group... but I couldn't replicate it:

![image](https://user-images.githubusercontent.com/63455896/110767040-b7a3f380-824d-11eb-83e2-7e4cc392f036.png)

I haven't had any luck tracing the SQL queries of any of these yet, but the wrong/inconsistent behaviour is clear anyway, and even the platform states that it has simply ignored the filter, since it doesn't include it in the error msg as it normally would.

**Comment by atoader** [comment]
> @atoader Can we get a second opinion re: whether this is on-topic? It concerns the compiler not producing correct SQL queries for the code it's given. How is that not related to AL dev?

It is not a compiler issue because the compiler does not produce SQL statements, that is the runtime. The compiler validates your AL and then it will emit C# and XML. The runtime will interpret your access to records and emit SQL queries.

**Comment by db-bc** [comment]
I have the below reply from MS. So, it is a known limitation, and they will be fixing the documentation to reflect that, and *maybe* allowing it to work as expected with FlowFields later, for which I'm sure upvotes here can help! -

_**[BC Idea to make this work](https://experience.dynamics.com/ideas/idea/?ideaid=3cac57c6-4706-ec11-b76a-0003ff459e25)**_

***

```none
All you are stating it is true. FILTERGROUP(-1) does not work with FlowFields. 
Let me try to write down the whole story. 
 
The first time it has been reported, it was for NAV 2018 (version 11.x) with the following repro

1.  Import attached page, or create it from text below. 
 
2.  Click "Insert Data" to create 3 records:
"No."  Description  "Identifier Code"
ABC    TEST
TEST   Item 1
XYZ    Item 3           TEST

FILTERGROUP(-1) is supposed to filter across columns, so we want to filter where any of the columns contain TEST. 
So click "Filter Test" which runs the following:
```

```al
SETAUTOCALCFIELDS;
FILTERGROUP(-1);
SearchString := '@*TEST*';
SETFILTER("No.",SearchString);
SETFILTER(Description,SearchString);
SETFILTER("Identifier Code", SearchString); // <-- This filter gets ignored
CurrPage.UPDATE;
IF FINDSET THEN
  REPEAT
    MESSAGE("No.");
  UNTIL NEXT = 0;
FILTERGROUP(0);
```

```none
It will show a MESSAGE for 2 of the item. 
Problem: It will not show the item where "Identifier Code" = TEST, most likely because "Identifier Code" is a flowfield. 
Expected behaviour: It should find all 3 items.

REPRO PAGE
```

```al 
OBJECT Page 99959 Item Identifier
{
  OBJECT-PROPERTIES
  {
    Date=;
    Time=;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    SourceTable=Table27;
    PageType=List;
    ActionList=ACTIONS
    {
      { 6       ;    ;ActionContainer;
                      ActionContainerType=ActionItems }
      { 7       ;1   ;ActionGroup }
      { 8       ;2   ;Action    ;
                      Name=Filter Test;
                      OnAction=BEGIN
                                 SETAUTOCALCFIELDS;
                                 FILTERGROUP(-1);
                                 SearchString := '@*TEST*';
                                 SETFILTER("No.",SearchString);
                                 SETFILTER(Description,SearchString);
                                 SETFILTER("Identifier Code", SearchString);
                                 CurrPage.UPDATE;
                                 IF FINDSET THEN
                                   REPEAT
                                     MESSAGE("No.");
                                   UNTIL NEXT = 0;
                                 FILTERGROUP(0);
                               END;
                                }
      { 9       ;2   ;Action    ;
                      Name=Insert Test data;
                      OnAction=BEGIN
                                 "No." := 'TEST';
                                 Description := 'Item 1';
                                 IF INSERT THEN;
                                 "No." := 'ABC';
                                 Description := 'TEST';
                                 IF INSERT THEN;
                                 ItemIdentifier.Code := 'TEST';
                                 ItemIdentifier."Item No." := 'XYZ';
                                 IF ItemIdentifier.INSERT THEN;
                                 "No." := 'XYZ';
                                 Description := 'Item 3';
                                 "Identifier Code" := 'TEST';
                                 IF INSERT THEN;
                               END;
                                }
    }
  }
  CONTROLS
  {
    { 1   ;0   ;Container ;
                ContainerType=ContentArea }
    { 2   ;1   ;Group     ;
                Name=Group;
                GroupType=Repeater }
    { 3   ;2   ;Field     ;
                SourceExpr="No." }
    { 4   ;2   ;Field     ;
                SourceExpr=Description }
    { 5   ;2   ;Field     ;
                SourceExpr="Identifier Code" }
  }
  CODE
  {
    VAR
      ItemIdentifier@1000 : Record 7704;
      SearchString@1001 : Text;
    BEGIN
    END.
  }
}
```

```none
And this was reported in February 2018 already. 
The final answer from product group was
“Currently searching into flowfields does not work for the QuickFilter search.
There are several complications in supporting that - especially that of performance, as the case insensitive search would perform very poorly and lock up the user's session in cases with semi-large data amounts.
We have slice […] [Search] Improved Search in Client
for this functionality, but it is currently not planned”
 
This means that we are talking, at the moment, of a documentation defect – as you also stated – in relation of FLOWFIELD(-1) behavior. 
What I have done on your behalf, then, is to open a Document Defect to product group in order to have this fully documented in docs.onmicrosft.com. 
Taking out from your suggestions, this is what has been escalated
 
FlowFields in `FilterGroup(-1)` should be ORd with the other fields. If they are not supported here, that needs to be
- documented,
 This is the current TFS entry filed on your behalf as Document Defect
- a compile-time error so that no one else wastes their time debugging and figuring out a repro for this, and
 This was already opt-out by server runtime team since it would require quite some time and refactor (and would be a waste of time if resolved later on)
- ideally fixed later.
 This is related to the IDEA to be voted, together with the internal slice open since version 11.x
 
Stated the above, then, I will keep you posted on the documentation defect and its progress
```
