### ISSUE TITLE
Your program license does not allow you to publish AL project. September update

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#649]
Hi team, 
In your [blog](https://blogs.msdn.microsoft.com/nav/2017/09/07/nav-development-preview-september-update/)  is written

> The developer endpoint on the Dynamics NAV server now performs license checks when publishing AL projects. Developer Preview environments offer a free demo range of 50100-50149. Dynamics 365 for Financials sandboxes have a more permissive license that lets you use range 50000-99999 as well as the 70000000-75000000 range.

When I try to publish my app on US locale, i have error 

> Your program license does not allow you to publish 'App name'

I thought, if we use D365 Sandbox, we can publish in any object range inside 70000000-75000000 without any problems.
Or under `Dynamics 365 for Financials sandboxe` you mean online sandbox, not those that installed in Preview VM?

In such case, where can we get a license for development? Only after submitting the idea and getting object range id? Like in Extensions v1 ?

**Comment by StanislawStempin** [comment]
That's right, we mean the online sandbox. But note that you will still need your own object range to be able to submit the app to AppSource.

The process for getting an ID range is the same as for Extensions V1

**Comment by dkatson** [comment]
ok, But what should I do, If I want to play with making apps in VS Code? 
F.ex. I want to create some app for demo purposes in range 71000000..71000100. And I don't want to upload it on AppSource later. In August Dev VM, I did this without any problems. Now (in September Dev VM) I cannot publish this app, cos I don't have a license.

**Comment by StanislawStempin** [comment]
You can use range 50100 - 50149 for demo development.

**Comment by andrecavalcanti** [comment]
I get the same license error message, then I've changed the range and I get the error below

c:\Users\Administrator\Documents\GitHub\AL\samples\HelloWorld2\HelloWorld.al(6,10): error AL0297: The application object identifier '50100' is not valid. It must be within the allowed range '70000000' - '74999999'.
