### ISSUE TITLE
Error using Enum with List variable

### ISSUE THREAD

**Issue by makuhn** [microsoft/AL#6493]
**Describe the bug**
We ocassionally get following error when installing our app with release pipeline:
```
2021-02-26T02:16:49.6780002Z RulesMgt_ITMod/Cod_LNModIntegrMgt.al(82,32): error AL0133: Argument 1: cannot convert from 'Enum "PB365 LM LN Mod. 
2021-02-26T02:16:49.6782329Z Rule Action"' to 'Enum "PB365 LM LN Mod. Rule Action"'
```
Rerunning the pipeline usually solves the problem. Sometimes we must trigger this multiple times until a run succeeds.

**To Reproduce**
The following code is related to the error.

An Enum variable as well as a list variable for an Enum are declared:
```
    var
        lRulesAction: Enum "PB365 LM LN Mod. Rule Action";
        lCheckList: List Of [Enum "PB365 LM LN Mod. Rule Action"];
```
Code that finally causes the error is adding the Enum variable to list:
```
            if lCheck then
                lCheckList.Add(lRulesAction);
```

**Expected behavior**
The error should not occur.

**5. Versions:**
We actually use Business Central 16.3 platform 16.0.14073.14195

**Comment by atoader** [comment]
Can you check if this issue reproduces on the latest version of the AL development tools? Can you provide a self-contained project and a script to reproduce the issue?

**Comment by makuhn** [comment]
I think AL development tools are not really relevant. Issue occurs when installing the apps via a release pipeline. We have actually two pipelines running for different Business Central versions:
- 17.4 (Platform 17.0.21485.21516 + Application 17.4.21491.21531)
- 16.3 (Platform 16.0.14073.14195 + Application 16.0.12076.0)

The issue arises ocassionally and cannot be reproduced by a script. Both pipelines have 2 stages (2 instances, where the apps are installed) which depend on each other. Sometimes first stage fails, sometimes second stage. There is no pattern recognizable.

**Comment by atoader** [comment]
I suspect that it might be a concurrency issue in the compiler, but from the repro, we do not have sufficient information to debug it.

**Comment by makuhn** [comment]
Well I don't know what additional information I can share with you. I can give you the apps and scripts to setup a release pipeline for installing them. Then you can run the pipeline multiple times until it fails. We can also have a joint session where I can share my screen in order to have together a look at the pipeline etc.

**Comment by makuhn** [comment]
@atoader Any news on this issue?

**Comment by makuhn** [comment]
We get same error run ALValidation via bccontainerhelper for acutal BC version . We run it for 9 different countries. Error occurs for different country version e.g. in first run error occurs for us container, all other countries succeed, in second run error occurs for nl container and all other countries succeed. I can share the log files from the pipeline if necessary.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
