### ISSUE TITLE
Caption ML Problem

### ISSUE THREAD

**Issue by ReneGubler** [Microsoft/AL#65]
Hi

I can't compile objects if I add more than one CaptionML

        field(1;"Code";Code[10])
        {
            CaptionML=ENU='Code';
            CaptionML=DES='Code';            
        }
Is the syntax wrong?

**Comment by StanislawStempin** [comment]
The correct syntax for CaptionML property is:
<MultiLanguageText> ::= <LanguageText> [{ ,<LanguageText>}];
<LanguageText> ::= <LanguageIdOrComment> = <string>
<LanguageIdOrComment> ::= Language3LetterCode | Comment

In this particular case:
    field(1;"Code";Code[10])
    {
        CaptionML=ENU='Code', DES='Code';            
    }
