### ISSUE TITLE
Question: How to access an internal Object for OnPrem scenario?

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#650]
How can I use an object, which I have added by using C/Side? 

Reason:
- AL for customizing most of the changes
and
- C/Side for realizing changes, which are impossible with AL

My internal (On-Prem) Custom Object
![grafik](https://user-images.githubusercontent.com/15800069/30167019-5eb168f2-93e5-11e7-8c2e-5360b7ee0671.png)

My `app.json`:
![grafik](https://user-images.githubusercontent.com/15800069/30166920-0ce13bf6-93e5-11e7-8df6-d6c18da9d046.png)

My Code:
![grafik](https://user-images.githubusercontent.com/15800069/30167102-a5c8a49e-93e5-11e7-8e03-031d651042f2.png)

**Comment by kalberes** [comment]
We have a feature in our backlog to have symbol generation in VsCode reacting to application objects changes in C/SIDE.

**Comment by megel** [comment]
When is this feature available?

**Comment by kalberes** [comment]
I cannot commit on saying when it will be available. We have already been working on it for a while.
