### ISSUE TITLE
Snapshot debugging: Record Filter Value Visible

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/AL#6501]
**Describe the bug**
If you set a breakpoint for a snapshot debugging session you can inspect the variable values on this breakpoint. You see the field vales of a record but no filter values like in normal debugging.

**To Reproduce**
Prepare a snapshot debugging session with breakpoints on specific locations.

**Expected behavior**
Filter Values are visible in the locals variables tab just like in the normal debugging.

**Screenshots**
Snapshot Debugging sessin of a record without Filter sections. At least the SetRecFilter should produce a filter on the No. of the item in this snapshot.
![grafik](https://user-images.githubusercontent.com/46522333/109612893-af063b80-7b30-11eb-8950-5b5b057f9911.png)

**5. Versions:**

 - AL Language: 6.5.413786

 - Business Central: AT Business Central 17.4 (Plattform 17.0.21485.22555 + Anwendung 17.4.21491.21531)

**Comment by kalberes** [comment]
It is more like a request then a bug. We can add it of course but we have to evaluate the "price" it pays to record it on a production NST.  Lets deal with it as a bug for now.

**Comment by NAVFreak** [comment]
No news about this?

**Comment by qutreson** [comment]
This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
