### ISSUE TITLE
PermissionSet Generation - Bug or Feature

### ISSUE THREAD

**Issue by christianurban-faveo** [microsoft/AL#6506]
**Describe the bug**
Using the command "AL: Generate permission set containing current extension objects" a permissionSet.xml is generated containing all object types of the application (TableData, Table, Page, ...). In comparison to that the default microsoft permission sets contain only TableData and all other Object Types with 0. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Visual Studio Code
2. Open an extension folder or workspace
3. Run command "AL: Generate permission set containing current extension objects"
4. Open generated permission set

``` AL Code to reproduce the issue ```

**Expected behavior**
In my opinion the resulting permission set should only contain the TableData and all other ObjectTypes with ObjectId 0.

**Screenshots**
Generated Permission Set:
![image](https://user-images.githubusercontent.com/13030139/109923843-adb74900-7cbf-11eb-89f9-0230332eeb69.png)
Microsoft Default Permission Set ("BASE")
![image](https://user-images.githubusercontent.com/13030139/109923979-e1926e80-7cbf-11eb-88ca-195238c1af14.png)

**5. Versions:**

 - AL Language: 6.1.362735

 - Business Central: 16

**Comment by dtkb** [comment]
What would be the use of generating a permission set that didn't give people the ability to use the pages, codeunits, and reports that actually make tables meaningful...?

**Comment by christianurban-faveo** [comment]
They can use all of the extension objects when the permissions for the other object types like page are generated with objectid 0 (see screenshot from Microsoft Default Permission Set). At the moment the permission set looks like:

<Permission>
      <ObjectID>50530</ObjectID>
      <ObjectType>5</ObjectType>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectID>50500</ObjectID>
      <ObjectType>8</ObjectType>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>

In my opinion it should be:
<Permission>
      <ObjectID>0</ObjectID>
      <ObjectType>5</ObjectType>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectID>0</ObjectID>
      <ObjectType>8</ObjectType>
      <ReadPermission>0</ReadPermission>
      <InsertPermission>0</InsertPermission>
      <ModifyPermission>0</ModifyPermission>
      <DeletePermission>0</DeletePermission>
      <ExecutePermission>1</ExecutePermission>
      <SecurityFilter />
    </Permission>

**Comment by dtkb** [comment]
The point is to generate permissions for the current extension's objects. How does `<ObjectID>0` do that? Won't that in fact give permission to ALL objects, base, current app, and other apps?

**Comment by dtkb** [comment]
Ah, I see. So if the Permission Set has extension Scope, then 0 means 'all objects provided by this extension'? I suppose that makes sense. However, arguably generating XML for all individual object IDs can be handy, as it is a way to get a 'template' that we can then use to copy/paste/alter permissions, e.g. to more quickly create varied sets for different groups.

**Comment by christianurban-faveo** [comment]
Probably a second action would be good to generate only type table data with the tables of the extension and all other object types with id = 0.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
