### ISSUE TITLE
app.json runtime issue, not able to publish

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#6507]
**Describe the bug**
The minimum runtime version for using NavigationPageId and Multiplicity in api pages changed the last month. According to [app.json documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Appjson) the runtime for 17.3 is 6.3 and for 17.4 it is 6.4. So when developing the above api pages, I am targeting 17.3 and 17.4 with their respective runtimes 6.3 or 6.4.
However, when publishing from VSCode, the following error occurs:

[2021-03-04 08:03:32.80] Sending request to https://bc173de:7049/BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default
[2021-03-04 08:03:33.04] The request for path /BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: The runtime version of the extension package is currently set to '6.3'. The runtime version must be set to '6.2' or earlier in the app.json file in order to install the extension package on this server.

**To Reproduce**
1. Install docker container with onprem:17.3.20469.20605-de
2. Create a new app with runtime set to 6.3 (to support NavigationPageId)
3. Add a dependency to "id": "10cb69d9-bc8a-4d27-970a-9e110e9db2a5", "name": "_Exclude_APIV2_", "publisher": "Microsoft", "version": "17.3.0.0"
4. Create an api page for Items, add id, no, description
5. Add field unitOfMeasureId with TableRelation = "Unit of Measure".SystemId;, NavigationPageId = "APIV2 - Units of Measure";
6. Publish

ERROR: The request for path /BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: The runtime version of the extension package is currently set to '6.3'. The runtime version must be set to '6.2' or earlier in the app.json file in order to install the extension package on this server.

**Expected behavior**
Successful publishing and correct runtime checking

**Screenshots**

**5. Versions:**
Using onprem:17.3.20469.20605-de

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.6.425415
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by MODUSCarstenScholling** [comment]
Excuse me!? What is this, if not to "Report a bug in the latest AL compiler / Developer Tools"?
We are blocked to develop/publish apps from VSCode with this issue. So please reopen it!

**Comment by qutreson** [comment]
Re-opening the issue, sorry for the confusion, we are looking into it.

**Comment by qutreson** [comment]
@MODUSCarstenScholling thank you for reporting this issue. It appears indeed that the backward compatibility check done in the server for versions 17.2, 17.3, 17.4 and 17.5 is not correct, leading to some issues deploying extensions or using some features with are available for specific versions (as mentioned here). 

We are working on a HF for it in SaaS and it will be available in docker images too.

**Comment by qutreson** [comment]
This issue should now be fixed and should be deployed soon.

Here are the minimum server/platform versions containing the fix:
- 17.2: 17.0.19353.22854
- 17.3: 17.0.20458.22852
- 17.4: 17.0.21485.22862
- 17.5: 17.0.22463.22853

**Comment by tinfister** [comment]
Do you know when will we able to create docker containers with this hotfix?
I cannot get artifact with mentioned versions for 17.4 and 17.5
![image](https://user-images.githubusercontent.com/29481795/111216345-9a1bb480-85d4-11eb-88f0-b52ea463189e.png)

**Comment by atoader** [comment]
The versions mentioned above are the platform versions. You should be able to see the version of the platform in the Help & Support page.
