### ISSUE TITLE
AL Language Extension v6.6.425415 get an error when loading

### ISSUE THREAD

**Issue by Daniamstutz** [microsoft/AL#6509]
Since the AL Language Update **v6.6.425415**, the error messages appear when starting Visual Studio Code:

* Could not start the language service: [Error: spawn EPERM at ChildProcess.spawn (internal/child_process.js:394:11) at Object.spawn (child_process.js:549:9) at h:\vscode-extension\ms-dynamics-smb.al-6.6.425415\node_modules\vscode-languageclient\lib\main.js:376:40] { errno: 'EPERM', code: 'EPERM', syscall: 'spawn' }

* Couldn't start client AL

This means that the extension is not loaded correctly and does not work.
I have to use the earlier AL Language Extension **v6.5.413786**

**Comment by dtkb** [comment]
dupe of https://github.com/microsoft/AL/issues/6508

**Comment by qutreson** [comment]
Thank you for reporting this issue. Closing it as duplicate of #6508 to keep the discussion in one thread.
