### ISSUE TITLE
Request for External

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/AL#651]
Missed methods from #447
Codeunit 12 : UnapplyCustLedgEntry
Table 5994 : SendProfile
Codeunit 1535 : DeleteApprovalEntries,

**Comment by pmohanakrishna** [comment]
still getting error in build 0.10.13928
Codeunit 12 : UnapplyCustLedgEntry

**Comment by StanislawStempin** [comment]
Have you re-downloaded .app symbol packages from the October Update server?

**Comment by StanislawStempin** [comment]
I have just double checked and all of these methods are External in October Update codebase

**Comment by pmohanakrishna** [comment]
Sorry, is there any command to download the symbols?

**Comment by StanislawStempin** [comment]
You can either delete the existing .app package in the .alpackage folder or press Ctrl + Shift + P and select command AL: Download Symbols

**Comment by pmohanakrishna** [comment]
Thanks.
Downloading new symbols solved.
