### ISSUE TITLE
Edit in Excel failed if property is set with instruction

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/AL#6512]
**Describe the bug**
If I set an instruction in a card-pageextension property and try to edit the field in the "edit in excel" feature an error occurs.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new Pageextension, for example for Customer Card.
2. add an instruction for Editable Property in a field (for example: Rec.Field = "specific Value")
3. publish the app and edit the field in excel with the "edit in excel" feature
4. try to publish the changes from excel to business central

AL Code:
``` 
pageextension 50100 CustomerCardExt extends "Customer Card"
{
    layout
    {
        modify("Phone No.")
        {
            Editable = Rec.Blocked = Rec.Blocked::Ship;
        }
    }
}

```

**Expected behavior**
The field change should be able to be published successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/34675109/109992479-9900a280-7d0b-11eb-83b8-d527d9addf88.png)

**5. Versions:**
 - AL Language: 6.6.425415
 - Business Central: Plattform 17.0.21485.22555, Application 17.4.21491.21531

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
