### ISSUE TITLE
Viewing variables in debug breaks session

### ISSUE THREAD

**Issue by damse60** [microsoft/AL#6514]
**Describe the bug**
I'm running a debugging session on an instance. When I try to view variables in the Run and Debug pane the session terminates with an error:
"Unable to compare operands of type NavOption with Boolean"

I can step through all the code without problems. Only occurs when doing the above.

All other extensions than AL Language and theme are disabled!

**To Reproduce**
1. Start debugging session
2. Step into sub function.
3.  Go to debug pane and choose variables.
4. Click on 

**Expected behavior**
That I can view all relevant variables

**Screenshots**

**5. Versions:**
 - AL Language: 6.6.425415 

 - Business Central: 17.1

**Comment by kalberes** [comment]
Can you please provide a small repro, if possible?

**Comment by damse60** [comment]
Hi

It’s not easy to reproduce as it comes on different places from time to time.

But I’ve made a small screen recording to illustrate.

It’s a BC 17.1 DK with the extension from LS Retail installed.

When I debug it runs fine to begin with as seen. But as I press F11 to step it breaks with the error “Unable to compare operands of type NavOption with Boolean”. If I don’t open the variables window and step through it there is no problem!

Hope this I sufficient.



Hilsen



www.jcd.dk
Arne Damkjer - JCD A/S
Dynamics NAV udvikler
ada@jcd.dk
www.jcd.dk
Systemvej 6, DK-9200 Aalborg SV
Ejby Industrivej 111, DK-2600 Glostrup

Følg os på LinkedIn
Vi deler tips, advarer mod virus og 
giver dig viden, du kan bruge til noget
Telefon+45 70 12 00 03
Døgnsupport  +45 70 12 00 08
Mobil+45 22 600 927
Email: info@jcd.dk


JCD A/S gør opmærksom på, at denne email samt eventuelt
vedhæftede dokumenter kan indeholde fortrolig information, der specifikt er
fremsendt til den oprindelige modtager. Såfremt du modtager denne mail ved en
fejl, beder vi dig anvende svar-funktionen og give afsender besked herom.
Samtidig beder vi dig slette emailen i dit system. Det er forbudt at
videresende, kopiere eller på anden måde gøre emailen tilgængelig for andre. 

Selv om emailen og ethvert vedhæftet bilag efter JCD A/S
overbevisning er fri for virus og fejl, som kan påvirke computeren eller
it-systemet, åbnes denne på modtagerens eget ansvar. JCD A/S siger på forhånd
tak for samarbejde og forståelse vedrørende ovenstående. 

Fra: Kálmán Béres <notifications@github.com>
Sendt: 7. marts 2021 12:19
Til: microsoft/AL <AL@noreply.github.com>
Cc: Arne Damkjer - JCD A/S <ada@jcd.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/AL] Viewing variables in debug breaks session (#6514)


Can you please provide a small repro, if possible?

**Comment by kalberes** [comment]
A recording would also be fine. Just to have a clue of the context it happens.

**Comment by damse60** [comment]
Hi

Just to be sure – I attached the recording to the previous mail. Did you see that?




Hilsen



www.jcd.dk
Arne Damkjer - JCD A/S
Dynamics NAV udvikler
ada@jcd.dk
www.jcd.dk
Systemvej 6, DK-9200 Aalborg SV
Ejby Industrivej 111, DK-2600 Glostrup

Følg os på LinkedIn
Vi deler tips, advarer mod virus og 
giver dig viden, du kan bruge til noget
Telefon+45 70 12 00 03
Døgnsupport  +45 70 12 00 08
Mobil+45 22 600 927
Email: info@jcd.dk


JCD A/S gør opmærksom på, at denne email samt eventuelt
vedhæftede dokumenter kan indeholde fortrolig information, der specifikt er
fremsendt til den oprindelige modtager. Såfremt du modtager denne mail ved en
fejl, beder vi dig anvende svar-funktionen og give afsender besked herom.
Samtidig beder vi dig slette emailen i dit system. Det er forbudt at
videresende, kopiere eller på anden måde gøre emailen tilgængelig for andre. 

Selv om emailen og ethvert vedhæftet bilag efter JCD A/S
overbevisning er fri for virus og fejl, som kan påvirke computeren eller
it-systemet, åbnes denne på modtagerens eget ansvar. JCD A/S siger på forhånd
tak for samarbejde og forståelse vedrørende ovenstående. 

Fra: Kálmán Béres <notifications@github.com>
Sendt: 8. marts 2021 10:43
Til: microsoft/AL <AL@noreply.github.com>
Cc: Arne Damkjer - JCD A/S <ada@jcd.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/AL] Viewing variables in debug breaks session (#6514)


A recording would also be fine. Just to have a clue of the context it happens.

**Comment by kalberes** [comment]
No, probably because I do not receive mails from github.

**Comment by damse60** [comment]
https://user-images.githubusercontent.com/32761466/110432136-08311a80-80af-11eb-9575-891c8f4241d9.mp4

**Comment by damse60** [comment]
Here is the screen recording as promised

**Comment by kalberes** [comment]
thanks

**Comment by nickgoddard777** [comment]
@kalberes Is there any update on this.  I am getting the same issue.  This happens a lot, usually if I open Global Variables.  At the minute I have a breakpoint on line 249 of Item Tracking Lines page, in OnAssisEdit of field Lot No. If I don't open Global Vars I can step through fine, as soon as I expand Global Vars and the next step I make the error appears in the Debug Console and (min is actually Unable to compare operands of type NavDate with Boolean this time, the NavDate bit changes) and the Debugger disappears.  I'm on VSCode 1.67.2 and AL Extension v9.0.615906. BC is 20.1.39764. It has happened lots though on versions since v18
