### ISSUE TITLE
[Event Request] Add OnLookup as an available trigger in a table extension

### ISSUE THREAD

**Issue by complord** [microsoft/AL#6516]
Would like the ability to override/add OnLookup handling to a table field.

Example:

```
tableextension 50100 CustomerExt extends Customer
{
    fields
    {
        modify("Global Dimension 1 Code")
        {
            trigger OnLookup()
            begin
                //use custom lookup
            end;
        }
    }
}
```

The above would replace both the lookup from the TableRelation and base code in the fields's OnLookup trigger.

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.

**Comment by atoader** [comment]
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there.
