### ISSUE TITLE
Request for option to enum data type conversion of field Type Table 951 TimeSheetLine 

### ISSUE THREAD

**Issue by mohit0989** [microsoft/AL#6517]
**Describe the bug**
Request for creation of enum data type for Table 951 "TimeSheetLine" field Type which is currently option type.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to table "Time Sheet Line"
2. Check the field Type which is an option type

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47515024/110286236-9901ea80-800a-11eb-8c49-4f4e73233a69.png)

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by dtkb** [comment]
wrong repo, needs moved to https://github.com/microsoft/ALAppExtensions/issues

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
