### ISSUE TITLE
Request for converting an option data type field to enum data type for Approver Type in Table 1523 Workflow step argument 

### ISSUE THREAD

**Issue by mohit0989** [microsoft/AL#6518]
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release. 

Posting your suggestion to the Business Central Ideas forum will allow other partners to see it and vote on it and it will ensure that the ideas that the community considers most valuable get implemented.
Request for conversion of field "Approver Type" from option data type to enum data type for table 1523 "Workflow step argument"
![Capture](https://user-images.githubusercontent.com/47515024/110286991-d2872580-800b-11eb-9126-b223c9b9008c.JPG)

**Comment by dtkb** [comment]
wrong repo, needs moved to https://github.com/microsoft/ALAppExtensions/issues

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
