### ISSUE TITLE
Request for option to enum data type conversion of "Cross-Reference Type" Table 5717 "Item Cross Reference"

### ISSUE THREAD

**Issue by mohit0989** [microsoft/AL#6519]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
Request for creation of enum data type for field "Cross-Reference Type" Table 5717 "Item Cross Reference" which is currently an option data 
![Capture](https://user-images.githubusercontent.com/47515024/110288636-56daa800-800e-11eb-9dc7-bac3e2e0b2f3.JPG)
type.

**Comment by qutreson** [comment]
Please log an issue to the following repository: https://github.com/Microsoft/ALAppExtensions
