### ISSUE TITLE
No check of duplicate field ID' s

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#652]
Last issue for today :D

I have released two apps that add a field with the same id to the custom table.

Scenario would be customer buys two adaptations as an app from two companies. Both companies implement a field as a side effect of their programming.

Same names don't work, but the same id's are actually allowed. This has to follow a crash. The client can no longer be opened.

![doppelteids](https://user-images.githubusercontent.com/16351673/30168452-b66e2e50-93e9-11e7-8519-5e386373c6f0.PNG)

**Comment by StanislawStempin** [comment]
You should use field IDs that are within your extensions Object ID range. This is checked during AppSource validation process and at some point we will provide a local version of the tool that will let you detect violdations before submitting the app.

**Comment by Gallimathias** [comment]
Ok for apps you use for the app source is ok. But what about individual customizations that were made indivudal for the customer and don't fit into the app source? In case of doubt, there is no review there.

**Comment by StanislawStempin** [comment]
On-Prem these checks are not enforced but we would still recommend all partners to follow the AppSource publishing best practices if they want to avoid these kinds of problems.
