### ISSUE TITLE
Can't overload a procedure with different Text or Code lenght

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/AL#6522]
**Describe the bug**
We are using overload function for get value from Json. Overload function fill table fields and there is problem with possible overload. Is ti possible. So we would like create new overloads for like this:

procedure GetJsonTokenValue(JsonObj: JsonObject; TokenKey: Text; var TextValue: Text) Found: boolean
procedure GetJsonTokenValue(JsonObj: JsonObject; TokenKey: Text; var TextValue: Text[250]) Found: boolean
procedure GetJsonTokenValue(JsonObj: JsonObject; TokenKey: Text; var TextValue: Text[100]) Found: boolean
.
.
.
Visual Studio Code can find different overloads for this (show references number correctly for functions). Problem is that AL compilator raise error that function with same name and parameters exists. Can you allow overloading with different variable length? It realy helps with warnings AA0139.  

**5. Versions:**

 - AL Language: 7.0.420929

 - Business Central:

**Comment by thloke** [comment]
Hi! This is a legitimate improvement request, but it's not a bug. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
