### ISSUE TITLE
should error if Page methods are called with wrong Table type (i.e. not SourceTable)

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6525]
See also https://github.com/microsoft/AL/issues/6438

None of these should compile. But they do, and we only get told at runtime that someone goofed.

I get that the base `Page` object takes generic `var Record: Table` arguments, so at the base level those can't be validated - but it is hopefully possible for specific Pages, which have a specific SourceTable set, to error out if they are passed a Table that is not of the same type.

Please can you consider doing this? It would catch common thinkos and save much time.

I might've missed some methods taking `Record: Table` arguments from my example, in which case, please include all such methods in this fix.

![image](https://user-images.githubusercontent.com/63455896/110925501-2dc25c00-831b-11eb-9c8c-c82046202ebd.png)

**Comment by thloke** [comment]
This is a perfect use case for a new code cop rule. It shouldn't be a compiler error, since syntactically it's correct. Could you add the idea to https://aka.ms/BusinessCentralideas? We'll triage it from there based on the votes it gets.

**Comment by dtkb** [comment]
> It shouldn't be a compiler error, since syntactically it's correct.

I get what you mean, since the method takes a 'base' Table, and a 'derived' Table 'is' one of those... but my PoV is that if something will always cause a runtime error, it can/should be stopped at compile time. I appreciate though that such code analysis is a deep rabbit-hole and hence not a priority versus 100s of other tickets.

Idea submitted: https://experience.dynamics.com/ideas/idea/?ideaid=df8e9c09-3986-eb11-8ced-0003ff45a07d

**Comment by StefanMaron** [comment]
Also see https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/16
