### ISSUE TITLE
Global variable in report not updating value

### ISSUE THREAD

**Issue by matevzpoljanc-spin** [microsoft/AL#6526]
**Describe the bug**
In the code below, we have global Boolean variable. This variable is displayed on request page of the report. Initial value of the global variable is set in OnOpenPage trigger. If user changes value of the field on request page, the variable value does not have this changed value in OnPreDataitem trigger, but it has the value set in OnOpenPage.

**To Reproduce**
Steps and to reproduce the behavior:
1. Minimal code for report:

``` 
report <pick any ID> TestReport
{
    dataset
    {
        dataitem(<anything>;<anything>)
        {

            trigger OnPreDataItem()
            begin
                Message(Format(globalTest));
            end;
        }
    }

    requestpage
    {
        SaveValues = true;

        layout
        {
            area(Content)
            {
                field(TestBoolField; globalTest)
                {
                    ApplicationArea = All;
                }
            }
        }

        trigger OnOpenPage()
        begin
            globalTest := false;
        end;
    }

    var
        globalTest: Boolean;
} 
```

**Expected behavior**
User changes value to true on request page field. When message is shown, it should display value **true** (instead it displays **false**)

**Screenshots**
![image](https://user-images.githubusercontent.com/56061470/110939872-599f0b00-8336-11eb-9ea7-10927245b2fc.png)
![image](https://user-images.githubusercontent.com/56061470/110940104-a97dd200-8336-11eb-89b3-8ecb87cc25bf.png)

**5. Versions:**

 - AL Language: 6.6.425415

 - Business Central: W1 17.0 (Platform 17.0.16974.0 + Application 16.0.11310.0)

**Comment by dannoe** [comment]
Can you try to set the value in the ``OnInitReport`` trigger. I think this behavior was already the case in old NAV.

**Comment by matevzpoljanc-spin** [comment]
If I set values in ```OnInitReport``` trigger it works as expected. Please define _old_ - I have NAV 2016 version where this issue does not arise.

I have temporarily fixed my AL code, but I think this is serious semantic inconsistency with how one would expect the program to behave.

**Comment by dtkb** [comment]
maybe related to https://github.com/microsoft/AL/issues/6535

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
