### ISSUE TITLE
AS0025: Parameter order triggers false positives

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6528]
**Title**
The rule AS0025 falsely triggers when parameters are added to an existing event. 

**Description**
The rule AS0025 should prohibit destructive changes to an already published event. This however triggers also when I make non-destructive changes to an event. Example see below: adding a new parameter at the beginning of the parameter list

**v1.0:**
`local procedure OnWhatever(Content: Record "ZheContent"; var Unit: Record "ZheUnit")`
**v2.0:**
`local procedure OnWhatever(var Header: Record "ZheHeader"; Content: Record "ZheContent"; var Unit: Record "ZheUnit")`

I did not change any of the existing parameters, I just added a new one. If I add the parameter at the end of the event instead, the rule no longer triggers. 
Parameter binding for event subscriptions however does not happen via parameter order, but by name. As such, this should be considered a non-breaking change.

There is an example in the [documentation ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0025-parameterscannotbemodifiedorremovedfromevents#code-examples-not-triggering-the-rule) that explicitly describes that adding parameters is allowed. The example however also adds the parameter at the end.

You should either allow this change (preferred) or at least document it very clearly, that events can only be modified when parameters are added at the end.

**Reason for the rule**
The order of parameters helps with readability of code. It's not that important, but given the above circumstances, I don't see a reason for this rule to trigger on events in the case I have described.

**Bad code sample**
N/A

**Good code sample**
N/A

**Good and bad practices for fixing the rule**
N/A

**Comment by qutreson** [comment]
This issue has been fixed some weeks ago in the latest version of the AL compiler in the VS Code marketplace.
