### ISSUE TITLE
'#pragma warning' is not indented and hinders expand/collapse

### ISSUE THREAD

**Issue by TeusV** [microsoft/AL#6530]
**Describe the bug**
When saving an al file, lines starting with '#pragma warning' are not indented. If you did indent, the indent is removed. Then when expanding/collapsing a code block (such as layout{}), the collapse stops at the '#pragma warning' line. Indentation equal to that of comments would make more sense.

**To Reproduce**
1. On a page, in the layout{} section, add a new line '#pragma warning'
2. Save the file (indents are removed)
3. Collapse the layout{} section

``` AL
page 50000 MyPage
{
    SourceTable = "Sales Header";

    layout
    {
        area(content)
        {
            #pragma warning disable AA0218
            group(General)
            {
                field(No; Rec."No.")
                {
                    ApplicationArea = All;
                }
            }
            #pragma warning restore AA0218
        }
    }
}
```

**Expected behavior**
Indents of '#pragma warning' are treated the same as indents of comments (or, worse but better than now, left alone, like some table relation indents).

**Screenshots**
![uKx1daQScw](https://user-images.githubusercontent.com/36189834/111170345-1ba71e80-85a4-11eb-9011-975e85663e8c.gif)

**5. Versions:**
 - AL Language: 6.6.425415
 - Business Central: W1 17.4 (Platform 17.0.21485.21516 + Application 17.0.16993.0)

**Comment by dtkb** [comment]
This might be inspired by C/C++, where AFAIK the general convention is to keep preprocessor directives in column 0 (I think the leading `#` might even _have_ to be there). But yeah, it's not ideal, especially if it interferes functionally with things like expand/collapse.

**Comment by Ji-Peter** [comment]
> This might be inspired by C/C++, where AFAIK the general convention is to keep preprocessor directives in column 0 (I think the leading `#` might even _have_ to be there). But yeah, it's not ideal, especially if it interferes functionally with things like expand/collapse.

From what I'm reading, this was also something that they reported over at the [vscode/c++ tools by microsoft](https://github.com/microsoft/vscode-cpptools/issues/407) issue #406

**Comment by NKarolak** [comment]
@thloke 
This also impacts regions:
As long as the file is not saved and the pragma is still indented, the region is foldable:
![image](https://user-images.githubusercontent.com/34504100/183416708-89606ef8-8188-49bc-b0e3-82889d97a7b2.png)

And as soon as I save = remove the pragma indentation, the region is broken:
![image](https://user-images.githubusercontent.com/34504100/183416855-e3e14f41-21d0-4d2c-9bc8-36e852caefbd.png)

**Comment by blrobl** [comment]
Hi, we have defined an AL custom code folding, which ignores processor directives as expanding and collapsing anchors. We will keep the processor directives in column 0, as per convention, but they will no longer interfere with the code navigation.

**Comment by fvet** [comment]
@blrobl @JesperSchulz  I tried to give this a spin with the v11.0.748446 vsix insider and got it working (I think) only once using the 'Fold Level 1' action. This showed only the field definition, function signature and [IntegrationEvent(false, false)] as lines, which was (almost) perfect!

However, I can't get it working any longer. Is 'Fold Level 1' the proper action, or should we use different commands?

Until now, we are use regions to fold by region, but if we can use standard folding to only show function names without using regions, that would be great !

PS: When folding on level 1, I always get `[IntegrationEvent(false, false)]` for the events. Any option to show the signature instead?

![image](https://user-images.githubusercontent.com/25268332/218333464-e6a774f4-b424-459b-9f05-49c7b8344dea.png)

**Comment by JesperSchulz** [comment]
I'll let someone from the compiler team answer this one :-)

**Comment by fvet** [comment]
> I'll let someone from the compiler team answer this one :-)

@JesperSchulz  Any hint on who to tag to get some feedback?

**Comment by thloke** [comment]
@blrobl - can you check the feedback above?
