### ISSUE TITLE
open specific view on a page

### ISSUE THREAD

**Issue by SarahBirrer** [microsoft/AL#6531]
**Describe the bug**
Is it possible to open a specific view of a Page? When I set the exact filters on the page, the actual view isn't selected.
![image](https://user-images.githubusercontent.com/48559946/104490474-2dcf0580-55d1-11eb-97cc-0cfae8ff0cdd.png)

![image](https://user-images.githubusercontent.com/48559946/104490584-4c350100-55d1-11eb-9c06-088396ea4d42.png)

Thanks,
Sarah

**To Reproduce**

``` AL Code to reproduce the issue ```

**Screenshots**

**5. Versions:**

 - AL Language: v6.6.425415

 - Business Central: 17.0

**Comment by dtkb** [comment]
I was just wondering this earlier, in the context of `RunPageView` from actions.

It would make sense if we could select views by name, rather than having to painstakingly replicate them with code or properties, and then not getting them shown as selected anyway.

**Comment by thloke** [comment]
Unfortunately we don't have a way to set a predefined view from the page. This will have to be an improvement. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
