### ISSUE TITLE
Rule AA0242 should not warn about primary key fields

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6533]
For the attention of @PhDuck

**Describe the bug**
When working with partial records, primary key fields are automatically included and thus do not need to be mentioned for `SetLoadFields`.
However, CodeCop throws warning AA0242 if you work with primary key field that you didn't include in `SetLoadFields`.

> Field 'xx' is not selected for loading and accessing it may cause a JIT load.

**To Reproduce**
```
    local procedure TestAA0242()
    var
        Item, Item2 : Record Item;
    begin
        Item.SetLoadFields(Description);
        Item.FindFirst();

        Item2."No." := Item."No."; // will generate AA0242
        Item2.Description := Item.Description;
    end;
```

**Expected behavior**
No warning for primary key fields.

**5. Versions:**
 - AL Language: 7.0.420292

**Comment by PhDuck** [comment]
Generally what fields are loaded and not loaded is an implementation detail that may change over time.

However, I cannot see us ever not loading PK and customers will often themselves want to load it. So I think it is alright we disclose this implantation detail.

**Comment by dtkb** [comment]
It is already disclosed in [the documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setloadfields-method)

> It is not necessary to include the following fields, because they are always selected for loading: Primary key, SystemId, and data audit fields (SystemCreatedAt, SystemCreatedBy, SystemModifiedAt, SystemModifiedBy).

**Comment by PhDuck** [comment]
@dtkb Hard to remember what I wrote half a year ago :)

I guess it would be a nice idea to not warn about the ones we deliberately document always will be loaded.

**Comment by dtkb** [comment]
Yeah, it would be very nice! Personally, I tend to explicitly include them in the `SetLoadFields()` call anyway, for the benefit of anyone reading the code later (including my future self) who doesn't know they are already implicitly loaded and thinks I goofed ;-) but assuming since they were documented, they're likely to stay implicit, warning is excessive.
