### ISSUE TITLE
OnLookup/OnAssistEdit triggers not functioning on PageParts with dynamic visibility

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/AL#6534]
**Describe the bug**
On a CardPart (and probably on ListPart) page when dynamic visibility is used to show/hide this part the lookup and assist edit triggers are not responding. The assist edit and lookup buttons are visible next to the corresponding field, but the code is not executed when clicking on them. The same applies if the code is written on the page triggers or table triggers. 

**To Reproduce**
Use the sample code below to reproduce the issue. Run the "Main Page" and use the Action to make the card part visible. Then click on the lookup button next to the "Lookup Field". The code in the trigger of the "Lookup Field" that is to show a simple message is not executed.  

From my investigation on this issue, I found that the cause of this malfunction is the dynamic visibility of the CardPart. When the main page runs the card part visibility is by default "false", then by using the action the visibility changes to true, which makes the card part visible but the lookup actions seem not to be enabled. When the initial visibility of the Card Part is changed to 'true' (e.g. in the OnOpenPage() trigger of the Main Page) and then immediately set to 'false' in the OnAfterGetRecord trigger, for example, then the lookup trigger works as expected. I'm using this as a workaround for the time being and suggest the same for anyone else facing the same issue.

//**** AL Sample Code ****

table 60000 "A Simple Record"
{
    Caption = 'A Simple Record';

    fields
    {
        field(1; Code; Code[10])
        {
            Caption = 'Code';
        }
        field(2; Description; Text[50])
        {
            Caption = 'Description';
        }
        field(3; "Lookup Field"; Code[20])
        {
            Caption = 'Lookup Field';

            trigger OnValidate()
            begin
                Message('Validate triggered from table');
            end;
        }
    }
    keys
    {
        key(PK; Code)
        {
            Clustered = true;
        }
    }

}

page 60000 "Main Page"
{

    Caption = 'Main Page';
    PageType = Document;    

    layout
    {
        area(content)
        {
            part(MainCardPart; "Main Rec Card Part")
            {
                ApplicationArea = All;
                Visible = ShowSubpage;
            }
        }
    }
    actions
    {
        area(Processing)
        {
            action(ShowHideSubPageAction)
            {
                ApplicationArea = All;
                Caption = 'Show Hide Subpage';

                trigger OnAction()
                begin
                    ShowSubpage := not ShowSubpage;
                end;
            }
        }
    }

    var
        ShowSubpage: Boolean;

}

page 60001 "Subpage Part"
{

    Caption = 'Subpage Part';
    PageType = CardPart;
    SourceTable = "A Simple Record";

    layout
    {
        area(content)
        {
            group(General)
            {
                field(Description; Rec.Description)
                {
                    ApplicationArea = All;
                }
                field("Lookup Field"; Rec."Lookup Field")
                {
                    ApplicationArea = All;

                    trigger OnLookup(var Text: Text): Boolean
                    begin
                        Message('Lookup triggered');
                    end;
                }
            }
        }
    }
}

**Expected behavior**
The code on the triggers should be executed. 

**Screenshots**

**5. Versions:**

 - AL Language: v6.6.425415

 - Business Central: Platform 17.0.19353.19730 + Application 17.2.19367.19735

**Comment by thloke** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. This will have to go to the client team, as it relates to the webclient functionality. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible. 

 

To open a support case, you can: 

 

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

 

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
