### ISSUE TITLE
The order of trigers on print and/or preview report in BC17.0

### ISSUE THREAD

**Issue by jacmax** [microsoft/AL#6535]
**Describe the issue**
When the system runs the report the triggers: OnInitReport and OnOpenPage are runed
I use these trigers to initialize default values to variables which are updated as a paramters to run the report
When I choose "print" button the system runs trigger: OnPreReport()
When I choose "preview" button the system runs triggers: OnInitReport() and OnOpenPage() and OnPreReport(), is ok? or I do something worng

The system Version: IT Business Central 17.0 on premise (Platform 17.0.16974.0 + Application 17.0.16993.0)

**Comment by thloke** [comment]
Can you share a repro? "Print" should only run `OnPreReport` and not `OnInitReport` or `OnOpenPage`. `OnInitReport` and `OnOpenPage` should run only when the report is loaded (before the request page is shown)

**Comment by jacmax** [comment]
"Print" is ok, "Preview" is not ok.
"Preview" runs : OnIinitReport, OnOpenPage, OnPreReport
I share an example. "50100.ImpPriceListFullfromHASS.Report.al"

![obraz](https://user-images.githubusercontent.com/16525376/111446139-62b02380-870c-11eb-939e-541cb23916b4.png)
![obraz](https://user-images.githubusercontent.com/16525376/111446242-7a87a780-870c-11eb-9623-034f39d4b4bf.png)


[Test-002.zip](https://github.com/microsoft/AL/files/6155235/Test-002.zip)

**Comment by dtkb** [comment]
maybe related to https://github.com/microsoft/AL/issues/6526

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
