### ISSUE TITLE
AA0072 still warns re argument names in event subscribers, which we can't control

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6536]
https://github.com/microsoft/AL/issues/6181 was closed claiming this is resolved, but it still is not, with AL extension version 6.6.425415:

![image](https://user-images.githubusercontent.com/63455896/111455966-57f68e00-870e-11eb-9b43-d1c4f6b6cd54.png)

We cannot control how you name your event arguments, or whether you get them right according to your own rule!

Moreover, since `Sender` is an automatic argument name, generated by the `IncludeSender` annotation, it _couldn't_ be changed anyway. The same goes for `Rec` and `xRec` in table `On*Event()`, etc.

Warnings shouldn't be thrown for event arguments of fixed names, and nor should they be reported for arguments that could be named 'correctly' but would need changed by the publisher since that is not our problem.

Warnings for our own published events' arguments seem fine, but then warn about those at the declaration of the publisher, not at individual subscribers, since the latter can only work with the names given to them by the former.

Please fix this, so we won't have to spam the code up with `#pragma`s everywhere just to avoid these false positives, while trying to follow AA0072 elsewhere (I guess I'm a masochist).

**Comment by thloke** [comment]
@PaulIvan Can you have a look at this since you closed #6181 ?

**Comment by PaulIvan** [comment]
Hi, @dtkb at the time we fixed #6181 it was for the next major release so please try again with a v.7.x extension

**Comment by dtkb** [comment]
Yes, it seems that as of AL extension 7.1.441584 in VS Code the spurious warnings are not emitted, so thanks!
