### ISSUE TITLE
rdlc' is opened in another application. Close the application to be able to compile.

### ISSUE THREAD

**Issue by kevamer** [microsoft/AL#6537]
**Describe the bug**

'....rdlc' is opened in another application. Close the application to be able to compile.

Until BC17 i could use one rdlc layout for several reports.  For example a Sales Invoice and Sales Credit Memo  can share the same rdlc layout .

Until BC17 this worked with occasionaly the message "'....rdlc' is opened in another application. Close the application to be able to compile."
I think this comes because the dataset in the rdlc is checked with the dataset in the report.  This takes time and isn't waited for by the compiler.

After some time this however worked.

In BC17 i can't do this anymore.

Is there a way to disabled the checking of the dataset in the rdlc or to give the compiler more time to check the rdlc and then go on ?

**To Reproduce**
take 2 reports and giv them the same rdlc layout file

Business Central:  BC 17.4

**Comment by dtkb** [comment]
I reported that duplicate layouts shouldn't be allowed, or should at least be warned, because it's not predictable which AL object 'wins':
https://github.com/microsoft/AL/issues/6401

**Comment by kevamer** [comment]
No,

report1.al  uses layout1.rdlc
report2.al  uses  also layout1.rdlc

Looks to me like correct and predictable

**Comment by dtkb** [comment]
It's not correct and predictable, if the compiler doesn't enforce that the AL objects impose the same datasets on the RDLC - which would probably be prohibitively costly - because in my experience that means that which dataset gets synched to the report is arbitrary. Thus devs who accidentally associated multiple AL reports with the same RDLC layout are in for unwelcome surprises later.

**Comment by kevamer** [comment]
Yeh,  but that you can control.   Create the same dataset and there is no suprise.  When you use this, you know that you should create the same dataset.  I'f you don't its your own fault.    I have 5 reports with different datasets and the same layout.  To me it gives the same posibilities on errors to copy  one default layout to the other 4 reports as to know that the datasets should be equal.

**Comment by BazookaMusic** [comment]
Will be handled with issue #6401
