### ISSUE TITLE
NAV Preview September Release Developer Environment

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/AL#654]
Hello Team,

Today created the VM of NAV September Release and found that NAV runs on Docker.

1. Can anyone help on how to access the database with the developer environment, to check which functions are exposed as global or which events can be subscribed.

2. Is there any way to have the September release to be deployed on local machines, like earlier steps.

Regards,
MAS

**Comment by hgnamvn** [comment]
I also want to mention these questions.

Maybe, Please, MS can provide us a virtual machine as Dynamics 365 for operation (on-premise).

**Comment by Gallimathias** [comment]
I got an answer to the subject in #639

**Comment by freddydk** [comment]
We are working on making the classic development environment available inside the VM. This is needed for the workshops at Directions, which are going to be based on the same setup. So sometime next week, a newly deployed september update will have finsql there as well.
Deploying September update to local box requires docker (which requires win10 or win2016) and it requires access to MS Docker images from our private repository. Shoot me an email and I can send you info on how to get started. Note though - docker comes with a learning curve:-)

**Comment by anwar0206** [comment]
thanks @freddydk, I already have your email on how to access NAV on docker and will definitely try that in the new VM.

It will help us to move forward, if you can provide few answers on the below questions.
1. When an image is pulled and container is running, after shutting down/restarting the VM, the container is stopped and cannot use it again.
2. Is there a way to start/access the same container created earlier?
2. Is there a way to access the Developer environment from the docker for NAV 2017 CU10 and do the changes in the objects and to make those changes saved so next time when the container is accessed we have those changes for us?

**Comment by freddydk** [comment]
1 and 2) 
docker stop/start/restart containername should work
If you remove the container it is gone - and you won't be able to recover anything

3) www.github.com/microsoft/navcontainerhelper contains a number of cmdlets to access stuff inside the container (import/export/compile objects included).
The latest navdeveloperpreview includes a NAV Container Helper prompt.
The latest navdeveloperpreview also makes C/SIDE appear on the desktop for the primary container or any containers created for C/SIDE development via the navcontainerhelper.
