### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MONIMAKER365** [microsoft/AL#6547]
- Issue Type: `Performance`
- Extension Name: `al`
- Extension Version: `6.6.434101`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\jhayp\AppData\Local\Temp\ms-dynamics-smb.al-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atoader** [comment]
Hi! Could you open the issue following the template and provide the requested information?
