### ISSUE TITLE
Al converts field name to field number instead

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#655]
Hello,

I  have converted a table to al some of the fields show the number of the field instead of the field name. Does anyone know why?
 
file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Codeunit%2070018003%20-%20EDI%20Foundation.al'
severity: 'Error'
message: 'The name '"Table No."' does not exist in the current context'
at: '227,23'
source: 'AL'

![image](https://user-images.githubusercontent.com/6551266/30195699-29393a62-9429-11e7-9745-264e207b16cb.png)

![image](https://user-images.githubusercontent.com/6551266/30195684-09e9f5ac-9429-11e7-9199-060408b9032a.png)

Thanks

**Comment by StanislawStempin** [comment]
I'm not sure I understand the issue. All table fields have IDs and it looks correctly in your screenshots.
A potential issue I can think of is that you have some name conflict with 2 symbols named "Table No." and that causes ripple-down errors.
Could you please check that?

**Comment by andrecavalcanti** [comment]
Yes. The IDs is correct. When I go to the table I see the error below, but there is only one field called table no.

file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Table%2070018002%20-%20EDI%20Handler.al'
severity: 'Error'
message: 'A field with name 'Table No.' is already defined'
at: '162,15'
source: 'AL'

**Comment by atoader** [comment]
Is there a global variable with the same name?

**Comment by andrecavalcanti** [comment]
No there is not, but I get the same error on another line, but it is a table relation

file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Table%2070018002%20-%20EDI%20Handler.al'
severity: 'Error'
message: 'A field with name 'Table No.' is already defined'
at: '229,51'
source: 'AL'

![image](https://user-images.githubusercontent.com/6551266/30214225-9c284af4-9479-11e7-811c-a7dffddd6535.png)
