### ISSUE TITLE
Let Users set default vaules for launch.settings

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#6551]
Please include the following with each issue:

**1. Describe the bug**
In /src/services/initializeDebugAdapterService.js 
Let the user to configure (via settings) the default values for the launch.json 
**2. To Reproduce**

``` AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally ```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: Any
- Visual Studio Code: Any
- Business Central: Any
- List of Visual Studio Code extensions that you have installed: 

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by atoader** [comment]
Hi, Stefano! This sounds like a feature request. Shouldn't it go to BCIdeas?

**Comment by stefanoPrimo** [comment]
I think this is borderline:
For me, it is a must-have because the current values rarely are applicable. (by default every BC container made with BcContainerHelper has the server instance as BC and not BC170/BC160 etc..) and due to also MS is moving to containers the "localhost" server is more likely not correct

**Comment by thloke** [comment]
This should go to BCIdeas, since it's a feature request. I agree that it would be nice to have (internally we also always have to change the preset values), but in terms of priority we'd need it to be voted on by the community.
