### ISSUE TITLE
Multiple listparts on a page result in "The view is filtered, and ..." message when entering data

### ISSUE THREAD

**Issue by wdet** [microsoft/AL#6552]
**1. Describe the bug**
We have created a page with two listparts where the second listpart is linked to the first via the provider property.
When we enter data then we receive the message

![image](https://user-images.githubusercontent.com/36985016/112478811-ae01ac00-8d74-11eb-8972-a5f326524897.png)

**2. To Reproduce**

I created a little sample extension: 
[List Part Issue.zip](https://github.com/microsoft/AL/files/6204904/List.Part.Issue.zip)

After publishing the extension, the issue can be reproduced by these steps:
1. Go to 'Header' page.
2. Create some records in the 'Header ListPart' by entering a "Section No." and Description.
3. Select the first record in the 'Header ListPart' and enter an "Item No.".
4. When navigating to the next record the message appears.

**3. Versions:**

- AL Language: v6.6.434101
- Visual Studio Code: 1.54.3
- Business Central: W1 17.5

**Comment by atoader** [comment]
Hi! Could you help us understand why this is an issue with the development tools?

**Comment by fvet** [comment]
Moved to Collaborate
https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/461932
