### ISSUE TITLE
IntelliSense of table keys not in key sequence

### ISSUE THREAD

**Issue by sybrenwille** [microsoft/AL#6554]
**1. Describe the bug**
If you use the intelliSense feature for tables the default key is not in the correct sequence.
The sequenceof the intelliSense is always the fieldno sequence.
However in C/AL it first shows the primary key in its sequence and after that the fields in fieldno sequence.

**2. To Reproduce**
Use for instance table Item Variant.
If you use intelliSense you see field `Code` and then field `Item No.` (based on field no sequence).
However the key is the other way around `Item No.` and then `Code`
Its nice to see this in IntelliSense

**3. Expected behavior**
The behaviour expected is like it was always in C/AL. 
See below screenshot:
![image](https://user-images.githubusercontent.com/38318627/112857707-6ac77600-90b1-11eb-8320-dd6563a37eec.png)

**4. Actual behavior**
The current behaviour is in the wrong order:
![image](https://user-images.githubusercontent.com/38318627/112857770-787cfb80-90b1-11eb-98d7-e169681924ca.png)

**5. Versions:**

- AL Language: v6.6.434101
- Visual Studio Code: 1.54.3
- Business Central: V17

**Comment by dtkb** [comment]
Yeah, it would be preferable to see the PK fields in the order that `Record.Get()` would need them, otherwise we risk thinkoes.

**Comment by PhDuck** [comment]
This has been discussed on Twitter also:
https://twitter.com/jamtpearson/status/1349288256010129411

**Comment by EmilDamsbo** [comment]
In newer versions of the AL Language extension, the primary key fields are labeled in IntelliSense hover text like:
![image](https://user-images.githubusercontent.com/67266681/199501801-95194d8c-003b-4021-9ba5-e1990eb0cb84.png)
