### ISSUE TITLE
Question : How do we publish our extension for more than one country

### ISSUE THREAD

**Issue by AMCJN** [Microsoft/AL#656]
We need to publish our extension for more than one country.
But in the app.json we can only put in one locale.
Is this only used in Visual Studio Code or is it also used
when trying to Publish/Install the extension in a D365 version ?

If so, how can we setup the extension to be able to publish/install
on multiply D365 versions ?

**Comment by StanislawStempin** [comment]
Currently you can only author and publish extensions V2 per one country at a time. We are working on enabling multi-country support. I will use this issue for tracking the work and update once we have a timeline for it.

**Comment by anwar0206** [comment]
We are also in same situation, need to publish our D365 App for more than one country.
@StanislawStempin, can we expect this thing addressed in the next release?

**Comment by StanislawStempin** [comment]
This has been addressed in November Update. More information can be found in: https://blogs.msdn.microsoft.com/nav/2017/11/08/nav-development-preview-november-update/
under section Application Dependency.
