### ISSUE TITLE
AA0242 warns spuriously for Enum/Option fields not loaded, only used to get constant member names

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6560]
**1. Describe the bug**
If `SetLoadFields()` is used to load a list of fields, then subsequently an unloaded field of `Enum` or `Option` type is used purely as a way to lookup a specific constant enumerator value (_not_ from the record itself), AA0242 warns the field is not loaded, _but its value is not used_, so this shouldn't happen.

The workaround is to not use the `[RecordName].[Field Name]::[Enum Member]` syntax, but instead write `Enum::[Enum Name]::[Enum Member]`. But: (a) sometimes that's longer, (b) old code converted from Options to Enums will/can still use the former syntax and shouldn't need changed just for the sake of it (that's `git diff` noise, i.e. bad), and  (c) it shouldn't be a warning in any case as only the literal enumerator is used, not a row's value. Edit: and (d) fields that remain as Option type (not that I'm saying that's good!) give no other (sane) way to specify the enumerator value of interest... etc.

This is my third bug about AA0242 in a single day of using it. Could it maybe have been tested a bit better internally, before pushing it out to developers?

**2. To Reproduce**
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    procedure Foo()
    var
        Customer: Record Customer;
    begin
        Customer.SetLoadFields("No.");
        Customer.FindSet();

        repeat
            TestBlocked(Customer."No.", Customer.Blocked::" ");
        until Customer.Next() = 0;
    end;

    local procedure TestBlocked(CustomerNo: Code[20]; CustomerBlocked: Enum "Customer Blocked")
    var
        Customer: Record Customer;
    begin
        Customer.SetLoadFields(Blocked);
        Customer.Get(CustomerNo);
        Customer.Testfield(Blocked, CustomerBlocked);
    end;
}
```

**3. Expected behavior**
The field's value is not used; it is only used as a way to specify one of the enumeration members. Therefore, the value is not needed, and I shouldn't be warned about JITing it.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/63455896/113308702-562bed80-92fe-11eb-952f-e265aae8d0d8.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.0
- Business Central: 17.5

**Comment by PhDuck** [comment]
@qutreson please assign this to me, I have a fix ready.

@dtkb Thanks for reporting the bug(s), we are always trying to improve, if you find more bugs regarding this rule, please open more issues and tag me in them :)

**Comment by dtkb** [comment]
@PhDuck Thanks for working on it!

This also occurs for other non-value accesses to fields such as `FieldCaption("Field Name")`. Will/can your fix cover that too, or do I need to open another issue?

example:
![screenshot of VS Code showing the code `YieldForecast.FieldCaption("Customer No.")` causing a diagnostic that the field "is not selected for loading and accessing it may cause a JIT load"](https://user-images.githubusercontent.com/63455896/113745736-77754b00-96fd-11eb-8492-4cd2a4700ecb.png)

**Comment by PhDuck** [comment]
@dtkb Can you please open a new issue, I have already submitted a fix for the original content of this issue. So the item will soon be closed.

Also if you, or other, have more methods that don't actually trigger a loading of the field, please also add them.

**Comment by dtkb** [comment]
@PhDuck: OK, here is the other one for many other methods causing false positives: https://github.com/microsoft/AL/issues/6565

and a bonus for you :-P https://github.com/microsoft/AL/issues/6564

**Comment by PhDuck** [comment]
@atoader this has been fixed, we can close this issue.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24292 and VS Code Extension Version 8.0.446271. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
