### ISSUE TITLE
Cannot publish app in BC18 DK RTM OnPrem container - Unsupported symbol type 393316

### ISSUE THREAD

**Issue by kasperdj** [microsoft/AL#6562]
Please include the following with each issue:

**1. Describe the bug**
I am trying to install our Cloud & Licensing App (that works on BC15, 16 and 17) but fails on my brand new BC18 OnPrem Container with a strange error: **Publish-NavApp : Unsupported symbol type 393316**

**2. To Reproduce**

Try to publish an app to the same version:
![image](https://user-images.githubusercontent.com/54669593/113681439-40ce0f00-96c2-11eb-8b31-ba13664a3fc0.png)

![image](https://user-images.githubusercontent.com/54669593/113681454-462b5980-96c2-11eb-9f02-eae70a8cb2d1.png)

**3. Expected behavior**
That my Cloud & Licensing app is successfully installed

**4. Actual behavior**
Publish-NAVApp fails with error text: **Unsupported symbol type 393316**

**5. Versions:**

- AL Language:
- Visual Studio Code: 1.55.0
- AL Compiler: 7.1.441584
- Business Central: 18 RTM DK (DK Business Central 18.0 (Platform 18.0.22893.23773 + Application 18.0.23013.23795)
- List of Visual Studio Code extensions that you have installed: None, trying to install the first one.

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [Not relevant ] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
With which BC version was the runtime package created?  I am asking because of the [Limitations](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages#limitations) of runtime packages:

> Runtime packages are guaranteed to work only if published to a platform with the same version as the one where they were produced.

**Comment by kasperdj** [comment]
The runtime app was created on BC17. I will test the same app, just signed to see if that works

**Comment by kasperdj** [comment]
It works then the same app is only signed
