### ISSUE TITLE
AA0242 warns for non-value uses of fields: FieldNo(), FieldName(), GetFilter(), etc.

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6565]
**1. Describe the bug**
The title says it all. I already have a bug for Option/Enum member names ([link](https://github.com/microsoft/AL/issues/6560#issuecomment-814258829)), but PhDuck requested a new one, so here it is.

I included the fields I had time to think of... Please check for other non-value-using accesses of record fields that exist and fix them all at the same time, if possible!

**2. To Reproduce**
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
        i: Integer;
        t: Text;
    begin
        Customer.SetLoadFields("No.");
        Customer.FindFirst();
        i := Customer.FieldNo(Name);
        t := Customer.FieldCaption("Name 2");
        t := Customer.FieldName("Post Code");
        t := Customer.GetRangeMin("Search Name");
        t := Customer.GetRangeMax(Address);
        t := Customer.GetFilter("Address 2");
        Customer.CopyFilter(City, Customer.County);
    end;
}
```

**3. Expected behavior**
No warnings for any of those calls because they don't use field values, only metadata or filters. So no record/field/values needs to be loaded, and the warnings are wrong.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/63455896/113834418-b8637300-9782-11eb-8ee6-d843c433f3bd.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55
- Business Central: 17.5
- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/63455896/113707797-55b59d00-96d8-11eb-90ef-f627b52763a9.png)

**Comment by dtkb** [comment]
Hopefully the analyser has, or can be given, access to knowledge whether a given 'naming' of a field actually refers to its value or not, in which case this could be nice and simple?

**Comment by PhDuck** [comment]
@dtkb I'm not sure we actually know that at this step, we have a list of methods that are just ignored :( but expanding on it should be trivial.

@qutreson please assign to me.

**Comment by PhDuck** [comment]
@atoader this has been fixed, we can close this issue.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24292 and VS Code Extension Version 8.0.446271. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
