### ISSUE TITLE
AL Language Extension 7.x Triggers Invalid Function ID Errors

### ISSUE THREAD

**Issue by bernalfr** [microsoft/AL#6566]
**1. Describe the bug**
The following type of error is presented when invoking certain functions from extension/app code:

_Function ID nnn was called.  The object with ID nnn does not have a member with that ID._

![screenshot01](https://user-images.githubusercontent.com/35543556/113948688-b1605300-97ca-11eb-86e1-444e3a228055.png)

The error occurs when a call is made from code in one app (App A) to a function that exists in a separate app (App B).  App B is a dependency of App A.

Both apps compile and publish successfully from VS Code.  The error only appears within BC14, BC15, and BC16 sessions (Windows Client, Modern Client, and SOAP).  The apps have the same runtime version (for the targeted BC platform) specified in the app.json file.

The error surfaced after installing the AL Language extension for VS Code included in a container image with an Insider build of BC18.  The version of the language extension was 7.0.420929.  This week, in an effort to troubleshoot the cause, it was uninstalled and replaced with the current version from the Extension Marketplace (7.1.441584).  Unfortunately, that did not address the problem.  Removing that version of the language extension and installing an older one in its place -- in this case, one included with the RTM build of BC17 (6.0.338496) -- did away with the errors after re-publishing the apps.

**2. To Reproduce**

The error is triggered by statements similar to the one below, which call functions in a dependency:

![screenshot02](https://user-images.githubusercontent.com/35543556/113948770-e66ca580-97ca-11eb-9e21-b2e9cbb6f8eb.png)

Perhaps a similar scenario would be:

1/ Install version 7.x of the AL Language extension

2/ Create app: "App B"
* create a codeunit with a function that requires the parameter: "Item: Record Item"

3/ Create app: "App A"
* specify "App B" as a dependency
* create a page extension that adds an action to the Items list page (P31) and call the function in the codeunit from "App B"

4/ Publish the apps to an on-prem instance of BC14, BC15, or BC16

**3. Expected behavior**

The function call should be completed without error.

**4. Actual behavior**

The following error is presented:
_Function ID nnn was called.  The object with ID nnn does not have a member with that ID._

![screenshot01](https://user-images.githubusercontent.com/35543556/113948688-b1605300-97ca-11eb-86e1-444e3a228055.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.0
- Business Central: NA Business Central 16.0 (Platform 16.0.11233.12061 + Application 16.0.12076.0)
- List of Visual Studio Code extensions that you have installed:
>* AL Language
>* AL Object Designer
>* Cobalt2 Theme Official
>* GitLens — Git supercharged
>* Insert GUID

**Comment by bernalfr** [comment]
I referred to the following bug report:

https://github.com/microsoft/AL/issues/6448

The version of the AL Language extension that was mentioned as containing a fix (7.0.411812) is earlier than the versions that, in my case, resulted in a similar problem (7.0.420929 and 7.1.441584).

**Comment by atoader** [comment]
We'll take a look at this right away. Can you provide some sample code to reproduce the issue?

**Comment by bernalfr** [comment]
Hi, Alexandru.

Sorry, for the delay in getting back...  Included here are two basic apps; one has a dependency on the other.  It was possible to duplicate the error with them.

[BrokenApp.zip](https://github.com/microsoft/AL/files/6289066/BrokenApp.zip)

These are the extensions that are installed in my VS Code environment:

![Screenshot01](https://user-images.githubusercontent.com/35543556/114254096-aa704680-996a-11eb-827c-2b769455d9fa.png)


The version of the AL Language that was used to publish the apps:

![Screenshot02](https://user-images.githubusercontent.com/35543556/114254109-beb44380-996a-11eb-9405-1fe0e147d208.png)


The version of Business Central that the apps were published to:

![Screenshot03](https://user-images.githubusercontent.com/35543556/114254119-d12e7d00-996a-11eb-92cd-fe283c9bf956.png)


The modified page object where one can invoke the function that triggers the error:

![Screenshot04](https://user-images.githubusercontent.com/35543556/114254142-f1f6d280-996a-11eb-9d5e-f05778d3529b.png)


The resulting error:

![Screenshot05](https://user-images.githubusercontent.com/35543556/114254191-1f438080-996b-11eb-850f-0c3c4f89f5a6.png)


After installing an older version of the language extension, the function presented the expected result:

![Screenshot06](https://user-images.githubusercontent.com/35543556/114254237-6893d000-996b-11eb-85fe-101fee033a4b.png)

![Screenshot07](https://user-images.githubusercontent.com/35543556/114254259-85300800-996b-11eb-928e-c1df5a42ab28.png)


After doing some fiddling around, I found that changing the parameter type for the function in App B from BigText to Text -- or removing it altogether -- also got rid of the problem.  It seems that function calls cannot include BigText values.

This problem occurs in BC14 through BC16.  I have not encountered it in BC17 or BC18... so far.

**Comment by Ratmaniac82** [comment]
Same problem here! Any news?

**Comment by bernalfr** [comment]
Was it possible to verify and confirm that this is an issue?  The error is still raised with code compiled with the current version of the AL Language extension (v.7.2.475273).

**Comment by thpeder** [comment]
Hi @bernalfr,
We have had fixes in this area, so please upgrade your server to the latest in the major version you are using and try publish + install the apps once again.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
