### ISSUE TITLE
Require Handled Boolean to check/update Customer's Bill-to Customer No. while creating Sales Invoice From Job Planning Lines

### ISSUE THREAD

**Issue by sandeepchapte** [microsoft/AL#6567]
Require Handled Boolean to check/update Customer's Bill-to Customer No. while creating Sales Invoice From Job Planning Lines.
Below is Object and image is for refrance.

Objetct : **codeunit 1002 "Job Create-Invoice"**
Function: **CreateSalesHeader**

![image](https://user-images.githubusercontent.com/36148210/113982095-fbe2dd80-9865-11eb-8536-19aae4b064d0.png)

**Comment by dtkb** [comment]
wrong repo; post at https://github.com/microsoft/ALAppExtensions/issues but with more info including how the event publisher should be declared and how it should be emitted/called
