### ISSUE TITLE
implicit with warning & inherited field caption

### ISSUE THREAD

**Issue by sarocker** [microsoft/AL#6571]
When I add Rec. to the source exception on a page, the UI does not show the field caption specified on the source table, but if I skip adding Rec., I get the warning (AL0604) "Use of implicit 'with' will be removed in the future."

Get warning:
```
                field(name; name)
                {
                    ApplicationArea = All;
                }

```
Empty caption on the UI when page is shown:
```
                field(name; Rec.name)
                {
                    ApplicationArea = All;
                }

```
I tested on BC140 Web Client and RTC, BC170, BC180 and on SaaS sandbox. The above symptom is experienced in all cases.

When I add Caption to the page field, the caption is shown on UI:
```
                field(name; Rec.name)
                {
                    ApplicationArea = All;
                    Caption = 'Name';
                }

```
I would like to use the table specified field caption without any compiler warning.

**Comment by atoader** [comment]
We will close this issue because it does not follow the template.
