### ISSUE TITLE
OnInstallPerCompany Insert Permission Error

### ISSUE THREAD

**Issue by lktraser** [microsoft/AL#6573]
**1. Describe the bug**
When the OnInstallAppPerCompany tries to insert data into a table that is owned by the app being installed. This behavior changed in BC18 from BC17. It only happens in BC18 saas environments. I cannot replicate this in local environments and installing the app through the extension page in the client works without a problem. It seems something in this trigger happens out of order. 

**2. To Reproduce**
``` 
table 70000 "Demo Table"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;
            AutoIncrement = true;
        }
    }

    keys
    {
        key(Key1; MyField)
        {
            Clustered = true;
        }
    }
}

codeunit 70000 "Demo Codeunit"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    var
        DemoTable: Record "Demo Table";
    begin
        DemoTable.MyField := 0;
        DemoTable.Insert(true);
    end;
}
```

There is nothing besides this in the app and I have generated a PermissionSet through VSCode. The problem occurs whenever I publish such an app to a BC18 saas environment either through powershell or directly from VSCode.

**3. Expected behavior**
The Insert should run fine as it did in BC17.

**4. Actual behavior**

An error is thrown saying that I do not have the necessary permissions. Which doesn't make sense since I'm SUPER in this environment. Also the fact that the app installs just fine indicates that I do have the permissions.

```
The request for path /v2.0/***/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Die Installation der Erweiterung „InstallDemo“ von „Default publisher“ (Version „1.0.0.0“) für Tenant „***“ und Unternehmen „***“ war aufgrund des Fehlers „Sie verfügen nicht über die folgenden Berechtigungen für TableData Demo Table: Insert.

Details über Ihre Berechtigungen finden Sie auf der Seite 'Effektive Berechtigungen'. Wenn Sie ein Problem melden möchten, beziehen Sie sich auf die folgende Serversitzungs-ID: '1783'.“ und AL-StackTrace „
"Demo Codeunit"(CodeUnit 70000).OnInstallAppPerCompany line 5 - InstallDemo by Default publisher
""Extension Triggers""(CodeUnit 2000000010).OnInstallAppPerCompany line 2
“ nicht möglich.
```
**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.1
- Business Central: 18.0.23013.24140

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
