### ISSUE TITLE
Translations are not working

### ISSUE THREAD

**Issue by RCORELLA** [microsoft/AL#6574]
Hi,

I have an issue with the translation in Business Central 17.5 Saas.

**1. Describe the bug**
I choose the right language in the configuration (Spanish International 3082).

Theorically, all the menu must be in Spanish because the xlf is correct.  

![image](https://user-images.githubusercontent.com/23438653/114524014-23122400-9c45-11eb-8c53-9886f2935dce.png)

I have an extension with a role center and in the menu, as you can see in the picture, part of the menu is in English and part in Spanish.  The Xliff file is correct with the [es-ES] language for all the captions in the role center.  

I put in the app.json the [SupportedLocals] option.

Some idea about this.

Thanks,

Roberto

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
