### ISSUE TITLE
Table 1003 - Add parameters in the event OnBeforeFindPriceAndDiscount

### ISSUE THREAD

**Issue by rswaldia** [microsoft/AL#6575]
Request for Adding parameter "Rec" and "xRec" in event OnBeforeFindPriceAndDiscount in function FindPriceAndDiscount.

OnBeforeFindPriceAndDiscount(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; CalledByFieldNo: Integer; var IsHandled: Boolean); //two New parameters Rec and xRec with type var.

**Comment by dtkb** [comment]
wrong repo, you want https://github.com/microsoft/ALAppExtensions/issues

**Comment by dtkb** [comment]
since you reposted there, please close this one 👍 
https://github.com/microsoft/ALAppExtensions/issues/12007
