### ISSUE TITLE
AL Debugger: Error Message will not been shown

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6576]
**1. Describe the bug**
Compared to the Windows Client Debugger, the AL Debugger does not displays an error message when an error occurs.

**Comment by kalberes** [comment]
If you set breakOnError to true in a launch.json the debugger will break on the error and you should see the AL exception message in the variable windows.

**Comment by kalberes** [comment]
Ok, this is a bug we are missing the error message. I was under the idea that we expose that.

**Comment by mjmatthiesen** [comment]
I often run it twice. Once run through to get the error message, the second time to actually step through from there.

**Comment by PeterBizz** [comment]
I have multiple issues with the break on error functionality. 
1. the error message is not shown anywhere in the debugger ( and GetLastErrorMessage etc. functions cannot be used in Variable window)  
2. very often also the breakpoint (current code line) is not visible and the callstack is empty, i.s.o. showing the error in the client a number of "invisible steps"  need to performed ( pressing F10 multiple times) until the control is back in the Client. 
2.a. same situation is when the Step Over (F10)  is executed after the line with the ERROR(xx) is shown with callstack.
![image](https://user-images.githubusercontent.com/16479136/124129759-62028980-da7e-11eb-9e12-aef685581657.png)

**Comment by kalberes** [comment]
the second issue could be caused by having wrong local symbols compared to how code looks on the server, or that you hit a frame with showmycode false.

**Comment by DanielGoehler** [comment]
Hi @JesperSchulz, where can I try this out? BC 19.0.28135.0 with AL Language Extension 8.0.487599 doesn't show the error message in the VScode.

**Comment by JesperSchulz** [comment]
@kalberes, that question is for you ;-)
