### ISSUE TITLE
The output of the last report is handled only, if multiple reports are executed without a request page within the same transaction.

### ISSUE THREAD

**Issue by InnoNavSupport** [microsoft/AL#6578]
**1. Describe the bug**
If more than one report without a request page is executed within the same transaction, then the result of the last report is returned only. The print output of all other reports is ignored.

**2. To Reproduce**
1. Write a piece of code which execute more than one report without a request page.
2. Execute the code / action

_Code example:_
``` 
pageextension 50101 "My Customer List Ext" extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {
            action(TestPrintWithoutConfirm)
            {
                Caption = 'Test Printing - without confirm';
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                var
                    SalesInvoiceHeader: Record "Sales Invoice Header";
                    SalesShipmentHeader: Record "Sales Shipment Header";
                begin
                    SalesInvoiceHeader.FindFirst();
                    SalesInvoiceHeader.SetRecFilter();
                    SalesInvoiceHeader.PrintRecords(false);

                    SalesShipmentHeader.FindLast();
                    SalesShipmentHeader.SetRecFilter();
                    SalesShipmentHeader.PrintRecords(false);

                    Message('Done');
                end;
            }
            action(TestPrintWithConfirm)
            {
                Caption = 'Test Printing - with confirm';
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                var
                    SalesInvoiceHeader: Record "Sales Invoice Header";
                    SalesShipmentHeader: Record "Sales Shipment Header";
                begin
                    SalesInvoiceHeader.FindFirst();
                    SalesInvoiceHeader.SetRecFilter();
                    SalesInvoiceHeader.PrintRecords(false);

                    if Confirm('This confirm message separates the report calls and leads to both reports being executed correctly.') then;

                    SalesShipmentHeader.FindLast();
                    SalesShipmentHeader.SetRecFilter();
                    SalesShipmentHeader.PrintRecords(false);

                    Message('Done');
                end;
            }
        }
    }
}
```

**3. Expected behavior**
Both reports should be downloaded / printed as pdf or the chosen printer.

**4. Actual behavior**
Only the output of the last report executed is downloaded / printed.

_Example:_
Result TestPrintWithoutConfirm:
    The pdf of the last report (Sales Shipment) executed is downloaded / printed only. The first (Sales Invoice) is missing.
    ![image](https://user-images.githubusercontent.com/62563638/114557191-b78e7d80-9c69-11eb-99d6-41fbf81999c4.png)

Result TestPrintWithConfirm:
Step 1: As soon as the confirm message appears, the pdf of the first report (Sales Invoice) is downloaded / printed.
    ![image](https://user-images.githubusercontent.com/62563638/114558142-a98d2c80-9c6a-11eb-861b-7ff20fae96af.png)

Step 2: After submitting the confirm message, the second report (Sales Shipment) is also downloaded / printed successfully.
    ![image](https://user-images.githubusercontent.com/62563638/114558196-ba3da280-9c6a-11eb-88f1-52311b815078.png)

An Interruption of the code fixes the behaviour, but of course it is not a solution in any case.
For example a post & print functionallity which prints some additional documents like general terms.

**5. Versions:**

- AL Language: 
v7.1.441584
- Visual Studio Code: 
1.55.1
- Business Central: 
BC170 CU2 (Dynamics.365.BC.19735.CH)
- List of Visual Studio Code extensions that you have installed:
AL Language

**Comment by NKarolak** [comment]
This is no AL bug, but a browser restriction.
See the purple box in this article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-run-method#remarks

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
