### ISSUE TITLE
Could not download reference symbols

### ISSUE THREAD

**Issue by szapataq** [microsoft/AL#6580]
**Hi, i want to compile the helloWorld.al file but the following error appears when i try to do so.**

The request for path /v2.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2021-04-16 11:37:57.81] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

This is my app.json file:
app.json:

![image](https://user-images.githubusercontent.com/55293526/115073978-aee2b500-9ebe-11eb-9788-a285a52ae176.png)

And this is my Launch.json file:
launch.json
![image](https://user-images.githubusercontent.com/55293526/115073846-82c73400-9ebe-11eb-969f-cd40048fbb38.png)

**These are the steps i have followed before getting the error:**
1. I'm logged in correctly with my account in D365 BC.
2. I installed vscode and the AL extension.
3. I configured the telemetry settings.
4. I created a new project using AL:GO! I chose the last version and the sandbox enviroment .

please help, thanks for reading this

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
