### ISSUE TITLE
Al CodeCop Analyzer does not show error for rule AA0008

### ISSUE THREAD

**Issue by ViggoVll** [microsoft/AL#6581]
**1. Describe the bug**
When compiling a piece of code whit the rule AA00008 broken, the problems tab does not show it as an error or underlines it as an error.

**2. To Reproduce**
1. Create a table
2. Create a procedure
3. Write Rec.IsTemp and pick the "IsTemporary" intelisens suggestion
4. It does not write the () at the end and the CodeCop Analyzer does not show it as an error

    local procedure TestAA00008()
    begin
        If Rec.IsTemporary then
            exit;
    end;

**3. Expected behavior**
I expected the CodeCop Analyzer to show this as an warning or an error, because this breaks a rule that is setup for code in the Microsoft AppSource standard.

**4. Actual behavior**
The Warning is not show and some intelisens suggestions does not insert the () at the end even when it is show in the preview of the function.
![image](https://user-images.githubusercontent.com/82797917/115192435-17ae7500-a0eb-11eb-80e8-55d7417bbc3f.png)

![image](https://user-images.githubusercontent.com/82797917/115193219-277a8900-a0ec-11eb-97e5-cf506ae1531d.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.2
- Business Central: 15.4
- List of Visual Studio Code extensions that you have installed:
1. Al CodeActions
2. AL Extension Pack
3. AL Language
4. AZ AL Dev Tools/AL Code Outline
5. GitLens
6. Jira And Bitbucket
7. Night Owl
8. PowerShell
9. Rest Cilent
10. TODO Highlight
11. Todo Tree
12. waldo's CRS AL language Extension
13. YAML

**Comment by dtkb** [comment]
The warning's name is AA0008, just three zeroes.

related:
* https://github.com/microsoft/AL/issues/6356
* https://github.com/microsoft/AL/issues/6357
* https://github.com/microsoft/AL/issues/6365

**Comment by thloke** [comment]
@ViggoVll  - does this reproduce on the latest version of the VSIX?

**Comment by NKarolak** [comment]
@thloke I've just tested the above-mentioned example with AL Language 9.3.646020:
Neither the parenthesis are inserted by intellisense, nor warning AA0008 is shown. So 100% reproduced.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
