### ISSUE TITLE
Wrong indentation level of `repeat`/`until` loop directly under `case` option label

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6582]
I'd expect to write and see something like this:

```al
codeunit 50100 Test
{
    trigger OnRun()
    var
        Customer: Record Customer;
    begin
        Customer.FindSet();

        case true of
            true:
                repeat
                    Message(Customer.Name);
                until Customer.Next() = 0;
        end;
    end;
}
```

but the autoformatter changes it to this:

![image](https://user-images.githubusercontent.com/63455896/115214783-c4dcb980-a0fa-11eb-80c1-20e2a7bac71f.png)

That makes no sense.

The bug seems only to affect `repeat`, and not manifest if some other `if` condition or a redundant `begin`/`end` are added:
![image](https://user-images.githubusercontent.com/63455896/115214950-eb9af000-a0fa-11eb-9da8-d8cd7388649b.png)

VS Code 1.55.2

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.1.441584
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by bernalfr** [comment]
This formatting issue also applies to code in IF... THEN BEGIN... END statements:

![Screen Shot 2022-06-23 at 16 01 21](https://user-images.githubusercontent.com/35543556/175431977-ef26e690-5a26-4402-9e47-1ef9691983a2.png)

This is whilst running AL Language extension v.9.3.642746.

**Comment by dnpb** [comment]
I have never seen that. Did it just start in a new version?

**Comment by geertsj** [comment]
I have the same problem:

![image](https://user-images.githubusercontent.com/46344013/175500069-3f0e3d33-6e58-4444-8465-c6526eddbb77.png)

Please solve this quick!!
If this remains we cant use Visual Studio Code anymore (mayby Notepad++ in the meantime)

**Comment by NKarolak** [comment]
@geertsj If this behavior is new, then you can also downgrade the AL Language extension to a working version.

**Comment by geertsj** [comment]
@NKarolak I have downgraded to v9.2.639332. But I restart VSC this extension is autonatically upgraded to v9.3.642746. How can I skip that?

**Comment by NKarolak** [comment]
That's weird. So far, it has always worked for me.
Did you downgrade that way?
![image](https://user-images.githubusercontent.com/34504100/175504984-66b80119-429d-4ca0-97da-7de870cb9269.png)

**Comment by geertsj** [comment]
@NKarolak  I have found a setting like this:

![image](https://user-images.githubusercontent.com/46344013/175506467-5eaf6ffe-622f-4e14-9585-a5214737223b.png)

**Comment by geertsj** [comment]
Or check your: c:\Users\<username>\AppData\Roaming\Code\User\settings.json

"extensions.autoCheckUpdates": false

**Comment by NKarolak** [comment]
BTW are you running the latest version of VS Code? Mine is 1.68.1

**Comment by geertsj** [comment]
Mine is version: 1.68.1

**Comment by geertsj** [comment]
If you do not set:

"extensions.autoCheckUpdates": false

(or it is true) thenwhen you starts VSC or restarts the estension AL Language is automatically updated from v9.2.639332 to v9.3.642746. Normally no problem but in this case the version should stay v9.2.639332 while this problem is not solved by MS.

**Comment by bernalfr** [comment]
I am using VSC 1.68.1.  I rolled back the AL Language extension to v.9.0.615906 (for additional reasons).  Code formatting works fine in that build.

One can also control the way that extensions are updated from the Extensions panel:

![Untitled](https://user-images.githubusercontent.com/35543556/175562920-aa3610c8-ddc9-4e74-a252-90d5b3b2e079.png)

**Comment by markborges** [comment]
So, this issue from April 2021 has been accepted 4 days ago, and it broke the situation even more...?

I followed the tips above from @NKarolak and I rolled back to version 9.2.639332 from 1 week ago, and now this is back to normal.

Hopefully this will be fixed soon, and not in Aug 2023.

**Comment by geertsj** [comment]
@markborges Indeed, we are a week further and Microsoft still hasn't released a hotfix for this extension "AL Language". I think this is a major issue (all over the world?).

**Comment by bernalfr** [comment]
@geertsj:
At least one has the option to roll back to a prior version as a stopgap.

**Comment by CptBlaubart** [comment]
@geertsj @markborges @bernalfr @NKarolak they rolled out an update 22hrs ago. Looks like fixed to me.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42990 and VS Code Extension Version 10.0.645962. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
