### ISSUE TITLE
Run-AlPipeline: AppSourceCop Error for PageExtension with obsolete Action

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#6583]
We are running AppSourceCop tests based on the CI/CD example and the `Run-AlPipeline` function, loading the latest released version as previous App.

Switching to BC18 we successfully removed obsolete functions (allowed for Major upgrade).

Our solutions is now divided into a W1 and DE Localization part within BC18.
We moved a Page Extension from our german BC17 solution to the BC18 DE Localization App.

To avoid a breaking change we marked the (only) action in the pageextension in BC17 as Obsolete.
(we cannot mark the pageextension itself as obsolete).

if we now run  `Run-AlPipeline` the routines fails during compilation:

_[error]The 'PageExtension' with ID '5043122' and name 'BET SR Delivery Reminder' was found in the previous version, but is missing in the current extension. This will break dependent extensions._

```
pageextension 5043122 "BET SR Delivery Reminder" extends "Delivery Reminder"
{
    actions
    {
        addafter("Co&mment")
        {
            action("BET SR Page Ext. Text Line Docs")
            {
                ApplicationArea = All;
                Caption = 'Document Texts';
                Image = ViewComments;
                ObsoleteState = Pending;
                ObsoleteReason = 'Action will be moved to localization extension for W1 compatibility';
                ObsoleteTag = '29.0';
                ToolTip = 'Document Texts.', Comment = 'Auto-Generated en-US=Document Texts.|de-DE=Belegtexte.';
                Visible = StandardReportsVisible;

                trigger OnAction()
                var
                    StandardReportsFunctions: Codeunit "BET SR Report Functions";
                begin
                    StandardReportsFunctions.OpenCommentLines(Rec);
                end;
            }
        }
    }
    var
        [InDataSet]
        StandardReportsVisible: Boolean;

    trigger OnOpenPage()
    var
        GranuleManagement: Codeunit "BET GRN Granule Management";
    begin
        StandardReportsVisible := GranuleManagement.CheckGranuleActive(Enum::"BET GRN Granule"::SR);
    end;
}
```

**Comment by qutreson** [comment]
@ralf-escher, closing this issue as it is now being tracked by #6803 which has some discussion on the thread.
