### ISSUE TITLE
OnBeforeConfirmDownloadShipmentAlsoQst(IsHandled);

### ISSUE THREAD

**Issue by Sleina** [microsoft/AL#6587]
Please include the following with each issue:

**1. Describe the bug**
Hi

In BC I would like to hide the Dialog which asks to download the shipment document after we use post and send.
![image](https://user-images.githubusercontent.com/55833917/115558190-c650e200-a2b2-11eb-96ff-167eeb4b591f.png)

Right now there is no integration event which allows me to hide this Dialog.

**2. To Reproduce**

Go to Sales Order
Create new Sales Order
Post and Send
Ship and Invoice
-> after the posting information the following Dialog pops up:
You can also download the Sales - Shipment document now. Alternatively, you can access it from the Posted Sales Shipments window later.\\Do you want to download the Sales - Shipment document now?
Yes/No

1. Go to 'Codeunit 80 Sales-Post'
2. _"if not ConfirmManagement.GetResponseOrDefault(DownloadShipmentAlsoQst, true)"_
begin
                        OnSendSalesDocument(Invoice and Ship, SuppressCommit);
                        if Invoice then begin
                            SalesInvHeader.Get("Last Posting No.");
                            SalesInvHeader.SetRecFilter;
                            SalesInvHeader.SendProfile(DocumentSendingProfile);
                        end;
                        if Ship and Invoice and not OfficeManagement.IsAvailable then
                            if not ConfirmManagement.GetResponseOrDefault(DownloadShipmentAlsoQst, true) then
                                exit;
                        if Ship then begin
                            SalesShipmentHeader.Get("Last Shipping No.");
                            SalesShipmentHeader.SetRecFilter;
                            SalesShipmentHeader.SendProfile(DocumentSendingProfile);
                        end;
                    end;
**3. Expected behavior**
An Integration Event in order to hide the DownloadShipmentAlsoQst Dialog or Workaround.

**5. Versions:**

- AL Language: v7.1.441584
- Visual Studio Code: March 2021 (version 1.55)
- Business Central: 17.5.22499.22680

**Comment by dtkb** [comment]
wrong repo; you want https://github.com/microsoft/ALAppExtensions/issues

**Comment by qutreson** [comment]
Closing this issue as it should be logged for the ALAppExtensions repo
