### ISSUE TITLE
Objects not showing in package files when object of type Profile is added

### ISSUE THREAD

**Issue by mhenricus** [microsoft/AL#6589]
- AL Extension Version: v8.0.440987

- Server Version: 
Version: W1 19.0 (Platform 18.0.24349.0 + Application 19.0.24591.0)
Azure AD tenant: (blank), Environment: Sandbox (Sandbox)

Scenario: Create a new project with AL: Go! and download symbols
A list of objects in the app files are visible:
![image](https://user-images.githubusercontent.com/69308907/115692863-a9261d00-a35f-11eb-98ba-28b6d7fbbbf6.png)

Build the solution. The objects in the package are also visible:
![image](https://user-images.githubusercontent.com/69308907/115692996-c824af00-a35f-11eb-8e07-094a1edca450.png)

Add a Profile object to the solution
![image](https://user-images.githubusercontent.com/69308907/115693206-01f5b580-a360-11eb-993a-7c22fd36dd1e.png)

Now the objects in the base app package file (and the other app files) are not listed anymore!?
![image](https://user-images.githubusercontent.com/69308907/115693282-12a62b80-a360-11eb-8e5a-60c0e72ff37d.png)

**Comment by qutreson** [comment]
Hi @mhenricus, the object designer view is not provided by the AL Language extension for Visual Studio Code. Do you have other extensions installed?

This seems to be an issue for the [AL Object Designer extension](https://marketplace.visualstudio.com/items?itemName=martonsagi.al-object-designer).

**Comment by mhenricus** [comment]
Sorry @qutreson , I thought it was part of the AL Extension. It is the 'AZ AL Dev Tools/AL Code Outline' extension that has this functionality and seems to have this issue. So, I reported the issue there. https://github.com/anzwdev/al-code-outline/issues/234
