### ISSUE TITLE
Add Length property to Text type

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#659]
It would also be cool if you could pass the length prop of the underlying string up in NAVText. Then you don't have to use StrLen all the time.

![length](https://user-images.githubusercontent.com/16351673/30211639-1df72ef6-94a2-11e7-98ef-6892f7346810.PNG)

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
