### ISSUE TITLE
String overflow in BC v18.0.23795 OnPrem with Spanish Permission Sets descriptions

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#6591]
**1. Describe the bug**
In the last Spanish OnPrem version we can't open Permission Set Page because there is this ERROR:

![image](https://user-images.githubusercontent.com/5801847/115969995-0f699600-a540-11eb-853c-5928d6511613.png)

**2. To Reproduce**
Try to open de Pemission Set Page

**3. Expected behavior**
No Errors with descriptions length.

**4. Actual behavior**
Some descriptions in this table are longer than the maximum field length.

**5. Versions:**
v18.0.23795 OnPrem Spanish

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
