### ISSUE TITLE
A member of type RequestPageExtension with name 'RequestPageExtension' is already defined in ReportExtension (AL0155)

### ISSUE THREAD

**Issue by christian-clausen** [microsoft/AL#6592]
**1. Describe the bug**

I have three apps, M1, M2, and M3 with dependencies as follows

- M2 -> M1
- M3 -> M1
- M3 -> M2

Report and extensions:

- M1 defines Report1 with a RequestPage
- M2 extends Report1 and also the RequestPage
- M3 extends Report1 and also the RequestPage

In this setup I get the following following problem reported on the RequestPage of the report extention in M3:
```
A member of type RequestPageExtension with name 'RequestPageExtension' is already defined in ReportExtension 'Report1Extension' by the extension 'M2 by Statical (1.0.0.0)'.AL(AL0155)
```
Additionally, I get a compilation error when the request page in M3 references a control in the requestpage of M2:
```
The control 'Label2' is not found in the target 'RequestOptionsPage'
```

**2. To Reproduce**

1. Unzip [repro.zip](https://github.com/microsoft/AL/files/6375269/repro.zip)
2. Open workspace file with VS Code
3. Compile

**3. Expected behavior**
I would expect no errors reported and compilation to succeed. For normal pages, it is possible to extend and extended page, so it seems to be a bug that the same cannot be done for request pages.

**4. Actual behavior**
Compilation error:
```
Microsoft (R) AL Compiler version 7.1.6.48380
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'M2' containing '1' files at '9:49:28.72'.

c:\tmp\repro\M2\M2-code.al(8,22): error AL0270: The control 'Label1' is not found in the target 'RequestOptionsPage'

Compilation ended at '9:49:28.104'.

Error: The package could not be created.
```

Also compilation error:

```
The control 'Label2' is not found in the target 'RequestOptionsPage'
```

**5. Versions:**

- AL Language: v7.1.441584
- Visual Studio Code:
- Version: 1.55.2 (system setup)
- Business Central: 18
- List of Visual Studio Code extensions that you have installed:
  - AZ AL Dev Tools/AL Code Outline
  - Marddown PDF
  - vscode-position
  - waldo's CRS AL Language Extension 

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
This is a known bug with workspaces that's on our radar, which addresses the duplicate request page issue.

I suspect the same underlying workspace issue to also be at fault for the label issue. If I compile the apps separately, publish, and download symbols it works.

**Comment by nndobrev** [comment]
The issue is fixed and the bugfix will be available with the next minor.
