### ISSUE TITLE
AL0667: Replacement for RestoreArchiveData

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/AL#6593]
Is there a new method for replacing RestoreArchiveData? 

I'm a little confused as the standard documentation for upgrading extensions continues to reference this function.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions

'RestoreArchiveData' is being deprecated in the versions: '6.0' or greater. The features related to data migration from V1 to V2 extensions are being deprecated. This warning will become an error in a future release.AL(AL0667)

**Comment by atoader** [comment]
We need to update the documentation. What do you use RestoreArchiveData for? What are you trying to achieve?

**Comment by TimothyWatkins** [comment]
Nothing more than retaining the data from our custom tables in "embed" upgrades. I understand this function is specifically for V1 to V2 but is there otherwise no specific code we need to have to make sure data from custom tables are retained during an upgrade?

**Comment by atoader** [comment]
Data is always retained for V2 extensions. The only case where data is removed is if you uninstall the extension and specify -DoNotSaveData or Sync-NavApp -Mode Clean.

**Comment by TimothyWatkins** [comment]
Thanks, I'll remove any reference we have to this function.
