### ISSUE TITLE
C# Compilation Error For Method Overload with Different Interfaces

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6594]
Hi,

We've got two overloads for a method taking different interfaces:

procedure SelectInterface(var InterfaceOne: Interface "Interface One")

procedure SelectInterface(var InterfaceTwo: Interface "Interface Two")

AL compiles, but I get a C# compilation error when trying to execute the code. The callstack is massive but includes "The type 'Codeunit2014410' already contains a definition for 'SelectInterface_Scope_850733594."

I haven't tested whether this is important but both of the interfaces are implemented by the same enum.

**Comment by atoader** [comment]
Could you provide a project to reproduce the issue and the version of the product that you are using?

**Comment by jimmymcp** [comment]
Hi Alex,

Please see https://github.com/jimmymcp/al-issue-6594

There is a new action on the Customer List page "TestInterfaceOverload" which repros the error. When you run that action the web client falls over and a bunch of errors about C# compilation are put into the event log.

**Comment by EmilDamsbo** [comment]
Not reproducible on the latest versions of BC and AL extension. This was fixed along with #6924.
