### ISSUE TITLE
Upgradation from CAL to AL Dataclassification property is missing

### ISSUE THREAD

**Issue by mohit0989** [microsoft/AL#6595]
Please include the following with each issue:

**1. Describe the bug**
When we are upgrading CAL(BC 14) to AL (BC 17), Dataclassification property is only coming for fields which has Dataclassification:ToBeClassified. The other value i.e Dataclassification:CustomerContent is missing. Shouldn't it should fetch from CAL Version ? or Is it not mandatory to put this property on every field of the extension. 

**2. To Reproduce**

1. When we convert from CAL to AL, we follow the standard microsoft steps and the same scripts which are provided in the below link:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool

``` AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally ```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**2. Expected behavior**
Dataclassification:ToBeClassified should automatically be placed in upgraded AL files. 
Dataclassification is only coming for fields which are not ToBeClassified. 

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:Dynamics.365.BC.20605.DE.DVD.zip
- Visual Studio Code:1.55.2
- Business Central:Dynamics.365.BC.Spring2019.29537.DE.DVD.zip
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by qutreson** [comment]
Closing this issue as we are working on focusing the activity in this repository on addressing issues related to the AL development tools. As this issue appears to require changes across multiple areas of our product, and requires changes on older versions of the product (since the txt2al is not shipped anymore in the latest releases), we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
