### ISSUE TITLE
Issue with Field named "Code"

### ISSUE THREAD

**Issue by ReneGubler** [Microsoft/AL#66]
Hi

I created a new simple table like this:

`
table 70001000 "Poison Class"
{
    captionML = ENU='Poison Class';
    DataPerCompany = true;

    fields
    {
        field(1;"Code";Code[10])
        {
            CaptionML=ENU='Code';
           // CaptionML=DES='Code';
        }
        field(2;Description;Text[50])
        {
            Captionml=ENU='Description';
           // Captionml=DES='Beschreibung';
        }
    }
    keys
    {
        key(1;PrimaryKey;"Code")
        {
            Clustered=TRUE;
        }
        key(2;SecondaryKey;Description)
        {
            Clustered=False;
        }
    }
}`

The I added a page

``
page 70001000 "Poison Classes"
{
    PageType=List;
    SourceTable="Poison Class";
    layout
    {
        area(content)
        {
            repeater(Steps) 
            {
                field("Code";"Code"){}
                field(Description;Description){}
            }
        }
    }
}
``

Sometimes VS don't know the field "Code". I tried it a couple of times. After I changed the name to "No" it worked. Then I rechanged it back to "Code". Very strange, now it works and I can't repro it in the same project. But when I create a new project and do the same steps I end in the same error.

**Comment by StanislawStempin** [comment]
This was a bug in the incremental parsing. It is fixed in the upcoming update.
