### ISSUE TITLE
XmlDocument doesn't seem to recognize ISO-8859-1 as a valid encoding

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#660]
When I set the encoding on an XmlDocument to ISO-8859-1 and then write the document to an OutStream, the encoding has been changed to UTF-8 and additional Unicode characters are written to the beginning of the stream. We communicate with web services that either don't understand Unicode, need the encoding set to ISO-8859-1, or don't want an XML declaration at all.

**Comment by atoader** [comment]
The XmlDocument is an in-memory data structure. It doesn't have an encoding until it is written to a stream, and then, it adopts the encoding of the stream. 
Could you please provide a C# snippet that does what you need the AL code to do? It would help greatly in designing a behavior that suits your needs.

**Comment by jcooper01** [comment]
OK, so our xml handling/communication code is pretty complex, and I'm trying to boil it down to something that will demonstrate the issue. I've been able to reproduce the first part (the encoding not sticking), but I'm having trouble demonstrating the extra Unicode characters (but it does happen in our app). Here's the first issue:

page 50100 PageName
{
    PageType = List;

    layout
    {
        area(content)
        {
        }
        area(factboxes)
        {
        }
    }

    actions
    {
        area(processing)
        {
            action(Send)
            {
                ApplicationArea=Basic,Suite;
                Promoted=true;
                trigger OnAction();
                var 
                    WebRequest : HttpClient;
                    Content : HttpContent;
                    Response : HttpResponseMessage;
                    TempBlob : Record TempBlob temporary;
                    OStream : OutStream;
                    IStream : InStream;
                    Txt : Text;
                    XmlDoc : XmlDocument;
                    Text001 : TextConst ENU='<?xml version="1.0" encoding="ISO-8859-1"?><Test></Test>';
                begin
                    
                    XmlDocument.ReadFrom(Text001, XmlDoc);
                    TempBlob.Insert;
                    TempBlob.Blob.CreateOutStream(OStream, TextEncoding::Windows);
                    XmlDoc.WriteTo(OStream);
                    TempBlob.Modify;
                    TempBlob.CalcFields(Blob);
                    TempBlob.Blob.CreateInStream(IStream);

                    Content.WriteFrom(IStream);
                    WebRequest.Post('https://requestb.in/149nifk1', Content, Response);

                end;
            }
        }
    }
}


You can see the results here: https://requestb.in/149nifk1?inspect

In out app, we get results like this (note the extra characters before the XML declaration):
Ù<?xml version="1.0" encoding="utf-8" ?><Test></Test>

When that happens, the remote service doesn't consider the request to be valid XML and returns an error.

**Comment by atoader** [comment]
Thanks! I understand the issue as far as the AL implementation is concerned. 
Could you please write a short snippet in C# where you create a valid request to this web service in the encoding of your choice. I will investigate in depth tomorrow and try to find a workaround.

**Comment by jcooper01** [comment]
The DotNet method is proprietary, so I just sent it to your email address on your GitHub profile.
