### ISSUE TITLE
[TableType = Temporary] AL(AA0237) should not be raised when variable is prefixed with Temp

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/AL#6602]
**1. Describe the bug**
The warning "The name of non temporary variables <myTemporaryTableRecord> must not be prefixed with Temp.AL(AA0237)" is raised even if the referenced to the record is a table with **TableType** property as **Temporary**.

**2. To Reproduce**

- Create a table with Temporary as TableType
- In a procedure, create a variable referencing the created table, prefix the name of the variable with "Temp" like _TempMyTable_
- The warning is raised.

```
table 50100 MyTable
{
    DataClassification = SystemMetadata;
    TableType = Temporary;

    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(Key1; MyField)
        {
            Clustered = true;
        }
    }
}

codeunit 50100 MyCodeunit
{
    local procedure MyProcedure()
    var
        // CodeCop analyzer enabled
        TempMyTable: Record MyTable; // < Warning here
    begin

    end;
}

```
![image](https://user-images.githubusercontent.com/29598240/116515806-0de7f700-a8cd-11eb-9765-ecce470ab721.png)

**3. Expected behavior**
The warning should not appear as the table is actually temporary. For readability purpose (I think) is better to know that the record is temporary by reading the variable name.
Also, I think it should appear when Temp does not prefixe a table set as Temporary with the TableType Property.

**4. Actual behavior**
The warning appears when Temp prefixes the table name of a table set as Temporary with the TableType property.
Plus, the warning does not appear when the Temp prefix is not added to a variable referenceing a temporary table (set with the TableType property).

**5. Versions:**

- AL Language: 7.1.453917
- Visual Studio Code: 1.55.2
- Business Central:
- List of Visual Studio Code extensions that you have installed:

**Comment by dtkb** [comment]
previously raised via https://github.com/microsoft/AL/issues/6227#issuecomment-709303514
