### ISSUE TITLE
reminder uses the wrong Currency."Invoice Rounding Precision"

### ISSUE THREAD

**Issue by InnoNavSupport** [microsoft/AL#6607]
**1. Describe the bug**
When creating a reminder the wrong Currency."Invoice Rounding Precision" is used.

**2. To Reproduce**
Create a reminder by using REPORT::"Suggest Reminder Lines"

**3. Expected behavior**
Use "Invoice Rounding Precision" of the currency of the reminder header

**4. Actual behavior**
table "Reminder Header" -> local procedure ReminderRounding(ReminderHeader: Record "Reminder Header")

Since BC17.2
the procedure ReminderRounding(ReminderHeader: Record "Reminder Header") calls 
the procedure GetInvoiceRoundingAmount() which calls 
procedure GetCurrency(ReminderHeader) to get the currency of the reminder.
But the used variable "ReminderHeader" used in GetCurrency doesn´t contain the right data because it´s a global.
Either you add the ReminderHeader as a parameter to the procedure GetInvoiceRoundingAmount() or you call GetCurrency(Rec) instead of GetCurrency(ReminderHeader)

table 295 "Reminder Header"
procedure GetInvoiceRoundingAmount(): Decimal
    var
        TotalAmountInclVAT: Decimal;
    begin
        GetCurrency(ReminderHeader);  <- wrong variable

**5. Versions:**
Version: CH Business Central 17.2 (Plattform 17.0.19353.19730 + Anwendung 16.1.12629.12805)

**Comment by kalberes** [comment]
This looks like an app issue and not a compiler issue. 
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
