### ISSUE TITLE
Codeunit 99000774 "Calculate Routing Line" - Procedure CalculateRoutingLine()

### ISSUE THREAD

**Issue by InnoNavSupport** [microsoft/AL#6608]
**1. Describe the bug**
In all former versions the calculation of the "MaxLotSize" used the variable "ProdOrderQty" (Codeunit 99000774 "Calculate Routing Line" - Procedure CalculateRoutingLine()).
Since 17.2 the variable "ExpectedOperOutput" is used which always contains the whole quanity of the production order without considering the output quantity already produced.

**2. To Reproduce**
Go into a production order which has a quantity <> remaining quantity.
Change the starting date in the line

**3. Expected behavior**
Please restore the old behaviour or add a Event Publisher incl. IsHandled Pattern to allow a individual change of the behaviour.

![image](https://user-images.githubusercontent.com/62563638/116662945-bca43a00-a996-11eb-8da8-9905f190cdcb.png)

**5. Versions:**
Version: CH Business Central 17.2 (Plattform 17.0.19353.19730 + Anwendung 16.1.12629.12805)

**Comment by dtkb** [comment]
wrong repo, you want https://github.com/microsoft/ALAppExtensions/issues - and they'll probably want examples of the event publisher/emission as text.
