### ISSUE TITLE
 The type BLOB is not supported.

### ISSUE THREAD

**Issue by achecac** [microsoft/AL#6610]
I have a PTE in version 18.0.23013.23532 (SaaS) which imports an excel sheet using Excel Buffer (ExcelBuf: Record "Excel Buffer" )
ExcelBuf.OpenBookStream(FileInStream, SheetName);
ExcelBuf.ReadSheet();
When the excel cell being read is larger than 250 characters, I get the error "**The type BLOB is not supported**".

I have this same PTE in v.17.5.22499.22680 running without any issues (even this >250 char cells)

**Comment by kalberes** [comment]
Can you please go through customer support. This looks like a runtime, or AL application issue. This repository is only for issues related to the AL compiler. 
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/

**Comment by achecac** [comment]
Sorry to insist, but I after reviewing this issue, I understand this is related to compiler in brand new version  18.0.23013.23532 (SaaS)
To be more specific:
In ExcelBuffer table, in procedure  ParseCell, this command 

OutStream.Write("Cell Value as Blob");

Should be:

OutStream.Write(Value);

Now, out of the box with this new version, if you try to import an excel sheet with some cell larger than 250 characters, it raises error  "The type BLOB is not supported".

This is due because Outstream.write needs a text variable as parameter and you are using a blob type field.

I have tried to report this issue where you proposed but it seems to be only for prepaid issues.

**Comment by atoader** [comment]
As far as I understand, you are stating that the issue is in ExcelBuffer table, in procedure ParseCell. How do you see that it is related to the developer tools?

**Comment by achecac** [comment]
Hi Alenxandru, I think that with your answer I am begging to understand this is not the right place to post this issue. This issue is obviously an application error, not something that a compiler command does not do properly. Sorry. Anyway, I tried to create a support ticket as your colleague suggested, but they are all paying-tickets.

**Comment by Henry4Xperit** [comment]
Question, is this issue already recognized as a bug? And has it been fixed?

**Comment by db-bc** [comment]
As written above, it is an issue with the application code, not the AL compiler or other development tools, so it's not on-topic here.

Also... if you look at the current BC18.3 code, in `ParseCellValue()`, the suggested change was already made: the code does `OutStream.Write(Value)`, not `OutStream.Write("Cell Value as Blob")`.

So this seems both off-topic _and_ already fixed.
