### ISSUE TITLE
BC140 If service is restarted language will be mixed on pages

### ISSUE THREAD

**Issue by finszterr** [microsoft/AL#6613]
I am using verison 14.0.42627 RTC.

**The bug**
When the service (or the entire server) is restarted then the pages will have mixed captions.

**Expected behavior**
After we compile the pages the captions will be correct (only the current, one language):
![image](https://user-images.githubusercontent.com/17743965/117060936-dbe9f100-ad21-11eb-9efe-d58a06d2bce2.png)

**Actual behavior**
Mixed captions
![image](https://user-images.githubusercontent.com/17743965/117014740-6108e200-acf1-11eb-9df1-cc8eaad50ce0.png)

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
