### ISSUE TITLE
BC version 18. Client crash when set report layout to A4-Landscape

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/AL#6615]
- AL Extension Version: v7.1.453917
- Server Version: 
   W1 18.0 (Platform 18.0.22893.23773 + Application 18.0.23013.23795) (onprem 18.0.23013.23795 base on container)
   W1 18.0 (Platform 18.0.22893.24945 + Application 18.0.23013.23532) (Sandbox)

Procedure:
1. I create test report.
![image](https://user-images.githubusercontent.com/24407031/117122078-a85da400-adbf-11eb-9223-8524c8e533f8.png)

2. For Layout, I keep as default. And, I only set Page Setup as bellow.
![image](https://user-images.githubusercontent.com/24407031/117121088-59fbd580-adbe-11eb-9493-655ad73a5cd0.png)

3. When I run report on Web client. It crash.
![image](https://user-images.githubusercontent.com/24407031/117121631-0dfd6080-adbf-11eb-8d82-9dd93ddc27e3.png)

![image](https://user-images.githubusercontent.com/24407031/117122957-9f210700-adc0-11eb-984f-e347e3d61b21.png)

4. Note: IF I change layout to A4-Portrit. I run well.
   I have some reports (with layout A4-Landscape) run well on old version of BC. But, When I upgrade the package to BC version 18. They also crash when running. Some reports (A4-Landscape) still can run, I don't know why???

**Comment by dtkb** [comment]
Do you have access to the event viewer of the BC server? Are there any illustrative errors / stack traces therein?

**Comment by hgnamvn** [comment]
I update information
I test on W1 18.0 (Platform 18.0.22893.23773 + Application 18.0.23013.23795) (onprem 18.0.23013.23795 base on container)

_Fault bucket , type 0
Event Name: SQL140Exception
Response: Not available
Cab Id: 0

Problem signature:
P1: SQL Server 2019@RTM@
P2: 0x8E91D6AA
P3: 0x8E91D6AA
P4: 0x97A656BB@1306@18
P5: 0x97A656BB@1306@18
P6: SqlEngineConfigAction_rebuilddatabase_validation
P7: 0x085CD773
P8: Unknown
P9: Unknown
P10:

Attached files:
\\?\C:\Program Files\Microsoft SQL Server\150\Setup Bootstrap\Log\20210310_131128\Watson_1\LogFiles.cab
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC1DD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC24B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2B3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2C4.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_SQL Server 2019@_b0eba872c34df9e6de4a1b8d1305b9e5d4af4_000
00000_cab_07f0c2e2

Analysis symbol:
Rechecking for solution: 0
Report Id: 493454c7-ff3e-40ff-b0e6-753dac038012
Report Status: 6
Hashed bucket:
Cab Guid: 0_

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
