### ISSUE TITLE
CodeCop Analyzer doesn't warn for AA0226

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6616]
Please include the following with each issue:

**1. Describe the bug**
If I create a field inside a new table and do not provide a caption property I am not getting a warning for this.

**2. To Reproduce**
See this attached [project](https://github.com/microsoft/AL/files/6426315/ALProject8.zip) OR:

1. AL: Go!
2. Change settings to enable CodeCop analyzer
3. New Table with new Field without a caption.
4. Compile the package.
5. No warnings are given.

settings.json
```json
{
    "al.codeAnalyzers": [
        "${CodeCop}"
    ],
    "al.enableCodeAnalysis": true,
    "al.backgroundCodeAnalysis": true
}
```

MyTable.Table.al
```al
table 50100 MyTable
{
    DataClassification = OrganizationIdentifiableInformation;

    fields
    {
        field(1; Code; Code[20])
        {
            // Where is the warning for the caption?
        }
    }

    keys
    {
        key(Key1; Code)
        {
            Clustered = true;
        }
    }

}
```

**3. Expected behavior**
I expect to get a warning on the vscode "problems" tab or atleast while compiling in the "output" tab.
see [CodeCop Rule AA0226](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0226-captionlanguagevaluemustbefilled)

**4. Actual behavior**
No warning.

**5. Versions:**

AL Language - Version: 7.1.453917
- Visual Studio Code:Version: 1.55.2 (user setup)
- Business Central: BC18
- List of Visual Studio Code extensions that you have installed: I disabled everything except "AL Language"

**Comment by dtkb** [comment]
Does the warning appear if that field is then displayed on a page, without supplying a caption there? I wonder whether it's only evaluated for page fields. Dunno though

**Comment by dannoe** [comment]
Nope, it is not triggered for pages either.

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
