### ISSUE TITLE
Debugging with BC 15.16 fails

### ISSUE THREAD

**Issue by epernst** [microsoft/AL#6617]
After we upgraded from 15.3 to 15.16 we are no longer able to debug from VS Code.
We use the latest VSCode extension (7.1.453917), BcContainerHelper 2.0.11 and NavUserPassword auth.

Publishing the app works fine, but when debugging, then after entering credentials it fails with 
"Something went wrong. An error has occurred".

Looking into the event viewer, the latest error we can find here is:
Error accessing Website Type: Microsoft.Dynamics.Framework.UI.FormActivatorException Message: Parameter id must be a valid number between 1 and 2147483647. StackTrace: at Microsoft.Dynamics.Framework.UI.PropertyBagInvokedActionBase.RetrieveRequiredSingleIntParameter(FormPropertyBag queryParameters, String parameterName, Int32 minimumValue, Int32 maximumValue) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\URL\PropertyBagInvokedActionBase.cs:line 228 at Microsoft.Dynamics.Nav.Client.NavRunPagePropertyBagInvokedAction.Validate(FormPropertyBag queryParameters, UISession uiSession, Object invocationState) in s:\repo\src\platform\client\Shared\Prod.Client.UI\NavRunPagePropertyBagInvokedAction.cs:line 152 at Microsoft.Dynamics.Framework.UI.LogicalFormActivator.GeneratePropertyBagCommand(FormPropertyBag propertyBagToUse, UISession uiSession, Object invocationState) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\URL\LogicalFormActivator.cs:line 157 at Microsoft.Dynamics.Framework.UI.LogicalFormActivator.ValidateAndInvokePropertyBag(FormPropertyBag propertyBagToUse, UISession uiSession, Object invocationState) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\URL\LogicalFormActivator.cs:line 60 at Microsoft.Dynamics.Framework.UI.OpenFormInteraction.InvokeCore(OpenFormInteractionInput logicalInteractionInput) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\Interactions\SystemInteractions\OpenFormInteraction.cs:line 0 at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke[T](String interactionName, Action`1 invokeMethod, T input) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 37 at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\platform\client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 40 at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\platform\client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 125 Source: Microsoft.Dynamics.Framework.UI

Later down it also says:
Server instance: BC Category: Development ClientSessionId: 00000000-0000-0000-0000-000000000000 ClientActivityId: 00000000-0000-0000-0000-000000000000 ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000 ServerActivityId: dffae511-75f5-4b4d-b018-5b25a187ddd1 EventTime: 05/06/2021 08:34:57 Message Failed request -- Method:GET; Url:http://dbc-server-dev:7049/bc/dev/signalr/start?clientProtocol=2.1&transport=webSockets&connectionData=%5b%7b%22Name%22%3a%22DebuggerHub%22%7d%5d&connectionToken=AQAAANCMnd8BFdERjHoAwE%2fCl%2bsBAAAA0SGZE8Z3K0%2bkMq83dl%2bIAwAAAAACAAAAAAAQZgAAAAEAACAAAABFzMKLyKIvVVkOjD%2fYW3I8KYIdiIUHAtG%2bUyJPHkPtQgAAAAAOgAAAAAIAACAAAACHaoK8uXd5ilWQ7WagKdNKGib5eXRVujS2dCV%2bjGHMRDAAAAA8K4EUOTxSs7mkwIrpWST9WMf2RFL4kwVfpP8n%2bbuKLlJZB0ddWJdStLgpvMZVt%2fBAAAAATrpL3gpz4ul0hmqbAF0rvxGLu9cv1cPzAK8zOJfL179EIS7q%2bNa89G1bnR8BRlRyUWhqGxbvtfpHvmyAYcrx0g%3d%3d&tenant=default&Authentication=; StatusCode:NotFound; ReasonPhrase:Not Found; Token: ProcessId: 12120 Tag: 00006NR ThreadId: 11 CounterInformation: CustomParameters: 00000000-0000-0000-0000-000000000000

Any clues?

**Comment by atoader** [comment]
Hi! Is this still an issue for you?

**Comment by epernst** [comment]
Yes, we just upgraded to 15.17 and the issue remains the same.

**Comment by atoader** [comment]
We have accepted the bug and we will try to reproduce it on 15.17. Do you hit this issue on any other release?

**Comment by atoader** [comment]
@epernst I have setup an environment with the latest build from the 15 release and I can publish a simple Hello World extension and I hit the breakpoint. It looks like the issue is related to either your setup or the particular code that you are debugging. 

Would you mind raising this issue with our customer support team? They will work with you to pin point the problem.

![image](https://user-images.githubusercontent.com/3097909/126493537-090029b7-103c-4cce-abdb-9bcd64caa5e9.png)
