### ISSUE TITLE
Published event in extension object not raised

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#662]
An event is published and raised with a tableextension object, but the subscriber is not called. Event Subscriptions page shows error 'ErrorOriginalMethodNotFound'.
 
Code to publish and raise an event using a tableextension

![image](https://user-images.githubusercontent.com/19155831/30261444-ecfa65a2-96cc-11e7-9372-7775aebc9430.png)

Code to subscribe to it from a new Codeunit

![image](https://user-images.githubusercontent.com/19155831/30261467-099457fe-96cd-11e7-9ca3-18bf141cecf8.png)

Call it from the OnOpenPage of the Item List

![image](https://user-images.githubusercontent.com/19155831/30261478-17e94710-96cd-11e7-8130-6457ab8888ba.png)

The message from the event subscriber is not displayed. Only the one from the HelloWorld method.

In the Event Subscriptions page it shows 'ErrorOriginalMethodNotFound'

![image](https://user-images.githubusercontent.com/19155831/30261527-52768d34-96cd-11e7-8085-26a91e85a291.png)

Visual Studio Code shows the event with intellisense, so I suppose this scenario should work.

![image](https://user-images.githubusercontent.com/19155831/30261572-90adc1bc-96cd-11e7-93a3-d9f7f9927842.png)

**Comment by kalberes** [comment]
Needs investigating. One comment though. Our intellisense is not context specific. Yet. Thus you may get suggestions for members that are not in scope.

**Comment by ajkauffmann** [comment]
Ok, I can see that.
But I really hope this is just a bug and not something that is by design.

- The compiler accepted it, the app package could be created and published without any warning. 
- Intellisense nicely picks up the published event from the tableextension, while I used the base table as the publishing object in the event subscriber annotation.
- Extension objects are the only way to add events to base objects.
- Events from fields added by the extension, do work.

So, overall it seems a very valid scenario to me.

**Comment by cmrudolph-msft** [comment]
This is a valid scenario. We understand why it does not work right now and consider it a bug.

**Comment by KJBOLOE** [comment]
Hi, Is there a way to copy the parameters from the Publisher Event to the Subscriber Local procedure. Like the way it is in the Development Enviroment.
Best regards,
Kenneth 
![image](https://user-images.githubusercontent.com/35993204/35615076-66f5d4a4-0671-11e8-8bdb-f5ba543566ea.png)
