### ISSUE TITLE
Report Extension Issue

### ISSUE THREAD

**Issue by jngillard** [microsoft/AL#6621]
**1. Describe the bug**
When using a report extension - Dataitem that contains elements that are extended by another "extension", referring to those fields in the report extension causes an error. Example: The SourceExpr for report control 'WSI0009_Height' is not valid. The following error occurred: Object reference not set to an instance of an object.

The field is part of table coming from an extension. That table has been extended by a second extension. Both of these extensions are "dependencies". So, the compiler does not complain about the fields. (There is no compiler errors)
If I remove the fields that are not extended by a second extension, the report will run without error.

**2. To Reproduce**
Create an extension that has dependency on 2 other extension. On one of these extensions, create a table. On the 2nd, extend the table from the first extension. Then, try and use those "extended" fields with a report extension.

``` AL
reportextension 50100 "WSI Pick Instruction" extends "Pick Instruction" //214
{    
    RDLCLayout = './Report Extensions/PickInstruction.rdl';
    dataset
    {
        // Add changes to dataitems and columns here
        add("Sales Header")
        {
            column(WSI_Shipping_Agent_Code; "Shipping Agent Code")
            {
            }
            column(WSI_Shipping_Agent_Service_Code; "Shipping Agent Service Code")
            {
            }
            column(WSI_Package_Tracking_No_; "Package Tracking No.")
            {
            }
        }
        addfirst("Sales Line")
        {
            dataitem("WSI0012 Pack Out Layer"; "WSI0012 Pack Out Layer")
            {
                DataItemLinkReference = "Sales Line";
                DataItemLink = bcsubtype = field("Document Type"), BCDocNum = field("Document No."), BCLineNum = field("Line No.");
                DataItemTableView = sorting(BCType) WHERE(BCType = const(36));
                column(Item_No_; "Item No.")
                {
                }

                dataitem("WSI0012 PackOut"; "WSI0012 PackOut")
                {
                    DataItemLink = BCDocNum = field(BCDocNum), BCType = field(BCType), BCSubType = field(BCSubType), "Pack No." = field("Pack No.");
                    DataItemTableView = sorting(BCType) WHERE("EasyPost OrderID" = filter('<>0'));
                    column(WSI_Pack_No_; "Pack No.")
                    {
                    }
                    column(WSI0009_PreDefinedPackage_Desc; "WSI0009 PreDefinedPackage Desc")
                    {
                    }
                    column(WSI0009_Height; "WSI0009 Height")
                    {
                    }
                    column(WSI0009_Length; "WSI0009 Length")
                    {
                    }
                    column(WSI0009_Width; "WSI0009 Width")
                    {
                    }
                    column(WSI0009_Weight; "WSI0009 Weight")
                    {
                    }
                    column(WSI_Contained; Contained)
                    {
                    }

                    trigger OnAfterGetRecord()
                    begin
                        Contained := "WSI0012 Pack Out Layer"."Item No.";
                    end;

                }
            }
        }
    }

    requestpage
    {
        // Add changes to the requestpage here
    }

    var
        Contained: Code[20];
}
```

**3. Expected behavior**
No error should occur when running the report (which uses the report extension)

**4. Actual behavior**
When running the report, an error occurs. (Even without referencing the fields in the report template)
![image](https://user-images.githubusercontent.com/33632558/117665424-d0a72300-b170-11eb-8db0-1881b51f96f3.png)

**5. Versions:**

- AL Language: 7.1.453917
- Visual Studio Code: 1.56.0
- Business Central: Version: CA Business Central 18.0 (Platform 18.0.22893.25030 + Application 18.0.23013.25070)

**Comment by atoader** [comment]
Can you check if this still reproduces on the latest developer preview or in 18.1? We have made a large number of improvements to report extensions in 18.1

**Comment by grantbrimhall** [comment]
I am receiving the same error on a report extension, but for a different reason. I have extended the Prod. Order - Mat. Requisition report, with this syntax:

            dataitem("Prod. Order Line"; "Prod. Order Line")
            {
                DataItemLink = Status = field(Status),
                               "Prod. Order No." = field("No.");

                <some columns>

                dataitem("Prod. Order Routing Line"; "Prod. Order Routing Line")
                {
                    DataItemLink = Status = field(Status),
                                   "Prod. Order No." = field("Prod. Order No."),
                                   "Routing Reference No." = field("Line No.");

                    <some columns>

                    column(Setup_Time_PORL; FORMAT("Setup Time"))
                    { }
                    column(Run_Time_PORL; "Run Time")
                    { }

                    <some more columns>

                }
            }

For the column Run_Time_PORL, I get the same error (The SourceExpr for report control 'Run_Time_PORL' is not valid. The following error occurred: Object reference not set to an instance of an object.)

But the field above it (Setup_Time_PROL) does not give me the error if I wrap the field name with FORMAT(). Almost as if there is some bug extending Decimal fields.

All other field types seemed to work fine. I had a couple Codes, Dates, integers, DateTimes, etc... But my 4 Time fields (Setup Time, Run Time, Wait Time, and Move Time) all would give the same error unless I put them inside FORMAT().

After I had the report working (using the FORMAT() trick) I added the Quantity field to the Production Order Line dataitem. Got the same error for that too. Added FORMAT() and it works fine again.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.

**Comment by gonzaloriosley** [comment]
Hi, this is still a bug.

Thanks to @grantbrimhall for his FORMAT suggestion, it works.
