### ISSUE TITLE
Job Actual to Budget Cost(BC 18.0)AL

### ISSUE THREAD

**Issue by Indira26** [microsoft/AL#6624]
Please include the following with each issue:

**1. Describe the bug**
BC version 18.0 while in he **JobCard** Page we try to access the action  **Job Actual to Budget (Cost)**  then in line no. 150
  JobDiffBuff.Description := GetItemDescription(Type.AsInteger(), "No."); there is an exception if the description size in the item is more than 50 char. this is because of the inconsistent size of description columns in the "Job Difference Buffer" and Item.

**2. To Reproduce**
Go to Job Card -> Job Actual Budget cost (Mae sure for those items whose description is more than 50 char).
Error "The length of the string is 78,but must be less than 50 chars"

``` AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally ```
 dataitem("Job Planning Line"; "Job Planning Line")
                    {
                        DataItemLink = "Job No." = FIELD("No."), "Planning Date" = FIELD("Planning Date Filter");
                        DataItemLinkReference = Job;
                        DataItemTableView = SORTING("Job No.", "Job Task No.", "Schedule Line", "Planning Date") WHERE(Type = FILTER(<> Text));

                        trigger OnAfterGetRecord()
                        begin
                            Job.SetJobDiffBuff(
                              JobDiffBuff, "Job No.", "Job Task"."Job Task No.", "Job Task"."Job Task Type", Type.AsInteger(), "No.",
                              "Location Code", "Variant Code", "Unit of Measure Code", "Work Type Code");
                            JobDiffBuff."Unit of Measure code" := '';

                            if JobDiffBuff.Find then begin
                                JobDiffBuff."Budgeted Total Cost" := JobDiffBuff."Budgeted Total Cost" + "Total Cost (LCY)";
                                JobDiffBuff.Modify();
                            end else begin
                                if "Job Task"."Job Task Type" = "Job Task"."Job Task Type"::Posting then
                                    **JobDiffBuff.Description := GetItemDescription(Type.AsInteger(), "No.");**
                                JobDiffBuff."Budgeted Total Cost" := "Total Cost (LCY)";
                                JobDiffBuff.Insert();
                            end;
                        end;

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The report should open for all records.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/84044641/117881795-485b7780-b26f-11eb-940b-283926aa993d.png)

**5. Versions:**

- AL Language:   v7.1.453917
- Visual Studio Code:1.56.1
- Business Central:18
- List of Visual Studio Code extensions that you have installed:AL Language,

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
