### ISSUE TITLE
can use add border style excel for "excel buffer" on cloud

### ISSUE THREAD

**Issue by kaomiza** [microsoft/AL#6626]
I see "DocumentFormat.OpenXml.Spreadsheet.BorderStyleValues" in dotnet but not working on cloud
and I need generate excel with styles.

Do you have any solutions?

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
