### ISSUE TITLE
TableRelation looking up field with conflicting type is not diagnosed by compiler

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6627]
Is it intended that TableRelations can have different types between the looking-up and looked-up field? That seems wrong.

I suppose looking up shorter text into a field of longer text could be OK, or maybe converting between Code/Text and Decimal/Integer, etc. But surely trying to look up text into a numeric field, and suchlike, can't possibly be useful?

Catching these thinkoes at compile-time will save developers having to wait until they've released and run the code and found the error - or our users have.

![image](https://user-images.githubusercontent.com/63455896/118283408-3d028900-b4c7-11eb-97ef-41bb0aff88fc.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.1.453917
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by atoader** [comment]
Could you provide a sample project with comments on where you think diagnostics should be emitted and why?

**Comment by dtkb** [comment]
I suppose it depends. What is your intention? That it should be allowed if the value selected in the drop-down/lookup can be converted/coerced/cast to the destination field type? With an error at runtime if not? like this:

![image](https://user-images.githubusercontent.com/63455896/121492044-6e8b4900-c9ce-11eb-9f0c-c256f040833e.png)

If so, then I guess whatever, although I question how useful this would be in reality.

I did find another runtime error when testing this, which should probably be compile-time:
![image](https://user-images.githubusercontent.com/63455896/121492114-806cec00-c9ce-11eb-87d1-7ac17613998f.png)

**Comment by atoader** [comment]
I think the best would be to focus this bug on the case that you think should be blocked by the compiler to prevent a runtime error. Can you provide a project to reproduce this with details on the expected experience?

**Comment by atoader** [comment]
Thanks for closing it! It definitely helps us focus :)
