### ISSUE TITLE
'A field with name 'Table No.' is already defined'

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#663]
Hello
I get this error when I open the al file on visual studio code. Do you know how I could fix this?

file: 'file:///c%3A/Users/vmadmin/FieldSecurity/Table%2070018002%20-%20EDI%20Handler.al'
severity: 'Error'
message: 'A field with name 'Table No.' is already defined'
at: '229,51'
source: 'AL'

![image](https://user-images.githubusercontent.com/6551266/30278499-7b9c5cc4-96d8-11e7-9384-6d1e4bb625c4.png)

![image](https://user-images.githubusercontent.com/6551266/30278473-6d4c2294-96d8-11e7-9df3-9dffe946e572.png)

**Comment by DominikDitoIvosevic** [comment]
Could you please first try to fix all the syntax errors? I could be that the compiler has gotten confused because the syntax is broken. Also, are you sure this is not a duplicate declaration of the same field?

**Comment by andrecavalcanti** [comment]
ok. I'll try to fix all the errors before. I'm sure it is not a duplicate
thanks
