### ISSUE TITLE
[BUG (?)] Different Fieldtype in the table "Tariff Number" for field "Supplementary Units" in localization BE & CZ

### ISSUE THREAD

**Issue by TimCsr** [microsoft/AL#6631]
Hello,
For a particular customer, we synchronize tables in different environments & tenants. One of the synchronizations is the "Tariff Number" table between the localization BE (Belgium) and CZ (Czech). Now we noticed that the field "Supplementary Units" in BE is a "normal" field and in CZ a Flowfield. So this field cannot be synchronized.
Can you look into this and solve it? In which localization is this correct?
![image](https://user-images.githubusercontent.com/50943286/118483604-7d0b7b00-b716-11eb-826f-f19cccabf6bf.png)

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
