### ISSUE TITLE
Business Chart: Columns with the same name will be grouped together

### ISSUE THREAD

**Issue by EricPhoon** [microsoft/AL#6632]
**1. Describe the bug**
Business Chart seems to have the columns with the same name are grouped together on the web client. 
Tested on StackedArea, Area, and Line, so far.
This is happened only on Web client. Window client looks fine.

Web Client (column with the same name are grouped together)
![image](https://user-images.githubusercontent.com/63275754/118504585-393c6400-b75e-11eb-8a27-e58627af9173.png)

Window client (column with the same name is created as separated column)
![image](https://user-images.githubusercontent.com/63275754/118503771-810ebb80-b75d-11eb-88ef-661119808632.png)

**2. To Reproduce**
Create and insert Business Chart Buffer with the same column name as below
![image](https://user-images.githubusercontent.com/63275754/118496386-aa781900-b756-11eb-8ea4-216491fc1e66.png)

**5. Versions:**

- AL Language: Yes
- Business Central: BC14, and BC17

Please review. Thanks.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
