### ISSUE TITLE
ChangeLogic based on the Enum in Service Item Component Table

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/AL#6638]
Here we have enum with 2 values , But if we extend Enum there are more values to handle in OnLookup And onValidate triggers of No field.

field(5; Type; Enum "Service Item Component Type")
        {
            Caption = 'Type';

            trigger OnValidate()
            begin
                if Type <> xRec.Type then
                    Validate("No.", '');
            end;
        }

Add Case statement for Below triggers
**field(6; "No."; Code[20])
        {
            Caption = 'No.';
            TableRelation = IF (Type = CONST("Service Item")) "Service Item"
            ELSE
            IF (Type = CONST(Item)) Item;

            trigger OnLookup()
            begin
                if Type = Type::Item then begin
                    Item."No." := xRec."No.";
                    if PAGE.RunModal(0, Item) = ACTION::LookupOK then
                        Validate("No.", Item."No.");
                end else begin
                    ServItem.Get("Parent Service Item No.");
                    ServItem2.Reset();
                    ServItem2.SetCurrentKey("Customer No.", "Ship-to Code");
                    ServItem2.SetRange("Customer No.", ServItem."Customer No.");
                    ServItem2.SetRange("Ship-to Code", ServItem."Ship-to Code");
                    ServItem2."No." := "No.";
                    if PAGE.RunModal(0, ServItem2) = ACTION::LookupOK then
                        Validate("No.", ServItem2."No.");
                end;
            end;

            trigger OnValidate()
            begin
                if "No." <> '' then begin
                    if Type = Type::"Service Item" then begin
                        if "No." = "Parent Service Item No." then
                            Error(
                              Text000,
                              Type, "No.", TableCaption, ServItem.TableCaption, "Parent Service Item No.");
                        ServItem.Get("No.");
                        "Serial No." := ServItem."Serial No.";
                        "Variant Code" := ServItem."Variant Code";
                        Description := ServItem.Description;
                        "Description 2" := ServItem."Description 2";
                    end else begin
                        Item.Get("No.");
                        "Serial No." := '';
                        Description := Item.Description;
                        "Description 2" := Item."Description 2";
                    end;
                    "Date Installed" := WorkDate;
                end else begin
                    "No." := '';
                    "Date Installed" := 0D;
                    "Serial No." := '';
                    Description := '';
                    "Description 2" := '';
                end;

                Validate("Serial No.");
            end;
        }**

**Comment by dtkb** [comment]
you want the https://github.com/microsoft/ALAppExtensions/issues repo instead

**Comment by srinivasGangadhara** [comment]
Is Request is Accepted or can i use other labels?

**Comment by dtkb** [comment]
It's off-topic for this repo, so you should repost it on the correct repo, as linked above.

**Comment by atoader** [comment]
Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
