### ISSUE TITLE
[Event Request] Codeunit 1003 - Job task indent -OnRun - OnBeforeConfirm

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/AL#6640]
Provide Event as per the below request.

![image](https://user-images.githubusercontent.com/29703512/119620344-81c0e500-be22-11eb-8bbc-139dfddc6063.png)

Thanks!
Srinivas

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
