### ISSUE TITLE
Unify Document Type data type between Header and Lines for IC Inbox / Outbox Transactions

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/AL#6641]
Please unify data type for Document Type between Header and Line records related to Intercompany Transactions. Currently all Header records contain Document Type of Enum but the related Line records uses Document Type of Option. This data type mismatch is in the following tables:

- IC Inbox Sales Header / IC Inbox Sales Line
- IC Outbox Sales Header / IC Outbox Sales Line
- IC Inbox Purchase Header / IC Inbox Purchase Line
- IC Outbox Purchase Header / IC Outbox Purchase Line
- Handled IC Inbox Sales Header / Handled IC Inbox Sales Line
- Handled IC Outbox Sales Header / Handled IC Outbox Sales Line
- Handled IC Inbox Purchase Header / Handled IC Inbox Purchase Line
- Handled IC Outbox Purchase Header / Handled IC Outbox Purchase Line

For Sales transactions in the Header tables Enum IC Sales Document Type is used but in the Line "old" Option data type is used.
For Purchase transactions in the Header tables Enum IC Purchase Document Type is used but in the Line "old" Option data type is used.

I think it will be nice to unify it as we would like to create our own new value for IC Sales Document Type / IC Purchase Document Type which we can currently easily extend and use for Header tables but we would like to have a possibility to extend it the same way for related Line tables too which is not possible now because of Option data type.

Thanks in advance.

Note: We currently uses the latest version of BC

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
