### ISSUE TITLE
"Object definition is not available" on extension objet for our own app 

### ISSUE THREAD

**Issue by Polux-cpu** [microsoft/AL#6642]
Hello,
We are having a problem accessing our own objects in app files if this object have "extension type".
No issue with table, page etc ... but impossible with Table extension, Page extension etc...
Example: If I try to visualize this table for this app package :
![image](https://user-images.githubusercontent.com/84836327/119789915-c5275c00-bed3-11eb-9679-f4658932b362.png)
No problem here I have access to the source :
![image](https://user-images.githubusercontent.com/84836327/119790041-e425ee00-bed3-11eb-9dda-ba846f13760e.png)
But, when I try on **extension** object, like this :
![image](https://user-images.githubusercontent.com/84836327/119790128-f738be00-bed3-11eb-9aa0-ae12cee1071c.png)
I have this error message all time on bottom :
![image](https://user-images.githubusercontent.com/84836327/119790193-0455ad00-bed4-11eb-9d2f-5cf960bea73f.png)
Do you have an idea of the problem ?
Thank for you help if you have an idea and have a good day.

Cyril.

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository as this is not a Microsoft VSCode extension, but a 3rd party one. Please open the issue in the right depository.
