### ISSUE TITLE
FieldGroups -  tables need default DropDown FieldGroup

### ISSUE THREAD

**Issue by Wilkai8** [microsoft/AL#6643]
It is not possible to extend a FieldGroup without it already existing. E.g. the "Posted Gen. Journal Line" (181) table has no DropDown FieldGroup so I can't add any field from a tableextension to the default dropdown in a lookup. It defaults to just Description.

Could you please add the default DropDown and Brick fieldgroup to:
"Posted Gen. Journal Line" (181)
Thank you in advance.

**Comment by dtkb** [comment]
This should really be two issues I think. The request for fieldgroups to exist by default would be on-topic here, but the request for specific fieldgroups to be added for extensibility in the meantime should go to https://github.com/microsoft/ALAppExtensions/issues

**Comment by Wilkai8** [comment]
Thank you for your suggestion
I created a new issue
The link is as follows
[#6643](https://github.com/microsoft/AL/issues/6643)
