### ISSUE TITLE
Cannot Unpublish a marketplace extension from cloud environment

### ISSUE THREAD

**Issue by moizsoloman** [microsoft/AL#6645]
Recently I installed an extension from the Marketplace on a cloud environment, but had contacted the vendor for some additions to the product, the vendor sent me a .app file with the updates.

To install the extension I tried using the Upload function on the Extension Management, I get error the app id already exist

Once I uninstall the extension I cannot Unpublish it, as the uninstalled extension do not show up in Extension Management list. 

Question: I want to install the new extension, Can I unpublish an extension from the cloud environment? if yes then how? else does the vendor need to update the extension on the marketplace for us to get the latest version

**Comment by kalberes** [comment]
The above issue does not really qualify for this github repository
But just for your info unofficially. 
If you have the source code you can install a dev extension with an increased version from vscode. That is what is supported, or ask the partner to install a newer version on the marketplace.
