### ISSUE TITLE
Enums: Breaking changes allowed through Syncronize action and must be prevented! 

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#6646]
**EXTREMELY URGENT.!!**

This is the following error that has been returned during Appsource submission:

The validation process has detected an issue when validating for version 18.0, country: United Kingdom Error encountered for the extension XXX.error : Failed to compile package: src/EnumExtension/SalesDocumentType.EnumExt.al(1,23): error AS0083: The enum value with name 'ABC' and ID '9012345' was found in the previous version of 'EnumExtension SalesDocumentTypeEQ2', but is missing in the current extension. This might break the upgrade of existing installations and dependent extensions. 

The Appsource submission has correctly been rejected because certain EnumExtension values have been removed from one version to the next - this is not allowed and yet VS Code has not had any problem with it (which it most definitely should!).

VS Code must pick this up and prevent publishing otherwise this will destroy data and will go unnoticed until failing Appsource submission and for OnPrem sites this could simply delete data without error..!

For other field types this sort of breaking change is of course prevented, I guess (the newer) Enums must have been forgotten?

**Comment by qutreson** [comment]
Hi @eque2al, this is validated by the AppSourceCop analyzer (with [AS0083](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0083-enumvaluedeletionnotallowed)). The AppSourceCop analyzer is not enabled by default as all extensions are not targeting the AppSource marketplace.

Do you have the AppSourceCop enabled as documented [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool) and have your AppSourceCop.json pointing to your baseline extension as documented [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop#configuration)?

**Comment by eque2al** [comment]
Yes absolutely, I have always used AppSourceCop and can see other errors and warnings but this one has definitely been missed and allowed publishing in mode 'Synchronize', hence logging it..

**Comment by qutreson** [comment]
So you have enabled AppSourceCop, have specified the baseline extension to use in the AppSourceCop.json, but you do not get the diagnostic AS0083 reported for your enum breaking change?

How does your AppSourceCop.json and your project look like?
Can you provide us with a sample project that reproduces the issue?

**Comment by eque2al** [comment]
Well, actually I just tested it this morning as I wanted there to be no doubt.

To reproduce the issue it is very simple:

1. Create AppSourceCop.json file as below (changing supportedCountries as desired and 'AWC' to your own suffix):

{
  "supportedCountries": ["GB"], 
  "mandatorySuffix": "AWC"
}

2. Create settings.json file as below:

{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
      "${AppSourceCop}"
    ]
}

3. Create an EnumExtension file within a new project as below:

enumextension 50001 CommentLineTableNameAWC extends "Comment Line Table Name"
{
    value(50000; "Custom Header")
    {
        Caption = 'Custom Header';
    }
    value(50001; "Custom Line")
    {
        Caption = 'Custom Line';
    }
}

4. Publish the App (F5) to your local sandbox.
5. Close VS Code and reopen it.
6. Delete the EnumExtension value 50001; "Custom Line".
7. Publish the App (F5) again.

The app is published without error!

This is not acceptable as it should be prevented, just as it is with other breaking changes.  We can't rely on a manual process to pick this up so you must assume that this problem will cause you more failed AppSource submissions, something neither of us has the time for.!

So, I **really** do appreciate this being fixed ASAP.  Thank you!

**Comment by qutreson** [comment]
Your AppSourceCop configuration does not specify the baseline to validate breaking changes against, which is why the rule is not reported.

See: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop#configuration

**Comment by eque2al** [comment]
Thank you very much for the prompt reply, I'll get that checked - if that's all it is then I'm **very** happy!!
