### ISSUE TITLE
Cannot download symbols from cloud business central 

### ISSUE THREAD

**Issue by deborahQinzm** [microsoft/AL#6649]
Please include the following with each issue:

**1. Describe the bug**
When try to download symbols, it gets the Table data Permission issue. But checked, I have read permission on this table.

[2021-06-03 15:50:14.32] The request for path /v2.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0 failed with code Forbidden. Reason: You do not have the following permissions on TableData Published Application: IndirectRead.

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '121634'.
[2021-06-03 15:50:14.63] The request for path /v2.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=18.1.24822.26035 failed with code Forbidden. Reason: You do not have the following permissions on TableData Published Application: IndirectRead.

**2. To Reproduce**

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by atoader** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
