### ISSUE TITLE
Allowed Range Error

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#665]
I've loaded my developer license, but I'm getting the following error on a XmlPort:
'The application object identifier '70001002' is not valid. It must be within the allowed range '50100' - '50149'

I can't test locally because of previous issue. I'm getting this error on my remote development machine, not sure if that is related. I didn't get this error on the July Preview.

September Preview downloaded 9/11

**Comment by johndcollins** [comment]
So it's only showing the error for my XmlPort, but when trying to compile I get a lot of these errors:

error AL0297: The application object identifier '70001001' is not valid. It must be within the allowed range '50100' - '50149'.

**Comment by StanislawStempin** [comment]
We have added a new app.json setting for controlling your object id range:
```
"idRange": {
    "from": 50100,
    "to": 50149
  }
```
Simply change it to match the range from your license file.

**Comment by johndcollins** [comment]
Ahh..thanks. Didn't catch that.
