### ISSUE TITLE
Request to add OnBeforeStatisticsAction Event for all Service Module Transaction pages

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/AL#6650]
**Describe the bug**
we have **OnBeforeStatisticsAction** Event for all Sales module transaction pages, but for Service Module same Publisher events are not available. 

**Current behavior**
No Publisher event available in below Service module transaction pages
1. Page	- 5900	- Service Order
2. Page	- 5933	- Service Invoice
3. Page	- 5935	- Service Credit Memo
4. Page	- 5964	- Service Quote
5. Page	- 6050	- Service Contract
6. Page	- 9317	- Service Quotes
7. Page	- 9318	- Service Orders
8. Page	- 9319	- Service Invoices
9. Page	- 9320	- Service Credit Memos
10. Page	- 9321	- Service Contracts

**Expected behavior**
we are requesting for below two changes on above pages
**Change 01** : **Add publisher Event on each transaction page**
`
[IntegrationEvent(false, false)]
    local procedure OnBeforeStatisticsAction(var SalesHeader: Record "Sales Header"; var Handled: Boolean)
    begin
    end;
`
**Change 02** : **Use Handled in OnAction() trigger of Statistics Action**
![image](https://user-images.githubusercontent.com/5293496/120789854-c6016300-c54f-11eb-8fe3-8d512577b608.png)

Thanks 
Sachin Chavan

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
