### ISSUE TITLE
AA0072 not ignoring prefix of depency app

### ISSUE THREAD

**Issue by TeusV** [microsoft/AL#6651]
**1. Describe the bug**

When declaring a variable of an object that is part of a dependent app, warning AA0072 shows up.

**2. To Reproduce**

1. In an extension with prefix APP and table "APP Foo", declare:
``` AL
var
    Foo: Record "APP Foo";
```
No warning (good).

2. Now in an extension i) with a different prefix and ii) which is depending on APP, declare exactly the same.
Warning shows up (not good).

**3. Expected behavior**
No warning in step 2.

**4. Actual behavior**
Warning AA0072 in step 2.

**5. Versions:**

- AL Language: 7.1.453917
- Visual Studio Code: 1.56.2
- Business Central: W1 17.4 (Platform 17.0.21485.21516 + Application 17.0.16993.0)
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
