### ISSUE TITLE
Undocumented breaking change in OutStream.Write(Variant)

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6653]
outstr.Write(instr) where outstream is a OutStream object and instr InStream causes a runtime error.

Apparently outstream.Write(variant) has been restricted to not allow instreams, but this has not been documented..? This used to work. We do not receive a compiler error.

For others affected by this issue, we were able to circumvent the new restriction using copystream.

**Comment by jehelles** [comment]
Hi,

Could you include a small sample of this issue, and for what versions you experience that this worked and stopped working? Also, the exact error message you are getting would be very helpful.

**Comment by navdotnetreqs** [comment]
Hi,

                trigger OnAction()
                var
                    outstr: OutStream;
                    copyoutstr: OutStream;
                    copyinstr: InStream;
                    tempblob: Codeunit "Temp Blob";
                begin
                    tempblob.CreateOutStream(outstr);
                    outstr.WriteText('fuu');
                    tempblob.CreateInStream(copyinstr);
                    copyoutstr.Write(copyinstr);

                end;

Error message:
 - The type InStream is not supported.

Fails on Platform: 18.0.22893.24763.

**Comment by jehelles** [comment]
Thanks for the good repro steps - and this worked on 17?

**Comment by navdotnetreqs** [comment]
Yeah, plenty of saas-customers using this with no issues.

**Comment by nndobrev** [comment]
@navdotnetreqs We tested on Platform versions 17.0 and 16.0 and we don't see that working. Do you know on which version this has been working? Could you provide more info?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
