### ISSUE TITLE
AppSourceCop gives breaking change error whil change is not breaking ( AS0036)

### ISSUE THREAD

**Issue by PP1986** [microsoft/AL#6659]
**1. Describe the bug**

When checking the new version of my app for appsource on breaking changes etc. (using Run-ALValidation, which uses AppSourceCop), the result says it will fail when submitting the app to app source because of a breaking chance while as far as I can see the change is not breaking.

Previous app (published on app source) has a whole table set to access = internal. So I assume this means all fields in this table are internal. In my new app version I removed the access = internal from the table, so the table is now public, but I set some fields in this table to access = internal.
Now validation code says these fields were not internal before, so it is breaking, but they were in a table that was completely internal, so the fields were never public.
Concluding: I feel like the AppSourceCop incorrectly says the change is breaking.

error AS0036: The property 'Access' for field 'FieldNameHere' in Table 'TableNameHere' has changed from value 'Public' to value 'Internal'. This is not allowed because it will break upgrade of existing installations and dependent extensions.

**2. To Reproduce**
Create a table with a property access = internal on it.
Add a few fields with no access property on them.
Publish app.

Remove access = internal property from table and add it to one of the fields in the table.
Publish app.

Compare the two results for app source validation using Run-ALValidation. This will give you the above error message.

In code:

```AL
table 50100 "Setup"
{
    Caption = 'Setup';
    Access = Internal;

    fields
    {
        field(1; "Code"; Code[1]) {}
        field(2; "Another Field"; Integer){ }
    }
}
```
_____
```AL
table 50100 "Setup"
{
    Caption = 'Setup';

    fields
    {
        field(1; "Code"; Code[1])
        {
            Access = Internal;
        }

        field(2; "Another Field"; Integer)
        {
            Access = Internal;
        }
    }
}
```

**3. Expected behavior**
I expect the change not to be breaking.

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: v7.1.453917
- Visual Studio Code: v1.56
- Business Central: BC18
- List of Visual Studio Code extensions that you have installed:

**Comment by dannoe** [comment]
What happens if you use 2 steps? First set the fields to internal, while the table is still internal and then update the app again and remove the internal for the table?

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 27686 and VS Code Extension Version 8.0.487599. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
