### ISSUE TITLE
Availability of a trial version for new customers (30 days)

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#666]
Since I didn't find any real information about this question on the official Microsoft pages, and also here in the Issue List, I put the question here. It is about providing the customer a trial version, which is limited in time. This is a criteria for the AppSource. Do Microsoft have "best practices"to offer this kind of service, or do you have to develop it over and over again? It would be best if Dynamics provided a functionality to handle such a case.

**Comment by freddydk** [comment]
We have created a whitepaper on registration and self-monetization of your app. This includes explanation on how to do trial period. We are currently working on a v2 of this whitepaper, which includes payment integration. Arend-Jan Kauffmann from Cloud-Ready-Software will talk about this next week at Directions.
You will find the whitepaper at http://aka.ms/appsforfinancials

**Comment by FSharpCSharp** [comment]
Thank you for the quick response. It is good to know that Microsoft has a guideline here and a presentation at the Directions.
