### ISSUE TITLE
Command pallet option to generate permission set generates wrong kind of file on runtime >= 7.0

### ISSUE THREAD

**Issue by invalidCards** [microsoft/AL#6661]
Please include the following with each issue:

**1. Describe the bug**
Since runtime 7.0, a warning appears when using an extensions permission set XML file rather than the new PermissionSet data type. However, the command palette function `AL: Generate permission set containing current extension objects` still creates an `extensionsPermissionSet.xml` in the root directory of the extension rather than a PermissionSet.

I understand that this function is still useful (/ required by the Per Tenant Extension code analyzer) before runtime 7.0, so it would be nice if the existing function either automatically generates the correct type of file based on the runtime in the `app.json`, or a separate command pallet function is created for automatically generating PermissionSet objects rather than XML files.

**2. To Reproduce**

1. Press *Ctrl+Shift+P* or *F1* in Visual Studio Code with the AL Language extension active.
2. Choose the option `AL: Generate permission set containing current extension objects`.

**3. Expected behavior**
A new PermissionSet object is created in the root directory of the extension, containing all objects that are provided by that extension.

**4. Actual behavior**
A new `extensionPermissionSet.xml` is created in the root directory of the extension, containing all objects that are provided by that extension, and a warning is generated from runtime 7.0 onwards on the `app.json` file.

**5. Versions:**

- AL Language: 7.1.453917
- Visual Studio Code: 1.56.2
- Business Central: 18.1.24822.24906
- List of Visual Studio Code extensions that you have installed:
  - AL CodeActions 1.0.1 by David Feldhoff
  - AL Extension Pack 1.0.11 by waldo
  - AL Language 7.1.453917 by Microsoft
  - AL Navigator 0.4.6 by Waldemar Brakowski
  - AL Object Designer 0.2.4 by Márton Sági
  - AL Test Runner 0.5.6 by James Pearson
  - AL Toolbox 2.0.9 by Bart Permentier
  - Andromeda 1.7.0 by Eliver Lara
  - AZ AL Dev Tools/AL Code Outline 3.0.5 by Andrzej Zwierzchowski
  - Carbon Product Icons 0.2.4 by Anthony Fu
  - Create GUID 0.0.2 by nwallace
  - Docker 1.13.0 by Microsoft
  - Error Lens 3.2.7 by Alexander
  - Git Graph 1.30.0 by mhutchie
  - Git History 0.6.16 by Don Jayamanne
  - GitLens - Git Supercharged 11.4.1 by Eric Amodio
  - Gemlins tracker for Visual Studio Code 0.26.0 by Nicolas Hoizey
  - NAB AL Tools 1.2.0 by NAB Solutions AB
  - PowerShell 2021.5.1 by Microsoft
  - REST Client 0.24.5 by Huachao Mao
  - snippet-creator 0.0.5 by nikitaKunevitch
  - TODO Highlight 1.0.4 by Wayou Liu
  - Todo Tree 0.0.213 by Gruntfuggly
  - Unicode code point of current character 0.2.0 by zeithaste
  - vscode-icons 11.4.0 by VSCode Icons Team
  - waldo's CRS AL Language Extension 1.4.9 by waldo
  - XLIFF Sync 1.1.0 by Rob van Bekkum
  - XML Format 1.1.2 by Mike Burgh
  - AL Variable Helper 2.4.0 by Rasmus Aaen (disabled)
  - AL XML Documentation 1.1.1 by 365 business development (disabled)
  - Bracket Pair Colorizer 2 0.2.0 by CoenraadS (disabled)

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem **(not applicable)**

**Comment by kalberes** [comment]
This is by design for now. We have kept the old permission xml file generation around for legacy issues as you have also noted. The new (metadata based) permission system is different. It is another paradigm.  Example: It has nesting capabilities, it provides means to encapsulate it by  having it internal or public etc, etc. I am not sure these can be done through code generation.
