### ISSUE TITLE
false AA0206 "initialized but not used" warning from "quoted" variables in field/action properties like Editable/Enabled/Visible

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6662]
I noticed this in code being copied/pasted/modified from a Continia product. The quotes are unnecessary, sure, but they shouldn't produce spurious and inconsistent warnings like they do.

Given this code:
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    layout
    {
        modify("No.")
        {
            Editable = "FieldEditable";
            Enabled = "FieldEnabled";
            Visible = "FieldVisible";
        }
    }

    actions
    {
        modify("&Customer")
        {
            Enabled = "ActionEnabled";
            Visible = "ActionVisible";
        }
    }

    var
        // fine!
        // FieldEditable, FieldEnabled, FieldVisible, ActionEnabled, ActionVisible : Boolean;
        // not fine!
        FieldEditable: Boolean;
        FieldEnabled: Boolean;
        FieldVisible: Boolean;
        ActionEnabled: Boolean;
        ActionVisible: Boolean;

    trigger OnOpenPage()
    begin
        FieldEditable := true;
        FieldEnabled := true;
        FieldVisible := true;

        ActionEnabled := true;
        ActionVisible := true;
    end;
}
```

Spurious warnings are emitted:

![image](https://user-images.githubusercontent.com/63455896/121707748-cad59200-cace-11eb-9974-7f69c8f3d9b4.png)

These warnings disappear if either:

(1) The uses of the variables are unquoted in the properties:
![image](https://user-images.githubusercontent.com/63455896/121708207-3e779f00-cacf-11eb-8921-3336221030c5.png)

(2) or, bizarrely, the variables are declared simultaneously, instead of separately:
![image](https://user-images.githubusercontent.com/63455896/121708251-4b948e00-cacf-11eb-9672-bd877d27c0de.png)

I expect no warnings, regardless of superfluous quotes or declaration style, since the variables clearly *are* used.

AL:
```
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.2.475273
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

perhaps related to https://github.com/microsoft/AL/issues/6207

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
