### ISSUE TITLE
UTC time and Unix timestamp

### ISSUE THREAD

**Issue by GedasB** [microsoft/AL#6663]
For Auth2 authentication i need UTC time and Unix Time stamp.
1. How to get UTC time? Do you have any smart way to get it? I found only Format(datetime, 0, 9), then we get XML datetime format and then can extract time from it.
2. How to get Unix timestamp ?  I tried calculate duration between some datetime and 1970.01.01 12:00:00 AM, but received one hour less. Is it bug or not? If it is not because of some reasons then i still need to get Unix timestamp - how? 

**1. Describe the bug**
   var     
       DateTimeTest: DateTime;
        EpoxTime: DateTime;
        DurationTest: Duration;
        UnixTime: Integer;
    begin

        DateTimeTest := CreateDateTime(20210612D, 120000T);// 06/12/21 12:00:00 PM
        EpoxTime := CreateDateTime(19700101D, 000000T);// 01/01/70 12:00:00 AM
        DurationTest := DateTimeTest - EpoxTime; // 18790 days **11 hours** - but here must be 12 hours???
        UnixTime := round(DurationTest / 1000, 1); // 1623495600 if we use https://www.unixtimestamp.com/ to check we found Sat 
                                                                             //    Jun 12 2021 **11:00:00** GMT+0000
   end

**3. Expected behavior**
1. Simple way to get UTC time. (as dotnet)
2. Simple way to get Unix timestamp (as dotnet)
3. Using workarounds receive correct duration value 18790 days and **12 hours** = Jun 12 2021 12:00:00 GMT+0000

**4. Actual behavior**
DurationTest := DateTimeTest - EpoxTime; // 18790 days **11 hours** =  Jun 12 2021 **11:00:00** GMT+0000

**5. Versions:**

- AL Language: v7.2.475273
- Visual Studio Code: 1.57.0
- Business Central: Version: W1 17.2 (Platform 17.0.19353.19730 + Application 17.2.19367.19735)
- List of Visual Studio Code extensions that you have installed: Standard docker installation from Sandbox W1

**Comment by Drakonian** [comment]
Use codeunit 10 "Type Helper"
![image](https://user-images.githubusercontent.com/16802407/121883627-a40b9b80-cd1a-11eb-86e6-5241281e0f51.png)
![image](https://user-images.githubusercontent.com/16802407/121883709-bdace300-cd1a-11eb-95ac-4415bcfde050.png)

**Comment by GedasB** [comment]
Hmm i would say it doen't work as i expect:
DateTimeUtc := TypeHelper.GetCurrUTCDateTime();
returns 06/15/21 08:28:25.493 AM, and this is my current time EET (+3 UTC).
When i debug Type helper, i see code:
        DotNetDateTime := DotNetDateTime.UtcNow;
        exit(DotNetDateTime)
in variables:
DotNetDateTime: 6/15/2021 5:34:05 AM - this OK
<Return Value>: 6/15/2021 08:34:05.005 AM -  it is already converted to local time zone.

Then i can do:
        DateTimeUTCtext := TypeHelper.GetCurrUTCDateTimeAsText();
        DateTimeUtc := TypeHelper.EvaluateUTCDateTime(DateTimeUTCtext);
it works correct, but why direct function doesn't? Is it "by design"??

And finally of course i don't have function to get UnixTimestamp from DateTime and duration here works strange.

**Comment by atoader** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
