### ISSUE TITLE
Error code: 85132273 when publishing extension BC 18.1 on premise

### ISSUE THREAD

**Issue by davmac1** [microsoft/AL#6664]
Please include the following with each issue:

**1. Describe the bug**
When installing the app using PowerShell, I get Error code: 85132273. This seems to be a generic error that has been around for years.
I then tried with the Cronus demo.
[AppDependencies.xlsx](https://github.com/microsoft/AL/files/6644916/AppDependencies.xlsx)

If I publish to Cronus using VS Code, I get:

The request for path /BC180/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Error code: 85132273
Violation of PRIMARY KEY constraint 'Application Dependency$Key1'. Cannot insert duplicate key in object 'dbo.Application Dependency'. The duplicate key value is (b40d3121-9b25-4358-aa15-097e9a8a1fa2, c1335042-3002-4257-bf8a-75c898ccb1b8).
The statement has been terminated.
I checked the contents using SQL for dbo.Application Dependency', and could not find any duplicates.
**2. To Reproduce**

``` AL
This is my app.json:

{
  "id": "22a14cf1-202a-463c-806f-b095e0d008ec",
  "name": "XXX Customizations",
  "publisher": "XTIVIA",
  "version": "1.0.0.1",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [{
    "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
    "publisher": "Microsoft",
    "name": "System Application",
    "version": "18.0.0.0"
  },
  {
    "id": "437dbf0e-84ff-417a-965d-ed2bb9650972",
    "publisher": "Microsoft",
    "name": "Base Application",
    "version": "18.0.0.0"
  },
  {
    "id": "c1335042-3002-4257-bf8a-75c898ccb1b8",
    "publisher": "Microsoft",
    "name": "Application",
    "version": "18.0.0.0"
  },
  {
    "id": "aabf70de-e7af-4252-8727-6beaecbe3f9a",
    "name": "ISVapp",
    "publisher": "XTIVIA",
    "version": "11.0.0.0"
  }],
  "screenshots": [],
  "platform": "1.0.0.0",
  "application": "18.0.0.0",
  "idRanges": [
    {
      "from": 50000,
      "to": 50049
    }
  ],
  "contextSensitiveHelpUrl": "https://NAV2021.com/help/",
  "showMyCode": true,
  "runtime": "7.0"
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
Do you need this dependency?
 {
    "id": "c1335042-3002-4257-bf8a-75c898ccb1b8",
    "publisher": "Microsoft",
    "name": "Application",
    "version": "18.0.0.0"
  },

**Comment by davmac1** [comment]
I removed the Microsoft dependencies because the version lines did it too apparently, so it was doubling up.

Could do with a better error code - this one has been around for years.
When I installed the app, I receive the error code without a reason. When I published from VS Code, it gave me the additional detail of the duplicate key.

Thanks for your response.
