### ISSUE TITLE
Rename Enum and explicit using of it

### ISSUE THREAD

**Issue by DSaladinCH** [microsoft/AL#6668]
**1. Describe the bug**
When I rename a enum with the included rename functionality in vscode (click on name and press Ctrl+R twice -> Rename symbols command), all the enum references getting renamed, expect the explicit enum references.

**2. To Reproduce**

1. Create a enum
2. Use the enum as variable or parameter
3. Use the enum as explicit somewhere in the code:
`HasFullAccess := Rec.HasPermission("User Access"::"Full Access");`
4. Now go to a enum object
5. Click on enum name and run the command "Rename symbols" and rename the enum (for example: "User Access" to "User Permission").
6. Go to the references you just created and you will see that the variable and the parameter reference have been changed. But the explicit reference (without a variable, just the name of the enum and a option of it) have not been changed at all and is still "User Access" instead of "User Permission".

**3. Expected behavior**
All enum references should be renamed, also explicit references.

**4. Actual behavior**
Only variables (local, global and parameters) are getting renamed.

**5. Versions:**
- AL Language: 7.2.475273
- Visual Studio Code: 1.57.0
- Business Central: CH Business Central 18.1 (Platform 18.0.24800.26311 + Application 18.1.24822.26330)
- List of Visual Studio Code extensions that you have installed: AL Navigator, AL Variable Helper, AL Object Helper, NAB AL Tools

**Comment by nndobrev** [comment]
Hi @DSaladinCH could you please provide a code snippet that reproduces the issue. Thanks :)

**Comment by DSaladinCH** [comment]
Okay, never mind. As I was preparing the code for you I did test it again and it worked, so I will close this Issue.
