### ISSUE TITLE
How to test with the Dynamics 365 for financials sandbox

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#667]
In the September update, the object area for creating extensions is very limited. There are only 50 objects per area, which is very little. But in the blog entry for the September update, there's an important hint:

> Dynamics 365 for Financials sandboxes have a more permissive license that lets you use range 50000-99999 as well as the 70000000-75000000 range.

How should this reference be understood? How do you get a Dynamics 365 for financials sandbox to have a larger object area? If you select US or GB on the Azure machine, the database is a Dynamics 365 database, but you can't use any other object area for publishing.

**Comment by StanislawStempin** [comment]
Whenever we say Sandbox we mean the Microsoft hosted Dynamics 365 for Financials Sandboxes as described here: 
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-apps-for-fin
and here:
https://docs.microsoft.com/en-us/dynamics365/financials/across-how-create-sandbox-environment

However, please note that the sandboxes are currently still on July Update so you need to use the corresponding VSIX to connect to them  (0.7.xxxx)

**Comment by FSharpCSharp** [comment]
Thank you for the quick information. But if I want to set up a sandbox now, the mistake is that this has not yet been allowed in my country.  Is there a way to create a sandbox, even if it is not yet available in my country? That would be very important for development. That's the only way I can get any further. The little problem so far is that only July has been possible so far.

**Comment by StanislawStempin** [comment]
You can use a demo account created at demos.microsoft.com for a limited period of time. 

If you're working on an App that will end up in AppSource you should request a development license with your own object range. You can then use that license on the development environments.

**Comment by FSharpCSharp** [comment]
OK, thank you very much. I'll try it out right away later. If there are any mistakes or questions I will add them here.

another question about the developer license you mentioned. I've assumed so far that you won't get such a license until you've proposed to register an app. Or are there licenses with a fixed object area, similar to the previous developer licenses? Most of the documents for the registration process seem to be valid only for Extension Framework 1.0. Will they be updated for the current framework soon?

**Comment by FSharpCSharp** [comment]
@StanislawStempin
I have tried to create a sandbox environment for Dynamics 365 several times, even with different accounts in vain. Whenever I log in to the Microsoft demo portal and want to create a tenant, the following error appears. 

![Uploading ErrorCreateTenant.png…]()

Is it no longer possible to create tenants, or do you need special rights? We actually have a partner account, and that's how it should work. After an hour, we gave it up. Do you have any more ideas what else we can do here?

**Comment by StanislawStempin** [comment]
I'm sorry, I'm not familiar with the details of the demos.microsoft.com service. Could you please try their support link?

**Comment by StanislawStempin** [comment]
Regarding the object ranges the process is the same as for Extensions V1. Please see the section 1) Get the prerequisites in place on https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-apps-for-fin

**Comment by FSharpCSharp** [comment]
We have already created a support case for this. Are there already plans for when the current state of development (September) will be available in the sandbox? You had already said that so far you can only work with the July version of the development preview there.

**Comment by StanislawStempin** [comment]
I expect that September update will be available on the sandboxes within a few weeks.

**Comment by StanislawStempin** [comment]
September Update is now available in the VS Code Marketplace and for new sandbox sign ups. To make sure that your existing sandbox is also on the September Update you can use the Reset Sandbox link posted in one of the documentation pages linked above.
