### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by PdwJMB** [microsoft/AL#6670]
**1. Describe the bug**
Error consuming external web service from BC SaaS.
The web service security protocol is TLS 1.2.

**2. To Reproduce**
When executing the call to the web service, the system always returns the error while sending the request:
"The request was aborted: Could not create SSL/TLS secure channel."

**AL Code (invoke the web service):**

    local procedure SendToWS(RequestUri: Text; var IStream: InStream)
    var
        vHttpClient: HttpClient;
        vHttpContent: HttpContent;
        vHttpHeaders: HttpHeaders;
        vHttpRequest: HttpRequestMessage;
        vHttpResponse: HttpResponseMessage;
        ResponseText: Text;
    begin
        vHttpContent.WriteFrom(IStream);
        vHttpRequest.Content(vHttpContent);
        vHttpRequest.Method('POST');
        vHttpRequest.SetRequestUri(RequestUri);
        vHttpRequest.GetHeaders(vHttpHeaders);

        vHttpHeaders.Remove('ContentType');
        vHttpHeaders.Add('KeepAlive', 'TRUE');
        vHttpHeaders.Add('Method', 'POST');
        vHttpHeaders.Add('ContentType', 'text/xml; charset=utf-8');
        vHttpHeaders.Add('Timeout', '20000');

        vHttpClient.Send(vHttpRequest, vHttpResponse);

        if not vHttpResponse.IsSuccessStatusCode() then begin
            vHttpResponse.Content().ReadAs(ResponseText);
            Error(ResponseText);
        end else
            Message('ok');
    end;

**3. Expected behavior**
I hope to get the response status: 200 OK, as with other tools used successfully (SoapUI and Postman) and also from Business Central OnPremise.

**4. Actual behavior**
The system returns the following error:

![image](https://user-images.githubusercontent.com/86055662/122396441-470d2100-cf78-11eb-9767-2099925e7804.png)

**5. Versions:**

- AL Language: 7.2.475273
- Visual Studio Code: 1.57.0
- Business Central: 18.1 (Platform 18.0.24800.26638 + Application 18.1.24822.24906)

**Comment by kalberes** [comment]
Similar duplicate issues: #5405, #1414.  Don't seem to be related to the development environment.
For quicker resolution on runtime issues the best is to open a support ticket.
