### ISSUE TITLE
Partial Records in Pages: setloadfields does not work fine

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/AL#6672]
**1. Describe the bug**
In Pages, rec.setloadfields is ignored in many page events, so the SQL query includes all fields from all table extensions in the source table.
Please, fix this issue with setloadfields and allow the use of SetLoadFields on pages to allow manual use of partial records on pages.

**2. To Reproduce**

- Install a Business Central BC 18.2 OnPrem ES.
- Create and publish new app: JALPageSetLoadFieldsExt1. This app only extend "Fixed Asset" table with many new fields. Next file contains source code.  [JALPageSetLoadFieldsExt1_Source.zip](https://github.com/microsoft/AL/files/6686900/JALPageSetLoadFieldsExt1_Source.zip)
- Create and publish new app: JALPageSetLoadFieldsExt2.  This app add a new page list from "Fixed Asset" table, including only some fields from base app, **none from the new previous application JALPageSetLoadFieldsExt1**.
[JALPageSetLoadFieldsExt2_Source.zip](https://github.com/microsoft/AL/files/6686901/JALPageSetLoadFieldsExt2_Source.zip)
- On JALPageSetLoadFieldsExt2, in page JALSLFE2FAFldsBase.Page.al add breakpoints in rec.setloadfields commands.
![image](https://user-images.githubusercontent.com/68008246/122783382-cf116480-d2b1-11eb-8b15-2d0097d6558a.png)

- Publish with debugging JALPageSetLoadFieldsExt2. On every breakpoing check last queries executes from SQL from table 5600 "Fixed Asset". The results should be similar to the following execution examples captured during my tests (a copy is in fonder JALPageSetLoadFieldsExt2\doc\Test02_WithSetLoadFields)
 ![image](https://user-images.githubusercontent.com/68008246/122784083-6f678900-d2b2-11eb-8e6c-72929cec5e40.png)

> In two first queries, 02_01 and 02_02, it seems that setloadfiels is correct as it selects only some fields.
> But in the rest of queries, when it is looping from source table (OnAfterGetRecord), the sql query include all fields of each extensions, intead of to do the same as the two first queries.

```
//02_01_OnFindRecord.sql
SELECT
    "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Vendor No_",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" = @0)
```
```
//02_02_OnFindRecord.sql
SELECT
    TOP (@0) "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Vendor No_",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" >= @1)
ORDER BY
    "No_" ASC OPTION(FAST 50)

```

```
//02_03_OnAfterGetRecord.sql
SELECT
    "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Search Description",
    "5600"."Description 2",
    "5600"."FA Class Code",
    "5600"."FA Subclass Code",
    "5600"."Global Dimension 1 Code",
    "5600"."Global Dimension 2 Code",
    "5600"."Location Code",
    "5600"."FA Location Code",
    "5600"."Vendor No_",
    "5600"."Main Asset_Component",
    "5600"."Component of Main Asset",
    "5600"."Budgeted Asset",
    "5600"."Warranty Date",
    "5600"."Responsible Employee",
    "5600"."Serial No_",
    "5600"."Last Date Modified",
    "5600"."Blocked",
    "5600"."Maintenance Vendor No_",
    "5600"."Under Maintenance",
    "5600"."Next Service Date",
    "5600"."Inactive",
    "5600"."No_ Series",
    "5600"."FA Posting Group",
    "5600"."Image",
    "5600_e2"."JALSLFE1 UNE Class",
    "5600_e2"."JALSLFE1 Used for",
    "5600_e2"."JALSLFE1 Used Code",
    "5600_e2"."JALSLFE1 UNE Description",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" = @0)

```

```
//02_04_OnAfterGetRecord.sql
SELECT
    TOP (@0) "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Vendor No_",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy",
    "5600"."Search Description",
    "5600"."FA Class Code",
    "5600"."FA Subclass Code",
    "5600"."Global Dimension 1 Code",
    "5600"."Global Dimension 2 Code",
    "5600"."Location Code",
    "5600"."FA Location Code",
    "5600"."Main Asset_Component",
    "5600"."Component of Main Asset",
    "5600"."Budgeted Asset",
    "5600"."Warranty Date",
    "5600"."Responsible Employee",
    "5600"."Serial No_",
    "5600"."Last Date Modified",
    "5600"."Blocked",
    "5600"."Maintenance Vendor No_",
    "5600"."Under Maintenance",
    "5600"."Next Service Date",
    "5600"."Inactive",
    "5600"."No_ Series",
    "5600"."FA Posting Group",
    "5600"."Image",
    "5600_e2"."JALSLFE1 UNE Class",
    "5600_e2"."JALSLFE1 Used Code",
    "5600_e2"."JALSLFE1 UNE Description"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" > @1)
ORDER BY
    "No_" ASC OPTION(FAST 50)

```

```
//02_05_OnAfterGetRecord.sql
SELECT
    "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Vendor No_",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy",
    "5600"."Search Description",
    "5600"."FA Class Code",
    "5600"."FA Subclass Code",
    "5600"."Global Dimension 1 Code",
    "5600"."Global Dimension 2 Code",
    "5600"."Location Code",
    "5600"."FA Location Code",
    "5600"."Main Asset_Component",
    "5600"."Component of Main Asset",
    "5600"."Budgeted Asset",
    "5600"."Warranty Date",
    "5600"."Responsible Employee",
    "5600"."Serial No_",
    "5600"."Last Date Modified",
    "5600"."Blocked",
    "5600"."Maintenance Vendor No_",
    "5600"."Under Maintenance",
    "5600"."Next Service Date",
    "5600"."Inactive",
    "5600"."No_ Series",
    "5600"."FA Posting Group",
    "5600"."Image",
    "5600_e2"."JALSLFE1 UNE Class",
    "5600_e2"."JALSLFE1 Used Code",
    "5600_e2"."JALSLFE1 UNE Description"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" = @0)

```

**3. Expected behavior**
After setloadfields only selected fields would be include in sql query (and few other fields added by default: primary key fields and system fields) 

**4. Actual behavior**
Only apply selected fields in first queries after start looping, but on each OnAfterGerRecord the sql query select all fields of source table, including fields added by extension table objects. That reduces de perfomance because and need to do more joins than are required for optimal perfomance.

**5. Versions:**

- AL Language: v7.2.475273
- Visual Studio Code: 1.57.1
- Business Central: BC18.2 ES OnPrem  docker container.
- List of Visual Studio Code extensions that you have installed:

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.

**Comment by ti-jalopez** [comment]
Hello,
I don't understand way this issue is out of scope. According to https://github.com/microsoft/AL/blob/master/README.MD :  *bugs pertaining to the AL compiler and the developer tools for the latest version can be filed in this repository*.
I need to open a partner support case for this problem? I thought this is only for C/AL..

In my opinion, this issue is a bug that describes a use case where **using manually SetLoadFields** the system don't select the fields according to expected behavior for SetLoadFields command (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setloadfields-method)  and Partial Records (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-partial-records#:~:text=The%20partial%20records%20capability%20in%20Business%20Central%20allows,-%20objects%20whose%20source%20code%20loops%20through%20records.).
 
Best regards,

**Comment by atoader** [comment]
Developer tools refers to the AL Language extension and the AL compiler. Anything pertaining to AL library, runtime, client is something that needs to be filed as a support case.  As I understand it, you are describing runtime behavior of the SetLoadFields, not a compiler issue.

**Comment by ti-jalopez** [comment]
@atoader,
Thanks, your explanation makes it clearer what the microsoft / AL repository is used for and why not. 
In this case, since it is an execution problem with SetLoadFields, I will see if I can open a support case.
Best regards,

**Comment by jensmpmsft** [comment]
You mention that you are extending the Fixed Assets table. It should be noted that if any event subscriber or trigger code on the table reads a non-loaded field, we invalidate the result-enumerator and revert to default behavior to avoid the double round-trip for any call.
Hence the behavior you describe is most likely due to fields outside of the SetLoadFields being loaded by other code.

**Comment by jensmpmsft** [comment]
If you have reproed this in SaaS, please provide time, aadTenantId and session ID (see Help & Support page for that).  Telemetry is emitted if a JITLoad takes place

**Comment by ti-jalopez** [comment]
@jensmpmsft ,
I understand partial records can be used outside of pages and in this situation can exists some event sucriber or trigger to record and it can be the same problem using partial records.
Also, partial records are required mainly in scenarios using extended tables such as Fixed Assets.
So, if i don't use partial records due a possible problem with suscriptions, Why is the partial records functionality available then? 
Partial record should be available,  although using a lot of control in all possible scenarios. 
Implementing partial records in our extensions is a hard and complex work !!

**Comment by dtacconi** [comment]
@ti-jalopez Many thanks to have this logged through standard support. Repro has been dissected by product group and to open up the outcome to whole community, this could be found in the following blog post https://community.dynamics.com/business/f/dynamics-365-business-central-forum/431329/partial-records-and-setloadfields-in-ui-pages-important-things-to-know
