### ISSUE TITLE
Partial Records: setloadfields include some unnecessary fields

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/AL#6674]
**1. Describe the bug**

Performing tests I have detected that the following fields are automatically included in setloadfields, although these fields are not documented in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setloadfields-method#remarks. There are normal fields used as a filter in:
* **Tablerelation**
* **Calcformula**

These fields should only be included if the fields where they are used are included  as tablerelation or calcformula, but nowadays fields are always included.  which can sometimes lead to adding additional sql tables with their corresponding joins. 

This is an example using tablerelation, but the same occurs with fields in calcformula.

**2. To Reproduce**

- Install a Business Central BC 18.2 OnPrem ES.
- Create and publish new app: JALPageSetLoadFieldsExt1. This app only extend "Fixed Asset" table with many new fields. Next file contains source code.  [JALPageSetLoadFieldsExt1_Source.zip](https://github.com/microsoft/AL/files/6686900/JALPageSetLoadFieldsExt1_Source.zip). **The field "JALSLFE1 Used for" is used in field "JALSLFE1 Used Code"as a filter in table relation, so nowadays the field "JALSLFE1 Used for" is always incluided in sql queries. I think in this scenario is not required, because is not used by the process.**

``` AL
//JALSLFE1FixedAsset.TableExt.al
tableextension 50090 "JALSLFE1 FixedAsset" extends "Fixed Asset"
{
    fields
    {
        // Add changes to table fields here
        field(50090; "JALSLFE1 UNE Class"; Code[20])
        {
            DataClassification = CustomerContent;
        }

        field(50091; "JALSLFE1 Used for"; Option)
        {
            OptionMembers = "Customer","Vendor";
            DataClassification = CustomerContent;
        }

        field(50092; "JALSLFE1 Used Code"; Code[20])
        {
            DataClassification = CustomerContent;
            TableRelation = IF ("JALSLFE1 Used for" = CONST(Customer)) Customer
            ELSE
            Vendor;
        }
        field(50093; "JALSLFE1 UNE Description"; Text[50])
        {
            DataClassification = CustomerContent;
        }
    }
}

```

- Create and publish new app: JALPageSetLoadFieldsExt3.  This app add a new page with an action to test setloadfields in extended table on App JALPageSetLoadFieldsExt1 (Fixed Assed) and uses only some fields of base app. Next file contains source code.  [JALPageSetLoadFieldsExt3_Source.zip](https://github.com/microsoft/AL/files/6688775/JALPageSetLoadFieldsExt3_Source.zip)
``` AL
//JALSLFE3TestPartialRecords.Page.al
page 50097 "JALSLFE3 Test Partial Records"
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    actions
    {
        area(Processing)
        {
            action(TestSetLoadFieldsFA)
            {
                ApplicationArea = All;
                Caption = 'TestLoadFields Fixed Asset';

                trigger OnAction()
                var
                    JALSLFE3TestPartialRecords: codeunit "JALSLFE3 Test Partial Records";

                begin
                    JALSLFE3TestPartialRecords.TestSetLoadFieldsFA();
                end;
            }
        }
    }
}
```

```  AL
//JALSLFE3TestPartialRecords.Codeunit.al
codeunit 50097 "JALSLFE3 Test Partial Records"
{
    procedure TestSetLoadFieldsFA()
    var
        FixedAsset: record "Fixed Asset";
        myCount: Decimal;
    begin
        FixedAsset.SetLoadFields(Description, "Description 2", "Global Dimension 1 Code");
        IF FixedAsset.FindSet(false) then
            repeat
                myCount += 1;
            until FixedAsset.Next() = 0;

        Message('Cantidad FA: %1', myCount);
    end;
}
```
- On JALPageSetLoadFieldsExt3, in page JALSLFE3TestPartialRecords.Codeunit.all add breakpoint in line "until FixedAsset.next() = 0".
- Publish with debugging JALPageSetLoadFieldsExt3. Run page 50097 and excecute TestSetLoadFields Fixed Asset action.
![image](https://user-images.githubusercontent.com/68008246/122807335-bdd55180-d2cb-11eb-8904-eec04ca047d0.png)

- On every breakpoing check last queries executes from SQL from table 5600 "Fixed Asset". The results should be similar to the following execution examples captured during my tests (a copy is in folder JALPageSetLoadFieldsExt3\doc\Test03_SetLoadFieldsFixedAsset).
![image](https://user-images.githubusercontent.com/68008246/122807611-13a9f980-d2cc-11eb-9739-f05de4002fc0.png)
> Two first iterations 03_01_Step1.sql and 03_02_Step2.sql are equals, and the sql query include fields selectected by SetLoadFields and **additionally the field "JALSLFE1 Used for" that should not be included because isn't used by the rest of fields selected with setloadfields**.
> Rest of iterations has the same query 03_03_Step3.sql. This query include all fields of "Fixed Asset" incluiding base fields and all extended by table extension. **I don't undertand way are all fields included in query if setloadfields is enable with only some fields of base table.**

```
//03_01_Step1.sql
SELECT
    "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Global Dimension 1 Code",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
ORDER BY
    "No_" ASC OPTION(FAST 50) 

```

```
//03_03_Step3.sql
SELECT
    TOP (@0) "5600"."Search Description",
    "5600"."timestamp",
    "5600"."No_",
    "5600"."Description",
    "5600"."Description 2",
    "5600"."Global Dimension 1 Code",
    DATALENGTH("5600"."Picture"),
    "5600_e2"."JALSLFE1 Used for",
    "5600"."$systemId",
    "5600"."$systemCreatedAt",
    "5600"."$systemCreatedBy",
    "5600"."$systemModifiedAt",
    "5600"."$systemModifiedBy",
    "5600"."FA Class Code",
    "5600"."FA Subclass Code",
    "5600"."Global Dimension 2 Code",
    "5600"."Location Code",
    "5600"."FA Location Code",
    "5600"."Vendor No_",
    "5600"."Main Asset_Component",
    "5600"."Component of Main Asset",
    "5600"."Budgeted Asset",
    "5600"."Warranty Date",
    "5600"."Responsible Employee",
    "5600"."Serial No_",
    "5600"."Last Date Modified",
    "5600"."Blocked",
    "5600"."Maintenance Vendor No_",
    "5600"."Under Maintenance",
    "5600"."Next Service Date",
    "5600"."Inactive",
    "5600"."No_ Series",
    "5600"."FA Posting Group",
    "5600"."Image",
    "5600_e2"."JALSLFE1 UNE Class",
    "5600_e2"."JALSLFE1 Used Code",
    "5600_e2"."JALSLFE1 UNE Description"
FROM
    "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972" "5600" WITH(READUNCOMMITTED)
    JOIN "CRONUS".dbo."CRONUS España S_A_$Fixed Asset$72391d89-0778-485e-a545-8b8882c4ed7a" "5600_e2" WITH(READUNCOMMITTED) ON ("5600"."No_" = "5600_e2"."No_")
WHERE
    ("5600"."No_" > @1)
ORDER BY
    "No_" ASC OPTION(FAST 50)
```

**3. Expected behavior**
All sql queries from table "Fixed Asset" include only fields selected by setloadfields and default fields (primary key and system* fields).

**4. Actual behavior**
Two first sql queries includes a addiional field not required but used as a filter in tablerelation (field "JALSLFE1 Used for" is not included in setloadfields and either is used the indirect "JALSLFE1 Used Code" in setloadfields).
Next queries include all fields of table "Fixed Asset", when they should be select the same fields than two first queries.

**5. Versions:**
- AL Language: v7.2.475273
- Visual Studio Code: 1.57.1
- Business Central: BC18.2 ES OnPrem  docker container.
- List of Visual Studio Code extensions that you have installed:

**Comment by ti-jalopez** [comment]
Hi,
Perhaps the documentation should indicate that these fields are added automatically to take this into account when designing table extensions.
For example, in the case of a tablerelation, you can change the code to add it in the OnLookup method instead of as the TableRelation property, which avoids the selection of the field and possibly a join if there are no more fields from the table added.
Regarding fields used in CalcFields, perhaps it can be taken into account if at the time of SetLoadFields there are fields with SetAutoCalcField activated, and consider only adding the fields if they are used in autocalfields. Alternatively, the calculated fields could be added in SetLoadFields to add the rest of the dependent fields.
In any case, as mentioned, this would be an improvement in the future if the performance of the currently designed system presents problems, according to the information captured from telemetry.
Best regards,

**Comment by thpeder** [comment]
Let's mark this as a bug for updating the documentation.

**Comment by atoader** [comment]
The doc change has been merged in and it will be pushed out with the next documentation refresh.
