### ISSUE TITLE
EVENT OnBeforeGenerateXML not valid for SAAS 

### ISSUE THREAD

**Issue by AitorLD** [microsoft/AL#6675]
- AL Extension Version:  7.2.475273

-Versión: ES Business Central 18.1 (Plataforma 18.0.24800.26946 + Aplicación 18.1.24822.24906)

This event subscriber is available from Codeunit SII XML Creator but its useless in cloud due to a parameter DOTNET.

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"SII XML Creator", 'OnBeforeGenerateXML', '', true, true)]
    local procedure OnBeforeGenerateXML(IsCreditMemoRemoval: Boolean;LedgerEntry: Variant;RetryAccepted: Boolean;SIIVersion: Option;UploadType: Option;var IsHandled: Boolean;var ResultValue: Boolean;**XMLDocOut: DotNet "System.Xml.XmlDocument"**)
var
begin
end;
```

ERROR: The type of the parameter 'XMLDocOut' on the event subscriber 'OnBeforeGenerateXML' does not match the expected type 'DotNet "System.Xml.XmlDocument"'.

**Comment by operrui** [comment]
Same problem

**Comment by atoader** [comment]
Hi! Welcome to the AL repository! Please take a minute to familiarize yourself with the purpose of this repository https://github.com/microsoft/AL/blob/master/README.MD and with the FAQ https://github.com/microsoft/AL/wiki/Frequently-Asked-Questions .
We believe that the issue you have opened is outside the scope of this repository. Please open it in the correct repository.
