### ISSUE TITLE
C# compilation has failed when using complex return value in case statment

### ISSUE THREAD

**Issue by MattiLE** [microsoft/AL#6679]
Hi AL-Team, 

when using complex data types in a case block with "else", a C# error occurs. 

**1. Describe the bug**
when using complex data types in a case block with "else", the error "C# compilation has failed for the application object PageExtension_50100" occurs. 

In our app, the error comes at runtime.
But you can also reproduce the error with an example app. There comes the error already when publishing. 

I could already find out that the error only occurs when there is an else in the case block.

**2. To Reproduce**

Steps and to reproduce the behavior:
1. Create a new AL Project with AL: Go
2. Change the CustomerListExt as follows: 

```
// Welcome to your new AL extension.
// Remember that object names and IDs should be unique across all extensions.
// AL snippets start with t*, like tpageext - give them a try and happy coding!

pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        AADApplicationInterface: Codeunit "AAD Application Interface";
    begin
        case Rec.Blocked of
            Rec.Blocked::" ":
                AADApplicationInterface := GetCodeunit();
            else
                AADApplicationInterface := GetCodeunit();
        end;
    end;

    local procedure GetCodeunit(): Codeunit "AAD Application Interface"
    var
        AADApplicationInterface: Codeunit "AAD Application Interface";
    begin
        exit(AADApplicationInterface);
    end;
}

```

3. Press F5 to publish the app 
4. Publish not possible

**3. Expected behavior**
The code should be executable without errors.

**4. Actual behavior**

The following error appears: 

The request for path /KT18/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: C# compilation has failed for the application object PageExtension_50100. 
The failing c# file name is 47E4A81AC1045C6062F417087ED52478F41E5BF3886539D25973393FCD26336D.cs. You can find this file with the associated AL file saved in the C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$KT18\apps\compilationerrors folder.
Detailed compilation error: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$KT18\apps\metadata\3\47\47E4A81AC1045C6062F417087ED52478F41E5BF3886539D25973393FCD26336D.cs(187,83): **error CS0103: The name 'δretValParent1' does not exist in the current context**

**5. Versions:**

- AL Language: v7.2.475273
- Visual Studio Code: 1.57.1
- Business Central: onprem 18.2

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 27637 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
