### ISSUE TITLE
what is wrong here?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/AL#668]
This issue has been moved from https://github.com/Microsoft/vscode/issues/34199

From @PeterBizz

---

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
al|ms-|0.7.12087
vscode-c-al|zod|0.0.11

I am trying to use the NAV financials AL to create extension.
I am completely new to VS CODE. 

I am only getting errors telling me that symbols could not be loaded. 
I have multiple Azure accounts and a Github acount with different user names. This might be related to the issue. 

The output window tells me this: 
[2017-09-12 09:09:41.88] Using reference symbols cache path: c:\Users\Peter\Documents\AL\ALProject1\packages
[2017-09-12 09:09:41.89] Authenticating...
[2017-09-12 09:09:43.91] Downloading from https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=10.0.0.0 ... Error (Forbidden)
[2017-09-12 09:09:44.13] Downloading from https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0 ... Error (Forbidden)
[2017-09-12 09:09:44.13] Could not download reference symbols

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by StanislawStempin** [comment]
Please follow the steps listed here if you want to use a Docker image with the server:
https://blogs.msdn.microsoft.com/nav/2017/09/07/nav-development-preview-september-update/

Or here if you want to sign up for online sandbox:
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-apps-for-fin

**Comment by PeterBizz** [comment]
HI Stanislaw,

I have followed the procedure with the Docker image.
This procedure ended as described in the call

I have used <ctrl>+<shift>+P and cleared credentials and then reentered peter.wijntjes@bizzbrain.nl<mailto:peter.wijntjes@bizzbrain.nl> credentials

Seems download of symbols fails. Can you help?





The output window tells me this:
[2017-09-12 09:09:41.88] Using reference symbols cache path: c:\Users\Peter\Documents\AL\ALProject1\packages
[2017-09-12 09:09:41.89] Authenticating...
[2017-09-12 09:09:43.91] Downloading from https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=10.0.0.0 ... Error (Forbidden)
[2017-09-12 09:09:44.13] Downloading from https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0 ... Error (Forbidden)
[2017-09-12 09:09:44.13] Could not download reference symbols



Van: Stanislaw Stempin [mailto:notifications@github.com]
Verzonden: 12 September 2017 11:47
Aan: Microsoft/AL <AL@noreply.github.com>
CC: Bizzbrain | Peter Wijntjes <peter.wijntjes@bizzbrain.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Microsoft/AL] what is wrong here? (#668)


Please follow the steps listed here if you want to use a Docker image with the server:
https://blogs.msdn.microsoft.com/nav/2017/09/07/nav-development-preview-september-update/

Or here if you want to sign up for online sandbox:
https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-apps-for-fin

**Comment by StanislawStempin** [comment]
How does your launch.json look like. Are you pointing to the right server and using the right authentication method?

**Comment by PeterBizz** [comment]
Hi Stanislaw –

This is a picture of VStudio Code with the ALproject1 and  Launch.json.
You can see the error in the bottom and the green line under authentication.

[cid:image002.jpg@01D32E09.95C5D4F0]

Van: Stanislaw Stempin [mailto:notifications@github.com]
Verzonden: 12 September 2017 18:30
Aan: Microsoft/AL <AL@noreply.github.com>
CC: Bizzbrain | Peter Wijntjes <peter.wijntjes@bizzbrain.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Microsoft/AL] what is wrong here? (#668)


How does your launch.json look like. Are you pointing to the right server and using the right authentication method?

**Comment by StanislawStempin** [comment]
Can you please include the pictures? The only thing I see is a tag [cid:image002.jpg@01D32E09.95C5D4F0]

**Comment by PeterBizz** [comment]
![image](https://user-images.githubusercontent.com/16479136/30473253-0df77746-9a00-11e7-9d33-e4e0f27aa1f3.png)

And also app.json
![image](https://user-images.githubusercontent.com/16479136/30473465-d7259eea-9a00-11e7-8155-6e21af18c354.png)


![image](https://user-images.githubusercontent.com/16479136/30473326-5b3eeebc-9a00-11e7-9a86-2dd76507dc02.png)


![image](https://user-images.githubusercontent.com/16479136/30473373-8ba504e2-9a00-11e7-8806-bf529dff4473.png)

**Comment by StanislawStempin** [comment]
The problem seems that you are using old version of the AL Language extension. Please install the one that is available on the landing page that you've shown above al-0.9.12794.

**Comment by PeterBizz** [comment]
Ok, I have downloaded the file al-0.9.12794 

It opens with Visual Studio Version Selector and then this is created: 

![image](https://user-images.githubusercontent.com/16479136/30476508-8379a318-9a0a-11e7-96e0-9b4c594c4e46.png)

I have tried to open it with visual studio code , but this is not working. 
What steps to take to replace the current, -wrong- version with this - correct- version?

**Comment by PeterBizz** [comment]
Ok , now found how to install the vsix, next problem is credentials

**Comment by PeterBizz** [comment]
The message is: the Server Requires autenthication.

I do not see which server, what authentication. (I have multiple accounts)

![image](https://user-images.githubusercontent.com/16479136/30477481-a0b7d5be-9a0d-11e7-8c43-f0fe442ae254.png)

**Comment by DominikDitoIvosevic** [comment]
What is your authentication option in the launch.json?

**Comment by PeterBizz** [comment]
same as earlier in this thread: 
{
	"version": "0.2.0",
	"configurations": [
		
		{
			"type": "al",
			"request": "publish",
			"server": "https://navseptvm1.eastus.cloudapp.azure.com",
			"serverInstance": "NAV",
			"tenant": "",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}
	]
}
![image](https://user-images.githubusercontent.com/16479136/30478761-a60124a8-9a12-11e7-8fba-4665e6340dd0.png)

**Comment by PeterBizz** [comment]
I have tried with my vmadmin account as well

**Comment by StanislawStempin** [comment]
The username is admin, password is the same that you provided when provisioning the VM.

**Comment by PeterBizz** [comment]
thanks a lot, now symbols do load! 

will continue from here

**Comment by PeterBizz** [comment]
Next issue. 
When I use Debug and Select Dynamics NAV

![image](https://user-images.githubusercontent.com/16479136/30481785-a4f200ba-9a20-11e7-9325-80fc35340aa9.png)

I do not know what account to use here. If I use the account with which I created the Azure VM I get this

![image](https://user-images.githubusercontent.com/16479136/30481730-772c9690-9a20-11e7-9666-8ff48970a3bb.png)

**Comment by PeterBizz** [comment]
Yes,  
this is what I have done so far: 
- Install Visual Studio Code  ( local) 
- Create Azure Virtual machine from the Dynamics 365 Sept Development Preview page

Now I try to 
- Access the Microsoft Dynamics NAV "Tenerife" Developer Preview using Visual Studio Code
I have succesfully created a package and now I would like to test (deploy?) the Package to the Azure machine. 
In order to do that I press F5, then the screens above appear. 
launch.json is still: 
{
	"version": "0.2.0",
	"configurations": [
	
		{
			"type": "al",
			"request": "publish",
			"server": "https://navseptvm1.eastus.cloudapp.azure.com",
			"serverInstance": "NAV",
			"tenant": "",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}
	]
}

**Comment by PeterBizz** [comment]
there is also a warning: 

![image](https://user-images.githubusercontent.com/16479136/30485236-12011392-9a2d-11e7-8c04-f6aaab410b9a.png)

**Comment by StanislawStempin** [comment]
Try adding the name property with any name in it and restart vs code.
