### ISSUE TITLE
Rule AA0072 only allows omitting defined affix/prefix/suffix on some object types, but not report/query (etc.?)

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6681]
With this code:

```al
table 50100 MyTestTableFOO
{
    DataClassification = CustomerContent;

    fields
    {
        field(50100; TableFieldFOO; Boolean)
        {
        }
    }
}

page 50100 MyTestPageFOO
{
    UsageCategory = None;
}

report 50100 MyTestReportFOO
{
    UsageCategory = None;
}

query 50100 MyTestQueryFOO
{
    elements
    {
        dataitem(Sales_Header; "Sales Header")
        {
            column(No_; "No.")
            {
            }
        }
    }
}

codeunit 50100 MyTestCodeunitFOO
{
    trigger OnRun()
    var
        MyTestTable: Record MyTestTableFOO;
        MyTestReport: Report MyTestReportFOO;
        MyTestCodeunit: Codeunit MyTestCodeunitFOO;
        MyTestPage: Page MyTestPageFOO;
        MyTestQuery: Query MyTestQueryFOO;
    begin
    end;
}
```

Most object types that I've tried can have the affix omitted from variables thereof, but for some reason `Report` and `Query` objects cannot, and AA0072 complains about them:

![image](https://user-images.githubusercontent.com/63455896/123302580-c2407b00-d514-11eb-9d47-5462b47f6282.png)

Presumably this allowance of omitting the defined affix is meant to work for any object type? If so, please fix this so that it will. If not, an explanation/documentation why not is required.

Thanks!

AL extension:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.2.475273
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by Ugniusig** [comment]
Also a TestPage object is shown as a warning

**Comment by dnpb** [comment]
What is an example of the code, and what specific warning do you get?

**Comment by Ugniusig** [comment]
The same as you get @dnpb 
source code - https://github.com/Ugniusig/ALWarningExample

![image](https://user-images.githubusercontent.com/79054854/171581910-808ebc86-919e-4604-88a0-f4ee2677f16e.png)

AL extension:

``` 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: v9.0.615906
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
