### ISSUE TITLE
Event OnGetSpecialOrdersOnAfterSalesLineSetFilters in Codeunit "Dist. Integration"

### ISSUE THREAD

**Issue by JayDashti** [microsoft/AL#6682]
Hello,

Could you please look into event OnGetSpecialOrdersOnAfterSalesLineSetFilters in Codeunit  5702 "Dist. Integration".

[IntegrationEvent(false, false)]
local procedure OnGetSpecialOrdersOnAfterSalesLineSetFilters(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header")
begin
end;

I believe the second parameter that you are publishing with this evet should be PurchaseHeader and not SalesHeader. We would need PurchaseHeader so then we can set more filter to SalesLine based on PurchaseHeader!

procedure GetSpecialOrders(var PurchHeader: Record "Purchase Header")
    var
        SalesHeader: Record "Sales Header";
        ItemUnitOfMeasure: Record "Item Unit of Measure";
        Vendor: Record Vendor;
        NextLineNo: Integer;
        IsHandled: Boolean;
    begin

            ....

            SalesLine.Reset();
            SalesLine.SetRange("Document Type", SalesLine."Document Type"::Order);
            SalesLine.SetRange("Document No.", SalesHeader."No.");
            SalesLine.SetRange("Special Order", true);
            SalesLine.SetFilter("Outstanding Quantity", '<>0');
            SalesLine.SetRange(Type, SalesLine.Type::Item);
            SalesLine.SetFilter("No.", '<>%1', '');
            SalesLine.SetRange("Special Order Purch. Line No.", 0);
            **OnGetSpecialOrdersOnAfterSalesLineSetFilters(SalesLine, SalesHeader);**
            if SalesLine.FindSet then
                repeat
                   ...

And to compare, you have a similar event in Codeunit 76 "Purch.-Get Drop Shpt." and there you are already sending PurchaseHeader as the second param:

IntegrationEvent(false, false)]
local procedure OnCodeOnAfterSalesLineSetFilters(var SalesLine: Record "Sales Line"; PurchHeader: Record "Purchase Header")
begin
end;

codeunit 76 "Purch.-Get Drop Shpt."
{
....

local procedure "Code"()
    var
        PurchLine2: Record "Purchase Line";
        IsHandled: Boolean;
    begin
        with PurchHeader do begin
            TestField("Document Type", "Document Type"::Order);

            if "Sell-to Customer No." = '' then
                Error(SelltoCustomerBlankErr);
                
                 ....

            SalesLine.SetRange("Document Type", SalesLine."Document Type"::Order);
            SalesLine.SetRange("Document No.", SalesHeader."No.");
            SalesLine.SetRange("Drop Shipment", true);
            SalesLine.SetFilter("Outstanding Quantity", '<>0');
            SalesLine.SetRange(Type, SalesLine.Type::Item);
            SalesLine.SetFilter("No.", '<>%1', '');
            SalesLine.SetRange("Purch. Order Line No.", 0);
            **OnCodeOnAfterSalesLineSetFilters(SalesLine, PurchHeader);**

            if SalesLine.Find('-') then
                repeat

**Comment by dtkb** [comment]
Such issues should be posted on https://github.com/microsoft/ALAppExtensions/issues instead as they are not about the compiler but rather the extensibility of the base app.
