### ISSUE TITLE
SetSelectionFilter does not work properly properly when changing from multiple selection in a list to single line selection in the same list 

### ISSUE THREAD

**Issue by estherachalandabaso** [microsoft/AL#6683]
**1. Describe the bug**
Page.SetSelectionFilter(var Record: Record) method does not update properly the Record when changing from multiple selection in a list to single line selection in the same list .

**2. To Reproduce**

1. Go to Items List Page in Dynamics 365 Business Central
2. Select 3 item lines, for example , with No: 1010, 1011, 1012
3 Execute the action  Actions->Functions> Calculate Counting Period-
   The action is executed successfully for the selected lines,
4. Deselect the lines with No.: 1010 and 1011 and maintain selected the line with No. 1012.
5 .Execute the action  Actions->Function> Calculate Counting Period. This action is not executed for the selected line, it is executed for the line with No. 1011, that did not remain selected.

**3. Expected behavior**
When a user selects a set of records on a page, Page.SetSelectionFilter(var Record: Record) method refers to these selected records in Record parameter.
If we deselect some of these records and maintain selected only one of the initial set of the records , and call the method Page.SetSelectionFilter(var Record: Record) , Record parameter is expected to refer to the only selected record.

**4. Actual behavior**
When a user selects a set of records on a page, Page.SetSelectionFilter(var Record: Record) method refers to these selected records in Record parameter.
If we deselect some of these records and maintain selected only one of the initial set of the records , and call the method Page.SetSelectionFilter(var Record: Record) , Record parameter does not refer to the record that is seleted. It refers to one of the initial set of records that have been deselected.

**5. Versions:**

- AL Language: v7.2.475273

- Business Central: w1 17.1

**Comment by dtkb** [comment]
I think in your 3rd step, it is taking the line that **last** had the cursor focus/'selection' - rather than just a random "one of" the deselected ones. It should definitely take the one that was last left selected and still has the visible highlight to indicate focus, though! D'oh.

On a super quick test, I see this: the item with No underlined is the last one I deselected, thus seeming to leave the line tinted blue selected - but the underline suggests maybe BC thinks it's the other line selected. I didn't yet write code using `SetSelectionFilter()` though.

**Comment by dtkb** [comment]
Confirmed:

First select the top 3 items:
![image](https://user-images.githubusercontent.com/63455896/123437373-85818c00-d5c7-11eb-9f7f-6872fa9adf6f.png)

then deselect the top 2, and run the Calculate Counting Period action:
![image](https://user-images.githubusercontent.com/63455896/123437492-a0540080-d5c7-11eb-8676-abc6b1dff8c7.png)
Note that the 3rd line has the visual focus, **except** that the 2nd line has an underline on its No.

Execute the action - instead of running on the seemingly left-selected 3rd line, it runs on the 2nd!
![image](https://user-images.githubusercontent.com/63455896/123437614-c5e10a00-d5c7-11eb-933c-765ae1ab6f4b.png)

Btw, while this looks like a real bug, I suspect it is not on-topic for the compiler issue repo, and will have to be submitted to the platform team via a partner. Hopefully you have one?

**Comment by kalberes** [comment]
Yes, this issue would not qualify here. If you want a fast resolution the best is to ask for a request for hotfix.
Officially:
"We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using."

**Comment by dtkb** [comment]
I have filed this with our partner, just in case it otherwise gets missed.

**Comment by estherachalandabaso** [comment]
Thanks,  I am going to open a request through our partner too.

**Comment by db-bc** [comment]
It got there eventually!

![image](https://user-images.githubusercontent.com/63455896/125267628-e8c92900-e2fe-11eb-8d38-349be28caee6.png)

**Comment by db-bc** [comment]
repro that doesn't depend on the Calculate Item Counting Period action (which calls some code that does odd things with Marked/filters, but doesn't seem responsible for this)

```al
pageextension 66666 Test extends "Item List"
{
    actions
    {
        addfirst(processing)
        {
            action(Test)
            {
                ApplicationArea = All;
                Caption = 'Test';
                Image = Warning;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;
                ToolTip = 'Test a thing';

                trigger OnAction()
                var
                    Item: Record Item;
                    ItemNos: Text;
                begin
                    CurrPage.SetSelectionFilter(Item);
                    Item.SetLoadFields("No.");
                    Item.FindSet();

                    repeat
                        if ItemNos <> '' then
                            ItemNos += ' ; ';

                        ItemNos += Item."No.";
                    until Item.Next() = 0;

                    Message(ItemNos);
                end;
            }
        }
    }
}
```

**Comment by db-bc** [comment]
I have received this feedback from MS:

>I created a sample extension from the provided code, uploaded it to my 17.6 environment, and showed it to the Development team at the meeting we had today.
>
>The team noted that this behavior was reported last year, and a team member described it in this blog post.
>[Different behavior when enabling Select More feature and Current record position in Web Client - Dynamics 365 Business Central Forum Community Forum](https://community.dynamics.com/business/f/dynamics-365-business-central-forum/389131/different-behavior-when-enabling-select-more-feature-and-current-record-position-in-web-client)
>
> From what the engineer pointed it seems to note that currently, this is the expected behavior.
>
>I also asked them if the repair item I was able to find for 17.9 will mitigate this behavior however they did not provide feedback on it.

***

My response was this:

> Thanks for the link. However, it states this:
> 
> > 1.	“Enable “Select More” feature
> > 2.	Select the first posted sales invoice line (or whatever record item in a list you like)
> > 3.	Select the second posted sales invoice line
> > 4.	Deselect the 2nd 
> 
> And:
> 
> > Below you can see the latest fully patched 14.x Windows Client and it is showing exactly the same thing.
> > 
> > When using CTRL+CLICK key to select multiple items and then use CTRL+CLICK to deselect items, you would fall back in the same scenario
> > 
> > ![image](https://user-images.githubusercontent.com/63455896/125462566-949787e9-b903-4b85-a279-fcc244113965.png)
> >
> > In the case above, SETSELECTIONFILTER will register the first record (103027) while Navigate actions will stick with the cursor position and open/navigate using 103026 posting date and No.
> 
> So, it says that SetSelectionFilter() will get the record with the selection highlight, not the cursor rectangle/line – but what we have shown in our code samples is that the Web Client is not working that way, and is instead returning from SetSelectionFilter() the record that was last deselected, not the one that is left selected.
> 
> So it seems that the above article, while useful generally, does not explain the different behaviour we have demonstrated in the Web Client.
> 
> I have amended the latest example code to replicate the exact scenario as the Windows Client pic from that article:
> 
> ```al
> pageextension 66666 Test extends "Posted Sales Invoices"
> {
>     actions
>     {
>         addfirst(processing)
>         {
>             action(Test)
>             {
>                 ApplicationArea = All;
>                 Caption = 'Test';
>                 Image = Warning;
>                 Promoted = true;
>                 PromotedCategory = Process;
>                 PromotedOnly = true;
>                 ToolTip = 'Test a thing';
> 
>                 trigger OnAction()
>                 var
>                     SalesInvoiceHeader: Record "Sales Invoice Header";
>                     DocumentNos: Text;
>                 begin
>                     CurrPage.SetSelectionFilter(SalesInvoiceHeader);
>                     SalesInvoiceHeader.SetLoadFields("No.");
>                     SalesInvoiceHeader.FindSet();
> 
>                     repeat
>                         if DocumentNos <> '' then
>                             DocumentNos += ' ; ';
> 
>                         DocumentNos += SalesInvoiceHeader."No.";
>                     until SalesInvoiceHeader.Next() = 0;
> 
>                     Message(DocumentNos);
>                 end;
>             }
>         }
>     }
> }
> ```
> 
> Which results in this:
>  
> ![image](https://user-images.githubusercontent.com/63455896/125462587-3ce7dad8-d451-4997-a40e-0149b932efd5.png)
> 
> So, not what the article says would happen – SetSelectionFilter() is not returning the drawn-as-selected 103027 but instead the drawn-with-cursor 103026.
> 
> Can you please revisit?

**Comment by navdotnetreqs** [comment]
Happy to see this has not been properly fixed. :S

**Comment by navdotnetreqs** [comment]
Still waiting!
