### ISSUE TITLE
Cannot debug / set breakpoints on case statements

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6684]
**1. Describe the bug**
Set breakpoint on case statement. System will tell you breakpoint cannot be added. This bug: #6084

**2. To Reproduce**
Write a case statement. Try to set breakpoints.

**3. Expected behaviour**
Don't disable my breakpoints.

**4. Actual behaviour**
See above

**5. Versions:**
- AL Language: v7.2.475273
- Visual Studio Code: Version: 1.57.1
- Business Central: Version: W1 17.5 (Platform 17.0.22463.23157 + Application 17.5.22499.23279)
- List of Visual Studio Code extensions that you have installed: None that affect this.

**Comment by kalberes** [comment]
You mean while you are debugging you cannot set a breakpoint on a case statement?
Or before you debug you set a breakpoint on a case statement and the the breakpoint will not hit. More you get the error message? Is the repro the same as for the linked bug? Since for that I have no repro.

**Comment by mjmatthiesen** [comment]
Hi,

Either before the debug or while debugging. The breakpoint become inactive and you'll get an "error not possible to set breakpoint" in your log.

Same reproduce as before.

**Comment by kalberes** [comment]
That could also mean that your local source code is "old" compared to what is on the server, thus teh line on which you set a breakpoint cannot resolve.

**Comment by mjmatthiesen** [comment]
How does that happen when I hit F5 to publish and debug? I assume it's because of what the transpiled code looks like on the BC side? It's not exactly the most consistent thing. Every now and then it'll work, but I really don't have rhyme or reason for it.

**Comment by kalberes** [comment]
And just to confuse more it could also mean the inverse that the .net code has not been generated on the server for that application object yet, thus a breakpoint cannot resolve.
