### ISSUE TITLE
DelayedInsert shouln't be forced for API Pages with Editable = false

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6685]
Please include the following with each issue:

**1. Describe the bug**
Right now I have to set `DelayedInsert = true` for any API Page.

**2. To Reproduce**

``` AL
page 50000"TEST Cust.Led.Entry"
{
    APIGroup = 'test';
    APIPublisher = 'test';
    APIVersion = 'beta';
    Caption = 'Customer Ledger Entry';
    DataAccessIntent = ReadOnly;
    Editable = false;
    EntityCaption = 'Customer Ledger Entry';
    EntityName = 'custLedgerEntry';
    EntitySetCaption = 'Customer Ledger Entries';
    EntitySetName = 'custLedgerEntries';
    Extensible = false;
    ODataKeyFields = SystemId;
    PageType = API;
    SourceTable = "Cust. Ledger Entry";

    layout
    {
        area(Content)
        {
            repeater(GroupName)
            {
                field(acceptedPaymentTolerance; Rec."Accepted Payment Tolerance")
                {
                    Caption = 'Accepted Payment Tolerance';
                }
            }
        }
    }
}
```

**3. Expected behavior**
DelayedInsert shouln't be forced for API Pages with `Editable = false` or with `InsertAllowed = false`

**4. Actual behavior**
Right now I get the following warning:

> Pages of type API must have the DelayedInsert property set to true.

**5. Versions:**

- AL Language:
- Visual Studio Code: 7.2.475273

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thpeder** [comment]
Thanks for reporting the issue. I agree that it doesn't seem like "DelayedInsert" is needed.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 27520 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by pri-kise** [comment]
@JesperSchulz will this fix be downgraded to previous major versions too?

**Comment by JesperSchulz** [comment]
Only to version 18. If you'd like this to get backported to older versions, @thpeder might be able to help :-)

**Comment by pri-kise** [comment]
At least BC 17 might be  very helpul. Then we could clean up our could already in the current BC 17.
