### ISSUE TITLE
Passed parameters to ReportVariable.Execute(parameters) not being used  

### ISSUE THREAD

**Issue by SanderCMD** [microsoft/AL#6688]
This bug has already been reported but it should be fixed according to the comments in following github post:
https://github.com/microsoft/AL/issues/5710
This issue is still happening on version 18.2.26217.26331

**Describe the bug**
Different behavior of the following methods:

Passing parameters to MyReportVariable.Execute(Parameters) - report does not use the parameters that are supplied.
When using the standard Report.Execute(ReportNo, Parameters) - report takes parameters into account

In my case i can not use the second way of doing this, because i need to use certain procedures in the report variable.
This is not possible with the second way.

**To Reproduce**
Steps and to reproduce the behavior:

1- Deploy extension
2- Run the report request page:   Parameters := MyReportVariable.RunRequestPage();
3- Use the parameters variable: MyReportVariable.Execute(Parameters)
4- Parameters are not used while rendering report

**Comment by thpeder** [comment]
Hi @SanderCMD,
Could you please provide a complete and simple example project that reproduces the issue.
Thanks!

**Comment by SanderCMD** [comment]
Hello @thpeder,
The following code snipper is where I encountered this.
It adds an action to the warehouse shipment list, to create picks for multiple warehouse shipments in 1 go.
I want to use the request page 1 time and apply the parameters to every pick. Let me know if I can clarify further.

```
pageextension 51800 "Warehouse Shipments Ext" extends "Warehouse Shipment List"
{
    layout
    {
    }

    actions
    {
        addlast("F&unctions")
        {
            action("Create Picks")
            {
                ApplicationArea = Warehouse;
                Caption = 'Create warehouse picks';
                Image = CreateInventoryPickup;
                ToolTip = 'Create warehouse picks for the selected warehouse shipments.';

                trigger OnAction()
                var
                    ReleaseWhseShipment: Codeunit "Whse.-Shipment Release";
                    WhseShipmentHeader: Record "Warehouse Shipment Header";
                    WhseShipmentCreatePick: Report "Whse.-Shipment - Create Pick";
                    WhseShptLine: record "Warehouse Shipment Line";
                    HideValidationDialog: Boolean;
                    Parameters: Text;
                begin
                    HideValidationDialog := true;
                    WhseShipmentHeader := Rec;
                    CurrPage.SetSelectionFilter(WhseShipmentHeader);

                    if WhseShipmentHeader.findfirst() then begin
                        Parameters := WhseShipmentCreatePick.RunRequestPage();
                        repeat
                            WhseShptLine.Reset();
                            WhseShptLine.SetRange("No.", WhseShipmentHeader."No.");
                            // release if still open
                            if WhseShipmentHeader.Status = WhseShipmentHeader.Status::Open then
                                ReleaseWhseShipment.Release(WhseShipmentHeader);
                            // if there are lines with quantities that are not completely picked, start create picks
                            WhseShptLine.SetFilter(Quantity, '>0');
                            WhseShptLine.SetRange("Completely Picked", false);
                            if WhseShptLine.Find('-') then begin
                                Clear(WhseShipmentCreatePick);
                                WhseShipmentCreatePick.SetWhseShipmentLine(WhseShptLine, WhseShipmentHeader);
                                WhseShipmentCreatePick.SetHideValidationDialog(HideValidationDialog);
                                WhseShipmentCreatePick.UseRequestPage(not HideValidationDialog);
                                // WhseShipmentCreatePick.RunModal;
                                WhseShipmentCreatePick.Execute(Parameters);
                                WhseShipmentCreatePick.GetResultMessage;
                            end;

                        until WhseShipmentHeader.next() = 0;
                        Message('The warehouse picks were created.');
                    end;
                end;
            }
        }
    }
}
```

**Comment by SanderCMD** [comment]
Hello @thpeder ,
Was my code snippet enough for you to further examine this issue?

Thanks!

**Comment by thloke** [comment]
@SanderCMD - thanks for the code sample. This is sufficient for us to investigate, I'll mark this as a bug and accept it.

**Comment by thloke** [comment]
@SanderCMD  - I've tried reproducing the bug with a simple project, but as far as I can tell the parameters are being passed correctly to the Execute function. I have a theory on what is happening here though. Looking at the report you're trying to execute, the request page has an OnOpenPage trigger defined, which sets additional variables on the report itself as well as raises additional events. This is important, because parameters captured by Report.RunRequestPage only contains the state of the fields on the request page. It does not capture the state of any additional variables on the report itself, and when Report.Execute is run, it does not run the request page again - so the OnOpenPage trigger will not be run, and any additional variables that are set will not be set.

I'm not too familiar with this report itself, but it's possible that you can capture the additional variables necessary with the integration events provided. If not, it might be an extensibility request for our application team.

If you can repro the issue of Execute not getting the right params with a small project and a simpler report that doesn't use triggers to populate additional variables, feel free to reopen this issue.

**Comment by SanderCMD** [comment]
It appears I missed the OnOpenPage trigger like you said in your theory. The trigger adds some logic (that I overlooked) to a boolean that i tried to pass in the parameters. 

Thank you for your response! Not a bug.
