### ISSUE TITLE
Extending the Navigation Pane page

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#669]
In the faq it says:
The second purpose can be achieved by extending the Navigation Pane page.

How do you do that? I don't see a way to extend the navigation pane in al and no documentation on this.

**Comment by StanislawStempin** [comment]
Sorry, not very intuitive, but now we have it documented:)
```
pageextension 50102 ExtendNavigationPane extends "Business Manager Role Center" 
{
  actions 
  {
    addlast(Embedding) 
    {
      action("Open my new page") 
      {
        RunObject = page "Customer Bank Account List";
        ApplicationArea = All;
      }
    }
  }
}
```

**Comment by johndcollins** [comment]
So this is not really adding to the MenuSuite and the department area. This is adding to a Role Center.

Speaking about Role Centers, how would you add a new ActionGroup under ActivityButtons after action <Page Customer List - Order Status>?

I hope this will change very soon. It's really critical to be able to add other role centers.
The same with adding to the Department area. That should be possible by now.

**Comment by esbenk** [comment]
We are investigating adding pages and reports to search and expect to support that soon. That only use of MenuSuite in the web-client. Extending the department area will come later.

I'm not sure about the about the question on adding the ActionGroup. Can you share an image of where you want to add the ActionGroup?

You can add new Role Centers together with the new Profile. If that is what you need - or maybe I don't understand exactly what you want.

**Comment by johndcollins** [comment]
Here is an example what I would expect it to look like, but this is not working.

pageextension 51000 ExtendNavigationPane extends "Order Processor Role Center"
{
    
  actions 
  {
    addlast("Page Time Sheet List") 
    {
        actionGroup("MyNewActionGroup")
        {
            action("Open my new page") 
            {
                RunObject = page "Customer Bank Account List";
                ApplicationArea = All;
            }
        }
    }
  }
}

**Comment by esbenk** [comment]
I have extended the "Order Processor Role Center" in W1 with 

```
pageextension 50100 ExtendNavigationPane extends "Order Processor Role Center"
{

    actions
    {
        addlast(Sales)
        {
            group("MyNewActionGroup")
            {
                action("Open my new page")
                {
                    RunObject = page "Customer Bank Account List";
                    ApplicationArea = All;
                }
            }
        }
    }
}
```

with the following result

<img width="765" alt="screen shot 2017-10-04 at 14 10 02" src="https://user-images.githubusercontent.com/24257835/31175042-2349463e-a90e-11e7-83f3-4f294152ca36.png">

Are you expecting something else? I have tested with what will be the October preview, but it may work on the September preview too.

**Comment by johndcollins** [comment]
I'm trying to get it over here:
![image](https://user-images.githubusercontent.com/1684130/31181186-893feaee-a8d5-11e7-8f95-937f666f58f3.png)

**Comment by StanislawStempin** [comment]
Please try addlast(Sections) instead of addlast(Sales) as suggested in the example above.
