### ISSUE TITLE
BC Server warning with Enum Object name exceeding a length of 30 with identical first 30 characters

### ISSUE THREAD

**Issue by StHillmann** [microsoft/AL#6691]
**1. Describe the bug**
While you can create Enums with Object name exceeding a length of 30 without neither the compiler nor the runtime create errors, the Server Instance is logging a warning if the first 30 characters of two enums are the same!

Warning:
```
Server instance: BC
Category: Metadata
ClientSessionId: 2cbfce14-f375-4716-a715-0b70ee498e42
ClientActivityId: a3c80dbc-0937-4602-9614-4299e81698d6
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 22222a4c-7027-4c79-83f6-1f1f442551e0
EventTime: 07/02/2021 12:11:24
Message The object name 'MyEnumTestWithLongObjectNameFo' can only appear once for the type 'Enum'. The same object exists in both extension ('5abd5e44-96bd-4ef2-9084-61d76815d7b2' 'ALProjectLongEnumsObjectNames', Publisher: Default publisher, Package ID: 2da0348d-77ae-498d-a8ef-608689b60c72, Runtime Package ID: 2da0348d-77ae-498d-a8ef-608689b60c72, Scope: Tenant, Version: 1.0.0.0) and in extension ('5abd5e44-96bd-4ef2-9084-61d76815d7b2' 'ALProjectLongEnumsObjectNames', Publisher: Default publisher, Package ID: 2da0348d-77ae-498d-a8ef-608689b60c72, Runtime Package ID: 2da0348d-77ae-498d-a8ef-608689b60c72, Scope: Tenant, Version: 1.0.0.0).
ProcessId: 2344
Tag: 0000ES3
ThreadId: 136
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

By the way: 
The Standard W1 App [VATGroupManagement](https://github.com/microsoft/ALAppExtensions/tree/master/Apps/W1/VATGroupManagement) is running into the same warning, while the included Enums "VAT Group Authentication Type Saas" and "VAT Group Authentication Type OnPrem" are identical for the first 30 characters!

See warning:
```
Server instance: BC
Category: Metadata
ClientSessionId: 82bddaa1-a08a-4a86-aefd-487b02471803
ClientActivityId: cac20905-9c78-44c6-9f14-e15c63dc2fb1
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 22222a4c-7027-4c79-83f6-1f1f442551e0
EventTime: 07/02/2021 12:29:23
Message The object name 'VAT Group Authentication Type ' can only appear once for the type 'Enum'. The same object exists in both extension ('c50a4bf0-db51-4ad2-88d5-fe2287da0eb8' 'VAT Group Management', Publisher: Microsoft, Package ID: 66578977-d631-4ed5-b28b-ecf072793df5, Runtime Package ID: cbdac38c-32eb-4d84-8392-a70a63af7d07, Scope: Global, Version: 18.1.24822.26330) and in extension ('c50a4bf0-db51-4ad2-88d5-fe2287da0eb8' 'VAT Group Management', Publisher: Microsoft, Package ID: 66578977-d631-4ed5-b28b-ecf072793df5, Runtime Package ID: cbdac38c-32eb-4d84-8392-a70a63af7d07, Scope: Global, Version: 18.1.24822.26330).
ProcessId: 2344
Tag: 0000ES3
ThreadId: 96
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

```

**2. To Reproduce**

1. Create a new AL App using "AL:Go" in VS Code
2. Create a new Enum with an object name exceeding 30 characters (e.g. "MyEnumTestWithLongObjectNameForMS1")
``` AL
enum 50100 "MyEnumTestWithLongObjectNameForMS1"
{
    Extensible = true;

    value(0; EnumValue1)
    {
    }
    value(1; EnumValue2)
    {
    }
}
```
3. Create another new Enum with an object name new exceeding 30 characters where the first 30 characters are equal to the enum created at step 2. (e.g. MyEnumTestWithLongObjectNameForMS2)
``` AL
enum 50101 "MyEnumTestWithLongObjectNameForMS2"
{
    Extensible = true;

    value(0; MyValue1)
    {
    }
    value(1; MyValue2)
    {
    }
    value(2; MyValue3)
    {
    }
}
```
4. Publish the app
5. Open the event log of the Server Instance and have a look on the latest warnings for the warning described above.

**3. Expected behavior**
Either the AL compiler must also reject object names with length over 30 characters, or the service must be able to handle them without warnings.

**4. Actual behavior**
See warning above

**5. Versions:**

- AL Language: 7.2.475273
- Visual Studio Code: 1.57.1
- Business Central: W1 18.1 (Platform 18.0.24800.26311 + Application 18.1.24822.26330)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28803 and VS Code Extension Version 8.0.501212. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
