### ISSUE TITLE
[EventParameter] New parameter required in event OnAfterShouldFinalizeSalesInvHeader of report "Combine Return Receipts"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/AL#6698]
We need that the event OnAfterShouldFinalizeSalesInvHeader from the report 6653 "Combine Return Receipts" contains the same paremeters than the same event of the report 295 "Combine Shipments".

In the report 295 there is a 4th parament with the sales shipment line that we are looping. In the report 6653 there are only 3 parameters and we need the "Return Receipt Line" that we are looping.

**Comment by db-bc** [comment]
wrong repo; you want https://github.com/microsoft/ALAppExtensions/issues instead

**Comment by TriangleSPV** [comment]
Created issue in correct repo.
