### ISSUE TITLE
Question: FunctionVisibility

### ISSUE THREAD

**Issue by ReneGubler** [Microsoft/AL#67]
Hi

What is the exact use of the property FunctionVisibility(External/Internal) in functions? What is the difference to Local(Yes/No)

**Comment by StanislawStempin** [comment]
I will largely oversimplify as this is still under development but for now the way to think about it is that procedures marked with Visibility = Internal cannot to be used from extensions. Procedure marked with Visibility = External can.
When trying to call a procedure marked Internal from extension code you will see the following error:
![external](https://cloud.githubusercontent.com/assets/23653165/21889282/746aaf92-d8c8-11e6-98dd-80448b5667c6.png)
