### ISSUE TITLE
AL language versions and 'Extension' development support 

### ISSUE THREAD

**Issue by michaelsimonsendk** [Microsoft/AL#670]
AL language version 0.7.12087 is downloaded to my local VS Code installation but doesn't support the 
method "DOWNLOADFROMSTREAM". 
On my NAV Development Preview – September Update with AL language version 0.9.12794 my AL code is supported 

When is it possible to download/update the AL language to my local VS code?

Or is the method "DOWNLOADFROMSTREAM" not going to be used for 'Extension' development?

CODE:
`DOWNLOADFROMSTREAM(iStream,'Export','','All Files (*.*)|*.*',ToFileName);`

**Comment by StanislawStempin** [comment]
The AL Language extension that's available on the marketplace follows the product version available in the Microsoft Cloud Sandboxes. It will be a few more weeks before version 0.9 becomes available there.

But you are free to install the AL Language version 0.9 from Developer Preview on your local machine by going to VS Code, uninstalling the 0.7 extension and the selecting the option "Install from VSIX...": https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by StanislawStempin** [comment]
The AL Language extension available on the Marketplace is now also on version 0.9
