### ISSUE TITLE
Disable AL0604 and AL0606 with pragma are not working

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/AL#6700]
**1. Describe the bug**
It is not possible to disable warning AL0604 and AL0606 if this should throw an error.

**2. To Reproduce**
Create this AL-File:
``` 
codeunit 50002 "Test"
{
    Access = Internal;
    TableNo = Item;
    trigger OnRun()
    var
        Item: Record Item;
    begin
#pragma warning disable AL0604,AL0606
        Copy(Item);
        with Item do begin
            Description := Format(CurrentDateTime());
        end;

    end;

}
```
use this ruleset:
```
{
    "name": "Our ruleset",
    "description": "Some specific rules",
    "rules": [
        {
            "id": "AL0604",
            "action": "Error",
            "justification": "Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'."
        },
        {
            "id": "AL0606",
            "action": "Error",
            "justification": "The 'with' statement is deprecated and will be removed for cloud development in a future release."
        }
    ]
}
```

**3. Expected behavior**
It is possible to disable warning AL0604 and AL0606 for single objects.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/56454149/124884643-c370ae00-dfd2-11eb-88bc-a881e486cf52.png)

**5. Versions:**
- AL Language: 7.3.486497
- Visual Studio Code: 1.57.1
- Business Central: 18.2.26217.26795
- List of Visual Studio Code extensions that you have installed:
  - AL Language
  - AL Code ACtions
  - AL Extension Pack
  - AL Navigator
  - AL Toolbox
  - AL Variable Helper
  - AZ AL DevTools/AL Code Outline

**Comment by esbenk** [comment]
If you have elevated a warning to an error in a ruleset then it can't be suppressed. This is by design.

**Comment by AlexCeg** [comment]
It works for CodeCop warning like AA0181. Why does it not work for AppSourceCop warnings?
