### ISSUE TITLE
Disable ALxxx warnings with pragma not working

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#6702]
**1. Describe the bug**
In reference to https://github.com/microsoft/AL/issues/6700
1. Warning ALxxxx is set to error (default: warning)
    - I'll name these ALxxx cop in the following "Compiler" Cop
1. Warning AAxxxx is set to error (default warning) 
    - =CodeCop warning. But it's the same for UI Cop/PTE Cop/AppSource Cop

At the beginning of a file we disable all warnings with "pragma warning disable"
If there are AA-Cop-Issues inside the file, the "pragma warning disable" disable all the warnings AND errors
If there are AL-Cop-Issues inside the file, the  "pragma warning disable" does NOT disable the errors. It only disables warnings. Esben said in the linked issue that it's by design, but I want to ask you to think about it a second time as it's
1. inconsistent and
2. in our scenario quite annoying: We do have a clone object of the base app temporarily as we are waiting for some "request for externals". But we don't want to fix all the warnings in the cloned objects. Instead, we simply want to add a "pragma warning disable" at the top of the file, so that if it's take more time for Microsoft to implement our requests for external, we can still update easily our cloned objects, as the files are not diverged due to fixed warnings. But currently we cannot do that. That means we are not able to set a cop rule from warning to error if ANY cloned file contains this warning. The only way we would have then, is that we have to fix the warnings and clutter the merge which makes it harder to get back to Msft Standard.

I don't see any reason why the "compiler cops" (ALxxxx) behave differently than the other cops (CodeCop etc.) and I even do not see a reason why the "pragma warning disable" should not disable warnings which were "updated" to errors.

**2. To Reproduce**

1. Add an al file

``` AL
#pragma warning disable
codeunit 50100 "Test"
{
    Access = Internal;
    TableNo = Item;
    trigger OnRun()
    var
        Item: Record Item;
    begin
        Copy(Item);        //warning AL0604
        with Item do begin //warning AL0606 and AA0005
            Description := Format(CurrentDateTime());
        end;
    end;

}
```

2. Add a ruleset

``` JSON
{
    "name": "Our ruleset",
    "description": "Some specific rules",
    "rules": [
        {
            "id": "AL0604",
            "action": "Error",
            "justification": "Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'."
        },
        {
            "id": "AL0606",
            "action": "Error",
            "justification": "The 'with' statement is deprecated and will be removed for cloud development in a future release."
        },
        {
            "id": "AA0005",
            "action": "Error",
            "justification": "Only use BEGIN..END to enclose compound statements."
        }
    ]
}
```

3. Set the settings

``` JSON
{
    "al.codeAnalyzers": [
        "${CodeCop}"
    ],
    "al.enableCodeAnalysis": true,
    "al.ruleSetPath": "ruleset.json"
}
```

**3. Expected behavior**
The pragma warning disable disables the warnings and compiles the file successfully.

**4. Actual behavior**
The file errors due to the AL warnings.
If I fix the ALxxx cop issues, so that only the AA-Cop is left which is upgraded to an error as well, then the app compiles successfully as the AA-Error is suppressed.

**5. Versions:**

- AL Language: v7.3.486497
- Visual Studio Code: 1.57.1

**Comment by esbenk** [comment]
Hi David,

I will take another look. They should behave the same.

**Comment by DavidFeldhoff** [comment]
Thanks Esben. Appreciate you're looking into it.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 27937 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
