### ISSUE TITLE
Variable.print not available for extension development

### ISSUE THREAD

**Issue by renebrummel** [microsoft/AL#6703]
Dear all,

I'm trying to print a report in a PTE SaaS extension. In doing so I run into an annoying issue. Report.Print() works perfectly fine but when I do the same with a declared variable I get an error saying that The type or method 'Print' cannot be used for 'Extension' development. Is this by design?

![afbeelding](https://user-images.githubusercontent.com/20247116/125154453-61db4b80-e15a-11eb-9974-49c411647135.png)

**Comment by kalberes** [comment]
@thloke any idea why?

**Comment by thloke** [comment]
The short (and unhelpful) answer is that these are technically different functions (one being the static Report.Print, the other being the instance ReportVariable.Print), and for some reason they're not consistent in their SaaS availability. I don't see any reason why this should be the case. I'll mark this as a bug with the intention of investigating if there's any reason not to make the instance method available on SaaS.

Ideally we'll just remove the SaaS restriction, but there might have been an old reason for this. Either way, I'll update this issue with our findings.
