### ISSUE TITLE
Using one workspace and publishing selected objects depending on my different customers needs

### ISSUE THREAD

**Issue by jensW81** [microsoft/AL#6709]
Feature suggestion for dev tools

We are creating an AL app which we want to use for different customers. We are using different objects like XMLPort, tables, queries, pages. But not every customers needs all of them and therefore don't want to license all of them.

If the AL code workspace contains objects ids which our customer has not licensed we cannot publish the app. There is an error during publishing which does not allow it because of not licensed object ids.

Therefore I am thinking about if it is possible to have s.th. like a configuration file where the object ids to publish are defined. 
As afaik there os right now no way to do that.

I don't prefer to delete the objects because of maintainability reason of the code. I would like to have the same code base for all customers.

**Comment by kalberes** [comment]
The best is to post this to our Ideas forum at https://aka.ms/BusinessCentralideas.
