### ISSUE TITLE
protected variables declared in Base Application used in page extension not accessible in BC18.3

### ISSUE THREAD

**Issue by RalleSP86** [microsoft/AL#6711]
Please include the following with each issue:

**1. Describe the bug**

the relsolved Bug from issue #6648 already exists
in BC18.3. I tried this in Docker Container with the last image of BC18.3 (18.3.27240.27988)
Then i tried the same Extension to publish in a Container with BC18.2 (18.2.26217.27991)
Here i could publish the App with a pageextension which refers to protected var in page of base application.

**2. To Reproduce**

i made a pageextension to page 232 "Apply Customer Entries"
Then i added new fields which refers to the protected var **AppliedCustLedgEntry**

``` AL
pageextension 5015158 "PMS Apply Customer Entries" extends "Apply Customer Entries"
{
    layout
    {
        addafter(ApplyingDescription)
        {
            field("PMS AppliedCustLedgEntry.Type"; AppliedCustLedgEntry."PMS Type Inv./Cr. Memo/Payment")
            {
                ApplicationArea = All;
                Caption = 'Type';
                Editable = false;
                ToolTip = 'Specifies the value of the Type field';
            }
            field("PMS AppliedCustLedgEntry.Project No."; AppliedCustLedgEntry."PMS Project No.")
            {
                ApplicationArea = All;
                Caption = 'Project';
                Editable = false;
                ToolTip = 'Specifies the value of the Project field';
            }
        }
        addafter("Document No.")
        {
            field("PMS Type Inv./Cr. Memo/Payment"; Rec."PMS Type Inv./Cr. Memo/Payment")
            {
                ApplicationArea = All;
                ToolTip = 'Specifies the value of the Type Inv./Cr. Memo/Payment field';
            }
        }
        addafter(Description)
        {
            field("PMS Project No."; Rec."PMS Project No.")
            {
                ApplicationArea = All;
                ToolTip = 'Specifies the value of the Project No. field';
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/87529202/125949670-62033a11-53fe-49c0-8292-861119bef6df.png)

**3. Expected behavior**
The App should be published without error.

**4. Actual behavior**
the publish process crashes with the following error

[2021-07-16 14:42:29.18] The request for path /BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: C# compilation has failed for the application object PageExtension_5015158. 
The failing c# file name is 4CF42E892E1A7FECEDD1E02E9835B47E72D942AA8285CEE52AFBE019E382FB7C.cs. You can find this file with the associated AL file saved in the C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$BC\apps\compilationerrors folder.
Detailed compilation error: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\180\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\4C\4CF42E892E1A7FECEDD1E02E9835B47E72D942AA8285CEE52AFBE019E382FB7C.cs(72,203): error CS1061: 'PageExtension5015158' does not contain a definition for 'Page232_AppliedCustLedgEntry' and no accessible extension method 'Page232_AppliedCustLedgEntry' accepting a first argument of type 'PageExtension5015158' could be found (are you missing a using directive or an assembly reference?)

**5. Versions:**

- AL Language: v7.3.486497
- Visual Studio Code: 1.58.2
- Business Central: 18.3.27240.27988

**Comment by thloke** [comment]
@nndobrev  - this looks the same as the issue you raised internally. Can you confirm?

**Comment by nndobrev** [comment]
Yes, thank you @RalleSP86 for reporting it and providing the repro steps. We discovered the issue a few days ago and we are already working on it.

**Comment by RalleSP86** [comment]
Ok thank you for your reply. 
Will this bug be fixed in the next minor release 18.4?

**Comment by nndobrev** [comment]
This seems to be a bigger problem, so it might be also hot-fixed in 18.3, if not it will be available in 18.4.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28083 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by thloke** [comment]
In addition to the latest version mentioned above, we're also planning to hotfix this for 18.3.
