### ISSUE TITLE
Get error right after instal al language to VSC

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/AL#6713]
**1. Describe the bug**
I get error right after installing al language to VSC

**2. To Reproduce**
1) Install al language
2) reload VSC
3)
![image_2021_07_20T14_07_30_648Z](https://user-images.githubusercontent.com/20538979/126338524-de871950-1da2-430f-88ba-97bc692b5545.png)

[Error - 17:06:31] Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:562:9)
	at d:\Users\Administrator\.vscode\extensions\ms-dynamics-smb.al-7.4.491406\node_modules\vscode-languageclient\lib\main.js:376:40

**5. Versions:**

- AL Language: **7.4.491406**
- Visual Studio Code: **1.58.2**
- Business Central: **sandbox, 18.3.27240.27381**
- List of Visual Studio Code extensions that you have installed: **Only al language ext.**

**Comment by thloke** [comment]
Strange. This error is coming from a dependent module, and we haven't changed the codepath that uses this module in a while. I also can't repro locally. I have a few questions:

1. Is this something that only happened with the latest VSIX? Were you able to use older versions of the extensions? If not, can you try installing an older version to see if the issue still repros?
2. Is this transient, or does this appear each time you load an .al file in VSCode?

**Comment by Sv1N2S** [comment]
1. Yes I tried to install previous versions but the same
2. It appears each time I install VSIX to VSC (right after installing and when I run AL: Go command)

**Comment by thloke** [comment]
Just to clarify, does this happen only once per install, or every single time you run AL: Go?

**Comment by Sv1N2S** [comment]
Sorry for not answering quickly, so I tried to create a virtual machine with win10, then install VSC + Al Language ext and everything is OK -  symbols downloaded. It seems like the problem was with my PC

**Comment by thloke** [comment]
That's okay. Thanks for clarifying, I'll close this issue.
