### ISSUE TITLE
Reading a field from an extended Dataverse table crashes Business Central 

### ISSUE THREAD

**Issue by joergrau** [microsoft/AL#6714]
**1. Describe the bug**
BC crashes when using the extended field from a table of TableType = CRM.

**2. To Reproduce**
Given there is an additional field added to the Account entity in Dataverse. In my case "Client ID"
![image](https://user-images.githubusercontent.com/6723135/126460739-b91ae817-2081-4bd8-abc5-f2cededf63f6.png)

1. Create a tableextension for this field:

```
tableextension 52000 "CRM Account Ext_TSL" extends "CRM Account"
{
    fields
    {
        field(52000; "Client ID_TSL"; Code[20])
        {
            Caption = 'Client ID';
            DataClassification = AccountData;
            Description = 'Customer No. used in Business Central';
            ExternalAccess = Read;
            ExternalName = 'new_clientid';
            ExternalType = 'String';
        }
    }
}
```

2. Use this field in code, similar to this
```
 if not CRMAccount.Get(DVInvoice.CustomerId) then
            error(NoAccountFoundErr);

        if CRMAccount."Client ID_TSL" = '' then
            error(NoAccountNoErr, CRMAccount.AccountId, CRMAccount.Name);

        if not Customer.Get(CRMAccount."Client ID_TSL") then
            error(NoCustomerErr, CRMAccount."Client ID_TSL");

```
For testing/reproduction purposes use this code:
```
CRMAccount.FindFirst();
        
        if CRMAccount."Client ID_TSL" = '' then
            error(NoAccountNoErr, CRMAccount.AccountId, CRMAccount.Name);

        if not Customer.Get(CRMAccount."Client ID_TSL") then
            error(NoCustomerErr, CRMAccount."Client ID_TSL");
```
You do need to setup data in the fields so that it should work.
The crash happens on the` Customer.Get(CRMAccount."Client ID_TSL")`

**3. Expected behavior**
BC shouldn't crash.

**4. Actual behavior**
BC crashes. No error could be retrieved from telemetry.

**5. Versions:**

- AL Language: v7.4.491406
- Visual Studio Code: 1.58.2
- Business Central: NZ Business Central 18.3 (Platform 18.0.27224.28087 + Application 18.3.27240.27381)

**Comment by thloke** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue. 

We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.   

Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/ 

  

Or  

 

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
