### ISSUE TITLE
Profile (Role) Role Center ID reset to default (8999) after app publish

### ISSUE THREAD

**Issue by marekjz** [microsoft/AL#6719]
Happens "randomly", but very often, after BC AL app being published (at least from VS Code). What happens is that Role Center ID is set to default (i.e. 8999) afterwards.

In order to fix that, we had to write a custom "Install" codeunit that attempts to fix the Role Center ID to the correct one after BC app being published/installed, but that needs to be done asynchronously (via JobQueue), multiple times in some time intervals, to achieve any satisfying result. Even though sometimes Role Center ID is still broken, even after several fix attempts within ca. 2 minutes after app publish, and needs to be fixed manually via GUI.

Bug observed in: Version: NO Business Central **18.0** (Platform 18.0.22893.23773 + Application 18.0.23013.23795)
Worked Ok in (as long as I tested): Version: NO Business Central **16.1** (Platform 16.0.12630.12758 + Application 16.1.12805.0)

**Comment by marekjz** [comment]
PS: I should have mentioned that the issue applies to Role Center pages defined in the extension (i.e. not standard role centers - at least I haven't tested with them).

**Comment by thpeder** [comment]
Hi @marekjz,
Could you please provide a small project the reproduces the issue, since that makes it much easier for us to investigate and know for sure that we fixed the issue you have encountered.

Thanks,
Thomas

**Comment by marekjz** [comment]
Hi Thomas. I guess I could try to elaborate something, but I doubt this is related to project-specific configuration. We also have no customizations around Profile (Role) processing, except the Role Center page we have defined within our extension's object ID range. As I mentioned - it happens on quite random/arbitrary app publishes from VS Code to BC development endpoint. I suspect it is related to some kind of "defaulting" code that sets Role Center ID to 8999 whenever it finds that the configured page doesn't exist. When it happens - depend on several "timing" factors and things that happen when app is being deployed to BC via development services endpoint. But it should never end up in a wrong state I think, while it does.
![image](https://user-images.githubusercontent.com/25200511/126991751-56bc8abc-23e2-4bc4-9fd1-39a58214c191.png)

**Comment by thpeder** [comment]
Hi @marekjz,
I tried to reproduce the issue but I can't.
My steps are, I made an app with a Profile and a associated Role Center page. Published it and made it my Role Center and made it the default role center in the profiles page. I then made minor changes to the app, and published the app multiple times, but everytime I check both places still used my role center.

**Comment by marekjz** [comment]
You could try to make the app more "heavy" - our extension has over 1500 custom AL objects, plus several Word templates, and generated .app file has nearly 5MB. Also maybe try to interact with BC GUI while app is being published.

I suspect that the issue could be caused by some kind of "racing condition", timeout or something like that, which causes that the BC app installer "gives up" trying to assign Role Center ID from just (or not yet) deployed app and assigns a default value 8999. Also, the "problem" could be that some users try to open BC GUI while app is being deployed (i.e. when extension's objects are temporarily unavailable), so that BC assigns a default value 8999.

**Comment by marekjz** [comment]
Hi @thpeder 
You could try to make the app more "heavy" - our extension has over 1500 custom AL objects, plus several Word templates, and generated .app file has nearly 5MB. Also maybe try to interact with BC GUI while app is being published.

I suspect that the issue could be caused by some kind of "racing condition", timeout or something like that, which causes that the BC app installer "gives up" trying to assign Role Center ID from just (or not yet) deployed app and assigns a default value 8999. Also, the "problem" could be that some users try to open BC GUI while app is being deployed (i.e. when extension's objects are temporarily unavailable), so that BC assigns a default value 8999.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
