### ISSUE TITLE
Strange behaviour when modify("Replenishment System") with Item Card extension

### ISSUE THREAD

**Issue by mbug** [microsoft/AL#6720]
Please include the following with each issue:

**1. Describe the bug**
Hi, 
I get a runtime error when I modify the field "Replenishment System" on the item card, so that the field will not be editable when a stockkeeping unit for that item already exist. This problem exists since we updated to 18.3.27240.27480.

When I use the following code:
``` AL
pageextension 50100 "Item Card" extends "Item Card"
{
    layout
    {
        modify("Replenishment System")
        {
             Editable = not Rec."Stockkeeping Unit Exists"; 
        }
    }
}
```
After opening the item card, I get the following error:
![image](https://user-images.githubusercontent.com/42273207/127137304-edb98bc8-b51b-4a67-95e7-2264c695cd2f.png)

Surprisingly, the same code does work on many other fields without any issue, for example:
``` AL
pageextension 50100 "Item Card" extends "Item Card"
{
    layout
    {
        modify("Manufacturing Policy")
        {
            Editable = not Rec."Stockkeeping Unit Exists";
        }
    }
}
```

**2. To Reproduce**

1. Create a new extension and publish in onprem-18.3.27240.27480-de container
2.  Use the following code:
``` AL
pageextension 50100 "Item Card" extends "Item Card"
{
    layout
    {
        modify("Replenishment System")
        {
             Editable = not Rec."Stockkeeping Unit Exists"; 
        }
    }
}
```
3. Open the Item Card

**3. Expected behavior**
There should be no error.  The same code does work on multiple other fields on that page. The same code did work in onprem-17.4.21491.21531-de environment.

**4. Actual behavior**
After opening the item card, I get the following error:
![image](https://user-images.githubusercontent.com/42273207/127137304-edb98bc8-b51b-4a67-95e7-2264c695cd2f.png)

**5. Versions:**

- AL Language: 7.4.491406
- Visual Studio Code: 1.58.2
- Business Central: Version: DE Business Central 18.3 (Platform 18.0.27224.27469 + Application 18.3.27240.27480)

**Comment by db-bc** [comment]
I wonder if it's somehow, however oddly, related to "Stockkeeping Unit Exists" being a FlowField. Maybe it is somehow not calculated/loaded in the platform dataset normally, but gets included indirectly sometimes if you refer to certain other fields. `</thinkingaloud>`

**Comment by nndobrev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" on how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
