### ISSUE TITLE
AL Debugger: Error Message will not been shown

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6723]
**Describe the bug**
Compared to the Windows Client Debugger, the AL Debugger does not displays an error message when an error occurs.

AL Language Extension: 8.0.493428
Business Central Version: W1 19.0 (Plattform 18.0.28183.0 + Application 19.0.28475.0)

<img width="1920" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/127551690-7bd0d5f9-e797-460e-987a-dec33b0d28d9.png">

**Comment by DanielGoehler** [comment]
@kalberes 
The Windows Client Debugger shows you the error message right away.
![Windows Client Debugger](https://user-images.githubusercontent.com/9556549/129546178-0266c862-3526-4422-8a63-1aeb239574f4.png)
The Web Client Debugger doesn't shows this error messages.
![Visual Studio Code Debugger](https://user-images.githubusercontent.com/9556549/129546231-f6875d0f-5694-423a-a5d4-e9f9ab21ada6.png)
Even if you use F10.
![Windows Client Debugger 002](https://user-images.githubusercontent.com/9556549/129546271-771ecdce-31d9-4481-9a2f-d2393b899897.png)
To find out the error message you have to continue, check the web client output and then trigger the error again. Takes more time then the windows client debugger.

**Comment by zabcik** [comment]
Windows Client Debugger was better. I'm missing last error message, too.

**Comment by mjmatthiesen** [comment]
> 
> 
> Windows Client Debugger was better. I'm missing last error message, too.

I definitely wouldn't say it was better, but I do think seeing the error message in vs code is vital.

**Comment by NKarolak** [comment]
It looks like it was fixed with AL Language version 9.0.
https://twitter.com/StefanMaron/status/1509806026085875713

**Comment by kalberes** [comment]
@NKarolak 
That is not new. It has been part of the vsix for 8.x.

**Comment by mjmatthiesen** [comment]
Any way to add this to your watch? Tried simply adding it to the watch, but that didn't work :)
Just a few less clicks for my life.
