### ISSUE TITLE
AS0034 Breaking Change

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/AL#6724]
Please include the following with each issue:

**1. Describe the bug**
Table ObseleteState=Pending; V1
![image](https://user-images.githubusercontent.com/39938430/127672174-62039011-f17b-49e9-b0dc-472bcfc0e818.png)

V2 Set the Table to Access Internal:
![image](https://user-images.githubusercontent.com/39938430/127672318-b07ec697-c5fa-472e-93fa-7ccac7aaf24f.png)

error AS0034: The property 'Access' for Table 'xxxx' has changed from value 'Public' to value 'Internal'. This is not allowed because it will break upgrade of existing installations and dependent extensions.

- AL Language: 7.4.496506
- Visual Studio Code: 1.58.2
- Business Central: 18.3

**Comment by qutreson** [comment]
This issue is fixed for version of the AL extension for Visual Studio code higher than 7.4.500202.
