### ISSUE TITLE
BC 18.3 Installation of 3rd Party Extension - SQL constraints missing in extension tables

### ISSUE THREAD

**Issue by MathiasDuesing** [microsoft/AL#6725]
**1. Describe the bug**
Installing a 3rd Party Extension (Runtime) may lead into missing Constraints within the related SQL Table.

We found at least one 3rd Party Extension where all constrains are missing on all tables which extend Microsoft Base App tables after we published, synched and installed the app via Business Central Administration Shell.

Sync-NAVApp in different modes did not solve the issue as well as a reinstall etc.

If you trigger a schema recreate with a company rename within Business Central, all constrains get created.

**2. To Reproduce**
Take/Install a Business Central 18.3 Demo DB (CRONUS).
Take a 3rd Party Extension (Runtime) which extends Microsoft Base App.
Install Extension via Business Central Administration Shell (Publish, Sync, Install) and review constrains on SQL Server.
For us, this happens only for tables which extend Microsoft Base App.

**3. Expected behavior**
For all created Fields in every SQL Server Table of Business Central, constrains should be created which will set default values to fields.

**4. Actual behavior**
3rd Party Extension constrains are missing.
![image](https://user-images.githubusercontent.com/72605004/127872014-d24dfe26-fa3d-4035-9245-6380342d738a.png)

Constrains on same table from BC Base App are created correctly:
![image](https://user-images.githubusercontent.com/72605004/127873462-f8283ce6-d185-445f-8442-2c5cae5098c4.png)

If you rename the Company, also 3rd Party Extension constrains get created...

**5. Versions:**

- AL Language: Runtime 7.0
- Visual Studio Code: - 
- Business Central: 18.3.27240.27480
- List of Visual Studio Code extensions that you have installed: -

**Comment by nndobrev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
