### ISSUE TITLE
Missing warning in case of possible overflow in setrange

### ISSUE THREAD

**Issue by PP1986** [microsoft/AL#6726]
**1. Describe the bug**
When .SetRange is used possible overflow is not recognized by the code analyzers.

**2. To Reproduce**
User SetRange on a Text[100] field using a value that is more than 100 chars. This will give no warning, while it will cause an error in runtime.

**3. Expected behavior**
I would be handy if this possible overflow issue would be recognized by the code analyzers.

**4. Actual behavior**
It is not recognized so the issue can be easily overseen.

**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

**Comment by db-bc** [comment]
Same goes for `SetFilter()`, `Get()`, etc. - iirc

**Comment by nndobrev** [comment]
Hi! Thanks for the suggestion! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
