### ISSUE TITLE
TestField does not support Enums (followup of #5708)

### ISSUE THREAD

**Issue by dennisroczek** [microsoft/AL#6727]
Followup of #5708: if you use an enum as a parameter, you are not able to use testfield for a certain value.

e.g.

`
    local procedure DocumentTypeAllowed(DocumentType: Enum "Purchase Document Type"): Boolean
    begin
       DocumentType.testfield(DocumentType::Order);
       exit(true);
    end;
`

**Comment by db-bc** [comment]
One cannot test *any* variable, i.e. anything that is not a member of a table/record instance; I don't see why `Enum` variables should be special here. What would the error say if `TestField()` were possible and failed? `DocumentType must be Foo` without any context of what record it's for, where the test was done, etc.?

**Comment by nndobrev** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
