### ISSUE TITLE
Issue in Codeunit "CRM Sales Order to Sales Order" 5343

### ISSUE THREAD

**Issue by phil38000** [microsoft/AL#6729]
Dear,
I have an issue with this CU in Business Central SaaS 18.3
I subscribe to this publisher :
[EventSubscriber(ObjectType::Codeunit, Codeunit::"CRM Sales Order to Sales Order", 'OnCreateSalesOrderLinesOnBeforeSalesLineInsert', '', true, false)]
local procedure OnCreateSalesOrderLinesOnBeforeSalesLineInsertExt(CRMSalesorderdetail: Record "CRM Salesorderdetail"; var SalesLine: Record "Sales Line")
begin
SalesLine.Validate("VAT Prod. Posting Group", CRMSalesorderdetail.DBEVATProdPostingGrp);
end;

but when this event is triggered, Business Central crash with standard error "....Something Went Wrong..." :(
I tried without validate and same crash. I'm "SUPER" and ADMIN User.
if someone has any idear, thanks by advance.
have nice day

**Comment by thloke** [comment]
Apologies for the delay in getting a response for this. Can you share your AAD tenant ID? I need it to check our telemetry to see what might have gone wrong in SaaS, and figure out which team owns this bug. It's understandable if you don't want to post your aad tenant ID on this issue, so you can send it to me directly at thloke@microsoft.com. Thanks in advance!

**Comment by phil38000** [comment]
With Tholke, we managed to find a fix for this issue. use "Text" type for field definition in extension, instead of "Code" type.

**Comment by dnpb** [comment]
Thanks for posting the fix for others to see!
Hopefully MS can fix the crash or at least generate a proper error when it happens ;-)

**Comment by thloke** [comment]
That is the plan. There should never be a reason for the error page to be shown. We either need to not have the error to begin with, catch it earlier (compile time), or show something more friendly. :)
