### ISSUE TITLE
AppSourceCop AS0064: removing an obsoleted Interface in combination with public objects implementing that one is considered a breaking change

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#6731]
**1. Describe the bug**
If an interface is marked as obsolete for a while, it cannot be removed simply if any public objects has it implemented inside the extension. But it could be removed if no public object would have it implemented (which makes sense in my eyes as depending apps had enough time to switch)

**2. To Reproduce**
Create a new project with the following settings.json
```al
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${AppSourceCop}"
    ]
}
```
The app.json has the following setting
```
{
  "id": "61e4874d-51be-4b5b-b5bb-9ac2a2552482",
  "name": "ALProject50_AS0064ObsoletIssue",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "1.0.0.0",
  "application": "18.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "suppressWarnings": [ //not needed for this demo
    "AS0015",
    "AS0051",
    "AS0052",
    "AS0054",
    "AS0084"
  ],
  "contextSensitiveHelpUrl": "https://ALProject50_AS0064ObsoletIssue.com/help/",
  "showMyCode": true,
  "runtime": "7.0"
}
```
Create a first version of the app with the following objects
```al
interface MyInterface_V1
{
    ObsoleteState = Pending;
    ObsoleteReason = 'Use Interface v2 instead';
    procedure MyProcedure();
}
interface MyInterface_V2
{
    procedure MyProcedure(MyText: Text);
}
enum 50100 MyEnum implements MyInterface_V1, MyInterface_V2
{
    value(0; MyValue)
    {
        Implementation = MyInterface_V1 = MyCodeunit, MyInterface_V2 = MyCodeunit;
    }
}
codeunit 50100 MyCodeunit implements MyInterface_V1, MyInterface_V2
{
    [Obsolete('Use MyProcedure(MyText: Text) instead')]
    procedure MyProcedure();
    begin
    end;

    procedure MyProcedure(MyText: Text);
    begin
    end;
}
```

Move the created *.app file to the .alpackages, increase the app.jsons version no. and add an AppSourceCop.json
```
{
    "version": "1.0.0.0"
}
```
Now remove the Interface V1, so that the code looks like this
```al
interface MyInterface_V2
{
    procedure MyProcedure(MyText: Text);
}
enum 50100 MyEnum implements MyInterface_V2
{
    value(0; MyValue)
    {
        Implementation = MyInterface_V2 = MyCodeunit;
    }
}
codeunit 50100 MyCodeunit implements MyInterface_V2
{
    procedure MyProcedure(MyText: Text);
    begin
    end;
}
```

Now try to compile: Two errors are showing up:
error AS0064: Implementation of interface 'MyInterface_V1' has been deleted on Codeunit 'MyCodeunit'.
error AS0064: Implementation of interface 'MyInterface_V1' has been deleted on Enum 'MyEnum'.

**3. Expected behavior**
That shouldn't be a breaking change. The enum or the codeunit should be allowed to remove the Interface Implementation as it was obsoleted for a while and places which used that Interface V1 had enough time to switch to Interface V2.

**4. Actual behavior**
It is considered as a breaking change which shouldn't be the case. So currently we would have to 
1. keep the interface in our code as obsolete = pending and suppress the warning or something similar or
2. mark all objects which are implementing that interface as obsolete as well and create a v2 object for them as well which could lead to quite a night mare if an enum implemented that interface which is used in table fields, publishers, parameters, ...

**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code: 1.59.0

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 29615 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
