### ISSUE TITLE
RecRef KeyIndex vs RecRef CurrentKeyIndex with Obsolete Keys

### ISSUE THREAD

**Issue by andreilungu** [microsoft/AL#6734]
Please include the following with each issue:

**1. Describe the bug**
When we have Obsolete Keys in a table extension, KeyRef.Keyindex(i) is ignoring the Obsolete Keys, but RecRef.CurrentkeyIndex(i) seems is not.

**2. To Reproduce**
- Create table extension on Item table.
- Add 3 Keys (first 2 are obsolete, the last one is not):
```
keys
    {
        key("N Key1"; "Group sale", "Item Group")
        {
            ObsoleteState = Removed;
            ObsoleteReason = 'Not used anymore.';
        }
        key("N Key2"; "Primary Key Length")
        {
            ObsoleteState = Removed;
            ObsoleteReason = 'Not used anymore.';
        }
        key("N Key3"; "Replication Counter")
        {
        }
    }
```

Item table has 17 keys in standard table + 3 custom keys = 20 keys in total.

Write code to retrieve the Index of the Key on field "Replication Counter" using RecRefs:
```
local procedure GetReplicationCounterKeyIndex(RecRef: RecordRef; RepCounterFieldRef: FieldRef): Integer
    var
        i: Integer;
        KRef: KeyRef;
        FRef: FieldRef;
    begin
        For i := 1 to RecRef.KeyCount do begin
            KRef := RecRef.KeyIndex(i);
            IF KRef.FieldCount = 1 then begin //we are looking for the key with only one field --> Replication Counter
                FRef := KRef.FieldIndex(1);
                IF FRef.Name = RepCounterFieldRef.Name then
                    exit(i);
            end;
        end;
    end;
```
_Where RepCounterFieldRef = RecRef.Field(ReplicationCounterFieldNo);
And RecRef = Reference of Item table._

This code returns index 18 (it skips the 2 obsolete keys in the table extension).

Then, if we try to use the 18 index to set the CurrentKey on the RecRef we get error because it seems it thinks that index 18 is the first key in our table extension which is Obsolete..
`
RecRef.CurrentKeyIndex(18); //Set Replication Counter Key
`

Error message:
_Key Group sale, Item Group (17) for table Item (27) is obsoleted, reason: Not used anymore._
_Page Edit - Item Card - 1001 ∙ Touring Bicycle has to close._

**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code: 1.59
- Business Central: W1 17.0 (Platform 17.0.16974.0 + Application 17.0.16993.0)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 30174 and VS Code Extension Version 9.0.518562. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
