### ISSUE TITLE
Api version beta : Multiple web services with the name ProdBomHeader have been found.

### ISSUE THREAD

**Issue by sradouan** [microsoft/AL#6736]
Hi,
 i'm using Item page with a part of ProdBomHedaer and inside the page ProdBomHeader i'm using a part of ProdBomLines.

using method get on postman i have this error!
"error": {
        "code": "Unknown",
        "message": "Multiple web services with the name ProdBomHeader have been found.  Update your web service names to be unique and try again."
    }
}

page 50062 "ZA PostComponents"
{
    PageType = API;
    Caption = 'postComponents', Locked = true;
    APIPublisher = 'ZA';
    APIGroup = 'ZA';
    APIVersion = 'beta';
    EntityName = 'postComponent';
    EntitySetName = 'postComponents';
    SourceTable = Item;
    DelayedInsert = true;
    ODataKeyFields = Id;

part :
part(ProdBomHeaders; "ZA Prod.Bom Header")
                {
                    ApplicationArea = All;
                    Caption = 'Header';
                    EntityName = 'ProdBomHeader';
                    EntitySetName = 'ProdBomHeaders';
                    SubPageLink = "No." = FIELD("Production BOM No.");
                   
                }

ProdBom Hedaer page:

page 50064 "ZA Prod.Bom Header"
{
    PageType = API;   
    Caption = 'ProdBomHeader', Locked = true;
    APIPublisher = 'ZA';
    APIGroup = 'ZA';
    APIVersion = 'beta';
    EntityName = 'ProdBomHeader';
    EntitySetName = 'ProdBomHeaders';
    SourceTable = "Production BOM Header";
    DelayedInsert = true;
    ODataKeyFields = "No.";

part: 
part(ProdBomLines; "ZAProd.Bom Line2")
                {
                    ApplicationArea = All;
                    Caption = 'Lines';
                    EntityName = 'ProdBomLine';
                    EntitySetName = 'ProdBomLines';
                    SubPageLink = "Production BOM No." = FIELD("No.");
                }

Thanks.

**Comment by thloke** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible. 

 

To open a support case, you can: 

 

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

 

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
