### ISSUE TITLE
ExtendedDataType = Masked is ignored when the table is not the primary table on a page.

### ISSUE THREAD

**Issue by abc-RKN** [microsoft/AL#6737]
**1. Describe the bug**
If you add a table to a page indirectly, the ExtendedDataType = masked, is ignored.

**2. To Reproduce**

Create two tables, Table A and Table B,  to keep it simple just create the same table twice.
Both Tables are (in this case) setup tables with only a single record, so no linkage / keys are needed.

table 50000 "TABLE A"
{
    fields
    {
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
        }
        field(2; "Password"; Text[1024])
        {
            Caption = 'Password';
            ExtendedDatatype = Masked;
        }
   }
}

table 50001 "TABLE B"
{
    fields
    {
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
        }
        field(2; "Password"; Text[1024])
        {
            Caption = 'Password';
            ExtendedDatatype = Masked;
        }
   }
}

Now create a page based on Table A, which references Table B; 

Page 50000 "TEST PAGE"
{
     Caption = 'Test Page';
     PageType = Card;
     UsageCategory = Administration;
     ApplicationArea = All;
     SourceTable = "Table A"

layout
{
    area(content)
    {
           group('Table A')
           {
                      field(Password;Rec.Password)
                      {
                           ApplicationArea = All;
                           ToolTip = 'This field is correctly masked';
                      }
           }
           group('Table B')
           {
                      field(Password;TableB.Password)
                      {
                           ApplicationArea = All;
                           ToolTip = 'You would expect this field to be masked';
                      }
           }
}
trigger OnOpenPage()
begin
        TableB.Get();    // Both Tables are Single Record Setup Pages, so no filters needed;
end;
var 
        TableB : Record "Table B";
}

**3. Expected behavior**

The Table Field must be MASKED on the Page. Both the Field from Table A (Primary table for the page) as for Table B (Secondary/Referenced Table)
The only way to get the field from Table B masked, is to add the ExtendedDataType = Masked to the Page as well.

**4. Actual behavior**

The Table field for Table B (The Referenced table) is not masked, but cleartext.
You might argue that adding two tables to one page is not best practice, but this poses a potential security risk where passwords or other sensitive data might be exposed if someone links to the fields on a page by malicious end users / extensions. 

**5. Versions:**

- AL Language:  7.4.496506
- Visual Studio Code:  1.51.1 
- Business Central: 18.3
- List of Visual Studio Code extensions that you have installed: Not relevant for this bug.

**Comment by db-bc** [comment]
This has always been the same: any field from a non-`Rec` table on a page does not inherit any of the properties from the table field definition. They act just the same as a variable or any other expression would. Only `Rec` fields get special treatment and automatically inherit properties. For anything else, we have always needed to manually duplicate the properties on the page.

> this poses a potential security risk where passwords or other sensitive data might be exposed if someone links to the fields on a page by malicious end users / extensions.

If that's a concern, you should store the data securely, rather than just using `Masked`.

**Comment by abc-RKN** [comment]
You have a point about storing the data securely, but we both know that is very often not the case :) 
I never had to deal with this specific issue before, so I had no idea if it has been that way since C/AL.
However it would be a nice feature to have this working for a Record variable in my humble opinion.
But then I'm in the wrong Thread :)

**Comment by db-bc** [comment]
Yeah, that could definitely be worth posting or upvoting on BCIdeas :-)
