### ISSUE TITLE
Server error when trying to access DataItem in ReportExtension

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/AL#6739]
**1. Describe the bug**
I'm trying to access the DataItem in a ReportExtension. When I execute my compiled report, a server error shows up, Similar to Issue #6735

**2. To Reproduce**
To reproduce the error, exend a report. In this example, we are going to extend the `Close Income Statement` report

1. Create a new AL File
2. Paste the Code Snippet below
3. Create a new Close Income Statement
```AL
reportextension 50000 "My Close Income Statement" extends "Close Income Statement"
{
    trigger OnPreReport()
    begin
        "G/L Account".SetRange(Blocked, false);
    end;
}
```
**3. Expected behavior**
The Report should execute

**4. Actual behavior**
A Server Error is shown and following message is shown in the debug console of VSCode:
```
Error: C# compilation has failed for the application object ReportExtension_50000. 
The failing c# file name is <filename>.cs. You can find this file with the associated AL file saved in the <nav folder>\apps\compilationerrors folder.
Detailed compilation error:
<csharp file>(170,33): error CS1002: ; expected
<csharp file>(170,29): error CS1061: 'ReportExtension50000' does not contain a definition for 'G' and no accessible extension method 'G' accepting a first argument of type 'ReportExtension50000' could be found (are you missing a using directive or an assembly reference?)
<csharp file>(170,31): error CS0103: The name 'L' does not exist in the current context  
<csharp file>(170,33): error CS0103: The name 'Account' does not exist in the current context
```
**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code: 1.59.0
- Business Central: 18.0.23013.23795
- List of Visual Studio Code extensions that you have installed: not relevant

**Comment by thloke** [comment]
I can't reproduce this in the latest version of business central. A bunch of similar bugs to this was fixed around 18.2 - 18.4. Can you try to repro in the latest insiders build? If you can, please reopen this issue.
