### ISSUE TITLE
Function expose.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#674]
Hi again.

I was happy to see that my expose request was addressed in the the september update. 
However one function is still missing:
SumPurchLinesTemp in codeunit 90. 

Was this overlooked or skipped on purpose?

**Comment by StanislawStempin** [comment]
It looks like it was overlooked. We will have another go

**Comment by AlexanderYakunin** [comment]
This function already made External this week, you will see it in next update
