### ISSUE TITLE
Same issue like #5961 -> httpclient + 'GET' + 'Cannot send a content-body with this verb-type'

### ISSUE THREAD

**Issue by ftornero9** [microsoft/AL#6741]
Hello,

I have the same issue that #5961 but I only need to set the header with the "Content-Type" no send anything in the body and the method is a GET and the error is the same.

@ajkauffmann, Is there any kind of workaround to do that ?

Regards.

**Comment by db-bc** [comment]
What purpose can a content-type serve if there is no body for it to represent?

**Comment by ftornero9** [comment]
Well, the remote service needed it, otherwise It returns an HTML response.

Maybe the question would be why the constrains with the http headers in AL.

Regards.

**Comment by db-bc** [comment]
The `content-type` is to tell the recipient how to understand _your_ body content. If you want to tell the recipient what _it_ should send back to you, that should be the `Accept` header. ...Right?

**Comment by ftornero9** [comment]
That's true, but doesn't work, I have no doubt that the remote web service is bad designed but I can't force the change and everything works if the "Content-Ttype" is set to "application/json".

Tested with Postmant and with Powershell.

So what the problem would be if you could set this header in AL.

Regards.

**Comment by db-bc** [comment]
I'm not expert but am not certain this is an AL-specific issue; it looks like instead it is just about .Net not supporting bodies with GET requests: https://stackoverflow.com/a/3981584

That and many similar threads suggest it is just a limitation of .Net, not specific to AL, in which case it wouldn't be relevant to the AL compiler.

Some of them suggesting using POST instead, but presumably you tried that and it didn't work?

**Comment by ftornero9** [comment]
I don't need to send any information in the body just to set the header and that is not a limitation of .NET. 

Yes, POST don't work.

**Comment by db-bc** [comment]
How is it "not a limitation of .NET", when there are loads of discussions of people using the `HttpClient` in contexts other than AL/BC and getting the same error? Have you replicated the same code in some other language/environment against the same .Net `HttpClient` and gotten it to work without the error?

**Comment by ftornero9** [comment]
Yes, here is an example in Powershell, that works, the values of the X-IBM... are incomplete:
```
#--------------------------------
function Execute-GetRequest 
#--------------------------------
( 
  [String] $URL
) 
{ 
  $WebRequest = [System.Net.WebRequest]::Create($URL) 
  $WebRequest.Headers.Add("X-IBM-Client-ID",  "f8c6f3-c64-49a-922-5002ae6")
  $WebRequest.Headers.Add("X-IBM-Client-Secret", "O8scE1dY6cW2pR0wX3uA0vR7T2sJ6")
  $WebRequest.ContentType = "application/json"
  $WebRequest.Method      = "GET"         

  try {
    $resp = $WebRequest.GetResponse() 
    $responseStream = $resp.GetResponseStream() 
    $Reader = [System.IO.StreamReader]($responseStream) 
    $ReturnXml = $Reader.ReadToEnd() 
    $responseStream.Close() 
    return $ReturnXml 
  } catch {
    Write-Error $Error[0]
  }
}

#----------------------------------------------------------------------------------------------------------------------

$url = "https://apisandbox.iras.gov.sg/iras/sb/Authentication/CorpPassAuth?callback_url=https://businesscentral.dynamics.com/sandbox&tax_agent=false&state=StanleyState&scope=GSTF7SubCP"

$ret = Execute-GetRequest $url

$ret
```

**Comment by db-bc** [comment]
another source, linked from the earlier issue, indicates it's a limitation of .Net, not AL - and that in the newer .Net Core it will work - but not in .Net Framework - https://github.com/dotnet/runtime/issues/25485

BC will be using the Framework. Maybe your powershell is using Core instead. It still doesn't seem like BC's fault.

**Comment by ftornero9** [comment]
In my opinion it's a BC fault due to the way that the headers are implemented, Content Headers and  Request Headers.

In Postman there is not such diference.

![image](https://user-images.githubusercontent.com/12720964/130454298-d0cd36e6-bd1a-4faa-8cb4-436973cdd007.png)

**Comment by ftornero9** [comment]
And the Powershell that I am usign is version 5.1 

![image](https://user-images.githubusercontent.com/12720964/130456937-0d324fa3-b492-4a50-8b29-59931aee269f.png)

That use .NET Framework:

![image](https://user-images.githubusercontent.com/12720964/130456827-0c09ecab-122f-4255-a129-e0d054ca8ff0.png)

**Comment by db-bc** [comment]
Does it work to set the `Content-Type` on the `HttpClient.DefaultRequestHeaders`, instead of on the `Request` headers?

Anyway... #5961 was [closed](https://github.com/microsoft/AL/issues/5961#issuecomment-646563066) with the same rationale I already gave, so I don't see how this is different. It seems more a question for e.g. Yammer, than for the AL compiler GitHub.

**Comment by ftornero9** [comment]
No, it don't work.

![image](https://user-images.githubusercontent.com/12720964/130462766-f9ce02f7-3769-48ed-a006-993e129b8ba7.png)

Again, the headers issue.

All the examples that you have provided are related to sending something in the body with a GET method, that is not my case, I only want to set the value of a specific header.

**Comment by thloke** [comment]
As stated previously, the AL HttpClient class is just a wrapper around the .net implementation, so the behaviour is inherited from it. So we do not support this case.

**Comment by ftornero9** [comment]
Hello @thloke,

Could you explain a little why .net framework doesn't support what I'm asking, that it's send a header with "Content-Type" ?.

Thanks in advance.

Regards.

**Comment by julkifli33** [comment]
I have the same issue here..
any idea?
