### ISSUE TITLE
Sync-NAVApp - System.ArgumentNullException: Value cannot be NULL. - synchronize table migration extension

### ISSUE THREAD

**Issue by DobbyNator94** [microsoft/AL#6745]
- Server Version:  
18.0.22893.23773

Hi,

we are trying to migrate a customized BC14 CU10 C/AL solution to AL.
We are getting an error, when we are trying to Sync-NAVApp our table migration extension with the following error.

This Sync is already happpening on BC18.

Maybe this is a bug and we should use the latest CU of BC14 and BC 18.4?
Does anybody have an idea? We can use -SyncMode Force, but then the data is gone.

Thank you all!

best regards,
Robin

Type: System.InvalidOperationException
Message:
  Der Wert darf nicht NULL sein.
  Parametername: source
HResult: -2146233079

Server instance: MIGRATION18AMA
Category: Extensions
ClientSessionId: 02940e38-a002-42f0-be80-9e82c94711b8
ClientActivityId: d1778096-0242-4299-9228-7a986f822da0
ServerSessionUniqueId: 7380dfe7-07e5-4137-84ff-d63dcfb9a98b
ServerActivityId: fc291527-92ef-4c81-938d-f3c33f0783a1
EventTime: 08/26/2021 19:22:59
Message App Sync Exception -- System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.ListOfFieldsAsString(IEnumerable`1 fields)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.ChangedSqlIndexFields(SyncKeyComparisonEntry comparisonEntry)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.CheckForUnsupportedChanges(SyncKeyComparisonEntry c, List`1 errors)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.Validate(AppId appId, ObjectType objectType, Int32 objectId, SyncTableBundle bundle)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncTableBundle.Validate(AppId appId, IEnumerable`1 validators)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncChangeRetriever.GetChangesForAdd(AppSyncContext syncContext, SyncTableBundle bundle)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncChangeRetriever.GetChanges(AppSyncContext syncContext, SyncTableBundle bundle)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSyncInternal(NavSession session)
ProcessId: 5388
Tag: 00001X1
ThreadId: 62
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 032a9e0b-d398-4969-bf35-59fa7020890f

Server instance: MIGRATION18AMA
Category: Extensions
ClientSessionId: 02940e38-a002-42f0-be80-9e82c94711b8
ClientActivityId: d1778096-0242-4299-9228-7a986f822da0
ServerSessionUniqueId: 3dfb7164-f59a-479a-8916-ee6c2dc1dae8
ServerActivityId: 0cdc1d1e-c003-415f-9b95-2f86482e612b
EventTime: 08/26/2021 19:22:59
Message (ArgumentNullException): RootException: ArgumentNullException
Der Wert darf nicht NULL sein.
Parametername: source
ExceptionStackTrace:
   bei System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.ListOfFieldsAsString(IEnumerable`1 fields)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.ChangedSqlIndexFields(SyncKeyComparisonEntry comparisonEntry)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.CheckForUnsupportedChanges(SyncKeyComparisonEntry c, List`1 errors)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncKeyValidator.Validate(AppId appId, ObjectType objectType, Int32 objectId, SyncTableBundle bundle)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncTableBundle.Validate(AppId appId, IEnumerable`1 validators)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncChangeRetriever.GetChangesForAdd(AppSyncContext syncContext, SyncTableBundle bundle)
   bei Microsoft.Dynamics.Nav.Runtime.Apps.SyncChangeRetriever.GetChanges(AppSyncContext syncContext, SyncTableBundle bundle)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSyncInternal(NavSession session)
   bei Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynamics.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSession(Action`2 action, Boolean throwExceptions, Boolean useCurrentCulture, Boolean allowAppsDisabledMode, LanguageSetting language, NavCancellationToken cancellationToken)
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSync(AppSyncContext appSyncContext)
CallerStackTrace:
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSync(AppSyncContext appSyncContext)
   bei Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)
   bei Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass143_0.<Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp>b__0()
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.<>c__DisplayClass2_0`1.<RetryOperationWithTransientError>b__0()
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.InternalRetryOperationWithTransientError[T](Action operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String callerName, String additionaInfo, Boolean expectedType)
   bei Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.RetryOperationWithTransientError[T](Func`1 operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String caller, String additionalContext)
   bei Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp(SyncNavAppArguments syncNavAppArguments)
   bei SyncInvokeSyncNavApp(Object , Object[] , Object[] )
   bei System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.VerifyAdminCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass6_0.<Create>b__0(ServiceOperation operation, NSServiceBase instance, MethodBase syncMethodLocal, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   bei Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationDuration(Stopwatch stopWatch, Action action)
   bei Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationAction(Action action, NavSession session)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   bei Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   bei System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   bei System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   bei System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   bei System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   bei System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
   bei System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
   bei System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
   bei System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
   bei System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   bei System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   bei System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
   bei System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   bei System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   bei System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
   bei System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
   bei System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   bei System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   bei System.Net.Security.NegotiateStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.NegotiateStream.ReadCallback(AsyncProtocolRequest asyncRequest)
   bei System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   bei System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   bei System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   bei System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   bei System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
   bei System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   bei System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   bei System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

ProcessId: 5388
Tag: 0000ENC
ThreadId: 62
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 032a9e0b-d398-4969-bf35-59fa7020890f

**Comment by thloke** [comment]
Hi, this is the wrong channel for this bug. You're better off filing a request in Collaborate or opening a support case. To open a support case, you can:  

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

We don't deal with the DB sync unfortunately, just the AL language and compiler itself. Hope you get the assistance required!
