### ISSUE TITLE
AL extension error: language server must close to prevent text buffers not being in sync

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/AL#6748]
Please include the following with each issue:

**1. Describe the bug**
Periodically I get the error below when compiling my apps. It has been going on for a while now and it doesn't matter if I use the insider AL extension or the one published in the marketplace. It happens on multiple apps but is not consistent.

**2. To Reproduce**
It's not consistent but happens at time of compiling the app.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
No error shoudl appear

**4. Actual behavior**
this error appears:

``` AL
[Error - 10:31:43 a.m.] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 '
Details:
System.InvalidOperationException: The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 104
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
```

**5. Versions:**

- AL Language: v8.0.506596 (it has also done this on the marketplace version)
- Visual Studio Code: 1.59.1
- Business Central: v19 insider

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Do you have any more specific repro steps? E.g. do you modify the files externally from VSCode (e.g. doing a git pull)? In addition to this, it might be helpful to get the editor log file. To do this:

- in your VSCode settings.json, set the option "al.editorServicesLogLevel": "Verbose",
- reproduce the problem scenario
- there should be an editorservices.log file under the following path: C:\Users\<username>\.vscode\extensions\ms-dynamics-smb.al-<version number>\bin\win32
- don't forget to turn off verbose logging when done, the logs can easily fill up disk space if left turned on for a long time.

**Comment by MikeGlue** [comment]
I'll answer what I can but really this just seems to happen inconsistently. Today I received this error while simply downloading symbols from my database. Last week it happened while I was compiling my app. I'm not modifying the files outside of VS Code at all so nothing really special going on. I have attached a ZIP with my log file.

[EditorServices.zip](https://github.com/microsoft/AL/files/7146695/EditorServices.zip)

**Comment by kalberes** [comment]
You have  a file called .vscode/**temp-al-proxy.al**
This is a file that is not created by us, but some extension that you are using and it causes problems.

**Comment by MikeGlue** [comment]
Ahh ok I was not aware that wasn't your file. 

For reference, it appears to be from this extension:
https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline

Closing this issue.
