### ISSUE TITLE
IntelliSense keeps loading after some minutes of working

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#6749]
**1. Describe the bug**
AL Language keeps crashing. When this happens IntelliSense is not response (just loading).
It is hard to reproduce, I know, but some of my colleagues got same problem for some week now, so I thought it would be a good to report it and ask if you have any advice...
It only happens with AL, the rest of VS Code works just fine.

**2. To Reproduce**
Just work with the language

**3. Expected behavior**
IntelliSense works just fine

**4. Actual behavior**
IntelliSense keeps loading after some minutes of working.

**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code: 1.59.1
- Business Central: -
- List of Visual Studio Code extensions that you have installed:
   - AL Language
   - AL Variable Helper
   - Fix AL File Names

**Comment by thloke** [comment]
When you mention "keeps crashing", do you get a stacktrace in the output window? If so, can you share it? If not, it might be helpful to get the editor log file. To do this:

1.  in your VSCode settings.json, set the option `"al.editorServicesLogLevel": "Verbose",`
2.  reproduce the problem scenario
3.  there should be an editorservices.log file under the following path: `C:\Users\<username>\.vscode\extensions\ms-dynamics-smb.al-<version number>\bin\win32`
4.  don't forget to turn off verbose logging when done, the logs can easily fill up disk space if left turned on for a long time.

**Comment by DSaladinCH** [comment]
No, there is no error visible.
But we set the editor service log level to verbose. So, here you go:

[EditorServices.log](https://github.com/microsoft/AL/files/7083814/EditorServices.log)

**Comment by thloke** [comment]
@DSaladinCH - Can you try to repro with **only** the AL Language extension installed. We think it might be caused by hooks from other extensions into our language server.

**Comment by DSaladinCH** [comment]
Of course. We'll try it next week. Thanks for your effort so far :)

**Comment by thloke** [comment]
Also, if it does repro, please turn on verbose logging and collect the editorservices.log file again.

**Comment by DSaladinCH** [comment]
One of my colleagues got the error too. Then he deactivated all extensions and set the logging to verbose. Here is the log file:
[EditorServices.log](https://github.com/microsoft/AL/files/7104947/EditorServices.log)

**Comment by kalberes** [comment]
Please try disabling your AL codeAnalyzers and see if the issue still persists.

**Comment by DSaladinCH** [comment]
Okay, we will try. I'll give you a feedback until tomorrow :)

**Comment by EmilDamsbo** [comment]
@DSaladinCH Have you successfully reproduced the crash with AL code analyzers disabled?

**Comment by DSaladinCH** [comment]
I'm sorry you had to wait. We currently testing everything. I'll give you a feedback tomorrow!

**Comment by DSaladinCH** [comment]
Soo, we tested it without the code analyzers, but it doesn't work either. We also collected the editorservices.log, but it does not contain any information about the crash/error. The file only contains some git file logs (which file were changed). Sooo... do you have a clue why it does not work?

**Comment by DSaladinCH** [comment]
Did you guys find something? :)
