### ISSUE TITLE
Enum value Caption with Locked = true works in OnPrem container, but not when released to cloud (translation).

### ISSUE THREAD

**Issue by MiePlougstrup** [microsoft/AL#6750]
**1. Describe the bug**
I have created an enum with four values.
The first with blank Caption with locked = true, to avoid translating the blank value.
![image](https://user-images.githubusercontent.com/14122139/131475353-cadd1f71-14c4-4885-b04e-89807d04900f.png)

Docker container - OnPrem:
Version: DK Business Central 18.3 (platform 18.0.27224.27469 + program 18.3.27240.27480).

Language en-US:
![image](https://user-images.githubusercontent.com/14122139/131476948-3fadd182-3c23-4de2-8cfd-b4704b51498f.png)

Language da-DK:
![image](https://user-images.githubusercontent.com/14122139/131477063-82482f32-2d41-421b-9fc1-2800ceb06ecd.png)

Customers cloud environment:
Version: DK Business Central 18.3 (Platform 18.0.27224.29496 + Application 18.3.27240.27381).

Language en-US:
![image](https://user-images.githubusercontent.com/14122139/131477520-824d401b-983c-4bc3-ba2b-5776f4a30c61.png)

Language da-DK:
![image](https://user-images.githubusercontent.com/14122139/131477680-6afd02a1-8f72-42fa-8c31-d464ff5e7461.png)

**2. To Reproduce**
Create an enum as descriped above, and release to a similar cloud environment.

**3. Expected behavior**
I expect the translation to use the locked value (blank) when the extension is released to the customers cloud environment.

**4. Actual behavior**
The enum value is not translated from the caption, but shows the enum value name.

**5. Versions:**

- AL Language: 7.4.496506
- Visual Studio Code: 1.59.1 Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
- Business Central:
    - Docker container - OnPrem: Version: DK Business Central 18.3 (platform 18.0.27224.27469 + program 18.3.27240.27480).
    - Customers cloud environment: Version: DK Business Central 18.3 (Platform 18.0.27224.29496 + Application 18.3.27240.27381).
- List of Visual Studio Code extensions that you have installed: Not relevant

**Comment by MiePlougstrup** [comment]
Supplement:
I have now removed the locked attribute, and added a translation for the blank value.
![image](https://user-images.githubusercontent.com/14122139/131488094-79802170-e646-4064-ae6a-b47a68f6de37.png)
![image](https://user-images.githubusercontent.com/14122139/131488141-bf6b605e-71f9-422a-b839-f4f1ae79aefd.png)

The issue is still the same: The enum value name is shown, and not the blank caption.

**Comment by thpeder** [comment]
Hi @MiePlougstrup,
I tried what you said, but is unable to reproduce the issue. 
We made a change in 18.3 to address this issue but I might have missed something.

Could you share a small app that reproduces the issue so I'm sure not to have missed something?
Thanks!

**Comment by thpeder** [comment]
If you are still having the issue, feel free to open a new issue with a repro, and please also give it a try on the latest release.
