### ISSUE TITLE
Payments in international currency

### ISSUE THREAD

**Issue by developmentleasba** [microsoft/AL#6757]
Good morning!

How could I export a payment file with international currency in Business Central? It would have to be a file similar to SEPA, but as I mentioned, it has to be in international currency.

Best regards!

**Comment by dnpb** [comment]
This repo is for bugs in the AL language/compiler, not general support.

**Comment by nndobrev** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.
