### ISSUE TITLE
Issue while publishing App on Sandbox : Insufficient permissions TableData Published Application: IndirectInsert

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#6758]
Please include the following with each issue:

**1. Describe the bug**
Publishing an app to a sandbox results in error:
SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: U hebt onvoldoende machtigingen voor TableData Published Application: IndirectInsert.
= You have insufficient permissions for TableData Published Application: IndirectInsert.

App gets published nicely on SandboxDev
on same tenant, same appversion, same permissions
App does not contain breaking changes

Same as #5975 
and this thread:
https://www.yammer.com/dynamicsnavdev/threads/1205490514788352

(but we are on BC18.CU4 and permissions have been given)

Permissions:
![image](https://user-images.githubusercontent.com/34303738/132189001-605270a9-7baf-4d4a-8770-162dc2b63b6f.png)
User:
![image](https://user-images.githubusercontent.com/34303738/132190295-685134dd-a34c-4cef-93e6-042e667d5df5.png)

**2. To Reproduce**

1. Create app, publish on environment

**3. Expected behavior**
App gets published

**4. Actual behavior**
SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2021-09-06 09:57:31.96] The request for path /v2.0/SandboxTest/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: U hebt onvoldoende machtigingen voor TableData Published Application: IndirectInsert.

Als u details van uw machtigingen wilt weergeven, raadpleegt u de pagina Effectieve machtigingen. Als u een probleem wilt melden, raadpleegt u de volgende serversessie-id: 2153.

**5. Versions:**

- AL Language: 7.4.496506
- Visual Studio Code:
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
- Business Central: BE Business Central 18.4 (Platform 18.0.28593.29542 + Application 18.4.28601.29160)
- List of Visual Studio Code extensions that you have installed:
andrzejzwierzchowski.al-code-outline
BartPermentier.al-toolbox
chunsen.bracket-select
ClipDynamics.al-language-tools
coderAllan.vscode-dgmlviewer
CoenraadS.bracket-pair-colorizer-2
davidfeldhoff.al-codeactions
DotJoshJohnson.xml
dynasist.al-studio
eamodio.gitlens
funkyremi.vscode-google-translate
Gruntfuggly.todo-tree
heaths.vscode-guid
humao.rest-client
jamespearson.al-test-runner
martonsagi.al-object-designer
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-dynamics-smb.al
ms-mssql.mssql
ms-vscode.powershell
rasmus.al-formatter
rasmus.al-var-helper
usernamehw.errorlens
waldo.crs-al-language-extension
wayou.vscode-todo-highlight
wbrakowski.al-navigator
yzhang.markdown-all-in-one

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thpeder** [comment]
Hi @BertDeTemmerman,
I see that you already posted on the Yammer thread but for everybody else that finds this issue, please have a look at: https://www.yammer.com/dynamicsnavdev/threads/1205490514788352

**Comment by BertDeTemmerman** [comment]
> Hi @BertDeTemmerman,
> I see that you already posted on the Yammer thread but for everybody else that finds this issue, please have a look at: https://www.yammer.com/dynamicsnavdev/threads/1205490514788352

I already referenced the yammer thread in the post, but an extra time doesn't hurt. :)

**Comment by thloke** [comment]
Sorry that we couldn't get to this sooner, we're trying to work through our backlog of issues. I'm going to close this since it's for an older version of BC than the latest available. If it still occurs, please open a new issue. We've also addressed a few issues in this area in the 19.0 release, so it might work now.

**Comment by BertDeTemmerman** [comment]
> Sorry that we couldn't get to this sooner, we're trying to work through our backlog of issues. I'm going to close this since it's for an older version of BC than the latest available. If it still occurs, please open a new issue. We've also addressed a few issues in this area in the 19.0 release, so it might work now.

Since the BC19 update, we haven't had the problem (yet).
So hopefully it's fixed ... :)
If we have it again, we shall refer to this one.
Thank you.
