### ISSUE TITLE
vsix extension fails to load for runtime version 8.0 - BC19 docker preview sandbox image -19.0.29831.0

### ISSUE THREAD

**Issue by mcoNAV** [microsoft/AL#6759]
- AL Extension Version: 
v8.0.513901

- Server Version: 
BC19 - Windows Bersion 10.0.17763 Build 17763 - Server Data Center 2019 - image installed from available template.

I have been unable to load a valid AL extension into VS Code for any of the BC19 docker preview images.  After installing the "new version" from the vsix as soon as the AL extension loads it fails with the error below.  I can revert back to the current public versions however that won't allow runtime 8 and anything below runtime 8.0 cannot target BC19.    Any ideas how to fix this one?  I've disabled all other VScode extensions and tried uninstalling reinstalling with the same issues and no luck.

[Error - 12:15:44 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message **'workspace/didChangeConfiguration'** failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.

And also 

[Error - 12:15:44 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by thloke** [comment]
@mcoNAV  - can we get the full stack trace in the output window (feel free to redact user filepaths) or the editorservices.log file? To do this:

1.  in your VSCode settings.json, set the option `"al.editorServicesLogLevel": "Verbose",`
2.  reproduce the problem scenario
3.  there should be an editorservices.log file under the following path: `C:\Users\<username>\.vscode\extensions\ms-dynamics-smb.al-<version number>\bin\win32`
4.  don't forget to turn off verbose logging when done, the logs can easily fill up disk space if left turned on for a long time.

You can send the editorservices.log file to me via email (thloke@microsoft.com).

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 29995 and VS Code Extension Version 9.0.516711. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
