### ISSUE TITLE
Blob filed are not getting synced to CRM Blob filed through dataverse integration.

### ISSUE THREAD

**Issue by ngapandey** [microsoft/AL#6760]
Is it possible to sync a blob field through dataverse to a blob field in CRM?

I have synced few custom fields from Item to CRM Product. Rest of field with datatype Decimal, Option, Text are syncing okay but the blob field is not syncing. Any reason why?

**Comment by thloke** [comment]
Hi! This is a question for the relevant app team, not this repository as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible. 
 

To open a support case, you can: 

 

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

 

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
