### ISSUE TITLE
Can change the property value of table field ?

### ISSUE THREAD

**Issue by divjotn** [microsoft/AL#6761]
Hi Freddy,
Can we change the Property Value of any table field  for the app source , without getting AL Validation failed?
Basically I need to change the value of "DecimalPlaces" Property of table field and worried about the AL Validations.

Please Suggest.

Thanks in advance.

**Comment by thpeder** [comment]
HI @divjotn,
You can read more about the validation here: [Technical Validation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission).
It include as section where you can [run the validation yourself](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission#running-technical-validation-yourself)

**Comment by qutreson** [comment]
You can also use the [AppSourceCop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop) the know whether the change is allowed.
