### ISSUE TITLE
GlobalTriggerManagement events

### ISSUE THREAD

**Issue by adrianordonezm** [microsoft/AL#6762]
**1. Describe the bug**
i am trying to subscribe to the following events

- OnAfterOnGlobalInsert
- OnAfterOnDatabaseInsert
- OnAfterOnDatabaseModify

from code unit GlobalTriggerManagement  but is not executing my code

**2. To Reproduce**
Create code unit and add the following code

```AL
[EventSubscriber(ObjectType::Codeunit, Codeunit::GlobalTriggerManagement, 'OnAfterOnGlobalInsert', '', false, false)]
local procedure MAQLogInserttt(RecRef: RecordRef)

begin
    Message('1');
end;

[EventSubscriber(ObjectType::Codeunit, Codeunit::GlobalTriggerManagement, 'OnAfterOnDatabaseInsert', '', false, false)]
procedure MAQLogInsert(RecRef: RecordRef)
begin
            Message('1');
end;

[EventSubscriber(ObjectType::Codeunit, Codeunit::GlobalTriggerManagement, 'OnAfterOnDatabaseModify', '', false, false)]
procedure MAQLogUpd(RecRef: RecordRef)
begin
            Message('1');
end;
```

**3. Expected behavior**
Send the message on any insert or modify event on any table

**4. Actual behavior**
not sending the message

**5. Versions:**

- AL Language: v7.4.502459
- Visual Studio Code: 1.59.1
- Business Central: 18.4
- List of Visual Studio Code extensions that you have installed:
            - Al Language
            - AL Object Designer

**Comment by dnpb** [comment]
Don't you just need to set up which triggers should fire, for which tables?

https://community.dynamics.com/nav/f/microsoft-dynamics-nav-forum/184884/nav2015---adding-custom-code-to-ondatabaseinsert-modify-delete-rename/461762

**Comment by NKarolak** [comment]
Good point anyway: it is definitely not mentioned yet in the docs, but hopefully fixed soon:
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2030
