### ISSUE TITLE
Intellisense: page field does not add the (explicit) Rec

### ISSUE THREAD

**Issue by reiniroosh** [microsoft/AL#6763]
**1. Describe the bug**
When adding a field to a page, AL will allow me to pick a field from the Rec and fill in the values.
However it doesn't do this properly, neglecting to add the `Rec`

eg, instead of:
`field(Area; Rec.Area)`
it creates:
`field(Area, Area)`

**2. To Reproduce**
Go to a page layout, start typing `field(` and press Ctrl+Space to bring up the suggestions.
Select one of the record fields.

```
pageextension 50100 "Item Card" extends "Item Card"
{
    layout
    {
        addlast(Content)
        {
            group("foobar")
            {
                field("Commodity No.";"Commodity No.") { }
}}}}
```

**3. Expected behavior**
It would be nice if intellisense filled in the field according to best practices.
(It also leaves out the spaces, kind of annoying but handled by the format document anyways.)

**5. Versions:**

- AL Language: v7.4.502459
- Visual Studio Code:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z (9 mos ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

- Business Central: N/A
- List of Visual Studio Code extensions that you have installed: none

**Comment by dnpb** [comment]
seems like a dupe of https://github.com/microsoft/AL/issues/6240

> This is by design. If you opt-in for not using implicitwith with `#pragma implicitwith disable` the auto-completion includes the `Rec.`.
> 
> The rationale behind this design is that until you choose to switch over for an object, your source-code will look consistent.

The upshot for me was:

> Anyway, I guess now I have to go and add `NoImplicitWith` in `app.json` to all my projects, to avoid the compiler deciding I don't want `Rec.` prefixes and thus generating wrong code.

**Comment by reiniroosh** [comment]
Thank you, not sure why I didn't find that issue when I was searching.
