### ISSUE TITLE
SetLoadFields slow JTL response issue

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/AL#6764]
**1. Describe the bug**
I hope this is the correct place to report this issue, it is not an issue within the base app or any AL written code by Microsoft. Its more of an issue with how the underlying system handle SetLoadFields.

For about a week one of our customers get the following error message.
> The field Bin Code of table Warehouse Shipment Line contains a value (SYRUM) that cannot be found in the related table (Bin).

However we have been using this code for a long time and there is no data issue to be found. I have tracked the issue and it seems to be caused by the SetLoadFields when a field not included in SetLoadFields is used in the table relation validation. A very special thing is that if you debug the code slowly the function that cause the issue works fine. But when you run it normal or debug the code very fast you get the error. 

This made me think a bit. It has something to do with how SetLoadFields work where it seems the code continue to execute even if a JTL load is needed because the developer forgot a field in SetLoadFields. I have found nothing stating this is working as intended, previously the AL code execution was halted until the JTL load finished. 
 
**2. To Reproduce**

I created 2 functions to test the issue in the customer sandbox that let me reproduce the error message and the solution to it.

1. Place these function in a new codeunit
2. Create another function and simply get any warehouse shipment line and send it as parameter to any of my functions. Make sure to also include a valid BinCode for  that shipment line.
3. Run the code

``` AL
    local procedure TestSetLoadFields_Working(WhseShptLine_P: Record "Warehouse Shipment Line"; BinCode: Code[20])
    var
        WhseShptLine: Record "Warehouse Shipment Line";
    begin
        WhseShptLine.SetLoadFields("Line No.", "Source Line No.", Quantity, "Source Document", "Source No.", "Bin Code", "Location Code");
        WhseShptLine.Get(WhseShptLine_P."No.", WhseShptLine_P."Line No.");
        WhseShptLine.Validate("Bin Code", BinCode);
    end;

    local procedure TestSetLoadFields_NotWorking(WhseShptLine_P: Record "Warehouse Shipment Line"; BinCode: Code[20])
    var
        WhseShptLine: Record "Warehouse Shipment Line";
    begin
        WhseShptLine.SetLoadFields("Line No.", "Source Line No.", Quantity, "Source Document", "Source No.", "Bin Code");
        WhseShptLine.Get(WhseShptLine_P."No.", WhseShptLine_P."Line No.");
        WhseShptLine.Validate("Bin Code", BinCode);
    end;
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
With function TestSetLoadFields_NotWorking the Validation should pass without any errors.

**4. Actual behavior**
When function TestSetLoadFields_NotWorking runs we get the error
>The field Bin Code of table Warehouse Shipment Line contains a value (SYRUM) that cannot be found in the related table (Bin).

However when I run the TestSetLoadFields_Working everything works fine after adding "Location Code" to the SetLoadFields.
**5. Versions:**

- AL Language: v7.4.502459
- Visual Studio Code: 1.60.1
- Business Central: 18.4.28601.29160
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by PhDuck** [comment]
I think this was actually fixed in version 19, @CarlOhlsson would you be able to test out the code on a 19 preview docker instance?

**Comment by CarlOhlsson** [comment]
I can test it but a bit short on time this week. Will hit back here when

**Comment by PhDuck** [comment]
> Will the fix be backported to 18.x?

Depends, if it is what we already fixed, it is rather likely that we could backport it since the change is small.
If it is some new large bug that will require a large change to fix, then most likely not.

**Comment by PhDuck** [comment]
@CarlOhlsson Have you found any time to reproduce this on 19?

I'm not going to prioritize this before I know if it reproduces on 19.

**Comment by CarlOhlsson** [comment]
@PhDuck Dont have an exact copy of my scenario in a 19 environment but I set up something similar with another record and it seems to be fixed. Tested on the just released saas version.
