### ISSUE TITLE
Take Picture functionality Issue Again

### ISSUE THREAD

**Issue by chancellorowens** [microsoft/AL#6766]
This issue has popped back up:
https://github.com/microsoft/AL/issues/5755

Taking a picture on mobile in the Expense Sheet Attachments results in the following error:

![image](https://user-images.githubusercontent.com/17076721/133621349-d3570e43-724c-49ee-8f87-a2171757fd09.png)

on following build
Version: US Business Central 18.4,PGS 7.5.0.1,PGS 7.3.0.0 (Platform 18.0.28593.29542 + Application 18.4.28601.29726).

**Comment by dnpb** [comment]
That issue was closed as off-topic, so isn't this one too?

**Comment by kalberes** [comment]
Yes. The same comment applies
