### ISSUE TITLE
Can we increase the field length by table extension. Field is not a part of a primary key?

### ISSUE THREAD

**Issue by srinivasdes** [microsoft/AL#6770]
Can we increase the field length by table extension. Field is not a part of a primary key

**Comment by dnpb** [comment]
Did you try it? What error did you get? That probably is by design that you can't.

**Comment by nndobrev** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
