### ISSUE TITLE
Missing overflow warning when assigning values using Validate()

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6771]
Please include the following with each issue:

**1. Describe the bug**
When a value is assigned to a field using the Validate() method, in order to raise any validation triggers, the AL analyzer does not check for possible overflows, as it does if the same field is assigned using the ":=" operator.

![CleanShot 2021-09-22 at 09 34 48](https://user-images.githubusercontent.com/6630306/134301764-fa93140d-2fea-4d96-9ff5-2f0d47c4b786.png)

**2. To Reproduce**
Just create a new project with this table (and code analysis enabled):

```
table 50100 "MyTable"
{
    fields
    {
        field(1; "Code"; Code[20])
        {
            Caption = 'Code';
            DataClassification = CustomerContent;
        }
    }

    trigger OnInsert()
    var
        LongText: Code[30];
    begin
        LongText := '012345678901234567890123456789';
        Rec."Code" := LongText;
        Rec.Validate("Code", LongText);
    end;
}
```

**3. Expected behavior**
Both lines that assign the value of the variable LongText to field "Code" should raise an overflow warning.

**4. Actual behavior**
Only the one that uses the := operator to assign the value raises the warning.

**5. Versions:**

- AL Language: v8.0.508407 (this seems to be a bug since forever, we just found an error due to an overflow that had been hidden in our code since the first version of BC).
- Visual Studio Code: 1.60.1

**Comment by dnpb** [comment]
If this is a bug - which I agree that it is - then why isn't this other one?
[Missing warning in case of possible overflow in setrange #6726](https://github.com/microsoft/AL/issues/6726)

**Comment by kalberes** [comment]
Yes that is a bug too. When(??) this is fixed we will try to add the same semantics to all similar context.

**Comment by pri-kise** [comment]
@dnpb i agree with you that SetRange should check for the length, too.
But if there is a check for SetFilter (https://github.com/microsoft/AL/issues/6726#issuecomment-891718582) too, the check should correctly deal with FilterStrings.
e.g. the following FilterString has more than 10 characters, but is still valid.
```al
Rec.SetFilter("Field with Code10",'1234567890|0123456789')
```

**Comment by dnpb** [comment]
Yes, I know. I mentioned that caveat on [the Idea](https://experience.dynamics.com/ideas/idea/?ideaid=0ed04605-a0f6-eb11-ba5e-0003ff459e25) but didn't repeat it here.

**Comment by Lazys** [comment]
Hi, any update on this issue?

**Comment by mocu97** [comment]
I'm waiting too... 😞

**Comment by EmilDamsbo** [comment]
We have addressed this issue and the fix will be available in an upcoming release.

**Comment by EV-ANK** [comment]
Are this still an issue? Or has it becomde one again?
