### ISSUE TITLE
Expose all warnings in workspace

### ISSUE THREAD

**Issue by PeterBizz** [microsoft/AL#6773]
In AL when codecop/compiler generates over 100 warnings for one file any additional warnings are not shown. This prevents me from getting an overview of the total number of warnings in my workspace.

I understand that this is performance related, but sometimes you simply want them all ( ALRunner: Export Diagnostics ) . 

Would it be possible to change this number with some setting?

**Comment by kalberes** [comment]
We could and could make sense.
Please add an idea that it is tracked 
![image](https://user-images.githubusercontent.com/12760483/134549380-c799f847-3be1-45fb-8985-a920c4e339da.png)
 and than we will evaluate it
