### ISSUE TITLE
Repair-NavApp - Apps no more vissible or available in Client

### ISSUE THREAD

**Issue by sweikelt** [microsoft/AL#6774]
- AL Extension Version: 157.014

- Server Version: 18.0.29486.0 [OnPrem] ... and earlier

no code required!

if we use the repair-navapp command, the apps will not be available in the client (via search or something else)
we then have to uninstall and unpublish these apps and republish/reinstall these (without repair-navapp)
this seems to happen, if the published app was created on a lower serverversion than the used one

example:
```
Publish-NAVApp -ServerInstance BC -Path <<<FullAppPath>>>
Repair-NAVApp -ServerInstance BC -Name <<<YourAppName>>
sync-NAVApp -ServerInstance BC -Name <<<YourAppName>>
install-NAVApp -ServerInstance BC -Name <<<YourAppName>>

```

and the best of this story is: sometimes we get a sql error (on installing) which then causes dataloss because then we have to sync in forceMode <- this case is really hard to reproduce and i'm trying to find a solid way for you guys.

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/134550773-b6e63c33-8739-4597-9263-679819ae1791.png)
If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.
