### ISSUE TITLE
Open InPrivate

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/AL#6776]
Similar to #4340 Could you please make the action "Copy And Open" respect the same settings when downloading symbols

- AL Extension Version: 
v7.4.502459

- Server Version: 
N/A

**Comment by kalberes** [comment]
It makes sense, the only problem is that we have no programmatic control on the copy and open dialog as for now.
The best would be to add an idea 
![image](https://user-images.githubusercontent.com/12760483/134547539-c8eb7d61-ebdc-454f-8e19-1abf3c35742c.png)
We will have to do some refactoring in the near future here and maybe our options to hook in the settings which are part of workspace API will be better.
