### ISSUE TITLE
How-can-i-sign-a-string-using-rsa-and-sha1-with-AL- BC Cloud

### ISSUE THREAD

**Issue by AvnishP613** [microsoft/AL#6777]
I am working with a task where we need to sign data by using private key received from Azure Vault.
as per these specifications defined
![image](https://user-images.githubusercontent.com/72007996/134644037-fe9920b9-52fb-43cc-a0e0-868b3807a751.png)

![image](https://user-images.githubusercontent.com/72007996/134644559-6691ea14-7c08-46b5-93b5-8deac07f2347.png)
we are running in this issue
![image](https://user-images.githubusercontent.com/72007996/134643844-cc0fe4c7-8d64-459e-822a-3e11f6831691.png)

Here we are able to do it by following this blog:
[https://www.c-sharpcorner.com/article/how-to-access-azure-key-vault-secrets-through-rest-api-using-postman/](url)

after having this key in system we are trying to use Codeunit cryptography or RSA function signdata.

The Private key which we are receiving is in Base64 format.

[CryptoGraphy.txt](https://github.com/microsoft/AL/files/7224264/CryptoGraphy.txt)

[https://community.dynamics.com/business/f/dynamics-365-business-central-forum/380150/using-cryptography-management](url)
We have been through this also as installing a utility for Cloud does not seems valid option.
Attaching file with Code:Tried with both Cryptography Codeunit and RSA Codeunit
 trigger OnRun()
    var
        SIGNATURERECORD: Record "Signature Key";
        CryptoMgmt: Codeunit "Cryptography Management";
        rsa: Codeunit RSACryptoServiceProvider;
        Algo: Enum "Hash Algorithm";
        stream: InStream;
        outstream: OutStream;
        OUTSTREAM1: OutStream;
        TempBLOB: Codeunit "Temp Blob";
        SecretKey: Text;
        hASHVALUE: Text;
    begin
        SecretKey := 'MIICXgIBAAKBgQDIYh3tSlmpU7rxPepe+c20abLXiYpI1NfxlKh9OThouEble9ir3ymDq4H/OuKsw6yZ21QFYvuE1U7vrwqECb1lmOY4EqdcsmxgKvoZVOcHgB3Bj4DiSl6yGbOE6wwoJbUXlO39eKBRYGBGdg1POEr2ivDPph0XvSk+y+7sZ3ZF1QIDAQABAoGAYtkL3EdmDYJxYJnjaLCfydSuVWbS4XSlhdWIfCVi7z2gM4oxay9t4jcTrJ0WvpTUKx2nx/R5EKDNDK1zaYkIdRs+ASDSI4UuJ9XDLjB3ei9HnNP83ZzSoZ3LYHGNvuqM8ZSk9dJmb7+wuJocScOOnh8LI2GEjYd48SrPxQpXiEECQQDoO5304nUH1ZAuGWel5AER0F9Zg2XEA8carN3AQ4fjX+dKCSgWlYxjMtwjXpN0FL0ohTbvmvJgO3E9XLgdvQYFAkEA3OQObQYw5RokYHg7gmq+20+nyWm2gdbxfG7FyfIfpKCWoLIGMLcTprXr6Xgap/aTvPuuBknmXM5wtqPAxU/5kQJBAJDA6FpF9ZCmi7JQX4zFq+0Apw5SmtItUKPN8ILxFPijRLWfM3+wQ8tpXlIll1+ZtbZWIsIDIOTe6FzJOHJA6kkCQQDOpozYcnJL46kkl1cVK8hiZKMUS1HzJqPFRdzEkUAJRDOnIuWnrZ801/1c7oABoy2UH+EvAPQC3x+Tvp8Z+TgBAkEAySwRR2zFCcQFUYje26G60tyzcd1yKDBau3OOyxC/h1emBWoJtz+VC2nuA3gxBgwSq3sH2jJ2+WEHtolGLz3sCQ==';
        // SecretKey := '<RSAKeyValue><Modulus>' + SecretKey + '</RSAKeyValue>';//'</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>';
        SIGNATURERECORD.DeleteAll();
        SIGNATURERECORD.Init();
        SIGNATURERECORD."Key Index" := 1;
        SIGNATURERECORD.FromXmlString(SecretKey);
        SIGNATURERECORD.Insert();
        CryptoMgmt.SignData('FAC11', SIGNATURERECORD, Algo::SHA1, outstream);
        SIGNATURERECORD.Delete();
        outstream.WriteText(hASHVALUE);

        //RSA Codeunit
        SecretKey := 'MIICXgIBAAKBgQDIYh3tSlmpU7rxPepe+c20abLXiYpI1NfxlKh9OThouEble9ir3ymDq4H/OuKsw6yZ21QFYvuE1U7vrwqECb1lmOY4EqdcsmxgKvoZVOcHgB3Bj4DiSl6yGbOE6wwoJbUXlO39eKBRYGBGdg1POEr2ivDPph0XvSk+y+7sZ3ZF1QIDAQABAoGAYtkL3EdmDYJxYJnjaLCfydSuVWbS4XSlhdWIfCVi7z2gM4oxay9t4jcTrJ0WvpTUKx2nx/R5EKDNDK1zaYkIdRs+ASDSI4UuJ9XDLjB3ei9HnNP83ZzSoZ3LYHGNvuqM8ZSk9dJmb7+wuJocScOOnh8LI2GEjYd48SrPxQpXiEECQQDoO5304nUH1ZAuGWel5AER0F9Zg2XEA8carN3AQ4fjX+dKCSgWlYxjMtwjXpN0FL0ohTbvmvJgO3E9XLgdvQYFAkEA3OQObQYw5RokYHg7gmq+20+nyWm2gdbxfG7FyfIfpKCWoLIGMLcTprXr6Xgap/aTvPuuBknmXM5wtqPAxU/5kQJBAJDA6FpF9ZCmi7JQX4zFq+0Apw5SmtItUKPN8ILxFPijRLWfM3+wQ8tpXlIll1+ZtbZWIsIDIOTe6FzJOHJA6kkCQQDOpozYcnJL46kkl1cVK8hiZKMUS1HzJqPFRdzEkUAJRDOnIuWnrZ801/1c7oABoy2UH+EvAPQC3x+Tvp8Z+TgBAkEAySwRR2zFCcQFUYje26G60tyzcd1yKDBau3OOyxC/h1emBWoJtz+VC2nuA3gxBgwSq3sH2jJ2+WEHtolGLz3sCQ==';

        Clear(outstream);
        TempBLOB.CreateOutStream(OUTSTREAM1, TextEncoding::UTF8);
        OUTSTREAM1.WriteText('FAC11');
        TempBLOB.CreateInStream(stream);
        rsa.SignData(SecretKey, stream, Algo::SHA1, outstream);
        outstream.WriteText(hASHVALUE);
        Message(hASHVALUE);
    end;

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
