### ISSUE TITLE
Enum value hided in page if contains single double quote

### ISSUE THREAD

**Issue by JPicard90** [microsoft/AL#6778]
If an enum caption value contains a single double quote “ at the end the following enums will not be shown.

    value(50048; "My value 8")
    {
        Caption = '8"'; //Breaks value 9 to show
    }
    value(50049; "My value 9")
    {
        Caption = '9';
    }

If a single char in a captain is not allowed, I expect a compiler issue.

Versions:**
- AL Language: 7.2
- Visual Studio Code: 1.60.2
- Business Central: 18.5.29545.0

**Comment by nndobrev** [comment]
Hi @JPicard90, 

Unfortunately, I can't reproduce the issue, could you please provide more information?

This is what I see:
![image](https://user-images.githubusercontent.com/85873063/135223244-ceb678ad-73ff-4932-aec0-532a632a5752.png)

**Comment by JPicard90** [comment]
sorry, 
i forget to specify:

so use this enum inside a table,
use the table inside a page of "ListPart" type

**Comment by nndobrev** [comment]
@JPicard90, can you please provide code sample that reproduces the issue :)

**Comment by JPicard90** [comment]
enum 50010 "Test Enum"
{
    Extensible = true;

    value(50044; "Enum Visible 1")
    {
        Caption = 'Enum Visible 1';
    }
    value(50048; "Enum Visible 2")
    {
        Caption = 'Enum Visible 2';
    }
    value(50049; "With Error")
    {
        Caption = 'With Error"';
    }
    
    value(50050; "Non Visible")
    {
        Caption = 'Non Visible';
    }
}



table 50000 "Record Update Request line"
{
    Caption = 'Righe richiesta modifica record';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Request ID"; Code[20])
        {
            Caption = 'ID Richiesta';
            DataClassification = ToBeClassified;
        }

        field(3; "Line No."; Integer)
        {
            Caption = 'Line No.';
            DataClassification = ToBeClassified;
        }



        field(200; "Test Enum"; Enum "Test Enum")
        {
			Caption = 'Test Enum';
            DataClassification = ToBeClassified;
        }
	}
	keys
    {
        key(PK; "Request ID", "Line No.")
        {
            Clustered = true;
        }
    }
}

page 50000 "Customer Update Rec. Subpage"
{

    Caption = 'Campi da aggiornare cliente';
    PageType = ListPart;
    SourceTable = "Record Update Request line";
	AutoSplitKey = true;
    layout
    {
        area(content)
        {
            repeater(General)
            {
                field("Customer Field No. Enum"; rec."Customer Field No. Enum")
                {
                    ApplicationArea = All;
                }
            }
        }
    }
}
