### ISSUE TITLE
REPORT.SAVEASPDF(ReportNo,FileName,Rec) in Extension (Web Client)

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#678]
How can we save the pdf of a REPORT.SAVEASPDF action to use it later for e-mail attachment or something else?

`REPORT.SAVEASPDF(ReportNo,FileName,Rec);`

Because function **ServerTempFileName** in codeunit **File Management** is not available.

**Comment by dkorinets** [comment]
Take a look here https://github.com/Microsoft/AL/issues/354

**Comment by bvbeek** [comment]
Thanks! That's usefull for us. Issue can be closed.
