### ISSUE TITLE
The image Cloud is not valid in this context (AL0482)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6781]
**1. Describe the bug**
I'm getting an **AL0482** warning, but can't find much explanation on what might be wrong.

![image](https://user-images.githubusercontent.com/25268332/135608736-e643035f-9870-4440-9caf-19f39bfb969b.png)

**2. To Reproduce**

An extension targetting Cloud, bc19, with an action on a normal list page

```
action("Open In OneDrive")
                {
                    ApplicationArea = All;
                    Caption = 'Open in OneDrive';
                    Enabled = ShareOptionsEnabled;
                    ToolTip = 'Copy the file to your Business Central folder in OneDrive and open it in a new window so you can manage or share the file.', Comment = 'OneDrive should not be translated';
                    Image = Cloud;  // <<< Warning
                    Promoted = true;
                    PromotedCategory = Category4;
                    PromotedOnly = true;
                    Scope = Repeater;

                    trigger OnAction()
                    begin
                        Rec.OpenInOneDrive();
                    end;
                }
```

**3. Expected behavior**
I'd like to get more info on why the use of the 'Cloud', 'Download', ... image is not valid in a given context.

**5. Versions:**

- AL Language: Version: 8.0.508407
- Visual Studio Code:
- Business Central: 19.0
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment]
Hi @fvet, the warning you are getting is saying that the value you have specified is incorrect. Do you have a scenario where Cloud or Download can be used as an image for an action? In order to avoid such warnings, I would suggest using IntelliSense to get a list of the possible values for a propery.
