### ISSUE TITLE
ALC.exe does not accept analyzer while AL Extension and devops pipeline do

### ISSUE THREAD

**Issue by PeterBizz** [microsoft/AL#6783]
I try to specify "MyAnalyzer" as analyzer in a call to alc.exe like this:
$Cop  = [MyAnalyzer].dll

alc.exe  /analyzer:$Cop  ........ 

This results in an warning:
"The assembly C:\\Program Files\\GAC Business Solutions\\Gac.Analyzers.AlCop\\[MyAnalyzer].dll does not contain any analyzers"

while in vstudio code al workspace settings: 
"settings": {
		"al.enableCodeAnalysis": true,
		"al.codeAnalyzers": [
			"[MyAnalyzer].dll"
		],

work flawelessly

**Comment by thloke** [comment]
Closing as this is not a supported scenario and is out of scope for this repo.
