### ISSUE TITLE
Debugger - Error: An internal error has occurred when starting debug

### ISSUE THREAD

**Issue by BF9WDR** [Microsoft/AL#6787]
Please include the following with each issue:

**1. Describe the bug**

When pressing f5 with "launch" in the launhc.json:
Debugging does not work. Compiler finishes building the app, but then fails:
[2021-10-07 14:28:51.26] Publishing AL application using launch configuration 'Your own server'.
[2021-10-07 14:28:51.92] Publishing package to tenant 'default'
[2021-10-07 14:28:51.93] Targeting server 'http://servername', server instance 'instancename' and tenant 'default'.
[2021-10-07 14:28:51.93] Using Windows authentication.
[2021-10-07 14:28:51.95] Sending request to http://servername:7049/instancename/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2021-10-07 14:28:53.12] Success: The package 'app_name_1.0.0.2110070544.app' has been published to the server.
[2021-10-07 14:28:53.37] Error: An internal error has occurred

checked wireshark network activity, the debugger itself aborts the process
![image](https://user-images.githubusercontent.com/47924600/136386675-628adc45-4bc4-4190-a377-6c371b710f0e.png)

**2. To Reproduce**
press f5 with a launch.json similar to this
``` JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "servername",
            "serverInstance": "instancename",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default"
        }
    ]
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Debugging to start and the debugger not aborting its 

**4. Actual behavior**
Debugging stops instantly.

**5. Versions:**

- AL Language: v8.1.525271
- Visual Studio Code: tried with 1.61.0-insider and 1.60.2 stable
- Business Central: 18.0 W1
- List of Visual Studio Code extensions that you have installed: only AL Language enabled

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment]
Hi @BF9WDR, unfortunately, this seems to not be a compiler issue but a run-time one. I will close this issue now but I will ask you to open a support case, where the right team will continue the investigation.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" on how to open a support request or how to get credentials if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
