### ISSUE TITLE
How can we send an email with outlook with an attachment?

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#679]
My previous question #678 to safe a report as pdf, was answered.
We can use a OutStream, but how can we send this OutStream as an attachment in Outlook (not SMTP).

What we need is something like this:
```
Report.SaveAs(Report::"Customer - Sales List",'',ReportFormat::Pdf,OutStream,RecRef);
Mail.AddAttachmentFromOutStream(OutStream); // This line is needed!
Mail.Send;
```

**Comment by StanislawStempin** [comment]
What is Mail.Send in your code?

I'm not sure you will be able to use Outlook (I assume this is sending from the client side?) until we re-enable client side javascript add-ins.

**Comment by bvbeek** [comment]
See Codeunit 397 - Mail, there you will see a function called **AttachFile**, but we are not able to save a Temp file on the server.
So we need another function with a parameter OutStream.

Yes it's to send an e-mail from client-side, like the **Send** button on the **Posted Sales Invoice**.
We cannot use the standard because it's working with Report Selection, because it's an Option field. Option Fields cannot be extended as far as I know.
So, we need to build something like that, but I'm struggeling with the (good) restrictions. I hope you can help me with it.

![image](https://user-images.githubusercontent.com/28626283/30385501-ab6839f2-98a7-11e7-8782-126d0c57f617.png)

**Comment by StanislawStempin** [comment]
That codeunit will not work from the web client because it uses client-side .NET.  Web client is the only client supported for SaaS so to achieve this functionality one would need to use JavaScript add-in. 

I will check with our Client team on what are the plans for enabling client-side mailing in the web client.

For OnPrem you will be able to compile with target = Internal and get access to all functions as before.

**Comment by bvbeek** [comment]
I know this setting ;)
We need to send e-mails from the web-client, using Outlook because we want to build the app for Dynamics 365 Financials.

So if you got any news, please let me know!

**Comment by StanislawStempin** [comment]
I got a reply from the Client team and they are not planning to provide support for web-client integration with the Outlook desktop app. Browser architecture simply does not allow that.

Your options for how to handle this situation include an integration with web-based email service or exposing the file for download from the web client and having the user attach it to an email manually.
