### ISSUE TITLE
This AL extension version for Visual Studio Code cannot be used with the specified server.

### ISSUE THREAD

**Issue by pjllaneras** [microsoft/AL#6795]
**1. Describe the bug**
We can't use the AL Language extension to develop on BC 14 anymore, system will return an error: This AL extension version for Visual Studio Code cannot be used with the specified server.

**2. To Reproduce**
Go to any BC 14 project and try to download symbols. The same happens when try to install an extension on BC14 database.

**3. Expected behavior**
Download symbols action must download symbols from database and publish from VSC must be possible.

**4. Actual behavior**
The system gives us an error when try to download symbols or publish from VSC

**5. Versions:**
- AL Language: 8.1.525271
- Visual Studio Code: 1.61.0
- Business Central: 14 build 32600
- List of Visual Studio Code extensions that you have installed:
  - AL Language
  - AL Toolbox
  - AZ AL Dev Tools/AL Code Outline
  - Docker
  - Git Graph
  - GitLens
  - Markdown All in One
  - Markdown Preview Enhanced
  - Remote - Containers
  - Todo Tree
  - vscode-icons
  - waldo's CRS AL Language Extension
  - XLIFF Sync

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue
This issue has been reported previously, but never for BC 14

* [x] Reproduce the issue after disabling all extensions except the AL Language extension
This issue has nothing to do with other extensions, the same happens with no other extension installed (only AL Language)

* [x] Simplify your code around the issue to better isolate the problem
This issue has nothing to do with code, we have tried the example "Hello World" and the error is the same

**Comment by pjllaneras** [comment]
> 

Hi @nndobrev, finally we have solved partially this problem. Using VSC extension from latest BC14, we can download symbols and do debuging, but we can't install an extension from VSC.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

Is this issue still a problem for you? Does it reproduce on the latest release?

**Comment by pjllaneras** [comment]
Hi @thloke, I can confirm we have been working fine for a few months now. We are using latest VSC extension for AL Language. I'm sorry I didn't report this sooner, but this is related to an office colleague's issue, not mine.
