### ISSUE TITLE
"al.backgroundCodeAnalysis": false - turns off codeanalysis

### ISSUE THREAD

**Issue by JSebastianN** [Microsoft/AL#6798]
**1. Describe the bug**
Codeanalysis is turned completely off, when only background is turned off

**2. To Reproduce**
A
Using these settings.json
        "al.enableCodeAnalysis": true,"al.backgroundCodeAnalysis": false,
        "al.codeAnalyzers": ["${AppSourceCop}","${CodeCop}"],
        "al.ruleSetPath": ".codeanalysis/ignore.ruleset.json",

B
Create new unused variable.

**3. Expected behavior**

You would expect to see: "message": "Variable 'i' is unused in ...
But it does not appear.

Codeanalysis should run when building/publishing, just not in background.

**4. Actual behavior**
Our unused variable was not reported in the "Problems" window

**5. Versions:**

- AL Language: 8.1.525271
- Visual Studio Code: 1.61
- Business Central:  BC18 - "runtime": "6.0"
- List of Visual Studio Code extensions that you have installed:

**Comment by dnpb** [comment]
In those cases the warnings/errors would be reported in the Output tab, not Problems. Do you not see it in the former?
