### ISSUE TITLE
question: table renaming + upgrade process

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#680]
We currently have a v1 extension published in AppSource. I've upgraded the extension to v2 but I'd like to change the table names. The table numbers would remain the same, as would the table captions. What are my options? Is that going to be allowed? I wasn't sure if the upgrade process from a v1 extension to a v2 extension would allow me the freedom to do things like that.

**Comment by StanislawStempin** [comment]
We currently don't have capacity to investigate deeper but the educated guess from the owning team is that you should be able to do it (either through NavApp.RestoreArchiveData directly or through NavApp.GetArchiveRecordRef and manually populating the new table). 
I would recommend holding off with making the renaming decision before you can actually test it on your development environment. The upgrade APIs are available in the latest Docker drops and will be available in the October Update.
