### ISSUE TITLE
AA0136 Unreachable code detected - Expected for code after if-else that both result in exit

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#6800]
**1. Describe the bug**
If there are statements after an `if-else`-statement where both paths result in an `exit`-statement, then I would expect rule AA0136 to report a warning on any statement after the `if-else`-statement.

**2. To Reproduce**

1. Set up an AL project with the following procedure in a codeunit:

``` AL
    procedure MyProcedure(Bool: Boolean)
    begin
        if Bool then
            exit
        else
            exit;

        Message('Hello World!');
        exit;
    end;
```

**3. Expected behavior**
Get a warning from AA0136 that unreachable code was detected, similar to how Visual Studio does this for C# (rule: CS0162) for the same example, e.g.:
```cs
        public void MyProcedure(bool Bool)
        {
            if (Bool)
            {
                return;
            }
            else
            {
                return;
            }

            Console.WriteLine('Hello World!');
            return;
        }
```
For the given example, I would expect a warning on the `Message`-statement.

**4. Actual behavior**
No warning from AA0136 about unreachable code.

**5. Versions:**

- AL Language: 8.1.525271
- Visual Studio Code: 1.61.0
- Business Central: W1 19.0 (Platform 19.0.29884.30666 + Application 19.0.29894.30736)
- List of Visual Studio Code extensions that you have installed: **disabled to reproduce**

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
