### ISSUE TITLE
Change launch URL when Publish with Debugging

### ISSUE THREAD

**Issue by ashgibson** [microsoft/AL#6807]
I am building PTE's for business central but we are using Wiise which is hosted at https://wiise.bc.dynamics.com instead of https://businesscentral.dynamics.com. 

Visual Studio deploys the extensions to the sandbox without issue but it opens https://businesscentral.dynamics.com/{sandbox}...&debuggingcontext=... whereas I would like it to open https://wiise.bc.dynamics.com/{sandbox}...&debuggingcontext=... 

I can't find where this is set and if it is a configurable option. I have even tried searching the source code on this repo to try and workout where this value is coming from so i can at least potentially contribute.

**Comment by thloke** [comment]
The property you are looking for is `applicationFamily`. In your case, you want `"applicationFamily" : "wiise"`

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#publish-to-cloud-settings
