### ISSUE TITLE
[Bug] CodeCop vs. Compiler - Problem in Reports with AA0005

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#6808]
The warning "AA0005: Only use BEGIN..END to enclose compound statements." is ignored by the codecop in object type report.

The compiler show the warnings without problems.

Runtime 8.0.
 AL Compiler version 8.1.8.999

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
