### ISSUE TITLE
Better code visibility for Temporary Table

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/AL#6810]
Hey AL Gurus, 

With started using [Temporary Table](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables#:~:text=A%20temporary%20table%20is%20a,you%20use%20a%20database%20table.) within our coding practise and noticed that AL language is missing some features related to it. 

For example i have table "Additional Charges Buffer IMV" which is marked as temporary

![image](https://user-images.githubusercontent.com/16342128/138756655-79c80d69-710d-447b-9911-6474b01e5ebf.png)

When using Intellisense for SourceTable or Record, it's not clear from the list that this table is Temporary. Once you are familiar with a solution it's ok, but it's hard for a new developer.

![image](https://user-images.githubusercontent.com/16342128/138756763-bc8bd520-3ae6-4db8-9436-3ebfe2b422ea.png)

The same applies to the code formatting. It's impossible to say that SourceTable is temporary. It worsens code readability

![image](https://user-images.githubusercontent.com/16342128/138757203-6125b872-7e98-4827-9c6a-1138f326254f.png)

another example with variable definitions. 

![image](https://user-images.githubusercontent.com/16342128/138757444-d22576a3-c25c-4fe0-ae15-a6714a9976ee.png)

![image](https://user-images.githubusercontent.com/16342128/138757926-dcdfd4a7-f946-4c75-ba9f-faa617197d37.png)

As you can see from examples, there's no way to tell if that variable/sourcetable is temporary or not. 

Could you please make it improve AL language, so it would be clear for developer that this variable is temporary? 

Best Regards, 
Gintautas

**Comment by thpeder** [comment]
Hi @gintuoklis,
That seems like a wonderful idea, please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by gintuoklis** [comment]
Just made idea request:

https://experience.dynamics.com/ideas/idea/?ideaid=ecf49b17-4741-ec11-a3ee-0003ff45ceba

Where can I submit idea for your idea site? It currently lacks rich editing features. Cannot even put screenhots there. Sometimes image tells more that entire paragraph.
