### ISSUE TITLE
TableType option temporary is missing from Table Metadata table

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/AL#6811]
Dear AL gurus,

With a new addition of [Temporary Table](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables#:~:text=A%20temporary%20table%20is%20a,you%20use%20a%20database%20table.), we started to migrated our tables that are used as temp only, to use this new property.

What we are missing is ability to identify if table is marked as Temporary from metadata. 

There's table called "Table Metadata", which is supposed to hold this information & has a field for it, but its field has no such value.

![image](https://user-images.githubusercontent.com/16342128/138754491-8c44d3f3-484e-47cd-ac85-15917c57cac9.png)

If you check data on "Table Metadata" table, u will see temporary table (highlighted row) there. As you can see it TableType is blank.

![image](https://user-images.githubusercontent.com/16342128/138754835-39120f82-9cea-42b8-8126-a6e602e372a7.png)

Could you please add 'temporary' TableType to the TableMetadata table?

p.s. should this type of requests belong to this repo or microsoft/AL?

**Comment by kalberes** [comment]
Not a compiler issue. More a BC idea.

**Comment by gintuoklis** [comment]
I agree that it's not a compiler issue. But, it's not an idea either. 
If compiler teams adds new TableType, i think it should be correctly reflected in base application. Objects in 2 zillion range is out of our control, and only BC team can fix it.

**Comment by dnpb** [comment]
It seems like a platform issue, so probably should be reported via the usual channels for that.

**Comment by dtacconi** [comment]
CSS reproduced the issue and reported internally to server runtime team. This behavior is resolved starting from 19.3 onwards (ETA end of first week of January 2022).
