### ISSUE TITLE
AL: Publish Extension without building does not take into account EnvironmentName

### ISSUE THREAD

**Issue by dkatson** [microsoft/AL#6812]
Please include the following with each issue:

**1. Describe the bug**
When I try to debug Installation codeunit on the Sandbox, named other than 'Sandbox' i get an error 'The request for path /v2.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=ignore failed with code NotFound. Reason: Not Found'

**2. To Reproduce**
1. Create launch.json with the following parameters

`        {
            "name": "Attach: Microsoft cloud sandbox",
            "type": "al",
            "request": "attach",
            "environmentType": "Sandbox",
            "environmentName": "MySandbox",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            "breakOnNext": "WebServiceClient"
        },
        {
            "name": "Publish: Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "environmentType": "Sandbox",
            "environmentName": "MySandbox",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "launchBrowser": true,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10
        }
`

2. Go to Run and Debug and start "Attach: Microsoft cloud sandbox" session
3. Run: AL: Publish Extension without building

**3. Expected behavior**
Sending request to https://api.businesscentral.dynamics.com/v2.0/MySandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=ignore

**4. Actual behavior**
Sending request to https://api.businesscentral.dynamics.com/v2.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=ignore

**5. Versions:**

- AL Language: v8.1.525271
- Visual Studio Code: 1.61.2
- Business Central: 19.0.29884.30390

### Final Checklist

Please remember to do the following:

* [X ] Search the issue repository to ensure you are reporting a new issue

* [X ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ X] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
I have a fix on the way for this. As a workaround until we release a new VSIX, you can use the old `sandboxName` property in your launch.json instead.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 31908 and VS Code Extension Version 9.0.537507. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
