### ISSUE TITLE
The keyword "filter" is ignored for boolean fields in page views.  

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/AL#6814]
**1. Describe the bug**
I have created views for a list page to make filtering easier for users. 
For the first of the views I used the snippet "tview", which suggests the following code.  

```
view(ViewName)
{
   Caption = 'ViewCaption';
   Filters = where(TableFieldName = filter(FilterValue));
}
```

If you use this snippet as it is, and filter on a booelen field with either true or false, then the filter does not work correctly in the application. 

![image](https://user-images.githubusercontent.com/63199461/139087069-1d5525ef-9ecf-4d6b-ba2b-e4a770ae55ee.png)

The following view should be active.

```
 view("View filter(false)")
{
   Caption = 'View filter(false)';
   Filters = where(MyBoolean = filter(false));
   SharedLayout = true;
}
```

If you replace the "filer" keyword with "const" then the filtering works. 

![image](https://user-images.githubusercontent.com/63199461/139087552-00ef9b89-2dbf-4a76-b9a9-96e99e38d7d6.png)

```
 view("View const(false)")
{
  Caption = 'View const(false)';
  Filters = where(MyBoolean = const(false));
  SharedLayout = true;
}
```

It looks like the keyword "filter" for boolean fields does not work.

This may only be a small thing, but I wanted to report it anyway.

**2. To Reproduce**

Please copy my program code and try to execute it.

```
table 52211 MyTableREG
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; PK; Integer)
        {
            DataClassification = CustomerContent;
            AutoIncrement = true;
            Editable = false;
        }
        field(2; MyBoolean; Boolean)
        {
            DataClassification = CustomerContent;
        }
    }

    keys
    {
        key(Key1; PK)
        {
            Clustered = true;
        }
    }
}

page 52210 MyPageREG
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = MyTableREG;

    layout
    {
        area(Content)
        {
            repeater(GroupName)
            {
                field(PK; Rec.PK) { ApplicationArea = All; }
                field(MyBoolean; Rec.MyBoolean) { ApplicationArea = All; }
            }
        }
    }
    views
    {
        view("View const(false)")
        {
            Caption = 'View const(false)';
            Filters = where(MyBoolean = const(false));
            SharedLayout = true;
        }
        view("View const(true)")
        {
            Caption = 'View const(true)';
            Filters = where(MyBoolean = const(true));
            SharedLayout = true;
        }
        view("View filter(false)")
        {
            Caption = 'View filter(false)';
            Filters = where(MyBoolean = filter(false));
            SharedLayout = true;
        }
        view("View filter(true)")
        {
            Caption = 'View filter(true)';
            Filters = where(MyBoolean = filter(true));
            SharedLayout = true;
        }
    }
}
```

**3. Expected behavior**
It should be possible to create filters on Boolean fields with the keyword "const" as well as "filter" in views. 

**4. Actual behavior**
The keyword "filter" is ignored for boolean fields in page views.  

**5. Versions:**

- AL Language: v8.1.525271
- Visual Studio Code: 1.61.2
- Business Central: BC 19.0 Cloud (Sandbox)

**Comment by kalberes** [comment]
Looks like an issue in the client or server runtime . The best way to solve these kind issue to raise a Request For Hotfix
