### ISSUE TITLE
al.go command not found, installed in WSL remote

### ISSUE THREAD

**Issue by Remo** [microsoft/AL#6817]
Please include the following with each issue:

**1. Describe the bug**

When I try to use the AL extension to create a new project, it fails with the message "al.go command not found". After playing around with it, it seems to be related to WSL remote which I've got installed to.

**2. To Reproduce**

1. Install the "Remote - WSL" extension
2. Install the AL extension, here it says "install in wsl - ubuntu 20.04"
3. Hit Alt A+L

If I disable the Remote WSL extension first and then install the AL extension, everything seems to work. Even when I enable the remote WSL extension afterwards. From what I can see, the problem is only the fact that the AL extension in installed inside WSL and not locally.

**3. Expected behavior**

I'd like the command to run so that I can create a new project.

**4. Actual behavior**

The command doesn't run.

**5. Versions:**

- AL Language: v8.1.525217
- Visual Studio Code: 1.61.2
- Business Central: BC 19.0 Cloud (Sandbox)
- List of Visual Studio Code extensions that you have installed:
  -  AL Language
  - C#
  - Docker
  - Remote - Containers
  - Remote - WSL

**Comment by fanny257** [comment]
Hi Remo, did you solve the problem yet? I have the same problem after installing AL Language via vsix. I'm not able to run the command "Al:Go!" either. I received the same failure massage "al.go command not found".

**Comment by Remo** [comment]
I only have a workaround:

* Remove the WSL extension
* Install the AL extension
* Install the WSL extension again

**Comment by fanny257** [comment]
Hm... so are you able to use the command with this workaround?

**Comment by Remo** [comment]
yes, once it's installed locally, it works fine. It's just during the installation process where it's installed within WSL

**Comment by fanny257** [comment]
Thank you very much! But I cannot run the command 'al.go' even with this workaround :-(

**Comment by PooyaKharamesh** [comment]
Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
