### ISSUE TITLE
VSCode does not launch browser

### ISSUE THREAD

**Issue by fgilsc** [microsoft/AL#6819]
When I try to debug or publish my app, browser isn't lauched:

Error: Could not launch the Web browser. Please ensure that:
1. You have specified a valid browser option in your Visual Studio Code settings.
2. If you are running Microsoft Windows, Command Prompt is available and runnable by your current user.

I have already configured browser on Settings

**Comment by dnpb** [comment]
So show those settings?

**Comment by fgilsc** [comment]
"CRS.OnSaveAlFileAction": "Reorganize",
"CRS.RemovePrefixFromFilename": true,
"al.browser": "Chrome",

**Comment by NKarolak** [comment]
Usually, you don't need a specific setting, but just an entry in your [launch.json](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Launchjson):
`"launchBrowser": "true"`
Is that already set?

**Comment by fgilsc** [comment]
Yes, it's already set. Actually it works on one host but it doesn't on another one.

**Comment by NKarolak** [comment]
Does that other host have a standard browser defined? Not in VS Code, but in the operating system.

**Comment by fgilsc** [comment]
Yes it does. I've tried to reset default apps on OS, reinstalling VSCode and exentsions but it still doesn't work...

**Comment by NKarolak** [comment]
Hum, that's weird...
Did you check the second point from the error message?

> If you are running Microsoft Windows, Command Prompt is available and runnable by your current user.

**Comment by fgilsc** [comment]
It was that. I couldn't run cmd cause there were corrupt files.

I fixed it by running  `sfc /scannow` from PowerShell
