### ISSUE TITLE
Business Charts not showing up after Upgrade from BC17 to BC18 & BC19

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#6820]
Hi!

after (technically) upgrading our databases from BC17 to BC18/BC19 the Business Charts are not longer showing up.
The Event Log for the middle tier shows a _cryptic_ JavaScript error (see below).

We found a solution:
we had to reimport the Business Chart Add-In via the `Control Add-Ins` page.

Therefore my question is: do I have to extend my (PowerShell) Upgrade scripts that those Add-Ins entries are updated?
And if yes: how?
(my routines are based on [link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v18))

thanks
Ralf

```

Fehler beim Zugriff auf die Website Industry31-nightly
Unhandled error occurred on a browser or device client:
{
  "clientInfo": {
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.27 Safari/537.36 Edg/96.0.1054.8",
    "browserLanguage": "de",
    "deviceInfo": null
  },
  "pageUrl": "http://betlpznstsin02:8080/Industry31-nightly/?company=CRONUS%20AG&page=5043130&dc=0&bookmark=removed&runinframe=1",
  "message": "Exception was null or undefined. Generic error.",
  "originalError": {},
  "detailedMessage": "    at http://betlpznstsin02:8080/Industry31-nightly/js/client.js?h=91A1FA5AA04F8901DA6EE158AB3978BCE4FDE3161F8F54F7FAB3676BE8773429&_v=19.0.29884.30666:1:1951319\r\n    at window.onerror (http://betlpznstsin02:8080/Industry31-nightly/?company=CRONUS%20AG&page=5043130&dc=0&bookmark=16%3b0z3F%2fXK570yNfzZu%2bykv8g%3d%3d&runinframe=1:1:2446)\r\n",
  "location": null,
  "requireUserToSignOut": false,
  "renderRestartButton": true,
  "logToServer": true,
  "silent": true,
  "customProperties": {
    "ScriptControlAddIn.Name": "BusinessChart",
    "ScriptControlAddIn.Id": "Microsoft.Dynamics.Nav.Client.BusinessChart;PublicKeyToken=31bf3856ad364e35",
    "ScriptControlAddIn.Version": "637181530780000000",
    "PageUrl": "http://betlpznstsin02:8080/Industry31-nightly/?company=CRONUS%20AG&page=5043130&dc=0&bookmark=removed&runinframe=1",
    "Silent": true,
```

**Comment by dnpb** [comment]
It's documented on that page at
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v18#task-11-upgrade-control-add-ins
and shows how to do that via PowerShell instead of manually via GUI.

**Comment by ralf-escher** [comment]
@dnpb : Thanks for the hint, I already upgraded (successfully) my upgrade routine

**Comment by dnpb** [comment]
You're welcome, glad it helped!
