### ISSUE TITLE
NAV pre BC session stop doesnt work

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#6821]
When stopping a debug session it always fails and shows timeout error.
This used to work on BC13.
Thanks.

**Comment by dnpb** [comment]
What BC version and CU is this in? It has been a bug but fixed in recent versions and probably hotfixed, but maybe not to e.g. BC14 or your CU.

**Comment by txeriff** [comment]
Hi, 

Its BC13, on premises.

**Comment by thpeder** [comment]
Hi @txeriff,
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by txeriff** [comment]
Hi, 

I just tested and it doesnt seem to show the timeout error anymore but not sure it really stops the session.

anyway close the case.
thanks.
