### ISSUE TITLE
Excel Buffer function "Readsheetcontinuous" does not update dialog with progress

### ISSUE THREAD

**Issue by AvrilHowes** [microsoft/AL#6822]
When importing data via Excel Buffer (Table 370), the dialog window never gets updated, so there is no indication of progress, or if the process has stalled.

**Comment by dnpb** [comment]
It's doesn't seem on-topic for the language/compiler either...

**Comment by thpeder** [comment]
Hi @AvrilHowes,
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
