### ISSUE TITLE
Is there anything new about the event request process?

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#683]
It has been announced in the past that there will soon be news about registration of events. Unfortunately, I haven't heard about it since. Is it still considered that you can request events? If so, is there already any information on how the whole thing works? It will happen again and again that an event is missing at a program position. I have already mentioned some of these missing places in the issue list. It would therefore be very important to make this process known. Is there any news about this on the Directions NA? I would be very grateful for a short status update!

**Comment by StanislawStempin** [comment]
For now, please continue using this issue forum.
