### ISSUE TITLE
Missing GUID Filter on Card Page (CardPageId), 

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6830]
Please include the following with each issue:

**1. Describe the bug**
The Filter of a Guid is lost when a new record is created on the card instead of the list.

**2. To Reproduce**

See Repository: https://github.com/pri-kise/ALMissingGuidFilter

**3. Expected behavior**
All Filters should be transferred to the Card Page

**4. Actual behavior**
At the moment the Filter with the guid is missing on the card page.
Filter on the list Page:
![image](https://user-images.githubusercontent.com/56249171/141280834-c484bc45-157a-4fbc-850b-762cec6fa55c.png)

Filter on the Card Page:
![image](https://user-images.githubusercontent.com/56249171/141280995-c63a37d1-6e26-4b35-8def-d6c1e2c47489.png)

**5. Versions:**

- AL Language: v9.0.539949
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible. 

 

To open a support case, you can: 

 

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

 

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by pri-kise** [comment]
@thloke i used the latest AL Compiler and a BC 20.xx Release?
What's your problem with this issue?

**Comment by thloke** [comment]
It's not meant for this repository, this is a client issue. This repo is meant purely for the AL language.

**Comment by pri-kise** [comment]
Ah okay. I understand.
Maybe you can update your default answer template to include a shortlink to the Different support channels that should be used, since they changed a lot during the past two years.
