### ISSUE TITLE
allowDownloadingSource not working properly on DEV Extension

### ISSUE THREAD

**Issue by RED-Lin** [microsoft/AL#6831]
As title,
We publish a DEV app to the sandbox with Resource Exposure Policy -> allowDownloadingSource = false
But the app is still available on the Extension management page.

![CleanShot 2021-11-12 at 11 25 55](https://user-images.githubusercontent.com/54092477/141403924-83e7a1e1-e6bf-4bf2-9633-5bb1517d81a1.png)

![CleanShot 2021-11-12 at 15 27 14](https://user-images.githubusercontent.com/54092477/141427280-0734ddcd-26ec-4bce-98e2-d769f5a5786c.png)

**Comment by NKarolak** [comment]
This is intended behavior as per https://www.yammer.com/dynamicsnavdev/threads/1421963289387008

> When you deploy from VS Code, extensions are deployed as a DEV extension, as also now shown in the Ext Management page/screenshot in thread. In this mode ShowMyCode and also new resourceExposurePolicy settings are ignored, as it is expected you want to debug and possibly use Designer round-trip (that involves download) during development (you have source anyway). 
> 
> Once deployed as PTE or AppSource app, this should kick in.  
> 
> However, also note that protection will never be full on-prem/local container as you/admin will always have access to db and debugging platform pieces like NST. Only in cloud can this be gated.

**Comment by kalberes** [comment]
See the response above, from Natalie. By design. Dev extensions are not IP protection agnostic given that a dev extensions' primary purpose is to develop an app.
