### ISSUE TITLE
How to setup a standalone LSP server

### ISSUE THREAD

**Issue by Grueslayer** [microsoft/AL#6834]
How can we start the AL languange LSP server to use it from ouside VSCode in another environment?

**Comment by thloke** [comment]
I don't think we document/support this, and we have some extensions to the LSP that are non standard. 

Having said that, you can launch it manually. Run the exe here:

 `C:\Users\<username>\.vscode\extensions\ms-dynamics-smb.al-8.1.540594\bin\win32\Microsoft.Dynamics.Nav.EditorServices.Host.exe`

Just be aware that the operation of the LSP is always subject to change, so what works today might not work tomorrow and we can't answer detailed questions about its operation.
