### ISSUE TITLE
Obsolete state stopped working in 2.1 AL ver.

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#6835]
Hi all, 
**'ObsoleteState' is not available in runtime version '2.1'. The supported runtime versions are: '4.0' or greater.**

I´m sorry to say this used to work in 2.1 now I no longer can use it. I guess if I change my AL extension version to an older one it will work but... Not sure why this no longer works.
Thanks.

**Comment by thloke** [comment]
What object are you trying to use ObsoleteState on? 

For the majority of objects, ObsoleteState was only implemented in runtime version 4.0. Only Tables, Table Fields and Table Keys had ObsoleteState support prior to that.

**Comment by txeriff** [comment]
Hi, 

Im trying in a table as I did before. It seems like those I already wrote long work fine but if I try with a new one, it fails.

In my extension version I can´t delete fields/change keys... so obsoletestate is mandatory to have track for those fields.
Thanks.

**Comment by thloke** [comment]
I'm not sure if I follow. What do you mean by "it fails"?

I am able to create the following when targeting "RuntimeVersion":"2.1" in my app.json:

```
table 1 MyTable
{
    ObsoleteState = Removed;
    fields
    {
        field(1; N; Integer)
         {
            ObsoleteState = Removed;
         }
    }
}
```

Can you provide a sample project?

**Comment by txeriff** [comment]
Good morning, 
Sure, find below:

This one works, even in same table (I have more in other tables)
![image](https://user-images.githubusercontent.com/43034938/142167369-7e0d3955-f9c9-47d0-98ac-db414489c057.png)

this one doesnt
![image](https://user-images.githubusercontent.com/43034938/142167427-3796b5b2-a4ec-4ca8-9883-49756fdb8267.png)
![image](https://user-images.githubusercontent.com/43034938/142167451-e8a89354-b5c5-403f-8bca-52f59b5ed395.png)

![image](https://user-images.githubusercontent.com/43034938/142167494-484ed96b-d9a9-437f-a5f2-021d826fb0b0.png)
