### ISSUE TITLE
Events are not visible when published in Dev Scope

### ISSUE THREAD

**Issue by CarloAxians** [microsoft/AL#6838]
Please include the following with each issue:

**1. Describe the bug**
We have an app in AppSource and develop customizations as PTE apps for our customers.
We want our consultants and customers to preview new AppSource versions and the customizations in the PTE app.

So we ended up in creating a Sandbox, install our AppSource app with the BcContainerHelper command Publish-BcContainerApp in the Dev-scope and then install the PTE app the normal way via DevOps. It all seemed to work, but today we got an error when publishing the PTE app:

error AL0280: The event 'xyz is not found in the target

This event is a new event which we added to our AppSource app.

**2. To Reproduce**

1. Create an AppSource app and submit this.
2. Install this app in a sandbox
3. Create an PTE app, dependant of the AppSource app
4. Add an event to the AppSouce app and subscribe to this event in the PTE app
5. Install the AppSource app in Dev Scope
6. Install the PTE App in PTE-Scope, this results in the error: error AL0280: The event 'xyz is not found in the target

When we install the PTE App in Dev-scope the issue doesn't occur
**3. Expected behavior**
The event should be visible to the PTE app when installing it in PTE scope.

**4. Actual behavior**
Error _AL0280: The event 'xyz is not found in the target_ occurs

**5. Versions:**

- AL Language:  8.1.8.16322
- Visual Studio Code: 1.62.2
- Business Central: NL Business Central 19.0 (Platform 19.0.29884.32383 + Application 19.0.29894.30403)
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
I have a suspicion on what's going on (can't confirm without actually looking into the affected environment). It comes down to how we resolve dependencies when compiling in SaaS.

When you publish an application to a SaaS Sandbox, we get a list of apps that satisfy the published app's dependencies to compile against. How we do this is by querying for all extensions that are visible to that tenant and then comparing app IDs to the declared dependencies and taking the highest version of each dependency.

The key here is extensions visible to the tenant. This is composed of:

1. Global apps published on the server (could be published by other tenants)
2. Any PTE or DEV scoped apps published for that tenant

What this means is that if a Global **and** a PTE/DEV extension match a declared dependency, we take the highest version that matches. If there are both highest versions in Global and DEV scope, the behaviour is not defined (though implementation wise, I think we take globals first).

So in your case, the server likely has both the Global (appsource) version of the app published, as well as your DEV version published for your tenant.

The easiest way to resolve this is to ensure that the DEV version of your extension has a higher version number than any appsource version of your extension available. Bear in mind that if you want to switch that tenant over to the appsource version of your app, you have to unpublish any DEV scoped versions first.

If this is not the case, then the next step is to raise a support request so we can investigate the specific environment.
