### ISSUE TITLE
Support converting options to enums (case-insensitive)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6839]
Please include the following with each issue:

**1. Describe the bug**
In our process of moving away from options to enums, we sometimes have option field that have all the same option values, except for some casing differences. Changing from option to enum seems only supported if the values match 100%, including case matching. Question is to remove the casing restriction. 

References to field names / enum values seem to be case-insensitive, so it would make sense to apply the same for options to enum conversion too.

**2. To Reproduce**

I've a field 'Contact Type' with optionmembers : To, CC, B**CC**. 

![image](https://user-images.githubusercontent.com/25268332/142419744-8677957d-c1c2-4d0b-abb7-83458dcaea65.png)

I want to replace the option by the standard enum "Email Recipient Type", with values : To, Cc, B**cc**

![image](https://user-images.githubusercontent.com/25268332/142419769-f363bd0f-d183-4927-8200-837632c82659.png)

The AL compiler allows to reference an enum value using both `BCC `and `Bcc` (so case-insensitive)

![image](https://user-images.githubusercontent.com/25268332/142419819-de7369d4-55d4-4e76-a9e0-e86fb0350fa6.png)

However, the compiler sees the change from option to enum as non-supported

![image](https://user-images.githubusercontent.com/25268332/142419919-63cd3791-b6f7-47c1-aa34-4cf73a30526c.png)

**3. Expected behavior**
Please allow changing option fields to enum as long as the list of optionmembers matches the enum values, irrespective their casing.

**5. Versions:**

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.0.542050
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by qutreson** [comment]
@fvet - The rule is not case sensitive. The problem here is that the enum in the System Application defines "Bcc" with the ID 3, while it had 2 as ordinal value in your field definition. This is why you get an error from the AppSourceCop mentioning that an enum with value 2 is missing now.

The enum in the system app looks like this:
```
enum 8901 "Email Recipient Type"
{
    value(0; "To") { }
    value(1; "Cc") { }
    value(3; "Bcc") {  }
}
```

From the AppSourceCop's point of view, this is then as expected
