### ISSUE TITLE
Increase primary key field lenght not allowed for Appsource

### ISSUE THREAD

**Issue by JalmarazMartn** [microsoft/AL#6843]
- AL Extension Version: All

- Server Version: All.

If I Increase the field length of a primary key when I publish in Appsource in first validation I get this error message:

"Error AS0080: Field 'Item No.' has changed from 'Code[10]' to 'Code[20]' in table or table extension 'TIP SILICIE Item Pack. Type'. Decreasing the length of a field is not allowed. For fields used in the primary key, the field length cannot change.."

Notice that the text says "Decrease" but we are Increasing the length.

Already reported in ##4933. But nobody has answered it since 2019. No problem if you leave only one issue, and delete the mine one, but please answer us or tell us where we must post this issue, for getting some answers.

Thank in advance.

**Comment by dannoe** [comment]
Even microsoft had to introduce a new table to increase the primary key fields of cross-references (now they are called item references). So I don't think you can do that as customer.

**Comment by JalmarazMartn** [comment]
> Even microsoft had to introduce a new table to increase the primary key fields of cross-references (now they are called item references). So I don't think you can do that as customer.

Thank you @dannoe .

You are right. I thought about that and closed the issue before your answer. The problem was the lack of answer in the previous issue #4933 .

Best regards, thank you again for your fast answer.
