### ISSUE TITLE
AS0090 (Renaming objects) also applies to reportextension and enumextension objects while the object names cannot be referenced

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#6846]
Please include the following with each issue:

**1. Describe the bug**
Rule AS0090 "Objects that can be referenced and which have been published must not be renamed." also applies to reportextension and enumextension object names, even though these names cannot be referenced from AL code. Note that tableextension and pageextension object names are already excluded from this rule as these cannot be referenced either. I think that all extension objects (including reportextension and enumextension) can be excluded from rule AS0090.

Originally posed as a community question on the Dynamics 365 Business Central Development Yammer:
> **Rob van Bekkum – Monday at 11:25 AM**
> Why does rule AS0090 also apply to extension-objects?
> 
> More of a question to get a better understanding. We have rule AS0090 (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0090), which makes sense.
> 
> I was wondering why it also applies to enumextension, pageextension, reportextension and tableextension object names though.
> 
> These names cannot be referenced from AL code, can they?

Reply:
> **Quentin Tresontani – 59 minutes ago**
> Hi Rob van Bekkum, this is a valid point. PageExtensions and TableExtensions are already ignored by this rule, but it seems that report extensions and enum extensions are validated while this isn't needed. Can you log this as an issue on Github?  Issues · microsoft/AL (github.com) 

**2. To Reproduce**
1. Create a first version of an app that has an enumextension object with name X
2. Create a new version of the same app and try to change the name of that same enumextension object from name X to name Y
3. An error is raised by AS0090 for the enumextension object reporting that changing the name is not allowed as the name might be referenced by an extension.

**3. Expected behavior**
A diagnostic for rule AS0090 is not raised for reportextension or enumextension objects.

**4. Actual behavior**
A diagnostic for rule AS0090 is raised for reportextension or enumextension objects.

**5. Versions:**

- AL Language: 8.2.545335
- Visual Studio Code: 1.62.3
- Business Central: N.A.
- List of Visual Studio Code extensions that you have installed: N.A.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32975 and VS Code Extension Version 9.0.548816. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
