### ISSUE TITLE
Problem with propagateDependencies in application tree

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/AL#6847]
Please include the following with each issue:

**1. Describe the bug**
Compilator raise error that some object does not exist whe I use more leveled applications. I am using "propagateDependencies" = true in all my applications. Problem is that it work only from first app mentioned in dependencies. 
Example:
- Application1: Depends on CZ Localization
- Application2: Depends on Application1 - Here I can compile without problems objects from Czech Localization
- Application3: Depends on Application2 - Compilator raise error whena I use objects from Czech Localization. I do not get objects from Localization. When I add Application1 as dependency to my Application3. Compilator is without problem and I can use Czech Localization objects.

**2. To Reproduce**

1. Create first application that depends on CZ localization (or you can use another application). Use "propagateDependencies" = true in app.json.
2. Create second application that depends on the first application. Use "propagateDependencies" = true in app.json.
3. Try use objects from CZ localization or object from your app. Compilator shoudl work.
4. Create third application that depends on the second application. Use "propagateDependencies" = true in app.json.
5. Try use objects from CZ localization or object from your app. Compilator raise error.

**3. Expected behavior**
When I use "propagateDependencies" = true in all my applications it should propagate all dependencies from all applications. From my example: I would like set and dependency only Application3 and other applications and their dependecies should be provided automatically.

**4. Actual behavior**
"propagateDependencies" = true  works only for one level. Application2 depends on Application1 and can use objects from Application0 (CZ localization). That's it.

**5. Versions:**
- AL Language: 8.2.545335
- Visual Studio Code: 1.62.3 
- Business Central: 19.0.29894.30693

**Comment by qutreson** [comment]
This is by-design, we only propagate the first level dependencies. Our documentation does not mention it, but we will update it to mention this limitation.

We recommend that you post this on our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
