### ISSUE TITLE
JsonObject.SelectToken() sets Last Known Error when this is not necessary

### ISSUE THREAD

**Issue by LNitzsche** [microsoft/AL#6850]
**1. Describe the bug**

I want to call selectToken() to estimate if a given Json Path is valid in the JsonObject.
To avoid a runtime exception, the boolean return value is evaluated.
In this case I would expect that no error is logged in "Last Error" even if false is returned:

The behaviour should be like performing Record.get() with a PK that does not exist.
In this case no exception will be generated if the return value of get() is evaluated by the program
and also Last Error is not affected.

**2. To Reproduce**
Call SelectToken with a correct formatted JPath when this path does not exist.

AL
``
result := jobject.SelectToken('$.someNotExistingPath', jtoken);

``
See also attached minimal project.
[SelectToken.zip](https://github.com/microsoft/AL/files/7609401/SelectToken.zip)

**3. Expected behavior**
Expected behaviour is not to generate a runtime error (that works) but not setting the Last Error Code because the failure is handled by the program.
Otherwise users and admins may be confused by irrelevant messages maybe overwriting more urgent messages.

**4. Actual behavior**
No runtime error is generated (that is ok) but the Last Error Code is set to "InvalidJsonPathSelection".

**5. Versions:**

- AL Language: 8.1.540594
- Visual Studio Code: 1.54.3
- Business Central:  v19 
 (but is related to all versions since v14)

**Comment by LNitzsche** [comment]
I have posted a similar problem concerning Get() on dictionaries here: #5935

**Comment by kalberes** [comment]
Both are runtime issues. Actually runtime enhancements. Thanks for reporting it, though but if you want faster resolution then:
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
