### ISSUE TITLE
FilterGroup(-1) does not work when applied to a page

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6855]
**1. Describe the bug**
FilterGroup(-1) does not apply to pages.

**2. To Reproduce**
Add this code to the Customer List page:

    trigger OnOpenPage()
    begin
        Rec.FilterGroup(-1);
        Rec.SetRange("Country/Region Code", 'DE');
        Rec.SetRange(Name, 'Relecloud');
    end;

**3. Expected behavior**
Customers that have 'DE' as their "Country/Region Code", or 'Relecloud' as their name, are shown when you open the page.

**4. Actual behavior**
No filters whatsoever are applied when the page is opened.

**5. Versions:**

- AL Language: v8.2.550913
- Business Central: ES Business Central 19.1 (Platform 19.0.31889.32155 + Application 19.1.31886.32186)

**Comment by dnpb** [comment]
This is known, and I thought it was documented, but I can't find that now.

I imagine it's because FilterGroup -1 is used for the cross-column Search box, so it would be confusing/ambiguous to also allow setting it in code.

**Comment by dnpb** [comment]
It may be more a bug for the documentation. There is already this over there:
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1527

**Comment by salgiza** [comment]
I actually thought that it might be a known limitation, but I was surprised that lack of support for flowfields is clearly specified in the docs, but there is no mention on pages.

Is there any particular reason for this, though, if that is indeed the case?

If not possible/implemented, could we at least get an error instead of nothing happening? Obviously it would be better for us if it worked, but an error at least would be unambiguous about the reason, and avoid developers expending time wondering whether they did something wrong 😅

**Comment by dnpb** [comment]
> I was surprised that lack of support for flowfields is clearly specified in the docs, but there is no mention on pages.

It wasn't until I raised multiple issues, at least one of which was on PartnerSource ;-)

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

The reason for not accepting is down to capacity, and that this can also be addressed through better docs. I agree that it would be better to have an error raised for this (likely a codecop rule), but it's unlikely that we'll have the capacity to invest in that now.
