### ISSUE TITLE
AL Table Proxy Generator throws error CDS1028

### ISSUE THREAD

**Issue by ik3ras** [microsoft/AL#6856]
**1. Describe the bug**
When running AL Table Proxy Generator error is thrown on specific tables.

**2. To Reproduce**
It may be environment issue, but since we only work with BC it is hard for us to figure reason behind it or blame it on CRM guys.

PS C:\Users\ikeras\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\bin> .\altpgen.exe -Project:"C:\_Work\Dataverse" -PackageCachePath:"C:\_Work\Dataverse\" -ServiceURI:"https://brc-bc-dev.crm4.dynamics.com" -Entities:"invoice" -BaseId:50000 -tabletype:CDS

**3. Expected behavior**
AL Table created

**4. Actual behavior**
Error is thrown. Table is not created

**5. Versions:**

- AL Language: 8.2.545335

**Error stack:**

PS C:\Users\ikeras\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\bin> .\altpgen.exe -Project:"C:\_Work\Dataverse" -PackageCachePath:"C:\_Work\Dataverse\" -ServiceURI:"https://brc-bc-dev.crm4.dynamics.com" -Entities:"invoice" -BaseId:50000 -tabletype:CDS
Microsoft (R) AL Table Proxy Generator version 8.2.8.21063
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://brc-bc-dev.crm4.dynamics.com
Authenticated.
Retrieving entity metadata.
warning CDS0005: 'contact' and 'account' entities are required for Customer type. Skipping Invoice / Credit.CustomerId.
warning CDS0006: TimeZoneIndependent DateTimeBehavior is not supported by BC Runtime. Skipping Invoice / Credit.blc_InvoiceDueDate.
warning CDS0006: TimeZoneIndependent DateTimeBehavior is not supported by BC Runtime. Skipping Invoice / Credit.blc_COMMS2WeekReminderDate.
warning CDS0006: TimeZoneIndependent DateTimeBehavior is not supported by BC Runtime. Skipping Invoice / Credit.blc_COMMS45DaysOverdueDate.
warning CDS0006: TimeZoneIndependent DateTimeBehavior is not supported by BC Runtime. Skipping Invoice / Credit.blc_COMMS75DaysOverdueDate.
warning CDS0003: No table found for entity 'systemuser'. Unable to create TableRelation for 'Invoice / Credit.CreatedBy'.
warning CDS0003: No table found for entity 'systemuser'. Unable to create TableRelation for 'Invoice / Credit.ModifiedBy'.
warning CDS0003: No table found for entity 'systemuser'. Unable to create TableRelation for 'Invoice / Credit.CreatedOnBehalfBy'.
warning CDS0003: No table found for entity 'businessunit'. Unable to create TableRelation for 'Invoice / Credit.OwningBusinessUnit'.
warning CDS0003: No table found for entity 'team'. Unable to create TableRelation for 'Invoice / Credit.OwningTeam'.
warning CDS0003: No table found for entity 'transactioncurrency'. Unable to create TableRelation for 'Invoice / Credit.TransactionCurrencyId'.
warning CDS0003: No table found for entity 'opportunity'. Unable to create TableRelation for 'Invoice / Credit.OpportunityId'.
warning CDS0003: No table found for entity 'pricelevel'. Unable to create TableRelation for 'Invoice / Credit.PriceLevelId'.
warning CDS0003: No table found for entity 'salesorder'. Unable to create TableRelation for 'Invoice / Credit.SalesOrderId'.
warning CDS0003: No table found for entity 'sla'. Unable to create TableRelation for 'Invoice / Credit.SLAId'.
warning CDS0003: No table found for entity 'sla'. Unable to create TableRelation for 'Invoice / Credit.SLAInvokedId'.
warning CDS0003: No table found for entity 'account'. Unable to create TableRelation for 'Invoice / Credit.AccountId'.
warning CDS0003: No table found for entity 'contact'. Unable to create TableRelation for 'Invoice / Credit.ContactId'.
warning CDS0003: No table found for entity 'blc_donation'. Unable to create TableRelation for 'Invoice / Credit.blc_Donation'.
warning CDS0003: No table found for entity 'blc_eventbooking'. Unable to create TableRelation for 'Invoice / Credit.blc_EventBooking'.
warning CDS0003: No table found for entity 'blc_exportbatch'. Unable to create TableRelation for 'Invoice / Credit.blc_ExportBatchid'.
warning CDS0003: No table found for entity 'blc_grouporder'. Unable to create TableRelation for 'Invoice / Credit.blc_GroupOrder'.
warning CDS0003: No table found for entity 'blc_membership'. Unable to create TableRelation for 'Invoice / Credit.blc_Membership'.
warning CDS0003: No table found for entity 'contact'. Unable to create TableRelation for 'Invoice / Credit.blcip_BillToContact'.
warning CDS0003: No table found for entity 'bcbi_company'. Unable to create TableRelation for 'Invoice / Credit.bcbi_companyid'.
Writing output...
error CDS1028:
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding)
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 77
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorCommandLineTool.Run(String clientDirectory, String baseDirectory, String[] args)

**Comment by thloke** [comment]
Hi, this is out of scope of this repository. The altpgen tool is maintained by a different team, so the best way to get their attention is to raise a support case or collaborate request. 

As a reminder, this repo is only for issues with the AL compiler and language itself.
