### ISSUE TITLE
Missing error on compile upgrade codeunits being run by code

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6857]
**1. Describe the bug**
The compiler does not throw an error if Run is performed on an upgrade codeunit.
Only on publish, we get:

> Could not upgrade the extension 'x' by 'x' for tenant 'default' and company 'x' due to the following error: 'Upgrade codeunit 'x' cannot be invoked outside the schema synchronization process.

**2. To Reproduce**

1. Declare an upgrade codeunit with OnRun trigger

``` AL
codeunit 50000 "My Upgrade Codeunit"
{
    Access = Internal;
    Subtype = Upgrade;

    trigger OnRun()
    begin       
    end;
}
```

2. Run this codeunit from another upgrade codeunit (that will be run during publish): (*)
``` AL
MyUpgradeCodeunit.Run();
```

Build a package: no error will occur.
Publish the extension and run the upgrade: error as stated above.

(*) Originally, codeunit 50000 was designed as a "normal" codeunit. But it turned out once declared tables are on ObsoleteState = Removed, the codeunit would not compile anymore.

**3. Expected behavior**
The compiler should detect the run on an upgrade codeunit and throw an error.

**4. Actual behavior**
No error is thrown, but later on publish.

**5. Versions:**

- AL Language: 8.2.550913
- Visual Studio Code: 1.62.3

**Comment by thloke** [comment]
I wonder if the better fix here is to allow calling `Run` on upgrade codeunits, considering that the upgrade-specific steps have their own triggers. Either way I agree, we should either block this on compile, or we should allow this in the runtime.
