### ISSUE TITLE
$odata.nextlink is not returned in Business Central odata queries if $top is used

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#6858]
**1. Describe the bug**
I'm publishing a query using OData, and paging the results does not work if $top is used to specify the number of records by page. If there are more records than the value of the ODataServicesMaxPageSize server parameter, though, it does work.

**2. To Reproduce**
Just access any query or page published in Business Central, using its ODataV4 url, and specify $top=2 (2 being a number lower than the total number of records).

Example:

     https://{servername}/{instance}/ODataV4/Company('{company}')/salesDocuments?$top=2&tenant=default

**3. Expected behavior**

The returned json object should include an @odata.nextLink property, as it is returned when calling an OData URL that returns more than the ODataServicesMaxPageSize server value:
![CleanShot 2021-12-02 at 13 50 58](https://user-images.githubusercontent.com/6630306/144425443-79c7a9a5-8e44-4493-bb87-2bbb64d1a6ab.png)

**4. Actual behavior**

The returned json object does not include an @odata.nextLink value, thus indicating that no more results are available:
![CleanShot 2021-12-02 at 13 52 30](https://user-images.githubusercontent.com/6630306/144425687-eff2f824-d897-4486-972d-0963b52268c7.png)

**5. Versions:**

- Business Central: ES Business Central 19.0 (Platform 19.0.29884.31443 + Application 19.0.29894.31532)

**Comment by thloke** [comment]
Hi, this is out of scope of this repository. Web service endpoints are handled by a different team. To get this issue to them, please raise a support request or a collaborate request.

This repository is only meant for issues with the AL language compiler and VSCode extension.
