### ISSUE TITLE
Entity buffer tables migration

### ISSUE THREAD

**Issue by MakGM-FORTO** [microsoft/AL#6860]
Hello,
We are running the migration from On-Premise to Cloud and noticed that "Sales Order Entity Buffer" and "Sales Cr. Memo Entity Buffer" have ReplicateData = false.
Since they are not migrated we are not able to retrieve migrated records from API using the GET request.
Am I doing something wrong? Please elaborate on how this should be handled
Version: DE Business Central 19.1 (Platform 19.0.31889.33296 + Application 19.1.31886.32222)
API request: GET https://api.businesscentral.dynamics.com/v2.0/{tenantId}/{environtment}/api/v2.0/companies({companyId})/salesOrders
ER: all migrated records should be available from API
AR: request returns empty value
p.s. after modify is triggered it becomes available in API

**Comment by thloke** [comment]
Hi, this is out of scope of this repository. Cloud migration is handled by a different team. To get this issue to them, please raise a support request or a collaborate request.

This repository is only meant for issues with the AL language compiler and VSCode extension.
