### ISSUE TITLE
[still] no compile/runtime warning if SetLoadFields()/AddLoadFields() are passed fields of wrong type

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6862]
https://github.com/microsoft/AL/issues/6480 was closed. But there is still no warning in 19.1. I don't have access to an Insider build or time to figure out how to get one. But @PhDuck said this should get resolved. So reopening.

```al
pageextension 50100 "Customer List" extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {
            action(Test)
            {
                ApplicationArea = All;
                Caption = 'Test';
                Image = TestFile;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;
                ToolTip = 'Do a test.';

                trigger OnAction()
                var
                    Customer: Record Customer;
                begin
                    Customer.SetLoadFields("Sales (LCY)", "Balance (LCY)");
                    Customer.Get(Rec."No.");
                    Customer.TestField("Sales (LCY)");
                    Customer.TestField("Balance (LCY)");
                end;
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/63455896/144819778-aa72d629-8a92-4929-a396-0be20e01a01c.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.2.550913
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
Reading the old issue, I there was some discussion on implementing a warning, but no actual action taken to implement the warning. I'll accept it so it's tracked internally so we don't lose it again. 

To summarize the previous discussion, the intent is to add a new warning in CodeCop to detect usages of non-normal field types in [Set/Add]LoadFields.

**Comment by dnpb** [comment]
Great, thank you!

**Comment by thloke** [comment]
Unfortunately the team that owns this feature has no plans on implementing the warning, as they have other more high priority bugs to fix. In this case, closing this issue as a "won't fix".
