### ISSUE TITLE
Table "Gen. Journal Line" - wrong parameter passed into OnAfterCopyGenJnlLineFromCustLedgEntry() event

### ISSUE THREAD

**Issue by VMasalkov** [microsoft/AL#6863]
In BC19, table "Gen. Journal Line" procedure CopyCustLedgEntry() is called with variable CustLedgerEntry as parameter, but the call to OnAfterCopyGenJnlLineFromCustLedgEntry() event takes global variable CustLedgEntry instead of the one passed into procedure. That makes event subscription unusable for any kind of integration enhancements.

**Comment by dnpb** [comment]
wrong repo; you want https://github.com/microsoft/AlAppExtensions/issues
