### ISSUE TITLE
Option FlowFilter fields with blank options now set a filter on the blank option at DrillDown. (Did not happen in BC18 or earlier.)

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/AL#6865]
**1. Describe the bug**
If an option field has blank values, f.ex. ",Opt1,,Opt3" (not with spaces " ,Opt1..."), and you have a TableRelation in another table with a FlowFilter (with the same options), then at DrillDown time BC19 puts a filter on the view based on the empty option value. (There is no value in the FlowFilter.)
(In BC18 and earlier this resulted in no filtering on the field in the drilldown.)

**2. To Reproduce**

Create the following two objects (table and page), and run the page. Make it editable, and then drill down into the field on the page. See that the Page Filters for the page (Ctrl+Alt+F1) have a filter for the FlowFilter that was never set, so no entries are shown; in BC19. (In BC18 there are no Page Filters, so all entries are visible in the page.)

``` AL
**Object 1 of 2, Table:**
table 50000 "Test Option FlowFilter"
{
    DataClassification = CustomerContent;
    TableType = Temporary;

    fields
    {
        field(1; Code; Code[10])
        {
            DataClassification = CustomerContent;

        }
        field(2; JQE_ID; Integer)
        {
            DataClassification = CustomerContent;
            TableRelation = "Job Queue Entry" where("Object Type to Run" = field("Object Type to Run FlowFilter"));
        }
        field(7; "Object Type to Run FlowFilter"; Option)
        {
            Caption = 'Object Type to Run FlowFilter';
            FieldClass = FlowFilter;
            OptionCaption = ',,,Report,,Codeunit';
            OptionMembers = ,,,"Report",,"Codeunit";
        }
    }

    keys
    {
        key(Key1; Code)
        {
            Clustered = true;
        }
    }
}

**Object 2 of 2, Page:**
page 50000 "Test Option FlowFilter"
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = "Test Option FlowFilter";
    SourceTableTemporary = true;
    Caption = 'Test Option FlowFilter';

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(JQE_ID; Rec.JQE_ID)
                {
                    Caption = 'Job Queue Entry ID';
                    ApplicationArea = All;
                    ToolTip = 'This is a tooltip for the flowfilter test.';
                }
            }
        }
    }

    trigger OnOpenPage()
    begin
        if not Rec.Get() then
            Rec.Insert();
    end;
}
```
**End of objects.**

**3. Expected behavior**
The list page that is opened at DrillDown does not have a Page Filter set, so you can see all available entries.

Picture from BC18 where I do not have the problem:
![image](https://user-images.githubusercontent.com/57808351/145232598-83ed0f31-4756-451e-b084-ee0fbdb3ef32.png)

**4. Actual behavior**
The list page that is opened at DrillDown HAS a Page Filter set, so you CANNOT see ANY available entries.

Picture of the problem from BC19:
![image](https://user-images.githubusercontent.com/57808351/145232496-16575118-4543-4c99-9913-d705d5427dd4.png)

**5. Versions:**

VS-Code:
![image](https://user-images.githubusercontent.com/57808351/145232765-ef00c8c4-79f1-4e84-8235-f5e9701b989b.png)

AL-Packages:
![image](https://user-images.githubusercontent.com/57808351/145232879-21c2aecc-cb0b-4aca-9328-3cadf3c296bb.png)

**Comment by KristjanGaukur** [comment]
I have investigated this further with the aim to see if I could get rid of the problem by changing my option fields to enum fields.
Result, enums have the same problems when an enum value has a "" as a name.
I made a video to showcase that:

https://youtu.be/EROfyDa_pIM

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the web client behaviour.
