### ISSUE TITLE
Bug in altpgen.exe

### ISSUE THREAD

**Issue by Bertverbeek4PS** [microsoft/AL#6866]
The bug in isseu https://github.com/microsoft/AL/issues/6853#issuecomment-989769110 is solved.
I have installed version 8.2.552672 and you get a login reqeust. If you enter the credentials you get the following error:
 
PS C:\WINDOWS\system32> C:\Users\bverbeek\.vscode\extensions\ms-dynamics-smb.al-8.2.552672\bin\altpgen.exe -project:"C:\Users\bverbeek\Documents\GitHub\DataVerse" -packagecachepath:"C:\Users\bverbeek\Documents\GitHub\DataVerse\.alpackages" -serviceuri:"https://org13abfcc3.crm4.dynamics.com" -entities:new_employee -baseid:5200 -tabletype:CDS
Microsoft (R) AL Table Proxy Generator version 8.2.8.28400
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://org13abfcc3.crm4.dynamics.com
error CDS0001: Error connecting to Dataverse. 
Microsoft.Dynamics.Nav.Xrm.Common.XrmException: Kan bestand of assembly Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het 
opgegeven bestand niet vinden.

Server stack trace: 

Exception rethrown at [0]: 
   bij System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   bij System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   bij Microsoft.Dynamics.Nav.Xrm.Common.IXrmService.Connect(String serviceUri, String token)
   bij Microsoft.Dynamics.Nav.TableProxyGenerator.XrmMetadataService.CreateXmlMetadataService(String serviceUri, String token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\Xrm\XrmMetadataService.cs:regel 67
   bij Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.CreateXrmMetadataService(IList`1 diagnostics, String token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:regel 84
    

PS C:\WINDOWS\system32>

**Comment by MajorBarf** [comment]
Need to fix the title from "altpen.exe" to "altpgen.exe" otherwise people won't find this one when they go searching.

Comments from another issue that might be relevant:
https://github.com/microsoft/AL/issues/6853#issuecomment-989769110

**Comment by ProdwareJuanan** [comment]
Hi, same error here with same versión of compiler:

"error CDS0001: Error connecting to Dataverse. 
Microsoft.Dynamics.Nav.Xrm.Common.XrmException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=5.2.7.0, Culture=neutral, Public
KeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Server stack trace: 


Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Dynamics.Nav.Xrm.Common.IXrmService.Connect(String serviceUri, String token)
   at Microsoft.Dynamics.Nav.TableProxyGenerator.XrmMetadataService.CreateXmlMetadataService(String serviceUri, String token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.N
av.TableProxyGenerator\Xrm\XrmMetadataService.cs:line 67
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.CreateXrmMetadataService(IList`1 diagnostics, String token) in D:\a\1\s\source\Prod\Microsoft.Dyn
amics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 84"

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 33657 and VS Code Extension Version 4.0.144660. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
