### ISSUE TITLE
Could not download reference symbols

### ISSUE THREAD

**Issue by JohnEpsco** [Microsoft/AL#687]
I seem to be having a similar issue to some other people in downloading the ’reference symbols’.  Working with sandbox D365 Financials in the cloud, I have tried the suggestion in other posts such as changing the ‘locale’ to ‘W1’ from ‘US’ but this hasn’t worked.  Another recent suggestion is to install the latest version of AL extension – AL-0.9.12794 in place of my current install 0.7.12807, but I don’t know where from?
I’d appreciate any assistance.   

**App.json**
{
  "id": "bfd3701b-fea4-4f7c-bec7-9eab82653c5f",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "10.0.0.0",
  "application": {
    "version": "10.0.0.0",
    "locale": "US"
  }
}
**Output**
[2017-09-15 12:17:16.07] Using reference symbols cache path: c:\Users\xxxxx\Documents\AL\ALProject1\packages
[2017-09-15 12:17:16.08] Authenticating...
[2017-09-15 12:17:18.19] Downloading from https://api.financials.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0 ... Error (NotFound)
[2017-09-15 12:17:18.19] Could not download reference symbols

**launch.json**
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "publish",
            "name": "Cloud",
            "startupObjectId": 22
        }
    ]
}

Thank you

**Comment by StanislawStempin** [comment]
If you're working against the cloud sandbox you should in general use the VSIX from VS Code Marketplace:
https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

In which country is your cloud sandbox? It will only have symbols corresponding to that one country.

**Comment by JohnEpsco** [comment]
Thanks for your reply.  Yes, the link is where I downloaded my installed AL Extensions.
I'm not sure how to ascertain which country my sandbox is in (hosted?)?  I just followed the 'Try it out' instructions in the Microsoft page for developing Financials?  I'm in Cyprus if that helps?

**Comment by StanislawStempin** [comment]
As some point in the process there was a dropdown with country selection:  US, UK, CA. Do you remember which one you picked?

**Comment by JohnEpsco** [comment]
I think it was UK.

**Comment by StanislawStempin** [comment]
Ok, please try to use locale : "UK" in the app.json in that case

**Comment by JohnEpsco** [comment]
Ok.....well that worked!  Thanks so much!
