### ISSUE TITLE
BC19 with target Cloud enters Scope('OnPrem') Function

### ISSUE THREAD

**Issue by VictorMilveden** [microsoft/AL#6870]
**1. Describe the bug**
When calling Function ```DocumentSendingProfile.Send(ReportUsage, RecordVariant, DocumentNo, CustomerNo, DocName, CustomerFieldNo, DocumentFieldNo);``` with BC 19 Cloud app the code enters Function: ```SendToDiskForCust``` on Table: ```Report Selection``` which is aScope('OnPrem') function.

My app.json target is Cloud:
![image](https://user-images.githubusercontent.com/73481282/145634425-468755af-69fb-406a-a6da-14bb9fcd371b.png)

**2. To Reproduce**

1. Go to 'app.json' and include property ```"target": "Cloud"```
2. Add a breakpoint on Table: ```Report Selection``` Function: ```SendToDiskForCust```
3. Call function ```DocumentSendingProfile.Send(ReportUsage, RecordVariant, DocumentNo, CustomerNo, DocName, CustomerFieldNo, DocumentFieldNo);```
4. The breakpoint on Table: ```Report Selection``` Function: ```SendToDiskForCust``` should be triggered, which is a Scope('OnPrem') function.

**3. Expected behavior**
I would expect a compile error like this one:
![image](https://user-images.githubusercontent.com/73481282/145633148-ae6c9e93-e5b2-4158-a4be-100c62ddac44.png)

**4. Actual behavior**
The actual behavior runs function ``DocumentSendingProfile.Send();``` and enters a OnPrem Function:
![image](https://user-images.githubusercontent.com/73481282/145633735-1190041a-aeb0-4111-9f56-41d957a6c913.png)

**5. Versions:**

- AL Language: v8.2.552672
- Visual Studio Code: 1.63
- Business Central: BC19 Cloud

**Comment by dnpb** [comment]
Why do you think a SaaS app cannot call an OnPrem function behind-the-scenes? It is on Microsoft's premise. OnPrem only means cloud developers can't call those functions directly, not that Microsoft's own apps cannot.

**Comment by thloke** [comment]
@dnpb is correct - the OnPrem restriction is only for apps that target Cloud. Microsoft 1st party apps themselves target OnPrem, and are able to call into OnPrem functions themselves.
