### ISSUE TITLE
CodeAnalyzer - rule "AA0072" ignores triggers and event subscriber

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#6871]
the rule "AA0072" ignores all triggers and EventSubscribers.

AL Compiler version 8.2.8.28400

**Comment by dnpb** [comment]
It should, because end developers should not be warned about parameter names they cannot change...

**Comment by sschuh** [comment]
It's about my own triggers and subscribers.

Subscriber parameters from the standard, i agree, but used variables in this subscribers should be checked.

**Comment by dnpb** [comment]
I am not sure but I would think those should be checked on the publishing side, but not at subscribers. It's the publisher's problem, isn't it?

**Comment by sschuh** [comment]
Then the whole rule should be disabled.

**Comment by dnpb** [comment]
Why? A publisher should be warned if they pass variables with non-recommended names (and care about MS's recommendations). But subscribers should not be spammed with warnings saying the publisher didn't obey the rule. That's not their responsibility to fix, and making them put `#pragma`s around their subscriber's argument list is pointless busy-work.

**Comment by sschuh** [comment]
When i write my own custom codeunit with several own procedures with variables the info about variable naming appears. When i write my own page with an action that has an OnAction trigger with variables the info does not appear.

**Comment by dnpb** [comment]
Ah, sorry, I see your point now and agree - you mean local variables, not parameters. Then yes, since they're declared by you, they should be warned for. Perhaps MS's fix for parameter names was too wide-ranging and affected _all_ variables in triggers and subscribers...

**Comment by sschuh** [comment]
Sorry, maybe my fault, i'm a bit info hurry..next time i will give you a better description. :-)

**Comment by dnpb** [comment]
What type(s) of trigger are you seeing it not working in? It works for me in e.g. `OnOpenPage()`. But indeed it does not work for local variables in an `EventSubscriber`.
![image](https://user-images.githubusercontent.com/63455896/145811409-8fe479c1-4815-46f1-81ef-98ad0cea2c1a.png)

**Comment by sschuh** [comment]
for pages: "OnAction" , "OnDrillDown" , "OnLookup", " OnValidate" with local variables.

**Comment by sschuh** [comment]
EventSubscribers - local variables

**Comment by sschuh** [comment]
Report - OnAfterGetRecord, OnPreDataItem

**Comment by sschuh** [comment]
Tables - OnValidate, OnLookup with local variables

**Comment by sschuh** [comment]
Tableextension - the same as tables

**Comment by sschuh** [comment]
Pageextensions - the same as pages

**Comment by dnpb** [comment]
Just to (only occasionally!) be 'that guy' who posts this: This is still an issue, e.g. I just had to rename of my own local some `Codeunit` variables in `OnAction` triggers, to satisfy AA0072, because the analyser hadn't told me about it, and I just happened to notice the names were wrong (outdated). Is there any idea when this can be worked on / resolved? Thanks!

**Comment by TKapitan** [comment]
Hi guys, any updates about this issue?

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
