### ISSUE TITLE
🛑🛑🛑Please contact customer support🛑🛑🛑

### ISSUE THREAD

**Issue by JetinderSaini** [microsoft/AL#6873]
Hi All, I am new in AL programming, I am working in ISV product, there is a lots of customization on job card. System working fine. But 
I am facing performance issue while opening job card, it will take too much time (with jobs that have 100+ job planning line) while opening the job card.

Please let me suggest how to improve my job card performance.

**Comment by dnpb** [comment]
You should ask on a forum or the DynamicsNAVDev Yammer. This is not on-topic for this repo, which deals only with issues in the core AL language and compiler. Didn't the template you selected, with its title, indicate that? ;-)

**Comment by qutreson** [comment]
Closing this issue as it is out of scope for this repository
