### ISSUE TITLE
Send Remittance Advice Error  

### ISSUE THREAD

**Issue by RhipeDynamics** [microsoft/AL#6875]
Hi Support, 

When sending Vendor Remittance Advice we are getting an error "A call to MailKit.Net.Smtp.SmtpClient.Send failed with this message: No recipients have been specified."

We did a bit of digging and found that it is searching for customers and trying to use the customer's email address rather than vendor's. If the Customer with the same number is not found, it will print the above error, else it might even send the vendor's remittance to the customer.

This is happening in version 19.1.3.xxxxx

Please review

Thanks,
Ilija, Moiz.

**Comment by thloke** [comment]
Hi, this is out of scope of this repository. This repo is only for issues relating to the AL language and VSCode extension. In this case, you should open a support case.
