### ISSUE TITLE
BUG Print Customer Statement from home page

### ISSUE THREAD

**Issue by medaminemah** [microsoft/AL#6878]
there are bug when i try to print the report "Customer Statement" from main menu
Menu > Finance > Receivables > Reports > Customer Statement
Click it and come back to the home page
i try it on V 18 and 19.1 on-prem and cloud

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it. This repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
