### ISSUE TITLE
September Update:  Not able to compile in Dev Client

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#688]
Hi,

I am not able to compile in the dev client and getting the below error.
![image](https://user-images.githubusercontent.com/26792519/30479297-446c21d2-9a32-11e7-85e5-72840e65689d.png)

Can you please suggest us.

Thanks & Regards
Varun Reddy

**Comment by kaspermoerch** [comment]
Have you tried running the development environment as administrator?

**Comment by bachii1010** [comment]
HI,

Eventhough i run with administrator the error is still comming

**Comment by MrDavid5465** [comment]
I found that I had to run both scripts in C:\DEMO after each startup

**Comment by bachii1010** [comment]
Hi David,

Can you name the scripts that needs to be run each time

**Comment by MrDavid5465** [comment]
SetupDesktop and SetupNavContainer

**Comment by bachii1010** [comment]
Hi David,

The issue still exists.

can anyone suggest me how to solve this.

**Comment by freddydk** [comment]
The NAV Developer Preview was not designed for classic development., C/SIDE is added in order to inspect and find information in the base app, which you can use in AL development.
Having said that, you can do some development, but currently table changes doesn't work,
We will assess and might add more functionality to C/SIDE in the dev preview, but this is clearly not the primary goal of the setup.

**Comment by bachii1010** [comment]
Hi ,

We know that it is not for development
But we are using it to export the objects in new syntax.

So when we import our objects into the db to export with new syntax command i cannot compile it.

Please suggest me if i am wrong.

**Comment by freddydk** [comment]
Ok, yes that scenario is broken in September preview, but I will be updating the template in a few days and re-enabling this scenario.
The primary problem here is, that the template defaults to different users in nav and VM admin.
If you use the same username (ex. vmadmin) you will be able to use Windows Auth. from C/SIDE to the database - and you will be able to compile.
the second problem you might run into if you are using the financials localizatoin is some missing permissions/entitlements (when you do table changes it calls upgrade code and the permission for that is not in place), which also will be updated in a few days.

**Comment by freddydk** [comment]
btw. I will also add a sample script, which takes all modified objects, create deltas and convert to AL files.

**Comment by freddydk** [comment]
You should be able to create a new september preview on http://aka.ms/navdeveloperpreview2 - that will give you a devpreview with a few updates, which should enable your scenario. (without script yet)
