### ISSUE TITLE
Snapshot debugger error "Not found"

### ISSUE THREAD

**Issue by Frmog** [microsoft/AL#6880]
Hi,
I'm not sure if this is an error, or/and how to fix it, so I will report it just in case.
I would be very grateful if you can contribute with any help in order for me to fix this issue, thanks in advance.

I'm trying to snapshot debug our Azure production server, but i get the error, "Not found"
![image](https://user-images.githubusercontent.com/84179334/148521959-7ad8179f-d273-4bbe-a3b6-4316ffbf8db6.png)

I should have administrator permissions:
![image](https://user-images.githubusercontent.com/84179334/148522225-e1902626-22f9-4203-89c0-a14e4ebbf420.png)

the server is working:
![image](https://user-images.githubusercontent.com/84179334/148522301-4e4e0645-a865-4e47-b907-4154c1e52405.png)
![image](https://user-images.githubusercontent.com/84179334/148522897-71e5d4ae-0f85-4f2d-a510-9104404586c7.png)

I'm running the latest version of visual studio code, and business central
Launch Json:
![image](https://user-images.githubusercontent.com/84179334/148522988-bf62d9b3-fff4-45d3-b924-ba926b8c1d41.png)

Please let me know if you need more info.
Best Regards

**Comment by AskeHolst** [comment]
Seem your have an environment called "ferm_LIVEING_Production", but have "environmentName": "production" in launch.json???

**Comment by Frmog** [comment]
that helped, thanks for your help
