### ISSUE TITLE
Editable property works with Enum in page but it does not in table

### ISSUE THREAD

**Issue by deadmouse** [microsoft/AL#6881]
**1. Describe the bug**
Editable property properly works with Enum in pages but it does not in tables.

**2. To reproduce**

1. Create an enum with at least two options.
2. Create a table, add a field and make Editable property equal an enum value:

``` AL
field(50100; "G/L Account"; Code[20])
{
    Editable = "Bal. Account Destination Type" = "Bal. Account Destination Type"::Source;
}
```

**3. Expected behavior**
Being able to package.

**4. Actual behavior**
Unable to package. The error thrown is: Syntax error, boolean literal expected AL (AL0220)

**5. Notes**
Unlike in tables, it does not throw error in pages:
``` AL
field("G/L Account"; Rec."G/L Account")
{
    Editable = Rec."Bal. Account Destination Type" = Rec."Bal. Account Destination Type"::Source;
}
```

**6. Versions:**

- AL Language: v8.2.552672
- Visual Studio Code: 1.63.2
- Business Central: Not needed
- List of Visual Studio Code extensions that you have installed: AL Language; Create GUID; Explorer Exclude; Git Graph; GitLens - Git supercharged; PowerShell; TabOut; Todo Tree; vscode-icons.

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
Dynamic properties have never worked on table fields.

It should give an error before building, via background analysis if you have that enabled. Does it not?

**Comment by deadmouse** [comment]
Yes, it does throw an error via background analysis before packaging. So, if this is by design I am going to close the issue. Hope some day it is implemented :)

**Comment by dnpb** [comment]
Best to submit an idea here on BC Ideas, if there is not one already after searching:
https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central
