### ISSUE TITLE
BigInteger overflow runtime error

### ISSUE THREAD

**Issue by MiePlougstrup** [microsoft/AL#6883]
**1. Describe the bug**

I have a procedure like this:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/14122139/148778079-e8ca96f4-1d3d-49bc-b3e0-89f3ff645bf2.png">

I now get the runtime error: Arithmetic operation resulted in an overflow.

The error is in this calculation:
Measurements.Add('LineVol', (Height * 10) * (Length * 10) * (Width * 10) * Quantity);

With these values:
Height = 60
Length = 120
Width = 80
Quantity = 4

The calculated value is 2,304,000,000.
This should result in an error if i had used an Integer, but not when I use BigInteger.

The documentation states as follows:

BigInterger Data Type: Stores very large whole numbers that range from -9,223,372,036,854,775,807 to 9,223,372,036,854,775,807.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/biginteger/biginteger-data-type

Integer Data Type: Stores whole numbers with values that range from -2,147,483,647 to 2,147,483,647.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/integer/integer-data-type

**2. To Reproduce**

1. Create an action like below.
2. Run the action from the page.
3. Runtime error will be thrown.

AL:
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {

            action(ManualTestAction)
            {
                Caption = 'Manual Test - Calc big integer';
                ToolTip = 'Test';
                Image = TestDatabase;
                Promoted = true;
                PromotedOnly = true;
                PromotedIsBig = true;
                PromotedCategory = Process;
                ApplicationArea = All;

                trigger OnAction();
                begin
                    Message(Format(CalcBigInteger(60, 120, 80, 4)));
                end;
            }
        }
    }
    procedure CalcBigInteger(Height: Integer; Length: Integer; Width: Integer; Quantity: Integer) BigInt: BigInteger
    begin
        BigInt := (Height * 10) * (Length * 10) * (Width * 10) * Quantity;
    end;
}

**3. Expected behavior**
That a BigInteger variable can store the value 2,304,000,000.

**4. Actual behavior**
Runtime error: Arithmetic operation resulted in an overflow.

**5. Versions:**

- AL Language: 8.2.552672
- Visual Studio Code: 1.63.2
- Business Central: DK Business Central 19.1 (platform 19.0.31889.32155 + program 19.1.31886.32186)
- List of Visual Studio Code extensions that you have installed: None

**Comment by dnpb** [comment]
Probably you need to cast one/all of those `Integer` subexpressions to `BigInteger`, else you're overflowing the intermediate value before you can ever add it to the `Dictionary`.

**Comment by MiePlougstrup** [comment]
> Probably you need to cast one/all of those `Integer` subexpressions to `BigInteger`, else you're overflowing the intermediate value before you can ever add it to the `Dictionary`. The platform will use `Integer` until told otherwise, i.e. until some expression involves a `Decimal` or `BigInteger` or other type. It doesn't know that because you're eventually going to store the result in a `BigInteger`, it should use higher width than normal. So help it by making at least one of those a `BigInteger`, and it should do the calculation on that basis, instead of assuming it should continue with the `Integer`s that you're currently giving it.

OK, that makes sence. I will try that.

**Comment by nndobrev** [comment]
@MiePlougstrup, please let us know if it works with casting the intermediate values.

**Comment by MiePlougstrup** [comment]
> @MiePlougstrup, please let us know if it works with casting the intermediate values.

Yes, it worked, when i did like this:

procedure CalcBigInteger(Height: Integer; Length: Integer; Width: Integer; Quantity: Integer) BigInt: BigInteger
    var
        BigIntConverter: BigInteger;
    begin
        BigIntConverter := 1;
        BigInt := BigIntConverter * (Height * 10) * (Length * 10) * (Width * 10) * Quantity;
    end;

**Comment by nndobrev** [comment]
Closing this as it works as intended.

**Comment by guidorobben** [comment]
I had the same issue. In the beginning I had the following line.

` exit(DurationMin * 60000);`

This gave me an error. I couldn't figure out what to do. So I put the integer in the BigInteger and then it worked.

```
local procedure DurationToMs(DurationMin: Integer): BigInteger
    var
        DurationMinBigInt: BigInteger;
    begin
        DurationMinBigInt := DurationMin;
        DurationMinBigInt := DurationMinBigInt * 60000;
        exit(DurationMinBigInt);
    end;
```
