### ISSUE TITLE
Code 'ua' is not a valid ISO 3166-1 alpha-2 code

### ISSUE THREAD

**Issue by sergeyol** [microsoft/AL#6888]
Please include the following with each issue:

**1. Describe the bug**

We are building an app for AppSource. In the AppSourceCop.json, we specify:
`"supportedCountries": ["ua"]`

When compiling our extension for AppSource, we receive the following warning:

`
AppSourceCop.json(1,1): warning AS0056: The code 'ua' is not a valid ISO 3166-1 alpha-2 code for a country/region supported by the product.
`

UA is a valid ISO code for Croatia: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
Ukraine is supported by the product: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations

**2. To Reproduce**

1. Specify `"supportedCountries": ["ua"]` in AppSourceCop.json.
2. Compile the app.

**3. Expected behavior**
Warning should not appear.

**5. Versions:**

- AL Language: v8.2.552672
- Visual Studio Code: 1.63.2
- Business Central: 19.2

Similar issue: #6209

**Comment by qutreson** [comment]
Closing this issue as it should now be fixed in the latest version of the AL Extension for Visual Studio Code and in our latest developer preview.
