### ISSUE TITLE
Conditional directives: make text in different color like VS

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#6889]
Please include the following with each issue:

**1. Describe the bug**
Is it possible to visualize the current processing directive like VS?
![image](https://user-images.githubusercontent.com/36199751/149490747-3e3f8949-897c-4ae1-831d-0b5324a8fe34.png)

So if not enabled make the code grey/different color

**5. Versions:**

- AL Language: Any
- Visual Studio Code: Any
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
A BC Idea was already filed for this:
https://experience.dynamics.com/ideas/idea/?ideaid=4e96cc16-b83b-ec11-a3ee-0003ff45a61a

**Comment by f4n0** [comment]
thanks, I've missed that!

**Comment by nndobrev** [comment]
Hi @f4n0, I will close that since the right place for it is indeed bcideas. :)
