### ISSUE TITLE
September Update : ExportNewSyntax issue

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#689]
Hi,

When we use the exporttonewSyntax command to export the objects in september update we are getting the below error:

_[2_2922070] The following SQL Server error or errors occurred: 18452,"28000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.__
 

Please suggest us.

Thanks & Regards,
Varun Reddy

**Comment by atoader** [comment]
Are you running the command with administrator rights? What shell are you running the command from?

**Comment by bachii1010** [comment]
Hi 

We are running the command from command prompt should we run it from container comand prompt and yes we are running with admin rights

**Comment by freddydk** [comment]
This should work from the Container PowerShell Prompt: Export-NAVApplicationObject -DatabaseName FinancialsUS -Path c:\demo\test.txt -DatabaseServer localhost\SQL
XPRESS -LogPath c:\demo\log -Force -ExportToNewSyntax -Username sa -Password <yourpassword>

**Comment by bachii1010** [comment]
Hi,

I am able to do this with the suggestion from freddy but i am getting the below error:
![image](https://user-images.githubusercontent.com/26792519/30542994-0612eb5e-9c9f-11e7-82d1-f8b7e9b8ad4f.png)
i can upload our license but i need to know how can i restart the service as i cannot find it in the same VM

Can you please suggest.

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
In the NAV Container PowerShell prompt, you write: Set-NavServerInstance NAV -restart
you can also do Import-NavServerlicense in there.
or you can restart the container in a normal command prompt: docker restart navserver

**Comment by freddydk** [comment]
I have created a script which automates all the steps: creating baseline, export changes, create deltas, create .al files - this will be on my blog and on the image next week.

**Comment by dkatson** [comment]
Hi @freddydk .
I have next error when use 

Export-NAVApplicationObject -DatabaseName FinancialsUS -Path c:\demo\test.txt -DatabaseServer localhost\SQL
XPRESS -LogPath c:\demo\log -Force -ExportToNewSyntax -Username sa -Password yourpassword

![image](https://user-images.githubusercontent.com/29101017/30708294-075bf784-9f07-11e7-9f85-b08862bbd050.png)

**Comment by dkatson** [comment]
Oh my fault. Wrong DB name. All is ok
