### ISSUE TITLE
How to Create a user for BC Device License type  in Docker Environment ?

### ISSUE THREAD

**Issue by divjotn** [microsoft/AL#6895]
@freddydk 
Hi Freddy

Can we create a user for BC Device License type  in Docker Environment ?
if possible ,then can you please suggest me steps for creating  a user  for BC Device License type  in Docker Environment.
Also please suggest what are the limitations for BC Device license.

Thanks in advance

Thanks and Regards
Divjot Singh

**Comment by dnpb** [comment]
This repo is for issues in the AL language/compiler, not other topics. Try Docker if you want to ask Freddy something as he's pretty active there.

**Comment by dnpb** [comment]
This repo is for issues in the AL language/compiler, not other topics. Try Yammer if you want to ask Freddy something as he's pretty active there: https://www.yammer.com/dynamicsnavdev#/home
