### ISSUE TITLE
Direct printing to printer Report.Run()

### ISSUE THREAD

**Issue by Martnael** [microsoft/AL#6896]
**1. Describe the bug**
I'm on Business Central 19.2.32968.33504. Trying to replicate direct printing to label printer what worked on NAV 5.0. 
Is direct printing at all possible in new BC 19?

**2. To Reproduce**

Printers are set up in the Printer Selections page as on the picture. Running on Business Central what is installed to my computer. Printers are installed locally at the moment.

![Printersetup](https://user-images.githubusercontent.com/72755642/150155720-457dc671-0f7a-488f-bcd1-30b3376b3419.JPG)

Code what is calling out printing:
                    WhseActivHeader.RESET;
                    WhseActivHeader.CLEARMARKS;
                    WhseActivHeader.SETCURRENTKEY(Type, "Shipment/ Receipt No.");
                    WhseActivHeader.SETRANGE(Type, WhseActivHeader.Type::Pick);
                    WhseActivHeader.SETRANGE("Shipment/ Receipt No.", Rec."No.");
                    WhseActivHeader.SETRANGE("Last Registering No.", '');
                    WhseActivHeader.SETRANGE("No. Printed", 0);
                    WhseActivHeader.CALCFIELDS("Page Packing");
                    WhseActivHeader.SETRANGE("Page Packing", false);
                    IF WhseActivHeader.FINDSET THEN BEGIN
                        WhseSticker.SETTABLEVIEW(WhseActivHeader);
                        Report.Run(Report::"Sticker Strip", FALSE, TRUE, WhseActivHeader);
                    END;

Code is calling out three different reports all should be a different printer (warehouse, office, and so on)
I have tried Report.Print() and so on and different inputs to Run function. All ending up as pdf in my download folder.

**3. Expected behavior**
Reports are printed directly in the printer what is set up in the Printer Selection page.
Without showing the request page or any other printer selection page.

Trying to replicate this: https://www.youtube.com/watch?v=39fWPWknMIo&t=8s

**4. Actual behavior**
All report outputs are downloaded to the computer as pdf files. 

**5. Versions:**

Label Printer: Toshiba B-SA4TM other printer EPSON WF5790
- AL Language: +
- Visual Studio Code: 1.63.2
- Business Central: 19.2.32968.33504

**Comment by pri-kise** [comment]
If you are on the cloud this does not work, but for OnPrem you should check out the following repository. 
Maybe this can help you to setup "Direct Printing".
https://github.com/qbsgroup/QBS.BusinessCentral.DirectPrint

**Comment by thloke** [comment]
Hi, as @pri-kise mentions this issue is out of scope for this repository since it's about application functionality instead of the AL language itself. The Yammer channel is a good place to ask for help, otherwise you can also file a support request or go to Collaborate to get this prioritized by the correct teams
