### ISSUE TITLE
Exporting Document Attachments to zip

### ISSUE THREAD

**Issue by IgorBETerna** [microsoft/AL#6897]
**1. Describe the bug**
When exporting multiple document attachments in pdf using TempBlob codeunit some attachments gets corrupted,
when attachment smaller in file size is attached after bigger file.
When smaller attachment is uploaded in attachments as first and then bigger one as second problem is not reproduceable.
Soo exporting attachments depends on upload order.
Using latest BC v. 19.2.32968.33504. 
Version: W1 19.2 (Platform 19.0.32956.33475 + Application 19.2.32968.33504)

**2. To Reproduce**

1. Go to random document with Document Attachments
2. Choose two pdf files in different sizes
3. Upload first biggest file (pdf)
4. Upload second file (pdf) which is smaller
5. run code below as a function or a job (run once in foreground) (Example used Posted Sales Invoice No.:103027)
``` AL
trigger OnRun()
    var
        DocumentAttachment: Record "Document Attachment";
        OutStreamDocAtt: OutStream;
        DocInStream: InStream;
        TempBlob: Codeunit "Temp Blob";
        DataCompression: Codeunit "Data Compression";
        OutStreamZIPFile: OutStream;
        TenantMedia: Record "Tenant Media";
        InStreamObj: InStream;
        ToFile: Text;
    begin
        DataCompression.CreateZipArchive();

        DocumentAttachment.Reset();
        DocumentAttachment.SetRange("Table ID", 112);
        DocumentAttachment.SetRange("No.", '103027');
        if DocumentAttachment.FindSet() then
            repeat
                Clear(OutStreamDocAtt);
                Clear(DocInStream);
                if DocumentAttachment."Document Reference ID".HasValue() then begin
                    TempBlob.CreateOutStream(OutStreamDocAtt);
                    DocumentAttachment."Document Reference ID".ExportStream(OutStreamDocAtt);
                    TempBlob.CreateInStream(DocInStream);
                    DataCompression.AddEntry(DocInStream, DocumentAttachment."File Name" + '.' + DocumentAttachment."File Extension");  
                    
                end;
            until DocumentAttachment.Next() = 0;

        TempBlob.CreateOutStream(OutStreamZIPFile);
        DataCompression.SaveZipArchive(OutStreamZIPFile);

        TempBlob.CreateInStream(InStreamObj);
        ToFile := 'eDocumentPackage.zip';
        DownloadFromStream(InStreamObj, '', '', 'Zip Files (*.zip)|*.zip|All Files (*.*)|*.*', ToFile);
    end;
```
6. when zip folder is extracted second pdf file is same in bytes size as first.
7. If using TenantMedia problem is not relevant (workaround):
``` AL
trigger OnRun()
    var
        DocumentAttachment: Record "Document Attachment";
        OutStreamDocAtt: OutStream;
        DocInStream: InStream;
        TempBlob: Codeunit "Temp Blob";
        DataCompression: Codeunit "Data Compression";
        OutStreamZIPFile: OutStream;
        TenantMedia: Record "Tenant Media";
        InStreamObj: InStream;
        ToFile: Text;
    begin
        DataCompression.CreateZipArchive();

        DocumentAttachment.Reset();
        DocumentAttachment.SetRange("Table ID", 112);
        DocumentAttachment.SetRange("No.", '103027');
        if DocumentAttachment.FindSet() then
            repeat
                Clear(OutStreamDocAtt);
                Clear(DocInStream);
                if DocumentAttachment."Document Reference ID".HasValue() then begin               
                    if TenantMedia.Get(DocumentAttachment."Document Reference ID".MediaId()) then begin
                        TenantMedia.CalcFields(Content);
                        TenantMedia.Content.CreateInStream(DocInStream);
                        DataCompression.AddEntry(DocInStream, DocumentAttachment."File Name" + '.' + DocumentAttachment."File Extension");
                    end;
                end;
            until DocumentAttachment.Next() = 0;

        TempBlob.CreateOutStream(OutStreamZIPFile);
        DataCompression.SaveZipArchive(OutStreamZIPFile);

     
        TempBlob.CreateInStream(InStreamObj);
        ToFile := 'eDocumentPackage.zip';
        DownloadFromStream(InStreamObj, '', '', 'Zip Files (*.zip)|*.zip|All Files (*.*)|*.*', ToFile);
    end;
```

**3. Expected behavior**
Exporting documents attachments (pdf-s) should not depende on file sizes and upload order.

**4. Actual behavior**
When using TempBlob for exporting document attachments and when document attachments include pdf files, smaller pdf files gets corrupted if previous pdf file is bigger.

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: 1.63.2
- Business Central: 19.2.32968.33504
- List of Visual Studio Code extensions that you have installed: only apps

**Comment by thloke** [comment]
Hi, thanks for raising this issue. Unfortunately this is out of scope for this repository since we'll need the runtime team to handle this. As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.  What you can do to get this to the correct team is:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
