### ISSUE TITLE
Is January update applied on existing Azure Previews?

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#69]
Hi,

Is January update applied on existing images or do we have to do anything?
I have re build and published extension but still previous bugs are not solved.

**Comment by StanislawStempin** [comment]
You need to create a new VM from the updated image: [https://aka.ms/navdeveloperpreview](https://aka.ms/navdeveloperpreview). We have no control over the existing VMs created from the previous version of the image.

**Comment by pmohanakrishna** [comment]
thanks..
