### ISSUE TITLE
[Bug] Media type field's function ExportStream() does not take into account Record.CurrentCompany() if Record.ChangeCompany() was applied

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/AL#6903]
Please include the following with each issue:

**1. Describe the bug**
Field type Media does not export with ExportStream() from the record from other company if ChangeCompany was applied despite HasValue() is working correctly.

**2. To Reproduce**
1. Have at least 2 companies created
2. Have at least 1 Bank Account in each company created with Image uploaded.
3. Run code from the snippet1.

Snippet1:
```
    local procedure test()
    var
        BankAcc: Record "Bank Account";
        Comp: Record Company;
        Base64: Codeunit "Base64 Convert";
        TempBlob: Codeunit "Temp Blob";
        InS: InStream;
        OutS: OutStream;
    begin
        if Comp.FindSet() then
            repeat
                BankAcc.ChangeCompany(Comp.Name);
                if BankAcc.FindSet() then
                    repeat
                        if BankAcc.Image.HasValue() then begin //Bank Account's field Image has type Media
                            TempBlob.CreateOutStream(OutS);
                            if BankAcc.Image.ExportStream(OutS) then begin
                                TempBlob.CreateInStream(InS);
                                //this message will never be shown for non-current company
                                Message('Company %1\Bank Account %2\Image in Base64:\%3',
                                        Comp.Name,
                                        BankAcc."No.",
                                        Base64.ToBase64(InS));
                            end;
                        end;
                    until BankAcc.Next() = 0;
            until Comp.Next() = 0;
    end;
```

**3. Expected behavior**
Messages shown for every company and every bank account where Image has value.

**4. Actual behavior**
Messages shown only for current company.

**5. Versions:**

- AL Language: v8.1.540594
- Visual Studio Code: does not matter
- Business Central: 19.2.32968.33504
- List of Visual Studio Code extensions that you have installed: does not matter

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

P.S.
currently, there is workaround with the usage of Tenant Media table:
```
    local procedure test()
    var
        BankAcc: Record "Bank Account";
        Comp: Record Company;
        TenantMedia: Record "Tenant Media";
        Base64: Codeunit "Base64 Convert";
        InS: InStream;
    begin
        if Comp.FindSet() then
            repeat
                BankAcc.ChangeCompany(Comp.Name);
                if BankAcc.FindSet() then
                    repeat
                        if BankAcc.Image.HasValue() then begin
                            TenantMedia.Get(BankAcc.Image.MediaId);
                            TenantMedia.CalcFields(Content);
                            TenantMedia.Content.CreateInStream(InS);
                            //now message is shown for every company and every bank account within that companies
                            Message('Company %1\Bank Account %2\Image in Base64:\%3',
                                    Comp.Name,
                                    BankAcc."No.",
                                    Base64.ToBase64(InS));
                        end;
                    until BankAcc.Next() = 0;
            until Comp.Next() = 0;
    end;
```

**Comment by PaulFurlet** [comment]
Sometimes it is not obvious where exactly to open the issue for the System App / Base App.
reopened initial issue https://github.com/microsoft/ALAppExtensions/issues/16081

**Comment by dnpb** [comment]
My guess is this is more like a platform/runtime issue than either AL (language or build-time) or extensibility (it presumably is not specific to just the MS base apps)

**Comment by PaulFurlet** [comment]
@dnpb Does not depend on runtime - tested on BC18.1 and BC19.2 - same behavior.
