### ISSUE TITLE
AL Developer Fails To Remember Cached Credentials When Publishing Package To SaaS

### ISSUE THREAD

**Issue by jklassen** [microsoft/AL#6905]
**1. Describe the bug**
Cached credentials for SaaS are "forgotten" when publishing a package.
> Authenticating...
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CJWHADXK8 to authenticate.
> 
This is a common annoyance I think most AL developers are aware of but I am certain this is a bug because if I don't following the instructions and instead I cancel the request using the red square in the debugger window and then re-attempt to publish the package (up to three attempts) it will succeed with the cached credentials as if they were magically rediscovered.

**2. To Reproduce**

1. Open an AL extension workspace
2. Publish without debugging to a SaaS environment.
3. Follow instructions to authenticate and publish to the environment.
4. Now re-publish the package again without debugging.
5. If it asks to "To sign in, use a web browser to open the page https://microsoft.com/devicelogin..." 
  then great (well not really) and you can continue to the next step. if not then 5. 
  But if not, then keep publishing till you get the request. Maybe wait a minute or two.
6. Click the red square, stop icon, in the floating debugger tab that temporarily opens for the publishing.
7. Re-attempt to publish without debugging.
8. If it asks for you to authenticate then keep trying step 4-6. Sometimes it take 2-3 attempts.
9. If it successfully publishes without asking to authenticate. Then voila! Why did it not succeed the first time?

**3. Expected behavior**
The cached credentials should allow me to publish without constantly having to do the tedious re-authentication. The steps I mentioned above prove the authentication was already cached but somehow it was "lost" on the first call to publish the extension.

**4. Actual behavior**
Cached credentials are "forgotten" for the first attempt to publish a package, second (maybe third) attempt then the AL Extension magically remembers the cached credentials and no re-authentication is required.

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: 1.63.2
- Business Central: 19.x (But also existed before)
- List of Visual Studio Code extensions that you have installed:
AL Language

**Comment by thloke** [comment]
Hi,

We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

Thanks,
Thaddeus

**Comment by jklassen** [comment]
That's unfortunate. This credentials cache seems to be almost complete. This would be a huge time saver having this resolved.

**Comment by dnpb** [comment]
I'm confused... Surely it would make more sense to label it as low-priority, than to close it 'at the moment' and risk it never getting fixed if no one else reports it again at a more favourable time...

**Comment by mjmatthiesen** [comment]
Also see #6124.

This has been a long standing issue with the authentication. I assume the authentication has some sort of timer associated with it, that is just expiring earlier than anticipated.

**Comment by n8silverman** [comment]
This is still an issue in April 2023.
