### ISSUE TITLE
New object: Action Pane

### ISSUE THREAD

**Issue by ariweinda** [microsoft/AL#6907]
new object type called Action Pane. it may have a Rec behind and has actions on it. that way, i can put the same pane on list and card pages and i dont have to repeat them on both. eg, most of actions on sales order list and sales order page are the same and i dont want to have those actions twice

**Comment by thloke** [comment]
Hi, suggestions are out of scope for this repository. You're better off raising this as an idea under BCIdeas. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
