### ISSUE TITLE
BUG - Update Opportunity with Security filter

### ISSUE THREAD

**Issue by josejggil** [microsoft/AL#6916]
**1. Describe the bug**
Unable to update an opportunity on which security filter has been applied

**2. To Reproduce**

Create permission set with security filter

![image](https://user-images.githubusercontent.com/47104041/152141736-81230dfd-a807-4d29-b367-f5360b1c602d.png)
![image](https://user-images.githubusercontent.com/47104041/152141790-8cbcd656-6d98-4ffc-a75d-026b60a7fd41.png)
![image](https://user-images.githubusercontent.com/47104041/152141820-3e78c0bc-940b-47ff-a093-edfade4d17e7.png)

With this, the user can only access the opportunities that meet the security filter condition.
However, if we try to update one of them

![image](https://user-images.githubusercontent.com/47104041/152142031-9dc9b265-9df5-44fd-8166-298da9128382.png)
![image](https://user-images.githubusercontent.com/47104041/152142157-239a7c64-0ed8-4bef-8918-d139af43079a.png)

This error occurs

![image](https://user-images.githubusercontent.com/47104041/152142245-c1097de3-bf47-4801-b7d8-8e08e75c7295.png)

**3. Expected behavior**
Update the opportunity

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

![image](https://user-images.githubusercontent.com/47104041/152143553-1b47ec01-cdf8-4e02-8e26-9f64f0fabefb.png)

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
This does not look as an AL extension languages server issue. 
Copy pasting our template answer:
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
