### ISSUE TITLE
controladdin broken: scripts are loaded out-of-order

### ISSUE THREAD

**Issue by TardisServer** [microsoft/AL#6923]
**Description:** 

In the latest version of business central, controladdins which depend on a specific script loading order (e.g., a jQuery dependency or a bootstrap.js dependency) are broken because javascript files are not loaded in the order of their definition in the 'scripts' tag.

**To Reproduce**

1. Create a controladdin (e.g. 'LoadTest') like so:

        controladdin "LoadTest"
        {
        
            StartupScript = 'js/LoadTest/startup.js';
            Scripts = 'js/jquery-3.6.0.min.js',
                        'js/LoadTest/main.js';
        
        }

2. In the file `js/LoadTest/main.js`, write the following:

        $(async function(){
          console.log("Loaded In-Order");
        });

3. In the file `js/LoadTest/startup.js` write:

        console.log("Loaded Startup Script");

4. Finally, create a page to load the controladdin:

        page 50000 "Load Test Page"
        {
            Caption = 'Load Test';
            PageType = StandardDialog;
        
            layout
            {
                area(Content)
                {
                    usercontrol(ControlName; "LoadTest")
                    {
                        ApplicationArea = all;
                    }
                }
            }
        
        }

Result:

The controladdin will always have the message `Loaded Startup Script` in the console, but will arbitrarily (around 50% of the time) have the other message `Loaded In-Order`, and will otherwise throw an error indicating that `$` is undefined.

The expected behavior (as given in previous versions of business central) is that the scripts load in the order in which they are defined, which is important. It appears the scripts are loaded with `defer`, which is not valid for and breaks a large number of use cases.

This is an issue because certain extensions, e.g. a templating engine for writing an interactive interface, require jQuery to load first and be available. Additionally, jQuery hooks often represent the entry point for a number of behaviours, so breaking this makes the controladdin do absolutely nothing.

**Versions:**

AL: v.8.3.570094
VSCode: 1.63.2
Business Central: DE Business Central 19.3
Installed Extensions: AZ AL Dev Tools/AL Code Outline

**Comment by TardisServer** [comment]
**Hacky Workaround**

Business central doesn't actually verify the mime-type of files when defining them as `Images` in the controladdin (I am not sure if this is intentional or not, but definitely very useful, e.g. when loading non-hard-coded JSON or video files). You can therefore access basically any resource as long as you define it there. You can force in-order loading by abusing the `StartupScript` and doing the following trick:

1. In the controladdin, instead of adding your scripts to the `Scripts` tag, add them to the `Images` tag:

        controladdin "LoadTest"
        {
            StartupScript = 'js/LoadTest/startup.js';
            Images = 'js/jquery-3.6.0.min.js',
                        'js/LoadTest/main.js';
        }

This has the effect that the scripts are not actually loaded but made available as resources to the `Microsoft.Dynamics.NAV.GetImageResource` function.

2. In `startup.js`, write a `ScriptLoader` class which uses `async await` syntax to force in-order loading:

        class ScriptLoader {
        
            static async init(){
                await ScriptLoader.include("jquery-3.6.0.min.js");
                await ScriptLoader.include("LoadTest/main.js");
            }
        
            static path(file){
                return Microsoft.Dynamics.NAV.GetImageResource('js/' + file);
            }
        
            static include(file){
                return new Promise( resolve => {
                    var script  = document.createElement('script');
                    script.onload = resolve;
                    script.src  = ScriptLoader.path(file);
                    script.type = 'text/javascript';
                    script.defer = true;
                    document.head.appendChild(script);
                });
            }
        
        }
        
        console.log("Loaded Startup Script");
        ScriptLoader.init();

Congratulations. Your scripts are now loaded in order and your program is no longer broken.

**Comment by bjarkihall** [comment]
@TardisServer we're actually going to change to this approach since it also opens the possibility of lazy-loading our scripts as needed (it also allows us to control the scripts attributes, like type=module), just hoping MS won't accidentally/intentionally break this approach too, e.g. with some CORS restrictions in SAAS. :/

**Comment by TardisServer** [comment]
Yes I suppose that is the silver lining - modules could not be loaded (which was very disappointing for having nicely structured code) - but being forced to do it this way should allow for that. I did notice that with lazy-loading, loading times took a slight hit, but this is the tradeoff. I hope they don't break this possibility - it is not only image resources that need loading into controladdins sometimes.

**Comment by bjarkihall** [comment]
Yes, the delay is because you load them in series, that is, you await **every** file, while some might be loaded in paralell.
I think you can get almost the same speed as before if you allow scripts to be loaded at the same time (e.g. by using Promise.all) where possible. :)
You might also bundle the initial files into a single file with a bundler (e.g. webpack/rollup/parcel/vitejs) and only lazy-load files you require later in the web app.

**Comment by thloke** [comment]
This issue has been fixed and a hotfix has been rolled out.
