### ISSUE TITLE
dependencyPublishingOptions: Ignore still builds dependencies

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/AL#6925]
**1. Describe the bug**
`launch.json` setting `"dependencyPublishingOption": "Ignore"` does not ignore **compilation/builds** of dependencies (but correctly only **publishes** the active one).

We use this property in our setup because both our build + publish times are usually 1 + 3 minutes (or even more) for our largest extension in a multi-root workspace.

**2. To Reproduce**
In a multi-root workspace, you have an extension A which depends on extension B (which propagateDependencies to extension C).
All extensions have `"dependencyPublishingOption"` set to `"Ignore"` in `launch.json`.
I make changes to extension A and sometimes C and publish them separately.
When publishing extension A, the AL Language extension starts **building** extension B (even if it hasn't changed).

**3. Expected behavior**
Only the extension A (the active extension) should be compiled + published, this is how it worked previously, at least.
I would expect that I don't have to wait for extension B to do anything, since it's supposed to be "ignored".

**4. Actual behavior**
Both extensions A and B get **compiled** (the issue).
Only extension A (active extension) gets **published** (works as expected).

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: 1.63.2
- Business Central: 19.2
- List of Visual Studio Code extensions that you have installed: None

### Final Checklist

Please remember to do the following:
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
Building in VsCode and publishing are not really coupled this way.  They are completely decoupled operations. The current design - and this is not for publishing, but for RAD state and symbol state - we will build  (RAD) dirtied project reference  (e.g change an AL file). I am not sure we will change this. Maybe request a new feature change.

**Comment by bjarkihall** [comment]
@kalberes I tried deleting rad.json, but should extension B be built if it has no changed files since last build? If so I can close the issue.

![image](https://user-images.githubusercontent.com/8615374/152695321-668edc7e-2af5-40c2-9f04-15558d0f12e8.png)

So, to bypass the current design for now, I'm forced to only have A and C in the multiroot-workspace.
That way the VSCode extension won't start building B every time I try to publish A.

**Comment by kalberes** [comment]
@bjarkihall  I think this is a bug. I missed one detail in your original description : which propagateDependencies to extension C.

**Comment by bjarkihall** [comment]
Thanks for giving it another look, just let me know if you need any more info, it can get a bit tricky to describe these kind of scenarios. :)

**Comment by thloke** [comment]
I cannot reproduce this with a simple workspace (exactly the same as in your diagram). In my case, only A and C are compiled. Can you check the contents of the `rad.json` in project B when it happens?

It definitely should not be building project B if project B's `rad.json` file does not have any changes tracked.

**Comment by bjarkihall** [comment]
It must've been fixed then since I reported it?
I'll close the issue and reopen if it reoccurs and try to provide more detail as to why it might be happening.
At the time I tried removing rad.json and .app files before doing a full publish, seemed to always happen whatever I tried.
Thanks for taking a look though
