### ISSUE TITLE
Cannot remove obsolete controladdin

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/AL#6927]
Please include the following with each issue:

**1. Describe the bug**
A controladdin needs to be removed in App A.
The controladdin is removed=pending in version 2 of an app A.
Version 3 of App A has the controladdin removed. 
AppSourceCop detects a breaking change.
This is a bug, it should be allowed to remove the controladdin after properly obsoleting it in an older version.

**2. To Reproduce**
See 1.

**3. Expected behavior**
AppSourceCop does not issue an error when deleting an obsolete controladdin.

**4. Actual behavior**
See 1

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: no impact
- Business Central: no impact
- List of Visual Studio Code extensions that you have installed: no impact

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue
-> Quentin asked for raising here (https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1598305660624896)

* [x] Reproduce the issue after disabling all extensions except the AL Language extension
not applicable

* [x] Simplify your code around the issue to better isolate the problem
not applicable

**Comment by qutreson** [comment]
I looked into the issue and it actually wasn't an AppSourceCop problem, but a problem during the .app file creation. When the .app file is created, we are packaging also symbolic information about the objects it contains and we are missing to include the obsolete state of control-addins. So even if your control add-in is obsolete, dependent extensions will not see it as obsolete. Same thing for the AppSourceCop. We are fixing this packaging issue. 

This means that the AppSourceCop still won't allow removing obsolete control add-ins if the baseline package was built with an older version of the AL compiler. You will have to create a new version of your app with an AL compiler that has the fix (we will communicate the version once we have it) and use that one as baseline to be able to remove the control-addin.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 35924 and VS Code Extension Version 4.0.170781. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by qutreson** [comment]
We had some issues around exposing the right vsix version on Github. The bug has been fixed yesterday. The fix for this bug will be available with the next update of the AL extension in the Visual Studio Code marketplace. The version for it is  8.3.8.54989
