### ISSUE TITLE
How can we select a Profile-ID?

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#693]
I want to select a profile in a custom setup table but I can't declare the table **Profile - 2000000072** for this. 

How to handle this for SaasS?

![image](https://user-images.githubusercontent.com/28626283/30540943-719aa93c-9c79-11e7-9bcc-769a84a7a235.png)

**Comment by StanislawStempin** [comment]
Duplicate of #500 - we are looking into it
