### ISSUE TITLE
A TryFunction can explicitly return a value - but that value is discarded

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6931]
**1. Describe the bug**
A `TryFunction` must follow a specific signature. That is: it can not have a return value. This is because the return value implicitly becomes a Boolean that indicates whether the function failed (a runtime error was thrown) or if it succeeded (no error was thrown). The compiler therefore fails to compile, if a return value is defined on a function that is decorated with `[TryFunction]`.

The compiler however allows returning explicit Boolean values from inside that function, even though no return value is declared on the procedure (because as explained above: this is not allowed). Furthermore, whatever value is returned, it gets "overwritten" by the behavior explained above. An error occurred: false. No error occurred: true.

This is misleading and should be trapped and prohibited by the compiler.

**2. To Reproduce**
Create the following function:
```` AL
[TryFunction]
procedure SomeTest()
begin
  exit(false); // this should not compile, no return value is defined on the function
end;

// The following code will never show the message. 
// SomeTest will always return true, even if `false` is explicitly returned.
// It is correct behavior, but misleading and the function 'SomeTest' should not compile.
if not SomeTest() then Message('Huzzah!'); 
````

**3. Expected behavior**
The behavior of the function itself is correct, as no error occurred and therefore 'true' is returned. But the function itself should not compile, because explicitly returning a value should not be allowed in a TryFunction, to avoid confusion.

**4. Actual behavior**
Returning an explicit value from inside a TryFunction is allowed.

**5. Versions:**

- AL Language: 8.3.570094 
- Visual Studio Code: 1.64.1
- Business Central: /
- List of Visual Studio Code extensions that you have installed: /

**Comment by dnpb** [comment]
It also fails to diagnose properly if the returned object is a Joker, e.g.

![image](https://user-images.githubusercontent.com/63455896/156743837-6ff80aaf-15f6-4c7e-a9e4-9b56f379df2a.png)

the Variant case is diagnosed but the FieldRef.Value i.e. Joker is not

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

**Comment by hemisphera** [comment]
Thank you!
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al775?wt.mc_id=d365bc_inproduct_alextension
