### ISSUE TITLE
Download AL symbols not found error, how to change my connection url?

### ISSUE THREAD

**Issue by Kuhicop** [microsoft/AL#6933]
- AL Extension Version: v8.3.570094
- Server Version: OnPrem 19 latest

Why my Visual Studio is connecting to [http://adrianbc/BC/dev/metadata?tenant=default](url) ?

**I'm able to connect by browser to Business Central:**
![image](https://user-images.githubusercontent.com/27239965/153788827-f6ca5625-c2d8-46dd-8a31-0dc33e02362d.png)

**When I try to download AL symbols I get Not Found error:**
`[2022-02-11 13:20:58.02] Using reference symbols cache path: c:\Users\dimitri\OneDriveArqui\AL\Pan\./.alpackages
[2022-02-11 13:20:58.02] Sending request to http://adrianbc/BC/dev/metadata?tenant=default
[2022-02-11 13:20:58.03] The request for path /BC/dev/metadata?tenant=default failed with code NotFound. Reason: Not Found
[2022-02-11 13:20:58.03] Sending request to http://adrianbc/BC/dev/webendpoint
[2022-02-11 13:20:58.03] The request for path /BC/dev/webendpoint failed with code NotFound. Reason: Not Found
[2022-02-11 13:20:58.03] Sending request to http://adrianbc/BC/dev/metadata?tenant=default
[2022-02-11 13:20:58.03] The request for path /BC/dev/metadata?tenant=default failed with code NotFound. Reason: Not Found
[2022-02-11 13:20:58.03] Sending request to http://adrianbc/BC/dev/webendpoint
[2022-02-11 13:20:58.04] The request for path /BC/dev/webendpoint failed with code NotFound. Reason: Not Found
[2022-02-11 13:20:58.04] Sending request to http://adrianbc/BC/dev/metadata?tenant=default
[2022-02-11 13:20:58.04] The request for path /BC/dev/metadata?tenant=default failed with code NotFound. Reason: Not Found
[2022-02-11 13:20:58.04] Sending request to http://adrianbc/BC/dev/webendpoint
[2022-02-11 13:20:58.04] The request for path /BC/dev/webendpoint failed with code NotFound. Reason: Not Found`

**Here is my launch.json:**
`{
"version": "0.2.0",
"configurations": [        
    {
        "type": "al",
        "request": "launch",
        "name": "AdrianBC local",
        "server": "http://AdrianBC",
        "port": 80,
        "serverInstance": "BC",
        "authentication": "UserPassword",
        "breakOnError": true,
        "launchBrowser": true,
        "enableLongRunningSqlStatements": true,
        "enableSqlInformationDebugger": true,
        "tenant": "default",
        "schemaUpdateMode": "Synchronize"
    }
]}`

**Here is my docker setup:**
`Mounting Tenant
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Creating http download site
Setting SA Password and enabling SA
Creating adrian as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.24.103.254
Container Hostname  : AdrianBC
Container Dns Name  : AdrianBC
Web Client          : http://AdrianBC/BC/?tenant=default
Dev. Server         : http://AdrianBC
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting AdrianBC to 172.24.103.254 in host hosts file
Setting AdrianBC-default to 172.24.103.254 in host hosts file
Setting AdrianBC-default to 172.24.103.254 in container hosts file

Files:
http://AdrianBC:8080/ALLanguage.vsix

Container Total Physical Memory is 8.5Gb
Container Free Physical Memory is 5.8Gb

Initialization took 38 seconds
Ready for connections!
Reading CustomSettings.config from AdrianBC
Creating Desktop Shortcuts for AdrianBC
Container AdrianBC successfully created

Use:
Get-BcContainerEventLog -containerName AdrianBC to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName AdrianBC to get debug information about the container
Enter-BcContainer -containerName AdrianBC to open a PowerShell prompt inside the container
Remove-BcContainer -containerName AdrianBC to remove the container again
docker logs AdrianBC to retrieve information about URL's again

PS C:\WINDOWS\system32> `

**This is how I've created the docker in PowerShell:**
`Enable-WindowsOptionalFeature -Online -FeatureName $("Microsoft-Hyper-V", "Containers") -All

Set-ExecutionPolicy -ExecutionPolicy Unrestricted

Import-Module PowerShellGet

Install-Module -Name BcContainerHelper

$artifactUrl = Get-BCArtifactUrl -version 19 -country es  -type Sandbox

New-BCContainer -accept_eula -accept_outdated -containerName AdrianBC -artifactUrl $artifactUrl -shortcuts DesktopFolder -updateHosts -isolation hyperv -doNotExportObjectsToText -restart no -auth UserPassword -Verbose -locale "es-ES"`

**Testing with -type OnPrem didn't make any difference**

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository, we don't support general questions on functionality here. You can check our public docs on getting debugging setup here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging

If this doesn't resolve your problem, another option is to reach out to the wider AL developer community on yammer. 

At a quick glace it looks like the port is wrong though. The debugger port usually is 7049 unless you've overridden this.

**Comment by Kuhicop** [comment]
Creating the container as "OnPrem" and setting the launch.json as "OnPrem" did the trick.

Thanks <3
