### ISSUE TITLE
Error "You Cannot Change the value of an AutoIncrement Field" When Not Changed

### ISSUE THREAD

**Issue by DrewBorneman** [microsoft/AL#6934]
### 1. Describe the Bug
We have a table containing a field with the `AutoIncrement = true` property and `ObsoleteState = Removed`.  When modifying a record in this table, the following error is thrown: `You cannot change the value of an AutoIncrement field.`  At no point is the value in this field changed in code, and it has 0 references in this extension or any other.  Removing this property resolves these issues, but causes releases to fail with the message `The field 'Line Id' has changed autoincrement from 'True' to 'False'. Changing autoincrement of fields is not allowed`.  

### 2. To Reproduce
Unknown, since this issue has only surfaced in the last few weeks despite the field having been removed many months ago.  The field in question:
```
        field(10; "Line Id"; BigInteger)
        {
            DataClassification = SystemMetadata;
            AutoIncrement = true;

            ObsoleteState = Removed;
            ObsoleteReason = 'Task 6738';
            ObsoleteTag = 'PIMX4.2';
        }
```
### 3. Expected Behavior
When inserting/modifying a record that does not modify the value of an autoincrement field, this error should not be thrown.

### 4. Actual Behavior
Error thrown as described above

### Versions
- VS Code Version: 1.50.1

- AL Extension Version: 8.1.540594

- Server Version: W1 19.1 (Platform 19.0.31889.32155 + Application 19.1.31886.32186)
- Also tested on container with version: W1 19.3 (Platform 19.0.34506.35781 + Application 19.3.34541.35818)
- VS Code Extensions: n/a

**Comment by moprsal** [comment]
The feedback from the support team is:
1. Change the ObsoleteState from Removed to Pending, or even remove the property (in case we have a issue from our side?)
2. Review the usages of this field and update any AL code trying to modify it to not do it anymore.
3. Obsolete the whole table, stop referencing it and create a new one with the right properties (+ moving data if necessary)

Anyway, is there a way how to really remove tables (and fields) with ObosleteState set to Removed from the extension? The extension has been in the AppSource for more than 3 years. And we have lots of removed tables but still, we need to keep them in the source code.
