### ISSUE TITLE
Run multiple report.print or report.run doesn't work

### ISSUE THREAD

**Issue by rjimenezgactive** [microsoft/AL#6937]
If you try to run two reports in a row in the same code even with standard code like codeunit 242 "Item Jnl.-Post+Print".

            if ItemReg.Get(ItemJnlPostBatch.GetItemRegNo) then
                PrintItemRegister();

            if WhseReg.Get(ItemJnlPostBatch.GetWhseRegNo) then
                PrintWhseRegister();

    local procedure PrintItemRegister()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrintItemRegister(ItemReg, ItemJnlTemplate, IsHandled);
        if IsHandled then
            exit;

        ItemReg.SetRecFilter();
        Report.Run(ItemJnlTemplate."Posting Report ID", false, false, ItemReg);
    end;

    local procedure PrintWhseRegister()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrintWhseRegister(WhseReg, ItemJnlTemplate, IsHandled);
        if IsHandled then
            exit;

        WhseReg.SetRecFilter();
        Report.Run(ItemJnlTemplate."Whse.Register Report ID", false, false, WhseReg);
    end;

Just print the last one.

**Comment by dnpb** [comment]
As is documented:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-run-method

> Internet browsers can only handle one file per request. Therefore, with the Web client, if this method is called in a repetitive statement (or loop) that generates multiple files, only the last file will be sent to the browser. Alternatively, when designing for the Web client, bundle the files in an archive file (.zip), for example, by using the methods found in codeunit 419 File Management. For more details about this design pattern, see [Multi-File Download](https://community.dynamics.com/nav/w/designpatterns/220.multi-file-download). The methods in codeunit 419 are not external, therefore cannot be used in extensions. Instead, when developing extensions in AL, use the external methods of codeunit 425 Data Compression. The approach is similar.

**Comment by thloke** [comment]
dnpb is correct. Closing as that is the right answer.
