### ISSUE TITLE
FieldType::Enum does not exist and IsEnum() missing for Variant. #5998

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6940]
Ref. #5998 posted two years ago that was closed without discussion or a fix.

IsEnum() is also missing for Variant.

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by pri-kise** [comment]
Changelog mentions, that this will be added for Runtime 12.0
https://marketplace.visualstudio.com/items/ms-dynamics-smb.al/changelog#user-content-new-fieldref.isenum-method
