### ISSUE TITLE
Enum caption with ampersand (&) not displayed

### ISSUE THREAD

**Issue by JoelJame5** [microsoft/AL#6941]
Enum caption with ampersand is not displayed correctly, see below
![EnumCaption](https://user-images.githubusercontent.com/27202678/154926607-fd166ebc-3f87-415f-8696-62133acc7133.gif)

![image](https://user-images.githubusercontent.com/27202678/154926758-2296a465-3c91-4d6a-9748-8abff829473a.png)

The issue persist in BC19

**Comment by nndobrev** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
