### ISSUE TITLE
features parameter

### ISSUE THREAD

**Issue by deadmouse** [microsoft/AL#6944]
I know this repository is not for asking questions, but this is a question related with the AL compiler. 

When running alc.exe there is a parameter called "features". It says: _/features: List of feature flags._

How to use this parameter? There is no documentation explaning this parameter. Thanks.

**Comment by dnpb** [comment]
I would guess it corresponds to the `features` key in `app.json`:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files

**Comment by thloke** [comment]
@dnpb is correct.
