### ISSUE TITLE
All Watch to Inspect FilterGroup on Record

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6947]
**1. Describe the bug**
Not sure this qualifies as a bug, more a suggestion for the AL Language debugger. Currently if you watch a record, you can see the filters, for only one filtergroup - the one which the record is on, see below.
![image](https://user-images.githubusercontent.com/16603906/155239302-b0fc2eaf-cbe7-4a23-9c0d-6346645b41dc.png)
It would be incredibly amazing if I could in some fashion cycle the fitlergroups so that I can see what is in others, e.g. in this case 4. Not being able to do this means I have to insert code to switch the filtergroups just so I can inspect them all.

**2. To Reproduce**
Steps to reproduce the _behaviour:_

1. Debug anything with a record variable
2. Add watch.
3. Try and access any filtergroup other than the one currently set.
4. Fail.

**3. Expected _behaviour_**
Some way to expand the filtergroup option and see what filters are set in differing filter groups.

**4. Actual _behaviour_**
None.

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: 1.64.2
- Business Central: 19.3
- List of Visual Studio Code extensions that you have installed: Let's just say none since it's irrelevant for this.

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

**Comment by dnpb** [comment]
Extremely agreed :-)

**Comment by nndobrev** [comment]
Hi @mjmatthiesen ,
I would agree that it sounds like a good idea, however we are focusing the activity of this repository on addressing issues related to the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by mjmatthiesen** [comment]
So expanding the AL debugger, which is part of the development tools, to see all filtergroups, is not related to the development tools?

**Comment by nndobrev** [comment]
Hi @mjmatthiesen, 
I haven't said it is not part of the development tools- it definitely is. However, it is not an issue but a feature request. I agree it is a good idea and I believe other people of the community will be happy to see it as part of the debugger, but in order to get traction it should be listed on https://aka.ms/BusinessCentralideas, where it has better visibility and collect votes. This helps us to plan our work according to the communities needs.
Thank you!
