### ISSUE TITLE
Sorting on a Temporary Table's Flowfield is not possible.

### ISSUE THREAD

**Issue by bssi-danielf** [microsoft/AL#6948]
### Summary
Hi, I am creating a new ticket in regards to this /issues/5151, as mentioned we should do in the last comment by @atoader in that closed issue.  

To summarize: when a `FlowField` is calculated and then used for sorting, there is no issue, so long as the table is NOT declared as `temporary`. 

But when we try the same code with the table declared `temporary`, we get the following error instead: 
![image](https://user-images.githubusercontent.com/56848245/155244294-9fb2c2a4-f648-42e7-8257-c365d4bf5eaa.png)

> "Sorting cannot be done based on the %1 field(s) in the %2 table"

This runtime error _does not seem_ like an intention error to me, as it is not very descriptive of the root problem, nor does it occur during compiling (where it could easily be determined to be in error). 

### To Reproduce
1. In a procedure create a temporary record
2. Calculate a flow field of that record (using `CalcFields`)
3. Sort on that flow field  (using `SetCurrentKey`) 
                                                              ^-- _This is where the error occurs when you debug_

This does not happen if the record isn't declared `temporary`

### Example
Here is a simple code example that demonstrates this issue:
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addlast("&Customer")
        {
            action(TestFlowFieldSorting)
            {
                ApplicationArea = All;
                Caption = 'Test Sort on Temp Record FlowField';

                trigger OnAction()
                var
                    // When the 'temporary' declaration is removed, there are no errors
                    tempCustomer: Record Customer temporary;
                begin
                    tempCustomer.CalcFields(TestComment);
                    tempCustomer.SetCurrentKey(TestComment, "No.");
                    tempCustomer.SetFilter(TestComment, '<>%1', '');
                    if tempCustomer.FindSet() then
                        repeat
                            Message('In ascending order, first comments are: "%1"', tempCustomer.TestComment);
                        until tempCustomer.Next() = 0;
                end;
            }
        }
    }
}

tableextension 50100 CustomerExt extends "Customer"
{
    fields
    {
        field(5800; TestComment; Text[80])
        {
            // A simple TEXT based flowfield
            // gets the first comment associated with each customer
            CalcFormula = LOOKUP("Comment Line".Comment WHERE(
                "Table Name" = CONST(Customer),
                "No." = FIELD("No."))
            );

            Caption = 'First Comment';
            Editable = false;
            FieldClass = FlowField;
        }
    }
}
```

Let me know if I am missing a simple property / declaration that would make the above code work. _(The `temporary` table declartion, the `SetCurrentKey`, and the ` FieldClass = FlowField` are hard to change in our solution)_ 

### Expectation
We are mainly looking for an answer.

**Does Microsoft plan to support sorting on a Temporary table's FlowFields in the future?** 

If not, is there documentation that outlines this limitation? In my research so far, I've only ever seen speculation by NAV users / developers that this is a limitation, and nothing from an official source. It would also be nice if this limitation was added to the AL compiler diagnostic messages.

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
