### ISSUE TITLE
Event request Codeunit 8618 Config. Excel Exchange

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#695]
Please can you add this event:

Codeunit: 8618 - Config. Excel Exchange?
Function: ExportExcel
Event: **OnBeforeExportExcel**(ConfigPackageTable)

If this event is created, than we can add our custom tables into the default export/import template when the customer download the template.

**Comment by AlexanderYakunin** [comment]
Yes, this is possible, will be added for next update

**Comment by bvbeek** [comment]
Thanks for this!
