### ISSUE TITLE
Misleading Error message when doing breaking changes in an app with dependants

### ISSUE THREAD

**Issue by michvllni** [microsoft/AL#6950]
Please include the following with each issue:

**1. Describe the bug**
We have two extensions:
- extension1 
- extension2 that depends on extension1

When doing a breaking change in extension1, the error message from the publish is misleading. 
It tells me that there is an error yet fails to tell me that this error occurs **after** extension1 was successfully published.
The error comes from extension2 which is still published in my database and relies on the old version of extension1.
This leads to the false conclusion that my publish of extension1 failed even if it succeeded.

**2. To Reproduce**

1. Create extension1 and extension2:

extension1:
app.json
``` JSON
{
  "id": "09252521-585e-4c73-87a2-412f613f6b35",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "19.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": false,
    "includeSourceInSymbolFile": false
  },
  "runtime": "8.0"
}
```
mytable.table.al:
``` AL
table 50100 MyTable
{
    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;

        }
        field(2; MyField2; Integer)
        {
            DataClassification = ToBeClassified;
        }
    }

    keys
    {
        key(Key1; MyField)
        {
            Clustered = true;
        }
    }
    procedure MyProcedure(Param1: Text; Param2: Text)
    begin

    end;
}
```

extension2:
app.json:
```JSON
{
  "id": "ec24d259-289e-4ccd-a5ad-20c1098bb37e",
  "name": "ALProject2",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "id": "09252521-585e-4c73-87a2-412f613f6b35",
      "name": "ALProject1",
      "publisher": "Default publisher",
      "version": "1.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "19.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": false,
    "includeSourceInSymbolFile": false
  },
  "runtime": "8.0"
}
```
mypage.page.al:
```AL
page 50100 MyPage
{
    SourceTable = MyTable;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(MyField; Rec.MyField)
                {
                }
                field(MyField2; Rec.MyField2)
                {
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(ActionName)
            {
                ApplicationArea = All;

                trigger OnAction()
                begin
                    Rec.MyProcedure('test', 'test');
                end;
            }
        }
    }

    var
        myInt: Integer;
}
```

2. Publish both of those extensions, result: ![extensionsBefore](https://user-images.githubusercontent.com/45660891/155324248-59e6c0fd-be7c-455f-a179-1f0a0017af33.png)

3. Do breaking changes in extension1 (in this example: remove one field from the table and remove one parameter from the procedure):
```AL
table 50100 MyTable
{
    fields
    {
        field(1; MyField; Integer)
        {
            DataClassification = ToBeClassified;

        }
    }

    keys
    {
        key(Key1; MyField)
        {
            Clustered = true;
        }
    }
    procedure MyProcedure(Param1: Text)
    begin

    end;
}
```

4. Increase the version in extension1 to 1.0.0.1 (Not needed, only for showcase purposes to show the app gets successfully published)

5. Publish extension1 again, the following error occurs: ![error](https://user-images.githubusercontent.com/45660891/155324561-31a218fb-6973-4ee8-9e54-0c81332ff259.png)
6. As we can see in the extension management, extension1 was successfully published and extension2 was completely removed: ![extensionsAfter](https://user-images.githubusercontent.com/45660891/155325310-ed9f2bf6-7bad-471a-b9b2-aaa0327d9b5a.png)

**3. Expected behavior**
I get a message that the publish of extension1 was successful and precise information what objects in what depending extension failed. Additionally, I expect some information that extension2 was removed because of these errors

**4. Actual behavior**
I get an error in the publish that indicates my publish of extension1 failed and get listed some objects without any information about where they belong

**5. Versions:**

- AL Language: v8.3.570094
- Visual Studio Code: 1.64.2
- Business Central: 19.4
- List of Visual Studio Code extensions that you have installed:
    - AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment]
Hi @michvllni, are these extension residing in the same workspace?

**Comment by michvllni** [comment]
Hi @nndobrev, yes the issue also occurs if both extensions are in the same workspace:
![image](https://user-images.githubusercontent.com/45660891/155511627-972fa2a8-e749-4b88-b438-06063076fbaa.png)

**Comment by kalberes** [comment]
@michvllni  
What is in your dependencyPublishingOption option in the launch.json?

**Comment by michvllni** [comment]
It is unset, so I guess it is "Default". That would explain it. If I set it to "ignore", it works. Thanks for the hint @kalberes

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
