### ISSUE TITLE
Folding with AL Language doesn't works as expected with #pragma warning statements

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#6952]
I opened [this issue at VSCode GitHub repository](https://github.com/microsoft/vscode/issues/143424), but seems its solution is that #pragma sentences don't start at first column when the code is formatted automatically.

-- 

When you need introduce a `#pragma warning` statement in a Business Central AL file to avoid some compiler warning, the folding/unfolding actions stop at this statement and doesn't works as expected.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5801847/154773264-2b483fa4-da25-486f-875e-bb7864f38283.png">

- VS Code Version:
Versión: 1.64.2 (system setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Fecha: 2022-02-09T22:02:28.252Z
Electrón: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. For example: create a tableExtension AL file with some new fields
2. Add a `#pragma warning` statement in one of them
3. Try to fold the entire `fields { ... }` block

**Comment by mjmatthiesen** [comment]
I can confirm this issue. You can work around it by making your own regions, but that's silly.

**Comment by kalberes** [comment]
As specified in the vscode repository response we do not support  it yet AL language specific semantic folding. Could be requested though.

**Comment by NKarolak** [comment]
This is a known, old bug, see also open issue #6530
