### ISSUE TITLE
Copy base report to custom report results in errors

### ISSUE THREAD

**Issue by mabricco** [microsoft/AL#6954]
Please include the following with each issue:

**1. Describe the bug**
Base reports are copied to custom reports. Multiple errors indicating functions don't exist in base application, when they do and are used by base(copied from) reports.

**2. To Reproduce**
Copy report 10075 Sales Order to custom report. Immediately encounter 50+ errors. 

``` AL
 SalesTaxCalc.AddSalesLine(TempSalesLine);
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Copy base report to custom report without errors.

**4. Actual behavior**
Multiple errors. Examples(there are many)-
'Codeunit "Sales Tax Calculate"' does not contain a definition for 'AddSalesLine'
'Codeunit Language' does not contain a definition for 'GetLanguageIdOrDefault'
'Codeunit SegManagement' does not contain a definition for 'LogDocument'
'Codeunit "Format Document"' does not contain a definition for 'SetLogoPosition'

**5. Versions:**

- AL Language: v8.4.586670
- Visual Studio Code:Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
- Business Central:19.3.xxxxx
- List of Visual Studio Code extensions that you have installed:
AL Language
### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
I do not understand this issue? Can you create a small sample project with a repro.

**Comment by mabricco** [comment]
[Copy Base report 10075.docx](https://github.com/microsoft/AL/files/8145014/Copy.Base.report.10075.docx)
Please look at attached file. I copied a base report to  Custom report and have many similar errors. 
This happens with 4 different reports that I copied from the Base application, pasted in custom file and the errors appear in only the custom file.

**Comment by kalberes** [comment]
I am sorry I still don't understand. Have you copied the report to a new project that has a reference to the base application project? Have you built the base application? The base application project due to a bug  (fixed for the next release) does not participate in P2P (project to project) resolution, thus it is treated as an app symbol set, meaning that it needs to be built that a project that references it to work.
