### ISSUE TITLE
Feature request: Open Source SDK for editing TXT and AL files.

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#696]
In our opinion, an open source project should be provided by Microsoft in order to effectively edit the TXT files (old and new structure) of Microsoft Dynamics NAV. If the community were to be involved, it would have the advantage that there would be a lot of new productivity tools around Dynamics NAV. Of course, it would be even better if the merge tool were also made available as open source. Thus, all tools around Dynamics NAV would be powered by the community.

**Comment by StanislawStempin** [comment]
We currently don't have any plans in expanding support for handling the "old" TXT files. However, we do have plans to engage the community in tools for the new development experience. If you already have ideas for tools for .al files you're welcome to send me a suggestion directly or file an issue on this forum.

**Comment by kylehardin6** [comment]
There is a VSCode extension for C/AL written by zodiacfireworks. I haven't messed with it much, but turning on that language after I had opened a text object export color-coded some of the syntax and intellisense has a lot of C/AL keywords.

**Comment by DominikDitoIvosevic** [comment]
All it does for now is syntax highlighting and the intellisense comes from vscodes default completion which I trink offers all identifiers present in the solution or maybe they have some heuristic.

**Comment by FSharpCSharp** [comment]
Well, I think there are already some possibilities for tools that require such an SDK.

A few typical applications:

* Code Analysis
* Finding conditions that never apply
* Reverse conditions to minimize the indentation
* Carrying out refactoring
* Code generation
* Code Smells detection and code policy application

**Comment by FSharpCSharp** [comment]
@StanislawStempin
I had a question about the old TXT files. You said there's no plan to do something like open source for this. But wouldn't this be an important step for the transition period in particular? At that time, when the RTC was launched, Microsoft released the Form Transformation Tool. Later, the complete source code was released. You can still find it [here](https://community.dynamics.com/nav/b/navericwauters/archive/2011/08/17/source-code-of-form-transformation-tool-published) today.

If the TXT files really are dying in the classical sense, then it would be good if the community at least had the appropriate tools for it. I guess Microsoft will sooner or later let the TXT tools die anyway. In the long term, this is the right step. But there are still older versions in use for smaller customers. For them, such an open source SDK would be very practical, especially in the course of changes and adaptations. Could you perhaps raise these points internally, that it would be very practical for the community to have access to these resources?

**Comment by StanislawStempin** [comment]
@FSharpCSharp - Code Analysis will be made available as a set of APIs from the compiler assembly. We do not plan to open source the compiler itself at the moment.

I'm not sure I understand your question about TXT files. We already release Txt2Al tool with every update. Are you asking for making that tool open source or for some new tools that would let you programmatically edit TXT files?

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
There seems to be a misunderstanding here. I am aware that Microsoft will not publish the new AL compiler as Open Source. But that's not what I was worried about. There are a number of PowerShell tools to process the classic text files from Dynamics NAV. These are contained in the "Microsoft.Dynamics.Nav.Model.Tools" PowerShell DLL. These tools will no longer be needed in the future when the complete development is converted to the new AL framework. Therefore, my suggestion was that these tools should be made available to the community as open source. Despite the new development environment and further developments, many customers still have old versions for which these tools could be helpful. If these would then be under an open source license, the community could, for example, extend the merge tool there to include the missing object types Form and Dataport. These are no longer officially supported by Microsoft. Instead, you have to fall back on the age-old merge tools, or third party products.

**Comment by StanislawStempin** [comment]
Thank you, that clarifies a lot. I will discuss this topic internally and see what we can do.

**Comment by StanislawStempin** [comment]
After internal discussion we reached a decision not to open source the "old" tooling. We depend on the code from other Microsoft product, which is not open sourced and therefore we will not be able to open source it ourselves.

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
Thanks for the information. I've only looked at this once. On [StackOverflow ](https://stackoverflow.com/questions/8750018/net-dll-references-dependency-checking-utility)I found a way to check this with the Windows SDK. The only external dependencies I can find are included with the Microsoft.Xrm.SDK. There are no other dependencies on other products. The Xrm SDK is also exclusively included in the Microsoft.Dynamics.Nav.Model.Tools.dll.

If it really only fails because of this part, it might be possible to place the other DLLs under an open source license ("Microsoft.Dynamics.Nav.Model.Model.TypeSystem.dll","Microsoft.Dynamics.Nav.Model.dll","Microsoft.Dynamics.Nav.Model.Parser.dll").


These are self-contained and have no references to external products.

**Comment by JW1000111** [comment]
**@StanislawStempin**
We also often have to merge our customers to new NAV versions. Until now our company has to do this manually or with the help of old third party products. So we would really appreciate it, if the DLLs got open sourced. In doing so, we should be able to use these Tools and extend them if needed (e.g. supporting the object types Form and Dataport), so that the upgrade process of our customers with old NAV versions to newer versions could get more automated.

So if the old C/AL format won't be longer supported anyway, then it would be great, if the community could take care of these tools. Then they would not extinct with 2018 R2.

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
Thanks for the information. As it looks like others also want to use an SDK to change the text files (@JW1000111). Now I have to ask a very stupid question: If parts of the DLL are dependent on other non OpenSource products, does that rule out a release completely? I think it would be enough for Microsoft to provide the base that can parse and edit TXT files, if they don't have dependencies that prevent it. In addition, your statement suggests that the implementation has dependencies that may not exist in the future. Can you maybe talk about that next time? There is always some solution, and I think the community will play a much bigger role for Microsoft in the future. And from my point of view, that would be a very important step in that direction.

**Comment by esbenk** [comment]
We use some code from another MS product in our assembly. That code is not open sourced.

**Comment by JW1000111** [comment]
@esbenk
Wouldn't it be possible to open source just the code of the assembly, not the code from the other MS product? I'm sure just that could already help the community a lot.

**Comment by pborring** [comment]
While this is a fair request, we have not invested in this in the 4 years since suggested, nor do we plan to. Thus I will close the suggestion (i.e., won't fix), but thanks for initially providing feedback on this.
