### ISSUE TITLE
Lookup field "Item Reference No." on "Sales Order Subform" do not refresh totals

### ISSUE THREAD

**Issue by mcorvaisier37** [microsoft/AL#6960]
Hi,

I have a problem with totals on sales order subform when i use lookup on field "Item Reference No.".

Reproduce steps :  

Initial state :
<img width="994" alt="1 State" src="https://user-images.githubusercontent.com/90349833/156148723-07157811-f96b-4e6b-b39d-b6f5aedb00fa.png">

On the second line i use lookup on "Item Reference No." field to change item : 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/90349833/156147859-f48875ce-d477-4c80-9fc6-eeadb428e862.png">

Of course Unit price is refresh but totals are not refresh.

If i update price of this line, totals refresh but old amount is cumulated :  
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/90349833/156147986-365f8e52-d611-4b48-96c9-24f84771ce34.png">

This problem impact only lookup. if i use validate it's ok because there is call of function : DeltaUpdateTotals

**Comment by nndobrev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
