### ISSUE TITLE
Native xml schema validation

### ISSUE THREAD

**Issue by markkuventoifa** [microsoft/AL#6964]
We should have native support for xml schema validation.

Likewise
https://docs.microsoft.com/en-us/dotnet/api/system.xml.schema.extensions.validate?view=net-6.0

**Comment by markkuventoifa** [comment]
Just found these to investigate:

/// <summary>
/// Provides helper functions for xml validation against a schema.
/// </summary>
codeunit 6240 "Xml Validation"
codeunit 6241 "Xml Validation Impl."

**Comment by pri-kise** [comment]
I understand you request and I would love, if we get more native support. This belongs more to https://aka.ms/bcideas, since this issue here will be closed.

**Comment by navdotnetreqs** [comment]
> Just found these :
> 
> /// Provides helper functions for xml validation against a schema. codeunit 6240 "Xml Validation" codeunit 6241 "Xml Validation Impl."

Unfortunately these work very very poorly, since they only return the first validation error and then crash - why could we not at least get a list of all validation errors, since that's how the C#-implementation works.. ?

**Comment by markkuventoifa** [comment]
Yes. Done some tests and found them being useless for production.
