### ISSUE TITLE
Referencing a record array from the protected vars section as a field expression on a page extension makes the client crash 

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6965]
Please include the following with each issue:

**1. Describe the bug**

On the "Sales Order Statistics" page, the record TotalSalesLine is part of the protected vars, so we expect to be able to use this variable on page extensions. The compiler allows us to do so and successfully publish. However, when running the webclient (e.g. accessing the 'Statistics' page on a sales order, the client crashes)

**2. To Reproduce**

Create a page extensions on "Sales Order Statistics" that uses TotalSalesLine[1].whateverfield as source expression for a new field.

```
pageextension 71096736 "ESCB Sales Order Statistics" extends "Sales Order Statistics" // 402
{
    layout
    {
        addafter("TotalSalesLine[1].""Gross Weight""")
        {
            field("ESCB TotalSalesLine1 Net Weight"; TotalSalesLine[1]."ESCB Net Weight");
            {
                ApplicationArea = All;
                Caption = 'Net Weight (Item Unit)';
                DecimalPlaces = 0 : 5;
                Editable = false;
                Importance = Additional;
                ToolTip = 'Specifies the total net weight (defined on the item unit of measure) of the items in the sales document.';
                // Visible = false
            }
      }
}
```
The above makes the client crash.

As a temporary workraound, we made use of intermediate variables instead.
```

pageextension 71096736 "ESCB Sales Order Statistics" extends "Sales Order Statistics" // 402
{
    layout
    {
        addafter("TotalSalesLine[1].""Gross Weight""")
        {
            field("ESCB TotalSalesLine1 Net Weight"; TotalNetWeight[1])
            {
                ApplicationArea = All;
                Caption = 'Net Weight (Item Unit)';
                DecimalPlaces = 0 : 5;
                Editable = false;
                Importance = Additional;
                ToolTip = 'Specifies the total net weight (defined on the item unit of measure) of the items in the sales document.';
                // Visible = false
            }
      }

    trigger OnAfterGetRecord()
    begin
        TotalNetWeight[1] := TotalSalesLine[1]."ESCB Net Weight";
    end;

    var
        TotalNetWeight: Array[3] of decimal;
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central: Version: US Business Central 19.4 (Platform 19.0.35391.36082 + Application 19.4.35398.35925)

**Comment by kalberes** [comment]
Looks like a runtime issue. The compiler works as expected.  
The best to be fixed in a  timely manner is to create a request for hotfix.
Official answer:
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)

**Comment by fvet** [comment]
Created support request 2203160040008335
