### ISSUE TITLE
AA0225 should check actions as well

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6967]
IMHO, warning [AA0225](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0225) is incomplete:
> You must specify a caption in the Caption property for Fields that exist on page objects.

It should also check the actions.

**Comment by kalberes** [comment]
Thanks. It is a good idea, please log it in bcidea.

**Comment by NKarolak** [comment]
Please vote: https://experience.dynamics.com/ideas/idea/?ideaid=0e17aa87-59a0-ec11-826d-0003ff45e043
