### ISSUE TITLE
AL extension version for Visual Studio Code cannot be used with the specified server.

### ISSUE THREAD

**Issue by albertqm93** [microsoft/AL#6968]
Good morning,

I've installed the newest version relating to Business Central 2022 release wave 1.
I'm a partner developer, therefore I've tried to publish an extension to my new environment, but I couldn't succeed since I think the compiler is outdated.

I'm using [AL Language](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al) extension from Visual Studio Code.

I attach an [image](https://ibb.co/qD6wt2C) of the error I've get.

Please I would need to know when the AL Language compiler will be updated to the referred new version.

Thanks in advance,
Albert.

**Comment by HegedusZsolt** [comment]
Same here. Please update the AL Language extension, because we can not publish our app right now. Appsource validation from 19.0 to 20.0 failed and we are not able to correct our app because of the missing proper AL Language extension.

**Comment by kalberes** [comment]
You should be using the vsix from the preview based Dvd. The version of the vsix for the new version of BC will only be released when the product is released.

**Comment by kalberes** [comment]
We have internal builds and there the vsix packages are available. We cannot release something that we are still working on.
The 20.x version is developed in parallel with the server for the 20.x version.

**Comment by albertqm93** [comment]
Oh okey...
How can i get this internal builds?
Sending a ticket?

thanks!

**Comment by kalberes** [comment]
@albertqm93 
The vsix should be part of the preview: https://yzhums.com/10601/?amp=1

**Comment by NavDeb** [comment]
@albertqm93 Did you get anywhere with your ticket?

**Comment by albertqm93** [comment]
> @albertqm93 Did you get anywhere with your ticket?

i'm still waiting xd..
