### ISSUE TITLE
BC20 Upgrade is failing with AS0026 due to "business chart type"

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#6969]
**1. Describe the bug**
BC20 Upgrade is failing due to "business chart type"
our app validation is failing due to the move of enum "business chart type" from base app to system app.

**2. To Reproduce**
1. Create a new app (based on bc19) with just this codeunit:
``` AL
codeunit 50100 BusinessChartBugDemo
{
    trigger OnRun()
    var
        bct : Enum "Business Chart Type";
    begin
        OnDemoEvent(bct);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnDemoEvent(bct: Enum "Business Chart Type")
    begin
    end;
}
```
2. Compile (as v1).
3. Change Version (to v2).
4. Setup AppSourceCop to use v1 for breaking change check.
5. upgrade app to bc20 (change application + platform + downoad symbols)
6. compile

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
No error, just use the "Business Chart Type" from the other extension

**4. Actual behavior**
Error Occures:

error AS0026: The type or subtype of 'ChartTypePar' has been modified from '__MissingTypeSymbol__' to 'Enum "Business Chart Type"'. This is not allowed in events and external procedures because it will break dependent extensions.

**5. Versions:**

- AL Language: 9.0.8.54472
- Visual Studio Code: 1.65.0
- Business Central: 19.5.36567.36969 + 20.0.37023.0
- List of Visual Studio Code extensions that you have installed:
  - allanguage

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by qutreson** [comment]
@ChrisBlankDe - Can you share a project that reproduces the issue? How did you set up your AppSourceCop.json? What is the baselinePackageCachePath that you are using and which packages does it contain?

**Comment by ChrisBlankDe** [comment]
I've created a Demo: [BusinessChartBugDemo.zip](https://github.com/microsoft/AL/files/8204555/BusinessChartBugDemo.zip)
Just download symbols and try to compile. above mentioned Error will occur.
 AppSourceCop.json:
```json
{
    "version": "1.0.0.0"
}
```
settings.json
```json
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${AppSourceCop}"
    ],
    "al.ruleSetPath": ".vscode/appsourcecop4pte.ruleset.json",
}
```
The Ruleset will just hide warnings/errors  which are not relevant for this issue or needed to to compile an pte with appsourcecop.

**Comment by qutreson** [comment]
Thank you for the package, I can reproduce the behavior you are describing after editing the AppSourceCop.json as follows:
```
{
    "version": "1.0.0.0",
    "baselinePackageCachePath": "./.alpackages"
}
```

Your project appears to be missing the required dependencies for the baseline in order for the app to compile (this is surfaced as AS0091)

```
AS0091 - One or more dependencies of the previous version of the extension could not be found in the baseline package cache folder. Details: error AL1022: A package with publisher 'Microsoft', name 'System', and a version compatible with '1.0.0.0' could not be found in the package cache folder 'c:\Users\qutreson\Downloads\BusinessChartBugDemo\BusinessChartBugDemo\./.alpackages'
error AL1022: A package with publisher 'Microsoft', name 'Application', and a version compatible with '19.0.0.0' could not be found in the package cache folder 'c:\Users\qutreson\Downloads\BusinessChartBugDemo\BusinessChartBugDemo\./.alpackages'
```

Can you try to include the dependencies required (Application, Base Application, System Application, System) by the baseline version to the folder set as baselinePackageCachePath? 

This should fix both AS0091 and AS0026 - the type of the parameter type bct would then be resolved instead of being __MissingTypeSymbol__.
