### ISSUE TITLE
Cannot obsolete views on a pageextension

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#6970]
Please include the following with each issue:

**1. Describe the bug**
It is not possible to add the `ObsoleteReason`, `ObsoleteState` and/or `ObsoleteTag` properties to a `view` on a `pageextension` even though these properties are available for a `view`.
During **publish** an exception/error occurs.

**2. To Reproduce**

1. Create a `view` on a `pageextension` object (see sample snippet below).

``` AL
pageextension 50100 customerlistext extends "Customer List"
{
    views
    {
        addlast
        {
            view(MyView)
            {
                Caption = 'My Great View';
                ObsoleteReason = 'The base page will be removed so we remove the view of the page extension as well.';
                ObsoleteState = Pending;
                ObsoleteTag = '1.1.0.0';
            }
        }
    }
}
```

2. Compile the app, this is successful.
3. Try to publish, this fails with the following error message:
```
[2022-03-08 10:39:17.19] Publishing AL application using launch configuration 'Your own server'.
[2022-03-08 10:39:17.54] Publishing package to tenant 'default'
[2022-03-08 10:39:17.55] Targeting server 'http://apx-next', server instance 'BC' and tenant 'default'.
[2022-03-08 10:39:17.55] Using user name and password authentication. User name used is: '123'.
[2022-03-08 10:39:17.57] Sending request to http://apx-next:7049/BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2022-03-08 10:39:21.11] The request for path /BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: One or more errors occurred.
Failure while emitting metadata for object:'PageExtension customerlistext'
Unexpected value 'ObsoleteReason' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.PropertyKind'
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
An extension that contains a `pageextension` with an obsoleted `view` can be published.

**4. Actual behavior**
An extension that contains a `pageextension` with an obsoleted `view` cannot be published.

**5. Versions:**

- AL Language: v9.0.587938
- Visual Studio Code: 
```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z (5 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
- Business Central: Version: W1 20.0 (Platform 20.0.36953.0 + Application 20.0.37023.0) (but also on BC19 installations)
- List of Visual Studio Code extensions that you have installed: N.A.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by NKarolak** [comment]
Have you tried to simply delete the views? Since your views cannot be extended, this would not be a breaking change, if I'm not mistaken.

**Comment by rvanbekkum** [comment]
If the AppSourceCop does not complain, then that would be fine, will check. 😊 Still, I think there is an issue here, it should either allow the obsoletion properties and work or disallow them and give a compilation error.

**Comment by kalberes** [comment]
This is bydesign for now. You can ask for it on bcideas.

**Comment by rvanbekkum** [comment]
@kalberes Could you please resolve the bug though? The compiler should disallow the properties instead of a successful compilation, not only giving an error at the point that someone publishes the app.

**Comment by kalberes** [comment]
We have triaged it and it was rejected as a bug fix. We have no support for Obsoletion on properties for views. This is a feature that has to be designed, runtime support added, services updated etc.

**Comment by qutreson** [comment]
We added support for obsoleting page extensions and customizations from version AL compiler version 9.0.598294
