### ISSUE TITLE
Answer for kalberes

### ISSUE THREAD

**Issue by albertqm93** [microsoft/AL#6975]
> You should be using the vsix from the preview based Dvd. The version of the vsix for the new version of BC will only be released when the product is released.

Thanks for the information, but I don't have the DVD because it's not released right now. 

The problem is, if the changes of the BC20 breaks functionalities of my all extensions of my partners I cannot modify the code until the the product of BC20 is released?

That's not a solution...

_Originally posted by @albertqm93 in https://github.com/microsoft/AL/issues/6968#issuecomment-1063875943_

**Comment by dnpb** [comment]
should be a reply to #6968 not a new thread
