### ISSUE TITLE
September Release

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/AL#698]
Hello,
We have been facing a few issues after connecting our Visual Studio AL code with September Release and downloaded the Symbols.

Below are the steps we followed.
1. Installed Docker on the VM
2. Pulled navdocker.azurecr.io/dynamics-nav:devpreview-finus with ClickOnce Manifest
3. Downloaded the Certificate from the Manifest link generated
4. Configured the Certificate in the Root Authority
5. Imported our Developer License, with the permission range assigned for our App
6. In Visual Studio Code - launch.json changed following things
  a. server with the hostname given by Docker
                        "server": "https://91c368115ee9",
			"serverInstance": "NAV",
			"authentication": "UserPassword"
7. Changed the following this in app.json
  a.  "application": {
    "version": "10.0.0.0",
    "locale": "us"
  }

Downloaded the symbols

In all the objects we have created and where ever Standard NAV objects are referred Visual Studio Codes shows error
![image](https://user-images.githubusercontent.com/17919266/30612851-f60bd6f2-9d53-11e7-89a3-59f2d184b15f.png)

Also when we try to define any variable which refer to standard NAV, the **dropdown list doesn't show any standard NAV objects name** but indeed displays all the objects name created in the extension.

We can browse the webclient, perfectly without any issues.

Any idea or suggestion on what could be the possible reason and how to resolve this.

**Comment by MikeGlue** [comment]
I'm almost positive the version should be set to 11.0.0.0 in the September preview.

Regards,

Mike Glue


Sent from my Android device

________________________________

**Comment by anwar0206** [comment]
Hi @MikeGlue, thanks for the point, we do tried that too.. But same issue with the symbols.
Everytime, we start VS Code, it ask to download the Symbols.. Before downloading the symbol VS Code is showing Object there but the moment we download the symbols, VS cannot find Std. NAV Objects and gives that error.

**Comment by MikeGlue** [comment]
Are you using the latest version of the AL code extension? Don't remember the version number (it's 0.9.something) but I've had that issue when I was using an older version of it. If you launch the landing page desktop shortcut within the September preview vm, then at the bottom there is a link to get the latest extension. Load that in your local vs code and hopefully that will work.

Regards,

Mike Glue


Sent from my Android device

________________________________

**Comment by freddydk** [comment]
Did you deploy the VM manually or used http://aka.ms/navdeveloperpreview?

**Comment by anwar0206** [comment]
Hi Mike,

Thanks for point out, after we install the 0.9 extension the issue got resolved.
