### ISSUE TITLE
Reserved Keyword Clash when using DotNet Libraries

### ISSUE THREAD

**Issue by IridiumWasTaken** [microsoft/AL#6980]
**1. Describe the bug**
If a .Net library is used that exposes functions with a name equal to that of an AL keyword, the compiler assumes that the AL keyword is meant, preventing the use of the function of the .Net library.

**2. To Reproduce**

1. Set BC to the OnPremise version to enable .Net libraries
2. Place MimeKit (https://github.com/jstedfast/MimeKit) in the .netpackages folder
3. Create simple codeunit trying to use MimeKit
4. Use a MimeKit function that is named "To".
5. Try to compile

``` AL
dotnet
{
    assembly(MimeKit)
    {
        type(MimeKit.MimeMessage; MimeMessage) { }
        type(MimeKit.MailboxAddress; MailboxAddress) { }
    }
}

codeunit 1 Test
{
    procedure Test()
    var 
          Message: DotNet MimeMessage;
          MailAddress: DotNet MailboxAddress;
    begin
          MailAddress := MailAddress.MailboxAddress('Bla bla', 'bla@bla.com');
          Message.To.Add(MailAddress);
    end;
}
```

**3. Expected behavior**
The compiler correctly identifies the method "To" of the MimeKit.MimeMessage Class and thus the code compiles.

**4. Actual behavior**
The compiler incorrectly decides to identify the keyword "To" and fails to compile as he does not find a function "Add" that can be invoked.

**5. Versions:**

- AL Language: v8.4.586670
- Visual Studio Code: 1.62.3
- Business Central: DE Business Central 19.3
- List of Visual Studio Code extensions that you have installed: AL Language, AL AZ Dev Tools

**Comment by IridiumWasTaken** [comment]
Just found out that using

`Message."To".Add(MailAddress);`

works. It's a bit confusing why one works and not the other, but it works.

**Comment by dnpb** [comment]
Quoting it makes it unambiguous that you want a member or other user-defined symbol, not a reserved keyword, hence why that fixes it I guess.

Was the error you got that the keyword `To` has no `.Add` member, or instead an error about the syntax?
