### ISSUE TITLE
The system function "Report.SaveAs" does not work with type "Xml" anymore

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#6985]
Please include the following with each issue:

**1. Describe the bug**
The system function "Report.SaveAs" does not work as expected since BC 20. An error always appears when the function is executed. 

**2. To Reproduce**

In the concrete example, a report is to be saved as xml and then downloaded. The report is a classic RDLC report. However, when executing the function, the following error always appears:

_**Report 50100 does not have a layout of type None.**_

In BC 19, on the other hand, the sample code works perfectly.

An example with all the trimmings can be found [here](https://github.com/FSharpCSharp/BC20_ReportSaveAsXml). There is a page included that triggers the action. There is also a demo report included.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
It must be possible for the user to save and download the report as xml. An error must not occur during the execution.

**4. Actual behavior**
A strange error message is displayed to the user.

**5. Versions:**

- AL Language: 9.0.592718
- Visual Studio Code: 1.65.2
- Business Central: Platform 20.0.37332.0 + Application 20.0.37400.0
- List of Visual Studio Code extensions that you have installed: Only the extension from Microsoft for AL development is installed.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by PooyaKharamesh** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
 
To open a support case, you can:
 
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by MikeEndes** [comment]
If you come across this error and have written your own report, make sure you have included the following line at the top of your report:
DefaultLayout = RDLC;
After the equal sign choose RDLC, Word, or Excel, depending on your report.
It seems in version 19 it didn't care, but in 20 it does matter.

**Comment by FSharpCSharp** [comment]
I have reported the error to Microsoft elsewhere. There it has also been fixed in the meantime and we were able to test the fix successfully with 20.1. So the above example now works again. Therefore, the topic has been settled for me
