### ISSUE TITLE
How to pragma warning disable AA0240 in XLIFF files

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6986]
Please include the following with each issue:

**1. Describe the bug**
Looking for a way to disable the AA0240 warning that is raised for XLIFF files.

**2. To Reproduce**

- Create a page with a field control:

```
field(DecimalDelimiter; DecimalDelimiter)
            {
                Caption = 'Decimal Delimiter', comment = 'NLB="Decimaal Scheidingsteken"';
                ApplicationArea = All;
#pragma warning disable AA0240
                ToolTip = 'This function is used to extract the Quantity "7" and the RestText 5449000000996 from 7*5449000000996', comment = 'NLB="Deze functie wordt gebruikt om de hoeveelheid "7" en de resttext 5449000000996 uit 7 * 5449000000996 te extraheren"';
#pragma warning restore AA0240
            }
```

- Package the project and create a nl-BE xliff file
- Enable the AppSourceCop
- Following warning is raised

`"The xxx.nl-BE.g.xlf 'Page 2230540225 - Control 3469240332 - Property 1295455071:target' must not contain email addresses or phone numbers.",
`

**3. Expected behavior**
Even by setting a `pragma warning disable` around the **AL** code, the compiler still complains on AA0240 for the **XLIFF** file. Question is how to disable this warning on XLIFF files?

**5. Versions:**

- AL Language: v8.4.586670
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
