### ISSUE TITLE
Unprocessible Entity Error While Publishing AL

### ISSUE THREAD

**Issue by jemenyu** [microsoft/AL#6989]
When I try to Publish, it gives me an error the specified extension is not published
![image](https://user-images.githubusercontent.com/95473931/160381734-cd5aafb5-7ebb-425b-ad11-b4112e8624ab.png)

**Comment by dnpb** [comment]
When you try to publish what? To which server, running which version of BC? From which version of the AL extension for VS Code? etc.

**Comment by jemenyu** [comment]
I am publishing an AL extension to an Oprem BC170

vscode

> When you try to publish what? To which server, running which version of BC? From which version of the AL extension for VS Code? etc.

Publishing an AL Extension to BC170 OnPrem, VScode version in image 
![image](https://user-images.githubusercontent.com/95473931/160386738-739f3360-707f-472e-a7ec-5e0d8edd5b8b.png)

**Comment by jemenyu** [comment]
Apparently i have restarted the BC Server and Extension has published successfully, 

Thank you @dnpb for your quick response
