### ISSUE TITLE
Runtime Error when use a Record variable as an dynamic expression for Enabled property in a page

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#6992]
**1. Describe the bug**

When you use a Record variable as an dynamic expression for Enabled property in a page, the CodeCops and the AL Compiler don't display any Error or Warning.

**2. To Reproduce**

When you use a Record variable as an dynamic expression for Enabled property in a page, the CodeCops and the AL Compiler don't display any Error or Warning... you can Build & Deploy the App...

``` AL
trigger OnAfterGetRecord()
begin
    if not SalesHeader.Get(Rec."Document Type", Rec."Document No.") then
        SalesHeader.Init();
end;
```

``` AL
action(Reopen)
{
    ApplicationArea = Basic, Suite;
    Caption = 'Volver a abrir';
    Enabled = (SalesHeader.Status <> SalesHeader.Status::Open);
    Image = ReOpen;
    Promoted = true;
    PromotedCategory = Category5;
    PromotedOnly = true;
    ToolTip = 'Permite volver a abrir el documento para cambiarlo una vez que se haya aprobado.';

    trigger OnAction()
    var
        ReleaseSalesDoc: Codeunit "Release Sales Document";
    begin
        ReleaseSalesDoc.PerformManualReopen(SalesHeader);
    end;
}
```

But when you open this page, a Runtime Error raises with a message like **The identifier 'SalesHeader.Status' could not be found.**

![image](https://user-images.githubusercontent.com/5801847/160836054-c7f53910-60df-48ae-8058-60673615ab6e.png)

At the moment, you can't either declare a Record variable as `[InDataSet]` to try solve this issue.
![image](https://user-images.githubusercontent.com/5801847/160835940-c0420e7a-a312-4cee-a3e9-1d2cea29ada8.png)

**3. Expected behavior**
An Error message at development time.

**4. Actual behavior**
No errors, no warnings, all is ok at development time.

**5. Versions:**

- AL Language: v8.4.586670
- Visual Studio Code: 1.65.2
- Business Central: ES Business Central 19.4 (Plataforma 19.0.35391.36227 + Aplicación 19.4.35398.36428)
- List of Visual Studio Code extensions that you have installed: N/A

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. We will keep this open to possibly be fixed in the future. Thank you for raising this concern.
