### ISSUE TITLE
HttpClient and TLS compatibility

### ISSUE THREAD

**Issue by VishalAg55** [microsoft/AL#6995]
Hi,

Currently I have trying to integrate a website with Business  Central 19 saaas.
The website doesn't have a SSL certificate, so I need to skip its verification when sending https GET request.

Earlier I used ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 to use TLS protocol while calling a webservices but currently I think the Business Central doesn't support the same.

Can anyone let me know a way to call 3rd party web services using TLS protocol.

Thank You.

**Comment by dnpb** [comment]
As this is more a question about what the platform provides, rather than a demonstrable issue with the AL language or compiler itself, I don't think it's on-topic.

**Comment by nndobrev** [comment]
Hi, this repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
