### ISSUE TITLE
Intellisense doesn't work with foreach statement

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6997]
When entering the line

```
foreach x in y
```

intellisense does not show any suggestions when entering the variables x or y.

Tested on AL Language v9.0.605172

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

**Comment by EmilDamsbo** [comment]
Still reproduces on the latest AL compiler. We should re-assess whether we want to accept or close this.
