### ISSUE TITLE
Error after installing CU 2 NAV 2017

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#70]
Hi all,
I installed the NAV 2017 CU 2 update on my VM which was created when Visual studio code preview was released. But I'm facing an issue with the web client. I cannot open any page on my web client since many errors appear. Also I am not able to publish my previous extension using visual studio code on this CU 2 update.  It gives me following error:
'Could not publish the package to the server. See Visual Studio Code debug console for more details.'
Kindly let me know if any new VM has to be installed in order to use the NAV 2017 CU 2 update along with visual studio code.
Kindly give a solution to this. Thanks in advance.

**Comment by StanislawStempin** [comment]
The new development tools are not supported in NAV 2017 (including the CU2 update). You need the new server version ('Tenerife') that is released with the NAV Developer Preview azure image.

**Comment by TinaMenezes** [comment]
Hi @StanislawStempin,
Thank you. I installed the new server version.
