### ISSUE TITLE
BC21 This AL extension version for Visual Studio Code cannot be used with the specified server. Please update the AL extension from the Visual Studio Code marketplace.

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#7002]
Hi there, 

I can't download symbols for the BC21
sandbox\21.0.39235.0\
VSIX has been installed from the container 
![image](https://user-images.githubusercontent.com/31474116/163769520-0ad3a1fa-c4a3-48e5-b426-ac0e555b3108.png)
The "version": "9.0.605172", 
It looks like the VSIX  is not actual?!

Please advice.

**Comment by nndobrev** [comment]
Hi, does it work with the vsix available in the marketplace?

**Comment by dkorinets** [comment]
Hi, the behavior exactly the same. 
It seems like the VSIX in the container older version than in the marketplace. 

MarketPlace-->
![image](https://user-images.githubusercontent.com/31474116/164615178-b723df45-41a8-4daf-8b6d-cab1e628fdf7.png)

VSIX from the BC21 US container--> 
![image](https://user-images.githubusercontent.com/31474116/164615270-04a926f4-62d3-4b16-8e0b-e05a47821d34.png)

**Comment by dkorinets** [comment]
Update 4/26/2022L 
The latest available BC21 container image has VSIX "version": "9.0.611415" (same as it is on the marketplace), but still symbol downloading does not work.
![image](https://user-images.githubusercontent.com/31474116/165231714-fb690c58-9568-42e7-94a3-6392fcea9af9.png)

**Comment by dkorinets** [comment]
hi, 

Any updates? 

Thank you

**Comment by freddydk** [comment]
In the above screenshots - the VSCode is sending requests to bc21-us and the container you are creating is called bc21 - is that on purpose?

**Comment by freddydk** [comment]
When I create a BC21 container and grab the ALLanguage.vsix from that - I get:
![image](https://user-images.githubusercontent.com/10775043/165703558-6c4b1ee5-f4d5-43ad-91cc-3d2a92bbe6c8.png)
version 10.0.608152 of the AL Language extension (which matches the server).
In the output above your .vsix supports server up until 9.1 - and since the server is 10.0, it rejects your vsix.

**Comment by freddydk** [comment]
I think I know what went wrong here...
The parameters used to create that container - do you specify **-usevsix (Get-LatestAlLanguageExtensionUrl)** in that?
Then it will download the marketplace version and use that instead of the one shipped.
The marketplace version matches version 20 - not 21.

**Comment by dkorinets** [comment]
hi Freddy, 

Thanks for the reply. 
"-usevsix (Get-LatestAlLanguageExtensionUrl)" oops :)  that was the reason.
Will pay attention to that next time. 

Thank you
