### ISSUE TITLE
Direct download for cicd

### ISSUE THREAD

**Issue by jnus** [microsoft/AL#7003]
Please include the following with each issue:

**1. Describe the bug**
I'm trying to use alc in a Github workflow, but haven't been able to find a suitable direct download. Currently using vscode marketplace (e.g. https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/9.0.605172/vspackage), however the API has an extreme rate limiter policy, making it unusable in e.g. a GitHub Action. 

Question - any way we could have a direct download of the vsix or portable zip?

**2. To Reproduce**

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by cr998** [comment]
Other way to donwload the vsix package is from artifact repository used in the proccess to create BcContainer, yo can try with this [/navcontainerhelper/ContainerHandling/Get-AlLanguageExtensionFromArtifacts.ps1](https://github.com/microsoft/navcontainerhelper/blob/ba1097c36448a23abb4d873992bbfbc13452a01b/ContainerHandling/Get-AlLanguageExtensionFromArtifacts.ps1)

**Comment by jnus** [comment]
Hi cr998 -  I can see that the artifact store is storage account/CDN. If I look at the Get-BCArtifactUrl, it seems that I get 500MB+ zip file with bunch of apps, zip files, sql backup file etc. Not the actual vsix or the alc compiler tool.

**Comment by thloke** [comment]
Hi, we don't support any other way of getting the VSIX apart from through the VSCode marketplace or the insiders build. Closing this issue as we don't plan to support any other way of getting the VSIX.

**Comment by jnus** [comment]
@thloke  - kan you elaborate on the insiders build - is that something public available? Makes perfectly sense only to expose the vsix through vscode marketplace. Ideally I would just want a portable version om the compiler/sdk, since this is for building CICD pipelines. Currently building a custom github action for setting up AL (https://github.com/marketplace/actions/setup-al). Any information is greatly appreciated!
