### ISSUE TITLE
Code language not supported or defined.

### ISSUE THREAD

**Issue by james-rich** [microsoft/AL#7007]
Please include the following with each issue:

**1. Describe the bug**
Using Code Runner to run the HelloWorld.al example and getting an  error "Code language not supported or defined."

**2. To Reproduce**

1. Create a new HelloWord development (Ctrl+Shift+P)
2. if required connect it to business central  
3. run the development using code runner

**3. Expected behavior**
Instance of business central to open in a browser

**4. Actual behavior**
get the error "Code language not supported or defined."

![image](https://user-images.githubusercontent.com/32300192/164261888-a570c464-ae8e-49ca-ae48-a9b4612db656.png)

**5. Versions:**

- AL Language: 9.0.6 05172
- Visual Studio Code: 1.65 - 1.66 (tried older version)
- Business Central: Version: GB Business Central 19.5 (Platform 19.0.36528.39121 + Application 19.5.36567.36634)
- List of Visual Studio Code extensions that you have installed: 
    - Code Runner: 0.11.6 - 0.11.7 (Also tried to roll back)
    - AL CodeActions: 1.0.18 
    - AZ AL Dev Tools/AL Code Outline: 3.0.31
    - Waldo's CRS AL Language Extension: 1.5.4

### Final Checklist
Disabling all other extensions except Code Runner and AL Language result in the same error!

**Comment by thloke** [comment]
This is an issue with code runner.  We have no integration with code runner.
