### ISSUE TITLE
F12 does not find the AL file that contains the definition

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7010]
**1. Describe the bug**
F12 for "Go to Definition" does not work. VSCode does not find the file if the AL file that contains the definition contains spaces in the name. This is happening on either file with spaces. Going to the definition by first listing all references through Shift+F12 and then selecting the function definition works as expected.
Files that do not contain spaces in the name do **not** have this problem.
Possibly some kind of URL-encoding issue (%20 = space)?

**2. To Reproduce**
This should be easily reproduceable on any AL project:
1. Open any AL object that contains a call to a second AL object. This second AL object must be in a AL file with a space in the name.
2. Go to the function call, where the other object is called.
3. F12
4. The file is not found.

**3. Expected behavior**
The file should be found.

**4. Actual behavior**
The AL language extension does not find the file. And error is thrown, similar to this:
Unable to open 'Codeunit%20xxxx%20Some%20Filename.al': File not found.

**5. Versions:**

- AL Language: 9.0.611415
- Visual Studio Code: 1.66.2
- Business Central: /

**Comment by EmilDamsbo** [comment]
I am unable to reproduce this issue in the latest release of the AL Language extension. Please try re-installing the extension and report back with further information if the problem persists. 

For reference, I successfully navigated to the following symbols:
```
Page "Countries/Regions"
Codeunit "Activities Mgt."
Codeunit "Sales-Post Prepayment (Yes/No)"
```

**Comment by EmilDamsbo** [comment]
I incorrectly presumed that DAL files would be the same as AL files in your own project; I am indeed able to repro this. Changing labels.

**Comment by HBerndV** [comment]
I also have the same problem:
![GoToDefinition](https://user-images.githubusercontent.com/39124617/164702158-b92e3a0c-6b03-4d28-9b9c-0ed494413563.png)

Versions:
AL Language: 9.0.611415
Visual Studio Code: 1.66.2

**Comment by kalberes** [comment]
On it.

**Comment by pborring** [comment]
Some additional context on Twitter
https://twitter.com/eHougaard/status/1517554573199564801?t=vvwRXCytZF2S1Nemgzi5Xw&s=19

**Comment by CBlasek** [comment]
> Some additional context on Twitter https://twitter.com/eHougaard/status/1517554573199564801?t=vvwRXCytZF2S1Nemgzi5Xw&s=19
> 
> _It also only happens on windows 11 for me. Vs code and Al version on windows 10 works fine. I am not sure that w11 is culprit, but possibly._

I made that comment on Twitter. More than happy to test if needed.

VSCode: 1.66.2
AL:9.0.611415
OS W11: 21H2 (22000.613)

**Comment by ivanrlg** [comment]
I also have the same problem:
GoToDefinition
![image](https://user-images.githubusercontent.com/21310111/165115910-510d7e0f-86ee-4852-8f84-0d7aa627da54.png)

Versions:
SO: Win 11 Pro, 22H2, 22598.200
AL Language: v9.0.611415
Visual Studio Code: 1.66.2

**Comment by kalberes** [comment]
AL VSIX version 9.0.615906  should have a fix for it.

**Comment by CBlasek** [comment]
I have updated to 9.0.615906 and this has not resolved my issue. I am still experiencing the same result. When I am in a file and I select a function and hit F12, it does not go to definition. When I view the errors/warning in the problems section, and select a warning/problem, it does not go to that section of code. It states it is unable to open that file.

**Comment by hemisphera** [comment]
> I have updated to 9.0.615906 and this has not resolved my issue. I am still experiencing the same result. When I am in a file and I select a function and hit F12, it does not go to definition. When I view the errors/warning in the problems section, and select a warning/problem, it does not go to that section of code. It states it is unable to open that file.

Cannot confirm. It works just fine for me now.

**Comment by CBlasek** [comment]
> I have updated to 9.0.615906 and this has not resolved my issue. I am still experiencing the same result. When I am in a file and I select a function and hit F12, it does not go to definition. When I view the errors/warning in the problems section, and select a warning/problem, it does not go to that section of code. It states it is unable to open that file.

After I recloned repo - it started to work. Thanks!
