### ISSUE TITLE
Missing XMLDOMNamedNodeMap

### ISSUE THREAD

**Issue by psomani-itadynamics** [microsoft/AL#7015]
Hi All,

I try to create a new codeunit , I am copy ( codeunit 10145 "E-Invoice Mgt." ) but send below ERROR.

DotNet 'XMLDOMNamedNodeMap' is missing 

**Missing function on data type**

'XmlNode' does not contain a definition for 'ChildNodes'
'XmlNode' does not contain a definition for 'Value'
'XmlNodeList' does not contain a definition for 'Item'
'XmlDocument' does not contain a definition for 'AppendChild'
'XmlDocument' does not contain a definition for 'ImportNode'
'XmlNode' does not contain a definition for 'Value'
'XmlNamedNodeMap' is not recognized as a valid type

**Business Central: US Dynamics NAV 20.0 (OnCloud)**

**Comment by dnpb** [comment]
You can't use DotNet stuff in the cloud. So if you copy a codeunit that uses it, from OnPrem, and try to use it on SaaS, such errors are expected. Even if you defeated them by referencing the assemblies you need in VS Code, you won't be able to publish to SaaS.

**Comment by thloke** [comment]
By design. You cannot use .net interop in SaaS.
