### ISSUE TITLE
Help Pane - About apps on this page

### ISSUE THREAD

**Issue by sthiesyaveon** [microsoft/AL#7016]
OnPrem on Platform version 20.0.37114.38150(same in SaaS 20.0.37114.39543 )

when you click on one of the links of the apps in the new help area - "About apps on this page"

the language in the link is not resolved in the right way.

If you have configured in the app.json

"contextSensitiveHelpUrl": "https://yourappurl.com/{0}/something/yourapp"
 
Then the link is: https://yourappurl.com/%7B0%7D/something/yourapp/

but it shoud be: https://yourappurl.com/en-US/something/yourapp/ 

The link in the "About this task or page" section is fine.

**Comment by pborring** [comment]
This is not in the AL compiler/tooling, but BC client. There is already a discussion on Yammer with the client team involved, so closing this entry
