### ISSUE TITLE
Not able to Merge excel cells

### ISSUE THREAD

**Issue by RathnakumarDTX** [microsoft/AL#7018]
Hi Team,

I am saving a file directly in excel format. There i required some columns Header need to be merged. So i wrote the below code but still getting the error as shown below. Kindly help and do the needful.

**Code written:**
local procedure MakeExcelDataHeader()
    begin
        CompanyInformation.GET();
        ExcelBuf.NewRow;
        ExcelBuf.NewRow;
        ExcelBuf.AddColumn('', FALSE, '', TRUE, FALSE, FALSE, '', ExcelBuf."Cell Type"::Text);
        
        ExcelBuf.SetCurrent(ExcelBuf."Row No.", 1);
        ExcelBuf.StartRange();
        ExcelBuf.SetCurrent(ExcelBuf."Row No.", 10);
        ExcelBuf.EndRange();
        ExcelBuf.CreateRange(HeaderCaption + Format(Today));
        
        ExcelBuf.AddColumn(HeaderCaption + Format(Today), FALSE, '', TRUE, FALSE, FALSE, '', ExcelBuf."Cell Type"::Text);
        ExcelBuf.NewRow;
    end;

**Error Message:**
A DotNet variable has not been instantiated. Attempting to call Microsoft.Dynamics.Nav.OpenXml.Spreadsheet.WorksheetWriter.AddRange in Table Excel Buffer: CreateRange

**Comment by dnpb** [comment]
This is not about static code analysis, nor is this a support channel - it's for issues in the AL language/compiler themselves, not how they're used. Check base code for how it uses Excel Buffer and these functions, as you must be missing doing some action.

**Comment by BazookaMusic** [comment]
Closing this because as mentioned this repo is for issues related to the AL compiler/language.
