### ISSUE TITLE
An application object of type '{0}' with ID '{1}' is already declared by the extension

### ISSUE THREAD

**Issue by apaGitHub** [microsoft/AL#7019]
Please include the following with each issue:

**1. Describe the bug**
I have sometimes one or two .al files that show in PROBLEMS:
An application object of type 'Codeunit' with ID '52005' is already declared by the extension 'XYZ' (1.4.20220426.0)'
An application object of type 'Codeunit' with name 'ABC' is already declared by the extension 'XYZ' (1.4.20220426.0)'
(where 'ABC' is then name of the Codeunit with ID '52005')

I do not have these declared elsewhere. 

They are able to compile and launch, publish without issue. And function in BC as expected.

**2. To Reproduce**
I open VS Code and click on a few open files. 
If I disable and reload, and re-enable and reload AL Language, the PROBLEMS will appear again after I click on some open files. 
I ran Extension Bisect and it indicated the error was with Code Spell Checker. I disabled this and the PROBLEMS still showed the errors on reload.
I then Disabled all installed extensions, reloaded VS Code and only enabled  AL Language. This then resulted in the same PROBLEMS being displayed.

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Not to show this as a PROBLEM, as it is not.

**4. Actual behavior**
Prior to the above, I has also uninstalled the extension, reinstalled it.
I has also uninstalled the extension with removing all data, unpublished it, increased the version number and then published it again.
I deleted all cache.
Same PROBLEMS

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: Version: 1.66.2 (user setup)
- Business Central: 19.5.36567.36634
- List of Visual Studio Code extensions that you have installed: Its a long list, and except for AL Language they are now all disabled. Do you still need them?

### Final Checklist

Please remember to do the following:

* Search the issue repository to ensure you are reporting a new issue
Similar issue was reported: An application object of type with ID is already declared when package solution #4955
(https://github.com/microsoft/AL/issues/4955)

* Reproduce the issue after disabling all extensions except the AL Language extension
I did, as noted above.

* Simplify your code around the issue to better isolate the problem

**Comment by apaGitHub** [comment]
Am I missing something on this issue documentation that would help anyone to provide feedback?

**Comment by gmooblahem** [comment]
> Can you try cleaning up your package cache path and see if that helps?

I also have this problem. How do I clean package cache path?

**Comment by apaGitHub** [comment]
by clean package cache path, do you mean to delete the symbols (under ./.alpackages)?

 I did this:  removed the path in settings, replaced the path in settings, downloaded symbols and have the same issue as presented.

I can get it to work for a while if I disable AL Language and reload vscode , then re-enable AL Language and reload vscode. this worked while then had vscode open yesterday. this monring, opened vscode  and the problems will re-present themselves

**Comment by kalberes** [comment]
Yes, I have meant cleaning the package cache path. If you could share a repro then we would be able to debug the issue.
Else, just from the symptom is almost impossible to find the root cause.
Is this a workspace with multiple projects? Are you propagating dependencies?  Are you sure you do not have two apps with the same symbol Id defined in your app references?

**Comment by apaGitHub** [comment]
Thanks. I went through a series of steps to eradicate the issue; not sure which one worked, or if it was in some combination of the steps. In case anyone else happens upon this, this was my process:

VSCODE ==> Settings ==> AL Language extension ==> Code Analyzers

I had ${PerTenantExtensionCop} in the User Settings along with ${AppSourceCop}. Another developer had mentioned they recalled some instance where they may cause conflict. Not sure of the source, but removed the ${PerTenantExtensionCop} in User Settings and then double-checked Workspace settings. This is what I ended up with.

User:
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"
        // "${PerTenantExtensionCop}"

Workspace:
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"

Deleted rad.json

Closed all open tabs.

File ==> Exit VSCODE

Open VSCODE.

The problems have not appeared since then. Over a day now, so assume something in there worked.

**Comment by DimosthenisMichalopoulos** [comment]
Solution for me was this : Just map the network drive to a specific letter of my pc ! because the folder i was opening was from a network location and vscode didnt like that . Solution page : https://www.365cycle.nl/dynamics/an-application-object-of-type-x-is-already-declared/
