### ISSUE TITLE
file.DownloadFromStream parameters ignored in Web client

### ISSUE THREAD

**Issue by acyvas** [Microsoft/AL#702]
Following parameters are ignored in function file.DownloadFromStream:
- DialogTitle
- ToFolder
- ToFilter

The only way I can affect extentsion of downloaded file, is assigning default file name with file extension to file name variable.
Maybe it makes sence to remove these parameters to avoid confusion?

**Comment by StanislawStempin** [comment]
The answer to #703 acutally covered this question. 
Both Download and Upload have certain parameters that are not supported by the web client.
Since the RTC client is still using these parameters we cannot remove them from the function siganture.

**Comment by acyvas** [comment]
Thanks for explanation looks fair. Can be closed.
