### ISSUE TITLE
Can not run reports without a layout anymore?

### ISSUE THREAD

**Issue by srenders** [microsoft/AL#7020]
**1. Describe the bug**
When you develop a report, without a layout and try to run it, the following error occurs:
_Report x does not have a layout of type Excel._ 

**2. To Reproduce**
Create a Report without a layout, for example:
```
report 50100 Test
{
    UsageCategory = Administration;
    ApplicationArea = All;
    Caption = 'Test Report';
    
    dataset
    {
        dataitem(Customer;Customer)
        {

            column(No_Customer; "No.")
            {}
            column(Name_Customer; Name)
            {}
        }
    }
}
```

Publish the app, and run the report.
The following error appears:
Report 50100 does not have a layout of type Excel.

**3. Expected behavior**
The request page should appear, and we should be able to export the dataset, even when no layout is available. This used to work in v19.

**4. Actual behavior**
The following error appears:
Report 50100 does not have a layout of type Excel.

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.66.2
- Business Central: BE Business Central 20.0 (Platform 20.0.37114.39877 + Application 20.0.37253.38055)

**Comment by dnpb** [comment]
I think this is a dupe, in which case the fix is to put `DefaultLayout = RDLC` in there even though you don't have/need one.

**Comment by dnpb** [comment]
possible dupe: https://github.com/microsoft/AL/issues/6985

**Comment by srenders** [comment]
Actually, when you create an RDLC layout for the report and then run it, you get this error:
_Report 50100 does not have a layout of type None._
Indeed, if you then add the following property: DefaultLayout = RDLC; it works again.
But this was also not required before v20.

And the error messages are very confusing.

It should, imho, be possible to create a dataset for a report and no layout, and still be able to run it and export the dataset to Excel (data only), to be able to see the dataset, before creating any layout.

**Comment by dnpb** [comment]
Yes, it is a bug, and such workarounds should not be required, and won't be once MS release the fix.

**Comment by qutreson** [comment]
This looks like a runtime issue. Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by srenders** [comment]
I'm sorry, but I wont file any support request on Partnersource or Collaborate or SAM. (I don't even have a SAM).

I mentioned it here. If you feel it's important to fix, then inform your colleagues and have it fixed. ;)
