### ISSUE TITLE
Error in Opening Page 99000886 "Subcontracting Worksheet" German Version, Codeunit 330 TemplateSelection

### ISSUE THREAD

**Issue by bokhim** [microsoft/AL#7022]
**1. Describe the bug**
There is an error in german Version of Codeunit 330. TemplateSelection, when there is no template data, resulting in a Page Error, opening Page 99000886 "Subcontracting Worksheet" in German Version.

**2. To Reproduce**

1. Switch to German Language in SaaS.
2. Go to Subcontracting Worksheet (Fremdarbeitenarbeitsblätter), it does not open in German version and an error comes up.

> Die Länge der Zeichenfolge beträgt 11, darf aber höchstens 10 Zeichen umfassen. Wert: For. Arbeit
>......
> Al-Aufrufliste: 
> ReqJnlManagement(CodeUnit 330).WkshTemplateSelection line 22 - Base Application by Microsoft
> "Subcontracting Worksheet"(Page 99000886).OnOpenPage(Trigger) line 10 - Base Application by Microsoft

The error translates to "For. Arbeit" is too long 11 characters. In the english Version it is "For. Labor" stands for Foreign Work.
The translation of Label LocalText000 in Codeunit 330 is too long for the second Option for inserting into ReqWkshTmpl.Name.

``` AL
procedure TemplateSelection(PageID: Integer; RecurringJnl: Boolean; Type: Option "Req.","For. Labor",Planning; var ReqLine: Record "Requisition Line"; var JnlSelected: Boolean)
    var
        ReqWkshTmpl: Record "Req. Wksh. Template";
        LocalText000: Label 'Req.,For. Labor,Planning';
    begin
        JnlSelected := true;

        ReqWkshTmpl.Reset();
        ReqWkshTmpl.SetRange("Page ID", PageID);
        ReqWkshTmpl.SetRange(Recurring, RecurringJnl);
        ReqWkshTmpl.SetRange(Type, Type);
        OnTemplateSelectionSetFilter(ReqWkshTmpl, Type);

        case ReqWkshTmpl.Count of
            0:
                begin
                    ReqWkshTmpl.Init();
                    ReqWkshTmpl.Recurring := RecurringJnl;
                    ReqWkshTmpl.Type := Type;
                    if not RecurringJnl then begin
                        ReqWkshTmpl.Name := CopyStr(Format(SelectStr(Type + 1, LocalText000)), 1, MaxStrLen(ReqWkshTmpl.Name));
                        ReqWkshTmpl.Description := StrSubstNo(Text99000000, SelectStr(Type + 1, LocalText000));
                    end else begin
                        ReqWkshTmpl.Name := Text002;
                        ReqWkshTmpl.Description := Text99000001;
                    end;
                    ReqWkshTmpl.Validate("Page ID");
                    ReqWkshTmpl.Insert();
                    Commit();
                end;
            1:
              .......
            end;
        end;
    end;
```

**3. Expected behavior**
The Page should open without error and initiate a worksheet template without errors. 

**4. Actual behavior**
The page breaks with an error message.

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.66.2
- Business Central:19 and newer.
- List of Visual Studio Code extensions that you have installed: none

**Comment by dnpb** [comment]
This seems like a base app bug, not an issue in the AL language/compiler. Maybe you could try at https://github.com/microsoft/AlAppExtensions/issues instead, but it seems off-topic here (and possibly there)

**Comment by bokhim** [comment]
Moved to https://github.com/microsoft/ALAppExtensions/issues/17511
