### ISSUE TITLE
CodeCop Warning AA0005 - false positive

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#7023]
hi guys, 

there is a little problem with the AA0005 warning.

sample code:
```

		   if true then begin
                        for i := 1 to 5 do
                            if true then
                                Message('Hello World');
                    end else begin
                        for i := 1 to 5 do
                            Message('Hello World');
                    end;
```

**Comment by dnpb** [comment]
Best to include a screenshot of which warning(s) do you get, on which line(s), and your BC/AL extension version.

**Comment by sschuh** [comment]
AL Language v9.0.615906

Example:
<img width="637" alt="1" src="https://user-images.githubusercontent.com/34685182/166653228-0a154580-e2e0-47a3-8093-18f834e1dcdc.png">

This one can be refactored to:
<img width="654" alt="2" src="https://user-images.githubusercontent.com/34685182/166653570-57094589-27f1-4d12-8a7f-5eb2cc21bb38.png">

But, if you want to solve the warning, this would and up in this one (error)
<img width="696" alt="3" src="https://user-images.githubusercontent.com/34685182/166654001-6851b2bb-707b-43bf-ae0a-2cff4d36fdad.png">

i can not remove the semicolon, because this would change the code behavior.
<img width="560" alt="4" src="https://user-images.githubusercontent.com/34685182/166654102-6879915a-8ad2-4c5d-9157-1507ec88454e.png">

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

For this case consider using [Pragma Warning Directive](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning).
