### ISSUE TITLE
BC20: Report 7390 "Whse. Calculate Inventory" with lot tracking and package tracking

### ISSUE THREAD

**Issue by KristofVervaeke** [microsoft/AL#7026]
I think there a bug in the procedure "InsertWhseJnlLine" of report 7390 "Whse. Calculate Inventory".

This procedure loops all warehouse entries an creates warehouse journal lines when there is inventory.
It sorts the warehouse entries by item, variant, ..., and lot number.
When there's inventory on the lot, a journal line is created and after the creation of the journal line, there a find('+').
With this find('+') BC jumps to the lot entry of the lot number to process, so not all warehouse entries are looped, which is good for performance.

But with this find('+') in combination with lot tracking and package tracking some packages can/will be missed.

Look at the following warehouse entries for an item sorted in the order procedure "InsertWhseJnlLine" uses:

| **Lot No.** | **Package No.** | **Entry No.** |
| --- | --- | --- |
|L1|P1|14|
|L1|P1|4|
|L1|P2|10|
|L2|P2|9|
|L1|P2|11|
|L2|P3|5|

The code finds lot L1 (entry no. 14) and creates an entry of lot L1 and package P1.
Then, by doing the find('+') BC moves to the record with entry no. 11 and continues its loop.
So the next record to procees is record 5 with lot L2 and package P3.

Lot L1 package P2 and lot L2 package P2 are skipped and are not inserted in the warehouse inventory journal.

**Comment by dnpb** [comment]
This repo is for bugs in the AL language/compiler itself, not uses of AL in the base app. You should probably file this as an application bug via Partner Source or equivalent.
