### ISSUE TITLE
contextSensitiveHelpUrl does not work with locales in "About apps"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/AL#7028]
**1. Describe the bug**
It seems that property contextSensitiveHelpUrl does not work in all scenarios on the pages. It works correctly in the **About this task or page** section, but not in **About apps on this page** section.

**2. To Reproduce**
1.  create new extension
2. use these properties in the app.json
```
"contextSensitiveHelpUrl":  "https://mysite.com/{0}/documentation/",
 "supportedLocales": [ "en-US", "cs-CZ],
``` 
3. create new Page
4. deploy the project
5. open new Page and Help
6. There are two sections  **About this task or page** and  **About apps on this page** 

**3. Expected behavior**
When I use link in both section it opens the url https://mysite.com/en-US/documentation/ or https://mysite.com/cs-CZ/documentation/ depends on locales

**4. Actual behavior**
In the section **About this task or page** the logic works correctly.
In the section **About apps on this page** locales are not used and link keep as it is https://mysite.com/%7B0%7D/documentation/

**5. Versions:**
Business Central: 20

**Comment by qutreson** [comment]
This seems like a web client issue. Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
