### ISSUE TITLE
AL Debug Extension: StatusCode:NotFound; ReasonPhrase:Not Found

### ISSUE THREAD

**Issue by rcverbeek** [microsoft/AL#7029]
Hi,

We are having troubles attaching our VSCode debugger to a remote process. This is our environment:

- We created an Extension to the Base Application. The platform version is 18.0.0.0 and the runtime is 7.2 The target is OnPrem
- We develop locally and are able to debug both the base app and our extension
- Once a week we publish and install our extension on a testserver. It will be published as 'DEV'

We would like to debug on the testserver. To do so we added a configuration in our local lauch.json:

```
"configurations": [
		{
            "name": "Attach to ADF-OFT-01 Test environment",
            "type": "al",
            "request": "attach",
            "server": "http://testserver",
			"port": 8049,
			"environmentType": "OnPrem",
            "serverInstance": "BC180",
            "authentication": "Windows",
            "breakOnError": true,
			"startupObjectId": 22,
			"startupObjectType": "Page",
			"launchBrowser": true,
            "breakOnRecordWrite": false,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            "breakOnNext": "WebClient"
        },
```
In VSCode we use Ctrl+F5 to publish the extension and start a debugging session with F5 and attach to the TestServer. However, the breakpoints are not hit.
On the testserver we can see these messages in the application log:

```
Message Failed request -- Method:GET; Url:http://testserver:8049/BC180/dev/signalr/start?clientProtocol=2.1&transport=webSockets&connectionData=[{"Name":"DebuggerHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAQ5oPd02yNEmMiXIsSdtfcwAAAAACAAAAAAADZgAAwAAAABAAAAAnR3khEDJQqjK%2FpPh5OBNJAAAAAASAAACgAAAAEAAAAI9bgHeBCw6dknhzJQLzsnM4AAAAAgK0pWpJxhHOW2jWMNwNuqlHmV6K1osXO3xnHWqNA7cKUugZcCTRXvN5ldg2GQFrfi1IJFy0fp0UAAAAF1Lp%2FIZ0AzipBZo%2Bawy9vNhiRTk%3D; StatusCode:NotFound; ReasonPhrase:Not Found; Token:
ProcessId: 10868
Tag: 00006NR
ThreadId: 79
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

I am not sure if this message relates to the debugging issue, We also tried to use the ip address instead of the servername, but to no avail. The firewall on the testserver has been disabled.

**Comment by kalberes** [comment]
Is debugging enabled on teh test server? I assume that DeveloperServicesPort in the server config is 8049 and is enabled. Also DeveloperServicesEnabled is true on this NST.

**Comment by rcverbeek** [comment]
Hi kalberes and lvlaanderen, sorry for the late response.

Debugging has been enabled on the test server, indeed listening on port 8049. Enable Developer Service Endpoint is enabled too.

The web client base url has value http://localhost:8080/BC180.

For a couple of days debugging is working now, on IP base.

I don't know why it's working now, maybe some restart on the server. In the eventlog we still see the error messages, so I guess it is unrelated.

**Comment by rcverbeek** [comment]
See comment above. Thanks for your input.
