### ISSUE TITLE
file.UploadIntoStream parameters ignored

### ISSUE THREAD

**Issue by acyvas** [Microsoft/AL#703]
Following parameters are ignored in Dialog of **file.UploadIntoStream** function:
- FromFolder
- FromFilter

FromFilter is quite important for user experience. Now anything I set, ends up with default filter.
See example below:
![image](https://user-images.githubusercontent.com/11752827/30682802-9ccdf8ac-9eb3-11e7-96e8-2fe577ecb86b.png)

![image](https://user-images.githubusercontent.com/11752827/30682807-a49d1b9e-9eb3-11e7-8c8e-50dd4e9975f0.png)

**Comment by lukzog** [comment]
See the msdn documentation: https://msdn.microsoft.com/en-us/library/dd301099(v=nav.90).aspx

Those parameters are not supported by the web client.
