### ISSUE TITLE
New semanticHighlighting - Function's begin-end in RED

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#7030]
Please include the following with each issue:

**1. Describe the bug**
Hi, 
Today I've found out that there were some changes to the Semantic Highlight, and the Begin End of the procedures, are now in red color!
I think that it is not good to use red coloring for something but Errors!
It can be changed? 

**2. To Reproduce**

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Something not Red or Orange

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/36199751/167091788-cca66509-5ebf-446e-a23e-87d23d621419.png)

**5. Versions:**

- AL Language:
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 10.0.619721
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

and

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.0.615906
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
You can disable this new vscode feature with this setting:

```json
{
    "[al]": {
        "editor.bracketPairColorization.enabled": false
    }
}
```

**Comment by thpeder** [comment]
Hi @f4n0,
The colors from the feature "editor.bracketPairColorization.enabled", are not some that we control, and the semantic highlighting feature that came with a recent update doesn't pick any colors either, it only classifies the text in the document. It is based on the color themes in VS Code that gives it the specific color.
Please have a look at [https://dev.to/amanhimself/how-to-configure-vscode-bracket-pair-colors-natively-3nl](https://dev.to/amanhimself/how-to-configure-vscode-bracket-pair-colors-natively-3nl)

**Comment by thpeder** [comment]
Can you provide a file with the code that reproduces the "unexpectedBracket"?

**Comment by dannoe** [comment]
I can change the color of begin and end only with the following setting: ``editorBracketHighlight.unexpectedBracket.foreground``. So I was thinking that the begin and end are recognized as unexpected brackets.

**Comment by JSebastianN** [comment]
> yes, this will put a bandaid but I still think there is an issue. I'm the only one?

No you are not alone, we need a fix of sorts IMO

**Comment by ajkauffmann** [comment]
Here is a simple fix:

The file al.configuration.json contains the full list of possible bracket begin & end combinations.

Add this line to list and bracket matching works again:

`["begin", "end"]`

Note the missing ; after end, that combination was not in the list while other combinations are existing with and without the semicolon.

The file can be found in: %userprofile%\.vscode\extensions\ms-dynamics-smb.al-9.0.615906 (for current version).

Tip for Microsoft: it seems that bracket matching is case insensitive and also does not really care about the semicolon. This set of brackets works fine for me. Maybe other people can try and see how it works for them as well and report here?

```
    "brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["begin", "end"],
        ["case", "end"]
    ]
```

**Comment by dnpb** [comment]
> Tip for Microsoft: it seems that bracket matching is case insensitive and also does not really care about the semicolon. This set of brackets works fine for me. Maybe other people can try and see how it works for them as well and report here?

Looks good to me too. Thanks!

MS, please review and simplify/fix the `autoClosingPairs` also - particularly the oddity that some of them have multiple duplicates / more than one line, per `open` tag, e.g. `"open": "case"` causing [this problem](https://github.com/microsoft/AL/issues/7040#issuecomment-1127510054).

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42332 and VS Code Extension Version 10.0.640052. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
