### ISSUE TITLE
Have the runtime help text indicate version instead of or alongside release wave.

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#7032]
**1. Describe the bug**
When I change the runtime and hover, I get info about the release wave. This doesn't really help, as I then end up having to search which release wave is which version.

**2. To Reproduce**
Steps to reproduce the behaviour:

1. Go to app.json
2. Hover over runtime.
3. Get "business central year release wave i
5. Find version number through search

**3. Expected behavior**
Tell me the version number. I'm not sure who is helped by release wave info, but since we need to enter version numbers elsewhere, this information does nothing for me.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/16603906/167180223-31671192-76f9-4a97-8648-d284801921da.png)

**5. Versions:**

- AL Language: Current
- Visual Studio Code: Current
- Business Central:Any
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by dannoe** [comment]
For me the best site is the german wikipedia page for BC:
https://de.wikipedia.org/wiki/Microsoft_Dynamics_365_Business_Central#Versionshistorie
Just klick ``Ausklappen`` (Unfold) under ``Versionshistorie`` and you get a nice table.

**Comment by kalberes** [comment]
Makes sense. The best would be to add an entry to the Ideas forum 
![image](https://user-images.githubusercontent.com/12760483/168292812-61e7715c-1a74-4440-8843-476e13fd4dba.png)
