### ISSUE TITLE
Report.Execute does not print in PDF in BC20

### ISSUE THREAD

**Issue by ViggoVll** [microsoft/AL#7033]
Please include the following with each issue:

**1. Describe the bug**
When i run a BC18 & BC19 the function Report.Execute produces a PDF, but when i run the same code on a BC20, the report comes out without any file extension like "File.pdf".
According to the tool tip of Execute, i should download a PDF to the users browser client.

![image](https://user-images.githubusercontent.com/82797917/167352292-efa38cf2-6896-46e8-8e1b-4a40235b2325.png)

**2. To Reproduce**
Run any report with a Report.Execute(Report::XXXX, '', RecRef).

![image](https://user-images.githubusercontent.com/82797917/167352629-c3b05eb0-59f5-4d06-a627-3a07b5796c8a.png)

**3. Expected behavior**
I expected it to download as a PDF like the other versions of BC.

**4. Actual behavior**
This is an example of what happens in a BC18 and a BC20 with the same code.

![image](https://user-images.githubusercontent.com/82797917/167353027-7cca2c6d-fecb-4e97-a680-a54b54cdd9d2.png)

**5. Versions:**

- AL Language: 9.0.615906
- Visual Studio Code: 1.67.0
- Business Central: Platform 20.0.37114.38150 - Application 20.0.37253.38230

**Comment by NKarolak** [comment]
The issue was already submitted on [Yammer](https://www.yammer.com/dynamicsnavdev/threads/1719913577250816) and is already in progress (it seems).

**Comment by kalberes** [comment]
This is a runtime issue, will be fixed in a next minor.

**Comment by fabio-nettis** [comment]
This bug seems to be **still present** in version 20.1.39764.39901. PDF's are downloaded without any file extension and a `_` instead of the missing extension.
