### ISSUE TITLE
Cannot publish due to license restriction

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#704]
I cannot publish from my local VS Code in September Update.
I can successfully download Symbols from the System and Can connect to the web Client from my local machine. 

What did I do to prepare:

- Obtained a license that contains D365 ID range
- VS Code has the latest AL Version
- I have uploaded the license file via the Development Environment and also made sure to save the license file into the database to replace whatever was there before.
- I have restarted the docker container to get the Service Tier to restart as well.

Still publishing Fails:
[2017-09-21 13:08:46.16] Sending request to https://navpre092017.westeurope.cloudapp.azure.com:7049/NAV/dev/apps
[2017-09-21 13:08:46.90] The request for path /NAV/dev/apps failed with code 422. Reason: Your program license does not allow you to publish 'Order Availability Line'.

What did I miss?

**Comment by DominikDitoIvosevic** [comment]
Are you sure the objects are in the right id range?

**Comment by DominikDitoIvosevic** [comment]
and have you specified the right ID range in app.json?

**Comment by RafaelKoch** [comment]
Pretty much, yes. The license is for Dyn365 app development and the allocated Object Range is 70101620-70101669.
I will try and double check if NAV picked up the correct permissions.
Also You mentioned the range should be put into app.json? Can You give an example how this is correctly formatted there?

**Comment by StanislawStempin** [comment]
Here's the snippet to add to app.json:
```
"idRange": {
    "from": 50100,
    "to": 50149
  }
```

**Comment by RafaelKoch** [comment]
OK thanks - I will try to add this and retry later today.

In the meantime I can confirm my license is actually runnning and includes the app range. For whatever reason I could not just create a page that would actally Display the License Permission... always showed a diagram and no way to switch to list view. I had to publish the page as WS and consume this from Excel. :-) Strange but also somewhat fun.
Whatever the reason, I am now 100% sure I should have permission.

**Comment by RafaelKoch** [comment]
OK, found the time to try right away. No luck, same error. Just to recap: I can and could compile, and afaik this idRange is used to stop me compiling, not publishing. Yet Publishing is what fails.
Any ideas?

**Comment by kalberes** [comment]
Have you checked the server's event viewer? Is there anything related to license issues?

**Comment by RafaelKoch** [comment]
Nothing I can spot; but there even be something? Isn't this all encapsulated in docker?

**Comment by RafaelKoch** [comment]
OK, it might yet be the license. 
Although License Permission says I have execute permission on my object range I actually cannot create any objects in classic development. So I will next ask our Administration to go and recreate the license file including Demo/Dev. Let's first see if this helps.

**Comment by kalberes** [comment]
You need Insert or indirect insert rights on a given application object in order to be able to publish .

**Comment by RafaelKoch** [comment]
Sounds reasonable to do in General but does not help in this case.  :-)
It actually was the license file. Admin pulled another one from PBSC - just the very same way we did last time :-( - and now I can publish. Looks like design rights are now included when You configure a Demo/Dev License.

**Comment by RafaelKoch** [comment]
Sorry for bothering You all, it was after all not an AL issue. 
Closed.
