### ISSUE TITLE
Event Parameter Issue.

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/AL#7043]
Dear Team

We are facing a lot of challenges in posting sales return and sales credit memo due to "IsHandled" is not declared with reference in the events. Please declare "IsHandled" variable under references in **codeunit 18435 "Reference Invoice No. Mgt."**.

For your References only.

**Orignal code in BC365:**
[IntegrationEvent(false, false)]

local procedure OnBeforeCheckRefInvNoPurchHeader(var PurchaseHeader: Record "Purchase Header"; **IsHandled**: Boolean)

**Please correct the the code like in events.**
[IntegrationEvent(false, false)]

local procedure OnBeforeCheckRefInvNoPurchHeader(var PurchaseHeader: Record "Purchase Header"; **var IsHandled**: Boolean)

**Comment by dnpb** [comment]
wrong repo - you want https://github.com/microsoft/AlAppExtensions/issues

**Comment by dnpb** [comment]
cross-posted at https://github.com/microsoft/ALAppExtensions/issues/18001
You should be able to close this one one, and please do so.
