### ISSUE TITLE
Events and Application Enhancement.

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/AL#7044]
Dear Team,

Please do the needful.

**Change Dimension Action short key from CTRL+SHIFT+D to ALT+D in Page 18322 "Pay GST".**
**Change Option fields _"Status", "Change Status",  "Quote Type"_ to Enum in Service Contract Header Table with extensible true.**
**Change Option fields _"Contract Status"_ to Enum in Service Contract Line Table with extensible true.**
**Provide fields "_OnValidate_" trigger handling events in Service Contract Header Table.**
**Make Enum "_GST Reason Type_" extensible true.**

**Comment by dnpb** [comment]
wrong repo - you want https://github.com/microsoft/AlAppExtensions/issues

**Comment by dnpb** [comment]
cross-posted at https://github.com/microsoft/ALAppExtensions/issues/18000
You should be able to close this one one, and please do so.
