### ISSUE TITLE
Delete through TestPage

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#7045]
**1. Describe**
If I'm not mistaken, it's still not possible to delete records using the test page. With ongoing improvements & enhancements of the app from the Microsoft side, tests are automated tests are the keystone for all companies...

We had an issue with our process that is started once the record is deleted by the user as there was a change from CZ localization. 
We could prevent it by creating a simple AL test, but without support for deleting records through the test page, we can not...

I found #3253 from 2018 that it's on your backlog

**Comment by thloke** [comment]
Hi, this is not in our immediate backlog, so we don't have an ETA on when this will happen. The best way to get traction on this is to post it on BCIdeas at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
