### ISSUE TITLE
Uploading UTF-8 encoded data from files into a controladdin is seemingly impossible

### ISSUE THREAD

**Issue by IridiumWasTaken** [microsoft/AL#7050]
# Description

Uploading UTF-8 encoded data from files into a contrladdin is seemingly impossible.

An example use case would be to have a PDF file locally on the server, which you wish to display using pdf.js. If the PDF is UTF-8 encoded, it is seemingly impossible to get the data to javascript.

According to the docs ([link here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-file-handling-and-text-encoding)), text data from files is re-encoded to unicode after loading. For certain UTF8 characters used in the PDF format, this appears to fail. See below.

Using an alternative to a text or bigtext variable is impossible, because these types are not "serializable". For instance, the temp blob codeunit is not serializable and blobs are not accessible. Additionally, the docs for controladdins contain no reference to which types are even serializable.

Finally, allowing for the conversion to take place simply truncates the file and removes 99% of the data, making it useless.

In summary, it appears that there is no way to get UTF8 encoded binary data to javascript through business central. If I am wrong, please correct me.

# To Reproduce

There are multiple variants which can be tried, all of them fail. These are shown here.

1. Create a controladdin with a callback structure:

```
controladdin "UTF8Test"
{
    event RequestUTF8File(Path: Text);
    procedure RequestUTF8FileResult(/* something */);
}
```

2. Create the Page

```
page 50000 "UTF8TestPage"
{
    layout
    {
        area(Content)
        {
            // The control add-in can be placed on the page using usercontrol keyword.
            usercontrol(ControlName; UTF8Test)
            {
                trigger RequestUTF8File(Path: Text)
                var
                   // something...
                begin
                    // something...
                    CurrPage.ControlName.RequestUTF8FileResult(/* something */);
                end;
            }
        }
    }
}
```

3. Call from javascript

```
Microsoft.Dynamics.NAV.InvokeExtensibilityMethod('', [SOME_FILE_PATH], false, ( data ) => {
    console.log(data);
});
```

## Variant 1: Direct Read into Text

Callback: `procedure RequestUTF8FileResult(Data: Text);`
Trigger:

```
trigger RequestUTF8File(Path: Text)
var
   Data: Text;
begin
    Data := FileMgmt.GetFileContents(Path, TextEncoding::UTF8);
    CurrPage.ControlName.RequestUTF8FileResult(Data);
end;
```

This fails directly yielding some error along the lines of "the instream contains invalid data, text can't be read".
(Note: Full error in german is "Der Datenstrom enthält ungültige Daten. Der Text kann nicht gelesen werden.")

## Variant 2: Read via InStream into BigText

Callback: `procedure RequestUTF8FileResult(Data: BigText);`
Trigger:

```
trigger RequestUTF8File(Path: Text)
var
   Data: BigText;
   _InStream: InStream;
   _File: File;
begin
    _File.Open(Path);
    _File.CreateInStream(_InStream);
    Data.Read(_InStream);
    CurrPage.ControlName.RequestUTF8FileResult(Data);
end;
```

This does not fail directly but instead truncates 99% of the file (presumably due to the unicode conversion?).

## Variant 3: TempBlob / Blob

These simply won't compile:

`procedure RequestUTF8FileResult(Data: Blob);`

"Blob is not a valid parameter type"

`procedure RequestUTF8FileResult(Data: CodeUnit "Temp Blob");`

"The parameter data has a type which is not serializable and therefore cannot be used in the given context (AL0430)"

# Result

All of these methods fail to allow for uploading the UTF-8 data to javascript, either truncating the file, failing entirely to load the stream, or not compiling due to non-serializability of the return data type.

My recommendation is to either allow temp blobs to be serialized as binary data, which would fix this issue, or to allow for BigText variables to somehow keep their encoding.

Additionally, update the controladdin docs so they show which types are serializable and can be used with the callback interfaces. I couldn't find this anywhere.

Versions:

AL: v.8.3.570094
VSCode: 1.63.2
Business Central: DE Business Central 19.3
Installed Extensions: AZ AL Dev Tools/AL Code Outline

**Comment by dnpb** [comment]
Does a PDF file have an encoding? It's binary, isn't it?

Blobs and media can be serialised via `Codeunit "Base64 Convert"`

**Comment by weigert** [comment]
A PDF can be binary but doesn't have to be.

Using Base64 convert directly on an instream from a file leads to the same issue as the bigtext, simply truncating the file in Base64.

The following works:

Create a temporary table with a blob field (this is allowed for some reason)

```
table 50000 "Temporary Table"
{
    Caption = 'Temporary Table';
    TableType = Temporary;

    fields
    {
        field(1; Blob1; Blob)
        {
            Caption = 'Blob1';
        }
    }
}

```

Use a text variable for the callback, then:

```
trigger RequestUTF8File(Path: Text)
var
   Data: Text;
   _InStream: InStream;
   TempTable: Record "Temporary Table" temporary;
   Base64Convert: Codeunit "Base64 Convert";
begin
    TempTable.Blob1.Import(Path);
    TempTable.Blob1.CreateInStream(_InStream);
    Data := Base64Convert.ToBase64(_InStream);
    CurrPage.ControlName.RequestUTF8FileResult(Data);
end;
```

This is kind of silly of course because you need a table just to access a blob.

**Comment by IridiumWasTaken** [comment]
Using @weigert's approach resolved the problem. Closing this issue.
