### ISSUE TITLE
Report.Execute does not print in PDF in BC20

### ISSUE THREAD

**Issue by fabio-nettis** [microsoft/AL#7051]
**1. Describe the bug**
As mentioned in issue #7033, Report.Execute does not attach any file extension like "File.pdf", the original issue was closed due to the statement:

> This is a runtime issue, will be fixed in a next minor.

**2. To Reproduce**
Run any report with a Report.Execute(Report::XXXX, '', RecRef).

```AL
Rec123.GetTable(PayEntry_LON);
Report.Execute(Report::"Transfer List_LON", '', Rec123);
```

**3. Expected behavior**
Expected to download as a PDF with an appropriate file extension.

**4. Actual behavior**
This is an example of what happens in a BC18 and a BC20 with the same code. (Copied from #7033)

![167353027-7cca2c6d-fecb-4e97-a680-a54b54cdd9d2](https://user-images.githubusercontent.com/36916632/169762834-1f3fcb50-3bd4-4b71-a679-02ed0f73d6fc.png)

**5. Versions:**

- AL Language: Current
- Visual Studio Code: 1.67.0
- Business Central: Platform 20.0.39668.40796 - Application 20.1.39764.39901

**Comment by nhsejth** [comment]
A fix for this issue has been submitted today and will be included in the next minor.
Validated with this code snip that failed before the fix was applied.
action("Execute - Static Rdlc")
            {
                ApplicationArea = All;
                trigger OnAction()
                var
                    TriggerTable: Record ReportTriggers;
                    RecRef: RecordRef;
                begin
                    SetSelection(ReportLayoutType::RDLC, 'RDLCLayout');
                    RecRef.GetTable(TriggerTable);
                    Report.Execute(Report::"Report Triggers", '', RecRef);  
                end;
            }
