### ISSUE TITLE
Evaluate extended value for enum gives error

### ISSUE THREAD

**Issue by RobertatK3** [microsoft/AL#7053]
**1. Describe the bug**
I have extended the Price Type Enum and get an error when trying to create a new price list:
![image](https://user-images.githubusercontent.com/106147900/169997285-4b2b2b31-9728-4228-af86-d45d96541f6e.png)

The code that is giving the error is line 24 in codeunit 7018 "Price UX Management"
        **Evaluate(PriceSource."Price Type", PriceListHeader.GetFilter("Price Type"));**

**2. To Reproduce**
I have created a simple app to show that evaluate does not except the value:
Create a enum extension for Price Type:

```
enumextension 50100 "K3A Price Type" extends "Price Type"
{
    value(50100; K3ARetail)
    {
        Caption = 'Retail';
    }
}
```

Create a page to test:

```
page 50100 "K3A Test Page"
{
    Caption = 'Test Page';
    PageType = Card;
    UsageCategory = Documents;
    ApplicationArea = All;
        
    layout
    {
        area(content)
        {
            group(General)
            {
                field(ChoosePriceType; PriceType)
                {
                    Caption = 'Price Type';
                    ApplicationArea = All;
                    ToolTip = 'Choose a price type to evaluate';

                    trigger OnValidate()
                    var
                        PriceListHeader: Record "Price List Header";
                        PriceSource: Record "Price Source";
                        PriceTypeFilterText: Text;
                    begin
                        PriceListHeader.SetRange("Price Type", PriceType);
                        PriceTypeFilterText := PriceListHeader.GetFilter("Price Type");
                        Evaluate(PriceSource."Price Type", PriceTypeFilterText);
                    end;
                }
            }
        }
    }
    var
        PriceType: Enum "Price Type";

}
```

**3. Expected behavior**
When you run the page it should allow you to pick one of the price types. 
![image](https://user-images.githubusercontent.com/106147900/170004311-2629d85e-bc44-40f5-bd66-6e7b17d589c3.png)

**4. Actual behavior**
I can choose standard value like Sales:
![image](https://user-images.githubusercontent.com/106147900/170004420-1142483f-7299-4b7a-a077-86aaa03d7c86.png)
But not the extended value:
![image](https://user-images.githubusercontent.com/106147900/170004478-56fc06d8-4f22-4576-bcce-a584a1231afb.png)

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.67.2
- Business Central: 20.0.37253.38985

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
