### ISSUE TITLE
Key Vault For D365 BC Issue

### ISSUE THREAD

**Issue by v-henvaldt** [microsoft/AL#7058]
Hi all, 

I am facing an issue with reading Key Vault from Azure using Dynamics Business Central codeunit App Key Vault Secret Provider. For the development, I am using a container-based Business Central Server instance.
Steps were done to configure the key vault:

1. Was created a Self-Signed certificate.
2. A key vault application was created on the Azure portal. 
3. Added Dynamics 365 Business Central ISV Key Vault Reader.
4. Was added a certificate for the Key Vault reader.
5. Permissions were granted for the reader application.
6. Configured container Server Instance using script Set-BcContainerKeyVaultAadAppAndCertificate.ps1
7. Added link to key vault to the app.json 
8. Added the code in the BC extension which should read the secrets.

The issue is that the Initialization of the key vault is passing successfully, but the secrets are not returning, no error rises, which does not allow to identify a reason why it's happening. Can anyone advise something to solve this issue? Maybe anything was missed from my side?  

![image](https://user-images.githubusercontent.com/78726418/170443374-f96e9d84-2b4c-4139-b493-ff5ff8ceb968.png)

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
