### ISSUE TITLE
[Bug] An unexpected error occurred after a database command was cancelled. (AutoIncrement on non-PK fields)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7067]
Please include the following with each issue:

**1. Describe the bug**
When publishing a new version of an app in VS Code, an unclear error is shown, making it hard to find the code causing the problem

_The request for path /v2.0/SandboxUS/dev/apps?tenant=xxx&SchemaUpdateMode=forcesync&DependencyPublishingOption=strict failed with code UnprocessableEntity. Reason: An unexpected error occurred after a database command was cancelled._

After lots of trial and error, seems like a copy-paste error, where a new non-PK field got introduced with the AutoIncrement property enabled.

**2. To Reproduce**

- Create an AL project with following table

``` AL
table 71176626 "My Table 71176626"
{
    Caption = 'My Table 50110';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; Value1; integer)
        {
            Caption = 'integer';
            DataClassification = ToBeClassified;
            AutoIncrement = true;
        }
        field(2; Value2; integer)
        {
            Caption = 'Value2';
            DataClassification = ToBeClassified;
        }
    }
    keys
    {
        key(PK; Value1)
        {
            Clustered = true;
        }
    }
}

```
- Publish the app.
- Set the `AutoIncrement` property on field 2

```
table 71176626 "My Table 71176626"
{
    Caption = 'My Table 50110';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; Value1; integer)
        {
            Caption = 'integer';
            DataClassification = ToBeClassified;
            AutoIncrement = true;
        }
        field(2; Value2; integer)
        {
            Caption = 'Value2';
            DataClassification = ToBeClassified;
            AutoIncrement = true;
        }
    }
    keys
    {
        key(PK; Value1)
        {
            Clustered = true;
        }
    }
}
```

- Publish the app
- An error is shown

_The request for path /v2.0/SandboxUS/dev/apps?tenant=xxx&SchemaUpdateMode=forcesync&DependencyPublishingOption=strict failed with code UnprocessableEntity. Reason: An unexpected error occurred after a database command was cancelled._

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The AL compiler should at least warn on setting AutoIncrement  on non-PK fields, either the error message while publishing should provide more context on the failing object / code to support better trouble shooting.

**4. Actual behavior**

An unclear error is thrown, giving the developer no clue on what object is causing the error.

**5. Versions:**

- AL Language: v9.0.615906
- Business Central: 20.1

**Comment by dnpb** [comment]
Good find!

The problem is likely not the presence of AutoIncrement in a non-PK field, but that fact that there can be only one. That [is documented](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoincrement-property), so the compiler should enforce it properly, via Problems, rather than mysteriously failing during build.

> A table can only contain one auto-increment field.

**Comment by rsgilbert** [comment]
For me this error happened when I changed the name of a field in a table. When I restored the old table name, everything was okay again

**Comment by fvet** [comment]
FYI, we recently encountered the same when we **renumbered** a field in a table (PTE app).

**Comment by RonaldVeenman** [comment]
Removing a field which is also a key gives the same issue.
Workaround is to remove the key first, and the field afterwards.

**Comment by rsgilbert** [comment]
On another note, can you guys try out this command line tool I made for renaming AL files. Its called [alrenamer](https://www.npmjs.com/package/@passioncloud/alrenamer)

You need to have [nodejs ](https://nodejs.org/en/) installed and then followed below steps from your project (any folder with .al files in it).

1. Install alrenamer:
`npm install --global @passioncloud/alrenamer`

1. Enable running scripts:
`set-executionpolicy -scope currentuser remotesigned`

2. Rename the AL files
`alrenamer`

I will really appreciate the support, thanks!
