### ISSUE TITLE
Procedure Documentation

### ISSUE THREAD

**Issue by StefanHovenbitzer** [Microsoft/AL#707]
Is it possible by now to define a comment for a procedure which results in a description in intellisense like this: 

![image](https://user-images.githubusercontent.com/24838311/30702529-8185c2c0-9eed-11e7-992f-dc221a582ef9.png)

Thanks in advance!

**Comment by StanislawStempin** [comment]
This is not available yet but it's on our backlog.  Closing as duplicate of #132
