### ISSUE TITLE
BC20.2 ControlAddIn Variable - error AL0157: 'VariableName' is not a valid variable type

### ISSUE THREAD

**Issue by catadumitru** [microsoft/AL#7070]
**1. Describe the bug**
Compilation error when declaring a variable of type ControlAddIn
Same as issue - https://github.com/microsoft/AL/issues/7055 
but on the current released version - 20.2.41144.41423
**2. To Reproduce**

``` AL
codeunit 50100 "PTE ControlAddIn Mgt"
{
    var
        t: ControlAddIn OAuthControlAddIn; // this errors out
    trigger OnRun()
    begin
    end;
}
```
**3. Expected behavior**
This was not an issue in previous versions

**4. Actual behavior**
Compile error

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central: 20.2.41144.41423
- List of Visual Studio Code extensions that you have installed:

**Comment by nndobrev** [comment]
Hi @catadumitru, what version of the AL extension you are using, the one from marketplace or the one coming from docker container? If it is the one from marketplace, we haven't yet released the updated version, this will happen next week.

**Comment by catadumitru** [comment]
Also, our appsource app cannot be installed on the new cloud version because of this issue.

**Comment by oscarfernandezkurago** [comment]
We are experiencing the same problem in an SaaS enviroment (version 20.2.41144.41547) when we try to install our extensions, this is pretty critical as we´re blocked with that customer.

**Comment by carlosyuwono** [comment]
Our pipeline is also failing with the same error message on BC 20.2.41144.42196. 
Tested the same code on older version (20.1.39764.41791) it ran fine without an error. 

error AL0157: 'CustomControlAddin' is not a valid variable type

**Comment by nndobrev** [comment]
Hello everyone,

Heads up! The hotfix is rolling out right now. The updated version is Platform **20.0.41086.42208**.

Best,
Nikolay

**Comment by SHermann73** [comment]
Hi @nndobrev 
I can confirm that the mentioned version was rolled out to our environment today and I could successfully install all our extensions again.

**Comment by EmilDamsbo** [comment]
We are happy to hear that @SHermann73. @catadumitru can you please confirm as well in order for us to close this issue.

**Comment by catadumitru** [comment]
we also fixed our code by refactoring, so we can trust the test made by @SHermann73
