### ISSUE TITLE
Need new events in Table “Service Contract Header” at “OnValidateTrigger” of field “Starting Date”

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/AL#7074]
**_Need new events in Table “Service Contract Header” at “OnValidateTrigger” of field “Starting Date”:_**

        field(35; "Starting Date"; Date)
        {
            Caption = 'Starting Date';

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateStartingDate(Rec, IsHandled);
                if IsHandled then
                    exit;
           end;
        }

_**New Event:**_

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateStartingDate(var ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by nndobrev** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
