### ISSUE TITLE
Unable to download symbols with server CredentialType "UserName"

### ISSUE THREAD

**Issue by tfaller** [microsoft/AL#7079]
**1. Describe the bug**
I'm not able to download symbols when the server has CredentialType "UserName":
` Authorization has failed or the credentials have expired. The credential cache has been cleaned. Any access to reach Business Central would require new authorization.
The authentication has been cancelled.`

**2. To Reproduce**
 - OnPrem Server Instance with CredentialType "UserName"
 - In VSCode "Download symbols"
 - Enter correct credentials
 - Error happens as mentioned above

**3. Expected behavior**
Symbols should download. It works for CredentialType "NavUserPasswort", but not "UserName".

**4. Actual behavior**
Download does not start because of `Authorization has failed or the credentials have expired.` But this is not true.

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.67.2 (system setup)
- Business Central: Plattform 14.0.44327.0 + Anwendung 44342 (DE Business Central 14.16)
- List of Visual Studio Code extensions that you have installed: -

**Comment by thloke** [comment]
Can you try to repro this against the latest BC version (BC 20)? If it's a BC14 platform issue, then this github repo is not the correct place for this and it should go through customer support.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
