### ISSUE TITLE
Enable NoImplicitWith feature by default

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/AL#7083]
As discussed with @esbenk

Please enable the feature NoImplicitWith by default on new workspaces created with the AL:Go command.

This will help to reduce implicit with because with the feature enabled you will automatically get Rec prepended when adding controls to pages, etc.

**Comment by thloke** [comment]
We have an internal work item for exactly this change . This issue will be updated when it's done.

**Comment by mjmatthiesen** [comment]
It would be great if AL:Go allowed us to define our own templates rather than requesting updates to it :)

**Comment by SBalslev** [comment]
@mjmatthiesen please log your idea on BC ideas - for now this change will come in the vNext insider previews.
