### ISSUE TITLE
Bug regarding reservations and orderplanning

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/AL#7089]
Hi guys,

I found out that the Order Planning was not showing some Sales Orders in the demand overview. These should be shown seeing that the need an purchase to meet demand. I am missing order SO177761, SO177763 and SO177764 in this example.

![image](https://user-images.githubusercontent.com/92578153/175050794-e484c4ff-c3c2-4dd9-8bcb-3e97acaf7bdc.png)

I found out that during the calculation, it checks on the field "Planned" in the Sales Lines. A boolean field used to indicate is the outstanding quantity is met with reservation quantities. it uses a function in the Sales Line table to determine if it is planned, as seen below.

![code in salesline](https://user-images.githubusercontent.com/92578153/175051344-bbb6659f-a32a-4d22-abab-643e4138c37a.png)

During the calculation of the "Order Planning" it passes codeunit 5520 "Get Unplanned Demand". This will only check Sales lines that are not planned. As seen in the screenshot below.

![5520 get unplanned demand](https://user-images.githubusercontent.com/92578153/175051272-79e95a5b-345c-45e1-b138-ab50ffea2733.png)

The bug:
The field "Planned" is only changed in certain situations. The only times it executes the proces is when:
- the salesline is initiated
- the quantity field is validated
- when the reservation screen is opened(page 498)

But oddly enough not when a reservation is canceled on page 497 "Reservation Entries". The field planned is unchanged because nothing triggers the function "UpdatePlanned" or initiates a Sales line modification in this case. But after using the action "reserve" on the sales lines (which starts procedure ShowReservation on the sales line table and opens page 498) . It suddenly updates again. The "planned" field is now correct again. 

You can understand the impact of this bug. Orders are overseen, and this could lead to supply shortages/delays. The order planning overview is incompleet and incorrect. Please fix this in the base application. I can probably work around it by forcing the function after each reservation deletion, but it would be better if you make a fix in future versions seeming your order planning is untrustworthy at the moment.

**Comment by dnpb** [comment]
This is not about the AL language or compiler itself, so probably it should be reported via partner support - or, if it relates to extensibility, https://github.com/microsoft/AlAppExtensions/issues

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by JohnFrostDP** [comment]
I moved the bug to https://github.com/microsoft/ALAppExtensions/issues/18815
