### ISSUE TITLE
case of issue

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#709]
I am finding an issue that "case ... of" doesn't always work:

`
var
  a : int;
begin
  case a of
    1:
      if a = a then
        Message('here');
    2:
      if a = a then
        Message('not reachable');
  end;
end;
`

It will only reach the first block of code - so it will execute the code, if a = 1, but if a = 2, it will just skip over it. Once you put a "begin end" around the code in the different case options, it works. However, then code analysis complains that you should only use begin..end, if you have multiple line statements.

**Comment by esbenk** [comment]
I have just tried the following, that print 'NotReachable'.
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        a : Integer;
    begin
        a := 2;
        case a of 
            1: if a = a then Message('here');
            2: if a = a then Message('NotReachable');
        end;

    end;
}

```
It was tested with the latest internal version, so it is newer than the public ones and bugs may have been fixed. Can you verify if that snippet works on your machine?

The case lines expects exactly one statement or statement block. Putting begin/end around the if-statements shouldn't change anything.

Please note that the CodeAnalysis is very experimental and haven't been tested to the same level as the rest of the compiler.

**Comment by pzentner** [comment]
Yes, this is working. However, here are a couple scenarios where it is not working:

`
pageextension 50100 CustomerListExt extends "Customer List"
{
  trigger OnOpenPage();
  var
    a : Option Start,Middle,Completed;
  begin

    for a := 0 to 2 do begin
      case a of
        a::Start:
          if a = a then 
            Message('here');
        a::Completed: 
          if a = a then 
            Message('not reachable');
      end;
    end;
  end;
}
`
and

`
pageextension 50100 CustomerListExt extends "Customer List"
{
  trigger OnOpenPage();
  var
    a : Text;
    i : Integer;
  begin

    for i := 0 to 1 do begin
      if i = 0 then a := 'test';
      if i = 1 then a := 'not test';
      case a of
        'test':
          if a = a then 
            Message('here');
        'not test':
          if a = a then 
            Message('not reachable');
      end;
    end;
  end;
}
`

It seems my original example was wrong, but the issue seems to be with Option and Text - possibly others. But if the "case variable" is integer, it works.

**Comment by esbenk** [comment]
They both fail.
