### ISSUE TITLE
How to extend new features ?

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/AL#7090]
- AL Extension Version: 9.2.639332

- Server Version: windows server 2019

Unable to extend the new Feature Update: Standardized bank reconciliation and deposits
After turning on the feature, it is available on business central, but the symbols are not updated
What is the process of extending a turned on feature?
Do we need to generate symbols? 
Is there a step by step documentation for this?
Do cloud and on-prem versions differ in this regard?

You can read more about the  Standardized bank reconciliation and deposits feature here:
https://docs.microsoft.com/en-us/dynamics365/business-central/bank-create-bank-deposits

**Comment by nndobrev** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

**Comment by AbsolutelyFreeWeb** [comment]
@nndobrev @pri-kise
Answering that it is an extension in 20.2 is not a solution if the client is on 20.1
The nature of the problem withstands, On newer versions, there are newer features, with same problem.
The question is, how is it supposed to work to extend a feature. There should be documentation for this, not something to seek solve between users on a forum, hence the question here.
