### ISSUE TITLE
Debugger should show if a transaction is active

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/AL#7096]
- AL Extension Version: v9.3.642746

- Server Version: 20.2.41144.41959

Suggestion: I think the debugger should show if a transaction is active..

**Comment by thloke** [comment]
This is more of a feature than a bug, so it's out of scope for this repo. You can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
