### ISSUE TITLE
Automatic indentation of if ... then repeat until is wrong

### ISSUE THREAD

**Issue by cstuber** [microsoft/AL#7099]
**1. Describe the bug**
The automatic indentation of a repeat until loop after a condition is wrong.

**2. To Reproduce**

1. Create a simple `repeat until` with the usual check for existing records.

``` AL
    local procedure MyProcedure()
    var
        Item: Record Item;
    begin
        if Item.FindSet() then
            repeat
                Message(Item.Description);
            until Item.Next() = 0;
    end;
```
**3. Expected behavior**
The indentation of the repeat until should be one tab more than the `if FindSet() then`

```AL
    local procedure MyProcedure()
    var
        Item: Record Item;
    begin
        if Item.FindSet() then
            repeat
                Message(Item.Description);
            until Item.Next() = 0;
    end;
```

**4. Actual behavior**
The indentation is two tabs instead of one. This reformats large parts of the source code which have to be manually reversed.

``` AL
    local procedure MyProcedure()
    var
        Item: Record Item;
    begin
        if Item.FindSet() then
                repeat
                    Message(Item.Description);
                until Item.Next() = 0;
    end;
```

**5. Versions:**

- AL Language:v9.3.642746
- Visual Studio Code:1.68.1
- Business Central: Platform 20.0.41086.41354 + Application 20.2.41144.41423

**Comment by SBalslev** [comment]
Duplicate #7091
