### ISSUE TITLE
Code not fired in Sourcexp property of page field

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#71]
https://github.com/Microsoft/AL/issues/46

The field value is shown now in page but the code in sourexp is not fired.

**field(Comments;ChechComments.CheckCommentsExist(Rec."No."))**

I have added message statements in CheckCommentsExist function to test it and they are not fired.

**Comment by StanislawStempin** [comment]
This is a bug. We will have a look at it

**Comment by esbenk** [comment]
Different symptoms, but same root cause as #75

**Comment by StanislawStempin** [comment]
We have fixed this bug and uploaded a new azure gallery image to http://aka.ms/navdeveloperpreview. Please give it a try.

**Comment by pmohanakrishna** [comment]
It is working fine now. Thanks..
