### ISSUE TITLE
Actions Role Center Bug RunPageView

### ISSUE THREAD

**Issue by VRABart** [microsoft/AL#7105]
Please include the following with each issue:

**1. Describe the bug**
My action is not visible in the new rolecenter role i make when i use the property RunPageView. Action vendors is visible. Action Balance Vendor is not visible.

**2. To Reproduce**
1. Make a new page of type "Role Center".
2. Skip the layout and go to actions.
3. Go to the area sections make a new group and in this group make a new action.
4. Give the action two properties RunObject and RunPageView. (and the basics like applicationarea,Image,caption,...)
5. Publish the extension and the action will not be visible in the "Role center" when selected the correct Role.

``` AL
page 54302 "VRA Book Keeper Role Center"
{
    Caption = 'Book Keeper', Comment = 'NLB="Boekhouder"';
    PageType = RoleCenter;

    actions
    {
        area(sections)
        {
          group("Vendors Group")
            {
                Caption = 'Vendors', Comment = 'NLB="Leveranciers"';
                Image = Journals;
                ToolTip = 'Vendors', Comment = 'NLB="Leveranciers"';
                Action(VendorsBalance)
                {
                    ApplicationArea = All;
                    Caption = 'Balance Vendor', Comment = 'NLB="Balans Leverancier"';
                    Image = Balance;
                    RunObject = Page "Vendor List";
                    RunPageView = where("Balance (LCY)" = filter(<> 0));
                    ToolTip = 'Open List Balans Vendors', Comment = 'NLB="Opent lijst Balans Leverancier"';
                }
                Action(Vendors)
                {
                    ApplicationArea = All;
                    Caption = 'Vendors', Comment = 'NLB="Leveranciers"';
                    Image = Vendor;
                    RunObject = Page "Vendor List";
                    ToolTip = 'Open List Vendors', Comment = 'NLB="Opent lijst Leveranciers"';
                }
            }
        }
     }
}
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
When i publish my extension i want to see my action visible in my rolecenter role.Action vendors is visible. Action Balance Vendor is visible.

**4. Actual behavior**
Action vendors is visible. Action Balance Vendor is not visible.

**5. Versions:**

- AL Language: AL
- Visual Studio Code: 1.68.1
- Business Central: V20
- List of Visual Studio Code extensions that you have installed:

### Final Checklist
AL Formatter
Al Language
Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
