### ISSUE TITLE
BC Data Exchange Definition not calling Ext. Data Handling Codeunit

### ISSUE THREAD

**Issue by idealsceneprod** [microsoft/AL#7109]
**1. Describe the bug**
I'm having trouble with a Data Exchange Definition for a Canadian customer. MS's tables for Canada are missing vital fields that are only present in the US tables.

The problem is that the US NACHA format appends a block of 9999s at the end, which isn't acceptable in Canada.

I tried creating a modified copy of Codeunit 10323 "Exp. External Data EFT" and specifying it in Ext. Data Handling Codeunit field in the Data Exchange Defn, but it isn't getting called. I put a breakpoint in my codeunit in the Debugger and it never gets called.

In my new codeunit, I commented out the code AddPadBlocks which creates the block of 9999s at the end of the file. If I have only my codeunit specified, nothing happens. If I have the usual codeunits specified, it still outputs the block of 9999s.

**2. To Reproduce**
Create a new codeunit, perhaps a copy, like I did.
Create a Data Exchange Definition which references that codeunit in the Ext. Data Handling Codeunit field.
Setup your Bank account for US EFT.
Create a payment journal for Electronic-IAT.
Go to Bank / Export.
Go to Actions / Functions / Export EFT.
Uncheck all except the line you just created and then export EFT.

If you put a breakpoint in your VS code, it won't get called.

I tried with just that codeunit specified, and with the others specified as well.

**3. Expected behavior**
The codeunit won't be called. If I put a breakpoint, the debugger never stops on it.

**4. Actual behavior**

**5. Versions:**

- AL Language: v9.3.646020
- Visual Studio Code: 1.68.1
- Business Central: 19
- List of Visual Studio Code extensions that you have installed: AL Language; Edit CSV; Excel Viewer; Markdown Preview Enhanced; npm; solar2d-companion; SQLite; Vetur; VueJS helper; XML Tools;

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
