### ISSUE TITLE
Permission Sets

### ISSUE THREAD

**Issue by hvogelpohl** [Microsoft/AL#711]
Last time (Extensions 1.0) I had to compile a _permissions.xml_ in my NAVX file with the permission set of my app. Is this still needed, if so, how?

**Comment by MikeGlue** [comment]
You can simply use the same XML file you generated for your V1 extension, or use the same process to make a new one for your V2 extension, and then put the XML file into your extension project. Seems like you can put it anywhere you want and the compiler will figure out what to do with it.

For example, I put mine in a specific folder, and no other settings were needed to be changed and the compiler picked it up and included it in the compiled extension app.

<img width="119" alt="image" src="https://user-images.githubusercontent.com/5204734/30812611-37968886-a1d9-11e7-878e-59bbd16313ab.png">

**Comment by hvogelpohl** [comment]
Ahhh... "The file matches the definition for 'PermissionSet'.". Thank you very much!

**Comment by hvogelpohl** [comment]
I'm just wondering what object type page extensions and table extensions are? (  <Permission><ObjectType>??</ObjectType></Permission>). I searched here, I didn't find anything..

**Comment by MikeGlue** [comment]
Just give permissions to the original table/page objects you are extending, not the actual extension objects.
