### ISSUE TITLE
HttpClient.AddCertificate does not work for adding Keystore (.Key) file

### ISSUE THREAD

**Issue by STlambt** [microsoft/AL#7111]
This is the first Web Service call I have written where I need to send certificates so apologies if I am not describing this 100%

1. Describe the bug
When adding a Keystore certificate using the HTTPClient.AddCertificate, the following error occurs:
"Cannot find the requested object".

A large US bank requires a Pem certificate and a Key certificate to be sent when calling their web service. Basically this is what the cURL looks like if it helps:

![image](https://user-images.githubusercontent.com/108437356/178361140-315aff1c-9953-4b16-9d18-5eb051f55797.png)

I am able to successfully call the WS using Postman and as you can see Postman caters for a Key and a Cert (here I use the Pem certificate) certificate.

![image](https://user-images.githubusercontent.com/108437356/178361195-da8a809f-d42a-469c-875d-617aa65b52b6.png)

In AL I am using the following code to to add the certificates in the hope that I can add the two certificates, however when I get to loading the Key Certificate, it throws out a message “Cannot find the requested object” when hitting the code lClient.AddCertificate(lKeyCert,‘’)

local procedure CallforValidation(pBody: Text; pToken: Text) rResponse: Text;
    var
        lClient: HttpClient;
        lRequest: HttpRequestMessage;
        lResponse: HttpResponseMessage;
        lRequestHeader: HttpHeaders;
        lRequestContent: HttpContent;
        lResponseTextOut: Text;
        lJObject: JsonObject;
        lToken: Text;
        lBase64: Codeunit "Base64 Convert";
        lInstreamCert: InStream;
        lInstreamKey: InStream;
        lSetup: Record SetupTable
        lPemCert: Text;
        lKeyCert: Text;

    begin
        lSetup.Get();

        lRequestHeader.Clear();
        lRequest.GetHeaders(lRequestHeader);
        lRequestHeader.Add('Authorization', 'Bearer ' + pToken);
        lRequest.SetRequestUri(lSetup."Account Verification URL");

        //Add Content
        if pBody <> '' then
            lRequestContent.WriteFrom(pBody);

        lRequestContent.GetHeaders(lRequestHeader);
        if lRequestHeader.Contains('Content-Type') then
            lRequestHeader.Remove('Content-Type');
        lRequestHeader.Add('Content-Type', 'application/json');
        lRequestHeader.Add('gateway-entity-id', lSetup."Gateway Entity ID");
        lRequestHeader.Add('client-request-id', 'xxx-xxx-xxx-xxx-xxx-xxx-xxx');         

        lRequest.Content := lRequestContent;
        lRequest.Method('POST');

        lClient.Clear();
        lSetup.CalcFields("Certificate File");
        lSetup."Certificate File".CreateInStream(lInstreamCert);
        lPemCert := lBase64.ToBase64(lInstreamCert);
        lClient.AddCertificate(lPemCert, '');

        lSetup.CalcFields("Key File");
        lSetup."Key File".CreateInStream(lInstreamKey);
        lKeyCert := lBase64.ToBase64(lInstreamKey);
        lClient.AddCertificate(lKeyCert, '');

        if lClient.Send(lRequest, lResponse) then begin
            lResponse.Content.ReadAs(lResponseTextOut);
            IF NOT lJObject.ReadFrom(lResponseTextOut) then
                Error('Invalid response, expected a JSON object');
            exit(lResponseTextOut);
        end;
    end;

Is there another method I should be using to load a Keystore certificate?

**2. To Reproduce**
This may be really difficult to reproduce

**3. Expected behavior**
The .Key certificate will load

**4. Actual behavior**
When adding a Keystore certificate using the HTTPClient.AddCertificate, the following error occurs:
"Cannot find the requested object"

**5. Versions:**

AL Language v9.3.646020

BC On Prem Version: NA Business Central 17.2 (Platform 17.0.19353.19730 + Application 17.2.19367.19735)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by STlambt** [comment]
Regardless of whether this is out of scope for this repository, for the unfortunate soul who comes across this issue, this was resolved by combining the PEM certificate and the KEY certificate into one PFX certificate.

By downloading and installing openSSL and then using command prompt to convert the certs using the following command line:

openssl pkcs12 -export -out “Path to Certs\Cert.pfx” -inkey “Path to Certs\Cert.key” -in “Path to Certs\Cert.pem”

The PFX cert can then be stored in a blob field in a table and then sent with the Web Service request as follows:

    lClient.Clear();
    lSetup.CalcFields("Certificate Store");
    lSetup."Certificate Store".CreateInStream(lInstreamCert);
    lPemCert := lBase64.ToBase64(lInstreamCert);
    lClient.AddCertificate(lPemCert, '');

**Comment by abzmdc** [comment]
> Regardless of whether this is out of scope for this repository, for the unfortunate soul who comes across this issue, this was resolved by combining the PEM certificate and the KEY certificate into one PFX certificate.
> 
> By downloading and installing openSSL and then using command prompt to convert the certs using the following command line:
> 
> openssl pkcs12 -export -out “Path to Certs\Cert.pfx” -inkey “Path to Certs\Cert.key” -in “Path to Certs\Cert.pem”
> 
> The PFX cert can then be stored in a blob field in a table and then sent with the Web Service request as follows:
> 
> ```
> lClient.Clear();
> lSetup.CalcFields("Certificate Store");
> lSetup."Certificate Store".CreateInStream(lInstreamCert);
> lPemCert := lBase64.ToBase64(lInstreamCert);
> lClient.AddCertificate(lPemCert, '');
> ```

Thanks for the solution, it was indeed a great help, I was smashing my head into different thing to make it work, previously we had a certificate with the password, recently the third party has changed the communication protocol and out functionality was not working. Now they have provided a security certificate and a key file. Using your command, I was able to generate the certificate, but we also need to set the password as well, my adding an extra parameter, I was able to generate a certificate and use it in the AL, here is the updated command,
**openssl pkcs12 -export -out "D:\Cert.pfx" -inkey "D:\IT_auth.key" -in "ITSSL.cer" -name "Client Certificate" -password pass:your_password**
