### ISSUE TITLE
Rule AA0219 is being applied to Page Actions

### ISSUE THREAD

**Issue by epernst** [microsoft/AL#7114]
This is a re-post of #6383 reported in December 2020. Original issue been closed despite it has not been resolved.

Right now our only option is really to disable this cop, which is a shame as it helps us speed up code reviews.

**Comment by qutreson** [comment]
Closing this issue as this was fixed with version 12.0 of the compiler. 

See changelog entry:

```
- [AA0219](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0219) diagnostic no longer reports that page actions must start with 'Specifies', since actions generally don't specify something.
```
