### ISSUE TITLE
Snapshot Debugging: VS Code "Specified argument was out of the range of valid values. (Parameter 'index')"

### ISSUE THREAD

**Issue by Harakiri24** [microsoft/AL#7116]
**1. Describe the bug**
- When the download of a Snapshot (.zip) has been finished and you want to start the debugging session a Visual Studio Code window appearears after a while that contains the error message "Specified argument was out of the range of valid values. (Parameter 'index')".

**2. To Reproduce**

1. Have the latest Visual Studio Code "AL"-extension installed 
2. Initialize a Snapshot
3. Finisch (Download) the Snapshot
4. Start the Debugging (bottom left debugging symbol).

Each of those steps do NOT work with VS Code for Windows or macOS. 
**It works however with the old AL Language Extension 8.3.570094 (tested!)**. So it's a bug somewhere in a newer verison than 8.3.570094.

**3. Expected behavior**
The Debugger should jump into the code.

**4. Actual behavior**
Error Message  "Specified argument was out of the range of valid values. (Parameter 'index')".

**5. Versions:**

- AL Language: v9.3.646020
- Visual Studio Code: Version: 1.69.1
- Business Central: 20.2.41144.41547
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by kalberes** [comment]
In order to have a clue where exactly it fails :
Can you please enable verbose logging in VsCode "al.editorServicesLogLevel": "Verbose" and somehow send the DebuggerServices.log found in C:\Users<username>.vscode\extensions\ms-dynamics-smb.al-\bin
Don't forget to reset the settings, since the log will grow very fast very large.

**Comment by Harakiri24** [comment]
> In order to have a clue where exactly it fails : Can you please enable verbose logging in VsCode "al.editorServicesLogLevel": "Verbose" and somehow send the DebuggerServices.log or the exception found in C:\Users.vscode\extensions\ms-dynamics-smb.al-\bin Don't forget to reset the settings, since the log will grow very fast very large.
[DebuggerServices.log](https://github.com/microsoft/AL/files/9129853/DebuggerServices.log)

**Comment by Harakiri24** [comment]
Heres the logfile for the working Version (8.3.570094)
[DebuggerServices.log](https://github.com/microsoft/AL/files/9129889/DebuggerServices.log)

**Comment by kalberes** [comment]
Thanks.

**Comment by Harakiri24** [comment]
> 

That does not make a difference actually. I tested the snapshot debugging on a completely new VS Code install with extension Version 8.3.570094 and it worked ( but it didn't worked with the _newest_ version 9.3.646020 on that fresh install).

**Comment by OlgicaA** [comment]
First I have set some debugger points : snapshot was working fine, and could be replayed
Then I have added some more dubugger points in Integration Synchronization Codeunits and tables: snapshot was successfully downloaded and coulnd't be replayed with the same error Specified argument was out of the range of valid values. (Parameter 'index')

**Comment by KosPav** [comment]
this bug is still reproducable in version 10.1.707468
