### ISSUE TITLE
Missing Compiler Error for Variant.IsDataClassificationType() in Runtime 3.0

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7119]
There should also be an error for **Variant.IsDataClassificationType()** when you are using Runtime 3.0 because you can publish this in a Business Central version 14 database but the service tier crashes when this is executed. If you use **Variant.IsDataClassification()** - the same without the word **Type** -  you get the following compiler error:

`error AL0666: 'IsDataClassification' is not available in runtime version '3.0'. The supported runtime versions are: '8.0' or greater.`

**Comment by nndobrev** [comment]
Hi @DanielGoehler,
Variant.IsDataClassificationType() is the correct method you should be using when you target BC v14. Unfortunately, this is not in the scope of the compiler but a runtime one. In addition, the repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
