### ISSUE TITLE
License Error

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#712]
When I try to publish my app on US locale, i have error "Your program license does not allow you to publish 'App name'"

I have changed the objects range to 50100 but I still get the error.

Before the September update, it was working correctly

c:\Users\Administrator\Documents\GitHub\AL\samples\HelloWorld2\HelloWorld.al(6,10): error AL0297: The application object identifier '50100' is not valid. It must be within the allowed range '70000000' - '74999999'.

**Comment by StanislawStempin** [comment]
Have you added the correct IdRange to app.json?  See #704

**Comment by andrecavalcanti** [comment]
Yes. I have added it and I still get the same error.

**Comment by StanislawStempin** [comment]
Which version of AL Language extension are you using?  
Does your IdRange allow for identifier 50100, i.e.: 
```
"idRange": {
    "from": 50100,
    "to": 50149
  }
```

**Comment by andrecavalcanti** [comment]
I installed a version prior to September and it works now
