### ISSUE TITLE
Constant appearance of a breakpoint.

### ISSUE THREAD

**Issue by OlegLobakov** [microsoft/AL#7120]
This error keeps popping up even if no code is being executed.
Why is this breakpoint raises 1 time per second? How to turn it off?

![image](https://user-images.githubusercontent.com/34211051/180461726-8d86f304-98b9-4c91-899a-5cb52bb9e86d.png)

**Comment by kalberes** [comment]
What is your setting for breakOnRecordWrite?

**Comment by OlegLobakov** [comment]
{
            "type": "al",
             "request": "launch",
            "name": "BC20.3",
            "server": "http://bc23",
            "tenant": "default",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 70611641,
            "startupObjectType": "Page",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "schemaUpdateMode": "ForceSync",   
        }

**Comment by kalberes** [comment]
Probably you are in an error condition. If you open the variables, don't you see among the locals as the last variable an error message.
I assume if you open the breakpoints window, you donot see this breakpoint.

**Comment by OlegLobakov** [comment]
Yes. Locals contain information about no access to the "User Preference" table, but I have SUPER permissions.

**Comment by Delirious-Grandpa** [comment]
Same here. Is this because (in my case) delegated admins are treated differently?

**Comment by kalberes** [comment]
I do not know. That is a question to @JesperSchulz , or app teams.   This is not a debugger issue.
I am closing the issue.

**Comment by OlegLobakov** [comment]
And what must I do? Problem exists
