### ISSUE TITLE
`"Quotes in Variable Names"` like `var "Text": Text` cause false warning 'Parameter "Text is declared by reference but never changed in method (AA0150)'

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7122]
Reopening #6184 as AA0150 is still broken. I get that you want to close issues about adding/improving CodeCops, but you should fix clear bugs in them, please!

***

AA0150 says things declared as `var` are not modified when they clearly are.

Looking more closely, this seems due to `"Quoted Names"`, more evidence that it's just a bug, and hopefully easy to fix :-)

N.B. I am in the habit of trying to `"Quote"` things that are elsewhere reserved words, like e.g. a variable named `Text`, as not all themes render them in the right colour if unquoted. And even if quotes are unnecessary, they shouldn't break code analysers ;-)

***

Code:

```al
codeunit 50100 HelloWorld
{
    internal procedure TestOne(var Text: Text)
    begin
        Text := 'foo';
    end;

    internal procedure TestTwo(var "Text": Text)
    begin
        "Text" := 'foo';
    end;

    internal procedure TestThree(var vText: Text)
    begin
        vText := 'foo';
    end;

    internal procedure TestFour(var "vText": Text)
    begin
        "vText" := 'foo';
    end;

    internal procedure TestFive(var Gurgler: Text)
    begin
        Gurgler := 'foo';
    end;

    internal procedure TestSix(var "Gurgler": Text)
    begin
        "Gurgler" := 'foo';
    end;
}
```

Wrong warnings:

![image](https://user-images.githubusercontent.com/63455896/180733261-d7d9f2ed-b093-4db2-93a9-b8d6cc1ee50f.png)

***

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.3.646020
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
Long term our plan is to overhaul the CodeCop rules, so fixing issues in the existing rules don't really fit into our roadmap. Unfortunately as far as priorities go, we don't have the capacity to fix existing code cop rules. I agree that it would be nice to fix them, but we have to also weigh them against other bugfixes/features that are also in the backlog. :(

I know this isn't the answer you were hoping for, but hopefully we'll get time to do that overhaul of codecop in the near future instead which will be a more comprehensive review of our CodeCop rules. We'll definitely be looking at issues tagged with CodeCop when we get to that.
