### ISSUE TITLE
Download Symbols

### ISSUE THREAD

**Issue by KosPav** [microsoft/AL#7125]
**1. Describe the bug**
I am developing an extension for Business Central Online(SAAS).

As part of some routine inside the extension I need to download the symbols from Business Central. 

I have investigated that VSC(visual studio code) uses this “86665399-b262-4a92-bc07-da1b50e66a92” application and OAuth 2.0 device authorization grant flow when developer needs to download symbols for his AL project.
I have implemented the same logic inside my extension:

**2. To Reproduce**
After Initialization of Device Code Auth Flow user enters his credentials in the browser to retrieve an access token. 

``` AL
    procedure InitializeDeviceCodeAuth() ResponseContentTxt: text
    var
        HttpResponseMessage: HttpResponseMessage;
        ContentRequestTxt: Text;
        ErrLbl: Label 'Failed to initialize DeviceCode Authentication Flow.', Locked = true;
    begin
        ContentRequestTxt += 'client_id=' + TypeHelper.UriEscapeDataString('86665399-b262-4a92-bc07-da1b50e66a92');
        ContentRequestTxt += '&resource=' + TypeHelper.UriEscapeDataString('https://api.businesscentral.dynamics.com');

        SendRequest('POST', 'https://login.microsoftonline.com/', AzureADTenant.GetAadTenantId() + '/oauth2/devicecode/', ContentRequestTxt, HttpResponseMessage);

        HttpResponseMessage.Content.ReadAs(ResponseContentTxt);
        if not HttpResponseMessage.IsSuccessStatusCode() then begin
            if ResponseContentTxt = '' then
                ResponseContentTxt := ErrLbl;
            Error(ResponseContentTxt);
        end;
    end;

```

**3. Expected behavior**
The above procedure helps me to retrieve the access token suitable for downloading of the symbols. And it works great for all BC environments which I have tested except for my corporate environment.

**4. Actual behavior**
I am getting this error when trying to authorize the application for my corporate environment: 
![image](https://user-images.githubusercontent.com/45877997/181313347-4c71567e-ee1b-420d-9002-0824cf958894.png)

You cannot access this right now
Your sign-in was successful but does not meet the criteria to access this resource. For example, you might be signing in from a browser, app, or location that is restricted by your admin.

Error Code: 53003
Request Id: 9656e507-0ce6-4034-99c6-78fe60343300
Correlation Id: b22c1787-2b27-42af-8a60-43b65a5a973f
Timestamp: 2022-07-19T15:31:12.374Z
App name: Dynamics 365 Developer
App id: 86665399-b262-4a92-bc07-da1b50e66a92
IP address: 20.234.8.69
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

I am not getting the above error when downloading symbols through the Postman or VSC. It appears only when request is sent from BC. (and only for our corporate BC environments).
I had a conversation with our security administrator. Seems that problem is with Location. Our corporate BC is hosted on the server in Ireland.
VSC and Postman I am using from Ukraine.

Security administrator can not setup security policies for this application because somehow we do not have it in “Enterprise Applications” in our corporate Azure Portal. 
But it is in my personal trial azure:
![image](https://user-images.githubusercontent.com/45877997/181316918-5313f18e-8ed3-418d-af26-cb5727d459f5.png)

**5. Questions:**
	Could you please give us some advice how we can solve this problem?
	Why this application is absent in our corporate Azure Portal (maybe there is some another application that we can use)?

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
