### ISSUE TITLE
Creating Extension using W1 installation.

### ISSUE THREAD

**Issue by mvdheijkant** [Microsoft/AL#713]
Maybe I’m running ahead of business but I’m trying to create an Extension using Dynamics (symbols) version W1_11.0.18344.0. with AL Extension “al-0.9.12794”.
Also created the latest Tenerife environment on Azure which is running on version US_11.0.18323.0.
Created the Demo “Hello World” app in Azure with “AL:GO!”, configured the environment, compiled and published the extension as one expects.
But on my own “identical” environment, running W1 it doesn’t work, because extends are not recognised. Symbols are downloaded from my local VM.
Only when I ad the US symbols from Azure, and modify the “locale: US” setting in my app.json, extends are recognised.
But when compiling and trying to publish the local extension, again this error shows.
“The target Page "Customer List" for the extension object is not found”

Is this configuration already supported, meaning are W1 extensions already supported?

**Comment by StanislawStempin** [comment]
To develop against W1 you should select Country = W1 when provisioning the development environment through aka.ms/navdeveloperpreview

**Comment by mvdheijkant** [comment]
Checked in Azure if I could find that "Country = W1" setting somewhere when provisioning the dev-environment but I can't find it.  Only choice that's more or less related is the opthon to deploy a finus, finca or fingb environment, but that's not it.
But what I was looking for is, how to modify our own on-site VM with W1 development environment. What local setting(s) in VS-Code with the AL-extension is neccesary , apart from the one mentioned  to make this work.

**Comment by gprodware** [comment]
i have selected the Country = W1 through aka.ms/navdeveloperpreview and got the US enviroment.

**Comment by freddydk** [comment]
Remove the -finus from the Docker Image name in order to get W1 - because you now have the option to replace the navserver inside the VM using the navcontainerhelper prompt.

**Comment by mvdheijkant** [comment]
Freddy, you are correct. By removing the -finus parameter, a W1 Development Preview is created.
This Development environment works as is, nothing wrong there.

I was hoping to find a difference in settings comparing this Azure environment and our own on-site W1 environment.
We’re still very devoted to develop in our on-site environments.

Big difference is that on Azure there’s, I think an Azure SQL Database as a backend and in our on-site environment we have a local SQL Database.

The AL-Extension overview page says following:
NOTE: To deploy code built using this extension you need a NAV Developer Preview Azure Gallery image available at https://aka.ms/navdeveloperpreview.

So I’m now very concerned that I’m asking for the impossible or at least asking for a feature that’s not yet supported.

Is it possible to have a complete on-site Development environment running for Dynamics W1 2018
