### ISSUE TITLE
There should be a Compiler Error for setting the Editable Property of a part in a PageExtension

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/AL#7133]
For example the following code will compile but when uploading it, it throws an error:

```
pageextension 50000 "My User Card" extends "User Card"
{
    layout
    {
        modify(Permissions)
        {
            Editable = false;
        }
}
```

**Comment by dnpb** [comment]
What error? With which version(s) of the AL extension and BC server/platform?

**Comment by matthias-planzer** [comment]
Yea sure I should have included that beforehand. The Error Message is 
`The request for path /BC/dev/apps?SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: An error occurred while applying changes from the object of type 'PageExtension' with ID '50178' in the 'AppName' app to the application object of type 'Page' with the ID '9807'. Failing delta: Type: 'ContentChangeDelta'; TargetKind: 'Content'; TargetId: 'Permissions'; TargetType: 'ControlBaseDefinition'; PropertyNames: 'Editable'; The error was: InvalidOperationException - Metadata delta application failed due to the following error(s): Modifications to property Editable are not supported.`
BC Version: Version: CH Business Central 20.0 (Plattform 20.0.37114.38150 + Anwendung 20.0.37253.38230)
AL Lanuage Version: 9.4 (latest)
VSCode Version: 1.70 (latest)
