### ISSUE TITLE
moveafter() not working under Actions on page ext.

### ISSUE THREAD

**Issue by DragonPaladin** [microsoft/AL#7134]
The moveafter() doesn't seem to work under Actions like it does under Layout on page ext.
I've tried with and without "s around it as well. 

I am trying to move CopyDocument to be the 2nd in order as well as others, the PromotedIsBig only seems to be of use with 2 buttons/ribbons to reorder.

Code:
![image](https://user-images.githubusercontent.com/109811802/183753636-441dd3ca-257c-41e2-b984-04717c40d34d.png)

BC:
![image](https://user-images.githubusercontent.com/109811802/183753775-05bf5d36-40b4-4197-9889-29b45b61b45d.png)

Thanks in Advance!
(if this isnt the place to post please leave a link toward that area, ty)

**Comment by qutreson** [comment]
@DragonPaladin - Your screenshot shows the promoted side of the action bar. This side of the action bar contains promoted actions which are implicitly created by the usage of the Promoted properties:
- Promoted triggers the creation of the promoted action in the promoted area
- PromotedCategories specifies in which group the action is defined
- PromotedIsBig specifies if the action should be added toward the start or the end of the group.

This current design does not allow to specify explicitly the order of the promoted actions in AL.

The moveafter that you created impacted the position of the main action which is located on the right side of the action bar (where Actions / Related / Reports/ etc are located).
