### ISSUE TITLE
AL includes symbols from apps not in the .alpackages folder

### ISSUE THREAD

**Issue by lvlaanderen** [microsoft/AL#7138]
- AL Extension Version: v9.4.663067

![Screenshot 2022-08-12 110531](https://user-images.githubusercontent.com/88882450/184333639-f35868fe-4a6d-4802-8419-eca2220a73f5.jpg)

The app files in the main app folder are loaded as symbols and causes it to complain objects already exist in the symbols when they do not in the .alpackages folder

**Comment by lvlaanderen** [comment]
This seems to occur when compiling at which point the new app file is complained about

**Comment by thloke** [comment]
Can you share what's the value (if any) of the setting `al.packageCachePath` in your settings.json?

**Comment by lvlaanderen** [comment]
That value is not set

**Comment by thloke** [comment]
Can you share the contents of your `settings.json` for both the project and VSCode level? Or share a workspace which reproduces this issue.

**Comment by lvlaanderen** [comment]
This a typical settings.json
{
  "CRS.AlSubFolderName":"Source",
  "CRS.ObjectNameSuffix":" ",
  "CRS.FileNamePattern":"<ObjectTypeShortUpper><ObjectId>.<ObjectNameShort>.al",
  "CRS.FileNamePatternExtensions":"<ObjectTypeShortUpper><BaseId>.EXT<ObjectId>.<ObjectNameShort>.al",
  "CRS.FileNamePatternPageCustomizations":"<ObjectTypeShortUpper><BaseId>.EXT<ObjectId>.<ObjectNameShort>.al",
  "al.enableCodeAnalysis":true,
  "al.enableCodeActions":true,
  "al.ruleSetPath":".codeAnalysis\\ruleset.json",
  "al.codeAnalyzers":["${CodeCop}",
  "${PerTenantExtensionCop}",
  "${UICop}"],
  "alVarHelper.ignoreALSuffix":"",
  "editor.minimap.scale":3
}

**Comment by qutreson** [comment]
@lvlaanderen Are you still experiencing this issue? Can you also share all the settings you have defined on a user/workspace/project level?

**Comment by thloke** [comment]
We cannot reproduce this internally. If this is still happening on the latest version of the AL Extension for VSCode, please re-open and provide all relevant settings.json files.
