### ISSUE TITLE
EU VAT Registration No. Validation - issue

### ISSUE THREAD

**Issue by CChub402** [microsoft/AL#7140]
**1. Describe the bug**

When EU VAT REgistration No. Validation service enabled in Service connections as shown below,

![image](https://user-images.githubusercontent.com/68992345/185572672-175f3ea7-9f67-45ba-8e5d-f20b94131cb2.png)

We get the following error when a VAT registration number is entered in customer, vendor or contact card page

A call to System.Xml.XmlDocument.Load failed with this message: '>' is an unexpected token. The expected token is '"' or '''. Line 1, position 55.

![image](https://user-images.githubusercontent.com/68992345/185575250-05ab49da-7d5c-4dd3-9c60-c08d776c8683.png)

**2. To Reproduce**
Search for Service connections in Business central web client, and select the option "EU VAT Registration No. Validation service" and enable it.
Open Customer card page and type in a value for "VAT Registration No." field.

**3. Expected behavior**
"VAT Registration No." validation check goes through without any error.

**4. Actual behavior**
An error occurs with the message "A call to System.Xml.XmlDocument.Load failed with this message: '>' is an unexpected token. The expected token is '"' or '''. Line 1, position 55"

**5. Versions**
In every Business central versions

**Comment by dannoe** [comment]
see https://www.yammer.com/qbsdachpartnernetwork/#/threads/show?threadId=1876461175873536

**Comment by devKomak** [comment]
> see https://www.yammer.com/qbsdachpartnernetwork/#/threads/show?threadId=1876461175873536

Hi. Could you paste solution here?

**Comment by dannoe** [comment]
Sorry, I didn't notice I posted an non-official microsoft yammer group. (and it's even in german 😅)

For SaaS an update/hotfix should be released this week.
For OnPrem - NAV 2018 and forward a CU will be released in september
For OnPrem before NAV 2018 no update is planned. You can try to fix it yourself. A user posted this:
![grafik](https://user-images.githubusercontent.com/7450586/186114886-9c6dee7e-d520-4bce-be3f-5c4acd26859a.png)

Another user posted he had to upgrade 2 Codeunits on NAV 2017:

Codeunit 248 VAT Lookup Ext. Data Hndl
Codeunit 1290 SOAP Web Service Request Mgt.

**Comment by CChub402** [comment]
Perfect. Thanks. It works

**Comment by MarcGretener** [comment]
In case the user is using NAV2016 the hotfix applies to Codeunit 248 and 1290 as suggested.
The hotfix in Codeunit 248, is stated above, however the function SetContentType does not exist in Codeunit 1290 
1) In codeunit 1290 add the Global variable GlobalContentType, DataType Text

2) Add the function SetContentType:
![image](https://user-images.githubusercontent.com/115552762/195089084-d1c260ff-6085-4d2d-a802-3e6b824a4798.png)

3) Modify function BuildWebRequest:
![image](https://user-images.githubusercontent.com/115552762/195090425-3ede060e-d594-4afc-a9ce-0ba006de2638.png)


Done

**Comment by Solitium** [comment]
EU VAT GitHub, Inc

**Comment by Solitium** [comment]
I need EU VAT of GitHub, Inc
