### ISSUE TITLE
AL: Go! does not create the .alpackages folder

### ISSUE THREAD

**Issue by albgen** [microsoft/AL#7149]
Describe the bug
When using AL: Go! to create a new package, the .alpackages folder and files are not created.

To Reproduce
Ctrl+Shift+P to activate the command pallet
Select AL: Go!
Define folder
Select 9.0 Business Central 2022 release wave 2
Select Microsoft cloud sandbox
New package is built but with the following error:

The package cache c:\Users\my username\Documents\AL\ALProject./.alpackages could not be found.

Expected behavior
The result of the AL: Go! process should be a new package that compiles cleanly

Business Central: Version: W1 Business Central 20.0.41086.41354

**Comment by dnpb** [comment]
Hasn't it always worked this way, and you just need to Download Symbols first?

**Comment by christianbraeunlich** [comment]
> Hasn't it always worked this way, and you just need to Download Symbols first?

Yes, the symbols have to be downloaded from the server.

**Comment by EmilDamsbo** [comment]
Closing this since downloading symbols will fix this issue, and there is an easy shortcut via creating the folder manually.

**Comment by albgen** [comment]
The problem is that it cannot download the symbols. Also creating the folder manually is not a solution but a woraround. Anyway have a nice day
