### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by MrDavid5465** [Microsoft/AL#715]
I want to save the result of a report into a blob field so that it can be downloaded at a later time, but when I try to download the file, I don't get a dialogue, I just get a file called DynamicFileHandler.axd

I'm not sure if I'm approaching this correctly or if it's broken

![image](https://user-images.githubusercontent.com/29601581/30882471-10446aa6-a2d7-11e7-8933-ef0481c627b3.png)

**Comment by MrDavid5465** [comment]
#update: I figured out why i was getting DynamicFileHandler.axd, I was not supplying a filename, but now the pdf file that is downloaded is empty. I'm expecting the filesize to be about 104kb

![image](https://user-images.githubusercontent.com/29601581/30883812-6b574284-a2db-11e7-8416-93a2fa52bf37.png)

**Comment by johndcollins** [comment]
Is LicenseStore a global blob variable?
Did you try and save the blob to a record?
What exactly are you trying to accomplish?

**Comment by MrDavid5465** [comment]
License Store is a Blob field in my Table. I am trying to save the report (which is a license) so that it can be downloaded at a later time. It needs to be exactly the same at the reprint time as it was when the license was generated, even if the License information changes. That is why I'm trying to save the report

**Comment by kaspermoerch** [comment]
If LicenseStore is a Blob field on your table, you need to do a CALCFIELDS(LicenseStore) before creating the OutStream.

**Comment by MrDavid5465** [comment]
That worked! Thank you!
