### ISSUE TITLE
no more advanced tooltip on hovering a Label

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/AL#7154]
Please include the following with each issue:

**1. Describe the bug**
It used to be possible hover a label in VS Code together with the ctrl key. It showed the actually definition of the label such that you could easily spot the content of the label without going all the way to it, read it, and jump back to the piece of code using it. That was quite nice! Unfortunately it stopped working.

**2. To Reproduce**
find a codeunit (e.g. 12) that uses a label, find the spot in the code (e.g. line 1236) that uses it (e.g. Error(DocNoMustBeEnteredErr ...), press and hold ctrl key and hover the label with the mouse courser. it will only repeat the label name, but not the actual content.

**3. Expected behavior**
Well, as before (not sure when that was I must say). When I do an extended/advanced hover, I would like to see the definition text of the label, such that I can continue coding without jumping around to find out what the label consists of. 

**4. Actual behavior**
This is what you get currently - not really helpful:
![image](https://user-images.githubusercontent.com/23500845/188373072-16123513-cfc2-468d-810f-96fe724dda5a.png)

**5. Versions:**

- AL Language: 9.5.674382
- Visual Studio Code: 1.71.0
- Business Central: n/a
- List of Visual Studio Code extensions that you have installed: 
AL CodeActions (disabled)
AL Langugage
AL Navigator (disabled)
AZ AL Dev Tools (disabled)

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [n/a] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
