### ISSUE TITLE
Cannot build AL project on MacOS

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7158]
When i run Build command on VS Code (macOs), i get the following error message: "No Build Task to Run Found" 

Other AL Commands like AL:GO, Download Symbols, or Publish are working fine. 

**2. To Reproduce**
Run VS Code on MAC OS
Run Al:Go to make new project
Update launch.json and link to your server
Download symbols
Run Build ⬆️⌘+B

**3. Expected behavior**
 Project is build and app file generated

**4. Actual behavior**
error message "No Build Task to Run Found" 

**5. Versions:**
- AL Language: v9.5.674382
- Visual Studio Code: 1.71.0
- Business Central: not relevant
- List of Visual Studio Code extensions that you have installed: AL Language only

**Comment by salgiza** [comment]
Mmm.. I don't know what's the logic behind it, but I've always compiled AL projects in macOS using Ctrl + Shift + B (that is, Ctrl instead of Cmd).

If I use Cmd + Shift + B, I get the same prompt as you, but I always thought that was expected 😅

**Comment by gntpet** [comment]
you are right @salgiza , ctrl + shift + b is working :) 
confusion is that it's not the same as 'build task' (like on windows). I would say it's a bug :)

**Comment by nndobrev** [comment]
Hi,
 
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern, we will keep it in mind and if we see that it is commonly faced issue, we will re-evaluate it.
 
Thanks,
Nikolay

**Comment by zaidtariq-D360** [comment]
@nndobrev any plan for this fix because seems like it's still the issue.
