### ISSUE TITLE
ValidateTableRelation field Property - Default value is now False

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#716]
In Dynamics NAV C/SIDE environment the default value of the field property ValidateTableRelation is Yes.
In AL, the default value is False. We have to explicity set it to yes if we want the field to behave that way.

As developers we need to want to validate table relations most of the time.

Would it be possible to set the property to True as default? (just as in C/SIDE)

Thanks is advance.

Salut!
Laura Nicolàs

**Comment by esbenk** [comment]
The default value is still true. You only need to specify the ValidateTableRelation property if you want it set to false.

**Comment by LauraNicolas** [comment]
I am using the July Preview database... Is this why I am experiencing the opposite? Was it changed in a later release?

**Comment by esbenk** [comment]
I'm unsure about that, a lot have changed since July. I have just verified on the latest codebase, please re-test on the latest version.

**Comment by MikeGlue** [comment]
I just experienced this same issue and I am using the latest September release. I created a field in my extension that was related to the Item table, and unless I specifically added the "ValidateTableRelation=true" property, I was able to manually type any value into the field.
