### ISSUE TITLE
CreateDateTime does not account for Timezone in OnInstall or OnUpgrade code (this is a bug in your system application)

### ISSUE THREAD

**Issue by CptBlaubart** [microsoft/AL#7160]
**1. Describe the bug**
When using CreateDateTime() in a Upgrade or Install Codeunit, the input Time is always handled as if it was entered in the UTC timezone. Even though the Session knows it is in a different one.

This is a problem because the time-datatype is not affected by timezones but the datetime-datatype is. (it is saved in the database in it's UTC value, and presented to the client with whatever shift is needed).

As we want to patch the data to obsolete our old date- and time-fields we need the new fields to represent the times that have been entered in the old fied in the datetime-fields now.

This is not an issue if we would patch the data in an object run by a user. - However: what's the point of Upgrade-Codeunits if they don't work reliably?!

**2. To Reproduce**
1. copy code below & publish
2. make sure current user is not on UTC timezone.
3. open testpage
4. add test records by filling random values to "myCode", "myDate", "myTime"
5. see how inserting fills the DTInsert field with the same time as entered in the myTime field for each record
6. see how using the UpdateDTAction-Action sets the same values to all the created records at once
7. republish the extension to trigger the upgrade code.
8. notice how the datetimes there assumed you where in a UTC timezone when entering the values

_**Setting the TimeZone in the SessionSettings-Object does not affect the Outcome.**_

**Note**: my example doesn't use Upgrade-tags on purpose. you can just keep publishing with `"forceUpgrade": true` in the launch.json

``` AL

table 99000 "test"
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; MyCode; Code[10])
        {
            DataClassification = CustomerContent;
            NotBlank = true;
        }
        field(2; MyDate; Date)
        {
            DataClassification = CustomerContent;
            NotBlank = true;
        }
        field(3; MyTime; Time)
        {
            DataClassification = CustomerContent;
            NotBlank = true;
        }
        field(4; DTInsert; DateTime)
        {
            DataClassification = CustomerContent;
        }
        field(5; DTUpgrade; DateTime)
        {
            DataClassification = CustomerContent;
        }
        field(6; DTAction; DateTime)
        {
            DataClassification = CustomerContent;
        }
    }

    keys
    {
        key(PK; MyCode)
        {
            Clustered = true;
        }
    }
    trigger OnInsert()
    begin
        DTInsert := CreateDateTime(MyDate, MyTime);
    end;

    procedure UpdateDateTime(UseCase: Option "Upgrade","Action")
    var
        test: Record test;
    begin
        if test.FindSet() then
            repeat
                if UseCase = UseCase::Action then
                    test.DTAction := CreateDateTime(test.MyDate, test.MyTime)
                else
                    test.DTUpgrade := CreateDateTime(test.MyDate, test.MyTime);
                test.Modify();
            until test.Next() = 0;
    end;

}

page 99000 "testpage"
{
    ApplicationArea = All;
    Caption = 'testpage';
    PageType = List;
    SourceTable = test;
    UsageCategory = Lists;
    DelayedInsert = true;

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field(MyCode; Rec.MyCode)
                {
                    ApplicationArea = All;
                }
                field(MyDate; Rec.MyDate)
                {
                    ApplicationArea = All;
                }
                field(MyTime; Rec.MyTime)
                {
                    ApplicationArea = All;
                }
                field(DTInsert; Rec.DTInsert)
                {
                    ApplicationArea = All;
                }
                field(DTUpgrade; Rec.DTUpgrade)
                {
                    ApplicationArea = All;
                }
                field(DTAction; Rec.DTAction)
                {
                    ApplicationArea = All;
                }
            }
        }
    }
    actions
    {
        area(Processing)
        {
            action(updateDTAction)
            {
                ApplicationArea = All;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;
                Image = UpdateDescription;

                trigger OnAction()
                begin
                    Rec.UpdateDateTime(1);
                    CurrPage.Update(false);
                end;
            }
        }
    }
}


codeunit 99000 "test"
{
    Subtype = Upgrade;

    trigger OnUpgradePerCompany()
    var
        test: Record test;
    begin
        test.UpdateDateTime(0);
    end;
}

```

**3. Expected behavior**
The Upgrade Codeunit should generate the same result as the action on the page.

**4. Actual behavior**
The fields updated by the Upgrade-Codeunit behave like they where entered while the user was in the UTC timezone
The fields updated by inserting or using the action on the test-page behave accounting for the time-zone the server/user is in.

**5. Versions:**

- AL Language: 9.5.674382
- Visual Studio Code: 
```
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```
- Business Central: BC20.5
- List of Visual Studio Code extensions that you have installed: i don't have a problem with the dev-environment.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by CptBlaubart** [comment]
additional info / alternative solution:

I'm aware that this behaviour has been set on purpose as MS needs their Saas servers to always run on UTC.
While looking for workarounds I took a closer look at the TypeHelper-Codeunit. It does have a function to get the offset of a timezone to UTC, which works fine... at the current Date! I would've been able to use the TypeHelper if it wasn't for daylight savings time for the Dates on the other half of the year.

If you could expand the function set for that, this issue is solved. So far all the options i see would restrict me to OnPrem

**Comment by CptBlaubart** [comment]
Update:

I built a workaround for OnPrem, I can use for my current situation. 
But as we are also creating AppSource apps, i can't say that the issue is resolved. But i can get resolved by adding some functionality to the "Type Helper" Codeunit. Should i create a new issue under "Application Enhancement"?

i wrote these two procedures and used the "GetUTCDateTimeFromLocal()" function instead of the "CreateDateTime()" in the upgrade Usecase.

``` AL
    procedure ParseDateAndTime2Integers(_Date: Date; _Time: Time; var yyyy: Integer; var mm: Integer; var dd: Integer; var h: Integer; var m: Integer; var s: Integer; var ms: Integer)
    begin
        yyyy := Date2DMY(_Date, 3);
        mm := Date2DMY(_Date, 2);
        dd := Date2DMY(_Date, 1);

        ms := _Time - 000000T;
        h := ms DIV 1000 DIV 60 DIV 60;
        ms -= h * 1000 * 60 * 60;

        m := ms DIV 1000 DIV 60;
        ms -= m * 1000 * 60;

        s := ms DIV 1000;
        ms -= s * 1000;
    end;

    procedure GetUTCDateTimeFromLocal(LocalDate: Date; LocalTime: Time): DateTime
    var
        dnDateTime: DotNet DateTime;
        dnTimeZoneInfo: DotNet TimeZoneInfo;
        CurrSessionSettings: SessionSettings;
        yyyy, mm, dd, h, m, s, ms : integer;
    begin
        CurrSessionSettings.Init();
        dnTimeZoneInfo := dnTimeZoneInfo.FindSystemTimeZoneById(CurrSessionSettings.TimeZone());

        ParseDateAndTime2Integers(LocalDate, LocalTime, yyyy, mm, dd, h, m, s, ms);
        dnDateTime := dnDateTime.DateTime(yyyy, mm, dd, h, m, s, ms);
        exit(dnTimeZoneInfo.ConvertTimeToUtc(dnDateTime));
    end;
```
There is probably a more efficient way to init the DotNET DateTime-Objects. Maybe it would also make sense to pass the timeZoneid as a parameter instead of getting it from the SessionSettings, for more flexibility. But it serves my purpose and I think it's easy to adapt for one of your guys into the BaseApp.

**Comment by kalberes** [comment]
This is a runtime issue not strictly related to our repo. Official answer:
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
