### ISSUE TITLE
Compiler Error AL0449 "The alias '{0}' is already declared."

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#7165]
Hi there, 

There are 2 separate AL projects with .net declarations. 
Similar .net wrappers are created in each.
1st project - doesn't have such an error, but the second shows 
![image](https://user-images.githubusercontent.com/31474116/190071849-19b6c93e-6ee3-4e61-9387-58c4caf5730e.png)

Why is that happening? Please advise.

**Comment by dnpb** [comment]
Two projects open in the same one workspace, or what?

**Comment by dkorinets** [comment]
nope, workspaces are separate.

**Comment by thloke** [comment]
Are there any dependencies between the two projects, or on any other projects?

**Comment by dkorinets** [comment]
Both of the projects are using the same .net libraries

**Comment by thloke** [comment]
Do they have the same dependencies in their app.json?
