### ISSUE TITLE
Copies wrong sql statement

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/AL#7166]
Please include the following with each issue:

**1. Describe the bug**
When you debug and have enableSqlInformationDebugger: true or enableLongRunningSqlStatements: true in launch.json you get the databasestatistics section in the debugger pane. Here you can select a statement, right click and copy, but it seems that no matter which statement you copy, you always get the statement from SQL0.

**2. To Reproduce**
1. Add enableSqlInformationDebugger: true and enableLongRunningSqlStatements: true to launch.json
2. Add a breakpoint anywhere in code after a few database reads.
3. Start debugging.
4. Execute the code to hit the breakpoint.
5. Expand the database statistics in the debugger pane.
6. Expand any statement except SQL0.
7. Select the sql statement.
8. Right click and select copy.
9. Paste the statement anywhere.
10. Now you will notice that you didn't paste the selected sql statement.

``` AL
page 50001 "MyPage"
{
    Caption = 'mypage';
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    actions
    {
        area(Processing)
        {
            action(ActionName)
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    Customer: Record Customer;
                    Vendor: Record Vendor;
                    i:Integer;
                begin
                    Customer.Get('10000');
                    Vendor.Get('10000');
                    i:=0; //Set breakpoint here
                end;
            }
        }
    }
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
I expect that the correct sql statement is copied.

**4. Actual behavior**
Notice the sql statement in SQL9:
![Skærmbillede 2022-09-15 152626](https://user-images.githubusercontent.com/31523525/190416311-a989a0d8-672c-4f86-881b-9ef19677b6d6.png)

Select and copy.
![Skærmbillede 2022-09-15 152656](https://user-images.githubusercontent.com/31523525/190416272-75d42895-19dc-4e6a-963f-9fbd6805a752.png)

Paste and you get:
![Skærmbillede 2022-09-15 152729](https://user-images.githubusercontent.com/31523525/190416161-6759a824-e74f-468f-9b21-6bc1dcc7e0af.png)

...a different sql statement. (SQL0)

**5. Versions:**

- AL Language: v9.4.663067
- Visual Studio Code: 1.71.1
- Business Central: 20.2.41144.41959
- List of Visual Studio Code extensions that you have installed:
Al Language

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.48153.0 and VS Code Extension Version 11.0.698501. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
