### ISSUE TITLE
See number of primary key fields when showing primary key for table fields in IntelliSense

### ISSUE THREAD

**Issue by Quivelus** [microsoft/AL#7167]
Hi,

Really like the idea that was implemented recently of showing the primary key fields via IntelliSense. References:
 - https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/see-primary-key-table-fields-intellisense
 - https://experience.dynamics.com/ideas/idea/?ideaid=ef837bea-68ad-ea11-8b71-0003ff68c1c1

It would be great to see the number of primary key fields added to this feature. Some tables only have one primary key field (like Item), some have many. For tables that are not used often it isn't always clear how many primary key fields must be included in let's say a Get() statement. In order to see this easily, for example to not need to scroll the whole list of all possible fields, it seems nice if we're able to see the actual number of primary key fields.

This could be done via showing something like 1/5, 2/5, 3/5, 4/5, 5/5, (where now we just see 1, 2, 3, 4, 5) or just showing the total number of primary key fields somewhere.

Thank you for considering.

Regards,
Filip

**Comment by IvoMol** [comment]
If this modification is implemented, please consider also marking the FlowField and FlowFilter fields in the same place:
- Journal Template Name (PK1/3)
- Journal Batch Name (PK2/3)
- Journal Line No. (PK3/3)
- Posting Date
- Document No.
- Remaining Quantity (FlowField)
- Quantity
- Date Filter (FlowFilter)
- Location Code
- Location Filter (FlowFilter)
etc.

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/191568966-933f86a1-7022-4fc6-aa46-e4dfc4473771.png)

**Comment by Quivelus** [comment]
> ![image](https://user-images.githubusercontent.com/12760483/191568966-933f86a1-7022-4fc6-aa46-e4dfc4473771.png)

Hi Kálmán, the reason I posted on Github is because at BC Techdays in Antwerp this was proposed to me at the ask-the-expert booth from MS, in favor of adding it to the original BC Idea(s). No problem if BC Ideas is the way to go for you. I already commented on the original BC Idea and that comment suffices for me.
