### ISSUE TITLE
Phone Client: Repeater in NavigatePage does not show all entries

### ISSUE THREAD

**Issue by vovazvv** [microsoft/AL#7168]
**1. Describe the bug**
Repeater in NavigatePage does not show all entries

**2. To Reproduce**
- Open Web Client
- Install the test project
- Find "List Wizard" via search menu
- Add a bookmark for "List Wizard"
- Open Phone Client
- Select "List Wizard"
- Scroll to the bottom of the list, note it stops at 14

**3. Expected behavior**
Can view all entries

**4. Versions:**
- AL Language: v9.5.674382
- Visual Studio Code: 1.71.1
- Business Central:
   --Web Client: Version: CH Business Central 20.5 (Platform 20.0.45448.46476 + Application 20.5.45456.45681)
   --Phone Client: 3.7.81.61 (for Android) 

[WizardError.zip](https://github.com/microsoft/AL/files/9598350/WizardError.zip)

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
