### ISSUE TITLE
Rapid Application Publish - Permissions error

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7169]
Please include the following with each issue:

**1. Describe the bug**
At BCTechDays 2022, we were encouraged to make use of the existing tooling, including the 'Rapid Application Publish' feature. However, trying to do so results in various failures.

**2. To Reproduce**

- We're developing against sandboxes on our online CDX saas tenant (so no Docker involved, no onprem)
- Apps are published in VS Code via 'Publish without Debugging'
- A startupObject (page) has been configured in the launch.json
- Normal publish works fine

- Perform some minor changes (changing the **content** of a procedure, not the parameters, signature, ...)
- Publish the app in VS Code via 'Rapid Application Publishing'
- Following error occurs

![image](https://user-images.githubusercontent.com/25268332/191219487-f3b18865-6fc7-4bac-9d23-55b5deb313fe.png)

**3. Expected behavior**
Rapid Application Publishing to work in more scenarios, or at least the error to be more clear.

**4. Actual behavior**

Error stack

```
Uw licentie verleent u niet de volgende machtigingen voor Page ESCI Imported Documents: Execute.

Zie de pagina Effectieve machtigingen voor meer informatie over uw machtigingen. Als u een probleem wilt rapporteren, raadpleegt u de volgende serversessie-id: 1267733.

Page Geïmporteerde documenten has to close.

Interne sessie-id: 
0482deb6-693e-438d-92c5-34bd79b56dcf

Id van Application Insights-sessie: 
8f9154ad-559b-4e0b-85ae-7ae1f0b44ab0

Id van clientactiviteit: 
cd7fe0f1-05ce-49b4-a0c9-142cbdb453f5

Tijdstempel van fout: 
2022-09-20T08:52:05.7232594Z

```

**5. Versions:**

- AL Language: v9.5.674382
- Business Central: Versie: US Business Central 20.4 (platform 20.0.44266.46375 + toepassing 20.4.44313.44365)

**Comment by kalberes** [comment]
Just for curiosity, the user who did the publish has rights to Page ESCI Imported Documents on all companies and teh same the one for RAD.

**Comment by fvet** [comment]
1. User is SUPER on all companies

![image](https://user-images.githubusercontent.com/25268332/191949836-61beb1b3-013e-4cf8-ba98-6dfd74cbb772.png)

2. Did not remove any application object.
    As far as I remember, I only changed some code lines inside a procedure, no signature changes.

Will try to use RAD bit more upcoming week and report any similar issues - included the rad.json content - in this thread.

**Comment by kalberes** [comment]
@fvet

I do not have a repro for your issue.  Well, I tried @tyurm s repro. I have no repro there. 
Can you check that the app that you try to publish with RAD has an Entitlement folder with <your app id>.xml in it  (you can open the app with 7.zip)

**Comment by tyurm** [comment]
Hi @kalberes 

I have checked xml file after first-regular publish, and after second-RAD publish, it is the same:

```
<?xml version="1.0" encoding="utf-8"?>
<Entitlement MetadataVersion="130000" Name="0fb1406e-8858-477f-85c0-e9faa1335453" Type="Implicit" xmlns="urn:schemas-microsoft-com:dynamics:NAV:MetaObjects">
  <ObjectEntitlements>
    <Permission Type="0" ID="50100" Value="15" />
    <Permission Type="1" ID="50100" Value="16" [/>](url)
  </ObjectEntitlements>
</Entitlement>
```
[Default publisher_ALBug_1.0.0.0.zip](https://github.com/microsoft/AL/files/9733218/Default.publisher_ALBug_1.0.0.0.zip)


I have also tried to download source code from Sandbox after RAD publishing, and there was only these files in the archive (no table file):
<img width="977" alt="image" src="https://user-images.githubusercontent.com/45788765/194535348-5f3083bc-4a92-419a-9280-73f91f4eaed3.png">

**Comment by fvet** [comment]
@kalberes

Just checked, the app file used for RAD publishing contains an entitlement folder / XML file.

![image](https://user-images.githubusercontent.com/25268332/194540403-f2382dc3-6fb4-414f-bdc6-f81f93f3cb40.png)

Last attempt when I tried to use the RAD publishing was no longer giving a permission error, but in fact, my extension seems to have disappeared from the UI instead.

Here's the repro steps:

- Opened my workspace (Core + dependend Item app)
- Core app got published (Full)
- Item app got published (Full)
- Open web client --> pages (Import template) found via Search
- Empty rad.json files for both apps
- Perform small table change (added field)
- Package app
- rad.json got updated
- Rapid Publish (item app) -> no error in VS Code
- Open web client --> Suddenly my extension seems to have dissappeared ? (no more pages in the search results)
- Only option to restore is doing a full publish again.

I would have expected VS Code to either complain that RAD publish is not supported for those cases, either for the RAD to do a good publish and properly update the extension on the server.

---
App file that got published during RAD contained only the changed table.
![image](https://user-images.githubusercontent.com/25268332/194540895-356d1f71-861d-4f46-8968-3b0eb763ae5c.png)

---

https://user-images.githubusercontent.com/25268332/194541836-5ea6670c-d2d0-44db-b4a9-ef40c19bf114.mp4

**Comment by kalberes** [comment]
@fvet
You should never manually delete the rad file, unless you reload the whole project. That is an internal file handled by the workspace. If you interact with it, while your project is opened then you can make things worse.

I do not understand the below
_Open web client --> Suddenly my extension seems to have disappeared ? (no more pages in the search results)_
Are you saying that if you open your extension management page the extension you have just published is not there?
Or that

**Comment by fvet** [comment]
> @fvet You should never manually delete the rad file, unless you reload the whole project. That is an internal file handled by the workspace. If you interact with it, while your project is opened then you can make things worse.

I'm fully aware of that. I've not manipulated the file in any way.
I meant to state that the 'rad.json was **empty**' after doing the full publish, so I just double checked the content of it to got a clean start to do perform changes and do the RAD.

> I do not understand the below _Open web client --> Suddenly my extension seems to have disappeared ? (no more pages in the search results)_ Are you saying that if you open your extension management page the extension you have just published is not there? Or that the navigation(search) is not working after RAD publish?

The extension **is** still there (and it's marked as **installed**). However, none of my pages are accessible (the 'Imported Document' bookmark dissappeared from my rolecenter, the 'Import Template' pages do not show up in the search results, ...)

**Comment by fvet** [comment]
Server is BC 21.0

App seems 'gone' for the user, though still installed in the extension management.

![image](https://user-images.githubusercontent.com/25268332/194555806-f5744e4d-01b2-4c0e-9a4c-ee3019a5fc76.png)

**Comment by kalberes** [comment]
Yes, we have just released a hotfix for 21.X, 21.0 but that will only be available for SAAS, in the next few days. OnPrem unfortunately RAD will be broken (no modified objects are taken into consideration) until the 21.1 release.

**Comment by kalberes** [comment]
@tyurm 
That when you download the source after RAD you do not see the original app package (that you have in vscode) should be fine. You have only published the page. The table is there, its dll was loaded, its schema created, and it is "running".
For some reason you get a permission issue. Like the entitlements are not reloaded. Will involve the team handling the permission system.

**Comment by fvet** [comment]
Just another heads up on trying to benefit from 'Rapid Application Publishing'.

- I've a workspace with 2 dependend apps (Core + Dependend App)
- 'Publish full dependency tree for current project'
- Both apps are successfully published
- I perform a small code change to a page object in the Core app
- 'Rapid Application Publish without Debugging'
- Debug console: Success: The package 'Dynavision_Dynavision Core_20.0.15.0.app' has been published to the server.
- Open the webclient
- All my objects from the 'Core app' seem to have dissappeared.
- Only option to restore is to run 'Publish full dependency tree for current project' again :(

**Comment by kalberes** [comment]
@fvet 
Can you please create a new github issue for this problem.  That we accept is another bug. One problem one bug,
I guess the Core is there if you look in Extension managment unly uninstalled. What was your dependency publishing option?
