### ISSUE TITLE
Missing Code Cop Warnings AA0139

### ISSUE THREAD

**Issue by Loisel21** [microsoft/AL#7170]
**Title**
Missing Code Cop Warning AA0139

**Description**
In our app (Codeunit with 1400 lines) the warning for AA0139 is not displayed. In a few other codeunits (around 800 lines) it does work. 
So i copied the Codeunit 80 from the base app and the same thing happened here. With a fresh codeunit it does work.
I also noticed that the problems and the output (by building the app) of the Test.Codeunit are different (both files attached).
In the output are a few A00139 warnings, that i can not find in the problems.

**Expected behaviour**
Warning should appear

**Example**
![image](https://user-images.githubusercontent.com/61054888/191223210-5bb9bcba-7fd8-4058-bd98-91002cd4e3d4.png)
![image](https://user-images.githubusercontent.com/61054888/191223244-1b30fd0e-e3cb-4ffe-bafa-a12dd1663105.png)

- AL Extension Version: v10.0.673593

- Server Version: DE Business Central 21.0 (Platform 21.0.45803.0 + Application 21.0.45833.0)

**AL code sample that triggers the issue**
https://comsol-my.sharepoint.com/:f:/g/personal/lno_comsol_ag/Ev4jN58mEDhBr-GISkSsK2EBpZHPq_S4MxrfbNHJuw5KDg?e=0d11Mz
[Test.Codeunit.al_Problems.txt](https://github.com/microsoft/AL/files/9606237/Test.Codeunit.al_Problems.txt)
[Test.Codeunit.al_Output.txt](https://github.com/microsoft/AL/files/9606238/Test.Codeunit.al_Output.txt)

**Comment by thloke** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!
