### ISSUE TITLE
Code Cop Warning Suggestion: Temporary Table with Autoincrement

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#7171]
According to this documentation https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoincrement-property

"The AutoIncrement property does not work with Dynamics 365 Business Central temporary tables."

It would be nice if there was a warning pointing to this so we can find out faster what's not working right. 

Many thanks in advance

**Comment by qutreson** [comment]
This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
