### ISSUE TITLE
Return InStream Bug

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/AL#7172]
**1. Describe the bug**
When using an "InStream" object as return in a procedure the instream object seems to be empty in the calling code.

**2. To Reproduce**
I created two procedures to demonstrate:

``` AL
    procedure TestProcedure()
    var
        IStream: InStream;
        TestText: Text;
    begin
        IStream := GetInStreamFromText('HELLO WORLD!');
        IStream.ReadText(TestText);
        MESSAGE(TestText);
    end;


    procedure GetInStreamFromText(NewText: Text) IStream: InStream
    var
        TempBlob: Codeunit "Temp Blob";
        OStream: OutStream;
        IStream2: InStream;
        TestText: Text;
    begin

        TempBlob.CreateOutStream(OStream);
        OStream.WriteText(NewText);
        TempBlob.CreateInStream(IStream);
        TempBlob.CreateInStream(IStream2);
        IStream2.ReadText(TestText);
        MESSAGE(TestText);
        Exit(IStream);
    end;
```

**3. Expected behavior**
The returned InStream should contain my Text "HELLO WORLD!" 

**4. Actual behavior**
The content of the returned instream is empty.

**5. Versions:**

- AL Language: v9.5.674382
- Visual Studio Code: 1.71.2
- Business Central: 20.05. Germany
- List of Visual Studio Code extensions that you have installed:

**Comment by dnpb** [comment]
What if you remove the `Exit(IStream)`? That will cause a self-assignment, so I wonder if it's tripping something up. `IStream` is already the return variable, so no need to explicitly return it. Of course, self-assignment shouldn't clear it, but maybe it'll be a workaround in the interim.

**Comment by JulianTillmann** [comment]
I've tried a named return, unnamed return and a parameter by reference, but to no avail. 

But somebody on yammer pointed out, that when you have the tempblob as a global variable it works. So maybe that will point you in the right direction?

**Comment by dnpb** [comment]
Well, my understanding of the deep mechanics of streams is lacking, but I might guess it is simply that the Temp Blob owns the data - and when said Blob goes out of scope, it disposes the data, and there's no longer anything for the InStream to read.

**Comment by bctstkla** [comment]
Hi @JulianTillmann , what if you change the procedure to instead pass the instream-variable as a parameter of type var instream (ie by reference) 
procedure GetInStreamFromText(NewText: Text; var IStream: InStream)

and then call

 GetInStreamFromText('HELLO WORLD!', IStream);   ?

**Comment by dnpb** [comment]
> I've tried a named return, unnamed return and a parameter by reference, but to no avail.

;-)

**Comment by JulianTillmann** [comment]
@bctstkla 
unfortunately that does not work

as I understand it the local tempblob variable is removed from memory after exiting the procedure and this seems to remove the instream content as well. Seems to be always a "by reference" 

I would like to know if that's a bug or by design. If it's by design there should be documentation about this and maybe a warning by a code analyzer

**Comment by dnpb** [comment]
From my PoV it is fairly intuitive that streams are just 'pipes', which can only read or write data if they have something 'real' behind them storing the data. So if that source goes away, reads will get nothing, and writes will do nothing (good). Extra clarity in documentation is never a bad thing, though! :-)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. If you do have suggestions for improving the docs, you can suggest the improvements on the releveant docs page!
