### ISSUE TITLE
CodeCop: Rule AA0139 does not trigger for array elements

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7173]
**1. Describe the bug**
The rule [AA0139](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0139) (possible text overflow) does not trigger when the value that exceeds the length is an element of an array.

**2. To Reproduce**
See the code below:

``` AL
    local procedure ParentFunction()
    var
        ValueOne: Code[20];
        ValueTwo: Code[40];
        Values: array [20] of Text;
    begin
        ChildFunction(ValueOne); // warning AA0139 is not issued - correct
        ChildFunction(ValueTwo); // warning AA0139 is issued - correct
        ChildFunction(Values[1]); // warning AA0139 is NOT issued - NOT correct
    end;

    local procedure ChildFunction(Code: Code[20])
    begin
    end;
```

**3. Expected behavior**
The rule should trigger if the array elements are of larger size

**4. Actual behavior**
The rule should trigger.

**5. Versions:**

- AL Language: v10.0.673593
- Visual Studio Code: 1.71.2

**Comment by qutreson** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!
