### ISSUE TITLE
The AL extension highlighter treats "End" in a field name as if it was the "end" keyword.

### ISSUE THREAD

**Issue by salgiza** [microsoft/AL#7174]
**1. Describe the bug**
When highlighting the code, the extension considers the word "end", as part of a field name, as if it was the end keyword. This also affects the begin..end colours of the method the field is used in.

**2. To Reproduce**
Just create a field with the word "End" (e.g., "End Date") and use it in a block of code.

![CleanShot 2022-09-23 at 13 57 34](https://user-images.githubusercontent.com/6630306/191955284-e8e34b09-e7e0-48f0-b7ca-0626fd327cea.png)

As you can see in the previous screenshot, the End in "End Date" is highlighted as a reserved keyword, and the "end" at the end of the procedure has a different colour from the "begin" keyword.

**3. Expected behavior**
The End in "End Date" should not be highlighted.
The "end" at the end of the procedure should have the same colour as the begin keyword.

**4. Actual behavior**
The End in "End Date" is highlighted.
The "end" at the end of the procedure is highlighted in red.

**5. Versions:**

- AL Language: 
- Visual Studio Code: 10.0.683327
- Business Central: -
- List of Visual Studio Code extensions that you have installed: -

**Comment by dnpb** [comment]
Ditto `case`, etc.:
https://github.com/microsoft/AL/issues/7041

**Comment by salgiza** [comment]
@dnpb You are right! Closing this ticket as a duplicate of #7041 , then.

My searching skills obviously failed on Friday 😅
