### ISSUE TITLE
CodeAnalyzer - rule "AA0072" ignores triggers and event subscriber

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#7177]
hi,

AL Language v10.0.673593

the rule AA0072 does not regonize wrong named variables in the following objects and triggers:

for codeunits: EventSubscriber with local variables

for pages: "OnAction" , "OnDrillDown" , "OnLookup", " OnValidate", "OnAssistEdit" with local variables

for reports: "OnAfterGetRecord", "OnPreDataItem" with local variables

for tables: "OnValidate", "OnLookup" with local variables

for tableext: "OnValidate", "OnLookup" with local variables

for pageext: "OnAction" , "OnDrillDown" , "OnLookup", " OnValidate", "OnAssistEdit" with local variables

**Comment by dnpb** [comment]
Yup, MS correctly stopped warning us about _argument_ names, since we can't control those, but I suspect the fix is applied to broadly and also applies to local variables (maybe arguments and locals are considered the same) - but it must not be, please :)
