### ISSUE TITLE
CaptionML for Areas compile but fail Technical validation

### ISSUE THREAD

**Issue by viktoreinars** [Microsoft/AL#718]
Adding CaptionML to area in page compiles fine in Visual Studio Code but fails technical validation when publishing to AppSource.

![image](https://user-images.githubusercontent.com/3970209/30988679-9a7f8480-a48a-11e7-9120-fec0d3dc06db.png)

**Comment by StanislawStempin** [comment]
This is only because App Validation team used a newer build. It will fail during compilation on newer builds.
