### ISSUE TITLE
Object level granularity for the resourceExposurePolicy

### ISSUE THREAD

**Issue by quadfin** [microsoft/AL#7183]
Currently the resourceExposurePolicy settings (allowDownloadingSource, includeSourceInSymbolFile) are global (to the app).
However, the allowDebugging setting can be 'overridden' at the variable and procedure level with the [NonDebuggable] AL attribute.

It would be **EXTREMELY** (did I emphasise that enough?) useful if the other two settings could be overridden at object scope.

Perhaps an attribute for each--
allowDownloadingSource=true   ==> [DisallowDownloadingSource] = prevents current object source from downloading
includeSourceInSymbolFile=true ==> [ExcludeSourceInSymbolFile] = excludes current object source from the symbol file

That would allow protecting IP at a granular level without having to break up the application into library or dependent apps (which has tremendously high overhead for existing apps that were not originally designed for that model -- as that is a relatively recent language addition).

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/195414895-ffbdc1ad-c28b-4410-ac36-9044b4c0dddc.png)

But besides I will bring it in front of our PM, since I agree more could be done here.
