### ISSUE TITLE
BC20 cu04 US data migration issue

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/AL#7185]
Hello, during the data upgrade from BC14 to BC20 cu04 onprem I got a strange issue. I am running the data upgrade on the BC20 and the process takes unnaturally longer than it should and stops without any error. I changed timeouts on the server instance settings, but it didn`t help. I tried to run data upgrade on three different versions of BC, but got the same issue. (Database size ~75 GB).
The sync process took 30 minutes. The data upgrade took 15 hours and stopped.
Do you have any ideas about what can be wrong?

![image](https://user-images.githubusercontent.com/66109755/193597209-c75b3fff-b9d5-478e-81b9-e93d35029a87.png)

**Comment by dnpb** [comment]
This repo is for issues in the AL language or compiler or surrounding tools, so data-upgrade seems off-topic.

**Comment by OSH-ZT** [comment]
Ok, got it, sorry.
