### ISSUE TITLE
Creating Extension using W1 installation.

### ISSUE THREAD

**Issue by mvdheijkant** [Microsoft/AL#719]
The AL-Extension overview page says following:
NOTE: To deploy code built using this extension you need a NAV Developer Preview Azure Gallery image available at https://aka.ms/navdeveloperpreview.

So I’m now very concerned that I’m asking for the impossible or at least asking for a feature that’s not yet supported.

Is it possible to have a complete on-site Development environment running Dynamics W1 2018, instead of developing on Azure?

If it's possible than please refer to my original question 713 for further clarification.

I'm very sorry for this very elaborate way of asking my question.
But my previous question was'nt answered.

**Comment by Gallimathias** [comment]
Yes, this can be done without any problems.

Simply use Docker to drag the current image and install the. al extension in vs code.

You can get data from the gallery, your own Azure machine, GitHub or just ask for it ;).

**Comment by mvdheijkant** [comment]
I appreciate your answer, and I understand why Microsoft is pushing towards Azure and Docker.
But we are still very devoted to developing on PC's, Terminal Server or VM's running in On-Site Hyper-V,

So, when having installed a local VM with Windows 10, including a SQL2016 Server, Navision 2018, VS-Code and AL-Extension. Does anyone have this configuration up and running.
Because this is where my question originated (713). 
This configuration is having a problem using W1 Symbol files and publishing to a local (not a cloud installation) Navision ans SQL.

**Comment by Gallimathias** [comment]
First of all, the use of dockers does not speak against local development. Your Docker container is then on your PC.

2. nav DVD can be extracted from a docker container. In the older previews the nav folder can be found under c.

3. I recommend to use docker at least as long as it is still a Preview / Early Access. What speaks for you against the use of Docker?

**Comment by StanislawStempin** [comment]
At the moment we do not officially support dev environments others than obtained through aka.ms/navdeveloperpreview or Docker images. 
In theory if you mimic the exact setup of these images you could do development in your own local setup but we don't encourage it. 

For NAV 2018 release we are working on a few features that will make it simple to set up a local development environment.
