### ISSUE TITLE
Enforce Substring start index must be more than 1 during compilation

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/AL#7192]
Hi AL Language Development Team,

Could you enforce the start index of **Substring(...)** to be more than 1 during compilation?

We encountered an issue where users run an action that triggers the following code.
![image](https://user-images.githubusercontent.com/69611495/194220474-06fcd5ab-9442-4e29-8bef-b7b48e4c0f66.png)

And they got this error during runtime.
![image](https://user-images.githubusercontent.com/69611495/194220681-e4c5130b-8d01-4744-81d6-1e175d1fb8d6.png)

I think this error can be prevented by enforcing the above rule. Thank you.

Kind regards,
Tuan Nguyen

**Comment by pri-kise** [comment]
I guess every String Method that supports a 1-Based StartIndex should lead to compile time errors.
e.g. https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-remove-method

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
