### ISSUE TITLE
Error - (Reason: Token StartAttribute in state Element Content would result in an invalid XML document. ) when combining TableRelation and OnAfterValidate/OnBeforeValidate trigger in OnModify section of TableExtension

### ISSUE THREAD

**Issue by VitaliiKanishchev** [microsoft/AL#7193]
![image](https://user-images.githubusercontent.com/115148088/194284586-99931b62-37f2-43aa-9e8b-3b9e14edc37a.png)

**1. Describe the bug**
It is impossible to publish the app, that contains TableRelation and OnAfterValidate/OnBeforeValidate trigger together in one Modify("Field Name") construction for TableExtension.

**2. To Reproduce**

1. Create TableExtension for "Sales Header"
2. Add modify("Salesperson Code") with TableRelation and OnAfterValidate/OnBeforeValidate trigger. Trigger can be empty.
      
 ```
 modify("Salesperson Code")
        {
            TableRelation = "Salesperson/Purchaser" where("Salesperson/Purchaser" = const(Salesperson));

            trigger OnAfterValidate()
            begin
            end;
        }
```
3. Try to publish it.

**3. Expected behavior**
Publishing without errors.

**4. Actual behavior**
Error:  The request for path /DynamicsNAV-DEV/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Token StartAttribute in state Element Content would result in an invalid XML document.

**5. Versions:**

- AL Language: 10.0.687650
- Visual Studio Code: 1.70.0
- Business Central: 14; Business Central Spring '19 Release; runtime: 3.0
- List of Visual Studio Code extensions that you have installed: AL Extension Pack by waldo

**Comment by thloke** [comment]
Hi, I noticed this was reproduced against BC14. Does this reproduce against the latest release (BC21)? If it's BC14 only, this will need to go through support as it's not for this repo.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
