### ISSUE TITLE
Compiler is using wrong symbols to compile in Multi-Root project

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7195]
**1. Describe the bug**
I do have two extensions  A & B in multi-root project setup. 

Extension B, depends on Extension A. 

Extension A is using symbols from W1 
Extension B is using symbols from Italian localization. 

When I compile Extension B, it first compiles dependecy A & then itself. Both projects are getting compiled using symbols from Extension A. 

**2. To Reproduce**
Make two simple projects in multi-root configuration.
for project A download symbols from w1 version
for project B download symbols from italian version

for project B add some code that works in base version only. For e.g. use "Prices Including VAT", which does not exist in Italian version, but exist in w1 version.

```
pageextension 50364 pageextension50364 extends "Sales Order"
{
    layout
    {
        addafter("Prices Including VAT")
        {
            field("Gen. Bus. Posting Group"; "Gen. Bus. Posting Group")
            {
                ApplicationArea = All;
            }
        }
    }
}
```

You will see, that extension will compile successfully, but you won't be able to deploy it to Italian version. 

**3. Expected behavior**
I would expect that each extension is compiled using the symbols from each folder, and I should see compiler error while compiling extension B, since i'm referencing non-existing control.

**4. Actual behavior**
Extension B is compiled using symbols from project A.

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: 1.71.2
- Business Central: 20.5.45456.47314 (italian)
- List of Visual Studio Code extensions that you have installed: not applicable

**Comment by kalberes** [comment]
If you have a workspace with project references extension B will resolve symbols defined in A and referenced in B from the project A and not the extension A. App(extension) references are resolved from the individual package cache folders.
 Composition though will be tricky, if you are using propagateDependencies, since I think then what B delegates will be taken into consideration, Is that your issue?

**Comment by gntpet** [comment]
When I compile my Italian extension, I expect it to be compiled against symbols stored in Italian extension .alpackage folder, not with a symbols from some other extension.

**Comment by kalberes** [comment]
But are you using propagateDependencies? Since if not thigs are expected to work like that and this is a big bug.

**Comment by gntpet** [comment]
I'm not using propagateDependencies

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

Our recommendation is to set a global packages cache using the `al.packageCachePath` setting (either on user or workspace level)
