### ISSUE TITLE
Code Action : Convert to use new ActionRef syntax ... is truncated?

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7196]
Please include the following with each issue:

**1. Describe the bug**
Not sure if this is VS Code / setting / AL related.

When trying to use the new 'Convert to use new ActionRef syntax ...' code action via the light bulb on a 'Promoted = true' code line, I get below suggested code actions. It's not clear to which scope each action belongs... ('--> Apply to ...' is missing)

![image](https://user-images.githubusercontent.com/25268332/194502051-50205c57-dcee-45e6-89e5-5560847e63cb.png)

**3. Expected behavior**
At BC Techdays, below actions were presented

![image](https://user-images.githubusercontent.com/25268332/194502128-5397f0a4-ec89-4f23-999b-b41278a5f60e.png)

The code actions text should contain the scope / full text ('--> Apply to ...').

**4. Actual behavior**
The code actions text is truncated.

**5. Versions:**

- AL Language: v10.0.687650
- VS Code: Version: 1.72.0 (system setup)

**Comment by NKarolak** [comment]
I just wanted to report the very same!
![image](https://user-images.githubusercontent.com/34504100/195536797-9f1dde5c-efef-480d-8eb1-cc87ebc038b5.png)
