### ISSUE TITLE
V2 package fileName extension App - signing error

### ISSUE THREAD

**Issue by gprodware** [Microsoft/AL#720]
Hi,

i am using the september update and noticed that V2 package fileName extension have changed to *.app from *.navx

Signtool.exe sign /f "C:\Users\gdarmon\Documents\MyCodeSigningCertificate.pfx" /p **** /t http://timestamp.verisign.com/scripts/timestamp.dll "C:\TMP\Control_1.0.0.0.app"

I am gtting the follwoing error when trying to sign the app file
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: C:\TMP\Control_1.0.0.0.app
Thanks,

Gill

**Comment by hvogelpohl** [comment]
when i rename it to navx signing works (inside the file saying it's NAVX). It doesn't have to be correct way. ;-)

**Comment by gprodware** [comment]
That is what i did and worked for me too.

**Comment by freddydk** [comment]
On the upcoming October Preview you will be able to get the navsip.dll from the container and register it on the VM. The NavContainerHelper will have a function called get-navcontainernavsip - which will copy and register navsip on the host (Azure VM or your local docker host)
You also need signtool, which you get from installing Visual Studio if you do not have it. On the azure Vm for october preview you will find c:\demo\install-vs2017community.ps1, which you can run to install VS2017 Community and the Win10 SDK (including signtool).
Now you should be able to open the Visual Studio Developer prompt and sign your .app file.

**Comment by hvogelpohl** [comment]
@freddydk It's actually **Install-NAVSipCryptoProviderFromNavContainer**. Also, I had to manually stop-start the docker service to have access to the files. Once I did that .app file signing was not problem at all.

**Comment by stanuj** [comment]
Hi,

I'm considering the steps from the link, which is as followed, to resolve code signing issue:

https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-an-extension-package

Please ensures that the above link will respond correctly or not?

If yes, I’m getting below error:

![inkedcommand error_li](https://user-images.githubusercontent.com/32701699/35112049-dbe57cac-fca2-11e7-8c2a-8c67fcbdf573.jpg)

Please provide us the guidance to resolve this issue.
