### ISSUE TITLE
There should be a warning for Primary Key Fields with a TableRelation + ValidateTableRelation = false

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/AL#7202]
Please include the following with each issue:

**1. Describe the bug**
`The <Name> field on the <TableName> table cannot be renamed from "" to "<new value>". When a field has a relation defined, the field cannot be renamed to and from zero or an empty value.`
So as you can see, there is no way the value "" can ever be changed, once the record is saved.
I suggest that this should throw a warning.
Some Context:
Table A: DataPerCompany = false, has a field with TableRelation to "Table B".Field + ValidateTableRelation = false. The field is a part of the Primary Key.
Table B: DataPerCompany = true + field from Table Relation in Table A is null.

**2. To Reproduce**
Create a Table with infos from description. If you need any more infos, feel free to ask me.

**3. Expected behavior**
A compiler warning would be great for this, I think, as this is a rather critical bug when migration from older nav versions, as it worked perfectly there.

**4. Actual behavior**
It runs into an error that can't be caught with the debugger.

**5. Versions:**

- AL Language:
- Visual Studio Code: Latest (1.72.0)
- Business Central: 20.4 (Platform 20.0.44266.44359 + Application 20.4.44313.44365)
- List of Visual Studio Code extensions that you have installed:
  - AL Language

**Comment by qutreson** [comment]
This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
