### ISSUE TITLE
Sticky scroll does not work on .dal files

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7214]
**1. Describe the bug**
The VS Code sticky scroll feature works fine on al files.
However, when drilldown to the base app symbols, a .dal file is opened which does not fully support the sticky scroll feature. (See animation below where line 1 + the 'field' definition + ... are not included in the sticky part when loading the dal file)

Related to #7146

**2. To Reproduce**
Enable the stick scroll feature in VS Code.

`"editor.stickyScroll.enabled": true,`

Open an al file. Sticky scroll works fine.

Open a dal file. Sticky scroll skips the first line, skips the field definition, ...

![Stickyscroll](https://user-images.githubusercontent.com/25268332/195567563-68244323-3d9e-446c-9257-40d3ed14bfe7.gif)

**3. Expected behavior**
Sticky scroll for dal files should work the same way as for al files.

**5. Versions:**

- AL Language: 10.0.687650
- Visual Studio Code: 1.72.1

**Comment by kalberes** [comment]
DAL files are temporary in memory files files not part of the compilation unit that carries the information for sticky scroll. 
It is by design for now.  I will add it for triage but it we have many more important things to fix.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
