### ISSUE TITLE
PromotedActionCategories are missing in xlf

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7216]
Please include the following with each issue:

**1. Describe the bug**
The current AL Language Extensions does not create xlf Entries for `PromotedActionCategories`

**2. To Reproduce**
Create a Page with property `PromotedActionCategories ` and Feature `TranslationFile`.
Compile the App and check the .g.xlf file

**3. Expected behavior**
There should be a translation for the PromotedActionCategories.

**4. Actual behavior**
The current AL Language Extensions does not create xlf Entries for `PromotedActionCategories`

**5. Versions:**

- AL Language: 10.0.687650
- Visual Studio Code:Version: 1.72.1 (user setup)
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by pri-kise** [comment]
This bug seems to fixed with Business Central Version 21.1, since the NextMinor generates this xlf entries, but this should be fixed for the AL Language Extensions, too.

**Comment by Lazys** [comment]
We've run into the same issue. When can we expect the update of the AL Language Extension?

**Comment by YevgeniyaYermolayeva** [comment]
Same problem, please fix it.

**Comment by thloke** [comment]
This has been fixed and will be in the next marketplace release of the AL extension.
