### ISSUE TITLE
Adding BLOB field to XMLPort crashes client when browsing AllObjWithCaption (14.27 to 21.0)

### ISSUE THREAD

**Issue by JuricaB** [microsoft/AL#7217]
Please include the following with each issue:

**1. Describe the bug**
If you have an XMLPort published from extension, and that XMLPort has fieldattribute based on BLOB field, browsing AllObjectsWithCaption crashes client with following errors:
- Fatal error during metadata load 
- Requested value 'Blob' was not found

**2. To Reproduce**

1. Add BLOB field to XMLPort as fieldattribute
Note: I replicated this with custom as well as standard BLOB fields.
``` AL
tableextension 50100 CustExt extends Customer
{
    fields
    {
        field(50100; MyField; Blob)
        {
            DataClassification = ToBeClassified;
        }
    }

}

xmlport 50100 MyXmlport
{
    schema
    {
        textelement(Root)
        {
            tableelement(Customer; Customer)
            {
                fieldattribute(MyField; Customer.MyField)
                {

                }
            }
        }
    }
}
```

2. Open Permission Sets, 
3. create user defined permission set
4. Try to add XMLPort 50100 to permission set - client crashes with errors as above
5. Issue also present on BC 14.27.47563.0-nz with same symptoms
6. Issue also presents if browsing AllObjWithCaption table from custom code.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Client does not crash. If adding blob field to XMLPort in this manner is not allowed, there should be an AL compiler error raised at runtime.

**4. Actual behavior**
Client crashes. Following errors found in event log:

Fatal error during metadata load -- Type:XmlPort; Id:50100; MetadataGroup:94; 
MetadataLoaded:False; CLRLoaded:False; ThreadGroup:95 ProcessId: 17624 Tag: 
00007YQ ThreadId: 32 CounterInformation: CustomParameters: { } 

RootException: ArgumentException Requested value 'Blob' was not found. ExceptionStackTrace: at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult) at Microsoft.Dynamics.Nav.Types.Metadata.MetaXmlPortFieldNode..ctor(XmlNode textNode) at Microsoft.Dynamics.Nav.Types.Metadata.MetaXmlPort..ctor(XmlDocument xmlDoc, CreateRequestForm createRequestForm, Int32 metadataAppGroupId, Int32 languageAppGroupId, RemoveItemsOnPageBasedOnLicenseAndApplicationArea removeItemsOnPageBasedOnLicenseAndApplicationArea) at Microsoft.Dynamics.Nav.Runtime.NCLMetaXmlPort.LoadMetadata() at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate() at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Int32 appGroupId) CallerStackTrace: at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Int32 appGroupId) at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled) at Microsoft.Dynamics.Nav.Runtime.AllObjWithCaptionDataProvider.GetCaptionAndSubtype(NavAppGroup appGroup, ObjectType type, Int32 objectNumber, String objectName) at Microsoft.Dynamics.Nav.Runtime.AllObjWithCaptionDataProvider.<GetValuesWithinRangeForKeyField>d__4.MoveNext() at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext() at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext() at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source) at Microsoft.Dynamics.Nav.Runtime.DataAccess.Exists(ExistsCacheRequest request) at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.ValidateNonFlowField(NCLMetaField field, Boolean isUserInput) at Microsoft.Dynamics.Nav.Runtime.NavRecord.ValidateField(FieldTriggerHandler`1 fieldEvent, NCLMetaField metaField, Boolean isUserInput, List`1 beforeHandlers, List`1 afterHandlers) at Microsoft.Dynamics.Nav.Runtime.NavRecord.Validate(NCLMetaField metaField, NavValue newValue, NavRecord callerRecord, Boolean isUserInput) at Microsoft.Dynamics.Nav.Service.NsDataAccess.Validate(Int32 fieldId) at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass15_0.<ValidateField>b__0(NsDataAccess recDataAccess) at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func) at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func) at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func) at Microsoft.Dynamics.Nav.Service.NSField.Validate(NavSession session) at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.IClientApi.ValidateField(FieldRequest fieldRequest, NavRecordState dataSetState) at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.<>c.<Invoke>b__8_0(ServiceOperationContext context) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddToThreadSchedulerCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PartnerTelemetryPermissionErrorCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PushPopCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0() at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation) at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.Invoke(MethodInfo targetMethod, Object[] args) at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args) at generatedProxy_1.ValidateField(FieldRequest , NavRecordState ) at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at StreamJsonRpc.TargetMethod.<InvokeAsync>d__19.MoveNext() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() ProcessId: 17624 Tag: 00007YR ThreadId: 32 CounterInformation: CustomParameters: { } 

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: 1.72.2
- Business Central: 21.0.46256.47284-nz
- List of Visual Studio Code extensions that you have installed: n/a

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by JuricaB** [comment]
Hi @thloke,

As I mentioned in my report, if this is not supported scenario, then I would expect AL compiler would raise an error to prevent me from compiling code containing this scenario. 

I can imagine this being out of scope if this is a known bug in the system. Can you confirm this is the case? Your response was very much template.

Thanks!

**Comment by thloke** [comment]
Understandable, it is a template response. The reason why this is out of scope is because it's to do with the runtime behaviour which this repo doesn't handle. We'll need the team who handles how Xmlports work at runtime to look at this, but that has to go through CSS and not here unfortunately.

So in short, this is probably a bug, but we cannot handle it through this channel since this repo is specifically for the AL compiler and dev tools, not the runtime behaviour.

I hope that clears things up!

**Comment by JuricaB** [comment]
Thank you @thloke! Much appreciated!
