### ISSUE TITLE
Compiler doesn't error if we use reserved words that will cause syntax error if rebuilt on older BC version(s) / said errors are vague

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#7219]
Take this code:

```al
codeunit 50100 Test
{
    trigger OnRun()
    var
        Part: Text;
    begin
        Part := 'oh no';
    end;
}
```

***

No warnings from the latest AL language extension:

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 10.0.687650
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

***

But if you try to publish it to a server running BC15 (for example, and probably others), you will get a syntax error about the use of `Part`, as it seems that used to be a strictly 'reserved word' in BC15 et al. - and only subsequently has become contextually allowed.

In order to replicate those errors in VS Code, we have to downgrade to an old AL extension, e.g. to:

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.249486
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

which gets us this cluster of confusing errors:

![image](https://user-images.githubusercontent.com/63455896/196714945-34c900e8-29e0-4831-afe1-3ce786e151a9.png)

***

Sorry to rant, but I keep having to report issues like this, where once something becomes OK in a later runtime/platform, the compiler 'forgets' that it didn't work - **and still won't** - if published/rebuilt on an older runtime/platform, where it was and still is a syntax error.

Having to do so is a huge waste - of our time as developers, of our consultants'/support's time when they find that they can't publish something we give them (because we naively assumed VSC/AL would error, if it would be an error at runtime), and of customers' time and goodwill if we can't deliver what we say we will... and the most we can tell them is 'Sorry, Computer Says No, But It Didn't Before'.

***

Please can you fix, and see if there's any way to get a better process in place, so that when delivering - great, _hugely_ appreciated! - fixes for newer runtimes/platforms, you don't end up losing the knowledge that it won't work on older ones, and waste everyone's time?

And please, while fixing that, can you make such cases say something clear like

> The reserved word `part` cannot be used in this context before runtime `$BAR`.

...instead of the compiler basically falling over and spewing seemingly unrelated errors?

***

Thank you muchly!

**Comment by mjmatthiesen** [comment]
The only way to reliably build older versions is to use the vsix that was shipped with that version of BC. Anything else will result in faulty/missing diagnostics like you mention as well as a resulting build that is more likely to cause runtime errors.
At least that has been our experience, hence our pipeline uses the  appropriate vsix.

**Comment by dnpb** [comment]
We don't want to have to accept that, though. We build apps that _can_ be installed on BC15 _but also_ need to be installable and as diagnostic-free as possible on newer versions too. Old compilers won't have new diagnostics and probably have more old bugs. Et cetera, et cetera.

I guess we have to now try to remember to, after developing and validating on latest AL compiler, also test our BC15-targeting apps against Ye Olde Version 4.x - but, and I'm sorry to say it, that's just another waste of our time, which shouldn't be required!

**Comment by mjmatthiesen** [comment]
It's not that I don't agree, I'm just detailing the experience we've had.

**Comment by thloke** [comment]
We've decided to not fix this issue for now. The problem is that this is a form of backwards compatibility that we do not currently support.

Right now we (try to) guarantee that code that used to compile will continue to compile with newer compilers. I.e. a new compiler will not break existing app code.

This however is a different form of backwards compatibility: that code that used to **not** compile will continue to not compile.  The cost of implementing this is too high to be considered at the moment. For now, the recommendation to use the compiler that is shipped with the version you are building for if you require strict compatibility is probably the best workaround.

As usual, you can raise this on BCIdeas though. If there's enough support for this in the partner community, that would add weight to us being able to prioritize the resources required to do this.
