### ISSUE TITLE
Debug without republishing of App

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#722]
Hi team,
Is there any option to enable Debug option without F5 (republishing the app)?

If I use F5 then all data of my app is deleted and I cannot debug (cos I need to input all data once again).

**Comment by StanislawStempin** [comment]
Unfortunately for now it is not possible to avoid data deletion when starting the debugger. We are working on a feature that will let you preserve the data on subsequent republishes if schema changes are compatible. See #62

**Comment by megel** [comment]
How is the recommended approach to provide these data needed for the development / debugging process?

Is there an event that could be subscripted in a codeunit to create the data e.g. in a test codeunit?

**Comment by hgnamvn** [comment]
Please check and support this feature soon. It is very very important for testing the extension. Currently, I'm testing my extension, but it is very difficult to track issues without debug tool.

**Comment by epernst** [comment]
Personally I solved it (for now) by creating an automated "demo install" codeunit (subtype install), which publishes my test data. Takes time to do, but most of that is saved when it comes to build automated step.
Wouldn't it be able to do almost the same with a .NAVDATA file? Thus we could save just save the current data, to reload them each time.

**Comment by bwdeleeuw** [comment]
Just ran this test in NAV2018, and it is failing. That means that all production data disappears when a debug is done, or a hotfix or update is loaded. Are there any workarounds for this, or at least a timeline for a fix? 

At this point, we cannot use this functionality on any project without risking data loss.

**Comment by StanislawStempin** [comment]
We are currently working on addressing this issue. We will target backporting the fix to NAV 2018.

**Comment by strophanthus** [comment]
> preserve the data on subsequent republishes if schema changes are compatible.

Will that consider the updgrade logic?
