### ISSUE TITLE
Unexpected value 'BadExpression' if using Enum class as Parameter with Next Minor Version of BC21

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL#7220]
we have added a new function within BC20/BC21 which now fails within the upcoming BC21, CU1 (Next Minor)

```
Publishing C:\ProgramData\BcContainerHelper\Extensions\industry-37137-nextminor\<xxx>\BE-terna_BE-Industry_33.0.0.37137.app
One or more errors occurred.
Failure while emitting method. Object:'Codeunit "BET IND Setup"' Method:'CreateAutomotiveCueSetup()'
Unexpected value 'BadExpression' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind
```

the problematic function call:
```
local procedure CreateAutomotiveCueSetup()
    var
        Cue2: Record "BET AUT Cue 2";
        CuesAndKPIs: Codeunit "Cues And KPIs";
    begin
        CuesAndKPIs.InsertData(Database::"BET AUT Cue 2", Cue2.FieldNo("AUT Orders - Open"), 
                               Enum::"Cues And KPIs Style"::Favorable, 0,
                               Enum::"Cues And KPIs Style"::Favorable::Ambiguous, 5,
                               Enum::"Cues And KPIs Style"::Unfavorable);
```

I solved this issue by using Variables for the Enum values

    local procedure InsertDataStandardCue(TableID: Integer; FieldNo: Integer)
    var
        CuesAndKPIs: Codeunit "Cues And KPIs";
        LowRangeStyle, MiddleRangeStyle, HighRangeStyle : Enum "Cues And KPIs Style";
    begin
        LowRangeStyle := LowRangeStyle::Favorable;
        MiddleRangeStyle := MiddleRangeStyle::Ambiguous;
        HighRangeStyle := HighRangeStyle::Unfavorable;
        CuesAndKPIs.InsertData(TableID, FieldNo, LowRangeStyle, 0, MiddleRangeStyle, 5, HighRangeStyle);
    end;

However I am confused why this came up with the Next Minor version...

**Comment by thloke** [comment]
We fixed a bug recently around chaining of enum access. It might be the following line which is causing the issue:

`Enum::"Cues And KPIs Style"::Favorable::Ambiguous`

If you change that to:

`Enum::"Cues And KPIs Style"::Ambiguous`

Does the bug still repro? The `BadExpression` is definitely not ideal though.

**Comment by thloke** [comment]
Okay, got this to repro exactly with that setup.

**Comment by ralf-escher** [comment]
Okay, did not see this "double" Enum Expression.
I changed it and now it works.

Thanks a lot!

**Comment by thloke** [comment]
Reopening since even though it works now, we want to fix the fact that it crashes the emit step of compilation. :)

**Comment by dnpb** [comment]
ref: https://github.com/microsoft/AL/issues/7077 :-)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.48696.0 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by thloke** [comment]
To add to the above - we have also backported the fix so the next marketplace release of the extension should not crash on this.
