### ISSUE TITLE
AL0204 and AL0118 raised on using the new option access syntax

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7229]
Please include the following with each issue:

**1. Describe the bug**
Errors raised on using the new [option access syntax](https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/use-option-access-syntax-formulas).

**2. To Reproduce**

1. In the `app.json`, ensure you work with `"runtime": "10.0"`

2. Add the following object
``` AL
page 50000 "CCS PDM CAD Item Card"
{
    ApplicationArea = All;
    Caption = 'New Item Card';
    PageType = Card;
    RefreshOnActivate = true;
    SourceTable = Item;
    UsageCategory = None;
 
    layout
    {
        area(Content)
        {
            group(Item)
            {
                Caption = 'Item';
                field("No."; Rec."No.")
                {
                }
            }        
        }     
    }

    actions
    {       
        area(Navigation)
        {
            group(Navigation_Item)
            {
                Caption = 'Item';
                action(Dimensions)
                {                    
                    Caption = 'Dimensions';
                    Image = Dimensions;                   
                    RunObject = page "Default Dimensions";
                    RunPageLink = "Table ID" = const(27),
                                  "No." = field("No.");
                    ShortcutKey = 'Alt+D';
                    ToolTip = 'View or edit dimensions, such as area, project, or department, that you can assign to sales and purchase documents to distribute costs and analyze transaction history.';
                }
	    }
         }
    }
}
```

3. Change the action's `RunPageLink` to the new [option access syntax](https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/use-option-access-syntax-formulas) using IntelliSense:
`RunPageLink = "Table ID" = const(Database::Item),`

Now, the following errors are thrown:
On `"Table ID"`: Field type Integer is not convertible to field type. [AL0204](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al204)
On `Database`: The name 'Database' does not exist in the current context. [AL0118](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al118)

**3. Expected behavior**
Either no errors AL0204 and AL0118, or IntelliSense should not support using `const(Database::Item)`.

**4. Actual behavior**
IntelliSense supported, but errors AL0204 and AL0118 thrown.

Note: The new syntax **does** work on other occurrences, such as when turning 
`SubPageLink = "Table ID" = const(27)`
into 
`SubPageLink = "Table ID" = const(Database::Item)`

**5. Versions:**

- AL Language:  v10.0.687650
- Visual Studio Code: 1.72.2
- Business Central:  21

**Comment by JMA1972** [comment]
It's a duplicate of #7205

**Comment by NKarolak** [comment]
That's right. I did not find it myself because the warning IDs are not mentioned there.
