### ISSUE TITLE
Testing empty date

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#723]
I get an AL syntax error when I try to check if a date field is empty. This was allowed in C/AL. Any reason this is not supported now?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/5204734/31082184-34b80b66-a75c-11e7-98a8-c748bb554a11.png">

**Comment by StanislawStempin** [comment]
You need to use capital D in 0D to denote the zero date literal in the new compiler.
