### ISSUE TITLE
Debugging background sessions for sandbox environments

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7232]
Hey AL gurus, 

For development we are using containers & Azure VMs with sandbox artifacts. So we are as close as production environment, and all SaaS functions (for e.g. IsSaaS), are working correctly. 

Recently, we came to one annoying limitation of using sandox artifacts. Apparently, it's not possible to debug background sessions for sanbox environments. This make completely sense for production, but for local(& cloud) dev/test environments it doesn't. To my opinion, debugging background sessions should be allowed for nonprod environment, otherwise the purpose of using sandboxes for dev & testing looses it's meaning. 

Best Regards, 
Gintautas

**Comment by thloke** [comment]
This is a feature request, so it will have to go through our prioritization for new features. You can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by gntpet** [comment]
hey @thloke,
Can you please confirm that it's not possible to enabled debugging background session for container created with sandbox artifacts? Perhaps there's navserver settings that we could use to enable it?

**Comment by gntpet** [comment]
Created new idea:
https://experience.dynamics.com/ideas/idea/?ideaid=2dc38cdb-bd64-ed11-a76e-0003ff459205
