### ISSUE TITLE
AS0053: The compilation target is set to 'OnPrem', but it must be set to 'Cloud' or 'Extension'.

### ISSUE THREAD

**Issue by MHOLSTGLI** [microsoft/AL#7238]
**1. Describe the bug**
I have a project in BC 19 for a customer, where I have to use the file management for local access.
The project have been create with "target" = "Cloud" in the app.json
Now I have to change the target from "Cloud" to "OnPrem". When building the project i get the error AS0053.
![image](https://user-images.githubusercontent.com/117986636/201333384-990aae91-189f-4687-b405-978f172df480.png)

How can I findout, what is wrong. There is no information, which object creates the error.

I tried to rebuild the error in another project, but there I don't get the error. I used nerly the same app.json.
![image](https://user-images.githubusercontent.com/117986636/201335496-c80fa943-d42b-49af-b7ad-1c8fb35cd022.png)

**2. To Reproduce**
Can not reproduce the error.

**3. Expected behavior**
I expect to get an information, which object throws the error.

**4. Actual behavior**
Next to other warnings on building the project this error is created.
![image](https://user-images.githubusercontent.com/117986636/201336925-acf55497-779e-462d-befe-afb26fd13c4d.png)

**5. Versions:**
AL Language: v10.1.707468
Visual Studio Code: 1.73.1
BC; 19.6.38118 (de)
List of VS Code extensions installed:
![image](https://user-images.githubusercontent.com/117986636/201338179-2f002121-55cb-4550-a563-f896633dab33.png)

**Comment by dnpb** [comment]
The `AS` prefix means the diagnostic is from `AppSourceCop`, which indeed requires Cloud-ready apps. So that's intentional.

But you can disable the diagnostic on the `ruleset.json` file:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

If the error is thrown by the server you're publishing to, I guess it's SaaS-only, in which case you have no way around this.

**Comment by MHOLSTGLI** [comment]
I entered this error (AS0053) into Hidden.Ruleset.json and the error doesn’t appear anymore at compilation. So the extension could be created.




Mit freundlichen Grüßen / Best regards

Mathias Holst

Service & Support



GLI Business Solutions GmbH
Fraunhoferstraße 3
25524 Itzehoe

Telefon:        +49 4821 4039880
Telefax:        +49 4821 4039882
E-Mail: ***@***.******@***.***>
Internet:       https://www.main-tool.de
https://www.gli-bs.de<https://www.gli-bs.de/>


<https://www.main-tool.de/news/webinare/><https://www.linkedin.com/company/8859856/admin/><https://www.linkedin.com/company/8859856/admin/>[cid:linkedin_46be8323-ec84-4071-96b5-4ac6f7609e13.png]<https://www.linkedin.com/company/8859856/admin/>  <https://www.youtube.com/user/user_name_here> <https://www.youtube.com/channel/UC9Gtqnx1mfgu_DruHw-6m5A> [cid:youtube_ea8f2a30-5024-4b1e-bc2b-6446ee3289e8.png] <https://www.youtube.com/channel/UC9Gtqnx1mfgu_DruHw-6m5A>

<https://www.main-tool.de/>[cid:Logos_fr_Signatur_330_x_46px_790e8824-f679-4a8f-8ab9-6ee899e95491.png]

<https://www.main-tool.de/anmeldung-zum-anwendertreffen/>

<https://www.main-tool.de/anmeldung-zum-anwendertreffen/><https://www.main-tool.de/news/webinare/><https://www.main-tool.de/maintool/webinare/>[cid:webinare_7ae5ba0b-5171-4af2-b4fc-e7ee423f28a7.png]<https://www.main-tool.de/maintool/webinare/>
 <https://www.main-tool.de/maintool/webinare/>

This e-mail and any attachment thereto contain confidential and/or privileged information.
If you are not the intended recipient or have received this e-mail in error, please notify the sender immediately and delete this e-mail and any attachment thereto from your system.
Any unauthorized retention, copying, transmission, distribution, disclosure or use of the content of this e-mail and/or any attachment thereto is prohibited.
GLI is not liable for any omission or error in this e-mail and/or any attachment thereto which may arise as a result of the e-mail-transmission or for damages resulting from any unauthorized change of the content of this e-mail and/or any attachment thereto.
Thank You

GLI Business Solutions GmbH<https://www.gli-bs.de/>   |  Mitglied der collana IT Gruppe<https://www.collana-it.com/>   |  Geschäftsführer: Marc Pfeiffer, Sven Pfeiffer  |  Amtsgericht Pinneberg HRB 1560 IZ
Von: dnpb ***@***.***>
Gesendet: Freitag, 11. November 2022 17:28
An: microsoft/AL ***@***.***>
Cc: Mathias Holst ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/AL] AS0053: The compilation target is set to 'OnPrem', but it must be set to 'Cloud' or 'Extension'. (Issue #7238)


The AS prefix means the diagnostic is from AppSourceCop, which indeed requires Cloud-ready apps. So that's intentional.

But you can disable the diagnostic on the ruleset.json file:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

If the error is thrown by the server you're publishing to, I guess it's SaaS-only, in which case you have no way around this.

**Comment by dnpb** [comment]
I didn't think there was anything to fix, but I do also like to use AppSourceCop for diagnostics such as suffixes and object IDs, while suppressing the more stringent AppSource-compat stuff. So as long as it keeps working to disable rules, I'm golden :-D
