### ISSUE TITLE
txt2al.exe Handling SQLIndex

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#724]
Tested with the August Update. The result of txt2al.exe with SQLIndex is
```
key(Key2;"Item No.","Variant No.","Lot No.")
{
  SQLIndex='"Item No.","Variant No.","Lot No."';
}
```
But the Pre-Complier notice this as an error. If I remove the Apostroph (') at the beginning and the end, the error disappeared. 
```
key(Key2;"Item No.","Variant No.","Lot No.")
{
  SQLIndex="Item No.","Variant No.","Lot No.";
}
```
Would be nice if txt2al.exe does that in the first place.

**Comment by atoader** [comment]
Did you use the ExportToNewSyntax command when exporting from C/SIDE?

**Comment by DanielGoehler** [comment]
Yes, but the Apostrophe (') appears after the conversion with txt2al.exe.

BTW, I also tested with September Update, same Problem.
