### ISSUE TITLE
Add Interface on standard Enum

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#7240]
It is possible to extend standard Enum, which is great.
I would like to link an interface to a standard Enum. I do not find a way to do it.
I hope it is possible, but how? Can you give me any help?

**Comment by EmilDamsbo** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
