### ISSUE TITLE
Universal Code: access to table "Licence Information"

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/AL#7242]
Hi,
To make apps compatible with "Universal Code" is required target must be Cloud in app.json.

I want to convert an existing app that I'm using in BC OnPrem. This app shows the data of onprem license, like the old RTC Client was in help (license information).

The problem is, the table "License Information" is marked as scope=OnPrem, and when I try to generate de package, this error is generated:  **error AL0296: The application object or method 'License Information' has scope 'OnPrem' and cannot be used for 'Cloud' development.**

I think this table would be accessible as a Universal App, because a table isn't a resource inaccesible in a isolated environment (as a Cloud).

Could yo do something to allow the use of tables in Universal Apps?

I propose some improvements:
* Relax the error AL0296 when the object is a table, change to a Warning.
* Create a method that return the data of license information.

Best regards,
José Antonio López

**Comment by SBalslev** [comment]
Information about the license does not come from the license information table in a cloud enabled world. This means if you have a dependency to the License Information table then you are developing for onpremises only and not cloud ready.
The solution can no longer be moved to the cloud.

So the question is what type of information are you in need of getting from the license information table?

**Comment by JesperSchulz** [comment]
We are currently processing a PR, which addresses the same issue you have brought up. We haven't landed on a solution quite yet, but it's probably interesting for you to follow and contribute to the discussion. Take a look: https://github.com/microsoft/ALAppExtensions/pull/20445.

**Comment by ti-jalopez** [comment]
> We are currently processing a PR, which addresses the same issue you have brought up. We haven't landed on a solution quite yet, but it's probably interesting for you to follow and contribute to the discussion. Take a look: [microsoft/ALAppExtensions#20445](https://github.com/microsoft/ALAppExtensions/pull/20445).

Ok, I've done that and I've contributing to the discussion.
Thanks.
Best regards,
