### ISSUE TITLE
SetLoadFields doesn't work as expected

### ISSUE THREAD

**Issue by FabioC34** [microsoft/AL#7245]
**1. Describe the bug**
In CU22, function GetValuationDate, even if I set the SetLoadFields in Event "OnGetValuationDateOnAfterOldValueEntrySetFilters" the system has a strange behavior, and picks up info not requested from TableExtension

**2. To Reproduce**
I created a TableExtension of table 5802 "Value Entry", adding several fields. Two fields added are "Source Order Type" and "Source Order No." (that have TableRelation to other tables depending on "Source Order Type":
```
TableExtension 55802 "Value Entry Ext." extends "Value Entry"
{
    fields
    {
        field(50020; "Commercial Cond. Code"; Code[20])
        {
            Caption = 'Commercial Cond. Code';
        }
        field(50021; "Commercial Cond. %"; Decimal)
        {
            Caption = 'Commercial Cond. %';
        }
        field(50200; "Source Order No."; Code[20])
        {
            Caption = 'Order No.';
            Editable = false;
            TableRelation = if ("Source Order Type" = const(Sales)) "Sales Header"."No." where("Document Type" = const(Order), "No." = field("Source Order No."))
            else
            if ("Source Order Type" = const(Purchase)) "Purchase Header"."No." where("Document Type" = const(Order), "No." = field("Source Order No."))
            else
            if ("Source Order Type" = const("Return Sales")) "Sales Header"."No." where("Document Type" = const("Return Order"), "No." = field("Source Order No."))
            else
            if ("Source Order Type" = const("Return Purch.")) "Purchase Header"."No." where("Document Type" = const("Return Order"), "No." = field("Source Order No."))
            else
            if ("Source Order Type" = const(Service)) "Service Header"."No." where("Document Type" = const(Order), "No." = field("Source Order No."));
            ValidateTableRelation = false;
        }
        field(50201; "Source Order Line"; Integer)
        {
            Caption = 'Order Line';
            Editable = false;
        }
        field(50202; "Source Order Type"; Option)
        {
            Caption = 'Order Type';
            Editable = false;
            OptionCaption = ' ,Sales,Return Sales,Purchase,Return Purch.,Service,Transfer';
            OptionMembers = " ",Sales,"Return Sales",Purchase,"Return Purch.",Service,Transfer;
        }
    }
    keys
    {
    }
}
```
Because of this TableExt, since Value Entry table has more than 40 million records, the function GetValuationDate results really slow, because the join with SetCurrentKey is not optimized. So I decided to insert a SetLoadFields in Event OnGetValuationDateOnAfterOldValueEntrySetFilters, in order to load only the field needed in the process and avoiding join with TableExt:
**Subscriber:**
```
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Item Jnl.-Post Line", 'OnGetValuationDateOnAfterOldValueEntrySetFilters', '', false, false)]
    local procedure OnGetValuationDateOnAfterOldValueEntrySetFiltersCU22(var OldValueEntry: Record "Value Entry"; ValueEntry: Record "Value Entry"; OldItemLedgEntry: Record "Item Ledger Entry")
    begin
        OldValueEntry.SetLoadFields("Valuation Date");
    end;
```
Removing the TableRelation from field "Source Order No." the function is fast and it's working (doesn't pick TableExt fields, even if it picks table fields not requested, apparently randomly)

**3. Expected behavior**
I expect that after a SetLoadFields, all the fields not requested won't be picked (and also join with TableExt)

**4. Actual behavior**
I created a TableExtension of table 5802 "Value Entry", adding several fields. Two fields added are "Source Order Type" and "Source Order No." (that have TableRelation to other tables depending on "Source Order Type", see screenshot below:
![image](https://user-images.githubusercontent.com/57533883/202669894-db570da0-2846-4c19-8a5b-f198f1643148.png)

Because of this TableExt, since Value Entry table has more than 40 million records, the function GetValuationDate results really slow, because the join with SetCurrentKey is not optimized. So I decided to insert a SetLoadFields in Event OnGetValuationDateOnAfterOldValueEntrySetFilters, in order to load only the field needed in the process and avoiding join with TableExt:
**CU22:**
![image](https://user-images.githubusercontent.com/57533883/202670928-07249ce9-ebaf-43ed-ae33-e7243de56299.png)
**Subscriber:**
![image](https://user-images.githubusercontent.com/57533883/202671182-b9adf7dd-4a3a-4f02-b57f-b3c080d04737.png)

However, the SetLoadFields doesn't work completely, because doesn't load most of the fields of TableExt, but loads the fields "Source Order Type" and "Source Order No.", so the FindLast results very slow (see SQL statement below):
**Live Query Statistics:**
![Live Query Statistics](https://user-images.githubusercontent.com/57533883/202671633-b4a1b12d-0514-4577-8715-071ecfe32ac2.png)
**SQL Statement:**
![image](https://user-images.githubusercontent.com/57533883/202671849-a803d518-55c3-498f-8bd4-abbb4606a0db.png)

Removing the TableRelation from field "Source Order No." the function is fast and it's working (doesn't pick TableExt fields anymore, even if it picks table fields not requested, apparently randomly), as you can see from SQL Statement below picked from SQL Server Profiler
**SQL Statement after modification:**
![image](https://user-images.githubusercontent.com/57533883/202679014-9114ac85-9aa9-4bc0-a736-dc4a1b5a6b0c.png)

Could you please check what's wrong?

**5. Versions:**

- AL Language: v10.1.707468
- Visual Studio Code: Version 1.73.1
- Business Central: IT Business Central 21.1 (platform 21.0.48357.48504 + application 21.1.48363.48638 (OnPrem)
- List of Visual Studio Code extensions that you have installed:

**Comment by dnpb** [comment]
I believe it is expected that fields used in relations are always loaded, and has been discussed on here. I'm not sure it got documented as I think it was considered an implementation detail.

**Comment by FabioC34** [comment]
It doesn't seem so, in Value Entry Table there are many fields that have TableRelation but they're not loaded (Es. "Source No.", "Source Posting Group"), and there are others instead that don't have TableRelation and are loaded (Es. "Source Type", "Entry Type")...
It's a strange behavior from my point of view, it would be nice to know the logic behind in order to avoid unwanted behavior

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because it relates to the runtime behaviour of BC, so it needs to go to the team who handles the runtime.
