### ISSUE TITLE
Local function in codeunit is inaccessible with self referencing codeunit

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#7246]
**1. Describe the bug**
Inside the same codeunit, it is not possible to call a local function, when calling it through a self referencing variable.

**2. To Reproduce**
Paste that code inside a codeunit and you will see that in the function Test1, the error "'Test2()' is inaccessible due to its protection level" will show up.

``` AL
local procedure Test1()
var
    FooBar: Codeunit "Foo Bar";
begin
    FooBar.Test2();
end;

local procedure Test2()
begin
    
end;
```

**3. Expected behavior**
The function Test2() is accessible because it is getting called inside the same codeunit.

**4. Actual behavior**
The function Test2() is inaccessible.

**5. Versions:**

- AL Language: 10.1.707468
- Visual Studio Code: 1.73.1
- Business Central: BC 21 (2022 Wave 2)

**Comment by JMA1972** [comment]
That's the expected behaviour, you can't call local procedures with variables. "Foobar" in this example is not a self referencing variable but another instance of that codeunit.

**Comment by DominicSaladin** [comment]
In like C# that would work... But would it be possible to implement something like this with protected functions?

**Comment by PooyaKharamesh** [comment]
This behavior is by-design. When a procedure is marked as private, the procedure won't be exposed through a variable even if the variable is declared in the same codeunit.
