### ISSUE TITLE
Make "Object Metadata" available in Cloud

### ISSUE THREAD

**Issue by obychyk** [microsoft/AL#7247]
Hi all,

I have a particular case when I need to access `Object Metadata` while building solution for Cloud BC: I need to read a `SubPageLink` parameters and parse it for further processing. I was able to achieve that in NAV 2018, but, while moving functionality to BC SaaS, I realised that all Metadata tables which contain metadata BLOBs are marked as `Scope = OnPrem`.
Can you please make `Object Metadata` available for SaaS or create something similar that can be used to read metadata from SaaS?

Best regards,
Oleksandr

**Comment by thloke** [comment]
Thanks for the suggestion. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
