### ISSUE TITLE
FTP Upload and Download

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#725]
In order to do some FTP Uploading or Downloading within AL it would be nice to have the following classes available
```
System.IO.Path
System.IO.Stream
System.IO.StreamReader
System.Net.FileWebRequest
System.Net.FtpWebResponse
System.Net.NetworkCredential
System.Net.WebClient
System.Net.WebRequest
```

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
