### ISSUE TITLE
[BUG] on Format function (with setting 9)

### ISSUE THREAD

**Issue by Arthurvdv** [microsoft/AL#7251]
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property#standard-xml-and-string-formats

Hoping that I interpret the documentation correctly, the function Format(Value, 9) formats as value to be used in an XML document.

Simplified the functions, where I expected a different result.

```AL
trigger OnOpenPage()
var
    MessageLbl: Label 'The formatted value of ''%1'' is ''%2''.';
begin
    Message(StrSubstNo(MessageLbl, WorkDate(), Format(WorkDate(), 9)));
end;
```
| Result | Value of pop-up message |
| ------------- | ------------- |
| Expected | The formatted value of '21/11/22' is '2022-11-21'. |
| Outcome | The formatted value of '21/11/22' is ' 21/11/22'. |

```AL
trigger OnOpenPage()
var
    MessageLbl: Label 'The formatted value of ''%1'' is ''%2''.';
    myDecimal: Decimal;
begin
    myDecimal := 1234.56;
    Message(StrSubstNo(MessageLbl, myDecimal, Format(myDecimal, 9)));
end;
```
| Result | Value of pop-up message |
| ------------- | ------------- |
| Expected | The formatted value of '1.234,56' is '1234.56'. |
| Result | The formatted value of '1.234,56' is ' 1.234,56'. |

_(I've noticed also that in both cases a space is added before the value)_

version: BE Business Central 21.1
application: 21.1.48363.48789
platform: 21.0.48357.49378

**Comment by dnpb** [comment]
Typo: You want `Format(Thing, 0, 9)`, not `Format(Thing, 9)`. The 2nd argument is the length to output or 0 for automatic.

**Comment by Arthurvdv** [comment]
> This is not a bug, but your typo: You want `Format(Thing, 0, 9)`, not `Format(Thing, 9)`. The 2nd argument is the length to output or 0 for automatic. The **3rd** argument is the format string or standard format number.

Oops, this is slightly embarrassing. Me and my colleague also overlooked this.

Thank you @dnpb and @NKarolak for the support.
