### ISSUE TITLE
AL compiler does not check for wrong casing

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#7253]
**1. Describe the bug**
The compiler does not check the casing when referencing variables.

**2. To Reproduce**
Paste this function in any object and no error will be thrown.
``` AL
local procedure Test()
var
    MyText: Text;
begin
    // this variables does not exist like this. The "M" and the "T" MUST be uppercase
    mytext := '';
end;
```

**3. Expected behavior**
The compiler should throw an error and tell me that the variable "mytext" was not found. C# for example, which is very similar to AL, would throw an error, which I would expect to happen here to.

**4. Actual behavior**
No error, the compiler accepts the wrong written variable usage.

**5. Versions:**
- AL Language: 10.1.707468
- Visual Studio Code: 1.73.1

**Comment by BazookaMusic** [comment]
AL is case insensitive by design:
![image](https://user-images.githubusercontent.com/36576941/203761060-e61918a3-015a-4aea-9ed5-657e68d93e27.png)

This design decision was taken during the creation of AL being a successor of C/AL, which was case insensitive, to help migration of older apps.
