### ISSUE TITLE
🛑🛑🛑Please contact customer support🛑🛑🛑

### ISSUE THREAD

**Issue by Yiknok** [microsoft/AL#7256]
when try command AL:GO return an error 
![Screenshot from 2022-11-25 15-03-24](https://user-images.githubusercontent.com/77238925/203991680-0b336065-fca7-472b-a631-b520336905fd.png)
i working in 64 bit Ubuntu 20.04.5 LTS

**Comment by EmilDamsbo** [comment]
Please describe in more detail what your issue seems to be? Which error are you experiencing when using the AL: Go! command in the AL Language extension?

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
