### ISSUE TITLE
help with field

### ISSUE THREAD

**Issue by elhola** [microsoft/AL#7258]
Tell me how to filter the Item table so that only the Code and Description are in the field?  I don't need all the columns

**Comment by pri-kise** [comment]
@elhola you should use the yammer group https://www.yammer.com/dynamicsnavdev/ for partners

the twitter #bcalhelp or other dynamics nav / business central communities (https://community.dynamics.com/nav/b/navug) for these kind of questions.

**Comment by EmilDamsbo** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://www.dynamicsuser.net/nav)
