### ISSUE TITLE
The editor could not be opened because the file was not found.

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#7261]
Please include the following with each issue:

**1. Describe the bug**
The AL DLL is incorrectly dealing with "URL encoding". This is normally a serious security bug, but is probably just embarrassing in this case.

**2. To Reproduce**

* Have a small project, with a procedure in a codeunit.
* Rename the directory the project is in to `Test%20Project`
* Open the project in vs-code and navigate to the procedure definition.
* Right click on the procedure name and select "Go to Definition".

``` AL
procedure Hello()
begin
end;
```

**3. Expected behavior**
Usually the iframe that holds the code "peek" will be displayed.

**4. Actual behavior**
Error in the subject: "The editor could not be opened because the file was not found."

**5. Versions:**

- AL Language:
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 10.1.707468
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

- Visual Studio Code:
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.14393
Sandboxed: No

- Business Central:
NONE
- List of Visual Studio Code extensions that you have installed:
All extensions disabled except "AL Extension".

### Final Checklist

Please remember to do the following:

* [ x] Search the issue repository to ensure you are reporting a new issue

* [ x] Reproduce the issue after disabling all extensions except the AL Language extension

* [ x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
