### ISSUE TITLE
[CI/CD] Missing row selection functionality in TestPage object

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/AL#7263]
**1. Describe the bug**
In the UI of a list page, it is possible to select multiple records, e.g. via Ctrl + Click. In automated testing, this is not possible due to  missing functionality to select a record.

**2. To Reproduce**
1. Create a list-type testpage object (e.g. ItemListTestPage: TestPage "Customer LIst") ;
2. Attempt to write code that selects multiple records;
3. Find that that is impossible;
4. Run around office flailing in despair.

``` AL
    [ModalPageHandler]
    procedure ReqWorksheetCheckModalHandler(var ReqWorksheet: TestPage "Req. Worksheet");
    begin
        ReqWorksheet.First();
        ReqWorksheet.Select();  // AL0132: TestPage Req. Worksheet' does not contain a definition for 'Select'
    end;
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
I would that the Select method gets added to the TestPage functionality for list-type pages (list, listpart, worksheet, etc.) in order to be able to select multiple records.

**4. Actual behavior**
There is no Select method present so the current behavior prevents testing this behavior in the system.

**5. Versions:**

- AL Language: 10.1.707468
- Visual Studio Code: 1.73.1
- Business Central: 21.1
- List of Visual Studio Code extensions that you have installed: 
-- AL Language
-- AL CodeActions
-- AL Object Designer
-- AL Variable Helper
-- AZ AL Dev Tools/AL Code Outliner
-- BusinessCentral.LinterCop
-- ErrorLens
-- Git Blame
-- Git History
-- GitLens - Git Supercharged
-- PowerShell
-- Waldo's CRS Language Extension

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
