### ISSUE TITLE
AppSourceCop Rule AS0011 / AS0079 should warn on event procedures

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7264]
Please include the following with each issue:

**1. Describe the bug**
The Appsource Cop does not warn if you created an event publisher without affix in an extension object.

**2. To Reproduce**

1. Specify an Mandatory Affix in the AppSourceCop.json and enable the appsource cop
2. Create a table extensions.
3. Add a new Event Publisher without affix

**3. Expected behavior**
You should introduce a new rule like `AS0079 ` that checks for event publisher in extension objects.
Similiar Issue: https://github.com/microsoft/AL/issues/5255

**4. Actual behavior**
Right now there is now warning

**5. Versions:**

- AL Language: v10.1.707468
- Visual Studio Code: Version: 1.73.1 (user setup)
- Business Central: Unrelated
- List of Visual Studio Code extensions that you have installed: I have disabled all extensions except the AL Language extension

**Comment by NKarolak** [comment]
Events are local functions, and therefore don't need affixes.
If an event is declared as global, another rule applies: [AS0079](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0079).

**Comment by pri-kise** [comment]
@NKarolak have you tried to define an event with the same name and signature as in the BaseApp?
How can we know which event we subscribe to?

**Comment by NKarolak** [comment]
Nope, I didn't consider that scenario yet.

**Comment by pri-kise** [comment]
The same goes for global variables. They are only accesible for the current extension, but as soon as the BaseApp defines a new global variable with the same name, your extension won't compile anymore.

**Comment by qutreson** [comment]
The validation of affixes for global variables should already be handled in the preview version of the AL extension available in docker images. We have added validation of affixes and breaking changes for global variables (changing name, type, accessibility, etc).

We will look into adding a diagnostic for local events

**Comment by qutreson** [comment]
@pri-kise - Can you share an example reproducing the issue for the missing diagnostic for affixes on events?

I cannot reproduce the issue using the latest extension from the marketplace:

![image](https://user-images.githubusercontent.com/31541422/205624210-6cd5038d-6ecf-4698-8637-3603be0f9e87.png)

**Comment by pri-kise** [comment]
@qutreson I checked it now, and with the latest AL Compiler this is now reported as warning.
This must have beend changed during the last week. Because we have one project, where this warnings weren't shown.

**Comment by demiliani** [comment]
Sorry, but why not working with something more “pro” like namespaces instead of continuously forcing to use affixes? This should be a priority.
