### ISSUE TITLE
Rapid Application Publish fails

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7267]
Please include the following with each issue:

**1. Describe the bug**

Follow-up of #7169

At BCTechDays 2022, we were encouraged to make use of the existing tooling, including the 'Rapid Application Publish' feature. However, trying to do so results in various failures.

**2. To Reproduce**

- I've a workspace with 2 dependent apps (Core + Dependent App)
- 'Publish full dependency tree for current project'
- Both apps are successfully published
- I perform a small code change to a page object in the Core app
- 'Rapid Application Publish without Debugging'
- Debug console: Success: The package 'Dynavision_Dynavision Core_20.0.15.0.app' has been published to the server.
- Open the webclient
- All my objects from the 'Core app' seem to have dissappeared.
- Only option to restore is to run 'Publish full dependency tree for current project' again :(

**3. Expected behavior**

**4. Actual behavior**

**5. Versions:**

- AL Language: v9.5.674382
- Business Central: Versie: US Business Central 20.4 (platform 20.0.44266.46375 + toepassing 20.4.44313.44365)

**Comment by nndobrev** [comment]
@fvet Please when you come across issues verify if they are reproducible on the latest version of the compiler. We fixed similar issue with the latest version.

**Comment by thloke** [comment]
Can you see if this still reproduces on the latest marketplace VSIX? We fixed a whole bunch of RAD related issues recently.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
