### ISSUE TITLE
AA0235 "When using 'OnInstallPerCompany' you should also add 'Company-Initialize'::'OnCompanyInitialize' event subscriber." - Not working

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/AL#7269]
**1. Describe the bug**
Rule AA0235 does not work with the current latest AL Language extension.

**2. To Reproduce**

1. Create a new AL project.
2. Create a codeunit with `Subtype = Install` and add an implementation for the `OnInstallAppPerCompany` trigger, but do not add a subscriber for `Company-Initialize'::'OnCompanyInitialize` yet.
3. AA0235 is not triggered.

``` AL
codeunit 1160 "AP Install"
{
   Subtype = Install;

   trigger OnInstallAppPerCompany()
   begin
       Message('Hello World');
   end;
}
```

**3. Expected behavior**
Rule AA0235 is triggered if there is an implementation for the `OnInstallAppPerCompany` trigger, but no subscriber for `Company-Initialize'::'OnCompanyInitialize` yet.

**4. Actual behavior**
Rule AA0235 is NOT triggered when there is an implementation for the `OnInstallAppPerCompany` trigger, but no subscriber for `Company-Initialize'::'OnCompanyInitialize` yet.

**5. Versions:**

- AL Language: v10.1.707468
- Visual Studio Code: 1.73.1
- Business Central: 21.1.48363.49889-W1
- List of Visual Studio Code extensions that you have installed: N.A.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

### Additional References
* https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0235
* https://github.com/microsoft/alguidelines/discussions/203
* https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/251
* https://twitter.com/rvanbekkum/status/1598703510794674176

**Comment by thloke** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!
