### ISSUE TITLE
Debugger: Continue after Error - Why do I have to click "continue" twice?

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7274]
Please include the following with each issue:

**1. Describe the bug**
When an error occurs, why do I have to click "Continue" twice before the debugger continues? 
This was not the case in the Windows Client Debugger of Business Central 14.

<img width="1920" alt="Screenshot 001" src="https://user-images.githubusercontent.com/9556549/206147880-654a6bbc-5d56-4e75-8362-3cd0698b7e75.png">

<img width="1920" alt="Screenshot 002" src="https://user-images.githubusercontent.com/9556549/206147892-96a24fb1-6e47-43bd-ab11-0c82e628fdcc.png">

**2. To Reproduce**

1. Run the debugger
2. Encounter an error
3. Click on Continue
4. Click on Continue

**3. Expected behavior**
The debugger should continue after the first Continue.

**4. Actual behavior**
You need to click on Continue twice.

**5. Versions:**

- AL Language: 10.2.719883
- Visual Studio Code: 1.73.1
- Business Central: DE Business Central 21.1 (Plattform 21.0.48357.50310 + Anwendung 21.1.48363.48789)
- List of Visual Studio Code extensions that you have installed:
  - AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
