### ISSUE TITLE
Building extension breaks history RDLC

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/AL#7282]
**1. Describe the bug**
When developing a RDLC report layout with Visual Studio it is recommended to leave the modified file open while testing your changes. This way it was possible to easily revert any breaking changes with Visual Studio by using the Undo action. Currently this is no longer possible, building your extension after modifying a RDLC file seems to wipe your history. Using the Undo action does not lead to reversion anymore.  

**2. To Reproduce**
- Use any report with RDLC layout, for this scenarion created a simple example
```
 report 50100 MyReport
{
    UsageCategory = ReportsAndAnalysis;
    ApplicationArea = All;
    DefaultRenderingLayout = LayoutName;

    dataset
    {
        dataitem(Customer; Customer)
        {
            column(No_; "No.")
            {
            }
            column(Name; Name)
            {
            }
        }
    }

    rendering
    {
        layout(LayoutName)
        {
            Type = RDLC;
            LayoutFile = 'mylayout.rdlc';
        }
    }
}
```
- Open RDLC file externally with Visual Studio.
 
![image](https://user-images.githubusercontent.com/85683700/207584844-09c4147c-88cf-4bae-84ae-15529f4e75a3.png)

- Change RDLC layout and save
 
![image](https://user-images.githubusercontent.com/85683700/207585151-60be1d4b-66a5-48dc-99d8-174cdde9305e.png)
![image](https://user-images.githubusercontent.com/85683700/207585342-10bc9113-2275-4c32-823e-d37c822af3f3.png)

- Use Undo (Ctrl+Z) and change is reverted
 
![image](https://user-images.githubusercontent.com/85683700/207585683-b632ff6f-8011-47f9-9fd0-208b903be511.png)
![image](https://user-images.githubusercontent.com/85683700/207585724-bdd05988-66d2-458f-9b25-9a82c1467bb9.png)

- Now do the same but build (or publish) your extension after making the change in the RDLC layout (without closing the file!). Using Undo does not lead to any reversion.

![image](https://user-images.githubusercontent.com/85683700/207586496-6694a367-42cb-4700-a9fc-9a815a260bbe.png)
![image](https://user-images.githubusercontent.com/85683700/207589214-0627df97-7d06-44ed-9815-3119da76171a.png)

**3. Expected behavior**
Retention of change history in Visual Studio when developing RDLC layouts. This was the case in C/AL development. Finding a breaking change in a complicated document report layout is very difficult, easy reversion to working version is critical for smooth RDLC development.

**4. Actual behavior**
See reproduction.

**5. Versions:**

- AL Language: v10.2.719883
- Visual Studio Code: 1.74.0
- Visual Studio: Professional 2022 (64-bit) - Version 17.4.3
- Business Central: NL Business Central 21.2 (platform 21.0.49939.50846 + application 21.2.49946.50869)
- List of Visual Studio Code extensions that you have installed: None during reproduction.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by moomencegekadsa** [comment]
> Just answer the question of reloading the rdlc file in Visual Studio with "No", then you can still undo. The modifications in the rdlc file when building the application aren't of any relevance.

Take you for your reply. I already suspected it had something to do with reloading, but in my case it does not seem to be optional. As in I do not get any question or other dialog which asks me to reload or not. Where does this difference in behaviour come from?

**Comment by JMA1972** [comment]
Maybe this helps: [https://stackoverflow.com/questions/45741034/visual-studio-auto-reload-solution](https://stackoverflow.com/questions/45741034/visual-studio-auto-reload-solution)

**Comment by moomencegekadsa** [comment]
> Maybe this helps: https://stackoverflow.com/questions/45741034/visual-studio-auto-reload-solution

Thanks, this works. I do still think this behaviour is a bug, but at least there is a workaround.

**Comment by BazookaMusic** [comment]
This behavior is not a bug. In order to publish an RDLC layout or just to build the app, the AL compiler needs to modify the layout to insert some parameters and also the schema of the report dataset. This re-writes the entire RDLC layout.

When you open the RDLC layout in Visual Studio and we re-write the entire file, Visual Studio loses the history because it considers it to be a different file (reloading).  We can't avoid re-writing the file as that would mean that we would not be inserting the dataset in it and it would render incorrectly.

Thus this behavior is by design and the workaround to not reload from VS is the correct solution.
