### ISSUE TITLE
SetFilter with wildcards and replacement value doesn't work.

### ISSUE THREAD

**Issue by Joerio** [microsoft/AL#7283]
**1. Describe the bug**
When you use the method 'SetFilter' with a replacement value, eg. %1, it works fine. However, as soon as you use a wildcard it doesn't apply the replacement value and uses the literal filter value.

This doesn't work, the filter applied is '*%1*' instead of '*a*':
``` AL
Customer.SetFilter("Name", '*%1*', 'a'); 
```

It does work when you use:
``` AL
Customer.SetFilter("Name", '*a*');
```

Or when you don't use a wildcard:
``` AL
Customer.SetFilter("Name", '<>%1', 'a');
```

**2. To Reproduce**
Make a new filter in code and use a replacement value with wildcards, for example:
``` AL
Customer.SetFilter("Name", '*%1*', 'a'); 
```

**3. Expected behavior**
A filter is applied as '*a*'

**4. Actual behavior**
A filter is applied as '*%1*'

**5. Versions:**
- AL Language: 10.2.719883
- Visual Studio Code: 1.74.0
- Business Central: Version: NL Business Central 21.1 (Platform 21.0.48357.50144 + Application 21.1.48363.50147)

**Comment by JMA1972** [comment]
That's just the way Setfilter works since ever and it doesn't have anything to do with the AL compiler. You have to use strsubstno for your example.

**Comment by thloke** [comment]
This is by design. It's also something that needs to go to the team that actually handles the running of filters. You can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
