### ISSUE TITLE
WebClient Refresh Issue : On Sales Order, Sales Lines not refreshing on open.

### ISSUE THREAD

**Issue by ItsAjayVerma** [microsoft/AL#7284]
Issue Description :-
I'm using NAV 2018, I have created few custom fields on Customer table.
Added a Card page to take input for Customer's custom fields.
I've added code to open custom page on Sales Order onopenpage trigger with RunModal.
The things are working fine in RTC, but in Web Client Sales lines not refreshed, once i click on any action then only lines showing.
I tried to place the code in Onaftergetrecord trigger, then the caption not render for some fields in Web Client.

Application : Dynamics NAV 2018
Version : GB Dynamics NAV 11.0
BUILD : 11.0.49345.0

Sample Code :

IF ( lCustomer.GET("Sell-to Customer No.")) AND (NOT lCustomer.Complete) THEN BEGIN
    CustomerAdditionalInfo.LOOKUPMODE(TRUE);
    CustomerAdditionalInfo.SETRECORD(lCustomer);
    CustomerAdditionalInfo.RUNMODAL;

 END;

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
