### ISSUE TITLE
Upgrade of AppSource App with empty al file failes with AL0198

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#7285]
Please include the following with each issue:

**1. Describe the bug**
An empty al file breaks upgrade of customers but succeed appsource validation and is not covered by any codecop.
When update of app 

**2. To Reproduce**
Create an App with an obsolet pending object ("tested" with page and enum)
Install App via AppSource in Environment
remove code of pending object but leave empty file.
push to appsource and wait for envinoment to updat ethe app.

**3. Expected behavior**
Either the update of the environment must work or we need a codecop rule which prevents the compilation of empty al files already at the developer.

**4. Actual behavior**
Error Occures:
Production
```
Operation Type: UpdateAzure AD tenant ID: *** Created by:Operation ID: 67e0bf8b-9cdf-4c9c-9e67-9fc1fe67b514
Operation Details:Status: FailedError: Update failed with an error: AppSource extension '***' version 21.1.53893.0 by '***' failed to compile. Extension compilation failed src/page/Setup.Page.al(1,1): error AL0183: Unexpected character '
________________________________________
' src/page/Setup.Page.al(1,1): error AL0198: Expected one of the application object keywords (table, tableextension, page, pageextension, pagecustomization, profile, codeunit, report, reportextension, xmlport, query, controladdin, dotnet, enum, enumextension, interface, permissionset, permissionsetextension, entitlement) src/page/Setup.Page.al(1,2): error AL0183: Unexpected character ''
From version: 20.5.45456.45681To version: 21.0.46256.46853Update status: FailedCustom date selected: No

Operation Time:Scheduled on: 14.12.2022, 22:42:39Started on: 14.12.2022, 22:42:39Completed on: 14.12.2022, 23:07:26

```

**5. Versions:**

- AL Language: v10.2.719883
- Visual Studio Code: 1.7.1
- Business Central: From version: 20.5.45456.45681To version: 21.0.46256.46853
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
In order to avoid these issues, it is recommended to entirely remove the source file and release the new version on AppSource (if you haven't already). We will discuss the priority of this item internally.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

Our recommended workaround is to ensure that there no empty files.
