### ISSUE TITLE
More resillience for json parser would be great

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7287]
Please include the following with each issue:

**1. Describe the bug**
If you put a comma in the wrong place, the dialog **Loading workspace: : Preparing project: 'ModuleApp'** will not be closed and cannot be built with Ctrl + Shift + B. The output then only shows the message `[Error - 22:25:08] No active project was found. Make sure to select a project in the VS Code Explorer.`

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9556549/208191364-4cfec31d-5204-4d62-896d-d3d49d1729b4.png">

**2. To Reproduce**
1. Put a comma in the wrong place, e.g. after dependencies -> version.

``` json
{
  "id": "b4f939e2-385f-4671-8179-a853e9d909d6",
  "name": "ModuleApp",
  "publisher": "Default publisher",
  "version": "20.0.22221.1",
  "dependencies": [
    {
      "id": "88cf5d4c-8afc-4a98-9cb7-212196c51d74",
      "name": "Continia OPplus",
      "publisher": "Continia Software",
      "version": "20.0.0.0",
    }
  ],
  "screenshots": [],
  "platform": "21.0.0.0",
  "application": "21.1.0.0",
  "idRanges": [
    {
      "from": 50000,
      "to": 50799
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": false,
    "includeSourceInSymbolFile": true
  },
  "runtime": "10.0",
  "target": "Cloud",
  "supportedLocales": [
    "de-DE"
  ],
  "features": [
    "NoImplicitWith"
  ]
}
```
**3. Expected behavior**
Ctrl + Shift + B should tell me what is wrong. At least the app.json is wrong.

**4. Actual behavior**
Dialog **Loading workspace: : Preparing project: 'ModuleApp'** will not be closed and Ctrl + Shift + B doesn't work.

**5. Versions:**
- AL Language: 10.2.719883
- Visual Studio Code: 1.74.1
- List of Visual Studio Code extensions that you have installed:
  - AL Language
### Final Checklist

Please remember to do the following:
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by deadmouse** [comment]
This happened to me last week. Yep, it's not easy to detect you misspelled a comma.

**Comment by thloke** [comment]
Doesn't the issue appear in the `Problems` tab? 

![image](https://user-images.githubusercontent.com/39045749/220311747-da9db668-8b72-4fce-8562-f59b2ce0e38d.png)

**Comment by DanielGoehler** [comment]
Yes, 
![image](https://user-images.githubusercontent.com/9556549/222535058-6bdf3e68-fae5-4e33-85ae-7d89fbf2dd35.png)

But the window Loading workspace will not be closed even if you fix this problem

![image](https://user-images.githubusercontent.com/9556549/222535506-3ad8cd55-8089-48db-b0f1-675244b5023e.png)

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Our suggested workaround for now is to reload the window if there was a problem loading the `app.json`.
