### ISSUE TITLE
Variant data type and support for Classes

### ISSUE THREAD

**Issue by Koubek** [Microsoft/AL#729]
Question:

If you want to pass e.g. **JsonObject** or **JsonArray** etc. using **Variant** data type, how can I cast it later back to the original data type? I mean, how to identify the original data type for Classes? 
There is no `variantVariable.IsJsonObject` etc. There isn\`t something like `typeof`. Maybe I am wrong, then sorry for my question.

**Comment by atoader** [comment]
You are right, there isn't an option to do this. Could you please describe the scenario you are trying to accomplish?

**Comment by Koubek** [comment]
Hmmm, actually I would expect the is nothing to demonstrate ;) 

If **Variant** datatype allows me to pass any object I should be able to identify it back. Ok, I can identify the standard datatypes (`var.IsDate`, `var.IsDateTime`, I can also use `var.IsObjectType`  but I can\`t say of what Type the object is).

An example (but actually this is not the only case, as I have stated before, I suppose we should be able to identify any object):
```
    local procedure StartDemo();
    var
        myyXmlDoc : XmlDocument;
        myXmlNode: XmlNode;
        myXmlNodeList: XmlNodeList;
    begin
        // Load XML Document (not included).
        
        // Do sth to initialize the variables
        //...

        // You can the following:
        LogCurrentObjectValue(myyXmlDoc);
        // But you can run also this:
        LogCurrentObjectValue(myXmlNode);
        // Or this:
        LogCurrentObjectValue(myXmlNodeList);
    end;

    local procedure LogCurrentObjectValue(obj: Variant);
    begin
        // What is the object entering into the function?
        // - XmlDocument?
        // - XmlNode?
        // - ... any other object?
    end;
```

**Comment by Koubek** [comment]
In the previous example, in the function `LogCurrentObjectValue`, using `obj.IsObjectType` returns `False` for `XmlDocument` datatype. `Format` doesn\`t work for variant (in case of new .NET Interop Replacement Objects), it fails (there is no `ToString()` method implemented???).

**Comment by atoader** [comment]
All the XML types represent an XmlNode. In AL, we do not have inheritance in a strict sense but we can convert from an XmlDocument/XmlElement etc. to an XmlNode at any point and convert from an XmlNode to the appropriate Xml subtype using the As* methods.
Variant is a lot more flexible, but we did not focus on integrating the new types with Variant because we do not believe it leads to good design.

**Comment by Koubek** [comment]
OK, I repeat, **XmlNode** was just an example, maybe the wrong one.

The problem is we won\`t be able to achieve generic solutions if we won\`t have right *tools*.

Right now, I can see the language is very obsolete as it is completely missing OOP approach. I expected radical changes in the new language once introduced (I have been working with NAV for more than 12 years and I hope I can say that I know what I am talking about :) ).

In this particular case, we were able at least partially emulate the polymorphism using Variant in the old C/SIDE but if you won\`t include a sufficient support in the new language, we will lose it as well (now I refer .NET Interop as this is a pretty painful loss).

**Comment by kine** [comment]
@gunnargestsson Do you have some coment to this? What do you mean? Can you see some different way how to solve the problem?

**Comment by Koubek** [comment]
Hi @kine - may I ask why @gunnargestsson? Sorry, I don\`t understand well right now.

**Comment by kine** [comment]
Because he is working with Json and DotNet interop often, thus may be he can add something to this.

**Comment by Koubek** [comment]
@kine - Ok, I`ve got it. Thank you very much!!!

**Comment by esbenk** [comment]
The current Variant implementation that we have inherited from C/AL has never been designed for more than a few types. It clearly shows it age with the number of new types we have added. We are investigating how we can provide a better Variant story.

You are right. C/AL and AL have never been OOP in a traditional sense. We plan to add more OOP like features in the future, but our current focus is to bring AL on par with the functionality in C/AL before we expand the scope. 

We have chosen a development model where we have involved the developer community earlier in the development process, and add more features over time. We believe that it is a better model over developing the new tools in isolation over many years and trying to deliver everything in the first release.

We are planning to method overloads in the future, which allows you to solve the problem shown.

**Comment by tfenster** [comment]
> We are planning to method overloads in the future

Quietly dropping bombs :)

**Comment by Gallimathias** [comment]
@esbenk Method Overloading and more OOP <3. This is really great news. Thanks for the info :)

**Comment by Koubek** [comment]
@esbenk Cool, reading your post makes me happy. The content is really promising. 

Personally, I am not sure if publishing a new language in very early stages is the best idea. Especially in the case, when we (partners at all) are trying already to prepare some of our solutions to be V2 ready. I can understand you can change this and that, fix issues. This is fine. 

But I would expect to have some roadmap in this case because changing some core functionality that could probably change the programming approach can lead to another refactoring of our solutions.

Keep in mind that we are moving from C/AL to AL we know today and then, if there will be some important changes (like OOP approach available), we should refactor the applications again.

Please, don\`t understand me wrong. I am really happy with the changes we can see (ok, I won`t be OK with the missing .NET Interop for a long time as we use it almost everywhere), but would be really nice to have some strategic roadmap of the AL development. I mean I would be happy to see upcoming core ideas related to some dates (like 2018-Q1 etc.).

Anyway, thank you very much for your response. I appreciate it very much.

**Comment by StanislawStempin** [comment]
Method overloads, which should address this issue, were delivered for Anniversary Update.
