### ISSUE TITLE
AA0206 'variable is initialized but not used' is not issued for unused Option or Enum variables

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7290]
We don't seem to get AA0206 warnings about initialised-but-unused variables of Option or Enum type (we _do_ get AA0137 if they are never even initialised) - but I would think we should, no?

Code:
```al
    procedure CanBeCastedToInteger(pVariant: Variant): Boolean;
    var
        c: Char;
        i: Integer;
        b: BigInteger;
        d: Decimal;
        o: Option;
        e: Enum "Sales Document Type";
    begin
        c := 42;
        i := c;
        b := c;
        o := c;
        e := Enum::"Sales Document Type".FromInteger(c);
        d := c;
    end;
```

Result:
![image](https://user-images.githubusercontent.com/63455896/208410207-34c86c82-43ae-41b3-beca-b9a5465c0275.png)

Version:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 10.2.719883
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!
