### ISSUE TITLE
Debugger stops when expanding globals

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/AL#7292]
Please include the following with each issue:

**1. Describe the bug**
Expanding the Globals list stops the debugger
![image](https://user-images.githubusercontent.com/23434319/208977711-676cc5fd-0384-4103-89ff-a856eabd3418.png)
![image](https://user-images.githubusercontent.com/23434319/208977736-c67f9f40-1bd1-4b88-99f6-80ccad1862fc.png)

As a result, I cannot look at global variables while debugging. In order for me to see these values, I now have to create local variables and set those in the code. Takes me back to when the C/AL debugger wouldn't work, and we had to put in MESSAGE statements to see values. Good times :)

Related but different: https://github.com/microsoft/AL/issues/7273 

**2. To Reproduce**
Start the debugger, and expand the globals

**3. Expected behavior**
I expect to be able to expand the globals

**4. Actual behavior**
The debugger stops as soon as I click to expand the globals

**5. Versions:**
Local Hyper-V VM on Windows Server 2019 Standard, (host is on windows 11 pro) Docker container, BCContainerHelper 4.0.7
- AL Language: 10.2.719883
- Visual Studio Code: 
Version: 1.74.2 (system setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z (1 day ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No

- Business Central: US Business Central 21.2 (Platform 21.0.49939.50249 + Application 21.2.49946.50316)
- List of Visual Studio Code extensions that you have installed: standard apps that come with the container, plus the custom app that I am trying to debug

**Comment by nndobrev** [comment]
Hi @TheDenSter, can you please elaborate a bit within what context you can't expand global variables? Can you please share some sample code where the debugger fails?

**Comment by TheDenSter** [comment]
Any context, any code. Clicking the globals stops the debugger

**Comment by nndobrev** [comment]
Hi @TheDenSter, I tried reproducing the issue and I can't it seems like it is related somehow to your local docker setup, it is not related to us.

**Comment by fvet** [comment]
@nndobrev Our entire dev team is facing the same issues for several months on the latest vsix insider, not using docker, but normal online sandboxes. This happens when clicking on the globals section, faced it today whenever hovering over a record / recordref variables ... In short, debugging is hell and requires us to revert to adding 'messages' ... :(
