### ISSUE TITLE
Confused compiler looks in wrong path for dependencies in multi-root workspaces

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7293]
**1. Describe the bug**
When I open a multi-root workspace with four applications and try to compile (Strg + Shift + B), I often get an error message due to missing dependency applications. The CodeCops produces also a ton of errors.

**Error Message:**
```
Compilation started for project 'Module Z' containing '1615' files at '23:20:52.136'.

error AL1022: A package with publisher 'My Company', name 'This App', and a version compatible with '1.0.0.0' 
could not be found in the package cache folder 'c:\Users\user\source\repos\Module B\MainApp\.alpackages'
```
But the problem is that the compiler wants to compile **module Z**, but looks in the wrong folder **.alpackages** of **module B**.

![Screenshot](https://user-images.githubusercontent.com/9556549/209015582-20ac0c54-d44f-4a1b-9bb0-0dfe9c3156ff.png)

All modules each opened individually, compiled flawlessly every time.

Download Symbols fixes this problem, although there are no changes to the **.alpackages** folder, but it is annoying, should be fixed to lift and move properly 😊

**2. To Reproduce**

1. Create a multi root workspace as described.
2. Open it.
3. Try to compile a AL project with depenances that the other AL projects don't have.

**3. Expected behavior**
The compile (Strg + Shift + B) and CodeCops should work every time.

**4. Actual behavior**
```
error AL1022: A package with publisher 'My Company', name 'This App', and a version compatible with '1.0.0.0' 
could not be found in the package cache folder 'c:\Users\user\source\repos\Module B\MainApp\.alpackages'
```

**5. Versions:**
- AL Language: 10.2.719883
- Visual Studio Code: 1.74.1
- List of Visual Studio Code extensions that you have installed:
  - AL Language
### Final Checklist

Please remember to do the following:
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
I think I have seen this error multiple times before. I fixed this by specifying an common ``"al.packageCachePath"`` path in the workspace file. So every project is using the same packageCachePath.

**Comment by g021670** [comment]
Hit F1 and open "Preferences: open default settings (json)". search for .alpackages ->

// Sets the directory path where reference symbol packages are located

You can type relative or absolute path of the location, where to compiler looks for reference symbol packages.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.12045.0 and VS Code Extension Version 12.0.858534. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
