### ISSUE TITLE
False AS0026 error when changing parameter of an obsolete procedure

### ISSUE THREAD

**Issue by NicolasJdl** [microsoft/AL#7294]
**1. Describe the bug**
When upgrading my app version, if I change one parameter of an obsolete procedure, I get error AS0026.

**2. To Reproduce**

1. Create a codeunit with a procedure mark as obsolete

V1
```
[Obsolete('This function is replaced by MyProcedure with Transfer Shipment Header argument', 'V1')]
    procedure MyProcedure(Header: Record "Sales Shipment Header")
    begin
        If Header.FindFirst() then
            Message(Header."No.");
    end;
```

3. Compile and move the file AppName_V1.app generated in the /.alpackages folder
4. Upgrade the app version in your app.json, and set the version in the AppSourceCop.json to the previous one.
5. Change a parameter of the precedure in the codeunit

V2
```
procedure MyProcedure(Header: Record "Transfer Shipment Header")
    begin
        If Header.FindFirst() then
            Message(Header."No.");
    end;
```
6. Compile, and here you get error AS0026

**3. Expected behavior**
We should be able to delete or change the parameters of a procedure if the procedure was obsoleted

**4. Actual behavior**
```
error AS0026: The type or subtype of 'Header' has been modified from 'Record "Sales Shipment Header"' to 'Record "Transfer Shipment Header"'. 
This is not allowed in events and external procedures because it will break dependent extensions.
```

**5. Versions:**

- AL Language: v10.2.719883
- Visual Studio Code: 1.63.2

**Comment by qutreson** [comment]
@NicolasJdl - We couldn't reproduce the issue on a similar scenario. When the parameter has changed and the method is still obsolete, then an error is reported, as expected:
![image](https://user-images.githubusercontent.com/31541422/223104347-0ecf10b3-bc92-494c-8323-f44ae87b7bc4.png)

However, once the obsolete attribute has been removed, no error is reported anymore and the package can be built, as expected:
![image](https://user-images.githubusercontent.com/31541422/223104563-73676ded-4ea8-47f9-8a40-255d7a515527.png)

We believe it might then have been an AppSourceCop configuration issue. Can you share the workspace with which you can reproduce the issue?

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
