### ISSUE TITLE
TryFunctions.com not working

### ISSUE THREAD

**Issue by swensonic** [microsoft/AL#7297]
When trying to use tryfunctions.com/try. I select the "I'm Not a Robot" and then click on the "Create a sample function app" button and then nothing happens. I've tried in multiple browsers and in incognito mode and get the same behavior. I've also tried 3 different computers and get the same behavior.

**Comment by EmilDamsbo** [comment]
From your initial post, it seems your issue is out of scope for the AL Language. Please describe how this issue pertains to the AL Language extension, otherwise we will be closing your issue in the near future.
