### ISSUE TITLE
Code 'CR, DO, EC, SV, GT, HN, IL, NI, PA, PY, UY' is not a valid ISO 3166-1 alpha-2 code

### ISSUE THREAD

**Issue by ESkeiris** [microsoft/AL#7299]
**1. Describe the bug**
We are building an app for AppSource. In the AppSourceCop.json, we specify:
`"supportedCountries": ["CR","DO","EC","SV","GT","HN","IL","NI","PA","PY","UY"]`

As stated on Microsoft Learn those countries are available and supported
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations

**2. To Reproduce**
1. add `"supportedCountries": ["CR","DO","EC","SV","GT","HN","IL","NI","PA","PY","UY"]` in AppSourceCop.json.
2. Compile the app.

**3. Expected behavior**
Warning should not appear.
This same problem was resolved for  "ua" on  https://github.com/microsoft/AL/issues/6888

**4. Actual behavior**
When compiling our extension for AppSource, we receive the following warning:
`AppSourceCop.json(1,1): warning AS0056: The code 'CR, DO, EC, SV, GT, HN, IL, NI, PA, PY, UY' is not a valid ISO 3166-1 alpha-2 code for a country/region supported by the product.`

```
[{ 
      "resource": "/c:/AL/Productos/LicenseManagement/AppSourceCop.json",
      "owner": "_generated_diagnostic_collection_name_#0",
      "code": {
            "value": "AS0056",
            "target": {
                  "$mid": 1,
                  "external": "[https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0056](https://atpscan.global.hornetsecurity.com/index.php?atp_str=lAG6-ztqZfY4WDFOjYABK8skUsHJ0iQxxUCZ60pZFYd8AvZ5o478E_2Q1CcDPUPYPCJKOZPgDytldlEFuYgTbKblaItYx3CmOtsq2N7_keHQKYmroX9vtHEzVdpvClBdI2VLDN5cis0VJcJ57TiGtRLZMjlP9IxnO5sSKPEtWxI3rZGKmw2tMJx04i_kdvgRaJJpkBOHq-Yyape7b2zvJzhWaYalzOBIAhObKPSSuJoYrg-xCK_rUKuq3cpKnuAMmZ7t4LPt3rhLYNjrJ0ckg8ZoSoVekWMCp9ndi1cuUUnRF7Z6ihpVzGNlWckbQwadvGHWgVwGDlpxtlCqa7LOYb7xg87AXTpiXoYEtp_N5EfRaOZTvygV1rFxzuVmyeNgdn24ZILpm2wcAViDcLA0rUlOan_7Q58cAK7QA3koWvcQgvYvNKZlu46PiOlwaDYHajmxF0M8D7ZbHRrvVxDszAA6gs3k2cL2Q-AGDXcoLIsyaiHa94Dfxo7zsioShxUHwRZlitgGi4iI_BpzuP3ijVAJLEzYg5GBWXReQDTFnTuSlEgWjRSDEmuZJd5HJCz1rO2H8_tphzahiXqUzRrzGei4aEdcSNaiC00Qjf_nzxDNSwzOON_lbb9PJc7xD_sVDGWAPemqxJh3gz2jLUrmrPyduX2f9K9BJdl8xtyg58uDbfHvJWjpxHJSFN9M4nA0BhLHfrT3dVAT4GsHux9mD4EUr6jwSFwzQ_YJughNdBqf6V8TxqUsEXELmKeAeDPjxvA7e-vhJ455n4ZEX8BRNRBSLMrO2b6j25K-qHPkCSaAra42VldAf9GJHgbjyumFaGg5-fo1jxWNsaeSk-G7Zg2kc04FJ5U_ahQAN3EDnew9zHQJJs9CvsrRz7wpmuV3OF_1A8crGkDRrvU_XMZlZJETW4hFbiVDVHcvbi0aRjftA_AQiUjeBZb7aioWPMQ9VdxXNbNKXhi-EyZR5ZmJS-gqgziYIgIMcDMS2KkbdyM6OiMj1bbM4TXjTJ8mzRAjOjojC-BrsSiBpp8csYesUgg9rQ)",
                  "path": "/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0056",
                  "scheme": "https",
                  "authority": "learn.microsoft.com"
            }
      },

      "severity": 4,
      "message": "The code 'CR, DO, EC, SV, GT, HN, IL, NI, PA, PY, UY' is not a valid ISO 3166-1 alpha-2 code for a country/region supported by the product.",
      "source": "AL",
      "startLineNumber": 1,
      "startColumn": 1,
      "endLineNumber": 1,
      "endColumn": 1
}]

```
**5. Versions:**
AL Language: v10.2.719883
Visual Studio Code: 1.74.2
Business Central: 21.2

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.51711.0 and VS Code Extension Version 11.0.733768. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
