### ISSUE TITLE
Option type values in NAV App Object Metadata table

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#73]
There are numeric options type values in NAV App Object Metadata table after publishing an extension.
I guess they should be proper as all.
![option types](https://cloud.githubusercontent.com/assets/23735402/21982829/343cf71e-dc14-11e6-969d-bd58d360e481.png)

**Comment by DominikDitoIvosevic** [comment]
@pmohanakrishna Could you help us understand how you got to this state? Do you have some code with which we could repro this?

**Comment by DominikDitoIvosevic** [comment]
@pmohanakrishna If you are still encountering this error please ping us back. Since there was no response for 8 months, I'm closing this
