### ISSUE TITLE
New DataTransfer Needs Better Error Reporting

### ISSUE THREAD

**Issue by mattkeyeswc** [microsoft/AL#7301]
Hello,

We are using the DataTransfer functionality to migrate a large amount of data from an old version of an extension that has been redone under a new app ID into a new version (the earlier version was just a prototype of sorts, and the new version is a product that we resell to clients).  When running the DataTransfer process, very little is provided in terms of which tables and fields are causing problems, and this creates hours of research.  I have been able to get past that; however, now I am failing on a primary key error but there is no indication which tables are causing the issue.  We are migrating data by table ID (so that we do not have to install all of the dependencies), and I introduced some logging features as well but those are not working.

The error I have right now is the following:

`Error code: 85132273`

After some Google searching, I found this is a primary key violation.  The DataTransfer executes within a codeunit OnRun trigger, and, when I wrap it with if not Codeunit.Run() then HandleError(GetLastErrorText()), I then receive the following error message:

`An error occurred and the transaction is stopped. Contact your administrator or partner for further assistance.`

Due to the virtually non-existent error reporting in the DataTransfer process, we cannot proceed at this point as we have no idea which table (out of tens to potentially over a hundred) is involved.  Would it be possible to please improve the error messages coming from the DataTransfer process?

Additionally, since we cannot debug an installation/upgrade routine, can we please allow the DataTransfer process to be run outside of an installation/upgrade scenario (i.e., be able to run it simply in the client as a routine)?

**Comment by NKarolak** [comment]
> since we cannot debug an installation/upgrade routine

You can:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debug-upgrade-install-code

**Comment by mattkeyeswc** [comment]
Ah, thank you!  I did not think to use the Attach debugger (to be honest, I've had mixed results with it in the past but perhaps it works better now).  I will give that a shot.

**Comment by PhDuck** [comment]
Great to hear you are using DataTransfer :)

When you are getting this limited errors are you picking these up on a local installation or is this error messages coming from SaaS?

I will take a look and see if we can do something about passing the underlying SQL errors with more info.

@thpeder can you make this a bug and assign it to me please?

**Comment by mattkeyeswc** [comment]
Hi NKarolak, attaching the debugger did not work, just FYI.  I will probably have to open a support ticket for this issue due to the lack of error reporting

**Comment by NKarolak** [comment]
@mattkeyeswc It worked for me in the past. Maybe try another how-to; just follow my thread here: https://twitter.com/KarolakNatalie/status/1527591836294033408

**Comment by mattkeyeswc** [comment]
Thank you @NKarolak.  I will keep trying but I think it has to do with my partner account configuration so that I can support both BC and their Azure portal.  I can't open support tickets for this client, either, due to the same reasons.  I will post back if I can figure this out

**Comment by mattkeyeswc** [comment]
@NKarolak thank you for the help.  I had my tenant guest account delegation removed, and I can follow your steps now.  It worked!  I was unable to get the F5 version to work, however.  That would be a little more efficient but I'm running into problems, too.

At any rate, thanks for point out how to get this to work!!

**Comment by NKarolak** [comment]
@mattkeyeswc You're very welcome :-)
However, are you sure you want to keep the bug closed and thus stop @PhDuck from working on a better error reporting?

**Comment by mattkeyeswc** [comment]
Hi @NKarolak I have what I need here but better error reporting would be nice.  Reopened.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.52808.0 and VS Code Extension Version 11.0.746383. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
