### ISSUE TITLE
DataItemTableView not sorting keys correctly

### ISSUE THREAD

**Issue by deadmouse** [microsoft/AL#7302]
**1. Describe the bug**
DataItemTableView not sorting keys correctly when using intellisense.

![image](https://user-images.githubusercontent.com/6352552/211532299-9b0ead67-3a48-4c17-8bb2-d096ad17620c.png)

**2. To Reproduce**

1. Create new report.
2. Add new dataitem. E.g.: Sales Header.
3. Insert DataItemTableView, add "sorting" property, 

**3. Expected behavior**
Keys in correct order (key1, key2, ..., key10, key11, etc.).

**4. Actual behavior**
Keys are incorrectly ordered (key11, key10, key1, key2, ..., etc.).

**5. Versions:**

- AL Language: 10.3.731181
- Visual Studio Code: 1.74.2
- Business Central: Not needed
- List of Visual Studio Code extensions that you have installed: AL Language, AZ AL Dev Tools, Explorer Exclude, Git Graph, GitLens, TabOut, Todo Tree, waldo's CRLS AL Language.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JMA1972** [comment]
I can't imagine a use case where the sorting of the keys is of any importance. Do I miss something here?

**Comment by NKarolak** [comment]
@JMA1972 It is not _important_, but wouldn't you mind if intellisense would also reorder fields?

@deadmouse Wouldn't you expect the keys to be sorted in their order of declaration instead of key name?

**Comment by JMA1972** [comment]
@NKarolak : Field names ARE important, key names not.
If the key sorting will be changed at all it should be ordered by the fields in it because the fields in the keys are the only thing I'm interested in.

**Comment by srenders** [comment]
Why show keys here anyway? Should a sorting not be possible on any column from the table?
