### ISSUE TITLE
Incorrect error message for SubString() method

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/AL#7304]
**1. Describe the bug**
The bug is that the SubString returns an invalid error when the length of the target string is smaller than the value of the 'Count' parameter. The error message ("Index and length must refer to a location within the string. Parameter name: length") refers to a parameter that does not exist for the SubString method. 

I have some address fields in a custom table, which I have programmed to follow along with every other set of address fields in the base app. One of the things you have to do is send the address fields into the PostCode.LookupPostCode function, which in turn populate city/state/zip into the appropriate fields from the Post Code table. The problem is that the parameters in that function are of type Text, and the fields are of type Text[30], so the compiler yells at you that you have a potential overflow situation. Irritating that this sort of thing happens in the standard app, but not the biggest problem. So I create my own LookupPostCode function where I have local Text type vars and so I have to trim those back down to length 30. See the procedure below.

I thought I'd use the SubString method, which has two parameters: StartIndex and Count. The problem is that when the target text is less than the number of characters I want to trim to (i.e. the value of the Count variable), I'm getting an error message "Index and length must refer to a location within the string. Parameter name: length". The first problem here is that there is no parameter called 'length'. The second problem is that as an AL developer, you expect to get back the whole string when that is smaller than the Count parameter, just like the CopyStr function is able to do.

Seems like I have to actually program a check for the length of the returned string before I call SubString. Not very programmer-friendly, so I went back to using CopyStr, which does work when the string is smaller than the Length parameter.

**2. To Reproduce**
- add address fields to a custom table
- add the following procedure to the table
``` AL
    local procedure LookupPostCode(var MyCity: Text[30]; var MyZIPCode: Code[20]; var MyState: Text[30]; var MyCountryRegionCode: Code[10])
    var
        PostCode: Record "Post Code";
        CityText: Text;
        StateText: Text;
    begin
        CityText := MyCity;
        StateText := MyState;
        PostCode.LookupPostCode(CityText, MyZIPCode, StateText, MyCountryRegionCode);
        MyCity := CityText.Substring(1, 30);
        MyState := StateText.Substring(1, 30);
    end;
```
- add this OnLookup trigger to the city and ZIP fields
``` AL
            trigger OnLookup()
            begin
                LookupPostCode("City", "ZIP Code", "State", "Country/Region Code");
            end;
```
- then deploy to BC, hit the lookup button from the custom city/state field and pick one. You should get the error "Index and length must refer to a location within the string. Parameter name: length"

**3. Expected behavior**
I expect SubString to just return the whole string when its length is less than the Count parameter. If you insist on keeping this as an error situation, then I expect the error to describe the actual problem, like 'You cannot cut x number of characters from a string that is less than x characters long' or something like that. The error message as it is today refers to a parameter that does not exist, and frankly the message itself is VERY unclear.

Here's the documentation for the SubString method, which does not mention any parameter called 'Length'
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-substring-method

**4. Actual behavior**
I described the actual behavior above

**5. Versions:**
- AL Language: v10.3.731181
- Visual Studio Code:
Version: 1.74.2 (system setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z (3 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No

- Business Central:US Business Central 21.3 (Platform 21.0.51393.51935 + Application 21.3.51409.52006)

**Comment by TheDenSter** [comment]
Found a reference to the same problem in the documentation https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1355

I don't think this is a problem with the documentation though, this is a problem with the content of the error message, and actually I think that SubString should work the same as CopyStr when it comes to the length of the target string

**Comment by dnpb** [comment]
> actually I think that SubString should work the same as CopyStr when it comes to the length of the target string

That would be a breaking change at this point, though.

It would also make the method inconsistent with its underlying .Net counterpart (which also might be what is throwing the seemingly unrelated error?)

**Comment by TheDenSter** [comment]
Yeah I didn't think you were going to fix this. I'll submit a PR on the documentation to describe the behavior, because the error is just incorrect. Thanks for looking into this.

**Comment by dnpb** [comment]
There is no "you" as I don't work for MS :-) was just pointing out that, if they did want to change it, they risk breaking existing code.

**Comment by TheDenSter** [comment]
oh! I thought you were at MS, sorry :)
