### ISSUE TITLE
Cloud sandbox authentication does not work

### ISSUE THREAD

**Issue by sirhc101** [microsoft/AL#7305]
Please include the following with each issue:

**1. Describe the bug**
Whenever I try to download symbols I just see "Authenticating..." and nothing else happens:
![image](https://user-images.githubusercontent.com/39621236/212319131-9c821f27-48ad-403c-9f24-590aeb6931ff.png)

**2. To Reproduce**

1. `AL: Go!`
2. Select "Microsoft cloud sandbox"
3. Execute `AL: Download symbols`

**3. Expected behavior**
Authentication with Sandbox and download symbols.

**4. Actual behavior**
Simply nothing happens.

**5. Versions:**

- AL Language: 10.3.731181
- Visual Studio Code: 1.74.3
- Business Central: 21.2.49946.49990

**Comment by JMA1972** [comment]
I just tried that and got a little window to provide the authentication:
![image](https://user-images.githubusercontent.com/92122854/212341058-1e7b87b5-1992-4df6-b92c-ecc578175e3b.png)

**Comment by sirhc101** [comment]
Yes, this is what I expected in some way, but nothing shows up. I also cleared the credential cache multiple times, restarted VSCode, restarted my computer. Nothing works...

**Comment by sirhc101** [comment]
I needed to copy the symbols from another project and run publish command. Then the authentication worked!
