### ISSUE TITLE
DefaultRenderingLayout cannot be overriden in ReportExtension

### ISSUE THREAD

**Issue by jorispoppe** [microsoft/AL#7307]
**1. Describe the enhancement**
When developing a report and a report extension on it, you can override the property RDLCLayout or WordLayout in the report extension. But when using the Rendering section, you can add new layouts but you cannot override the DefaultRenderingLayout.
It would be great to be able to set the default to the extended layout.

**2. To Reproduce**

- Report:

```
report 50100 MyReport
{
    UsageCategory = ReportsAndAnalysis;
    ApplicationArea = All;
    DefaultRenderingLayout = LayoutName;

    dataset
    {
        dataitem(Customer; Customer)
        {
            column(No_; "No.") { }
            column(Name; Name) { }
        }
    }

    rendering
    {
        layout(LayoutName)
        {
            Type = RDLC;
            LayoutFile = 'mylayout.rdlc';
        }
    }
}
```

- ReportExtension

```
reportextension 51100 MyExtendedReport extends MyReport
{
    dataset
    {
        add(Customer)
        {
            column(Address; Address) { }
        }
    }

    rendering
    {
        layout(ExtLayoutName)
        {
            Type = RDLC;
            LayoutFile = 'myExtendedLayout.rdlc';
        }
    }
}
```

**3. Expected behavior**
Be able to set the DefaultRenderingLayout in the ReportExtension.

**4. Actual behavior**
Compiler Error: The property 'DefaultRenderingLayout' cannot be used in this context.

**5. Versions:**

- AL Language: v10.3.731181
- Visual Studio Code: 1.74.3

**Comment by EmilDamsbo** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
