### ISSUE TITLE
An error occurs while using the Method List.Contains(T) with T of type Dictionary

### ISSUE THREAD

**Issue by oni1300** [microsoft/AL#7308]
Hello,
we are using BC21CU2 OnPrem.

By executing the following code
```
local procedure Table_PurchaseLine_OnAfterInitDefaultDimensionSources(var PurchaseLine: Record "Purchase Line"; var DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer)
var
	DimSourceOld: Dictionary of [Integer, Code[20]];
...
		DimSourceOld.Add(Database::Job, PurchaseLine."Job No.");
		if DefaultDimSource.Contains(DimSourceOld) then
			DoSomething();
```
an error is thrown at Method **DefaultDimSource.Contains(..**:
"Unable to compare operands of type NavDictionary`2 with NavDictionary`2."

The same error occurs while using Method DefaultDimSource.IndexOf(...

**Comment by RadoArvay** [comment]
The documentation is not updated yet and there is still "The List can only be used with simple types." Maybe for complex types, there is no other option than to loop through <T> values.
I am wondering of an answer from someone.

**Comment by oni1300** [comment]
I noticed that but I assumed that I can use all list type methods, not only adding 😉. Ok, lesson learned. Foreach works as well in my case.


Von: RadoArvay ***@***.***>
Gesendet: Dienstag, 17. Januar 2023 20:02
An: microsoft/AL ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/AL] An error occurs while using the Method List.Contains(T) with T of type Dictionary (Issue #7308)


The documentation is not updated yet and there is still "The List can only be used with simple types." Maybe for complex types, there is no other option than to loop through values.
I am wondering of an answer from someone.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
