### ISSUE TITLE
Blob field retains part of old content after write - sometimes

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#7314]
Hi,

I managed to debug a weird issue within one of our solutions and then narrowed it down to the following either bug or undocumented feature of blob fields.

```
BEHAVE_WEIRD := true;
salesheader.FindFirst();
salesheader."Work Description".CreateOutStream(outStr);
outstr.WriteText('### LONG TEXT MUCH STUFF HAPPENING ###');
salesheader.Modify();
if not BEHAVE_WEIRD then salesheader.FindFirst();
salesheader."Work Description".CreateOutStream(outstr);
outstr.WriteText('-new short text-');
salesheader.Modify();

salesheader."Work Description".CreateInStream(instr);
instr.ReadText(tx);
Message(tx);
```

![image](https://user-images.githubusercontent.com/35798628/214807064-491acf3a-dc27-41ac-8efd-a99e54bf9aa7.png)

If there is no find being run between the writes to the blob, or if we don't specifically run a clear() on the blob variable before the second write, we end up with mixed contents between the first and second write.

..this is probably not to be expected, or is it documented somewhere?

**Comment by navdotnetreqs** [comment]
Anything?

**Comment by nicolassaleron** [comment]
It is by design, the BLOB should be cleared if you want to overwrite it completely.
By just opening an outputstream, the cursor is positioned at the beginning of the stream and starts replacing the existing data byte per byte.

**Comment by navdotnetreqs** [comment]
> It is by design, the BLOB should be cleared if you want to overwrite it completely. By just opening an outputstream, the cursor is positioned at the beginning of the stream and starts replacing the existing data byte per byte.

Then why does re-fetching the blob without clearing it result in a different behavior ?

**Comment by nicolassaleron** [comment]
Do you mean that if BEHAVE_WEIRD = false, then the message is "### LONG TEXT MUCH STUFF HAPPENING ###-new short text-" ?

I am not absolutely sure of my answer but my guess is that if you do not Clear the stream between two CreateOutStream calls, the cursor stays at the same position.
It might be a bug, but it is also a bad usage of a stream :)

**Comment by navdotnetreqs** [comment]
> Do you mean that if BEHAVE_WEIRD = false, then the message is "### LONG TEXT MUCH STUFF HAPPENING ###-new short text-" ?

No, if you set behave_weird = false, it works the way it should, eg. the message is:
"-new short text-"

Writing to a blob always replaces the entire content. Except in this weird case,
when something is pertained in local scope that clearly should not be.

**Comment by dannoe** [comment]
``salesheader.FindFirst();`` is clearing the stream. If you call ``CalcFields`` after the ``FindFirst``, it will still print ``-new short text-CH STUFF HAPPENING ###`` because without the ``CalcFields`` (or another ``CreateOutStream``) your stream will be empty.

```
...
if not BEHAVE_WEIRD then begin
    SalesHeader.FindFirst();
    SalesHeader.CalcFields("Work Description");
end;
...
```

If you want to append to the existing BLOB data, you have to export the previous data first and append to that and then write it to the BLOB again.

**Comment by thloke** [comment]
As noted, this is by design. We can definitely document this better though. Can you create an issue at https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues to update the documentation on BLOB to cover this?
