### ISSUE TITLE
PromotedActionCategories is ignored in extension

### ISSUE THREAD

**Issue by MortenSteengaard** [microsoft/AL#7315]
The property PromotedActionCategories is ignored in my new page with pagetype = Document.

My code:

```
page 50136 "myPage"
{
    Caption = 'My Page';
    PageType = Document;
    PromotedActionCategories = 'New,Process,Report,Approve,Release,Posting,Prepare,Order,Request Approval,History,Print/Send,Navigate';
```

...
```
                action(DocAttach5)
                {
                    ApplicationArea = All;
                    Caption = '5';
                    Image = Attach;
                    Promoted = true;
                    PromotedCategory = Category5;
                    ToolTip = '5';

                    trigger OnAction()
                    begin
                        Message('');
                    end;
                }

```
When my page is shown the action has the caption "Category 5". It should have the caption "Release".

You can reproduce the error by copying page 42 (Sales Order), change the object id and name, and add it as a new page in an extension.

This error is on newest Business Central cloud in Danish.

**Comment by dnpb** [comment]
Yes, I believe BC 21.3 is severely broken wrt translations. and I think this is just one part of it.

Until they hotfix it, you should be able to work around it by either running BC in en-US, or explicitly adding `PromotedActionCategoriesML = ENU = 'Foo', DAN = 'Foo'` or whatever language you want to run in,

**Comment by MortenSteengaard** [comment]
Hi dnpb,

Thank you very much for your comment.

You are right. Your solution works.

Best regards,

Morten

**Comment by EmilDamsbo** [comment]
We have recently deployed hotfixes regarding the translation issues, and I believe that this issue has been resolved as a result. Please open a new issue if you believe this has not been resolved and reference the current issue.
