### ISSUE TITLE
New Code Warning if global procedures are declared inside an Object that has set its Access property to internal 

### ISSUE THREAD

**Issue by MichaelSchauer98** [microsoft/AL#7316]
Hi, 

The access property of an AL object can be easily overlooked, especially in objects with much code in it. If set to internal global procedures cannot be called from another app, which makes sense but a code-warning which indicates that global procedures inside an access restricted object cannot be called from another app would be a helpful indicator. 

Thanks and best regards,
Michael

**Comment by dnpb** [comment]
I guess just to protect against developers not noticing the `Access = Internal` at the top of the codeunit, and adding `procedure`s without access modifier, thus thinking they'll be public, and only finding out later when trying to use the app as a dependency that they aren't.

**Comment by TKapitan** [comment]
Hmm, but do we really want to see warnings for something that's usually intended behaviour? In our projects, we often use Internal objects to hide the implementation.

So yes, it could be added but please set it hidden by default.

**Comment by thloke** [comment]
I'm not sure if we want to add this for a few reasons:

1. It will be very noisy on existing code. I suspect there are many `internal` objects with procedures not marked with `local` or `internal`.
2. We'll ideally want a code action to add `internal` on any global procedures in an `internal` object.
3. It will make the language more verbose. It would mean every procedure on an `internal` object will need a `internal` or `local` modifier.

We'll need more feedback from the partner community to see if we really want this. You can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
