### ISSUE TITLE
Cannot update app from AppSource at customer due to table size

### ISSUE THREAD

**Issue by Heinz2611** [microsoft/AL#7318]
Hello all,

We have a big problem with installing an update of our app from AppSource at a customer. The app is published as "Contact me" in AppSource, and we install the app on behalf of our customers in their tenant. The Microsoft Tek Experts, with whom we raised a support call (TrackingID#2301110040003370) directed us here for further help or explanations. According to them, one of our tables exceeds the allowed size limit, and there seems to be no way to fix this.

As this is my first try at GitHub, please let me know if this is the wrong forum/channel and kindly move my posting elsewhere, if necessary. Any help or hints will be gladly appreciated.

So, here is what happened:

1. We published an app to AppSource several months ago. The app has since undergone several updates, without any problems or errors.

2. The last update introduced some more fields to a certain table. There were NO errors or warnings in VS Code. As a side note, we also provide the app for the older NAV versions, where there was no error message regarding table size either. The table has a lot of fields (some 420), but still well below the documented limit of 500 fields per table.

3. When the new version was published to AppSource, we received an error message stating that a "database operation was aborted" (roughly translated from the German original). Research and consultation with other developers pointed to the "CompressionType" attribute of the table, which was not set/used by us, but seems to be set automatically in AppSource, and which somehow "collided" with table or key size (table too large to be compressed? whatever...). We were recommended to explicitly set CompressionType=None on this certain table, which we did.

4. The next attempt at publishing the app gave an error that modifying the CompressionType for an already published app was considered a breaking change and therefore not allowed. We opened a call and within a few days, this was changed on AppSource - modifying this property is now allowed, and we could successfully publish the new version of our app, new fields and all, to AppSource.

5. **Installing the app at a new Cloud/SaaS customer worked without any problems. However, when we tried to install the new version at a customer who already had the (old version of the) app installed, we received yet another "database operation was aborted" error.**

6. So we opened another call and were informed that the table's record was too large - 8109 bytes instead of the allowed 8060. Please recall that we did not receive an error or warning in VS Code or during AppSource validation, and that a first time install at a new customer was successful. We were recommended by the Tek Experts to redesign the table.

7. Unfortunately, the only way we know to redesign the table would be to set some fields to "Obsolete", which of course did not help, as the fields still occupy storage space. And "physically removing" fields is not allowed or possible in a Cloud app. In an OnPrem installation, we could publish the app with "Force" or, as a last resort, with "Recreate", but how can we do this in the Cloud?

So now we are stuck there. **We are supposed to reduce table size, but can not do this due to the restriction of removing fields**. The app compiles and publishes without error or warning, but updating an old version at an existing customer fails. We also tried resetting /deleting the CompressionType property, but no matter what we tried, the app refused to deploy in the customer's tenant. To make matters worse, the old version of our app has completely disappeared from the customer's extension management list, so we can't even go back to the old version - which would be useless anyway, as this is an app that needs to be adapted to new legal requirements on a regular basis.

What shall and can we do to solve this? And why is there no indication in VS Code or at least during AppSource validation that some table size limit has been exceeded?

Thank you for your time, best regards,
Heinz Herbeck

**Comment by Heinz2611** [comment]
Hi Emil,

Actually, there is an ongoing support case and the support team repeatedly recommended us to take our issue HERE, giving us the exakt URL "al/issues" for reference. They said here we would "get into contact with the developers and experts". And, as I mentioned in my post, this in fact is also an issue with the compiler and tools, as there is no warning or other indication that a table exceeds size limits.

So, what are we supposed to do?
Heinz

**Comment by qutreson** [comment]
@Heinz2611 - I am closing this issue because it is being handled as part of the support case 2301110040003370 which is still active. We will investigate better compiler/analyzer validation that could help catching such issues, but to mitigate your customer environments the support case is the right way to proceed.
