### ISSUE TITLE
CodeCop Warning AA0008: Warning doesn't show up for standard procedure calls without any parameters (e.g. .IsEmpty, .RecordId, .Count)

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/AL#7321]
Please include the following with each issue:

**1. Describe the bug**
As the CodeCop is activated no warnings are shown for AA0008 for procedure calls which doesn't require any parameters. On calls like FindSet which has optional parameters it's working.

![image](https://user-images.githubusercontent.com/88825803/217533771-7727bd5c-1190-4270-8a4e-1d78766b305e.png)

But the tooltip of the commands show that those are procedures having parenthesis:
![image](https://user-images.githubusercontent.com/88825803/217533812-0fa5df76-93d5-4673-abbd-0be82ba968eb.png)

This would go against the rule of AA0008
![image](https://user-images.githubusercontent.com/88825803/217534058-d28b9691-b00f-4889-a2e5-2e3ae487b7a4.png)

**2. To Reproduce**
Activate Code analysis for the workspace and add "CodeCop" as cop

Add following lines:

![image](https://user-images.githubusercontent.com/88825803/217533663-8d05cc2d-f9d5-4cfa-96c8-4b524cbd35a2.png)

``` AL
codeunit 50000 "AA0008 GitHub"
{
    local procedure AA0008()
    var
        SalesLine: Record "Sales Line";
        RecordIdTemp: RecordId;
    begin
        // Works
        SalesLine.FindSet;
        // Works
        HelloWorld;

        // Doesn't work
        Message(Format(SalesLine.IsEmpty));
        if SalesLine.IsEmpty then;

        Message(Format(SalesLine.Count));
        if SalesLine.Count > 0 then;

        Message(Format(SalesLine.RecordId));
        if SalesLine.RecordId = RecordIdTemp then;
    end;

    local procedure HelloWorld()
    begin
        Message('Hello World');
    end;
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Show a warning for standard procedure calls with no parameters

**4. Actual behavior**
Show no warning for standard procedure calls with no parameters

**5. Versions:**

- AL Language: 11.0.748446
- Visual Studio Code: 1.75.0
- Business Central: sandbox/21.4.52563.52989/w1
- List of Visual Studio Code extensions that you have installed:
AL CodeActions
AL Language
AL Toolbox
AL Variable Helper
AZ AL Dev Tools / AL Code Outline
waldo's CRS AL Language Extension
NAB AL Tools
Git Tree Compare
Git Lens
Xliff Sync
Project Manager
Error Lens

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
``IsEmpty``, ``Count``, etc. are Properties which can be accessed using the property access syntax. (see https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-count-method) This does not require parentheses.

This is by-design, see https://github.com/microsoft/AL/issues/6908#issuecomment-1028644117

**Comment by PiGlic** [comment]
This is a little bit confusing even in the Docs (For IsEmpty and Count) the Example uses the ().
![image](https://user-images.githubusercontent.com/36172313/217783880-b9c772f3-7582-4eeb-80ce-3fde4bdad431.png)

But thanks for the Information!
