### ISSUE TITLE
AS0110/PTE0016/AA0050: Permissions for the object '"XXXX"' cannot be added through a permission set extension because it is defined in another application.

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#7323]
**1. Describe the bug**
"AS0110/PTE0016/AA0050: Permissions for the object '"XXXX"' cannot be added through a permission set extension because it is defined in another application."

I probably do not understand this error/warning - XXXX object is from the application, and I want to add this object to the base permissionset using permissionsetextension. 

**2. How to replicate**

1. Create a new table in your extension
2. Create permissionsetextension that extends for example "D365 BASIC"
3. Add your table

**5. Versions:**
Next-Major 22.0.53150.0

**Comment by SBalslev** [comment]
Thanks for reporting this, sounds like it might be a bug. It is supposed to warn you if you extend a permission set and include objects from outside your extension.

**Comment by pri-kise** [comment]
We receive the same warning on our NextMajor pipelines an we're only adding our own objects on some permissionsets.

**Comment by BazookaMusic** [comment]
Could you provide an example project where you see this failure?

Trying to replicate with the given steps does not produce any warnings on the simple project below, so it might be something particular in your use case that confuses the analyzer

[example-no-repro.zip](https://github.com/microsoft/AL/files/10840899/example-no-repro.zip)

**Comment by TKapitan** [comment]
Just for clarification, as of 22.0.53703.0, all three cops are warnings (still broken, but warnings). Previously the AA was an error.
