### ISSUE TITLE
SetRange and SetFilter does not work correctly on DateTime fields

### ISSUE THREAD

**Issue by DBiernat** [microsoft/AL#7325]
**1. Describe the bug**
If you apply one of the following record filters, you will get a result set with records that are outside the filter after e.g. calling FindSet():

Record.SetRange(DateTimeField, 0DT, CreateDateTime(Date, 235959.999T);
Record.SetFilter(DateTimeField, '%1..%2', 0DT, CreateDateTime(Date, 235959.999T);

**2. To Reproduce**
I've attached a sample project to this issue. Just click on the "Reproduce" action under the home group.
I've tested it with ENU and DEU region.

``` AL
GenJournalLine.DeleteAll(false);

GenJournalLine.Init();
GenJournalLine."Line No." := 10000;
GenJournalLine."Last Modified DateTime" := CreateDateTime(20240325D, 000000.000T);
GenJournalLine.Insert(false);

Message('Inserted Line with %1 = %2', GenJournalLine.FieldName("Last Modified DateTime"), GenJournalLine."Last Modified DateTime");

CorrectFilterGenJournalLine.Reset();
CorrectFilterGenJournalLine.SetRange("Last Modified DateTime", 0DT, CreateDateTime(20240324D, 235959.998T));
if not CorrectFilterGenJournalLine.FindSet() then
    Message('No line found, this is correct. Filter: %1', CorrectFilterGenJournalLine.GetFilters());

WrongFilterGenJournalLine.Reset();
WrongFilterGenJournalLine.SetFilter("Last Modified DateTime", '%1..%2', 0DT, CreateDateTime(20240324D, 235959.999T));
if WrongFilterGenJournalLine.FindSet() then
    Message('Line found, this is wrong. Filter: %1', WrongFilterGenJournalLine.GetFilters());
```

**3. Expected behavior**
Only valid records should be inside the result set.

**4. Actual behavior**
Invalid records are inside the result set. To me it looks like there is some kind of rounding going on if the filter contains 999 milliseconds.

**5. Versions:**

- AL Language:
  v10.4.747197
- Visual Studio Code:
  1.75.1
- Business Central:
  21.4.52563.53193
- List of Visual Studio Code extensions that you have installed:
  andrzejzwierzchowski.al-code-outline
  DavidAnson.vscode-markdownlint
  GrapeCity.gc-excelviewer
  idleberg.openvpn
  mhutchie.git-graph
  ms-azure-devops.azure-pipelines
  ms-azuretools.vscode-docker
  ms-dotnettools.csharp
  ms-dynamics-smb.al
  ms-vscode.azure-account
  ms-vscode.powershell
  statical.prism-al
  vscode-icons-team.vscode-icons
  waldo.crs-al-language-extension
  wayou.vscode-todo-highlight

**Comment by DBiernat** [comment]
[DatTimeFilterBug.zip](https://github.com/microsoft/AL/files/10734276/DatTimeFilterBug.zip)

**Comment by JMA1972** [comment]
That's not a bug, DateTimes in SQL are rounded to increments of .000, .003, or .007 seconds. AL can't do anything about that.

**Comment by DBiernat** [comment]
> That's not a bug, DateTimes in SQL are rounded to increments of .000, .003, or .007 seconds. AL can't do anything about that.

Thanks for the answer. That's really a strange behavior, that I was not aware of! However, BC should behave the same way I guess. Setting a filter value to .999 milliseconds should be rounded to the same value as in the SQL table, after returning the filter with GetFilters().

Btw., the following AL statement
```
Result := (CreateDateTime(20240324D, 235959.999T) >= CreateDateTime(20240325D, 000000.000T);
```
returns false. No rounding here.

To me, BC should behave the same in all situations.

**Comment by dnpb** [comment]
The rounding only occurs once the data/filter gets to SQL, so (a) an in-AL comparison would not have it and (b) making it so would mean AL becomes extra-coupled to implementation details of SQL Server, which I don't think is a terribly good move.

**Comment by thloke** [comment]
As mentioned, this is a consequence of the underlying SQL construct so it's by design.
