### ISSUE TITLE
List type enhancement using Join

### ISSUE THREAD

**Issue by warlof** [microsoft/AL#7326]
Hello there,

That would be awesome if we could have a `Join(string): string` method on the `List` type for convenience.

I worked on a path builder yesterday using that type and had to loop manually over the list to switch from the list to the string using a union value.

Usage:

```
MyList.Add(Element1)
MyList.Add(Element2)
MyList.Join(',') // Element,Element2
```

**Comment by thloke** [comment]
Thanks for the suggestion. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
