### ISSUE TITLE
Backslash ( \ ) issue in Dialog functions for printing a new line.

### ISSUE THREAD

**Issue by hassnainmunir** [microsoft/AL#7327]
**1. Describe the bug**
There is an issue while using Backslash (\\) in dialog functions. I have tested it for error, confirmation and message dialog boxes.
_**Note:** For any strange reason the backslash in label does not work just for the first instance of "\\". For all other backslashes it works as expected._

**2. To Reproduce**

Write the following code in Visual Studio Code (Taken from Microsoft Learn: [Link](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-message-method))
```al
begin
        Message('App published: Hello world');

        Text := 'ABCDE';
        Number := 12345.678;

        // The backslash indicates a new line.  
        // You can concatenate strings using the + operator.  
        // You can insert variable values using the % symbol.  
        Message(Text000 + Text001 + '%1\' + Text002 + '%2\', Number, Text);
    end;


    var
        Text: Text;
        Number: Decimal;
        Text000: Label 'You can use message windows to display text and numbers: \';
        Text001: Label 'The number: ';
        Text002: Label 'The text: ';

  ```

**3. Expected behavior:** As per documentation of MS Learn.

The message window reads: 
**You can use message windows to display text and numbers:**  
**The number: 12,345.678**  
**The text: ABCDE** 

**_Screenshot:_**
![image_2023_02_20T07_57_58_830Z](https://user-images.githubusercontent.com/96062001/220046740-455106d0-b28d-4ad0-b764-084d7d13cc21.png)

**4. Actual behavior:** The first line \\ is not working as shown below.

The message window reads: 
**You can use message windows to display text and numbers:The number: 12,345.678** 
**The text: ABCDE**  

**_Screenshot:_**
![image_2023_02_20T07_34_00_952Z](https://user-images.githubusercontent.com/96062001/220045750-c3315572-6979-44ee-8cd7-0c432ff36210.png)

**5. Versions:**

- AL Language: 10.4.747197
- Visual Studio Code: 1.74.3
- Business Central: DK Business Central 21.4 (Platform 21.0.52534.53320 + Application 21.4.52563.52602)
- List of Visual Studio Code extensions that you have installed: AL Language, AZ AL Dev Tools, waldo's CRLS AL Language.

**Comment by fauzanazam-DI** [comment]
I am encountering this issue since last Thursday, Feb 16, 2023. 
You are right, just first backslash is being ignored for a strange reason, perhaps a bug because it was working fine before.

**Comment by Yu-457** [comment]
Hey @all, 

we've encountered this issue too and reported it to MS via a support ticket. 
Theyre going to fix this in the next rollup. Build: 21.0.53184.0

**Comment by BazookaMusic** [comment]
I am closing this bug since it is related to the runtime and a support ticket was already raised.

Thanks @Yu-457
