### ISSUE TITLE
The type of the parameter 'TempBlob' on the event subscriber 'OnExportXMLFileOnBeforeBLOBExport' does not match the expected type '__MissingTypeSymbol__'.

### ISSUE THREAD

**Issue by BilalRai** [microsoft/AL#7339]
I am checking my extension against v22 and found this issue AL0284 that type of parameter is not correct. 

**Error:** [{
	"resource": "/c:/Offic/Tasks & Issues/Extension Subscription/Customer/Customer***/src/codeunit/EventLibrary.codeunit.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "AL0284",
		"target": {
			"$mid": 1,
			"path": "/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al284",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 8,
	"message": "The type of the parameter 'TempBlob' on the event subscriber 'OnExportXMLFileOnBeforeBLOBExport' does not match the expected type '__MissingTypeSymbol__'.",
	"source": "AL",
	"startLineNumber": 16,
	"startColumn": 76,
	"endLineNumber": 16,
	"endColumn": 84
}]

**Following is my code:**

codeunit 50104 "Event Library"
{
[EventSubscriber(ObjectType::Codeunit, Codeunit::"OIOUBL-Management", 'OnExportXMLFileOnBeforeBLOBExport', '', false, false)]
    local procedure OnExportXMLFileOnBeforeBLOBExport(DocNo: Code[20]; var TempBlob: Codeunit "Temp Blob"; FileName: Text; var IsHandled: Boolean)
    var
     
    begin
        //Code Removed
        IsHandled := true;
    end;

}

**Comment by blrobl** [comment]
Hi, I can only seem to reproduce this after downloading the symbols on an extension that depends on OIOUBL, but the error disappears once I reload the window - is this your case? Otherwise, could you give more information about your setup and dependencies for us to try to reproduce it? Thanks.

**Comment by blrobl** [comment]
- [ ]
