### ISSUE TITLE
Allow Extension Target Level?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#734]
What are the difference between the **Allow Extension Target Levels** _Personalization_, _Extension_, _Solution_ and _Internal_ in the Service Tier Administration under the FastTab Development?

**Comment by HunterFeltman-MSFT** [comment]
In Extensions 2.0, we have added a concept of 'levels' of extensions that are used to determine different classifications and capabilities of an extension package. 
In VSCode development, this is something you can specify in the app.json file using the "target" property. This places a restriction on what is 'allowed' within the extension.

On the server side, you are given the ability to set the 'level' of 2.0 extensions that you want to allow to be publishable/installable. This gives admins control over what kinds of extension they want to have on their systems.

In order the 'level' progress as follows:
1. Personalization  
    - Lowest current level, only allows for inclusion of UI objects like Profiles/PageCustomizations

2. Extension
    - Default level, allows for all of the capabilities you would currently expect from an extension

3. Solution
    - Unused at the moment, this (or something very like it) will be used to encompass the capabilities of 'Embed' apps in the future.

4. Internal
    - Highest level, currently only for internal use

**Comment by DanielGoehler** [comment]
Thanks
