### ISSUE TITLE
Error: The project contains errors when downloading symbols

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#7342]
**1. Describe the bug**
With the current version of AL, it is not possible to Download Symbols, if the symbols are not already in the .alpackages folder.

**2. To Reproduce**
1. Open a AL project, with 1 or more dependencies (.alpackages folder empty)
2. app.json will show a error, because the dependencies could not be found in the package cache folder (.alpackages)
3. Run "Download Symbols"
4. "Error: The project contains errors." will be shown in the output

**3. Expected behavior**
Download Symbols

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/43037258/223826910-4d27d215-ec1d-469e-bf17-0319521539b8.png)
And a error message "Error: The project contains errors." in the output window.

If I downgrade to the previous release 10.5.760365 it works perfectly fine.

**5. Versions:**

- AL Language: 10.5.765371
- Visual Studio Code: 1.76.0
- List of Visual Studio Code extensions that you have installed:
AZ AL Dev Tools/AL Code Outline

**Comment by qutreson** [comment]
@DominicSaladin - Can you reproduce this issue with the latest AL extension in the VS Code marketplace (version 11.*) ?

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
