### ISSUE TITLE
Supported debugger 6.0 not available!!!

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/AL#7347]
Please include the following with each issue:

**1. Describe the bug**
Can't publish to local docker container with latest version of visual studio.  

**2. To Reproduce**
Install Visual Studio
Install the latest Visual Studio Code VSIX file which is in Docker Container
Press Ctrl + F5 to publish

<img width="725" alt="image" src="https://user-images.githubusercontent.com/28625572/225397632-8b87f0d9-4c3d-4219-98f2-978821917470.png">

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Expect to be able to publish against docker V22 container

**4. Actual behavior**
Error message occurs. Looks like debugger versions don't match.
<img width="725" alt="image" src="https://user-images.githubusercontent.com/28625572/225398204-94abe957-b7bf-4417-b825-1fca8f7b4b90.png">

**5. Versions:**

- AL Language: en-US
- Visual Studio Code:
- 
![image](https://user-images.githubusercontent.com/28625572/225399396-639af35f-d8ea-4fec-b9c2-f683cf5b3055.png)

- Business Central: v. 22.0.54348.0
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Can you give us the version of the VSIX you have installed?

**Comment by AmandaTest** [comment]
VSIX version is the one that was delivered with the latest insider build for business central version 22. I picked it up yesterday.  I don't see a version on it.

**Comment by AmandaTest** [comment]
@thloke Any news on this?

**Comment by SShadowS** [comment]
Same issue here. Any updates?

**Comment by thloke** [comment]
We're looking into this now.

**Comment by DWDBE** [comment]
I have the same issue. AL version is: AL Language extension for Microsoft Dynamics 365 Business Central  v11.0.763936

**Comment by thloke** [comment]
We've found the source of the issue, and @nndobrev is working on a fix

**Comment by thloke** [comment]
This should now be fixed in the latest docker insiders build.

**Comment by leegeurts** [comment]
> Thx, now it works :)

How did you get your artefacturl ? I cant seem to get it to work?

**Comment by bcarmo-dev** [comment]
It's also not working for me. When I download the latest docker insider build I get the vs code extension with version **v11.0.763936** and that doesn't work.

**Comment by thloke** [comment]
Which version of the artifacats are you requesting? Can you try getting the public preview?

`get-bcartifacturl -select Latest -country us -storageAccount bcpublicpreview`

**Comment by DWDBE** [comment]
I have recreated the docker image using this artifact url:
$artifactUrl = Get-BcArtifactUrl -type sandbox -country base -select 'latest' -storageAccount BcPublicPreview
and then downloaded a new VSIX with AL version of: **v11.0.771299**

**Comment by AmandaTest** [comment]
> This should now be fixed in the latest docker insiders build.

Thank you.

**Comment by bcarmo-dev** [comment]
> Which version of the artifacts are you requesting? Can you try getting the public preview?
> 
> `get-bcartifacturl -select Latest -country us -storageAccount bcpublicpreview`

Indeed this now works.
I was using the bcsinder and there it's not fixed yet.

Thanks

**Comment by AmandaTest** [comment]
Yes. The public preview version is working for me.

Best Regards,
Amanda Snow

On Mar 22, 2023, at 7:38 AM, bcarmo-dev ***@***.***> wrote:

﻿

Which version of the artifacts are you requesting? Can you try getting the public preview?

get-bcartifacturl -select Latest -country us -storageAccount bcpublicpreview

Indeed this now works.
I was using the bcsinder and there it's not fixed yet.

Thanks

**Comment by AmandaTest** [comment]
This one works for me.

Best Regards,
Amanda Snow

On Mar 22, 2023, at 5:55 AM, Thaddeus Loke ***@***.***> wrote:

﻿

Which version of the artifacts are you requesting? Can you try getting the public preview?

get-bcartifacturl -select Latest -country us -storageAccount bcpublicpreview
