### ISSUE TITLE
.env inside AL code.

### ISSUE THREAD

**Issue by joshuahiwat** [microsoft/AL#7350]
Hi All,

I'm a php developer and currently learning a lot of AL code.

I want to keep my code clean and readable for others who are working on it in the future. Some of those things are the environment variables. Why is there no option to create a kind of .env file or something where you can place your important information, like API keys or slugs. 

I know there is a isolated storage, but that is not what I mean. 

Any ideas or did I take a look at the wrong place?

_Originally posted by @joshuahiwat in https://github.com/microsoft/alguidelines/discussions/221_

**Comment by thloke** [comment]
Thanks for the suggestion. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
