### ISSUE TITLE
CodeCop AL0378 is missing for OnBeforeAction/OnAfterAction of PageExtension in RoleCenter

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7352]
**1. Describe the bug**
CodeCop **AL0378** isn't triggerd on page Extensions for the OnBeforeAction and OnAfterAction Trigger
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al378

**2. To Reproduce**
``` AL
pageextension 50000 "PTE Acc. Receivables Adm. RC" extends "Acc. Receivables Adm. RC"
{
    actions
    {
        modify("Combine Shi&pments")
        {
            trigger OnBeforeAction() //Missing Warning
            begin

            end;
            trigger OnAfterAction()//Missing Warning
            begin

            end;
        }
    }
}
```
**3. Expected behavior**
We should receive the same warning as for other triggers.

**4. Actual behavior**
Right now we receive no warning

**5. Versions:**

- AL Language: 10.5.765371

**Comment by thloke** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!
