### ISSUE TITLE
[AL0122] and [AL0133] - Dictionary in Variants

### ISSUE THREAD

**Issue by PiGlic** [microsoft/AL#7360]
**1. Describe the bug**
It is possible to assign a dictionary to a variant, but it is not possible to assign the variant to a dictionary afterwards.

**2. To Reproduce**
Example code:
    
```
local procedure TestDictionary()
    var
        VariantBuffer: Variant;
        IntDictionary: Dictionary of [Integer, Integer];

    begin
        IntDictionary.Add(1, 2);
        IntDictionary.Add(3, 6);

        VariantBuffer := IntDictionary;

        IntDictionary := VariantBuffer; // [AL0122] Cannot implicitly convert type 'Variant' to 'Dictionary of [Integer, Integer]'
        Evaluate(IntDictionary, VariantBuffer); // Is compilable but crashes during execution
    end;
```

In reality I tried to enqueue a dictionary via the "Library - Variable Storage" (which worked).

When I tried to dequeue the dictionary, I found out that it is not possible to assign the dictionary from the variable.

 ```
   local procedure TestDictionary()
    var
        VariantBuffer: Variant;
        IntDictionary: Dictionary of [Integer, Integer];
        LibraryVariableStorage: Codeunit "Library - Variable Storage";
    begin
        IntDictionary.Add(1, 2);
        IntDictionary.Add(3, 6);

        VariantBuffer := IntDictionary;

        LibraryVariableStorage.Enqueue(IntDictionary);
        LibraryVariableStorage.Dequeue(IntDictionary); //[AL0133] Argument 1: cannot convert from 'Dictionary of [Integer, Integer]' to 'var Variant' 
    end;
```

**3. Expected behavior**
If it is possible to assign a Dictornary to a Variant, there should be at least one way to write this information back to the Dictornary.

**5. Versions:**

- AL Language: v11.0.771299
- Visual Studio Code: 1.77.0
-

**Comment by dzzzb** [comment]
I'm not sure that's correct, nor that `Evaluate()` can help much... By my reading, the problem is here:

```al
       VariantBuffer := IntDictionary;
       LibraryVariableStorage.Enqueue(IntDictionary);
       LibraryVariableStorage.Dequeue(IntDictionary);
       //[AL0133] Argument 1: cannot convert from 'Dictionary of [Integer, Integer]' to 'var Variant' 
   end;
```

This is a standard error when dealing with `Variant`s, and it's because they are not automatically 'un/boxed' to the 'real' contained type.

What if you just do this?

```al
       VariantBuffer := IntDictionary;
       LibraryVariableStorage.Enqueue(IntDictionary);
       LibraryVariableStorage.Dequeue(VariantBuffer);
       IntDictionary := VariantBuffer;
```

That is: pass `Dequeue()` the `var Variant` it insists upon, then assign that to the concrete `Dictionary` type. I would expect this to work... but I can't test it.
