### ISSUE TITLE
Folding of regions does no longer work

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7361]
Please include the following with each issue:

**1. Describe the bug**
Before v11.0 we were able to fold regions using the Ctrl+K + ! / Ctrl+K + J shortcuts. 
Since v11.0 this does no longer work on various objects.

Might be related to #6530 

**2. To Reproduce**

v11.0 behavior

![110bis](https://user-images.githubusercontent.com/25268332/230007305-e88fa8b3-831f-4831-a2f2-c92ff961d000.gif)

**3. Expected behavior**

Same as in v10.5

![105](https://user-images.githubusercontent.com/25268332/230006375-c2eb815f-c710-4aa3-91aa-6d0436dbc3f4.gif)

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:  **11.0.779295**
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

**Comment by salgiza** [comment]
FWIW: I saw something peculiar in the gif and just confirmed it: the bug is triggered by placing the _region_ tag between the procedure comments and the procedure definition.

**Comment by fvet** [comment]
@thpeder Wanted to provide some additional feedback on folding related regressions since runtime 11:

- I have various scenarios where I get none or invalid fold/unfold behavior upon opening a new file. '**Reload window**' (it became our most favorite shortcut ... :( ) seems to fix the issue most of the times, but is decreasing productivity.
- Same occurs when adding new functions combined with regions. They do only show up on '**reload window**'.

![regions fold unfold](https://github.com/microsoft/AL/assets/25268332/df1cbd5f-5196-42c2-8d4f-b9cc5cab4cc9)

- When creating procedures with the `#region` tag put between the procedure documentation and the procedure declaration (cfr. comment from @salgiza), the compiler (after reload window) seems to be able to deal with this (as it was before runtime 11)

- I've not found any info or received feedback from the development team (@blrobl ) on which improvements have been made on folding/unfolding of regions, combined with **pre-compiler directives** as mentioned here: https://github.com/microsoft/AL/issues/6530#issuecomment-1348155979 

I've tried various scenarios with code containing `#pragma warning` code lines, but they still interfere with / prevent a neat fold/unfold experience.

```
Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.810452
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.11340.0 and VS Code Extension Version 12.0.827331. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
