### ISSUE TITLE
Page field intellisense without Rec.

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#7366]
- AL Extension Version:  11.0.779295

When I add a new field to page, I use the intellisense to search the field.
![image](https://user-images.githubusercontent.com/47736215/231067064-5d147623-b1bc-4145-9454-088e29627f6b.png)
The intellisense add the field, but without rec in front of the expression.
![image](https://user-images.githubusercontent.com/47736215/231067163-e7bb5700-7537-4fd6-9d73-0f74180dc787.png)
This leads to a warning since a few years, so I still have to add the rec for each field. Is it possible to adjust that?
![image](https://user-images.githubusercontent.com/47736215/231067602-733f755e-8b6c-4df3-8c51-995a459eb8f3.png)

**Comment by deadmouse** [comment]
Add this in your app.json:

```
"features": [
    "NoImplicitWith"
]
```

**Comment by FSchneiderYav** [comment]
Thank you, that's perfekt.
