### ISSUE TITLE
Possible bug in Codeunit 99000854 "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#7368]
Please include the following with each issue:

**1. Describe the bug**
Based on step-by-step debugging calculating Requisition Worksheet for Item doesn't seem to match supply and demand correctly. Might be a missing setfilter-call in code (below).

![image](https://user-images.githubusercontent.com/35798628/231142966-26ec6325-e701-4cfd-9060-b29f1cc96993.png)

As far as I can tell, the same filter should be set both for Supply and Demand.

**Comment by pri-kise** [comment]
This is the wrong repository for such bugs.
If a customer is impact, then please contact the microsoft suppoer via the common channels.

If you only want to report this possible bug, then share it via yammer or other community channels.

**Comment by kalberes** [comment]
As mentioned above.
