### ISSUE TITLE
[AL  Explorer] Can not open objects with slash in object name

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7369]
Please include the following with each issue:

**1. Describe the bug**
You can not open a object if the object name contains a "/" (slash)

**2. To Reproduce**
- Open the AL explorer 
- Search for "sales-quote to". 
- Try to open
  - ``Sales-Quote to Order`` --> works
  - ``Sales-Quote to Order (Yes/No)`` **--> does not work**

Tested it with different object types. 

**3. Expected behavior**
It should be the openable for all of them, regardless of whether there is a slash in the name.

**4. Actual behavior**
Objects without slash in the name can be opened.
Objects with slash in the name can not be opened.

**5. Versions:**

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.779295
Publisher: Microsoft

**Comment by MarjanChabukovski** [comment]
Objects with a slash in the name can be opened now with AL Language version 11.0.787898 but their content doesn't show when you're debugging.

**Comment by ChrSt89** [comment]
I have the same problem. Opening works, but no content is displayed when debugging. Is there a solution?

**Comment by Lumberer** [comment]
Hi, I have the same problem. I have a feeling it's also the reason why the debugger does not break on these objects. Other objects work fine. Is there a solution or workaround?

**Comment by minaskats** [comment]
+1

**Comment by DanielGoehler** [comment]
+1

**Comment by pri-kise** [comment]
Someone suggested on yammer the following: 

In the previous version of the AL Language extension (v10.x), the debugger displayed numbers in the file name when it downloads/generates the .DAL file. With v11 it's using the actual object names which seems to be the cause of the issue. Can't the v10 functionality be enabled to use numbers as a fallback until the issue in Visual Studio Code is fixed?
