### ISSUE TITLE
usePublicURLFromServer ignores port from launch.json/workspace

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7373]
**1. Describe the bug**
For developing BC some developers use a shared docker server for developing. The network is internal and so we are using http instead of https. 
With the new setting ``usePublicURLFromServer : false`` it is using the url from the launch json, but it still keeps adding the https port 443.

**2. To Reproduce**

Add ``usePublicURLFromServer : false`` to launch.json/workspace
Add ``url: "http://dockerserver123/"`` to launch.json/workspace
Add ``port: 80`` to launch.json/workspace
Add ``instance: "BC"``
Start debugging or publish so a new browser window/tab opens

We also tried  ``url: "http://dockerserver123:80/"``. Doesn't work either.

**3. Expected behavior**
It should open a browser window/tab with ``http://dockerserver123/BC/[...]``
Or at least ``http://dockerserver123:80/BC/[...]``

**4. Actual behavior**
It opens a browser window/tab with ``http://dockerserver123:443/BC/[..]``

**5. Versions:**

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.779295
Publisher: Microsoft

**Comment by BazookaMusic** [comment]
This is a known issue that will be fixed in one of the next releases.

**Comment by BazookaMusic** [comment]
This will be added in the next release of our VSIX. Check it out when it is released and re-open if you still experience the issue.
