### ISSUE TITLE
Added field "Search Name" in fieldgroups for Vendor and Customer table is not shown in DropDown

### ISSUE THREAD

**Issue by KingMO90** [microsoft/AL#7374]
If I add the field "Search Name" in the Vendor or Customer table in the DropDown Fieldgroup, the field is not shown in webclient.
Is there an explanation for this or is this a bug?

```
tableextension 50000 "Vendor +" extends Vendor
{
...
    fieldgroups
    {
        addlast(DropDown; "Search Name") { }
    }
...
}
```

Some colleagues have looked at my code, so I don't suspect a formal error. 
Also other fields instead of "Search Name" were displayed in the dropdown.

**Comment by Plowmage** [comment]
This seems to be related to the LookupPageID page, that is defined on the vendor/customer table. 

If you add a field to the fieldgroup, and that field is set to Visible = false, on the lookup page, then it wont be shown in the dropdown. 

So you would probably need to pageext "Customer Lookup", and modify the "Search Name" field to be visible = true.

**Comment by KingMO90** [comment]
Thanks a lot.. Never thought this might be the problem 👍
