### ISSUE TITLE
Query Method Count data type None instead of Integer

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#7375]
**Query Method Count data type None instead of Integer**

Query Method Count has data type None instead of Integer, making is impossible to work with, blocking compilation

**REPRO**

Define Query with Count column:

```AL
query 81000 "M365 Number Of Items"
{
    Caption = 'Mumber of Items';
    QueryType = Normal;

    elements
    {
        dataitem(Item; Item)
        {
            column(No; "No.")
            {
            }

            column(Count)
            {
                Method = Count;
            }
        }
    }
}
```
Use the query and column Count:

```AL
codeunit 81000 "M365 No External Changes"
{
    internal procedure HasRecords(): Boolean
    var
        q: Query "M365 Number Of Items";
    begin
        q.Open();
        q.Read();

        exit(q.Count > 0);
    end;
}
```

**Expected behavior**

The expectation is that it works like before and Count returns an Integer.

**Actual behavior**

ERROR:
```json
[{
	"resource": "/C:/Dev/AL/_Playground/MicrosoftIssues/app/src/codeunit/NoExternalChanges.Codeunit.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "AL0175",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al175",
			"path": "/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al175",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 8,
	"message": "Operator '>' cannot be applied to operands of type 'None' and 'Integer'",
	"source": "AL",
	"startLineNumber": 10,
	"startColumn": 14,
	"endLineNumber": 10,
	"endColumn": 25
}]
```

**Versions**

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.779295
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

Version: 1.77.3 (system setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

All installable extensions were disabled.
This stops us from developing several projects.

**Comment by MODUSCarstenScholling** [comment]
Thank you, I'm not searching for closed issues while they are still occuring...

**Comment by NKarolak** [comment]
Unfortunately, you should. The way Microsoft handles Issues here is a bit... unpractical.
