### ISSUE TITLE
Never ending Loading Workspace in VSC

### ISSUE THREAD

**Issue by dvanes67** [microsoft/AL#7378]
When opening a workspace with 29 projects I keep getting stuck with a 'loading workspace' notification popup in the bottom left of the screen. It never finishes the task. Canceling it results in not having intellisence.

Restarting VSC, reload windows, uninstalling the al extension and installing it again, nothing works.

When I checked the runtime status of the al Language extension I see this:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/57436337/233320074-efad87da-6e7e-4b8a-85f3-a8fa75b0488f.png">

and after a long search I found a trailing comma in an app.json file at the end of the depencies declaration.

I think it should be possible to catch this and be more specific in the the error message, and to make it pop up instead of hiding it.

**Comment by qutreson** [comment]
Same as for #7287, we have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Our suggested workaround for now is to reload the window if there was a problem loading the app.json.

**Comment by jmux** [comment]
Fresh install. I haven't seen anything from this application yet OTHER than 'loading workspaces'.
