### ISSUE TITLE
Chosen debug configuration has an unsupported attribute value `request`: 'publish'.

### ISSUE THREAD

**Issue by pzentner** [Microsoft/AL#738]
I just tried to debug an extension I just created and am getting above error message with the option to open launch.json. However, there is nothing other than "publish" as an valid option.

AL: version 0.10.12859
VS Code just wanted to be updated, version: 1.17.0

It successfully creates the package, but then doesn't publish it to the server.

My repro steps are: 
AL:Go! to create new extension
Update launch.json with server info 
try Crtl+F5 or F5 

-> Error message from title after creating the package.

Is this something on my end?

**Comment by pzentner** [comment]
I just confirmed that it works with VSC 1.16.1, but not with VSC 1.17.0. I downgraded VSC with choco to test it out and can publish extensions without a problem.

**Comment by yrest** [comment]
According to Freddy they are working on it. [https://github.com/Microsoft/nav-docker/issues/55](https://github.com/Microsoft/nav-docker/issues/55)

**Comment by StanislawStempin** [comment]
Just change 'publish' to 'launch'. We will have all the samples and auto-generated templates updated for October Update.

**Comment by pzentner** [comment]
Tried to do that before I opened it, but then it complained that it's not a valid option. I guess, i actually should have tried to execute it - it works with launch. Thank you
