### ISSUE TITLE
Debugging the Base app showing "No content available" message for some objects 

### ISSUE THREAD

**Issue by MarjanChabukovski** [microsoft/AL#7383]
Please include the following with each issue:

**1. Describe the bug**
debugging the base Business Central application, I noticed that the contents of various objects, eg report 7323 in Create Invt Put-away/Pick/Mvmt, are hidden. While stepping into the object instead of showing the code, it opens a file named Mvmt.dal which displays "No content available" message. 

I'm trying to create an inventory pick from a PO. I can see the code for page 50 and table 38 but when it gets to the report it seems like it's not allowed to be read. 

Lots of other people experienced the same issue. See the comments from April this year on this community link: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-ready-to-go#developing-for-business-central-in-general

![No content available](https://user-images.githubusercontent.com/131866000/234544527-48d9b32e-f805-4761-b7c6-5de4ea8022d0.PNG)

**2. To Reproduce**

set a breakpoint on action("Create Inventor&y Put-away/Pick") on Page 50 and breakpoints in report 7323 and try to create a pick 

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

expecting to be able to view all code from report 7323 

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: 11.0.787898
- Visual Studio Code: Version: 1.77.3 (user setup)
- Business Central: 21.5.53619.53813
- List of Visual Studio Code extensions that you have installed: What's the easiest way to get this list? it will take me all day to type them all up. 

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by FBakkensen** [comment]
I am experiencing the exact same problem when trying to debug page 408.

As an additional information I have the same problem when trying to view the source code from the new AL Explorer in VS Code for page 408 og report 7323, while it works fine for other objects.

**Comment by PooyaKharamesh** [comment]
This issue misses the information mentioned in the template. To help us get to the issues faster you must provide all the information in the template. 

Please provide the following info
AL Extension version
Server extension version

**Comment by FBakkensen** [comment]
AL Extension: 11.0.787898
Server: BC Saas Sandbox 22.0.54157.54644

**Comment by MarjanChabukovski** [comment]
> This issue misses the information mentioned in the template. To help us get to the issues faster you must provide all the information in the template.
> 
> Please provide the following info AL Extension version Server extension version

AL Extension: 11.0.787898
Server: BC Saas Sandbox 21.5.53619.53813

**Comment by fvet** [comment]
![image](https://user-images.githubusercontent.com/25268332/234838588-7c68ea11-a707-4fbd-82df-7ae3992b0321.png)

**Comment by MarjanChabukovski** [comment]
> It seems to be related to **slashes** included in the object name, at least that's my guess ...
> 
> ![image](https://user-images.githubusercontent.com/25268332/234838588-7c68ea11-a707-4fbd-82df-7ae3992b0321.png)

Who's going to fix it I wonder? I logged a case with Microsoft and they referred me here :)

**Comment by MarjanChabukovski** [comment]
I was debugging OnPrem BC ver 19 today and I got the same issue so the BC version is not the culprit here.  It seems that @fvet was right. I'm getting No content avail for any objects with / in their name.   AL Extension is 11.0.787898 and VSC is 1.77.0

**Comment by NKarolak** [comment]
> It seems to be related to **slashes** included in the object name, at least that's my guess ...
> 
> ![image](https://user-images.githubusercontent.com/25268332/234838588-7c68ea11-a707-4fbd-82df-7ae3992b0321.png)

Then this is related, it seems
https://github.com/microsoft/AL/issues/7369

**Comment by thloke** [comment]
This is actually something on the VSCode side. I've raised the issue with them, but I'll ping them again.

https://github.com/microsoft/vscode/issues/172108

**Comment by minaskats** [comment]
This is still an issue also for "Inventory Posting To G/L" and the report 1002 "Post Inventory Cost to G/L".
