### ISSUE TITLE
Remove Enum and set field to removed

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#7387]
Hello,

I have to remove an obsolete enum from our app. The enum is used in a table and the field is set to Obsolete = Pending. When I remove the obsolete enum. An error is shown for the table field. But I cant set the enum to Obsolete = Removed. What is se right way to set this constellation removed

```
enum 50100 "SI Perf Resp Type" implements "SI Performance Response Type"
{
    Caption = 'Performance Response Type';
    ObsoleteReason = 'Replaced by SI Perfo Resp Type';
    ObsoleteState = Pending;
    ObsoleteTag = '5.5';

    value(1; Booking)
    {
        Caption = 'Consumption';
        Implementation = "SI Performance Response Type" = "SI Perf. Booking Mgt";
    }
    value(2; Order)
    {
        Caption = 'Order';
        Implementation = "SI Performance Response Type" = " SI Perf. Order Mgt";
    }
}
```
```
        field(15; "Performance Response Type"; Enum "SI Perf Resp Type")
        {
            Caption = 'Performance Response Type';
            DataClassification = CustomerContent;
            ObsoleteReason = 'Replaced by field Performance Resp Type';
            ObsoleteState = Pending;
            ObsoleteTag = '5.5';
        }
```

**Comment by thloke** [comment]
Unfortunately there's no way at the moment to remove the enum. You'll have to keep it around until we either allow for:

1. Actual removal of table fields
2. A non-breaking way to change the type of the field (probably to Option)

But none of these are on the horizon for the moment, so the current situation means that you can't remove the enum completely.

**Comment by LFlamme** [comment]
Any Update or Plans on this? This can be very bad if you remove an enum in one App that was used in an obsolete field in a dependency. You wont be able to remove the field so you have to reimplement the enum?

**Comment by thloke** [comment]
No, there currently aren't any plans for this. The best way to get traction on this would be to raise it on BCIdeas so we can get a better idea of the community need for this.

**Comment by SchulzOli** [comment]
@thloke hI,
would like to ask again. Is there any update on this? 
Might be this Idea, right?
https://experience.dynamics.com/ideas/idea/?ideaid=3dce6c07-e0b9-ee11-92bd-000d3ae311ab
