### ISSUE TITLE
Transfering Files from and to Azure Functions 

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#739]
I read a lot about DotNet is not going to be enabled in a SaaS-Environment and the alternative should be Azure Functions.

As  I would like to implement a FTP Client with Download and Upload, as an example (#725). I have a lot other file based examples in the back of my head, which could be implement the same way and I alos know how to implement an FTP Client in Azure Functions.

From that GetAddressService-Example (https://github.com/Microsoft/AL/blob/master/samples/GetAddressService/Codeunits/AddressService.al) I also know how to communicate with a Azure Function App I created and I also know how to Process a Json Result. 

However, is there any way you could provide me some hints how to Create Json Object for more than one parameter for FTP Server Credentials and how to transfer files from or to Azure Functions?

**Comment by StanislawStempin** [comment]
See if this blog post answers your question:
http://www.kauffmann.nl/2017/07/18/al-web-service-examples/

**Comment by DanielGoehler** [comment]
The downloading files part is pretty good described that blog article. 

What still not understand is how to upload a file from an extension. In that article only parameter are used to call that web services:
![bulksmsalcodesnippet](https://user-images.githubusercontent.com/9556549/31430069-0e73a224-ae70-11e7-8828-158e4011df3b.jpg)

**Comment by DanielGoehler** [comment]
Up- and Downloading Files to and from Azure Functions was pretty good show by @vjekob on NAV TechDay 2017 [Azure Functions Deep Dive](https://www.youtube.com/watch?v=f10lFZtUWGE)
