### ISSUE TITLE
Certain expressions in RDLC layouts will cause that layout to fail validation in v22

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/AL#7390]
**1. Describe the bug**
Validating a RDLC layout fails with an error when it contains an expression in that layout which contains linebreaks. 

_Error message;_
The value expression for '=Cstr(Fields!Number1.Value) + Chr(177) + Cstr(Fields!Number2.Value) + Chr(177) + Cstr(Fields!Number3.Value) + Chr(177) +Cstr(Fields!Number4.Value) + Chr(177) +Cstr(Fields!Number5.Value) + Chr(177) +Cstr(Fields!Number6.Value) + Chr(177) +Cstr(Fields!Number7.Value) + Chr(177) +Cstr(Fields!Number8.Value) + Chr(177) +Cstr(Fiel
ds!Number9.Value) + Chr(177) + Cstr(Fields!Number10.Value)' contains an error. 'ds' is not defined.

AL call stack: 
"Report Layouts Impl."(CodeUnit 9660).InsertNewLayout line 80 - _Exclude_ReportLayouts by Microsoft
"Report Layouts Impl."(CodeUnit 9660).CreateNewReportLayout line 20 - _Exclude_ReportLayouts by Microsoft
"Report Layouts"(Page 9660)."NewLayout - OnAction"(Trigger) line 5 - _Exclude_ReportLayouts by Microsoft

**2. To Reproduce**
1. Use Report and layout from; [Report.zip](https://github.com/microsoft/AL/files/11404897/Report.zip)
2. Publish to environment.
3. Go to _Report Layouts_ and find report (50100). 
![image](https://user-images.githubusercontent.com/85683700/236422890-77f5efe1-8ff4-4a80-989f-80f41ec5ab57.png)
4. Use action _Export Layout_ to save the layout of report.
5. Use action _New Layout_ to create a new RDLC layout for the same report. 
![image](https://user-images.githubusercontent.com/85683700/236423519-cbc68772-b190-4525-87b8-1aa8f739e485.png)
6. Drag and drop layout file exported in step 4.
7. Errormessage like at top appears.

**3. Expected behavior**
Validation of RDLC report layout behaves as before. For example scenario exactly as above is accepted in v21; 
![image](https://user-images.githubusercontent.com/85683700/236425034-0b49654e-5683-44e8-8466-80675b9e8dd5.png)

**4. Actual behavior**
1. Error is caused by how any linebreaks present in an expression are interpreted. These linebreaks are common in certain document reports using the GetData and SetData patterns.
  a. Error 
![image](https://user-images.githubusercontent.com/85683700/236427264-c8623afc-5613-4e2e-b614-62410588e9f8.png)
b. No error 
![image](https://user-images.githubusercontent.com/85683700/236427495-e7dfba44-dca2-4bc7-970f-74610bf2c3b9.png) 
2. Although a fix/workaround is present, checking and correcting all our RDLC layouts would be very unwanted action. Also we cannot influence the custom report layouts present at customers.
3. Publishing and running of the report does not seem to be impacted by this issue.

**5. Versions:**
- AL Language: v11.0.787898
- Visual Studio Code: 1.78.0
- Business Central: NL Business Central 22.0 (Platform 22.0.55180.0 + Application 22.2306.10112.0)
- List of Visual Studio Code extensions that you have installed: AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This is out of scope because the rdlc validation is handled by the runtime, and not by the VSCode plugin.
