### ISSUE TITLE
launch.json issues (intelisence & Add configuration button)

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#7391]
**1. Describe the bug**
Since the last vsCode update:
* In the launch.json the Intellisense in the option value does not show possible values.
* The "add configuration" does not show AL configuration shortcut anymore.

**2. To Reproduce**
Just create a new AL project and try to change the launch.json file

**3. Expected behavior**
Like previously, get intellisence for options and configuration shortcuts.

**4. Actual behavior**
no more intellisence and configuration shortcuts.

**5. Versions:**
- AL Language: v11.0.787898
- VS Code: v1.78.0

**Comment by dannoe** [comment]
Looks like a vscode bug, see: https://github.com/microsoft/vscode/issues/181615

**Comment by thloke** [comment]
As mentioned, this is a bug in VSCode.
