### ISSUE TITLE
Credential cache is always lost on AL language extension update

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7394]
**1. Describe the bug**
Whenever the AL Language extension is updated, the credential cache is lost. This forces me to re-authenticate to all servers / tenants that I have used before. While this is technically not a problem, it is a nuisance that makes no sense.
There are two main reasons for this:
1. The encrypted credential/token cache is stored in the same folder as the binaries that are running the AL language extension.
2. The folder and filename are part of the encryption key that are used to de-/encrypt the file. This means updating the extension (and therefore the folder) would render the file unreadable anyways.

**2. To Reproduce**
Update the language extension and the token cache will disappear.

**3. Expected behavior**
The files where the credentials are cached could easily be in a more "persistent" location like `%localappdata%` or `%userprofile%` or something of the sort. The encryption key would also have to change of course, but that does not really change anything. This would decouple it from the language extension version and executable.

**4. Actual behavior**
Installing a new version of the AL Language extension comes with no cache and therefore all credentials are lost.

**5. Versions:**

- AL Language: 11.0.787898
- Visual Studio Code: 1.77.3

**Comment by DynaExperts** [comment]
Rhe same behavior is there after I update my language extension to 12

**Comment by PooyaKharamesh** [comment]
This is probably a design decision on VS code; We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
