### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by Niebling83** [microsoft/AL#7395]
I have an extension that has been running for a year on SaaS, but after upgrading to ver 22 this error appears
I have teste on different tenants with same result.
I have a sandbox still running 21.6 where it' srunning without problems. 

The SSL connection could not be established, see inner exception
![image](https://user-images.githubusercontent.com/45655373/236767999-e8e824cc-d87f-4654-bdfe-c9985a9d2853.png)

My code is :
RequestMessage.Method('POST');
RequestMessage.SetRequestUri(url);
XML_text := 'grant_type=client_credentials';
Content.WriteFrom(XML_text);
Content.GetHeaders(Headers);
Headers.Remove('Content-Type');
Headers.Add('Content-Type', 'application/x-www-form-urlencoded');
Client.DefaultRequestHeaders.Add('Authorization', 'Basic ' + Base64.ToBase64(NetradarSetup."User Name" + ':' + NetradarSetup.Password));
RequestMessage.Content := Content;
RequestMessage.GetHeaders(Headers);
Client.send(RequestMessage, ResponseMessage);

Complete Error message
The SSL connection could not be established, see inner exception.
Internt sessions-id: 
97073048-2544-420b-810c-08fddf6db20d
Sessions-id for Application Insights: 
d769e371-6f2a-4875-bd67-3aa906000c2d
Klientaktivitets-id: 
5dea1b3d-47ac-47b1-b098-1161535b0616
Tidsstempel ved fejl: 
2023-04-25T07:43:22.2608564Z
AL-kaldt stak: 
"BAL Netradar Management"(CodeUnit 95400).GetAccessToken line 41 - Netradar Prices by Aktieselskabet balance.as
"BAL Netradar Setup Card"(Page 95400)."TestConnection - OnAction"(Trigger) line 4 - Netradar Prices by Aktieselskabet balance.as

I don't get any response

Any suggestions?

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by kpipic** [comment]
Hello @Niebling83, 

do you have solution for this problem?

**Comment by Niebling83** [comment]
> Hello @Niebling83, 
> 
> do you have solution for this problem? 

Yes, Microsoft mad an hotfix for it

**Comment by kpipic** [comment]
> > Hello @Niebling83,
> > do you have solution for this problem?
> 
> Yes, Microsoft mad an hotfix for it

But, I have the same error in 22.3 version. 
What is the hotfix?

**Comment by Niebling83** [comment]
> > > Hello @Niebling83,
> > > do you have solution for this problem?
> > 
> > Yes, Microsoft mad an hotfix for it
> 
> But, I have the same error in 22.3 version. 
> What is the hotfix? 

Im running SaaS, but I think it was some ting about TLS, If uoy Are running onpren you have to raise TLS to ver 1.3

**Comment by kpipic** [comment]
> > > > Hello @Niebling83,
> > > > do you have solution for this problem?
> > > 
> > > 
> > > Yes, Microsoft mad an hotfix for it
> > 
> > 
> > But, I have the same error in 22.3 version.
> > What is the hotfix?
> 
> Im running SaaS, but I think it was some ting about TLS, If uoy Are running onpren you have to raise TLS to ver 1.3

I tried on sandbox 22.3 (saas version), and still getting this error.

**Comment by Niebling83** [comment]
> > > > > Hello @Niebling83,
> > > > > do you have solution for this problem?
> > > > 
> > > > 
> > > > Yes, Microsoft mad an hotfix for it
> > > 
> > > 
> > > But, I have the same error in 22.3 version.
> > > What is the hotfix?
> > 
> > Im running SaaS, but I think it was some ting about TLS, If uoy Are running onpren you have to raise TLS to ver 1.3
> 
> I tried on sandbox 22.3 (saas version), and still getting this error. 

Hi.
Then i have No idea, we reportere it to Microsoft as a terror and Then the made a hotfix. Try to report it to MS
