### ISSUE TITLE
"Multiple page customizations have been specified for the same page"

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7396]
**1. Describe the bug**
AL language does not allow m eto defined multiple page customizations for the same page

**2. To Reproduce**
1. Create pagecustomization1 for Customer Ledger entries page
2. Create pagecustommization2 for Customer Ledger entries page
3. Create new profile and assign both newly defined customizations to it

**3. Expected behavior**
As a deveoper I expect to create small/reusable page customizations objects that could be used with multiple profiles. For e.g. i have one custmoization which adds additional Views for Customer Ledger Entries page. I would like to use this customization with all my profiles. Then, I would define additional page customization objects, which defines column order, per each profile. 

**4. Actual behavior**
System prevents me assigning multiple page customzations for a profile, if those target the same page.

**5. Versions:**
- AL Language: v11.0.787898
- Visual Studio Code: 1.7.8
- Business Central:  22.0.55180.0 

6. Sceenshots
Customization no1 - adding views
![image](https://user-images.githubusercontent.com/16342128/236838804-250ed0f6-c576-4bba-ba61-48608514c78f.png)
Customization no2 - changing column order
![image](https://user-images.githubusercontent.com/16342128/236838982-efa29b24-6f72-4496-95e9-4c2a10b92184.png)
Assigning customizations to the profile
![image](https://user-images.githubusercontent.com/16342128/236838712-4bbe2bf9-5c30-4592-a95e-789c3d70d38a.png)
Error
![image](https://user-images.githubusercontent.com/16342128/236839250-d4130337-f533-42a6-80fa-8109da27ec6d.png)

**Comment by thloke** [comment]
This is currently by design unfortunately. Adding this to BCIdeas would be the best thing. It looks like the small (gut feeling, I could be way off) sort of improvement that we'll pick up from there.

https://aka.ms/BusinessCentralideas
