### ISSUE TITLE
TempBlob.ToRecordRef not working

### ISSUE THREAD

**Issue by jordihayes** [microsoft/AL#7397]
Please include the following with each issue:

**1. Describe the bug**
TempBlob.ToRecordRef is not working as described in https://learn.microsoft.com/en-us/dynamics365/business-central/application/system-application/codeunit/system-application-codeunit-temp-blob

**2. To Reproduce**
Implement the sample procedure below...

`
    procedure Attachment_ImportAttachmentFromClientFile(var Attachment: record Attachment; var FileName: text)
    var
        FileMgt: Codeunit "File Management";
        TempBlob: codeunit "Temp Blob";
        AttachmentRecRef: RecordRef;
        FileDialogTxt: Label 'Attachments (%1)|%1', Comment = '%1=file types, such as *.txt or *.docx';
        FilterTxt: Label '*.jpg;*.jpeg;*.bmp;*.png;*.gif;*.tiff;*.tif;*.pdf;*.docx;*.doc;*.xlsx;*.xls;*.pptx;*.ppt;*.msg;*.xml;*.*', Locked = true;
        ImportTxt: Label 'Attach a document.';
    begin
        // *** IMPORT
        FileName := FileMgt.BLOBImportWithFilter(
            TempBlob, ImportTxt, FileName, StrSubstNo(FileDialogTxt, FilterTxt), FilterTxt);

        message('formaT(TempBlob.HasValue())-->' + formaT(TempBlob.HasValue()));
        message('format(TempBlob.Length()) --> ' + format(TempBlob.Length()));

        // *** COPY TO BLOB FIELD
        clear(Attachment);
        Attachment."Read Only" := true;
        Attachment."Storage Type" := Attachment."Storage Type"::Embedded;
        Attachment.insert(True);

        AttachmentRecRef.GetTable(Attachment);
        TempBlob.ToRecordRef(AttachmentRecRef, Attachment.fieldno("Attachment File"));
        Attachment."File Extension" := FileMgt.GetExtension(FileName);
        Attachment.modify;

        Attachment.CalcFields("Attachment File");
        message('format(attachment)-->' + format(attachment));
        message('format(attachment."Attachment File".HasValue-->' + format(attachment."Attachment File".HasValue));

        error('rollbackl!!!!');

    end;
`

**3. Expected behavior**
In // IMPORT, the MESSAGEBOX indicates that TempBlob has stored value from attachment. 

`
        message('formaT(TempBlob.HasValue())-->' + formaT(TempBlob.HasValue()));
        message('format(TempBlob.Length()) --> ' + format(TempBlob.Length()));
`

However, after TempBlob.ToRecordRef() is executed, when the field MESSAGEBOX indicates Attachment."Attachment File" has no values.
`
        message('format(attachment)-->' + format(attachment));
        message('format(attachment."Attachment File".HasValue-->' + format(attachment."Attachment File".HasValue));
`

**4. Actual behavior**
As mentioned in 3., Current behaviour is TempBlob.ToRecordRef is transferring blob values to the blob field.

COPYSTREAM still works. So BLOB values can still be copied via COPYSTREAM.

**5. Versions:**

- AL Language: 11.0.787898
- Visual Studio Code: 1.77.3
- Business Central: W1 22.0 (Platform 22.0.56306.0 + Application 22.0.54157.56364
- List of Visual Studio Code extensions that you have installed: AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue is to do with the runtime behaviour of recordrefs and tempblobs, so it needs to be looked at by the runtime team.
