### ISSUE TITLE
VS Code looses focus when Publishing

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7398]
**1. Describe the bug**
When publishing full dependency tree (Shift+Alt+W), you can use keyboard arrows to select server where to publish to. But, when you use regular Publish (Ctrl+F5), VSCode looses its focus and arrow keys no longer works for selecting server.

**2. To Reproduce**
1. Click Ctrl+F5 & wait till server selection showsup
2. Try to use keyboard arrows to select server

**3. Expected behavior**
I should be able to use keyboard arrows to select server where to publish solution to

**4. Actual behavior**
User must use mouse to select server where to publish solution to 

**5. Versions:**

AL Language: v11.0.787898
Visual Studio Code: 1.7.8
Business Central: 22.0.55180.0

**6. Screenshot**
![Animation](https://user-images.githubusercontent.com/16342128/237026447-42459265-3f1f-4e3e-ae5d-7bfa6c9ad1df.gif)

**Comment by gntpet** [comment]
Thanks @JMA1972  for the tip, 
I'm raising this an issue, since it this annoying issue and all AL developers are facing it daily.

**Comment by dannoe** [comment]
Temporary workaround: 

- Open the exentsion.js from C:\Users\<username>\.vscode\extensions\ms-dynamics-smb.al-<version> in any text editor
- Search for this: ``outputChannel.show()``
- replace it with this: ``outputChannel.show(true)``
- (Should be 7 occurrences in 11.7.863928)
- Reload/Reopen vscode 

The ``true`` will tell vscode to keep the previous focus on opening/displaying the "Output" tab.

(Keep in mind you have to do this every time the AL extension is updated or you switch between pre-release and normal version):

**Comment by JSebastianN** [comment]
This has been fixed in Version 12.0 yes?

I love it, you can now use the keyboard without TAB first, to select endpoint.
