### ISSUE TITLE
How to work with RDLC or Word Reports in VsCode?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#740]
I have transfered existing Reports to VsCode with **txt2al.exe**. 

When I change the DataSet in the .al-File, how is the connected .rdlc-File supposed to know about that change in the XML-DataSet? In addition, how do I edit exists Report Layouts or create new Reports?

**Comment by MrDavid5465** [comment]
I create a word document and link it like this
![image](https://user-images.githubusercontent.com/29601581/31278554-577c9724-aa73-11e7-8337-d4b88670742e.png)
Then i publish and go to Custom Report Layouts in dynamics, i create a new record
![image](https://user-images.githubusercontent.com/29601581/31278613-a3d59940-aa73-11e7-97fa-3a23da249be7.png)
Then I export the layout. It will download your original file with the data linked. Then once you are happy with the layout file, just overwrite your original layout in your project with the new one and republish.

If you change the dataset, you will have to repeat this process. ensure that you use a new custom report layout when you need to export a change as the Default layout file is linked to the record at the time of creation of the custom layout

http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/
