### ISSUE TITLE
[AL Home] BC developer news shows wrong fixed version number. Correct fixed version is 1.78.2

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/AL#7401]
Please include the following with each issue:

**1. Describe the bug**

The Business Central developer news entry "2023-05-09 AL debugger and snapshot capture doesn't work in Visual Studio Code v1.78" on the AL Home window shows the wrong version number 1.78.1:

![grafik](https://github.com/microsoft/AL/assets/25108568/8cae28bb-7738-4bf0-912c-a27ea43cfac2)

**2. Expected behavior**

It should say 1.78.2 as this is the version that will include the fix.

See: https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22April+2023+Recovery+2%22
or
https://github.com/microsoft/vscode/issues/181485#issuecomment-1540999881
![grafik](https://github.com/microsoft/AL/assets/25108568/882f9a0c-4bf8-40a6-9e43-335a8f162c49)

**Comment by esbenk** [comment]
News updated.
