### ISSUE TITLE
Runtime package with removed page does not install on BC22.0

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7405]
**1. Describe the bug**
I have an app that is some years old now. We have declared some pages as obsolete in version 17.0. Now we're starting to clean up those obsolete pieces and therefore I have removed some given page from the app. Being declared as obsolete, the AppSourceCop correctly accepts my change and does not detect it as a breaking change.

The build pipeline ran fine and produced a runtime package. However, I am unable to install this runtime package on service. The error I get is
````
The metadata object Page xxxx was not found for the compiler with emit version 22004.
      The application might be incompatible with the current compiler. Please unpublish the application that contains the application object Page xxxx and republish it.
      Or, run a technical upgrade of the application database with the 'Force' flag set.
````

**2. To Reproduce**
1. Create an app that has a page that is declared as `Obsolete` = **Pending**.
2. Build this as v1.0.0 and publish it to a first service (service A)
3. Create a runtime package from v1.0.0 and install it on a second service (service B)
4. Delete the page in the app and recompile it as v2.0.0
5. Publish v2.0.0 to service A
6. Create a new runtime package from v2.0.0
7. Install this runtime v2.0.0 to service B

**3. Expected behavior**
I expect the deployment to succeed, because the compilation has also succeeded.

**4. Actual behavior**
The deployment fails with the error message above.

**5. Versions:**

- AL Language: 11.0.787898
- Visual Studio Code: 1.77.3
- Business Central: platform 22.0.54512.0, application IT 22.0.54157.54635

**Comment by thloke** [comment]
I'm having trouble reproducing this. What I have done:

1. Create an app with a single page, mark it as obsolte pending
2. Publish v1 of that app to a local BC server
3. Create v2 of that app with the page deleted
4. Publish v2 of that app to a local BC server
5. Get runtime packages of both versions of the app
6. Publish/Sync/Install v1 of the app on a different BC server
7. Publish/Sync v2 of the app on the other sever as well
8. Uninstall v1 of the app
9. Upgrade the app to v2

All of the steps succeed for me unfortunately. Is there anything different from what you're doing?

**Comment by thloke** [comment]
Alternatively, can you check the windows event logs for the machine hosting the server where the runtime packages are being hosted on? They might contain a stacktrace that I can work from.

**Comment by hemisphera** [comment]
Unfortunately the stack trace on the event log from yesterday is gone. I am currently trying to reproduce it locally with the same packages that I was working with yesterday. It happened on one of our build machines. Not during build, but during deploy to a test service. It's pretty crowded there, so I don't have many details left.

I've just spun up a new fresh container and tried to replicate using the same identical runtime packages. The version that was installed to begin with (22.0.2), the version that broke installation (22.0.3) and the version that reverted my changes and then installed fine (22.0.4). Each one went up without problems.

I think I might have found something though. Let met test this through and I will get back to you.

**Comment by hemisphera** [comment]
OK. I have unveiled the arcane. This is a problem on my end and I just got confused by the new error message.

The cause was that on our test service there was a second app which contained a pageextension to the page that I have deleted. This causes my update to fail because - obviously - the base page disappeared.

I am closing this issue.
