### ISSUE TITLE
Issue with "Select All Rows" Functionality and Suggestion for Event Hook in Business Central

### ISSUE THREAD

**Issue by sharan-lal** [microsoft/AL#7407]
I encountered an issue in relation to the "Select All Rows" functionality and the absence of an event hook. When attempting to perform actions or calculations on multiple rows using the "Select All Rows" option, the functionality does not work as expected. It requires manual selection of rows instead.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/131354523/237047851-c77ce0d1-f7fd-4453-96e3-a85d9472af24.png">

There is also no event available to hook into for capturing the "Select All Rows" action which would be a useful addition to extend the functionality. 

Please consider addressing this issue and implementing an event hook for enhanced functionality.

Thank you
Sharan

**Comment by JMA1972** [comment]
What do you want to do with such an event? Just selecting rows from the user side without pressing an action button shouldn't lead to any computations.

**Comment by GaryFrostick2** [comment]
Example where this is needed would be something like an application screen. If you were selecting entries to apply you can show a running total of the selected amount to apply. This can be updated if an individual or multiple records are selected.  However no events are called if you use 'Select All'. Ideally using the select all should trigger the OnAfterGetCurrRecord event  to allow this sort of functionality, like selecting individual records triggers.

**Comment by thloke** [comment]
Thanks for the suggestion. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
