### ISSUE TITLE
ValidateTableRelation extensibility

### ISSUE THREAD

**Issue by STaillandier** [microsoft/AL#7410]
We can modify base application fields to add a tablerelation, that's ok
But we can't change ValidateTableRelation/TestTableRelation.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
