### ISSUE TITLE
Table field captions are generated even without GenerateCaptions flag

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/AL#7415]
**1. Describe the bug**
When field doesn't have caption specified it is still included into translation file even without GenerateCaptions flag. Problem was introduced with runtime 10.

**2. To Reproduce**

1. Create table extension:
```
tableextension 50000 TestCaption extends Item
{
    fields
    {
        field(50000; "Field without caption"; Boolean)
        {
        }
    }
}
```
2. Make app.json to have following setup:
  "runtime": "11.0",
  "features": [ "TranslationFile" ],

3. Compile project

**3. Expected behavior**
New field is not added to the generated translation file

**4. Actual behavior**
Following section is added to translation file:
```
        <trans-unit id="TableExtension 3171360700 - Field 1715668212 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Table 3276313895">
          <source>Field without caption</source>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">TableExtension TestCaption - Field Field without caption - Property Caption</note>
        </trans-unit>
```

**5. Versions:**
Runtime 11

**Comment by thpeder** [comment]
All table fields has a caption by default, and this has been the behavior since xliff translations was introduced.
