### ISSUE TITLE
No Purchase Orders were created

### ISSUE THREAD

**Issue by elhola** [microsoft/AL#7417]
Hi, 
When trying to create a Purchase Order on the Purchase Replenishment Journal page, an error occurs (No Purchase Orders were created), how to fix it?

**Comment by nndobrev** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
