### ISSUE TITLE
RDLC RunTime Bug  - "Native compiler return value: ‘[BC40000] 'RequestMinimum' is obsolete" - Microsoft.ReportingServices.RdlObjectModel.ExpressionParser.VBFunctions

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7420]
**1. Describe the bug**
When I copy tablix with some expressions in RDLC, then they get the full assembly path added in front of the function name

**2. To Reproduce**

1. Copy the Vat Clause Tablix of the Sales Invoice Header
The expression 
``` 
<FilterExpression>=Cstr(Len(Fields!Code_VATClauseLine.Value))</FilterExpression>
```
is converted to 

```
<FilterExpression>=Microsoft.ReportingServices.RdlObjectModel.ExpressionParser.VBFunctions.Cstr(Len(Fields!Code_VATClauseLine.Value))</FilterExpression>
```

**3. Expected behavior**
It shouldn't be a problem if the full path is used or at least we should get some better error.

**4. Actual behavior**
Currently the following error is displayed

![image](https://github.com/microsoft/AL/assets/56249171/faf7b32c-a21a-4cdc-a392-9af57160f734)

> Rendering output for the report failed and the following error occurred: An unexpected error occurred while compiling expressions. Native compiler return value: ‘[BC40000] 'RequestMinimum' is obsolete: 'Assembly level declarative security is obsolete and is no longer enforced by the CLR by default. See http://go.microsoft.com/fwlink/?LinkID=155570 for more information.'.’.
**5. Versions:**
- Business Central: Latest BC Version (BC 22.1=
- List of Visual Studio Code extensions that you have installed:

**Comment by pri-kise** [comment]
I close this issues since it probably won't be fixed here, but I want to provide a public solution for anybody having the same problem.

**Comment by aptMattKoe** [comment]
I had had the same error message (in my docker container) but another reason.
One line in the report code (inside the rdlc file) was not correct "in line".
![image](https://github.com/microsoft/AL/assets/57363453/15bed3b8-abcd-43a0-8d3c-0687d20efafa)

In the BC Environment there was this error:
![image](https://github.com/microsoft/AL/assets/57363453/0db872ad-c2c5-4627-bd8e-c85631758c8e)
