### ISSUE TITLE
[AL Explorer] Can not filter by Type

### ISSUE THREAD

**Issue by Ponch18** [microsoft/AL#7421]
1. Describe the bug
You can not filter objects by Type

2. To Reproduce

Open the AL explorer
Try to filter objects

3. Expected behavior
Enable possibility to filter

4. Actual behavior
It's not possibile to filter by Type

5. Versions:

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.787898
Publisher: Microsoft

**Comment by EmilDamsbo** [comment]
It is possible to group by object type which should be able to cover your scenario. See the below picture for example:
![image](https://github.com/microsoft/AL/assets/67266681/0d880b05-0482-4f51-800b-56e1648f6562)

Are you suggesting that the search filter should also allow to search for the object type? If so, can you provide an explanation why the above type grouping is insufficient?
