### ISSUE TITLE
OnAfterInsert() within TableExtension is not firing

### ISSUE THREAD

**Issue by RobertJohnstoneEque2** [microsoft/AL#7422]
**Version** = 22.0.54157.54644

**Code Sample:**
tableextension 50100 JobTableExt extends Job
{
    trigger OnAfterInsert()
    begin
        rec.description := 'Table Extension OnAfterInsert'
    end;
}

**Issue:**
In the above example, the code executes correctly if you enter a new Job record via the Job Card, by tabbing off of the "No." and allowing the default number series to populate the number.

The code does not execute if you use the "No. Series" AssistEdit on the Job Card to insert the new record.

Could someone please advise?

Cheers.
Robert

**Comment by pri-kise** [comment]
You should probably use the Trigger OnInsert if you want to change fields on the Job table.
OnAfterInsert executes after the transaction.

**Comment by BazookaMusic** [comment]
As mentioned this is how AL works by design.
