### ISSUE TITLE
[AL Explorer] Add object name in event subscribers

### ISSUE THREAD

**Issue by Ponch18** [microsoft/AL#7423]
**1. Describe the bug**
Add object name into subscribers events created with "Subscribe" button

**2. To Reproduce**
Search for event "OnAfterReleaseSalesDoc" into events list.
Subscribe 2 events with same names but from different objects.
Paste both events on a codeunit.

example:
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Release Sales Document", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure OnAfterReleaseSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var LinesWereModified: Boolean);
    begin
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure OnAfterReleaseSalesDoc(var SalesHeader: Record "Sales Header");
    begin
    end;

Compiler return error: "A member of type Method with name 'OnAfterReleaseSalesDoc' is already defined in Codeunit.. etc"

**3. Expected behavior**

Expectes events names:

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Release Sales Document", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure "Release Sales Document_OnAfterReleaseSalesDoc"(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var LinesWereModified: Boolean);
    begin
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure "Sales-Post_OnAfterReleaseSalesDoc"(var SalesHeader: Record "Sales Header");
    begin
    end;

**4. Actual behavior**
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Release Sales Document", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure OnAfterReleaseSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var LinesWereModified: Boolean);
    begin
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnAfterReleaseSalesDoc', '', false, false)]
    local procedure OnAfterReleaseSalesDoc(var SalesHeader: Record "Sales Header");
    begin
    end;

**5. Versions:**

- AL Language: v11.0.787898
- Visual Studio Code: 1.78.2
- Business Central: BC21, BC22
- List of Visual Studio Code extensions that you have installed: Al Language

**Comment by ernestasjuska** [comment]
Adding my 2 cents.

We usually name event subscribers like this:
```al
[EventSubscriber(ObjectType::Table, Database::"Sales Header", 'OnBeforeModifyEvent', '', false, false)]
local procedure "(Table Sales Header) OnBeforeModifyEvent"(var Rec: Record "Sales Header")
begin
    // ...
end;
```

Basically the procedure name always has format ```"(<ObjectType> <Object Name without quotes>) <EventName>[ - <Optional field name>]"```.

It would be a good idea to implement code analyzer that would check the procedure name. The format could be saved in workspace settings. This would be useful when event publisher is changed, but procedure name is left unchanged.
