### ISSUE TITLE
Debugger can't access dal file contents

### ISSUE THREAD

**Issue by lassekilperkm** [microsoft/AL#7430]
- AL Extension Version: v11.0.810452

- Server Version: DE Business Central 20.0 (Plattform 20.0.37114.38150 + Anwendung 20.0.37253.38230)

Try to debug the following code, any object with an '/' inside the name should trigger the problem.
```
    trigger OnAfterGetRecord()
    var
        Test: Codeunit "G/L Account Category Mgt.";
    begin
        Test.Run();
    end;
```
This results in the .dal file for the debugger showing `No content available` since the file's name is split at the position of the '/'.

Running the same code with another codeunit without an '/' in the object's name works as expected.
```
    trigger OnAfterGetRecord()
    var
        Test: Codeunit "Global Triggers";
    begin
        Test.Run();
    end;
```

**Comment by dannoe** [comment]
duplicate: https://github.com/microsoft/AL/issues/7369
