### ISSUE TITLE
Does not change page and role after finishing customized assisted setup.

### ISSUE THREAD

**Issue by KonstantynRomanowski** [microsoft/AL#7432]
**1. Describe the bug**
We have create a custom assisted setup for our application. In last step after selection Finish button the application should open specified Role Center page, but that does not happen and user stays on page he was previously.

**2. To Reproduce**
In any assisted setup to local procedure FinishAction add a new function "ChangeRole".

An example of the ChangeRole procedure:
```
local procedure ChangeRole()
    var
        SessionSetting: SessionSettings;
        ICIRoleIDLbl: Label 'ITI ICI', Locked = true;
    begin
        SessionSetting.Init();
        if SessionSetting.ProfileId() = ICIRoleIDLbl then
            exit;

        if SwitchRole then begin
            SessionSetting.ProfileId(ICIRoleIDLbl);
            SessionSetting.RequestSessionUpdate(true);
            Page.Run(Page::"ITI ICI Role Center");
        end;
    end;
```
**3. Expected behavior**
After finishing assisted setup should be open a Role Center page.

**4. Actual behavior**
Nothing happen and user stays on the page he was previously.

**5. Versions:**

- AL Language: v11.0.810452
- Visual Studio Code: 1.77.3
- Business Central: Version: W1 22.1 (Platform 22.0.56191.0 + Application 22.1.55890.56216)
No other extensions were enabled in recreating this issue.

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
