### ISSUE TITLE
TableRelation Formatting issue

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#7439]
Please include the following with each issue:

**1. Describe the bug**
The Table relation property is formatted wrong!
![image](https://github.com/microsoft/AL/assets/36199751/db06fc2c-61f0-45d4-8470-566f685da73d)

Even if I set the spaces manually like this:
![image](https://github.com/microsoft/AL/assets/36199751/1a20339b-f77f-49c6-9275-d1d9c57721b7)

When Formatting again the document (or if someone has the nice feature format on save) everything goes back to that ugly indentation.

**2. To Reproduce**
Write a multiline Table Relation 

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
A nicely done indentation, as the other things. 

**4. Actual behavior**
see first screenshot 

**5. Versions:**

- AL Language:
Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.810452
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
- Visual Studio Code:
Version: 1.79.1 (user setup)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:14:05.102Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- Business Central: does not matter
- List of Visual Studio Code extensions that you have installed: same here

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by nndobrev** [comment]
Hi,
 
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
 
Thanks

**Comment by navdotnetreqs** [comment]
Why report anything when 99% of issues just get shut down.
