### ISSUE TITLE
AA0205 should not be fired for Compare with empty Text (Default Value for Code)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7440]
Please include the following with each issue:

**1. Describe the bug**
A compare statement with the default value shouldn't trigger the warning AA0205 

**2. To Reproduce**

``` AL
var
    LastShippingAgentCode: Code[20];
begin
if MyTable.FindSet() then begin
    repeat
        if LastShippingAgentCode= '' then begin // warning AA0205: Use of unassigned variable 'MyValue '
            LastShippingAgentCode:= MyTable."Shipping Agent Code";
        end else begin
            Magic();
            LastShippingAgentCode:= MyTable."Shipping Agent Code";
        end;

      
    until MyTable.Next() = 0;
end;
end;
```

**3. Expected behavior**
We shouldn't get a warning if we are comparing with the default value.
If the variable is of Type Text everthing is working as expected an no warning is shown.

**4. Actual behavior**
We get the warning AA0205

**5. Versions:**

- AL Language: v11.0.810452

**Comment by BazookaMusic** [comment]
This is by design, since it also mimics the behavior of the C# analyzer for unassigned variables. If you do:

```c#
string cheese;
if (cheese == null)
{
  cheese = "Gooda";
}
```

You will get the same warning on cheese and it will request you to do it like,

```c#
string cheese = null;
if (cheese == null)
{
  cheese = "Gooda";
}
```

**Comment by dannoe** [comment]
@BazookaMusic
Shouldn't it warn for Text, Text[n] and Boolean then? Right now it doesn't. (Didn't check the pre-release version)


```al
    procedure MyProcedure()
    var
        MyTable: Record "Sales Line";
        LastShippingAgentCode: Text;
    begin
        if MyTable.FindSet() then
            repeat
                if LastShippingAgentCode = '' then // no warning for AA0205
                    LastShippingAgentCode := MyTable."Shipping Agent Code"
                else begin
                    Message('Foo');
                    LastShippingAgentCode := MyTable."Shipping Agent Code";
                end;
            until MyTable.Next() = 0;
    end;
```

**Comment by pri-kise** [comment]
@dannoe exactly. I thought that the behaviour for text is the correct one. Therefore I createdt this idea.
I would really appriciate it, if you create a new issue to get this warning for Text type, too.
