### ISSUE TITLE
Change Standard Code For Dimenssion (version issue)

### ISSUE THREAD

**Issue by Minn-Soe-Khant** [microsoft/AL#7441]
- AL Extension Version: 

- Server Version: 

In Codeunit 1336 (Item Templ. Mgt.)
    In Procedure InsertDimenssion, how to add the following Code
if DestDefaultDimension."Value Posting" = DestDefaultDimension."Value Posting"::" " then begin
                    DestDefaultDimension."Value Posting":= SourceDefaultDimension."Value Posting";
                    DestDefaultDimension.Modify(true);
                end;

**Comment by pri-kise** [comment]
This issue is lacking details and has nothing to do with the AL Language Extension.
Application issues should solved via questions on yammer or the normal support channel.

Therefore this issue should be closed here.
