### ISSUE TITLE
Values from Enum Extension out of the base app are not available

### ISSUE THREAD

**Issue by achim-t** [microsoft/AL#7448]
**1. Describe the bug**
Some Enums are defined in System and extended in Base. The additional values from the Base are not available.

**2. To Reproduce**
- AL: Go
- Edit HelloWorld.al:

``` AL
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('%1', "Email Scenario"::"Job Planning Line Calendar");
    end;
}
```

**3. Expected behavior**
It should compile.

**4. Actual behavior**
```error AL0132: '"Email Scenario"' does not contain a definition for 'Job Planning Line Calendar'```

**5. Versions:**

- AL Language: 12.0.12.14294
- Visual Studio Code: 1.78.2
- Business Central: 23
- List of Visual Studio Code extensions that you have installed:
  - AL Language

It works for BC 22 and AL Language 11.0.12.24044.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Looks like a bug

**Comment by kalberes** [comment]
This should work on later versions of the 12.x compiler.
![image](https://github.com/microsoft/AL/assets/12760483/bd1aff81-8c94-4c79-9018-4f6bf72d1730)
