### ISSUE TITLE
Select Just-In-Time-Debugger - Unhandled Exception / Ausnahmefehler in [23052]

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7449]
Please include the following with each issue:

**1. Describe the bug**
Since yesterday I always get the following window when trying to publish something

![image](https://github.com/microsoft/AL/assets/56249171/c8b26264-1989-4835-9e94-219d09fb55f5)

Additionally I have to reauthenticate (Copy+Open Authentication code) everytime.

**2. To Reproduce**
Publish an extensions

**3. Expected behavior**
Everything should be working as befor.

**Versions:**

- AL Language: v11.0.825804
- Visual Studio Code: Version: 1.78.2 (user setup)

**Comment by ptrk-tr** [comment]
I can confirm, getting the same behavior as described. Seems to be caused by yesterdays release of the AL Language version (v11.0.825804).

As a workaround for now: Installing the previous version of the AL Language extension (v11.0.810452) seems to be working. Only had to authenticate once after that, no more JIT Debugger window anymore.

**Comment by pri-kise** [comment]
I had the problem yesterday, that I always get an error, when I try to install the old version. 

> Download not possible - please try the manual download and installation

**Comment by pri-kise** [comment]
I update to VS Code: 
Version: 1.79.2 (user setup)

But this does not help.

Now even Download-Symbols did not help

**Comment by dotonpkt** [comment]
I downgraded AL Language extension and worked

**Comment by ptrk-tr** [comment]
> I had the problem yesterday, that I always get an error, when I try to install the old version.
> 
> > Download not possible - please try the manual download and installation

Were you able to install the old AL Language version then, after updating to VS Code 1.79.2? If not, have you tried downloading it directly from the VS Code marketplace? [Direct Download for v11.0.810452](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/11.0.810452/vspackage) and then installing the vsix directly in VS Code?

**Comment by pri-kise** [comment]
Now it was possible to downgrade the AL Language Extension after upgrade VS Code

**Comment by rickblommetjes** [comment]
Same here, will downgrade the extension

**Comment by debmitchell-tnp** [comment]
Same here. Have downgraded but now have issue with Create Package.

**Comment by mjmatthiesen** [comment]
v11.0.827766 appears to fix this

**Comment by SBalslev** [comment]
Correct v11.0.827766 resolves this issue.
