### ISSUE TITLE
Compare-NAVApplicationObject | Txt2al issue

### ISSUE THREAD

**Issue by MohamedGabsi1** [microsoft/AL#7450]
Hello,

I have strange issue while try to compare 2 NAV 2018 Object (customer object vs standard object).

when i run Compare-NAVApplicationObject  with  -ExportToNewSyntax parameter, as result i get identical file, while are not (at 10 field added) and no delta file is generated.

when i run Compare-NAVApplicationObject  without  -ExportToNewSyntax parameter, as result, i get the delta file.
I take the delta file & try to run Tx2al, i get an error The delta file was not generated with ExportToNewSyntax flag.

So I'm stuck in a loop... any idea please.

![image](https://github.com/microsoft/AL/assets/138225117/3bfd7f5d-e148-4817-9d01-8050bd7c8ef2)

**Comment by EmilDamsbo** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
