### ISSUE TITLE
'Assign-to Type' shows incorrect value

### ISSUE THREAD

**Issue by joelsigurd** [microsoft/AL#7454]
**1. Describe the bug**
The field 'Assign-to Type' on Sales Price Lists and Purchase Price Lists pages doesn't show the correct value.

**2. To Reproduce**
1. Go to the pages Sales Price Lists and Purchase Price Lists
2. Open a Price List Header record and set 'Assign-to Type' to any value
3. Open the Page Inspection and see that the value you chose has been assigned to the field 'Source Type'
4. Go back to the list page and the 'Assign-to Type' field has not been updated
5. Open the Page Inspection and you will see that the 'Source Type' field has been updated

**3. Expected behavior**
The 'Assign-to Type' field on the list page should match the 'Source Type' field on the record.

**4. Actual behavior**
![image](https://github.com/microsoft/AL/assets/25962318/e2f4b23b-ab6d-41d0-b003-416799f282b6)

**5. Versions:**

- AL Language: v11.0.827766
- Visual Studio Code: 1.79.2
- Business Central: 22.2 (Platform 22.0.57579.0 + Application 22.2.56969.57617)
- List of Visual Studio Code extensions that you have installed: Only AL Language Extension

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. 

If it is in the application and you already know how to fix the issue go to https://github.com/microsoft/ALAppExtensions and submit your suggestion for a fix.
