### ISSUE TITLE
Get Receipt Lines - Error when adding from the same PO

### ISSUE THREAD

**Issue by bsl-kuba** [microsoft/AL#7457]
**1. Describe the bug**
Issue with standard functionality, when creating a Purchase Invoice and trying to add extra lines via Line > Functions > 'Get Receipt Lines', if you select a receipt line that has the same PO as an existing line on the Purchase Invoice, you get the following error.
![image](https://github.com/microsoft/AL/assets/131792633/1f622b40-ad6e-4b3a-b2b9-6c902d841eb6)

Debugger breaks on Codeunit 1173 Document Attachment Mngt, Copy Attachments function, Line 1175
![image](https://github.com/microsoft/AL/assets/131792633/ec028b54-0c5a-45d9-996b-4c64be218c64)

**2. To Reproduce**
 Step 1: Create a Purchase Order, and post lines making sure to just 'Receive'.
 Step 2: Add attachments to the Purchase Order (attachment should go on the header, not the lines).
 Step 3: Create a Purchase Invoice, use Line > Functions > 'Get Receipt Lines' function to add the first receipt line.
 Step 4: Use the function again but select a different receipt line which originates from the same PO.

    procedure CopyAttachments(var FromRecRef: RecordRef; var ToRecRef: RecordRef)
    var
        FromDocumentAttachment: Record "Document Attachment";
        ToDocumentAttachment: Record "Document Attachment";
        FromFieldRef: FieldRef;
        ToFieldRef: FieldRef;
        FromDocumentType: Enum "Incoming Document Type";
        FromLineNo: Integer;
        FromNo: Code[20];
        ToNo: Code[20];
        ToDocumentType: Enum "Incoming Document Type";
        ToLineNo: Integer;
    begin
        FromDocumentAttachment.SetRange("Table ID", FromRecRef.Number);
        if FromDocumentAttachment.IsEmpty() then
            exit;
        case FromRecRef.Number() of
            DATABASE::Customer,
            DATABASE::Vendor,
            DATABASE::Item:
                begin
                    FromFieldRef := FromRecRef.Field(1);
                    FromNo := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("No.", FromNo);
                end;
            DATABASE::"Sales Header",
            DATABASE::"Purchase Header":
                begin
                    FromFieldRef := FromRecRef.Field(1);
                    FromDocumentType := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("Document Type", FromDocumentType);
                    FromFieldRef := FromRecRef.Field(3);
                    FromNo := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("No.", FromNo);
                end;
            DATABASE::"Sales Line",
            DATABASE::"Purchase Line":
                begin
                    FromFieldRef := FromRecRef.Field(1);
                    FromDocumentType := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("Document Type", FromDocumentType);
                    FromFieldRef := FromRecRef.Field(3);
                    FromNo := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("No.", FromNo);
                    FromFieldRef := FromRecRef.Field(4);
                    FromLineNo := FromFieldRef.Value();
                    FromDocumentAttachment.SetRange("Line No.", FromLineNo);
                end
        end;

        case ToRecRef.Number() of
            DATABASE::"Sales Line":
                if FromRecRef.Number() <> DATABASE::"Sales Line" then
                    FromDocumentAttachment.SetRange("Document Flow Sales", true);
            DATABASE::"Sales Header":
                if FromRecRef.Number() <> DATABASE::"Sales Header" then
                    FromDocumentAttachment.SetRange("Document Flow Sales", true);
            DATABASE::"Purchase Line":
                if FromRecRef.Number() <> DATABASE::"Purchase Line" then
                    FromDocumentAttachment.SetRange("Document Flow Purchase", true);
            DATABASE::"Purchase Header":
                if FromRecRef.Number() <> DATABASE::"Purchase Header" then
                    FromDocumentAttachment.SetRange("Document Flow Purchase", true);
        end;

        if FromDocumentAttachment.FindSet() then
            repeat
                Clear(ToDocumentAttachment);
                ToDocumentAttachment.Init();
                ToDocumentAttachment.TransferFields(FromDocumentAttachment);
                ToDocumentAttachment.Validate("Table ID", ToRecRef.Number);

                ToFieldRef := ToRecRef.Field(3);
                ToNo := ToFieldRef.Value();
                ToDocumentAttachment.Validate("No.", ToNo);

                case ToRecRef.Number() of
                    DATABASE::"Sales Header",
                    DATABASE::"Purchase Header":
                        begin
                            ToFieldRef := ToRecRef.Field(1);
                            ToDocumentType := ToFieldRef.Value();
                            ToDocumentAttachment.Validate("Document Type", ToDocumentType);
                        end;
                    DATABASE::"Sales Line",
                    DATABASE::"Purchase Line":
                        begin
                            ToFieldRef := ToRecRef.Field(1);
                            ToDocumentType := ToFieldRef.Value();
                            ToDocumentAttachment.Validate("Document Type", ToDocumentType);

                            ToFieldRef := ToRecRef.Field(4);
                            ToLineNo := ToFieldRef.Value();
                            ToDocumentAttachment.Validate("Line No.", ToLineNo);
                        end;
                end;

                if not ToDocumentAttachment.Insert(true) then;

                ToDocumentAttachment."Attached Date" := FromDocumentAttachment."Attached Date";
                ToDocumentAttachment.Modify();   ######### THIS IS THE LINE THAT BREAKS WHEN RUNNING IN DEBUG ########

            until FromDocumentAttachment.Next() = 0;

        // Copies attachments for header and then calls CopyAttachmentsForPostedDocsLines to copy attachments for lines.
    end;

**3. Expected behavior**
The receipt line(s) selected should be added onto the Purchase Invoice, and any attachments should also be moved across onto the Purchase Invoice if they have not already been copied from a previous use of the 'Get Receipt Lines' function - if the attachments already exist then we should see just the new Purchase Lines added.

**4. Actual behavior**
The selected receipt line(s) is not added onto the Purchase Invoice, and the attachment(s) do not get moved across onto the Purchase Invoice if they were not previously added.

**5. Versions:**
- AL Language: v11.0.827766
- Visual Studio Code: 1.80 (current)
- Business Central: 22.2.56969.57282

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by pri-kise** [comment]
@AndreiPanko answered the following on [yammer](https://www.yammer.com/dynamicsnavdev/threads/2391222976503808):
>This one was already reported and fixed. I'm not aware how it will be distributed (next minor update or hotfix).
Ref: 477621
