### ISSUE TITLE
Suggestion: Code Documentation

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#746]
If you build an extension on top of another extension, of which you don't know the code, your only chance is to guess how it behaves based on its symbol names.

It would be great to be able to add more information/documentation to the base extension in order to make it easier for the one extending the extension.

E.g. 
- describe the parameters of a function
- describe the meaning of the return value of a function
- give some insight in what the function does
- add additional information to fields in a table
- add additional information about the purpose of objects
- etc.

It could be imagined either as Properties of the Items to be documented or as in-code comments like in Visual Studio 

E.g.
        /// <summary>
        /// Sends the message.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="message">The message.</param>
        /// <param name="expectingresponse">if set to <c>true</c> [expectingresponse].</param>
        public void SendMessage(int id, string message, bool expectingresponse = false)

This information can then be shown in IntelliSense.

**Comment by Gallimathias** [comment]
I'd like to link that to the other issues: #132 #567 #707

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. It is already tracked through #132
