### ISSUE TITLE
Creating an additional key to an existing table with "Clustered = true" is not rejected by the compiler. 

### ISSUE THREAD

**Issue by JoergDZ** [microsoft/AL#7461]
**1. Describe the bug**
If a new key is created in an existing table with the property "Clustered = true", neither the compiler nor the AppSource Validation complains about this, although this is a breaking change, because the primary key is implicitly clustered by default.
This prevents an update of the installed app with the following message _"Changing the key 'Key1' to not be clustered is not allowed. Set the 'Clustered' property on the key 'Key1' to true again."_

**2. To Reproduce**
Step 1: Create new Table
Step 2: Compile App and install
Step 3: Create a new Key with Property "Clustered = true"
Step 4: Compile App´
Step 5: Update existing App (BC reports to Sync-NAVApp with above error message)

**3. Expected behavior**
Error message when compiling the app: _"Changing the key 'Key1' to not be clustered is not allowed."_

**4. Actual behavior**
App will be compiled with no issues.

**5. Versions:**

- AL Language: v11.5.834620
- Visual Studio Code: 1.80.1
- Business Central: 22.3.58346.58453
- AZ AL Dev Tools/AL Code Outline

**Comment by BazookaMusic** [comment]
Accepting this since it led to failures for AVS jobs
