### ISSUE TITLE
System crash if procedure has many lines

### ISSUE THREAD

**Issue by OlegLobakov** [microsoft/AL#7462]
![image](https://github.com/microsoft/AL/assets/34211051/37918601-4b74-460d-9ef8-10e133460a14)

**1. Describe the bug**
System crash if procedure has many lines. 
in >= BC22 version (in previous version it works)
debugger and breakpoints does not work in procedure.

**2. To Reproduce**
Create procedure with a lot of lines (~9000 lines):
For example, we have function that complete some table and run 1 function,  
dumb function like
![image](https://github.com/microsoft/AL/assets/34211051/4dee6d90-95f5-4f5e-997d-e60cadd65fec)

CreateAirPort('ZZZ', 'XXX', XXXX', 11, 'French Polynesia', 'PF', -17.354999, -145.508332);

**5. Versions:**
- AL Language: 11.5
- Visual Studio Code: 1.70 
- Business Central: 22
- List of Visual Studio Code extensions that you have installed: does not matter

**Comment by qutreson** [comment]
@OlegLobakov - We have discussed in the team and we will not introduce a compiler warning or error when a procedure has too many lines. However, this could be a good candidate for some new CodeCop analyzer rules about code maintainability. We would then recommend logging this as an idea on aka.ms/BCIdeas or voting up on the idea if it is already there.

**Comment by qutreson** [comment]
@OlegLobakov - We have discussed in the team and we will not introduce a compiler warning or error when a procedure has too many lines. However, this could be a good candidate for some new CodeCop analyzer rules about code maintainability. We would then recommend logging this as an idea on aka.ms/BCIdeas or voting up on the idea if it is already there.
