### ISSUE TITLE
Query object does not recognize table extension fields from dependent extension

### ISSUE THREAD

**Issue by Mashaiasu** [microsoft/AL#7463]
**1. Describe the bug**

When creating a query and adding fields that originate from another table extension on the chosen table, the fields are not recognized.

In my case the fields are able to be used by other objects/code, and a table object and all its fields that belong to that same extension can also be used in a query, so it is not a dependency issue.

**2. To Reproduce**

1. Create new query object.
2. Add a table that has a table extension (belonging to another extension) to the query.
3. Add a field belonging to that table extension.

![image](https://github.com/microsoft/AL/assets/5380983/9bf75924-3020-4276-99f3-0ffb70d6206c)

**3. Expected behavior**

The field is able to be added to the query without issue and treated as a field of the table.

**4. Actual behavior**

The field is not recognized as a proper field on the table and cannot be used.

**5. Versions:**

- AL Language: v11.5.834620
- Visual Studio Code: 1.80.1
- Business Central: 22.2

**Comment by BazookaMusic** [comment]
What is the type of the fields? Can you also provide their definition or a minimal reproduction of the issue in a project?

**Comment by Mashaiasu** [comment]
As of today I rechecked this issue and found everything to be working as expected.
The only change I see is that my Visual Studio Code updated to version 1.81.0, which seems to have fixed it.

I will close the issue.

**Comment by slashinpdx** [comment]
Having this same issue today.

**Comment by NKarolak** [comment]
@slashinpdx Microsoft does not look into closed issues. If you want them to proceed your issue - and your VS Code version is >= 1.81.0, then please create a new one (but you can mention the old one in there).

**Comment by slashinpdx** [comment]
Thank you for the response.  I'll do that.  I was really just looking for a bit of advice if anyone saw my post.

**Comment by slashinpdx** [comment]
For anyone else looking here, I found a workaround in putting the dependent query inside the same AL file as the table extension.
