### ISSUE TITLE
FactBox Page (PageType = CardPart) with ShowAsTree and visible can not collapse

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/AL#7465]
**1. Describe the bug**
On a FactBox Page (PageType = CardPart) with an Repeater with ShowAsTree = true and using the Visible Property you can not expand and collapse the tree this is always completely expand, can not be collapse.

**2. To Reproduce**
An example
``` AL
page 50100 "MyFactBox"
{
    Caption = 'Demo Tree Fact Box';
    Editable = false;
    PageType = CardPart;
    ApplicationArea = All;
    InsertAllowed = false;
    RefreshOnActivate = true;
    ShowFilter = false;
    SourceTable = "Item Category";
    SourceTableView = SORTING("Presentation Order");
    UsageCategory = Administration;

     layout
    {
        area(content)
        {
            repeater(Control1)
            {
                IndentationColumn = Rec.Indentation;
                IndentationControls = "Code";
                ShowAsTree = true;
                ShowCaption = false;
                Visible = ShowControl1;
                field("Code"; Rec.Code)
                {
                     Editable = false;

                    trigger OnValidate()
                    begin
                        CurrPage.Update(false);                       
                    end;
                }
                field(Description; Rec.Description)
                {

                }
            }
        }    
     
    }

    actions
    {
        area(Processing)
        {
              action(MyDemoSetVisibleTrue)
                    {
                        ApplicationArea = All;
                        Caption = 'Set Visible True';
                        Image = EndingText;
                         trigger OnAction()
                         begin
                            ShowControl1 := true;  
                            CurrPage.Update();                       
                         end;
                    
                    }
                      action(MyDemoSetVisibleFalse)
                    {
                        ApplicationArea = All;
                        Caption = 'Set Visible False';
                        Image = Alerts;
                         trigger OnAction()
                         begin
                            ShowControl1 := false;                         
                            CurrPage.Update();
                         end;
                    
                    }
      
        }      
    }

   trigger OnOpenPage()
    begin
        ShowControl1 := true;     
    end;
    
    var
        ShowControl1: Boolean;
}

pageextension 50100 MyItemCard extends "Item Card"
{
    layout
    {
          addfirst(FactBoxes)
        {
            part(MyFactBox; MyFactBox)
            {
                ApplicationArea = All;
                ShowFilter = false;                
            }
        }
    }
}

```

**3. Expected behavior**
The tree should be able to expand and collapse

**4. Actual behavior**
The tree is complete expand and can not collapse

**5. Versions:**
AL Language: 11.5.834620
Visual Studio Code: 1.80.1
Business Central: Version: W1 22.3 (Platform 22.0.58692.0 + Application 22.3.58346.58709)
No other extensions were enabled in recreating this issue.

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by Schnieringer** [comment]
**Currently I have not received any feedback on the issue. The problem still exists with BC23 and Runtime 12.**

Versions:
AL Language: v12.0.875970
Visual Studio Code: 1.82.2
Business Central: Version: Version: W1 23.0 (Platform 23.0.12789.0 + Application 23.0.12034.12816)
No other extensions were enabled in recreating this issue.

**Comment by ChrisBlankDe** [comment]
Hi @EmilDamsbo, can you please have a look on this?
I know that this issue is not in the scope of this repo but we dont know a better place and you created internal issues on similar web-client issues.

**Comment by ChrisBlankDe** [comment]
Thanks @EmilDamsbo !
We [Reported this on Yammer](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2501056528662528) but got no reaction from msft :(

**Comment by EmilDamsbo** [comment]
Hi again @ChrisBlankDe and @Schnieringer, I spoke with the team responsible for the BC web client and we actually have a dedicated group for such discussion over at https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=123146436608
I hope you have better luck reporting issues there in future, but you are also encouraged to log a support request for these types of issues.
