### ISSUE TITLE
Table Relation Filter Issue

### ISSUE THREAD

**Issue by shankarradha-dxc** [microsoft/AL#7466]
**Original code - base application - Table 39 Purchase Line**

        field(45; "Job No."; Code[20])
        {
            Caption = 'Job No.';
            TableRelation = Job;

            trigger OnValidate()
            var
                Job: Record Job;
                IsHandled: Boolean;
            begin

**Table extension one of our client requested to show only open/active jobs in the purchase, they want to see the full list of jobs that are not open.**

**I made the below change hoping to work, apparently not. Is it bug in the product.**

tableextension 55002 "Purchase Line Ext" extends "Purchase Line"
{
    fields
    {
        // Add changes to table fields here
        modify("Job No.")
        {
            TableRelation = Job Where(Status = filter(Open));
        }
    }
}

**Comment by BazookaMusic** [comment]
This could either be a compiler bug or a runtime issue. It needs some investigation

**Comment by christianbraeunlich** [comment]
To me it looks as designed, as it states in the documentation: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tablerelation-property#example "Modifications to the TableRelation are additive [...]. The primary use case is conditional table relations based on conditional enums."

Maybe this could become a feature, but I doubt there's a good way to handle it, when multiple extensions try to modify the property.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
