### ISSUE TITLE
Cannot debug code in upgrade codeunits (outside upgrade process)

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7468]
**1. Describe the bug**
The debugger does not stop at breakpoints set in upgrade codeunits - even when _not_ upgrading.

**2. To Reproduce**
Add a page action that calls a procedure declared in codeunit with `Subtype = Upgrade;`.
Set a breakpoint in your procedure code.
Publish with debugging (F5). In the web client, invoke the new action.

**3. Expected behavior**
The debugger should stop at the breakpoint.

**4. Actual behavior**
The system behaves as if during an upgrade: no debugger stop at breakpoint.
Once you remove `Subtype = Upgrade;` from the codeunit, the breakpoint resumes working.

**5. Versions:**

- AL Language: 11.5
- Business Central: 22.3

**Comment by thloke** [comment]
I'm not sure if this is still relevant. I tried a simple repro as follows:

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addfirst(General)
        {
            action(Upgrade)
            {
                trigger OnAction()
                begin
                    Upgrade.Action();
                end;
            }
        }
    }
    var
        Upgrade: Codeunit "MyCodeunit";
}

codeunit 50100 MyCodeunit
{
    Subtype = Upgrade;

    procedure Action()
    begin
        Message('Upgrade');
    end;
}
```

Adding a breakpoint on MyCodeunit::Action works as expected, when I use the new action on the page it hits the breakpoint. Maybe this has been fixed in the meanwhile?

**Comment by NKarolak** [comment]
Thanks @thloke, 
tested with AL 12.6, I cannot reproduce it anymore either.
