### ISSUE TITLE
List page (not editable) on table 9999 "Upgrade Tags"

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/AL#7469]
We've also started using tag handling to perform data arrangements in upgrade-type codeunits. 
Would it be possible to have a list to check which updates have been performed and when?
Being a table of type internal, we can't do it
Thank you
![image](https://github.com/microsoft/AL/assets/51199875/4e4d5a7c-43f3-4547-999d-c6f186c8e477)

**Comment by nndobrev** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
