### ISSUE TITLE
Error Messages for Action with RunPageLink

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#747]
I get three error messages if try to create an Action on Page Chart of Accounts:

> Reference to object Change Log Entries is ambiguous. Make sure you are not referencing packages containing objects with the same names.

> The property value '"Table No."=CONST(15), "Primary Key Field 1 Value"=FIELD("No.")' on property 'RunPageLink' is not valid.

> Field type Text is not convertible to field type Code.

```
pageextension 70000002 pageextension70000002 extends "Chart of Accounts" 
{
  layout
  {
  }
  actions
  {
    addafter("G/L Register")
    {
      action("Change Log Entries")
      {
        CaptionML=DEU='Änderungsprotokoll',
                  ENU='Change Log Entries';
        Image=ChangeLog;
        RunObject=Page "Change Log Entries";
        RunPageLink="Table No."=CONST(15), "Primary Key Field 1 Value"=FIELD("No.");
        RunPageView=SORTING("Table No.","Primary Key Field 1 Value") ORDER(Descending);
      }
    }
  }
}
```
![chart of account error](https://user-images.githubusercontent.com/9556549/31359104-d82c204c-ad48-11e7-9d37-4ddf2db03588.png)

**Comment by StanislawStempin** [comment]
I cannot reproduce it either. It looks like this one is also caused by ambiguous references. 
Do you have any extension dependencies in app.json? Can you make sure that you have up to date symbol files (.app) by deleting them from the cache and redownloading from the server?

**Comment by DanielGoehler** [comment]
There are no dependencies in app.json. I deleted the symbol files. Problem still exists.

I attached a sample project with the .al-File in the screenshot, which generates the second and third error message in the September Update Azure VM. I try to reproduce the first error message for the case #745.

```
Microsoft (R) AL Compiler version 0.9.12794
Copyright (C) Microsoft Corporation. All rights reserved

c:\Users\vmadmin\Simple Project\Modification  - Chart of Accounts(Page 16).al(13,44): error AL0204: Field type Text is not convertible to field type Code.
c:\Users\vmadmin\Simple Project\Modification  - Chart of Accounts(Page 16).al(13,21): error AL0171: The property value '"Table No."=CONST(15), "Primary Key Field 1 Value"=FIELD("No.")' on property 'RunPageLink' is not valid.
Error: The package could not be created.
```
[Simple Project.zip](https://github.com/Microsoft/AL/files/1377389/Simple.Project.zip)

**Comment by qutreson** [comment]
Hi @DanielGoehler, are you still facing this issue? I just tried to reproduce it using the zip file you attached and it seems to work fine now. If you can still reproduce it, please open a new issue for it and I will pick it up.
