### ISSUE TITLE
ALDoc repeats remarks until they change

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#7470]
**1. Describe the bug**
If xml comments include remarks, the same remark is repeated for each method without a remark.

**2. To Reproduce**
Use the following code to have the first two procedures contain the remarks from the first:

``` AL
    /// <summary>
    /// An important procedure
    /// </summary>
    /// <param name="tableId">The ID of the table</param>
    /// <param name="tableFilterText">a table filter as text</param>
    /// <param name="doLookup">Select whether you like to do a lookup or validation.</param>
    /// <returns>A table filter as text</returns>
    /// <remarks>
    ///   The filter is composed from the table name and field CAPTIONS!
    /// </remarks>
    procedure HandleTableFilter(tableId: Integer; tableFilterText: Text; doLookup: Boolean): Text
    begin
    end;

    /// <summary>
    /// Apply a table filter to a record reference.
    /// </summary>
    /// <param name="tableFilterText">The table filter as text.</param>
    /// <param name="toRecRef">The record reference to apply the filter to.</param>
    procedure ApplyTableFilter(tableFilterText: Text; var toRecRef: RecordRef)
    begin
    end;

    /// <summary>
    /// A third procedure
    /// </summary>
    /// <param name="tableFilterText">The table filter as text.</param>
    /// <param name="toRecRef">The record reference to apply the filter to.</param>
    /// <remarks>
    ///	This one is shown.
    /// </remarks>
    procedure ThirdProcedure(tableFilterText: Text; var toRecRef: RecordRef)
    begin
    end;
```
**3. Expected behavior**
The remarks (and possibly other values) must be cleared after processing each procedure.

**4. Actual behavior**
The first two procedures contain the remarks from the first:

**5. Versions:**

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 12.0.847725
Publisher: Microsoft

Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by MODUSCarstenScholling** [comment]
I'm sorry, the issue seems to be in docfx. The generated reference yaml itself does not repeat. Closing this issue.

**Comment by MODUSCarstenScholling** [comment]
It is really hard to get to the point if you don't know the tools well. I now assume again it is AlDoc. If you change the template file `BusinessCentralApplicationObject.html.primary.js` slightly, it works. it can be an issue in docfx probably, but eventually this change is easier:

From:
```JavaScript
function updateMemberDetails(members) {
	if (members) {
		members.forEach(element => {
			element.commentId = element.commentId || null;
			element.examples = element.example || null;
			element.remarks = element.remarks || null;
			element.summary = element.summary || null;
			element.description = element.description || null;
			updateSyntax(element.syntax);
			updateObsoletion(element);
		});
	}
}
```

To:
```JavaScript
function updateMemberDetails(members) {
	if (members) {
		members.forEach(element => {
			element.commentId = element.commentId || null;
			element.examples = element.example || null;
			element.remarks = element.remarks || "";
			element.summary = element.summary || null;
			element.description = element.description || null;
			updateSyntax(element.syntax);
			updateObsoletion(element);
		});
	}
}
```

**Comment by nndobrev** [comment]
Hi,
 
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
 
Thanks
