### ISSUE TITLE
ALDoc does not generate an object summary if the namespace declaration follows the summary

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#7471]
**1. Describe the bug**
ALDoc does not generate an object summary if the namespace declaration follows the summary comment.

**2. To Reproduce**

``` AL
/// <summary>
/// Anything around stuff.
/// </summary>
namespace MODUS.Anything;

codeunit 123456 "M365 Anything"
{
}
// ^^^The above is NOT working properly
```
``` AL
namespace MODUS.Anything;
/// <summary>
/// Anything around stuff.
/// </summary>
codeunit 123456 "M365 Anything"
{
}
// ^^^The above is working
```

**3. Expected behavior**
Both variants should be working equally OR the first variant must raise a compile time error.

**4. Actual behavior**
In the case of the namespace declaration after the summary, the summary tag is missing in the generated reference yaml.

**5. Versions:**

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 12.0.847725
Publisher: Microsoft

Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by esbenk** [comment]
This is by design. The xml-comment always belongs to the next/closest symbol. We also still support multiple objects in same file.

We don't plan to warn/error against this.

**Comment by MODUSCarstenScholling** [comment]
Ok, that makes sense, thank you Esben.
