### ISSUE TITLE
AL0118: Breaking change regarding CurrPage.Editable ahead?

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7473]
I am developing with AL Language 11.5.83462 in runtime 8.0.

Recently, I've added the following Code to a page OnOpen trigger:
`Editable = false;`
This is not a variable, but a reference to the [Page.Editable method](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-editable-method).
The compiler accepts it without warning, and the solution is deployed and working correctly.

However, the Run-AlValidation script terminates with the following error:
`error AL0118: The name 'Editable' does not exist in the current context`

The issue is solved by writing instead 
`CurrPage.Editable(false);`

According to its log, Run-AlValidation used the following AL version: 11.5.12.48212

If that means that the upcoming AL Language 12 cannot interpret `Editable = false;` correctly, then please make it a warning already in AL Language 11.x, so we can prepare.

**Comment by qutreson** [comment]
@NKarolak - are you still experiencing this issue? I cannot reproduce it on the latest versions of the vsix

![image](https://github.com/microsoft/AL/assets/31541422/6b1de8c0-0404-44e1-85a8-fcc379579e11)

**Comment by NKarolak** [comment]
I'd misread the AL Validation log file: the issue appeared only for the minimum version check that still run AL Language 8.0, not the current version.

The issue in question was fixed with AL Language 11.0.787898 (1st update of 11.0).
