### ISSUE TITLE
Issue with GeneralLedgerSetup on report 5692 "Calculate Depreciation"

### ISSUE THREAD

**Issue by MoallaMehdi** [microsoft/AL#7475]
On the Report 5692, use of GeneralLedgerSetup record table when rounding : 
                Custom1Amount := round(Custom1Amount, GeneralLedgerSetup."Amount Rounding Precision");
                DeprAmount := round(DeprAmount, GeneralLedgerSetup."Amount Rounding Precision");

but GeneralLedgerSetup is never initialized (GeneralLedgerSetup .get() not found)
In fact, when calculate depreciation, the value is always round to 0.01, even we put 0.001 on general ledger setup

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
