### ISSUE TITLE
AL language does not respect editor.suggest.insertMode setting

### ISSUE THREAD

**Issue by JosefKainz** [microsoft/AL#7478]
Please include the following with each issue:

**1. Describe the bug**
The AL language extensions does not respect the editor.suggest.insertMode. It always behaves like the setting is set to replace.

**2. To Reproduce**
Set the setting to insert.
Set the cursor infront of existing code.
Select a suggestion from intellisense.

![image](https://github.com/microsoft/AL/assets/122879590/f8b98132-637c-4810-9d4d-7d5c263f48f1)

**3. Expected behavior**
 The chosen suggestion will be placed infront of the existing code.

**4. Actual behavior**
 The following code is still be consumed like setting is set to replace.

**5. Versions:**

- AL Language: v11.5.8
- Visual Studio Code: 1.81.1
- List of Visual Studio Code extensions that you have installed: AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
I've not been able to reproduce your issue, the insert mode is respected as far as I could see:
![image](https://github.com/microsoft/AL/assets/67266681/44c02fdc-445f-473f-bc82-eef9db7f27dd)

I also tried inserting a snippet in front and that did not replace the "true", though of course it didn't compile:
![image](https://github.com/microsoft/AL/assets/67266681/e538faac-055e-4f72-82ee-95f5e6613405)

Could you provide a case where this happens consistently for you, even better if you could upload a gif/video.

**Comment by JosefKainz** [comment]
I updated vscode and the extensions and now the setting works.
The issue can be closed.
