### ISSUE TITLE
Date(-Time) functions suggestion

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#748]
Now we have the **TextBuilder** and the built-in functions on the **Text** variable. I'd like this!

**Poin 1**
Is it a good idea to add built-in functions on the Date(-Time) variable like the System.DateTime in mscorlib?

I think, it's easier to write date/time specific code (see print screen).

**System.DateTime.?**
```
.Add
.AddDays
.AddHours
.AddMilliseconds
.AddMinutes
.AddMonths
.AddSeconds
.AddTicks
.AddYears
.DayOfWeek
.DayOfWeek
.DayOfYear
.DaysInMonth (Current option: DATE2DMY(CALCDATE('CM',DMY2DATE(01,MonthNumber,YearNumber)),1);)
.Year (Current option: DATETODMY(Date,3)
.Month (Current option: DATETODMY(Date,2)
.Day (Current option: DATETODMY(Date,1)
.Hour
.Minute
.Second
.Millisecond
.IsDaylightSavingTime
.IsLeapYear
.Parse(Optional: Culture <String>, Optional: Format <string>)
.ParseExact(Optional: Culture <String>, Optional: Format <string>)
.TryParse(Optional: Culture <String>, Optional: Format <string>)
.TryParseExact(Optional: Culture <String>, Optional: Format <string>)
```

**Point 2:**

Also missing:
```
TODAY(Optional: UTC <Boolean>)
WORKDATE(Optional: UTC <Boolean>)
CURRENTDATETIME(Optional: UTC <Boolean>)
```

**Point 3:**
Do we get these Text functions also in C/AL?

![image](https://user-images.githubusercontent.com/28626283/31383524-aa643776-adbb-11e7-9af6-df4543a4bbbc.png)

**Comment by bvbeek** [comment]
What is the status of this issue?

**Comment by pri-kise** [comment]
Is there any progress? Especially the to parse with CultureInfo is mandatory for replacing C/AL with AL

**Comment by atoader** [comment]
Hi! As this feature would require input from multiple teams would you please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. 
Another option would be to build AL wrappers for .NET functionality and submit them to the System Application repository.

**Comment by DanielGoehler** [comment]
Hi @atoader,

the wrapper codeunits starting with DotNet* are currently all part of the base app. Will that change anytime soon so can do PR?

**Comment by atoader** [comment]
I might have said something silly, I was under the impression that those are part of the System Application. @JesperSchulz can provide more guidance on this

**Comment by JesperSchulz** [comment]
Unfortunately we don't have the capacity to turn all of our .NET wrappers into proper System Application Modules at the moment. However, if you have wrapper that you'd like to add to, please do take a stab at transforming it into a module and submit a PR, and we will happily process it. An example of a wrapper module is the [Math module](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Math).
