### ISSUE TITLE
Action Find Event (Shift+Alt+E) lookup only business, integration events defined in the source code

### ISSUE THREAD

**Issue by boych83** [microsoft/AL#7480]
**1. Describe the bug**
If I call "Find Event"action and searching for a trigger events ( system events that are automatically declared and published in a table and page object) the dropdown menu not showing these events subscribers.

**2. To Reproduce**
From an AL project in codeunit object open the event list by using the Shift + ALT + E shortcut.
Start typing e.g. 'OnBeforeModifyEvent'.  Selecting an event from the list is not possible.

![image](https://github.com/microsoft/AL/assets/9000967/3cb077ed-7762-4b7a-95f8-17f8e374bd29)

**3. Expected behavior**
The list should include all the events as is stated in documentation for EventSubscriber Attribute https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-eventsubscriber-attribute
![image](https://github.com/microsoft/AL/assets/9000967/782b22b9-95fd-4e70-a429-26d185775fb2)

**4. Actual behavior**
When calling "Find Event" action, only business and integration events are listed in dropdown menu

**5. Versions:**

- AL Language: 11.5.834620
- Visual Studio Code: 1.80.1

**Comment by qutreson** [comment]
We discussed this internally and we will update the documentation to reflect the current behavior because the list of events would be too big and most likely unusable.

**Comment by boych83** [comment]
Dear @qutreson 

Okay.

I don't know how this works internally, but:
- the number of events could be limited on initial load. Then would be dynamically loaded only the new ones when you scroll/move up/down the list or when you narrow down the search,
- if all events need to be loaded at once, then I also aggre that action will most likely be useless due to higher loading time after initiating the command
