### ISSUE TITLE
ALDoc: `aldoc build` fails with a NullReferenceException, detailed logging required

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7481]
Please include the following with each issue:

**1. Describe the bug**
I tried to run `aldoc` on an app of mine, but the `build` command fails with a generic NullReferenceException. I don't really know what I am doing wrong, if there is bug in the tool or if there is something wrong with my code. We really need a detailed stack trace or logging feature that allows us to delve into the root cause of any build failures.

**2. To Reproduce**
N/A

**3. Expected behavior**
You should provide a detailed logging experience (including stack traces), either by file or somewhere else. This is a tool intended for developers and as such should provide as much technical detail as possible.

**4. Actual behavior**
I just get a "Object reference not set to an instance of an object" exception, not telling me where or why that error occurred.

**5. Versions:**

- AL Language: v12.0.849798
- Visual Studio Code: N/A
- Business Central: N/A
- List of Visual Studio Code extensions that you have installed: N/A

**Comment by easypdf365** [comment]
I second the motion.
Respectfully, the tool is not usable in its current form - mostly due to the complete lack of diagnostics in the docfx tool.

**Comment by esbenk** [comment]
> I second the motion. Respectfully, the tool is not usable in its current form - mostly due to the complete lack of diagnostics in the docfx tool.

The docfx tool is an open source tool with its own repo. Lack of diagnostics in docfx should be reported in the docfx repo.

**Comment by esbenk** [comment]
The aldoc tool is in only available in the pre-release build and not officially released. Bugs are expected and will be addressed. If the aldoc tool fails to crashes during "aldoc build" it is a bug in tool. 

We will add some context with the current symbol being processed during the crash to help provide repro.

**Comment by tadaskristolaitis-columbus** [comment]
The mitigation is to downgrade DocFx to version 2.70.0.
#7488

**Comment by MODUSCarstenScholling** [comment]
Workaround in #7488
