### ISSUE TITLE
ALDoc chokes on .app filename with comma, succeeds with 8.3 name

### ISSUE THREAD

**Issue by easypdf365** [microsoft/AL#7484]
**1. Describe the bug**
aldoc raises an exception when an app filename containing commas is passed.

**2. To Reproduce**
aldoc -o . -t '.\myapp X, Y, Z_1.0.0.0.app'
Unhandled exception. System.IO.FileNotFoundException: Could not find file '.\myapp X, Y, Z_1.0.0.0.app'.

aldoc -o . -t '.\MYAPPX~1.APP'
success

**3. Expected behavior**
It should handle any valid filename.

**4. Actual behavior**
Raises exception.

**5. Versions:**

- AL Language:
aldoc 12.0.12.63390
- Visual Studio Code:
n/a
- Business Central:
n/a
- List of Visual Studio Code extensions that you have installed:
n/a

**Comment by SBalslev** [comment]
After revisiting this old issue, we have decided not to accept it. The tool uses , as separator between modules so it does not accept , in the file names. Workaround is to rename the file before calling ALDoc.
