### ISSUE TITLE
File paths for CodeCop issues in output window have become relative and thus are no longer "clickable" URLs

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7486]
**1. Describe the bug**
At some point in the preview version (12.x) of the AL Language extension the file/position indicators in the output window when building an AL project have become relative URLs and thus have stopped to be clickable links. In AL Language 11.x they were absolute URLS (prefixing it with the AL project folder) and so they were clickable. I could quickly jump to the single issue instance and resolve it.

This has become a major nuisance because the CodeCop warnings by default (and for good reason) in the "Problems" window are only processed and shown for the currently opened file. This in turn means that I no longer have a list of **all** the issues my current project has. With version 11.x I worked around this by building the project, looking at the build output, and clicking through all the files that reported issues and then resolving them.

Now that the file URLs are relative, I cannot do so and must manually search the file in the explorer and open it to resolve the issues.

**2. To Reproduce**

1. Create or open any project that has any CodeCop issue
2. Build the project via Ctrl+Shift+B (or similar)
3. Go to the output window and locate the warnings that were written for the CodeCop issues. They are prefixed with the file name and position where that issue was detected, but only the project-relative part.
4. In previous versions of AL Language, these file/position indicators where fully qualified and thus clickable and allowed me to directly jump to the file to correct it.

**3. Expected behavior**
The file URLs should be absolute.

**4. Actual behavior**
The file URLs are relative.

**5. Versions:**

- AL Language: v12.0.849798
- Visual Studio Code: 1.81.1
- Business Central: n/a
- List of Visual Studio Code extensions that you have installed: n/a

**Comment by BazookaMusic** [comment]
Is it codecop only or compiler diagnostics as well? If all of them are relative, this issue will be fixed in the next release of the preview

**Comment by hemisphera** [comment]
Seems to be fixed with AL language 12.0.85807.

**Comment by BazookaMusic** [comment]
Glad to hear the fix worked and thanks for reporting the issue! I'll close this
