### ISSUE TITLE
AppSourceCop does not detect breaking change

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL#7487]
Please include the following with each issue:

**1. Describe the bug**
Last week we encountered the following error after deploying an update of one our apps to AppSource:

Function ID 1979252384 was called. The object with ID 71096582 does not have a member with that ID.

After some investigation we discovered the AppSourceCop does not report a problem when a function is changed from internal to public AND a return value is added. (The access modifier is probably not the root cause).

The error seems logic, but these things can be overlooked.

Can this be fixed please?

**2. To Reproduce**

For an existing app on AppSource do the following:

1. Look for an existing internal procedure without a return value
2. Change the procedure definition so it has a return value
3. Change the access modifier from internal to public

``` AL

// Before
internal procedure AttachReusablePackagingToLine(var RecordRef: RecordRef)
begin
end;

// After
procedure AttachReusablePackagingToLine(var RecordRef: RecordRef) LineAttached: Boolean
begin
end;
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The AppSourceCop should detect the change above as a breaking change.

**4. Actual behavior**
The AppSourceCop does not report a breaking change. Dependant apps on AppSource fail because the procedure is assigned a new ID.

**5. Versions:**

- AL Language: v11.5.834620
- Visual Studio Code: 1.80.1
- Business Central: BE Business Central 22.4 (Platform 22.0.60033.0 + Application 22.4.59114.59220)
- List of Visual Studio Code extensions that you have installed: only AL Language Extension (others were disabled)

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by hemisphera** [comment]
If the procedure was internal, then it was not visible to anyone outside your app, and thus not part of its public API. AppSourceCop only checks for breaking changes in the public API. Therefore: as far as AppSourceCop is concerned, your method is **new**, and not **changed**.

The only scenario I can think of, where this could happen, is when you are using `internalsVisibleTo`. In which case though I think it is _your_ responsibility to make sure your that your internals and internals-consuming apps are compatible. Because, as stated above, internals are not part of the public API.

**Comment by nndobrev** [comment]
Procedure was internal and moved to public. If you try to move it from public to internal this would be considered as breaking changes and AppSourceCop will be triggered.
