### ISSUE TITLE
AlDoc is not working with DocFx 2.70.1

### ISSUE THREAD

**Issue by esbenk** [microsoft/AL#7488]
When using DocFx v2.70.1 to build the site from aldoc yaml output it reports random errors for the yaml files. Error like

```
C:\src\aldoc\docs\reference\base-application\Page\Microsoft.InventoryMgt.Ledger.Value-Entries-Preview.yml: error InvalidInputFile: Unable to load file 'reference/base-application/Page/Microsoft.InventoryMgt.Ledger.Value-Entries-Preview.yml' via processor 'BusinessCentralApplicationObject': Object reference not set to an instance of an object.
```

The mitigation is to downgrade DocFx to version 2.70.0. Most likely this is caused by an updated dependency in DocFx.

**Comment by esbenk** [comment]
Also tracked here https://github.com/dotnet/docfx/issues/9146

**Comment by MODUSCarstenScholling** [comment]
This is a race condition with parallel executions. A workaround is to set `--maxParallelism 1` for docfx.

**Comment by gregsdennis** [comment]
As mentioned in the docfx issue linked above, a fix has been published for JsonSchema.Net.  It needs to be incorporated into docfx.

**Comment by esbenk** [comment]
Version 2.70.4 of DocFx is fixed. Update with `dotnet tool update -g docfx`
