### ISSUE TITLE
Error AL0183 not raised on * in variable names

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7490]
`?` is not supported in variable names. If it is used, error AL0183 is raised.
However, the rule should apply to `*`, but it does not:

```
    local procedure MyProcedure()
    var
        myInt: Integer;
        my?Int: Integer; // AL0183 raised: Unexpected character '?'
        my*Int: Integer; // AL0183 not raised
    begin
    end;
```

Furthermore, using `*` or `?` in variable names seems to cut off the first part of the variable. 
Compare:
```
    local procedure MyProcedure()
    var
        myInt: Integer;
        //my?Int: Integer; // AL0183 raised
        //my*Int: Integer; // AL0183 not raised
    begin
        Int := 1; // error AL0118, as expected
    end;
```

```
    local procedure MyProcedure()
    var
        myInt: Integer;
        my?Int: Integer; // AL0183 raised
        //my*Int: Integer; // AL0183 not raised
    begin
        Int := 1; // no error!
    end;
```

```
    local procedure MyProcedure()
    var
        myInt: Integer;
        //my?Int: Integer; // AL0183 raised
        my*Int: Integer; // AL0183 not raised
    begin
        Int := 1; // no error!
    end;
```

**Versions:**

- AL Language: 11.5
- Visual Studio Code: 1.81.1

**Comment by esbenk** [comment]
This difference is that ? is not a valid token in AL and the lexer will error on that (same as e.g. ½).  * on the other is a valid token and it is left to the parser to figure whether it is used in the right place. Both cases produces valid diagnostics based on context and is not something we will change.
