### ISSUE TITLE
Error AS0064: Implementation of interface '__MissingInterface__' has been deleted on Enum

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7496]
Today I have updated AL Language extension from 11.5.834620 to 11.6.861323 and when I try to build the app, the error has appeared:
`Error AS0064: Implementation of interface '__MissingInterface__' has been deleted on Enum 'slt_Amount Allocation Target'`. The error is attached to the object itself (to the first line of it).
A pipeline running on the latest version (some 12.x) finished successfully. And till this new public version everything has worked.

The AL code is like:
```al
enum 51612854 "slt_Amount Allocation Target" implements "slt_Amount Allocation Provider"
{
    Caption = 'Amount Allocation Target';
    Access = Public;
    Extensible = true;
    DefaultImplementation = "slt_Amount Allocation Provider" = "slt_Undefined Allocation";
    UnknownValueImplementation = "slt_Amount Allocation Provider" = "slt_Undefined Allocation";

    value(0; Undefined)
    {
        Caption = 'Undefined';
    }
}
```

**Comment by EmilDamsbo** [comment]
Hello, thanks for taking the time to report this issue. We are working to resolve this as quickly as we can, in the meantime consider  temporarily changing back to extension version 11.5.834620. 
I will give a status on here when Microsoft has released a version addressing the problem.

**Comment by EmilDamsbo** [comment]
We have just released a new version, v11.7.863928, which should address this problem. Can you please confirm with me that the new 11.7 version does not reproduce this? @RadoArvay

**Comment by RadoArvay** [comment]
Yes, v11.7 works well. Thank you for quick fix.

**Comment by EmilDamsbo** [comment]
I am glad to hear it! Closing this as fixed
