### ISSUE TITLE
Error while creating a decimal field in the January update

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#75]
Hi,
I had created a decimal field previously in Visual studio code. 
 field(70000011;"Percentage";Decimal)
        {
        }
It worked properly previously. But now when I am creating a simple decimal field in the January update and installing the extension, my web client stops working due to the decimal field created and gives error that 'Server error has occured and the content cannot be displayed'.

![image](https://cloud.githubusercontent.com/assets/24891208/22010137/69e3190e-dcad-11e6-88b1-b67c1c5b8fec.png)

![error 2- while creating decimal field](https://cloud.githubusercontent.com/assets/24891208/22010142/75330b02-dcad-11e6-9b76-d661931e3f2c.PNG)

Kindly give a solution to this.

**Comment by StanislawStempin** [comment]
Could you please try with a different field Id? It could be an Id conflict that is not handled gracefully.
We haven't noticed any issues with Decimal fields in particular.

**Comment by pmohanakrishna** [comment]
I created a decimal field and seems to be working fine.
could be something else. please add details from event viewer.
![decimal](https://cloud.githubusercontent.com/assets/23735402/22015926/2e5a8080-dcca-11e6-8e94-215f022de79f.png)

**Comment by TinaMenezes** [comment]
Hi all,
@StanislawStempin I created another decimal field with different ID which is unique. It is not conflicting. I checked that. But I still get the same error while opening the web client.
field(70000005;"Average Field";Decimal)
        {    }
                           
@pmohanakrishna          
I checked the event viewer. Below are the details:
Type: System.IndexOutOfRangeException
Message: 
Message: Index was outside the bounds of the array.
Logical Control: Name=1001603; Caption=Average Field
Format Column Binder: 27_Item.Control1001603_Format

Kindly suggest.

**Comment by esbenk** [comment]
We are investigating this. Seems like there is a problem with Decimals in some situations.

**Comment by TinaMenezes** [comment]
Hi @esbenk ,
Ok. Thank you.

**Comment by StanislawStempin** [comment]
We have fixed this bug and uploaded a new azure gallery image to http://aka.ms/navdeveloperpreview. Please give it a try.

**Comment by TinaMenezes** [comment]
Hi,
Does this mean that a new VM has to be created for it again ?

**Comment by pmohanakrishna** [comment]
yes, keep backup of your .al files.

**Comment by TinaMenezes** [comment]
Ok. Thanks.

**Comment by TinaMenezes** [comment]
Hi @StanislawStempin,
Its working now. Thank you.
