### ISSUE TITLE
ALDoc :  warning UidNotFound: Unable to find uid "O:Enum::...".

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7504]
Please include the following with each issue:

**1. Describe the bug**
When generating the documentation for our app using ALDoc, we get several warnings of type

` warning UidNotFound: Unable to find uid "O:Enum::ESCA_Printer_Provider".`

**2. To Reproduce**
This is hard to reproduce on a sample AL project, but it seems like the reference enum is not part of the documentation, although it is part of the app file contents.

Here's the definition of the related .al file

```
enum 71096578 "ESCA Printer Provider" implements "ESCA IPrinter Provider"
{
    Access = Internal;
    DefaultImplementation = "ESCA IPrinter Provider" = "ESCA Default Printer Provider";
    Extensible = true;
    value(0; "")
    {
        Caption = '', Locked = true;
    }
    value(1; PrintNode)
    {
        Caption = 'PrintNode', Locked = true;
        Implementation = "ESCA IPrinter Provider" = "ESCA PrintNodeFunctions";
    }
}
```

**3. Expected behavior**
ALDoc should include ALL .al files, avoid above warning.

**5. Versions:**

- AL Language: 13.0.864697

**Comment by esbenk** [comment]
Internal objects are not being documented and hence the id can't be found. You probably have a public method that takes this the enum as an argument. The error comes from the documentation of that method.
In the next update the tool will not create references to internal objects.
