### ISSUE TITLE
PermissionSet object does not allow to include objects with scope OnPrem (AL0296)

### ISSUE THREAD

**Issue by t-tarasiuk** [microsoft/AL#7505]
**1. Describe the bug**
Permission Set objects do not allow to include OnPrem objects as Compiler Error AL0296 occurs.

It was already reported in the following issues, but not yet solved:
https://github.com/microsoft/AL/issues/6765
https://github.com/microsoft/AL/issues/6693

I'm trying to allow users who have limited permissions to work with Personalization functionality. I do not see any standard permission sets that will give access only to the involved objects, so I'm trying to extend my custom permissionset object with the necessary objects. However some of them are with OnPrem scope level, so the compiler does not allow me to include those objects (for example, page "Page Fields"). 

This is not expected behavior for me to have limitations for particular objects in permission sets as basically, I am able to include all objects with * option (for example, permissions page * = X). This still will not work for me, as it will include unnecessary objects and I want to avoid it.

Also, we had no limitations with XML permission sets and were able to include any abject we needed. So, I expect the PermissionSet Object will not bring limitations as well.

**2. To Reproduce**
Create a new project with the following permissionset object:

permissionset 50100 "My Permission Set"
{
    Assignable = true;
    Permissions =
        page "Page Fields" = X;
}

**3. Expected behavior**
Compiler Error AL0296 will not occur in Permission Set or Permission Set Extension objects. 

**4. Actual behavior**
Compiler Error AL0296 occurs: The application object or method 'Page Fields' has scope 'OnPrem' and cannot be used for 'Extension' development.

**5. Versions:**

- AL Language: v11.7.863928
- Visual Studio Code: v1.82.1
- Business Central: 22.x
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by neverbeam** [comment]
We run into the same issue with AL0296 being fired for permission set for OnPrem Tables. We copied D365Basic which contains a lot permission on OnPrem tables.

**Comment by thloke** [comment]
Thanks for the suggestion. We've discussed this internally and have agreed that this is an improvement request that needs to be prioritized. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by t-tarasiuk** [comment]
I've added the following idea [Extend PermissionSet object to allow adding objects with OnPrem scope](https://experience.dynamics.com/ideas/idea/?ideaid=3572bd11-d20e-ef11-9899-000d3ae29eff#).

Please feel free to vote.
