### ISSUE TITLE
Wrong parameter for GenJnlCheckLine.IsDateNotAllowed in codeunit 395 "FinChrgMemo-Issue"

### ISSUE THREAD

**Issue by Frantic42** [microsoft/AL#7507]
Finance Charge Memo with a Name field length over 20 characters cannot be issued due to an overflow.
When CheckVATDate runs in c395, the following code is executed:
`if GenJnlCheckLine.IsDateNotAllowed(FinChrgMemoHeader."VAT Reporting Date", SetupRecID, **FinChrgMemoHeader.Name**) then`

The overload for IsDateNotAllowed that accepts a third parameter expects a Code[20] value for TemplateName:
`procedure IsDateNotAllowed(PostingDate: Date; var SetupRecordID: RecordID; **TemplateName: Code[20]**) DateIsNotAllowed: Boolean`

This can be reproduced by issuing a Finance Charge Memo with a Name containing more than 20 characters.

**Comment by dannoe** [comment]
Wrong repository. Besides, this was already fixed in BC22.2.
