### ISSUE TITLE
Region folding / stickyscroll not working

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7516]
Please include the following with each issue:

**1. Describe the bug**

Since a few months, regions in AL files seem to be troublesome. (Already reported in #7361, but no real improvements in the latest vsix). In a lot of projects / AL files, the regions simply don't render well (no fold / unfold option is available), resulting in the stickyscroll feature not to work either.

**2. To Reproduce**

I often discover regions to work when reloading the window, but after working for a while, they stop to be working.

One scenario which is sometimes troublesome is the encapsulation of **regions within regions**.
We often use this pattern, to keep publishers close to it's parent functions. This used to work in all earlier AL vsix versions ...

```
 #region UpgradeReportLayoutSetupDescription
    internal procedure UpgradeReportLayoutSetupDescription()
    var
        UpgradeImpl: Codeunit "ESCA Upgrade Impl.";
    begin
        if UpgradeTag.HasUpgradeTag(ReturnReportLayoutSetupDescriptionUpgradeTag()) then
            exit;

        UpgradeImpl.UpdateReportLayoutSetupDescriptions();

        UpgradeTag.SetUpgradeTag(ReturnReportLayoutSetupDescriptionUpgradeTag());
    end;

    #region ReturnReportLayoutSetupDescriptionUpgradeTag
    internal procedure ReturnReportLayoutSetupDescriptionUpgradeTag(): Text[250]
    begin
        exit('ESCR-7306-ReportLayoutSetupDescription-20230913');
    end;
    #endregion ReturnReportLayoutSetupDescriptionUpgradeTag   
    #endregion UpgradeReportLayoutSetupDescription
```

Changing to below structure might resolve the problem (but is not what we'd like to achieve)

```
 #region UpgradeReportLayoutSetupDescription
    internal procedure UpgradeReportLayoutSetupDescription()
    var
        UpgradeImpl: Codeunit "ESCA Upgrade Impl.";
    begin
        if UpgradeTag.HasUpgradeTag(ReturnReportLayoutSetupDescriptionUpgradeTag()) then
            exit;

        UpgradeImpl.UpdateReportLayoutSetupDescriptions();

        UpgradeTag.SetUpgradeTag(ReturnReportLayoutSetupDescriptionUpgradeTag());
    end;
    #endregion UpgradeReportLayoutSetupDescription

    #region ReturnReportLayoutSetupDescriptionUpgradeTag
    internal procedure ReturnReportLayoutSetupDescriptionUpgradeTag(): Text[250]
    begin
        exit('ESCR-7306-ReportLayoutSetupDescription-20230913');
    end;
    #endregion ReturnReportLayoutSetupDescriptionUpgradeTag   
```

**3. Expected behavior**

Regions, including nested regions, should always render.

**5. Versions:**

- AL Language: 11.7.863928
- Visual Studio Code: Version: 1.82.2 (user setup)

**Comment by EmilDamsbo** [comment]
Hi, Fvet, as mentioned in #7361 by Jesper, the fix is available from version 12+, which will be released soon with 2023 Wave 2. You could either 1. install the pre-release version from VS Code marketplace or 2. wait not-so-long-I-promise for the 12.0 to be generally available.

**Comment by fvet** [comment]
@emildamsbo Forgot to menion that I had tested on the Prerelease version as well without any luck.

Just tried again with AL 12.x version, and some regions (in this animation, it's the first region that conflicts) just don't collapse, resulting in the stickyScroll not to work either I suppose :(

https://github.com/microsoft/AL/assets/25268332/0c7a2ecc-3be2-4160-93a7-4cbdeb480462
