### ISSUE TITLE
InternalServerError when downloading symbols on production environment

### ISSUE THREAD

**Issue by olgabast** [microsoft/AL#7520]
**1. Describe the bug**
When I'm downloading symbols from sandbox environment it works fine.
Attempt to download from production environment throws InternalServerError.

```
[2023-09-29 23:26:25.92] Sending request to https://api.businesscentral.dynamics.com/v2.0/Production/dev/metadata
[2023-09-29 23:26:48.70] Error: An error occured while processing the request.
Request ID: 3a634f7b-5114-4ab3-a498-c6df010168c3
Session ID: 348f0811-9536-4f4b-918e-5518d2f91526

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2023-09-29 23:26:48.74] The request for path /v2.0/Production/dev/metadata failed with code InternalServerError. Reason: Internal Server Error
```

**2. To Reproduce**
- Create new project with AL:Go! command using last BC version and cloud server
- Change environmentName in launch.json to "Production"
- Download symbols

**3. Expected behavior**
Symbols downloaded

**4. Actual behavior**
InternalServerError

**Comment by joemattar** [comment]
How did you solve this?

**Comment by olgabast** [comment]
@joemattar I didn't, I learned that you're not supposed to do this. You can't develop on production environment, you can only install the compiled extension there. Please take my words with a grain of salt, I am not an expert in this matter.

**Comment by joemattar** [comment]
That could be it, thank you so much for your feedback! I will try again after creating a sandbox/dev instance.
