### ISSUE TITLE
AL version 12: Warnings can't be removed

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#7522]
**Issue:**
After AL has been upgraded to version 12 I get few warnings (from old developments before me):
_The identifier '"Item No. "' cannot have any leading or trailing spaces. This warning will become an error when targeting a runtime with version '13.0' or higher._

**To Reproduce**

-Update to AL version 12 
-Add a field with some leading or ending blank space.
-If you try to add in app.json  "suppressWarnings": ["AL0771"] it will just fail because:

_'suppressWarnings' is not available in runtime version '2.2'. The supported runtime versions are: '6.0' or greater._

**Expected behavior**
Fix this issue

**Comment by PooyaKharamesh** [comment]
as mentioned in the error message the suppress functionality is introduced in runtime version 6.0 and later. To use this functionality you should change the runtime version in app.json to 6.0 or above.

**Comment by txeriff** [comment]
> as mentioned in the error message the suppress functionality is introduced in runtime version 6.0 and later. To use this functionality you should change the runtime version in app.json to 6.0 or above.

Hi PooyaKharamesh, 

-I can't switch it because I'm in BC13.
-I can't supress the warnings either when before these weren't an issue.
