### ISSUE TITLE
Export to New Syntax file not showing (Sept Update)

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#753]
Hi

I have runt he exporttonewsyntax command in the Container powershell promt  and i got the below result

![image](https://user-images.githubusercontent.com/26792519/31433378-bd34724a-ae96-11e7-8251-cd7177699cdd.png)

But when i went to the folder and checked i cannot see the file the folder is empty as shown below:

![image](https://user-images.githubusercontent.com/26792519/31433416-e042d1be-ae96-11e7-8639-b61df9c17d85.png)

Apart from this i also found that if the path is C:\demo then the file is showing in the folder. Is it not possible to export in any other folder apart from C:\demo?

Please suggest me.

Thanks & regards 
Varun Reddy

**Comment by StanislawStempin** [comment]
Are you possibly confusing C:\ drive within the container with the C:\ drive on the host machine?

**Comment by bachii1010** [comment]
Hi,

OK are you saying that the C:\ drive within the container and the c:\ drive in the VM is different so since the D:\ drive is in VM we cannot access it.

If yes how can we use the D:\ drive in VM in container?

Please suggest?

**Comment by HunterFeltman-MSFT** [comment]
Yes, the container file system is logically separate from the VM's. 
So executing any commands that create files from within the container not immediately place them on the VM's file system.

That being said, you can copy things between the container and the VM using the docker utilities.
Here is a link to the docker documentation on the cp (copy) command: [https://docs.docker.com/engine/reference/commandline/cp/](https://docs.docker.com/engine/reference/commandline/cp/)
