### ISSUE TITLE
Syntax Highlithing does not work in the Preview of Changes for all files [AL Language Syntax Highlights - Azure DevOps]

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7530]
**1. Describe the bug**
Currently the Syntax Highlighting isn't applied in the preview of the changes of a PR.
Only when I select one specific file, then I'm getting the syntax hightlighting

**2. To Reproduce**

1. Install the extension https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.allanghighlights for DevOps
2. Create a PR with multiple .al files.
3. There is not syntax highlighting

![image](https://github.com/microsoft/AL/assets/56249171/8bc83524-fa7f-4abc-a8af-c1f850e021ee)

**3. Versions:**

- AL Language Syntax Highlights for Microsoft Dynamics 365 Business Central 12.1.878832 (Latest)

**Comment by pri-kise** [comment]
it could be that this isn't related to the  AL Language.
Maybe this is a general Azure DevOps issue.
I wasn't able to find any other documentation on this topic.
https://www.reddit.com/r/azuredevops/comments/sxpogh/syntax_highlighting_in_diff_view/

**Comment by EmilDamsbo** [comment]
Hi, thanks for being an early adopter of the AL Syntax Highlighting extension for Azure DevOps. We appreciate your feedback, unfortunately this is a limitation in the Azure DevOps product as you mentioned. This behaviour is no different from the preview for other languages like C# or Java in the same context. To get syntax highlighting, you can click the files in the left-side pane of the Files tab:
![image](https://github.com/microsoft/AL/assets/67266681/0226567b-c756-43de-8358-57ca881dfbdb)

![image](https://github.com/microsoft/AL/assets/67266681/5132815c-c9bc-406e-950f-5ce8a0cef28f)


I hope this helps!

**Comment by pri-kise** [comment]
@EmilDamsbo you have any kind of official documentation, that this is a limitation of azure DevOps?
I really searched through the web, but couldn't find any reference.

If this is a limitation of Azure DevOps, then I will close this issue an open an Idea for Azure DevOps

**Comment by pri-kise** [comment]
I created an idea now for azure devops
https://developercommunity.visualstudio.com/t/Add-syntax-highlighting-for-the-diff-vie/10483974

**Comment by EmilDamsbo** [comment]
I have not found it documented anywhere, but the behaviour is exhibited for all languages I have tried in Azure DevOps in the webclient. I upvoted your idea too :)
