### ISSUE TITLE
ShowCaption does not work for RichContent

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#7532]
**1. Describe the bug**
The Property `ShowCaption `is ignored for fields with `ExtendedDatatype = RichContent`.

**2. To Reproduce**
Implement RichContent field and set ShowCaption to false:
``` AL
pageextension 50110 CustomerCardExt extends "Customer Card"
{
    layout
    {
        addafter(General)
        {
            group(DoodleBoard)
            {
                Caption='Doodel Board';
                field(dummyText; dummyText)
                {
                    Caption = 'Dont show this';
                    ShowCaption = false;
                    ApplicationArea = All;
                    MultiLine = true;
                    ExtendedDatatype = RichContent;
                }

            }
        }
    }
    var
        dummyText: Text;
}
```
**3. Expected behavior**
I expect the caption to be hidden like in every other control.

**4. Actual behavior**
Caption is showed:
![image](https://github.com/microsoft/AL/assets/18051656/9e58d33d-983d-46aa-8f0f-ec8a470351e8)

**5. Versions:**

- AL Language: 12.0.13.24028
- Visual Studio Code: 1.82.2
- Business Central: Version: W1 23.0 (Plattform 23.0.12789.0 + Anwendung 23.0.12034.12816)
- List of Visual Studio Code extensions that you have installed: ms-dynamics-smb.al

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
Hi, unfortunately this is not in the scope of this repository, as it relates to the rendering in the web client. I have instead opened a ticket internally for our web client team to make sure that `ShowCaption = false` is respected in Rich Text Editor controls in future.

**Comment by ChrisBlankDe** [comment]
This issue has been fixed with 24.x.
