### ISSUE TITLE
Group Visibility breaks RichContent Control in Factboxes

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#7533]
**1. Describe the bug**
If a FactBox contains a group which contains a RichContent control has the `Visible` property configured then `ExtendedDatatype = RichContent` is ignored and the control falls back to multiline.

**2. To Reproduce**
Create a CardPart Page which contains one group with configured visibile property.
the group contains a RichContent  Control

Add the CardPart Page as Factbox on another Page

``` AL
pageextension 50110 CustomerCardExt extends "Customer Card"
{
    layout
    {
        addfirst(factboxes)
        {
            part(DoodleFactbox; DoodleFactbox)
            {
                ApplicationArea = All;
                Caption = 'Doodle Factbox';
            }
        }
    }
}
page 50110 "DoodleFactbox"
{
    PageType = CardPart;
    layout
    {
        area(Content)
        {
            group(General)
            {
                Visible = DoodleBoardVisible; //This line breaks the rich editor
                ShowCaption = false;
                field(RichControl; dummyText)
                {
                    Caption = 'Rich Text', Locked = true;
                    ShowCaption = false;
                    MultiLine = true;
                    ExtendedDatatype = RichContent;
                    Editable = false;
                }
            }
        }
    }
    trigger OnOpenPage()
    begin
        DoodleBoardVisible := true;
        dummyText := '<b>Hello World</b>';
    end;

    var
        dummyText: Text;
        DoodleBoardVisible: Boolean;
}
```
**3. Expected behavior**
I expect that the rich content control renders the html fine:
This can be achived by removing or comment out the Visible Property
![image](https://github.com/microsoft/AL/assets/18051656/c3604c06-929a-488f-8a58-06719541a27d)

**4. Actual behavior**
Control falls back to normal multiline content
![image](https://github.com/microsoft/AL/assets/18051656/fbfd0f1e-8e74-4e7e-8907-988edfc2f214)

**5. Versions:**

- AL Language: 12.0.13.24028
- Visual Studio Code: 1.82.2
- Business Central: Version: W1 23.0 (Plattform 23.0.12789.0 + Anwendung 23.0.12034.12816)
- List of Visual Studio Code extensions that you have installed: ms-dynamics-smb.al

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
Hi, thanks for reporting this issue. Unfortunately this is not in the scope of this repository, as it relates to the rendering in the web client. I have instead opened a ticket internally for our web client team to make sure that the `Visible` property does not break the rendering of the rich text control. The fix will be shipped in a future update of Business Central.
