### ISSUE TITLE
AL is marking as error things that should be warnings

### ISSUE THREAD

**Issue by amunoz-ldr** [microsoft/AL#7534]
**1. Describe the bug**

In a BC16 project, with the new al version [12.0.875970] we are getting this error:
`Table 'Product Group' is removed. Reason: Product Groups became first level children of Item Categories.. Tag: 15.0.`

With the previous one [11.7.863928], it’s just a warning as it should be:
`Table 'Product Group' is removed. Reason: Product Groups became first level children of Item Categories.. Tag: 15.0. This warning will become an error in a future release.`

**Comment by naradae** [comment]
We have also seen this problem in a BC16 repo

**Comment by frottke** [comment]
We have the same problem, is there already a workaround?

**Comment by blrobl** [comment]
This warning turned into an error with release BC 16.0 because the Table 'Product Group' was obsoleted in the base app. As suggested in the message, use the 'Item Category' table instead.
