### ISSUE TITLE
Quick fix for parenthesis (AL0008) is not working correctly

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7535]
**1. Describe the bug**
Quick fix for adding parenthesis is not working correctly. 
If you have comments above the line, you want to fix, it removes those comments. See image bellow

![Animation](https://github.com/microsoft/AL/assets/16342128/fa90959c-f003-48d2-a036-be0c3703d0e3)

**2. To Reproduce**
see above

**3. Expected behavior**
It should not remove comments, but just add parenthesis as expected

**4. Actual behavior**
Removes comments & adds parenthesis

**5. Versions:**

- AL Language:  v13.0.878831 (pre-release), the same behavior with stable version
- Visual Studio Code: 1.82.3

**Comment by BazookaMusic** [comment]
This is definitely because the action creates a new syntax without the previous trivia. Needs to be fixed
