### ISSUE TITLE
al.compilerOptions.outFolder does not work as expected for "Publish full dependency tree..." command

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7536]
AL Language v12.0.875970

We have a workspace with couple of folders (apps). I have set `al.compilerOptions.outFolder` property in a code-workspace configuration file.
```json
"al.compilationOptions": {
	"outFolder": "../.albuilds"
}
```
When I run a general build command for any app from within the folder, the created app file is placed to the `outFolder` correctly.
But when I run `Publish full dependency tree` command, only the _top_ app is placed to `outFolder` and all apps that the _top_ app depends on are placed to the individual apps folders as before (ignores `outFolder` set up).
Is it "by design"? Bug? Or have I set up anything incorrectly?

**Comment by RadoArvay** [comment]
I have been forced to remove `al.compilerOptions.outFolder` setup, because there are other issues and I am not able to find out a correct way to set up a relative path of the property for the multiroot workspace.

For example:
```
Publishing AL application using launch configuration 'nnn'.
Sending request to http://nnnnn/BC/dev/metadata?tenant=default
Error: File ../.albuilds\nnnnnn.dep.app does not exist.
```
But _nnnnnn.dep.app_ file exists and it is placed in _.albuilds_ folder.

Would it be possible to update a documentation how to use this property and how to set up relative paths in a workspace?

**Comment by DominicSaladin** [comment]
Is there a solution to this problem or is there any fix coming soon?

**Comment by DominicSaladin** [comment]
Any updates? :(

**Comment by Ajef** [comment]
I have found an easy workaround:
In the settings.json you can use the VSCode variable ${workspaceFolder}.

> ```
> "al.compilationOptions": {
> 
>         "outFolder": "${workspaceFolder}\\bin"
>     }
> ```

**Comment by thpeder** [comment]
There will be an update coming in the next version of the Pre-Release.

**Comment by RadoArvay** [comment]
Isn't there any chance to support **Visual Studio Code variables** in _User_ or _Workspace_ settings? For this `outFolder` property and other ones...

**Comment by thpeder** [comment]
> Isn't there any chance to support **Visual Studio Code variables** in _User_ or _Workspace_ settings? For this `outFolder` property and other ones...

Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by RadoArvay** [comment]
> There will be an update coming in the next version of the Pre-Release.

What version was meant by that "Pre-Release"?
Because couple of months after I am trying to set up it in the current public 13.0.964488 and still it does not work for me. Or - can someone describe the correct setup for this property?

**Comment by RadoArvay** [comment]
It seems it works finally.
