### ISSUE TITLE
BC Server warning with Enum Object 'SII Doc. Upload State Document'

### ISSUE THREAD

**Issue by fcrespoprofand** [microsoft/AL#7537]
**1. Describe the bug**
The Server Instance is logging a warning for duplicated Enu, incorrectly:

`Server instance: BC
Category: Metadata
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9c221358-5422-4765-b553-b58bd32f6a02
EventTime: 10/09/2023 09:06:51
Message The object name **'SII Doc. Upload State Document'** can only appear once for the type 'Enum'. The same object exists in both extension ('437dbf0e-84ff-417a-965d-ed2bb9650972' 'Base Application', Publisher: Microsoft, Package ID: 270893f2-1c4f-400a-bc49-ae77891fd804, Runtime Package ID: 3dc678da-9d75-4b66-9994-63ec6d182364, Scope: Global, Version: 21.9.58412.0) and in extension ('437dbf0e-84ff-417a-965d-ed2bb9650972' 'Base Application', Publisher: Microsoft, Package ID: 270893f2-1c4f-400a-bc49-ae77891fd804, Runtime Package ID: 3dc678da-9d75-4b66-9994-63ec6d182364, Scope: Global, Version: 21.9.58412.0).
ProcessId: 1204
Tag: 0000ES3
ThreadId: 8
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: `

The problem is that there are 2 enums:

- enum 10756 "SII Doc. Upload State Document Type"
- enum 10755 "SII Doc. Upload State Document Source"

BC is truncating the name to 30 characters and this way it looks there are two duplicated enums  "SII Doc. Upload State Document".

Similar issue has been solved in [https://github.com/microsoft/AL/issues/6691]

**2. To Reproduce**
Just Start a BC instance of the Spanish localizartion. Base Application will raise the Warning in the Windows Event Viewer several times before get started.

**3. Expected behavior**

Correct Base Application to truncate the name of enum and change their names to prevent duplicated names.

This way no warning will be written in logs.

**4. Actual behavior**
Explained above.

**5. Versions:**

- AL Language: 12.0.875970
- Visual Studio Code: 1.83.0
- Business Central: 21.9

**Comment by pri-kise** [comment]
@fcrespoprofand you should create a support request to get this fixed.
This is clearly a bug and can lead to errors in the future.

Therefore use the normal support channels to get this addressed by microsoft.

**Comment by fcrespoprofand** [comment]
Hi @pri-kise I though this was the right channel to submit a support request. So... where should I submit it?

Thanks!

**Comment by pri-kise** [comment]
This repository is for Bug Reports with AL Language Extension.

For other BugReports check out the following link:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/technical-support#summary-of-where-to-file-bugs-and-issues

e.g. for BC SaaS Customers use the partner center and create a support request on behalf of this customer.

**Comment by pborring** [comment]
As commented, app bug that should be logged elsewhere, thus closing this entry

**Comment by fcrespoprofand** [comment]
This is exactly the same error described in [issue 6691](https://github.com/microsoft/AL/issues/6691) but with a different enum. Why it was solved in this forum but not current ticket?

I've accessed the link provided by @pri-kise but I'm a Customer and cant access to Microsoft Support for this kind of issue. 🤷‍♂️

**Comment by pborring** [comment]
I've forwarded this internally
