### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by stanuj** [Microsoft/AL#754]
Hello,

I'm getting an error while pressing F5 i.e. error AL1022: A package with publisher 'Microsoft', name 'System', and a version compatible with '10.0.0.0' could not be found in the package cache folder 'e:\Nav Extension Example\New Folder\.alpackages'
Error: The package could not be created.

My app.json file is:
{
  "id": "e2c4c4be-87eb-46ea-af54-55ca01e861e2",
  "name": "New Extension",
  "publisher": "stanuj",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "10.0.0.0",
  "application": {
    "version": "10.0.0.0",
    "locale": "W1"
  },
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

My launch.json file is:
{
	"version": "0.2.0",
	"configurations": [
		
		{
			"type": "al",
			"request": "launch",
			"name": "stanuj",
			"server": "http://localhost:7046/DynamicsNAV100",
			"serverInstance": "DynamicsNAV100",
			"tenant": "default",
			"authentication": "Windows",
			"startupObjectId": 22
		}
	]
}

Please help me to sort out this problem.
Thanks in advance.

**Comment by esbenk** [comment]
What happens if you choose "AL: Download symbols" from the Command Palette? 

What version of the server are running? The latest version contains symbols with version 11.0.0.0.

**Comment by stanuj** [comment]
I got no errors while downloading reference symbols.

I'm also using latest version with 11.0.0.0, to remove error I only changed it to 10.0.0.0
Please look below image:

![vsc information](https://user-images.githubusercontent.com/32701699/31480481-ab578120-af3b-11e7-911e-233a4d68fe3d.PNG)

**Comment by esbenk** [comment]
What is the content of

'e:\Nav Extension Example\New Folder.alpackages'

**Comment by stanuj** [comment]
contents in this folder are:

![vsc information2](https://user-images.githubusercontent.com/32701699/31482932-fad9cc88-af47-11e7-8e84-627f225fdc75.PNG)

**Comment by StanislawStempin** [comment]
It looks like we are constructing a path without the last backslash. Can you retry in a folder structure that doesn't contain spaces?

**Comment by stanuj** [comment]
Hi StanislawStempin,

It contains last backslash like e:\Nav Extension Example\New Folder\.alpackages,
while pasting error, unfortunately , it was deleted.

**Comment by StanislawStempin** [comment]
How did you create the environment? Did you use aka.ms/navdeveloperpreview?

**Comment by stanuj** [comment]
Yes, i used aka.ms/navdeveloperpreview.

**Comment by StanislawStempin** [comment]
Are you still hitting this issue?

**Comment by stanuj** [comment]
No, this is solved. Thanks
