### ISSUE TITLE
AL client: couldn't create connection to server

### ISSUE THREAD

**Issue by MarcusFabian** [microsoft/AL#7540]
Type: <b>Bug</b>

Only happens on my Mac. Doesn't happen on a Windows installation:

Error - 14:32:43] AL client: couldn't create connection to server.
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:441:11)
    at Object.spawn (node:child_process:752:9)
    at transports (/Users/marcu/.vscode/extensions/ms-dynamics-smb.al-12.0.875970/dist/webpack:/al/node_modules/vscode-languageclient/lib/node/main.js:426:46)
    at x.connection [as createConnection] (/Users/marcu/.vscode/extensions/ms-dynamics-smb.al-12.0.875970/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:1052:15)
    at x.start (/Users/marcu/.vscode/extensions/ms-dynamics-smb.al-12.0.875970/dist/webpack:/al/node_modules/vscode-languageclient/lib/common/client.js:617:19)

Extension version: 12.0.875970
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|24.00GB (1.62GB free)|
|Process Argv|--crash-reporter-id 750f918f-4026-4c5f-b91f-6680c961c177|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by antonbasecloud** [comment]
Having the same issue on a new installation on Mac OS

**Comment by nkalichynskyi** [comment]
Same here, works fine on Ubuntu but not on Mac OS(M3 Pro Macbook Pro)

**Comment by esbenk** [comment]
Please try the solution described here #7506. It sounds like the samme issue.

**Comment by antonbasecloud** [comment]
Manual install of rosetta solved it :)

/usr/sbin/softwareupdate --install-rosetta
