### ISSUE TITLE
Unable to attach session to vs code 

### ISSUE THREAD

**Issue by minaskats** [microsoft/AL#7543]
**1. Describe the bug**
Unable to attach a session to debug, from a customers online tenant , with error message "The Launch.json is invalid."

**2. To Reproduce**
Using the new feature of BC version 23 "Attach debugger to this session" , I am logging into a customers tenant (SAAS) , using the GDAP user of partner center. Then ,into the project we want to debug ,I created the appropriate launch.json setting* ,  where XXX is the customers tenant ID and userid the user_XXXXXX from partner center (GDAP).
We log into customers tenant & sandbox environment which has BC ver 23 , and use the option "Attach debugger to this session" from the Help & Support page. Then VS Code pops ups, and asks to use the current project or create a new one. Using the option current project & Regular Debugging , we get an error message saying "The Launch.json is invalid."
Note that the user_xxxxxx has been assigned the D365 ATTACH DEBUG permission set.

*Launch.json setting
{
"name": "Attach: Microsoft cloud sandbox",
"type": "al",
"request": "attach",
"environmentType": "Sandbox",
"environmentName": "NameOfCustomersSandBoxEnv",
"breakOnError": true,
"breakOnRecordWrite": false,
"numberOfSqlStatements": 10,
"breakOnNext": "WebClient",
"sessionId": TheSessionOfmyuser,
"tenant": "CustomersTenantID_XXXX",
"userId": "user_XXXX"
}

**3. Expected behavior**
It should not give an error message.

**4. Actual behavior**
An error message saying "The Launch.json is Invalid."

**5. Versions:**

- AL Language: v12.1.883011
- Visual Studio Code: 1.83.1
- Business Central: W1 23.0.12034.12676
- List of Visual Studio Code extensions that you have installed:

**Comment by blrobl** [comment]
Hi, there is a strong validation on the launch.json file being a JSON object for parsing reasons, and otherwise it will throw such an exception. This can be for example, if you have a comment or a trailing comma at the end of the configuration. I don't see that is the case from your example, but could this be the case? Nonetheless, we'll work on relaxing this validation.

**Comment by MarcelMo** [comment]
See https://github.com/microsoft/AL/issues/7554
23.0.12034.12676 is broken
