### ISSUE TITLE
New outFolder builds, but fails at publishing

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/AL#7544]
**1. Describe the bug**
The new outFolder builds the app correctly, but does not find the file when publishing

**2. To Reproduce**
1. Configure a outFolder in the top folder, for example: "../app-output".
2. Build App
3. Publish

**3. Expected behavior**
Publish with the app file in "../app-output"

**4. Actual behavior**
`Error: File ../app-output\Publisher_AppName_1.0.0.0.app does not exist.`

**5. Versions:**
- AL Language: v12.1.883011
- Visual Studio Code: 1.83.1

**Comment by BazookaMusic** [comment]
Can you try specifying the path as '..\app-output' to see if it works. Looks like a path normalization issue

**Comment by DominicSaladin** [comment]
Nope, that didn't work. I change the outFolder to `"outFolder": "..\\app-output"`, but I get the same error, just with the updated path: `Error: File ..\app-output\Publisher_AppName_1.0.0.0.app does not exist.`

**Comment by pborring** [comment]
Seems like same as https://github.com/microsoft/AL/issues/7536

**Comment by DominicSaladin** [comment]
@BazookaMusic So, will this error be fixed in the near future?

**Comment by qutreson** [comment]
Closing as duplicate of #7536 which has been accepted, but hasn't been fixed yet.
