### ISSUE TITLE
IntelliSense does not work in table.fields part

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7546]
When I want to use IntelliSense anywhere inside `fields` part (root, field, trigger level) of `table` (or `tableextension`) object to select properties, variables type, or anything else, it stucks on _Loading..._ text.
When I write `Rec.` and use IntelliSense after that, it works. Also there is no problem outside of `fields` part.

AL Language: v12.1.883011 - but I have already had the issue in v11.x
VSCode: v1.83.1

**Comment by RadoArvay** [comment]
At first, one note: as I wrote, it happens inside `table` and `tableextension` objects, not `page`.
And yes, it happens in all of them.The project is a workspace with couple of apps.
I will do more tests on my environment - I will try a new project; I will try to disable extensions (I did not want to do it because of mix of many active and disabled ones), and so on...I let you know.

**Comment by RadoArvay** [comment]
Hard to reproduce.
I have found out that it works for a while, but in some moment it stops and I need to reload window (and it works again after that).
I do not know when "the moment" is. After couple of (or specific) pre-compiler errors, or.....

**Comment by thloke** [comment]
Considering that this is a hard to reproduce bug, there's not much we can do on our end. If we can get a consistent repro we can revisit this, but for now I will close the issue.
