### ISSUE TITLE
Microsoft_Statistical Accounts_22.5.59966.60187 : Codeunit 2624 : Stat. Acc. Jnl. Line Post

### ISSUE THREAD

**Issue by ClintonSaundersSeeSide** [microsoft/AL#7548]
Please include the following with each issue:

**1. Describe the bug**
When writing extensions that run the above codeunit (and therefor executing the OnRun trigger), a "Record already exists in the Statistical Ledger Entry table". The normal posting routine that starts with Codeunit 2626 : Stat. Acc. Post. Batch does not produce the same error because it does not use the OnRun trigger in codeunit 2624.

**2. To Reproduce**
Write code to populate the "Statistical Acc. Journal Line" table, then run codeunit 2624 and passing the newly created Journal Line. 

``` AL
        StatsJnlLine.Init();
        StatsJnlLine."Document No." := GenJnlLine."Document No.";
        StatsJnlLine."Posting Date" := GenJnlLine."Posting Date";
        StatsJnlLine.Description := StrSubstNo(DescrTxt, VendLedgEntry."Policy No.");
        StatsJnlLine.Amount := AppliedAmount;
        StatsJnlLine."Shortcut Dimension 1 Code" := VendLedgEntry."Global Dimension 1 Code";
        StatsJnlLine."Shortcut Dimension 2 Code" := VendLedgEntry."Global Dimension 2 Code";
        StatsJnlLine."Dimension Set ID" := VendLedgEntry."Dimension Set ID";
        StatsJnlLine.Insert();

        Codeunit.Run(Codeunit::"Statistical Jnl. Post Line", StatsJnlLine);
        StatsJnlLine.Delete();

I believe the problem is in Function "internal procedure PostLine(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var NextEntryNo: Integer; TransactionNumber: Integer)", specifically the following two lines:

        StatisticalLedgerEntry."Entry No." := NextEntryNo;
        NextEntryNo += 1;

I believe that the problem will be resolved if these two lines are swapped around.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
A new Statistical Ledger Entry should be created

**4. Actual behavior**
A "Record Already exists in the Statistical Ledger Entry Table" is produced, becauase the system tries to use the last Entry No. in the Statistical Ledger Entry table as the Entry No for the new entry.

**5. Versions:**

- AL Language: 12.1
- Visual Studio Code: 1.83.1
- Business Central: 22.5.59966.60565
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
