### ISSUE TITLE
The multi-part identifier could not be bound

### ISSUE THREAD

**Issue by RodrigoPuelma** [microsoft/AL#7549]
**1. Describe the bug**
I set up a BC sandbox version 23.0.12034.12676 and during runtime I get the error below when running a query that joins the customer ledger entry table and the sales invoice line table and has a reference to 2 table extension fields (MyField1 and MyField2) in the sales invoice line table:

An unexpected error occurred after a database command was cancelled.

SQL error message:
The multi-part identifier "SalesInvLine_ext.MyExt MyField1$b719c353-c8ea-4707-acc8-470fc2dae028" could not be bound.
The multi-part identifier "SalesInvLine_ext.MyExt MyField1$b719c353-c8ea-4707-acc8-470fc2dae028" could not be bound.
The multi-part identifier "SalesInvLine_ext.MyExt MyField2$b719c353-c8ea-4707-acc8-470fc2dae028" could not be bound.
Statement(s) could not be prepared.

I did not have this issue before setting up a BC sandbox with the latest version. 

**2. To Reproduce**
1. Add a couple of table extension fields to base table.
2. Create query that joins another base table with the extended base table and includes the table extension fields.
3. Run query.

``` AL
query XXXXXXXX "MyExt Query"
{
    Access = Internal;
    Caption = 'MyExt Query';
    DataAccessIntent = ReadOnly;
    Permissions = tabledata "Cust. Ledger Entry" = r, tabledata "Sales Invoice Line" = r;
    QueryType = Normal;

    elements
    {
        dataitem(CustLedgerEntry; "Cust. Ledger Entry")
        {
            DataItemTableFilter = "Document Type" = const(Invoice);

            column(CustomerNumber; "Customer No.")
            {
            }
            column(CurrencyCode; "Currency Code")
            {
            }
            column(RemainingAmount; "Remaining Amount")
            {
            }
            dataitem(SalesInvLine; "Sales Invoice Line")
            {
                DataItemLink = "Document No." = CustLedgerEntry."Document No.";
                SqlJoinType = InnerJoin;

                column(SalesInvNumber; "Document No.")
                {
                }
                column(SalesInvLineNumber; "Line No.")
                {
                }
                column(MyField1; "MyField1")
                {
                }
                column(MyField2; "MyField2")
                {
                }
                column(AmountIncludingVAT; "Amount Including VAT")
                {
                }
            }
        }
    }
}
```

**3. Expected behavior**
Query should be able to join base table with table extension without throwing error.

**4. Actual behavior**
Error mentioned above is thrown.

**5. Versions:**
- AL Language: v13.0.878831
- Visual Studio Code: 1.83.1
- Business Central: 23.0.12034.12676

**Comment by BazookaMusic** [comment]
Unfortunately, this is a runtime issue and not an issue with the AL Compiler. On our side, I will create a bug for the relevant team to speed up the process as this seems to be a dangerous bug related to SQL query generation. On your side, I suggest that you open a support case or file a bug in Collaborate, to be able to track the progress on this bug and to add priority to it.

To open a support case, you can:

Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

You can refer them to the internal bug #488241.

**Comment by RodrigoPuelma** [comment]
For anyone else seeing this:

I got a reply in Yammer that helped me solve this issue. 

As shown in my example code in OP, there is a reference to the flowfield remaining amount from the customer ledger entry table. This is what is actually causing the problem and by removing that field from the query, I get no error. The problem for me is that remaining amount is the fundamental for the query to begin with.
