### ISSUE TITLE
Compilation Error: Input string was not in a correct format

### ISSUE THREAD

**Issue by rslovak** [Microsoft/AL#755]
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
Error: The package could not be created.
[Error - 2:26:49 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeLens' failed with error: 'Input string was not in a correct format.'

The problem is with this block of code:
![image](https://user-images.githubusercontent.com/32643537/31447090-681a8a1e-aea1-11e7-99cf-a15f07a28bda.png)

Roman

**Comment by thpeder** [comment]
Hi @rslovak, 
I tried making the minimum codeunit and table, for the objects you reference, that makes that code compile but I'm not able to reproduce your problem with codelens.
If you could make a small extension that shows the problem then I will take another look at it.

Thanks, 
Thomas

**Comment by rslovak** [comment]
Dear Thomas,

with the latest November update of NAV development preview it works. I am not able to reproduce it.

Roman
