### ISSUE TITLE
Unable to download symbols on newly generated BC23 docker environment

### ISSUE THREAD

**Issue by peterz84** [microsoft/AL#7552]
**1. Describe the bug**
I am getting an error message when downloading symbols on a newly created docker environment with the latest BC23 environment (23.0.12034.13233), using the latest AL Language extension from the marketplace (non-pre-lease-version: v12.1.883011).

**2. To Reproduce**
Create a new docker environment:
```
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'YourPassword!' -AsPlainText -Force)
$licenseFile = "https://yourlicensefile.bclicense"
$artifactUrl = "https://bcartifacts.azureedge.net/sandbox/23.0.12034.13233/nl"
$containername = "BC230-ERR"

New-BcContainer `
    -accept_insiderEula `
    -accept_eula `
    -containerName $containername `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -licenseFile $licenseFile `
    -updateHosts `
    -memoryLimit 8G `
    -dns 8.8.8.8 `
    -includeTestToolkit `
    -includeTestFrameworkOnly `
    -includeTestLibrarieskOnly `
    -assignPremiumPlan
```

Visual Studio code, ensure you have the latest marketplace AL Language extension (v12.1.883011) and create a new project with AL:Go!. 

Create a launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "http://BC230-ERR",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "breakOnError": "All",
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default",
            "usePublicURLFromServer": true
        }
    ]
}
```

**3. Expected behavior**
I should be able to download the symbols. When you reproduce with an older image, for instance:  "https://bcartifacts.azureedge.net/sandbox/23.0.12034.13077/nl", it does work.

**4. Actual behavior**
An error occured:

```
[2023-10-20 09:50:38.43] Using reference symbols cache paths: [c:\Users\p.eckhardt\Documents\AL\ALProject1\.alpackages]
[2023-10-20 09:50:38.47] Targeting server 'http://BC230-ERR', server instance 'BC' and tenant 'default'.
[2023-10-20 09:50:38.53] Using user name and password authentication. User name used is: 'admin'.
[2023-10-20 09:50:38.55] Sending request to http://bc230-err:7049/BC/dev/metadata?tenant=default
[2023-10-20 09:50:38.77] Sending request to http://bc230-err:7049/BC/dev/metadata?tenant=default
[2023-10-20 09:50:38.86] This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 12.1
- Web API: 6.0
- Debugger: 6.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 7.0, 7.1, 7.2, 8.0, 8.1, 9.0, 9.1, 9.2, 10.0, 10.1, 10.2, 11.0, 11.1, 12.0
- Supported Web API: 1.0, 2.0, 3.0, 4.0, 5.0, 6.0
- Supported debuggers: 1.0, 2.0, 3.0, 4.0, 5.0, 6.0
```

**5. Versions:**

- AL Language: v12.1.883011
- Visual Studio Code: Version: 1.78.2 (user setup)
- Business Central: sandbox/23.0.12034.13233/nl
- List of Visual Studio Code extensions that you have installed: a lot (waldo's pack for instance)

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Looks like the docker image was released a bit faster than the latest extension. I would suggest to use the pre-release version until the new VSIX is released.

The next version of the extension will resolve this.

**Comment by peterz84** [comment]
Any idea when the new version of the extension will release? And any plan how this can be prevented next time? 
Our DevOps CI/CD is failing because of this mismatch.
