### ISSUE TITLE
DevOps Syntax Highlithing does not apply for preprocessor or pragma directives.

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7556]
**1. Describe the bug**
Currently the DevOps Syntax Highlighting isn't applied for preprocessor Symbols

**2. To Reproduce**

1. Install the extension https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.allanghighlights
2. Go to a file which includes `#if not CLEAN22` or create a file with the al snippet below
3. these directives are not highlighted correctly.

``` AL
#if not CLEAN23
    [Obsolete('Use Codeunit "Format Address Contact2".FormatAddr2 instead.', '22.0')]
    procedure FormatAddr2(var AddrArray: array[8] of Text[100]; Name: Text[100]; Name2: Text[100]; Contact: Text[100]; Contact2: Text[100]; Addr: Text[100]; Addr2: Text[50]; City: Text[50]; PostCode: Code[20]; County: Text[50]; CountryCode: Code[10])
    begin
#pragma warning disable AL0432
        OnFormatAddr2(AddrArray, Name, Name2, Contact, Contact2, Addr, Addr2, City, PostCode, County, CountryCode);
# pragma warning restore AL0432
    end;
#endif
```
![image](https://github.com/microsoft/AL/assets/53570297/2fd30bfe-8c36-4d84-855a-49397eb81770)

**3. Expected behavior**
That the directives like `#pragma warning ..` or `#if not CLEAN` are highlighted correctly in DevOps (e.g. green like in VS Code similar to a comment)

**4. Actual behavior**
e.g. the word `not` is highlighted, but the word `if` is not and CLEAN23 as well not, so it's not equal.

**5. Versions:**

- ms-dynamics-smb.allanghighlights: 12.1.886884 (Latest)

**Comment by EmilDamsbo** [comment]
Thank you for using the Azure DevOps Syntax Highlighting extension, we appreciate you taking the time to report this. Unfortunately we have decided to not accept this suggestion after all, in order to focus on higher priority items in the backlog.
