### ISSUE TITLE
Sync-NAVApp : Upgrade issue for Invoice Post. Buffer table

### ISSUE THREAD

**Issue by jacmax** [microsoft/AL#7557]
**Describe the bug**
I am upgrading BC V20 to V23.
I have two extensions for Invoice Post. Buffer table :

'Core Localization Pack for Czech' and 'MyExtension'

BaseApp > dbo.CRONUS CZ s_r_o_$Invoice Post_ Buffer$437dbf0e-84ff-417a-965d-ed2bb9650972
CzechExt > dbo.CRONUS CZ s_r_o_$Invoice Post_ Buffer$267b59d3-7302-44c5-ba77-c87000380514
MyExt > dbo.CRONUS CZ s_r_o_$Invoice Post_ Buffer$0ed0789d-bd93-455f-a782-afc9e090d4a4

During the upgrade process the system connected two SQL tables with extensions guid to one with 'ext' at the end of name.

dbo.CRONUS CZ s_r_o_$Invoice Post_ Buffer$437dbf0e-84ff-417a-965d-ed2bb9650972$ext

Inside this new table I found fields related to two extensions above.

![obraz](https://github.com/microsoft/AL/assets/16525376/cd85b10f-e174-4b8b-8477-292823c0d189)

When I run Sync-NavApp for 'Core Localization Pack for Czech' I received error:

`Core Localization Pack for Czech
TableExtension 11722 Invoice Post. Buffer CZL :: The field 'Ext. Amount CZL' cannot be located. Removing fields is not
allowed.
TableExtension 11722 Invoice Post. Buffer CZL :: The field 'Ext. Amount Incl. VAT CZL' cannot be located. Removing fiel
ds is not allowed.
TableExtension 11722 Invoice Post. Buffer CZL :: The field 'VAT Date CZL' cannot be located. Removing fields is not all
owed.
TableExtension 11722 Invoice Post. Buffer CZL :: The field 'Correction CZL' cannot be located. Removing fields is not a
llowed.
TableExtension 11722 Invoice Post. Buffer CZL :: The field 'Original Doc. VAT Date CZL' cannot be located. Removing fie
lds is not allowed.
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC23/nav-systemapplication,Microsoft.Dyna
   mics.Nav.Apps.Management.Cmdlets.SyncNavApp
    + PSComputerName        : localhost
`

It seems to me that the system is trying to delete this table, 

On upgrade Cronus demo database, this table is deleted in Sync-NavApp process. 

I did upgrade process from V20 to V23 on Cronus demo database for Czech, everything was OK.

In my database I installed two extensions, and upgrade process has an issue.

![obraz](https://github.com/microsoft/AL/assets/16525376/4880643b-ef62-42e8-a4cb-f3c4e095b827)

**Comment by qutreson** [comment]
Closing this issue because it has been inactive since November
