### ISSUE TITLE
Suggestion for txt2al.exe: Skip SIFTLevelsToMaintain and KeyGroups

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#756]
I found some legacy property **SIFTLevelsToMaintain** and **KeyGroups** in some of my .al-Files. Pre-Compiler says _The property 'SIFTLevelsToMaintain' cannot be used in this context_ or _The property 'KeyGroups' cannot be used in this context_.

Somehow, it is still in NAV 2017 in some of my objects, but I cannot see it in the Classic Development Environment of NAV 2017 and I will remove this via Text Export/Import in NAV 2017. 

For me it caused some strangely unrelated and hard to trace problems (see #745).

So to smoothen the transition for others I would like to suggest skipping **SIFTLevelsToMaintain** and **KeyGroups** in **txt2al.exe** or in the **New Export Format**, because it is not useable for keys anyway.

New Export Format Delta File:
```
[..]
 KEYS
  {
    {    ;"Entry No."                             ;Clustered=true }
    {    ;"Customer No.","Posting Date","Currency Code";
                                                   SumIndexFields="Sales (LCY)","Profit (LCY)","Inv. Discount (LCY)";
                                                   SIFTLevelsToMaintain=[{"Customer No."},
                                                                         {"Customer No.","Posting Date":Year},
                                                                         {"Customer No.","Posting Date":Month}] }
    { false;"Customer No.","Currency Code","Posting Date";
                                                   KeyGroups=Cust(Curr) }
   [..]
```

**Comment by markbrummel** [comment]
SIFTLevelsToMaintain... there is a trip down memory lane... :-)
