### ISSUE TITLE
AL extension version for Visual Studio Code cannot be used with the specified server.

### ISSUE THREAD

**Issue by HBPGroupPreSales** [microsoft/AL#7560]
Started receiving this message today, nothing has changed other than device has been rebooted since working on project last week.
BC environment is Version: GB Business Central 23.0 (Platform 23.0.13275.0 + Application 23.0.12034.12676)
Which was built last week as a clean sandbox.
Worked on project and was able to publish without debugging to sandbox now receive below error.

![image](https://github.com/microsoft/AL/assets/147608561/e88c3c60-7b73-471c-bf5a-5bc198a61ae9)

have rolled AL extension back to 12.0 but same issue.

Can see the base BC application is 22 but as i say this was working absolutely fine last week for at least a day or more after the sandbox was rebuilt.

**Comment by harshilpatel984** [comment]
Facing the same issue

**Comment by SBalslev** [comment]
Please update the extension in VSCode and try again

**Comment by harshilpatel984** [comment]
Already checked with the latest version of al extension as well as pre released versiosn but not working

**Comment by SBalslev** [comment]
Have you tried changing the runtime version in the app.json to match the supported version on the server? From your screenshot that is 12.1.

**Comment by harshilpatel984** [comment]
when will it be resolved?

**Comment by HBPGroupPreSales** [comment]
> Please update the extension in VSCode and try again

How do i do this?

**Comment by HBPGroupPreSales** [comment]
> Have you tried changing the runtime version in the app.json to match the supported version on the server? From your screenshot that is 12.1.

The App.json is set to 12.0, runtime 12.1 says it isn't support

**Comment by HBPGroupPreSales** [comment]
I have reinstalled the AL update and updated app.json to 12.1 and is now all working fine

**Comment by harshilpatel984** [comment]
With V23 Is you debugging working fine? After Reinstalling AL?
