### ISSUE TITLE
Strange behavior of the debugger

### ISSUE THREAD

**Issue by NavNab** [microsoft/AL#7561]
**1. Describe the bug**
The debugger is behaving strangely while debugging the Codeunit "Customer Templ. Mgt.". 

**2. To Reproduce**
1- Create a new app (AL GO).
2- Create a page extension:
```
pageextension 50100 "possible bug" extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {
            action(Test)
            {
                Caption = 'Test';
                Image = Action;
                Promoted = true;
                PromotedIsBig = true;
                PromotedOnly = true;

                trigger OnAction()
                var
                    Customer: Record Customer;
                    CustomerTemplMgt: Codeunit "Customer Templ. Mgt.";
                    IsHandled: Boolean;
                begin
                    CustomerTemplMgt.CreateCustomerFromTemplate(Customer, IsHandled, 'CUSTOMER COMPANY');
                end;
            }
        }
    }
}
```
3- Set a breakpoint on line 86 of the codeunit "Customer Templ. Mgt."
4- Deploy to a W1 V23.0 container (on-prem ; I didn't test on saas)
5- Execute the Action
6- Start debugging using F10

Please refer to this discussion https://twitter.com/_NavNab/status/1717226246394753278 ; different inputs from the community.

A video showing the strange behavior in V23.0
https://twitter.com/_NavNab/status/1717300741239431280

The same works fine on V22.5
https://twitter.com/_NavNab/status/1717299720391893271

**3. Expected behavior**
A sane debugger 😅

**4. Actual behavior**
A crazy debugger

**5. Versions:**

- AL Language: v12.1.887908 and pre-release
- Visual Studio Code: 1.83.1
- Business Central: 23.0.12034.12841

**Comment by NavNab** [comment]
What I discovered is that the debugger doesn't allow direct debugging of standard objects.
As shown in the screenshot, breakpoints are disabled in this context. You can effectively debug custom code until you invoke a standard object. At that point, the debugger becomes 'crazy' and displays random lines within the standard object. While not entirely random, it seems to be related to the 'using' statement, as pointed out by the community on X (Twitter 🙈)

![image](https://github.com/microsoft/AL/assets/34076325/7ad59809-1556-46cd-a80c-811b361084d0)

**Comment by mfalk118** [comment]
It is most likely the usings. I have just debugged Purchase Line and the debugger is off with 62 lines. Funny enough there is 62 lines of using statements

**Comment by KuljitSinghParmar** [comment]
have same . debugger is off by many lines of code.

**Comment by kalberes** [comment]
This is teh same as issue #7566

**Comment by shashihubgit** [comment]
same issue, since long

**Comment by gymhood96** [comment]
Has this problem already been solved? I had the same problem today.
