### ISSUE TITLE
Debugging is not working with V23

### ISSUE THREAD

**Issue by harshilpatel984** [microsoft/AL#7562]
Please include the following with each issue:

**1. When I depoy extension with f5 for debigging extension is publishing but debugging is not working, yesterday it was working normally and i did not updated anything in the system**
<img width="641" alt="image" src="https://github.com/microsoft/AL/assets/28805630/cddcbeb6-9c79-4b3a-8872-6e5e5e854ca5">

**2. To Reproduce**
Open your extension and press f5 to debug

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Debugging should work with f5

**4. Actual behavior**
Getting an internal server error

**5. Versions:**

- AL Language:
<img width="154" alt="image" src="https://github.com/microsoft/AL/assets/28805630/df81fb2a-60d8-4bdf-b23f-52cf35a33701">

- Visual Studio Code:
<img width="293" alt="image" src="https://github.com/microsoft/AL/assets/28805630/73dfabc5-4533-451d-a048-5de107d9ee6c">

- Business Central:
<img width="574" alt="image" src="https://github.com/microsoft/AL/assets/28805630/525b3457-664d-479d-b814-1971b20cf5af">

- List of Visual Studio Code extensions that you have installed:
<img width="641" alt="image" src="https://github.com/microsoft/AL/assets/28805630/13065039-2ffa-4b25-a951-2c5c3fe7e064">

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by NKarolak** [comment]
Refer to #7554

**Comment by evilimkova** [comment]
I have exactly the same problem.

**Comment by SBalslev** [comment]
We're working on the challenge, unfortunately we do not have an ETA.
Currently we would recommend using snapshot debugging.
Duplicate #7554
