### ISSUE TITLE
AL debugger cannot locate errors inside report column expressions

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#7564]
**1. Describe the bug**
The AL debugger cannot locate errors **inside reporting column expressions**, such as division by zero, while the web client produces a run-time error.

**2. To Reproduce**

1. Create a new Report with any expression for a column that can raise an error... like this example:

```al
report 50000 "Division By Zero Crash Test"
{
    ApplicationArea = All;
    Caption = 'Division By Zero Crash Test';
    DefaultLayout = Excel;
    ExcelLayout = '.\DivisionByZeroCrashTest.xlsx';
    UsageCategory = ReportsAndAnalysis;

    dataset
    {
        dataitem(SalesLine; "Sales Line")
        {
            DataItemTableView = sorting("Document Type", "Document No.", "Line No.");
            RequestFilterFields = "Document Type", "Document No.", "Line No.", "Type", "No.";

            column(DocumentType; "Document Type") { }
            column(DocumentNo; "Document No.") { }
            column(LineNo; "Line No.") { }
            column(Type; "Type") { }
            column(No; "No.") { }
            column(Quantity; Quantity) { }
            column(Amount; Amount) { }
            column(UnitPrice; "Unit Price") { }
            column(AmountIncludingVAT; "Amount Including VAT") { }

            // Division by Zero here! but compiler can't identify this is the line with the Bug
            column(UnitPriceIncludingVAT; "Amount Including VAT" / Quantity) { AutoFormatType = 2; }
        }
    }

    trigger OnPreReport()
    begin
        // Set a breakpoint here!
        Message('Start debugging here!.');
    end;
}
```

2. Publish the changes to the CRONUS company of a sandbox with F5 and a breakpoint in the OnPreReport() event to begin debugging.

3. You get a **runtime error** like this one that crashes the web client and **AL Debugger cannot locate the error line**

![image](https://github.com/microsoft/AL/assets/5801847/c4128012-22b2-43f1-84ec-9918c73d9650)

**3. Expected behavior**
- AL Debugger should locate the error line
- Web Client should show a friendly description for this error and not crash like now

**4. Actual behavior**
- A **runtime error** like the above one crashes the web client 
- **AL Debugger cannot locate the error line**

**5. Versions:**

- AL Language: v12.1.887908
- Visual Studio Code: 1.83.1
- Business Central: ES Business Central 23.0 (Platform 23.0.13032.0 + Application 23.0.12034.13092)
- List of Visual Studio Code extensions that you have installed: (none)

**Comment by qutreson** [comment]
The debugger is only supported in AL methods and we do not support it on expressions at the moment. We would recommend logging this as an idea on aka.ms/BCIdeas or upvote the existing idea if there is already one.

**Comment by JavierFuentes** [comment]
Thanks but I'll wait for you to fix it, if you want.

I have already dedicated part of my time to document and reporting it because it is not an improvement, it is a Bug that also crash the web client.
