### ISSUE TITLE
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown"

### ISSUE THREAD

**Issue by bouncy99** [microsoft/AL#7565]
Please include the following with each issue:

**1. Describe the bug**
After enabling SSL on a BC instance, VS Code reports "Error: The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown".  The certificate is signed with an Open SSL internal CA, and no revocation list has been specified or published.

**2. To Reproduce**
Enable SSL on BC with openssl ca signed cert, update server in launch.json to https, attempt to Connect to BC

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Connection should be successful, or a an option to disable crl check, prior to connection.   This is based on an open issue #3274 where defr0std on the 31/08/2018 advised "We have received a permission to add an option for disabling the CRL validation in the AL extension." 5 years on, this doesnt appear to have been addressed.

**4. Actual behavior**
"Error: The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown"

**5. Versions:**

- AL Language: 12.1.887908
- Visual Studio Code: 1.83.1
- Business Central: 21
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by SBalslev** [comment]
Please see #7618
