### ISSUE TITLE
Debugging BC23 shows not the correct line

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#7566]
Debugging a BC standard code shows not the correct line.
![image](https://github.com/microsoft/AL/assets/47736215/08b288f1-2af2-4e75-a821-f0f17da0e42f)

The namespace and usage above the codeunit moves the code down and causes the debugger not to be on the correct line.

**5. Versions:**

- AL Language: 12.1.887908
- Visual Studio Code: 
- Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
- Business Central: 23.0.12034.13549

**Comment by kalberes** [comment]
OnPrem you would need version 23.1 that the debug engine understands the same way line information generated by the the vsix version of the compiler and the compiler generated symbols on the server.

**Comment by kalberes** [comment]
OnPrem 23.1 was released.

**Comment by shashihubgit** [comment]
what about inside docker container ?

**Comment by gymhood96** [comment]
Has this problem already been solved? I had the same problem today.

**Comment by NKarolak** [comment]
@gymhood96 Yes, but see above:

> OnPrem you would need version 23.1 of the NST and apps recompiled that the debug engine understands the same way line information generated by the the vsix version of the compiler and the compiler generated symbols on the server.

Were you working on a 23.0?

**Comment by gymhood96** [comment]
@NKarolak Yes, but I have read in other forums that it is a bug in VS Code. Is this a bug in BC 23.0 so we need to update our customers to at least 23.1?

**Comment by NKarolak** [comment]
@gymhood96 
It's a platform bug related to the introduction of namespaces, hence you need an update to 23.1.

**Comment by gymhood96** [comment]
@NKarolak ok thank you
