### ISSUE TITLE
D365 Business Central integration with SharePoint - SharePoint Module not found

### ISSUE THREAD

**Issue by kgowthampqube** [microsoft/AL#7567]
Hi,
I'm trying to enable the SharePoint integration in a trial environment that I have set up recently to evaluate BC. I have searched for "SharePoint Setup" in the global search. It doesn't return any result related to SharePoint. Instead, it shows One Drive. Is it not possible to use SharePoint anymore? Can anyone help me out?

**Comment by EmilDamsbo** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
