### ISSUE TITLE
Unable debugging Business Central 23

### ISSUE THREAD

**Issue by isabtogumon** [microsoft/AL#7568]
I have not been able to debug the code in Visual Studio Code since version 23 of Business Central was released.
I already confirmed that the version of the AL Language extension is updated, which is v12.1.887908

Log:
[2023-10-31 12:12:52.56] Success: The package 'Default publisher_Test_1.0.0.0.app' has been published to the server.
[2023-10-31 12:12:52.56] By publishing an extension from Visual Studio Code, you accept the per-tenant extension disclaimer https://go.microsoft.com/fwlink/?linkid=2193002&clcid=0x409. If you do not accept, you must uninstall and unpublish the extension from the Extension Management page of the environment where the extension was published.
[2023-10-31 12:12:52.56] Important: Extensions that have been published from Visual Studio Code are removed when the environment is updated or relocated within our service. For more information, see this article on sandbox environments https://go.microsoft.com/fwlink/?linkid=2153804 .
[2023-10-31 12:12:53.87] Error: An internal error has occurred

The extension is published but it does not allow me to debug the code.
Has anyone else had this problem and can give me an idea on how to solve it?

**Comment by harshilpatel984** [comment]
Yes this is an issue from microsoft side, unfortuantly i am also facing the same. Microsft has not provided any timeline for this so, it is pity for us

**Comment by RobertatK3** [comment]
I'm able to debug, but the pointer in the file is not correct. Any breakpoints I set are not fired.
It looks like the new _using namespace_ lines are not present in the compiled apps, which causes the line numbers not to match the ones in the .dal files.

**Comment by navaddins** [comment]
I also facing same issue. Debugger console is showing below message, and it's not attached to break point.

`Error: It is not possible to add a breakpoint at line number 279 in application object type TableExtension, ID 50000. Check that the resource exposure policies applied to this extension allows debugging.`

However, I can manage to debug to my code after remove **namesapce from al files**. But It's not right solution for us.

**Comment by NKarolak** [comment]
The [debugger is off by as many lines as "using ... " lines exist in the object](https://github.com/microsoft/AL/issues/7566). Try setting the breakpoints at the appropriate number of lines higher or lower.

**Comment by RobertatK3** [comment]
Nice suggestion and it worked for me yesterday, but stepping through the code is cumbersome if not impossible...

**Comment by NKarolak** [comment]
@RobertatK3 No doubt that this is no solution, just a workaround to be able to start the debugger at all 🤷‍♀️
But as long as Microsoft does not fix the issue, it's the only alternative to removing the namespaces in your objects. I hope it's fixed asap; it seems that the Directions pause the process.

Please also mind this statement by Microsoft:
https://github.com/microsoft/AL/issues/7554#issuecomment-1778858716

**Comment by EmilDamsbo** [comment]
Since this issue is already tracked by existing open issues, please keep discussion to #7561 and #7554
