### ISSUE TITLE
List Part Pages are displayed incorrectly in grid layout

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/AL#7577]
**1. Describe the bug**
If two list part pages are placed in a grid layout on a card page the pages have a minimum unreadable width and cannot be expand.
This behavior comes with version 23. In Version 22 the width was normal.

**2. To Reproduce**
1. Create a grid layout in a group of a card page and place two list parts in it:
``` AL
                    grid(GridForTwoListPars)
                    {
                        part(ListPartPageOne; "List Part Page One")
                        {
                        }
                        part(ListPartPageTwo; "List Part Page Two")
                        {
                        }
                    }
```
2. Compile and publish.
3. Open the webclient and navigate to the page.

**3. Expected behavior**
The layout in the page should show the list parts side by side, without any empty spaces. In Version 22 this has worked fine.
Here is a Screenshot how it looked like till BC22.5:
![image](https://github.com/microsoft/AL/assets/34675109/62b3ad01-6917-42c1-99c4-13fe868b5def)

**4. Actual behavior**
Since BC23 the list parts are so narrow that you can't read any field anymore and a wide empty space is right next to them.
![image](https://github.com/microsoft/AL/assets/34675109/76126495-49ac-4fef-88d2-dda8f1f5a4f5)

**5. Versions:**

- AL Language: 12.1.887908
- Visual Studio Code: 1.84.1
- Business Central: DE Business Central 23.0 (Platform 23.0.13573.0 + Application 23.0.12034.12676)
- List of Visual Studio Code extensions that you have installed: Tested with none except the AL-Language

**Comment by pri-kise** [comment]
This is not related to the AL Language Extension.
You should create a support case to get this addressed.

This issue here is nice for other partners as reference, but it won't solve your problem.

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. The owning team is already aware of this issue, however you can choose to open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible. 

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
