### ISSUE TITLE
Suggestion for System.Convert and System.IO.MemoryStream

### ISSUE THREAD

**Issue by rrudalski** [microsoft/AL#758]
Is it possible to see System.Convert and System.IO.MemoryStream classes in AL in near future? 

In most cases we use both of them to handle Base64Strings but Convert can be more usefull tool than EVALUATE especialy when woking with .net.

**Comment by Gallimathias** [comment]
Memory Stream has already been requested. In the open library there is already a wrapper. 
[al-OpenLibrary](https://github.com/Microsoft/cal-open-library/blob/master/BaseApp/COD704.txt)

It would be better than Convert if casting is implemented.

**Comment by mrabus** [comment]
Hello NAV Modern Dev Team & Community,

first of all: merry christmas! 

I saw you added the MemoryStreamWrapper codeunit from the open AL library. But none of the methods of the codeunit are visible externally. Would you please make them available? 

Thank you very much

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
