### ISSUE TITLE
ValuesAllowed does not allow empty value

### ISSUE THREAD

**Issue by ValsorimS** [microsoft/AL#7580]
Please include the following with each issue:

**1. Describe the bug**
We are converting functionality from NAV2009, where the ValuesAllowed property on the form was set to "";A;N for the Code[1] field. When I set the same property in BC22 or BC23 to '', 'A', 'N'; and I delete a value in a field, I get an error: "Value '' is not a valid value. The following values can be used: ;A;N."

**2. To Reproduce**
Just add a field of type Code[1] to the page and set the ValuesAllowed property.

``` AL
field(ValuesAllowedBug; Rec.ValuesAllowedBug)
                {
                    ToolTip = 'Specifies the value of the ValuesAllowedBug field.';
                    ValuesAllowed = '', 'A', 'N';
                }
```

**3. Expected behavior**
I expect that it will be possible to delete the value in the field when there is a value '' in the ValuesAllowed.

**4. Actual behavior**
Type A in the field and delete it. And you get an error: Value '' is not a valid value. The following values can be used: ;A;N.

**5. Versions:**

- AL Language: v12.1.887908
- Visual Studio Code: 1.84
- Business Central: BC23, BC22
- List of Visual Studio Code extensions that you have installed:

**Comment by qutreson** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
