### ISSUE TITLE
Explore page in Visual Studio Code - Error "c.workspace.workspaceFolders is not iterable"

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7582]
Please include the following with each issue:

**1. Describe the bug**

When I use the 'Explore page in Visual Studio Code' on page 'Bank Acc. Reconciliation (379, ListPlus)', VS Code is opened with the error  'c.workspace.workspaceFolders is not iterable'

![vscode](https://github.com/microsoft/AL/assets/25268332/a5a4f076-032d-418b-bea1-c6bb3ccdc3fe)

**2. To Reproduce**

- Open page 'Bank Acc. Reconciliation (379, ListPlus)'
- Ctrl+Alt+F1 
- 'Explore page in Visual Studio Code' 
- VS Code is opened 
- error  'c.workspace.workspaceFolders is not iterable' is shown

**3. Expected behavior**
No error

**4. Actual behavior**
- error  'c.workspace.workspaceFolders is not iterable' is shown

**5. Versions:**

- AL Language: 12.1.887908
- Visual Studio Code:
- Business Central: US Business Central 23.1 (Platform 23.0.13573.0 + Application 23.1.13431.13546)
- List of Visual Studio Code extensions that you have installed:

**Comment by elmer-t** [comment]
Experiencing the same issue

**Comment by blrobl** [comment]
This should have been fixed with the latest VSIX - could you confirm this is the case? Thanks!

**Comment by fvet** [comment]
@blrobl Seems to be fixed, will reopen if it should appear again. Thanks for the quick fix !
