### ISSUE TITLE
Publishing/Debuging extension to Cloud Sandbox, when Proxy server in network

### ISSUE THREAD

**Issue by danooooo1** [microsoft/AL#7584]
Hi,
I wanted to ask how to set up a proxy server for the AL extension in VS Code and then publish the application or download symbols to/from the Sandbox BC environment. From a network without a proxy server, everything works fine, but if I try to publish the app from a network with a proxy server, I still end up with a 407 error and I am unable to set the proxy server in VS Code. Property "http.proxyAuthorization" from VS Code settings.json is set up and is totally ignored.

Thanks for the advice, Daniel

**Comment by BazookaMusic** [comment]
The extension does not use the vscode proxy. You will need to setup the proxy on the machine that runs vscode, so that the language server uses it by default.

**Comment by BazookaMusic** [comment]
Unofficially, it may be possible for your network setup to setup a proxy via netsh winhttp. Officially we do not support proxies for the extension.

I'd suggest voting for this feature in  aka.ms/bcideas, which is our feedback tool to see which features are important to developers.

I'll be closing this issue.
