### ISSUE TITLE
VS Code AL Extension 0.10.13928 does not cater for default Documents location changed (still)

### ISSUE THREAD

**Issue by yrest** [Microsoft/AL#759]
Thanks for releasing new preview update!

Have pulled docker image, ran it, downloaded new VS Code extension from http://uspreview:8080/al-0.10.13928.vsix and installed it.

Ctrl+Shift+P, AL:Go! tries to create new project in C:\Users\profile\Documents\AL folder.
However, my "Documents" folder has been changed to a different drive/location.

If attempting to change suggested path to a custom folder, getting 

Path does not exist
The path '\Source\AL\ALProject3' does not seem to exist anymore on disk.

After that it stops, but actual project is created.

**Comment by DominikDitoIvosevic** [comment]
Hi. This is a known bug for electron which is the base for vscode. They have the fix and it should be in the next monthly update.

https://github.com/Microsoft/vscode/issues/27285
https://github.com/electron/electron/pull/10377

**Comment by yrest** [comment]
That's great, thanks for the update gentlemen!
