### ISSUE TITLE
Sales-Post  and Purch.-Post Bug 

### ISSUE THREAD

**Issue by saferali** [microsoft/AL#7590]
**1. Describe the bug**
I used an event subscription OnBeforePostPurchaseDoc and OnBeforePostSalesDoc To Set SuppressCommit=true and  Set HideProgressWindow=True

I got this error : The operation failed because the dialogue box is not open.		

**2. To Reproduce**
Scenario 
	Codeunit
		codeunit 80 Sales-Post 
			RunWithCheck	
				OnBeforePostSalesDoc(SalesHeader2, SuppressCommit, PreviewMode, HideProgressWindow, IsHandled);
						(Set SuppressCommit=true; Set HideProgressWindow=True)
						
						
			ProcessPosting >> ProcessPostingLinesCommitBehaviorIgnore 
						   >> ProcessPostingLines
						   >> PostInvoice
						   >> PostSalesTaxToGL
			Line 6765 6766   >> Error ( Should test also on HideProgressWindow)
								if GuiAllowed then
									Window.Update(3, StrSubstNo('%1 / %2', LineCount, TaxLineCount));
            
			
		          Same Error for codeunit 90 "Purch.-Post"
					           >> PostSalesTaxToGL
			  Line 6502 6503 >> Error ( Should test also on HideProgressWindow)
								  if GuiAllowed then
									  Window.Update(3, StrSubstNo('%1 / %2', LineCount, TaxLineCount));

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. 

If it is in the application and you already know how to fix the issue go to https://github.com/microsoft/ALAppExtensions and submit your suggestion for a fix.
