### ISSUE TITLE
Debugger loses the call stack after entering a UI handler in test code

### ISSUE THREAD

**Issue by adrogin** [microsoft/AL#7591]
When debugging any test which has a UI handler, I can see the correct call stack until the code reaches the handler. After entering the UI code, call stack gets cleared and shows only the current method.

![image](https://github.com/microsoft/AL/assets/42849285/314d77f8-eede-4204-a842-45201ed6e75e)

For example, it can be reproduced on the codeunit 137023 "SCM Reservation Worksheet", test method GettingDemandAndValidateFields. Call stack disappears when the test invokes the report "Get Demand To Reserve".

If a test calls a UI action which requires a handler, while the handler attribute is missing in the test, the error message shows an empty call stack.

![image](https://github.com/microsoft/AL/assets/42849285/1a85e64d-f112-4153-bc08-6035efb00b21)

**Application/platform version**
Platform 23.0.13804.0 + Application 23.1.13431.13812

**AL Language version**
v12.3.900902

**Comment by kalberes** [comment]
This is by design. The AL stack is not preserved between these calls.
