### ISSUE TITLE
Procedure declaration should not end with semicolon

### ISSUE THREAD

**Issue by Arthurvdv** [microsoft/AL#7598]
**1. Describe the bug**
There are two actions in the AL Language VS Code extension, where I'm aware of, that add an semicolon at the ending of a Procedure declaration.

A) 'Subscribe to Event' (AL Explorer)
B) 'Implement interface' code action

**2. To Reproduce (A) - 'Subscribe to Event' (AL Explorer)**
From the AL Explorer select the tab EVENTS.
Select an event and hit the Subscribe button.
Paste the content of the clipboard in an AL file

![image](https://github.com/microsoft/AL/assets/44637996/79f14010-5897-4fc4-9989-51849a756cdb)
![image](https://github.com/microsoft/AL/assets/44637996/ca8b23a6-fd79-499c-b3ef-2c52506b2e20)

``` AL
    [EventSubscriber(ObjectType::Codeunit, Codeunit::Checklist, 'OnChecklistLoading', '', false, false)]
    local procedure Checklist_OnChecklistLoading();
    begin
    end;
```

The semicolon at the ending of `Checklist_OnChecklistLoading` procedure should not be there.

**2. To Reproduce (B) - 'Implement interface' code action**
Create an codeunit which implements an interface
Select the 'Implement interface' code action

![image](https://github.com/microsoft/AL/assets/44637996/ed85d8cf-c956-4e73-9849-1cc6404bd5ca)
![image](https://github.com/microsoft/AL/assets/44637996/6c38e9db-3982-4116-8143-069bd555256f)

``` AL
interface MyInterface
{
    procedure Myprocedure()
}

codeunit 50100 MyCodeunit implements MyInterface
{
    procedure Myprocedure();
    begin

    end;
}
```

The semicolon at the ending of `Myprocedure` procedure should not be there.

**Comment by fvet** [comment]
Same applies to the 'Find Event' (probably uses the same code path as the 'Subscribe to Event' scenario)

![FindEvent](https://github.com/microsoft/AL/assets/25268332/54161547-ef0d-49f4-91d1-e52c56b77a1e)

**Comment by RadoArvay** [comment]
But just a simple question about a semicolon: why not?

**Comment by fvet** [comment]
> But just a simple question about a semicolon: why not?

There's some valid arguments listed here on X
https://twitter.com/arthrvdv/status/1727729430737342791

**Comment by NKarolak** [comment]
@fvet Please mind that people who are not logged into Twitter / X cannot read any of the answers below, thanks to Elon.

**Comment by Arthurvdv** [comment]
I’ve try’ed to summarize all the reasons in the documentation on the rule of the LinterCop; https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0024
