### ISSUE TITLE
Using multiple namespaces for the same pageextension

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7599]
**1. Describe the bug**
Project, with multiple namespaces for the same object, does not compile, but gives the following error:

`The extension object 'CustomerListExt2' cannot be declared. Another extension for target 'Customer List' or the target itself is already declared in this module.
`
**2. To Reproduce**
Create new AL project with two files

```
namespace DefaultPublisher.myNameSpace1;

using Microsoft.Sales.Customer;

pageextension 50100 CustomerListExt1 extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('App published: Hello world1');
    end;
}

```

```
namespace DefaultPublisher.myNameSpace2;

using Microsoft.Sales.Customer;

pageextension 50101 CustomerListExt2 extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Message('App published: Hello world2');
    end;
}
```

**3. Expected behavior**
I expect that project compiles successfully, and I can have multiple pageextensions (or any other extension type), for the same project.

According to namespace documentation, it should be possible. My objects are named differently

![image](https://github.com/microsoft/AL/assets/16342128/3cb5ed24-bf0f-4358-9743-a55239eac218)

**5. Versions:**

- AL Language: v12.3.900902
- Visual Studio Code: 1.84.2

**Comment by SBalslev** [comment]
This is by design and stated only a few lines above where your highlights.
![image](https://github.com/microsoft/AL/assets/9417259/d5fed919-0888-4be2-bf3a-e963687e89a0)

**Comment by dannoe** [comment]
Just to be sure: Esben [wrote](https://www.yammer.com/dynamicsnavdev/threads/2535961633153024) yesterday on Yammer/Viva Engage that this feature is being worked on for the next major. I hope you are not working against each other 😛
