### ISSUE TITLE
TestField doesn't throw error message

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#76]
NAV 2017 using Visual Studio Code

This Code is written in the Codeunit

In my Code 
r: This a variable corresponding to a Record
Field1 : is a boolean field
Field2: is a text field

If r.Field1 then begin
r.TestField(r.Field2)
end;

 The TestField doesn't throw an error

**Comment by pmohanakrishna** [comment]
May I know where did you write your code?

**Comment by StanislawStempin** [comment]
We could not reproduce the problem. The system correctly raises an error if TestField is used with a FieldRef that contains a blank value.
