### ISSUE TITLE
Vendor Bill Line's Withholding Amount calculation during Suggest Payment is wrong in the Italian Version

### ISSUE THREAD

**Issue by Chuucommie** [microsoft/AL#7603]
Please include the following with each issue:

**1. Describe the bug**
_in the Italian version, When generating Vendor Bill Lines from Suggest Payments the field "Withholding Amount" is recalculated and the Withholding Code Lines are retrieved with a Findfirst() without checking for their dates or their validity, a Withholding Tax Code could have more than one Withholding Code Line with different dates and percentages._

![image](https://github.com/microsoft/AL/assets/88215251/4cbb268e-c353-42b1-92e6-6480f632fe1c)

_this, in case you have more than one Withholding Code Line, uses the "Taxable Base %" from the Withholding Code Line and the "Withholding Tax %" from the Vendor Bill Lines's  Withholding Tax table, this can and will cause an error during the recalculation and the Withholding Amount field will be wrongly populated._

**2. To Reproduce**
_To reproduce this behaviour:
1- Choose a Withholding Tax Code from the list page
2- Related --> Withhold Rates --> Withholding Code Lines
3- Create two Withholding Code Lines the first with a Start Date lower than the second line, in the first set the "Withholding Tax %" to 0 and the "Taxable Base %" to 100 in the second one the "Withholding Tax %" to 20 and the "Taxable Base %" to 0
4- Create a Purchase Invoice with a Vendor that has the Withholding Code you choose at the start, check that the Withholding Tax exists for the Purchase Invoice: Actions- Request Approval- Withhold Taxes Soc. Sec., check the Withholding Tax Amount
5- Post the Invoice
6- Create a Vendor Bill Line and Suggest Payments to get the line from the invoice you just posted
7- The withholding tax amount field will be different from the one you saw in the invoice's Withholding Tax
8- if you open the Withholding Tax for that Vendor Bill Line you can see the Withholding Tax Amount is the correct one, when you close the page it will update the vendor bill line correctly, the users can't do this for every single line every single time though._

``` AL
![image](https://github.com/microsoft/AL/assets/88215251/4cbb268e-c353-42b1-92e6-6480f632fe1c)

if ("Vendor Entry No." <> 0) and (VendBillWithhTax."Withholding Tax Amount" = 0) then begin
            VendorLedgerEntry.Get("Vendor Entry No.");
            WithholdCodeLine.SetRange("Withhold Code", VendBillWithhTax."Withholding Tax Code");
            if WithholdCodeLine.FindFirst() then
                if VendorLedgerEntry."Purchase (LCY)" <> 0 then
                    "Withholding Tax Amount" := -Round(
                        (VendorLedgerEntry."Purchase (LCY)" *
                        WithholdCodeLine."Taxable Base %" *
                        VendBillWithhTax."Withholding Tax %") / 10000,
                        GetCurrencyAmtRoundingPrecision(VendBillWithhTax."Currency Code"));
        end;

```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
_The recalculation should check the Invoice Posting Date and then choose the right Withholding Code Line_

**4. Actual behavior**
_The recalculation just takes the first Withholding Code Line for that Withholding Code._

**5. Versions:**

- AL Language:  12.3
- Visual Studio Code: 1.84.2
- Business Central: 23.1
- List of Visual Studio Code extensions that you have installed: AL ToolBox, AL Codeactions, AL Object designer, AL AZ Dev Tools, AL Variable Helper, Waldo Crs
- The problem is present in other versions of BC,  >BC14.45, >BC20.11, >BC21.5, >BC22.0, >BC23.0

### Final Checklist

Please remember to do the following:

* [✅ ] Search the issue repository to ensure you are reporting a new issue

* [✅ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [✅ ] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
