### ISSUE TITLE
Wrong Syntax Highlighting for keywords in OptionMembers

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7604]
Please include the following with each issue:

**1. Describe the bug**
If you create OptionMembers with keywords then those values are highlighted as keyword.

**2. To Reproduce**

1. Create a new Option field

``` AL
table 50000 "PTE Dummy"
{
    Caption = 'PTE Dummy';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "No."; Text[20])
        {
            Caption = 'No.';
            DataClassification = CustomerContent;
            NotBlank = true;
        }
        field(10; "My Special Type"; Option)
        {
            Caption = 'My Special Type';
            DataClassification = CustomerContent;
            OptionCaption = 'none,internal,protected,CorrectHighlithing';
            OptionMembers = none,internal,protected,CorrectHighlithing;
        }
    }

    keys
    {
        key(Key1; "No.")
        {
        }
    }

}

```

**3. Expected behavior**
The keywords shouldn't get this formatting if they are OptionMembers.

**4. Actual behavior**
Currently they are hightlighted as on other places.

**5. Versions:**
- AL Language: v13.0.903630

**Comment by EmilDamsbo** [comment]
Hello, thank you for reporting this issue on syntax highlighting in the AL languge extension. Unfortunately, this is not something that we can resolve well in syntax highlighting. To know whether a word is used in the context of an `OptionMembers` declaration, that requires just that: Context-awareness. Syntax highlighting lacks such a context, unfortunately, but you can use semantic highlighting in Visual Studio Code to achieve better highlighting awareness. 

You can read more about semantic highlight [here](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview), but the short solution is to open your VSCode settings and add `"editor.semanticHighlighting.enabled": true` and enjoy more accurate highlighting.
