### ISSUE TITLE
Txt2Al issue 

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#761]
When i ran the txt2Al tool in Container command prompt i get the below:
![image](https://user-images.githubusercontent.com/26792519/31496566-90d89bca-af79-11e7-8ed8-2eee8f12f1da.png)

i have run the command from NAV Container Helper al files are created but there is no option to give startId(it is taking id from 50100 but i want to give my own range in 70 mil range) see below:
![image](https://user-images.githubusercontent.com/26792519/31496687-05f18f02-af7a-11e7-8966-c67838ef5744.png)

Please suggest me.

Thanks & Regards
Varun Reddy

**Comment by tfenster** [comment]
try 
`Convert-Txt2Al -startId 70000000`
and replace 70000000 with your range

**Comment by bachii1010** [comment]
Hi

Yes this worked.

But i have one more question how can we know what all the parameters  we can pass for a particular command in NAV Container Helper?

Thanks & Regards
Varun Reddy

**Comment by bachii1010** [comment]
Hi 

we have found this how to get help it can be done as show below
![image](https://user-images.githubusercontent.com/26792519/31614469-2649d0fc-b2a4-11e7-8ea4-307a660e119d.png)

Hope it will help others
