### ISSUE TITLE
Error: The SSL connection could not be established, see inner exception. The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation

### ISSUE THREAD

**Issue by ZjTham** [microsoft/AL#7618]
Please include the following with each issue:

**1. Describe the bug**
For BC on-premise, after enabled SSL, when publish extension (F5) VS Code throws error "Error: The SSL connection could not be established, see inner exception. The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation".
This issue also occur in Sandbox environment (SaaS).

**2. To Reproduce**
Publish extension (F5) in VS Code targeting either BC on-premise or Sandbox environment.

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Should be able to publish extension (F5) in VS Code targeting BC on-premise with SSL enabled and Sandbox environments.

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring
BC on-premise:
![image](https://github.com/microsoft/AL/assets/103009699/f9aa1a2d-bb34-4e2f-9758-13e162e180fb)

BC Sandbox:
![image](https://github.com/microsoft/AL/assets/103009699/e8c2d2dd-04b5-4ea5-abcf-4aa54974bbf9)

**5. Versions:**

- AL Language: v12.3.900902
- Visual Studio Code: 1.85.0
- Business Central: W1 23.0 (Platform 23.0.14464.0 + Application 23.0.12034.12676)
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [/] Search the issue repository to ensure you are reporting a new issue

* [/] Reproduce the issue after disabling all extensions except the AL Language extension

* [/] Simplify your code around the issue to better isolate the problem

**Comment by ZjTham** [comment]
kindly assist, this issue have been around for long time already for BC on-premise with SSL enabled. Recently, the Sandbox environment got affected as well. Thank you.

**Comment by SBalslev** [comment]
Certificate validation is done on the client side. 
You can see the different error scenarios here: https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags

If your network configuration does not allow connection to the revocation endpoint you will need to make sure it is verifiable offline or open for it.

Currently, we do not support skipping certificate validation. If needed then I recommend adding an idea on aka.ms/bcideas
