### ISSUE TITLE
Chosen debug configuration has an unsupported attribute value `request`: 'publish'.

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#762]
Today I found that after I try to publish App, i get error
`Chosen debug configuration has an unsupported attribute value `request`: 'publish'.`
![image](https://user-images.githubusercontent.com/29101017/31500787-138f1b06-af71-11e7-8578-832135dedb9b.png)

If I change Request to launch - all is ok, but I have warning
![image](https://user-images.githubusercontent.com/29101017/31500831-322ab52a-af71-11e7-853c-fb5b9d62d708.png)

![image](https://user-images.githubusercontent.com/29101017/31500840-3988b7e0-af71-11e7-9e91-4c9eb4f8f8cd.png)

**Comment by tslomer** [comment]
I have the same issue, but as a temporary workaround, you can use F6 publish your App.  It just opens the web page in development mode.

**Comment by yrest** [comment]
It should be fixed on October update in AL Extension 0.10.13928

**Comment by dennisfrostlander** [comment]
Yes, this is fixed in October update. VSCode 1.17 discontinued custom request types such as "publish", so now it should be "launch" or "attach".
The easiest is simply to set "request" to "launch" and ignore the warning that you get. Once you upgrade the AL extension, the warning will disappear.
