### ISSUE TITLE
how-can-i-sign-a-file-using-rsa-and-sha256-with-AL Business Central Cloud

### ISSUE THREAD

**Issue by ssapra28** [microsoft/AL#7621]
Hello Everyone,

I am working with a task where we need to encrypt data using RSA and SHA256 in Business Central Cloud, what methods can we use.

When we are using Cryptography Management and RSACryptoServiceProvider functions and getting below error:

**A DotNet variable has not been instantiated. Attempting to call System.Security.Cryptography.RSACryptoServiceProvider.ToXmlString in CodeUnit RSACryptoServiceProvider Impl.: ToXmlString**

**Comment by nndobrev** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://www.dynamicsuser.net/nav)
