### ISSUE TITLE
How to encrypt data using A128CBC-HS256 Algorithm in saas business Central.

### ISSUE THREAD

**Issue by VarunGarg99** [microsoft/AL#7623]
Hi Everyone,

I am working on a task where i need to encrypt API JSON body using A128CBC-HS256 algorithm, I can encrypt body by HS256 using Cryptography Management Codeunit but how do i encrypt it with A128CBC?

Can Anyone please help?

**Comment by nndobrev** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://www.dynamicsuser.net/nav)
