### ISSUE TITLE
Unexpected value 'NoConversion' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.ConversionKind'

### ISSUE THREAD

**Issue by sergiogp1** [microsoft/AL#7626]
**1. Describe the bug**
My environment in SaaS can't upgrade to v23.0 because it's throwing this compilation error: 

_Per-tenant extension 'XYZ' version 1.0.0.25 by 'ABC' failed to compile. Failure while emitting method. Object:'Codeunit "ABC Create Item Jnl. Lines"' Method:'SetLine(var Record "ABC Staging Order Item" temporary)' (Unexpected value 'NoConversion' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.ConversionKind') Unexpected value 'NoConversion' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.ConversionKind'_

**2. To Reproduce**
Unable to reproduce in my local environment with v23.0 in app.json. The code is like this:

```
codeunit 70002 "ABC Create Item Jnl. Lines"
{
    TableNo = "ABC Staging Order Item";
    
    trigger OnRun()
    begin
        SetLine(Rec);
    end;

    internal procedure SetLine(var StagingOrderItem: Record "ABC Staging Order Item" temporary)
    begin
    ...
```

**3. Expected behavior**
I expect that the environment can upgrade.

**4. Actual behavior**
Environment can't upgrade

**5. Versions:**

- AL Language: Unknown (I guess 12.1)
- Visual Studio Code: None
- Business Central: 23.0

### Final checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue
* [X] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Is this table "ABC Staging Order Item" in the same app or another PTE that this depends on? This looks like a dependency issue where the other table cannot be found and thus the type of Rec is not resolved

**Comment by sergiogp1** [comment]
Yes, it's in the same app. That code has been working for 2 years at least.

**Comment by sergiogp1** [comment]
I found the reason of the error. I will open a new issue and close this one.
