### ISSUE TITLE
AL:Go don't open automatic a workspace folder in another location than users documents

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#763]
When I use the AL:Go! command, I'm ablet to enter a folder:
![grafik](https://user-images.githubusercontent.com/15800069/31535577-e39ab3e8-affb-11e7-9c23-aa1683e5d5d2.png)
![grafik](https://user-images.githubusercontent.com/15800069/31535644-1cce14e8-affc-11e7-8ae8-34657c87dfb6.png)

Than I change the folder to a different drive:
![grafik](https://user-images.githubusercontent.com/15800069/31535616-00ab0f00-affc-11e7-8364-a4077f0083fb.png)

After ENTER I get the following message:
![grafik](https://user-images.githubusercontent.com/15800069/31535679-3ccb86d6-affc-11e7-8f7d-eabd70dcccad.png)

The new workspace was still created, but won't be opened:
![grafik](https://user-images.githubusercontent.com/15800069/31535723-60b1a594-affc-11e7-96e8-e99fa69bdce4.png)

**Comment by yrest** [comment]
Same here [https://github.com/Microsoft/AL/issues/759](https://github.com/Microsoft/AL/issues/759)

**Comment by megel** [comment]
it should be the same problem.
