### ISSUE TITLE
codeunit 99000770 "Where-Used Management" procedure BuildWhereUsedList add value to TempWhereUsedList."Production BOM No."

### ISSUE THREAD

**Issue by Michel-up** [microsoft/AL#7630]
Please include the following with each issue:

**1. Describe the bug**
The "Production BOM No." in Record "Where-Used Line" is always empty,
when filled it will show in which "Production BOM No." the item is being used (Page Prod. BOM Where-Used (99000811, Worksheet)

**2. To Reproduce**

1. Go to 'Prod. BOM Where-Used' from 'Item Card' Page
2. you will notice that the column "Production BOM No." is always empty

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
fill the "Production BOM No." , code snipet below 

in codeunit 99000770 "Where-Used Management, procedure BuildWhereUsedList
``` AL
 TempWhereUsedList."Version Code" := VersionMgt.GetBOMVersion(No, CalcDate, true);
    //Add Line Below
    TempWhereUsedList."Production BOM No." := No;
 
   OnBeforeWhereUsedListInsert(TempWhereUsedList, ItemAssembly, CalcDate, Quantity);
   TempWhereUsedList.Insert();
```

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: 12.5.914975
- Visual Studio Code: 1.85
- Business Central: 23.1
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
I do not see a clear repro. And this issue does not seem to be related to the latest pre release version of teh AL compiler.
Please try the same question on repos dealing with actual developing apps. LIke BCApps
