### ISSUE TITLE
[AL Exlorer] Caches symbols and shows wrong source code after symbol update

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/AL#7636]
Please include the following with each issue:

**1. Describe the bug**
When you modify symbols (add/delete) in .alpackages folder the AL Explorer doesn't update which can lead to confusement since the developer thinks that AL exlorer shows the CURRENT Symbols in the .alpackage folder.

**2. To Reproduce**
1. Delete all symbols in .alpackages
2. Download symbols (AL: Download Symbol) from environment (ex. Prod) that contains dependency symbols ( I did this for an OnPrem installation but it shouldn't matter).
3. Restart Visual Studio code
4. Let it build environment
5. Open AL Explorer, go to a source code for an object that you have changed in the second environment.
6. Delete all symbols in .alpackages
7.  Download symbols from second environment (dev) where you have made changes to the object
8.  Open AL Explorer and go to the source of the object and it still shows the source for the object in the first environment

**3. Expected behavior**
I would expect that AL Explorer reindexes the symbols once there are file changes the .alpackages folder or at least reindexes the symbols when it runs AL: Download Symbols

**4. Actual behavior**
It seems like AL Explorer caches the source code when the repo is opened and it doesn't get refreshed when you choose AL Download Symbols OR do updates to the folder. 

**5. Versions:**

- AL Language: v13.0.921843
- Visual Studio Code: 1.85.1
- Business Central: BC 22.5
- List of Visual Studio Code extensions that you have installed: New profile with ONLY AL Language

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [N/A] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
On the one hand, for certain operations we do not reload symbols after the first load, so it could be that this is by design. On the other hand, AL explorer is a visual tool, so I'm marking this for triage.

**Comment by PooyaKharamesh** [comment]
This behavior is  embedded in the current design, however, it is, a great idea.! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
