### ISSUE TITLE
AL: Go! does not set platform in app.json

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7638]
**1. Describe the bug**
`AL: Go!` does not set the `platform` property according to the target platform.

**2. To Reproduce**

1. Hit F1, then `AL: Go!`.
2. Choose the latest target platform version, e.g. 12.0.
3. Open the `app.json` and check the `platform` property.

**3. Expected behavior**
The platform `property` should be set dynamically, just as the `application` and `runtime` already are.
See also [example from standard code](https://github.com/microsoft/BCApps/blob/29fac541e9ceec74c6539fcbe0184a776477e9c7/src/Tools/Performance%20Toolkit/App/app.json#L38): version 24.0.0.0 is used.

**4. Actual behavior**
App.json:
``` JSON
  "platform": "1.0.0.0",
```
Or maybe there is a good reason to choose 1 as the minimum value?
The [docs](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#appjson-file) are totally unclear about which value to choose (the Symbol link does not point to the right content, it seems):
![image](https://github.com/microsoft/AL/assets/34504100/3bee469c-e0e4-4308-b298-2cddc184e460)

**5. Versions:**

- AL Language: 12.5.914975

**Comment by NKarolak** [comment]
It seems the docs article above is supposed to forward to this link: https://learn.microsoft.com/en-us/dynamics365/business-central/application/system/module/system. I think I know now how to fix the docs ... However, the `AL: Go!` issue is still open ;-)

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

If you do need the newer version of the platform, then you can specify that.
