### ISSUE TITLE
How can you access the API of a marketplace's app?

### ISSUE THREAD

**Issue by KevinRomanp** [microsoft/AL#7639]
**1. Describe the bug**
We're selling an app in the marketplace. There's a table that keeps changing overtime. We update that table manually and after we update it, we want to use a button to send the update to all of our clients and update that same table.

This is the documentation we found:
https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols

But we're having issues with the secret. We haven't been able to let the app read the secret.

We don't understand if our marketplace app should read the secret or if the client's extension should read the secret.

**Comment by SBalslev** [comment]
If you want to connect from your service to BC environments, then you can find samples and links here: https://github.com/microsoft/BCTech/tree/master/samples/VSCRestClientOAuthBCAccess

If you want to connect from an installed BC App to another service using OAuth you can find samles and useful links here: https://github.com/microsoft/BCTech/tree/master/samples/OAuth2Flows
