### ISSUE TITLE
Convertion of OemText to Text fails

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#764]
Used this version with the current DevPreview of NAV:
![grafik](https://user-images.githubusercontent.com/15800069/31536324-7723e4ca-affe-11e7-8820-7bf0d26fde27.png)

My ```app.json``` contains:
```json
{
  
  "target": "Internal"
}
```

I have reduced the problem to the following code snipped:
```javascript
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var Object:      Record Object;
        name:        Text;
        companyName: Text;
    begin
      if Object.FindSet then
      begin
          // *** This convertion fails: OemText to Text ***
          name        := Object.Name;
          companyName := Object."Company Name";
      end;

      Message('First Object: %1 (company: %2)', name, companyName);
    end;
}
```

When I open the ```Customer List``` this message is displayed:
![grafik](https://user-images.githubusercontent.com/15800069/31536146-e55a8c2e-affd-11e7-901b-d591ec90580b.png)

Is there another way to convert the OemText into a valid string?

**Comment by StanislawStempin** [comment]
We'll investigate and get back to you on this one.

**Comment by mortenbraemer** [comment]
#1313
