### ISSUE TITLE
Code Coverage shows field triggers without the field name.

### ISSUE THREAD

**Issue by spesotskiy** [microsoft/AL#7641]
**1. Describe the bug**
AL Code Coverage page shows the field triggers without the field name, so it is not possible to find code related to a certain field without looking through AL source file.

**2. To Reproduce**

1. Open page `AL Code Coverage (130460, Worksheet)`, Set `Object Id Filter` to `36`
2. On `Page 130460`: Start the coverage
3. Create a new `Sales Order` and put any customer code to `Sell-to Customer No.` field
4. On `Page 130460`: Stop the coverage; Refresh.
5. See the lines of code coverage. Try to find `Sell-to Customer No. - OnValidate()` line to see if it is all covered.

**3. Expected behavior**
The code coverage line for a field trigger must include the field name, so you can recognize triggers easily., like it is in the standard error call stack string, e.g.
- "Sales Header"(Table 36)."**Bill-to Customer No. -** OnValidate"(Trigger) line 37 - Base Application by Microsoft
- "Sales Header"(Table 36)."**Sell-to Customer No. -** OnValidate"(Trigger) line 104 - Base Application by Microsoft

**4. Actual behavior**
All field triggers are listed without field names:
<img width="290" alt="image" src="https://github.com/microsoft/AL/assets/16445780/6d6ee079-4b31-441a-b72b-bb185fe1ce63">

**5. Versions:**
- AL Language: v13.0.921843
- Visual Studio Code: 1.85.1
- Business Central: US Business Central 23.2 (Platform 23.0.14707.0 + Application 23.2.14098.14755)

**Comment by spesotskiy** [comment]
By the way, the line number that is shown in the call stack :
   - "Sales Header"(Table 36)."Bill-to Customer No. - OnValidate"(Trigger) **line 37** - Base Application by Microsoft

does not correspond with the line numbers in code coverage. This is the number of the line counting from the start of the function/trigger. So, I need to find the number of the function line first, then add 37, to get the line number in the source file and in code coverage table.
Also, such a relative number does not help to find which of the overloaded functions is called, as there are no params in the call stack and relative line number cannot help at all. 
Just put absolute line numbers like in Code Coverage data.

So, the **expected behavior** section should be:
1.  The field trigger line must include the field name in `Code Coverage` table. Not `Trigger OnValidate()`, but `Bill-to Customer No. - OnValidate"(Trigger)`
2.  There must be absolute line numbers instead of relative in the `Call Stack` message.

**Comment by kalberes** [comment]
Sorry Stan. This is a runtime issue.  
If you can trigger a Request For Hotfix I am sure it will be considered.

![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
