### ISSUE TITLE
Package cache doesn't support subfolders with .app files

### ISSUE THREAD

**Issue by kine** [microsoft/AL#7644]
**1. Describe the bug**
When app files (symbols) are downloaded by another way than by "Download Symbols" action into the package cache folder (e.g. through NuGet packages) and they are placed into subfolders, they are not visible to AL Language extension. 

**2. To Reproduce**
1. Create project with some code using standard objects
2. Download symbols 
3. Move one symbol file into new subfolder in the .alpackages folder
4. Reload VSCode
5. The compiler will show error like "A package with publisher 'Microsoft', name 'Application', and a version compatible with 'XX.0.0.0' could not be found in the package cache folders: XXXX"

**3. Expected behavior**
.app file (symbol files) should be detected even in subfolders of the package cache folders.

**4. Actual behavior**
.app files (symbols) are detected only directly in the package cache folders.

**5. Versions:**

- AL Language: 13.0.921843
- Visual Studio Code: 1.85.1
- Business Central: 23.2
- List of Visual Studio Code extensions that you have installed: AL Language extension

**Comment by NKarolak** [comment]
The issue looks related to #7636 (not identical).
