### ISSUE TITLE
[AL Language Syntax Highlights Devops] Some colors are not right

### ISSUE THREAD

**Issue by f4n0** [microsoft/AL#7645]
Please include the following with each issue:

**1. Describe the bug**
Using the devops extension "AL Language Syntax Highlights" there are a lot of colors not right:

1. Literal Names (action names, fields, etc.) Have only the Double quote colored, the rest still in plain text.
2. The ":" are in red. (normally the red color indicates an error)
3. Properties are the same color as their value. 

**2. To Reproduce**
Steps to reproduce the behavior: **Use it in Devops**

**3. Expected behavior**
Can we use the same syntax Highlighter as the one in VsCode? 

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

![image](https://github.com/microsoft/AL/assets/36199751/e7c1dfd8-8325-4203-aa1f-9a53adc1670a)

**5. Versions:**
AL Language Syntax Highlights for Microsoft Dynamics 365 Business Central:  **12.6.916372**

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by NKarolak** [comment]
I believe the answer is already given here:
https://github.com/microsoft/AL/issues/7617#issuecomment-1881498766

**Comment by f4n0** [comment]
unfortunately not. 
In my issue, there are some highlight bugs. 

> 1. Literal Names (action names, fields, etc.) Have only the Double quote colored, the rest still in plain text.
> 2. The ":" are in red. (normally the red color indicates an error)
> 3. Properties are the same color as their value.

Then yes, there is one thing that is similar to the issue you reference: 

>Can we use the same syntax Highlighter as the one in VsCode?

But the real problem here are the point 1-3

**Comment by EmilDamsbo** [comment]
**On point 1 - "_Literal Names (action names, fields, etc.) Have only the Double quote colored, the rest still in plain text._":** 
This was a deliberate design decision. As double quoted names are not strings, it felt inconsistent to highlight them as single quoted strings are. However, highlighting just the quotes at least calls awareness to when you are using a quoted name. This decision was made on the back of internal feedback pulling in either direction. As we've only had this one issue logged on this behaviour, we will not be addressing it at this time.

**On point 2 - "_The ":" are in red. (normally the red color indicates an error)_":** 
Yep, that's an actual issue. It's the reason why I am marking this issue as accepted.

**On point 3 - "_Properties are the same color as their value._":** 
Our answer is the same as what NKarolak mentioned: The syntax highlighting in VSCode also highlights property names and values the same. As an example, take this throwaway report snippet I made in VSCode using syntax highlighting:
![image](https://github.com/microsoft/AL/assets/67266681/33f913a3-8bc6-42c5-b1f4-59d8db3324c3)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.16028.0 and VS Code Extension Version 13.0.938391. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
