### ISSUE TITLE
VS Code all of a sudden giving error AL0197 and AL0118

### ISSUE THREAD

**Issue by anwars-dsvc** [microsoft/AL#7647]
We have a repo another developer pushed some changes, when pulled by me VS Code started showing AL0197 and AL0118 errors. We usually clone and work on repos in Onedrive location. Initially we thought its a UNC Path and we tried cloning the repo on Local Drive and the errors are still there.
The app doesn't have any extension and depends only on 

We tried following things and the problem is still there.
1. We cloned the repo on other machine and checked
2. We cloned the repo on Local Machine Document folder
3. Disabled AL language extension in VS Code, restarted the VS Code and enabled the extension again. The errors are still there.
4. Deleted and re-downloaded the symbols the errors are still there

**2. To Reproduce**
Can't reproduce.

Any suggestions or place we should look at to resolve this?
Thanks in advance.

**Comment by christianbraeunlich** [comment]
Reset to the commit before the pushed changes and reload VS Code

**Comment by rdebath** [comment]
Make sure the `rad.json` file and the generated `*.app` files are not in the committed repo; clear them from your working directory before rebuild. Turn off `"al.incrementalBuild": true,` before you trigger the rebuild.

Are you using the same version of the AL extension as your colleague? Eg have you or they loaded a vsix or blocked updates?

Some VSc extensions create cached and temp AL files, make sure you don't have any uncleaned leftovers from them. 

Remove any unnecessary APP files from the `.alpackages` directory. Especially an earlier version of this extension. Also best if these are NOT commited either.

If you have `"al.enableCodeAnalysis": true,` tuned on make sure you select the scope eg: `"al.backgroundCodeAnalysis": "Project",`

**Comment by kalberes** [comment]
No version, no clear repro. CLosing.
