### ISSUE TITLE
[AL Language VSC Extension] Debugging in Codespaces fails to show the code when hitting breakpoint

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/AL#7649]
Please include the following with each issue:

**1. Describe the bug**
When using GitHub Codespaces and a breakpoint is hit in the AL code, the execution seems to stop correctly (variables and database statistics are available in debug window), but source code isn't shown. Error:
<img width="1568" alt="image" src="https://github.com/microsoft/AL/assets/1463140/11a4855d-fef7-4f45-8e52-5890e8e511f9">

**2. To Reproduce**

1. Open an AL-Go repo inside a codespace
2. Setup your development environment and launch.json 
3. Set a breakpoint within your app code
4. Publish the app and do the according action in the web client to hit the breakpoint
5. Verify that the execution stopped and the debugger shows variables + database statistics but an error shows that the source code file can't be openend although it exists under the exact same path

Example Hello World App: https://github.com/lippertmarkus/MyAlGoRepoAppSource/blob/main/MyApp/HelloWorld.al#L9

**3. Expected behavior**
Source code where the breakpoint was hit should be shown.

**4. Actual behavior**
Error is shown:
```
The editor could not be opened due to an unexpected error: Unable to read file
'/workspaces/MyAlGoRepoAppSource/MyApp/HelloWorld.al'
(Unavailable (FileSystemError): Error: No file system handle registered (/workspaces))
```

Video:

https://github.com/microsoft/AL/assets/1463140/e1537cdd-45aa-4720-a73f-01894816d76b

**5. Versions:**

- AL Language: 13.0.921843
- Visual Studio Code: 1.85.2
- Business Central: sandbox-23.3.14876.15532-us
- List of Visual Studio Code extensions that you have installed: AL Language, COSMO Alpaca Preview

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by lippertmarkus** [comment]
Note: It also doesn't work with https://marketplace.visualstudio.com/items?itemName=StefanMaron.allanguagelinuxpatcher from @StefanMaron

**Comment by StefanMaron** [comment]
I noticed that it only works when accessing the codespace with local vs code running on Linux when you have a copy of the repository at the exact same location locally as it is in the codespace

**Comment by lippertmarkus** [comment]
Thanks for the feedback @StefanMaron. Maybe we can get a built-in fix which works everywhere from the AL-Team :)

**Comment by kalberes** [comment]
We do not have proper support for debugging within codespaces.  One of the issue being  the same file canonicalization issues you have seen.  What I can tell you is that it is in the timeline. ETA: "Good question"
