### ISSUE TITLE
Signing App Packages

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#765]
Let's ask a question about signing app packages. For this we need a code signing certificate as described in the help. However, as it has now been said at the EMEA that a lot of things will change at the start of the Tenerife version of Dynamics NAV, the question arose now whether this will also be done via certificates in the future. We would have to buy a certificate for the creation now, and that is not exactly cheap. The question therefore remains as to whether there will be something in the future, and whether the money will have to be invested here in the future.

**Comment by StanislawStempin** [comment]
There are no planned changes to the signing process.
