### ISSUE TITLE
I want a example of 3 couloms in a DataTable and how to insert data into it

### ISSUE THREAD

**Issue by Rami-Mezo** [microsoft/AL#7658]
Hi ,,,,, How create New DataTable It contains (1 couloms) and

How do copy the contents of 1 fields (Rec."No." ) value in the header (Sales Header) table to the New data table in

in AL Business Central 

===========================================================

pageextension 50100 "Sales Order Ext" extends "Sales Order"
{
    actions
    {
        modify(Post)
        {
            Trigger OnAfterAction()
            var 
                SalesHeaderRec: Record "Sales Header";
                SalesLineRec: Record "Sales Line";
            begin
                Message('Hello from Posted! 1');

                CLEAR(SalesHeaderRec);
                CLEAR(SalesLineRec);

                SalesHeaderRec.SETFILTER("No.", Rec."No.");
                SalesHeaderRec.FINDFIRST;
                
                Message('InvoiceID: %1', Rec."No.");

            end;

        }
    }

}

**Comment by BazookaMusic** [comment]
Hello, github issues is not a QA forum. It is reserved for issues in the AL compiler and related developer tooling. I would suggest that you take a look at the official documentation and microsoft learn for training material.
