### ISSUE TITLE
Error Message in Page: A member with name 'Description' is already defined

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#766]
I got an error message if an action has the same name as an field. 
> c:\Users\vmadmin\Simple Project\Item Test.al(12,15): error AL0155: A member with name 'Description' is already defined
> c:\Users\vmadmin\Simple Project\Item Test.al(26,14): error AL0155: A member with name 'Description' is already defined

It the classic Development Environment this is possible.

My Test File:
```
page 5273630 "Item Test"
{
  PageType=List;
  SourceTable=Item;
  layout
  {
    area(content)
    {
      repeater(Group1)
      {
        field(Description;Description)
        {
          Visible=false;
        }
      }
    }
  }
  actions
  {  
    area(navigation)
    {
      action(Description)
      {
        CaptionML=DEU='Beschreibung',
                  ENU='Description';
        Image=Entries;
      }
    }
  }
}
```

**Comment by esbenk** [comment]
This is by design. Previously in C/SIDE this was allowed for legacy reasons even though that it broke testability. This is no longer allowed.

**Comment by DanielGoehler** [comment]
Ok, thanks!
