### ISSUE TITLE
Custom List Page - Clear(rec) problem in Edit Mode

### ISSUE THREAD

**Issue by MedizinPumPer** [microsoft/AL#7663]
Please include the following with each issue:

**1. Describe the bug**
Build up a Custom Page for "Vendor Ledger Entry" with Custom Fields and Editable true property.
Filter is Set to `Document Type::Invoice`, `Open: true`
Custom Button with local Procedure:

`Clear(Rec);`
`SetPaymentVisible();`
`rec.reset();`
`rec.SetCurrentKey("Document No.");`
`rec.SetRange(Reversed, false);`
`rec.setRange(open, false);`
`if rec.FindSet() then;`
`rec.Ascending(true);`
`CurrPage.Update(false);`

Trigger The button on List-View Mode works Excellent and reset the `Open` Filter.
Now, im back in the Standard-View with `Open, true` and swith to the `List-Edit/Editable` mode (Noticed that here the OnOpenPage is triggered again).
Now in that Edit Mode, i trigger my Custom Button with the procedure, but the `Open` filter still exist and is set to `true`. I think there is a But in the System site. 

Base Application 23.3.14876

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
