### ISSUE TITLE
AA0072 - drives me mad, I can't find much info on the rule itself

### ISSUE THREAD

**Issue by simplyTrex** [microsoft/AL#7666]
var RecSibExtSetupTableRecord: Record Sib.BusinessCentralsAddons.SibExtSetupTable;

Where I can find a practical documentation that explain this rule? How should I rename this variable, to be able to get rid of the CodeCop AA0027?

I deeply apologize for posting this here. No idea where to go for answers and documentation plainly states some general things.

"The name of RecSibExtSetupTableRecord is not valid. The name of variables and parameters must be suffixed with the type or object name."

It makes no sense and trying to understand.

**Comment by dannoe** [comment]
Try SibExtSetupTable.

PS: In our projects we disable AA0027. (see also this yammer thread: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1602560331243520)

**Comment by simplyTrex** [comment]
Thank you but nope, the song remains the same:

`The name of SibExtSetupTable is not valid. The name of variables and parameters must be suffixed with the type or object name.`

It just drives me nuts. I did not wanted to disable it, I wanted to learn to format and name variable names as it is recommended, but in Microsoft Docs, it is just a vague description without any examples.

**Comment by dannoe** [comment]
Can not reproduce this with the newest AL vsix. (``Version: 12.6.936426``).
Could be caching problem. Can you try to reload or restart your vscode. (Ctrl+Shift+P -> Reload window)

**Comment by simplyTrex** [comment]
Thanks @dannoe.

Reloaded Window.

`The name of SibExtSetupTable is not valid. The name of variables and parameters must be suffixed with the type or object name.`

Switched to pre-release. Reload window. same issue.
Switch to release version. Reload window. Same issue.

**Comment by dannoe** [comment]
Can you maybe share a minimal project with this error? 

![grafik](https://github.com/microsoft/AL/assets/7450586/f812d198-3ef4-483c-82d8-2fab15d3d80d)

**Comment by dannoe** [comment]
The warning appears just on the ``Foo`` variable, which is correct. With the ``SibExtSetupTable`` variable I have no warning in my vscode.

**Comment by simplyTrex** [comment]
![image](https://github.com/microsoft/AL/assets/159697851/f6cc4561-1969-4e3c-b538-6aa4dee0987a)

How do you preffer me to share the project, I am new to this? It has two AL files.

**Comment by dannoe** [comment]
Zip it up and just drag and drop it into your input box here. (Do not include the ``.alpackage`` folder in the zip else you will exceed the upload limit on Github.)

PS: In your screenshot the variable name should be ``SiboneyExtSetupTable``.

**Comment by simplyTrex** [comment]
Do I get any credentials to take out?

**Comment by simplyTrex** [comment]
Daymn, if I named it SiboneyExtSetupTable, it went away, I am totally confused now!

**Comment by simplyTrex** [comment]
I did the same in the original project and it all went away. No more AL0072!

**Comment by dannoe** [comment]
Awesome. If it is resolved you can close this issue with the "Close issue" button under the input box.

**Comment by simplyTrex** [comment]
Oh wow. thank you. I need to read again from the beginning to check what really happened here. Thank you @dannoe . Muțumesc!

**Comment by simplyTrex** [comment]
This is closed, as it got resolved, thanks to above replies from @dannoe

**Comment by mjmatthiesen** [comment]
Highly recommend disabling this silly rule. AA0027 is asinine.

**Comment by simplyTrex** [comment]
I only activated it to try to learn what would be best practice recommended for naming variables and objects. Basically to be more catholic than the pope himself.
