### ISSUE TITLE
The type or method xxx cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#767]
Codeunit 12 - UnapplyCustLedgEntry
Table 5994 - SendProfile
Table 36 - IsApprovedForPostingBatch
Codeunit 1535 - DeleteApprovalEntry
Codeunit 1004 - FromPurchaseLineToJnlLine
Codeunit 1535 - PrePostApprovalCheckPurch

Need to have access to Profile Metadata table, as MS has create Profiles using config mode, we are not able to delete some actions on Role centers which are not required and must to remove from our end.

**Comment by StanislawStempin** [comment]
These methods are already all External on October Update. 

Profile access is tracked as part of #500

**Comment by pmohanakrishna** [comment]
Codeunit 1535 - DeleteApprovalEntry is not available.

these are new: do you want me to create new issue?

Table 38 - IsApprovedForPostingBatch
Table 110- SendProfile
Table 114- SendProfile

**Comment by pmohanakrishna** [comment]
any update?

**Comment by StanislawStempin** [comment]
Yes, please create a new issue for these. This one was already resolved as Won't Fix as thus not resulting in work item for the team.
