### ISSUE TITLE
Add a setting to not automatically add braces after procedure names

### ISSUE THREAD

**Issue by atheck** [microsoft/AL#7673]
When entering a procedure name in vs code and accepting the intelli sense, it automatically adds braces and sometimes even a semicolon. This often is not what I want. Is there a setting to disable this behaviour?

**Comment by kalberes** [comment]
No there is none. But it could be a good idea.
Hi,
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
