### ISSUE TITLE
The page contains a control add-in that is not permitted. Contact your system administrator Error in BC Insider build 24

### ISSUE THREAD

**Issue by srkkoneti** [microsoft/AL#7674]
Microsoft.Dynamics.Nav.Client.BusinessChart;PublicKeyToken=31bf3856ad364e35, The page contains a control add-in that is not permitted. Contact your system administrator.
Version: BC 24 Insider 24.0.16336.0

Following error message at Role Center page under insights area.
We have used the Business chart dll in the below image. But these are not having any issues with the BC 23 version
On cloud issue.

<img width="622" alt="image" src="https://github.com/microsoft/AL/assets/39953344/49c132ae-515b-45d8-9d49-cfca16641cd9">

Please let us know, how can we fix this, or if is it going to be fixed in the next minor of the insider build.

**Comment by sschuh** [comment]
Had the same issue:

This will work:
<img width="511" alt="image" src="https://github.com/microsoft/AL/assets/34685182/0a751402-b339-43a9-ae05-8175a32a553b">

<img width="481" alt="image" src="https://github.com/microsoft/AL/assets/34685182/5f7ded1a-2205-4471-bbbb-4b5d5a8a15c2">

**Comment by srkkoneti** [comment]
Yes, It worked.

Thanks,
