### ISSUE TITLE
Factbox OnLookUp not being executed 

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#7677]
**1. Describe the bug**
The **OnLookUp** trigger is not executed on the Factboxses.

**2. To Reproduce**
Create any simple fact box with a simple message example in it
field(TestText; TestText)
            {
                Caption = 'TestText';
                ApplicationArea = all;
                Lookup = true;

                trigger OnLookup(var Text: Text): Boolean
                begin
                    Message('The OnLookup Works!');
                end;
            }

**3. Expected behavior**
When you click "TestText"  - you see the expected message ('The OnLookup Works!). 

**4. Actual behavior**
When you click "TestText"  - you do not see the expected message. 

**5. Versions:**

- AL Language: Version 12.6
- Visual Studio Code: Version: 1.73.1 (user setup)
- Business Central: 23.1
- List of Visual Studio Code extensions that you have installed: -

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
