### ISSUE TITLE
Number Sequence is very slow on Cloud environments

### ISSUE THREAD

**Issue by Drakonian** [microsoft/AL#7678]
Please include the following with each issue:

**1. Describe the bug**
NumberSequence is slowest way to get next number in **Cloud** Business Central. 
Each [NumberSequence.Next](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/numbersequence/numbersequence-next-method) take 3ms 
![image](https://github.com/microsoft/AL/assets/16802407/5e911ea2-f11d-46ee-b9a3-e609406dcc94)

In my analysis, I came to the conclusion that the issue is a slow hard disk for Cloud Business Central.

One of the possible ways to improve performance it's to add CACHE parameter upon [NumberSequence.Insert](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/numbersequence/numbersequence-insert-method)
In this case we can reduce number of IOs for [SQL Server NumberSequence](https://learn.microsoft.com/en-us/sql/relational-databases/sequence-numbers/sequence-numbers) object

More information in article https://vld-nav.com/number-generation-performance-cloud

I don't have partner account, so if you think this isn't the right place, **I won't be able to create a ticket**.

**2. To Reproduce**

Create number sequence and call it in loop in Cloud Business Central.

``` AL
NumberSequence.Insert('TestPerformance');
for i := 1 to 100000 do
    NumberSequence.Next('TestPerformance');
```

**3. Expected behavior**
It should work at least faster than Rec.Modify()/UPDATE statement in AL/SQL.

**4. Actual behavior**
It's super slow.

**5. Versions:**

Latest available Cloud Business Central

**Comment by kalberes** [comment]
We cannot help you if you do not have a partner account. 
Try with the repos for AL developers (e.g the repo for the system application) . Maybe they have better ideas and experience.
Nevertheless it is not for this repo.
