### ISSUE TITLE
Go to Definition-Error: Unable to open 'Regions.al': resource is not available.

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#768]
It try to **Go to Definition** on  "Countries/Regions" and got the error message:
> Unable to open 'Regions.al': resource is not available.

Releated Object:
```
pageextension 70000003 pageextension70000003 extends "Countries/Regions" 
{
[..]
```

**Comment by StanislawStempin** [comment]
This is most likely a bug related to the fact that there is a backslash in the object name. We will investigate further.
