### ISSUE TITLE
AL:FindEvent slow. Not preloading but loading on demand

### ISSUE THREAD

**Issue by ewaldventer** [microsoft/AL#7680]
**1. Describe the bug**
Using AL:FindEvent takes ages to load as it seems to load on demand instead of on load of solution.

**2. To Reproduce**
When editing a file and attempting to subscribe to an event, use the AL:FindEvent function from the command palette.
Depending on the size of the project and number of dependencies, this might take quite a while to load.

Is there possibly a way to load this in the background *after* the solution has loaded?

Using v12.6.936426

**Comment by qutreson** [comment]
Thank you for the suggestion, but this is beyond the scope of a bug fix and is rather a feature suggestion. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
