### ISSUE TITLE
Download symbols not working for version 23.5.16502.17404

### ISSUE THREAD

**Issue by srinebolt-ktl** [microsoft/AL#7686]
**1. Describe the bug**
Download symbols not working for version 23.5.16502.17404

**2. To Reproduce**

1. Create a Docker container using version 23.5.16502.17404 (Get-BCArtifactUrl -type "Sandbox" -select "Closest" -country "us" -version "23.5.16502.17404")
2. Go to VS Code and create an AL project (install AL extension with pre-release)
3. Configure launch.json to point to the container
4. Run AL: Download Symbols

**3. Expected behavior**
Symbols download without issue

**4. Actual behavior**
[2024-03-15 10:25:46.04] This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 12.2
- Web API: 6.0
- Debugger: 6.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 7.0, 7.1, 7.2, 8.0, 8.1, 9.0, 9.1, 9.2, 10.0, 10.1, 10.2, 11.0, 11.1, 12.0, 12.1, 13.0, 14.0
- Supported Web API: 1.0, 2.0, 3.0, 4.0, 5.0, 6.0
- Supported debuggers: 1.0, 2.0, 3.0, 4.0, 5.0, 6.0

**5. Versions:**

- AL Language: 14.0.956192
- Visual Studio Code: 1.87.2
- Business Central: 23.5.16502.17404
- List of Visual Studio Code extensions that you have installed: AL extension

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by srinebolt-ktl** [comment]
I was already on pre--release. I have since uninstalled and reinstalled and am running the pre-release with the same error.

Get Outlook for iOS<https://aka.ms/o0ukef>

Scott Rinebolt
Software Development Manager
Office:301-360-0001
Direct:301-329-2808
KTL Solutions, Inc. – Disclaimer  This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited. 
________________________________

**Comment by srinebolt-ktl** [comment]
I'm not sure what changed, but when I opened VS Code this morning the AL Extension extension showed that a reload was required. I reloaded VS Code and can now download symbols.

***@***.***?anonymous&ep=bwmEmailSignature>
Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>


Scott Rinebolt
Software Development Manager
Office:301-360-0001
Direct:301-329-2808
KTL Solutions, Inc. – Disclaimer  This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.

**Comment by qutreson** [comment]
We released new versions of the AL Language extension to the VS Code marketplace (both the pre-release version and standard one) which should have resolved this issue. Closing then this issue, but let us know if you are still facing it.
