### ISSUE TITLE
"Sending notification workspace/didChangeConfiguration failed" error

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7687]
I have installed the latest released version 13.0.964488 of AL Language.

When I open VSC with multifolder workspace and no file is open in an editor from previous session, I get the error:
_[Error - 5:42:43 AM] Sending notification workspace/didChangeConfiguration failed_
But, when there is a file in the editor left open from previous session, everything is OK.

Note: Though I get the error, it seems everything works after that.

**Comment by NKarolak** [comment]
Already handled in #7664 (check the very lasts posts).

**Comment by RadoArvay** [comment]
Thanks, Natalie. I forgot to use "search", I have just checked last issues (I thought it is something new).

**Comment by NKarolak** [comment]
However, your observation was good:  By the time you open (not reload) VS Code, no AL file may be open, else the error appears. Other file types do not matter.

**Comment by RadoArvay** [comment]
Just a detail: I open (do click) any app.json mostly when I want to do something in a specific app and app.json (and I believe any file from any folder - I did not test it) is enough now to avoid the error.

**Comment by qutreson** [comment]
Closing this issue as duplicate of #7664 for which a fix will be provided in the next release of the AL extension for VS Code
