### ISSUE TITLE
Page Customization breaks translations for Page Extension

### ISSUE THREAD

**Issue by andersws** [microsoft/AL#7688]
**1. Describe the bug**
When i create a page customazation on top of a page extension, the translation file gets messed up.
Meaning that all tooltips, captions etc. from the original page extension now is treated as fields on the page customization in the translation file.

**2. To Reproduce**
1. Enable TranslationFile feature in app.json
"features": ["TranslationFile"]

2. Create a standard page extension:
```
pageextension 50020 "AUZ Item Card" extends "Item Card"
{
    layout
    {
        addafter("No.")
        {
            field(AUZNo2; Rec."No. 2")
            {
                ApplicationArea = All;
                ToolTip = 'Specifies the tooltip.';
            }
        }
    }
}
```

Build to see expected behavior.

3. Create a page customization for the page.
```
pagecustomization "AUZ Item Card" customizes "Item Card"
{
    layout
    {
        modify(AUZNo2)
        {
            Visible = false;
        }
    }
}
```

**3. Expected behavior**
```
<trans-unit id="PageExtension 1717001217 - Control 3934353231 - Property 1295455071" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Page 1434786627">
   <source>Specifies the tooltip.</source>
   <note from="Developer" annotates="general" priority="2"></note>
   <note from="Xliff Generator" annotates="general" priority="3">PageExtension AUZ Item Card - Control AUZNo2 - Property ToolTip</note>
</trans-unit>
```

**4. Actual behavior**
```
<trans-unit id="PageCustomization 1717001217 - Control 3934353231 - Property 1295455071" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Page 1434786627">
   <source>Specifies the tooltip.</source>
   <note from="Developer" annotates="general" priority="2"></note>
   <note from="Xliff Generator" annotates="general" priority="3">PageExtension AUZ Item Card - Control AUZNo2 - Property ToolTip</note>
</trans-unit>
```

**5. Versions:**

- AL Language: 13.0
- Visual Studio Code: 1.87.2
- Business Central: 23.5 (N/A)
- List of Visual Studio Code extensions that you have installed: (N/A)

**Comment by NicolaiEsbensen** [comment]
We have the same issue, also present in the preview version of AL (14.x).

**Comment by LightValley** [comment]
We have the same problem and are forces to downgrade the AL extension to version 12.x. 
This is stopping us from developing to the new BC24 at the moment.

**Comment by qutreson** [comment]
Thanks for reporting this issue. We have already prepared a fix for it which will be part of BC 24 and of the next release of the preview version of the AL extension.
