### ISSUE TITLE
Caption changes can not be translated from a third App

### ISSUE THREAD

**Issue by IceOnly** [microsoft/AL#7690]
**1. Describe the bug**
If an app changed a caption of an exisiting control in a dependend app, this caption change can't be translated with an third App.

**2. To Reproduce**
1. Create an App A that adds a Field to the page like the Item Card
2. Create an App B that change the caption of this new Control of App A
3. Create an App B - Danish Translation App and place a danish translation of App B in it

**3. Expected behavior**
The controlshould have the danish translation if all three apps are published and danish language is selected

**4. Actual behavior**
The caption has the untranslated caption of App B

**5. Versions:**

I tried in in the latest sandbox. The oldest Version I tested was BC22.5

Sample code:
[TranslationIssue.zip](https://github.com/microsoft/AL/files/14664488/TranslationIssue.zip)

**Comment by thpeder** [comment]
Hi @IceOnly,
The problem is that in the language app are you using the trans-unit ID of the Change, not of the field.
```XML
        <trans-unit id="PageExtension 2122701710 - Change 678184728 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Page 1434786627">
          <source>Test Field App B</source>
          <target state="translated">DK - Testfelt App B</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">PageExtension ItemCardExtB - Change TestField - Property Caption</note>
        </trans-unit>
```` 
------>
```XML
        <trans-unit id="PageExtension 209611859 - Control 678184728 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Page 1434786627">
          <source>Test Field App A</source>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">PageExtension ItemCardExtA - Control TestField - Property Caption</note>
        </trans-unit>
```

**Comment by IceOnly** [comment]
And how can you automate the whole thing? Why does the translation file work if it is part of App B?
The translator needs to translate the source of the change, not of the orginal fieldcaption.

So the Trans Unit ID is already wrong in App B? Then there is an error in the compiler after all.
