### ISSUE TITLE
[Bug] [BC24] Go to Definition for Moved Table Object (e.g. "No. Series", "No. Series Line") - Unable to resolve text model content for resource

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7693]
Please include the following with each issue:

**1. Describe the bug**
I receive the follwoing when I try to DrillDown to "No. Series Line"
> The editor could not be opened due to an unexpected error: Unable to resolve text model content for resource al-preview://allang/MainApp/Table/309/No.%20Series%20Line.dal

![image](https://github.com/microsoft/AL/assets/56249171/b6bb96cb-6383-448b-ac73-0cd50ce28924)

**2. To Reproduce**

1. Try to use "Go to Definition" on "No. Series Line"

``` AL
    local procedure Dummy()
    var
        NoSeriesLine: Record "No. Series Line"; 
    begin
       ...
    end;
```

**3. Expected behavior**
It should be possible to DrillDown to any Object

**4. Actual behavior**
Currently I receive this strange error.
Maybe this is related to the case, that the "No. Series Line" was moved to the "Business Foundation Layer"

**5. Versions:**
- AL Language: v14.0.963280 (pre-release)

**Comment by mjmatthiesen** [comment]
I can confirm the same issue.

**Comment by PooyaKharamesh** [comment]
Thank you for reporting this issue. This problem with goto definition on the moved objects, is fixed. The fix will be available in the next version of AL language extension.
