### ISSUE TITLE
AA0218 should no longer trigger on pages if ToolTip is defined on a table field

### ISSUE THREAD

**Issue by tinestaric** [microsoft/AL#7696]
**1. Describe the bug**

When moving the ToolTip from the PageField to the TableField, AA0218 is still triggered on PageField.

**2. To Reproduce**

![image](https://github.com/microsoft/AL/assets/42935028/5eb736aa-1314-451d-abd0-67622b0acfb9)

![image](https://github.com/microsoft/AL/assets/42935028/619b1dcb-9775-4bd7-ac22-ef06b093fc75)

Page:
```
page 30163 "Shpfy Metafields"
{
    Caption = 'Shopify Metafields';
    PageType = List;
    SourceTable = "Shpfy Metafield";
    UsageCategory = None;
    ApplicationArea = All;

    layout
    {
        area(Content)
        {
            repeater(Metafields)
            {
                field(Namespace; Rec.Namespace)
                {
                }
            }
        }
    }
}
```
Table:
```
table 30101 "Shpfy Metafield"
{
    Access = Internal;
    Caption = 'Shopify Metafield';
    DataClassification = CustomerContent;
    DrillDownPageId = "Shpfy Metafields";
    LookupPageId = "Shpfy Metafields";

    fields
    {
        field(1; Id; BigInteger)
        {
            Caption = 'Id';
            DataClassification = SystemMetadata;
            Editable = false;
        }

        field(2; Namespace; Text[255])
        {
            Caption = 'Namespace';
            DataClassification = SystemMetadata;
            ToolTip = 'Specifies the namespace of the metafield.';
        }
    }
}
```

**3. Expected behavior**

No warning, if ToolTip is defined on Table Field

**4. Actual behavior**

Warning on Page Field, even though ToolTip is defined on the Table Field

**5. Versions:**

- AL Language: both v13.0.964488 and the prerelease version 
- Visual Studio Code: 1.87.2
- Business Central: 24.0 (runtime 13)

**Comment by BazookaMusic** [comment]
Thank you for reporting this. We know about this bug already and it will be fixed soon with the next release of the extension.

**Comment by BazookaMusic** [comment]
This should be fixed in the latest release.
