### ISSUE TITLE
Wrong capitalization of object types on "Implement interface"

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7699]
**1. Describe the bug**
Code action "Implement interfaces" uses a wrong capitalization of object types within parameters.

**2. To Reproduce**

1. Create the following interface
``` AL
interface MyInterface
{
    procedure Test(TestEnum: Enum "AFS Write"; var SalesPost: Codeunit "Sales-Post")
}
```
2. Create the following empty codeunit:
``` AL
codeunit 50000 MyImpl implements MyInterface
{
}
```
3. On the first codeunit line, run code action "Implement interface".

**3. Expected behavior**
Implemented procedure:
``` AL
    procedure Test(TestEnum: Enum System.Azure.Storage.Files."AFS Write"; var SalesPost: Codeunit Microsoft.Sales.Posting."Sales-Post")
    begin

    end;
```

**4. Actual behavior**

Implemented procedure:
``` AL
    procedure Test(TestEnum: enum System.Azure.Storage.Files."AFS Write"; var SalesPost: codeunit Microsoft.Sales.Posting."Sales-Post")
    begin

    end;
```

**5. Versions:**
- AL Language: 13.0.971907

**Comment by krupybalu** [comment]
Hi @NKarolak ,

Thank you for the issue.
We have investigated it further and found that it is not possible for us, at this point, to keep the original formatting.
