### ISSUE TITLE
No validation for tablerelation property

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#77]
I created a field in Job Setup with tablerelation to new field.
The field is allowing to add any values which are not in new table.

![table relation validation](https://cloud.githubusercontent.com/assets/23735402/22014563/5ff16c68-dcc4-11e6-9ed5-81ebede20185.png)

**Comment by esbenk** [comment]
To get validation you need to set 

`ValidateTableRelation = true;`

on the field.

The documentation can be found here. Notice that the TestTableRelation is not in use anymore.

https://msdn.microsoft.com/en-us/library/dd338934(v=nav.90).aspx

**Comment by pmohanakrishna** [comment]
Perfect. thanks
