### ISSUE TITLE
Error AS0049 on enum even after previous obsoletion.

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7700]
Related to #5997 from 2020:

In my previous app version, I've obsoleted an enum object.
As long as the removed table field it is still attached to cannot be physically removed, I won't be ever able to delete the enum. Therefore, I'd like to set it internal at least.

But even with an obsoletion in the previous version, the enum object in the current version will error on compile:

> The access modifier of the Enum '...' cannot be changed to a value that provides less access. ([AS0049](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0049))

**Versions:**

- AL Language: 13.0.971907, but runtime 11.1

**Comment by nndobrev** [comment]
Hi @NKarolak, I see where the issue is unfortunately, although not ideal this is by design.
