### ISSUE TITLE
Security FIlter switches to obsolete field

### ISSUE THREAD

**Issue by AndrHrnk** [microsoft/AL#7706]
Hello,

I am experiencing the following issue: when I set the security filter for the table 38 Purhcase Header, I set the filter for the field 

Repro steps:
1. Open any Permission Set that contains table 38 Purchase Header (or create one).
![image](https://github.com/microsoft/AL/assets/166102831/6f22f3a1-9221-40a7-ac77-ed3ba5d65fe6)
2. Press Assist Edit (...) on Security Filter field
3.  In the pop-up that opens set a filter for Journal Template Name field
![image](https://github.com/microsoft/AL/assets/166102831/22ab7a43-2aa6-4414-af3f-82f6722cc2c0)
4. Press Close on a pop-up window.
5. The Security Filter is filled in but the value is incorrect. 
![image](https://github.com/microsoft/AL/assets/166102831/55342f6f-eee5-4e4a-9f77-9835a17e7e41)
It uses field 11300 Template Name(obsolete) instead of the Journal Templ. Name field that was specified.
![image](https://github.com/microsoft/AL/assets/166102831/ed8bb0e4-f550-4250-8d93-ffbefaa995d9)

My BC version:
Version: BE Business Central 21.7, XPC 11.0, LQS 4.0 (Platform 21.0.56004.0 + Application 21.1.48363.48638)

Please let me know if that can be fixed. Thanks.

Please include the following with each issue:

**1. Describe the bug**

**2. To Reproduce**

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

Please include the following with each issue:

**1. Describe the bug**

**2. To Reproduce**

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
