### ISSUE TITLE
Unexpected warning AL0697 when an object is added to an entitlement through a permissionsetextension

### ISSUE THREAD

**Issue by Jeeve65** [microsoft/AL#7712]
**1. Describe the bug**
We have an app that uses entitlements. Entitlements reference PermissionSet objects, and PermissionSet objects can be extended using PermissionsetExtension objects. Now, we have an object in a permissionsetextension object that extends a permissionset that is part of an entitlement. Here we get warning AL0679 that the object is not included in any entitlement.

**2. To Reproduce**
Create the following objects in a new app:

codeunit 50100 "AL0697 issue 1" { }
codeunit 50101 "AL0697 issue 2" { }
permissionset 50100 "AL0697 issue"
{
    Assignable = true;
    Permissions =
        codeunit "AL0697 issue 1" = X;
}
permissionsetextension 50100 "AL0697 issue extension" extends "AL0697 issue"
{
    Permissions =
        Codeunit "AL0697 issue 2" = X;
}
entitlement "AL0697 issue"
{
    Type = Unlicensed;
    ObjectEntitlements = "AL0697 issue";
}

**3. Expected behavior**
No warning

**4. Actual behavior**
Warning AL0697 is shown:
The application object 'Codeunit "AL0697 issue 2"' is not included in any entitlement and will therefore not be accessible in the cloud.

**5. Versions:**
- AL Language: v14.0.983287 (pre-release)
- Visual Studio Code: 1.88.0 (system setup)
- Business Central: 24
- List of Visual Studio Code extensions that you have installed: AL, Insert GUID, Powershell
Internal work item: [AB#524803](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524803)

**Comment by BazookaMusic** [comment]
Another bug with objects and extensions in the same app
