### ISSUE TITLE
page 13, email editor will not close when email message is html formated

### ISSUE THREAD

**Issue by areberger** [microsoft/AL#7713]
Lock in page 13 Email Editor when using codeunit 8904 Email Message,

EmailMessage.Create('', '', '', true) where it is html formatted. 
Email.OpenInEditor(EmailMessage, Enum::"Email Scenario"::Default);

Page 13:
If you type in receipient it disappers.
Two body sections appears
Page can't be closed.

Works if html formatted is false
![email](https://github.com/microsoft/AL/assets/65893051/2e2d4d86-176f-4f6b-940d-654bf2b913ad)

**Comment by BazookaMusic** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
