### ISSUE TITLE
Switching page view unexpectedly initializes global page variables

### ISSUE THREAD

**Issue by jhoek** [microsoft/AL#7717]
Please include the following with each issue:

**1. Describe the bug**
When users switch between (built-in or user-defined) page views, the page's global variables are reinitialised, thus losing the page "state".

**2. To Reproduce**

1. Run the following page, populate the "Test" column for a few of records.
1. Press F5 to verify that the page state is maintained.
1. Create a user-defined view, e.g. one that filters on the Name field = '\*a\*'.
1. In a record that satisfies the view's criteria, type a value into the "Test" column.
1. Switch back to the "All" view and note that the value entered in the previous step is lost. 

``` AL
page 50100 Test
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = Customer;

    layout
    {
        area(Content)
        {
            repeater(Control1)
            {
                field("No."; Rec."No.") { }
                field(Name; Rec.Name) { }
                field(Test; MyInteger)
                {
                    BlankZero = true;

                    trigger OnValidate()
                    begin
                        MyGlobal.Set(Rec."No.", MyInteger);
                    end;
                }
            }
        }
    }

    trigger OnAfterGetRecord()
    begin
        MyInteger := 0;

        if not MyGlobal.Get(Rec."No.", MyInteger) then;
    end;

    var
        MyInteger: Integer;
        MyGlobal: Dictionary of [code[20], Integer];
}
```

**3. Expected behavior**
Switching views, like refreshing the page with F5, should retain it's state (i.e. it's global variables).

**4. Actual behavior**
State is lost.

**5. Versions:**

- AL Language: v13.0.971907
- Visual Studio Code: Version: 1.88.0
- Business Central: NL Business Central 23.5 (platform 23.0.18033.0 + toepassing 23.5.16502.16589)
- List of Visual Studio Code extensions that you have installed: n/a

### Final Checklist

Please remember to do the following:
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
This is a runtime issue and potentially a breaking change, so not fit for this repository.

Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

Open a support request to CSS through the PartnerSource portal
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
