### ISSUE TITLE
/ in name of record breaks symbol building

### ISSUE THREAD

**Issue by Itexu** [microsoft/AL#7720]
**1. Describe the bug**
If downloading symbols and a there is a record (might be other objects) that contains a / in its name, the compiler cant read it.
Happens with C/AL Table 823 "Name/Value Buffer".
Considering this is a default table and you can also name objects containing a /, this seems to be a bug.

It seems to happen only as parameter.

You get the message:
Argument 5: cannot convert from 'Record "Name/Value Buffer" temporary' to '__MissingTypeSymbol__'

**2. To Reproduce**
1: Have version of "AL Language extension for Microsoft Dynamics 365 Business Central" greater than version 11.7 (latest correct working version)
2: Have a Table containing a / (like C/AL Table 823 "Name/Value Buffer")
3: Have procedure with that object as a parameter in an extension.
4: Call that procedure from a different extension
5: Execute "AL: Download Symbols" (in pop-up menu)
6: Try to compile

``` AL
codeunit x "CallingCodeunit"
{
local procedure CallingFunction()
var
        ltrecNameValueBuffer: Record "Name/Value Buffer" temporary;
        lcunCodeunitInOtherExtension: Codeunit CodeunitInOtherExtension;
begin
        lcunCodeunitInOtherExtension.FunctionInOtherExtenstion(ltrecNameValueBuffer);
end;
}

codeunit y "CodeunitInOtherExtension"
{
procedure FunctionInOtherExtenstion(var ptrecNameValueBuffer: Record "Name/Value Buffer" temporary)
begin

end;
}
```

**3. Expected behavior**
Correct reference of symbols so it can be compiled

**4. Actual behavior**
Generates error:
Argument 5: cannot convert from 'Record "Name/Value Buffer" temporary' to '__MissingTypeSymbol__'

**5. Versions:**

- AL Language: (Platform/application/runtime) 14.0.0.0/14.0.0.0/3.2
- Visual Studio Code: 1.88.1
- Business Central: 14.0.47686.0
- List of Visual Studio Code extensions that you have installed:
- AL Language Extension: 13.0.971907

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
Version 14 aka C/SIDE is not supported anymore.
Official answer:
![image](https://github.com/microsoft/AL/assets/12760483/f5e64b92-1e6a-439c-ae61-a23614615bfd)
