### ISSUE TITLE
ALDoc: Support Newer DocFx Version

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#7724]
**1. Describe the bug**
This is not a bug, but a request to support a new docfx version. Currently the only output choice is html, [with 2.71, support was added for markdown](https://github.com/dotnet/docfx/issues/684#issuecomment-1741710547). Markdown is more useful for how we typically publish. We already have existing infra for our docs and markdown works well. Right now I use html to markdown tools to get something close.

**2. To Reproduce**
N/A

**3. Expected behavior**
Option to generate markdown

**4. Actual behavior**
Generates html

**5. Versions:**

- AL Language: v13
- Visual Studio Code: Yes
- Business Central: Yes
- List of Visual Studio Code extensions that you have installed: No

### Final Checklist

Please remember to do the following:

* [x ] Search the issue repository to ensure you are reporting a new issue

* [ x] Reproduce the issue after disabling all extensions except the AL Language extension

* [ x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
