### ISSUE TITLE
No published extensions match the specified parameter values.

### ISSUE THREAD

**Issue by RDJ202V** [microsoft/AL#7727]
same issue facing since yesterday and after upgrading app id and version it shows 
![image](https://github.com/microsoft/AL/assets/107498845/f8b8fa3d-ca23-4d3f-b0dc-002a2e002c52)

_Originally posted by @Prachii202 in https://github.com/microsoft/AL/issues/7721#issuecomment-2071808761_

**Comment by thloke** [comment]
Duplicate of #7721
