### ISSUE TITLE
GetUrl returns not working link in version 24.0

### ISSUE THREAD

**Issue by nvtopalov** [microsoft/AL#7738]
**1. Describe the bug**
The system function GetUrl start returning different not working links in Version: W1 24.0 (Platform 24.0.18959.0 + Application 24.0.16410.17628)
Same code below is tested on version 23.5 and it works fine, while on version 24.0 it is not working correctly.

**2. To Reproduce**
1) Create a new project. 
2) Use this small test page
`
```
page 50200 "Test GetUrl"
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    layout
    {
        area(Content)
        {
            group(General)
            {
                fielD(UrlText; UrlText)
                {
                    ApplicationArea = All;
                    Caption = 'Url Text';
                    ToolTip = 'Url Text';
                    MultiLine = true;
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(GenerateUrl)
            {
                ApplicationArea = All;
                Caption = 'Generate Url';
                ToolTip = 'Generate Url';

                trigger OnAction()
                begin
                    Customer.FindFirst();

                    UrlText := GetUrl(ClientType::Web, CompanyName, ObjectType::Page, Page::"Customer Card", Customer)
                end;
            }
        }
    }

    var
        Customer: Record Customer;
        UrlText: Text;
}
```
`

**3. Expected behavior**
A link should be generated that is able to open the right destination.

Correct link generated deploying the code on version 23.5
https://businesscentral.dynamics.com/[TenantIdMasked]/[EvnNameMasked]/?company=[CompanyNameMasked]&page=21&bookmark=27%3bEgAAAAJ7%2f0QAMAAwADMAMAAwADAAMA%3d%3d

**4. Actual behavior**
The link first try open Business Central, but immediately after that redirect to https://signup.microsoft.com/get-started/signup page asking to start a Business Central trial. 
Tested with both partner account and account in the destination tenant.

Same code deploying the code on version 24.0 returns:
https://businesscentral.dynamics.com:443/?company=[CompanyNameMasked]&page=21&bookmark=27%3bEgAAAAJ7CDAAMQA0ADQANQA1ADQANA%3d%3d&tenant=[TenantNameMasked]

**5. Versions:**

- AL Language: v13.0.971907
- Visual Studio Code: 1.88.1
- Business Central: Version: W1 24.0 (Platform 24.0.18959.0 + Application 24.0.16410.17628)
- List of Visual Studio Code extensions that you have installed:

**Comment by BazookaMusic** [comment]
This is an issue with the runtime, so it is not in the scope of this repository. One reason I'm saying this is that the link does not look malformed, so it is the service that is not responding to it properly.

To get this to the correct team, I'd suggest one of the options below:
Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

**Comment by nvtopalov** [comment]
Thanks for the answer. 
I do understand there should be some rules and guide to use the right support channel so I did think twice before whether I should post it here or Yammer or Partner Portal. However you have to think to be able redirect somehow internally if for some reason the channel is mistaken. 
If I have to open a ticket in a few places, contact someone to help me understand where I should register a support ticket...

**Comment by BazookaMusic** [comment]
Any of the options suggested above are valid for the issue you are reporting. They also ensure you will have a go to person to ask for the progress on the resolution of the issue and that multiple people who might have the same issue will benefit from its resolution. The issue you are reporting may also affect live customers, thus it must be prioritized accordingly.

This is a repository for issues on the AL language compiler and developer tools, so we do not track these issues here.

**Comment by NKarolak** [comment]
It has already been posted on Yammer: https://www.yammer.com/dynamicsnavdev/threads/2776607520030720
