### ISSUE TITLE
Error downloading symbols

### ISSUE THREAD

**Issue by vickarma** [microsoft/AL#7740]
I've just installed a OnPremise Business Central installation on my computer (not using docker or other software), directly on my personal computer.

This is my first Hello World.

Trying to download symbols from Visual Studio I get the following error:
![image](https://github.com/microsoft/AL/assets/9880781/0b8cab9d-b92f-4979-8250-1346476a504d)

**Comment by BazookaMusic** [comment]
This repository is for bugs in the AL language compiler and developer tools, so it's not the correct forum for this question.

However, from the looks of it, you are trying to download version 24 symbols for a server instance called BC14, which probably has an application with version 14.

Add "application":"14.0.0.0" in your app.json file
