### ISSUE TITLE
AA0248 Add 'this' qualification. - Missing Runtime version check

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7742]
Please include the following with each issue:

**1. Describe the bug**
The CodeCop should check for  the runtime specified in the app.json and only trigger the warning AA0248 then.

**2. To Reproduce**

``` AL
    procedure SaveContactSync(CurrUserSecurityID: Guid; var Contact: Record Contact; NewID: Text)
    var
        RecordRef: RecordRef;
    begin
        RecordRef.GetTable(Contact);
        SaveSync(CurrUserSecurityID, RecordRef, Enum::"PTE Entity"::Contact, NewID); // Wrong warning for this
    end;

    procedure SaveSync(CurrUserSecurityID: Guid; var RecordRef: RecordRef; MgEntity: Enum "PTE Entity"; NewID: Text)
    var

    begin
        // Magic
    end;
```
.

**3. Expected behavior**
Similiar to other properties the CodeCop should respect the runtime version.

**4. Actual behavior**
The runtime is ignored.

**5. Versions:**

- AL Language: v14.0.1002061 (pre-release)

Internal work item: [AB#534070](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534070)

**Comment by thloke** [comment]
This has been fixed.
