### ISSUE TITLE
Unable to access standard report date item from report extension data item

### ISSUE THREAD

**Issue by djole369** [microsoft/AL#7749]
Please include the following with each issue:

**1. Describe the bug**
Unable to access standard report ("Add Contacts") data item "Contact" from report extension data item (Service Item) because text field in Service Item table is called "Contact" as well and only option i have is that field. 

**2. To Reproduce**
1. Create report extension for standard report "Add Contacts"
2. Add data item to report extension with table "Service Item"
3. Try to access data item "Contact" in "Service Item" data item

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Standard data item "Contact" can be accessed from other data items on report extension 

**4. Actual behavior**
![dataitem](https://github.com/microsoft/AL/assets/72451207/793bcef9-92fd-43f4-8429-78730448c273)
![error](https://github.com/microsoft/AL/assets/72451207/da9b25fe-c74e-407c-bb51-d13913359d84)
![fieldcontact](https://github.com/microsoft/AL/assets/72451207/9b8e2dae-1144-4ac8-9008-8f7a97cf997a)

**5. Versions:**

- AL Language: 2204
- Visual Studio Code: 1.86.0
- Business Central: 22.04
- List of Visual Studio Code extensions that you have installed: AL CodeActions, AL Language extension for Microsoft Dynamics 365 Business Central, AL Variable Helper

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
Just add ``CurrReport.`` in front of ``Contact``.

**Comment by BazookaMusic** [comment]
@dannoe Thanks a lot for contributing here and helping people! I'll close this bug.
