### ISSUE TITLE
Event Subscription MissingTypeSymbol issue

### ISSUE THREAD

**Issue by shyamraoo** [microsoft/AL#7753]
Hi Team,

I am trying to make some changes in Shopify Connector extension. I have downloaded the symbols, However, when I use any of the event subscription I am facing below error.

I tried reinstalling extension and redownloaded symbols but still facing same issue. Can anyone help me with this?

![image](https://github.com/microsoft/AL/assets/14193656/d2e5797c-9d7b-474e-9ce4-2b63c9385ac7)

**Comment by SBalslev** [comment]
@shyamaroo please share a simple project including the app.json for us to reproduce.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
