### ISSUE TITLE
Function GetRecord working incorrectly when in factbox we have more then 15 records  

### ISSUE THREAD

**Issue by ABU-LT** [microsoft/AL#7755]
**1. Describe the bug**
When we using function GetRecord to get selected record from then factbox to the main page, then we get wrong record. It happens when in factbox is more then 15 records. If we have till 15 records everything is working correctly
 
![MS-BUG_BC24](https://github.com/microsoft/AL/assets/61690726/634f408c-10c2-46fe-aaa1-7535a1520419)

**2. To Reproduce**
Create Main page with factbox. 
![image](https://github.com/microsoft/AL/assets/61690726/b581c034-e6f0-4643-99b9-b201dd8a2cde)

In main page create action :
![image](https://github.com/microsoft/AL/assets/61690726/e3899fa8-8eae-4ef3-b4ef-8f878b0e0e73)

Then add more then 15 records in factbox. 
Select first record in factbox and press action button "Test"
You will get not first but last record from the factbox.
![image](https://github.com/microsoft/AL/assets/61690726/c1825fd4-7ffb-4b42-92fd-e2ffa2dfb335)

**3. Expected behavior**
Function GetRecord should return a record of what exactly I chosed

**4. Actual behavior**
GetRecord return last records from then factbox if there is more then 15 records 

**5. Versions:**

-AL Language: v13.0.1007491
-VSC Version: 1.89.1 (user setup)
-Business Central: v. 24.1.18927.19633
-Microsoft Edge :Version 125.0.2535.67

**Comment by SBalslev** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by MPayne1** [comment]
@ABU-LT I'm having a similar problem, did you manage to resolve this?
