### ISSUE TITLE
Always an .alpackages/.snapshots folder

### ISSUE THREAD

**Issue by SebastiaanLubbers** [microsoft/AL#7762]
Please include the following with each issue:

**1. Describe the bug**
Even when not working with AL. Having the extension installed creates .alpackages and .snapshots folder.

**2. To Reproduce**

1. Open empty folder in vscode
2. Run dotnet new console
3. An empty .alpackages and .snapshots folder also appear

**3. Expected behavior**
No AL related stuff as long there is no app.json in the folder/solution.

**4. Actual behavior**
![image](https://github.com/microsoft/AL/assets/520909/7a7a3745-0f4c-4536-b2c6-c82de275cd21)

**5. Versions:**

- AL Language: latest per 6-6-24
- Visual Studio Code: latest per 6-6-24
- Business Central: doesn't matter
- List of Visual Studio Code extensions that you have installed: AL

**Comment by samyhaff** [comment]
Hi, I couldn't reproduce this, can you please check that you're not missing any step in the "To Reproduce:" section, and that you don't have anything relevant in you setup that is not mentioned in the "Versions" section, such as other installed VSCode extensions or AL global settings? Thanks!

**Comment by SebastiaanLubbers** [comment]
I've split up my workloads and started using VSCode profiles where depending doing AL/C#/Java/Node I use a different profile with each their own settings/extensions. This way Java does not activate when doing AL, and AL does not activate when doing C#
