### ISSUE TITLE
Command 'AL: Go!' resulted in an error (command 'al.go' not found)

### ISSUE THREAD

**Issue by AbdulWahabWarind** [microsoft/AL#7763]
I am trying to prepare my sandbox for the purpose of following the steps below.

1. Sign up for a [Dynamics 365 Business Central sandbox](https://signup.microsoft.com/signup?sku=6a4a1628-9b9a-424d-bed5-4118f0ede3fd&ru=https%3A%2F%2Fbusinesscentral.dynamics.com%2FSandbox%2F%3FredirectedFromSignup%3D1).
2. Download [Visual Studio Code](https://code.visualstudio.com/Download).
3. Download the [AL Language extension for Microsoft Dynamics 365 Business Central](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al).
4. Select Ctrl+Shift+P to open the User Settings window; here you can modify the [telemetry settings](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started#telemetry-settings).
**5. Select Alt+A, and right after, Alt+L to trigger the AL Go! command, choose a path to a new empty folder and which version to run. Then choose Microsoft cloud sandbox as the server.**

While performing step number 5, we encountered the error message ‘Command ‘AL: Go!’ resulted in an error (command ‘al.go’ not found).’

Here is the [link](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started) of the documentation. Please suggest how to resolve the error.

**Comment by thloke** [comment]
Please open an issue using the correct template which specifies which versions of VSCode and the AL Extension you are using.

As a sanity check, have you tried after restarting VSCode after installing the extension? This looks like an issue where the AL Extension had issues starting up.

I'm closing this issue as it's not using the right template and is missing information.

**Comment by AbdulWahabWarind** [comment]
Hi,

I restarted my computer, but still, it is not working.

Thanks
Regards,


Abdul Wahab, MCP, Consultant

Direct: +92 (332) 3281237

Email: ***@***.******@***.***>

Skype: abdul.wahabubit

Website: http://www.abmlogics.com/

LinkedIn: https://www.linkedin.com/in/abdul-wahab-a5b8b011a/
Twitter: Abdul Wahab ***@***.***) / Twitter<https://twitter.com/Abdulwahabubit>
GitHub: https://github.com/AbdulWahabWarind
Youtube: https://www.youtube.com/channel/UCBjgLqLK_2kU-3bwo4McrTw
________________________________
