### ISSUE TITLE
RUNTIME of Visual Code is not compatible with Server RunTime

### ISSUE THREAD

**Issue by Maryamkaterji** [microsoft/AL#7766]
- AL Extension Version: 13.0921843 pre-released version

- Server Version: 13.1
![Screenshot 2024-06-08 at 8 21 53 AM](https://github.com/microsoft/AL/assets/117437195/829ba286-3f02-4903-b7a5-92a90a18c1f2)

**Comment by milanfto** [comment]
Hi!
Had the same problem last week.
Your VS Code version might not be compatible with the latest AL version, so it will not show up as an option.
Try updating your VS Code first, then install a new version from the AL extension via a ".VSIX" file.

You can download one from here:
https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al&ssr=false#version-history

**Comment by thloke** [comment]
As mentioned, please try to update your version of VSCode, if this doesn't work please mention which version of VSCode you are using.

**Comment by Maryamkaterji** [comment]
I figured out that the max version of visual code is 13.9 on Mac however on windows there is 14.0. 
I didn't find if there will be an update for AL extension on MacBook

**Comment by Maryamkaterji** [comment]
> Hi! Had the same problem last week. Your VS Code version might not be compatible with the latest AL version, so it will not show up as an option. Try updating your VS Code first, then install a new version from the AL extension via a ".VSIX" file.
> 
> You can download one from here: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al&ssr=false#version-history

I've tried it shows a binary file it didn't work on mac
