### ISSUE TITLE
Suggestion: No Templates on Variable Declaration

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#777]
On declaration of the variable type in the list of possible variable types there are also the code templates. I would if it's possible to only show the valid options (variable types)?

**Comment by StanislawStempin** [comment]
We will consider it for long-term backlog.

**Comment by DanielGoehler** [comment]
Hi @StanislawStempin,
any update on this? 

I would remove the templates in these cases. It would make working a little bit smoother.

![2019-12-14 16_30_10-Window](https://user-images.githubusercontent.com/9556549/70850856-25b50b80-1e8f-11ea-9168-aefb356ca387.png)

![2019-12-14 16_30_37-Window](https://user-images.githubusercontent.com/9556549/70850857-277ecf00-1e8f-11ea-86cf-876527912a0a.png)

**Comment by nndobrev** [comment]
This should have been fixed, as one can get more accurate suggestions now:
![image](https://github.com/microsoft/AL/assets/85873063/f7c3b7af-bf05-41d9-a34a-2fbc7128ccbd)
