### ISSUE TITLE
Error on "Verify Registration" at "Email Microsoft Entra application registration"

### ISSUE THREAD

**Issue by SidlyarSergii** [microsoft/AL#7774]
**1. Describe the bug**
We installed BC 24.2 W1 On-Prem. 
We are trying to configure the mailing functionality in Business Central but receiving the following error while clicking "Verify Registration" action on the "Email Microsoft Entra application registration" page. 
![image](https://github.com/microsoft/AL/assets/113432934/6a426f36-43a5-4e03-92dc-cc3179760578)

**2. To Reproduce**

1. Install BC 24.2 W1 On-Prem
2. Register Azure app in the Azure portal and  provide App permissions  according to this article
https://learn.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email#set-up-email-for-business-central-on-premises
![image](https://github.com/microsoft/AL/assets/113432934/f998d350-b9ec-46e4-a6d7-0ad8fbb35b5b)

3. Create a Client Secret for the registered Azure app
![image](https://github.com/microsoft/AL/assets/113432934/8c05476b-49ef-4022-bafc-b600ac2c6832)

5. Open BC Web Client and search for "Email Microsoft Entra application registration" in Tell Me
![image](https://github.com/microsoft/AL/assets/113432934/377a9e75-9571-4699-aa93-8e5022ecda07)

6. Specify Client ID, Client Secret and Redirect URL from the registered Azure App in the opened page:
![image](https://github.com/microsoft/AL/assets/113432934/104cc650-a50f-4d3b-aa11-d0a35f17dec2)

7. Click "Verify Registration" action

**3. Expected behavior**
Authentication should be successfully verified
![image](https://github.com/microsoft/AL/assets/113432934/76bffd47-9a32-4c84-b467-8b51ae0442f2)

**4. Actual behavior**
An error "A DotNet variable has not been instantiated. Attempting to call Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.LastErrorMessage in CodeUnit OAuth2Impl: GetLastErrorMessage" is shown
![image](https://github.com/microsoft/AL/assets/113432934/52ee5084-51b4-40cf-bf56-68c1f20d3666)

Additional Info:
We tried to do the same steps for BC22.5 On Prem and everything works fine
We tried to do the same steps for BC24.1 On Prem and received the same error
We googled this issue and found that other users have similar problem: https://www.dynamicsuser.net/t/error-with-bc240-email-setup-microsoft-app-registration/85281

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by wansong-yu** [comment]
Having some issue in our Indian project. We were using v22 and everything worked fine. This summer we upgraded to BC24.2. Old secret can continue to used until expiry at Sep. Then, renewing the secret was always not success
