### ISSUE TITLE
Will be there a new version of AL extension in VSCode for 14.0 ?

### ISSUE THREAD

**Issue by Maryamkaterji** [microsoft/AL#7775]
🔻🔻🔻This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for AL compiler and developer tools 🔻🔻🔻

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)

**Comment by dannoe** [comment]
You just have to switch to the pre-release version inside of VSCode:
![grafik](https://github.com/microsoft/AL/assets/7450586/832aae9b-a485-444d-bb0e-4591e20ba20e)

**Comment by Maryamkaterji** [comment]
yes i switched it to pre-release the last verison is 13.0.9 however runt time of server became 13.1 which causing an error

**Comment by Maryamkaterji** [comment]
on MacBook

**Comment by dannoe** [comment]
Oh can't help you with mac. But FYI: On Windows the latest pre-release version is 14.0.1044805.

**Comment by thloke** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools. 

 

To get help for your question please use one of the following resources: 

[Business Central Community](https://community.dynamics.com/business/f/758) 

[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier) 

[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
