### ISSUE TITLE
Can not install a hello world OnPrem with personal licence

### ISSUE THREAD

**Issue by jmadrigalTCN** [microsoft/AL#7776]
Please include the following with each issue:

**1. Describe the bug**
In a OnPrem v. 230 and 240 version and with my licence in these BBDD, I can not install any app, not eve a helloWorld, with target=OnPrem in the app.json file

**2. To Reproduce**

Create a new HelloWorld app with AL Go comand.
Set then property Target = OnPrem in the app.json file: i.e:

{
  "id": "5db73a4e-87c0-4ca3-a223-ce332f64366f",
  "name": "test01",
  "publisher": "Default Publisher",
  "version": "1.0.0.0",
  "brief": "https://tecon.es",
  "description": "https://tecon.es",
  "privacyStatement": "https://tecon.es",
  "EULA": "https://tecon.es",
  "help": "https://tecon.es",
  "url": "https://tecon.es",
  "logo": "logo/informacion.png",
  "contextSensitiveHelpUrl": "https://tecon.es",
  "dependencies": [],
  "screenshots": [],
  "platform": "1.0.0.0",
  "application": "24.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": true,
    "includeSourceInSymbolFile": true
  },
  "runtime": "13.0",
  "features": [
    "NoImplicitWith","TranslationFile"
  ],
  "target": "OnPrem"
}

Then, with a final custer licence installed in the BBDD, try to install the app via Ctrl+F5 or with powershell, and then you will get the next error:

The request for path /BC240/dev/apps?tenant=default&SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Sorry, we can't proceed with the operation for app 'borrame33' by 'Default Publisher' for tenant 'default' because the app doesn’t meet our Universal Code requirement. You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an exception to the requirement. For more information, see https://aka.ms/bcUniversalCode.

Can not we now set the target as OnPrem for OnPremise environments?

**Comment by dannoe** [comment]
Check the provided link with your partner account: https://aka.ms/bcUniversalCode
Or read this blog post https://community.dynamics.com/blogs/post/?postid=5508a98b-1175-431d-98c1-c1f80ee1753e

You have to license apps that don't target the cloud.

**Comment by BazookaMusic** [comment]
This is by design as the error describes. As mentioned, the apps must be licensed if they are targeting on-prem..
