### ISSUE TITLE
[Pre-release] Feedback/question about the new "is" operator

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7780]
I discovered the new ``is`` operator in the prerelease version and have a question. Is it intended that the syntax is designed so it is only valid for interfaces. 

I think this might make it hard to add other is-checks in the future, e.g.:

```al
procedure Foo(MyVariant: Variant)
begin
    if MyVariant is Record "Item" then
        Message('MyVariant is a Item');
end;
```

Or maybe is-casts like in c#:
```al
procedure Foo(MyVariant: Variant)
var
  MyItem: Record "Item"
begin
    if MyVariant is MyItem then
        Message('Item: ' + MyItem."No.");
end;
```

**Comment by esbenk** [comment]
It is targeted interfaces for now, but we don't rule out expanding the functionality in the future. We would probably then use then existing ObjectType qualifier syntax e.g.

```al
procedure Foo(MyVariant: Variant)
begin
    if MyVariant is Database::"Item" then
        Message('MyVariant is a Item');
end;
```

And yes I know that our current Database:: is a weird naming, but it is what we have today. We have discussed adding Table:: at some point.
