### ISSUE TITLE
Get-NAVServerPermissionSet return value is always empty

### ISSUE THREAD

**Issue by PETMLA** [microsoft/AL#7796]
**1. Describe the bug**
Get-NAVServerPermissionSet return value is always empty and never returns a list of permission sets for the specified Business Central Server instance.

**2. To Reproduce**

Follow the example from [https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/get-navserverpermissionset?view=businesscentral-ps-24](url)

`Get-NAVServerPermissionSet -ServerInstance "ServerInstance"`

**3. Expected behavior**
It should return a list of permission sets for the specified Business Central Server instance.

**4. Actual behavior**
It returns nothing.

![image](https://github.com/user-attachments/assets/78fa04bd-315b-454b-b207-61804c652674)

**5. Versions:**

- AL Language: -
- Visual Studio Code: -
- Business Central: 24 (also tested with 23 and 22)
- List of Visual Studio Code extensions that you have installed: -

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
