### ISSUE TITLE
New-NAVServerPermissionSet always returns an error

### ISSUE THREAD

**Issue by PETMLA** [microsoft/AL#7797]
**1. Describe the bug**
New-NAVServerPermissionSet always returns an error and never creates a new permission set.

**2. To Reproduce**

Follow the example from [https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navserverpermissionset?view=businesscentral-ps-24](url)

`New-NAVServerPermissionSet -ServerInstance "ServerInstance" -PermissionSetId TEST -PermissionSetName 'This is a set for TEST.'`

**3. Expected behavior**
It should create a new permission set.

**4. Actual behavior**
It throws an error.

![image](https://github.com/user-attachments/assets/0958d2e6-85e0-47e3-9049-2ed22907ad3b)

**5. Versions:**

- AL Language: -
- Visual Studio Code: -
- Business Central: 24
- List of Visual Studio Code extensions that you have installed: -

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/157720687-c507e6aa-8588-4b9f-a7d1-6386db557300.png)
