### ISSUE TITLE
On v24 and getting lots of AL0432 warnings about home page size increase

### ISSUE THREAD

**Issue by nickgoddard777** [microsoft/AL#7799]
Please include the following with each issue:

**1. Describe the bug**
In VS Code, I have added CLEAN24 to my app.json, I am getting warnings still everywhere I have referenced "home page" from the company information table. if I look at the field in the dal file the correct one is greyed out so I don't understand why I'm still getting the warning, there are over 30 entries for this and it is making it hard to see other issues.

**2. To Reproduce**

1. Added home page field to a report
2. Enable Code Cops
3. Open Report
4. Warning appears

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```
column(CompanyInformationNameHomePage; CompanyInformation."Home Page") { }

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
If CLEAN24 is in the app.json file the warning should not be shown as we are now using the new field.

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring
Warning appears

**5. Versions:**

- AL Language: v13.1.1065068
- Visual Studio Code: 1.91.1
- Business Central: 24.0.16410.19115
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ X] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
Preprocessor symbols are only considered in your source code, not in dependencies. If you want to get rid of the warnings, you have to add pragmas 

You can read more about this:
On Yammer/Viva Engage: https://www.yammer.com/dynamicsnavdev/threads/2625737496993792
Blog post from @NKarolak: https://nataliekarolak.wordpress.com/2024/01/17/increasing-the-length-of-non-pk-fields/

**Comment by blrobl** [comment]
Closing as solution was provided, please re-open if there are any follow-up questions.
