### ISSUE TITLE
RTC Crash

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#78]
Created a field in "Jobs setup" and Job.
RTC crashing with below error in event viewer while selecting/entering values in Job Card. (working fine Job Setup page). 
Is it related to VS code extension or something else?
NOTE: if I unistall extension then Job card is working fine. I cannot modify any standard field also in Job card when extension is installed.
[crash event viewer.txt](https://github.com/Microsoft/AL/files/710538/crash.event.viewer.txt)

**Comment by StanislawStempin** [comment]
It looks like a duplicate of #75

**Comment by esbenk** [comment]
The crash is most likely caused by #75. Without the more details it is hard to say.

**Comment by StanislawStempin** [comment]
We have fixed this bug and uploaded a new azure gallery image to http://aka.ms/navdeveloperpreview. Please give it a try.

**Comment by pmohanakrishna** [comment]
Its working fine now. Thanks..
