### ISSUE TITLE
pageextension add new fields does not work

### ISSUE THREAD

**Issue by priteshsomani** [Microsoft/AL#780]
Hi..

I just tired with October build and found the issue when i add new field in pageextension does not work.

Below is the my code. 

pageextension 70092504 CustomerCardExtension extends "Customer Card"
{
    layout
    {
        addafter(Address)
        {
            field(Priority;Priority)
            {
            }
        }
       
    }
}

I tried all functions addafter,addbefore,addlast and addfirst but all not working. When i tried to moveafter,movebefore,movefirst and movelast with exiting fields it's working fine.

Please let me know if i am missing anything here.

**Comment by twityde** [comment]
Did you set the ApplicationArea for the fields?

**Comment by priteshsomani** [comment]
Hi Thomas,
I set addafter(Address). is it ApplicatoinArea ?

If not then can you please guide me.

Thanks

**Comment by reiniroosh** [comment]
@priteshsomani  maybe the same thing has happened to you as to me.

twityde is saying your extension code should look like:

```
pageextension 70092504 CustomerCardExtension extends "Customer Card"
{
layout
{
addafter(Address)
{
field(Priority;Priority)
{

          ApplicationArea=Basic' //for example
}
}

}
}
```


Absent the ApplicationArea property, every field declared in AL will not be visible in the UI.

I was porting over something as a test, so I didn't want to go update all the fields to try this out.
So, if you go to Application Areas, and uncheck _all_ the Application Areas. This page is set to be non-editable. I tried making it editable and that did work correctly.

**Comment by StanislawStempin** [comment]
Since September Update the dev environments mimic more closely the Dynamics 365 environment which means Application Area needs to be set for all controls.  
We are looking into extension-wide setting for Application Area so you won't have to apply it to each individual control in the future.
