### ISSUE TITLE
Control Addin `type="module"` script support

### ISSUE THREAD

**Issue by Hugos68** [microsoft/AL#7802]
I'm building a Control Addin and wanted to use a few libraries, most of the modern libraries are `esm` which means they use `import` and `export` syntax. Even though browsers support this widely (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), there is no way to specify this with control addins. They are always `type="text/javascript"` which means they will be treated as CommonJS modules. This really hurts the amount of libraries you can use and makes pretty much working with Control Addin scripts a big painpoint. I would love it if you could somehow specify within the control addin what type of script you're including. This would solve a lot of  the problems I'm having with control addins.

**Comment by kalberes** [comment]
Hi,
Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by Hugos68** [comment]
Thanks for the swift response, will do!
