### ISSUE TITLE
Budget (113) SaveValues page property

### ISSUE THREAD

**Issue by BergantINC** [microsoft/AL#7805]
The page Budget (113) had the property SaveValues set to **true** until BC19, then it disappeared. I tried to find a reason as to why that happened, but i couldn't find anything, there is no documentation on this change.
Unfortunatly this can't be fixed with a page extension and the work neccesary to fix the lack of this property is quite big. I would appreciate if this property could be added back in a future update or at least if there is some reason as to why it was removed.

Thank you very much

**Comment by dannoe** [comment]
You opened your request in the wrong repository. That's better off here: https://github.com/microsoft/ALAppExtensions/issues
This repository is only for AL compiler related issues/bugs.
