### ISSUE TITLE
Editable Property on page fields with underlying table relation breaks lookup

### ISSUE THREAD

**Issue by fmenke** [microsoft/AL#7807]
**1. Describe the bug**

Setting the Editable property on a page field to a global variable causes issues with the table relation lookup of the table field on list/worksheet pages. 
The tablerelation lookup works normally for the first line that is entered, but completely stops working for subsequent lines.

**2. To Reproduce**

  1. Go to any listpage that displays a tablefield with a tablerelation and an Editable property, that is set to a global variable.
  2. Enter a new record/line
  3. Navigate to the field with the table relation and start typing something. The expected behaviour of a lookup window opening and values being filtered should happen.
  4. Enter another record/line
  5. Navigate to the field with the table relation and start typing something. The expected behaviour of a lookup window opening and values being filtered does not happen at all.

AL

I've created a simple table and page which demonstrates the behaviour:

[TestLookup.Table.al.txt](https://github.com/user-attachments/files/16363141/TestLookup.Table.al.txt)
[TestLookup.Page.al.txt](https://github.com/user-attachments/files/16363142/TestLookup.Page.al.txt)

points to note: 

  1. it doesn't seem to matter, where the global var is set, i.e. through a pageaction or a trigger
  2. The error doesn't occur when the Editable property of the field is hardcoded to true

**3. Expected behavior**
In this example the Customer No. Field has the Editable property set to a variable and a tablerelation to customer, the Vendor No. Field only has the tablerelation and a default Editable Property

The lookup works as expected for the second and further records that are entered

First line, it works for all fields:
![image](https://github.com/user-attachments/assets/50781d94-01c4-481b-9ae0-88386142e034)

**4. Actual behavior**
The lookup only works for the first record that is entered

Second line, it works only for the vendor no:
![image](https://github.com/user-attachments/assets/dad3c611-d045-476c-a473-9a7046189fb2)
For Customer No. the filter text has no impact:
![image](https://github.com/user-attachments/assets/35fa4af1-582c-431f-8d94-60d6cad137d2)

**5. Versions:**

- AL Language:14.0.1070882
- Visual Studio Code:1.91.1
- Business Central: 24.3.21374.21517

**Comment by Yann-Moreau** [comment]
We are experiencing this as well.

**Comment by nickorlando-ait** [comment]
We are experiencing this as well

**Comment by Teming** [comment]
We are experiencing this as well, but sometimes it is working.
We understand that the inconsistent issues are the most difficult to fix.  Does anyone know how could we raise the attention level up to 'high priority' for MS tech support?  Thanks very much.

**Comment by NKarolak** [comment]
You are posting in a repository for issues with the AL language, not for the resulting application. You won't get any help here. Please raise a support request at Microsoft, or if you are a partner with access to the Yammer partner network, you can try posting it there.

**Comment by BazookaMusic** [comment]
As @NKarolak pointed out this issue is outside the scope of this repo.

Instead you can do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
