### ISSUE TITLE
`internal interface` ... is it supported? Yes, but actually no.

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [microsoft/AL#7808]
**1. Describe the bug**
I am trying to create an internal interface. The compiler complains though that `internal` can only be used with certain keywords like `table`, `page` ... and - to my surprise: `interface`. Is the compiler right and the message wrong, or the message right and the compiler wrong?

**2. To Reproduce**
Create the following interface:

``` AL
internal interface IMyInterface
{
  procedure MyMethod();
}
```

The compiler fails with the following message:
````
error AL0198: Expected one of the application object keywords (table, tableextension, page, pageextension, pagecustomization, profile, profileextension, codeunit, report, reportextension, xmlport, query, controladdin, dotnet, enum, enumextension, **interface**, permissionset, permissionsetextension, entitlement)
````

**3. Expected behavior**
I would find it extremely useful to be able to declare internal interfaces. For modularizing my application for example. As such I actually expected them to be supported, but looks like they are not. Or they are and the compiler is mistaken.

**4. Actual behavior**
Error `AL0198` is given.

**5. Versions:**

- AL Language: 14.0.1070882
- Visual Studio Code: 1.91.1
- Business Central: 24.0

**Comment by KonstantynRomanowski** [comment]
Hi Thomas,

Have you tried to do that this way?

``` AL
interface IMyInterface
{
Access = internal;

  procedure MyMethod();
}
```

**Comment by BazookaMusic** [comment]
Access in objects is managed through the access property.Closing this.
