### ISSUE TITLE
Field."App Package ID" only works in combination with Next()

### ISSUE THREAD

**Issue by J-KVS** [microsoft/AL#7809]
Please include the following with each issue:

**1. Describe the bug**
The field `"App Package ID"` is empty if you `Get()` the `Field` Record.

**2. To Reproduce**
Example to reproduce below:

``` AL
pageextension 50059 KVSItemCard extends "Item Card"
{
    actions
    {
        addlast(navigation)
        {
            action(KVSTestGetFieldWithNext)
            {
                Caption = 'Test Get Field  Next';
                ApplicationArea = All;
                Promoted = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                Image = TestReport;
                trigger OnAction()
                var
                    Field: Record Field;
                begin
                    Field.Get(Database::Item, Rec.FieldNo("No."));
                    //App Package ID: {00000000-0000-0000-0000-000000000000}| App Runtime Package ID: {00000000-0000-0000-0000-000000000000}
                    Message('App Package ID: %1| App Runtime Package ID: %2', Field."App Package ID", Field."App Runtime Package ID");

                    Field.Next(1);
                    Field.Next(-1);
                    //App Package ID: {101E1184-D029-4711-A72D-A7AED8C2F547}| App Runtime Package ID: {B8953742-D29A-42BB-AD73-3DB806B37BE7}
                    Message('App Package ID: %1| App Runtime Package ID: %2', Field."App Package ID", Field."App Runtime Package ID");
                end;
            }
        }
    }
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Both messages should return _App Package ID: {101E1184-D029-4711-A72D-A7AED8C2F547}| App Runtime Package ID: {B8953742-D29A-42BB-AD73-3DB806B37BE7}_

**4. Actual behavior**
The first message returns _App Package ID: {00000000-0000-0000-0000-000000000000}| App Runtime Package ID: {00000000-0000-0000-0000-000000000000}_

**5. Versions:**

- AL Language: v13.1.1065068
- Visual Studio Code: 1.91.1
- Business Central: BC24.3
- List of Visual Studio Code extensions that you have installed: AL Language extension for Microsoft Dynamics 365 Business Central

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by blrobl** [comment]
Hi, thanks for the detailed repro. This is indeed a bug on the 24.x platform. This has been fixed on BC25, hence it needs to be backported.

**Comment by thloke** [comment]
So we've looked into this more, and backporting the fix to 24.x is not straightforward as it was part of a much larger refactor that we don't want to backport. Seeing that BC25 is around the corner, I'm going to close this as "fixed" with the meaning of "fixed" being that it's fixed in BC25.
