### ISSUE TITLE
Add publisher OnAfterGetSalesHeaderPageID

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/AL#7814]
Dear team,

On Codeunit "Page Management", please help to add publisher OnAfterGetSalesHeaderPageID(RecRef, SalesHeader, Result) place after function GetSalesHeaderPageID

![image](https://github.com/user-attachments/assets/e952c2a4-540f-46ad-a324-ff296df92346)

Thank you in advance!

**Comment by pri-kise** [comment]
This is the wrong repository for event request.
Please use this repository: https://github.com/microsoft/ALAppExtensions
