### ISSUE TITLE
Duplicated query on codeunit "Copy Document Mgt."

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/AL#7815]
Hi team,

In Codeunit "Copy Document", function CopySalesShptLinesToDoc, I see 2 lines testfield as below. I think we should to remove the second line.

![2024-08-05_17h07_36](https://github.com/user-attachments/assets/b6a73d9b-5e55-4be5-8e23-1897086b8cec)

Regards.

**Comment by pri-kise** [comment]
This is the wrong repository for event request.
Please use this repository: https://github.com/microsoft/ALAppExtensions

**Comment by GiangLNT56** [comment]
I got it.
Thank you
