### ISSUE TITLE
Request to add publishers control testing "Prices Including VAT" field on codeunit "Copy Document Mgt."

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/AL#7816]
Dear team,

In codeunit "Copy Document", function CopyPurchRcptLinesToDoc, I'd like to have an subscriber to control if need to test OriginalPurchHeader."Price Including VAT" or not. Please help me to add new publisher OnCopyPurchRcptLinesToDocOnBeforeTestPriveInclVAT(ToPurchHeader, IncludeHeader, Recalculculatelines, FromPurchRcptHeader, Ishandle) just like below to meet the requirement.

![2024-08-06_13h30_26](https://github.com/user-attachments/assets/1cd2d131-a7b1-4645-b6b9-fd6dabbf825a)

I also need publishers with same purpose on functions: CopyPurchInvLinesToDoc, CopyPurchCrMemoLinesToDoc, CopyPurchReturnShptLinesToDoc. Please consider to add.

![2024-08-05_17h27_01](https://github.com/user-attachments/assets/ed9d0965-4dd3-44ae-8010-2a48b13726b8)

![2024-08-05_17h27_01](https://github.com/user-attachments/assets/74f34d52-a5e5-4886-93ec-3f0e0d350b29)

![2024-08-05_17h27_01](https://github.com/user-attachments/assets/208b7a5b-e399-4141-a1a8-46ecb0778698)

![2024-08-05_17h31_25](https://github.com/user-attachments/assets/b23d72b5-3d8e-4999-9ddc-a1d65f91a21e)

Thank you in advance!

**Comment by pri-kise** [comment]
This is the wrong repository for event request.
Please use this repository: https://github.com/microsoft/ALAppExtensions
