### ISSUE TITLE
CSVBuffer does not recognize german characters in ANSI converted CSV-File

### ISSUE THREAD

**Issue by ChrisChristophers** [microsoft/AL#7818]
**1. Describe the bug**
CSVBuffer does not recognize german umlauts in ANSI encoded dCSV. The Import only works correctly if the File is converted with UTF-8 encoding 

**2. To Reproduce**

``` AL
    local procedure ReadCSVData()
    var
        FileManagement: Codeunit "File Management";
        InStream: Instream;
        FromFile: Text[100];
    begin


        UploadIntoStream(ChooseFileMsg, '', '', FromFile, InStream);
        if FromFile <> '' then begin
            g_FileName := FileManagement.GetFileNameWithoutExtension(FromFile);
        end else
            Error(ChooseFileMsg);

        TempCSVBuffer.Reset();
        TempCSVBuffer.DeleteAll();
        TempCSVBuffer.LoadDataFromStream(InStream, ';');
        TempCSVBuffer.GetNumberOfLines();
    end;
```

**3. Expected behavior**
![image](https://github.com/user-attachments/assets/afe1d8e7-e2ae-4751-83d4-003aacb02178)

**4. Actual behavior**
![image](https://github.com/user-attachments/assets/e3d7f16f-fe9e-4f84-95dc-ce226abb16e7)
**5. Versions:**

- AL Language: 24
- Visual Studio Code: 1.92
- Business Central: 24 
- List of Visual Studio Code extensions that you have installed: none

Is there a workaround where we can stay cloud-ready but still specify the encoding when importing?

**Comment by rdebath** [comment]
I don't think this would be seen as an issue for this Repo; however, I know this one.


You can specify the Stream encoding when you "create" it, so something like this ...
You are allowed to use a variable of type `TextEncoding` , so you can have the user select an option to choose something other than UTF-8; though, really only the 'Windows' encoding is likely to be reliable and useful.  (CP1252 aka ISO8859-1/Miscosoft for West Europe) 

``` AL
                trigger OnAction()
                var
                    IStrm: InStream;
                    TempBlob: Codeunit "Temp Blob";
                    FileMgt: Codeunit "File Management";
                begin
                    if '' <> FileMgt.BLOBImportWithFilter(
                        TempBlob,
                        'Import CSV',
                        'Import.csv',
                        'CSV Files (*.csv)|*.csv|TXT Files (*.txt)|*.txt|All Files (*.*)|*.*',
                        '*.*') then begin
                        Rec.Reset;
                        Rec.DeleteAll;
                        TempBlob.CreateInStream(IStrm, TextEncoding::UTF8);
                        LoadCSVFromStream(Rec, IStrm);
                    end;
                end;
 ```

**Comment by ChrisChristophers** [comment]
> I don't think this would be seen as an issue for this Repo; however, I know this one.
> 
> You can specify the Stream encoding when you "create" it, so something like this ... You are allowed to use a variable of type `TextEncoding` , so you can have the user select an option to choose something other than UTF-8; though, really only the 'Windows' encoding is likely to be reliable and useful. (CP1252 aka ISO8859-1/Miscosoft for West Europe)
> 
> ```al
>                 trigger OnAction()
>                 var
>                     IStrm: InStream;
>                     TempBlob: Codeunit "Temp Blob";
>                     FileMgt: Codeunit "File Management";
>                 begin
>                     if '' <> FileMgt.BLOBImportWithFilter(
>                         TempBlob,
>                         'Import CSV',
>                         'Import.csv',
>                         'CSV Files (*.csv)|*.csv|TXT Files (*.txt)|*.txt|All Files (*.*)|*.*',
>                         '*.*') then begin
>                         Rec.Reset;
>                         Rec.DeleteAll;
>                         TempBlob.CreateInStream(IStrm, TextEncoding::UTF8);
>                         LoadCSVFromStream(Rec, IStrm);
>                     end;
>                 end;
> ```

Thanks for the suggestion, unfortunately none of the encodings seem to correctly import ANSI  csv

**Comment by rdebath** [comment]
Ok, first check your file with a Hexdump program. Below are the four encodings currently accepted by, European, BC.
```
$ echo Schloß Holte-Stukenbrock | iconv -f utf8 -t cp1252 | hd
000000: 53 63 68 6c 6f df 20 48  6f 6c 74 65 2d 53 74 75  Schlo² Holte-Stu
000010: 6b 65 6e 62 72 6f 63 6b  0a                       kenbrock␊
$ echo Schloß Holte-Stukenbrock | iconv -f utf8 -t cp850 | hd
000000: 53 63 68 6c 6f e1 20 48  6f 6c 74 65 2d 53 74 75  Schlo³ Holte-Stu
000010: 6b 65 6e 62 72 6f 63 6b  0a                       kenbrock␊
$ echo Schloß Holte-Stukenbrock | iconv -f utf8 -t utf8 | hd
000000: 53 63 68 6c 6f c3 9f 20  48 6f 6c 74 65 2d 53 74  Schlo²ⁿ Holte-St
000010: 75 6b 65 6e 62 72 6f 63  6b 0a                    ukenbrock␊
$ echo Schloß Holte-Stukenbrock | iconv -f utf8 -t utf16 | hd
000000: ff fe 53 00 63 00 68 00  6c 00 6f 00 df 00 20 00  ��S␀c␀h␀l␀o␀²␀ ␀
000010: 48 00 6f 00 6c 00 74 00  65 00 2d 00 53 00 74 00  H␀o␀l␀t␀e␀-␀S␀t␀
000020: 75 00 6b 00 65 00 6e 00  62 00 72 00 6f 00 63 00  u␀k␀e␀n␀b␀r␀o␀c␀
000030: 6b 00 0a 00                                       k␀␊␀
$
```
The CP850 changes pretty randomly based on i18n, the CP1252 is basically West Europe and other random areas. The default for Nav (and so BC) is the OEM charset and so CP850 for a European l10n.

However, there's a nasty side effect in that some browsers try to "do what you mean", so they may try to convert your file on upload if they _know_ that it's a text file. Usually, they make this guess based on the file extension.

Does the upload change if the extension is `.bin` or an unknown extension rather than CSV?

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
