### ISSUE TITLE
Make CopySheet evailable for cloud development

### ISSUE THREAD

**Issue by michuanni** [microsoft/AL#7819]
Hi,

is it possible to make the function CoipySheet in Excel Buffer evailable for cloud development?

`    [Scope('OnPrem')]
    procedure CopySheet(SheetName: Text; ClonedSheetName: Text; ReferenceSheetName: Text; PasteBefore: Boolean)
    begin
        XlWrkBkWriter.CopySheet(SheetName, ClonedSheetName, ReferenceSheetName, PasteBefore);
    end;`

We have some development in connection with Jet Reports where it is necessary to copy the sheet.

King regards

Michael

**Comment by BazookaMusic** [comment]
This is something to ask ij this repo:
https://github.com/microsoft/BCApps

The system app is open source and thus you can even work on it.

Closing as this repo is only for the AL language compiler and tooling
