### ISSUE TITLE
New default visibility of procedures.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#782]
Hi again there.

I was very excited to see that you added support for Client Add-ins in the October release!

However i was a bit dissapointed to see that none of my existing code was working anymore,
one part was due to that you no longer support declarations of object variables by id anymore...?
Are you actually going to completely kill objects ID's completely before the 2018 R2 release? Just
out of interest to see where we are going. 

However that's not my actual/most urgent question/issue. It seems to me that all procedures now are local by default even if they are note marked explicitely as being that. So "local procedure MyProcedure"
and "procedure MyProcedure" are equally local. I couldn't really figure out what to do as all my code would get errors on all invocations. I then ran some code conversion on the stardard objects and came across the Scope attribute. Are you supposed to use this for all your functions...?
I could only find
[Scope('Internal')] and [Scope('Personalization')]
In the converted baseobjects (Quick look, small subset). I expect [Scope('Internal')] is when the objects is extended and [Scope('Personalization')] would be for making a function public. 

Is this attribute documented somewhere and is it actually mandatory for making a procedure externally visible or are the something else wrong in my code (which was working in the september release)...

**Comment by NicolaiEsbensen** [comment]
I played around a bit more, and when i remove some of the existing .al files, the visibility issue seems
to dissapear. So it seems the previous issues in other files causes the parsing of succeeding (correct) files to fail, giving faulty errors. I haven't identified a pattern yet.

**Comment by StanislawStempin** [comment]
We will not remove object IDs in 2018 R2 release but at some point in the future they will go away.
If you use ExportToNewSyntax as part of Txt2Al conversion you will see that all variable declarations that used IDs will have been replaced with names so there should be no additional manual work for you.

Regarding the Scope attribute it is not related to your issue. See #67 , #387 

We would be really interested to hear more about your issue. The compiler should generally be robust against compilation errors in other files.

**Comment by NicolaiEsbensen** [comment]
Hi @StanislawStempin. I can offer you to send you our project for you to use for debugging, if that could be of interest? I haven't been able to point out which particular part of the project, that gives the error.

**Comment by NicolaiEsbensen** [comment]
@StanislawStempin I finally had some time to do some more investigation. I converted our pages with control add-ins, and the output created would give a lot of syntax errors (a bit more than necessary in my opinion :)). It seems to me that the variables declared after these errors would be treated as object declarations rather than variable declarations and therefor the resolving of symbols within them would fail as the declaration is would be empty (intellisense would only show run method). 

Commenting out all ControlAddIn fields solves this issue. So i guess it's easy to reproduce the error, just by using txt2al on a file with ControlAddIns where you would have declared a codeunit as a variable on the OnControlAddIn trigger, would cause issues for that specific codeunit... 

So i guess it's a two-part thing, the txt2al handling of ControlAddIns and fix the parser not to get confused by the variables declared in the OnControlAddIn trigger. Again i'm only guessing about the real issue with the parser, i'm just interpreting my observations. Also i don't know if you have any plans for handling pages with Control Add-ins in txt2al or the recommendations is just not to use the output of a page conversion with add-ins and just to recreate them in al from the beggining.. ?

**Comment by StanislawStempin** [comment]
Thank you for a detailed investigation. We will take a look into both issues.

**Comment by DominikDitoIvosevic** [comment]
Hi. We have fixed the parsing issue caused by txt2al and the function visibility should not pose a problem for you when doing the conversion.
