### ISSUE TITLE
OSX unable to download symbols from an `authentication: Windows` server

### ISSUE THREAD

**Issue by doobeh** [microsoft/AL#7824]
**1. Describe the bug**

When on OSX, I am unable to download Symbols from an OnPrem server that uses Windows authentication.  The plugin seems to be designed not to ask for credentials when `"authentication": "Windows"` is specified. In the case of an OSX developer that doesn't have windows credentials stored, it feels like it should prompt.

Setting to `UserPass` doesn't work either (which matches the documentation (authentication method should match)).

Interestingly, if I just copy and paste the url the Symbol request hits (`http://100.100.100.100:9049/LearnTest/dev/metadata?tenant=default`) in Chrome, I do get a basicAuth kind of user/password prompt, and entering any DOMAIN\user that's allowed gets me to some output.  So it does just seem like I need a way to specify it.

Is there a way to create a environmental variable/file or similar so that when `Windows` is set as a authentication mode, the developer can override the defaults.

**2. To Reproduce**

Set up a standard project with a `launch.json` similar to:

``` json
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "learning",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "http://100.100.100.100",
            "serverInstance": "LearnTest",
            "port": 9049,
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": "All",
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default",
            
        }
    ]
}
```

Open the command palette, and choose AL: Download Symbols.

Optionally, open the command palette and choose AL: Clear Credentials, and then AL: Download Symbols.

**3. Expected behavior**

Because the operating system can't provide windows credentials, it should prompt for a user/pass it can use instead.  If this behavior is the same on Windows machines, it would also be useful to provide alternative credentials when needed.  (E.g. if the server had a user called `ABC\Alice` enabled, and you were developing on a different user locally `ZZZ\Carol` it seems useful to be able to specify `ABC\Alice` as a username to pass to the BC server.

**4. Actual behavior**

No user/password prompt is shown, and the console displays:

```
[2024-08-16 18:39:32.12] Sending request to http://100.100.100.100:9049/LearnTest/dev/metadata?tenant=default
[2024-08-16 18:39:32.24] Authorization has failed or the credentials have expired. The credential cache has been cleaned. Any access to reach Business Central would require new authorization.
```

**5. Versions:**

- Visual Studio Code: 1.92.0
- Business Central: Version: W1 24.1 (Platform 24.0.19487.0 + Application 24.1.18927.19498)
- List of Visual Studio Code extensions that you have installed: AL Language Extensions (ms-dynamics-smb.al)

**Comment by rdebath** [comment]
Prior to Version-15 this would have been an authentication method of `UserName`, which would have worked with a service tier setting of Windows or UserName (but not UserPassword).
Does that work despite the settings.json warning?

NB: Workaround is two service tiers with different authentication settings.

**Comment by esbenk** [comment]
Windows authentication is not support from OSX.
