### ISSUE TITLE
Publish-NAVApp does not recognize a certificate

### ISSUE THREAD

**Issue by jmaciejewskitozepterit** [microsoft/AL#7825]
Please include the following with each issue:

**1. Describe the bug**
I try to upgrade BC20.0 to BC24.3.21517.W1 on customer server onprem version.
Customer license is without module 'Implemented code is not cloud-optimized'

Publish-NAVApp did not recognize a certifiacate for the 'Microsoft_Base Application.app' file. I was not able publish it.
 
**When I use -SkipVerivication I upgraded the system!**

But when I try to login to the system I got an error:

```
Sorry, we can???t sign you in. You're using a customized version of the following Microsoft applications, which doesn???t meet our Universal Code requirement:
_Exclude_APIV1_ by Microsoft
_Exclude_APIV2_ by Microsoft
_Exclude_Bank Deposits by Microsoft
_Exclude_ClientAddIns_ by Microsoft
_Exclude_Email Logging Using Graph API by Microsoft
_Exclude_PlanConfiguration_ by Microsoft
_Exclude_ReportLayouts by Microsoft
API Reports - Finance by Microsoft
Application by Microsoft
Audit File Export by Microsoft
Bank Account Reconciliation With AI by Microsoft
Base Application by Microsoft
Business Foundation by Microsoft
Company Hub by Microsoft
Contoso Coffee Demo Dataset by Microsoft
Data Archive by Microsoft
Data Search by Microsoft
E-Document Core by Microsoft
E-Documents Connector with External Endpoints by Microsoft
Email - Current User Connector by Microsoft
Email - Microsoft 365 Connector by Microsoft
Email - Outlook REST API by Microsoft
Email - SMTP API by Microsoft
Email - SMTP Connector by Microsoft
Enforced Digital Vouchers by Microsoft
Error Messages with Recommendations by Microsoft
Essential Business Headlines by Microsoft
EU 3-Party Trade Purchase by Microsoft
Intrastat Core by Microsoft
Late Payment Prediction by Microsoft
OnPrem Permissions by Microsoft
Payment Links to PayPal by Microsoft
Payment Practices by Microsoft
Permissions Mock by Microsoft
Recommended Apps by Microsoft
Review General Ledger Entries by Microsoft
SAF-T by Microsoft
Sales and Inventory Forecast by Microsoft
Send To Email Printer by Microsoft
Service Declaration by Microsoft
Shopify Connector by Microsoft
Simplified Bank Statement Import by Microsoft
Statistical Accounts by Microsoft
Sustainability by Microsoft
Sustainability Contoso Coffee Demo Dataset by Microsoft
System Application by Microsoft
Troubleshoot FA Ledger Entries by Microsoft
Universal Print Integration by Microsoft
VAT Group Management by Microsoft
You must either upgrade the apps to meet the requirement or license the non-Universal Code module that grants an exception to the requirement.
For more information, see https://aka.ms/bcUniversalCode.

```
**2. To Reproduce**
1. Use Publish-NAVApp to publish Microsoft_Base Application.app without -SkipVerivication option.

**3. Expected behavior**
Use Publish-NAVApp to publish Microsoft_Base Application.app with certificate.

**4. Actual behavior**
Publish-NAVApp did not recognize certificate on 'Microsoft_Base Application.app' file

**5. Versions:**
- AL Language: N/A
- Visual Studio Code: N/A
- Business Central: BC24.3.21517.W1 onprem on customer server
- List of Visual Studio Code extensions that you have installed: N/A
- PSVersion                      5.1.17763.1971                                                                                                        
- PSEdition                      Desktop                                                                                                               
- PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
- BuildVersion                   10.0.17763.1971                                                                                                       
- CLRVersion                     4.0.30319.42000                                                                                                       
- WSManStackVersion              3.0                                                                                                                   
- PSRemotingProtocolVersion      2.3                                                                                                                   
- SerializationVersion           1.1.0.1  

Get-AuthenticodeSignature returns
D:\Nav\Install\BC24.3.21517.W1\applications\BaseApp\Source\Microsoft_Base Application.app
Signature Type: None
Status: UnknownError
Status Message: The form specified for the subject is not one supported or known by the specified trust provider

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

Internal work item: [AB#545237](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545237)

**Comment by SBalslev** [comment]
We're currently investigating this issue.
@jmaciejewskitozepterit can you share the properties of this file: D:\Nav\Install\BC24.3.21517.W1\applications\BaseApp\Source\Microsoft_Base Application.app? Specifically the Digital Signatures tab.

**Comment by SBalslev** [comment]
@jmaciejewskitozepterit can you please make sure navsip.dll is registered on the machine where you do not see the signature?
regsvr32 <path to>\navsip.dll 
Remember to reboot after registering.

**Comment by jmaciejewskitozepterit** [comment]
an error occurred:

![obraz](https://github.com/user-attachments/assets/f860e0a2-465e-47a7-bb8d-6fad16fbdd1c)

**Comment by jmaciejewskitozepterit** [comment]
I installed the newest version MS C++ 2015-2022 14.40.3810, 
Publish-NAVApp works fine.

**Comment by jmaciejewskitozepterit** [comment]
12
