### ISSUE TITLE
The debugger doesn't stop when error occurs or on breakpoints during debugging in Saas.

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/AL#7826]
**1. Describe the bug**
I am trying to debug the custom API page (published like a web service in BC and based on the standard table Gen. Journal Line) in BC24 Saas.
The debugger does not stop when an error occurs or on breakpoints. I tried to do it with "Debug Without Publishing" or the F5 option (with attach request). I tried to debug the API page on different tenants, but it didn`t work. (I thought that it is not popular issue, but my colleagues faced with this issue as well.)

**2. To Reproduce**
Please create a new extension and custom API page and set breakpoints somewhere.
Please publish the extension and create a new web service for this API page.
Please use the parameters request "Attach" and breakOnNext "WebServiceClient" in the launch.json file.
Please run the debugger and check if it stops on breakpoints.

**3. Expected behavior**
The debugger should stop and work as it does during debugging standard or custom objects (not API pages).

**4. Actual behavior**
The debugger doesn`t stop and work as it does during debugging standard or custom objects (not API pages).

**5. Versions:**

- AL Language: v14.0.1108692
- Visual Studio Code: 1.92.1
- Business Central:  US Business Central 24.3 (Platform 24.0.22865.0 + Application 24.3.21374.21517)
- List of Visual Studio Code extensions that I have installed: AL Language Tools, AL Object Designer, AL Variable Helper, Create GUID, AZ AL Dev Tools/AL Code Outline, GitLens - Git supercharged, TODO Tree, waldo`s CRS AL Language Extension.

![image](https://github.com/user-attachments/assets/7c7facca-555e-49b8-8739-e0aa9c27fe66)

**Comment by DevHarmonize** [comment]
Your webservice user is the same as the user you are debugging with?

**Comment by OSH-ZT** [comment]
@DevHarmonize No, they are different, I run a debugger with the user for the sandbox, but the web service user in my case is, clientID from the Microsoft Entra Application. As I know we are not able anymore to send requests with authorization (BC user password).

**Comment by DevHarmonize** [comment]
Can you try with setting the userId property in the launch file to that of the entra application?
![image](https://github.com/user-attachments/assets/6997ecc2-558b-4be5-9119-b51339a890fa)

**Comment by OSH-ZT** [comment]
@DevHarmonize I tried with breakpoints and when an error occurred, but it didn`t help. It still doesn`t stop.

**Comment by OSH-ZT** [comment]
@DevHarmonize In this case it works only for the debugger breakpoints. When an error occurs, it doesn`t open any files from the base app, I mean the object where the error comes from.

**Comment by OSH-ZT** [comment]
@DevHarmonize I forgot to add that when an error occurs, it doesn`t open any files from the base app, but it stops. If I press "continue" it automatically crashes.

**Comment by DevHarmonize** [comment]
I just tried this in our setup, seems to work for me..
Make sure you have the correct symbols (down)loaded?
![image](https://github.com/user-attachments/assets/43b732d1-708b-4630-bf4e-3ac3c1676227)

**Comment by OSH-ZT** [comment]
@DevHarmonize  Yes, I have the correct symbols and it looks like that. Error that should occur, in the background in Postman.
![image](https://github.com/user-attachments/assets/dc52c173-06f7-40f3-b397-daeaa4ba0595)
![image](https://github.com/user-attachments/assets/26104149-2604-4e49-b474-a9f4c7cf6182)

**Comment by thloke** [comment]
I'm closing this as out of scope as this looks like an issue with the specific setup rather than a general issue with debugging, so it's hard for us to handle this within the capacity we have for github issues. If it's really blocking or urgent, you should raise a support case instead.
