### ISSUE TITLE
Latest AL Language Extension generates invalid SymbolReference.json in app package (v14.0.1108692 (pre-release))

### ISSUE THREAD

**Issue by vejbalzer** [microsoft/AL#7828]
Please include the following with each issue:

**1. Describe the bug**
When creating an app package e.g. with the "AL: Package" command, the generated app file contains a SymbolReference.json file with invalid JSON. It seems like the content is doubled, compared to how it should be. For example it looks like this:

``` JSON
{"RuntimeVersion":"9.0","Codeunits":[],"PageExtensions":[{"TargetObject":"Customer List","Variables":[{"TypeDefinition":{"Name":"Integer"},"Name":"myInt"}],"ActionChanges":[{"Anchor":"processing","ChangeKind":1,"Actions":[{"Kind":2,"Properties":[{"Name":"ApplicationArea","Value":"#All"}],"Id":885376841,"Name":"Test"}]}],"ReferenceSourceFileName":"HelloWorld.al","Id":50100,"Name":"CustomerListExt"}],"Reports":[],"XmlPorts":[],"Queries":[],"ControlAddIns":[],"EnumTypes":[],"DotNetPackages":[],"Interfaces":[],"PermissionSets":[],"PermissionSetExtensions":[],"ReportExtensions":[],"InternalsVisibleToModules":[],"AppId":"93ba70c0-3bda-421d-b731-675c3a52b841","Name":"ALProject1","Publisher":"Default publisher","Version":"1.0.0.0"}{"RuntimeVersion":"9.0","Codeunits":[],"PageExtensions":[{"TargetObject":"Customer List","Variables":[{"TypeDefinition":{"Name":"Integer"},"Name":"myInt"}],"ActionChanges":[{"Anchor":"processing","ChangeKind":1,"Actions":[{"Kind":2,"Properties":[{"Name":"ApplicationArea","Value":"#All"}],"Id":885376841,"Name":"Test"}]}],"ReferenceSourceFileName":"HelloWorld.al","Id":50100,"Name":"CustomerListExt"}],"Reports":[],"XmlPorts":[],"Queries":[],"ControlAddIns":[],"EnumTypes":[],"DotNetPackages":[],"Interfaces":[],"PermissionSets":[],"PermissionSetExtensions":[],"ReportExtensions":[],"InternalsVisibleToModules":[],"AppId":"93ba70c0-3bda-421d-b731-675c3a52b841","Name":"ALProject1","Publisher":"Default publisher","Version":"1.0.0.0"}
```

**2. To Reproduce**

1. Create a new extension with "AL: Go!"
2. Download symbols with "AL: Download symbols"
3. Create app file with "AL: Package"

**3. Expected behavior**
SymbolReference.json contains valid JSON

**4. Actual behavior**
SymbolReference.json contains doubled content which leads to invalid JSON

**5. Versions:**

- AL Language: 14.0.1108692 (pre-release)
- Visual Studio Code: 1.92.2
- Business Central: 21.2

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

Internal work item: [AB#545880](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545880)

**Comment by christian-clausen** [comment]
We have seen this issue, also, with a quite a few .app files in 25.0.23170.0. It very much looks like SymbolReference.json was written with File.OpenWrite (which by default does not truncate if the file already exists) at a time when there is a bigger SymbolReference.json from a previous build (unclean workspace).

**Comment by pri-kise** [comment]
I have the same issue when I was working for the BaseApp with version 25.0.23212.0
The symbol reference of the System Application is wrong:
[SymbolReference.json](https://github.com/user-attachments/files/16758133/SymbolReference.json)

**Comment by rvanbekkum** [comment]
I suspect we also are experiencing issues from this. We get weird error messages like `error AL0281: Object member '<EventPublisherName>' is not an event.` when having an event subscriber to an event publisher for which nothing has changed. The target procedure is actually an event publisher.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26.0.23829.0 and VS Code Extension Version 15.0.1128421. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
