### ISSUE TITLE
Customized List Pages Unable to Save Filters and Views

### ISSUE THREAD

**Issue by YTLIU0323** [microsoft/AL#7829]
Issue 1: All Customized list pages cannot save filters and views.
Issue 2: A list of views appeared on the Sales Order List and could not be removed.

The MS Support team and I have tried to publish all the extensions in a new clean sandbox, but it is still not working. No useful information can also be taken from telemetry logs. We have tried the code in another tenant, and there is no issue with the code we can perform save filter and views but not for the current tenant we using. These issues were encountered 3 months ago and we did all we could but were still unable to solve the issue. 

Checked on Roles and Role Center, and all the setups, seems nothing is affected.

Versions : 
"Platform": "1.0.0.0",
"application": "23.0.0.0",
"runtime": "12.2",

![image](https://github.com/user-attachments/assets/4397f17a-c4be-4a2a-a978-4680c8074b16)

**Comment by nndobrev** [comment]
Hi! This issue concerns a production system. This repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central and we cannot guarantee a timely resolution of your issue.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
