### ISSUE TITLE
Custom StartupObjectId

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#783]
Hi,

Currently in launch.json we have the startupObjectId as **22** .

Can you please suggest us how to use our custom RoleCenter Page in startupObjectId.

Thanks & Regards
Varun Reddy

**Comment by StanislawStempin** [comment]
I'm not sure I understand your question - you can specify any page id in the startupObjectId.

**Comment by bachii1010** [comment]
Hi,

Since the page id for the default rolecenter is 9022 we put startupObjectid as 22,
similarly if we have a custom rolecenter with id say suppose 70097620 then what will be the startupObjectID ?

**Comment by StanislawStempin** [comment]
Then you put 70097620 but you might need to configure the system so that the role center is actually viewable by your user.

22 is not because default role center is 9022 but because it opens Customer List page (with page id = 22)

**Comment by bachii1010** [comment]
you mean by configuring means making the custom rolecenter say suppose with id 70097620 as the default rolcenter for that user in the profile in rolcenter settings.

let me know if this is wrong?

**Comment by StanislawStempin** [comment]
That's correct.
