### ISSUE TITLE
al.referencesCodeLens.enabled

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#784]
Maybe it's a good idea to have a setting to be able to discable the references.  

Kind of like we have with the TypeScript settings in VSCode: typescript.referencesCodeLens.enabled

**Comment by StanislawStempin** [comment]
You can achieve it using so-called language specific settings in VSCode:
```
    "[al]": {
        "editor.codeLens": false
    }
```
Would this be sufficient?

**Comment by waldo1001** [comment]
It would for me :-).

I wasn't aware of this.  No need to have a flood of settings, while this is already possible this way .. just a "need-to-know".

Thanks for the tip!
