### ISSUE TITLE
error AL0570: Same label var name in same codeunit results in same translation ID 

### ISSUE THREAD

**Issue by cristof-thomas** [microsoft/AL#7844]
Please include the following with each issue:

**1. Describe the bug**
error AL0570: Same label var name in same codeunit results in same translation ID 

**2. To Reproduce**
codeunit 1234 my_codeunit
{
procedure p1()
var lbl1: Label 'label1';
begin
end;

procedure p2()
var lbl1: Label 'label2';
begin
end; 
}

...\my_codeunit.al(y1,x1): error AL0570: The symbol 'lbl1' results in the same translation ID as one or more other symbols. Rename symbol to resolve the problem.
...\my_codeunit.al(y2,x2): error AL0570: The symbol 'lbl1' results in the same translation ID as one or more other symbols. Rename symbol to resolve the problem.

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
2 differents translation ID generated

**4. Actual behavior**
error with same translation ID

**5. Versions:**

- AL Language: v14.0.1114061 (pre-release)
- Visual Studio Code:  Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
- Business Central: Version : FR Business Central 24.3 (plateforme 24.0.23306.0 + application 24.3.21374.21517)
- List of Visual Studio Code extensions that you have installed:
andrzejzwierzchowski.al-code-outline
davidanson.vscode-markdownlint
docsmsft.docs-article-templates
docsmsft.docs-authoring-pack
docsmsft.docs-build
docsmsft.docs-images
docsmsft.docs-markdown
docsmsft.docs-preview
docsmsft.docs-scaffolding
docsmsft.docs-yaml
github.copilot
github.copilot-chat
github.remotehub
gruntfuggly.todo-tree
learningengineeringoperations.learn-training-ai-assistant
martonsagi.al-object-designer
ms-dotnettools.csdevkit
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-dynamics-smb.al
ms-vscode.azure-repos
ms-vscode.powershell
ms-vscode.remote-repositories
nabsolutions.nab-al-tools
redhat.vscode-yaml
waldo.crs-al-language-extension
yzhang.markdown-all-in-one
### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by thpeder** [comment]
Hi @cristof-thomas,

I just tried out the code that you have in the issue description, and it does not reproduce for me. This is the generated translation file.
```xml
<trans-unit id="Codeunit 2605812460 - Method 2186843627 - NamedType 1006928925" size-unit="char" translate="yes" xml:space="preserve">
  <source>label1</source>
  <note from="Developer" annotates="general" priority="2"></note>
  <note from="Xliff Generator" annotates="general" priority="3">Codeunit my_codeunit - Method p1 - NamedType lbl1</note>
</trans-unit>
<trans-unit id="Codeunit 2605812460 - Method 4099933478 - NamedType 1006928925" size-unit="char" translate="yes" xml:space="preserve">
  <source>label2</source>
  <note from="Developer" annotates="general" priority="2"></note>
  <note from="Xliff Generator" annotates="general" priority="3">Codeunit my_codeunit - Method p2 - NamedType lbl1</note>
</trans-unit>
```

That being said, the Ids of a trans-unit is a hash of the names involved, which means that there can occur collisions. We have therefor included multiple elements to help avoid that situation. For instance in the example above.
Codeunit **my_codeunit** - Method **p2** - NamedType **lbl1**

If you encounter such diagnostic the best recommendation I have for you is to rename the local variable inside the procedure
