### ISSUE TITLE
Exposing Binary Blob in SOAP using BigText encoding issue

### ISSUE THREAD

**Issue by Martin-Lavigne** [Microsoft/AL#785]
Hi, 
I'm trying to expose a Binary Product's Picture using a Soap CodeUnit and save the file in my DotNet Windows App . 

` 
TenantMedia.Content.CREATEINSTREAM(IStream  , TEXTENCODING::Windows  );
    CLEAR(Content);
    ContentLine:='';
    IStream.READTEXT(ContentLine );
   Content.ADDTEXT( ContentLine);
    WHILE NOT IStream.EOS DO BEGIN 
        IStream.READTEXT(ContentLine); 
        Content.ADDTEXT(  ContentLine);
        ContentLine:='';
    END;
    Picture.ADDTEXT(Content);
    PictureType := TenantMedia."Mime Type"
`

I tried using different TextEncoding( Windows, MSDos and Default) and then I also tried multiple Encoding.GetBytes in Dot Net. 

`            
For Each oEncoding As System.Text.EncodingInfo In System.Text.Encoding.GetEncodings 
                My.Computer.FileSystem.WriteAllBytes("c:\dev\" & oEncoding.CodePage & ".jpeg", oEncoding.GetEncoding.GetBytes(sPictureAsText), False)
            Next
`
But each file that I saved wasn't formatted correctly.
 

I would really appreciate any input I can't seems to find what I am missing.

**Comment by twityde** [comment]
Why did you not use base64? To handle a binary file with string operations can corrupt the data.

Use an record of Type TempBlob like:

TenantMedia.CalcFields(Content);
TempBlob.blob := TenantMedia.Content;
Content := TempBlob.ToBase64String();

**Comment by Martin-Lavigne** [comment]
It worked thank you so much.
