### ISSUE TITLE
Missing ALC linux binary in version 15.0.1143290

### ISSUE THREAD

**Issue by HenrikSydow** [microsoft/AL#7859]
Please include the following with each issue:

**1. Describe the bug**
ALC (The AL Compiler) binary is missing from the linux bin directory.
Cannot compile any extensions on linux.

**2. To Reproduce**
Download the al extension through this official link:
https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/15.0.1143290/1726837673745/Microsoft.VisualStudio.Services.VSIXPackage

Unpack the extension. For example using 7zip.
Go to extension/bin/linux and search for alc.

The AL compiler (alc) is missing from this directory.

**3. Expected behavior**
Binary file is present in the bin directory.

**4. Actual behavior**
Missing linux alc binary.

**5. Versions:**
- Operating System:
  * [ ] Windows
  * [X] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

Internal work item: [AB#550227](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550227)

**Comment by martonnagy** [comment]
Hi, the same true for MacOS as well:

![CleanShot 2024-10-07 at 08 13 23@2x](https://github.com/user-attachments/assets/3c41358a-3705-40f1-a88c-5b3e53572718)

No alcohol binary either. Shall I create a new issue?

**Comment by SBalslev** [comment]
Lastest preview has the files. The 14.x version will have the files in the next release.

**Comment by martonnagy** [comment]
Good stuff! Thanks for sorting this out

**Comment by thpeder** [comment]
I'll close the issue, as it seem to be fixed in the latest available version.
Feel free to open a new issue if there still is an issue.
