### ISSUE TITLE
Txt2AL - After convert to AL in Oct update field is giving a strange issue

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#786]
Hi,

After Converting the file from Txt to Al using Txt2AL the field control in page is creating a property as below:

![image](https://user-images.githubusercontent.com/26792519/31651411-39a9edfe-b339-11e7-8fd1-2f7da83f2c82.png)

and due to this getting an error as shown below:

![image](https://user-images.githubusercontent.com/26792519/31653311-cae70d32-b33f-11e7-9fb1-48f3fe93a4f9.png)

Please suggest us.

Thanks & Regards
Varun Reddy

**Comment by HunterFeltman-MSFT** [comment]
This property is not used in the new syntax and was recently added to the ignore list for the Txt2AL converter. The change 'should' be in the October preview unless I've messed up dates. 

In any case, you can remove the property from the converted AL code and recompile.

**Comment by bachii1010** [comment]
Hi,

I am using the below version which is october preview
![image](https://user-images.githubusercontent.com/26792519/31702642-fc554c06-b3f5-11e7-930d-38e81d3f7056.png)

Can you please recheck if it is ignored in october preview

**Comment by StanislawStempin** [comment]
This didn't make it into October preview, will be available in November.
