### ISSUE TITLE
Debugger attach WebServiceClient doesn't attach to next session

### ISSUE THREAD

**Issue by louagej** [microsoft/AL#7860]
**Issue Description: ***Debugger attach WebServiceClient doesn't attach to next session*** **

I have an online sandbox `DEV` where I want to debug an API call.
so I prepared my launch.json as like this:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach: Isomo DEV",
            "type": "al",
            "request": "attach",
            "environmentType": "Sandbox",
            "environmentName": "DEV",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            "breakOnNext": "WebServiceClient",
            "tenant": "<<my tenant ID>>"
        }
    ]
}
```

**How to To Reproduce**

1. Publish a custom API

2. Attach your degugger

When I hit F5 and start this attach configuration, the debug console confirms my debug sessions will stop on the next session of type WebServiceClient

```log
[2024-09-25 19:04:11.92] Starting a debug session using launch configuration 'Attach: Isomo DEV'. 
[2024-09-25 19:04:16.35] Authenticated as user 'myuseraccount@mydomain.com' in tenant '<<my tenant ID>>'. Please note that these credentials are cached. Clear the credentials cache to authenticate as another user.
[2024-09-25 19:04:16.35] Targeting Dynamics 365 Business Central environment tenant '<<my tenant ID>>'.
[2024-09-25 19:04:17.53] Debugger will attach to the next session of type WebServiceClient.
```

In VSCode, the known debugging symbols appear:

![image](https://github.com/user-attachments/assets/0366a119-bfec-433c-acbf-e06520f0c18c)

A breakpoint is set in the OnOpenPage trigger:

![image](https://github.com/user-attachments/assets/54e6c757-22cf-4914-85af-aa81a88a4f41)

3. invoke web service request
I use postman to invoke a webrequest from Postman, but the debugger didn't pick up this WebServiceClient request.

![image](https://github.com/user-attachments/assets/2caec0eb-4470-4178-87a5-894ec5c7ebc9)

``` AL
page 50000 "PTE_Bin Conent"
{
    APIGroup = 'job';
    APIPublisher = 'louage';
    APIVersion = 'v1.0';
    ApplicationArea = All;
    Caption = 'Bin Content';
    DelayedInsert = true;
    EntityName = 'binContent';
    EntitySetName = 'binContents';
    PageType = API;
    SourceTable = "Bin Content";
    SourceTableTemporary = true;

    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field(locationCode; Rec."Location Code")
                {
                    Caption = 'Location Code';
                }
                field(binCode; Rec."Bin Code")
                {
                    Caption = 'Bin Code';
                }
                field(itemNo; Rec."Item No.")
                {
                    Caption = 'Item No.';
                }
                field(variantCode; Rec."Variant Code")
                {
                    Caption = 'Variant Code';
                }
                field(quantity; Rec.Quantity)
                {
                    Caption = 'Quantity';
                }
                field(unitOfMeasureCode; Rec."Unit of Measure Code")
                {
                    Caption = 'Unit of Measure Code';
                }
            }
        }
    }

    trigger OnOpenPage()
    var
        BinContent: Record "Bin Content";
    begin
        if not Rec.IsTemporary() then
            exit;
        if not Rec.IsEmpty() then
            Rec.DeleteAll();
        BinContent.CopyFilters(Rec);
        BinContent.SetAutoCalcFields(Quantity);
        if BinContent.FindSet(false) then
            Rec.Copy(BinContent);
    end;
}
```

**Expected behavior**
The debugger should stop at the breakpoint

**Actual behavior**
The debugger doesn't stop

**Versions:**

- AL Language: v13.1.1065068
- Visual Studio Code: 

> Version: 1.93.1 (user setup)
> Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
> Date: 2024-09-11T17:20:05.685Z
> Electron: 30.4.0
> ElectronBuildId: 10073054
> Chromium: 124.0.6367.243
> Node.js: 20.15.1
> V8: 12.4.254.20-electron.0
> OS: Windows_NT x64 10.0.22631

- Business Central: Version: BE Business Central 24.4 (Platform 24.0.24483.0 + Application 24.4.22295.22393)
- List of Visual Studio Code extensions that you have installed: AL Language Extension
- Operating System:
  * [X] Windows : Windows 11 Enterprise (Version 23H2, OS Build 22631.416)
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
Try to add ``"userId": "<userid-that-is-calling-the-api>"`` to the launch configuration.

**Comment by louagej** [comment]
Hi,
That doesn't work as well

**Comment by dannoe** [comment]
After publishing a change the first attach session fails for me. After starting a second attach session, it works.
I used your code, just another object name and id.

Is your authenticated user from the same tenant as ``"<<my tenant ID>>"``? If yes, you can just remove or comment out the ``tenant`` part in your launch.json. Or maybe try add the tenant-id to the request url. My tests were done in a customer sandbox with my user as a delegated admin.

**Comment by louagej** [comment]
Hi,
The tenant is a customer tenant where we are grated acces trough with GDAP.
So my user account is not in the same tenant.

**Comment by louagej** [comment]
> Try to add `"userId": "<userid-that-is-calling-the-api>"` to the launch configuration.

Hi,
I tried following scenario's
- "userId": "Entra App Registration ID"
- "userId": ""
- "userId": "bearer token calling the api" `This option returned an error from the server that the user couldn't be found.`

But still no breakpoint got hit

**Comment by BazookaMusic** [comment]
Hello,
While this issue is in the scope of the repository, since it involves a customer tenant, it will be much easier to investigate via a support request.

We will need the id of the customer tenant to see what goes wrong during the attempt to attach. GitHub issues is not fit for sharing this information.

Please follow these instructions to make a request. You can ask the support to route it to the Developer Tools team and show them this issue.

The options are:
1) Open a support request to CSS through the PartnerSource portal
2) Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

I will close this issue. Please follow up there.

**Comment by navdotnetreqs** [comment]
Note for anyone looking for info on this:
For me it **only started working when I set userId** (from Entra page) - even though I assumed it to be optional!
