### ISSUE TITLE
Issue publishing with Entra authentication

### ISSUE THREAD

**Issue by KoenvdLouw** [microsoft/AL#7864]
I have setup on-prem BC with Entra authentication and it is working perfectly to log in to BC with Entra. However from within VScode I can't get it to work. Downloading symbols or publishing get's me an error which I can't seem to find what I am doing wrong.

Launch.json
![image](https://github.com/user-attachments/assets/ffd8e049-6f2f-472f-a1ce-76af1a494286)

When downloading symbols I am being redirect to the MS site to log in with my Entra user and allow me for Dynamics 365 Business Central Developer. I do that, allow it and in VScode it then gives this error:

![image](https://github.com/user-attachments/assets/2b96c2b9-1f94-44aa-885a-6ff8df5680ed)

ClientServicesCredentialType is set to AccessControlService to prevent normal username/password login. When I have it on NavUserPassword and log in with my username/password I can download the symbols. So to me the only logical thing is something is wrong with the Entra authentication from within VScode or some setting. I'm however struggling to find the issue and google is not my friend this time. 

BC version 2024 wave 1
VScode version 1.94.0
Al language extension v14.0.1161190

Should this be able to work correctly? Is there anything obvious I am missing or something I need to check ? Any help would be appreciated.

**Comment by BazookaMusic** [comment]
Did you follow this?
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-aad-auth-onprem

I see the primary tenant domain commented out

**Comment by KoenvdLouw** [comment]
I did follow that and allready tried with PrimaryTenantDomain. I was trying a lot of things after that, hence it being commented out at the moment.

I have rechecked with xxxxx.onmicrosoft.com as primaryTenantDomain, but no luck..

**Comment by BazookaMusic** [comment]
Can you check the event viewer when you try to login for errors? Also did you setup the audiences as described in the documentation?

Using Visual Studio Code
If you are connecting to your solution from Visual Studio Code, then you must also specify the Business Central server config parameter ValidAudiences and set it to https://api.businesscentral.dynamics.com. If you do not do this, you will get the error securitytokeninvalidaudienceexception in the application log when trying to download symbols

**Comment by KoenvdLouw** [comment]
I have edited the ValidAudiences and now oData is working. After some change in de launch.json (tenant to default) publishing from within VScode also works. Thanks a lot for your input!
