### ISSUE TITLE
altpgen dataverse authentication failure in al 14.0.1161190

### ISSUE THREAD

**Issue by BeytullahCengiz88** [microsoft/AL#7869]
**1. Describe the bug**
altpgen gives authentication failure during authenticating Dataverse. Reason: One or more errors occurred. (Only loopback redirect uri is supported,) in ms-dynamics-smb. al 14.0.1161190

**2. To Reproduce**
When you run the following powershell script in altpgen.dll directory in ms-dynamics-smb. al 14.0.1161190 then you get this error.
This is not throwing an error in earlyer versions. 

_.\altpgen 
    -project:"C:\Users\Documents\" 
    -packagecachepath:"C:\Users\Customizations\.alpackages" 
    -serviceuri:"https://xxxx-test.crm4.dynamics.com" 
    -entities:msdyn_workorder 
    -tabletype:CDS 
    -baseid:50055 
    -clientid:"" 
    -redirecturi:"xxxxxxxxxxxxxxxx://auth"_

**3. Expected behavior**
When you run this script, you get an 2FA login pop-up window for credentials.

**4. Actual behavior**
It throws inmediately an error instead of authentication.

**5. Versions:**

- AL Language: 14.0.1161190
- Visual Studio Code: 1.94.2
- Business Central: 24.5
- List of Visual Studio Code extensions that you have installed: None
- Operating System:
  * [X ] Windows

![Image](https://github.com/user-attachments/assets/1f67a38b-9a94-4918-8484-c3b5815f4bbe)

![Image](https://github.com/user-attachments/assets/c85c2f74-be80-4a49-b952-b6aa682f2fb3)

**Comment by manisharma31** [comment]
Check this URL and add http://localhost,
https://github.com/MicrosoftDocs/azure-docs/issues/61446

**Comment by BeytullahCengiz88** [comment]
> Check this URL and add http://localhost, [MicrosoftDocs/azure-docs#61446](https://github.com/MicrosoftDocs/azure-docs/issues/61446)

The adding of localhost was already made but it delivers no solution
![Image](https://github.com/user-attachments/assets/445db0aa-af55-4832-adcf-ec0479be1e8f)

**Comment by carcallynx** [comment]
I have the same error.

Does anyone have a solution?

**Comment by manisharma31** [comment]
The redirect url of localhost should be in you script also.
packagecachepath:"C:\Users\Customizations.alpackages"
-serviceuri:"https://xxxx-test.crm4.dynamics.com<https://xxxx-test.crm4.dynamics.com/>"
-entities:msdyn_workorder
-tabletype:CDS
-baseid:50055
-clientid:""
-redirecturi:"http://localhost"

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by carcallynx** [comment]
Thank you. That worked great for me.

**Comment by BeytullahCengiz88** [comment]
Thanks that works indeed!
