### ISSUE TITLE
Usage of custom database on the Dev Preview

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#787]
I would like to explore building extensions for a custom database. This DB is currently on platform Nav2017 Cu11.

I uploaded it to the Nav DEV Preview VM and restored it on the SQL server, opened it in Dev Client to convert it. 
During the conversion I am getting the message "You do not have permission to read the 'Company' Table.".
The user is SUPER and the database has a Nav2017 developer license.

Is the scenario of using a custom database already supported?
Is there already a Nav2018 license, which i'd require?
Is there another way I can update the database?

Thanks!

**Comment by StanislawStempin** [comment]
Using custom database is not supported yet but will be supported from November Update. By supported I mean that it will be possible to generate symbol reference package from your custom database. 

I am not aware of any license changes required for upgrading the database.

**Comment by markbrummel** [comment]
Standing ovation! Thanks Stan! This will make a huge impact on the adoption of VSCode.
