### ISSUE TITLE
Intellisense for "Field" creates Implicit With Warnings

### ISSUE THREAD

**Issue by kasperdj** [microsoft/AL#7872]
**1. Describe the bug**
When adding a field using Intellisense to a page or page extension, "Implicit With" ruleset is not taken into account and is missing the "Rec." before the field name that is inserted.

**2. To Reproduce**
Just add a field to a page or a pageextention and use the "field" intellisense, see example of the bug:

![Image](https://github.com/user-attachments/assets/ca2e2f02-6f3e-4c1c-b127-f02d7c853c09)

See use of IntelliSense here: 
https://github.com/user-attachments/assets/2029d867-6802-4c5d-bd83-ddf3a81414e2

**3. Expected behavior**
![Image](https://github.com/user-attachments/assets/0b6b95da-e63e-446e-9c7b-de1b9b147977)

**4. Actual behavior**
See image in point 2

**5. Versions:**

- AL Language: 14.0.1161190
- Visual Studio Code: 1.94.2
- Business Central: All versions
- List of Visual Studio Code extensions that you have installed:
- Operating System:
  * [x] Windows
  * [ ] Linux
  * [ ] MacOS

**Comment by BazookaMusic** [comment]
You're missing the feature flag in the app.json to not allow implicit with. This is by design for legacy projects where this was the default style.

If you set the flag, the autocomplete will include Rec.

The intent is to keep the project uniform and at the same time, provide code actions to mass convert it.

**Comment by kasperdj** [comment]
No no, I have AppSourceCop, CodeCop and PTECop enables as code analyzers, hence I do not need to set Implicit With Feature flag.
..and the bug reported is related to intellisense which should ALWAYS apply "Rec." in fields name reference regardless if the feature flag is enabled or not - as I do not expect Microsoft to suggest bad code based

**Comment by NKarolak** [comment]
> No no, I have AppSourceCop, CodeCop and PTECop enables as code analyzers, hence I do not need to set Implicit With Feature flag.

Rulesets have absolute no influence on what IntelliSense will insert. They just analyze already written code.
If you want IntelliSense to insert Rec.FieldName, then you definitely must set the feature flag as BazookaMusic suggests. 

> ..and the bug reported is related to intellisense which should ALWAYS apply "Rec." in fields name reference regardless if the feature flag is enabled or not - as I do not expect Microsoft to suggest bad code based

Omitting `Rec.` is bad code only if the feature flag is enabled ;-)
When you don't set the flag, you WANT to use implicit with - and therefore leave out `Rec.` as often as you can.
And once you set the flag, you will see that also some code analyzers will adjust.

Btw, if you ran `AL: Go!` to create a new project, you would see that `NoImplicitWith` is automatically set.
