### ISSUE TITLE
AA0198 and AA0244 and "this" keyword

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/AL#7877]
Please include the following with each issue:

**1. Describe the bug**
This is a tricky one since the compiler is _technically_ correct, but keeping this (no pun intended) enabled like it is would introduce a lot of warnings and is - I think - contrary to the reasons that "this" was added to AL. I realize that it might be hard for the compiler to check this consistently, however.

The problem is that when you have a global variable and a local variable or parameter of the same name, AA0244 still fires, even if you consistently use the "this" keyword.

I would like to see what the community thinks of this. 
For my part, I am not going to advise my team to use "this" to specify global variables/procedures if it introduces more warnings that we then have to handle.

**2. To Reproduce**

1. Ensure CodeCop is enabled in your project
2. Create a codeunit with a global variable
3. Create a public/internal procedure in that codeunit that has either a local variable or a parameter of the same name as the global variable.
4. Assign the global variable using the "this" keyword (i.e. this.MyVar := MyVar)
5. Check the warnings and see that AA0244 still fires

``` AL
codeunit 50060 "This Test"
{
    var
        Customer: Record Customer;

    procedure AssignCustomer(Customer: Record Customer);
    begin
        this.Customer := Customer;
    end;
}
```

``` AL
codeunit 50060 "This Test"
{
    var
        Customer: Record Customer;

    procedure AssignCustomer(CustomerNo: Code[20])
    var
        Customer: Record Customer;
    begin
        if Customer.Get(CustomerNo) then
            this.Customer := Customer;
    end;
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
If the "this" keyword is used consistently throughout procedures to denote the global variable, I hope that the compiler can recognize this and not give the warning (yes, I know that it is hard to determine whether it is used consistently)

**4. Actual behavior**
Both rules still fire even though the "this" would indicate the variables are different.

![Image](https://github.com/user-attachments/assets/1a34da45-4d63-413e-9f3b-366b017fb6b8)

![Image](https://github.com/user-attachments/assets/377dbe18-11f9-4a78-a6ae-8001a1ba64bd)

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:
- Operating System:
  * [x] Windows
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension (caveat: I had to leave CodeCop enabled)

* [x] Simplify your code around the issue to better isolate the problem

**Comment by dannoe** [comment]
In my eyes using the same name for a local/parameter and a global variable is a code smell (even with ``this`` introduced) and could easily lead to errors. I would vote for keeping the warnings as is.

**Comment by nndobrev** [comment]
Hi,
Thank you for raising the concern but this is by design. We might change the design in the future, however, currently we will prioritize other issues. Thank you for raising this concern.
