### ISSUE TITLE
Saving xml documents

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#788]
I'm curious if there is an alternative to XML DOM Management.SaveXMLDocumentToOutStream? If not could we get functionality to allow the custom xml document to be downloaded/saved by the user?

**Comment by StanislawStempin** [comment]
We provide a method XMLDocument.WriteTo(OutStream). See the documentation at:
https://msdn.microsoft.com/en-us/dynamics-nav/developer/api/xmldocument-class
https://msdn.microsoft.com/en-us/dynamics-nav/developer/api/xmldocument-writeto-outstream-method

**Comment by strophanthus** [comment]
Perfect, thanks!
