### ISSUE TITLE
Extension objects can reference members of other extension objects in the same app, regardless of whether the other extension object has a lower or higher object ID

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/AL#7887]
**1. Describe the bug**

When using multiple table extensions to the same target table, we can use the members (procedures, fields, ...), regardless of whether the other extension object has a lower or higher object ID.

Note: I haven't checked other extension objects like pageext, reportext,... would assume that it's the same behavior, has to be tested.

In the changelog it quotes: "Extension objects can reference members from other extension objects in the same app only if the other extension object has a lower object ID." (https://marketplace.visualstudio.com/items/ms-dynamics-smb.al/changelog)

Does this work as intended and does the changelog need to be edited?
Perhaps I have misunderstood something here. What is a member of an object in this case?

**2. To Reproduce**

1. Create two table extensions to the same target that reference each other

```AL
tableextension 50103 CustomerServiceExt extends Customer
{
    fields
    {
        field(50103; Quantity; Integer) { }
    }

    procedure CustomerService()
    begin
        Rec.CustomerPayment();
        Rec.Active := true;
    end;
}

tableextension 50140 CustomerPaymentExt extends Customer
{
    fields
    {
        field(50140; Active; Boolean) { }
    }

    procedure CustomerPayment()
    begin
        Rec.CustomerService();
        Rec.Quantity := 10;
    end;
}
```

**3. Expected behavior**

Based on the quote from the changelog, I would expect only the **CustomerPaymentExt** table extension object to be able to reference the members of the **CustomerServiceExt** table extension object.

The compiler validation: "Extension objects can reference members from other extension objects in the same app only if the other extension object has a lower object ID." is expected to work.

**4. Actual behavior**
It compiles without warnings or errors.

**5. Versions:**

- AL Language: v15.0.1177813
- Visual Studio Code: 
  Version: 1.94.2 (user setup)
  Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
  Date: 2024-10-09T16:08:44.566Z
  Electron: 30.5.1
  ElectronBuildId: 10262041
  Chromium: 124.0.6367.243
  Node.js: 20.16.0
  V8: 12.4.254.20-electron.0
  OS: Windows_NT x64 10.0.26100
- Business Central: W1 25.0 (Platform 25.0.25866.0 + Application 25.0.23364.25903)
- List of Visual Studio Code extensions that you have installed:
  * ms-dynamics-smb.al
- Operating System:
  * [X] Windows
  * [ ] Linux
  * [ ] MacOS
Internal work item: [AB#556002](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556002)

**Comment by esbenk** [comment]
The change-log is a bit vague. The entry is only valid for ordered elements like page controls and actions. E.g. 

![Image](https://github.com/user-attachments/assets/0a361658-7950-467d-a36e-f8f41a8ff99f)

When applying changes from extensions within the same app they are applied in the id order in the runtime. In the example pageext 50101 can't be applied before 50102 because it has changes relative to elements from 50102. 

Code references to table fields and methods does not have to abide to this rule since they are resolved at compile time.
