### ISSUE TITLE
Replaced by SetSourceLine in Order Tracking should refer to SetVariantRec

### ISSUE THREAD

**Issue by stevehughes-adv** [microsoft/AL#7888]
**1. Describe the bug**
Some obsolete functions in page 99000822 Order Tracking refer to a function called SetSourceLine. This function does not exist.
Should the obsolete suggestion refer to procedure SetVariantRec() instead?

Checking Sales Line ShowOrderTracking procedure uses the SetVariantRec

![Image](https://github.com/user-attachments/assets/4bc5c4c8-6d2a-45aa-a3e3-d43d46c4a6d4)

**2. To Reproduce**
1. Navigate to Order Tracking and check example function SetSalesLine.

        [Obsolete('Replaced by SetSourceLine()', '25.0')]
        procedure SetSalesLine(var CurrentSalesLine: Record Microsoft.Sales.Document."Sales Line")
        begin
          OrderTrackingMgt.SetSalesLine(CurrentSalesLine);
          CurrItemNo := CurrentSalesLine."No.";
          CurrQuantity := CurrentSalesLine."Outstanding Qty. (Base)";
          StartingDate := CurrentSalesLine."Shipment Date";
          EndingDate := CurrentSalesLine."Shipment Date";
        end;

2. Search for SetSourceLine but not found

![Image](https://github.com/user-attachments/assets/84ae03f5-5ce2-43f5-9431-edad51dd91e1)

**3. Expected behavior**
SetSourceLine procedure should be found in object 99000822 Order Tracking.

**4. Actual behavior**
SetSourceLine procedure not found in object 99000822 Order Tracking. 

**5. Versions:**

- AL Language: 15.0.1177813 (pre-release)
- Visual Studio Code: 1.94.2
- Business Central: not related
- List of Visual Studio Code extensions that you have installed: not related
- Operating System: Windows

**Comment by PeterConijn** [comment]
I wish we could continue on Yammer, but many of us no longer have access to it.

**Comment by JairJimenez-Nun** [comment]
This issue is now an error, not a warning, I cannot find the SetSourceLine() yet. I cannot access the yammer thread either. Anyone that has access can share the solution? Thanks

**Comment by NKarolak** [comment]
According to a [thread](https://engage.cloud.microsoft/main/org/microsoft.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMzg0MDU0MjA5OTgwODI1NiJ9?trk_copy_link=V2) on the BC Partner network on Viva Engage, use `OrderTrackingMgt.SetSourceRecord` instead.
