### ISSUE TITLE
Cannot update an app (with dependent apps) in onCloud environment version 25.0

### ISSUE THREAD

**Issue by SantiagoMasramon** [microsoft/AL#7892]
**1. Describe the bug**
When trying to update/deploy an app from VS Code to an onCloud environment, which has dependencies the following error occurs

```
Sending request to https://api.businesscentral.dynamics.com/v2.0/XXX/dev/apps?tenant=YYY&SchemaUpdateMode=forcesync&DependencyPublishingOption=default
Error: An error occured while processing the request.
Request ID: 77a7840e-b3d6-409f-9dda-ff8c110023d3
Session ID: a764c70b-3252-4777-a76d-c87f1367a8f1


If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
The request for path /v2.0/XXX/dev/apps?tenant=YYY&SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: A publication failed due to "Extension compilation failed
error AL1024: A package with publisher 'Default Publisher', name 'ALProject1', and a version compatible with '1.0.0.0' could not be loaded. Symbols for the requested app ALProject1 by Default Publisher 1.0.0.0 could not be found among this tenant's installed apps. AppGroup Id 2973". The original extensions have been restored.
```

This does not happen in an OnCloud version 24 environment. 
This happens also using the Publish-BcContainerApp command of BcContainerHelper (executed from a pipeline).

**2. To Reproduce**
Create two apps ALProject1 and ALProject2, such that ALProject2 depends on ALProject1. Both apps created using the AL: GO! command without any major changes and no code except for the HelloWorld.al (and changes needed to make the PageExtension ID not overlap each other, etc.).
When installing ALProject1, then ALProject2 and trying to install ALProject1 again, the error described above occurs.

**3. Expected behavior**
Being able to deploy the app without error

**4. Actual behavior**
The error described in point 1

**5. Versions:**

- AL Language: v14.1.1180850 and v15.0.1177813 (pre-release)
- Visual Studio Code: 1.95.1
- Business Central: W1 25.0 (Platform 25.0.26191.0 + Application 25.0.23364.24599)
- List of Visual Studio Code extensions that you have installed: None except AL Language extension for Microsoft Dynamics 365 Business Central
- Operating System:
  * [X] Windows
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by prathys** [comment]
We have also faced same issue and after contacting Microsoft we came to know that it is a known issue. 

An workaround suggested by MS 

Set "dependencyPublishingOption" to "Ignore" in your launch file.

**Comment by SantiagoMasramon** [comment]
@prathys  Thank you, it works

if it is a known issue, then I close this one.
