### ISSUE TITLE
Having issues Downloading Symbols

### ISSUE THREAD

**Issue by Dbaxter73** [microsoft/AL#7896]
I am trying to download the symbols needed to write in AL and create workflows for power automate. But I keep getting the same error:
[2024-11-07 14:30:19.00] Targeting Dynamics 365 Business Central.
[2024-11-07 14:30:19.01] Sending request to https://api.businesscentral.dynamics.com/v2.0/Production/dev/metadata
[2024-11-07 14:30:40.26] Error: An error occured while processing the request.
Request ID: f5adf4d1-4e6c-47d4-82da-d60ea89689e4
Session ID: 2a69c1ce-7e3e-481a-acbf-8bcf3fa95b38

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2024-11-07 14:30:40.26] The request for path /v2.0/Production/dev/metadata failed with code InternalServerError. Reason: Internal Server Error
[2024-11-07 14:30:40.27] Sending request to https://api.businesscentral.dynamics.com/v2.0/Production/dev/metadata

The code im using to launch is the following:
{
    "version": "0.2.0",
    "configurations": [
        
    

        {
            "name": "Microsoft cloud sandbox",
            "request": "launch",
            "type": "al",
            "environmentType": "Production",
            "environmentName": "Production",
            "server": (removed for privacy)
            "startupObjectId": 18,
            "startupObjectType": "Page",
            "breakOnError": "All",
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "authentication": "AAD"
            
            

        
        }
    ]
}

Also this:
{
  "id": "d273061a-2776-41d0-809c-4c72ef5d195f",
  "name": "ALProject6",
  "publisher": "Default Publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "screenshots": [],
  "platform": "1.0.0.0",
  "application": "24.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": true,
    "includeSourceInSymbolFile": true
  },
  "runtime": "13.0",
  "features": [
    "NoImplicitWith"
  ]
}

Any and all help is appreciated. I have tried to troubleshoot this in the past with other forums with similar issues but the fixes for them didn't fix my issue unfortunately.

**Comment by kalberes** [comment]
Is this a sandbox or production environment. You can only download symbols on a production environment if you use snapshotInitialize request.
Else only sandboxes.
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-launch-file

**Comment by Dbaxter73** [comment]
It is for a production environment yes.
