### ISSUE TITLE
Unable to publish apps to Sandbox Protocol Violation

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/AL#7897]
Please include the following with each issue:

**1. Describe the bug**
I am publishing 5 apps via DevOps pipeline to sandbox and I receive an ERROR The server committed a protocol violation. Section=ResponseStatusLine
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\Saas\Publish-PerTenantExtensionApps.ps1: line 190
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\AppHandling\Sort-AppFilesByDependencies.ps1: line 193
at Sort-AppFilesByDependencies, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\AppHandling\Sort-AppFilesByDependencies.ps1: line 192
at Publish-PerTenantExtensionApps, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\Saas\Publish-PerTenantExtensionApps.ps1: line 136
at <ScriptBlock>, C:\Agent\_work\12\s\Cloud Tests\DeployTestsPTE(Current).ps1: line 13
at <ScriptBlock>, C:\Agent\_work\_temp\39d987bf-c9e1-4d50-ac81-9b459a42a5db.ps1: line 4
at <ScriptBlock>, <No file>: line 1

This happens while it tries to publish the first app. 

**2. To Reproduce**

1.  Run this script
******************************************************************************************
#Use this script to deploy all tests in cloud for ATT
#******************************************************************************************
$refreshToken =$env:RefreshToken
Write-Host "Using refreshToken: $refreshToken"
$tenantid = '<correct tenentid>'
$tenant = '<mytenant>'
$authContext = New-BcAuthContext -refreshToken $refreshToken -tenantID $tenantid
$environment ="<mysandbox name>"
$syncMode = 'Force'
$apps = "C:\Temp\cloudtest\mytests_Tests.zip"
Publish-PerTenantExtensionApps  `
    -bcAuthContext $authcontext `
    -environment $environment `
    -schemaSyncMode $syncMode `
    -appFiles $apps

Write-Host -ForegroundColor Green "Success, All Tests Published Sucessfully!"

2) Pipeline Task looks like this:
 - task: PowerShell@2
    displayName: 'Publish Tests on Cloud'
    continueOnError: true
    enabled: true
    env:
      Username: $(myusername)
      Password: $(Password)
      Tenant: $(TenantId)
      RefreshToken: '$(refreshToken)'     
    inputs:
      targetType: filePath
      filePath: 'Cloud Tests\DeployTestsPTE(Current).ps1'
      failOnStderr: false 
    timeoutInMinutes: 30

**3. Expected behavior**
I expect the task to successfully publish all my apps as PTE

**4. Actual behavior**

The pipeline is failing with this error:

ERROR The server committed a protocol violation. Section=ResponseStatusLine
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\Saas\Publish-PerTenantExtensionApps.ps1: line 190
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\AppHandling\Sort-AppFilesByDependencies.ps1: line 193
at Sort-AppFilesByDependencies, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\AppHandling\Sort-AppFilesByDependencies.ps1: line 192
at Publish-PerTenantExtensionApps, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.28\Saas\Publish-PerTenantExtensionApps.ps1: line 136
at <ScriptBlock>, C:\Agent\_work\12\s\Cloud Tests\DeployTestsPTE(Current).ps1: line 13
at <ScriptBlock>, C:\Agent\_work\_temp\39d987bf-c9e1-4d50-ac81-9b459a42a5db.ps1: line 4
at <ScriptBlock>, <No file>: line 1

It seems to connect to the sandbox without issue and it looks like it is publishing the first app, but it doesn't seem to wait for the first app to finish publishing before it starts publishing the next app.

It also appears that all apps have to be uninstalled and unpublished prior to running the task (which is not the same case when I run the script outside of the pipeline)

All apps publish fine when I ran this same script outside of the pipeline

$tenantid = '<tenantid>'
$tenant = '<mytenant>'
$authContext = New-BcAuthContext  -includeDeviceLogin -refreshToken $refreshToken -tenantID $tenantid
$environment ="<mysandbox name>"
$syncMode = 'Force'
$apps = "C:\Temp\cloudtest\mytests_Tests.zip"
Publish-PerTenantExtensionApps  `
    -bcAuthContext $authcontext `
    -environment $environment `
    -schemaSyncMode $syncMode `
    -appFiles $apps

**5. Versions:**

- AL Language: 
- Visual Studio Code: 
- Business Central: 24.5 and 22.7
- List of Visual Studio Code extensions that you have installed:
- Operating System:
  * [ ] Windows
 
### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by AmandaTest** [comment]
One further note:  After publishing all the apps outside of the pipeline, if I were to rerun the pipeline, the task would pass without issue. So I know my connections are fine.  I am thinking that something could possibly be breaking the authentication connection while it is publishing or it is just not waiting for previous app to finish publishing before it attempts the next one.

**Comment by BazookaMusic** [comment]
Hello, this issue seems related to BcContainerHelper and is out of scope for this repository. This repo is for the AL language compiler and developer tools. Consider opening an issue here:
https://github.com/microsoft/navcontainerhelper/issues
