### ISSUE TITLE
OptimizeForTextSearch issue

### ISSUE THREAD

**Issue by SilviuVirlan** [microsoft/AL#7899]
**1. Describe the bug**
I have enabled full-text search in my BC SaaS environment 
I created a new table with 2 columns, ID and Description.
ID is PK.
Description has OptimizeForSearch = true.

**2. To Reproduce**
table 50100 OptimizedSearchTable
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; Id; Integer)
        {
            DataClassification = CustomerContent;
            AutoIncrement = true;
        }
        field(2; Description; Text[1000])
        {
            DataClassification = CustomerContent;
            OptimizeForTextSearch = true;
        }
    }

    keys
    {
        key(Key1; Id)
        {
            Clustered = true;
        }
    }
}

page 50100 TextSearch
{
    ApplicationArea = All;
    Caption = 'TextSearch';
    PageType = List;
    SourceTable = OptimizedSearchTable;
    UsageCategory = Lists;    

    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field(Id; Rec.Id)
                {
                    ToolTip = 'Specifies the value of the Id field.', Comment = '%';
                }
                field(Description; Rec.Description)
                {
                    ToolTip = 'Specifies the value of the Description field.', Comment = '%';
                }
            }
        }

    }
    actions
    {
        area(Processing)
        {

            action(Search)
            {
                trigger OnAction()
                var
                    FoundMsg: Label 'Found %1 recs';
                    counter: Integer;
                begin
                    Rec.SetFilter(Description, '&&' + 'aa' + '*');
                    counter := Rec.Count();
                end;
            }
        }
    }
}

**3. Expected behavior**
I would have expected to see Rec.Count work, but I get an error:
If requesting support, please provide the following details to help troubleshooting:

Error message: 
An unexpected error occurred after a database command was cancelled.

Page TextSearch has to close.

SQL error message:
The argument type "nvarchar(max)" is invalid for argument 2 of "CONTAINS".
Statement(s) could not be prepared.

Internal session ID: 
16d170b8-5b45-458e-9608-36847cd3fabc

Application Insights session ID: 
2038e928-1d81-4c4c-8f07-a87a348a0bb0

Client activity id: 
f968b6e5-baf0-4186-a8d7-cb7082252208

Time stamp on error: 
2024-11-10T18:54:37.6763097Z

User telemetry id: 
5fab890c-64be-4a5c-88a2-f751ff672622

**4. Actual behavior**
Also, in Admin Center, on Telemetry blade I get the error logged:
AL ErrorCode:Sql:Sql Connection type:WebClient Message: Message not shown because the NavBaseException constructor was used without privacy classification StackTrace: TextSearch(Page 50100)."Search - OnAction"(Trigger) line 6:

**5. Versions:**

- AL Language:v15
- Visual Studio Code:1.95.1
- Business Central:25.0.23364.25996
- List of Visual Studio Code extensions that you have installed:AZ AL Dev Tools/AL Code; waldo's CRS AL Language; AL toolbox; AL Object Designer; AL Code Actions; AL Navigator.
- Operating System:
  [*] Windows

**Comment by BazookaMusic** [comment]
Hello, this repository is only for the AL language compiler and related tools. I will create a bug for the team responsible, but they do not use github thus I will close this issue.

If you need immediate support for this, you can use the following routes.

Open a support request to CSS through the PartnerSource portal

Open a bug in Collaborate

Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
