### ISSUE TITLE
SETSELECTIONFILTER still not possible?

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#79]
Hi, 

I was assuming that I would be able to use SETSELECTIONFILTER, but it appears I can't.  I get the error:

`[2017-01-17 10:31:36.09] Error: The request failed with code 500, reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\100\Server\MicrosoftDynamicsNavServer$Navision_main\source\PageExtension\PageExtension70066090.cs(130,17) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  c:\ProgramData\Microsoft\Microsoft Dynamics NAV\100\Server\MicrosoftDynamicsNavServer$Navision_main\source\PageExtension\PageExtension70066090.cs(130,38) : error CS1061: 'Microsoft.Dynamics.Nav.BusinessApplication.PageExtension70066090' does not contain a definition for 'SetSelectionFilter' and no extension method 'SetSelectionFilter' accepting a first argument of type 'Microsoft.Dynamics.Nav.BusinessApplication.PageExtension70066090' could be found (are you missing a using directive or an assembly reference?)  `

I noticed there is a "CurrPage.SetSelection(Item)" as well, and that does compile and publish.  But when I execute the new action, I get this error:

> Function ID 1 was called. The object with ID 0 does not have a member with that ID.

**Comment by waldo1001** [comment]
THis is what I tried:

```
actions
    {
        // Add changes to page actions here
        addfirst("&Purchases")
        {
            action("Show Selected Items")
            {            
                CaptionML=ENU='Show Selected Items';
                Promoted=true;
                PromotedIsBig=true;
                PromotedCategory=New;
                
                trigger OnAction();
                var
                Item : Record 27;
                begin
                    //CurrPage.SetSelectionFilter(Item);
                    currpage.SetSelection(Item);                    
                    
                    message(format(Item.count));
                end;
            }
        }
            
    }
```

**Comment by StanislawStempin** [comment]
The SetSelectionFilter is clearly a bug. We will have a look.

I couldn't get the SetSelection to compile though:
![snip_20170117115139](https://cloud.githubusercontent.com/assets/23653165/22017620/581526ba-dcab-11e6-929d-afe695f0aecf.png)

**Comment by waldo1001** [comment]
What can I say :-)

![image](https://cloud.githubusercontent.com/assets/12088142/22017927/9762e9a0-dcac-11e6-99e6-e10edfe7cb88.png)

**Comment by waldo1001** [comment]
ah, now I see it - I did it on the Item List .. you did on the Item Card .. may be that's why ...

**Comment by StanislawStempin** [comment]
Ok, it reproduces with Item List. Unfortunately this is another bug
