### ISSUE TITLE
"IF FieldRef.CALCFIELD THEN" should trap the error instead of throwing

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/AL#790]
Hello together,

I used `"IF FieldRef.CALCFIELD THEN ..."` to calculate flowfields.

If the user has no permission to read the table which is defined in the `CalcFormula` the system triggers an error, but it should return `"FALSE"` if the FlowField could not be calculated.

**ErrorMessage:**
"You do not have the following permissions on TableData Cust. Ledger Entry: Read
..."

kind regards,
Benjamin

**Comment by RafaelKoch** [comment]
The attempt do calculate does already read the table behind a FlowField (trace SQL once to see what is happening), so the permission error is quite logical. 
Test for permissions instead: `Ok := Record.READPERMISSION`

**Comment by BenjaminHochstetter** [comment]
Hi,

thank you for your answer.

1. Usualy if I use the boolean result of a like `[Ok :=] EVALUATE(Variable, String[, Number])`, `[Ok :=] Record.GET([Value],...)`, Find, ... no error is triggered.
The behavior of `[Ok :=] FieldRef.CALCFIELD` should be the same. If i use `FieldRef.CALCFIELD` an error should be triggerd if there is a problem if i use `IF FieldRef.CALCFIELD THEN ...` no error should be triggerd.

2. To use the `RecordRef.READPERMISSION` function I have to determine the `Table No.` from the `CalcFormular` of the `FlowField`. I wasn't able to do this with C/AL based on a Record or RecordRef. I would be very happy if you have an idear how to do this.

Thanks in advanced,
Benjamin

**Comment by kalberes** [comment]
Hi
it has been a while with no answers on this thread.  The same reproes for me from C/SIDE.
But your suggestion makes sense. I will add it to our backlog.

**Comment by BazookaMusic** [comment]
We are looking at untriaged issues in the repository to deal with AL development issues.

Due to the fact that this behavior originates from C/Side and that it has been in the product for so long, it would be a breaking change to change it at this point. If it is an issue that still plagues the development experience, feel free to open it again.
