### ISSUE TITLE
Microsoft Automation API - Delete Customer: Error message company currently in use

### ISSUE THREAD

**Issue by SilMueller** [microsoft/AL#7901]
Hello. I want to use the [Microsoft Automation API to delete a company](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/api/dynamics_automationcompany_delete) from a saas environment.

The request seems to be okay and it seems to find the correct company I try to delete, yet I get the following error message:
![Image](https://github.com/user-attachments/assets/ce0df8f2-8872-4622-b684-d99fedb8092c)

Even tough I was on another company I switched to a different one and the error remains.
So I tried testing it in Postman to see if that works, but still the same error:
![Image](https://github.com/user-attachments/assets/7630854e-951f-4445-a823-4dce2fbd1b84)

I have closed every bc environment and I have ensured that I am the only user on this environment.
Is this a known problem or is there maybe something wrong with the request?

Thank you in advance.

BC Version used: 24.5.23489.25852

**Comment by BazookaMusic** [comment]
Hello, this is an issue with the runtime and thus is out of scope for this repository. The repository is only for bug reports on the AL language compiler and developer tools. Please follow the support process below.

- Open a support request to CSS through the PartnerSource portal or the Business Central Admin Center.
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
