### ISSUE TITLE
All endpoints become unreachable after publishing specific endpoint

### ISSUE THREAD

**Issue by IridiumWasTaken** [microsoft/AL#7902]
**1. Describe the bug**
As soon as the production orders are exposed by a custom API, all API endpoints stop working.

**2. To Reproduce**
1. Expose the production orders by an API v2 endpoint:
`page 50088 "API - Production Order"
{
    PageType = API;
    APIVersion = 'v2.0';
    APIPublisher = 'trds';
    APIGroup = 'standard';

    EntityCaption = 'ProductionOrder';
    EntitySetCaption = 'ProductionOrders';
    EntityName = 'productionOrder';
    EntitySetName = 'productionOrders';

    SourceTable = "Production Order";
    SourceTableView = where(Status = filter(Released));
    ODataKeyFields = Status, No.;

    Extensible = false;
    DelayedInsert = true;

    layout
    {
        area(Content)
        {
            repeater(data)
            {
                field(status; Rec.Status)
                {
                    Caption = 'Status';
                }
                field(no; Rec."No.")
                {
                    Caption = 'No.';
                }
}
}
}
`
2. Publish to server.
3. Try to reach any endpoint, it does not matter which one. It fails with 
"Error 500 - Internal Server Error
Sequence contains more than one matching element"

**3. Expected behavior**
I can read the endpoint and other endpoints too. 

**4. Actual behavior**
All endpoints become unreachable until the endpoint is removed.

**5. Versions:**

- AL Language: 8.1
- Visual Studio Code: 1.87.2
- Business Central: Business Central 2021 release wave 2
- List of Visual Studio Code extensions that you have installed:  AL Language Extension
- Operating System:
  * Windows

**Comment by BazookaMusic** [comment]
This repository is only dedicated to bug reports for AL compiler and developer tools. This is an issue with the runtime and is not covered by the repository.

Runtime issues should follow the support process indicated below.

- If you are a Microsoft Partner, follow the [documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/manage-technical-support#escalating-support-issues-to-microsoft) here to escalate a customer issue
- If you are a Business Central customer, read about [reporting a problem](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem)
- Open a bug in [Collaborate](https://aka.ms/collaborate)
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

You can also use [Viva Engage](https://www.yammer.com/dynamicsnavdev) for asking questions and providing feedback around the runtime behavior of the product.
