### ISSUE TITLE
Request to Modify `Source Type` Field in Table 414 to Support Customizable Enum

### ISSUE THREAD

**Issue by AlaWeslati** [microsoft/AL#7908]
The `Source Type` field in the `IC Outbox Transaction` table (ID 414) is currently of type `Option`. We propose changing it to an `Enum` to make it extensible, allowing partners and developers to customize and extend its values as needed.

Reason for Change:

- Using an `Enum` enables extensibility, which aligns with the AL development philosophy.  
- It removes limitations imposed by `Option` fields, improving customization flexibility.  

Expected Outcome:

- Convert the `Source Type` field in table 414 to an `Enum`.  
- Ensure backward compatibility for existing implementations.  

Thank you for considering this enhancement request!

**Comment by BazookaMusic** [comment]
This is not the correct repo for requests on modifications to the base app. Try here:
https://github.com/microsoft/BCApps
