### ISSUE TITLE
Request to Remove `[Scope('OnPrem')]` from `SetBatchMode` in Codeunit 426

### ISSUE THREAD

**Issue by AlaWeslati** [microsoft/AL#7909]
The `SetBatchMode` function in the `Payment Tolerance Management` codeunit (ID 426) is currently marked with `[Scope('OnPrem')]`. However, there seems to be no functionality within the method that would limit its use to on-premises deployments.  

**Reason for Change:**  
- Marking this function as `OnPrem` restricts its use in extensions targeting Business Central SaaS environments.  
- There is no apparent technical limitation or dependency on on-premises features for this function, so it should be accessible in both SaaS and on-premise environments.  
- Removing this scope will increase the flexibility and usability of this codeunit for developers working in cloud-targeted solutions.  

**Expected Outcome:**  
- Remove the `[Scope('OnPrem')]` attribute from the `SetBatchMode` function in codeunit 426 (`Payment Tolerance Management`), allowing it to be used in cloud-targeted extensions.  

Thank you for considering this request to enhance functionality and usability in Business Central SaaS!

**Comment by BazookaMusic** [comment]
This is not the correct repo for requests on the base app. Try here:
https://github.com/microsoft/BCApps
