### ISSUE TITLE
Bug - Undo Receipt Line for Sales Return Order

### ISSUE THREAD

**Issue by yarenkaplann** [Microsoft/AL#7912]
**1. Describe the bug**
Getting Error by using "Undo Receipt Line" button for Sales Return Order document

**2. To Reproduce**

1. Go to new Sales Return Order
2. Add 3 items to the document in seperate lines. It's important to add items in order with: first item without tracking, second item with tracking and third item without tracking
3. Receive all items
4. Go to Receipt document of related sales return order.
6. Select all lines of items
7. Click on "Undo Receipt Line" button

``` AL
![Image](https://github.com/user-attachments/assets/bf1685bf-968f-4eda-a6ce-f15a9bbbe73a)
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
It will be undo lines by clicking "Undo Receipt Line" button.

**4. Actual behavior**
When clicking on "Undo Receipt Line" button, system gives error called "Value Entry ... already exist".

**5. Versions:**

- AL Language:
- Visual Studio Code: 23.0 , 23.5 and 24.5 (bug is detected for all AL language symbols)
- Business Central: 23.0(On-Prem) , 23.5(On-Prem) and 24.5(Cloud)
- List of Visual Studio Code extensions that you have installed: installed extensions added below as screenshot
- ![Image](https://github.com/user-attachments/assets/fe4a17b6-8fdd-4d14-bff7-58cbf902fa06)
- Operating System:
  * [x] Windows 10
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
This repository is only dedicated to bug reports for AL compiler and developer tools. Runtime issues should follow the support process indicated below. 

# How to get help
- Review our resources for [help and support](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support)
- If you are a Microsoft Partner, follow the [documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/manage-technical-support#escalating-support-issues-to-microsoft) here to escalate a customer issue
- If you are a Business Central customer, read about [reporting a problem](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem)
- Open a bug in [Collaborate](https://aka.ms/collaborate)
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

## General Questions
You can use [Viva Engage](https://www.yammer.com/dynamicsnavdev) for asking questions and providing feedback around the runtime behavior of the product.
