### ISSUE TITLE
Package could not be created. .rdl is opened in another application.

### ISSUE THREAD

**Issue by Gatimu** [microsoft/AL#7915]
I'm persistently encountering an issue when trying to compile the solution. I keep receiving an error indicating that a particular file is open. Does anyone have a solution?

**g:\SOLUTIONS\STAGE\ - Stage\src\Reversal Management\Rep50000DeleteData.al(85,13): error AL0445: The file 'mylayout.rdl' is opened in another application. Close the application to be able to compile.

Compilation ended at '13:40:19.333'.

Error: The package could not be created.**

**Comment by blrobl** [comment]
Hi, as the error message indicates, the file is being used by another application while the project is being compiled. If you believe this is a bug on our side, please re-open the issue provide us with more information, including screenshots and steps that allow us to reproduce the issue.

You can also use [Viva Engage](https://www.yammer.com/dynamicsnavdev) for asking questions and providing feedback around the runtime behavior of the product from the community.
