### ISSUE TITLE
Since BC 25.0 IncomingDocument."Document Type" is always set to Journal

### ISSUE THREAD

**Issue by iti-konrad-jasinski** [microsoft/AL#7917]
### **Incoming Document Type defaults to Journal in BC 25.1 for Sales Invoices**

---

**Describe the issue:**

In Business Central 25.1, the **Document Type** for an Incoming Document linked to a Sales Invoice defaults to **Journal** instead of **Sales Invoice**. This behavior is inconsistent compared to previous versions (e.g., BC 24), where the correct Document Type is assigned.

---

**Steps to reproduce:**

1. Tested in a container with BC 25.1 (the issue does not occur in BC 24).  
2. Create a new Sales Invoice.  
3. Attach an Incoming Document to the Sales Invoice.  

**Expected behavior:**  
- The Document Type for the Incoming Document should be set to **Sales Invoice**.  

**Actual behavior:**  
- The Document Type is incorrectly set to **Journal**.

---

**Technical details:**

The issue stems from the **`GetUnpostedSalesPurchaseDocType`** function in codeunit 134 **"Import Attachment - Inc. Doc."**. Starting in BC 25, there is an exit clause:

```al
if RelatedDocumentType <> RelatedDocumentType::" " then
    exit;
```

The RelatedDocumentType enum value is by default (value 0) set to Journal (not " "), causing the Incoming Document to have the incorrect Document Type.

**Impact**:

This behavior is inconsistent with the autogenerated Incoming Documents using Digital Vouchers, which assign the correct Document Type.
When accessing the Incoming Documents via the BC standard API, the parentType is incorrectly set to Journal, and parentId is a null GUID ("00000000-0000-0000-0000-000000000000"), as shown below:

```json
{
    "@odata.etag": "W/\"JzIwOzE0NTQwODg3MzAyNDgyNjg5MTY1MTswMDsn\"",
    "id": "234eef9c-d5ab-ef11-b632-ccb081c367bf",
    "parentId": "00000000-0000-0000-0000-000000000000",
    "fileName": "Test 1.pdf",
    "byteSize": 85251,
    "lastModifiedDateTime": "2024-11-26T09:05:43Z",
    "parentType": "Journal",
    "attachmentContent@odata.mediaEditLink": "http://test25:7048/BC/api/v2.0/companies(5cdd1530-dba8-ef11-a600-c576beaf3f41)/attachments(234eef9c-d5ab-ef11-b632-ccb081c367bf)/attachmentContent",
    "attachmentContent@odata.mediaReadLink": "http://test25:7048/BC/api/v2.0/companies(5cdd1530-dba8-ef11-a600-c576beaf3f41)/attachments(234eef9c-d5ab-ef11-b632-ccb081c367bf)/attachmentContent"
}
```

**Comment by thpeder** [comment]
HI @iti-konrad-jasinski,
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
