### ISSUE TITLE
Bug - Table DrillDownPageId Property

### ISSUE THREAD

**Issue by yarenkaplann** [microsoft/AL#7919]
**1. Describe the bug**
If table DrillDownPageId property defined and in that table there is a flowfield which uses lookup formula, then page gives error while opening.

**2. To Reproduce**
1- create a new table 
2- add two fields to table, one field just for the table requirements(field type is not important), define other field as flowfield and use lookup formula for that field.
3- create a new page for newly created table and just use flowfield in that layout of the page.
4- define PageType property as ListPart for the new page.
5- create an extension page for sales order and and created new test page as part into sales order extension page.
6- publish app to Business Central.
7- try to open new sales order page or existing sales order page.

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.

newly created table:
![Image](https://github.com/user-attachments/assets/5067aa7b-7a04-435a-89f3-438e71948951)

newly created test page as listpart:
![Image](https://github.com/user-attachments/assets/771ba757-8f55-4109-be72-9a0feb8105e4)

newly created extension page:
![Image](https://github.com/user-attachments/assets/bd32f1ae-310b-421a-830e-32e8b9cc1ebe)

```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

code block for new table:
```AL
table 50100 "Test Table"
{
    Caption = 'Test Table';
    DataClassification = ToBeClassified;
    DrillDownPageId = "Test Page";

    fields
    {
        field(1; "PK"; Boolean)
        {
            Caption = 'PK';
        }
        field(2; "Test Sales Line"; Boolean)
        {
            Caption = 'Test Sales Line';
            FieldClass = FlowField;
            CalcFormula = lookup("Test Table"."Test Sales Line");
        }

    }
    keys
    {
        key(PK; PK)
        {
            Clustered = true;
        }
    }
}
```
----------------
code block for test page:
```AL
page 50100 "Test Page"
{
    ApplicationArea = All;
    Caption = 'Test Page';
    PageType = ListPart;
    SourceTable = "Test Table";


    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field("Test Sales Line"; Rec."Test Sales Line")
                {
                    ToolTip = 'Specifies the value of the Test Sales Line field.', Comment = '%';
                }
            }
        }
    }
}
```
--------------
code block for sales order extension page:
```AL
pageextension 50101 "Sales Order Ext." extends "Sales Order"
{
    layout
    {
        addafter(SalesLines)
        {
            part(testpage; "Test Page")
            {
                ApplicationArea = All;
            }
        }
    }

    actions
    {
        // Add changes to page actions here
    }

    var
        myInt: Integer;
}
```
-------------

**3. Expected behavior**
When a new table created and used in a list part page and also added to a an existing page in Business Central, page needs to be opened and page needs to display newly added list part page.

**4. Actual behavior**
After a new table created and used in a list part page and also added to a an existing page in Business Central, and then trying to open related extension page, page gives error called "A flow field is part of the query column list, this is not supported". Related error screenshot added below.

This error is get from On-Prem:
![Image](https://github.com/user-attachments/assets/77d15524-407a-4c5d-9306-2b6fbe05bc26)

Cloud gives same error called "A flow field is part of the query column list, this is not supported" also and in addition to that, gives "Somenthing went wrong" error also and shotdowns immediately:
![Image](https://github.com/user-attachments/assets/f681ac42-5242-44aa-b1a9-1e33a9f945fc)

**5. Versions:**

- AL Language: 23.1 & 24.5
- Visual Studio Code:
- Business Central: On- Prem 23.1 and Cloud 24.5
- List of Visual Studio Code extensions that you have installed:
 ![Image](https://github.com/user-attachments/assets/de2d594c-9fe6-4b11-be33-50373f878be3)
- Operating System:
  * [] Windows
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JMA1972** [comment]
This issue is wrongly placed because it isn't a problem in VS Code. Nonetheless it's a simple programming error, a flowfield can never refer to itself. It can refer to other flowfields in some circumstances but only if there is a real field after all the lookups in the chain are resolved.

**Comment by thpeder** [comment]
Hi @yarenkaplann,
As the error already writes, this is not a supported scenario. However if you still think it should be, then let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
