### ISSUE TITLE
Target object is not found

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#792]
I created a new environment with october update.

I cannot access any standard object in AL. 
Even the HelloWorld.al have the error message "The target Page "Customer List" for the extension object is not found" 

What is wrong with my project?

I created the project as follows:
- Alt + A
- Alt + L
- Name of project
- Select Cloud
- Now he asks for authentication (I denied this because I have no authentication which is okay; is this the problem?)
- Then I changed the launch.json as described on landing page
- download symbols

My launch.json looks like:
"type": "al",
"request": "launch",
"name": "Cloud",
"startupObjectId": 22,
"server": "https://xxx.eastus.cloudapp.azure.com",
"serverInstance": "NAV",
"tenant": "",
"authentication": "UserPassword"

My app.json looks like:
"id": "4c18c173-a236-4687-bd5a-2584e5670a9a",
  "name": "ALProject2",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": {
    "version": "11.0.0.0",
    "locale": "US"
  },
  "idRange": {
    "from": 50100,
    "to": 50149
  }

**Comment by StanislawStempin** [comment]
Press Ctrl + Shift + P and select command "AL: Download Symbols". When prompted for username password use "admin" and then the password that you used for provisioning the VM.
It should work afterwards.

**Comment by Labberlich** [comment]
I already run the command "Download Symbols" too. 
The compiler still shows the error message. When I press Ctrl + Space I can see the objects.

**Comment by StanislawStempin** [comment]
Did the command succeed? Do you see Application and System .app symbol files in a folder called .alpackages?

**Comment by Labberlich** [comment]
Command was successfull. See output below.

In .alpackages I have only the following files:
- Microsoft_System_11.0.12925.0.app
- Microsoft_US_11.0.18712.0.app

Output
[2017-10-18 09:22:00.77] Using reference symbols cache path: c:\Users\vmadmin\Documents\AL\ALProject2\.alpackages
[2017-10-18 09:22:00.83] Sending request to https://onixdevprevoct.eastus.cloudapp.azure.com:7049/NAV/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0
[2017-10-18 09:22:00.84] Sending request to https://onixdevprevoct.eastus.cloudapp.azure.com:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-10-18 09:22:01.51] All reference symbols have been downloaded.

**Comment by cbulson** [comment]
I had a similar problem on the last build and simply had to go to File > Save.  This refreshed it in some way and it started working.

**Comment by Labberlich** [comment]
I tested to save the file with File > Save. 
It seemed not to change anything. I still have the error message.

**Comment by strophanthus** [comment]
I am experiencing the same issue

Output of download symbols: 
[2017-10-19 12:50:08.92] Using reference symbols cache path: c:\ALConvert\VSPROJ\.alpackages
[2017-10-19 12:50:08.92] Sending request to http://localhost:7064/DynamicsNAV110/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0
[2017-10-19 12:50:08.92] Sending request to http://localhost:7064/DynamicsNAV110/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-10-19 12:50:09.01] All reference symbols have been downloaded.

Result is Microsoft_System_11.0.12925.0.app and Microsoft_US_11.0.18596.0.app in c:\ALConvert\VSPROJ\.alpackages

VS Code version is 1.17.2

AL Language version is 0.9.13932

I deleted the .app files and tried again a couple times. I've restarted VS Code (including closing and reopening the folder), saving in VS code, and refreshing the explorer.

**Comment by StanislawStempin** [comment]
Could you please make sure that you're all using the latest released versions of both the NAV Server and AL Language extension? 
You should be using the following build numbers:
NAV - 11.0.18712.0
AL Language - 0.10.13928
(These are the versions currently available through aka.ms/navdeveloperpreview)

If you're still encountering the problem using these versions, please let us know.

**Comment by Labberlich** [comment]
Okay it works now. 

I reinstalled AL Language.

**Comment by strophanthus** [comment]
@StanislawStempin Is the azure portal required for the AL Language 0.10.13928? I switched to the Insider's VS Code but the newest version of AL Language I can see is still 0.9.13932.

**Comment by StanislawStempin** [comment]
The AL Language available from VS Code Marketplace should only be used against the Microsoft Cloud sandboxes. 

The navdeveloperpreview releases should be used with AL Language extension version that is bundled with it. You can find the link on the VM landing page.

**Comment by strophanthus** [comment]
Where can I find the vsix somewhere other than the azure cloud or docker?

**Comment by freddydk** [comment]
Well, you would need to have a Nav Server that matches the .vsix.
The .vsix in the marketplace matches the Server in the cloud, the one on aka.ms/navdeveloperpreview (download it from the landingpage) matches the server in the docker container in the VM.

**Comment by SUD-D365** [comment]
@strophanthus  you can find it inside the directory "C:\DEMO\navserver" on your azure VM.

**Comment by strophanthus** [comment]
oh, thank you! I should have updated, I have managed to get a hold of it :)
