### ISSUE TITLE
Still error AL0133: cannot convert from <type> to __MissingTypeSymbol__  with alc.exe 14.1.1180850

### ISSUE THREAD

**Issue by petterssonmv** [microsoft/AL#7923]
### **This is a reopening of https://github.com/microsoft/AL/issues/7529 Cannot Convert from 'type' to _MissingTypeSymbol**

**1. Describe the bug**
GIVEN
- An AL-project with several dependent apps with Business Central 14 OnPrem as target with added and modified C/AL objects.
- Using alc.exe 14.1.1180850

WHEN
Running alc.exe to compile the project 

THEN
` error AL0133: Argument 1: cannot convert from 'Record "POS Menu Line"' to '__MissingTypeSymbol__'`

**2. To Reproduce**
1. Use a BC14 database
2. Create an AL app 1.
3. Write a codeunit in AL with a procedure that use a C/AL table as var parameter.
4. Create an AL app 2.
5. Write a codeunit in AL with the C/AL table as parameter.
6. Declare the 1st codeunit as a variable.
7. In the OnRun trigger, call the procedure in that codeunit with Rec as parameter.
8. Compile using alc.exe 

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

 Set-Location C:\users\petterssonm\source\repos\SA-RBD-Dev\Apps\NO\Module2\RIP-IX\RIP Activity\
 remove-item *.app
  = get-childitem -Path C:\Users\petterssonm\.vscode\extensions\ -Recurse
  = C:\Users\petterssonm\.vscode\extensions\ms-dynamics-smb.al-14.1.1180850\bin\win32\alc.exe +  /project:. /packagecachepath:./.alpackages/ /assemblyprobingpaths: + "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Add-ins","C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Add-ins\LSRetail","C:\Windows\assembly","..\DotNetPackages"
 invoke-expression -Command C:\Users\petterssonm\.vscode\extensions\ms-dynamics-smb.al-14.1.1180850\bin\win32\alc.exe /project:. /packagecachepath:./.alpackages/ /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Add-ins","C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Add-ins\LSRetail","C:\Windows\assembly","..\DotNetPackages"
Microsoft (R) AL Compiler version 14.1.18.1238
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'RIP Activity' containing '2' files at '14:55:28.475'.

Codeunit\CgiActivityModule.Codeunit.al(9,59): error AL0133: Argument 1: cannot convert from 'Record "POS Menu Line"' to '__MissingTypeSymbol__'

Compilation ended at '14:55:38.532'.

PS C:\users\petterssonm\source\repos\SA-RBD-Dev\Apps\NO\Module2\RIP-IX\RIP Activity>

```
Example code snippet:
```
codeunit 90198 cgiPosCommandMaster
{
TableNo = "POS Menu Line";

procedure RegisterRIPActivityModule(var MenuLine: Record "POS Menu Line")
var
        POSMenuHeader: Record "POS Menu Header";
        POSMenuLine: Record "POS Menu Line";
        Module: Code[20];
        CodeunitId: Integer;
    begin
     // Register Retail Module
....
    end;

codeunit 90340 "Cgi Activity Module"
{
    TableNo = "POS Menu Line";
    SingleInstance = true;

    trigger OnRun()
    begin
        if "Registration Mode" then
            cgiPosCommandMaster.RegisterRIPActivityModule(Rec);
    end;
.....
    var
        cgiPosCommandMaster: codeunit cgiPosCommandMaster;
}

```

**3. Expected behavior**
Output from alc.exe: None. The compilation should end without errors.

**4. Actual behavior**
Output from alc.exe: ` error AL0133: Argument 1: cannot convert from 'Record "POS Menu Line"' to '__MissingTypeSymbol__'`

This is still an issue for BC14 using alc.exe.  Compiling in VSCode using AL extension 14.1.1180850 does work since some version ago.
The problem is that it still breaks all our pipelines that use alc.exe.

### **Could the fix that was made for the AL extension also be implemented in alc.exe please?**

**5. Versions:**

- AL Language: 14.1.1180850
- Visual Studio Code: * Version: 1.95.3 (user setup)
- Business Central:  14.0.41143.0
- List of Visual Studio Code extensions that you have installed:
  - AL Language extension 
  - AL Extension Pack
  - GitHub Copilot
  - GitLens
- Operating System:
  * Windows OS: Windows_NT x64 10.0.20348

_____________________________________________________________________________

**Not Working: alc.exe 14.1.1180850**
![Image](https://github.com/user-attachments/assets/5bad6c46-abe9-4863-b92c-5d1ce4124c94)

**Working: alc.exe 11.7.863928**
![Image](https://github.com/user-attachments/assets/15a0c6ba-670e-4c70-89ea-3fd8b5120206)

**Comment by kalberes** [comment]
I do not think we will fix this. Although have you tried having the same symbols when resolving from alc.exe and vscode.
Alc.exe is just a wrapper around the same subsystem that vscode is using with input parameters coming though different channels.
14.x C/SIDE I know it is still in use but it is out of support. Sorry.
