### ISSUE TITLE
Using ternary operator with variant methods leads to runtime error

### ISSUE THREAD

**Issue by zeande** [microsoft/AL#7926]
**1. Description**
The ternary operator is awesome, but it appears there is an edge case that leads to a runtime error. It only happens when the expression is `false` and the corresponding expression is a method that returns a non-text variant (e.g. integer).

**2. Repro Steps**
Easiest way to reproduce is to run the following test method:

``` AL
    [Test]
    procedure TestTernaryVariants()
    var
        MyCondition: Boolean;
        MyVariant: Variant;
    begin
        MyCondition := true;
        MyVariant := MyCondition ? GetVariant() : 'Bar';
        MyVariant := MyCondition ? 'Bar' : GetVariant();

        MyCondition := false;
        MyVariant := MyCondition ? GetVariant() : 'Bar';
        MyVariant := MyCondition ? 'Bar' : GetVariant(); // <-- This line (and only this line) fails
    end;

    local procedure GetVariant() Result: Variant
    begin
        Result := 1234; // Test passes if this is a string
    end;
```

**3. Expected behavior**
In the last line, I would expect that `MyVariant` contains the integer value `1234`.

**4. Actual behavior**
The following runtime error:
The expression Microsoft.Dynamics.Nav.Runtime.NavIndirectValue cannot be type-converted to a Microsoft.Dynamics.Nav.Runtime.NavText value.

**5. Versions:**

- AL Language: 14.1.1180850
- Visual Studio Code: 1.95.3
- Business Central: 25.1 (CH)
- List of Visual Studio Code extensions that you have installed: N/A (Issue is not related to developer experience itself)
- Operating System: 
  * [x] Windows
  * [ ] Linux
  * [ ] MacOS

**Comment by BazookaMusic** [comment]
This is by design. The type that the ternary returns is defined by the part of the body that is true. The generated code tries to cast the else to the same type.

So for the lines you shared:

MyCondition := true;
        MyVariant := MyCondition ? GetVariant() : 'Bar'; // returns variant, no cast
        MyVariant := MyCondition ? 'Bar' : GetVariant(); returns text, no cast

        MyCondition := false;
        MyVariant := MyCondition ? GetVariant() : 'Bar'; // returns variant, casts text to variant
        MyVariant := MyCondition ? 'Bar' : GetVariant(); // <-- returns text, tries to cast text to variant

The last line is not a compile error because during runtime, variant can contain text. However the ternary expects both the  true and the false cases to have the same type or be possible to be cast to the type of the true case, thus you see the compile error.

**Comment by navdotnetreqs** [comment]
Here's a super simple example to demonstrate this bug:
```
pageextension 50100 "Customer List Test" extends "Customer List"
{

    trigger OnOpenPage()
    var

        Boo: Boolean;
        Quantity: Decimal;
        OrigQty: Decimal;

    begin
        OrigQty := 0.25;
        Boo := false;
        Quantity := Boo ? 1 : OrigQty;
    end;
}

```

![Image](https://github.com/user-attachments/assets/6b4413e5-5038-4a07-8243-6d3ceac768ab)


I don't agree with the choice to not test the types and define the return type by the left variable.
