### ISSUE TITLE
Evaluating Conditional Expressions

### ISSUE THREAD

**Issue by gregarican** [microsoft/AL#7927]
Typically one would expect mulitple conditionals to be evaluated from left to right. And the remainder of the conditional expressions can be short-circuited and not evaluated, depending on the cirumstances.

Below is my sample code. Unless I wrap the procedure in a TryMethod, there is a runtime error "Index and length must refer to a location within the string." Pertaining to the Substring function, which shouldn't even be evaluated. Since the very first conditional expression is false. So one would assume that the Substring function wouldn't be a factor. Neither would the StartsWith function, since one would assume that the conditional logic would be short-circuited.

    procedure StringParsing()
    var
        InputString: Text[50];
    begin
        InputString := '01000000IT1092012';
        if (Text.StrLen(InputString) > 20) and (InputString.StartsWith('01')) and (InputString.Substring(17, 2) = '21') then
            Message('Hello world!');
    end;

Is this expected behavior?

**Comment by BazookaMusic** [comment]
Yes, AL is based on C/AL which had this behavior. Unfortunately for now, you need to nest your ifs for short-circuiting.

**Comment by NKarolak** [comment]
@gregarican There are some other patterns to implement lazy evaluation in AL:
https://nataliekarolak.wordpress.com/2022/12/21/lazy-evaluation-in-al/
