### ISSUE TITLE
The target table of table extension 'XXX Source Code Setup' has changed from 'MissingTypeSymbol' to 'Source Code Setup'

### ISSUE THREAD

**Issue by iti-mikolaj-sledz** [microsoft/AL#7929]
Please include the following with each issue:

**1. Describe the bug**
We have a problem when running Run-ALCops for our app, but with a table extension that hasn’t been changed for several releases. The issue only occurs on version 23; it does not occur on higher versions of Business Central.

##[error]./C:/ProgramData/BcContainerHelper/e739898c-0903-4e6c-a952-9c7241ecd6db/src/src/tableextension/XXXSourceCodeSetup.TableExt.al(1,25): error AS0068: The target table of table extension 'XXX Source Code Setup' has changed from 'MissingTypeSymbol' to 'Source Code Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.

Object code 
```
tableextension YYYYYYYYYY "XXX Source Code Setup" extends "Source Code Setup"
{
    fields
    {
        field(YYYYYYYYYY ; "Field Name"; Code[10])
        {
            Caption = 'Field Name';
            DataClassification = CustomerContent;
            TableRelation = "Source Code";
        }
    }
}
```

**2. To Reproduce**
AL-Go Run-AlCops on BC 22 W1 

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Run-ALCops ends without error. 
**4. Actual behavior**
##[error]./C:/ProgramData/BcContainerHelper/e739898c-0903-4e6c-a952-9c7241ecd6db/src/src/tableextension/XXXSourceCodeSetup.TableExt.al(1,25): error AS0068: The target table of table extension 'XXX Source Code Setup' has changed from 'MissingTypeSymbol' to 'Source Code Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
**5. Versions:**

- AL Language: Runtime 12
- Visual Studio Code:  Works :) 
- Business Central: 22 W1
- List of Visual Studio Code extensions that you have installed:
- Operating System:
  * [ X] Windows
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [X ] Search the issue repository to ensure you are reporting a new issue

* [ X] Reproduce the issue after disabling all extensions except the AL Language extension

* [ X] Simplify your code around the issue to better isolate the problem

**Comment by kalberes** [comment]
We only handle issues related to teh latest or prerelease versions in this repo.
All other issues have to find their way using some other means.
Official answer:
![Image](https://github.com/user-attachments/assets/7da63a49-cc9b-4a4c-a9ed-f5fdb0616525)
