### ISSUE TITLE
Continue keyword in 15.0.1251530 breaks existing code

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7930]
**1. Describe the bug**
With the newest pre-release 15.0.1251530 the ``continue`` keyword was introduced for loops. This breaks existing code, if there is a variable called continue. 

**2. To Reproduce**

- Update to 15.0.1251530
- Open existing project with a variable called "continue":
```AL
procedure SetContinue(NewContinue : Boolean)
begin
    Continue := false;
end;
```

**3. Expected behavior**
It would be great to be able to use my continue variable with an old "runtime" set in the app.json. 
This could trigger quite some errors for appsource validations or upgrades, couldn't it?

**4. Actual behavior**
I am getting compiler errors:
If the continue variable is used outside of a loop: AL0873
If the continue variable is used inside of a loop: Syntax error, 'end' expected

**5. Versions:**

- AL Language: 15.0.1251530
- Visual Studio Code: 1.95.3
- Operating System: Windows

**Comment by BazookaMusic** [comment]
It's a known issue, we are releasing the pre-release version every once in a while with the latest changes so this went through.

We will very soon release a new version of the pre-release where if there is any symbols with colliding names, we will not bind the continue keyword. Also it will not be bound at all for older runtimes.

**Comment by BazookaMusic** [comment]
New version should fix it, let me know if there are other issues
