### ISSUE TITLE
Unreadable information in AL Outline panel

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#7934]
**1. Describe the bug**
Good morning,
I don't know how to reproduce it but this is happening to me quite often.

![Image](https://github.com/user-attachments/assets/6b7bcba8-c943-465b-a258-1c0bba1874d3)

**2. To Reproduce**
I think it may be related to enabling the "Follow Cursor" option which on the other hand appears right now with a question mark:

![Image](https://github.com/user-attachments/assets/65028d82-9b9c-42cc-87bb-847d42ab6517)

**3. Expected behavior**
A clear and concise information in AL Outline Panel.

**4. Actual behavior**
As discribed.

**5. Versions:**

- AL Language: 14.2.1249978
- Visual Studio Code:
Versión: 1.96.0 (user setup)
Confirmar: 138f619c86f1199955d53b4166bef66ef252935c
Fecha: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
SO: Windows_NT x64 10.0.22631
- Business Central: N/A
- List of Visual Studio Code extensions that you have installed: N/A
- Operating System:
  * [X] Windows 11
  * [ ] Linux
  * [ ] MacOS

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by NKarolak** [comment]
You are in the wrong repository - the AL Outline belongs to the extension [AZ AL Dev Tools/AL Code Outline](https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline).

**Comment by JavierFuentes** [comment]
Ah, ok, sorry...

I found this link doing a quick search and thought it was yours.

https://learn.microsoft.com/es-es/dynamics365/business-central/dev-itpro/developer/devenv-al-outline-view

**Comment by NKarolak** [comment]
No wonder, as the standard "Outline" and "AL Outline" panels in VS Code are very easy to confuse.
Btw, I'm not working for Microsoft ;-)
