### ISSUE TITLE
Text variable methods throw unneeded CodeCop Warning

### ISSUE THREAD

**Issue by damse60** [microsoft/AL#7935]
Using text instance methods like:

TextVariable.Trim(), TextVariable.ToUpper()

will throw an CodeCop AA0139.

Example:

_var
  Name: Text[50]

begin
   Name := Name.Trim().ToUpper();
end;_

This will be marked with "possible overflow assigning 'Text' to 'Text[50]' which is not needed.

All non-adding methods should never cause this warning, like:

Remove
ToLower
ToUpper
Trim
TrimStart
TrimEnd

AL Language Extension 14.1.1180850

**Comment by nndobrev** [comment]
Hi,
 
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
 
Thanks
