### ISSUE TITLE
Question: Visual Studio Code Tasks: Signing

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL#795]
I am trying to automate the signing of the packages and therefore am using a task. However, the question is - how do I get the ".app" filename in a task? I know, it is publisher_name_version.app, but are those variables from the app.json available in the tasks? If not, can they be made available?

**Comment by StanislawStempin** [comment]
They are not available but you could parse the app.json file in your task. We will look into optimizing it in the future.

**Comment by pzentner** [comment]
Thank you, good idea. eventually, this will probably wind up in our release process on TFS, but at least for now, while things are changing rather frequently, it doesn't make sense yet to finalize the new release process (e.g. having to replace alc every couple weeks or so), although ModernDev makes it a lot cleaner and easier

**Comment by ik3ras** [comment]
Maybe it will help someone.

We use task.json:
{
    "version": "2.0.0",
    "windows": {
        "options": {
            "shell": {
                "executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "args": [
                    "-NoProfile",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-Command"
                ]
            }
        }
    },
    "tasks": [
        {
            "label": "SignApp",
            "type": "shell",
            "command": "${cwd}/PSScripts/SignApp.ps1 -taskList SignApp",
            "problemMatcher": []
        }        
    ]
}            

that runs PSSCript:
$NAVXPath = Get-ChildItem *.app
$Cert = Get-PfxCertificate -FilePath "CodeSigning.pfx"
Set-AuthenticodeSignature -Certificate $Cert -FilePath $NAVXPath

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

As mentioned it is possible to parse the app.json through any JSON parsing library and get these values. 

If this is a feature that you would really like to have integrated, I recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.

We are constantly monitoring top ideas and will consider them for a future release.
