### ISSUE TITLE
Unable Node.WriteTo through SOAP call 

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/AL#797]
Unable Node.WriteTo(TextVariable) through SOAP call.
Error message: "The requested operation cannot be performed in this context."

**Comment by atoader** [comment]
Hi! Could you please clarify what you mean? It would be great if you could provide a snippet of code that reproduces the issue.

**Comment by dkorinets** [comment]
Cant't reproduce it with current version 11.0.19756.0-finus
