### ISSUE TITLE
October preview: report RequestFilterFields do not show as expected

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#799]
Until September this code gave me expected controls on a request page:

```
dataset
    {
        dataitem(Item;Item)
        {
            RequestFilterFields = "No.",Description;
```

Now I Can no longer see my Request Filter fields when I run the report. What did I miss?

**Comment by thpeder** [comment]
You haven't missed anything. There was a bug which is fixed now.

Thanks for reporting it,
Thomas
