### ISSUE TITLE
"logo" in app.json

### ISSUE THREAD

**Issue by ReneGubler** [Microsoft/AL#80]
Hi
Is is supportet to use the logo property in the app.json file yet? Where do I have to put the image file into? 
I tried to put it in the source folder and just userd the file name. But i try to publish the extension it hangs somehow. 

![image](https://cloud.githubusercontent.com/assets/25059443/22017602/49bdef02-dcab-11e6-94ae-567530b56c61.png)

This is the compiler output
![image](https://cloud.githubusercontent.com/assets/25059443/22017630/61c0bac6-dcab-11e6-88bb-68fc82c9c73c.png)

It seems it hangs while it compiles the code. It never starts the publishing process 

When I remove the icon property it works fine again.

**Comment by StanislawStempin** [comment]
The logo property should contain relative path to the logo file. When saving the app.json the compiler will validate if the file exists and give you an error if it can't find it.

However, we have a bug in a seemingly unrelated place that affects this scenario. As a workaround please rename the "screenShots" property to "screenshots" and the logo should be correctly deployed.
