### ISSUE TITLE
Integration is not a valid attribute

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#800]
I feel I must be missing something? I am getting this result when I load the .al files in Visual Studio Code v 1.17.2. I have the AL Language Extension v 0.9.13932

![image](https://user-images.githubusercontent.com/32313731/31739413-03cff1d8-b40b-11e7-9b5e-40ec59be2039.png)
![image](https://user-images.githubusercontent.com/32313731/31739433-14242658-b40b-11e7-9393-46e033c63ac4.png)

I have not had luck with loading symbols, could that be contributing?

**Comment by kaspermoerch** [comment]
It should be `[IntegrationEvent(false, false)]`.

**Comment by strophanthus** [comment]
thanks!
