### ISSUE TITLE
October preview landing page on my local machine

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#803]
I deployed a couple of october previews, all of which show this behavior:
After deploying I can access the interim landing page from my computer and link to the status window. This completes as expected and I can then access the full landing page. 
But then - I guess after installing the certificate - I can no longer access the landing page  but get this error:

> `403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied`

It is just the landing page opened from my Computer that does not work, If I access the VM and run the landing page there it works. If I then copy the links to vsix file, web Client, web Services, ... to my computer  those all work. I can also download Symbols and deploy extensions from my local VS Code.

So only a nuisance, but would be nice to know how to fix.

**Comment by mrabus** [comment]
My machine is behaving like yours. Landing page creates the access denied message from within the VM but works from the outside.

**Comment by freddydk** [comment]
What browser are you using?
Could you maybe send me the URL for your landing page in an email to freddyk at microsoft dot com?
Thanks

**Comment by RafaelKoch** [comment]
Sent an email just now. 
Yet I think I might see the problem - I picked devpre102017 as a name for my machines. The landing page always redirects to https. Another VM I deployed today is named differently and its landing page does not redirect to https and seems to work just fine.
So maybe already resolved :-)

**Comment by RafaelKoch** [comment]
Resolved after uninstalling and reinstalling the certificate PLUS emtying the browser cache. Thanks to @freddydk for helping!

**Comment by freddydk** [comment]
Pretty sure that removing browser history would be enough:-)

**Comment by RafaelKoch** [comment]
Probably true. But that was what I did and so could not test if the cache alone was my problem.  :)
Thanks again for assisting!
