### ISSUE TITLE
Publish with large App

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#804]
Hi !

I build and publish my package.
But I get the error as bellow:
    
![image](https://user-images.githubusercontent.com/24407031/31761462-25b2b678-b4e2-11e7-87ab-460f245b8115.png)

This is my app file. (the app file is large because there are many report in the package)
   
![image](https://user-images.githubusercontent.com/24407031/31761522-5fec040c-b4e2-11e7-8426-5776dd9d4d52.png)

Please support so that I can publish my app.

**Comment by dennisfrostlander** [comment]
Publishing of the apps obeys the general upload limitation on the server, which is 30M by default.
You can adjust the setting ClientServicesMaxUploadSize in customsettings.config file for your instance or by using a commandlet (don't forget to restart the server afterwards).
```
Set-NAVServerConfiguration nav -KeyName ClientServicesMaxUploadSize -KeyValue 100
```

**Comment by hgnamvn** [comment]
Greate !

Thank Dennisfrostlander so much !!!
