### ISSUE TITLE
Copy Standard Report like 1306 to an extension is not possible

### ISSUE THREAD

**Issue by twityde** [Microsoft/AL#805]
For one of our extensions I need to extends some standard reports.
I exported and translated the the Report 1306 Standard Sales - Invoice with txt2al.
But some Functions that are used in the Report are marked as Internal, like CompanyInfo.GetContactUsText(...) and FormatDocument.SetSalesInvoiceLine(...).

It would be nice, if any report that is setup in an report selection table, could be translated and used in an extension.

**Comment by DanKinsella** [comment]
To add to this, it's a common request to add new fields to an existing report. A reportextension object would be very useful coupled with the existing custom layout to allow us to add fields to the data set and add/extend functions / triggers.
