### ISSUE TITLE
October Preview Issue

### ISSUE THREAD

**Issue by alanb999** [Microsoft/AL#809]
**Installation NOT complete** 
no icons on desktop, Restart VM, no change

**Please identify how to continue install/setup process**

Event Viewer 
**Application - Docker warning message**
[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]
Security
**Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network.**

**You can view the installation status by following this link.**  
6:34:11 PM Waiting for container to become ready, this will only take a few minutes
6:33:34 PM Running navdocker.azurecr.io/dynamics-nav:devpreview-finus
6:33:34 PM Locale en-US
6:33:34 PM Version 11.0.18712.0-finus
6:33:34 PM Country finus
6:33:34 PM Using image navdocker.azurecr.io/dynamics-nav:devpreview-finus
6:20:14 PM Pulling navdocker.azurecr.io/dynamics-nav:devpreview-finus (this might take a while)
6:20:06 PM Logging in to navdocker.azurecr.io
6:20:05 PM Adding Landing Page to Startup Group
6:20:05 PM Disabling Server Manager Open At Logon
6:20:05 PM Enabling Font Download in IE
6:20:04 PM Enabling File Download in IE
6:19:51 PM Launching SetupVm
6:19:02 PM Restarting computer and start Installation tasks
6:19:01 PM Downloading C:\DEMO\Install-VS2017Community.ps1
6:19:01 PM Downloading c:\demo\SetupStart.ps1
6:19:01 PM Downloading c:\demo\SetupVm.ps1
6:19:01 PM Downloading c:\demo\SetupNavContainer.ps1
6:19:01 PM Downloading c:\demo\Setupdevpreview.ps1
6:19:00 PM Downloading c:\demo\SetupDesktop.ps1
6:19:00 PM Downloading c:\demo\NavContainerHelper.psm1
6:19:00 PM Downloading c:\demo\NavContainerHelper.ps1
6:19:00 PM Getting Nav Container Helper from http://www.github.com/Microsoft/navcontainerhelper
6:19:00 PM Downloading c:\myfolder\SetupNavUsers.ps1
6:19:00 PM Turning off IE Enhanced Security Configuration
6:18:58 PM Enabling Docker API
6:18:58 PM Creating Connect.rdp
6:18:58 PM Downloading C:\inetpub\wwwroot\web.config
6:18:58 PM Downloading C:\inetpub\wwwroot\Microsoft.png
6:18:58 PM Downloading C:\inetpub\wwwroot\line.png
6:18:58 PM Downloading C:\inetpub\wwwroot\status.aspx
6:18:58 PM Downloading C:\inetpub\wwwroot\default.aspx
6:17:08 PM Installing Internet Information Server (this might take a few minutes)
6:17:08 PM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/navdeveloperpreview.json
6:17:08 PM Starting initialization

**Comment by freddydk** [comment]
Can you send me the name and credentials in an email to freddyk at microsoft dot com of this machine (or another one you create) and then I will have a look?

**Comment by DominikDitoIvosevic** [comment]
@alanb999 @freddydk Have you had any luck resolving this issue?

**Comment by alanb999** [comment]
Issue was resolved, must wait 20-30 minutes for Docker layers to be installed.
