### ISSUE TITLE
New app(.json)

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#81]
I notice you create a new guid for each app - the AppId .. makes sense ;-).

when creating a new app: do you manually have to create an app.json, or is there some kind of shortcut?
and if manual: how do you create a new guid from within vscode?  Do you use the "guid" extension?  or is there something in the al-extension that we can use for that?

**Comment by StanislawStempin** [comment]
Ctrl+Shift+B will generate a default app.json if it's missing. You just need to make sure the extension is actived by creating and opening an .al file in the folder.
![snip_20170117124957](https://cloud.githubusercontent.com/assets/23653165/22019343/7726114c-dcb3-11e6-8cf9-9c7e36511684.png)

**Comment by waldo1001** [comment]
Oh, stupid me.  Pressed that many times to load the resources/symbols :-).

thanks!
