### ISSUE TITLE
Question: Role Center -> HomeItems

### ISSUE THREAD

**Issue by JoergDZ** [Microsoft/AL#810]
Hello,
I have created a new RoleCenter page, and I have defined new Groups in the Section Area. But how can I add HomeItems to the StartPage Group in the Section Area? Has any Body a example for creating a page of type RoleCenter?

**Comment by StanislawStempin** [comment]
Have you looked at the example link to from the FAQ? 
https://github.com/Microsoft/AL/issues/669
