### ISSUE TITLE
convert-txt2al does not renumber the table to 50010 range

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#811]
I run the convert-txt2al, but it does not renumber to 50100 range

![image](https://user-images.githubusercontent.com/6551266/31814522-eede2d6e-b557-11e7-90fe-d5bfd962d650.png)

**Comment by freddydk** [comment]
the convert-txt2al is part of the navcontainerhelper, which has its own github repo here: www.github.com/microsoft/navcontainerhelper.
But as the name suggests - it converts txt 2 al - it doesn't renumber.
It does have a starting id - but that is for page and table extensions, which will become new objects.
The NavContainerHelper is an open source project which aim it is to assist partners in working with Nav Containers - it is work in progress.

**Comment by andrecavalcanti** [comment]
I'll use the tx2al tool instead. Thanks
