### ISSUE TITLE
Comparing option fields is not correct

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#812]
Hi !

I have an issues with getting option value from text. (as bellow)    
      ![image](https://user-images.githubusercontent.com/24407031/31814376-a5ef54f0-b5b3-11e7-841a-0f917acf428e.png)

You see value of **Field.Type** is **Option**. So, the result of comparison expression should be **No**
But the system show result:
      ![image](https://user-images.githubusercontent.com/24407031/31814578-4c5f6348-b5b4-11e7-8d0d-72ffb0e7d93c.png)

Please check this problem for me.

**Comment by hgnamvn** [comment]
Hi!

Please check my case.

**Comment by StanislawStempin** [comment]
We will investigate it.

**Comment by atoader** [comment]
This is fixed in the latest update. 
```
pageextension 50101 MyExtension extends "Customer Card"
{
    trigger OnOpenPage()
    var
        t: Codeunit TestingCodeUnit;
    begin
        Message('Before');
        GetOptionNo(Database::Customer, 80, '');
        Message('After');
    end;

    local procedure GetOptionNo(TableNum: Integer; FieldNumber: Integer; PValue: Text[250])
    var
        RecRef: RecordRef;
        FieldRef: FieldRef;
        TypeHelper: Codeunit 10;
        "Field": Record Field;
    begin
        RecRef.Open(TableNum);
        FieldRef := RecRef.Field(FieldNumber);
        Field.Get(RecRef.Number, FieldRef.Number);        
        Message(Format(Field.Type<>Field.Type::Option));

    end;
}
```
