### ISSUE TITLE
DotNet not recognized

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#816]
DotNet is not recognized. Will it be allowed in the future?

![image](https://user-images.githubusercontent.com/6551266/31853145-e60e4e76-b651-11e7-9d90-ed00e0c2f971.png)

**Comment by mrabus** [comment]
No, it won't but some parts of .NET will be embedded in AL. I guess your code is used to manipulate strings, that can be done in AL now.

**Comment by StanislawStempin** [comment]
Please see the FAQ: 
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions

**Comment by Gallimathias** [comment]
This is one of the most frequently asked questions. If you search, you will find a lot of issues with multiple answers from Microsoft. for example #276 #124 #475 #146 #119 and some more.....
