### ISSUE TITLE
Integration Event request for Codeunit 452

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#817]
@AlexanderYakunin Please add

    [Integration]
    LOCAL PROCEDURE OnAfterSendVANDocumentReport@3(VAR TempDocumentSendingProfile@1004 : TEMPORARY Record 60;VAR ElectronicDocumentFormat@1003 : Record 61;VAR DocumentRecRef@1002 : RecordRef;VAR ServerFileName@1001 : Text[250];VAR ClientFileName@1000 : Text[250]);
    BEGIN
    END;

to Codeunit 452 and call it from  PROCEDURE VANDocumentReport

    [Internal]
    PROCEDURE VANDocumentReport@5(HeaderDoc@1000 : Variant;TempDocumentSendingProfile@1002 : TEMPORARY Record 60);
    VAR
      ElectronicDocumentFormat@1003 : Record 61;
      RecordExportBuffer@1008 : Record 62;
      DocExchServiceMgt@1005 : Codeunit 1410;
      RecordRef@1006 : RecordRef;
      SpecificRecordRef@1007 : RecordRef;
      XMLPath@1004 : Text[250];
      ClientFileName@1001 : Text[250];
    BEGIN
      RecordRef.GETTABLE(HeaderDoc);
      IF RecordRef.FINDSET THEN
        REPEAT
          SpecificRecordRef.GET(RecordRef.RECORDID);
          SpecificRecordRef.SETRECFILTER;
          ElectronicDocumentFormat.SendElectronically(
            XMLPath,ClientFileName,SpecificRecordRef,TempDocumentSendingProfile."Electronic Format");
          **OnAfterSendVANDocumentReport(TempDocumentSendingProfile,ElectronicDocumentFormat,SpecificRecordRef,XMLPath,ClientFileName);**
          IF ElectronicDocumentFormat."Delivery Codeunit ID" = 0 THEN
            DocExchServiceMgt.SendDocument(SpecificRecordRef,XMLPath)
          ELSE BEGIN
            RecordExportBuffer.RecordID := SpecificRecordRef.RECORDID;
            RecordExportBuffer.ClientFileName := ClientFileName;
            RecordExportBuffer.ServerFilePath := XMLPath;
            CODEUNIT.RUN(ElectronicDocumentFormat."Delivery Codeunit ID",RecordExportBuffer);
          END;

        UNTIL RecordRef.NEXT = 0;
    END;

**Comment by gunnargestsson** [comment]
Perhaps this should be OnBeforeSend...

**Comment by thpeder** [comment]
We can't make this event available since it is exposing the server file path.

**Comment by gunnargestsson** [comment]
I see, and I can agree.  But that require you to change the whole process and replace the ServerFilePath variable in ReportExportBuffer with a BLOB and stop using the server file system in this whole process.
