### ISSUE TITLE
Question: event requests for 'localized' versions?

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#818]
Before actually posting my issues related to requesting additional event publishers in localised NAV databases (BE), I would like to know the procedure to be followed. 

Most event publishers requested via Github are meant to be included in the W1 version, but can we manage the same for localised databases via Github as well? Will these issues / event requests be picked up the same way by MS and included as fast in new releases (once the localized versions become available)?

**Comment by AlexanderYakunin** [comment]
Yes, you can submit requests for integration events to local objects/features same way.
