### ISSUE TITLE
startupObjectId in the launch.json

### ISSUE THREAD

**Issue by waldo1001** [microsoft/AL#82]
I love the functionality, but .. it's just half cooked, I guess.

1) would be nice to be able to work with names rather then the Id
2) would be nice to not only have to work with pages, but start (any?) other object types as well

like:

have "StartupObject": Codeunit "MyNewMethodCodeunit"

with intellisense - if possible. :-)

**Comment by esbenk** [comment]
It is not done yet. We are moving towards name-based everywhere, but it will take some time.

Currently the web-client only supports pages. The launch.json will support the client capabilities.

**Comment by waldo1001** [comment]
oh, ok, because through PowerShell, you can start any object, using the windows client.. .
is there a reason why you "only" use the webclient for these types of integration?  I'd rather expect it doesn't really matter - and I can start any object using the win client.. .

**Comment by TinaMenezes** [comment]
How can I run a table to check the values ? My windows client always says that credentials are wrong and hence it never gets connected...so I check using web client. But web client does not help to check table records..so if I want to check a table what is the other way ?

**Comment by markbrummel** [comment]
Tip: You can create a new codeunit in classic which says for example

page.run(70008000);

This will run the TowersOfHanoi page in your windows client.

I use it all the time because it saves me the hassle of adding an action somewhere on an existing page.

**Comment by kalberes** [comment]
Still long way until fully name based references. Other object types are supported by now.
