### ISSUE TITLE
Export-NAVContainerObjects not exporting with new syntax in Oct Preview

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#821]
Hi 

I used the below command to export the objects with new syntax in NAV Container Helper:
![image](https://user-images.githubusercontent.com/26792519/31881162-592cc824-b800-11e7-8cf0-b61196c1aa97.png)

But it is not exporting in that syntax see below:
![image](https://user-images.githubusercontent.com/26792519/31881236-9403c3a8-b800-11e7-8b54-dd8f5ffe5795.png)

but when the object is exported with new syntax it should be like this:
![image](https://user-images.githubusercontent.com/26792519/31881481-3fd94de2-b801-11e7-9df5-fde04660ca28.png)

Please suggest us.

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
This problem should have been fixed over the weekend, so if you deploy a new version, you should be fine.
You can also download a new navcontainerhelper.ps1 and navcontainerhelper.psm1 from www.github.com/microsoft/navcontainerhelper and overwrite the existing ones in c:\demo

**Comment by bachii1010** [comment]
HI Freddy,

Copying the scripts to my oct preview worked.
 so it is a bug in october preview.

Please make sure this will come in Nov update.

**Comment by freddydk** [comment]
In fact, if you deploy an October Preview anytime after Sunday morning you would get the new navcontainerhelper from PowerShellGet, so it is fixed for new deployments.
