### ISSUE TITLE
Control AddIn Startup Script

### ISSUE THREAD

**Issue by PeterSchade1306** [Microsoft/AL#822]
Hi,

have anyone an example for the startup script parameter usage?
If I declare the startup script parameter, nothing happens.

At the moment I throw an "AddInReady" event in my js add-in, so that I know its ready loaded before I access to it by AL (Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("AddInReady", null)).

Best regards
Peter

**Comment by dennisfrostlander** [comment]
You can test it with the following code in the file `startup.js`:
```JavaScript
alert('startup called');
```

And an add-in like this:
```JavaScript
controladdin TestAddIn
{
    StartupScript = 'startup.js';
}

page 50300 PageWithAddIn
{
    layout
    {
        area(Content)
        {
            usercontrol(ControlName; TestAddIn)
            {
                ApplicationArea = All;
            }
        }
    }
}
```

Are there any errors in the browser console when you run your add-in with startup script not working?
