### ISSUE TITLE
Dynamically Control Add-In properties

### ISSUE THREAD

**Issue by PeterSchade1306** [microsoft/AL#823]
Hello,

is it possibly to declare the control add-in properties dynamically?

For example I want to load the properties from a table. I don't find a solution for this.
If its work, I could declare different sizing properties for the same add-in which is used on different pages or could individualize the script urls.

Thank you!

**Comment by dennisfrostlander** [comment]
No, this is not possible. Was there any solution to this in the "old" way of creating control add-ins?

**Comment by PeterSchade1306** [comment]
Hi, thanks for your reply. No there was no solution in the old environment.

**Comment by RafaelKoch** [comment]
It could come in handy though

**Comment by dennisfrostlander** [comment]
Ok, thanks, marking as enhancement.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
