### ISSUE TITLE
Control AddIn events in windows client

### ISSUE THREAD

**Issue by PeterSchade1306** [Microsoft/AL#824]
Hi,

I have a problem with add-in events in the windows client.

I build a diagram add-in and if a user clicks on a shape, some information should be send to D365.
It works in the web based clients. In the windows client nothing happens.

**My JS add-in call:**
Microsoft.Dynamics.NAV.InvokeExtensibilityMethod('ReceivedClickedShapeId', ['SomeShapeId']);

**My AL trigger:**
 trigger ReceivedClickedShapeId(shapeId : Text)
                begin                    
                    Message('Diagram click received shape id: ' + shapeId);
                end;

Best regards
Peter

**Comment by dennisfrostlander** [comment]
Are you able to reproduce it in a simple test project?
Here is the sample I tried which seems to work fine in Windows client:

```JavaScript
//startup.js
var button = document.createElement("button");
button.textContent = "Hello";
button.onclick = function() {
    Microsoft.Dynamics.NAV.InvokeExtensibilityMethod('ReceivedClickedShapeId', ['SomeShapeId']);
}
document.getElementById("controlAddIn").appendChild(button);
```

```JavaScript
controladdin TestAddIn
{
    StartupScript = 'startup.js';

    event ReceivedClickedShapeId(shapeId: Text);
}

page 50300 PageWithAddIn
{
    layout
    {
        area(Content)
        {
            usercontrol(ControlName; TestAddIn)
            {
                ApplicationArea = All;

                trigger ReceivedClickedShapeId(shapeId : Text)
                begin
                    Message('Received %1', shapeId);
                end;
            }
        }
    }
}

pageextension 50300 CustomerCardAddIn extends "Customer Card"
{
    actions
    {
        addafter(Approve)
        {
            action(OpenPageWithAddIn)
            {
                ApplicationArea = All;

                trigger OnAction();
                begin
                    Page.Run(Page::PageWithAddIn);
                end;
            }
        }
    }
}
```

Open any customer card, click a new action, then click Hello button:
![image](https://user-images.githubusercontent.com/16953692/31885371-95bf852a-b7f0-11e7-9ef2-b82a68397063.png)
