### ISSUE TITLE
IntelliSense missing value when trying to define RunTrigger in Insert/Delete/Modify

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#827]
When writing calls to Insert/Delete/Modify triggers there is no value TRUE given by IntelliSense. Instead the only suggestion is call to tprocedure snippet:
![image](https://user-images.githubusercontent.com/30231314/31887608-a6b3800a-b801-11e7-83b4-f557a19b7221.png)
But it exists in suggestions when calling IntelliSense directly with Ctrl+Space.

**Comment by dennisfrostlander** [comment]
Looking into this as part of #510
