### ISSUE TITLE
FileManagement ZIP functions

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#829]
Hi all,

is there a way I can create a zip folder and add files and OutStreams to the zip folder (see Codeunit 419 File Management)?
Or is this coming up in a future release?

**Comment by jiwanovski87** [comment]
Is there any update on this? 
Will there be some "dotnet" datatypes to create zip archives in the future?

**Comment by StanislawStempin** [comment]
Since files are not allowed anymore we are looking into rewriting this functionality to be stream based. We will update this issue once we have a more precise timeline.

**Comment by JesperSchulz** [comment]
We added function AddStreamToZipStream to codeunit 419. Please refer to pull request https://github.com/Microsoft/cal-open-library/pull/41.
The update will be part of January update.

**Comment by StanislawStempin** [comment]
It is already available in Anniversary Update.
