### ISSUE TITLE
Table NAV App (2000000160) cannot be used for extensinos

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#830]
Hi all,

in APP v1 we subscribed to page 2500 and 2501 to make a hook in the actions
- Install
- Uninstall

In V2 the table "NAV App" cannot be used to trigger any code.
WHat can we do, if we want to trigger some code for install oder uninstall?

**Comment by kvaldik** [comment]
We are having the same issue. We used to subscribe to the OnAfterActionEvent on the Install action on page 2500 and 2501 and offer the user to run the assisted setup of our extension. 

Is there perhaps some other way to achieve this, an event that I'm unaware of? If not, could it make sense to add an event that fires when an extension is installed?

**Comment by StanislawStempin** [comment]
The Installation code should be executed using a codeunit of subtype = Install. You can then see the list of available trigger by typing trigger and pressing Ctrl+Space within the codeunit.
