### ISSUE TITLE
Case label cannot be decimal

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#834]
I have a case statement that takes a decimal value and returns another decimal value, something like this:
![image](https://user-images.githubusercontent.com/23434319/31919553-22b351ba-b818-11e7-82c7-f31af67fcdd3.png)

The debug console tells me "error CS0151: A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type"

So then I had to change my code to something like this:
![image](https://user-images.githubusercontent.com/23434319/31919562-30e1cc9e-b818-11e7-9c05-991b9e677be7.png)

And at least it compiles, still testing whether it still works properly. Case statements against decimal variables work in C/SIDE, why is that no longer the case (haha no pun intended)?

**Comment by DominikDitoIvosevic** [comment]
Hi @TheDenSter . I cannot repro your report on our nightly version of our compiler. It could be that we either fixed it in the meantime with some other fix or that you had a temporary hiccup from our compiler (could be some other errors in the files were causing incorrect behaviour at this point).

This is what I have and it compiles without errors:

![image](https://user-images.githubusercontent.com/6378638/32940943-68491686-cb84-11e7-8a1c-dddbe482df39.png)


Could you please try and repro again?
Thanks
