### ISSUE TITLE
Application Area Page not visible

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/AL#835]
The application area is set to basic, the same on the company information. The page is not displayed on the search. How do I do to show it up on the search?

![image](https://user-images.githubusercontent.com/6551266/31924157-4bbb6a04-b84d-11e7-8b91-34df49db2c16.png)

![image](https://user-images.githubusercontent.com/6551266/31924091-da51469a-b84c-11e7-9bf8-fb24b77658b2.png)

![image](https://user-images.githubusercontent.com/6551266/31924101-ef796f48-b84c-11e7-9427-1f9c234d4b08.png)

**Comment by esbenk** [comment]
We are currently working on the ability to have pages created in extensions show up in the search. It is not possible right now.

**Comment by qutreson** [comment]
Hi @andrecavalcanti, it is possible to add your pages and report to the search bar by using the property `UsageCategory`. This is available in the AL extension from the December update (version: 0.12.15359).

For more information on how to use it, see the online doc: [Adding Pages and Reports to Search](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-al-menusuite-functionality).

I hope this solves your issue!
