### ISSUE TITLE
Cannot deploy the ES October preview

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#838]
Hello,

I have tried to create a virtual machine for the October preview, via http://aka.ms/navdeveloperpreview
I have been able to create one for the w1 and for the us localizations.

However I cannot create one for the ES localization.
This is the log. It hangs on the last line forever (+24 hours now). I have tried twice, with the same result.

Is there any problem with de ES docker image? Am I doing something worng?

12:53:52 PM Running navdocker.azurecr.io/dynamics-nav:devpreview-fines
12:53:52 PM Locale 
12:53:52 PM Version 
12:53:52 PM Country 
12:53:52 PM Using image navdocker.azurecr.io/dynamics-nav:devpreview-fines
12:53:50 PM Pulling navdocker.azurecr.io/dynamics-nav:devpreview-fines (this might take a while)
12:53:47 PM Logging in to navdocker.azurecr.io
12:53:47 PM Adding Landing Page to Startup Group
12:53:47 PM Add Import navcontainerhelper to PowerShell profile
12:53:47 PM Disabling Server Manager Open At Logon
12:53:47 PM Enabling Font Download in IE
12:53:47 PM Enabling File Download in IE
12:52:09 PM Launching SetupVm
12:51:11 PM Restarting computer and start Installation tasks
12:50:44 PM Install Nav Container Helper from PowerShell Gallery
12:50:44 PM Downloading c:\myfolder\SetupNavUsers.ps1
12:50:44 PM Turning off IE Enhanced Security Configuration
12:50:42 PM Enabling Docker API
12:50:42 PM Creating Connect.rdp
12:50:42 PM Downloading C:\inetpub\wwwroot\web.config
12:50:42 PM Downloading C:\inetpub\wwwroot\Microsoft.png
12:50:42 PM Downloading C:\inetpub\wwwroot\line.png
12:50:41 PM Downloading C:\inetpub\wwwroot\status.aspx
12:50:41 PM Downloading C:\inetpub\wwwroot\default.aspx
12:48:24 PM Installing Internet Information Server (this might take a few minutes)
12:48:24 PM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/master/navdeveloperpreview.json
12:48:24 PM Starting initialization

**Comment by freddydk** [comment]
There is no such thing as Financials ES version of the october preview.
At this time, W1, FINUS, FINGB, FINCA and FINDK exists.
Later on we will have docker images with spanish localization as well.

**Comment by LauraNicolas** [comment]
Hello Freedy. Thanks for the reply. I will have to wait then!
