### ISSUE TITLE
Lookup, Search and FlowField on Permission / (Aggregated) Permission Set table

### ISSUE THREAD

**Issue by RHaest** [Microsoft/AL#839]
Hi,

I am using the latest docker finus preview image and am currently migrating our V1 extension to V2. So far so good.

In our extension (which is permission related) we use permission sets to link certain functionality to users. Therefore we have a simple lookup to the table Aggregated Permission Set and a flowfield to retrieve the name. Both is not allowed since these tables cannot be used for extension development. Furthermore we need to be able to perform search and find actions in the Permission table. Here we have the same issue. 

I have read that we should use the Tenant Permission and the Tenant Permission Set table, however they do, AFAIK, not contain all the necessary information for our extension. For both the lookup and the search actions it is incomplete. Therefore this is not acceptable for us. I know about the target: "Internal" setting in app.json which allows me to test it locally, however I cannot build the extension without it and I suppose I therefore cannot submit the .app file for AppSource.

Is there a workaround for this? We really need to be able to set filters on the Permission table on e.g. Object Type and Object ID. We do **_not_** need to alter the tables, we only do lookups. I've looked around here but cannot find a solution yet.

Any advice is appreciated, thanks.

Kind regards, 

Rogier

**Comment by StanislawStempin** [comment]
The tables Aggregated Permission Set, Permission Set, Permission, Tenant Permission and Tenant Permission Set have been all made available for Extension development.

Hopefully this unblocks your scenario.
