### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#840]
After successfully building the .app file, I'm getting the error: "Object reference not set to an instance of an object" in VS Code:
[2017-10-24 14:04:16.42] Sending request to http://navserver:7049/NAV/dev/apps
[2017-10-24 14:05:27.69] The request for path /NAV/dev/apps failed with code 422. Reason: 
Object reference not set to an instance of an object.

This is obviously a blocking issue for us.

When looking at the Docker console output, I'm getting this every few seconds:

TimeGenerated : 10/24/2017 2:04:42 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: Runtime
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 10/24/2017 18:04:42
                Message <ii>(NullReferenceException): <ii>Object reference not 
                set to an instance of an object.
                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.NCLCodeLoader.GetApplicati
                onObjectClrType(ObjectType objectType, Int32 objectId, Func`1 
                assemblyGetterFunc, String className)
                   at Microsoft.Dynamics.Nav.Runtime.NCLCodeLoader.GetApplicati
                onExtensionObjectClrType(ObjectType objectType, Int32 
                objectId, NavAppRuntimeMetadata runtimeAppMetadata)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.C
                ompileAndLoadClrObject()
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.g
                et_ApplicationObjectClrType()
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.F
                indMethodScopeType(String alMethodName)
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tion..ctor(INavEventSubscriber subscriber, MethodInfo 
                subscriberMethodInfo, NavAppGroup subscriberNavAppGroup, 
                NavEventSubscriptionModifiers subscriptionModifiers)
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tion.<FindDefinedEventSubscriptions>d__32.MoveNext()
                   at System.Collections.Generic.List`1.InsertRange(Int32 
                index, IEnumerable`1 collection)
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tionFactory.FindAndCreateNavEventSubscriptionsFromCodeunitIds(I
                Enumerable`1 codeunitIds, NavAppGroup appGroup, 
                NavEventSubscriptionModifiers subscriptionModifiers)
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tionFactory.FindAndCreateBaseSubscriptionInstances(NavEventSubs
                criptionModifiers subscriptionModifiers)
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tionMetadata.RebindAllEvents()
                   at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscrip
                tionMetadata.RebindEventSubscriptionsIfNeeded(Func`1 staleFunc)
                   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
                   at Microsoft.Dynamics.Nav.Runtime.NavDatabase.RaiseTypeSpeci
                ficTrackingEvent(EventHandler`1 eventHandler, List`1 
                trackingObjects, ObjectTrackingChangeType changeType)
                   at Microsoft.Dynamics.Nav.Runtime.NavDatabase.HandleTracking
                Event(List`1 trackingObjects)
                   at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.
                HandleTrackingEvent()
                   at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.
                TimerHandleTrackingEvent()
                   at Microsoft.Dynamics.Nav.Runtime.NavDatabaseChangeListener.
                TimerHandler(Object param)
                   at Microsoft.Dynamics.Nav.Runtime.NonReEntrantTimerWrapper.T
                imerDelegateWrapper(Object state)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.NonReEntrantTimerWrapper.T
                imerDelegateWrapper(Object state)
                   at 
                System.Threading.ExecutionContext.RunInternal(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                   at System.Threading.TimerQueueTimer.CallCallback()
                   at System.Threading.TimerQueueTimer.Fire()
                   at System.Threading.TimerQueue.FireNextTimers()
                
                </ii></ii>
                ProcessId: 4124
                Tag: 000004I
                ThreadId: 13
                CounterInformation:

**Comment by jcooper01** [comment]
Just as a follow up, our base extension deployed successfully, In addition, another (smaller) app that uses the base extension also deployed successfully.

**Comment by dennisfrostlander** [comment]
@HunterFeltman-MSFT @cmrudolph-msft Do you have any hints on what could be wrong here with event subscriptions?

**Comment by freddydk** [comment]
Could you share what docker version you are running on?
On the dump above it looks like some event subscription hook fails.
Since you have other apps publishing successfully, it might be a good idea to try to identify which event subscription is causing the error (if this is the cause)

**Comment by jcooper01** [comment]
When I updated the base extension dependency version in my app.json to match the actual version of the base app (rather than the minimum version), it deployed successfully. Is this just a red herring? When I change it back, it still deploys correctly.

**Comment by thpeder** [comment]
We recently found a bug in how we would cache different versions of an extension which would show up if you have other extensions depending on that. 
It sounds like that might be your problem and hopefully you shouldn't see this again as soon as the holiday update is released.
