### ISSUE TITLE
'The record 'NAV App' does not match the event parameter record 'NAV App'.' 

### ISSUE THREAD

**Issue by MortenRa** [Microsoft/AL#854]
Getting this error in the October Release 

[EventSubscriber(ObjectType::Page, 2500, 'OnOpenPageEvent', '', false, false)]
  local procedure ShowNotificationOnOpenPageExtensionsManagement(var Rec : Record "NAV App");
  begin
    OnOpenRoleCenter;
  end;

**Comment by bachii1010** [comment]
Hi,

You have to remove the NAV app parameter from the code as NAV app is not supported in extension development.

**Comment by MortenRa** [comment]
But my target is Interal and that should work.

**Comment by kalberes** [comment]
I suppose you got the above error when publishing. Even though you set the compilation scope as internal in VsCode, you are still "external" on the server where we recompile the published package

**Comment by MortenRa** [comment]
Not published yet, get the error after downloading symbols.
