### ISSUE TITLE
Generic Chart - not possible use tables from extension

### ISSUE THREAD

**Issue by rslovak** [Microsoft/AL#856]
Is not possible to create chart with table from extension. I can select the table from list:
![image](https://user-images.githubusercontent.com/32643537/32100454-171c604a-bb14-11e7-8259-eea8d6e2d03a.png)

After selection:
![image](https://user-images.githubusercontent.com/32643537/32100481-2f8ce32a-bb14-11e7-983c-c84681077450.png)

**Comment by thpeder** [comment]
Hi @rslovak,
Would you mind giving it a try again, since it seems to be working.

**Comment by rslovak** [comment]
Yes, it’s seems ok. You can close this issue.

Roman

**Comment by linasostreika** [comment]
This problem still exists. I can not choose an extension table as data source in generic charts. 
![table](https://user-images.githubusercontent.com/39334704/40716156-aa2cbdc6-6410-11e8-8b61-d00f15b33e39.PNG)

**Comment by thpeder** [comment]
Hi @linasostreika,
What version are you running?
Please have a look at the release schedule: [AL Developer Previews, multiple releases, and GitHub](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)

**Comment by linasostreika** [comment]
hi @thpeder I am using NAV 2018 CU05.
