### ISSUE TITLE
IntelliSense/Snippets Issue

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#86]
When we try to create new triggers using IntelliSense and snippets
it will be
![snippet 1](https://cloud.githubusercontent.com/assets/23735402/22098961/42ac5550-de4f-11e6-91f4-ac44bc64c711.png)

when we type Onbefore or so and press tab
![snippet 2](https://cloud.githubusercontent.com/assets/23735402/22098996/6c9ae69c-de4f-11e6-81e6-0834f29ccf2a.png)
Its adding (); at the end and we already have (Parameters);
we have to manually delete them.

Can it be corrected to add only OnBeforeValidate text and not ();

**Comment by kalberes** [comment]
Trigger intellisense is suggesting the correct signature. So that should stay. Also completion should not delete user code. (like deleting (Parameters) which is just a hint and should be deleted anyway). I am not sure there is much we can do, maybe change the snippet. We will look into it.

**Comment by pmohanakrishna** [comment]
Yes, snippet should not add ();

**Comment by StanislawStempin** [comment]
The snippets have been cleaned up at some point therefore closing this suggestion.
