### ISSUE TITLE
List type page shown as a Card type page which opens on clicking an action.

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#87]
Hi all,
I have created a list type page 'SamplingQuantityPage'
![image](https://cloud.githubusercontent.com/assets/24891208/22135096/0c18a3f6-def2-11e6-9902-2dd8e2b9b203.png)

I have created an action which on clicking opens up this page.
![image](https://cloud.githubusercontent.com/assets/24891208/22135706/ec5b7256-def5-11e6-9f09-d43ca4a35129.png)

**But on clicking this action, the page opens up as a card type page instead of a list type even though I have declared it as a list type page.**
![image](https://cloud.githubusercontent.com/assets/24891208/22135695/e2323116-def5-11e6-8f73-5fe98c7ca2d4.png)

Kindly give a solution. Thanks in advance.

**Comment by pmohanakrishna** [comment]
Please check this issue
https://github.com/Microsoft/AL/issues/72
we need to add repeater also.

**Comment by TinaMenezes** [comment]
Hi @pmohanakrishna,
Oh Yes! Thank you. Its solved.
