### ISSUE TITLE
Refactor Request - PAG344.InsertIntoDocEntry

### ISSUE THREAD

**Issue by jwikman** [Microsoft/AL#870]
Please refactor Page 344 by modifying procedure InsertIntoDocEntry.
1. Make InsertIntoDocEntry global
2. Add parameter with the source record of the page "VAR DocumentEntry@1004 : TEMPORARY Record 265.

New procedure signature:
```
PROCEDURE InsertIntoDocEntry@3(VAR DocumentEntry@1004 : TEMPORARY Record 265;DocTableID@1000 : Integer;DocType@1003 : Option;DocTableName@1001 : Text[1024];DocNoOfRecords@1002 : Integer)
```
Then add Rec as the new parameter in every call to  InsertIntoDocEntry.
In the InsertIntoDocEntry procedure the record should be inserted in the parameter variable instead of Rec.

```
    PROCEDURE InsertIntoDocEntry@3(VAR DocumentEntry@1004 : TEMPORARY Record 265;DocTableID@1000 : Integer;DocType@1003 : Option;DocTableName@1001 : Text[1024];DocNoOfRecords@1002 : Integer);
    BEGIN
      WITH DocumentEntry DO BEGIN
        IF DocNoOfRecords = 0 THEN
          EXIT;
        INIT;
        "Entry No." := "Entry No." + 1;
        "Table ID" := DocTableID;
        "Document Type" := DocType;
        "Table Name" := COPYSTR(DocTableName,1,MAXSTRLEN("Table Name"));
        "No. of Records" := DocNoOfRecords;
        INSERT;
      END;
    END;
```

In this way we don't need to duplicate the code inside InsertIntoDocEntry when we are subscribing to the event OnAfterNavigateFindRecords

Delta file built on CTP16 W1:
[PAG344.txt](https://github.com/Microsoft/AL/files/1421944/PAG344.txt)

**Comment by JesperSchulz** [comment]
I assume you also want InsertIntoDocEntry to be [External]?

**Comment by jwikman** [comment]
Aah, yes!

I have to get used to the fact that Global (not Local)  is not enough anymore, ofcourse we need it as [External] as well.

Thanks for asking!

**Comment by JesperSchulz** [comment]
All done :) The check-in should be processed before EOD. Thanks for your clean code suggestion - made my job very easy!

**Comment by jwikman** [comment]
Great Jesper!

Then you might check out all other of my event requests now? They are all as clean as this, so you'll be able to fix them all before the holidays ;-)
