### ISSUE TITLE
Debug install code

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#871]
Is it possible to debug the code that is executed on install or upgrade-time?

I have an error, but would like to investigate..
![image](https://user-images.githubusercontent.com/12088142/32104718-f2923832-bb25-11e7-9735-a71a2458d935.png)

![image](https://user-images.githubusercontent.com/12088142/32104714-ebb9528e-bb25-11e7-882c-18c52e58647b.png)

**Comment by kalberes** [comment]
Don't you have any hints on what went wrong in the Application and Services Logs\Microsoft\DynamicsNAV eventgoup?
Publishing is pure server code.
