### ISSUE TITLE
Page part drop down off screen

### ISSUE THREAD

**Issue by TaylerPino** [Microsoft/AL#874]
On a custom card, I have a page part at the bottom of the card. When using the drop down, it drops below the task bar. This only occurs when the table is empty, but it prevents usage of the 'new' button. It happens in both Edge and Chrome.

![pagepartbug](https://user-images.githubusercontent.com/19294127/32122730-60a185d6-bb2f-11e7-9c6b-ca992300286e.PNG)

**Comment by HunterFeltman-MSFT** [comment]
Thanks for finding this! We'll start looking into it
