### ISSUE TITLE
Txt2AL: Action Groups do not nest properly after conversion

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#875]
The indentation levels on action items are lost during the conversion. Therefore, ActionGroups end up empty, and Actions never end up in groups.

**Comment by DominikDitoIvosevic** [comment]
I'm not allowed to accept your code I'm afraid. Could you explain the hierarchy before/after? Just a short example

**Comment by jcooper01** [comment]
Sure. We have modified many NAV pages to add actions and fields. Let's take the Posted Sales Invoice page (ID 132) as an example. We added a large number of actions, so we want them separated into groups for better usability. We have a top-level ActionGroup A (Indentation Level 1 in the TXT export/delta), and then several ActionGroups B1, B2, and B3 below that, which have an Indentation Level of 2 in the TXT export/delta. The actual Actions C1, C2, and C3 have an Indentation Level of 3. The visual result is a page with an action group that contains drop-down buttons that contain the actions. After AL conversion, everything is flattened. We get an empty ActionGroup A, and empty ActionGroup B1, followed by Action C1. Then, we get an empty ActionGroup B2, followed by Action C2. The visual result loses all grouping because the empty ActionGroups aren't displayed, so all that are left are a bunch of Actions without any organization.

The same is true for fields. We added a Group to the same page, which has an Indentation Level of 1 in the TXT/delta file. All the Fields have an Indentation Level of 2 and should appear in the Group (FastTab). The converted AL file flattens them, so the fields are actually added to the previous FastTab, and our new FastTab is lost.

Let me know if you need more information. This is an urgent issue for us.

**Comment by DominikDitoIvosevic** [comment]
Ok. I'm prioritizing this. I'll try to get it fixed asap

**Comment by jcooper01** [comment]
Thanks. Related to this is that there doesn't seem to be a way to add actions/fields after a group. For example, the TXT/delta says "InsertAfter=Area(Control 75)". Area is the last field in the Fireign Trade FastTab, and we are trying to add a new FastTab after Foreign Trade. However, in the AL file, that gets turned into addafter(Area), and the controls actual end up inside the Foreign Trade FastTab. Hopefully however you fix this will address that issue as well.

I'm happy to test your fix as soon as it's available.

**Comment by DominikDitoIvosevic** [comment]
Honestly, for me it's a big problem just finding a small repro for my unit test so that I can start debugging from there.

I have:

    OBJECT Modification MyPage(Page 5919)
    {
      OBJECT-PROPERTIES
      {
        Date=;
        Time=;
        Version List=;
      }
      PROPERTIES
      {
        Target=MyPage(Page 5919);
        TargetPageType=Card;
      }
      CHANGES
      {
        { Insertion         ;InsertAfter=MyControl(Control 2);
                             ChangedElements=ControlCollection
                             {
                               { 1903305101;1;Group  ;
                                           Name=MyGroupName }

                             }
                              }
        { Insertion         ;InsertAfter=MyGroupName(Control 1903305101);
                             ChangedElements=ControlCollection
                             {
                               { 1101100003;2;Field  ;
                                           Name=MyFieldName;
                                           SourceExpr=MySecondField }

                             }
                              }
      }
      CODE
      {

        BEGIN
        END.
      }
    }

and it gets converted to

    pageextension 70000001 pageextension70000001 extends MyPage 
    {
      layout
      {
        addafter(MyControl)
        {
          group(MyGroupName)
          {
          }
        }
        addafter(MyGroupName)
        {
          field(MyFieldName;MySecondField)
          {
          }
        }
      }
    }

How does this differ from your delta file?
This one compiles correctly

**Comment by jcooper01** [comment]
[test.txt](https://github.com/Microsoft/AL/files/1427857/test.txt)
Here's an example.

**Comment by DominikDitoIvosevic** [comment]
Thanks. I'm on it!

**Comment by jcooper01** [comment]
Were you able to resolve this? If so, would it be possible to get a new Docker build via Collaborate?

**Comment by DominikDitoIvosevic** [comment]
Hi. This should be fixed now. We needed more time to get the fix intergrated. Could you verify now? I think it should be in the newest docker image since our fix got integrated on Friday

**Comment by jcooper01** [comment]
Can you push the new docker image to my Collaborate account?

**Comment by jcooper01** [comment]
So the controls nest properly now, but they are still added in the wrong place. See these screenshots for examples:
What we get after AL conversion:
![image](https://user-images.githubusercontent.com/19348055/32514334-b2192c18-c3ca-11e7-864b-4734e0c261de.png)
![image](https://user-images.githubusercontent.com/19348055/32514349-bbfac4d0-c3ca-11e7-9ab1-15593a277615.png)

What it should look like:
![image](https://user-images.githubusercontent.com/19348055/32514374-d2003210-c3ca-11e7-9b9c-04745cfb26c6.png)
![image](https://user-images.githubusercontent.com/19348055/32514390-db89079e-c3ca-11e7-801a-90d10b8303f6.png)

Here's a snippet from the delta file:
    { Insertion         ;InsertAfter="Pla&nning"(Action 121);
                         ChangedElements=ActionCollection
                         {
                           { 70000500;1   ;ActionGroup;
                                           Name=P&ayment;
                                           CaptionML=ENU=P&ayment;
                                           Image=Sales }
.
.
.
.

As you can see, it's supposed to be added after the Planning action on the Sales Order page. However, in AL, it becomes:
    addafter("Pla&nning")
    {
      group("P&ayment")
      {
        Caption = 'P&ayment';
        Image = Sales;

Without the "1" like we have in the delta file, AL doesn't know that this group should be at the level just under the ActionContainer. Instead, it ends up inside the Plan ActionGroup.

The same thing happens for fields. We add a subpage to the Sales Order page, and it ends up inside the Prepayment FastTab instead of in its own FastTab below it. See example:
![image](https://user-images.githubusercontent.com/19348055/32514750-f31640a6-c3cb-11e7-84b9-a2fc5befb8e2.png)

vs.

![image](https://user-images.githubusercontent.com/19348055/32514777-06cc34de-c3cc-11e7-820b-4beebb797908.png)


Thoughts?

**Comment by DominikDitoIvosevic** [comment]
I tried recreating your scenario. From what I understand. You are trying to addafter "Planning" but not at the level where "Planning" is but on a level above. There is currently no way to describe this in V2 extensions and I don't think we should even support that. Why don't you add after "Plan" which is on the level on which you want to add the group at? What was the motivation for adding after "Planning" instead of "Plan" (I'm trying to understand the motivation so that we know how to develop this in the future)?

**Comment by StanislawStempin** [comment]
@DominikDitoIvosevic  - that is what the original code did. It added at the same level as "Plan". The fact that it was after "Planning" in terms of txt file layout doesn't mean it should be at the same indentation level after conversion.

**Comment by jcooper01** [comment]
@DominikDitoIvosevic, @StanislawStempin is correct. I'm not choosing to add after "Planning" - that's what Compare-NAVApplicationObject generates when it creates the delta file. This is just one example, but it comes up all over the place with actions and page controls in our apps. Pretty much everything ends up in the wrong spot after conversion if we are trying to add actions or controls to the top level of the container. I'd really like to get this fixed, as it is occurring dozens of times across our apps. It's a blocking issue for us. Either Compare-NAVApplicationObject should add the controls and actions after the previous element at the same indentation level instead of just the previous element (if that's how AL wants to see it) or txt2al should fix the addafter statement so that the indentation level is respected.

**Comment by DominikDitoIvosevic** [comment]
You have valid points Jonathan. I'll make this work

**Comment by DominikDitoIvosevic** [comment]
@jcooper01 A new change has been made with generating delta files. When using the Compare-NAVApplicationObject you need to provide a -ExportToNewSyntax flag (if you don't, txt2al will reject it if you provided any page extensions). This will enable providing enough information to txt2al to be able to cover these cases. 

Could you try and see if we have unblocked you?

**Comment by jcooper01** [comment]
What build has this update?

**Comment by DominikDitoIvosevic** [comment]
19494

**Comment by jcooper01** [comment]
Is that build available in Docker?

**Comment by jcooper01** [comment]
Looks like it isn’t. Could you make it available through Collaborate for me? I can test today.

**Comment by DominikDitoIvosevic** [comment]
I'm not sure whats the process for making it available as I'm not a part of it. Try talking to Freddy.

**Comment by jcooper01** [comment]
Looks like there is an issue with table object comparisons:
WARNING: Table=3 Element Field does not support property Level or the value is non numeric
The result is that page objects are excluded from the delta.

**Comment by DominikDitoIvosevic** [comment]
@jcooper01 could you please describe the issue in more detail? I do not understand the exact situation you are describing. Do you have a repro for this or at least a code snippet?
