### ISSUE TITLE
Txt2AL: Field Groups do not nest properly after conversion

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#877]
Similar to #875, fields on a pageextension lose their nesting during the conversion, resulting in a page that loses its FastTabs for the added fields, as empty groups are created.

**Comment by DominikDitoIvosevic** [comment]
I'm working on a bug related to this. Could you please paste me the actual result vs expected? It would help a lot!

**Comment by jcooper01** [comment]
Yes - can I send it to you privately somehow?
