### ISSUE TITLE
Factbox subpage link with provider id

### ISSUE THREAD

**Issue by marcellmark** [Microsoft/AL#88]
Hello,
I tried to extend the Sales Order page with a factbox that shows information based on the current record highlighted on the Sales order lines, but it doesn't show any records.

> pageextension XXXXXXXX SalesOrderExtension extends "Sales Order"
{
    layout 
    {
        addlast(FactBoxes)
        {
            part("Item info"; "Test Item Factbox" ) 
            {
                ProviderId = 58;
                SubPageLink = "Item No."=FIELD("No.");   
            }
        }   
    }
}

Thanks in advance for your help!

**Comment by StanislawStempin** [comment]
This is a bug with the ProviderId property.  We will look into it

**Comment by marcellmark** [comment]
Great, Thanks!

**Comment by dennisfrostlander** [comment]
The bug has been fixed, but unfortunately it did not make it into the March update, so the fix will be available in April.
Just a hint. The ProviderId property has been renamed to Provider and it now references the parts by name rather than by Id.
So the new syntax will be:
```AL
part("Item info"; "Test Item Factbox" )
{
    Provider = "SalesLines";
    SubPageLink = "No."=FIELD("No.");
}
```
