### ISSUE TITLE
AL Package Manager

### ISSUE THREAD

**Issue by ghost** [microsoft/AL#880]
Most other programming languages have package managers that allow you do re-use other peoples brainwaves and keep them updated if you want to or hack them into what you need them to be.

I found myself copying objects from Arend Jan to consume Web Services and I noticed Dmitry did that too.

Are you planning on delivering something to manage this? Like npm or nuget? Or is this something you expect the community to pick up?

**Comment by Gallimathias** [comment]
I'm completely of the same opinion. 

I would like to stand up for Nuget even if we have to check out we want to handle it for AL. On the other hand it works with chocolatey ;)

**Comment by StanislawStempin** [comment]
It is something we are considering longer-term. Thanks for the suggestions.

**Comment by deadmouse** [comment]
Has this had any progress?

**Comment by thpeder** [comment]
Hi! Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
