### ISSUE TITLE
Txt2AL: Small Conversion Issues

### ISSUE THREAD

**Issue by Walwode** [Microsoft/AL#885]
ok, i'm updating this thread with the Txt2AL converter issues i'm finding, to avoid multiple threads.

DateFormula InitValues
```
Converter: InitValue = -7D; [ParseNumericPropertyError]
Correct: InitValue = '-7D';
```

Variable for page "Fields":
```
Converter: MyPageVariable: Page Fields; [Application Object Keyword]
Correct: MyPageVariable: Page "Fields";
```

**Comment by StanislawStempin** [comment]
Thanks, @Skordas. In general please open a new issue for each problem. We track each issue as an individual bug and if you update once the fixing is in progress the fix might not include your latest updates.

**Comment by Skordas** [comment]
Variable for Table "Key":
```
Converter: MyKeyRecord: Record Key; [Application Object Keyword]
Correct: MyKeyRecord: Record "Key";
```
