### ISSUE TITLE
begin statement autocomplete

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#886]
The autocomplete when you type 'begin' is nice (type 'begin' and 'end;' is automatically generated and indents appropriately when you press enter)

This also happens if you type 'begin' in a comment line. It's nothing major but it would be nice if autocomplete checked if it was in a comment to avoid having to delete the 'end;' every time you type 'begin' in a comment.

**Comment by StanislawStempin** [comment]
This a behavior controller by VS Code. I logged an issue on their issue tracker: microsoft/vscode#38110

**Comment by StanislawStempin** [comment]
It is possible to control this behavior per language. We will fix it.

**Comment by strophanthus** [comment]
Thanks!

**Comment by qutreson** [comment]
There is actually a bug in VS Code related to auto closing pairs, I opened a new issue for them: [microsoft/vscode#39234](https://github.com/Microsoft/vscode/issues/39234)

**Comment by qutreson** [comment]
VS Code fixed the related issue and we made the necessary changes in order to make it work. Note that, for now, their fix is only available in VS Code Insider. Once their fix makes it into VS Code, you won't have to remove "end" anymore when writing "begin" in comments :)
