### ISSUE TITLE
Configuring VS Code on Local servers with Tenerife CTP16 for Extensions 2.0

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#887]
I am trying to set up the environment for publishing Extensions 2.0 from visual studio code on local servers but with no success to connect from VS Code to NAV. 

Tenerife service (CTP16 build 18843 for NA) is setup with enabled development endpoint (port 7049), and I can open Win client on address: 
``
devnav20181:7046/dynamicsnavdemo
``

Visual Studio code is using extension for AL Language 0.10.13928 (October Update).

When I try to download symbols I get the following message:
````
[2017-11-02 08:38:34.03] Using reference symbols cache path: c:\Users\idordevic\Documents\AL\ALProject2\.alpackages
[2017-11-02 08:38:34.03] Sending request to http://devnav20181:7049/dynamicsnavdemo/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0
[2017-11-02 08:38:34.03] Sending request to http://devnav20181:7049/dynamicsnavdemo/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-11-02 08:38:34.05] The request for path /dynamicsnavdemo/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2017-11-02 08:38:34.06] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application locale and version are specified in the app.json file.
````
This is mine **launch.json** file:
````
"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "launch",
			"name": "devnav20181",
			"server": "http://devnav20181",
			"serverInstance": "dynamicsnavdemo",
			"tenant": "",
			"authentication": "Windows",
			"startupObjectId": 22
		}
	]
````
And **app.json**:
````
{
  "id": "cc3dc56d-6f23-4d98-a2c5-1f61b2cefaaa",
  "name": "ALProject2",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": {
    "version": "11.0.0.0",
    "locale": "US"
  },
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}
````

**Comment by StanislawStempin** [comment]
You are using outdated AL Language extension. CTP16 build is newer than October Update so you need to use the AL Language from the same build. There was another issue for this recently with instructions how to get the right .vsix file.

**Comment by ivandjordjevic** [comment]
I see there are #878 and #802. If I try with docker to download devpreview image in order to get new .vsix file with:
````
docker run -m 3G -e ACCEPT_EULA=Y -e USESSL=N -e navdocker.azurecr.io/dynamics-nav:devpreview-finus
````
I still get the same version of al extension **0.10.13928**:
````
http://f91d59709e0c:8080/al-0.10.13928.vsix
````
Might be that I have to first delete existing image locally and download new one from navdocker.azurecr.io server

**Comment by StanislawStempin** [comment]
Think of AL Language as a client. If you're using server from CTP16 you should be using a client from CTP16. Therefore you should use vsix from docker image from CTP16, not from October Update.

**Comment by ivandjordjevic** [comment]
Understand, thanks. Will try that. It'd be easier if AL Language extension is then shipped with Tenerife CTP DVD.

**Comment by ivandjordjevic** [comment]
That was it. Work with AL Extension version 14380:

al-0.11.14380.vsix

Thanks!
