### ISSUE TITLE
Symbols used in VS code throws error

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#889]
Hi,
I've installed Development Preview - October Update which installs successfully. 
It ask me to download Symbols. whenever I download symbols it throws error 'cannot connect to server'
![1](https://user-images.githubusercontent.com/24870777/32368886-4420e3ec-c0ad-11e7-8b83-5c58cbc40a11.png)

How to move about?

**Comment by bachii1010** [comment]
Hi 

Can you let me know what is the Server you have given in Launch.json.

or may be can you show the lanunc.json

**Comment by Skordas** [comment]
are you using local installation of NAV, or Docker? (e.g. https://github.com/Microsoft/AL/issues/878)

**Comment by dkatson** [comment]
@Chris-Dsilva if you use http://aka.ms/navdeveloperpreview then change your settings in launch.json file according to landing page parameters.

**Comment by Chris-Dsilva** [comment]
Hi,
Thanks for your help! I made the necessary chnages in the launch.json and app.json file now while downloading symbols it prompts me for user name and password. I thought so its my VM credentials but its not. any help here?

**Comment by bachii1010** [comment]
hi 
here you should use user id - admin and paswword same as your VM password

**Comment by Chris-Dsilva** [comment]
Hi I tried using admin too its still the same

**Comment by bachii1010** [comment]
HI

can you try sa instead of admin as userid

**Comment by yrest** [comment]
@Chris-Dsilva , have you checked https://github.com/Microsoft/AL/issues/597 ? The user is defined when provisioning VM, In above link it is vmadmin

**Comment by StanislawStempin** [comment]
@bachii1010 is right,  the username **admin** should work. 

Note that when you focus out of the password entry window it will reset the process (that's the VS Code input field behavior). You need to make sure you are typing both the username and password without leaving VS Code

**Comment by Chris-Dsilva** [comment]
Hi,
Still facing the same issue, VS code ask me for the credentials. 
even after entering username as admin and password it still prompts for credentials

**Comment by TinaMenezes** [comment]
Hi,
I am also facing the same issue while entering username as 'admin' to download symbols. An error comes up  and the symbols are not downloaded. Error is as below:
![image](https://user-images.githubusercontent.com/24891208/32884992-261fa25e-cae2-11e7-9240-461de143b59c.png)
Kindly give a solution.
Thanks.

**Comment by StanislawStempin** [comment]
Please make sure to closely follow the steps described in the getting started documentation as well as in the recent Nav Developer Preview blog posts detailing how to work with VMs based on the docker image.

From your error message it looks like you didn't replace the placeholders in launch.json with the actual name and azure region of your VM.
