### ISSUE TITLE
Temporary Tables

### ISSUE THREAD

**Issue by eknraw** [Microsoft/AL#89]
Is it possible to define a record as temporary? 

I've tried: 

var
 TempSalesHeader : TEMPORARY Record "Sales Header";

**Comment by StanislawStempin** [comment]
It is possible. In the new syntax the temporary keyword goes to the end of the type declaration:
```
var
 TempSalesHeader : record "Sales Header" temporary;
```

**Comment by eknraw** [comment]
Ah, yes, that works.  thanks!
