### ISSUE TITLE
Debugging Error: "Sorry that didnt work"

### ISSUE THREAD

**Issue by jaspreet997** [Microsoft/AL#893]
When i try to debug code by Pressing F5, the package is build successfuly and the browser opens up, but i get the following error. Is this a Config file error where am missing some key?
Details:
1. Using CTP16 locally with proper AL language extension
2. Symbols downloaded and everything else is working just fine.

![image](https://user-images.githubusercontent.com/28197115/32414423-367af2d2-c24c-11e7-9d76-79286e22b0f8.png)

**Comment by epernst** [comment]
It's an error in your code. Happens to me all the time! ;) Turn on the debugger as close to the potential error and find your error in the code.

**Comment by Skordas** [comment]
i do have the same issue. If i use my local installed CTP16 in launch.app and hit F5, i receive the error mentioned by jaspreet. Removing the url parameter "debuggingcontext" does at least start the webclient (and my app is working), but ofc i can't debug anymore.

Using the docker version of CTP16 makes debugging possible. But it takes several tries to start the webclient (very often i receive timeouts). Also, i have to run docker-nav without SSL, else i can't deploy my app. How to install the SSL certificate that is provided from the docker run? (double click, install to local machine and reboot was not enough, though).

**Comment by jaspreet997** [comment]
@Skordas I suspect there is a flag that needs to be added in config file to enable debugging. If possible ,Can you compare the config file between your local installation and the one on Docker
@epernst The code is running fine when I press Ctrl+F5. the app is built and I can test it successfully. Its a small app so I can confirm everything is working fine and no errors are reported anywhere

**Comment by StanislawStempin** [comment]
To enable debugging the NetFx40_LegacySecurityPolicy setting in the Microsoft.Dynamics.Nav.Server.exe.config file must be set to false. This requires a server restart.

More information available here: https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-debugging
