### ISSUE TITLE
TXT2AL: Skips second caption on Pages, Queries, Reports and XMLPorts

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#894]
In the October preview, when converting Pages, Queries, Reports and XMLPorts with TXT2AL, then it only includes the first CaptionML. Running it with the DK version (with ENU and DAN), then only CaptionML=DAN remains.

It works fine for tables!

**Comment by DominikDitoIvosevic** [comment]
Hi @epernst 
I cannot get a repro for your bug. Here are my before and after conversion and I see that both captions are correctly included.
Could you possibly create a repro for us?


            var source = @"OBJECT Page 1051 MyNewPage
{
  OBJECT-PROPERTIES
  {
    Date=20171023D;
    Time=120000T;
    Version List=NAVW111.0;
  }
  PROPERTIES
  {
    CaptionML=ENU=Additional Fee Visualization;
    SourceTable=MyTable;
  }
  CONTROLS
  {
    { 1000;    ;Container ;
                ContainerType=ContentArea;
                Name=Control1000 }

    { 1006;1   ;Group     ;
                Name=Graph;
                CaptionML=ENU=Graph;
                GroupType=Group }

    { 1002;2   ;Field     ;
                Name=BusinessChart;
                CaptionML=ENU=BusinessChart,DAN=Poslovni graf }

  }
  CODE
  {
    BEGIN
    END.
  }
}

";

            var expected = @"page 1051 MyNewPage
{
  // version NAVW111.0

  Caption = 'Additional Fee Visualization';
  SourceTable = MyTable;

  layout
  {
    area(content)
    {
      group(Graph)
      {
        Caption = 'Graph';
        field(BusinessChart;'')
        {
          CaptionML = ENU='BusinessChart,DAN=Poslovni graf';
        }
      }
    }
  }

  actions
  {
  }
}

";

**Comment by epernst** [comment]
I looked into this again, and tried to recreate it. And it seems actually to be quite different problem.
The objects I exported came from FinancialsDK. And the objects I exported were standard objects. Somehow the ENU label is empty on all Pages, Queries, Reports and XMLPorts in the Danish Financials.

**Comment by DominikDitoIvosevic** [comment]
If I remember correctly, you need to make sure you have the correct language of the product installed to get it's captions. I think it was a planned decision. However, I have no idea whether English should be there or not. Are you sure that any language besides Danish is supposed to be provided?

**Comment by epernst** [comment]
Well the ENU caption should always be there by default. No matter what other languages there might be.
Nothing to do with the license - actually using a US license so if "by design" then it should take the ENU.
 
CTP16 of the Danish CronusDK database does have the ENU captions there, so don't know what's going on with FinancialsDK. My guess is that it's part of unfinished work to move Danish language into an extension? Or something else.

**Comment by StanislawStempin** [comment]
Does the problem still occur on NAV 2018 or later?

**Comment by DominikDitoIvosevic** [comment]
Hi @epernst . Could you please tell us if you are still experiencing these problems on Nav 2018 or later?

**Comment by epernst** [comment]
Yes the problem is still there. Check for instance page 1 (FINDK) from the page designer. While it has both ENU and DAN captions for all fields and controls on the page, then it only has a DAN page caption. There is no ENU caption on the pages.
