### ISSUE TITLE
finsql Command=ExportToNewSyntax: fails with error "The length of the source exceeds the size of the destination buffer"

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#896]
This happens on exporting a Page.
As far as I could track it down the reason seems to be that the Page has a Factbox Page Part with a long SubPageLink (944 characters, if I put the whole SubPageLink into one line).

**Comment by kalberes** [comment]
Is a standard exportobjects command for this page passing your scenario?

**Comment by janhofmann24** [comment]
Yes, the standard exportobjects command for the same page works.

**Comment by kalberes** [comment]
Ok. Looks like with quoting identifiers we are getting out of the allocated length for the output memory . 
We may not fix this one.
Can the SubpageLink be refactored to be shorter?

**Comment by janhofmann24** [comment]
The SubPageLink is so long, because it transports a bunch of flowfilters to the Factbox. 
I don't think it can be shortened without functional impact. 
Since I know which two pages this are, I can deal with it now. 

However, it was very hard to identify which Object is the troublemaker. I had to first export them by Object Type to find out, that my problem is with Pages, then slicing the Pages into smaller and smaller packages to narrow it down. 
The error message doesn't give any indication which of the potentially thousands of objects is the troublemaker. 
Even if the main problem is not to be fixed, maybe at least that can be fixed?

Thanks
