### ISSUE TITLE
String handling with .Net

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#90]
I know .Net is not available (yet?).  But I'd like to do some simple string handling, like:
- System.String
- System.Array
- System.IO.StringReader

Is .Net on the agenda already?
Do you have any idea when something simple like this would be possible?

**Comment by stuartglasson** [comment]
It's on the agenda and it's high on the priority list of .NET replacement functions we want to do.
As with our other .NET wrappers, we're unlikely to cover all properties and methods from the types.  We'll implement as much as we can to ensure you get core use, but it would be kind of you (and others) to illustrate how you use the string/array/string reader types to ensure we cover the core use you need.

**Comment by waldo1001** [comment]
OK, @stuartglasson , looks good.  

How do you want me to illustrate it?

**Comment by stuartglasson** [comment]
Code or pseudo code would be good.
What we're looking for is an understanding of how much of some particular .NET type needs to be implemented by us in order to be useful.

**Comment by waldo1001** [comment]
Well, let's point to the codeunit I'd like to be able to create in .al :-).  That gives you all code that I was thinking about...

https://github.com/waldo1001/Waldo.NAV/blob/master/WaldoNAVPad/Split/COD82111.TXT

**Comment by kaspermoerch** [comment]
I use .NET for splitting strings with the following code snippets:

![image](https://cloud.githubusercontent.com/assets/1166791/23202670/55195468-f8df-11e6-9958-5c6a561295e1.png)

It can of course be done with plain AL, but would require much more code.

**Comment by Gallimathias** [comment]
I find that the split functionality should be done with strings over a member access.
`stringArrayB := stringA.Split();`
And really great would be array access by an indexer.
`stringB := stringArrayB[10];
stringArrayA := stringArrayB[1].Split();`
If we are already there. It would be super advantageous if arrays were either A) expandable or dynamically definable or there would still be something like List. Currently arrays in classic AL are in my opinion a joke and are only annoying.

**Comment by StanislawStempin** [comment]
String handling functions have been delivered in August update. Please log new issues for specific things that might still be missing:
https://blogs.msdn.microsoft.com/nav/2017/08/03/nav-development-preview-august-update/
