### ISSUE TITLE
JsonArray adds unwanted JsonObject

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/AL#900]
I am seeing JsonArray and JsonObject add unwanted object.

{"Customer":[{},{"No":"01445544","Name":"Progressive Home Furnishings","Balance":2310.38},{"No":"01454545","Name":"New Concepts Furniture","Balance":342529.44},{"No":"01905893","Name":"Candoxy Canada Inc.","Balance":0.0},{"No":"01905899","Name":"Elkhorn Airport","Balance":0.0},{"No":"01905902","Name":"London Candoxy Storage ...

The "Customer" array has unwanted {} in the beginning of the first object only.

Sample code:

`    
procedure BuildCustomerJsonUsingJObject() Json: Text;
    var
        Customer : Record Customer;
        JObject : JsonObject;
        JArray : JsonArray;
    begin
        Customer.SETAUTOCALCFIELDS(Balance);
        IF Customer.FINDSET THEN REPEAT
            JObject.Add('No', Customer."No.");
            JObject.Add(Customer.FIELDNAME(Name), Customer.Name);
            JObject.Add(Customer.FIELDNAME(Balance), Customer.Balance);
            JArray.Add(JObject);
            JObject.RemoveAll;        
        UNTIL Customer.NEXT = 0;
        JObject.Add(Customer.TableName,JArray);
        JObject.WriteTo(Json);
    end;
`

**Comment by atoader** [comment]
Thanks for reporting! I will investigate.

**Comment by atoader** [comment]
The same code in C# produces the same result. 
```
using System;
using Newtonsoft.Json.Linq;

namespace ConsoleApp19
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var jobject = new JObject();
            var jarray = new JArray();

            foreach (var customer in new[] { new { No = 1, Name = "Test", Balance = 1.2m }, new { No = 2, Name = "Test2", Balance = 2.2m } })
            {
                jobject.Add("No", customer.No);
                jobject.Add("Name", customer.Name);
                jobject.Add("Balance", customer.Balance);
                jarray.Add(jobject);
                jobject.RemoveAll();
            }

            Console.WriteLine(jarray.ToString());
        }
    }
}
```
This is mostly to the fact that, for the sake of performance, JSON and XML types are reference types and not value types. This means that when you:
```
JArray.Add(JObject);
```
You add the reference to the object and when you later call 
```
JObject.RemoveAll()
```
you clear its value.

I have opened a ticket to add more documentation on this issue.
The solution is to call Clear on the JObject variable instead of RemoveAll

**Comment by yrest** [comment]
Would it be at all possible to use something like Newtonsoft.Json.JsonConvert.SerializeObject(customer)

**Comment by atoader** [comment]
It is on our backlog, but I cannot offer you an ETA.
