### ISSUE TITLE
[Request] Add more events for WMS management, Dim Management

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#902]
Hi!
I have some request:
**_1._** Please add more some events for these methods:
    - Codeunit 5895 Inventory Adjustment : PostItemJnlLine
    - Codeunit 7301 Whse. Jnl.-Register Line : InitWhseEntry
    - Codeunit 7302 WMS Management : CreateWhseJnlLine

**_2._** Please implement more workflows for FA Journal, Item Journal as General Journal have done.

**_3._** For Codeunit 408 DimensionManagement - Method CheckDimValue, Current the system
only allow to post Dimension with Type=Standard|Begin-Total. But there are some our customers request that user only allow to post Dimension with Type=Standard. Please support us an option to do it.

**_4._** Please support system table 2000000039 Printer for extensions.

**Comment by StanislawStempin** [comment]
Regarding point 4 - why do you need this table? What would you expect to find in it on a dynamics 365 tenant?

**Comment by hgnamvn** [comment]
For point 4, I mean: In some cases, the customer want to select printer from client side for print report without preview report.

**Comment by AlexanderYakunin** [comment]
Unfortunately I cannot process your request. Please be more specific for events you need for asks 1 and 2. For your ask 3 - please suggest how you would like to solve this problem. In ask 4 - Printer is system table, we cannot add events here. Instead we can make codeunit which provide interface to table Printer, but we need to know your requirements for this interface. Please rework your request and make one ask per request please.

**Comment by hgnamvn** [comment]
Hi AlexanderYakunin,

1. Please add more some events for these methods
 - Codeunit 5895 Inventory Adjustment : function **"PostItemJnlLine"**. To assign some custom fields' data from OrigValueEntry to ItemJnlLine.
      ![image](https://user-images.githubusercontent.com/24407031/34187263-132cb042-e563-11e7-9a55-5efd31d6d8ea.png)

 - Codeunit 7301 Whse. Jnl.-Register Line : function **"InitWhseEntry"**. To assign some custom fields' data from WhseJnlLine to WhseEntry.
     ![image](https://user-images.githubusercontent.com/24407031/34187325-5d621620-e563-11e7-9c17-159d4912972a.png)

 - Codeunit 7302 WMS Management : function **"InitWhseJnlLine"**. To assign some custom fields' data from ItemJnlLine to WhseJnlLine.
     ![image](https://user-images.githubusercontent.com/24407031/34187398-b6d3b09c-e563-11e7-8e17-34796c71ce8d.png)

2. Please implement more workflows for FA Journal, Item Journal as General Journal have done.
   The system already have workflow template for general journal (MS-GJBAPW and MS-GJLAPW).
   Please also implement more workflow template for Item journal (maybe: MS-IJBAPW and MS-IJLAPW) for "Item journal" page, implement more workflow template for Fixed Asset (maybe: MS-FAJBAPW and MS-FAJLAPW). if need, i can log new thread for this request. Please confirm if you want.

3. For Codeunit 408 DimensionManagement - Method CheckDimValue, please add more event before or affter the standard code with DimVal as parameter, so that I can implement my requirement by myself.
     ![image](https://user-images.githubusercontent.com/24407031/34188923-779124ca-e56b-11e7-89d3-77073ad5e026.png)

4. I found another method for my request, so please cancel this point.

**Comment by AlexanderYakunin** [comment]
Thanks! Item 1 and 3 are in progress and will be implemented soon. Please move item 2 for workflows into another thread.
