### ISSUE TITLE
[Request] Import pictures for multi-customer at the moment.

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/AL#903]
Hi.

On **Customer Card** page have a Customer Picture Factbox, Please support us a function to import pictures for multi Customer at the moment.
**_And please also do that for Vendor, Item, FA, Contact_** 

![image](https://user-images.githubusercontent.com/24407031/31069281-fe0337b0-a785-11e7-9979-edc57373790f.png)
I have implemented a report on-premise. I also try do it with AL language, but AL still don't support IMPORTFILE method of Media DataType, some methods of File DataType, DeleteServerFile method of Codeunit FileManagement.

**Comment by StanislawStempin** [comment]
For On-Premise extensions simply use:  "target" : "internal" in the app.json and configure the NST to accept compilation level Internal.

We will look into the mass-import scenario for the cloud.

**Comment by hgnamvn** [comment]
Hi StanislawStempin,
I am trying to build large package with NAV Docker (November Update). Please show me more details about "configure the NST to accept compilation level Internal", so that i can fix issues of this import multi-picture tool.

Thank you so much!
