### ISSUE TITLE
Caption

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#906]
Have Captions been depreciated?

Txt2AL still creates them but the compiles does not like them
![caption](https://user-images.githubusercontent.com/7205122/32603791-53528ef4-c54b-11e7-892e-4ce5346809e9.png)

**Comment by DominikDitoIvosevic** [comment]
They most certainly have not been removed. This should work. Could you tell me which version of vs extension you have?

**Comment by markbrummel** [comment]
![al](https://user-images.githubusercontent.com/7205122/32606978-915ea4ce-c557-11e7-9e3b-d987d7ba6ac5.png)

**Comment by markbrummel** [comment]
I think the extension on the marketplace has not been updated since september. Is that correct? Do I have to pull the extension from the Azure machine?

When are you going to keep the marketplace in synch with the updates?

**Comment by DominikDitoIvosevic** [comment]
Yes, it looks like you have a too old version. I'll get back to you for the other questions. Try to get a newer version from the azure instance in the mean time.

**Comment by markbrummel** [comment]
Trying that. It's a freaking nightmare with all this docker stuff. Nothing is accessible in the way you would expect.

**Comment by StanislawStempin** [comment]
Hi Mark,
The VS Code extension present on the marketplace is a version that is in sync with the Cloud Sandboxes.
The Developer Preview builds are ahead and that's why you need to use a pre-release version of the extension that is bundled with the docker images.

**Comment by markbrummel** [comment]
So what will be the extension for NAV2018? Surely not mandatory via Docker I hope.

**Comment by StanislawStempin** [comment]
For NAV 2018 the VSIX file will be copied into program files folder by the NAV installer.

**Comment by markbrummel** [comment]
That would be perfect! Is that already in next weeks CTP17?

**Comment by ln1000000** [comment]
@DominikDitoIvosevic AL version 0.11.14434. We're running the October build with Docker.

**Comment by StanislawStempin** [comment]
Could you check on December Update and let us know if you're still running into this issue?
