### ISSUE TITLE
NAVApp record not supported

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#907]
Hi,

we see that NAVApp Record in not available without this we cannot delete the records created in assisted setup, help & resources and product videos during unpublish of the app.

can you please suggest on this.

Thanks & Regards
Varun Reddy

**Comment by DominikDitoIvosevic** [comment]
Hi Varun
In what way is it not available?
I'm currently investigating a bug where for event subscribers using NAV App record has a bug when publishing

**Comment by bachii1010** [comment]
Hi,

See below we need the navapp record in this events

![image](https://user-images.githubusercontent.com/26792519/32606078-e6823354-c579-11e7-975c-a4bd568fce15.png)

the below is the error:
![image](https://user-images.githubusercontent.com/26792519/32606094-f9cc2406-c579-11e7-9c78-f1c3735ac4ac.png)

Please suggest.
Thanks & Regards
Varun Reddy

**Comment by kvaldik** [comment]
This is the related to [#830](https://github.com/Microsoft/AL/issues/830) and shouldn't be that difficult to add for extensions.

**Comment by StanislawStempin** [comment]
See the reply to #830
