### ISSUE TITLE
[Feature Request] Creation of InStreams directly from TextBuilder

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#909]
The new TextBuilder is indeed very practical, and also very fast in terms of performance. It would be very helpful if you could generate an InStream directly from this and download it with the function "DownloadFromStream". You could then avoid the laborious detour to create this InStream first.

**Comment by BazookaMusic** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 

As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.

We are constantly monitoring top ideas and will consider them for a future release.
