### ISSUE TITLE
Sending invoices/reports as an email in an extension

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#910]
Hi all.

We have a V1 extension in D365 and we are using the Email Item table to send invoices. This will no longer work in V2 since we need to save the report to a temporary location in order to attach it to the email, and file handling is banned in D365.

We would however like to continue to allow our users to send emails to their customers. But this seems to be blocked for extensions since none of the emailing functions are external. 

Is it possible to have this functionality exposed to extensions? I would prefer to use the standard instead of integrating with a third party email service.

The most straight forward function to expose would be TrySendToEmail in the Sales Invoice Header table. However having access to some of the functions used deeper in TrySendToEmail might be handy as well.

**Comment by StanislawStempin** [comment]
We are looking into ways of exposing this functionality for Extensions V2. We will update this thread once we have a more precise timeline but we treat it with high priority.

**Comment by StanislawStempin** [comment]
A new procedure in codeunit 260 has been added. Please let us know if this is sufficient for your scenario:

 [External]
    PROCEDURE EmailFileFromStream@24(AttachementStream@1001 : InStream;AttachmentName@1006 : Text;Body@1007 : Text;Subject@1008 : Text;MailTo@1009 : Text;HideDialog@1011 : Boolean;ReportUsage@1012 : Integer) : Boolean;
    VAR
      TempEmailItem@1010 : TEMPORARY Record 9500;
      FileManagement@1004 : Codeunit 419;
      TempFile@1003 : File;
      OutStream@1002 : OutStream;
      TempFileName@1005 : Text;
    BEGIN
      TempFileName := FileManagement.ServerTempFileName('');
      TempFile.CREATE(TempFileName);

      TempFile.CREATEOUTSTREAM(OutStream);
      COPYSTREAM(OutStream,AttachementStream);
      TempFile.CLOSE;

      TempEmailItem.VALIDATE("Plaintext Formatted",TRUE);
      TempEmailItem.SetBodyText(Body);

      EXIT(EmailFileInternal(
          TempEmailItem,
          COPYSTR(TempFileName,1,MAXSTRLEN(TempEmailItem."Attachment File Path")),
          COPYSTR(AttachmentName,1,MAXSTRLEN(TempEmailItem."Attachment Name")),
          '',
          COPYSTR(Subject,1,MAXSTRLEN(TempEmailItem.Subject)),
          COPYSTR(MailTo,1,MAXSTRLEN(TempEmailItem."Send to")),
          '',
          '',
          HideDialog,
          ReportUsage,
          FALSE));
    END;

**Comment by kvaldik** [comment]
I've just tested this and it does what we need.

One followup feature that would be useful is to be able to send a report as html in the email body. If I save a report as html and put the html text in the email body I receive the email with the html code as plain text. I guess the email needs to be configured to using html rather than plain text or something like that.
