### ISSUE TITLE
Flowfield with lookup causes crash when enabled=false

### ISSUE THREAD

**Issue by faludigabor** [Microsoft/AL#916]
I have a table extension that does a reason code lookup for an item . I use a flowfield to show the text of the "block reason" to help the customer .

![2017-11-12 14_49_19-itemextenion al - demoprep - visual studio code](https://user-images.githubusercontent.com/16480091/32699612-f4a2aa04-c7b8-11e7-8ae8-d96ecf958563.png)

This works just fine until I set the enabled property to false then I receive a non informative error message .

![2017-11-12 14_44_36-demo preps - onenote](https://user-images.githubusercontent.com/16480091/32699618-090a1284-c7b9-11e7-8eec-cdff533a9ade.png)

here is my solution : 
https://github.com/faludigabor/AlCodeDemo
**This is whats on the docker console :** 
 : 11/12/2017 2:55:37 PM
 : Error
 : Server instance: NAV
   Tenant ID:
   <ii>User:
   Type: System.IndexOutOfRangeException
   Message: <ii>Index was outside the bounds of the array.</ii>
   StackTrace:
        at Microsoft.Dynamics.Nav.Runtime.MutableRecordBuffer.set_
   Item(Int32 index, NavValue value)
        at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Cal
   cFields(DataError errorLevel, NCLMetaField[] fields, Boolean
   onlyFieldsSourcedFromVirtualTables)
        at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Cal
   cAutoCalcFields(Boolean calculateAll)
        at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Fin
   dRecordWithoutCheckingValues(DataError errorLevel, NavValue[]
   primaryKeyValues, FiltersAndMarks filtersAndMarks, Boolean
   useRecord, Boolean cacheOnly, Boolean calcAutoCalcFields)
        at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Get
   Record(DataError errorLevel, NavRecordId recordId, Boolean
   copyRecord, Boolean useFilters, Boolean calcAutoCalcFields)
        at Microsoft.Dynamics.Nav.Runtime.NavRecord.Get(DataError
   errorLevel, NavRecordId recordId, Boolean copyRecord, Boolean
   useFilters, Boolean calcAutoCalcFields)
        at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRe
   gistrateDataAccess(FormOpenResponse openResponse)
        at
   Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession
   session)
        at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenF
   ormRequest form)
        at SyncInvokeOpenForm(Object , Object[] , Object[] )
        at
   System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
   instance, Object[] inputs, Object[]& outputs)
        at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
   RunInTransactionCombinator(ServiceOperation innerOperation,
   NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
   inputs, Object[]& outputs)
        at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
   <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase
   serviceInstance, Object[] inputs, Object[]& outputs)
        at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
   TransientErrorRetryCombinator(ServiceOperation innerOperation,
   NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
   inputs, Object[]& outputs)
        at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
   <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase
   serviceInstance, Object[] inputs, Object[]& outputs)
        at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
   ErrorMappingCombinator(ServiceOperation innerOperation,
   NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
   inputs, Object[]& outputs)
   Source: Microsoft.Dynamics.Nav.Ncl
   HResult: -2146233080
   </ii>
thanks,
gabor

**Comment by kalberes** [comment]
This is a bug.
