### ISSUE TITLE
November Update - Error: Could not connect to the server.

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#917]
When I try to publish the Sample AL Projects (_C:\Users\vmadmin\Documents\AL\Samples\HelloWorld_ or _C:\Users\vmadmin\Documents\AL\Samples\GetAddressService_) I got the following error messages:
> [2017-11-12 18:47:21.96] Error: Could not connect to the server. Please verify that:
> 1. The server is started.
> 2. The development endpoint is enabled (DeveloperServicesEnabled server setting).
> 3. The service name matches the one specified in the URL.
> 4. The port number matches the one specified in the URL (DeveloperServicesPort server setting).
> 5. The protocol matches the one specified in the URL (DeveloperServicesSSLEnabled server setting), and that a trusted certificate is used in case of an SSL connection.
> Please provide the 'startupObjectId' setting in the launch.json file

In order to fix that errors in _launch.json_, I had to add the line `"startupObjectId" : 22` (Page 22 seems to be the default value), change `"server" : "http://localhost"` to `"server" : "https://nav2018nov.westeurope.cloudapp.azure.com"` (_nav2018nov.westeurope._ in my case)  and `"serverInstance" : "us"` to `"serverInstance" : "NAV"` as well as `"authentication": "Windows"` to `"authentication": "UserPassword"`.

Also as said in the latest [Blog Post](https://blogs.msdn.microsoft.com/nav/2017/11/08/nav-development-preview-november-update/) to be able to download the Symbols in app.json 
```
  "application": {
    "version": "10.0.0.0",
    "locale": "US"
  },
```
should be changed to
```
  "application":  "10.0.0.0",
```

It would more user friendly if the Samples would work right out the box or everything static would be fix and for the rest a hint for what to be change (currently: `"server"`).

**Comment by moulikaku** [comment]
Hi Try below changes and settings for Hello world program will work

launch.json file 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Publish",
            "server": "https://****.uksouth.cloudapp.azure.com",
            "serverInstance": "NAV",
            "authentication": "UserPassword"
        }
    ]
}

app.json

{
  "id": "a7a49c61-7712-400a-9fc5-bc35f8e02aa0",
  "name": "Hello World",
  "publisher": "Microsoft",
  "brief": "The ability to greet your customers ",
  "description": "The ability to greet your customers in multiple languages.",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "platform": "11.0.0.0",
  "application": {
    "version": "11.0.0.0",
    "locale": "US"
  },
  "screenshots": []
}

**Comment by StanislawStempin** [comment]
The samples have been updated with all required changes apart from "server" in which we left placeholders to populate vm name and azure region.
