### ISSUE TITLE
Which Xliff tool is recommended

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#919]
Now we have XLIFF and we are spoilt for choice. There seems to be no VS Code extension for XLIFF. Which tool is recommended by MS? Has anyone already had experience with an XLIFF tool? Maybe you can gather some experience here.

**Comment by sd484** [comment]
I am using **[Pootle](http://pootle.translatehouse.org/)**. 
It is an online translation tool and translation management tool. I have installed my own instance of Pootle on a Linux server, but you could also use a pre-configured docker image or you deploy a Pootle installation directly to azure by using the [bitnami image](https://bitnami.com/stack/pootle).

**Comment by Gallimathias** [comment]
I'm currently experimenting with Weblate which I like best so far. Most of the XLIFF tools haven't convinced me yet. With recherchen I stumbled upon some interesting comments. XLIFF was developed for CAD software, which is unfortunately also noticeable in most tools.

I am thinking about writing my own OpenSource XLIFF tool.

**Comment by epernst** [comment]
Remember one of the old Navision translation tools. Here you "feed" it with both the full standard ENU and whatever language code you needed. This was then used as the foundation to set the context and from which the tool could suggest similar wording. Often that would give you a majority of the required translation, with the advantage that same words always were translated the same, no matter if it was standard Navision or our add-on.
My hope is that a similar tool is out there, which we could use.

**Comment by Gallimathias** [comment]
@epernst Such a function is available in Weblate. My current problem with the tools is the process or the power that doesn't fit 100% to us. Weblate is cool and Pootle is probably cool too. 

I would also like to see some fast translations. a google translator or Deepl connection would exist.

**Comment by sd484** [comment]
@Gallimathias Weblate as well as Pootle are both based on the Translate Toolkit and the Django framework. So I think they are quite similar (but I have to take a close look to Weblate). 
Why do you want to write your own tool? What's wrong with Weblate?

**Comment by StanislawStempin** [comment]
We do not have an official recommendation and would really like to hear from you on what your experience is with using various tools

**Comment by Gallimathias** [comment]
Ok all clear @StanislawStemptin. I am also curious what the discussion promotes as too days. What kind of tool do you use?

@sd484 In itself, the tool is good, it's just minorities. 
* I need a Linux environment (ok that's really small thanks to Azure, Docker or raspberry). 
* Much more the process structure disturbs me. Weblate allows programming and then translating, that's ok but we are getting more and more agile and then traslation changes in several branches all the time. It is rather annoying and time-consuming to correct this manually every time. I would also like more convenience features. Reusability of records. Standard sentences for easy adoption. Connection to tools such as DeepL or Google Translator. A bit of reporting would be interesting.

Conclusion the idea would be to produce a tool that is more tailored to the NAV scenario. A connection to VS Code would also be interesting or a narrower GUI. In my case the browser windows count grows on my screen and this is annoying.

**Comment by FSharpCSharp** [comment]
I am also looking for a useful tool to manage XLIFF files. the mentioned tools all sound not bad, but they are all web-based. This poses a problem for us, as the processing is to take place exclusively offline. I am a little surprised that there is no reasonable extension for the Visual Studio code to manage XLIFF files.

@Gallimathias 
I would suggest that if there really is a new development here, it should be directly integrated into Visual Studio code. Then you wouldn't have to change the software again just to edit these files.

@StanislawStempin 
Is there actually also a tool for automatically transferring the ML texts in the objects to the XLIFFs? Translate export in the Classic Client is excluded because the source code is no longer available in the old structure.

**Comment by Gallimathias** [comment]
@FSharpCSharp I see it that way like you. Would you be interested in a joint open source development?

I wouldn't keep it vs-code exclusive now, but this should be given special attention or a special priority.

**Comment by lvanvugt** [comment]
Guys, I think translation of XLIFF should be support by [Microsoft Dynamics 365 - Translation Service](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/translation-service-overview).

**Comment by DominikDitoIvosevic** [comment]
@lvanvugt it's on the way :)

**Comment by lvanvugt** [comment]
@DominikDitoIvosevic aspart of the Microsoft Dynamics 365 - Translation Service?

**Comment by StefanHovenbitzer** [comment]
until then https://developer.microsoft.com/de-de/windows/develop/multilingual-app-toolkit is adds a lokal Program: "Multilingual Editor"

**Comment by lvanvugt** [comment]
Thanx @StefanHovenbitzer. Not being a VS expert, how do I go about using this for just translating a xliff file? Any tips are welcome.

**Comment by StefanHovenbitzer** [comment]
i just installed it with option "Complete" and it set itself as default program for .xlf files

**Comment by lvanvugt** [comment]
Aha, so I can run it stand alone. Hadn't thought of that having watched the videos.Thanx.

**Comment by AddEleven** [comment]
The above link requires you to sign in with your twitter account which gives them permission to:
**Read Tweets from your timeline.
See who you follow, and follow new people.
Update your profile.
Post Tweets for you.
See your email address.**

**Comment by ShalokShalom** [comment]
Which one? 

Xliff does work perfectly correct here 
Is there even such a login via Twitter?

Simply upload the file and that`s it.

**Comment by GreatScott000** [comment]
So now I have to learn Linux in order to use a translation tool??????? Pootle and Weblate are both Linux based.

**Comment by Gallimathias** [comment]
@GreatScott000 Most translation tools are for Linux, yes. XLIFF does not come from the MS universe :D

Personally and also from what I have heard from others, Poodle and Weblate are the most convincing. But you don't have to use that, you can find a tool that fits you better and runs on Windows or write one yourself. Feel free.

If the question was meant otherwise. I am not aware that Poodle or Weblate is available as a Windows application. However, there are docker images.

**Comment by ShalokShalom** [comment]
And you dont have to learn Linux, in order to use a Linux based OS. 

So long as you can do steps which my grandmother can do - literally - its fine. 

You are welcome my friend ;)

**Comment by dekarl** [comment]
@Gallimathias with regard to feature branches, you could put a tool that collects the strings from the branches and sends them to the translation service, e.g. https://serge.io/docs/plugins/callback/feature_branch/
(disclaimer: I've not used this myself, as I'm just researching options at the moment)

**Comment by marie-dk** [comment]
> The above link requires you to sign in with your twitter account which gives them permission to:
> **Read Tweets from your timeline. See who you follow, and follow new people. Update your profile. Post Tweets for you. See your email address.**

@AddEleven is absolutely correct. It seems you can just upload at translate at http://xliff.brightec.co.uk/, but after all your work is done, you are forced to sign in with Twitter to get your translated file. Seems like a scam to get access to your data. If it looks like a trap, and feels like a trap...

**Comment by StefanHovenbitzer** [comment]
synXLIFF - AddOn for Business Central
https://www.synalis.de/synxliff/

Its a free App for translating XLF-files within Business Central (ID-Range 90100..90120).

**Comment by svwfr** [comment]
For synXLIFF I got error: "maxWidth attribute is not declared" !

**Comment by StefanHovenbitzer** [comment]
We uploaded a new version where this issue should be fixed. Please try again.

**Comment by svwfr** [comment]
Sorry StefanHovenbitzer, got the same error:  "maxWidth attribute is not declared"  With Your v.1.0.0.1

**Comment by AndreasSippel** [comment]
It seems to be an issue of case sensitivity. Per default the attribute is "maxwidth" when generated in AL.
If you replace "maxWidth" with "maxwidth" in your file, it should work.

**Comment by svwfr** [comment]
Yes, thx that was the case. But my .xfl generated by AL build: 0.12.28462 does write the attribute like maxWidth, whith capital 'W'.

**Comment by Gallimathias** [comment]
I'm sorry. But I think this is really off-topic. Errors to synXLIFF should be reported to synXLIFF Repo and not in an Thread about __wich Tool__ is recommended.

**Comment by StefanMaron** [comment]
> I'm sorry. But I think this is really off-topic. Errors to synXLIFF should be reported to synXLIFF Repo and not in an Thread about **wich Tool** is recommended.

Issues are now tracked here:
https://github.com/StefanMaron/synXLIFF

**Comment by Wildhammer** [comment]
https://lokalise.co

**Comment by CptBlaubart** [comment]
Which one of the mentioned tools is best for collaborative work? We're currently upgrading our C/AL solution into AL in a team of 4 developers. Each feature we decide to adopt is built in a different branch and merged with a pull request. Currently, we added *.xlf to the gitignore list, as it creates merge conflicts all the time of the pull-request. Which also means that we didn't do any translations, yet. - But we need to, as we're publishing in 4 languages and we don't really want to have one guy/girl translate everything at the end of the project.

So, I think, we need something that is able to complement the missing translations in the localized files, and exports the files with the elements in a fixed order so git's merge engine doesn't get confused just because two items switched places. - We already noticed, that the IDs AL Language creates are based on the object name - probably. So it'd be really great if we woudn't lose all our translations just because we fixed a typo in the Reports Object Name.

**Comment by hvitsten** [comment]
I made my own tool that I published to the Microsoft Store. It is a simple program that can be used to translate XLIFF files, as well as compare source file (generated by BC) with target file (translated file) and find new texts so that they can be translated and added. There is little extra functionality as I have just developed and published it. It's called Translation Merge Tool. It's not free, but it has a free trial.
https://www.microsoft.com/store/apps/9NK0C52PJWD9

**Comment by boomerama** [comment]
Hi, i dont know if this topic is still actual. 

i am quite happy with the combination of 
this one to create and sync the XLFF Files (incluiding autom. language translation from the code)
https://marketplace.visualstudio.com/items?itemName=rvanbekkum.xliff-sync

And this tool to search the XLFF translation for a "item" (Caption, Label, etc)

https://marketplace.visualstudio.com/items?itemName=nabsolutions.nab-al-tools

**Comment by avivr06** [comment]
> Hi guys
> 
> This here is a standalone, web-based, no registration or installation required solution: http://xliff.brightec.co.uk/

It has limitations for up to 1000 items. After 1000 the target is set to blank in the generated file.

**Comment by ramyakrishnapandian** [comment]
> I'm currently experimenting with Weblate which I like best so far. Most of the XLIFF tools haven't convinced me yet. With recherchen I stumbled upon some interesting comments. XLIFF was developed for CAD software, which is unfortunately also noticeable in most tools.
> I am thinking about writing my own OpenSource XLIFF tool.

Hi, Could you please guide me how to translate business central xlif file using Weblate, because i'm very new to Weblate.

**Comment by mmarquez** [comment]
I think that the best tool is still [QT Linguist](https://download.qt.io/linguist_releases/)
