### ISSUE TITLE
[Event Request] Additional posting events that are missing

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#921]
Due to the November update, a lot of events have been added which were missing in the booking process so far. But there are still some events missing. Here are the places that are still missing and what the events should look like.

Codeunit 12:

> OnBeforeRun(GenJnlLine,PreviewMode)

This event is particularly important to determine whether the current posting is being previewed.

===================================================================

Codeunit 13:

> OnBeforeProcessLines(VAR GenJnlLine)

===================================================================

Codeunit 13:

> OnBeforeCode(VAR GenJnlLine)

===================================================================

Codeunit 12:

> OnBeforeUpdateAndDeleteLines(VAR GenJournalLine : Record "Gen. Journal Line")

===================================================================

Codeunit 12:

> OnBeforeInsertGlobalGLEntry(GlobalGLEntry,GenJnlLine,TaxDetail)

===================================================================

Codeunit12:

> OnAfterInitGLEntry(GLEntry,GenJnlLine)

===================================================================

Codeunit12:
Before the Code `VATEntry.INSERT(TRUE);` in Function `InsertVAT`. The table event cannot be used here because the reference to the Gen. Journal Line is missing.

> OnBeforeInsertVATEntry(GenJnlLine)

===================================================================

Codeunit12:
In Function `CalcPmtTolerance` after the following code lines
```
PmtTol := -OldCVLedgEntryBuf2."Accepted Payment Tolerance";
PmtTolAmtToBeApplied := PmtTolAmtToBeApplied + PmtTol;
PmtTolLCY :=
  ROUND(
    (NewCVLedgEntryBuf."Original Amount" + PmtTol) / NewCVLedgEntryBuf."Original Currency Factor") -
  NewCVLedgEntryBuf."Original Amt. (LCY)";
```

> OnAfterCalcPmtTolerance(PmtTol,PmtTolAmtToBeApplied,PmtToILCY,OldCVLedgEntryBuf,OldCVLedgEntryBuf2)

===================================================================

Codeunit12:
In Function `CalcPmtDisc` after the following code lines
```
  PmtDisc := -OldCVLedgEntryBuf2."Remaining Pmt. Disc. Possible";
  PmtDiscLCY :=
    ROUND(
      (NewCVLedgEntryBuf."Original Amount" + PmtDisc) / NewCVLedgEntryBuf."Original Currency Factor") -
    NewCVLedgEntryBuf."Original Amt. (LCY)";
```

> OnAfterCalcPmtDisc(PmtDisc,PmtDiscLCY,OldCVLedgEntryBuf,OldCVLedgEntryBuf2)

===================================================================

Codeunit12:
In Function `InsertPmtDiscVATForVATEntry` before the line
`TempVATEntry.INSERT;`
The table event cannot be used here because the reference to the Gen. Journal Line is missing.

> OnBeforeInsertTempVATEntry(GenJnlLine)

===================================================================

Codeunit12:

> OnBeforeFindAmtForAppln(NewCVLedgEntryBuf ;OldCVLedgEntryBuf ;OldCVLedgEntryBuf2 ;AppliedAmount ;AppliedAmountLCY ;OldAppliedAmount)

> OnAfterFindAmtForAppln(NewCVLedgEntryBuf ;OldCVLedgEntryBuf ;OldCVLedgEntryBuf2 ;AppliedAmount ;AppliedAmountLCY ;OldAppliedAmount)

===================================================================

Table 383:
In Function `InitFromGenJnlLine` 

> OnAfterInitFromGenJnlLine(GenJnlLine)

===================================================================

Codeunit 12:

> OnBeforeInsertDtldCustLedgEntry(GenJnlLine)

Before the following code line
`  INSERT(TRUE);`
The table event cannot be used here because the reference to the Gen. Journal Line is missing.

===================================================================

Codeunit 12:

> OnBeforeInsertDtldVendLedgEntry(GenJnlLine)

Before the following code line
`  INSERT(TRUE);`
The table event cannot be used here because the reference to the Gen. Journal Line is missing.

===================================================================

Codeunit 12:

> OnBeforeInsertDtldCustLedgEntryUnapply(GenJnlLine)

Before the following code line
`  INSERT(TRUE);`
The table event cannot be used here because the reference to the Gen. Journal Line is missing.

===================================================================

Codeunit 12:

> OnBeforeInsertDtldVendLedgEntryUnapply(GenJnlLine)

Before the following code line
`  INSERT(TRUE);`
The table event cannot be used here because the reference to the Gen. Journal Line is missing.

===================================================================

Codeunit 17:

> OnBeforeCreateGenJnlLine(GenJnlLine)

Before the following Code
```
IF GenJnlPostLine.GetNextEntryNo = 0 THEN
  GenJnlPostLine.StartPosting(GenJnlLine)
ELSE
  GenJnlPostLine.ContinuePosting(GenJnlLine);
```

===================================================================

Codeunit 17:

> OnBeforeCreateReversedCustAndVendLedgEntries(GenJnlLine)

Before the following Code
```
GenJnlPostLine.SetGLRegReverse(GLReg);

CopyCustLedgEntry(CustLedgEntry,TempCustLedgEntry);
CopyVendLedgEntry(VendLedgEntry,TempVendLedgEntry);
CopyBankAccLedgEntry(BankAccLedgEntry,TempBankAccLedgEntry);
```

**Comment by FSharpCSharp** [comment]
I just wanted to inform myself about the current status of this event request. This one was accepted. Is there already an approximate planning when these events will be installed? Since the extension is based on these events I would need them as soon as possible.

**Comment by AlexanderYakunin** [comment]
We implement events on daily basis, this one is available from Dec 2. Check CTP18 or take any build after Dec 2.
