### ISSUE TITLE
[Feature Request] Various string functions as standard for text variables

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#922]
The following. NET string functionality should also be available in Dynamics by default:

[String.Contains](https://msdn.microsoft.com/en-us/library/dy85x1sa(v=vs.110).aspx)
[String.IndexOf](https://msdn.microsoft.com/en-us/library/k8b1470s(v=vs.110).aspx)
[String.Split](https://msdn.microsoft.com/en-us/library/tabh47cf(v=vs.110).aspx)
[String.Trim](https://msdn.microsoft.com/en-us/library/t97s7bs3(v=vs.110).aspx)

**Comment by Gallimathias** [comment]
And
String.TrimEnd
String.TrimStart

**Comment by thpeder** [comment]
In the August update we added all those functions and more to the language.
You can find them here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/datatypes/devenv-text-data-type

**Comment by Gallimathias** [comment]
@thpeder right, but i can't see the split function.

**Comment by thpeder** [comment]
@Gallimathias The Split function is in the language, we just missed it in the documentation.

**Comment by Gallimathias** [comment]
Oh, fact, excuse me. I think I even had a positive comment when it came out. 

If you're not program permanently AL , something goes down fast.

Sorry again ^^
