### ISSUE TITLE
SETSELECTIONFILTER(Record)

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#927]
Are there any plans to provide external access to the SETSELECTIONFILTER function?

Example:

```
ResourceList.LOOKUPMODE(TRUE);
IF ResourceList.RUNMODAL = ACTION::LookupOK THEN BEGIN
  ResourceList.SETSELECTIONFILTER(Resource);
  ...
END;
```

This would give more flexibility and allow to receive multiple selections from NAV core pages without modifiying them.

**Comment by Skordas** [comment]
You can create a "pageextension" object to extend the page and retrieve the selectionfilter.

**Comment by ThomasBrodkorb** [comment]
By allowing this, the following (and future) function requests would be (at least partly) obsolete: #420 , #552, #609 , #948

**Comment by ShadowXVII** [comment]
SETSELECTIONFILTER across all pages would be useful.

The pageextension/function would be a good way to do so without adjusting page event signatures to include CurrPage.

**Comment by StanislawStempin** [comment]
I'm not sure I understand this request. Currently you can already access SetSelectionFilter both through a page variable and through CurrPage on a page extension. What do you mean by external access to this function?

**Comment by StanislawStempin** [comment]
What I mean is that this code compiles for me without any problems:
```
codeunit 50101 Demo 
{
    procedure AccessSetSelectionFilter()
    var
        page1 : page  "Absence Over. by Cat. Matrix";
        tab1: record "Acc. Sched. KPI Buffer";
    begin
        page1.SetSelectionFilter(tab1);
    end;
}
```

So I don't quite understand what other kind of external access is required. Can you give an AL code example that demonstrates the problem?

**Comment by ThomasBrodkorb** [comment]
I'm surprised, it really works, it is just undocumented.
So is UPDATE and SAVERECORD.

It would really be of big help if those functions - which are publically available - are documented somewhere and shown in the CAL Menu in DevEnv.
