### ISSUE TITLE
Base logic doesn't allow adding workflow templates

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#929]
There is an event (OnInsertWorkflowTemplates) in codeunit 1502 (Workflow Setup) in the InsertWorkflowTemplates function. I've subscribed to this event, and after copying a number of base functions (see issue #928) it seems as though I will be able to add my own workflow templates.

Not so...............

The function InsertWorkflowTemplates is ONLY called when there are no existing workflow templates, which pretty much renders it impossible to easily add a new workflow template via extension as there will always be existing entries that are generated as part of the base code.

**Comment by StanislawStempin** [comment]
New event OnAfterInitWorkflowTemplates has been added to solve this issue
