### ISSUE TITLE
OnQueryClosePage issue

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#93]
Hi all,
I have put a message in OnQueryClosePage. But when I close the page and the message is displayed, I press OK, but the message keeps on appearing again and again. It is stuck in a loop.
Kindly suggest

**Comment by esbenk** [comment]
Hi Tina,

The OnQueryCloseTrigger is used to optionally prevent the page from closing. If you add an OnQueryCloseTrigger you must return true if you allow the page to close.
