### ISSUE TITLE
Problems on modern Browser with WebClient and sha1 hashes

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#931]
The web client does not load correctly because the integrities specified use SHA1. I also get the error that the SHA256 hash does not match. There are no problems with Internet Explorer, but it is no longer used by our customers.

Firefox: 57.0 (64-Bit)
Internet Explorer: 11.1770.14393.0
Chrome: Version 62.0.3202.94 (Offizieller Build) (64-Bit)

![error_and_warnings](https://user-images.githubusercontent.com/16351673/32770517-4afe1498-c920-11e7-8966-e5caa25bcdfa.png)

**Comment by Gallimathias** [comment]
Ok same Problem on Chrome

**Comment by jjaviercv** [comment]
Hi,

Can you provide some additional information?
1) How did you create this deployment?
2) What version of our product are you working with?
3) Repro steps?

Thanks,
J

**Comment by Gallimathias** [comment]
The problem has been solved. Removed the hash value in js script ^^.
I use version 0.11.14434
But the warnings remain. I think this could also explain some of the graphic errors.

I created a page with JS controladdin and checked if jQuery is loaded.

````JS
if (window.jQuery) {
        document.getElementById("MessageText").innerText = "jQuery is loaded";        
    } else {
        onError("jQuery load failed!");
    }
````

**Comment by jjaviercv** [comment]
Was it you that had added the hash values?

**Comment by Gallimathias** [comment]
No, by default, sub-resources are checked with the integrities. I wanted to reload a higher version of jQuery just because the hash didn't work that way, because i use the Wrong HTML element. That was the red console entry. But the yellow entries come from Navision itself, all the frameworks used by Navision's web client use SHA1 hashes in the integrities. Mozilla and Google have agreed to block SHA1. Chrome and Firefox completely block the loading of these resources. No framework, no clean representation of the client. Internet Explorer is so old-fashioned that he simply doesn't care about it, because everything is going very well (no Bugs, no Graphic issues, no Warnings).

**Comment by jjaviercv** [comment]
Are you consuming one of the Docker images?

**Comment by Gallimathias** [comment]
I use the default settings when creating via the official link from the README. The only difference is that I chose Westeurope. So yes I use the preview docker image.

**Comment by freddydk** [comment]
The c:\run\setupCertificate.ps1 uses SHA1 by default, that is correct.
I will change this to SHA256, even though the default self-signed certificate, nor docker at this time should be used for production, you seem to be having the problem during development and there is no reason not to change it.
If you want to test this out yourself, share a my folder to the container (-v c:\myfolder:c:\run\my), place the setupcertificate.ps1 from docker in that and modify the New-SelfsignedCert... line to:

New-SelfSignedCertificateEx -Subject "CN=$publicDnsName" -SubjectAlternativeName @($publicDnsName) -IsCA $true -Exportable -Path $certificatePfxFile -Password $SecurePfxPassword -SignatureAlgorithm sha256 | Out-Null

And then remove your container and re-run.

**Comment by Gallimathias** [comment]
Ok thanks @freddydk I'll try it out :)

**Comment by Gallimathias** [comment]
In the published version everything works fine. If this also applies to the December preview, we can close the issue. :)

**Comment by StanislawStempin** [comment]
Once we get a confirmation from you that it works on December Update we would like to close this issue.

**Comment by Gallimathias** [comment]
You have done a very good job and it also works in the preview
