### ISSUE TITLE
[Question] OpenBook feature of Excel Buffer

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#934]
Hi!

In previous release (October Update), I can use Excel Buffer table for importing data from excel file.

But in current release (November Update), I can't use it because OpenBook method of Excel Buffer table is locked, can't used for extension.

Show please show me why extension can't use this method. If you can, please set this method can be used for extension.

**Comment by radovandokic** [comment]
HI,

Any news about this?

**Comment by StanislawStempin** [comment]
If your solution is meant to run in the cloud you need to use the new stream based functions in table 370. 
If it is intended to run On-Premise you can just change the target of your extension to internal by setting "Target" : "Internal" in the app.json.

**Comment by hgnamvn** [comment]
Sorry,
I don't know how to use the "OpenBookStream" function.
This function require a InStream as parameter.
I can't create a instream of local file because AL don't support File API now.

**Comment by StanislawStempin** [comment]
You can create an InStream through File.UploadIntoStream - does that help in your case?

**Comment by hgnamvn** [comment]
Thank StanislawStempin,
I will test your suggestion.

**Comment by hgnamvn** [comment]
Hi StanislawStempin,
You mean the UploadIntoStream of Codeunit 419, I can't find this method.

However, I solved my problem by using BLOB.
Example:
_trigger OnValidate();
            var
              FileBlob : Record TempBlob;
              FileInStream : InStream;
            begin
              IF SheetPar <> '' THEN begin
                FileBlob.Blob.Import(FilePathPar);
                FileBlob.Blob.CreateInStream(FileInStream);
                ExcelBufferTmp.OpenBookStream(FileInStream,SheetPar);
              end;
            end;_
