### ISSUE TITLE
Simple Expression in Visible Property does compile but crashes when opening Page

### ISSUE THREAD

**Issue by dNsl9r** [Microsoft/AL#937]
When using a simple expression in the Visible Property of a e.g. group in a page, there is a bug:
`group(MyGroup1)
 {
 Visible=VisibleInteger=1;`

As you can see, the visibility is based on a simple expression: If my Variable "VisibleInteger" is 1 the Group is visible.
You can compile and publish the app, but when starting the page you get the following error:
![grafik](https://user-images.githubusercontent.com/5330063/32827670-44971ef6-c9ed-11e7-913e-0aca79a14360.png)

When you change the code to the following the page can be opened:

`group(MyGroup1)
 {
 Visible=VisibleInteger = 1;`

Tested on November Preview

**Comment by DominikDitoIvosevic** [comment]
Hi @dNsl9r . The expression parser is not a part of the compiler but the runtime so due to legacy reasons (compatibility with CSIDE) we cannot make breaking changes to it yet

**Comment by DominikDitoIvosevic** [comment]
I have managed to fix the spacing issue. You can expect the fix in the next update
