### ISSUE TITLE
Control Addin event  $(window).load()

### ISSUE THREAD

**Issue by DavideVD** [Microsoft/AL#939]
After many attempts, I still don't find the right place where to put the  $(window).load() event.

I had a simple code in that event in a NAV2017 addin. To test it in the new  environment i create this function :

  **$(window).load(function () {
    alert("Pippo");
  });**

it should be fired after the $(document).ready event (that start correctly)

I tried to put  the test code in the startup script, after the $(document).ready and in a separate script (with just window.load code). It never fires. 

How can I solve this issue? Is there any walk-around?

**Comment by ThomasBrodkorb** [comment]
Well, the "load" event of the window will most probably already have hapeened when you get the chance to add your code in the iframe.
http://www.w3schools.com/jsref/event_frame_onload.asp
maybe this helps?

**Comment by DavideVD** [comment]
Thanks for the answer Thomas, but I am not so sure. In NAV2017 I observed a difference behavior from RTC client and Webclient, difference about the order of the events (I don't remember exactly which is the case), but in one client windows.load triggers before document.ready and in the other client, after. If i am not wrong, in the web client windows.load triggers after the document ready. Since I could intercept the document.ready in VSC, I think something change. I had code in that trigger (window.load) to render the objects in a  canvas, after it has been create.

**Comment by Gallimathias** [comment]
window.ready ->will be fired when the html document (s) is/are completely loaded.
windo.onload -> is thrown when all contents (images, scripts, pages....) have been loaded.

**Comment by DavideVD** [comment]
Thanks Mathias, the problem is I can't find the write place where to intercept the window.load. I tried both in the startupscript and Script, with the syntax above (it is a quite stupid message). It has never been triggered

**Comment by Gallimathias** [comment]
I would write it in the start script. What do you have in mind? eventually there could be an alternative to document. load. If you just want to load a canvas you could use its load event. If you moved code to a second script, how did you integrate it into your app?

**Comment by dennisfrostlander** [comment]
The startup script already runs inside the window.onload handler. Therefore the new subscription does not work as the event already emitted.
You can see this if you inspect the generated html code for the iframe. The alert() is what I've put into my startup script.
![image](https://user-images.githubusercontent.com/16953692/32899316-ef8cf33c-caea-11e7-9178-a3043f171c38.png)
