### ISSUE TITLE
List of unsupported items

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#94]
Hi,

Is there a list of all things that is not supported yet by the new developer tools?

**Comment by StanislawStempin** [comment]
At a high level here are the supported areas:
- Extension development
- Page, Table, Codeunit authoring
- Page Extension objects, Table extension objects authoring
- Reference and run XMLPorts & Reports objects

The rest is not supported yet, notably:
- Report, XmlPort, Query authoring
- Menusuites
- .NET interop
- Base application development

We'd rather not go into a more detailed list. Do you have any specific areas in mind?

**Comment by waldo1001** [comment]
No, this is about the list that I had as well.. .  I also have "dependencies" on it - like being able to created dependent apps, or apps with prerequisites.. .

What about:
- JavaScript Control AddIns
- PermissionSets
- ReportLayouts
- Web Services
- Data Migration 
- ...

I know, it's kind of an open question - but sometimes it's just good to know what is NOT possible in stead of what is ;-)

**Comment by stuartglasson** [comment]
We don't plan on publishing a deeper list of what's not supported yet, however you're right that most of those aren't implemented.

**Comment by m3koenig** [comment]
Hi, I'm not sure because I did not find a 100% statement to this: 
Are add-ins available now? WinForms, JavaScript Control Add Ins (like waldo asked) or own .NET Assemblies?

Or did I missed something?

**Comment by m3koenig** [comment]
I do not find an 100% statement to this: are add ins available now?
WinForms, Javascript (like waldo asked) or own .NET assemblies?

or did I missed something? How to do that?

**Comment by stuartglasson** [comment]
No .NET assemblies, no control add ins yet.
Not sure what you mean by winforms.

**Comment by m3koenig** [comment]
Sorry, i mean WinForms as control add in. The type normal control add in.
Thanks for the answer! :)

In "Old NAV Extensions" Add ins are available or?

**Comment by stuartglasson** [comment]
Still working on that - look for a future (not next, but not too far away either) update.

@all in this thread, this issue isn't really a bug or suggestion - unless you disagree, we'd like to close it in a couple of days.

**Comment by stuartglasson** [comment]
Closing due to being answered and low activity.
