### ISSUE TITLE
Brick fieldgroup not working

### ISSUE THREAD

**Issue by kvaldik** [Microsoft/AL#940]
I have defined the following fieldgroup in one of my tables:
`fieldgroup(Brick;"No.",Description,Inventory,"Unit Price",Quantity,Picture)`

This however isn't reflected in the list pages for the table. Instead the brick/tile view is based on the order of the fields in the page. Which is not what I want, because I want the list view ordered differently than the brick view.

Am I missing something or is this a bug?

**Comment by gudrunleos** [comment]
It would also be appreciated if an extension could overwrite the Brick fieldgroup defined in a core table, for example as a page property.

**Comment by thpeder** [comment]
@kvaldik No it looks like you are doing it right, but there is a bug on this in the November update however it is fixed in the December update.

@gudrunleos We have it on our backlog so we will get to it at some point.
