### ISSUE TITLE
Report - Data Item request fields on Reques page

### ISSUE THREAD

**Issue by gudrunleos** [Microsoft/AL#941]
Hi.
What do I need to do to get the Data Item Request filter fields visible on a report request page ? 

I have a customized report - data Item is Customer and I extend the Customer List with an action to run the report.
This is the start of the report:
![image](https://user-images.githubusercontent.com/24827406/32845607-093c7740-ca1d-11e7-9cdb-91334e381f44.png)

The report also contains a requestpage definition with few fields that are visible 

And here is the Customer List Page extension:
![image](https://user-images.githubusercontent.com/24827406/32845738-6c7052be-ca1d-11e7-8f0f-155148476402.png)

What am I missing here?

**Comment by DominikDitoIvosevic** [comment]
Hi @gudrunleos . Thank you for reporting this bug. I can confirm that we have fixed it and you can expect it to work in a future update
