### ISSUE TITLE
DropDown fieldgroups not working

### ISSUE THREAD

**Issue by TaylerPino** [Microsoft/AL#943]
Since updating to the November update, my drop-down fieldgroups are not displaying and instead defaulting to the primary keys. 
![image](https://user-images.githubusercontent.com/19294127/32861988-95b1f3ba-ca24-11e7-8d75-8b33d0453444.png)
![image](https://user-images.githubusercontent.com/19294127/32862055-c6c86b28-ca24-11e7-97a2-d489240ac1c6.png)

Is there a new way of modifying drop-down columns or is this a bug?

**Comment by DominikDitoIvosevic** [comment]
Hi @TaylerPino . Are you still having this issue?
I just tried using some fieldgroups and it works for me.
Please provide code for repro so that we can investigate.

This code works for me:

```


page 50229 PageName
{
    PageType = Card;
    SourceTable = MyTable2;

    layout
    {
        area(content)
        {
            field(Name; MyField)
            {
                Caption = 'qwe';
                Style=StandardAccent;
                StyleExpr=true;
            }
        }
    }
}

table 50664 MyTable2
{
    
    fields
    {
        field(1;MyField; Integer)
        {
            TableRelation=MyTable;
        }
    }    
}

table 50110 MyTable
{
    
    fields
    {
        field(1;MyField; Integer)        {        }
        field(2;MyField2; Integer)        {        }
        field(3;MyField3; Integer)        {        }
        field(4;MyField4; Integer)        {        }
    }
    
    fieldgroups {
        fieldgroup(DropDown; MyField,MyField3) {        }
    }   
}
```

**Comment by TaylerPino** [comment]
@DominikDitoIvosevic Looks like this bug was fixed on the December build. Thanks!
