### ISSUE TITLE
Formatter for AL

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#944]
Alt+Shift+F keyboard shortcut typically invokes the Format Document command, which applies formatting rules and results in a correctly formatted document. This works fine for many file types (e.g. JSON).

However, when it is run for AL files, the following message appears: "Sorry, but there is no formatter for 'al'-files installed."

It would be nice to include this feature in the AL Language extension.

**Comment by FSharpCSharp** [comment]
Yes, I am absolutely in favour of that. That is why I requested this a few months ago with the following point.  [441](https://github.com/Microsoft/AL/issues/441)

**Comment by Gallimathias** [comment]
That's how I see it too. I am currently using the Rasmus extension, which works quite well for me and I recommend it to others ;).
![al_formatter](https://user-images.githubusercontent.com/16351673/32878179-3bb5b00a-caa5-11e7-984d-e9f32b5872d7.png)

**Comment by atoader** [comment]
You should be able to use this: https://msdn.microsoft.com/en-us/dynamics-nav/developer/devenv-al-formatter in the next update. 
Please let us know if you encounter any issues with it.

**Comment by DanielGoehler** [comment]
Will it be possible to format all .al-Files after converting via txt2al?
