### ISSUE TITLE
Object identifier limitation of 30 characters - revise?

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#946]
Having object identifier limitation of 30 characters might require some revisions, at least for new object types.

Currently, declaring object identifier longer than 30 characters fails for pageextension and pagecustomization, but it works fine for profile and controladdin for example.

Why not making it possible to have object names longer than 30 characters for pageextension and pagecustomization, or perhaps for all other object types as well?

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We added it to our backlog (specifically pageextension and pagecustomization)

**Comment by pborring** [comment]
I am going to close this old feedback item as this is already tracked in high voted ideas for objects and field
https://experience.dynamics.com/ideas/idea/?ideaid=7dce671b-7802-ea11-b862-0003ff68edfa
https://experience.dynamics.com/ideas/idea/?ideaid=1e7c245f-e232-ea11-8454-0003ff689747

I agree on the value of this, but it is a very large effort, with breaking change impact, and it currently not in the near term plans
