### ISSUE TITLE
SelectionFilterManagement - GetSelectionFilter

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#947]
Please make GetSelectionFilter in CU46 public and External.

I cannot see any logical reason to limit the function to local execution only.

**Comment by tejabalusu** [comment]
Please make this Code Unit more generic so that every list page or any table can access filtering. (Now we noticed the functions are available only for master list pages.


![selectionfilter](https://user-images.githubusercontent.com/28556102/32887716-ecedcef8-caea-11e7-9a6f-8396b885a169.jpg)

**Comment by bachii1010** [comment]
Hi,

Yes the above is a great feature to have.
This is blocking in several places  for full eventing.

**Comment by ThomasBrodkorb** [comment]
The function we requested, GetSelectionFilter in CU46, IS gerneric already as it is getting called with the generic RecordRef type and the field ID of the filter field you want to have returned in the filter string.

I requested the availability of the SETSELECTIONFILTER as a public property of page objects in #927 already, but got denied on it as it could be added easily in pageextensions.
