### ISSUE TITLE
InDataset property

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#95]
Hi all,
Kindly guide me with the syntax of how to set a global variable's 'IncludeInDataset' property to Yes in visual studio code.

Thanks

**Comment by esbenk** [comment]
Hi Tina

The syntax is:

```
var
    [InDataSet]
    i : Integer;

```

/esben

**Comment by TinaMenezes** [comment]
Thank you @esbenk

**Comment by lvanvugt** [comment]
But is this still needed?

In the attachment an AL project that extends the Customer table with a field _Inactive_ . This field can only be changed by an action _Toggle_ added to Customer Card and List. When _Inactive_ = true,  the _Name_ field on the the page should color red based on
```
        Style = Attention;
        StyleExpr = NameStyleSet;
```
NameStyle has been defined
```
var
        //[InDataSet]
        NameStyleSet : Boolean;
```
I thought I needed **InDataSet** (as you can see), but not using it (by out commenting) it still does the 
job.
[DeactivateCustomer.zip](https://github.com/Microsoft/AL/files/1851283/DeactivateCustomer.zip)
