### ISSUE TITLE
TempBlob

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/AL#950]
As TempBlob seems to be the new File object, would it be a big deal to add another column with FileName or Desciption (Text[80] or Text[250] to the table?
Maybe also a Size field (Integer)?

**Comment by StanislawStempin** [comment]
Thanks for the suggestion. We will consider making that change

**Comment by ThomasBrodkorb** [comment]
Does this mean it will not come ?

**Comment by pborring** [comment]
Closing this old suggestion, TempBLOB obsoleted. Use, e.g., BLOB Storage module in the System Application instead.

**Comment by ThomasBrodkorb** [comment]
Thanks for ignoring!

The same issue exists in the new BLOB Storage module.

Even though the Length (Size) was added, filename and/or description are still not available.
It is great tactics to ignore issues until the code - which has the issue - is replaced by some other code with the same shortcoming.

**Comment by pborring** [comment]
Well, this GitHub only tracks bugs in the AL Language and VSC VSIX. In general, https://aka.ms/bcideas is used to track new suggestions.

Currently there are not plans to add this capability to BLOB Storage. However, you can suggest these changrs yourself by creating an issue in the open source GitHub for the base and system apps, and once approved, create a PR
https://github.com/microsoft/BCApps/blob/main/CONTRIBUTING.md

**Comment by ThomasBrodkorb** [comment]
Well, not in 2017 when this thread started,
