### ISSUE TITLE
Passing Data to ControlAddin wont deploy

### ISSUE THREAD

**Issue by faludigabor** [Microsoft/AL#953]
Hi , 

I was just playing around w/ the controladdin feature and I get an exception i would like to call a JS method .  Is it me ? 

**here is the AL code** . 
controladdin TestAddIn
{
    
    Scripts = 'js/main.js';
    StartupScript = 'js/startup.js';
    event DemoEvent(prop1 : text[100]);

    **event getCustomerName(Name : text[100]);**
}

**page 50300 PageWithAddIn**
{
    SourceTable = "Customer";
   
    
    layout
    {
        area(Content)
        {
            field(Name; Name) {
             trigger OnValidate();
             begin
                **CurrPage.ControlName.getCustomerName(Name);**
             end;
            }
            usercontrol(ControlName; TestAddIn)
            {
                

                trigger DemoEvent(prop1:text[100])
                begin   
                    Message(prop1);
                end;
            }
        }
    }
 
}

**and the JS code :** 
function OnButtonClicked() {
    var i = 1;
    alert('Clicked from JS');
    PassDataToNAV(new Date());

}

function PassDataToNAV(data){
    Microsoft.Dynamics.NAV.InvokeExtensibilityMethod('DemoEvent', [data]);
}

**function getCustomerName(CustomerName){
    alert('Data from NAV: ' + CustomerName);
}** 

**Exception received:** 

[2017-11-18 10:11:29.93] The request for path /nav/dev/apps failed with code InternalServerError. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Page\Group120feac9f17dd9a6723bea7019c91ec7_Page50300.cs(271,17) : error CS0012: The type 'Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.IEntityBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.ActiveDirectory.GraphClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\MicrosoftDynamicsNavServer$NAV\source\Page\Group120feac9f17dd9a6723bea7019c91ec7_Page50300.cs(271,56) : error CS1061: 'Microsoft.Dynamics.Nav.Runtime.NavDotNet' does not contain a definition for 'Invoke' and no extension method 'Invoke' accepting a first argument of type 'Microsoft.Dynamics.Nav.Runtime.NavDotNet' could be found (are you missing a using directive or an assembly reference?)

thanks,
gabor

**Comment by ajkauffmann** [comment]
Change the line in the controladdin

`event getCustomerName(Name : text[100]);`

to

`procedure getCustomerName(Name : text[100]);`

You controladdin code then looks like:

```
controladdin TestAddIn
{
  Scripts = 'js/main.js';
  StartupScript = 'js/startup.js';
  event DemoEvent(prop1 : text[100]);
  procedure getCustomerName(Name : text[100]);
}
```

**Comment by faludigabor** [comment]
Yes indeed that was me :) thanks !

**Comment by dennisfrostlander** [comment]
`CurrPage.ControlName.getCustomerName(Name)` should not even compile if getCustomerName is declared as an event. We'll add the missing validation.
