### ISSUE TITLE
Error while downloading symbols in VS code in NAV Developer preview November update

### ISSUE THREAD

**Issue by TinaMenezes** [Microsoft/AL#957]
Hi all,
I am getting an error on downloading symbols in VS code November update. It is asking me to login. I am entering 'admin' as username and my password. But an error comes up and the symbols aren't downloaded. Kindly suggest a solution. The error screenshot is attached below. Thanks.
![image](https://user-images.githubusercontent.com/24891208/33001223-75037db2-cdd2-11e7-8af5-98445554706b.png)

**Comment by johndcollins** [comment]
If you look at your error you can kinda tell that you didn’t fill in your instance correctly.

Https://<vmname>.<azureregion>.cloudapp.azure.com is not going to be a valid address.

**Comment by TinaMenezes** [comment]
Hi,
Can you please give me details on where do we need to put our instance name? I have not manually entered it anywhere. I just installed VS code from the start page and opened the Hello World program which is already existing. But when I publish it I get this error.

**Comment by MikeGlue** [comment]
Look in the launch.json file.

**Comment by johndcollins** [comment]
If you look at the wiki page (https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions) it should give you all the details you need.

In there you will find a getting started link to how to get started (https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-get-started)

Let me know if you have any more questions.

**Comment by Gallimathias** [comment]
John Collins has actually said everything important. You will probably not have configured launch.json correctly. It should look like this
````JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "https://example.westeurope.cloudapp.azure.com",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22
        }
    ]
}
````

**Comment by KristofKlein** [comment]
I have a small question here on this one as well: Installed fine the navpreview Azure Image. Docker running, VSCode can also connect to the Docker Image after applying the provided setup from the landing page to the lunch.json. Now my question here is. If I run a second Docker Image - what is the connecting Server ?! it can't be the original one. so I have to use somehow the docket Container name (if so i can not get the Symbols due to several errors). So the VM must have a setup that allows the Traffic to go through it and points to a dedicated docker image. Where is that?! Or: how do I get VSCode to connect to an alternative Docker Image [Docker Container done via New-CSideDevContainer -accept_eula -doNotExportObjectsToText -containerName MyNewContainer]? 
If I try "server": "https://MyNewContainer", i get: 
```
Error: An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a send.
The handshake failed due to an unexpected packet format.
```
If I try the IP I get:
```
 [2017-11-22 11:58:36.07] Sending request to http://172.18.233.197:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2017-11-22 11:58:36.09] Sending request to http://172.18.233.197:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-11-22 11:58:36.09] The request for path /NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0 failed with code Unauthorized. Reason: Unauthorized
[2017-11-22 11:58:36.10] The request for path /NAV/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0 failed with code Unauthorized. Reason: Unauthorized
```
and it keeps me asking user and pswd again and again.

Some help would be nice :)

**Comment by freddydk** [comment]
I am not sure why you would want to run 2 containers for extensions v2 development in the same azure VM, but if you want to do that, yoiu need to:
- open endpoints on the Azure VM for VSCode and WebClient (f.ex. 7149 and 444)
- open the ports in the firewall
- create the container with navuserpassword authentication (-e auth NavUserPassword), ports published on the new ports (-p 7149:7049 -p 444:443), tell the container which webclientport is the public (-e publicWebClientPort=444).

What you did above was to create a container inside the VM which is not accessible to the world. You can probably access it from VSCOde inside the container. Use Docker Logs containername to get the logs, where the dev. server url can be found - but it is probably just http (default when using windows auth).

**Comment by TinaMenezes** [comment]
Hi all,
My issue has been solved. I had to change my server key  in launch.json file which has to contain my vmname and azureregion. After doing this change, the symbols were downloaded successfully with admin as username. Thank you all.
