### ISSUE TITLE
The type or method DeleteServerFile cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by auribev1** [Microsoft/AL#959]
Hello, I'm trying to rewrite some Control Add-ins from NAV 2016 to AL, But it doesn't let me use DeleteServerFile, anyone knows what could I do ?

Thanks

**Comment by Skordas** [comment]
File handling is not (or very partially) supported. You have to refactor your code to use streams for communication. Creating files must be done in azure functions, if neccessary. The only functions i found so far that are useable from codeunit File Management are UploadFileSilent (which indeed creates a server temp file that can't be deleted anymore) and DownloadTempFile (which adresses a server temp file that can't be created by AL permissions anymore).

**Comment by StanislawStempin** [comment]
@Skordas is right. I updated the FAQ with an entry about blocked FILE APIs.
