### ISSUE TITLE
Add XMLText to XMLElement

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#961]
Hi everyone,

I want to create a new xml Document and I have some problems to add my values to my xml Elements / Nodes. How can I add a text value to my Node / Element? 

I receive an error message when I try to convert the XMLElement to XMLText.

**XML Example**
`<?xml version="1.0" encoding="UTF-8"  ?>`
`<root release="2.1">`
`    <FirstName>Max</FirstName>`
`    <Surname>Mustermann</Surname>`
`</root>`

**Code example (whats wrong?)**
`// Create XML Document` 
`xmlDoc := XmlDocument.Create;` 
`xmlDec := xmlDeclaration.Create('1.0','UTF-8','');` 
`xmlDoc.SetDeclaration(xmlDec);`

`// Root Element` 
`CurrElement := XmlElement.Create('root');` 
`CurrElement.SetAttribute('release','2.1');`

`// First Name Element` 
`NewChildElement := XmlElement.Create(NodeName,NameSpace);` 
`XMLChildNode := NewChildElement.AsXmlNode;` 
`XMLChildText := XMLChildNode.AsXmlText;`  **Error: Unable to convert XMLElement to XMLText**
`XMLChildText.Value := 'Max';` 
`XMLChildNode := XMLChildText.AsXmlNode;` 

`// Surname Element`
`Code like above`

`// Add Element / Node FirstName to Root` 
`CurrElement.Add(XMLChildNode);`

`// Finish XML Document` 
`xmlDoc.Add(CurrElement);`

Can anyone help here to create the xml file?

**Comment by Skordas** [comment]
```
    procedure SetNodeText(Node : XmlNode;Txt : Text);
    begin
        Node.AsXmlElement.Add(XmlText.Create(Txt));
    end;

```
