### ISSUE TITLE
Publish command does not use port number from server url

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#963]
Consider these settings in the launch.json:

```
"server": "https://mynav.westeurope.cloudapp.azure.com:444/",
"serverInstance": "NAV",
"port": 7149,

```
Download symbols and publishing app works on port 7149. But after publishing, VS Code launches the url without the specified portnumber 444.

**Comment by DominikDitoIvosevic** [comment]
@ajkauffmann could you describe what is your scenario? You want one port for symbols and other for publishing?

**Comment by ajkauffmann** [comment]
Just found out that I had a wrong assumption. Freddy told me how it works.

My assumption was that the port number in the server url was used by VS Code to launch the browser. But apparently, that is not the case.
 
I published the web client on port 444, but I forgot to tell the nav server that it's public port number for the web client was changed. The server url from launch.json is only used to connect to the nav server. The nav server replies with the port number for the web client.
