### ISSUE TITLE
Flowfields always editable, if field Editable property not set in page

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#965]
If you add a flowfield to page, then even if the Field Editable property is set to False, then the field remains editable in the page. Only way to avoid it, is to also set the field editable in the page.

How to do again?
1) Create a flowfield in a table. I tried with both lookup and count. Set the field as Editable=false;
2) Insert the field in a card page. 
3) Run and edit the field.

I'm using AL 0.11.14434 / 11.0.19101.0-findk

**Comment by StanislawStempin** [comment]
Thanks. We will investigate

**Comment by kalberes** [comment]
This is a bug, The immediate workaround is to set the editable property on the flowfield backing control on the page to false.
