### ISSUE TITLE
Converting Delta files with txt2AL converter

### ISSUE THREAD

**Issue by doughton** [Microsoft/AL#966]
Any chance of getting the txt2AL converter to be updated to reflect the capabilities that exist in Extensions v2 that are different from Extensions v1?  

Procedures added to existing tables(previously not allowed in Extensions v1) are allowed in Extensions v2.  To allow for a seamless transition, one could rewrite the code to move the procedure to a codeunit and then move it back after the conversion -  or convert without the procedure and copy / paste from the delta files procedure by procedure.  

Seems like a little extra effort on the converter could make the transition from delta files to AL much more seamless.

Dan  

ps. Freddy may or may not have influenced my decision to post this.

**Comment by StanislawStempin** [comment]
You're right. We should not apply V1 limitations to the .delta file conversions. We will look into enhancing the txt2al for these cases.

**Comment by StanislawStempin** [comment]
The supported for this scenario has been implemented since. Please open a new issue if you're still encountering any shortcomings in the txt2al tool.
Please remember to apply the exportToNewSyntax parameter when using the Compare-NavApplicationObject cmdlet to generate proper .delta files.
