### ISSUE TITLE
XML Document WriteTo Exception

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#969]
Hi everyone,

I try to create a xml structure and to export this as xml File.
I reveice an error message when I try to write the xmlDocument to OutStream. 
Do I have to initialie the stream?

**Error Message**
Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException' was thrown.

**Example**
`// Save and write xml File to Outstream`
`xmlDoc.WriteTo(NVOutStream);` --> Error message is thrown. 
`CopyStream(NVOutStream,NVInStream);`
`// Download xml file`
`File.DownloadFromStream(NVInStream,'Export','','',DownloadName);`

**Comment by jiwanovski87** [comment]
When I add a text variable to the function xml.doc.WriteTo it is okay.
I get this error message only when I try to write the xml file to stream.

**Full example**
`xmlDoc := xmlDocument.Create();`
`xmlDec := xmlDeclaration.Create('1.0','UTF-8','');`
`xmlDoc.SetDeclaration(xmlDec);`

`xmlElem := xmlElement.Create('root');`
`xmlElem.SetAttribute('release','2.1');`

`xmlElem2 := XmlElement.Create('FirstName');`
`xmlElem2.Add(xmlText.Create('Max'));`

`xmlElem.Add(xmlElem2);`
`xmlDoc.Add(xmlElem);`

`xmlDoc.WriteTo(xmlString);`

`xmlDoc.WriteTo(NVOutstream);`
`CopyStream(nvoutstream,nvinstream);`
`FIle.DownloadFromStream(NVInStream,'Export','','',Downloadname);`

**Comment by Skordas** [comment]
yes, a stream memory position needs to be identified, first. In your case, it looks like you want to save a xml file on client

```
Document.WriteTo(DocumentText);
TempBlob.Blob.CreateInStream(InStr);
TempBlob.WriteAsText(DocumentText,TextEncoding::UTF8);
DownloadFromStream(InStr,'Window Title','','*.xml|*.XML',ClientFileName)
```

**Comment by jiwanovski87** [comment]
Okay this seem to work.
But for me it is still a bug that we cannot use the WritoTo command with a stream directly.

**Comment by atoader** [comment]
Hi @jiwanovski87 ! Here is a full example:
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        xmlDoc: XmlDocument;
        xmlDec: XmlDeclaration;
        xmlElem: XmlElement;
        xmlElem2: XmlElement;
        TempBlob: Record TempBlob;
        outStr: OutStream;
        inStr: InStream;
        TempFile: File;
        fileName: Text;
    begin
        xmlDoc := xmlDocument.Create();
        xmlDec := xmlDeclaration.Create('1.0', 'UTF-8', '');
        xmlDoc.SetDeclaration(xmlDec);

        xmlElem := xmlElement.Create('root');
        xmlElem.SetAttribute('release', '2.1');

        xmlElem2 := XmlElement.Create('FirstName');
        xmlElem2.Add(xmlText.Create('Max'));

        xmlElem.Add(xmlElem2);
        xmlDoc.Add(xmlElem);

        // Create an out stream from the blob, notice the encoding.
        TempBlob.Blob.CreateOutStream(outStr, TextEncoding::UTF8);
        // Write the contents of the doc to the stream
        xmlDoc.WriteTo(outStr);
         // From the same blob, that now contains the xml document, create an instr
        TempBlob.Blob.CreateInStream(inStr, TextEncoding::UTF8);

        // Save the data of the InStream as a file.
        File.DownloadFromStream(inStr, 'Export', '', '', fileName);
    end;
}
```

We know this is not ideal and we are considering to improve the experience of working with Streams in the future. We will update the docs with a similar example.
