### ISSUE TITLE
ApplicationArea and UsageCategory properties of page

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#970]
Dear colleagues, on NavTechDays 2017 you show how to add page to Search area - by adding this properties to page:
UsageCategory = Administration;
ApplicationArea = Basic, Suite;

But there are no such properties in my vscode for page. And in docs also written that this property could be added to fields an page parts only. 

![image](https://user-images.githubusercontent.com/33904099/33135493-940bce84-cfb3-11e7-8916-cdb264aa20e4.png)

![image](https://user-images.githubusercontent.com/33904099/33135456-7b9a6f18-cfb3-11e7-9e4d-64a1b277746e.png)

![image](https://user-images.githubusercontent.com/33904099/33135739-4c81b3ca-cfb4-11e7-91e6-0222ba9bb762.png)

**Comment by MikeGlue** [comment]
Don't think this feature is planned until the next update (December).

**Comment by StanislawStempin** [comment]
MIke is right, this is coming soon with the December Update and NAV 2018

**Comment by hgnamvn** [comment]
Hi All,

As MS mention at [December Update](https://blogs.msdn.microsoft.com/nav/2017/12/06/nav-development-preview-december-update/)
I tested these properties on December Update. But They is not effect.
Please check again for me.
     ![image](https://user-images.githubusercontent.com/24407031/33824563-69c21d76-de91-11e7-9c44-ba983e02c183.png)

![image](https://user-images.githubusercontent.com/24407031/33824647-ad8d9472-de91-11e7-909c-ac28384a2d4a.png)

**_Version Update:_** W1 11.0 (19585)

**Comment by lvanvugt** [comment]
Today I was trying the same on NAV 2018 RTM and also there the issue exists. Haven't had the opportunity to get CU1 installed.

**Comment by ABaludin** [comment]
@hgnamvn I've got such situation couple of days ago. I send an *.app file to my colleague for testing and after publishing and installation Search window shows nothing. It was because of Cronus demo license on database (new installed). After development license uploading and NAV instance restart - everything works well.

**Comment by hgnamvn** [comment]
Hi!

Please reference at [Issue with UsageCategory](https://github.com/Microsoft/AL/issues/1166)

**Comment by finn777** [comment]
After a few minutes delay... search works fine in my case. I did not change anything ( relogin to microsoft-sandbox only)
![image](https://user-images.githubusercontent.com/16433990/36259245-ac311732-126e-11e8-9abb-afea17e05ee9.png)
