### ISSUE TITLE
Web Client Crash Attempting to Query.READ Query that References TableExtension Fields

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#972]
I had a query that referenced a standard table and included both standard fields and fields added by a tableextension object. In this case it was Customer joined to Cust. Ledger Entry and Contact table. A tableextension was used to add fields to the Contact table.

Calls to Query.SETRANGE were executed, but when Query.READ was hit the session crashsed on the web client ("Sorry, that didn't work...an error has occurred").

Removing the references to the new fields has worked around the problem for now.

**Comment by StanislawStempin** [comment]
Thanks for reporting. We will look into it.

**Comment by cmrudolph-msft** [comment]
Following up on old open issues - is this still a problem? I put together a scenario that was as close to the one described and cannot find any problems.

If it is a problem, can you please attach a small repro app or code file?
