### ISSUE TITLE
Launch.json to Dynamics 365 Sandbox?

### ISSUE THREAD

**Issue by dmaxwe11** [Microsoft/AL#973]
See next comment...

**Comment by dmaxwe11** [comment]
We are just getting started.  We have some skills now on the 365 sandbox, but want to use VBC to make extensions with it.  Is this possible?  I'm stuck on the parameters I'd use on the launch.json file.

			"type": "al",
			"request": "launch",
			"name": "??",
			"server": "https://xxxxxxx-sandbox.financials.dynamics.com",
			"serverInstance": "??",
			"tenant": "default",
			"authentication": "Windows",
			"startupObjectId": 22

**Comment by StanislawStempin** [comment]
What do you mean by VBC?

**Comment by dmaxwe11** [comment]
Visual Studio Code

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by StanislawStempin** [comment]
Could you try closely following the steps listed on the Getting Started documentation page:
https://docs.microsoft.com/da-dk/dynamics-nav/developer/devenv-develop-apps-for-fin

If you select deployment option "Microsoft Cloud Sandobx" a correct launch.json will automatically be created for you.
