### ISSUE TITLE
Clear report before run it.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#974]
Hi!

I create a new report. In my report, I will update data using the processingonly report.
But I can't run the processingonly report 2 times.
![image](https://user-images.githubusercontent.com/24407031/33156878-7ddb53b4-d030-11e7-8512-b9d4173bd56b.png)

When the processingonly report run second times, the error is shown as below:
![image](https://user-images.githubusercontent.com/24407031/33156890-975b4f38-d030-11e7-8c20-36b71ee003a1.png)

I already clear report variable, but system still show error.

**Please help me solve this issues.
Version: November Update**

**Comment by epernst** [comment]
Is the procedure UpdateCFSEntries in the same report as the report no. 50000 you are calling? 
Or do you call it from a different report object?

**Comment by tatnorther** [comment]
what about using runmodal?
or as a test, create another variable for the same report

**Comment by hgnamvn** [comment]
I run report ID 50001.
From Report 50001, I create  function UpdateCFSEntries to call report ID 50000 to update some data before I run report 50001.

**Comment by hgnamvn** [comment]
Hi tatnorther,

I also solve my case by create new variable for the same report. 
But I think this case should be solved, maybe we catch this case many in the future.

**Comment by esbenk** [comment]
Is this converted code or new code? It will help us to know if this is caused by a change in compiler behavior or because of a bug in the runtime.

**Comment by hgnamvn** [comment]
Hi esbenk,

Report 50000 and 50001 are converted from NAV 2017. However, the function UpdateCFSEntries (on Report 50001) is written directly on Visual Studio Code.

**Comment by darench** [comment]
I have a similar situation. I created an Action in a new page that runs a processing only report to populate data in the page. The first time the action works fine, any subsequent time the action is called I get he same error:
_The object has been run. Use the function CLEAR(Report)._

As you can see from the screenshot, the CLEAR function is used just prior.
![image](https://user-images.githubusercontent.com/33038024/34223192-a67f87d0-e57b-11e7-8069-5829893002b1.png)
