### ISSUE TITLE
Lookup isn't effect on Request page of report.

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#975]
Hi.

This is my case.
1. I export report 94-Close Income Statement to txt, convert to AL.
2. I create new report with 2 parameter (GenJnl Template and Batch), implement as report at step 1.
![image](https://user-images.githubusercontent.com/24407031/33157526-42ce222e-d035-11e7-9965-2fb2b4ace2e4.png)

3. I run report to test. After I select batch from "Gen. Journal Batch" Page, the value isn't shown on request page for that parameter. The message show correct value. I also EXIT(TRUE) for the lookup trigger.
![image](https://user-images.githubusercontent.com/24407031/33157628-f00bcf18-d035-11e7-9273-41e687376ce3.png)

![image](https://user-images.githubusercontent.com/24407031/33157652-13e0dc26-d036-11e7-8232-83e38eeb8864.png)

**Please show me where I'm wrong or this is a bug.
Version: November Update**

**Comment by DominikDitoIvosevic** [comment]
Hi @hgnamvn ! Could you please try and set the properties on the field Visible=true; Enabled=true; and check if you have the right ApplicationArea (maybe add "All" just in case).

Otherwise, could you please try and get a smaller repro so that we know what to look for?
Also, could you please post the source code causing the issue (not just the picture)?

Thanks!

**Comment by hgnamvn** [comment]
Hi!

I tested again, but the result is the same.

This is my AL code: [https://github.com/hgnamvn/LookupTEST]( https://github.com/hgnamvn/LookupTEST)

**Comment by epernst** [comment]
Hi hgnamvn,
This is nothing new regarding AL. If you add fields to request pages, then you need to either add lookup pageid or code the onLookup trigger. It will not work just setting a source field with a table relation.

It's "always" been like that.  :)

**Comment by hgnamvn** [comment]
Thank All!

My issue is solved. I also update lookupTEST again.
