### ISSUE TITLE
Error while downloading symbols in VS code in NAV Developer preview from docker

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#978]
Hi I keep getting a SSL error when downloading the symbols.

Here is what I do:
I started the docker developers preview: 
![image](https://user-images.githubusercontent.com/33752561/33173083-008ae884-d053-11e7-877e-54971e73ae73.png)

I downloaded the al-0.11.14434.vsix file and installed it in the Visual Studio Code Editor.
![image](https://user-images.githubusercontent.com/33752561/33173197-81a61da8-d053-11e7-83b4-728a1bc6124d.png)

I update the server name with the one fromthe docker image:
![image](https://user-images.githubusercontent.com/33752561/33183240-575f1fda-d077-11e7-8b90-e16c0c38c6d1.png)

When I click the AL:Download I authenticate with admin and the password and then get the following error:
![image](https://user-images.githubusercontent.com/33752561/33173590-f67b32de-d054-11e7-883d-251163ddb1de.png)

I even tried to download the certificate from: http://8fb709a0b2c9:8080/certificate.cer and install it, but that does not work either.

What am I doing wrong?

Peik

**Comment by peikba** [comment]
Sorry the third picture should be:
![image](https://user-images.githubusercontent.com/33752561/33173692-6371d85c-d055-11e7-9549-8d7bf2692af9.png)

**Comment by peikba** [comment]
BTW my operating system is Windows 10 Enterprise 2016 LTSB

**Comment by peikba** [comment]
I Just tried it on a Windows Server 2016.
I got the same error.

**Comment by peikba** [comment]
Solved it myself.
I installed the certificate in the "Trusted Root Certification Authorities" and now the symbols can be downloaded.

However, then I try to Debúg the program, I get a new error:
![image](https://user-images.githubusercontent.com/33752561/33206516-cd4ac242-d10a-11e7-9a04-ca5cacbfe7c7.png)
Which is not very descriptive

**Comment by DominikDitoIvosevic** [comment]
does the file exist on that location?

**Comment by peikba** [comment]
No the problem is that it does not create the file.
Is there a log somewhere telling what it does?

**Comment by StanislawStempin** [comment]
Did the compilation succeed?  Try Ctrl + Shift + B first to just build the package.

**Comment by peikba** [comment]
It only gives me this:
![image](https://user-images.githubusercontent.com/33752561/33212194-390c3a8a-d122-11e7-8d4b-ecf029ee6382.png)

**Comment by StanislawStempin** [comment]
Can you confirm that the AL Language extension is active when you're invoking the build task? You should see "AL" in the bottom right corner.

AL Language extensions get activated either when opening a folder that contains app.json and .al files.

**Comment by peikba** [comment]
The AL is active when I am in the.al file 
JSON on the app.json file

**Comment by peikba** [comment]
I don't know if it means anything, but when I logon to the server, the log shows this error:

TimeGenerated : 11/25/2017 7:50:01 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: Runtime
                ClientSessionId: d2f8c5b7-3f7c-4e38-aae3-63542e513ca8
                ClientActivityId: dd977e3c-92f5-4112-9619-163bb7aa3517
                ServerSessionUniqueId: 1f182c12-094b-4bb3-8dde-1086cc6e41e1
                ServerActivityId: 2130d555-ba66-4e1c-8977-c35dc5c105b8
                EventTime: 11/25/2017 18:50:01
                Message <ii>(NavConfigurationException):
                <ii>Konfigurationsindstillingen AzureActiveDirectoryClientId
                har en værdi, der ikke er gyldig.
                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.Valid
                ateServerAadConfiguration(Boolean& hasCertificate, String&
                clientId)
                   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.Acqui
                reTokenFromCache(String resourceName)
                   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Cat
                ch(Func`1 action)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Tra
                ceException(Exception exception)
                   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Cat
                ch(Func`1 action)
                   at System.RuntimeMethodHandle.InvokeMethod(Object target,
                Object[] arguments, Signature sig, Boolean constructor)
                   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(
                Object obj, Object[] parameters, Object[] arguments)
                   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj,
                BindingFlags invokeAttr, Binder binder, Object[] parameters,
                CultureInfo culture)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavDotNet.Invoke[T](String
                methodName, UInt32 methodIndex, BindingFlags flags,
                ParameterModifier modifier, Type[] referenceTypes, Object[]
                arguments)
                   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokeMethod[T](
                Boolean isStatic, String methodName, UInt32 methodIndex,
                Object[] arguments)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6303.A
                cquireTokenFromCache_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6303.A
                cquireTokenFromCache(NavText resourceName)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6300.A
                cquireToken_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6300.A
                cquireToken(NavText resourceName, ByRef`1 accessToken)
                   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBase.T
                ryInvoke(Action method)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6300.G
                etAccessToken_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6300.G
                etAccessToken(NavText resourceUrl, NavText resourceName,
                Boolean showDialog)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6301.I
                sUserReadyForPowerBI_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6301.I
                sUserReadyForPowerBI()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6301.O
                nInvoke(Int32 memberId, Object[] args)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Page6303.LoadP
                art_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at
                Microsoft.Dynamics.Nav.BusinessApplication.Page6303.LoadPart()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Page6303.TryLo
                adPart()
                   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBase.T
                ryInvoke(Action method)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Page6303.OnOpe
                nPage_Scope.OnRun()
                   at Filter.InvokeWithFilter(NavMethodScope )
                   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                   at Microsoft.Dynamics.Nav.BusinessApplication.Page6303.OnOpe
                nPage()
                   at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
                   at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
                   at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRegi
                strateDataAccess(FormOpenResponse openResponse)
                   at
                Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession
                session)
                   at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFor
                mRequest form)
                   at SyncInvokeOpenForm(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Ru
                nInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                ansientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pu
                shPopCombinator(ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                aceScopeCombinator(Category telemetryCategory,
                ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pe
                rformanceCounterCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                itClientTelemetryIdsCombinator(ServiceOperation
                innerOperation, NSServiceBase serviceInstance, MethodBase
                syncMethod, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tl
                sClearCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                voke(Object instance, Object[] inputs, Object[]& outputs)
                   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.I
                nvokeBegin(MessageRpc& rpc)
                   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.P
                rocessMessage5(MessageRpc& rpc)
                   at
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean
                isOperationContextSet)
                   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(
                Boolean& alreadyResumedNoLock)
                   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProce
                ssing(IResumeMessageRpc resume)
                   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.
                <>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Obje
                ct state)
                   at
                System.Threading.ExecutionContext.RunInternal(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.QueueUserWorkItemCallback.System.Threadi
                ng.IThreadPoolWorkItem.ExecuteWorkItem()
                   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                </ii></ii>
                ProcessId: 2812
                Tag: 00000CY
                ThreadId: 10
                CounterInformation:

**Comment by peikba** [comment]
I Just created a new Developers Preview machine on Azure and I get the same error there.
It all worked on the September release.
What am I missing?

**Comment by StanislawStempin** [comment]
What exactly fails for you?  
The error that you see in the Event Log is not related and will not cause any functionality to fail.

**Comment by peikba** [comment]
The only message I get is, that the file does not exist.

Nothing else.

Sendt fra min iPad

**Comment by peikba** [comment]
I can give you access to the development preview machine on Azure.
There you can see the error yourself.

/Peik

Sendt fra min iPad
