### ISSUE TITLE
Receiving error when initializing new developer experience as of 02162017

### ISSUE THREAD

**Issue by doctorpartlow** [Microsoft/AL#98]
was working fine the 15th. not sure what happened but the extension in vs code is no longer available.

<font color="Green">2:48:36 PM New Developer Experience Installation succeeded</font>
<font color="Gray">2:57:22 PM Read Settings</font>
<font color="Gray">2:57:23 PM Import Modules</font>
<font color="Gray">2:57:23 PM Downloading Visual Studio Code Setup Program</font>
<font color="Gray">2:57:26 PM Installing Visual Studio Code</font>
<font color="Gray">2:58:42 PM Remove and add http binding for local access using Windows Auth</font>
<font color="Gray">2:58:43 PM Setup NetTcpPortSharing</font>
<font color="Gray">2:58:45 PM Create Developer Service Tier</font>
<font color="Gray">2:58:46 PM Download samples</font>
<font color="Gray">2:58:47 PM install vsix</font>
<font color="Gray">2:58:47 PM C:\DEMO\New Developer Experience\al-0.2.7308.vsix</font>
<font color="Gray">2:58:50 PM WARNING: Promise with no error callback:12</font>
<font color="Gray">2:58:50 PM { exception: null,</font>
<font color="Gray">2:58:50 PM   error: [ [ [Object] ] ],</font>
<font color="Gray">2:58:50 PM   promise: </font>
<font color="Gray">2:58:50 PM    { _oncancel: null,</font>
<font color="Gray">2:58:50 PM      _nextState: null,</font>
<font color="Gray">2:58:50 PM      _state: </font>
<font color="Gray">2:58:50 PM       { name: 'error',</font>
<font color="Gray">2:58:50 PM         enter: [Function: enter],</font>
<font color="Gray">2:58:50 PM         cancel: [Function: a],</font>
<font color="Gray">2:58:50 PM         done: null,</font>
<font color="Gray">2:58:50 PM         then: null,</font>
<font color="Gray">2:58:50 PM         _completed: [Function: a],</font>
<font color="Gray">2:58:50 PM         _error: [Function: a],</font>
<font color="Gray">2:58:50 PM         _notify: [Function: m],</font>
<font color="Gray">2:58:50 PM         _progress: [Function: a],</font>
<font color="Gray">2:58:50 PM         _setCompleteValue: [Function: a],</font>
<font color="Gray">2:58:50 PM         _setErrorValue: [Function: a] },</font>
<font color="Gray">2:58:50 PM      _listeners: null,</font>
<font color="Gray">2:58:50 PM      _value: [ [Object] ],</font>
<font color="Gray">2:58:50 PM      _isException: false,</font>
<font color="Gray">2:58:50 PM      _errorId: 12,</font>
<font color="Gray">2:58:50 PM      done: [Function: done],</font>
<font color="Gray">2:58:50 PM      then: [Function: then] },</font>
<font color="Gray">2:58:50 PM   handler: undefined,</font>
<font color="Gray">2:58:50 PM   id: 12,</font>
<font color="Gray">2:58:50 PM   parent: undefined }</font>
<font color="Gray">2:58:50 PM Create Desktop Shortcuts</font>
<font color="Gray">2:58:50 PM Cleanup</font>
<font color="Gray">2:58:50 PM Start VS Code with the Hello World app</font>
<font color="Green">2:58:50 PM New Developer Experience Installation succeeded</font>

**Comment by StanislawStempin** [comment]
Does it work if you create a new VM from the official link aka.ms/navdeveloperpreview?

**Comment by doctorpartlow** [comment]
yep that works. thanks.
