### ISSUE TITLE
Suggestion: txt2al.exe: TableRelations Indentation

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#982]
It would be nice if **txt2al.exe** would indent TableRelations in **Tables** better:

**C/AL-Text:**
```
 { 7   ;   ;No.                 ;Code20        ;TableRelation=IF (Type=CONST(" ")) "Standard Text"
                                                                 ELSE IF (Type=CONST("G/L Account")) "G/L Account"
                                                                 ELSE IF (Type=CONST(Item)) Item
                                                                 ELSE IF (Type=CONST(Resource)) Resource
                                                                 ELSE IF (Type=CONST("Fixed Asset")) "Fixed Asset"
                                                                 ELSE IF (Type=CONST("Charge (Item)")) "Item Charge";
```

**November Update Result:**
```
  field(7;"No.";Code[20])
    {
      TableRelation = IF (Type=CONST(" ")) "Standard Text"
ELSE IF (Type=CONST("G/L Account")) "G/L Account"
ELSE IF (Type=CONST(Item)) Item
ELSE IF (Type=CONST(Resource)) Resource
ELSE IF (Type=CONST("Fixed Asset")) "Fixed Asset"
ELSE IF (Type=CONST("Charge (Item)")) "Item Charge";
```
**Would be nice Result:**
```
  field(7;"No.";Code[20])
    {
      TableRelation = IF (Type=CONST(" ")) "Standard Text"
                      ELSE IF (Type=CONST("G/L Account")) "G/L Account"
                      ELSE IF (Type=CONST(Item)) Item
                      ELSE IF (Type=CONST(Resource)) Resource
                      ELSE IF (Type=CONST("Fixed Asset")) "Fixed Asset"
                      ELSE IF (Type=CONST("Charge (Item)")) "Item Charge";
```

**Comment by epernst** [comment]
Hi Daniel,
I saw you made a few suggestions to improve the indentation from Txt2AL. Of course the better the Txt2AL is the better. But personally I would rather that they spend time fixing the issues in AL/VSCode and the application, then spending too much time on Txt2AL. 
How it looks when it comes into AL doesn't really matter much. Just use the "Format Document" command. Then it automatically adjust all indentations as well as uppercase/lowercase changes in the new language. 
Right now you have to download Rasmus Aaen's AL Formatter VSCode extension [(https://marketplace.visualstudio.com/items?itemName=rasmus.al-formatter] - but if I didn't misunderstood the message from Microsoft at NAV Tech Days, then this would soon also be a build-in part of the AL compiler extension.

**Comment by DominikDitoIvosevic** [comment]
I agree with @epernst in that we will not be investing too much into txt2al formatting since it is a tool to be used only once and it doesn't have proper utilities for formatting. AL extension on the other hand is coming with a formatter and while I don't think we support this scenario right now we will

**Comment by StanislawStempin** [comment]
We will in general try to address all formatting issues through the Format Document functionality rather than directly in txt2al.

**Comment by epernst** [comment]
When can we expect to see your own Format Document functionality?

**Comment by StanislawStempin** [comment]
It will be available in December Update
