### ISSUE TITLE
XLIFF files handling

### ISSUE THREAD

**Issue by janhofmann24** [microsoft/AL#983]
First of all: It is great, that the translation is out of the source files!

I am wondering about the handling of these files though. If I understood correctly, the translated xlf files have to be in the Translations folder of the Extension.
Is there a way to add the translation later to the packaged Extension? 
Otherwise that would mean, that the Extension publisher has to take care of translations to all languages centrally.

**Comment by DominikDitoIvosevic** [comment]
Right now the xliff files are consumed during the packaging and end up in the metadata of the objects. I suppose we could add the ability to add them separately but it's not a small feat so we will have to see how important this is

**Comment by DominikDitoIvosevic** [comment]
The only thing extension publisher has to do is have the translated xliffs at publish time. You could delegate the translation process elsewhere and when you need to update the translations, all you need to do is republish. You could also translate in page extensions

**Comment by janhofmann24** [comment]
Would it be possible to have a dependant Extension, which adds the translation file?

I don't know how many languages exactly, but operating in more than 50 countries - amongst them China, Thailand, Korea, Japan, Russia, UAE, all of Europe - I see quite some difficulties orchestrating the translation.

**Comment by DominikDitoIvosevic** [comment]
I think you could have an extension which depends on your original extension which adds the translations. I haven't personally tested this scenario but I think it should work even now since you can customize captions. One issue would be that you cannot customize label variables so I'm afraid that is blocked for now.

Also, writing all these extensions which extend each field in the app could prove cumbersome. I suppose a small script which is using the compiler as a library to generate these extensions might be a way better solution.

**Comment by StanislawStempin** [comment]
Thank you for the input. We currently don't support adding translations for an extension in a separate extension but will consider it this scenario for our backlog.

**Comment by janhofmann24** [comment]
Okay, Thanks

**Comment by StanislawStempin** [comment]
We would like to keep this issue open for backlog tracking.

**Comment by netrpe** [comment]
Any new information concerning this issue ?

**Comment by thpeder** [comment]
Hi @janhofmann24,
Good news, we are now supporting translating other extensions.
Make a folder called Translations and place your translated xliff in there.
Docs: [Translating other extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions)

**Comment by adrian-panaite** [comment]
How can we generate the xliff file for Base Application and System Application?

**Comment by atoader** [comment]
Hi! You can extract it from the .app file by opening the .app file with 7zip or similar or you can get it from the DVD. Please open new issues for any problems you encounter using this feature.
