### ISSUE TITLE
Application Insights

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#984]
I got this question from my customer:  Is NAV2018 / Dyn365 going to support "Application Insights"?

https://azure.microsoft.com/en-us/services/application-insights/

Didn't know it, but looks interesting - so I'd like to know the answer :-).

**Comment by StanislawStempin** [comment]
We currently don't support it but plan to have some form of Insight/Telemetry capabilities available to partners in the future.

**Comment by yrest** [comment]
Thanks for the great work you do guys! As a side note to this subject...
Is it possible or are there any plans to make AL extension for VS Code available on "full visual studio" marketplace?

**Comment by StanislawStempin** [comment]
Currently we don't have plans to make AL available in the big Visual Studio.
