### ISSUE TITLE
Send E-Mails with PDF attachments in a background batch (REPORT.SAVEASPDF)

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#986]
The functions SaveAsPDF, SaveASExcel, SaveAsWord, SaveAsHtml are no longer available in extensions V2.
We need a functionallity to send mails with attachments (NAV Reports as PDF) via a background batch job.
How can we make it work?
Perhaps you can provide a function to send a mail via SMTP with an attached outstream?

**Comment by StanislawStempin** [comment]
We are currently looking into the area of sending email file attachements.

**Comment by waldo1001** [comment]
Can you tell me when this "future update" will be there?  printing-in-code is quite necessary for many extensions...

**Comment by thpeder** [comment]
We are aiming at getting the update out before the end of the year.

**Comment by ivandjordjevic** [comment]
@StanislawStempin I still have this issue on AL Language version 0.14.17461?

![image](https://user-images.githubusercontent.com/20359384/37141464-56a69d12-22b5-11e8-80f4-3e63b4cf2ab3.png)

It this yet to be delivered?

**Comment by StanislawStempin** [comment]
We should have been more clear when closing this issue. The solution provided was the second part of he original suggestion: "Perhaps you can provide a function to send a mail via SMTP with an attached outstream?"
We did exactly that, have a look at the new function COD260.EmailFileFromStream

**Comment by ivandjordjevic** [comment]
Will look into it. Thanks!
