### ISSUE TITLE
Error: Cannot implicitly convert type 'int' to 'char'. An explicit conversion exists (are you missing a cast?)

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#987]
Publishing my Extension worked fine. During the install process the following error occured in the eventlog (Attached you can find the Al-code and C#-code):

Server instance: NAV
                Category: Extensions
                ClientSessionId: 3d95dcef-338c-4e01-9eb5-292496e1e3c1
                ClientActivityId: 08cdfee5-ccf2-41ad-b18c-815fc339576d
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 11/24/2017 19:34:16
                Message <ii>(InvalidOperationException):
                <ii>c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\
                MicrosoftDynamicsNavServer$NAV\source\Codeunit\Group8ef9d416441
                27117b550809dc7d87a3e_Codeunit70107972.cs(1576,43) : error
                CS0266: Cannot implicitly convert type 'int' to 'char'. An
                explicit conversion exists (are you missing a cast?)
                c:\ProgramData\Microsoft\Microsoft Dynamics NAV\110\Server\Micr
                osoftDynamicsNavServer$NAV\source\Codeunit\Group8ef9d4164412711
                7b550809dc7d87a3e_Codeunit70107976.cs(3706,43) : error CS0266:
                Cannot implicitly convert type 'int' to 'char'. An explicit
                conversion exists (are you missing a cast?)

                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter.MakeAssembl
                y(String assemblyFileName, AssemblyBucket assemblyBucket)
                   at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter.MakeAssembl
                yAndSetClrObjects(AssemblyBucket assemblyBucket, String
                assemblyFileName)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter.MakeAssembl
                yAndSetClrObjects(AssemblyBucket assemblyBucket, String
                assemblyFileName)
                   at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter.InitializeN
                avAppGroupAssembly(NavAppGroup appGroup, PerformanceLog
                perfLog)
                   at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter.CompileNavA
                ppGroup(NavAppGroup appGroup, PerformanceLog perfLog)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roupAssembly(NavAppGroup appGroup, PerformanceLog perfLog)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roup(NavAppGroup appGroup)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roup(NavAppGroup appGroup)
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppGroupUpdater.Pr
                epareAppGroups(NavAppGroups groups, PerformanceLog
                performanceLog)
                   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.Prepare
                AllAppGroupsForInstallChain(NavAppInstallPreCheckHelper
                precheckResult, PerformanceLog outerPerfLog)
                   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.Interna
                lInstallNavApp(NavAppInstallPreCheckHelper precheckResult,
                String name, NavTenant tenant, Boolean doNotLoadData, String
                activityId, PerformanceLog outerPerfLog)
                   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.<>c__Di
                splayClass25_0.<InstallNavApp>b__1(NavTenant tenant,
                NavSession session)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynami
                cs.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSes
                sion(Action`2 action, Boolean throwExceptions, Boolean
                useCurrentCulture, Boolean allowAppsDisabledMode)
                   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.<>c__Di
                splayClass25_0.<InstallNavApp>b__0()
                   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.Install
                NavApp(InstallNavAppArguments installNavAppArguments, Boolean
                async)
                   at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__Displa
                yClass54_0.<Microsoft.Dynamics.Nav.Types.INCLAdminService.Insta
                llNavApp>b__0(NavSession session)
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.SendTraceTagOnFailure(Action operation, String
                additionalInfo, String callerName)
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSessi
                on.SendTraceTagOnFailure[T](Func`1 operation, String
                additionalInfo, String callerName)
                   at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.D
                ynamics.Nav.Types.INCLAdminService.InstallNavApp(InstallNavAppA
                rguments installNavAppArguments)
                   at SyncInvokeInstallNavApp(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pu
                shPopCombinator(ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Te
                lemetryCombinator(Category telemetryCategory, Verbosity
                telemetryVerbosity, ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass6_0.<Create>b__0(ServiceOperation operation,
                NSServiceBase instance, MethodBase syncMethodLocal, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pe
                rformanceCounterCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                itClientTelemetryIdsCombinator(ServiceOperation
                innerOperation, NSServiceBase serviceInstance, MethodBase
                syncMethod, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tl
                sClearCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                voke(Object instance, Object[] inputs, Object[]& outputs)
                   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.I
                nvokeBegin(MessageRpc& rpc)
                   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.P
                rocessMessage5(MessageRpc& rpc)
                   at
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean
                isOperationContextSet)
                   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(
                Boolean& alreadyResumedNoLock)
                   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProce
                ssing(IResumeMessageRpc resume)
                   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.
                <>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Obje
                ct state)
                   at
                System.Threading.ExecutionContext.RunInternal(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.QueueUserWorkItemCallback.System.Threadi
                ng.IThreadPoolWorkItem.ExecuteWorkItem()
                   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                </ii></ii>
                ProcessId: 3776
                Tag: 00000AG
                ThreadId: 39
                CounterInformation:
![cu70107972](https://user-images.githubusercontent.com/34025722/33270068-14f114b4-d383-11e7-89e4-9134ce581f3f.png)
![cu70107976](https://user-images.githubusercontent.com/34025722/33270069-151b7cb8-d383-11e7-8020-67c53535659f.png)

**Comment by StanislawStempin** [comment]
Thanks for reporting
