### ISSUE TITLE
Compiler complains about table "Media Set" and "Media" 

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#989]
An error occurs in VS Code, when you define a variable of Record "Media Set" or "Media":

"The type or method 'Media' cannot be used for 'Extension' development."
"The type or method 'Media Set' cannot be used for 'Extension' development."

Is there a reason for it?

**Comment by dennisfrostlander** [comment]
In multi-tenant installations, Media and Media Set tables may contain cross-tenant data, therefore extensions cannot read from them.

Could you please share more details about your scenario? Would you be able to use Tenant Media and Tenant Media Set tables instead?

P.S. You can always change the "target" property in the app.json to "Internal" to get access to Media and Media Set. But please remember that you will not be able to submit such extensions to AppSource, should you have an intention to do so.

**Comment by MaKnauer** [comment]
Thanks for the quick answer. Tenant Media Set and Tenant Media works for us.

**Comment by dennisfrostlander** [comment]
Thanks, closing then.
