### ISSUE TITLE
Inconsistent capitalization of T/F in true/false

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#99]
IntelliSense is not consistent when suggesting the keywords true and false.

When you promote an action the values are suggested with uppercase T or F:
![image](https://cloud.githubusercontent.com/assets/1166791/23126797/be1becd6-f778-11e6-89cf-50c1adb10bf7.png)

But when you try to set the Editable property of a page field, the suggestions are with lowercase t and f:
![image](https://cloud.githubusercontent.com/assets/1166791/23126950/5dd90060-f779-11e6-845d-4ad088fa63b8.png)

**Comment by kalberes** [comment]
That's a bug. We will fix it.
