### ISSUE TITLE
Please refactor the new Event OnBeforeTestBalance (...) in Codeunit 8

### ISSUE THREAD

**Issue by navlarste** [Microsoft/AL#990]
New event is placed in the wrong place.
COD8 OnBeforeTestBalance (...)
 
Problem:
- ColValue is overwritten after the event.
- The Event is in a Case statement and cannot be reached for other types than ColumnLayout. "Ledger Entry Type" :: Entries:
 
Solution:
- Place the event before the “IF TestBalance THEN BEGIN”
- Parameter ColValue and GLAccount must be changed to Property=AsVar
 
Delta file built on CTP17 W1:
[COD8.zip](https://github.com/Microsoft/AL/files/1517400/COD8.zip)

**Comment by navlarste** [comment]
I fund some more problem with the New Event OnBeforeTestBalance(…) IN Code unit 8


To parameters must be Property=AsVar
COD8 OnBeforeTestBalance (...)
 
Problem:
•	Parameter ColValue are not updated with the New value set by the event
•	Filters are lost on parameter GLAccount, it is used for calculation new values in the event.

Solution:
•	Parameter ColValue and  GLAccount must be changed to Property=AsVar

 
Delta file built on CTP17 W1:
[COD8.zip](https://github.com/Microsoft/AL/files/1517395/COD8.zip)

**Comment by AlexanderYakunin** [comment]
Can you please explain the purpose of this event, how you would like to use it? There are many places in the code which use statement “IF TestBalance THEN BEGIN”, where exactly you need this event?

**Comment by navlarste** [comment]
It is used analyzing Closing Entries in General Journals for simulation of the results before posting. So you can see wat it will be after posting. 

The function LOCAL CalcGLAcc(..) return a calculation in ColValue were I have to add what is on the General Journal and also using the same filters during the calculation.
Therefore the parameter has to be ColValue AsVar.

The event has to be place hear
  IF CalcAddCurr THEN
     ColValue := CalcLCYToACY(ColValue);
END;

===New Event===

IF TestBalance THEN BEGIN
    IF AccSchedLine.Show = AccSchedLine.Show::"When Positive Balance" THEN
