### ISSUE TITLE
Download Handler Multiple Files

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#994]
Hi everyone,

our app creates different files for an item (one xml file and one jpg file as example).
Before downloading the files, the app collects all generated files in temporary records (BLOB field). After collecting everything, the system iterate threw the temporary record and exports / downloads the BLOBs with the command DownloadFromStream. 

**The problem now is:** 
It is not possible to download two blobs in quick succession. 
The system only downloads the last BLOB I triggered with the command DownloadFromStream.

We cannot create a zip archive to reduce the number of files to download (see issue 829).

How should we handle this?

**Comment by StanislawStempin** [comment]
Issue #829 is being addressed and will allow you to create one ZIP archive. 

We will investigate this issue further. Are you getting two download dialogs? Which client are you using?

**Comment by jiwanovski87** [comment]
Hi Stanislaw,

I am using chrome and I don't get any download dialog. 
Chrome just start downloading. 

I tested this with IE too. There I get only one downloaf dialog for my last file / blob field.

**Comment by jiwanovski87** [comment]
Update:
I added an sleep between the two DownloadFromStream commands.
I still get only the last file.

**Comment by thpeder** [comment]
I'll take that as a yes.
