### ISSUE TITLE
Will the conversion tool handle OPTIONSTRING to OptionMembers

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#996]
Similar to issue 995. 

OPTIONSTRING is being replaced by OptionMembers, will the txt2al tool handle this conversion at some point?

**Comment by epernst** [comment]
It's already doing that....

**Comment by strophanthus** [comment]
Which version of the txt2al tool? I am using CTP17.

**Comment by FSharpCSharp** [comment]
the conversion is taking place, that's right. But there are problems with strings that also contain empty elements.

For example, the conversion of ",,,,Test,Test2,,Test5"did not work properly and an unpleasant number shift occurred.

**Comment by DominikDitoIvosevic** [comment]
Could you please give us a repro for this shift issue? Sounds like a bug

**Comment by FSharpCSharp** [comment]
@DominikDitoIvosevic 
Nothing could be easier!

```
OBJECT Codeunit 50002 Test Option
{
  OBJECT-PROPERTIES
  {
    Date=29.11.17;
    Time=10:37:19;
    Modified=Yes;
    Version List=;
  }
  PROPERTIES
  {
    OnRun=BEGIN
          END;

  }
  CODE
  {
    VAR
      GlobalOption@5550000 : ',,,,,Test,,Test4,,Test6';

    BEGIN
    END.
  }
}
```

This NAV object is converted using the Txt2AL tool as follows.

```
codeunit 50002 "Test Option"
{

  trigger OnRun();
  begin
  end;

  var
    GlobalOption : Option Test,,Test4,,Test6;
}
```

As you can see, the empty elements are simply cut off at the beginning. This can have rather bad consequences during development.

**Comment by DominikDitoIvosevic** [comment]
Thanks! I think I can fix this quickly

**Comment by strophanthus** [comment]
Hey, for the conversion case it is occurring in this line (CTP17): 
    "Business Number" :=
                  COPYSTR(
                    "Business No." + SELECTSTR("Program Identifier" + 1,PIFieldRef.OPTIONSTRING) + 
                  "Reference No.",1,MAXSTRLEN("Business Number"));

Which is in the OnValidate for Reference No.

**Comment by esbenk** [comment]
The FieldRef.OptionString call is not converted. The txt2al tool doesn't parse (understand) the C/AL code, only the surrounding metadata.

**Comment by strophanthus** [comment]
So this will not be handled by the txt2al tool?

**Comment by DominikDitoIvosevic** [comment]
@FSharpCSharp I have fixed your conversion case. It was our bug. @strophanthus I must admit I do not understand what you are asking. Could you provide me with what you are getting after converting and what you are expecting?

**Comment by strophanthus** [comment]
fieldref.OPTIONSTRING is not converting to fieldref.OptionMembers. Which is what this issue is about.
