### ISSUE TITLE
What happened to codeunit 80?

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#998]
Somehow then I no longer can reference directly to codeunit 80.

Intellisense does not show it:
![image](https://user-images.githubusercontent.com/5236163/33308049-387fcfec-d419-11e7-8275-85312c2c3b5f.png)

But I can use it if I reference directly to it:
![image](https://user-images.githubusercontent.com/5236163/33308089-69333886-d419-11e7-9869-7ea9e339f026.png)

The same goes for a number of other codeunits, including 90.

I'm using the CTP17 DK build on Azure. Same happens on local Docker install.

**Comment by thpeder** [comment]
Codeunit 80 has a hyphen in the middle of the name ie. it is Sales-Post, you can also see that if you use Go-To-Definition on "Codeunit 80". 
Give it a try without the space but simply writes "salespost" then you should see it.

**Comment by epernst** [comment]
Thanks. Still strange that the hyphen makes it not show up in the "search" - then it shouldn't show Sales Batch Post Mgt either.
